### ISSUE TITLE
Plus rien ne fonctionne

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1000]
Bonjour, j'ai mis à jour hier à 12h25 et plus rien ne fonctionne.
Derneire version de jeedom stable v4, dernier abeille.

J'ai remis à /Dev/ttySO, mais rien n y fait plus de communication avec mes modules ikea et xiaomi.

**Comment by KiwiHC16** [comment]
Peux tu me partager une capture d'ecran de la page configuration du plugin ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
As tu activé le port ?
As tu essayé de demarrer le demon ?

**Comment by bouboun59** [comment]
Merci de ton retour rapide, alors pour info, j'ai fait machine arrière car je bosse et je ne voulais pas pénaliser la domotique en place. Donc tout remarche en ancienne version.

Les manips que j'ai faites avant passage en arriére:
Vérification coinfig/ remis en route ttyS0, redemarrage plusieurs fois, selection du binaire, mais j'avais une erreur en mise à jour car il ne trouvait pas un fichier php.

Je vais rester ce week end car je travaille et je n'ai pas trop le temps en ce moment.
et posterai des log si cela ne fonctionne toujours pas.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-03-05 à 10 30 21](https://user-images.githubusercontent.com/8549674/75967583-52942000-5ecc-11ea-90ad-679f67b65b7d.png)

Je viens de tester avec une Zigate serie et cela fonctionne. Je n'ai pas de Zigate Wifi dispo pour le test. Je vais essayer dans trouver une pour tester.

**Comment by KiwiHC16** [comment]
Effectivement j'ai le meme comportement sur ma prod si je mets le port 1 en Wifi.

**Comment by KiwiHC16** [comment]
Peut etre un lien avec #996.

Est ce un PiZigate ?

**Comment by bouboun59** [comment]
Oui c'est un PiZiGate

**Comment by bouboun59** [comment]
j'ai restest ce soir vite fait, cela ne fonctionne toujours pas.
Install du plugin config sur port TTYS0 car perte de config
test -> KO
reboot jeedom -> TEST - > KO
j'ai des logs si tu souhaites par mail.
![image](https://user-images.githubusercontent.com/46579815/76012824-3e294500-5f17-11ea-80b6-09e244657e60.png)
![image](https://user-images.githubusercontent.com/46579815/76012840-43868f80-5f17-11ea-811c-a1877edcce4a.png)


``

**Comment by KiwiHC16** [comment]
Ok, il y a deux sujets d'apres ta capture d'écran.
Commencont par le ttyS0. Peux tu me dire si la led bleue sur la PiZigate est fortement ou faiblement allumée ?
Peux tu aussi faire en ssh:
`ls -l /dev/tty*`

**Comment by bouboun59** [comment]
Cela re-fonctionne, car il fallait prendre AMA0 et pas ttyS0, j'ai regardé la config par rapport à l'ancien.
Par contre ma télécommande de groupe ne fonctionne plus.
![image](https://user-images.githubusercontent.com/46579815/76082506-dd981780-5fab-11ea-8fe7-fe8248bd9312.png)
EDIT
J'ai essayé de recréer une télécommande virtuelle, plus possible cela ne fonctionne pas pour info.

**Comment by KiwiHC16** [comment]
J'ai trouvé pour la creation des Telecommande. Je fais une correction.

**Comment by KiwiHC16** [comment]
Je viens de faire un push dans le master. Je vais essayer de tester pour voir si c est ok maintenant.

**Comment by KiwiHC16** [comment]
Ca semble ok pour les télécommandes.

**Comment by KiwiHC16** [comment]
Je clos ce sujet. La correction telecommande sera dans la prochaine version.
Si j'ai oublié un truc ouvre une autre issue avec celle ci en reference.
