### ISSUE TITLE
Dernière Version abeille 6.3.20

### ISSUE THREAD

**Issue by sneu68** [KiwiHC16/Abeille#1003]
Hello,
Merci Pour ton boulot ! Suis conquis. Depuis Novembre 2019, j'ai monté ma centrale domotique autour de Jeedom, d'abord avec le plugin de Zigate, puis rapidement passé à abeille, que je trouvais personnellement plus stable et simple d'utilisation.
Pour ma part, j’ai mis le dernier plugin abeille à jour aujourd’hui (6.3.20). J’ai bien retrouvé les équipements qui communiquaient avant, mais plus moyen de mettre la Zigate en mode inclusion. Elle ne clignote pas lorsque j’appuie sur le nouveau bouton + (qui remplace l’ancienne icone/bouton inclusion.
J’ai donc fait un restore de mon dernier backup, et tout est rentré dans l’ordre avec la version abeille de déc 2019. L’inclusion fonctionne à nouveau comme avant.
RPi4, Core 4.0.42, ZigateUSB, 18 capteurs (principalement Xiaomi)
Si tu as une piste, je suis preneur; ça m’embêterait d’avoir en permanence une notification de mise à jour affichée. Mais je peux également attendre un update prochain.
Merci !

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok. Il faudrait si possible mettre le plugin en debug. Faire la demande d inclusion. Et partager le log AbeilleCmd.
Peux tu aussi partager une capture d ecran de la page configuration du plugin ?

**Comment by sneu68** [comment]
Hello !
Je suis une nouille ! Je viens de refaire la manip pour migrer sur la dernière version.  Avec la nouvelle version, j'avais oublié de ré-associer la Zigate sur le Port USBTTY correspondant. J'étais parti du principe qu'on ne mettait que l'appli à jour. Je suis donc à jour maintenant. Et la Zigate clignote effectivement en mode inclusion.  
Seule bizarrerie, la table des noeuds affiche autre chose qu'avant. Mais ce n'est peut-être qu'une question de temps.
Sorry pour le dérangement !

**Comment by KiwiHC16** [comment]
SUper, pas de soucis. La table des noeuds est en cours de refonte suite au passage en MultiZigate.
