### ISSUE TITLE
Depuis ce post dans le forum

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#1004]
https://community.jeedom.com/t/plugin-abeille-pour-la-zigate-zigbee-fil-principal-des-news-et-discussions/2774/354
Nous avons essayer cette version 
il en resort que tout ceux qui sont en pizigate et wifizigate ne fonctionnent pas et son revenue sur des sauvegardes
a partir de ton post j'ai fait l'effort de demander a chacun sa configuration tu a donc toutes les réponses sous le post que tu a fait.

bien a toi n'hésite pas a redessendre sur le forum nous sommes tous a ton écoute.

**Comment by KiwiHC16** [comment]
Je vais prendre les cas un par un pour les résoudre.

**Comment by KiwiHC16** [comment]
#1008
Je clos celui ci et on continue dans l autre.
