### ISSUE TITLE
Systeme sneu

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1007]
> Hello,
> Pour ma part, j’ai mis le dernier plugin abeille à jour aujourd’hui (5.3.20). J’ai bien retrouvé mes équipements qui communiquent, mais plus moyen de mettre la Zigate en mode inclusion. Elle ne clignote pas lorsque j’appuie sur le nouveau bouton + (qui remplace l’ancienne icone/bouton inclusion.
> J’ai donc fait un restore de mon dernier backup, et tout est rentré dans l’ordre avec la version abeille de déc 2019. L’inclusion fonctionne à nouveau comme avant.
> RPi4, Jeedom 4.0.42.
> Si quelqu’un a une piste, je suis preneur. ça m’embêterait d’avoir en permanence une notification de mise à jour affichée.
> Merci !

**Comment by KiwiHC16** [comment]
Est ce un Zigate USB ? Wifi ? PiZigate ?

**Comment by edgd1er** [comment]
Bonjour @KiwiHC16 ,

j'ai le même problème sur mon système depuis le multi zigate et je pense avoir une piste mais pas de solution. j'ai l'impression que pour l'inclusion le type et l adresse sont inversées:

pour un get NetworkStatus, j'ai 
`` Msg sent: {"message":{"topic":"TempoCmdAbeille1\/Ruche\/getNetworkStatus&time=1583622928","payload":"getNetworkStatus"}} on queue: 123``

Topic: TempoCmdAbeille1/Ruche/getNetworkStatus

pour un include, j'ai
```
Msg sent: {"message":{"topic":"CmdRuche\/Abeille1\/SetPermit","payload":"Inclusion"}}
procmsg fct - Type: CmdRuche Address: Abeille1 avec Action: SetPermit
procmsg fct - Address != Ruche
AbeilleCommand unknown: SetPermit
```
or la fonction procmsg cherche adresse != ruche (L2598) toujours vrai  et cherche donc parmi les commandes d'abeille, en ligne 3682 on a le unknown du log.

Est ce le test de la ligne 2598 qui doit etre changé ou la définition de la ruche dans ma bdd ?
id	Name	logicalId ....
"150"	"Ruche-Abeille1"	"Abeille1/Ruche"	"2"	"Abeille"	"{""topic"":""Ruche\/Abeille1"",""type"":""topic"",""lastCommunicationTimeOut"":""-......

Est ce que du fait du multi zigate ta convention de nommage se téléscope ? De ce fait, maintenant ruche se trouve toujours après AbeilleX.

avant: abeille/devices ou ruche
après: Abeille[0-5]/(device ou Ruche)

Pour info, j'ai renommé le topic de ma ruche Ruche\/Abeille1 en Abeille1\/Ruche et l'inclusion, le getNetworkStatus et getVersion fonctionnent. Je n'avais pas eu le temps de finaliser ma fonction de renommage avant que tu ne poposes la tienne, du coup , Ma fonction avait peut-être renommé incorrectement le topic de la ruche....

bon, au final, je crois que c'est mon topic de ruche qui était faux, peux tu me confirmer que c'est bien Abeille\/Ruche (topic) et que le logicalId de la ruche sur le port 1 est bien Abeille1/Ruche ?

C'est une sacrée évolution que tu pousses la, très ambitieuse :) ;)

**Comment by KiwiHC16** [comment]
Sur mon systeme de prod je suis avec 4 zigates et 76 noeuds et ca n'a jamais aussi bien ronronné ni été aussi rapide.

Je ne pense pas qu'il y est de soucis de ce côté car je viens d'inclure plusieurs équipements. 
Le format des messages n'est pas super clair (meme moi je m'y pers) du fait de l'evalution du plugin surtout de ma petite comprenhension du zigbee quand l aventure à commencée.

Il faudrait que je trouve 5 minutes pour faire une doc sur le format des messages.

regardes dans AbeilleCmd:
function procmsg( $message ) {
...
if ($address != "Ruche") {
...
else { // $address == "Ruche"

Il y a un traitement different si Ruche ou si Device.

**Comment by KiwiHC16** [comment]
@sneu ou en es tu avec ton systeme ?

**Comment by KiwiHC16** [comment]
Pas de nouvelles je clos.
