### ISSUE TITLE
Systeme Olive

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1008]
> Essai avec la version 2020.03.06 stable Jeedom 4.0.43 une zigate WiFi

**Comment by KiwiHC16** [comment]
Peux tu me faire un capture d'ecran de la page de configuration apres tentative ?

**Comment by djsyl** [comment]
Il va faloir attendre pour l'instant ma machine est en prod sur une sauvegarde qui fonctionne

**Comment by KiwiHC16** [comment]
Quelle est la taille du fichier de ton backup ?

**Comment by djsyl** [comment]
125Mo

**Comment by djsyl** [comment]
![Capture d’écran du 2020-03-07 19-17-45](https://user-images.githubusercontent.com/19546412/76150340-c2abcd00-60a9-11ea-9ff3-8cb8d541d41c.png)
![Capture d’écran du 2020-03-07 19-18-56](https://user-images.githubusercontent.com/19546412/76150341-c8a1ae00-60a9-11ea-9e16-c73ddb3a3147.png)
![Capture d’écran du 2020-03-07 19-20-55](https://user-images.githubusercontent.com/19546412/76150344-cccdcb80-60a9-11ea-8400-701ed0bac882.png)
  

et la la machine est planté ...

**Comment by djsyl** [comment]
bon ca s'est mal passé, boot planté 
obligé de remonter un système complet + sauvegarde pour repartir

**Comment by KiwiHC16** [comment]
Pourquoi le champ "Abeille Serial Port" est sur AUCUN.
Si tu as une ZIgate Wifi, il faut choisir Wifi1 et mettre l adresse IP:PORT dans le champ suivant.

Ok le Backup est trop gros. Je vais refléchir à comment récupérer ta conf pour la mettre sur mon systeme et tester.

**Comment by djsyl** [comment]
Pourquoi le champ "Abeille Serial Port" est sur AUCUN.
Si tu as une ZIgate Wifi, il faut choisir Wifi1 et mettre l adresse IP:PORT dans le champ suivant.


Ben simplement si l'on met Wifi1 dans le champ ca donne une erreur de port ...
mais crois moi j'ai fait l'essai avec et sans ...

**Comment by KiwiHC16** [comment]
Sur la version de départ, peux tu aller dans la page configuration, page OS/DB:
![Capture d’écran 2020-03-08 à 20 09 11](https://user-images.githubusercontent.com/8549674/76169473-d1ad8080-6178-11ea-9a0b-e61f3976b695.png)

Puis 
![Capture d’écran 2020-03-08 à 20 10 49](https://user-images.githubusercontent.com/8549674/76169480-eb4ec800-6178-11ea-8e5e-28fdcda8e814.png)

Puis saisir la ligne:
![Capture d’écran 2020-03-08 à 20 11 16](https://user-images.githubusercontent.com/8549674/76169483-f9044d80-6178-11ea-8042-6d2bd634c7f4.png)
`select * from config where plugin = "Abeille";`
Et partager le résultat.

**Comment by djsyl** [comment]
Voilà

`

plugin | key | value
-- | -- | --
Abeille | AbeilleParentId | 17
Abeille | AbeilleSerialPort | /tmp/zigate
Abeille | AbeilleSerialPort2 | none
Abeille | AbeilleSerialPort3 | none
Abeille | AbeilleSerialPort4 | none
Abeille | AbeilleSerialPort5 | none
Abeille | active | 1
Abeille | affichageCmdAdd | Y
Abeille | affichageNetwork | Y
Abeille | affichageTime | Y
Abeille | deamonAutoMode | 1
Abeille | deamonRestartNumber | 0
Abeille | IpWifiZigate | 192.168.0.252:9999
Abeille | IpWifiZigate2 |  
Abeille | IpWifiZigate3 |  
Abeille | IpWifiZigate4 |  
Abeille | IpWifiZigate5 |  
Abeille | lastDeamonLaunchTime | 2020-03-08 22:04:06
Abeille | lastDependancyInstallTime | 2020-03-06 16:35:40


`

**Comment by KiwiHC16** [comment]
Ok, je vais tester avec cette config.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-03-10 à 10 57 00](https://user-images.githubusercontent.com/8549674/76300989-e0ea1680-62bd-11ea-8793-6081025e7e1c.png)

One diff /tmp/zigate and /dev/zigate

Version:

- Abeille -> HEAD détachée sur eb278b37
- Jeedom -> 4.0.38

**Comment by KiwiHC16** [comment]
Restart process apres checkout master:
![Capture d’écran 2020-03-10 à 11 04 07](https://user-images.githubusercontent.com/8549674/76301641-e09e4b00-62be-11ea-8875-a54b0f468b88.png)

![Capture d’écran 2020-03-10 à 11 05 05](https://user-images.githubusercontent.com/8549674/76301743-12afad00-62bf-11ea-9733-0d7da55fd896.png)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-03-10 à 11 06 31](https://user-images.githubusercontent.com/8549674/76301813-34a92f80-62bf-11ea-8671-ee28ce310869.png)
Save and error message "Warning: le port serie vers la zigate n existe pas: /dev/zigate1"

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-03-10 à 11 07 34](https://user-images.githubusercontent.com/8549674/76301898-5b676600-62bf-11ea-920e-c3282f7d8c72.png)

**Comment by djsyl** [comment]
Et ... ???

**Comment by KiwiHC16** [comment]
Si je publie une beta peux tu la tester ?

**Comment by KiwiHC16** [comment]
La beta devrait etre dispo demain.
Et si bon retour alors je ferai une Stable.

**Comment by djsyl** [comment]
Faut voir cette fois je fait une image complete du disk avant de faire quoi que ce soit.

**Comment by djsyl** [comment]
La bêta n'a plus sa place tant que stable ne fonctionne pas ...

**Comment by KiwiHC16** [comment]
As tu essayé de nouveau ? Des nouvelles ?

**Comment by KiwiHC16** [comment]
Pas de nouvelles je clos.
