### ISSUE TITLE
AbeilleParser utilise tout l'espace disque

### ISSUE THREAD

**Issue by lukebr91** [KiwiHC16/Abeille#101]
![capture](https://user-images.githubusercontent.com/35848408/36115987-0b044748-1035-11e8-9fe5-88119170a1a7.PNG)

Suite au bug que je croyais isolé, j'ai refait une installation propre hier de mon raspberry mais rebelotte ce soir

AbeilleParser fait 28go ! me blinde l'espace disque & plante mysql avec mariadb qui ne veut plus se lancé même après suppression du fichier ou du plugin.

**Comment by edgd1er** [comment]
En mode debug, c'est très verbeux, tu peux passer en mode info ou error. 
Normalement, le redémarrage du démon, écrase les logs précédents. (AbeilleParser, AbeilleSerialRead et AbeilleMQTTCmd)

Peux tu confirmer que les premières lignes dates bien du jour de lancement du demon ? ( info dans la page du plugin) 

je ne sais pas si Jeedom a une surveillance de logs pour alerter l'utilisateur..  C'est un point a noter effectivement.

**Comment by KiwiHC16** [comment]
Oui il faut qu on règle se problème. 
Je vais créer une issue spécifique. Cela se produit avec les derniers master(introduction d u bug) ou si la clef n est pas dispo fonctionnelle.

**Comment by edgd1er** [comment]
AbeilleParser écrit une ligne par seconde, un message est envoyé meme si la taille est de zéro.
le contournement  en ligne 124 est:        (($length>0)) && deamonlog('info', '-------------- '.date("Y-m-d H:i:s").': protocolData size('.$length.')');

il reste a trouver pourquoi un message est envoyé vide. datas size = 0

J'ai mis le correctif dans le pull request commit 389562d899d82d2d0b86179645dd44446ee2c6ad

**Comment by KiwiHC16** [comment]
Ca se produit quand par exemple on perd la liaison avec la ZIGate ou suite au bug introduit par erreur hier (voir dernier message sur Forum Jeedom Plugin Abeille). J'ai fait une correction rapide mais pas encore testée. @edgd1er , je me pose la question du benefice de ce pipe entre AbeilleSerial et AbeilleParser. Quand il marche c 'est super par contre quand ca commence à ne plus marcher c'est la galère. Il faut reflechir a  inclure AbeilleSerial dans AbeilleParser sans passer par le pipe je pense. Je vais reflaichir plus qu sujet avant d'enelever le pipe.

**Comment by KiwiHC16** [comment]
J'ai repris la modif de @edgd1er et fait un peu de clean up pour ne pas avoir des if dans if mais pluto if return, c est plus facile a lire.
Je clos le cas. Si ce n'est pas suffisant on rouvrira.
