### ISSUE TITLE
Changement d'adresse IEEE de la ruche

### ISSUE THREAD

**Issue by fbonelle** [KiwiHC16/Abeille#1010]
Bonjour,

Bizarrement, j'ai la ruche qui aurait changé d'adresse IEEE: "Alerte changement de l adresse IEEE pour un equipement !!! ( Ruche : 00158d0001c61c2b =>00158d00011c2b99"

C'est un comportement possible ? Comment je fais pour valider la nouvelle adresse ?

Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Bonjour,
Ce n'est pas possible (à ma connaissance). Toutes les situations que j'ai rencontrée dans ce cas étaient liées à des problemes de CRC. As tu des erreurs CRC dans ton log ?
Quelle version d'Abeille ?
Quel HW ? USB, Wifi, PiZigate ?

**Comment by fbonelle** [comment]
Bonjour,
Oui, à priori, j'ai eu des remontées d'erreur CRC. D'ailleurs, c'est quoi ? Je suis sur une zigate USB. J'ai eu ce problème Samedi et Dimanche une partie de la journée. Depuis  cela semble rentré dans l'ordre.
Merci

**Comment by KiwiHC16** [comment]
Ça veut dire que le messages envoyé par la zigate sont corrompus quand ils arrivent à Abeille. Le problème jusqu’à présent vient du module USB entre la zigate et le rpi. Bien vérifier que tout est correctement connecté et si ça perdure probablement changer le module usb.

**Comment by KiwiHC16** [comment]
Je clos. Rouvres si besoin.
