### ISSUE TITLE
Reglage butée Store Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1011]
https://community.jeedom.com/t/plugin-abeille-store-fyrtur-ikea-comment-regler-la-course-maximale/19897

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Pas d'infos et tres vieux sujet.
A reouvrir si ca interesse qqn avec + d'infos.
