### ISSUE TITLE
LOG reste en mode debug

### ISSUE THREAD

**Issue by sagitaz** [KiwiHC16/Abeille#1014]
Bonsoir,

Lorsque je passe le log en mode default alors qu'il était en mode debug et que je redémarre le deamon, le log continue à indiquer toutes les infos debug.

zigate usb firmware 3.1c
jeedom 4.0.43
abeille 06.03.2020

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok je l ajoute pour correction dans la prochaine version importante.

**Comment by KiwiHC16** [comment]
Peux tu me dire si c'est toujours le cas apres un restart du demon ?

**Comment by sagitaz** [comment]
je te tiens au courant prochainement, j'ai un soucis depuis un reboot de jeedom, j'ai tout qui est passe en time out et plus rien de fonctionne, même en revenant sur un ancien backup.

ma clé ne répond plus au mode inclusion, j'ai essayé de réinstaller un firmware mais rien ne change. je vais attendre d'avoir un peu de temps pour chercher une solution.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-03-18 à 10 08 55](https://user-images.githubusercontent.com/8549674/76943961-7b6ed900-6900-11ea-9876-aa3544abc658.png)

Si Abeille sur defaut alors c est la valeur qui est dans "Niveau de log par defaut" qui est pris en compte.

**Comment by KiwiHC16** [comment]
Correction pushed for AbeilleCmd.
Can't see the issue for AbeilleParser, AbeilleSerial, AbeilleSocat1.
