### ISSUE TITLE
PDM Commandes: decode8035

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#1019]
Bonjour
Dans les logs AbeilleParser, j'ai l'erreur suivante

Call to a function which doesn t exist: decode8035

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ce n'est pas important.
C est une fonctionalité ajoutée à la Zigate qui n'est pas utilisée dans Abeille.
Peux tu me dire quel Firmware est installé sur ta zigate ?
Je garde le sujet ouvert en "enhancement" pour immplementation future.

**Comment by sebfar9172** [comment]
c'est la 3.1c
je viens de la mettre à jour ce matin (pour info cette information ne s'affiche pas sur la page Abeille, c'est vide

**Comment by tcharp38** [comment]
Il y a un message maintenant que ce message est ignoré.
Je suggere de clore ce point. A reouvrir le jour ou le message 8035 est necessaire ou utile pour Abeille.

**Comment by KiwiHC16** [comment]
Ok je clos.
