### ISSUE TITLE
Installation dependance user experience

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#102]
En fin d'installation des dependance on fait un restart de apache sans demander l avis de l utilisateur, résultat, une perte de Jeedom pour l utilisateur, des messages d'erreurs dans tous les sens et un jeedomdom qui revient après 20s et certainement beaucoup plus sur des petties machines.

Premier solution:
- ne pas faire le restart d'apache et demander un restart a l utilisateur

Deuxieme solution:
- ?????

(Je le classe bug car c'est vraiment pas bon pour une premiere experience, même moi a chaque fois je me dis, quest ce qui ce passe, c est planté....)

**Comment by edgd1er** [comment]
Solutions possibles
* pas de restart car l'on considérerai que les dépendances apache/php/mosquitto sont ok ou a laisser faire par l'utilisateur. 
* ne plus passer par php mais par du python (je ne sais pas comment, mais il est peut être possible de se passer de mosquitto, façon plugin openzwave)

**Comment by KiwiHC16** [comment]
On peut imaginer se passer de mosquitto. Ca risque d être un boulot important mais faisable. Il faut peser le pour et le contre.

Pour la config actuelle avec Mosquitto:
- permet de faire la gestion des queues de messages
- permet d avoir plusieurs clients sur un meme type de message
- permet de mettre plusieurs plugin au dessus de la zigate (j'en ai un autre en gestation) 
- pas de boulot de portage sur une autre solution
- permet d'avoir un client mosquitto graphique pour générer/visualiser graphiquement les messages (MQTTBox, c est ce que j utilise)

Contre la config actuelle:
- installation de mosquitto est loin d'etre simple
- ...

Autres sujets:
- Mosquitto permet de découpler la partie Abeille de la partie zigate/resource/demons, on peut imaginer avoir zigate/resource/demons sur une machine et jeedom/abeille sur une autre. Est ce que cela vaut le coup depuis qu'il y a "jeedom link" ?


Il y a aussi le pipe input qui est le fruit de la genèse de Abeille, je ne suis pas franchement sure qu'il soit nécessaire. Mais maintenant nous n'avons plus de problème avec alors qu'au début ce n'était pas le case.

**Comment by KiwiHC16** [comment]
Est ce qu'il y a eu un chanegement car actuellement le restart de apache est super rapide, pas comme dans certain cas ou je devais attendre pratiquement une minute. Dans ce cas on peut garder le restart apache.

**Comment by edgd1er** [comment]
Salut,
Pas de changement de mon coté, ça démarre toujours en 10-15 secondes. ca fait un moment que je n'ai pas fait de full install sur un docker neuf.

Concernant le demon python, il faut aussi un proxy php pour avoir accès aux objets php. Du moins, c'est ce que je crois comprendre du code. Les dev sont supers avares de docs et commentaires... Du coup, l’intérêt de changer diminue.

**Comment by KiwiHC16** [comment]
mosquitto est top pour suivre les messages entre les modules logiciels et permet d envoyer des messages sans faire de code pour tester. Le remplacer serait un gros boulot et on perdrait en fonctionnalité alors je le garde. Je prefere passer du temps sur les problemes que de vouloir refaire le monde.

**Comment by KiwiHC16** [comment]
Sur ma VM de test cela fonctionne bien. Je clos le point. Je ferai des test sur un RPI3 fresh et si ce point est visible je rouvrirai.
