### ISSUE TITLE
Espacer nom de la zigate / bouton d'inclusion / bouton télécommande

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1020]
Hello (ce n'est pas parce que je ne suis pas très actif en commentaires depuis une semaine que je ne surveille pas ton travail ;) )
Histoire de pinailler pour pas grand chose, peux tu mettre quelques espaces entre le nom de la ruche, le bouton d'inclusion et le bouton de la télécommande virtuelle, histoire d'éviter les mauvais cliques à ceux qui ne sont pas très précis dans la visée du curseur, (ou qui ont parkinson)

Dans l'attente de la suite pour refaire un essai sur ma machine en prod (quand tu auras traité #991 , #999, #944  & #958 + ce qui est plus urgent )

En te remerciant

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
In master.
