### ISSUE TITLE
TRADFRI Driver 10W

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1021]
> quand j’ouvre le widget j’ai bien la commande nom et le test me répond : TRADFRI Driver 10W mais depuis que j’ai choisi : Ikea Ampoule Transformer 10W dans la liste déroulante de l’Equipement, le message d’erreur je l’ai eu à la création lors de l’inclusion et il n’y avait pas de nom.
bon mais ça marche je peux les commander, merci de ta réponse
pour le dimmer je vais continuer à tester
bien cordialement

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by antec** [comment]
bonjour KiwiHC16:

voici les spec du TRADFI Driver 10W 
DONNÉES TECHNIQUES 
10W
Type : IC P SHC24-10EU-IL-1
Tension d’entrée : 220-240 VCA, 50-60 Hz
Tension de sortie : 24 VCC
Puissance de sortie max. : 10 W
Pour un usage en intérieur uniquement
Portée radio : 10 m en champ libre
Fréquence de fonctionnement :2405-2480 Mhz
Puissance de sortie : 14 dBm

Est ce bien ceci dont a besoin ?
bien cordialement

**Comment by KiwiHC16** [comment]
Aurais tu le lien vers ce produit sur le site Ikea ?

**Comment by antec** [comment]
https://www.ikea.com/fr/fr/p/tradfri-transformateur-electrique-connecte-gris-50356187/
cordialement

**Comment by KiwiHC16** [comment]
C est le même que celui ci déjà dans Abeille mais avec une puissance différente donc une duplication du modèle doit suffire. Je vais faire ça dans les jours à venir.

**Comment by antec** [comment]
ok merci

**Comment by KiwiHC16** [comment]
Modele fait dans master. Sera dispo dans la prochaine version d abeille. Pas celle d aujourd'hui mais la prochaine.

**Comment by antec** [comment]
super merci
cordialement
