### ISSUE TITLE
repeteur ikea :

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1023]
> création du repeteur ikea :
Abeille	getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/…/…/…/core/config/devices/TRADFRISignalRepeater/TRADFRISignalRepeater.json will send back default template.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
C est surprenant car la modele existe: TRADFRIsignalrepeater.json
La difference est le S en majuscule et le R en majuscule.
Dans le repertoire change le modele: TRADFRIsignalrepeater.json et son repertoire pour avoir les lettres en majuscule et cela devrait fonctionner.

Peux tu tester et me dire ?

**Comment by antec** [comment]
j'ai changé le nom du répertoire et du fichier json dans plugins/Abeille/core/config/devices resultat à la création je n'ai plus le message not found mais j'obtiens cela : 
![Screenshot_2020-03-14 Abeille - Jeedom](https://user-images.githubusercontent.com/3456023/76676079-4725b080-65c0-11ea-8613-d6b61cace2aa.png)
dans la liste déroulante icone je ne trouve plus le repeteur et dans les commandes je n'ai plus la commande nom ?

**Comment by antec** [comment]
je suppose que por l'icone il faudrait également changer le nom dans /images du node_xxx.png ? dans le fichier json faut il également changer les noms

**Comment by KiwiHC16** [comment]
Oui
Peux tu partager une capture d écran de la page commande ?

**Comment by antec** [comment]
voilà la page commande
![Screenshot_2020-03-14 Abeille - Jeedom(1)](https://user-images.githubusercontent.com/3456023/76683179-53326200-6602-11ea-81cf-afd4e704962c.png)

**Comment by KiwiHC16** [comment]
Effectivement il manque la commande nom. Tres surprenant.
La commande nom est bien dans le modele pourtant.
Il faut que je teste.

**Comment by KiwiHC16** [comment]
Je viens de mettre le modele dans le master. Sera dispo avec la prochaine version (pas celle d aujourd'hui, la suivante).

**Comment by antec** [comment]
ok merci bien
Cordialement

**Comment by letictac67** [comment]
Salut, j'ai eu un peu le même problème j'ai fais un inclusion d'une ampoule philips hue via ma zigate usb et j'ai eu ce message d'erreur . as tu une solution ?
![3](https://user-images.githubusercontent.com/62446338/78073853-eceb6480-73a1-11ea-97ee-796052c257c7.jpg)
 en faite je viens de regarder dans jeexplore le répertoire n'est pas présent d’où l'erreur, ces ampoules ne sont plus compatible avec cet version ?
