### ISSUE TITLE
Inclusion capteurs et prises Xiaomi difficile

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#1027]
Bonjour,

La plus part des elements xiaomi (je n'ai que ça) passent en timeout, certain fonctionnent à nouveau en les actionnant. Par exemple un capteur d'ouverture repasse ok en l'actionnant tandis qu'une prise n'est plus incluse, lorsque je tente une inclusion j'obtiens le message me disant .. dejà existant, mise à jour.. à plusieurs reprises et pour finir la prise n'est pas commandée ! Bref l'ensemble xiaomi abeille semble être instable..
Le plugin en version 2020-03-12 01:01:06 n'améliore pas la situation.
Pour info j'ai tenté de flasher la version 3.1b pour m'apercevoir que cela ne résolvait pas les pb rencontrés, je suit donc revenu en 3.0f.
Je ne sais plus quoi tenter, une idée ?

Merci,
Ivan

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4338761/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
As tu une Zigate USB ? Wifi ? PiZigate ?

**Comment by KiwiHC16** [comment]
Difficile de voir ce qu'il se passe sur ton systeme. On voit des equipements qui remontent leurs informations, d'autres qui "rejoin" le reseau (zigate en mode inclusion) et d'autres qui ne répondent pas à la zigate.
Peux tu partager une capture de la page santé, que j'ai une idée de ton réseau ?

**Comment by ivan9187** [comment]
Bonjour,

Des capteurs que j'ai réussi à ré inclure hier sont en time out.
La reception sur ces capteur est bonne (relayée par des 2 prises xiaomi).
Au besoin je peux partager mon écran par skype (id:).
La page santé donne:

[image: image.png]
Merci pour ton aide,
Ivan

**Comment by KiwiHC16** [comment]
Peux tu mettre l image ? Elle n'apparait pas. 

J'ai retiré tes infos perso. 
On va commencer en discutant dans cette page pour que je comprenne la situation. Et si on ne parvient pas à résoudre je me connecterai à ton systeme.

J'aurai besoin de la page santé et de la page "Table des noeuds" dans un premier temps.

**Comment by ivan9187** [comment]
re,

Utilises tu tjrs mosquitto dans ton plugin ?
J'ai fait un essai en enlevant une des prises xiaomi puis essai d'inclusion
(sans succès).
Le log ci joint..

<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ivan9187** [comment]
Dernier essai en supprimant 2 capteurs de température puis en les ré incluant -> un des 2 s'inclut bien pas l'autre (aucun msg, aucun objet créé).
Peut-il  y avoir un pb avec l'eeprom qui serait corrompue (je suis passé en 3.1b puis revenu en 3.0f sans effacer l'eeprom )?
La version 3.1b de la clé est elle supportée ?
Table de noeud :

ID | Name | Voisine | Voisine_Name | Relation | Profondeur | LQI | Type
-- | -- | -- | -- | -- | -- | -- | --
0000 | Ruche | 2833 | Abeille-2833 | Child | 01 | 180 | End Device |  
0000 | Ruche | 04d0 | Abeille-04d0 | Child | 01 | 211 | End Device |  
0000 | Ruche | b7cd | Abeille-b7cd | Child | 01 | 105 | End Device |  
0000 | Ruche | aa10 | Abeille-aa10 | Sibling | 00 | 171 | Router |  
0000 | Ruche | 3d9e | Lumiere | Sibling | 00 | 141 | Router |  
3d9e | Lumiere | 0000 | Ruche | Sibling | 00 | 214 | Coordinator |  
3d9e | Lumiere | aa10 | Abeille-aa10 | Sibling | 0F | 152 | Router |  
aa10 | Abeille-aa10 | 0000 | Ruche | Parent | 00 | 254 | Coordinator |  
aa10 | Abeille-aa10 | 3d9e | Lumiere | Sibling | 0F | 162 | Router |

**Comment by KiwiHC16** [comment]
Peux tu te connecté à https://github.com/KiwiHC16/Abeille/issues/1027
car je ne vois pas tes pieces jointes ni la capture de la page santé.

Mosquitto n'est plus utilisé.

**Comment by ivan9187** [comment]
![image](https://user-images.githubusercontent.com/47478813/76875225-9560db00-6870-11ea-9ab2-4ae042f1eae4.png)

**Comment by ivan9187** [comment]
![image](https://user-images.githubusercontent.com/47478813/76875300-ae698c00-6870-11ea-9e8f-bd702d558a28.png)

**Comment by ivan9187** [comment]
Si tu as besoin de voir mon système , comment puis je t'envoyer l'ip, le login et pwd temporaires ?

**Comment by KiwiHC16** [comment]
Premiere analyse:
je trouve dans la page santé,
- Que des equipements xiaomi.
Les routeurs: 
- Zigate = 0000
- Ampoule Ext Garage = 5ce1
- Prise X = 1d5e
Or dans la page Table des noeuds, les routeurs sont 0000, 3d9e (Lumiere) et aa10 (Abeille-3d9e).

Donc il faut deja resoudre ce soucis. On n'a pas la meme info sur les deux pages.

De quand date ton dernier GetLQI ?
Quelle versio d'abeille ?

**Comment by ivan9187** [comment]
GetLQI je connais pas
Derniere version

**Comment by KiwiHC16** [comment]
Le bouton vert "getLQI Z1".
Des infos: http://kiwihc16.free.fr/Radio.html

**Comment by ivan9187** [comment]
il est ou ce bouton, sur la clé ?

**Comment by ivan9187** [comment]
Ma clé zigate est connecté à mon odroid C2 Debian par usb.

**Comment by ivan9187** [comment]
Dans les routeurs il y a 2 prises xiaomi dont une que je n'arrive plus à inclure (peut-être celle à 000 ?)
et Ampoule Ext Garage = 5ce1 qui n'est pas alimenté.

**Comment by ivan9187** [comment]
J'ai trouvé le bouton getLQI, c'est en cours..
Ca donne ca : 
![image](https://user-images.githubusercontent.com/47478813/76881271-3358a380-6879-11ea-8be7-edc8b92d2f2b.png)

**Comment by ivan9187** [comment]
J'ai retenté une inclusion d'une prise et d'un capteur T° toujours sans succès (cela ne semble pas être le cas des autres capteurs: un refresh d'un autre capteur à bien été vu par abeille
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4344739/AbeilleParser.log)
).

**Comment by KiwiHC16** [comment]
Un equipement s'annonce (probablement quand tu fais l inclusion):
[2020-03-17 18:02:22][AbeilleParser][debug];Type; 004d; (Device announce)(Processed->MQTT); dest: Abeille1; Src Addr : 3d65; IEEE : 00158d000253d5d4; MAC capa : 8e; Rejoin : 00

et aussi un second:
[2020-03-17 18:02:43][AbeilleParser][debug];Type; 004d; (Device announce)(Processed->MQTT); dest: Abeille1; Src Addr : c500; IEEE : 00158d0002c8ef71; MAC capa : 80; Rejoin : 00

**Comment by KiwiHC16** [comment]
Peux tu partager AbeilleCmd quand tu fais l inclusion ?

**Comment by ivan9187** [comment]
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4344794/AbeilleCmd.log)

**Comment by ivan9187** [comment]
Dans le cas ou tu n'aurais pas le temps d'investiguer, y a t-il une méthode un peu bourrin à faire (du style effacer l'eeprom ?)
Faut-il flasher la clé en 3.1b ?
Faut-il passer en jeedom V4 quand à Abeille (et pour les futures versions) ?

**Comment by KiwiHC16** [comment]
```
Je mets la commande dans la queue: 5ce1 - Nb Cmd:31 -> [{"received":1584464527.0125,"time":0,"retry":3,"priority":4,"dest":"5ce1","cmd":"0100","len":"000e","datas":"025ce10101000600000000010000"}
```
Tres bizarre, "dest" devrait etre egale a "Abeille1" et pas "5ce1".

**Comment by KiwiHC16** [comment]
```
procmsg fct - message: {"topic":"Cmd5ce1\/5ce1\/ReadAttributeRequest","payload":"EP=01&clusterId=0008&attributeId=0000","priority":4}
```

"topic":"Cmd5ce1

C est n importe quoi !!! 

Ca ressemble a un gros bug.

Sur quelle version d'Abeill es tu ?

**Comment by ivan9187** [comment]
2020-03-12 01:01:06 mais j'avais à peu près le même comportement avec la version n-1

**Comment by KiwiHC16** [comment]
J'ai fait une correction il y a deux jour qui doit corriger ton soucis: https://github.com/KiwiHC16/Abeille/commit/0dc7a06fd49e0d90df4ce7cc859d9ff5fc00f32e#diff-2e009dad98c5d84fe9c3bf21367f3a7aL3700

Demain une nouvelle version doit être dispo; Installes la, fait un restart du demon et j'espere que cela devrait de nouveau fonctionner.

**Comment by ivan9187** [comment]
> 
> 
> ```
> Je mets la commande dans la queue: 5ce1 - Nb Cmd:31 -> [{"received":1584464527.0125,"time":0,"retry":3,"priority":4,"dest":"5ce1","cmd":"0100","len":"000e","datas":"025ce10101000600000000010000"}
> ```
> 
> Tres bizarre, "dest" devrait etre egale a "Abeille1" et pas "5ce1".
5ce1 correspond à une ampoule xiaomi pas alimentée mais qui peut (ou a pu) servir de relais (routeur ?)
En tuo cas en ce moment 5Ce1 ne peu pas répondre car pas alimentée.

**Comment by ivan9187** [comment]
Je viens de faire une ré inclusion d'un capteur (à 19h02 env) de porte sans succès et là encore il y a du 5ce1 un peu partout dans le log abeillecmd.... C'est peut être pour ça que le plugin Abeille ne vois rien venir..
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4345020/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4345025/AbeilleParser.log)

**Comment by ivan9187** [comment]
Un nouvel essai d'inclusion** (NOK)  en ayant supprimé l'objet 5ce1 avant
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4345055/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4345056/AbeilleCmd.log)

**J'ai supprimé l'objet E1A9 "porte de garage OF" puis tenté une inclusion

...

**Comment by ivan9187** [comment]
Est ce que je peux avoir ta correction ce soir (sinon mas radiateur électriques risques de faire n'importe quoi). Je peux peut être remplacer des fichiers sous ssh?

**Comment by ivan9187** [comment]
Faut-il flasher la clé en 3.1b ?
Faut-il passer en jeedom V4 quant à Abeille ou cela n'a pas d'importance?

**Comment by KiwiHC16** [comment]
Il faudrait juste que tu mettes le master sur ta machine.
Par le market, ca ne sera dispo que demain.

**Comment by ivan9187** [comment]
Faut-il flasher la clé zigate en 3.1b ?
Faut-il passer en jeedom V4 quant à Abeille ou cela n'a pas d'importance?

**Comment by KiwiHC16** [comment]
Dans ton cas le bug est dans Abeille.
Pas de besoin de flash firmware ni de mise a jour Jeedom.
Perso j utilise les dernières versions pour maintenir Abeille donc c est mieux si les utilisateurs d'Abeille sont avec les memes niveaux que moi ca me simplifie le support.
Perso: Jeedom 4.0.43 et Zigate 3.1b.

**Comment by KiwiHC16** [comment]
Si tu fais des mises a jours:
Backup jeedom avant toute chose
SI flash firmware toutes les inclusions a refaire. Le objets dans Abeille seront Ok si ils ont une adresse IEEE (voir page santé).

**Comment by ivan9187** [comment]
Ok merci pour ces indications.
Tu pourrais peut être indiquer ces infos d'environnement dans la doc ou les notes de versions ?

**Comment by KiwiHC16** [comment]
Bonne idée. Mais le temps me manque. Je vais essayer.

**Comment by ivan9187** [comment]
Bonjour,
Après avoir fait l'update, Abeille n'inclut par le capteur de T° (pas de msg de découverte)
Voici les logs
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4347895/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4347896/AbeilleCmd.log)

Merci
Ivan

**Comment by KiwiHC16** [comment]
```
Je mets la commande dans la queue: Abeille - Queue Numero:  - Nb Cmd:32 
```

Dans AbeilleCmd, cette trace n est pas bonne. Il faut comprendre pourquoi.
ca vient 
```
{"topic":"CmdAbeille\/8de3\/Annonce","payload":"Default","priority":2}
{"topic":"CmdAbeille\/8de3\/Annonce","payload":"Hue","priority":2}
{"topic":"CmdAbeille\/8de3\/Annonce","payload":"OSRAM","priority":2}
```

vient de:
```
[2020-03-18 09:50:07][AbeilleParser][debug];Type; 004d; (Device announce)(Processed->MQTT); dest: Abeille1; Src Addr : 8de3; IEEE : 00158d0002c8ef71; MAC capa : 80; Rejoin : 00
[2020-03-18 09:50:09][AbeilleParser][debug];Type; fct; processActionQueue, action: {"when":1584521408,"what":"mqqtPublish","parm0":"Abeille\/8de3","parm1":"IEEE","parm2":"Addr","parm3":"00158d0002c8ef71"}
```

**Comment by ivan9187** [comment]
Je viens de refaire un essai d'inclusion T° xiaomi avec plein d'erreur:

Ce qui est marrant en plus c'est que j'ai supprimé mes capteurs de vibration
et qu'il reviennent tout seuls alors que je n'ai pas appuyé sur le bouton des
capteurs
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4348245/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4348248/AbeilleCmd.log)

**Comment by KiwiHC16** [comment]
J'ai inclus 3 capteurs sur mon systeme de prod hier sans soucis alors je regarde la difference avec ton systeme.

**Comment by KiwiHC16** [comment]
D'apres les trace tin systeme tombe dans un bug que j'ai corrigé cette nuit après publication de la version d'aujourd'hui ;-(
Je vais publier une version qui devrait être dispo demain matin qui je l'espere corrige ton probleme.

**Comment by ivan9187** [comment]
Peux tu m'envoyer les fichiers, cela permettra de tester le fix ce matin ? Et de mon côté de faire fonctionner le système

**Comment by KiwiHC16** [comment]
Connias tu git et gitHub ?

**Comment by ivan9187** [comment]
Moyennement mais ayant été développeur (C, C++ et php) je devrait m'en sortir. Sinon je sais utiliser winscp et putty pour remplacer des fichiers.
Comme Network/AbeilleLQI_MapData.json si c'est celui la qu'il faut changer.

**Comment by KiwiHC16** [comment]
Alors regardes:
http://kiwihc16.free.fr/Installation.html?highlight=clone#avances

En gros tu as tous les fichier dans /var/www/html/plugins/Abeille

Tu enleves le repertoire Abeille, tu fais un git clone et tu dois avoir la version master sur ton systeme.

**Comment by ivan9187** [comment]
J'ai essayé cette nouvelle mouture:
Pas d'inclusion de mon capteur de T° xiaomi, pas de log dans le ficchier AbeilleParser, des msg non acquittés dans Abeillecmd...
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4348778/AbeilleCmd.log)

**Comment by ivan9187** [comment]
Essai de ré inclusoin de mon capteur de T°: toujours NOK.
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4348810/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4348811/AbeilleParser.log)

**Comment by ivan9187** [comment]
Comme cela ne marche pas de mon coté, j'ai l'impression qu'il y a peut être qq chose qui cloche dans mon installation.
Pour repartir d'un config propre faut-il que j'efface l'eeprom (avec la version 31.b) puis que je ré-inclus mes routeurs et capteurs xiaomi ? Y a t-il qq chose d'autre à faire pour "nettoyer" mon système? (je ne voudrais pas me retrouver dans un cas ou je ne puisse pas inclure mes capteurs).
Merci de ton aide.

**Comment by ivan9187** [comment]
J'ai un petit problème, mon hdd est à 100% certainement parceque j'ai aissé Abeille en debug..
Comme je ne peux plus accéder à l'interface web, comment puis je faire pour stopper ça (ssh)?

**Comment by KiwiHC16** [comment]
Hi ivan,
Jeedom/Abeille sur un RPI est a moins de 1% de CPU.
Je clos cette issue car la discussion aborde trop de sujets et je fini par etre perdu.
Si tu as toujours des soucis ouvre une issue specifique pour que je puisse t aider au mieux.
