### ISSUE TITLE
Set Channel

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#1028]
Suite à des difficultés à inclure des équipements qui avait "quitté" le réseau, je me suis rendu compte que Abeille ne crée plus de nouvel équipement.

J'ai essayé avec 3 devices différents, à chaque fois j'ai le même résultat :
- Ces 3 équipements existaient dans Jeedom, je faisais un reset, mode inclusion, la zigate m’annonce une mise à jour de l'équipement, mais celui-ci ne fonctionnait pas
- Je supprime l'équipement dans jeedom
- Je fais un reset, mode inclusion, l'équipement n'est pas créé. Je n'ai pas de message.

Testé avec un switch livolo, on zigbeeonoff controler et une prise Ikea.

**Comment by graouxx** [comment]
J'ai testé un Erase Persistent Data suivi d'un factory new reset ..
J'ai bien réussi à créer un nouvel équipement, par contre impossible de revenir sur le channel 26 :/

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Quand tu fais l inclusion il me faudrait le log Abeille, AbeilleParser et AbeilleCmd.

Pour le channel 26, as tu fais comme indiqué ici: http://kiwihc16.free.fr/Radio.html?highlight=channel#zigate-channel-selection
(désolé la mise en page n'est pas top, il faut que je la reprenne...)

**Comment by graouxx** [comment]
Yes, j'ai suivi ta doc, ce que j'avais d'ailleurs fait la première fois. Mais le channel n'a jamais changé.
Du coup je suis passé par la méthode sur la doc de la Zigate.

Concernant l'inclusion, cela fonctionne maintenant. La zigate devait être dans un état instable. Je ne sais pas ... En tout cas le wipe/reset a corriger le truc (mais m'oblige à refaire l'appairage de tout mes devices :( )
Je pense qu'on peut fermer l'issue.

**Comment by KiwiHC16** [comment]
Avant de fermer je voudrai vérifier l histoire du canal car il y a peut etre un bug. Je change le titre.

**Comment by KiwiHC16** [comment]
set Channel bug corrected. In master.
