### ISSUE TITLE
PiZiGate GPIO to start auto

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1029]
https://community.jeedom.com/t/zigate-et-jeedom/16685/4

GPIO sur restart demon (car si restart RPI, perte de la zigate).

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
@tcharp38 je mets ton pseudo sur ce cas si tu veux le traiter. C'est aussi pour moi une facon de me souvenir d'éviter de travailler dessus.

**Comment by tcharp38** [comment]
Ca marche pour moi. Je m'y colle des que je trouve un peu de temps

**Comment by KiwiHC16** [comment]
En gros je ne suis pas sure que sur demarrage RPi, reboot RPi, ... les GPIO soient tout le temps bien configurés pour avoir la PiZiGate alimenté;

**Comment by tcharp38** [comment]
Salut. Je n'ai pas laissé tombé ce point mais l'architecteure d'Abeille n'est pas encore tres clair pour moi.
Peux tu me pointer vers le code du démon ? Celui éxécuté au démarrage ? Merci

**Comment by KiwiHC16** [comment]
Il faut que tu regardes dans Abeille.core.class
Il y a une fonction demon_start
Je suis avec mon tel alors je ne peux pas vérifier le nom exact.

**Comment by KiwiHC16** [comment]
Le lien est 
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L442

**Comment by tcharp38** [comment]
J'avais fini par trouver cette même piste.
Meric

**Comment by tcharp38** [comment]
J'ai un fix à te proposer mais je n'arrive pas à créer une seconde pull request. Il y en a déja une dans la pipe de ma part. J'attends de tes news.

**Comment by KiwiHC16** [comment]
Je viens d'accepter le Pull Request qui doit être dans le master maintenant. J espere que cela va te permettre de faire un nouveau Pull Request.

**Comment by tcharp38** [comment]
En fait je n'ai rien à livrer. Tu l'as déja intégré. Mon 2nd commit a automatiquement été ajouté au pull request déja en cours. Désolé. Je suis encore loin de maitriser GitHub.

**Comment by KiwiHC16** [comment]
Il me reste donc à le tester sur mon PI avec sa PiZigate.

**Comment by KiwiHC16** [comment]
La led etait faible et je viens de reboot le RPI et maintenant elle est fortement allumée et le demon d'Abeille tourne donc ca semble fonctionner. Et sur une inclusion la led clignote.

Tip Top. Toujours mieux ce plugin !!!!

Merci encore....

Je clos.
