### ISSUE TITLE
Desactivation plugin error

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#103]
Sur desactivation plugin ou sur supprime plugin erreur.

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-02-13 a 12 32 00](https://user-images.githubusercontent.com/8549674/36148279-bc8d091a-10bb-11e8-8b2b-1c7fc51b64f1.png)

**Comment by edgd1er** [comment]
Sur docker, je n'ai pas eu cette erreur.... As tu eu qq chose dans les logs de jeedom ?

**Comment by KiwiHC16** [comment]
Non je ne trouve rien sur le sujet. Si le plugin est actif et que tu fais desactiver tu as ce message. Si le plugin est actif et que tu fais supprimer, tu as aussi ce message, le plugin se desactive mais n'est pas supprimé, il faut le supprimer une fois désactivé.

**Comment by KiwiHC16** [comment]
Je n'ai pas eu cette erreur aujourd'hui !

**Comment by KiwiHC16** [comment]
Je n ai plus cette erreur, je clos le sujet.

**Comment by edgd1er** [comment]
J'ai reproduit l'erreur. Cela est du aux droits par défaut du répertoire. Il faut compléter l'install pour faire du dos2unix et du chmod/chown.

**Comment by KiwiHC16** [comment]
Le probleme vient du fichier remove.sh qui cherche a enlever la conf mosquitto. Comme de toute facon on n enleve pas mosquitto lors de la deinstallation d Abeille c est plus une source de soucis qu'autre chose. J'enleve le truc automatique et le garde en manuel pour les admins et est fait une doc.
Je clos le sujet.
