### ISSUE TITLE
J'ai un petit problème, mon hdd est à 100% 

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#1033]
J'ai un petit problème, mon hdd est à 100% certainement parceque j'ai aissé Abeille en debug..
Comme je ne peux plus accéder à l'interface web, comment puis je faire pour stopper ça (ssh)?

_Originally posted by @ivan9187 in https://github.com/KiwiHC16/Abeille/issues/1027#issuecomment-600751028_

**Comment by KiwiHC16** [comment]
sur quelle type de machine es tu ?
oui ssh et reboot.

**Comment by KiwiHC16** [comment]
Sur un RPI 3 je suis à
%Cpu(s):  0,3 us,  0,2 sy,  0,0 ni, 99,4 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st

Soit rien du tout.

**Comment by ivan9187** [comment]
Merci, j'ai dû faire un restart Apache pour résoudre le pb.... (vu sur
forum jeedom)

J'ai finalement programmé la clé en 3.1c, effacé l'eeprom et ré inclut mes
xiaomi pour obtenir un comportement correct (j'ai eu besoin de forcer un
redémarrage Abeille quand l'inclusion ne donnait rien tout les 3/4
inclusion).

**Comment by KiwiHC16** [comment]
Tout est en ordre ;-)
Je clos.
