### ISSUE TITLE
GIT issue sur TRADFRISignalRepeater.json

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1034]
Salut Kiwi
Je galere a me realigner sur ton dernier master.
Je suis dans un repo dans lequel je n'ai RIEN modifié donc je m'attends à aucun conflit.
Neanmoins à l'issu du "git pull" ou meme "git pull --rebase" j'ai un conflit qui me bloque.

![image](https://user-images.githubusercontent.com/35221038/76995290-f0b5ca80-694f-11ea-9003-7fbcd7ae151f.png)

Ca te parle ?
J'ai demandé à des copains pourtant maitrisant bien GIT et ils sechent aussi.

**Comment by tcharp38** [comment]
Une autre info
![image](https://user-images.githubusercontent.com/35221038/76995487-38d4ed00-6950-11ea-9c8f-84d6d5260810.png)

**Comment by tcharp38** [comment]
Ok, voila une piste.

![image](https://user-images.githubusercontent.com/35221038/77002252-7d19ba80-695b-11ea-8b79-a679f1b0b01e.png)

Ma conclusion est que tu as poussé les 2 fichiers avec juste la casse d'une lettre de difference.
Manque de pot je suis dans un environnement Windows avec git bash, donc de mon côté pas de différence minuscule/majuscule, d'ou le clash insoluble.

Peux tu virer les 2 fichiers qui ne servent plus parmis les 4 suivants ?

-   'core/config/devices/TRADFRISignalRepeater/TRADFRISignalRepeater.json'
-   'core/config/devices/TRADFRIsignalrepeater/TRADFRIsignalrepeater.json'
-   'images/node_TRADFRISignalRepeater.png'
-   'images/node_TRADFRIsignalrepeater.png'

Merci

**Comment by KiwiHC16** [comment]
Oui je peux les virer mais alors on aura un autre soucis. J'ai ajouté ces fichier avec cette "casse" car un utilisateur a remonté l'info qu'il avait un repeter Ikea avec ce nom.
Je ne sais pas trop comment on peut faire dans cette situation.
Je vais regarder quel nom remonte avec celui que j'ai.

**Comment by KiwiHC16** [comment]
Premier:
![Capture d’écran 2020-03-19 à 08 48 24](https://user-images.githubusercontent.com/8549674/77043709-66587f80-69be-11ea-8dca-4963c616116f.png)

**Comment by tcharp38** [comment]
Est ce que tout simplement il ne faut pas ignorer la casse de ce qui est remonté ?
Je ne peux pas imaginer qu'un fabricant remonte "ModelX" et "Modelx" en considerant qu'il s'agit de 2 modeles differents. La string est codée dans le standard Zigbee ?

**Comment by tcharp38** [comment]
Bon ecoute j'ai creusé un peu et je crois que cette histoire n'est pas assez claire mais le point doit rester ouvert.
En gros est ce qu'on peut considerer que le model identifier est "case insensitive". Si ca n'est pas le cas il faut revoir la structure des devices et ca n'est pas immediat.
Je vais me debrouiller pour avoir un env case sensitive pour avancer.

**Comment by KiwiHC16** [comment]
Je vais integre le second pour voir ce que je recupere.
La solution c est que je vais faire une verrue pour ce cas particulier dans le code et enlever le second modele qui pose probleme.

**Comment by KiwiHC16** [comment]
Ok fait dans master.

**Comment by KiwiHC16** [comment]
Ca doit resoudre ton probleme maintenant.

**Comment by tcharp38** [comment]
Oui merci. J'ai du recloner le GIT mais la c'est propre.
Je clos le point.  Neanmoins peut etre faut il garder une issue ouverte ? Qu'en penses tu ?

**Comment by KiwiHC16** [comment]
Je cherche à limiter le nombre d'issue au strict minimum avec des points précis car la liste est longue et on ne sait plus ce qui est important à faire.
Je clos et et si on a un point precis on ouvrira une issue specifique.

**Comment by tcharp38** [comment]
Oui parfait pour moi. C'était mon seul moyen de com avec toi.
