### ISSUE TITLE
Plus de network graph

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#1035]
Voir screenshot
![image](https://user-images.githubusercontent.com/36622777/77069504-d54ace00-69e8-11ea-93dc-a0b317fae9f1.png)
 par contre sur la popup network list ça fonctionne bien :
![image](https://user-images.githubusercontent.com/36622777/77069600-00352200-69e9-11ea-991e-df2bd72e1f7b.png)

je ne sais pas pourquoi j'ai un warning sur le nom d'objet unique.

**Comment by KiwiHC16** [comment]
Cela n’a pas été mis à jour avec l évolution MultiZigate. La mise à jour est en cours. Devrait être dispo d ici une semaine ou deux.

**Comment by KiwiHC16** [comment]
Ca doit ete bon maintenant.
