### ISSUE TITLE
attribuer un groupe à la zigate

### ISSUE THREAD

**Issue by antec** [KiwiHC16/Abeille#1039]
bonjour Kiwih
impossible d'attribuer un groupe à la zigate (derniere version stable abeille, zigate en 31c)
cordialement

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok, il faut que je regarde ce qu'il se passe. Des que je peux.

**Comment by antec** [comment]
ok merci kiwihc en attendant j'arrive à remonter le groupe avec la ruche, mais comment fait on pour en attribuer un depuis la ruche je n'ai pas bien compris : adresse courte dans le champ correspondant = ok mais après end point = groupe ??? où trouve t on le end point de l'equipement et quelle est la syntaxe dans quel champ merci

**Comment by KiwiHC16** [comment]
Ok, le sujet a été résolu hier dans une correction faite sur les groupe.
Sera dispo dans la prochaine version (dispo dans le master).
