### ISSUE TITLE
Apres installation des dependances, le plugin ne demarre pas tout seul immédiatement.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#104]
Je mets en bug pour l experience utilisateur.

**Comment by edgd1er** [comment]
J'ai l'impression que c'est la sauvegarde des paramètres qui déclenche l'installation des dépendances. A confirmer.
si c'est le cas, un message pourrait avertir l'utilisateur.

**Comment by KiwiHC16** [comment]
Peut etre qu il demarre tout seul avec le mode automatique mais dans ce cas il faut probabkement attendre 5 minutes tests a faire

**Comment by KiwiHC16** [comment]
Il faut juste attendre 5 min apres l installation des dependances.
