### ISSUE TITLE
Configuration des Zigates: ajouter un type

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1040]
Salut
Je pense qu'il serait bon d'ajouter et mémoriser le "type" de chaque Zigate: USB, PI, WIFI.
Ca permettrait de faire des choses + propres derriere et en particulier d'aligner les controles en consequence.
Exemples:
- si type "USB", alors il est probable que seuls les "ttyUSBx" soient valides et on peut donc verifier ca.
- si type "PI", alors on peut autoriser la programmation ou mettre les IOs dans le bon mode par defaut

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
C'est une possibilité. A investiguer. Je suis preneur de toute solution pour tous.
Perso j'essaye de limiter les cas avec sous cas et sous sous cas. Surtout pour la partie graphique qui n'ai pas la partie que je prefere.
Je ne suis super favarable au premier point de filter les tty en fonction car tu trouveras toujours un cas particulier. Il faut ouvrir je pense pour avoir tous les tty dans la liste.
Perso j'utilises des /dev/ttyZigateMaison et des trucs dans ce genre...

**Comment by tcharp38** [comment]
En ligne avec toi concernant les ports à utiliser. Je ne saurais pas filtrer aujourd hui.
Neanmoins, si tu sais de quel type il s'agit tu peux faire des check supplementaires.
- La PiZigate par exemple a besoin de GPIO en + pour RESET/FLASH mais pas les autres cas.
- La programmation du FW n'est possible que pour la version "Pi" aussi.
Bref on pourrait empecher des boulettes/erreurs/ou questions qui ne font pas de sens et ainsi améliorer la stabilité et la vision globale d'Abeille.

**Comment by KiwiHC16** [comment]
Je sais le faire "facilement" quand les fichiers de code sont en php. Mais il y a toute un partie en javascript et ajax et je doit dire que je ne maitrise pas alors je ne me lance pas encore dans ce niveau.

Par exemple, il y a le tab param des équipements qui devrait n'afficher que les champs necessaires en fonction du types d'équipement et je n'ai pas trouvé comment faire....

**Comment by tcharp38** [comment]
PR faite ce jour.
Le type est maintenant dispo.

**Comment by KiwiHC16** [comment]
Ok je clos cet issue alors.
