### ISSUE TITLE
Link Quality null (Xiaomi Presense aqara 2) 

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#1041]
Bonjour kiwihc16,

J'ai intégré il y a 1 semaine 2 équipements  Xiaomi Presense aqara v2 à mon installation et j'ai remarqué que la commande **Link Quality** remote "null" sur chacun d'eux. Dans le widget, la commande n'affiche rien. 
![abeille_XiaomiPresenseaquara2_02](https://user-images.githubusercontent.com/48121420/77411007-17468c00-6dbc-11ea-8ce8-6e1e84b3799f.png)
![abeille_XiaomiPresenseaquara2_01](https://user-images.githubusercontent.com/48121420/77411009-1877b900-6dbc-11ea-832b-c220eb207f67.png)

Jeedom 4.0.45 et abeille 5a020205a493741d (Master).

Ce qui est bizarre, c'est que je récupère bien les informations depuis la table des nœuds LQI
![abeille_XiaomiPresenseaquara2_03](https://user-images.githubusercontent.com/48121420/77411141-3f35ef80-6dbc-11ea-9db3-34e95e6de4a9.png)

Aurais-tu une idée ?

Les logs en pièce jointe.
[Abeille_6728.txt](https://github.com/KiwiHC16/Abeille/files/4374458/Abeille_6728.txt)
[AbeilleParser_6728.txt](https://github.com/KiwiHC16/Abeille/files/4374459/AbeilleParser_6728.txt)
[Abeille_abb8.txt](https://github.com/KiwiHC16/Abeille/files/4374465/Abeille_abb8.txt)
[AbeilleParser_abb8.txt](https://github.com/KiwiHC16/Abeille/files/4374464/AbeilleParser_abb8.txt)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut Asyrah, 
Cette info avait été mise au debut dans les objets mais elle n'est pas pertinente si les messages sont routés vers la zigate.
Il faut passer par la table des noeuds pour avoir la bonne info.
Je ne pense pas investiguer ce cas et en théorie il faudrait que j'enleve cette commande des equipements.

**Comment by Asyrah** [comment]
Ah c'est dommage car c’était utile pour en un clin d’œil vérifier que mes objets sont à porter de mes ruches sans passer par la table des nœuds. Et la valeur était mis à jour régulièrement.

Ça reste de la cosmétique quand même :)

**Comment by KiwiHC16** [comment]
Le probleme est que l'info n'est pas forcement pertinente .
Bon il reste des souscis avec la table des noeuds et le passage en multi Zigate qu'il faut que je resolve, encore du boulot.....
