### ISSUE TITLE
Network Graph & Firefox

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1049]
Bonjour,
Petit message adressé plus à @tcharp38 qu'à KiwiHC16, vu que nous avons déjà échangé sur ce sujet, et que ça serait moins dans ses cordes: serait-il possible de rendre le Network Graph compatible avec Firefox? 
En effet, sur ce navigateur, aucun objet n'apparait.
![image](https://user-images.githubusercontent.com/46709337/78060522-f10c8780-738b-11ea-8a38-41188a1adb42.png)

Merci d'avance, et encore bravo pour votre taf ;)

++

**Comment by KiwiHC16** [comment]
Salut,
Comme j'ai bossé sur cette partie ces derniers jours sous Safari, j'ai fait un test hier avec Firefox du fait de probleme de rafraichissement et je suis tombé sur le même soucis.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
J'ai encore des trucs à faire sur cette partie. Si @tcharp38 tu fais des trucs, peut être patiente pour ne pas avoir de conflit entre tes modifs et les miennes.

**Comment by tcharp38** [comment]
Salut.
J'ai mis en suspend toute modif de cette partie depuis que tu t'es lancé sur la refonte.
Donc je patiente et surtout, hate d'arriver à un network list fonctionnel qui permette de fiabiliser le reseau.

**Comment by tcharp38** [comment]
Je pense avoir trouvé. Je fais qq tests et file le patch à Kiwi.

**Comment by tcharp38** [comment]
@Soyann 
Un fix est maintenant intégré au master. A voir si ca solutionne tes problemes d'affichage.
Donc dans la prochaine version stable si tu n'es pas sur le GIT.
A+

**Comment by Soyann** [comment]
Extra, merci beaucoup Tcharp38, un affichage au poil! (n'a pas résolu #1070 , j'avais un petit espoir là dessus, mais bon, ce n'est vraiment pas catastrophique, et vais pouvoir afficher mon réseau quand je serai au bureau, cad dans... quelques temps :p )
