### ISSUE TITLE
Affichage des équipements

### ISSUE THREAD

**Issue by PetitPhoenix** [KiwiHC16/Abeille#1050]
Bonjour,

J'ai un comportement étrange dans l'affichage des équipements dans Jeedom.

Le "Network graph" n'affiche rien et en petit texte, on trouve tous mes équipements en double comme indiqués "Pas dans Jeedom"
![Capture1](https://user-images.githubusercontent.com/62991642/78126068-37a4c500-7412-11ea-8ada-7c0f3bab2089.PNG)

Le "Network list" m'indique "Warning: chaque nom d objet doit être unique" alors que tous les noms de mes équipements sont bien uniques (Prise 2, Température 5, Température 9, Température 11, Température 4, Température 14, Température 3, Température 6, Présence 2, Prise 4, Température 1, Température 7, Température 2, Température 8, Bouton, Présence 1, Prise 1, Prise 3, Température 12, Température 10, Température 13)
![Capture2](https://user-images.githubusercontent.com/62991642/78126077-3a071f00-7412-11ea-9158-8ec29ff9fddf.PNG)

Merci

**Comment by KiwiHC16** [comment]
Salut
Sur quelle version es tu ?

**Comment by PetitPhoenix** [comment]
Je suis actuellement sous Jeedom 4.0.47 et Abeille 2020-03-19 01:01:07.

J'avais la même en étant en version Jeedom 3.x, je viens tout juste de passer en 4 pour voir si ça améliorait la situation mais ça n'est pas le cas (j'ai les deux mêmes problèmes).

**Comment by KiwiHC16** [comment]
Les problemes datent probablement de mi decembre.
J'ai corrigé ses aspects dans la version de dev. Sera donc corrigé dans la prochaine version.

**Comment by PetitPhoenix** [comment]
Ok merci. Je te ferais un retour suite à la prochaine mise à jour.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je clos. Quand tu me tiendras au courant.
