### ISSUE TITLE
Last Stamps en boucle toutes les secondes, Elements Zigbee injoignables

### ISSUE THREAD

**Issue by Franckybel** [KiwiHC16/Abeille#1051]
Bonjour,

Après plusieurs mois de bonne utilisation d'Abeille utilisant une trentaine d'équipements, je suis passé à Jeedom 4.0 mais Abeille semble instable plusieurs minutes après un reboot.
Dans les logs en temps réel un Last Stamps s'affiche toutes les secondes, la plateforme Zigbee semble ne plus répondre, détecteurs, lampes et autres ne se mettent plus à jour ou très très lentement (plusieurs secondes). LA domotique n'est plus utilisable.
Ci-dessous 2 captures de Event pour illustrer
[event.txt](https://github.com/KiwiHC16/Abeille/files/4417467/event.txt)
[event2.txt](https://github.com/KiwiHC16/Abeille/files/4417468/event2.txt)

Je suis sous Jeedom 4.0.47, Abeille "2020-03-19 01:01:07", Raspbian 10

Merci pour le support

**Comment by Franckybel** [comment]
Voici le Event après un reboot
[event3.txt](https://github.com/KiwiHC16/Abeille/files/4417562/event3.txt)
Après le reboot, tout fonctionne correctement et très réactif sur les élèments Zigbee.
Cela est le même scénario, après reboot tout est OK et après plusieurs minutes, même problème décrit ci-dessus.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Bonjour Franckybel, 
Peux tu mettre le plugin en mode debug, redemarrer le daemon et partager Abeille, AbeilleParser, AbeilleCmd ? (Je ne peux rien dire avec event.txt)

**Comment by Franckybel** [comment]
Stupide, on avait déjà échangé sur d'autres sujets et oui il te faut les Logs Abeille, désolé.

Voici, le problème est apparu quelque minutes après le mode Debug des Logs à 10h00
Je repasse les logs en mode Defaut
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4419607/AbeilleCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4419608/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4419609/Abeille.txt)

**Comment by KiwiHC16** [comment]
Si tu vas dans la page santé, il doit te manquer plusieurs adresses IEEE.
En ssh, peux tu me partager le résultat de :
```
 ps -ef | grep AbeilleInterrogate
```

Abeille doit chercher les adresses manquantes.

**Comment by KiwiHC16** [comment]
Il cherche 4 adresses visiblement;
```
[{"received":1585814491.591279,"time":0,"retry":3,"priority":4,"dest":"Abeille1","cmd":"0041","len":"0006","datas":"95d895d80100"},{"received":1585814491.733179,"time":0,"retry":3,"priority":4,"dest":"Abeille1","cmd":"0041","len":"0006","datas":"84b484b40100"},{"received":1585814491.916913,"time":0,"retry":3,"priority":4,"dest":"Abeille1","cmd":"0041","len":"0006","datas":"e01fe01f0100"},{"received":1585814496.522985,"time":0,"retry":3,"priority":4,"dest":"Abeille1","cmd":"0041","len":"0006","datas":"ee33ee330100"},
```

**Comment by KiwiHC16** [comment]
Il faut peut etre que je fasse la recherche moins agressive.

**Comment by Franckybel** [comment]
Voici
root@jeedom:/home/pi# ps -ef | grep AbeilleInterrogate
root     24960 24125  0 12:40 pts/0    00:00:00 grep AbeilleInterrogate

**Comment by Franckybel** [comment]
Le résultat après un reboot
pi       14953 14028  0 18:55 pts/0    00:00:00 grep --color=auto AbeilleInterrogate

**Comment by Franckybel** [comment]
Si cela te prend du temps de corriger, est-il possible d'installer une version précédente ?

**Comment by KiwiHC16** [comment]
Tu trouveras toutes les versions à https://github.com/KiwiHC16/Abeille/releases mais il faut faire les installation manuellement.

**Comment by Franckybel** [comment]
ça marche, merci, 3 questions rapides
Penses tu corriger rapidement le problème ?
Pour l'installation manuelle, il suffit d'arrêter le plugin et de copier le contenu du ZIP dans Abeille ?
Y a t-il perte de la configuration et des équipements ?
Merci encore car malheureusement Jeedom est HS comme tout est en Zigbee à la maison.
Bon courage à toi

**Comment by KiwiHC16** [comment]
https://github.com/KiwiHC16/Abeille/commit/f6945350de492180eee5a063984ab6c9ada7bd4c

Tres surprenant ta situation.

En regardant de nouveau ton premier message, on peut reduire le volume d'event en commentant la ligne 842 en mettant // en debut de ligne.

**Comment by KiwiHC16** [comment]
Si tu veux que je regarde directemetn sur ton systeme, install any desk.com, partage ton ecran, ouvres 2 ssh sur le systeme et donne moi le code Anydesk.

**Comment by Franckybel** [comment]
Comment puis je te contacter pour échanger et te fournir l'info demandée ?

**Comment by KiwiHC16** [comment]
kiwihc16 à free.fr

**Comment by KiwiHC16** [comment]
Oui regardes
https://github.com/KiwiHC16/Abeille/issues/1056

**Comment by Soyann** [comment]
Bonjour, si à un objet fantôme est associé un scénario, une commande... il est possible de les basculer simplement vers l'objet actif sans éplucher l'ensemble des programmes faits:
-Sur l'objet fantôme, aller sur la commande souhaitée (par exemple: Etat, On, Off...) et éditer cette commande (roue crantée à coté de 'Tester')
![image](https://user-images.githubusercontent.com/46709337/78655620-8fd24000-78c6-11ea-9984-0e2cb3366360.png)


-Cliquer sur le bouton 'Remplacer cette commande par la commande':
![image](https://user-images.githubusercontent.com/46709337/78771749-f6bc2b80-7990-11ea-800a-9925a3e88490.png)


-Aller chercher la commande sur l'objet actif:
![image](https://user-images.githubusercontent.com/46709337/78653435-6532b800-78c3-11ea-9e6a-8bb5fcaf0eaa.png)


-Dans l'onglet Configuration, vérifier qu'il n'y a pas eu de commandes de créé dans la rubrique 'Action sur valeur' (pour les commandes d'infos) ou 'Action avant/après exécution de la commande' (pour les commandes d'actions). Si des champs ont été renseigné, il faut les reporter sur l'objet actif. De plus, pour les commandes historisées, il est possible de transférer cet historique par le bouton 'Copier l'historique de cette commande sur une autre commande':
![image](https://user-images.githubusercontent.com/46709337/78772907-be1d5180-7992-11ea-8cd3-e4e6a139d984.png)


Il est possible alors de supprimer, sans pertes, l'objet fantôme. 
Depuis Jeedom 4.0, la demande de confirmation de suppression d'objet indique les interactions encore actives avec ce dernier. Ainsi, s'il y a autre chose que l'objet parant, c'est qu'un transfert de commande est encore à réaliser (dans l'exemple ci-dessous, l'objet est encore déclaré dans le scénario test):
![image](https://user-images.githubusercontent.com/46709337/78654274-995aa880-78c4-11ea-8ef9-ee8cdb0b9a9f.png)

Une fois l'objet supprimé, il est possible de vérifier que cela n'a pas générer de commandes orphelines (Analyse -> Équipements -> Commandes orphelines):
![image](https://user-images.githubusercontent.com/46709337/78654559-fa827c00-78c4-11ea-9c4b-86878747e687.png)
Ici, on voit que la commande #8205# a été supprimée alors qu'elle est mentionnée dans le scénario test. Si tel est le cas, il faut dans un premier temps identifier à quoi faisait référence cet objet (une commande d'état par exemple), puis aller sur la commande remplaçant l'ancienne commande fantôme, et cliquer sur 'Cette commande remplace l'ID'
![image](https://user-images.githubusercontent.com/46709337/78655498-64e7ec00-78c6-11ea-892b-15ae33623588.png)


Puis remettre le numéro de la commande orpheline:
![image](https://user-images.githubusercontent.com/46709337/78655147-e12dff80-78c5-11ea-96f3-386d5746e4a1.png)


Normalement avec tout ça, ma migration devrait se refaire facilement et sans loupés ;) 
En espérant que cela répondra à ta question, en complément de celle de KiwiHC16.

**Comment by Franckybel** [comment]
OK super pour le détail, je ne connaissais pas, ça m'aidera pour d'en d'autres circonstances.

Voici un petit retour d'expérience sur ce problème.
- Le problème n'existait pas avant ma migration vers Jeedom 4.0
J'ai effectué ma migration en effectuant un restore d'une sauvegarde
Je souhaitais migrer tout en installant un RaspBian dernière génération est bascule sur disque SSD
J'ai donc effectuer une mise à jour Jeedom quand mon autre système sur SSD était prêt (RaspBian et Jeedom 4.0)
- En lisant l'article de Ben #1056 et en supprimant mes appareils 'Fantômes' (au nombre de 4) cela fonctionne maintenant parfaitement.
Mes 4 appareils n'avaient pas de IEEE mais ils étaient mis en 'INACTIF' mais 'VISIBLE' car des appareils intégrés dans la Zigate et Jeedom pour des usages futurs. 

KiwiHC16,, Petite suggestion,  ne serait-il pas intéressant que la recherche des IEEE ne s'effectue que sur les appareils 'Actifs' dans Abeille, car sinon il n'est pas possible d'intégrer des appareils en préparation d'un futur usage.

En tout cas superbe aide sur ce sujet, Merci pour la prise de main à distance permettant de confirmer le problème.
Mon Jeedom fonctionne de nouveau correctement avec mes 30 appareils Zigbee. 

Je pense qu'il est important d'aider KiwiHC16 en contribuant à la cagnotte, déjà effectué pour ma part il y a quelques mois lors de l'intégration de nouveaux équipements :)

A+

**Comment by KiwiHC16** [comment]
Je fais exactement comme Soyann avec en plus la migration de l historique de la commande.

**Comment by KiwiHC16** [comment]
"KiwiHC16, Petite suggestion, ne serait-il pas intéressant que la recherche des IEEE ne s'effectue que sur les appareils 'Actifs' dans Abeille, car sinon il n'est pas possible d'intégrer des appareils en préparation d'un futur usage."

Comment fais tu la preparation d'equipement ? Pourquoi passes tu des équipements en inactif ? Je ne comprends pas ce que tu fais. Si tu pouvois détailler ce que tu fais ?

**Comment by Franckybel** [comment]
L'objectif est d'avoir dans Jeedom les équipements déjà intégrés même si ils ne sont pas utilisés.
Je fais cela pour tous les équipements Zigbee ou autre.

Quand je reçois les équipements le première chose que je fais c'est l'intégration dans Jeedom et donc inclusion Zigate et Abeille pour le Zigbee.
Une fois l'équipement **_intégré et vérifié_** qu'il fonctionne :
- Désactive l'équipement pour ne pas interagir avec la domotique
- Place l'équipement dans l'objet "Aucun" (ce que tu avais vu lors de la prise de main à distance)
- Colle une Etiquette avec son 'Address' pour l’identifier facilement pour utilisation future
- Le débranche ou enlève la pile pour stockage

**Conclusion** : 
- Cela permet dès réception du matériel de vérifier que l'équipement fonctionne
- De le stocker déjà configuré et intégré dans Jeedom
- De sortir un équipement du stock, le réactiver dans Jeedom avec sa référence de son étiquette et l'utiliser en production dans la domotique.

C'est une méthode un peu industrielle mais cela permet de vérifier que l'équipement fonctionne dès réception, le référencer et le stocker.

J'espère que les explications permettent de mieux appréhender ma façon de faire qui n'est peut-être pas la bonne,

**Comment by Soyann** [comment]
Notice ci-dessus mise à jour avec ajout des actions sur valeurs et transfert des historiques ;)

**Comment by KiwiHC16** [comment]
C'est méthodique et probablement une bonne habitude. Mais avec le zigbee il faut prendre en compte plusieurs points:
- Etiquette avec son 'Address': il ne faut pas prendre l adressee courte de 4 chiffres car elle change. Il faut prendre l adresse IEEE sur 16 chiffres.
- Si tu enleves les piles alors l'équipement ne discute plus. Le standard Zigbee indique que dans ce cas l'équipement doit "être oublié" par le réseau au bout d'un certain temps. Il est fort probable de devoir le ré-inclure dans le future.

Je vais inclure la prise en compte de l etat du device.

**Comment by KiwiHC16** [comment]
J'ai ajouté à la doc et modifier le code pour prendre en compte le fait que l element est actif/inactif.

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Remplacement.html

**Comment by Franckybel** [comment]
Merci Encore, Super boulot
