### ISSUE TITLE
Ampoule Hue

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1052]
ce sont des ampoules : Philips Hue Ampoules LED Connectées White Ambiance E27 Compatible Bluetooth, Fonctionne avec Alexa Pack de 2 [Classe énergétique A+]
philips hue ambiance

**Comment by KiwiHC16** [comment]
https://www.boulanger.com/ref/1127708?xtor=SEC-6903-GOO&xts=171153&origin=pla&kwd=&utm_medium=liens_sponsorises&utm_source=google_shopping&utm_campaign=objets-connectes&xtor=SEC-10238-GOO-%5B%5D&utm_medium=liens_sponsorises&utm_source=google_shopping&utm_campaign=leguide_generic&gclid=CjwKCAjw95D0BRBFEiwAcO1KDDfs7NwAQxZwOa_FZo-Ul78G8m3mvhgfX53lmsbnlNK1ZCdLs2VKGhoCEHQQAvD_BwE&gclsrc=aw.ds

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
LTA001

**Comment by KiwiHC16** [comment]
modele in master.

**Comment by letictac67** [comment]
aprpriori c bon j'ai juste rajouté l'image dans le rep img et le LTA001.json dans device
t'es un chef merci
