### ISSUE TITLE
Faire doc sur duplication ddes abeilles et leur gestions

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1056]

**Comment by Soyann** [comment]
Si ça peut t'aider: dis moi rapidos comment simuler le pb, m'expliquer vite fait comment solutionner (je suppose à grand coup de 'Cette commande replace la commande'), et j'essaye te faire ici un tutos détaillé à mettre dans ta doc ;)

**Comment by KiwiHC16** [comment]
Unicité des équipements 

Lors de l’inclusion d’un nouvel équipement, Abeille va créer un équipement dans Jeedom pour le representer et pouvoir interagir avec lui. 
Le réseau Zigbee permet d’adresser les équipements par l’intermédiaire d’une adresse courte. Cette adresse courte est fournie à l’équipement par la zigate lors de l’appairage (Pour ceux qui connaisse le monde IP c’est comparable au protocole DHCP). Cette adresse courte peut changer au cours du temps par exemple lorsqu’un équipement quitte le réseau zigbee et se déconnecte. Il est donc impossible d’identifier spécifique un équipement à partir de son adresse courte. Heureusement, les équipements ont tous un adresse IEEE unique. Cette adresse est uniquement au monde et deux équipements ne peuvent pas avoir la même même si ce sont deux produits identiques. C’est un peu comme le numero de sécurité sociale. A partir de cette adresse on peut identifier l’équipement de façon certaine. Mais elle ne nous informe pas sur le type d’équipement.
Un autre élément interessant est le nom que fourni l’équipement si on le lui demande. Ca nous permet de connaitre son type. 
Comme Abeille cherche a être le plus générique possible, des qu’une information interessante remonte de la zigate un équipement est créé. En gros des qu’on arrive à avoir le nom et l’adresse courte de l’équipement physique alors on crée un équipement dans Jeedom.
Ensuite Abeille cherche a collecter le plus d’infos possible sur l’équipement en l interrogeant. En particulier récupérer l’adresse IEEE pour l identifier de façon unique.
Maintenant cela ne se passe forcement toujours très bien. Par example pendant l’inclusion on peut avoir le scenario suivant. L’équipement Physique se joint au réseau Zigbee et la Zigate lui donne une adresse. Abeille récupère son nom et son adresse courte et crée un équipement A dans Jeedom. Abeille cherche alors a récupérer l’adresse IEEE auprès de l équipement physique. Pour une raison X ou Y, Abeille n’y parvientt pas. L’équipement quitte le réseau et rejoin le réseau de nouveau, alors la Zigate lui donne une adresse courte B (different de la premiere A), Abeille reçoit le nom avec la nouvelle adresse B. A la reception Abeille crée un deuxième équipement. Le résultat est que l équipement A dans Jeedom ne représente plus l’équipement B qui est en lien avec l’équipement physique.
Il y a d’autre scénarii qui peuvent provoquer la création d’équipement dans Jeedom sans lien avec un équipement physique.
Pour limiter ce creation fantome il est important de récupérer les adresses IEEE. Car a la creation si l’adresse IEEE est connu, Abeille va modifier dans Jeedom l’équipement existant et ne pas en créer un nouveau.
Pour connaître les équipements fantome dans Abeille, il faut aller dans la page santé et investiguer les équipements en timeout et sans adresse IEEE. Une fois que vous pensez que c est un équipement fantôme, essayez de la faire réagir depuis abeille (par exemple Allume/Eteint pour une ampoule), ou en le faisant réagir physiquement (par exemple en ouvrant une porte). Si rien ne se passe il fort probable que cela soit un fantôme que vous pouvez supprimer de Jeedom.

Dans les dernières versions d’abeille (Fin février 2020), j’ai ajouté une fonction essayant de récupérer les IEEE des équipements. Normalement au bout d’une heure l’information IEEE est récupère et le processus s’arrête. Dans le cas d’un fantôme, l’interrogation est envoyée mais l’information n’ ai pas récupérée, pour l instant l’interrogation continue indéfiniment. Il faut que je trouve un moyen pour mieux gérer ces cas. Le problème est que les fantômes provoque ces interrogations sans fin en chargeant la zigate. Si dans la page santé vous trouvez de fantôme, supprimez les et si vous trouvez des équipements sans adresse IEEE, réveillez les plusieurs fois pour qu’ils répondent et que l’adresse IEEE apparaisse dans la page santé (la rafraichir en la fermant puis ouvrant).

**Comment by KiwiHC16** [comment]
Voila un premier jet sans relecture que je voudrai mettre dans la doc.

**Comment by tcharp38** [comment]
Très interessant.
J'ai revu ta premiere version en séparant en 3 parties pour + de clareté. J'ai reformulé aussi un peu. J'espère que ca te convient.

Le nom du sujet serait plutot "Equipements fantomes (sans adresse IEEE).

Lors de l’inclusion d’un nouvel équipement, Abeille va devoir le référencer dans Jeedom pour qu'il ait une représentation graphique et qu'on puisse interagir avec lui.

Adresses courte et IEEE
=======================
Le réseau Zigbee permet d’adresser les équipements par l’intermédiaire d’une adresse courte.
Celle-ci est affectée à l’équipement par le coordinateur (la zigate) lors de l’inclusion (appairage).
Pour ceux qui connaissent le monde IP, c’est comparable au protocole DHCP.
Cette adresse courte peut changer au cours du temps par exemple lorsqu’un équipement quitte le réseau, son adresse courte peut être réaffectée à un nouvel entrant.
Il n'est donc pas fiable dans le temps d’identifier un équipement particulier à partir de son adresse courte.
Heureusement, les équipements ont tous une adresse IEEE, unique au monde. Deux équipements ne peuvent donc pas avoir la même et ceci même s'il s'agit de deux produits identiques. C’est un peu comme le numéro de sécurité sociale.
A partir de cette adresse on peut identifier l’équipement de façon certaine. Mais elle ne nous informe pas sur le type d’équipement.

Récupération d'informations complémentaires
===========================================
En dehors de son adresse, il est nécessaire de connaitre le type d'équipement dont il s'agit. Il est obtenu en lui demandant son nom (une chaine de caractères).
Comme Abeille cherche a être le plus générique possible, des qu’une information interessante remonte de la zigate un équipement est créé. En gros des qu’on arrive à avoir le nom et l’adresse courte de l’équipement physique alors on crée un équipement dans Jeedom.
Ensuite Abeille cherche a collecter le plus d’infos possible sur l’équipement en l'interrogeant. En particulier récupérer l’adresse IEEE pour l'identifier de façon unique.

Equipements "fantomes" (adresse IEEE manquante)
===============================================
Mais l'inclusion ne se passe pas forcement toujours très bien.
Par exemple
- l’équipement se joint au réseau Zigbee
- la Zigate lui affecte une adresse courte
- Abeille récupère son nom et son adresse courte et crée un équipement A dans Jeedom.
- Abeille cherche alors a récupérer l’adresse IEEE auprès de l équipement physique mais pour une raison X ou Y, Abeille n’y parvient pas.
- L’équipement quitte le réseau puis le rejoint à nouveau. Une nouvelle adresse courte lui est affecté (B, different de A)
- Abeille reçoit le nom avec la nouvelle adresse B et crée un deuxième équipement dans Jeedom. Le résultat est que l'équipement A dans Jeedom ne représente rien de concret.
Il y a d’autres scénarii qui peuvent provoquer la création d’équipement dans Jeedom sans lien avec un équipement physique.
Pour limiter ces creations de "fantomes" il est important de récupérer les adresses IEEE. Car a la creation si l’adresse IEEE est connue, Abeille pourra mettre à jour la base Jeedom au lieu de créer un nouvel equipement.
Pour connaître les équipements fantomes dans Abeille, il faut aller dans la page santé et investiguer les équipements en timeout et sans adresse IEEE. Une fois que vous pensez que c est un équipement fantôme, essayez de la faire réagir depuis abeille (par exemple Allume/Eteint pour une ampoule), ou en le faisant réagir physiquement (par exemple en ouvrant une porte). Si rien ne se passe il fort probable que cela soit un fantôme que vous pouvez supprimer de Jeedom.

Dans les dernières versions d’abeille (depuis fin février 2020), j’ai ajouté une fonction essayant de récupérer les IEEE des équipements. Normalement au bout d’une heure l’information IEEE est récupérée et le processus s’arrête. Dans le cas d’un fantôme, l’interrogation est envoyée mais l’information n’est pas récupérée, pour l instant l’interrogation continue indéfiniment. Il faut que je trouve un moyen pour mieux gérer ces cas. Le problème est que les fantômes provoquent ces interrogations sans fin en chargeant la zigate.
- Si dans la page santé vous trouvez un fantôme, supprimez le.
- Si vous trouvez des équipements sans adresse IEEE, réveillez les plusieurs fois pour qu’ils répondent et que l’adresse IEEE apparaisse dans la page santé (la rafraichir en la fermant puis ouvrant).

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Remplacement.html
