### ISSUE TITLE
Latence puis perte Tradfri

### ISSUE THREAD

**Issue by Mindstorm96** [KiwiHC16/Abeille#1057]
Bonjour,
Tout fonctionnait sur mon Pi. Je suis passé sur un macmini2012 i7 avec debian strech et Jeedom v4 samedi dernier.Je suis reparti de la sauvegarde.
Depuis sur les ampoules tradfri ça a commencé par une latence énorme (4s pour un ON) plus rien n apparaît dans les graphes network et maintenant je perd certains devices qui deviennent incontrôlable.
J ai dèsinstallé/réinstallé plugin et dépendance, supprimer (est-ce une exclusion ?) et inclus de nouveau un device sans amélioration 
Cdlt
Nicolas

**Comment by KiwiHC16** [comment]
Les graphes ne fonctionnent pas dans la version stable actuelle. J'ai fait les corrections et devraient de nouveau fonctionner avec la stable (ok dans la beta de demain).

**Comment by KiwiHC16** [comment]
Pour le reste il faut investiguer, mais je préfèrerai le faire sur la prochaine stable si possible. Dispo certainement dimanche.

**Comment by Mindstorm96** [comment]
Merci d avoir répondu aussi vite ! 

Ps: table des noeuds est vide aussi

**Comment by Mindstorm96** [comment]
Bonjour 
Juste pour info: il y a une petite diode bleue toute près de la grosse rouge. Après un redémarrage pendant quelques minutes elle est éteinte et toutes les commandes sont super rapide malheureusement elle se remet à clignoter et toutes les commandes  redeviennent lentes 
Cdlt

**Comment by Mindstorm96** [comment]
Bonjour, vous pouvez clore cet incident. La diode bleue m’a fait pensé au broadcast en équivalence réseau du coup j ai supprimé un à un les équipements depuis la ruche ..... et retour à la normale après suppression d un des devices. J ai quand même inclus de nouveau de device pour savoir si c était un défaut physique. Il n en est rien. Tout fonctionne à nouveau.
Cdlt
Nicolas
