### ISSUE TITLE
Verification du crc dans le parser not used for the time being.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#106]
//verification du CRC
        //if ($crc == dechex($crctmp))
        // if ($crc != dechex($crctmp)) { return -2; }

**Comment by edgd1er** [comment]
je propose de loguer l'erreur de crc mais de continuer le traitement pour le moment.

L153 AbeilleParser.php
       if ($crc != dechex($crctmp)) {
            log::add('Abeille','error','CRC corrupted: expected '.$crc.' / computed: '.dechex($crctmp).' This message should be discarded.');
            
        }

**Comment by KiwiHC16** [comment]
if ($crc != dechex($crctmp)) {
            deamonlog('error','CRC is not as expected ('.dechex($crctmp).') is '.$crc.' ');
        }

AbeilleParser 2018-02-24 17:18:44[ERROR]CRC is not as expected (f) is 0F 
AbeilleParser 2018-02-24 17:47:48[ERROR]CRC is not as expected (d) is 0D 
AbeilleParser 2018-02-24 18:05:07[ERROR]CRC is not as expected (e) is 0E 
AbeilleParser 2018-02-24 19:36:09[ERROR]CRC is not as expected (e) is 0E 

Le probleme semblerait venir de la valeur calculée quand <= 0xF, il manquerait le zero comme "0F" au lieu de "f".

**Comment by KiwiHC16** [comment]
Corrected in a push on 27/02/2018
