### ISSUE TITLE
Panneau FLOAT 30x30 Ikea

### ISSUE THREAD

**Issue by Laplich** [KiwiHC16/Abeille#1060]
Bonjour,

Je voudrais savoir comment ajouter ce panneau.

[2020-04-05 14:40:28][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/FLOALTpanelWS30x30/FLOALTpanelWS30x30.json will send back default template.

je suppose donc que le modele existe pas. Je vois que le 60x60 existe mais pas le 30x30.

Comment peut on le rajouter ? J imagine que c est les mêmes commande vu que juste la taille change.

Je vous remercie pour votre réponse .

**Comment by KiwiHC16** [comment]
Il faut faire un modèle. Je vais le faire rapidement.

**Comment by Laplich** [comment]
Merci beaucoup pour la réponse rapide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Sera dans la version stable de demain.
