### ISSUE TITLE
Network list: des equipements en trop

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1061]
Salut
Je viens de basculer sur la "Stable 7/4/20".
Merci pour les points #889, #890, & #961 qui sont bien fixés depuis cette version.

J'ai fait un refresh et je trouve des équipements inconnus.

J'ai mes 12 équipements (volet profalux + capteurs temp Xiaomi)
![image](https://user-images.githubusercontent.com/35221038/78691272-b90bc400-78f8-11ea-9acf-5064e0a853e3.png)

Le graphique du reseau est enfin sympathique puisque plus rien n'est "doublé" mais il y a des surprises :) (1 manquant: Temp C2, 3 inconnus)
![image](https://user-images.githubusercontent.com/35221038/78691551-07b95e00-78f9-11ea-9711-986e4f64544a.png)

La table des noeuds donne
![image](https://user-images.githubusercontent.com/35221038/78692745-9d092200-78fa-11ea-9170-15576b3ed543.png)
![image](https://user-images.githubusercontent.com/35221038/78692805-b6aa6980-78fa-11ea-8cfb-a9ed766d95f8.png)

Enfin le panneau santé
![image](https://user-images.githubusercontent.com/35221038/78693326-6253b980-78fb-11ea-9e03-b9001e2d4272.png)

Je vais refléchir à ça mais si tu as une idée je suis preneur.
D'ailleurs, je devrais ouvrir un autre pb... mes volets sont marqués en "time-out" dans le panneau santé. Ce qui est bien sur tout faux.

**Comment by tcharp38** [comment]
J'ai trouvé ce message aussi. Ca concerne mon capteur manquant.
![image](https://user-images.githubusercontent.com/35221038/78701767-e0b65880-7907-11ea-8448-4c568d8cd5c8.png)

**Comment by KiwiHC16** [comment]
Peux tu regarder https://github.com/KiwiHC16/Abeille/issues/1056 avant que je regardes les details.

**Comment by tcharp38** [comment]
Ok. Je m'y colle

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Remplacement.html?highlight=fantome

**Comment by KiwiHC16** [comment]
As tu résolu le soucis ? Peut on clore ce sujet ?

**Comment by tcharp38** [comment]
En vrai non. Ca traine toujours dans mon env pour me rappeler qu'il manque des choses pour aider ce genre de situation.
On peut cloturer.
