### ISSUE TITLE
Croquis architecture Abeille à mettre à jour

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1062]
@KiwiHC16 
Ton croquis la http://kiwihc16.free.fr/Developpement.html m'est super utile.
Serait il possible de le mettre à jour ?
J'ai l'impression que tu utilises le support "msg queue" de PHP mais Mosquitto est toujours la. J'ai encore du mal à avoir la vue d'ensemble.

Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Developpement.html

**Comment by tcharp38** [comment]
Super !
Merci.
