### ISSUE TITLE
Température couleur ampoules IKEA ou Philips Hue

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#1063]
Bonjour,
J'ai installé la version de ce jour (8/4/2020)  d'abeille et je n'ai plus de retour de la couleur des ampoules que ce soit des IKEA ou d'une Philips Hue.
Les autres informations sont correctes que ce soit level ou état. Les commandes fonctionnent ( on off, toogle, set level, set temperature ).
J'ai essayé un getetat  mais pas plus de remonté de la couleur. 

Apparemment ce souci existait déjà sur la version précédente d'abeille puisque d'après le timestamp de jeedom sur l'information , la dernière remontée de la temperature de couleur date respectivement du 29 et du 30 mars dernier en fonction de l'ampoule.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Il y a bien longtemps que je n'ai pas touché cette partie.
Il faut que je teste avec mes ampoules.
Peut être ce soir.

**Comment by Krankhore** [comment]
J'ai restauré sur une VM de test une plus veille sauvegarde ( abeille en date du 12 mars ) et le problème est déjà existant. Dans l'historique du changement de couleur et le plus récent changement e couleur date du 12 février .  
Sur ma Vm de production , le dernier changement était le 30 mars pour cette même ampoule. 
Hors J'ai attendu pratiquement un mois avant de mettre la version multi-zigate sur ma prod ( attendu la correction des lignes de log qui sortaient m^me si pas de debug activé) alors que la vm de test est depuis sa sortie en version multi-zigate. 
Au vue des éléments je me demande si ce n'est la version multi-zigate qui a introduit un souci sur la remontée de la température de couleur.

**Comment by Krankhore** [comment]
Fait d'autres tests.
J'ai repris une sauvegarde de ma production du 21 mars. Elle était avec une version abeille du 2020-03-03 01:01:07 .
La remontée de la température de couleur fonctionne correctement.
Je suis en wifi pour la zigate et donc les deux VM tournent en parallèle .C'est la même zigate wifi et les mêmes ampoules 
Et donc sur la version de 3 mars c'est ok et sur les version postérieure que j'ai , cela ne fonctionne plus.
Il me semble que cette version était la dernière avant la version multi-zigate.

**Comment by KiwiHC16** [comment]
Interessant. Va probablement aider les investigations....

**Comment by Brugal21** [comment]
Bonjour à vous deux,

je confirme le problème de la remontée d'information de la température du blanc pour les ampoules IKEA, mais aussi AQARA de mon coté.
Les dernières remontées d'information dans ma domotique date du 12/03/2020. D'après les recherches de @Krankhore , il semble donc que le problème soit apparu autour de cette date...
Pour info, la commande slider (setTemperatureLight) pour modifier la température du blanc fonctionne bien, les ampoules changent de température.
Est ce que tu as pu avancer sur ce problème @KiwiHC16 ?

Merci d'avance et encore merci pour ton plugin et tout le travail accompli !

**Comment by KiwiHC16** [comment]
Merci pour les retours. Avancé: Non pas vraiment.
Je me focalise maintenant sur la sortie d une nouvelle stable.

**Comment by Brugal21** [comment]
Salut @KiwiHC16,

Pas de soucis, on attendra une prochaine version avec la correction. 
Juste pour essayer d'avancer, tu penses que le problème peut venir de abeilleCmd.php ?
Merci encore et bon courage pour la sortie de la prochaine version.

**Comment by Brugal21** [comment]
Est ce que tu as pu regarder cette issue ?
En complément de la remontée de la température du blanc, les ampoules de couleur IKEA ne remonte pas l'info de la couleur sur la commande ColourRGB. J'utilise l'action setColourRGB qui fonctionne bien pour faire changer la couleur de l'ampoule.
Par contre l'info de couleur remonte bien sur colourX et colourY.

**Comment by KiwiHC16** [comment]
Non, pas encore.

**Comment by Brugal21** [comment]
Salut @KiwiHC16,

Je vois que tu es en plein développement d'abeille pour l'intégration du nouveau fw 3.1d mais je me permet de te relancer sur le sujet de la température de couleur.
Penses tu pouvoir faire quelque chose prochainement ?
C'est contraignant de ne pas avoir le retour d'info de la température de couleur ou de la couleur des ampoules.

Merci d'avance !
Brugal21

**Comment by Brugal21** [comment]
Bonjour à tous,

je reviens vers vous avec une très bonne nouvelle. Pour ma part, depuis la version stable d'abeille du 09/03/21, l'info de la température de couleur du blanc fonctionne à nouveau. Je m'explique dans le détail : 

Il faut recréer l'objet dans abeille pour que l'équipement soit mis à jour.

Je rappel que pour moi le problème était sur les ampoules AQARA (light.aqcn02) et les ampoules IKEA de différents types. (J'avais aussi une Phillips HUE dont je ne me sers plu, je pense que ça doit fonctionner aussi pour les ampoules Phillips)
Avec la modification du Template :  core/config/devices/Template/temperatureLight.json et les modifications apportées par @KiwiHC16 dans "Temperature light review from A to Z" l'info de la température de couleur du blanc fonctionne !!! avec les remarques suivantes :smiley: 

 - Pour les ampoules IKEA, dont la variation de température de couleur du blanc est de 2200 à 4000K, (et qui utilise le template temperatureLight.json et setTemperatureLight.json), une action sur le slider setTemperatureLight ne donne pas exactement la meme valeur sur l'info temperatureLight. Voici le résultat de mes tests : 

[IKEA.pdf](https://github.com/KiwiHC16/Abeille/files/6135050/IKEA.pdf)

Pour moi, c'est parfait, rien à modifier. J'ai recréé toutes mes abeilles ampoules IKEA et toutes fonctionnent parfaitement, l'info remonte dans Jeedom avec une MAJ quasi instantanée.

 - Pour les ampoules AQARA, dont la variation de température de couleur du blanc est de 2700 à 6500K, (et qui utilise le template temperatureLight1.json et setTemperatureLight1.json), une action sur le slider setTemperatureLight ne donne pas exactement la meme valeur sur l'info temperatureLight. Voici le résultat de mes tests :

[AQARA.pdf](https://github.com/KiwiHC16/Abeille/files/6135055/AQARA.pdf)

J'ai donc fait des modifs, car avant cette review du template et avant 03/2020, un setTemperatureLight de 5000K donnait une valeur info de 5000K, avec le même rendu réel du blanc qu'aujourd'hui à 6452K (soit une valeur info de 6493K).

J'ai donc modifié le template light.aqcn02.json, temperatureLight1 et setTemperatureLight1 et créer 4 template 2700K_AQARA.json, 4000K_AQARA.json, 5000K_AQARA.json et 6500K_AQARA.json avec les valeurs que j'ai obtenu dans le tableau plus haut.
Pour moi ça fonctionne bien, car je n'ai pas d'autres ampoules qui "font appel" à tous ces templates. Mais si certains équipements sont en lien avec ces template ça peut peut-être foutre le bazar...

Je pense que cette différence de valeur entre le set et l'info vient de la conversation de mired en Kelvin en divisant par 1000000 et qui doit être mathématique, j'ai pas creusé... (smiley tête qui fume)

Il reste cependant l'info de la couleur (RGB) pour ma seule ampoule couleur IKEA (TRADFRIbulbE27CWSopal600lm) qui ne fonctionne pas. Peut-etre le même genre de correction ?

En tout cas un grand merci à toi @KiwiHC16 pour la refonte de cette info après presque 1 an de non fonctionnement.

Je joins les fichiers json que j'ai créé pour l'ampoule Led Aqara E27. A voir si tu veux les intégrer dans Abeille. (Moi ça m'arrangerait, je ne serai pas obligé de les remettre à chaque MAJ d'abeille :smiley: 

[AQARA - AMPOULE LED ABEILLE.zip](https://github.com/KiwiHC16/Abeille/files/6135072/AQARA.-.AMPOULE.LED.ABEILLE.zip)

J'ai vu qu'il y avait plein de template : temperatureLight et setTemperatureLight dans Abeille, je pense qu'un tri/maj est nécessaire avant de clore cette issue...

@KiwiHC16 , j'ai vu ça en faisant mes tests de l'issue 1857 avec les ampoules IKEA...

**Comment by Spilarix** [comment]
Bonsoir, le problème persiste au moins avec les ampoules Philips Hue Color E27 (LCE002) 😢.

**Comment by tcharp38** [comment]
@Spilarix @Brugal21 
C'est vous qui avez commenté cet antique sujet en dernier.
Toujours interessés ? Est il toujours d'actualité ?
Merci

**Comment by Krankhore** [comment]
Pour ma part, c'est réglé depuis fort longtemps.
Et il faut réinitialiser l'ampoule pour que ce soit correct comme indiqué par @Brugal21 ( je suppose pour appliquer le template modifié).

J'ai oublié de clore, ce que je fais maintenant.
