### ISSUE TITLE
Impossible de récupérer la table des nœuds après restauration sur une nouvelle machine

### ISSUE THREAD

**Issue by HoM3r17** [KiwiHC16/Abeille#1065]
Salut @KiwiHC16 , venant de passer sur une nouvelle machine, j'ai restauré mon dernier backup de Jeedom, jusque la tout s'est bien passé, tous les équipements et scénarios associés ont repris leur cours comme sur l'ancienne machine, mais comme je l'ai déplacé a l'opposé de la maison j'étais curieux de voir si le maillage du réseau allait s'adapter a la nouvelle position de la ruche, mais plus rien ne remonte  et j'obtiens une erreur :
` Oops, je ne peux pas écrire sur tmp/AbeilleLQI_MapDataAbeille1.json.lock` 
![Sans titre](https://user-images.githubusercontent.com/10429372/79011137-af39c900-7b63-11ea-9943-f8ec1d541e07.png)

La page "graphique du réseau me donne : 
`Données du réseau non trouvées, faites un cache-refresh sur la page Network List`

Le rapport "Santé" semble correct, mais rien n’apparaît dans les "Network Graph"

Les logs sont vides.

Je suis passé de Stretch a Buster dans l'opération

C'est pas bien méchant mais je préfère signaler

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Probablement un petit reste a corrigé du passage en multi zigate.

Efface le fichier tmp/AbeilleLQI_MapDataAbeille1.json.lock et fais un refresh.

**Comment by KiwiHC16** [comment]
Correction faite dans la version de dev. Sera dispo à la prochaine version.
