### ISSUE TITLE
Améliorations multizigate

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1067]
Hello

Hier, je me suis enfin décidé à faire le pas de la mise à jour d'Abeille sur ma machine de prod afin de profiter du multizigate, et... ça marche!!! :D Voici cependant mes remarques:
Je n'ai pas constaté de fantômes sur ma zigate 1, par contre, l’insertion de la seconde a provoqué quelques Missing IEEE, qui ne voulaient pas disparaitre malgré des réveilles forcés (pas facile de faire changer l'état sur des capteurs d’inondation ou des sondes de températures :p ), mais finalement corrigé par un Refresh LQI
J'ai constaté hier soir et ce matin que j'ai de temps à autres des TimeOut sur mes Tradfri Signal Repeater (solutionné par un reboot de ces derniers), à voir dans la durée si c'était le temps que le réseau se mette en place et se stabilise ou s'il y a anguille sous roche... j'ai encore une dizaine de capteurs de porte à ajouter dessus, je vais prendre mon temps avant de les migrer petit à petit de la passerelle Xiaomi.

Par contre, voici quelques points à améliorer:
[A] -Dans le Network List, lorsqu'on affiche un LQI, serait-il possible dans les colonnes Name et Voisine_Name de mettre l'objet parent des Abeilles: je voudrais mettre mes répéteurs avec en nom 'Routeur' (sachant qu'ils sont dans différentes pièces), mais du coup, il est difficile de savoir sur quel routeur se connecte une abeille sans avoir à coté une table de correspondance entre les ID et les objets...
![image](https://user-images.githubusercontent.com/46709337/79041414-05ece480-7bf0-11ea-823e-1514d4badfff.png)

- [B] Dans le Network Graph: pour la zigate 1, ça va à peu près, cependant j'ai un routeur (point orange en bas, au centre) où le nom n'apparait pas, et les liaisons vers cette abeille partent vers la droite...
![image](https://user-images.githubusercontent.com/46709337/79041823-22d6e700-7bf3-11ea-9f99-911f39916dfb.png)
Pourtant, la position est correcte sur l'équipement lui même
![image](https://user-images.githubusercontent.com/46709337/79041483-90cddf00-7bf0-11ea-85bb-1b0063b5ff44.png)

-[C] Dans Network Graph toujours, impossible de sélectionner la zigate 2 à afficher (qui a également des abeilles sans nom...)

- [D] J'ai fait un essai de passage d'une abeille d'une zigate à une autre: c'est un peu la panade, il me créer dans un premier temps un second objet, puis rapatrie le premier objet de la première zigate à la suivante... pourrais-tu travailler sur ce point qui pourrait vite mettre le souque (il est vite fait de ne pas mettre la bonne zigate en inclusion pour remettre sur le réseau une abeille déconnectée pour une raison x ou y) 

En te remerciant encore pour ce magnifique travail ;)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
J'ai noté [A], [B], [C], [D] les sujets dans ton descriptif.

On va traité [A] dans cette issue.

[B] On va suivre dans #1070.

[C] On va suivre dans #1071

[D] Pour le passge d'une Abeille d'une zigate à une autre, ce n'est pas ma priorité pour l'instant car très difficile à gérer proprement a ce stade. Je vais suivre dans #1069.

**Comment by KiwiHC16** [comment]
Petite question hors sujet. La carte ressemble aux cartes faites par les aspirateurs xiaomi. Quel modèle est ce ?

**Comment by Soyann** [comment]
Hello, merci pour ton traitement ;)
Pour la carte, c'est bien une vielle capture d'écran de mon Xiaomi S50 :p 
Pour info, je n'ai pas eu de problèmes particuliers avec mon système ces derniers jours, les déconnexion notées devaient bien être le temps que le réseau se stabilise ;)
J'ai commencé à migrer mes derniers capteurs de porte de la passerelle à la Zigate 2: ça se passe pas trop mal, mais quelques remarques:
-Une fois inclus, ils remontent bien, mais passent en timeout au bout de quelques heures. A ce moment là, il suffit de faire un changement d'état du capteur pour qu'il repasse en ligne, puis le problème disparait (stable sur les dernières 48h)
-Lors d'une inclusion (pour nouvel objet ou mise à jour), le message de création ou mis à jour du centre des messages n'apparait pas systématiquement (mais la commande passe bien) 

PS, je comprends que #1069 n'est pas ta priorité, mais c'est une fonction qui manque cruellement

**Comment by KiwiHC16** [comment]
Normalement [A] est dans le master.
