### ISSUE TITLE
Dans Network Graph toujours, impossible de sélectionner la zigate 2

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1071]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peux tu preciser le soucis car je vois bien le bouton Zigate2 dans ta captre d'écran.

**Comment by Soyann** [comment]
Le bouton existe, mais aucune réaction lorsque je clique dessus (idem si je fais 'Rafraichir le graphe' derrière; test réalisé depuis Safari et depuis Edge)

**Comment by KiwiHC16** [comment]
Should be solved now in dev version.
