### ISSUE TITLE
Latence (commandes qui s’empilent)

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#1074]
Bonjour, 

Déjà évoqué sur d'autres issues, je crée un case dédié.
En PJ mon log AbeilleCmd

A dispo pour faire des tests ou fournir d'autres logs.

Pour la reproductibilité, c'est assez aléatoire (fréquence + faible depuis les dernières version).
En mode inclusion c'est assez systématique (mais mon gênant).
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4474936/AbeilleCmd.txt)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2020-04-14 13:11:41][AbeilleCmd][info]Il y a plus de 50 messages dans le queue de la zigate: 1
```

**Comment by KiwiHC16** [comment]
Quel est l equipement qui a cette adresse: 78c6

**Comment by KiwiHC16** [comment]
```
[2020-04-14 13:11:41][AbeilleCmd][info]procmsg fct - message: {"topic":"TempoCmdAbeille1\/78c6\/ReadAttributeRequest&time=1586862701","payload":"EP=06&clusterId=0006&attributeId=0000","priority":4}
[2020-04-14 13:11:41][AbeilleCmd][info]procmsg fct - message: {"topic":"TempoCmdAbeille1\/78c6\/ReadAttributeRequest&time=1586862702","payload":"EP=06&clusterId=0008&attributeId=0000","priority":4}
```

Nombre incroyable de ces requetes ! 30 à la minute !!
Pourquoi ?

L appel provient probablement du cron. Mais on ne devrait avoir qu'une requete par minute.
Dans Abeille on doit avoir une Trace: log::add('Abeille', 'debug', 'GetEtat/GetLevel: '.$address);

Peux tu partager le log Abeille ?

**Comment by graouxx** [comment]
Ça provient d'un switch Livolo :
Inter. table cuisine | TI0001 | 557 | Abeille1 | 78c6 | 00124b0018027fd9 | OK | 2020-04-15 14:45:26 | 0 | 2019-10-26 12:28:58
C'est l'équipement le plus proche de la zigate et pourtant je le perds souvent. Est ce que ce ne sont pas 30 requêtes sur 30 minutes qui ce sont empilés ? (par ce que l'appareil n'était plus appairé ?)

J'active le mode debug et t'envoi le log Abeille

**Comment by graouxx** [comment]
Log dans Abeille filtré sur "GetLevel"
C'est étrange je pensais retrouver une ligne par équipement livolo chaque minute ?

```
[2020-04-15 17:32:02][DEBUG] : GetEtat/GetLevel: 11bf
[2020-04-15 17:32:02][DEBUG] : GetEtat/GetLevel: a1fc
[2020-04-15 17:32:02][DEBUG] : GetEtat/GetLevel: fc44
[2020-04-15 17:33:01][DEBUG] : GetEtat/GetLevel: 11bf
[2020-04-15 17:33:01][DEBUG] : GetEtat/GetLevel: a1fc
[2020-04-15 17:33:01][DEBUG] : GetEtat/GetLevel: fc44
[2020-04-15 17:34:02][DEBUG] : GetEtat/GetLevel: 11bf
[2020-04-15 17:34:02][DEBUG] : GetEtat/GetLevel: a1fc
[2020-04-15 17:34:02][DEBUG] : GetEtat/GetLevel: fc44
[2020-04-15 17:35:02][DEBUG] : GetEtat/GetLevel: 11bf
[2020-04-15 17:35:02][DEBUG] : GetEtat/GetLevel: a1fc
[2020-04-15 17:35:02][DEBUG] : GetEtat/GetLevel: fc44
[2020-04-15 17:36:02][DEBUG] : GetEtat/GetLevel: 11bf
[2020-04-15 17:36:02][DEBUG] : GetEtat/GetLevel: a1fc
[2020-04-15 17:36:02][DEBUG] : GetEtat/GetLevel: fc44
```

En tout cas pas de soucis pour le moment. Je ferai un nouveau check plus tard.

**Comment by KiwiHC16** [comment]
On est bien a une requete par equipement par minute.
Le probleme vient peut etre de la gestion de la queue des messages.
Un cas possible est si l'interrupteur ne repond pas.
Sur qu'elle version d'Abeille es tu ?

**Comment by graouxx** [comment]
Je suis sur la version Stable (b80200602f5f32888d2df89d63e4b7c84e61fb93)
Et je pense que tu as raison: le problème survient quand je perds des équipements qui ne répondent plus.
Ce qui me fait dire ça, c'est que depuis hier, j'attends que le problème de latence pointe le bout de son nez pour te sortir les logs. Et rien. Et quand je vais dans "santé", tous mes équipements sont OK (à l'exception d'inter Ikea, mais ça c'est depuis longtemps)

**Comment by graouxx** [comment]
> On est bien a une requete par equipement par minute

Du coup si c'est une requête par minute par équipement, pourquoi n'ais-je que 3 lignes dans les logs toutes les minutes ?
Ne devrais-je pas avoir une ligne par équipement ? (donc une 20aine)

**Comment by KiwiHC16** [comment]
Ce n'est que pour les équipements qui ont la configuration poll = 1

```
if ($eqLogic->getConfiguration("poll") == "1")
```

Qui sont interrogés. Visiblement dans ton cas il y en a trois.

Si je probleme est lié à la perte d'un équipement alors le soucis est résolu dans la version de dev je pense car j'avais eu des soucis sur perte d'équipement.

**Comment by graouxx** [comment]
Je confirme que la perte d'équipement provoque un empilement des messages.
Quelques équipements livolo perdu ce matin suite disjoncteur off. Et j'ai pas mal de messages dans la queue. Et à priori rien à noté dans le log Abeille si je filtre sur GetLevel.
[AbeilleCmd2.txt](https://github.com/KiwiHC16/Abeille/files/4492292/AbeilleCmd2.txt)

Equipements unpair :
18aa, a6d0 et f283

**Comment by KiwiHC16** [comment]
Il y a une amélioration dans la version de dev (master) sur ces sujets.
Je vais publier une version beta qui sera dispo demain.
Peux tu faire un backup et installer la beta ?
Si tu ne peux pas la beta, peux tu installer le master ? (Il tourne sur mon systeme de prod).

**Comment by graouxx** [comment]
Alors après un peu de recul et utilisation de la dernière version, je peux confirmer que le problème persiste. J'ai l'impression que c'est un peu mieux, mais c'est peut être subjectif.
Ce que je constate avec la nouvelle version : 
- jeedom met énormément de temps pour ouvrir les logs (quand je clic sur AbeilleCmd dans la page de conf du plugin)
- Les commandes mettent beaucoup de temps à se dépiler (voir log 
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4544956/AbeilleCmd.txt)
) -> par contre la pile est plus petite qu'avant.
Si je redémarre le daemon, tout rendre dans l'ordre, plus de lenteur quand je clic sur AbeilleCmd et les commandes se dépilent rapidement.

**Comment by KiwiHC16** [comment]
As tu tester avec la derniere version stable ?
Pour les log, il faut que je reduise le volume car ils sont tres lourds et il y a moins de besoins. @tcharp38 a fait du boulot de ce côté, c a devrait être mieux.

**Comment by graouxx** [comment]
Salut @KiwiHC16 
J'avoue que depuis un petit moment ça fonctionne bien. Je suis en beta. Ais-je besoin de basculer sur la version stable ?
En fait je n'ai plus de perte d'équipement Livolo depuis pas mal de temps. Et comme je l'avais mentionné, la latence apparaît surtout quand il y a des pertes d'équipement.
Du coup je pense qu'on peut fermer pour le moment. SI ça revient, je rouvrirai l'issue.

**Comment by KiwiHC16** [comment]
Oui la perte d equipement provoque des délais car on attend leur reponse et ils ne repondent pas. Mais dans la derniere version, ils sont en basse priorité pour essayer de limiter le soucis.
Bete et Stable sont identique donc ne bouge pas.
Ok je clos. A suivre.
