### ISSUE TITLE
Perte équipements Livolo

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#1075]
Bonjour,

je perds régulièrement des équipements Livolo sans raison apparente. Même ceux qui sont situés à 1 mètres de la zigate.
J'ai planifié une inclusion toutes les 12h de ma zigate pour "corriger" le problème. Mais ce n'est pas terrible.

Je ne sais pas quoi fournir comme log ?

Je perds également les équipements (systématiquement il me semble) lors d'une perte de courant au niveau de l'interrupteur. Je pense pas que ce soit normal ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Sur perte de courant il est possible de perdre des équipements mais pour chacun il faut investiguer son comportement, ce n'est pas forcement facile sans l accès au code.

Sais tu au bout de combien de temps tu perds le Livolo ?
C est des switch Livolo ?
Ceux qui sont à un mètre sont ils aussi "child" de la zigate ?
Es tu sur le canal 26 ?
Si tu as ton inclusion toutes les 12 h tu recuperes les livolo ?

**Comment by graouxx** [comment]
Je vais essayer de répondre à tes questions :

> Sais tu au bout de combien de temps tu perds le Livolo ?

Non je ne suis pas sûr, je pense que c'est immédiat, il faut que je test.
> Ceux qui sont à un mètre sont ils aussi "child" de la zigate ?

Refresh LQI en cours, je te dis ça dans quelques minutes.
> Es tu sur le canal 26

Oui
> Si tu as ton inclusion toutes les 12 h tu recuperes les livolo ?

Pas systématiquement, des fois je suis obligé de faire un reset sur le switch (après avoir lancé une inclusion).

**Comment by graouxx** [comment]
Concernant les équipements proches, ils sont pas tous en child, exemple de ces 2 inters, l'un en dessous de l'autre à 1m de la zigate : 

Abeille1/Ruche | Ruche-Abeille1 | Abeille1/78c6 | Inter. table cuisine | Child | 01 | 137 | End Device
Abeille1/b26a | Tablette | Abeille1/6c0D | Halogènes | Child | 02 | 39 | End Device

**Comment by KiwiHC16** [comment]
Est ce que tu peux clarifier la table que tu as mis dans ton dernier poste. Je ne parviens pas à la lire.

**Comment by graouxx** [comment]
C'est mieux ?

-- | -- | -- | -- | -- | -- | -- | -- | --
Abeille1/Ruche | Ruche-Abeille1 | Abeille1/78c6 | Inter. table cuisine | Child | 01 | 137 | End Device | 
Abeille1/b26a | Tablette | Abeille1/6c0D | Halogènes | Child | 02 | 40 | End Device | 
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by KiwiHC16** [comment]
Oui c'est plus facile à lire !
(en le simplifiant pour ne garder que deux lignes j'ai perdu le format ;-( )
Donc visiblement en direct sur la zigate comme tu disais pour le premier et en rang 2 pour le second qui est router par Abeille1/b26a.

Le premier à un LQI de 137 donc c'est doit être Ok.
Le second à un LQI de 40 donc ce n'est pas bon. En dessous de 50 le soucis commence.

J'aurai tendance a croire que tu perds plus souvent le second que le premier.

La ruche vois bien le routeur b26a avec LQI 161:
Abeille1/Ruche | Ruche-Abeille1 | Abeille1/b26a | Tablette | Sibling | 00 | 161 | Router |  

L'inverse n'est pas aussi bon LQI 100:
Abeille1/b26a | Tablette | Abeille1/Ruche | Ruche-Abeille1 | Parent | 00 | 100 | Coordinator |  

Mais ca reste dans les bonnes valeurs.

**Comment by graouxx** [comment]
> J'aurai tendance a croire que tu perds plus souvent le second que le premier.

hello,
En fait le 2nd je ne sais pas trop te dire. Je l'utilise assez peu (éclairage extérieur), c'est surtout le premier que j'utilise beaucoup. Et il est perdu assez régulièrement.

Il y a moyen de forcer l'équipement à dialoguer en direct avec la zigate plutôt que de passer par un routeur ? quand même étrange cette route ....

Sinon ce matin, j'ai un disjoncteur qui a sauté (quelques minutes)
J'avais 4 inters Livolo dessus. 3 sont maintenant unpair, 1 seul a gardé le lien. Et c'est pourtant le plus loin de tout.

EDIT : je me demande si il n'y a pas un effet boule de neige. Je viens de perdre un équipement qui n'était pas concerné par la coupure de ce matin. Est ce que le fait d'avoir des messages qui s'empilent (cf mon autre issue, qui à priori serait lié à la perte d'un équipement) ne provoquerait pas la perte de certains équipements qui ne reçoivent pas de réponse à temps de la part de la zigate ?
EDIT2 : l'équipement que j'ai mentionné dans mon précédent EDIT ne sait en fait pas désappairé. J'avais un timeout dans l'onglet santé, mais il a disparu. J'imagine que cela était du au nb de msg dans la queue.

**Comment by graouxx** [comment]
Plus d'une centaine de commandes maintenant dans le pipe
[AbeilleCmd3.txt.tar.gz](https://github.com/KiwiHC16/Abeille/files/4492780/AbeilleCmd3.txt.tar.gz)

**Comment by graouxx** [comment]
1. Je poursuis mes tests.
2. Reboot du deamon pour vider la queue.
3. 30 minutes après reboot, queue toujours vide
4. Dans l'onglet santé je vois que 78c6 est en timeout (celui qui est à coté de la zigate)
5. J'essaie de lui envoyer une commande => ko
6. J'allume et j'éteins des équipements livolo plusieurs fois, en utilisant des équipements appairés et d'autres en timeout. Au bout de quelques clics (une dizaine) ça commence à laguer, voir à ne plus executer les commandes (même pour les équipements appairés). Et dans les logs je vois une 40 aines de commandes en attente : 
[AbeilleCmd4.txt](https://github.com/KiwiHC16/Abeille/files/4493164/AbeilleCmd4.txt)
7. je refais le même test uniquement avec des équipements appairés Livolo. Il y a quand même un certains nombres de commandes qui se perdent ou qui s’exécutent en retard. Par contre un peu moins qui s'empile dans le log. Une quinzaine.
8. Je refais le même test uniquement avec des équipements non livolo (ikea). Et la c'est hyper réactif. Je peux spammer les boutons sur jeedom, la commande est instantanée.

Ma conclusion est que :
- le problème est lié uniquement aux équipements Livolo, même sur une commande unitaire, le temps de réaction est plus long. Je ne sais pas si c'est hardware ou software, coté zigate ou coté Livolo. A toi de me dire.
- le problème s'aggrave si on essaie d'actionner des équipements qui ne sont plus appairés

**Comment by graouxx** [comment]
J'ai donc lancé une réinclusion des devices. Pas de problème pour le faire, par contre le nombre de messages exploses dans la queue. Plus de 300.
[AbeilleCmd5.txt.tar.gz](https://github.com/KiwiHC16/Abeille/files/4493243/AbeilleCmd5.txt.tar.gz)

Est-ce qu'un appelle à l'attribut état sur un objet Livolo déclenche une commande sur la zigate ? J'imagine que non, mais je préfère vérifier, car mes virtuels ont ce genre de paramétrage sur leur statut : (#[Ruche][Inter. table cuisine][etat]# == 0) || (#[Ruche][Inter. table cuisine][etat]# == 2)  ? 0 : 1

**Comment by KiwiHC16** [comment]
Il y a une amélioration dans la version de dev (master) sur ces sujets.
Je vais publier une version beta qui sera dispo demain.
Peux tu faire un backup et installer la beta ?
Si tu ne peux pas la beta, peux tu installer le master ? (Il tourne sur mon systeme de prod).

**Comment by graouxx** [comment]
Pas de problèmes pour installer la beta ou master.
J'ai un backup quotidien donc je pourrai faire un roolback rapidement.

**Comment by graouxx** [comment]
Hello. Depuis la mise à jour vers la bêta il y a plus de 10 jours aucune perte d'équipement.
