### ISSUE TITLE
Volet PROFALUX : Monter / Descendre ne fonctionne pas

### ISSUE THREAD

**Issue by Stefma24** [KiwiHC16/Abeille#1076]
Hello @KiwiHC16,
merci pour tes travaux !
J'ai quelques volets profalux.
L'inclusion dans Abeille s'est bien déroulée, mais toutes les commandes ne fonctionnent pas.
Les commandes : Identify, getLevel et Stop fonctionnent correctement.
Cependant, et c'est là où c'est bête, les commandes Monter et Descendre ne fonctionnent pas. rien ne se passe coté volet.
La télécommande du volet, elle, fonctionne parfaitement.
Une idée ?
Merci !

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
"La télécommande du volet, elle, fonctionne parfaitement." tu veux dire la telecommande physique ? type Zoe ou autre ?

Peux tu faire un "monter"/"descendre" et partager le log AbeilleCmd ?

**Comment by Stefma24** [comment]
exacte, le télécommande **physique** fonctionne normalement. (la petite, celle du volet. La grosse Zoé se dés-appaire lors de l'inclusion du volet, mais ce n'est pas grave)
voici le log, 
j'ai procédé ainsi
volet à moitier ouvert
16h16 35s demande monter depuis jeedom (le volet ne bouge pas)
16h16 56s demande descente depuis jeedom (le volet ne bouge pas)
17h17 20s appui sur la télécommande physique descente (le volet descend)
17h17 27s demande stop depuis jeedom (le volet s'arrete)
Merci !

[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4481765/AbeilleCmd.txt)

**Comment by KiwiHC16** [comment]
On:
```
[2020-04-15 16:16:35][AbeilleCmd][debug] =================> Envoi de la commande a la zigate: /dev/ttyUSB0-0092-0006-02351c010101
[2020-04-15 16:16:35][AbeilleCmd][debug]traiteLesAckRecus fct - Message 8000 status recu: 00
```

Off:
```
[2020-04-15 16:16:56][AbeilleCmd][debug] =================> Envoi de la commande a la zigate: /dev/ttyUSB0-0092-0006-02351c010100
[2020-04-15 16:16:56][AbeilleCmd][debug]traiteLesAckRecus fct - Message 8000 status recu: 00 
```

Les deux commandes semblent correctes et avoir été transmises à la Zigate.

1) Pourrais tu faire collecter de la meme facon les log AbeilleCmd et AbeilleParser quand tu fais un getLevel ?
2) Pourrais tu afficher sur la ruche la commande 
![Capture d’écran 2020-04-17 à 08 30 25](https://user-images.githubusercontent.com/8549674/79538976-b1c98080-8085-11ea-9877-dfecfe64d477.png)
renseigner l adresse 351c du volet et 01 pour le deuxieme champr et recuperer AbeilleParser ?
3) Il faudrait capturer les messages envoyées par ta télécommande. As un bon niveau d'informatique pour utiliser une sniffer ? Il te faut qussi un sniffer.

**Comment by Stefma24** [comment]
Hello,
Merci pour ton analyse.
1. voici les fichiers avec le getLevel (la réponse sur le plugin était 74%)
[AbeilleCmd1.txt](https://github.com/KiwiHC16/Abeille/files/4491970/AbeilleCmd1.txt)
[AbeilleParser1.txt](https://github.com/KiwiHC16/Abeille/files/4491971/AbeilleParser1.txt)

2. le fichier avec le SimpleDescriptorRequest
[AbeilleParser2.txt](https://github.com/KiwiHC16/Abeille/files/4491977/AbeilleParser2.txt)

3. niveau informatique, je me débrouille, mais je ne suis pas expert. j'ai dejà utilisé il y a quelques années Wireshark et je sais utiliser un fer à souder !
Soyons fous ! Quelle est la procédure / matériel à avoir ?
Bonne journée

**Comment by KiwiHC16** [comment]
3/ Sniff 
Ce n'est pas une solution sur étagère. J'ai développé un truc pour sniffer avec un JN5168 de NXP et analyser dans wireshark. Jerome-PS a repris le truc et fait des améliorations dont une une super importante. Puis j'ai repris pour mes propres besoins
Ma version, pas vraiment facile a lire:
https://github.com/KiwiHC16/Butineuse
La version de Jerome-PS, bien plus claire pour commencer:
https://github.com/Jerome-PS/JN516xSniffer

Sinon tu essayer avec : https://faire-ca-soi-meme.fr/hack/2017/03/13/hack-xiaomi-mi-smarthome-zigbee-sniffer/

Apres il existe d autre sur le net mais je ne les connais pas.

**Comment by KiwiHC16** [comment]
2/ Description

```
[2020-04-17 11:02:41][AbeilleParser][debug];type; 8000; (Status)(Not Processed); dest: Abeille1; Length: 5; Status: 00-(Success); SQN: f4; PacketType: 0043
[2020-04-17 11:02:41][AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); dest: Abeille1; SQN : f4; Status : 00; Short Address : 351c; Length : 1a; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0200 (Shade); bitField : 00; InClusterCount : 09
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0003 - General: Identify
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0004 - General: Groups
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0005 - General: Scenes
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0006 - General: On/Off
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0008 - General: Level Control
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 000A - General: Time
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0100 - Closures: Shade Configuration
[2020-04-17 11:02:41][AbeilleParser][debug]In cluster: 0015 - General: Commissioning
[2020-04-17 11:02:41][AbeilleParser][debug]OutClusterCount : 00
```

**Comment by KiwiHC16** [comment]
1/ getLevel

Cmd:
```
[2020-04-17 10:50:49][AbeilleCmd][debug]Message pulled from queue queueKeyAbeilleToCmd: CmdAbeille1/351c/ReadAttributeRequest -> EP=01&clusterId=0008&attributeId=0000
[2020-04-17 10:50:49][AbeilleCmd][debug] =================> Envoi de la commande a la zigate: /dev/ttyUSB0-0100-000e-02351c0101000800000000010000
```

Answer:
```
[2020-04-17 10:50:49][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); dest: Abeille1; SQN: c0; Src Addr : 351c; End Point : 01; Cluster ID : 0008; Attr ID : 0000; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : ->bd<-
```

Ca fonctionne bien.

**Comment by KiwiHC16** [comment]
Peux tu faire la meme manipulation avec un setLevel ? (recuperes abeilleCmd et abeilleParser).

**Comment by Stefma24** [comment]
Bonjour,
Voici les log du SetLevel
[AbeilleCmdsetlevet.txt](https://github.com/KiwiHC16/Abeille/files/4504890/AbeilleCmdsetlevet.txt)
[AbeilleParsersetlevel.txt](https://github.com/KiwiHC16/Abeille/files/4504891/AbeilleParsersetlevel.txt)
Pour le "Ca fonctionne bien" du GetLevel, c'est un bon début. ca veux dire que ca discute ! effectivement pas encore dans le même language, mais bientot !

Pour le Sniffer, je suis en cours. j'ai pris un capteur de température Aqara (JN5169).
J'ai soudé 6 fils sur les connecteurs
j'ai pris un FTDI 232 et relié le tout.
installé BeyondStudioNTX, installé le sdk 4163, récupéré ta Butineuse, suivi les paramètrages comme indiqué par ton site...
Bon pour le moment ca ne discute pas encore, le lien COM ne semble pas passer entre le FTDI et le capteur (enfin c'est mon diagnostique à cet instant !)

A bientôt

**Comment by tcharp38** [comment]
Salut @Stefma24 
J'ai moi aussi des Profalux mais ca fonctionne plutot bien, en dehors de l'etat affiché qui n'est pas souvent en ligne avec la réalité.
Ceci dit ton pb semble être similaire aux soucis que j'ai eu lors de l'inclusion. Je crois me souvenir avoir recommencé 1 ou 2 fois avant que ca ne fonctionne. Tout ça pour dire que de tête le processus d'inclusion de Profalux semble assez capricieux.

**Comment by Stefma24** [comment]
Bonjour,
Merci @tcharp38, malheureusement j'ai essayé d'inclure mes volets plusieurs fois, et cela n'a rien changé. Si, j'ai appris à faire un reset du volet ! car j'avais perdu la liaison volet / télécomande.
Pour @KiwiHC16,
voici le résultat du sniff en format Wireshark (je peux evidemment te le fournir en un autre format).
[Wiresharkvolet210420.zip](https://github.com/KiwiHC16/Abeille/files/4511294/Wiresharkvolet210420.zip)
j'ai procédé ainsi :
17h20 et entre 35s / 50s j'ai lancé Wireshark
17h21 14s j'ai fait un Get level depuis jeedom réponse 100%
17h21 25 j'ai fait un descendre avec la télécomande physique
17h21 34 Stop (télécommande physique)
17h21 41 GetLevel (Jeedom) résultat 65%
17h21 50 decendre (physique)
lors de cette commande, le volet a fait un descendre / monté / descendre tout seul (ca arrive suite à probalement une résistance trop importante sur le moteur)
17h22 16 le volet s'arrête tout seul, il est tout en bas
17h22 22 GetLevel (Jeedom) résultat 0%
17h22 34 monter (physique)
17h22 44 Stop (physique)
17h22 51 GetLevel (Jeedom) résultat 44%
17h23 00 monter (physique)
17h23 14 le volet s'arrête tout seul, il est tout en haut
17h23 22 GetLevel (Jeedom) résultat 100%

J'espère que ca peut t'aider !
Merci

**Comment by Stefma24** [comment]
Salut,
voici le fichier.
[Inclusion.zip](https://github.com/KiwiHC16/Abeille/files/4516936/Inclusion.zip)
Pour ma culture perso, il faut que ce soit avec un nouvel appareil ou une "ré-inclusion" peut te convenir ? Ici c'est un nouveau capteur de porte Aquara qui se nomme 9e0C.
A ta dispo pour faire des scann

**Comment by KiwiHC16** [comment]
Super je vais regarder. 
Il faut que ce soit une nouvelle inclusion. 
Le zigbee cherche à minimiser le nombre de fois que la clef est envoyée dans les airs. Une fois que la zigate a envoyé la clef à un device elle ne lui renverra pas sauf s il quitte le réseau officiellement et revient.

**Comment by Stefma24** [comment]
Hello,

J’ai fait un Sniff d’un monter/ Descendre avec la télécommande et depuis jeedom.
[teleco vs abeille.zip](https://github.com/KiwiHC16/Abeille/files/4623254/teleco.vs.abeille.zip)
A ce que je comprends, la télécommande physique demande au volet un « move » dans levelcontrol (cluster 08) avec Up ou Down
Alors que Abeille, lui, demande un « OnOff » (cluster 06) avec On ou Off,

J’ai bien tenté de faire envoyer à la Zigate une demande move, avec une action créée dans le volet avec un « sendCmd » et un payload EP=01&targetEndpoint=01&clusterId=0008&attributeId=01&AttributeType=01&value=255
mais la traduction en langage Zigate / zigbee est une science que je ne maîtrise pas du tout ! Et donc,… il ne se passe rien !
 
A tout hasard, j’ai inclus un autre de mes volets roulants (97ee). Comme cela on a la liste des clusters, mais tu dois déjà avoir cela. 
![cluster](https://user-images.githubusercontent.com/63648068/81838135-01e11900-9546-11ea-9bae-d35ec411f03c.PNG)
Lors de cette inclusion, j’ai un équipement supplémentaire, inconnu au bataillon (icône petite abeille avec un point d’interrogation), qui est arrivé (a530). Il s’agit de la télécommande,
Elle est toujours présente, et discute régulièrement, car pas en timeout.
[inclusion volet 97ee.zip](https://github.com/KiwiHC16/Abeille/files/4623258/inclusion.volet.97ee.zip)

Voilà, Si ça peut aider à faire avancer la chose...
Bonne journée

**Comment by KiwiHC16** [comment]
Ok, je peux lire les deux captures. Il faut que je regardes les details.

**Comment by Stefma24** [comment]
Hello,
Super, pas de problème, merci pour ton travail.

Pour info, j’ai également une télécommande Zoé
J’ai vu que @dams74 avait réussi à inclure la télécommande Zoé https://github.com/KiwiHC16/Abeille/issues/1066 grâce à la méthode de @cyrillo  
Malheureusement je n’ai pas trouvé cette méthode ! Help à qui veut bien !

Si tu veux, quand j’aurai trouvé ladite méthode, je peux tenter de sniffer cette inclusion. 
As tu besoin des logs d’Abeille en même temps ? Et si oui lesquels ?
A bientôt

**Comment by dams74** [comment]
Salut
Tu trouveras le méthode dans le message de cyrililo du 19 février
https://community.jeedom.com/t/zigate-volets-profalux-2019-zigbee-probleme/16234/15

@+

**Comment by Stefma24** [comment]
Bonjour tout le monde !

Merci @dams74, j’ai suivi la procédure de @cyrillo, j’ai pas mal galéré pour inclure la ZOE, mais je pense avoir réussi.
Je retrouve mon fonctionnement d’avant sur jeedom (stop et Get level qui fonctionnent, le reste viendra plus tard) + la ZOE qui gère mes volets.
J’ai les petites télécommandes physiques qui sont toutes remontées dans Abeille et actives (pas en timeout), contrairement à la ZOE qui, elle, est passée en TimeOut juste après son inclusion. (mais qui pilote bien les volets).

Pour revenir sur la procédure de @cyrillo, et si ça peut aider les prochains : au moment de l’inclusion dans abeille passer directement à l’étape 2 (l’inclusion en elle-même) sans initialiser la petite télécommande (sinon on perd l’uniformité du réseau) !
Au début, la télécommande ZOE n’a  trouvé aucun volets, et ce, à plusieurs reprises, j’ai dû faire une RAZ de la ZOE (étape A, page 2) comme vu ici.
[NSAVB015-SAV telecommande ZOE.pdf](https://github.com/KiwiHC16/Abeille/files/4689110/NSAVB015-SAV.telecommande.ZOE.pdf)

Ensuite faire un R + Stop sur une petite télécommande, comme demandé par la zoé, lancer l’inclusion dans abeille et suivre les instructions de la télécommande.

La Zoé à mis beaucoup de temps pour trouver les volets mais ça marche !  @KiwiHC16, voici le Sniff, si tu veux.
[inclusion ZOE 32c2 OK.zip](https://github.com/KiwiHC16/Abeille/files/4689105/inclusion.ZOE.32c2.OK.zip)

Bonne journée
