### ISSUE TITLE
Deux inclusions pour la création d'une abeille

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1078]
Bonjour,

Sur ma zigate 2, je note un comportement surprenant: lors de l'inclusion d'un nouvel équipement (en l'occurrence un Xiaomi Door Sensor).
Tout se passe bien sur le capteur (clignotement rapide pour confirmer l'association...), par contre, sur le plugin, rien ne se passe (pas de message de création d’objet, ni affichage de l'abeille même après rafraichissement de la page).
Si je fais un Refresh LQI, je vois pourtant bien l'objet Abeille2/7f40 dans la table des nœuds, mais depuis la page de garde ou dans Santé, rien.
Je suis obligé de faire une seconde procédure d'inclusion pour voir apparaitre correctement l'abeille (ce n'est pas pour autant que j'ai un message de création...)

Ça m'a fait ça deux fois aujourd'hui, sur deux Xiaomi Door Sensor, n'avais pas eu ce comportement sur ceux ajoutés avant-hier, et la dissociation avec l'ancienne passerelle avait bien été fait avant.

Sachant qu'il me reste 3 capteurs à migrer (dont un Door Sensor), souhaites-tu que je te prenne des logs lors de la prochaine mésaventure de ce genre? (et surtout quels logs :p )

En te remerciant pour tout

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Quand tu fais la manip il me faudrait, le log AbeilleParser et le log Abeille.

**Comment by Soyann** [comment]
OK, par contre, bien que je sois en mode debug, AbeilleParser est vide...
Edit: autant pour moi, c'est l'affichage qui était lent :p

**Comment by Soyann** [comment]
Hello, bon, je viens de finir de mettre mes derniers objets errants sur ma zigate 2, et n'ai pas reproduit le problème :(
Du coup, je clos, et relancerai si besoin (en même temps, logiquement, mon réseau ne devrait plus trop bouger, hormis quelques bascules de la zigate 1 à la zigate 2, mais ça, on verra après la prochaine maj)
Merci pour tout
++
