### ISSUE TITLE
Remplacement ancienne abeille par nouvelle (suite à remplacement device)

### ISSUE THREAD

**Issue by Dreaky255** [KiwiHC16/Abeille#1079]
Suite à un device zigbee xiaomi tombé en panne (capteur temp/hum), j’en ai commandé un et souhaite remplacer l’ancien par le nouveau (pour garder le lien des commandes existantes ainsi que l’historique).

Il semble que le plugin prévoit ce [cas d’utilisation](http://kiwihc16.free.fr/Remplacement.html#remplacement), par contre y’a pas mal de warning en début de la doc :

> Attention Attention, cette manipulation n’est pas sans risque car je n’ai pas la maitrise de tout.
> Attention Cette fonction était intéressante dans les premières versions d’Abeille car le changement d’adresse des équipements zigbee n’était pas géré. Maintenant c’est automatique et donc le remplacement manuelle non nécessaire. A n’utiliser que pour des besoins très spécifiques.
> Attention La méthode décrite ci dessous est valable pour les versions d’Abeille jusqu’à Decembre 2019. Ensuite la version multi zigate est apparau et demande une adaptation de la procedure ci dessous. Les adresses doivent être complete comme Abeille/xxxx et Abeille3/yyyy t non plus que xxxx et yyyy.

Notamment un qui m’interpelle : 

> Cette fonction était intéressante dans les premières versions d’Abeille car le changement d’adresse des équipements zigbee n’était pas géré. Maintenant c’est automatique.

 Comment effectuer ce changement **automatique** ?

J’ai bien tenté la manip manuelle du « device replacement » de la doc (en respectant bien les adresses "Abeille1/xxxx"), mais visiblement cela ne fait rien du tout.
Quelle est la marche à suivre svp ?

Merci d’avance !

PS : Je tourne sur la dernière version stable disponible, et possède une seule zigate usb. Je n'ai aucun autre problème, tout fonctionne très bien sinon.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Regardes ici:
http://kiwihc16.free.fr/Remplacement.html#gestion

Consideres dans le texte que le fantome est ton ancien capteur.

**Comment by Dreaky255** [comment]
Merci pour l'info. Mais quid de l'historique avec la méthode de remplacement ? Mon historique sur ma température par exemple sera-t-il conservé ?

**Comment by KiwiHC16** [comment]
Dans la commande tu trouveras la commande pour transférer l historique, similaire au remplacement de cmd mais c est dans un autre Tab.

**Comment by Dreaky255** [comment]
Impeccable, j'ai tout récupéré via cette méthode (lien des commandes et historique récupéré).

Merci beaucoup pour le support, je clôture l'issue.
