### ISSUE TITLE
detecteur d'ouverture de porte XIAOMI MCCGQ01LM

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#108]

**Comment by KiwiHC16** [comment]
Forum Jeedom:
RMOREIRA a écrit :
Bonjour,
Merci pour ton aide 
j'ai finalement eu le temps de fixer certains problèmes et j'ai finalement quelques résultats.
par contre je rencontre un problème non évoqué (je pense) .
lors de association du détecteur de mouvement XIAOMI aqara rtcgq11lm abeille créer un device Abeille-50f8-Type d objet inconnu (!JSON) sans commandes idem pour le detecteur d'ouverture de porte XIAOMI MCCGQ01LM, une idée du problème, je n'ai pas rencontrer de problème sur le bouton ROND XIAOMI WXKG01LM il est parfaitement reconnu.

**Comment by lukebr91** [comment]
![image](https://user-images.githubusercontent.com/35848408/36622351-10d6140a-18fd-11e8-8c2c-17417ae8cf6f.png)

![image](https://user-images.githubusercontent.com/35848408/36622386-306c45e6-18fd-11e8-8d76-ac9f032519ca.png)

JSON : copier coller du lumi.sensor_switch.aq2

Résultat nouvelle inclusion en automatique : 
![image](https://user-images.githubusercontent.com/35848408/36622671-bc447718-18fe-11e8-8fd6-00201ce69b36.png)

**Comment by KiwiHC16** [comment]
Ok je vais l ajouter demain matin dans les objets. Merci.

**Comment by KiwiHC16** [comment]
Je viens d ajouter dans le master. Peux tu tester ?

**Comment by KiwiHC16** [comment]
Ca fonctionne chez moi.
