### ISSUE TITLE
Redémarrage Jeedom: Alerte changement de l adresse IEEE pour un equipement !!! ( Ruche : 00158d0001ed464f =>00158d0001ed4043

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1080]
Yop

Je viens de faire un essai de redémarrage de Jeedom pour vérifier qu'Abeille marche toujours sans problèmes:
Je note sur le dashboard deux équipements de ma Zigate1 en rouge (comme s'ils étaient en TimeOut), pourtant dans Santé ils sont OK (mais plus de remonté de valeurs...)
![image](https://user-images.githubusercontent.com/46709337/79344225-d3b0ef00-7f2f-11ea-8d3e-5ab878cbc2a8.png)

J'ai le message suivant: Alerte changement de l adresse IEEE pour un equipement !!! ( Ruche : 00158d0001ed464f =>00158d0001ed4043
La ruche de la Zigate 2 est en TimeOut, et les abeilles après ne répondent plus...
-> Redémarrage du Demon: les objets de la zigate 2 se créer tout seul avec des Missing IEEE; perte des répéteurs, et création également d'un nouvel objet avec le même IEEE (pas de mise à jour...)

Bref, help!

Ci joint les logs avec un redémarrage vers 15h10

[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4481440/AbeilleCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4481441/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4481442/Abeille.txt)

![image](https://user-images.githubusercontent.com/46709337/79343813-2e961680-7f2f-11ea-969a-95b21357151a.png)

![image](https://user-images.githubusercontent.com/46709337/79345142-060f1c00-7f31-11ea-95f8-a140c8275a60.png)

**Comment by Soyann** [comment]
Bon, vu que la ruche 2 était en timeout, j'ai essayé de la supprimer et de redémarrer le demon: depuis c'est encore pire (IEEE missing sur la ruche):
![image](https://user-images.githubusercontent.com/46709337/79356065-c818f480-7f3e-11ea-90f5-ac44c1defb06.png)


Relance des dépendances / Démon / Redémarrage de Jeedom: idem

**Comment by Soyann** [comment]
Pourtant l'abeille d'une porte qui m'a créé un fantôme depuis la zigate 2 fonctionne... je suis largué et désespéré

**Comment by Soyann** [comment]
Je suis bon pour reseter tous mes objets (je commence par mes routeurs), car un simple réveil ne suffit pas (au moins sur les prises et lumières, ce qui est d'autant plus agaçant vu comment l'appairage en direct entre les interrupteurs et les ampoules est capricieuse)

**Comment by Soyann** [comment]
Mes répéteurs Ikea ne veulent plus s'enregistrer...

**Comment by Soyann** [comment]
J'en peux plus des notifications en boucle sur mon téléphone me disant que les objets ne communiquent plus (une 30enes de notif toutes les 5 min, c'est méga stressant)

**Comment by Soyann** [comment]
HELP stp

**Comment by Soyann** [comment]
On dirait qu'un répéteur s'est enregistré, mais il n'apparait pas dans Abeille, et si je fais un refresh et que j'affiche derrière, ça me dit "fichier vide, rien à traiter"

**Comment by Soyann** [comment]
Les xiaomi door sensor ne veulent pas non plus s'inclure

**Comment by Soyann** [comment]
la ruche 2 a récupéré son IEEE après être passé sur la master!

**Comment by Soyann** [comment]
Mais ça a pas solutionné le reste :(

**Comment by graouxx** [comment]
Hello,

Je ne sais pas si ça peut aider, j'ai eu le même message d'erreur en démarrant un second jeedom (test migration v4) à partir d'une sauvegarde de mon premier jeedom. En revanche cela n'a causé aucun soucis dans mes équipements. (j'ai eu le message dans le nouveau jeedom, puis dans l'ancien quand j'ai arrêté le nouveau)

> Alerte changement de l adresse IEEE pour un equipement !!! ( Ruche : XXXX =>XXXX)

**Comment by Soyann** [comment]
Merci Graouxx pour ton message, car oui, il a aidé indirectement: je suis allé voir dans la configuration du plugin, dans la section 'Connection' (ne devrait-il pas s'appeler 'Connexion' ? :p ), et ai constaté que sur le port de la zigate 1 était renseigné la zigate 2, et dans le port de ma zigate 2 mon RFXCom (tu m'étonnes que ça marche moins bien! )
Du coup, quand j'ai fais un refresh LQI Z1, il m'a retrouvé mes ampoules!, par contre pour le refresh LQI Z2, j'ai eu un message : d'erreur (pas eu le temps de le noté, mais un truc du genre impossible de récupérer la table). 
J'ai donc supprimé les ruches, et depuis, je constate que mes deux ruches ont le même IEEE
![image](https://user-images.githubusercontent.com/46709337/79434452-b121e300-7fce-11ea-9d64-7959376641de.png)

Depuis, je sèche (et pense que plus rien ne fonctionne)
Edit: si les ampoules sont contrôlable depuis la zigate 1!

**Comment by graouxx** [comment]
J'ai eu le même souci de conf de port il y a quelques semaines (ma zigate s'est retrouvée sur mon port RFxcom comme toi)
Il me semble que c'est quand j'ai fait la mise à jour du plugin avec la version "multi zigate".

Essaie peut être de supprimer une des 2 ruches pour avoir un nouvel IEEE ?

**Comment by Soyann** [comment]
Ouai, déjà fait, mais le résultat est le même (j'ai même supprimé les deux ruches, mais ça donne la capture d'écran faite juste au dessus)
On dirait que tout fonctionne mieux (j'ai beaucoup moins de rouge dans santé, je vais commencer à jeter un oeil aux TimeOut restant)
par contre, impossible de faire un refresh LQI Z2:
![image](https://user-images.githubusercontent.com/46709337/79437682-d6185500-7fd2-11ea-8886-9c8c6a6a149b.png)

Plusieurs questions : 
-Est-ce que ce changement de port a été fait suite au redémarrage ou à la mise à jour sur le Master?
-Les prises inclus hier soir, que je pensais sur la zigate 1, mais qui au final ont été fait sur la zigate 2 (et qui ne marchent plus) vont se négocier par la suite (si je les inclus de nouveau sur la zigate 1, ne va-t-il pas rester une trace sur la zigate 2 qui mettrait le souque par la suite?) ....
-comment solutionner ce problème de timeout sur les ruches avec le même IEEE?
![image](https://user-images.githubusercontent.com/46709337/79438503-e1b84b80-7fd3-11ea-8475-6584801e9724.png)
![image](https://user-images.githubusercontent.com/46709337/79438529-ec72e080-7fd3-11ea-8947-0f004b244238.png)

**Comment by KiwiHC16** [comment]
Ce qui c'est probablement passé est que les devices créés par l'OS (Linux) ont été mélangés.
Ils sont créés lors du demarrage de Linux.
par exemple /dev/ttyUSB2 est devenu /dev/ttyUSB1, etc...
Dans ce cas, c'est la grouille.

Je n'avais pas trop prévu ce soucis ....

Maintenant comment le géré ?

Peux tu partager le résultat de la commande 
> dmesg

en ssh  ?

**Comment by KiwiHC16** [comment]
Ou tu peux avoir la meme info dans Jeedom:

menu OS/DB:
![Capture d’écran 2020-04-16 à 11 24 05](https://user-images.githubusercontent.com/8549674/79439256-e16c8000-7fd4-11ea-8134-05be1f577d3f.png)

Systeme -> Administration -> lancer:
![Capture d’écran 2020-04-16 à 11 24 13](https://user-images.githubusercontent.com/8549674/79439270-e6313400-7fd4-11ea-9511-4945e787c68e.png)

dmesg:
![Capture d’écran 2020-04-16 à 11 24 23](https://user-images.githubusercontent.com/8549674/79439279-eaf5e800-7fd4-11ea-81ca-44fff4c9e871.png)

**Comment by Soyann** [comment]
.......

[    3.050419] ACPI: bus type USB registered
[    3.050483] usbcore: registered new interface driver usbfs
[    3.050507] usbcore: registered new interface driver hub
[    3.050571] usbcore: registered new device driver usb
[    3.058139] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 1
[    3.059300] xhci_hcd 0000:00:14.0: hcc params 0x200077c1 hci version 0x100 quirks 0x0000000081509810
[    3.059315] xhci_hcd 0000:00:14.0: cache line size of 64 is not supported
[    3.059757] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.18
[    3.059762] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.059764] usb usb1: Product: xHCI Host Controller
[    3.059767] usb usb1: Manufacturer: Linux 4.18.0-0.bpo.1-amd64 xhci-hcd
[    3.059769] usb usb1: SerialNumber: 0000:00:14.0
[    3.060199] hub 1-0:1.0: USB hub found
[    3.060232] hub 1-0:1.0: 7 ports detected
[    3.061675] xhci_hcd 0000:00:14.0: xHCI Host Controller
[    3.061686] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 2
[    3.061697] xhci_hcd 0000:00:14.0: Host supports USB 3.0  SuperSpeed
[    3.061898] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.18
[    3.061902] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.061905] usb usb2: Product: xHCI Host Controller
[    3.061907] usb usb2: Manufacturer: Linux 4.18.0-0.bpo.1-amd64 xhci-hcd
[    3.061910] usb usb2: SerialNumber: 0000:00:14.0
[    3.062237] hub 2-0:1.0: USB hub found
[    3.062265] hub 2-0:1.0: 6 ports detected
[    3.062668] usb: port power management may be unreliable

...

[    3.401168] usb 2-1: new SuperSpeed Gen 1 USB device number 2 using xhci_hcd
[    3.440515] usb 2-1: New USB device found, idVendor=0bda, idProduct=0411, bcdDevice= 1.17
[    3.440527] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.440536] usb 2-1: Product: 4-Port USB 3.0 Hub
[    3.440541] usb 2-1: Manufacturer: Generic
**_[    3.451452] hub 2-1:1.0: USB hub found_**
[    3.452666] hub 2-1:1.0: 4 ports detected
[    3.556136] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    3.579231] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    3.725533] usb 1-1: New USB device found, idVendor=0bda, idProduct=5411, bcdDevice= 1.17
[    3.725547] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.725557] usb 1-1: Product: 4-Port USB 2.0 Hub
[    3.725565] usb 1-1: Manufacturer: Generic
**_[    3.729573] hub 1-1:1.0: USB hub found_**
[    3.731130] hub 1-1:1.0: 4 ports detected
[    3.800965] usb 2-1.1: new SuperSpeed Gen 1 USB device number 3 using xhci_hcd
[    3.838336] usb 2-1.1: New USB device found, idVendor=0bda, idProduct=0411, bcdDevice= 1.17
[    3.838353] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.838364] usb 2-1.1: Product: 4-Port USB 3.0 Hub
[    3.838373] usb 2-1.1: Manufacturer: Generic
**_[    3.855032] hub 2-1.1:1.0: USB hub found_**
[    3.857157] hub 2-1.1:1.0: 4 ports detected
[    3.956261] usb 1-2: new full-speed USB device number 3 using xhci_hcd
[    4.000158] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    4.022011] systemd[1]: Detected architecture x86-64.
[    4.022989] systemd[1]: Set hostname to <JeedUP>.
**_[    4.140098] usb 1-2: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[    4.140111] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.140154] usb 1-2: Product: ZiGate
[    4.140162] usb 1-2: Manufacturer: Silicon Labs
[    4.140170] usb 1-2: SerialNumber: 0001_**
[    4.188109] usb 1-1.1: new high-speed USB device number 4 using xhci_hcd

...

[    4.307218] usb 1-1.1: New USB device found, idVendor=0bda, idProduct=5411, bcdDevice= 1.17
[    4.307225] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    4.307228] usb 1-1.1: Product: 4-Port USB 2.0 Hub
[    4.307231] usb 1-1.1: Manufacturer: Generic
[    4.308838] hub 1-1.1:1.0: USB hub found
[    4.309728] hub 1-1.1:1.0: 4 ports detected
[    4.402830] systemd-journald[264]: Received request to flush runtime journal from PID 1
[    4.428063] usb 1-3: new full-speed USB device number 5 using xhci_hcd

...

**_[    4.587496] usb 1-3: New USB device found, idVendor=0403, idProduct=6015, bcdDevice=10.00
[    4.587502] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.587505] usb 1-3: Product: RFXtrx433XL
[    4.587508] usb 1-3: Manufacturer: RFXCOM
[    4.587510] usb 1-3: SerialNumber: DO2Y30TG_**
[    4.664079] usb 1-1.4: new full-speed USB device number 6 using xhci_hcd

...

**_[    4.800897] usb 1-1.4: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[    4.800903] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.800906] usb 1-1.4: Product: CP2102 USB to UART Bridge Controller
[    4.800908] usb 1-1.4: Manufacturer: Silicon Labs
[    4.800911] usb 1-1.4: SerialNumber: 0001_**

...

[    4.917706] usbcore: registered new interface driver usbserial_generic
[    4.917737] usbserial: USB Serial support registered for generic
[    4.946657] usbcore: registered new interface driver cp210x
[    4.946694] usbserial: USB Serial support registered for cp210x
**_[    4.946781] cp210x 1-2:1.0: cp210x converter detected
[    4.954245] usb 1-2: cp210x converter now attached to ttyUSB0
[    4.954369] cp210x 1-1.4:1.0: cp210x converter detected
[    4.957240] usb 1-1.4: cp210x converter now attached to ttyUSB1_**

...

**_[    4.963906] usb 1-1.1.1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=82.41
[    4.963912] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0_**

...

[    5.052075] usb 1-1.1.4: new full-speed USB device number 8 using xhci_hcd

...

    5.129958] usbcore: registered new interface driver ftdi_sio
**_[    5.129997] usbserial: USB Serial support registered for FTDI USB Serial Device
[    5.130159] ftdi_sio 1-3:1.0: FTDI USB Serial Device converter detected
[    5.130269] usb 1-3: Detected FT-X
[    5.139082] usb 1-3: FTDI USB Serial Device converter now attached to ttyUSB2
[    5.171876] usb 1-1.1.4: New USB device found, idVendor=0658, idProduct=0200, bcdDevice= 0.00
[    5.171882] usb 1-1.1.4: New USB device strings: Mfr=0, Product=0, SerialNumber=1
[    5.171886] usb 1-1.1.4: SerialNumber: 32303136-3131-3033-3030-303032363234_**

...

[    5.295274] usbcore: registered new interface driver btusb

...

[    5.354879] usbcore: registered new interface driver cdc_acm

**Comment by KiwiHC16** [comment]
Dans ton cas on peut imaginer le cas suivant:
Tu as Jeedom avec une Zigate A sur /dev/ttyUSB0 et RFXCOM sur /dev/ttyUSB1.
Tu ajoutes une Zigate B qui prend le numero suivant donc 2 -> /dev/ttyUSB2.

Tu reboot
L'OS regardes sur les Bus USB les devices et trouve en premier Zigate B et lui donne /dev/ttyUSB0, trouve ensuite Zigate A et lui donne /dev/ttyUSB1 etc

et c 'est le bazar...

**Comment by Soyann** [comment]
![image](https://user-images.githubusercontent.com/46709337/79439872-a28afa00-7fd5-11ea-8613-28cf6c7a1d8f.png)

**Comment by Soyann** [comment]
En effet, ma zigate 2 est sur le port ttyUSB0

**Comment by KiwiHC16** [comment]
Il faut que tu remettes les Zigates sur leur bonnes positions.
Laquelle doit aller sur Zigate 1 et laquelle doit aller sur Zigate 2 ?

**Comment by KiwiHC16** [comment]
Peux tu aussi me partager une photo de chaque zigate ?

**Comment by Soyann** [comment]
Quote: Il faut que tu remettes les Zigates sur leur bonnes positions.
Laquelle doit aller sur Zigate 1 et laquelle doit aller sur Zigate 2 ?
C'est ce que j'ai fait, et qui a fait repartir le bouzin :p

**Comment by Soyann** [comment]
Sur la photo, on voit ma Zigate 1 sur le hub avec la clé bluetooth & la clé ZWave; Le RFxcom et la Zigate 2 (sécurité) directement sur mon Z83
![IMG_20200416_113848](https://user-images.githubusercontent.com/46709337/79441513-9e5fdc00-7fd7-11ea-94b7-5900795351f8.jpg)

**Comment by KiwiHC16** [comment]
Normalement ca doit devrait être ok mais tu va devoir faire du menage pour virer tous les fantomes ;-(

**Comment by Soyann** [comment]
Plus de fantômes (j'ai viré les objets créé depuis hier)

**Comment by Soyann** [comment]
Mes trois problèmes à régler:
![image](https://user-images.githubusercontent.com/46709337/79441884-18906080-7fd8-11ea-9a64-2a1975772e2e.png)
-Même IEEE pour les deux ruches
-Gérer l'inclusion des mes prises qui ont été fait sur la mauvaise zigate hier
-Le Refresh LQI Z2 qui ne marche plus (lié au pb d'IEEE de pense)

**Comment by KiwiHC16** [comment]
Etape par étape:
Fait un reset sur les deux zigate depuis les commandes des ruches pour recuperer le IEEE.

**Comment by KiwiHC16** [comment]
Deuxieme Zigate:

[ 4.140098] usb 1-2: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[ 4.140111] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4.140154] usb 1-2: Product: **_ZiGate_**
[ 4.140162] usb 1-2: Manufacturer: Silicon Labs
[ 4.140170] usb 1-2: SerialNumber: 0001

**Comment by KiwiHC16** [comment]
Premiere Zigate:

[ 4.800897] usb 1-1.4: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[ 4.800903] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4.800906] usb 1-1.4: Product: **_CP2102 USB to UART Bridge Controller_**
[ 4.800908] usb 1-1.4: Manufacturer: Silicon Labs
[ 4.800911] usb 1-1.4: SerialNumber: 0001

**Comment by KiwiHC16** [comment]
Peux tu me dire d ou vient le premier module USB et le second module USB ?

**Comment by Soyann** [comment]
je dirais l'inverse: la zigate 1 est sur le hub (donc UART Bridge Controller), et zigate 2 directement sur la machine

**Comment by KiwiHC16** [comment]
Ok j ai changé Premiere/Deuxieme dans mes commentaires.

**Comment by KiwiHC16** [comment]
As tu acheter les deux zigates à zigate.fr ou as tu des modules acheté ailleurs ?

**Comment by Soyann** [comment]
Je n'ai aucune commande sur les deux ruches...
![image](https://user-images.githubusercontent.com/46709337/79443501-2e9f2080-7fda-11ea-9fd6-663d3883b257.png)

**Comment by KiwiHC16** [comment]
Si tu partages ton ecran avaec anydesk.com je suis dispo pour 30 minutes.

**Comment by KiwiHC16** [comment]
Sur ta phot une zigate est à gauche de ton RFXCOM avec la led bleue et l 'autre est en haut a droite avec led bleu et rouge ?

**Comment by Soyann** [comment]
code anydesk par mail

**Comment by Soyann** [comment]
mon clavier ne répond plus sur la VM où tu as la main

**Comment by Soyann** [comment]
teamviewer?

**Comment by Soyann** [comment]
Tout est reparti, je n'ai plus de module en TimeOut :)
Pour les prise Ikea inclus hier soir sur la mauvaise Zigate, j'ai bien fait une remove IEEE sur la zigate 2 avant de les remettre sur la zigate 1, et tout va bien (je suis soulagé)
Seul problème restant suite à cette mésaventure: je ne peux plus faire de refresh LQI Z2 et retombe sur ce message:
![image](https://user-images.githubusercontent.com/46709337/79453378-eb4cae00-7fe9-11ea-970a-f735084d83ce.png)

Bref, je revis, et te remercie pour ton intervention (j'ouvre une autre issue pour ce dernier problème)
