### ISSUE TITLE
Position Store Ikea

### ISSUE THREAD

**Issue by nicoriviere** [KiwiHC16/Abeille#1081]
Bonjour,
Ça fait quelques jours que j’essaye d’intégrer des stores Ikea Fyrtur/Kadrilj sans succès. (je précise que j'avais pu les intégrer il y a quelques semaines mais j'avais laissé en suspens faute de retour d'information sur la position d'ouverture). Aujourd'hui, l’équipement remonte bien à l’inclusion mais sans les commandes nécessaires à la montée descente des stores (ni position du reste) j’ai ce message :

getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/…/…/…/core/config/devices/KADRILJrollerblind/KADRILJrollerblind.json will send back default template.

Peux-tu regarder? Merci beaucoup

**Comment by KiwiHC16** [comment]
As tu un lien vers le site IKEA pour ces stores ?

**Comment by nicoriviere** [comment]
Salut,

Ce sont les mêmes que les FYRTUR… la seule différence c’est que ce ne sont pas des stores occultants :

https://www.ikea.com/fr/fr/p/kadrilj-store-a-enrouleur-sans-fil-a-pile-gris-80408123/

Merci pour la prise en charge :)

**Comment by KiwiHC16** [comment]
Je viens de faire un modele

Le fichier est dispo à :
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/KADRILJrollerblind

Mets le sur ton systeme en creant un repertoire KADRILJrollerblind.

Sinon sera dispo dans la prochaine version.

Et dis moi si cela fonctionne.

**Comment by nicoriviere** [comment]
Super merci ! peux-tu juste me dire à quel endroit je dois créer le répertoire?

**Comment by nicoriviere** [comment]
J'ai trouvé ça fonctionne merci beaucoup!! Je vais tester ça aujourd'hui... Merci encore!

**Comment by nicoriviere** [comment]
Edit: il n'y a pas de retour d'info sur la position?

**Comment by KiwiHC16** [comment]
Non, pas de retour d'info. Je ne sais pas si le store connait ca position. Il y a une histoire de "tarage de la position haute et de la position basse (voir autre issue) mais je n'ai pas regardé le sujet encore.

**Comment by nicoriviere** [comment]
Pas de soucis c'est déjà très bien!!! Merci encore et bon courage!

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
https://github.com/a4refillpad/Ikea/blob/master/devicetypes/IKEA-window-blinds#L77

private getCLUSTER_BATTERY_LEVEL() { 0x0001 }
private getCLUSTER_WINDOW_COVERING() { 0x0102 }
private getCOMMAND_OPEN() { 0x00 }
private getCOMMAND_CLOSE() { 0x01 }
private getCOMMAND_PAUSE() { 0x02 }
private getCOMMAND_GOTO_LIFT_PERCENTAGE() { 0x05 }
private getATTRIBUTE_POSITION_LIFT() { 0x0008 }
private getATTRIBUTE_CURRENT_LEVEL() { 0x0000 }
private getCOMMAND_MOVE_LEVEL_ONOFF() { 0x04 }

**Comment by KiwiHC16** [comment]
#1011 Reglage butée Store Ikea

**Comment by KiwiHC16** [comment]
get 0x0008 (Level) - 0x0000 (Current Level) => Unsupported attribute

Table 5.2  Clusters Used in the HA Profile
Functional Domain - Cluster Name - Cluster ID
Closures - Window Covering  - 0x0102

Table 9.20  Window Covering Attribute Set
Attribute Set Identifier - Description 
0x0000 - Window Covering Information
0x0010 - Window Covering Settings 

get 0x0102 (Window Covering) - 0x0000 (Type) => 0x00 - Rollershade 
get 0x0102 (Window Covering) - 0x0001 (PhysicalClosedLimit – Lift (cm)) => Unsupported attribute
get 0x0102 (Window Covering) - 0x0002 (PhysicalClosedLimit – Tilt (tenth of a degree)) => Unsupported attribute
get 0x0102 (Window Covering) - 0x0003 (Current Position) => Unsupported attribute
get 0x0102 (Window Covering) - 0004 => Unsupported attribute
get 0x0102 (Window Covering) - 0005 => Unsupported attribute
get 0x0102 (Window Covering) - 0006 => Unsupported attribute
get 0x0102 (Window Covering) - 0x0007 (Config/Status) => 0x03 (Default) - Table 9.23 - Online + Operational
get 0x0102 (Window Covering) - 0x0008 (Current Position Lift Pourcentage) => Success.
Volet Top Butée: 0
Volet Bottom Butée: 100
get 0x0102 (Window Covering) - 0x0009 (Current Position Tilt Pourcentage) =>  Unsupported attribute.

Table 9.26  Commands Received by the Window Covering Server Cluster
In ligne with Zigate command:
               // 0 = Up/Open
                // 1 = Down/Close
                // 2 = Stop
                // 4 = Go To Lift Value (extra cmd : Value in cm)
                // 5 = Go To Lift Percentage (extra cmd : percentage 0-100)
                // 7 = Go To Tilt Value (extra cmd : Value in cm)
                // 8 = Go To Tilt Percentage (extra cmd : percentage 0-100)
                // <extra command : uint8_t or uint16_t >
Command: 0,1,2 implemented dans Abeille et fonctionnent.
Can't get 5 to work. Si je mets la commande 05 suivi d un octet XX, je vois bien 05 XX dans Wireshark. Mais le device reject la demande. Zigbee standard  (9.3.2.2.4.2  Go to Lift Percentage) dit que je devrais avoir 05-Type-Level%. Dans ce cas il y aurait un bug Zigate.

**Comment by KiwiHC16** [comment]
Dans le modele maintenant on peut recuperer la position en % du store.
Je ne parviens pas a lui demander de se positionner a une hauteur en %. Il rejete les demandes.

**Comment by KiwiHC16** [comment]
Reste a tester sur un store (pour l instant modif dans le master)

**Comment by nicoriviere** [comment]
Super nouvelle merci! Par contre je me rappelle pas trop comment récupérer le master pour tester(je sais je suis un boulet 😉)
@+ Nico

**Comment by KiwiHC16** [comment]
Je viens de publier une beta, peut être testé avec. Sinon attendre la stable qui arrive.

**Comment by KiwiHC16** [comment]
Ca fonctionne je sais le positionner à une position definie. A implementer dans le modele.

**Comment by KiwiHC16** [comment]
[fyrtur-block-out-roller-blind__AA-2172195-2_pub.pdf](https://github.com/KiwiHC16/Abeille/files/5852356/fyrtur-block-out-roller-blind__AA-2172195-2_pub.pdf)

Doc pour les histoire de min et max.

**Comment by KiwiHC16** [comment]
```
Ca fonctionne je sais le positionner à une position definie. A implementer dans le modele.
```

Fait dans master

**Comment by tcharp38** [comment]
Je clos cet antique sujet sans vie.
A reouvrir si nécessaire
