### ISSUE TITLE
Konke

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1083]
rtanpion
16h
Bonjour,

@kiwihc16, je viens d’intégrer 2 capteurs température/humidité Konke.
Les 2 informations sont bien remontées sur chaque capteur. Par contre, les informations de batterie n’apparaissent pas dans la page récapitulative de Jeedom.
Y-a-t-il quelque chose de particulier à faire pour cela ? Ou bien est-ce un problème connu ? Ou bien n’est-ce tout simplement pas géré sur ces capteurs ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Tartanpion27** [comment]
Bonjour,
Si besoin d'informations supplémentaires, je suis disponible.

**Comment by KiwiHC16** [comment]
Il faut trouver comme les equipements Konke remonte l'information Batterie.

**Comment by KiwiHC16** [comment]
Dans mes notes je trouve:
![Capture d’écran 2020-04-16 à 10 21 06](https://user-images.githubusercontent.com/8549674/79432380-fd1f5880-7fcb-11ea-9e96-cde18699e2a3.png)

**Comment by KiwiHC16** [comment]
Je vais inclure un Konke (Faut que je le retrouve) dans mon systeme pour récupérer l info et on ne  devrait avoir qu'a ajouter les commandes qui vont bien dans le modele.

**Comment by KiwiHC16** [comment]
Je viens d 'inclure dans les commandes j'ai:
![Capture d’écran 2020-04-16 à 10 36 27](https://user-images.githubusercontent.com/8549674/79434172-42dd2080-7fce-11ea-8703-7a1fa8334c6d.png)

Et si je fais tester j'ai:
![Capture d’écran 2020-04-16 à 10 37 44](https://user-images.githubusercontent.com/8549674/79434216-512b3c80-7fce-11ea-96d7-b0990033badf.png)

Avec affichage:
![Capture d’écran 2020-04-16 à 10 46 10](https://user-images.githubusercontent.com/8549674/79435052-7e2c1f00-7fcf-11ea-8839-4de85ccf9575.png)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-04-16 à 10 39 37](https://user-images.githubusercontent.com/8549674/79434374-92bbe780-7fce-11ea-88bf-4878b9d8c5b1.png)

Qui est en ligne avec le message envoyé par le device.

**Comment by KiwiHC16** [comment]
Pardon ci dessus est avec le bouton Konke.

**Comment by KiwiHC16** [comment]
Je fais avec Temperature:
![Capture d’écran 2020-04-16 à 10 48 14](https://user-images.githubusercontent.com/8549674/79435331-c8ad9b80-7fcf-11ea-9ba9-ce007c96a825.png)

Il faut afficher la commande Batterie Volt et etendre le widget pour la rendre visible.

Ca semble fonctionner.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-04-16 à 10 57 19](https://user-images.githubusercontent.com/8549674/79436356-0ced6b80-7fd1-11ea-9093-10526a032099.png)

Pour le capteur Infra Rouge.

**Comment by Tartanpion27** [comment]
Si je clique sur tester au niveau de Batterie Volt de mes capteurs de températures, j'ai bien une information. Par contre, rien dans la page récapitulative de Jeedom.

**Comment by KiwiHC16** [comment]
Quelle est la page "récapitulative de Jeedom" ? Peux tu partager une capture d'écran ?

**Comment by Tartanpion27** [comment]
La page est Analyse >> Equipements.

Tous les équipements sur pile sont normalement dans cette page, sauf les Konke.

![page](https://user-images.githubusercontent.com/63756609/79791970-70b7c180-834e-11ea-8648-280a8eff3825.PNG)

**Comment by Tartanpion27** [comment]
Je viens d'essayer de comparer avec un autre capteur. Le Konke sort une valeur en V, alors qu'un Ikea le sort en % et un Xiaomi fournit les 2 (V et %).

**Comment by KiwiHC16** [comment]
Il faut probablement que je fasse une adaptation. Je mets ca dans la liste des trucs à faire. Quand ?

**Comment by Tartanpion27** [comment]
Ce n'est pas vital. C'est une fonction intéressante mais non urgent pour ma part.
D'autant que les piles sont quasi neuves :)

**Comment by tcharp38** [comment]
Salut @Tartanpion27 
Ce super antique sujet... t'interesse encore ?

**Comment by Tartanpion27** [comment]
Salut @tcharp38 
Non en effet, plus intéressé.

**Comment by tcharp38** [comment]
D accord merci.
Je clos. A reouvrir si ca interesse qqn.
