### ISSUE TITLE
Refresh LQI Z2 impossible

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1086]
Suite à ma mésaventure de réaffectation de ports USB #1080 il reste l'impossibilité de refaire un Refresh LQI Z2 (qui abouti sur ce message)
![image](https://user-images.githubusercontent.com/46709337/79454383-6b274800-7feb-11ea-932c-262c7764bd88.png)

De quels logs as-tu besoin?

Merci pour tout

**Comment by KiwiHC16** [comment]
Merci pour ta mesaventure car avec le code que je viens d 'ajouter ca ne devrait plus arriver. Il faut encore le tester mais semble fonctionner.

**Comment by KiwiHC16** [comment]
#1071 
Je clos cette issue.

**Comment by Soyann** [comment]
Du coup, je dois mettre à jour ma version Master? 
Si tu as le moindre doute, il y a moyen qu'on planifie ensemble cette mise à jour "au cas où..."  ;)
Même si j'ai bien galéré pendant une journée, bien contant que ça ait servit ^^

**Comment by Soyann** [comment]
De plus ça pourrait permettre que tu jettes un oeil au problème de Network graph zigate 2 qui ne s'affiche pas (mais ce coup-ci depuis un anydesk sur un mac, et non depuis une VM qui rend le clavier complètement dingue :p )
