### ISSUE TITLE
Pas de bouton inclusion

### ISSUE THREAD

**Issue by jmubamba** [KiwiHC16/Abeille#1087]
Bonjour,
Je viens d'installer une PiZiGate sur mon RPI 2 B.
La santé RPi et la santé abeille sont OK.
Par contre je n'ai pas de bouton inclusion !
Je joins des copies d'écran.
Pouvez-vous m'aider à trouver ce que j'ai raté.
Merci d'avance !
     Jean-Marie
![Ruche](https://user-images.githubusercontent.com/63742402/79481431-c66b3180-800f-11ea-98ab-cc448e75f86e.JPG)
![Plugin](https://user-images.githubusercontent.com/63742402/79481447-cf5c0300-800f-11ea-95a5-81169060f40e.JPG)

**Comment by Soyann** [comment]
Hello

Il est normal que tu n’aies pas de bouton d'inclusion, car tu n'affiches pas la ruche. As-tu configuré la partie PiZigate ? (il faut cliquer sur affiche de la section dans la configuration)

**Comment by Soyann** [comment]
Tu as la procédure d'installation là:
http://kiwihc16.free.fr/InstallationPiZiGate.html?highlight=pizigate

**Comment by KiwiHC16** [comment]
Comme dit Soyann, il faut faire la configuration en premier, pour cela il au faut que tu ouvres la partie Connection et la Partie PiZigate et renseignes les informations.

Dans la prochaine version des ameliorations à venir sur le partie PiZigate. Tiens nous au courant car je crois que les tests ont été fait sur des RPi3 et pas sure pour RPi2.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by jmubamba** [comment]
Bonjour,
Merci @Soyann et @KiwiHC16 pour les réponses très rapides.
J'avais déjà vu la procédure. Mais je m'étais emmêlé dans la config du plugin ....
Donc j'ai bien la ruche et les boutons !
Mais j'ai un problème de port. Il n'était pas visible, alors j'ai actionné le bouton activer et ça a lancé un script qui a installé pas mal de paquets, de libs.... Je rappelle j'ai un PI2B+. Jeedom est bien reparti après le reboot.
Maintenant le port est  visible mais NOK.
J'espère que vous aurez des idées !! Normalement sur le PI2 ça se déroule sans problème !!

PS: Dans le `cmdline.txt` j'ai bien supprimé `console=serial0,115200` et les gpio 0 et 2 sont bien sur OUT.
```
jeedom@raspberrypi:~ $ cat /boot/cmdline.txt
#correspond au boot sur mmcblk0p1
#dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=aeebefd0-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
#
#correspond au boot sur Disque Dur sur sda2
#dwc_otg.lpm_enable=0 console=tty1 root=/dev/sda2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

# modif PiZiGate
dwc_otg.lpm_enable=0 console=tty1 root=/dev/sda2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
```
![Plugin Zigate](https://user-images.githubusercontent.com/63742402/79554731-c5cdac00-809e-11ea-90c9-8f13c70dea76.JPG)
![Ruche](https://user-images.githubusercontent.com/63742402/79554740-c8c89c80-809e-11ea-9ea5-2d416f693957.JPG)

**Comment by tcharp38** [comment]
Salut
Quand tu dis NOK tu fais allusion à cette partie ?
![image](https://user-images.githubusercontent.com/35221038/79556506-789f0980-80a1-11ea-844c-05f4a6f22176.png)

Si oui peux tu selectionner le bon port à la place de "none" et cliquer sur "Tester" ?

**Comment by KiwiHC16** [comment]
tcharp attention a la version car les utilisateurs n'ont pas tes dernieres modifs qui n'ont pas été publiées...

**Comment by tcharp38** [comment]
Ca marche. Néanmoins ca que j'ai proposé devrait fonctionner. 
Je note quand meme que "none" + "NOK" ca perturbe donc une petite amélioration à faire de mon côté.

**Comment by jmubamba** [comment]
Désolé je vous ai embrouillé avec les écrans.

![Plugin Abeille](https://user-images.githubusercontent.com/63742402/79564193-74c5b400-80ae-11ea-8cd9-4a8ef987c665.JPG)
Le port est bien visible. Je joins des logs 
```
Execution de 'checkTTY.sh
Configuration du port /dev/ttyAMA0
= Ok
Contact de la Zigate
- Reçu 8 bytes: 02 10 02 10 02 15 95 02
= ERROR: Mauvaise réponse reçue de la Zigate.
```

Sinon **port tty -> tester** : j'avais obtenu un message (popup) du style adresse IEEE qui a changé. Mais pas le temps de lire ni de copier. Cela ne se reproduit plus.

Je ne vous avais pas prévenus, quand j'ai une galère, c'est une galère ;-)

**Comment by jmubamba** [comment]
Je viens de trouver ceci : 
`[2020-04-17 13:43:01][AbeilleParser][error];CRC is not as expected (132) is 04 `

**Comment by tcharp38** [comment]
Pas de soucis.
J'ai l'impression que l'interrogation de la zigate est perturbée par qqch.
Si tu refais "Tester" plusieurs fois ca donne toujours NOK avec le type d'erreur que tu montres ?

**Comment by jmubamba** [comment]
@tcharp38 
Lorsque je fais **tester** le statut **NOK** ne bouge pas.
Je n'ai aucun **nouveau log**. Par contre, de temps en temps j'ai le popup (@ IEEE), mais ça me semble être un warning sans grande importance. Mais je ne peux pas le capter.
Si je te suis, le port fonctionne (ça me paraît normal à ce stade) mais le script de test de la pizigate échoue sans rien dire.

**Comment by tcharp38** [comment]
J'avoue ne pas comprendre le status NOK quand tu testes le port.

1. Donc soit il y a qqch qui m'echappe
2. soit ce port n'est pas tres stable (il semble utilisé par qqn d'autre en meme temps).
3. 

Du coup oublie ce NOK pour l'instant. Si le comportement avec tes periphs est ok c'est le cas 1.
Sinon c 'est le cas 2 qui perturbe tout.
Les messages de changement IEEE ne me plaisent pas.
@KiwiHC16, tu en penses quoi ?

**Comment by jmubamba** [comment]
En date du 3 mars j'avais ce log : 
`[2020-03-03 09:05:31][AbeilleMQTTCmdTimer][DEBUG.BEN] AbeilleTimer constructor
[2020-03-03 09:05:32][AbeilleMQTTCmdTimer][DEBUG.BEN] {"debug":{"cli":1,"AbeilleTimerClass":1,"procmsg":0},"parameters_info":{"parametersCheck":"ok","parametersCheck_message":"","AbeilleAddress":"127.0.0.1","AbeillePort":"1883","AbeilleConId":"jeedom",**"AbeilleUser":"jeedom","AbeillePass":"jeedom","AbeilleTopic":"#","AbeilleSerialPort":"\/dev/ttyUSB0"**,"AbeilleQos":"0","AbeilleParentId":"1","onlyTimer":"N","IpWifiZigate":"192.168.4.1"},"Timers":[],"lastWidgetUpdate":1583222732,"lastCmdUpdate":1583222732,"RefreshWidgetRate":5,"RefreshCmdRate":1,"queueKeyAbeilleToTimer":null,"queueKeyTimerToAbeille":null,"requestedlevel":"error"}
[2020-03-03 09:05:32][AbeilleMQTTCmdTimer][DEBUG.BEN] Let s start`
 
avec mention du port ttyUSB0 ??

**Comment by jmubamba** [comment]
Je suggère de désinstaller le plugin, d'enlever la pizigate, de rebooter et de recommencer.
Qu'en pensez-vous ?

**Comment by jmubamba** [comment]
@tcharp38 je penche pour le cas 1.
Le système fonctionne depuis des mois et des années.
J'ai un rfxcom qui tourne depuis le début.
Ensuite j'ai installé une box xiaomi (d'où l'intérêt de la zigate ...).
Et j'ai rajouté un pidrive pour soulager la carte SD.

**Comment by tcharp38** [comment]
Soit. Donc si cas 1 t'inquiete pas du NOK. Mais il faudra que je comprenne pourquoi tu ne l'as jamais OK.
Ceci etant je pige pas tout ton historique 'Abeille'. Comment tu as fait pour te retrouver avec un log mentionnant ttyUSB0 ? Tu as eu un Zigate USB a un moment et tu viens de passer en PiZigate ?

**Comment by jmubamba** [comment]
Non c'est ma première install de zigate.
Au départ j'ai employé l'outil de test `~/PiZiGate-tools/test/PiZiGate_test` et j'ai eu pas mal de soucis. Le script me disait sans cesse de supprimer  `console=serial0,115200` alors que c'était déjà fait.
Mais ce paramètre était cité dans une ligne précédente, commentée par **#**, sauf que le script ne tient pas compte de ce caractère !!! Donc il échoue !!!
Donc j'ai galèré la-dessus.
J'ai beaucoup cherché sur les forums zigate et jeedom avant de tomber sur le github. Et je vous remercie tous, cela m'encourage à persévérer.
A l'instant j'ai supprimé `console=serial0,115200` partout dans le `cmdline.txt` et refais le test : 

```
jeedom@raspberrypi:~/PiZiGate-tools/test $ sudo ./PiZiGate_test /dev/ttyAMA0
[sudo] password for jeedom:
RPI Model searching ...
All it's OK
Verifying /boot/cmdline.txt ...
+ /boot/cmdline.txt seems to be OK
Searching /dev/ttyAMA0...
Port : /dev/ttyAMA0 is already used. Please read output.tmp file to get more informations about process which use /dev/ttyAMA0
jeedom@raspberrypi:~/PiZiGate-tools/test $ cat output.tmp
php       15969          www-data    5r      CHR     204,64       0t0       1156 /dev/ttyAMA0
agetty    16970              root    0u      CHR     204,64       0t0       1156 /dev/ttyAMA0
agetty    16970              root    1u      CHR     204,64       0t0       1156 /dev/ttyAMA0
agetty    16970              root    2u      CHR     204,64       0t0       1156 /dev/ttyAMA0
jeedom@raspberrypi:~/PiZiGate-tools/test $
```
Par contre j'ai besoin de vos éclaircissements, je sèche ....

**Comment by jmubamba** [comment]
PS : je m'absente un moment pour me déconfiner un peu, j'ai besoin d'air :-)

**Comment by tcharp38** [comment]
Ha ca ca me plait.
D'apres tes tests Zigate, il y a bien qqn qui se sert de ce port. D'ou conflit avec Abeille.
On est bien dans le cas 2 que je mentionnais.

Donc la priorite maintenant est de laisser Jeedom & Abeille de cote et se focaliser sur ton installation RPI.
Regarde la
php       15969          www-data    5r      CHR     204,64       0t0       1156 /dev/ttyAMA0
agetty    16970              root    0u      CHR     204,64       0t0       1156 /dev/ttyAMA0
On voit que ttyAMA0 est utilisé par "php" et "agetty". Ce dernier est a virer. Il doit y avoir une console dessus

**Comment by tcharp38** [comment]
Apres une recherche rapide il se pourrait qu'un service "getty" utilise le port. Du coup je te suggere de tenter ca (je sais pas si c'est serial-getty ou getty).
sudo systemctl mask serial-getty@ttyAMA0.service
ou
sudo systemctl mask getty@ttyAMA0.service
Puis refaire un truc du style "ps aux | grep ttyAMA0" pour voir qui l'utilise.
Je ne peux pas reproduire ca alors à toi de tester.

**Comment by jmubamba** [comment]
Moi aussi ça me plaît, on sait où chercher : 

```
AVANT
~/PiZiGate-tools/test $ ps aux | grep ttyAMA0
www-data 15969  0.0  3.3 137016 31692 ?        S    12:17   0:00 /usr/bin/php /var/www/html/plugins/Abeill                   e/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/ttyAMA0 error
root     16970  0.0  0.1   2316  1388 ?        Ss+  11:49   0:00 /sbin/agetty --keep-baud 115200,38400,960                   0 ttyAMA0 vt220
jeedom   26894  0.0  0.0   2696   584 pts/0    S+   14:11   0:00 grep --color=auto ttyAMA0

APRES ...
jeedom@raspberrypi:~/PiZiGate-tools/test $ sudo systemctl mask getty@ttyAMA0.service
[sudo] password for jeedom:
Created symlink /etc/systemd/system/getty@ttyAMA0.service → /dev/null.

jeedom@raspberrypi:~/PiZiGate-tools/test $ ps aux | grep ttyAMA0
www-data 15969  0.0  3.3 137016 31692 ?        S    12:17   0:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/ttyAMA0 error
root     16970  0.0  0.1   2316  1388 ?        Ss+  11:49   0:00 /sbin/agetty --keep-baud 115200,38400,9600 ttyAMA0 vt220
jeedom   28359  0.0  0.0   2696   552 pts/0    S+   14:12   0:00 grep --color=auto ttyAMA0

jeedom@raspberrypi:~/PiZiGate-tools/test $ sudo systemctl mask serial-getty@ttyAMA0.service
Created symlink /etc/systemd/system/serial-getty@ttyAMA0.service → /dev/null.

jeedom@raspberrypi:~/PiZiGate-tools/test $ ps aux | grep ttyAMA0
root     16970  0.0  0.1   2316  1388 ?        Ss+  11:49   0:00 /sbin/agetty --keep-baud 115200,38400,9600 ttyAMA0 vt220
www-data 30783  1.8  3.3 137016 31676 ?        S    14:13   0:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/ttyAMA0 error
jeedom   31708  0.0  0.0   2696   556 pts/0    S+   14:14   0:00 grep --color=auto ttyAMA0

jeedom@raspberrypi:~/PiZiGate-tools/test $
```
et la suite : 
![test_tty](https://user-images.githubusercontent.com/63742402/79579228-9d0ddc80-80c7-11ea-8297-2818626ffffe.JPG)

MERCIIII !

Reste à virer définitivement ce service. Je vais faire des recherches.
Bon il faut que j'aille ranger mon bazar dehors, je reviendrai pour tester le plugin.

@tout

**Comment by tcharp38** [comment]
Super !
Je vais tacher d'améliorer mon test du coup.
Bonne continuation

**Comment by tcharp38** [comment]
Pense à clore le sujet si tu le consideres tel quel.
Si sujet different, ouvre une autre "issue".

**Comment by jmubamba** [comment]
Avant de clore le sujet voici ce que j'ai fait : 

```
sudo systemctl stop getty@ttyAMA0.service
sudo systemctl disable getty@ttyAMA0.service

sudo systemctl stop serial-getty@ttyAMA0.service
sudo systemctl disable serial-getty@ttyAMA0.service
```
D'après mes manips précédentes c'est plutôt `serialgetty@ttyAMA0.service` qui fait le job, mais bon ...

Ensuite un reboot du PI2 suivi de : 
```
jeedom@raspberrypi:~ $ ps aux | grep ttyAMA0
jeedom    1379  0.0  0.0   2696   552 pts/0    S+   16:07   0:00 grep --color=auto ttyAMA0
```
Et là ça roule.
Encore merci de votre aide précieuse.
Bonne continuation @ tous.

      Jean-Marie
