### ISSUE TITLE
Ma première mise en service PiZiGate sur PI2 B+

### ISSUE THREAD

**Issue by jmubamba** [KiwiHC16/Abeille#1088]
Re-bonjour @ tous,

Mon système fonctionne "à peu près". Je décris les étapes de mise en route suite à l'élimination du service getty. A cet effet je préfère ouvrir une nouvelle "issue".
Voici quelques retours :
1. Au reboot du PI2, Abeille n'apparaît **pas attaché au port série** : 
```
ps aux | grep ttyAMA0
 jeedom    1355  0.0  0.0   2696   568 pts/0    S+   16:47   0:00 grep --color=auto ttyAMA0
```
2. Coté plugin : 
deamon NOK il faut le relancer
port tty affiche "?" il faut "**tester**" pour obtenir "**OK**"
- Coté PI suite à cette relance, abeille apparaît mais avec une **erreur**
```
ps aux | grep ttyAMA0
www-data  5550  1.3  3.3 137016 31400 ?        S    16:50   0:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/ttyAMA0 error
jeedom    7256  0.0  0.0   2696   540 pts/0    S+   16:51   0:00 grep --color=auto ttyAMA0
```
3. Coté jeedom : 
  - inclusion : la led bleue clignote
  - j'ai inclus un capteur de mouvement et de luminosité xiaomi : OK
4. Conclusion
Cela à l'air de fonctionner, mais les trois points ci-dessus ne sont pas satisfaisants et pourraient probablement conduire à un système instable.
Dans un premier temps je vais introduire des équipements *hors production*.

Cordialement @ tous,

Jean-Marie

**Comment by jmubamba** [comment]
Bonjour,

Je continue le fil des essais.
Je précise que dans le billet précédent j'avais installé un NOUVEAU capteur xiaomi. Je n'ai touché ni à la box xiaomi, ni au plugin xiaomi.

Aujourd'hui je viens d'associer un ANCIEN capteur xiaomi (**déjà** inclus dans la box xiaomi) ; je l'ai inclus sans difficulté dans la zigate.

Les deux capteurs sont opérationnels.
Les deux passerelles (zigate et xiaomi) aussi.

Pour le moment les points 1,2,3 du premier billet sont en suspens.
Cordialement @ tous,

Jean-Marie

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
ps aux | grep ttyAMA0
www-data  5550  1.3  3.3 137016 31400 ?        S    16:50   0:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/ttyAMA0 error
jeedom    7256  0.0  0.0   2696   540 pts/0    S+   16:51   0:00 grep --color=auto ttyAMA0
Coté PI suite à cette relance, abeille apparaît mais avec une erreur
```

Ce n'est pas un soucis c'est juste que tu lances le demon avec le plugin en mode 'error' pour les logs, tu peux aussi avoir 'debug',...

**Comment by KiwiHC16** [comment]
@tcharp38 , peux tu commenter les points 1 et 2 car tu joues plus que moi avec les RPI...

**Comment by KiwiHC16** [comment]
Ca peut t'aider:
http://kiwihc16.free.fr/Remplacement.html?highlight=fantome

Dans ton cas les "fantômes" seront les devices dans le plugin xiaomi.

**Comment by tcharp38** [comment]
> Ca peut t'aider:
> http://kiwihc16.free.fr/Remplacement.html?highlight=fantome
> 
> Dans ton cas les "fantômes" seront les devices dans le plugin xiaomi.

Salut Kiwi.
Quel rapport entre ce post et les equipements "fantomes" ?

**Comment by tcharp38** [comment]
@jmubamba 
Je pense que tes points 1 et 2 sont liés.
Abeille n'apparait pas attaché car le démon ne tourne pas.
Donc tu le démarre à la main.
La question du coup est la suivante: faut il que tu le démarres chaque fois toi même ou etais ce juste cette fois ?

> port tty affiche "?" il faut "tester" pour obtenir "OK"
Normal. Le test n'est pas automatique aujourd hui dans la mesure ou ca prend un peu de temps (arret du démon, test, puis redémarrage)

> Coté PI suite à cette relance, abeille apparaît mais avec une erreur
Tu as déja la réponse. Il s'agit juste du niveau de "log"

Bref, je ne vois plus de soucis de ton côté. Je me trompe ?

**Comment by KiwiHC16** [comment]
Le rapport est que d'apres ce que je comprends il a des equipements xiaomi en passant par la gateway xiaomi [A] et le plugin associé et qu'il les associe mainteant avec la zigate et le plugin Abeille [B].
Il va avoir donc un objet avec [A] et un objet avec [B], soit deux objets dans Jeedom alors qu'il n'a qu'un équipement physique. S'il ne veut pas perdre les historiques, les scenariii, ... il peut utiliser cette méthode. 
Mais j'ai amené peut etre plus de confusion qu'autre chose.
@jmubamba si ce n'est pas clair oubli mon point et focalisons sur les dernieres questions de @tcharp38 .

**Comment by tcharp38** [comment]
Ok, bien vu.

**Comment by jmubamba** [comment]
@KiwiHC16 
> Ce n'est pas un soucis c'est juste que tu lances le demon avec le plugin en mode 'error' pour les logs, tu peux aussi avoir 'debug',...

OK j'ai compris, mais le mot *error* m'a de suite stressé !!
Voici le bilan santé : 
![Santé](https://user-images.githubusercontent.com/63742402/79740212-979ad700-82ff-11ea-9ec1-0d2b6ee5699a.JPG)
Y a-t-il un souci sur *maison/ruche*, où est-ce normal ? Les *santé* jeedom et abeille sont à OK.
Concernant les *fantômes* je suis preneur de l'info puisque je vais prochainement migrer d'*anciens* équipements. En attendant je vais d'abord en inclure des *nouveaux*.

@tcharp38 

> port tty affiche "?" il faut "tester" pour obtenir "OK"
> Normal. Le test n'est pas automatique aujourd hui dans la mesure ou ca prend un peu de temps (arret du démon, test, puis redémarrage)

Je vais suivre ce point de près et noter mes interventions ainsi que la chronologie.
Aujourd'hui j'ai redémarré le démon qui était arrêté je ne sais plus pour quelle raison ; du coup j'ai également lancé un test pour obtenir "OK". Promis je vais faire très attention.
J'ai aussi réactivé la gestion automatique du démon (sans doute un dérapage de la souris qui aurait désactivé cette gestion).
Merci à tous les deux pour vos précieux conseils.

**Comment by tcharp38** [comment]
Pour le bilan santé, je laisse la balle à @KiwiHC16 

Côté démon, effectivement il faut normalement le laisser sur "Automatique".

**Comment by jmubamba** [comment]
@tcharp38 C'est certain. Pour moi c'est accidentel.

**Comment by KiwiHC16** [comment]
Je suppose qu on peut clore le sujet alors.

**Comment by jmubamba** [comment]
Peux-tu juste me confirmer que c'est normal : 
![image](https://user-images.githubusercontent.com/63742402/79749627-d6388d80-830f-11ea-9dd8-04deaea73d39.png)

**Comment by KiwiHC16** [comment]
1) Tu as deux ruches. Probablement du fait de la mise a jour d'Abeille.
Supprimes la premiere ruche, celle en time out.

2) Le missing sur le Proxy1 devrait disparaitre d ici une heure ou deux.

apres 1 et 2 tout semble ok.

**Comment by jmubamba** [comment]
Ca y est c'est fait. J'en ai profité pour renommer les éléments.
![image](https://user-images.githubusercontent.com/63742402/79763582-8e703100-8324-11ea-93b6-8103c8cbacc6.png)
@tcharp38 Du coup perte du **OK** !

![image](https://user-images.githubusercontent.com/63742402/79764356-8b297500-8325-11ea-8c94-6b7cd2ddb991.png)

Est-ce que le **OK** va revenir tout seul, j'attends ?
En attendant le système est fonctionnel et les capteurs de mouvement répondent. Je patiente encore un peu avant de clore, mais ça devrait le faire.

**Comment by tcharp38** [comment]
Pas de rafraichissement automatique jusque la. Donc le "?" est juste normal tant qu'on ne "Teste" pas.
Si tu as une proposition pour que ce soit moins troublant, dis moi.
Peut être est ce le fait que ca soit en rouge qui te perturbe ?

**Comment by jmubamba** [comment]
Non, tout va bien. C'est juste que je suis un peu pénible car je veux tout contrôler et comprendre. 
Tu m'expliques, dès lors ce **?** ne me dérangera plus. Alors d'accord, quand c'est rouge on pense erreur ou défaut. Manifestement ce n'est pas le cas ici.
On pourrait peut-être mettre **activer** en vert dès lors que c'est bon et supprimer le rouge. Mais vous avez d'autres chats à fouetter !
En fait c'est le premier pluging qui me pose des problèmes, mais ça vient essentiellement de moi !
J'ai encore beaucoup à apprendre.
Encore **merci** à vous pour votre patience, réactivité et disponibilité.
Je clos le sujet.

Jean-Marie

**Comment by KiwiHC16** [comment]
Salut Jean Marie,
J'ai mis ce plugin à la disposition de tous pour justement avoir un retour, l'améliorer et j'en profite par la même occasion.
Merci pour tes retours.

**Comment by jmubamba** [comment]
C'était un plaisir de travailler avec vous deux.
@tcharp38 je viens de rebooter le RPI. Le plugin est bien attaché au port !
Coté jeedom le plugin est en bonne santé, mis à part le  "**?**" il faut "**tester**" pour obtenir "**OK**" ,  mais ce comportement est normal.
