### ISSUE TITLE
Refresh LQI Z2: Error while processing zigbee network information

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1089]
Bonjour,
Depuis mon histoire de reboot ayant tout pété (avec mon problème d'affectation de ports USB), je n'arrive plus à faire de Refresh LQI Z2: message "Error while processing zigbee network information, please see logs"
Ayant quelques TimeOut sur des capteurs éloignés, je voulais savoir où ils se connectent pour voir s'il faut que je leur force la main pour se connecter sur un routeur à proximité, mais impossible d'avoir la moindre information.
J'ai donc ce matin pris tous les risques en faisant la mise à jour de la version Master: idem.
Essayé avec un reboot de mon système (j'avais envie de vivre dangereusement :p ) : idem 

Peux-tu me dire ce dont tu as besoin pour analyser ce dysfonctionnement, ou m'indiquer les manœuvres à faire pour rétablir?

En te remerciant

PS: visiblement, dans Network Graph, je peux enfin sélectionner la zigate 2, mais vu que l'analyse du réseau ne peut se faire, ben j'ai pas grand chose à afficher...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Le probleme du refresh LQI Z2 doit être réglé avec le master.
Peux tu faire un backup de ton systeme et essayer avec le master ?

**Comment by Soyann** [comment]
Hello,
MAJ faite, mais pb toujours existant :(
Je note que lorsque je fais un Refresh LQI Z2, une fois le message d'erreur affiché, si je vais dans le Network Graph, je vois qu'il fait un Resfresh LQI de ma Z1:
![image](https://user-images.githubusercontent.com/46709337/79733294-29e9ad80-82f5-11ea-90e5-238eea4a2a68.png)

**Comment by Soyann** [comment]
J'irais même plus loin en notant que dès que je clique sur Refresh LQI Z2, il traite ma ruche 1:
![image](https://user-images.githubusercontent.com/46709337/79734682-68806780-82f7-11ea-8cd8-6f44b8d0d9bb.png)
Sans doute un reste de mon gros bug de la semaine dernière où ma Zigate 2 s'était configurée sur le port de la Zigate 1

**Comment by KiwiHC16** [comment]
C est mieux sans le flag de debug. Si tu peux essayer ?

**Comment by Soyann** [comment]
Tu assures!
Reste les problèmes de #1070 , mais on y voit déjà beaucoup plus claire :)
Merci beaucoup
