### ISSUE TITLE
interrupteur Yagusmart Tuya ZigBee Smart Switch non reconnu

### ISSUE THREAD

**Issue by Snakelori** [KiwiHC16/Abeille#1092]
Bonjour ,

J'ouvre un issue comme demandé car le plug-in abeille ne reconnait pas ce périphérique Zigbee qui est bien reconnu par le plug-in Zigate.
Je join le fichier de log Abeille(en mode debug)

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4499333/Abeille.txt)

Je rappel mon message ci-dessous:

Bonjour,

J’ai installé le plugin Abeille hier pour tester par rapport à Zigate car j’avais beaucoup trop de déconnexion.
J’ai pu y intégrer la plupart de mes périphériques (Xioami essentiellement) mais pas mes interrupteur Yagusmart Tuya ZigBee Smart Switch (achetés sur Amazon).
Voici le lien–>https://www.amazon.fr/gp/product/B081TX21LR/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1 1

Ce cont des interrupteurs fonctionnant en Zigbee et sans file neutre nécessaire.
Abeille les vois bien mais en inconnu et les commandes (on/off/Statut) ne sont donc pas présentes.
Il étaient bien reconnus dans Zigate mais pas dans Abeille.

Que dois-je faire pour pouvoir les intégrer ?

Merci pour votre aide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-04-20 à 09 00 09](https://user-images.githubusercontent.com/8549674/79723229-ae343480-82e5-11ea-822e-6fa94503f125.png)
![Capture d’écran 2020-04-20 à 09 00 27](https://user-images.githubusercontent.com/8549674/79723232-affdf800-82e5-11ea-8023-4ab026d23ac0.png)
![Capture d’écran 2020-04-20 à 09 00 33](https://user-images.githubusercontent.com/8549674/79723234-b0968e80-82e5-11ea-85ce-7a7b54edefaf.png)
![Capture d’écran 2020-04-20 à 09 00 48](https://user-images.githubusercontent.com/8549674/79723235-b0968e80-82e5-11ea-917c-b0e6533c606f.png)
![Capture d’écran 2020-04-20 à 09 01 06](https://user-images.githubusercontent.com/8549674/79723236-b12f2500-82e5-11ea-911b-7b6fc7d66052.png)
![Capture d’écran 2020-04-20 à 09 01 32](https://user-images.githubusercontent.com/8549674/79723237-b1c7bb80-82e5-11ea-95d9-db3b10b9111d.png)

**Comment by KiwiHC16** [comment]
From Abeille.txt

```
[2020-04-19 16:24:35][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0011/TS0011.json will send back default template.
```

**Comment by KiwiHC16** [comment]
Peux tu faire une inclusion et partager le fichier log: abeilleParser ?

**Comment by KiwiHC16** [comment]
J'en ai commandé 2 pour les integrer dans Abeille, ci jamais on y parvient pas avec les infos que tu me donnes.

**Comment by Snakelori** [comment]
Voici le fichier abeilleParser
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4501832/AbeilleParser.txt)
 
Merci pour tes actions ;)

**Comment by KiwiHC16** [comment]
J'ai mis un (pre) modèle dans le dev:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TS0011

Tu peux récupérer le fichier et le mettre sur ton systeme. Effaces l'objet existant, refaits l inclusion et dis moi si cela fonctionne.

**Comment by KiwiHC16** [comment]
```
[2020-04-20 09:23:33][AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); dest: Abeille1; SQN : 7a; Status : 00; Short Address : 38d6; Length : 12; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 04
[2020-04-20 09:23:33][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2020-04-20 09:23:33][AbeilleParser][debug]In cluster: 0004 - General: Groups
[2020-04-20 09:23:33][AbeilleParser][debug]In cluster: 0005 - General: Scenes
[2020-04-20 09:23:33][AbeilleParser][debug]In cluster: 0006 - General: On/Off
[2020-04-20 09:23:33][AbeilleParser][debug]OutClusterCount : 01
[2020-04-20 09:23:33][AbeilleParser][debug]Out cluster: 0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
```
[2020-04-20 09:23:36][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); dest: Abeille1; SQN: 53; Src Addr : 38d6; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0006; Data byte list : ->TS0011<-
```

**Comment by Snakelori** [comment]
ok. Tu serais me donner le chemin du dossier dans lequel je dois le déposer ?
Je fais ca ce midi et te dis ce que ca donne ;)

**Comment by KiwiHC16** [comment]
Dans /var/www/html/plugins/Abeille/core/config/devices
Crée le repertoire TS0011
Et dans ce repertoire mets le fichier TS0011

**Comment by Snakelori** [comment]
Ouaaah, ca marche !!! :)
J'ai fait un test avec l'un de mes 4 interrupteurs et les actions On/Off fonctionnent . C'est Super !
Par contre j'ai pas la commande pour récupérer l'état (on ou off). C'est normal ?
Je testerais sur mes 3 autres ce soir.

**Comment by Snakelori** [comment]
rectification , j'ai bien l'état avec la commande "Etat charge" :) :)
Manque plus que l'icône après et c'est tout bon mais le principal est là :)

Grand merci à toi pour tes actions, ta prise en compte super rapide et retour tout aussi efficace :)
Bravo et Merci encore :)

**Comment by KiwiHC16** [comment]
L icone c est le fichier https://github.com/KiwiHC16/Abeille/blob/master/images/node_TS0011.png
a mettre dans ton systeme a 
/var/www/html/plugins/Abeille/images

**Comment by Snakelori** [comment]
Nickel 👌 

Merci :)

**Comment by KiwiHC16** [comment]
Est ce que tout fonctionne maintenant ? Puis je clore ?

**Comment by KiwiHC16** [comment]
snakelori

kiwihc16
1j
Merci pour tes actions sur l’issue que j’ai ouvert sur ce sujet. Tout fonctionne correctement  :slight_smile:
C’est Nickel :ok_hand:
