### ISSUE TITLE
Icones transparentes 

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1093]
Hello,

Je viens de m'amuser un coup avec toutes les icônes du répertoire /Abeille/images, et ai supprimé le fond blanc.
Si tu veux jeter un œil et intégrer au Master ;)
[images.zip](https://github.com/KiwiHC16/Abeille/files/4499571/images.zip)

Dans les faits, on passe de ça:
![image](https://user-images.githubusercontent.com/46709337/79694042-4ee70d80-826e-11ea-81a6-4ea486546ac6.png)
à ça:
![image](https://user-images.githubusercontent.com/46709337/79694054-60c8b080-826e-11ea-9904-9a1bd87157f5.png)

J'ai trouvé une manière assez simple de le faire via Word:
Glisser le .png sur une page
La sélectionner, dans les menus -> Outils Image -> Supprimer l'arrière-plan
Corriger les erreurs avec 'Masquer les zones à conserver/supprimer'
Une fois les corrections faites, clique droit sur l'image -> 'Enregistrer en tant qu'image', et écraser le fichier d'origine

**Comment by KiwiHC16** [comment]
Copié dans le dev (master).
