### ISSUE TITLE
Correction images + pb affichage Hue living Colors bloom

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1095]
Bonjour,
Après avoir contrôlé dans la version Master les nouvelles images, dans la liste des compatibilités, j'ai noté quelques irrégularités/oublis, et ai corrigé.
Il y a un truc que je ne comprends pas: il ne veut afficher l’icône des Hue living Colors bloom (ça le fait déjà sur la version stable)
[new.zip](https://github.com/KiwiHC16/Abeille/files/4510058/new.zip)

oui, je m'embête avec des détails, mais quitte à faire, autant que ce soit le plus propre possible ;) (et puis pendant ce temps, j'ai l'impression de contribuer "activement" au développement du plugin, avec mes humbles compétences)

**Comment by KiwiHC16** [comment]
Continu, je suis preneur !!!
Mis dans le master.
Peux tu partager une capture d'ecran du soucis dans la liste des compatibilités ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Soyann** [comment]
Voilà:
![image](https://user-images.githubusercontent.com/46709337/79991705-e50b7580-84b2-11ea-8ebe-31f12ae5c0ef.png)

Pourtant, si j'inspecte le code, ça pointe bien vers le png:
![image](https://user-images.githubusercontent.com/46709337/80006878-c5ca1380-84c5-11ea-986a-47535a26f3ff.png)
Edit: non, ça ne pointe pas vers le bon nom de fichier: node_ColorsBloom.png (sans espace entre Colors et Bloom)


Je t'ajoute l'image de la LWO001 (je n'ai pas le nom du fichier, car pas mis à jour ma Master)
![LWO001](https://user-images.githubusercontent.com/46709337/79992417-bf32a080-84b3-11ea-81f7-f020dfd0647f.png)

**Comment by Soyann** [comment]
Peut-être que "ta" communauté apprécierait un sujet sur https://community.jeedom.com/tags/c/plugins/protocole-domotique/66/plugin-abeille où elle pourrait proposer de nouvelles icônes si celles en place ne leur plaisent pas (je pense surtout aux photos où il y a les boites), à moins que tu gardes une issue ouverte à cet effet
Après, je veux bien repasser derrière pour effacer les fonds blancs si besoin (au pire, je m'efforcerai de faire un contrôle à chaque version stable) ;)

**Comment by KiwiHC16** [comment]
Les issue github sont intéressantes pour traiter un sujet particulier. 
Les systèmes community peuvent être beaucoup plus ouverts aux discussions diverses et variés. 

Lances le sujet on verra si les utilisateurs sont intéressés...

**Comment by KiwiHC16** [comment]
Reste a faire:
Hue LightStrip 1re génération
Hue living-Colors bloom

**Comment by KiwiHC16** [comment]
Done.
