### ISSUE TITLE
Ampoule Philips Hue White Forme Globe - LWO001

### ISSUE THREAD

**Issue by Guillaumertens** [KiwiHC16/Abeille#1097]
Bonjour,

J'ai une ampoule Philips Hue Ampoule LED Connectée White Filament E27 Forme Globe qui remonte avec le nom LWO001

Je viens de l'acheter et c'est ma première ampoule hue, je ne sais donc pas si elle n'est juste pas reconnue ou si elle ne se signale pas comme il faut.

J'ai crée le fichier LWO001.json (en repartant du LTA001) et tout semble fonctionner correctement.

Bonne journée.
Guillaume

**Comment by W1W1-M** [comment]
Bonjour @Guillaumertens 
Peux-tu joindre ton fichier LWO001.json STP ? As tu une image de l'ampoule aussi ?
Bonne journée

**Comment by Guillaumertens** [comment]
Et voilou.
Guillaume

![node_LWO001](https://user-images.githubusercontent.com/64126916/79987897-441abb80-84ae-11ea-8fe7-0a4b120980bd.png)
[LWO001.json.zip](https://github.com/KiwiHC16/Abeille/files/4516356/LWO001.json.zip)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Génial, je l ajoute.
C'est une belle ampoule !

**Comment by KiwiHC16** [comment]
Elle est dans la version de dev, sera dans la prochaine version stable.

Merci pour tous.
