### ISSUE TITLE
Plugin Jeedom : Network list/map

### ISSUE THREAD

**Issue by Kallagan99** [KiwiHC16/Abeille#1099]
bonjour,

récent utilisateur WiFi Zigate/Abeille, j'ai inclus tous mes modules Xiaomi dans jeedom.
Qd je regarde la Network Map ou list, je n'obtiens rien du tout. Si je clique sur "Refresh LQI Z1" j'otiens ce message d'erreur :

> Error, while processing zigbee network information, please see logs

Rien dans les logs, meme en mode debug (ou alors rien qui me parle... ce qui est + probable...)

Je ne sais pas où chercher. Help ;)

Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
C est probablement un des derniers bugs qui est corrigé dans la prochaine version.
A venir d ici quelques jours.

**Comment by Kallagan99** [comment]
ok je vais attendre alors. Merci

**Comment by Kallagan99** [comment]
Hello. Pour info, j'ai retenté la génération de la map en commencant par faire un Refresh des LQI.
Habituellement j'avais un msg d'erreur en anglais assez fugace.
Là j'ai aussi un message d'erreur mais en francais disant qu'il n'avait pas les droits pour ecrire tmp/AbeilleLQI_MapDataAbeille1.json.lock

l'absence de / devant le tmp indique un chemin relatif donc j'ai au hasard créé le répertoire tmp dans plugins/Abeille/Network ... 
Plus de msg d'erreur mais une roue crantée qui tourne relativement longtemps (3 à 4 min - peut être parce que j'ai des sensors en timeout...).
Et au final j'ai bien les sensors et leur LQI...

**Comment by KiwiHC16** [comment]
#1129

**Comment by KiwiHC16** [comment]
La recuperation des LQI peut être longue car on interroge chaque capteur (routeur).

Interressant le path relatif, je vais regarder le code. En fait le probleme est certainement qu'Abeille ne crée pas le répertoire tmp par defaut.

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by Kallagan99** [comment]
Zut, j'ai zappé de revenir là pour maj le ticket.
Oui ca marche depuis qques jours maintenant. Et-ce dû à une maj du plugin ou pas, je sais pas mais maintenant la carte reseau et les LQI remontent bien
