### ISSUE TITLE
Icones des abeilles / widgets

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#11]
Pas sur que ce soit super utile, mais les icônes sont sympa.

desktop/php/Abeille.php
L66
-        echo '<img src="plugins/Abeille/doc/images/' . $path . '.png" height="105" width="95" />';
 +        echo '<img src="plugins/Abeille/docs/images/' . $path . '.png" height="105" width="95" />';

L230
-  var text = 'plugins/Abeille/doc/images/node_' + $("#sel_icon").val() + '.png';
 +  var text = 'plugins/Abeille/docs/images/node_' + $("#sel_icon").val() + '.png';

Conserver l'icone abeille dans 
* recopier le fichier doc/images/Abeille_icon.png vers docs/images/Abeille_icon.png

ou déplacer les icones dans doc au choix....

**Comment by KiwiHC16** [comment]
Bonsoir,

Je vais integrer la modif.
Est ce que cela veut dire que tu as les objets qui remonte dans Jeedom ?

Ben

**Comment by KiwiHC16** [comment]
Motif faite dans Master Branche.
.

**Comment by edgd1er** [comment]
Oui, oui dans le docker j ai mes deux baro temp humidite (xiaomi) et mes deux detection de contacts affichés dans le dashboard. L historique est conservé depuis midi. Tt vas bien pour le moment. Super boulot. Le je regardevdu cote des widgets en suivant ta doc.
