### ISSUE TITLE
Plugin Jeedom : deamon qui tombe

### ISSUE THREAD

**Issue by Kallagan99** [KiwiHC16/Abeille#1100]
Re-bonjour,

mon démon Abeille tombe régulièrement (sans logique apparente entre 2 périodes de fonctionnement... ça peut aller de 2 ou 3 heures à qques dizaine de minutes pour les périodes de fonctionnement les plus courtes).

Voici un bout de log debug du moment ou le démon tombe :

```
[2020-04-23 19:17:08][DEBUG] : deamon_info, Port Declaré sur Zigate 1 et actif: /dev/zigate1
[2020-04-23 19:17:08][DEBUG] : **deamon info: OUT**  deamon deamon_info: {"state":"ok","launchable":"ok","launchable_message":"","nbProcessExpected":4,"nbProcess":"4"}
[2020-04-23 19:20:04][DEBUG] : fct message Topic: ->Abeille1/b2d8/Batterie-Volt<- Value ->3065<-
[2020-04-23 19:20:04][DEBUG] : fct message Topic: ->Abeille1/b2d8/Batterie-Pourcent<- Value ->79<-
[2020-04-23 19:20:11][DEBUG] : fct message Topic: ->Abeille1/773c/0006-01-0000<- Value ->0<-
[2020-04-23 19:20:11][DEBUG] : fct message Topic: ->Abeille1/Ruche/Zigate-8702<- Value ->b2d8<-
[2020-04-23 19:21:02][DEBUG] : fct message Topic: ->Abeille1/b3c0/0402-01-0000<- Value ->2803<-
[2020-04-23 19:21:02][DEBUG] : fct message Topic: ->Abeille1/b3c0/0405-01-0000<- Value ->3580<-
[2020-04-23 19:21:02][DEBUG] : fct message Topic: ->Abeille1/b3c0/0403-01-0000<- Value ->967<-
[2020-04-23 19:21:02][DEBUG] : fct message Topic: ->Abeille1/b3c0/0403-01-0014<- Value ->-1<-
[2020-04-23 19:21:02][DEBUG] : fct message Topic: ->Abeille1/b3c0/0403-01-0010<- Value ->9673<-
[2020-04-23 19:21:36][DEBUG] : fct message Topic: ->Abeille1/fa34/Batterie-Volt<- Value ->3055<-
[2020-04-23 19:21:36][DEBUG] : fct message Topic: ->Abeille1/fa34/Batterie-Pourcent<- Value ->76<-
[2020-04-23 19:21:43][DEBUG] : fct message Topic: ->Abeille1/Ruche/Zigate-8702<- Value ->fa34<-
[2020-04-23 19:21:44][DEBUG] : fct message Topic: ->Abeille1/e7aa/Batterie-Volt<- Value ->3015<-
[2020-04-23 19:21:44][DEBUG] : fct message Topic: ->Abeille1/e7aa/Batterie-Pourcent<- Value ->64<-
[2020-04-23 19:21:52][DEBUG] : fct message Topic: ->Abeille1/Ruche/Zigate-8702<- Value ->e7aa<-
[2020-04-23 19:28:31][DEBUG] : **deamon info: IN**
[2020-04-23 19:28:31][DEBUG] : deamon_info, Port Declaré sur Zigate 1 et actif: /dev/zigate1
[2020-04-23 19:28:31][DEBUG] : deamon_info, ooooooooooo: /dev/zigate1
[2020-04-23 19:28:31][INFO] : deamon_info: ---------found 2 running / 4 expected.
[2020-04-23 19:28:31][DEBUG] : **deamon info: OUT**  deamon deamon_info: {"state":"nok","launchable":"ok","launchable_message":"","nbProcessExpected":4,"nbProcess":"2"}
```

Si vous avez une idée...
Pour info, c'est une clé Zigate WiFi...
Merci !

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2020-04-23 19:28:31][INFO] : deamon_info: ---------found 2 running / 4 expected.
```

Quand ca tomb, peux tu en ssh faire un

```
ps -ef | grep Abeille
```

et partager le résultat ?

Quand c'est tombé, est ce que tu peux pinger la zigate wifi ?

**Comment by Kallagan99** [comment]
voici le 'ps' qd le plugin est tombé : 

```
# ps -ef | grep Abeille | grep -v grep
www-data 27473     1  0 22:20 ?        00:00:06 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleParser.php debug
www-data 27475     1  0 22:20 ?        00:00:08 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleCmd.php debug
```

pour info il est comme ça qd il fonctionne : 

```
# ps -ef | grep Abeille | grep -v grep
www-data 27308     1  0 22:20 ?        00:00:00 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleSocat.php /dev/zigate1 debug 192.168.99.16:9999
www-data 27471     1  0 22:20 ?        00:00:00 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php Abeille1 /dev/zigate1 debug
www-data 27473     1  0 22:20 ?        00:00:04 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleParser.php debug
www-data 27475     1  0 22:20 ?        00:00:06 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleCmd.php debug
```



RAS pour le ping de la zigate WiFi (ping en continue, aucune perte)

**Comment by tcharp38** [comment]
Salut.
Ca fait peut etre partie des pbs corrigés, et donc à venir sur la prochaine release.
Néanmoins tu devrais avoir un log du type "AbeilleSocat1" non ? Si oui, copie le qu'on y jette un oeil.

**Comment by Kallagan99** [comment]
alors j'avais un coquille dans mon install jeedom qui empechait le heartbeat de fonctionner et de redémarrer le plugin Abeille tout seul. C'est grâce à cette erreur que je me suis rendu compte qu'Abeille tombait très régulièrement. Depuis mon cron remarche et donc Abeille est relancé. (mais ca corrige pas le pourquoi Abeille tombe souvent).

Voici le log AbeilleSocat1 :

```
[2020-04-27 02:05:03][AbeilleSocat][info]Attention certain systemes acceptent l option rawer pour socat et pas d autres. Modifiez la commande en fonction de votre systeme en mettant rawer ou raw dans le fichier AbeilleSocat.php ligne 40
Attention certain systemes acceptent l option rawer pour socat et pas d autres. Modifiez la commande en fonction de votre systeme en mettant rawer ou raw dans le fichier AbeilleSocat.php ligne 40
[2020-04-27 02:05:03][AbeilleSocat][info]Starting reading port /dev/zigate1 with log level debug
Starting reading port /dev/zigate1 with log level debug
[2020-04-27 02:05:03][AbeilleSocat][Info]Creation de la connection wifi.
Creation de la connection wifi.
[2020-04-27 02:05:03][AbeilleSocat][Info]Command: /usr/bin/sudo /usr/bin/socat pty,raw,echo=0,link=/dev/zigate1 tcp:192.168.99.16:9999
Command: /usr/bin/sudo /usr/bin/socat pty,raw,echo=0,link=/dev/zigate1 tcp:192.168.99.16:9999
```

**Comment by tcharp38** [comment]
Effectivement rien de flagrant dans ce log. Je vais creuser de mon côté mais peut être que Kiwi aura une idée. Tu es sur la derniere stable ?

**Comment by Kallagan99** [comment]
oui oui...
Ca n'a peut etre aucun rapport mais j'ai aussi un souci avec la génération de la Network Map
Qd je demande le Refresh LQI Z1 j'ai une erreur et un message de Jeedom qui me parle de Javascript et d'URL incorrecte :

(url)https://i.ibb.co/mS97pbY/1.png

**Comment by tcharp38** [comment]
Il y a des soucis côte "Network map" mais je crois qu'il y a deja des fixes dans le pipe.
Néanmoins je ne vois pas le lien avec le démon qui tombe.
Quant à ton URL, l'adresse "http://192.168.99.11/jeedom/index.php" n'est pas bonne ? Tu peux la copier dans un nouvel onglet du navigateur et tester ?

**Comment by Kallagan99** [comment]
yes, aucun souci, cette URL est ok

**Comment by tcharp38** [comment]
Ok, la je seche.
Cote démon qui tombe, si je te file un fichier PHP à remplacer pour faire des essais et essayer de capturer des infos utiles quand ca tombe, c'est possible ?

**Comment by Kallagan99** [comment]
oui oui bien sûr...

**Comment by tcharp38** [comment]
Tiens. Peux tu essayer avec le fichier à mettre à la place de "core/class/AbeilleSocat.php".
Conserves bien sur l'original.

[AbeilleSocat.zip](https://github.com/KiwiHC16/Abeille/files/4539874/AbeilleSocat.zip)

J'ai ajouté le mode debug à la commande "socat" mais comme la sortie n'est pas compatible Jeedom (pas UTF8), je la redirige vers le log "AbeilleSOCATTOOL".
Peut etre qu'on aura + d'infos sur la cause de l'arret.

**Comment by KiwiHC16** [comment]
@tcharp38, interessant ton système de debug.

Socat qui tombe est signe pour moi de mauvaise connection wifi. 
J'ai des périodes ou cela se produit souvent puis des semaines sans ce soucis.
J'ai commencé à investiguer une solution Ethernet pour enlever la faiblesse intrinsèque du wifi.

Des que mon Wifi est de nouveau fonctionnel, je mettrai en mode debug mon socat. 

@Kallagan99, sur quel port scout se connecte t il ? 
Il y avait une premiere version du module Wifi puis une seconde. Elle n'ont pas les meme soft et le meme hardware. La V2 est basée sur mes retour à Zigate et doit être bien plus stable.

**Comment by Kallagan99** [comment]
ok j'ai remplacé le fichier et relancé le démon Abeille. Donc là je dois
avoir du contenu dans jeedom/log/AbeilleSOCATTOOL en + des autres logs
habituels ?

**Comment by tcharp38** [comment]
@Kallagan99 
Tout à fait. Et j'espere y trouver une piste, une info, explicant pourquoi socat se termine.

**Comment by Kallagan99** [comment]
> @Kallagan99, sur quel port scout se connecte t il ?
> Il y avait une premiere version du module Wifi puis une seconde. Elle n'ont pas les meme soft et le meme hardware. La V2 est basée sur mes retour à Zigate et doit être bien plus stable.

Sur quel port ? Cad ?

j'ai ça :
 `# ps ax | grep -i socat
 1122 pts/1    R+     0:00 grep -i socat

22032 ?        S      0:00 /usr/bin/php /var/www/jeedom/plugins/Abeille/core/class/../../core/class/AbeilleSocat.php /dev/zigate1 debug 192.168.99.16:9999

22039 ?        S      0:00 sh -c /usr/bin/sudo /usr/bin/socat -d -d pty,raw,echo=0,link=/dev/zigate1 tcp:192.168.99.16:9999 >>/var/www/html/log/AbeilleSOCATTOOL 2>&1

22040 ?        S      0:00 /usr/bin/sudo /usr/bin/socat -d -d pty,raw,echo=0,link=/dev/zigate1 tcp:192.168.99.16:9999

22041 ?        S      0:00 /usr/bin/socat -d -d pty,raw,echo=0,link=/dev/zigate1 tcp:192.168.99.16:9999
`

**Comment by Kallagan99** [comment]
> Tiens. Peux tu essayer avec le fichier à mettre à la place de "core/class/AbeilleSocat.php".
> Conserves bien sur l'original.
> 
> [AbeilleSocat.zip](https://github.com/KiwiHC16/Abeille/files/4539874/AbeilleSocat.zip)
> 
> J'ai ajouté le mode debug à la commande "socat" mais comme la sortie n'est pas compatible Jeedom (pas UTF8), je la redirige vers le log "AbeilleSOCATTOOL".
> Peut etre qu'on aura + d'infos sur la cause de l'arret.

J'ai trouvé où allait se trouver le nouveau fichier de log. Normal que Socat soit lancé 2 fois ? (cf ps ax dans ma réponse précédente) ?

**Comment by tcharp38** [comment]
@KiwiHC16 

> @tcharp38, interessant ton système de debug.
> 
> Socat qui tombe est signe pour moi de mauvaise connection wifi.
> J'ai des périodes ou cela se produit souvent puis des semaines sans ce soucis.
> J'ai commencé à investiguer une solution Ethernet pour enlever la faiblesse intrinsèque du wifi.

Oui le Wifi est un problème globale. Encore pire dans mon cas d'appart en petit immeuble. 12 box autour de moi. C'est galère.

**Comment by tcharp38** [comment]
> J'ai trouvé où allait se trouver le nouveau fichier de log. Normal que Socat soit lancé 2 fois ? (cf ps ax dans ma réponse précédente) ?

Il n'est pas lancé 2 fois.
Il y a le shell (sh) qui lance socat

**Comment by Kallagan99** [comment]
> > J'ai trouvé où allait se trouver le nouveau fichier de log. Normal que Socat soit lancé 2 fois ? (cf ps ax dans ma réponse précédente) ?
> 
> Il n'est pas lancé 2 fois.
> Il y a le shell (sh) qui lance socat


ok. je laisse tel quel toute la nuit. J'ai désactivé le heartbeat et la gestion auto du démon de Jeedom histoire de voir si demain matin il est tombé ou pas.

**Comment by tcharp38** [comment]
Ok merci

**Comment by Kallagan99** [comment]
alors... Loi de Murphy / hasard / correctif via effet de bord : 

ca n'est pas tombé de la nuit. Habituellement il ne fallait pas + de 2h pour observer le plugin HS, là ca a tenu depuis le lancement hier soir vers 21h...

Ou alors c'est lié à la résolution de mon souci de cron avec Jeedom (qui m'empechait d'avoir un heartbeat fonctionnel sur mes plugins, heartbeat que j'ai volontairement hier soir désactivé pour Abeille...)

Bref. Je laisse tel quel pour le moment, j'vous tiens au jus

**Comment by Kallagan99** [comment]
autre remarque : mon jeedom n'est pas dans le répertoire "habituel" (/var/www/html) mais dans un répertoire spécifique (/var/www/jeedom) or je note bcp d'appels au chemin absolu usuel de jeedom dans les fichiers du plugin (j'en note 23 au total). Je ne sais pas si les 2 élements sont liés.
Faut il que je les change à la main ?
Est il prévu que ce soit paramétrable ou que ca aille chercher l'URL d'install de jeedom automatiquement ?

**Comment by tcharp38** [comment]
Salut
Ha ca c'est une bonne remarque. J'ai bien peur que parfois il y ai encore des chemins en dur.
Et tu as raison, le code devrait se baser sur le chemin officiel de Jeedom pour pouvoir suivre les evolutions. C'est donc à corriger de notre côté.

**Comment by tcharp38** [comment]
> autre remarque : mon jeedom n'est pas dans le répertoire "habituel" (/var/www/html) mais dans un répertoire spécifique (/var/www/jeedom) or je note bcp d'appels au chemin absolu usuel de jeedom dans les fichiers du plugin (j'en note 23 au total). Je ne sais pas si les 2 élements sont liés.
> Faut il que je les change à la main ?
> Est il prévu que ce soit paramétrable ou que ca aille chercher l'URL d'install de jeedom automatiquement ?

Quand j'y repense je ne vois pas comment ca peut fonctionner dans ton cas. Il ya beaucoup trop de chemins en dur vers "/var/www/html/plugins....". On doit pouvoir fixer ca mais  ca n'est pas immédiat. Du coup j'imagine que l'ancien chemin existe toujours ?

**Comment by Kallagan99** [comment]
non l'ancien chemin n'existe plus et donc oui je me demande comment ca marche LOL
bref. J'ai tout changé, je suis revenu au chemin historique pour coller au chemin relatif du code du plugin... on verra

**Comment by tcharp38** [comment]
Oui je pige pas du tout. Peut être que le cache du navigateur à masqué une partie.
Quoi qu'il en soit je viens de voir que tu avais déja posté un commentaire (je suppose que c'est toi) sur le forum Jeedom. La réponse étant "il n'est pas recommandé d'installer Jeedom autre part que dans le chemin par defaut", ca veut dire que meme à leur niveau ca n'est pas propre.
Autrement dit j'arrete de creuser cette piste pour virer les chemins absolus. On reprendra si besoin.

**Comment by tcharp38** [comment]
Ceci dit, à l'occasion je reste preneur du log AbeilleSocatTOOL (fichier zippé, PAS un copy/paste) meme si le démon ne tombe pas. Juste pour voir à quoi ca ressemble et voir comment améliorer les choses. Merci

**Comment by Kallagan99** [comment]
de toute facon je suis redevenu "jeedom compliant" avec le retour au repertoire par défaut
j'attends jusqu'à demain pour voir si le démon reste eveillé convenablement et je te zip le log

**Comment by Kallagan99** [comment]
Ce matin, tjrs RAS. Le plugin tient. Je l'ai manuellement relancé ce matin vers 08:50 histoire de voir si aucune souci. 

[Abeille_logs.zip](https://github.com/KiwiHC16/Abeille/files/4550248/Abeille_logs.zip)

On peut clôturer...

**Comment by tcharp38** [comment]
Salut
Je vois un exit à 11h54 le 28, c etait voulu cet arret ?
2020/04/28 11:54:57 socat[7005] N socat_signal(): handling signal 15
2020/04/28 11:54:57 socat[7005] W exiting on signal 15
2020/04/28 11:54:57 socat[7005] N socat_signal(): finishing signal 15
2020/04/28 11:54:57 socat[7005] N exit(143)

**Comment by Kallagan99** [comment]
J'ai fait qques tests sur mon jeedom hier. Pas impossible que ce soit un
restart involontaire. Je me souviens plus exactement.
Mais clairement, je suis passé d'une situation à plusieurs stop du daemon
par jour (voire par heure) à tout qui tient sans intervention manuelle...

**Comment by tcharp38** [comment]
Ok tant mieux.
On va supposer que la principale cause etait le chemin d'installation different de la valeur par defaut.
Je te laisse cloturer le point.
