### ISSUE TITLE
Fixer ports USB, devices identiques

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1102]
Hello,
Hier, j'ai du rebooter mon Jeedom, et me suis de nouveau retrouvé avec un mélange de ports USB (merci beaucoup pour ton processus de blocage, qui m'a de suite prévenu)
J'ai donc commencé à me renseigner sur le lien donné sur le forum, et me retrouve confronté à un problème: mes deux clés ont le même idVendor et idProduct 
  idVendor           0x10c4 Cygnal Integrated Products, Inc.
  idProduct          0xea60 CP210x UART Bridge / myAVR mySmartUSB light
  iProduct                2 ZiGate
  iSerial                 3 0001
  idVendor           0x10c4 Cygnal Integrated Products, Inc.
  idProduct          0xea60 CP210x UART Bridge / myAVR mySmartUSB light
  iProduct                2 CP2102 USB to UART Bridge Controller
  iSerial                 3 0001

Sais-tu comment faire pour les différencier dans 99-usb-serial.rules?

On sort de la configuration même d'Abeille, mais je pense que ce point aurait besoin d'un paragraphe dans la doc ;)

Merci d'avance

**Comment by tcharp38** [comment]
Salut Soyann.
J'étais en train de faire qq recherches pour ma culture et je suis tombé sur une piste.
Il semble que dans beaucoup de cas de clefs "low cost", le serial ne soit meme pas programmé.
Comme ce sont des clefs identiques, meme ID.

Mais comme c'est du CP2102 tu peux peut etre programmer un num de serie toi meme.
![image](https://user-images.githubusercontent.com/35221038/80303836-0621de00-87b3-11ea-8712-2ecdd9b3bbdd.png)

Page complete la
https://askubuntu.com/questions/49910/how-to-distinguish-between-identical-usb-to-serial-adapters

**Comment by Soyann** [comment]
Salut Tcharp38 :)
Merci pour ta réponse, mais je ne suis pas trop chaud pour partir _aussi loin_ à l'aventure: ça a l'aire un poil expérimental cette méthode, ils ne parlent que de changement de SN et non d' idVendor / idProduct, et n'ai pas envie de planter le module (c'est sur ma prod, et n'ai pas de spare si ça tourne mal)

**Comment by tcharp38** [comment]
Je comprends. 
Il reste la solution d'integrer la position du device dans la liste.

La solution donnée sur le wiki Domoticz semble faire le taf.
https://www.domoticz.com/wiki/PersistentUSBDevices

Ce chapitre en particulier:
![image](https://user-images.githubusercontent.com/35221038/80306258-679d7900-87c2-11ea-8683-e6496209dc6a.png)

**Comment by Soyann** [comment]
Donc si j'applique à ma conf:
![image](https://user-images.githubusercontent.com/46709337/80307313-856ddc80-87c8-11ea-821d-e6008a8c3214.png)


ça veux bien dire que je dois mettre:
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{devpath}=="1.4", SYMLINK+="ttyUSB-Zigate1"
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{devpath}=="2", SYMLINK+="ttyUSB-Zigate2"

? 
(désolé, je ne suis pas super à l'aise avec ça, et une fois de plus, ne veux me louper)

**Comment by tcharp38** [comment]
Ca me semble correct.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Soyann** [comment]
Je n'ai pas eu le temps d'appliqué, et le ferai sans doute dans le weekend 
D'ici là, @KiwiHC16 , toi qui a déjà appliqué (si j'ai bien compris) cette méthode, peux-tu confirmer que ça devrait passer? (oui, je suis flippé)

**Comment by KiwiHC16** [comment]
Oui il y a au moins 3 paramètres programmables dans les modules USB-TT. J'ai programmé certains de mes modules. Ca fonctionne super bien après avoir fait la conf dans linux.
Mais, j'ai tout un stock de modules USB-TTL qui refusent de se faire programmer. Depuis Linus ils sont tous identiques. Aucun moyen de le différencier.
J ai donc oublié la piste car en plus cela demande au plugin de faire une conf OS (Pas top).
La seule solution que j'ai trouvée, c'est de vérifier que je parle avec la bonne Zigate en l identifiant avec son IEEE.

Soyan, si tu ne changes pas les équipements sur le bus USB, a chaque démarrage, ils devraient garder le même ordre (ttyUSB0, ttyUSB1,...). 
Si l'ordre n'est pas le bon, Abeille ne doit pas trouver les zigates au bon endroit. Changes l ordre  sur le bus USB ou interverti les module USB-TTL avec les Zigate. 
On peut certainement implémenter dans Abeille une "inversion" automatique sur détection de zygotes. Il faut que je réfléchisse plus au sujet.

**Comment by KiwiHC16** [comment]
Soyann, dans un premier temps essayes les changements que je te propose sans toucher à l'OS.

**Comment by Soyann** [comment]
Merci pour ta réponse, cependant, ça va me causer d'autres soucis:
A chaque fois que j'ai eu un mélange de ports, il me sélectionne les ports de la Zigate 2 et mon RFXcom. Ces deux périphs sont plugués directement sur ma machine, (ma Zigate 1 étant sur le HUB). 
Du coup, ça m'obligerait à mettre mes deux Zigates cote à cote (avec un risque d'inversion si je dois en démonter une), de plus, j'ai déjà noté que mon RFXcom a un comportement bizarre si je le branche sur le HUB (et n'ai que 3 ports USB natif), donc je suis plus ou moins forcé de garder l'ordre actuel...

**Comment by KiwiHC16** [comment]
Dans ce cas tu peux faire des liens symboliques dans linux.
Par exemple tu crées :
- un lien /dev/zigate1 sur /dev/ttyUSB2
- un lien /dev/zigate2 sur /dev/ttyUSB1

Et dans Abeille tu choisis les /dev/zigateX qui vont bien.

Pour ca tu utilises la commande "ln -s" en ssh

**Comment by KiwiHC16** [comment]
Dans le master j ai mis il y a quelque temps une sécurité qui fait que les commandes ne sont pas envoyées si la Zigate identifiée n'est pas celle attendu sur le port.

Ca doit éviter bien des soucis si la config "port" n est pas bonne.

Je clos cette issue. On ouvrira une autre si d autre besoin spécifiques.
