### ISSUE TITLE
Alerte changement de l adresse IEEE pour un equipement !!! Ruche

### ISSUE THREAD

**Issue by antarmc** [KiwiHC16/Abeille#1103]
Salut 

Je migre mon install en V4 (pas mal de soucis variés sur ma V3, y compris des timeout reguliers sur les device zigbee) en repartant de zero.

J'ai installé abeille sur ce v4 tout neuf mais ai renommé la ruche, et je crois que c'était la chose a ne surtout pas faire ??
Je n'arrive plus maintenant (malgré suppression / re-creation de toutes les devices et de la ruche) a me débarrasser de l'erreur Alerte changement de l adresse IEEE pour un equipement !!! Ruche ID

Je suis sous rpi3 avec pizigate. Je te joins mon abeille parser en debug. Merci d'avance.

Antar

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je ne vois pas d'AbeilleParser.
As tu des CRC dans le log ? C'est le soucis typique quand tu as des erreurs IEEE Ruche.

**Comment by antarmc** [comment]
Oups je n'ai pas du cliquer sur UP apres le glisser deposer du log.
J'ai tout effacé juste après, je n'ai pas de logs sous la main, (je tourne encore sur une V3, je basculerai sur la v4 quand j'aurai corrigé tous mes petits pb.) Je te donne ca tout a l'heure.

**Comment by antarmc** [comment]
[2020-04-27 19:28:24][AbeilleParser][debug];type; 8000; (Status)(Not Processed); dest: Abeille1; Length: 5; Status: 00-(Success); SQN: 00; PacketType: 0010
[2020-04-27 19:28:28][AbeilleParser][debug];type; 8000; (Status)(Not Processed); dest: Abeille1; Length: 5; Status: 00-(Success); SQN: 00; PacketType: 0009
[2020-04-27 19:28:28][AbeilleParser][error];CRC is not as expected (101) is 8d
[2020-04-27 19:28:28][AbeilleParser][debug];type; 8009; (Network State response)(Processed->MQTT) Dest: Abeille1 Short: 0001 Ext Addr: ed40c8a72f1e6cee PAN Id: 40d3 Ext PAN Id: 92fb780B00 Channel: 0

J'ai bel et bien des CRC

**Comment by KiwiHC16** [comment]
Alors Abeille (je) ne peux rien faire. Est ce une zigate sur USB ?

**Comment by antarmc** [comment]
C'est une pizigate. Que veux tu dire par ne rien pouvoir faire ? c'est un problème insolvable ? Que puis je faire personnellement ? Quitte a évoquer de "grands remèdes" ?
Ca ne gène en rien le fonctionnement ?

**Comment by tcharp38** [comment]
@antarmc , as tu seulement migré Jeedom sur une machine fonctionnelle ou est-ce un nouveau RPI avec une installation toute neuve ?

**Comment by antarmc** [comment]
C'est un rpi fonctionnel en v3 depuis plus d'un an. Juste je change de jeedom

**Comment by tcharp38** [comment]
Ok. Je pige pas comment tu peux avoir des erreurs CRC avec une PiZigate. Je me trompe peut etre mais comme ca je ne vois que 2 possibilites

- le port est utilisé aussi par un autre process.
- souci avec la PiZigate

Sais tu vérifier ca ?

**Comment by antarmc** [comment]
Je t'avoue que non je ne sais pas vérifier. Tu peux m'aiguiller ?

**Comment by W1W1-M** [comment]
Bonjour @antarmc 
Est-ce que une installation fraîche de Jeedom, sur une autre microSD pour garder ton installation actuelle, permettrait d’exclure un problème matériel du PiZiGate peut être ?
Le firmware du PiZiGate est en quelle version ?
Bonne journée

**Comment by antarmc** [comment]
Bonjour W1W1-M
Je suis sur une install toute fraiche, que je n'utilise d'ailleurs pas encore en prod
Oui puis je touver la version du firmware ?
Bonne journée également

**Comment by W1W1-M** [comment]
Sauf erreur de ma part il me semble que la commande SDK de la ruche renvoi la version du firmware de la ZiGate.

**Comment by tcharp38** [comment]
Sur la page du plugin (protocole domotique->Abeille) tu dois trouver la version
![image](https://user-images.githubusercontent.com/35221038/80491155-9fdbbd80-8962-11ea-9140-3ca44382b0ed.png)

**Comment by antarmc** [comment]
Voici ma version : SDK  031a

**Comment by tcharp38** [comment]
Donc ca n'est pas une antiquité de firmware même si il y a plus récent. Je suis sur la meme version.
Sais tu faire un ssh sur ta machine ?
Si oui il faudrait essayer la commande "sudo lsof <nomduport>"
Ex: sudo lsof /dev/ttyS0

**Comment by antarmc** [comment]
pi@raspberrypi:~ $ sudo lsof /dev/ttyAMA0
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nodejs   1530 www-data   21uW  CHR 204,64      0t0 1158 /dev/ttyAMA0
php     29750 www-data    5r   CHR 204,64      0t0 1158 /dev/ttyAMA0

voila voila

**Comment by tcharp38** [comment]
yessss une piste !
Ton port ttyAMA0 si c' est bien celui que tu utilises pour la PiZigate, est AUSSI utilisé par "nodejs".
Donc il y a forcement conflit, d'ou les CRC.

**Comment by antarmc** [comment]
Très bonne nouvelle. Je ne sais pas d'ou vient ce NodeJS par contre ...

**Comment by tcharp38** [comment]
Peut être est-ce une nouveauté de Jeedom v4 si ca n'etait pas par défaut sur ta plateforme.

**Comment by tcharp38** [comment]
Tu n'as fait que passer en v4 ? Tu n'as pas de nouveau plugin (qui utiliserait NodeJs) ?
Dans tous les cas si ca vient avec un autre plugin ou avec Jeedom v4 il faudra trouver comment lui dire de pas toucher au port de la PiZigate.

Si il n'y a pas d'autre idée, je te suggere d interroger le forum Jeedom.

**Comment by antarmc** [comment]
J'ai installé v4 puis les plugins domotique suivants :
abeille, jmqtt, espeasy, rflink

**Comment by tcharp38** [comment]
L'un d'eux est coupable. Regarde si dans leur config il n'y a pas le choix d'un port tty.
D'ailleurs peut etre RFlink ? Je seche la.

**Comment by antarmc** [comment]
Je crois que ta question était la bonne tcharp38 sur les autres plugins, j'ai honte de ne pas y avoir pensé ! meaculpa a tous !
Et doublement juste de ta part, il s'avère que Rflink serait le coupable (par malchance j'ai mon récepteur 433mhz HS (commande en cours) donc je n'avais pas finalisé la config du plugin, et il était paramétré sur ttyAMA0 !)
Je corrige et checke

**Comment by antarmc** [comment]
Bon et bien après plusieurs heures a bidouiller mon bouzin jeedom v4... Je n'ai plus l'erreur de changement d'adresse !
Merci pour votre aide et vos compétences. Respect, et bonne continuation !
