### ISSUE TITLE
Eurotronic Spirit Off mode

### ISSUE THREAD

**Issue by Tulan** [KiwiHC16/Abeille#1104]
Hi,
with the end of winter I have created a Jeedom Mode to switch Off thermostats & all Spirit heads.

It seems the "Off" action don't do anything, as I can see Heating still changing during day and night.

Do you have an idea or do you need any log ?

Jeedom 4.0.52
Abeille  2020-04-08 01:01:06 
Zigate 3.1b

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
I did not test this mode due to summer as I set the temperature to 5deg.
The issue I faced was that because I moved from Zwave to Zigbee the Temperature was set to 4deg in my scenario. 4 deg was rejected by the spirit.
I will check. If the command exist I guess I tested it when I did the incorporation into Abeille.

**Comment by KiwiHC16** [comment]
If you could put the plugin into debug, Set to Off and share the logs AbeilleCmd and AbeilleParser. Also a photo of the radiateor before and after to see the change.

**Comment by Tulan** [comment]
Attached log files in debug mode and a photo of the display. No change after Off action. 
I have tested the Off function on device with IEEE address 00158d00053d2db5.

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4560814/Abeille.txt)
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4560815/AbeilleCmd.txt)
[AbeilleDbConf.txt](https://github.com/KiwiHC16/Abeille/files/4560816/AbeilleDbConf.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4560817/AbeilleParser.txt)
[AbeilleSerialRead1.txt](https://github.com/KiwiHC16/Abeille/files/4560818/AbeilleSerialRead1.txt)
![IMG_0430](https://user-images.githubusercontent.com/818430/80755224-bc2d5500-8b30-11ea-93a2-2e9be1cb8b88.jpeg)

**Comment by Tulan** [comment]
Hi,
do you need more infos or logs about this problem ?

Regards.

**Comment by KiwiHC16** [comment]
Don't worry I have many of them in my house. I'll test as soon as I have few minutes.
Sorry I will take me few weeks as I'm very busy.

**Comment by KiwiHC16** [comment]
Dans la commande il y a les parametres:
clusterId=0201&attributeId=4008&EP=01&Proprio=1037&attributeType=22&value=000010

remplacer par:
clusterId=0201&attributeId=4008&EP=01&Proprio=1037&attributeType=22&value=000020

**Comment by KiwiHC16** [comment]
Correction dans master
