### ISSUE TITLE
Problème Timeout / Inclusion suite passage en SSD 

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#1107]
Hello Ben,
J'ouvre une issue pour plus de visibilité.
Hier, j'ai installé un SSD sur mon Pi4 pour soulager ma SD.
Avant d'effectuer la bascule, j'ai installé un nouveau hub alimenté et fais une sauvegarde Jeedom. Tout était OK, aucun souci sur Abeille.
Une fois la migration passée, tous mes capteurs / volets sont passés en Timeout et impossible de les ré-inclure. Il ne se passe rien. Sauf 1 ou 2 qui fonctionne encore.
J'ai essayé diverses choses : 
 * zigate sur port USB direct Pi4 -> pas de changement
 * restauration de ma sauvegarde -> pas de changement
 * Suppression d'un capteur puis réinclusion -> ne se passe rien
 * Réinclusion d'un capteur en timeout sans suppression -> il ne se passe rien (pas de message du type : équipement déjà présent on fait la MAJ)

Voici les logs.
J'espère que tu pourras m'aider :) 

Merci d'avance

[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/4544121/AbeilleSerialRead1.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/4544122/Abeille.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4544123/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4544124/AbeilleParser.log)

**Comment by Xav-74** [comment]
Mise à jour de la zigate en 3.1c final.
Résultat pas mieux :(

J'ai purgé les logs avant de redémarré avec la nouvelle vrsion de firmware. Voici les fichiers. Pas mal d'erreur dedans : 

[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4546751/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4546753/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/4546754/AbeilleSerialRead1.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/4546755/Abeille.log)

Mais j'ai du mal à analyser.
Merci

**Comment by tcharp38** [comment]
Salut
Il y a plein de choses qui remontent de la Zigate mais je note un truc qui me semble anormal:
type; 8000; (Status)(Not Processed); dest: Abeille1; Length: 5; Status: (ZigBee Error Code unknown): 15; SQN: c7; PacketType: 0100

Jamais vu ca.
@KiwiHC16, une idée ?

**Comment by tcharp38** [comment]
On dirait que ton réseau est bien pollué. Une nouvelle borne wifi à proximité ou un changement wifi recemment peut etre ?

**Comment by Xav-74** [comment]
ma Zigate n'est en effet pas très loin de ma box mais cela a toujours été le cas !
Pas de changement sur le Wi-Fi sinon.

**Comment by Xav-74** [comment]
Dans le doute je vais désactiver le Wi-Fi de ma box car j'ai une autre borne dans la maison.
Je vais perdre un peu en couverture mais si cela peut m'aider :)

**Comment by tcharp38** [comment]
Si ca fonctionnait avant au meme endroit, peut etre que la box a changé de canal. Sinon ca ne vient pas de la.
Clef endommagée ?

**Comment by Xav-74** [comment]
c'est bizarre car c'est arrivé au redémarrage du Pi4 lors de mon passage de SD à SSD
Est-ce que la recopie de la carte sur le SSD a pu provoquer cela je ne sais pas ?

Est-ce que la clé est endommagé : idem difficile à dire. J'ai un capteur qui vient de revenir ce soir, un autre a disparu ! La mise à jour en 3.1c s'est bien passée aussi.

**Comment by Xav-74** [comment]
Je viens de passer ma box en canal 4. Mon Zigbee est en 15.
On va voir ce que cela donne.
En tout cas merci pour ton aide

**Comment by tcharp38** [comment]
> c'est bizarre car c'est arrivé au redémarrage du Pi4 lors de mon passage de SD à SSD
> Est-ce que la recopie de la carte sur le SSD a pu provoquer cela je ne sais pas ?

Non aucun rapport mais je penche pour une coincidence malheureuse.
En tout cas jamais vu ca.

> Est-ce que la clé est endommagé : idem difficile à dire. J'ai un capteur qui vient de revenir ce soir, un autre a disparu ! La mise à jour en 3.1c s'est bien passée aussi.

Ca sent la perturbation réseau.

**Comment by Xav-74** [comment]
je crois que je vais repartir sur une install propre !
J'ai fait tellement de tests au départ que ca ne fera pas de mal. Je vais attendre l'avis de @KiwiHC16 mais je ne vais pas avoir le choix je pense :(
En même temps, j'ai du temps en ce moment :)

**Comment by Xav-74** [comment]
Bon, suppression du plugin, RAZ EEPROM de ma Zigate, réinstallation du plugin.
Check
Inclusion de mon premier volet : NOK

Voici les logs : 

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/4550515/Abeille.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/4550516/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4550518/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/4550519/AbeilleCmd.log)

Merci d'avance

**Comment by tcharp38** [comment]
Salut
Je ne vois plus de soucis réseau dans tes logs. Rien d'anormal à signaler pour moi.
Tu peux résumer le status actuel ? Tu dis premier volet NOK donc aucun device inclus jusque la ?

**Comment by Xav-74** [comment]
Oui pour le moment, je n'ai aucun équipement inclus.
Je n'y arrive pas en tous les cas.
Je ne sais plus quoi tester.

**Comment by tcharp38** [comment]
Peux tu vider les logs "SerialRead1", "AbeilleParser", et "Abeille", puis relancer l'inclusion de ton volet, et renvoyer les logs ?
La phase d'inclusion n'y est pas.

**Comment by Xav-74** [comment]
Voilà logs vidés puis mise en poistion inclusion de ma Zigate et tentative d'inclusion de mon volet.
J'ai vraiment l'impression que le mode inclusion ne se lance pas.

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/4558421/Abeille.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/4558422/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/4558423/AbeilleSerialRead1.log)

**Comment by tcharp38** [comment]
La zigate clignote en mode inclusion. C'est le cas ?

**Comment by Xav-74** [comment]
Oui elle clignote bien

**Comment by tcharp38** [comment]
Ok c'est en ligne avec ce que je vois dans le log.
8014; ( “Permit join” status response)(Processed->MQTT); **Permit Join Status: 01**

Mais on ne voit rien d'autre.
Je dirais donc que ton volet n'essaie pas d'entrer dans le réseau.
C'est du Profalux ?

**Comment by Xav-74** [comment]
oui volet Profalux

**Comment by tcharp38** [comment]
Ok j'ai la meme chose.
Mais une piste... le canal choisi de la zigate c'est quoi ? Par defaut je crois que c'est 11 mais ca peut être autre chose si trop "encombré". La ou je veux en venir c'est que, en supposant que tu fasses le bonne procédure côté Profalux, est il capable de joindre un réseau autre que le canal 11 ?

**Comment by Xav-74** [comment]
Dans mon log AbeilleParser je suis bien sur le canal 11
J'ai bougé mon Wifi en canal 4 pour être sur

**Comment by nieren502** [comment]
Peux-tu indiquer la solution mise en oeuvre (changement de canal ?). J'ai aussi un pizigate qui clignote en mode inclusion (installation toute fraiche, aucun device d'associé) mais je n'arrive pas à faire l'inclusion de mes devices Xiaomi. Bon je suis en jeedom 4 sous raspbian buster, je sais que le plugin n'est pas encore testé pour mais je me dis que comme le pizigate clignote, peut être que ça pourrait marcher ?

**Comment by Xav-74** [comment]
J'ai changé le canal de mon Wifi, pas de ma Ziagte :)

**Comment by nieren502** [comment]
Merci. Je viens de vérifier je suis en canal 6 pour mon wifi et en 11 pour la box. C'est pas ça donc.
Xav-74, j'ai cru voir que tu avais une config similaire à la mienne (rpi 4 buster avec SSD + jeedom V4 + pizigate) ? Si oui, y a-t-il des choses particulières que tu as faites pour arriver à faire fonctionner abeille ?
De mon côté, je n'ai pas accès à la page de config du plugin (celle où l'on choisit le mode d'inclusion automatique / manuel)

**Comment by Xav-74** [comment]
Même config au détail près que je suis sur une Zigate USB, pas une PiZigate.
Tu as installé la version stable de Abeille ? Les dépendances ont bien été installées ?

**Comment by Xav-74** [comment]
Peux tu ouvrir une nouvelle issue sur ce github pour ne pas perdre le fil de celle-ci ?
Je vais essayer de t'aider ?

**Comment by tcharp38** [comment]
> Je viens de vérifier je suis en canal 6 pour mon wifi et en 11 pour la
 ATTENTION ! Les canaux Zigbee et Wifi ne se numérotent pas de la même façon

Voial un article plutot interessant :
https://shop.prestige-distribution.fr/blog/blog-prestige-distribution-france-1/post/bien-configurer-diagnostiquer-son-reseau-zigbee-mise-a-jour-22-02-10

**Comment by nieren502** [comment]
Merci beaucoup pour ta proposition d'aide. Je viens de créer une nouvelle issue : Inclusion impossible - Rpi4 SSD - Jeedom 4 - pizigate #1110

Pour l'article sur les canaux, ton lien montre que le zigbee 6 et wifi 11 seraient compatibles, si je le lis bien

**Comment by Xav-74** [comment]
Bon ben j'ai ma réponse !
En repassant sur ma SD mais en laissant le SSD branché -> même souci
En repassant sur ma SD et en débranchant le SSD -> inclusion OK
Donc cela vient bien de mon SSD ! Ce n'était pas une coincidence !
@KiwiHC16 : pb de puissance élec à ton avis ?
Si je prends une alim plus puissante, ca devrait remarcher ?

**Comment by tcharp38** [comment]
Enfin une piste.
J'en conclus que le SSD est alimenté par le RPI.
Sur quel port ? Type C ?

**Comment by Xav-74** [comment]
Oui SSD alimenté par mon Pi4 sur port USB 3 et connectqiue C pour mon SSD
Ma Zigate est sur un hub USB alimenté

**Comment by nieren502** [comment]
Merci pour le retour et surtout pour le test !
Mon SSD est sur port usb3 avec adaptateur sata. J'ai une prise sur l'adaptateur sata pour une alim externe. Il faut que je trouve une alim compatible et que je teste!
Je vous dis si j'ai du nouveau.

**Comment by tcharp38** [comment]
Tu dis 2 fois SSD donc je suppose
- alim sur type C
- SSD sur USB3
 Si ta Zigate est alimentée séparement je ne comprends pas mais t'en as fait la preuve.
Je viens de regarder un peu sur le net, il y a déja un souci connu sur le type C mais partout ils disent au moins 3A pour l'alim.

A lire
https://arstechnica.com/gadgets/2019/07/raspberry-pi-4-uses-incorrect-usb-c-design-wont-work-with-some-chargers/

**Comment by Xav-74** [comment]
Oui tu as bien compris :)
Type C pour mon alim

**Comment by tcharp38** [comment]
Bon courage pour tes essais.
L'effet de bord sur la Zigate est etrange alors c'est à garder en tête pour les autres malchanceux.

**Comment by Xav-74** [comment]
Je viens de brancher mon SSD sur mon hub USB -> même souci
Je laisse mon SSD sur le hub et je repasse la Zigate en direct sur le Pi4 -> même souci

Je ne comprends pas ! Un pb de puissance ?

**Comment by tcharp38** [comment]
Ton hub etant auto-alimenté je ne vois pas le pb de puissance.
Donc en gros des que le SSD est branché, alimenté par le RPI ou exterieur, ca merde.
Bon résumé ?

**Comment by Xav-74** [comment]
Exact ! Très bon résumé 
C'est incompréhensible

**Comment by tcharp38** [comment]
Si on exclut le pb de power, que reste t'il ?
Il se passe qqch cote kernel quand le SSD est detectée ?
Tu peux peut etre faire un lsof sur ton port de la zigate pour verifier qu'il n'est utilisé que par Abeille. Mais tu aurais des pbs de CRC peut etre.

**Comment by Xav-74** [comment]
@nieren502 : ton SSD est un SATA ou un MSata ?

**Comment by nieren502** [comment]
C'est un SATA avec cet adaptateur :
https://www.amazon.fr/gp/aw/d/B01CJK5F9E/ref=ya_aw_oh_bia_dp?ie=UTF8&psc=1

**Comment by Xav-74** [comment]
bon ben SATA comme moi !
Quelle marque ? Moi PNY.
Sur les forums Jeedom, ils me conseille vivement un MSata, qui consomme moins et meileur compatibilité Pi4 !

[https://community.jeedom.com/t/se-lancer-dans-laventure-raspberry-pi-et-jeedom-comment-faire/22672/76](url)

Je vais renvoyer mon SATA sur Amazon et on verra bien

**Comment by nieren502** [comment]
Un Samsung Evo 850 qui date de 2015.
Je vais suivre si tu arrives a passer en msata et que ça résout le problème.

**Comment by Xav-74** [comment]
Commande passée sur AliExpress.
Livraison fin mai. Je te tiens au jus.
En attendant je suis repassé sur SD et ca marche nickel ! Tous mes équipements sont revenus après ré-inclusion

**Comment by Smanar** [comment]
Pöur information sur le raspberry 4, il ne faut jamais utiliser le port USB 3 pour les clé zigbee (2.4 GHz).
Je suis sur conbee c'est pareil, le port USB 3 est trop parasité des que l'on y branche un appareil.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1643

Le probleme c'est pas le disque, c'est le raspberry. Pas de soucis avec un raspberry 3, tu as essayé en utilsant tout simplement un port USB 2 ?

**Comment by Xav-74** [comment]
Merci Smanar pour ce retour !

Oui je suis repassé sur USB 2 mais résultat idem. Dès que mon SSD est branché, ma Zigate est dans les choux.

J'ai finalement commandé un MSata Transcend 32G sur Amazon. Réception le 11/05.
Je vous tiendrai au courant.

**Comment by Smanar** [comment]
Ha mince j'etais sur que le passage en usb 2 changeait quelque chose.

**Comment by Xav-74** [comment]
C'est vraiment surprenant cette histoire.
Je viens finalement de commander un disque SSD MSata Transcend préconié par akenad sur les forum Jeedom. A priori compatibilité parfaite et grosse fiabilité. Réception dans qq jours. Je vous tiens au jus

**Comment by nieren502** [comment]
Merci pour les infos. J'ai essayé aussi pour vérifier, en utilisant une carte sd a la place de mon SSD. Même résultat l'inclusion fonctionne bien.
Pourtant chez moi j'ai une pizigate.... Quel rapport donc entre les gpio et le SSD sur USB 2 ou 3? Étrange

**Comment by KiwiHC16** [comment]
Interessant. J'avais mon RPi3 sur un SSD Kingston 120G sur une carte MSATA SSD "SupTronics X850 v3.0" et ca fonctionnait nickel.
Je n'aai pas de RPi4 pour tester.

**Comment by KiwiHC16** [comment]
#1110

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Xav-74** [comment]
Bon Msata Transcend reçu auj avec le boitier Inateck TS32GMSA370
Je le branche juste sur le Pi4 sans boot dessus, tous mes équipements passent en TimeOut !!!
Je débranche et tout redevient OK.
Il y a donc bien une incompatibilité entre la clé Zigate et un SSD sur le Pi4 :frowning:

Des idées pour le debug ?

**Comment by nieren502** [comment]
Mince. Mais suite a ton message j'ai encore fait des recherches avec la clef conbee qui fait l'équivalent de zigate. Je suis tombé la dessus :+1: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1803
Il y a plusieurs pistes. Je n'ai pas le temps de les explorer ce soir, mais il y a un problème d'isolation de l USB 3 face aux hautes fréquences du zigbee. Une première solution consiste a éloigner la clef zigbee ce qui n'est pas possible chez moi puisque j'utilise un pizigate.
L'autre piste est d'utiliser le SSD sur port usb2 en désactivant le UAD ou en effectuant un paramétrage spécifique de l'USB (Persistant USB).
Voilà pour quelques pistes

**Comment by tcharp38** [comment]
Une question peut etre idiote. A t'on supprimé tout pb software ?
Lorsque le SSD est connecté, est ce que le kernel ne fait pas qqch suite à la detection du SSD ? Le port zigate pourrait par ex se retrouver occupé par autre chose qu'Abeille (conflit d'acces).

**Comment by Xav-74** [comment]
> Mince. Mais suite a ton message j'ai encore fait des recherches avec la clef conbee qui fait l'équivalent de zigate. Je suis tombé la dessus 👍 [dresden-elektronik/deconz-rest-plugin#1803](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1803)
> Il y a plusieurs pistes. Je n'ai pas le temps de les explorer ce soir, mais il y a un problème d'isolation de l USB 3 face aux hautes fréquences du zigbee. Une première solution consiste a éloigner la clef zigbee ce qui n'est pas possible chez moi puisque j'utilise un pizigate.
> L'autre piste est d'utiliser le SSD sur port usb2 en désactivant le UAD ou en effectuant un paramétrage spécifique de l'USB (Persistant USB).
> Voilà pour quelques pistes

Pourquoi je n'ai pas essayé plus tôt !!!!!
J'ai passé mon SSD sur port USB 2.0 et ça fonctionne !!!!! Pas de désactivation UAD ni aucun paramétrage.
Merci infiniment @nieren502 !

**Comment by nieren502** [comment]
De rien, je suis content si on a une solution ! Je viens d'essayer aussi :
Avec une rallonge USB pour mon SSD sur USB3 -> Aucun résultat, inclusion impossible.
Avec le SSD branché sur un port USB2 -> Ça marche, inclusion OK et signaux renvoyés par les capteurs.
Du coup on perd l'intérêt de l'USB3 mais on résout au moins le problème de carte SD et on peut avoir du volume de stockage (je veux utiliser des caméras).

**Comment by Xav-74** [comment]
> De rien, je suis content si on a une solution ! Je viens d'essayer aussi :
> Avec une rallonge USB pour mon SSD sur USB3 -> Aucun résultat, inclusion impossible.
> Avec le SSD branché sur un port USB2 -> Ça marche, inclusion OK et signaux renvoyés par les capteurs.
> Du coup on perd l'intérêt de l'USB3 mais on résout au moins le problème de carte SD et on peut avoir du volume de stockage (je veux utiliser des caméras).

A mon avis la rallonge c'est pour la clé Zigate. Donc pas possible pour toi. Je vais tester ca !

**Comment by Xav-74** [comment]
Je confirme ! Je viens de mettre ma clé sur une rallonge 1m branché sur mon hub USB et SSD sur USB 3.0 ça fonctionne !

**Comment by tcharp38** [comment]
Salut.
Bien joué. C'est une info à faire passer à "fairesoimeme" vu qu'il travaille sur la prochaine Zigate. Un filtrage elec pourrait la rendre + robuste.

**Comment by KiwiHC16** [comment]
J'ai lu que l'USB 3 du RPi4 avant quelques soucis en particulier du fait des signaux video qui provoque des perturbations...

**Comment by KiwiHC16** [comment]
Je clos ce sujet.
