### ISSUE TITLE
Inclusion impossible - Rpi4 SSD - Jeedom 4 - pizigate

### ISSUE THREAD

**Issue by nieren502** [KiwiHC16/Abeille#1110]
Bonjour
J'ai installé un Pi4 avec Raspbian Buster qui tourne sur un SSD et dessus, Jeedom 4.0.52.
Je viens d'acheter un PiZigate, que j'ai installé en utilisant la démarche adaptée au Pi4 donnée sur le wiki de Zigate. Le test du PiZigate effectué en ligne de commande fonctionne bien. Le test sous Jeedom - plugin abeille fonctionne également comme le montre le log Abeille_PiZigate suivant :
Execution de 'checkTTY.sh'
_Configuration du port /dev/ttyS0
= Ok
Contact de la Zigate
Reçu 8 bytes: 01 80 02 10 02 10 02 15
= Ok. Bonne réponse reçue de la Zigate_

Lorsque j'essaie de faire une inclusion (j'ai une série de capteurs et une smart plug Xiaomi), je passe en mode inclusion depuis le plugin abeille, la led du pizigate se met à clignoter, mais l'inclusion ne fonctionne pas et aucun périphérique n'est ajouté à la ruche (j'appuie bien sur les boutons d'association pendant 5 à 10s - l'inclusion fonctionne avec une gateway xiaomi).

Au niveau de l'interface d'abeille, la page de configuration me montre seulement les paramètres de config du PiZigate, mais pas vraiment ceux du plugin (d'après ce que j'ai vu sur des screenshot, on devrait pouvoir choisir un mode d'inclusion manuel ou automatique par exemple) ::

![image](https://user-images.githubusercontent.com/60428087/80725087-ecf69580-8b02-11ea-8271-2626837a92a6.png)

![image](https://user-images.githubusercontent.com/60428087/80725331-37781200-8b03-11ea-8b0b-2c4d9e611925.png)

La page de gestion du plugin ressemble à ça ::
![image](https://user-images.githubusercontent.com/60428087/80725209-0dbeeb00-8b03-11ea-94a2-70e9e6a33e04.png)

![image](https://user-images.githubusercontent.com/60428087/80725257-1dd6ca80-8b03-11ea-9519-9c505b231d3c.png)

J'ai déjà essayé de mettre à jour le firmware du PiZigate. Je suis maintenant en 3.1c.
Le canal zigbee est le 11, celui de mon wifi le 6.

Je ne sais plus trop quoi essayer, je veux bien un peu d'aide si vous avez une idée.
Merci d'avance !
;-)

**Comment by Xav-74** [comment]
ok on en est donc au même point je pense ! un souci d'inclusion.
Peux tu passer les logs en mode debug ? Puis vide les avant de relancer une inclusion puis poste les ici stp (log Abeille / AbeilleParser / AbeilleSerialRead1)

**Comment by Xav-74** [comment]
on va y arriver :)
on a à priori le même souci : l'équipement ne s'annonce pas

**Comment by nieren502** [comment]
Merci. ;-)
Je viens de faire le test d'inclusion avec un détecteur de présence (version avec le capteur de luminosité) et un capteur de fermeture de porte. Les logs sont joints.

[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4559186/AbeilleParser.txt)
[AbeilleSerialRead1.txt](https://github.com/KiwiHC16/Abeille/files/4559187/AbeilleSerialRead1.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4559188/Abeille.txt)

**Comment by Xav-74** [comment]
ah non je disais que c'était bon car j'avais installé AnyDevice :)

**Comment by Xav-74** [comment]
Je vais tenter un dernier test : revenir sur ma SD et supprimer mon SSD pour voir si cela vient de là

**Comment by tcharp38** [comment]
Impressionnant. On pourrait croire que ce sont les memes logs.

**Comment by nieren502** [comment]
Qu'est ce que c'est que AnyDevice (dsl je débute) ? Est ce que ça permet de contourner le pb ?

**Comment by Xav-74** [comment]
je dirai presque que cela me rassure : ce ne serait pas un pb hardware ou alors on a vraiment pas de chance

**Comment by Xav-74** [comment]
cela permet à Ben de prendre le contrôle à distance de ton PC pour faire des tests en live

**Comment by nieren502** [comment]
ah ok j'étais bien à côté de la plaque...
De mon côté, tout le matos est neuf sauf le SSD. J'ai une bonne alim stabilisée 5V 3A sur le Pi.
Je suis preneur si tu as une piste. J'arrive aux limites de mes compétences car je ne sais pas analyser ces logs.

**Comment by KiwiHC16** [comment]
nieren502, as tu essayé sans le SSD et sr une SD ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by nieren502** [comment]
Oui  j ai essayé aussi pour vérifier, en utilisant une carte sd a la place de mon SSD. L'inclusion fonctionne bien comme indiqué dans le post #1107 . C'est le même problème.

**Comment by KiwiHC16** [comment]
Tu veux dire que tu as le meme probleme que dans le cas #1107 ? Donc c est le SSD qui pose probleme ?

**Comment by nieren502** [comment]
Oui c'est bien ça. J'ai aussi essayé avec le plugin zigate et même problème

**Comment by nieren502** [comment]
Après quelques recherches, on a trouvé que le simple fait de relier le SSD sur un port USB2 au lieu du port USB3 permet à la zigate ou pizigate de fonctionner (inclusion OK, signaux reçus depuis les capteurs).
Si certains veulent chercher plus loin et faire fonctionner le SSD sur USB3, il y a des pistes ici : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1803
