### ISSUE TITLE
Config: 1 objet parent par Zigate

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1113]
Salut Kiwi.
Dans la page config, il y a 1 objet parent et un seul
![image](https://user-images.githubusercontent.com/35221038/80861049-580fab80-8c6c-11ea-80a4-5d403161677f.png)

Sauf erreur, on pourrait avoir un objet parent par zigate n'est ce pas ?
Je crois d'ailleurs que ca se configure via la page du plugin.

![image](https://user-images.githubusercontent.com/35221038/80861095-a91f9f80-8c6c-11ea-863b-363463a75445.png)

Si tu confirmes que c'est bien la même chose, je vais travailler sur une mise à jour de la page config.
Dis moi

**Comment by KiwiHC16** [comment]
On peut imaginer avoir un objet parent par défaut par zigate mais est ce bien nécessaire. Déjà l'idée de l objet parent a posé problème car les utilisateurs arrivent souvent de Zwave ou autre et ne comprennent pas l'idée.
C est configuré dans la age config dans Mode Paramètre. 
C est utilisé que pendant la creation d une ruche ou d une abeille.
Ensuite l utilisateur peux e changer au niveau de l équipement comme pour tout équipement jeedom.

**Comment by tcharp38** [comment]
L'objet parent par défaut c'est déja le cas la vu qu'il n'y a qu'un parent possible dans la page de config.
Apres ca n'est pas moi qui ai poussé pour du multi zigate mais je peux imaginer avoir une zigate par pieces specifique et pas toutes au meme endroit.
Enfin bon, ok. On garde un seul parent par défaut jusqu'a requete reelle.

**Comment by tcharp38** [comment]
Je reviens juste sur ta remarque "arrivent souvent de Zwave" pour comprendre un peu mieux.
Quel rapport ? Cette histoire d'objet parent est purement Jeedom et non pas spécifique Abeille n'est ce pas ? Tu veux peut etre dire qu avec le plugin openzwave ils n'ont pas à définir de parent ? C'est ca ?

**Comment by KiwiHC16** [comment]
Oui au debut les premieres versions d'Abeille demandait d'avoir un objet parent defini sinon crash du plugin.
Actuellement d'apres mes souvenirs, si il n'est pas défini, je prends le premier objet que je trouve dans la base ou un truc dans le genre.
Il n'y avait pas vraiment de demande pour le Multi mais moi j'avais un gros besoin de cette possibilité. Mon approche est d'avoir un objet "Preparation" qui est le objet parent. Comme j'ai 4 ruches, elles sont toutes sur cet objet et quand j'inclus un equipement il apparait ici et je l ouvre change son objet parent pour l'allouer à la bonne piece: SdB, cuisine,...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
@KiwiHC16 
Je reviens la dessus. j'ai pensé à un cas qui pourrait poser pb.
Par ex tu as deja 2 ruches et tu les as affecté chacune à une piece differente via la page de gestion.
Tu ajoutes une 3ieme ruche via la page de config avec un autre "objet parent" puis sauvegarde.
Qu'est ce qui se passe ? Seule la nouvelle ruche prend l'objet parent de config ?

**Comment by KiwiHC16** [comment]
Aujourd'hui, un objet pour toutes les ruches donc pas de soucis.
Si un objet par ruche alors lors de la creation on utilise l'objet associé à la ruche (on sait sur qu'elle ruche l'abeille est créé / On sait sur quel reseau zigbee a lieu l association) et normalement pas de soucis.

**Comment by tcharp38** [comment]
A réouvrir si besoin.
