### ISSUE TITLE
probleme trop de message  CAS A 

### ISSUE THREAD

**Issue by jossalison38** [KiwiHC16/Abeille#1114]
bonjour j'ai souvent des time out sur mes pheripherique , mais plus particulierement les prises ikea 
hier j'ai remarquer un message sur jeedom 
donc je vien vous demandé de laide 
voici la capture ecran
![image](https://user-images.githubusercontent.com/47280807/80868189-2bbe5400-8c99-11ea-9565-586d311c25f8.png)
voici les fichier en mode debug 

[AbeilleParser (4).txt](https://github.com/KiwiHC16/Abeille/files/4568004/AbeilleParser.4.txt)
[Abeille (1).txt](https://github.com/KiwiHC16/Abeille/files/4568016/Abeille.1.txt)

**Comment by KiwiHC16** [comment]
Interesant, encore jamais rencontré.
Peux tu partager une capture d'écran de la page santé pour commencer ?

**Comment by jossalison38** [comment]
merci pour l’intérêt que tu porte a mon problème 
voici mes capture d’écran sante , si tu a besoin d'autre chose fait moi signe 
petit info régulièrement dans abeille parser j'ai mes télécommande qui apparaisse pour des commande introuvable 
![image](https://user-images.githubusercontent.com/47280807/80891034-b9159e80-8cc1-11ea-91db-07df5d86172c.png)
![image](https://user-images.githubusercontent.com/47280807/80891050-c894e780-8cc1-11ea-9df7-520f10786614.png)

cordialement

**Comment by KiwiHC16** [comment]
Il y a beaucoup de "Telecommande Fixe". Quel est ce produit inconnu pour Abeille ?

**Comment by KiwiHC16** [comment]
6 prises Ikea dans le premiere page et 5 dans la deuxieme = 11
Et 15 volets Profalux: J'aurai jamais imaginé ca quand j'ai développé cette partie. C'est cool à voir ;-)
Ca nous fait 26 routeurs.

**Comment by KiwiHC16** [comment]
Toutes les minutes j'envoies 2 messages si Poll = 1. 
Soit 26*2 = 52 messages et le limite est à 60.
Avec quelques retransmission si des equipements sont hors reseau comme tes deux prises Ikea alors on doit être à plus de 60 messages.

Aie sauf qu'en regardant les modeles des volet et prise aucun n'a de Poll defini donc ca ne doit pas etre ca.

**Comment by KiwiHC16** [comment]
Par contre en regardant le modele defaut qui est utilisé dans tes télécommandes, lui il a le poll.
Devrait pas. Je l'enlève.
C est confirmé par le log Abeille.
Comme tu en as au moins 17, fois 2 ca fait 34 messages supplementaires par minutes et comme les équipements ne repondent pas ca fait 3 tentatives, soit 34*3 = 102 messages par minutes. Il est fort possible que cela fasse boule de neige et que ton systeme ne soit plus tres repondant !!!

Il faut mettre les poll dans tes telecommande à 0 et ca doit resoudre.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by jossalison38** [comment]
coucou KiwiHC16 , dessole pour les réponse tardive mais je ne suis actuellement pas devant moi pc , bricolage oblige .
en ce qui concerne les prise il y en a 8
4 dans les chambre , 3 a l’extérieure et 1 dans le garage 
pour les volet il y en a bien 15 
en ce qui concerne les inconnus , ce sont les télécommande qui correspond au volets .lors de l'inclusion je les est tous de suite enregistre avec le même nom que les volets pour savoir a quoi ils correspondez .
j'ai crée des télécommande groupe virtuel pour mes volets , de façon a les commandé via la google 

je n'ai pas trop compris l'histoire de poll , a vrai dire je ne comprend pas bien les terme technique 
serait t'il possible que tu m'explique comment changez ce poll ?
-petit question supplémentaire est ce que les time out des prise vienne de ce problème ? car avant j'avait pas de soucie sans mes volets 
a bientot

**Comment by KiwiHC16** [comment]
Difficile de répondre pour les timeout mais ca peut jouer.
Résolvons un sujet après l'autre.

le Poll est le fait qu'Abeille va interroger de temps en temps les équipements pour avoir des informations car les équipements ne les envoient pas par eux même.

Je n'ai pas de solution simple. Serais tu modifier un fichier en ssh sur ta machine ?

Sinon tu peux passer par Jeedom en suivant les etapes suivantes:

![Capture d’écran 2020-05-03 à 22 30 45](https://user-images.githubusercontent.com/8549674/80925133-bed8b600-8d8d-11ea-8c17-6b4354d43d5f.png)

![Capture d’écran 2020-05-03 à 22 31 08](https://user-images.githubusercontent.com/8549674/80925141-cac47800-8d8d-11ea-9b49-c9e7f5ec5495.png)

![Capture d’écran 2020-05-03 à 22 31 21](https://user-images.githubusercontent.com/8549674/80925145-d2841c80-8d8d-11ea-8be7-af4aeed08fa1.png)

![Capture d’écran 2020-05-03 à 22 31 52](https://user-images.githubusercontent.com/8549674/80925156-e4fe5600-8d8d-11ea-8fe8-0d898512e715.png)

![Capture d’écran 2020-05-03 à 22 32 11](https://user-images.githubusercontent.com/8549674/80925160-f0518180-8d8d-11ea-8b98-8c24b2aaf7bb.png)

**Comment by KiwiHC16** [comment]
Dans le fichier tu vas en ligne 256 pour trouver la function cron()
Comme tu as certainement une version differente le mienne la ligne est peut être différente.

Dans la fonction quelques lignes plus bas tu vas trouver:
            foreach ($eqLogics as $eqLogic) {
                list( $dest, $address)  = explode("/", $eqLogic->getLogicalId());
                if (strlen($address) == 4) {
                    if ($eqLogic->getConfiguration("poll") == "1") {

Tu changes == "1"
par == "toto"

tu sauvegardes et tu relaces le demon.

Apres quelques heures de fonctionnement comme cela on pourra regarder les TimeOut.

**Comment by jossalison38** [comment]
salut 
je viens de suivre tes explication pour la modification du poll.
 je te met des capture écran,
 pourrez tu me dire si ses bien le bonne endroit ou il fallait modifié , a mon avis oui au vu des explication
merci pour ton aide pour réglé le problème sur mon installe .
je reviens vers toi d'ici ce soir ou demain ( a ton avis combien de temps cela peut il prendre pour voir les effets sur le réseaux zigbee ? )
a très bientôt 
bonne journée 

AVANT
![Sans titre](https://user-images.githubusercontent.com/47280807/80941506-e86ffc80-8de2-11ea-9d57-5e7d6022f8cf.jpg)

APRES 

![2](https://user-images.githubusercontent.com/47280807/80941523-f6258200-8de2-11ea-9b16-fa36b9528240.jpg)

**Comment by jossalison38** [comment]
Coucou 
me revoila 
je joint des fichier de abeille , abeille parser et abeille cmd  
pourrez tu me dire si tu voit des problème après modification poll
j'ai remarqué que dans abeille , j'ai deamon info qui passe de in   a   out  . est ce normal ?
a bientôt
[Abeille (2).txt](https://github.com/KiwiHC16/Abeille/files/4573164/Abeille.2.txt)
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4573165/AbeilleCmd.txt)
[AbeilleParser (5).txt](https://github.com/KiwiHC16/Abeille/files/4573166/AbeilleParser.5.txt)

**Comment by tcharp38** [comment]
> Toutes les minutes j'envoies 2 messages si Poll = 1.

Kiwi, pour mon info, pourquoi envoyé 2 messages ?
J'ai cru comprendre que le but etait avant tout de montrer une activite necessaire pour toute Zigate Wifi (a cause des 5min de timeout ESPLInk). Je me gourre ? Le commentaire est faux ou incomplet ?
Merci

**Comment by KiwiHC16** [comment]
@tcharp38, c'est deux sujets differents.
1/ ESPLINK, on fait une demande a la zigate (un getVersion ou un truc du genre) pour maintenir le lien ouvert du fait du timeout. cf commentaire.
2/ Certains equipements de remontent pas leur infos par defaut. Par exemple les équipements Hue, donc dans le modele on défini une periode pour les interroger et recuperer les infos. Ici une minute.

**Comment by KiwiHC16** [comment]
@jossalison38 d apres tes captures d'ecran c est bon.

**Comment by KiwiHC16** [comment]
D apres ce que je vois dans les logs Abeille et AbeilleCmd, tout semble ok.

**Comment by jossalison38** [comment]
bonjour 
je reviens vers toi , pour une info .
jusqu’à présent tous fonctionné normalement .
même les prise ikea ne passé plus en time out , jusqu'a la mise a jour que j'ai faite avant hier .
je ne me suis pas m’effilez que cela pouvais effacé les modification faite précédemment 
du coup cette Apres midi  j'ai modifié la ligne .
je vous dirait si cela est revenu a la normale ?
après je fermerais le sujet 
cordialement

**Comment by jossalison38** [comment]
bonjour  
je fait suite a la  modification de abeille . tous marche de nouveau correctement
je n'est plus de time out , aussi sur mes différent  module 
merci beaucoup pour ton aide 
bonne continuation 
a bientôt 
cordialement

**Comment by jossalison38** [comment]
bonjour 
je me permet de revenir vers vous car mon probleme , trop de message cas a est revenu depuis que je suis passe a jeedom v4.061 sur un rpi4.
tous fonctionne maintenant mais se message revient tous le temp .
pourriez vous me dire si cela est grave et que puis je faire?
merci par avance 
voici quel que ecran un fichier debug:
![image](https://user-images.githubusercontent.com/47280807/103536230-6a448800-4e92-11eb-8bfb-d91d00195192.png)

**Comment by jossalison38** [comment]
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5764682/AbeilleCmd.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5764683/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5764684/AbeilleParser.log)


[Abeille (3).txt](https://github.com/KiwiHC16/Abeille/files/5764686/Abeille.3.txt)
