### ISSUE TITLE
Mettre à jour la page version mobile du fait du multizigate.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1119]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-19 à 13 51 01](https://user-images.githubusercontent.com/8549674/99668611-4528c100-2a6e-11eb-9339-3566be73dfe3.png)

Dans configuration plugin Abeille, activer Panneau Mobile

![Capture d’écran 2020-11-19 à 13 49 11](https://user-images.githubusercontent.com/8549674/99668472-114d9b80-2a6e-11eb-864b-f8b85b14b964.png)

Version mobile

![Capture d’écran 2020-11-19 à 13 52 07](https://user-images.githubusercontent.com/8549674/99668744-6b4e6100-2a6e-11eb-9250-6bd57a3b8939.png)

Plugins -> Abeille

![Capture d’écran 2020-11-19 à 13 52 41](https://user-images.githubusercontent.com/8549674/99668817-802af480-2a6e-11eb-901e-f4dac928220c.png)

Cette page ne prend pas en compte les dernieres evolutions.

Par exemple affiche 5 zigate alors qu'une seule est active.

**Comment by KiwiHC16** [comment]
Fichier a mettre a jour:
https://github.com/KiwiHC16/Abeille/blob/master/mobile/html/abeille.html

**Comment by Guiz67** [comment]
Ok je vais commencer à regarder ca.
Je vais juste monter mon environnement avant :)

**Comment by tcharp38** [comment]
Je clos ce sujet.
Pas beaucoup d'interet de jouer avec Abeille via un mobile et pas de temps à consacrer à ça.
