### ISSUE TITLE
Valeur d'état étrange et scénario perturbé

### ISSUE THREAD

**Issue by JohnDoe15152** [KiwiHC16/Abeille#1121]
Bonjour, et merci pour ce super plugin. Je rencontre toutefois un problème avec interrupteur Xiaomi. C'est un interrupteur mural simple sans fil, carré (nom dans le plugin abeille: XiaomiButtonb186acn01). Lorsque j'essaie de faire un scénario qui active une prise connectée, des erreurs surviennent. Tout d'abord, je met comme déclencheur l'état de l'interrupteur. Ensuite, si la prise est on, éteindre, si off allumer. Dans la condition SI, si je met état 1, ça ne fonctionne pas. Si je met 0, ça fonctionne. Ça ne devrait pas être l'inverse plutôt?
De plus, lorsque j'actionne l'interrupteur, environ 1m30 après l'avoir actionné, la prise de déclenche toute seule, sans rien toucher. Je ne comprends pas pourquoi.
Pourriez vous éventuellement me diriger sur une piste pour résoudre ces problèmes svp?
Merci et bonne journée !

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Regadardes ma reponse dans :
https://community.jeedom.com/t/scenario-zigate-abeille-avec-interrupteur-xiaomi-mural-sans-fil-carre/27219/14

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by JohnDoe15152** [comment]
Alors, bizzarement, après avoir supprimé et ré inclus l'équipement, ça ne me l'a plus fait, donc problème résolu! Et au passage, merci pour ton super plugin, au top!

**Comment by KiwiHC16** [comment]
Bienvenu et content de voir qu'il est utilisé.
Je clos donc.
