### ISSUE TITLE
Prise Xiaomi EU

### ISSUE THREAD

**Issue by Freeman656** [KiwiHC16/Abeille#1124]
Bonjour,
Déjà merci beaucoup pour ce plugin !
Je viens d'acquérir un prise type wall plug de Xiaomi (Mi Smart Plug ZigBee EU) et j'ai l'impression que ce composant n'est pas bien reconnu.
Déjà au niveau de l'inclusion, il ne me le reconnait pas (lumi.plug.mmeu01), donc j'ai ajouté la config pour ce device un peu à l'arrache, dans le dossier Abeille/**/devices/plug.mmeu01 avec l'image qui va bien égalmeent, et il est bien reconnu maintenant.
Par contre au niveau de la remonté des valeurs, le On/Off/Toggle fonctionnement, mais pas la remontée de puissance/conso. Et c'est là que s'arrête mes capacités en terme d'intégration.

Donc la log du parser, j'ai cette info qui remonte toutes les 10s donc j'ai envie de dire que c'est la valeur de conso.... :

[2020-05-07 09:40:50][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=43, SrcAddr=1fc1, EndPoint=15, ClusterID=000C, AttrID=0055, AttrStatus=00, AttrDataType=39, AttrSize=0004, DataByteList=42caa9fc
[2020-05-07 09:41:00][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=44, SrcAddr=1fc1, EndPoint=15, ClusterID=000C, AttrID=0055, AttrStatus=00, AttrDataType=39, AttrSize=0004, DataByteList=42b7428f

Et en regardant vite fait dans le code, j'ai l'impression que le EndPoint 15 pose problème.

Bref, si quelqu'un peut me filer un coup de main pour l'intégration de ce device, ce serait cool.

Cdlt,

**Comment by Freeman656** [comment]
Bon alors c'était pas si compliqué en fait pour la partie conso instantanée, j'ai juste modifié la condition dans le parser  pour le datatype 39 / cluster id 000c et attid 0055 :

if (($EPoint=="02") || ($EPoint=="15"))

Et ça me remonte bien une information qui a l'air correcte.

Si besoin, je peux faire un push de mes modifications...

**Comment by KiwiHC16** [comment]
Salut
Oui fait un PR pour que tout le monde profite du nouveau module.

**Comment by KiwiHC16** [comment]
Ok dans le code. Je clos le sujet.
