### ISSUE TITLE
Problème d'inclusion ampoules Phillips Hue & Osram

### ISSUE THREAD

**Issue by Licoti** [KiwiHC16/Abeille#1127]
Bonjour,

Je rencontre quelques problèmes pour inclure différentes ampoules. J'ai lu la doc mais il me semble qu'elle n'en font pas parties. Y aurait-il une possibilité de les ajouter ? :)

- J'ai une [Phillips Hue Filament](https://images-na.ssl-images-amazon.com/images/I/71lAemc1fjL._AC_SL1500_.jpg), j'ai ajouté le GetName comme dans la doc, mais aucune réponse :
![phillips](https://user-images.githubusercontent.com/539146/81501840-ba0a8980-92da-11ea-88d3-5f1cf3ca3ca0.JPG)
_(dans l'image j'ai ajouté le short name dans le titre et 0B dans le champ message comme indiqué dans la doc)_

- Et, j'ai une ampoule Osram qui n'est pas indiqué dans la doc : https://images-na.ssl-images-amazon.com/images/I/713u8jAWvUL._AC_SL1500_.jpg
![osram](https://user-images.githubusercontent.com/539146/81501993-81b77b00-92db-11ea-9398-2ebe1eb641d8.JPG)

Je précise que les boutons identify marchent bien, il me manque juste les boutons On/Off

Merci beaucoup :)

**Comment by KiwiHC16** [comment]
As tu renseigné manuellement les nom "LWA004" et "B40 TW - LIGHTIFY" ou est ce Abeille qui récupéré cette info ?

**Comment by Licoti** [comment]
Hello, merci @KiwiHC16 pour ta réponse.
Je confirme que c'est Abeille qui a récupéré toutes ces infos.

**Comment by KiwiHC16** [comment]
Dans ce cas il reste à faire les modèles sur cette base. Je le ferai dès que possible. 
Peux tu fournir les informations / spécifications de ces produits : contrôle de l intensité, couleur, blanc,....

**Comment by Licoti** [comment]
Ok, voici :
**OSRAM Smart+ Culot E14 :**  Dimmable + température de couleur
Blanc Chaud/Froid 2000/6500K.

**Philips Hue White Filament E27 :** Variation d'intensité uniquement

**Comment by Licoti** [comment]
Hello @KiwiHC16 ,
Des nouvelles de votre côté ? J'ai vu des Maj passées, mais c'est toujours ko de mon coté :'(

**Comment by KiwiHC16** [comment]
Salut,
Désolé pour le délai.

LWA004 est dans les modeles: https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/LWB004
Pourrais tu re-essayer ?

B40 TW - LIGHTIFY n est pas dans le modeles.

Pourrais tu faire une inclusion de ces ampoules en mettant le plugin en debug et partager les logs Abeille, AbeilleParser ?

**Comment by jkyndt** [comment]
Bonjour
Est ce que LWA004 et LWB004 sont les mêmes profiles?
Mes logs sont vides en mode debug pour ces deux mêmes ampoules quand je les inclus.
Merci pour tout le travail

**Comment by tcharp38** [comment]
Salut @Licoti 
Ce sujet est toujours d'actualite ?
Des soucis ?

**Comment by tcharp38** [comment]
Sans nouvelles je clos le sujet.
A réouvrir si besoin.
