### ISSUE TITLE
Table des noeuds, mise à jour LQI impossible

### ISSUE THREAD

**Issue by Franckybel** [KiwiHC16/Abeille#1128]
Bonjour,

Quand je souhaite visuliser la table des noeuds, j'ai ce message
![2020-05-10_22h11_48](https://user-images.githubusercontent.com/53462598/81509776-5baace80-930d-11ea-942e-afdd629d9e60.png)
Quand je clique sur Refresh LQI Z1, j'ai ce message alors que le refresh précédent avec le même message a été lancé la veille
![2020-05-10_22h12_02](https://user-images.githubusercontent.com/53462598/81509778-5d749200-930d-11ea-911b-3ad19408bd43.png)
La fenêtre suivante s'affiche mais la construction de la table ne s'effectue pas 
![2020-05-10_22h12_13](https://user-images.githubusercontent.com/53462598/81509779-5f3e5580-930d-11ea-8e2b-9c5303795c95.png)

Cela s'est produit depuis la mise en place de la dernière version officielle.
Merci pour le support.

**Comment by tcharp38** [comment]
Salut.
J'ai déja vu ce souci. Il me semble qu'il est fixé pour la prochaine release mais en attendant tu peux essayer de détruire le fichier de lock et t'assurer que le répertoire tmp existe.
/var/www/html/plugins/Abeille/Network/tmp/AbeilleLQI_MapDartaAbeille1.json.lock

**Comment by KiwiHC16** [comment]
Oui effaces fichier lock ou redemarre demon doit faire le boulot sur les dernieres versions.
Il y avait aussi des soucis dans les dernieres versions et je pense que tout est résolu dans la version beta ou celle de dev que je devrais transformer en stable des que possible.

**Comment by Franckybel** [comment]
Super, cela fonctionne merci à vous deux
