### ISSUE TITLE
Possibilité de bloquer la creation de nouvelles Abeilles

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1129]
Si nous savons que toutes les abeilles sont créées alors on doit pouvoir bloquer la creation et forcer la ré-utilisation des abeilles existantes si on voit une nouvelle apparaitre.

**Comment by Soyann** [comment]
Hello,
Peut-être devrais-tu t'inspirer du plugin RFXcom, où il y a un bouton 'Récupérer ID' pour associer un objet à un équipement en cas de changement de pile ;) 
https://jeedom.github.io/plugin-rfxcom/fr_FR/

**Comment by KiwiHC16** [comment]
Interressant.

**Comment by tcharp38** [comment]
@KiwiHC16 
Salut. Tu peux préciser le contexte ? Je pige pas ce que tu entends pas "réutilisation des abeilles existantes". Ton plugin supporte déja le changement d'adresse courte si reinclusion donc dans quel cas on peut avoir un nouvel equipement sans être vraiment nouveau ?
Ha... tu parles de remplacement d'un equipement HS peut etre ?

**Comment by Soyann** [comment]
C'est un cas, mais aussi pour prévenir en cas de création d'objet fantôme comme vu il n'y a de ça pas si longtemps. Peut-être également utile lorsqu'on passe une abeille d'une ruche à une autre (mulizigate)...

**Comment by KiwiHC16** [comment]
Il doit y avoir des cas qu'Abeille ne capture pas car j'ai des équipements qui sont créés alors qu'ils existent déjà. J'ai en particulier 2 télécommandes Ikea qui n'arretent pas de se multiplier. Il est possible qu'il y ai un truc autour de Rejoin. 
J'ai ouvert ce cas pour garder en t^te l idée et voir comment cela peut fonctionner pour l utilisateur final.

**Comment by tcharp38** [comment]
Ca marche mais il faudra lister les differents cas à supporter car jusque la en dehors du cas "remplacement equipement HS" je ne vois ce "blocage" que pour palier à un pb non résolu/compris.
En ligne avec ca ?

**Comment by KiwiHC16** [comment]
Exact.

**Comment by KiwiHC16** [comment]
Suite a reinstallation les command son vide et donc les IEEE ne sont plus renseignées ce qui provoque des fantômes. Passer la valeur IEEE de commandes à param de config ?

**Comment by KiwiHC16** [comment]
Sur réveil ,IR Ikea:

```
[2020-06-01 23:00:25][debug] Type=004d/Device announce: Dest=Abeille3, SrcAddr=a613, IEEE=ec1bbdfffea04cce, MACCapa=80, Rejoin=02
```

**Comment by KiwiHC16** [comment]
La casse sur le IEEE est maintenant sous controle enfin j espere.
