### ISSUE TITLE
Volets profalux en timeout

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1135]
Je log ce point car toujours pas résolu avec la stable "14 mai 2020".
Ca doit être commun avec plusieurs autres pbs remontés par les utilisateurs.
Je creuse de mon côté;

Jeedom v3, Abeille stable 14 mai 2020

Les volets sont parfaitement fonctionnels donc surement pas en timeout.

![image](https://user-images.githubusercontent.com/35221038/82063590-f61f5f00-96cb-11ea-9f13-9262671cb04d.png)

**Comment by dams74** [comment]
De mon côté, j'en ai un qui est passé en time out.
il fonctionne via sa télécommande mural mais impossible depuis jeedom
Besoin de log ou autre ?

**Comment by tcharp38** [comment]
Salut @dams74 
De mon côté j'ai fixé un bug qui semble solutionner mon pb de timeout de mes volets.
Je teste encore un peu et je pousserai une fois que Kiwi à intégré ma livraison précédente.
Je ne suis pas sur que ca soit le même souci que toi, vu que je peux quand même piloter mes volets malgre le timeout.

**Comment by dams74** [comment]
Salut
Oui bizzare, je n'ai pas réinclus le volet pour le moment au cas où il y est besoin d'un log quelconque

**Comment by tcharp38** [comment]
Si tu veux creuser un peu, voila ma compréhension.
Pour les equipements sur secteur, il y a un "ping" toutes les minutes pour voir s'il sont toujours "en vie". Tu dois donc pouvoir trouver dans le log "Abeille" un ping vers l'adresse courte de ce volet.

Ensuite et en supposant que le volet est toujours dans le reseau géré par ta zigate, tu dois avoir une réponse de cette adresse courte, à voir via "AbeilleParser".

Je regarde ce soir si j'ai le temps pour avoir + de details sur ces infos.

**Comment by dams74** [comment]
Tu vois il suffit de vouloir investiguer et mon volet n'est plus en time out...
Pour voir si il était toujours dans le réseau, j'ai via la télécommande zoé donné l'ordre de descendre à tous mes volets et celui en time out à bien répondu.
Je suis allé voir dans jeedom et il était plus en time out...
A suivre

**Comment by jossalison38** [comment]
bonjour 
je viens de voir votre sujet sur le time out  . j'ai eu des problème moi aussi .
après avoir modifie le plugin via les conseille de kiwi (cause les télécommande des volet ) 
cela a bien fonctionné .
Allez voir mon sujet  "probleme trop de message CAS A"
j'au aussi faite un scenario de get level , suivant les conseille de cyrililo 
a cette adresse https://community.jeedom.com/t/plugin-abeille-pour-la-zigate-zigbee-fil-principal-des-news-et-discussions/2774/522       .    **date du 11 avril** 

en espèrent que cela vous aide 
cordialement

**Comment by KiwiHC16** [comment]
Peut on fermer ce cas ou il y a des choses a faire ?
