### ISSUE TITLE
Philips hue single bulb e27 warm white LWA001

### ISSUE THREAD

**Issue by misterchikite** [KiwiHC16/Abeille#1143]
Bonjour,

Sais-tu si il est possible de rajouter la compatibilité avec les ampoules LWA001 (bluetooth et Zigbee) ? 

Merci d'avance
Cordialement 
Chikite

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Bonjour,
Je n'ai pas d'info sur cette ampoule. Des liens vers les specifications techniques ?
Pour la partie Bluetooth, Abeille ne prend pas cela en charge.
Pour la partie Zigbee, probablement mais demande des investigations.

**Comment by misterchikite** [comment]
C'est des ampoules a 20 euros. 

Voici la spécificité de l'ampoule.
https://www2.meethue.com/en-gb/p/hue-white-1-pack-e27/8718696785317

Oui oui je savais pour le bluetooth, c'était juste pour indiquer que c'etais le modèle bluetooth zigbee. 
Et le modèle c'est LWA001. 
J'imagine qu'il faut récupérer l'ID du modèle de la lampe mais bon c'est ma première hue et j'y connais pas grand chose :)

**Comment by KiwiHC16** [comment]
Pas de trace de zigbee dans la page indiquée.

**Comment by misterchikite** [comment]
Oui effectivement c'est la page descriptif du produit et non celle du zigbee.
Je vais me débrouiller pour chercher les infos Zigbee.

Je remontais juste l'information savoir si il était simple ou possible de rendre compatible ce type d'ampoule.

Je suis qu'un utilisateur du protocole Zigbee rien de plus.

**Comment by letictac67** [comment]
regarde ce post moi j'vais des LTA001 
https://github.com/KiwiHC16/Abeille/issues/1052

**Comment by misterchikite** [comment]
Merci 
Oui j'avais vu un autre poste parlant de ça.
Mais j'imagine qu'il ne suffit pas de copier/renommer le Json LTA001 en LWA001 pour que cela fonctionne. 

Il faut l'id de l'ampoule non ?

**Comment by KiwiHC16** [comment]
Si ton ampoule est effectivement Zigbee (pas vu d info dans ce sens, et cela serait pour moi la premiere ampoule dans ce cas, mais rien d'impossible) alors prend LTA001 comme modele et fait le meme fichier json en remplacant tout par LWA001 (a faire dans le fichier json, changer le nom du fichier json et le nom de son repertoire).

Si tu me trouves une confirmation du fait quelle est Zigbee, je peux te faire le modele. Mais comme mon temps est compté, je souhaites la doc en premier...

**Comment by Brugal21** [comment]
Salut,

Je viens de recevoir cette ampoule philips, pour info, en promo chez Amazon à 4,99€ au lieu de 17,99€. J'ai galéré la soirée pour la faire fonctionner, avant de trouver cette issue... En reprenant le fichier json de la LTA001 pour en faire un LWA001, cela fonctionne parfaitement (j'ai laissé le modèle de la LTA001 pour l'icône de l'objet). Il a ensuite fallu que je supprime l'équipement et éteindre et rallumer l'ampoule en attendant 15sec. Abeille a recréer l'équipement avec toutes les commandes ! C'est tout bon, l'ampoule s'allume / s'éteint et varie en intensité ! @KiwiHC16 juste besoin de recopier le json de la LTA001 pour créer la LWA001, l'icône de la LTA est bonne pour la LWA.

**Comment by KiwiHC16** [comment]
Super. Je viens de le faire et mis dans le master.
