### ISSUE TITLE
Livolo zigbee délai d'allumage/extinction

### ISSUE THREAD

**Issue by jerome83136** [KiwiHC16/Abeille#1150]
Hello,

J'ai un interrupteur Livolo (vlc702z) que j'ai réussi à intégrer dans Jeedom avec Abeille.

J'ai remarqué qu'il y avait un délai plus ou moins long entre l'activation d'une commande dans Jeedom et l’exécution de l'ordre sur l'interrupteur.

Exemple: si j'appuie sur "On1" le relais 1 s'active au bout de ~3 - 5 secondes (parfois avec nécessité de relancer la commande plusieurs fois depuis Jeedom)

J'ai le cas avec toutes les commandes sur cet inter. (On1 , Off 1, On 2, etc...)

Par contre ce qui m'intrigue c'est que lorsque j'allume l'interrupteur manuellement depuis le bouton physique, l'information remonte en max 1 seconde sur Jeedom.

Quelqu'un aurait-il la gentillesse de m'éclairer ?

Merci d'avance

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Cela vient du mode de fonctionnement de l interrupteur.
Il se reveille de temps en temps (toutes les 3 secondes) pour demander sa commande et la zigate lui donne. Donc tu dois avoir un temps de l ordre de 4s.
Dans le cas de la remontée d'info, il reagit immediatement a ton doigts et envoie l info a la zigate dans  l instant.

**Comment by jerome83136** [comment]
Hello,
Merci beaucoup pour le retour.

Du coup vu le mode de communication de cet interrupteur (inter qui interroge la zigate régulièrement pour savoir s'il a des commandes en attente)  je n'ai aucun moyen de raccourcir ce temps j'imagine ?

Cela dit le délai est assez variable. Ça va de 3 à 4 secondes jusqu'à parfois ~ 15 secondes.
Parfois la commande n'est tout simplement j'aurais exécutée.

J'imagine que ces interrupteurs sont un peu capricieux ^^

Si ça se confirme, je pense que je vais me rabattre sur un autre type d'inter du coup :-)

Merci au passage pour ton boulot sur le plugin ;-)

Bonne journée

**Comment by KiwiHC16** [comment]
Pour moi celui que j'ai est dans les 3 ou 4s et c est tres bien pour mon utilisation.
C'est qu'il ya qq chose qui charge le systeme.
Si tu pilotes une ampoules, il vaut mieux une ampoule zigbee qui elle va reagir des qu'elle recoit l ordre (routeur). Les inter qui repondent tout de suite (mode routeur) ne sont pas nombreux et je crois me souvenir qu'il y a que celui de Legrand.

**Comment by jerome83136** [comment]
Ok, je dois avoir un problème de charge du coup en effet.

Je pense que je vais me rabattre sur le shelly dimmer sw quand il sera dispo et aussi convertir mes interrupteurs traditionnels.

Merci pour ton aide.
