### ISSUE TITLE
AbeilleInterrogate.php without rigth answer

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1151]
AbeilleInterrogate.php Abeille1 c7f9

Zigate <-> Prise Ikea <-> Door Xiaomi

Comme Door Xiaomi dort pas de reponse de sa part mais Prise Ikea repond avec son adresse IEEE mais ne fourni pas celle de Door Xiaomi.

Idem avec Xiomi Smoke.

So we don't get the answer and we slow down the network ;-(

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Obsolete.
AbeilleInterrogate n'est plus utilisé.
