### ISSUE TITLE
Perte ampoules/prise Ikea

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1154]
Bonjour,
Comme ça, sans prévenir ni aucune action particulière (j'étais sur la route, et ce n'est pas ma femme qui allait y toucher), j'ai perdu sur la Zigate 1 (USB) d'un coup mes 2 prises Ikea, et 4 des 5 ampoules Ikea (TimeOut)
Si je les débranche / branche, ces dernières n'apparaissent plus en TimeOut, par contre, aucune action ne passe... Idem après redémarrage du système; aucun pb par contre sur la dernière ampoule, ni sur les capteurs Xiaomi reliés directement à la ZG
Une idée?

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4718643/Abeille.txt)
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/4718644/AbeilleCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4718645/AbeilleParser.txt)

Merci d'avance
 PS: Petit complément d'information: les ampoules en TimeOut sont toujours pilotable par les interrupteurs (Hue 4 boutons), de plus, tout à l'aire d'être tombé en même temps, ce qui me fait bien penser à un pb Zigate
 
Autre précision: les XIaomi qui passaient par les routeurs en TimeOut ne veulent plus rejoindre le réseau sur inclusion (au niveau des voyants sur le module) mais il y a une communication avec Jeedom vu qu'il n'apparaissent plus en TimeOut (ce n'est pas pour autant que j'ai de remontée d'infos, et ils retombent)
Si je vais une inclusion d'une prise Ikea, j'ai bien le message de maj automatique, mais plus rien derrière.

Pour ma dernière ampoule vivante, elle passe également en timeout, mais re-vie si je l'actionne depuis de Tradfri carré 2 boutons.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Firmware 3.0F
```
[2020-06-02 16:55:25][DEBUG] : fct message Topic: ->Abeille1/Ruche/SW-SDK<- Value ->030F<-
[2020-06-02 16:55:25][DEBUG] : fct message Topic: ->Abeille2/Ruche/SW-SDK<- Value ->030F<-
```

**Comment by KiwiHC16** [comment]
Avant que je ne me plonge dans les logs, as tu:
- la date et le heure du probleme ?
- les adresses courte ou IEEE des equipment HS ?

**Comment by Soyann** [comment]
Bonjour KiwiHC,
Heure de la première remontée pour Bureau Ikea-Est/Ouest/Moniteur, Salle de Jeux Mi-Home, Escalier Lumière-Placard, Marion Lampe à 14h50 avec un TimeOut à 60 min. Vu que mon système était super stable, j'économisais le SSD de ma machine (qui n'est pas un RPI mais un Z83) avec des logs par défaut...

Voici les abeilles impactées:
![image](https://user-images.githubusercontent.com/46709337/83605053-83d9c600-a577-11ea-8eec-0be75b861ddb.png)

En te remerciant

**Comment by KiwiHC16** [comment]
As tu essayer de debrancher / rebranchée la zigate et redemarrage du demon ?

**Comment by Soyann** [comment]
oh le boulet...
Bon, j'ai bien miséré à remettre la prise sur laquelle j'ai fait mes tests d'inclusion, mais on dirait que ça va mieux après un reset à la télécommande 4 boutons (ne voulait rien savoir autrement)
Je garde l'issue ouverte jusqu'à demain matin pour vérifier que c'est stable.
Merci encore, et désolé pour la perte de temps.

PS: je sais que ça serait bien de mettre à jour le firmware, mais vu la colonie sur mes ruches, j'ai la flemme de faire la bascule de chaque objet (commande/histo/widget, vivement un bouton de transfert #1055 ), tant que ça va comme ça...

**Comment by Soyann** [comment]
Bonjour,
Je clos, même si j'ai toujours un problème avec un groupe ampoule Ikea -> interrupteur Tradfri carré 2 boutons que je n'arrive pas à faire fonctionner correctement malgré la documentation (mode boulet bis repetita, j'avais déjà galéré la première fois). Je manque de temps pour approfondir, il faut que je le trouve.

En te remerciant de nouveau, et en m'excusant pour ta perte de temps
