### ISSUE TITLE
Page du plugin incohérente en multi-onglet Abeille 

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#1156]
Testé sous Firefox 76 et Master 7f7ee2d5020aa943..., la page du plugin devient incohérente si on ouvre 2+ onglets Abeille.

![image](https://user-images.githubusercontent.com/48121420/83563161-041e0e00-a51b-11ea-81bf-ab351e127da4.png)

**Comment by KiwiHC16** [comment]
Tres bizarre.
J ai aussi eu ca sur la version master, je ne crois pas l avoir vu sur la stable (a verifier) quand on fait un refresh d'une page dans le browser web (safari), mais pas si on entre l adresse de Jeedom.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Oui j'avais ca moi aussi hier mais pour moi c'est loin d"etre recent. Je croyais etre le seul d'ailleurs. Ca a fini par disparaitre apres plusieurs redemarrages d apache.
Je ne suis pas encore convaincu que ca vienne d'Abeille. J'avais aussi de la non reaction (je clique et rien ne se passe) sur d'autres parties de Jeedom hors abeille.

**Comment by Asyrah** [comment]
Ce qui est bizarre, c'est que seul le plugin Abeille a ce soucis chez moi. Les autres plugins (21) fonctionnent bien en multi-onglets, Abeille c'est systématique...

**Comment by tcharp38** [comment]
Qu'est ce que tu appelle "multi onglets" ?

**Comment by Asyrah** [comment]
> Qu'est ce que tu appelle "multi onglets" ?

Avoir 2 onglets Abeilles ouverts simultanément

![image](https://user-images.githubusercontent.com/48121420/83613397-02d4fb80-a584-11ea-9781-4a661c5ecec6.png)

**Comment by tcharp38** [comment]
Ha oui ?! Du coup si tu en fermes un ca fonctionne correctement ?

**Comment by Asyrah** [comment]
Si on ferme le 2e onglet ouvert oui, la première page fonctionne toujours.
Si on ferme le 1er onglet, la seule solution trouvée est de charger un autre plugin puis ouvrir de nouveau Abeille. Ça fonctionne 3 fois sur 4, parfois j'obtiens des boutons sans réaction (je clique et rien ne se passe). Le retour sur le dashboard a aucun effet.

Je penche pour un soucis Jeedom mais bizarre que ça ne touche que le plugin Abeille chez moi

**Comment by tcharp38** [comment]
Merci pour ces pistes. Je n'avais effectivement pas fait le lien avec un deuxieme onglet ouvert.
Comme j'ai ce souci de temps en temps j'espere trouver du temps pour creuser.

**Comment by KiwiHC16** [comment]
Je l ai a tout les coups si je vais dans la page Configuration Abeille et je fais un Refresh de la page depuis le menu du browser. Je suis avec Safari.

**Comment by tcharp38** [comment]
Tu saurais me dire comment reproduire du coup ?
La je n'y arrive plus.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-06-04 à 11 15 08](https://user-images.githubusercontent.com/8549674/83738492-a857a000-a654-11ea-89b9-deef41eec81e.png)

Un simple clic sur les fleches en boucle (refresh) dans la barre d URL. A cote du texte "Recharger cette page"

**Comment by KiwiHC16** [comment]
Une autre facon de faire est dans cette meme page de ckic sur "Get Group". Ce qui est similaire car fait un refresh de la page.

**Comment by KiwiHC16** [comment]
J'ai le soucis sur mon system de dev avec le master mais pas sur mon systeme de prod qui est la version stable plus qq correction (Branche stabilisationProd dans github).

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-06-04 à 12 02 55](https://user-images.githubusercontent.com/8549674/83743738-68e08200-a65b-11ea-8574-d6d8a02e68ce.png)

J ai aussi ce message dans la console Safari.

**Comment by tcharp38** [comment]
C'est bon je reproduis avec Chrome. 
Je n'ai pas l'erreur dont tu parles mais je creuse.

**Comment by tcharp38** [comment]
C'est fixé pour moi

**Comment by Asyrah** [comment]
Mise à jour faite, fixé aussi pour moi (firefox) 👍 .
Je clos
