### ISSUE TITLE
Récupération d'état interrupteur filaire Legrand with Netatmo

### ISSUE THREAD

**Issue by zabouille** [KiwiHC16/Abeille#1163]
Bonjour

J'ai intégré des interrupteurs filaires de volets roulant Dooxie with Netatmo. (Reconnus comme Shutter switch with neutral)

Voici les derniers que j'ai intégrés:

```
[2020-05-27 20:09:34][INFO] : Recherche objet:  Shutter switch with neutral dans les objets connus
[2020-05-27 20:09:34][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/Shutterswitchwithneutral/Shutterswitchwithneutral.json will send back default template.
[2020-05-27 20:09:34][INFO] : Creation de la commande: IEEE-Addr suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:34][INFO] : Creation de la commande: Link-Quality suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:34][INFO] : Creation de la commande: Time-Time suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:34][INFO] : Creation de la commande: Time-TimeStamp suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: Power-Source suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: Short-Addr suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: online suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: 0000-01-0005 suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: 0000-01-0004 suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: 0000-01-4000 suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: getManufacturerName suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: getModelIdentifier suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: getSWBuild suivant model de l objet pour l objet: Abeille1-7461
[2020-05-27 20:09:35][INFO] : Creation de la commande: Identify suivant model de l objet pour l objet: Abeille1-7461
```

Sur les premiers que j'ai intégré en février, il y avait bien les actions pour monter/descendre/arrêter les volets.
Sur les derniers, ces actions n'étaient pas créées, je les ai donc ajouté manuellement.

Je voudrais ajouter une action et une info pour récupérer l'état (ouvert ou fermé)

Je pense qu'il faut créer une action getEtat et une info etat mais je ne sais pas comment récupérer ce qu'il faut mettre dans Topic et Payload.
Et pour le type Info, je ne peux pas la créer manuellement (dev en cours).

Peux-tu m'aider pour cela?

Et que faudrait-il pour ajouter le modèle json de cet équipement?

Merci d'avance de ton aide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Shutterswitchwithneutral

**Comment by KiwiHC16** [comment]
Peux tu partager les informations sur le produit ? les specifications ? Une image ?
Dans la ruche tu dois trouver une commande "SimpleDescriptorRequest". Affiches la et envoies la commande sur l equipement 7461 et avec le EndPOint 01. partages le résultat que tu dois recuperer dans AbeilleParser.

**Comment by zabouille** [comment]
Bonsoir
C'est un Interrupteur filaire connecté Dooxie with Netatmo pour volet roulant  Legrand référence 600086
Voici le lien sur le site de Legrand:
https://www.legrand.fr/catalogue/interrupteur/interrupteur-pour-volet-roulant-a-cabler-pour-installation-connectee-dooxie-with-netatmo-avec-plaque-blanche

Il s'installe à la place d'un interrupteur filaire de volet roulant avec un neutre.

Voici l'image
![600086_pw_245784_pz](https://user-images.githubusercontent.com/59845540/84072900-34a8f080-a9d0-11ea-8021-da4d80e5a2fd.jpg)

Voici le parser
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4748208/AbeilleParser.txt)

Merci

**Comment by zabouille** [comment]
Bonjour
J'ai reçu un nouvel interrupteur (je les achète petit à petit), Je ne sais pas si c'est plus complet ou pas alors je t'ajoute le paser de l'inclusion de ce nouvel interrupteur.
Bonne journée!
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4774143/AbeilleParser.txt)

**Comment by kaleofr** [comment]
Bonjour à tous,

J'ai également intégré des commandes pour volet Legrand Netatmo Céliane.
Comme déjà évoqué, je ne maitrise pas tout (include??? uniqId choisi au hazard, etc) mais les fichiers ci-dessous me donnent satisfaction... et si ca peut aider.
Tout n'est peut-être pas utile d'ailleur.

Pour le retour de la position c'est 0%, 50% ou 100%.
0% et 100% sont retournés lorsque le volet est arrivé en buté et que l'interrupteur arrète d'alimenter la montée/descente après quelques secondes.
Si le volet arrive ne buté que que vous envoyez un ordre stop, le retour sera de 50%.

Voici mes fichiers:

Shutterswitchwithneutral.json
{
  "Shutterswitchwithneutral": {
    "nameJeedom": "Shutter switch with neutral",
    "timeout": "60",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c6207662071f",
      "icone": "Shutterswitchwithneutral",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include5": "current_position_lift_percentage",
      "include9": "WindowsCoveringUp",
      "include10": "WindowsCoveringDown",
      "include10 2": "WindowsCoveringStop",
      "include20": "getcurrent_position_lift_percentage",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include27": "BindToZigateCurrent_Position_Lift_Percentage",
      "include29": "setReportCurrent_Position_Lift_Percentage"
    }
  }
}

Template/BindToZigateCurrent_Position_Lift_Percentage.json
{
  "BindToZigateCurrent_Position_Lift_Percentage": {
    "Comment": "Used to bind the device to zigate",
    "isVisible": 0,
    "name": "BindToZigateCurrent_Position_Lift_Percentage",
    "order": 28,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07cc26621916",
      "topic": "bindShort",
      "request": "targetExtendedAddress=#addrIEEE#&targetEndpoint=#EP#&ClusterId=0102&reportToAddress=#ZiGateIEEE#",
      "visibilityCategory": "Network"
    }
  }
}

Template/current_position_lift_percentage.json
{
  "0102-#EP#-0008": {
    "isVisible": 1,
    "name": "current_position_lift_percentage",
    "order": 4,
    "isHistorized": "1",
    "Type": "info",
    "subType": "numeric",
    "invertBinary": "0",
    "template": "",
    "unite": "%",
    "configuration": {
	"uniqId": "5c07c76621e16621e11",
      "minValue": "0",
      "maxValue": "100",
      "historizeRound": "0",
      "visibilityCategory": "All"
    }
  }
}

Template/getcurrent_position_lift_percentage.json 
{
  "getcurrent_position_lift_percentage": {
    "isVisible": 0,
    "name": "getcurrent_position_lift_percentage",
    "order": 13,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "invertBinary": "0",
    "template": "",
    "configuration": {
	"uniqId": "5c07c76623d65623d65",
      "topic": "ReadAttributeRequest",
      "request": "EP=#EP#&clusterId=0102&attributeId=0008",
      "visibilityCategory": "additionalCommand"
    }
  }
}

Template/present_value.json
{
  "000f-#EP#-0055": {
    "isVisible": 1,
    "name": "present_value",
    "order": 1,
    "isHistorized": "0",
    "Type": "info",
    "subType": "binary",
	"invertBinary": "0",
	"template": "badge",
    "configuration": {
	"uniqId": "5c07c76621e1667c76621e11",
      "visibilityCategory": "All"
    },
	"display": {
	  "repeatEventManagement": "always",
      "forceReturnLineAfter": "1"
    }
  }
} 

Template/setReportCurrent_Position_Lift_Percentage
{
  "setReportCurrent_Position_Lift_Percentage": {
    "isVisible": 0,
    "name": "setReportCurrent_Position_Lift_Percentage",
    "order": 30,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07ccc6624fbb",
      "topic": "setReport",
      "request": "targetEndpoint=#EP#&ClusterId=0102&AttributeId=0008&AttributeType=10",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Kaléo.

**Comment by KiwiHC16** [comment]
Génial.
Je viens de le mettre dans le master. Sera dispo dans la prochaine stable.
Je clos le sujet. Si besoin le rouvrir ou ouvrir un autre plus specifique.
