### ISSUE TITLE
Images pour version stable

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#1165]
Bonjour,
Vu que tu vas sortir une nouvelle stable, je viens de jeter un oeil aux images de la version Master, et je te propose une correction sur les nouvelles, sans fond blanc
[new.zip](https://github.com/KiwiHC16/Abeille/files/4740749/new.zip)
Merci pour tout
++

**Comment by KiwiHC16** [comment]
Ajouté au master. Super. Merci.
