### ISSUE TITLE
Xiaomi Capteur Luminosité: Batterie et Online information

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1166]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Brugal21** [comment]
Salut @KiwiHC16,

Petite relance sur la batterie de la sonde de luminosité, c'est le seul équipement sur pile que j'ai qui ne remonte pas sa valeur de batterie. J'ai presque 20 capteurs sur pile aqara (temp/hygro carré, fenêtre carré, bouton carré, inondation, incendie, vibration) et tous remontent l'état de leur batterie parfaitement toutes les heures. Étonnant que cette sonde soit récalcitrante. Le principal est là, la valeur de luminosité remonte bien toutes les 10min 😀

Je rajoute que cette sonde passe en repond NOK sur la page santé après quelques minutes suite à un reapparaige, mais pas en timeout. J'ai fait plusieurs apparaige à différents endroits de la maison, mais même en étant appairée en direct sur la zigate, son statut repond est NOK rapidement après l'apparaige.

RPI3B+ / Debian Buster à jour / Jeedom 4.1.20 / zigate USB FW3.1D / abeille stable du 09/03/21

**Comment by tcharp38** [comment]
Correction dans le master.
Détruire puis réinclure le capteur.

**Comment by tcharp38** [comment]
210423-BETA-1

**Comment by tcharp38** [comment]
Pas de soucis à constater de mon cote sur les dernieres versions.

A noter que ce capteur ne remonte que la valeur de la batterie et pas le pourcentage.
Je clos mais reouvrir si besoin.

**Comment by Brugal21** [comment]
Je confirme la remontée de la valeur de la batterie, uniquement en volt. Du coup le capteur n'apparait pas dans Jeedom, menu Analyse/Equipements.

**Comment by tcharp38** [comment]
Ajouter polling pour pourcentage batterie

**Comment by Brugal21** [comment]
Je dois faire quoi ? Mdr

**Comment by tcharp38** [comment]
:)
C'est pas pour toi mais un memo pour moi.

**Comment by Brugal21** [comment]
Ok bien noté.
Merci

**Comment by tcharp38** [comment]
En fait je crois que ce capteur ne remonte que la tension.
Il faut donc extrapoler pour obtenir un pourcentage qui lui est bien plus interessant contrairement au voltage qui n'est pas parlant.

**Comment by Brugal21** [comment]
Ok pas de soucis, j'ai fait ça de mon coté :

Un virtuel avec une commande info basée sur la commande volt de l'équipement et la formule suivante :

![image](https://user-images.githubusercontent.com/55110607/123321353-2c681880-d533-11eb-9dfc-6114c8b12558.png)

Et ensuite un design avec toutes mes piles.

**Comment by tcharp38** [comment]
[2021-06-29 13:28:23] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0001, SrcEP=01, DestEP=01, SrcAddrMode=02, SrcAddr=E7F9, DestAddrMode=02, DestAddr=0000
[2021-06-29 13:28:23]   FCF=18, SQN=42, cmd=0A/Report attributes
[2021-06-29 13:28:23]   msg=2000201F
[2021-06-29 13:28:23]   Ignored
[2021-06-29 13:28:23] Abeille1, Type=8102/Attribut report, SQN=42, Addr=E7F9, EP=01, ClustId=0001, AttrId=0020, AttrStatus=00, AttrDataType=20, AttrSize=0001
[2021-06-29 13:28:23]   BatteryVoltage=1F => 3.1V
[2021-06-29 13:28:23]   decodeDataType(): size=1, hexString=1F => hs=1F

[2021-06-29 13:28:23][DEBUG] : message(topic='Abeille1/E7F9/0001-01-0020', payload='31')

**Comment by tcharp38** [comment]
Beta 210708-BETA-1 a tester pour la remontée batterie.

Ce capteur ne renvoi que la tension. Du coup il y a une conversion vers %.

**Comment by tcharp38** [comment]
Je clos.
La derniere stable du jour devrait inclure une solution (calcul du pourcentage à partir de la tension reportée)
