### ISSUE TITLE
Interrupteur 3A SmartHome

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1172]
```
[2020-06-10 00:49:03][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=01, SrcAddr=9a06, EndPoint=0B, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=000D, DataByteList=LXN-1S27LX1.0
```

LXN-1S27LX1.0

**Comment by KiwiHC16** [comment]
Pourrais tu:
- mettre Abeille en mode debug
- redémarrer la daemon
- faire l inclusion et partager le log AbeilleParser ?

**Comment by Notrede** [comment]
Il y a longtemps que j'ai résolu le sujet par moi meme...
J'ai repris un modele pour un autre interrupteur et changé le nom. C'est passé sans pb...

**Comment by KiwiHC16** [comment]
Ok super. Peux tu partager ton fichier json ?

**Comment by Notrede** [comment]
Il a disparu… reste le répertoire mais il est vide ☹

Probablement la mise à jour ?

Le nom du device est : LXN-1S27LX1.0

**Comment by KiwiHC16** [comment]
Te souviens tu du modele que tu avais utilisé ?

**Comment by Notrede** [comment]
De mémoire (donc pas à 100%), le zigbeeOnOffLight.json
Il semble basique donc parfait pour ca :-)

**Comment by tcharp38** [comment]
Plus de vie depuis un bail.
A reouvrir si besoin
