### ISSUE TITLE
Découpage par device du fichier de configuration json.

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#118]
Proposition de réorganisation des fichiers de configs afin de faciliter les nouveaux ajouts.

config -> devices -> sensor_86sw1 - sensor_86sw1.json
                                                         - sensor_86sw1.png

Refaire les les fonctions de Tools:get.. pour tenir compte de cette réorg. J'ai commencé le code pour voir ce que cela donne.

**Comment by KiwiHC16** [comment]
Oui ca semble une bonne idée

**Comment by KiwiHC16** [comment]
Peux tu aligner les codes avant de faire les modif afin d'avoir un Pull Request qui fonctionne tout seul ;-)
Je suis entrain de regarder ton dernier pull request.

**Comment by edgd1er** [comment]
Ok, je vais voir comment faire. Merci pour l'intégration manuelle. Je suis en train de valider la conf par objet. si tu veux essayer, ce sera commité sur mon dépot dans la branche checkSum (le rename ne va pas jusqu'a github...). J'ai mis a jour la doc et forcer la création de tout les objets connus.

**Comment by KiwiHC16** [comment]
Je travaille sur plusieurs sujets en // alors je vais attendre que tu fasses un request pour tester.

**Comment by KiwiHC16** [comment]
Merged into master and tested so I close the issue.
