### ISSUE TITLE
Comprendre fonctionnement message 8035

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1180]
Pas un pb mais plutot pour la culture et eventuel support.
A quoi sert le message 8035 et à quelle commande fait-il suite ?
A priori il est lié aux informations stockées en "Non Volatile Mem" (mémoire permanente) de la Zigate donc en dehors d'un nouvel equipement, quelle autre info est mise-à-jour reguilierement ?

![image](https://user-images.githubusercontent.com/35221038/85146821-4b600a80-b24e-11ea-9546-df62e86b9b53.png)

![image](https://user-images.githubusercontent.com/35221038/85146896-629ef800-b24e-11ea-9b0b-9d2265246277.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Si mes souvenir sont bon c est lié à la possibilité de mettre des infos sur le plugin  et pas dans la memoire de la zigate afin de pouvoir reduire ce qui est en meoire zigate et ainsi augmenter le nombre d equipemetns. C est dans les trucs a faire mais pas encore eu le temps.

**Comment by KiwiHC16** [comment]
Couvert par "Investigate PDM server. " #147
