### ISSUE TITLE
log AbeilleCmd size (et les autres)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1181]
AbeilleCmd
```
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/core/class/config.class.php on line 247
PHP Notice:  Undefined index: log::level::Abeille in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 21
```

AbeilleParser
```
[2020-06-24 07:28:32][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=40, SrcAddr=c48d, EndPoint=01, ClusterID=0000, AttrID=ff01, AttrStatus=00, AttrDataType=42, AttrSize=001d, DataByteList=0121ef0B0328150421a84305218b00062401000000000A213d91641000
[2020-06-24 07:28:32][debug]   Champ proprietaire Xiaomi (Door Sensor)
[2020-06-24 07:28:32][debug]   DoorV2Voltage=3055, Pourcent=76, DoorV2Etat=00
PHP Warning:  Error while sending QUERY packet. PID=26283 in /var/www/html/core/class/DB.class.php on line 84
```

AbeilleSerial1
```
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/core/class/config.class.php on line 247
PHP Notice:  Undefined index: log::level::Abeille in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 21
```

**Comment by KiwiHC16** [comment]
log AbeilleCmd - 500M

Erase log AbeilleCmd restart demon et tout est en ordre.

**Comment by tcharp38** [comment]
@KiwiHC16 
Peux tu detailler le sujet ? En particulier j'ai l'impression que tu parles de la taille des logs generes.
Effectivement aujourd hui on crache sans arret dans le log sans limite de taille pour tout ce qui est sortie "interne Abeille", sans passer par la classe "log" de Jeedom.
Que souhaites tu ?

**Comment by KiwiHC16** [comment]
Passer par les log jeedom pour avoir du rolling et donc contrôler la taille des fichiers. 
En debug j ai eu des fichiers de plus de 250Mo.
L idée est de garder un log par process. Je ne sais pas si les librairies/classes jeedom permettent d avoir plus d un log par plugin.

**Comment by tcharp38** [comment]
J'ai l'impression que la classe log de Jeedom ne couvre pas cet aspect.
De + qu'entends tu par "rolling" ? Sauf erreur, Jeedom repart au debut du fichier quand il atteind le seuil. J'ai du mal à concevoir qu'on puisse tout decaler d'une ligne des qu'on arrive à la limite. Ca serait super consommateur CPU et disque.
T'en pense quoi ?

De mon côté j'ai fait une lib "AbeilleLog.php" pour sortir les logs comme on veut et les gerer comme on veut. J'avoue que je ne pige pas la classe log, trop compliquée et aucune doc.

**Comment by KiwiHC16** [comment]
Oui c est un peu le problème: pas de doc. 
Si on atteint un nombre de lignes alors on vide le fichier. 
Ou alors si on atteint un nombre de ligne on passe au fichier 2, et quand fichier 2 atteint un nombre de ligne on repasse au fichier 1: ça peut être une bonne idée pour ne pas se retrouver avec un fichier vide car on vient d atteindre le nombre Max par fichier. Dans certains syslog où voit des fichiers jusqu a 5. Je suppose que c est pour garder la taille de chaque fichier la plus petite possible.

**Comment by tcharp38** [comment]
Ok jusque la on est en ligne. Du coup je les solutions suivantes:

1. On fait comme ta premiere propale. Une fois le fichier au max, on vide et on repart de 0. Le pb de ca est qu'on perd l'historique.
2. On joue sur 2 fichiers. Une fois le max atteind on passe au 2nd. On revient au premier quand max atteind sur le 2nd. etc etc. J'avais pensé à cette solution mais comme c'est Jeedom qui gere l'affichage, il va montrer au user les log.1 log.2 de chaque démon. Hors dans le cas d'Abeille il y a deja du monde. Si c'était masqué de l utilisateur je serais partant.
3. Enfin ma derniere idée du moment.. on defini la taille max au double de ce qu'on veut afficher. Par ex 500lignes max, le fichier va jusqu'a 1000. Quand max atteint on n'efface (tronque) la premiere moite. De ce fait on a toujours un historique de 500lignes.

Une preference ?

**Comment by KiwiHC16** [comment]
4. On écrit dans le fichier de  toto.log. Donc visible dans jeedom.  A 500 lignes on ferme le fichier toto.log on le renomme en toto.log1 Ou toto.old. On crée toto.log et on écrit de nouveau dedans.

**Comment by tcharp38** [comment]
Ton point 4 est mon point 2. Du coup Jeedom va voir les 2 et donc afficher les 2... sauf peut etre si le fichier ne commence pas par "Abeille". L'autre defaut de cette solution si on arrive à masquer le 2nd fichier à Jeedom, c'est que l'utilisateur lambda ne pourra pas voir tout l'historique.

**Comment by KiwiHC16** [comment]
Autre solution et probablement la meilleure, on ecrit jusqu'à a x lignes et on seek to offset 0: https://www.php.net/manual/en/function.fseek.php
En gros on écrit x lignes et on repositionne la position d'ecriture sur le premier octet.
Dans le fichier on aura:
10:01:00 kjdfskdjfdmsfkdj
10:02:00 dlkjsdfd
10:03:00 dkjsd ds

Et apres avoir atteint le max:
10:04:00 je recommence au debut
10:02:00 dlkjsdfd
10:03:00 dkjsd ds

**Comment by tcharp38** [comment]
Tu te rends comptes que ton log va pas etre tres ... lisible comme ca ?
La transition sera tres bizarre puisque ta nouvelle ligne occupera surement + ou - de place.. donc il restera des bouts d'une vielle ligne. Sans tout "deplacer" (ce que je fait pas seek) ca va donner un truc comme

10:00 Ligne toto 1
10:01 Ligne toto2
10:03 Ligne tot3
on seek avec un nouveau message "10:04 Ligne to4"
10:04 Ligne to4o 1
10:01 Ligne toto2
10:03 Ligne tot3

L'autre souci que je vois est Jeedom. Lui ne va pas t'afficher la derniere ligne en cours car il n'en sait rien ou tu ecrit. Il va surement t'afficher la derniere ligne du fichier (qui alors n'est plus du tout le dernier message).

**Comment by KiwiHC16** [comment]
Le recouvrement de ligne ne me gene pas car il y a les dates en debut de ligne.
Par contre effectivement l affichage Jeedom ne fonctionnera pas (perso je ne l utilise pas).

On n'a pas la solution miracle alors. Ca vaudrait peut etre le coup de passer un peu de temps sur la class des log Jeedom pour l utiliser et la on serait dans la ligne du parti.

**Comment by tcharp38** [comment]
Je reviens sur le sujet apres qq avancées.

Côte Jeedom je ne vois rien qui permette de gerer des logs rotatifs. Leur lib de base se contente de tronquer le fichier quand il arrive à une certaine taille et on perd la trace precedente.
Leur systeme de log est compliqué car permet la sortie de trace en different formats et differentes cibles (fichier, remote server type syslogd.. etc).

Pour Abeille et à défaut d'avoir mieux par Jeedom lui meme je te propose les points suivants déja dispo et en test de mon cote:
- Une librairie AbeilleLog pour gerer les sorties
- Sorties dans les fichiers habituels AbeilleXXX (/var/www/hml/log)
- Si dépasse un max de lignes (j'ai mis 500), alors copie dans 'tmp' et log remis à 0

On a le meme comportement que via Jeedom, sauf qu'en plus une copie du log precedent est dispo dans le "tmp" d'Abeille (ex: "AbeilleParser-prev" ou "AbeilleSerialRead1-prev"

![image](https://user-images.githubusercontent.com/35221038/95985485-f069a900-0e24-11eb-9702-44ce5ee8ef5f.png)

Qu'en penses tu ?

**Comment by KiwiHC16** [comment]
Ca me parait une bonne solution.
Fait une branche specifique pour tester ? ou tu pousses dans le master ?

**Comment by tcharp38** [comment]
De mon cote je teste tout dans la "dev_tcharp38" de mon repo
https://github.com/tcharp38/Abeille.git

Mais si l'idée te plait je peux pousser progressivement ce support
Par ex
- AbeilleSerialRead
- AbeilleParser
- ... etc
Comme ca je limite les changements et tu peux voir au fur et à mesure

**Comment by KiwiHC16** [comment]
Ok support, un a un...

**Comment by tcharp38** [comment]
AbeilleSerialRead poussé avec la lib AbeilleLog.

**Comment by tcharp38** [comment]
Bon juste pour info je realise que malgré l'utilisation de notre propre lib pour la sortie de log, les fichiers sont tronqués en fonction de la config de Jeedom 
![image](https://user-images.githubusercontent.com/35221038/96609150-7ccf0c80-12fa-11eb-987d-d71766804099.png)

Ca gave.
Pas vu le code qui faisait cette surveillance en tache de fond. Qqch m'echappe.

**Comment by tcharp38** [comment]
J'ai compris !
Le log peut depasser la taille définie dans la config Jeedom mais des qu'on l'affiche... Jeedom le tronque.
Autrement dit si
- on configure 500 lignes dans Jeedom
- et qu'AbeilleLog a sa limite à 2000
- chaque fois qu'on va afficher le log via Jeedom on va perdre des données

Il faut donc que la config Jeedom soit egale ou superieure à celle de notre lib.

**Comment by tcharp38** [comment]
@KiwiHC16 
A l'occase donne moi ton retour sur la sortie des logs "SerialRead" & "Parser" via "AbeilleLog".
Merci

**Comment by KiwiHC16** [comment]
Pas de soucis vu de mon côté.
Peut etre un soucis quand j inclus le log est trop court dans AbeilleParser.

**Comment by tcharp38** [comment]
Trop court ?
Tu peux eclairer ?

**Comment by KiwiHC16** [comment]
Comme le processus d inclusion est tres verbeux, le log se rempli vite. 
Comme j ai fait des modifications de ce côté, je vais voir par la suite si j ai toujours ce soucis.

**Comment by tcharp38** [comment]
@KiwiHC16 tu as revu ton pb de log parser trop court ?

**Comment by KiwiHC16** [comment]
Non. Je clos cette issue. Et ouvrirai une nouvelle si besoin specique. Cool de ne plus avoir des log monstrueux ....
