### ISSUE TITLE
Monitorer ipcs pour voir si une pile devient folle.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1182]
Le plugin est Ok. Il ne detecte pas de soucis.

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages
0x00000336 1638404    www-data   666        16344        212  

Queue 822 en dec qui est serie to parser

tail AbeilleParser
```
[2020-06-29 11:00:29][debug] Type=8102/Attribut Report: Dest=Abeille4, SQN=0D, SrcAddr=4ae0, EndPoint=01, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0009, DataByteList=lumi.plug
[2020-06-29 11:00:33][debug] Type=8102/Attribut Report: Dest=Abeille2, SQN=b0, SrcAddr=b023, EndPoint=01, ClusterID=0201, AttrID=0008, AttrStatus=00, AttrDataType=20, AttrSize=0001, DataByteList=00
[2020-06-29 11:00:33][debug] Type=8102/Attribut Report: Dest=Abeille2, SQN=b1, SrcAddr=b023, EndPoint=01, ClusterID=0201, AttrID=4002, AttrStatus=00, AttrDataType=20, AttrSize=0001, DataByteList=00
```
Ca fait donc 24h que parser ne log plus.

ps -ef | grep AbeilleParser
```
www-data 14108     1  0 Jun26 ?        00:26:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleParser.php debug
```

Parser tourne toujours.

**Comment by KiwiHC16** [comment]
-rw-rw-r-- 1 www-data www-data 182M Jun 30 08:15 AbeilleCmd

Rien de visible dans les ps, top.

Je peux me connecter à la base avec adminer sans soucis.

**Comment by KiwiHC16** [comment]
```
kill 14108;  /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleParser.php debug
```

```
www-data  1816 21249  0 08:34 pts/3    00:00:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleParser.php debug
```

Kill de AbeilleParser et redemarrage de celui ci uniquement mais ipcs ne bouge pas:
```
------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages    
0x00000336 1638404    www-data   666        16344        212  
```

**Comment by tcharp38** [comment]
Salut Kiwi
Qu'appelles tu "ipcs" ? Tu parles des fifo msg utilsées avec msg_send/receive ?

Pour info, côté monitoring je bosse sur un moniteur permettant de suivre tous les messages vers un périph particulier (sortants et entrants). J'espere que ca aidera par ex pour debugguer des pbs de pertes de periph.

**Comment by KiwiHC16** [comment]
ipcs: sont des fonctions de base unix/linux: message entre process, memoire partagée, sémaphore. 
J utilise pour passer des messages entre le programmes php. Comme tu dis les msg_send/receive.
La j ai mon systeme planté car AbeilleParser ne lit pas les messages venant de la zigate donc tout est HS.
Je cherche pourquoi j'ai ca.

**Comment by KiwiHC16** [comment]
```
------ Semaphore Arrays --------
key        semid      owner      perms      nsems     
0x00000000 32768      www-data   600        1         
0x00000336 65537      www-data   666        3         
0x002fa327 98306      root       600        2   
```

```
ipcrm -s 32768
```
ok mais 
```
ipcrm -s 65537
ipcrm: permission denied for id (65537)
```

Arret Parser et redemarrage du parser uniquement, rien ne change sur les messages et semaphore n est pas recréé.

**Comment by KiwiHC16** [comment]
Si je fait juste une loop sans traitement des messages sur
```
 if (msg_receive( $queueKeySerieToParser, 0, $msg_type, $max_msg_size, $dataJson, false, MSG_IPC_NOWAIT))
```
ca loop mais pas de mesasge recu !!!

**Comment by KiwiHC16** [comment]
si je passe de $max_msg_size = 512; à $max_msg_size = 2048;
tout repart sans rien faire d'autre !!!
Et zut je n'ai pas attrapé le message qui posait probleme.

Bon je vais augmenter la taille et puis c est tout.

**Comment by KiwiHC16** [comment]
https://www.php.net/manual/en/function.msg-stat-queue.php

The maximum number of bytes allowed in one message queue. On Linux, this value may be read and modified via /proc/sys/kernel/msgmnb.

root@jeedompro:~# cat /proc/sys/kernel/msgmnb
16384

**Comment by KiwiHC16** [comment]
Monitoring de la taille de la queue:
   
                $a =  msg_stat_queue ($queueKeySerieToParser)["msg_qnum"];
                if ($a) echo $a."\n";

**Comment by KiwiHC16** [comment]
Log added dans deamon_info
