### ISSUE TITLE
Ajout d'une ampoule OSRAM e27 smart+ non detecté

### ISSUE THREAD

**Issue by Aguay-val** [KiwiHC16/Abeille#1184]
Bonjour,

Je viens d'ajouter une ampoule OSRAM comme présent dans l'issue. [https://github.com/KiwiHC16/Abeille/issues/568]( https://github.com/KiwiHC16/Abeille/issues/568)

Mais cependant lorsque ma ruche détecte mon abeille  aucune commande n'est créé, et il me met l'icone de "Default Unknown".

Je débute en zigbee et avec le plugin. J'ai cherché a récupérer des informations pour savoir si d'un point de vue "commande zigbee" les données étaient correctement récupéré et j'ai ça :

![image](https://user-images.githubusercontent.com/2204373/86961729-fd119d80-c161-11ea-9afa-ee036f0c846e.png)
Du coup je ne sais pas sur quoi se base le plugin pour créer le contrôleur dans jeedom mais j'ai l'impression qu'il ne récupère pas correctement l'info.

Ce que je peux dire c'est quand faisant le "identifier" j'ai bien mon ampoule qui clignotte donc je suis assuré d'avoir la bonne "abeille" de connectée.

Je me suis posé la question s'il y avait un moyen d'appliquer un "modèle" de donnée directement via le plugin et de créer les commandes à la volée mais je n'ai pas trouvé.

Merci d'avance !

**Comment by Aguay-val** [comment]
Hello ! Je reviens avec des bonnes nouvelles.

J'ai réussi à inclure mon Ampoule en créant un JSON qui correspond au nom découvert par la ruche.
En lisant la doc j'ai vu à un endroit le fait de recréer la ruche lorsqu'on ajoute/modifie un JSON.

Du coup j'ai recréé ma ruche, réimporté mon ampoule et je peux correctement faire un On/off/Toggle.

La question que j'ai maintenant c'est, comment je fais pour ajouter la fonctionnalité de "dimmering" qui est normalement gérée par mon Ampoule ? Any idea, suggestions, examples ?

> PS: Je ferais une PR pour mettre à disposition le JSON. 
> Il me faudra également de l'aide pour correctement configuré les paramètres du JSON :)

Aguay.

**Comment by Aguay-val** [comment]
Je viens de voir qu'il y avait un Template pour le Dimmering. Je l'ai utilisé et ça fonctionne parfaitement !

Du coup je vais faire la PR et une fois que ce sera validé on pourra fermer ce ticket :)

**Comment by KiwiHC16** [comment]
Peux tu partager le contenu du fichier JSON ? 
Sois tu fais un copié-collé ici et je fais le fichier et je le mets dans le master ou si tu maitrises GitHub alors fais un PR.

**Comment by Aguay-val** [comment]
Here we go : https://github.com/KiwiHC16/Abeille/pull/1194

:)

**Comment by KiwiHC16** [comment]
Super. C est dans la version de dev maintenant. ;-)
