### ISSUE TITLE
Ajout Switch Zemismart TS0043

### ISSUE THREAD

**Issue by Youss93** [KiwiHC16/Abeille#1185]
Bonjour,
J'ai essayé d'inclure un interrupteur zemismart TS0043 acheté sur Aliexpress mais abeille ne le reconnaît pas. 
Pourriez-vous m'aider s'il vous plaît ?
Je vous remercie d'avance. 

![Screenshot_2020-07-09-11-07-25-621_com alibaba aliexpresshd](https://user-images.githubusercontent.com/67928370/87020655-72b65180-c1d4-11ea-9236-764648374e21.jpg)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Cet inter n'est pas connu par Abeille.
Il faut lui faire un modele pour qu'Abeille puisse créé le créer et le piloter.
Cet inter est similaire à https://github.com/KiwiHC16/Abeille/issues/1092
Il faudrait certainement reutiliser le modele et l'adapter pour cet inter.
Peux tu mettre le plugin en debug, faire l inclusion et partager le log AbeilleParser.

**Comment by Youss93** [comment]
Bonjour, cet interrupteur sans fil et fonctionne avec des piles. Voici le log abeilleparser en mode inclusion.
Merci beaucoup pour ton aide.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KiwiHC16** [comment]
Je ne vois pas le log.

**Comment by Youss93** [comment]
>je te l'ai envoyé en pièce jointe par Outlook.

**Comment by KiwiHC16** [comment]
Invisible. Peux tu me mettre sur le site GitHub: https://github.com/KiwiHC16/Abeille/issues/1185

**Comment by Youss93** [comment]
________________________________

**Comment by Youss93** [comment]
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4924402/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
```
[2020-06-09 11:15:51][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=25, Status=00, ShortAddr=ba19, Length=18, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0051 (Smart Plug), BitField=00
[2020-06-09 11:15:51][debug]   InClusterCount=07
[2020-06-09 11:15:51][debug]   InCluster=0000 - General: Basic
[2020-06-09 11:15:51][debug]   InCluster=0003 - General: Identify
[2020-06-09 11:15:51][debug]   InCluster=0004 - General: Groups
[2020-06-09 11:15:51][debug]   InCluster=0005 - General: Scenes
[2020-06-09 11:15:51][debug]   InCluster=0006 - General: On/Off
[2020-06-09 11:15:51][debug]   InCluster=0702 - Smart Energy: Metering
[2020-06-09 11:15:51][debug]   InCluster=0B04 - 
[2020-06-09 11:15:51][debug]   OutClusterCount=01
[2020-06-09 11:15:51][debug]   OutCluster=0019 - General: OTA
```
(Forget as wrong log file)

**Comment by Youss93** [comment]
Désolé je me suis trompé de fichier

**Comment by Youss93** [comment]
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4924479/AbeilleParser.txt)

**Comment by Youss93** [comment]
Je crois que cette fois-ci c'est le bon fichier 😂

**Comment by KiwiHC16** [comment]
```
[2020-07-15 10:54:53][debug] Type=004d/Device announce: Dest=Abeille1, SrcAddr=646c, IEEE=ec1bbdfffe79e330, MACCapa=80, Rejoin=00
...
[2020-07-15 10:55:17][debug] Type=8045/Active Endpoints Response: Dest=Abeille1, SQN=95, Status=00, ShortAddr=646c, EndPointCount=03, EndPointList=; 01; 02; 03
...
[2020-07-15 10:55:18][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=b5, SrcAddr=646c, EndPoint=01, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006, DataByteList=TS0043
...
[2020-07-15 10:55:28][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=99, Status=00, ShortAddr=646c, Length=10, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0000 (On/Off Switch), BitField=00
[2020-07-15 10:55:28][debug]   InClusterCount=03
[2020-07-15 10:55:28][debug]   InCluster=0000 - General: Basic
[2020-07-15 10:55:28][debug]   InCluster=0001 - General: Power Config
[2020-07-15 10:55:28][debug]   InCluster=0006 - General: On/Off
[2020-07-15 10:55:28][debug]   OutClusterCount=01
[2020-07-15 10:55:28][debug]   OutCluster=0019 - General: OTA

```

**Comment by KiwiHC16** [comment]
```
cet interrupteur sans fil et fonctionne avec des piles
```

Peux tu me confirmer ce point ?

**Comment by Youss93** [comment]
Oui tout à fait il fonctionne avec des piles

**Comment by Youss93** [comment]
#Aliexpress € 14,80  40%OFF | Le commutateur sans fil de zemimart fonctionne avec le Hub de Tuya un autocollant de commutateurs tactiles de deux trois Gangs
https://a.aliexpress.com/_B0Q2nt

**Comment by KiwiHC16** [comment]
Et tu ne connectes pas les fils des ampoules (neutre et phase) ?

**Comment by Youss93** [comment]
Non, l'idée était de le faire fonctionner comme le bouton rond Xiaomi en déclenchant un événement dans jeedom et ainsi créer des scénarios...
Je ne sais pas si c'est faisable

**Comment by Youss93** [comment]
J'ai un autre interrupteur yagusmart TS0011 sans neutre qui lui fonctionne très bien pour contrôler les lumières de mon jardin

**Comment by KiwiHC16** [comment]
TS0011 est aussi sur pile ?

**Comment by Youss93** [comment]
Non le TS0011 un interrupteur mural brancher électriquement et sans fil neutre

**Comment by Youss93** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/commit/5f541a11220c24a3f604957afdeb29b579b57396

Voilà les infos que j'ai trouvé pour le TS0043

**Comment by KiwiHC16** [comment]
Peux tu recuperer le fichier https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TS0043
créer un repertoire TS0043 dans ton systeme et mettre le fichier dedans.
Ensuite faire une inclusion pour vérifier que l'object est bien créé dans Abeille (Supprimes l ancien s il existe).

**Comment by Youss93** [comment]
J'ai bien créer le répertoire TS0043 dans jeedom. Le seul problème c'est que je n'arrive pas à télécharger le modèle json que tu as fait. 
![Screenshot_2020-07-15-13-23-21-994_com android chrome](https://user-images.githubusercontent.com/67928370/87539993-2a4cd700-c69f-11ea-84bf-20aa1bf31ce9.jpg)

**Comment by KiwiHC16** [comment]
Depuis un tel ca risque de ne pas etre simple. Peux tu le faire depuis un ordinateur ?

**Comment by Youss93** [comment]
Oui effectivement pas facile. Je suis handicapé et là je ne suis pas sur mon fauteuil roulant. Je pourrais accéder à mon ordinateur dans l'après-midi et je te tiens au courant. 
Merci beaucoup en tout cas pour ton aide c'est très sympa 😋

**Comment by KiwiHC16** [comment]
Ok tiens moi au courant.

**Comment by Youss93** [comment]
Re j'ai effectué la procédure que tu m'as donné, lancé l'inclusion de l'inter. Ca a crée une abeille avec 3 commandes on et 3 commandes off. Par contre pas de commande etat pour me permettre de creer des scenarios dans jeedom.
Quelle est la marche à suivre?

**Comment by KiwiHC16** [comment]
Je pense que c'est une telecommande en fait donc tu ne peux pas avoir d'état. Je pense ca car c est sur piles.
Et en fait le modele prépare ne doit pas etre bon car je suis parti d un inter sur fils. Il aurait fallu que je parte d'une télécommande.
En fait j'ai un gros doute sur son fonctionnement.
Ou l as tu acheté ?
As tu la documentation ?

**Comment by Youss93** [comment]
Je l'ai acheté sur Aliexpress. Il se paramètre via l'application Tuya et il nécessite un hub Tuya zigbee. Pas de doc avec. 😕
![IMG_20200715_192726](https://user-images.githubusercontent.com/67928370/87576245-597c3c00-c6d1-11ea-893c-b8c02f2642a6.jpg)
![IMG_20200715_192653](https://user-images.githubusercontent.com/67928370/87576247-5aad6900-c6d1-11ea-82cc-7d828fcfc561.jpg)

**Comment by Youss93** [comment]
Il y a donc 3 boutons et trois fonctions par bouton. 1 click, double click et appui long. Ce qui fait 9 commandes possibles en théorie.

**Comment by Youss93** [comment]
Bonjour, j'ai retrouvé la doc du switch si ça peut t'aider. Merci
![IMG_20200716_131404](https://user-images.githubusercontent.com/67928370/87665324-081e8c00-c767-11ea-8c5d-a3e04306ae59.jpg)
![IMG_20200716_131623](https://user-images.githubusercontent.com/67928370/87665326-08b72280-c767-11ea-9aed-c69d5e0b0e9e.jpg)

**Comment by KiwiHC16** [comment]
Il faut que je sniff les messages zigbee qu il utilise.
Si tu as le lien aliexpress, j en commande un avec la cagnotte et dès reception je le mets sur la GW Tuya que j ai pour savoir ce qu'il dit.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Youss93** [comment]
Cool :)https://fr.aliexpress.com/item/4000460643839.html?spm=a2g0s.9042311.0.0.264c6c37Ay2mGU

**Comment by Youss93** [comment]
Merci pour ton aide

**Comment by KiwiHC16** [comment]
Commandé, d'ici quelques semaines,...

**Comment by KiwiHC16** [comment]
Based on the doc: controle scene et groupe. A suivre.... (comme une telecommande).....

**Comment by Youss93** [comment]
Cool.😁

**Comment by Youss93** [comment]
Je suis à la recherche d'un capteur de luminosité et je suis tombée sur un modèle Xiaomi. Pourrais-tu me dire s'il est compatible avec le plugin s'il te plaît ?
https://fr.aliexpress.com/item/4000476379615.html?src=google&src=google&albch=shopping&acnt=248-630-5778&isdl=y&slnk=&plac=&mtctp=&albbt=Gploogle_7_shopping&aff_atform=google&aff_short_key=UneMJZVf&gclsrc=aw.ds&&albagn=888888&&ds_e_adid=438856512718&ds_e_matchtype=&ds_e_device=c&ds_e_network=u&ds_e_product_group_id=743612850714&ds_e_product_id=fr4000476379615&ds_e_product_merchant_id=106473098&ds_e_product_country=FR&ds_e_product_language=fr&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&ds_dest_url=https://fr.aliexpress.com/item/Xiaomi-Mijia-Smart-Light-Sensor-Zigbee-3-0-Light-Detection-Intelligent-Linkage-Waterproof-Used-With-Smart/4000476379615.html?src=google&albcp=10191220514&albag=107473525128&gclid=CjwKCAjwmMX4BRAAEiwA-zM4JoyO0Efus_dY7KzrB4bJzO4-PZ1b9xZTNYlOhqYDRnmNrRV-6FAi9RoCkZMQAvD_BwE

**Comment by KiwiHC16** [comment]
Oui mais sera dispo dans la prochaine stable.

**Comment by KiwiHC16** [comment]
Nouvelles pas terrible. Semble qu on soit obligé de faire des changement dans le firmware de la zigate pour pouvoir l utiliser. Je continu les investigations.

**Comment by pipiche38** [comment]
@KiwiHC16 le firm31d est ouvert pour ca

Tous les messages non traités par la Zigate sont remontés via le message 0x8002 et du coup après tu peux les traiter

Dans l'autre sens, c'est le 0x0530 qui peut etre utilisé pour envoyé des commandes.

L'avantage, c'est qu'on ne charge plus la Zigate avec des clusters

**Comment by KiwiHC16** [comment]
Sauf que la je pense qu on a le cluster server sur la zigate du cluster 0x0006 qui repond et donc rien n'est passé sur le bus serie. Je vais faire un mail à Akila voir s'il est en ligne et si il peut enlever ce cluster qui ne sert pas en server.

**Comment by KiwiHC16** [comment]
https://www.zigbee2mqtt.io/devices/TS0043.html

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3220

**Comment by pipiche38** [comment]
> Sauf que la je pense qu on a le cluster server sur la zigate du cluster 0x0006 qui repond et donc rien n'est passé sur le bus serie. Je vais faire un mail à Akila voir s'il est en ligne et si il peut enlever ce cluster qui ne sert pas en server.

Si un device fait un read Attribute sur un cluster/attribut à la zigate (en 31c) la zigate repond : 0x86 non supporté
En 31d le message ira vers le niveau supérieur.
C'est typiquement ce que j'ai eu avec un scene controleur de Tuya qui n'envoie que des commandes

**Comment by KiwiHC16** [comment]
En passant la zigate en mode hybride ca fonctionne. Sera dispo dans la prochaine stable.
