### ISSUE TITLE
Ajouter le capteur Xiaomi detecteur de fuite

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#119]

**Comment by KiwiHC16** [comment]
![capture](https://user-images.githubusercontent.com/8549674/36565232-263f4614-1820-11e8-9de3-875a667fb891.PNG)

C'est un tres bon début. On trouve les informations de base comme Link Quality , Power Source -> Batterie, IEEE Addr et le timestamp.

Apres on trouve les champs 0000-0001, 0000-0005 et 0000-ff01.

Le champ 0000-0001 doit etre la version logicielle, as tu un bouton sur le côté ? Si oui peux tu faire un appui court et voir si l'info remonte ?

Le champ 0000-0005 doit etre le nom de l'équipement, as tu un bouton sur le côté ? Si oui peux tu faire un appui court et voir si l'info remonte ?
 
0000-ff01 est un champ propriétaire qu'il faut décoder, as tu un bouton sur le côté ? Si oui peux tu faire un appui court et voir si l'info remonte ?

Et si tu attends plusieurs heures est ce que des valeurs apparaissent ou d'autres lignes sont ajoutées ?

**Comment by wolfnco** [comment]
Après appuie sur le bouton du dessus (pas de bouton latéral, jusque un bouton invisible sur le dessus) :+1: 

![capture2](https://user-images.githubusercontent.com/36747565/36567467-cc8eee24-1826-11e8-8fed-2e0b1929e4e0.PNG)

**Comment by KiwiHC16** [comment]
Super on a son nom. C'est tip top. On va pouvoir commencer à faire un fichier de configuration.

Peux tu mettre en Debug le plugin Abeille.

M'envoyer le log AbeilleParser pendant que tu fais un appui sur le bouton du dessus ?

**Comment by wolfnco** [comment]
Il suffit de demander !

AbeilleParser 2018-02-22 23:23:32[DEBUG]-------------- 2018-02-22 23:23:32: protocolData size(78) message > 12 char
AbeilleParser 2018-02-22 23:23:32[DEBUG]Type: 8102 quality: 33
AbeilleParser 2018-02-22 23:23:32[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-02-22 23:23:32[DEBUG][2018-02-22 23:23:32]
AbeilleParser 2018-02-22 23:23:32[DEBUG]SQN: 10
AbeilleParser 2018-02-22 23:23:32[DEBUG]Src Addr : eced
AbeilleParser 2018-02-22 23:23:32[DEBUG]End Point : 01
AbeilleParser 2018-02-22 23:23:32[DEBUG]Cluster ID : 0000
AbeilleParser 2018-02-22 23:23:32[DEBUG]Attr ID : 0005
AbeilleParser 2018-02-22 23:23:32[DEBUG]Attr Status : 00
AbeilleParser 2018-02-22 23:23:32[DEBUG]Attr Data Type : 42
AbeilleParser 2018-02-22 23:23:32[DEBUG]Attr Size : 0015
AbeilleParser 2018-02-22 23:23:32[DEBUG]Data byte list : 6c756d692e73656e736f725f776c65616b2e617131
AbeilleParser 2018-02-22 23:23:32[DEBUG]Data byte: lumi.sensor_wleak.aq1
AbeilleParser 2018-02-22 23:23:32[DEBUG]mqttPublish with Qos: 0

Je me couche d'ici 5 minutes, donc s'il te faut autre chose, demande moi vite ! :)

**Comment by KiwiHC16** [comment]
Le mieux est que tu ailles profiter de ta nuit sinon nous allons aller nous coucher à pas d'heure. Je peux déjà commencer à faire des choses avec les infos du jour.
Bonne nuit....

**Comment by wolfnco** [comment]
Toi aussi tu as le droit de te reposer ;)
Bonne nuit !

**Comment by KiwiHC16** [comment]
Merci, je suis un peu comme les chouettes ...
Je viens de mettre dans le master, une premiere version de l'objet Xiaomi Inondation. Quand tu pourras, installe la verison master, essayes en mode automatique du plugin Abeille et apres avoir supprimé l'objet existant dans Jeedom, un appui court sur le capteur pour voir si cela crée l objet.

**Comment by wolfnco** [comment]
Je pars en week-end demain, donc je ne pourrai pas avancer avant mardi soir.
As tu la possibilité de pousser l'update sur la version stable du market jeedom ? J'aurais peut-être assez de temps pour tester ce soir si je peux lancer l'update en un click.

**Comment by KiwiHC16** [comment]
Si je pousse le master sur le beta ou stable, cela ne sera pas avant demain matin sur le market. Donc ca devra attendre ton retour.

**Comment by wolfnco** [comment]
Ca marche, bon week end alors !

**Comment by KiwiHC16** [comment]
Bon week end.

**Comment by wolfnco** [comment]
J'ai mis à jour Abeille, et en mode automatique, le capteur est bien reconnu.

J'ai fait quelques tests en plongeant le capteur dans un verre d'eau :

je plonge le capteur dans un verre d'eau :

AbeilleParser 2018-03-04 14:47:36[DEBUG]-------------- 2018-03-04 14:47:36: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:47:36[DEBUG]Type: 8401 quality: 5d

je retire et essuie le capteur :

AbeilleParser 2018-03-04 14:48:28[DEBUG]-------------- 2018-03-04 14:48:28: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:48:28[DEBUG]Type: 8401 quality: 63

Je replonge :

AbeilleParser 2018-03-04 14:49:15[DEBUG]-------------- 2018-03-04 14:49:15: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:49:15[DEBUG]Type: 8401 quality: 69

je retire et essuie le capteur :

AbeilleParser 2018-03-04 14:49:36[DEBUG]-------------- 2018-03-04 14:49:36: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:49:36[DEBUG]CRC is not as expected (0a) is 0A
AbeilleParser 2018-03-04 14:49:36[DEBUG]Type: 8401 quality: 48

Je replonge :

AbeilleParser 2018-03-04 14:50:00[DEBUG]-------------- 2018-03-04 14:50:00: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:50:00[DEBUG]Type: 8401 quality: 6c

Je retire et essuie le capteur :

AbeilleParser 2018-03-04 14:51:44[DEBUG]-------------- 2018-03-04 14:51:44: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:51:44[DEBUG]Type: 8401 quality: 6f

Je replonge :

AbeilleParser 2018-03-04 14:53:08[DEBUG]-------------- 2018-03-04 14:53:08: protocolData size(40) message > 12 char
AbeilleParser 2018-03-04 14:53:08[DEBUG]Type: 8102 quality: 4e

Je retire et essuie le capteur :

AbeilleParser 2018-03-04 14:54:20[DEBUG]-------------- 2018-03-04 14:54:20: protocolData size(38) message > 12 char
AbeilleParser 2018-03-04 14:54:20[DEBUG]Type: 8401 quality: 3f

Je suis perplexe : "en général", la valeur de l'attribut quality est plus élevée quand le capteur est immergé. Mais pas toujours...

**Comment by KiwiHC16** [comment]
Je viens de finaliser le code et de le pousser dans master.

Je clos le "issue".
