### ISSUE TITLE
AbeilleMonitor missing

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1190]
le master ne tourne pas car il manque AbeilleMonitor.php

**Comment by tcharp38** [comment]
Ha zut j'ai poussé un truc pas encore mature alors. Je regarde et pousse le correctif. 
Le monitor fonctionne mais pas encore assez testé

**Comment by KiwiHC16** [comment]
Regardes les deux cas que je viens d ouvrir. Je rebascul sur une vieille version pour mes tests.

**Comment by tcharp38** [comment]
Ca devrait etre corrigé.
Dis moi

**Comment by KiwiHC16** [comment]
le pR a un conflit, il n'accepte pas le merge ;-(

**Comment by KiwiHC16** [comment]
Ok tout semble fonctionner dans le master. Je clos.
