### ISSUE TITLE
Master : Modif dans system log , can t start Abeille

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1191]
```
PHP Fatal error:  Uncaught Error: Call to undefined function deamonlog() in /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php:72
Stack trace:
#0 {main}
  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php on line 72
```

**Comment by KiwiHC16** [comment]
deamonlog() n existe plus dans Tools.php

**Comment by tcharp38** [comment]
Ouah ouah .. toutes ces erreurs viennent de moi ?

**Comment by KiwiHC16** [comment]
Celle ci je crois que oui.

**Comment by tcharp38** [comment]
Oui oui je confirme. Je suis fautif.
J'annule le PR ?

**Comment by tcharp38** [comment]
Bon ca semble bon si je me mets sur ma branche "master_tcharp38". 
Donc dis moi si tu preferes que je l'annule ou pas.

**Comment by KiwiHC16** [comment]
J ai pris tous les PR dispo que j ai mis dans la master.
Il faut que je la teste. Peut etre ce week end.

**Comment by KiwiHC16** [comment]
Sur mon systeme de dev le master est fonctionel de nouveau. Je clos.
