### ISSUE TITLE
mettre une virgule entre date en texte in Parser log

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1198]
Avant
[2020-07-19 23:16:19][debug] Type=

Apres
[2020-07-19 23:16:19][debug],Type=

pour faciliter le processing csv

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Peux tu detailler ton idée ?
J'imagine que tu cherche à avoir un separateur "connu" et non pas des espaces mais du coup tu veux separer quoi ?
Par ex que cherches tu a extraire de la ligne suivante ?
[2020-07-20 11:58:28][debug] Abeille1 Type=8009/Network State Response: ShortAddr=0000, ExtAddr=00158d0001ed3365, PANId=2582, ExtPANId=d3798aeb0f4c1f67, Channel=11

**Comment by KiwiHC16** [comment]
L idée est d avoir un log csv.
Tu fais un import dans excel avec le separateur virgule et tu peux filtrer, faire des stats,...
Par exemple je ne veux que les messages 8009...
![Capture d’écran 2020-07-20 à 14 04 33](https://user-images.githubusercontent.com/8549674/87935737-f2280880-ca91-11ea-9810-ca99f3cc1844.png)
Ca permet d avoir un outil sympas quand je veux plus que le grep.

**Comment by tcharp38** [comment]
Ok c'est bien ma comprehension. Donc le separateur pour CSV devient le ','.
Du coup chaque debut de message comme
"Type=XXX/nom du message**:** yyy"
doit etre modifié en
"Type=XXX/nom du message**,** yyy"
Je garde ca en tete pour mes modifs

**Comment by KiwiHC16** [comment]
Voila le separateur est la virgule.

**Comment by tcharp38** [comment]
Update partielle poussée

**Comment by KiwiHC16** [comment]
Je viens de le mettre dans le master.

**Comment by tcharp38** [comment]
A cloturer du coup

**Comment by KiwiHC16** [comment]
Je viens de passer en master -> beta-dev et le log parser semble bien plus propre.
;-)
