### ISSUE TITLE
AbeilleSerialRead error in log.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1199]
```
PHP Warning:  fread() expects parameter 1 to be resource, bool given in /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php on line 95
```

**Comment by tcharp38** [comment]
Je vais pousser des modifs sur SerialRead si tu patientes.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok je ne touche pas alors.

**Comment by tcharp38** [comment]
A cloturer je pense.
