### ISSUE TITLE
Avoir l'affichage des objets en mode dev (avec tous les details) et en mode User (avec les details interessants uniquement).

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#120]

**Comment by KiwiHC16** [comment]
En mode dev mettre visible sur toutes les commandes, sinon prendre la valeur de visible dans le fichier JSON.

**Comment by KiwiHC16** [comment]
Implemented on 27/2/2018
To have all comment visible uncomment line in the code.

**Comment by lukebr91** [comment]
On est d'accord que le changement du réglage n'a d'effet que sur les équipements ajoutés par la suite et non les objets déjà créés ? 
(je me doute que pas simple à gérer vu que certains  equipements peuvent ajour été créés avec un json + ancien)

**Comment by KiwiHC16** [comment]
Exact: sur les nouveaux.
On pourrait faire pour tous mais j en'en vois pas l'intérêt.

**Comment by edgd1er** [comment]
je confirme et j'ajoute que sur un jeedom de dev, la suppression/creation du widget sera plus simple et plus sur. Dans le cas d'un jeedom de prod, le besoin me semble pas évident et il reste la possibllité de cocher l'option visible dans Jeedom.
