### ISSUE TITLE
Ajout sirène Evology ENKI

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1205]
Bonjour

J'ai fait l'acquisition d'une sirène Zigbee de marque Evology (Enki LM, Boulanger). Celle-ci se connecte au réseau et est détectée lors de l'inclusion.
Toutefois, il n'existe pas de modèle pour insérer les commandes.
Si je t'envoie les logs Abeille et AbeilleParser en mode debug, penses-tu pouvoir travailler sur le sujet ?
Exemple de ce que contient les logs en particulier Parser
```
[2020-07-22 20:43:21][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=5f, Status=00, ShortAddr=79dd, Length=14, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0403 (IAS Warning Device), BitField=00
[2020-07-22 20:43:21][debug]   InClusterCount=05
[2020-07-22 20:43:21][debug]   InCluster=0000 - General: Basic
[2020-07-22 20:43:21][debug]   InCluster=0001 - General: Power Config
[2020-07-22 20:43:21][debug]   InCluster=0009 - General: Alarms
[2020-07-22 20:43:21][debug]   InCluster=0500 - Security & Safety: IAS Zone
[2020-07-22 20:43:21][debug]   InCluster=0502 - Security & Safety: IAS WD
[2020-07-22 20:43:21][debug]   OutClusterCount=01
[2020-07-22 20:43:21][debug]   OutCluster=0019 - General: OTA
```
J'en ai acheté 2 pour la modique somme de 13€ / pièce. On peut envisager le prêt de l'une d'elle afin que tu puisses travailler dessus si tu le souhaites.

Merci à toi pour la taf réalisé

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
On doit pouvoir tenter un modele pour voir si cela fonctionne dans un premier temps.
Pour cela il faut le nom de la sirène.
Peux tu afficher la commande getName sur la ruche et faire un getName sur l adresse 79dd et le endpoint 01 ?
As tu un lien vers le produit pour avoir une photo et les specs ?

**Comment by mickadam29** [comment]
Salut
Pas de soucis pour ce que tu demandes 
J’ai le nom et firmware dans les logs
Je t’envoie ça ce soir
Merci

**Comment by mickadam29** [comment]
Voici la réponse 

 execute ->action<- function with options ->{"title":"79dd","message":"01","utid":"1595438440252"}<-
[2020-07-23 19:25:53][DEBUG] : topic: CmdAbeille1/Ruche/getName
[2020-07-23 19:25:53][DEBUG] : request: address=#title#&destinationEndPoint=#message#
[2020-07-23 19:25:53][DEBUG] : topic: CmdAbeille1/Ruche/getName request: address=79dd&destinationEndPoint=01
[2020-07-23 19:25:53][DEBUG] : (All) Msg sent: {"message":{"topic":"CmdAbeille1\/Ruche\/getName","payload":"address=79dd&destinationEndPoint=01"}}
[2020-07-23 19:25:53][DEBUG] : fct message Topic: ->Abeille1/79dd/0000-01-0005<- Value ->PSE03-v1.1.0<-
[2020-07-23 19:25:53][DEBUG] : Update ONLINE Status

Et le lien vers Boulanger. Tu auras le peu de notice

https://www.boulanger.com/ref/1109481

Adresse de la doc

https://www.boulanger.com/ecommerce/notices/8/3351842348278_n_0.pdf

**Comment by mickadam29** [comment]
Commande génériques créées :
get name                                topic 0000-01-0005                                  Résultat de la commande : PSE03-v1.1.0
sw                                           topic 0000-01-4000                                  Résultat de la commande : 1.1.0

ET une vue des commandes créées mais beaucoup ne remontent rien

![image](https://user-images.githubusercontent.com/36518012/88318624-485bac80-cd1b-11ea-976d-bb626c86d028.png)

**Comment by jiki974** [comment]
Ca ressemble fortement à ça https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/WarningDevice/WarningDevice.json tu peux essayer ?

**Comment by jiki974** [comment]
J'ai acheté la même sirène et elle fonctionne avec zigbee2mqtt  en utilisant le cluster ssIasWd 1282

**Comment by mickadam29** [comment]
Merci. Je regarde ça.

**Comment by mickadam29** [comment]
En retour, j'ai créé un fichier json au nom de l'alarme soit  /var/www/html/plugins/Abeille/core/config/devices/PSE03-v1.1.0/PSE03-v1.1.0.json avec le contenu du fichier donné en exemple. Je l'ai adapté pour que cela colle à peu prêt.

{
  "PSE03-v1.1.0": {
    "nameJeedom": "Alarm PSE03-v1.1.0",
    "timeout": "60",
    "Comment": "Draft",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c76626sdesdfsde88a",
      "icone": "HS2WD",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "ZCLVersion",
      "include5": "dateCode",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include28": "setReportEtat",
      "include28 2": "writeAttributeRequestIAS_WD_Flash",
      "include28 2 2": "writeAttributeRequestIAS_WD_Sound",
      "include28 2 2 2": "writeAttributeRequestIAS_WD_FlashSound"
    }
  }
}

Et si je comprends bien, il me faut les fichiers dans Template qui correspondent aux derniers include
Mais ils n'existent pas
Celui qui s'en rapproche c'est writeAttributeRequestIAS_WD.json

Mais les commandes ne sont pas créées

![image](https://user-images.githubusercontent.com/36518012/88980613-6483be80-d2c4-11ea-95ff-655752e68f29.png)


Je suis un un fatigué pour traiter tout cela maintenant, j'y regarderai à nouveau demain. Merci à vous

**Comment by KiwiHC16** [comment]
C est la bonne piste

**Comment by jiki974** [comment]
J'ai trouvé une documentation avec les clusters zigbee ici  : https://manualzz.com/doc/31262656/multi-sound-siren-pse03

**Comment by mickadam29** [comment]
Merci pour l’implication.
Il faut que je regarde le modèle créé hier dans device/..../pse03...Json et comment fonctionne les templates qui manquent pour créer les commandes dans l’objet.
Dans le fichier il y a de mémoire un UniqID. Est-ce une valeur aléatoire que je dois modifier en changeant un caractère par exemple ou cette valeur correspond elle à une valeur constructeur (à l’image des adresses MAC par exemple)

**Comment by KiwiHC16** [comment]
UniqID n est pas utilisé. Juste mettre une chaine aleatoire si jamais dans le future cela pouvait servir.

**Comment by KiwiHC16** [comment]
Les trois fichiers qu ils te manquent sont ici:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/Template
en fin de page.
Car tu as probablement la version stable sur ta machine et ils ne sont pas encore sur la version stable.
Le probleme est que tu ne vas pas avoir les commandes associées.
Si tu peux attendre qu on sorte unne version beta ou stable. Si tu connais gitthub prend la branche beta-dev.

**Comment by mickadam29** [comment]
Merci

**Comment by mickadam29** [comment]
Grâce à vos infos à vous 2, j'ai bien avancé. Je peux déclencher la sirène.
Récup du fichier JSON PSE03
Récup des 3 fichiers Template
Récup du fichier AbeilleCmd.php et adaptation de celui-ci

En reprenant les info du pdf, j'ai modifié  :

$direction ="00"
Et j'ai mis $warningmode ="04" aux trois. 

Suppression de l'objet dans Abeille et inclusion avec les modifs ci-dessus.

Le curseur durée fait le job pour SOUND.

Pas réussi à faire clignoter uniquement 

Je peux donc faire tous les tests pour aider à gérer les modes spécifiques (différents sons, flash, ...) . J'ai seulement besoin de savoir si je dois recréer l'objet après chaque changement de AbeilleCmd.php

**Comment by mickadam29** [comment]
j'ai remplacé l'icône

![image](https://user-images.githubusercontent.com/36518012/89087515-d4617a00-d394-11ea-847d-b7f30c3de8d5.png)

**Comment by mickadam29** [comment]
Salut
Je viens de faire la mise à jour Abeille. Version du 29/08 ?
J'ai ajouté une seconde sirène à l'issue.
J'ai obtenu ces messages d'erreur.

![image](https://user-images.githubusercontent.com/36518012/91641539-5b9e1e00-ea25-11ea-8696-b1fdaf04b893.png)

Quelque chose à faire ? Les sirènes fonctionnent en mode SOUND (pas flash). Pas grave en soi. Merci encore pour le taf

**Comment by KiwiHC16** [comment]
Je regardes demain.

**Comment by mickadam29** [comment]
Merci.
Mais il semble que ce ne soit pas lié à mes sirènes. Voici ce que j'ai dans mes logs

![image](https://user-images.githubusercontent.com/36518012/91653862-7794d480-eaa4-11ea-8224-1fd51269dd5c.png)

L'objet 58d3 est un double interrupteur Xiaomi sur pile.

[2020-08-29 17:04:56][DEBUG] : fct message Topic: ->Abeille1/58d3/0000-ff01<- Value ->$this->decoded as Volt-Temperature-Humidity<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: Objet existe mais pas la commande, je passe ->Abeille1/58d3/0000-ff01<- Value ->$this->decoded as Volt-Temperature-Humidity<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: ->Abeille1/58d3/Batterie-Volt<- Value ->3015<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: ->Abeille1/58d3/Batterie-Pourcent<- Value ->64<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: ->Abeille1/58d3/0402-01-0000<- Value ->2048<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: Objet existe mais pas la commande, je passe ->Abeille1/58d3/0402-01-0000<- Value ->2048<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: ->Abeille1/58d3/0405-01-0000<- Value ->2580<-
[2020-08-29 17:04:56][DEBUG] : fct message Topic: Objet existe mais pas la commande, je passe ->Abeille1/58d3/0405-01-0000<- Value ->2580<-

Je retrouve d'autres messages d'erreur avec $This. 
Qui sont tous des équipements sur pile Xiaomi (inter doubles ou capteurs de temp/hum carrés). Objet existe mais pas la commande


Et je découvre aussi cette erreur. Je pense qu'il faudra ouvrir plusieurs ISSUE

![image](https://user-images.githubusercontent.com/36518012/91653942-289b6f00-eaa5-11ea-85ce-8d686c7537d2.png)

C'est un capteur de température Xiaomi. Carré. Le pourcentage de la pile remonte qq chose qui n'a rien à voir.
lumi.sensor_ht en lieu et place d'une valeur numérique

Merci à toi
