### ISSUE TITLE
Error -> Info pour batterie

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1207]
https://community.jeedom.com/t/zigate-et-jeedom/16685/15

Passer 
[2020-07-29 22:21:54][error] Voltage a moins de 2.8V. Je retourne 0% mais il y a qq chose qui cloche.

en
[2020-07-29 22:21:54][info] Voltage a moins de 2.8V. Je retourne 0% mais il y a qq chose qui cloche.

**Comment by KiwiHC16** [comment]
Serait-il possible d’indiquer le nom de l’appareil dans le message ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Le nom de l appareil aparait dans les lignes juste avant dans le log.
Je garde en debug et j ai adapter le texte pour essayer de le rendre plus lisible/comprehensible.    

 if ( $voltage/1000 > 3.135 ) {
                $this->deamonlog( 'debug', 'Voltage remonte par le device a plus de 3.135V. Je retourne 100%.' );
                return 100;
            }
            if ( $voltage/1000 < 2.8 ) {
                $this->deamonlog( 'debug', 'Voltage remonte par le device a moins de 2.8V. Je retourne 0%.' );
                return 0;

**Comment by tcharp38** [comment]
Salut @KiwiHC16 
Je peux comprendre que si la valeur remontée est supérieure à la tension batterie ca pue, mais pourquoi cette limite basse de 2.8 ?
