### ISSUE TITLE
Valeur Batterie dans Dashboard diff de dans analyse equipements.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1210]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
https://community.jeedom.com/t/anomalie-valeurs-batterie-equipement-ts0201-dans-analyse-equipement-batterie/34136

**Comment by djsyl** [comment]
TS0201
https://fr.aliexpress.com/item/4000645020326.html?spm=a2g0s.9042311.0.0.66956c37wRh77G

**Comment by KiwiHC16** [comment]
Dans status il faut mettre la valeur en % sans mettre le %.
Le probleme vient du non alignement de "Batterie-Volt", "Batterie-Pourcent", "0001-01-0021".
Je fais une correction dans le master.

**Comment by KiwiHC16** [comment]
Correction dans master.
Sera dispo dans une prochaine version.
Je clos.
