### ISSUE TITLE
Retour direct sur la config de l'équipement

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1211]
Bonjour,
Je ne sais pas si cela a déjà été demandé. Lorsque nous sommes sur un équipement sur le dashboard et qu'on clique sur son nom on se retrouve dans la configuration du plugin abeille. Serait-il possible et intéressant (pour moi, oui) de se retrouver directement sur la config de l'équipement ?
Merci

**Comment by KiwiHC16** [comment]
Peux tu partager des captures d écran car je ne suis pas sure de comprendre le besoin.

**Comment by Kenderv** [comment]
Bonjour, 
Je suis sur le dashboard : https://i.goopics.net/2Ewyr.jpg.
Je clique sur l'équipement et je me retrouve ici : https://i.goopics.net/oqElD.jpg alors que je souhaiterai me retrouver ici : https://i.goopics.net/8bn7b.jpg
J'espère que mes liens vont bien fonctionner.
Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Tres surprenant car perso cela fonctionne comme tu le souhaites.
Ce n'est pas (a ma connaissance) le plugin qui gere cela mais le coeur jeedom.
As tu le meme comportement sur les autres plugins ?
Sur quel version de Jeedom es tu ?

**Comment by Kenderv** [comment]
Non, je n'ai pas ce problème avec les autres plugins. Voici ma version de Jeedom : https://i.goopics.net/KPO5Y.jpg

**Comment by KiwiHC16** [comment]
Moi je suis en :
![Capture d’écran 2020-08-05 à 11 17 40](https://user-images.githubusercontent.com/8549674/89395195-49bea900-d70d-11ea-91fa-b7772bfa1928.png)

**Comment by KiwiHC16** [comment]
La je ne vois pas car le plugin ne defini rien sur ce sujet. Soit il y a un chengement entre 4.0.54 et 4.1 de jeedom, soit autre chose mais quoi ?
Peux tu poster le sujet sur le forum jeedom pour voir ce que disent les autres utilisateurs ?

**Comment by Kenderv** [comment]
OK , je fais ça en début d'après-midi.

**Comment by KiwiHC16** [comment]
https://community.jeedom.com/t/abeille-mauvaise-redirection/34424

**Comment by Kenderv** [comment]
Bonjour,
Aucun retour sur le forum Jeedom à ce propos https://community.jeedom.com/t/abeille-mauvaise-redirection/34424 .
Et de ton côté ?

**Comment by KiwiHC16** [comment]
Rien non plus. 
Par contre comment fais tu pour être en 4.1 car sur mon système je n ai de proposé que des 4.0.xx ?

**Comment by Kenderv** [comment]
Je ne me souviens pas de la façon dont j'ai procédé, mais je crois seulement en modifiant ce paramètre 
![Capture](https://user-images.githubusercontent.com/52486183/90226303-1b2e8580-de13-11ea-9a16-182592a3c0c1.JPG)

**Comment by KiwiHC16** [comment]
Intéressant il faut que je regardes.

**Comment by Kenderv** [comment]
Bonjour,
As-tu pu voir le pourquoi de cette anomalie ?
Merci et bon courage

**Comment by KiwiHC16** [comment]
Aucune info a ce stade. 

Si tu fais un clic droit sur le titre de la pile quel lien as tu ?
Ici un exemple de ce que je recuperes:
http://jeedom/index.php?v=d&p=Abeille&m=Abeille&id=2315

As tu quelque chose de similaire ?

**Comment by Kenderv** [comment]
Bonjour,
Voilà ce que je récupère : https://monNomDeDomaine/index.php?v=d&p=dashboard&object_id=12.
Est-ce que tu as pu essayer de passer en Jeedom 4.1 . Sur mon autre site je n'ai pas le même problème bien qu'en Jeedom 4.1.5 mais je suis sous zigate donc ça ne veut rien dire.

**Comment by KiwiHC16** [comment]
Si tu vas sur la page :
https://doc.jeedom.com/fr_FR/presentation/index

la 4.1 est indiquée alfa alors je ne vais pas la tester tout de suite.

![Capture d’écran 2020-08-25 à 23 00 42](https://user-images.githubusercontent.com/8549674/91227696-3e1c3c00-e727-11ea-8d38-410f07560042.png)


Pour moi le soucis vient de jeedom, je ne peux pas vraiment faire quelque chose côté plugin sauf si le coeur jeedom demande un modification plugin que je ne connais pas.

**Comment by KiwiHC16** [comment]
As tu touché à cette partie ?
https://doc.jeedom.com/fr_FR/core/4.1/widgets

**Comment by Kenderv** [comment]
Bonjour, 
Je ne sais pas ce que tu entends par `As tu touché à cette partie ?` mais oui j'ai créé des widgets avec le nouvel Onglet Widget.
Tu penses que cela a un lien ?

**Comment by Kenderv** [comment]
En ce qui concerne Jeedom 4.1 je comprends ta réticence. J'ai été un peu trop curieux et renseignement pris auprès de la team Jeedom,  il n'est pas possible de revenir en arrière. Il faudra donc attendre qu'elle soit officielle avant de voir ce qu'il advient de ce problème.

**Comment by KiwiHC16** [comment]
Je clos, on verra quand la 4.1 sera dispo. J'ai encore 80 sujets ...
