### ISSUE TITLE
http.error

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1216]
jeedom dans docker sur rpi4
abeille beta-test du 5/8/2020

sh: 1: gpio: not found
sh: 1: gpio: not found
sh: 1: gpio: not found
sh: 1: gpio: not found
sh: 1: gpio: not found

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Tu fais quoi pour avoir ces erreurs ? Et elles apparaissent ou ?

**Comment by KiwiHC16** [comment]
fichier /var/www/html/log/http.error
Jeedom est dans un container docker et n a pas acces au gpio. Mais en meme temps je n'ai pas de PiZigate.

Aucune idée de la raison de ces logs.

**Comment by tcharp38** [comment]
Pour ma culture, docker te sert à quoi ?

**Comment by KiwiHC16** [comment]
J ai plusieurs RPIs et cela me facile la vie en:
- permettant des backup complet du systeme a distance
- duplication des systemes pour tests
- surtout je n'ai pas besoin d'intervenir physiquement sur le RPI
- ...

http://kiwihc16.free.fr/Docker.html

**Comment by KiwiHC16** [comment]
```sh: 1: gpio: not found```
Sur mon premier systeme: Pas de PiZigate/Jeeduino. GPIO ne doit pas etre installé.
aussi sur mon deuxième systeme: Pas de PiZigate/Jeeduino. GPIO ne doit pas etre installé.
Pas sur mon 3ieme systeme: PiZigate donc GPIO doit etre installé.
Pas sur mon 4ieme systeme: Jeeduino, donc GPIO doit etre installé.

Peut etre pas lié à Abeille mais a autre chose...

Ressemble a Abeille qui cherche GPIO par defaut meme si pas necessaire.
Je me demande si ce n'est la mise en place de pin GPIO par defaut au demarrage d'Abeille.

**Comment by tcharp38** [comment]
A l'occasion je regarderai si ca peut m'apporter qqch.
Je me dit que 'gpio' est une commande utilisée par Abeille, comme par hasard et meme si tu n'as pas de PiZigate, souviens toi qu'on a ajouté un setup des GPIO au démarrage des démons. J'avais mis un commentaire à l'epoque "A revoir quand on sait identifier qu'il y a une PiZigate sur le systeme". Bref ce setup est fait dans tous les cas. L'erreur doit venir de la dans ton cas.
Quoi qu'il en soit, ca sous entend qu'on sait pas utiliser la pizigate sous Docker.

**Comment by KiwiHC16** [comment]
Utiliser la PiZigate sous docker doit etre possible mais demande une config specifique. Par le passé, je mettais en place les commandes GPIO sur le host et donnais acces au /dev/tty au container. Mais ca suppose des manip sur le host manuelles.

**Comment by KiwiHC16** [comment]
Je n ai plus ce message. Je clos.

**Comment by KiwiHC16** [comment]
Dans Abeille demain_start()
```
 /* Configuring GPIO for PiZigate case.
            TODO: Should be done only if PiZigate is present to avoid any unexpected side effect. */
            /* PiZigate reminder (using 'WiringPi'):
            - port 0 = RESET
            - port 2 = FLASH
            - Production mode: FLASH=1, RESET=0 then 1 */
            exec("gpio mode 0 out; gpio mode 2 out; gpio write 2 1; gpio write 0 0; sleep 0.2; gpio write 0 1 &");
```

Mettre cette execution sous condition d une pizigate. Ajouter le if() qui va bien.

**Comment by tcharp38** [comment]
tu peux me l'assigner si tu veux

**Comment by KiwiHC16** [comment]
Ok je te l assigne comme ca je sais que tu es dessus et on evite de changer le code au meme endroit et faire des conflits.

**Comment by tcharp38** [comment]
C est meme fixé je pense.
Tu me dira si tu vois un souci.

**Comment by tcharp38** [comment]
Je clos car je considére résolu. A réouvrir si besoin.
