### ISSUE TITLE
Module Gelopto GL-C-008  >> [ERROR] : getJSonConfigFilebyDevices: filename not found: 

### ISSUE THREAD

**Issue by sebgsx01** [KiwiHC16/Abeille#1219]
Hello,

J'ai installé un contrôleur RGBW de marque Gelopto gl-c-008 zeegbe.

Version Jeedom | 3.3.53 |  
Version PHP | 7.0.33-0+deb9u8 |  
Version OS | Linux raspseb 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux [9.13] |  
Version database | 10.1.45-MariaDB-0+deb9u1
Abeille: Version2020-07-16 01:00:06 Version Jeedom3.1.7

L'inclusion se fait correctement mais je n'ai aucune commande de dispo.

J'ai le message suivant dans les log:
[2020-08-06 16:25:53][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/GL-C-007/GL-C-007.json will send back default template.

Si besoin d'information complémentaire, n'hésites pas à me le faire savoir, j'ai cherché des log mais je ne touve pas grand chose...

Merci beaucoup.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Est ce celui ci : https://www.banggood.com/GLEDOPTO-GL-C-008-ZIG_BEE-ZLL-RGBCCT-Smart-APP-LED-Strip-Controller-Work-With-Home-Kit-Philip-Hub-p-1471007.html?cur_warehouse=CN

**Comment by KiwiHC16** [comment]
Cela est du au fait qu il n est pas connu d'Abeille.
Si tu confirmes que c est celui ci alors on peut faire un modele pour qu il soit reconnu.

**Comment by sebgsx01** [comment]
Hello,  

je te confirme que c'est bien ce modèle. :+1: 

> Est ce celui ci: [https://www.banggood.com/GLEDOPTO-GL-C-008-ZIG_BEE-ZLL-RGBCCT-Smart-APP-LED-Strip-Controller-Work-With-Home-Kit-Philip-Hub -p-1471007.html? cur_warehouse = CN](https://www.banggood.com/GLEDOPTO-GL-C-008-ZIG_BEE-ZLL-RGBCCT-Smart-APP-LED-Strip-Controller-Work-With-Home-Kit-Philip-Hub-p-1471007.html?cur_warehouse=CN)

Merci beaucoup.

**Comment by KiwiHC16** [comment]
Ok donc il faut lui faire son modele.
Pourrais tu : 
- mettre le plugin en debug
- vider le log AbeilleParser
- supprimer l ampoule dans jeedom
- faire une inclusion de l ampoule
et partager le log AbeilleParser.

**Comment by sebgsx01** [comment]
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/5052972/AbeilleParser.zip)

Salut KiwiHC16, tu devrais trouver en pièce jointe le fichier AbeilleParaser Zippé, il y a peut-être un moyen plus simple de partager le log depuis jeedom... 

Si besoin n'hésites pas.

Merci

**Comment by KiwiHC16** [comment]
```
[2020-08-10 21:29:55][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=f4, SrcAddr=add4, EndPoint=0B, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0008, DataByteList=GL-C-007
```

```
[2020-08-10 21:29:55][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=66, Status=00, ShortAddr=add4, Length=16, EndPoint=0B, Profile=c05e (ZLL Application Profile), DeviceId=0210 (Extended color light), BitField=02
[2020-08-10 21:29:55][debug]   InClusterCount=07
[2020-08-10 21:29:55][debug]   InCluster=0000 - General: Basic
[2020-08-10 21:29:55][debug]   InCluster=0003 - General: Identify
[2020-08-10 21:29:55][debug]   InCluster=0004 - General: Groups
[2020-08-10 21:29:55][debug]   InCluster=0005 - General: Scenes
[2020-08-10 21:29:55][debug]   InCluster=0006 - General: On/Off
[2020-08-10 21:29:55][debug]   InCluster=0008 - General: Level Control
[2020-08-10 21:29:55][debug]   InCluster=0300 - Lighting: Color Control
[2020-08-10 21:29:55][debug]   OutClusterCount=00
```

Reste a faire le modele. Des que ja i du temps.

**Comment by sebgsx01** [comment]
Top.

Je te remercie!

**Comment by KiwiHC16** [comment]
Recuperes ce modele:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/GL-C-007

Mets sur ton systeme et ca devrait fonctionner.

**Comment by KiwiHC16** [comment]
Pas de retour, je clos. Si tu passes par la rouvre le sujet.

**Comment by sebgsx01** [comment]
Salut KiwiHC16,

Je prend enfin le temps de réintégrer le module.
Il est à présent bien reconnu par Jeedom, mais il y a un soucis de fonctionnement. Je ne sais pas si c'est le module ou le plugin qui présente un défaut.

note: Le module peut fonctionner avec plusieurs type de led, RGB/ RGB+W etc etc.

Actuellement j'utilise une RDB+W, la bande de LED Blanche et de led RGB.
Lorsque j'active ON ou OFF  >> suel les LED RGB s'allument et s'éteignent; en revanche les led blanches restent en permanance allumées à fond et elles éclairent tellement fort (LED Blanche) qu'après 8h d'éclairage, 1/3 d'entre elles ont grillées....

Côté fonctionnement des RGB, tout fonctionne parfaitement et rien de grillé. Je n'ai pas réussi à activer la modulation de couleur (je n'ai pas top cherché).

Si tu as besoin de qqch pour faire un diag, fais moi le savoir.

A+

Seb
