### ISSUE TITLE
Equipement bizarre dans le niveau des batteries

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1220]
Bonsoir,
Dans Analyse --> Equipements j'a un équipement qui me fait ce retour 
![Capture](https://user-images.githubusercontent.com/52486183/89716870-fa98a280-d9b0-11ea-9bc0-a8f7cb15b966.JPG)
alors que dans la config du même équipement le niveau de batterie est correct 
![Capture1](https://user-images.githubusercontent.com/52486183/89716885-1c922500-d9b1-11ea-8be5-b675ecb4a671.JPG)
et sur le dashboard 
![Capture2](https://user-images.githubusercontent.com/52486183/89717194-49940700-d9b4-11ea-9231-82764fec7e5f.JPG)

Une petite idée ?
Merci et bonne soirée

**Comment by Kenderv** [comment]
Ce matin j'ai 2 équipements dans le même cas :
![Capture](https://user-images.githubusercontent.com/52486183/89726640-e9857b00-da1c-11ea-8fc5-07cc3658522f.JPG)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ca doit être un bug, la commande "batterie Volt" est bonne mais la commande "Batterie %" doit contenir le nom de l équipement en lieux et place de la batterie %

Pouvez vous partager (capture écran) la definition de la commande Batterie Pourcent/% ?

**Comment by Kenderv** [comment]
Bonjour,
Voici la config des commandes Batterie et Batterie Pourcent.
![Capture1](https://user-images.githubusercontent.com/52486183/89986382-bf31f880-dc7c-11ea-9970-79e922cee82d.JPG)
![Capture](https://user-images.githubusercontent.com/52486183/89986394-c5c07000-dc7c-11ea-806e-59e1dfc01dd1.JPG)
Curieusement les valeurs semblent correctes et pourtant j'ai toujours cela dans Equipements
![Capture](https://user-images.githubusercontent.com/52486183/89986574-06b88480-dc7d-11ea-8035-1ad6d483d950.JPG)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-08-13 à 10 43 49](https://user-images.githubusercontent.com/8549674/90113593-e1497a80-dd51-11ea-887b-12110d5f5973.png)

Peux tu aussi partager une capture d'ecran des commandes comme ci dessus ?

**Comment by Kenderv** [comment]
Voilà 
![Capture](https://user-images.githubusercontent.com/52486183/90118025-f7f2d000-dd57-11ea-92b3-57c163bf8f47.JPG)
Ce matin j'ai de nouveau 2 équipements dans cet état, celui ci-dessus et celui ci-dessous
![Capture](https://user-images.githubusercontent.com/52486183/90118251-43a57980-dd58-11ea-96eb-0c0011655c0a.JPG)
![Capture](https://user-images.githubusercontent.com/52486183/90118412-79e2f900-dd58-11ea-9038-88d85dfb26c0.JPG)
Tous mes capteurs de T° ont les mêmes commandes

**Comment by Kenderv** [comment]
Bonjour,
Pour info, une piste pourrait-être le niveau du pourcentage de la batterie ou du voltage renvoyé.  Peut-être en dessous de 2.8v
Par ailleurs, j'ai cru voir que pour les détecteurs d'ouverture Xiaomi il était indiqué une CR2032 comme type de pile alors que ce sont des CR1632. 
Bon courage et merci des tes réponses

**Comment by Kenderv** [comment]
Dans le même genre de problème avec les batteries, et avant que j'en change, j'avais un log dans le style de celui ci-dessous qui me signalait une erreur pour cause de niveau de batterie < à 2.8V. J'ai remplacé par une nouvelle batterie que j'ai testée à 3.3V et voici le nouveau log 
![Capture](https://user-images.githubusercontent.com/52486183/90861351-e4fd8280-e38b-11ea-81a4-925eb24ad79c.JPG)
sans qu'on ne sache de quel équipement il s'agit. Les piles bouton CR2032 sont très souvent testées à 3.3V. Peut-être faudrait-il remonter le niveau d'alerte ?

**Comment by KiwiHC16** [comment]
En fait l equipement en question est indiqué à la ligne precedente dans le log. Je ne vais pas faire de modification car trop compliqué alors qu il suffit de regarder la ligne precedente.

**Comment by KiwiHC16** [comment]
La reference de la batterie est definie dans le modele. Je viens de le faire sera dans les prochaines versions.

**Comment by KiwiHC16** [comment]
Pour les 3.3V, je modifie le texte pour ne pas créer de question utilisateur. En fait je l ai deja fait.

**Comment by KiwiHC16** [comment]
J'ai le meme soucis sur un equipement de mon systeme de prod donc je vais pourvoir investiguer:
![Capture d’écran 2020-08-25 à 15 24 45](https://user-images.githubusercontent.com/8549674/91179666-1d33f680-e6e7-11ea-8eaf-f9feb0b469cb.png)

Ce qui est interessant c'est que toi tu as un capteur Temperature, un capteur Door et moi ici c est un radiateur et a chaque fois c'est un message lumi.sensor_ht%.

**Comment by KiwiHC16** [comment]
`/html/log$ grep sensor_h *`

ne donne rien sur mon systeme.

si tu fais un 
`grep sensor_h *`
dans le repertoire /var/www/html/log
qu est ce que cela donne ?

**Comment by Kenderv** [comment]
Cela ne donne rien non plus, pas de sensor_h dans les logs.
Par contre pour ta réponse https://github.com/KiwiHC16/Abeille/issues/1220#issuecomment-679976549 ci-dessus, je n'ai aucune indication du nom du module dans mes logs. De quel log parles-tu ?

**Comment by KiwiHC16** [comment]
Dans le log AbeilleParser, il y a un ligne avec l adresse courte de l equipement et immédiatement apres tu dois avoir l erreur sur le voltage.

**Comment by Kenderv** [comment]
Je te confirme que je na'ai pas cette ligne. Ci-joint le log de la journée d'hier 
[AbeilleParser (2).txt](https://github.com/KiwiHC16/Abeille/files/5127939/AbeilleParser.2.txt)

**Comment by KiwiHC16** [comment]
Je comprends ta question maintenant car je vois que tu log en mode error et pas en mode debug donc tu ne vois pas toutes les lignes.
Dans la version stable de ce jour, le message est en mode debug pour avoir toutes les lignes ensembles.

**Comment by KiwiHC16** [comment]
Maintenant j en ai deux mais je n ai pas le message dans les logs ;-(

![Capture d’écran 2020-08-26 à 11 14 11](https://user-images.githubusercontent.com/8549674/91285254-46a75d80-e78d-11ea-84be-31947eca8a72.png)

**Comment by Kenderv** [comment]
As-tu vérifié qu'il ne soit pas en dessous ou au dessus des limites de tes tests. Si j'ai bien compris tu as une limite basse autour de 2.8v et haute autour de 3 (ou 3.3 ) pour des piles bouton de nominal 3V et j'ai l'impression que nous récupérons ce message si les batteries ont des valeurs au-delà. Quelles sont les limites pour des piles AAA de  V ?

**Comment by KiwiHC16** [comment]
As tu un capteur de temperature aqara de premiere generation, les capteurs ronds, dans ton reseau ?

**Comment by KiwiHC16** [comment]
La courbe de decharge d'une pile en fonction de le tension est complexe et depend de plein de facteur (type de pile, temperature,...). Comme tu dis j'ai linearisé cette courbe etre 3.1V et 2.8V. Et les valeurs en dehors je les mets soit a 100% soit à 0%. Apres on peut s'amuser à faire des trucs complexe mais ca n'en vaut vraiment pas le coup car connaitre le % en fonction de le tension est quasi impossible. C est juste pour avoir un ordre d'idée.

**Comment by Kenderv** [comment]
https://github.com/KiwiHC16/Abeille/issues/1220#issuecomment-680767981 Non

**Comment by Kenderv** [comment]
<j'ai linearisé cette courbe etre 3.1V et 2.8V>Et pour les piles AAA 1.5

**Comment by Kenderv** [comment]
Je viens de passer les logs en mode debug

**Comment by KiwiHC16** [comment]
Je ne connais pas de capteur en 1.5V.
Il y a des 2 fois 1.5V, ce qui donne 3V.
Il faudrait peut etre faire un analyse plus precise de ce sujet mais il y a plen d autres sujets avant celui ci.

**Comment by KiwiHC16** [comment]
Le probleme vient probablement de https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1086

**Comment by KiwiHC16** [comment]
J'ai fait une modif dans le code pour essayer de limiter l'occurance du probleme meme si je ne comprends d ou il vient. Je vais monitorer mon systeme pour voir si cela se reproduit.

**Comment by Kenderv** [comment]
`Je ne connais pas de capteur en 1.5V.` J'ai des capteurs de T° Oregon THN132 avec piles au Lithium 1.5V pour mes congélateurs. Ils tiennent mieux le coup que les Xiaomi qui déconnent un peu si T°< -20°. Malheureusement il ne donnent pas la tension de la batterie mais seulement le % de charge. Si batterie neuve = 100 (%). Je retraduis en V par cette formule : 1.5-(0.4*(100-#[T° Frig. Cong.][Congel 2 cuisine][Batterie]#)/100) ou 0,4 est le delta que je me suis fixé entre batterie pleine et batterie vide. Qu'en penses-tu ?

**Comment by KiwiHC16** [comment]
Oregon THN132
C est du RFXCom ? Ce n est pas du Zigbee ? Tu confirmes ?

**Comment by Kenderv** [comment]
Oui

**Comment by KiwiHC16** [comment]
Suite a mes modif du code le sujet "Equipement bizarre dans le niveau des batteries" n est pas revenu sur mon systeme.
Je clos, si besoin rouvrir.
