### ISSUE TITLE
Hierarchie des répertoires et nettoyage progressif

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1222]
@KiwiHC16 
J'ouvre ce point pour essayer de clarifier & nettoyer progressivement la structure du plugin au niveau repertoires.
Corrige moi si je me trompe mais ce qui est imposé par Jeedom est
- core: Tout le code pour le fonctionnement interne du plugin
--  ajax: Code repondant aux requetes Ajax
-- class: Ne devrait contenir que des classes mais aujourd hui démons et librairies principales
-- php: On n'utilise pas aujourd hui mais c'est la qu'on devrait avoir les libs internes d'Abeille (hors classes).
-- config: la config des devices
-- i18n: Traductions
- plugin_info: De quoi informer jeedom des caracteristiques du plugin, et l'installer ou le configurer
- desktop
-- css/js/modal/php ... tout ce qui concerne l'affichage en mode "bureau"
- mobile: idem "desktop" mais pour le mobile
- docs: doc au format markdown. On n'utilise pas

On a en + 
- images: a priori les icones des devices supportés
- Network
- resources
- Wifi_Module
- Zigate_Module

Et je ne descends meme pas dans la hierarchie. Il y en a de partout.
Bref c etait juste pour ouvrir la discussion. Si jamais tu pensais améliorer tout ca et comment, je prends.
J'ai qq idées bien sur mais je ne veux pas chambouler ton organisation. Et dans tous les cas il faut etre clair avant de progressivement faire du "rangement" à ce niveau.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
C est toujours tentant mais ca peut amener enormement de boulot et je ne suis pas sure du benefice.
'quand on range trop on ne retrouve pas ses affaires'
On crée de nouveau bugs...

C est un peut le bazarre car c est le fruit de dev en meme temps que la découverte de Jeedom, zigbee,...

Et il y a plein d astuce que j'ai comprises tres longtemps apres le debut et il doit y en avoir d autre. Par exemple le repertoire class, devrait contenir des class, donc des objets. Or ces memes class sont appelées en directe sans passer par des instance d'objets pour avoir acces au fonction en direct... etc...

Perso je prefere passer du temps sur de nouvelles fonctionalités, il y a 80+ issues ouvertes ... et de quand necessaire en meme temps je nettoie.

**Comment by tcharp38** [comment]
Je ne comptais pas non plus "passer du temps" la dessus mais si jamais qqch de nouveau est créé autant savoir ou le mettre.
Mais ca marche on laisse ca de coté.

**Comment by KiwiHC16** [comment]
Si on crée alors on peut essayer de se coller au plus possible des reco jeedom.

**Comment by KiwiHC16** [comment]
Ok je clos. Cette issue sera toujours dispo plus la doc.
