### ISSUE TITLE
Sur changement du nombre de zigate faire un refresh de la page.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1225]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Tu as vu quel souci ?

**Comment by KiwiHC16** [comment]
Sur la version stable du 16 juillet 2020, plugin avec une zigate définie. On passe à 10 et sauvegarde, on ne voit que la premiere. On refresh la page et on les voient toutes.

**Comment by tcharp38** [comment]
Ok donc c'etait sans mes modifs je crois.
A revoir sur la beta. Pour moi le systeme est completement different, géré en javascript.

**Comment by tcharp38** [comment]
Ce souci doit être clos. A réouvrir si besoin.
