### ISSUE TITLE
PiZigate Reset HW refusé.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1226]
![Capture d’écran 2020-08-16 à 10 00 03](https://user-images.githubusercontent.com/8549674/90329715-73968c00-dfa7-11ea-8804-76ef9fb4f295.png)
![Capture d’écran 2020-08-16 à 10 00 20](https://user-images.githubusercontent.com/8549674/90329717-75604f80-dfa7-11ea-9742-fbbaa18e3c6b.png)
![Capture d’écran 2020-08-16 à 10 00 30](https://user-images.githubusercontent.com/8549674/90329721-785b4000-dfa7-11ea-8f65-158d98eceb9e.png)

**Comment by KiwiHC16** [comment]
Apres reset de jeedom, je problemen n existe plus.

**Comment by tcharp38** [comment]
Je vois bien comment on reproduit ca.
Il suffit de laisser la page de config ouverte pendant un moment.
La session se ferme mais rien ne le montre
Du coup les actions suivantes sont "non autorisées"
