### ISSUE TITLE
Migration de la doc vers GitHub/enhancement

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1227]

**Comment by tcharp38** [comment]
Le format actuel ne supporte pas l affichage d images n'est ce pas ?

**Comment by KiwiHC16** [comment]
La doc actuelle est basée sur un truc github qui ne laisse pas la main a l utilisateur et surtout ce que je souhaite avoir est une fonction "rechercher".

**Comment by KiwiHC16** [comment]
En fait je pensais que la doc etait sous un serveur perso mais en fait elle est dans https://github.com/KiwiHC16/AbeilleDocSphinx.git

Il faut avoir sphynx sur sa machine pour compiler la doc.

Modifier les fichiers dans le repertoire Source.

Ensuite je la mets sur le serveur:
http://kiwihc16.free.fr

**Comment by tcharp38** [comment]
Tu peux me l'assigner.

**Comment by tcharp38** [comment]
Une mise à jour du status:
La doc sera accessible via GitHub dans la prochaine stable mais les liens Jeedom vers doc ne seront mis à jour que pour la stable suivante.

**Comment by KiwiHC16** [comment]
Fait.
