### ISSUE TITLE
PiZigate port update / force page reload

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1229]
Si tu changes le port de la zigate alors le port de test de la pizigate ne se met pas a jour. Il faut forcer le refresh de la page.

![Capture d’écran 2020-08-26 à 09 32 48](https://user-images.githubusercontent.com/8549674/91276087-5325b900-e781-11ea-9c4b-78e59170682a.png)

![Capture d’écran 2020-08-26 à 08 58 34](https://user-images.githubusercontent.com/8549674/91276085-51f48c00-e781-11ea-8ef4-d0fb5d4d3ab8.png)

**Comment by KiwiHC16** [comment]
En general je me refuse a dupliquer l information car cela pose toujours des soucis.
Est ce qu il  ne faudrait pas regrouper les tests PiZigate avec la conf du port. En faisant apparaitre les tests des que la personne selectionne le type comme PiZigate par exemple.
Il faudrait ajouter une commentaire pour chaque bouton avec ce qu'il fait exactement. Car meme moi je ne sais quel bouton utiliser en fonction de ce que je veux faire.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Tout à fait en ligne avec toi.
J'ai conservé la partie PiZigate en l'etat le temps que les changements soient officiels et qu'on ait qq retours.
Quand tu dis "je ne sais quel bouton utiliser" tu as un cas d exemple ?

Je vais aussi regarder le pb que tu mentionnes.

**Comment by KiwiHC16** [comment]
Par exemple:
- Tester: dire que cela va prendre la main donc arret demon...
- Reset: dire que on va mettre GPIO a zero pour couper l alimentation et la remettre
- Activer: qu est ce qu on fait quand on appui sur ce bouton ? (Je crois avoir compris qu il refait la conf pour le port et donc demande un reboot...) En gros comme je ne sais pas je ne l utilise pas.

En gros c est faire une sorte de petite doc sur les actions faites quand on clic sur chaque bouton.

**Comment by tcharp38** [comment]
Ok pour "tester" et ""reset. Je dois pouvoir améliorer ca.
Pour "activer" c'est ton ancien code/nom. Je n'ai pas revu cette partie n etant pas satisfait des améliorations que j'ai en tete.
Mais il est clair que "activer" ne me semble pas le bon terme. Ca serait plutot "liberer" (qui ne me plait pas non plus. Faut encore + simple/clair pour les utilisateurs). Bref... a reflechir mais ca reste dans la liste des points d'amélioration.

**Comment by tcharp38** [comment]
Concernant le souci que tu as soulevé, je ne reproduis pas de pb mais je crois comprendre maintenant que tu changes le port et va utiliser le bouton "tester" de la partie "PiZigate" c'est ca ?
Si c'est le cas alors ok. Les 2 parties sont independantes et ma prochaine livraison va simplifier ca.

**Comment by KiwiHC16** [comment]
Oui c est ca.

**Comment by tcharp38** [comment]
La derniere livraison doit cloturer ce souci.
Tu confirmes ?

**Comment by KiwiHC16** [comment]
Je confirme. Je clos donc.
