### ISSUE TITLE
Support prise Blitzwolf BW-SHP13

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1231]
https://community.jeedom.com/t/support-prise-blitzwolf-bw-shp13/35181/3

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-08-27 à 08 49 20](https://user-images.githubusercontent.com/8549674/91405400-3604ef00-e842-11ea-8db4-584b67b36b7e.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
J'en ai commandé une car pouvoir de coupure de 16A est interessant.

**Comment by KiwiHC16** [comment]
```
[2020-08-26 15:13:59][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=81, SrcAddr=5f90, EndPoint=01, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006, DataByteList=TS0121
```

EndPoint=01
TS0121

**Comment by KiwiHC16** [comment]
Un bon début.
Pourrais tu refaire l inclusion et partager de nouveau AbeilleParser mais avec plus de log car il me manque des infos.

**Comment by machpro64** [comment]
voilà un nouveau log. j'ai changé paramétrage pour passer de 500 à 5000 lignes
j'ai aussi vu que tu avais mis en ligne une nouvelle version du plugin et je l'ai installée.
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5135319/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Oui il y a un souci de retour d etat sur cette version. Une nouvelle sera dispo demain pour corriger.

**Comment by KiwiHC16** [comment]
Aie beaucoup d erreur dans ce log. Est ce un log avec la nouvelle version ou la precedente ?
```
PHP Notice:  Uninitialized string offset: 27137 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 829
PHP Notice:  Uninitialized string offset: 27136 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 830
```

**Comment by KiwiHC16** [comment]
Pas plus d infos que la fois precedente.
On va faire avec une autre solution. Peux tu afficher la commande : SimpleDescriptorRequest
![Capture d’écran 2020-08-27 à 11 19 16](https://user-images.githubusercontent.com/8549674/91422214-26dc6c00-e857-11ea-9e0d-27a513382648.png)
Au lieu de 394f tu mets 5f90 et tu partages la reponse qu'on obtiens dans AbeilleParser.

**Comment by machpro64** [comment]
OK - ci-joint la réponse dans le log du parser
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5135920/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
```
[2020-08-27 12:44:00][debug] Abeille1, Type=8043/Simple descriptor response, SQN=2d, Status=00, ShortAddr=5f90, Length=18, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0051 (Smart Plug), BitField=01
[2020-08-27 12:44:00][debug]   InClusterCount=06
[2020-08-27 12:44:00][debug]   InCluster=0000 - General: Basic
[2020-08-27 12:44:00][debug]   InCluster=0004 - General: Groups
[2020-08-27 12:44:00][debug]   InCluster=0005 - General: Scenes
[2020-08-27 12:44:00][debug]   InCluster=0006 - General: On/Off
[2020-08-27 12:44:00][debug]   InCluster=0702 - Smart Energy: Metering
PHP Notice:  Undefined index: 0x0b04 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 1564
[2020-08-27 12:44:00][debug]   InCluster=0b04 - 
[2020-08-27 12:44:00][debug]   OutClusterCount=02
[2020-08-27 12:44:00][debug]   OutCluster=0019 - General: OTA
PHP Notice:  Undefined index: 0x000a in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 1568
[2020-08-27 12:44:00][debug]   OutCluster=000a - 
```

**Comment by KiwiHC16** [comment]
Tres interessant.
Je vais mettre en pause ce sujet et je travaillerai dessus quand j aurai la prise dans les mains. Cela ira plus vite.

**Comment by machpro64** [comment]
OK - merci pour ton aide!

**Comment by Jorael57** [comment]
Bonjour  KiwiHC16, As tu reçu ta prise ? Sais-tu quand tu pourras mettre à jour le plugin pour son support ? ( La mienne attends sagement :))

**Comment by KiwiHC16** [comment]
Elle vient de passer de mon stock a mon bureau ;-)

**Comment by KiwiHC16** [comment]
En fait je viens de la brancher et hop elle est dans mon systeme de dev.
En fait elle est identique 
![Capture d’écran 2020-09-29 à 15 47 27](https://user-images.githubusercontent.com/8549674/94566816-16128200-026b-11eb-8300-b69d23635494.png)

Sera dans la prochaine stable.

**Comment by KiwiHC16** [comment]
On/Off fonctionne.
Retour etat fonctionne si on utilise bouton sur la prise.

**Comment by KiwiHC16** [comment]
Il faut encore travailler ce point:
InCluster=0702 - Smart Energy: Metering

**Comment by Jorael57** [comment]
C'est le point qui m'interessait le plus dans cette prise :)

**Comment by KiwiHC16** [comment]
0x0702 -> Smart Energy - Metering
0x0b04 -> Home Automation - Electricity Measurement 0x0b04

**Comment by KiwiHC16** [comment]
https://www.zigbee2mqtt.io/devices/TS0121_plug.html

Visiblement on a Volts, W, A

measurement_poll_interval: This device does not support reporting electric measurements so it is polled instead. The default poll interval is 10 seconds.


https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2677

**Comment by KiwiHC16** [comment]
Y a du code a faire

**Comment by KiwiHC16** [comment]
Bon je parviens a lire V, A et W mais je ne parviens pas à les faire rapporter les changements.
Suite au prochain épisode.

**Comment by Jorael57** [comment]
Est ce que tu sais si il garde les infos en mèmoire ? à la manière des plugwise Circle ?
ou est ce qu'il faut interroger la prise toutes les minutes par exemple si on veut une courbe de charge ?

**Comment by KiwiHC16** [comment]
Il ne garde rien en memoire.
Je ne connais pas plugwise circle donc je ne peut commenter.
Actuellement jeedom peut interroger l equipement et garder un historique.
Ce que je cherche mainteant a faire est de configurer la prise pour qu'elle envoit les infos toute seule sans avoir Jeedom qui demande les infos tout le temps.

**Comment by Jorael57** [comment]
Les plugwise circles sont des prises comme la Blitzwolf mais elles sont beaucoup plus vieilles en zigbee (surement en version 1) propriétaires elles coutaient cheres 25 à 30 euros de mémoire, Leur principale avantage c'est qu'elles gardent en mémoire la consommation jusqu'à ce qu'elle soit sur que les valeurs sont remontés dans l'outils de lecture. donc si parfois la connexion zigbee est interrompue quand elles se reconnectent au réseau tu n'as rien perdu des mesures.

**Comment by KiwiHC16** [comment]
Modele mis a jour avec Puissance, Volt et Ampere.
Reste a comprendre l unité du compteur.

**Comment by KiwiHC16** [comment]
15h33 -> 29
Load 50W - 220mA
15h46 -> 30
15h55 -> 31
16h15 -> 32
16h27->33

Soit 33-29=4 en une heure.

Ca serait des 4 (x10) Wh.

**Comment by KiwiHC16** [comment]
Modele mis a jour.
Tout sera dispo dans la prochaine stable.
