### ISSUE TITLE
Tous mes capteurs en timeout

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1232]
Bonjour, depuis la mise à jour de ce matin, tous mes capteurs sont en timeout. J'ai relancé les dépendances et le démon, tout est ok  sauf que tout est en timeout? Que faire ?
Merci
![image](https://user-images.githubusercontent.com/52486183/91462975-1c3bca00-e88b-11ea-88c9-4111a75b99ab.png)

**Comment by Marc--** [comment]
Salut, je pense avoir une piste. As tu ce genre de message ?

`La zigate Abeille1 detectee ne semble pas etre la bonne (IEEE qui remonte: 00158d0000c0e00e alors que j ai en memoire: 00158d0000c0e00E). Je la bloque pour ne pas créer de soucis.`
![2020-08-27 19_42_56-Abeille - Jeedom](https://user-images.githubusercontent.com/9568739/91477026-13a0bf00-e89e-11ea-9dc9-0ab2a35b9fac.png)


Je viens de le remarquer suite à la MaJ, et mes capteurs tombent petit à petit. Je pense qu'il s'agit juste d'un problème de casse (majuscules / minuscules), mais je n'ai pas mis le nez dans le code encore (et ce n'est pas ma spécialité du tout).

@KiwiHC16 as tu moyen de confirmer ?


Edit: le test de la zigate (dans la configuration du plugin) est bien OK. Mais chez moi il déclenche le message d'erreur ci dessus.
![2020-08-27 19_47_46-Abeille - Jeedom](https://user-images.githubusercontent.com/9568739/91477247-61b5c280-e89e-11ea-9bbe-ab910da466da.png)

Perso j'ai rollback a ma sauvegarde pre-update en attendant analyse.

**Comment by KiwiHC16** [comment]
Oui comme indiqué dans https://community.jeedom.com/t/abeille-et-sensibilite-a-la-casse-adresse-abeille-et-ieee/35771/3 il y a un soucis de casse maintenant. Je ne comprends pas pourquoi. Du coup j ai commencé à changer le code pour gérer ca mais ca va demander du temps de test car c est delicat comme modification.

le message ```La zigate Abeille1 detectee ne semble pas etre la bonne (...``` est le resultat d un test pour gerer les situation multi zigate. Dans ce cas on peut modifier ce test et cela doit fonctionner.

Dans le fichier AbeilleParser remplacer
```
if ( config::byKey( str_replace('Abeille', 'AbeilleIEEE', $dest), 'Abeille', 'none', 1 ) == $ExtendedAddress ) {
```

par 
```
if ( strtoupper(config::byKey( str_replace('Abeille', 'AbeilleIEEE', $dest), 'Abeille', 'none', 1 )) == strtoupper($ExtendedAddress) ) {
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Kenderv** [comment]
@Marc-- @KiwiHC16 -- Salut, je n'ai pas eu ce message mais en revanche j'ai eu celui-ci : il doit y avoir un problème avec le démon que je viens de relancer 3 fois de suite. Je suis allé voir la config, le démon était KO, je l'ai relancé manuellement, de nouveau KO, relance une troisième fois et il est resté OK. Ce matin il est toujours OK mais tous mes équipements sont toujours en timeout. J’espère qu'il  ne va pas falloir tous les ré inclure, avec tous les scénarios à corriger !!!!

Edit 08:51 Je viens de remarquer dans la config que le port série de la Zigate est devenu 
![image](https://user-images.githubusercontent.com/52486183/91530695-d5da7f80-e90b-11ea-8c46-da6630a2fe3a.png)
Je ne comprends pas pas pourquoi. Aurai-je fais une mauvaise manip en allant relancer le démon ??? Je corrige et vous teins au courant.

**Comment by Marc--** [comment]
Salut Kenderv, je vois dans le port série "RFXCOM". Ne serait-ce pas la l'erreur ? Abeille gère la Zigate, pas le RFXCOM (ou alors j'ai loupé un épisode).

Si tu fais "tester", tu dois avoir le firmware dans le carré vert à côté.

**Comment by KiwiHC16** [comment]
Lors des mises a jour il est possible que la configuration des ports soit perdue.
Pourquoi je ne sais pas, il faut que j investigue.
Est ce que si tu mets le bon port tout rentre dans l ordre ?

**Comment by Marc--** [comment]
Mon port n'a pas sauté. Donc comme tu dis comportement aléatoire.

A mon avis s'il remet le bon port, il ça se retrouver dans la situation ou
le IEEE est en conflit.

Ce serait intéressant de voir le résultat.

**Comment by KiwiHC16** [comment]
Avec la version de demain normalement le probleme de casse ne doit plus apparaitre.

**Comment by Kenderv** [comment]
@KiwiHC16  @Marc-- Bonjour vous deux. Comme précisé dans mon dernier message j'ai rechangé le port pour le repasser à ça 
![image](https://user-images.githubusercontent.com/52486183/91564999-cb3add00-e941-11ea-9a1d-43c0ecb60942.png) et forcément ça marche beaucoup mieux. Petit à petit mes capteurs reviennent à la vie mais c'est long. Il m'en reste 6 en timeout, on verra demain matin. Ils étaient tous ok avant. L'essentiel @KiwiHC16 c'est que tu aies mis le doigt (j'espère que c'est le pouce) sur l'anomalie et que tu aies pu la corriger. Merci pour tous les efforts fournis pour maintenir un telle usine à gaz (pas péjoratif). 
Bon après-midi à vous.

**Comment by Kenderv** [comment]
Petite question subsidiaire : pourquoi tous les capteurs n'ont pas d'IEEE et qu'est-ce que l'IEEE ?
Merci

**Comment by KiwiHC16** [comment]
l IEEE est un numero de serie unique pour chauqe equipement. Abeille l utilise pour identifier un equipement. Il n'est pas necessaire pour les fonctions de base. Abeille cherche a le recuperer des que possible mais des fois ne parvient pas a le recuperer. Une facon de recuperer les IEEE est de faire un Refresh LQI.

**Comment by Kenderv** [comment]
OK Merci, et bonne nouvelle plus que 2 en timeout

**Comment by Kenderv** [comment]
All is perfect 
![image](https://user-images.githubusercontent.com/52486183/91580830-f4616a80-e94d-11ea-8c14-2b5278b1f8d0.png)

**Comment by KiwiHC16** [comment]
C est beau le vert ;-)

**Comment by Marc--** [comment]
Ouaip c'est beau. M'en parles pas j'ai ajouté un second inter de volet roulant ce soir et tout mon réseau c'est effondré 😱 Donc je vois rouge.  J'ai décidément beaucoup à apprendre sur le protocole Zigbee! 

En tout cas content que ça remonte Kenderv, et j'espère KiwiHC16 que tu as pu identifier ce soucis sans y passer trop de temps. Merci pour ton travail sur le plugin !

**Comment by KiwiHC16** [comment]
Du nouveau sur ce sujet ?

**Comment by KiwiHC16** [comment]
Pas de nouveau depuis mon dernier post. Je clos. Rouvrir si besoin.
