### ISSUE TITLE
Ajout compatibilité d'un module Switch Tuya 

### ISSUE THREAD

**Issue by Flobul** [KiwiHC16/Abeille#1233]
Suite à l'achat d'un module Switch Tuya Zigbee 3.0 sur ali ([Aliexpress](https://fr.aliexpress.com/item/4001253094829.html?src=google&albch=shopping&acnt=248-630-5778&isdl=y&slnk=&plac=&mtctp=&albbt=Gploogle_7_shopping&aff_atform=google&aff_short_key=UneMJZVf&gclsrc=aw.ds&&albagn=888888&&ds_e_adid=438856512718&ds_e_matchtype=&ds_e_device=c&ds_e_network=u&ds_e_product_group_id=743612850714&ds_e_product_id=fr4001253094829&ds_e_product_merchant_id=107894055&ds_e_product_country=FR&ds_e_product_language=fr&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&ds_dest_url=https://fr.aliexpress.com/item/4001253094829.html?&albcp=10191220514&albag=107473525128&gclid=EAIaIQobChMI9IzgtPK76wIVWvhRCh1XzwxkEAQYASABEgIgN_D_BwE)) , j'ai tenté de l'intégrer au plugin (dernière beta installée). 

J'ai copié le json de "511.201 illuminize" en modifiant les infos et ajoutant la photo.

J'ai bien les commandes ON/OFF/Toogle fonctionnelles.

Le sujet ouvert ce matin https://github.com/KiwiHC16/Abeille/issues/1231 porte le même DataByteList (TS0121), mais le module est différent.

Json :
```
{
  "TS0121": {
    "nameJeedom": "TS0121",
    "timeout": "60",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "uniqId": "5cfdgh0asd6rt78620b6b",
      "icone": "TS0121",
      "mainEP": "#EP#",
      "poll": "1"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etatLight",
      "include5": "levelLight",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include19": "getEtat",
      "include20": "getLevel",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel"
    }
  }
}
```

Image :
![node_TS0121](https://user-images.githubusercontent.com/46993341/91476460-4f875480-e89d-11ea-8f78-2ccc4c36c345.png)

Log :
Plus de log d'inclusion.
```
[2020-08-27 19:45:26][debug] Abeille1, Type=8102/Attribut report, SQN=e7, SrcAddr=adf9, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006, DataByteList=TS0121
[2020-08-27 19:50:05][debug] Abeille1, Type=8102/Attribut report, SQN=ec, SrcAddr=adf9, EndPoint=01, ClustID=0006, AttrID=0000, AttrStatus=00, AttrDataType=10, AttrSize=0001, DataByteList=00
[2020-08-27 19:50:05][debug] Abeille1, Type=8102/Attribut report, SQN=ed, SrcAddr=adf9, EndPoint=01, ClustID=0008, AttrID=0000, AttrStatus=86, AttrDataType=ff, AttrSize=0000, DataByteList=
[2020-08-27 19:50:47][debug] Abeille1, Type=8102/Attribut report, SQN=45, SrcAddr=adf9, EndPoint=01, ClustID=0000, AttrID=0001, AttrStatus=00, AttrDataType=20, AttrSize=0001, DataByteList=43
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Il est possible que le HW soit different mais que le soft soit le meme.
Je l ajoute dans la liste des modules.

**Comment by KiwiHC16** [comment]
J ai mis le modele dans master. Je clos le point et on ouvrira des issues si besoins spécifiques.

**Comment by Flobul** [comment]
Petite coquille sur la dernière stable et beta : 
/var/html/plugins/Abeille/core/config/devices/TS0121/TS0111.json


Renommer le fichier json en TS0121.json pour que ça fonctionne.

Et le pdf de la doc contient que des pages blanches ;)

**Comment by KiwiHC16** [comment]
Renomage fait.
PDF mis a jour.
Merci.
