### ISSUE TITLE
Profalux 0x0006 -> 0x0008

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1234]
Recommendation de la part de Profalux , il est préférable d'utiliser uniquement le Cluster 0x0008 plutot que le 0x0006 pour On/Off et 0x0008 pour level control.
https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Profalux-corner.md

#1161

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Je clos.
En cours avec ce sujet https://github.com/KiwiHC16/Abeille/issues/1994
