### ISSUE TITLE
Ajout de la version Zigate DIN.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1236]
- La mise à jour se fait sans démontage. 2 pattes du ftdi sont configurées en IO et du coup, il est possible de piloter le reset et le flash. Tous les logiciels de flashage de la ZiGate sont déjà compatibles avec la fonction.
Si tu veux intégrer la fonction dans abeille, il me semble que je t'avais envoyé un bout de code pour le gérer...
Je t'ai en PJ le code dans flash_ZiGate-DIN.py

See mail du 9/6/2020 à 10h54

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
@KiwiHC16 
Dois je comprendre qu'il y a une solution pour flasher une zigate usb sans intervention manuelle ? 
Ou est ce reservé uniquement a la version "DIN" ?

**Comment by KiwiHC16** [comment]
Oui tu peux upgrader le piziagte et la DIN.

**Comment by KiwiHC16** [comment]
https://zigate.fr/documentation/mise-a-jour-de-la-zigate-din/

**Comment by tcharp38** [comment]
Ok mais pas la zigate USB qui pourtant est proche de la DIN.

Je peux bosser sur son integration dans Abeille si tu en as une à me preter.

**Comment by KiwiHC16** [comment]
Oui proche mais des fils ne sont pas connecter et ne permettent pas de la faire sur la version USB.
La version DIN est une evolution de la version USB.

**Comment by tcharp38** [comment]
Ok.
Sais tu si les dernieres version USB sont modifiées dans ce sens alors ?
Ca pourrait etre sympa de savoir quelle modif faire aussi.

**Comment by KiwiHC16** [comment]
A ma connaissance les USB non pas évoluées.

**Comment by tcharp38** [comment]
Premier support ajouté (#1401).
@KiwiHC16, tu en as une n'est ce pas ?

**Comment by KiwiHC16** [comment]
Oui j'en ai une.

**Comment by KiwiHC16** [comment]
la prochaine ZiGate-USB v2 sera avec le remote upgrade.

**Comment by tcharp38** [comment]
je n'en attendais pas moins.
Si il a trouvé la solution sur la DIN alors ca doit être facile à transposer.

**Comment by KiwiHC16** [comment]
Essai de mise en 3.1D de ma version DIN en suivant la doc page: https://zigate.fr/documentation/mise-a-jour-de-la-zigate-din/

Debian 10 / Jeedom 4.1.19 / Abeille Master dans VM Parallele sous OSX.

```
root@abeille:/var/www/html/JennicModuleProgrammer/Build# ./flash_ZiGate-DIN.py -s /dev/ttyUSB0 -b 250000 -f ZiGate_v3.1d.bin 

**** Mode Flash ****

JennicModuleProgrammer Version: 0.6 (r56124)
Setting baudrate: 250000
Error setting baudrate

**** Mode Production ****


**** Terminé ****
```

Je ne parviens pas a programmer. Tout se passe bien sauf la programmation. Lors de la programmation la led devient blafarde  puis revient pleine luminosité.

**Comment by KiwiHC16** [comment]
Windows 7 / Beyond Studio from NXP.

Ne trouve pas le driver.
EByte E75 - FTDI 

Installation du driver et la programmation nickel.

**Comment by tcharp38** [comment]
@KiwiHC16 
Nouvelle update dans le master.
Je te laisse tester. J'ai pas ce type de zigate.

**Comment by tcharp38** [comment]
Je close le sujet.
A reouvrir si besoin
