### ISSUE TITLE
Dans la liste des compatibilités vers la doc.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1237]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
@KiwiHC16 J'ai l'impression que c'est déja en place non ?
Enfin pas en ligne avec le titre. Le lien renvoi vers AbeilleDoc donc parfait

**Comment by KiwiHC16** [comment]
Je dirai que oui.
Je change le titre.

Mais il semble que tout ne soit pas en ligne (ou je ne comprend pas le fonctionnement):
Sur la page de conf d  un equipement la doc pointe vers:
"https://github.com/KiwiHC16/AbeilleDoc/blob/master/docs/products"

d apres le code: resources/AbeilleDeamon/includes/config.php:    define('urlProducts', 

Pour le legrand 20AX, si je clic j arrive à:
https://github.com/KiwiHC16/AbeilleDoc/tree/master/docs/products/Contactor

alors que le lien dans Abeille est:
https://github.com/KiwiHC16/AbeilleDoc/blob/master/docs/products/Contactor

Donc github redirect la requête.

**Comment by tcharp38** [comment]
Oui mais les 2 fonctionnent et arrivent au meme endroit.
Tu sais la diff entre "tree" et "blob" ?

**Comment by KiwiHC16** [comment]
Non, je ne me souviens plus. Mais dans ce cas ou est le stocage des docs dans Github ?
Si j ai  une nouvelle doc, je la mets ou ?

**Comment by tcharp38** [comment]
La cible est la meme.
Toujours "docs/produits" sous AbeilleDoc

mais l'URL pour y acceder via tree ou blob je vois que ca fait pareil. D'ou ma question

**Comment by KiwiHC16** [comment]
Dans la page compatibilité, le lien est du type:
https://github.com/KiwiHC16/AbeilleDoc/tree/master/source/docProduits/Contactor/doc/

et si je clic j arrive sur:
https://github.com/KiwiHC16/AbeilleDoc/tree/master/source/docProduits/Contactor/doc/

et c est encore different ...

**Comment by KiwiHC16** [comment]
Alignement du lien depuis page equipement et page compatibility list sur le lien:
https://github.com/KiwiHC16/AbeilleDoc/blob/master/docs/products/Contactor

Si ce n est pas le bon il faut le modifier dans 
esources/AbeilleDeamon/includes/config.php: 
define('urlProducts',

**Comment by KiwiHC16** [comment]
L organisation de la doc est expliquée ici: https://github.com/KiwiHC16/AbeilleDoc dans le Readme.md.

Donc maintenant semble ok.

Je clos.
