### ISSUE TITLE
Probleme remonté etat sur transformateur tradfi

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1239]
Bonjour,

Je remarque que la remontée des etats des transfo tradfi fonctionne mal, en effet il ne remonte pas l etat, il faut faire une action pour avoir l etat ON ou OFF.

Un peu embetant car on ne sait pas si c'est allumé ou non 

cordialement

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Vérifie dans santé que tu as bien les adresses IEEE pour la ruche et le transfo.
Si non fais un refresh LQI.
Si ok, vas dans les commandes du transfo ou tu dois trouver: BindToZigateEtat et setReportEtat
Fais executer sur la premiere, puis sur la seconde, ca devrait resoudre le soucis.

**Comment by bouboun59** [comment]
Bonjour,

Merci cela refonctionne normalement

merci
