### ISSUE TITLE
Perte du Port Série

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1240]
Bonjour,
De nouveau, ce matin tous mes capteurs étaient en Timeout. Je n'ai fait aucune mise a jour. Dans la config du plugin, c'est a nouveau le port qui a sauté et qui est passé sur RFXCom. Cela fait 2 fois en quelques jours et toujours avec le RFXCom. 
Une idée ? Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Sur quelle version es tu ? (voir page de configuration)

**Comment by Kenderv** [comment]
Excuse le retard de la réponse. Merci et bon dimanche
![image](https://user-images.githubusercontent.com/52486183/92320316-d2887780-f020-11ea-8d90-af2f84b62b78.png)

**Comment by KiwiHC16** [comment]
Peux tu partager une copie d'ecran de la partie 
![Capture d’écran 2020-09-06 à 18 38 06](https://user-images.githubusercontent.com/8549674/92330563-1ce51500-f070-11ea-86d6-1d49973c522d.png)

(ici c est indiqué master, mais tu dois avoir une date).

**Comment by Kenderv** [comment]
Voilà 
![Capture](https://user-images.githubusercontent.com/52486183/92374762-7b59d400-f100-11ea-96a1-43c463362a4c.JPG)

**Comment by Kenderv** [comment]
J'ai l'impression qu'à chaque fois que je redémarre Jeedom, le port change vers le port du RFX Com. Je suis obligé de changer le port et d'attendre que tous les équipements sortent du timeout.

**Comment by Kenderv** [comment]
Bonsoir @KiwiHC16 . Je te confirme qu'après un redémarrage de Jeedom j'ai à nouveau perdu le port de la Zigate remplacé par celui de mon RFXCom
Ci-joint le log du redémarrage
[AbeilleConfig.txt](https://github.com/KiwiHC16/Abeille/files/5230847/AbeilleConfig.txt)

**Comment by tcharp38** [comment]
Salut
J'essaie de comprendre ton pb.
Quand tu dis "jai perdu le port. Il est passé sur RFXcom".. ca veut dire quoi au niveau Abeille ?

**Comment by Soyann** [comment]
Hello
Regardes #1102 , car malgré les modifs de KiwiHC16, ça me le fait encore... ici c'est entre 2 Zigates, mais également avec mon RFXcom:
Il n'est pas rare au démarrage de Jeedom (environ 1 fois sur 2) que je trouve en port de la zigate1 le port USB de mon RFXcom et en zigate2 le port de ma zigate1...
![image](https://user-images.githubusercontent.com/46709337/93334154-b9ec3e80-f824-11ea-8b79-92ebeb7cde8d.png)

**Comment by Kenderv** [comment]
Salut @Soyann et @KiwiHC16 
C'est exactement à cet endroit que je retrouve RFXCom au lieu de Silicon_labs. Bon courage et bonnes recherches

**Comment by KiwiHC16** [comment]
@Kenderv, le plugin Abeille ne peut rien faire si l OS change l ordre de device USB. 

Une solution pour ton systeme est : https://www.domoticz.com/wiki/PersistentUSBDevices

**Comment by Kenderv** [comment]
Merci, je regarde ça de très près et je te tiens au courant

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by Kenderv** [comment]
Non, j'ai lu le dossier dont tu m'as envoyé le lien mais je n'ai pas mis en œuvre ayant eu peur de faire une connerie et de planter mon system.

**Comment by KiwiHC16** [comment]
Que fait on de cette issue ? As tu encore besoin d aide ?

**Comment by Kenderv** [comment]
Je n'ai malheureusement pas eu le temps de gérer ce problème. Je pense qu'il convient de fermer ce sujet.
Merci de ton aide et de ton travail sur ce plugin

**Comment by KiwiHC16** [comment]
Ok je ferme.
