### ISSUE TITLE
Erreur sur Abeille::deamon() : Call to a member function setConfiguration() on null

### ISSUE THREAD

**Issue by Youss93** [KiwiHC16/Abeille#1242]
Bonjour, j'ai installé un capteur de luminosité xiaomi. Abeille le reconnais bien mais il ne renvoie aucune information et reste désespérément time out. À savoir que j'ai déjà un autre capteur identique que j'ai installé avant la mise à jour du plugin et celui-ci fonctionne parfaitement. Pourriez-vous m'aider s'il vous plaît ?
![IMG_20200903_114848](https://user-images.githubusercontent.com/67928370/92100624-500f7600-eddc-11ea-861e-66e61844fdb4.jpg)

**Comment by beuz1212** [comment]
hello depuis la mise à jour du plugin j'ai cette erreur également lors des nouvelles inclusion.
Personnellement je viens de relancer un backup pour faire un rollback, je n'ai pas d'erreur sur l'ancienne version.

**Comment by Youss93** [comment]
Merci beaucoup pour l'info. Je vais en faire de même en attendant une autre mise à jour 👍👍

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok je viens de la reproduire. Je regarde.

**Comment by KiwiHC16** [comment]
Je viens de publier une nouvelle stable qui corrige le soucis.

**Comment by KiwiHC16** [comment]
Je clos, rouvrez si le probleme persiste

**Comment by Youss93** [comment]
Re, j'ai refait une nouvelle inclusion. Il n'y a plus de message d'erreur mais le capteur est toujours en timeout 😕

**Comment by Youss93** [comment]
Bonjour, j'ai refait une nouvelle inclusion tout fonctionne parfaitement. Je pense que l'on peut clôturer le post. Merci pour votre aide et chapeau pour tout le boulot 😋😋

**Comment by KiwiHC16** [comment]
Merci pour le retour.
