### ISSUE TITLE
WiringPi semble mal installé. PiZigate inutilisable.

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#1245]
Bonjour @KiwiHC16.

J'ai testé le dernier correctif (version master - febb78a5900596edba2d...) et je te remonte une issue "mineure".
Après mise à jour puis redémarrage du plugin, j'obtiens le warning "WiringPi semble mal installé. PiZigate inutilisable." alors que j'utilise une Zigate **Wifi**.

Il manque surement une condition quelque part dans ton code ! :)

![image](https://user-images.githubusercontent.com/48121420/92218460-76471b80-ee99-11ea-8f4a-667bad60fc30.png)

**Comment by tcharp38** [comment]
Salut.
Ca doit etre lié à ce que j'ai poussé.
Si tu n'as pas de PiZigate l'erreur n'a pas d'incidence mais j'aimerais comprendre pourquoi tu as ça.
Peux tu me copier la page "support", accessible via la page de gestion d'Abeille ?
Merci

**Comment by Asyrah** [comment]
[support_abeille.txt](https://github.com/KiwiHC16/Abeille/files/5173593/support_abeille.txt)

**Comment by Asyrah** [comment]
Pour plus d'ergonomie sur la page support, y aurait-il moyen d'inclure un bouton "télécharger" ?

**Comment by tcharp38** [comment]
> Pour plus d'ergonomie sur la page support, y aurait-il moyen d'inclure un bouton "télécharger" ?

Ha pour recuperer le fichier sans faire de copier/coller je suppose. Oui ca doit etre jouable.
Je te laisse creer une issue dans ce sens. A tagger "enhancement"

Quant au probleme que tu reportes, je viens de trouver mon bug.
Je vais pousser le fix. Merci

**Comment by tcharp38** [comment]
@Asyrah 
Kiwi a mergé ma correction. Je te laisse retester.
Merci pour ton aide

**Comment by Asyrah** [comment]
@tcharp38 
Maj effectuée version d85542c97d780883...
RAS, je n'ai plus le warning sur mon antenne avec zigate wifi.
RAS aussi sur mon antenne avec pizigate aussi.
On peut clore l'issue.
