### ISSUE TITLE
[Ergonomie] Ajouter un bouton "télécharger" à la page support

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#1247]
Évoqué dans l'issue  #1245 

Pour plus d'ergonomie sur la page support, ajouter un bouton "télécharger" pour récupérer le fichier sans faire de copier/coller.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
@KiwiHC16 
Tu peux me l'affecter si tu veux

**Comment by KiwiHC16** [comment]
C est fait. Super.

**Comment by tcharp38** [comment]
Heu.. tu t'es gouré de cible :)

**Comment by KiwiHC16** [comment]
Oups pardon

**Comment by tcharp38** [comment]
Livré !
