### ISSUE TITLE
Dimmer/Switch Sunricher et Rebrand

### ISSUE THREAD

**Issue by Gaubuz** [KiwiHC16/Abeille#1249]
Bonjour, 

Nouveau dans le monde de la programmation je me permet d'ouvrir une issue pour faire un petit focus sur les switch/dimmer provenant du fabriquant "Sunricher", le plus connu étant le "Iluminize". Le but étant surtout de confirmer la compatibilité.

J'ai pu acquérir à bon prix un SM309 (clone du Iluminize) : [https://www.samotech.co.uk/products/zigbee-dimmer-switch-hue-compatible/](url)

Ce dernier n'est pas reconnu initialement par le plugin, après quelques heures de lecture j'ai trouvé comment créer mon fichier JSON. J'ai fait un copier-coller du fichier JSON du module Iluminize 511.201 en changeant "nameJeedom" par "SM309" et "uniqID" par une séquence différente.

A présent le module est parfaitement reconnu et fonctionne parfaitement.

Il existe une multitude de clone :
[https://www.lumimania.fr/immax-neo-interrupteur-variateur-pour-luminaires-zigbee-3-0/?gclid=CjwKCAjwkdL6BRAREiwA-kiczFKZNmwZJd6Q_6sd8-aRcLkha21l4KyU7Lub3gAuNTm3TzvyVORZhBoCzF4QAvD_BwE](url)
[https://www.amazon.fr/CONNEX-Zigbee-Variateur-phase-230/dp/B07MC6GB9V/ref=sr_1_38?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=zigbee+dimmer&qid=1599418287&sr=8-38](url)
[https://www.amazon.fr/Zigbee-Module-variateur-0-200-Halog%C3%A8ne/dp/B086N2HKJM/ref=sr_1_102?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=zigbee+dimmer&qid=1599418320&sr=8-102](url)

Et j'en oublie surement...
Cela pourrait être intéressant d'ajouter ces variations à la liste des modules compatibles ?

Bravo pour le boulot !

Gaubuz

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Super !

Peux tu partager le fichier JSON que tu as fait pour que je l ajoute ?

**Comment by Gaubuz** [comment]
Biensur !

Le voici :
[SM309.json.txt](https://github.com/KiwiHC16/Abeille/files/5288681/SM309.json.txt)

(en fichier .txt car json non accepté par Github)

**Comment by KiwiHC16** [comment]
Merci. Ajouté au master.
