### ISSUE TITLE
Possibilité de remplacer un équipement par un autre

### ISSUE THREAD

**Issue by lukebr91** [KiwiHC16/Abeille#125]
C'est peut être un peu tôt pour cela mais je lance l'idée 👍

Sur le même principe qu'en Zwave : https://nechry-automation.ch/2017/08/28/remplacer-node/

En cas de module défaillant ou de reset complet du réseau (comme c'est le cas pour la mise à jour 3.0D)
Si l'on peut avoir la possibilité d'indiquer la nouvelle adresse à l'ancien equipement ça permettrait de ne pas avoir à faire le transfert commande par commande ou mise à jour des scenarii.

**Comment by lukebr91** [comment]
Nota: réussi à le faire en remplaçant directement dans la base SQL les noms/logicalid/configuration sur l'ancien equipement - mais une fonction le faisant & supprimant le nouvel équipement en doublon serait top !
Mais ça reste de la bidouille, il faut aussi modifier dans les cmd

**Comment by KiwiHC16** [comment]
J'ai aussi vu ce besoin, je supporte l'idée.

**Comment by KiwiHC16** [comment]
Qu’est ce que tu as changé dans la base ? Juste le eqLogic ou beaucoup plus ?

**Comment by lukebr91** [comment]
Pour avoir les remontées d'info, juste les eqlogic, pour avoir également
les actions, j'ai fait un export de la base, remplacer tout pour chaque
module dans le .sql et reimport de la base ne maîtrisant pas assez sql.

**Comment by KiwiHC16** [comment]
Apres premiere analyse , surtout ne pas toucher à la structure des Id mais uniquement changer les references aux Addr Short.
Donc en parametre nous n'avons besoin que de l'adresse de initiale et l'adresse target.

**Comment by KiwiHC16** [comment]
https://github.com/KiwiHC16/Abeille/blob/master/Documentation/RemplacementDunEquipement.adoc

**Comment by lukebr91** [comment]
Fonctionnement OK chez moi 👍
