### ISSUE TITLE
Problème d'appairage ampoules phillips hue

### ISSUE THREAD

**Issue by MiKLM** [KiwiHC16/Abeille#1251]
Bonjour à tous,

Je souhaiterais migrer des ampoules hue, qui sont actuellement sur le pont hue vers ma zigate en utlisant le plugin abeille.
J'ai donc procédé de la manière suivante:
1) J'ai supprimé mes ampoules de l'application.
2) J'ai fait un reset de la télécommande (appuis environ 10s sur le bouton reset)
3) j'ai vérifié que la télécommande ne pilotait plus de lumières.
4) J'ai fait un reset de l'ampoule avec appuis d'environ 10s sur les boutons I et O de la télécommande en étant proche de l'ampoule. le reset a l'air de fonctionner car l'ampoule clignote.
5) Je débranche l'ampoule pour l'éteindre
6) Je met la zigate en mode inclusion
7) Je rebranche l'ampoule qui s'allume

Normalement à cette dernière étape un objet doit apparaitre dans la ruche, mais là rien...
Avez-vous une idée de ce qui peut bloquer?
Merci de votre aide.
Mickaël

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je vais traiter #1256 en premier car le probleme vient probablement de la.

**Comment by KiwiHC16** [comment]
Correction in master

**Comment by KiwiHC16** [comment]
Correction dans stable dispo demain.
