### ISSUE TITLE
Philips Hue White and color ambiance

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#1252]
Bonjour, 
Cela fait un moment que je parcours les doc les listes ...

j'aimerais savoir si ce modèle est supporté ?

**Philips Hue White and color ambiance single bulb E27**

Si oui quel procédure d'inclusion.

par avance merci et désolé si je n'ai pas trouvé le bon sujet

cordialement.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Il m est difficile de repondre. Il me faudrait son nom zigbee. On le recupere lors d une inclusion. En as tu une stock ?

**Comment by djsyl** [comment]
https://www.amazon.fr/gp/product/B07SS38CVG/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

**Comment by djsyl** [comment]
elle ne sort pas en intégration

**Comment by KiwiHC16** [comment]
Si tu es en mode debug et que tu regardes dans le log AbeilleParser, vois tu son nom passer ?

**Comment by djsyl** [comment]
Pour l'instant je les aient toutes integréres dans le plugin philipshue je doit en reçevoir 2 autres 
Je ferait le test ce weekend ... je te fait un retour dés que possible.

**Comment by djsyl** [comment]
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5250379/AbeilleParser.txt)
Voilà Mr

**Comment by djsyl** [comment]
up ?

**Comment by KiwiHC16** [comment]
As tu son nom (zigbee dans abeilleparser) ?

**Comment by djsyl** [comment]
Aucune idée le fichier est juste au dessus !

**Comment by KiwiHC16** [comment]
Je ne vois rien dans le log.
Je me demande si il n'y a pas un souci avec les inclusions de hue il faut que je fasse un test

**Comment by djsyl** [comment]
ça marche tiens nous informé.

**Comment by KiwiHC16** [comment]
J'ai trouvé un soucis sur les hue je vais pousser une solution.

**Comment by djsyl** [comment]
Oki aprés mise a jours d'aujourd'hui 
la détection est faite :


  | 2020-09-30 15:50:56 | Abeille | getJSonConfigFilebyDevices:  filename not found:  /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/LCA001/LCA001.json  will send back default template. |   |  
-- | -- | -- | -- | -- | --
  | 2020-09-30 15:50:56 | Abeille | Création d un nouvel objet Abeille (Abeille1/0f6f) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

Il ne semble pas y avoir de commandes en relation ...
etat, on off ... sont absentes.

**Comment by djsyl** [comment]
up

**Comment by djsyl** [comment]
[LCA001.zip](https://github.com/KiwiHC16/Abeille/files/5339136/LCA001.zip)
puis qu'il faut tout faire voila ...
à mettre dans 
/var/www/html/plugins/abeille/core/config/devices

**Comment by djsyl** [comment]
PR fait

**Comment by KiwiHC16** [comment]
Super aussi l icone dans le master.
