### ISSUE TITLE
philips hue smart button modele

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1254]
https://community.jeedom.com/t/philips-hue-smart-button-jeedom-v3-plugin-abeille/36350/3

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
https://zigate.fr/produits-philips-hue-compatibles-zigate/compatible/smartbutton/

**Comment by tcharp38** [comment]
Pas d'infos et vieux sujet.
A reouvrir si qqn est interessé.
