### ISSUE TITLE
Support GLEDOPTO RGT+CCT LED Controller (id = GL-C-007, GLEDOPTO)

### ISSUE THREAD

**Issue by cochise57** [KiwiHC16/Abeille#1256]
Bonjour,
Je tente depuis plusieurs jours d’inclure mon contrôleur RGB GLEDOPTO avec le plugin abeille et ma Zigate, mais en vain. Aucun objet ne se créait mal grès plusieurs reset du module et une réinstallation de Jeedom.
J’ai essayé avec le plugin Zigate et avec ce dernier l’inclusion fonctionne correctement.

Mon Jeedom a une version 4.0.61 et tourne sur RPI 2B. Le plugin Abeille a la version du 04.09.2020.

Pourriez-vous m’aider? Si oui quels sont les logs que vous avez besoin ?

Cordialement,
Anthony

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Visiblement il y a quelque chose de cassé pour les inclusions. Je vais regarder. J espere ce week end.

https://community.jeedom.com/t/association-ampoule-hue-impossible-avec-ma-zigate/36162/22

**Comment by KiwiHC16** [comment]
Ca doit fonctionner avec la version stable de demain si tu peux essayer demain.

**Comment by cochise57** [comment]
Bonjour,
C'est super, ca fonctionne. En revanche, je tiens à t'alerter sur le fait que j'ai récemment acheté des interrupteurs Xiaomi, normalement inclus dans les équipement compatibles. Malheureusement il se voit comme inconnu dans Jeedom.
Je reçois ce message à la création de l'équipement.
getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/switch.b1nacn02/switch.b1nacn02.json will send back default template.
 

Pour résoudre ce problème, j'ai copier le fichier /core/config/devices/ctrl_ln1.aq1 en changeant le nom et le titre, en ctrl_ln1.aq1.json se qui à résolu le problème.

Merci pour toutes les actions que tu as mené

Cordialement,
Anthony

**Comment by cochise57** [comment]
Visiblement, tout ne fonctionne pas, la communication entre Jeedom et le contrôleur le ne fonctionne pas. J'ai beau essayer toutes les commandes, mais aucune ne fait réagir le contrôleur. En revanche, les info (level, on/off,...) remontes bien.

Cordialement,
Anthony BREDA

**Comment by KiwiHC16** [comment]
Salut, je vois 3 sujets dans une même discussion c est pas terribleme. J'ai besoin de clarifier.

_Sujet 1: GLEDOPTO RGT+CCT LED Controller, retour etat fonctionne mais pas envoie de commandes_
=> Peux tu partager les commandes envoyées (log AbeilleCmd) quand tu envoies une commande ?

_Sujet 2:  interrupteurs Xiaomi (switch.b1nacn02), N est pas créé dans Abeille_
=> C est normal il n est pas connu par Abeille

_Sujet 3:  j'ai copier le fichier /core/config/devices/ctrl_ln1.aq1 en changeant le nom et le titre, en ctrl_ln1.aq1.json_
=> Pour quel probleme est ce ?

**Comment by KiwiHC16** [comment]
Du nouveau pour mes questions ?

**Comment by cochise57** [comment]
Bonjour,
Désolé de ma non réponse, j'ai pas trop eu de temps ces derniers jours. En réalité, et c'est entièrement de ma faute, il y a 2 sujet (je sais que c'est mal) sur ce post. Le premier est bien le GLEDOPTO RGT controller. Pour la génération des logs, est-ce que je dois mettre à jour abeille dans la version qui ne fonctionne pas? Ou est-ce que je peux rester dans ma version actuelle ?

Le deuxième sujet est le bouton Xiaomi cité précédemment et pour le faire fonctionné j'ai copié le fichier d'un device similaire (Xiaomi Wall Switch w/o Neutral 1) en le renommant avec le bon intitulé (switch.b1nacn02.json).

Cordialement,
Anthony

**Comment by KiwiHC16** [comment]
GLEDOPTO RGT controller: Prend la versioon que tu as dans un premier temps.

**Comment by cochise57** [comment]
Bonjour,
Quel est la démarche que tu préconises ? Dois-je juste exécuter les commande disponible et te renvoyer les logs AbeilleCmd ?

Cordialement,
Anthony

**Comment by cochise57** [comment]
Bonjour et meilleur vœux,
As-tu une démarche à me préconiser ?

Cordialement,
Anthony

**Comment by KiwiHC16** [comment]
GLEDOPTO RGT controller

Peux tu mettre Abeille en mode debug, redémarrer le daemon, faire l inclusion du contrôleur et partager ce que tu obtiens dans AbeilleParser.log.

**Comment by cochise57** [comment]
Bonjour,
Je viens de réaliser ta demande. J'ai plusieurs GL-C-008 et deux n'avaient pas réagis pareil la dernière fois, alors dans le doute, j'ai fait l'analyse demandé avec les deux versions.

Je te remercie vraiment pour le suivit que tu réalise sur ce plugin. Bien sur je reste à ta disposition pour d'autres tests.

Cordialement,
Anthony BREDA

[AbeilleParser-GL-C-008-seconde-version.txt](https://github.com/KiwiHC16/Abeille/files/5875661/AbeilleParser-GL-C-008-seconde-version.txt)
[AbeilleParser-GL-C-008-premiere-version.txt](https://github.com/KiwiHC16/Abeille/files/5875662/AbeilleParser-GL-C-008-premiere-version.txt)

**Comment by KiwiHC16** [comment]
Premiere Version, infos interessante:

```
[2021-01-26 20:37:40][debug] Type=8102/Attribut Report: Dest=Abeille1, SQN=9f, SrcAddr=9b6f, EndPoint=0B, ClusterID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0008, DataByteList=GL-C-008
```
GL-C-008

```
[2021-01-26 20:37:36][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=09, Status=00, ShortAddr=9b6f, Length=16, EndPoint=0B, Profile=c05e (ZLL Application Profile), DeviceId=0210 (Extended color light), BitField=02
[2021-01-26 20:37:36][debug]   InClusterCount=07
[2021-01-26 20:37:36][debug]   InCluster=0000 - General: Basic
[2021-01-26 20:37:36][debug]   InCluster=0003 - General: Identify
[2021-01-26 20:37:36][debug]   InCluster=0004 - General: Groups
[2021-01-26 20:37:36][debug]   InCluster=0005 - General: Scenes
[2021-01-26 20:37:36][debug]   InCluster=0006 - General: On/Off
[2021-01-26 20:37:36][debug]   InCluster=0008 - General: Level Control
[2021-01-26 20:37:36][debug]   InCluster=0300 - Lighting: Color Control
[2021-01-26 20:37:36][debug]   OutClusterCount=00
```

On/Off - Level - Color


Deuxieme Version, pas d info vraiment intéressante.

**Comment by KiwiHC16** [comment]
Peux tu me rappeler ce que tu souhaites, ton soucis car la je suis perdu.

**Comment by cochise57** [comment]
Bonjour,
J'avais mis en place le contrôleur sur la dernière version stable mais ca ne fonctionnait pas. J'avais bien la partie info mais la partie commande ne fonctionnait pas. Souhaites tu que je mettent à jour et que je reface un test?

Cordialement,
Anthony

**Comment by KiwiHC16** [comment]
Pour l instant je suis perdu dans ton sujet. Dis toi que j'ai pas loin de 200 cas et qu'a chaque fois il faut que je parvienne a suivre ce que vous faites, ce qui fonctionne et ce qui ne fonctionne pas. Peux tu me faire un resumé de ce qui fonctionne, et de ce qui ne fonctionne pas et ce que tu souhaite. Désolé pour de te poser ces questions de base.

**Comment by cochise57** [comment]
En gros, en version 2020.07.20 de abeille, l'inclusion fonctionne et une fois mis à jour en 2020.08.26, l'inclusion ne fonctionnait plus. Tu as ensuite mis à jour abeille et après, l'inclusion fonctionnait, mais plus moyen de changer les couleurs, ou d'éteindre ou d'allumer le module. En revanche j'avais bien les infos de couleur, allumé/éteint.. qui remontaient. Je te proposais de mettre à jour en v.2020.12.01 afin de tester.

**Comment by KiwiHC16** [comment]
Et quelle est la situation sur la derniere stable ?

**Comment by cochise57** [comment]
Bonjour,
Je viens de mettre à jour et de tester. Mes premier essaies étaient concluant sur la l'équipement déjà présent sur mon Jeedom. J'ai donc essayé de le supprimer et de le remettre, et là en revanche, les problèmes commences.
L'inclusion fonctionne, et j'ai bien le type d'équipement, ainsi que les commandes qui remontent. En revanche, je n'ai plus les valeur de retour de mon équipement et l'ensemble des commandes ne répondent plus (On/Off/Changement de couleurs/Changement d'intensité/...). J'ai essayé un autre équipement du même model et je rencontre le même problème.
Afin de t'aider j'ai réalisé une capture du parser au moment de l'inclusion. Je te mets 2 fichier, le premier est l'inclusion et le second contient des erreurs à la suite de l'inclusion.
[Erreur.log](https://github.com/KiwiHC16/Abeille/files/5920921/Erreur.log)
[Inclusion.log](https://github.com/KiwiHC16/Abeille/files/5920922/Inclusion.log)

Merci de ton aide,
Anthony

**Comment by tcharp38** [comment]
Salut @cochise57 
Toujours interessé par le sujet ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Oui je suis toujours intéressé par ce sujet, car j'ai encore des problèmes de prises en charges entre abeille et les module RGB.

Cordialement,
Anthony BREDA

**Comment by tcharp38** [comment]
Ok, alors on va essayer d'avancer ensemble.
Pourrais tu déja me generer un discovery ? (voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee) et tu me le zip et met ici.

Ensuite comme ce sujet date et qu Abeille a beaucoup evolué en profondeur, j'ai besoin d'un résumé actualisé (ce qui fonctionne et ce qui ne fonctionne pas).

Enfin, je te suggere de basculer sur la beta le temps qu'on bosse ensemble. Tu pourra ensuite rester sur la stable.
Voir; https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by cochise57** [comment]
Salut @tcharp38,
Désolé du petit délai, mais j'ai eu un problème de connexion entre ma zigate et Abeille. J'ai donc réinstallé tout Jeedom et impossible de connecter ma zigate à Abeille. Je sélectionne usb+/2 et le port usb de ma zigate et j'ai un cercle de chargement en boucle. Si je rafraichit la page et que je resélectionne, j'ai un message me disant qu'aucune zigate n'est détecté.  Je cherche pour résoudre et je reviens vers toi. Maintenant si tu as une piste je suis preneur.
Cordialement,
Anthony

**Comment by tcharp38** [comment]
Tu me montres ta page de config et tu me file le log AbeilleConfig ? Attention a bien activer le mode "debug" puis redemarrer si ca n'est pas le cas.

**Comment by cochise57** [comment]
Salut @tcharp38;
Après pas mal de d'acharnement, j'arrive à connecter ma zigate DIN V1 (je me suis trompé dans mon précédent message).
Je viens de prendre un module GLEDOPTO que j'avais de côté et je l'ai appairé à Abeille. J'ai bien toujours le même problème, le W, du module est en permanence allumé.
Comme demandé, j'ai réalisé une découverte sur cette équipement, qui donne le fichier que je te joins à ce message.
Merci encore de l'aide.
Anthony
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7824301/discovery.zip)

**Comment by tcharp38** [comment]
Merci pour la découverte. Elle est bien incomplete mais c'est déja ca.

C est quoi ca le W du module ?
J'ai du mal à comprendre ce qui fonctionne et ce qui fonctionne pas. Tu peux m'eclairer ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Est-ce que je peux t'aider pour la rendre complète?
Le module permet de contrôler des LED RBG ayant en plus des LED - Classique pour la température de couleurs. C'est ces LED là qui sont allumés en permanence par le W.

Cordialement,
Anthony BREDA

**Comment by tcharp38** [comment]
Si tu n'es pas sur la beta, peux tu basculer dessus ?

**Comment by cochise57** [comment]
Je suis déjà en béta, comme tu me l'avais demandé ;)

**Comment by tcharp38** [comment]
Cool.
Du coup avec l'assistant il faut essayer de transformer tous les boutons orange en vert, en recliquant dessus.
J'imagine que tu en avais plusieurs orange non ?

**Comment by cochise57** [comment]
Avant te t'envoyer le fichier, j'ai cliqué à plusieurs reprises sur chaque bouton mais ils ne sont jamais passés vert. Dois-je attendre un certain temps après chaque clique sur les flèches orange?

Anthony

**Comment by tcharp38** [comment]
Non pour un equipement sur secteur ca doit etre quasi immediat.
Donc il y a un souci.
Peux tu regarder dans core/config/devices_local/GL-C-007 si il n'y a pas un discovery auto-generé ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Non je n'ai aucun fichiers auto-généré dans ce dossier.

**Comment by cochise57** [comment]
Dois-je refaire des tests ?

**Comment by tcharp38** [comment]
Salut @cochise57 
Je realise que ton equipement s identifie comme 2 equipements differents: GL-C-007 (EP 0B) & GL-C-006 (EP 0F).
Jamais vu ce cas de figure.
J y reflechis et je reviens vers toi

**Comment by cochise57** [comment]
Salut @tcharp38,
Je reviens vers toi si tu as eu une réflexion positive sur mon problème?

Cordialement,
Anthony BREDA

**Comment by tcharp38** [comment]
Salut @cochise57 
La reflexion n'est pas complete mais tu peux deja, passer en beta si ca n'est pas le cas, et tenter une inclusion de ce modele, puis me filer le package de logs.
Je veux voir comment Abeille reagit maintenant. Tous les EP doivent etre interrogés.

**Comment by tcharp38** [comment]
Pour mémoire cet equipement repond
- GL-C-007 sur EP 0B
- GL-C-006 sur EP 0F

C'est le premier équipement qu'on voit passer avec une double identification.

**Comment by cochise57** [comment]
Salut @tcharp38,
Voici la découverte. J'ai l'impression qu'elle est moins fourni qu'au part avant.

Cordialement,
Anthony
[discovery.txt](https://github.com/KiwiHC16/Abeille/files/8200089/discovery.txt)

**Comment by tcharp38** [comment]
Salut
Je t'avais demandé le package de logs suite à une nouvelle inclusion :)
Mais merci.

**Comment by cochise57** [comment]
Désolé de ce contre-temps. On parle de l'équipement avec l'adresse F7AB / 00124B002114C2BA.


[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8200633/AbeilleSerialRead1.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8200634/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8200635/AbeilleParser.log)

Merci pour ton aide

**Comment by tcharp38** [comment]
@cochise57 
Je vois qu'il est reconnu comme GL-C-007 cette fois.
Quel est le status ?
Il y a des tas de commandes qui ont du etre generées.

Autre point: package de logs = celui dispo via la page support/telecharger tout. Il est + complet et tout pret pour faire un drag & drop dans ce forum.

**Comment by tcharp38** [comment]
Salut @cochise57 
Ce sujet fait encore du sens ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Oui, j'ai toujours un problème avec la gestion de la température de lumière. Dès que je branche la lettre W c'est allumé en permanence. De plus je viens de remarqué, le device est reconnu en temps que GL-C-007 et GL-C-006 mais aucune de ces deux références ne correspondent au problème. La bonne référence est le GL-C-008.

Merci encore pour l'aide que tu apporte
Anthony

**Comment by cochise57** [comment]
Salut @tcharp38,
Qu'aurais-tu besoin pour m'aider dans la résolution de ce bug ?

Merci à toi,
Anthony

**Comment by tcharp38** [comment]
Salut @cochise57 
Tu aurais une photo qui montre ce dont tu parles, cette fameuse lettre W ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Voici la Photo demandé.
![IMG_20220608_123203](https://user-images.githubusercontent.com/15246946/173206121-b6fc71d5-c47b-4075-852f-7dd3546293c7.jpg)

Merci à toi,

Anthony

**Comment by cochise57** [comment]
Salut,
@tcharp38, je déterre un peut ce sujet mais as-tu pus avancer sur mon problème. Est-ce que ca ne serait pas plus simple que je t'envois un de mes GL-C ?

Anthony

**Comment by tcharp38** [comment]
Salut @cochise57 
Envoie moi un mail perso via "tcharp38@laposte.net". Je te filerai mes coordonnées si tu veux toujours m'envoyer un GL-C pour creuser.

**Comment by tcharp38** [comment]
Je ferme cet antique sujet sans vie.
A réouvrir si qqn est interessé.
