### ISSUE TITLE
Page santé: missing IEEE

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1259]
@KiwiHC16 
Je ne sais plus pour quelle raison je suis arrivé à ce stade mais néanmoins sur une de mes plateformes de test j'ai 3 adresses IEEE manquantes.

![image](https://user-images.githubusercontent.com/35221038/94165980-14bc1080-fe8b-11ea-8b01-9a148ba6f2b8.png)

Elles n'était pas non plus dans la config des periphériques en question.
Ce que j'ai corrigé mais ... la page ne change pas et les adresses restent "manquantes".

Apres analyse du code, il se trouve que tu ne prends pas l'adresse IEEE stockée dans la config
$eq->getConfiguration('IEEE')).
Au lieu de ca on dirait que tu demandes au périph de renvoyer son adresse IEEE
$commandIEEE = $eqLogic->getCmd('info', 'IEEE-Addr');
$addrIEEE = strtoupper($commandIEEE->execCmd());

Du coup pourquoi ne pas prendre l'adresse stockée dans config, et peux tu m'expliquer le role de ces 2 appels (getCmd + execCmd) ?
Merci

**Comment by KiwiHC16** [comment]
Depuis le debut, a la reception d'une adresse IEEE celle ci etait envoyée à la commande info IEEE du device. Tout était ok, jusqu'au jour ou je me suis aperçu que cette info pouvait être perdu sur un refresh cache par exemple. Donc au lieu d'utiliser une commande info pour garder l information je la souvegarde dans la configuration.
Mais pour avoir une rétro-compatibilité, j'ai aussi gardé la solution avec la commande. Donc maintenant il y a la commande et la config a mettre a jour en meme temps et si je trouve l info dans l une je la met aussi dans l autre. En esperant avoir fait toutes les modifications necessaire dans le code. Je ne suis pas a l abri d avoir oublié des endroits dans le code.

**Comment by tcharp38** [comment]
Je ne pige pas tout mais si je propose une modif de code pour la page santé qui va d'abord prendre l 'adresse IEEE de la config si elle existe, puis va executer le code courant (getCmd() + execCmd()) si n'existe pas. Ca te conviendrait ?
Ca reste compatible avec le code actuel du coup.

**Comment by KiwiHC16** [comment]
oui

**Comment by tcharp38** [comment]
Poussé !

**Comment by KiwiHC16** [comment]
Mis dans le master.
