### ISSUE TITLE
Batterie capteur luminosité xiaomi

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1264]
https://community.jeedom.com/t/capteur-de-luminosite-xiaomi-gzcgq01lm/18355/33

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Brugal21** [comment]
Salut,

merci d'avoir ouvert une issue rapidement, tu avais déjà l'issue #1166 qui parle de ce problème.
Si tu as besoin d'infos complémentaires, n'hésite pas !

@+

**Comment by KiwiHC16** [comment]
Merci pour l info.
Ok donc je clos pour ne pas dupliquer.
