### ISSUE TITLE
Attention a la casse

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1265]
https://community.jeedom.com/t/incompatibilite-jeedom-v4/37810/5

```
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/Timer/Timer.json
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TRADFRISignalRepeater/TRADFRISignalRepeater.json
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0121/TS0121.json
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/zigbeeDimmablelight/zigbeeDimmablelight.json
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/LOM02/LOM02.json
```

**Comment by KiwiHC16** [comment]
TS0121.json corrigé.
Pas en relation avec cette issue. Erreur de nom de fichier.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Model TRADFRIsignalrepeater/TRADFRIsignalrepeater.json et recherche TRADFRISignalRepeater !!

**Comment by KiwiHC16** [comment]
zigbeeDimmableLight/zigbeeDimmableLight.json et recherche zigbeeDimmablelight.json
Le l minuscule est dans le json pour l icône.

**Comment by tcharp38** [comment]
@KiwiHC16, as tu qq part une description de ce champ ?
Je ne comprends pas le fait qu un module Toto et TOTO ne soient pas le meme.
J'aurais tendance à normaliser ce champ.
Entre parenthese j'ai eu un souci par le passé que tu as patché à cause de ca.

**Comment by KiwiHC16** [comment]
Je ne comprends ce qu il s est passé. Pendant des mois aucun soucis et maintenant j ai l impression que les infos qui remontent sont sensible à la casse. Voir une lettre peut etre minuscule ou majuscule sans raison entre differents systemes...
Si il faut tout passer en strtoupper ca va etre long....

**Comment by tcharp38** [comment]
On peut trouver une solution progressive mais il faut d'abord se mettre d'accord sur cette chaine de description.
@pipiche38 peut peut etre nous dire comment il voit les choses cote plugin.
En résumé peut on passer toutes les chaines en upper case et considerer que 2 produits avec une casse differente sont identiques.

**Comment by KiwiHC16** [comment]
Pipiche developpe un plugin sur un autre systeme. Il ne travaille pas sur Abeille/Jeedom.

**Comment by tcharp38** [comment]
Oui je sais, le plugin de Domoticz. Mais la problématique est la meme qq soit le systeme.

**Comment by pipiche38** [comment]
Pour l'instant on ne fait rien coté caste. La seule chose qui est faite, c'est la suppression du '/'.

Pour ma part, je pense qu'il faudrait combiner 'Manufacturer Name' + 'Model Name' (grosso modo les attributs 0x0004 et 0x0005). Cela devrait régler la plus part des problèmes. 

Pour ceux comme profalux c'est plus compliqué.
