### ISSUE TITLE
Ajout Support Capteur d'ouverture de porte Tuya NEO RH3001

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#1266]
Bonjour,
Suite à l'achat d'un capteur d'ouverture de porte Zigbee Tuya, j'ai tenté de l'ajouter avec le plugin abeille, 
le capteur est bien reconnu mais il y a une erreur  : 

2020-09-29 14:47:34 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0121/TS0121.json will send back default template. |   |  - | -- | -- | -- | --
  | 2020-09-29 14:47:34 | Abeille | Création d un nouvel objet Abeille (Abeille1/e7e0) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5299312/AbeilleParser.log)

Lien du capteur sur Aliexpress : https://www.aliexpress.com/item/4001221425050.html

Qu'as tu besoin comme log ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
RH3001

Il faut faire son modele.

Erreur: TS0121.json corrigé ce jour dans le master.

**Comment by KiwiHC16** [comment]
```
[2020-09-29 15:37:24][debug] Abeille1, Type=8043/Simple descriptor response, SQN=c0, Status=00, ShortAddr=580b, Length=12, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0402 (IAS Zone), BitField=00
[2020-09-29 15:37:24][debug]   InClusterCount=04
[2020-09-29 15:37:24][debug]   InCluster=0000 - General: Basic
[2020-09-29 15:37:24][debug]   InCluster=000a - General: Time
[2020-09-29 15:37:24][debug]   InCluster=0001 - General: Power Config
[2020-09-29 15:37:24][debug]   InCluster=0500 - Security & Safety: IAS Zone
[2020-09-29 15:37:24][debug]   OutClusterCount=01
[2020-09-29 15:37:24][debug]   OutCluster=0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-09-29 à 15 58 41](https://user-images.githubusercontent.com/8549674/94568342-a8ffec00-026c-11eb-87e9-c77ac2c5e7ed.png)

**Comment by KiwiHC16** [comment]
Recuperes le fichier et essayes:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/RH3001

**Comment by Jorael57** [comment]
Pourrais-tu me préciser dans quel répertoire je dois le copier stp ?
/var/www/html/plugins/Abeille/core/config/devices/
ou 
/var/www/html/plugins/Abeille/core/config/devices/Template/

**Comment by KiwiHC16** [comment]
Il faut que tu crée un repertoire core/config/devices/RH3001 et tu mets le json dedans

**Comment by Jorael57** [comment]
J'ai fait ce que tu as demandé, maintenant il se créé correctement mais  : 
-Est ce normal de ne pas avoir de commande pour connaitre l'état de la batterie ?
- savoir si il est alimenté par USB ou via la batterie

Sinon on arrive bien à voir si oui ou non le capteur est ouvert ;)

**Comment by KiwiHC16** [comment]
C est un bon début. Pour le reste il faut investiguer son fonctionnement.

**Comment by Jorael57** [comment]
@KiwiHC16 : Est ce que ça t'aide si je te joins ces données pour chaque cluster du capteur ?
**Basic :**
![image](https://user-images.githubusercontent.com/72082610/105841632-35c97500-5fd5-11eb-80b6-4873a57bc753.png)

**Comment by KiwiHC16** [comment]
Oui bien sûr. Continue à ajouter des infos si tu en trouves.

**Comment by Jorael57** [comment]
Celui idem il fonctionne  mais pas non plus de remontée d'info de la batterie dans Analyse Equipement de Jeedom.

**Comment by tcharp38** [comment]
Peux tu 
- aller sur la page de l'equipement
- assistante EQ
- et faire en sorte que toutes les lignes soient remplis si possible, via le bouton refresh correspondant
- puis drag & drop du discovery.log ici
Merci

**Comment by Jorael57** [comment]
Salut, désolé pour le delai, j'ai essayé la procedure mais rien n'y je n'ai pas mieux que ça : 

{"epCount":1,"endPoints":{"01":{}}}

Une autre idée peut-être ?

**Comment by tcharp38** [comment]
Bon on laisse tomber l assistant.
Essaie avec ca
[RH3001.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7583877/RH3001.zip)

 A decompresser dans core/config/devices/RH3001
puis redemarrer Abeille
et refaire inclusion

Ensuite file moi le package de logs de la page support (telecharger tout)

**Comment by tcharp38** [comment]
Salut @Jorael57 
Ce super vieux sujet t interesse toujours ?

**Comment by tcharp38** [comment]
Pas de reponse. 
Je clos.
A reouvrir si qqn veut bosser la dessus.
