### ISSUE TITLE
Ajout Support Capteur d'ouverture de porte Konke 3AFE280104020015

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#1267]
Bonjour, 
Je continue mes tests ( j'ai plusieurs IoT zigbee à installer) désolé pour le boulot que ça va te demander :/

J'ai acheté des capteurs de porte Konke , j'ai vu que normalement ils sont supporter par abeille mais quand je joins le mien il n'est pas reconnu correctement : 

2020-09-29 16:08:25 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/3AFE280104020015/3AFE280104020015.json will send back default template. |   |  
-- | -- | -- | -- | --
  | 2020-09-29 16:08:25 | Abeille | Création d un nouvel objet Abeille (Abeille1/b5db) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

Le getName donne bien : 3AFE280104020015
Le société et SW ne retournent rien.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Jorael57** [comment]
Salut ,

Meme problème avec le capteur de présence Konke : 


2020-10-01 15:40:38 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/3AFE28010402000D/3AFE28010402000D.json will send back default template. | 
 2020-10-01 15:40:38 | Abeille | Création d un nouvel objet Abeille (Abeille1/0699) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.


Est ce que j'ouvre une autre issue ?

**Comment by Jorael57** [comment]
Je viens de trouver cette page très interessante : https://zigbee.blakadder.com/Konke_KPDR.html
Donc normalement on peut résoudre facilement le problème en copier le répertoire 3AFE130104020015 je suppose

**Comment by Jorael57** [comment]
@KiwiHC16 J'ai copier les fichiers /var/www/html/plugins/Abeille/core/config/devices
Mais maintenant le capteur est créé mais dans les commandes je n'ai meme plus la commande pour avoir son nom.
Je vois que dans le fichier JSON il y a un configuration->uniqId  à quoi cela correspond-t-il ? Je pense que je dois le changer non ?

Voici le fichier abeilleParser
[AbeilleParser_konke.log](https://github.com/KiwiHC16/Abeille/files/5334538/AbeilleParser_konke.log)

**Comment by KiwiHC16** [comment]
configuration->uniqId
Ne sert pas. Il avait ete mis en place au cas ou mais finalement n est pas utilisé.

**Comment by KiwiHC16** [comment]
3AFE28010402000D
n est pas connu par Abeille.
Il faut lui faire son modele.
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices

**Comment by KiwiHC16** [comment]
```
[2020-10-06 16:29:59][debug] Abeille1, Type=8045/Active endpoints response, SQN=22, Status=00, ShortAddr=09a8, EndPointCount=01, EndPointList=; 01
```

**Comment by KiwiHC16** [comment]
```
[2020-10-06 16:30:08][debug] Abeille1, Type=8043/Simple descriptor response, SQN=25, Status=00, ShortAddr=09a8, Length=16, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0402 (IAS Zone), BitField=00
[2020-10-06 16:30:08][debug]   InClusterCount=05
[2020-10-06 16:30:08][debug]   InCluster=0000 - General: Basic
[2020-10-06 16:30:08][debug]   InCluster=0001 - General: Power Config
[2020-10-06 16:30:08][debug]   InCluster=0003 - General: Identify
[2020-10-06 16:30:08][debug]   InCluster=0500 - Security & Safety: IAS Zone
[2020-10-06 16:30:08][debug]   InCluster=fcc0 - 
[2020-10-06 16:30:08][debug]   OutClusterCount=02
[2020-10-06 16:30:08][debug]   OutCluster=0003 - General: Identify
[2020-10-06 16:30:08][debug]   OutCluster=fcc0 - 
```

**Comment by KiwiHC16** [comment]
Avec les infos du log on doit pouvoir faire un modele maintenant.

**Comment by Jorael57** [comment]
@KiwiHC16 
je progresse j'ai ça  actuellement : 
`{
  "3AFE280104020015": {
    "nameJeedom": "Konke Door Sensor",
    "timeout": "60",
    "Categorie": {
      "security": "1"
    },
    "configuration": {
      "uniqId": "5c07c766sd2639b",
      "icone": "3AFE130104020015",
      "battery_type": "1x3V CR1632",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "nom",
      "include3": "etatDoorAlarme",
      "include4 2": "Batterie-Volt-Konke"
    }
  }
}
..`
ça me créé bien le capteur mais j'ai aucun commande qui fonctionne dans l'interface (Name, Battery etc)

**Comment by Jorael57** [comment]
Bon ça ne marche pas complétement : 
les commandes du modèle ci-dessous qui ne remontent rien : 
-etat
-SW
-Batterie Volt
-Power Source

Les autres fonctionnent.
Jeedom ne détecte donc pas l'ouverture ou la fermeture de la porte actuellement.

**Comment by KiwiHC16** [comment]
Mets le demon en debug, redemarre le demon

Fais des manipulations ouverture/fermeture en notant les heures exactes et partages le log AbeilleParser.

**Comment by Jorael57** [comment]
Voilà : 
[AbeilleParser_Konke_Fermeture.log](https://github.com/KiwiHC16/Abeille/files/5341439/AbeilleParser_Konke_Fermeture.log)
[AbeilleParser_Konke_ouverture.log](https://github.com/KiwiHC16/Abeille/files/5341440/AbeilleParser_Konke_ouverture.log)

**Comment by KiwiHC16** [comment]
Tu me demandes un peu de trouver une aiguille dans un botte de foin.

Peux en ssh, faire un
`tail -f AbeilleParser`

Et partager la ligne qui s affiche quand tu ouvres ou quand tu fermes le capteur.

**Comment by Jorael57** [comment]
Comme dis dans l'issue avec le capteur IR , j'ai le même soucis avec ce capteur. Les logs pour l'ouverture et la fermeture sont bien uniquement la partie généré par l'action que j'ai faite ( j'avais clean le log à chaque fois).

et Abeille /b5db c'est le capteur d'ouverture de porte.

Je ne peux pas faire moins de log. ( je ne sais pas pourquoi ça génère des getNE et des configureNE

**Comment by Jorael57** [comment]
Alors est ce que c'est parce que j'ai copié le json de l'id qui fonctionne ?

**Comment by tcharp38** [comment]
@Jorael57 
Quel est la situation sur ce periph ? Toujours des soucis ?
Merci

**Comment by Jorael57** [comment]
à la dernière tentative je n'arrivais plus à les appairer avec la zigate. Il faut que je réessaye.

**Comment by tcharp38** [comment]
Si c'est le encore le cas alors peux tu suivre les etapes suivantes
- Si pas deja fait: mode debug + 5000 lignes de log au lieu de 500
- Redemarrer Abeille
- Nouvelle inclusion
- Drag & drop ici du package de logs (page support/telecharger tout)
Merci

**Comment by tcharp38** [comment]
@Jorael57 
Des news ?

**Comment by Jorael57** [comment]
Oui il faut que je change les batteries de mes konke tous est à plats :/

**Comment by tcharp38** [comment]
Ok. On refait le point apres.
Normalement j'avais ajouté dans la page "santé", le dernier etat de la batterie et dernier LQI aussi.

**Comment by tcharp38** [comment]
Salut @Jorael57 
Toujours interessé par cet antique sujet ?

**Comment by tcharp38** [comment]
Je clos.
A réouvrir si ca interesse qqn
