### ISSUE TITLE
A chaque reboot à froid abeille ne pointe pas su le bon port USB

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#1269]
Bonjour,
Depuis plusieurs mois, après chaque reboot à froid Abeille pointe sur l'USB du RFplayer et ce quelque soit la position du module Zigbee (USB0/USB1)..
Après un reboot à chaud, je n'ai pas ce problème.
Merci,
Ivan

**Comment by tcharp38** [comment]
Salut
Je vois que tu n'as pas eu de reponses sur le sujet.
Je pense que ton souci est lié au kernel et sa façon d'affecter les ports au démarrage.
Le plugin abeille ne supporte pas ports dynamiques.

Un sujet similaire est celui ci
https://community.jeedom.com/t/zigate-sur-un-autre-port-apres-coupure-secteur/22555/3

Mais ton sujet me semble mal enoncé. Abeille ne change jamais de port tout seul. Donc qu'entends tu par "ne pointe pas sur le bon port" ? Il y avait quoi avant le reboot et quoi apres ?

**Comment by ivan9187** [comment]
Bonjour
Effectivement c'est un pb de port dynamique..
Merci
