### ISSUE TITLE
Ajout Support Capteur d'ouverture de porte Tuya  zemismart TS0203

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#1270]
Après ajout dans Abeille :

2020-10-01 15:56:41 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0203/TS0203.json will send back default template.
| 2020-10-01 15:56:41 | Abeille | Création d un nouvel objet Abeille (Abeille1/8a4e) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

lien vers le capteur : 
https://www.aliexpress.com/item/4000405556917.html

[AbeilleParser_a74e.log](https://github.com/KiwiHC16/Abeille/files/5312863/AbeilleParser_a74e.log)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-10-06 à 17 02 11](https://user-images.githubusercontent.com/8549674/95219469-b0d40900-07f5-11eb-923c-a2a340ddc1b4.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2020-10-01 16:43:33][debug] Abeille1, Type=8102/Attribut report, SQN=2f, SrcAddr=a74e, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006, DataByteList=TS0203
```

```
[2020-10-01 16:43:39][debug] Abeille1, Type=8043/Simple descriptor response, SQN=63, Status=00, ShortAddr=a74e, Length=12, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0402 (IAS Zone), BitField=01
[2020-10-01 16:43:39][debug]   InClusterCount=03
[2020-10-01 16:43:39][debug]   InCluster=0000 - General: Basic
[2020-10-01 16:43:39][debug]   InCluster=0001 - General: Power Config
[2020-10-01 16:43:39][debug]   InCluster=0500 - Security & Safety: IAS Zone
[2020-10-01 16:43:39][debug]   OutClusterCount=02
[2020-10-01 16:43:39][debug]   OutCluster=0019 - General: OTA
[2020-10-01 16:43:39][debug]   OutCluster=000a - General: Time
```

**Comment by KiwiHC16** [comment]
Il faut faire le fichier json modele maintenant.

**Comment by Jorael57** [comment]
@KiwiHC16 Une mise à jour de la doc pour la creation des devices JSON serait pas mal pour aider, je l'ai lu mais ça ne m'aide pas beaucoup.

Par exemple pour ce capteur, que mettre dans les commandes (à part les basiques Societe, nom etc..)
Je prends tous ce qui pourrait servir dans Templates et je testes empiriquement ?

Ou il y a un autre endroit qui permette de faire le lien entre ?

**Comment by KiwiHC16** [comment]
Rien n'est facile. Soit:
- tu parviens a recevoir des infos dans AbeilleParser en jouant avec le module
- soit tu vas sur le net pour voir si qq d autre a des infos
- soit tu sniff le zigbee
- ...

Ensuite dans le meilleur des cas il faut "juste" faire un modele  (JSON), soit ce n'est pas suffisent et il faut faire du code....

**Comment by Jorael57** [comment]
En jouant avec le capteur, abeilleParser : 

> [2020-10-07 16:09:34][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=2f, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0000, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:42][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=30, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0001, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:51][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=31, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0000, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:53][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=32, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0001, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:55][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=33, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0000, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:57][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=34, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0001, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:09:59][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=35, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0000, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:10:04][debug] Abeille1, Type=8401/IAS Zone status change notification, SQN=36, EndPoint=01, ClusterId=0500, SrcAddrMode=02, SrcAddr=a74e, ZoneStatus=0001, ExtStatus=00, ZoneId=00, Delay=0000
[2020-10-07 16:10:23][debug] Abeille1, Type=8000/Status, Status=00-(Success), SQN=00, PacketType=0010
[2020-10-07 16:10:23][debug] Abeille1, Type=8010/Version, Appli=3, SDK=031a

**Comment by KiwiHC16** [comment]
```
ZoneStatus=0000
ZoneStatus=0001
```

Donc l info remonte bien. Il faut ajouter la commande info qui va bien.

**Comment by KiwiHC16** [comment]
Peux tu recuperer le modele et essayer ?
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TS0203

**Comment by Jorael57** [comment]
Alors cela fonctione pour savoir si l'etat est ok ou non mais par contre par de retour d'information pour la batterie.

**Comment by KiwiHC16** [comment]
Voila un bon debug.
Peux tu mettre le plugin en mode debug, redemarrer le daemon, puis laisser tourner 24h. Ensuite tu partages AbeilleParser en me donnant l adresse courte de l equipement.

**Comment by tcharp38** [comment]
@Jorael57 
Quel est le status de ce périphérique ? Toujours des soucis ?
Merci

**Comment by Jorael57** [comment]
Alors il fonctionne correctement maintenant sauf la remontée d'information concernant l'état de charge de la batterie ( dans Analyse équipement.)

**Comment by tcharp38** [comment]
Donc meme question en utilisant l'assistant de découverte:
Peux tu

- aller sur la page de l'equipement
- assistante EQ
- et faire en sorte que toutes les lignes soient remplis si possible, via le bouton refresh correspondant
- puis drag & drop du discovery.log ici

Merci

**Comment by Jorael57** [comment]
J'ai essayé la procédure mais le discovery.json est vide ( que ce soit sur ce capteur ou sur les autres) 
Sur la page assistant EQ j'ai presque rien comme information : 
![image](https://user-images.githubusercontent.com/72082610/132198821-b56a24cb-16fc-4458-b5fd-ba950f19b10c.png)

ps: J'ai vérifé que le capteur soit bien dans le reseau au moment de faire la manip.

**Comment by tcharp38** [comment]
Le capteur etant sur piles, l'as tu réveillé au fur et à mesure des requetes ?

**Comment by Jorael57** [comment]
Oui c'est un capteur qui est sur une porte de couloir ouverte plusieurs fois par jour en ce moment, je viens de refaire la manip juste après avoir vérifier que le capteur envoyait bien son etat à jeedom et j'ai le même resultat fichier discovery vide.

**Comment by Jorael57** [comment]
J'ai ça dans abeilleDebug.log
```

> [2021-09-06 11:53:35] CliToQueue: type:sendToCli_net:Abeille1_addr:9FE7_ieee:BC33ACFFFE058272
> [2021-09-06 11:53:35] CliToQueue: {"type":"sendToCli","net":"Abeille1","addr":"9FE7","ieee":"BC33ACFFFE058272"}
> [2021-09-06 11:53:35] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 11:53:41] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 12:01:00] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 12:01:00] CliToQueue: type:sendToCli_net:Abeille1_addr:9FE7_ieee:BC33ACFFFE058272
> [2021-09-06 12:01:00] CliToQueue: {"type":"sendToCli","net":"Abeille1","addr":"9FE7","ieee":"BC33ACFFFE058272"}
> [2021-09-06 12:01:06] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 12:24:57] QueueToCli: msg={"src":"parser","type":"attributeReport","net":"Abeille1","addr":"9FE7","ep":"01","clustId":"0001","attrId":"0021","status":"00","value":100}
> [2021-09-06 12:24:59] QueueToCli: msg={"src":"parser","type":"attributeReport","net":"Abeille1","addr":"9FE7","ep":"01","clustId":"0001","attrId":"0021","status":"00","value":100}
> [2021-09-06 12:25:42] CliToQueue: type:sendToCli_net:Abeille1_addr:9FE7_ieee:BC33ACFFFE058272
> [2021-09-06 12:25:42] CliToQueue: {"type":"sendToCli","net":"Abeille1","addr":"9FE7","ieee":"BC33ACFFFE058272"}
> [2021-09-06 12:25:42] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 12:25:44] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7
> [2021-09-06 12:30:06] CliToQueue: topic=CmdAbeille1/9FE7/ActiveEndPoint, payload=address=9FE7

```

**Comment by tcharp38** [comment]
Ce genre de capteur s'endort l'essentiel de son temps pour economiser la batterie. Du coup il n'est pas capable de recevoir une requete. Il se reveille juste lorsqu'il a besoin (changement etat porte ou report d etat batterie).
Bref, tu dois le reveiller juste au meme moment ou tu lances les requetes de decouverte sinon aucune chance qu'il reponde.

**Comment by Jorael57** [comment]
Alors effectivement j'ai fait les 2 actions dans la même seconde (pas forcement evident) et voici ce que j'ai obtenu : 

`

> {"epCount":1,"endPoints":{"01":{}}}

`

**Comment by tcharp38** [comment]
Une fois installé sur la porte oui je comprends.
Mais du coup tu t'en sers comment si il n'est pas supporté ?

Il manque des tas d'infos. Il faut parfois relancer le refresh pour les autres points jusqu'a avoir une reponse

**Comment by Jorael57** [comment]
bah la fonction de base à savoir si la porte est ouverte ou fermée fonctionne :)
 Donc du coup il faut que je le fasse plein de fois jusqu'à avoir plus de chose ?

**Comment by tcharp38** [comment]
Oui pour qu'il collecte un max d infos de decouverte il faut le reveiller plusieurs fois je pense.
C'est pas l'idéal j avoue mais c'est le meilleur moyen d'avoir une vue d'ensemble.

**Comment by Jorael57** [comment]
Voilà ce que j'ai réussi à avoir : 
[discovery_1.json.txt](https://github.com/KiwiHC16/Abeille/files/7117831/discovery_1.json.txt)

Question c'est pas ces données là qu'on peut avoir plus facilement via Deconz /Conbee  ?

**Comment by tcharp38** [comment]
Tiens.
[TS0203__TZ3000_f1hmoyj4.zip](https://github.com/KiwiHC16/Abeille/files/7119936/TS0203__TZ3000_f1hmoyj4.zip)

A decompresser dans "core/config/devices"
puis redemarrer Abeille
et refaire une inclusion

J'ai ajouté le report de batterie.

Note qu'il manque toujours (n'est ce pas ?) une icone qui va bien. 
Je te laisse me trouver une image au format PNG sans fond.

Concernant ta question

> Question c'est pas ces données là qu'on peut avoir plus facilement via Deconz /Conbee ?

Je ne connais pas leur interface alors peut etre que c'est + pratique. A toi de me dire. Mais le reveil de l'equipement sera obligatoire quand meme, à moins de faire toute cette interrogation pendant la phase d'inclusion.

**Comment by Jorael57** [comment]
Celle -ci ne va pas ? 
https://user-images.githubusercontent.com/8549674/95219469-b0d40900-07f5-11eb-923c-a2a340ddc1b4.png

J'ai fait la manip mais de réinclusion ( faut-il supprimer avant ?) mais le capteur n'apparait toujours pas dans analyse equipement pour son taux de batterie

**Comment by tcharp38** [comment]
La batterie remonte 1 fois par H seulement.
Peux tu me filer le package de logs que le vois si qqch s'est mal passé ?

Pour le PNG je vais prendre le tient mais idealement il faudrait sans arriere plan.

Y a t'il un modele ou ref donné avec ce capteur Zemismart ?

Enfin, quel est le type de batterie ?

**Comment by Jorael57** [comment]
Voici les seuls infos disponibles.
![image](https://user-images.githubusercontent.com/72082610/132336833-8b302422-25aa-4b70-9252-9750e61a0729.png)

**Comment by tcharp38** [comment]
Parfait: model ZXZDS, battery CR2032 donc 3V

D'ailleurs capteur Zemismart meme si fabrication generique de Tuya.

**Comment by tcharp38** [comment]
La 210907-BETA-1 contient le support actuel

**Comment by tcharp38** [comment]
Ou en est on ?

**Comment by Jorael57** [comment]
Pareil que l'autre toujours pas de remontée d'informations  de la batterie dans analyse équipement.

**Comment by tcharp38** [comment]
Meme souci.
Le bon fichier est celui ci mais reinclusion ou recharger JSON au minimum
[TS0203__TZ3000_f1hmoyj4.zip](https://github.com/KiwiHC16/Abeille/files/7153760/TS0203__TZ3000_f1hmoyj4.zip)

**Comment by Jorael57** [comment]
Bon bah je ferme on a bien le retour du pourcentage de la batterie, merci ;)
