### ISSUE TITLE
Ajout Support Interrupteur sans fil Zemismart 2 boutons Tuya TS0042

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#1272]
2020-10-01 19:35:50 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0042/TS0042.json will send back default template. 
2020-10-01 19:35:50 | Abeille | Création d un nouvel objet Abeille (Abeille1/1163) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

Lien vers le produit : https://www.aliexpress.com/item/4001227549409.html

[AbeilleParser_TS0042.log](https://github.com/KiwiHC16/Abeille/files/5313881/AbeilleParser_TS0042.log)

**Comment by Jorael57** [comment]
ps : Est ce qu'il y a un moyen de t'aider un peu plus que ça pour l'intégration de nouveaux capteurs ? genre pour te pré-macher le travail voir te fournir directement de quoi intégrer direct les capteurs ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Regardes la doc: http://kiwihc16.free.fr/ModeleJson.html
pour faire un modele.
Malheuresement cette doc est vieille et donc pas à jour mais elle peut aider.

**Comment by KiwiHC16** [comment]
```
[2020-10-01 19:35:50][debug] Abeille1, Type=8102/Attribut report, SQN=b3, SrcAddr=1163, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006, DataByteList=TS0042
```

```
[2020-10-01 19:35:58][debug] Abeille1, Type=8043/Simple descriptor response, SQN=90, Status=00, ShortAddr=1163, Length=10, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0000 (On/Off Switch), BitField=00
[2020-10-01 19:35:58][debug]   InClusterCount=03
[2020-10-01 19:35:58][debug]   InCluster=0000 - General: Basic
[2020-10-01 19:35:58][debug]   InCluster=0001 - General: Power Config
[2020-10-01 19:35:58][debug]   InCluster=0006 - General: On/Off
[2020-10-01 19:35:58][debug]   OutClusterCount=01
[2020-10-01 19:35:58][debug]   OutCluster=0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-10-06 à 17 07 39](https://user-images.githubusercontent.com/8549674/95220152-728b1980-07f6-11eb-9fdf-13309fd22988.png)

**Comment by Jorael57** [comment]
@KiwiHC16 J'essaie ça (copié du TS0043) : 
 
{
  "TS0042": {
    "nameJeedom": "Switch Zemismart TS0042 2 boutons sur piles",
    "timeout": "60",
    "Comment": "https://github.com/KiwiHC16/Abeille/issues/1272",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5ceosfqsdshjextssdgdfzsddzze5d43",
      "icone": "TS0042",
      "mainEP": "01"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "societe",
      "include3": "nom",
      "include5": "On",
      "include5 2": "On1",
      "include6": "Off",
      "include6 2": "Off1",
      "include8": "getEtat",
      "include9": "getManufacturerName",
      "include10": "getModelIdentifier"
    }
  }
}

**Comment by Jorael57** [comment]
Bon ça n'a pas l'air de fonctionner.
Je ne peux meme pas créer un scenario avec pour allumer un lumière si j'appuis sur l'un des boutons.



![Clipboard03](https://user-images.githubusercontent.com/72082610/95237115-14673200-0808-11eb-82e8-e9467bda02a6.jpg)

**Comment by KiwiHC16** [comment]
Quand tu appuis as tu quelque chose dans AbeilleParser (mode debug) ?

**Comment by Jorael57** [comment]
A priori je dirais que non j'ai ça qui c'est affiché dans abeilleParser mais pas du tout au même moment que mes appuies sur les boutons.:

> [2020-10-07 15:54:22][debug] Abeille1, Type=8000/Status, Status=00-(Success), SQN=00, PacketType=0010
> [2020-10-07 15:54:22][debug] Abeille1, Type=8010/Version, Appli=3, SDK=031a
> [2020-10-07 15:54:26][debug] Abeille1, Type=8000/Status, Status=00-(Success), SQN=00, PacketType=0009
> [2020-10-07 15:54:26][debug] Abeille1, Type=8009/Network state response, ShortAddr=0000, ExtAddr=00158D0001EDE7DC, PANId=2556, ExtPANId=e1cd2c03688a579f, Channel=15
> [2020-10-07 15:55:13][debug] Abeille1, Type=8102/Attribut report, SQN=d9, SrcAddr=df68, EndPoint=01, ClustID=0000, AttrID=ff01, AttrStatus=00, AttrDataType=42, AttrSize=002b, DataByteList=6410000328229839000000009539b72b9240052137009a2000082122130727000000000000000009210104
> [2020-10-07 15:55:13][debug]   Champ proprietaire Xiaomi (Wall Plug)  OnOff=0, Puissance=0, Consommation=4.5678362846375

Donc ça voudrait dire que ce switch n'est pas supporter par la Zigate ?

**Comment by KiwiHC16** [comment]
#1185 => En passant la zigate en mode hybride ca fonctionne. Sera dispo dans la prochaine stable. Et il faut firmware 3.1D.
#1406

**Comment by Jorael57** [comment]
Bonsoir @KiwiHC16 ,
Après un peu de recherche sans trouver de réponse il faut faire quoi pour passer la Zigate en mode hybride ?

**Comment by Jorael57** [comment]
C'est bon j'ai trouvé comment il fallait faire pour la mettre en hybride, je continue mes tests alors :)

**Comment by Jorael57** [comment]
@KiwiHC16 
C'est bon ça à l'air de fonctionner , bien qu'il me semble beaucoup moins réactif que l'équivalent chez Xiaomi Aquara

Il manque plus que le retour d'info batterie mais je ne sais pas si il le fait vu ce que je vois avec la conbee 2  ( Je ne sais pas si c'est la Conbee qui ne lit pas bien les infos ou autre chose) : 

![image](https://user-images.githubusercontent.com/72082610/106133712-ef575000-6165-11eb-92f9-6605006d8dab.png)
Node Infos : 
![image](https://user-images.githubusercontent.com/72082610/106134598-077b9f00-6167-11eb-93e9-3cf0f26d3999.png)

Basic 01 : 
![image](https://user-images.githubusercontent.com/72082610/106133772-00a05c80-6166-11eb-9734-1cd6fb858a6a.png)

Power Configuration Cluster 01 : 
![image](https://user-images.githubusercontent.com/72082610/106133894-23cb0c00-6166-11eb-8e7a-7339d9179176.png)

On/Off Cluster 01 : 
![image](https://user-images.githubusercontent.com/72082610/106134365-b9669b80-6166-11eb-939a-691ecbbbeb8d.png)
![image](https://user-images.githubusercontent.com/72082610/106134422-cd120200-6166-11eb-8552-938dbdd20c22.png)


OTAU Cluster 01 : 
![image](https://user-images.githubusercontent.com/72082610/106134477-e0bd6880-6166-11eb-96ba-6892ff65ebc9.png)
![image](https://user-images.githubusercontent.com/72082610/106134523-eb77fd80-6166-11eb-8f7b-84b276c797ce.png)

Voilà 

On a sensiblement la même chose pour la partie 02.

**Comment by KiwiHC16** [comment]
Je viens de relire le chat dans ton modele du 6 oct il manque juste l etat.

Peux tu essayer avec:

{
  "TS0042": {
    "nameJeedom": "Test Utilisateur",
    "timeout": "60",
    "Comment": "https://github.com/KiwiHC16/Abeille/issues/1272",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5ceosfqsds766ssdgdfzsddzssdsfsze5d44",
      "icone": "TS0042",
      "mainEP": "01"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "societe",
      "include3": "nom",
      "include4": "etatCharge0",
      "include5": "On",
      "include6": "Off",
      "include8": "getEtat",
      "include9": "getManufacturerName",
      "include10": "getModelIdentifier"
    }
  }
}

Tu devrais avoir le premier bouton qui fonctionne. Peux tu confirmer ?

Quelle version de firmware ziaget as tu ?

**Comment by Jorael57** [comment]
Firmware le dernier 3.1d je crois.
Avec l'ancien Model les 2 boutons fonctionnaient, mais pas de retour de l'état de la batterie ( Tension % de charge/decharge de la batterie) comme sur un xiaomi Aquara

Par contre là avec ce modèle le clic bouton gauche ne fonctionne qu'une seul fois.

**Comment by KiwiHC16** [comment]
Peux tu mettre le plugin en debug, redémarrer le daemon et partager les messages qui passent dans AbeilleParser.log quand tu appuis sur les boutons de l inter ?

**Comment by tcharp38** [comment]
@Jorael57 
Je reviens sur ce vieux sujet. Il y a encore des soucis ou on peut clore ?
Merci

**Comment by Jorael57** [comment]
Les boutons fonctionnent oui , il a tendance à sortir du reseau puis revenir tous seul.
Mais  pas de remontée d'information pour la batterie. 
Je ne sais pas si c'est lié au capteur ou si ils vous manquent des infos pour que ces données remontent ?

**Comment by Jorael57** [comment]
@tcharp38 
J'ai pas réussi à avoir plus le end point 2 ne s'étant pas remplis et après plus rien.
Sinon dans l'autre sujet je te demandais pour les infos issue de Deconz regarde les captures plus haut que j'avais faite 
`

> {"epCount":2,"endPoints":{"01":{"servClusters":{"0000":{"attributes":{"0004":{"value":"_TYZB02_keyjhapk"},"0000":{"value":3},"0001":{"value":68},"0002":{"value":0},"0003":{"value":0},"0005":{"value":"TS0042"},"0006":{"value":""},"0007":{"value":"03"},"FFFD":{"value":1}},"commandsReceived":[]},"0001":{"attributes":{"0000":{"value":0},"0020":{"value":0},"0021":{"value":0},"FFFD":{"value":1}},"commandsReceived":[]},"0006":{"attributes":{"0000":{"value":1},"FFFD":{"value":1}},"commandsReceived":["00","01","02","40","41","42"]}},"cliClusters":{"0019":{"attributes":{"0000":{},"0001":{},"0006":{},"FFFD":{}}}}},"02":{}},"powerSource":"battery"}

`

**Comment by tcharp38** [comment]
[TS0042__TYZB02_keyjhapk.zip](https://github.com/KiwiHC16/Abeille/files/7122073/TS0042__TYZB02_keyjhapk.zip)

A decompresser dans "core/config/devices"
puis redemarrer Abeille
et refaire inclusion

Report de la batterie toute les H

D'ailleurs quel type de batterie ?
Et il y a un nom de modele ou ref ?

**Comment by Jorael57** [comment]
Nom de modele sur le pcb : YC-ZS-LO3C-A V1.2
Batterie : CR2032

Manip faite je verais demain si ça apparait. Merci.

**Comment by tcharp38** [comment]
@Jorael57 
Quel est le status ?

**Comment by Jorael57** [comment]
Alors soit j'ai mal fait soit ça ne marche pas, je n'ai aucune remontée d'infos de la batterie dans analyse équipement

**Comment by tcharp38** [comment]
Ha j'ai compris. J'ai fixé des trucs mais surement encore sur la beta.
Le bon fichier est celui ci mais beta ou pas il te faut refaire une inclusion ou recharger le JSON.
[TS0042__TYZB02_keyjhapk.zip](https://github.com/KiwiHC16/Abeille/files/7153749/TS0042__TYZB02_keyjhapk.zip)

Ma faute.

**Comment by Jorael57** [comment]
Donc si je passe sur la beta c'est bon ? ( plus la ré-inclusion bien sur)

**Comment by tcharp38** [comment]
Ca devrait. En tout cas tu sera sur la version la plus avancée.

**Comment by tcharp38** [comment]
Salut @Jorael57 
On en est ou ?

**Comment by Jorael57** [comment]
Je viens de refaire la manip d'inclusion et le rechargement du json plus qu'à attendre un peu.

**Comment by Jorael57** [comment]
Par contre toujours rien pour celui là :(

**Comment by tcharp38** [comment]
Ok donc on cherche toujours à faire foncitonner le retour de batterie.

Peux à l'occase me generer un "discovery.json" ? (https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee)

A part ca on va verifier 2 choses: le binding et le reporting
Via la page EQ/avancé, interroge la table de binding
![image](https://user-images.githubusercontent.com/35221038/142915452-423aa3ce-133f-42fd-998e-e59776c0a5b0.png)

puis le reporting
![image](https://user-images.githubusercontent.com/35221038/142915628-97695e0f-bb5f-4db4-9e4d-de560c717796.png)

ATTENTION: Comme ce périph fonctionne sur batterie, pense à le reveiller apres chaque interrogation.
Et file moi ton package de logs

Merci

**Comment by tcharp38** [comment]
Salut @Jorael57 
Ce sujet t interesse toujours ?

**Comment by tcharp38** [comment]
Antique sujet sans vie.
Je ferme mais à réouvrir si besoin.
