### ISSUE TITLE
Fonctionalites 'supprimer' & 'exclure"

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1273]
Salut @KiwiHC16 
Peux tu me dire ce que tu comptais faire avec les boutons suivants ?
Quelle difference entre 'supprimer'" et "exclure" ?

![image](https://user-images.githubusercontent.com/35221038/94998095-b7713f00-05af-11eb-95d4-9e3c399af627.png)

J'aurai surement d'autres questions apres.

**Comment by KiwiHC16** [comment]
Comme on peut sélectionner les équipements je pensais ajouter la possibilité de supprimer au Au lieu de devoir aller dans chaque équipement et de faire supprimer. 

Cela serait super pratique surtout pour le développement car il n'est pas rare de créer a mainte reprise des équipements et de devoir les supprimer pour tester les nouvelles fonctionnalités et le développement en cours. ￼ ￼

L'idée était de utiliser la possibilité de sélectionner des équipements pour leur appliquer à tous une action￼

**Comment by tcharp38** [comment]
> Comme on peut sélectionner les équipements je pensais ajouter la possibilité de supprimer au Au lieu de devoir aller dans chaque équipement et de faire supprimer.
> 

Ok mais ce mode de suppression ne supprime l'equipement qu'au niveau Jeedom et en aucun cas Zigate n'est ce pas ?
Ce qui veut dire que si tu lances une inclusion et appuis sur le bouton de ton equipement il se retrouve reinclus.
C'est ce que j'observe. 
En ligne ?

> Cela serait super pratique surtout pour le développement car il n'est pas rare de créer a mainte reprise des équipements et de devoir les supprimer pour tester les nouvelles fonctionnalités et le développement en cours. ￼ ￼
> 

C'est clair. J'ai déja développé ca mais je suis coincé sur la suppression de l 'info dans la zigate.

> L'idée était de utiliser la possibilité de sélectionner des équipements pour leur appliquer à tous une action￼

C'est en cours.
Je sais déja supprimer des equipements selectionnés, mais comme je t'ai inqidué, ca se limite à la DB Jeedom. La Zigate elle les connait toujours.

**Comment by KiwiHC16** [comment]
Oui l'idée était de faire les actions qu'au niveau de la base de données de Jeedom et en aucun cas au niveau de la zigate. 

On peut imaginer par exemple pouvoir sélectionner plusieurs équipements et définir leur timeout￼￼ etc

**Comment by tcharp38** [comment]
Donc des actions juste pour "developpeur" et pas pour les utilisateurs finaux.
Peux tu lister celles que tu as en tete par priorite ?

Et du coup cote "Supprimer" ou "exclure" pour l'utilisateur final je sais pas ce que tu en penses mais voila mon point de vue en fonction de ce que j'ai compris:
- pour un utilisateur supprimer = exclure. Donc a virer de jeedom ET de la zigate
- pour le cote zigate on ne peut virer que les equipements sur secteur. Ceux sur batterie doivent demander eux meme de quitter.
Ok avec ca ?

**Comment by tcharp38** [comment]
Je viens de pousser la fonctionalite developpeur "supprimer de Jeedom" pour les eq selectionnés.

J'ai besoin qu'on clarifie la fonction utilisateur de suppression/exclusion.
Tu l'as documenté qq part ?

**Comment by KiwiHC16** [comment]
Je viens de mettre dans le master le PR pour la fonction supprime.
La doc est accessible à http://kiwihc16.free.fr
Les sources sont : https://github.com/KiwiHC16/AbeilleDocSphinx

**Comment by KiwiHC16** [comment]
```
J'ai besoin qu'on clarifie la fonction utilisateur de suppression/exclusion.
Tu l'as documenté qq part ?
```

Non pas de doc specifique.

**Comment by tcharp38** [comment]
Ca s'est bien eclairci depuis donc j'ai les billes et je dois faire encore qq tests.

**Comment by KiwiHC16** [comment]
https://zigate.fr/documentation/commandes-zigate/
Commande: 0x0026 | Remove Device | <target short address: uint64_t>

Il faut envoyer un message sur la queue: queueKeyAbeilleToCmd
Avec la commande Remove et l adresse IEEE de l equipement.
        if ( isset($Command['Remove']) && isset($Command['IEEE']) )

**Comment by tcharp38** [comment]
Remplacé par #1770
