### ISSUE TITLE
Problème ampoule GU10 Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1276]
https://community.jeedom.com/t/probleme-ampoule-gu10-ikea/38257

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Pas de vie, pas d'infos.
Je clos
