### ISSUE TITLE
 Ajout Support Capteur de presence IR  Konke 3AFE28010402000D

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#1281]
Demande d'Ajout du support du capteur de présence Konke 3AFE28010402000D

[AbeilleParser_Konke_IR.log](https://github.com/KiwiHC16/Abeille/files/5341527/AbeilleParser_Konke_IR.log)

> {
  "3AFE28010402000D": {
    "nameJeedom": "Konke IR INfra Rouge Presence",
    "timeout": "60",
    "Categorie": {
      "security": "1"
    },
    "configuration": {
      "uniqId": "5c07c766gyyd264bf",
      "icone": "3AFE14010402000D",
      "battery_type": "1x3V CR2450",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "nom",
      "include3": "etatIR_Alarme",
      "include4 2": "Batterie-Volt-Konke"
    }
  }
}

**Comment by Jorael57** [comment]
La détection de présence n'est pas correctement remonté dans Jeedom

Quand on joue avec : 
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5341581/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Cet équipement n'est pas dans Abeille. Actuellement.
Si je comprends bien le JSON proposé ci dessus est une premiere version pour essayer d avoir ce produit dans Abeille. Est ce bien cela ?

**Comment by KiwiHC16** [comment]
Dans log:
```
[2020-10-07 16:43:19][debug] Abeille1, Type=8045/Active endpoints response, SQN=49, Status=00, ShortAddr=c6a2, EndPointCount=01, EndPointList=; 01
...
[2020-10-07 16:43:21][debug] Abeille1, Type=8102/Attribut report, SQN=9c, SrcAddr=c6a2, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0010, DataByteList=3AFE28010402000D
...
[2020-10-07 16:43:29][debug] Abeille1, Type=8043/Simple descriptor response, SQN=4f, Status=00, ShortAddr=c6a2, Length=16, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0402 (IAS Zone), BitField=00
[2020-10-07 16:43:29][debug]   InClusterCount=05
[2020-10-07 16:43:29][debug]   InCluster=0000 - General: Basic
[2020-10-07 16:43:29][debug]   InCluster=0001 - General: Power Config
[2020-10-07 16:43:29][debug]   InCluster=0003 - General: Identify
[2020-10-07 16:43:29][debug]   InCluster=0500 - Security & Safety: IAS Zone
[2020-10-07 16:43:29][debug]   InCluster=fcc0 - 
[2020-10-07 16:43:29][debug]   OutClusterCount=02
[2020-10-07 16:43:29][debug]   OutCluster=0003 - General: Identify
[2020-10-07 16:43:29][debug]   OutCluster=fcc0 - 
```

**Comment by Jorael57** [comment]
J'ai simplement copier et modifier le json du capteur IR konke reference Zigbee ID: "3AFE14010402000D"; sensé déjà fonctionné avec abeille si je ne me trompe pas.

Il en exite 2 autres :  "3AFE27010402000D"; "3AFE28010402000D"

https://zigbee.blakadder.com/Konke_KPBS.html

**Comment by KiwiHC16** [comment]
Peux tu partager un log AbeilleParser quand tu le declenche ?

**Comment by Jorael57** [comment]
Mon 2eme commentaire contient le log AbeilleParser quand je le déclenche. 
Je ne sais pas pourquoi mais ça génère tout ce log à chaque fois  et c'est pareil pour le capteur de porte. Je ne peux pas te le réduire plus que ça. j'ai fait plusieurs tentatives et à chaque fois ça génère tout ça avec les mêmes séquences.

je n'ai pas regardé dans le détails mais ça génère des configureNE 
abeille1 c6a2 c'est le capteur IR Konke

**Comment by KiwiHC16** [comment]
Si ca genere des configureNE c'est que tu fais une inclusion.
Moi je voudrais le log quand tu ouvres la porte.
Ca ne devrait generer qu'une ligne.

**Comment by Jorael57** [comment]
J'ai réessayé en prenant soin de vérifier que la zigate n'était pas en mode inclusion, ça ne change rien j'ai la même chose dans les logs. (le configureNE)

le problème maintenant c'est que je n'arrive même plus à les inclure à la zigate les capteurs Konke... je ne comprends pas pourquoi...  J'ai meme fait un reset de la zigate ...

**Comment by KiwiHC16** [comment]
Est ce que ta zigate est bien sur les canaux acceptés par Konke. Je crois me souvenir 15 et 20 ou un truc du genre.

**Comment by Jorael57** [comment]
Voici les infos obtenus via Deconz : 
![image](https://user-images.githubusercontent.com/72082610/106180318-70c9d500-619c-11eb-8701-f1637a1f7713.png)

Node Infos : 
![image](https://user-images.githubusercontent.com/72082610/106179860-e4b7ad80-619b-11eb-8eee-2fab03bab310.png)

Basic Cluster : 
![image](https://user-images.githubusercontent.com/72082610/106179982-04e76c80-619c-11eb-872f-15688ff63191.png)

Power Configuration Cluster : 
![image](https://user-images.githubusercontent.com/72082610/106180054-1d578700-619c-11eb-9ca3-32e14a3f9458.png)

Identify Cluster : 
![image](https://user-images.githubusercontent.com/72082610/106180203-47a94480-619c-11eb-9527-9d684cb8216b.png)

IAS Zone : 
![image](https://user-images.githubusercontent.com/72082610/106180278-64457c80-619c-11eb-8fef-35fc1dbabc08.png)

Ma zigate est actuellement sur le channel 11 normalement channel accepté. (C'est surement pour ça qu'à ce moment là je n'arrivais pas à refaire inclusion (après le reset)

Konke devices only work on Zigbee channel 15, 20 and 25. (On Zigate they will work on channel 11, but first they must be paired on channel 15. After that switch the Zigate to channel 11 and the device will follow automatically)

**Comment by Jorael57** [comment]
Je repasserais la Zigate  sur le channel 20 pour rééssayer demain (ma conbee est sur la 15)

**Comment by tcharp38** [comment]
Salut @Jorael57 
Tu es toujours interessé par ce tres vieux sujet ?

**Comment by Jorael57** [comment]
Salut,

Toujours pas changé les piles des capteurs car manque de temps depuis 
pas mal de temps. Donc oui il faudra mais je ne sais pas quand. (au pire 
ferme et j'ouvrirais à nouveau quand je prendrais le temps de le faire)

Jorael.


Le 2022-07-27 15:01, Tcharp38 a écrit :

**Comment by tcharp38** [comment]
Ok, pas de soucis.
Mais comme je ne peux avancer sur un sujet sans un "utilisateur" à l'autre bout, je clos celui la mais pense à le réouvrir (ou creer un nouveau sujet si le status actuel n'a plus rien à voir).

Merci
A+
