### ISSUE TITLE
Batterie des spirit eurotronics pas bonne dans analyse equipement.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1282]
https://community.jeedom.com/t/200-batterie-eurotronics-abeille/38701/2

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by hargathor** [comment]
bonjour,

pas de fix pour l'instant ?

Pendant que j'y suis merci pour le plugin abeille il est vraiment efficace !

**Comment by KiwiHC16** [comment]
Merci pour le retour, ca fait plaisir et motive car c est beaucoup de boulot.

Non pas encore de fix. Comme la modif ne doit pas être extrement compliquée, je l ajoute pour la prochaine stable.

**Comment by hargathor** [comment]
👍

**Comment by KiwiHC16** [comment]
Dans master.
