### ISSUE TITLE
Test and adapt to firmware 3.1d

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1286]
* Add 0x8002 command (raw command) when cluster or attribute is unknown. https://github.com/fairecasoimeme/ZiGate/pull/287 / https://github.com/fairecasoimeme/ZiGate/pull/314
=> very good and used by Abeille when subject known.

* Add PDMonHost commands for future implementation https://github.com/fairecasoimeme/ZiGate/pull/281
=> PDM Hosts : #147

* Add new message when PDM is loaded (usefull for PDMonHost implementation) https://github.com/fairecasoimeme/ZiGate/pull/281
=> PDM Hosts : #147

* Add Write Attribute Request with no response https://github.com/fairecasoimeme/ZiGate/pull/306
=> Unicast or UnicastAck: not managed by Abeille.

* Add a new sequence number method to link status messages https://github.com/fairecasoimeme/ZiGate/pull/296 / https://github.com/fairecasoimeme/ZiGate/pull/298

* Add rawmode hybrid and keep existing one https://github.com/fairecasoimeme/ZiGate/pull/307
=> Hybrid will probably become the default mode for Abeille. No direct impact.

* Upgrade UART RX buffer --> 255 octets instead of 127
=> No impact to Abeille

* Fix configure report when using 8 bits datatype https://github.com/fairecasoimeme/ZiGate/pull/308
=> Look to be a bug fix in zigate, can't see Abeille impact.

* Fix 0x8100 vs 0x8102 https://github.com/fairecasoimeme/ZiGate/pull/299
=> can't see Abeille impact.

* Fix ignore unknow attribute on configureReportingCommand --> (for DANFOSS with specific attribute)
=> can't juge not enough info.

* Fix a callback function which run before a registering https://github.com/fairecasoimeme/ZiGate/pull/293
=> can't see Abeille impact.

* Fix 24bits types handling https://github.com/fairecasoimeme/ZiGate/pull/290
=> can't see Abeille impact.

* Fix When cluster is unknow and there is not customCallbackFunction, we transmit to 0x8002 command (actually, concern 0x0300, 0x0120 and 0x0005)
=> taken into account into Abeille for the known messages.

* Fix Finally desactive 0x8035 command by default
=> PDM Hosts : #147

* Fix OTA bug for Legrand OTA
=> OTA not used in Abeille.

* Fix Legrand timer for controler (increment all second and reset to 0 when restart)
=> ?

* Fix UART FIFO capacity
=> No impact to Abeille

* Fix name error on cluster capacity (in ZCL_options.h
        POWER_CONFIGURATION_SERVER --> POWER_CONFIGURATION_CLIENT
        BINARY_INPUT_BASIC_SERVER --> BINARY_INPUT_BASIC_CLIENT
        delete ELECTRICAL_MEASUREMENT_SERVER
=> can't see Abeille impact.

* Change MAX_PACKET_SIZE ( for PDMonHost implementation)
=> PDM Hosts : #147

* Fix some other bugs
=> ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
La 3.1d n'est pas encore officielle n'est ce pas ?
En ce qui me concerne je basculerai dessus des que c'est le cas, et avant de la pousser.

**Comment by KiwiHC16** [comment]
Non elle n est pas officielle. Il est fort probable qu'elle sorte la semaine prochaine.

Ensuite il faut prend les modifications ci dessus une à une et voir si Abeille est ok avec.

**Comment by pipiche38** [comment]
@KiwiHC16 , @tcharp38 n'hésitez pas à me contacter si vous avez des questions. Pas mal de choses répondent à des choses qu'on a poussé avec @badzz ..

**Comment by KiwiHC16** [comment]
Ok merci pipiche38

**Comment by Asyrah** [comment]
Bonjour,
Passage manuelle de ma pizigate en 3.1d (wiki Zigate) (15/10). Pour l'instant, RAS sur mon système (Abeille branche master).

**Comment by tcharp38** [comment]
Ce FW sans changements Abeille semble provoquer des soucis cote volet profalux. Les miens passent en timeout.
Je ne vois pas de status/info remonter quand je les actionne via leur telecommande mais ils sont commandable d'Abeille et la le timeout disparait.
A creuser.

**Comment by battousai90** [comment]
de mon coté update manuel en 3.1d de la zigate (Le Prolific bleu), plus de ruche. retour en 3.0f, tout refonctionne.

**Comment by battousai90** [comment]
> de mon coté update manuel en 3.1d de la zigate (Le Prolific bleu), plus de ruche. retour en 3.0f, tout refonctionne.

En fait en regardant le SDK était rester sur 030f. Après Reflash et redémarrage, il y a bien SDK 031d et la ruche fonctionne.

Je vais maintenant tout réappairer et tester.

**Comment by tcharp38** [comment]
Salut
Pourquoi as tu besoin de ton réappairer ?
Et si jamais tu tombes sur des pbs avec ce FW, il serait utile que tu passes les logs en mode debug (si pas deja le cas) pour pouvoir recuperer des infos pratiques.
Merci

**Comment by battousai90** [comment]
> Pourquoi as tu besoin de ton réappairer ?

Je ne sais pas, mais plus rien fonctionne, je m'en passerai bien (27 appareils)

**Comment by tcharp38** [comment]
Ok pour moi ca n'est pas normal depuis la 3.0f.
Ca montre qu'on a des soucis avec la 3.1d. Il faut qu'on trouve du temps pour couvrir ca.
En + j'imagine que tu es sur la version "stable" et depuis dans la branche master beaucoup de choses ont encore evolué.
A suivre ... mais pour l instant 3.1d à eviter. Elle n'est d'ailleurs pas fournie par defaut dans Abeille. Elle le sera quand on considerera ce FW bien supporté.

**Comment by tcharp38** [comment]
Une info concernant les volets et j'imagine tout equipement sur secteur:
Abeille envoie regulierement des cmds "0100/Read Attribute request" pour "pinguer" l'equipement
- en 3.1c le retour etait "8102/Attribut report"
- en 3.1d le retour semble etre un "8011/APS data ack" suivi d'un "8100/Read attribut response"

FW3.1c
[2020-10-29 15:17:24][debug] => 0100-000e-025D8A0101000000000000010005
[2020-10-29 15:17:24][debug] <= 8102/Attribut report, SQN=44, SrcAddr=5D8A, EndPoint=01, ClustId=0000, AttrId=0005, AttrStatus=86, AttrDataType=FF, AttrSize=0000, DataByteList=
[2020-10-29 15:32:25][debug] => 0100-000e-025D8A0101000000000000010005
[2020-10-29 15:32:25][debug] <= 8102/Attribut report, SQN=4A, SrcAddr=5D8A, EndPoint=01, ClustId=0000, AttrId=0005, AttrStatus=86, AttrDataType=FF, AttrSize=0000, DataByteList=

FW3.1d
[2020-10-30 22:47:24][debug] collectMessagesForCmd(): Queue=queueKeyCmdToCmd, topic='CmdAbeille1/5D8A/Annonce', payload='01'
[2020-10-30 22:47:24][info ] Traitement du message: {"topic":"CmdAbeille1\/5D8A\/Annonce","payload":"01","priority":4}
[2020-10-30 22:47:24][debug] processCmd(): cmd={"ReadAttributeRequest":"1","priority":4,"dest":"Abeille1","address":"5D8A","clusterId":"0000","attributeId":"0005","EP":"01"}
[2020-10-30 22:47:24][debug]  =================> Envoi de la commande a la zigate: /dev/ttyUSB0-0100-000e-025D8A0101000000000000010005

[2020-10-30 22:47:24][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=5D8A, DestEP=01, ClustId=0000
[2020-10-30 22:47:24][debug] Abeille1, Type=8100/Read attribut response, SQN=5F, SrcAddr=5D8A, EP=01, ClustId=0000, AttrId=0005, AttrStatus=86, AttrDataType=FF, sizeOfAttribute=0000

Quelle est la difference entre la 8102 et la 8100 ?

**Comment by tcharp38** [comment]
@KiwiHC16 
Je pense avoir la solution, assez simple en fait. C'est pret à être poussé des que tu as inclus mon PR actuel histoire de pas tout mélanger.
Chez moi je suis maintenant en 3.1d et tout fonctionne à nouveau, les volets y compris.

Pour detailler ce que j'ai mis en place: je me suis dit que les reponse 8100 & 8102 etaient a traiter de la meme maniere.
J'ai donc
- pris le decode8102 pour le copier en decode8100_8102
- commenté le contenu de decode8100 pour qu'il appelle decode8100_8102
- commenté le contenu de decode8102 pour qu'il appelle decode8100_8102
Ca roule comme ca.

**Comment by KiwiHC16** [comment]
ok. Pousse le PR ;-)

**Comment by tcharp38** [comment]
C'est parti.

**Comment by KiwiHC16** [comment]
Dans le master maintenant.

**Comment by tcharp38** [comment]
Pour moi le 3.1d est ok. Je ne vois pas d'autres regressions.
Peut etre qu'on pourrait le mettre par defaut dans la prochaine beta et demander son test aux utilisateurs.

**Comment by KiwiHC16** [comment]
Il faudrait commencer à figer une version. Le master semble fonctionner actuellement. Je vais commencer à regarder cela.

**Comment by tcharp38** [comment]
Oui, je ne vois pas de regressions sur mes 3 plateformes, maintenant en 3.1d
@KiwiHC16 
Du coup j'arrete les PR le temps que tu generes une beta.

**Comment by pipiche38** [comment]
Pour infor: https://github.com/fairecasoimeme/ZiGate/issues/333

**Comment by tcharp38** [comment]
Merci @pipiche38 
J'avais bien eu ta notif. Merci de nous avoir mis dans la boucle

**Comment by battousai90** [comment]
De mon coté tout fonctionne depuis 2 semaines maintenant.
J'ai juste un problème avec Homebridge que je traite en parallèle.

Pour info j'utilise :
- détecteur ouverture xiaomi aqara V2
- Sonde Xiaomi aqara v2
- Ikea Tradfri Prises
- Ikea Tradfri Ampoule RGB color spectre Opal
- Ikea Tradfri Ampoule Blanche White Spectre Opal
- Ikea Tradfri Ampoule Blanche White Opal
- Ikea Floalt Panneau Led
- Ikea Tradfri Variateur ( switch carré)
- Ikea Tradfri Detecteur de mouvement

**Comment by battousai90** [comment]
Pour le problème avec Homebridge, cela vient du fait que certains périphériques retourne un nom avec un charactère spécial :
lumi.sensor_magnet.aq2�
TRADFRI bulb E27 W opal 1000lm�

**Comment by KiwiHC16** [comment]
@battousai90: quelle version du firmware utilises tu quand tu as ce soucis ? Je suppose 3.1D mais je veux etre sure. Est ce que tu te souviens d'avoir ce soucis dans un firmware precedent ?

**Comment by KiwiHC16** [comment]
Ok je clos cette issue. L'idée était de revoir tous les changements ce que j'ai fait dans le premier post.
Pour les problemes trouvés, on a soit une issue ouverte ou la correction.
La prochaine stable sera donc compatible 3.1d par defaut.
