### ISSUE TITLE
Pour dev: fonctionalite de mise à jour ou switch de branche

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1287]
@KiwiHC16 
Ca n'est pas un souci mais une proposition.

J'ai mis en place une fonctionalite de mise à jour de branche ou basculement vers une autre branche pour le mode developpeur.
Ca ajoute les widgets suivants sur la page de config.

![image](https://user-images.githubusercontent.com/35221038/95475933-0855ae80-0987-11eb-8b73-bd347f20d925.png)

Est ce que ca t'interesse ?

**Comment by KiwiHC16** [comment]
Interessant.
Peux tu me dire comment cela fonctionne ?

**Comment by tcharp38** [comment]
J'ai créé une lib pour controler grossierement GIT.
Avec ca je peux lister les branches dispos, voir si il y a des modifs locales, faire un git checkout et git reset, et redemarrer cron & apache2 pour prendre en compte les mises à jour.

Du coup si tu selectionnes la branche sur laquelle tu es deja, ca fait une mise à jour sur le dernier commit (fetch + reset)
Si c est une autre branche, tu bascules sur celle ci et dernier commit.

Dans l'ordre tu as
- la branche courante (vert=pas de modifs locales, rouge = modifs locales)
- la liste des branches (y compris si plusieurs remote)
- un bouton 'mise à jour' si meme branche, ou 'changer' si differente

La sortie de ces actions est dans "AbeilleConfig".
Je me sers beaucoup de ca maintenant pour mettre à jour mes differentes box sans m enquiquiner avec une connexion SSH.

Voila des exemples de sortie dans AbeilleConfig. Ca te donne une idée de ce qui est fait.

![image](https://user-images.githubusercontent.com/35221038/96004768-12baf100-0e3c-11eb-8c21-827081eae8a3.png)

**Comment by tcharp38** [comment]
Tu as intégré ça dans le master.
Avec le dernier PR (un fix sur le script switchBranch.sh), ca doit fonctionner.
Tiens moi au jus.

**Comment by tcharp38** [comment]
Un retour ?

**Comment by KiwiHC16** [comment]
Je n'ai pas testé car je ne sais pas si le code utilise ton repository ou le mieux et je ne voudrais avoir confirmation avant de tester et tout casser si cela utilise ton github.

**Comment by tcharp38** [comment]
Salut.
Le code ne connait pas mon repo. Il lit directement ceux definis chez toi.
Par ex moi j'ai "origin" pour ton repo GitHub et "tcharp" pour mon repo GiHub donc il va me proposer un switch ou une mise à jour de la branche choisie.
Je m'en sers tout le temps de cette feature.

**Comment by KiwiHC16** [comment]
Ok je vais essayer.

**Comment by KiwiHC16** [comment]
Ca semble bien fonctionner. 
C est cool.
Je l utiliserai pour les machines en production distantes sous docker. 
Pour le dev, je garde mon montage NFS, GitHub Deskop et la ligne de commande pour avoir un control plus fin.

**Comment by KiwiHC16** [comment]
Je suppose qu on peut fermer cette issue si tu es Ok.

**Comment by tcharp38** [comment]
Ha oui c'est super pratique de mon côté.
Je clos
