### ISSUE TITLE
Plugin Abeille pour volet Profalux

### ISSUE THREAD

**Issue by cissemp** [KiwiHC16/Abeille#1296]
Bonjour à tous

Je vous partage mes galères depuis quelques semaines avec mes volets.
Je ne suis pas un novice sur Jeedom mais là je bloque et j’ai besoin de votre aide.
J’ai installé des volets neufs chez moi il y un mois, des volets de marque profalux en protocole zigbee.
J’ai acheté une clef Zigate USB, et j’ai installé le firmware en version 3.1C. J’ai aussi installé le plugin Abeille pour inclure mon volet en suivant la procédure décrite sur la page http://kiwihc16.free.fr/Profalux.html 1
J’utilise la version 4.0.61 de Jeedom
Mais quand je fais le processus d’inclusion, un deuxième objet abeille est créé correspondant à mon volet sauf que le volet n’est pas vraiment reconnu il manque les commandes on, off et stop (cf image jointe)
Le plus étonnant c’est que j’avais réussi une fois à faire fonctionner mais suite à une fausse manip j’ai supprimé et depuis ça ne marche plus.
Merci de votre aide
![Abeille1](https://user-images.githubusercontent.com/72965923/96225705-c5509800-0f91-11eb-8375-822f11dc73ef.png)
![Abeille2](https://user-images.githubusercontent.com/72965923/96225731-ce416980-0f91-11eb-97ae-6b736296dc9b.png)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5389912/AbeilleParser.log)

**Comment by tcharp38** [comment]
Salut
Je me souviens que l'inclusion de mes volets n'a pas été si transparente que ca. J'ai du m'y reprendre à plusieurs reprises. J'en ai 5.
KiwiHC16 Kiwi pourra donner des pistes mais de mon cote je peut tenter qq essais.

J'imagine que tu es sur la derniere version stable, n'est ce pas ? (page config, version abeille)

**Comment by pipiche38** [comment]
Dixit Profalux:

> "Le plus simple c'est d'ouvrir le réseau de votre GW puis de faire un R + montée sur chacune des TS, le reset n'est pas utile. 
> J'ajoute que l'appui sur Stop n'est utile que pour vérifier que vos équipements (TS + volet) se sont bien appairés ensemble : 2 verts. 
> Pour éviter des problèmes de portée, il faudrait peut-être commencer par les équipements les plus proches de la gw. "


Ensuite, il faut bien comprendre que quand on associe un Volet avec la Zigate, ceux sont 2 devices qui sont associés:
- Le Volet en question
- La télécommande maitre du volet (attention ne faire aucun binding sinon c'est la perte assurée)

**Comment by cissemp** [comment]
@tcharp38 
Je suis sur la dernière version du plugin stable 3.1.7

**Comment by tcharp38** [comment]
Ca n'est malheureusement pas la version abeille. C est merdique ce truc.
Tu dois regarder + bas, "Version abeille". C'est une date

**Comment by cissemp** [comment]
@tcharp38 2020-09-30 01:00:23

**Comment by pipiche38** [comment]
> @pipiche38
> Vous entendez quoi par ouvrir le réseau GW ?

Mettre la Zigate en appairage

> TS c'est la télécommande ?

Oui, la télécommande associée au volet

**Comment by cissemp** [comment]
@pipiche38 c'est ce que je fais depuis le début (cf mon message initial)

**Comment by KiwiHC16** [comment]
2020-09-30 est la derniere et il faut cette version.

Peux tu confirmer que tu as bien le texte: 
```
Stable du 30 septembre 2020
 = Stable du 04.09.2020 avec Hue correction #1251<br><br>
```

Ensuite peux tu partager le log AbeilleParser quand tu fais l inclusion ? (plugin en mode debug)

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 

Voici ce que je vois
![image](https://user-images.githubusercontent.com/72965923/96255765-c0064400-0fb7-11eb-842b-c18f4174b509.png)
 Voici les logs
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5391324/AbeilleParser.log)

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 
J'ai bien avancé dans mon investigation et tout laisserait à croire que c'est un problème de distance entre mon jeedom et le volets. En effet, j'ai lu que la portée zigbee est de 10m. Or, j'ai une maison sur trois niveaux : les volets sont au dernier étage et le jeedom tout en bas au RDC.
J'ai déplacé ma jeedom (compliquée) pour la mettre près des volets et là miracle l'association a fonctionné et je pouvais piloter mon volet. Ensuite j'ai remis la jeedom à sa place au RDC et plus rien ne marche.
Quel est votre avis ?
<img width="345" alt="Abeilles" src="https://user-images.githubusercontent.com/72965923/96278443-c99ea480-0fd5-11eb-8c27-de1d125b2595.png">
<img width="781" alt="commandes" src="https://user-images.githubusercontent.com/72965923/96278454-cefbef00-0fd5-11eb-9572-bdb377414ee0.png">
<img width="918" alt="Santé" src="https://user-images.githubusercontent.com/72965923/96278468-d28f7600-0fd5-11eb-84fc-1927c21b2df2.png">

**Comment by KiwiHC16** [comment]
Tu as un soucis radio.
J ai fait une doc sur le sujet regardes: http://kiwihc16.free.fr/Radio.html

**Comment by cissemp** [comment]
Merci @KiwiHC16 
Mais je fais comment pour régler le souci radio ?

**Comment by dams74** [comment]
Salut @cissemp 
Pour résoudre ton soucis, il est possible de deporter la zigate en prenant le modèle wifi. 
Sinon il faut étendre ton réseau zigbee grâce à un ou plusieurs répéteur. Les éléments zigbee répéteur sont ceux qui sont alimentés comme les prises Ikea ou les ampoules hue. Ikea fait aussi des modules qui font seulement répéteur. 
J'espère que tu va arriver à solutionner ton soucis. 
Bon weekend
Damien

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by oldneef** [comment]
bonjour a tous,
pas nouveau sur jeedom j'ai voulu mettre mes volets profalux datant de nov 2017, grosse galère comme mentionné par cissemp...
exactement le meme pb avec le plugin Abeille....je ne sais plus quoi faire pour l'utiliser, ma Zigate est à jour, mon plugin aussi...

je rajoute qu'avec le plugin Zigate cela fonctionne seulement je n'ai pas le retour d'etat du volet mais bon....
j'aimerai le faire fonctionner avec Abeille comme beaucoup ici mais je ne sais plus quoi entreprendre.

**Comment by KiwiHC16** [comment]
J'essaye de ne pas mélanger les sujet.
Je clos ce point.
oldneef, ouvres une issue specifique si tu as besoin d aide.
