### ISSUE TITLE
Add little script to test health

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#13]
- test ttyUSB presence
- test zigate presence
- test mosquito presence
- test zigate to mosquito
- test mosquito to Jeedom
- test Jeedom to mosquito
- test mosquito to zigate
- test from A to Z chain
- ....

**Comment by KiwiHC16** [comment]
Fichier avec la liste des tests ajoutés. Reste a coder...

**Comment by edgd1er** [comment]
j'ai commencé certains tests (commit c3aa4f4cc7b46b4edafdac3dc0f52a74f915ed13 )
pour l'instant, c'est de la validation d'install et un test d'envoi de message, mais ça marche moyen...

**Comment by KiwiHC16** [comment]
Super petit a petit ca progress.
J ai ajouté des projets dans GitHub pour essayer de clarifier et visualiser les progrès.
J ai essaye de te mettre en action sur des Issues pour qu on ne travaille pas en parallèle sur les memes sujets mais je n'ai pas trouvé comment faire. Je vais te mettre collaborateur et on verra si c est la solution. Visiblement il faut que tu accept la demande.

**Comment by edgd1er** [comment]
Bonjour,

Merci pour l invitation, j ai accepté. Je n ai pas trouvé non plus comment m affecter une issue. Je l impression que ca se fait par mots clefs dans les commit...
mes prochaines taches seront la sortie de la conf du code, récupération dans l interface de power source et link quality (récupération des infos des messages).

**Comment by KiwiHC16** [comment]
" récupération dans l interface de power source et link quality (récupération des infos des messages)." sont deja dans l interface. As tu une idée précise ?

**Comment by KiwiHC16** [comment]
Fichier verification.sh dispo alors je clos le sujet.
