### ISSUE TITLE
Creation des commandes cachées dans ruche

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#130]
@edgd1er, peux tu remplacer la liste des objets:
 $items = array("Ikea Tradfri 5 Btn Rond", "LLC020", "LWB006", "lumi.plug", "Plug01", "lumi.sensor_86sw1", "lumi.sensor_ht", "lumi.sensor_magnet.aq2", "lumi.sensor_motion", "lumi.sensor_motion.aq2",
            "lumi.sensor_switch", "lumi.sensor_switch.aq2", "TRADFRI bulb E14 WS opal 400lm", "TRADFRI bulb E27 CWS opal 600lm", "TRADFRI bulb E27 opal 1000lm", "TRADFRI bulb E27 W opal 1000lm 2",
            "TRADFRI bulb GU10 W 400lm", "ProFaluxVolet");

Ligne 934 dans Abeille.class.ph

Par un truc du style ls dans le repertoire des objets, pour ne pas avoir a changer le code quand on ajoute/supprime un équipement ?

**Comment by KiwiHC16** [comment]
Attention il y a un objet ruche dans le epertoire et il ne doit pas faire parti de la liste.

**Comment by edgd1er** [comment]
oui, ce sont les commandes de la ruche. Pourquoi ne doit il pas faire parti de la liste ? Pour moi, c'est de la conf à sortir du code.

**Comment by KiwiHC16** [comment]
C est certainement ce qu il y a de plus simple et de plus clair.

**Comment by KiwiHC16** [comment]
Merged correction so I'm closing the issue. If during testing some issues are found we will open dedicated issues.
