### ISSUE TITLE
PHP Notice: Undefined index 5F01

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1302]
Pb rencontré pendant l inclusion de capteur de temp Xiaomi.

[19-Oct-2020 22:54:08 Europe/Brussels] PHP Notice:  Undefined index: 5F01 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 1672
[19-Oct-2020 22:54:08 Europe/Brussels] PHP Notice:  Undefined index: 5F01 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 1684

En dehors du fait qu'un deviceId inconnu ne devrait pas generer d'erreur PHP, d'ou sort ce 5F01 ? Je ne le trouve dans aucune spec ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
As tu la version du soft quand tu as eu ce message car les lignes ne semblent pas correspondre dans le master a cette erreur.

**Comment by tcharp38** [comment]
En fait c'est surement sur ma branche de dev donc pas de version utilisable.
Par contre je peux te dire que ca correspond au code ce dessous ($deviceInfo...)

            $this->deamonlog('debug', $dest.', Type=8043/Simple descriptor response'
                             . ', SQN='             .substr($payload, 0, 2)
                             . ', Status='          .substr($payload, 2, 2)
                             . ', ShortAddr='   .substr($payload, 4, 4)
                             . ', Length='          .substr($payload, 8, 2)
                             . ', EndPoint='        .substr($payload,10, 2)
                             . ', Profile='         .substr($payload,12, 4) . ' (' . $profileTable[substr($payload,12, 4)] . ')'
                             . ', DeviceId='        .substr($payload,16, 4) . ' (' . $deviceInfo[$profile][$deviceId] .')'
                             . ', BitField='        .substr($payload,20, 2));

Mais le 5F01 te parle ?
C'est une valeur "fabricant" ou "standard zigbee" ?

Je peux surement reproduire et te filer des logs du parser si tu veux.

**Comment by KiwiHC16** [comment]
C est deux octets donc ca peut être soit le profile, soit le deviceId
Il faudrait trouver lequel des deux, cela serai plus facile pour  la recherche.
Je penche plus pour le device info.

**Comment by tcharp38** [comment]
A priori ca n'est pas le profile mais le deviceId.
Je vais recreuser et te dire comment j'obtiens ca mais c'est avec un banal capteur Xiaomi temp carré.

**Comment by KiwiHC16** [comment]
Je viens de le trouver dans une note:
AbeilleParser 2018-12-10 22:14:48[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 83; Status : 00; Short Address : d87c; Length : 20; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 5f01 (); bitField : 01; InClusterCount : 05

Pour le Xiaomi Temperature V1 (celui qui est legerement rond).

**Comment by KiwiHC16** [comment]
Je viens de la mettre dans le master.

**Comment by tcharp38** [comment]
Je n'ai aucun capteur de temp rond. Que des v2. 
Faudra que je regarde celui ci pour voir si il fait pas partie d'un lot different.

Du coup, tu n'as pas répondu; sais tu si les deviceId sont des num du standard zigbee ou sous le controle du fabricant ?

**Comment by KiwiHC16** [comment]
Pardon, tous ceux definis dans la norme sont dans le code dans la table $deviceInfo dans AbeilleParser. Je complete cette table quand des équipements remontent de Id inconnus. Dans notre cas 5F01, je pense que Aqara a créé de nouveaux ids.
