### ISSUE TITLE
Compatibilité vanne intelligente

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1305]
Bonjour est-ce que ce type de vanne est compatible et connu de Abeille 👍 
https://fr.aliexpress.com/item/4000778266597.html?src=google&albch=shopping&acnt=248-630-5778&isdl=y&slnk=&plac=&mtctp=&albbt=Gploogle_7_shopping&aff_atform=google&aff_short_key=UneMJZVf&gclsrc=aw.ds&&albagn=888888&&ds_e_adid=438856512841&ds_e_matchtype=&ds_e_device=c&ds_e_network=u&ds_e_product_group_id=743612850874&ds_e_product_id=fr4000778266597&ds_e_product_merchant_id=105574338&ds_e_product_country=FR&ds_e_product_language=fr&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&ds_dest_url=https://fr.aliexpress.com/item/4000778266597.html?&albcp=10191220517&albag=107473525088&gclid=Cj0KCQjwuL_8BRCXARIsAGiC51Cm9quw6ZEI3g_HIbxyfO5sZ__5UhdGag4QQJqLH-HUXQ67CyesLbcaAqUBEALw_wcB

Merci

**Comment by KiwiHC16** [comment]
Oui

**Comment by bouboun59** [comment]
Bonjour

Apparemment cela ne fonctionne pas, il détecte bien mais pas de commande et fichier : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TS0111/TS0111.json will send back default template.

Pensez vous intégrer ce produit ?


merci
