### ISSUE TITLE
Capteur luminosité: frequence.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1309]
https://community.jeedom.com/t/capteur-luminosite-xiaomi-changer-la-frequence-de-rafraichissement/39702/13

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
La luminosité est fixée à 10min actuellement.
On pourrait réduire un peu mais est ce vraiment necessaire ?
A remettre sur le tapis si c'est le cas.
