### ISSUE TITLE
Interrupteur volet roulant "Loratap Tuya Smart Life ZigBee 3.0"

### ISSUE THREAD

**Issue by Marc--** [KiwiHC16/Abeille#1310]
Salut !

Dans la même veine que #1228, j'ai encore acheté des interrupteurs de volets roulants. Je pensais que ce serait les même, et bien non !

Je suis donc en train d'ajouter les "Loratap Tuya Smart Life ZigBee 3.0 Curtain Blind Switch for Roller Shutter Electric motor".

Pour les passer en inclusion : 10s sur le bouton "bas". Le voyant du haut clignotera alors.

Beaucoup d'info déjà disponible ici : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3134

J'arrive à le faire fonctionner en copiant le modèle du TS0302, mais je continue de regarder car je crois qu'il y a un peu plus de commandes sur ce modèle. Je posterai mes résultats comme je l'avais fait pour le #1228, afin de l'intégrer.

A bientôt !

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Salut @Marc-- 
Ce sujet est super vieux et je vois qu'il n'a pas bougé.
Es tu toujours interessé ?

**Comment by Marc--** [comment]
Salut,

Oui, mais ils sont destinés à une maison que je suis en train de construire, et je n'ai pas eu le temps de m'attaquer aux inters de volets.  A mon avis inutile de laisser trainer ce ticket, quand j'aurais le temps de les intégrer j'ouvrirai une nouvelle issue en liant celle ci.

**Comment by tcharp38** [comment]
Ok je comprends.
Donc je propose de clore ce sujet mais quand tu es pret a repartir dessus, tu le reouvre ou lieu d'en creer un nouveau.
A+
