### ISSUE TITLE
Clef Zigate NOK apres flash 3.1D -- port utilisé "apache2"

### ISSUE THREAD

**Issue by Mindstorm96** [KiwiHC16/Abeille#1313]
Bonjour, 
Apres avoir flashé la clef en suivant la procédure sur le site Zigate, Abeille n'arrive plus a se connecter sur la clef et l'annonce en NOK quand je fais TESTER.
J'ai relancé les dependances qui je trouve s'installe tres vite (peut etre un details) 
J'ai rechargé une sauvegarde sans succès
Dans abeilleconfig j'ai

[2020-10-27 09:21:44] Démarrage de 'checkTTY.sh'
Vérifications du port '/dev/ttyUSB1'
= ERREUR: Le port /dev/ttyUSB1 n'existe pas !
[2020-10-27 09:21:56] Démarrage de 'checkTTY.sh'
Vérifications du port '/dev/ttyUSB1'
= ERREUR: Le port /dev/ttyUSB1 n'existe pas !
[2020-10-27 09:37:29] Démarrage de 'checkTTY.sh'
Vérifications du port '/dev/ttyUSB0'
= Ok, le port semble libre.
[2020-10-27 09:45:11] Démarrage de 'checkTTY.sh'
Vérifications du port '/dev/ttyUSB0'
= ERREUR: Port utilisé par la commande 'apache2'.
=         Le port doit être libéré pour permettre le dialogue avec la Zigate

Merci d'avance 

Cdlt

nicolas

**Comment by tcharp38** [comment]
Salut.
Tu dois avoir le meme port qu'avant ton flashage en 3.1d donc je suppose que tu avais "/dev/ttyUSB0".

As tu un autre plugin qu'Abeille qui pourrait utiliser ce port ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
en ssh que donne la commande:
sudo ls -l /dev/ttyUSB*

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by Mindstorm96** [comment]
Bonjour 
le sudo ls -l /dev/ttyUSB me renvoyant un message d'erreur je suis reparti d'une fresh install et cela tourne maintenant.

merci 

cdlt

Nicolas

**Comment by Mindstorm96** [comment]
Merci a vous
