### ISSUE TITLE
Question: la zigate est t elle par design incompatible avec un hub alimenté ou non ?

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1316]
Cet issue est plus une question générale sur la zigate et les hub pour les utilisateurs. Il ne s'agit pas d'un bug du plugin.

je suis passé sur raspberry 4 + hub usb alimenté pour la clé zwave , un dd (stockage pas d'OS) et la zigate. Et la commence mes problèmes,, depuis deux semaines plus aucun device n'est inclus/reconnu/trouvé/écouté. j'ai essayé avec une autre zigate, avec un autre plugin ( jeedom-zigate) avec un autre hub et c'est la même chose. La clé est detecté, le réseau est formé, les commandes pour la ruche partent, les réponses de la ruche reviennent ( permit status, IEEE, payload, ...., ) mais rien des devices deja connu et des devices a reconnaitre.

J'ai essayé avec le firmware 3.1c et 3.1d, avec la version master du 26/10 et avec la version taggée v.2020.08.29 et avec deux hub usb alimentés différents ( mais mm alimentation), en faisant un reset pdm, un reset eeprom...

Bref, je ne vois plus que l'avis des utilisateurs pour avoir un retour d'expérience :)

Les questions:
- les clés usb zigate et un hub usb (alimenté dans mon cas) sont ils incompatible nativement ?
- y a t il une incompatibilité entre le rpi 4 et la zigate ?

PS: rpi3 + hub donne le même résultat. Les deux zigates fonctionnent sur un pc portable mais sans hub.
PS2: je dois trouver un cable usb type A pour essayer un branchement direct ce sera contraire au but recherché: soulager l'alimentation du RPI4

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut edgd1er,
Pour répondre à la question du titre, ma réponse est Oui cela fonctionne avec un rpi4 et un hub USB.
3 sources de soucis que j'ai vu:
- rpi4: semble avoir des soucis du fait de frequence sur different bus qui font que l USB 3 peut etre "délicât". Dans ce cas utiliser l USB 2. Pour la zigate ce n est pas un soucis.
- DD/SSD: ces bestioles consomment du courant et mettent à plat l alim RPI4.
- radio: Wifi et Zigbee sur la même bande donc si le wifi du RPI4 est utilisé, garder vos distance.

Ceci dit j'ai bien galéré pour mettre mon RPI4 en fonction avec son ssd (USB), zwave (USB), 2 zigates (USB), sms (USB)...
Ma config actuelle est:
- alim PC USB-C (65W) sur le RPI4, pas celle fournie avec le PI, elle ne semble pas etre suffisement bonne.
- SSD avec alimentation dédiée 3A sur USB-3 du rpi
- Hub USB sur USB-2 du Rpi avec sa propre alim 
- zwave, 2x zigate, sms, rfxcom sur le hub USB

Ca fonctionne comme cela depuis des mois sans aucun soucis. Avant j'avais des soucis en tout genre.

**Comment by edgd1er** [comment]
Merci pour ton retour

Effectivement, j'ai eu des pb et le SSD ne fonctionne pas s'il est sur un Hub. peut etre une limitation du firmware qui cherche a booter sur un périphérique raccordé directement..
sur le RPI4, jai le SSD sur un USB3, le hub sur USB3 et HD+zigate+zwave sur le HUB alimenté.

En mettant une rallonge USB et en éloignant, le zigate de la clé z-wave, cela semble mieux marcher.... les deux clés restent sur un hub alimenté.
il me reste a comprendre pourquoi je monte a une centaine de commandes empilées a chaque inclusion de devices...

**Comment by KiwiHC16** [comment]
Lors de l inclusion ca peut monter à beaucoup de commande car Abeille "bombarde" l equipement de question mais apres ca doit tourner tranquillement. Ca se produit aussi si equipement ne repond pas.

**Comment by edgd1er** [comment]
avec plus de mille commandes en attente, en quelques minutes,  pas sur que la solution retenue soit performante, il doit y avoir un réamorçage permanent des 37 commandes envoyées. Je ferais une PR si je vois comment traiter ce point.

Pour terminer le pb avec la zigate sur hub, il a fallut ajouter une rallonge pour éloigner la clé zwave de la clé zigate. Depuis, je n'ai plus de problème.Je ne connaissais pas cette distance minimale nécéssaire entre les deux clés. Cela risque d'arriver à d'autres.
