### ISSUE TITLE
Gestion des equipements qui ont le meme nom zigbee mais sont differents.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1318]
Exemple: TS0121 et Blitzwolf-BW-SHP13

**Comment by tcharp38** [comment]
Je vais poser des questions de novice mais ca peut peut être aider à clarifier.
J'imagine que ces 2 periphs remontent le meme 'ModelIdentifier'. Correct ?
Lequel ?

J'imagine que comme avait suggéré Pipiche, il faut stocker aussi le 'ManufacturerName' pour séparer des periphs.

**Comment by KiwiHC16** [comment]
TS0121

Proposition Pipiche, Oui c est une option 

mais je ne l'aime pas pour la raison suivante: tout le plugin est construit sur l idée de transaction unique. Je veux dire que si nous utilisons ModelIdentifier + Manufacturer nous sommes à deux transactions. Cela veut dire gestion de machine a état. Ce que j'essaye de fuir comme la peste.

Je ne dis pas que c'est toujours en mode transaction dans Abeille mais presque a une ou deux exceptions pret.

**Comment by tcharp38** [comment]
J'imagine que ne demande qu'une seule fois quel est le manufactureur, pendant l'inclusion.
Apres... l'adresse IEEE doit prévaloir et permet d'identifier le device de maniere unique.
Il y a surement qqch à faire par la.

**Comment by KiwiHC16** [comment]
De fait de tes questions, il est peut etre possible de se baser sur une autre info comme le SW level ou un truc du genre. A fouiller.
Ca donnerait une truc comme:
- je recois TS0121 mais cela n est pas unique
- je drop l info et demande la verison HW ou soft ou autre
- je recois l info et cela me permet de créé de facon unique l objet

**Comment by tcharp38** [comment]
Oui c 'est une bonne piste.
Lorsque l'identifiant n'est pas unique, tu peux aussi juste demander le fabricant et decider à partir de ça non ?
Du coup une 2nde transaction QUE SI l'identifiant n'est pas unique. Ca limite l'impact

**Comment by KiwiHC16** [comment]
SW n est pas ok avec le module que j ai dans les mains ;-(

Oui je peux avoir le fabricant mais je suppose que plusieurs modules ont le meme fabricant, ce qui veut dire que je garde en memoire le ModelId et attend le fabricant. Mais s il ne vient jamais ? Il faut gérer des timeout.... ca devient plus compliqué. Faisable biensur mais si complexe moins robuste...

**Comment by tcharp38** [comment]
Comment pourrait il ne jamais venir ?
Je suppose que ca fait partie des trucs obligatoires dans le standard Zigbee. Ca me semble un minimum non ?

**Comment by KiwiHC16** [comment]
Oui y a le standard et l implementation soft.
Alors dans les trucs dispos on a des octets ou des strings. Les infos au format octet ne donne que 256 possibilités donc pas viables . Et les string: manu, model, location et datecode.
Datecode n est quasi jamais dispo. idem pour location.
Donc il nous reste que le couple manu, model.

Pas top cette histoire

**Comment by KiwiHC16** [comment]
Implementé pour TS0121. Pour les prochain equipement, aligner le modele sur le nouveau mode et l ajouter dans le code d abeilleParser.
