### ISSUE TITLE
Limite dans les champs des attributs

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#132]
PHP Fatal error:  Uncaught exception 'Exception' with message '[MySQL] Error code : 22001 (1406). Data too long for column 'name' at row 1' in /var/www/html/core/class/DB.class.php:101
Stack trace:
#0 /var/www/html/core/class/DB.class.php(157): DB::Prepare('INSERT INTO `cm...', Array, 0)
#1 /var/www/html/core/class/cmd.class.php(757): DB::save(Object(AbeilleCmd))
#2 /var/www/html/plugins/Abeille/core/class/Abeille.class.php(677): cmd->save()
#3 /var/www/html/plugins/Abeille/core/class/Abeille.class.php(1088): Abeille::message(Object(stdClass))
#4 {main}
  thrown in /var/www/html/core/class/DB.class.php on line 101

 [name] => Luminosite should we keep it that si the question
 [name] => etat should we keep it that si the question
.....

**Comment by KiwiHC16** [comment]
Effectivement j ai du mettre ces trucs comme des commentaires sans voir les conséquences.
J'ai vu que tu as modifier dans le pull request donc je clos ce sujet
