### ISSUE TITLE
SonOff SNZB-03 - IR Sensor

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1324]
Split of
SonOff SNZB-02,01,03 #1301
to have a case per device

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Commandé, attente livraison.

Livré.

**Comment by mickadam29** [comment]
Salut
Encore un grand merci pour ton taf
J'ai reçu les miens ce matin.

**Comment by KiwiHC16** [comment]
IR Sensor

Zigate Ch 11
EP list 01
Nom: MS01
Location: vide
Cluster:
In: 0x000, 0x0001, 0x0003, 0x0500
Out: 0x0003


n envoit pas de message en spontanément.

**Comment by KiwiHC16** [comment]
Battery added to template

**Comment by bouboun59** [comment]
fonctionne sauf batterie

**Comment by KiwiHC16** [comment]
Batterie ok now.
bind et setreport a faire eventuellement manuellement sur reveil de l equipement.
Sera dispo dans la stable dans 15 jours.
