### ISSUE TITLE
SonOff SNZB-04 - Door Sensor

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1325]
https://community.jeedom.com/t/sonoff-snzb-04-sur-zigate-et-abeille/39336

**Comment by KiwiHC16** [comment]
See also SonOff SNZB-02,01,03 #1301

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Icone: in the master
Modele core: dans le master comme proposé
Commande template: reduit a une commande etat dans master.

**Comment by KiwiHC16** [comment]
Commandé, attente livraison.

**Comment by KiwiHC16** [comment]
Door sensor

AbeilleMaster:
Abeille Inclusion - bouton pendant 10s - association - retour etat fonctionne immédiatement.

Name: DS01
Location: vide

EP list: 01

n envoie pas de message en spontanément.

**Comment by KiwiHC16** [comment]
https://zigate.fr/produits-sonoff-compatible-zigate/compatible/snzb-04capteurdouverturedeporte/

Astuces :

Il faut faire un BIND sur le cluster 0x0001 ( power config)

**Comment by shadsnob** [comment]
Comment on fait un bind car j'ai ouvert le logiciel mais je sais pas les valeurs qu'il faut rentrer

**Comment by KiwiHC16** [comment]
Sera dispo dans la prochaine stable. 
Il faut que je finisse l integration dans les details.

**Comment by KiwiHC16** [comment]
Battery info added

**Comment by KiwiHC16** [comment]
Template updated.

Will be available in stable in 2 weeks.

Could need bind, setreport on batterie.
