### ISSUE TITLE
Key fob néo (un porte clé avec 4 boutons)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1326]
https://community.jeedom.com/t/developpement-equipement/40294/7

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2020-10-29 17:31:34][debug] Abeille1, Type=8102/Attribut report, SQN=2c, SrcAddr=dfe5, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=000c, DataByteList=Keyfob-ZB3.0
```

Keyfob-ZB3.0

**Comment by KiwiHC16** [comment]
```
[2020-10-29 17:31:37][debug] Abeille1, Type=8045/Active endpoints response, SQN=26, Status=00, ShortAddr=dfe5, EndPointCount=01, EndPointList=; 01
```

EP=01

**Comment by KiwiHC16** [comment]
```
[2020-10-29 17:31:38][debug] Abeille1, Type=8102/Attribut report, SQN=35, SrcAddr=dfe5, EndPoint=01, ClustID=0000, AttrID=0010, AttrStatus=86, AttrDataType=ff, AttrSize=0000, DataByteList=
```

Location=

**Comment by KiwiHC16** [comment]
Attente envoie.

**Comment by KiwiHC16** [comment]
Attente reception de la bete pour travailler dessus.

**Comment by KiwiHC16** [comment]
Bonne reception.

**Comment by KiwiHC16** [comment]
Wireshark: doc/ZigateEnInclusionKeyNewRemovePlasticProtectBatteryAssociation.pcapng
6259
EP: 01
Nom: Keyfob-ZB3.0
Location: ""

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-07 à 11 12 08](https://user-images.githubusercontent.com/8549674/98438386-16affb00-20ea-11eb-9903-37a9fac42bcf.png)

**Comment by KiwiHC16** [comment]
L appairage se fait bien et la creation dans Abeille est bonne.
Probleme, quand on appui sur les touchent la key n'envoie pas de message zigbee. Il doit y avoir une conf à faire mais laquelle ?

**Comment by KiwiHC16** [comment]
Input:
"0x0000": "General: Basic",
"0x0003": "General: Identify",
"0x0500": "Security & Safety: IAS Zone",
"0x0B05": "Inmax Neo private",

Output:
"0x0003": "General: Identify",
"0x0019": "General: Inconnu par abeille",
"0x0501": "Security & Safety: IAS ACE",

**Comment by KiwiHC16** [comment]
Il faudrait la gateway Inmax pour faciliter la suite.

**Comment by KiwiHC16** [comment]
https://zigbeealliance.org/zigbee_products/keychain-remote/

**Comment by tcharp38** [comment]
Je clos.
A réouvrir si nouvelles infos et si ca interesse qqn.
