### ISSUE TITLE
compatibilité module on/off tuya

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#1328]
Bonjour 
Est ce que Abeille est compatible avec un module Tuya Zigbee 3.0 onoff ?
Merci,
Ivan
[sur Aliexpress ](https://m.fr.aliexpress.com/item/1005001621078310.html?spm=a2g0n.productlist.0.0.2ed6df961ABG7R&browser_id=886d92db313747b68a2f321c773ba9a0&aff_trace_key=429fd04d569e4e168661ee0bac62dfd6-1590184016379-07575-cqcxR1hd&aff_platform=msite&m_page_id=ngtmfxhbcocau57z1757b8321d75ca937c9960e927&gclid=&_imgsrc_=ae01.alicdn.com%2Fkf%2FH648872538f3c4f69882543bde097e232L.jpg_640x640Q90.jpg_.webp)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ca doit etre le TS0121 (Qui est dans Abeille) mais je ne peux pas en etre sure.
https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/TS0121/doc/Tuya%20ZigBee%203.0%20commutateur%20de%20lumière%20intelligente%20Mini%20Module%20de%20disjoncteur%20bricolage%20vie%20intelli.pdf

**Comment by ivan9187** [comment]
Ok merci pour ta réactivité.
C'est un module d'une gamme (tuya) alternative à aquara un peu moins cher...
Je vais le commander sur Aliexpress...

**Comment by KiwiHC16** [comment]
Ok je clos.
