### ISSUE TITLE
Capteur de vibration Aquara

### ISSUE THREAD

**Issue by vince122** [KiwiHC16/Abeille#1329]
Bonjour Kiwi,

Tout d'abord un grand merci pour ton plugin qui fonctionne très bien !
J'ai voulu tester mes capteurs de vibration aquara, j'arrive à communiquer avec eux (niveau de batterie visible), cependant aucun d'entre eux ne me génère d'Evenement lorsque je tape sur la fenêtre à laquelle ils sont attachés.

Pourtant je les ai tous réglés en sensibilité High

J'ai activé le mode debug sur le Plugin, je ne vois rien s'afficher quand je leur tape dessus.

Aurais-tu une piste ?

Ma config :
Pizigate firmware 3.1c
Raspberry pi 3b+
Jeedom 4.0.61
Abeille du 30 Septembre

Merci d'avance,
Vince.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
As tu regardé: http://kiwihc16.free.fr/Xiaomi.html#vibration

**Comment by vince122** [comment]
OK j'ai compris mon erreur j'avais oublié le trigger() dans mes conditions de test... 
Ça fonctionne maintenant ! Désolé pour le dérangement

**Comment by KiwiHC16** [comment]
Merci du retour. Super, bonne nouvelle. Je clos.
