### ISSUE TITLE
Migrer knownDevices.json dans chaque config json.

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#133]
Les icônes sont liées aux devices via le fichier KnownDevices.json. Ce lien pourrait être fait directement dans le fichier json de chaque devices.

**Comment by KiwiHC16** [comment]
Je suis en ligne.

**Comment by edgd1er** [comment]
Ok, je m en occupe.

**Comment by KiwiHC16** [comment]
No issue seen with this merge so I close the case
