### ISSUE TITLE
Support capteur d’ouverture BlitzWolf BW-IS2 rechargeable

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1332]
https://community.jeedom.com/t/support-capteur-douverture-blitzwolf-bw-is2-rechargeable/40780

**Comment by KiwiHC16** [comment]
Faire le modele

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Module commandé le 11/1/2021

**Comment by tcharp38** [comment]
Antique sujet sans details.
Je clos mais a reouvrir si nouveauté.
