### ISSUE TITLE
Support capteur de mouvements BW-IS3 rechargeable

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1333]
https://community.jeedom.com/t/support-capteur-de-mouvements-bw-is3-rechargeable/40786

**Comment by KiwiHC16** [comment]
Faire le modele

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Je clos cette antiquité de sujet.
A reouvrir si qqn a cet equipement .
