### ISSUE TITLE
Bug - Choix icone d'une abeille

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#1335]
Bonjour @KiwiHC16,

Passage en Master build 33167136e8c36366... aujourd'hui et j'ai remarqué ce problème. J'ai 2 abeilles qui ont "perdu" leur icone.

![Capture2](https://user-images.githubusercontent.com/48121420/97994321-80c45980-1de5-11eb-9049-4607466cc423.PNG)
![Capture3](https://user-images.githubusercontent.com/48121420/97994324-81f58680-1de5-11eb-9067-4278338980c5.PNG)

J'ai remarqué que la liste est bizarrement incomplète, y a peut-être un loup là dessous :
![Capture4](https://user-images.githubusercontent.com/48121420/97994334-83bf4a00-1de5-11eb-9466-621407c48cb9.PNG)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Attention Attention: juste pour ête en ligne, le master est la version de dev et donc ne fonctionne que de temps en temps.

J'avais vu ce soucis et il doit etre résolu depuis.
