### ISSUE TITLE
Eurotronic SPZB0001u Not recognize

### ISSUE THREAD

**Issue by benoitfl** [KiwiHC16/Abeille#1338]
Hello,
All went well so far with the plugin, but at the moment where it come to the SPZB0001u, the plugin won't recognize it.
I'm wondering, is it because of the name that it return is SPZB0001u and not SPZB0001 as declare in the plugin ? 
So far I can't get it to command the valve.
Thanks for the help !

**Comment by benoitfl** [comment]
Well looking into adding devices and found that the log said that the json file is not found : 
[2020-11-05 11:44:31][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/SPZB0001`/SPZB0001`.json will send back default template.

The point is that the name of the valve keep changing ! If i paired it 3 times i'll SPZB0001 z,i,l,o ... 

I don't know what to do ...

**Comment by KiwiHC16** [comment]
Hi,
Could you share the specification of this product ? Is it : https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/SPZB0001/doc/2019_03_18_12_05_39.pdf

From what I see the name include a space /SPZB0001 [space]/SPZB0001[space].json which is not normal as normaly Abeille remove such caracter so strange.

Could you check that you have the file
/var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/SPZB0001/SPZB0001.json
in your system ?

**Comment by benoitfl** [comment]
Hi, I have core/config/devices/SPZB0001/SPZB0001.json
containing :
{
  "SPZB0001": {
    "nameJeedom": "Eurotronic Spirit",
    "timeout": "60",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c7822067c",
      "icone": "SPZB0001",
      "battery_type": "2x1,5V LR6 AA",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25 2 2 2": "spiritTemperatureConsigne",
      "include25 2 2": "spiritTemperatureConsigneGet",
      "include25 2": "spiritTemperatureConsigneSet",
      "include25 2 2 2 2": "spiritTemperature",
      "include25 2 2 3": "spiritTemperatureGet",
      "include25 2 2 2 2 3": "spiritTemperatureBindShortToZigate",
      "include25 2 2 2 2 2": "spiritTemperatureSetReport",
      "include25 2 2 3 2 2": "spiritPiHeatingDemand",
      "include25 2 2 3 2": "spiritPiHeatingDemandGet",
      "include25 2 2 3 2 2 2": "spiritValvePosition",
      "include25 2 2 3 2 2 2 2": "spiritValvePositionGet",
      "include25 2 2 3 2 2 2 2 2": "spiritValvePositionSet",
      "include25 2 2 3 2 2 3": "spiritTrvMode",
      "include25 2 2 3 2 3": "spiritTrvModeGet",
      "include25 2 2 3 2 3 2": "spiritTrvModeSet",
      "include25 2 2 3 2 3 2 2": "spiritTrvModeSetManu",
      "include25 2 2 3 2 3 2 2 2": "spiritTrvModeSetValve",
      "include25 2 2 3 2 3 2 2 2 2 2 2": "spiritBatterie-Pourcent",
      "include25 2 2 3 2 3 2 2 2 2": "BindShortToZigateBatterie",
      "include25 2 2 3 2 3 2 2 2 2 2": "spiritSetReportBatterie",
      "include25 2 2 3 2 3 2 2 2 2 2 3": "spiritHostFlags",
      "include25 2 2 3 2 3 2 2 2 2 2 3 2": "spiritErrors",
      "include25 2 3": "spiritHostFlagsDisplayDownSet",
      "include25 2 3 2": "spiritHostFlagsDefaultSet",
      "include25 2 3 2 2": "spiritHostFlagsBoostSet",
      "include25 2 3 2 2 2": "spiritHostFlagsChildLockSet",
      "include25 2 3 2 2 2 2": "spiritHostFlagsOffSet",
      "include25 2 3 2 2 2 2 2": "spiritUnknown1",
      "include25 2 3 2 2 2 2 2 2": "spiritUnknown2"
    }
  }
}
It's where I got lost, why would abeille not recognize the name of the device ?

**Comment by KiwiHC16** [comment]
Is it a print issue in Github or is it the real situation in your log ?
There is a space after the name.
Could you check ?

**Comment by benoitfl** [comment]
Well I had a space in the name, but in the log it would not appear as a space. It was replaced by a letter (u,z,o,...) or "]".
this morning I got this :
getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/SPZB0001W/SPZB0001W.json will send back default template.

Then the name in Jeedom appear as SPZB0001T ...

**Comment by KiwiHC16** [comment]
So looks like one lettre to many is used.
Which version of Abeille are you using ?

**Comment by KiwiHC16** [comment]
You will find the information in the configuratioon page:
![Capture d’écran 2020-11-09 à 08 25 56](https://user-images.githubusercontent.com/8549674/98511586-33bd0900-2265-11eb-9593-08a62583d814.png)

And which firmware Zigate are you using ?

**Comment by benoitfl** [comment]
Stable du 30 septembre 2020 = Stable du 04.09.2020 avec Hue correction #1251
I Just installed the latest from the market.

**Comment by KiwiHC16** [comment]
I remember doing a correction on this subject few weeks ago. 
If I propose a beta, would you be able to test ?

**Comment by benoitfl** [comment]
Yep ! Easy for me this week till this Monday for test.
Thanks for the help I'll go ahead on the "cagnotte"

**Comment by KiwiHC16** [comment]
Are you familiar with github ? with php ?

**Comment by benoitfl** [comment]
Github not much, PHP I use it at my job for website integration with Databeses, I should be fine.

**Comment by KiwiHC16** [comment]
Ok then I will generate a beta and then if needed will see to adapt some php if needed.

**Comment by KiwiHC16** [comment]
Which zigate firmware are you using ?

**Comment by benoitfl** [comment]
003 here

**Comment by KiwiHC16** [comment]
3.1b ? 3.1c ? 3.1d ?

**Comment by benoitfl** [comment]
3.1d
looking at Abeille.class.php line 1214 :
`$trimmedValue = str_replace(' ', '', $trimmedValue);`
this as far as i know, would efectively replace space by no caractere. 

Few lines above, Abeille put stuff into log "info".
the output of this line was :
[2020-11-09 12:10:20][INFO] : Recherche objet: SPZB0001T dans les objets connus
[2020-11-09 12:10:20][DEBUG] : value:SPZB0001T / trimmed value: ->SPZB0001T<-

Seems like the device does not sent the space but a specific caractere et the end. 
I'll try few times see if i always get the "T" at the end.

[2020-11-09 12:36:52][INFO] : Recherche objet: SPZB0001Z dans les objets connus
[2020-11-09 12:36:52][DEBUG] : value:SPZB0001Z / trimmed value: ->SPZB0001Z<-

**Comment by KiwiHC16** [comment]
AbeilleParser read one char too many. I'm nearly 100% sure that the issue is corrected in last versions.
I have created a beta-dev version which is now on all my system.
No crash up to now. 
I'll wait few hours and then generate a beta version.

**Comment by benoitfl** [comment]
@KiwiHC16 Ok ! sounds good, it happened as well on the legrand Shutter switch with neutral], the caracter at the end is also here...
Thanks for the support

**Comment by benoitfl** [comment]
Problem solved with Beta 13/11/2020
