### ISSUE TITLE
Integration recepteur profalux Zigbee pour volets roulants

### ISSUE THREAD

**Issue by 2CConnect** [KiwiHC16/Abeille#1342]
Bonjour,

Je n'arrive pas à intégrer mes volets profalux (initialement filaire) équipé de récepteur profalux zigbee NB072 (sous Jeedom)
[
[Notice recepteur Profalux ZigBee - Volet roulant, Trapèze et Store - NB072 (2).pdf](https://github.com/KiwiHC16/Abeille/files/5504931/Notice.recepteur.Profalux.ZigBee.-.Volet.roulant.Trapeze.et.Store.-.NB072.2.pdf)

J'ai joint le fichier Parser, SerialRead et Abeille  comme suggéré par @Xav-74

[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/5504933/AbeilleCmd.txt)
[AbeilleSerialRead1.txt](https://github.com/KiwiHC16/Abeille/files/5504934/AbeilleSerialRead1.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5504935/AbeilleParser.txt)
[Abeille (3).txt](https://github.com/KiwiHC16/Abeille/files/5504936/Abeille.3.txt)

Pour info j'ai tenté de l'inclure par la télécommande individuelle et j'obtiens deux équipements sous Jeedom (le module light profalux 
![profalux light](https://user-images.githubusercontent.com/50622932/98444555-9c47a100-2112-11eb-8811-1ae22d9165a7.PNG)
) et un point d'interrogation pour le second. Je n'ai pas les commandes montées descente, stop disponible.

Merci beaucoup pour ton aide et à ta disposition pour tout essai complémentaires
Cordialement
Jean Luc

**Comment by dams74** [comment]
@KiwiHC16 
C'est normal car ce module est multifonctions. Il faudrait proposer une choix une fois inclus. Je ne sais pas si c'est possible. Si besoin je dois avoir les documentation des différentes fonctions

**Comment by 2CConnect** [comment]
Merci beaucoup pour ta réponse rapide.

Je suis preneur de la documentation sur les differentes fonctions.
Cdt
jean Luc

**Comment by dams74** [comment]
Jean Luc
Pour le moment seulement la fonction on off a été implémenté pour ce module. Il faut voir si @KiwiHC16 peut permettre les deux fonctions sur le même module

**Comment by 2CConnect** [comment]
Merci pour l'info.

J'espère que @KiwiHC16  pourra implementer ces commandes avec une selection predefinie.

Sinon est-il possible de rajouter les commandes montee/descente/stop manuellement (sous jeedom par exemple) avec une syntaxe prédefinie sur le module light?
Cdt
jean Luc

**Comment by KiwiHC16** [comment]
Dans le log AbeilleParser j ai le nom PRZ qui remonte:
```
[2020-11-04 22:15:50][DEBUG] : message(topic='Abeille1/01dc/0000-01-0005', payload='PRZ')
```

Si je regarde le modele pour cet equipement, j'ai On/Off/Etat. Et une note que j avais prise qui dit:
```
ProfaluxLigthModule
```

**Comment by KiwiHC16** [comment]
Recepteur calyps'home / Profalux #652

```
AbeilleParser 2019-03-29 09:21:48[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 8d; Status : 00; Short Address : a117; Length : 20; endpoint : 03; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 09
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 000A - General: Time
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: 0015 -
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: fc20 -
AbeilleParser 2019-03-29 09:21:48[DEBUG]In cluster: fc21 -
AbeilleParser 2019-03-29 09:21:48[DEBUG]OutClusterCount : 03
AbeilleParser 2019-03-29 09:21:48[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser 2019-03-29 09:21:48[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2019-03-29 09:21:48[DEBUG]Out cluster: fc20 -
```

**Comment by KiwiHC16** [comment]
Ces traces ont été prise il ya presque 2 ans !!!
Depuis j'ai de nouvelles infos:
Cluster:
"0x0015": "General: Commissioning",
fc20 - Inconnu
fc21 - Inconnu

Il faudrait: 
- de la doc technique sur le module. 
- les specifications sur les fc20 et fc21.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by dams74** [comment]
Voilà j'ai mis toute la doc que j'ai en ma possession
[Notice recepteur CalypsHOME - Porte de garage Profalux - ROLLIXO - NB084.pdf](https://github.com/KiwiHC16/Abeille/files/5506120/Notice.recepteur.CalypsHOME.-.Porte.de.garage.Profalux.-.ROLLIXO.-.NB084.pdf)
[Notice recepteur CalypsHOME - Porte de garage Profalux - Oct 2013 A Aout 2016 - MAI-KM8 ou MAI-KM8PX - NB082.pdf](https://github.com/KiwiHC16/Abeille/files/5506121/Notice.recepteur.CalypsHOME.-.Porte.de.garage.Profalux.-.Oct.2013.A.Aout.2016.-.MAI-KM8.ou.MAI-KM8PX.-.NB082.pdf)
[Notice recepteur CalypsHOME - Portail  et Sabot - NB083.pdf](https://github.com/KiwiHC16/Abeille/files/5506122/Notice.recepteur.CalypsHOME.-.Portail.et.Sabot.-.NB083.pdf)
[Notice recepteur  CalypsHOME - Eclairage - NB076.pdf](https://github.com/KiwiHC16/Abeille/files/5506123/Notice.recepteur.CalypsHOME.-.Eclairage.-.NB076.pdf)
[Notice recepteur Profalux ZigBee - Volet roulant, Trapèze et Store - NB072.pdf](https://github.com/KiwiHC16/Abeille/files/5506124/Notice.recepteur.Profalux.ZigBee.-.Volet.roulant.Trapeze.et.Store.-.NB072.pdf)

**Comment by piwii** [comment]
J'ai aussi ce module pour piloter un de mes volets roulants que je n'arrive pas a intégrer correctement dans Jeedom via le plugin Abeille.
@KiwiHC16 en tant que développeur, j'aimerais apporter ma part de contribution pour que ce module soit bien reconnu pour piloter un volet roulant et non une lumière.
Est ce que tu pourrais m'aiguiller un peu ? installation en local ? documentation ? fichier a modifier ? procédure de test ?
Merci a toi pour ton super boulot.

**Comment by 2CConnect** [comment]
Merci à tous,

@piwii  et @KiwiHC16 , n'hésitez surtout pas à m'inclure dans le process pour de la documentation, des tests ou autres ...

Concernant la notice recepteur Profalux Zigbee de @dams74 , je n'ai hélas pas plus d'informations ou de specifications.

**Comment by dams74** [comment]
J'essaierai de faire un mail à proflux

**Comment by pipiche38** [comment]
Il y a des chances qu’il fonctionne comme le BSO

**Comment by KiwiHC16** [comment]
Pour moi c est un peu difficile car je ne possede pas ce module pour tester en direct.
J'ai encore un cas ouvert sur BSO pour l inclinaison des lames.

@piwii, @2CConnect est ce que l un d'entre vous peux faire la manipulation suivantes:
- backup de votre systeme
- mettre le plugin en mode debug et redemarrer le daemon
- remplacer le modele PRZ par le modele Volet et remplaçant dans le fichier Volet par PRZ
- suppression de l objet créé par Abeille pour ce module apres avoir récupéré son adresse courte
- option 1: re-inclusion si pas trop difficile
- option 2: faire un getName sur le device avec son adresse courte depuis la ruche 
- tester les commandes
- partager la liste des tests fait avec leur horodatage et les log Abeille, AbeilleCmd et AbeilleParser

**Comment by KiwiHC16** [comment]
Savez vous ou je peux commander ce module ?

**Comment by piwii** [comment]
Je l'ai vu ici mais il coûte quand même 230 euros : https://www.profalux-pieces-detachees.com/domotique/350-recepteur-radio-profalux-zigbee.html

**Comment by KiwiHC16** [comment]
Donc je ne peux pas casser la cagnote pour ce module. Je vais avoir besoin de vos informations; 
As tu un sniffer Zigbee ?

**Comment by 2CConnect** [comment]
J'attends des nouvelles de Profalux, pour tenter d'avoir un module de demo. Pour la manip de @KiwiHC16 , je ne suis pas super compétent pour tout comprendre. Est'il possible d'effectuer ces manips avec un accès distant et moi au téléphoner en support?

Concernant le sniffer, je ne suis pas équipé; Est-ce que une Clé sniffer zigbee CC2531 avec antenne serait suffisant pour faire les tests ?

**Comment by KiwiHC16** [comment]
Pour le sniffer je ne sais pas. Je me suis fabriqué le mien: https://github.com/KiwiHC16/Butineuse
mais il n'est pas plug and play. Il faut sortir le fer à souder, etc...

Pour le fichier je peux en preparer un des que je peux. Il faudra le mettre sur jeedom pour tester.

**Comment by piwii** [comment]
Je vais tenter la procédure demain.

**Comment by piwii** [comment]
J'ai réalisé la procédure de @KiwiHC16, j'ai bien les commandes pour des volets mais maleureusement ces commandes ne fonctionnent pas :-(
Seule la fonction setLevelVolet fonctionne mais comme un Toogle

Je vous joins les log ci-dessous  :
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/5523201/Abeille.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5523202/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5523203/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5523204/AbeilleCmd.log)

**Comment by oldneef** [comment]
J'ai le meme soucis avec le plugin ZIGATE

**Comment by tcharp38** [comment]
Salut @piwii 
Quel est le status de ce vieux sujet ?

**Comment by tcharp38** [comment]
@2CConnect 
Salut. Ce sujet en est ou ?

**Comment by tcharp38** [comment]
Je clos ce sujet antique.
A reouvrir si qqn est pret à bosser dessus
