### ISSUE TITLE
Ecrans table des noeuds et graphique du réseau jamais rafraichis

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1343]
Bonjour Ben,

Depuis des mois (juillet 2020), j'avais ces deux écrans qui ne changeaient jamais malgré l'inclusion de nouveaux périphériques. En parcourant le forum Jeedom, j'ai lu un truc qui m'a mis la puce à l'oreille, ça concernait le dossier /var/www/html/plugins/Abeille/Network/tmp
Voici la copie du contenu du mien
![image](https://user-images.githubusercontent.com/16527222/98445507-61e10280-2118-11eb-9362-5522e7bd21c9.png)
J'ai donc fait le ménage en virant les fichiers AbeilleLQI_Map*.* et j'ai relancé la découverte, et la, tout s'est soudainement enrichi.
J'ai recommencé 10 minutes plus tard pour voir si l'horodatage des fichiers changeait. C'est bien le cas.
C'est donc un bug "résolu" mais il faudrait peut-être écrire quelque chose dans une KB et/ou voir pour nettoyer ce dossier depuis l'interface du plugin et faire quelques contrôles, dans le cas ou ce problème soit aussi présent chez d'autres.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Sur quelle version Abeille es tu ? Car normalement le fichier *.lock est celui qui bloque. Mais un restart du daemon l efface.
As tu redemarrer le plugin, le daemon depuis Juillet 2020 ?

**Comment by JC38** [comment]
Salut, je suis sur la stable du 30/09. 
Et oui, j'ai fait des reboot depuis Juillet.

**Comment by tcharp38** [comment]
@JC38 La prochaine release fixe qq soucis de ce cote. Tu dois au moins pouvoir "forcer" le raffraichissement avec "Refresh LQI" non ?

**Comment by JC38** [comment]
@tcharp38 : Oui, comme je l'ai signalé, la suppression des fichiers manuellement a débloqué la situation et j'ai ensuite testé le refresh, les fichiers se mettaient à jour. C'est donc un bug qui se résout avec la manip mais qui est apparu au moins une fois.

**Comment by KiwiHC16** [comment]
Quel firmware tourne sur ta zigate ?

**Comment by KiwiHC16** [comment]
Je ne connais pas la vrai raison du soucis. Le cleanup des fichiers lock est fait au demarrage du daemon.
Je clos en esperant que c etait un cas particulier.

**Comment by tcharp38** [comment]
@KiwiHC16 
Je vois un souci potentiel.
On detruit effectivement le lock mais on ne verifie pas si AbeilleLQI tourne encore pour une raison ou une autre.
J'ai fait un test rapide en lancant AbeilleLQI à la main et il se fiche du restart d'Abeille. Il tourne toujours.

Je viens d'ajouter ca dans "deamon_stop()". Je pousse dans la PR dans qq mins.
