### ISSUE TITLE
Support de la prise EU Xiaomi  ZNCZ04LM (lumi.plug.mmeu01)

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1344]
Bonjour,

Je viens de recevoir ces prises Xiaomi EU. Abeille les détecte avec une icône générique, pour autant l'icône Prise Xiaomi EU était bien présente dans la liste. 
Dans la liste des commandes crées, il n'y a pas les commandes On/off ni la consommation.
Ce modèle est-il correctement pris en charge par Abeille ?

**Comment by KiwiHC16** [comment]
Peux tu partager ce que contient la commande nom sur cet icône ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Dans Abeille on a plug.mmeu01
mais je vois dans ton titre plug.mmeu01f

As tu un lien vers cette prise sur le net ?

**Comment by JC38** [comment]
Pour la cagnotte, c'était prévu mais maintenant c'est fait. Tu pourras rapprocher le don avec ce sujet ;-)
Voici un lien pour l'origine des prises : [https://fr.aliexpress.com/item/4000763741872.html](url)
Elle est vendue aussi en France comme par exemple ici [https://www.domadoo.fr/fr/peripheriques/5305-xiaomi-prise-connectee-zigbee-mi-smart-plug-6934177706493.html](url)
J'ai aussi trouvé ce lien (mais je ne sais s'il peut te servir) : [https://www.zigbee2mqtt.io/devices/ZNCZ04LM.html ](url)
Quelques captures
![image](https://user-images.githubusercontent.com/16527222/98469747-bb613400-21e1-11eb-8de3-e0e690b06c57.png)
Oups, la dernière capture ne fonctionne plus, j'ai une erreur json quand je veux afficher les périphériques qui sont dans l'objet "Zigbee" (c'est le nom de la "pièce" dans laquelle je renage mes devices Zigbee en attente d'affectation).
![image](https://user-images.githubusercontent.com/16527222/98470220-899d9c80-21e4-11eb-9d88-61eb34ee82cc.png)

Cette erreur json est provoquée par 2 devices, dont un que j'ai depuis longtemps, l'autre étant la prise. Hier, ça marchait sans problème. Si je décoche la coche visible de ces 2 devices, l'erreur disparait.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-09 à 08 45 25](https://user-images.githubusercontent.com/8549674/98513299-ebebb100-2267-11eb-9a47-9282a25d0cc7.png)

**Comment by KiwiHC16** [comment]
D apres https://www.zigbee2mqtt.io/devices/ZNCZ04LM.html 
Elle remonte Etat, W, kWh, °C, V, A

**Comment by KiwiHC16** [comment]
Je viens d en commander une.

**Comment by KiwiHC16** [comment]
Je me demande si le soucis n'est pas le même que #1338

**Comment by KiwiHC16** [comment]
Peux tu me donner la version Abeille sur ton systeme:
![](https://user-images.githubusercontent.com/8549674/98511586-33bd0900-2265-11eb-9593-08a62583d814.png)

**Comment by benoitfl** [comment]
Bonjour,
Il semble effectivement que j'ai le même probleme.
random lettre à la fin du nom.

**Comment by JC38** [comment]
> Elle remonte Etat, W, kWh, °C, V, A
Oui, c'est justement pour ça que je les ai commandées ! Marre des prises Z-wave qui tombent en carafe :-(
![image](https://user-images.githubusercontent.com/16527222/98517612-77684080-226e-11eb-99d8-5b80e1c795fe.png)
J'ai encore la seconde dans son emballage, veux-tu que je l'appaire pour voir quel nom elle va prendre ?
C'est compliqué de faire une modif pour ajouter une conf plug.mmeu01f copiée de la conf plug.mmeu01 (je connais pas le code mais des fois que ça puisse le faire). Je peux aller mettre des fichiers dans le dossier du plugin ou en éditer certains si on me donne le détail.

**Comment by KiwiHC16** [comment]
Je pense avoir fait une correction sur ce sujet il y a quelques semaines. 
Est ce que tu pourrais tester une beta si j'en mets une à disposition ?

**Comment by JC38** [comment]
Oui, pas de pb. Redis-moi juste comment on passe de prod a beta. Il faut désinstaller le plugin et le recharger en version beta ? c'est sans perte de conf ?

**Comment by KiwiHC16** [comment]
Je ne suis pas sure. Il faut que je teste le truc.
Sinon connais tu GitHub ? Connais tu le php ?

**Comment by JC38** [comment]
Github, j'ai l'appli Desktop, j'ai déjà récupéré des contenus avec. Le php sans plus mais je sais ouvrir un fichier et faire une modif dedans.

**Comment by KiwiHC16** [comment]
Ok on va essayer de passer par les beta sur Jeedom pour faciliter le truc. Je prepare et reviens vers toi quand dispo. Peut etre qq jours.

**Comment by JC38** [comment]
Dak, à tout hasard, tu aurais pas une piste pour résoudre le pb de l'erreur 200 concernant le json (bandeau rouge dans la capture ci-dessus). C'est juste le fait de mettre visible pour 2 devices du plugin Abeille. Et je ne sais où trouver une trace plus complète de cette erreur.

**Comment by KiwiHC16** [comment]
Pardon, je n avais pas vu. Quelle manipulation fais tu pour declancher cette erreur ? (Je ne l ai jamais vu)

**Comment by KiwiHC16** [comment]
Sur quelle version du firmware Zigate ?

**Comment by JC38** [comment]
Je suis en 3.1d.
J'ai mis qq devices dans une pièce Zigbee (ce réglage n'est pas récent).
![image](https://user-images.githubusercontent.com/16527222/98545706-2a986000-2296-11eb-81ed-03a888144e68.png)
Si je coche visible pour le device Abeille1-12ff ou BT2 Garage Abeille1-9537 , lorsque je  vais dans le Dashboard afficher la pièce "Zigbee" alors j'ai le bandeau rouge. Le device BT2 Garage Abeille1-9537 est associé depuis des semaines, je ne vois pas ce qui change. J'ai l'impression que c'est un pb de taille des tuiles sur l'écran, c'est peut-être bien le seul truc que j'ai changé récemment. Même Abeille1-12ff (la prise lumi.plug.mmeu01f) s'affichait correctement avant-hier sur le Dashboard, c'est même comme cela que j'ai récupéré son nom.

**Comment by KiwiHC16** [comment]
Sur quelle version de Jeedom es tu ?

**Comment by JC38** [comment]
Je suis en 4.0.61

**Comment by KiwiHC16** [comment]
Je suis aussi sur 4.0.61. C est une bonne chose et j ai aussi des 3.1d en firmware.

**Comment by KiwiHC16** [comment]
Est ce que tu as des infos dans le log http.error ?

**Comment by JC38** [comment]
Il n'y a rien dans le http.error log  sur ce plugin.
Et surprise du jour, BT2 Garage Abeille1-9537 ne fait plus planter l'affichage. Seul Abeille1-12ff fait encore planté l'affichage. Vraiment bizarre ce truc.

**Comment by KiwiHC16** [comment]
Si tu mets ton browser en debug pour te donner les erreurs est ce que tu as quelques choses ?

**Comment by JC38** [comment]
Je ne sais pas comment mettre le browser en debug mais j'ai identifié le problème .
1. J'ai supprimé la prise depuis le plugin
2. J'ai mis le plugin en inclusion et relancé une détection en mettant aussi la prise en appairage --> IEEE-Addr; adresse IEEE 04CF8CDF3C867771 pour 45c7 qui remonte est deja dans l objet ea21 - Abeille1-ea21, on fait la mise a jour automatique
--
3. J'ai vérifié l'affichage, il était ok (par contre le nom est passé de Abeille1-12ff  à Abeille1-45c, c'est normal ?)
4. J'ai voulu afficher des infos en cochant les cases qui vont bien 
![image](https://user-images.githubusercontent.com/16527222/98806131-01eca380-2419-11eb-91e0-757ce254ac3a.png)
5. Et là, je me retrouve avec l'erreur 200

Ce qui est super bizarre, c'est qu'un ancien device se soit mis à provoquer le même problème et que lors de mon tout premier essai avec cette prise,  j'ai pu lire des infos dans la tuile, comme par exemple le fameux lumi.plug.mmeu01f
Explication probable, il doit y avoir une mauvaise prise en compte de valeurs NULL dans la construction du json ? Même si ces NULL sont exceptionnels.

**Comment by JC38** [comment]
Je ne sais pas comment mettre le browser en debug mais j'ai identifié le problème .
1. J'ai supprimé la prise depuis le plugin
2. J'ai mis le plugin en inclusion et relancé une détection en mettant aussi la prise en appairage --> IEEE-Addr; adresse IEEE 04CF8CDF3C867771 pour 45c7 qui remonte est deja dans l objet ea21 - Abeille1-ea21, on fait la mise a jour automatique
--
3. J'ai vérifié l'affichage, il était ok (par contre le nom est passé de Abeille1-12ff  à Abeille1-45c, c'est normal ?)
4. J'ai voulu afficher des infos en cochant les cases qui vont bien 
![image](https://user-images.githubusercontent.com/16527222/98806131-01eca380-2419-11eb-91e0-757ce254ac3a.png)
5. Et là, je me retrouve avec l'erreur 200

Ce qui est super bizarre, c'est qu'un ancien device se soit mis à provoquer le même problème et que lors de mon tout premier essai ,  j'ai pu lire des infos dans la tuile, comme par exemple le fameux lumi.plug.mmeu01f
Explication probable, il doit y avoir une mauvaise prise en compte de valeurs NULL dans la construction du json ? Même si ces NULL sont exceptionnels.

Voici aussi la ligne qui a été écrite dans le log de Abeille au moment de la détection :
[2020-11-11 11:59:21][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/plug.mmeu01–/plug.mmeu01–.json will send back default template.

**Comment by KiwiHC16** [comment]
Es tu sur le firmware 3.1d ?

**Comment by JC38** [comment]
@KiwiHC16 
Bonjour Ben
As-tu reçu ta prise ? Les miennes sont fonctionnelles sur le On/Off/W mais la Conso reste à 0
Il manque la remontée du voltage, des ampères et de la température (Exposes | switch (state), power, energy, temperature, voltage, current, linkquality)

**Comment by KiwiHC16** [comment]
Je viens de la recevoir, elle est sur mon bureau.

**Comment by KiwiHC16** [comment]
Je viens de revoir le modele.
Ce qui fonctionne: 
- envoie On, Off, Toggle
- remontée etat du relai sur On/Off/Toggle depuis Jeedom et aussi depuis bouton lateral.
- Remontée de la puissance consommée.

Il existe d autres messages envoyés par la prise mais je ne sais pas les décodés. Si vous avez des infos...

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2583

**Comment by KiwiHC16** [comment]
Finalisé dans master. Si soucis ouvrir issue specifique.
