### ISSUE TITLE
Moyen de communication entre developpeur

### ISSUE THREAD

**Issue by piwii** [KiwiHC16/Abeille#1346]
Bonjour à tous,

J'aimerais contribué a ce beau projet qui m'a déjà beaucoup simplifié la vie.
Mais je dois avouer être un peu perdu et je ne sais pas par ou commencer.

Est ce qu'on pourrait mettre une place un moyen de communication comme un slack pour pouvoir s'entraider et se donner des conseils sur le développement du projet Abeille.

Qu' est ce que tu en penses @KiwiHC16 ? et les autres developpeurs ?

**Comment by edgd1er** [comment]
Bonjour,

Bonne idée, je bataille a comprendre le vocabulaire zigbee ( commande, attributes RO/RW, M/O, direction ) et comment cela s'insère dans le plugin, les templates avec des 2 2 2 2 3 3 3 4 3 2 2 3...
Brej, je patauge depuis une semaine pour créer un modèle pour le thermostat Danfoss ally.
La doc de kiwi couvre pas mal de choses mais pas ça....

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut,

Je n'ai pas de solution. Si vous avez un outils facile à utiliser je peux vous rejoindre.
@piwii, tu mentionnes Slack, peux tu nous inviter ? Est ce accessible depuis un browser web ?

**Comment by KiwiHC16** [comment]
@edgd1er, un modele possede un corps qui contient les informations non relative aux commandes. Ce corps inclus les modeles des commandes. Dans la catégorie Commandes on fait les instenciations par le mot clef "include" suivi d'une chaine de caractere unique. Elle peut etre aleatoire, mon outils "JSON Editor" utilise ces numéros: 1 2 3 comme tu indiques.

**Comment by KiwiHC16** [comment]
Je rajoute un Labels dev pour pouvoir focaliser sur ces sujets.

**Comment by piwii** [comment]
Vous pouvez rejoindre le slack abeille en cliquant sur ce lien : https://join.slack.com/t/nouvelespaced-qns2883/shared_invite/zt-ixx0uaxx-S0gmJ72A_K7RBWWIZ_eDVw
C'est utilisable depuis le web, sur une application lourde ou encore sur mobile.
