### ISSUE TITLE
Support GLEDOPTO Zigbee lumière lien lampe de jardin ?

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1347]
Bonjour,

Ce n'est pas une issue mais je ne sais pas trop ou poster; ici  ou sur la communauté Jeedom. :-(
Je ne sais pas si ce [produit ](https://fr.aliexpress.com/item/32957910925.html )est supporté par Abeille. 
Peut-être en regardant la page, ceux qui connaissent peuvent avoir une idée de la compatibilité.
Je me pose aussi la question du rapport qualité/prix pour ce produit là et de son rendu, si certains ont de l'expérience sur celui-ci ou des produits identiques...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Cet equipement n'est pas connu par Abeille.

**Comment by JC38** [comment]
Dans la combo box du choix des icones, tu as du matériel de cette marque. Sauf que je ne sais faire le lien avec le produit ci-dessus
![image](https://user-images.githubusercontent.com/16527222/98545194-6979e600-2295-11eb-9692-e290fee85101.png)
car ça ressemble bien au second de la liste GLED OPTO couleur.
Au pire, si je le commande, tu sauras l'intégrer si je te fournis des infos ?

**Comment by KiwiHC16** [comment]
On ne peut pas savoir si il est deja connu par Abeille sans le faire parler.

"Au pire, si je le commande, tu sauras l'intégrer si je te fournis des infos ?"
=> Il y a de grandes chances que oui car il y a deja des equipements de la meme famille (Je ne veux pas m'engager car c'est tes €).

Tiens moi au courant si tu en achetes un.

**Comment by JC38** [comment]
Bonjour,

Je vais attendre demain pour passer commande, ce sera le 11/11 en Chine (je sais en France aussi) mais il y a pas les mêmes promos :-(
Je voudrais d'ailleurs regarder un peu plus l'ecosystem Mijia à cette occasion. Si je savais, je commanderais d'ailleurs un lot de prise EU... mais c'est lié à la résolution de l'autre ticket.

**Comment by JC38** [comment]
Bon, ben les commandes sont passées.
[https://fr.aliexpress.com/item/32957910925.html](url)
[https://fr.aliexpress.com/item/32967902742.html](url)
Et des modules SonOff , eux ne devraient pas poser de pb  : https://fr.aliexpress.com/item/1005001304487239.html

**Comment by JC38** [comment]
Bonjour, la commande a été reçue ce matin. (livrée en 10 jours !)
Le produit est détecté mais pas "reconnu".
Voici comment Jeedom le voit :
![image](https://user-images.githubusercontent.com/16527222/99876427-f22e4580-2bf6-11eb-9c0f-81fbb8d4c267.png)
et voici les réf au dos du projecteur
![image](https://user-images.githubusercontent.com/16527222/99876473-2c97e280-2bf7-11eb-82af-56ef3ad478fc.png)
Si besoin d'avoir des infos supplémentaires, merci de me donner la procédure pour les récupérer.

**Comment by JC38** [comment]
Petit complément d'info
`[2020-11-21 12:34:22][ERROR] : getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/GL-G-001ZSf/GL-G-001ZSf.json will send back default template.
`
J'ai l'impression que ça ressemble à l'autre problème que j'ai en cours avec une prise EU Xiaomi et à celui-ci #1433 aussi ?

**Comment by KiwiHC16** [comment]
Plusieures choses:
- la ref est la meme chose que le nom zigbee ca c est top
- Tu dois être avec la version stable d abeille et tu as le bug du caractere en trop "GL-G-001ZSf" alors que le nom est "GL-G-001ZS"
- Cet equipement n'est pas dans Abeille.

Je viens de le mettre dans la beta de dev. Sera dans la prochaine beta disponible.

Quand tu pourras tien moins au courant sur le bon focntionnement.

**Comment by KiwiHC16** [comment]
Commit dans master aussi

**Comment by JC38** [comment]
Bon voici les news du soir, après avoir passé le plugin dans Jeedom sur la branche master Github
Prise Xiaomi EU : elle est bien reconnue mais il manque le bon visuel au niveau de l'icône (d'ailleurs, la liste me semble moins longue qu'avant).
Eclairage de jardin : idem pour le visuel bien que j'aie entr'aperçu la vraie image 
Détecteur de fumées Heiman : il s'appelle maintenant Humein ( ?) smoke sensor. Je l'avais sorti avant hier pour voir comment se passait l'inclusion mais du coup, j'ai eu le bug de la lettre de trop et il était plus reconnu correctement. Je ne sais pas par contre s'il fait bien son boulot de détecteur de fumées, quels sont les noms des commandes relatives à la fonction de détection qui devraient être présentes dans la liste de ses commandes ?
La prise Xiaomi
![image](https://user-images.githubusercontent.com/16527222/100016129-3ed17680-2dd9-11eb-97a1-70e596a37978.png)
La lampe GLEDOPTO
![image](https://user-images.githubusercontent.com/16527222/100016176-4db82900-2dd9-11eb-9ee9-b42e6fd056e0.png)
Et voici la liste des commandes crées pour le détecteur
![image](https://user-images.githubusercontent.com/16527222/100016375-996ad280-2dd9-11eb-83ab-5e8a172cd669.png)

**Comment by KiwiHC16** [comment]
@JC38, le nombre de sujet explose et je ne parviens pas à tout suivre.

Tu parles de plusieurs produits. Peux tu faire une issue par produit.

Peux tu utiliser la beta et pas la master.

Quels sont tes résultats sur l inclusion de cette ampoule ?

**Comment by JC38** [comment]
L'ampoule de jardin est ok au niveau on/off et couleurs. Seule son icône n'est pas ok mais c'est le cas a priori pour mal d'équipements, également ceux qui étaient présents avant. Peut-être qu'en pensant sur la beta ce sera ok, je verrai peut-être ce soir pour le faire ainsi que pour ouvrir des issues séparées.

**Comment by KiwiHC16** [comment]
Ok je clos cet issue et tu ouvrira des specifiques si besoin.
