### ISSUE TITLE
Mettre le nom et l objet des equipements.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1349]
![Capture d’écran 2020-11-09 à 12 33 33](https://user-images.githubusercontent.com/8549674/98536258-ca022680-2287-11eb-8474-13626ce9c0cc.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je viens de pousser ton PR. Super !

Peut être devrions nous avoir un ligne comme:

Object - Equipement (Abeille1/984D) veut joindre Object - Equipement (Abeille1/0000) passera par Object - Equipement (Abeille1/5FB2)

Avec Objet par exemple la pièce: Salon
Et l equipement: Prise

en place et lieu de:

Abeille1/984D veut joindre 0000 passera par 5FB2

Peux tu nous faire un PR supplémentaire.

Apres à plus lon terme, je me demande comment afficher ces infos d un point de vue graphique... mais c est plus de boulot...

**Comment by piwii** [comment]
![Capture](https://user-images.githubusercontent.com/3097527/98946923-d50dbe80-24f4-11eb-9144-38bf94ccc9b4.PNG)

**Comment by piwii** [comment]
![Capture](https://user-images.githubusercontent.com/3097527/98966070-1c06ae80-250b-11eb-86bd-f15d72371a98.PNG)
