### ISSUE TITLE
Refresh en fin d execution sur "Route-Tout Collecter" et "Bruit-Tout Collecter"

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1350]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Network List
![Capture d’écran 2020-11-09 à 17 31 16](https://user-images.githubusercontent.com/8549674/98568424-612fa400-22b1-11eb-8cea-cb86beee4763.png)

Route - tout collecter
![Capture d’écran 2020-11-09 à 17 31 41](https://user-images.githubusercontent.com/8549674/98568497-70165680-22b1-11eb-9537-b4e47a95108d.png)

La page ne se rafraichie pas en fin d exécution

**Comment by tcharp38** [comment]
Pour info, j'ai une update à venir pour la table des noeuds.

**Comment by tcharp38** [comment]
Je ferme ce sujet.
- La fonctionalité "bruit" n'est plus maintenue
- La fonctionalité "route" devrait à terme être dans le nouveau "placement routage"
