### ISSUE TITLE
Undefined index zigate in ...AbeilleLQI.php on line 226

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1351]
Je log ce pb pour mémoire. Je vais pousser le correctif dans la foulée.

Erreur PHP:
      [09-Nov-2020 114506 EuropeBrussels] PHP Notice  Undefined index zigate in varwwwhtmlpluginsAbeilleNetworkAbeilleLQI.php on line 226

A cause du code de lancement cronDaily() qui ne passe aucun paramètre.

            /**
             * Refresh LQI once a day to get IEEE in prevision of futur changes, to get network topo as fresh as possible in json
             */
            log::add('Abeille', 'debug', 'Launching AbeilleLQI.php');
            $ROOT= "/var/www/html/plugins/Abeille/Network" ;// getcwd();
            log::add('Abeille', 'debug', 'ROOT: '.$ROOT);
            $cmd = "cd ".$ROOT."; nohup /usr/bin/php AbeilleLQI.php >/dev/null 2>/dev/null &";
            log::add('Abeille', 'debug', $cmd);
            exec($cmd);

Du coup je pense que la mise à jour journaliere de la table LQI ne se faisait pas.
De + le code le lance **qu'UN** AbeilleLQI, ce qui veut dire que les cas multi-zigates ne sont pas supportés.
A noter que le "refresh" à partir du bouton de la page réseau lui fonctionne.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
"Du coup je pense que la mise à jour journaliere de la table LQI ne se faisait pas." -> je confirme et me disais qu il faudrait que je regarde un jour ou l autre.

**Comment by tcharp38** [comment]
Je clos. Pour moi c'est fixé pour la prochaine stable.
