### ISSUE TITLE
Device name too long: one char too many

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1352]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
- https://github.com/KiwiHC16/Abeille/issues/1286#issuecomment-723586656 (Firmware: ?)
- Support de la prise EU Xiaomi ZNCZ04LM (lumi.plug.mmeu01f) #1344 (Firmware: ?)
- Eurotronic SPZB0001u Not recognize #1338 (Firmware: 3.1d)

**Comment by KiwiHC16** [comment]
I think the correction was: https://github.com/KiwiHC16/Abeille/commit/110070a94fdb57abec1bc017a1b3e290c0c85613

**Comment by battousai90** [comment]
#1286 
Pour le problème avec Homebridge, cela vient du fait que certains périphériques retourne un nom avec un charactère spécial :
lumi.sensor_magnet.aq2�
TRADFRI bulb E27 W opal 1000lm�

@battousai90: quelle version du firmware utilises tu quand tu as ce soucis ? Je suppose 3.1D mais je veux etre sure. Est ce que tu te souviens d'avoir ce soucis dans un firmware precedent ?

Firmware 3.1d, firmware précédent 3.0f et aucuns soucis.

**Comment by KiwiHC16** [comment]
Une beta sera dispo demain si tu veux essayer. Surtout faire un backup de jeedom avant.

**Comment by battousai90** [comment]
Entendu je testerai ca et ferai un retour ;)

**Comment by mickadam29** [comment]
Le firmware 3.1D retourne en effet des noms avec des caractères "spéciaux" Par exemple ]
Je n'avais aucun souci auparavant.

**Comment by tcharp38** [comment]
J'ai un doute car j'ai au moins un de tes equipements... lumi.sensor_magnet.aq2 et je vois pas ce pb.
En outre j'ai du mal à croire que le FW est coupable.
Tu as confirmé avec un essai en 3.1c ?

**Comment by mickadam29** [comment]
Je vais faire le retour en 3.1C
Aucun souci. Tout réagissait rapidement
Les équipements remontent maintenant avec ces noms par exemple
Tu peux voir les caractères à la fin. Ils étaient peut-être présents avant mais jamais vu. 
J'ai viré une ampoule IKEA qui serait peut-être coupable d'un mauvais routage ?
D'autres anomalies sont apparues. Seconde image : Plus de placement réseau.
En tout cas tout est apparu après le passage 3.1c vers 3.1d.


![image](https://user-images.githubusercontent.com/36518012/98584972-dbb6ee80-22c6-11eb-9de7-6799bde028cb.png)
![image](https://user-images.githubusercontent.com/36518012/98585207-36e8e100-22c7-11eb-90ec-8fdbec1ca719.png)

Et cela aussi

![image](https://user-images.githubusercontent.com/36518012/98585311-5b44bd80-22c7-11eb-85b6-bcfb6a917153.png)

Mais tout n'est peut-être pas lié.
Juste que c'est pénible car cela touche les interrupteurs !

**Comment by tcharp38** [comment]
C 'est pas simple à isoler LA cause du pb. Parfoit on cumule trop de changements et c'est galère.
Quoi qu'il en soit je suis maintenant en 3.1d, et j'ai ce capteur de door. Pas vu du tout ce caractere de fin. 
Peut etre que demain tu pourra nous dire si le souci est toujours la. Il y a eu tellement de modifs depuis..

**Comment by battousai90** [comment]
De mon côté je n’ai pas les characters spéciaux sur tous les périphériques.
J’ai  8 détecteurs d’ouvertures xiaomi Aqara 2 et seulement 4 on le characters à la fin. Pareil pour les Ampoules IKEA.

Envoyé de mon iPhone

**Comment by mickadam29** [comment]
C'est surtout très embêtant car les scénarios ne fonctionnent plus puisque les noms ne sont pas correctement reconnus.
Si j'exécute les scénarios liés à l'appui des boutons en manuel, je pilote correctement le ON/OFF des ampoules.
Je n'avais pas ce problème jusqu'à hier matin, passage de 3.1c à 3.1d. 37 objets dans la zigate. La mémoire commence peut-être 
à saturer. Comme l'ajout des prises ajoute des routeurs je vais patienter. Mais tant que les noms seront "parasités" mes scénarios risquent de ne plus fonctionner. Je suis surtout embêté par un interrupteur double sur pile Xiaomi que j'ai réinclus quand je me suis aperçu qu'il ne pilotait plus l'éclairage. Je vais faire un request de son nom pour vérifier s'il correspond à celui qui existait à la création du scénario.

**Comment by mickadam29** [comment]
Je confirme pour les noms : 3 interrupteurs / 2 portent le nom lumi.remote.b286acn01 et le 3ème qui n'est plus pris en compte dans les scénario est passé à lumi.remote.b286acn01T
Le T fait toute la différence ;-)
@battousai90. Peux-tu vérifier si tes objets avec les caractères spéciaux sont liés à des scénarios, s'ils fonctionnent ou pas ?
De mon côté, je vais replacer mon objet sur mon scénario en espérant que le nom ne changera pas et qu'il conservera le T à la fin. Ca va être très compliqué d'appairer des objets avec nom qui change !! Le modèle json ne sera jamais bon.
J'espère que qq1 trouvera une cause et une solution à ce bug. J'ai d'autres objets à inclure dans mon réseau.
En tout cas merci à tous ceux qui font vivre la zigate et le plugin Abeille.

**Comment by battousai90** [comment]
Pas de scénario de mon côté, j’utilise ceux de maison par l’intermédiaire de home bridge. Par contre j’ai beaucoup de groupe pour lié les interrupteur IKEA aux ampoules. A creuser.

Envoyé de mon iPad

**Comment by mickadam29** [comment]
Ma crainte est fondée. L'inclusion se passe mal. Le nom du modèle à un "i" à la fin. Donc aucun modèle json à ce nom aléatoire
Et pourtant je suis reparti d'une sauvegarde du 7/11. A cette date aucun objet n'avait de caractère supplémentaire.
Tout va bien tant que je n'appuie pas sur cet interrupteur. Peut-être est-ce le seul qui me pose problème
Je vais restaurer à l'état de 19H ce jour. Sans toucher à cet interrupteur. On verra bien.
Mais je sais dorénavant que je ne peux plus ajouter d'équipement.


2020-11-09 21:51:32 | Abeille | IEEE-Addr; adresse IEEE 00158D0002B48B91 pour 4915 qui remonte est deja dans l objet eb46 - Couloir VV-CH, on fait la mise a jour automatique |   |  
-- | -- | -- | -- | --
  | 2020-11-09 21:51:23 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/remote.b286acn01i/remote.b286acn01i.json will send back default template. |   |  
  | 2020-11-09 21:51:23 | Abeille | Création d un nouvel objet Abeille (Abeille1/2f0b) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

**Comment by KiwiHC16** [comment]
I think the correction was: https://github.com/KiwiHC16/Abeille/commit/110070a94fdb57abec1bc017a1b3e290c0c85613
Une beta sera dispo demain si tu veux essayer. Surtout faire un backup de jeedom avant.

**Comment by mickadam29** [comment]
Je testerai après avoir vérifié la stabilité, pour être certain. J'ai restauré au 7/11 et j'ai retrouvé des noms erronés. Mais moins. Et pour la plupart les routeurs (Prise Ikea et Sirène PSE03)
J'ai 2 interrupteurs Xiaomi qui fonctionnent très bien tant que je ne sollicite pas le 3ème qui me pose problème. Car sinon, ils ne fonctionnent plus. Reboot et ou redémarrage du plugin.
Si je dois condamner un interrupteur provisoirement ça ira. Reste à voir les nouvelles inclusions.
Je te fais un retour dès que j'ai testé la beta.

**Comment by mickadam29** [comment]
@KiwiHC16 
Le souci concernerait des équipements IKEA (après lecture il semblerait que non) ? Car effectivement, j'ai ajouté des prises. Celles-ci ont toutes un caractère supplémentaire. Je les ai remise en service cette semaine pour étendre le réseau et éviter des timeout sur des équipements sur pile. Merci à toi

**Comment by KiwiHC16** [comment]
Ca peut toucher n importe quel equipement, c est generique.

**Comment by mickadam29** [comment]
Je viens de corriger mon poste  précédent et tombe sur ta réponse après. 
Concrètement que va-t-il se passer pour les objets qui ont été mal inscrits ? Il faudra les réinclure ? Ou ta version beta va prendre cela en charge ? 
Et donc rien à voir avec la version 3.1d ?

**Comment by mickadam29** [comment]
Dis-moi c'est normal d'avoir ça sans que la zigate ne soit en inclusion ? (Et ce foutu caractère W en plus mais ça j'ai compris.)
Je vais regarder l'objet, mais je risque de pas savoir à quoi il correspond du coup. Remote.b286acn01, si tu connais.
Ah ben ça s'est curieux, ca correspond à un interrupteur comme celui qui me pose problème. Et ça doit faire une heure que j'ai tenté de le réinclure avec mes backup/restauration.


2020-11-09 22:42:48 | Abeille | getJSonConfigFilebyDevices: filename not found: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/remote.b286acn01W/remote.b286acn01W.json will send back default template. |   |  
-- | -- | -- | -- | --
  | 2020-11-09 22:42:48 | Abeille | Création d un nouvel objet Abeille (Abeille1/4915) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.

**Comment by tcharp38** [comment]
Sans quelle soit en inclusion ?! Je ne maitrise pas encore tout mais ca je pige pas.
Tu faisais quoi au moment ou ce message est apparu ?

**Comment by mickadam29** [comment]
Rien, c'est ça qui est étrange. Je cherchais l'objet avec l'adresse courte que tu m'as demandé sur l'autre issue.
Mais uniquement en visu sur les noms.  En même temps ma zigate est au sous-sol. Mais suis certain qu'elle n'était pas en inclusion et encore moins d'avoir appuyé sur l'interrupteur qui est dans un couloir à 5m de moi

**Comment by mickadam29** [comment]
Pour info, j'ai oublié de préciser que JEEDOM est en version 4.0.61

**Comment by tcharp38** [comment]
Peut etre qu'on cron s'est déclenché et a initié tout ça.
Tu peux filer la trace Abeille+AbeilleCmd+AbeillerPaser ?

**Comment by mickadam29** [comment]
@tcharp38 
Suis plus devant l’ordinateur. Je vérifierai demain le contenu des 3 fichiers et s’ils contiennent les événements de ce soir je les mettrai à disposition. Dans tous les cas, c’est bien l’usage de l’interrupteur qui met le bazar mais depuis quand ?  Et donc peut-être rien à voir avec la 3.1d ou avec le caractère qui s’ajoutent au nom.

**Comment by battousai90** [comment]
Quelque test de ce matin :
 - Reset du cache de jeedom.
 - Reboot de jeedom.
 - Toutes les abeilles sont présentes mais plus aucun ID
 - Refresh LQI
 - Tous est revenu avec les ID
 - Toutes les abeilles qui avait un nom avec caractère spécial, ont maintenant plus de nom, aucune valeur retournée
![image](https://user-images.githubusercontent.com/47687052/98664840-2da15800-234b-11eb-8396-f7047c5ff237.png)
 - Celle qui avait un nom on maintenant une lettre en plus à la fin
![image](https://user-images.githubusercontent.com/47687052/98664983-59244280-234b-11eb-8e65-88e05539b809.png)
 
En supprimant la commande nom des abeilles sans valeur, homebridge démarre et tout fonctionne, quand à la lettre supplémentaire, ca ne dérange pas.

**Comment by mickadam29** [comment]
Cela fait suite à l'installation de la version beta ?

**Comment by mickadam29** [comment]
Concernant l'objet créé, j'ai un objet non reconnu car le nom porte le caractère supplémentaire. Ce nouvel objet, à l'ancienne adresse courte de l'interrupteur XIAOMI. En fait, mon interrupteur avait l'id 4915, celui est maintenant sur l'objet Abeille et l'interrupteur à une nouvelle adresse courte. Cet objet est celui créé hier soir sans que la zigate ne soit en inclusion. Et aurait dû être une simple mise à jour de l'interrupteur. Autre anomalie. L'interrupteur me renvoie 2 ID qui sont censés être identiques.

![image](https://user-images.githubusercontent.com/36518012/98671756-08b1e280-2355-11eb-906d-47ab8f592353.png)

Interrogation de son adresse courte : 19b5
Or l'objet remonte

![image](https://user-images.githubusercontent.com/36518012/98671857-3008af80-2355-11eb-91e5-ee0540522edc.png)

Sacré pagaille !

**Comment by mickadam29** [comment]
Et enfin une autre curiosité, apparue après la mise à jour en 3.1d ou l'ajout des mes routeurs (prises IKEA)
Lorsque j'appuie sur mes interrupteurs qui fonctionne et sont reconnus sans caractère supplémentaire, il ne se passe absolument rien. Puis si je réappuie, ils actionnent les scénarios. Valable pour mes 3 interrupteurs. C'est comme si le réseau se mettait en veille et que le premier appui le réveillait. Ensuite tout va bien fonctionner pendant qqs heures et ensuite il faut à nouveau appuyer une première fois pour réveiller tout ce monde.

**Comment by mickadam29** [comment]
@battousai90 

Es-tu certain que cela n'a pas d'influence sur le routage ? Cela concerne une ampoule qui fait routeur.

**Comment by battousai90** [comment]
@mickadam29  `Cela fait suite à l'installation de la version beta ?`
Non.

@mickadam29 `Es-tu certain que cela n'a pas d'influence sur le routage ? Cela concerne une ampoule qui fait routeur.`
Le fait de supprimer la commande 'nom' ? C'est pas le nom de l'abeille, c'est la commande qui est censé récupérer le nom du périphérique.
j'ai rien constaté d'anormal dans le network, juste quelque abeille en timeout car débranchée.
![image](https://user-images.githubusercontent.com/47687052/98677754-bf19c580-235d-11eb-8afc-6deea2102b21.png)

**Comment by battousai90** [comment]
Après pardon, les routes sont vides :
![image](https://user-images.githubusercontent.com/47687052/98683081-ec1da680-2364-11eb-9be6-d49d1278707b.png)

**Comment by KiwiHC16** [comment]
Les gars, c'est impossible de vous aider, ca part dans tous les sens. Imaginez pour nous qui cherchons a suivre ce que vous faites, essayons de traiter plus de 100 issues en ce moment, plus les dev en cours.

Je ne sais plus par quel bout prendre votre sujet.

Je suis obligé d'être "emmerdant" et procéder par étape, désolé.

Tant que le premier soucis n'est pas réglé (lettre en trop en fin de nom) tout le reste est finalement perte de temps.

Puis je vous demander de faire un test et paratger le resultat:
- installer la beta
- refaire une inclusion d un module avec une lettre en trop
- partager le log AbeilleParser, Abeille lors de l inclusion
- et tester sur le nom.

**Comment by tcharp38** [comment]
Normal. J'allais dire la même chose. Je n'arrive pas à suivre non plus. Un pas apres l'autre

**Comment by battousai90** [comment]
Oui désolé, le ticket s'est transformé en Facebook.

Alors après install de la Beta, suppression d'un detecteur d'ouverture qui remontait un caractere special, réinclusion, toujours pareil :
![image](https://user-images.githubusercontent.com/47687052/98688410-196d5300-236b-11eb-9922-81d87c18dd45.png)

![image](https://user-images.githubusercontent.com/47687052/98688237-eb880e80-236a-11eb-9542-22a22820c4d7.png)

![image](https://user-images.githubusercontent.com/47687052/98688134-d4e1b780-236a-11eb-8810-9d58225679fe.png)

**Comment by battousai90** [comment]
Les logs
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5518021/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5518022/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Super, le soucis est clairement visible. Reste a aller voir ce qu'il se passe dans le code.

Abeille:
```
[2020-11-10 15:43:12][DEBUG] : message(topic='Abeille1/2733/0000-01-0005', payload='lumi.sensor_magnet.aq2')
[2020-11-10 15:43:12][INFO] : Recherche objet: lumi.sensor_magnet.aq2 dans les objets connus
[2020-11-10 15:43:12][DEBUG] : value:lumi.sensor_magnet.aq2 / trimmed value: ->sensor_magnet.aq2<-
[2020-11-10 15:43:12][DEBUG] : Template initial: {"sensor_magnet.aq2"
...
[2020-11-10 15:43:23][DEBUG] : message(topic='Abeille1/2733/0000-01-0005', payload='lumi.sensor_magnet.aq2Ñ')
[2020-11-10 15:43:23][DEBUG] : Update ONLINE Status
[2020-11-10 15:43:29][DEBUG] : message(topic='Abeille1/2733/0000-01-0005', payload='lumi.sensor_magnet.aq2Ñ')
[2020-11-10 15:43:29][DEBUG] : Update ONLINE Status
[2020-11-10 15:43:33][DEBUG] : message(topic='Abeille1/2733/0000-01-0010', payload='Ñ')
...

```

AbeilleParser:
```
[2020-11-10 15:43:11][debug] Abeille1, Type=8102/Attribut report, SQN=00, SrcAddr=2733, EndPoint=01, ClustID=0000, AttrID=0005, AttrStatus=00, AttrDataType=42, AttrSize=0016, DataByteList=lumi.sensor_magnet.aq2
...
[2020-11-10 15:43:23][debug] Abeille1, Type=0x8100/Read attribut response, SQN=ae, SrcAddr=2733, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42
[2020-11-10 15:43:23][debug]   Size of Attribute=0016
[2020-11-10 15:43:23][debug]   Data byte list (one octet pour l instant)=6c
[2020-11-10 15:43:23][debug]   Data byte=lumi.sensor_magnet.aq2Ñ
...

```

**Comment by KiwiHC16** [comment]
Le decodage sur Type=0x8100/Read attribut response AttrDataType=42 n est pas bon.

**Comment by tcharp38** [comment]
C 'est maintenant le meme que celui du 8102 donc ce dernier devait etre daubé.

**Comment by KiwiHC16** [comment]
Si c est le meme maintenant pourquoi le log est different. Si le decodage etait parfaitement identique je devrais avoir exactement le meme log ! Y a donc une difference.
Dans les deux cas le lenght est 0x16.

**Comment by tcharp38** [comment]
Tu marques un point ! Mais ca doit etre exactement le meme. J'appelle la meme fonction decode_8100_8102 dans les 2 cas.
Ce log vient de la beta ?

**Comment by KiwiHC16** [comment]
Non dans la beta ces log sont en commentaires. Je ne comprend pas quel soft tourne sur sa machine.

@battousai90: peux tu me dire ce qui est indiqué comme version dans la page de conf:
![Capture d’écran 2020-11-10 à 16 21 55](https://user-images.githubusercontent.com/8549674/98693661-db732d80-2370-11eb-95a6-cb4a12dcc6a0.png)

**Comment by tcharp38** [comment]
En regardant le code rapidement pour le type 0x42 je vois que l'AttrSize n'est que rarement utilisé.
Au contraire il y a du code du style
                    $voltage        = hexdec(substr($payload, 24 + 2 * 2 + 2, 2).substr($payload, 24 + 2 * 2, 2));

                    $voltage = hexdec(substr($payload, 24 + 2 * 2 + 2, 2).substr($payload, 24 + 2 * 2, 2));
                    $temperature = unpack("s", pack("s", hexdec( substr($payload, 24 + 21 * 2 + 2, 2).substr($payload, 24 + 21 * 2, 2) )))[1];
                    $humidity = hexdec( substr($payload, 24 + 25 * 2 + 2, 2).substr($payload, 24 + 25 * 2, 2) );

                    $voltage        = hexdec(substr($payload, 28+2, 2).substr($payload, 28, 2));
                    $lux            = hexdec(substr($payload, 86+2, 2).substr($payload, 86, 2));

Bref ca ne tient pas compte de l'AttrSize.
Mais la on parle de data brute (voltage, temp...) et non pas d'une chaine.

**Comment by KiwiHC16** [comment]
Oui c est pour des raison historique. Tout au debut je ne parvenais pas a faire fonctionner le bousin donc je codais en dur. Maintenant que cela fonctionne on peut faire des optimisations mais attention de ne pas casser le code.

Je le demande si le market jeedom a pris en compte la beta mise a dispo hier. Je vais investiguer ce point.

Je vais republier une beta en mettant la date pour etre sure du soft dont on parle parceque si @battousai90 repond que c est Beta alors je ne suis toujours pas sur du code qui tourne sur sa machine.

Je vais essayer de faire ca ce soir mais sans garanti ...

**Comment by battousai90** [comment]
Oups désolé j'ai restauré mon backup avant beta.
En fait j'ai téléchargé la branche beta sur le git et j'ai chargé le plug-in en Samba.
S'il  faut ressayer je pourrai le faire ce soir après 20H.

**Comment by KiwiHC16** [comment]
Ok alors je ne fais rien et tu refais les manips....

**Comment by battousai90** [comment]
Désolé, rien a voir avec le ticket, mais la beta ne veut plus s'installé.

Ajout de la Beta manuellement :
![image](https://user-images.githubusercontent.com/47687052/98698100-f5fbd580-2375-11eb-8ac3-f5240c66251f.png)
Mise a jour
![image](https://user-images.githubusercontent.com/47687052/98698176-0ad86900-2376-11eb-908e-2c31faf4bd87.png)
Echec
![image](https://user-images.githubusercontent.com/47687052/98698391-4115e880-2376-11eb-8563-f1afdb97a731.png)
[2020-11-10 16:59:19][ALERT] : [START UPDATE]
[2020-11-10 16:59:19][ALERT] : Début de la mise à jour de : Abeille 
[2020-11-10 16:59:19][ALERT] : Téléchargement du plugin...
[2020-11-10 16:59:19][ALERT] : Téléchargement de Abeille...
[2020-11-10 16:59:30][ALERT] : OK 
[2020-11-10 16:59:30][ALERT] : Décompression du zip...
[2020-11-10 16:59:33][ALERT] : OK 
[2020-11-10 16:59:33][ALERT] : Post-installation de Abeille...
[2020-11-10 16:59:33][ALERT] : Impossible d'installer le plugin. Le nom du plugin est différent de l'ID ou le plugin n'est pas correctement formé. Veuillez contacter l'auteur.
[2020-11-10 16:59:33][ALERT] : [END UPDATE ERROR]

![image](https://user-images.githubusercontent.com/47687052/98698857-cc8f7980-2376-11eb-9aaf-f091d04486c2.png)

**Comment by mickadam29** [comment]
Merci à vous 2. Ok on va s'en tenir au caractère supplémentaire. Je vais chercher de mon côté ce qui déconne. Et probablement revenir à la version 3.1c. Car là c'est vraiment galère.

**Comment by mickadam29** [comment]
L'un de vous peut-il m'expliquer comment bascule sur la beta ?
J'ai fait un git clone de la branche beta.
Je m'attendais à trouver un install.sh mais à priori non
Merci

**Comment by mickadam29** [comment]
OK. Trouvé la doc. J'ai configuré le market et installe la beta

![image](https://user-images.githubusercontent.com/36518012/98718318-978f2100-238e-11eb-95fc-1af4d0150a0c.png)

**Comment by tcharp38** [comment]
@mickadam29 Attention ! Je ne sais pas si c'est clair pour toi mais dans toutes tes manips et surtout quand une version à provoqué une regression, il faut revenir au precedent backup pour que la base Jeedom ne soit pas gardé corrompue pour la suite.
Ex: tu passes en beta et ca pourri le nom de tes equipements, ca ne suffit pas de revenir en stable. La DB Jeedom n'est pas remise à etat. Ca fait du sens pour toi ?

**Comment by mickadam29** [comment]
Oui. Je comprends tout à fait ça. Ce que je n'explique pas c'est tout le bazar qui est apparu d'un coup.
J'ai d'ailleurs fait des tests après avoir restauré Jeedom. Rien à changé.
Reste à revenir en 3.1c. Vu les tests que j'ai effectués et en particulier la restauration Jeedom, c'est déjà la première étape.
Ensuite je verrai pour les noms qui sont erronés. Car probablement qu'ils existaient avant la maj 3.1c

**Comment by mickadam29** [comment]
Pour information, j'ai restauré la version 3.1C
Redescendu la version stable du plugin Abeille en restaurant mon backup jeedom de samedi matin. Avant mise à jour de la zigate en 3.1d. Tous les noms sont corrects.
Or, en version 3.1d, j'avais déjà redescendu la même version du backup et les noms étaient erronés
Donc je vous confirme que Jeedom en V 4.0.61 + Abeille du 30/09 + Firmware 3.1d >>>> KO chez moi
Je veux bien vous fournir d'autres infos si nécessaire. Mais je vais patienter avant de mettre à jour Abeille et Firmware Zigate.

**Comment by mickadam29** [comment]
Dernier test: Restauration à date de ce matin. Les objets ont un caractère de trop. Donc oui, la mise à jour a endommagé la BDD.
Retour au backup de dimanche matin avant que la mise à jour 3.1d ne plante la BDD. Tout fonctionne à nouveau. 
Pas de latence dans les actions interrupteurs/ampoules (scénarios). Chaque appui est fonctionnel contrairement à la version 3.1D

Toutefois j'ai retiré mon interrupteur. Je vais attendre avant de l'inclure à nouveau. De même, j'ai retiré mes 3 prises IKEA qui me servaient de routeurs. Je perdrai qqs objets en timeout, mais je vais retirer tous les changements récents de l'équation.

Je vous tiens au courant.

Ce qui n'aura pas tardé. Au bout de 20/30 minutes, les noms des objets changent pour prendre un caractère supplémentaire. 
Cela semble concerné tous ceux qui sont Routeurs (IKEA et sirène PSE03), pour le moment. Les équipements à pile Xiaomi (détecteur de présence, interrupteur, capteur temp/hum) n'ont pas encore ce problème. Mais même s'ils ont des caractères supplémentaires, cela ne les empêche pas de bien fonctionner depuis le retour en 3.1c. 

Phénomène étrange : Après avoir eu des caractères supplémentaires, lorsque je repasse sur mes objets pour interroger le nom, ben tout est est redevenu correct. Il y a semble-t-il un côté très aléatoire à tout cela.

Encore merci à vous

**Comment by battousai90** [comment]
Bonjour,

Revenons au sujet des caractères.
Beta :
![image](https://user-images.githubusercontent.com/47687052/98770780-4e1cf100-23e3-11eb-88a5-fd189204f9bf.png)
Le caractère spéciale est bien la :
![image](https://user-images.githubusercontent.com/47687052/98770870-7d336280-23e3-11eb-973b-c5d7ad4b3f33.png)
Suppression de l'abeille
Ré inclusion en Beta
Check du nom, toujours le caractère spécial
![image](https://user-images.githubusercontent.com/47687052/98771297-65101300-23e4-11eb-8db6-8e1a32bb990b.png)

Logs joint
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5521882/Abeille.txt)
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/5521883/AbeilleCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5521884/AbeilleParser.txt)
[AbeilleSerialRead1.txt](https://github.com/KiwiHC16/Abeille/files/5521885/AbeilleSerialRead1.txt)

**Comment by mickadam29** [comment]
Pour info, après avoir débranché toutes mes prises IKEA, les premières impactées par les caractères, aucun autre objet n'a de caractère en trop. Et ce depuis plusieurs heures.

**Comment by battousai90** [comment]
@mickadam29 
Ils trouveront la solution tranquillement en analysant les logs que l'on fournit. Sans logs ils peuvent rien faire.

**Comment by mickadam29** [comment]
Le caractère supplémentaire n'est qu'une partie visible. 
Après avoir tout restauré hier soir : Jeedom et firmware j'ai par exemple ce matin récupéré le graphe du maillage. Perdu depuis mes opérations de mise à jour.
Les noms n'ont plus de caractères "parasites".  Je vois dans tes logs des messages liés au routage.  Comme j'ai la même chose j'ai viré mes prises pour ces 2 raisons : Impactées par le caractères et pb de maillage.

Je ne serai pas aussi insistant si cela ne concernait pas les objets type "interrupteurs". Je m'en fous de pus avoir la temp d'une pièce, mais être dans le noir car le scénario réagit 5 min après l'appui c'est énervant. C'est encore ce qui s'est passé ce matin. Donc les objets sont tous reconnus, les actions reconnues, mais le traitement prend trop de temps. 

![image](https://user-images.githubusercontent.com/36518012/98782500-5fbcc380-23f8-11eb-8fcf-03effbff6300.png)

**Comment by battousai90** [comment]
`Je ne serai pas aussi insistant si cela ne concernait pas les objets type "interrupteurs". Je m'en fous de pus avoir la temp d'une pièce, mais être dans le noir car le scénario réagit 5 min après l'appui c'est énervant. C'est encore ce qui s'est passé ce matin. Donc les objets sont tous reconnus, les actions reconnues, mais le traitement prend trop de temps.`
C'est pour cela que c'est en Beta, au pire revient en Firmware 3.0f et tout rentrera dans l'ordre pour toi.

**Comment by mickadam29** [comment]
Tout fonctionnait correctement depuis des mois en 3.1c
Mais comme j'arrive à la limite des 40 objets, je souhaite pouvoir étendre. Par la version de Zigate qui prendre en charge le déplacement la PDM ou en ajoutant des routeurs.
D'où les changements que j'ai effectués.
Je soupçonne que l'ajout de routeur dans la version actuelle de Abeille me pose des soucis. Au mieux, je restaure avec la version antérieure. Mais j'en suis pas là. Je regarde les logs de ce matin pour comprendre pourquoi les premières actions sur les interrupteurs sont aussi longues à être interprétées. Puis ensuite, tout fonctionne nickel.  Il faut que je sache si les trames des interrupteurs arrivent bien de suite au plugin, ou si elles se perdent en chemin.

**Comment by KiwiHC16** [comment]
SVP Ne melangons pas les sujet.
@mickadam29, peux tu ouvrir une issue pour ton systeme pendant que l on continue dans cette issue avec @battousai90.

**Comment by KiwiHC16** [comment]
@battousai90 la beta que tu as sur ton systeme est une vieille beta. Donc tu n'as pas le bon code. La beta n a pas ete pris en compte par le market jeedom. J'ouvre une issue pour resoudre ce probleme.

Il faudrait faire la manip en ligne de commande en ssh. Faire un git clone. Saurais tu faire ca ?

**Comment by battousai90** [comment]
je m'en doutait la date était suspecte.
je peux voir pour faire ca si on me guide un peu, jamais fais sous Jeedom le Git, 
Le clone on le fait dans le répertoire Abeille ?
Je peu me connecter au Slack de Piwii si tu veux ca sera plus simple.

**Comment by mickadam29** [comment]
@KiwiHC16 @battousai90 @tcharp38 
Je suis un énorme boulet !!!!
J'ai trouvé la cause de tous mes problèmes. Pour faire court, j'avais 2 objets SONOFF (détecteur de présence) appairés avec la zigate mais supprimés de jeedom. C'est d'ailleurs avec eux que j'ai découvert qu'un caractère s'ajoutait au nom.
Chaque fois que je passais devant ca mettais la grouille dans la zigate avec les trames en pagaille. Cf issue 1354

Pour en revenir au sujet, maintenant que tout est clean de mon côté, je veux bien te fournir des infos strictement liées au caractère en trop puisque très impacté. La dernière inclusion, il y a 5min  s'est bien passé. Le nom est correct.

Comme je te le disais, si je rebranche mes prise IKEA, celles-ci vont très rapidement mettre le bazar (elles auront un nom erroné) et les inclusions qui suivent sont foireuses car elles aussi auront un caractère de trop.

**Comment by mickadam29** [comment]
@KiwiHC16 
Et comme j'ai fait mon boulet, je viens de vider compte paypal sur ta cagnotte ! C'est peu mais je me sens mieux

**Comment by KiwiHC16** [comment]
La beta règle de soucis de char en trop sur le systeme de @battousai90 .
Attention la beta n est pas dispo sur le market suite a un soucis. Prendre la beta sur github directement.
Je clos cet issue.
@mickadam29 rendez vous dans l issue que tu auras ouverte.

**Comment by mickadam29** [comment]
@KiwiHC16 @battousai90 @tcharp38 

Pour ma part tout est rentré dans l'ordre. Aucun caractère ne s'ajoute à mes équipements. Y compris mes prises IKEA. 👍 

Pour en arriver là

Retour à la version 3.1C (Zigate)
Restauration de Jeedom à une date antérieure à l'application de la maj 3.1D
Extinction des 2 SONOFF qui ne sont pas encore reconnus dans Abeille. Plus de pollution des messages de tentative de création.
Que va-t-il se passer quand je vais les remettre sous tension ??? 
Suppression de mes prises IKEA de la ruche (pas de la Zigate / donc toujours connues)
Remise sous tension des prises, une par, une
Création automatique des objets dans Abeille, puisque connus par Zigate. Sans que je ne sois obligé de mettre en inclusion. 
Ces prises n'ont pas le caractère en trop.

Je peux donc dire que tout est OK. Sans la version beta.

**Comment by benoitfl** [comment]
Bonjour,
Savez vous quand la version stable sera dispo sur le market ? 
Merci,
