### ISSUE TITLE
TS0121 Tuya smart switch module

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#1361]
Bonjour,

Suite à #1328 

A moins qu'il ne s’agisse d'une erreur de nommage que sur ma plateforme, il faudrait corriger le nom du fichier dans "config/devices/TS0121/ "   TS01**1**1.json >> TS01**2**1.json".

Bien à toi,
ivan

**Comment by KiwiHC16** [comment]
Oui ca a ete corrige dans la version de dev. Sera dans la prochaine stable.
