### ISSUE TITLE
Jeedom Market ne prend plus le github: trop gros

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1362]
En forcant a la min la  prise en compte de la beta, le market plante avec l erreur:

Le fichier est trop gros (maximum 100mo)

**Comment by dams74** [comment]
Quelle parti prend autant de place?
100 Mo c'est énorme

**Comment by KiwiHC16** [comment]
@tcharp38, mauvaise nouvelle !
Je pense qu'il ne faille pas ajouter la doc au github sinon on tombe dans ce soucis. Il faut garder 2 github pour decoreller les soucis. 

Il y a une option git module qui met parait tres bien mais je ne la maitrise pas. Il faut investiguer. En gros tu as un github qui fait reference a d autre github et quand tu fais ton git clone sois tu demande juste ton git sois tu demandes ton git et tous les modules git dépendants.

Ce qui faut peut être aussi faire c est purger une partie de l historique Git. Je pense qu il y a des video que j avais mises dans le git qui prennent beaucoup de place et qui ne serve pas.

**Comment by KiwiHC16** [comment]
www-data@Abeille:~/html/plugins$ du -sh Abeille
502M	Abeille

Il faut que l on purge l historique mais je ne sais pas comment faire pour l instant. Une solution probable:
- rename Abeille en AbeilleOld
- creation de Abeille
- commit des sources

C est probablement le plus simple mais ton fork risque de resté connecté à KiwiHC16/AbeilleOld ...

**Comment by tcharp38** [comment]
Kiwi, tu dois enlever le repertoire .git dans ton calcul.
Je vois 24MB de docs. C'est tout.
Mais bon si tu veux on vire ca et on passe en sub module. Pas sur que ca soit moins compliqué que la solution actuelle SphinxToDoc mais dis moi.

**Comment by tcharp38** [comment]
@KiwiHC16 Assigne le moi.

**Comment by edgd1er** [comment]
ce one-liner permet de trouver les gros fichiers dans l'historique:
```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```
source: https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history

qq docs de 1mb mais qq videos de 15 a 60 mb et des captures d'écran entre 500 et 1Mo

**Comment by dams74** [comment]
je ne sais pas si tu as vu mais la doc dans les autres plugin est en .MD
![image](https://user-images.githubusercontent.com/2788955/98800804-3197ad80-2411-11eb-8b65-f9453e8ea2b0.png)
Tu es sure que ça va fonctionner en .html?

**Comment by battousai90** [comment]
Il y a 2 repertoires Doc :
Docs
Docs_gen
Ca fait 26 +24 = 50 Mo

C'est surtout les images des périphériques, elle sont même répétées, peut-être passé par des liens vers un host ?

**Comment by KiwiHC16** [comment]
Je ne sais pas comment le script du Forum Jeedom fait le calcul. Je sais qu'il vient chercher la beta et me dit error plus de 100Mo.

@dams74, la doc Abeille est tres importante par rapport aux autres docs et il y a une fonction de recherche c'est pour cela que je ne suis pas le format proposé par jeedom.

**Comment by KiwiHC16** [comment]
www-data@Abeille:~/html/plugins$ du -sh Abeille
502M	Abeille
www-data@Abeille:~/html/plugins$ cd Abeille
www-data@Abeille:~/html/plugins/Abeille$ du -sh .git
375M	.git

500-375 ca nous fait 125M > 100Mo

**Comment by KiwiHC16** [comment]
42M	core
248K	desktop
26M	docs
28M	docs_gen

1) On n a pas besoin de la doc sur ce git, ce qui fait qu'on peut recuperer 26+28.
-> facile a regler
2) Dans core, je pense que cela vient de la doc dans les repertoires doc des devices.
-> il faudrait trouver une solution simple et efficace

**Comment by tcharp38** [comment]
@KiwiHC16 
J'étais en train de bosser sur ce sujet mais j'ai voulu reproduire le pb avant.
Moi je n'ai aucun souci à installer la beta. Pas eu de messages d'erreurs m'indiquant une taille trop grande. Tu as refais une beta nettoyée ou j'ai loupé qqch ?

![image](https://user-images.githubusercontent.com/35221038/98855323-1d2cd280-245c-11eb-900a-8df592a31757.png)

**Comment by KiwiHC16** [comment]
As tu fais l installation depuis le market ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-11 à 20 41 57](https://user-images.githubusercontent.com/8549674/98856761-59f9c900-245e-11eb-8b14-bb48952073b2.png)

![Capture d’écran 2020-11-11 à 20 41 37](https://user-images.githubusercontent.com/8549674/98856728-4d757080-245e-11eb-8e2d-05b621af8055.png)

**Comment by tcharp38** [comment]
Par le market ? Non.
J'ai fait "+ plugins" 
![image](https://user-images.githubusercontent.com/35221038/98994054-8d585880-252f-11eb-818c-cba33b262dd0.png)

puis
![image](https://user-images.githubusercontent.com/35221038/98994120-a3661900-252f-11eb-8e0a-90acf95ea41d.png)

et enregistrer.
Pas de soucis rencontrés mais... je suis encore en Jeedom v3.
D'autre part quelle est la réalité de ce pb ? Cela veut il dire que personne n'a pu tester la beta via ce chemin ? Tu confirmes ?
Si oui peux tu retester en detruisant le contenu de "docs" dans ta prochaine beta-dev ?

**Comment by KiwiHC16** [comment]
On ne parle pas de la meme chose.
Dans Jeedom Market, tu as le plugin en version stable et en version beta.
Pour cela cela suppose que le market Jeedom est venu chercher les fichiers sur GitHub pour le mettre à disposition des utilisateurs. C est l upload qui pose probleme.
Toi tu vas chercher le plugin directement depuis github pour le mettre sur ton systeme.

**Comment by tcharp38** [comment]
Haaaaa ... sorry.
Je vais voir comment je fais et retester.

**Comment by KiwiHC16** [comment]
Beta:
www-data@Abeille:~/html/plugins$ du -sh Abeille
456M	Abeille
www-data@Abeille:~/html/plugins/Abeille$ du -sh .git
377M	.git

79M.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-13 à 10 36 08](https://user-images.githubusercontent.com/8549674/99057416-0d1c0c80-259c-11eb-8ccb-53aea9d4e209.png)

**Comment by tcharp38** [comment]
Ok confirmé donc.

**Comment by KiwiHC16** [comment]
Je clos et on continu: #1227
