### ISSUE TITLE
Problème inclusion

### ISSUE THREAD

**Issue by Obex200sx** [KiwiHC16/Abeille#1363]
Bonjour,
Le nom des devices change a chaque inclusions.
Ducoup les fichier .Json ne corresponde pas et le plugins ne crée pas les commande.
A chaque inclusion il ajoute une lettre en plus sur le nom:"Nom du device"E,x,r,~ ect...

**Comment by mickadam29** [comment]
@KiwiHC16 

Décidemment nous sommes nombreux.

**Comment by Obex200sx** [comment]
J'imagine que si je suis pas le seule, il y a pas de solution pour le moment ?

**Comment by mickadam29** [comment]
Visiblement @KiwiHC16 a une version beta qui corrige le problème.
Attends qu'il passe par là ou que le changement soit implémenté dans la stable.

**Comment by Obex200sx** [comment]
D'accord merci pour ce retour rapide de ta part.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Es tu passé en firmware 3.1d ?
(Oui la beta corrige le soucis - par contre je ne connais pas l origine car pendant des semaines tout les monde semblait ok. Je me demande si c est pas le firmware qui provoque ce souci).

**Comment by Obex200sx** [comment]
En effet je dirais que cela a commencé depuis le passage en version 3.1d.

**Comment by KiwiHC16** [comment]
Le mieux serait de revenir sur la 3.1c si tu peux, ou d'attendre la prochaine beta si ton systeme n'est pas trop impacté.

**Comment by Obex200sx** [comment]
Je peux pas j'ai malheureusement pas fait de sauvegarde.A tu une idée sur la dispo de la prochaine beta ?

**Comment by KiwiHC16** [comment]
D ici quelques jours quand aura resolu le probleme de market.
Si tu connais github tu peux deja la recuperer.

**Comment by Obex200sx** [comment]
L'idée sur github c'est de copier le code et de le remplacer avec j'explore?
Si oui quel partie du code il faut remplacer ?

**Comment by KiwiHC16** [comment]
Le code d'Abeille est dans /var/www/html/plugins/Abeille
Il faut l effacer et le remplacer par le code de github (branche beta)

Ne fais cette manipulation que si tu maitrises...

**Comment by Obex200sx** [comment]
Petit retour sur ma manip de ce matin j'ai essayer la beta sans résultat de mon coté.
J'ai donc essayer la Beta_dev, cela fonctionne avec la beta_dev les device son bien reconnue et les commandes ce crée bien.
Petite information je pense que le retour de puissance sur les module Legrand ne remonte plus sûrement du a la version du firmware de la clef zigate.
Puis-je faire un essaie pour t'avancer sur le sujet ?

**Comment by KiwiHC16** [comment]
Ok je clos car ca confirme le meme probleme et sera corrigé dans beta puis stable a venir.

Peux tu ouvrir un cas pour le sujet Legrand - retour puissance ?
