### ISSUE TITLE
Caractère en trop dans les noms

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1364]
@KiwiHC16 @tcharp38 

Par rapport à l'issue 1352

Pour ma part tout est rentré dans l'ordre. Aucun caractère ne s'ajoute à mes équipements (pour le moment). Y compris mes prises IKEA. 👍 

Pour en arriver là

Retour à la version 3.1C (Zigate)
Restauration de Jeedom à une date antérieure à l'application de la maj 3.1D
Extinction des 2 SONOFF qui ne sont pas encore reconnus dans Abeille. Plus de pollution des messages de tentative de création.
Que va-t-il se passer quand je vais les remettre sous tension ??? 
Suppression de mes prises IKEA de la ruche (pas de la Zigate / donc toujours connues)
Remise sous tension des prises, une par, une
Création automatique des objets dans Abeille, puisque connus par Zigate. Sans que je ne sois obligé de mettre en inclusion. 
Ces prises n'ont pas le caractère en trop.

Je peux donc dire que tout est OK. Sans la version beta. 
Peux-tu me dire par rapport à tes changements dans le code, si cela est possible que je me sois débarrassé du bug ? Ou est-ce un coup de chance ?

**Comment by mickadam29** [comment]
@KiwiHC16 

Tu indiques de ne pas activer le heartbeat.
Lors de mes soucis avec l'inclusion, les caractères en trop et tout le reste.... Cette fonction était active chez moi. Je m'en suis aperçu en lisant les logs ce matin. Je l'ai donc désactivé et cela fait partie des actions ci-dessus qui ont participé à la résolution des problèmes.

Note: Jeedom propose une fonction de Heartbeat dans la tuile "Logs et surveillance". Cette fonction n'est pas implémentée dans Abeille. Ne pas l'activer pour l'instant.

**Comment by KiwiHC16** [comment]
Oui le heartbeat n est pas géré dans Abeille donc ne pas l activer.

Il semble que le probleme de car de trop est en relaton avec les mises a jour du firmware 3.1d. 
La stable actuelle est ok avec le firmware 3.1c
Je pense qu on va annoncer le support de la prochaine stable avec le firmware 3.1d.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by mickadam29** [comment]
Merci @KiwiHC16 
Désolé d'avoir pollué avec mes soucis, mais le retour en 3.1C a corrigé tous mes bugs.
Depuis ce matin situation ok : Jeedom 4.0.61 / Abeille 30/09 et firmware 3.1C
Les nouvelles inclusions se font très bien
Et pour la cagnotte, je t'ai versé un petit pécule ce matin également

**Comment by KiwiHC16** [comment]
Super pour la cagnotte, ca permettra d investir dans un equipement et etendre les compatibilié pour tous ;-)

Pas de soucis pour ta solution, je prefere investiguer maintenant et trouver les soucis que lorsqu'on publiera une stable. 

Et le plus important et l echange et la bonne humeur ;-)

Content que ton rollback est fonctionné et que ton systeme soit up and runnniing

L histoire continue.

**Comment by mickadam29** [comment]
Et surtout redevenu très réactif

J'en profite, et après je te laisse, pour te demander si tu as une date pour l'intégration des SONOFF SNZB-03 (détecteur de mouvement)
Comme tu l'as peut-être lu, ceux-ci sont connus de ma zigate et Abeille tente de les créer. En vain. Mais surtout, s'ils détectent un mouvement, ben il mettent à genoux toute mon infra le temps de tenter de les créer. Je sais que tu vas travailler dessus. Peut-être sont-ils déjà dans la prochaine stable ?

**Comment by KiwiHC16** [comment]
Je suis en attende de livraison, encore qq semaines...
