### ISSUE TITLE
Ikea Tradfri Ampoule 1000lm

### ISSUE THREAD

**Issue by battousai90** [KiwiHC16/Abeille#1365]
Une de mes ampoules ne veut plus se réinclure sur la Beta du 11/11/2020, après c'est la seule que j'ai essayé d'inclure a nouveau car elle me faisait planter Homebridge, peut être que l'on ne peut plus inclure d'ampoule IKEA.
![image](https://user-images.githubusercontent.com/47687052/98817642-b216d800-242a-11eb-9582-e58ab6dd5e7f.png)
![image](https://user-images.githubusercontent.com/47687052/98818544-01a9d380-242c-11eb-8f39-35559190ca1b.png)
[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/5524293/AbeilleCmd.txt)
[AbeilleSerialRead1.txt](https://github.com/KiwiHC16/Abeille/files/5524295/AbeilleSerialRead1.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5524296/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5524297/Abeille.txt)
Voila la référence de l'ampoule en question
https://zigbeealliance.org/fr/zigbee_des-produits/tradfri-led-e27-1000lm-opale-dimmable-sans-fil-4/
![image](https://user-images.githubusercontent.com/47687052/98816603-35372e80-2429-11eb-8379-bf564868e354.png)

**Comment by mickadam29** [comment]
Tu es en 3.1D à ce que je vois
Bon courage. 
Suis repassé en 3.1C et tout fonctionne à merveille, avec d’autres changements également. Donc 3.1D peut-être hors de cause.
Et, en particulier, en supprimant justement les équipements inconnus car cela rendait la zigate trop bavarde sur le réseau 
Mais c’est dans cette version que je n’ai plus de problème avec les équipements IKEA type routeur. Dont ta prise fait partie.

**Comment by tcharp38** [comment]
Pour la 3.1d vous devez avoir au moins la "beta". Sinon attendre la prochaine stable.

**Comment by mickadam29** [comment]
merci @tcharp38 
C'est la conclusion à laquelle je suis arrivé.
Et la seconde, investir dans une pizigate (et recyclé un raspberry coincé dans un placard depuis longtemps) pour avoir un environnement de test complet.
Test des montées de version : jeedom, plugin Abeille, firmware et valider qu'il n'y a pas de régression. Cela permettra de valider la bonne inclusion d'un objet avant de le faire en prod. Comme au taf  : DEV  /  RE7  / PROD

**Comment by battousai90** [comment]
> Pour la 3.1d vous devez avoir au moins la "beta". Sinon attendre la prochaine stable.

C'est le cas, fraichement installée par Kiwi
![image](https://user-images.githubusercontent.com/47687052/98838467-9a4c4d80-2444-11eb-93e2-37b57d606804.png)

**Comment by KiwiHC16** [comment]
AbeilleParser:
```
C110
TRADFRI bulb E27 WW 806lm
TRADFRIbulbE27WW806lm.json donc elle est connue par Abeille.

664E
TRADFRI bulb E27 W opal 1000lm
TRADFRIbulbE27Wopal1000lm.json celle ci est aussi connue pas par Abeille.
```

Abeille:
```
[2020-11-11 14:31:24][DEBUG] : message(topic='Abeille1/664E/0000-01-0005', payload='TRADFRI bulb E27 W opal 1000lm')
```

**Comment by KiwiHC16** [comment]
As tu dans Abeille un equipement à l adresse 664E ? Si oui peux tu le supprimer et refaire l inclusion ?
(et partager les log Abeill et AbeilleParser)

**Comment by battousai90** [comment]
Oui j'ai bien cette abeille, c'est celle de mon premier post avec les log.

**Comment by battousai90** [comment]
Pardon; 
La suppression a déjà été tenté 4 fois; d’où la création du ticket. 
Le screenshot et les logs sont les résultats de la 5 émet inclusion.

**Comment by KiwiHC16** [comment]
AbeilleParser
```
[2020-11-11 14:31:35][info ] Zigate1 en mode INCLUSION
...
[2020-11-11 14:31:36][debug] Abeille1, Type=8100/Read individual attribute response, SQN=23, Addr=664E, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=001E, DataByteList=TRADFRI bulb E27 W opal 1000lm
...
[2020-11-11 14:31:36][debug] Abeille1, Type=8045/Active endpoints response, SQN=C9, Status=00, ShortAddr=664E, EndPointCount=01, EndPointList=; 01
...
[2020-11-11 14:31:41][debug] Abeille1, Type=8043/Simple descriptor response, SQN=CA, Status=00, ShortAddr=664E, Length=20, EndPoint=01, Profile=C05E (ZLL Application Profile), DeviceId=0100 (Dimmable light), BitField=02
[2020-11-11 14:31:41][debug]   InClusterCount=08
[2020-11-11 14:31:41][debug]   InCluster=0000 - General: Basic
[2020-11-11 14:31:41][debug]   InCluster=0003 - General: Identify
[2020-11-11 14:31:41][debug]   InCluster=0004 - General: Groups
[2020-11-11 14:31:41][debug]   InCluster=0005 - General: Scenes
[2020-11-11 14:31:41][debug]   InCluster=0006 - General: On/Off
[2020-11-11 14:31:41][debug]   InCluster=0008 - General: Level Control
[2020-11-11 14:31:41][debug]   InCluster=0B05 - Diagnostics (DIAGNOSTICS_CLUSTER)
[2020-11-11 14:31:41][debug]   InCluster=1000 - ZLL: Commissioning
[2020-11-11 14:31:41][debug]   OutClusterCount=04
[2020-11-11 14:31:41][debug]   OutCluster=0005 - General: Scenes
[2020-11-11 14:31:41][debug]   OutCluster=0019 - General: OTA
[2020-11-11 14:31:41][debug]   OutCluster=0020 - General: Poll Control
[2020-11-11 14:31:41][debug]   OutCluster=1000 - ZLL: Commissioning
```

Abeille:
```
[2020-11-11 14:31:25][DEBUG] :   L'objet 'Abeille1/664E' existe mais pas la cmde 'SimpleDesc-01-DeviceDescription' => message ignoré
```

Dans le logs que tu as fourni on voit l ampoule qui est interrogée par Abeille dans AbeilleParser. Par contre on voit dans le log Abeille que l'objet existe.

Ce qui me fait penser que soit l equipement existait deja quand tu as pris les logs, soit que tu as partager des logs pris "trop" tard.

D'ou ma demande.

Je vois dans ta capture d ecran 14:31:04. Et le log Abeille commence a [2020-11-11 14:31:24].

Donc j ai besoin que tu refasses le test. Augmente la longueur du log de 500 à 5000 le temps du test dans Jeedom si tu veux.

**Comment by KiwiHC16** [comment]
Le code est:
log::add('Abeille', 'error', 'Nouvel équipement \''.$device.'\' inconnu. Utilisation de la config par défaut.');

Donc je ne sais pas pourquoi mais $device est vide. Il faut trouvé pourquoi.

Et pour cela j ai besoin des logs de ton test.

**Comment by battousai90** [comment]
Voilà.
Par contre ce que je trouve bizarre, c'est que j'ai les message d'inclusion très vite, normalement on éteint et allume 6 fois, l'ampoule clignote et ca s'inclus, la au bout de la 2 ou 3eme fois j'ai les message d'inclusion.

[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5530004/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5530005/Abeille.txt)

**Comment by KiwiHC16** [comment]
TMalheuresement toujours pas les bonnes infos dans le log. Je vais trouver une ampoule et voir si je parviens à reproduire le soucis.

**Comment by battousai90** [comment]
Je comprend pas pourtant 
![image](https://user-images.githubusercontent.com/47687052/98931102-dda6ca80-24dd-11eb-8ce5-0d2fdbdd1360.png)

**Comment by battousai90** [comment]
et la ?
[Abeille.zip](https://github.com/KiwiHC16/Abeille/files/5530071/Abeille.zip)

**Comment by battousai90** [comment]
C'est normal cette ligne ?

`[2020-11-12 11:58:00][debug] Abeille1, Type=8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=D0 (ZPS_NWK_ENUM_ROUTE_DISCOVERY_FAILED->Attempt at route discovery has failed due to any reason except lack of table space), Addr=664E`

**Comment by KiwiHC16** [comment]
Je viens de tester avec une ampoule ikea. Cela fonctionne.

Il faudrait que tu fasses les tests suivants:
- tu eteins l ampoule électriquement
- tu supprimes l ampoule de jeedom
- tu allumes l ampoule électriquement
- elle doit etre créée dans Abeille

Dans les log AbeilleParser, tu dois pouvoir voir une ligne comme celle ci passer:
[2020-11-12 12:21:00][DEBUG] : value:TRADFRI bulb E27 WW clear 250lm / trimmed value: ->TRADFRIbulbE27WWclear250lm<-

Bien sur avec le bon nom d ampoule.

Peux tu partager cette ligne ?

**Comment by battousai90** [comment]
Désolé pour mon ignorance, c'était pas la bonne valeur a 5000.
J'ai changé la bonne cette fois ci, ca devrait être bon :
[Abeille (1).txt](https://github.com/KiwiHC16/Abeille/files/5530272/Abeille.1.txt)
[AbeilleParser (1).txt](https://github.com/KiwiHC16/Abeille/files/5530273/AbeilleParser.1.txt)

**Comment by battousai90** [comment]
Je viens de suivre le mode opératoire et toujours pareil
[Abeille (2).txt](https://github.com/KiwiHC16/Abeille/files/5530315/Abeille.2.txt)
[AbeilleParser (2).txt](https://github.com/KiwiHC16/Abeille/files/5530316/AbeilleParser.2.txt)

J'ai éteint l'ampoule
Je l'ai supprimé
J'ai lancé l'inclusion
Je l'ai allumé, et au bout de 4 fois les deux messages, avec le fameux Inconnu.

**Comment by KiwiHC16** [comment]
On voit le probleme ici avec trimmed value qui est vide:
```
[2020-11-12 12:25:23][DEBUG] : message(topic='Abeille1/664E/0000-01-0005', payload='TRADFRI bulb E27 W opal 1000lm')
[2020-11-12 12:25:23][INFO] : Recherche objet: TRADFRI bulb E27 W opal 1000lm dans les objets connus
[2020-11-12 12:25:23][DEBUG] : value:TRADFRI bulb E27 W opal 1000lm / trimmed value: -><-
```

Je ne comprends pas.

Peut on refaire une session anydesk ?

**Comment by KiwiHC16** [comment]
.

**Comment by battousai90** [comment]
ce soir après 18h

**Comment by KiwiHC16** [comment]
Vers 21h peut etre possible pour moi.

**Comment by battousai90** [comment]
Ca va faire tard pour jouer avec l'ampoule de mon côté, au pire on peut voir ça ce week-end.

**Comment by KiwiHC16** [comment]
Ok

**Comment by KiwiHC16** [comment]
Quand serais tu dispo ?

**Comment by battousai90** [comment]
Désolé réponse tardive, j'ai été très pris :(
Je serai dispo à partir de jeudi si tu veux je serai en Week-end prolongé.

**Comment by KiwiHC16** [comment]
Ok, je te tiens au courant.

**Comment by battousai90** [comment]
Bon apparement le problème est plus général; j’ai la même chose sur une prise IKEA.

**Comment by battousai90** [comment]
Je viens d'installer la dernier béta 
Version Abeille :beta, 2020-11-21 00:58:04
Les inclusion d'ampoule et de prise IKEA refonctionne à merveille avec le Firmware 3.1d
Merci pour ce travail Kiwi, on peut fermer le ticket.
