### ISSUE TITLE
0302/Message inconnu

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1369]

**Comment by KiwiHC16** [comment]
[2020-11-11 22:53:47][debug] Abeille1, Type=0302/Message inconnu, ignoré (non supporté).

**Comment by tcharp38** [comment]
Commande non documentée. Je log un bug "doc" chez Zigate.

**Comment by KiwiHC16** [comment]
Je ne trouve pas 0x0300 dans https://zigate.fr/documentation/commandes-zigate/
