### ISSUE TITLE
Force isVisible: dispo dans la conf du plugin

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#137]
Ajout d un champ pour activer desactiver le forcage du isvisible. En cours...

**Comment by KiwiHC16** [comment]
Bonne idée.
Veux tu mettre ce champ dans le config du plugin ?

**Comment by edgd1er** [comment]
oui, c 'est ça. le code est fait, je suis en train de tester. Du coup, je suis à la bourre ce matin ;)

**Comment by KiwiHC16** [comment]
Je viens de tester ca semble marcher. Je clos le point.
