### ISSUE TITLE
Legrand - retour puissance

### ISSUE THREAD

**Issue by Obex200sx** [KiwiHC16/Abeille#1373]
Bonjour,
Je n'ai plus de retour puissance sur les modules Legrand, je suppose depuis la mise a jour de la zigate en version 3.1d.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ta discription est un peu courte ;-)

Peux tu dire quels modules ?

Version Firmware Zigate , Version Abeille  ?

**Comment by Obex200sx** [comment]
Sur les modules prise et sortie de cable Legrand :
 - 064879
 - 600698

La version d'abeille : beta dev 
La version de la la zigate 3.1d

**Comment by KiwiHC16** [comment]
Beta sur le market = Stable
3.1d n est pas supporté par la stable actuelle.

**Comment by Obex200sx** [comment]
J'ai intégré la beta dev dispo sur le github pour corriger le problème inclusion des modules.

**Comment by KiwiHC16** [comment]
Et est ce que cela fonctionne ?

**Comment by Obex200sx** [comment]
Non pas de retour de puissance.

**Comment by KiwiHC16** [comment]
Peux tu me donner le nom des equipements en questions (commande nom -> tester)

**Comment by Obex200sx** [comment]
le nom c'est --> "Connected Outlet"

**Comment by tcharp38** [comment]
Salut @Obex200sx 
Es tu toujours interessé par cet antiquité de sujet ?

**Comment by Obex200sx** [comment]
Bonsoir,
Je suis passé sous le plugin zibee officiel donc plus besoin merci a toi.

**Comment by tcharp38** [comment]
Ok.
Si personne pour bosser sur ce sujet je clos.
A reouvrir si besoin.

**Comment by tcharp38** [comment]
@Obex200sx 
Une derniere question; plugin zigbee officiel mais tu utilises toujours une zigate ou tu as migré sur un autre bridge aussi ?
