### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1375]
Autrement sur mon environnement en prod (NUC), j’ai un pb avec le plugin Abeille qui fait appel à des liens en direct sur /var/www/html en particulier en cas d’erreur. Serait-il possible de modifier pour avoir des liens relatifs pour être indépendant de l’endroit de l’install jeedom?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Rappelle toi que le chemin du plugin est collé en dur dans Jeedom meme, a de nombreux endroits. Il y a eu ce debat. Tu te souviens ?
Du coup tu as un exemple de cas ou ca merde ?
Et oui des liens avec "/var/www/html" ca devrait pas exister.

**Comment by KiwiHC16** [comment]
ca vient de pphil
https://community.jeedom.com/t/plugin-abeille-livolo/25031/46

Sinon je ne me souviens pas de la discussion...

**Comment by tcharp38** [comment]
Il y avait eu un utilisateur qui avait installé le plugin (voir Jeedom) a un endroit non standard et rien ne fonctionnait.
Pour cause, Jeedom lui meme ne supporte pas une installation "non standard", donc ca doit etre forcement en "/var/www/html".

**Comment by pphil78** [comment]
Bonjour, jeedom marche pourtant bien dans mon environnement. Je suis passé  en 4.0.61 sans pb. J'ai un roundcube et jeedom qui sont actifs, je ne peux donc pas laisser la racine à jeedom.
J'ai constaté le pb lorsque j'ai voulu modifier la canal pour faire mes tests sur mon inter LIVOLO. J'ai donc modifié le lien dans Abeille.php vers AbeilleFormAction.php mais ca n'a pas suffit.

En faisant une recherche sur /var/www/html dans le plugin il y en a un bon nombre:

core/config/addParameterToAllTemplates.php
6:    // www-data@Abeille:~/html/plugins/Abeille/core/config/devices$ php addParameterToAllTemplates.php /var/www/html/plugins/Abeille/core/config/devices '"configuration": {' '"configuration": {\n\t"uniqId": "UNIQUEID",'

core/class/AbeilleParser.php
19:        ini_set('error_log', '/var/www/html/log/AbeillePHP');

core/class/AbeilleCmd.php
17:        ini_set('error_log', '/var/www/html/log/AbeillePHP');
876:                $f=fopen("/var/www/html/log/toto","w");

core/class/AbeilleSocat.php
18:        ini_set('error_log', '/var/www/html/log/AbeillePHP');

core/class/AbeilleSerialRead.php
11:     * /usr/bin/php /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php <AbeilleX> <ZigatePort> <DebugLevel>
23:        ini_set('error_log', '/var/www/html/log/AbeillePHP');

core/class/AbeilleZigate.php
9:    // ini_set('error_log', '/var/www/html/log/AbeillePHP');

desktop/modal/inconnu.php
18:$cmd = "grep -e 'existe mais pas la cmde' /var/www/html/log/Abeille | grep -v 'ff01' ";

desktop/modal/listeCompatibilite.php
69:    foreach ( glob( '/var/www/html/plugins/Abeille/core/config/devices/*/*.json') as $file ) {

desktop/modal/getCompleteAbeilleConf.php
79:    getFileAndPrint('/var/www/html/plugins/Abeille/plugin_info/AbeilleVersion.inc', "{{Version from AbeilleVersion.inc}}", 1, 1);

plugin_info/configuration.php
278:                            foreach (ls('/var/www/html/plugins/Abeille/Zigate_Module/', '*.bin') as $value) {

Network/TestSVG/NetworkGraph.php
783:            if (file_exists("/var/www/html/plugins/Abeille/Network/TestSVG/images/AbeilleLQI_MapData_Perso.png")) {

resources/updateFirmware.sh
6:PROG=/var/www/html/plugins/Abeille/Zigate_Module/JennicModuleProgrammerRPI3
7:FW_DIR=/var/www/html/plugins/Abeille/Zigate_Module

resources/syncconf.sh
4:cd /var/www/html/plugins/Abeille/core/config/
7:cd /var/www/html/plugins/Abeille
17:cd /var/www/html/plugins/Abeille/tmp/Abeille-master
18:mv images /var/www/html/plugins/Abeille
19:chmod -R 755 /var/www/html/plugins/Abeille/images
21:cd /var/www/html/plugins/Abeille/tmp/Abeille-master/core/config/
22:mv devices /var/www/html/plugins/Abeille/core/config/
23:chmod -R 755 /var/www/html/plugins/Abeille/core/config/devices
25:cd /var/www/html/plugins/Abeille/

**Comment by tcharp38** [comment]
Ok je comprends que le truc en dur soit "crade" mais je pige pas le but de 
"J'ai donc modifié le lien dans Abeille.php vers AbeilleFormAction.php mais ca n'a pas suffit."

**Comment by pphil78** [comment]
Tu as raison c'est le form action="/plugins/Abeille/desktop/php/AbeilleFormAction.php" method="post" qui me posait pb que j'ai modifiée en form action="plugins/Abeille/desktop/php/AbeilleFormAction.php" method="post" c'est ensuite que je suis tombé sur des pb avec le fichier log qui était introuvable : The stream or file "/var/www/html/core/class/../../log/plugin" could not be opened: failed to open stream: Permission denied

**Comment by KiwiHC16** [comment]
@pphil78 pourrais tu proposer un PR pour modifier ces liens ?
(Qu est ce que c 'est :  roundcube ?)

**Comment by pphil78** [comment]
PR ?
Roundcube c'est un webmail. Je gère moi même ma messagerie.

**Comment by KiwiHC16** [comment]
PR: Pull Request
Si tu sais utiliser Git (GitHub), tu peux faire les corrections, les vérifier sur ton systeme et proposer les corrections pour tout le monde sous la forme d un PR et ensuite je l accepte et c'est ajouté au code pour tous.

**Comment by pphil78** [comment]
Non, jamais eu l'occaz. Je regarde si j'arrive a m'en débrouiller.

**Comment by KiwiHC16** [comment]
Ok super. Dis si tu as besoin d un petit coup de pouce.

**Comment by tcharp38** [comment]
> Non, jamais eu l'occaz. Je regarde si j'arrive a m'en débrouiller.

Je te suggere de ne modifier qu'un fichier et tenter ce PR reduit jusqu'au bout.

**Comment by tcharp38** [comment]
Plusieurs liens déja fixés sous le master

**Comment by KiwiHC16** [comment]
Est ce qu il y a encore du boulot a faire ou on peut clore ?

**Comment by tcharp38** [comment]
Je crois qu'on a tout viré.
On peut clore et reouvrir s'il en manque.
