### ISSUE TITLE
Ajout de tooltip pour aider l utilisateur dans la config du plugin

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#138]
En cours..

**Comment by KiwiHC16** [comment]
Bonne idée.

**Comment by KiwiHC16** [comment]
J'ai vu que tu sais envoyer des messages d alertes sur le dashboard. Qu'elle est le fonction pour faire cela ? Je voudrais afficher un message d'alerte en haut du dashboard quand on crée un nouvel objet.

**Comment by edgd1er** [comment]
Ajout du message:
   message::add('Abeille', 'Mise à jour en cours...', null, null);  
retrait des messages du plugin:
message::removeAll('Abeille');

la doc de l'api avec ses commentaires et l'aide :(
https://jeedom.github.io/documentation/phpdoc/classes/message.html#method_add
Je n'ai pas creusé l'utilisation des autres paramètres.

**Comment by KiwiHC16** [comment]
Super merci

**Comment by KiwiHC16** [comment]
Merge et ca marche alors je clos cet issue. On pourra ajouter des ToolTips au fil de l'eau maintenant.
