### ISSUE TITLE
Icone de produit defini par utilisateur.

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1383]
@KiwiHC16 

Pourrais-tu nous indiquer comment te proposer des images png pour les associer aux objets ?
J'ai un png qui correspond aux sirènes PSE03-v1.1.0 dont tu as fais le modèle mais qui à l'image d'un autre appareil du marché.
Le png est fonctionnel en le plaçant dans Abeille\images\node_PSE03-v1.1.0 (transparent et résolution de 360x360)
et en modifiant le nom de l'icône dans Abeille\core\config\devices\PSE03-v1.1.0\PSE03.v1.1.0.json

Cela fonctionne chez moi, mais à chaque mise à jour, je recommence car mon modèle change (json) et son contenu (le nom de l'icone) avec. Evidemment remplacés par ta version.

Merci à toi 

{
  "PSE03-v1.1.0": {
    "nameJeedom": "Alarm PSE03-v1.1.0",
    "timeout": "60",
    "Comment": "Draft",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c76626sdesdfsde88a",
      "icone": "**PSE03-v1.1.0**",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "ZCLVersion",
      "include5": "dateCode",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include28": "setReportEtat",
      "include28 2": "writeAttributeRequestIAS_WD_Flash",
      "include28 2 2": "writeAttributeRequestIAS_WD_Sound",
      "include28 2 2 2": "writeAttributeRequestIAS_WD_FlashSound"
    }
  }
}

![image](https://user-images.githubusercontent.com/36518012/99143792-a44a9800-2660-11eb-8d25-f0ad510313b9.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
