### ISSUE TITLE
Valeur non initialisée

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1385]
https://github.com/KiwiHC16/Abeille/blob/dbcf777437fd12a7a7a6d2239dfec7c8c85f8551/core/class/Abeille.class.php#L55

y aurait il un mix ci dessous ?
``` 
$IEEE = $ghost->getConfiguration('IEEE','none');
            if ( $ghostIEEE == 'none' ) {
```

not defined:
https://github.com/KiwiHC16/Abeille/blob/dbcf777437fd12a7a7a6d2239dfec7c8c85f8551/core/class/Abeille.class.php#L1924
https://github.com/KiwiHC16/Abeille/blob/dbcf777437fd12a7a7a6d2239dfec7c8c85f8551/core/class/Abeille.class.php#L2061

**Comment by KiwiHC16** [comment]
Line 55 corrigé

Line 1924: je ne vois pas de soucis

Line 2061: Zone de test, ce n est pas important.
