### ISSUE TITLE
static ou this 

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1386]
https://github.com/KiwiHC16/Abeille/blob/ce748a03c784992277fce0e8ebd57b20eef120ef/core/class/AbeilleParser.php#L3542

static + self ou new + this

https://stackoverflow.com/questions/151969/when-to-use-self-over-this

**Comment by KiwiHC16** [comment]
Dans Abeile, j'ai essayé de passer en mode objet mais il reste des appels directs vers les fonctions de class sans instanec d objet.

Mais surtout:
Il faut noter aussi que certaines fonctions sont appelées directement par le core de jeedom.

Du fait de ce melange des fois on a un appel direct a la fonction self::fonctionToto() et des fois $this-> fonctionToto()
...

Ca fonctionne mais ce n est pas toujours très clair.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by edgd1er** [comment]
oui, avoir des daemons statiques etaient pas forcément une bonne décision de la part de jeedom....

 la le point c'est que la fonction utilise this, alors qu elle est statique, mais ce n'etait pas clair dans ma description.
un $this->fonction() ne genere pas une erreur dans une fonction statique ? je ne suis pas un pro du PHP :)

**Comment by tcharp38** [comment]
Tu as raison. Ca genere des erreurs normalement.
Encore faut il que les err PHP soient actives à ce moment. Ca n'est peut etre pas le cas ici
