### ISSUE TITLE
PHP Notice:  Undefined variable: arg1 in /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php on line 78

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#1387]
Petite cocquille je pense:
PHP Notice:  Undefined variable: arg1 in /var/www/html/plugins/Abeille/core/class/AbeilleSerialRead.php on line 78

$abeilleNb = (int)substr($arg1, 7); // Zigate number (ex: 1)

cela ne devrait-il pas être $abeilleNb = (int)substr($argv[1], 7); // Zigate number (ex: 1)

Kaléo.

**Comment by tcharp38** [comment]
Tu vois ca sur quelle branche ?

**Comment by tcharp38** [comment]
Je viens de verifier. Ca n'est déja plus le code sur la derniere beta.
Je te laisse confirmer et cloturer.
Merci pour le retour.

**Comment by edgd1er** [comment]
ah, je dois faire un rebase sur beta  alors pour avoir qq chose de correct ?

**Comment by tcharp38** [comment]
Non, les dev doivent etre realignes sur la derniere master avant tout PR.
Ce que je voulais dire c est que deja sur la beta (une vielle master maintenant :)) ce defaut n'etait pas la.
Ou j'ai mal compris ton souci ? Dis moi.

**Comment by kaleofr** [comment]
Je confirme, c'est présent sur la version stable.
Je viens d'essayer de passer en beta et Abeille a juste ... disparu! info.json introuvable ( 0bytes), class 'Abeille' not found,...)
J'ai essayé par deux fois.
Bref, retour stable!
