### ISSUE TITLE
Recuperer le niveau des batteries de la telecommnade Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#139]
Info est transmise lors de l association de la telecommande avec la GW Ikea.

**Comment by KiwiHC16** [comment]
La zigate ne remonte pas l info alors qu'elle est envoyée par la télécommande.

![capture d ecran 2018-02-28 a 14 22 35](https://user-images.githubusercontent.com/8549674/36789834-343c64b4-1c93-11e8-811d-da341d5c22c4.png)

![capture d ecran 2018-02-28 a 14 22 58](https://user-images.githubusercontent.com/8549674/36789837-38c56cec-1c93-11e8-8bd7-011bacdeb90c.png)

![capture d ecran 2018-02-28 a 14 23 16](https://user-images.githubusercontent.com/8549674/36789841-3cce1a14-1c93-11e8-9ec0-878b50f6bddb.png)

La ZiGate transmet juste le Ok de l'envoie de la requête, message 8000, mais pas la réponse:
AbeilleParser 2018-02-26 22:03:04[DEBUG]-------------- 2018-02-26 22:03:04: protocolData size(20) message > 12 char
AbeilleParser 2018-02-26 22:03:04[DEBUG]Type: 8000 quality: 00
AbeilleParser 2018-02-26 22:03:04[DEBUG]type: 8000 (Status)(Not Processed)
AbeilleParser 2018-02-26 22:03:04[DEBUG]Length: 5
AbeilleParser 2018-02-26 22:03:04[DEBUG]Status: 00-(Success)
AbeilleParser 2018-02-26 22:03:04[DEBUG]SQN: 13

**Comment by KiwiHC16** [comment]
Quand le probleme ZiGate sera resolu on peut voir a faire un bind et un report sur les batterie. Voir mes notes.

**Comment by fairecasoimeme** [comment]
Fixed in next firmware 3.0e

**Comment by KiwiHC16** [comment]
Les trames 0xFF02 sont géré dans la 3.0e tout comme le cluster power configuration pour ikea

**Comment by KiwiHC16** [comment]
En testant la Zigate 30E pour module Wifi, j ai des infos qui remontent:

![capture d ecran 2018-08-13 a 14 01 04](https://user-images.githubusercontent.com/8549674/44030532-5afb5e52-9f01-11e8-886d-abaa283fd8d0.png)

`AbeilleParser 2018-08-13 13:59:13[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 03; Src Addr : 9300; End Point : 01; Cluster ID : 0001; Attr ID : 0021; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 2f`

![capture d ecran 2018-08-13 a 14 01 46](https://user-images.githubusercontent.com/8549674/44030569-720cffba-9f01-11e8-9779-839a3e9a991d.png)

Y a plus qu a faire...

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-08-13 a 14 14 06](https://user-images.githubusercontent.com/8549674/44031100-3451b434-9f03-11e8-876e-0ad5eff349ea.png)
