### ISSUE TITLE
Inclusion volet profalux & FW 3.1d

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1392]
J'ai finalement été contraint de refaire une inclusion d'un de mes volets qui fonctionnait depuis des mois.
Ils avaient étés inclus avec un FW anterieur au 3.1d.
La c'est clair qu'il y a encore qqch à creuser. L'inclusion semble bien se passer mais il ne reagit pas aux commandes monter/descente.
Je refais une inclusion en 3.1c et la c'est bon.

A creuser.
La 3.1d est toujours à deconseiller côté Abeille.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok, peux tu capturer le log AbeilleCmd et le Sniff Zigbee avec le firmware 3.1C et 3.1d ?

Peux tu partager un log AbeilleCmd et AbeilleParser avec la conf qui ne fonctionne pas quand tu fais monter/descendre ?

**Comment by tcharp38** [comment]
Je clos.
Pbs restants profalux => voir https://github.com/KiwiHC16/Abeille/issues/1994
