### ISSUE TITLE
Installation de la Beta depuis le market ne fonctionne pas.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1393]

**Comment by KiwiHC16** [comment]
https://community.jeedom.com/t/support-prise-blitzwolf-bw-shp13/35181/13

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Effectivement j'ai le même soucis.
![Capture d’écran 2020-11-18 à 10 36 18](https://user-images.githubusercontent.com/8549674/99512690-0e797a80-298a-11eb-92c3-d3b6de1bc98a.png)

**Comment by KiwiHC16** [comment]
L installation se fait car j ai tout dans les repertoire mais n'apparait pas dans Jeedom ! ?

Sauf que tous les fichiers dans le repertoire plugin info sont des coquilles vides !!!!!!!

Si je recupere le fichier zip depuis l interface dev du market, il contient bien toutes les infos ...

**Comment by KiwiHC16** [comment]
```
www-data@Abeille:~/html/plugins$ du -sh Abeille
471M	Abeille
www-data@Abeille:~/html/plugins/Abeille$ du -sh .git
383M	.git

Delta: 88M plus ou moins en ligne avec les 66M d Abeille.zip

Il faut encore reduire d 30M...
```

**Comment by KiwiHC16** [comment]
Deplacment de toute la doc spécifiques aux equipements dans la doc sur le web:
415M	Abeille
383M	.git
Delta: 32M

**Comment by tcharp38** [comment]
Tu l'as déplacé sous free alors ? Ou tu as reussi à resoudre le pb de fichier modifé AbeilleDoc ?

**Comment by KiwiHC16** [comment]
Le probleme vient de /tmp qui fait 128M et Abeille.zip qui fait 66M avec unzip x2 > 128M -> crash
