### ISSUE TITLE
Legrand Shutter switch with neutral

### ISSUE THREAD

**Issue by benoitfl** [KiwiHC16/Abeille#1397]
Hello,
Besoin d'aide pour l’intégration d'un legrand shutter switch with neutral.
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5545300/AbeilleParser.txt)

[2020-11-16 10:19:38][debug] Abeille1, Type=8043/Simple descriptor response, SQN=81, Status=00, ShortAddr=97B8, Length=1C, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=0202 (Window Covering Device), BitField=01
[2020-11-16 10:19:38][debug]   InClusterCount=07
[2020-11-16 10:19:38][debug]   InCluster=0000 - General: Basic
[2020-11-16 10:19:38][debug]   InCluster=0003 - General: Identify
[2020-11-16 10:19:38][debug]   InCluster=0102 - Window Covering
[2020-11-16 10:19:38][debug]   InCluster=0004 - General: Groups
[2020-11-16 10:19:38][debug]   InCluster=0005 - General: Scenes
[2020-11-16 10:19:38][debug]   InCluster=000F - General: Binary Input (Basic)
[2020-11-16 10:19:38][debug]   InCluster=FC01 - Legrand private
[2020-11-16 10:19:38][debug]   OutClusterCount=03
[2020-11-16 10:19:38][debug]   OutCluster=0000 - General: Basic
[2020-11-16 10:19:38][debug]   OutCluster=FC01 - Legrand private
[2020-11-16 10:19:38][debug]   OutCluster=0019 - General: OTA

J'ai du mal a croiser cela avec les commande dispo dans les Template...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2020-11-16 10:19:29][debug] Abeille1, Type=8100/Read individual attribute response, SQN=51, Addr=97B8, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=001F, DataByteList= Shutter switch with neutral
```

**Comment by KiwiHC16** [comment]
Je trouve le modele dans la version de dev.

Peux tu recuperer le fichier:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/Shutterswitchwithneutral

Et ses dépendances:
current_position_lift_percentage.json
getcurrent_position_lift_percentage.json
BindToZigateCurrent_Position_Lift_Percentage.json
setReportCurrent_Position_Lift_Percentage.json

Dans le repertoire:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/Template

**Comment by benoitfl** [comment]
Ok fichier récupérer, j'avais effectivement un .json.json, cependant les commandes ne fonctionnent pas. 
Je récupere bien le nom et le du fabriquant mais pas de up down stop et percentage.

**Comment by KiwiHC16** [comment]
@kaleofr est ce que cela fonctionne chez toi ?
Je suppose que oui car on a clos le cas
"Récupération d'état interrupteur filaire Legrand with Netatmo" #1163

**Comment by benoitfl** [comment]
Dans le parser de l'issue #1163 il n'a pas de legrand private. hum sounds weird !

**Comment by KiwiHC16** [comment]
Dans le deuxieme AbeilleParser tu ftrouve FC01 sans le commentaire car le code a évolué. C est identique.

**Comment by kaleofr** [comment]
> @kaleofr est ce que cela fonctionne chez toi ?
> Je suppose que oui car on a clos le cas
> "Récupération d'état interrupteur filaire Legrand with Netatmo" #1163

Oui, depuis fort longtemps :-)

**Comment by KiwiHC16** [comment]
Y a de l espoir pour @benoitfl alors ;-)

**Comment by kaleofr** [comment]
@benoitfl : 
As-tu également les json ci-dessous dans Template?
WindowsCoveringUp.json
WindowsCoveringStop.json
WindowsCoveringDown.json

**Comment by benoitfl** [comment]
@kaleofr Yes all 3.
Mon interr reste rouge fixe, tu confirmes que c'est une comportement normal ? J'ai vraiment aucune commande qui fonctionnent.
Ex : current_position_lift_percentage me retourne vide.

**Comment by kaleofr** [comment]
@benoitfl 
HA NON! 
Une fois le module associés, la diode s'éteint!
Lors de l'association elle doit passer de rouge à vert, puis lorsque la zigate arrète le mode inclusion la diode s'éteint.
Si le module est bien associé, lorsque l'on repasse en mode inclusion, la diode se rallume en vert.

Pour info, current_position_lift_percentage ne te retournera que 3 valeurs: 0%, 50% et 100%.

Bon courage, on y est presque!

**Comment by KiwiHC16** [comment]
Quel est le status de cette discussion ? On clos ?

**Comment by benoitfl** [comment]
J'ai toujours pas réussi à l'intégrer, sans trop comprendre pourquoi... 
Je vois pas pourquoi mon inter ne fonctionne pas alors qu'abeille le reconnait bien

**Comment by KiwiHC16** [comment]
Ok donc il y a du boulot....

**Comment by kaleofr** [comment]
Perso mes 10 fonctionnent.
La diode rouge a fini par s'éteindre?
Si non, c'est un problème d'associations, pas de Abeille. 

Pour moi c'est fonctionnel. Commandes individuelles et commandes de groupes.

**Comment by benoitfl** [comment]
Je peux t'envoyer le miens si tu le veux. Vu que j'ai encore mes standard.

**Comment by KiwiHC16** [comment]
C est un idée. 
Mondial relai ?

**Comment by benoitfl** [comment]
Ok, j'ai changé mon hub auto alimenté. J'ai récupéré mes équipements. Je pense que mon câble USB à été pincé et à causé un défaut du hub. Puis l'interrupteur volet il fonctionne maintenant, cependant Up et down et Down et up ... j'ai renommé les commandes. Tu peux close cette issu. merci

**Comment by KiwiHC16** [comment]
Super ;-)
