### ISSUE TITLE
Ajout commande info dans un equipement existant

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1399]
![Capture d’écran 2020-11-16 à 13 05 18](https://user-images.githubusercontent.com/8549674/99250740-773ae880-280c-11eb-809f-83aea14ae69c.png)

**Comment by tcharp38** [comment]
en cours

**Comment by KiwiHC16** [comment]
Génial !!!

**Comment by tcharp38** [comment]
Dans le master donc je clos. A reouvrir si bug.
