### ISSUE TITLE
Erreur retour info pression

### ISSUE THREAD

**Issue by Marc--** [KiwiHC16/Abeille#14]
Parfois le retour du topic  0403-0000 "pression1" est sur 4 bytes, parfois 5 ou 6. Ca semble lié à la présence ou pas des décimales.

Le topic 0403-0010 "pression" est affecté de la même manière, avec un facteur /10.

Ca fausse le retour sur le plugin.

**Comment by KiwiHC16** [comment]
Quel est le capteur qui remonte cette info ? Un Xiaomi aqara temperature carré ?

**Comment by edgd1er** [comment]
J ai eu le mm cas, assez rarement avec un capteur rond.

**Comment by Marc--** [comment]
Chez moi c'est un capteur Xiaomi Aqara carré.

**Comment by KiwiHC16** [comment]
Je viens de pousser dans master les corrections. Cela etait du au fait que les valeurs récupérées dans le data Xiaomi, ne sont identiques aux parametres publiques.
