### ISSUE TITLE
Master: AbeilleClass: CheckParameters: undefined variable

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1405]
https://github.com/KiwiHC16/Abeille/blob/a3c0ef2a0a02d7985d8ba118dec826942cff3064/core/class/Abeille.class.php#L1008

Après un rebase sur la master, ça clignote rouge dans mon ide.
La fonction checkParameters utilise la variable return ( non définie ) à la place de param.

idem pour les lignes 1009,1022, 1023, 1024, ....

Quelqu'un peut confirmer ? Est ce deja corrigé sur la dev ?

**Comment by tcharp38** [comment]
Salut.
C est tout aussi daubé chez moi.
Tu fixes ou je fais ?

**Comment by edgd1er** [comment]
je veux bien que tu les fasses, j'ai failli tt perdre dimanche avec un stash qui s'est ma passé. j'ai bcp de modif en cours....

**Comment by tcharp38** [comment]
Ok, ca marche.

**Comment by KiwiHC16** [comment]
Pas vu ce soucis.

**Comment by tcharp38** [comment]
Normal. L'erreur est belle et bien la mais la fonction n'est pas utilisée du tout.
C'est pourquoi elle ne ressort pas dans AbeillePHP je pense.
Je la commente en attente d'un futur menage si vraiment sans utilité.

**Comment by edgd1er** [comment]
je me demande si la mise en commentaire n'a pas été un peu trop large. La fonction statique postSave a été commentée également. Selon le [template](https://github.com/jeedom/plugin-template/blob/master/core/class/template.class.php) de plugin Jeedom , c'est un méthode appelé par le core de jeedom après chaque modification des paramètres du plugin. 

je pense que même si la fct ne fait rien, elle doit exister dans la class Abeille au moins vide pour éviter un log d'erreur, ou un traitement incomplet si l'erreur est catchée en silence. De ce que je comprends du template, les fonctions non commentées doivent être présentes même vide, celles commentées sont optionnelles.

Qu'en pensez vous ?

**Comment by tcharp38** [comment]
Ha oui j'ai été trop rapide.
Je suis descendu trop bas dans ma selection.
Je corrige de suite

**Comment by tcharp38** [comment]
Pour revenir à ton point, as tu vu qq part des erreurs generées à cause d'une fonction "Jeedom" manquante ?
Je crois bien qu'il inclut la class template. Ce qui fait que si le plugin ne fournit pas la fonction, il utilise sa version template vide.
Pour moi ca fait du sens de ne definir dans le plugin QUE les fonctions utiles au plugin.

**Comment by edgd1er** [comment]
non, je n'ais pas regardé le fonctionnement de chargement du plugin, je me basais juste sur la tete du fichier template, mais la doc de jeedom est comment dire... legere surtout pour les devs. 
Abeille etend eqLogic qui n'a pas ces fonctions. la classe plugin n'a pas ces fct non plus.
Si tu as vu un mécanisme qui défini par défaut, je suis intérréssé pour savoir comment.

**Comment by tcharp38** [comment]
@edgd1er 
J'ai recreusé un peu. 
Par ex il y a "preSave" qui peut etre defini et utilisé avant de sauver la config de la page de configuration.
Le code Jeedom fait 

      var postSave = $('#span_plugin_id').text()+'_postSaveConfiguration';
      if (typeof window[postSave] == 'function'){
        window[postSave]();
      }

Je ne comprends pas tout mais il me semble qu'il execute "preSave" du plugin si ce dernier existe.

Il y a d'autres lignes de code en PHP aussi qui testent si la methode existe
core/class/DB.class.php:                if (!$_direct && method_exists($object, 'preSave')) {
core/class/DB.class.php:                        $object->preSave();

Bref... tout ça pour dire que je pense que le plugin ne doit implementer que les fonctions minimales.
Les autres sont optionnelles et ca semble bien géré vu que je n'ai pas vu d'erreur dans ce sens.

**Comment by edgd1er** [comment]
@tcharp38 , merci pour la recherche. ok pr moi.
