### ISSUE TITLE
Température Philips Hue White and Color

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#1412]
Bonjour,

Je constate que dans les templates des bulbs Hue (celles que j'ai en tout cas, je n'ai pas vérifié les autres, c'est à dire LCA001, LCT001 et LCT015) il n'y a pas les commandes de gestion de la température de couleur : 
      "include37": "2200K",
      "include38": "2700K",
      "include39": "4000K",
      "include40": "temperatureLight",
      "include40 2 2": "setTemperatureLight",
alors qu'elles sont compatibles avec cette fonction, et vont de 2000K à 6500K. est-ce normal ?

J'ai pu tester à l'arrache et j'ai constaté que ces commandes semblent fonctionner. du coup, question subsidiaire, y-t-il un moyen de ré-appliquer un template sur une abeille déjà existante ou dois-je recréer les commandes à la main ?

Merci beaucoup.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
1) j ai ajouté ces commandes au modeles.
Dans la master maintenant.

**Comment by KiwiHC16** [comment]
2. _y-t-il un moyen de ré-appliquer un template sur une abeille déjà existante ou dois-je recréer les commandes à la main ?_
Malheuresement non, je pensais le faire, il y a eu un debut de solution a un moment mais ce n'est pas simple et source de trop de soucis donc je l ai enlevé. Comme tu dis le plus simple a ce jour est de supprimer et recréer ;-(

**Comment by KiwiHC16** [comment]
Je clos mais si tu as besoin, rouvre.

**Comment by elydan** [comment]
Salut, merci pour ton retour rapide !

Toujours aussi efficace ;)

J'ai fait en sorte d'avoir accès à toute la plage de température, dis moi si ça te convient ou si tu veux que je fasse quelque chose différemment.

Pour info j'ai mis des ID inventés et uniques (j'ai vérifié) dans les fichiers setTemperatureLight2.json et temperatureLight2.json.

Par contre je ne suis pas sûr de l'ajout de       "include41":  "5000K" (je ne sais pas si le 41 est cohérent, mais en tout cas ça fonctionne)

Enfin j'ai constaté que toutes les commandes de modification, que ce soit slider ou boutons avec valeur définie fonctionnent bien, mais pas la récupération de la température actuelle qui, elle, reste à 0K. je n'ai pas trouvé pourquoi, si tu as une idée ....

Merci et bonne journée !
