### ISSUE TITLE
tmp/Abeille_LQI_MapDataAbeille1.json.lock

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1413]
Bonsoir, après un passage en V4.1 j'ai perdu la quasi totalité des LDI. Si je lance un Refresh je récupère cette erreur :
![image](https://user-images.githubusercontent.com/52486183/99433238-8e153400-290d-11eb-9ab6-81786339197d.png).
Dans le messages, j'ai aussi une erreur javascript  
http://192.168.0.45/index.php?v=d&m=Abeille&p=Abeille	148	Uncaught ReferenceError: url is not defined
C'est sans doute une erreur de ma part. Merci de ton aide

**Comment by tcharp38** [comment]
Salut
tu es sur une version "stable" d'Abeille ?

En gros si tu es sur la derniere stable, le fichier en question se cache dans le plugin/Network/tmp.
Peut etre que le repertoire "tmp" n existe pas ou qu'il n'a pas les bons droits.

Le chemin complet devrait etre "/var/www/html/plugins/Abeille/Network/tmp"

**Comment by Kenderv** [comment]
Bonjour, et merci de ta réponse. Effectivement le répertoire tmp n'existait pas. Je l'ai créé, changé les droits, le propriétaire et le groupe rt je n'ai plus le message.
Oui, je suis sur la dernière stable 
![image](https://user-images.githubusercontent.com/52486183/99495359-d155be00-2972-11eb-8b1e-f69681e02ba5.png)

**Comment by KiwiHC16** [comment]
Oui c est un "vieux" bug.
Je clos. Rouvrir si besoin.
