### ISSUE TITLE
Icone "refresh" ne s'affiche plus en Jeedom v4

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1417]

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-18 à 14 03 19](https://user-images.githubusercontent.com/8549674/99533900-e51b1780-29a6-11eb-8025-864be880282c.png)

**Comment by tcharp38** [comment]
Tu l'avais déja ouvert cette page depuis mes modifs ?
Je vois que tu es en Jeedom v4 alors peut etre qu'il y a qqch d'incompatible.
je ferai un essai sur ma VM v4 pour voir ca

**Comment by tcharp38** [comment]
Je confirme. C est un defaut d'affichage sur Jeeom V4 uniquement mais le bouton refresh est bien la et fonctionne.

v4
![image](https://user-images.githubusercontent.com/35221038/99540489-dab14b80-29af-11eb-8fd0-48d7399dcedf.png)

v3
![image](https://user-images.githubusercontent.com/35221038/99540516-e270f000-29af-11eb-9843-07546c6659ae.png)

Tu peux me l'assigner. Je vais tacher de comprendre

**Comment by tcharp38** [comment]
Bon en fait rien à voir avec "refresh LQI". Je change le titre.
Tous les logos de refresh n apparaissent plus en v4.
Par ex sur la page de config 
![image](https://user-images.githubusercontent.com/35221038/99544465-a2603c00-29b4-11eb-9021-b6d9515e9173.png)

et
![image](https://user-images.githubusercontent.com/35221038/99544495-aa1fe080-29b4-11eb-8268-fa367f6cb790.png)

**Comment by KiwiHC16** [comment]
Pour les modales je viens de faire une correction car j en ai besoin. Je suis en V4. J espere que cela fonctionne aussi en V3. 
J ai mis une roue crantée car il ne veut pas le cercle...

**Comment by tcharp38** [comment]
Ca change l'aspect mais qqch apparait.
C'est ce que tu souhaite ?

![image](https://user-images.githubusercontent.com/35221038/99549795-5617fa80-29ba-11eb-9b0c-846021ae6210.png)

Vu comme ca on dirait plutot un bouton de "settings" je trouve

**Comment by KiwiHC16** [comment]
Il y avait 2 soucis: l affichage / l appel a la fonction qui ne fonctionnait plus.
Maintenant que cela fonctionne on peut jouer avec.
Je n'ai pas de preference.

**Comment by KiwiHC16** [comment]
```
<a class="btn btn-info btn-sm" id="bt_checkAllUpdate"><i class="fas fa-sync"></i> Vérifier les mises à jour</a>
```

fas fa-sync: Permet d avoir un symbole fleches en cercle .

**Comment by tcharp38** [comment]
Pour moi c'est clos. A réouvrir si je vais trop vite.
