### ISSUE TITLE
Boutons droite/gauche telecommande Ikea.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1418]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Tonio16** [comment]
Salut
Je serais intéressé aussi pour une solution.

Tcho

Antoine

**Comment by KiwiHC16** [comment]
C est dans le master maintenant. Il faut la Zigate en mode hybride.

![Capture d’écran 2021-01-19 à 15 34 59](https://user-images.githubusercontent.com/8549674/105048458-e67ec400-5a6b-11eb-9beb-431e2db300f3.png)
