### ISSUE TITLE
Re-appliquer un modele sur un equipement existant pour le mettre a jour.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1421]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by mickadam29** [comment]
@KiwiHC16 
#1472 Ce point est clos et je t'en remercie. Ici, ton idée de mettre à jour le modèle prend tout son sens.
Cela éviterait de supprimer les objets pour les réinclure en prenant le nouveau modèle.
Encore merci pour le taf autour d'abeille.

**Comment by tcharp38** [comment]
Je ne suis pas sur de bien comprendre le sujet mais peut etre qq infos en lien:
- plus besoin de supprimer un equipement pour le reinclure (et mettre à jour ses commandes à partir du JSON)
- en mode dev pour l'instant: page EQ/avancé: on peut recharger le JSON pour faire cette mise à jour de commandes sans reinclusion

**Comment by tcharp38** [comment]
Recharger JSON depuis la page EQ/avancé.
Dispo pour tous.
je suppose que ca repond au besoin initial. Je clos mais à reouvrir si je me trompe.
