### ISSUE TITLE
Solution issue Perte du port série

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1422]
Une bonne nouvelle concernant ce post fermé, https://github.com/KiwiHC16/Abeille/issues/1240 , la solution donnée ici https://github.com/KiwiHC16/Abeille/issues/1240#issuecomment-694546785 fonctionne parfaitement et je ne perds plus le port de la Zigate à chaque (ou presque) redémarrage.

**Comment by KiwiHC16** [comment]
Super. Merci de partager cette information.
