### ISSUE TITLE
Mettre à jour JennicModuleProgrammer pour effacement EEPROM

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1423]
@KiwiHC16 
La version dispo dans Abeille semble n'etre pas à jour. Il manque des options dont le "eraseeeprom" que je cherche.
D'ou vient elle ? L'as tu recompilé toi meme ?
Merci

**Comment by KiwiHC16** [comment]
Ou la la, ca fait une éternité que j ai fait ca. Je ne sais plus ....

**Comment by KiwiHC16** [comment]
Je me demande si ce n'était pas un projet github avec des fonctionnalités spécifiques.
Je ne sais plus.

**Comment by KiwiHC16** [comment]
https://github.com/WRTIOT/JennicModuleProgrammer ?

**Comment by KiwiHC16** [comment]
https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

Sous Linux
Pour mettre à jour la ZiGate sous Linux, vous pouvez vous référer au programme suivant :
https://github.com/Jerome-PS/JennicModuleProgrammer

(J avais fait mon sniffer avec Jerome-PS)

**Comment by tcharp38** [comment]
Je clos pour l'instant.
Plus nécessaire. On peut effacer la PDM via la page de l'equipement "zigate".

![image](https://user-images.githubusercontent.com/35221038/105184514-b6005e00-5b2f-11eb-9423-8f705e5ba6a4.png)
