### ISSUE TITLE
PHP Warning: hex2bin(): Hexadecimal input string must have an even length

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1430]
[20-Nov-2020 15:52:46 Europe/Brussels] PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 2674

 Sur la master du moment.

**Comment by tcharp38** [comment]
else {
                    $data = hex2bin(substr($payload, 24, hexdec($AttributSize) ) ); // -2 est une difference entre ZiGate et NXP Controlleur pour le LQI.
                }

**Comment by tcharp38** [comment]
Ok trouvé.
$AttributSize est un nombre de bytes, donc *2.
Je pousse la correction.
Et ca solutionne mon souci de reinclusion du capteur lumi au passage.

**Comment by tcharp38** [comment]
La correction est la suivante (ajout du "* 2")
                $data = hex2bin(substr($payload, 24, hexdec($AttributSize)  * 2) ); // -2 est une difference entre ZiGate et NXP Controlleur pour le LQI.

**Comment by KiwiHC16** [comment]
Le PR éatir en conflit entre ma correction et tes modifs. J ai repris toutes tes modifs a la main et fait un commit. Doit être résolu maintenant.

**Comment by tcharp38** [comment]
Ca a amélioré grandement la situation à la maison. Il me reste à reinclure tous les manquants.
