### ISSUE TITLE
INCLUSION / Problème récurrent et non isolé (Lié à l'upgrade de la Zigate en 3.1D et retour en 3.1C)

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1433]
@KiwiHC16 

Peux-tu nous expliquer ce qui se passe sur la version actuelle en matière d'inclusion ?
Un problème connu en cours de résolution dans la future release ?
Un problème qui touche plusieurs d'entre nous. Il y a eu les caractères en trop,
mais là je ne peux plus inclure des équipements connus de longue date par Abeille.

Cela concerne cette fois les prises IKEA, comme @batttousai90.
Pour rappel, FW 3.1C  Abeille du 30/09 Jeedom 4.0.61.

Merci à toi

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5575506/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/5575507/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
```Un problème qui touche plusieurs d'entre nous. Il y a eu les caractères en trop,```
Oui sera corrigé dans la prochaine version.

**Comment by KiwiHC16** [comment]
#1430

**Comment by mickadam29** [comment]
Merci. Wait and See
Je pense que l'on peut joindre le pb #1409 à celui-ci

**Comment by mickadam29** [comment]
Au final, l'inclusion de la prise IKEA est faite. Seulement l'objet n'est pas créé dans Abeille.
Toutes les 15 min, lors des ping des routeurs, je vois une adresse 362f qui ne correspond à aucun objet vu/créé par le plugin.
Cet objet 362f est bien LA prise IKEA que je recherche. Donc au final, il ne s'agit pas véritablement d'un pb d'inclusion mais plutôt de création d'objet. Peut-être faut-il changer le nom du problème ? Je te laisse voir.

2 cas de figure en cas d'inclusion ::

- L'objet existe. Mise à jour de l'adresse courte, mais Abeille ne le voit plus par la suite (pour les objets sur pile). L'objet passera en timeout malgré qu'il émette sur le réseau Zigbee. 
- L'objet n'existe pas/plus. Il est bien inclus dans le réseau mais l'objet n'est pas créé dans Abeille. Bien que son modèle soit connu. 

Bon courage. @KiwiHC16. Tu dois en avoir du taf en ce moment ;-)


[2020-11-21 08:00:02][DEBUG] : Ping: 362f
[2020-11-21 08:00:02][DEBUG] : Envoi du message topic: TempoCmdAbeille1/362f/Annonce&time=1605942232 payload: 01 vers 123
[2020-11-21 08:00:02][DEBUG] : Msg sent: {"message":{"topic":"TempoCmdAbeille1\/362f\/Annonce&time=1605942232","payload":"01"}} on queue: 123
[2020-11-21 08:00:02][DEBUG] : Get etat and Level des ampoules
[2020-11-21 08:00:02][DEBUG] : Ending cron15 

![image](https://user-images.githubusercontent.com/36518012/99869867-a8ca0000-2bce-11eb-844a-afb109c05af0.png)

**Comment by mickadam29** [comment]
Finalement après beaucoup de recherches et un effacement de la PDM de la Zigate tout est, à priori, revenu à la normal.
Je peux à nouveau inclure mes objets (existants et nouveaux). Certaines inclusions nécessitent beaucoup de temps (de l'ordre de 2 à 3 minutes et pour un même équipement 30 secondes)
Il faut faire passer le message. Pas d'upgrade en 3.1D pour le moment

**Comment by mickadam29** [comment]
@KiwiHC16 
J'ai ajouté dans le titre que c'était dû au passage 3.1D puis retour 3.1C. Je te laisse juge du titre si tu penses que les problèmes peuvent avoir une autre cause)

**Comment by KiwiHC16** [comment]
Il faudrait que je passe toutes mes Zigate en 3.1D pour voir ....

**Comment by mickadam29** [comment]
Je te trouve bien courageux vu les déboires que nous sommes plusieurs à avoir rencontrés. Mais il faudra y penser. Je pense que de ton côté tu as un environnement de dev/re7

**Comment by KiwiHC16** [comment]
Plein d environnements, je peux en générer presque autant que je veux mais il me faut du temps.

**Comment by mickadam29** [comment]
Plus de problème. Situation stable, passage en 4.1.17 depuis l'ouverture de l'incident
