### ISSUE TITLE
AbeilleCmdPrepare.class.php: Undefined index: MinInterval / MaxInterval 

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1441]
```
[21-Nov-2020 17:47:04 Europe/Brussels] PHP Notice:  Undefined index: MinInterval in /var/www/html/plugins/Abeille/core/class/AbeilleCmdPrepare.class.php on line 1077
[21-Nov-2020 17:47:04 Europe/Brussels] PHP Notice:  Undefined index: MaxInterval in /var/www/html/plugins/Abeille/core/class/AbeilleCmdPrepare.class.php on line 1078
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Quelle version ?

**Comment by tcharp38** [comment]
Sur ma branche de dev donc alignées master.
N'apparait que pendant l inclusion d'un xiaomi au moins.

**Comment by KiwiHC16** [comment]
Normalement aucun Xiaomi n a besoin de cette fonction setReport sauf le capteur de luminosité.
Peux tu confirmer que c est lui ?

**Comment by KiwiHC16** [comment]
2 problemes possibles:

Premier soucis (suite a discussion sur parametrage capteur xiaomi luminosité):
- il faut certainement revoir cette fonction: 
- str_pad(dechex($parameters['MinInterval']),4,0,STR_PAD_LEFT),
- par un sprintf("%04s",dechex(........));
- MinInterval est un dec qu'il faut coder en hex sur 4 digits.

Deuxieme soucis (Ton cas):
- Pourquoi MinInterval n est pas defini. Il faudrait tracer les actions sur ton systeme.

**Comment by tcharp38** [comment]
Je verifierai mais sauf erreur je jouais avec le "door sensor"

**Comment by KiwiHC16** [comment]
Pour la door, il n y pas besoin de setReport donc si c est le cas il faut comprendre pourquoi.

**Comment by tcharp38** [comment]
Je regarderai, des que j'ai reussi à merger et rattraper qq regressions.

**Comment by KiwiHC16** [comment]
Des nouvelles sur ce cas ?

**Comment by tcharp38** [comment]
Pas retombé dessus. Je clos et reouvrirai si besoin
