### ISSUE TITLE
Redirection vers config équipement

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1442]
Bonjour @KiwiHC16 
Lorsque je suis sur un équipement dans le dashboard, 
![image](https://user-images.githubusercontent.com/52486183/99899715-b73a1980-2cab-11eb-99a5-b63ad8284397.png)
si je clique sur le nom de l'équipement je me retrouve sur la configuration du plugin au lieu de me retrouver sur la configuration de l'équipement. 
![image](https://user-images.githubusercontent.com/52486183/99899788-50693000-2cac-11eb-8565-0eb8f585d2fc.png)

Ce n'est pas pratique Est-ce normal ? Merci
PS Y-a-il un moyen de réduire la taille des images dans github ou faut-il le faire avant de les intégrer à un post ? Merci

**Comment by tcharp38** [comment]
Salut. Je viens de faire l'essai chez moi. Pas de soucis mais je suis en Jeedom v3 toujours.
Je ne vois pas ou Abeille joue un role dans cette histoire donc je penche pour un bug Jeedom v4.

**Comment by mickadam29** [comment]
En V4.0.61, chez moi, j'arrive bien sur la page de l'équipement. 
Donc ca ne serait pas un bug généralisé mais produit dans certaines circonstances

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ce sujet a deja été posté et c'est en relation avec V4.1.
Pas supporté par Abeille actuellement.

**Comment by KiwiHC16** [comment]
Normalement corrigé maintenant.

**Comment by Kenderv** [comment]
Bonsoir KiwiHC16 et merci pour cette correction. Je n'ai pas fait la dernière mise à jour, elle me fait un peu peur. Ma Zigate est toujours en 031a. Si j'applique la mise à jour qui prend en charge le firmware zigate 3.1d vais-je être obligé aussi de réinclure tous mes modules ? Est-il possible d'appliquer une mise à jour qui corrige ce bug de redirection sans être obligé de passer par la mise à jour du 24/11/2020. Suis-je obligé de passer ma Zigate en 3.1d ? Merci de tes réponses. Au fait, c'est quoi le mode hybride ?
