### ISSUE TITLE
Nom par defaut d'un équipement

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1443]
@KiwiHC16 
Jusque la quand tu crees un equipement tu le nommes 'AbeilleX-YYYY".
L'adresse courte n'apporte pas grand chose et du fait qu'elle peut changer à chaque réinclusion genere des difficultes en imposant de nommer l'equipement si changement.
Je viens de trouver un bug sur ce point, probablement lié au fait qu'on soit passé en upper case.

Que penses tu si dorenavent le nom par défaut utilise l"ID Jeedom plutot que l'adresse courte ?
Au moins l'ID ne change pas tant que l'equipement est connu de Jeedom
Ca donnerai "AbeilleX-ZZ".
Ca me semble beaucoup + stable au long terme non ?

**Comment by mickadam29** [comment]
@tcharp38 et @KiwiHC16 
Ca reste mon avis, mais ayant vu, avec tcharp38 le bug, je le donne.
La plupart des logs remontent l'adresse courte. Pour moi, le fait qu'il apparaisse permet de rapidement identifier l'objet.
Mais c'est peut-être aussi parce que je conserve Abeille-XXXX+mon suffixe que j'y vois un intérêt à conserver cette norme AbeilleX-YYYY

**Comment by mickadam29** [comment]
@tcharp38 
Autre problème avec les majuscules. Je viens faire le reset PDM. En incluant une prise, je souhaite la mettre dans le groupe 3cda. Problème, le groupe est renommé 3CDA. Et visiblement cela bloque.

**Comment by tcharp38** [comment]
> @tcharp38 et @KiwiHC16
> Ca reste mon avis, mais ayant vu, avec tcharp38 le bug, je le donne.
> La plupart des logs remontent l'adresse courte. Pour moi, le fait qu'il apparaisse permet de rapidement identifier l'objet.
> Mais c'est peut-être aussi parce que je conserve Abeille-XXXX+mon suffixe que j'y vois un intérêt à conserver cette norme AbeilleX-YYYY

Je vais déja completer ce point.

Le fait que le nom d'un equipement contienne l'adresse courte provoque de grosses difficultées.
On peut renommer un eq si on trouve son adresse courte dans le nom mais imagine qu'on loupe une "device announce", on aura loupé le changement de nom et c'est mort. L'eq va garder son nom pour toujours avec une ancienne adresse courte.
C'est ce qui se passe depuis la passage en majuscules. J'ai loupé qqch sur la beta. Faut que je fixe ca.

En ce qui me conserne je deconseille de garder l'adresse courte dans le nom. Un truc + parlant et independant de l'adresse est bien mieux à long terme. Chez moi je mets du "Temp C1," "Temp C2", "Chauffage ST".. ext C1 C2 = chambres, ST = salle TV par ex. Ca restera TOUJOURS valide meme si je dois refaire des inclusions et tous les scenaris bases dessus aussi.

**Comment by tcharp38** [comment]
> @tcharp38
> Autre problème avec les majuscules. Je viens faire le reset PDM. En incluant une prise, je souhaite la mettre dans le groupe 3cda. Problème, le groupe est renommé 3CDA. Et visiblement cela bloque.

Je ne comprends pas ce que tu fais. Tu as les logs associés ?

**Comment by mickadam29** [comment]
Je finis d'inclure mes équipements et je refais la manip (peut-être demain). La plupart des noms se corrigent automatiquement Ancien - > Nouveau (nouveau nom en majuscule)

Pour le groupe :

La télécommande HUE permet de s'associer à une ampoule en formant un groupe. Lorsque c'est fait, tu récupères le nom du groupe sur l'ampoule. Car tu ne peux pas l'avoir directement sur la télécommande. Puis, ce groupe tu l'associes à toutes les ampoules que tu veux commander simultanément. Ma télécommande pilotait le groupe 3cda. Mais maintenant, le groupe que l'on ajoute avec l'interface d'Abeille, ce positionne en majuscule sur l'ampoule. Et visiblement ce n'est pas vu comme un seul et même groupe. Le changement min->maj est lourd de conséquence à priori. On retrouve des effets de bord un peu partout.

**Comment by mickadam29** [comment]
Pour en revenir au changement de nom, lorsque celui-ci se fait bien il n'y a pas de souci.
Voila ce que cela donne chez moi
![image](https://user-images.githubusercontent.com/36518012/99916231-2bef7100-2d09-11eb-9424-1b9b85be7061.png)
Et après une nouvelle inclusion (objet 79d3) . Note les majuscules et l'adresse courte réattribuée. (A1C1). Changement fait par le processus d'inclusion.

![image](https://user-images.githubusercontent.com/36518012/99916307-c059d380-2d09-11eb-92de-66155ea2a383.png)

Mais si vous garder la logique du développement des routes, ca va aussi. On retrouve les 2. Donc il faudrait adopter cela pour tous les logs

![image](https://user-images.githubusercontent.com/36518012/99916289-9ef8e780-2d09-11eb-882e-7d8aa04806e2.png)

**Comment by mickadam29** [comment]
> > @tcharp38
> > Autre problème avec les majuscules. Je viens faire le reset PDM. En incluant une prise, je souhaite la mettre dans le groupe 3cda. Problème, le groupe est renommé 3CDA. Et visiblement cela bloque.
> 
> Je ne comprends pas ce que tu fais. Tu as les logs associés ?

Voici la démarche

https://faire-ca-soi-meme.fr/domotique/2018/03/14/une-telecommande-zigbee-pour-les-controler-tous/

**Comment by KiwiHC16** [comment]
SVP ne pas mélanger les sujets. Ici c est le nom de l objet et il faut créer une autre issue sur la gestion des groupes.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
@tcharp38, l adresse dans le nom etait super pratique au debut mais maintenant il suffit d'aller dans la page santé pour avoir l'info. Comme la complexité est l'ennemi du bien je suis 100% ok avec ta proposition. On vire l adresse du nom (et tous les mechnisme associés).
Lors de la creation de l objet on lui donne pour nom l'Id de eqLogic et cela sera parfait. Ensuite l utilisateur le change comme il le souhaite.

**Comment by tcharp38** [comment]
Ok ca me semble carrement + propre et moins dangereux.
Considere que je m'y colle.

**Comment by tcharp38** [comment]
#1462
