### ISSUE TITLE
EEPROM / PDM Reset obligatoire suite à migration 3.1D -> 3.1C

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1444]
@KiwiHC16 @tcharp38 

La question devrait être posée sur le forum Zigate, mais je pense que certains d'entre vous ont la réponse.
Je soupçonne la PDM de ma ZIGATE d'être corrompue après une montée de version 3.1C vers 3.1D. Depuis l'édition, je suis tombé sur l'article #1404.
Ni Abeille, ni Zigate ne peuvent procéder à l'inclusion des objets (nouveaux comme anciens, supprimés de Abeille mais toujours connus de la zigate).

Si je procède à l'effacement de cette PDM, vais-je n'avoir qu'à refaire une inclusion des objets ? L'IEEE restant évidemment la même, je m'attends à ce que Abeille me dise, je connais l'objet, je fais la mise à jour. Et ainsi, et surtout, conserver tous mes équipements dans les scénarios et autres. Je n'aurai qu'à les renommer. CF #1443 

Ce sera l'occasion de refaire le maillage avec les routeurs en place, les endpoint aussi. Certains seront plus faciles à réinclure que d'autres.

**Comment by tcharp38** [comment]
Apres effacement PDM tu devra redeclencher une inclusion de TOUS les periphs de la zigate en question. Celle derniere ne connait plus personne mais coté Jeedom les equipements sont normalement encore la.

Donc oui il devrait te dire un truc du style "l'adresse est deja dans l'objet machin..." et faire la mise à jour.
Sauf pour le nom, pour lequel il y a un bug en cours.

**Comment by mickadam29** [comment]
Le bug n'est pourtant pas systématique. Je m'en rends compte au fur et à mesure

**Comment by tcharp38** [comment]
C est aussi mon observation.
Mais j'ai clairement avancé en effacant la PDM. Je suis à nouveau sur qqch de + stable.

**Comment by mickadam29** [comment]
Tu sais que lorsque j'ai mis la zigate avec le ZGWUI, j'ai comme l'impression qu'il avait détecté 2 coordinator.
Après reset PDM, plus qu'un seul. Je ne parviens pas à inclure tous mes périphériques. 2 interrupteurs Xiaomi OK, le 3ème identique KO. L'inclusion refuse toujours les périphériques que la zigate ne connaissait pas. Les autres OK. Et pourtant un reset PDM a bien eu lieu. Changement du PANID et périphériques à réassocier

**Comment by tcharp38** [comment]
Ok, toujours sur la beta et 3.1c ?

**Comment by mickadam29** [comment]
Oui

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/99911175-dad48280-2cf2-11eb-9f5b-4411c24fc736.png)

**Comment by tcharp38** [comment]
Quels sont les periphs qui ne fonctionnent toujours pas à l'inclusion ?

**Comment by mickadam29** [comment]
J'avais une prise ampoule IKEA et 1 interrupteur Xiaomi. Ce qui est super étrange, c'est que j'ai bien tenté 7 ou 8 fois chacun. Puis d'un coup la lampe a bien été enregistrée sur le réseau. Et comme par hasard, l'interrupteur aussi. Comme s'il y avait eu un temps de blackout. J'ai donc remis en service mes routeurs en priorité. Ampoules et Prises. Je vais insister pour inclure 2 prises IKEA. Comme cela j'aurai l'ensemble de mes routeurs. Mais c'est pas gagné. Et surtout très incertain pour l'avenir.

**Comment by tcharp38** [comment]
De mon experience la procedure d'inclusion n'aime pas trop qu'on en fasse "trop à la fois".
L'inclusion d'un seul eq peut prendre du temps et plusieurs allers retours donc si tu lance l'inclusion de plusieurs eq en meme temps ca peut merder. J'attends que ca soit stabilisé chaque fois avant de passer au suivant, en surveillant l'activite du parser.

Bon donc globalement c'est mieux ?

**Comment by mickadam29** [comment]
Pas vraiment. Je te dirai oui si je parviens à inclure des périphériques nouveaux. Donc avec écriture/ajout dans la PDM. Là visiblement ca écrit déjà dedans puisque je réinclus des équipements mais jusqu'où ? C'est pour ça que j'insère mes routeurs avant. Pour qu'ils prennent en charge certains équipements et libère la "mémoire" de la zigate. Mais j'ai l'essentiel. Retour de la lumière avec interrupteurs. Perdu la télécommande HUE et la gestion groupe des mes ampoules. Mais pas urgent. Comme toi ça, se remet petit à petit. J'ai remarqué également qu'il vaut mieux passer la zigate en inclusion, inclure l'objet, retirer le mode inclusion et passer au suivant.

**Comment by mickadam29** [comment]
Pour les équipements qui passent pas. Abeille me dit pas qu'il les connait, peut-être qu'il parvient pas à récupérer l'IEEE
Et curieusement j'ai reçu ça. J'ai positionné 300 tentatives avant de mettre Inactif un objet.

Equipement 'Abeille1-17D0' désactivé. Il a probablement quitté le réseau.
--
Après réactivation, Abeille me dit cette fois qu'il connait l'objet. Mais l'inclusion est KO
Y a des boucles dans l'interrogation des cluster

![image](https://user-images.githubusercontent.com/36518012/99912514-fb530b80-2cf7-11eb-9850-352dd4a8c982.png)


Malgré ces boucles, l'inclusion s'est faite. Mais ca prend 1 minute !! Et visiblement il faudrait un Leave avant de pouvoir faire quelque chose au niveau de l'inclusion

**Comment by mickadam29** [comment]
Après une réussite, l'objet avait l'adresse 576A. Je relance l'inclusion. Procédure inclusion sur la prise. Ben les boucles se produisent encore sur l'ancien nom
![image](https://user-images.githubusercontent.com/36518012/99913624-efb41480-2cf8-11eb-9ffc-054f2a72c634.png)

**Comment by mickadam29** [comment]
Le reset de l'EEPROM a solutionné les problèmes d'inclusion suite au passage de la version 3.1D avec retour vers 3.1C. PDM semble corrompue. L'opération, même si cela nécessite de tout réinclure, est la seule que j'ai trouvée.
A ceux que cela parle. Dans le champ Discover Devices j'avais 2 adresses. Ca me paraît étrange d'autant qu'après le reset de la PDM je n'en avais plus qu'une.

![image](https://user-images.githubusercontent.com/36518012/99915913-ffd2f080-2d06-11eb-82f2-310d882e8959.png)

**Comment by mickadam29** [comment]
Ca fait plaisir

![image](https://user-images.githubusercontent.com/36518012/99918069-ba1d2480-2d14-11eb-9b4f-ac415ceb09c3.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
- si tu es sur la version stable d'Abeille il y a un bug qui fait que les inclusions ne se produisent pas. Le probeleme est aléatoire et donc apres beaucoup de tentative cela peut fonctionner. Si tu peux tester avec la beta car le soucis est corrigé dedans.
- Lors de la migration du firmware, la base de donnée (PDM-dans la zigate) est mise à jour. Je suppose que cela a été implémenté en montant (3.1c -W 3.1d) mais je doute que l inverse fonctionne. Perso, n'ayant pas eu le temps de regarder ces aspects, je fais la grosse brute et j'effaces l'EEPROM complete. Ensuite je fais l inclusion de tout le monde.

**Comment by mickadam29** [comment]
@KiwiHC16 
J'ai la version Beta. Mais seule cela ne suffisait à remettre d'équerre. Il a fallu que j'efface l'EEPROM. Après j'ai 38 noeuds, mais comme les objets sont reconnus par leur adresse IEEE et qu'Abeille fait les mises à jour ça reste jouable. Ce qui est compliqué c'est l'importance accordée aux objets. Je gère un partie de l'éclairage de ma maison, entre autre et, à compter de la fin de semaine, ma chaudière avec le plugin thermostat et agenda. Donc j'ai besoin, comme beaucoup, que ce soit robuste. Je profite pour te demander comment va se passer le retour beta vers master ? Il va me suffire de sélectionner "Installer Stable" sur le market ? Dans la beta tu gères les SONOFF (relais, et détecteur de présence), tu les as ajoutés aussi au master ?

**Comment by KiwiHC16** [comment]
@mickadam29, quelques éléments de reflexion:

- Plus tu as d'équipements plus tu augmentes la probabilité d'avoir des soucis. Perso j'ai decoupé mon systeme en petites parties. Par exemple ce matin j'ai perdu une partie et il a fallu que je redemarre une zigate. Ca arrive rarement mais ca arrive. C'est le probleme des systemes centralisés. J'ai aussi plusieurs Jeedom. Si j'en perds un je ne perds pas tout.

- "Ce qui est compliqué c'est l'importance accordée aux objets." -> Je ne comprends pas ce commentaire

- " Je gère un partie de l'éclairage de ma maison" perso j'ai jeedom qui commande mais aussi une telecommande. Si je perds l un j ai l autre et vis versa.

- Tout ce qui est dans beta est dans master sauf erreur de manipulation. Une fois que la beta semble stable elle passera en stable. Beta et Stable sont dispo dans le market jeedom.

**Comment by mickadam29** [comment]
@KiwiHC16 

> @mickadam29, quelques éléments de reflexion:

> > * Plus tu as d'équipements plus tu augmentes la probabilité d'avoir des soucis. Perso j'ai decoupé mon systeme en petites parties. Par exemple ce matin j'ai perdu une partie et il a fallu que je redemarre une zigate. Ca arrive rarement mais ca arrive. C'est le probleme des systemes centralisés. J'ai aussi plusieurs Jeedom. Si j'en perds un je ne perds pas tout.

Je me demande si je vais pas investir dans une second clé. Pizigate ou autre pour justement isoler. Mais une V2 est en cours de DEV donc j'attends

> * "Ce qui est compliqué c'est l'importance accordée aux objets." -> Je ne comprends pas ce commentaire

Je faisais référence au fait d'effacer la PDM régulièrement. Si je peux me passer de capteur de température, tout ce qui est interrupteur et régulation chauffage c'est plus compliqué.

> * " Je gère un partie de l'éclairage de ma maison" perso j'ai jeedom qui commande mais aussi une telecommande. Si je perds l un j ai l autre et vis versa.

J'ai une télécommande HUE en mode SOS justement. J'affecte le groupe de cette télécommande à toutes mes ampoules. Comme ça sans Zigate ou crash du PC, je reste maître de mon éclairage.

> * Tout ce qui est dans beta est dans master sauf erreur de manipulation. Une fois que la beta semble stable elle passera en stable. Beta et Stable sont dispo dans le market jeedom.

Là je ne te suis pas. Ce que je crois comprendre c'est qu'à un moment il faudra que je resélectionne "Installer Stable" dans le gestionnaire de plugin. Ou cela se fera automatiquement par une mise à jour de la beta qui me rebasculera sur la stable. Car je ne pense pas rester sur la beta. C'était pour les problèmes caractères en trop et inclusion liés à la version 3.1D
Je ne sais pas si je suis clair

**Comment by KiwiHC16** [comment]
Je ne sais pas exactement  comment Jeedom gere le beta et stable car sur mes systemes je vais en direct.
Par defaut tu n'as pas acces aux beta dans le market jeedom. Si mes souvenir sont bons il faut cocher une case pour dire donner moi acces aux betas. Je suppose qu apres tu as aussi les beta depuis le market. De mon cote, sur le market, je mets les deux versions a dispo mais je ne force pas l utilisation de l une ou l autre. C est l utilisateur qui choisi celle qu'il veut.

**Comment by KiwiHC16** [comment]
L effacement des PDM n est plus necessaire. Normalement la zigate gere le truc.
Perso lors de l arrivée d un nouveau firmware j'en profite pour tout remettre a plat. C est pour cela que j efface. Mais pas obligatoire.

**Comment by tcharp38** [comment]
@KiwiHC16 J'ai des doutes quant au FW zigate. Je pense qu'il y a encore des choses incomprises et des corruptions.
En tout cas pour moi l'effacement et retour en 3.1c à partir de retrouver un peu de fonctionalite meme si je ne suis pas encore au niveau d'avant (toujours des explosions de cmd dans la nuit).

**Comment by KiwiHC16** [comment]
Et tu n as plus ces explosions quand tu es en 3.1c ?

**Comment by tcharp38** [comment]
Si si. Encore cette nuit. Mais au moins j'ai pu reinclure mes volets et autres capteurs Xiaomi

**Comment by tcharp38** [comment]
C est ce à quoi je pense. Mais donc rien à voir avec ce sujet.

**Comment by KiwiHC16** [comment]
Ok je clos ce point et on va traité ton sujet dans d autres Issues #1476 #1490
