### ISSUE TITLE
Support mise à jour OTA

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1445]
J'ai découvert par hasard qu'il existait un site répertoriant des fichiers OTA pour la mise à jour des firmware IKEA
Une option de mise à jour est-elle envisagée directement depuis Abeille dans les releases à venir ?
Je pense, en effet, qu'il serait bon de faire évoluer les firmwares de ces équipements qui font routeur (prises et ampoules) et réalisable avec les box des constructeurs. Voir où trouver ces fichiers OTA pour les autres fabricants.
Car Zigate progresse, Abeille aussi mais les nouveautés sont-elles prisent en compte par des produits qui datent de 2 ans et plus ?
Evidemment, il faudrait étudier les changements pour savoir si une mise à jour apporte une quelconque évolution et surtout aucune régression.

**Comment by tcharp38** [comment]
La mise à jour OTA n'est pas supportée par Abeille mais effectivement ca pourrait etre interessant.
Je ne sais pas combien d'equipements ca concerne. Perso, j'en n'ai aucun. Je crois pas que Profalux fasse des updates comme ca.
A garder en tete.
Je te suggere de renommer le sujet en "Support mise à jour OTA" ou qqch du style. C'est pas specifique Ikea non ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
La zigate supporte le protocol.
Perso je n'ai jamais poussé le sujet dans Abeille car cela demande trop de reverse ingeniering.
Je sais que d'autres projets on bossé le sujet.
Et le soft n'est dispo que pour certaines marques qui se comptent sur les doigts d'une main.
