### ISSUE TITLE
Call to a member function getName() on null

### ISSUE THREAD

**Issue by battousai90** [KiwiHC16/Abeille#1446]
Je suis sur la bêta du 21/11.
Après avoir retiré un accessoire d’une pièce et l’avoir affecté à la pièce aucun, impossible de retourner à la page configuration d’abeille:
Erreur : Call to a member function getName() on null

**Comment by battousai90** [comment]
Ce n’est pas bloquant;
On peut contourner en désactivant l’accessoire

**Comment by tcharp38** [comment]
Moi ca me parle pas.
Si jamais on arrive à reproduire on pourra creuser, sinon faudra patienter. Ca semble etre un defaut Jeedom d'ailleurs et pas Abeille.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
"impossible de retourner à la page configuration d’abeille:"
Peux tu faire une capture d'ecran pour etre sure ?
J'ai corrigé un probleme similaire il y a qq jours: "Test to avoid error" #1434

**Comment by battousai90** [comment]
Oui bien sur.
Abeille sur Maison je la passe sur Aucun :
![image](https://user-images.githubusercontent.com/47687052/99949904-17988c00-2d7c-11eb-89bf-36df8d6b857d.png)
je clic sur sauvegarde pour enregistrer
![image](https://user-images.githubusercontent.com/47687052/99949989-2f701000-2d7c-11eb-816f-07f7d828e267.png)
Si j'essaye de rafraichir la page ou de retourner sur le plug-in abeille j'ai toujours la même erreur
![image](https://user-images.githubusercontent.com/47687052/99950120-59c1cd80-2d7c-11eb-9695-9f327009feff.png)

**Comment by KiwiHC16** [comment]
Ok super, je vais tester et corriger.

**Comment by battousai90** [comment]
Je vais désactiver l'abeille depuis le résumé domotique et je reviens c'est bon :
![image](https://user-images.githubusercontent.com/47687052/99950797-6561c400-2d7d-11eb-9843-045a8d1f23ac.png)

**Comment by KiwiHC16** [comment]
J ai le soucis aussi.

**Comment by KiwiHC16** [comment]
Corrigé dans beta-dev.

**Comment by KiwiHC16** [comment]
Porté sur master aussi

**Comment by battousai90** [comment]
ca marche j'attend la beta du market ;)
