### ISSUE TITLE
Version BETA ABEILLE / Icone Xiaomi sensor_motion.aq2 manquante

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1447]
A priori, un petit oubli de la part des développeurs. L'icône n'apparaît pas mais le json du modèle spécifie un png qui est présent dans le répertoire images : node_XiaomInfraRouge2.png

![image](https://user-images.githubusercontent.com/36518012/99916920-64914980-2d0d-11eb-8192-2f984e2cdfe5.png)

sensor_motion.aq2

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peux tu partager un lien sur le net vers la photo de cet equipement ?

**Comment by mickadam29** [comment]
@KiwiHC16. Il est connu. C'est juste que je peux pas  le sélectionner dans la version beta. Si tu vas dans compatibilité tu le trouves.
Donc tu l'as déjà placé dans images. Il est renseigné dans le json, mais n'apparaît pas dans la liste pour l'objet

![image](https://user-images.githubusercontent.com/36518012/99995116-3fa6e000-2dba-11eb-8694-e0fa2f85739b.png)

**Comment by mickadam29** [comment]
J'en profite pour te proposer à nouveau un png pour les sirènes Alarm PSE3-v1.1.0
Si tu veux je te l'envoie sur ta bal. J'ai ton adresse.

**Comment by KiwiHC16** [comment]
Pour "sirènes Alarm PSE3-v1.1.0" mets l image dans ce fil de discussion.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-24 à 10 15 16](https://user-images.githubusercontent.com/8549674/100073567-f5674280-2e3d-11eb-828a-d1a52ed048d2.png)

Le bien semble ok. (Je suis sur la beta qui sera dispo demain)

**Comment by mickadam29** [comment]
Absent chez moi. La liste se base sur le seul contenu du répertoire Images ? /var/www/html/plugins/Abeille/images$

![image](https://user-images.githubusercontent.com/36518012/100080393-13d13c00-2e46-11eb-8469-85f1aec2caba.png)

Et bien présent dans le répertoire

![image](https://user-images.githubusercontent.com/36518012/100080571-47ac6180-2e46-11eb-848e-01457debc633.png)

**Comment by mickadam29** [comment]
[node_PSE03-v1.1.0.png.zip](https://github.com/KiwiHC16/Abeille/files/5589111/node_PSE03-v1.1.0.png.zip)

**Comment by mickadam29** [comment]
./sensor_motion.aq2/sensor_motion.aq2.json:      "icone": "XiaomiInfraRouge2"
![image](https://user-images.githubusercontent.com/36518012/100086198-5c402800-2e4d-11eb-97ac-66ea4e1f0aba.png)

 Abeille_icon.png
 inclusion.png
 node_3AFE130104020015.png
 node_3AFE140103020000.png
 node_3AFE14010402000D.png
 node_3AFE170100510001.png
 node_511.201.png
 node_511.202.png
 node_Abeille.png
 node_BASICZBR3.png
 node_Blitzwolf-BW-SHP13.png
 node_bsoProFalux.png
 node_CLA60RGBWOSRAM.png
 node_ColorsBloom.png
 node_Connectedoutlet.png
 node_Contactor.png
 node_COSensor-EM.png
 node_ctrl_86plug.aq1.png
 node_ctrl_ln1.aq1.png
 node_ctrl_ln2.aq1.png
 node_ctrl_neutral1.png
 node_ctrl_neutral2.png
 node_defaultUnknown.png
 node_Dimmerswitchwoneutral.png
 node_FlexRGBW.png
 node_FLOALTpanelWS60x60.png
 node_FYRTURblock-outrollerblind.png
 node_GardenspotRGB.png
 node_GL-B-001Z.png
 node_GL-B-008Z.png
 node_GL-C-008.png
 node_GLEDOPTODualWhiteAndColor.png
 node_GLEDOPTO.png
 node_GL-MC-001.png
 node_GL-S-003Z.png
 node_GL-S-004Z.png
 node_GUNNARPpanelround.png
 node_HS2WD.png
 node_HueGo.png
 node_HueWhite.png
 node_IkeaTradfri2BtnCarre.png
 node_IkeaTradfri5BtnRond.png
 node_IkeaTradfriBulbE14WSOpal400lm.png
 node_IkeaTradfriBulbE27Opal1000lm.png
 node_IkeaTradfriBulbE27WOpal1000lm2.png
 node_IkeaTRADFRIbulbE27WSopal980lm.png
 node_IkeaTradfriBulbGU10W400lm.png
 node_IkeaTRADFRIbulbGU10WS400lm.png
 node_IkeaTradfriDimmer.png
 node_IkeaTradfriMotionSensor.png
 node_Keyfob-ZB3.0.png
 node_Lamp_01.png
 node_LCA001.png
 node_LCT001.png
 node_LCT015.png
 node_LegrandRemoteSwitch.png
 node_light.aqcn02.png
 node_LIGHTIFYIndoorFlexRGBW.png
 node_LIGHTIFYOutdoorFlexRGBW.png
 node_LOM002.png
 node_LST001.png
 node_LST002.png
 node_LTA001.png
 node_LTW001.png
 node_LTW010.png
 node_LTW012.png
 node_LTW013.png
 node_LWO001.png
 node_Micromoduleswitch.png
 node_MotionSensor-A.png
 node_MR16TWOSRAM.png
 node_OSRAMClassicA60RGBW.png
 node_OSRAMClassicA60Wclear-LIGHTIFY-2.png
 node_OSRAMClassicA60Wclear-LIGHTIFY.png
 node_OSRAMClassicE27Dimmable.png
 node_OsramLightifyplug01OutDoor.png
 node_OsramLightify.png
 node_PAR1650TW.png
 node_PAR16RGBWZ3.png
 node_PlugZ3.png
 node_.png
 node_ProfaluxLigthModule.png
 node_PSE03-v1.1.0.png
 node_RB175W.png
 node_RC110.png
 node_relay.c2acn01.png
 node_remotecontrol.png
 node_RF263.png
 node_RF265.jpg
 node_RF265.png
 node_RH3001.png
 node_router.png
 node_Ruche.png
 node_RWL021.png
 node_SA-003-Zigbee.png
 node_sen_ill_mgl01.png
 node_sensor_cube.png
 node_Shutterswitchwithneutral.png
'node_ SM309.png'
 node_SML001.png
 node_SML002.png
 node_SmokeSensor-EM.png
 node_SNZB-01.png
 node_SNZB-02.png
 node_SNZB-03.png
 node_SNZB-04.png
 node_SPZB0001.png
 node_Switch4xEU-LIGHTIFY.png
 node_TI0001.png
 node_TRADFRIbulbE14CWSopal600lm.png
 node_TRADFRIbulbE14Wopch400lm.png
 node_TRADFRIbulbE14WS470lm.png
 node_TRADFRIbulbE14WSopal600lm.png
 node_TRADFRIbulbE27CWSopal600lm.png
 node_TRADFRIbulbE27WSopal1000lm.png
 node_TRADFRIbulbE27WW806lm.png
 node_TRADFRIbulbE27WWclear250lm.png
 node_TRADFRIbulbGU10WW400lm.png
 node_TRADFRIcontroloutlet.png
 node_TRADFRIDriver10W.png
 node_TRADFRImotionsensorE1525.png
 node_TRADFRImotionsensorE1745.png
 node_TRADFRIonoffswitch.png
 node_TRADFRIopencloseremote.png
 node_TRADFRIsignalrepeater.png
 node_TRADFRISignalRepeater.png
 node_TRADFRItransformer10W.png
 node_TRADFRItransformer30W.png
 node_TS0001.png
 node_TS0002.png
 node_TS0003.png
 node_TS0011.png
 node_TS0043.jpg
 node_TS0043.png
 node_TS0111.png
 node_TS0121.png
 node_TS0201.png
 node_TS0302.png
 node_TY0A01.png
 node_voletProFalux.png
 node_WS2812_light_controller.png
 node_XiaomiBouton1.png
 node_XiaomiBouton3.png
 node_XiaomiBouton.png
 node_XiaomiButtonb186acn01.png
 node_XiaomiButtonb286acn01.png
 node_XiaomiButtonSW861acn01.png
 node_XiaomiButtonSW861.png
 node_XiaomiInfraRouge2.png
 node_XiaomiInfraRouge.png
 node_XiaomiPorte1.png
 node_XiaomiPorte.png
 node_XiaomiPriseEU.png
 node_XiaomiPrise.png
 node_XiaomiSensorGaz.png
 node_XiaomiSensorSmoke.png
 node_XiaomiTemperatureCarre.png
 node_XiaomiTemperatureRond.png
 node_XiaomiVibration.png
 node_Xiaomiwleak_aq1.png
 node_zigbeeColorDimmableLight.png
 node_zigbeeColortemperaturelight.png
 node_zigbeeDimmablelight.png
 node_zigbeeExtendedcolorlight.png
 node_zigbeeNoncolorcontroller.png
 node_zigbeeNon-colorscenecontroller.png
 node_zigbeeOnOffLight.png
 node_zigbeeWindowCoveringDevice.png
 node_ZLL-DimmableLigh.png
 node_ZLO-DimmableLight.png
 node_ZLO-ExtendedColor.png
 node_ZLO-LTOSensor.png
 node_ZLO-OccupancySensor.png

Tu noteras également un pb sur ce nom 'node_ SM309.png'
Il a des simple quote

Je vois pas ce qui cloche dans cette version, mais le pb existe pour Xiaomi et ma Sirène. "Dans le doute, Reboot" donc je vais 
suivre la recommandation.

**Comment by mickadam29** [comment]
Curieusement après avoir renommé l'icone en PSE03_V1.1.0 (V maj remplace v minuscule) , l'icone est dispo et rattaché au nom Alarm PSE03_v1.1.0. En revanche je parviens toujours pas à mettre la sensor_motion_aq2. D'ailleurs je n'ai pas non plus l'icone du modèle 1.

**Comment by KiwiHC16** [comment]
Merci de preciser les versions Abeille que vous utilisez associé à vos tests.

**Comment by mickadam29** [comment]
Il faudrait pouvoir l'associer à son avatar. Version Beta du 21/11

**Comment by mickadam29** [comment]
Version Beta de 21/11
Etrange
Si je supprime un fichier .png du répertoire images et que je sélectionne le modèe qui pointe sur ce fchier, la liste de proposition ne change pas. Exemple, j'ai enlevé node_XiaomiVibration.png
Je peux toujours le sélectionner dans la liste et l'icone est présente

![image](https://user-images.githubusercontent.com/36518012/100096298-1ccd0800-2e5c-11eb-971e-78ad46c8a867.png)

Par contre, lorsque je reviens sur les objets, j'ai une icone Abeille car le fichier n'est pas.

![image](https://user-images.githubusercontent.com/36518012/100096450-50a82d80-2e5c-11eb-8b01-ddd46b4355a1.png)

En fait, il suffit d'un simple fichier vide qui porte le nom de l'icone pour que celle-ci apparaissent dans les objets. Ici j'ai créé un fichier node_XiaomiVibration.png et dans les objets l'icone réapparait. 

![image](https://user-images.githubusercontent.com/36518012/100098255-1770bd00-2e5e-11eb-879c-3fa03de576e8.png)



Donc je vois un problème qui est que tu sembles aller chercher l'icone ailleurs que dans le répertoire Images pour construire ta liste. Car bien qu'associées à un modèle et déclarées dans le json, certaines icones ne sont pas proposées. Et lorsqu'elles sont dans la liste on se fiche complètement du contenu du fichier png. Faut juste un fichier portant le bon nom node_xxxx.png
Tu fais une mise en cache des icones dans la base ? Car pour le détecteur Xiaomi, je ne vois rien d'anormal et pourtant impossible de le sélectionner car l'icone n'apparait pas dans la liste. J'ai bien tenté d'inscrire le nom "XiaomiInfraRouge2" dans la BDD au niveau de la configuration de l'iD dans la table eqLogic mais ca me semble hasardeux.

**Comment by mickadam29** [comment]
Autre icone, manquante cette fois
Comme il s'agit de la beta, ce n'est pas très grave, si les manques sont dans la master.

![image](https://user-images.githubusercontent.com/36518012/100103154-d039fa80-2e64-11eb-8d2f-c3e82b71623b.png)

**Comment by mickadam29** [comment]
@KiwiHC16 
Il manque quelque chose dans la version Beta. Je viens de réinstaller la Master et j'ai retrouvé ce qu'il manquait.
Lorsque j'ai installé la beta, j'avais désinstallé la stable. Donc répertoire plugin/Abeille inexistant.

![image](https://user-images.githubusercontent.com/36518012/100350474-40be5400-2fea-11eb-8cd0-f09c5f9486df.png)

**Comment by JC38** [comment]
@mickadam29 : tu as récupéré toutes tes icones ? Moi, il m'en manque toujours un paquet. 
Tu peux donner la manip. Moi je suis juste passé de la version stable du market à la version Master de github en suivant la manip que j'ai décrite ici #1465 et qui vient de [https://jeedomiser.fr/article/installer-vos-plugins/](url)

**Comment by mickadam29** [comment]
@JC38 
Rien de particulier. Parce que j'avais passé ma Zigate en 3.1D j'étais passé en version beta du market Jeedom. Puis, je suis repassé en 3.1C, tout réinclus. Donc j'avais plus le besoin d'être en beta. J'ai donc fait l'installation de la Stable tjs depuis le market jeedom. Et j'ai retrouvé une liste bien plus complète. Toutefois, c'est la capacité de l'afficher qui pose problème. Car même en version beta, les fichiers png étaient présents. Ce que je pourrais te conseiller : Sauvegarde JEEDOM. Désactivation puis suppression du plugin. Tu vérifies que tu n'as plus le répertoire Abeille dans plugins , soit par Jeexplore ou putty. Et après tu réinstalles. Là, s'il te manque encore des icônes (à afficher) ou liste incomplète, il faudra que tu sollicites @KiwiHC16 .

**Comment by JC38** [comment]
@mickadam29 . Je ne peux pas repasser en version du market pour le moment. Je suis en fw 3.1d, je ne veux pas revenir en arrière sur le fw et/ou refaire des inclusions, j'ai des périphériques qui sont à plus de 5 m de haut :-(
En plus, si je revenais sur la version du market, je me retrouverais certainement avec des devices non reconnus.
J'ai vu que dans la version master la fonction displayBeeCard avait été modifiée par rapport à la stable. Si j'ai bien compris, c'est cette fonction qui permet de récupérer les png. D'un point de vue file system, tous les png sont bien présents dans le dossier mais seulement quelques-uns sont listés. Malheureusement, je ne connais pas assez le code pour aller plus loin dans le débogage.

**Comment by KiwiHC16** [comment]
Sur mon systeme de dev avec master j ai bien Xiaomi Presence Aqara 2 dispo. Idem sur une machine en prod avec beta-dev du 2020-11-20.

**Comment by KiwiHC16** [comment]
```
Tu noteras également un pb sur ce nom 'node_ SM309.png' 
```

Correction poussée dans master.
