### ISSUE TITLE
Penser RPI "like" et non pas RPI

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1450]
Je suis désolé de remettre ca sur le tapis mais ca ne semble pas clair.

Un exemple concret: verifier la presence de la commande "socat".
Il y avait en PHP

> $cmd = "hash socat";
> exec($cmd, $out, $ret);
> if ($ret != 0) ... erreur
> 

puis

> $cmd = "command -v socat"

qui teste mieux que le "hash" puisque verifie qu'elle soit executable

et maintenant

> $cmd = "dpkg -l socat"

Meme si cette derniere peut fonctionner un peut partout supposant que dpkg est bien déployé, on a changé le but.

- Abeille a besoin de la commande "socat". Qu'elle vienne d'un package officiel dpkg ou non ne regarde pas Abeille. Sur certaines plateformes ce sont des packages custom.
- Mais pire, cette derniere commande verifie que le package est installé mais ne verifie plus que "socat" est bien installé et utilisable. Il y a, sauf erreur de ma part bien sur, une regression la.

En résumé ne se focaliser QUE sur les besoins d'Abeille et ne pas extrapoler. Besoin de la commande "socat" ne veut pas dire "package socat dpkg installé".
Vous me suivez ?

**Comment by KiwiHC16** [comment]
Oui je suis avec toi.

Perso, il faut le plus possible décorréler l'OS de Jeedom, d'Abeille.

Je me souviens d'un commentaire d'une personne qui avait fait des evaluaiton des differents systemes domotique et qui disait que Jeedom est trop permissif, c est a dire que les plugin se "permettent" de toucher à la conf systeme.
Perso je trouve que c'est sa puissance car tout est accessible.

Donc je dirai:
- on test la presence de socat (je vois hash, perso j aurrai utilisé which)
- si pas presente on demande l installation des dependances à l utilisateur.
- La ca va etre dependant de la plateforme et il faut faire des cas spécifiques.

Etes vous en ligne avec moi ?

**Comment by tcharp38** [comment]
@KiwiHC16 
Perso je ne vais pas perdre mon temps a repasser derriere ou faire mon "enquiquineur".
Je souhaite juste que l'objectif d'Abeille soit clair, de + en + robuste, et maintenable (regles de langage, commentaires, ...).
Et qu'on comprenne bien ou on peut introduire une contrainte pas necessaire ou ne repondant pas au reel besoin.

Bref c'est + un debat ouvert qu'un pb.

**Comment by KiwiHC16** [comment]
J ai mis @edgd1er et @tcharp38 car je pense que vous êtes les seuls à faire des changement dans cette partie du soft.

**Comment by KiwiHC16** [comment]
Je suis bien en ligne avec ton point de vue.
Je pense qu'on aborde une nouvelle phase pour Abeille qui est la participation de plus de personnes d'où les besoins de s'aligner et d'être plus méthodique.
On discute, on s'aligne et a plusieurs on fera plus que moi tout seul.... ;-)

**Comment by mickadam29** [comment]
D'autant que JEEDOM travaille sur le dev d'un plugin ZIGBEE. Donc on peut s'attendre à une parfaite cohésion entre les 2 deux. Pour le moment la zigate est en beta avec ce plugin. Conservez votre force qui est de développer rapidement et un support réactif
Bon courage à vous tous qui faites vivre Abeille

**Comment by KiwiHC16** [comment]
Qui prend ce sujet @edgd1er ou @tcharp38 ? (pour n'avoir qu'une personne qui fait du code et pousse un PR)

**Comment by edgd1er** [comment]
Bjr,

1er point: si du code est en cause autant mettre la branche, la classe et la ligne, ca évite de chercher, supputer et s'emballer, github le permet, autant etre clair et direct ;) meme avec le lien direct, des fois, je ne vois pas mes erreurs.

2eme point: jeedom est compatible debian, ubuntu par extension, Abeille est fortement liée à jeedom (pas d'abstraction) donc, je veux bien que Abeille sois compatible archLinux ou lfs, mais quelle utilité si jeedom ne fonctionne pas sur ces systèmes.

3eme point: si je comprends bien, dpkg -l socat est revenu qq part dans le code... je n'ai pas encore compris ou..
De mon coté, cette ligne de code n'existe plus, la ou je l'ai remplacé, c'était la:
https://github.com/edgd1er/Abeille/blob/4ce74552f05a2c9ce97e8c050b2d6bdec4e55415/core/class/Abeille.class.php#L776

Effectivement, jeedom est trop permissif et a besoin des droits root a différent moment, c'est une des raisons qui m'a facilité le passage a docker, en cas de mauvais dev ou manip, le droit root, ne casseront que le conteneur.... un docker pull est un jeedom est operationnel en qq secondes. bon, c'est surtout la facilité d'installation et de test qui m'ont fait adopter docker.

Plus on sera nombreux a dev et meilleurs seront les idées et le résultat donc :)

on ne vérifie pas le hash de la commande donc on vérifie juste son existence.
Command -v vérifie l'existence et le fait que ce soit un pgm executable, mais peut etre qu'on ne parle pas de la même chose.

**Comment by tcharp38** [comment]
Oui.
Tu l'as en partie decrit dans les regles developpeur
