### ISSUE TITLE
Poussoir avec Neutre Tuya

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1455]
@KiwiHC16 

Tu penses pouvoir intégrer ces interrupteurs ? Coût très intéressant et le fond est rond. Donc à priori encastrable
dans les anciennes "boîtes" pour de la rénovation. Il me semble avoir lu que Tuya ne respectait pas tout à fait la norme Zigbee

https://amzn.to/3h5jNtF

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
"Tu penses pouvoir" probablement oui mais quand ....

As tu l un des ces équipements ?

**Comment by mickadam29** [comment]
Pas encore commandé mais j'y réfléchis. Je voulais être certain de la compatibilité. Je creuse un peu les infos au sujet de Tuya et le respect Zigbee. Je te tiens au courant

**Comment by mickadam29** [comment]
Je me demande si tu ne le connais déjà pas sous le nom Zemismart. En tous cas c'est l'icone

**Comment by KiwiHC16** [comment]
On ne peut guere se fier au nom commercial...
