### ISSUE TITLE
prise Blitzwolf BW-SHP13 - problème unité intensité

### ISSUE THREAD

**Issue by pierre6641** [KiwiHC16/Abeille#1456]
Bonjour,
J'ai 2 SHP13
L'une est reconnue comme une Blitzwolf BW-SHP13
L'autre comme une TS0121, bien que je les ai reçues en même temps.
Sur la TS0121 il y a un SPA. La puissance affichée semble correcte, environ 1000W
Mais le courant affiché n'est pas bon, quelques dizaines de mA seulement.
Dans les 2 cas la conso reste à 0.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
D apres mes souvenirs la "Blitzwolf BW-SHP13" se presente sous le nom "TS0121" et c'est ce modele qui est utilisé.
C est une limite actuelle dans Abeille. Certains équipements se presentent sous le meme nom même si ils sont différents.
Il existe un solution pour gérer cette situation mais elle n'est pas implémentée dans Abeille.
Par contre ce qui me surprend est ton commentaire: "bien que je les ai reçues en même temps." est ce que l intégration a été faite avec la même version d'Abeille ? Quelle version ?

Sinon il faut que l on implemente ce bout de soft qui permet de faire la diff entre une Blitzwolf BW-SHP13 et une TS0121. Ensuite on pourra travailler sur les autres sujets.

**Comment by pierre6641** [comment]
Non l'intégration ne s'est pas faite en même temps. La 1ère prise il y a quelques semaines, puis j'ai vu qu'il fallait valider la version beta pour que la prise soit reconnue. Puis il y a eu 1 ou 2 mises à jour de la beta. Puis intégration de la 2ème prise. 
Pour exemple, actuellement la prise affiche 
V 220 
A 35mA 
P 953W

**Comment by KiwiHC16** [comment]
Ceci explique la difference.
Il faut que je resolve " limite actuelle dans Abeille."

**Comment by pierre6641** [comment]
Et si je les supprime toutes les 2 puis je les ré-intègre, ça peut résoudre le problème ? Je ne veux pas te créer des complications.

J'ai également posté dans un topic concernant une sonde Sonoff SNZB-02 non reconnue (device id 66666 le nombre de la bête ;-) )
A l'occasion si tu as le temps, mais c'est pas bien urgent tu sais.
Merci pour tout le temps que tu consacres à ce projet.

**Comment by KiwiHC16** [comment]
Ce que tu peux faire est supprimer le fichier TS0121, supprimer les objets dans Abeille et refiare l inclusion.

**Comment by KiwiHC16** [comment]
Gestion des equipements qui ont le meme nom zigbee mais sont differents. #1318

**Comment by pierre6641** [comment]
Merci beaucoup, je fais ça dès que je le peux, il faudra sans doute attendre la fin de la semaine, je rentre un peu trop tard en ce moment pour le faire. Je te tiens au courant

**Comment by KiwiHC16** [comment]
Le sujet est resolu mais demande la version d abeille de dev (master). Sera probablement dans la stable n+1. Pas celle qui devrait sortir mais la suivante.

Pas trop de solution en attendant.

**Comment by pierre6641** [comment]
J'ai vu ton message trop tard, j'ai supprimé les 2 prises puis inclusion des 2. Maintenant j'en ai 4 qui apparaissent.
![image](https://user-images.githubusercontent.com/74932819/100427195-61da7f80-3092-11eb-86d4-c177f99cccd1.png)

Je ne touche plus à rien en attendant la stable n+1

Quand tu me disais plus haut de supprimer le fichier TS0121, de quel répertoire parlais-tu ?
