### ISSUE TITLE
Master: Abeille.class: tryToGetIEEE: undefined variable: $eqLogicIds

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1457]
https://github.com/KiwiHC16/Abeille/blob/b95b747fbf84148770efefc202071370a07fb565/core/class/Abeille.class.php#L181

variable non définie donc ce code n'est jamais executé. est ce volontaire ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je ne comprends pas ce cas car sur la master on a:

```
 public static function tryToGetIEEE()
 ...
$eqLogics = Abeille::byType('Abeille');
....
foreach ($eqLogics as $key => $eqLogic) {
```

Soit deja corrigé, soit autre soucis que je ne vois pas.

**Comment by KiwiHC16** [comment]
tryToGetIEEE() regression fix + other minor fixes
 master (#1452)
@tcharp38
@KiwiHC16
tcharp38 authored and KiwiHC16 committed 13 hours ago 


Visiblement @tcharp a poussé une correction.

Par contre cela veut dire qu on a le bug dans la beta. Je regarde.

**Comment by KiwiHC16** [comment]
Pas de soucis dans la beta-dev.

Je clos. (rouvres si j ai loupé qq chose)

**Comment by edgd1er** [comment]
@KiwiHC16 

eqlogics est défini, pas eqLogic**Ids**

https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php dans ce fichier, un find ne trouve qu'une occurence. la ligne 182. donc la boucle cherche a parcourir un élément non défini, donc ne faire rien.

Y a t il qq chose qui m'échappe ?

**Comment by edgd1er** [comment]
bien joué @tcharp38 , a priori cette ligne répond à la non définition.
$eqLogicIds = array_rand( $tryToGetIEEEArray, 2 );

**Comment by tcharp38** [comment]
Pour moi c'est clos.
