### ISSUE TITLE
renomme le repertoire resources/AbeilleDaemon en resources/demond

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1460]

**Comment by KiwiHC16** [comment]
Reprendre l exemple de openzwave.

/usr/bin/python /var/www/html/plugins/openzwave/core/class/../../resources/openzwaved/openzwaved.py

Ce qui donnerait:

/var/www/html/plugins/Abeille/core/class/../../resources/Abeilled/Abeille*.php

**Comment by tcharp38** [comment]
Qu est ce qu'on fait de ce cas ?
Pour ma part je suggere de pas creer de structure dependant d'une fonctionalite.
Si le code match la structure officielle Jeedom (core/php core/class core.js ou cote UI desktop/php desktop/js...) alors on devrait utiliser cette structure et pas creer de zone speciale "demons". Les 2 choix sont opposés.

**Comment by tcharp38** [comment]
Cette idée est abandonnée.
On colle à la structure Jeedom

- core/php core/js core/scripts
- destkop/php ...
- mobile/php ...

Pas de repertoire par fonctionalité, donc pas de "demond".
Côte "Network" reste à voir ce qui ne rentre pas dans la structure ci dessus.
