### ISSUE TITLE
Branche master : type non identifié

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1465]
Bonjour Ben,

Par rapport à ta demande, je suis resté sur la branche master, elle semble plus souvent rafraichie que la branche beta.
Sinon, pour cette issue, voici le problème. Les derniers éléments que j'ai inclus n'étaient pas typé correctement, et quand on regarde la liste des icones, on voit qu'elle est beaucoup plus courte qu'avant.
Et même si on édite un objet existant , par exemple le contacteur entouré en jaune, je vois bien sa miniature depuis l'écran principal
![image](https://user-images.githubusercontent.com/16527222/100202078-1e044080-2f01-11eb-9f8c-ba8ce87bbd39.png)
Mais une fois édité :
![image](https://user-images.githubusercontent.com/16527222/100202001-0462f900-2f01-11eb-89aa-e0678165f06f.png)

PS : l'icône en haut à gauche intitulée Décodeur Orange est en fait une prise OsramLightify, mais ces prises ont disparues elles aussi de la liste des icones.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Es tu sure que tu es sur master car je ne vois pas le soucis sur mon systeme.
Comment as tu installé la master ?

![Capture d’écran 2020-11-25 à 10 14 59](https://user-images.githubusercontent.com/8549674/100206806-16e03100-2f07-11eb-9f67-140a985e3ec2.png)

**Comment by JC38** [comment]
J'ai suivi cette procédure [https://jeedomiser.fr/article/installer-vos-plugins/](url)
Depuis Github
Activez tout d’abord l’installation de plugins depuis Github dans Jeedom, via la roue crantée puis « Configuration« .
![image](https://user-images.githubusercontent.com/16527222/100212057-2e221d00-2f0d-11eb-8fcb-ec54e89e43c6.png)
Rendez-vous ensuite dans « Mises à jour » puis « Github« , cochez l’activation et cliquez sur « Sauvegardez« 
![image](https://user-images.githubusercontent.com/16527222/100212092-3a0ddf00-2f0d-11eb-9c08-00c785ceb6e5.png)
Retournez ensuite dans la gestion des plugins mais choisissez ensuite « Sources« .
![image](https://user-images.githubusercontent.com/16527222/100212150-4abe5500-2f0d-11eb-82c2-73c3731bc1e4.png)
Choisissez ensuite en type de source “Github” et saisissez les informations relatives au plugin (ici je vais prendre l’exemple du plugin FBbot qui n’est, à ce jour, plus proposé dans la liste des plugins du Market) :

ID logique du plugin : fbbot
(C’est simplement le nom du plugin à installer)

Utilisateur ou organisation du dépôt : NextDom
(vous le trouvez en haut, à gauche du nom de dépôt)

Nom du dépôt : plugin-fbbot
(Il apparaît en haut et se trouve côte à côte avec l’utilisateur)

Branche : master

Tu ne fais pas comme cela ? Ça marche bien (sur le papier au moins), et les maj de la branche master apparaissent aussi dans les maj proposées par Jeedom.

**Comment by mickadam29** [comment]
Sauf erreur, problème identique #1447 
Ce matin, j'ai des icônes aussi absentes. Mais sur la version beta d'hier.
Je vois que les droits sont différents. Même si ça ne peut-être la seule cause.
![image](https://user-images.githubusercontent.com/36518012/100218817-83622c80-2f15-11eb-9ca8-e72da09a6ba9.png)

**Comment by JC38** [comment]
@KiwiHC16 
Je suis passé de la master Github a la beta du Market. Rien n'a changé au niveau des icones.
Pour mon info, quelle est la différence entre canal beta et canal master sur Github ? Master semble plus à jour.

PS : j'ai écrit ce post il y a quelques jours, mais il était resté en brouillon :-(

**Comment by JC38** [comment]
Après le post du dessus que j'avais oublié de publier, je suis aussi passé de la beta du Market à la stable du Market, mais le problème des icones manquantes persistait. Aussi en cette fin de journée, j'ai fait une manip un peu plus radicale
1 - Sauvegarde de Jeedom au cas où...
2 - Arrêt du demon du plugin
3 - Rename du dossier Abeille en Abeille.old
4 - Rechargement du plugin en stable depuis le market et réactivation
5 - Tous les devices sont remontés, et j'ai pu sélectionner les icones manquantes car cette fois la liste est ok.

**Comment by mickadam29** [comment]
@KiwiHC16 

Cela confirme que sur mon système et celui de @JC38 la mise à jour ne prend pas en compte tous les fichiers. Une réinstallation est complète. J'ai fais le constat aussi en passant de la Beta Market à la stable Market (en suppriment le dossier Abeille, et dans ce cas tout est présent)
Une mise à jour est incomplète ou le zip ne parvient pas à mettre correctement les fichiers.

**Comment by KiwiHC16** [comment]
Des tests sont dans la prochaine version.
