### ISSUE TITLE
Détecteur de fumées Heiman 

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1467]
Je continue à scinder mes issues en tickets individuels comme demandé.
Détecteur de fumées Heiman : il s'appelle maintenant Humein ( ?) smoke sensor. C'est bizarre ce nom.
...
Je ne sais pas s'il fait bien son boulot de détecteur de fumées, quels sont les noms des commandes relatives à la fonction de détection qui devraient être présentes dans la liste de ses commandes ? Voici la liste et je n'en vois aucune qui semble faire référence à la détection de fumées.
![image](https://user-images.githubusercontent.com/16527222/100232444-a518df00-2f28-11eb-910c-d709049141d0.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Merci pour la separation des cas.

C est la commande Etat.
