### ISSUE TITLE
Déplacer "tmp" dans le tmp Jeedom => utilisation de jeedom::getTmpFolder()

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1468]

**Comment by tcharp38** [comment]
@KiwiHC16 Assigne le moi.
C'est en cours mais plus compliqué que ce que je pensais au début.

**Comment by tcharp38** [comment]
La generation des logs "previous" et la page support utilisent maintenant le tmp Jeedom au lieu du tmp du plugin.

**Comment by KiwiHC16** [comment]
Super, je clos alors.
