### ISSUE TITLE
Investigate PDM server.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#147]

**Comment by KiwiHC16** [comment]
JN-AN-1216 Chap B.4. Basically this is the Coordinator which control the protocol with the Host and binary need to be compiled with it set On.

**Comment by KiwiHC16** [comment]
Visiblement Abeille ne serait qu'un serveur au service de ZiGate qui controle les datas. Suppose aussi Controleur compilé avec cette option donc on verra si on en a besoin dans le future sur un tres gros reseau mais pour l instant je ne vois pas le besoin. Je clos le sujet.

**Comment by KiwiHC16** [comment]
#1286

**Comment by KiwiHC16** [comment]
https://zigate.fr/documentation/deplacer-le-pdm-de-la-zigate/


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/280

**Comment by KiwiHC16** [comment]
https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Technical/ZiGate-PDMonHost.md

**Comment by KiwiHC16** [comment]
https://github.com/pipiche38/Domoticz-Zigate/blob/4276f21030850b7f48893864fbe0c9ecfabb2ca8/Modules/pdmHost.py

**Comment by KiwiHC16** [comment]
Je ne vois pas le 0x0300 passer.
@pipiche38 si tu passes par là, comment trigger tu ce message de la part de la zigate ?

**Comment by KiwiHC16** [comment]
ZIgate attendrait le host ?
https://github.com/fairecasoimeme/ZiGate/blob/master/Module%20Radio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/pdm_host.c#L154

PUBLIC void vAppMain(void)

// 0x0300 - E_SL_MSG_PDM_HOST_AVAILABLE
PRIVATE void vInitialiseApp ( void )
    PDM_eInitialise ( u8NumberOfEEPROMsegments = 63 );
    PDM_vWaitHost(void)
    APP_MigratePDM();
    PDUM_vInit ( );
    PWRM_vInit ( E_AHI_SLEEP_OSCON_RAMON );

    // 0x0302 - E_SL_MSG_PDM_LOADED
    // Envoie message Start after PDM loaded
    vSL_WriteMessage ( E_SL_MSG_PDM_LOADED,

**Comment by pipiche38** [comment]
Le 0x0300 est envoyé par la zigate après un Off/on , un reset ou un Erase Pdm

**Comment by KiwiHC16** [comment]
Merci @pipiche38 pour ce retour. 
Je ne parviens pas avoir le 0x0300 dans aucun de ces trois cas. 
Doit on avoir un firmware spécifique?
Faire une config spécifique ?
Est ce qu une Zigate qui fonctionnait sur PDM interne va envoyer le 0x0300 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pipiche38** [comment]
J'ai failli te poser la question ;-) OUi il faut un firmware compilé en mode PDMonHost . Je pense que tu as tout compris, désolé de ne pas l'avoir dit plus  tot.

Il y  3 modes possibles

PDMonEEPROM (mode classique)
PDMonHost 
PDMonHostandonEEPROM

je pense que @fairecasoimeme n'a essayé que PDMonHost.

Autre chose, on a été obligé d'augment la vitesse  car le 115200 n'etait pas suffisant

**Comment by fairecasoimeme** [comment]
Désolé, 
oui il faut une version PDMonHOST compilé :

Je l'ai UP ici : 
https://github.com/fairecasoimeme/ZiGate/releases/tag/Pre_PDMonHOST

Cette version est bien à 115200 bauds

Fred

**Comment by KiwiHC16** [comment]
Ouf, je commençais à tourner bourrique et mon env de dev du firmware refuse de compiler. La lois de Murphy.
Bon j'essaye.
Merci.

**Comment by KiwiHC16** [comment]
Tout de suite c est en ligne avec le code ;-)
```
[2020-11-20 10:58:13][info ] Démarrage d'AbeilleSerialRead sur port /dev/ttyUSB0
[2020-11-20 10:58:14][debug] Reçu: "03000001DCDE"
[2020-11-20 10:58:16][debug] Reçu: "03000001DCDE"
[2020-11-20 10:58:18][debug] Reçu: "03000001DCDE"
```

**Comment by tcharp38** [comment]
Je clos ce sujet car ne me semble plus d'actualité.
Le PDMonHost n'est plus fourni.
A reouvrir si besoin.
