### ISSUE TITLE
Equipement deuxieme tab: param

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1471]
https://community.jeedom.com/t/onglet-telecommande-et-setgroupe-remote/43340/5

**Comment by KiwiHC16** [comment]
Suite a inclusion un equipement est créé.
Tab Param vide.
Sauvegarde de l equipement.
Tab Param n est plus vide. 

Images dans le forim.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by mickadam29** [comment]
Il n'y a pas que lors de l'inclusion. Sous chrome, lorsque tu arrives sur Param, parfois, il n'y a rien. Même sur des équipements créés de longue date. Que le paragraphe. Un simple F5 et les paramètres sont là. Mais cela ne crée peut-être pas ce qu'il faut et c'est pourquoi il faut faire F5 fréquemment

Avant
![image](https://user-images.githubusercontent.com/36518012/100353508-e1af0e00-2fee-11eb-83c9-f205e296b158.png)

Après le F5
![image](https://user-images.githubusercontent.com/36518012/100353496-dd82f080-2fee-11eb-92bc-79c03c8b4e51.png)

**Comment by Tonio16** [comment]
Je n'avais pas testé le F5 directement dans l'onglet Param vide.

Sinon, si on fait un F5 depuis la page du plugin, on perd à nouveau les champs de l'onglet param pour les dispositifs.

Antoine

**Comment by mickadam29** [comment]
Peut-être que cela ne concerne que les équipements sur secteur. Ceux sur pile ont au moins un champ de paramétré.

**Comment by Tonio16** [comment]
> Peut-être que cela ne concerne que les équipements sur secteur. Ceux sur pile ont au moins un champ de paramétré.

Pour moi, tous les dispositifs, secteur ou pile, sont concernés. 

Antoine

**Comment by mickadam29** [comment]
Je confirme. Mais il y a une notion de cache du navigateur. Hier, après avoir fait un F5 sur un équipement secteur, la page PARAM s'affichait systématiquement. Ce matin, de nouveau vide jusqu'au F5. Il suffit d'un F5 sur un équipement pour que la page s'affiche pour tous. Mais en relisant le paragraphe, tout est dit. Et comme les équipements sur pile ont l'info dans le modèle ....

Par defaut si cette partie n est pas definie dans le modele tout est affiché.
Si cela est defini dans le modele alors que les parameteres necessaires sont affichés.

Donc je pense que @KiwiHC16 a identifié un bug. Laissons le bosser dessus.

**Comment by KiwiHC16** [comment]
ce qu il doit se passer est qu Abeille teste ce qu il faut afficher. Tout est envoyé au browser web mais caché. Lors de la sauvegarde le core jeedom recoit tout meme ce qui est caché et le sauvegarde (probablement avec des valeurs vides). EL en refraichsasnt, il ne cache pas car les variables existent. Il faut que je confirme dans le code et fasse la correction.

**Comment by KiwiHC16** [comment]
Quand on clic sur un equipement on arrive sur la page:
http://abeille/index.php?v=d&m=Abeille&p=Abeille&id=729
Mais l'Id n est pas recu par le code.

Si on saisi l'adresse: http://abeille/index.php?v=d&m=Abeille&p=Abeille&id=729 directement alors on recoit bien l'id.

$_GET et $_POST vide.

Comportement identique sur safari et sur firefox.

**Comment by KiwiHC16** [comment]
Il semble que lorsque l on clic c est la fonction: $(".li_eqLogic,.eqLogicDisplayCard").on('click', function () {
dans core/js/plugin.template.js qui fait le boulot.

**Comment by tcharp38** [comment]
PR #1610 en attente

**Comment by tcharp38** [comment]
Ok dans le master.
