### ISSUE TITLE
Legrand Contacteur 20AX / Demande d'évolution

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1472]
@KiwiHC16 

J'ai mis en place le contacteur 20AX. Tout fonctionne très bien.
Commande et relevé de conso.
Pas contre, je voulais voir si il s'était déclenché dans la nuit en m'appuyant sur l'historique ON/OFF
Or ces 2 commandes n'ont pas l'option "Historiser".
Prévois-tu de l'ajouter ou y-a-t-il un moyen de l'ajouter de mon côté sans que cela ne disparaisse à la prochaine mise à jour.
Plus facile de voir des états ON/OFF sur un graph que de déterminer par la courbe de puissance. Même si puissance non nulle = ON

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je vais re-integrer celui que j'ai pour voir.

**Comment by mickadam29** [comment]
Merci à toi.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-12-01 à 14 03 15](https://user-images.githubusercontent.com/8549674/100744346-f704ad80-33dd-11eb-8d45-f58b1550f67c.png)

Et voila, c est dans le master. Je vais pouvoir installer le mien sur le tableau électrique ;-)

**Comment by KiwiHC16** [comment]
Je clos.

**Comment by mickadam29** [comment]
Merci
