### ISSUE TITLE
"Supprimer de Jeedom" ne fonctionne pas sur Zigate 4 (beta-dev)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1473]

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-28 à 10 10 25](https://user-images.githubusercontent.com/8549674/100498358-f1029880-3161-11eb-8801-9adf76bf0615.png)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-28 à 10 10 49](https://user-images.githubusercontent.com/8549674/100498365-ff50b480-3161-11eb-85a8-6ea5a964a2df.png)

**Comment by tcharp38** [comment]
"Supprimer tout" ?
Tu parles du bouton dans la zone developpeurs ?

**Comment by KiwiHC16** [comment]
Oui. Tu select et supprime

**Comment by tcharp38** [comment]
Je n'avais pas touché cette partie et je ne sais pas si ca fonctionnait avant.
Mais je vais faire l update si tu veux mais qu'est ce qu'on attend de "supprimer tout" ?
Il ya "supprimer de Jeedom" et la tu selectionnes ce que tu veux supprimer.
Mais supprimer tout, pas besoin de selectionner quoi que ce soit si c'est "tout".

Donc ton "supprimer tout" fait quoi ?

**Comment by KiwiHC16** [comment]
Pardon ce n est pas "supprimer tout" mais le bouton "supprimer de jeedom" comme visible sur capture ecran.

**Comment by tcharp38** [comment]
ok, je me regarde.
Je viens juste de repondre à ton dernier merge. Je pense que tu as fait une boulette "merge into stable"... #1474

**Comment by tcharp38** [comment]
@KiwiHC16 J'imagine que ca ne fonctionne pas pour zigate 4 mais pas mieux pour une zigate autre que 1 n'est ce pas ?

**Comment by KiwiHC16** [comment]
Sur 1 c est Ok. Sur 2 et plus je ne sais pas. Pas testé.

**Comment by KiwiHC16** [comment]
Sur master, je vois que le bouton est passé au niveau des zigates.
Si je fais le test suivant:
- activation de 6 zigates
- 6 zigate déclarées Wifi
- Sauvegarde
- re-demarrage daemon
- Creation de 6 Ruches
- Maintenant si je choisi une ruche et fais supprime alors ca fonctionne.

Je suppose que c est corrigé avec tes dernieres modifications. 

Je clos.
