### ISSUE TITLE
PHP Notice:  Undefined property: AbeilleParser::$ManufacturerNameTable in /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php on line 2329

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1478]

**Comment by tcharp38** [comment]
Pendant inclusion Xiaomi temp carré

**Comment by KiwiHC16** [comment]
Je ne trouve pas ce code donc a du être corrigé. Je clos.

**Comment by tcharp38** [comment]
Je l'ai commenté. Il m'a semblé incomplet.

>// Tcharp38: To be revisited for ManufacturerNameTable[] which appears to be empty
> // $this->deamonlog('debug', "  ModelIdentifier='".pack('H*', $Attribut)."', trimmed='".$trimmedValue."', ".json_encode($this->ManufacturerNameTable).', [Modelisation]');
>$this->deamonlog('debug', "  ModelIdentifier='".pack('H*', $Attribut)."', trimmed='".$trimmedValue."', [Modelisation]");
>
