### ISSUE TITLE
End Device raccroché à Zigate et un routeur en simultané

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1483]
@KiwiHC16 

Une anomalie du graphe ou est-ce possible ? Pour moi non
Comme on peut le voir, le End Device 2 est connecté à la Zigate 3 et à un routeur 1 sur le graphe

![image](https://user-images.githubusercontent.com/36518012/100781438-53ca8d00-340b-11eb-8afb-27fa72d3fa1d.png)

Confirmé dans le tableau des noeuds
L'objet est pourtant un détecteur de présence Aqara V2 (2) 
En plus de la ruche (3), c'est un contacteur SONOFF BASICZBR3 (1)

![image](https://user-images.githubusercontent.com/36518012/100782271-77420780-340c-11eb-9d35-9ca41aeeb245.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peux tu partager la colonne "Relation" de la table pour ces deux lignes ?

**Comment by mickadam29** [comment]
Pas de souci
Et encore merci.
J'en profite aussi pour te signaler, qu'on fonction des stables dispos sur le market, certains objets sont inconnus. 
Sur la N-2 (30/09 de mémoire, beaucoup étaient inconnus), l'avant-dernière tout était bon, et avec celle de matin (01/12) de nouveau des inconnus. Seconde image

![image](https://user-images.githubusercontent.com/36518012/100870106-5924e780-349e-11eb-8976-8dbed0fba079.png)

![image](https://user-images.githubusercontent.com/36518012/100870400-dbada700-349e-11eb-8a5a-3a588a6ef4d3.png)


L'objet inconnu 41C1, c'est mon contacteur LEGRAND 20AX, que tu viens de modifier. Tu y as fais référence dans un autre issue.

**Comment by KiwiHC16** [comment]
Effectivement les deux premiers lignes indiquent "Child" donc les deux représentations sont en accord.
Je peux imaginer les raisons suivantes:
- 8848 a changé de routeur de ratachement et l ancien n est pas au courant
- ...???...

Dans un premier temps patienter quelques heures et refaire un refresh LQI pour voir si les équipements se sont mis a jour.

Pour être vraiment sure il faudrait sniffer le traffic zigbee pour voir qui parle a qui....

(Ce n'est qu'une representation et n'impacte en rien le fonctionnement d abeille).

**Comment by KiwiHC16** [comment]
41C1: est ce que l objet Contacteur Legrand existe dans Abeille ?

**Comment by mickadam29** [comment]
Tout à fait d'accord. Cela n'empêche pas le bon fonctionnement. Cela fait qqs jours que j'ai remarqué cela. Donc refresh LQI effectué.
Dans le doute j'en lance un maintenant. Car pas fait depuis la maj de ce matin.
Mais je pense plus à un bug. 

> 41C1: est ce que l objet Contacteur Legrand existe dans Abeille ?

Oui. Et il est correctement actif. Pilote mon chauffage.

**Comment by KiwiHC16** [comment]
Est ce qu'il a son adresse IEEE dans la page santé ?

**Comment by mickadam29** [comment]
Le refresh LQI de la version 01/12 n'apporte rien. Tjs 2 accrochages. Mais je crois t'avoir communiqué une erreur.
Ce n'est pas avec le contacteur 20AX qu'il est associé c'est avec un contacteur SONOFF BASICZBR3
Et oui, l'adresse IEEE est présente (pour le sonoff du coup) On oublie le contacteur LEGRAND

![image](https://user-images.githubusercontent.com/36518012/100875519-6d6ce280-34a6-11eb-8000-b31225433051.png)

**Comment by tcharp38** [comment]
Juste pour info, il y a au moins un bug dans la partie de collecte des infos qui peut reporter une mauvaise adresse courte.
@mickadam29 
Si je te file une ligne de code à changer pour tester tu saura faire n'est ce pas ?

**Comment by mickadam29** [comment]
@tcharp38 

Oui. En principe pas de souci. Je peux te tester ça entre 12 et 14h

**Comment by tcharp38** [comment]
Tu es sur la derniere stable ?

Bon si jamais c'est le cas regarde cette diff. A droite c'est mon fix si tu veux tester chez toi.
Je vois suite à ca que parfois une ligne est doublée dans la table des noeuds (2 fois la meme chose) mais je pense qu'il s'agit d'un autre defaut.

![image](https://user-images.githubusercontent.com/35221038/101013487-aa97aa00-3564-11eb-8288-15d91e33db73.png)

Le code prefixé par "Tcharp38" est celui que je propose de changer pour ton test

>             // $srcAddress           = substr($payload, 52, 4); // Tcharp38
>             $NTListCount = substr($payload, 6, 2); // Tcharp38
>             $srcAddress           = substr($payload, 10 + ($NTListCount * 42), 4); // Tcharp38
>             $index                = substr($payload, 8, 2);
>             $NeighbourAddr        = substr($payload, 10, 4);
>             $NeighbourIEEEAddress = substr($payload, 30,16);
>             $lqi                  = hexdec(substr($payload, 48, 2));
>             $Depth                = hexdec(substr($payload, 46, 2));
>             $bitMapOfAttributes   = substr($payload, 50, 2); // to be $this->decoded
>             // $LQI[$srcAddress]     = array($Neighbour=>array('LQI'=>$lqi, 'depth'=>$Depth, 'tree'=>$bitMapOfAttributes, ));
> 
>             $data =
>             // "srcAddress="                   .substr($payload,52, 4) // Tcharp38
>             "srcAddress="                   .$srcAddress // Tcharp38
>             ."&NeighbourTableEntries="      .substr($payload, 4, 2)
>

**Comment by tcharp38** [comment]
Je crois que tu peux oublier ce correctif. Meme si il y a bug, je viens de voir que cette info ne semble pas utilisée au final.

**Comment by mickadam29** [comment]
Ne suis plus concerné car j'ai tout réinstallé. Zigate 3.1D et Abeille version github Master.
Je n'ai plus d'objet lié à deux routeurs.
