### ISSUE TITLE
Nouvelle perte des icônes.

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1486]
@KiwiHC16 
Je ne sais ce qui se passe avec les distrib, mais une fois sur 2, on perd les icônes.
De nouveau la liste est incomplète. De mémoire env 20 produits Xiaomi. Et là, à peine plus de 10.
Mise à jour faite ce matin. La précédente était complète.

![image](https://user-images.githubusercontent.com/36518012/100869863-f9c6d780-349d-11eb-8a6f-77118a4be21d.png)

![image](https://user-images.githubusercontent.com/36518012/100869627-95a41380-349d-11eb-8322-1fb29a27e661.png)

**Comment by KiwiHC16** [comment]
Master:
![Capture d’écran 2020-12-02 à 13 17 17](https://user-images.githubusercontent.com/8549674/100871515-b4f07000-34a0-11eb-9516-e95b4a85c735.png)


Stable:
![Capture d’écran 2020-12-02 à 13 19 15](https://user-images.githubusercontent.com/8549674/100871701-fb45cf00-34a0-11eb-97c9-51c96b97a14f.png)

**Comment by KiwiHC16** [comment]
Quelle version est indiquée dans la page de configuration ?
![Capture d’écran 2020-12-02 à 13 20 04](https://user-images.githubusercontent.com/8549674/100871776-19133400-34a1-11eb-8efc-2e908d0777cd.png)

**Comment by mickadam29** [comment]
Désolé, pas vu que le bandeau s'était positionné dessus. Celle que tu indiques. A savoir, 01/12 15h00

**Comment by mickadam29** [comment]
Désolé, ma copie d'écran voulait représenter la liste des XIAOMI. En fait, je ne sais pas si il me manque la ZLO-LTOSensor
Mais ce qui est certain c'est qu'il manque le XIAOMI Sensor Motion V2. Voir #1447
Dans la version précédente, je l'avais récupérée. Comme beaucoup d'autres objet d'ailleurs. Je mets à jour par rapport au market et je choisi stable. D'ailleurs, pour être précis je fais Mettre à jour dans centre de mise à jour

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-12-02 à 13 39 50](https://user-images.githubusercontent.com/8549674/100873708-dbfc7100-34a3-11eb-9972-675fa7d8617d.png)

29 Xiaomi sur mon systeme (stable).

Alors que 12 dans ton systeme avec la même version !!!

**Comment by KiwiHC16** [comment]
Que donne en ssh:
```
cd /var/www/html/plugins/Abeille/core/config/devices
grep -R Xiaomi * | grep name
```

**Comment by mickadam29** [comment]
On est d'accord mais il se passe qq chose. La fois d'avant déjà tu m'as montré que chez toi la liste était complète. Si tu te rapportes à #1447 j'avais mis une copie d'écran où ma liste était redevenue complète. Et là avec la maj de 01/12 j'a ide nouveau perdu une bonne partie. Je ne rentre pas dans le code, donc pas de fichiers personnalisés.

**Comment by KiwiHC16** [comment]
La stable est égale à la beta, c est jsute le nom qui change (sur le market).
Comment passes tu de l une a l autre ?

**Comment by mickadam29** [comment]
Ils sont présents. Mais c'est bien via l'interface de configuration de l'objet que ma liste est incomplète.
Je ne sais pas comment tu la construis, mais y a une différence entre les 2

3AFE170100510001/3AFE170100510001.json:    "nameJeedom": "Xiaomi Interrupteur simple",
ctrl_86plug.aq1/ctrl_86plug.aq1.json:    "nameJeedom": "Xiaomi Prise Murale Encastrée",
ctrl_ln1.aq1/ctrl_ln1.aq1.json:    "nameJeedom": "Xiaomi Wall Switch w Neutral 1",
ctrl_ln2.aq1/ctrl_ln2.aq1.json:    "nameJeedom": "Xiaomi Wall Switch w Neutral 2",
ctrl_neutral1/ctrl_neutral1.json:    "nameJeedom": "Xiaomi Wall Switch w/o Neutral 1",
ctrl_neutral2/ctrl_neutral2.json:    "nameJeedom": "Xiaomi Wall Switch w/o Neutral 2",
plug/plug.json:    "nameJeedom": "Xiaomi Prise",
plug.mmeu01/plug.mmeu01.json:    "nameJeedom": "Xiaomi Prise EU",
relay.c2acn01/relay.c2acn01.json:    "nameJeedom": "Xiaomi Module Double Switch Aqara",
remote.b186acn01/remote.b186acn01.json:    "nameJeedom": "Xiaomi Interrupteur Mural Carré Simple",
remote.b1acn01/remote.b1acn01.json:    "nameJeedom": "Xiaomi Bouton Aqara 2 Copy",
remote.b286acn01/remote.b286acn01.json:    "nameJeedom": "Xiaomi Interrupteur Mural Carré Double",
remote.b286acn02/remote.b286acn02.json:    "nameJeedom": "Xiaomi Interrupteur Mural Carré Double (Pile)",
sen_ill.mgl01/sen_ill.mgl01.json:    "nameJeedom": "Xiaomi Smart Ligth Sensor",
sensor_86sw1/sensor_86sw1.json:    "nameJeedom": "Xiaomi Interrupteur Carré simple",
sensor_86sw2/sensor_86sw2.json:    "nameJeedom": "Xiaomi Interrupteur Mural Carré Double",
sensor_cube/sensor_cube.json:    "nameJeedom": "Xiaomi Cube",
sensor_cube.aqgl01/sensor_cube.aqgl01.json:    "nameJeedom": "Xiaomi Cube",
sensor_ht/sensor_ht.json:    "nameJeedom": "Xiaomi Temperature Rond",
sensor_magnet/sensor_magnet.json:    "nameJeedom": "Xiaomi Door Sensor",
sensor_magnet.aq2/sensor_magnet.aq2.json:    "nameJeedom": "Xiaomi Door Sensor Aqara 2",
sensor_motion/sensor_motion.json:    "nameJeedom": "Xiaomi Presence",
sensor_motion.aq2/sensor_motion.aq2.json:    "nameJeedom": "Xiaomi Presence Aqara 2",
sensor_natgas/sensor_natgas.json:    "nameJeedom": "Xiaomi Gaz Sensor",
sensor_smoke/sensor_smoke.json:    "nameJeedom": "Xiaomi Smoke Sensor",
sensor_switch/sensor_switch.json:    "nameJeedom": "Xiaomi Interrupteur simple",
sensor_switch.aq2/sensor_switch.aq2.json:    "nameJeedom": "Xiaomi Bouton Aqara 2",
sensor_switch.aq3/sensor_switch.aq3.json:    "nameJeedom": "Xiaomi Bouton Aqara 3",
sensor_wleak.aq1/sensor_wleak.aq1.json:    "nameJeedom": "Xiaomi Inondation Aqara",
switch.b2nacn02/switch.b2nacn02.json:    "nameJeedom": "Xiaomi Wall Switch D1 w Neutral 2 Button",
Template/setReportIlluminanceXiaomi.json:    "name": "setReportIlluminanceXiaomi",
vibration.aq1/vibration.aq1.json:    "nameJeedom": "Xiaomi Vibration",
weather/weather.json:    "nameJeedom": "Xiaomi Temperature Carre",

**Comment by mickadam29** [comment]
> La stable est égale à la beta, c est jsute le nom qui change (sur le market).
> Comment passes tu de l une a l autre ?

Comme j'avais galéré avec le firmware 3.1D J'ai désinstallé le plugin beta (ou beta-dev) récupéré sur github.
Donc supprimé complètement le répertoire plugins/Abeille.
Depuis le market, j'ai réinstallé la stable. Mais cela fait plusieurs jours que je suis de nouveau sur la stable.
Lors de cette réinstallation je n'avais pas toutes les icones.
Dans la précédente version disponible sur le market en stable, j'avais tout récupéré.
Et avec celle d'hier, j'ai de nouveau perdu une partie de la liste. Uniquement la liste. J'ai bien les png

**Comment by mickadam29** [comment]
Il faut creuser sur le code. En particulier la façon de générer la liste déroulante. Les node_xxxx.png sont bien présents.

### Je vois que tu as changé tous les noms  .
###  Ils ne sont plus préfixés par node.

En même temps j'étais dans le répertoire devices et pas images

**Comment by Tonio16** [comment]
Bonsoir

Au cas ou cela pourrait aider, voici le comportement chez moi.
Si je vais sur mon abeille pour une ampoule Ikea, je n'ai que trois entrées dans la liste: abeille, ruche et ampoule innr edison RF263 vintage E27 (que je n'ai pas).
Version Abeille :beta, 2020-11-24 09:57:04 (pas d'autres de proposer)
Passage à stable en forçant la mise à jour depuis le market, relance du demon: version, 2020-12-01 15:00: là aussi seulement 3 entrées dans la liste Icone.

Les icones sont visibles dans la partie plugin mais pas dans les dispositifs.

Antoine

**Comment by mickadam29** [comment]
@KiwiHC16 @Tonio16 
Je confirme ce point. Une fois sélectionnée, càd avant de disparaître les images des objets sont visibles. Ici le motion_sensor_2

![image](https://user-images.githubusercontent.com/36518012/100923981-4d5a1500-34e0-11eb-9119-40ace3652065.png)

Mais si je repasse par la config de l'équipement, l'image n'est pas disponible

![image](https://user-images.githubusercontent.com/36518012/100924111-79759600-34e0-11eb-8d5a-5a7ba3544a05.png)

**Comment by mickadam29** [comment]
@KiwiHC16 

Si cela peut aider. Il manque bien des fichiers dans certaines versions STABLE que nous recevons du market. Je confirme que node_null.png n'existe pas chez moi dans /plugins/Abeille/image
Et du coup on peut se poser la question sur d'autres fichiers manquants, autres que des png disons peu vitaux au système.

![image](https://user-images.githubusercontent.com/36518012/100979423-056cd980-3544-11eb-8c61-d307c0bfe931.png)

**Comment by KiwiHC16** [comment]
Pouvez vous me donner la reponse en ssh à la commande:
```
df -h
```

**Comment by mickadam29** [comment]
jeedom@JEEDOM-DEBIAN:/var/www/html/plugins/Abeille/images$ df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev               1,9G       0  1,9G   0% /dev
tmpfs              386M     40M  346M  11% /run
/dev/sda1          454G    8,3G  423G   2% /
tmpfs              1,9G       0  1,9G   0% /dev/shm
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              1,9G       0  1,9G   0% /sys/fs/cgroup
tmpfs              128M    5,2M  123M   5% /tmp/jeedom
tmpfs              386M       0  386M   0% /run/user/1000

**Comment by JC38** [comment]
Pour info, je viens de publier une suite sur un sujet identique dans #1465 
ça ne donne pas l'origine du problème mais ça semble apporter une solution "de contournement"

**Comment by mickadam29** [comment]
@JC38 
Merci du retour. Cela confirme ce qui se passe chez moi aussi.
En désinstallant et en réinstallant le plugin Stable depuis le market tout était revenu. Liste des icônes, et fichiers png complets.
Une mise à jour et je perds la moitié de la liste dans la config des équipements. Alors que les png sont toujours là
@KiwiHC16 
Une piste à  nous communiquer ? Genre quelle fonction crée la liste des icones dans fichier php ? Je peux mettre le nez dans le code afin que tu te concentres sur d'autres problèmes. Car on va dire que c'est gênant et pas bloquant

**Comment by JC38** [comment]
@mickadam29  : je pense que le code est dans ce dossier desktop/php. Ils ont modifié récemment le contenu en splitant le code en plusieurs pages. Cherche du côté de la fonction displayBeeCard, je pense qu'elle est dans le coup même si je ne lis pas le php dans le texte :-(

**Comment by KiwiHC16** [comment]
Je ne pense pas que cela vient du code Abeille mais du core jeedom. Voici ce que je vois.

- le code abeille lit tous les modeles (*.json) recupere les noms et genere la liste.
- J ai lu qq part que vous aviez des json vides
- Je vois dans df que tmp est 128M

Nous avions un soucis avec la taille d'Abeille. Nous avons réduit la taille au max mais il est possible que cela pose toujours un soucis.
En gros, un zip d'Abeille est téléchargé dans /tmp ou il est dezippé. Le zip plus le dezip, remplissent la partition /tmp mais le processus ne s arrete pas. Le unzip crée des fichiers vide (de facon aleatoire).
J'avais travaillé sur la partie installation qui semble être corrigé maintenant.
Mais d apres vos retour, la partie update a le meme soucis.
De mon point de vue, il faut chercher de ce côté dans un premier temps.

**Comment by KiwiHC16** [comment]
Avez vous des logs de l upgrade pour regarder si nous avons des erreurs dedans ?

**Comment by mickadam29** [comment]
@KiwiHC16 
Je regarde ces points et te fais un retour.

**Comment by Xav-74** [comment]
Même souci de mon côté.

Jeedom v4.1.16
Abeille master uptodate

Pour ma part j'ai perdu la partie volet Profalux (BSO OK) et prise IKEA Tradfri

Pas bloquant dans l'utilisation au quotidien sauf que régulièrement ces équipements uniquement partent en Time Out. Un redémarrage du démon et c'est reparti.

A dispo

Xav

**Comment by KiwiHC16** [comment]
Pout tous jeedom V4.1.x n est pas encore supporté. Xav-74 est à la pointe et à fait les corrections necessaires.

```
 j'ai perdu la partie volet Profalux (BSO OK) et prise IKEA Tradfri
```

Que veux tu dire ?

**Comment by Xav-74** [comment]
Je te confirme que je suis en train de faire les modifs pour la 4.1 :) PR ce week-end si tout va bien 👍 

J'ai perdu les icônes des équipements dans  la liste déroulante :

![image](https://user-images.githubusercontent.com/56156622/101175657-b73fff00-3645-11eb-8229-7e31fc01f0a4.png)

Idem pour les prises IKEA Tradfri.
Ma liste s'est fortement réduite lors du passage en master.

Xav

**Comment by JC38** [comment]
Pour le df -h
root@debian:~# df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev               3,9G       0  3,9G   0% /dev
tmpfs              790M     81M  709M  11% /run
/dev/sda1          110G    8,5G   96G   9% /
tmpfs              3,9G       0  3,9G   0% /dev/shm
tmpfs              5,0M    4,0K  5,0M   1% /run/lock
tmpfs              3,9G       0  3,9G   0% /sys/fs/cgroup
tmpfs              128M     11M  117M   9% /tmp/jeedom
tmpfs              790M       0  790M   0% /run/user/0

Sinon, j'ai toujours dispo l'ancien dossier du plugin, celui qui liste mal les images. Je peux donc retrouver des infos et comparer avec la version stable rechargée "clean" du market.
Pour le dossier images, je n'ai pas vu de différence notable entre les 2. Les png sont là, aucun fichier ne fait 0 octet.

**Comment by KiwiHC16** [comment]
Sur un upgrade j ai le log:
```
26350K              88.5M=0.5s
2020-12-04 18:11:29 (49.2 MB/s) - '/tmp/jeedom/market/Abeille.zip' saved [27026311]
[2020-12-04 18:11:29][ALERT] : | OK
[2020-12-04 18:11:29][ALERT] : Décompression du zip
[2020-12-04 18:11:29][ALERT] : | OK
[2020-12-04 18:11:29][ALERT] : Post-installation de Abeille
[2020-12-04 18:11:29][ALERT] : Supression des fichiers inutiles
[2020-12-04 18:11:30][ALERT] : | OK
[2020-12-04 18:11:30][ALERT] : Launch cron dependancy plugins
[2020-12-04 18:11:30][ALERT] : [END UPDATE SUCCESS]
```

Donc il descend 26350K -> 26Mo (en ligne avec la nouvelle taille) dans tmp/jeedom/market/Abeille.zip

Quelle est la taille de votre zip ? 26Mo ?

**Comment by KiwiHC16** [comment]
Branche master : type non identifié
#1465

**Comment by mickadam29** [comment]
Pour ma part

 26350K .......... .......... .......... .......... ..          793K=36s

2020-12-03 21:12:47 (741 KB/s) - '/tmp/jeedom/market/Abeille.zip' saved [27026328]

**Comment by Xav-74** [comment]
> C est les json qui doivent faire 0 octets

Pour ma part le json est bien OK (1ko)

![image](https://user-images.githubusercontent.com/56156622/101240568-4144a200-36f0-11eb-8916-dbc67fcfd95f.png)

**Comment by Tonio16** [comment]
La stable du jour n'a rien changé pour moi.

Antoine

**Comment by mickadam29** [comment]
@KiwiHC16 

Je te confirme qu'une suppression complète du plugin, suivie d'une réinstallation permet d'avoir une liste complète des icones.
Donc il y a un sérieux souci avec les mises à jour faites par l'installation depuis le market.
Opération refaite ce matin car j'ai repassé ma Zigate en 3.1D.

**Comment by JC38** [comment]
Pour les json, ils sont tous présents dans les 2 dossiers de plugin (Celui de Abeille ok, et l'ancien de Abeille ko). Aucun ne fait 0 octet.

**Comment by mickadam29** [comment]
La mise à jour par Github ne semble pas impacter ce fonctionnement. J'abandonne la maj via le Market.

**Comment by Xav-74** [comment]
Bon je confirme qu'après renommage du plugin en .old et réinstallation de la master depuis Jeedom, tout est revenu.
Je viens également de m'apercevoir que du coup les options présentes dans l'onglet param des équipements ont également réapparu !
Je pensais au départ que cela venait de la version master.

**Comment by mickadam29** [comment]
@Xav-74 
J'avais le même comportement pour la liste des icônes. Si cela fait comme chez moi, attends-toi à perdre à nouveau des éléments lors de la prochaine màj via le market. Pour quelle raison je ne sais pas. Comme l'a dit @KiwiHC16 peut-être un espace insuffisant sur le /tmp/jeedom. Et malgré un dézip incomplet, la mise à jour continue, engendrant des problèmes dans le plugin.
Mais je te l'accorde, une suppression, réinstallation ne semble pas impactée comme une mise à jour.

**Comment by Xav-74** [comment]
Je vais voir sur la prochaine MAJ car comme je suis sur la branche master et non stable, je fais forcément la mise à jour via le github. Mon souci a du arriver avant, lorsque j'étais en stable. Je vous tiens au jus

**Comment by KiwiHC16** [comment]
Je viens de reproduite un comportement très similaire.
Je suis sur la derniere stable du market. Je fais croire à jeedom qu'une nouvelle version est dispo.
Je rempli le repertoire temporaire pour avoir la place du fichier zip récupéré du market mais pas assez de place pour faire le unzip complet. Aucune erreur du core jeedom par contre plein de fichiers vide dans le repertoire du plugin.

J'ai ajouté un test dans la page de configuration du plugin pour avertir si l espace n'est pas suffisant.

Sera dans la prochaine stable.

**Comment by bocquetm** [comment]
Solution trouvée dans #1536
