### ISSUE TITLE
cmd execAtCreation ne semble pas toutes etre exécutées.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1491]

**Comment by mickadam29** [comment]
@KiwiHC16 
Abeille dernière version stable du market installée ce matin. (Suppression de la version précédente)
Jeedom 4.0.61
Zigate 3.1D

Si tu veux dire que les commandes sur les équipements ne se créent pas alors je te confirme. Ce n'est pas "semble pas"
J'ai repassé ce matin ma zigate en 3.1D avec erase de l'EEPROM. J'ai désinstallé Abeille. Et je commence à inclure mes équipements.
Certains se passent sans problème. Genre Ampoule IKEA. Les prises en revanche c'est très aléatoire. Très rapide comme très compliqué. Mais les commandes sont là
En revanche, j'ai des équipements qui sont inclus, et où il ne se passe rien en interrogeant les commandes.

Si on parle bien de la même chose, j'ai 2 sirènes. Modèle identique. L'une s'est bien créée avec ses commandes actives, l'autre à ses commandes dans l'équipement mais quasi aucune ne fonctionne. Pour info, ces objets ce sont encore créés alors que la zigate n'était pas en inclusion.

Autre exemple, le contacteur 20AX Legrand ne remonte pas sa puissance. Cela fonctionnait très avant que je ne réinstalle tout.
La commande est créée pour l'équipement. Mais pas alimentée. Puissance nulle malgré ON

![image](https://user-images.githubusercontent.com/36518012/101253861-dbbbda00-371e-11eb-9686-768f4af8281a.png)
![image](https://user-images.githubusercontent.com/36518012/101255887-74525a00-371f-11eb-8d46-cfacacc1290b.png)


Le online fonctionne parfaitement

![image](https://user-images.githubusercontent.com/36518012/101254763-1f164880-371f-11eb-8580-2ffbaedddb47.png)

**Comment by KiwiHC16** [comment]
Non ce n est pas le meme sujet. Je clos. Si tu as un soucis ouvre une issue spécifique.
