### ISSUE TITLE
demande ajout equipement TRADFRIDriver30W

### ISSUE THREAD

**Issue by letiou** [KiwiHC16/Abeille#1493]
Bonjour,

pouvez-vous ajouter l’équipement TRADFRIDriver30W c'est le même que TRADFRIDriver10W qui existe déjà dans Abeille, la différence c'est que c'est du 30W.

Merci.

Bon courage :)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Dispo dans la stable de demain

**Comment by Brugal21** [comment]
Salut @KiwiHC16,

Le transfo 30w existait déjà, je l'ai depuis plus d'un an. On avait d'ailleurs essayé de travailler dessus car il ne remonte pas son état en "instantané" mais au bout de presque 1min...
Il y a plusieurs noms dans les templates des objets pour ce transfo : driver30w, transfo30w et pareil pour le 10w. Si tu recréer quelque chose ça en fait 3 maintenant.
