### ISSUE TITLE
Equipement met la Zigate en inclusion: Contacteur 20AX Legrand / Tete Radiateur Spirit / ???

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1496]
@KiwiHC16 

Abeille stable du market
Jeedom 4.0.61
Zigate 3.1D

Le contacteur LEGRAND 20AX, lorsque tu appuies sur le bouton d'inclusion est capable de passer lui même la zigate en inclusion.
Très dangereux à mon avis.
Pourrais-tu confirmer cela ? 
J'appuie 5 secondes sur le petit bouton, qui passe en violet et la zigate, elle passe en inclusion

**Comment by KiwiHC16** [comment]
Il faudrait que tu me décrives la manip car cela ne me parait pas faisable.

**Comment by mickadam29** [comment]
Lorsque tu appuies sur le petit bouton en façade du contacteur, il passe en couleur "violet/rose". Peu importe. On est loin du rouge ou du vert. Et lorsqu'il est dans cet état, la Zigate se met à clignoter, comme lorsqu'elle est en inclusion. Rien d'autre de spécial. Je n'ai pas vérifié le status à l'instant précis. Reproductible, si je parviens de façon certaine à mettre le contacteur sur l'état violet.

**Comment by mickadam29** [comment]
Pourrais-tu m'expliquer la façon dont tu as inclus ce contacteur ? Zigate en inclusion et simple mise sous tension, appui de qqs sec sur le bouton, séquence d'appui, genre 3 ou fois ,,,,
De mon côté je tente le mode inclusion forcé

**Comment by KiwiHC16** [comment]
C est quoi le mode inclusion forcé ?

**Comment by mickadam29** [comment]
Bon c'est confirmé. Le mode inclusion forcé, c'est le contacteur qui met la zigate en inclusion. LED bleue clignote
Je viens à l'instant d'appuyer sur le contacteur. Le contacteur est passé de éteint, à clignote bleu, à vert.
La zigate est passée en inclusion. Confirmé par la commande

![image](https://user-images.githubusercontent.com/36518012/101276581-3c462800-37ae-11eb-804e-0561ccbdf35a.png)

**Comment by mickadam29** [comment]
Un équipement est en mesure de passer la zigate en inclusion

**Comment by tcharp38** [comment]
Il me semble que j'ai déja vu ca avec mes manips Profalux.
A priori il est possible que l'equipement stoppe l'inclusion, mais je n'ai pas pu confirmer le contraire.

**Comment by mickadam29** [comment]
@tcharp38 
Pour lesquels tu as aussi des soucis, de mémoire. 
Est-ce normal et dans la norme Zigbee d'ailleurs qu'un équipement puis passer le coordinator en inclusion ?
J'ose pas imaginer si en plus il lui prend l'idée de faire un erase EEPROM, construction d'un nouveau réseau, changement du canal, .....

**Comment by tcharp38** [comment]
Oui de mon cote je n'ai pas fini avec mes soucis. Je cumulais plusieurs trucs mais je n'ai toujours pas retenté la 3.1d.
Fermer un reseau doit faire partie du standard. L'ouvrir par qqn d'autre que le coordinateur.. bizarre. Mais je n'ai aucun doute que le "erase pdm" à distance est juste impossible. Ca serait un trop gros danger.

**Comment by KiwiHC16** [comment]
Je ne connais pas d'option Zigbee pour faire cela mais on peut tout imaginer.
Chez Legrand c est possible avec la telecommande Entrée/Sortie mais ca semble propriétaire.

Je tenterai la manip pour voir si je parviens à le faire et je suifferai le truc.

**Comment by KiwiHC16** [comment]
2 observations supplémentaires:
- une zigate en prod chez moi se met à clignoter de temps à autre
- lors d'une inclusion d'un xiaomi temperature il s est associé avec Zigate4 alors que j avais mis zigate1 en inclusion, en fait zigate4 etait (d apres sniff) en mode inclusion et semble avoir été provoqué par un rejoin de tete radiateur spirit.

Il faudrait voir si dans la norme un rejoin peut provoqué la mise en inclusion d'un coordinateur

**Comment by tcharp38** [comment]
@KiwiHC16 Juste pour info j'ai déja vu ce comportement en jouant avec mes volets profalux. La zigate passait en mode inclusion ou en sortait. J'ai cru rever.
A priori en sortir c'est possible d'apres pipiche.

**Comment by KiwiHC16** [comment]
J ai aussi cru rêver mais si le device à la clef et est deja enregistre par la zigate alors pour le recuperer on peut imaginer ce scenario. Il faut depouiller la doc zigbee.

**Comment by tcharp38** [comment]
Je clos ce vieux sujet. A reouvrir si besoin.

- Un device peut fermer le reseau (ex: volets profalux)
- Donc je suppose qu'un device peut aussi declencher une inclusion si il est deja dans le reseau bien sur
