### ISSUE TITLE
Les équipements passent en timeout

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1497]
@KiwiHC16 

Dernière version du market installée le 5/12
Jeedom 4.0.61
Zigate 3.1D

Je remets le sujet sur un nouvel issue. Car je repars sur une installation nouvelle vis à vis des problèmes de TimeOut.
Sauf pour ma version Debian

Certains équipements sont déjà en timeout. Réinstallation ce matin.
Je veux bien croire qu'il pourrait s'agir de perturbation et que Zigate ne parvienne pas à décoder le datagramme. Mais je ne crois pas un problème de portée, de pile ou ce genre de souci. L'équipement est neuf. Il s'agit d'un interrupteur Xiaomi simple sur pile

Et, lorsque j'appuie sur le bouton, rien n'arrive, ne se passe vis à vis du scénario. Des problèmes sur les adresses IEEE, mais vu sur un autre issue. Trop de temps à consacrer sur la nouvelle inclusion de tous mes équipements mais ça mériterait de mettre le sniffer en service. Pour le Xiaomi, qqs minutes après le scénario fonctionnait. Et maintenant, plus rien
Je vais refaire l'inclusion, on verra combien de temps ça dure. Et pour l'équipement qui a perdu sa IEEEE, c'est encore et toujours un équipement qui s'est créé seul sans que la zigate soit en inclusion. Du moins pas à ma demande.

![image](https://user-images.githubusercontent.com/36518012/101258279-be3c3f80-3721-11eb-814d-a581d38e1166.png)

**Comment by mickadam29** [comment]
Un bouton SONOFF vient de passer en timeout. Sans qu'il soit désactivé, impossible de détecter l'appui. Cela fonctionnait encore il y à 2h. Timeout produit par absence d'activité de l'équipement. Normal si l'on considère que c'est un poussoir. Mais un appui dessus devrait envoyer l'info. Zigate ne comprend rien car ne connait plus l'objet. Des objets "disparaissent" car Zigate ne voit pas l'adresse de l'objet qui lui communique une info ? L'équipement Abeille1/.... est vide. J'ai aussi du réinclure un interrupteur. En revanche j'ai pas le log pour l'interrupteur.

![image](https://user-images.githubusercontent.com/36518012/101276818-f0947e00-37af-11eb-8b82-a605c14ce6da.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Cf ma prposition de support sur les autres issues.

**Comment by mickadam29** [comment]
Comme j'ai tout réinstallé depuis hier, avec la version github Master, je verrai dans le temps la stabilité.
Ce matin, qqs éléments en timeout mais en déclenchant une action (mouvement pour les capteurs, ouverture d'une fenêtre pour les capteurs d'ouverture) ils sont revenus corrects. Sauf pour un capteur de température mais qui passait sans doute par une prise Ikea. Elle même passée en timeout qqs minutes après. Donc des doutes quant à l'utilisation des prises IKEA pour faire routeur.

**Comment by mickadam29** [comment]
Plus de timeout. Les prises IKEA, finalement ne sont pas de bons routeurs.
