### ISSUE TITLE
Installation / Maj de ABEILLE. Market ou Github

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1501]
@KiwiHC16 @tcharp38 

Je m'adresse à vous car là franchement je comprends plus rien.
Après de multiples installation/désinstallation, màj Firmware Zigate ....
j'en arrive à me demander quelle version, et surtout quelle fiabilité accorder à l'installation/maj de Abeille depuis le market.

Rencontrant énormément de difficultés, après avoir tout réinclus encore hier, j'ai décidé une nouvelle fois de tout désinstaller.
Mais cette fois, en utilisant Github en tant que source.
Et je constate que l'installation semble aller jusqu'au bout sur mon installation. Contrairement à la version du market. Je ne sais pas encore si les màj par Github fonctionneront mieux mais je reste convaincu que mes problèmes viennent d'une màj incomplète. Je le constate sur des json non mis à jour par exemple.

 @KiwiHC16 tu mentionnais un problème d'espace sur tmpfs /tmp/jeedom
C'est peut-être la cause.

Très clairement, je vous invite à être verbeux dans les logs de mise à jour. Afin que d'autre et  moi puissions mieux comprendre les dysfonctionnements.

Je reviendrais poster les résultats de cette installation via Github. Car parmi les problèmes, il y a des timeout d'équipements, le contactor 20AX Legrand, ..... Je verrai aussi pour alimenter les autres issues. 

Bon courage à vous. Je pars inclure mes 43 équipements pour la 4ème fois depuis un mois.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Essayons de traiter les sujets un à un car sinon tu vas passer beaucoup de temps et risque de perdre patience.

Il y a d'autres issues ouvertes concernant des problemes sur la mise a jour d'Abeille depuis le market. La prodecure de mise à jour est controlée par le coeur de Jeedom et pas par les plugins. On continue les investigations dans les autres issues.

**Comment by KiwiHC16** [comment]
Une fois que tu as fais une installation github avec la branche stable. Tiens moi au courant et si tu le souhaites je peux me connecter sur ton systeme pour regarder ce qu'il se passe. Il me faudrait dans ce cas, deux sessions ssh ouvertes et l interface jeedom. Tu partages ton ecran avec anydesk.com. Tu me fourni ton code d acces et je regarde.

**Comment by mickadam29** [comment]
Pas de soucis @KiwiHC16. Il est certain que pour le moment, les inclusions se font très bien. J'inclus d'abord tous mes routeurs puis je passerai au End Device. C'est surtout niveau Scénarios et Alarme que c'est compliqué. Mais déjà, comme mes équipements sont connus de la Zigate, ca simplifie par rapport à hier où j'avais effacé la PDM. Je retiens ta proposition de AnyDesk pour ma prochaine mise à jour.

**Comment by mickadam29** [comment]
Voilà, j'ai tout réinclu. Reste à revoir les scénarios, les vues, design, .... car comme je suis reparti de 0, je n'ai plus aucun historique lié aux objets Zigbee. (temp, humidite ,.....)
Je vérifier la stabilité de tout ça et te recontacte. A priori, il n'y a que le contacteur Legrand qui pose un pb. La conso parvient à zigate mais n'est pas collectée/affichée/historisée
Comme dit plus haut, la version Market ne devait s'installer correctement et entièrement. En tous cas certainement pas lors des mises à jour.
Quelques adresses IEEE manquantes. On verra dans le temps.
Merci à toi

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

Suite à la réinstallation depuis le github, branche Master
Jeedom   ->  V 4.0.61
Zigate   -> 3.1D
Abeille Github / Master   ->   master_tcharp38, 2020-12-02 15:16:06

Une fois tout inclus, je constate 

1) Une erreur apparait toutes les heures avec le cron Hourly. L'erreur fait mention de $this 
Erreur sur la fonction cronHourly du plugin : Using $this when not in object context

![image](https://user-images.githubusercontent.com/36518012/101323958-bf788400-3869-11eb-948b-34def94949e0.png)

2) Un objet, qui est réintégré dans le réseau, n'est pas vu comme une mise à jour mais comme un nouvel équipement. Passer par les commandes Objet Cassé/Objet Remplace fonctionne bien.

3) Prise SONOFF BASICZBR3 : Fonctionne de façon classique. Anomalie : Dans un groupe (piloté par télécommande HUE), la commande ON fonctionne. Pas la OFF.

4) Contactor 20AX Legrand : Pilotage sur ses fonctions ON/OFF mais la puissance et le mode ne sont pas remontés jusqu'au widget. Le datagramme de la puissance est bien reçu par zigate.

**Comment by KiwiHC16** [comment]
1. #1503 
2. #1504
3. #1505
4. #1506

**Comment by KiwiHC16** [comment]
Je clos cet issue qui contient trop de sujets et on va suivre dans les issues filles.
