### ISSUE TITLE
télécommande 5 boutons IKEA TRÅDFRI : un appui simple sur le bouton On/Off n’est plus détecté

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1502]
https://community.jeedom.com/t/tradfri-ampoule-a-led-e14-w-c-et-tradfri-telecommande-5-boutons/42465/10
version stable, 2020-12-01 15:00.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ma ZiGate est en version de firmware 3.0f.

**Comment by Brugal21** [comment]
Salut,
je confirme le problème, l'info click-middle ne remonte plus pour les télécommandes IKEA 5 boutons mais aussi pour le détecteur IR IKEA et pour les interrupteurs ON/OFF IKEA...
Je suis en firmware 3.1D avec une fresh install depuis cette semaine. J'étais en stable du 30/09/20 avec un firmware 3.1C avant et ça fonctionnait bien, j'ai des scenarios qui utilisent ces infos.
Je reviens sur l'issue #1063, l'info de la couleur de température du blanc pour les ampoules IKEA, XIAOMI et PHILIPS et l'info de la couleur RGB des ampoules couleurs IKEA ne fonctionne toujours pas et ce depuis mars maintenant.

Je vois qu'il y a beaucoup d'issue ouverte, alors courage !
Merci pour tout le travail

**Comment by KiwiHC16** [comment]
Je viens de tester et cela fonctionne.

**Comment by Brugal21** [comment]
Juste pour confirmer, ça fonctionne bien maintenant !
