### ISSUE TITLE
Un objet, qui est réintégré dans le réseau, n'est pas vu comme une mise à jour mais comme un nouvel équipement.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1504]

**Comment by KiwiHC16** [comment]
Suite à la réinstallation depuis le github, branche Master
Jeedom -> V 4.0.61
Zigate -> 3.1D
Abeille Github / Master -> master_tcharp38, 2020-12-02 15:16:06

**Comment by KiwiHC16** [comment]
Un objet, qui est réintégré dans le réseau, n'est pas vu comme une mise à jour mais comme un nouvel équipement. Passer par les commandes Objet Cassé/Objet Remplace fonctionne bien.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
@KiwiHC16 Un truc que j'aurais cassé ?

**Comment by KiwiHC16** [comment]
Je ne sais pas. Cela peut se produire quand un equipement est créé mais n'a pas recu son IEEE, et dans ce cas un autre peut être créé si l adresse courte a changée.

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 
Lorsque je suis allé dans santé, j'ai vu des objets avec IEEE inconnue. Mais je ne saurai pas vous dire si lors de la nouvelle inclusion cela concernait le même objet.

**Comment by mickadam29** [comment]
Peut-être un bug sur la fonction Remplace.
Version Github Master
Zigate 3.1D

Ayant des soucis de timeout sur un équipement qui passait par une prise IKEA, j'ai débranché la prise.
Voulant gagné du temps j'ai refait l'inclusion de cet équipement. Tout s'est bien passé.
Ensuite, j'ai voulu faire le "Remplace". Donc Gost, ancien ID, Remplace nouvel ID.

Donc je m'attends à ce que le nouvel objet disparaisse. Et que l'ancien récupère l'adresse courte pour que ce nouvel objet hérite finalement de l'historique de l'ancien.

Visiblement, il m'a supprimé le nouvel objet et l'ancien est toujours en timeout. Donc la fonction remplace à échoué.
je vais retenter la manip

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/101357855-52311700-389a-11eb-98d2-cf50c770d16a.png)

A droite, l'ancienne référence (objet en timeout). A gauche, le même équipement (physique) nouvellement inclus.
Ci-dessous, c'est inversé. A gauche en timeout, à droite nouvel objet

![image](https://user-images.githubusercontent.com/36518012/101358138-b8b63500-389a-11eb-9f4e-545be0fbe1e3.png)

J'utilise la fonction Remplace

![image](https://user-images.githubusercontent.com/36518012/101358261-e4391f80-389a-11eb-9bb9-eefa375f7f95.png)

Cette fois-ci, c'est le nouveau nom qui est conservé. Pourquoi pas si son historique correspond à celui de l'ancienne référence.

![image](https://user-images.githubusercontent.com/36518012/101358455-29f5e800-389b-11eb-89c0-4405cc1c76cb.png)

Visiblement c'est bien le cas. Donc RAS. Mais cela confirme que juste avant, la fonction remplace n'a pas fonctionné et a supprimé le nouvel objet sans faire le remplacement.

![image](https://user-images.githubusercontent.com/36518012/101358555-4db92e00-389b-11eb-8441-3f1de8efd891.png)

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 
Il y a quand même un problème avec les mises à jour d'objet. La fonction remplace ne fait pas tout. Si j'ai retrouvé l'historique,
une vue est incomplète. Ci-dessous, j'avais l'objet Abeille-281. Qui a disparu. Et l'objet Abeille-284 n'est pas là.

![image](https://user-images.githubusercontent.com/36518012/101359079-0da67b00-389c-11eb-8cbc-293bec8bee9b.png)

Ainsi que dans les objets aux sens Jeedom ? Ben non, ca c'est correct.
On voit que l'objet 284 est mentionné à la place de 281. Donc la vue seule est impactée. Pas de scénario à contrôler avec cette objet.
 
![image](https://user-images.githubusercontent.com/36518012/101359247-4ba39f00-389c-11eb-9a25-4e01a49af79c.png)

**Comment by mickadam29** [comment]
@KiwiHC16, @tcharp38 
Dans la version master_tcharp38, 2020-12-12 15:42:46 la mise à jour a bien été faite.

J'ai pris mon capteur de t° TS0201. Hors inclusion, je suis resté appuyé >5s donc l'objet est sorti et le symbole réseau a disparu sur l'afficheur. J'ai mis en inclusion. Inclus l'objet. Cette fois j'ai bien eu une mise à jour de l'objet. 
 Donc si qq1 a travaillé dessus, le bug a disparu, sinon cela se passe de façon aléatoire suivant l'équipement.

**Comment by tcharp38** [comment]
Pour info, concernant le sujet "eq reintegre vu comme nouvel eq", j'ai un correctif dans ma PR en attente (#1575)

**Comment by tcharp38** [comment]
Vu toutes les modifs faites ces derniers temps je pense que ce point est clos mais ne pas hesiter à reouvrir si besoin
