### ISSUE TITLE
Prise SONOFF BASICZBR3 : Fonctionne de façon classique. Anomalie : Dans un groupe (piloté par télécommande HUE), la commande ON fonctionne. Pas la OFF.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1505]

**Comment by KiwiHC16** [comment]
Suite à la réinstallation depuis le github, branche Master
Jeedom -> V 4.0.61
Zigate -> 3.1D
Abeille Github / Master -> master_tcharp38, 2020-12-02 15:16:06

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
@mickadam29, Si tu as une telecommande virtuelle dans Abeille et que tu pilotes ce groupe est ce que le On et le Off focntionne ?

**Comment by mickadam29** [comment]
@KiwiHC16 
Je vais tester ça et te faire un retour.

**Comment by mickadam29** [comment]
Test pertinent.
La télécommande virtuelle pilote parfaitement le commutateur SONOFF et les ampoules qui sont dans le groupe.
La télécommande HUE pilote parfaitement les ampoules (on, off, intensité) et la fonction ON du commutateur SONOFF.
Curieusement, il n'y a que la touche "0" de la télécommande qui reste sans effet sur la fonction OFF du commutateur
L'association Télécommande HUE/Contacteur SONOFF via le groupe semble mal implémentée mais Abeille et Zigate n'y peuvent rien. Les télécommandes adressent les groupes sans passer par le coordinateur, c'est bien cela ?
Si c'est bien le cas, je ferai un scénario pour envoyer le OFF à l'aide de la Zigate sur réception du bouton OFF de la télécommande.

**Comment by KiwiHC16** [comment]
"c'est bien cela ?"

Oui
