### ISSUE TITLE
Contactor 20AX Legrand : Pilotage sur ses fonctions ON/OFF mais la puissance et le mode ne sont pas remontés jusqu'au widget. Le datagramme de la puissance est bien reçu par zigate.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1506]

**Comment by KiwiHC16** [comment]
Suite à la réinstallation depuis le github, branche Master
Jeedom -> V 4.0.61
Zigate -> 3.1D
Abeille Github / Master -> master_tcharp38, 2020-12-02 15:16:06

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je crois me souvenir qu'il faut positionner la zigate en mode hybride à l'aide de la commande dans la page de configuration.

Peux tu essayer voir si cela résoud le soucis ?

![Capture d’écran 2020-12-07 à 10 57 58](https://user-images.githubusercontent.com/8549674/101336713-12a70280-387b-11eb-9694-b0444b2a6f08.png)

**Comment by KiwiHC16** [comment]
Mon contacteur est réinclus. Donc cela fonctionne mieux avec la version réinstallée depuis github.
Je peux gérer le contact, façon ON/OFF. Donc je vaispouvoir repiloter ma chaudière.

En revanche, il y a un bug. Je vois des commandes spécifiques qui reviennent de l'équipement sous la forme

message (Topic=Abeille1/1729/0B04-01-050B,payload=31488)
à qqs caractères de syntaxe près.

Donc, le contacteur renvoie à la zigate, la puissance consommée : 314,88 W
En revanche, rien dans le Widget, ni dans la commande "Puissance" de l'équipement.

**Comment by KiwiHC16** [comment]
Donc oublies le sujet hybride. Je vais tester sur le min pour voir.

**Comment by KiwiHC16** [comment]
Je viens de pousser dans le master une correction. Fonctionne sur le mien.

**Comment by mickadam29** [comment]
@KiwiHC16 

Je veux bien que tu m'indiques comment recevoir la mise à jour github.
En partant de ta doc, le git pull m'indique une erreur 

cd /var/www/html/plugins/Abeille
sudo git pull https://github.com/KiwiHC16/Abeille
fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git

**Comment by mickadam29** [comment]
J'ai appliqué la mise à jour.
La puissance remonte correctement. En revanche, le mode reste à 0. Et il me semble que tu avais ajouté une autre information que je n'ai pas sur le widget. Peut-être l'as tu retiré depuis.
J'irai voir l'issue sur lequel tu avais mis la copie écran du widget.

Il me semble que je t'avais posé la question concernant les mise à jour liées aux modèles json. Comme lorsque tu as ajouté le mode pour ce contacteur, tu as corrigé, entre autre, le modèle JSON. Est-ce que l'on doit faire qq chose pour que les modifs du modèle s'applique sur un objet existant ?

**Comment by mickadam29** [comment]
J'ai retrouvé. #1472 
Ta version
![image](https://user-images.githubusercontent.com/36518012/101348922-c1077380-388c-11eb-9a7a-93afc2f6c2ed.png)

Ma version
![image](https://user-images.githubusercontent.com/36518012/101348989-e09e9c00-388c-11eb-87c7-1738bd844f19.png)

**Comment by KiwiHC16** [comment]
"Il me semble que je t'avais posé la question concernant les mise à jour liées aux modèles json. Comme lorsque tu as ajouté le mode pour ce contacteur, tu as corrigé, entre autre, le modèle JSON. Est-ce que l'on doit faire qq chose pour que les modifs du modèle s'applique sur un objet existant ?"
Non pas a ce jour. Issue ouverte pour voir si on le fera un jour.

**Comment by KiwiHC16** [comment]
Pour l instant seule solution. Supprime l objet de re-inclus pour avoir le dernier modele.

**Comment by mickadam29** [comment]
Merci. Si la puissance est bien là, les autres infos ne remontent pas. Mais cela vient peut-être de la création de l'objet et de ses commandes. Je vais le réinclure.
J'espère que vous parviendrez à mettre à jour les équipements avec les ajouts dans les modèles. Ca me parait essentiel.
Car supprimer un objet cela revient à perdre son historique par exemple. Mais aussi revoir les scénarios ..... Mais ca tu le sais mieux que quiconque.

**Comment by KiwiHC16** [comment]
L etat manque car petit souci dans modele. Je viens de pousser un correctif.

**Comment by mickadam29** [comment]
Merci
