### ISSUE TITLE
Suggestion / Inclusion

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1507]
@KiwiHC16 @tcharp38 

Vous aviez évoqué la phase de création d'objet dans jeedom alors que la zigate n'était pas en phase d'inclusion, de mémoire.
Sur le même thème, ne pourrait-on pas sortir la zigate du mode inclusion lorsque la création de l'objet est terminée ? 
Cela pourrait éviter par exemple que des objet soient créés en même temps que celui que l'on est en train d'inclure, en réduisant la fenêtre d'inclusion au strict minimum.
Pour avoir inclus 43 objets en peu de temps, et être repassé sur certains, je pense que mettre en inclusion, inclure l'objet et quitter le mode inclusion est  bénéfique par rapport à mettre en inclusion, inclure plusieurs objets et quitter le mode inclusion ou le laisser se fermer au bout de 4 min.

**Comment by tcharp38** [comment]
Ha oui, c'est pas bete sauf que ca n'empeche personne de démarrer l'inclusion de plusieurs devices en meme temps et c'est la que ca coince. Je veux dire par la tu oublie de pas en inclure plusieurs à la fois, tu lances l inclusion Zigate, et tu fais un reset de 2 ou + capteurs par ex. Ca m'est arrivé.

Bref comme on ne peut pas controler les inclusions cette idée serait tres limitée.

**Comment by mickadam29** [comment]
@tcharp38 
Ma suggestion c'était de fermer l'inclusion lorsque l'objet est créé. C'est à dire que l'on se discipline à n'inclure qu'un seul objet à la fois. 
Dans certains cas, j'ai vu jusqu'à 3 min pour inclure un objet et des tempêtes de message. Mais ça ce n'est pas le cas normal.
Hier, lorsque j'ai tout réinstallé, les inclusions ne prenaient que très peu de temps. Inférieure à 1 min. Donc pendant 3 minutes, car ne sachant pas combien de temps il fallait pour être certain que l'objet soit totalement inclus, càd dire qu'il ait répondu à l'ensemble des clusters, je laissais les 4 minutes s'écouler. Et bien pendant ce temps, je prends le risque qu'un objet arrive à s'enregistrer. La difficulté que j'ai rencontré; c'était de déterminer quel était l'objet qui s'était inclus.  Par exemple capteur de temp, parmi une dizaine, lequel est-ce ? Donc c'était plus simple pour moi de supprimer l'objet et qu'il attende que je lui fasse l'inclusion pour arriver sur le réseau.
Ce n'est que mon expérience, mais sur 43 objets, j'ai dû en supprimer 6 ou 7 car ils s'étaient enregistrés pendant l'inclusion d'un objet pour lequel j'avais fait la demande (appui prolongé sur le bouton par exemple)
Ou alors, il faut supprimer la création automatique sur réception. Mais je crois que c'est lié au changement d'adresse courte. 
Car ces objets étaient déjà présents dans Zigate mais pas dans jeedom.  Donc pas véritablement une inclusion dans le réseau sans que l'on fasse la procédure d'inclusion. Je vais effacer une nouvelle fois la PDM, mais le comportement aurait certainement différent. Encore que dans ce cas, je n'aurai pas eu à réinclure mes objets mais les laisser se présenter à zigate.

**Comment by tcharp38** [comment]
Oui j'avais bien compris ta proposition mais comme tu dis ca impose que l utilisateur n'en fasse qu'un à la fois.
Ca demande quand meme un peu de boulot pour restreindre.
De mon cote je prefere bosser à améliorer la phase d'inclusion. Il y a beaucoup trop de messages qui rendre l'inclusion peu efficace mais ca fait déja partie des points ouverts il me semble.

En attendant un point important à signaler aux users, etre patient, et tenter l inclusion un par un.
J'imagine que @KiwiHC16  à un peu la meme vison.

**Comment by KiwiHC16** [comment]
On peut ajouter une option c est pas trop de code.
Mais je suis plus dans la ligne @tcharp38.

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

C'est vous les développeurs.
En même temps, j'espère pas devoir me retaper l'inclusion des tous mes équipements avant longtemps. Je garderai en tête l'idée de pas inclure plus d'un objet à la fois.

**Comment by tcharp38** [comment]
J'espere aussi et je comprends tout à fait ta frustration.
Il y a a des tas de trucs en cours pour rendre Abeille + robuste. Patiente...

**Comment by mickadam29** [comment]
@tcharp38 

Pas très grave. Je commence à comprendre pourquoi les changements évoqués ici ou là n'avaient aucune influence sur mon installation. Visiblement qq chose qui cloche depuis le market.
Tout semble être rentré dans l'ordre. Avec une installation uptodate. 3.1D et Version Github.
Prochaine étape, c'est l'installation d'une sirène Zigbee en extérieur à pls mètres de haut. Donc j'aimerais que tout soit stable pour la tester dans tous les sens avant d'aller l'accrocher. Ensuite, j'ai commander des modules de test zigbee pour développer mes propres modules. Comme par exemple une sonde de niveau bas de fuel. Et la commande de cette fameuse sirène. 2 Contacts secs commandés par Abeille. Ce que l'on trouve sur le marché ce sont des relais connectés à la phase. Donc il aurait fallu dessouder. Après si j'y arrive pas, commande du double relais Xiaomi, adaptation des relais pour isoler les contacts NO/NC

Bon courage à vous qui développez. Et encore merci pour le taf.

**Comment by mickadam29** [comment]
Solution non retenue
