### ISSUE TITLE
Timeout sur les objets Zigbee

### ISSUE THREAD

**Issue by cissemp** [KiwiHC16/Abeille#1509]
J’ai un bug sur le plugin Abeille depuis la nouvelle version : toutes les deux ou trois heures mes objets Zigbee ne sont plus joignables ils sont tous déconnectés.
Mais quand je relance le démon et je clique plusieurs fois par exemple sur le bouton on de mon ampoule, ça repart et je suis obligé de faire ça pour tous mes objets. Je n’avais pas ce bug avant.

Après relance du démon, tout fonctionne à nouveau. Mais le problème revient après quelques heures

![Abeille_Config](https://user-images.githubusercontent.com/72965923/101372753-83b2de00-38ac-11eb-810b-123477cd0dd4.png)

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/5653686/Abeille.log)

[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5653690/AbeilleSerialRead1.log)

[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5653692/AbeilleCmd.log)

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5653694/AbeilleParser.log)

<img width="909" alt="Abeille" src="https://user-images.githubusercontent.com/72965923/101372841-99c09e80-38ac-11eb-947f-45673e375085.png">

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Quel firmware sur la zigate ?

**Comment by cissemp** [comment]
Bonjour 
Je suis en 3.1d. Ce matin bizarrement, ça continue de fonctionner.

**Comment by KiwiHC16** [comment]
Si tu regardes dans la page santé as tu un équipement avec l adresse courte: 2835
(Bcp d'Annonce)

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 
Je n'ai aucun équipement avec l'adresse courte : 2835. Ce matin tout fonctionne, je te partage la santé des objets

<img width="912" alt="2020_12_08_10_20_49_Abeille_Jeedom" src="https://user-images.githubusercontent.com/72965923/101464769-5bc08a80-393f-11eb-846d-e73bde0f0872.png">

**Comment by shadsnob** [comment]
Bonjour, moi aussi j'ai le même souci je suis en zigate firmware 3.1d avec jeedom en v4.0.61 plugins Abeille stable version 2020-12-05 01:00:13. Le problème se fait sur un sonoff SNZB-04 je suis obligé de relancer avec le menu "network list" et sélectionner dans "Afficher réseau" qui se trouve dans "tables des nœuds" le bouton orange mais parfois cela marche pas et me dit "fichier vide rien à traiter". Et je n'ai pas d'adresse 2835 mais 7CD3 pour mon appareil

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5660033/Abeille.txt)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5660034/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5660038/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5660040/AbeilleSerialRead1.log)

**Comment by KiwiHC16** [comment]
Pouvez vous tester la beta ?

**Comment by shadsnob** [comment]
je me suis mis en bêta même problème

**Comment by cissemp** [comment]
Bonjour @KiwiHC16  @shadsnob 

Je ne sais pas si ça a un rapport ou pas mais je suis allé dans la partie Network list -> Table des noeuds et j'ai cliquer sur forcer la réinterrogation du réseau. Je l'ai fait hier soir et depuis je n'ai pas de coupure

**Comment by shadsnob** [comment]
ce bouton entourer en rouge me permet de refaire une synchro mais la ne marche plus je suis bloque

![1](https://user-images.githubusercontent.com/55192541/101520905-63a31d80-3985-11eb-8a55-2ee8ed3caf45.png)

**Comment by shadsnob** [comment]
dans Abeille j'ai ce message "L'objet 'Abeille1/Ruche' existe mais pas la cmde 'SystemMessage' => message ignoré"

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5660886/Abeille.txt)

**Comment by cissemp** [comment]
Bonjour @shadsnob 

Oui c'est bien le bouton que j'avais utilisé mais chez moi ce matin ça a recommencé. 
@KiwiHC16  ça serait pas plus judicieux de revenir sur la version précédente du plugin ?

**Comment by KiwiHC16** [comment]
On vient de trouvé un soucis pas cool sur la beta pour l instant je recommande la stable. On travaille sur le sujet.

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 

Des idées sur le bug ? J'ai le souci tous les jours

**Comment by KiwiHC16** [comment]
On a fait une nouvelle beta. Peux tu a tester ? (Elle tourne chez moi)

**Comment by shadsnob** [comment]
Moi j'ai télécharge la bêta toujours au mème point pas de graphique timeout alors que avant en 3.1c et version stable j'avais pas ce souci et maintenant jai ce message en haut a droite une icone triangle gris erreur javascript
![Sans titre](https://user-images.githubusercontent.com/55192541/102485456-f0299c00-4067-11eb-841b-25c77e91b1dd.png)

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 

Je viens d'installer la version beta. Pour l'instant ça tourne bien et je vais te dire si ça continue encore demain

**Comment by KiwiHC16** [comment]
La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
@shadsnob peux tu ouvrir une issue specifique pour ton soucis car c est different de la discussion en cours.

**Comment by cissemp** [comment]
Bonjour @KiwiHC16 

Le plugin beta fonctionne très bien, je n'ai plus de soucis

**Comment by KiwiHC16** [comment]
Super ! Bonne nouvelle !
