### ISSUE TITLE
Mise a jour des equipements sur la base des nouveaux modeles

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1511]

**Comment by KiwiHC16** [comment]
Tu utilises encore "syncconf.sh" ? Il va avec la modal "syncconf.abeille.php" appelée par "AbeilleClassTest.php"

**Comment by KiwiHC16** [comment]
Comparaison en place (je ne sais plus ou c est visible dans Abeille - a ete caché).

**Comment by tcharp38** [comment]
Depuis la 220324-BETA-1, les commandes infos existantes ne devraient plus changer d'ID avec une mise à jour, ne creant ainsi aucune commande info orpheline.

Ca n'est toujours pas le cas pour les cmds "action" qui n'ont pas de "logicalId" unique.

**Comment by tcharp38** [comment]
Je clos cet antique sujet.
Beaucoup de choses ont changé depuis et pas de details.
