### ISSUE TITLE
Espace disque insuffisant pour faire la mise à jour

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1512]
@KiwiHC16 

Pourrais-tu indiquer la taille nécessaire que tu juges utile ?
Car le Zip fait env 27 Mo, dézip 31 Mo et j'ai 91 Mo de dispo.
Je pense que d'autres que moi seront intéressés, quitte à changer la taille.
D'autant que cela semble faire planter les mises à jour sans que nous le sachions.

Bon taf en tous cas

![image](https://user-images.githubusercontent.com/36518012/101455722-4f363500-3933-11eb-93b3-d3428617cf1d.png)

**Comment by Tonio16** [comment]
Comment est définie l'espace dispo? Car je suis sur un SSD, donc avec plus qu'il ne faut de parce, et j'ai pourtant ce problème d'icônes absentes. 

Antoine

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je l ai defini de facon arbitraire a 100Mo dans un premier temps.

Je ne dis pas que c est la seule raison au soucis mais c est clairement une raison et il n'y a aucune alarme de Jeedom pour indiquer les soucis.

Jeedom utilise un repertoire tmp qui est normalement dans /tmp qui est une partition montée en memoire tmpfs.

Je vais essayer de reduire encore la taille d'Abeille pour limiter l occurance.

Il faudrait ouvrir un ticket Jeedom pour leur demander de traiter ce cas car il impacte potentiellement tous les plugins.

**Comment by mickadam29** [comment]
Pour ma part, je viens de la passer à 256M
Je verrai à l'usage. Mais @KiwiHC16 ne penses-tu qu'il faudrait un nouveau log dédié afin de tracer la mise à jour ?
Celui en place n'est pas bavard, en tous cas pas en mode debug.
Faut-il placer le mode en ERROR ?

![image](https://user-images.githubusercontent.com/36518012/101478514-173dea80-3951-11eb-986f-776152d83c6d.png)

**Comment by KiwiHC16** [comment]
Je ne peux rien faire car ce n est pas le plugin qui fait l update mais le core.

Il faut que je regarde si le core jeedom fait appelle a des fonctions du plugin, ce qui permettrai de faire des verifications mais pour l instant je ne sais pas.

**Comment by mickadam29** [comment]
Ok. Donc Jeedom télécharge le zip et se débrouille.
Je pensais que les développeurs, quelque soit le plugin, géraient le script de mise à jour de bout en bout.

**Comment by KiwiHC16** [comment]
Non, c est jeedom qui fait ca tambouille ...

**Comment by KiwiHC16** [comment]
```
[2020-12-08 23:37:25][ALERT] : [START UPDATE]
[2020-12-08 23:37:25][ALERT] : Début de la mise à jour de : Abeille [Kiwi:preInstallUpdate()]
[2020-12-08 23:37:25][ALERT] : Action de pré-update [Kiwi:preInstallUpdate()->$plugin->callInstallFunction('pre_update');]
[2020-12-08 23:37:25][ALERT] : | OK
[2020-12-08 23:37:25][ALERT] : Téléchargement du plugin
[2020-12-08 23:37:26][ALERT] : Téléchargement de Abeille
[2020-12-08 23:37:26][ALERT] : URL https://market.jeedom.com/core/php/downloadFile.php?id=3219&version=stable&jeedomversion=4.0.61&hwkey=52c9c688f6db6ad60d1399c5c9645cbd1c841d59a3a7658b37cae935b274d8c&username=kiwihc16&password=200e5cf503fbaae9dc3e0af530b68ce2e5a5ff29&password_type=sha1
--2020-12-08 23:37:26--  https://market.jeedom.com/core/php/downloadFile.php?id=3219&version=stable&jeedomversion=4.0.61&hwkey=52c9c688f6db6ad60d1399c5c9645cbd1c841d59a3a7658b37cae935b274d8c&username=kiwihc16&password=200e5cf503fbaae9dc3e0af530b68ce2e5a5ff29&password_type=sha1
Resolving market.jeedom.com (market.jeedom.com) 51.178.69.128
Connecting to market.jeedom.com (market.jeedom.com)|51.178.69.128|:443 connected.
HTTP request sent, awaiting response 200 | OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/jeedom/market/Abeille.zip'
0K      2.86M
50K      5.73M
...
26350K             98.5M=0.5s
2020-12-08 23:37:26 (53.9 MB/s) - '/tmp/jeedom/market/Abeille.zip' saved [27027150]
[2020-12-08 23:37:26][ALERT] : | OK
[2020-12-08 23:37:26][ALERT] : Décompression du zip
[2020-12-08 23:37:27][ALERT] : | OK
[2020-12-08 23:37:27][ALERT] : Post-installation de Abeille
[2020-12-08 23:37:27][ALERT] : Supression des fichiers inutiles
[2020-12-08 23:37:28][ALERT] : | OK
[2020-12-08 23:37:38][ALERT] : Launch cron dependancy plugins
[2020-12-08 23:37:38][ALERT] : [END UPDATE SUCCESS]
```

**Comment by KiwiHC16** [comment]
```
core/class/update.class.php:					log::add('update', 'alert', __('Action de pré-update...', __FILE__));
```

```
Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=Abeille function=pre_update callInstallFunction=1

jeePlugin.php
$plugin->callInstallFunction($function, true);
$plugin_id::$function();
```

**Comment by KiwiHC16** [comment]
J ai ajouté du code pour avoir des logs. Sera dispo dans les futures versions.
