### ISSUE TITLE
Plusieurs souci avec beta et firmware 3.1d

### ISSUE THREAD

**Issue by shadsnob** [KiwiHC16/Abeille#1527]
Bonjour, j'ai de nouveaux plusieurs problèmes en passant a la beta, 2020-12-08 10:34 ma zigate en firmware 3.1d ne vois plus mon sonoff snzb-04 et quand je fais dans network list un refresh pour afficher le réseau je vois plus rien et même âpres une réinstallation du plugin j'ai ce lmessage "ERREUR ! Qqch s'est mal passé. Le fichier 'AbeilleLQI_MapDataAbeille1.json' n'existe pas." et je met le log abeille merci @KiwiHC16 de m'aider
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5678707/Abeille.txt)

**Comment by tcharp38** [comment]
Salut
Tu es sur la derniere version stable ou sur une beta ?

Peux tu donner le log AbeilleParser apres ta tentative de refresh ? Je te suggere de le vider puis lancer le refresh.
On doit trouver des messages du type 804E.

D'ailleurs, il vaut mieux fournir le log complet via la page support, telecharger tout.

**Comment by shadsnob** [comment]
Je suis sur une beta la dernière que jeedom propose voila ce que contient apres vidage du fichier ce que vous avez demandez
`[2020-12-11 11:57:20][debug] Abeille1, Type=804E/Management LQI response, SQN=84, Status=C1, NeighbourTableEntries=00, NeighbourTableListCount=00, StartIndex=00, NWKAddr=0000, ExtPANId=00, ExtAddr=, Depth=0, LinkQuality=0, BitMapOfAttr=, SrcAddr=`

**Comment by tcharp38** [comment]
Et les lignes d'apres ?

**Comment by mickadam29** [comment]
@shadsnob, après la mise à jour, il est fortement conseillé d'effacer la PDM et de tout réinclure. C'est un retour d'expérience.

**Comment by shadsnob** [comment]
aucune autres je l'avais déjà fait de tout effacer

**Comment by tcharp38** [comment]
Ok, je vois deja que la reponse de la zigate est daubée. Elle dit ne connaitre "aucun" equipement (NeighbourTableListCount=00).
Donc pour elle aucune inclusion n'est faite.

J'ai eu la mauvaise experience aussi en 3.1d. Pour moi il y a des choses pas claires mais effectivement j'ai du effacer la PDM et refaire les inclusions. Depuis je suis resté en 3.1c.
Donc à garder en tete que le FW 3.1d (ou la migration vers 3.1d) comporte plusieurs doutes pour lesquels nous ne savons pas repondre aujourd hui malheureusement.

**Comment by KiwiHC16** [comment]
Essayons d'aider @shadsnob car je vois 2 sujets dans sa demande:
A - mon sonoff snzb-04
B - network list un refresh

A - J ai un sonoff snzb-04 sur mon bureau avec le master, le firmware 3.1d et fonctionne très bien pour indiquer l ouverture et fermeture de porte. Donc cette combinaison fonctionne.

B - "network list un refresh" il y a des soucis visiblement car on a une issue ouverte et on vient de faire un PR donc il faut qu on le teste plus avant d'investiguer sur ton systeme.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
A - Est ce que tu as l objet SonOff dans la liste des equipements dans Abeille ?

**Comment by KiwiHC16** [comment]
Par exemple sur mon systeme j 'ai :
![Capture d’écran 2020-12-11 à 14 31 46](https://user-images.githubusercontent.com/8549674/101909318-9b94a580-3bbd-11eb-9710-d268753e6cad.png)

**Comment by shadsnob** [comment]
J'ai tout repartie de zéro reset complet du plugin réinstalle du plugin bêta, 2020-12-08 10:34 donc j'ai aussi re associer
 le sonoff pour l'instant il est bien vu mais j’attends de voir sur 60 minutes si il repart en vadrouille. le refresh semble marcher pour l'instant mais j'attend comme pour l'ouverture de porte 

![10](https://user-images.githubusercontent.com/55192541/101913854-dac5f500-3bc3-11eb-853c-2a0abe68b178.jpg)
![20](https://user-images.githubusercontent.com/55192541/101913994-08ab3980-3bc4-11eb-87fb-1e164b018635.jpg)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5679619/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5679620/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5679623/AbeilleSerialRead1.log)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5679626/Abeille.txt)

**Comment by shadsnob** [comment]
Plusieurs options je trouve manque voir photos et meme n'est pas afficher la batterie dans "Analyse" "Equipements" "Batteries"
![4](https://user-images.githubusercontent.com/55192541/101921780-a8b99080-3bcd-11eb-8805-878f9dc5d1bd.png)

**Comment by KiwiHC16** [comment]
"j’attends de voir sur 60 minutes si il repart en vadrouille" qu est ce que cela veut dire ?
Si tu veux dire qu il passe en TimeOut c est normal car l integration n'est pas fini, mais cela ne l empeche pas de fonctionner.
Ouvres et fermes le porte et regardes si le widget Jeedom se met à jour.

**Comment by KiwiHC16** [comment]
SonOff SNZB-04 - Door Sensor #1325

**Comment by shadsnob** [comment]
Pour l'instrant il se met pas en timeout le bouton BindToPowerConfig correspond a quoi le bind qu'on doit effectuer pour avoir le niveau de batterie ?

**Comment by bouboun59** [comment]
pour les sonoff j ai fait aussi une remontée/retour experience sur les issue dediés du snzb-02 03 les niveaux de batterie ne remontent pas.

**Comment by KiwiHC16** [comment]
Il y a trop de sujets dans ce fil, je parviens pas a suivre. Je clos. Ouvres si besoin une cas precis et specifique par sujet.
