### ISSUE TITLE
Thermomètre TS0201 (report temperature périodicité)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1528]
@KiwiHC16

Pourrais-tu me dire s'il est possible, sur un équipement sur pile, de "poller" les infos. Je me sers de cette sonde pour l'automatisation de ma chaudière et il arrive qu'il se passe plus de 5H entre 2 valeurs. Pas cool pour contrôler la température et agir sur la commande de chauffe. Si j'appuie sur le bouton, la température est bien transmise à Abeille qui met à jour la table et l'historique. C'est l'envoi "spontané" qui cloche, voire qui n'existe pas.
Je pensais ouvrir un sujet spécifique mais je profite de celui de @Renobonus pour évoquer un éventuel changement dans le modèle ou les commandes.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
"Je pensais ouvrir un sujet spécifique mais je profite de celui de @Renobonus pour évoquer un éventuel changement dans le modèle ou les commandes."

Oui ouvre car je n'ai pas le temps de relire tout un historique de discussion surtout quand plusieurs sujets se melange. Je lis le tire, je regarde les deux derniers échanges.

**Comment by mickadam29** [comment]
Merci @KiwiHC16.

Je vais regarder cette histoire de setreport. Je connaissais pas. 
Merci de ton aide

**Comment by mickadam29** [comment]
J'avais un doute sur le fait que la commande existe ou pas.
La commande SetReport n'existe pas.
Peut-elle être ajouté dans le json sur la base d'un modèle qui en dispose, genre Xiaomi, puis je réinclus l'objet.

**Comment by mickadam29** [comment]
@KiwiHC16 

Pourrais-tu expliquer ce décalage ? Y a-t-il un bug quelque part ?
Comme je te le disais, j'étais étonné par la fréquence des relevés de t° de cette sonde.

Si je vais voir les équipements, la sonde est en timeout (depuis 4h27 alors qu'à priori à 7h32 elle a envoyé qq chose)
![image](https://user-images.githubusercontent.com/36518012/101978697-237abe00-3c57-11eb-8c8d-3936ef6f58dd.png)
![image](https://user-images.githubusercontent.com/36518012/101978723-4d33e500-3c57-11eb-8f07-e75f7a059b6a.png)

Sauf que si je lance la commande pour TIME-TIME, j'ai ceci comme retour. Je viens d'historiser. Comme ça je saurai finalement
à quelle fréquence la sonde envoie une valeur. Peut-être que si les écarts entre 2 relevés sont trop faibles, il n'y a pas d'envoi pour économiser la pile. Mais dans ce cas ,cette sonde ne va pas me servir. Et le plugin thermostat risque de mettre en défaillance la sonde.

![image](https://user-images.githubusercontent.com/36518012/101978761-ab60c800-3c57-11eb-98fa-6deb706fb39d.png)

Et cela vient de se confirmer par un message.
![image](https://user-images.githubusercontent.com/36518012/101978745-82403780-3c57-11eb-94c6-8fb6d972c8ca.png)

J'avais modifié les décimales pour une sonde Xiaomi, justement parce qu'au dixième, la fréquence de changement n'était pas suffisante, il me fallait plus de précision. Si l'un de vous à connaissance d'un modèle avec afficheur et dont la précision est le centième mais surtout avec une fréquence d'envoi de t° (setreport configurable et fonctionnel), je suis preneur de l'info. Sinon je démontrerai cette sonde pour y mettre une pulsation sur le bouton et une alimentation secteur.

**Comment by KiwiHC16** [comment]
Avant d aller plus avant j ai besoin de connaitre la referenc exact du produit. Que retourne la commande nom ?

**Comment by mickadam29** [comment]
Merci @KiwiHC16 

Le nom qui remonte est TS0201

Référence Amazon
https://www.amazon.fr/gp/product/B0882PDJT3/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

![image](https://user-images.githubusercontent.com/36518012/101982087-ebcd3f80-3c71-11eb-99e7-e49c89f8e54a.png)

**Comment by mickadam29** [comment]
@KiwiHC16 
Si tu as le temps de lire cet sur la communauté Jeedom. Sur les derniers messages, à partir du 30ème ,tu verras que le capteur, à la base, n'envoie pas assez de messages de relevés de Temp. Préservation des piles. Donc firmware à revoir.
Je ne sais pas si tous les modèles sont concernés : Tuya Ewelink, Blitzwolf. C'est dommage car l'afficheur était ma préférence. 
Pratique, mais pas adapté en l'état au pilotage du chauffage. 

https://community.jeedom.com/t/capteur-de-temperature-avec-affichage-fiable-zigbee-ou-zwave/29391

**Comment by mickadam29** [comment]
Sinon je peux me rabattre là-dessus, mais c'est beaucoup plus cher. Mais prévu pour envoyer une valeur toutes les 10 minutes

https://zigbeealliance.org/fr/zigbee_products/room-sensor-rs-23zbs/

**Comment by KiwiHC16** [comment]
Ok ce n est pas le meme que le cas #1525. Je change le titre.

**Comment by KiwiHC16** [comment]
Il est beau mais...

Il est vendu sous differentes versions visiblement.

Mon experience avec ce capteur est qu'il n'envoit pas souvent ses infos. 
Comme je n'ai pas investigué ce qu'on peut le forcé de faire il n'y a pas de setReport dans le modele.

La norme zigbee cherche a reduire la conso des piles et pour cela envoyer les messages le moins souvent possible.
La norme propose: 
- des parametres de temps: min et max. Le capteur devra envoyer au minimun toutes les min secondes et au maximum toutes les max secondes.
- parametres de variations: si la valeur de change pas de plus de x alors pas de message envoyé.

Le mien envoie sur variation de 0.7°C. Il peux se passer 10h pour avoir une variation de 0.7deg...

Il te permet de faire une régule en hysteresis et +-0.7deg.

Il faut que je regarde si il accepte d'etre configuré pour avoir d autres valeurs.

**Comment by mickadam29** [comment]
Titre plus approprié en effet. J'ai lu dans le descriptif qu'il existait 2 méthodes pour le relever de température. Si l'un pouvait être la fréquence, quelque soit l'écart de t°, ça m'irait bien. Mais j'ai constaté qu'en appuyant sur le bouton, non seulement l'envoi se faisait, mais il arrive parfois que la température change de près de +/- 1 voire 1.5 degrés. Donc, si la sonde ne fait pas elle même de relevés, impossible de recevoir la valeur.  Mais la fréquence côté Zigbee (via min/max) pourrait agir aussi sur le fait de provoquer un relevé de t°. Merci à toi

**Comment by tcharp38** [comment]
Antique sujet.
En ouvrir un nouveau précis si besoin.
