### ISSUE TITLE
Mise à jour du 5/12/2020

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1529]
Bonjour KiwiHC16 et merci pour la correction du bug #1442.   Je n'ai pas fait la mise à jour du 5/12/2020. Elle me fait un peu peur. Ma Zigate est toujours en 031a. Si j'applique cette mise à jour qui prend en charge le firmware zigate 3.1d alors que je suis en 031.a vais-je être obligé aussi de réinclure tous mes modules ? Est-il possible d'appliquer une mise à jour qui corrige ce bug de redirection sans être obligé de passer par la mise à jour du 24/11/2020. Suis-je obligé de passer ma Zigate en 3.1d ? Merci de tes réponses. Au fait, c'est quoi le mode hybride ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Kenderv** [comment]
Je te remercie de ta réponse. Toutefois tu ne m'as pas indiqué si, dans l'hypothèse où je fais la mise à jour du 05/12/2020 avec la version de zigate en 3.1d je vais être obligé de réinclure tous mes modules comme indiqué dans le changelog.  j'ai lu dans plusieurs posts que certains avaient eu des problèmes en changeant de version sur la zigate. Est-ce toujours vrai?
Merci et bon week-end

**Comment by KiwiHC16** [comment]
Duex sujets:
1) Mise a jour Abeille: rien a faire. 
2) Mise a jour Firmware ZIgate:
- Sans effacer EEPROM: rien a faire.
- En effaceant EEPROM: tout reinclure (rien n est perdu dans Abeille)

**Comment by KiwiHC16** [comment]
Clos.

**Comment by Kenderv** [comment]
Mise à jour effectuée ce soir, pas de soucis particuliers pour l'instant.  En revanche, après la mise à jour je suis allé dans la config d'Abeille et j'ai pu voir qu'il y avait été rajouté la possibilité de mise à jour du Firmware de la Zigate. Est-ce fonctionnel ? Pour ma part, étant en 03.1a il semble que je ne puisse upgrader qu'en 3.1c. Est-ce qu'une fois en 3.1c je pourrais aller en 3.1d et ainsi de suite ?
Merci encore une fois pour ton boulot et tous mes vœux pour de bonnes fêtes de fin d'année (horribilus comme disait Sa Majesté).

**Comment by tcharp38** [comment]
Salut @Kenderv . La mise à jour est supportée pour la PiZigate seulement.
Tu peux passer en 3.1c (backup avant comme toujours par prudence).
Si pas besoin de la 3.1d, je suggere de rester en 3.1c pour l'instant.
Bonnes fetes !
