### ISSUE TITLE
Recuperation systeme de l utilisateur @bocquetm

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1530]
@bocquetm

Mais du coup je ne comprends pas comment réinstaller sans rien perdre sachant que c'est mon installation de prod.
Si je fais un backup, que je désinstalle et réinstalle, j'ai plus mes objets et si je réimporte mon backup, il va me remettre l'ancien plugin qui avait été backupé, du coup c'est le serpent qui se mord la queue et je reviens au point de départ.

Sinon l'histoire du market, j'ai juste cliqué sur "Installer Stable" pour qu'il réécrase le plugin. Du moins j'ai tenté comme ça et ça semble réinstaller car il relance le daemon etc. D'ailleurs dans l'arbo du plugin, je vois bien que les fichiers ont été modifiés ce jour au moment de la réinstallation (Dec 11 14:45)

Par contre même comportement, pas la liste des images, refresh des noeuds qui marchent pas etc.

Comment faire pout tromper le market et qu'il le réinstalle ? Jeedom se base sur une sorte de manifest qu'il y a dans le plugin ?

Pour ce qui est de l'espace disque de la partition tmp jeedom, je pense que ce n'est pas lié.
tmpfs 256M 4.6M 252M 2% /tmp/jeedom

Et dans les logs d'update du plugin, je n'ai pas d'erreur quelconque:

+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependancy_abeille_in_progress
+ echo 'Début d'\''installation des dépendances'
Début d'installation des dépendances
+ '[' '!' -z /tmp/jeedom/Abeille/dependance ']'
+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependance
+ touch /tmp/jeedom/Abeille/dependance
+ echo 0
+ echo
+ echo 'Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement '
Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement
+ echo
+ echo 50
+ echo
+ echo 'Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.'
Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.
+ echo
+ echo '**Ajout du user www-data dans le groupe dialout (accès à la zigate)**'
**Ajout du user www-data dans le groupe dialout (accès à la zigate)**
++ groups www-data
++ grep -c dialout
+ [[ 1 -ne 1 ]]
+ echo 'OK, utilisateur www-data est déja dans le group dialout'
OK, utilisateur www-data est déja dans le group dialout
+ echo 100
+ echo
+ echo 'Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN'
Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN
+ echo
+ rm /tmp/jeedom/Abeille/dependance

**Comment by KiwiHC16** [comment]
@bocquetm

Je m'autoréponds. J'avais jamais remarqué qu'il y avait une option pour réinstaller les plugins dans le centre de maj... du coup je teste.

Edit: ça n'a pas marché. Toujours les mêmes problématiques.

**Comment by KiwiHC16** [comment]
@bocquetm

Pour info, j'ai fait un diff de directory entre la version stable du git et le répertoire du plugin. Les seuls fichiers qu'il y a en plus dans le répertoire du dépôt, c'est les ".gitttribute" etc. Tout le reste c'est des fichiers supplémentaires dans le répertoire d'installation du plugin.

J'ai également recherché des fichiers qui seraient vides et j'en ai pas (j'ai fait un diff avec les 2 résultats de commande de ce type ls -lR /var/www/html/plugins/Abeille/ | awk '{print $5" "$9 }' pour les 2 répertoires.

J'ai vérifié également les logs Jeedom de DL et d'update du plugin et il n'y a aucune erreur:

[2020-12-11 19:04:21][ALERT] : [START UPDATE]
[2020-12-11 19:04:21][ALERT] : Début de la mise à jour de : Abeille
[2020-12-11 19:04:21][ALERT] : Action de pré-update...
[2020-12-11 19:04:21][ALERT] : OK
[2020-12-11 19:04:21][ALERT] : Téléchargement du plugin...
[2020-12-11 19:04:22][ALERT] : Téléchargement de Abeille...
[2020-12-11 19:04:22][ALERT] : URL https://market.jeedom.com/core/php/downloadFile.php?id.....
Resolving market.jeedom.com (market.jeedom.com)... 51.210.253.116, 51.178.69.128
Connecting to market.jeedom.com (market.jeedom.com)|51.210.253.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/jeedom/market/Abeille.zip'
     0K .......... .......... .......... .......... .......... 3.00M
    50K .......... .......... .......... .......... .......... 7.08M
   100K .......... .......... .......... .......... .......... 7.41M
[...]
 26200K .......... .......... .......... .......... .......... 15.5M
 26250K .......... .......... .......... .......... .......... 14.3M
 26300K .......... .......... .......... .......... .......... 15.5M
 26350K .......... .......... .......... .......... ...        14.9M=1.9s

2020-12-11 19:04:24 (13.4 MB/s) - '/tmp/jeedom/market/Abeille.zip' saved [27027150]

[2020-12-11 19:04:24][ALERT] : OK
[2020-12-11 19:04:24][ALERT] : Décompression du zip...
[2020-12-11 19:04:26][ALERT] : OK
[2020-12-11 19:04:26][ALERT] : Post-installation de Abeille...
[2020-12-11 19:04:26][ALERT] : Supression des fichiers inutiles...
[2020-12-11 19:04:28][ALERT] : OK
[2020-12-11 19:04:28][ALERT] : Launch cron dependancy plugins
[2020-12-11 19:04:28][ALERT] : [END UPDATE SUCCESS]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Tres difficile pour moi de comprendre dans quelle situation est ton systeme.
Peux tu me donner version Jeedom, Version Abeille actuellement sur ton systeme, version Firmware ?

**Comment by bocquetm** [comment]
Bonjour @KiwiHC16 ,

Alors voici les détails :
- Debian Buster sur Pi4
- Jeedom 4.0.61
- Pizigate en v3.1d (màj sur celle ci car je croyais qu'avec la nouvelle version d'abeille il fallait ce firmware selon les notes dans le plugin)
- Abeille 2020-12-05 01:00:13

Sinon je n'avais pas de problèmes jusqu'à ce que je détecte qu'un capteur de température était en timeout. De là j'ai voulu regarder un peu les nœuds etc, et je me suis aperçu que plus rien ne marchait et que le refresh ne fonctionnait pas.
J'ai également voulu tester les autres nouvelles fonctionnalités (bruit etc), ça tourne en rond puis quand je refresh (comme c'est expliqué), je n'ai pas de graphique qui s'affiche.

Sinon mon capteur de température est tombé avant la mise à jour du plugin, donc rien à voir avec la maj du 5 décembre. Tout semble être fonctionnel hormis les problèmes d'affichage des nœuds etc (édit) et également des images et détection des capteurs. J'ai bien les mises à jour des capteurs et aucun timeout (hormis le petit souci avec le capteur cité).


Pour l'histoire des images :

![SmartSelect_20201212-130004_Chrome](https://user-images.githubusercontent.com/8374552/101983266-42d71280-3c7a-11eb-8e12-78eea18d0067.jpg)
--
![Screenshot_20201212-130116_Chrome](https://user-images.githubusercontent.com/8374552/101983276-53878880-3c7a-11eb-85cf-3856497fd49e.jpg)


Cdt,

Mickael

**Comment by Tonio16** [comment]
Cela rejoint cette issue: https://github.com/KiwiHC16/Abeille/issues/1486

J'ai le même souci avec les icones mais sinon c'est fonctionnel.

Antoine

**Comment by bocquetm** [comment]
Ce qui est étrange pour moi, c'est que le dossier master stable du GitHub, en comparaison avec mon dossier local téléchargé depuis le Market est similaire et je n'ai pas de fichiers à 0 octet. J'ai les mêmes fichiers des 2 côtés et n'ai juste que des fichiers en plus côté installation (sûrement des fichiers de configuration ou autre).
Pour ce faire, j'ai fait une comparaison de dossier avec diff et ensuite une comparaison de ls -lR (uniquement nom + taille via awk) avec diff également, donc logiquement c'est 
à peu près viable.

**Comment by KiwiHC16** [comment]
Je clos si probleme specifique ouvres une issue.

**Comment by bocquetm** [comment]
Ok j'ai recréé une issue avec les infos regroupées.
