### ISSUE TITLE
Pb template et cmdId non définis

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1532]
1er point: 
https://github.com/KiwiHC16/Abeille/blob/360938aee5bd45acae5804b4fa046bbe2a63cc24/core/class/Abeille.class.php#L1786

cette clé "template" n'est pas définie dans rucheCommand. il y a un indefined index de la même façon pour la ligne 1787.
 j'ai l'impression qu'un commit doit manquer sur ce fichier.

2éme point:
https://github.com/KiwiHC16/Abeille/blob/360938aee5bd45acae5804b4fa046bbe2a63cc24/core/class/Abeille.class.php#L1804

cmdId n'est pas défini

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
