### ISSUE TITLE
Ampoule Ledvance Classic E27 Tunable White inconnue sous Jeedom V4

### ISSUE THREAD

**Issue by ipod71** [KiwiHC16/Abeille#1533]
Hello je viens de recevoir 2 ampoules leddvance  Classic e27 tunable white. J’ai réussi l’inclusion avec la zigate mais l équipement n’est pas reconnu directement:
Pas de fonction dimmer
Pas de changement de la température de couleur
Aucun bouton sous jeedom. 

[supportPage.log](https://github.com/KiwiHC16/Abeille/files/5684976/supportPage.log)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Il faudrait que tu mettes le plugin en mode debug, que tu le redémarres, que tu supprimes l objet existant dans Jeedom qui correspond à l ampoule (s il existe) que tu fasses l inclusion et que tu partages le log AbeilleParser.

**Comment by ipod71** [comment]
Merci pour ton aide voila (il y a 2 ampoules du coup j'ai fait l'inclusion des 2 directement) : 
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5687504/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
Ampoule 1:

```
[2020-12-14 09:37:24][debug] Abeille1, Type=004d/Device announce, Addr=C1B0, ExtAddr=F0D1B8000013B2FC, MACCapa=8E, Rejoin=45, [Modelisation]
```
MACCapa=8E

```
[2020-12-14 09:37:24][debug] Abeille1, Type=8045/Active endpoints response, SQN=F4, Status=00, ShortAddr=C1B0, EndPointCount=02, EndPointList=; 01; F2, [Modelisation]
```
 EndPointList=; 01; F2

```
[2020-12-14 09:37:24][debug] Abeille1, Type=8102/Attribut report, SQN=7E, Addr=C1B0, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=0009, DataByteList=A60 TW Z3, [Modelisation]
```
A60 TW Z3

**Comment by KiwiHC16** [comment]
Ampoule 2:

```
[2020-12-14 09:37:53][debug] Abeille1, Type=8043/Simple descriptor response, SQN=FA, Status=00, Addr=CDA4, Length=1E, EP=01, Profile=0104/ZigBee Home Automation (ZHA), DevId=010C/Device 010C inconnu, BitField=01
[2020-12-14 09:37:53][debug]    [Modelisation] InClusterCount=0A
[2020-12-14 09:37:53][debug]    [Modelisation] OutClusterCount=00
```
Liste pas dispo. Je vais ouvrir une issue.

``
[2020-12-14 09:37:57][debug] Abeille1, Type=8102/Attribut report, SQN=AD, Addr=CDA4, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=0009, DataByteList=A60 TW Z3, [Modelisation]
```
A60 TW Z3

C est le meme type d ampoule ? Tu confirmes ?

**Comment by KiwiHC16** [comment]
https://zigbeealliance.org/zigbee_products/a60-tw-z3/
Color Temperature Light, Basic, Identify, Groups, Scenes, On/Off, Level, Color, Over the air

Interessant la photo porte la marque OSRAM qui semble etre maintenant LEDvance.

Et le EP est 01...

**Comment by KiwiHC16** [comment]
Le log n a pas tout décodé. J'ai besoin d une confirmation.
Est ce une ampoule spectre de blanc uniquement ?
Est une ampoule couleur ?

**Comment by ipod71** [comment]
dsl de t'avoir fait attendre:
Oui strictement les 2 memes ampoules.
Elles sont dimmables et elles permettent de passer de varier de 2700k et 6500k.
je te mets le lien de l'ampoule ca devrait t'aider (enfin je pense)
https://www.ledvance.fr/particuliers/produits/smart-home/produits-intelligents-avec-technologie-bluetooth/lampes-smart-home/lampe-de-forme-classique-avec-technologie-bluetooth/smart-classic-tunable-white/index.jsp

**Comment by KiwiHC16** [comment]
Modele fait et dans la version de dev. Sera dispo dans la prochaine stable.
Sinon récupères le fichier et mets le dans son repertoire:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/A60TWZ3

Tiens moi au courant.

**Comment by ipod71** [comment]
Je te remercie j'essai ca :)

**Comment by Brugal21** [comment]
Pourras-tu essayer, si ton ampoule fonctionne, de regarder l'info de la température de couleur du blanc (temperatureLight) si tu as une valeur qui remonte (en Kelvin normalement) ?

**Comment by Brugal21** [comment]
Je reinterviens dans la discussion. Kiwi a du partir du template des ampoules ikea qui varient elle de 2200 a 4000K. Il faudrait bricoler le template pour inclure une valeur à 6500K. Néanmoins, il y a quelques temps déjà, nous avions intégré avec kiwi les ampoules aqara qui varient de 2500 a 6500K aussi. Mais impossible de monter à 6500K, on avait alors trouvé que 5000 K était correct pour un blanc froid.
Tu peux peut-être modifier l'echelle de l'action setTemperatureLight et mettre min= 2500 et max = 6500 et faire varier le curseur sur la tuile de ton ampoule

**Comment by ipod71** [comment]
> Je reinterviens dans la discussion. Kiwi a du partir du template des ampoules ikea qui varient elle de 2200 a 4000K. Il faudrait bricoler le template pour inclure une valeur à 6500K. Néanmoins, il y a quelques temps déjà, nous avions intégré avec kiwi les ampoules aqara qui varient de 2500 a 6500K aussi. Mais impossible de monter à 6500K, on avait alors trouvé que 5000 K était correct pour un blanc froid.
> Tu peux peut-être modifier l'echelle de l'action setTemperatureLight et mettre min= 2500 et max = 6500 et faire varier le curseur sur la tuile de ton ampoule

Hello, malheureusement c'est une opération que je ne sais pas faire.

**Comment by ipod71** [comment]
Apres 1 journée de test 
toggle ok
set level ok
Juste le probleme de température est present (perso je n'ai pas les connaissances pour faire la modif et pas envie de faire de betises) valeur actuelles 2200 a 4000k, contre valeur 2700k a 6500k.

merci

**Comment by Brugal21** [comment]
Salut,

tu peux essayer avec ces fichiers là :

[
[A60TWZ3.zip](https://github.com/KiwiHC16/Abeille/files/5698794/A60TWZ3.zip)
](url)

Depuis Jeedom avec le plugin jeexplorer, tu remplaces le fichier A60TWZ3.json dans plugins/
Abeille/core/config/devices/A60TWZ3/
Et tu copies tous les autres fichiers dans plugins/
Abeille/core/config/devices/Template/

Ensuite tu supprimes et tu réinclus ton ampoule.

**Comment by ipod71** [comment]
merci j'essai :)

**Comment by ipod71** [comment]
du coup 
les bouton 2700k et 4000k sont fonctionnels (un doute sur le 4000 ca me parait bien blanc).
Le 6500 ne fonctionne pas aucune réaction
l'info "temperature light" reste à 0K qq soit le mode 
le curseur Settemperature light ne fonctionne pas .
Bouton on off > ok 
setlevel > ok
etat > ok

**Comment by KiwiHC16** [comment]
Récupères les fichiers et mets les dans leur repertoire:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/A60TWZ3
et dans
https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/Template/
getColorTemperature.json
temperatureLightV2.json 

Supprimes l ampoule dans Abeille, refais l inclusion et fais un getColorTemperature pour voir si tu recuperes l info.

Tiens moi au courant.

**Comment by ipod71** [comment]
Bonjour,

j'ai du faire une fausse manipulation j'ai des messages d'erreurs (log en pj)

J'ai du creer les json getColorTemperature.json et temperatureLightV2.json






[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5711150/Abeille.txt)

**Comment by ipod71** [comment]
Hello, une ame charitable pour m'aider ? please :'(

**Comment by ipod71** [comment]
Kiwi ? un coup de main stp :)

**Comment by KiwiHC16** [comment]
Pas trop dispo en ce moment. Probablement mi janvier...

**Comment by ipod71** [comment]
> Pas trop dispo en ce moment. Probablement mi janvier...

Pas de souci , bonnes fetes de fin d'année

**Comment by ipod71** [comment]
Hello, bonne année, as tu un peu plus de bande passante ou une date de la prochaine master ?
merci

**Comment by ipod71** [comment]
Hello, je voulais te remercier, la dernier master à parfaitement tout intégrée. Au top :)

**Comment by ipod71** [comment]
parfaitement résolu
