### ISSUE TITLE
Pas d alerte si le port serie est vide.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1534]
![Capture d’écran 2020-12-14 à 10 46 08](https://user-images.githubusercontent.com/8549674/102066234-ddaa2b00-3df9-11eb-900a-82e87e6d6d06.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Si le port serie est vide pas d'alerte.
Si la ruche a ete supprimée, elle ne se crée pas.
Status du plugin vert: Ok.

**Comment by KiwiHC16** [comment]
Pourquoi la fonction 
```
 public static function checkParameters()
```
est commentée ?

**Comment by tcharp38** [comment]
Il est possible que ca soit moi qui l'ai fait. Elle n'etait utilisée nul part.

**Comment by KiwiHC16** [comment]
Alors il faut la remettre et l affiner. Des candidats ?

**Comment by tcharp38** [comment]
Tu en attends quoi de cette fonction ?

**Comment by KiwiHC16** [comment]
Que les parametres fournis pas l utilisateurs soient valides. 
Pas de champ vide, pas de zigate activé si port pas defini,...

**Comment by tcharp38** [comment]
Ok donc c'est une fonction pour la page de config.
Assigne le moi si tu veux.

**Comment by KiwiHC16** [comment]
Oui c est ca. Ok.

**Comment by tcharp38** [comment]
Bon jusque la c'est super compliqué voir pas forcement jouable.
La raison est qu'on n'a pas le controle du bouton "sauvegarde". C'est Jeedom qui gere et il ne propose pas d'appel à une callback "pre save" javascript.
Je continue de creuser.

**Comment by KiwiHC16** [comment]
Te prends pas la tete. 
Fais le dans les verifications avant le lancement du daemon, refuse le lancement si un probleme: log + message.
Ou ajoutes un bouton "Vérifier la configuration"

**Comment by tcharp38** [comment]
J'ai mis une alerte mais la zigate est aussi désactivée.

De + si WIFI, je check aussi que l'adresse Wifi est entrée.
Pour ca j'ai du virer l'affectation par defaut à 192.168.0.1.
