### ISSUE TITLE
thermomètre zigbee ewelink : retour batterie

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1535]
Suite de #1525

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
```
FNB54-THM17ML1.1
```

**Comment by tcharp38** [comment]
Antique sujet.
Je clos mais à réouvrir si besoin de retravailler dessus et + d'infos.
