### ISSUE TITLE
Perte des icônes et types de capteurs

### ISSUE THREAD

**Issue by bocquetm** [KiwiHC16/Abeille#1536]
Bonjour,

à la demande de @KiwiHC16 , je recrée un ticket pour la perte des icônes et des types du capteur.
Je remets le troublehoot déjà effectué.

---

J'ai remarqué que je n'ai plus les images des capteurs... du coup quand j'édite un capteur, il me mets l'image par défaut qui est une abeille... ça renvoie vers "/plugins/Abeille/images/node_null.png" et la liste des icones est vide. Un peu comme s'il ne savait plus ce que c'était comme capteur...

Pour ce qui est de l'espace disque de la partition tmp jeedom, je pense que ce n'est pas lié.
tmpfs 256M 4.6M 252M 2% /tmp/jeedom

Et dans les logs d'update du plugin, je n'ai pas d'erreur quelconque:

```
PROGRESS_FILE=/tmp/jeedom/Abeille/dependancy_abeille_in_progress
echo 'Début d'''installation des dépendances'
Début d'installation des dépendances
'[' '!' -z /tmp/jeedom/Abeille/dependance ']'
PROGRESS_FILE=/tmp/jeedom/Abeille/dependance
touch /tmp/jeedom/Abeille/dependance
echo 0
echo
echo 'Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement '
Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement
echo
echo 50
echo
echo 'Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.'
Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.
echo
echo 'Ajout du user www-data dans le groupe dialout (accès à la zigate)'
Ajout du user www-data dans le groupe dialout (accès à la zigate)
++ groups www-data
++ grep -c dialout
[[ 1 -ne 1 ]]
echo 'OK, utilisateur www-data est déja dans le group dialout'
OK, utilisateur www-data est déja dans le group dialout
echo 100
echo
echo 'Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN'
Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN
echo
rm /tmp/jeedom/Abeille/dependance
```

j'ai fait un diff de directory entre la version stable du git et le répertoire du plugin. Les seuls fichiers qu'il y a en plus dans le répertoire du dépôt, c'est les ".gitttribute" etc. Tout le reste c'est des fichiers supplémentaires dans le répertoire d'installation du plugin.

J'ai également recherché des fichiers qui seraient vides et j'en ai pas (j'ai fait un diff avec les 2 résultats de commande de ce type `ls -lR /var/www/html/plugins/Abeille/ | awk '{print $5" "$9 }'` pour les 2 répertoires.

J'ai vérifié également les logs Jeedom de DL et d'update du plugin et il n'y a aucune erreur:

```
[2020-12-11 19:04:21][ALERT] : [START UPDATE]
[2020-12-11 19:04:21][ALERT] : Début de la mise à jour de : Abeille
[2020-12-11 19:04:21][ALERT] : Action de pré-update...
[2020-12-11 19:04:21][ALERT] : OK
[2020-12-11 19:04:21][ALERT] : Téléchargement du plugin...
[2020-12-11 19:04:22][ALERT] : Téléchargement de Abeille...
[2020-12-11 19:04:22][ALERT] : URL https://market.jeedom.com/core/php/downloadFile.php?id.....
Resolving market.jeedom.com (market.jeedom.com)... 51.210.253.116, 51.178.69.128
Connecting to market.jeedom.com (market.jeedom.com)|51.210.253.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/jeedom/market/Abeille.zip'
0K .......... .......... .......... .......... .......... 3.00M
50K .......... .......... .......... .......... .......... 7.08M
100K .......... .......... .......... .......... .......... 7.41M
[...]
26200K .......... .......... .......... .......... .......... 15.5M
26250K .......... .......... .......... .......... .......... 14.3M
26300K .......... .......... .......... .......... .......... 15.5M
26350K .......... .......... .......... .......... ... 14.9M=1.9s

2020-12-11 19:04:24 (13.4 MB/s) - '/tmp/jeedom/market/Abeille.zip' saved [27027150]

[2020-12-11 19:04:24][ALERT] : OK
[2020-12-11 19:04:24][ALERT] : Décompression du zip...
[2020-12-11 19:04:26][ALERT] : OK
[2020-12-11 19:04:26][ALERT] : Post-installation de Abeille...
[2020-12-11 19:04:26][ALERT] : Supression des fichiers inutiles...
[2020-12-11 19:04:28][ALERT] : OK
[2020-12-11 19:04:28][ALERT] : Launch cron dependancy plugins
[2020-12-11 19:04:28][ALERT] : [END UPDATE SUCCESS]
```

Voici visuellement ce que j'ai:

![image](https://user-images.githubusercontent.com/8374552/102077528-bfe4c200-3e09-11eb-9e7d-a92e26c74d9f.png)

![image](https://user-images.githubusercontent.com/8374552/102077543-c6733980-3e09-11eb-839e-bdcb6e7b65fa.png)

Ce qui est étrange pour moi par rapport au bug de la maj qui met des fichiers vide ou ne copie pas tout, c'est que le dossier master stable du GitHub, en comparaison avec mon dossier local téléchargé depuis le Market est similaire et je n'ai pas de fichiers à 0 octet. J'ai les mêmes fichiers des 2 côtés et n'ai juste que des fichiers en plus côté installation (sûrement des fichiers de configuration ou autre).

Voici les détails sur l'installation :

Debian Buster sur Pi4
Jeedom 4.0.61
Pizigate en v3.1d (màj sur celle ci car je croyais qu'avec la nouvelle version d'abeille il fallait ce firmware selon les notes dans le plugin)
Abeille 2020-12-05 01:00:13

Cdt,

Mickael

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Comme tu sembles plutot avisé, peux tu en ssh faire les commandes suivantes et partager le résultat (C est le code qui génère la liste):

```
cd /var/www/html/plugins/Abeille/desktop/php
php -a
require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';
$items = AbeilleTools::getDeviceNameFromJson('Abeille');

$selectBox = array();
foreach ($items as $item) {
  $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
  $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
  $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
  $selectBox[ucwords($name)] = $icone;
}
ksort($selectBox);
foreach ($selectBox as $key => $value) {
  echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
}
```

**Comment by bocquetm** [comment]
Voici les résultats:

```
php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';
  $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
  $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
  $selectBox[ucwords($name)] = $icone;
}
ksort($selectBox);
PHP Warning:  require_once(./../../resources/AbeilleDeamon/lib/AbeilleTools.php): failed to open stream: No such file or directory in php shell code on line 1
PHP Fatal error:  require_once(): **Failed opening required './../../resources/AbeilleDeamon/lib/AbeilleTools.php**' (include_path='.:/usr/share/php') in php shell code on line 1
php > $items = AbeilleTools::getDeviceNameFromJson('Abeille');
PHP Warning:  Uncaught Error: Class 'AbeilleTools' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
php >
php > $selectBox = array();
php > foreach ($items as $item) {
php {   $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
php {   $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
php {   $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
php {   $selectBox[ucwords($name)] = $icone;
php { }
PHP Notice:  Undefined variable: items in php shell code on line 1
PHP Warning:  Invalid argument supplied for foreach() in php shell code on line 1
php > ksort($selectBox);
php > foreach ($selectBox as $key => $value) {
php {   echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
php { }
php >

```
En fait il n'y a pas AbeilleTools.php dans le dossier mais Tools.php tout court.

```
root@pijeedom:/var/www/html/plugins/Abeille/desktop/php# ls -l ./../../resources/AbeilleDeamon/lib
total 12
-rwxrwxr-x 1 www-data www-data 10580 Dec 11 19:04 Tools.php
```

**Comment by bocquetm** [comment]
Pour info @KiwiHC16 , il n'y a pas non plus la lib dans le package stable du github que j'ai décompressé pour faire mes compare. 

```
# ls /tmp/tempabeille/Abeille-stable/resources/AbeilleDeamon/lib/
Tools.php
```

Ma source dont je fais le compare:  https://github.com/KiwiHC16/Abeille/archive/stable.zip 


Après je me suis dit que c'était peut être une erreur, alors j'ai tenté en mettant le required de Tools et non pas de AbeilleTools:

```
php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/Tools.php';
php > $items = AbeilleTools::getDeviceNameFromJson('Abeille');

$selectBox = array();
foreach ($items as $item) {
  $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
  $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
  $iconePHP Warning:  Uncaught Error: Class 'log' not found in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php:245
Stack trace:
#0 php shell code(1): AbeilleTools::getDeviceNameFromJson('Abeille')
#1 {main}
  thrown in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 245
 = $AbeilleObjetDefinition[$item]['configuration']['icone'];
  $selectBox[ucwords($name)] = $icone;
}
php >
ksort($selectBox);
foreach ($selectBox as $key => $value) {
  echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
}php > $selectBox = array();
php > foreach ($items as $item) {
php {   $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
php {   $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
php {   $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
php {   $selectBox[ucwords($name)] = $icone;
php { }
PHP Notice:  Undefined variable: items in php shell code on line 1
PHP Warning:  Invalid argument supplied for foreach() in php shell code on line 1
php > ksort($selectBox);
php > foreach ($selectBox as $key => $value) {
php {   echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
php { }
php >
```

**Comment by KiwiHC16** [comment]
Stable:
https://github.com/KiwiHC16/Abeille/tree/stable/resources/AbeilleDeamon/lib
il n y a que Tools.php
C est en ligne avec ton systeme.

Mais alors pourquoi sur mon systeme je ne vois pas ce soucis ....

**Comment by KiwiHC16** [comment]
J'ai du te donner le code de dev.
Peux tu essayer avec:
```
cd /var/www/html/plugins/Abeille/desktop/php
php -a
           require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/Tools.php';
                    $items = AbeilleTools::getDeviceNameFromJson('Abeille');

                    $selectBox = array();
                    foreach ($items as $item) {
                        $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
                        $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
                        $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
                        $selectBox[ucwords($name)] = $icone;
                    }
                    ksort($selectBox);
                    foreach ($selectBox as $key => $value) {
                        echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
                    }
```

**Comment by bocquetm** [comment]
Voici le résultat:

```
php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/Tools.php';
php >                     $items = AbeilleTools::getDeviceNameFromJson('Abeille');
PHP Warning:  Uncaught Error: Class 'log' not found in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php:245
Stack trace:
#0 php shell code(1): AbeilleTools::getDeviceNameFromJson('Abeille')
#1 {main}
  thrown in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 245
php >
php >                     $selectBox = array();
php >                     foreach ($items as $item) {
php {                         $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
php {                         $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
php {                         $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
php {                         $selectBox[ucwords($name)] = $icone;
php {                     }
PHP Notice:  Undefined variable: items in php shell code on line 1
PHP Warning:  Invalid argument supplied for foreach() in php shell code on line 1
php >                     ksort($selectBox);
php >                     foreach ($selectBox as $key => $value) {
php {                         echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
php {                     }
php >
```

**Comment by KiwiHC16** [comment]
peux tu modifier le fichier /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php
en ligne 245
et mettre // devant la ligne et refaire le test ?

**Comment by bocquetm** [comment]
Mieux :)

Mais j'ai qu'un seul result.

```
php >  require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/Tools.php';
                        echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
                    }php >                     $items = AbeilleTools::getDeviceNameFromJson('Abeille');
php >
php >                     $selectBox = array();
php >                     foreach ($items as $item) {
php {                         $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
php {                         $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
php {                         $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
php {                         $selectBox[ucwords($name)] = $icone;
php {                     }
php >                     ksort($selectBox);
php >                     foreach ($selectBox as $key => $value) {
php {                         echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
php {                     }
                     <option value="RF263">{{Ampoule Innr Edison RF263 Vintage E27}}</option>
php >

```

**Comment by KiwiHC16** [comment]
J arretes ici. Il y a eu enormement de modifications sur cette partie. Je vais me focaliser sur la sortie d un beta puis d une stable en on verra si tu as toujours le soucis.

**Comment by bocquetm** [comment]
Ok pas de soucis. Après si tu veux que je teste des choses pour être sûr que ce soit corrigé dans la prochaine release, n'hésite pas à me dire.

**Comment by KiwiHC16** [comment]
Une nouvelle beta doit etre sur le market si tu veux essayer.

**Comment by bocquetm** [comment]
Je viens de tester le passage dans la beta (2020-12-14 17:50:15).

C'est pas mieux ni pour les problématiques de refresh de LQI ou encore les icônes.

J'ai maintenant ce message: ERREUR ! Qqch s'est mal passé. Le fichier 'AbeilleLQI_MapDataAbeille1.json' n'existe pas.

**Comment by tcharp38** [comment]
Tu peux lancer un refresh manuel ?

**Comment by KiwiHC16** [comment]
STOP le sujet est "Perte Icones..."

Est ce que tu as la liste des icones ?

**Comment by bocquetm** [comment]
@tcharp38 , cad ?

J'utilise le petit bouton orange pour refresh 

![image](https://user-images.githubusercontent.com/8374552/102112349-db66c180-3e37-11eb-955a-16d577a54e1c.png)

**Comment by tcharp38** [comment]
Yes

**Comment by bocquetm** [comment]
@KiwiHC16 
Non toujours pas
![image](https://user-images.githubusercontent.com/8374552/102112449-03562500-3e38-11eb-81a6-e33ca7805110.png)

**Comment by tcharp38** [comment]
Oops. sorry. Kiwi a raison. On melange pas les sujets.

**Comment by bocquetm** [comment]
@KiwiHC16 

Nouveau résultat avec ton code PHP initiale: 

```
php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';
  $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
  $selectBox[ucwords($name)] = $icone;
}
ksort($selectBox);
foreach ($selectBox as $key => $value) {
  echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
}php > $items = AbeilleTools::getDeviceNameFromJson('Abeille');
php >
php > $selectBox = array();
php > foreach ($items as $item) {
php {   $AbeilleObjetDefinition = AbeilleTools::getJSonConfigFilebyDevices(AbeilleTools::getTrimmedValueForJsonFiles($item), 'Abeille');
php {   $name = $AbeilleObjetDefinition[$item]['nameJeedom'];
php {   $icone = $AbeilleObjetDefinition[$item]['configuration']['icone'];
php {   $selectBox[ucwords($name)] = $icone;
php { }
php > ksort($selectBox);
php > foreach ($selectBox as $key => $value) {
php {   echo "                     <option value=\"" . $value . "\">{{" . $key . "}}</option>\n";
php { }
                     <option value="RF263">{{Ampoule Innr Edison RF263 Vintage E27}}</option>
php >
```

Il n'y a plus les erreurs de logger mais par contre toujours qu'un seul result.

**Comment by bocquetm** [comment]
Je ne sais pas si c'est lié, mais quand je regarde l'onglet modèles et notamment mon capteur que j'ai dû réinitialiser (valeurs Jeedom vides), il est noté comme cela:

![image](https://user-images.githubusercontent.com/8374552/102121085-b24c2e00-3e43-11eb-88e4-bc1426aae776.png)

Sur un capteur qui n'a pas été modifié et qui garde son affichage et son type:

![image](https://user-images.githubusercontent.com/8374552/102121557-71a0e480-3e44-11eb-84a8-254ef08e1c17.png)

**Comment by KiwiHC16** [comment]
Peux tu faire:

```
cd /var/www/html/plugins/Abeille/desktop/php
php -a
require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';
$items = AbeilleTools::getDeviceNameFromJson('Abeille');
var_dump($items);
```

Et partager le resultat.
Sur la version beta.

**Comment by bocquetm** [comment]
Voilà le résultat

```
php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';

php > $items = AbeilleTools::getDeviceNameFromJson('Abeille');
php > var_dump($items);
array(1) {
  [0]=>
  string(5) "RF263"
}
php >
```

**Comment by KiwiHC16** [comment]
Une seule ligne alors que tu devrais alors plusieurs dizaine. On se rapproche.
Je regardes et te propose un autre test.

**Comment by bocquetm** [comment]
Yes, n'hésite pas :)

**Comment by KiwiHC16** [comment]
J ai revue la fonction.
Peux tu tester avec le master ?

**Comment by bocquetm** [comment]
Mon installation est via le Market (j'ai qu'une prod), il faudrait que tu pousses une nouvelle bêta dessus. Comme ça en même temps je peux valider toutes les autres modifications et confirmer si c'est corrigé ou non.

**Comment by KiwiHC16** [comment]
Il doit y avoir une nouvelle beta si tu peux tester.

**Comment by bocquetm** [comment]
Je viens de l'installer. La problématique est toujours présente je n'ai que le rf263.

Par contre tous les autres bugs sont bien corrigés. Je n'ai plus d'erreur.

**Comment by KiwiHC16** [comment]
Il faudrait que je me connecte sur ton systeme. Pourrais tu partager ton ecran avec Anydesk.com (ouvrir 2 ssh et un web browser on jeedom) ?

**Comment by bocquetm** [comment]
Désolé, je ne souhaite pas faire de remote access. Je peux vous aider à debug, faire des tests de codes etc, mais sans remote.

**Comment by bocquetm** [comment]
Après debug et décodage du code, je pense avoir trouvé l'erreur.

Après avoir fait un bout de code, je retrouvais la même problématique que dans l'interface:

```
root@pijeedom:/var/www/html/plugins/Abeille/desktop/php# php test-mick.php
string(5) "RF263"
Fichier introuvable: ../../core/config/devices/Timer/Timer.json
```

Ce qui correspond exactement au log que j'avais en warning dans mes logs
`[2020-12-11 12:04:39][WARNING] : Fichier introuvable: Timer.json
`

Selon la fonction dans la librairie:

```
public static function getDeviceNameFromJson($logger = 'Abeille')
    {
        $return = array();
        $devicesDir = self::devicesDir;
        if (file_exists($devicesDir) == FALSE) {
            log::add('Abeille', 'error', "Problème d'installation. Le chemin '...core/config/devices' n'existe pas.");
            return $return;
        }

        $dh = opendir($devicesDir);
        while (($dirEntry = readdir($dh)) !== false) {
         
            if ( in_array($dirEntry, array(".", "..", "listeCompatibilite.php", "Template") ) ) 
                continue;

            $fullPath = $devicesDir . $dirEntry . DIRECTORY_SEPARATOR . $dirEntry . ".json";
            if (!file_exists($fullPath)) {
                log::add($logger, 'warning', "Fichier introuvable: " . $file);
                return $return;
            }

            try {
                $return[] = array_keys(json_decode(file_get_contents($fullPath),1))[0];
            } catch (Exception $e) {
                log::add($logger, 'error', 'Impossible de lire le contenu du fichier ' . $file);
            }
        }

        return $return;
    }
```

On voit quand tu passes sur tous les directory via le while que tu sors de la boucle si jamais un fichier n'existe pas alors qu'il faudrait dans la logique juste passer et donc ne pas faire de return.

En remplacant le return juste par un "continue" afin de passer au prochain fichier, la fonction est ok:

```
root@pijeedom:/var/www/html/plugins/Abeille/desktop/php# php -a
Interactive mode enabled

php > require_once dirname(__FILE__) . '/../../resources/AbeilleDeamon/lib/AbeilleTools.php';
php >                     $items = AbeilleTools::getDeviceNameFromJson('Abeille');
php > var_dump($items);
array(190) {
  [0]=>
  string(5) "RF263"
  [1]=>
  string(20) "TRADFRIcontroloutlet"
  [2]=>
  string(6) "RWL021"
  [3]=>
  string(12) "sensor_86sw1"
  [4]=>
  string(11) "PAR16RGBWZ3"
  [5]=>
  string(26) "FYRTURblock-outrollerblind"
  [6]=>
  string(5) "SM309"
  [7]=>
  string(17) "ZLO-DimmableLight"
  [8]=>
  string(6) "TS0041"
  [9]=>
  string(6) "RB175W"
  [10]=>
  string(6) "LLC011"
  [11]=>
  string(6) "LWA001"
  [12]=>
  string(8) "GL-C-007"
  [13]=>
  string(17) "SmokeSensor-N-3.0"
  [14]=>
  string(6) "LST002"
  [15]=>
  string(12) "ctrl_ln1.aq1"
  [16]=>
  string(25) "TRADFRIbulbE27WSopal980lm"
  [17]=>
  string(12) "sensor_86sw2"
```

Et la page fonctionne:

![image](https://user-images.githubusercontent.com/8374552/102267739-a2534d80-3f1a-11eb-9fad-464c30a0f4af.png)



Pour résumer, il faut juste modifier la fonction getDeviceNameFromJson par :  

 ```
  public static function getDeviceNameFromJson($logger = 'Abeille')
    {
        $return = array();
        $devicesDir = self::devicesDir;
        if (file_exists($devicesDir) == FALSE) {
            log::add('Abeille', 'error', "Problème d'installation. Le chemin '...core/config/devices' n'existe pas.");
            return $return;
        }

        $dh = opendir($devicesDir);
        while (($dirEntry = readdir($dh)) !== false) {

            if ( in_array($dirEntry, array(".", "..", "listeCompatibilite.php", "Template") ) )
                continue;

            $fullPath = $devicesDir . $dirEntry . DIRECTORY_SEPARATOR . $dirEntry . ".json";
            if (!file_exists($fullPath)) {
                log::add($logger, 'warning', "Fichier introuvable: " . $file);
                //return $return;
                continue;
            }

            try {
                $return[] = array_keys(json_decode(file_get_contents($fullPath),1))[0];
            } catch (Exception $e) {
                log::add($logger, 'error', 'Impossible de lire le contenu du fichier ' . $file);
            }
        }

        return $return;
    }
```

**Comment by bocquetm** [comment]
Sinon pour info, j'ai 3 dossiers qui n'existent plus et donc qui ont fait que ça plantait:
Fichier introuvable: ../../core/config/devices/Timer/Timer.json
Fichier introuvable: ../../core/config/devices/TRADFRISignalRepeater/TRADFRISignalRepeater.json
Fichier introuvable: ../../core/config/devices/LOM02/LOM02.json

Du coup je suppose que quand il y a une mise à jour via le market Jeedom, les dossiers ne sont pas correctement supprimés et "synchronisés", il ne fait qu'ajouter et ne supprime pas ce qui est déjà en place si les fichiers ne sont pas/plus présents dans la mise à jour.

**Comment by KiwiHC16** [comment]
Correction ajoutée dans la version de dev.

```Fichier introuvable: ../../core/config/devices/Timer/Timer.json```
C est normal. Tu peux effacer le repertoire.

```Fichier introuvable: ../../core/config/devices/TRADFRISignalRepeater/TRADFRISignalRepeater.json```
Ca ce n est pas normal car il existe: https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TRADFRIsignalrepeater

```Fichier introuvable: ../../core/config/devices/LOM02/LOM02.json```
Ce n'est pas normal car le repertoire comme le fichier n'existe pas. Tu peux supprimer.

**Comment by bocquetm** [comment]
Il faut que vous compreniez pourquoi ils ne sont pas supprimés à la mise à jour ou faire un post script d'installation qui supprime les résidus... Les dossiers ont été créés au fur et à mesure des maj, je vois mal les gens à chaque mise à jour d'abeille passer dans les répertoires pour trouver et supprimer les dossiers vides qui risquent de faire planter leur système.
D'ailleurs il y a plein de personnes qui ont cette problématique, on le voit dans les logs postés par les gens dans leurs issues car ça crée des traces dans les logs d'Abeille.

Sinon le capteur que tu dis qu'il existe, il n'existe pas.

![Screenshot_20201216-085127_Chrome](https://user-images.githubusercontent.com/8374552/102320360-7963a480-3f7c-11eb-9594-306a7ce5503d.jpg)

Dans le git il n'a pas de majuscule alors que j'ai bien des majuscules de mon côté. J'ai tout simplement les 2 car l'autre n'a pas dû être supprimé lors de la maj associée.

![Screenshot_20201216-090105_JuiceSSH](https://user-images.githubusercontent.com/8374552/102321026-67cecc80-3f7d-11eb-8766-28cddd361b08.jpg)

Bref, après, avec le correctif que je vous ai trouvé, cela ne devrait plus trop poser de problème car il n'arrêtera plus le traitement en cas de dossier vide mais par contre il faudrait peut-être mettre un message dans Abeille pour dire de supprimer le dossier manuellement si vous ne voulez pas faire de post script de nettoyage.

**Comment by KiwiHC16** [comment]
Pour le cleaning on va suivre dans le cas: #1556
