### ISSUE TITLE
Onglet Modèles

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1537]
@KiwiHC16 

Jeedom 4.0.61
Zigate 3.1D
Abeille master_tcharp38, 2020-12-12 15:42:46

Je ne sais dans quel but l'onglet Modèles a été ajouté.
Par contre il renvoie des infos qui peuvent intéresser les développeurs.
Pb 

![image](https://user-images.githubusercontent.com/36518012/102081338-5d42f480-3e10-11eb-8240-273dc5438a97.png)

ou cela

getEtat: This uniqId (5c07c76623cd1), doesn t correspond to any template !
--

![image](https://user-images.githubusercontent.com/36518012/102081549-b6ab2380-3e10-11eb-9f02-44fcf0b23648.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
C est en cours de dev et en relation avec #1421.
On suit le sujet dans #1421. Je clos ce cas.
