### ISSUE TITLE
Aide à l'ouverture des Issues

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1538]
@KiwiHC16 

Ne serait-il pas utile d'avoir une fonction dans la page support qui résumerait les points importants que sont :

Version du plugin
Version du FW de la Zigate
Version de Jeedom

Avec un bouton, coller dans le presse-papiers.

Ainsi, chaque fois qu'il est nécessaire d'ouvrir des issues, il n'y plus qu'à commencer par coller le contenu afin que les développeurs possèdent ces infos pour commencer à investiguer.

Ce n'est qu'une proposition. Mais pour avoir ouvert plusieurs issues, je me rends compte que parfois j'oublie de vous communiquer ces infos

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
C est en cours dans la page support tu as:

![Capture d’écran 2020-12-14 à 15 42 47](https://user-images.githubusercontent.com/8549674/102094795-0692e600-3e23-11eb-894a-3d82f7e5cc25.png)

**Comment by mickadam29** [comment]
Oui, C'est un bon point de départ. Reste la version Jeedom, Firware et le bouton "Copier vers Github" comme "Télécharger" et "Télécharger Tout". Ces infos, on les a mais un peu partout. Et l'informaticien fainéant que je suis s'habitue à en faire le moins possible. 

Excellent travail.
Ca chôme pas en ce moment.

**Comment by tcharp38** [comment]
Ca ferait quoi un "copier vers Github" ?

**Comment by mickadam29** [comment]
Je disais en début "Copier vers le presse papiers" pour coller toutes les infos dans l'issue nouvellement créée

**Comment by tcharp38** [comment]
Ca c'est bon que pour un petit bout de log.
Si tu copy/paste un fichier entier, c'est illisible.
Pour un log complet il faut mettre le fichier entier, ou le fichier compressé.

**Comment by KiwiHC16** [comment]
Dans github il faut mettre \`\`\` avant et apres le code  \`\`\` et ca sort propre

**Comment by tcharp38** [comment]
Ok je testerai à l 'occase, mais je conseille de le limiter aux bouts de log de qq lignes.
Sinon ca prend des pages entieres pour seulement une petite partie interessante.

**Comment by mickadam29** [comment]
L'idée @tcharp38 c'est juste de copier/coller les infos à jour des versions OS/JEEDOM/FIRMWARE/ABEILLE sans aller chercher un peu partout dans les interfaces. C'est pas de copier des logs sans fin. L'OS faut passer en ligne de commande, Jeedom dans le menu Réglages, Zigate on a le bouton "tester" pour récupérer la version installée, Abeille faut aller dans configuration ou Support et là on a qq chose prêt à être collé

L'idée donc, c'était que vous rassembliez tout par exemple dans cette page support et qu'un bouton récupère les infos pour ne plus avoir qu'à les coller dans github. C'est peut-être aussi parce que je colle à vos changements que j'y vois un intérêt

Genre ça, et tjs à jour au moment du "Copier"

OS : "Debian GNU/Linux 10 (buster)"
JEEDOM : 4.0.61
FIRMWARE ZIGATE : 3.1D
ABEILLE : master_tcharp38, 2020-12-12 15:42:46

**Comment by mickadam29** [comment]
Ce n'est qu'une idée, mais vous réclamez assez souvent ces infos aux dépositaires d'issues

**Comment by tcharp38** [comment]
C etait le but de la page support. Elle doit regrouper toutes ces infos mais il peut en manquer.

**Comment by mickadam29** [comment]
Oui, je pense que c'est un peu restrictif à Abeille pour le moment. Mais on parle bien de cela ici, non ? 
Plus sérieusement, ce que vous faites est super. Moi, je vois mon côté "Ah mince, j'ai oublié les infos, et d'ailleurs depuis hier, dans quelle version suis-je ?". C'est  certain que pour ceux qui sont encore en 3.0f par exemple et Jeedom 3 sur un raspberry sur lequel ils ne font pas d'évolution, c'est plus facile. Ils ont quelque chose de stable et se souviennent des valeurs à vous indiquez ici.

**Comment by KiwiHC16** [comment]
Ajout des versions firmware
Ajout des lignes Modélisation de AbeilleParser

**Comment by KiwiHC16** [comment]
Je clos et on ajoutera si des besoins.
