### ISSUE TITLE
Implémentation Multiprise TS0115

### ISSUE THREAD

**Issue by Sokren** [KiwiHC16/Abeille#1539]
Bonjour,

Je suis en train d'essayer d'implémenter une multiprise zigbee (4 prises EU + 2 USB)
https://fr.aliexpress.com/item/4001148859962.html?spm=a2g0s.9042311.0.0.36c76c37kTDh6I

J'ai réussi à faire fonctionner le On Off sur les 3 premières prise mais je n'ai pas réussi à faire la 4e et les USB. (je suis parti depuis le template TS0003)
Voici mon fichier json joint
[TS0115.json.txt](https://github.com/KiwiHC16/Abeille/files/5688776/TS0115.json.txt)

Comment peut-on ajouter de nouvelles commandes ? Tel que Off3 etc

Merci de votre aide

PS : Mon autre objectif serait de réussir aussi d'intégrer la NLG-remote par moi même et partager quand j'aurais réussi :) (https://zigbeealliance.org/fr/zigbee_products/q-cct-remote-controller/)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
TS0115: Mis dans la version de dev, sera dans la prochaine stable.

**Comment by KiwiHC16** [comment]
Je clos cet issue et ouvre une autre pour la télécommande.
