### ISSUE TITLE
télécommande CCT

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1540]

**Comment by KiwiHC16** [comment]
#1539 

PS : Mon autre objectif serait de réussir aussi d'intégrer la NLG-remote par moi même et partager quand j'aurais réussi :) (https://zigbeealliance.org/fr/zigbee_products/q-cct-remote-controller/)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Est ce que tu as cette telecommande ?
As tu un sniffer zigbee ?

**Comment by Sokren** [comment]
Oui j'ai la télécommande mais je n'ai pas de sniffer zigbee

**Comment by KiwiHC16** [comment]
Risque d'être difficile mais on peut essayer. Dans un premier temps essayes de trouver tous ce que tu peux sur le net. Et partages.

**Comment by Sokren** [comment]
J'ai trouvé très peu d'information car il s'agit d'une télécommande qui est vendu avec un plafonnier (qui lui s'est intégré sans problème dans le pont HUE)

J'ai trouvé des informations sur une télécommande similaire du même fabriquant sur un autre projet : https://github.com/Koenkk/zigbee2mqtt/issues/4013
https://www.zigbee2mqtt.io/devices/100.462.31.html
https://www.gitmemory.com/issue/Koenkk/zigbee-herdsman-converters/731/549168275

**Comment by tcharp38** [comment]
Salut @Sokren 
Je sais que c'est un tres vieux sujet mais es tu toujours interessé ?

**Comment by Sokren** [comment]
Bonjour @tcharp38 
Pas de soucis, par contre je ne possède plus la télécommande.
On peut close la demande.
Merci

**Comment by tcharp38** [comment]
Ok merci, alors je clos.
A reouvrir si qqn veut bosser sur ce modele.
