### ISSUE TITLE
Zigate change de port série et mets la mauvaise zigate

### ISSUE THREAD

**Issue by shadsnob** [KiwiHC16/Abeille#1541]
Bonjour, je suis sur jeedom 4.0.61 Zigate 3.1d et abeille stable, 2020-12-01 15:00 je comprend pas a chaque fois lors d'un redémarrage du système ma clé Zigate est remplace par ma clé rfplayer est ce que ça vient du module USB-TTL Prolific (bleu) (Plus distribué depuis Juillet 2019) ou du plugin 

[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5689581/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5689582/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5689583/AbeilleSerialRead1.log)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5689584/Abeille.txt)
[AbeilleDbConf.txt](https://github.com/KiwiHC16/Abeille/files/5689585/AbeilleDbConf.txt)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Je ne peux rien faire pour cela. Regardes dans les differents post, ce sujet a deja ete couvert. Plusieurs solutions existent.

**Comment by tcharp38** [comment]
@shadsnob Juste pour clarifier un peu le souci. Ca ne vient ni de Jeedom ni du plugin Abeille mais de ton systeme qui change l'affectation des ports USB au demarrage, en fonction de la clef qui demarre le + vite j'imagine.

Abeille ne sait gerer qu'un port bien defini et fixe.
