### ISSUE TITLE
(master) Graphique du reseau que pour la Zigate1

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1542]
![Capture d’écran 2020-12-14 à 17 22 52](https://user-images.githubusercontent.com/8549674/102106547-013c9800-3e31-11eb-93ae-e4f780bdbaf6.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Quel que soit le bouton vert AbeilleX sélectionné, j ai toujours le graph de la Zigate1.
Je n ai pas le soucis avec l onglet "Table des noeuds"

**Comment by tcharp38** [comment]
Peux tu donner la trace de la console JS quand tu cliques sur Abeille2 ou autre > 1 ?
C'est pas la premiere fois que tu remontes ce souci.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-12-14 à 17 28 32](https://user-images.githubusercontent.com/8549674/102107225-cb4be380-3e31-11eb-90fe-8957c02142d5.png)
Demande graph zigate 1 puis demande graph zigate 2
L appel semble bon.

**Comment by tcharp38** [comment]
Ouais. Donc je suppose que le souci est ailleurs. Je soupconne qu' on recupere le bon JSON mais qu'on que la partie affichage est daubée. Je vais revoir ma copie

**Comment by KiwiHC16** [comment]
ok (oui c est la premiere fois que je vois ce soucis).
