### ISSUE TITLE
(Master) Erreur lors du lancement manuel du refresh LQI

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#1543]
Hello,

Je viens de m'apercevoir d'une erreur Javascript lors du refresh manuel du LQI 👍 

![image](https://user-images.githubusercontent.com/56156622/102108889-bec88a80-3e33-11eb-9103-95c36f247a40.png)

A priori, la commande est bien exécutée car si je patiente qq mins le tableau des noeuds est bien actualisé.
Cette erreur n'apparait pas lors du refresh auto à 0h00. Pas de trace dans les logs http.error

Jeedom v4.1.16
RPI 4
Zigate USB v3.1c

Xav

**Comment by tcharp38** [comment]
Merci. je regarde ca aussi.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by tcharp38** [comment]
@Xav-74 Peux tu ouvrir la console JS (F12 sur la plupart des navig) et montrer la ligne juste avant l'erreur. Tu devrais trouver un truc du style "Status=xxx"
Merci

**Comment by Xav-74** [comment]
Voici ;)

![image](https://user-images.githubusercontent.com/56156622/102114952-1fa79100-3e3b-11eb-8374-fddc964d1dd4.png)

**Comment by Xav-74** [comment]
D'ailleurs, en me plongeant dans les logs http.error j'ai plusieurs récurrences concernant le plugin Abeille.
J'ouvre une nouvelle issue où on traite ici ?

**Comment by tcharp38** [comment]
Ok merci pour la piste. Le status est celui que j'attendais. Je vais nettoyer ca.
Si tu penses que les autres erreurs ne correspondent pas au sujet, ouvre une autre issue.

**Comment by tcharp38** [comment]
En fait je n'arrive pas à comprendre comment se produit ce cas de figure. Si tu as des idées je prends.

**Comment by Xav-74** [comment]
Peut-être lié à la 4.1 ?

**Comment by Xav-74** [comment]
Je me demande d'ailleurs si les erreurs dans le log http.error ne sont pas liées : (les heures coïncident)

```
[14-Dec-2020 17:25:59 Europe/Brussels] PHP Notice:  Undefined index: nbProcess in /var/www/html/plugins/Abeille/desktop/modal/network.php on line 55
[14-Dec-2020 17:25:59 Europe/Brussels] PHP Notice:  Undefined index: nbProcessExpected in /var/www/html/plugins/Abeille/desktop/modal/network.php on line 55
[14-Dec-2020 17:25:59 Europe/Brussels] PHP Notice:  Undefined index: nbProcess in /var/www/html/plugins/Abeille/desktop/modal/network.php on line 56
[14-Dec-2020 17:25:59 Europe/Brussels] PHP Notice:  Undefined index: nbProcessExpected in /var/www/html/plugins/Abeille/desktop/modal/network.php on line 56
```

**Comment by tcharp38** [comment]
Non, ces erreurs trainent depuis un moment mais c'est plus du warning qu'autre chose.
Il s'affiche autre chose quand tu lances le refresh manuel ?

**Comment by Xav-74** [comment]
non malheureusement rien d'autre
je n'ai par exemple pas la bande verte avec le décompte du nombre d'équipement

**Comment by tcharp38** [comment]
Je n'ai pas compris dans quel cas de figure on tombe sur cette erreur mais j'ai un peu blindé le truc.
Elle ne devrait plus apparaitre.
A réouvrir si besoin.

**Comment by Xav-74** [comment]
Hello !
Mise à jour de la master à l'instant.
Même erreur :(

**Comment by tcharp38** [comment]
Salut
Tu parles de laquelle ?

**Comment by Xav-74** [comment]
Version Abeille master du jour !
Pour l'erreur : celle du Javascript lors du refresh manuel du LQI (cf. premier message de cette issue)

**Comment by tcharp38** [comment]
Ha oui ?! C est le meme numero de ligne ?

**Comment by Xav-74** [comment]
Ah bien vu ! Non pas même ligne -> 177 maintenant
et la partie console :

![image](https://user-images.githubusercontent.com/56156622/102623438-c42f1900-4142-11eb-87cd-f810d0129ccf.png)

**Comment by tcharp38** [comment]
Ok c est toujours le meme cas que j'arrive pas à reproduire. Je reouvre.

**Comment by Xav-74** [comment]
on peut regarder sur ma machine si tu veux !
Peut-être lié à la 4.1 ?

**Comment by tcharp38** [comment]
J'allais te demander ton aide. Tu as le souci chaque fois que tu relances manuellement la collecte ?

**Comment by Xav-74** [comment]
Yes à chaque clic :)
Aucun souci pour t'aider !

**Comment by tcharp38** [comment]
Ok merci.
Peux tu essayer avec le code suivant a decompresser dans "destkop/js"

[network.zip](https://github.com/KiwiHC16/Abeille/files/5716841/network.zip)

J'ai besoin de la trace de console Javascript à partir de "trackLQICollectStatus" jusqu'a l'erreur.

**Comment by Xav-74** [comment]
Voila : 

![image](https://user-images.githubusercontent.com/56156622/102639212-fcd9ed00-4158-11eb-925e-bd087d84801f.png)

**Comment by tcharp38** [comment]
T es sur d'avoir utilisé mon fichier ? J'ai ajouté une trace que je ne vois pas la.

console.log("res="+JSON.stringify(res));

Donc on devrait voir "res=" juste avant "Status="

**Comment by Xav-74** [comment]
j'ai bien décompressé le fichier dans le bon rep.
Ce qui m'a paru bizarre, c'est que ce fichier n'existait pas avant !
Normal ? Comment est-il appelé du coup ?

**Comment by tcharp38** [comment]
Ben il s'appelle "network.js". Tu dois l'avoir. Ca n'est pas qqch de nouveau.
Je ne pense pas qu'on l'ai changé de place recemment donc "desktop/js" devrait etre la bonne place.

**Comment by Xav-74** [comment]
Me demande pas où je l'avais mis, ce devait être la fatigue de la fin de semaine !!!

C'est mieux ce matin :)

![image](https://user-images.githubusercontent.com/56156622/102709308-9fa18100-42a9-11eb-9392-ae284731f12b.png)

**Comment by tcharp38** [comment]
Je te demande pas :)
Reste a comprendre ce foutu message. Merci

**Comment by tcharp38** [comment]
Bon j'ai une piste. J arrive à reproduire.
Par hasard si tu te reconnectes a ton Jeedom puis tu retentes ca donne la meme chose ?
J'ai l'impression que tu relances la collecte dans une fenetre ouverte depuis longtemps.

**Comment by Xav-74** [comment]
Yes cette erreur est systématique ! Aucune autre modale ou fenêtre ouverte.
Je viens de tester sur un autre navigateur où il n'y avait pas de cache.
Idem

**Comment by tcharp38** [comment]
?! Tu te reconnectes à Jeedom, passes sur la fenetre "Network list" puis lances la recherches. C'est ca ?
J'arrive à reproduire ton souci que lorsque je me suis déconnecté du serveur sur une autre fenetre.
Je vais pousser une petite update de ce côte mais si ca match toujours pas ton cas.. suis toujours perdu.

**Comment by Xav-74** [comment]
Oui c'est ca !
Je viens de refaire un test en supprimant toues les fenêtres où je pouvais être connecté (GSM, tablette,...)
Je n'ai plus qu'une seule session d'ouverte, et même souci !

**Comment by Xav-74** [comment]
Je pousserai la master demain et je te tiendrai au courant ;)
Merci pour ton aide !

**Comment by tcharp38** [comment]
@Xav-74 
Le dernier correctif est dans le master maintenant.

**Comment by Xav-74** [comment]
Même erreur lors de mes tests auj :(

![image](https://user-images.githubusercontent.com/56156622/103286595-c31ea700-49e0-11eb-891a-69925918ea64.png)

Après cela n'est pas bloquant donc...

Xav

**Comment by tcharp38** [comment]
Grrr.. pas bloquant mais j'aimerais bien comprendre comment on tombe dans ce cas.
Je viens juste de passer en v4 mais je realise que tu es encore + avancé.. v4.1.
Une raison pour etre si avancé cote Jeedom ?
Quoi qu 'il en soit je vais encore creuser, voir comment reproduire ce truc.

**Comment by Xav-74** [comment]
Hello,

J'ai basculé ma prob en v4.1 pour mon plugin Verisure. Ma preprod (une mini+) a grillé récemment et j'avais besoin de faire des tests de compatibilité rapide pour valider le bon fonctionnement de mon plugin en v4.1.
Et comme elle est annoncée en stable pour Janvier ;)

Je repensai à notre pb : est ce que le fait que mes 2 interfaces LAN et WLAN soient activées et fonctionnelles sur mon PI4 pourraient jouer ?
Tu parlais de connexions simultanées ?

Xav

**Comment by tcharp38** [comment]
Salut Xav
Non je ne vois pas de rapport avec les interfaces mais comme je n'arrive pas à reproduire ce cas qqch m'echappe surement.
En + personne d'autre n'a remonté ce pb. En meme temps faut ouvrir la console JS pour le voir donc c'est peut etre normal.

Enfin je n'ai pas regardé les modifs de la 4.1 alors je sais pas si c est le coupable. Si t'as la possibilité de tester en v4 peut etre que ca peut aider sinon ... on verra lors d'une autre idée geniale.
A suivre...

**Comment by Xav-74** [comment]
Hello,
Alors je ne sais pas ce que tu as changé dans la dernière beta, mais tu as corrigé le souci 😉
Il y a eu 2 MAJ auj : le core en 4.1.18 et la beta de Abeille. L'une des 2 a du corriger le souci.
Je retrouve maintenant le bandeau avec le décompte de tous mes modules `xx/XX en cours` 

👍 👍 

Xav

**Comment by tcharp38** [comment]
Salut
Ha une bonne nouvelle. J'ai lu trop vite et je me disais "encore un souci" :) mais non.
Merci
