### ISSUE TITLE
Refresh LQI Impossible avec BETA 2020-12-14 17:50:15

### ISSUE THREAD

**Issue by bocquetm** [KiwiHC16/Abeille#1544]
Problème toujours présent avec la version  BETA 2020-12-14 17:50:15 

#1524

**Comment by bocquetm** [comment]
@tcharp38  J'ai refait un sujet du coup vu qu'il a dit de recréer :)

**Comment by tcharp38** [comment]
Parfait. Ca va etre aussi + facile de trouver ce qui deconne pour toi avec une version + recente. Il y a eu beaucoup trop de modifs.

**Comment by bocquetm** [comment]
@tcharp38 

Premier debug ;)

![image](https://user-images.githubusercontent.com/8374552/102113258-1f0dfb00-3e39-11eb-8410-fcc6aebbdeea.png)

[Mon Dec 14 18:18:29.618415 2020] [php7:error] [pid 9048] [client X.X.X.X:38766] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /var/www/html/plugins/Abeille/Network/AbeilleLQI.php:296\nStack trace:\n#0 {main}\n  thrown in /var/www/html/plugins/Abeille/Network/AbeilleLQI.php on line 296, referer: https://Y.Y.Y.Y/index.php?v=d&m=Abeille&p=Abeille

**Comment by tcharp38** [comment]
Ok c est un vieux truc ca que je ne peux pas reproduire mais j'ai une piste.
Pour le reste peux tu devrais avoir un AbeilleLQI.log dans /tmp/jeedom/Abeille.

En fait, je suggere la chose suivante
- tu vides AbeilleParser & AbeilleCmd
- tu lances un refresh manuel
- tu me donnes les logs AbeilleParser, Cmd et AbeilleLQI

**Comment by bocquetm** [comment]
C'est pas très parlant les logs de debug...


**AbeilleLQI.log**
```
[2020-12-14 18:35:45] Démarrage d'AbeilleLQI.
[2020-12-14 18:35:45] Interrogation de la zigate 1

```

**AbeilleCmd.log**
`[2020-12-14 18:35:37][debug] tempoMessageQueue: 0 - cmdQueue: 1 nb message: 0 -
`

**AbeilleParser.log**

Nada


Après l'erreur serveur tu as un retour comme quoi le fichier JSON n'existe pas 

![image](https://user-images.githubusercontent.com/8374552/102115362-c2600f80-3e3b-11eb-8670-ba12cab8fb19.png)

**Comment by tcharp38** [comment]
Ok bizarre. Je vais voir si la premiere erreur que tu as remonté peut bloquer le tout.

Tu serais partant pour modifier un peu de code pour faire des tests ? Je pense à AbeilleLQI.php, donc ca ne touche pas l'aspect fonctionnel d'Abeille, juste la collecte des infos.

**Comment by tcharp38** [comment]
Donc le pb de getName() est bien bloquant.
Voila le code si tu veux le tester. Tu as juste à remplacer ton "AbeilleLQI.php" par celui attaché.

[AbeilleLQI.zip](https://github.com/KiwiHC16/Abeille/files/5691030/AbeilleLQI.zip)

**Comment by bocquetm** [comment]
Nickel ! 👍 

![image](https://user-images.githubusercontent.com/8374552/102127649-0d365300-3e4d-11eb-9a0e-4ce37ee0560d.png)


Du coup les 2 parties Listing et Graphique du réseau sont fonctionnels:

![image](https://user-images.githubusercontent.com/8374552/102128111-ab2a1d80-3e4d-11eb-950b-22dad6eb61c0.png)


Après j'ai eu une grosse mise à jour de toutes les adresses, je ne sais pas si c'est normal :

![image](https://user-images.githubusercontent.com/8374552/102128199-cdbc3680-3e4d-11eb-84e2-e86af73e2cb7.png)

**Comment by tcharp38** [comment]
A priori oui si il ne s'agit que de passer de minucules à majuscules. Ca semble etre le cas.

**Comment by tcharp38** [comment]
Pour moi ce cas est fixé dans le master. A réouvrir si besoin.
