### ISSUE TITLE
Reduce images (doc) and icon size to spare space.

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#155]
- no need of 600x600 icon size. 300x300 seems to be a good ratio
- image size to be defined for the best user experience.

le code html donne une idée de ce qui est attendu :)
`<img` name="icon_visu" src="" width="160" height="200"/>`

**Comment by KiwiHC16** [comment]
Je crois bien avoir vu passer tous les icones en petites tailles dans un PR, je clos donc le sujet.
