### ISSUE TITLE
Intégration TS0041 (Interrupteur Zemismart 1 gang sur pile)

### ISSUE THREAD

**Issue by Sokren** [KiwiHC16/Abeille#1550]
Bonjour,

Je viens de finir de créer le json pour le TS0041 (en PJ le json et l'image)
J'ai d'ailleurs préparé le modèle TS0042 qui est je pense la version 2 interrupteurs mais je n'ai aucun moyen de le tester…

[TS0041.json.txt](https://github.com/KiwiHC16/Abeille/files/5693980/TS0041.json.txt)
![TS0041](https://user-images.githubusercontent.com/25526655/102183398-13a8e700-3eae-11eb-877f-148fad26f444.jpg)
[TS0042.json.txt](https://github.com/KiwiHC16/Abeille/files/5693981/TS0042.json.txt)
![TS0042](https://user-images.githubusercontent.com/25526655/102183402-14417d80-3eae-11eb-9495-0987146c53ea.jpg)

Par contre j'ai galéré à trouver comment mettre la zigate en mode hybride (quand on le sait on sait que c'est simple)
Pour ceux qui verront le message par la suite, il faut aller dans le pluggin Abeille et descendre jusqu'à trouver "Set Mode" et cliquer sur "Set Hybride Mode Z1"
Il faut avoir le firmware 3.1D

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Super merci. J'ai mis dans le master.

**Comment by M4dd4M** [comment]
Bonjour, @tcharp38 
J'ai un soucis avec ce bouton, il apparait bien, mais la ligne commande indiquant le résultat du clic n'apparait pas ...
et il remonte avec un autre nom, c'est étrange.
Voici la découverte : 
[discovery-undefined__TZ3000_axpdxqgu bouton mezza TS0041.json](https://github.com/user-attachments/files/15924916/discovery-undefined__TZ3000_axpdxqgu.bouton.mezza.TS0041.json)

**Comment by tcharp38** [comment]
Peux tu lire l attribut 0005 du cluster 0000 via l onglet avancé ?
et me filer les logs

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/81de2e96-d20a-45ad-a625-b5064b36c124)

**Comment by M4dd4M** [comment]
Salut @tcharp38,
J'espère que j'ai bien fait ...mais je ne vois pas de résultat particulier (en même temps je ne comprends pas bien les logs ^^ )
Lancé à 23:54 et 23:55 (J'ai écrit "0005" et cliqué sur "Lire")
[AbeilleLogs-240623 (inter).gz](https://github.com/user-attachments/files/15946395/AbeilleLogs-240623.inter.gz)

**Comment by tcharp38** [comment]
Ton device ne répond pas.

    [2024-06-23 23:55:03] Abeille1, Type=8000/Status, Status=00/Success, SQN=04, PacketType=0100, Sent=01, SQNAPS=F8, NPDU=00, APDU=01
    [2024-06-23 23:55:03] Abeille1, Type=8702/APS data confirm fail, Status=E9/MAC_ENUM_NO_ACK, SrcEP=01, DstEP=01, AddrMode=02, Addr=9FB1, SQNAPS=F8, NPDU=00, APDU=01
    [2024-06-23 23:55:10] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=9FB1, EP=01, ClustId=0000, SQNAPS=F8

Trop loin de la zigate ?

Juste pour clarifier la situation ce device n'est pas reconnu.
Il ne renvoi pas son identifiant "TS0041", mais juste le fabricant "_TZ3000_axpdxqgu".
Reste à comprendre si il y a un souci ailleurs (pb de routage ? pb de Zigate ? pb Abeille ?) ou c'est juste un device pourri.

D'ailleurs il est neuf ? Jamais utilisé ? Quel est son histoire ?

**Comment by M4dd4M** [comment]
Ok, je vais démonter pour le rapprocher.
En fait c'est mon premier interrupteur (ça doit être mon premier bouton intégré avec l'abeille), et jusqu'ici je l'utilisait "mal" c'est a dire que j'avais mis une action sur son actualisation (le Time-Time je crois) ... donc ça marchais, mais je comprenais pas pourquoi la lumière s'allumais de manière aléatoire ^^
Je ne crois pas que la device soit pourrie, après, j'ai peut-être essayer de bidouiller des choses dans les modèles dans les modèles du dossier "Devices" à l'époque (je ne me rappel pas) ... j'ai appris plus tard qu'il ne fallait pas jouer avec ça

**Comment by tcharp38** [comment]
Si tu étais déja en mode "bidouille" avant c'est peut etre que le modele n'a jamais été terminé.
Mais je doute encore de son comportement.
Regenere moi un discovery. Tant qu'il ne donne pas son nom.. je ne vois pas comment il peut etre considéré comme un truc serieux.

**Comment by M4dd4M** [comment]
Salut @tcharp38,
Pour info, depuis juillet, j'avais testé de forcer le remplacement du modèle : cet interrupteur fonctionne parfaitement avec le modèle loratap 3 bouton (TS0043__TZ3000_bi6lpsew), sur le click 1.
En l'état c'est donc parfaitement fonctionnel pour moi.

**Comment by tcharp38** [comment]
Salut @M4dd4M 
Donc tu as forcé le modele ?
Peux tu me filer ton package de logs et me dire de quel device il s'agit ? (nom ou adresse)

**Comment by M4dd4M** [comment]
Hello,
Oui, comme dit au dessus j'ai forcé avec le modèle loratap 3 bouton (**TS0043__TZ3000_bi6lpsew**).
Te voici un package de Log.
(j'ai fait des actions dessus : 1 clic simple, 1 clic double, 1 clic long ... )
[AbeilleLogs-241009.tar.gz](https://github.com/user-attachments/files/17312227/AbeilleLogs-241009.tar.gz)

C'est effectivement mieux que tu l'intègres proprement, car hier, le remplacement avait sauté. (et du coup j'avais perdu mes actions ^^ )

... et tu peux déjà préparer un autre, le  **TS0041_TZ3000_oxjrteo6**, un bouton 1 action très similaire, qui avait le même comportement que mon bouton de ce sujet, et qui fonctionne de la même manière (c'est a dire correctement 😁 ) en forçant le modèle loratap 3 bouton (TS0043__TZ3000_bi6lpsew)
