### ISSUE TITLE
Problème toujours même sous bêta 2020-12-15 11:20:57

### ISSUE THREAD

**Issue by shadsnob** [KiwiHC16/Abeille#1553]
Bonjour j'ai essayer la nouvelle bêta mais toujours les mêmes soucis je suis en :

1/ Version (AbeilleVersion.inc)
===================================
beta, 2020-12-15 11:20:57
2/ Linux
============
["Raspbian GNU\/Linux 10 \\n \\l","","\u001b[9;0]"]
["Linux raspberrypi 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU\/Linux"]
3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

Lorsque je rafraîchie ma network list il se passe rien ou alors il faut que je fasse tout les boutons pour apercevoir ceci alors que mon module est connecte et pas en timeout seulement si je l'ouvre et le ferme sinon il passe en timeout 

![1](https://user-images.githubusercontent.com/55192541/102245005-4fb76880-3efd-11eb-8ef1-3e3066828eeb.png)
![2](https://user-images.githubusercontent.com/55192541/102245011-51812c00-3efd-11eb-8175-cf7db5a70fdf.png)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5697294/Abeille.txt)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5697295/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/5697296/AbeilleConfig.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5697297/AbeilleParser.log)

**Comment by tcharp38** [comment]
Salut.
Je vois des trucs pas sympa dans le parser. En particulier le status=C1 pour les message 804E.
La page santé donne quoi ?

**Comment by shadsnob** [comment]
il etait en timeout avant que je fasse une ouverture de porte pour le remettre ok

![1](https://user-images.githubusercontent.com/55192541/102246985-a7ef6a00-3eff-11eb-83ad-c11779b2ca8c.png)

**Comment by tcharp38** [comment]
Recois tu des message dans le parser de ton sonoff ? Message 8102/8100 je pense

**Comment by shadsnob** [comment]
le parser eux c'est quoi ca ?
dans un scenario si il s'ouvre je dois recevoir un email et il le fait

**Comment by tcharp38** [comment]
Pardon, le log du parser donc 'AbeilleParser.log"
Ok, donc ton sonoff est bien en vie est envoie des messages.

Tu peux recuperer le log AbeilleLQI ? Il est dans /tmp/jeedom/Abeille

**Comment by shadsnob** [comment]
j'ai relancer la machine mais je vois rien dans le chemin que vous m'indiquer

**Comment by tcharp38** [comment]
Il est generé tous les soirs à minuit, ou quand on force la reinterrogation du reseau.

**Comment by shadsnob** [comment]
Voici se que j'ai réussi a avoir dans ce dossier

[AbeilleCmd-prev.log](https://github.com/KiwiHC16/Abeille/files/5698107/AbeilleCmd-prev.log)
[AbeilleLQI.log](https://github.com/KiwiHC16/Abeille/files/5698109/AbeilleLQI.log)
[AbeilleLQI_MapDataAbeille1.json.txt](https://github.com/KiwiHC16/Abeille/files/5698116/AbeilleLQI_MapDataAbeille1.json.txt)

**Comment by tcharp38** [comment]
Ce que je vois est coherent avec le fait que la zigate ne remonte RIEN quand on lui demande la liste des equipements connus.
Tu as fait plusieurs passages entre FW 3.1c et 3.1d ?
De mon cote je n'ai aucune confiance dans cette version de FW. Comme la, il y a trop de comportements inexplicables.

Je vais tenter qq essais sur une plateforme de test mais dans l'immediat je ne sais que dire. Le pb ne vient pas d'Abeille mais de la zigate elle meme.

**Comment by mickadam29** [comment]
1/ Version (AbeilleVersion.inc)
===================================
master_tcharp38, 2020-12-14 22:53:57

2/ Linux
============
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

Certaines trames semblent passer à l'as.
De mon côté, j'ai passé certains timeout à des valeurs plus élevées, 2 à 240 minutes. Et j'ai 1 timeout dans les messages. 1 dans Santé. Le même dans les équipements (vue de jeedom). Equipement connu pour ne pas envoyer assez de messages. Il peut se passer plusieurs entre chaque message.
Par contre je reçois des mails chaque fois que j'ai un équipement en Timeout. Ces mails, j'en plusieurs par jour et cela concerne plusieurs équipements.  Donc plusieurs équipements passent en timeout dans la journée.
Si je n'avais pas ces mails, ces timeout passeraient inaperçus. Mais ils existent.

**Comment by KiwiHC16** [comment]
@shadsnob, ou en es tu ?

**Comment by tcharp38** [comment]
Aucune nouvelle depuis fin jan.
@shadsnob, Je clos mais a reouvrir si besoin
