### ISSUE TITLE
on master: Uncaught Error: Class 'MsgAbeille'

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1558]
> [16-Dec-2020 14:44:08 Europe/Brussels] PHP Fatal error:  Uncaught Error: Class 'MsgAbeille' not found in /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php:163
> Stack trace:
> #0 /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php(1462): AbeilleParser->mqqtPublish('Abeille3/Ruche', 'Network', 'Status', 'Network (alread...')
> #1 /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php(573): AbeilleParser->decode8024('Abeille3', '04000000158D000...', '000D', 0, '')
> #2 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php(200): AbeilleParser->protocolDatas('Abeille3', '8024000D1C04000...', 0, Array, Array)
> #3 {main}
> thrown in /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php on line 163

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
