### ISSUE TITLE
Install sur RPI3

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#156]
Install Stuck at 5%

-----------------------------------------------------------------
`
+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependancy_abeille_in_progress
+ tries=3
+ echo 'Début d'\''installation des dépendances'
Début d'installation des dépendances
+ '[' '!' -z /tmp/jeedom/Abeille/dependance ']'
+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependance
+ touch /tmp/jeedom/Abeille/dependance
+ echo 0
+ echo
+ echo 'Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement '
Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement
+ echo
++ id
+ cmd='uid=0(root) gid=0(root) groups=0(root)'
+ echo 'id: uid=0(root)' 'gid=0(root)' 'groups=0(root)'
id: uid=0(root) gid=0(root) groups=0(root)
++ pwd
+ cmd=/var/www/html/core/ajax
+ echo 'pwd: /var/www/html/core/ajax'
pwd: /var/www/html/core/ajax
++ uname -a
+ cmd='Linux jeedomzwave 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux'
+ echo 'uname -a: Linux' jeedomzwave 4.9.35-v7+ '#1014' SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
uname -a: Linux jeedomzwave 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
+ '[' -d /etc/php5/fpm/ ']'
+ '[' -d /etc/php5/apache2/ ']'
+ echo 'system tourne avec apache2 et php5'
system tourne avec apache2 et php5
+ SERVICE=apache2
+ echo 5
+ echo
+ echo 'Avancement: 5% ---------------------------------------------------------------------------------------------------> Install lsb-release php-pear'
Avancement: 5% ---------------------------------------------------------------------------------------------------> Install lsb-release php-pear
+ echo
+ apt-get -y install lsb-release php-pear
Reading package lists...
Building dependency tree...
Reading state information...
lsb-release is already the newest version.
lsb-release set to manually installed.
The following extra packages will be installed:
libapache2-mod-php5 php5-cli php5-common php5-curl php5-gd php5-mysql
php5-readline
Suggested packages:
php5-user-cache
The following packages will be upgraded:
libapache2-mod-php5 php-pear php5-cli php5-common php5-curl php5-gd
php5-mysql php5-readline
8 upgraded, 0 newly installed, 0 to remove and 114 not upgraded.
Need to get 4894 kB of archives.
After this operation, 614 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-gd armhf 5.6.33+dfsg-0+deb8u1 [23.2 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-readline armhf 5.6.33+dfsg-0+deb8u1 [11.2 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-cli armhf 5.6.33+dfsg-0+deb8u1 [1908 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-curl armhf 5.6.33+dfsg-0+deb8u1 [24.5 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-mysql armhf 5.6.33+dfsg-0+deb8u1 [52.2 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ jessie/main libapache2-mod-php5 armhf 5.6.33+dfsg-0+deb8u1 [1881 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian/ jessie/main php5-common armhf 5.6.33+dfsg-0+deb8u1 [728 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ jessie/main php-pear all 5.6.33+dfsg-0+deb8u1 [266 kB]
Reading changelogs...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 4894 kB in 6s (751 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 52240 files and directories currently installed.)
Preparing to unpack .../php5-gd_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-gd (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php5-readline_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-readline (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php5-cli_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-cli (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php5-curl_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-curl (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php5-mysql_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-mysql (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../libapache2-mod-php5_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking libapache2-mod-php5 (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php5-common_5.6.33+dfsg-0+deb8u1_armhf.deb ...
Unpacking php5-common (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Preparing to unpack .../php-pear_5.6.33+dfsg-0+deb8u1_all.deb ...
Unpacking php-pear (5.6.33+dfsg-0+deb8u1) over (5.6.30+dfsg-0+deb8u1) ...
Processing triggers for man-db (2.7.5-1~bpo8+1) ...
Setting up php5-common (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up php5-gd (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up php5-cli (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up php5-readline (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up php5-curl (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up php5-mysql (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Setting up libapache2-mod-php5 (5.6.33+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
apache2_invoke php5: already enabled
`
-----------------------------------------------------------------

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-03-02 a 12 24 04](https://user-images.githubusercontent.com/8549674/36896904-a5889340-1e14-11e8-9923-5daf9a1f6a73.png)

Install depuis git clone + chmod 777 + chown www-data

**Comment by KiwiHC16** [comment]
echo 5 > ${PROGRESS_FILE}
echo
echo "Avancement: 5% ---------------------------------------------------------------------------------------------------> Install lsb-release php-pear"
echo

apt-get -y install lsb-release php-pear
[[ $? -ne 0 ]] && arretSiErreur "Erreur lors de l'installation de pear et lsb-release. Pb réseau ?"

echo 8 > ${PROGRESS_FILE}
echo
echo "Avancement: 8%

**Comment by KiwiHC16** [comment]
cat: /tmp/jeedom/Abeille/dependancy_abeille_in_progress: No such file or directory

**Comment by KiwiHC16** [comment]
Demande relance installation dependances:

![capture d ecran 2018-03-02 a 12 27 57](https://user-images.githubusercontent.com/8549674/36897013-297de36c-1e15-11e8-93f6-d5f33237d938.png)

**Comment by KiwiHC16** [comment]
cat /tmp/jeedom/Abeille/dependance 
5

**Comment by KiwiHC16** [comment]
rm dependance pour relancer install dependance

+ echo 'Avancement: 5% ---------------------------------------------------------------------------------------------------> Install lsb-release php-pear'
Avancement: 5% ---------------------------------------------------------------------------------------------------> Install lsb-release php-pear
+ echo
+ apt-get -y install lsb-release php-pear
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
+ [[ 100 -ne 0 ]]
+ arretSiErreur 'Erreur lors de l'\''installation de pear et lsb-release. Pb réseau ?'
+ echo
+ echo '***************'
***************
+ echo Erreur lors de 'l'\''installation' de pear et lsb-release. Pb $'réseau' '?'
Erreur lors de l'installation de pear et lsb-release. Pb réseau ?
+ echo '***************'
***************
+ echo

**Comment by KiwiHC16** [comment]
dpkg --configure -a
Setting up libapache2-mod-php5 (5.6.33+dfsg-0+deb8u1) ...
apache2_invoke php5: already enabled
Setting up php-pear (5.6.33+dfsg-0+deb8u1) ...
Installing new version of config file /etc/pear/pear.conf ...

**Comment by KiwiHC16** [comment]
relance install

**Comment by KiwiHC16** [comment]
Install finish but stay at 70% on plugin page like if stuck. Impression je suis planté.
Mais si on recharge la page tout est ok.

Tous les process Up and running.

Sauf qu'ils sont sur le port USB0 sur lequel j ai RFXCom !!!

**Comment by KiwiHC16** [comment]
La ruche est sur le premier objet. Alors je crée un objet dédié. Mais comment connaitre son Id. Il faudrait un menu deroulant d objet dans le conf du plug in.

**Comment by edgd1er** [comment]
Je met 1, tu peux le changer ensuite dans la conf du device. Cela peut être ma prochaine tache...

**Comment by edgd1er** [comment]
ton log ne montre pas d'anomalie. le dpkg --configure -a que tu as fait montre que l'installation s'est arrêté en cours de route. Il est sans doute trop tard pour avoir la raison en analysant /var/log/apt/* ou /var/log/syslog

**Comment by KiwiHC16** [comment]
Oui c'était bizarre. Tout était stoppé et aucune trace d'activité dans les "ps -ef" ni dans les logs. Probablement un des problemes qu'on ne rencontrera plus jamais.

**Comment by KiwiHC16** [comment]
Je clos ce sujet car vieux.
Je vais faire des tests d install sur un RPI3 fresh et j ouvrirai des points specifiques si besoin.
