### ISSUE TITLE
AbeilleParser Erreur CRC

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1562]
```
PHP Notice:  Uninitialized string offset: 5649 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.class.php on line 533
```

Ce n est pas la peine d avoir une boucle qui va jusqu'a un valeur de folie on peut bloquer à la longueur max d un message.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
#1563

Cela viens peut de la duplication de process qui doivent se marcher sur les pieds. Car quand j ai les bons Processes je n 'ai pas le soucis.

Donc probablement pas de probleme mais on peut quand meme:
"Ce n est pas la peine d avoir une boucle qui va jusqu'a un valeur de folie on peut bloquer à la longueur max d un message."

**Comment by tcharp38** [comment]
Je comprends mieux.

Pour info, j'avais laissé ce code "legacy" mais j'avais implementé le check CRC directement dans SerialRead.
L'idée etant dans le futur de limiter les messages inutiles qui pouvaient du coup remonter au parser.

**Comment by KiwiHC16** [comment]
Les plus longs messages que je vois au niveau Zigbee sur mon sniff en cours sont de 127 bytes.

**Comment by KiwiHC16** [comment]
Et dans un doc je trouve: 
PHY Available Payload: 127:  maximum 802.15.4 payload size
+4 preamble
+1 SFD
+1 Lenght
=133 Phy Layer.

Je suppose que la zigate ne vas pas consolider des messages. Je vais bloquer à 150 avec un log si 150 est atteint.
