### ISSUE TITLE
Erreur à l'interrogation de la version du firmware Zigate

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1567]
1/ Version (AbeilleVersion.inc)
===================================
dev_tcharp38, 2020-12-16 10:38:17

2/ Linux
============
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

Ce matin, en voulant tester la bonne communication avec la zigate en mode USB. J'ai un message de Jeedom. Je le retrouve pas mais il m'indiquait "Danger il manque un processus pour .... ". Les tentatives sont bonnes par la suite. On voit bien 3.1D.

![image](https://user-images.githubusercontent.com/36518012/102588885-6ed91480-410e-11eb-963c-d6fc7a036db6.png)

Par contre j'ai ça au moment où j'ai fait l'interrogation

![image](https://user-images.githubusercontent.com/36518012/102588778-46511a80-410e-11eb-8241-98f291b22141.png)

La Zigate fonctionnait car les scénarios d'éclairage fonctionnaient également.

**Comment by tcharp38** [comment]
J'ai vu ces erreurs. j'ai poussé un correctif hier que Kiwi a déja mergé sur le master.

**Comment by mickadam29** [comment]
OK. Je vais faire la maj. Merci

**Comment by tcharp38** [comment]
Welcome. Mais n'hesite pas. On essaie d'etre reactifs et surtout de "nettoyer" le schmilblick mais ya encore du taf

**Comment by mickadam29** [comment]
Comme tu l'as sans doute constaté, je n'hésite pas à prendre la "Master" via github. Jouant certainement un peu avec le feu.
Mais il faut bien du monde pour recetter. J'ai d'ailleurs installé la 4.1 sur un Raspberry pour sortir certains de risques de ma prod.
Reste à déterminer la gate que sera dessus. PI, Wifi, Usb ou voire même du conbee, mais ça sortirait de ce projet.

**Comment by tcharp38** [comment]
Oui c'est courageux si tu n'as qu'un systeme.
De mon cote j'ai plusieurs OrangePi zero, qq capteurs Xiaomi et pizigate pour faire qq tests sans risque à un prix defiant toute concurrence (10e env pour l'OPI ou les capteurs, 29e pour la zigate). De quoi jouer.

**Comment by mickadam29** [comment]
Je vais m'y mettre. Ce jour je reçois des modules de développement à base CC2530. Je vais pouvoir, je l'espère, développer un ou deux modules Zigbee sépcifiques. Et donc il me faut absolument un environnement de recette.

**Comment by mickadam29** [comment]
Pour en revenir à la mise à jour. Rien ne se passe chez moi. Jeedom me dit qu'il y a une maj master de Abeille, mais quand je fais mettre à jour, la roue crantée tourne dans le vide. Pas de log Abeille_update

**Comment by tcharp38** [comment]
Je n'ai pas trop suivi les modifs de Kiwi de ce cote mais clos ce sujet, et s'il n'existe pas deja, ouvre en un specifique. Merci

**Comment by mickadam29** [comment]
Sauf que du coup je ne sais pas si ta modif fonctionne. Je considère que oui et j'ouvre un sujet spécifique

**Comment by mickadam29** [comment]
1/ Version (AbeilleVersion.inc)
===================================
dev_tcharp38, 2020-12-17 15:50:37

2/ Linux
============
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

@tcharp38 

Je réouvre car visiblement le sujet est toujours d'actualité avec la version à jour d'hier à 15h50

![image](https://user-images.githubusercontent.com/36518012/102609978-b2db1200-412c-11eb-828a-b5315cdbfcc3.png)

**Comment by tcharp38** [comment]
Ha oui mais pas la meme erreur. La il s'agit de la gestion des processus. @edgd1er est dessus.

**Comment by mickadam29** [comment]
Toi tu évoquais le log Parser ?  Car visiblement les alertes précédentes ne sont pas notifiées
Ne générant pas de dysfonctionnements visibles, je vais attendre que @edgd1er s'occupe du problème.
A priori, il ne devrait pas y avoir de maj de firmware tout de suite.

**Comment by tcharp38** [comment]
Je parlais du log parser à quel moment ? Pas dans ce sujet en tout cas non ?
Cote process, on n'a toujours pas de solution propre qui ne genere pas de messages mais à priori il n'y a rien de bloquant sur le master aujourd hui.

**Comment by mickadam29** [comment]
> J'ai vu ces erreurs. j'ai poussé un correctif hier que Kiwi a déja mergé sur le master.
Je pensais que tu parlais des erreurs php. Mais probablement qu'elles ne sont pas liées à l'interrogation du firmware

Donc j'ai mal interprété. Pas grave dans la mesure où la solution Zigate/Abeille est fonctionnelle.
