### ISSUE TITLE
Intégration matériel prochaine MAJ

### ISSUE THREAD

**Issue by Alex-57-FR** [KiwiHC16/Abeille#1569]
Salut Kiwi,
j'ai reçu 1 équipement zigbee qui n'est pas compatible avec abeille directement, un module MS-104Z nouvelle génération avec le bouton de réinitialisation dessus, il est reconnu sous le module TS011F par la zigate et il fonctionne avec les commandes du module TS0011 et on peux lui mettre l'image du TS0121.
Bonne journée
Alex
[TS011F.zip](https://github.com/KiwiHC16/Abeille/files/5715173/TS011F.zip)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
As tu une image pour cet equipement ?

**Comment by KiwiHC16** [comment]
Modele ajouté à Abeille

Manque image

**Comment by KiwiHC16** [comment]
Pardon je n avais pas vu, image du TS0121.
Ok je clos.
