### ISSUE TITLE
Config plugin, mettre un menu deroulant pour choisir l objet sans avoir a connaitre son Id.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#157]

**Comment by KiwiHC16** [comment]
Objet parent

Dans chaque objet on a cette liste déroulante pour rattacher l objet a son parent.

**Comment by edgd1er** [comment]
Pb cité dans #172. Rattachement aiu plugin ou individuel pour chaque abeille ?

**Comment by KiwiHC16** [comment]
Closed as per #172
