### ISSUE TITLE
Afficher ttyXXXX sur page santé

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1572]
![Capture d’écran 2020-12-18 à 23 14 21](https://user-images.githubusercontent.com/8549674/102666263-c4e99e80-4186-11eb-9d6f-bd1aa2de0d23.png)
![Capture d’écran 2020-12-18 à 23 14 31](https://user-images.githubusercontent.com/8549674/102666275-cadf7f80-4186-11eb-842a-b83e7ae36494.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by tcharp38** [comment]
Et tu comptes en afficher combien et quoi vu que tu supportes jusqu"a 10 zigates ?

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

A ce sujet, mais je crois que nous n'êtes pas parvenu à le résoudre, je pense qu'il faudrait parvenir à s'assurer que Abeille communique toujours avec la zigate et donc soit toujours rattaché au bon port usb. Au redémarrage parfois, USB0 ou USSB1 et cela crée un conflit avec d'autres périphériques USB. Sous linux, sans être expert, je crois qu'il existe les alias pour nommer les ports USB. Il faudrait donc pouvoir gérer l'alias PORT-ZIGATE. Lui même rattaché à USB0 ou 1 par le système au démarrage et selon l'identifiant Constructeur/modèle de ce qui est attaché au port physique.  Dans la liste de sélection, n'apparaisse que les dev physique. Peut-être une piste à creuser en même temps que de l'afficher comme tu le souhaites. Mais c'est peut-être aussi un bridage jeedom. @tcharp38, je pense que @KiwiHC16  ne parle que des zigates USB. Pas certain que l'utilisateur lambda en possède beaucoup.  Bon courage.
