### ISSUE TITLE
Pas de Graphique réseaux et messages mystérieux et pas de affichage batterie snzb-04 et timeout

### ISSUE THREAD

**Issue by shadsnob** [KiwiHC16/Abeille#1573]
1/ Version (AbeilleVersion.inc)
===================================
beta, 2020-12-15 11:20:57

2/ Linux
============
["Raspbian GNU\/Linux 10 \\n \\l","","\u001b[9;0]"]
["Linux raspberrypi 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU\/Linux"]

3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

Toujours pas de vue de la part dans la table des nœuds même en appuyant sur le bouton refresh pas de graphique non plus,
Et découverte d'un message en haut a droite dans un triangle gris et autre dans options modèles, pas de batterie pour le sonoff snzb-04 et problème de timeout qui me gonfle car on dirait que la zigate ou le plugin ne garde pas le lien entre le matériel et jeedom en vert comme avec mosquitto.

![Sans titre](https://user-images.githubusercontent.com/55192541/102687455-850ad180-41ef-11eb-9e0b-100a12eed9d7.png)
![Sans titre2](https://user-images.githubusercontent.com/55192541/102687456-86d49500-41ef-11eb-9df5-32ae43829191.png)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5719223/Abeille.txt)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5719224/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/5719225/AbeilleConfig.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5719226/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5719228/AbeilleSerialRead1.log)

**Comment by tcharp38** [comment]
Salut
Le type de réponse suivant est complement "non sens".

> Type=804E/Management LQI response, SQN=6D, Status=C1, NeighbourTableEntries=00, NeighbourTableListCount=00, StartIndex=05, SrcAddr=0000

Ta zigate est dans un sale etat.
Elle dit ne connaitre personne (aucun equipement dans son reseau).
Du coup Abeille ne peut rien faire avec ca.
Pour moi la cause de tes soucis est plutot passage en 3.1d (peut etre via plusieurs AR 3.1c 3.1d ?) mais clairement aucune update d'Abeille ne fera avancer le schmilblick.
@KiwiHC16 Une idée ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Il y a beaucoup trop de sujets dans un et je suis complément perdu entre ce qui fonctionne et ce qui ne fonctionne pas.
Rien que le sujet contient 4 questions:

- Pas de Graphique réseaux (@tcharp38 , c est le StartIndex=05 donc ça semble ok si 4 équipements )
- messages mystérieux
- pas de affichage batterie snzb-04
- timeout

Désolé mais je vais avancer pas à pas dans mes questions pour cerner les soucis.
Première question, est ce que globalement le système fonctionne ? Oui combien d'équipements sur le réseau zigbee ?

**Comment by shadsnob** [comment]
le système fonctionne et j'ai que un seul équipement zigbee dessus

**Comment by KiwiHC16** [comment]
- Pas de Graphique réseaux
Peux tu faire une capture ecran pour clarifier ce point ?

**Comment by KiwiHC16** [comment]
@shadsnob , quelle est la situation ?
As tu essayé avec la dernière stable.

**Comment by KiwiHC16** [comment]
Clos du fait du nouveau issue.
