### ISSUE TITLE
Nouvel équipement 'TRADFRIbulbE27WSclear950lm' inconnu. Utilisation de la config par défaut. [Modelisation]

### ISSUE THREAD

**Issue by Disciplus86** [KiwiHC16/Abeille#1574]
Bonjour,
Je viens de retrouver dans mon basard une ampoule TRADFRI bulb E27 WS clear 950lm.
https://zigbee.blakadder.com/Ikea_LED1546G12.html

Toutefois, elle n'est pas reconnue dans abeille.
J'utilise jeedom 4.0.61 et le pluguin abeille stable, 2020-12-01 15:00 

Avez vous une solution? Si oui ce serai chouette

Sinon super pluguin :D

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Merci pour le retour encourageant.

Il faut lui faire son modele pour cela:

Pourrais tu mettre le plugin en débug, redémarrer le daemon, vider le log AbeilleParser, supprimer l objet (si existant), faire une inclusion de la prise, partager le log AbeilleParser.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-12-28 à 13 20 10](https://user-images.githubusercontent.com/8549674/103213942-74550c80-490f-11eb-9568-4fc456cf1892.png)

**Comment by KiwiHC16** [comment]
Peux tu faire les manips proposer dans le post précédent et partager le résultat ?

**Comment by KiwiHC16** [comment]
Modele dans master.
