### ISSUE TITLE
Mise à jour PIZIGATE 3.1d

### ISSUE THREAD

**Issue by StephaneG38** [KiwiHC16/Abeille#1576]
Bonjour,
Je n'arrive pas à mettre à jour ma Pizigate de 3.1c à 3.1d.
Si je lance mise à jour avec la dernière version d'abeille (2020-12-05 01:00:13) j'ai le message si dessous 
`[2020-12-22 08:46:36] Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0
Vérifications préliminaires
= ERREUR: Le programmateur Jennic n'est pas exécutable !
=         /var/www/html/plugins/Abeille/Zigate_Module/JennicModuleProgrammerRPI3`

Merci par avance
Stéphane

**Comment by tcharp38** [comment]
Salut
Sais tu acceder à ce repertoire via SSH ?
Je ne sais pour quelle raison mais il doit manquer les droits d'execution pour le fichier "JennicModuleProgrammerRPI3".
Un "chmod +x JennicModuleProgrammerRPI3" devrait resoudre le pb.

**Comment by StephaneG38** [comment]
@tcharp38 Salut et merci pour ta réponse. Je peux aller sous Puty en SSH mais tu peux me mettre le chemin type cd ....
Sinon par jeexplorer ?
Merci pour ton aide
stéphane

**Comment by tcharp38** [comment]
Le chemin tu l'avais dans ton erreur "/var/www/html/plugins/Abeille/Zigate_Module/JennicModuleProgrammerRPI3".
J'ai pensé aussi à Jeexplorer mais je vois pas la possibilite de modifier les droits. Tu la vois ?
Dans tous les cas fais un "ls -l JennicModuleProgrammerRPI3" qu'on voit les droits actuels

**Comment by StephaneG38** [comment]
Ca ne marche pas 
`pi@raspberrypi:~ $ cd /var/www/html/plugins/Abeille/Zigate_Module/
pi@raspberrypi:/var/www/html/plugins/Abeille/Zigate_Module $ chmod +x JennicModuleProgrammerRPI3
chmod: changing permissions of 'JennicModuleProgrammerRPI3': Operation not permitted
pi@raspberrypi:/var/www/html/plugins/Abeille/Zigate_Module $ ls -l JennicModuleProgrammerRPI3
-rw-r--r-- 1 www-data www-data 24016 Dec 22 08:36 JennicModuleProgrammerRPI3`

**Comment by tcharp38** [comment]
Ok, surement besoin d'un sudo alors
"sudo chmod +x JennicModuleProgrammerRPI3"
Tu dois avoir le mot de passe root.

On voit bien que ce fichier n'est pas executable.

**Comment by StephaneG38** [comment]
Super ca marche !!
Je suis pas très doué sous linux.
Merci à toi et passe de bonne fêtes !
Stéphane

**Comment by tcharp38** [comment]
Bonne fetes !

**Comment by StephaneG38** [comment]
Merci !
Par contre ma telecommande loratap 3 bouton ne fonctionne toujours pas !
[https://github.com/KiwiHC16/Abeille/issues/1406](url)
Tu peux m'aider ?

**Comment by tcharp38** [comment]
Ha la non désolé. Mes connaissances vont pas jusque la :)
Faut attendre @KiwiHC16 mais si le sujet specifique n'existe pas cree en un.

**Comment by StephaneG38** [comment]
OK
merci
Par contre je m'appercois que aucun capteur ne fonctionne !!
Je vais essayé de les inclure de nouveau
C'est galère !
Merci quand même

**Comment by tcharp38** [comment]
Alors la tu as peut etre un souci avec la 3.1d.
J'etais entousiaste au debut mais il y a beaucoup trop d effets de bord incomprehensibles.
Ne test que sur un capteur à la fois et prend celui avec lequel tu peux declencher un envoi (par ex, capteur de porte).
Tu dois voir un message de ce capteur remonter via AbeilleParser

**Comment by StephaneG38** [comment]
Certain capteur marche sans intervention et d'autre je dois lancer une inclusion. 
Mais la fameuse télécommande 3 boutons ne veux rien savoir !
Je vais voir avec @KiwiHC16

**Comment by tcharp38** [comment]
En dehors de cette telecommande pour laquelle je sais qu'il y a un boulot en cours, tu n'as pas de regression au passage 3.1d sur les autres capteurs ?

**Comment by StephaneG38** [comment]
Comme j'ai 23 capteurs différents il faut que je fasse le tour pour refaire une inclusion pour chacun. C'est un peux long !
Mais de toute façon pas trop le choix si j'ai bien compris les mise à jour Abeille seront seulement sur les 3.1d ?

**Comment by tcharp38** [comment]
non non la 3.1d n'est pas obligatoire pour Abeille.
Moi je suis retombé en 3.1c avec effacement complet pour retrouver un systeme stable.

Par contre en y refelchissant pour toi oui, à cause de loratap qui a besoin des fonctionalites 3.1d.
Du coup oui je crois que t'as pas le choix

**Comment by StephaneG38** [comment]
Ok merci pour ton aide 
Stéphane
