### ISSUE TITLE
Intégration Télécommande 3 boutons Loratap #1406

### ISSUE THREAD

**Issue by StephaneG38** [KiwiHC16/Abeille#1577]
Bonjour @KiwiHC16 ,
Je reviens sur mon problème avec cette télécommande.
Je viens de faire la Mise à jour du Plugin (2020-12-05 01:00:13) et du firmware de ma PIZIGATE de 3.1c à 3.1d.
La télécommande ne fonctionne toujours pas !
Merci par avance pour ton aide !
Stéphane

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
As tu passé la zigate en mode hybride (voir en fin de page avec toutes les abeilles).

**Comment by StephaneG38** [comment]
Hello,
Merci pour l'info. 
J'ai cliqué sur  "set hybride mode Z1" puis refait une inclusion et la télécommande semble fonctionner.
Par contre il faut appuyer 2 fois pour avoir 1 et 1 fois pour revenir à 0. C'est normal ? C'est configurable ?
Je dois laisser en mode hybride ? Quelle répercussion pour les autres équipements ?
Merci par avance,
Stéphane

**Comment by KiwiHC16** [comment]
Mode Hybride est supporté par les dernieres versions d'Abeille et ne pas changer le fonctionnement des autres équipements.

```
Par contre il faut appuyer 2 fois pour avoir 1 et 1 fois pour revenir à 0. C'est normal ?
```
D après mes souvenir oui.

```
C'est configurable ?
```
Non, passe par un virtuel/scenario si tu as besoin.

Tu dois aussi avoir appui long (>5s) si be souvenir sont bons.

**Comment by StephaneG38** [comment]
@KiwiHC16  Bonjour et grand merci pour ton aide !!
Je vais regarder pour passer avec des virtuels.
Passe de bonnes fêtes 
Stéphane
