### ISSUE TITLE
Aqara SmartPlug

### ISSUE THREAD

**Issue by ThierryViens** [KiwiHC16/Abeille#1578]
Bonjour, 

J'ai acheté des prises Aqara SmartPlug, modèle SP-EUC01, voici les specs https://www.zigbee2mqtt.io/devices/SP-EUC01.html et https://zigbee.blakadder.com/Xiaomi_SP-EUC01.html
Lors de l'ajout de l'appareil,  il me dit 
2020-12-22 21:32:13|Abeille|Nouvel équipement ‹ plug.maeu01 › inconnu. Utilisation de la config par défaut.

2020-12-22 21:32:13|Abeille|Création d un nouvel objet Abeille (Abeille1/5EC7) en cours, dans quelques secondes rafraîchissez votre dashboard pour le voir.
Voici le log du plugin en debug, les autres logs sont vides.. il n'y a que le log Abeille qui a un peu d'infos : 
[Abeille2.txt](https://github.com/KiwiHC16/Abeille/files/5731937/Abeille2.txt)

Merci d'avance pour votre aide.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
```
plug.maeu01
```
n'est pas encore connu d'Abeille. Il faut lui faire son modèle.

**Comment by KiwiHC16** [comment]
Fichier introuvable: LOM02.json

**Comment by KiwiHC16** [comment]
Pourrais tu mettre le plugin en débug, redémarrer le daemon, vider le log AbeilleParser, supprimer l objet pour cette prise, faire une inclusion de la prise, partager le log AbeilleParser.

**Comment by ThierryViens** [comment]
Salut, c'est fait, le "abeilleparser" est vide, par contre il y a des remontées dans "abeilleparser.log", le voici.
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5749812/AbeilleParser.log)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5749813/Abeille.txt)

**Comment by KiwiHC16** [comment]
Abeille.txt
```
[2020-12-29 07:42:11][DEBUG] : value:lumi.plug.maeu01 / trimmed value: ->plug.maeu01<-
```
n existe pas dans les modeles actuels.
```
[2020-12-29 07:42:17][DEBUG] : message(topic='Abeille1/5171/SimpleDesc-01-DeviceDescription', payload='zigbeeSmart Plug')
```

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-05 à 17 03 15](https://user-images.githubusercontent.com/8549674/103668877-e95fbc00-4f77-11eb-88cf-0d1ef287c1ba.png)

**Comment by KiwiHC16** [comment]
Le log AbeilleParser est très court. Il y eu une rotation de log et on n a pas les infos.
Pourrais tu refaire la manip ?

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2267

**Comment by KiwiHC16** [comment]
Oui si possible. Sinon dans le lien ci dessus, il y a plein d info pour commencer. Des que j ai du temps....

**Comment by ThierryViens** [comment]
Ok je vais le faire, par contre le 2e lien c'est du chinois écrit en espagnol pour moi :-)

**Comment by KiwiHC16** [comment]
Je mis dans le master un modele sur la base d une autre prise mais je ne peux pas tester. Sera dispo dans la stable dans 15 jours.

**Comment by ThierryViens** [comment]
Hello, merci beaucoup, j'attends patiemment. Si d'ici là tu veux que je teste quelque chose n'hésites pas, j'en ai 2 branchées et une dans la boite encore.
Bonne journée.

**Comment by KiwiHC16** [comment]
Tu pourras tester soit avec la beta de lundi soit avec la stable du lundi en 15.

**Comment by ThierryViens** [comment]
Alors je teste lundi et je te donne un petit feedback :-) Merci en tous cas

**Comment by ThierryViens** [comment]
Hello, petit feedback comme prévu, la prise est bien reconnue et je peux la piloter. Je n'ai pas de consommation pour l'instant mais ce n'est pas le plus important pour l'instant :-) Merci pour ton travail
![image](https://user-images.githubusercontent.com/76496856/106514922-30889080-64d5-11eb-9412-d85771fb3776.png)

**Comment by KiwiHC16** [comment]
Super c est un bon début.

**Comment by KiwiHC16** [comment]
Pour l etape suivante il faudrait que tu recuperes l adresse de la prise:
![Capture d’écran 2021-02-03 à 17 47 35](https://user-images.githubusercontent.com/8549674/106780055-e7a51900-6647-11eb-8295-f12cb545dc74.png)
Dans cet exemple AAEE
![Capture d’écran 2021-02-03 à 17 49 14](https://user-images.githubusercontent.com/8549674/106780305-22a74c80-6648-11eb-8af5-e4f2a89a7e6b.png)

Clic sur les deux commandes l une apres l autre et partages ce qui remonte dans AbeilleParser (plugin en mode debug)


Que tu rendes la ruche visible ainsi que les commandes: ActiveEndPoint et SimpleDescriptionRequest, cela donne:

**Comment by GaelM01** [comment]
Bonsoir,
je sais pas si ça peut aider.
[AbeilleParser(1).log](https://github.com/KiwiHC16/Abeille/files/5961766/AbeilleParser.1.log)
Si j'ai bien compris, par contre j'ai du appuyer 2 fois sur les commandes donc si il faut autre chose ...

**Comment by KiwiHC16** [comment]
```
[2021-02-10 22:55:30][debug]   ManufacturerName='LUMI', trimmed='LUMI', {"Abeille1\/D73B":{"time":1612964301,"ManufacturerName":"_TZ3000_riwp3k79"},"Abeille1\/2DDB":{"time":1612994130,"ManufacturerName":"LUMI"}}, [Modelisation]
```

Pas beaucoup d infos.

Il faudrait faire une inclusion avec la version stable qui sortira lundi en 15 car je viens de faire des corrections récemment.

**Comment by GaelM01** [comment]
Bonsoir.
Voici l'AbeilleParser après suppression de la prise, redémarrage du daemon et inclusion de la prise.
[AbeilleParser(1).log](https://github.com/KiwiHC16/Abeille/files/6005478/AbeilleParser.1.log)
Désolé de la réponse tardive, j'ai encore un peu de mal avec Github.
Merci encore pour ton travail.

**Comment by KiwiHC16** [comment]
```
[2021-02-18 20:44:04][debug]   ManufacturerName='LUMI', trimmed='LUMI', {"Abeille1\/CD19":{"time":1613677444,"ManufacturerName":"LUMI"}}, [Modelisation]
```
Pas grand chose dans le log ;-(

Il a ete pris trop tard apres la manip.

Peux tu re-essayer ?

**Comment by GaelM01** [comment]
Voilà
[AbeilleParser(3).log](https://github.com/KiwiHC16/Abeille/files/6111096/AbeilleParser.3.log)
Là j'ai fait le plus vite possible.

**Comment by MonsieurFlal** [comment]
hello @KiwiHC16 
as tu pu checker ce probleme de conso/puissance instant sur cette prise ?
je pense qu'il y a le même probleme sur la prise CN (lumi.plug) mais ceci est une autre histoire. déja, cette prise ronde aqara ^^
merci pour le retour !

**Comment by GaelM01** [comment]
@tcharp38, peux-tu me dire si le AbeilleParser a les bonnes infos pour finir le model?

**Comment by tcharp38** [comment]
Salut @GaelM01 
Si je comprends bien le pb restant est le retour de mesure de conso/puissance.
C'est bien ca?

Je viens de voir rapidement et pour ca il manque un peu de support dans Abeille pour le cluster "smart energy".
De + je n'ai pas ce type d'equipement ou similaire sous la main.
Par hasard tu saurais et aurais de quoi sniffer le reseau ?

**Comment by GaelM01** [comment]
Heu... J'ai commencé il y a peu et sniffer le réseau c'est pas dans mes cordes :x.
J'ai juste une zigate et quelques prises et modules de marques différentes ...
Du coup, j'avais juste répondu à KiwiHC16 pour les infos qu'il demandait.
Sinon, oui, mesure conso/puissance et (d'après le widget de la smartplug) une température ^^.
Mais en soit le retour d'état et le on/off pour le moment me suffisent, c'était pour aller un peu plus loin ^^
Merci pour votre boulot à tous les deux.

**Comment by tcharp38** [comment]
Ok, je vais creuser ca en tache de fond. Je viens de me commander une prise avec mesure de conso alors ca devrait m'aider.
Pourquoi parles tu de température ? Il y a un capteur de temp sur cette prise ?

**Comment by GaelM01** [comment]
![Capture d’écran 2021-05-15 053949](https://user-images.githubusercontent.com/78859197/118346994-0ddc2e00-b540-11eb-807f-22e0f2b17dd0.png)
La présentation sur domadoo dit qu'il y a une protection contre la surchauffe et le widget de la prise affiche une mesure de température ensuite je suis pas sur que ce soit une sonde de température vraiment ^^'

**Comment by oywino** [comment]
Did you manage to get this working?
I have the _lumi.plug.maeu01_  and it shows up in deConz like this:
![image](https://user-images.githubusercontent.com/18447119/121734587-41858600-caf5-11eb-967b-9bb71fd18359.png)
With the following FCC0 cluster info:
![image](https://user-images.githubusercontent.com/18447119/121734702-70036100-caf5-11eb-9115-549071ef3a96.png)
and the following 000C cluster info:
![image](https://user-images.githubusercontent.com/18447119/121734810-8f9a8980-caf5-11eb-8172-d055aef3f2a3.png)

I tried to pair it from Phoscon both as a light and as a sensor. The result is identical.
It shows up in Home Assistant, but only as an on/off switch. No parameters for either consumption or or any other additional info.

Any help you can offer is highly apprechiated. 
All my SW and FW are updated to the latest versions, except for the device itself. I have no idea how to do that.

**Comment by tcharp38** [comment]
Hello @oywino 
Support for this plug is neither completed on our side so far.
But keep in mind this forum is dedicated to Abeille plugin (for Zigate bridge) and not for Deconz.

Anyway I need to restart on this subject so thanks to raise that up.

**Comment by oywino** [comment]
Sorry for my misunderstanding 😶
Anyway, after initiating another round of "detections" from Phoscon, now using _Sensor_ instead of _Light_,  while keeping the above registration and keeping the device powered on, and simultanously frenetikally clicing the "Read" button on the Basic Cluster, all of a sudden the remaining "lost" sensors did show up, and now everything seems just fine (?)
![image](https://user-images.githubusercontent.com/18447119/121769000-7fb88f00-cb61-11eb-876e-888d246c2efa.png)
![image](https://user-images.githubusercontent.com/18447119/121769098-05d4d580-cb62-11eb-980d-2f99d1aae385.png)

**Comment by Brugal21** [comment]
Salut @tcharp38 

Tu as reçu ta prise avec mesure de conso ? Si oui as-tu pu avancer sur le sujet de la remontée de la conso/puissance pour cette prise ?

Merci de ton retour

**Comment by tcharp38** [comment]
Salut
Oui j'ai ma prise Tuya. Elle semble bien  fonctionner. Le seul truc qui me chagrinne est le total de puissance reporté. Pas compris quand est ce qu'il etait remis à 0.

![image](https://user-images.githubusercontent.com/35221038/123825660-62284b00-d8ff-11eb-8d1f-01d64f636ad6.png)

Tu as une aqara smartplug aussi ?
Quel est le status aujourd hui ?

**Comment by Brugal21** [comment]
Salut @tcharp38,

Oui j'ai aussi une prise aqara, celle là :

https://www.domadoo.fr/fr/peripheriques/5385-xiaomi-aqara-prise-connectee-zigbee-30-smart-plug-sp-euc01.html

Je les ré inclus récemment le 23/06. Pas de soucis d'inclusion. Depuis elle ne remonte aucune valeur sur la conso, puissance, intensité et tension. Il y a aussi la température dans les commandes créées mais je sais pas si quelque chose doit remonter...

Pour les commandes on, off et état ça fonctionne.

![image](https://user-images.githubusercontent.com/55110607/123838970-e0d7b500-d90c-11eb-9ee0-43b42a78cfdd.jpeg)

![image](https://user-images.githubusercontent.com/55110607/123838982-e46b3c00-d90c-11eb-9ae9-28ce4635ba10.jpeg)

Pour la conso elle ne peut pas revenir à zéro, c'est un compteur totalisateur. Du coup il compte et c'est tout. Il faut à mon avis intervenir directement sur le module pour le remettre à zero.
J'ai des relais aqara 2ch, il y a aussi une conso. Quand je le supprime d'abeille et que je le reinclus, la valeur du compteur reviens à la valeur au moment de la suppression,il la mémorisé...
Enfin c'est ce que je pense 😉

**Comment by tcharp38** [comment]
@Brugal21 J'essaie de reprendre le sujet.
Peux tu
- virer le fichier core/devices/plug.maeu01/plug.maeu01.json
- redemarrer les démons
- et refaire une inclusion
- et me filer le package de logs

Ca devrait donner des choses dans discover.log.
Merci

**Comment by Brugal21** [comment]
Ok, merci de t'en occuper ;)
J'ai fait la manip.

L'equipement s'annonce : (adresse courte : F3CF)

![image](https://user-images.githubusercontent.com/55110607/124019389-49945f80-d9e9-11eb-9d0c-bead3b94c70a.png)

L'objet crée ne comporte aucune commande : 

![image](https://user-images.githubusercontent.com/55110607/124019424-5749e500-d9e9-11eb-9447-d89a5f0a7156.png)

Et le package de log ne fait pas apparaitre de discover.log

[AbeilleLogs-210630.tar.gz](https://github.com/KiwiHC16/Abeille/files/6743491/AbeilleLogs-210630.tar.gz)

**Comment by tcharp38** [comment]
Si il est toujours reconnu comme  'plug.maeu01' c'est surement que tu n'as pas redemarré Abeille apres avoir supprimé le JSON.

> EQ is supported with 'plug.maeu01' identifier

Du coup il ne tente pas de decouverte car pense qu'il est deja supporté.

**Comment by Brugal21** [comment]
Il me semblait que si, mais non ... :)
Bon du coup je refais la manip. Je supprime aussi le répertoire "plug.maeu01".

![image](https://user-images.githubusercontent.com/55110607/124022902-b578c700-d9ed-11eb-9b9c-6710b12fcc0c.png)

Voila le package de logs avec le discover.

[AbeilleLogs-210630_3.tar.gz](https://github.com/KiwiHC16/Abeille/files/6743652/AbeilleLogs-210630_3.tar.gz)

C'est mieux en suivant précisément ce que tu demandes... merci pour tout

**Comment by tcharp38** [comment]
Tiens, a tester.
[1578.zip](https://github.com/KiwiHC16/Abeille/files/6747504/1578.zip)

Le fichier plug.maeu01.json est pour core/config/devices/plug.maeu01/
et les autres pour core/config/commands

Relancer Abeille
Refaire une inclusion

**Comment by Brugal21** [comment]
Salut,

merci pour les fichiers. Je viens de tester, j'ai réinclus la prise : pas de problème d'inclusion.
Toutes les commandes se sont créées. Mais rien ne remonte sur la valeur puissance et la consommation. 
Je peux piloter la prise (on et off) et j'ai le retour d'état.

La prise est inclus depuis 45min avec une charge branchée dessus : 

![image](https://user-images.githubusercontent.com/55110607/124119261-953f1b80-da72-11eb-9219-cb0f9eff693d.png)

Je te joins les logs de l'inclusion : device inclus à 12:54:56 - adresse courte : A19B

[AbeilleLogs-210701.tar.gz](https://github.com/KiwiHC16/Abeille/files/6747831/AbeilleLogs-210701.tar.gz)

A dispo pour tout autre besoin.

**Comment by Brugal21** [comment]
Je viens de faire quelques essais avec les nouvelles commandes créées.

Je regarde la valeur des infos : UnitOfMeasure / Multiplier / Divisor / SummationFormatting : rien ne remonte, aucune valeur.

Du coupe j’exécute les actions suivantes : 

- get-0702-UnitOfMeasure
- get-0702-Multiplier
- get-0702-Divisor
- get-0702-SummationFormatting

Je re-regarde les valeurs des infos, et là, j'ai des valeurs : 
 - UnitOfMeasure = 0
 - Multilplier = 0
 - Divisor = 3
 - SummationFormatting = 23

Je reteste les valeurs des infos Power et TotalPower : toujours rien, aucune valeur ne remonte.

**Comment by tcharp38** [comment]
Nouvelle tentative.
J'ai ajouté des config de reporting. On va voir ce qui passe ou pas.
Donc apres decompression meme combat
- redemarrer Abeille
- refaire une inclusion
- package de logs

Nouveau package: 
[1578.zip](https://github.com/KiwiHC16/Abeille/files/6748761/1578.zip)

**Comment by tcharp38** [comment]
@Brugal21 
On fait le point sur ce sujet ?

**Comment by tcharp38** [comment]
Je clos ce vieux sujet.
A réouvrir si besoin.
