### ISSUE TITLE
Plugin Abeille non confirmé compatible v4

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1579]
A priori il l'est mais lors de la mise à jour l'utilisateur est averti que le plugin n'est pas confirmé pour la v4.
A corriger pour faire disparaitre ce message qui peut engendrer des questions inutiles.

![image](https://user-images.githubusercontent.com/35221038/103000989-69bfff00-452c-11eb-920c-79bba1ac41a9.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Ou trouves tu cette capture d'écran ? Quel est le chemin pour y accéder ?

**Comment by tcharp38** [comment]
Via le "centre de mise à jour" en v3
puis

![image](https://user-images.githubusercontent.com/35221038/103240552-f154a600-4950-11eb-9e20-a1014e5105b7.png)

puis

![image](https://user-images.githubusercontent.com/35221038/103240578-029db280-4951-11eb-9250-c5bbd661311d.png)

**Comment by tcharp38** [comment]
A verifier une fois que la prochaine stable est dispo

**Comment by KiwiHC16** [comment]
Commit 72b01b3baeb4a65ef4c54b54b5bcac3b31978bc2 devrait resoudre le sujet.

**Comment by KiwiHC16** [comment]
Est ce que quelqu'un peu tester ? (je n'ai pas de V3 depuis des mois).

**Comment by tcharp38** [comment]
C'est bon.
![image](https://user-images.githubusercontent.com/35221038/105387537-f20dee80-5c15-11eb-8717-cf983eddb244.png)

je clos

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-24 à 22 10 07](https://user-images.githubusercontent.com/8549674/105643603-1c1f1500-5e91-11eb-9421-eb1d207bfe8e.png)
