### ISSUE TITLE
Télécommande Osram mini switch

### ISSUE THREAD

**Issue by olivr2s** [KiwiHC16/Abeille#1580]
Bonjour KiwiHC16,

j'ai une télécommande Osram mini switch 
![image](https://user-images.githubusercontent.com/59806634/103099114-7bc59e80-460d-11eb-93a3-83a0780c2129.png)
https://zigate.fr/produits-osram-compatibles-zigate/compatible/osramswitchmini/
et lors d'une inclusion sur Abeille version master et Zigate en 3.1c, j'ai
"Nouvel équipement 'LightifySwitchMini' inconnu. Utilisation de la config par défaut. [Modelisation]"
Est-il possible d'intégrer cette télécommande dans Abeille ?
Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Effectivement Abeille ne connait pas cette télécommande.
Pourrais tu supprimer l objet dans Abeille s il existe, mettre le plugin en mode début, redémarrer le daemon, et faire une inclusion, ensuite partages le log AbeilleParser.

**Comment by tcharp38** [comment]
Je clos ce point.
J'avais ouvert celui la https://github.com/KiwiHC16/Abeille/issues/2119
Donc en cours.
