### ISSUE TITLE
Inclusion impossible -PIZIGATE-ABEILLE

### ISSUE THREAD

**Issue by Saperlipopette01** [KiwiHC16/Abeille#1581]
Bonjour à tous , 
aprés avoir réglé les problémes de radio avec le chevauchement de cnx WIFI ( maintenant réglé en 15 sur la PIZIGATE et 6 pour wifi),   j’ai mis à la place définitive le PI4 ( antenne externe sur un plan de masse pour la pizigate , wifi et Bt desacivé sur le PI4 ). sur les 13 capteurs aqara que j’ai , toujours la moitié non joignable , j’ai essayé de les réinclure a proximité immédiate de la pizigate , rien n’y fait , impossible de les réinclures. Du coup j’ai supprimer tous les objets , bien mal m’en a pris , plus aucuns ne peux s’inclurent …
Soit , pour le moment je n'ai pas de "routeurs" pour fiabiliser le réseau zigbee mais cela n'explique pas la raison pour lequel je ne peux plus rien réinclure ou inclure.  
Je n’y comprend plus rien … Tout essayé , changé de cnx , reinstallé le plugin , reflashé en 3.1c la pizigate , toujours impossible d’inclure quoi que ce soit et pourtant le led bleu change de rythme sur la pizigate a la reception d’une info aprés appui sur le bouton du capteur aquara …

C’est une vrai galére…
 j'en perd vraiment mon latin  et j'y passe un temps extraordinaire pour faire fonctionner une quinzaine de capteurs  d'ouvertures et 1 capteurs IR aquara.

Merci pour votre aide .

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Salut Saperlipopette01,
Peux tu mettre le daemon en debug, le redémarrer, vider le log AbeilleParser et AbeilleSerial.
Mettre en inclusion, appui 7s sur le bouton lat d'un capteur de porte xiaomi pour inclusion.
Partager ce qu'il se passe et les lao AbeilleParser et AbeilleSerial.

**Comment by KiwiHC16** [comment]
```antenne externe sur un plan de masse pour la pizigate```
Peux tu partager une photo du montage ?

**Comment by Saperlipopette01** [comment]
Bonjour  , tout d'abord merci pour le retour et par avance, pour l'aide :-) 

J'ai fait les actions que tu m'a demandé , et voici les resutats :
Navré sur le formatage n'est pas au top mais je ne maitriuse pas aussi bien que vous l'outil GitHub.
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5747758/AbeilleParser.log)
[AbeilleSerialRead1 .log](https://github.com/KiwiHC16/Abeille/files/5747759/AbeilleSerialRead1.log)

entre temps , et je ne sais pas pour quel raison des capteurs que j'avais essayé d'inclure hier sont apparu par magie avec 3 heures de retard dasn le dashboard , j'en ai profité ce matin pour essayer d'en inclure d'autres , et pour quelque uns cela a fonctionné avec plus ou moins de "retard" a l'inclusion ( de instentané à +/- 10 mn ) 

Pour ce qui est de la photo  , ce n'est qu'une maquette bidouille  fait avec deux barquettes en alu de 0,5 l , à l'analyseur de spectre je coupe déja 80% du rayonnement :
![1609070082017](https://user-images.githubusercontent.com/76660073/103223529-bb023100-4926-11eb-8612-0eaa3faf5405.jpg)
Si je suis satisfait du resultat j'usinerais un boitier hadoc en alu pour y integrer la carte du PI4 sur colonette et le disque MVNe.

**Comment by Tonio16** [comment]
Ajout impossible sur Zigate déportée. #1593

@Tonio16, je prefere garder les deux discussions en parallel sinon je me perds. Je mets la ref pour pouvoir passer facilement d un sujet à l autre.

**Comment by KiwiHC16** [comment]
@Saperlipopette01:
- comment as tu fait le cablage de l antenne ? Est ce un PiZigate sur laquelle tu as soudé une antenne ?
- Tu as le wifi qui émet dans la boite ?
- Ou fais tu t as mesure à l analyseur de spectre ?
- Pour les interference j ai lu des articles expliquant que le signal video peut mettre le basard sur les RPI4 ainsi que l'USB3. Donc pas de video, ni de USB3.

Je regarde les logs.

**Comment by KiwiHC16** [comment]
AbeilleParser est très court (idem AbeilleSerial, tu as du recuperer juste apres un rotation de log) mais on peut voir qu'Abeille parle avec la zigate, que la zigate dit être ne mode Inclusion.
Par contre pas de message sur l arrivée d'un nouvel équipement.

Peux tu refaire la manip pour essayer d avoir plus de log ?

Sinon:
- Tu confirmes que tu n'as pas plus de 15 equipements zigbee sur cette zigate ?
- As tu effacé l'EEPROM quand tu as flashé la zigate ?

**Comment by Saperlipopette01** [comment]
Hello , meilleurs vœux à tous . 

Merci pour ton retour . 
Désolé de la réponse tardive , submergé par le boulot en cette rentrée .
Alors....
- WIFI et BT désactivé sur le PI4 qui supporte la PIZIGATE
- Je ne fait pas d'usage de la vidéo , par contre j'ai un disque EMv en USB3
- Pour l'analyseur de spectre , j'ai un vieux coucou RS qui n'est plus étalonné , par contre la mesure est faite avec un dipôle , et je constate juste qu'avec ma boiboite en alu j'ai 80 % de moins de rayonnement parasite .
- La pizigate est une version avec le connecteur intégré et a été livré avec son antenne . 
- Je confirme que je n'ai d'enregistré que 13 équipements 
-  Effacer l'EEPROM .... heuuuuu nooobs  , je ne sais pas faire .... c'est quoi la manip et qu'est ce que ça implique ? Y a un tuto ?

Je viens de refaire la manip d'inclusion avec le capteur de porte XIAOMI , entre temps j'ai reçu une sirène HEIMAN HS2WD-E que j'ai essayé d'inclure et que ce soit pour l'un ou pour l'autre même résultat , inclusion non exécutée .....

Je précise que TOUS les autres capteurs son fonctionnels et vus ( 1 IR et 11 portes) 

Voila les log :

[AbeilleParser 9_01_2021 Saperlipopette.log](https://github.com/KiwiHC16/Abeille/files/5791559/AbeilleParser.9_01_2021.Saperlipopette.log)
[AbeilleSerialRead 9_01_2021 Saperlipopette.log](https://github.com/KiwiHC16/Abeille/files/5791560/AbeilleSerialRead.9_01_2021.Saperlipopette.log)

 Je débute juste avec jeedom , zigate et consort et mes connaissances en réseaux .

Est ce que cela pourrait être un FW corrompu dans le PIZIGATE ???

J'ai pet être mal lu avant de commencer mon projet ... mais c'est maximum 15 objets ZIGBEE pour une ZIGATE ??????


Avec mes remerciements 

Vincent

**Comment by Saperlipopette01** [comment]
Bon ... j'ai encore essayé aujourd'hui de refaire l'inclusion de mes capteurs et sirène  après avoir refait un flash en 3.1d ( a plusieurs reprises ) rien n'y fait

**Comment by Tonio16** [comment]
Essaye avec un erase eeprom en sus.

**Comment by Saperlipopette01** [comment]
> Essaye avec un erase eeprom en sus.

Je ne sais pas faire sur une PIZIGATE , je ne trouve pas l'info , je n'ai vu des explications que sur une base de zigate USB et windows

**Comment by KiwiHC16** [comment]
Dans les logs que tu partages on voit la zigate discustée avec Abeille mais aucune trace d'arrivée d'un capteur.
Je ne sais pas ou tu as vu que la zigate est limitée à 15 équipements. Dans mes souvenirs c est bien plus.

Je vois que tu es en 3.1D. Ce week end j'ai fait une fausse manip et perdu une prise. Ensuite elle a refusé de se connecter, aussi en 3.1D. Je vais investiguer mon systèmeème et voir si cela a un lien avec ton sujet.

**Comment by Saperlipopette01** [comment]
Heuuuu, Ben c'est toi qui me demande de confirmer si je n'ai pas plus de 15 objets dans un poste. 

Au passage, si tu à l'astuce pour une pizigate de comment faire un ERASE EEPROM je suis preneur... :-)

**Comment by Tonio16** [comment]
De mémoire le Max de la zigate serait 40 sans routeur et 70 avec. 
https://zigate.fr/forum/topic/quantite-maximum-dappareil/

Mais je me demande si le problème de libération de mémoire et vraiment résolu. 

Antoine

**Comment by Saperlipopette01** [comment]
Merci Antoine.

**Comment by tcharp38** [comment]
Qqn connait l'astuce pour savoir ou on en est ? (combien associé en direct ? combien indirect ?)

**Comment by KiwiHC16** [comment]
@Saperlipopette01, ou en es tu sur ce sujet ?

**Comment by Saperlipopette01** [comment]
J'en suis que  :
-PIZIGATE retournée à Fred en échange d'une ZIGATE USB .
- Problèmes résolus en déconnectant les ports USB3 du RPI  ( j'ai un ssd dessus) 
Après ré inclusion de tous les modules ZIGBEE ,depuis tout fonctionne nickel .
conclusion USB3 --> pas avec ZIGBEE
