### ISSUE TITLE
ajout sonoff zbmini

### ISSUE THREAD

**Issue by blattes86** [KiwiHC16/Abeille#1584]
Bonjour tout d'abord merci pour ce plugin qui m'a permis d'enlever la passerelle Ikea qui ne fonctionnait plus chez moi et qui m'a donné l'occasion d'acheter et d'intégrer plein de capteur xiaomi.
J'ai récemment acheté un sonoff zbmini, c'est un produit relativement récent (2 mois) qui permet de contrôler les lumières, il fonctionne sur secteur avec fil neutre.
Je joint une image et le fichier AbeilleParser.log
![sonoff_zbmini](https://user-images.githubusercontent.com/5450173/103216100-7c17af80-4915-11eb-9998-5759114f3c01.jpg)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5747373/AbeilleParser.log)

Encore une fois merci pour le travail, bon courage et bonne fête

**Comment by blattes86** [comment]
petit modification.
En prenant exemple sur  le micromoduleswitch de Legrand, j'ai créé un json pour le zbmini, j'en ai aussi profité pour changer l'image.

[01MINIZB.json.txt](https://github.com/KiwiHC16/Abeille/files/5747537/01MINIZB.json.txt)
![node_01MINIZB](https://user-images.githubusercontent.com/5450173/103219250-732adc00-491d-11eb-9fae-77bb628eb7cc.png)
Si l'un de vous pouvez justre prendre 2 secondes pour vérifier que pour lui le json est bon.
Merci encore pour tout le boulot

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Dans la boite.
