### ISSUE TITLE
Equipements qui rejoignent le réseau sans les avoir fait quitter 

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1589]
Salut @KiwiHC16 

1/ Version (AbeilleVersion.inc)
===================================
master_tcharp38, 2020-12-22 18:02:19

2/ Linux
============
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===============
Zigate: 1
    SW-Application: 0003
    SW-SDK: 031D

Est-ce normal que certains équipements sur pile "disparaissent" et reviennent sur le réseau ?
Concernant le 2ème ID342, c'est un module CC2530 codé avec le firmware de ptvo. Mais l'autre c'est la sonde avec afficheur LCD
Je pense que cela provient de la dernière version du master car je n'avais pas ce genre de message avant. Et ce sont des retours sans que le Zigate soit en mode inclusion.

![image](https://user-images.githubusercontent.com/36518012/103441428-442ea600-4c4e-11eb-8074-dbf0455d0beb.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Il faut que je regarde la code pour voir la condition qui provoque le message.

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/103487871-c4990680-4e08-11eb-8de2-019464dae280.png)

J'en suis à 13 absences/retours pour le capteur qui n'émet que très peu de trames (fréquence aléatoire).
Pour le 273 je l'ai inclus. Méthode inclusion.
Les autres vont et viennent à leur gré. Toutefois cela ne concerne qu'une poignée d'équipement sur 43.

Je n'ai pas fait de rapprochement avec des éventuels timeout qui dureraient plusieurs heures.

**Comment by mickadam29** [comment]
Pendant que j'écrivais la réponse, je suis allé appuyer sur le bouton du capteur 251. Juste une impulsion.
Et j'en suis passé à 14 messages "Abeille 251 a rejoint le réseau". Donc le capteur a quitté le réseau entre 20H42 et 21H20.
L'intervalle me parait court et exclut pratiquement un problème de routeur. Ou alors ce dernier bagote. 

![image](https://user-images.githubusercontent.com/36518012/103488042-f494d980-4e09-11eb-8dd6-eb5d3aed1950.png)

**Comment by tcharp38** [comment]
Je peux en parler, Je pense que ce message est une de mes modifs.
Autrement dit, si il apparait c'est qu'un "device announce" a ete remonté et qui dit "device announce" alors son adresse courte à changé.
J'imagine que tu es sur la master.

C'est tres bizarre effectivement.
Je viens de verifier, ce message n'apparait si et seulement si il y a eu le message "004D/device announce".

Tu peux filer le log parser quand tu joues avec le capteur 251 par ex ?

**Comment by mickadam29** [comment]
Salut @tcharp38 

Oui, je suis bien sur la master. Je vais surveiller son adresse courte.
Je vais regarder tout cela. Je te fournirai le log.

**Comment by mickadam29** [comment]
@tcharp38 

Pour faire rapide, sans refresh de la page SANTE

Mon abeille 251 apparaît avec l'adresse courte 43E5. Et dans les équipements Abeille en 1005. Donc l'équipement change bien d'adresse courte. A suivre

![image](https://user-images.githubusercontent.com/36518012/103520591-aae2d800-4e77-11eb-906d-91fb35ed8732.png)

**Comment by tcharp38** [comment]
On verra le log AbeilleParser. C'est lui qui va nous donner un peu + d'infos.

**Comment by mickadam29** [comment]
@tcharp38 

Le souci c'est que je ne maitrise pas le moment où le message se produit. Donc le AbeilleParser peut ne pas correspondre. Je vais rajouter des lignes dans le log. 500 ce n'est pas suffisant.

**Comment by tcharp38** [comment]
Ha oui 500 c'est trop peu. J'ai 2000 ou 5000 chez moi.
Mais tu m'as dit pouvoir declencher ca par un simple appuis sur le capteur non ?

**Comment by mickadam29** [comment]
> Ha oui 500 c'est trop peu. J'ai 2000 ou 5000 chez moi.
> Mais tu m'as dit pouvoir declencher ca par un simple appuis sur le capteur non ?

Pas à tous les coups malheureusement. Si cela fait un moment, alors probablement qu'il se réannonce.

**Comment by mickadam29** [comment]
Tiens j'ai eu de la chance. Je viens juste d'avoir un avertissement qui signale que l'équipement n'avait pas contacté le réseau depuis 60 min.
Je suis allé appuyé sur le bouton. Il a rejoint le réseau. Du coup AbeilleParser est très bavard

[AbeilleParser (5).log](https://github.com/KiwiHC16/Abeille/files/5766980/AbeilleParser.5.log)
[AbeilleParser-prev.log](https://github.com/KiwiHC16/Abeille/files/5766988/AbeilleParser-prev.log)

Il y a bien un problème dans les adresses courtes. Mon équipement qui aurait quitté le réseau est Abeille-251 qui a l'adresse courte 
1005 dans Topic/Abeille. Mais dans les logs, c'est 43E5 qui remonte.
A 22H59 dans AbeilleParser on voit le 004D/device announce

![image](https://user-images.githubusercontent.com/36518012/103584524-c71b5f00-4ee1-11eb-9dba-1170003a3055.png)
![image](https://user-images.githubusercontent.com/36518012/103584559-d8646b80-4ee1-11eb-8cc2-53b04445036e.png)
![image](https://user-images.githubusercontent.com/36518012/103584582-e4502d80-4ee1-11eb-8df2-3776d281a6fe.png)
![image](https://user-images.githubusercontent.com/36518012/103584676-106bae80-4ee2-11eb-8431-34138629fb4c.png)

Dans la page Santé Abeille-251 a bien l'adresse courte 43E5. Donc incohérence.
![image](https://user-images.githubusercontent.com/36518012/103585607-a0f6be80-4ee3-11eb-80d9-1386221b1f14.png)

Je pense que cela s'approche de ton issue #1596 

Du coup quelle est la véritable adresse courte ? 1005 comme le laisse supposer la page Abeille/Equipement ou 43E5 comme le laisse penser les logs ?

Je pense que l'équipement ne quitte jamais le réseau. Mais comme on le connait sur une mauvaise adresse, on pense qu'il revient.
J'ai d'autres équipements qui m'ont fait ce coup là (on le voit au début de ce post), mais visiblement après les avoir inclus à nouveau (car ils restaient en timeout), ils ne font plus apparaître le message. Je pense que la nouvelle inclusion à remis d'aplomb l'adresse courte partout dans la conf et BDD
Je pourrais tenter une inclusion de mon Abeille-251 mais je pense qu'il vaut mieux laisser comme ça et tenter d'en tirer des infos pour corriger ce qui ne va pas.

J'ai passé mes logs à 5000

**Comment by tcharp38** [comment]
Salut.
Ok la véritable adresse est celle du device announce.
Le topic est faux. Il y a bug donc à ignorer.
Tu peux verifier que ta page santé donne la bonne adresse.

Maintenant la question est pourquoi y a t'il device announce.
Mais on tombe encore sur un cas ou l'info de "rejoin" n'a aucun sens et pas documentée
J'ai mis à jour le bug chez Zigate: https://github.com/fairecasoimeme/ZiGate/issues/325

**Comment by tcharp38** [comment]
@mickadam29 La prochaine fois que tu as cette trace "device announce" avec un 'rejoin' > 3, peux tu aussi donner la trace "SerialRead" ? Merci

Ou tu peux repondre directement dans l'issue https://github.com/fairecasoimeme/ZiGate/issues/325

**Comment by mickadam29** [comment]
@tcharp38 
Ok. Je viens de voir un nouveau message "Abeille-251 a rejoint le réseau" mais cela fait déjà 1H.
Donc tu vois qu'il est assez fréquent pour que je parvienne à tirer quelque chose des logs. 
J'ai augmenté la taille des logs pour faciliter la recherche.
Si je comprends bien, lorsque j'ai le 004D je dois trouver une valeur qui suit pour rejoin. Je maitrise pas linux, mais je pense que l'on doit pouvoir provoquer une copie des fichiers logs (parser et serial) vers export-announce.log (par exemple) dès que 004D/device announce est écrit dans AbeilleParser. Au moins je suis certain de pas louper l'info. Si tu connais linux ce serait pas un mixte d'un tail et d'un grep ?

**Comment by mickadam29** [comment]
> Salut.
> Ok la véritable adresse est celle du device announce.
> Le topic est faux. Il y a bug donc à ignorer.
> Tu peux verifier que ta page santé donne la bonne adresse.
> 
> Maintenant la question est pourquoi y a t'il device announce.
> Mais on tombe encore sur un cas ou l'info de "rejoin" n'a aucun sens et pas documentée
> J'ai mis à jour le bug chez Zigate: [fairecasoimeme/ZiGate#325](https://github.com/fairecasoimeme/ZiGate/issues/325)

La page santé remonte 43E5. Les logs aussi à priori. Donc la véritable adresse sur le réseau. Mais le topic /1005
![image](https://user-images.githubusercontent.com/36518012/103640821-fe752480-4f50-11eb-8dbd-4b542fd033f1.png)
![image](https://user-images.githubusercontent.com/36518012/103641059-6f1c4100-4f51-11eb-8f05-c8d19324cd57.png)

**Comment by mickadam29** [comment]
@tcharp38 
Pas trop mauvais en linux
tail -f AbeilleParser.log | grep -m 1 "device announce"
Reste à faire le batch pour faire le cp des 2 fichiers attendus (Parser et Serial)

**Comment by mickadam29** [comment]
@tcharp38 
Voici ce que j'ai mis pour tracer

sudo rm /tmp/AbeilleParser-announce.log
sudo rm /tmp/AbeilleSerialRead1-announce.log
tail -f AbeilleParser.log | grep -m 1 "device announce"
cp /var/www/html/log/AbeilleParser.log /tmp/AbeilleParser-announce.log
cp /var/www/html/log/AbeilleSerialRead1.log /tmp/AbeilleSerialRead1-announce.log

A la première occurrence je devrais avoir les infos.

**Comment by tcharp38** [comment]
Super !
Donc pour résumer pour tout le monde
- le topic peut etre faux (bug). Je vais entrer une issue pour ca
- du coup ne pas utiliser la commande "short-addr" pour recuperer l'adresse courte mais voir la page santé
- il y a des devices announce incompris mais reels. Du coup nouvelle adresse courte et nouveau message "a rejoint le reseau"
- bug ouvert cote zigate concernant l'info de "rejoin" qui pourrait peut etre nous aider si elle etait valide: https://github.com/fairecasoimeme/ZiGate/issues/325

**Comment by mickadam29** [comment]
@tcharp38 
Voici les 2 logs demandés. Le "device announce" a lieu à 12H 58min 28sec. Une modélisation a lieu
Cet "device announce" se produit parce que j'appuie sur le bouton pour forcer l'équipement à émettre

[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5769993/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5769995/AbeilleParser.log)

**Comment by mickadam29** [comment]
> Super !
> Donc pour résumer pour tout le monde
> 
> * le topic peut etre faux (bug). Je vais entrer une issue pour ca
> * du coup ne pas utiliser la commande "short-addr" pour recuperer l'adresse courte mais voir la page santé
> * il y a des devices announce incompris mais reels. Du coup nouvelle adresse courte et nouveau message "a rejoint le reseau"
> * bug ouvert cote zigate concernant l'info de "rejoin" qui pourrait peut etre nous aider si elle etait valide: [fairecasoimeme/ZiGate#325](https://github.com/fairecasoimeme/ZiGate/issues/325)

Tu dis nouvelle "adresse courte". Pas pour moi. Les 2 valeurs 43E5 (santé) et 1005 (topic) sont les mêmes depuis au moins hier, voire plus. Et j'ai dû avoir au moins 5 ou 6 "device announce" depuis.

**Comment by tcharp38** [comment]
Ha ok. C est un device announce sans changement d'adresse alors.
Faut piger cette info rejoin mais du coup il doit y avoir qqch à faire pour réduire les messages "a rejoint le reseau".

**Comment by mickadam29** [comment]
C'est un équipement qui n'envoie pas suffisamment d'infos et est régulièrement en timeout. Quand il fini par envoyer un message, il est vu comme revenant sur le réseau. J'ai eu d'autre "device announce" dans le WE pour d'autres équipements. Mais ceux-là sont apparu après un arrêt électrique de JEEDOM/Abeille. Au redémarrage, j'ai un plein de timeout, une 20 d'équipements. Et certains on signalé le "Device announce" mais pas tous. Et j'ai dû forcer des inclusions pour certains. Heureux d'avoir mis un onduleur sur ma solution. Un projet DIY "alerte perte secteur" verra le jour d'ici peu.

**Comment by tcharp38** [comment]
Résumé de tes logs... toujours le meme equipement (en l'occurence c'est quoi ?)

> [2021-01-05 11:07:31][debug] Abeille1, Type=004d/Device announce, Addr=43E5, ExtAddr=5C0272FFFEC3EA56, MACCapa=80, Rejoin=60, [Modelisation]
> [2021-01-05 11:07:31][debug] Reçu: "004D000C5543E55C0272FFFEC3EA568060"
> 
> [2021-01-05 12:25:48][debug] Abeille1, Type=004d/Device announce, Addr=43E5, ExtAddr=5C0272FFFEC3EA56, MACCapa=80, Rejoin=57, [Modelisation]
> [2021-01-05 12:25:48][debug] Reçu: "004D000C6243E55C0272FFFEC3EA568057"
> 
> [2021-01-05 12:58:28][debug] Abeille1, Type=004d/Device announce, Addr=43E5, ExtAddr=5C0272FFFEC3EA56, MACCapa=80, Rejoin=4B, [Modelisation]
> [2021-01-05 12:58:28][debug] Reçu: "004D000C7E43E55C0272FFFEC3EA56804B"
> 
>

**Comment by mickadam29** [comment]
Un capteur chinois temp/hum avec afficheur LCD.
Et c'est apparu depuis 1 semaine ou 2 environ. Je ne saurai pas dire depuis quelle version Abeille. Si tant est qu'il y ait un lien

![image](https://user-images.githubusercontent.com/36518012/103645725-ca9dfd00-4f58-11eb-9089-f3acaeed7d41.png)

**Comment by mickadam29** [comment]
@tcharp38 
Peut-être une piste sur l'implémentation Zigbee 3

Child Device Management
Child management is a procedure for which parent devices must now age out neighbor table entries for
unresponsive end device children by a pre-configured default timeout. This aging timeout can be changed
per end device upon request from that end device using the End Device Timeout Request command.
MAC data polls are sent from a child end device to reset the parent's aging counter. But once the timeout
value is exceeded and the child is aged out, the parent will send the device a Leave Request with the
rejoin attribute set so that the device may be allowed to rejoin the network through a new parent device.
MAC Association
APS Transport Key : NWK Key
APS Update Device
APS Tunnel : Transport Key
ZDO Device Announce Broadcast
ZDO Node Descriptor Req
ZDO Node Descriptor Rsp
(APS Encrypted w/ Link Key A)
APS Request Key
(APS Encrypted w/ Link Key A)
APS Transport Key : Link Key B
APS Verify Key
APS Confirm Key
(APS Encrypted w/ Link Key B)
Joining Device now has
NWK Key
,I³6WDFN&RPSOLDQFH
5HYLVLRQ¥ILHOGRI1RGH
Descriptor is 0x15, start
Link Key update
procedure
Joining Device now
Discards Link Key A and
Only uses Link Key B
Joining Device Router Trust Center
Same as legacy
device commisioning
Unencrypted
APS Only
NWK Only
APS + NWK
Packet Encryption Legend
Zigbee PRO Specification www.ti.com
2 SWRA615A–June 2019
Submit Documentation Feedback
Copyright © 2019, Texas Instruments Incorporated
What's New in Zigbee 3.0
2.2 Parent Announce Command
The Parent Announce message is now mandatory on all routing devices (router and coordinator) and is
used to notify other routing devices in a network of which child devices are known to it. The message is
broadcast to 0xFFFC if a routing device previously in the network was rebooted and successfully rejoins
the network. It is sent 10 to 20 seconds after this device rejoins the network.

**Comment by mickadam29** [comment]
Je pense à cela car j'ai parfois un équipement qui dans le graphique Network Abeille apparait comme étant attaché à 2 routeurs.
Comme si le Leave se passait mal et que l'équipement sans être détaché du premier routeur se connectait à un deuxième.
Il faudrait un Leave dans les logs, ca pourrait peut-être aider.

**Comment by mickadam29** [comment]
Référence de la doc

https://www.ti.com/lit/an/swra615a/swra615a.pdf?ts=1609769606639&ref_url=https%253A%252F%252Fwww.google.hu%252F

**Comment by mickadam29** [comment]
@tcharp38 

Sur un interrupteur double sans fil Xiaomi, l'appui plus de 10 sec, avec la Zigate en mode inclusion, provoque bien 1 Leave suivi d'un join

![image](https://user-images.githubusercontent.com/36518012/103687548-bfff5a00-4f90-11eb-80ca-486c69a5bdab.png)

**Comment by tcharp38** [comment]
Ca c est coherent avec les dernieres modifs que j'avais poussé.
Il faut maintenant que je creuse cote paquets recus.

**Comment by mickadam29** [comment]
Visiblement, des pertes de paquets engendraient des timeouts et le routeur "sortait" l'équipement, qui lorsqu'il a des choses à dire 
se manifeste à nouveau. D'où ces messages. Je crois comprendre que c'est une implémentation Zigbee. Donc pas véritablement un problème.
