### ISSUE TITLE
Perte des équipements après coupure de courant

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1590]
1/ Version (AbeilleVersion.inc)
===============================
dev_tcharp38, 2020-12-30 00:36:56

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

Suite à une coupure de courant certains équipements sont sortis du réseau du point de vue Abeille. C'est à dire que je n'ai plus aucune information de leur part, même au bout de qqs heures. Par exemple, et essentiellement mes équipement Xiaomi, l'action sur les interrupteurs ne déclenche plus les scénario. Je passe la Zigate en mode inclusion et je procède à l'inclusion des objets, j'obtiens un message "Abeille-xxx à rejoint le réseau" avec XXX= ID de l'objet qui ne fonctionnait plus. Et après l'inclusion, tout fonctionne à nouveau.  Càd que XXX n'est pas vu comme un nouvel équipement, ni même un objet avec la même IEEE mais tout simplement comme un objet qui s'était absenté du réseau et qui revient. Et les scénarios les prennent en compte. Donc je vais à nouveau lancer l'inclusion de quelques objets afin que Abeille sache qu'ils sont là sur le réseau. On va dire que c'est gênant plus que bloquant mais il y a un bug à trouver et à corriger. Il se pourrait que ces objets aient été rattachés à un routeur qui n'existe plus. Et que l'inclusion va donc les raccorder à un routeur présent. Mais avant ou après la coupure électrique, aucun nouveau routeur n'a été ajouté.

**Comment by mickadam29** [comment]
Pour tenter d'être clair. J'ai constaté le dysfonctionnement après ma coupure électrique de l'équipement sur lequel tourne Jeedom (PC) . En me basant sur le tableau santé.

![image](https://user-images.githubusercontent.com/36518012/103460675-91774a00-4d18-11eb-8414-0a9b12e3bdc3.png)

Pour faire reconnaître Abeille-266. Je passe la Zigate en inclusion. Je fais la procédure d'inclusion de l'objet.
![image](https://user-images.githubusercontent.com/36518012/103460751-25491600-4d19-11eb-84a0-7ef9bb098001.png)

Et à partir de là tout revient dans l'ordre. Mon détecteur de présence est vu dans les déclencheurs de scénario.

**Comment by mickadam29** [comment]
Je pense donc que ces équipements communiquaient avec un routeur qui a disparu (il serait lui-même absent sur le réseau après le retour secteur de la Zigate). Et l'inclusion les ramènent sur le réseau en passant par un autre. N'ayant pas les infos sur qui passait par quel routeur pour joindre la zigate avant la coupure, cela reste un supposition. Mais la correction étant tellement simple que je ne vois que cela.
Et ce d'autant que tous les équipements qui ont quitté le réseau sont physiquement au RDC, donc probablement rattachés au même routeur. 
J'ai oublié de préciser que tous les équipement à inclure sont sur pile et la coupure électrique n'a concerné que le linux sur lequel tourne jeedom.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Les possibilités que je connais:
- perte d un routeur
- coupure trop longue et les capteurs xiaomi ont un "bug" car dans ce cas finisse par quitter tout seul le réseau.

**Comment by mickadam29** [comment]
> Les possibilités que je connais:
> 
> * perte d un routeur
> * coupure trop longue et les capteurs xiaomi ont un "bug" car dans ce cas finisse par quitter tout seul le réseau.

Je pencherai pour la perte d'un routeur mais je ne vois pas lequel. Après avoir provoqué une inclusion, Zigate en mode inclusion, appui >5s sur les Xiaomi, ils reviennent sur le réseau. Il faudra que j'identifie les routeurs par lesquels ils passent. L'un d'eux est le capteur de temp avec afficheur LCD. Il peut mettre 7h avant d'envoyer un trame. Donc la piste de coupure trop longue est possible. Mais cela viendrait d'une des version Abeillle. Car le phénomène ne se produit que depuis qqs jours. Et pas que sur des équipements Xiaomi.

**Comment by mickadam29** [comment]
Je pense que cela vient de la version 3.1D qui implémente le fait qu'un Endpoint est "sorti" du réseau si il ne communique plus.
En soit ce n'est pas un problème car il rejoint facilement et systématiquement le réseau
