### ISSUE TITLE
Interrupteur simple/double Xiaomi. Retour de valeurs Appui court, long et double

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1592]
@KiwiHC16 

S'agissant d'un interrupteur Double Xiaomi sans fil (WXKG02LM) vu par son nom ``lumi.remote.b286acn01``
En lisant certains posts, je constate que les modèles récents (année de fab >2018 vs 2016)  gèreraient le simple, double et long appui.
As-tu connaissance de l'info ? Car si c'est implémenté, il faudrait modifier le template car dans celui qui existe on refuse la valeur 0 pour la commande 0012-01-0055. Et donc l'appui long n'est pas gérable. Or il pourrait servir dans des scénario style gestion Dimmer

Les valeurs que me retourne mon interrupteur sont :

0 : Appui long
1 : Appui court
2 : Double appui

Exemple du double appui.

[2021-01-03 11:50:40][DEBUG] : fct message Topic: ->Abeille1/767F/0012-01-0055<- Value ->2<-
[2021-01-03 11:50:40][DEBUG] : message(topic='Abeille1/767F/0012-01-0055', payload='2')

Exemple appui long >=2 secondes. Retour 0 et rejet.

![image](https://user-images.githubusercontent.com/36518012/103477589-a7d8e080-4dc0-11eb-8e1f-d77014422f58.png)

L'appui court renvoie "1"

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Oui il certainement modifier le modele de binaire à numeric sur cette commande.

**Comment by mickadam29** [comment]
@KiwiHC16 Merci
Je ferai des tests. Ce n'est pas ma priorité. DIY avant tout.
Toutefois, concernant ces interrupteurs, depuis qqs jours, j'ai un phénomène de rebond. Càd que l'appui sur l'interrupteur
est détecté, le toggle se fait, mais dans la seconde un second toggle se produit. OFF-ON-OFF. Pas très pratique.

**Comment by mickadam29** [comment]
Il y a confusion entre les modèles à 1 et 2 boutons.
Sur le modèle qui remonte ``lumi.remote.b186acn01`` il n'y a qu'un bouton. Donc seul Etat1 existe. Or le modèle crée 3 états.
Pour Etat1, le payload devrait être 0,1 ou 2 en fonction de l'appui. Donc numérique et non binaire. Je ferai des tests en modifiant le modèle et les templates si nécessaire. Je te dirai s'il faut modifier des éléments dans la distrib.

![image](https://user-images.githubusercontent.com/36518012/103573427-81a16680-4ece-11eb-846f-6bba21a9a233.png)

**Comment by mickadam29** [comment]
@KiwiHC16 
Je viens de supprimer les états 2 et 3 dans l'équipement basé sur le  modèle b186acn01 et mis la valeur Etat1 en numérique. Cela fonctionne très bien. 0 - Long / 1 - Court / 2 - Double
![image](https://user-images.githubusercontent.com/36518012/103575787-836d2900-4ed2-11eb-8e69-ce09f0b9410a.png)

Mais le rejet de la valeur 0 a toujours lieu. Il faut que supprime l'équipement pour qu'Abeille le recrée en numérique ? En fait je crois que non, c'est plutôt le template. Dis moi si je me trompe. Mais dans ce cas il faudra recréer l'équipement

![image](https://user-images.githubusercontent.com/36518012/103575688-60427980-4ed2-11eb-9339-29a62a17eee1.png)

**Comment by KiwiHC16** [comment]
Binaire: C est dans le modele:
https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/Template/etatSwitchDoubleb286acn01_1.json#L8

Je le passe en numeric.

**Comment by KiwiHC16** [comment]
Le reject Value est aussi dans le modele.
https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/Template/etatSwitchDoubleb286acn01_3.json#L16

**Comment by KiwiHC16** [comment]
J ai modifié dans le modele la binary to numeric et retiré les reject.
recuperes les fichiers depuis https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/Template:
- etatSwitchDoubleb286acn01_1.json
- etatSwitchDoubleb286acn01_2.json
- etatSwitchDoubleb286acn01_3.json
Mets les sur ton systeme au lieux des anciens, suppirmes tes equipements, refaits l inclusion et ca doit être bon.

**Comment by mickadam29** [comment]
Merci @KiwiHC16 
Je vais faire les maj
Par contre je suppose qu'il faut que tu fasses aussi les modifs pour le modèle 1 interrupteur. Le b186acn01, comme tu viens de le faire pour le b286acn01

Toujours pas d'astuce pour éviter de supprimer l'objet et appliquer le nouveau modèle ?

**Comment by KiwiHC16** [comment]
Non pas encore possible de faire une mise a jour des equipements. J ai fait un menu Modeles qui fait la liste des differences c est un premier pas dans cette direction.

**Comment by mickadam29** [comment]
@KiwiHC16 
J'ai supprimé et recréé l'objet.
L'objet est conforme. 3 états "numérique" et la valeur 0 n'est plus rejetée.
Tu prévois la même chose dans la master pour l'interrupteur simple b186acn01 ? 
La prise en charge de ces 2 modèles sera donc complète et je pourrai te valider tout cela avant passage en stable.
Merci à toi

**Comment by KiwiHC16** [comment]
b186acn01 a recu la meme modif car il utilise les meme sous modele.
Ok je clos alors.
