### ISSUE TITLE
Impossible d'indiquer icon sur équipement abeille 

### ISSUE THREAD

**Issue by loustic03** [KiwiHC16/Abeille#1594]
J’ai refais une new instal jeedom
Je n'ai aucun icon dans la liste dans l'équipement, malgré que sur le dossier image du plugin elles sont bien présentes.
![image](https://user-images.githubusercontent.com/76919490/103487907-f90cc280-4e08-11eb-8d17-91ba93bd0897.png)
![image](https://user-images.githubusercontent.com/76919490/103487919-0de95600-4e09-11eb-854d-ea696cb4105d.png)
Je sais pas si tu pourra voir les images , c'est ce que je tes poster en MP sur
https://community.jeedom.com/t/re-probleme-avec-les-icon-sur-equipement/45165

**Comment by loustic03** [comment]
![image](https://user-images.githubusercontent.com/76919490/103488001-b4355b80-4e09-11eb-9e07-a837fc15f165.png)
![image](https://user-images.githubusercontent.com/76919490/103488004-bd262d00-4e09-11eb-9945-adec6d4defb1.png)
Bon j'ai mis le reste car je ne savais pas que cela aller s'afficher une fois poster.

**Comment by tcharp38** [comment]
Salut @loustic03 
Sur quelle version es tu ? Si pas sur la version "market", comment as tu procédé pour l'installation ?

**Comment by loustic03** [comment]
Salut, j'ai la version abeille du market depuis 3 ans donc en stable depuis le début.

**Comment by loustic03** [comment]
Début décembre j'ai passé la zigate en 3.1d ensuite tout à bug sur abeille du coup je suis repassé en 3.1b tous fonctionne correctement à part ce problème de liste d'icônes

**Comment by KiwiHC16** [comment]
Salut @loustic03 
Tu n'ais pas le premier utilisateur à remonter ce soucis.
Il peut provenir d'un probleme lors de la mise a jour.
Peux tu me donner deux infos:
1- version abeille sur ton systeme. Visible dans la page de configuration
2- en ssh, partager le resultat de 
```
df -h
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by loustic03** [comment]
![image](https://user-images.githubusercontent.com/76919490/103561919-8c520080-4eba-11eb-840a-7c23ec681d86.png)

![image](https://user-images.githubusercontent.com/76919490/103562162-e5ba2f80-4eba-11eb-8bc6-2d80ff0d58ab.png)

**Comment by Tonio16** [comment]
> Salut @loustic03
> Tu n'ais pas le premier utilisateur à remonter ce soucis.
> Il peut provenir d'un probleme lors de la mise a jour.
> Peux tu me donner deux infos:
> 1- version abeille sur ton systeme. Visible dans la page de configuration
> 2- en ssh, partager le resultat de
> 
> ```
> df -h
> ```
Salut

Je me permets de répondre ayant le même problème.

Pour mon cas, mes installations sont faites depuis le market et après plusieurs installations, le problème persiste.

df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
/dev/root          110G    5.2G  101G   5% /
devtmpfs           455M       0  455M   0% /dev
tmpfs              488M       0  488M   0% /dev/shm
tmpfs              488M     50M  438M  11% /run
tmpfs              5.0M    4.0K  5.0M   1% /run/lock
tmpfs              488M       0  488M   0% /sys/fs/cgroup
tmpfs              128M    6.4M  122M   5% /tmp/jeedom
/dev/sda1          253M     54M  199M  22% /boot
tmpfs               98M       0   98M   0% /run/user/1000

Antoine

**Comment by KiwiHC16** [comment]
Est ce que l un de vous deux serai ok pour faire un partage d'ecran avec AnyDesk.com pour que je regarde directement sur le systeme. Il me faudrait une vue jeedom (web browser) et deux ssh ouverts. Vous me passez le code d'acces et on convient d'un rendez vous car j'ai besoin de vous devant la machine.

**Comment by loustic03** [comment]
Salut @KiwiHC16 , je suis dispo si tu veux.

**Comment by KiwiHC16** [comment]
Ce soir après 21h ?

**Comment by loustic03** [comment]
Ok pour 21h, si j'ai bien compris je télécharge AnyDesk.com , je te donne le numéro du poste de travail et j'ouvre 2 fenêtres ssh sur le pc

**Comment by KiwiHC16** [comment]
Oui. Je fais mon possible pour être là à 21h. J'espère ne pas être en retard sinon n'attend pas plus de 5 minutes et je posterai un message ici quand je serai dispo.

**Comment by loustic03** [comment]
Ok ça marche , je t'envois le code en mp sur community

**Comment by Patag** [comment]
Bonsoir,
Très intéressé également car dans le même cas.
Précision : à l'inclusion, la bonne image est associée au nouveau module bien que la liste soit presque vide. C'est après la sauvegarde du module que l'image par défaut est associée.

**Comment by KiwiHC16** [comment]
Je suis dispo. Tiens moi au jus pour le code.

**Comment by KiwiHC16** [comment]
Stable du 1/12/2020 15:00
Une zigate USB 31B
Mise a jour Abeille Classique par le menu mise a jour.


Exemple: Zightligt 
Icones possibles: Abeille / Ruche / ZigbeeWindowsCoveringDevice

Linux aarch64

/tmp/jeedom 256M 6M used tmpfs

Core Jeedom 4.0.61

rmdir Timer
rmdir TRADFRISignalRepeater
et la la liste est plus longue mais ne semble pas complete.

rmdir zigbeeDimmable
rmdir LOM02

plus d erreur *.json dans log Abeille

Soucis: fichiers json qui manquent.

Voir comment faire une mise a jour des templates qui manquent et enlever Timer qui etait toujours la...
Faire un test pour ne pas planter sur manque de fichier json....

**Comment by KiwiHC16** [comment]
Test sur systeme de dev:

- checkout stable: 
[2021-01-06 08:01:48][WARNING] : Fichier introuvable: A60TWZ3.json

- checkout master
[2021-01-06 08:03:43][WARNING] : Fichier introuvable: 

- rm rf Abeille, git clone...
No error

- checkout stable
No error
mkdir Timers
Error Fichier introuvable: Timers.json mais liste incomplete

- checkout master
No error
mkdir Timers
[2021-01-06 08:14:46][WARNING] : Fichier introuvable: 
Mais liste semble complete
rmdir Timers
Pas error liste complete

**Comment by KiwiHC16** [comment]
J ai mis plus de tests dans le code. Sera dispo dans la prochaine beta et puis stable. Ne resout pas le probleme de fond mais doit mieux gérer les erreurs et avoir plus de trace pour comprendre ce qu il  se passe.

**Comment by loustic03** [comment]
Salut,  étant donné que ton intervention d'hier à résolu mon souci de liste d'icônes je clôture cette demande. 
Merci à toi.

**Comment by Patag** [comment]
Bonjour,
Cela aurait été cool de publier ici une solution (même temporaire) en attendant une màj et avant de fermer....
