### ISSUE TITLE
probleme trop de message CAS A    (de nouveau)

### ISSUE THREAD

**Issue by jossalison38** [KiwiHC16/Abeille#1595]
bonjour
je me permet de revenir vers vous car mon problème , trop de message cas a est revenu depuis que je suis passe a jeedom v4.061 sur un rpi4.
tous fonctionne maintenant mais se message revient tous le temp .
pourriez vous me dire si cela est grave et que puis je faire?
lors de ma précédant demande KiwiHC16, m'avait fait modifie un fichier mais cette fois ci ca n'a rien changé 
pour info l'installation comprend  (15 volet profalux avec les 15 télécommande, la telecommande zoe ,  10 prise ikea , 2 detecteur de fumee)
merci par avance
voici quel que écran un fichier debug:
[Abeille (3).txt](https://github.com/KiwiHC16/Abeille/files/5764720/Abeille.3.txt)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5764721/AbeilleCmd.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5764724/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5764725/AbeilleParser.log)

![image](https://user-images.githubusercontent.com/47280807/103536958-b643fc80-4e93-11eb-8081-828e5a88c63f.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Normalement pas de soucis.
Peux tu partager une capture de l ecran santé ?

**Comment by jossalison38** [comment]
bonsoir pas de soucis .
pour info entre mon dernier message et ce soir . le message cas A est revenue 119 fois 
j'ai remarqué aussi qu'il y  des moment , on est obligé de demandé plusieurs fois  pour actionné une prise ikea , je ne ses  pas si les probleme son lié 
![image](https://user-images.githubusercontent.com/47280807/103686630-68142380-4f8f-11eb-9bda-34e48d628964.png)
![image](https://user-images.githubusercontent.com/47280807/103686658-73674f00-4f8f-11eb-8346-3cc29202192c.png)
a bientot merci

**Comment by jossalison38** [comment]
bonsoir avez vous des news du problème ? 
le message est  revenu 291 fois en 3jours 
a bientôt 
cordialement

**Comment by KiwiHC16** [comment]
D'apres les captures d'écran il y a beaucoup d equipmeent en timeout. Il faudrait faire le menage dans un premier temps.
Peux tu regarder pourquoi tu as cette situation, car si c est le cas, les queues de messages peuvent s allonger car les equipements ne repondent pas.

**Comment by jossalison38** [comment]
bonjour
 j'ai fait le ménage sur les équipement, la plupart était des télécommandes de volet profalux .
Le peu qu'il me reste en time out sur la capture écran, son une prise qui n'est pas utilise pour l'instant et un détecteur Ikea qui ne l'ais pas non plus. 
j'ai toujours le message cas a qui apparait environ 200 fois par jour 
je mais en lien les fichiers debug pour une éventuelle résolution du problème 
un grand merci a vous 
bonne journée 

[AbeilleSerialRead1 (1).log](https://github.com/KiwiHC16/Abeille/files/5860102/AbeilleSerialRead1.1.log)
[AbeilleCmd (1).log](https://github.com/KiwiHC16/Abeille/files/5860103/AbeilleCmd.1.log)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/5860104/AbeilleParser.1.log)
[Abeille (5).txt](https://github.com/KiwiHC16/Abeille/files/5860106/Abeille.5.txt)

 ![image](https://user-images.githubusercontent.com/47280807/105576826-c86bd900-5d75-11eb-9dfb-652e73c047aa.png)
![image](https://user-images.githubusercontent.com/47280807/105576831-d15caa80-5d75-11eb-9bcc-c129e6e07fcc.png)

**Comment by KiwiHC16** [comment]
AbeilleParser: enormement de menages:
```
[2021-01-23 12:19:35][debug] Abeille1, Type=8035/PDM event code, PDMEvtCode=x03, RecId=0000F102 => LARGEST_RECORD_FULL_SAVE_NO_LONGER_POSSIBLE
```
Tu es le deuxième utilisateur qui remonte ca dans ses logs. Perso je ne les ai jamais eu. Semble indiquer que la zigate ne parvient pas a sauvegarder ses data !!!

Quelle est la version du firmware ? (je vois Type=8010/Version, Appli=3, SDK=031C dans les logs)

Tu as aussi beaucoup de message, qui indiquent des problèmes de dialogue sur la radio:
```
Type=8702/APS Data Confirm Fail, Status=D4
```

Combien d'équipement as tu sur ta zigate ?

Peux tu partager une capture d'écran du reseau ? menu plugin -> abeille -> network list -> graphique des liens.

**Comment by jossalison38** [comment]
voici les capture 
Lorsque je demande un reinterrogation du réseaux  j'ai ce message et pas de réintégration


![image](https://user-images.githubusercontent.com/47280807/105749039-31ed1280-5f43-11eb-94f5-29a79eb078ae.png)

![image](https://user-images.githubusercontent.com/47280807/105748908-079b5500-5f43-11eb-91c4-f30986935be2.png)
![image](https://user-images.githubusercontent.com/47280807/105748996-1f72d900-5f43-11eb-91c4-3a013d9b2b28.png)

**Comment by jossalison38** [comment]
salut j'ai 29 equipement reel sur la zigate

**Comment by KiwiHC16** [comment]
As tu la derniere stable Abeille ? Quelle version ?

**Comment by KiwiHC16** [comment]
Pour moi le probleme est le même que #1665. Je clos celui ci.
