### ISSUE TITLE
eqLogic, logicalId vs configuration/topic & config/topic FAUX

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1596]
@KiwiHC16 
Je réalise qu'il y a deux infos qui me semblent identiques mais pas à jour.
Dans un 'eqLogic', quelle est la diff entre "logicalId" et "configuration/topic" ?

Sur ma plateforme de test je vois par ex un equipement (Xiaomi temp carré) qui n'a pas de "topic" valide:
"id":"19",
"name":"Abeille1-19",
"logicalId":"Abeille1\/D5A7"
"configuration"    "topic":"Abeille1/052C"

Du coup evidement le topic est faux mais il me semble pas mal utilisé.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Normalement il doit être identique.
Il faudrait que je me rafraichisse la memoire en regardant le code.
D apres mes souvenirs, le topic doit être utilisé lors de l envoi d une commande (command action)
et le logical Id lors de la reception d un message.
Cette "merdouille" doit etre l'heritage des premieres ligne de code et probablement devrait être remise à plat.

**Comment by tcharp38** [comment]
Ok. Peu importe l'historique. Tu devais en avoir besoin sans vraiment avoir le temps de remettre à plat.
Donc ce qui m'interesse maintenant c'est si tu consideres encore le "topic" necéssaire et dans quel cas.
Si il y a redondance il faut progressivement le virer.

**Comment by tcharp38** [comment]
Le topic est utilisé lorsqu'on passe par les commandes de l'equipement puis test de la commande "short-addr" par ex.
L'adresse remontée est celle du topic. Mais comment ???
Aucune info n'est renvoyée sur le reseau. Ca ne semble meme pas passer par Abeille. Jeedom se debrouille avec les infos qu'il a.

Donc actuellement cette adresse (test peut etre fausse !!

![image](https://user-images.githubusercontent.com/35221038/103639577-d1277700-4f4e-11eb-8060-ffbf3693a228.png)

**Comment by KiwiHC16** [comment]
Quand tu fais tester ca appelle la fonction execute: https://github.com/KiwiHC16/Abeille/blob/master/core/class/AbeilleCmd.class.php#L5
et en ligne
https://github.com/KiwiHC16/Abeille/blob/master/core/class/AbeilleCmd.class.php#L28
on recupere le topic.

**Comment by KiwiHC16** [comment]
Je t'ai dit une betise hier. logicalId et topic sont differents.
Topic tu peux le voir dans les commandes:
![Capture d’écran 2021-01-05 à 16 21 11](https://user-images.githubusercontent.com/8549674/103663995-085b4f80-4f72-11eb-9fa4-1098b29c146a.png)
LogicalId est l adresse du device.
Topic est soit la cmd a envoyer pour une commande action, soit le cluster/EP/Param pour un commande info.

**Comment by KiwiHC16** [comment]
Il faudrait regarder pourquoi tu as une info qui ressemble à une logicalId dans un topic. Ca ne semble pas correct.

**Comment by KiwiHC16** [comment]
Je viens de tomber exactement sur le meme soucis.
![Capture d’écran 2021-01-11 à 16 25 35](https://user-images.githubusercontent.com/8549674/104201511-25889600-542a-11eb-845d-3b260b5b2c9f.png)

Il faut trouver le code qui fait la mise a jour du logicalId mais oublis les commandes. Et encore mieux ne pas dupliquer l information, c est a dire avoir l info de l adresse dans logicalId et ne pas l avoir dans les commandes.

**Comment by tcharp38** [comment]
Le logicalId est mis à jour au "device announce".
Les commandes dependent du logical ID ?

**Comment by tcharp38** [comment]
J'essaie de comprendre comment est utilise "eqLogic->config->topic"
A priori faut deja pas se melanger entre le "topic" d'un equipement et celui d'une commande.
```
$ grep -R getConfiguration * | grep -v '.bak' | grep topic
core/class/Abeille.class.php:                    Abeille::publishMosquitto(queueKeyAbeilleToCmd, priorityInterrogation, "TempoCmd" . $cmd->getEqLogic()->getLogicalId() . "/" . $cmd->getConfiguration('topic') . "&time=" . (time() + $cmd->getConfiguration('PollingOnCmdChangeDelay')), $cmd->getConfiguration('request'));
core/class/AbeilleCmd.class.php:                if (strpos("_" . $this->getConfiguration('topic'), "CmdAbeille") == 1) {
core/class/AbeilleCmd.class.php:                    $topic = $this->getConfiguration('topic');
core/class/AbeilleCmd.class.php:                    if (strpos("_" . $this->getConfiguration('topic'), "CmdCreate") == 1) {
core/class/AbeilleCmd.class.php:                        $topic = $this->getConfiguration('topic');
core/class/AbeilleCmd.class.php:                        $topic = "Cmd" . $NE->getConfiguration('topic') . "/" . $this->getConfiguration('topic');
core/class/AbeilleCmd.class.php:                if (strpos("_" . $this->getConfiguration('topic'), "CmdAbeille") == 1) {
core/class/AbeilleCmd.class.php://     $topic = str_replace( "CmdAbeille", "CmdAbeille".$NE->getConfiguration("Zigate"), $topic );
core/class/AbeilleCmd.class.php:                    $topicNEArray = explode("/", $NE->getConfiguration("topic"));
core/class/AbeilleCmd.class.php:                    $topic = str_replace("#addrGroup#", $NE->getConfiguration("Groupe"), $topic);
core/class/AbeilleParser.class.php:                Abeille::publishMosquitto( queueKeyAbeilleToCmd, priorityInclusion, "TempoCmd".$cmd->getEqLogic()->getLogicalId()."/".$cmd->getConfiguration('topic')."&time=".(time()+$cmd->getConfiguration('PollingOnCmdChangeDelay')), $cmd->getConfiguration('request') );
core/php/AbeilleClassTest.php:                    Abeille::publishMosquitto(queueKeyAbeilleToCmd, priorityInterrogation, "TempoCmd" . $cmd->getEqLogic()->getLogicalId() . "/" . $cmd->getConfiguration('topic') . "&time=" . (time() + $cmd->getConfiguration('PollingOnCmdChangeDelay')), $cmd->getConfiguration('request'));
core/php/AbeilleClassTest.php:                    echo "Conf: " . $abeille->getConfiguration('topic') . " - ";
core/php/AbeilleClassTest.php:                    $abeille->setConfiguration('topic', str_replace($from, $to, $abeille->getConfiguration('topic')));
core/php/AbeilleClassTest.php:                    echo "Conf: " . $abeille->getConfiguration('topic') . "\n";
core/php/AbeilleTest.php:                    // Abeille::publishMosquitto( queueKeyAbeilleToCmd, priorityInclusion, "TempoCmd".$cmd->getEqLogic()->getLogicalId()."/".$cmd->getConfiguration('topic')."&time=".(time()+$cmd->getConfiguration('PollingOnCmdChangeDelay')), $cmd->getConfiguration('request') );
plugin_info/install.php:                $abeille->setConfiguration('topic', str_replace( $from, $to, $abeille->getConfiguration('topic') ) );
plugin_info/install.php:                $abeille->setConfiguration('topic', str_replace( $from, $to, $abeille->getConfiguration('topic') ) );
plugin_info/install.php:            $topic = $eqLogic->getConfiguration('topic', 'undefined');
```

**Comment by tcharp38** [comment]
Apres recherche, il semble que le **eqLogic->config->topic** ne soit pas utilisé du tout.
Celui de cmd, lui par contre l'est.

Je vais continuer de creuser mais du coup je ne vois aucun impact sur le fait qu'il soit faux.
@KiwiHC16 Dis moi si tu es en ligne avec ca ou si je loupe qqch.

**Comment by KiwiHC16** [comment]
Soucis provient probablement d ici:
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1233
logicalId met à jour mais pas les commandes. Ca a du être perdu lors d une modification.

**Comment by KiwiHC16** [comment]
eqLogic->config->topic : je le trouve à la ligne: https://github.com/KiwiHC16/Abeille/blob/master/core/class/AbeilleCmd.class.php#L34
C est probablement le bug, il faudrait 
```
$topic = "Cmd" . $NE->getLogicalID() . "/" . $this->getConfiguration('topic');
```
en place et lieux de 
```
$topic = "Cmd" . $NE->getConfiguration('topic') . "/" . $this->getConfiguration('topic');
```

**Comment by KiwiHC16** [comment]
On doit pouvoir commenter/supprimer cette ligne:
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1329

Idem pour
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1398

Il faut retirer cette ligne aussi:
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1412

**Comment by KiwiHC16** [comment]
.

**Comment by tcharp38** [comment]
> Soucis provient probablement d ici:
> https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1233
> logicalId met à jour mais pas les commandes. Ca a du être perdu lors d une modification.

Oui j'avais repris cette partie de code.
Je mets à jour le eqLogic->config->logicalId car nouvelle adresse courte mais je ne vois toujours pas le rapport avec les commandes.

Je ne vois pas ou est utilisé le eqLogic->config->topic contrairement à cmd->config->topic.

**Comment by KiwiHC16** [comment]
Pour les commandes actions, il faut savoir à quelle adresse envoyer la demande.
Au debut cette info etait en dure dans le topic de la commande. Puis je me suis rendu compte que je dupliquais cette information dans toutes les commandes d un même équipement donc j ai reduis l info dans topic au strict necessaire.
C est a dire le nom de la commande uniquement. Par exemple de "CmdAbeille1/ABCD/On" à "On".
Ensuite j avais besoin de garder l adresse quelque part au niveau de l'equipement donc j'ai du le mettre dans topic au niveau de l equipement et aussi dans logicalId. 
Le resultat de cette discussion, est qu'il faut faire le menage et qu'il n'est pas necessaire d'avoir un topic dans l'équipement car l info est dans  logicalID.

J'ai aussi trouvé des trucs pas trop propre, je vais pousser des corrections sur le sujet aujourd'hui.

**Comment by KiwiHC16** [comment]
J ai fait toutes les modifs que je voulais faire. On peut clore le sujet mais avant il faut tester car ca touche une partie sensible du code...

**Comment by tcharp38** [comment]
ok, a suivre donc.
De toute facon il y a deja une beta dispo et j'espere que tu pourra la pousser en stable. Trop de decalage avec les utilisateurs maintenant.

**Comment by KiwiHC16** [comment]
Je passe en stable lundi prochain.
Ne contiendra pas cette correction mais si nos tests sont ok on peut en sortir une autre une semaine plus tard.
