### ISSUE TITLE
Network Graph - Zigate > 1

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1598]
![Capture d’écran 2021-01-05 à 17 16 26](https://user-images.githubusercontent.com/8549674/103670348-c0402b00-4f79-11eb-8d2b-9f251b183449.png)

![Capture d’écran 2021-01-05 à 17 16 43](https://user-images.githubusercontent.com/8549674/103670389-cf26dd80-4f79-11eb-9e5e-032e137e1e8a.png)

URL: http://jeedompro/index.php?v=d&m=Abeille&p=AbeilleNetworkGraph

Select Zigate 2, 3 ou 4

![Capture d’écran 2021-01-05 à 17 17 19](https://user-images.githubusercontent.com/8549674/103670450-e06fea00-4f79-11eb-894c-98898c28d18d.png)

URL: http://xxxxxxx/plugins/Abeille/Network/TestSVG/NetworkGraph.php?zigate=2

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Version Abeille: beta, 2020-12-15 11:20:57

**Comment by tcharp38** [comment]
Ca fonctionne dans le master ?
J'avais déplacé "Network/NetworkGraph.php" vers "desktop/AbeilleNetworkGraph.php"

**Comment by KiwiHC16** [comment]
je viens de tester avec master et c est bon donc je clos.
