### ISSUE TITLE
Remettre un lien vers la doc depuis la conf d un equipement.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1600]

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-06 à 09 42 32](https://user-images.githubusercontent.com/8549674/103747811-8156b780-5003-11eb-9f10-76ebef4e0246.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-06 à 09 43 32](https://user-images.githubusercontent.com/8549674/103747920-a5b29400-5003-11eb-9294-dabc97d4ea4b.png)

Lien identique au lien dispo sur Liste Compatibilité

**Comment by KiwiHC16** [comment]
Exemple: https://github.com/KiwiHC16/AbeilleDoc/blob/master/source/docProduits/SPZB0001/doc/2019_03_18_12_05_39.pdf

Sur depot AbeilleDoc.

**Comment by KiwiHC16** [comment]
Ok je te l assigne.

**Comment by tcharp38** [comment]
J'ai ajouté les docs "produits" dans "docs/products" pensant que c'etait directement accessible mais ca ne l'est pas donc à retravailler.
En attendant les docs sont dispo via

https://github.com/KiwiHC16/AbeilleDoc/tree/master/docs/products/**<product_name>**/**<file_name>**

Ex: https://github.com/KiwiHC16/AbeilleDoc/blob/master/docs/products/SPZB0001/2020_01_14_13_52_22.pdf

Comme je bosse sur la page "Equipement" je vais mettre à jour ces liens dans la foulée.

**Comment by tcharp38** [comment]
PR #1610 en attente

**Comment by tcharp38** [comment]
Ca devrait être ok sur le master.
A reouvrir si besoin.
