### ISSUE TITLE
Graphe: ajouter le nom de la piece (Objet) au nom du device

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1601]
Ajouter le nom de la piece (Objet) au nom du device sinon on peut se retrouvé avec plusieurs Temp(rature) et du coup on ne sasit plus qui est qui.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-07 à 08 23 14](https://user-images.githubusercontent.com/8549674/103863706-9a25a280-50c1-11eb-8d51-1aa2f23fb43a.png)

**Comment by mickadam29** [comment]
+1

**Comment by tcharp38** [comment]
En cours.

**Comment by tcharp38** [comment]
Dans la branche master.
A reouvrir si ca ne convient pas ou si bugs.
