### ISSUE TITLE
Support des Benexmart Zigbee 3.0 Gu10 Smart 5W RGBCW LED

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1604]
Bonjour,

Ce sont des ampoules RGB GU10 a priori de chez Zemismart. Elles sont - chères que les GledOpto
[https://www.amazon.fr/Benexmart-intelligentes-compatibles-SmartThings-Contr%C3%B4le/dp/B08PCMJLMT](url)
[https://fr.aliexpress.com/item/1005001770179104.html](url)
Je suis prêt à en commander quelques-unes mais avant je voudrais savoir si elles ont déjà été validées sur Abeille ?
Merci pour votre retour

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Ne sont pas connues d'Abeille.
A priori il suffit de faire un modele (copie d un modele existant) et cela devrait être bon, mais je ne peux être sure à 100% sans les avoir testé.

**Comment by JC38** [comment]
C'est commandé, wait and see.

**Comment by JC38** [comment]
Bonsoir,
Les ampoules sont arrivées. Tu as une procédure qui décrit les actions à faire pour te permettre de les intégrer ?
![image](https://user-images.githubusercontent.com/16527222/106501565-9d932a80-64c3-11eb-8bbd-73b266262fb7.png)

**Comment by JC38** [comment]
Bon, 
je suis arrivé à faire quelque chose de manière plus ou moins empirique.
J'ai pris le fichier json GL-B-008Z que j'ai renommé en ZB-CL01 et posé dans un dossier du même nom après l'avoir customisé.
Fichier txt à renommer en json
[ZB-CL01.txt](https://github.com/KiwiHC16/Abeille/files/5936584/ZB-CL01.txt)
Fichier pour l'icone
![node_ZB-CL01](https://user-images.githubusercontent.com/16527222/107114699-3a5d1b80-6868-11eb-9abe-02f705d34438.png)
Source pour l'équipement et les images : [https://benexmart.com/products/benexmart-gu10-zigbee-bulb-alexa-google-home-assistant-tuya-smart-life-app-remote-control-rgb-led-light-dimmer-lamp-ampoule-led-gu10](url)
[https://cdn.shopify.com/s/files/1/0283/3920/8267/products/1-be_1024x1024@2x.jpg?v=1608714330](url)

**Comment by tcharp38** [comment]
Salut @JC38 
Je sais que le sujet est antique et j'imagine que tu n'es plus interessé. Correct ?

**Comment by JC38** [comment]
Bonjour,
Oui, le sujet est un peu poussiéreux. Je suis actuellement entrain de migrer pour une solution basée sur Zigbee2mqtt

**Comment by tcharp38** [comment]
Ok merci pour ton retour.
