### ISSUE TITLE
Icônes incorrectes

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#1605]
Bonjour @KiwiHC16 et tous mes vœux de santé, bonheur et réussite pour cette nouvelle année.
Ci-après curiosité au niveau des icônes des équipements, mais je ne sais pas te dire depuis quand cela se produit. Enfin presque puisque je me suis aperçu de cela ce matin après avoir inclus le module Ab1-T° Terrasse et modifié le module Ab1-Niche Domot.
![image](https://user-images.githubusercontent.com/52486183/104102898-95b6e080-529f-11eb-91d3-c5793e88b61e.png)

De plus, j'ai toujours le problème que je t'avais signalé il y a quelque temps, lorsque je suis sur le dashboard de mes équipements Températures, su je clique sur un équipement, au lieu d'aller sur la configuration de cet équipement je me retrouve sur l'écran de gestion du plugin.

Merci de ton aide 

Edit : pour le point 1, quand je vais dans Santé du plugin je vois que le Type de l'équipement est passé à Abeille ou est vide.
Je suis en Jeedom 4.1.17 et pour Abeille 2020-12-05 01:00:13

Petite précision concernant le point 1 : lors d'une modification sur la page de l'équipement, changement de nom par exemple, on récupère l'icône Zigbee. Si on modifie une commande de l'équipement, unité par exemple, on récupère l'icône Abeille.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Bonne année !

Point 1 Icones: cela provient probablement de la mise à jour du plugin. Peux tu me dire si tu as un repertoire Timers dans /var/www/html/plugins/Abeille/core/config/devices

Point 2: " si je clique sur un équipement, ...je me retrouve sur l'écran de gestion du plugin" : il y a eu des evolutions dans Abeille pour suivre le core Jeedom mais je vois que tu es en Jeedom 4.1.17 qui n'est pas testé avec Abeille. La version en cours pour Abeille est 4.0.62.

**Comment by Kenderv** [comment]
Bonjour, J'ai effectivement un répertoire Timer et non Timers. Ce répertoire est vide.

Pour le point 2 c'est vraiment dommage, le plus tôt sera le<mieux pour la modif.
Merci

**Comment by Tonio16** [comment]
Bonsoir

Pour les icônes, la dernière béta a résolu le problème pour moi.

Antoine

**Comment by KiwiHC16** [comment]
Point 1: tu as probablement le soucis de ce que je vais appeler les repertoires/fichiers fantômes...
Pas encore de solution mais ne dois pas empecher ton systeme de fonctionner sauf peut être en cas d inclusion de nouveau device.

**Comment by KiwiHC16** [comment]
@Kenderv, ou en es tu de ce sujet ?

**Comment by Kenderv** [comment]
Bonjour,
Toujours les mêmes soucis après avoir fait toutes le mises à jour. Je n'ai pas fait la mise à jour en béta indiquée par @Tonio16

**Comment by KiwiHC16** [comment]
@tcharp38 un exemple du problème de fichiers qui traînent ou upgrade qui ne clean avant mis à jour.

**Comment by tcharp38** [comment]
@KiwiHC16 Je vois pourquoi un fichier peut trainer mais je ne pige pas son implication car si le code mis à jour pointe ailleurs alors en dehors de la place gaspillée, ca ne doit pas poser de soucis.
Si soucis alors c'est l'installation qui est corrompue.
Non ?
Quoi qu'il en soit je bosse sur un systeme de check d'integrité et nettoyage de fichiers residuels. A venir...

**Comment by KiwiHC16** [comment]
@Kenderv: quelle est la situation actuellement ? As tu mis les dernieres versions stable d abeille ?

**Comment by Kenderv** [comment]
Bonjour @KiwiHC16 Oui, je suis à jour sur le plugin et j'ai pu retrouver les bonnes images de mes équipements en faisant une mise à jour de l'icône dans les paramètres des équipements qui affichaient l'Abeille. 
![image](https://user-images.githubusercontent.com/52486183/108192083-1d500480-7114-11eb-981c-c9a7ab76c521.png)
Depuis je n'ai pas réinclus d'autres équipements. Dans la Santé du plugin tout est au vert.

**Comment by KiwiHC16** [comment]
Ok je clos et si tu as de nouveaux soucis alors ouvres une autre.
