### ISSUE TITLE
Philips Hue Smart Button

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1609]
https://community.jeedom.com/t/philips-hue-smart-button-jeedom-v3-plugin-abeille/36350

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
```
[2021-01-12 12:09:12][debug]   ModelIdentifier='ROM001', trimmed='ROM001', [Modelisation]
```
ROM001

```
[2021-01-12 12:09:12][debug] Abeille1, Type=8100/Read individual attribute response, SQN=69, Addr=A71D, EP=01, ClustId=0000, AttrId=0004, AttrStatus=00, AttrDataType=42, AttrSize=0007
[2021-01-12 12:09:12][debug]   ManufacturerName='Philips', trimmed='Philips', {"Abeille1\/A71D":{"time":1610449752,"ManufacturerName":"Philips"}}, [Modelisation]
```
Philips

```
[2021-01-12 12:09:11][debug] Abeille1, Type=004d/Device announce, Addr=A71D, ExtAddr=0017880108036BA4, MACCapa=80, Rejoin=A2, [Modelisation]
```
MACCapa=80

```
[2021-01-12 12:09:12][debug] Abeille1, Type=8045/Active endpoints response, SQN=AD, Status=00, ShortAddr=A71D, EndPointCount=01, EndPointList=; 01, [Modelisation]
```
EP: 01

```
[2021-01-12 12:09:20][debug] Abeille1, Type=8043/Simple descriptor response, SQN=B8, Status=83, Addr=A71D, Length=00, EP=00, Profile=0000/Profil 0000 inconnu, DevId=0000/Profil 0000 inconnu, BitField=00
[2021-01-12 12:09:20][debug]   [Modelisation] Simple Descriptor Not Active
```
No simple desc

**Comment by KiwiHC16** [comment]
.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-12 à 12 31 06](https://user-images.githubusercontent.com/8549674/104309179-0c3b2480-54d2-11eb-80b0-98ace49b55d5.png)

**Comment by KiwiHC16** [comment]
Cluster from other sites:
0000 Basic
0001 Power Configuration
0003 Identify
FC00 unknown
1000 ZLL commissioning
and
0019 OTAU
0000 Basic
0003 Identify
0004 Group
0006 On/Off
0008 Levele Control
0005 Scene
1000 ZLL commissioning

it reports the buttonevent values on cluster 0xfc00

**Comment by KiwiHC16** [comment]
Maintenant que le switch est inclus, peux tu appuyer sur le bouton et partager les messages qui passent dans AbeilleParser ?

**Comment by Dites33** [comment]
Je n'ai rien dans le AbseilleParser, c'est vide, même quand je vais une ou plusieurs pression.
J'ai fait un reset et une nouvelle inclusion, toujours pareil, équipement ajouté mais rien dans le fichier AbeilleParser
Je suis en mode Debug
Normal ?

**Comment by KiwiHC16** [comment]
Je pense que c est normal car il faut certainement le paramétrer et c est la que la galere commence.

Il faut trouver comment le configurer.

**Comment by Dites33** [comment]
Les infos sur le site Zigate ne suffise pas c'est ca ?

https://zigate.fr/produits-philips-hue-compatibles-zigate/compatible/smartbutton/
https://zigbee.blakadder.com/Philips_ROM001.html

Parceque techniquement c'est un bouton ,donc juste on/off, que devrais je configurer de mon côté pour t'aider au mieux ?
T'en commander un ? J'ai déjà participé à la cagnotte mais si il le faut je veux bien t'en offrir un ...

**Comment by KiwiHC16** [comment]
"_Les infos sur le site Zigate ne suffise pas c'est ca ?_"
Non malheureusement, ce sont les mêmes infos qu on a recuperer dans tes logs.

**Comment by KiwiHC16** [comment]
"_T'en commander un ? J'ai déjà participé à la cagnotte mais si il le faut je veux bien t'en offrir un ..._"
Même si j 'en commande un, comme c est du Philips je ne suis même pas sure de pouvoir sniffer les discussions avec la GW car ils criptent avec une clef que je ne connais pas.
Il faudrait trouver quelqu un qui la deja fait.

**Comment by Dites33** [comment]
QQchose ici pourrait t'aider peut être @KiwiHC16 ?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2077

surtout la partie 

ebaauw commented on 4 Mar 2020
Received the button, paired it to deCONZ: resource is created, but no button events. In the deCONZ log, I see commands from the client clusters (causing config.group to be exposed), but nothing from 0xfc00.

Time to activate the sniffer.

The pairing sequence with the Hue bridge is very similar to that of the Lutron Aurora (see #2305 (comment)). It starts with the usual descriptor requests and reading of the Basic attributes. Then a series of 0x82 commands to cluster 0xfc00, but with a different payload than to the Aurora. The button responds with 0x83 commands on the same cluster. The sniffer didn't capture all of them, I'm afraid. Next, the writing of 0x0000/0x0031 with 0x000b, the bindings for 0xfc00 and 0x0001 and the attribute reporting for 0x0001/0x0021 (battery percentage): 900/900/2. Next the reading of unsupported attributes 0x0000/0x0033 and 0x0032.

On button actions the button sends command 0x00 from 0xfc00, with the same payload as the Aurora. As with the Aurora, I see no commands from the client clusters, so no hybrid mode like the Hue dimmer.

@ebaauw
 
Collaborator
ebaauw commented on 4 Mar 2020
Now receiving button events, incl. the eventduration! Not sure exactly what I've done to make the button change behaviour; I reset the button, paired it to deCONZ, ran my little deconz-cli-plugin script to replay the Aurora setup, bound the 0xfc00 cluster (tried to delete the binding first: no entry?!) and voilà... button events.

**Comment by KiwiHC16** [comment]
Très bon début d infos. Il faudra que je regarde les détails... Des que j ai du temps...

**Comment by Dites33** [comment]
Coucou ! As tu prévu de faire cette intégration ? Si ce n'est pas possible je dois regarder pour une autre solution.

**Comment by Dites33** [comment]
Je tente une derniere relance même sans beaucoup d'espoir vu le backlog. Peux tu me dire si c'est encore jouable ?
Merci @KiwiHC16

**Comment by tcharp38** [comment]
Salut @Dites33 
Toujours interessé ? Désolé pour ce tres vieux sujet.

**Comment by Dites33** [comment]
Merci pour la proposition même un an et demi après mais j'ai migré sur Homey :)
Bon courage !

**Comment by tcharp38** [comment]
Ok je me doutais un peu :)
Merci pour ton retour.
