### ISSUE TITLE
THERMOSTAT DANFOSS ALLY ZIGBEE 3.0

### ISSUE THREAD

**Issue by Fred7862** [KiwiHC16/Abeille#1611]
Bonjour,

J'ai acheté 3 Thermostats DANFOSS ALLY ZIGBEE 3.0 ( Référence 014G2420), il fonctionne sur le Plugins ZIGATE mais je voudrais les utiliser sur le Plugins ABEILLE où ils ne sont pas reconnu. J'ai déjà implémenté mes Xiaomi Température Carré sur Abeille.

Joint le log AbeilleParser, une photo et lien.

https://www.danfoss.com/fr-ch/campaigns/dhs/smart-heating/danfoss-ally/#tab-overview
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5803836/AbeilleParser.log)
![danfoss-tete-electronique-ally-zigbee-30](https://user-images.githubusercontent.com/64770674/104351514-c8621280-5505-11eb-87dd-7bdda6d1ec8f.jpg)

D'avance merci et je reste à ta disposition pour de plus ample renseignement,
Fred

**Comment by edgd1er** [comment]
Bonjour,

J'en ai acheté également mais je bloque depuis trois mois sur la redaction d'un json qui permettrait la reconnaissance. Mes connaissances en zigbee (endpoints, cluster, profile, full device, reduced device, ) et ma compréhension du code ne me permettent pas d'avancer ... (templates, lien widgets/templates, stockage infos mémoire, stockage infos bdd, ....)

A partir d'un fichier word trouvé dans les specs du produit, j'ai crée un fichier XLS reprenant les commandes, attributs, cluster etc
Tous les fichiers sont ici: https://github.com/edgd1er/Abeille/tree/master/core/config/devices/eTRV0100

J'essaie d'y travailler de temps en temps, mais le temps manque :(

pour aider voici la conf de domoticz qui reconnait ce device:
```
{
  "_comment": "Dansfoss Ally Radiator Thermostat 014G2461 ( https://assets.danfoss.com/documents/DOC235786405834/DOC235786405834.pdf )",
  "_version": "0.1",
  "Ep": {
    "01": {
	    "0000": "",
	    "0001": "",
	    "0003": "",
	    "000a": "",
		"0019": "",
		"0020": "",
	    "0201": "",
	    "0b05": "",
	    "Type": "Temp/ThermoSetpoint" }
  },
  "Type": "",
  "ClusterToBind": [ "0001", "0019", "0201" ],
  "ConfigureReporting": {
	"0001": {"Attributes": { "00": {"DataType": "20", "MinInterval":"0E10", "MaxInterval":"A8C0", "TimeOut":"0000","Change":"02"}}},
	"0201": {"Attributes": {
		"4000": {"DataType": "30", "MinInterval":"003C", "MaxInterval":"A8C0", "TimeOut":"0000","Change":"00"},
		"4012": {"DataType": "10", "MinInterval":"0001", "MaxInterval":"0000", "TimeOut":"0000","Change":"00"},
		"0000": {"DataType": "29", "MinInterval":"003C", "MaxInterval":"0E10", "TimeOut":"0000","Change":"0050"},
		"0012": {"DataType": "29", "MinInterval":"0001", "MaxInterval":"A8C0", "TimeOut":"0000","Change":"0001"},
		"0008": {"DataType": "20", "MinInterval":"012C", "MaxInterval":"A8C0", "TimeOut":"0000","Change":"01"}
		}}
  },
  "ReadAttributes": {
	"0000": [ "0000", "0001", "0002", "0003", "0004", "0005", "0006", "0007", "0010"] ,
	"0001": [ "0020" ],
	"0020": [ ],
	"0201": [ "0000", "0003", "0004", "0008", "0012", "0015", "0016", "001b", "001c", "4000" ],
	"0204": [ "0000", "0001", "4000" ],
	"0b05": [ "011c", "011d", "4000" ]
  },
  "PollingEnabled": 1
}
```



une ébauche ni fonctionnelle ni complete du json
```
{
    "eTRV0100": {
        "nameJeedom": "Dansfoss Ally Radiator Thermostat 014G2461",
        "comment": "Dansfoss Ally Radiator Thermostat 014G2461 ( https://assets.danfoss.com/documents/DOC353849556547/DOC353849556547.pdf ) ",
        "timeout": "0",
        "Categorie": {
            "heating": "1"
        },
        "configuration": {
            "uniqId": "5cfdgh0asd6rt78620b6b",
            "icone": "eTRV0100",
            "mainEP": "#EP#",
            "battery_type": "2x1,5V LR6 (AA)",
            "poll": "1"
        },
        "Commandes": {
            "include1": "nom",
            "include2": "societe",
            "include3": "SW",
            "include21": "getManufacturerName",
            "include22": "getModelIdentifier",
            "include23": "getSWBuild",
            "include24": "Identify",

            "include25 2 2 2": "spiritTemperatureConsigne",
            "include25 2 2": "spiritTemperatureConsigneGet",
            "include25 2": "spiritTemperatureConsigneSet",
            "include25 2 2 2 2": "spiritTemperature",
            "include25 2 2 3": "spiritTemperatureGet",
            "include25 2 2 3 2 3 2 2 2 2 2 2": "spiritBatterie-Pourcent",
            "include25 2 2 3 2 3 2 2 2 2": "BindShortToZigateBatterie",
            "include25 2 2 3 2 3 2 2 2 2 2": "spiritSetReportBatterie"
        }
    }
}
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Ils ne sont pas connus par Abeille et il est fort probable que du code spécifique soit nécessaire.
Avez vous une GW pour les piloter ?
Si vous m'en prêtez un, et si comme dit Fred7862, cela fonctionne avec le plugin zingage je pourrait regarder le dialogue et l implémenter dans Abeille.
Il y a plein d infos sur le net visiblement donc c est jouable.

**Comment by pipiche38** [comment]
@KiwiHC16 , je l'ai intégré il y a quelques mois déjà est c'est un exemple du genre. Du 100% Zigbee 3.0. 

Cluster 0x0201 et 0x0204 poru toute la gestion du Thermostat ( Setpoint, Local Temperature ...)

La doc commerciale: https://assets.danfoss.com/documents/DOC235786405834/DOC235786405834.pdf

**Comment by Fred7862** [comment]
@KiwiHC16, je n'ai pas de GW. Par contre, si cela peut aider, je peux t'envoyer un Thermostat ...

**Comment by KiwiHC16** [comment]
@pipiche38 super nouvelle.

@Fred7862 , je veux bien un thermostat car dans ce cas je peux regarder ce qu'a fait @pipiche38 pipiche et l implémenter dans Abeille.
Avec un vrai hard, je pourrai vérifier le bon comportement.

@Fred7862, Contactes moi par MP dans le Forum Jeedom: https://community.jeedom.com/tags/plugin-abeille

**Comment by KiwiHC16** [comment]
https://www.zigbee2mqtt.io/devices/014G2461.html

**Comment by edgd1er** [comment]
C'est utilisable comme fichier pour Abeille ? ça ne parle pas de endpoints, de reporting, de read attributes, de write attributes, de cluster, de profile.....

Par exemple, le cluster 201 expose l'attribut 4000 avec des min et max dans la définition de domoticz, est ce que Abeille permet ce type de définition ?

Y a t il qq part un tuto zigbee qui explique clairement, les relations entre cluster profile, read/write attributes, bref la théorie zigbee ? je suppose que l'encodage, lui est spécifique à la zigate.

L'image est un peu grande, je l'avais retaillée il a qq temps:
https://github.com/kiwiHC16/Abeille/blob/master/images/node_eTRV0100.png, la taille est assez proche, de ce fait, je ne sais pas si c'est utile...

**Comment by KiwiHC16** [comment]
D apres mes tests j'ai tout ce qu'il faut. Il me reste a ajouter les commandes dans le modele.

**Comment by KiwiHC16** [comment]
Il est dans la boite.
Sera dispo dans la beta ce lundi et en stable Lundi en 15.

**Comment by edgd1er** [comment]
Au vu du travail effectué, ce n'était pas juste copier/coller les templates pour créer un nouveau modèle, comme j'avais pu l’espérer au début.
Merci pour cet ajout.

**Comment by Fred7862** [comment]
Hâte de le tester, Merci encore
