### ISSUE TITLE
JEEDOM propose la mise à jour 4.1.17

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1613]
@KiwiHC16 

Salut

Peut-on suivre la montée de version de Jeedom ?
Je suis avec une zigate 3.1D et une version de Abeille de master_tcharp38, 2021-01-12 16:37:06

**Comment by tcharp38** [comment]
Salut @mickadam29 
Il te propose la 4.1.17 parce que tu es deja "hors stable" sinon je suis quasi sur qu'il ne te proposerait qu'une version "4.0.x".
Meme si tu me l'a  pas demandé :) je donne ma vision. On peut toujorus essayer d'etre un peu "en avance" mais on a deja tellement à faire avec des pbs purement Abeille que je crois que la priorité doit etre sur la derniere stable Jeedom pour pas cumuler les pbs.

Maintenant concernant la 4.1 et d'apres les modifs que j'ai vu, je pense qu'on a bien moins a faire cote Abeille que le passage en 4.0.

**Comment by mickadam29** [comment]
Effectivement j'ai activé il y a bien longtemps la possibilité d'avoir des betas. Mais jusque là, Jeedom ne proposait que de la 4.0. La 4.1 étant plutôt sympa, je me demandais si cela était raisonnable et surtout compatible Abeille. 
Mais je pense qu'ils ont officialisé la 4.1 en stable
![image](https://user-images.githubusercontent.com/36518012/104467498-a96f8900-55b6-11eb-8cf8-22e030bf7d92.png)

**Comment by tcharp38** [comment]
Ha oui alors si la 4.1 est officielle on n'a plus le choix.
T'es le cobaye alors en dehors du fait qu'Abeille n'est pas "marqué" compatible 4.1 ni 4.0 d'ailleurs (pas encore), dis nous si tu vois des soucis.
Merci pour ton aide

**Comment by mickadam29** [comment]
Je souris seul en te lisant ! Bon ben sauvegarde et tests. Je ferai un retour si anomalie. Il fait encore jour pour remettre mon éclairage en service au cas où !

**Comment by mickadam29** [comment]
Je voulais vous proposer ça. Une fonction Recherche. Ben elle est là

![image](https://user-images.githubusercontent.com/36518012/104469472-d886fa00-55b8-11eb-9c0c-afa3da5207fa.png)

**Comment by mickadam29** [comment]
Je me lance dans les tests de fonctionnement Abeille. Scénario, retour d'infos, timeout, etc.... On verra pour les inclusions et les plus complexes

**Comment by mickadam29** [comment]
En tout Synthèse a de la gueule !

![Uploading image.png…]()

**Comment by tcharp38** [comment]
> Je voulais vous proposer ça. Une fonction Recherche. Ben elle est là
> 
> ![image](https://user-images.githubusercontent.com/36518012/104469472-d886fa00-55b8-11eb-9c0c-afa3da5207fa.png)

Ha, une recherche dans les logs.
Ca t'est utile ?

**Comment by mickadam29** [comment]
Oui, ca va éviter de les exporter pour voir passer une inclusion par exemple. Ou un payload en particulier. J'ai pas encore tester la Recherche. J'ai testé mes interrupteurs Xiaomi, avec scénario. Ca fonctionne. Je redémarre complètement pour m'assurer que Jeedom -> Zigate -> Abeille soient toujours OK

**Comment by mickadam29** [comment]
Pas d'anomalie franche après le redémarrage. Mais capteurs remontent 0° mais dès qu'ils envoient une T° tout rentre dans l'ordre

![image](https://user-images.githubusercontent.com/36518012/104471772-885d6700-55bb-11eb-90dc-10d8af24b1ba.png)

**Comment by mickadam29** [comment]
@tcharp38 

Pour un join par exemple, la recherche s'avère efficace

![image](https://user-images.githubusercontent.com/36518012/104471659-682da800-55bb-11eb-8e1d-c0af37e9f633.png)

**Comment by tcharp38** [comment]
Oui une recherche sur le log affiché je comprends. Ca je m'en sers.
Une recherche globale dans tous les logs... j'ai + de mal.

**Comment by mickadam29** [comment]
Pas fais gaffe pour tous les logs, mais l'idée c'était le log en cours, un par un.

**Comment by KiwiHC16** [comment]
La 4.1.7 n'est pas la priorité pour moi. 128 issues ouvertes, soit encore beaucoup de boulot.
Une issue remontée par un utilisateur avec la 4.1.x, quand on clic sur une abeille on arrive pas sur la bonne page.

**Comment by tcharp38** [comment]
@mickadam29 Tu avais raison, la 4.1.17 est maintenant proposée par défaut.
![image](https://user-images.githubusercontent.com/35221038/104500261-7b05a400-55de-11eb-8e9c-f4758cedc207.png)

Donc on va tres vite avoir des utilisateurs 4.1.17.

**Comment by mickadam29** [comment]
@KiwiHC16 
Pour le problème de page, pourrais-tu remettre le numéro de l'issue.
Car chez moi, si je clique sur une abeille j'arrive sur la bonne page. Pas de bug à ma connaissance. Et je crois que j'avais fais une réponse à ce sujet. Le bug était déjà absent chez moi. Mais j'ai aussi la version de @tcharp38 avec tous les détails

![image](https://user-images.githubusercontent.com/36518012/104506258-6d9fe800-55e5-11eb-8d61-215725f901ea.png)
![image](https://user-images.githubusercontent.com/36518012/104506293-78f31380-55e5-11eb-80b0-a18096d907b2.png)
![image](https://user-images.githubusercontent.com/36518012/104506521-ca030780-55e5-11eb-941a-14d85e0d0bb5.png)

**Comment by mickadam29** [comment]
Pour le moment aucune anomalie. @KiwiHC16 je comprends que tu sois réticent. S'il y a des tests à faire en 4.1.17 puisque j'y suis passé, fais moi signe. Suis passé de 4.0.62 à 4.1.17. Je ferai des test plus poussés ce WE, comme par exemple une inclusion.

**Comment by KiwiHC16** [comment]
Si ça devient la mise a jour par défaut alors pas trop le choix. Je ferai aussi des tests pour voir...

**Comment by KiwiHC16** [comment]
VM Debian 9 - Jeedom DIY upgrade to 4.1.7: plus rien ne fonctionne. Equipements non visibles dans Dashboard,...

**Comment by mickadam29** [comment]
JEEDOM indique qu'il faut absolument BUSTER / V10 !

**Comment by mickadam29** [comment]
Attention, j'ai aussi eu peur à la fin de l'installation. Des erreurs dans la BDD en passant les versions intermédiaires (prévu par le script d'update). Puis, les niveaux à zéro pour mes capteurs de temp. J'ai redémarré. Les mises à jour des plugin se poursuivent après le reboot. OpenVpn a posé des problèmes. Résolus par un second reboot. MAIS RIEN A SIGNALER DANS ABEILLE ! C'EST UNE REUSSITE

**Comment by mickadam29** [comment]
En contrôlant, je me demande si j'ai pas moins de messages de timeout sur mes objets. Je vais contrôler ça

**Comment by KiwiHC16** [comment]
Sur install fresh Debian 10 Jeedom 4.1.17: Interface Jeedom semble Ok. Reste a faire test avec un vrai réseau zigbee avec une Zigate1.

**Comment by KiwiHC16** [comment]
Ziagte Ok 1.

Donc semble que 4.1.17 et Abeille soit compatible. Je clos.
