### ISSUE TITLE
Master broken.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1614]

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-13 à 17 40 08](https://user-images.githubusercontent.com/8549674/104481708-62898f80-55c6-11eb-937a-b8a2584063d4.png)

Select equipement name

![Capture d’écran 2021-01-13 à 17 40 36](https://user-images.githubusercontent.com/8549674/104481766-72a16f00-55c6-11eb-8cb3-3d6e52e7cfb5.png)

White page

With URL: http://abeille/index.php?v=d&p=Abeille&m=Abeille&id=701

**Comment by tcharp38** [comment]
Tu peux me donner me montrer l URL de la page blanche ?

**Comment by tcharp38** [comment]
Tu peux tester avec http://abeille/index.php?v=d&p=Abeille&m=AbeilleEq&id=701.
Il manque le "Eq"
J'ai eu ce souci avant redemarrer apache. qqch reste en cache

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-13 à 17 47 11](https://user-images.githubusercontent.com/8549674/104482582-5f42d380-55c7-11eb-8100-4e8e744d2d1c.png)

Bug est dans ce commit, car commit precendent pas de soucis.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-13 à 17 49 02](https://user-images.githubusercontent.com/8549674/104482783-a0d37e80-55c7-11eb-9811-52db2bf68a6d.png)

**Comment by tcharp38** [comment]
@mickadam29 
Toi qui est sous master, peux tu me dire si tu vois ce souci ?

**Comment by KiwiHC16** [comment]
J'ai le soucis sur un rpi3 et sur une VM.

**Comment by mickadam29** [comment]
Je regarde. J'ai mis ta version d'hier et depuis suis sous 4.1.17.

**Comment by KiwiHC16** [comment]
Sur VM Debian 10, Jeedom 4.1.17, abeille master:

Dashboard clic sur ruche:
![Capture d’écran 2021-01-14 à 00 33 18](https://user-images.githubusercontent.com/8549674/104525298-21ae6c80-5600-11eb-8d0a-f4b90e517d21.png)

Arrive sur page blanche:
![Capture d’écran 2021-01-14 à 00 33 57](https://user-images.githubusercontent.com/8549674/104525334-3559d300-5600-11eb-943f-007c5ab94d3f.png)

Depuis:
![Capture d’écran 2021-01-14 à 00 34 21](https://user-images.githubusercontent.com/8549674/104525355-43a7ef00-5600-11eb-8df5-395fb8b11035.png)

Clic sur ruche:
![Capture d’écran 2021-01-14 à 00 34 45](https://user-images.githubusercontent.com/8549674/104525375-50c4de00-5600-11eb-86c8-e99efccbc568.png)

Ca fonctionne:
![Capture d’écran 2021-01-14 à 00 35 21](https://user-images.githubusercontent.com/8549674/104525426-689c6200-5600-11eb-8bd6-47f379829b7f.png)

Mais le troisième Tab plante (on perd les Tab):
![Capture d’écran 2021-01-14 à 00 36 54](https://user-images.githubusercontent.com/8549674/104525509-9da8b480-5600-11eb-9705-d7b583e32a9a.png)

![Capture d’écran 2021-01-14 à 00 37 10](https://user-images.githubusercontent.com/8549674/104525525-a7321c80-5600-11eb-9424-00469800305b.png)

**Comment by mickadam29** [comment]
Désolé ma box vient de me lâcher. Plus d’internet. J’ai la même chose. Page blanche en cliquant sur le nom de l’objet depuis la page synthèse

**Comment by tcharp38** [comment]
Ok je comprends le souci si
- depuis le dashboard
- ou page synthese
- depuis n'importe ou autre que la page de gestion

Mais depuis la page de gestion c'est toujours page blanche ?

**Comment by tcharp38** [comment]
Je viens de pousser un correctif.
Normalement en cliquant sur un EQ de n'importe ou on doit arriver au bon endroit.
Dites moi si ca colle.

**Comment by KiwiHC16** [comment]
Le PR résoud le soucis. 

Le tab Commande disparait si la liste des commandes est plus longue que la page. En faisant un scroll vers le bas les tab apparaissent mais c est perturbant car les tab disparaissent.
(Test fait sur Jeedom 4.1.17)
