### ISSUE TITLE
Affichage contenu Tab - Param

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1618]
Affiche les paragraphes Télécommandes et Calibration que quand necessaire.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-14 à 12 23 34](https://user-images.githubusercontent.com/8549674/104585618-92877000-5664-11eb-82ef-57b0b479a0b1.png)

**Comment by tcharp38** [comment]
Quel est le but de la partie "telecommande" ?
Un exemple d'utilisation ?

**Comment by tcharp38** [comment]
@KiwiHC16 Je te laisse tester et clore si ca te convient.

**Comment by KiwiHC16** [comment]
Nickel. Je viens de pousser la modification du son remote et ça fonctionne. Je clos. Cela faisant si longtemps que j avais ce truc en tête ;-)
