### ISSUE TITLE
Comment fait on une alarme sur une batterie faible ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#162]

**Comment by edgd1er** [comment]
avec /index.php?v=d&p=eqAnalyse, tu peux définir des actions selon les niveaux  et des couleurs de widget.
Effectivement comme tu l'indiques dans le #161, il faut pouvoir trouver les periph dans ce menu...

**Comment by edgd1er** [comment]
a priori, **battery_type** ne provoque pas l'affichage dans le menu Analyse->Equipement. l'ajout du type de batterie ne permet pas son apparition dans le menu equipement. 
J'ai des periph zwave dont ce champs n'est pas renseigné mais qui apparaissent qd même.
Je me demande la zone status dans conf avancée qui montre un battery: 30 ne déclencherait pas les alarmes batterie:
{"lastCommunication":"2018-03-03 18:30:20","timeout":0,"warning":0,"danger":0,"battery":**30**,"batteryDatetime":"2018-03-03 18:30:19","batterydanger":0,"batterywarning":0}

Concernant l'alarme, ça se passerait dans le champ configuration. Exemple pour du zwave en bdd:
{"product_name":"EUR_STELLAZ Wall Radiator Thermostat Valve Control","manufacturer_id":328,"product_type":1,"product_id":1,"createtime":"2017-07-22 11:57:46","updatetime":"2018-01-19 06:53:44","fileconf":"","conf_version":"","battery_type":"",**"battery_danger_threshold":"5","battery_warning_threshold":"15"**}

**Comment by KiwiHC16** [comment]
Page Batterie Equipement
http://jeedomzwave/index.php?v=d&p=eqAnalyse 
<title>EqAnalyse - Jeedom</title>

desktop/php/eqAnalyse.php
$eqLogic->getConfiguration('battery_type'
Exemple zwave: "battery_type":"2x1.5V AAA"
Exemple zigbee: "battery_type":"2x1.5V AAA"

$eqLogic->getStatus('battery'
Exemple zwave: "battery":48
Exemple zigbee: "battery":48 (mis dans la base mais n'apparait pas dans info jeedom, il faut le charger en memoire probablement au demarage et sur nouvelle valeur)

**Comment by KiwiHC16** [comment]
First implementation in push today.
Calibration to Volt min=2,7 et max=3,1 en prenant l entree en mV pour calculer un %.

**Comment by KiwiHC16** [comment]
Probleme c est que la valeur n'est probablement pas standardisée dans la mesure ou pour Xiaomi on remonte des milliV mais est toujours le cas et si pas une batterie de 3V (Est ce qu'on utilise l info Type de piles) ?

Je ne vois aucun traitement pour l affichage donc la standardisation/normalisation doit être faite lors du stockage de la valeur au plus tard en etant un % de batterie.

**Comment by KiwiHC16** [comment]
Maintenent les equipements sont dans le menu Analyses - Equipement.
Comment fait on une alarme ?

**Comment by KiwiHC16** [comment]
https://jeedom.github.io/core/fr_FR/eqAnalyse

**Comment by KiwiHC16** [comment]
https://www.jeedom.com/forum/viewtopic.php?f=144&t=31954

**Comment by KiwiHC16** [comment]
CheckBattery.php et CheckAlive.php ajouté dans folder resource.
Pour l instant mis sous la forme d un script dans la plugin script pour tests. Si ok voir comment les mettres dans le plugin Abeille.

**Comment by KiwiHC16** [comment]
Un petit scrip associé a scenario en test:
Objet script:
![capture d ecran 2018-03-16 a 18 40 49](https://user-images.githubusercontent.com/8549674/37536135-0552caee-294a-11e8-8ef2-aa881e8aa4d5.png)
2 commandes avec les scripts: CheckBattery.php et CheckAlive.php (see folder resource
![capture d ecran 2018-03-16 a 18 41 06](https://user-images.githubusercontent.com/8549674/37536141-097f3210-294a-11e8-8231-9ad938372eab.png)
Scenario pour monitorer:
![capture d ecran 2018-03-16 a 18 40 28](https://user-images.githubusercontent.com/8549674/37536182-2941d152-294a-11e8-9ea2-a0f5634d606b.png)
![capture d ecran 2018-03-16 a 18 40 20](https://user-images.githubusercontent.com/8549674/37536189-2ba50bb2-294a-11e8-92df-58d7df896254.png)

En cours de test chez moi.

**Comment by KiwiHC16** [comment]
https://github.com/KiwiHC16/Abeille/blob/master/Documentation/064_Sante_Des_Equipements.adoc
