### ISSUE TITLE
Inclusion Xiaomi lum: "PHP Notice: Undefined variable: Command"

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1620]
> [14-Jan-2021 16:55:02 Europe/Brussels] PHP Notice:  Undefined variable: Command in /var/www/html/plugins/Abeille/core/class/AbeilleCmdPrepare.class.php on line 1464
> [14-Jan-2021 16:55:02 Europe/Brussels] PHP Notice:  Undefined variable: Command in /var/www/html/plugins/Abeille/core/class/AbeilleCmdPrepare.class.php on line 1465

Apres modif du code pour capturer l'erreur

> [2021-01-14 17:02:13][debug] sendCmdToZigate(Dest=Abeille1, cmd=0043, len=0003, datas=BEF70B)
> [2021-01-14 17:02:13][debug]   Envoi de la commande a la zigate: /dev/ttyS1-0043-0003-BEF70B
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/BEF7/ -> 1
> [2021-01-14 17:02:13][debug]   L2 - procmsg({"topic":"CmdAbeille1\/BEF7\/","payload":"1","priority":1,"message":null})
> [2021-01-14 17:02:13][debug]   L2 - procmsg("CmdAbeille1\/BEF7\/" , "1" , 1)
> [2021-01-14 17:02:13][debug]   WARNING: Unkown command ! (topic=CmdAbeille1/BEF7/)
> [2021-01-14 17:02:13][debug]   J'ai 3 commande(s) pour la zigate a envoyer.
>

**Comment by KiwiHC16** [comment]
C est une mer douille que je viens de corriger dans le master. J'attendais ta correction pour pousser la mienne. Tu ne devrais plus avoir ce soucis.
https://github.com/KiwiHC16/Abeille/commit/cb81ef6805c472e44b117440ed3713a0ac80a54e
Je clos, si tu as encore rouvre
(Effaces/Re-crées les équipement créés ces derniers jour car ils ne sont pas correctes et provoquent les soucis ci dessus.  )
