### ISSUE TITLE
Telecommande GROUP ne fonctionne plus

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1622]
Bonjour,

SUis-je le seul dont les telecommandes groupes ne fonctionnent plus depuis le passage debian buster jeedom 4.1.17 avec pizigate 3.1d et Version Abeille :master_tcharp38, 2021-01-14 11:33:41 ?

Ou est-ce localisé sur mon install ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Comme tu es sur la master peux tu mettre a jour et vérifier car il y a eu changement sur ce sujet aujourd'hui.

**Comment by KiwiHC16** [comment]
Correction mise dans master.

**Comment by bouboun59** [comment]
ok ca fonctionne merci
