### ISSUE TITLE
Inclusion volet Profalux impossible

### ISSUE THREAD

**Issue by Fatal926** [KiwiHC16/Abeille#1625]
Bonjour,

Je suis actuellement embêter avec mes volet roulants profalux

Equipement: Raspberry PI 4, Pizigate et volet profalux installé en 2020.

Je tourne actuellement sous jeedom 4.1.17

Dans un 1er temps j'aimerai confirmation de quel port il faut que j'utilise faire fonctionné le pizigate.

Ensuite, dans le plugin abeille, quand je déroule le menu "pizigate", dans le menu déroulant "port" je n'ai rien qui apparait es-ce normal?

![Sans titre](https://user-images.githubusercontent.com/63459626/104843240-d16a2f80-58c9-11eb-8dd2-d29c100d0250.png)

Je débute dans la domotique, donc je ne maitrise pas encore tout.

Merci d'avance pour votre aide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Regardes la dedans si tu trouves ton bonheur:
http://kiwihc16.free.fr/InstallationPiZiGate.html

**Comment by tcharp38** [comment]
Salut @Fatal926 
Tu dois commencer par declarer ta zigate (section zigate), ca veut dire indiquer sur quel port elle se trouve (surement qqch comme ttyS1), eventuellement "tester" pour confirmer que le port est le bon, l'activer, et sauvegarder.

**Comment by Fatal926** [comment]
Merci de vos réponse, quand tu dis qu'il faut indiqué sur quel port elle est, la est justement ma question, comment savoir, j'ai parcouru pas mal de forum, et je rencontre des port "ttyAMA0", "serial0" et "ttys1". Donc je ne sais pas quel est le bon.
Y'a t'il une méthode pour le savoir (je précise que je part d'un installation propre du RPI4 avec uniquement jeedom d'installé sans aucun autre plugin qu'abeille).

**Comment by tcharp38** [comment]
D'apres les forums zigate ca semble etre ttyAMA0. Alors tente un test dessus.
Passe aussi en mode debug (en haut à droite + sauvegarder) pour avoir + de logs.
Tu ne risque rien à tenter ttyS1 non plus.

**Comment by Fatal926** [comment]
Ah oui et dans la liste des port je n'ai pas tous les ports que j'ai cité ci-dessus

![1](https://user-images.githubusercontent.com/63459626/104851816-88c96b00-58f7-11eb-8914-80f8422a78f6.jpg)
![2](https://user-images.githubusercontent.com/63459626/104851817-89620180-58f7-11eb-9e69-4f98e059ae26.jpg)
![3](https://user-images.githubusercontent.com/63459626/104851818-89620180-58f7-11eb-8cdb-399bdccaf337.jpg)
![4](https://user-images.githubusercontent.com/63459626/104851819-89fa9800-58f7-11eb-98f2-d0b846c8ef25.jpg)

**Comment by tcharp38** [comment]
Oublie la section pizigate. Tu n'en as pas besoin.
Choisis ttyAMA0 puis tester. Si OK alors c'est bon, sinon le log est dans AbeilleConfig.
Faire la meme chose avec ttyS1 si pas OK
Je pense que c'est un de ces 2 la

**Comment by Fatal926** [comment]
J'ai testé avec ttyAMA0, le demon passe bien en OK mais quand je lance une inclusion la pizigate ne clignote pas et l'inclusion ne fonctionne pas.
Le ttyS1 n'est pas dans la liste des port a sélectionné :(

**Comment by Fatal926** [comment]
Petite question, je vais surement repartir de zéro vu tous les test que j'ai effectué.

A partir du moment où j'ai installé raspeberryOS et que j'ai installé jeedom, y'a t'il d'autre chose à faire avant d'installer le plugin abeille.
Parce que sur le site de la zigate il dise plusieurs chose a faire, mais le plugin abeille ne le fait t'il pas automatiquement ?

**Comment by tcharp38** [comment]
Ok si le test sur AMA0 est OK c'est bon.

Peux tu montrer un snapshot de ta page config, puis celui de la page santé (plugins>protocole domotique>Abeille>Santé) ?

**Comment by tcharp38** [comment]
Je viens de revoir un peu le chapitre "installation" pour essayer de le clarifier.
https://kiwihc16.github.io/AbeilleDoc/Installation.html#

**Comment by KiwiHC16** [comment]
Non le plugin Abeille ne fait pas tout car: 
- les modifications systèmes sont toujours délicates
-  le nombre de configuration utilisateur est trop important
- ...

On a consolidé la doc et on peut aider (comme le fait @tchap38, et par la meme occasion mettre à jour la doc).

**Comment by Fatal926** [comment]
Merci pour vos retour, je m'y remet le weekend prochain, pas trop le temps en semaine, mais je vous tiens informé

**Comment by Fatal926** [comment]
Bonjour,

Alors je me remet un peu dessus voila ou j'en suis:

Quand j'accède au menu de la gestion du plugin abeille: Il y a un point d'interrogation dans la case verte a coté de la case "tester".

![screencapture-jeedomdefatal-ovh-index-php-2021-01-23-10_04_56_page-0001](https://user-images.githubusercontent.com/63459626/105574750-f8f84680-5d66-11eb-9818-263e641f3d96.jpg)

Quand je clic sur tester le point d'interrogation disparait et passe en FW031D donc cela apparait être bon.

![2](https://user-images.githubusercontent.com/63459626/105574754-001f5480-5d67-11eb-8e13-729508effa19.jpg)

Mais quand je retourne dans le plugin abeille et lance une inclusion, la led de la pizigate ne clignote pas.

Je précise avoir lancer une mise a jour de la pizigate depuis le plugin abeille et cette dernière c'est bien déroule jusqu'à la fin.

![Sante](https://user-images.githubusercontent.com/63459626/105574343-3c04ea80-5d64-11eb-8af5-619d85c5bfac.jpg)

![screencapture-jeedomdefatal-ovh-index-php-2021-01-23-10_30_12_page-0001](https://user-images.githubusercontent.com/63459626/105574760-0a415300-5d67-11eb-826e-6135b9228170.jpg)

![Etat zigate](https://user-images.githubusercontent.com/63459626/105574765-0f9e9d80-5d67-11eb-952d-693c136c8a3c.jpg)

**Comment by KiwiHC16** [comment]
Peux tu partager un log Abeille et un log AbeilleParser quand le plugin est en mode debug ?

**Comment by tcharp38** [comment]
https://github.com/KiwiHC16/Abeille/issues/1994

**Comment by tcharp38** [comment]
@Fatal926 
Salut. Quel est le status de ce point ?
Merci

**Comment by tcharp38** [comment]
Salut
Aucune nouvelle depuis le 23 jan.
Voir #1994 si besoin.
L'inclusion et profalux volet a ete revue.
Je clos le point.
