### ISSUE TITLE
Page "Network list" - Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by bocquetm** [KiwiHC16/Abeille#1626]
Bonjour à tous,

depuis le passage en 4.1, j'ai une erreur JS:

![image](https://user-images.githubusercontent.com/8374552/104894783-69712300-5975-11eb-9ba3-07e41ab9ba03.png)

![image](https://user-images.githubusercontent.com/8374552/104895276-f61be100-5975-11eb-815d-90669cbc7fb2.png)

Ce qui correspond au code suivant: 

![image](https://user-images.githubusercontent.com/8374552/104895403-1ea3db00-5976-11eb-9d53-0f2bd965e8ad.png)

Celle-ci se produit quand je refresh le réseau: 

![image](https://user-images.githubusercontent.com/8374552/104895580-5d399580-5976-11eb-925c-c41409c3fd09.png)

Une idée ?

Pour info, je suis revenu à la version stable de Abeille de ce matin.

Cdt,

Mickael

**Comment by tcharp38** [comment]
Salut
Ho ca ressemble à un vieux souci ca.
La 4.1 est trop recente et ca nous a pris de court.
Je suppose que tu es à jour donc sur la derniere stable.
Si ca te tente, tu peux tester la beta du moment.

Je fais qq essais de mon cote

**Comment by bocquetm** [comment]
Salut @tcharp38,

oui ça peut se tenter :) Si tu vois le souci et que tu lances une correction, fais moi signe, je repasserai en beta dans le store pour valider si c'est corrigé ou non. J'ai pas encore fouillé dans tout le plugin pour voir s'il y avait d'autres erreurs de ce type sur certaines pages.

**Comment by tcharp38** [comment]
Oublie la beta.
Je confirme le souci :(
Je m'y colle

**Comment by tcharp38** [comment]
Je note néanmoins que malgre l'erreur la collecte semble faite. Un nouvel appui sur Abeille1 fait apparaitre le resultat

**Comment by tcharp38** [comment]
Je crois que j'ai trouvé. PR en cours pour le master.
Si tu veux tester de ton côté, remplace (decompresse) le fichier attaché en "desktop/js/network.js"

[network.zip](https://github.com/KiwiHC16/Abeille/files/5829478/network.zip)

**Comment by bocquetm** [comment]
Oui oui, la collecte est bien effectuée.
Top si tu as trouvé le pb !

Je teste et te redis.

**Comment by bocquetm** [comment]
Alors le refresh fonctionne, mais l'affichage est planté. Et il y a une autre erreur quand on va dans l'onglet graphique réseau et plus rien ne s'affiche.

![image](https://user-images.githubusercontent.com/8374552/104905689-ff5f7a80-5982-11eb-9e02-fa064b06e432.png)

![image](https://user-images.githubusercontent.com/8374552/104905470-aee81d00-5982-11eb-8a24-03ae359efbc8.png)

![image](https://user-images.githubusercontent.com/8374552/104905532-ccb58200-5982-11eb-9e81-5a5bc03edab8.png)

**Comment by tcharp38** [comment]
Ha oui.
Désolé. En fait le fichier que je t'ai filé est trop en avance par rapport à ta version.
Je peux t'en faire un autre, juste pour test.

**Comment by bocquetm** [comment]
Je me disais bien, en faisant un diff un paquet de choses avaient changé ^^

Ca me va, si ça ne te prend pas trop de temps. Sinon donne moi juste le bout de code modifié et la ligne et je le remplace.

**Comment by tcharp38** [comment]
[network.zip](https://github.com/KiwiHC16/Abeille/files/5829693/network.zip)

1 seule ligne modifée. Ca devrait le faire

**Comment by bocquetm** [comment]
J'ai bien modifié la ligne pour passer en POST et l'erreur JS a bien disparu.

**Comment by tcharp38** [comment]
Donc dispo dans la prochaine beta.

**Comment by bocquetm** [comment]
Top merci :)

Sinon je sais pas si un case est ouvert mais j'ai l'impression que le refresh du network fonctionne aléatoirement, les devices ne s'affichent pas complétement à chaque fois. On peut avoir tous les éqs, ensuite juste 3, ensuite plus qu'un etc etc. C'est normal ? Il me semblait que ça marchait bien avant. On va pas s'étendre sur le sujet ici, mais est-ce connu ? Sinon j'ouvrirai une issue.

**Comment by tcharp38** [comment]
Ouvre un point different avec des details pour reproduire quand c'est possible.
Ca me dit qqch et je pense que je ne suis pas allé jusqu'au bout de mes modifs.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by tcharp38** [comment]
Pb résolu

**Comment by KiwiHC16** [comment]
Mentionné ici encore:
https://community.jeedom.com/t/mise-a-jour-jeedom-et-plugin-abeille/50618/3

**Comment by KiwiHC16** [comment]
@tcharp38 Tu as repondu en fait donc je reclus.
