### ISSUE TITLE
Visibilité sur les processus.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1630]
Avec le nouveau mode de gestion des processus, je ne sais pas si le plugin est vert et si j ai bien tous les processus en courss d execussion. Comment visualisé simplement.

**Comment by KiwiHC16** [comment]
Pour l instant je peux faire un Abeille -> Support -> Processus mais cela me demande de réfléchir au configs de zigate et donc a la liste que je dois avoir.

Il serait cool d avoir une page avec la liste de processus attendus et si ils sont la ou pas.

Page santé ?

**Comment by KiwiHC16** [comment]
Par exemple:
![Capture d’écran 2021-01-18 à 11 40 07](https://user-images.githubusercontent.com/8549674/104904827-eaceb280-5981-11eb-995a-2253b957d120.png)

Il fat que je fouille pour voir que je ne vois pas la zigate 2 alors qu abeille est vert
![Capture d’écran 2021-01-18 à 11 41 03](https://user-images.githubusercontent.com/8549674/104904958-0cc83500-5982-11eb-810e-1a57063c85b4.png)

Et que j ai un message qui ne m aide pas trouvé la source du soucis
![Capture d’écran 2021-01-18 à 11 41 26](https://user-images.githubusercontent.com/8549674/104905020-1a7dba80-5982-11eb-83b0-ee3db8db11f2.png)

**Comment by tcharp38** [comment]
Oui, une icone par demon attendu, vert si OK, rouge si dead.
Ca pourrait etre sympa.
Je m'y collerai si personne ne s'y est lancé avant, des que j'ai exclusé un peu ma liste en cours.

**Comment by edgd1er** [comment]
@tcharp38 

Lorsque la ligne "Danger, il manque au moins un process" apparait , et si tes ruches sont récentes, elles sont capables de recevoir un systemMessage et le daemon manquant est affiché dans la ruche. Dans tout les cas, le processus manquant devrait etre relancé. S'il est manquant a chaque fois, c'est peut etre un bug, ou qq chose fait planter le demon.

je pense que tu peux t'appuyer ou cloner la fonction [checkAllDaemons](https://github.com/KiwiHC16/Abeille/blob/feff2dea71c96222fc7596190a409b8320c9516a/resources/AbeilleDeamon/lib/AbeilleTools.php#L322) pour faire une page qui liste les processus attendus et ceux présents. C'est exactement ce que fait getMissingDaemons, il reste la mise en page html a faire.

**Comment by tcharp38** [comment]
@edgd1er 
Ok merci.

Quel est ton status vis a vis du controle des processus ? Tu as encore des trucs à faire ou tu consideres que c'est bon?
En ce qui me concerne il y a des trucs pas propre qui restent encore, comme le redemarrage des demons. Voir #1632 par ex.
J'ai déja eu ca plein de fois et je pense que le fait de "killer" un demon n'est pas tres propre. Toutes ses ressources ne sont pas forcement liberées tout de suite.

**Comment by KiwiHC16** [comment]
Merci @edgd1er me rafraichir la memoire !!! J avais oublié. C est un truc a garder pour faire des scenarii dans Jeedom.

Pour les utilisateurs lambdas, un truc graphique serait certainement très bien.

@edgd1er as tu fait un petit bout de doc sur le systemMessage ? Peut etre devrions nous avoir ca pour nous rememorer ce qu on a fait quelques mois plutôt !

**Comment by edgd1er** [comment]
@tcharp38, pour moi le contrôle des processus est ok et validé par 3 mois d'utilisation quand il y a 1 zigate. Comme dis lors des devs, je n'ai pas plusieurs zigates, donc j'ai validé les cas d'erreur (zigate mal configuré et donc daemon qui ne démarre pas) mais pas les cas passants. je vais regarder #1632 

@KiwiHC16 , le code commençant a devenir volumineux, il devient nécessaire de mettre en place une phpdoc, il me semble que cela etait en discussion. En attendant, avec les commentaires comme il y a pour la fonction checkalldaemon, un bon ide peut aller chercher cette info et l'afficher. cf capture ci dessous: intelliJ: ctrl+q


![image](https://user-images.githubusercontent.com/3601462/104961794-52631d00-59d7-11eb-9daa-a1bd932d5ab6.png)

**Comment by KiwiHC16** [comment]
Oui je rajoute du phpdoc partout ou je passe quasiment.
Oui je pense que c est surtout de l affichage a faire. Le code de detection/gestion doit deja exister, je suppose.

**Comment by tcharp38** [comment]
C'est pret. Livraison lundi car pas connecté ce WE.
![image](https://user-images.githubusercontent.com/35221038/105497396-1245b800-5cbf-11eb-88cb-4aa95548f892.png)

**Comment by KiwiHC16** [comment]
C est cool !

**Comment by tcharp38** [comment]
Livré.
Je te laisse tester en multi zigates et cloturer si ca convient.

**Comment by KiwiHC16** [comment]
Sur deux systèmes c est nickel. Je n'ai pas testé en cas de défaillance mais on verra avec l experience. Je clos et si soucis dans le future on ouvrira un cas spécifique.
Merci !
