### ISSUE TITLE
Jeedom "V4.1.17" Abeille "beta, 2021-01-18": Call to a member function getLogicalid() on bool

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1631]
Zone dev - Afficher - Activer

![Capture d’écran 2021-01-18 à 11 35 58](https://user-images.githubusercontent.com/8549674/104904331-56fce680-5981-11eb-8e5f-f260a9e9c3b0.png)

![Capture d’écran 2021-01-18 à 11 36 30](https://user-images.githubusercontent.com/8549674/104904401-6a0fb680-5981-11eb-8481-469d68381ee3.png)

**Comment by tcharp38** [comment]
Oui j'ai vu ca aussi.
Je pense que ta session est expirée.
Peux tu verifier ca ?

C est dans le pipe de toute façon

**Comment by tcharp38** [comment]
Si jamais tu sais reproduire facilement dis moi commen tu fais. La je n'y arrive plus mais ca reviendra.

**Comment by KiwiHC16** [comment]
Je ne l ai plus non plus. Bon je clos alors, on a d autres sujets.

**Comment by tcharp38** [comment]
Je crois que malheureusement c'est un cas assez aléatoire. Pas facile de reproduire à la demande.
