### ISSUE TITLE
Début tumultueux avec zigate et Abeille

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#1632]
Bonjour,

Ca fait 3 jours que j’essaie d’installer ma zigate avec abeille pour passer tout mon zigbee dessus mais je n’arrive pas rien…

Je ne sais plus ou donner de la tête. J’ai essayé avec les firmware 3.1c et 3.1d mais rien…
Jeedom est en VM sur proxmox, en version 4.1.17
Abeille : 2021-01-18 09:07:21

J’ai essayé de revenir a d’ancienne save de jeedom, d’arreter, redémarrer.
Désinstaller réinstaller le plugin, les dépendances et j’en passe.
Je craque, j’ai besoin d’aide ^^
Est ce que ce souci est courant ou c’est moi?
Je dois repartir sur une installation neuve de jeedom ? ou j’abandonne tout

Merci =)

Voici tout les log et les screen depuis mon dernier reboot et vidange des logs…
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5831344/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/5831346/AbeilleConfig.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5831347/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5831348/AbeilleSerialRead1.log)
![config](https://user-images.githubusercontent.com/49479084/104939862-406e8380-59b1-11eb-9d3f-c0f8288b168d.JPG)
![zigate](https://user-images.githubusercontent.com/49479084/104939871-42384700-59b1-11eb-9184-01744647ea59.JPG)

**Comment by tcharp38** [comment]
Salut.
Le point bloquant que je vois est ta zigate qui n'est pas "OK".
Si tu regardes le log "AbeilleConfig" tu vois ca

= ERREUR: Le port est utilisé par le process '1102'.
=         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
=         Details du process 1102:
=           PPid=530, cmd='/usr/sbin/apache2 -k start'

Bref, la zigate n'est pas libre. Donc Abeille n'arrive pas à communiquer avec elle sans soucis.

Tu as d'autres plugins qui pourraient par ex perturber ca ?

**Comment by Jake309** [comment]
Non, mais ce message, je ne l'air que quand je refais un second, 3eme etc test. Au 1er j'ai pas ce message la.
J'ai cherché un moment, et j'ai fini par me dire que c'était Abeille qui ne le libérait pas vraiment avant de relancer un test du port.
Sans réelle certitude

**Comment by tcharp38** [comment]
Ha oui tu dois avoir raison. Il y a effectivement un pb en cours cote Abeille sur le redemarrage des démons.
Donc si c'était ok au premier setup alors c'est bien.
Reste qu'il faut retrouver un etat démarré stable.

Que dit la page santé ? (plugins>domotique>Abeille>Santé)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
AbeilleCmd: "Je n'ai pas de Ack"
AbeilleParser: Vide
AbeilleSerial: Vide
AbeilleConfig: info partagée par @tcharp38

En gros Abeille/Jeedom semble fonctionner mais la discussion avec la zigate n'est pas en place.

Tu confirmes que c est une Zigate USB ?

**Comment by KiwiHC16** [comment]
As tu fais les tests 3 et 4 ?
http://kiwihc16.free.fr/Debug.html?highlight=echo#connection

**Comment by KiwiHC16** [comment]
Je laisse @tcharp38 t'aider. Si vous n'y parvenez pas je peux faire une investigation a distance ce soir apres 21h30. Pour cela il me faudra un partage d ecran avec AnyDesk.com avec une interface jeedom, 2 ssh ouverts. Tiens nous au courant.

**Comment by Jake309** [comment]
> AbeilleCmd: "Je n'ai pas de Ack"
> AbeilleParser: Vide
> AbeilleSerial: Vide
> AbeilleConfig: info partagée par @tcharp38
> 
> En gros Abeille/Jeedom semble fonctionner mais la discussion avec la zigate n'est pas en place.
> 
> Tu confirmes que c est une Zigate USB ?

Zigate USB oui.
Les 2 log vide sont bien vide, pas de pb, je refais une désinstallation du plugin, reboot, réinstalle, et relance le tuto installation avec les log en debug. debug suffit ou vous voulez plus en log ? 
et je post le resultat.

La méthode 2 et 3 sont faites. la 3 me retourne pas d'erreur mais la zigate clignote pas.
Je vais remonter une VM avec un jeedom vierge et je vais installer que Abeille pour tester.
Mais après le repas, sinon la patronne va raler ;)

Merci

**Comment by KiwiHC16** [comment]
Je viens de relire ta description et tu es dans une VM proxmox.
Pour moi le problème vient de la. Le port série n'est pas visible d'Abeille. proxmox ne fait pas le boulot.
Un autre utilisateur avait un soucis identique.
Je ne peux aider je n'ai jamais utilisé proxmox.
Regardes comment passer un port série du host vers la VM avec proxmox.

**Comment by Jake309** [comment]
Donc, j'ai refais le teste sur un jeedom vierge.
Le pb est le même. au niveau des screen, du plugin et de la conf, c'est les meme.

Non, je pense pas que la vm et proxmox soit en cause, car abeille voit bien la zigate et il envoie le message, juste qu'il n'y a pas de retour.
Ma clé bluetooth avec BLEA est configuré comme ca aussi et ca ne pose pas de souci. 
Après, je pourrai faire une image d'un de mes pc pour faire une install debian en direct si on veut en etre sur.
Mais comme l'inclusion n'a pas l'air de fonctionner non plus sous windows quand je test avec testGUI (voyant clignotant mais pas de message et l'équipement ne s'appaire pas) je me dis qu'il y a quand meme un pb matériel...


Je mets les log du jeedom tout neuf, mais ils semble identique.
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5832306/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/5832307/AbeilleConfig.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5832308/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5832310/AbeilleSerialRead1.log)

**Comment by Jake309** [comment]
J'ai essayé la méthode 4 en plus sur la jeedom neuve, et je n'ai pas vue passer les trame dnas le 1er terminal...

**Comment by edgd1er** [comment]
Bonsoir @Jake309 

Typiquement, ta zigate ne discute pas avec le plugin. Cette ligne indique que la zigate ne répond pas.
```
[2021-01-18 14:54:24][debug]   Envoi de la commande a la zigate: /dev/ttyUSB0-0010-0000-
[2021-01-18 14:54:25][debug] Je n'ai pas de Ack (Status) depuis 1 secondes avec now = 1610978065 et timeLastAck = 1610978064 donc je considère la zigate dispo.....
```
Les causes sont souvent matériel pour ce cas la:
* clé zwave/wifi ou autre trop prés.
* mauvaise alimentation du hub si sur hub
* hub chinois pas super respectueux des normes ( j ai ça a la maison)
* raccord ou rallong usb defectueuse ( j'ai fait un assemblage de cable usb-microUsb + adaptateur microUsb/usp femelle qui m'a laché au bon de deux ans.)

Si je devais debugguer mon install: 
* Je testerai avec l'[appli windows](https://zigate.fr/documentation/tester-la-zigate-usb/) de faire ça soi meme pour valider que le pb n'est pas encore plus matériel et localisé dans la zigate.
* Puis je ferais les tests de la zigate, ie ceux de validation de la communication.
* lsusb => 'Bus 001 Device 009: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port' ( tu devrais avoir qq chose de simialire
* vérifier que la clé est bien visible: `ls /dev/ttyUSB*`
* enfin tester en ligne de commande l'accès a la zigate (il faut que je retrouve le bout de code qui fait ça.)


En passant les logs du plugin en debug tu devrais a minima avec ce type de logs quand la zigate discute avec le plugin:
```
AbeilleSerialRead1.log <==
[2021-01-18 21:58:21][debug] Reçu: "8102000F5FD4E838010405000000210002158D6C"
[2021-01-18 21:58:21][debug] Reçu: "8102000F3CD5E83801040300000029000203F76C"
[2021-01-18 21:58:21][debug] Reçu: "8102000E20D5E838010403001400280001FF6C"
[2021-01-18 21:58:21][debug] Reçu: "8102000F54D5E83801040300100029000227AB6C"
```

**Comment by Jake309** [comment]
Salut @edgd1er ! 

Merci pour la réponse. 
Tu ten a confirmer mon hypothèse de zigate défaillante. 

Elle est branche en direct sur le port usb, jen ai essayé sur 2, un direct carte mère, un autre sur une extension. Tous a 30cm dune clé bluetooth, je testerai de la déconnecte, mais quand jai testé sur mon windows sans ce genre de perturbateur, avec un équipement à 2cm de la zigate, ça n'allait pas non plus. 

D'ailleurs, le test que tu me propose est la 1ere choses que jai fait. Et je le connais parcoeur. ^^
Tout a fonctionné sauf le dernier point, quand je lance lappairage, rien n'apparait dans raw data. 

Je ferai ta proposition de debug demain et te ferai un retour. 
En parallèle jai aussi contacté le site zigate, jai acheté ma clé direct dessus, jattends leur retour. 
Dommage que ça coince des le début ^^

**Comment by edgd1er** [comment]
Salut @Jake309,

Un point que je n'ai pas indiqué: USB2, j'ai cru lire qq part que la zigate n'aime pas l'USB3, mais je ne saurais te rediriger vers la source ou j'ai lu ça et je ne pourrais te certifier si c'est encore le cas.

D'après ce que tu indiques, un défaut matériel semble être la cause de tes ennuis.

Tu maîtrises certainement beaucoup mieux que moi proxmox, ne prends pas mal les questions :
Jeedom tourne t il dans un vm ?
As tu donné l'accès au port usb dans la [vm](https://pve.proxmox.com/wiki/USB_Devices_in_Virtual_Machines) ?
Le port est il partagé entre plusieurs vm ?
Quel version de proxmox utilises tu ?
Quelle est la distribution de la machine hôte ?

Si c'est un problème matériel (port usb, usbttl, module zigbee), il y a peut etre des retraits/ajout de la clé zigate visible dans le syslog de la machine hôte. voici ce que cela pourrait donner:
```
Jan 15 20:37:50 localhost kernel: [178254.820112] usb 1-1.3: USB disconnect, device number 3
Jan 15 21:30:53 localhost kernel: [181437.945151] usb 1-1.3: new full-speed USB device number 9 using xhci_hcd
Jan 15 21:30:53 localhost kernel: [181438.079690] usb 1-1.3: New USB device found, idVendor=067b, idProduct=2303, bcdDevice= 3.00
Jan 15 21:30:53 localhost kernel: [181438.079709] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jan 15 21:30:53 localhost kernel: [181438.079726] usb 1-1.3: Product: USB-Serial Controller
Jan 15 21:30:53 localhost kernel: [181438.079742] usb 1-1.3: Manufacturer: Prolific Technology Inc.
Jan 15 21:30:53 localhost kernel: [181438.093675] usb 1-1.3: pl2303 converter now attached to ttyUSB0
```

**Comment by Jake309** [comment]
Salut @edgd1er 

Alors oui, j'avais lu aussi que l'USB3 était source de souci avec la zigate, pour ca que je la branche que sur des USB2. Rien n'apparait dans les release des version de firmware
Je joins l'image de config usb de proxmox, pour faire simple, tu as le choix d'attribuer le port usb, soit par marque de periph, soit pas port physique, j'ai testé plusieurs fois les deux, on s'entend bien la dessus ;). Et tu as une option pour l'USB3, bon j'en ai pas sur l'hote, mais je décoche quand meme.
Et je ne partage pas un matos avec plusieurs VM, je préfère éviter justement pour pas se rajouter d'épines dans le pied ^^

Je ne prends rien de mal, parfois meme, ca semble tellement "de base" que t'y pense pas ^^
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
Linux SRVproXmoX 5.4.78-2-pve

Et je mets les logs en plus qui sont bon =)
Désolé, beaucoup d'image, je passes par l'interface web pour proxmox avec sa console intégré qui est capricieuse avec les selection copier.
![conf usb](https://user-images.githubusercontent.com/49479084/105004255-fe3a5600-5a33-11eb-99a1-5a86f8c45dbf.JPG)
![log usb](https://user-images.githubusercontent.com/49479084/105004260-fed2ec80-5a33-11eb-8c30-4afe0ba0c315.JPG)

**Comment by Jorael57** [comment]
Je fais tourner Jeedom aussi sous proxmox mais dans un container et non une VM.
Mais je fais tourner Deconz et conbee2 dans une vm (je n'ai pas réussi dans un container)

As tu vérifié dans /var/log/message que la clé USB ne deco pas ? (j'ai eu le soucis avec la conbee 2 suite à un update de firmware raté la clé se deco.
Normalement via la vm tu n'as pas le soucis des droits dans le /dev/ttyUSBXX représentant la zigate. As tu vérifé que dans la VM tu voyais la clé via le lsusb ?

**Comment by Jake309** [comment]
Bonjour à tous !
Merci pour l'aide.
L'échange standard a permis de régler le souci =) Donc je n'avais pas de souci de configuration logiciel ou matériel, c'était bien la clé qui avait un défaut, elle est en cours de dissection. 
Je passe tranquillement tout mon zigbee sur abeille en modifiant mes scénarios. Et je commence déjà à voir la suite grâce au possibilité qu'offre le plugin et la zigate !
Je vous ai envoyé un geste sur le paypal de ben en guise de remerciement et pour contribuer, à ma manière, à vos efforts.
A bientôt =)

**Comment by KiwiHC16** [comment]
Merci Jake309 pour la cagnotte .

Je clos donc le cas. Bonne continuation avec ton système.
