### ISSUE TITLE
problème de remontée d'info sur ampoule ikea

### ISSUE THREAD

**Issue by blattes86** [KiwiHC16/Abeille#1634]
Bonjour à tous, j'ai sur mon réseau zigbee une ampoule TRADFRIbulbE27WSopal1000lm avec le contrôle de la luminosité et de température.
Je peux régler la température sans problème mais j'ai un souci sur la remontée de l'information. En effet la commande info temperatureLight reste vide:
![image](https://user-images.githubusercontent.com/5450173/105005824-1b702400-5a36-11eb-80c7-70dd30a2dd8d.png)

Est-ce un problème connu?
De quoi avez-vous besoin qu'y puisse vous aider a le résoudre?
Bon courage à tous et bonne journée

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Oui c est connu et pas implémenté.

Fait parti des truc à faire.

**Comment by blattes86** [comment]
Ok merci beaucoup @KiwiHC16 .
je clos l'issue ou je vous la laisse pour memo ?
S'il y a besoin de tester, je suis dispo. Niveau code je suis à la masse mais pour tester c'est bon.
Bon courage @tous

**Comment by KiwiHC16** [comment]
Laisses ouvert pour que cela soit fait un jour.

**Comment by tcharp38** [comment]
@blattes86 
Toujours partant pour se repencher sur ce pb ?

**Comment by tcharp38** [comment]
Trop vieux sujet sans reponse.
A réouvrir si qqn a des soucis en ligne avec ce sujet.
