### ISSUE TITLE
Hybride mode en 3.1B met le bazar. Doit on limiter en fonction du firmware. Mais est ce que cela fonctionne en 3.1D ? 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1635]
Inclusion en mode hybride ne semble pas fonctionner.

**Comment by KiwiHC16** [comment]
#1608

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Zigate 3 en 3.1B passée en hybride et tous les equipements passsent en timeout. Dans AbeilleParser j ai 
```
[2021-01-19 21:48:56][debug] Abeille3, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0104 cluster:0000 srcEndPoint:01 destEndPoint:01 sourceAddressMode:02 srcAddress:4924 destinationAddressMode:02 dstAddress:Ruche
```

En fait elle doit passer en mode raw d ou les soucis.

Il faut bloquer hybride et raw pour les utilisateurs.

**Comment by tcharp38** [comment]
En dehors de toi, qui utilise un mode autre que "normal" et pourquoi ?

**Comment by KiwiHC16** [comment]
Le mode hybride devra etre le mode par defaut avec et apres 3.1D.
Mode normal: zigate traite tous les messages quelle connait et rejete les autres (Avant 3.1D)
Mode hybride: idem Mode Normal mais les messages inconnus sont passé a Abeille (Doit etre mise en place an lancement d'Abeille a partir de 3.1d et suivantes)
Mode Raw: Zigate transparente elle passe tous les messages (pas pour Abeille).

-> il faut les cacher aux utilisateurs

**Comment by tcharp38** [comment]
ok, visible en mode dev only alors

**Comment by KiwiHC16** [comment]
Oui.
Je t assigne comme tu maitrises cette partie.

**Comment by KiwiHC16** [comment]
Trop fort !!!
Aussitôt dit aussitôt fait.

**Comment by KiwiHC16** [comment]
Reste a programmer le mode de la zigate de facon transparente pour l utilisateur.

L'ideal serait: demarrage d'Abeille, set mode en fonction du firmware.
Mais je voudrais tester plus 3.1D avant de forcer le mode Hybride.

Je passe tous mes systemes en 3.1D et je verrai. Ca va me prendre qq jours.

**Comment by tcharp38** [comment]
Tout est jouable.
Reste toujours à maitriser la 3.1d et ses caprices.
