### ISSUE TITLE
L'accès direct sur la page de configuration du plugin ne fonctionne pas.

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#1640]
Version: KiwiHC16/master du 20/01/2021

L'appel a la fonction js: xableDevMode(1) conduit a l'erreur: Call to a member function getLogicalid() on bool

il semblerait que l’accès direct au panneau de configuration du plugin Abeille ne soit pas possible:
https://localhost:9443/index.php?v=d&m=Abeille&p=Abeille&id=Abeille => erreur Call to a member

l'appel à la même page pour le plugin openzwave fonctionne:
https://localhost:9443/index.php?v=d&m=openzwave&p=openzwave&id=openzwave => ok

il s'agit donc d'un bug dans le plugin Abeille.

Il faut retrouver la fonction qui retourne un booléen au lieu de la structure attendue

la requetes post vers https://localhost:9443/core/ajax/event.ajax.php avec les données ci dessous ne retourne rien avant 10 secondes sur mon système. il doit y avoir un traitement assez couteux.

y a t il un moyen simple de connaitre le cheminement du code a partir d'index.php ?

**Comment by tcharp38** [comment]
Tu es passé en 4.1 je suppose alors

**Comment by tcharp38** [comment]
Je suppose que oui. Il y a beaucoup de pb avec la 4.1 que je decouvre au fur et a mesure.
A voir si #1641 solutionne ce point.

**Comment by KiwiHC16** [comment]
#1641 résoud le soucis.

**Comment by edgd1er** [comment]
@KiwiHC16 , @tcharp38 
oui, c'était bien la 4.1 et #1641 corrige bien le problème. Merci
