### ISSUE TITLE
Jeedom 4.1 et Sauvegarde sur un objet

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1649]
Bonjour,

j'ai un souci lors de modification sur un objet afficher historiser, j'enregistre et abeille me dit :

![image](https://user-images.githubusercontent.com/46579815/105204284-4d6fac00-5b44-11eb-8d60-75b1a326b1db.png)

et de ce fait aucune modification est faites
J utilise la branche Version Abeille :master_tcharp38, 2021-01-20 13:24:27

cdt

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
La master n est pas sensé etre utilisée car en modification permanente et que pour les dev.

Peux tu te mettre en stable et voir si tu as le meme soucis ?

**Comment by bouboun59** [comment]
EN stable du 18/01 c'est ok, sorry pour la gene.

**Comment by KiwiHC16** [comment]
Pas de soucis, c est juste qu il y encore 120 cas et le temps manque...
