### ISSUE TITLE
Bind et setReport pour les ampoule Ikea pour qu'elle remontent leur etat et level.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#165]

**Comment by KiwiHC16** [comment]
Implementé et fonctionne sur mon ampoule : TRADFRI bulb E27 CWS opal 600lm
Il est important que les adresses IEEE de l ampoule et de la ZiGate soient dispo pour que cela fonctionne.

**Comment by dams74** [comment]
Salut Ben
J'ai reçu la télécommande ;)
Voici le log d'appairage avec la base hue
J'espère que tu trouveras ton bonheur !

**Comment by KiwiHC16** [comment]
Je ne vois pas le log
