### ISSUE TITLE
telecommande stable EN stable du 18/01 problèmee

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1652]
Bonjour

la télécommande ne fonctionne plus depuis passage en stable 18/01

merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Peux tu nous décrire un peu plus le sujet ? Capture écran ? ce que tu fais ?

**Comment by bouboun59** [comment]
j'ai recréer toutes mes telecommandes pour resoudre le problème
