### ISSUE TITLE
Support prise Blitzwolf BW-SHP13 (id = TS0121, _TZ3000_g5xawfcq)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1655]
_Je suis dans la même situation, 15 minutes c’est trop long pour contrôler le chauffage et à travers un scénario la valeur ne se met pas à jour instantanément. Je me demande s’il existe des fichiers que nous pouvons manipuler manuellement lors de la mise en œuvre de cette amélioration. par contre, la valeur de consommation Wh reste toujours à 0._ 

https://community.jeedom.com/t/support-prise-blitzwolf-bw-shp13/35181/27

Pour l instant je poll toutes les minutes ?
Est ce que je peux bind/setReport ?
Verifier la bonne remontée de conso Wh

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by Jorael57** [comment]
Bonjour,

J'ai cette prise également , je viens de l'intégrer à nouveau j'ai bien la conso  et le voltage qui remonte mais par contre le on/off/toggle ne fonctionne pas ( que se soit depuis la tuile ou depuis les commandes de l'équipement

En commande name j'ai cela : TS0121__TZ3000_g5xawfcq

**Comment by KiwiHC16** [comment]
@Jorael57, peux tu essayer avec la derniere stable ?

**Comment by KiwiHC16** [comment]
Apres de multiple tentatives en tout genre impossible de faire un bind/report qui fonctionne. La prise dit ok mais rien ne remonte...
Je ne suis pas le seul a arriver a cette conclusion ;-(
https://easydomoticz.com/forum/viewtopic.php?f=28&t=10973

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-25 à 15 24 43](https://user-images.githubusercontent.com/8549674/105718375-74055c80-5f21-11eb-98d9-7b8ca0095f32.png)

![Capture d’écran 2021-01-25 à 15 25 13](https://user-images.githubusercontent.com/8549674/105718449-867f9600-5f21-11eb-9ebb-bdd03c36c17d.png)

![Capture d’écran 2021-01-25 à 15 25 50](https://user-images.githubusercontent.com/8549674/105718520-9c8d5680-5f21-11eb-87a5-a531db97baba.png)

Cron15

**Comment by KiwiHC16** [comment]
Comment rendre cette valeur accessible à l utilisateur ?

**Comment by Jorael57** [comment]
J'essaye dans l'aprem.
Si ça peux éventuellement t'aider j'ai acquis une Conbee2 qui est sensé supporté cette prise donc je peux faire des manip dessus pour t'aider si besoin.

J'ai vu que tu avais aussi une passerelle Tuya pour les tests, Tous les IoT tuya que tu as acheté fonctionne sans soucis avec ?

Parce que j'ai pris la conbee2 pour utiliser les tuya que j'ai et qui ne sont pas encore utilisable avec la zigate/abeille mais j'ai aussi pas mal de soucis avec au final... Genre des switch muraux identiques un et reconnu correctement l'autre non... alors que sur abeille il fonctionne.

**Comment by Jorael57** [comment]
@KiwiHC16 Bon après test cela semble fonctionner, il n'y a plus qu'à attendre pour voir la conso (car c'est ce qui m'interesse le plus dans cette prise :))

**Comment by Jorael57** [comment]
Après avoir appliqué une certaine puissance sur la prise  (700W) je vois que la valeur Current n'est pas bonne  elle n'a pas dépassé 0.90mA alors qu'elle aurait grimper à plus de 2A.

**Comment by KiwiHC16** [comment]
Je n'ai pas essayé la prise sur une GW Tuya car je lui parle en directe avec zigate. Mais je pourrai essayer pour voir le contenu de la discussion.

Le dernier modele dans le master de dev interroge les 3 valeurs: V, A, W toutes les minutes.

Je pensais avoir vérifié la valeur en A avec une ampoule de 50W mais je vais revérifier avec une charge plus importante.

**Comment by pipiche38** [comment]
> Apres de multiple tentatives en tout genre impossible de faire un bind/report qui fonctionne. La prise dit ok mais rien ne remonte...
> Je ne suis pas le seul a arriver a cette conclusion ;-(
> https://easydomoticz.com/forum/viewtopic.php?f=28&t=10973

seul le reporting de la puissance cummulée est automatique. Pour la puissance instantanée il faut faire un read Attribute.

@KiwiHC16 tu trouveras un sniff sur une gateway Tuay:
http://cloud.pipiche.net/index.php/s/BwydoNC8A7gsoxZ

**Comment by Jorael57** [comment]
> Le dernier modele dans le master de dev interroge les 3 valeurs: V, A, W toutes les minutes.

Est ce que ce type de paramètre peut être changer depuis Abeille ? Si c'est une valeur non modifiable par l'utilisateur de Jeedom Est ce que cela pourrait être le cas  (dev nécessaire ?) ?

En faisant mon test j'ai eu l'impression que les 3 valeurs n'étaient pas mise à jour  en même temps dans la tuile. Est ce normal ?

**Comment by KiwiHC16** [comment]
Ajout accès au cron. Pour choisir cron / cron5 / cron10 / cron15 / cron30 / ... dans la version de dev: https://github.com/KiwiHC16/Abeille/commit/940e3a8646571521afe1b9e47cbd81bb5140b415

**Comment by KiwiHC16** [comment]
L 'interrogation des trois valeurs va se faire en sequence, qq dixième de seconde de difference, et affichage se fait toutes les secondes ou plus alors il peut y avoir un décalage visible a l affichage mais doit être sous la seconde dans Jeedom.

**Comment by KiwiHC16** [comment]
@pipiche38, je viens de regarder ta trace en détails et aucune trace de bind/set report.

des write sur attribute 8001 et 8002 mais aucune idée de leurs fonctions.

Donc pour l instant poll....

**Comment by KiwiHC16** [comment]
@Jorael57, je vois que dans le trace il y a une demande pour les 3 ce qui fait 3 fois moins de messages. Je pourrai faire ca. Je vais implementer une commande specifique.

**Comment by KiwiHC16** [comment]
Je pense que le modele dans le master est complet. Sera dispo dans stable dans 2 semaines. Je clos.
