### ISSUE TITLE
Fonctions getgroup et addgroup

### ISSUE THREAD

**Issue by Hadrienalbouy** [KiwiHC16/Abeille#1657]
Bonsoir, 

J'essaye d'utiliser la fonction Add Group pour un interrupteur de lancement de scénarios Tradfri. C'est comme si l'action n'avait aucun effet. L'équipement n'apparait pas dans le tableau en face. (voir GIFj joint)
![2021-01-21_21h24_17](https://user-images.githubusercontent.com/77808770/105411726-0bbe2e80-5c34-11eb-8969-2d5b194dda45.gif)

J'ai tenté d'upgrader en 3.1D .
J'ai essayé la manip sur une télécommande virtuelle, même souci. 

Voici Abeille Keyinfo:
```
`1/ Version (AbeilleVersion.inc)
===============================
stable, 2021-01-18

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l","","**************************************","*           Welcome to Jeedom        *","**************************************","Username : jeedom","Password : ********",""]
["Linux jeedom 5.10.5-v8+ #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031C`


```
Merci pour votre aide.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Une petite video comme ça c est vraiment top. Je ne savais pas qu on pouvait ajouter cela dans github.
Comment fais tu ?

**Comment by Hadrienalbouy** [comment]
J'utilise l'appli screenpresso (gratuite et géniale), j'edite ensuite la vidéo en GIF avec Adobe premiere :)

**Comment by KiwiHC16** [comment]
Sinon pour ton cas je vois deux équipements le bouton et le capteur IR.
Dans les deux cas, ils se comportent comme des télécommandes. De ce fait, abeille ne les interrogent pas pour avoir leur groupe. Abeille ne sait pas faire. Je ne sais pas si c'est possible d'ailleurs. Il faudrait que je regarde un jour.

Ce qu'il faut probablement faire mais je n'ai pas testé avec ces deux équipements est utiliser la commande "set Group Remote".

mettre un Group dans le champ Id. Disons 0001 par exemple. Réveiller l'équipement (IR en passant devant, Bouton en appuyant dessus) et faire "set Group Remote". Abeille va envoyer le Group à l'équipement. Si cela se passe bien alors ils vont utiliser le Group. Donc si l'IR se déclenche il va envoyer sa commande au groupe en question. Si tu veux récupérer l info pour déclencher le scénario il faut ajouter la zigate au groupe avec les bouton "Add Group".

Si tu veux utiliser les boutons dans abeilles, il faut que tu renseignes dans le Group dans les param de l équipement.

Il faudrait que je fasse une doc avec les détails...

**Comment by KiwiHC16** [comment]
Regardes aussi: https://kiwihc16.github.io/AbeilleDoc/Ikea.html?highlight=telecommande#groupes
Ce n'est pas forcement super à jour mais ça doit aider.

**Comment by Hadrienalbouy** [comment]
Ok, merci pour ta réponse. Ce qui m'étonne, c'est que l'info ne remonte pas pour la télécommande virtuelle que j'ai créée également.

**Comment by KiwiHC16** [comment]
Qu'elle info ?

**Comment by Hadrienalbouy** [comment]
Dans le tableau, en face des fonctions de groupe, il n'apparait que la ruche.

**Comment by Hadrienalbouy** [comment]
J'ai regardé la vidéo avec Attention. 
Si je comprends bien, on se sert d'une ampoule pour savoir à quel groupe appartient le bouton physique, et on peu ensuite utiliser ce groupe pour lancer des scenarios en modifiant le param telecomande groupe et en ajoutant la ruche à ce groupe. 
J'ai modifié le param pour le bouton, et voici ce que j'obtiens.
![2021-01-21_22h50_00](https://user-images.githubusercontent.com/77808770/105416846-044e5380-5c3b-11eb-83bb-69b7eaf93a06.png)
Donc je suppose que je peux déclencher un scénario avec une de mes trois commandes, le bouton, le capteur IR et la télécommande virtuelle. 

Pour réaliser un test, je voudrais me servir de la commande virtuelle.. Elle se trouve bien dans le même groupe de ma Ruche. 
Je crée donc un nouveau scénario provoqué. Disons que le déclencheur serait : #[CHEZ NOUS][virtucom][Up-Down]#, 
Je crée le scenario suivant : 
![2021-01-21_23h39_42](https://user-images.githubusercontent.com/77808770/105421156-f2bc7a00-5c41-11eb-9c41-0457ffbf6cd7.png)

Je teste, mais ça ne fonctionne pas. Où est ce que je me plante ?

**Comment by KiwiHC16** [comment]
Tu te plantes dans le fait que la commande virtuelle envoie une commande groupe sur le réseau zigbee en utilisant la zigate. Comme c est la zigate qui l'envoie elle ne s'écoute pas parler donc elle ne reçoit pas le message.

Par contre si une commande phisique (IR / Inter) envoie un message au groupe, que tu as mis la zigate dans le groupe alors elle reçoit le message et tu peux utiliser le scenario.

**Comment by Hadrienalbouy** [comment]
Ahh  👍 . Donc ça veut dire qu'il va falloir que j’achète une ampoule pour savoir à quels groupe appartiennent mes inter physiques ! Et si je veux utiliser mon Infra rouge, il faut que je récupère le trigger [Click-Middle]# == 1 pour démarrer mon scénario, en supposant que tout le monde soit dans le même groupe, et que mon capteur IR soit télécommande de groupe ?

**Comment by Hadrienalbouy** [comment]
Après une bonne nuit de sommeil j'ai réussi à avancer avec le capteur IR. Voici Comment j'ai procédé : 
- Le capteur IR IKEA appartient par défaut au groupe 0000.
- Ajouter la ruche au groupe 0000 pour qu'elle puisse voir les actions du capteur. 
 -Définir le param télécommande groupe du capteur sur 0000.

![2021-01-22_10h06_28](https://user-images.githubusercontent.com/77808770/105470178-853c3800-5c99-11eb-9d3e-5b7c192c2e1d.png)


Quand le capteur détecte un mouvement, la valeur click middle renvoyée est 42 (la réponse à l'univers). La valeur remonte, correctement sur le panneau. Je peux donc créer un scénario avec ce paramètre. 

![2021-01-22_10h13_53](https://user-images.githubusercontent.com/77808770/105471029-989bd300-5c9a-11eb-85fe-642b66eada21.png)


Il faut maintenant que je trouve le moyen d'inclure le nouveau bouton Ikea qui n'existe pas encore dans abeille :
TRADFRISHORTCUTButton (https://www.ikea.com/fr/fr/p/tradfri-lanceur-de-scenario-connecte-blanc-40356381/)
![2021-01-22_10h11_50](https://user-images.githubusercontent.com/77808770/105470795-4955a280-5c9a-11eb-9435-a696f44f335b.png)

@KiwiHC16 si tu veux, je peux t'en envoyer un pour test.
