### ISSUE TITLE
get IEEE

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1660]
Verifier qu un get IEEE est bien fait lors de l inclusion.

**Comment by tcharp38** [comment]
Salut
Pourquoi faire ?
Le premier dev announce fourni tout. Pourquoi redemander derriere ?

**Comment by KiwiHC16** [comment]
Pas pour les equipements xiaomi qui ne font pas d annonce lors de l inclusion d apres mes souvenirs.
Toujours des cas particuliers ........

**Comment by tcharp38** [comment]
Ha bon ?! 
Il me semblait que le 004D etait le tout premier paquet, donc addr courte + IEEE.
A eclaircir

**Comment by KiwiHC16** [comment]
D apres le teest que je viens de faire il y a bien un annonce. Je ne sais pas pourquoi je pensais que non.

**Comment by KiwiHC16** [comment]
Y a bien un soucis quand on recupere un equipement sur la base de son nom et pas sur son inclusion qui provoque une annonce.

**Comment by KiwiHC16** [comment]
On récupère l IEEE maintenant.
Test: supprimer Xiaomi Door sensor, faire un appui court sur bouton qui envoie nom et FF01. Creation dans abeille et on a bien IEEE.
