### ISSUE TITLE
Heiman Siren : WarningDevice-EF-3.0

### ISSUE THREAD

**Issue by Fabtwo38** [KiwiHC16/Abeille#1662]
Bonjour,
J'arrive à inclure une sirene heiman avec le plugin Abeille mais il n'y a pas de commandes.
Je suis sous Jeedom v4 .
Le device info est WarningDevice-EF-3.0 

Merci pour votre aide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Dans la liste on a: WarningDevice mais pas WarningDevice-EF-3.0.

Pourrais tu mettre le plugin en débug, redémarrer le daemon, vider le log AbeilleParser, supprimer l objet pour cet equipement, faire une inclusion de l equipement, partager le log AbeilleParser.

**Comment by Fabtwo38** [comment]
Bonjour, 

J'ai fait toute la procédure que tu m'as décrite.
Je n'arrive plus a inclure la sirene . 
Voici les logs 
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5860055/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5860056/AbeilleParser.log)

Merci.


[Abeille.log](https://github.com/KiwiHC16/Abeille/files/5860059/Abeille.log)

**Comment by KiwiHC16** [comment]
Le fichier AbeilleParser ne contient que deux lignes. Il a du etre rafraichi apres que tu es fait la manip.
Peux refaire la meme manipulation et partager le log AbeilleParser ?

**Comment by Fabtwo38** [comment]
Voici le log 
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5868552/AbeilleParser.log)

La sirène apparaît en équipement dans abeille mais pas de commandes action 
Merci beaucoup.

**Comment by KiwiHC16** [comment]
on a un debut d'info:
```
[2021-01-25 18:51:40][debug]   ManufacturerName='HEIMAN', trimmed='HEIMAN', {"Abeille1\/4761":{"time":1611597100,"ManufacturerName":"HEIMAN"}}, [Modelisation]
```

Peux tu me dire ce que donne la commande nom quand tu fais tester dessus ?

**Comment by Fabtwo38** [comment]
Le nom est WarningDevice-EF-3.0

**Comment by KiwiHC16** [comment]
As tu une image de cette sirene ?

**Comment by KiwiHC16** [comment]
Peux tu mettre ce fichier:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/WarningDevice-EF-3.0

sur ton systeme dans le repertoire associé (du meme nom), puis supprimer l equipement sous Abeille, et refaire une inclusion.

**Comment by Fabtwo38** [comment]
L'image est la même que la sirène heiman warningdevices. Seul la référence change HS2WD-E
Je fais le test ce soir , merci .

**Comment by Fabtwo38** [comment]
La sirene est reconnue et fonctionne. Faut juste que je comprenne comment fonctionne les sliders . Elle hurle fort 
Merci.

**Comment by KiwiHC16** [comment]
Ok super. Rouvres si besoin.
