### ISSUE TITLE
Demarrage daemon: interroge tous les equipements pour avoir leur etat.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1663]

**Comment by tcharp38** [comment]
J'avais deja ca en tete et c'est facile à faire.
On est d'accord que ca ne concerne QUE les eq sur secteur. Les eq sur batterie ne repondent que lorsqu'ils se reveillent donc potentiellement.. rarement.

**Comment by KiwiHC16** [comment]
Oui mais.
Pour la partie secteur facile oui mais pas aussi simple. Quelles valeurs on interroge ? Si ampoule on va avoir les ampoules on/on, mais aussi celle qui regle la couleur du blanc, d autre la couleur,... Donc comment savoir ce que l on doit aller chercher pour chaque ...
Pour ceux qui dorme j'ai mis en place une queue qui prend les demandes et attent le reveil. Sur réveille envoie les commandes.

**Comment by tcharp38** [comment]
Effectivement. Je faisais allusion au cron15 par ex. Depuis un moment je me disais que ca devait etre executé aussi au demarrage.

Pour ceux qui dorment, tu as essayé ? T'es sur qu'ils restent "à l'ecoute" un moment ? Un exemple concret ?

**Comment by KiwiHC16** [comment]
Pour ceux qui dorment il y a plusieurs situations.
1) la plus simple: un capteur de temperature Xiaomi. Il remonte toutes les heures un message vers le contrôleur (zigate). Quand Abeille reçoit l info, alors on a quelques secondes pour envoyer nos demandes.
2) Le capteur ne remonte que de temps en temps (a sa discrétion), dans ce cas il faut le reveiller physiquement (appuie sur un bouton, faire changer la valeur comme temperature en le chauffant.
3) L'équipement ne fait que des requêtes L2: data request, la le sujet est plus compliqué.
4) ...

**Comment by KiwiHC16** [comment]
Ajout de l option RefreshData fait.
Voir doc ModeleJSON
