### ISSUE TITLE
Zigate ne parviens pas a sauvegarder....

### ISSUE THREAD

**Issue by jossalison38** [KiwiHC16/Abeille#1665]
bonjour 
je me trouve très embêter car je Vien de faire les mise a jour jeedom et abeille 
depuis cette mise a jour plus moyen de contrôlé mes volet, ni mes prise ikea .
Lors ce que je débranche les prises et les rebranches elle communique avec abeille , mais ca reste la seule chose quel font .
Pour mes volet pas de communication rien même pas lors de l'ouverture du réseaux rien ne bouge 
j'ai l'impression que la zigate ne peu pas émettre 
auriez vous une idée du problème 
avant la mise a jour tous marché bien 
(même en revenant sur une sauvegarde ca ne change rien )
merci

**Comment by KiwiHC16** [comment]
Salut
As tu redémarré Jeedom après mise a jour ? 
( c est une étape que j ai du faire )
Une fois fait et si toujours des soucis, mets le plugin en mode debug, redémarres les daemon et partages le log Abeille et AbeilleParser. 
Donnes aussi les version de ton OS, de Jeedom, d abeille et du firmware zigate.

**Comment by jossalison38** [comment]
bonsoir 
les périphérique on l'air de communiqué maintenant , j'ai laissé mon Install tournée le temp de bricolé 
mais par moment il faut que je demande plusieurs fois pour que la commande s'exécute .
je penserai que mon problème Vien de mon autre poste sur le "cas A  trop de message" 

A votre avis ?

je vous joins les fichier 
merci bien 

[AbeilleParser (2).log](https://github.com/KiwiHC16/Abeille/files/5862807/AbeilleParser.2.log)
[Abeille 5.txt](https://github.com/KiwiHC16/Abeille/files/5862810/Abeille.5.txt)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
16 toutes les minutes 
```
Envoyé '{"topic":"TempoCmdAbeille1\/6EAC\/ReadAttributeRequest&time=1611509402","payload":"EP=01&clusterId=0006&attributeId=0000"}' vers queue 123
```
Sur 0006 et 0008. Est ce normal toutes les minutes ? Il faut que je vérifie le code.

cron15: Interrogation des équipements sans nouvelles depuis plus de 15mins.
27 annonces:
```
[2021-01-24 18:30:03][DEBUG] : publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/A9B3\/Annonce&time=1611509403","payload":"01"}' vers queue 123
```

Peux tu partager une capture d écran de la page santé ?

**Comment by KiwiHC16** [comment]
AbeilleParser: Jamais vu un contenu de ce genre ...
```
[2021-01-24 18:19:45][debug] Abeille1, Type=8035/PDM event code, PDMEvtCode=x03, RecId=0000F102 => LARGEST_RECORD_FULL_SAVE_NO_LONGER_POSSIBLE
```

Quelle version de firmware zigate utilises tu ?

**Comment by jossalison38** [comment]
désole pour le délai de réponse 
la zigate est en 3.1c
voici la capture ecran
![image](https://user-images.githubusercontent.com/47280807/105748414-67453080-5f42-11eb-95b9-7adfac0bc429.png)
![image](https://user-images.githubusercontent.com/47280807/105748440-70ce9880-5f42-11eb-98d1-80cc3dacd303.png)

**Comment by tcharp38** [comment]
> AbeilleParser: Jamais vu un contenu de ce genre ...
> 
> ```
> [2021-01-24 18:19:45][debug] Abeille1, Type=8035/PDM event code, PDMEvtCode=x03, RecId=0000F102 => LARGEST_RECORD_FULL_SAVE_NO_LONGER_POSSIBLE
> ```
> 
> Quelle version de firmware zigate utilises tu ?

@KiwiHC16 J'en ai plein des comme ca en 3.1c, depuis des lustres.
Donc c'est pas forcement un pb.

**Comment by KiwiHC16** [comment]
Peux tu aussi partager la page "Graphique des liens" ?

**Comment by jossalison38** [comment]
salut a chaque appuie pou reinterroge le reseaux j'ai ce message 
![image](https://user-images.githubusercontent.com/47280807/105896068-a47af280-6016-11eb-9d83-bf8fdc3168ad.png)
voici le graphique il n'y a rien a part un detecteur lol
![image](https://user-images.githubusercontent.com/47280807/105895868-5e259380-6016-11eb-8a1e-65acb837040e.png)

**Comment by KiwiHC16** [comment]
https://github.com/KiwiHC16/Abeille/issues/1626 est corrigé.
Sur quelle version Abeille es tu ?

**Comment by jossalison38** [comment]
sur la 18-01-2021
![image](https://user-images.githubusercontent.com/47280807/105897172-21f33280-6018-11eb-9a17-4c5338ac3324.png)

**Comment by KiwiHC16** [comment]
Peux tu passer en 25/1/2021 ?

**Comment by jossalison38** [comment]
J ai fait la mise à jour avant  de partir au travail,  Je vous recontacte dans la soirée pour vous donnez des nouvelles  .

**Comment by jossalison38** [comment]
bonsoir je reviens vers vous après la mise a jour , ce soir  plus rien ne fonctionne tout est en time out sauf un détecteur de fumée.
lorsque je force une réintégration , il ce limite a ce détecteur  .
j'ai l'impression d'avoir le même problème que la personé avec ce sujet [https://github.com/KiwiHC16/Abeille/issues/1687](url)  , en plus d'avoir ce message 
![image](https://user-images.githubusercontent.com/47280807/106034224-f08b6d00-60d2-11eb-8267-3fa87539b7c4.png)
que ce passe t'il , tous marchez bien avant ?
de quoi avez vous besoin ?
merci d'avance help

**Comment by KiwiHC16** [comment]
Le plus rapide serait que je me connecte à ton système. Pour cela il faudrait partager ton écran avec anydesk.com ouvrir un Jeedom et avoir deux ssh ouverts. 

Es tu preneur ?

**Comment by jossalison38** [comment]
oui quand ? je regarde pour installé anydesk

**Comment by jossalison38** [comment]
j'ai installé anydesk et j'ai ouvert un 2 ssh et un jeedom 
quand tu veut

**Comment by KiwiHC16** [comment]
Maintenant si tu m envoies le numéro anydesk par email a kiwihc16 x free.fr

**Comment by jossalison38** [comment]
j'ai envoye email a tu recu ?

**Comment by KiwiHC16** [comment]
Ok j ai reçu. J installe anydesk sur ma machine.

**Comment by KiwiHC16** [comment]
Demande de connection en cours...

**Comment by KiwiHC16** [comment]
NE: 
- Xiaomi smoke
- prise Ikea
- ZigbeeOccupencySensor sans icône: 5cfdgh0asd6rt78620b6b
- Remote visuelle (parameter groupe invisible) -> @tcharp38
- volet profalux 5c07c7662688a

stable, 2021-01-25 12:29

une zigate USB 3.1C

Seul Ruche et un smoke ne sont pas en timeout.

Sur refresj LQI seul le smoke remonte.

AbeilleParser crache tout le temps:
```
[2021-01-27 22:29:42][debug] Abeille1, Type=8035/PDM event code, PDMEvtCode=x03, RecId=0000F101 => LARGEST_RECORD_FULL_SAVE_NO_LONGER_POSSIBLE
```

AbeilleCmd plein de commande tout le temps avec message pas de Ack.

IPCS clean

Smoke remonte ses infos:
```
[2021-01-27 22:43:11][debug] Abeille1, Type=8102/Attribut report, SQN=96, Addr=3901, EP=01, ClustId=0000, AttrId=FF01, AttrStatus=00, AttrDataType=42, AttrSize=0028
[2021-01-27 22:43:11][debug]   Champ proprietaire Xiaomi (Sensor Smoke)
[2021-01-27 22:43:11][debug]   Voltage=3065, Voltage%=79
```

**Comment by tcharp38** [comment]
@KiwiHC16 Quel est ce point "Remote visuelle (parameter groupe invisible) -> @tcharp38" ?

**Comment by KiwiHC16** [comment]
Je suis sur le système de la personne entrain d'investiguer. Le volet 2 pour une remote télécommande n apparait pas.

**Comment by KiwiHC16** [comment]
Proposé de faire:
- PDM erase et re-inclusion
- ou EEPROM Erase, Soft programmation et re-inclusion
A suivre ce week end.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-27 à 22 57 44](https://user-images.githubusercontent.com/8549674/106059509-17f23200-60f3-11eb-86f4-796bd8894a03.png)

Sur ce système le paragraphe Télécommande n'était pas visible. Je suppose que c 'est du fait de veille version.
@jossalison38, pourrais tu créer une Télécommande virtuelle et me dire si tu vois le paragraphe Télécommande dans cette nouvelle alors qu on ne le voit pas dans les anciennes.

**Comment by jossalison38** [comment]
voici la capture écran  d'une  télécommande virtuelle on ne voit pas le paragraphe télécommande  
![image](https://user-images.githubusercontent.com/47280807/106059985-c8603600-60f3-11eb-9194-18aabbb63348.png)

**Comment by jossalison38** [comment]
bonsoir 
je reviens vers vous car aujourd'hui, je devais remettre le firmware 3.1c sur la clé zigate et réinclure mais équipement . 
mais j'ai eu un problème avec mon clé zwave gen5 et en regardand un peu de partout ,
 je me suis aperçue que mes équipement communiqué de nouveau avec la clé zigate et que je n'avait quasiment plus de time out .
même par moment plus du tout de time out .

-je me pose la question si quelqu'un avait déjà eu des problèmes de conflit entre les 2 clés ?
-si cela était du a la position des clés , chez moi elle sont espacé de 30 cm ou bien du port usb du Raspberry pi 4  ?

je vais faire des test durant la semaine avant du tous réinstallé , dans un premier temp  espacé plus les clés usb , 
et je pense dans un deuxième temps essayé un hub usb alimenté 
si vous pourriez me donné vos avis ou bien vos mésaventure sur ce problème je vous en serait très reconnaissant 
bon weekend

**Comment by KiwiHC16** [comment]
@jossalison38 , les bandes de frequences Zigbee et Zwave ne sont pas communent donc ne doivent pas inter-agir. Mias bon il est toujours bon de mettre de l espace entre antennes pour eviter des inter-actions.
Le pi4 est connu pour poser des soucis. Il vaut mieux un Hub USB auto-alimenté et pour la zigate ne pas utiliser les port USB en bleu.

Je clos car tu dis ne plus avoir de soucis. Ouvres une nouvelle issue si d autres soucis.
