### ISSUE TITLE
Eq Ruche, params, affichage heure: pas à jour

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1667]

**Comment by KiwiHC16** [comment]
Demande de l heure par la prise blitzwolf:
![Capture d’écran 2021-01-25 à 10 12 10](https://user-images.githubusercontent.com/8549674/105684893-ccbf0000-5ef5-11eb-889d-f091141bbc75.png)

pas de reponse zigate.

![Capture d’écran 2021-01-25 à 10 13 35](https://user-images.githubusercontent.com/8549674/105685093-fe37cb80-5ef5-11eb-823d-9eeab9fdbd4f.png)
Modifier suivi de Lire ne met pas l heure a jour.

**Comment by KiwiHC16** [comment]
Sur lire dans AbeilleParser:
[2021-01-25 10:15:05][debug] Abeille1, Type=8017/Get Time server Response: Timestamp=1611566105
qui est la bonne heure donc semble être un soucis affichage dans Abeille

En fait il faut faire, lire suivi du refresh de la page pour voir la mise a jour.

**Comment by tcharp38** [comment]
Je m attendais à un souci restant à ce niveau. Colle le moi

**Comment by tcharp38** [comment]
@KiwiHC16 Est ce qu'on a besoin de mettre autre chose que l'heure du host ?
Autrement dit est ce vraiment necessaire que l'utilisateur puisse choisir l heure ?

**Comment by KiwiHC16** [comment]
L heure du host est parfaite. Pas de bseoin d'heure fournie par utilisateur.

**Comment by tcharp38** [comment]
Parfait. Ca me parait bien moins dangereux. Il aurait pu mettre une heure qui colle pas du tout.
Du coup ca devrait etre plus facile à remettre en place.

**Comment by tcharp38** [comment]
@KiwiHC16, juste pour info.
Je realise qu'il y a probablement un mic mac de ce cote.
Le format attendu par la zigate est un timestamp depuis **2000** (<timestamp UTC: uint32_t> from 2000-01-01 00:00:00), hors le code par defaut utilise le "time()" de PHP qui lui donne un timestamp depuis **1970** (1er janvier 1970 00:00:00 GMT).
Je ne vois aucune conversion faite au passage.

Je vais corriger le tir mais je ne vois pas quel impact ce bug pourrait avoir.
Si jamais tu as penses à qqch ..

**Comment by tcharp38** [comment]
Bon au final je crois que le bug de mauvaise ref timestamp n'a pas d'impact cote Abeille car meme defaut en entree et en sortie.
Mais entre eq qui pourraient avoir une autre ref, pb potentielle ?

Pb d'affichage pas fixé.
Un execCmd() n'attend pas d'avoir une réponse du reseau. Son comportement est a clarifier

**Comment by KiwiHC16** [comment]
La zigate est un serveur de temps. Certains equipements recuperent l heure. Je pense au tete de radiateur avec programmation du calendrier à la semaine. Il est mieux s'ils ont la bonne heure...
Probablement pas utilisé a ce jour ce pourquoi le probleme n a pas ete vu.

**Comment by tcharp38** [comment]
Ok, donc à verifier que la bonne heure est transmise de la zigate aux eq si ils la demandent.
Question: la zigate a sa ref de temps le 1-1-2000. Quelle est la ref "zigbee" ?

**Comment by KiwiHC16** [comment]
Aucune idée. Il faudrait sniffer pour voir mais il faut que je trouve un equipement qui demande l heure. Miais j'ai aussi une issue sur le sujet: (que je ne retrouve plus mais j ai vu que la zigate de repondait pas alors que part le passé cela fonctionnait)

**Comment by tcharp38** [comment]
#1916

**Comment by tcharp38** [comment]
Je clos. A reouvrir si besoin mais ca devrait etre bon
