### ISSUE TITLE
RPI3: AbeilleParser 2018-03-02 13:01:57[ERROR]CRC is not as expected (0f) is 0F

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#167]

**Comment by edgd1er** [comment]
le crctemp est un entier, je propose de le comparer à crc converti en entier. cette proposition sera dans ma prochaine PR. KiwiHC16/Abeille/pull/175

**Comment by KiwiHC16** [comment]
#175 Merged

Et je ne vois pas ce probleme sur mon RPI3 en prod avec beaucoup d'équipements.
Je clos le sujet.
