### ISSUE TITLE
Add Philips HUE Ensis

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#1670]
Bonjour à tous,

pourrait-on intégrer le Philips HUE Ensis aux prochaines updates?
![node_HueEnsis](https://user-images.githubusercontent.com/60474071/105747924-b2127880-5f41-11eb-9ec4-a0a17a47b010.png)

Le lustre est vu comme deux lampes identiques, une pour le dessus et une pour le dessous.
Ci-joint mes fichiers de configuration, aucun template supplémentaire n'est nécessaire.
[Hue Ensis.zip](https://github.com/KiwiHC16/Abeille/files/5868661/Hue.Ensis.zip)

Merci!

Kaléo.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Super, j ajoutes les modèles dans Abeille.

**Comment by KiwiHC16** [comment]
mis dans la master sera dans la prochaine stable dans une semaine probablement.
