### ISSUE TITLE
Phillips Hue LCT010 non reconnue

### ISSUE THREAD

**Issue by alexh-fr** [KiwiHC16/Abeille#1673]
Bonjour !

Mes ampoules Phillips Hue LCT010 (Hue White and Color Ambiance A19 E26 (Gen 3)) ne sont pas reconnues par le plugin.
Seules les commandes "par défaut" pour obtenir les informations sont présentes mais aucune action sur l'ampoule disponible

Cependant, possédant également des Phillips Hue LightStrip Plus (LST002), en ajoutant manuellement toutes les commandes pour les actions/infos du LST002, ces dernières fonctionnent parfaitement sur la LCT010.

Suis-je le seul dans ce cas ?
Est-il possible de rendre nativement compatibles les LCT010 ?

Merci.

Clé zigbee: ZIGATE officiel (FW 031D)
Version Jeedom: 4.1.18
Version Abeille: STABLE / 2021-01-25 09:09:39

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Les LCT010 ne sont pas dans la liste des ampoules connues par Abeille.
Je fais un modele sur la base des LST002 comme tu indiques que cela repond au besoin.

**Comment by KiwiHC16** [comment]
As tu une images de ces ampoules ?

**Comment by KiwiHC16** [comment]
Voila dans la version de dev, sera dans la prochaine beta (1 semaine) et la prochaine stable (2 semaines)

**Comment by alexh-fr** [comment]
J'ai testé quelques commandes qui m'intéresse.
Si tu souhaite, je peut tester de façon complète afin de t'assurer de la compatibilité de toutes les commandes actions/infos.

Voici un lien de l'image provenant du site Phillips:
https://www.assets.signify.com/is/image/PhilipsLighting/634127b6f5f047069795ac6700e57afd

**Comment by KiwiHC16** [comment]
Recuperes ce fichier pour tester:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/LCT010

**Comment by KiwiHC16** [comment]
Tiens moi au courant.

**Comment by alexh-fr** [comment]
Je te confirme que le .json (https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/LCT010) fonctionne correctement. 
Toutes les commandes actions/infos correspondent parfaitement a la LCT010.
L'ensemble des commandes apparaissent bien à l'intégration de la LCT010.

**Comment by alexh-fr** [comment]
Je t'ai adapté l'image pour l'ampoule si tu souhaite.
![node_LCT010](https://user-images.githubusercontent.com/78020272/105859021-52bd7280-5fec-11eb-9d4f-d334fff83a21.png)

![image](https://user-images.githubusercontent.com/78020272/105859092-6a94f680-5fec-11eb-9950-5a27126d150b.png)

**Comment by KiwiHC16** [comment]
Super. Je clos. Rouvres si nécessaire.
