### ISSUE TITLE
Envoyer les commandes sans ACK

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1674]
```
[2021-01-26 11:53:47][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=E403, DestEP=01, ClustId=0B04
```

**Comment by tcharp38** [comment]
J'en profite pour poser la question: comment sait on 
- que la commande attend un ACK ?
- que c'est une commande dont le resend est géré par la zigate/stack directement ?

Je cherche à comprendre quand Abeille doit gerer le retry lui meme.

**Comment by KiwiHC16** [comment]
On peut avoir des ACK a tous les niveaux. Celui dont je parle ici est au niveau Zigbee APS et est géré par la stack zigate.
C est un truc que je ne souhaite pas dans Abeille (toujours discutable).
Actuellement Abeille ne gère pas ces ACK. 
Pour l instant Abeille ne fait de resend que sur la notfication de la zigate sur la prise en compte ou pas de la commande. 
On peut discuter du sujet dans slack, cela sera plus simple qu'ici.

**Comment by pipiche38** [comment]
L'idée de faire de l'envoie de messages sans-Ack permet simplement de réduire le trafic et de paralléliser les choses quand c'est possible

**Comment by KiwiHC16** [comment]
Cmd 0100 request ACK APS.

**Comment by KiwiHC16** [comment]
Prendre les stats utilisation des commandes et le passer en raw une a une en commençant par les plus utilisées.

**Comment by KiwiHC16** [comment]
[2021-01-27 15:44:07][debug] incStatCmd():{"0024":4,"0016":4,"0009":4,"0002":4,"0100":140,"0530":850,"0010":36,"0092":1}

0002: setMode
0009: getNetworkStatus
0010: getVersion
0016: setTimeServer
0024: startNetwork
0092: onoff
0100: getParam / getParamHue / getParamOSRAM
0530: Raw

**Comment by KiwiHC16** [comment]
je garde le OnOffRaw dispo mais ne generalise pas vu le mauvais comportement de certain equipement.
