### ISSUE TITLE
Sur annonce faire un get ModelId/Manu dans une meme requête.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1675]

**Comment by KiwiHC16** [comment]
et en backup garder l envoie des ces meme requete en serie au cas ou le device ne reponde pas a la premiere demande.

**Comment by tcharp38** [comment]
La phase d inclusion ayant changé cette requete est obsolete.
La demande de manuf est faite au device announce, tout comme la "location".
