### ISSUE TITLE
Bouton sauvegarder : un équipement portant ce nom xxxx existe déjà pour cet objet

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1678]
Bonjour,

Je suis sur la version Master de Github. Je ne fais pas des modifs de mes devices tous les jours donc je ne découvre ce problème que ce jour; j'ignore depuis quand il est présent.
Voici l'erreur. Elle est encore présente ce soir après un dernier update avec les sources dispo  à 19h20.
![image](https://user-images.githubusercontent.com/16527222/105887944-a2139b00-600c-11eb-8c97-727ed1dceccb.png)
Cela s'affiche quand on édite un périphérique et qu'on clique sur le bouton sauvegarder.

**Comment by tcharp38** [comment]
Salut @JC38 
Je vais faire un essai. Tu as cliqué sur un equipement et à modifié qqch, comme son nom par ex. Puis sauvegarde. C'est ca ?

N'oublie pas que le master est la branche qui change le +, quasi tous les jours. Donc c'est n'est ni une beta et encore moins une stable. Mais tout bug est bon a connaitre.

**Comment by tcharp38** [comment]
Je ne reproduis pas. Donc il nous faut + de details.

**Comment by mickadam29** [comment]
@tcharp38 

1/ Version (AbeilleVersion.inc)
===============================
master_tcharp38, 2021-01-25 10:17:38

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

Je confirme le message d'erreur de JC38. Message que je viens de découvrir avant de le lire ce post.
Par exemple j'ai inclus un objet (diy mais peu importe visiblement). Si tu veux sauvegarder, sans rien modifier tu obtiens ce message. Je le déplace en changeant son "Parent". Là, la sauvegarde se passe bien. Mais si je le remets là où il était, le message m'indique l'erreur que l'objet existe déjà.

Mais la raison est ici, très probablement. Santé me fait apparaître l'objet que j'ai depuis supprimé. Avant il y avait 2 lignes comme celle-ci.
Si j'avais eu connaissance du messe de @JC38 , j'aurai fait des captures.
Et maintenant la question va être comment supprimer cet objet qui n'existe pas. 

Ouf, j'y suis parvenu en allant dans la vue Equipements de Jeedom. Equipements en alerte. En cliquant sur le nom, je suis revenu dans Abeille (normal)/Equipement/Paramètres. Le bouton "Supprimer" à fonctionner

![image](https://user-images.githubusercontent.com/36518012/105891688-33850c00-6011-11eb-8e68-5b49337b463e.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by mickadam29** [comment]
Finalement facile à reproduire. Je pense que chaque nouvel objet inclus pose souci.

![image](https://user-images.githubusercontent.com/36518012/105897908-15230e80-6019-11eb-811e-9505681ba04f.png)

**Comment by mickadam29** [comment]
Cela impacte tous les équipements, anciens comme nouveaux. Donc mise à jour 4.1.18 de Jeedom ou release Abeille d'hier ou aujourd'hui. Cela faisait qqs jours que je n'avais pas mis Abeille à jour mais il se peut que je n'ai pas utilisé la fonction "Sauvegarder" depuis qqs jours aussi

**Comment by tcharp38** [comment]
Ok ca doit encore etre lié à la 4.1. A la maison je suis encore en 4.0 et je peux pas changer tant que j'ai pas fait evoluer la Debian.
Je teste ca demain

**Comment by mickadam29** [comment]
Objet  créé dans Bureau. Aucune modif ne peut être sauvegardée
![image](https://user-images.githubusercontent.com/36518012/105899459-fd4c8a00-601a-11eb-81e5-5f18b07c8b8d.png)
Je déplace dans Aucun et passe de sécurité à Automatisme.
![image](https://user-images.githubusercontent.com/36518012/105899572-1fdea300-601b-11eb-83d0-f4fdf935aa54.png)
Aucun message d'erreur lors de l'appui sur "Sauvegarder". Donc je pensais que tout allait bien. Sauf qu'en revenant sur l'objet, aucune modif n'a été prise en compte (retour Bureau et Sécurité)
![image](https://user-images.githubusercontent.com/36518012/105899981-b6ab5f80-601b-11eb-9652-69c4c834efbd.png)
Et impossible de sauvegarder.

**Comment by mickadam29** [comment]
Merci @tcharp38

**Comment by mickadam29** [comment]
En complément. Lorsque tu veux aller sur Configuration Avancée de l'objet

![image](https://user-images.githubusercontent.com/36518012/105902003-5833b080-601e-11eb-8881-61a44a9023a9.png)

**Comment by tcharp38** [comment]
Ok. Désolé. 
Je fais de mon mieux demain pour reproduire et fixer ca.

**Comment by mickadam29** [comment]
Fais de ton mieux. Encore merci. En attendant c’est bloquant. Je ferai le test demain. Sauvegarde, restauration 4.1.17 et on verra si le bug est apparu en 4.1.18

**Comment by KiwiHC16** [comment]
Je viens de tomber sur le meme soucis.

Prod en erreur:
1) Système de Prod: Jeedom 4.1.17 / Abeille master_tcharp38, 2021-01-24 20:36:17 (doit être la stable du 25/01/2021).
Ouverture d un equipment, changement visibilité d'une commande.
Sauvegarde, erreur.

2) Sur mon système de prod mis a jour sur master: Abeille master et Jeedom 4.1.17, ouverture d un équipement et sauvegarde sans rien faire d autre et error.


Systeme de dev Ok:
1) J'ai fait ce genre de manip toute la journée sur mon système de dev sur Abeille master_tcharp38, 2021-01-25 10:17:38 et Jeedom 4.1.17 sans soucis.

2) Je viens de passer le dev sur master et pas de soucis.

Donc deux systèmes en master de ce soir et l un fonctionne et pas l autre....

Passage en 4.1.18 des deux ne change rien.
Pas de soucis identique sur un autre plugin, donc lié à Abeille.

**Comment by KiwiHC16** [comment]
Erreur venant de:
 core/ajax/eqLogic.ajax.php

Plante sur:
line 463: $eqLogic->save()

Et d après l erreur du fait du nom respect d'une clef dans la DB.

**Comment by KiwiHC16** [comment]
En mode dev activé, je n ai plus ce soucis sur mons système de Prod.

**Comment by tcharp38** [comment]
Je reproduis.
Je suis dessus.

**Comment by mickadam29** [comment]
@tcharp38 
Nickel et merci. Fonctionne à nouveau
