### ISSUE TITLE
Création d'objet et Indice

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1679]
@KiwiHC16 @tcharp38 

Lors de mes tests, j'ai des objets qui se créent automatiquement dans Abeille. Bien que la Zigate ne soit pas en inclusion.
Le souci, c'est que cela crée un objet à chaque fois et incrémente le numéro. Avec tous ces objets supprimés, je suis passé de Abeille-360 à 390.
Est-il possible, après avoir vérifié tous mes objets, de remettre ce compteur à une valeur plus proche du dernier objet créé valide ? Je suppose que vous avez inscrit ce nombre soit dans la BDD soit dans un fichier.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
@tcharp38  doit avoir la réponse car il est le dernier à avoir changé cette partie.

**Comment by mickadam29** [comment]
Merci. Va jeter un petit coup d'oeil sur slack, je t'ai laissé des news.

**Comment by tcharp38** [comment]
Tu fais allusion à l'ID d'un equipement. Ce truc est automatiquement attribué par Jeedom à la création de l'equipement. Je ne crois pas que nous ayons un quelconque controle dessus. C'est Jeedom qui s'assure que cet ID est unique.
A noter que c'est exactement la meme chose pour l'ID de chaque commande.

Mais en regardant dans l'API Jeedom je vois un setId(). Donc je reviens sur mes paroles. On doit pouvoir faire qqch mais ca me semble dangereux.

Donc tu souhaiterais que les ID des equipements soient un peu +... consecutifs. c'est ca ?

**Comment by mickadam29** [comment]
Oui @tcharp38 pour les ID
Pas pensé que ça dépendait de Jeedom puisqu’en fait, vous êtes passé de l’adresse courte à l’ID pour constituer le nom. Donc raccourci rapide. Ma crainte c’est la limite. Y a de la marge jusqu’à 999. Faut vraiment que j’investisse dans un environnement de re7

**Comment by tcharp38** [comment]
l'ID est un nombre. Je ne vois meme pas de limite à 3 chiffres, donc 999 n'a pas de raison dans être une.
Mais le fait que l'API propose un setId() m'intrigue car il faut absolument que l'ID soit unique. Il sert d indexe aux tables MySQL.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-27 à 00 53 07](https://user-images.githubusercontent.com/8549674/105922011-0b5dd300-603a-11eb-8738-c93cc9c784e6.png)

Int(11) on peut en créer des équipements....

Je clos.
