### ISSUE TITLE
Création d'objet et adresse courte

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1680]
@tcharp38  et @KiwiHC16 

1/ Version (AbeilleVersion.inc)
===============================
master_tcharp38, 2021-01-25 10:17:38

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

Est-il normal qu'un objet qui est créé puis récréé, se voit réattribuer la même adresse courte (IEE étant toujours la même)?
Je pensais que cette adresse était modifiée à chaque création.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
L'adresse courte est attribuée par la zigate lors de l inclusion et est temporaire.
Entre plusieurs inclusions, elle peut rester la même. Mais peut être changé. Elle peut aussi changer de temps à autre. Dans Abeille s'est normalement transparent pour l utilisateur.
Abeille ne fait que récupérer cette info.

**Comment by mickadam29** [comment]
Merci
