### ISSUE TITLE
Canal 26

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1683]
https://community.jeedom.com/t/plantage-de-linterface-web-jeedom-avec-derniere-version-beta-abeille/45902/6

**Comment by KiwiHC16** [comment]
En creusant un peu, je ne peux pas entrer le bon nombre de caractères pour le canal 26. Quand je mets le 0 devant 4000000 j’ai une erreur « Le masque doit être une valeur hexa ». En commentant dans le php le test !isHex(mask) c’est OK, je peux configurer le canal 26.

**Comment by KiwiHC16** [comment]
En creusant un peu, je ne peux pas entrer le bon nombre de caractères pour le canal 26. Quand je mets le 0 devant 4000000 j’ai une erreur « Le masque doit être une valeur hexa ». En commentant dans le php le test !isHex(mask) c’est OK, je peux configurer le canal 26.

**Comment by tcharp38** [comment]
Je vous laisse verifier que ce qu'il y a dans le master vous convient, et cloturer si c'est le cas.

**Comment by tcharp38** [comment]
Pour moi c'est fixé.
Je vous laisse réouvrir si besoin.

**Comment by ghost** [comment]
Bonjour,

Désolé de relancer cette vieille issue, mais je viens d'acquérir une pizigate en v2 et je n'arrive pas à changer le canal de la zigate (je n'arrive plus à intégrer des ampoules et prises Osram Ledvance qui fonctionnaient parfaitement avec ma pizigate v1).
Je cherche à forcer le canal 11 en remplissant le champ dédié dans l'onglet avancé de la zigate avec la valeur 00000800, mais je retrouve le message d'erreur "ERREUR: ERROR: Invalid payload. Not hexa ! (setChannelMask)".
Je ne trouve pas dans quel fichier commenter le !isHex(mask) pour tester. 

Merci pour votre aide. 

J'ai oublié de préciser : 
Jeedom 4.2.11
Abeille beta 2022-02-12 01:00:12

Edit : j'ai trouvé où commenter le !isHex(mask) dans AbeilleEq-Js.php, mais toujours impossible de changer le canal.

**Comment by tcharp38** [comment]
Salut @FQsqQ 
Je regarde ca et reviens vers toi

**Comment by tcharp38** [comment]
@FQsqQ 
Peux tu tester la 220215-BETA-1 ?
Voir si besoin: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by ghost** [comment]
Merci ! C'est parfait. J'ai n'ai pas eu de message d'erreur et après redémarrage la zigate est bien passée sur le canal 11.
Bon je n'ai toujours pas réussi à réinclure mes devices Osram mais ça c'est une autre histoire...

**Comment by tcharp38** [comment]
Super. Je clos alors.
Pour ton autre souci, regarde si le sujet existe, et reouvre ou cree en un précis.
