### ISSUE TITLE
Plus rien ne fonctionne

### ISSUE THREAD

**Issue by Dronarg** [KiwiHC16/Abeille#1687]
Bonjour,

J'utilise abeille avec une zigate. Tout fonctionnait assez moyennement avec des équipements qui avaient du mal à se connecter. 
J'ai des prises ikea qui font routeur zigbee et des capteurs xiaomi mais le routage zigbee ne fonctionnait pas sauf sur un capteur.
j'ai passé la zigate au dernier firmware 3.1d et la miracle j'ai eu d'un coup un fonctionnement parfait pour tous les équipements avec routage pour les plus éloignés.
Cela a duré quelques temps mais, et sans rien modifier, depuis une dizaine de jours tous les capteurs sauf un sont en time out. 
Si j'essaye de les réinclure, il ne se passe rien. 

J'avoue ne pas bien comprendre. Merci pour votre aide.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Quelle version Jeedom ?
Quelle version Abeille ?

**Comment by Dronarg** [comment]
Jeedom est en version 4.1.18 et Abeille c'est 2021.01.25

**Comment by KiwiHC16** [comment]
Peux tu partager une capture d ecran de la page santé ?

**Comment by Dronarg** [comment]
Oui bien sur, voila : 

![abeillesante](https://user-images.githubusercontent.com/19281383/106018994-6dfab180-60c2-11eb-9107-03aaeb4b61c2.jpg)

**Comment by KiwiHC16** [comment]
Peux tu partager aussi: Table des liens ?

**Comment by Dronarg** [comment]
Oui la voici. En fait il n'y a plus rien dedans

![abeille liens](https://user-images.githubusercontent.com/19281383/106030215-3c87e300-60ce-11eb-8678-288e91db1eb6.jpg)

**Comment by KiwiHC16** [comment]
Est ce que cela se met à jour si tu utilises le bouton orange de refresh ?

**Comment by Dronarg** [comment]
Oui mais ca donne juste cela.
En fait il ne reste plus qu'un seul équipement qui arrive à communiquer, le capteur de présence.

**Comment by KiwiHC16** [comment]
Peux tu mettre en debug, restart daemon et partager le log AbeilleParser ?

**Comment by benoitfl** [comment]
Bonsoir, idem ici tous crash plus de comm avec aucun équipement, plus d'inclusion
FW 031D
Dernière beta
Jeedom 4.1.17

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5883241/AbeilleParser.log)

Update, j'en ai qui reviennent mais pas d'explication sur pourquoi.

Voir #1696

**Comment by KiwiHC16** [comment]
@benoitfl ouvres une issue spécifique pour ton cas et fais référence a celle ci SVP (sinon je ne parviens pas a suivre). Merci.

**Comment by Dronarg** [comment]
Merci,
Alors voila le abeilleparser.log qui a l'air bien ;-)

[2021-01-28 09:47:39][info ] (Re)Démarrage d'AbeilleParser
[2021-01-28 09:47:40][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0024
[2021-01-28 09:47:40][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0016

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5885897/AbeilleParser.log)

Le abeille.log a l'air plus bavard

[2021-01-28 09:51:02][DEBUG] : AbeilleTools:clearSystemMessage:570 clearing zigate 1
[2021-01-28 09:51:02][DEBUG] : AbeilleTools:sendMessageToRuche:553 sending  to zigate 1
[2021-01-28 09:51:02][DEBUG] : publishMosquitto(): Envoyé '{"topic":"Abeille1\/Ruche\/SystemMessage","payload":""}' vers queue 121
[2021-01-28 09:51:02][DEBUG] : AbeilleTools::isMissingDaemons:446: False,   found: {"cmd":1,"parser":1,"serialRead1":1}
[2021-01-28 09:51:02][DEBUG] : AbeilleTools::isMissingDaemons:446: False,   found: {"cmd":1,"parser":1,"serialRead1":1}
[2021-01-28 09:51:02][DEBUG] : AbeilleTools:clearSystemMessage:570 clearing zigate 1
[2021-01-28 09:51:02][DEBUG] : AbeilleTools:sendMessageToRuche:553 sending  to zigate 1
[2021-01-28 09:51:02][DEBUG] : publishMosquitto(): Envoyé '{"topic":"Abeille1\/Ruche\/SystemMessage","payload":""}' vers queue 121
[2021-01-28 09:51:02][DEBUG] : fct message Topic: ->Abeille1/Ruche/SystemMessage<- Value -><-
[2021-01-28 09:51:02][DEBUG] : message(topic='Abeille1/Ruche/SystemMessage', payload='')
[2021-01-28 09:51:02][DEBUG] :   L'objet 'Abeille1/Ruche' existe mais pas la cmde 'SystemMessage' => message ignoré
[2021-01-28 09:51:02][DEBUG] : fct message Topic: ->Abeille1/Ruche/SystemMessage<- Value -><-
[2021-01-28 09:51:02][DEBUG] : message(topic='Abeille1/Ruche/SystemMessage', payload='')
[2021-01-28 09:51:02][DEBUG] :   L'objet 'Abeille1/Ruche' existe mais pas la cmde 'SystemMessage' => message ignoré
[2021-01-28 09:51:23][DEBUG] : fct message Topic: ->Abeille1/Ruche/SW-Application<- Value ->0003<-
[2021-01-28 09:51:23][DEBUG] : message(topic='Abeille1/Ruche/SW-Application', payload='0003')
[2021-01-28 09:51:23][DEBUG] : fct message Topic: ->Abeille1/Ruche/SW-SDK<- Value ->031D<-
[2021-01-28 09:51:23][DEBUG] : message(topic='Abeille1/Ruche/SW-SDK', payload='031D')


[Abeille.log](https://github.com/KiwiHC16/Abeille/files/5885899/Abeille.log)

**Comment by KiwiHC16** [comment]
Les deux log ne montrent pas d erreur.

Peux tu faire la meme chose en pilotant un ampoule ou prise en faisant 2 trois On suivi de Off et partager les logs : AbeilleParser, AbeilleCmd et Abeille.

**Comment by benoitfl** [comment]
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5888149/AbeilleCmd.log)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/5888150/AbeilleParser.1.log)

[AbeilleCmd.txt](https://github.com/KiwiHC16/Abeille/files/5888151/AbeilleCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5888152/Abeille.txt)

**Comment by KiwiHC16** [comment]
AbeilleCmd: beaucoup de
```
Je n'ai pas de Ack (Status) depuis 1 secondes
```
ce n est pas normal.

AbeilleParser: beaucoup de
```
Abeille1, Type=8011/APS data ACK, Status=A7, DestAddr=1F18
Abeille1, Type=8702/APS Data Confirm Fail,
Abeille1, Type=8000/Status, Status=15/Status 15
```
ce n est pas normal.

**Comment by KiwiHC16** [comment]
Je ne vois pas.
Si tu veux je peux me regarder ton systeme directement. Pour cela il faudrait que tu partages ton ecran avec anydesk.com. Que tu ouvres un jeedom et deux ssh ?
Dis moi si tu es intéressé ?

**Comment by benoitfl** [comment]
Oui, sans problèmes, cependant je ne peux plis aujourd'hui

**Comment by KiwiHC16** [comment]
Demain soir 21h ou Lundi soir 21h ?

**Comment by benoitfl** [comment]
Punaise j'avais pas vu que c'était pas mon issue  désolé

**Comment by benoitfl** [comment]
De suite j'ai une dispo 15 minutes autrement

**Comment by Dronarg** [comment]
Merci Kiwi

Ce matin j'ai refait des tests en mode débug. J'ai essayé d'associer à nouveau deux capteurs de température, une prise et une lampe.
Un des deux capteurs a été reconnu à nouveau et la lampe également.
J'ai également joué sur les commandes on off de la prise et de la lampe.
Voici les logs 

[Abeille2.log](https://github.com/KiwiHC16/Abeille/files/5892617/Abeille2.log)

[AbeilleParser2.log](https://github.com/KiwiHC16/Abeille/files/5892619/AbeilleParser2.log)

**Comment by Dronarg** [comment]
J'ai finalement pu associer à nouveau tout le monde ce matin et cela marche à nouveau.
Je ne sais pas pourquoi tout s'était mis en rade. Mystère ... mais au moins c'est ok

**Comment by mickadam29** [comment]
@KiwiHC16 

Problème similaire hier. On dirait que ce n'est pas isolé. Tout d'un coup j'ai perdu la communication avec de nombreux équipements. Et comme pour @Dronarg, certains sont revenus très rapidement. D'autres ont nécessité de les réinclure. La cause est très certainement la perte d'un, voire, plusieurs routeurs. Car en débranchant et en rebranchant mes ampoules (ikea donc routeurs) j'ai fini par récupérer une dizaine d'équipements d'un coup. J'imagine que c'est un routeur sur lequel  s'appuyaient ces équipements. Et le problème, c'est que cela s'est produit sans que je sois en train de bidouiller le système. 
@Dronarg, il y a des chances que le routage se soit remis d'équerre entre temps. 

1/ Version (AbeilleVersion.inc)
===============================
dev_tcharp38, 2021-01-29 12:51:55

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by KiwiHC16** [comment]
@mickadam29, le routage n'est pas sous le controle d'Abeille. Le routage est géré par les equipements eux meme. Si des equipements disparaissent/apparaissent (coupure de courant, allume avec inter d un ampoule,...) alors le reseau (les equipements) ont besoin de temps pour re-etablir le reseau. Dans ce cas Abeille peut ne pas les voir pendant un certain temps. La c est a vous d'avoir un reseau propre (sans courpure de jus, sans personne qui eteint electriquement les ampoules,...)

**Comment by KiwiHC16** [comment]
@Dronarg, si ok je clos. Ouvres une nouvelle issue si probleme.
