### ISSUE TITLE
Abeille class: utiliser this->import 

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#169]
Lors de la création, cela permet de ne pas devoir affecter chaque propriété / commande.
cela oblige a revoir tout les json pour qu'il soit conforme a ce que jeedom attend. pas de doc trouvée sur la structure et champs donc piochage a voir dans les plugins existants.

c'est de l'enhancement.

**Comment by KiwiHC16** [comment]
Je ne connais pas. 
Ou as tu trouvé ça ?
Quels sont les intérêts ?

On a des paramètres avec des conditions comme isVisible, est ce que ça prend ça en compte ?

**Comment by edgd1er** [comment]
l'intérêt est que ça fait tout tout seul. ça remplit les champs de l'objet automatiquement avec les parametres du json.

Dans un plugin (il va falloir que je trouve lequel), ça permet d'éviter tt les set des commandes mais il faut être sur des json. il y a un gros travail de découverte du format et normalisation des json.

Dans le plugin que j'ai vu, ça gère aussi les updates d'objets. en fait ça fait la mm chose sans setter le nom.

Pour le moment, je suis en découverte du fonctionnement.

**Comment by KiwiHC16** [comment]
As tu avancé sur ce sujet ?
As tu le temps ?
Est ce que cela vaut vraiment le coup ?

(Perso je propose de clore le sujet, car il y en a deja tellement sur la table).
