### ISSUE TITLE
Version master du 27/01 : plus de commande Off 

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1692]
Bonsoir,

J'ai mis à jour la version master du Github pour régler le problème apparu hier sur les sauvegardes mais là ce soir, je ne peux plus éteindre mes lumières pilotées par Abeille. 
ça va être une nuit claire :-(

1/ Version (AbeilleVersion.inc)
===============================
master_tcharp38, 2021-01-27 15:50:59

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by KiwiHC16** [comment]
C est une super fonction d'Abeille que je ne connaissais pas ;-)

**Comment by KiwiHC16** [comment]
J ai fait des modifs sur le sujet et j ai l impression que tu n es pas sur le dernier commit. Peux tu essayer avec la dernière dernière version ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by JC38** [comment]
J'ai forcé la mise à jour du plugin mais ça n'a rien changé.
![image](https://user-images.githubusercontent.com/16527222/106107332-181c1d00-6147-11eb-971d-c906c2524859.png)
Pour info, seules les lampes semblent impactées, les on/off des prises Zigbee sont ok.
Les lampes sont des Hue et des Gled Opto
Si le fichier qui porte les modifs du On/off est le AbeilleCmdPrepare.class.php, il me semble bien que j'aie le dernier
![image](https://user-images.githubusercontent.com/16527222/106108207-3afb0100-6148-11eb-828c-5e26ab584f91.png)

**Comment by KiwiHC16** [comment]
Le probleme vient de mes derniers tests. Je vais l enlevé car meme si c est en ligne avec la norme certains equipements ne fonctionnent visiblement pas correctement. Il y a la norme et la pratique.

**Comment by KiwiHC16** [comment]
C est dans le master.
