### ISSUE TITLE
Help Inclusion Illum Xiaomi = crash Abeille.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1693]
Suite de #1621

Stable du 25-01-2021
Une zigate USB en 3.1c

Collect LQI fonctionne bien

Tous rapportent à la zigate.

Xiaomi tous ok:

- portes
- inondation
- temperature
- bouton 
- IR

Lors de l inclusion
```
Erreur sur Abeille::deamon() : Error Object ( [message:protected] => Call to a member function execCmd() on bool [string:Error:private] => [code:protected] => 0 [file:protected] => /var/www/html/plugins/Abeille/core/class/Abeille.class.php [line:protected] => 1241 [trace:Error:private] => Array ( [0] => Array ( [file] => /var/www/html/plugins/Abeille/core/class/Abeille.class.php [line] => 886 [function] => message [class] => Abeille [type] => :: [args] => Array ( [0] => MsgAbeille Object ( [topic] => Abeille1/Ruche/disable [payload] => 04CF8CDF3C7F2096 [priority] => [message] => ) ) ) [1] => Array ( [file] => /var/www/html/core/php/jeeCron.php [line] => 87 [function] => deamon [class] => Abeille [type] => :: [args] => Array ( ) ) ) [previous:Error:private] => )
```

Zigate n a pas son adresse IEEE dans la page santé. Je n'ai pas vérifié dans la based de donnée.

Supprime ruche, restart daemon, inclusion nickel (Ruche a son adresse IEEE).

Peut être un lien entre l ancienne gestion dans un commande IEEE et le fait que l info est en paramètres maintenant.

**Comment by KiwiHC16** [comment]
1) Trouver la raison du crash si IEEE ruche pas présent et éviter le crash.
2) Informer l utilisateur que quelque chose ne va pas car la ruche n a pas son IEEE.

**Comment by tcharp38** [comment]
Je clos ce souci qui semble avoir disparu depuis qq temps.
A reouvrir si besoin
