### ISSUE TITLE
Group list vide

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1695]
![Capture d’écran 2021-01-27 à 23 47 55](https://user-images.githubusercontent.com/8549674/106064466-33ad0680-60fa-11eb-8260-3ccb4e3eb0f4.png)

Sur master

**Comment by KiwiHC16** [comment]
#967

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-27 à 23 50 25](https://user-images.githubusercontent.com/8549674/106064630-7242c100-60fa-11eb-875d-c5fa9f167e6b.png)

![Capture d’écran 2021-01-27 à 23 50 46](https://user-images.githubusercontent.com/8549674/106064675-7f5fb000-60fa-11eb-8754-f0373f13c6a9.png)

Groupes list vide pour les vrais équipements et pour la télécommande virtuelle.

**Comment by tcharp38** [comment]
Je regarde demain si qqch m'inspire ou je reviens vite fait en arriere.
