### ISSUE TITLE
Clic sur Equipement.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1697]
Si on clic sur un equipement Abeille on arrive sur la page avec tous les equipements et pas sur celui sélectionné:

![Capture d’écran 2021-01-28 à 11 10 32](https://user-images.githubusercontent.com/8549674/106122831-72be7480-6159-11eb-9fb0-7c73059abbd0.png)

Clic sur le titre ZIgLight et on arrive sur:
![Capture d’écran 2021-01-28 à 11 11 06](https://user-images.githubusercontent.com/8549674/106122891-8669db00-6159-11eb-8a1e-4b44248c7119.png)

et pas sur
![Capture d’écran 2021-01-28 à 11 11 24](https://user-images.githubusercontent.com/8549674/106122914-91247000-6159-11eb-8d2b-457f82c7b3e7.png)

master du 28/01/2021.

**Comment by tcharp38** [comment]
Je ne reproduis pas :(
pourtant bien sur le master du jour.
Clic à partir de la page gestion ou à partir d'un autre endroit ?

**Comment by tcharp38** [comment]
Ok, pb reproduis quand on clique du dashboard.
