### ISSUE TITLE
Xiaomi Simple switch Attr: ff01 comment decoder ?

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#170]
Comment decoder cet appui long sur le bouton ?

AbeilleParser 2018-03-03 17:41:33[DEBUG]-------------- 2018-03-03 17:41:33: protocolData size(90) message > 12 char
AbeilleParser 2018-03-03 17:41:33[DEBUG]Type: 8102 quality: bd
AbeilleParser 2018-03-03 17:41:33[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-03 17:41:33[DEBUG][2018-03-03 17:41:33]
AbeilleParser 2018-03-03 17:41:33[DEBUG]SQN: 01
AbeilleParser 2018-03-03 17:41:33[DEBUG]Src Addr : b1cc
AbeilleParser 2018-03-03 17:41:33[DEBUG]End Point : 01
AbeilleParser 2018-03-03 17:41:33[DEBUG]Cluster ID : 0000
AbeilleParser 2018-03-03 17:41:33[DEBUG]Attr ID : ff01
AbeilleParser 2018-03-03 17:41:33[DEBUG]Attr Status : 00
AbeilleParser 2018-03-03 17:41:33[DEBUG]Attr Data Type : 42
AbeilleParser 2018-03-03 17:41:33[DEBUG]Attr Size : 001b
AbeilleParser 2018-03-03 17:41:33[DEBUG]Data byte list : 0121db0B0328170421a8010521c000062401000000000A2100002b
AbeilleParser 2018-03-03 17:41:33[DEBUG]Data byte: !�
                                                      (!�!�$
!+
AbeilleParser 2018-03-03 17:41:33[DEBUG]mqttPublish with Qos: 0

**Comment by KiwiHC16** [comment]
Est ce un equipement sur batterie/pile ?

**Comment by edgd1er** [comment]
oui c'est celui la: lumi.sensor_86sw1, sur batterie.

**Comment by KiwiHC16** [comment]
Il faut faire du reverse engineering. Pour l instant je viens d'ajouter un bout de code qui doit faire remonter les valeurs de la batterie.
