### ISSUE TITLE
Afficher les groupes et les scenes dans:

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1713]
![Capture d’écran 2021-01-29 à 14 33 17](https://user-images.githubusercontent.com/8549674/106281022-f00fe500-623e-11eb-9972-b37f26c4b4eb.png)

**Comment by tcharp38** [comment]
![image](https://user-images.githubusercontent.com/35221038/168298623-aa4c6eb3-293d-478f-8a63-e3adfb4969f3.png)

Sera dispo dans la prochaine beta.
En revanche, rien n'est fait pour les scenes.
