### ISSUE TITLE
Contacteur 20AX LEGRAND et remontée de puissance absente

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1716]
@KiwiHC16 

Le contacteur 20AX ne reporte plus la puissance consommée depuis le 28/01. La commande ON/OFF fonctionne
Je ne sais pas avec quelle release ça s'est produit.
Tu avais corrigé ça il y a qqs temps.
Régression possible ou isolé à chez moi ?

**Comment by mickadam29** [comment]
Il a fallu que je crée l'issue pour que cela se remette à fonctionner.
J'ai tenté juste avant plusieurs fois ces commandes
-BindToZigatePuissance
-setReportPuissanceLegrand
-BindToZigateEtatLegrand

Je fermerai si le fonctionnement se confirme

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Je viens de le debranché mais il fonctionnait tres bien sur la version de dev. A suivre.

**Comment by mickadam29** [comment]
@KiwiHC16 

Est-ce nécessaire de lancer une fois une fois les commandes après une inclusion ? 

-BindToZigatePuissance
-setReportPuissanceLegrand
-BindToZigateEtatLegrand

Si oui, alors on peut fermer le sujet. Ne peut-on pas ajouter l'exécution automatique de ces commandes à la création de l'objet ?
Mes infos remontent correctement. Il faudra que je m'en souvienne

**Comment by KiwiHC16** [comment]
Normalement c est fait durant l inclusion mais cela ne se passe pas toujours bien.
Je suis sur l'idée d offrir un bouton pour l utilisateur pour forcer la configuration si besoin.

Dans la liste des trucs à faire.

Je clos. Merci por ton retour.

**Comment by mickadam29** [comment]
Merci. Sinon un Cron. Et valable pour tous les équipements qui devraient nous faire un retour. Très souvent, Jeedom me dit que j'ai une ampoule allumée. Et pourtant elle est éteinte. Il suffit de cliquer sur Off et l'état se met à jour.
