### ISSUE TITLE
Tout les devices en Time out après quelques heures

### ISSUE THREAD

**Issue by komega13** [KiwiHC16/Abeille#1718]
Bonjour

Tout mes devices passent en time out au bout de quelques heures depuis que je suis sur abeille, je n'avait ce soucis que sur les capteurs Aqara quand j'était sur le plugin zigate .

_Doublon avec mon post sur community Jeedom :_ [https://community.jeedom.com/t/statut-ok-mais-pas-de-donnee-aqara-abeille/51299/8](url) _avec de nombreuses captures d'écran ._

**Mon setup :**
-RPI3b+ avec Debian 10 et Jeedom V4
-SSD MSATA
-Dongle Zigate version 3.1d
-Un hub USB auto-alimenté pour ne pas tirer trop sur l'alim du pi
-4 capteurs de température Aqara 
-13 capteurs d’ouverture Xiaomi 
-2 prises IKEA Tradfri qui font routeur
-Box internet Freebox Crystal (WiFi canal 3 qui semble être le moins saccadé)

**Si je relance le demon Abeille tout les capteurs repassent au vert en quelques minutes .**

Ducoup pour mettre un pensement sur ma jambe cassé j'ai mis une valeur sur le heartbeat + coché la case "relancer le demon" mais ça ne semble pas fonctionner . J'ai décoché la case et effacé la valeur hearbeat . 
Finalement je viens de crée un scenario qui relance le demon toute les 60 minutes . C'est pas très propre mais en attendant ca devrait peut être aider .

Merci par avance pour votre aide

**Comment by mistyque** [comment]
Cas similaire:
Systeme: @mistyque TimeOut / Process crash #1722

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Comme indiqué dans le forum, clarifier dans un premier temps les soucis de module TTL-USB.

**Comment by komega13** [comment]
Salut @kiwihc16

Je viens de recevoir le nouveau module USB TTL pour ma Zigate .

Egalement une nouvelle alimentation pour le pi3b+ (alim officiel du pi4 avec adaptateur USB-C vers micro USB) et plus de soucis de « undervoltage »

La clé est branché et pour le moment tout semble OK . Je vais attendre quelques heures avant de me réjouir mais j’ai bon espoir 

Dans les logs j’ai :
`mtp-probe: bus: 1, device: 8 was not an MTP device`

J’ai désactivé mon scenario qui relance le demon toute les heures

EDIT du lendemain :

La page Santé est entierment en time-out :weary:
![abeille-sante-2](https://user-images.githubusercontent.com/7727919/107116351-cb38f480-6872-11eb-9276-02589ff75364.png)


EDIT : de nouveau ce message d'erreur javascript ainsi qu'un acces difficile à la page de configuration (chargement en boucle)
`
http://192.168.0.20/index.php?v=d&m=Abeille&p=Abeille&id=Abeille | 309 | Uncaught TypeError: Cannot set property 'Type' of undefined
-- | -- | --
`

En parallèle je suspect que les soucis peuvent être causé par mon installation de Debian 10 en 64bits sur le PI3b+ , soucis particulièrement lié à l'USB (dongle zigate, SSD,...) .

**Comment by KiwiHC16** [comment]
Si je comprends bien module TTL-USB remplacé.
Je vois les trois process en vert, donc ok de ce coté.

Peux tu installer la version stable de ce soir et me dire ce qu il se passe ?

**Comment by komega13** [comment]
Tout à l'air OK depuis 48H
Donc pour clore le sujet il semblerai que ce soit bel et bien la version 64bit de Debian qui causait mes soucis, pour ceux à qui cela arriverait repassez en version 32bits sur RPI3b+
