### ISSUE TITLE
Erreur Java Script lors de "Force la réintégration du reseau"

### ISSUE THREAD

**Issue by komega13** [KiwiHC16/Abeille#1719]
Bonjour

Lors d'une commande "Force la réintégration du réseau" j'ai ce message dans les erreur JavaScript :
`http://192.168.0.20/index.php?v=d&m=Abeille&p=Abeille | 309 | Uncaught TypeError: Cannot set property 'Type' of undefined
-- | -- | --`

**Comment by tcharp38** [comment]
Salut
Ca c'est un pb deja fixé.
Tu es sur quelle verison d'Abeille ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Une nouvelle stable ce jour (je ne sais pas si ce bug est corrigé sur cette stable ou celle de lundi prochain).

**Comment by komega13** [comment]
J'ai fait la mise à jour Abeille le bug semble avoir disparu :) merci de votre travail

**Comment by KiwiHC16** [comment]
Ok, je clos alos. Merci pour le retour.
