### ISSUE TITLE
Pb filiation objets: parentId = object_id. aucun objet ne peut avoir un autre parent que celui du plugin

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#172]
@KiwiHC16 , je pense que l'on va avoir un souci pour la flexibilité de la solution. Il doit y avoir une solution cependant.

Le parent_id est défini au niveau du plugin, lors de la creation d'un objet (announce), l'objet prend la valeur AbeilleParentId du plugin pour object_id. Le parent du plugin devient alors aussi celui de l'objet.

or chaque device devrait pouvoir être rattaché a un autre objet que celui du plugin (AbeilleParentId). si on garde cette structure tout les objets zigbee ne pourront pas être dispatché dans d'autres objets jeedom.

Cet id doit être défini après coup ou il faut trouver un moyen pour qu'il ne soit plus écraser par celui du plugin, une fois défini. 

un mécanisme semble re-affecter le AbeilleParentId aux objets Abeille régulièrement. il faudrait trouver lequel.

**Comment by edgd1er** [comment]
dans abeille.php, l'input met correctement le parent_id (qui s'appelle object_id en bdd) et permet l'affectation des devices à l'objet de son choix.

si on garde:
 $elogic->setObject_id($parameters_info['AbeilleParentId']); dans abeille.class.php
et 
<select class="configKey form-control" data-l1key="AbeilleParentId"> dans configuration.php

la parent par défaut est gardé dans le plugin Abeille, mais si besoin on peut lui mettre un parent particulier, en allant sur la conf du périphérique.

**Comment by KiwiHC16** [comment]
L'idée c 'est qu'un objet Abeille et rattaché à un object Jeedom par defaut à la création. Ensuite si tu edites l'objet Abeille tu peux le rattacher à l'objet que tu veux.
Par exemple, je viens d'appairer 6 ampoules Ikea et elles sont toutes dans un objet defaut disons "bureau Kiwi". Maintenant je vais en mettre une dans ma chambre, il me suffit d'ouvrir l'objet ampoule d'une des ampoules et de changer son objet de rattachement à "Chambre Kiwi".

**Comment by KiwiHC16** [comment]
Pour moi la seule modif qu'il faut faire est de mettre une liste deroulante dans le plugin pour selectionner un objet defaut de rattachement.

Ou alors je ne comprends pas ton point.

**Comment by edgd1er** [comment]
On est en accord sur le but: affecter un device a un objet bureau, ou cuisine ou garage.

Je crois que hier soir, j'étais bien fatigué et je me suis emmeler les pinceaux. Tu verras dans la PR, les changements sont mineurs.. ;) KiwiHC16/Abeille/pull/175

**Comment by KiwiHC16** [comment]
Je n'avais pas encore vu. Ca c'est top. Et en plus tu as ajouté les info battery tip top.
Je clos le sujet alors.
