### ISSUE TITLE
Retrait message: "XXXX a rejoin le reseau" qui provoque des questiosn utilisateurs pour rien.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1720]
![](https://community.jeedom.com/uploads/default/original/3X/c/0/c0eb217aa4655306a9e0beeeea6f70a5305d435b.png)

**Comment by mickadam29** [comment]
@KiwiHC16 
Peux-tu garder une option pour les afficher, mais masqués par défaut.
Je te demande ça car depuis 1 semaine pratiquement je perds tous les jours mes ampoules (routeurs). C'est pénible et ca me permet de voir que je l'ai bien remise sur le réseau. Merci à toi

**Comment by tcharp38** [comment]
Je l'avais ajouté car je trouvais l'info utile, tout comme le fait que l'eq quitte le reseau mais il faut améliorer ca.
Exemple; il quitte  le reseau pour le rejoindre dans la foulée.. faudrait idealement pas sortir les 2 messages car sans interet .

Bref a reflechir pour le court terme. Rajouter des options à droite à et gauche c'est aussi rajouter des tas de soucis potentiels.

**Comment by KiwiHC16** [comment]
Le plus simple serait d'etre plus explicite dans le texte pour clarifier le sujet pour les utilisateurs.
Ou faire un renvoie vers la doc pour expliquer ce qu'il se passe.

Sinon les faire apparaitre que sur lemode dev et pas sur le mode utilisateur.

**Comment by tcharp38** [comment]
A priori le message a déja ete viré.
Donc je fais rien et je clos.
