### ISSUE TITLE
@Jake309: V.2021-02-01 Pb d'inclusion et objet parent

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#1723]
Bonjour !

je viens de refaire des inclusions depuis la MAJ du 01/02, et ca crée des bug.
Mes appareils s'incluent bien, mais ils n'acceptent aucune modif, a tel point que quand je change d'objet parents, il me crée un doublon sans commande sur celui de la ruche et mon équipement avec toute les commandes n'est plus dans ma liste sur le plugin.

Je m'explique, ma ruche est dans "home", donc toutes mes inclusions s'ajoutent dans "home". Quand je veux bouger un équipement dans "salle de bain" par exemple, au niveau de abeille il reste dans home et sans commande, quand je vais sur le dashboard "salle de bain" et que je clique sur ce même équipement, la je vois avec les commandes...
Jusque la, on pourrait dire, bon ok, pas de souci, c'est gérable, mais ca rajoute un autre pb, l'équipement passe en time out.

J'ai pas vue de chose intéressante dans les log en mode debug, ou j'ai pas sur voir, mais dans santé, 2 lignes qui parlent d'elles meme sont affichées.

je vous joints des images pour illustrer mes explication, car je sais que je ne suis pas toujours très claire

En espérant que ce retour soit pertinent et utile =)
Merci

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5909629/AbeilleParser.log)
![apres save objet parent puis save modif commande](https://user-images.githubusercontent.com/49479084/106571500-89891080-6537-11eb-9798-ac1835fa999d.JPG)
![dans home](https://user-images.githubusercontent.com/49479084/106571504-8a21a700-6537-11eb-93f7-3e9913835797.JPG)
![dans sdb](https://user-images.githubusercontent.com/49479084/106571505-8a21a700-6537-11eb-8459-603b36f83d5c.JPG)
![santé abeille](https://user-images.githubusercontent.com/49479084/106571507-8aba3d80-6537-11eb-933f-d3806c58eb80.JPG)

**Comment by Jake309** [comment]
j'ai oublié d'ajouter les balises à l'issue :/ désolé

**Comment by YaYa-33** [comment]
Bonjour,
J'ai exactement le même soucis que toi,
J'ai reçu ma sirène Heiman aujourd'hui et impossible de la rajouter sur le plugin Abeille.
Idem pour des capteurs de présence que j'ai voulu rajouter aujourd'hui. Ca ne fonctionne plus !

Si j'essaye de modifier un équipement déjà existant je me retrouve avec la même erreur ... :(
Merci d'avance pour vos retours

![abeille1](https://user-images.githubusercontent.com/78439221/106642060-325f5c00-6588-11eb-88f9-6e09279e4d53.png)
![abeille2](https://user-images.githubusercontent.com/78439221/106642062-32f7f280-6588-11eb-961c-9c82f836c7a9.png)
![abeille3](https://user-images.githubusercontent.com/78439221/106642065-33908900-6588-11eb-97b3-fa7a190369e5.png)
![abeille4](https://user-images.githubusercontent.com/78439221/106642337-7e120580-6588-11eb-9cab-2850517aea12.png)
![abeille5](https://user-images.githubusercontent.com/78439221/106642465-a994f000-6588-11eb-8b6a-a91871f1dd7a.png)

**Comment by Jake309** [comment]
J'ajoute un sujet de la communité jeedom créé pour le même problème.
[https://community.jeedom.com/t/abeille-cree-un-equipement-que-je-ne-peux-renommer-car-existe-deja/51971/3](url)
Ca permet d'avoir les suivis des 2 cotés. j'ai mis le lien de l'issu dans une de mes réponses de ce sujet

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by Jake309** [comment]
jeedom en 4.1.19 :/
abeille : 2021-02-01 11:36:15

surement la version de jeedom ...
Je vais regarder comment revenir en 4.1.18

**Comment by KiwiHC16** [comment]
Les problemes liés aux changements de pièce ne sont pas gérés par Abeille alors j'ai un gros doute sur Jeedom.
Si tu peux essayer en 4.1.18 cela serait cool. Recuperes un backup et rollback.

**Comment by YaYa-33** [comment]
Est-ce la version 4.1.19 de Jeedom ou la version du 1er février d'Abeille qui nous fait cette erreur ?

Dans tous les cas, comment downgrader l'une des versions ? (Abeille ou Jeedom)

Merci

**Comment by KiwiHC16** [comment]
Je ne suis en mesure de reproduire le soucis avec differentes version d'Abeilles. Et je n'ai pas testé Jeedom 4.1.19.
Je vais essayer avec 4.1.19 quand je peux.

**Comment by Jake309** [comment]
je suis en train de rollback jeedom en 4.1.18, je te dis =)

**Comment by YaYa-33** [comment]
Dacc, on est obligé de restaurer un backup 4.1.18 pour repasser dans cette version, ou il existe une manip ?
Ca m'embête car j'ai fais pas mal de modif depuis la version 4.1.19, ça voudrait dire que je vais tout perdre.

**Comment by KiwiHC16** [comment]
Je viens de passer mon systeme en 4.1.19 avec Abeille stable et aucun soucis visible .

Etes te vous bien en Debian 10.

Quel est le HW ? RPI ? VM ?

**Comment by KiwiHC16** [comment]
Que dit le paragraphe:

![Capture d’écran 2021-02-03 à 18 08 55](https://user-images.githubusercontent.com/8549674/106782804-e2959900-664a-11eb-92f9-3ebf800e3b5a.png)

**Comment by Jake309** [comment]
Yes debian 10 pour proxmox VM, debian 10 pour jeedom
En jeedom 4.1.18 et abeille 2021-01-25 09:09:39, pas de souci
Ou trouve t-on ton screen ? 
Je mets a jour abeille

**Comment by Jake309** [comment]
![image](https://user-images.githubusercontent.com/49479084/106783159-43bd6c80-664b-11eb-8fe0-98e524d27fa0.png)

**Comment by KiwiHC16** [comment]
Je viens de supprimer Abeille de faire une install Stabel depuis market et toujours pas de soucis.

**Comment by Jake309** [comment]
abeille est a la version de lundi, je fais des test
j'espère que c'est pas un bug pendant la MAJ, sinon je vais avoir la rage !
Mais je ne suis pas le seul, donc étrange

**Comment by KiwiHC16** [comment]
@Jake309 quelle est ta conclusion ? 
- Jeedom 4.1.18 - Abeille abeille 2021-01-25 09:09:39 => pas de souci
- jeedom en 4.1.19 - Abeille : 2021-02-01 11:36:15 => soucis 

Est ce tes observations ?

**Comment by Jake309** [comment]
attends, je fais les entre 2
4.1.18 et 25/01 pas de pb apres rollback
avant ca, souci en 4.1.19 et 01/02
en 4.1.18 et 01/02 : souci :s

**Comment by Jake309** [comment]
j'attends ton retour, sinon je vais perdre les log. 
mais j'ai aucun souci a refaire un rollback pour tester ;)

**Comment by KiwiHC16** [comment]
Je suis preneur de jeedom 4.1.19 et Abeille stable, 2021-02-01.

Car cela fonctionne sur mon systeme et c est la version la plus récente (je prefere debugger la dessus).

**Comment by KiwiHC16** [comment]
Quel browser web ?

**Comment by Jake309** [comment]
chrome
j'ai fais un rollback 4.1.18 et 25/01 et passe les 2 maj, abeille et jeedom et refais une intégration

**Comment by KiwiHC16** [comment]
Je n ai pas pas Chrome. Peux tu essayer avec Firefox ?

**Comment by YaYa-33** [comment]
Moi je suis sous jeedom 4.1.19 et Abeille stable 2021-02-01.
Sous Rpi 4b et Debian 10

J'avais aucun soucis sous jeedom 4.1.18 et Abeille du 25/01

**Comment by KiwiHC16** [comment]
@YaYa-33 peux tu ouvrir un cas pour ton systeme avec la description des soucis que tu rencontres ?

**Comment by Jake309** [comment]
j'ai pris un peu de temps a refaire mes scénario etc pour avoir une save propre.
Tu veux quoi comme log éxactement ? 
parce qu'en fonction de la ou ca merde, juste le parser suffira pas je pense, faut voir au niveau conf du plugin non ?

**Comment by Jake309** [comment]
seul abeille a des log, tout le reste vide...

**Edit,** mon équipement test, a l'origine c'est Abeille1-85

![image](https://user-images.githubusercontent.com/49479084/106786746-31ddc880-664f-11eb-9db1-e09597bbcdd8.png)

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/5920416/Abeille.txt)

**Comment by Jake309** [comment]
c'est 2 lignes la m'interpellent 
[2021-02-03 18:38:06][DEBUG] : Nb repertoire template parcourus: 196 dont 3 exclus soit 193. 193 fichiers template ajoutés à la liste, 0 introuvables et 0 templates illisibles.
[2021-02-03 18:38:19][DEBUG] : Nb repertoire template parcourus: 196 dont 3 exclus soit 193. 193 fichiers template ajoutés à la liste, 0 introuvables et 0 templates illisibles.

**Comment by Jake309** [comment]
les 2 test sont time out, mais pas le abeille1-85...
![image](https://user-images.githubusercontent.com/49479084/106787553-24750e00-6650-11eb-9506-b5d543c38a95.png)

**Comment by KiwiHC16** [comment]
Il faut qu'on cadre les soucis car sinon je ne peux suivre. Premier sujet que je vois, appellons le A):
`Quand je veux bouger un équipement dans "salle de bain" par exemple, au niveau de abeille il reste dans home et sans commande, quand je vais sur le dashboard "salle de bain" et que je clique sur ce même équipement, la je vois avec les commandes...`

**Comment by KiwiHC16** [comment]
B) Sauvegarde `un équipement portant ce nom existe deja`

**Comment by KiwiHC16** [comment]
C) `Equipement sans commande`

**Comment by KiwiHC16** [comment]
D) `TimeOut`

**Comment by SebRider** [comment]
> Il faut qu'on cadre les soucis car sinon je ne peux suivre. Premier sujet que je vois, appellons le A):
> `Quand je veux bouger un équipement dans "salle de bain" par exemple, au niveau de abeille il reste dans home et sans commande, quand je vais sur le dashboard "salle de bain" et que je clique sur ce même équipement, la je vois avec les commandes...`

Oui j'ai également ce soucis, bien mieux expliqué que moi dans mon issue et mon avalanche de bug dont j'ai l'impression de plus rien suivre.

**Comment by Jake309** [comment]
alors, le problème : 
quand tu intègres un équipement, rien ne bug si tu ne touches a rien.
une fois que tu rentres dessus pour le renommer ou changer le parent, tu sauvegarde, il te crée un doublon, sans commande.
ce qui entraine, si tu fais un second enregistrement il te dit qu'il existe déjà, mais ca on s'en fiche.
Le plus important je pense c'est que des que tu saves, tu te retrouves avec mon screen de santé et mon dashboard

**Comment by SebRider** [comment]
> alors, le problème :
> quand tu intègres un équipement, rien ne bug si tu ne touches a rien.
> une fois que tu rentres dessus pour le renommer ou changer le parent, tu sauvegarde, il te crée un doublon, sans commande.
> ce qui entraine, si tu fais un second enregistrement il te dit qu'il existe déjà, mais ca on s'en fiche.
> Le plus important je pense c'est que des que tu saves, tu te retrouves avec mon screen de santé et mon dashboard

On est d'accord alors disons qu'on ne renomme pas ni modifie l'objet parent de cet équipement. Tu vas me dire donc pas de bug...
Prenons l'exemple d'un nouvel équipement que je viens d'inclure, un capteur d'ouverture Xiaomi. 
L'inclusion s'est bien passée et il est en ligne, un beau dashboard santé, propre comme on l'attend :
![Capture2](https://user-images.githubusercontent.com/78418545/106816596-e5f24a00-6675-11eb-86d6-5f73bd2527c4.JPG)

Je vais voir ses magnifiques commandes pour le coup bien crées ET fonctionnelles (a condition qu'elles soient affichés par défaut). Je veut simplement admettons afficher la commande "nom", (pas très utile mais cas d'école va-t-on dire). Voila l'erreur retournée :
![Capture](https://user-images.githubusercontent.com/78418545/106816654-facedd80-6675-11eb-9e05-9775d8afcb95.JPG)
Et je précise que c'est une install Jeedom clean, sur un nouveau PI4, debian et cle zigate mise a jour et eprom raz. Le capteur est fraichement déballé et c'est sa première inclusion dans ce domicile, pas de quoi faire dire que l'équipement porte déjà le même nom, je me trompe ?

**Comment by Jake309** [comment]
@SebRider jai le même pb que toi, pas la peine de répondre à mon message pour dire la même chose.
Ca pollue inutilement le cas.
Le souci va pas se régler comme ça.

Je commence doucement avec abeille, laisse le temps à kiwi de creuser le truc avec laide quon peut lui apporter.
En sachant que comme nous, il a une vie à côté...

Note pour plus tard, fais une sauvegarde avant de faire des modif ou mise à jour, ça permet des retour en arrière facile.

**Comment by SebRider** [comment]
Désolé d'avoir paru insistant, je suis entièrement conscient que tout le monde ici a une vie. 

Ce n'était pas pour polluer mais justement peut être donner l'élément qu'à l'origine on dirais que l'inclusion de l'objet est déjà défectueuse vu que jeedom retourne l'info d'équipement qui existe déjà.

> _HS : Je suis dans le même cas que toi @Jake309 avec Abeille. J'ai en fait deux installations Jeedom parallèle, la futur, celle de mes tests avec Abeille.  Et mon installation actuelle vieillissante a base de pi 2 et 3, de pluggin zigate et une architecture réseau que je veut changer. Perso j'utilise un nas pour faire les backups automatiques chaque nuit et en plus un backup avant et après une belle session de nouveauté, scenario, etc... Bref j'arrête cette dernière parenthèse HS polluante._

**Comment by Jake309** [comment]
@SebRider 
> Je vais voir ses magnifiques commandes pour le coup bien crées ET fonctionnelles (a condition qu'elles soient affichés par défaut). Je veut simplement admettons afficher la commande "nom", (pas très utile mais cas d'école va-t-on dire). Voila l'erreur retournée :
> ![Capture](https://user-images.githubusercontent.com/78418545/106816654-facedd80-6675-11eb-9e05-9775d8afcb95.JPG)

Ca t'as mis ce message tout de suite après avoir appuyer sur test de la ligne nom ou après avec appuyé sur test et sauvegarde ?

**Comment by SebRider** [comment]
La, juste après avoir créé l'équipement je suis allé voir ses commandes puis j'ai cliqué sur "Afficher" la commande "nom" puis "Sauvegarder"

**Comment by Jake309** [comment]
Je viens de faire le test, je suis repasser en dernière version de jeedom et abeille comme pour toi.
juste appuyer sur test ca ne fait pas de pb. C'est quand tu appuis sur sauvegarder que tu as ce pb, mais comme on ne change pas le nom ni le parent, on ne perd pas les commandes et il ne crée pas de doublon.

@KiwiHC16 , j'ai toujours ces 2 lignes dans les log abeille, c'est normal ?
`[2021-02-03 21:28:11][DEBUG] : AbeilleTools::isMissingDaemons:446: False,   found: {"cmd":1,"parser":1,"serialRead1":1}
[2021-02-03 21:28:11][DEBUG] : AbeilleTools::isMissingDaemons:446: False,   found: {"cmd":1,"parser":1,"serialRead1":1}`

**Comment by Jake309** [comment]
Alors, récapitulatif:
Jeedom 4.1.**18** - Abeille _2021-01-25 09:09:39_ => pas de souci
jeedom 4.1.19 - Abeille _2021-01-25 09:09:39_  => pas de souci
Jeedom 4.1.**18** - Abeille : 2021-02-01 11:36:15 => bug
jeedom 4.1.19 - Abeille : 2021-02-01 11:36:15 => bug
J'ai refais les 4 possibilités ce matin.
version actuelle en prod : jeedom 4.1.19 - Abeille 2021-01-25 09:09:39
S'il te faut n'importe quoi kiwi dis moi. je suis pas hyper allaise avec la compréhension des logs, j'ai pas assez d'expérience.

**Comment by KiwiHC16** [comment]
@Jake309 super recap. Merci.
Peux tu faire le test suivant:
jeedom 4.1.19 - Abeille Beta

**Comment by KiwiHC16** [comment]
Autre test: Peux tu mettre le plugin en mode "développeur"  sur la conf "jeedom 4.1.19 - Abeille : 2021-02-01 11:36:15"
![Capture d’écran 2021-02-04 à 12 43 33](https://user-images.githubusercontent.com/8549674/106888263-98fa8c00-66e6-11eb-9bed-295d57bfb0f9.png)

As tu toujours le soucis ?

**Comment by Jake309** [comment]
J'ai vue ta réponse pour SebRider, du coup j'ai pris 5min pour tester,
Abeille beta est sans pb pour moi aussi, je pense que tu peux la passer en stable comme tu proposais.

Sur le forum jeedom tu parles d'un PR, c'est quoi ?
Je vais y travailler, je ne promets pas une remise à jours total, mais au fur et a mesure que j'ai des trucs je les mettrais =)

**Comment by sbx59** [comment]
Bonjour,
Comment passé par la version Beta SVP ?

**Comment by YaYa-33** [comment]
Il faut autoriser l'installation de plugin beta sur le market de jeedom (connecte toi avec tes identifiants et dans les paramètres de ton compte active l'options pour les versions beta) ensuite tu retourne sur le market, tu recherches le plugin Abeille et tu auras l'options "version beta" de disponible.

**Comment by sbx59** [comment]
Zut, avec cette version : Aucune Zigate n'est activée ! 
Pourtant tout est OK dans les paramètres ...

**Comment by sbx59** [comment]
Meme avec la version beta, je n'arrive pas a y inclure mon Xiaomi sensor :(

**Comment by Jake309** [comment]
> Meme avec la version beta, je n'arrive pas a y inclure mon Xiaomi sensor :(

ton souci est pour inclure ? 
si c'est le cas, ton problème est différent. Ici on sait inclure mais on ne pouvait pas faire de modif sur l'équipement sans créer de bug.
Ton problème vient d'ailleurs

**Comment by sbx59** [comment]
En effet c'est pour inclure. Avec l'appli zigate aucun probleme. Je vais voir sur d'autre fils alors

**Comment by sbx59** [comment]
j'ajoute que ...

<a href='https://www.casimages.com/i/210206063724196413.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/06/210206063724196413.png' border='0' alt='Mon image' /></a>

<a href='https://www.casimages.com/i/210206063724123605.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/02/06/210206063724123605.png' border='0' alt='Mon image' /></a>

**Comment by KiwiHC16** [comment]
Je vais publier la beta en stable demain. Je clos.
