### ISSUE TITLE
Problème assignation groupe télécommande impossible

### ISSUE THREAD

**Issue by alexh-fr** [KiwiHC16/Abeille#1726]
Bonjour !

Après de nombreux essais depuis quelques jours, application de la documentation et recherche internet, je n'arrive toujours pas à assigner une télécommande à un groupe.

Version Jeedom: 4.1.19
Version Abeille: 2021-02-01 11:36:15
Version ZiGate: FW031D

Je peut aisément ajouter mes ampoules/bandeau Phillips Hue à un groupe.
Cependant, je n'arrive pas à assigné un groupe à une télécommande.
Ce que je fait:
1. Séléction de la télécommande
2. Renseignement du groupe
3. Appui sur "set Group Remote", tout en appuyant sur les boutons de ma télécommande.
4. Sélection de la télécommande puis "get Group"
4. Et la, rien ne se passe.

J'ai tenté avec une télécommande "carré" d'Ikea (2 boutons) ainsi qu'une télécommande Phillis Hue.

Par ailleurs, sur la documentation, il est mentionné de renseigner le groupe dans les paramètres Abeille de la télécommande, sauf que l'option n'est pas disponible.

Est-ce que je fait mal ? ou s'agit-il d'un souci côté Jeedom ?
![image](https://user-images.githubusercontent.com/78020272/106861432-09dd7c00-66c6-11eb-85bd-4620d5459cc0.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
```
Appui sur "set Group Remote", tout en appuyant sur les boutons de ma télécommande.
```
C est ben ce qu il faut faire.
- Testé avec le telecommande ronde Ikea (5 boutons). 
- Je crois avoir testé avec telecommande carré mais je ne suis pas sure. Devrait fonctionner.
- Autres télécommandes (Hue,...) ne fonctionne probablement pas;

```
Sélection de la télécommande puis "get Group"
```
Ne fonctionne pas sur les telecommande. D ou la proposition: http://kiwihc16.free.fr/Ikea.html#groupes

```
Par ailleurs, sur la documentation, il est mentionné de renseigner le groupe dans les paramètres Abeille de la télécommande, sauf que l'option n'est pas disponible.
```
C est un bug corrigé sur les prochaines versions d Abeille.

**Comment by davefr01** [comment]
Bonjour :)
J'ai exactement le même souci.
J'ai dû supprimer mes commandes de store Ikea (télécommande carrée) et je suis désormais incapable de les rajouter dans un groupe comme j'avais pu le faire il y a plus d'un an de cela avec une version antérieure du plugin.

**Comment by tcharp38** [comment]
Salut @davefr01 
Ca n'est pas trivial et du coup juste pour etre sur tu as
- selectionné ton equipement (case à cocher)
- entré le num de groupe à cote de "Id"
- puis fait "add group"

C'est ca ?

**Comment by davefr01** [comment]
Hello !
Oui j'ai essayé un grand nombre de fois en cochant ma télécommande, en indiquant l'id du groupe et en utilisant le bouton set group remote, puis en activant la télécommande en pressant sur la commande.
Mais elle n'apparaît jamais dans le tableau.

**Comment by tcharp38** [comment]
Salut
Set group remote ?
Je te parlais de "add group".

Si oui, peux tu refaire l'action puis me filer le package de logs (drag & drop ici, page support/telecharger tout).
Merci

**Comment by davefr01** [comment]
Bonjour,
Désolé pour mon retour tardif. Voici les logs du plugin lorsque je tente d'ajouter mon interrupteur de store Ikea en tant que remote du groupe 0000.
[Archive.zip](https://github.com/KiwiHC16/Abeille/files/7075554/Archive.zip)

**Comment by tcharp38** [comment]
Salut @davefr01
Tu n'es visiblement pas en mode debug donc je n'ai pas de trace utile (page config, debug, sauvegarder).
D'autre part si ca n'est pas le cas, change la config Jeedom pour augmenter le nombre de lignes de 500 à 5000 par ex, puis redemarre Abeille avant toute chose.

Merci

**Comment by davefr01** [comment]
Je suis pourtant bien en debug (je vois des messages [DEBUG] dans Abeille.log.
J'ai refait une tentative en recapturant les logs.
[Archive.zip](https://github.com/KiwiHC16/Abeille/files/7077319/Archive.zip)
Je ne sais pas si tu verras plus de choses...

**Comment by tcharp38** [comment]
Tres etrange. Il n'y a toujours pas log "AbeilleParser.log" pourtant obligatoire.
D'ailleurs pourquoi ca genere un "Archive.zip" ? Tu procedes comment pour recuperer les logs ? La page "support" puis telecharger tout, devrait te filer un package du type tar.gz que tu peux directement faire glisser ici.

**Comment by davefr01** [comment]
j'ai téléchargé les logs abeille 1 par 1.
Voici le tar.gz en passant par la page support 
[AbeilleLogs-210830.tar.gz](https://github.com/KiwiHC16/Abeille/files/7077400/AbeilleLogs-210830.tar.gz)

**Comment by tcharp38** [comment]
Ha c'est bien + complet.
Par contre il dit toujours "que" 500 lignes

> [2021-08-30 16:23:05] Max atteint (490 lignes) Log précédent sauvé sous '/tmp/jeedom/Abeille/AbeilleCmd-prev.log'

Mais je ne vois rien. Tu as fait ton add group à quelle heure ?

**Comment by davefr01** [comment]
j'ai fait un "set remote group" vers 16H13

**Comment by tcharp38** [comment]
Alors je ne le vois pas. La trace AbeilleCmd par ex la + vieille est 16h16. Logs trop courts.

Donc je ne vois pas l'ordre envoyé mais je vois une trace qui dit que ca s'est mal passé.
[2021-08-30 16:13:09] Abeille1, Type=8000/Status, Status=00/Success, SQN=37, PacketType=0530
[2021-08-30 16:13:16] Abeille1, Type=8702/APS data confirm fail, Status=F0/MAC_ENUM_TRANSACTION_EXPIRED, SrcEP=01, DestEP=01, AddrMode=02, Addr=77D5, SQN=37

C'est bien ce periph @addr 77D5 ?
Si oui alors tu sembles ne pas l'avoir reveille en meme temps comme necessaire pour tout equipement sur batterie.

**Comment by davefr01** [comment]
oui c'est bien ce périphérique.
Je viens de le récréer dans Jeedom, mais j'ai toujours le même phénomène, je ne parviens pas à le joindre au groupe quelque soit le moment où je tente de l'activer.
Cela dit, le comportement du bouton est étrange : de temps à autre, lorsque j'appuie dessus, il parvient à commander mon store (une seule fois avant un bon moment avant que je ne puisse renvoyer une commande), il semblerait donc savoir qu'il appartient au groupe dans lequel j'essaie de le mettre...

**Comment by tcharp38** [comment]
Tu l'as bien reveille juste apres ton "set remote" ?
Ta telecommande est de quel type ? Peux tu me donner ce qui est affiché quand tu cliques sur l equipement/avancé pour fichier JSON
![image](https://user-images.githubusercontent.com/35221038/131556299-e3086b59-a7de-4709-867c-ae9b1162f5c7.png)

Ca me dira comment ton equipement est reconnu.

**Comment by davefr01** [comment]
J'utilise la télécommande de store à 2 états. Je la réveille après avoir sélectionné l'objet, saisi mon groupe, et cliqué sur le bouton set group remote.
![image](https://user-images.githubusercontent.com/88789967/131671642-aece1740-c18e-4265-a1ef-f76ee7d2da53.png)

**Comment by tcharp38** [comment]
Salut @davefr01 
Est ce que tu pourrais me faire une decouverte zigbee de cet equipement ?
Page equipement/avancé => assistant: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

Pense à la reveiller si plus rien ne remonte et qu'il reste des boutons en orange.
Merci

**Comment by tcharp38** [comment]
Aucun signe de vie sur ce sujet.
Je clos.
A reouvrir si besoin
