### ISSUE TITLE
TimeOut des équipements en pagaille. Suite et fin ?

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1727]
@KiwiHC16 @tcharp38 

Je pense avoir mis le doigt sur un problème qui concerne les ampoules IKEA dans leur fonction de Routage.
Depuis une semaine maintenant, tous les jours je dois débrancher et rebrancher mes ampoules IKEA (6) car celles-ci passent en timeout, et de ce fait tous les équipements qui transitent par elles aussi.
Je pense à un bug dans la version "dev_tcharp38, 2021-01-29 12:51:55". En effet, mon problème date de cette version. Au passage, je suis passé à JEEDOM 4.1.19 à la même période.
Je m'explique : 
Je possède un contacteur legrand 20AX. Celui-ci ne remontait plus la puissance consommée depuis la mise à jour. Vérifié par des  graphes de consommation. J'ai rétabli l'envoi de la puissance avec l'aide de @KiwiHC16 qui m'a indiqué d'exécuter à nouveau les commandes bindtozigate, setreportpuissance. Depuis, la puissance consommée est correctement envoyée. Toutefois je n'avais pas prêté attention aux commandes. Elles disposent de durée en paramètre.

![image](https://user-images.githubusercontent.com/36518012/107111580-894b8680-6851-11eb-9037-4aa29a07360e.png)

C'est en repensant à ce problème que je suis allé voir les équipements IKEA. Et je vois là aussi que les commandes bind disposent d'une valeur en secondes. Le modèle a probablement changé depuis que j'avais créé mes ampoules car je ne me souviens pas avoir vu ces champs auparavant. J'ai réinclu des équipements (y compris mes ampoules) mais de mémoire cela fait déjà un moment. Et le problème ne date que de 8 jours.

J'ai donc positionné 30 secondes à chacune des commandes pour chacune des mes ampoules. 

![image](https://user-images.githubusercontent.com/36518012/107111855-91a4c100-6853-11eb-9a6c-71c0663f9a13.png)

Fait hier dans l'après-midi et pour le moment aucun timeout. Je ne vais toucher à rien d'autre ce WE. (Je précise au passage que ces ampoules en timeout dans jeedom restent pilotables avec la télécommande HUE, donc actives sur le réseau Zigbee). 
Ca me corrige également un petit souci, où jeedom me disait que des ampoules étaient allumées alors qu'elles étaient éteintes.

![image](https://user-images.githubusercontent.com/36518012/107111892-d16ba880-6853-11eb-98ff-e9163cf60e84.png)

Quand je parle de bug, je pense que les versions précédentes "stimulaient" les ampoules IKEA (d'ailleurs je crois que vous faites un bind des ampoules IKEA toutes les 15 minutes, et cela était sans doute suffisant pour éviter un timeout. Mise à part ça , je vois pas en quoi Abeille interviendrait. Mais si cela se confirme dans les jours à venir, il y a quelque chose à creuser. Soit dans la création des objets lors de l'inclusion (les bind sont mal implémentés) soit dans l'interrogation toutes les 15 minutes.
Je remplacerai mes 30 secondes par une valeur plus élevée si tout fonctionne bien et je verrai l'impact.

Désolé d'être aussi long.
Si cela fonctionne bien, je vais garder la version master, celle qui est en place, ainsi que celle de jeedom afin de pouvoir vous envoyer des logs si nécessaire.
Sinon je continuerai de suivre la version Master.

Merci encore pour le taf que vous faites

Bon courage

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Tout d'abord une petite clarification avant d aller dans les détails éventuellement. 

Le TimeOut n'est qu'une information pour essayer de détecter de possible soucis avec certains équipements. Le principe: chaque équipement dans Abeille possède une valeur de TimeOut. Cette valeur est basée sur la périodicité de messages reçus de cet équipement (en rien en relation avec les envoies). 

Par exemple: Typiquement un capteur de temperature Xiaomi envoie spontanément un message vers Abeille toutes les heures. TimeOut proposé: 120 minutes. On "autorise" une perte de packet par période. A vous de voir.

Comme vous pouvez l'imaginer chaque équipement a son propre fonctionnement et vu le nombre de type d équipement intégrés dans Abeille, je ne suis pas en mesure de tester et verifier toutes les valeurs de timeout proposées.

Pour les équipement sur 220V (routeurs), certains sont interrogés (poll) de façon périodique par abeille. De ce fait ils répondent et remettent à zero les compteurs et donc pas de timeout.

C est une partie qu'on est entrain de revoir et il va certainement y avoir différentes evolutions.

Donc si un équipement apparait en timeout cela ne veut pas dire qu il ne fonctionne pas.

Premiere chose a faire, lui envoyer un getName depuis la ruche pour voir s'il répond (pour ceux sur pile il faut les réveiller).

S'il ne répond pas alors passer à la recherche de panne.

**Comment by mickadam29** [comment]
Merci @KiwiHC16 

Je ne suis pas revenu faire le bilan.
J'ai toujours mes ampoules qui m'embêtent. Pour le timeout, ce qui me paraît étrange c'est que cela concerne 6 ampoules.
Et que les routeurs sont en liaison directe avec Zigate. Je vérifierai les logs de polling ainsi que le getname. J'ai d'autres équipements de type routeur à proximité de ces ampoules et eux parviennent à transmettre et surtout l'info est reçue par la zigate. J'élimine peut-être trop rapidement une perturbation avec mon wifi, ou autre. Une ampoule défectueuse mais le timeout ne concernerait qu'elle même.  A suivre.

**Comment by mickadam29** [comment]
Un cas concret :
![image](https://user-images.githubusercontent.com/36518012/107205065-b63c9c80-69fd-11eb-857f-f37af67db7b4.png)

Get-name fonctionne, j'ai bien le nom de l'équipement.
Aucun moyen de piloter avec les fonctions ON/OFF

La superposition des ONLINE de 4 ampoules montre des périodes où elles sont toutes OFFLINE au même moment. Bandes noires. Et ce depuis le 30 janvier.

![image](https://user-images.githubusercontent.com/36518012/107206765-c3f32180-69ff-11eb-9c79-e46e6af017a9.png)

**Comment by KiwiHC16** [comment]
Peux tu sélectionner une ampoule sur laquelle on va se focaliser. 
Toute la suite sera uniquement sur cette ampoule. 
Une fois qu on aura compris avec cette ampoule on regardera les autres. 
Peux tu me dire ce que retourne la commande nom ?

**Comment by mickadam29** [comment]
Get-name à prendre en compte : IkeaTradfriBulbE27Opal1000lm

**Comment by mickadam29** [comment]
Ce soir l'ampoule ne répond pas. Get-name ok
Je la débranche. Tout repart pour quelques temps.
De nombreux message de route

![image](https://user-images.githubusercontent.com/36518012/107260243-38e54c00-6a3e-11eb-96cf-73e10e2f12ba.png)

**Comment by battousai90** [comment]
Bonjour,
Je constate la même issue de mon coté depuis 1 semaine aussi.
Je m'explique :
Mes ampoules Ikea ne sont plus contrôlables des lors qu'elle reste inactives un certain temps d'activité.
Exemple, le soir j'était l'ampoule avec mon téléphone ou l'interrupteur Ikea avec Zigate et Abeile sans soucis depuis mon lit. Au petit matin ca marche plus, je prend la tablette, vais sur le dashboard Jeedom et plus de réponse de l'ampoule, si j'actionne l'interrupteur mécanique, le message "XXXX a rejoint le réseau" apparaît et l'ampoule fonctionne avec Jeedom.
Ca a peut être un lien avec le ticket des "XXX a rejoint le réseau" ???

**Comment by mickadam29** [comment]
On est tout à fait sur le même problème @battousai90 
Le fait de couper le courant sur l'ampoule et de le remettre réactive celle-ci pour qq heures.
Suis heureux de ne pas être le seul. Malheureusement, je n'ai pas trouvé mieux. Sauf que pour moi, je n'ai plus les interrupteurs mécaniques, donc une chaise, accès au plafonnier ...

@KiwiHC16 
Nous allons avoir besoin de tes compétences pour poser le bon diagnostic. Je suis pas certain que Abeille soit en cause mais plutôt Jeedom (que j'ai passé en 4.1.19 à priori à la même période que le début de mes souics). @battousai90  dans quelle version de Jeedom, Abeille, firware zigate es-tu ? Lorsque tes ampoules sont inopérantes, sont-elles vues en timeout ? Pour moi, parfois oui, parfois non, mais une ampoule qui n'est pas en timeout peut ne pas répondre aux ordres.

Pour info, ma télécommande HUE me permet de m'en sortir. En effet, l'envoi de la commande ON/OFF directement au groupe auquel sont rattachées les ampoules fonctionne tout le temps. Donc le problème n'est clairement pas l'ampoule. D'ailleurs mes 6 sont impactées. 

Ce que je constate aussi, j'actionne un interrupteur, l'ampoule s'allume (scénario Jeedom avec fontion Toggle sur l'ampoule). Je réappuie, l'ampoule ne réagit pas. Je dois vérifier que l'ordre arrive à Jeedom via la zigate. Mais si j'utilise la télécommande HUe ou même une télécommande virtuelle dans Abeille, cela fonctionne.

@battousai90 
Voici finalement ce que je peux te dire de faire pout t'aider. Crées-toi une télécommande virtuelle et associe l'ampoule et la télécommande ainsi que la ruche dans le même groupe. Lorsque tu auras le problème, tente cette télécommande. Chez moi, elle fonctionne en dépannage des interrupteurs.

Pour moi, il n'y a pas lien avec le ticket que tu mentionnes. Le message est tout à fait normal si tu coupes électriquement l'ampoule.

**Comment by battousai90** [comment]
Bonjour,
Aujourd'hui l'ampoule de mon bureau estait hors ligne, affiché en Timeout comme le montre le screen.
Logs et les information de version joint, dans les logs on verra la trace quand j'ai actionné l'interrupteur mecanique
![image](https://user-images.githubusercontent.com/47687052/107503833-b58d3d00-6b9a-11eb-9b9c-4659ffb12b96.png)
![image](https://user-images.githubusercontent.com/47687052/107502620-2f242b80-6b99-11eb-9124-047a346faf21.png)
![image](https://user-images.githubusercontent.com/47687052/107503167-eb7df180-6b99-11eb-9882-196aa70a4f5a.png)
![image](https://user-images.githubusercontent.com/47687052/107503251-03ee0c00-6b9a-11eb-9d41-c4e0433a197e.png)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/5957741/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5957742/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/5957743/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/5957749/Abeille.log)

**Comment by KiwiHC16** [comment]
Avez vous ces messages dans vos logs AbeilleParser.log
```
[2021-02-10 22:54:35][debug] Abeille1, Type=8000/Status, Status=15/Status 15 inconnu, SQN=3B, PacketType=0100
[2021-02-10 22:54:36][debug] Abeille1, Type=8000/Status, Status=15/Status 15 inconnu, SQN=3C, PacketType=0092
```

**Comment by KiwiHC16** [comment]
@battousai90 

Je vois des 
```
[2021-02-10 12:16:22][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=A65C, DestEP=01, ClustId=0001
```
ce qui est bon mais je vois aussi des
```
[2021-02-10 12:15:04][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4
[2021-02-10 12:15:10][debug] Abeille1, Type=8011/APS data ACK, Status=A7, DestAddr=6077, DestEP=01, ClustId=0000
[2021-02-10 12:16:13][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=E9 
```
Ce qui veut dire qu il y a des soucis de communications. (Status diff de 00 = soucis)

**Comment by battousai90** [comment]
@KiwiHC16 
> Ce qui veut dire qu il y a des soucis de communications. (Status diff de 00 = soucis)

Je n'ai pourtant rien changé à la maison, rien ajouté et rien enlevé et jamais eu de soucis network.
Y'a t'il un moyen de t'aider pour résoudre ca ?
Si non pas pour l'instant dis le moi car la c'est tellement l'enfer que je switch sur ma VM Home Assistant.
Merci

**Comment by mickadam29** [comment]
De mon côté je vais regarder ce soir ces logs . Des messages comme tu indiques j’en ai. Je vais aussi déplacer le PC avec la ZiGate pour vérifier la qualité du réseau. Je te tiens au courant

**Comment by mickadam29** [comment]
J'ai ça par exemple

Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=8930, SQN=61

![image](https://user-images.githubusercontent.com/36518012/107612917-96001e00-6c47-11eb-8fe4-45924b3da4aa.png)

**Comment by mickadam29** [comment]
@KiwiHC16 

Je viens d'éteindre Jeedom ainsi que forcément la zigate. J'ai utilisé la télécommande HUE. Toutes mes ampoules ont réagi aux commandes. Donc aucune anomalie sur le matériel IKEA. Le problème vient forcément de l'environnement PC, Zigate, Jeedom, Abeille. Ca, c'est démontré. 

Je déplace à l'instant mon PC du sous-sol au coeur de la  maison. Donc la zigate va être à moins de 5m de chacune des ampoules. Seuls obstacles les mur de briques. Je te tiens au courant si j'ai encore des erreur APS Data confirm fail

**Comment by mickadam29** [comment]
Le tableau LQI peut t'aider à nous orienter ?

![image](https://user-images.githubusercontent.com/36518012/107635903-31a38580-6c6c-11eb-8754-ab9da5f023e4.png)

**Comment by mickadam29** [comment]
Entre temps j'ai restauré au 25/01. Avec Jeedom en 4.1.17 et Abeille en master_tcharp38, 2021-01-14 11:33:41
Ca fonctionne pas mieux et exactement de la même façon. Je vais débrancher/rebrancher les ampoules pour voir ce que cela donne. Mais ca risque de bien fonctionner qqs heures. Et faudra bien que je restaure ma sauvegarde de ce midi

**Comment by mickadam29** [comment]
Même une vielle sauvegarde ne donne pas de bons résultats. Je vais donc migrer une ampoule vers mon réseau de dev et la pizigate pour voir comment cela se comporte. Vu mes tests, je crains que ce ne soit une mise à jour de Debian qui interfère.

**Comment by mickadam29** [comment]
@KiwiHC16 

Je te propose une connexion sur mon système via AnyDesk. Fais moi signe si ça te convient. Ici ou slack. Tu devrais y retrouver mon numéro de téléphone.

**Comment by mickadam29** [comment]
Les derniers tests tendent à montrer qu'il y a des "resend". Les commandes Toggle sont doublées. Envoi, pas de réponse, renvoi. Les ampoules font jour/nuit.

**Comment by mickadam29** [comment]
@battousai90 

De news de ton installation ? Ca se comporte toujours aussi mal ?

**Comment by battousai90** [comment]
Tous les matins quand j'arrive dans mon bureau pour le télétravail, l'ampoule est timeout, je dois actionner l'interrupteur mécanique. En fait toutes les ampoules tombent en rade pendant la nuit. Depuis 3 ans jamais eu de problème de communication, j'ai rien touché je vois pas pourquoi j'en aurai aujourd'hui.
Ce que j'ai remarquer c'est l'absence du petit logo de prise de courant dans santé, qui disait qu'un periphérique était alimenté electriquement et non par batterie.
Enfin je sais pas trop de chose on changé dans les différente update.
Ce week end je switch sur HASS.
Bonne journée.

**Comment by mickadam29** [comment]
Moi j’ai appliqué la mise à jour de @tcharp hier en fin de journée. Distribution MASTER
Aujourd’hui, je constate que ça fonctionne. Un peu tôt pour crier victoire. Mais ça fait des semaines que ça n’a pas fonctionné sans problème aussi longtemps. Je verrai durant le WE. Tu dis que les ampoules étaient vues comme des équipements sur piles ? Ça pourrait expliquer beaucoup de choses. Si tu peux patienter je te redis en fin de journée si ça continue de fonctionner chez moi. Ça fera 24H. Mais comme toi ça a fonctionné des mois sans anomalie et du jour au lendemain les ampoules IKEA et seulement ça, ça se met à mal fonctionner. Étrange.

**Comment by mickadam29** [comment]
@battousai90 

Je confirme un retour à la normale. Je n'ai pas tout testé mais déjà les ampoules restent opérationnelles depuis hier, pas besoin de les débrancher ! 24H, un luxe depuis 15j. Essaie la mise à jour du master. Si ce n'est pas ça qui a corriger, je me console d'une solution qui fonctionne. Certains retours d'état ne parviennent pas visiblement (détecteur de présence reste à 1)
@KiwiHC16 @tcharp38 
Des changements dans le code qui pourraient expliquer que ça déconnait depuis 15j et retour à la normale hier ? Avec à priori les toutes dernières modifs du master ?

**Comment by tcharp38** [comment]
Pas de livraison de cette ampleur de mon cote. Mais peut etre cote Kiwi.
J'espere en tout cas sinon pas d'explication = pb incompris :(

**Comment by mickadam29** [comment]
Une installation de la maj précédente qui se serait mal passée ? Le principal c’est que ce soit redevenu fonctionnel. 15j de galère.  Le côté étrange c’est que même une restauration n’a rien changé. Je ne vois que l’application des maj appliquées jeudi après-midi qui a rétabli le fonctionnement des ampoules. Merci à toi

**Comment by mickadam29** [comment]
Finalement de nouveau des timeout sur mes ampoules. La maj n’a pas corrigé. C’était un coup de chance que ça a fonctionné plus de 24H

**Comment by mickadam29** [comment]
@KiwiHC16 

Si tu passes par là je sollicite à nouveau ton aide au travers de prise de main à distance
Pour répondre à ta question
Avez vous ces messages dans vos logs AbeilleParser.log

[2021-02-10 22:54:35][debug] Abeille1, Type=8000/Status, Status=15/Status 15 inconnu, SQN=3B, PacketType=0100
[2021-02-10 22:54:36][debug] Abeille1, Type=8000/Status, Status=15/Status 15 inconnu, SQN=3C, PacketType=0092


Je joins des logs où j'ai bien des traces de status inconnu mais 14  lorsque j'envoie une commande vers l'ampoule (une parmi les autres qui fonctionnent mal ce matin. Hier tout était pourtant ok). Référence de l'ampoule : 
ID : 234
Logical ID C414
Get name : l'ampoule répond aux sollicitations get-name mais pas aux commandes ; TRADFRIbulbGU10WS400lm

Le log 12 correspond à la tentative de mettre à ON l'ampoule.

[AbeilleParser (11).log](https://github.com/KiwiHC16/Abeille/files/5975322/AbeilleParser.11.log)

[AbeilleParser (12).log](https://github.com/KiwiHC16/Abeille/files/5975338/AbeilleParser.12.log)

**Comment by battousai90** [comment]
Hier soir avant d'aller au lit j'ai fait une passe, dans santé tout était en vert.
Début d'après midi aujourd'hui :
![image](https://user-images.githubusercontent.com/47687052/107851625-ad880400-6e0b-11eb-816b-d79aab869757.png)
Même les prises connectées IKEA saute, a chaque fois faut sortir une aiguille et la resynchro, car débrancher rebrancher marche pas.

**Comment by mickadam29** [comment]
@battousai90 

Moi par contre aucune anomalie avec les prises IKEA. Que les ampoules. Du coup j'ai passé commande de 3 ampoules OSRAM. Je vais pas continuer avec ces ampoules si elles sont si spécifiques. Aucun autre routeur n'a cette anomalie. J'ai des Sonoff (relais), des sirènes Zigbee (évidemment), des prises IKEA, donc plusieurs sorte de routeurs et aucun ne décroche. Je suis vraiment sur une spécificité Ampoules IKEA. Pour toi par contre ça semble plus problématique. Tu vas pas tout changer. J'ai même revissé mes modules (différentiels, disjoncteurs, ... dnas les coffrets électriques). Même si ça résout rien niveau Zigbee ca fera pas de mal car certains méritait ce resserrage. J'ai fait ça car j'ai remarqué des baisses d'intensité fréquentes qui pourraient parasiter les ampoules. Ca m'étonnerait que ce soit ça. Et nous n'aurions pas le même souci. Je reviendrai communiquer le résultat des ampoules OSRAM. Mais ca n'aidera pas à résoudre. Peut-être juste à démontrer un souci avec les Tradfri. Le WE prochain je mettrai mes ampoules IKEA sur mon réseau Zigbee de dev. On verra ainsi si elle fonctionne ou pas. 2 OS différents, une Zigate USB d'un côté, une Pizigate de l'autre. Version 3.1D pour les 2. Et j mettrai les mêmes versions Abeille. Bon courage à toi @battousai90

**Comment by battousai90** [comment]
Moi je vais pas me prendre la tète longtemps, je ne fais pas de la domotique pour passé mon temps a bricoler.
Du coup je dégage ce duo infernal ZIgate Jeedom pour passe sur Conbee avec Deconz et HASS. 
M'enfin tout ca c'est une autre histoire.
Bon courage a Abeille et encore merci a Kiwi pour son boulot.

**Comment by KiwiHC16** [comment]
@battousai90, bonne chance....

**Comment by KiwiHC16** [comment]
AbeilleParser12:
```
[2021-02-13 09:25:08][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=C414, SQN=B7
[2021-02-13 09:25:08][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=2E, PacketType=0092
[2021-02-13 09:25:08][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=C414, SQN=B8
```

Il faut résoudre les soucis de radio zigbee. Mais pour cela le mieux est de sniffer la radio pour comprendre ce qu'il se passe. Sinon essayer de comprendre avec les LQI dans Abeille et voir si la nouvelle page 
![Capture d’écran 2021-02-14 à 23 04 10](https://user-images.githubusercontent.com/8549674/107890362-f679ae80-6f18-11eb-9ed3-187dad274deb.png)
donne des infos. Mais je n ai pas encore beaucoup testé.

**Comment by mickadam29** [comment]
@KiwiHC16 

Je vais essayer de trouver le temps nécessaire. J'ai commandé des ampoules OSRAM pour comparer le fonctionnement. Les soucis radio j'ai dû mal à y croire. Sur un plafonnier, entre autres, c'est toujours les mêmes qui fonctionnent mal. Vu leur position, comment expliquer des problèmes radios ? Ce matin une répond, pas les 2 autres. Et comme dit précédemment, pourquoi seules les ampoules IKEA sont impactées et pas les autres équipements de type "routeur" ?
Si cela fonctionne bien avec les OSRAM, je pourrais faire plus de tests avec les ampoules qui du coup seront inutilisées et te transmettre les infos. 

![plafonnier](https://user-images.githubusercontent.com/36518012/107915833-86454a00-6f65-11eb-9fd3-cda4a976dfa0.jpg)

En complément, la télécommande virtuelle fonctionne très bien. Elle pilote également sans soucis TOUTES les ampoules et prises, y compris celles du plafonnier. Donc le problème radio semble écarté pour le moment (je reconnais que les logs laisse penser le contraire). Pour le coup, c'est bien la Zigate qui envoie l'ordre, et donc les ampoules sont à portée de celle-ci.

En revanche, les scénarios qui pilotent les ampoules de façon individuelles ne fonctionnent pas. Donc ça rejoindrait le message qui semble indiquer **un problème Unicast** mais qui **n'existe pas en Broadcast**.

![image](https://user-images.githubusercontent.com/36518012/107918292-b1319d00-6f69-11eb-82ca-403528924959.png)

L'ampoule Abeille-232 qui était en timout, ne l'est plus après un refresh_lqi. Mais pour autant n'est pas pilotable.

Voici l'état des 3 ampoules du plafonnier après le refresh

![image](https://user-images.githubusercontent.com/36518012/107919156-25b90b80-6f6b-11eb-9070-f265633020ae.png)

Si j'envoie la commande ON à chacune, individuellement, une seule réagit, tjs la même depuis ce matin. Les 2 autres ne réagissent qu'aux télécommandes (physique et virtuelle). L'envoi au groupe fonctionne systématiquement

**Comment by KiwiHC16** [comment]
Dans le log AbeilleParser vois tu les messages:
```
[2021-02-16 00:00:40][debug] Abeille5, Type=8011/APS data ACK, Status=00, DestAddr=129C, DestEP=01, ClustId=0006
```
pour toutes les ampoules ?

**Comment by mickadam29** [comment]
@KiwiHC16 

J'en ai pour 4 de mes ampoules. 2 ne sont pas présentes dans le log car absente du réseau depuis 24H. J'ai cessé de monter sur un chaise pour les débrancher. Par contre j'ai aussi le cas où une ampoule est en timeout depuis hier soir mais présente dans le log.
Il s'agit de la BDBB.

![image](https://user-images.githubusercontent.com/36518012/108029645-1b137a80-702e-11eb-903d-8e3c3fd87878.png)

Une de celles non présentes

![image](https://user-images.githubusercontent.com/36518012/108029727-426a4780-702e-11eb-8d78-7334c965f761.png)

**Comment by KiwiHC16** [comment]
Si Status different de 00 c est qu il y a un soucis. BDBB est en status A7.

Peux tu partager la table: Table des liens
(Capture d ecran)

Peux tu preciser quelles sont les 4 ampoules (Adresses courtes).

**Comment by mickadam29** [comment]
Voici (il y en a bien 6)
Les getname fonctionnent

Les adresses sont : 8930 / B245 / 7316 / C414 / BDBB / 0BB2
Respectivement : TRADFRIbulbE27WSopal980lm / TRADFRIbulbGU10WS400lm x3 / TRADFRIbulbE27opal1000lm / TRADFRIbulbE27opal1000lm


![image](https://user-images.githubusercontent.com/36518012/108147261-d7248200-70ce-11eb-9dd1-1076c86f4a77.png)
![image](https://user-images.githubusercontent.com/36518012/108147327-ec99ac00-70ce-11eb-9e73-afe7f7e02e60.png)
![image](https://user-images.githubusercontent.com/36518012/108147355-fc18f500-70ce-11eb-8784-46d772e53c8b.png)

**Comment by KiwiHC16** [comment]
8930: n'a pas envoyée ses infos. Je suppose qu'elle a ete interrogée mais ne peut être sure.
-- est vue par: 
---- 4D18 / 1ER (2 etages diff et LQI 255) : tres bizarre surtout pour Ikea.
----  30B1 / Sam: LQI 104 avec sibling: Ok. 30B1 voit Zigate a 180 donc doit fonctionner.
---- ....
---- > Sur cette base 8930 doit fonctionner mais pourquoi n'a t elle pas repondu  aux requetes LQI.

BDBB: n'a pas envoyée ses infos. Je suppose qu'elle a ete interrogée mais ne peut être sure.
-- est vue par: 
---- 4D18 / 1ER (2 etages diff et LQI 255) : tres bizarre surtout pour Ikea.
---- ...
---- > Idem que pour la precedente.

Zigate: 
-- ne voit pas 8930
-- ne voit pas BDBB

Ce qui voudrait dire que la zigate ne peut dialoguer avec 8930 et BDBB sans que le reseau fasse du routage.
Je vois beaucoup de Unknown dans la colonne relation. C est signe de routeur Hue qui ne repondent pas correctement aux questions. Aurais tu des routeurs Hue ou Osram ?

**Comment by mickadam29** [comment]
Je vais vérifier pour 4D18. Je n’ai pas d’ampoules IKEA au 1Er. Le seul routeur est une sirène Evology. Lqi à 255 c’est très étrange car la ZiGate est au sous-sol

**Comment by mickadam29** [comment]
@KiwiHC16 

Pas de routeur HUE ni OSRAM. (Par contre je vais remplacer mes IKEA par des OSRAM)
Eventuellement, le routeur implémenté dans le E18 (DIY) que je veux supprimer. Mais qui est éteint depuis pas mal de temps. 

4D18 est bien la sirène Evology qui fait routeur.
8930 ne réagit pas aux commandes.
C'est une ampoule au RDC qui passerait par le 1ER pour joindre Zigate au sous-sol. 

Par contre, si je débranche l'ampoule elle va tout de suite se mettre à fonctionner.

Quand je vois ce graphique, je me dis que les ampoules sont hors réseau. Tous les endpoints sont sur la zigate. Sauf Abeille-360 qui est la 8930. Et avec les dalles béton, beaucoup de timeout. Aucun routeur ne fait office de routeur

![image](https://user-images.githubusercontent.com/36518012/108195789-8fc2e380-7118-11eb-827e-2404a1a5979d.png)

**Comment by mickadam29** [comment]
Je viens de changer mes ampoules IKEA par des OSRAM (changement plafonnier GU10 vers E27). Donc c'était l'occasion.
Je reviendrai indiquer si le réseau fonctionne mieux et surtout si mes ampoules ne se font pas la malle.

**Comment by KiwiHC16** [comment]
Perso j'ai viré mes prises OSRAM car elle n'utilisent pas les même messages pour assurer le routage et donc le routage ne fonctionnait pas. Je ne sais pas si depuis ils ont changé le soft pour le routage. Mais perso ma recommendation est soit tu es tout OSRAM soit sans OSRAM.

**Comment by KiwiHC16** [comment]
Ton retour d experience sera interessant. A suivre...

**Comment by mickadam29** [comment]
Pour le moment ça marche nickel. Mais c'est tout frais. Qqs heures. Les Ikea m'ont fait le coup aussi. En démontant un des plafonniers, je suis tombé sur du jeu dans le serrage de la douille. Donc si ça marche, subsistera un doute. Après, mes IKEA finiront sur le Zigbee DIY de dev si j'en ai à nouveau besoin. Mais je te tiens au courant. dans les jours qui viennent. Tu souhaites fermer le ticket ou je m'en charge d'ici qqs jours ?

Si je me fie au graph, des endpoints passent par les OSRAM

![image](https://user-images.githubusercontent.com/36518012/108235627-49847900-7146-11eb-956d-86290366be3b.png)

**Comment by KiwiHC16** [comment]
Cet issue deveint tres tres longue. Je prefererai qu on clos et qu on reparte sur des bases vierges. (eventuellement en faisant un lien vers ce ticket).

**Comment by mickadam29** [comment]
OK. D'autant que le périmètre a peut-être changé. Mais comme @battousai90 semblait avoir le même problème je voulais voir avec toi.
