### ISSUE TITLE
Aqara Double Switch w/o neutral  switch.b2lacn02

### ISSUE THREAD

**Issue by Eidern** [KiwiHC16/Abeille#1729]
Hello,

je viens d'installer le  double switch mural aqara sans fil neutre.
J'ai copié la config json du switch.b2nacn02, mais il ne fonctionne que pour un interrupteur (le Toggle1, le Toggle tout court ne renvoie rien).
Comment faire pour connaitre quels commande rajouter via les logs?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Mettre le plugin en debug. Redémarrer le daemon.
Faire les commandes cachées sur la ruche:
- ActiveEndPoint
- SimpleDescriptorRequest
Et partager le log AbeilleParser.log.

**Comment by Eidern** [comment]
Ok merci,
 mais je n'ai pas l'impression que mes commandes de ruches soient bien exécutées;
Quand je les execute deja je n'ai aucune confirmation visuelle donc je ne sais pas si c'est normal ou pas, et le log m'a l'air bien court.
J'ai rentré l'@ courte pour le activendPoint, quand au SimpleDescriptorRequest, je rentre aussi l'@ courte, puis le seul endPoint que je vois dans le log me semble être 01 alors je rentre [endPoint(01)] dans le champ texte.. est ce correct?
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5942025/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
"je n'ai aucune confirmation visuelle" -> normal.
"01 alors je rentre [endPoint(01)]" -> il faut juste mettre "01" rien de plus.
Je regarde la log.
Je ne vois pas les informations espérées. Pourrais tu le refaire et aussi partager l adresse courte pour me faciliter la recherche dans le log.

**Comment by Eidern** [comment]
Merci pour tout.alors voila le nouveau log, l'@ courte du double switch est 9DB8
[AbeilleParser-2.log](https://github.com/KiwiHC16/Abeille/files/5946935/AbeilleParser-2.log)

**Comment by KiwiHC16** [comment]
```
[2021-02-08 22:25:50][debug] Abeille1, Type=8043/Simple descriptor response, SQN=94, Status=00, Addr=9DB8, Length=1A, EP=01, Profile=0104/ZigBee Home Automation (ZHA), DevId=0006/Remote Control, BitField=02, [Modelisation]
[2021-02-08 22:25:50][debug]   [Modelisation] InClusterCount=06
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=0000 - General: Basic
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=0003 - General: Identify
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=0001 - General: Power Config
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=0002 - General: Temperature Config
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=0019 - General: OTA
[2021-02-08 22:25:50][debug]   [Modelisation] InCluster=000A - General: Time
[2021-02-08 22:25:50][debug]   [Modelisation] OutClusterCount=03
[2021-02-08 22:25:50][debug]   [Modelisation] OutCluster=0000 - General: Basic
[2021-02-08 22:25:50][debug]   [Modelisation] OutCluster=000A - General: Time
[2021-02-08 22:25:50][debug]   [Modelisation] OutCluster=0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
```
[2021-02-08 22:25:32][debug]   ManufacturerName='LUMI', trimmed='LUMI', {"Abeille1\/9DB8":{"time":1612819532,"ManufacturerName":"LUMI"}}, [Modelisation]
```

**Comment by Eidern** [comment]
Alors je suis désolé, mais cherche dans la documentation, mais je ne vois pas comment se servir de ces informations :(

Je regardais sur votre doc pour avoir plus de renseignements sur comment demeler tout ca, et je vois que pour avoir le endpoint on le trouve a l'aide du" EndPoint List" dans le log, mais en re interrogant avec le activeEndPoint, je ne vois pas dans le parser de "EndPoint List"..

Rien ne m'a l'air de coller, C'est tres bizarre d'avoir un "temperature config" pour un switch mural .. 

Bref si vous avez un petit lien d'ou je pourrai commencer a faire des recherches, ce n'est pas de refus :)

**Comment by mickadam29** [comment]
@Eidern 

Les interrupteurs Xiaomi comme le tien "envoient" des infos Temp & Humidité. Effectivement cela n'a rien à faire là. Je n'ai pas encore démonté le mien pour vérifier s'il y a une quelconque sonde à l'intérieur. Par contre, je suis presque certain que tu as parmi tes équipements Zigbee des capteurs de température Xiaomi ?  Je me trompe ? Et que si tu vérifies les logs, tu verras que ce n'est pas l'interrupteur qui envoie la température, mais ce capteur de temp qui se fait passer pour être ton interrupteur. Mais c'est un autre sujet. Je regarde dans mes logs pour te montrer où chercher et confirmer ce que je viens de te dire

**Comment by mickadam29** [comment]
@Eidern 

Si tu regardes dans ton log Abeille, tu verras sans doute des choses comme ici. Les messages ignorés sont des envois de température à 20.48° soi-disant provenant de 4 de mes interrupteurs du même type que toi. Lorsque j'avais cherché, j'avais bien un de mes capteurs de temp Xiaomi qui envoyait à ce moment là 20.48°. Depuis, la température a certainement changé, mais Abeille reçoit toujours ces trames. Et même s'il existait un capteur de temp impossible qu'il faisait la même température dans les 4 pièces où sont mes interrupteurs. J'avais créé un issue là-dessus #1591. 

![image](https://user-images.githubusercontent.com/36518012/107858100-ade7c580-6e32-11eb-9289-f444f34f5db6.png)

**Comment by Eidern** [comment]
Hello, 
Bien vu, effectivement mon seul autre équipement xiaomi est une sonde de temperature/ humidité.
Ceci explique cela

**Comment by KiwiHC16** [comment]
Ce qu'il manque c est le nom zigbee de cet inter.

Peux tu mettre la derniere version stable d'abeille, refaire une inclusion et partager AbeilleParser.
Désolé de redemander des logs.

**Comment by mickadam29** [comment]
@kiwihc16

Je me permets, si tu dois intervenir sur le modèle de te remonter l’info que dans les dernières versions, peut être de longue date, l’état du bouton ne change plus. Je vais ouvrir un nouveau ticket

**Comment by Eidern** [comment]
Pardon je mets du temps, ces temps ci avec les vaccinations je sais plus ou donner de la tete..

@KiwiHC16 alors est ce qu'il y a une nouvelle version stable? je suis passé en version beta, car la stable d'il y a une semaine m'a fait le probleme ou je ne pouvais plus renommer les anciens dispositifs ni creer de nouveaux dispositifs zigbee, et en passant a la beta ce probleme etait résolu

**Comment by Eidern** [comment]
Bon de toutes facons, apres reflexion, on s'en fout si la version stable ne marche pas bien chez moi pour l'instant, vu que de toutes facons je ne peux pas utiliser l'interrupteur ;)
Voilà le nouveau log avec version stable:
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6008782/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-03-09 à 20 42 37](https://user-images.githubusercontent.com/8549674/110528057-fd5ea000-8117-11eb-997c-e57e3947d8d3.png)

Peux tu afficher la commande simpleDescripteurRequest dans la ruche et envoyer la commande comme ci dessus en remplacant le 01 par 01; 02; 03; 04; 05; 06; 08 et partager le log AbeilleParser ?

**Comment by Eidern** [comment]
Alors voilà, a savoir que entre temps comme une nouvelle version d'abeille etait sortie, j'ai effacé, et reinstallé l'equippement  :)
Du coup son adresse n'est plus 9DB8, mais 9B23 maintenant (ce que j'ai mis evidemment pour le SimpleDescriptorRequest), j'ai redemarré le demon et fait la manip voilà le log:
[AbeilleParser-3.log](https://github.com/KiwiHC16/Abeille/files/6111071/AbeilleParser-3.log)

**Comment by tcharp38** [comment]
Salut @Eidern 
Si tu es toujours interessé tu veux essayer d'avancer avec moi ?
Si oui, peux tu ouvrir l'assistant de decouverte Zigbee (click equipement puis avancé)
Et essaie de faire en sorte que toutes les lignes soient remplies via le bouton refresh respectif.
La beta du moment est la + avancée.
Merci

**Comment by Eidern** [comment]
Hello @tcharp38 
Pour le moment je ne pourrai pas aider, je suis en plein déménagement et l'Aquara Double Switch n'est pour le moment branché a rien.
Des que je le remets en route, je reviens dans le coin

**Comment by tcharp38** [comment]
Pas de soucis. On garde le sujet ouvert.
Fais signe quand tu veux reprendre.

**Comment by tcharp38** [comment]
Salut @Eidern 
Toujours interessé par ce sujet ?

**Comment by Eidern** [comment]
hello, je n'ai malheureusement plus le temps de potasser le sujet, par contre si ca peut aider la communauté, je peux vous l'envoyer a domicile cadeau

**Comment by tcharp38** [comment]
Salut @Eidern 
Si vraiment tu ne t'en sers pas ou ne comptes pas t'en servir, je peux le récupérer. 
Ca me servira de test si j'ai besoin de faire du support.
Envoie moi un email à tcharp38@laposte.net et je te filerai mon adresse.

**Comment by Eidern** [comment]
Ok, c'est fait,
regarde les spams au cas ou..

**Comment by tcharp38** [comment]
Antique sujet sans vie.
Je ferme mais à réouvrir si besoin.
