### ISSUE TITLE
Ajouter un nouveau modele amarra

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1730]
https://community.jeedom.com/t/aqara-d1-1-bouton-et-commande-detat/52494/2

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by tcharp38** [comment]
Antique sujet sans infos.
A reouvrir si du nouveau.
