### ISSUE TITLE
Ajout interrupteur double ou simple LIVOLO

### ISSUE THREAD

**Issue by pphil78** [KiwiHC16/Abeille#1731]
version jeedom 4.1.19 et derniere version beta du plugin ABEILLE
L'ajout d'un nouvel interrupteur LIVOLO n'a plus l'air de fonctionner. La découverte de l'équipement se fait bien (ajout de l'équipement) par contre "l'appairage" non car la communication stoppe au bout de qques instants.
Par ailleurs, pour mon interrupteur double, je n'ai qu'une seule info Etat, c'est normal?

**Comment by KiwiHC16** [comment]
Peux tu essayer avec la version stable de ce soir ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by pphil78** [comment]
OK je fais le test aujourd'hui.

**Comment by pphil78** [comment]
J'ai fait le test avec la version stable et la version beta. Avec la version beta, j'arrive à commander un des 2 inter et avec le second rien à faire.  Par contre avec la version stable aucun des 2 inter ne fonctionne.
Je referai des tests ce WE en ajoutant un sniffer. Mes inter sont en place, j'ai peut-être des pb de portée ou alors j'ai un inter HS.

**Comment by KiwiHC16** [comment]
Ces inter sont pas faciles. La portée semble un point faible d après mes souvenirs. Il y a aussi une astuce pour les garder dans le réseau. Pas simple.

**Comment by pphil78** [comment]
C'est clair.  En tout cas merci et bravo pour la qualité du travail que vous réalisez. Je vous tiens au courant.
