### ISSUE TITLE
Jeedom 4.1 et Sauvegarde sur un objet

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#1732]
Bonjour,

j'ai un souci lors de modification sur un objet, si j'enregistre abeille me dit :

![image](https://user-images.githubusercontent.com/46579815/107260603-924d7b00-6a3e-11eb-916c-ddd9e073e9f4.png)

et de ce fait aucune modification est faite

Version Abeille :stable, 2021-02-01

**Comment by KiwiHC16** [comment]
Doit être corrigé dans la stable de ce soir, peux tu confirmer ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by bouboun59** [comment]
Ok c'est bon merci c'est reactif ;)

**Comment by KiwiHC16** [comment]
Nickel je clos.
