### ISSUE TITLE
Lidl Ruban lumineux TS0505A

### ISSUE THREAD

**Issue by ste69008** [KiwiHC16/Abeille#1734]
Bonjour,
J'ai acheté un ruban à LED Lidl il y a quelques jours. Aucun problème pour l'appairer avec ma Zigate Wifi cependant, il est reconnu comme modèle inconnu.

Le produit est un Tuya génériques et se présente avec l'ID TS0505A (qui est le même qu'une des ampoules d'après ce que j'ai compris).
Test ici : [https://www.maison-et-domotique.com/127360-lidl-smart-home-test-hue-jeedom-eedomus/](https://www.maison-et-domotique.com/127360-lidl-smart-home-test-hue-jeedom-eedomus/)

Je peux faire quelques tests pour aider à l'intégration via Abeille si besoin

Steph

**Comment by ste69008** [comment]
Comme demandé sur le forum pour un autre équipement [https://community.jeedom.com/t/prise-connectee-silvercrest/52441/2](https://community.jeedom.com/t/prise-connectee-silvercrest/52441/2), voici mon log AbeilleParser.log avec l'inclusion du ruban :
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5950025/AbeilleParser.log)

**Comment by kaleofr** [comment]
Perso j'ai repris un json et ca marche pas trop mal.
Il y a peut être d'autres fonctions ou certaines qui ne marchent pas mais c'est très fonctionnel:

TS0505A\TS0505A.json:

```
{
  "TS0505A": {
    "nameJeedom": "Silvercrest Ruban a LED",
    "timeout": "60",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "uniqId": "6547c886378a7",
      "icone": "FlexRGBW",
      "mainEP": "03",
      "poll": "1"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etatLight",
      "include5": "levelLight",
      "include6 2": "colorX",
      "include7 2": "colorY",
      "include6": "On",
      "include7": "Off",
      "include8": "Toggle",
      "include11 2": "setLevel",
      "include12 2": "Colour",
      "include13 2": "Blanc",
      "include14 2": "Bleu",
      "include15 2": "Rouge",
      "include16 2": "Vert",
      "include17 2": "getColorX",
      "include18 2": "getColorY",
      "include11": "getEtat",
      "include12": "getLevel",
      "include13": "getManufacturerName",
      "include14": "getModelIdentifier",
      "include15": "getSWBuild",
      "include16": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel",
      "include12 2 2": "ColourRGB",
      "include30": "setColourRGB",
      "include30 2": "setRGB",
      "include31": "colorRouge",
      "include32": "setRouge",
      "include33": "colorVert",
      "include34": "setVert",
      "include35": "colorBleu",
      "include36": "setBleu",
      "include37": "1700K",
      "include38": "2700K",
      "include39": "5000K",
      "include40": "temperatureLight",
      "include40 2 2": "setTemperatureLight_1700_4900"
    }
  }
}
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
```
[2021-02-09 18:19:32][debug] Type=8043/Simple Descriptor Response: Dest=Abeille1, SQN=61, Status=00, ShortAddr=a7f6, Length=1c, EndPoint=01, Profile=0104 (ZigBee Home Automation (ZHA)), DeviceId=010D (), BitField=01
[2021-02-09 18:19:32][debug]   InClusterCount=08
[2021-02-09 18:19:32][debug]   InCluster=0000 - General: Basic
[2021-02-09 18:19:32][debug]   InCluster=0003 - General: Identify
[2021-02-09 18:19:32][debug]   InCluster=0004 - General: Groups
[2021-02-09 18:19:32][debug]   InCluster=0005 - General: Scenes
[2021-02-09 18:19:32][debug]   InCluster=0006 - General: On/Off
[2021-02-09 18:19:32][debug]   InCluster=0008 - General: Level Control
[2021-02-09 18:19:32][debug]   InCluster=0300 - Lighting: Color Control
[2021-02-09 18:19:32][debug]   InCluster=1000 - ZLL: Commissioning
[2021-02-09 18:19:32][debug]   OutClusterCount=02
[2021-02-09 18:19:32][debug]   OutCluster=0019 - General: OTA
[2021-02-09 18:19:32][debug]   OutCluster=000A - General: Time
```

**Comment by KiwiHC16** [comment]
```
[2021-02-09 18:19:26][debug] Type=004d/Device announce: Dest=Abeille1, SrcAddr=a7f6, IEEE=588e81fffed5e2f4, MACCapa=8e, Rejoin=48
```

**Comment by KiwiHC16** [comment]
```
[2021-02-09 18:19:27][debug] Type=8045/Active Endpoints Response: Dest=Abeille1, SQN=5e, Status=00, ShortAddr=a7f6, EndPointCount=02, EndPointList=; 01; f2
```

**Comment by KiwiHC16** [comment]
Sur ces infos, le modele semble être une bonne base.

Pouvez vous confirmer que le modele est bon et si oui je l ajoute à Abeille.

Pouvez vous partager une image de ce produit ?

**Comment by kaleofr** [comment]
Bonjour, qu'entends tu par modèle? 
Le json proposé marche très bien avec les nouveaux rubans lumineux lidl TS0505A.
Comme dit précédement, j'ai repris d'autres json pour le créer mais je ne sais pas si on peut ajouter d'autres commandes de groupes par exemple.
De même, je n'utilise pas toutes les commandes.
Enfin, j'ai oublié d'ajouter ci dessus une template pour setTemperatureLight_1700_4900, très classique:
 setTemperatureLight_1700_4900.json
`{
  "setTemperatureLight_1700_4900": {
    "isVisible": 1,
    "name": "setTemperatureLight_1700_4900",
    "order": 14,
    "isHistorized": "0",
    "Type": "action",
    "subType": "slider",
    "generic_type": "LIGHT_SET_COLOR_TEMP",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07c7662540505A",
      "topic": "setTemperature",
      "request": "EP=#EP#&slider=#slider#",
      "minValue": "1700",
      "maxValue": "4900",
      "visibilityCategory": "All"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}`
C'est a cette plage de commande de température que répond le ruban.

Kaléo

**Comment by ste69008** [comment]
Bonjour,
Merci pour vos réponses rapides à tous les deux.
Après la création des fichiers  après Template\setTemperatureLight_1700_4900.json et TS0505A\TS0505A.json j'arrive bien à contrôler le ruban. 
Cependant, j'ai le message d'erreur suivant :
 `getJSonConfigFilebyDevices: filename is not a file: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/Template/1700K.json`
=> Pouvez-vous svp ajouter le fichier 1700K.json ?

Je souhaiterai pouvoir choisir la couleur via le widget intégré à Jeedom. Existe-t-il une commande déjà prête pour cela ?

Enfin, pour l'image, je propose d'utiliser celle-ci : [https://www.lidl-shop.be/media/790130f690d8147c3c76c176f6949e40.jpeg](https://www.lidl-shop.be/media/790130f690d8147c3c76c176f6949e40.jpeg)

Steph

**Comment by KiwiHC16** [comment]
modele = json

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-10 à 19 17 34](https://user-images.githubusercontent.com/8549674/107553118-a6c37c00-6bd4-11eb-96bd-6e46e67919d8.png)

**Comment by KiwiHC16** [comment]
Ok je vais mettre le modele et l image dans Abeille des que possible.

**Comment by kaleofr** [comment]
> Bonjour,
> Merci pour vos réponses rapides à tous les deux.
> Après la création des fichiers après Template\setTemperatureLight_1700_4900.json et TS0505A\TS0505A.json j'arrive bien à contrôler le ruban.
> Cependant, j'ai le message d'erreur suivant :
> `getJSonConfigFilebyDevices: filename is not a file: /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/Template/1700K.json`
> => Pouvez-vous svp ajouter le fichier 1700K.json ?
> 
> Je souhaiterai pouvoir choisir la couleur via le widget intégré à Jeedom. Existe-t-il une commande déjà prête pour cela ?
> 
> Enfin, pour l'image, je propose d'utiliser celle-ci : https://www.lidl-shop.be/media/790130f690d8147c3c76c176f6949e40.jpeg
> 
> Steph

Oui effectivement, voici 1700K.json:
`{
  "1700K": {
    "isVisible": 1,
    "name": "1700K",
    "order": 11,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07c76621501",
      "topic": "setTemperature",
      "request": "EP=#EP#&slider=1700",
      "visibilityCategory": "All"
    }
  }
}`

Pour le coup, je trouve domage de devoir passer par des templates pour ca, n'y aurait-il pas une amélioration à prévoir de ce coté la?

Pour la couleur: 
- SetTemperatureLight_1700_4900 commande la température du blanc (réalisé grace à des couples de diodes blanches fortes puissances froides/4900K et chaudes/1700K environ)
- setRGB commande de type Action/couleur permet de choisir précisement la couleur en mode RGB (utilisant des diodes RGB donc)

Je pense que c'est setRGB que tu dois afficher pour répondre à ton besoin.

Kaléo.

**Comment by KiwiHC16** [comment]
Je viens de mettre le modele proposé par @kaleofr  dans Abeille (Sera dispo en beta mardi et en stable mardi en 8).

**Comment by tcharp38** [comment]
Salut @ste69008 
Que est le status de ce modèle ? Tout fonctionne comme tu le souhaites ?
Merci

**Comment by tcharp38** [comment]
Sujet silencieux.
Je clos. A reouvrir si besoin
