### ISSUE TITLE
Test présence WiringPi alors qu'aucune PiZigate n'est présente

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1735]
@KiwiHC16 @tcharp38 

Pouvez-vous m'expliquer comment me débarrasser de ce dysfonctionnement ?
Je n'ai pas de pizigate sur cet environnement. PC sous Debian
Aujourd'hui, je constate des messages qui tentent de découvrir et configurer une pizigate. J'ignore depuis quand. Je vais tenter d'explorer une sauvegarde.

![image](https://user-images.githubusercontent.com/36518012/107399779-6d6e0c00-6b01-11eb-8f77-a1a443f4a723.png)

A priori je n'avais pas ça avant de débrancher ma Zigate. 
Je l'ai débranchée pour vérifier si cela pouvait m'aider à résoudre mes problèmes avec mes ampoules IKEA

Merci à vous

**Comment by mickadam29** [comment]
Pas vu que cela datait du 5/02

**Comment by mickadam29** [comment]
Je rouvre car finalement le message s'est reproduit hier. Pourquoi tenter la config PIZIGATE sur un système qui en est dépourvu ?
Et cette anomalie n'impacte-t-elle pas la Zigate USB, qui elle est bien sur TTY/USB1 ?

**Comment by tcharp38** [comment]
Salut
J'ai ce truc tout le temps en ce qui me concerne. Il y a qqch lié à la gestion des processus qui merde mais pas eu le temps de creuser. J'avoue que c'est assez désagreable.

En dehors du message tu as un reel probleme ou pas ?

D'ailleurs je ne pige pas le sujet "tentative de l'activer". Ca veut dire quoi ? Tu ne fais pas juste un "tester" ?

**Comment by mickadam29** [comment]
Ben disons que je cherche à comprendre pourquoi j’ai des problèmes avec mes ampoules IKEA. Maintenant si ça perturbe le port de la ZiGate ça explique peut-être mes problèmes.

**Comment by tcharp38** [comment]
Il y a un point a creuser qui n'est pas normal "commande gpio manquante".
Tu as une pizigate je suppose.
Donc cette erreur me trouble

Non, je vois port ttyUSB1 donc c'est pas une PiZigate mais une Zigate USB n'est ce pas ?
Bref il y a un check WiringPi alors que tu t'en fiches. C'est à améliorer ca.

En ligne ?

**Comment by mickadam29** [comment]
Pas de pizigate sur cette machine
Sur un raspberry oui

Celle qui génère le message est un pc sous debian

**Comment by tcharp38** [comment]
Ok. Tu as ce message dans ta page de config, et j'imagine quand tu developpes la partie PiZigate qui fait ca automatiquement.
C est ca ?

**Comment by mickadam29** [comment]
Possible que ce soit ça, je teste. Car quand je regarde il y a le port de renseigné.
C'est dans la page configuration et les log AbeilleConfig.
Tu as raison, c'est écrit dans le log lorsqu'on regarde dans la page configuration

**Comment by tcharp38** [comment]
Ok je vais revoir cette partie. J etais en train de toute façon.
Je change le titre.

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/107564443-b5b12b00-6be2-11eb-9e31-83c89e6f3ca2.png)

alors que c'est une zigate USB

![image](https://user-images.githubusercontent.com/36518012/107564536-d6798080-6be2-11eb-98ce-fbdbf211daac.png)

**Comment by tcharp38** [comment]
Oui mais en meme temps pourquoi ouvrir la partie "pizigate" alors que tu n'en as pas :)
C est ca qui lance le check.
Mais bon je reconnais qu'on peut mieux faire.
Je compte virer ces 2 sections d'ailleurs. Elles sont troublantes pour pas mal d'utilisateurs.

**Comment by mickadam29** [comment]
Par curiosité 😉
J’ai installé une pizigate sur un raspberry sur une autre installation Jeedom.
Un environnement de prod sans pizigate, celui dont on parle
L’environnement de dev. RPI3+ avec pizigate

**Comment by tcharp38** [comment]
Devrait etre amélioré avec #1775

**Comment by tcharp38** [comment]
Modifs dans le master. Je clos. A reouvrir si besoin.
