### ISSUE TITLE
Prise connectée SilverCrest: TS011F

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1736]

**Comment by KiwiHC16** [comment]
la prise connectée de chez Lidl

**Comment by KiwiHC16** [comment]
```
[2021-02-09 15:45:04][debug] Abeille1, Type=8043/Simple descriptor response, SQN=1B, Status=00, Addr=3FCA, Length=16, EP=0B, Profile=0104/ZigBee Home Automation (ZHA), DevId=010A/Legrand xxxx, BitField=01, [Modelisation]
[2021-02-09 15:45:04][debug]   [Modelisation] InClusterCount=05
[2021-02-09 15:45:04][debug]   [Modelisation] InCluster=0000 - General: Basic
[2021-02-09 15:45:04][debug]   [Modelisation] InCluster=0003 - General: Identify
[2021-02-09 15:45:04][debug]   [Modelisation] InCluster=0004 - General: Groups
[2021-02-09 15:45:04][debug]   [Modelisation] InCluster=0005 - General: Scenes
[2021-02-09 15:45:04][debug]   [Modelisation] InCluster=0006 - General: On/Off
[2021-02-09 15:45:04][debug]   [Modelisation] OutClusterCount=02
[2021-02-09 15:45:04][debug]   [Modelisation] OutCluster=0019 - General: OTA
[2021-02-09 15:45:04][debug]   [Modelisation] OutCluster=000A - General: Time
```

EP=0B

"parm1":"MACCapa","parm2":"MACCapa","parm3":"8E"

**Comment by KiwiHC16** [comment]
On a ce qu il faut pour faire un premier modele.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by GaelM01** [comment]
Bonjour,
Je trouve un problème sur mes prises Silver Crest le retour d'état ne se fait pas.
De plus depuis la mise à jour de mardi 9/03/2021 ou le 10 je sais plus, mes scénario n'active plus ces même prises. Je ne vois pas comment l'expliquer.
J'en ai supprimé une pour la ré-inclure, elle n'est toujours pas reconnu comme une prise mais comme TS0121 je crois un module on/off à encastrer. Elle n'a toujours pas le retour d'état actif.
Voilà le AbeilleParser de ce matin :
[AbeilleParser(4).log](https://github.com/KiwiHC16/Abeille/files/6120601/AbeilleParser.4.log)

Merci pour ton travail.

**Comment by sbx59** [comment]
Bonjour @KiwiHC16 a tu besoin de quelque chose d'autre pour implémenté dans le plugin ? J'ai aussi cette prise, mais Abeille trouve : Nouvel équipement 'TS011F__TZ3000_wamqdr3f' inconnu. Utilisation de la config par défaut. [Modelisation]

**Comment by sbx59** [comment]
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6140414/AbeilleParser.log)

**Comment by sbx59** [comment]
![Lidl_HG06337-FR-removebg-preview](https://user-images.githubusercontent.com/78600632/111137131-bb51b600-857e-11eb-9080-faea6d1db246.png)

**Comment by sbx59** [comment]
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6141385/Abeille.log)

**Comment by sbx59** [comment]
j'ai essayé de crée un modele mais cela n'a pas fonctionné.
![image](https://user-images.githubusercontent.com/78600632/111159884-db42a300-8599-11eb-8ebf-855e523d2e84.png)

Ma prise est reconnu surement comme multiprise ...
![image](https://user-images.githubusercontent.com/78600632/111159945-ea295580-8599-11eb-8c26-4e50ec3abd42.png)

Je laisse les pro de la bidouille ... je n'y comprend plus rien ( si je crée un dossier et fichier Legrandxxxx j'ai une erreur aussi ... )
![image](https://user-images.githubusercontent.com/78600632/111162248-468d7480-859c-11eb-9ade-88fbedcb7809.png)

**Comment by sbx59** [comment]
J'ai trouver cela sur internet :

            {modelID: 'TS011F', manufacturerName: '_TZ3000_kdi2o9m6'}, // EU
            {modelID: 'TS011F', manufacturerName: '_TZ3000_plyvnuf5'}, // CH
            {modelID: 'TS011F', manufacturerName: '_TZ3000_wamqdr3f'}, // FR
            {modelID: 'TS011F', manufacturerName: '_TZ3000_00mk2xzy'}, // BS

**Comment by sbx59** [comment]
@KiwiHC16 

`{
  "TS011F__TZ3000_wamqdr3f": {
    "nameJeedom": "LIDL Prise FR",
    "timeout": "60",
    "Comment": "TEST SBX",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5cfdgh0asDFRTd6rt78620b6b",
      "icone": "TS0121",
      "mainEP": "01"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "societe",
      "include3": "nom",
      "include4": "etatCharge0",
      "include5": "On",
      "include6": "Off",
      "include7": "Toggle",
      "include8": "getEtat",
      "include9": "getManufacturerName",
      "include10": "getModelIdentifier"
    }
  }
}

fonctionne uniquement si je modifie aussi dans le dossier TS011F le uniqID : 5cfdgh0asDFRTd6rt78620b6b ( celui de la prise ) au lieux de 5ceosfqsds766ssdgdfzsddzze5d4lkjyd4 ( celui du TS011F )`

Si je ne modifie pas le fichier TS011F voila le probleme : 
![image](https://user-images.githubusercontent.com/78600632/111493545-f2ba9100-873d-11eb-9438-0e5f8fb73273.png)

**Comment by sbx59** [comment]
@wikijm J'ai réussi avec ta méthode ! mais pareil, je n'arrive pas a faire fonctionne sans modifier le fichier d'origine ... si tu a eu l'astuce je prends !

**Comment by GaelM01** [comment]
@sbx59 et ensuite tu demande aux pro de la bidouille mais tu t'en sors bien :)
Moi j'ai juste rien compris à la création de modèle et toute la suite pour la prise ...
Pour le moment, j'ai le on/off qui marche le répéteur zigbee mais pas le retour d'état.
J'attends pour recréer lorsque le modèle sera dans abeille, je pense que ça sera plus prudent pour moi.

**Comment by sbx59** [comment]
@GaelM01 c'est une bidouille qui marche qu'a 50% :D J'attends les pro, mais aussi le concepteur d'Abeille.

**Comment by SebRider** [comment]
Bonjour,

Pour info, 
Pour ceux qui ont réussi a ajouter la prise avec l'avant dernière ou N-2 mise a jour de Abeille.

Avec ces précédentes version elle était bien reconnue avec ON OFF et retour d'état.
C'était sommaire mais fonctionnel.
Depuis cette dernière mise a jour d'abeille (2021-04-07 01:00:10), la prise devient inopérante.

**Comment by sbx59** [comment]
Pareil. Ne fonctionne plus avec mes bidouilles.

**Comment by sbx59** [comment]
bonjour,

petit UP, :(

**Comment by tcharp38** [comment]
Salut
KiwiHC16 est bien sur d'autres activites en ce moment mais je peux essayer de creuser. Je n'ai aucun de ces equipements donc ca se fera à l'aveuglette. 
Une nouvelle stable devrait etre dispo demain. On repartira de la mais j'aurai besoin d'une reinclusion (apres suppresion de l'eq) et  du tar.gz des logs (page support, telecharger tout + drap & drop ici).
A tres bientot

**Comment by tcharp38** [comment]
J'ai besoin de précisions.
Quelle est la ref fabricant du modele en question ?

Jusque la on les infos suivantes
- modelId (zigbee): 'TS011F'
- manufacturer (zigbee) '_TZ3000_wamqdr3f'
- fabricant: Silvercrest
- modele: ??
- nom: Silvercrest plug

**Comment by GaelM01** [comment]
Sur la notice on a Model No.: HG06337-FR
Si c'est ça dont tu parles .

**Comment by tcharp38** [comment]
Support dans la derniere stable
Voir https://github.com/KiwiHC16/Abeille/issues/2053
