### ISSUE TITLE
ruban led lidl

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1737]
https://community.jeedom.com/t/prise-connectee-silvercrest/52441/6

```
_TZ3000_riwp3k79
```

```
_TZ3000_wamqdr3f
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by GaelM01** [comment]
Bonjour,
Je post mon premier Abeilleparser.log

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/5958513/AbeilleParser.log)
D'après ce que j'ai compris il fallait mettre le log en debug, relancer le démon puis inclure le ruban led lidl. En espérant que ça aide.

Je rajoute juste une capture d'écran qui me dis : "Nouvel équipement 'TS0505A' inconnu" qui n'apparait pas dans le log du dessus ou je ne l'ai pas vu.
![abeille ruban led lidl 2021-02-10 144142](https://user-images.githubusercontent.com/78859197/107517573-33a70f00-6bae-11eb-9064-f7c2455388c2.png)
Merci pour le super boulot.
Cordialement.

**Comment by GaelM01** [comment]
Je rajoute ça : 
1/ Version (AbeilleVersion.inc)
===============================
stable, 2021-02-08 19:01

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux Jeedom 3.16.85+ #1 SMP PREEMPT Mon Jul 13 14:40:04 UTC 2020 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

4/ AbeilleParser / Modelisation
===============================
[2021-02-10 14:38:19][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964299,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:19][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964299,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:20][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964300,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:20][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964300,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:20][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964300,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:21][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964301,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:21][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964301,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:21][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964301,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:21][debug]   ManufacturerName='_TZ3000_riwp3k79', trimmed='_TZ3000_riwp3k79', {"Abeille1\/D73B":{"time":1612964301,"ManufacturerName":"_TZ3000_riwp3k79"}}, [Modelisation]

[2021-02-10 14:38:27][debug] Abeille1, Type=004d/Device announce, Addr=4789, ExtAddr=00124B0022696333, MACCapa=80, [Modelisation]

[2021-02-10 14:45:06][debug]   ModelIdentifier='TS011F', trimmed='TS011F', [Modelisation]

[2021-02-10 14:45:06][debug]   ModelIdentifier='TS011F', trimmed='TS011F', [Modelisation]

je viens de voir que pour une nouvelle issue il fallait le mettre, mais comme je contribue pour la 1er fois, je pense que ça peut être utile.

**Comment by KiwiHC16** [comment]
#1734 ?

**Comment by KiwiHC16** [comment]
Oui c est la bonne manip pour les logs.

_TZ3000_riwp3k79
TS011F

as tu une image de la bete ?

**Comment by GaelM01** [comment]
Bonsoir, voilà 
![Ruban Led Lidl 4](https://user-images.githubusercontent.com/78859197/107570783-4a6b5700-6bea-11eb-8df5-15ba86fc6672.png)

**Comment by GaelM01** [comment]
![Ruban Led Lidl 2](https://user-images.githubusercontent.com/78859197/107569906-20656500-6be9-11eb-96f0-6014429767ea.png)

**Comment by GaelM01** [comment]
J'ai pas trouvé mieux.

**Comment by KiwiHC16** [comment]
Comment est connect le ruban de LEDs au secteur ? Un boitier ?

**Comment by GaelM01** [comment]
![IMG_20210210_223014](https://user-images.githubusercontent.com/78859197/107575185-e3e93780-6bef-11eb-9b8b-de5c315e7c47.jpg)
![IMG_20210210_223030](https://user-images.githubusercontent.com/78859197/107575244-fe231580-6bef-11eb-83b2-065a86713a05.jpg)

**Comment by GaelM01** [comment]
Voilà j'ai mis des photo en plus.

**Comment by GaelM01** [comment]
c'est pas du ip68 mais pour 18€, si ça passe sur abeille, c'est très correct ^^

**Comment by GaelM01** [comment]
> 
> 
> #1734 ?

Oui ça doit être le même je n'avais pas vu l'autre issue

**Comment by GaelM01** [comment]
Comme il y a une nouvelle version du plugin abeille je renvoie un AbeilleParser.

[AbeilleParser(2).log](https://github.com/KiwiHC16/Abeille/files/6027037/AbeilleParser.2.log)

Lorsque j'inclue le ruban LED, j'ai toujours un équipement inconnu sans aucune commande utile pour commander le ruban LED.

Étant donné que sur l'autre issue #1734, la personne à l'air d'avoir réussi à le programmer mais malheureusement, je n'ai rien compris à la manipulation. 

Où faut-il créer les fichiers ou le modèle ?

Merci.

**Comment by KiwiHC16** [comment]
```
_TZ3000_riwp3k79
```

J ouvre un cas "Pourquoi ce message" #1838 car je vois une ligne dans le log que je ne comprends pas.

**Comment by KiwiHC16** [comment]
Voir mon dernier message dans #1734

**Comment by kaleofr** [comment]
Hello,

pour ma part j'ai en plus la possibilité de:
- réglé la température du blanc. Mon ruban réagit entre 1700k et 4900k(l'approximation à 5000k marche bien)
- un bouton pour passer au blanc 1700k
- un bouton Toggle

Cela nécessite d'ajouter au json actuel les lignes suivantes:
"include8": "Toggle",
"include37": "1700K",
"include40 2 2": "setTemperatureLight_1700_4900",

Et d'ajouter les commandes 1700K.json, setTemperatureLight_1700_4900.json et Toggle.json
1700K.json
```
{
  "1700K": {
    "isVisible": 1,
    "name": "1700K",
    "isHistorized": "0",
    "type": "action",
    "subType": "other",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "topic": "setTemperature",
      "request": "EP=#EP#&slider=1700",
      "visibilityCategory": "All"
    }
  }
} 
```
 setTemperatureLight_1700_4900.json
```
{
  "setTemperatureLight_1700_4900": {
    "isVisible": 1,
    "name": "setTemperatureLight_1700_4900",
    "isHistorized": "0",
    "type": "action",
    "subType": "slider",
    "generic_type": "LIGHT_SET_COLOR_TEMP",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "topic": "setTemperature",
      "request": "EP=#EP#&slider=#slider#",
      "minValue": "1700",
      "maxValue": "4900",
      "visibilityCategory": "All"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}
```

Pourquoi la commande Toggle.json est elle passée en obsolète? y-a-t-il moyen d'écrire les choses autrement?

Cordialement,

Kaléo.

**Comment by tcharp38** [comment]
J'ai ajouté tes commandes à Abeille.

Cote Toggle, ca existe encore mais je soupconne que ca n'est guere utilise. Quand on a ON et OFF on utilise ca + facilement que toggle car on connait le resultat mais peut etre que je me trompe.
Tu t'en sers ?

Sinon c'est juste la syntaxe qui a changé.
            "Toggle": {
                "use": "zbCmd-0006-Toggle",
                "nextLine": "after"
            }

J'ai fait un "LISEZMOI.txt" dans le "core/config/commands". Jettes y un oeil si tu veux.

**Comment by kaleofr** [comment]
Oui j'utilise le Toggle, pas vraiment sur l'interface graphique mais en réaction à un bouton physique d'une télécommande.
Un seul bouton, quand j'arrive dans la pièce, un appui pour allumer. Même bouton et même appel à Toggle pour éteindre en sortant. Pas besoin de scénario pour savoir s'il faut éteindre ou allumer.
Je vais regarder le Lisezmoi merci.

**Comment by tcharp38** [comment]
Ha ok, donc triggé par un autre evenement. Je le remets dans sa nouvelle syntaxe.
Mais du coup ca veut dire qu'il n'a pas besoin d'être visible.
J'essaie de limiter aux commandes vraiments utiles. C'est pourquoi j'avais eu tendance à le virer.

**Comment by tcharp38** [comment]
@kaleofr 
Tu pourrais me rappeler l'identifiant du produit que tu utilises ?
Page equipement/avancé ... fichier JSON

Ex
![image](https://user-images.githubusercontent.com/35221038/134025299-5309f99f-7563-4d43-83cd-af8a12520c48.png)

**Comment by kaleofr** [comment]
Ils sont reconnus comme TS0505A

**Comment by tcharp38** [comment]
Mise à jour avec Toggle

[TS0505A.zip](https://github.com/KiwiHC16/Abeille/files/7215716/TS0505A.zip)

A l'occasion peux tu faire une interrogation Zigbee et me filer le discovery.json ? Merci

**Comment by kaleofr** [comment]
> Ha ok, donc triggé par un autre evenement. Je le remets dans sa nouvelle syntaxe.
> Mais du coup ca veut dire qu'il n'a pas besoin d'être visible.
> J'essaie de limiter aux commandes vraiments utiles. C'est pourquoi j'avais eu tendance à le virer.

Ca me semble la meilleur solution: mettre un maximum de choses dans la configuration pour que l'utilisateur en ai connaissance, quitte comme tu le propose à mettre ca en non visible.

Concernant le fichier ci-dessus:
Il y a pour mes rubans une erreur dans ce fichier: le mainEP n'est pas 03 mais 01.
Le TS0505A originale est un Tuya, certainement avec un mainEP=03 (#1734).
Le Lidl est en 01.

Pourrais-tu également ajouter les commandes:
"include37": "1700K",
"include40 2 2": "setTemperatureLight_1700_4900"

dans TS0505A.json?

Le discovery ne donne pas grand choses malheureusement.
`{"endPoints":{"01":{"servClusters":{"1000":{},"0000":{"attributes":{"0005":{"value":"TS0505A"},"0004":{"value":"_TZ3000_riwp3k79"}}},"0003":{},"0004":{},"0005":{},"0006":{"attributes":{"0000":{"value":1}}},"0008":{"attributes":{"0000":{"value":255}}},"0300":{"attributes":{"0007":{"value":453}}}},"cliClusters":{"0019":{},"000A":{}}},"F2":{"servClusters":{"":{}},"cliClusters":{"0021":{"attributes":{"0010":{},"0011":{},"0016":{},"0017":{},"0022":{},"FFFD":{}}}}}},"epCount":2}`

**Comment by tcharp38** [comment]
Ok donc on parle de 2 modeles differents sur la base Tuya.
Voila celui qui correspond à ton modele.
A ajouter dans core/config/devices
L'autre (TS0505A) etant Tuya.

[TS0505A__TZ3000_riwp3k79.zip](https://github.com/KiwiHC16/Abeille/files/7217581/TS0505A__TZ3000_riwp3k79.zip)

Ca te va ?

**Comment by kaleofr** [comment]
Parfait merci!

**Comment by tcharp38** [comment]
210926-BETA-1
