### ISSUE TITLE
Version Abeille Master  / Fichiers corrompus

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1742]
@tcharp38

Petit souci avec la dernière version Master

![image](https://user-images.githubusercontent.com/36518012/107618007-22fba500-6c51-11eb-8293-dd1a83466f2f.png)

![image](https://user-images.githubusercontent.com/36518012/107618246-884f9600-6c51-11eb-822d-0024ff0df636.png)

Comment puis-je t'aider ?

**Comment by tcharp38** [comment]
Salut
Ha oui. Pas surprenant en fait. En gros apres un merge il faut refaire les signatures MD5.
Ce qu'on ne fait pas encore. Il faut trouver un process automatique pour ca.
Mais du coup le message ne devrait pas apparaitre.

Idealement il faudrait qqch qui se declenche juste apres le merge de chaque PR, donc probablement cote GitHub.
Si qqn à une idée.. je prends

Tout ca pour dire que les fichiers ne sont pas corrompus mais que le fichier de signature n'etant pas à jour, le check ne devrait pas avoir lieu.

**Comment by mickadam29** [comment]
OK, donc mise à jour fonctionnelle et simple message de check à ignorer. C'est bien cela ?

**Comment by tcharp38** [comment]
La oui.
J'ai poussé une modif qui devrait empecher le check quand le fichier de signature n'est pas à jour. A voir si ca suffit des que Kiwi l'a integré.
Je suis aussi en train de mettre à jour la doc pour detailler tout ca.

**Comment by tcharp38** [comment]
https://kiwihc16.github.io/AbeilleDoc/Developpement.html#test-d-integrite-du-plugin

**Comment by mickadam29** [comment]
Nickel cette doc

**Comment by KiwiHC16** [comment]
On continue dans #1776
