### ISSUE TITLE
Réglage du TimeOut supprimé?

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#1744]
Bonjour,

je ne retrouve plus le champ pour personnaliser le TimeOut de mes équipements.
Est-ce normal? 
Si oui, comment personnaliser les Timeout maintenant?
Si non, comment remédier à cela? Fausse manip de ma part? Problème dans ma DB?

![image](https://user-images.githubusercontent.com/60474071/107748901-0ecfaa80-6d1a-11eb-8c3b-60bfc0f524c9.png)

Informations clefs nécessaires au support.

Quand vous ouvrez une "issue" dans GitHub merci de copier/coller les 3 premiers chapitres ci dessous 
Pour l'intégration d'un équipement non encore supporté ajoutez le chapitre 4.

1/ Version (AbeilleVersion.inc)
===============================
beta, 2021-02-08 19:03
2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l","","**************************************","*           Welcome to Jeedom        *","**************************************","....]
["Linux jeedom 5.10.5-v8+ #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021 aarch64 GNU\/Linux"]
3/ Firmware
===========
Zigate 1: 031D

Merci, 

Kaléo.

**Comment by tcharp38** [comment]
Dans la partie "parametres" je crois maintenant

**Comment by battousai90** [comment]
Configuration Avancé / Alertes :
![image](https://user-images.githubusercontent.com/47687052/107750814-d382ab00-6d1c-11eb-978d-6610a76df66d.png)

**Comment by tcharp38** [comment]
Effectivement. Ca manque :(
C'est donc une regression à fixer.

**Comment by kaleofr** [comment]
Effectivement dans alertes communications mais même si je comprends la confusion que peut apporter le timeout, justement TimeOut ne veux pas dire que l'on souhaite obligatoirement émettre une alerte...
Mais pourquoi pas...

**Comment by tcharp38** [comment]
Correction dans le PR #1743

**Comment by kaleofr** [comment]
Thanks.
