### ISSUE TITLE
Problème d'inclusion, crash démon et... début de solution

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#1753]
Bonjour,

depuis quelques temps mes inclusions se soldent par un Erreur sur Abeille::deamon() :  Call to a member function execCmd() on bool
Rédémarrage du démon et refresh lqi et je m'en tirait.
Tout ca sur beta, 2021-02-08 19:03

Sauf que... pour un interrupteur qui passe en sommeil, a chaque réveil pour l'inclusion j'avais l'erreur, du coup impossible de l'inclure.
J'ai donc fouillé les logs et la dernière ligne du log debug de Abeille était 'vérification des adresses IEEE manquantes'
J'ai ajouté une commande log pour connaitres les abeilles dont l'IEEE manquait et il s'agissait de toutes mes télécommandes virtuelles de groupes (remotecontrol.json).

J'ai inséré en ligne 1331 de Abeille.class.php les deux lignes suivantes:
        $modeleJson= $bee->getConfiguration('modeleJson', 'none'); 
     	if($modeleJson=='remotecontrol') continue; 

Ma tentative d'inclusion suivante s'est exécutée correctement. J'ai donc, je penses, une solution pour mon problème... jusqu'à la prochaine update.
Est-il normal que mes télécommandes n'aient pas d'adresses IEEE complètes?
Suis-je le seul à avoir ce problème et si oui comment le résoudre?

Merci à vous.
Kaléo

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
'remotecontrol':
Correction interessante, je vais regarder car c est un objet virtuel qui ne fonctionne pas exactement comme les vrais équipements.

Par contre ce que je comprends pas c est pourquoi ce modele est impliqué quand tu parles d'un vrai équipement qui se reveille.

> Sauf que... pour un interrupteur qui passe en sommeil, a chaque réveil pour l'inclusion j'avais l'erreur, du coup impossible de l'inclure.

Quel équipement est ce ?

**Comment by kaleofr** [comment]
C'est une commande sans fils Legrand. 
Le problème venait juste du fait que l'inclusion au réveil du module plantait le demon, ce qui n'était pas le cas lors d'un refresh lqi. Le refresh lqi me permettait donc de finaliser l'inclusion de mes autres modules auparavent.
Avec ma modification, tout va bien, y compris pour la commande sans fils.

**Comment by tcharp38** [comment]
Salut @kaleofr 
Quel est le status de ce point ? 
Il y a une nouvelle beta dispo. L'as tu essayé ?

**Comment by tcharp38** [comment]
La partie inclusion a ete revue (210526-BETA-1).
Comme il n'y a aucune nouvelle de ce point depuis un moment je clos.
Ouvrir un nouveau sujet si besoin.
Merci

**Comment by kaleofr** [comment]
Bonjour tcharp,

J'ai fais une RAZ de ma zigate il y a quelques temps et tout réinclu. 
Je n'ai rien ajouté dernièrement donc je ne sais pas si le problème est résolu.
En tous cas, abeille est bien plus stable depuis un certain temps.
Merci.
