### ISSUE TITLE
Capteur qui rejoint tout les jours le réseau

### ISSUE THREAD

**Issue by dams74** [KiwiHC16/Abeille#1756]
Bonjour
Depuis quelques semaines j'ai un capteur et c'est tous les jours le même qui rejoint le réseau.
J'imagine donc qu'il doit en sortir.
C'est un capteur Hue motion extérieur
Je n'arrive pour le moment pas à récupérer les log car je m'en aperçois trop tard.
Promis j'en mets un dès que j'arrive à en récupérer.
Sinon auriez vous une piste pour ce genre de soucis
Merci de votre aide
Damien

**Comment by tcharp38** [comment]
Salut. Pas d'inquietude si il est toujours en vie.
On avait ajouté ce message car dans certains cas il est utile mais il est vrai qu'il peut etre trop "verbeux" suivant les equipements.
Donc en gros ca n'est pas un souci en soit mais juste une info qu'on ne sait pas encore trop comment gerer.

Mais je suis curieux pour voir comment on peut ameliorer les choses, il faudrait extraire d'AbeilleParser.log les messages du type "Device announce" pour le capteur en question.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
C est du meme niveau qu'un renew DHCP.
@tcharp38 perso je pense qu on doit cacher ce message car il va créer plein de questions pour rien. On peut le garder en mode dev si tu souhaite l utiliser dans des investigations. 

Je clos cet issue. Si vous pensez en avoir besoin rouvrez le.

**Comment by dams74** [comment]
Merci à vous deux pour les info. 
Si j'y arrive à capturer un log je vous le déposerai

**Comment by tcharp38** [comment]
Je vais le laisser actif seulement en mode dev. Faut comprendre comment filtrer les messages utiles de ceux qui disent juste "suis toujours la"

**Comment by dams74** [comment]
j'ai réussi à récupérer un log abeille
` message(topic='Abeille1/6C4C/enable', payload='20918A0000002FEE')
[2021-02-18 17:02:52][DEBUG] : message(): cmd=enable, net=Abeille1, IEEE=20918A0000002FEE
[2021-02-18 17:02:52][DEBUG] : message(): Mise-à-jour Abeille1/6C4C => Abeille1/6C4C
[2021-02-18 17:02:52][DEBUG] : message(topic='Abeille1/Ruche/joinLeave-IEEE', payload='Annonce->20918A0000002FEE')`

Je n'ai malheureusement pas le abeille cmd log

J'espère que ça vous aidera
