### ISSUE TITLE
Prise Innr SP 220

### ISSUE THREAD

**Issue by Jackbets** [KiwiHC16/Abeille#1757]
Bonjour,

J'ai acheté une prise Inrr SP 220, ma Zigate la voit bien mais le plugin abeille la voit en modèle inconnu. (Nouvel équipement 'SP220' inconnu. Utilisation de la config par défaut. [Modelisation])

Ce qui est bizarre c'est que je n'ai pas de fichier de log abeille payser.

J'ai que les fichiers ci-joints. Je suis persuader que j'avais avant le log payser. 

Faut-il être en débug ou autre ?

Pour info, j'active une inclusion toute les heures à cause d'un inter qui perd parfois le réseau. 

[AbeilleLogs-210214.tar.gz](https://github.com/KiwiHC16/Abeille/files/5977495/AbeilleLogs-210214.tar.gz)

1/ Version (AbeilleVersion.inc)
===============================
stable, 2021-02-08 19:01

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux Jeedom 3.16.85+ #1 SMP PREEMPT Mon Jul 13 14:40:04 UTC 2020 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

4/ AbeilleParser / Modelisation
===============================

**Comment by KiwiHC16** [comment]
Dans log Abeille:
```
[2021-02-14 11:07:46][ERROR] : Nouvel équipement 'SP220' inconnu. Utilisation de la config par défaut. [Modelisation]
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Il faudrait vraiment le log AbeilleParser.

Sinon as tu une image de la bête ? 
Un lien vers les spécifications ?

**Comment by Jackbets** [comment]
![innr-sp-220](https://user-images.githubusercontent.com/79042137/107986922-60539000-6fcd-11eb-9646-ebb781a58a6e.jpg)
Lien de la bête :

https://www.domadoo.fr/fr/peripheriques/5362-innr-prise-connectee-super-slim-zigbee-30-8718781552657.html?tag=6397152

Par contre, j'ai eu un soucis j'ai pas de log AbeilleParse. Je l'avais déjà mais je ne sais pas pourquoi je ne l'ai plus ! une solution ?

<img width="660" alt="Capture d’écran 2021-02-15 à 20 36 52" src="https://user-images.githubusercontent.com/79042137/107987126-c6d8ae00-6fcd-11eb-90d4-47dfc9b84ff8.png">

**Comment by KiwiHC16** [comment]
Passe le plugin en mode debug. Il est en mode Defaut d après ta capture d écran, redémarre le daemon et tu devrais avoir le log.

**Comment by Jackbets** [comment]
effectivement cela marche mieux :)  

Ci-joint le log AbeilleParser (au moment inclure la SP220 Innr)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/5991675/AbeilleParser.1.log)

**Comment by KiwiHC16** [comment]
```
[2021-02-16 22:10:38][debug]   ManufacturerName='innr', trimmed='innr', {"Abeille1\/B074":{"time":1613509838,"ManufacturerName":"innr"}}, [Modelisation]
```

```
[2021-02-16 22:10:38][debug]   ModelIdentifier='SP 220', trimmed='SP220', [Modelisation]
```

```
EP=01
```

**Comment by KiwiHC16** [comment]
Je n ai pas toutes les informations mais j ai fait un premier modele pour tester.
Peux tu recuperer le fichier:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/SP220
le mettre sur ton systeme, supprimer l'équipement dans abeille et refaire une inclusion et partager le resultat ?

**Comment by Jackbets** [comment]
Ah mince pour le log. Question stupide, on télécharge comment le fichier sur le site ? je clique dessus mais cela m'ouvre le fichier sur le site... ?

**Comment by Jackbets** [comment]
Personne ne sait ?

**Comment by Jackbets** [comment]
UP

**Comment by Jackbets** [comment]
> Je n ai pas toutes les informations mais j ai fait un premier modele pour tester.
> Peux tu recuperer le fichier:
> https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/SP220
> le mettre sur ton systeme, supprimer l'équipement dans abeille et refaire une inclusion et partager le resultat ?

Ah mince pour le log. Question stupide, on télécharge comment le fichier sur le site ? je clique dessus mais cela m'ouvre le fichier sur le site... ?

**Comment by KiwiHC16** [comment]
Le fichier doit être dispo dans la version stable dispo sur le market. Peux tu mettre à jour Abeille ?

**Comment by Jackbets** [comment]
yes je viens de tester la commande on off et le retour d'état ont l'air de fonctionner. Je vais poursuivre les tests les prochains jours. Par contre, l'image ne se charge pas une icone apparait dans le coin à gauche (catalogue des compatibilité et sur l'équipement lui même)

**Comment by Jackbets** [comment]
est ce normal ?

**Comment by KiwiHC16** [comment]
Capture d ecran ?

**Comment by Jackbets** [comment]
Ci-joint les captures d'écrans. 

<img width="439" alt="Capture d’écran 2021-03-09 à 21 43 11" src="https://user-images.githubusercontent.com/79042137/110535474-9e515900-8120-11eb-856e-5e27f72b6e3f.png">
<img width="1044" alt="Capture d’écran 2021-03-09 à 21 41 54" src="https://user-images.githubusercontent.com/79042137/110535484-a01b1c80-8120-11eb-9981-4165ba9c1aac.png">
<img width="844" alt="Capture d’écran 2021-03-09 à 21 40 53" src="https://user-images.githubusercontent.com/79042137/110535491-a27d7680-8120-11eb-8939-f0a71a32d2ef.png">

**Comment by Jackbets** [comment]
Du coup, c'est normal ?

**Comment by Jackbets** [comment]
Depuis la dernière MAJ abeille, les images s'affichent désormais. Je clos :) .
