### ISSUE TITLE
Volet Profalux semble ne plus être crée dans Abeille 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1759]
https://community.jeedom.com/t/impossible-de-faire-remonter-les-peripheriques-sur-abeille/53644

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Peux tu partager une capture d'écran de la liste des tes équipements Abeille ?
Peux tu aussi ajouter une capture d'écran "Tables de liens" ?

**Comment by KiwiHC16** [comment]
Je viens de faire une modif dans le code qui devrait aider. Dispo dans la stable dans 15 jours, soit le 2 mars.

**Comment by Seby9576** [comment]
Bonjour KiwiHC, peux tu me dire si sur jeedom le retour de position fonctionne avec les volets profalux stp ? Si oui est ce un vrai retour de position ou un retour estimatif ?
Je te pose cette question car je suis actuellement sur eedomus mais j'ai pas mal de soucis avec mes volets. Retour de position fictive et j'ai souvent des volets qui ne s'ouvre ou se ferme pas en mode automatique.
Donc je pense sérieusement a basculer sur jeedom pour ca.

Merci de ton retour

**Comment by KiwiHC16** [comment]
Je ne peux être affirmatif car je n'ai pas moi meme de volet profalux.
Pour l instant je n ai pas eu le temps d implementer le retour automatiquement.
Mais je crois me souvenir qu on peut les interroger.
Je sais que des utilisateurs avaient demandé un calibrage et d autres non.
Postes la question sur le forum avec plugin-abeille et je suis sure qu'on aura des retours.

**Comment by Seby9576** [comment]
merci de ton retour

**Comment by KiwiHC16** [comment]
Je clos r ouvre si besoin.
