### ISSUE TITLE
Modifier le hard ZiGate pour avoir une batterie 5V USB et un interrupteur pour association

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#176]
Rendre portable la ZiGate pour allez dans les pieces associer les objets.
En fait on a deja un interruptuer il suffit d'un bettarie et de changer le soft de le zigate.

**Comment by edgd1er** [comment]
genre clé usb z-wave d'aeon tec ;)

**Comment by KiwiHC16** [comment]
Sans le dire

**Comment by KiwiHC16** [comment]
Ce n'est pas necessaire car l inclusion se fait par les routeurs et le key par la zigate en routan tles messages.
