### ISSUE TITLE
Association (bind) directe d'interrupteurs Zigbee

### ISSUE THREAD

**Issue by JC-Villemur** [KiwiHC16/Abeille#1762]
Bonjour.
J'utilise des interrupteurs Tuya Zemismart pour créer des va et vient à des endroits, avec ou sans neutre, ou j'avais des interrupteurs simples et anciens.
Je fais des scenarios sur Jeedom avec le plugin Abeille et ça fonctionne très bien (utilisation de Toggle).

J'aurais voulu qu'un interrupteur s'adresse directement à l'autre, dans le cas du va et vient, pour : 
- éviter de passer par la box domotique, 
- avoir une réaction immédiate (comme un circuit filaire).

J'ai cherché, mais je n'ai pas trouvé. D'où ma question : est-ce possible avec Abeille ?

Merci beaucoup. Cordialement.

JC-Villemur

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by KiwiHC16** [comment]
Pour qu'un inter parle à un autre inter, c'est possible si on regarde la norme.
Maintenant je doute que cela codé dans le soft des inter.
Ce que j imagine possible est:
- d utiliser les groupes (d une ampoule avec 2 inter) mais je ne sais pas si le Tuya Z le supporte.  A regarder. La gestion des groupes est dans Abeille.
- de faire un bind de l inter vers l'ampoule mais je ne sais pas si le Tuya Z le supporte.  A regarder. La gestion d un bind d un équipement vers un autre n est pas dans Abeille. Je vais ouvrir une issue pour le faire.

**Comment by JC-Villemur** [comment]
Merci pour cette réponse rapide et précise.
Je ne vais pas utiliser les Groupes qui me semblent plutôt correspondre à une architecture de Télécommande.
Je vais attendre qu'un bind entre équipements Zigbee voit le jour.
Il méritera un signalement dans le changelog (et une récompense).
Cordialement.
JC Villemur

**Comment by KiwiHC16** [comment]
#1763

**Comment by KiwiHC16** [comment]
Je clos, a suivre dans #1763.
