### ISSUE TITLE
Bind d'un équipement vers un autre à implémenter dans Abeille.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1763]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.

**Comment by tcharp38** [comment]
Si le besoin est la, cette fonctionalité est dispo via la page EQ/avancé

![image](https://user-images.githubusercontent.com/35221038/142228856-28708558-c4e3-4241-b43e-53ed9aa9e5f7.png)

Je cloture mais à réouvrir si il y a besoin d'autre chose.
