### ISSUE TITLE
Ajout bouton remove from zigbee

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1770]
Ajouter un bouton pour retirer un equipement du reseau zigbee (sans touché a son existance dans Abeille).

La commande existe déjà. Accessible depuis la ruche. 

Objectif, more user friendly.

**Comment by tcharp38** [comment]
Il y a deja un point sur le sujet. 
Le #1273
Je clos le + vieux

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

Preneur des infos et des tests.
J'ai un routeur qui est présent dans Abeille et donc Zigate alors qu'il est HS. J'aimerai le supprimer car j'ai encore son IEEE mais visiblement la commande 0026 ne le vire pas de la Zigate. A moins que je ne m'y prenne mal.

**Comment by tcharp38** [comment]
C est un sujet que j'avais démarré il y a un moment mais que j'ai arrété en cours par manque de reponses.
Mais en résumé la ou j'en etais
- pas sur de la commande 0026. On m'a aussi aiguillé vers 004C
- Pour exclure un eq il faut que celui ci soit reveillé. Donc possible seulement avec un eq sur secteur
- De + dans le protocole zigbee c'est toujours l"eq qui dit si oui ou non il quitte le reseau donc si il est mort avant... c'est mort. Il reste un zombi dans la table des noeuds connus. Bref ce dernier point est peut etre ton pb.
Du coup si je vois juste, tu ne peux que le virer de Jeedom. Si HS son IEEE ne sera plus jamais active. Neanmoins occuper un slot de la zigate pour rien c'est un pb je trouve. Tout comme j'aimerais savoir comment connaitre le status de la zigate (nbre d eq connus vs max)

**Comment by mickadam29** [comment]
Je me suis pas penché énormément sur le sujet mais c'est curieux comme principe. Je vois pas l'intérêt pour la norme d'exclure la possibilité de virer de force un équipement. Je ferai avec évidemment. Lorsque qq1 se sera penché sur la mémoire d'un coordinateur il y aura certainement une façon de faire. D'ailleurs si on efface la PDM, ca revient en partie à la même chose non ?

**Comment by tcharp38** [comment]
Si on efface la PDM oui le coordinateur ne connait plus personne.
Mais aujourd hui on ne sait pas enlever juste un eq de la PDM.

**Comment by mickadam29** [comment]
Y a plus qu'à mettre le doigt sur la façon de faire. Même si c'est pas très Zigbee Alliance

**Comment by KiwiHC16** [comment]
En fait il y a 3 commandes au moins comprises par la zigate: 
- Remove qui est la command 0x0026. (Celle de ce sujet initialement)
- Mgt Leave Request qui est la commande 0x0047
- Leave Request Cmd 0x004C

0026 permet d'effacer de la zigate les infos d'un device. Je l'utilise quand un équipement 'disparait' ou quand j'ai du mal a faire une nouvelle inclusion car la zigate n'envoie pas deux fois la clef réseau.

Il faudrait que je teste les 3 pour voir les messages sur le zigbee.

**Comment by mickadam29** [comment]
@KiwiHC16 
Tu utilises la commande Remove avec l'adresse IEE de l'équipement à virer ? Sans action sur la Zigate

![image](https://user-images.githubusercontent.com/36518012/108032412-b9094400-7032-11eb-8032-419afeb0bd44.png)

La commande passe dans les logs

![image](https://user-images.githubusercontent.com/36518012/108032593-05548400-7033-11eb-9804-fc8af85d7a2b.png)

Un refresh LQI interroge toujours 14 objets. Seulement 13 sur le réseau. Le dernier étant celui que je veux virer.

C'est peut-être parce qu'il n'est pas directement rattaché à la Zigate ?

![image](https://user-images.githubusercontent.com/36518012/108033734-bd366100-7034-11eb-8dc2-47cbdc8911b2.png)

**Comment by KiwiHC16** [comment]
Remove pour moi retire l equipement de la base zigate. Mais personne sur le réseau n'est informé. Donc sur un LQI le routeur vont continuer à rapporter des infos pendant un certain temps.

Pour faire ce que tu veux il faut certainement utiliser:
- Mgt Leave Request qui est la commande 0x0047
- Leave Request Cmd 0x004C
en reveillant le device. Je vais faire des tests pour mieux cerner ces commandes.

**Comment by tcharp38** [comment]
Je dirais que pour les eq sur batterie, inutile de perdre du temps a "reveiler" le device. Lui faire un reset et c'est bon il quitte tout seul sans compliquer la procedure et Abeille est au courant.

Pour moi la question ne se pose que pour les eq sur secteur.

Non ?

**Comment by KiwiHC16** [comment]
Sur remplacement d'equipement je fais un remove:
```
self::publishMosquitto(queueKeyAbeilleToCmd, priorityNeWokeUp, "Cmd" . $destGhost . "/Ruche/Remove", "IEEE=" . $IEEE);
```

**Comment by KiwiHC16** [comment]
@tcharp38, faisons des tests avant de conclure.

**Comment by mickadam29** [comment]
Celui que j'aimerais retirer n'est pas sur batterie. Et effectivement ta fonction remove sur Remplacement devrait opérer de la même façon. A priori.

**Comment by tcharp38** [comment]
> @tcharp38, faisons des tests avant de conclure.

Bien sur :)

**Comment by KiwiHC16** [comment]
J'ai le detail des specifications et les tests sont en lignes.
Reste à savoir ce que l on fait dans Abeille.

**Comment by mickadam29** [comment]
Suis partant pour mettre en oeuvre. Y compris une routine php avant d'intégrer. J'ai ce routeur à virer et si j'ajoute la fonction routeur aux modules DIY, j'aimerai être certain de pas les accumuler au fur et à mesure de mes essais

**Comment by KiwiHC16** [comment]
@mickadam29 sur github et Mick... A... sur Slack est la meme personne ?

**Comment by tcharp38** [comment]
@KiwiHC16 
Tu peux resumer ce que tu sais fonctionnel ?

**Comment by mickadam29** [comment]
Oui. Une seule et même personne

**Comment by KiwiHC16** [comment]
1 - Remove qui est la command 0x0026. (Celle de ce sujet initialement)
Fait le remove au niveau NWK. Typiquement utilisé par le controleur de reseau (TC, ici zigate) pour virer des équipement qu il ne veut pas/plus.
Probablement pas optionnel car dans la couche Security.

2 - Mgt Leave Request qui est la commande 0x0047
 Typiquement utilisé par un Gestionnaire de réseau (ici Abeille)
Norme dit Optionnel.

3 - Leave Request Cmd 0x004C
Typiquement utilisé par un equipement qui veut en sortir un autre. Par exemple un routeur qui dit à son child, quitte et revient / ou pas.
Radius = 1 (Pas de routage)

Donc trois facons de faire decritent dans la norme qui font en gros la même chose.

Je dirai que si j ai bien compris, celui qui doit fonctionner à tous les coups et repond à nos besoins est le premier.

Les trois sont implementés dans des commandes de la ruche.

**Comment by KiwiHC16** [comment]
@tcharp, tu nous fais un beau bouton sur la base de la commande 1 ?

Commande dispo dans la  ruche:

![Capture d’écran 2021-02-17 à 12 22 03](https://user-images.githubusercontent.com/8549674/108197496-c0a41800-711a-11eb-8753-0d445eefc130.png)

**Comment by KiwiHC16** [comment]
@mickadam29, quand tu fais tes essais, si tu effaces la memoire du chipset, il faut faire un Remove depuis la ruche (cf commande ci dessus) sinon tu ne pourras pas re-inclure ton equipement.

**Comment by KiwiHC16** [comment]
Je pense qu'il faut aussi modifier les parametres et passer de:
IEEE=#title#
à
ParentAddressIEEE=#title#&ChildAddressIEEE=#message#

Je vais faire ca.

**Comment by mickadam29** [comment]
> @mickadam29, quand tu fais tes essais, si tu effaces la memoire du chipset, il faut faire un Remove depuis la ruche (cf commande ci dessus) sinon tu ne pourras pas re-inclure ton equipement.

Je ne souhaite pas faire le reset. Sinon encore une fois, il faudra tout réinclure

**Comment by mickadam29** [comment]
> Je pense qu'il faut aussi modifier les parametres et passer de:
> IEEE=#title#
> à
> ParentAddressIEEE=#title#&ChildAddressIEEE=#message#
> 
> Je vais faire ca.

J'ai tenté avec ZGUI de NXP, ca n'a visiblement pas marché non plus. Je te laisse poursuivre. Dans ce cas, Parent j'ai mis Zigate, et Child, mon routeur à sortir

**Comment by mickadam29** [comment]
Et la commande de la ruche je l'ai testée aussi. Sans succès.

![image](https://user-images.githubusercontent.com/36518012/108199978-11694000-711e-11eb-92f7-e0f13333b351.png)

![image](https://user-images.githubusercontent.com/36518012/108200085-36f64980-711e-11eb-8166-08b092ae182b.png)

 Avec l'IEEE de mon routeur à virer

**Comment by KiwiHC16** [comment]
Sur quelle information tu te bases pour dire que cela ne fonctionne pas ?

**Comment by KiwiHC16** [comment]
> > @mickadam29, quand tu fais tes essais, si tu effaces la memoire du chipset, il faut faire un Remove depuis la ruche (cf commande ci dessus) sinon tu ne pourras pas re-inclure ton equipement.
> 
> Je ne souhaite pas faire le reset. Sinon encore une fois, il faudra tout réinclure

Reset Zigate ne fait rien.
Erase PDM et tu dois tout re-inclure
Remove eneleve juste celui que tu veux. C est cette commande que tu dois utiliser.

Note que rien ne change dans Abeille, c est juste Zigbee.

**Comment by mickadam29** [comment]
@KiwiHC16 

C'est tout à fait ça que je veux. Juste le remove. Mais rien ne se passe, je vais vérifier à nouveau.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-17 à 13 57 23](https://user-images.githubusercontent.com/8549674/108207461-116e3d80-7128-11eb-8ccd-c910f1253ac3.png)


Prends le master, supprimes la ruche, redemarre le daemon pour recreer la ruche, affiche la commade Remove, mets l IEEE de ton device/routeur dans les deux champs (Routeur et equipement).

**Comment by mickadam29** [comment]
Ca marche, je teste ça

**Comment by mickadam29** [comment]
La commande est passée. Je vérifie le résultat sur 
00124B0021080DCD

![image](https://user-images.githubusercontent.com/36518012/108208398-4c24a580-7129-11eb-99cc-806494ae1e70.png)

**Comment by KiwiHC16** [comment]
"Je vérifie le résultat" -> Comment fais tu ?

**Comment by mickadam29** [comment]
Il faut que l'équipement soit sur le réseau ? Car Abeille interroge autant de routeurs dans refresh_Lqi.

**Comment by mickadam29** [comment]
C'est peut-être pas révélateur ce nombre de routeurs ?

**Comment by KiwiHC16** [comment]
"Car Abeille interroge autant de routeurs dans refresh_Lqi" 
Il faut que je regarde si le refresh_lqi prend bien en compte le fait que e routeur a ete desactivé dans Abeille car viré du réseau.

**Comment by mickadam29** [comment]
ok.
Mais j'ai encore l'objet dans Abeille. Il faut peut-être que je le retire non ? gardé pour avoir son adresse courte et IEEE

**Comment by KiwiHC16** [comment]
refresh_lqi ne prend pas en compte la desactivation de l equipement et je ne vais pas le faire car je veux refresh_lqi brute pour recuperer tout ce que l on peut.

**Comment by KiwiHC16** [comment]
> Mais j'ai encore l'objet dans Abeille. Il faut peut-être que je le retire non ? gardé pour avoir son adresse courte et IEEE

Remove enleve que du reseau zigbee et ne touche pas a abeille. Si tu le re-inclus il sera de nouveau dans la bon equipement Abeille avec la meme adresse IEEE et peut etre une adresse courte differente.

**Comment by KiwiHC16** [comment]
@tcharp38 si tu peux faire un beau bouton pour exclure avec cette nouvelle version de la version Remove.
Elle fonctionne pour les routeur en fournissant 2 fois l adresse IEEE du routeur en paramètre.

Par contre pour les equipements terminaux cela va etre un peut plus difficile. Il faudrait recuperer lors d un refresh LQI le parent de l equipement et le conserver dans les parametres de l equipement.

**Comment by KiwiHC16** [comment]
@mickadam29 je voudrais garder cet issue sur le sujet dans le titre.
Pour ton sujet ouvres une issue specifique.

**Comment by mickadam29** [comment]
Ca marche.

**Comment by tcharp38** [comment]
> @tcharp38 si tu peux faire un beau bouton pour exclure avec cette nouvelle version de la version Remove.
> Elle fonctionne pour les routeur en fournissant 2 fois l adresse IEEE du routeur en paramètre.
> 
> Par contre pour les equipements terminaux cela va etre un peut plus difficile. Il faudrait recuperer lors d un refresh LQI le parent de l equipement et le conserver dans les parametres de l equipement.

Ok je vais regarder ca.
Mais vu que tu parles d'un equipement parent, quelle doc ferais tu pour expliquer la procedure ? Pour moi ca reste pas clair.

**Comment by KiwiHC16** [comment]
Je te contact sur slack pour les details.

**Comment by tcharp38** [comment]
J'ai pu verifier l'exclusion avec un capteur Xiaomi de temp.
Apres demande d'exclusion, un p'tit coup de reveil via l'appuis sur son bouton est le message "a quitté le réseau" est apparu.
Mais ca n'a pas fonctionné pour le Xiaomi lumi
Et je n'arrive pas à reinclure le temp Xiaomi.

**Comment by mickadam29** [comment]
De mon côté j'ai réussi à virer mon routeur grâce à la fonction Remove de la Ruche
Adresse IEEE du parent qui le connaissait
Adresse IEEE de mon routeur à virer. Heureusement que j'avais son IEEE

Merci à vous

**Comment by tcharp38** [comment]
Pas propre. Voir #1906

**Comment by tcharp38** [comment]
Bon j'ai rendu le bouton accessible à tous.
![image](https://user-images.githubusercontent.com/35221038/131132728-a8bbeb1d-f70d-453e-a733-868226436080.png)

Je clos. A reouvrir si besoin
