### ISSUE TITLE
Legrand 20AX: Etat et Mode mettent plusieures minutes avant de remonter.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1773]

**Comment by mickadam29** [comment]
@KiwiHC16 

Les autres équipements aussi. Voire se perdent ! Courage.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Sujet tres vieux et peu documenté.
A reouvrir si ce pb existe toujours.

**Comment by Patag** [comment]
Je confirme pourtant et seulement avec les commandes venant de Jeedom. Lorsqu'elles viennent du fil jour/nuis du compteur EDF, pas de souci. Mais j'arrive à vivre avec. :-) #2213
