### ISSUE TITLE
core/php/AbeilleClassTest.php: A t on besoin de ce fichier ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1774]
Les fonctions sont deja dans core/class/Abeille.class.php visiblement.

**Comment by tcharp38** [comment]
Je n'utilise pas personnellement.
Mais si des fonctions de test dans "Abeille.class.php" alors je suggere de nettoyer ce dernier pour bien separer du test des fonctionalites.

**Comment by KiwiHC16** [comment]
Je l ai enlevé en esperant qu il n est effectivement pas utilisé.
