### ISSUE TITLE
Page de config, panneau "Mise à jour (Vérification)" pas fiable

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1776]
Pour discussion et peut etre suppression le jour ou le test d'integrité est en place pour tous.

De mon cote ce panneau me dit "pas assez de place pour la mise à jour" mais la mise à jour se passe bien (avec test d'integrité).
Bref son utilité est peut etre à revoir.

> Espace disponible: ->
> ....Avail
> .... 245M
> 
> 
> Taille Abeille: ->
> ....673M /var/www/html/plugins/Abeille
> 
> L espace disponible est trop faible pour faire une mise a jour.
>

**Comment by KiwiHC16** [comment]
Ce test donne une indication AVANT la mise a jour (et le plantage)...
Le resultat du test d'integrité est APRES.

 Les tests AVANT ne t'empeche pas de faire la mise a jour. Mais tu es au courant de potentiel soucis.

Les deux sont complémentaires.

**Comment by tcharp38** [comment]
Je clos.
Cette fonctionalité est masquée.
Pas assez fiable pour un utilisateur final.
