### ISSUE TITLE
Ampoules GU10 Philips

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1778]
https://community.jeedom.com/t/appaire-les-ampoules-gu10-philips/53355/8

**Comment by KiwiHC16** [comment]
- purger les **
- faire le modele

**Comment by KiwiHC16** [comment]
'**LWG004**'

**Comment by KiwiHC16** [comment]
retrait des ** fait.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Sujet antique, sans vie et sans details.
Je clos. A reouvrir si + d'infos.
