### ISSUE TITLE
Faire une documentation des groupes

### ISSUE THREAD

**Issue by Marc--** [KiwiHC16/Abeille#178]
Bonsoir !

La ruche propose des options pour les groupes (AddGroup, RemoveGroup, getGroupMemberShip). 

Je rencontre des problèmes de communication avec un capteur Aqara (temp/ hum carré) qui est en extérieur.

Les groupes sont-ils le moyen de créer un réseau maillé avec les capteurs, ce qui me permettrait de faire transiter le signal du capteur exterieur par un autre capteur plus proche avant d'atteindre la Zigate ?

Est-il possible de documenter la partie groupe ? Que dois-t-on entrer dans les champs "Titre" et "Message" pour créer un groupe et y associer des capteurs?

**Comment by KiwiHC16** [comment]
Salut @Marc-- ,

Il faut que je fasse une doc, il ya un tres court chapitre sur le sujet: https://github.com/KiwiHC16/Abeille/blob/caaf02675a90b030b18e16ec9e708c1d6a4b7d2c/Documentation/PhilipsHUE.asciidoc#group-control

Pour ton probleme, c'est un sujet de routage (rien a voir avec les groupes). Par defaut les "routeurs" zigbee mettent en place le reseau mesh. Les routeurs sont les equipements sous tensions permanentes en règle générale, par exemple prise 220V Xiaomi et ampoule Ikea (Cela je suis sure je les ai vu fonctionner). Dans ton cas mets une ampoule Ikea entre la ZiGate et Le capteur (dans l'ideal il faudrait qu'ils se voient les uns les autres).

La notion de group est une facon d'adresser plusieurs equipements en meme temps avec un seul message. Par exemple allumer 2 ampoules en meme temps. Premiere solution, j'envoie un message à la premiere ampoule, puis un deuxieme ampoule mais la tu n'as pas un synchro dans l allumage et si tu n'as qu'une télécommande comment faire. Donc par exemple les ampoules Ikea envoient une commande de group vers toutes les ampoules. Un appui sur la telecommande et les deux ampoules s'allument.

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-03-04 a 18 35 41](https://user-images.githubusercontent.com/8549674/36964607-7c68d41c-2057-11e8-8e03-ea918aaa448b.png)

Exemple pour un ampoule Ikea faithier sur mon système. Dans Titre c 'est l'adresse de l ampoule pour lui parler et dans message c est le groupe que l on veut definir. le endPoint est 01 pour Ikea, 03 pour Hue et 0B pour Philips si je me souviens bien.

**Comment by Marc--** [comment]
Génial, merci pour l'explication claire et précise !

Le truc dingue, c'est que j'ai déplacé ma Zigate, elle est maintenant plus proche du capteur extérieur (5m avec 2 murs parpaing, au lieu de 15m avec les même murs !)  et pourtant il ne capte plus... peut être l'environnement "perturbé" de mon armoire de brassage.

En tout cas je vais étudier cette possibilité de routeur. Il suffit de l'inclure dans le réseau Zigbee pour qu'il fasse son boulot de routage ? 

EDIT: Ok après un peu de lecture, je cherche un périphérique qui est FFD, contrairement aux petits capteurs sur batterie qui ne sont que RFD pour éco de la batterie.

Mais autant pour une prise, qui est constamment alimentée, je peux comprendre, mais pour une ampoule, il faut alors obligatoirement utiliser un interrupteur "zigbee" ? Car sinon avec un inter classique, on coupe la phase donc pas d'alimentation de l'ampoule ? Toi qui a testé ?

**Comment by KiwiHC16** [comment]
Oui

**Comment by KiwiHC16** [comment]
050_IntegrationEquipement.asciidoc
https://github.com/KiwiHC16/Abeille/blob/865cbb7606e80576a57dd5f6a3ee4f3414e5379c/Documentation/300_PhilipsHUE.asciidoc#colour-control
https://github.com/KiwiHC16/Abeille/blob/84059b1f3762153a0150ac02f887932b3a48ee4b/Documentation/200_IKEA.asciidoc#gestion-des-groupes

Voila trois chapitres sur le sujet. Donc je clos le cas.
