### ISSUE TITLE
Etat des interrupteurs Xiaomi

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1781]
@KiwiHC16 

Depuis quelques temps, peut-être depuis l'ajout de l'état 3 (appui sur les 2 boutons simultanément), le retour ou du moins le visuel n'est pas actualisé. Pour tester, c'est bien de l'avoir. Dans la vie courant peu d'intérêt, ça n'enlève rien au fonctionnement.

![image](https://user-images.githubusercontent.com/36518012/108148558-587d1400-70d1-11eb-8cbb-8687702a192b.png)

Tu peux voir que je viens d'appuyer sur le bouton 2. Heure 3;33. L'appui a été détecté. Mais je devrais avoir une croix au bout de qqs secondes. Je suis pas resté appuyé sur les boutons pour écrire .... D'ailleurs c'est 3 croix que je devrais avoir.

Tous les interrupteurs XIAOM font ça

Get-name : 

lumi.remote.b286acn01 (double, première génération)
lumi.remote.b186acn01 (simple, première génération)

Je croyais avoir des 02 mais non. #1729

J'en ai qui ne répond pas à la commande get-name mais qui est actif car il vient de déclencher un scénario. Peut-être lié à #1727 ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
"Mais je devrais avoir une croix au bout de qqs secondes."
Pourquoi quelques secondes ? Et combiens ?
L'inter change d etat quelques milli-secondes.
Pour le rendre accessible a l utilisateur c est une minute. Voir retour d etat dans la commande info en question.
Pour les scenarii, il faut declencher sur evenement de la commande info mais pas sur l'état.
Je sais ca perturbe au debut mais ca fonctionne très bien.

**Comment by mickadam29** [comment]
Au tout début lorsque j’ai commencé Jeedom et Abeille je suis certain que l’état changeait dès qu’on appuyait sur le bouton. Puis revenait à l’état initial. Je n’ai plus le temps en tête mais qqs secondes

**Comment by mickadam29** [comment]
> "Mais je devrais avoir une croix au bout de qqs secondes."
> Pourquoi quelques secondes ? Et combiens ?
> L'inter change d etat quelques milli-secondes. **Sauf à rester appuyé dessus, non ?**
> Pour le rendre accessible a l utilisateur c est une minute. Voir retour d etat dans la commande info en question.
> Pour les scenarii, il faut declencher sur evenement de la commande info mais pas sur l'état.
> Je sais ca perturbe au debut mais ca fonctionne très bien.

Les scénarios fonctionnent. Pas de soucis avec eux. Pourtant j'utilise Etat. Je vais revoir ce point là. 
![image](https://user-images.githubusercontent.com/36518012/108197022-1d530300-711a-11eb-8373-12d2aef4231b.png)
![image](https://user-images.githubusercontent.com/36518012/108197064-28a62e80-711a-11eb-98df-aaea19a71173.png)

Pour l'état des boutons tu admettras un souci, car comment peuvent-ils être vu actifs (coche) tout le temps. 

![image](https://user-images.githubusercontent.com/36518012/108197531-ce599d80-711a-11eb-92d9-11cca1f6a542.png)

A l'origine, c'est une croix en permanence, la coche lorsqu'on appuie et retour à la croix. C'est peut-être un simple souci de widget de la V4. Mais les dates de valeur et collecte semblent incohérentes. 
T'attarde pas trop là-dessus, on va dire que c'est esthétique.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-17 à 13 17 41](https://user-images.githubusercontent.com/8549674/108203262-850d4c00-7122-11eb-92b0-a5e5bdd6f911.png)

Regardes cette partie de la definition de la commande: retour etat

**Comment by mickadam29** [comment]
Je n'ai rien de renseigné
![image](https://user-images.githubusercontent.com/36518012/108210281-9c9d0280-712b-11eb-8572-457517fdb8f2.png)

**Comment by KiwiHC16** [comment]
Mets 0 dans "Valeur retour d etat"
Mets 1 dans "Durée avant retour d etat"

**Comment by mickadam29** [comment]
OK.

**Comment by mickadam29** [comment]
Ca fonctionne. Ca n'aurait pas disparu du json ? Je vais corriger mes boutons.

**Comment by mickadam29** [comment]
Et le retour à zéro (croix) se fait en 1 min. Je me rappelais pas que c'était aussi long
