### ISSUE TITLE
Remove des équipements

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1782]
@KiwiHC16 
Quelle est la procédure pour faire le ménage lorsque l'on retire des équipements ?

2 exemples 
- Un routeur HS
- Remplacement de 3 ampoules par une seule (3GU10 par 1E10/changement plafonnier).  Je peux dire que la nouvelle remplace une ancienne, mais que faire des 2 autres ?

Fonction Remove de Zigbee sur laquelle tu travailles puis remove de Abeille ? Ou l'inverse ou autre méthode ? 

L'idée c'est de virer de Zigate tout ce qui disparaît, volontairement ou pas. (Remplacement ou panne)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
- Un routeur HS
Actuellement suppression dans Abeille et normalement le reseau zigbee l oubliera au bout d'un certain temps.
Utilisation de la commande "remove" en cours de dev a venir (dispo dans la ruche)

**Comment by KiwiHC16** [comment]
- Replacement d une ampoule par une autre:
![Capture d’écran 2021-02-17 à 14 38 01](https://user-images.githubusercontent.com/8549674/108212069-bf301b00-712d-11eb-9f8e-0becf54530d7.png)

- Pour les deux autres 
- - cf HS. 
- - mettre la zigate en mode NON inclusion et faire la procedure d'inclusion au niveau de l equipement. Il devrait dans un premier temps quitter le reseau puis essayer de s inclusre dans un reseau mais ils sont tous fermés donc il n'est plus dans aucun reseau.

**Comment by mickadam29** [comment]
Merci. Je testerai. Pour le moment les ampoules sont retirées. Remplacées par des OSRAM. On verra la stabilité par rapport à l'autre issue #1727. Du coup je devrai les supprimer.

**Comment by mickadam29** [comment]
J'ai utilisé la fonction Remove de la Ruche (version @tcharp38 de ce jour)
Adresse IEEE du Parent
Adresse IEEE de l'équipement à sortir (non visible sur le réseau car pas branché)

A bien fonctionné.
Après j'ai vu le bouton Exclure fait par @tcharp38, donc pas testé. Mais en même temps, je ne pouvais pas car l'objet était déjà supprimé de Abeille.
