### ISSUE TITLE
execCmd() ... comportement attendu

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1784]
Quel est le comportement attendu d'execCmd() ?

Juste un status ?
ou le resultat reel de la commande ?

**Comment by KiwiHC16** [comment]
https://jeedom.github.io/documentation/phpdoc/classes/cmd.html#method_execCmd

**Comment by KiwiHC16** [comment]
https://github.com/jeedom/core/blob/alpha/core/class/cmd.class.php#L1056

**Comment by KiwiHC16** [comment]
Semble essayer de recuperer la valeur en cache d une commande de type info et si pas dispo utilise la commande execute() d'AbeilleCmd.Class.php qui dans notre cas ne fait rien.

Donc semble recupere la valeur d un commande info.

**Comment by tcharp38** [comment]
Il y a donc bien un souci.
Exemple... execCmd(getTime).. va pas renvoyer l'heure car la commande n'attend meme pas le resultat.

D'un point de vue general un certain nombre d'appels "execCmd()" doivent du coup donner qqch de décalé dans le temps.
A creuser

**Comment by NebzHB** [comment]
Bonjour, oui à creuser car cela pose problème à des plugins comme homebridge par exemple... la commande o2a que jeedom effectue fait un execCmd et renvoi une erreur...

**Comment by tcharp38** [comment]
@NebzHB Quel erreur as tu ?

**Comment by NebzHB** [comment]
Pas moi... déjà remarqué chez des utilisateurs homebridge (je dev ce plugin) qui avaient le plugin abeille... le symptôme c'est que si on appuie sur "tester" sur la commande dans abeille, il n'y a pas de bandeau vert qui apparaît en haut avec la valeur de la commande info.

**Comment by tcharp38** [comment]
Ok mais je pige pas le lien avec HomeBridge. Tu peux m'eclairer ?
Peut etre est ce homebridge qui utilise des commandes Abeille qui ne repondent pas ?

**Comment by KiwiHC16** [comment]
Normalement le soucis que mentionne @NebzHB est réglé depuis longtemps et la raison était qu'on envoyait du binaire dans les commandes. Cela de doit plus être le cas.

Pour le sujet de cette issue, ma compréhension de la situation est la suivante:
- Abeille demande l heure à la zigate
- AbeilleParser la recupere est l envoie à la commande ZiGate-Time: mise en cache et en db
- Ensuite on fait un execCmd() pour l affichage donc on devrait avoir l heure remontée et contenue en cache

Ces trois operations dures moins d une seconde donc doit bien récupérer l heure de la zigate. Tu dois la voir passer dans AbeilleParser si besoin avec le bon log.

En fait je ne comprends pas vraiment le soucis.

**Comment by tcharp38** [comment]
Le souci est que la sequence que tu decris demande 2 execCmd()
- l'une pour envoyer la requete à l eq
- l'autre pour la recuperer

Je doute que ce soit le comportement attendu d'un point de vue Jeedom. Enfin je ca me semble pas logique du tout.

**Comment by KiwiHC16** [comment]
2 execCmd ?
- 1 pour l’envoie 
- 1 pour la reception
Est ce t on idée ?
Si oui la première est une commande action et l autre une commande info. Elle ne fonctionne pas de la même façon. 

Je ne comprends toujours pas le soucis.

**Comment by tcharp38** [comment]
Bon je n'arrive pas à m'expliquer. Je ne comprends pas la vision "top" (jeedom).
Je vois juste qu'une commande info peut renvoyer soit rien soit un truc pas à jour, soit heureusment un truc valide. Bref... est ce en ligne avec la philosophie Jeedom ? Pas avec ma logique en tout cas.
Faut que j'avance encore dans ma comprehension globale.

Je clos ce point pour l'instant.
