### ISSUE TITLE
TeleCommande Innr n a pas de parametre groupe

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1786]

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-17 à 22 33 25](https://user-images.githubusercontent.com/8549674/108270732-28388280-7170-11eb-8aa2-762e3f308368.png)

**Comment by tcharp38** [comment]
Sauf erreur on dirait qu'il manque
      "paramType": "telecommande"
dans le JSON

**Comment by KiwiHC16** [comment]
Oui, ce cas est un pense bête pour moi pour l ajouter.

J ai aussi d'autress trucs en cours.

**Comment by KiwiHC16** [comment]
#1788

**Comment by KiwiHC16** [comment]
Fait dans master.
