### ISSUE TITLE
Ampoules Ikea, fonction Routeur?

### ISSUE THREAD

**Issue by battousai90** [KiwiHC16/Abeille#1787]
Bonjour,

Apparemment depuis Fin janvier maintenant mes ampoules Ikea n'assume plus leur fonction de routeur, ainsi les LQI s'envolent et les différentes sondes s'appairent à ce qu'elle peuvent cassant ainsi le maillage et créant des problèmes de réseau Zigbee et des timeout de périphérique.
![image](https://user-images.githubusercontent.com/47687052/108311734-d3b7f600-71b5-11eb-856b-b5a10b46b5d3.png)
![image](https://user-images.githubusercontent.com/47687052/108311781-e5010280-71b5-11eb-9f73-b22d34eb3205.png)
Version Abeille : Beta 2021-02-16 01:00:11 (d'ailleurs ca s'affiche en bas )
![image](https://user-images.githubusercontent.com/47687052/108312158-8d16cb80-71b6-11eb-9098-02439cc4394f.png)
ZIgate USB/TTL en 0.31D

**Comment by mickadam29** [comment]
Salut @battousai90 

Je profite de ton sujet pour apporter des infos. @KiwiHC16 me dira s'il faut un nouveau sujet.
Pour ma part, j'ai viré, hier, 5 de mes 6 ampoules IKEA pour les remplacer par 3 OSRAM. (les plafonniers ont été remplacés donc moins d'ampoules)
Aujourd'hui, tout fonctionne, mais cela a moins de 24H.

J'abonde en ton sens. Depuis fin janvier, avec les ampoules IKEA plus rien ne va dans le routage.
Avec les ampoules OSRAM, @KiwiHC16 m'a prévenu que le routage ne se passait pas bien.
Le graph LQI de ce matin, va dans ce sens. Je n'ai qu'une ampoule OSRAM qui passe par une prise IKEA. Tous les autres équipements, sur la base des données LQI, atteignent directement la Zigate.

Le maillage en est fortement simplifié.

![image](https://user-images.githubusercontent.com/36518012/108321398-62cc0a80-71c4-11eb-8240-a1d009f674c3.png)

Mais surtout, tout fonctionne bien et vite du coup. L'allumage des lampes est redevenu immédiat.
Même les capteurs Xiaomi de temp sur pile les plus éloignés communiquent très bien avec la zigate qui est au sous-sol (2 niveaux, 2 dalles béton). J'ai presque des doutes sur la table LQI et le graphe. Comme le dit @battousai90 il y a des LQI trop élevés pour des équipements éloignés.

En résumé, je dirai que mes ampoules nuisaient finalement plus qu'elles n'apportaient au réseau Zigbee, surtout depuis fin janvier. Je verrai comment évolue le maillage et j'ouvrirai une discussion dédiée.

Maintenant qu'est ce qui a changé à fin janvier ?? 

Bon courage à toi @battousai90 et merci @KiwiHC16 

Pour infos

1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by mickadam29** [comment]
@KiwiHC16 

J'ajoute que s'il faut, j'ai des ampoules IKEA (qui ont posé problème) et un réseau de dev (pizigate en lieu et place de Zigate USB)  pour tester des modifs si @battousai90 veut pas trop toucher à sa prod.

**Comment by KiwiHC16** [comment]
Salut à vous deux. 

Je souhaite clarifier quelques points avant de tirer des conclusions. 
- ce graph ainsi que les données LQI n est qu une représentation graphique d informations récoltées auprès des routeurs. 
- cela ne représente pas le routage effectif. 
- cela indique comment les équipements se voient les uns les autres. 
- le routage n est pas accessible à l utilisateur dans le monde Zigbee. Ça s'organise tout seul des qu'un équipement rejoin le réseau. 
- Si vous ne l avez pas deja vu, voici ma comprehension: https://kiwihc16.github.io/AbeilleDoc//Radio.html?highlight=radio

Donc Abeille n'influe en rien sur le routage. Si cela a changé fin Janvier ce n'est pas Abeille.

Maintenant il y eu une revisite de la collecte des LQI il y a quelques semaines (beaucoup plus rapide, correction bug,...) et c 'est peut être ce que vous avez vu fin janvier.

Il est possible que tout ne soient pas clean avec cette nouvelle mouture et par exemple des résultats differents entre refresh: mon experience (pas encore investigué). @tcharp38: je pense qu'il faut qu on regarde ca. J'ai peur que le flot de demandes s'atture la zigate (#1772) du fait de l acceleration (C'est pour eviter cela que ma version était lente).

Dans tous les cas cela n'explique pas l amélioration sur le réseau @mickadam29.

@battousai90, aurais tu un routeur qui repond difficilement pour qu on fasse des tests dessus ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
Merci @KiwiHC16 

Concernant le routage, je pensais, à tort, que cela était la représentation réelle du routage. Et comme tu le dis, 2 refresh ne donnent par forcément le même résultat.
Donc, mes OSRAM participent peut-être au routage. Ce qui explique que les équipements les plus éloignés voient encore la Zigate.

Pour ma part je viens de passer également à la 4.1.20 de Jeedom.
Je ne sais pas si @battousai90 peut nous indiquer à quelle date il était passé à la 4.1.19. Je vais regarder le nom de mes sauvegardes.

**Comment by mickadam29** [comment]
@KiwiHC16 

Voici une piste probable des dysfonctionnements. Le début des problèmes coïncident chez moi avec la mise à jour 4.1.19.
Si bug il y a, il faudrait creuser cela également, mais là ce n'est plus de ton ressort @KiwiHC16. Et cela ne concerne-t-il pas que les zigate USB ?
@battousai90 Il faudrait peut-être tenter le passage en 4.1.20. Rien dans le changelog.

![image](https://user-images.githubusercontent.com/36518012/108336894-cf4f0580-71d4-11eb-862a-64d14495abdd.png)

Je vous laisse poursuivre.

**Comment by mickadam29** [comment]
Le routage semble se mettre petit à petit en place. Le graphique est cohérent avec les emplacements physiques des routeurs.
Plus aucun souci en passant des ampoules IKEA à OSRAM

![image](https://user-images.githubusercontent.com/36518012/108396529-3b525d80-7217-11eb-96db-763d3c2b9244.png)

**Comment by battousai90** [comment]
Je clos le ticket
