### ISSUE TITLE
Fonction Remplace HS

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1789]
1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

En faisant un get-info, cela m'a créé un nouvel-objet. J'ai fait le get-info sur l'objet 423. Devenu inopérant. L'objet 428 fonctionne.

![image](https://user-images.githubusercontent.com/36518012/108339416-aed47a80-71d7-11eb-9ebb-f6ecc2439bc9.png)
![image](https://user-images.githubusercontent.com/36518012/108339526-d0356680-71d7-11eb-99b6-c772dcce3093.png)

Pas grave en soit, sauf que la commande Remplace plante.  @tcharp38,@kiwihc16 un bout de code que vous allez devoir changer non ?

![image](https://user-images.githubusercontent.com/36518012/108340067-784b2f80-71d8-11eb-99ee-849facb0258f.png)

![image](https://user-images.githubusercontent.com/36518012/108340143-8b5dff80-71d8-11eb-9ce5-ad7e4a3de36b.png)

**Comment by KiwiHC16** [comment]
As tu toutes tes IEEE ? (il faut qu j ajoute un test sur le sujet).

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
Oui les IEEE sont renseignées dans les 2 objets. D'ailleurs je devrai dire l'IEEE puisque c'est bien évidemment la même.
Et la page plante. (L'IEEE aurait pu être mise à jour entre temps)

**Comment by mickadam29** [comment]
Je n'ai fait pas le test avec 2 équipements "différents" et 2 donc 2 IEEE différentes.
ATTENTION : C'est le get-info qui m'a créé un nouvel objet "clône" de l'ancien. Donc si tu testes l'IEEE tu risques de dire que qq chose ne va pas car l'utilisateur veut remplacer le même objet par lui-même....

**Comment by mickadam29** [comment]
@KiwiHC16 

Je ne t'ai pas demandé du coup si c'est normal que Get Infos ait créé un nouvel objet. Probablement NON.

![image](https://user-images.githubusercontent.com/36518012/108351729-30330980-71e6-11eb-85b0-b3a1b47a408c.png)

**Comment by KiwiHC16** [comment]
@mickadam29 pour le Get Infos jouvre une issue specifique. Ce n est pas le meme code.

Peux tu tester le "Fonction Remplace HS" avec le master pour voir si maintenant c est ok pour toi ?

**Comment by mickadam29** [comment]
Je n’ai pas attendu pour faire le changement de mes équipements. Par contre j’ai encore des ampoules à virer donc je vais m’en servir pour faire le test. Après vérif j'ai aussi virer mes ampoules. Si tu n'as pas changé le code, je peux refaire le get infos et voir s'il me crée un nouvel objet. Et dans ce cas je pourrai tester le Remplace. Mais je viens d'installer une verison du master à l'instant 16h. Est-ce que le get infos a été corrigé ?

**Comment by mickadam29** [comment]
@KiwiHC16 

C'est un autre problème maintenant

J'ai reproduit ce que j'avais fait. A savoir un Get infos sur une ampoule. Cela m'a créé un nouvel objet. Du coup j'ai fait Remplacer. Le processus s'est déroulé sauf que j'ai obtenu un équipement sous ancien_nom_real. Et qui a quitté le réseau.
![image](https://user-images.githubusercontent.com/36518012/108746528-baf46b00-753c-11eb-82b6-f1fb1ab3bf9c.png)

J'ai fait le get infos sur l'objet 424. Cela m'a créé le 430. En faisant Remplace, les objets 424 et 430 ont disparu. 424 est devenu Abeille-424_real. Dans la foulée, a quitté le réseau. Abeille/Jeedom l'a désactivé. Et l'objet est KO même en le réactivant. et surtout j'ai des erreurs 500 lorsque je veux faire un ON ou OFF sur cet objet _real

![image](https://user-images.githubusercontent.com/36518012/108746845-22aab600-753d-11eb-8704-2e5ce09aca78.png)

**Comment by mickadam29** [comment]
Malgré ce code 500 l'ampoule fonctionne dans les scénarios. Donc l'objet qui portaient le nom Abeille-424_real fonctionnait. Mais avec ce code 500 je l'ai supprimé et j'ai recréé un objet en débranchant/rebranchant l'ampoule avec la zigate en inclusion.
Mais j'ai toujours ce code 500. Donc le pb de code 500 est lié à autre chose. La version Abeille, pas révélatrice, car cela fait plusieurs version qu'elle porte le même nom. Je dois être sur la master de cet AM. Installée à 16H 
Ta fonction remplace aurait parfaitement fonctionné si le nom de l'objet n'avait pas eu "_real" d'ajouté. Donc je suppose que quelque chose n'est pas allé jusqu'au bout.

1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux JEEDOM-DEBIAN 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by mickadam29** [comment]
Toutes les commandes Action génèrent un code 500 sur l'objet nouvellement créé. 
Get-name : ClassicA60Wclear-LIGHTIFY

Finalement pas lié aux changements de la fonction Remplace. Mais à la release du master

**Comment by mickadam29** [comment]
Je t'ouvre un nouvel issue

**Comment by KiwiHC16** [comment]
Que fait on avec cette issue ?

**Comment by mickadam29** [comment]
Mise à part le fait que le nom de l’objet n’était pas bon et que j’ai pas poussé les tests dû aux fait du code 500, il y a au moins un script de lancé. Tu peux fermer si tu penses que c’est bon pour toi. Peut-être que qu’un d’autre va se manifester sur un pb identique

**Comment by KiwiHC16** [comment]
Ok on clos. Si sujet revient on ouvrira une nouvelle issue.
