### ISSUE TITLE
A t on besoin de lsb-release php-pear pour l installation des dependances ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#179]

**Comment by edgd1er** [comment]
php-pear gère les modules et dépendances de php. donc c'est obligatoire.
lsb-release permet d'identifier le système. (http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/lsbrelease.html)
l'install en plus recompile un module pour l'intégrer. Vu de loin comme ça, ça me parait du de s'en passer. il faudrait analyser plus en profondeur le soucis. Malheureusement, je n'ai pas de RPi3 pour tester.

**Comment by KiwiHC16** [comment]
Obligatoire ? Pourquoi ? ce n'est pas installé par les autres plugin.
usb-release: peut ete pouvons nous avoir les memes info sans ce module. Moins on aura de truc a installer moins de problemes on aura.

**Comment by edgd1er** [comment]
Je suis d'accord avec toi, moins on en installe mieux c'est.

Les autres plugins sont en python principalement et n'utilisent pas de modules php.
Effectivement, ré-ecrire le plugin en python t'affranchit des dépendances php ;)

C'est une question que je me pose, faut il refaire le plugin en python ou se baser sur un projet déjà existant ? le démon par défaut proposé par jeedom peut lancer des threads et a une partie dediée à la lecture du port série. Mais tout cela devrait être abordé dans une autre issue.

Voila ce que j'ai compris de l'install.
- les headers des librairies mosquitto sont installées pour que pecl puissent compiler le module php mosquitto.so
- pecl se base sur https://pecl.php.net/package/Mosquitto pour lequel l'auteur indique que les dépendances sont 
PHP Version: PHP 5.3.0 or newer? PEAR Package: PEAR 1.4.0 or newer.
Pour info cette méthode est utilisée par le plugin MQTT de jeedom, mais je pense que tu le sais, car le  script en semble grandement inspiré. 
Donc pear/pecl est obligatoire sauf a vouloir se passer de ce module et donc de MQTT.

lsb-release est le plus souvent installé par défaut et utilisé pour connaitre les distribution et version afin d'ajouter les bons dêpots mosquitto qui sont spécifiques à la distribution et à la version. On peut effectivement s'en passer si on force l'install en pointant tout sur debian/jessie ou en bricolant un décodage du fichier /etc/os-release. 

Il est fort peu probable que le problème vienne de lsb-release, vu le soin que debian apporte à ses paquets. Il est plus probable que tu ais été limité par ton débit de récupération des packages. les logs /var/log/apt/* et /var/log/dpkg te permettront de voir ce qu'il s'est passé. La première install peut prendre du temps et rester longtemps sur le 30% (apt-get -y install mosquitto mosquitto-clients libmosquitto-dev). et sur un RPi3 l'install prendra plus de temps que ce tu as pu expérimenter sur ta vm.

**Comment by KiwiHC16** [comment]
Ok, quand on aura un plugin qui a toutes les fonctions que l on veut on pourra porter mais pour l'instant je me focalie sur les fonctions. Un portage peut être très long.

**Comment by KiwiHC16** [comment]
La conclusion de cet "issue" est Oui nous avons besoin de ces packages donc je clos le sujet.
