### ISSUE TITLE
Verifier le fonctionnement du get LQI

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1790]
Probablement en relation to #1772

**Comment by KiwiHC16** [comment]
Et avec: #1659

**Comment by tcharp38** [comment]
Quel souci avec la collecte LQI ?

**Comment by KiwiHC16** [comment]
Experience utilisateur: resultat pas consistant d une requete a l autre.
Mais techniquement je ne sais pas si il y a vraiment quelque chose et si oui qui.
Je vais regarder si  qu'un perception ou si je trouve un vrai soucis.

**Comment by tcharp38** [comment]
Pour info j'ai poussé recemment une modif du parser (message 804E).

Avant cette modif, tout eq INCONNU qui passait par la declenchait une interrogation et potentiellement un blocage des messages.
Comme la collecte LQI utilise un timeout, ces interrogations pouvaient donner un resultat inconsistent.

La modif bloque ces interrogations avec ton option avancée "Blocage recuperation equipement" sur OUI.

**Comment by tcharp38** [comment]
Je confirme des comportements bizarres sur le master.

**Comment by tcharp38** [comment]
Autre amélioration de la collecte LQI (commit https://github.com/KiwiHC16/Abeille/pull/1796/commits/dbcf7273a919151029eae054e6c9fc8aa8e2e774)

- Flush de la queue (parser>lqi) au démarrage
- Ignore les messages redondants (Abeille peut generer de multiples requetes identiques qui entrainent plusieurs reponses 804E aussi identiques mais renvoyées vers LQI)

**Comment by KiwiHC16** [comment]
Semble ok sur le master.
Je clos.
