### ISSUE TITLE
Equipement injoignable = Plantages

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1791]
@KiwiHC16 

Pour rebondir sur les anomalies du réseau, connues avec les ampoules IKEA, je viens de constater que l'action sur un objet injoignable rendait le réseau un peu bancale.
En référence à l'issue #1789, j'avais laissé volontairement l'ancien objet dans mon scénario. J'ai ajouté le nouvel objet en attendant que la fonction Remplace fonctionne à nouveau. Ces objets étant tous les 2 la même ampoule OSRAM.
Le scénario est actionné par l'appui sur un interrupteur. Donc, il a tenté d'allumer 2 ampoules (en fait la même)

![image](https://user-images.githubusercontent.com/36518012/108353831-e13aa380-71e8-11eb-9683-1a75253af8bb.png)

Et là ca commence à ne plus bien fonctionner. J'appui sur d'autres interrupteurs pour commander d'autres lampes, rien ne se passe.  Aucune action (scénario) n'aboutit. Je patiente qqs dizaines de secondes. Tout revient dans l'ordre. 
Tant que je ne déclenche pas d'actions à destination de l'objet qui n'est pas joignable sur le réseau tout fonctionne bien.
Je désactive l'objet du scénario.

![image](https://user-images.githubusercontent.com/36518012/108354444-bdc42880-71e9-11eb-802d-66c12f1bf597.png)

Je peux à nouveau utiliser mon interrupteur, la lampe réagit instantanément, les autres interrupteurs déclenchent instantanément les autres ampoules.
C'est flagrant et reproductible.

Donc je ne suis plus étonné du bazar rencontré lorsque les ampoules IKEA se faisaient la malle. 
Tous les essais pour les allumer/les éteindre se soldaient par un blocage temporaire. Multiplié par le nombre d'ampoules injoignables ..... et les tentatives pour agir dessus. 

Il faudrait découvrir ce qui se passe, à tous les niveaux, en particulier Jeedom et Zigate, lorsqu'une trame Zigate est à destination d'un objet injoignable.
@KiwiHC16 

Quels logs pourraient aider ?

**Comment by mickadam29** [comment]
Je viens de reproduire avec un SonOFF BASICZBR3 (relais) qui fait office de routeur (comme les ampoules IKEA). 
1) Je le débranche du secteur
2) Je tente  d'agir dessus avec un scénario (ko évidemment) via un interrupteur
2) Dans la foulée, je veux allumer un lampe, avec un autre interrupteur, il ne se passe rien.
3) Attendre
4) Je tente ma lampe, ça fonctionne
5) Je refais sur l'action à destination du Sonoff
6) Je plante à nouveau la lampe

Donc un ou plusieurs routeurs capricieux (comme les ampoules IKEA) et on se retrouve avec plus rien qui fonctionne si on les sollicite. Evidemment, une ampoule, de nuit, ca s'allume.... Comme cela se produit avec plusieurs routeurs, j'imagine que c'est pas le temps que le maillage se refasse  que j'ai ces problèmes de communication.


Je n'ai pas l'explication du pourquoi les ampoules devenaient injoignables, mais je comprends maintenant la pagaille occasionnée.

@KiwiHC16 Tu devrais pouvoir reproduire ça chez toi en virant un routeur (prise ou ampoule) et tu lances des actions ON/OFF dessus. L'idée c'est que la trame ne parvienne à personne. Tu devrais voir que d'autres objets vont devenir incontrôlables pendant qqs temps.

Et en passant, je n'ai visiblement plus de problèmes, depuis que j'ai viré les ampoules IKEA. Tout est d'une fluidité.... Que du bonheur. Le retour d'état d'une ampoule (OFF-ON) se fait en 1 seconde sur le dashboard contre plusieurs juqu'à hier.

**Comment by KiwiHC16** [comment]
Il y a une gestion des messages dans Abeille pour limiter ce phénomène.
Dans tous les cas si un équipement ne répond pas il va mettre la pagaille. C est pour cela que dans Abeille il y a toutes les solutions que je trouvé possible pour les detecter et permettre a l utilisateur des prendre des actions pour avoir un réseau sain.
Ce qui est sure est que le zigbee génère des routeurs qui sont éteins puis rallumés électriquement mais le réseau demande du temps pour se remettre de ces événements. Par exemple ton plafonnier il faut éteindre les ampoules par zigbee (télécommande) et surtout pas avec l ancien interrupteur du mur.
J ai aussi l issue #1772 qui devrait permettre de detecter des soucis et d améliorer la gestion des messages en attente.
Je crée une issue pour la partie gestion de queue: #1795

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Je reproduit le phénomène. Je vais voir si on peut le reduire.

**Comment by KiwiHC16** [comment]
```
Type=8702/APS Data Confirm Fail
```

**Comment by KiwiHC16** [comment]
```
[2021-02-18 16:35:22][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=CF, PacketType=0092
[2021-02-18 16:35:22][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=32A6, SQN=B6
[2021-02-18 16:35:25][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=D0, PacketType=0100
[2021-02-18 16:35:25][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=32A6, SQN=B7
[2021-02-18 16:35:26][debug] Abeille1, Type=8000/Status, Status=14/Status 14 inconnu, SQN=00, PacketType=0100
[2021-02-18 16:35:27][debug] Abeille1, Type=8000/Status, Status=14/Status 14 inconnu, SQN=00, PacketType=0100
[2021-02-18 16:35:28][debug] Abeille1, Type=8000/Status, Status=14/Status 14 inconnu, SQN=00, PacketType=0100
[2021-02-18 16:35:28][debug] Abeille1, Type=8011/APS data ACK, Status=A7, DestAddr=32A6, DestEP=01, ClustId=0006
[2021-02-18 16:35:31][debug] Abeille1, Type=8011/APS data ACK, Status=A7, DestAddr=32A6, DestEP=01, ClustId=0006
[2021-02-18 16:35:32][debug] Abeille1, Type=8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=D0 (ZPS_NWK_ENUM_ROUTE_DISCOVERY_FAILED->Attempt at route discovery has failed due to any reason except lack of table space), Addr=32A6
```

**Comment by KiwiHC16** [comment]
10s par commande si ne parvient pas a joindre....

**Comment by mickadam29** [comment]
@KiwiHC16 

Tout d'abord merci à toi pour ton investissement.

J'ai bien compris depuis longtemps, par expérience, que les équipements de type "routeurs" devaient être alimentés en permanence et ne pas quitter le réseau. C'est pourquoi, toutes mes ampoules Zigbee sont alimentées en direct et leurs interrupteurs "mécaniques" remplacés par des Xiaomi sur pile.

Comme tu as pu le voir, si l'un d'eux est injoignable, on a un phénomène de blocage sur l'ensemble du réseau et donc des équipements. Dans mon cas, c'était au moins 5 de mes 6 ampoules qui, pour je ne sais quelle raison, semblaient quitter le réseau. Du moins plus aucune comm. Elles passaient en timeout. Mais vu le bazar, je pense qu'elles étaient hors réseau/fonction routage. Pourtant le get-name fonctionnait. Donc, potentiellement, quasi 50% de mes routeurs injoignables.

Chaque interrupteur envoyait une trame "perdue" chaque fois que je tentais d'en allumer une et provoquait visiblement ce temps de 10" sans action possible ailleurs. Ca explique le fait que des équipements autres que les ampoules IKEA dysfonctionnaient seulement après avoir tenté d'allumer/éteindre une ampoule IKEA. Je pense que @battousai90 a le même comportement.

Depuis que j'ai viré 5 de mes 6 ampoules IKEA tout fonctionne. Encore ce matin. Donc les ampoules participaient aux dysfonctionnements. Fonctionnaient très bien avec les télécommandes Hue ou virtuelles . Mais fallait surtout pas les appeler dans des scénarios. Scénarios pris en compte par la gestion des interrupteurs Xiaomi.

Reste à savoir ce qui a mis la pagaille sur les ampoules IKEA depuis début février. Car, je me répète, mais le seul fait d'avoir remplacé des IKEA par des OSRAM a tout rétabli. Peut-être que si j'avais racheté des IKEA ça aurait fonctionné aussi. Une, est peut-être défaillante niveau Zigbee. Mais la soudaineté avec @battousai90 me fait pencher pour un autre souci.

**Comment by KiwiHC16** [comment]
Je viens de trouver un scenario possible. Utilisez vous des:
- setLevelGroup ?
- setColourGroup ?
- OnOffGroupTimed ?
- setTemperatureGroup ?

**Comment by mickadam29** [comment]
Chez moi, non.
Setlevel et temp oui mais individuellement, getlevel, getetat dans des scénarios
D'ailleurs si j'avais conservé mon plafonnier 3 ampoules je comptais le piloter par le groupe. Mais maintenant on oublie

**Comment by battousai90** [comment]
De mon coté je n'utilise aucun Scénario.
J'ai des switch Ikea carré ON/OFF que je lie avec les group Zigbee aux ampoules.

**Comment by KiwiHC16** [comment]
@battousai90 utilises tu des groupes depuis Abeille ? 
En utilisant les telecommandes dans abeille par exmeple ?

**Comment by KiwiHC16** [comment]
Avec cette modification cela devrait aider.
Test proposé par @mickadam29 le temps de reaction est maintenant de 5s environ sur le sonoff qui fonctionne alors que l ampoule HS a plus de 50 commandes en attentes.  
De toute facon ce n est pas le fonctionnement  nominal mais un mode degradé du fait d un probleme.
Je vais aussi ajouter dans santé une info pour identifier les equipements qui posent problemes.

**Comment by mickadam29** [comment]
@KiwiHC16 @battousai90 

Merci pour le taf. Ca ne pourra qu'améliorer. Le souci c'est que les ampoules ne répondent plus tant qu'on ne les a pas débranchées et rebranchées. Donc toute action qui leur sera adressée mettra le bazar. Peut-être qu'en les désactivant, comme le fait jeedom au bout des plusieurs timeout permettrait de maintenir opérationnel le reste de la domotique. Car c'est, je pense, indispensable.
Sur un second point @battousai90 je t'invite à utiliser une télécommande virtuelle. As tu testé ?  Chez moi cela fonctionnait tout le temps même quand toutes mes ampoules étaient down. On pourrait imaginer le temps de trouver le problème et la solution que tes carré Ikea appellent des télécommandes virtuelles au travers de scénarios. Bien évidemment, ce n'est qu'un palliatif.

**Comment by battousai90** [comment]
Ce matin 2 ampoules et un panneau LED Ikea down.
Afficher en timeout dans l'interface
![image](https://user-images.githubusercontent.com/47687052/108587626-0f3cf680-7355-11eb-8df1-32fc411c4718.png)
J'appuie sur on OFF ca répond plus.
Appuis sur ON su Switch Carré IKEA elle s'allume, le sitwh IKEA est appairé au lumière avec les groupe Zigbee abeille.
Depuis l'interface elles apparaissent toujours en timeout et ne répondent toujours pas.
Le réseau zigbee a l'air de fonctionner.
[AbeilleLogs-210220.tar.gz](https://github.com/KiwiHC16/Abeille/files/6014360/AbeilleLogs-210220.tar.gz)

En parallèle j'ai dégager la moitie des périphérique (tout l'étage) de Jeedom et Zigate pour Conbee avec Deconz et aucun problème depuis 1 semaine. La différence et que c'est pas Jeedom, c'est home assistant derrière car j'avais pas envie de payer encore 6 euros pour le plugin jeedom.
Du coup j'ai presque envie de porter la faute a Jeedom. Ce matin mon module zwave qubino n'a pas allumé mon sèche serviette, rien d'anormal mais plus rien réponds, je redémarre Jeedom ca remarche.

**Comment by mickadam29** [comment]
@battousai90. Tjs un peu de galère à ce que je lis

Pourquoi veux tu repayer pour Jeedom ? Les achats ne se font qu'une fois. Tout est acquis et pour le nombre d'installation que tu souhaites. Je me trompe peut-être. Mais j'ai 2 jeedom, et j'installe sur les 2 les plugins achetés une fois.
Es-tu passé en 4.1.20 de Jeedom ? Je n'ai plus de soucis depuis que j'ai viré 5 de mes 6 ampoules IKEA (la 6ème est dans un globe à l'extérieur. coup de chance elle pose pas de problème) mais aussi passage de Jeedom 4.1.19 à 4.1.20 et suivi des versions Master d'Abeille. As-tu tenté une télécommande virtuelle ? Tu parles de groupes, chez moi lorsque j'étais dans ta situation, seules les télécommandes pilotaient les ampoules. Tu peux en créer une virtuelle depuis la ruche. Et comme toi, elles étaient pourtant en timeout. Rien ne fonctionnait d'autre. Ni scénario, ni commande on,off,toggle de l'objet.

Bon courage

**Comment by battousai90** [comment]
Les 6€ c'est pour le plugin Deconz.
Après je vais pas étaler mes opinion Jeedom sur le GIT Abeille, c'est pas l'endroit.
Pour les interrupteur virtuel je ne vois pas l'interet de faire ca car avec les Switch IKEA dans le même groupe ca marche, ca prouve que c'est pas Zigbee mais la couche logiciel Jeedom.

**Comment by KiwiHC16** [comment]
AbeilleCmd.log
```
[2021-02-20 08:30:19][debug] Je n'ai pas de Ack (Status) depuis 1 secondes avec now = 1613806219 et timeLastAck = 1613806218 donc je considère la zigate dispo.....
```
Ce n est pas normal. Quelque chose ne fonctionne pas comme attendu. La zigate ne répond pas aux demandes.

AbeilleParser.log
```
[2021-02-20 08:30:17][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=6077, SQN=16
[2021-02-20 08:30:17][debug] Abeille1, Type=8000/Status, Status=15/Status 15 inconnu, SQN=9C, PacketType=0100
```
=> does not have a route available 

Ce qui veut dire que la zigate ne peut joindre l equipement.

Donc il semble qu'il y a un soucis zigbee entre la zigate et l equipement qui n existe pas entre la télécommande et l equipement.

regardes la note ici: https://kiwihc16.github.io/AbeilleDoc//Groups.html?highlight=group#intro

**Comment by mickadam29** [comment]
@KiwiHC16 

Ton dernier message s'adressait à moi ou à @battousai90  ?
Depuis que j'ai viré mes Ikea la situation est très stable. Un ou 2 équipement à réinclure, dont une prise Ikea qui fait office de commande d'un plafonnier
Pour moi le sujet peut être clos. Je saurai qu'un équipement injoignable met la grouille. J'en suis toujours à 10 sec plutôt que 5 avant de pouvoir renvoyer une commande

**Comment by KiwiHC16** [comment]
A @battousai90 je pense car le log vient de lui.

**Comment by battousai90** [comment]
Bonsoir,

J'ai acheter un passerelle IKEA sur leboncoin a 10€ et associer tous mes périphériques IKEA à cette passerelle, depuis plus de soucis. En plus la passerelle a mis à jour chaque firmware des périphériques.
C'est dommage de finir comme ça, mais apparement on est les seuls à avoir des soucis, ou bien les seuls qui voulions persister avec la zigate.
Voilà pour moi c'est clos.

**Comment by mickadam29** [comment]
@battousai90 
Tu me confortes dans l'idée qu'il est nécessaire de mettre à jour les équipements. Je pensais faire un OTA sur mes ampoules. J'avais évoqué le sujet avec @KiwiHC16. Mais ca semble pas évident avec la zigate. Maintenant, est-ce la passerelle qui a solutionné ou la mise à jour ? Peux-tu m'en dire plus STP ? Ce qui est embêtant c'est de devoir s'équiper d'une passerelle Ikea, une Xiaomi, une SonOff, une Lidl et j'en passe. Le cercle des participants est restreint. Comment font les autres ? Ils subissent ou nous sommes qu'une poignée à utiliser Jeedom / Zigate  / Abeille ......

**Comment by mickadam29** [comment]
@KiwiHC16 

On clos le ticket ?

**Comment by KiwiHC16** [comment]
Ok
