### ISSUE TITLE
Ajouter un bouton a chaque device avec la fonction execAtCreationCmdForOneNE() pour reconfigurer un device si besoin

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1794]

**Comment by KiwiHC16** [comment]
Pour tester:

```
php AbeilleTest.php 320 "Abeille1/4319"
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Reconfigurer un device qui "n'ecoute pas" est juste.. hasardeux.
Il faudrait gerer
- l'attente que le device est reveillé pour lui envoyer les ordres de config (bind + setReport)
- les codes retours comme "configure reporting response" pour etre sur que ca s'est bien passé.
Une reinclusion n'est elle pas plus rapide et + fiable ?

**Comment by tcharp38** [comment]
210708-BETA-1
Bouton "reconfigurer" dans la page EQ/avancé

![image](https://user-images.githubusercontent.com/35221038/124954944-e9b83d00-e016-11eb-8524-a12c5a95b3a2.png)

**Comment by tcharp38** [comment]
Je clos car je pense que ca répond au sujet.
A reouvrir si ca n'est pas le cas.
