### ISSUE TITLE
Abeille::execute() log are not produced. Can t see them. Should be in AbeilleCmd log.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1797]
J ai dupliqué les log pour les avoir en attendant dans le log Abeille.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
La fonction execute() est appelée d'ailleurs qu'AbeilleCmd ?

**Comment by KiwiHC16** [comment]
Quand tu fais tester sur une commande c est cette commande qui est appelé. 
pour abeille c est uniquement les commandes action qui sont traitées.

**Comment by KiwiHC16** [comment]
Semble fonctionner. Merci.
Je clos.
