### ISSUE TITLE
Refresh LQI, bug ?

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1798]
@KiwiHC16 @tcharp38 

Un petit souci ou tu es sur le sujet ? Si DEV en cours, laisse tomber et clos. Merci

La dernière release du master ne remonte que les endpoints rattachés directement à la zigate.
Aucun routeur.

![image](https://user-images.githubusercontent.com/36518012/108530548-ffca9880-72d5-11eb-887c-c9f6ea4fd0c7.png)

Les LQI semblent en phase avec la distance, situation Zigate  / EndDevice

![image](https://user-images.githubusercontent.com/36518012/108530679-22f54800-72d6-11eb-88f2-0149d4eff27c.png)

Ce qui est en OK dans Repond sont des routeurs. 

![image](https://user-images.githubusercontent.com/36518012/108530802-48825180-72d6-11eb-8cb3-f3f17413674d.png)

**Comment by tcharp38** [comment]
Tu est en ligne avec le master depuis quand ? Juste pour etre sur que tu as les dernieres modifs

**Comment by mickadam29** [comment]
Juste avant 17h
J'ai mis à jour

**Comment by tcharp38** [comment]
Bon je ne vois pas de pb particulier malheureusement :(
Du coup j'ai besoin de ton aide.
- vide les logs parser & cmd
- lance un refresh LQI
- et file moi les logs parser + cmd + AbeilleLQI
Merci

D'ailleurs je sais pas à quoi sert ce "Repond" :) Je découvre.

**Comment by mickadam29** [comment]
@tcharp38 

Voici ce que tu m'as demandé. Pas vu de log AbeilleLQI

[AbeilleParser (15).log](https://github.com/KiwiHC16/Abeille/files/6014415/AbeilleParser.15.log)
[AbeilleCmd (2).log](https://github.com/KiwiHC16/Abeille/files/6014416/AbeilleCmd.2.log)
![image](https://user-images.githubusercontent.com/36518012/108589090-f6d0da00-735c-11eb-8537-5ee7a38c7aff.png)
![image](https://user-images.githubusercontent.com/36518012/108589102-00f2d880-735d-11eb-9f07-a6fd9ae07010.png)

**Comment by tcharp38** [comment]
Merci je regarde. 
Le log AbeilleLQI est interne, donc accessible que depuis la page support.

**Comment by tcharp38** [comment]
L'interrogation s arrete au 10iem eq dans ton cas et je vois pas pourquoi.
AbeilleLQI me donnera l info j espere.

**Comment by mickadam29** [comment]
OK
Voici le log

[AbeilleLQI.log](https://github.com/KiwiHC16/Abeille/files/6014853/AbeilleLQI.log)

**Comment by tcharp38** [comment]
Effectivement, au moins 1 bug.
Peux tu essayer avec la version attachée ? (a decompresser dans core/php)
Tu dois etre aligné sur le master du jour vu que les dernieres mises à jour datent apres minuit hier.

[AbeilleLQI.zip](https://github.com/KiwiHC16/Abeille/files/6014997/AbeilleLQI.zip)

**Comment by mickadam29** [comment]
Ok, je te fais ça

**Comment by mickadam29** [comment]
Ca fonctionne mais du coup je suis revenu à l'ancienne version sans la colonne "Repond"

**Comment by mickadam29** [comment]
Toujours ces foutus fantômes ! Des objets inclus mais retirés depuis. Par exemple, j'ai viré mes ampoules IKEA (Abeille-424) et lorsque je l'ai remise sous tension pour l'exclure définitivement, elle s'est réinscrite alors que la Zigate n'était pas en inclusion.
Il faudrait clarifier ça @KiwiHC16 @tcharp38, comment empêcher un équipement quel qu'il soit de revenir sans que l'utilisateur l'y invite ? Je comprends que certains équipements sortent et reviennent sur le réseau, donc il faut que ce soit possible. Mais pour ceux qu'on ne veut plus c'est pénible. D'autant que maintenant, comment le supprimer ? Il n'est pas dans Abeille, je n'ai pas son parent ni son IEEE. Du moins, je ne crois pas, j'ai pas vérifier tous ces points.

![image](https://user-images.githubusercontent.com/36518012/108603168-a4b4a680-73a6-11eb-8774-52e7c364786f.png)

**Comment by mickadam29** [comment]
> Effectivement, au moins 1 bug.
> Peux tu essayer avec la version attachée ? (a decompresser dans core/php)
> Tu dois etre aligné sur le master du jour vu que les dernieres mises à jour datent apres minuit hier.
> 
> [AbeilleLQI.zip](https://github.com/KiwiHC16/Abeille/files/6014997/AbeilleLQI.zip)

J'ai fait effectivement une mise à jour ce matin

**Comment by tcharp38** [comment]
> Ca fonctionne mais du coup je suis revenu à l'ancienne version sans la colonne "Repond"

Pourquoi revenir à une ancienne version ?

**Comment by tcharp38** [comment]
> Toujours ces foutus fantômes ! Des objets inclus mais retirés depuis. Par exemple, j'ai viré mes ampoules IKEA (Abeille-424) et lorsque je l'ai remise sous tension pour l'exclure définitivement, elle s'est réinscrite alors que la Zigate n'était pas en inclusion.
> Il faudrait clarifier ça @KiwiHC16 @tcharp38, comment empêcher un équipement quel qu'il soit de revenir sans que l'utilisateur l'y invite ? Je comprends que certains équipements sortent et reviennent sur le réseau, donc il faut que ce soit possible. Mais pour ceux qu'on ne veut plus c'est pénible. D'autant que maintenant, comment le supprimer ? Il n'est pas dans Abeille, je n'ai pas son parent ni son IEEE. Du moins, je ne crois pas, j'ai pas vérifier tous ces points.
> 

Si un eq revient ou est toujours la c'est qu'il n'est pas exclu du reseau. Une fois exclu c'est imporssible qu'il revienne.
Bref on en revient à l'exclusion d'un eq du reseau.

Les 2 eq en timeout tu les as viré de Jeedom ?

Par contre

**Comment by mickadam29** [comment]
Pour l'un oui c'est certain. J'ai remplacé des ampoules ikea (la 424)  par des Osram. Comme j'ai pas forcément fais les choses dans l'ordre, l'ampoule Ikea n'a quitté ni Abeille, ni Zigate. Je l'ai rebranchée pour faire le leave ( 6 on/off consécutifs) mais avant elle a réussi à se réinscrire. Mais maintenant qu'elle a quitté le réseau .... L'autre il faut que je vérifie

**Comment by tcharp38** [comment]
Si un EQ quitte reellement le reseau je m'attends à ce qu'Abeille s'en apercoive et dise "xxx a quitté le reseau". Je crois que ce message est toujours la.

Sinon ce timeout d'AbeilleLQI pose des soucis ? Il manque des equipements ?

**Comment by mickadam29** [comment]
Pas de timeout. Un maillage particulier. Tous les équipements, hormis 2, atteindraient la Zigate sans passer par des routeurs. @KiwiHC16 
 m'a dit que c'est pas une représentation physique et réelle du maillage. Tout fonctionne, c'est le principal. C'est le jour et la nuit depuis que j'ai viré mes ampoules IKEA.
![image](https://user-images.githubusercontent.com/36518012/108607778-cd4a9980-73c2-11eb-94f5-f98e0466282f.png)

**Comment by tcharp38** [comment]
Donc tu es revenu sur une situation stable. Tant mieux.

Mais revenant sur la collecte LQI, consideres tu que lorsqu'il y avait des timeouts le resultats LQI etait faux ?

**Comment by mickadam29** [comment]
Très certainement, j'avais de mémoire énormément de LQI à 255. Donc on peut douter des résultats de l'époque. Depuis le remplacement de mes ampoules, mercredi, le retour d'état des équipements étaient parfaits. Depuis hier, à nouveau des timeout. Mais ne concerne que 2 équipements. Un interrupteur Xiaomi. Et un capteur de présence Sonoff. A suivre.

Penses-tu que cette fonction de collecte puisse apporter un quelconque soucis ? Comme @battoussai90, les équipements fonctionnaient la journée après avoir remis en service les routeurs. Puis le lendemain matin, c'était à nouveau KO. Comme il y a une requête LQI toutes les nuits, je me pose la question d'un lien.

**Comment by tcharp38** [comment]
Je vois 2 points

1. La collecte LQI reporte des resultats faux (affichage table des liens ou graph des liens). Je considere ce point maintenant clos depuis ma modif d'hier. Tu me corriges pas d'accord avec ca et si pas d'accord quel erreur vois tu.
2. La collecte LQI provoque la pagaille apres son execution. C est ce que tu sembles dire. J'ai déja eu ca il y a un bail mais depuis on a stoppé les interrogations des eq inconnus. D'autre part forcée ou executée auto, elle fait la meme chose. Donc si pas de timeouts apres son execution forcée, alors pas coupable. Maintenant si tu veux tu peux la desactiver par une petite modif de code pour voir si le lendemain tu as a nouveau des eq en timeout. DIs moi si tu veux tester ca.

**Comment by mickadam29** [comment]
Je garde la solution de désactivation sous le coude. Le souci qu'il peut y avoir, c'est que le timeout se déclenche 60 min après la collecte. Temps par défaut pour beaucoup. Et une collecte LQI remet ce compteur à zéro.
Pour l'équipement d'hier, c'est peut-être ça. 
J'ai changé le AbeilleLQI en début de soirée. Lancé manuellement pour tester. En soirée, le détecteur de présence a signalé le passage mais n'est pas revenu à l'état d'attente. Il indiquait tjs un passage récent ce matin. Pas cohérent.
Donc la collecte manuelle a peut-être planté également. 
Si j'ai de nouveau des timeout je te demanderai le bout de code pour totalement virer ça et voir le comportement. Comme je te le disais, j'ai depuis 2j des équipements inconnus qui sont revenus. C'est peut-être leur "présence" qui induit des problèmes.

**Comment by mickadam29** [comment]
Je viens de lancer une collecte. Je vais surveiller cet AM, et surtout d'ici une heure si des timeout apparaissent.

**Comment by mickadam29** [comment]
J'ai installé une version master ce matin. Je ne vois pas d'inconnu dans AbeilleLQI
Visiblement un souci au moment d'interroger l'équipement 243. Il est sur le réseau, connu par Jeedom
C'est un relais Sonoff. Il fonctionne très bien sur ses commandes on,off,toggle. C'est peut-être un de ses enfants qui cause le plantage. Mais du coup qui ?

Zigate 1: progression 8/11
[2021-02-21 11:23:02] Interrogation de 'Abeille1-243' (389A)
[2021-02-21 11:23:02] msgToCmd: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/Ruche\/Management_LQI_request","payload":"address=389A&StartIndex=00"}}
[2021-02-21 11:23:02] msgFromParser(eqIndex=8)
[2021-02-21 11:23:12]   Time-out !
[2021-02-21 11:23:12] Time-out => Abandon de l'interrogation de 'Abeille1-243' (389A).

[AbeilleLQI (1).log](https://github.com/KiwiHC16/Abeille/files/6017520/AbeilleLQI.1.log)

**Comment by mickadam29** [comment]
Pas de timeout pour le moment. On verra demain matin. Laissons passer la nuit

**Comment by tcharp38** [comment]
Concernant ton dernier log, juste pour info.
Il y  a une interrogation à 11:23:02 ([2021-02-21 11:23:02] msgToCmd)
Et aucune reponse dans les 10sec qui suivent. C'est hyper long.

Si tu retombes sur ce comportement, il faudrait
- AbeilleCmd.log pour s'assurer que la commande d'interrogation est bien envoyée à l'eq
- AbeilleParser.log pour suivre les reponses à partir de ce moment
- et bien sur AbeilleLQI.log pour voir comment le detail des eq interroges et les reponses associées

**Comment by mickadam29** [comment]
@tcharp38 

Ok, pour les logs, faudra que j'y pense.
Ce matin, aucun équipement en timeout. Si ce n'est mon capteur de temp avec afficheur, mais ca c'est connu et un bouton de scénario ON/OFF. Je vais regarder le log déposé du coup pour te dire si l'équipement dont tu parles est l'un d'eux.

**Comment by mickadam29** [comment]
> > Ca fonctionne mais du coup je suis revenu à l'ancienne version sans la colonne "Repond"
> 
> Pourquoi revenir à une ancienne version ?

Je croyais, lorsque je t'ai dit ça. Sauf que la colonne repond c'est dans la page santé pas network list.

**Comment by mickadam29** [comment]
@tcharp38 

Pourrais-tu m'indiquer comme désactiver temporairement les collecteLQI automatiques ? Ce matin j'ai encore des équipements en timeout. Ce qui m'étonne c'est que cela ne se passe en journée. Il y a moins d'activité sur le réseau zigbee puisque tout le mode dort, ce qui pourrait expliquer que certains équipements se mettent en veille mais j'aimerai aussi écarter cette piste de CollectLqi.  Je te ferai un retour sur pls jours

**Comment by mickadam29** [comment]
Je viens de lancer la collecte
Confirme que ma prise est hors réseau.
Elle est à 2m de la zigate. Du mal à croire qu'elle ne parvienne à la joindre.
Je crois plutôt qu'elle a quitté le réseau ou qu'on l'a sorti du réseau. @tcharp38  @KiwiHC16 Vous n'aviez pas mis un log "xxx a quitté le réseau" ? 
Je vais devoir déconnecter cette prise pour que ça reparte. Et peut-être faire une inclusion. Je vous dirai, je dois filer au taf


[2021-02-23 07:58:33] Interrogation de 'Abeille1-239' (30B1)
[2021-02-23 07:58:33] msgToCmd: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/Ruche\/Management_LQI_request","payload":"address=30B1&StartIndex=00"}}
[2021-02-23 07:58:33] msgFromParser(eqIndex=8)
[2021-02-23 07:58:43]   Time-out !
[2021-02-23 07:58:43] Time-out => Abandon de l'interrogation de 'Abeille1-239' (30B1).

**Comment by tcharp38** [comment]
Salut @mickadam29 
Tu as le log parser par hasard ?

Pour désactiver la collecte LQI (désolé aucune option prévue pour ca car pas normal), faut modifier le code.
- ouvres **core/class/Abeille.class.php**
- dans **function cronDaily()**
- commente **exec($cmd);**

Ca empechera la collecte  de la nuit mais ca ne t'empeche pas de la declencher manuellement.

**Comment by mickadam29** [comment]
Ok

Normal. Je teste et comme ça je saurai enfin si c’est ça qui bloque les équipements la nuit.
Quel est le but de cette collecte ? 
Lorsqu’elle est faite, elle remet à zéro le timeout puisqu’elle inscrit l’heure de collecte dans l’heure de dernière communication. Ce qui est totalement incohérent puisque l’équipement n’est pas joignable. La preuve c’est que le log te dit timeout ! Abandon 
Donc il y a probablement une coquille dans le code. Il ne faudrait pas mettre à jour l’heure si l’équipement n’a pas été interrogé.

Reste à comprendre pourquoi un équipement quitte le réseau. Je dois inclure à nouveau ma prise IKEA (encore Ikea) car une mise hors tension / sous tension ne suffit pas à remettre opérationnel l’objet.

Pour le log parser je peux t’en générer un.
Tu veux le log immédiatement après une collecte LQI ?

**Comment by tcharp38** [comment]
> Quel est le but de cette collecte ?

Recuperer des infos specifiques reseau dont le LQI. Avoir une vue d'ensemble.

> Lorsqu’elle est faite, elle remet à zéro le timeout puisqu’elle inscrit l’heure de collecte dans l’heure de dernière communication. Ce qui est totalement incohérent puisque l’équipement n’est pas joignable. La preuve c’est que le log te dit timeout ! Abandon
> Donc il y a probablement une coquille dans le code. Il ne faudrait pas mettre à jour l’heure si l’équipement n’a pas été interrogé.
> 
Si un eq interrogé (donc un routeur exclusivement) repond alors oui ca impacte son timeout car on a eu une reponse.
Mais tu as raison, son timeout ne doit pas changer si ce dernier n'a pas repondu.
Je vais voir si je trouve qqch mais #1816

> Pour le log parser je peux t’en générer un.
> Tu veux le log immédiatement après une collecte LQI ?

Le log parser est important PENDANT la collecte pour voir un peu ce qui remonte et s'assurer que c'est bien interprété.
Donc à récuperer juste apres par ex. Ou peut etre par chance il est toujours dispo qq heures + tard mais aligner les heures derniere requete LQI et messages parser associés.

**Comment by mickadam29** [comment]
Dès que j'ai un timeout je relance une collecte et récupère le log parser
Je crois même que les équipements sur pile sont mis à jour. Donc ce serait encore plus incohérent. Car au moment de la collecte, il sont supposé ne pas être réveillé. 
D'ailleurs, ce n'est peut-être pas la peine d'attendre un timeout. Je lance une collecte pour vérifier les heures des équipements sur pile.

**Comment by tcharp38** [comment]
La collecte ne doit interroger que des routeurs... donc sur secteur par obligation.
Donc ne doit pas toucher autre chose que la date de derniere comme de chaque routeur interrogé.

**Comment by mickadam29** [comment]
Et voilà. Je ne me suis pas trompé.
Je viens de lancer une collecte. Regarde les heures. Tu auras compris que dans le lot il ya plus d'équipements sur pile que de routeurs. Donc je suis certain que les routeurs injoignables sont aussi mis à jour. On verra cela au prochain timeout de l'un d'eux.
Et encore plus étrange, mais ce n'est pas le sujet, un équipement en timeout répond à la commande get-name. 
Donc faudrait savoir si oui ou non il est sur le réseau. Pour ce point je vais débrancher un équipement ce soir et lui faire un get-name. On verra et selon j'ouvrirai un issue ou pas
 
![image](https://user-images.githubusercontent.com/36518012/108856328-3b24da00-75ea-11eb-845a-56ae9a4398d3.png)

**Comment by mickadam29** [comment]
Comme tu le dis, le log LQI n'interroge que des routeurs. Indique bien qu'il abandonne sur un routeur injoignable, mais les heures sont modifiées.

**Comment by tcharp38** [comment]
#1816  STP
Tu as raison, au moins de ton cote qqch cloche.
Je regarde si je reproduis la meme chose sans routeurs
