### ISSUE TITLE
Xiaomi Double Interrupteur sensor_86sw2.json

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#180]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=594017#p594017

**Comment by KiwiHC16** [comment]
strown a écrit : ↑
Hier, 22:17
Image
kiwihc16 a écrit : ↑
04 mars 2018, 23:34
strown a écrit : ↑
04 mars 2018, 19:00


Bien joué c'est bien cà ;-) En fait j'ai fait au plus simple j'ai copié le json du sw1 dans sw2 en me disant que sur un malentendu ca marcherait...
Et bien ca marche... pas complètement !
Peux tu partager le fichier créé et partager ce qui marche et ce qui ne marche pas ? Je ferai une "issue" dans GitHub avec les infos et nous pourrons développer les JSON spécifique à ce produit. J'en est un en commande mais je ne l'ai pas en stock pour le tester donc tes informations seront importantes.
Le fichier créé, ben très simple j'ai pris le sensor_86sw1.json que j'ai simplement copié et renommé en sensor_86sw2.json et que j'ai mis dans le bon répertoire dans Abeille/core/config/devices, donc rien de bien méchant.

En revanche ci joint des extraits de logs du Parser qui pourront aider : 
Appui sur le premier bouton :
Code : Tout sélectionner

AbeilleParser 2018-03-05 22:05:32[DEBUG]-------------- 2018-03-05 22:05:32: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:05:32[DEBUG]Type: 8102 quality: b7
AbeilleParser 2018-03-05 22:05:32[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:05:32[DEBUG][2018-03-05 22:05:32]
AbeilleParser 2018-03-05 22:05:32[DEBUG]SQN: 16
AbeilleParser 2018-03-05 22:05:32[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:05:32[DEBUG]End Point : 01
AbeilleParser 2018-03-05 22:05:32[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:05:32[DEBUG]Data byte list : 01
AbeilleParser 2018-03-05 22:05:32[DEBUG]Data byte: 1
AbeilleParser 2018-03-05 22:05:32[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-03-05 22:05:32[DEBUG]-------------- 2018-03-05 22:05:32: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:05:32[DEBUG]Type: 8102 quality: b7
AbeilleParser 2018-03-05 22:05:32[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:05:32[DEBUG][2018-03-05 22:05:32]
AbeilleParser 2018-03-05 22:05:32[DEBUG]SQN: 16
AbeilleParser 2018-03-05 22:05:32[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:05:32[DEBUG]End Point : 01
AbeilleParser 2018-03-05 22:05:32[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:05:32[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:05:32[DEBUG]Data byte list : 00
AbeilleParser 2018-03-05 22:05:32[DEBUG]Data byte: 0
AbeilleParser 2018-03-05 22:05:32[DEBUG]mqttPublish with Qos: 0
Et sur le 2 ème :
Code : Tout sélectionner

AbeilleParser 2018-03-05 22:07:32[DEBUG]-------------- 2018-03-05 22:07:32: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:07:32[DEBUG]Type: 8102 quality: a5
AbeilleParser 2018-03-05 22:07:32[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:07:32[DEBUG][2018-03-05 22:07:32]
AbeilleParser 2018-03-05 22:07:32[DEBUG]SQN: 17
AbeilleParser 2018-03-05 22:07:32[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:07:32[DEBUG]End Point : 02
AbeilleParser 2018-03-05 22:07:32[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:07:32[DEBUG]Data byte list : 01
AbeilleParser 2018-03-05 22:07:32[DEBUG]Data byte: 1
AbeilleParser 2018-03-05 22:07:32[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-03-05 22:07:32[DEBUG]-------------- 2018-03-05 22:07:32: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:07:32[DEBUG]Type: 8102 quality: a5
AbeilleParser 2018-03-05 22:07:32[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:07:32[DEBUG][2018-03-05 22:07:32]
AbeilleParser 2018-03-05 22:07:32[DEBUG]SQN: 17
AbeilleParser 2018-03-05 22:07:32[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:07:32[DEBUG]End Point : 02
AbeilleParser 2018-03-05 22:07:32[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:07:32[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:07:32[DEBUG]Data byte list : 00
AbeilleParser 2018-03-05 22:07:32[DEBUG]Data byte: 0
AbeilleParser 2018-03-05 22:07:32[DEBUG]mqttPublish with Qos: 0
Et enfin sur les 2 à la fois :
Code : Tout sélectionner

AbeilleParser 2018-03-05 22:08:28[DEBUG]-------------- 2018-03-05 22:08:28: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:08:28[DEBUG]Type: 8102 quality: 9f
AbeilleParser 2018-03-05 22:08:28[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:08:28[DEBUG][2018-03-05 22:08:28]
AbeilleParser 2018-03-05 22:08:28[DEBUG]SQN: 18
AbeilleParser 2018-03-05 22:08:28[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:08:28[DEBUG]End Point : 03
AbeilleParser 2018-03-05 22:08:28[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:08:28[DEBUG]Data byte list : 01
AbeilleParser 2018-03-05 22:08:28[DEBUG]Data byte: 1
AbeilleParser 2018-03-05 22:08:28[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-03-05 22:08:28[DEBUG]-------------- 2018-03-05 22:08:28: protocolData size(38) message > 12 char
AbeilleParser 2018-03-05 22:08:28[DEBUG]Type: 8102 quality: 9f
AbeilleParser 2018-03-05 22:08:28[DEBUG] Type: 8102 (Attribut Report)(Processed->MQTT)
AbeilleParser 2018-03-05 22:08:28[DEBUG][2018-03-05 22:08:28]
AbeilleParser 2018-03-05 22:08:28[DEBUG]SQN: 18
AbeilleParser 2018-03-05 22:08:28[DEBUG]Src Addr : 82bc
AbeilleParser 2018-03-05 22:08:28[DEBUG]End Point : 03
AbeilleParser 2018-03-05 22:08:28[DEBUG]Cluster ID : 0006
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr ID : 0000
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Status : 00
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Data Type : 10
AbeilleParser 2018-03-05 22:08:28[DEBUG]Attr Size : 0001
AbeilleParser 2018-03-05 22:08:28[DEBUG]Data byte list : 00
AbeilleParser 2018-03-05 22:08:28[DEBUG]Data byte: 0
AbeilleParser 2018-03-05 22:08:28[DEBUG]mqttPublish with Qos: 0
Et l'objet Abeille en semi automatique : 
Capture.jpeg

Pur résumer ils sont tous les 3 identiques à l'exception du endpoint qui vaut respectivement 1, 2 ou 3. J'ai pes eu le temps de regarder en détail la syntaxe du json pour savoir s'il est possible de créer des commandes différentes en fonction du endpoint. 
Si oui, je suis volontaire pour tester. 
Si non, avec un peu d'aide je suis volontaire pour coder la fonctionnalité... et tester aussi ;-)
Super, y a toutes les infos pour faire un JSON.

Dans les logs on voit un retour 0 suivi de 1 ("Data byte: 0" -> "Data byte: 0"), dans le log c est dans la meme seconde. Peux tu voir si le 0 arrive quand tu appuis et le 1 quand tu relâches. Ou si les deux arrivent quand tu relâches ?

C'est le premier equipemnt qui a 3 endpoints donc il faut que je regardes comment mettre ca dans le code mais ne devrait pas être trop un soucis.

**Comment by edgd1er** [comment]
il y a aussi le multiclic sur le sw1 qui doit etre présent aussi sur le sw2 mais je ne sais pas comment l'intégrer dans le json: http://zigate.fr/xiaomi-bouton-poussoir-clusters/

**Comment by KiwiHC16** [comment]
Si @strown peut nous faire un test cela confirmera les infos de Akila et on peut l'intégrer assez facilement.

**Comment by strown** [comment]
J'ai essayé le double clic... ca n'a pas l'air de fonctionner, je ne vois rien passer dans le Parser à part les trucs habituels.

**Comment by strown** [comment]
> Dans les logs on voit un retour 0 suivi de 1 ("Data byte: 0" -> "Data byte: 0"), dans le log c est dans la meme seconde. Peux tu voir si le 0 arrive quand tu appuis et le 1 quand tu relâches. Ou si les deux arrivent quand tu relâches ?

=> Les 2 arrivent quand je relache

**Comment by strown** [comment]
AbeilleParser 2018-03-06 21:35:56[DEBUG]-------------- 2018-03-06 21:35:56: protocolData size(28) message > 12 char
AbeilleParser 2018-03-06 21:35:56[DEBUG]Type: 8045 quality: 48
AbeilleParser 2018-03-06 21:35:56[DEBUG]type: 8045 (Active Endpoints Response)(Not Processed)
AbeilleParser 2018-03-06 21:35:56[DEBUG]SQN : d8
AbeilleParser 2018-03-06 21:35:56[DEBUG]Status : 00
AbeilleParser 2018-03-06 21:35:56[DEBUG]Short Address : 82bc
AbeilleParser 2018-03-06 21:35:56[DEBUG]Endpoint Count : 03
AbeilleParser 2018-03-06 21:35:56[DEBUG]Endpoint List :
AbeilleParser 2018-03-06 21:35:56[DEBUG]Endpoint : 01
AbeilleParser 2018-03-06 21:35:56[DEBUG]Endpoint : 02
AbeilleParser 2018-03-06 21:35:56[DEBUG]Endpoint : 03

Pas de surprise ici

**Comment by strown** [comment]
AbeilleParser 2018-03-06 21:46:06[DEBUG]-------------- 2018-03-06 21:46:06: protocolData size(86) message > 12 char
AbeilleParser 2018-03-06 21:46:06[DEBUG]Type: 8043 quality: 63
AbeilleParser 2018-03-06 21:46:06[DEBUG]Type: 8043 (Simple Descriptor Response)(Not Processed)
AbeilleParser 2018-03-06 21:46:06[DEBUG]SQN : e4
AbeilleParser 2018-03-06 21:46:06[DEBUG]Status : 00
AbeilleParser 2018-03-06 21:46:06[DEBUG]Short Address : 82bc
AbeilleParser 2018-03-06 21:46:06[DEBUG]Length : 20
AbeilleParser 2018-03-06 21:46:06[DEBUG]endpoint : 01
AbeilleParser 2018-03-06 21:46:06[DEBUG]profile : 0104
AbeilleParser 2018-03-06 21:46:06[DEBUG]deviceId : 5f01
AbeilleParser 2018-03-06 21:46:06[DEBUG]bitField : 01
AbeilleParser 2018-03-06 21:46:06[DEBUG]InClusterCount : 05
AbeilleParser 2018-03-06 21:46:06[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2018-03-06 21:46:06[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:46:06[DEBUG]In cluster: 0019 - General: OTA
AbeilleParser 2018-03-06 21:46:06[DEBUG]In cluster: ffff -
AbeilleParser 2018-03-06 21:46:06[DEBUG]In cluster: 0012 -
AbeilleParser 2018-03-06 21:46:06[DEBUG]OutClusterCount : 07
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0000 - General: Basic
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0004 - General: Groups
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: ffff -
AbeilleParser 2018-03-06 21:46:06[DEBUG]Out cluster: 0012 -

**Comment by strown** [comment]
AbeilleParser 2018-03-06 21:50:09[DEBUG]-------------- 2018-03-06 21:50:09: protocolData size(62) message > 12 char
AbeilleParser 2018-03-06 21:50:09[DEBUG]Type: 8043 quality: 63
AbeilleParser 2018-03-06 21:50:09[DEBUG]Type: 8043 (Simple Descriptor Response)(Not Processed)
AbeilleParser 2018-03-06 21:50:09[DEBUG]SQN : e7
AbeilleParser 2018-03-06 21:50:09[DEBUG]Status : 00
AbeilleParser 2018-03-06 21:50:09[DEBUG]Short Address : 82bc
AbeilleParser 2018-03-06 21:50:09[DEBUG]Length : 14
AbeilleParser 2018-03-06 21:50:09[DEBUG]endpoint : 02
AbeilleParser 2018-03-06 21:50:09[DEBUG]profile : 0104
AbeilleParser 2018-03-06 21:50:09[DEBUG]deviceId : 5f02
AbeilleParser 2018-03-06 21:50:09[DEBUG]bitField : 01
AbeilleParser 2018-03-06 21:50:09[DEBUG]InClusterCount : 02
AbeilleParser 2018-03-06 21:50:09[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:50:09[DEBUG]In cluster: 0012 -
AbeilleParser 2018-03-06 21:50:09[DEBUG]OutClusterCount : 04
AbeilleParser 2018-03-06 21:50:09[DEBUG]Out cluster: 0004 - General: Groups
AbeilleParser 2018-03-06 21:50:09[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:50:09[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-03-06 21:50:09[DEBUG]Out cluster: 0012 -

**Comment by strown** [comment]
AbeilleParser 2018-03-06 21:52:03[DEBUG]-------------- 2018-03-06 21:52:03: protocolData size(62) message > 12 char
AbeilleParser 2018-03-06 21:52:03[DEBUG]Type: 8043 quality: 66
AbeilleParser 2018-03-06 21:52:03[DEBUG]Type: 8043 (Simple Descriptor Response)(Not Processed)
AbeilleParser 2018-03-06 21:52:03[DEBUG]SQN : e8
AbeilleParser 2018-03-06 21:52:03[DEBUG]Status : 00
AbeilleParser 2018-03-06 21:52:03[DEBUG]Short Address : 82bc
AbeilleParser 2018-03-06 21:52:03[DEBUG]Length : 14
AbeilleParser 2018-03-06 21:52:03[DEBUG]endpoint : 03
AbeilleParser 2018-03-06 21:52:03[DEBUG]profile : 0104
AbeilleParser 2018-03-06 21:52:03[DEBUG]deviceId : 5f03
AbeilleParser 2018-03-06 21:52:03[DEBUG]bitField : 01
AbeilleParser 2018-03-06 21:52:03[DEBUG]InClusterCount : 02
AbeilleParser 2018-03-06 21:52:03[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:52:03[DEBUG]In cluster: 000C -
AbeilleParser 2018-03-06 21:52:03[DEBUG]OutClusterCount : 04
AbeilleParser 2018-03-06 21:52:03[DEBUG]Out cluster: 0004 - General: Groups
AbeilleParser 2018-03-06 21:52:03[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser 2018-03-06 21:52:03[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-03-06 21:52:03[DEBUG]Out cluster: 000C -

**Comment by KiwiHC16** [comment]
Aie j'avais oublié qu'il va falloir les commissioner pour utiliser les groupes et scenes. Il va falloir sniffer le commissioning fait par la GW Xiaomi pour pourvoir simuler la meme chose.
Donc un premier temps on peut faire un JSON pour visualiser l'interrupteur dans Jeedom mais celui ci, a priori ne pourra rien commander directement. Inter->Jeedom/Scenario->Objet: Ok, Inter->Objet: Nok

**Comment by strown** [comment]
J'ai essayé de regarder un peu comment faire pour utiliser le endpoint afin de gérer 3 interrupteurs et je me pose quelques question sur l'archi du plugin. Soit : 
1) Dans AbeilleParser on ajoute le endpoint dans le MQTTPublish, ce qui va par effet de bord demander la modif dans Abeille.class de pas mal de trucs pour que ca marche avec un risque pas négligeable de régression. De plus cela demanderait problablement la mise à jour de tous les json existant si par exemple on modifie le topic en Abeille/src/endpoint/Cluster-attr
2) Dans AbeilleParser on bricole un truc pour que dans le cas particulier de cet inter on publie sur un cluster/attribut perso les différents états. Le pb ca risque d'être moche, peu maintenable, et pas très "réutilisable" si un autre équipement était dans le même cas. Problème annexe : lors du decode de abeilleParser on a pas l'info du type d'équipement, et il faudrait un mapping addr_src -> eqts qui à mon avis n'est pas l'esprit de la classe.

Du coup j'ai quelques questions sur l'architecture du plugin : 
1) Pourquoi ne pas avoir utilisé les clusters de la Zigbee Cluster Library, afin de rendre la config des objets plus génériques (ex: pour le cluster 0006
Identifier | Name | Type | Range | Access | Default | M/O
0x0000 | OnOff | bool | 0x00 – 0x01 | Read Only Reportable Scene | 0x00 | M
0x4000 | GlobalSceneControl | bool | 0x00 – 0x01 | Read Only | 0x01 | O
0x4001 | OnTime | uint16 | 0x0000 – 0xffff | Read Write | 0x0000 | O
0x4002 | OffWaitTime | uint16 | 0x0000 – 0xffff | Read Write | 0x0000 |O  ) ?
2) Si c'est voulu, comment vous gèreriez les endpoints avec l'archi actuelle ?
3) Pourquoi la clé des commandes dans le json est le cluster-attr ?

Bref, j'aimerais vous aider en codant la fonctionnalité mais je sais pas dans quel sens le prendre. Vous sauriez me conseiller ?

**Comment by KiwiHC16** [comment]
Que de bonne questions... quand j'ai commencé je découvrai tout (Plugin Jeedom, ZigBee,...) donc l'archi actuelle est le résultat de mes découvertes au fur et a mesure. Par exemple Abeille/src/Cluster-attr était différent au tout début.
Et si on va vers Abeille/src/endpoint/Cluster/attr comment on gere les adresses de groupes ? etc...
La nouvelle découverte ici est qu'un même equipement utilise plusieur EndPoint, c'est le premier dans ce cas.
Comment faire, pour l instant je n'ai pas de réponse car je n'ai pas eu le temps d'y travailler. 
Avant de faire des changements il nous faut comprendre comment on fait le parametrage de l'équipement, comment on le veut dans Jeedom,.... 
Je viens d'en recevoir un qui est sur mon bureau alors je vais pourvoir investiguer.
Une premiere idée était d'avoir un objet par EndPoint (Deux objets dans Jeedom, Pour un interrupteur double) mais j'ai lu que si tu appuis sur les deux alors c'est endpoint 03. Doit on avoir 3 objets dans Jeedom ?

**Comment by strown** [comment]
C'est ca 3 endpoints, 3 objets... OK en attendant que tu aie eu le temps de jouer un peu je vais faire un tour du coté du plugin zwave histoire de voir comment ils font de leur coté (ca demande un peu de temps, je découvre jeedom comme toi ;-)

**Comment by KiwiHC16** [comment]
Je viens finalement de commencer à integrer le Xiaomi Switch Double Poussoir sans neutre que j ai et il n'a pas le même nom: "ctrl_neutral2". Je vais créer une issue avec celui ci. 

Je retrouve les End Point multiple et j'ai fais une modif en reception pour que cela fonctionne.

Sur cette base je vais regarder le json de votre switch et les logs ci dessus pour voir si c est le même cas.

**Comment by KiwiHC16** [comment]
Je viens d ajouter le double switch mural sur pile. Je clos le topic.
