### ISSUE TITLE
Colonne Repond NOK sur des eq Terminaux: comprendre pourquoi.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1805]
![Capture d’écran 2021-02-22 à 08 30 04](https://user-images.githubusercontent.com/8549674/108676373-66270500-74e8-11eb-956c-cb36222c5c48.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
@KiwiHC16 

Je ne sais pas si tu as avancé sur le sujet.
Je viens d'inclure mon bouton Sonoff. Lui, répond bien OK
Objet inclus avant le dev de cette fonction, qui est nouvelle je crois -> KO
Objet inclus après -> OK (l'objet qui est en ok a été exclus par la commande Exclure, supprimé de Jeedom)

Je ne sais pas si ça peut t'aider.
PS : J'avais un doute, mais 8H53 n'est pas l'heure de création mais bien l'heure d'une com' avec Zigate

![image](https://user-images.githubusercontent.com/36518012/109411744-7cc7d300-79a4-11eb-9fab-a270223f8d1c.png)

Je viens de trouver un second objet qui est OK. Lui aussi a été réinclus depuis que la fonction existe.

![image](https://user-images.githubusercontent.com/36518012/109411951-9fa6b700-79a5-11eb-9f5d-1216c4d10a77.png)

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/109419202-9c72f180-79cc-11eb-8115-c9973b67c1a6.png)
 Passé à NOK au bout de qqs heures

**Comment by tcharp38** [comment]
De mon experience, quand on n'est pas en mode inclusion les devices peuvent ecouter sur une periode ultra courte.
Ca rend le test du chemin de retour pas fiable.
De + de mon point de vue, la reception de n'importe quelle info venant du device (last comm/online/Time-Time/Time-TimeStamp) est suffisante pour dire que tout est ok.

**Comment by tcharp38** [comment]
Pas de temps à passer la dessus. Cette fonctionalité est cachée pour l'instant.
A reouvrir si le besoin s'en fait sentir
