### ISSUE TITLE
Get Info clarification

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1807]
Fonction Remplace HS
#1789

**Comment by KiwiHC16** [comment]
Je ne t'ai pas demandé du coup si c'est normal que Get Infos ait créé un nouvel objet. Probablement NON.
![image](https://user-images.githubusercontent.com/8549674/108719361-c08f8800-751f-11eb-94f1-a60086801948.png)

**Comment by tcharp38** [comment]
Sujet obsolete.
