### ISSUE TITLE
Toutes les commandes Action->Tester génèrent un code 500 sur tous les objets

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1810]
@KiwiHC16 

En faisant les tests pour #1789 j'ai un plantage sur les commandes Actions

Toutes les commandes Action génèrent un code 500 sur tous les objets. En cliquant sur TESTER uniquement.
Les actions se font bien. Dans les scénarios aussi. En fait c'est le bouton tester qui génère le code 500.

Les commandes Infos, remonte bien l'info demandée

![image](https://user-images.githubusercontent.com/36518012/108749887-aa45f400-7540-11eb-96b6-4238c71e0614.png)

**Comment by mickadam29** [comment]
![Uploading image.png…]()

**Comment by KiwiHC16** [comment]
Erreur 500 est une veritable galère à trouver. 

Est ce que tu as aussi ce soucis avec des commandes sur des abeilles créées lors de leur inclusion ?

**Comment by mickadam29** [comment]
Au début je pensais que cela ne concernait que le dernier objet créé. Mais en fait c’est valable sur toutes les commandes et tous les objets.

**Comment by mickadam29** [comment]
Donc la réponse est oui

**Comment by KiwiHC16** [comment]
As tu des messages dans le log /var/www/html/log/http ?
Et dans la console du browser internet ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
[http.error.log](https://github.com/KiwiHC16/Abeille/files/6024871/http.error.log)

**Comment by mickadam29** [comment]
sous Edge j'ai ça
![image](https://user-images.githubusercontent.com/36518012/108764197-92776b80-7552-11eb-97f1-5b6d6b6af398.png)

Je ne sais pas qui est 192.168.1.9 ??? Une ip en dur dans le code ? Ce n'est pas mon navigateur et ce n'est pas mon jeedom

**Comment by KiwiHC16** [comment]
Adresse inconnue !

**Comment by mickadam29** [comment]
> Adresse inconnue !

Pas tout à fait si on tient compte du fait que celle de jeedom est 96. Donc l'adresse serait trounquée. Il manquerait le dernier caractère ?

**Comment by KiwiHC16** [comment]
Aucune adresse comme celle ci sur mes systèmes.
Regardes ta conf IP dans Jeedom.

**Comment by KiwiHC16** [comment]
```
[Mon Feb 22 18:39:40.912219 2021] [php7:error] [pid 21066] [client 192.168.1.35:1459] PHP Fatal error:  Uncaught Error: Call to a member function getName() on bool in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php:168\nStack trace:\n#0 /var/www/html/core/class/cmd.class.php(1104): AbeilleCmd->execute(NULL)\n#1 /var/www/html/core/ajax/cmd.ajax.php(88): cmd->execCmd(NULL)\n#2 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php on line 168, referer: http://192.168.1.96/index.php?v=d&m=Abeille&p=AbeilleEq&id=430
```

une erreur Abeille
Je l ai vu sur mon système aussi mais ne provoque pas errer 500 sur mes systèmes.

#1813

**Comment by mickadam29** [comment]
> ```
> [Mon Feb 22 18:39:40.912219 2021] [php7:error] [pid 21066] [client 192.168.1.35:1459] PHP Fatal error:  Uncaught Error: Call to a member function getName() on bool in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php:168\nStack trace:\n#0 /var/www/html/core/class/cmd.class.php(1104): AbeilleCmd->execute(NULL)\n#1 /var/www/html/core/ajax/cmd.ajax.php(88): cmd->execCmd(NULL)\n#2 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php on line 168, referer: http://192.168.1.96/index.php?v=d&m=Abeille&p=AbeilleEq&id=430
> ```
> 
> une erreur Abeille
> Je l ai vu sur mon système aussi mais ne provoque pas errer 500 sur mes systèmes.
> 
> #1813

So

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

La release d'hier soir a corrigé le pb
