### ISSUE TITLE
Rafraichissement des widgets

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1811]
@KiwiHC16 

Mise à jour Master à 16H

Dans la dernière version du master, il y a une petite bizarrerie
J'allume une lampe depuis le widget. Le widget change. L'ampoule passe allumée. Mais la roue reste affichée

![image](https://user-images.githubusercontent.com/36518012/108752025-407b1980-7543-11eb-958c-a22ebeab000e.png)

J'éteins la lampe. Le widget se met à jour. L'ampoule passe à off. Mais la roue de mise à jour, tourne en permanence jusqu'à ce que je fasse F5. 

![image](https://user-images.githubusercontent.com/36518012/108752462-c5fec980-7543-11eb-8d2b-14d29793789c.png)

Je ne sais pas si cela cache un problème ou si c'est juste visuel

**Comment by KiwiHC16** [comment]
J ai vu un soucis similaire du fait de plantages lors de mes dev. 
Je suis passé en 4.1.20, je ne sais pas si il y a un lien. 
Quelle version d Abeille, utilises tu ?

**Comment by mickadam29** [comment]
4.1.20

**Comment by mickadam29** [comment]
4.1.20 mais dès sa sortie. Par contre je n’ai vu cette roue que ce soir. Mais comme je passe plus de temps sur mon environnement de tests peut-être que ça date de la maj en 4.1.20

**Comment by KiwiHC16** [comment]
Sur mes systèmes le comportement de ces roues est bizarre.

Mais sur le plugin Virtuel la roue est présente avec un comportement different:
![Capture d’écran 2021-02-22 à 20 49 21](https://user-images.githubusercontent.com/8549674/108761701-72927880-754f-11eb-84c3-8eb91808858a.png)

Sur zwave, je ne vois pas ce comportement.

Cette roue est gérée par le core jeedom. Aucune idée comment il fonctionne.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 

Il y a peut-être une part de code dans l'affaire.
La mise à jour d'hier soir a corrigé aussi ce pb de roue.
Cf #1810 #1813
