### ISSUE TITLE
Lampe EWELINK ZB-RGBCW compatible Philips Hue

### ISSUE THREAD

**Issue by zorglub54** [KiwiHC16/Abeille#1812]
Bonjour,
Après achat de 1 lampe zigbee compatible philips hue sur ali, elle remonte en module inconnu avec les infos suivantes.
![image](https://user-images.githubusercontent.com/79474219/108753412-fe52d780-7544-11eb-996a-c239a2fb3861.png)
![image](https://user-images.githubusercontent.com/79474219/108753033-84225300-7544-11eb-882c-322f966302c1.png).
Informations clefs nécessaires au support.

1/ Version (AbeilleVersion.inc)
===============================
stable, 2021-02-15 19:32

2/ Linux
========
["Raspbian GNU\/Linux 10 \\n \\l",""]
["Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

4/ AbeilleParser / Modelisation
Vide !
===============================
Nota : la commande identify la fait clignoter 10 fois.....
L'intégration est elle possible vu son prix très intéressant ?
Je suis à ta disposition pour tout renseignement et actions compatibles avec mon niveau 0 en json
Merci d'avance 😉

**Comment by KiwiHC16** [comment]
Je vais te proposer un modèle et on verra si ça suffit.

**Comment by KiwiHC16** [comment]
Peux tu partager le lien direct vers le site d AliExpress ?

**Comment by KiwiHC16** [comment]
Recuperes le fichier 
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/ZB-RGBCW
et essayes.
Tiens moi au courant.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by zorglub54** [comment]
Merci de ta réponse rapide, voici le lien direct vers ali et je vois pour le reste : [https://fr.aliexpress.com/item/1005002179747762.html?spm=a2g0o.productlist.0.0.221f20faxQlkZo&algo_pvid=6d736e4d-e8c2-4091-a9da-23a2d96795f3&algo_expid=6d736e4d-e8c2-4091-a9da-23a2d96795f3-4&btsid=0b0a182b16140743822977797edf63&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_](url)

**Comment by zorglub54** [comment]
Bon j'ai copié/collé dans un fichier .text le fichier json, mais excuse mon ignorance, j'ai lu la doc du plug "modele et fichier json" mais ça reste complétement obscur (un comble pour de l'éclairage), je dois bien sur le placer à un endroit précis, peux tu m'expliquer ? ensuite je suppose que je supprime et  réinclue ma lampe ? d'avance merci pour tes explications.

**Comment by zorglub54** [comment]
Je me répond, je rentre les données à partir de ton fichier json dans les rubriques correspondantes de "configuration de l'équipement _ informations brutes" ??

**Comment by KiwiHC16** [comment]
Je suis un peut sous l eau avec tous les sujets. Je te propose d attendre la version stable dans 1 semaine et demi (lundi en 15) et de tester.

**Comment by zorglub54** [comment]
Ok merci

**Comment by zorglub54** [comment]
J'ai réinclu après mise à jour j'ai bien sur le dashboard l'arrêt marche fonctionnel


![image](https://user-images.githubusercontent.com/79474219/110663602-e0cd7100-81c6-11eb-886d-5db28ad5d6a1.png)

Mais pas de variation d'intensité ni de changements de couleurs.

Voici les log de parser :

![image](https://user-images.githubusercontent.com/79474219/110663937-415cae00-81c7-11eb-9b4b-317c598573eb.png)

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6117471/AbeilleParser.log)

**Comment by tcharp38** [comment]
Salut @zorglub54 
Je vois ce vieux sujet toujours ouvert.
Toujours d'actualité ?

**Comment by tcharp38** [comment]
Sujet sans vie depuis un moment.
Je clos mais à réouvrir si besoin.
