### ISSUE TITLE
getName issue

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1813]
```
[Mon Feb 22 18:39:40.912219 2021] [php7:error] [pid 21066] [client 192.168.1.35:1459] PHP Fatal error:  Uncaught Error: Call to a member function getName() on bool in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php:168\nStack trace:\n#0 /var/www/html/core/class/cmd.class.php(1104): AbeilleCmd->execute(NULL)\n#1 /var/www/html/core/ajax/cmd.ajax.php(88): cmd->execCmd(NULL)\n#2 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php on line 168, referer: http://192.168.1.96/index.php?v=d&m=Abeille&p=AbeilleEq&id=430
```

**Comment by tcharp38** [comment]
C est tout frais ca depuis aujourd hui non ?

**Comment by mickadam29** [comment]
Oui, depuis une installation du master vers 16H

**Comment by tcharp38** [comment]
Ok il faut que je regarde tres vite. Comment je reproduis ?

**Comment by mickadam29** [comment]
tu prends une commande action sur un objet et tu cliques sur tester. Genre ON ou OFF d'une ampoule mais surtout tu passes par les commandes tester. Par le widget ca passe très bien. Regarde l'issue #1810 j'ai mis des copies d'écran

**Comment by tcharp38** [comment]
Correctif poussé pour intégration dans le master.
Mais attaché si tu peux tester.
[AbeilleCmd.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6025243/AbeilleCmd.class.php.zip)

**Comment by KiwiHC16** [comment]
Dans le master.

**Comment by mickadam29** [comment]
Bug corrigé
