### ISSUE TITLE
Liste des équipements trouvés dans le réseau mais inconnus dans Jeedom

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1815]
https://community.jeedom.com/t/equipements-trouves-dans-le-reseau-mais-inconnus-dans-jeedom/54440

Liste des équipements trouvés dans le réseau mais inconnus dans Jeedom:
Abeille1/Ruche
Abeille1/1A23

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by mickadam29** [comment]
@KiwiHC16 

J'ai toujours eu ça chez moi, aussi loin que je m'en souvienne. Je me disais ils travaillent dessus, ce n'est pas abouti. Mais visiblement non ?

**Comment by mickadam29** [comment]
Résultat du log parser sur une collecte LQI
Les 2 listes sont incomplètes mais on y retrouve des similitudes. Un log dit connu de jeedom et le second inconnu ??

![image](https://user-images.githubusercontent.com/36518012/108885519-35d68800-7608-11eb-8c22-ee7409e743e9.png)

Et dessous la vue graph

![image](https://user-images.githubusercontent.com/36518012/108885616-53a3ed00-7608-11eb-8f6b-defe178263cf.png)

**Comment by KiwiHC16** [comment]
Probablement un soucis en relation avec les evolutions get LQI, doit pas être grand chose. Je vais regarder.

**Comment by mickadam29** [comment]
Ça me semble bien antérieur.
Mais comme je connais pas le code je te laisse gérer ce point. Dis moi simplement si tu as besoin d’infos ou logs

**Comment by KiwiHC16** [comment]
In master semble fonctionner maintenant.
