### ISSUE TITLE
Cube contrôler aide pour identifier tous les mouvements

### ISSUE THREAD

**Issue by SebRider** [KiwiHC16/Abeille#1818]
Bonjour,

J'ai quelques petites difficultés à gérer le cube contrôler de Xiaomi, tout comme @scottjim

1 - Je me heurte sur le sens de rotation du cube.
Lorsque je fait une rotation horaire et anti-horaire j'ai bien des valeurs mais toutes positives, en général la commande [Rotation (?)] remonte la valeur entre 290 et 630.
Comment déterminer les rotations horaires et anti-horaire ?

2 - Comment différencier le double et le simple tap avec le cube ?

3 - Lorsque je fait un "tap" ou un "double tap" j'ai des remontés "512 + face" MAIS :

Si j'ai déjà fait un "tap" ou "double tap" précédemment (même 10 min avant) le cube ne remonte plus la commande [Mouvement] avec sa valeur "512+face".
Si j'ai fait n'importe quel autre mouvement avant (exemple flip, donc la commande [Mouvement] à 74), la commande [Mouvement] "512+face" remonte bien.
=> On dirais que le plugin garde une sorte de rémanence du dernier mouvement et empêche la répétition au déclencheur, même si je m'amuse a prendre comme déclencheur la commande [Time-Time] qui elle est présente et différente a chaque manipulation du cube.
Ref : Cube Xiaomi Magic, inscription MI sur une face modèle : MFKZQ01LM
Abeille version 2021-02-08 19:05:11
Jeedom version 4.1.19
Cle Zigate v3.1D

PS j'ai repris un schéma avec une autre logique que celle du dev du plugin. Désolé je dois pas avoir une même faculté visuelle pour déterminer les valeurs de chaque actions du cube. 
Si cela peut intéresser quelqu'un. Je n'ai pas ajouté les rotations puisque comme la question 1 l'indique, je n'ai toujours pas compris comment bien l'identifier.

Merci pour votre aide précieuse 😁

![107882658-eb0f8e80-6eea-11eb-8390-72cf25d74772](https://user-images.githubusercontent.com/78418545/108886692-8ef2eb80-7609-11eb-81f1-8b5ad5172c54.jpg)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
https://kiwihc16.github.io/AbeilleDoc//Xiaomi.html?highlight=cube#cube-aqara

**Comment by SebRider** [comment]
Merci @KiwiHC16, j'ai épluché de long en large se schéma mais n'y ait pas trouvé la réponse aux précisions demandés, comme je disais j'ai sûrement pas la même logique :(

**Comment by KiwiHC16** [comment]
Si tu ne retrouves pas mes valeurs, il est possible que le soft est été modifié côté cube.
Attention entre Hexa et Decimal....

**Comment by KiwiHC16** [comment]
Ca correspond:
Tes notes:
![Capture d’écran 2021-02-26 à 16 56 16](https://user-images.githubusercontent.com/8549674/109323249-8d1c6880-7853-11eb-97f9-f7b691b2a90b.png)

Mes notes:
![Capture d’écran 2021-02-26 à 16 56 34](https://user-images.githubusercontent.com/8549674/109323286-973e6700-7853-11eb-826f-31d6b146d4c2.png)

**Comment by KiwiHC16** [comment]
Idem dans l autre sens:

![Capture d’écran 2021-02-26 à 16 57 06](https://user-images.githubusercontent.com/8549674/109323365-aa513700-7853-11eb-9f44-bfd079f30e99.png)

et

![Capture d’écran 2021-02-26 à 16 57 23](https://user-images.githubusercontent.com/8549674/109323396-b3da9f00-7853-11eb-8e1d-00a1d02492a7.png)

**Comment by KiwiHC16** [comment]
Je n ai pas vérifié la suite mais je suppose qu'idem...

**Comment by SebRider** [comment]
> Si tu ne retrouves pas mes valeurs, il est possible que le soft est été modifié côté cube.
> Attention entre Hexa et Decimal....

Bonsoir,
Merci @KiwiHC16 pour ton attention.

Toujours pour ma question 1 - Du coup comment puis-je récupérer les valeurs en Hexa ou en Décimal, abeille m'a crée automatiquement les commandes en chaine de caractère donc qui devraient me remonter les signes "+" ou "-" si l'on prend le cas de la rotation ?

Exemple de rotation : 
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-TimeStamp] valeur : 1614638081
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-Time] valeur : 2021-03-01 23:34:41
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Link Quality] valeur : 90
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Mouvement] valeur : 259
=> La valeur 259 serait en hexa ou décimal ?

=========================

Et question 2 - Dans mon cas également lorsque je reproduit deux fois un même mouvement (tap, ou chute) la valeur retournée doit être la même, or  je n'ai pas de remontée de la valeur, simplement une valeur temps.
Ex dans les logs :

Je double tap :
[2021-03-01 23:34:15][INFO] : Evènement sur la commande [Salon][Cube-Controler][Link Quality] valeur : 84
[2021-03-01 23:34:15][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-TimeStamp] valeur : 1614638055
[2021-03-01 23:34:16][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-Time] valeur : 2021-03-01 23:34:15
[2021-03-01 23:34:16][INFO] : Evènement sur la commande [Salon][Cube-Controler][Mouvement] valeur : 515
=> J'ai bien 515 qui remonte dans [Mouvement], normal

Je double tap quelques secondes après :
[2021-03-01 23:34:26][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-TimeStamp] valeur : 1614638066
[2021-03-01 23:34:26][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-Time] valeur : 2021-03-01 23:34:26
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Link Quality] valeur : 93
=> pas de remontée de [Mouvement], une explication ?

Alors que si je fait une rotation par exemple :
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-TimeStamp] valeur : 1614638081
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-Time] valeur : 2021-03-01 23:34:41
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Link Quality] valeur : 90
[2021-03-01 23:34:41][INFO] : Evènement sur la commande [Salon][Cube-Controler][Mouvement] valeur : 259
=> Il me remonte bien la rotation

Puis a nouveau double tap :
[2021-03-01 23:34:46][INFO] : Evènement sur la commande [Salon][Cube-Controler][Link Quality] valeur : 84
[2021-03-01 23:34:46][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-TimeStamp] valeur : 1614638086
[2021-03-01 23:34:46][INFO] : Evènement sur la commande [Salon][Cube-Controler][Time-Time] valeur : 2021-03-01 23:34:46
[2021-03-01 23:34:46][INFO] : Evènement sur la commande [Salon][Cube-Controler][Mouvement] valeur : 515
=> La valeur 515 remonte à nouveau dans [Mouvement], normal, 

La suite on la connait si je double tap à nouveau plus de valeur [Mouvement remontée]

Merci,

**Comment by KiwiHC16** [comment]
Exemple 1:

![Capture d’écran 2021-03-02 à 20 45 36](https://user-images.githubusercontent.com/8549674/109705598-405cc880-7b98-11eb-95ca-824c6cdc39bb.png)

Tu dis rotation mais visiblement il a envoyé un mouvement.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-03-02 à 20 48 47](https://user-images.githubusercontent.com/8549674/109705991-b2351200-7b98-11eb-805f-c21713e1681d.png)
Dans la commande mouvement quelque tu as pour cette partie de configuration ?

**Comment by KiwiHC16** [comment]
Dec ou Hex: je ne sais plus mais on dirai que tout est Dec.

**Comment by SebRider** [comment]
> ![Capture d’écran 2021-03-02 à 20 48 47](https://user-images.githubusercontent.com/8549674/109705991-b2351200-7b98-11eb-805f-c21713e1681d.png)
> Dans la commande mouvement quelque tu as pour cette partie de configuration ?

Parfait tu m'as appris a mieux connaitre jeedom, j'ai presque honte mais c'est très utile, merci !



> Exemple 1:
> 
> ![Capture d’écran 2021-03-02 à 20 45 36](https://user-images.githubusercontent.com/8549674/109705598-405cc880-7b98-11eb-95ca-824c6cdc39bb.png)
> 
> Tu dis rotation mais visiblement il a envoyé un mouvement.

ca devais être un faux positif il a mal interprété ma rotation, ca peut arriver a la limite ce n'est pas trop grave.
Par contre je ne comprend toujours pas comment retrouver le sens de rotation, quelqu'un a déjà réussi a avoir ce sens ? Une fonction que je ne connaisse pas encore de Jeedom ?

**Comment by KiwiHC16** [comment]
![](https://user-images.githubusercontent.com/8549674/109323249-8d1c6880-7853-11eb-97f9-f7b691b2a90b.png)

![](https://user-images.githubusercontent.com/8549674/109323365-aa513700-7853-11eb-9f44-bfd079f30e99.png)

Je ne comprends pas ton soucis. Ici par exemple tourne à droite alors valeur 72 et si tourne à gauche valeur 96.
Tu as bien le sens de rotation...

**Comment by KiBeu** [comment]
J'ai ressorti mon cube d'un tiroir il ya deux semaines et j'ai eu quelques problèmes aussi pour utiliser la rotation.
Au final je suis tombé sur un bug dans le plugin, je voulais faire une pull request mais j'ai un peu manqué de temps.
Tu as quelle version du cube ? sensor_cube ou sensor_cube.aqgl01 ?

**Comment by SebRider** [comment]
Bonjour,

Je me sent moins seul du coup, merci !
Bonne question, il est écris 2016DP0965 | MFKZQ01LM.
Sinon je ne sais pas où retrouver les dénominations que tu as cité, désolé.

Cordialement,
Seb.

**Comment by KiBeu** [comment]
A partir de la page du plugin Abeille, tu cliques sur ton cube, puis sur "configuration avancée" en haut à droite, puis sur "informations" en haut à droite (sur le bouton, à côté de Log).
Là tu arrives sur une page "informations brutes" et dans la partie "configuration"  tu as plusieurs champs, le second doit te donner le modèle "sensor_cube" ou "sensor_cube.aqgl01".

Autre questions, dans les commandes du cube, as-tu "Rotation (Angle ?)" ?

**Comment by SebRider** [comment]
En effet merci, c'est bien un "Cube contrôler".

Voici les commandes créés automatiquement par le cube :
![Screenshot_20210316-074831](https://user-images.githubusercontent.com/78418545/111267387-23aaa100-862c-11eb-94e1-325362d7dc85.jpg)
En général dans la rotation j'ai un chiffre plus ou moins aléatoire entre 290 et 630 mais pas de notion de positif ou negatif

**Comment by KiBeu** [comment]
En fait je parlais de ce que tu as là : ("Sensor_cube" pour moi) :
![Capture d’écran 2021-03-16 à 07 59 47](https://user-images.githubusercontent.com/29957710/111268839-1abacf00-862e-11eb-9056-e166e5f632df.png)
Quand tu cliques là dans configuration avancée :
![Capture d’écran 2021-03-16 à 07 59 33](https://user-images.githubusercontent.com/29957710/111268968-4938aa00-862e-11eb-96a6-e1a26dcc5329.jpg)

**Comment by KiBeu** [comment]
Il y a une commande "Rotation (angle?)" qui n'est pas définie avec le "sensor_cube" mais elle semble bien configurée avec le "sensor_cube.aqgl01" du coup je voudrais être sûr qu'on a bien le même modèle.
Après il y a aussi un problème dans le parser qui fait que la commande n'est pas bien remontée.

**Comment by SebRider** [comment]
Ah oui le deuxième champ ici, pardon oui c'est un sensor_cube tout court. J'étais à la bonne fenêtre mais donnait la deuxième ligne de la fenêtre et pas le deuxième champ de configuration. Désolé.

**Comment by KiBeu** [comment]
Ok pas de problème, on a bien le même modèle même si ma modification devrait fonctionner pour les deux.
Je vais faire une pull request

**Comment by KiwiHC16** [comment]
Le Pull Request est maintenant dans la version master. Merci KiBeu.

**Comment by SebRider** [comment]
Bonjour,

Merci a vous pour la réactivité !
Du coup j'ai supprimé et refait l'inclusion de mon cube, j'ai une manipulation spécifique pour faire remonter le sens de rotation ?

**Comment by KiBeu** [comment]
Tu devrais avoir une commande "Rotation Angle" en plus (pas forcément visible par défaut).
Par contre la modification a été poussée sur le master mais n'est pas dans la mise à jour officielle d'hier il me semble.

**Comment by SebRider** [comment]
Okay merci de l'info, ça marche j'attends de voir cela mais du coup il faudra refaire l'inclusion du cube pour la voir la commande, ou elle apparaît automatiquement lorsque je vais faire une action sur le cube par exemple ?

**Comment by KiBeu** [comment]
Il faudra refaire l'inclusion

**Comment by KiBeu** [comment]
@SebRider La modification est dans la dernière mise à jour. Il faut supprimer le cube et refaire l'inclusion. Tu auras une commande Rotation Angle qui devrait apparaitre
