### ISSUE TITLE
Image pour graphique Abeille => erreur 404 not found

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1820]
https://community.jeedom.com/t/image-pour-graphique-abeille-erreur-404-not-found/54592

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-24 à 09 04 54](https://user-images.githubusercontent.com/8549674/108967106-5d1c6c00-767f-11eb-8c85-dea3a0d98fba.png)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-24 à 09 05 41](https://user-images.githubusercontent.com/8549674/108967200-79b8a400-767f-11eb-8aa4-aaaf24bdc923.png)

**Comment by nawak86** [comment]
Hello Kiwi,
Je voulais savoir si tu avais avancé sur ce bug ?
merci
Bonne soirée

**Comment by tcharp38** [comment]
Salut @nawak86 
Donc ce souci est toujours d'actualité ?
Peux tu basculer sur la beta pour confirmer, et me dire comment reproduire le pb que tu observes ?
Merci

**Comment by nawak86** [comment]
Salut, oui pas de soucis je peux basculer sur la beta mais j'aimerais éviter de perdre le support c'est possible d'avoir un zip du code du plugin comme ça je peux revenir en arrière rapidement ?
Merci

**Comment by tcharp38** [comment]
Tout est sur le market. Tu choisis beta au lieu de stable.
voir https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

Et tu fais un backup avant par mesure de securite.
Dans tous les cas cette beta deviendra la nouvelle stable d ici peu. Pas de retours d'une quelconque regression jusque la.

Quant au zip, tu peux l 'avoir directement via Github 
https://github.com/KiwiHC16/Abeille
![image](https://user-images.githubusercontent.com/35221038/159160993-40751785-af78-4e7b-ae12-4b8970cd8e9a.png)

**Comment by nawak86** [comment]
Hello, 

je viens de mettre la beta quand je vais dans configuration j'ai : Version 2022-02-24 01:00:17
mais dans infos clés dans l'onglet support : Version Abeille: 220320-BETA-1

donc quand je vais sur Network Graph et que je clique sur une zigate :
http://192.168.0.33/plugins/Abeille/Network/TestSVG/NetworkGraph.php?zigate=2
Not Found
The requested URL was not found on this server.

dans réseau / graphique des liens j'ai le warning en haut à droite à coté des notifs jeedom : /index.php?v=d&m=Abeille&p=Abeille | 374 | Uncaught TypeError: Cannot set properties of undefined (setting 'Type') 

et j'ai 2 menus "Changement de Zigate" en bas : 
![image](https://user-images.githubusercontent.com/5274111/159192128-f15f675b-338d-424f-a978-95af53591e32.png)

et au besoin : 
```
Informations clefs nécessaires au support.

Quand [vous ouvrez une "issue"](https://github.com/KiwiHC16/Abeille/issues/new) dans GitHub merci de copier/coller les 3 premiers chapitres ci dessous 
Pour l'intégration d'un équipement non encore supporté ajoutez le chapitre 4.

Version Abeille: 220320-BETA-1

Kernel: ["Linux vm-jeedom-prod 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU\/Linux"]

Zigate 1: 0004-0321
Zigate 2: 0005-0321

Table du plugin
===============
{
    "233": {"type":"plugin","name":"Abeille","logicalId":"Abeille","localVersion":"2022-02-24 01:00:17","remoteVersion":"2022-02-24 01:00:17","source":"market","status":"ok","configuration":"{\"version\":\"stable\",\"market\":1,\"third_plugin\":1,\"doNotUpdate\":\"0\"}","updateDate":"2022-02-24 01:39:12"},
}

Table 'cron'
============
{
    "111875": {"enable":"1","class":"Abeille","function":"deamon","schedule":"* * * * *","timeout":"1440","deamon":"1","deamonSleepTime":"1","option":null,"once":"0"},
}

Table 'config'
==============
{
    "AbeilleActiver1": {"plugin":"Abeille","value":"Y"},
    "AbeilleActiver10": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver2": {"plugin":"Abeille","value":"Y"},
    "AbeilleActiver3": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver4": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver5": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver6": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver7": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver8": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver9": {"plugin":"Abeille","value":"N"},
    "AbeilleIEEE_Ok1": {"plugin":"Abeille","value":"1"},
    "AbeilleIEEE_Ok10": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok2": {"plugin":"Abeille","value":"1"},
    "AbeilleIEEE_Ok3": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok4": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok5": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok6": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok7": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok8": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok9": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE1": {"plugin":"Abeille","value":"00158D0001EE0457"},
    "AbeilleIEEE2": {"plugin":"Abeille","value":"00158D0006A3FDEA"},
    "AbeilleParentId": {"plugin":"Abeille","value":"1"},
    "AbeilleSerialPort1": {"plugin":"Abeille","value":"\/dev\/ttyUSB2"},
    "AbeilleSerialPort10": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort2": {"plugin":"Abeille","value":"\/dev\/ttyUSB0"},
    "AbeilleSerialPort3": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort4": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort5": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort6": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort7": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort8": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort9": {"plugin":"Abeille","value":"none"},
    "AbeilleType1": {"plugin":"Abeille","value":"USB"},
    "AbeilleType10": {"plugin":"Abeille","value":"USB"},
    "AbeilleType2": {"plugin":"Abeille","value":"USBv2"},
    "AbeilleType3": {"plugin":"Abeille","value":"USB"},
    "AbeilleType4": {"plugin":"Abeille","value":"USB"},
    "AbeilleType5": {"plugin":"Abeille","value":"USB"},
    "AbeilleType6": {"plugin":"Abeille","value":"USB"},
    "AbeilleType7": {"plugin":"Abeille","value":"USB"},
    "AbeilleType8": {"plugin":"Abeille","value":"USB"},
    "AbeilleType9": {"plugin":"Abeille","value":"USB"},
    "active": {"plugin":"Abeille","value":"1"},
    "agressifTraitementAnnonce": {"plugin":"Abeille","value":"4"},
    "api": {"plugin":"Abeille","value":"crypt:oSwJI+ZE4mWEYo9\/hqmwaL1Rd8S+At20CKOM8OYMxnJo4sUdUP\/aUlSvRCKKnpXPQvlxexcq\/aYEzBdh\/RJZJsHWk0vWCbL+P1A0qWzdRvHyLo7hf3DYfW48\/VZgJmGBj9PgxPuA+ZJk5fSVO0N5RDLs76E+DMlf5K\/NC1fdWOA="},
    "blocageRecuperationEquipement": {"plugin":"Abeille","value":"Oui"},
    "blocageTraitementAnnonce": {"plugin":"Abeille","value":"Non"},
    "DbVersion": {"plugin":"Abeille","value":"20201025"},
    "deamonAutoMode": {"plugin":"Abeille","value":"1"},
    "deamonRestartNumber": {"plugin":"Abeille","value":"0"},
    "displayMobilePanel": {"plugin":"Abeille","value":"1"},
    "IpWifiZigate1": {"plugin":"Abeille","value":""},
    "IpWifiZigate10": {"plugin":"Abeille","value":""},
    "IpWifiZigate2": {"plugin":"Abeille","value":""},
    "IpWifiZigate3": {"plugin":"Abeille","value":""},
    "IpWifiZigate4": {"plugin":"Abeille","value":""},
    "IpWifiZigate5": {"plugin":"Abeille","value":""},
    "IpWifiZigate6": {"plugin":"Abeille","value":""},
    "IpWifiZigate7": {"plugin":"Abeille","value":""},
    "IpWifiZigate8": {"plugin":"Abeille","value":""},
    "IpWifiZigate9": {"plugin":"Abeille","value":""},
    "lastDeamonLaunchTime": {"plugin":"Abeille","value":"2022-03-21 01:06:34"},
    "lastDependancyInstallTime": {"plugin":"Abeille","value":"2022-03-21 01:16:56"},
    "monitor": {"plugin":"Abeille","value":"755"},
    "preventLQIRequest": {"plugin":"Abeille","value":"no"},
}
```

voila voila ;)

merci

Bonne nuit ;p

**Comment by nawak86** [comment]
j'ai aussi :
core/php/getResource.php?file=core/js/log.class.js&md5=97aae7c356368e6a141e894799c00e88&lang=fr_FR | 246 | Uncaught ReferenceError: $rawLogCheck is not defined
sur la page pour libérer le port de la zigate.

++

**Comment by tcharp38** [comment]
Ok je reproduis ce pb

> donc quand je vais sur Network Graph et que je clique sur une zigate :
> http://192.168.0.33/plugins/Abeille/Network/TestSVG/NetworkGraph.php?zigate=2
> Not Found
> The requested URL was not found on this server.

Je regarde ca et reviens vers toi.

**Comment by nawak86** [comment]
pas de soucis hésites pas a me dire et je pousserais la nouvelle beta ++

**Comment by tcharp38** [comment]
[AbeilleNetworkGraph.zip](https://github.com/KiwiHC16/Abeille/files/8315850/AbeilleNetworkGraph.zip)

Ecraser le fichier dans desktop/php avec celui ci
recharger la page

Je te laisse tester et me dire ce qui deconne encore.

Sinon comment utilises tu cette page ?

**Comment by nawak86** [comment]
ça fonctionne, perso c'est surtout que ça me chagrine de voir plein d'erreur quand je me balade dans le plugin.

si tu veux je peux tester au fur et à mesure que tu corriges.

- il reste l'erreur javascript quand on clique sur réseau puis graphique des liens
- quand on clique dans configuration sur libérer le port l'erreur : 
/core/php/getResource.php?file=core/js/log.class.js&md5=97aae7c356368e6a141e894799c00e88&lang=fr_FR | 246 | Uncaught 
-  "Changement de Zigate" en double sur l'accueil du plugin

tu remplaces KiwiHC16 ?

mon vrais soucis est la : https://community.jeedom.com/t/prise-ikea-non-detecte/81307/2 si tu as une idée et que tu peux m'aider ça serait sympa.

Bonne soirée

**Comment by tcharp38** [comment]
Ha donc tu cliques un peu partout sans vraiment en avoir besoin :)

Il y a des tas de choses que je n'utilise pas ou n'ai jamais utilisé. Voir certaines dont je ne vois pas l'interet mais j'essaie de corriger et rendre plus robuste au fur et à mesure d'un retour utilisateur. Si personne n'utilise alors... à virer ou masquer mais pourquoi y perdre du temps ? En tout cas c'est mon approche.

je vais regarder les autres erreurs que tu mentionnes.

Et non je ne remplace pas Kiwi. C'est son bébé. Je ne fait que nettoyer, optimiser et corriger les erreurs qui trainent encore.
Et au passage j'essaie de rendre les choses + intuitives ou documentées. Un bon soft est un soft qui se passe de support :)

Pour ton pb Ikea, peux tu ouvrir un sujet sur ce forum. + pratique pour les logs.

**Comment by tcharp38** [comment]
Je ne reproduis que le 3iem point: "changement de zigate en double", donc fixé.
Les autres... je ne vois pas de soucis.

**Comment by nawak86** [comment]
la seule page qui peut être utilise c'est l'onglet réseau : 
![image](https://user-images.githubusercontent.com/5274111/159572503-0abc6a70-97f9-4040-a20c-a38bdfd3b563.png)
(sous firefox)
le reste j'avoue que je m'en moque un peu :p tant que la partie avec les équipements fonctionne ;)

ok je vais ouvrir un sujet merci

**Comment by tcharp38** [comment]
Je viens de pousser une autre beta.
Dis moi si on peut clore ce sujet.

**Comment by nawak86** [comment]
je fais la maj demain et je te tiens au courant ;)

**Comment by nawak86** [comment]
hello parfais plus d'erreurs ;) merci bien

**Comment by tcharp38** [comment]
Ok Je clos.
Merci
