### ISSUE TITLE
Objets "éjectés" du réseau Zigbee

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1821]
@KiwiHC16 

Depuis qqs temps, certains objets quittent le réseau Zigbee. Ils restent connus par Abeille. Donc ces objets passent en timeout.
Il faut donc les réinclure en passant par le mode inclusion de la zigate et en procédant selon l'objet à son inclusion.

Je rencontre le cas sur 2 environnements différents : 
Prod -> Debian / Jeedom 4.1.20 / Abeille (master que je maintiens up2date) / Zigate USB
Dev -> Raspian / Jeedom 4.1.20  / Abeille version beta (date de plusieurs jours/sem) / Pizigate

Les abeilles qui quittent sont par exemple une prise Ikea et un capteur de temp Xiaomi sur la prod
Sur le dev, c'est un objet DIY. Lui j'ai juste eu besoin de mettre la pizigate en inclusion car il était automatiquement en tentative et donc s'est réinclus seul. 

Une piste pour expliquer  qu'un objet quitte le réseau ? Quant je dis quitter, cela s'apparente à la fonction Exclure mais sans que j'en sois à l'origine, bien évidement.

![image](https://user-images.githubusercontent.com/36518012/108977714-1fbcdc00-7689-11eb-9bff-cc83458267cb.png)
 
Je ne pense pas qu'on soit sur une qualité du réseau.

**Comment by tcharp38** [comment]
J'ai ce type de comportement avec 3 capteurs Xiaomi depuis des lustres.

- Je suis certain qu'aucun ordre de quitter le reseau leur a ete envoyé
- Abeille n'est pas au courant que l'EQ sorte du reseau donc il n'a pas recu de message
- Bref en ce qui me concerne, souci de perturbations, de routage des messages ou portée.

Il faudrait en prendre un "ejecté", et le sniffer jusqu'a ce qu'il quitte pour voir ce qui se passe.

**Comment by tcharp38** [comment]
Le sujet concernant mes 3 capteurs est celui ci #1298
Je vais reprendre ce sujet. Abeille a eu beaucoup d'evolutions depuis et moi j'ai appris un peu +.

**Comment by mickadam29** [comment]
J'ai lu rapidement. Je reprendrai calmement. Mais une piste serait peut-être le fait que des équipements sont attachés à 2 routeurs.
Je fais une copie d'écran, comme ça la prochaine fois que je perds un équipement je verrai si par hasard il n'était pas dans ce cas.
Abeille-251 et Abeille-235 sont vus sur 2 routeurs.
Mais dans le cas de mon DEV, je n'ai que la pizigate. Donc probablement autre chose
 
![image](https://user-images.githubusercontent.com/36518012/108985065-e5efd380-7690-11eb-90f7-67bb44c6a846.png)

**Comment by tcharp38** [comment]
Attention, meme si tu vois des liaisons vers 2 routeurs je crois qu'on ne peut pas dire qu'il soit "attaché".
L'eq est vu par 2 routeurs mais un seul chemin est utilisé et choisi par l'eq lui meme à un instant donné.

**Comment by KiwiHC16** [comment]
On peut imaginer plein de raisons.

Pour les équipements sur piles Xiaomi, quand j'avais étudié le sujet j'avais trouvé qu'ils quittaient le réseau s'ils n'avaient pas de réponse de celui ci après plusieurs demandes. Ils font de temps en temps un DataRequest qui doit être ACK par le réseau. Dans le cas contraire, il pense avoir perdu le réseau, se déconnectent et cherchent à se reconnecter. Typiquement un probable radio, de temps en temps la liaisonnent assez bonne et ca tient et un jour la liaison est trop faible et ca ne passe pas. On avait essayé avec Akila de réduire se phénomène en augmentant des timers dans la zigate mais on ne peut modifier le soft des équipements donc il faut une bonne couverture radio...

Des bugs soft dans les équipements,

Un équipement qui veut se rattacher à un routeur referent plus interessant et la procedure se passe mal.

Premiere chose à faire, nettoyer la radio. Pas de wifi qui brouille tout, bonne couverture radio,....

Ensuite sniffer au niveau de l'équipement et regarder ce qu'il se passe. Je peux regarder les sniffs si vous en faites.

**Comment by Tonio16** [comment]
Salut

Même problème chez moi avec la dernière béta sous jeedom 4.1.20. Une prise ikea tradfry éjectée, des sondes de températures aqara, des détecteurs de vibrations aqara, d’ouverture aqara.
Plus surprenant, j’ai du appairer un détecteur d’ouverture plusieurs fois de suite. En quelques minutes il avait été éjecté.

Antoine

**Comment by mickadam29** [comment]
@KiwiHC16 @tcharp38 @Tonio16 @battousai90

Il me semble qu'on a tous rencontré le problème.
Ce qui m'interpelle c'est plutôt que ces soucis sont proches de nous. J'incrimine personne et je n'explique pas pourquoi. Mais il y a plusieurs semaines je postais pour dire que ça allait beaucoup mieux. Quasi jamais de timeout, et généralement la comm reprenait dans l'heure qui suivait. Mais là il faut refaire l'appairage.  De mémoire au passage en 4.1 JEEDOM. Pratiquement plus de timeout. Puis catastrophe début février (avec peut-être un lien avec la mise à jour jeedom 4.1.19). La seule solution que j'ai trouvée c'est virer mes ampoules IKEA pour les remplacer par des  OSRAM. Et là je retrouve une stabilité. 1 ou 2 équipement(s) en défaut contre une douzaine sur la quinzaine qui a précédé le remplacement de mes ampoules. @Tonio16 , on est en phase pour dire que la situation s'est dégradée tout dernièrement ? On a pas tous apporté des changements à nos infra. Il y a aussi @battoussai90 qui a remonté des difficultés avec les ampoules et donc de gros soucis de routage. Il faudrait que nous parvenions à concentrer nos infos et constatations pour tenter de résoudre ces problèmes. Les problèmes de parasites réseau, j'y crois pas vraiment. Pour mon environnement de dev, les 2 puces sont à 1m de ma pizigate. Si la puissance de la pizigate et la sensibilité des E18 sont pas suffisantes on peut pas espérer les séparer de  plusieurs mètres dans la maison. Des bugs dans les soft ? Le firmware 3.1D ? Des changements dans les releases 4.1.x de Jeedom ? J'ai un sniffer 2531 @KiwiHC16. Si tu me dis comment te fournir un scan, quel outil utiliser, je te fournirai tout ça. Effectivement, si l'on parvient à savoir qui de l'équipement ou du routeur/zigate le fait sortir du réseau on pourra sans doute avancer. Un sniffer proche de la zigate serait en mesure de capter tout ce qui lui est adressé ? Un peu comme un port mirroring sur un switch ?

**Comment by Tonio16** [comment]
Pour moi, c'est en lien avec la dernière beta, mais sans preuve. J'ai déjà eu des dispositifs en time out avant mais jamais en éjecté. J'ai des ampoules qui restent éteintes sans courant pendant des jours avoir été éjectées du réseau. 

 J'avais refait l'appairage hier de mes dispositifs et ce soir, j'ai de nouveau un capteur de température qui est éjecté, deuxième fois pour lui, dommage il est accessible uniquement avec une échelle. 
Les dispositifs à pile sont plus touchés à priori.

Antoine

**Comment by mickadam29** [comment]
Pour moi, ce sont ceux sur secteur et par effet de bord les autres sur piles puisqu'ils n'ont plus le routeur pour atteindre la zigate. Et comme moi tu dois avoir plus d'équipements sur pile que sur secteur. D'où ta constatation. Des timeout, on est d'accord, il y en a. Mais la plupart du temps, tu laisses passer deux heures au lieu de 60 min et le message passe et le timeout disparaît. Mais pas ces réappairages devenus trop fréquents.

**Comment by Tonio16** [comment]
Je constate ce soir que l’un des dispositifs éjectés n’est plus fonctionnel. C’est un detecteur de luminosité aqara. A l’appairage, cela semble ok, mais la valeur reste fixe. Un deuxième qui n’a pas été éjecté lui, fonctionne correctement.
Probablement aucun lien mais je préfère le signaler.

Antoine

**Comment by mickadam29** [comment]
Pour ma part je n'ai eu aucun équipement sorti du réseau depuis hier. La dernière mise à jour est la master faite hier 24/02 vers 10H. Je vais stopper toutes les mises à jour au moins jusqu'au prochain élément déconnecté. Comme je suivais jusque là la master, à chaque maj je l'installais. Mais je veux savoir d'où vient cette instabilité. Depuis hier, un seul équipement sur pile qui passe en timeout mais dès que j'appuie dessus il agit et repart pour une heure. C'est le bouton Sonoff. Mais ça c'est normal. Mode pile et sommeil pour l'économiser. Donc situation stable. A suivre

**Comment by KiwiHC16** [comment]
J ai 7 zigates qui tournent et plus de 130 équipements et je ne rencontre pas ce soucis. J ai des zigate en 3.1B et 3.1D. Tous les jeedoms sur le master.

Une piste est la charge des zigates. Combien d'équipements par Zigate avez vous ?
Moi je suis à 20 en moyenne. La plus grosse conf est à 30 pour une zigate.

Je ne vois que trois solutions pour avancer:
- vous capturez un log dans AbeilleSerial ou AbeilleParser qui nous amène une info.
- vous suiffez le zigbee pour voir ce qu il se passe
- on passe la zigate en mode debug avec des traces, mais pas facile car il faut compiler le soft, sortie un deuxième port USB qui n'est pas cablé....

**Comment by KiwiHC16** [comment]
@mickadam29 j ai développé mon propre sniffer: https://github.com/KiwiHC16/Butineuse mais pas facile à utilisé. Sinon regardes les discussions sur le sujet dans slack (je n ai pas testé, encore un truc à faire).

**Comment by mickadam29** [comment]
@KiwiHC16 

Pour ma part, je vois 21 abeilles en direct + 4 derrière des routeurs + 3 qui "connaissent 2 routes" la Zigate et un routeur.
Comme déjà évoqué, j'ai rencontré pour la dernière fois, le même jour, 2 objets sortis sur la zigate de prod. Mais aussi 1 DIY sur le dev. Donc pour le dev, impossible d'incriminer une charge. Seulement 2 abeilles sur une pizigate. A moins d'1m les uns des autres, sur le bureau. 
Reste 
- des anomalies de type "réseau". Parasites, Wifi, ,4G, etc. Ca va pas être facile à identifier. Je laisse tomber pour le moment. J'ai une borne wifi avec contrôleur dont la puissance est automatique. Il se pourrait que parfois, celle-ci couvre le signal Zigbee. Ca reste une hypothèse. Rien pour étayer ça.
- des anomalies de type routage/maillage. Déjà en virant mes ampoules IKEA j'ai quasiment viré tous mes problèmes. Avec, ça a été tous les jours pendant 20 jours que je devais refaire des inclusions, après avoir débranché/rebranché ces Ikea. Depuis, seulement 2 équipements à remettre et espacés de plusieurs jours. L'un 2 est une prise Ikea. C'est du matos acheté en 2018. Pas certains qu'ils soient en Zigbee 3.0. 

J'ajoute que depuis hier, aucun problème. Une stabilité à toute épreuve. Tous les équipements restent présents, pas de timeout, sauf les 2 connus . Pourvu que ça dure.
   

![image](https://user-images.githubusercontent.com/36518012/109248273-c9b17b00-77e5-11eb-84ee-9d01d1bdaccc.png)

**Comment by mickadam29** [comment]
A midi, ce jour 26/02, toujours pas d'équipement en timeout. Ni sorti du réseau et qui nécessiterait de faire l'inclusion.

**Comment by KiwiHC16** [comment]
Il y très longtemps au debut du plugin j avais ajouté une reconfiguration des ampoules Ikea automatique. Je l'ai enlevé du code pour voir. On verra si ca change quelque chose sur mon systeme...

**Comment by mickadam29** [comment]
OK. Ce qui est étrange c'est qu'il m'en reste une, à l'extérieur, et elle ne pose aucun problème. J'ai l'impression d'être sorti d'affaire concernant tous ces problèmes d'abeilles déconnectées. Je les garde sous le coude. A l'occasion elle seront peut-être remises en service ces ampoules. Si j'ai l'occasion de croiser une passerelle Ikea je lui ferai faire une mise à jour de ces ampoules. Bon courage à toi @KiwiHC16 et encore merci.

**Comment by Tonio16** [comment]
> Si j'ai l'occasion de croiser une passerelle Ikea je lui ferai faire une mise à jour de ces ampoules. Bon courage à toi @KiwiHC16 et encore merci.

Cela devrait etre possible en passantpar le plugin zigate de Domoticz. Je vais essayer de tester.
Antoine

**Comment by mickadam29** [comment]
@Tonio16 
Domoticz prendre en charge l'OTA au travers de la zigate ?

**Comment by Tonio16** [comment]
> @Tonio16
> Domoticz prendre en charge l'OTA au travers de la zigate ?

Oui, https://domoticz.com/forum/viewtopic.php?t=31195

**Comment by KiwiHC16** [comment]
Zigate prend en charge OTA. Abeille ne le prend pas a ce jour car j ai consideré qu'on ne maitrise pas le firmware qu on envoie. Risk: avoir des equipement complement à l'état de brique. Dans les infos que j'ai vue seul Ikea (et peut etre un autre vendeur) fournis le firmware. @mickadam29 je ne pense pas que cela resolve ton soucis. J'ai plus de 20 ampoules Ikea sans soucis.

Par contre j'ai peut être une piste. Les ampoules peuvent changer d adresse courte au cours du temps et je recupere des "Ghost". Cela s'est produit ce matin. D'ou maquestion dans l issue "Ampoules IKEA / Pas de route pour la joindre #1833".

**Comment by KiwiHC16** [comment]
Pour tester l hypothèse, pouvez vous créer une Telecommande Virtuelle dans Abeille lui associer le groupe 3333 (par exemple), asssocier l ampoule sur le meme groupe 3333 (Clic ampoule + bouton AddGroup). Testez que cela fonctionne.

Quand vous pensez que l ampoule est "éjectée" car vous ne parvenez pas à la piloter depuis abeille (depuis le widget de l ampoule), utilisez la telecommande pour voir si elle repond au On ou Off.

**Comment by KiwiHC16** [comment]
Mon soupçon est que l ampoule change d adresse et pour une raison ou une autre Abeille n'est pas au courant: d ou perte de controle de l ampoule.

**Comment by KiwiHC16** [comment]
Je change de veste, j ajoute une issue pour faire la partie OTA. J apprendrai des trucs en le faisant, les utilisateurs seront contents par contre je vais mettre un GROS warning....
Implementer OTA pour Ikea #1836

**Comment by mickadam29** [comment]
@KiwiHC16 

N'ayant plus les ampoules (sont dans un carton) que j'incrimine je vais pas pouvoir REfaire le test. Mais je peux te dire que durant les semaines où j'avais le problème, seules mes télécommandes n'avaient pas de problème. Que ce soit la physique HUE ou la virtuelle. Tout était dans le même groupe. C'est d'ailleurs que qui m'a sauvé. Je pouvais toujours allumer/Eteindre avec les télécommandes. @battousai90 a confirmé que la gestion des groupes fonctionnait aussi chez lui. 

Pour dire simplement : La gestion par groupe a toujours fonctionné

**Comment by KiwiHC16** [comment]
Ca confirme mon idée. Le soucis est Abeille, pas la zigate, ni les ampoules.

**Comment by mickadam29** [comment]
Par contre je te suis dans l'OTA. Ces ampoules étant dorénavant inutiles, et ayant un réseau Zigbee de test, je pourrais te faire les tests que tu veux. Sauf si dès le premier, mon ampoule se transforme en brique. Mais ça j'assume le risque pour te permettre d'avancer sur le sujet.

**Comment by KiwiHC16** [comment]
Peux tu partager l info dans l issue: #1833

**Comment by mickadam29** [comment]
> Ca confirme mon idée. Le soucis est Abeille, pas la zigate, ni les ampoules.

Te vexe pas, mais j'en doutais plus. C'est venu trop brutalement et ça a disparu chez moi avec la mise à jour faite le 24 au matin. 1 Timeout ce matin sur un détecteur de présence Sonoff. En passant devant il s'est signalé à la Zigate. Mais plus aucun appareil qui quitte le réseau. Pour le moment je bloque les mises à jour Master. Et celle de Jeedom. Je veux retrouver une stabilité pour m'occuper de mes DIY. Dès que tu as une piste, et un dev à tester lié spécifiquement à ce problème, fais moi signe je te le testerai

**Comment by mickadam29** [comment]
Je comprends aussi que tu ne disposes pas du temps nécessaire pout tout gérer. Bon courage et encore merci

**Comment by mickadam29** [comment]
J'ajoute une dernière petite chose. En suivant les posts ouverts, je constatais de plus en plus de sujets liés aux équipements IKEA et timeout en tous genres.

**Comment by mickadam29** [comment]
Actuellement je n'ai plus aucun problème de ce genre. Sujet clos pour moi.
