### ISSUE TITLE
commande "info" vs "action" & comportement Abeille

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1822]
Pour faire suite au #1784, ma comprehension a evolué et je pense maintenant qu'Abeille fait parfoit une mauvaise implementation de ce qui est attendu par Jeedom cote cmds.

Du coup qu'est ce qu'une commande "info" par rapport à une commande "action" ?
Comme d'hab j'ai rien trouvé coté Jeedom. Aucune doc qui précise ce qui est attendu.

Ma comprehension est la suivante
- action: un ordre envoyé vers un equipement sans aucun retour immediat. Le retour d'une telle commande est donc "c'est fait (ordre envoyé)" ou "erreur"
  Ex: ferme le volet. Le status du volet ne devrait etre dispo et renvoyé qu'un moment apres
- info: une information quelconque venant d'un equipement mais c'est la ou ca se complique.
  - L'info peut etre deja dispo (ex: volet fermé) et etre toujours valide. Concernant zigbee c'est le cas des infos remontées par chaque eq (attribut report), de maniere asynchrone la plupart du temps (surtout eq sur pile).
  - L'info peut etre deja dispo mais devenue obsolete, auquel cas il faut reinterroger l'eq pour retourner qqch qui fasse du sens
    Ex: heure de la zigate
  - L'info n'est pas dispo et il faut interroger l'eq pour l'avoir

Si je ne prends qu'un cas particulier Abeille, je prends celui de l'heure de la zigate.
Abeille propose 2 cmds:
- action: "Get Time"
- info: "Zigate-Time"
Pourquoi ca ?
Je m'attendrais a 1 seule commande info (getZigateTime) qui interroge la zigate systematiquement.
Sinon et sauf erreur, aujourd hui il faut absoluement faire une action getTime avant de recuperer l'info zigateTime, et etre sur que l'action s'est bien terminée entre. Si l'action getTime n'est pas faite, soit l'info n'est pas presente, mais pire l'info est obsolete.
L'action "Set Time" quant à elle est correcte. Aucun retour necessaire.

Autre exemple simple ? "Version" est une commande action donc aucun retour. 
La commande "SDK" est surement la reponse souhaitée.
Le but etant de lire la version du FW, ca devrait etre une commande "info", qui interroge la zigate si besoin.
Si besoin car la difference avec getTime est que la on n'a pas besoin de refaire une mise à jour et on pourrait retourner l'info obtenue depuis le demarrage (ou mise à jour FW).

En conclusion de ma comprehension, un certain nombre de cmde infos doivent ne pas retourner qqch à jour, necessitant pour l'utilisateur d'autres actions pour connaitre la verite et/ou entrainant des reactivités inattendues.
Certains commandes action n'ont pas lieu d'etre. Une remise en cause permettrait
- de clarifier leur role
- de reduire le nombre de commandes

@KiwiHC16, que penses tu de tout ce blabla ?

**Comment by KiwiHC16** [comment]
Comment répondre ...
La confusion vient probablement du mot "Commande" de jeedom.
Commande fait pensé à commander, piloter, faire quelque chose.
Dans le cas d'une "commande action", c'est un peut redondant.
Par contre dans le cas des "Commandes Info"...

Preso ca devrait s'appeler simplement action et info.
Mais comme les objets php sont identiques et utilisent la class cmd.

- Commande action: demande d executer une action, ouvre un volet, éteint la lumière, donne moi telle information, dis moi comme tu t'appelles,... aucune valeur n'est associée à la commande. 

- Commande info: c est une valeur, une variable dans un programme. Jeedom va manipuler cette valeur par exemple en virant les valeurs hors min/max, enregistrement en base de données, alerte sur valeur,...
  
et il n'y a pas de correlation entre les deux.

Dans Abeille, dans 99% des cas info contient une information venant du réseau et cmd envoie une demande à un équipement.  Exemple typique, je clic sur ON (cmd action) pour une ampoule. Un message ON est envoyé à l'ampoule. Celle ci s'allume. Elle envoie sont état à Abeille qui met la valeur de la (Cmd) Info.

Sur le meme principe, cmd getTime qui demande a la zigate de nous envoyer l heure. La zigate envoie l heure et Abeille la met dans l'info (cmd) heure.

C'est un fonctionnement asynchrone. Pas de temps perdu. Pas de blocage à attendre une réponse que ne vient pas ou lentement. etc

Est ce que cela fait sens ? Si oui je peux expliquer le contenu des infos et leur validité. Si non, je ne souhaite pas encore expliquer la validité des infos a ce stade.

**Comment by tcharp38** [comment]
Oui ca fait du sens.
Et comme je ne trouve aucune doc Jeedom pour expliquer ce qui est attendu je ne peux que croire que ta comprehension est la bonne.

Du coup comme je disais auparavent, pour lire l'heure de la zigate, 2 commandes sont necesaires et pas une de moins.
getTime
zigateTime

Et etre sur davoir terminé la premiere avant de faire un zigateTime.

En ligne avec ca ?

**Comment by KiwiHC16** [comment]
Tout le plugin est basé sur le fait que rien n'est sûr.
Mais si tu envoies une commande puis une seconde, elles vont être envoyées l une après l autre si tout se passe bien.
Donc l'ordre sera:
- set Time (Cmd Action): envoie l heure à la zigate pour la mettre a l heure
- get Time (Cmd Action): envoie le demande de l heure a la zigate pour connaitre son heure interne
- Time (Cmd Info): reception de l heure interne de la zigate
-

**Comment by KiwiHC16** [comment]
Que fait on de cette issue ?

**Comment by tcharp38** [comment]
Je clos.
Meme si je ne n'arrive pas encore à etre à 100% dans cette logique tu as repondu.
