### ISSUE TITLE
Problème de remonter info après une action

### ISSUE THREAD

**Issue by loustic03** [KiwiHC16/Abeille#1826]
Bonjour KiwiHC16,
J'ai fais la mise à jour d'Abeille est depuis j'ai un problème de remonter d'info d'état sur mes prise Ikea .
Lorsque j'allume la prise ou je l'éteint j'ai pas toujours la mise à jour de l'état , je suis obliger de soit rallumer et éteindre pour avoir l'info.
 En faisant quelque essai j'ai remarqué que si je fait on/off a 3/4 secondes d'intervalle la mise à jour de l'info ne ce fait pas , si je laisse un peu plus de temps c'est pas forcément mieux  .
On dirait comme si le clic n'était pas pris en compte.
Jeedom 4.1.19 

![image](https://user-images.githubusercontent.com/76919490/109190970-f50c7980-7795-11eb-9560-0d7d6b6600fb.png)

![image](https://user-images.githubusercontent.com/76919490/109190860-d7d7ab00-7795-11eb-89d4-8f5c783241eb.png)
![image](https://user-images.githubusercontent.com/76919490/109191214-3b61d880-7796-11eb-83af-73e7f4b88189.png)
Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
"la mise à jour d'Abeille" => on parle bien de la stable de cette semaine ? (juste pour être sûr)
"Lorsque j'allume la prise ou je l'éteint" -> Comment fais tu ? Depuis Abeille ? Depuis une télécommande ?

**Comment by loustic03** [comment]
Oui je parle bien de la mise à jour de cette semaine. (stable )
J'allume ou éteins depuis abeille.
![ikea1](https://user-images.githubusercontent.com/76919490/109213427-dd8eba00-77b0-11eb-8753-c12d7da1a39f.gif)

**Comment by loustic03** [comment]
Pour info j'ai le problème uniquement avec les prises Ikea , j'ai des Legrand Netatmo et aucun souci avec celle-ci .

**Comment by KiwiHC16** [comment]
Je viens de tester sur une que j ai été je n ai pas ce soucis. Peux tu mettre en debug le plugin, redémarrer le daemon,
faire des on/off en notant les heures/min/s de tests et partager les logs AbeilleCmd, AbeilleParser et Abeille.

**Comment by loustic03** [comment]
Salut, KiwiHC16
Bon j'ai débranché mes prises et remis 2 min après et cela à résolu le problème de remonter d'info et aussi le on/off qui ne fonctionné que par moment .
Bizarre car cela fait plus de 2 ans que c'est prise sont en service et brancher.

Merci à toi .
