### ISSUE TITLE
Creation de commande info: logicalId pas defini

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1829]
1) - revoir le code pour clarifier dans le cas des commande info entre logocalId et conf(topic)
2) - mettre a jour ce qui faut un fois que 1) est fait.

**Comment by tcharp38** [comment]
Tu peux detailler ? Un cas d'exemple ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-02-26 à 16 32 22](https://user-images.githubusercontent.com/8549674/109320350-36615f80-7850-11eb-8e66-188784cdbbde.png)

![Capture d’écran 2021-02-26 à 16 33 20](https://user-images.githubusercontent.com/8549674/109320494-585ae200-7850-11eb-8737-445f6dae2b27.png)
Sauvegarde

logicalId vide:
![Capture d’écran 2021-02-26 à 16 33 50](https://user-images.githubusercontent.com/8549674/109320556-69a3ee80-7850-11eb-8f30-e0cb1c80d5dd.png)

Info dans configuration:
![Capture d’écran 2021-02-26 à 16 34 14](https://user-images.githubusercontent.com/8549674/109320602-77f20a80-7850-11eb-8498-b01892d1be89.png)

Mais sur arrivée du réseau d une info on cherche la commande info sur le logicalId (pas sur le topic):https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1827

**Comment by KiwiHC16** [comment]
une "merdouil..." qui date des debuts. pour les commandes infos logicalId = configuration(topic). Et dans le code il est fort possible que les deux soient utilisées....
Il faudrait virer partout pour les commande info le topic dans la configuration de la commande.
Mais avant de le faire il faut vérifier que je ne raconte pas des bêtises.

**Comment by tcharp38** [comment]
Je jetterai un oeil.

**Comment by tcharp38** [comment]
Pas facile à suivre tant le terme "topic" est utilisé dans plusieurs contextes mais cote commandes son utilisation semble reduite.
On va nettoyer ca progressivement pour utiliser cmd->logicalId() au lieu de cmd->config->"topic"

$ grep -R getConfiguration * | grep topic | grep -v ".bak"
core/class/Abeille.class.php:                $topic   = $cmd->getEqlogic()->getLogicalId() . '/' . $cmd->getConfiguration('topic');
core/class/Abeille.class.php:                    Abeille::publishMosquitto(queueKeyAbeilleToCmd, priorityInterrogation, "TempoCmd" . $cmd->getEqLogic()->getLogicalId() . "/" . $cmd->getConfiguration('topic') . "&time=" . (time() + $cmd->getConfiguration('PollingOnCmdChangeDelay')), $cmd->getConfiguration('request'));
core/class/AbeilleCmd.class.php:                if (strpos($this->getConfiguration('topic'), "CmdAbeille") === 0) {
core/class/AbeilleCmd.class.php:                    $topic = str_replace("Abeille", $dest, $this->getConfiguration('topic'));
core/class/AbeilleCmd.class.php:                    $topic = "Cmd" . $this->getEqLogic()->getLogicalId() . "/" . $this->getConfiguration('topic');
core/class/AbeilleParser.class.php:                $topic = $cmd->getConfiguration('topic');
core/class/AbeilleParser.class.php:                Abeille::publishMosquitto( queueKeyAbeilleToCmd, priorityInclusion, "TempoCmd".$cmd->getEqLogic()->getLogicalId()."/".$topic."&time=".(time()+$cmd->getConfiguration('execAtCreationDelay')), $request );
desktop/php/AbeilleEq.php:            tr += '         <?php foreach ( $eqLogic->getCmd('info') as $cmd ) { echo "<option value=\"".$cmd->getConfiguration("topic")."\">".$cmd->getName()."</option>"; } ?>';

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-03-02 à 21 22 27](https://user-images.githubusercontent.com/8549674/109709976-6769c900-7b9d-11eb-9cde-d716d5f3f3ed.png)

Semble Ok.

**Comment by KiwiHC16** [comment]
La remontée d'info fonctionne. 
Je clos l issue et comme tu dis il faudra au fur et a mesure de virer les reference au topic pour les commandes infos.

**Comment by tcharp38** [comment]
Il ne doit pas en rester beaucoup. Peut etre qu'une pour laquelle j'avais un doute.
