### ISSUE TITLE
Ampoule Ikea: Level lié a setLevel. Mais setTemperatureLight pas lié a Temperature.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1830]
Visible avec une commande groupe:
- Level (info) et le cursor de setLevel: se mettent sur la valeur recue.
- Temperature se met mais pas le slider de setTemperature.
![Capture d’écran 2021-02-26 à 16 31 26](https://user-images.githubusercontent.com/8549674/109320226-1467dd00-7850-11eb-9e0f-b59431c1c11c.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Modèle non précisé mais correction appliquée à tous les modèles TRAFRIbulbXXXX
