### ISSUE TITLE
basculer le status de Online de get 0005 à TimeStamp.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1831]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Le status "online" est mis à jour à chaque reception d'une info de l'equipement en meme temps que
- Time-TimeStamp
- Time-Time
Je clos le point. A reouvrir si j'ai mal compris.
