### ISSUE TITLE
Interrupteur/Bouton scénario Sonoff SNZB-01

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1832]
@KiwiHC16 

Parmi  les équipements qui passent en timeout, il y a ce bouton de commande SNZB-01 de chez SONOFF
Pas embêtant, mais du coup, il s'affiche tout le temps en timeout puisqu'on ne récupère rien de lui. Et c'est gênant car chaque fois je me demande quel équipement s'est la malle.
Est-ce normal selon toi ? Disposes tu de ce bouton ?
Je m'intéresse au sujet car il est impossible d'avoir son nom par les commandes. J'ai beau l'activer au moment où je requête  son nom rien ne se passe. Cf ci-dessous. C'est vrai aussi pour son adresse courte et online. Je vais déjà tester avec un timeout très long.

Donc, si c'est normal, je mettrai le timeout à off comme il m'embêtera plus.
Si c'est pas normal, cela veut dire que j'ai eu un problème au moment de la création de l'objet. 

Si tu peux me faire un petit retour là-dessus je t'en remercierai.

![image](https://user-images.githubusercontent.com/36518012/109336894-50a53880-7864-11eb-9a43-ca53ceeaca47.png)

**Comment by KiwiHC16** [comment]
D apres mes notes dans #1322 il faut absoluement faire sa configuration juste apres son inclusion. Normalement Abeille le fait pour toi.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
https://kiwihc16.github.io/AbeilleDoc//SonOff.html?highlight=sonoff

**Comment by KiwiHC16** [comment]
Si la conf se passe bien il doit remonté son niveau batterie suivant la commande setReportBatterie:
MaxInterval=3500
En gros toutes les heures.

Si ce n'est pas le cas il faudrait regarder si on voit dans AbeilleParser ou la Commande Batterie les heures ou l info remonte.

(Je n'ai pas ce bouton sur mon systeme mais j'en ai un en stock qui a servi à l inclusion dans Abeille, si necessaire je pourrai le mettre en route pour tester).

**Comment by mickadam29** [comment]
T'embête pas. Le mien ne me sert qu'à stopper la chaudière et est dans un seul scénario. Je peux faire tous les tests. 
Je vais commencer par le virer. Et l'inclure à nouveau. On verra. Je l'ai intégré il y longtemps. Pas certain que tu avais finalisé les SonOff à l'époque. Je n'ai pas la commande SetReportBatterie dans l'objet.

**Comment by mickadam29** [comment]
Je n'arrive pas à avoir les infos. Sorti du réseau. Inclusion. La création se passe bien. L'appui sur le bouton ne remonte rien dans les logs. Je regarderai dans l'après-midi

**Comment by mickadam29** [comment]
J'ai réussi à l'inclure à nouveau.
Mode dev -> Exclure
Puis 20" appuyé, il a clignoté à 3 ou 4 reprises (intervalle de 5")
Zigate en mode inclusion
Appui env 15" -> Inclusion parfaite et toutes les commandes sont là.

Je pense que le délai de 10" est un peu court, ou le problème d'hier est ailleurs.
Bref, reste à voir si le niveau de pile remonte et si l'objet cesse de passer en timeout.

L'appui est traduit dans le log parser. Tout est fonctionnel. Je vais lui mettre un timeout à 120.

**Comment by KiwiHC16** [comment]
Similaire à #1837

**Comment by mickadam29** [comment]
Cette fois les infos remontent. Le bouton n'est plus vu en timeout
Mais la colonne Repond est passée de OK à NOK

![image](https://user-images.githubusercontent.com/36518012/109419142-47cf7680-79cc-11eb-93b7-ff1c8a92a32e.png)

**Comment by mickadam29** [comment]
Ca fonctionne. Je devais pas avoir le bon modèle lors de la création il y a pls mois.

**Comment by Seby9576** [comment]
Bonjour,

Comment fait on pour l'interprétation du simple, double et long click ? Dans commande j'ai qu'une ligne info.

Merci

**Comment by tcharp38** [comment]
Salut @Seby9576 
Pas sur que tu puisses avec le modele actuel.
Peux tu
- faire les 3 actions (simple, double, long)
- noter l'heure de chacune pour que je retrouve dans le log
- et me filer le package de logs (page support/telecharger tout)
Merci

**Comment by mickadam29** [comment]
Salut

J’utilise ce bouton.
Les actions sont prises en compte et remontent dans un middle-click ou qq chose comme ça. Valeur numérique selon action.

**Comment by Seby9576** [comment]
`[2021-11-29 18:54:24][DEBUG] : msgFromParser(): Abeille1, Zigate version 0003-031D
[2021-11-29 18:54:24][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='Click-Middle', Val='02'
[2021-11-29 18:54:24][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='01-0006-cmd02', Val='1'
[2021-11-29 18:54:24][DEBUG] :   Unknown Jeedom command '01-0006-cmd02'
[2021-11-29 18:54:25][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/5389/01': Attr='0402-01-0000', Val='1988'
[2021-11-29 18:54:25][DEBUG] :   Updating 'online' status for 'Abeille1/5389'
[2021-11-29 18:54:26][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/D852/01': Attr='0402-01-0000', Val='1898'
[2021-11-29 18:54:26][DEBUG] :   Updating 'online' status for 'Abeille1/D852'
[2021-11-29 18:54:26][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/2D3B/01': Attr='0402-01-0000', Val='1890'
[2021-11-29 18:54:26][DEBUG] :   Updating 'online' status for 'Abeille1/2D3B'
[2021-11-29 18:54:30][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='Click-Middle', Val='01'
[2021-11-29 18:54:30][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='01-0006-cmd01', Val='1'
[2021-11-29 18:54:30][DEBUG] :   Unknown Jeedom command '01-0006-cmd01'
[2021-11-29 18:54:36][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/D852/01': Attr='0402-01-0000', Val='1902'
[2021-11-29 18:54:36][DEBUG] :   Updating 'online' status for 'Abeille1/D852'
[2021-11-29 18:54:36][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/2D3B/01': Attr='0402-01-0000', Val='1892'
[2021-11-29 18:54:36][DEBUG] :   Updating 'online' status for 'Abeille1/2D3B'
[2021-11-29 18:54:38][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='Click-Middle', Val='00'
[2021-11-29 18:54:38][DEBUG] : msgFromParser(): Attribute report from 'Abeille1/B955/01': Attr='01-0006-cmd00', Val='1'
[2021-11-29 18:54:38][DEBUG] :   Unknown Jeedom command '01-0006-cmd00'`

**Comment by Seby9576** [comment]
Dans l'ordre 1 clic, 2 clics et enfin clic long.
si je comprend bien
1 clic = 02
2 clics = 01
1 clic long= 00

C'est ca ? Car sur le dashbord il y a rien qui apparait lors de mes tests

**Comment by tcharp38** [comment]
Je laisse @mickadam29 repondre.
Ca m'intrigue.
Dans le standard zigbee j'interprete ca differement
- 2 = toggle
- 1 = on
- 0 = off

**Comment by mickadam29** [comment]
Je confirme les états 

2 = Appui bref (click)
1 =  Double click
0 = Appui long >=3s

**Comment by mickadam29** [comment]
Les états de Seby sont conformes à ce que j’ai

**Comment by Seby9576** [comment]
J'ai fait un test mais ca ne fonctionne pas. est ce que mon scenario est bon svp ? merci
![image](https://user-images.githubusercontent.com/77990298/143937965-24a88a4e-04ae-494e-82ff-6eae33f4f1b5.png)

**Comment by Seby9576** [comment]
Bonjour,

Le bouton fonctionne mais je n'arrive pas a avoir 2 dans middle click. Dans les LOG il apparait bien mais quand je test j'arrive à avoir 1 et 0. Que je fasse 1 clic ou 2 j'obtient 1. Je ne comprend pas pourquoi

Pouvez vous m'aider svp ? Merci

**Comment by mickadam29** [comment]
La valeur 2 est pourtant la plus simple à obtenir. Un appui bref. Une demi seconde et tu devrais avoir 2 comme valeur. Double click très rapide =1 et enfin 0 pour un appui >3s

**Comment by mickadam29** [comment]
J’avais un doute du coup mais j’ai bien le modèle SNZB-01

**Comment by Seby9576** [comment]
Je viens de comprendre, désolé. J'étais en binaire, j'ai mis en autre et maintenant j'ai 02 / 01 / 00.

Merci

**Comment by jbromain** [comment]
Bonjour à tous,

J'ai également ce type de boutons, et je confirme ce qui a été dit concernant le retour du bouton sur le cluster on/off:
- Toggle (02) sur un appui simple
- On (01) sur un appui double
- Off (00) sur un appui long

Le but de ces valeurs (qui peuvent paraitre contre-intuitives) est surtout intéressant si on associe directement le bouton à une lampe: un appui simple va donc envoyer la commande "toggle" à la lampe (valeur 02), ce qui va permettre de l'actionner en un clic (allumer ou éteindre); les autres actions permettent de forcer l'allumage ou de forcer l'extinction, quel que soit son état antérieur.

Je suis parvenu à faire une telle association, mais ce n'a pas été simple, donc je vous partage ici comment je m'y suis pris. 

Une fois inclus et configuré, le bouton semble impossible à réveiller. Même en appuyant dessus avant/pendant/après l'utilisation des fonctions "bind to group", "bind to device" ou "set group remote" d'Abeille, il ne reçoit jamais la commande et reste donc uniquement "lié" à la zigate (= utilisable dans un scénario).

La solution est donc de modifier temporairement le fichier json de l'équipement, afin de lui envoyer la bonne configuration au moment de son inclusion; dans notre cas, il s'agit du fichier WB01.json, situé dans le dossier de jeedom /plugins/Abeille/core/config/devices/WB01/.

(Le plus propre est de copier le dossier WB01 et de le coller à l'intérieur du dossier devices_local. Si présent, il sera utilisé en priorité par Abeille lors de l'inclusion)

La modification consiste simplement à changer la commande "Bind-0006-ToZigate". Le rôle de cette commande est de dire au bouton "prévient la zigate si on te clique dessus":

Avant modification:
![image](https://user-images.githubusercontent.com/72972682/147264787-dc76bdef-c392-49c0-a868-bed65fd5bafe.png)

On va plutôt lui dire "Préviens telle lampe ou telle prise si on te clique dessus"; pour cela, on change la commande comme ceci:
![image](https://user-images.githubusercontent.com/72972682/147265138-4be95c2b-b68e-4a13-b9b8-bee61097aebb.png)

On n'utilise plus "zbBindToZigate" mais "zbBind" tout court, et on précise à quel équipement il faut envoyer l'information (remplacer les X par l'adresse IEEE de votre lampe ou prise). Dans destEp, il faut probablement mettre 01, sauf si vous voulez piloter un équipement ayant plusieurs EndPoint (typiquement un relai à plusieurs entrées aura surement plusieurs EP).

Enregistrez, redémarrez les démons Abeille (dans Configuration > Démons). 
Mettez la zigate en mode inclusion puis ré-appairez votre bouton Sonoff (clic trombone dans le trou "rst" pendant 5 secondes).

Si tout se passe bien, votre bouton est maintenant directement associé à votre lampe, prise, relai... dont vous avez spécifié l'adresse IEEE.

Après cela, vous ne recevrez plus les actions du bouton dans Jeedom; seul l'équipement va les recevoir, et ça fonctionnera même si votre zigate est éteinte ou HS.

**Bug concernant les groupes**
En théorie il est possible de faire la même chose en associant le bouton à un groupe plutôt qu'à une seule adresse IEEE. 
Cela consiste simplement à mettre le numéro de votre groupe (4 caractères) à la place de l'adresse IEEE. 
Malheureusement, ça semble ne pas fonctionner; de mon coté le device me répond qu'il est ok (bind response statut 00), mais en réalité il ne pilote rien du tout.

```
[2021-12-23 16:36:33]     exec cmd Bind-0006-ToGroupePrisesBureau with delay 0
[2021-12-23 16:36:33]       topic=bind0030, request=addr=00124B002268C10F&ep=01&clustId=0006&destAddr=2001&destEp=01
[2021-12-23 16:36:34] Abeille2, Type=8030/Bind response, SQN=41, Status=00, SrcAddrMode=02, SrcAddr=1ADE
```
Je m'y prend peut-être mal, la gestion des groupes et des "bind" est encore extrêmement floue pour moi (cf https://community.jeedom.com/t/zigbee-difference-entre-groupes-et-binding/74516).
