### ISSUE TITLE
Ampoules IKEA / Pas de route pour la joindre

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1833]
@KiwiHC16 

Je ne sais pas si ça peut aider à corriger ces dysfonctionnements avec les ampoules IKEA
Mais comme j'en ai plus qu'une, j'ai facilement identifié ces lignes dans le parser.
Le seul équipement pour qui j'ai des messages de type : 

8702, Unicast does not have a route available.... c'est l'ampoule ikea

Elle fonctionne très bien pourtant.
Je ne sais pas si le fait d'avoir ce genre de message peut provoquer, par ricochet, une instabilité de tout le réseau, mais avec un seul équipement impacté, le réseau est stable. Contrairement à l'époque où j'avais 6 ampoules.

```
Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=0BB2, SQN=20
[2021-02-26 19:03:53][debug] Abeille1, Type=8702/APS Data Confirm Fail:  Extérieur Abeille1-238 set APS_ACK to 0
[2021-02-26 19:03:53][debug] Abeille1, Type=8702/APS Data Confirm Fail status: 0
[2021-02-26 19:03:53][debug] Abeille1, Type=8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=00 (ZPS_EVENT_NONE->), Addr=0BB2
[2021-02-26 19:03:53][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0104 cluster:0000 srcEndPoint:01 destEndPoint:01 sourceAddressMode:02 srcAddress:0BB2 destinationAddressMode:02 dstAddress:Ruche
[2021-02-26 19:03:53][debug] Abeille1, Type=8100/Read individual attribute response, SQN=02, Addr=0BB2, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=001C
[2021-02-26 19:03:53][debug]   ModelIdentifier='TRADFRI bulb E27 opal 1000lm', trimmed='TRADFRIbulbE27opal1000lm', [Modelisation]
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0BB2, DestEP=01, ClustId=0000
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, found: [Extérieur][Abeille1-238] set APS_ACK to 1
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, APS_ACK: 1
[2021-02-26 19:03:53][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=A4, PacketType=0041
[2021-02-26 19:03:53][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0000 cluster:8001 srcEndPoint:00 destEndPoint:00 sourceAddressMode:02 srcAddress:0BB2 destinationAddressMode:02 dstAddress:Ruche
[2021-02-26 19:03:53][debug] Abeille1, Type=8041/IEEE Address response, SQN=A4, Status=00, ExtAddr=000B57FFFE4AAC1A, ShortAddr=0BB2, NumberOfAssociatedDevices=00, StartIndex=00
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0BB2, DestEP=00, ClustId=0001
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, found: [Extérieur][Abeille1-238] set APS_ACK to 1
[2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, APS_ACK: 1
```

Si je comprends bien le tableau, Zigate atteint l'ampoule extérieur Abeille-238 en passant par l'ampoule Abeille-428. Vu les distances ça paraît normal.
C'est la seule entrée Abeille-238 dans la table des liens.

![image](https://user-images.githubusercontent.com/36518012/109339295-bd6e0200-7867-11eb-87bb-69208844707d.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Docodé ca donne 

```
A - [2021-02-26 19:03:53][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=0BB2, SQN=20
B - [2021-02-26 19:03:53][debug] Abeille1, Type=8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=00 (ZPS_EVENT_NONE->), Addr=0BB2
C - [2021-02-26 19:03:53][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0104 cluster:0000 srcEndPoint:01 destEndPoint:01 sourceAddressMode:02 srcAddress:0BB2 destinationAddressMode:02 dstAddress:Ruche
D - [2021-02-26 19:03:53][debug] Abeille1, Type=8100/Read individual attribute response, SQN=02, Addr=0BB2, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=001C
E - [2021-02-26 19:03:53][debug]   ModelIdentifier='TRADFRI bulb E27 opal 1000lm', trimmed='TRADFRIbulbE27opal1000lm', [Modelisation]
F - [2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0BB2, DestEP=01, ClustId=0000

A - APS fail (Buffer) - 0BB2 - Extérieur Abeille1-238 => Zigate indique ne pas avoir la route, mets la commande en attente et demande la route. 
B - Route discovery confirm => la route est trouvée
C - Une info revient de 0BB2 mais on ne sait pas laquelle
D - Abeille demande le nom de l ampoule
E - 0BB2 repond avec son nom
F - 0BB2 ACK la demande
```

Donc tout fonctionne comme voulu.

**Comment by KiwiHC16** [comment]
Peux tu me partager la conf que tu as sur tes systemes ?
Le mien:
![Capture d’écran 2021-02-27 à 10 54 25](https://user-images.githubusercontent.com/8549674/109383970-2a29e080-78ea-11eb-91ea-3f7a63754d1a.png)

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/109385020-0fa73580-78f1-11eb-81ef-48ad228dde80.png)
 Pour rappel. Master installé le 24/02 au matin. Jeedom 4.1.20/ Firmware 3.1D

**Comment by mickadam29** [comment]
> Docodé ca donne
> 
> ```
> A - [2021-02-26 19:03:53][debug] Abeille1, Type=8702/APS Data Confirm Fail, Status=D4 (ZPS_NWK_ENUM_FRAME_IS_BUFFERED->Unicast frame does not have a route available but it is buffered for automatic resend. / https://github.com/fairecasoimeme/ZiGate/issues/207), SrcEP=01, DestEP=01, DestMode=02, DestAddr=0BB2, SQN=20
> B - [2021-02-26 19:03:53][debug] Abeille1, Type=8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=00 (ZPS_EVENT_NONE->), Addr=0BB2
> C - [2021-02-26 19:03:53][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0104 cluster:0000 srcEndPoint:01 destEndPoint:01 sourceAddressMode:02 srcAddress:0BB2 destinationAddressMode:02 dstAddress:Ruche
> D - [2021-02-26 19:03:53][debug] Abeille1, Type=8100/Read individual attribute response, SQN=02, Addr=0BB2, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=001C
> E - [2021-02-26 19:03:53][debug]   ModelIdentifier='TRADFRI bulb E27 opal 1000lm', trimmed='TRADFRIbulbE27opal1000lm', [Modelisation]
> F - [2021-02-26 19:03:53][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0BB2, DestEP=01, ClustId=0000
> 
> A - APS fail (Buffer) - 0BB2 - Extérieur Abeille1-238 => Zigate indique ne pas avoir la route, mets la commande en attente et demande la route. 
> B - Route discovery confirm => la route est trouvée
> C - Une info revient de 0BB2 mais on ne sait pas laquelle
> D - Abeille demande le nom de l ampoule
> E - 0BB2 repond avec son nom
> F - 0BB2 ACK la demande
> ```
> 
> Donc tout fonctionne comme voulu.

Il faut être un expert Zigbee pour comprendre ça. Mais tu confirmes que c'est le bon fonctionnement. Et ça confirme aussi que l'ampoule est pilotable.
1 Question : Pourquoi Zigate n'a pas la route ? On sait l'expliquer ?

 Par contre, quand les ampoules étaient KO, si Zigate ne connaissait que la route au travers de l'ampoule, et que cette dernière était sorti du réseau, je comprends les incidents qui en découlaient

**Comment by KiwiHC16** [comment]
Les routes sont temporaires pour s adapter aux evolution du reseau. Quand une route n est pas dipo. L equipement demande la route et les routeurs proposent des routes. L equipement choisi la meilleur (cf voir la norme). Si pas de dialogue alors la route est oubliée (petite memoire dans les equipements donc on fait de la place)

Mon scénario qui expliquerai le comportement que tu as eu:
- l ampoule change d adresse courte (fait partie de la norme). Elle ne sort pas du reseau, elle change juste d adresse. De ce fait tu n as pas de leave dans les traces
- l info est perdue et abeille n est pas au courant de la nouvelle adresse (scenario pas prévu dans Abeille, bug,...)
- Quand tu demandes une action sur l ampoule, Abeille adresse l ampoule sur l ancienne adresse. Il n y a plus personne a cette adresse.
- Si Abeille ou une telecommande envoie sur l adresse de groupe cela fonctionne car cette adresse n a pas changée.

Dans ce cas on peut recuperer la nouvelle adresse depuis abeille par des actions manuelles et mettre a jour Abeille et on recupere la main sur l ampoule.

Je vais rester vigilant sur ce scenario pour essayer de comprendre pourquoi Abeille n est pas mis a jour.

En esperant que c est bien cela qui se passe sur le reseau zigbee.

**Comment by mickadam29** [comment]
Un collecte LQI n'aurait pas dû faire apparaitre un objet inconnu dans ce cas ?

Je me réponds à moi même. Ce matin (24h après le post), il y a un objet inconnu

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/109410849-4d15cc80-799e-11eb-86a0-397af085ffea.png)

Cette fois c'est bien représenté et avec tes explications je comprends. On voit en effet que l'ampoule extérieure passe par une autre pour atteindre la zigate. Et inversement.

**Comment by KiwiHC16** [comment]
"Un collecte LQI n'aurait pas dû faire apparaitre un objet inconnu dans ce cas ?" -> normalement si le changement d adresse a été fait depuis quelques temps la réponse est oui.
