### ISSUE TITLE
Ajouter un bouton "get IEEE" a droite de short/IEEE (si adresse IEEE pas dispo par exemple)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1834]
![Capture d’écran 2021-02-27 à 10 44 34](https://user-images.githubusercontent.com/8549674/109383747-c8b54200-78e8-11eb-9cec-21249ca0bb0e.png)

Afin de permettre a l utilisateur de recuperer l adresse si elle n est pas dispo.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
@KiwiHC16 
Une adresse IEEE est toujours fournie lors du "device announce" n'est ce pas ?
Ou tu as vu des cas zarbis ?

**Comment by tcharp38** [comment]
Il y a encore une interrogation automatique si l'adresse IEEE est inconnue mais normalement ce genre de cas ne doit pas apparaitre.
Ca pourrait etre le cas que si pour une raison ou une autre l'équipement Jeedom à été supprimé sans être exclu du réseau.

Je ne cloture pas encore car la "récupération" des équipements fantomes (plus sur Jeedom mais toujours sur Zigbee) à peut etre besoin revue.

**Comment by tcharp38** [comment]
Bouton dispo dans la page équipement/avancé

![image](https://user-images.githubusercontent.com/35221038/144499625-0e841835-5cbf-478e-aa7e-16dae5dac5ae.png)

Je clos
