### ISSUE TITLE
Implementer OTA pour Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1836]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
https://github.com/pipiche38/Domoticz-Zigate/blob/stable/Classes/OTA.py

**Comment by KiwiHC16** [comment]
Convert format ?
https://github.com/pipiche38/Domoticz-Zigate/tree/stable/OTAFirmware

**Comment by mickadam29** [comment]
Je te suis dans l'OTA. Ces ampoules étant dorénavant inutiles, et ayant un réseau Zigbee de test, je pourrais te faire les tests que tu veux. Sauf si dès le premier, mon ampoule se transforme en brique. Mais ça j'assume le risque pour te permettre d'avancer sur le sujet.

**Comment by tcharp38** [comment]
Version préliminaire ok avec Ikea on/off switch => 211122-BETA-1

**Comment by tcharp38** [comment]
La version 211205-STABLE-1 contient deja de quoi faire.
Confirmé fonctionnel pour Ikea.
Meme si on peut encore améliorer les choses (chantier futur), je clos le sujet pour l'instant.
