### ISSUE TITLE
Toujours soucis avec SNZB-04

### ISSUE THREAD

**Issue by shadsnob** [KiwiHC16/Abeille#1837]
1/ Version (Abeille.version)
============================
2021-02-23 01:00:09

2/ Linux
========
["Raspbian GNU\/Linux 10 \\n \\l",""]
["Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

Sa fait un moment que j'ai toujours les mêmes soucis sur une ruche et son sonoff SNZB-04, **il remonte pas la batterie** il se met sans arrêt en NOK et dans le Network List, il voit rien du tout alors que tout est intégrer dans jeedom par mes scenario qui fais les actions demandes. J'ai refait une update de la clé et refait des intégrations toujours la même chose je n'arrive pas a comprenne le soucis car pour le nok si j'ouvre la porte la il réapparaît.

[Abeille_update.log](https://github.com/KiwiHC16/Abeille/files/6054955/Abeille_update.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6054956/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6054957/AbeilleParser.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/6054958/AbeilleConfig.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6054959/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6054960/Abeille.log)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
#1573

**Comment by KiwiHC16** [comment]
Door Sensor #1325

**Comment by KiwiHC16** [comment]
Dans les commandes du module dans Abeille. Tu dois trouver 2 commandes: bind, setreport pour batterie.
Ouvre la porte et en même temps envoie la premiere commande.
Ouvre de nouveau la porte et envoie la seconde commande.
Fais plusieurs fois ces manips éventuellement et attend quelques heures et dit moi ce qu'il en est.

**Comment by shadsnob** [comment]
Bonjour dans le module de l'équipement sonoff voici se que j'ai
![Sans titre](https://user-images.githubusercontent.com/55192541/109413814-aafee000-79af-11eb-9307-4a35c49a2a28.png)

**Comment by shadsnob** [comment]
J'ai essayer votre manipulation qui se trouve dans la ruche et pas dans l’équipement sonoff mais rien n'y fait je vous ai mis les infos fait dans la journée ainsi que a certains endroit ou j'ai vu des erreurs que j'avais pas. Le jeedom est passer a la version 4.1.20 et toujours votre plugin en beta version 2021-02-23 01:00:09

![1](https://user-images.githubusercontent.com/55192541/109427155-554b2780-79f1-11eb-9473-53818bdc5642.png)
![2](https://user-images.githubusercontent.com/55192541/109427157-5714eb00-79f1-11eb-8f5d-b1a37f07abfe.png)
![3](https://user-images.githubusercontent.com/55192541/109427159-58461800-79f1-11eb-8ef4-af27e12bbde0.png)
![4](https://user-images.githubusercontent.com/55192541/109427332-3b5e1480-79f2-11eb-9093-ec1c27dfa82b.png)

[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6057350/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6057351/AbeilleParser.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/6057352/AbeilleConfig.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6057353/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6057355/Abeille.log)

**Comment by shadsnob** [comment]
Bonjour est ce que vous rencontrer les mêmes problèmes que moi dans votre configuration avec le même matos ?

**Comment by KiwiHC16** [comment]
Je vais sortir celui que j ai du placard pour essayer dès que je peux.

**Comment by shadsnob** [comment]
Bonjour merci de m'aider et de me diriger sur qui est le fautif le plugin, le matériel zigate, le firmware ou une erreur de manipulation de ma part et comme c’était un nouveau produit je voulais remplacer mes aquara qui fonctionne niquel.
J'ai activer l'option "Blocage récupération équipement" pour voir si je voyais d'autre trames fantômes et je vois crash driver usb

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6097475/Abeille.log)

**Comment by KiwiHC16** [comment]
```
[2021-03-07 17:00:05][DEBUG] : Check USB driver potential crash
```

C est Abeille qui regarde si cela va bien et on il n y a pas de message d erreur donc Ok pas de soucis trouvé.

J ai pas eu le temps encore de le sortir du placard.

**Comment by shadsnob** [comment]
Bonjour je viens de faire la mise a jour du plugin et lorsque je fais un "test d’intégrité" dans "configuration", "options avancées"
j'ai dans le log plein de message que je sais pas a quoi sa correspond par rapport a mon problème qui doit être sous mes yeux

1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Raspbian GNU\/Linux 10 \\n \\l",""]
["Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/6115344/AbeilleConfig.log)

**Comment by tcharp38** [comment]
Salut
Juste qq mots à propos du test d'intégrité.
Normalement il n'est dispo qu'en mode developpeur. Le process n'est pas mature.

D'autre part, il ne peut etre valide sur le master car ca sous entendrait qu'une signature complete soit refaite à chaque correction/mise-à-jour. Bref si tu es sur le master, aucun interet.

C'est le cas ?

**Comment by shadsnob** [comment]
oui je le suis puisque sur mon jeedom il me marquait qu'il avait une mise a jour a faire sur abeille

**Comment by tcharp38** [comment]
Jeedom peut t'indiquer qu'une mise à jour est dispo quelle que soit la source (market, github, et stable, dev ou autre).
Donc je suppose que tu es sur master pour une bonne raison.
Du coup oublies le test d'intégrité.

**Comment by tcharp38** [comment]
J'avoue ne pas savoir comment Kiwi délivre sa beta. Donc pour moi ce process n'est pas fiable meme si c'est moi qui l'ai mis en place. Ca impose qu'on regenere les signatures tout de suite avant la livraison et je sais pas si il l'a fait et si c'est systematique.
Donc pour l'instant oublie cette fonctionalité que je pensais n'avoir mis en place que pour le mode "developpeur" d'ailleurs.

**Comment by shadsnob** [comment]
Bonjour toujours soucis j'ai réinstaller tout le système ça fonctionne cinq minutes ou je vois bien tout en vert et une fois le timeout finis plus rien a part quand je fais manuellement ouvrir les actions fonctionne dans jeedom mais pas la remonter du repond et encore moins l'affichage de la batterie et je suis tombe sur ça mais comprend pas comment le faire leur méthode https://zigate.fr/produits-sonoff-compatible-zigate/compatible/snzb-04capteurdouverturedeporte/

**Comment by tcharp38** [comment]
Salut @shadsnob 
Quel est le status de ton côté ?

**Comment by tcharp38** [comment]
Pas de news. Je clos.
A réouvrir si besoin
