### ISSUE TITLE
Rafraichir les infos ruche au demarrage du daemon.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1839]
![Capture d’écran 2021-02-28 à 10 57 22](https://user-images.githubusercontent.com/8549674/109414553-bfdd7280-79b3-11eb-9162-922b0601c62b.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
@KiwiHC16 
Tu fais allusion à quelle(s) info(s) ?

**Comment by tcharp38** [comment]
#1916

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si nouvelle livraison pas suffisante
