### ISSUE TITLE
Ajouter bouton reset dans la conf de la ruche:

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1840]
![Capture d’écran 2021-02-28 à 10 58 34](https://user-images.githubusercontent.com/8549674/109414583-e8656c80-79b3-11eb-8ab2-74ab54f82ca4.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Ca veut dire qu'on vire le reset de la page config ?
Suis assez partant avec ça. Peu d'interet à cet endroit je trouve.
T'en pense quoi ?

**Comment by KiwiHC16** [comment]
Super.

**Comment by tcharp38** [comment]
C'est dans le master. Je clos
