### ISSUE TITLE
LIDL Multiprise USB  HG06338-FR

### ISSUE THREAD

**Issue by sbx59** [KiwiHC16/Abeille#1848]
Bonjour,

L'inclusion des périphérique LIDL est t'elle prévu ? ( pour le moment il sont reconnue en SONOFF )
merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
En cours. Il y a des issues pour les inclure. Faire une recherche sur LIDL.

**Comment by sbx59** [comment]
Ici, je n'ai rien vu.

**Comment by KiwiHC16** [comment]
https://github.com/KiwiHC16/Abeille/issues?q=is%3Aissue+is%3Aopen+LIDL

**Comment by sbx59** [comment]
Au cas ou voici le fichier.
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6060405/AbeilleParser.log)

**Comment by sbx59** [comment]
Voici l'image : 

![352635878f37af6b5ac895771b96beae](https://user-images.githubusercontent.com/78600632/109482386-39419780-7a7e-11eb-8baa-5b430cf3d3fb.jpg)

**Comment by KiwiHC16** [comment]
```
[2021-03-01 10:00:27][debug] Abeille1, Type=8100/Read individual attribute response, SQN=3C, Addr=56ED, EP=01, ClustId=0000, AttrId=0004, AttrStatus=00, AttrDataType=42, AttrSize=0010
[2021-03-01 10:00:27][debug]   ManufacturerName='_TZ3000_vzopcetz', trimmed='_TZ3000_vzopcetz', {"Abeille1\/56ED":{"time":1614589227,"ManufacturerName":"_TZ3000_vzopcetz"}}, [Modelisation]
```

Un debut d info interessant mais le log est apres les manipulations.

Pourrais tu refaire l inclusion apres avoir supprimé d'Abeille l'équipement et re-paratager le lof AbeilleParser ?

**Comment by sbx59** [comment]
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6062342/AbeilleParser.log)

J'ai laisser tourner plus longtemps, et re-allumé la multi prise car une fois appareiller elle s’éteint.

**Comment by KiwiHC16** [comment]
Toujours rien. On va essayer autrement.
D apres les traces elle est a l adresse: 0057
Dans la ruche peux tu afficher la commande getName:
![Capture d’écran 2021-03-01 à 16 20 36](https://user-images.githubusercontent.com/8549674/109517936-11682900-7aaa-11eb-9c38-4a93cf855f30.png)
Faire la commande ci dessus et partager ce qui remonte dans les logs AbeilleParser et Abeille.

**Comment by sbx59** [comment]
Je n'ai pas l'impression que cela a fait quelque chose mais je partage : 

![image](https://user-images.githubusercontent.com/78600632/109521702-de279900-7aad-11eb-9ac7-9e39273befef.png)

Abeille 👍 

```
[2021-03-01 16:53:47][DEBUG] : execute(type=action, options={"title":"0057","message":"01","utid":"0"})
[2021-03-01 16:53:47][DEBUG] : topic updated: CmdAbeille1/Ruche/getName
[2021-03-01 16:53:47][DEBUG] : request updated: address=0057&destinationEndPoint=01
[2021-03-01 16:53:54][DEBUG] : Launch of Abeille_pre_update_analysis()
[2021-03-01 16:53:54][DEBUG] : End of Abeille_pre_update()
[2021-03-01 16:54:02][DEBUG] : publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/Ruche\/getVersion&time=1614614062","payload":"Version"}' vers queue 123
```

Parser 👍 
```
[2021-03-01 16:53:47][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=75, PacketType=0100
[2021-03-01 16:53:47][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0104 cluster:0000 srcEndPoint:01 destEndPoint:01 sourceAddressMode:02 srcAddress:0057 destinationAddressMode:02 dstAddress:Ruche
[2021-03-01 16:53:47][debug] Abeille1, Type=8100/Read individual attribute response, SQN=75, Addr=0057, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=0006
[2021-03-01 16:53:47][debug]   ModelIdentifier='TS011F', trimmed='TS011F', [Modelisation]
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0057, DestEP=01, ClustId=0000
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, found: [Zigbee][Abeille1-70] set APS_ACK to 1
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, APS_ACK: 1
[2021-03-01 16:53:47][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=C3, PacketType=0041
[2021-03-01 16:53:47][debug] Abeille1, Type=8002 (decoded but not processed - message unknown): status: 00 profile:0000 cluster:8001 srcEndPoint:00 destEndPoint:00 sourceAddressMode:02 srcAddress:0057 destinationAddressMode:02 dstAddress:Ruche
[2021-03-01 16:53:47][debug] Abeille1, Type=8041/IEEE Address response, SQN=C3, Status=00, ExtAddr=BC33ACFFFE58F6C9, ShortAddr=0057, NumberOfAssociatedDevices=00, StartIndex=00
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, Status=00, DestAddr=0057, DestEP=00, ClustId=0001
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, found: [Zigbee][Abeille1-70] set APS_ACK to 1
[2021-03-01 16:53:47][debug] Abeille1, Type=8011/APS data ACK, APS_ACK: 1
[2021-03-01 16:54:23][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0010
[2021-03-01 16:54:23][debug] Abeille1, Type=8010/Version, Appli=3, SDK=031D
```

**Comment by sbx59** [comment]
Multiprise allumé et ON
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6062828/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6062829/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
```
[2021-03-01 16:53:47][debug]   ModelIdentifier='TS011F', trimmed='TS011F', [Modelisation]
```

**Comment by KiwiHC16** [comment]
On a des infos interressasntes. Il porte le meme nom qu un qutre equipement alors il utilise un modele qui ne lui va pas.
Par contre l objet créé continet le On et Off.
Je vois dans les traces que tu as joué avec.
Je pense que si tu fais on et off la premire prise devrait changer d etat. Peux tu brancher une lampe dessus et me confirmer ?

**Comment by sbx59** [comment]
Oui c'est bien cela. Uniquement la première prise. Les deux autre reste éteinte.

Le on off et toggle fonctionne

**Comment by KiwiHC16** [comment]
Nickel je vais préparer un modèle.

**Comment by wikijm** [comment]
Bonjour à tous,

Mêmes éléments de mon côté (première prise pilotable, avec ON, OFF et Toogle).
Si besoin, je peux tester avec une version beta 😉

@KiwiHC16 Besoin d'une image détourée/transparente de la multiprise ?

**Comment by wikijm** [comment]
Note : La notice parle du produit "SILVERCREST BLOC MULTIPRISE USB SPSZ 3 A1".

**Comment by wikijm** [comment]
Discussion pour le même périphérique : https://github.com/Koenkk/zigbee2mqtt/issues/5204

**Comment by 8Thomas8** [comment]
Salut.

J'ai acheté également ce modèle pour tester. Est-ce qu'il y a encore besoin de quelque chose ?

**Comment by 8Thomas8** [comment]
En partant d'un autre modèle, j'ai fait édité le model TS011F pour faire marcher correctement ma prise et ça fonctionne bien. N'ayant pas de TS011F, ça ne me pose pas de soucis, mais si quelqu'un m'explique comment faire pour que la multiprise soit dissocié de TS011F, ça m'intéresse et je pourrais éventuellement proposer une pull request.

Si intéressé, voici mon TS011F.json actuellement, je peux contrôler les 3 prises.

```
{
  "TS011F": {
    "nameJeedom": "Yagusmart Tuya ZigBee Smart Switch",
    "timeout": "60",
    "Comment": "Intégration matériel prochaine MAJ #1569",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5ceosfqsds766ssdgdfzsddzze5d4lkjyd4",
      "icone": "TS0121",
      "mainEP": "01"
    },
    "Commandes": {
      "include1": "SW",
      "include2": "societe",
      "include3": "nom",
      "include4": "etatCharge0",
      "include4 2": "etatCharge1",
      "include4 2 2": "etatCharge2",
      "include5": "On",
      "include5 2": "On1",
      "include5 2 2": "On2",
      "include6": "Off",
      "include6 2": "Off1",
      "include6 2 2": "Off2",
      "include7": "Toggle",
      "include7 2": "Toggle1",
      "include7 2 2": "Toggle2",
      "include8": "getEtat",
      "include9": "getManufacturerName",
      "include10": "getModelIdentifier"
    }
  }
}
```

**Comment by sbx59** [comment]
Bonjour @8Thomas8 

Je débute ... Tu serai me dire comment on ajoute ton fichier ? Cela m'intéresse

**Comment by wikijm** [comment]
Merci @8Thomas8  pour ton fichier TS011F.json, cela fonctionne parfaitement 😄 

@sbx59 Voici une petite procédure à suivre :
1) Installer le plugin Jeexplorer
2) Aller modifier le fichier TS011F.json présent dans le dossier html/plugins/Abeille/core/config/devices/TS011F/
![image](https://user-images.githubusercontent.com/10724809/110216111-9dfd5780-7ead-11eb-8576-3e30fb90af3d.png)
3) Supprimer la multiprise dans le plugin Abeille
4) La ré-appairer
5) Profiter 😉

**Comment by wikijm** [comment]
En complément :
* Description sur le site de la Zigbee Alliance : https://zigbeealliance.org/fr/zigbee_products/smart-connect-strip-3/
* Photo transparente sur le site de la Zigbee Alliance : https://s3.amazonaws.com/assets.knackhq.com/assets/54e658034b4f44e42fb18201/5efc37609a1367001556526e/original/p1823fr.png

**Comment by KiwiHC16** [comment]
@wikijm 
peux tu nommer le fichier 
TS011_ _TZ3000_vzopcetz.JSON

oui je suis preneur de l image détourée.

Dans AbeilleParser il faut ajouter une exception
https://github.com/KiwiHC16/Abeille/blob/master/core/class/AbeilleParser.class.php#L2868

Et faire un pull request sur la branche master.

**Comment by 8Thomas8** [comment]
Je regardais comment faire.

Du coup j'ai créé une pull request.

(Le uniqId il est généré aléatoirement à partir de quelque chose / une règle, ou il est totalement aléatoire?)

En revanche pour l'exception dans AbeilleParser.class, j'ai plus de mal. L2868 je rajoute TS011F dans l'Array, mais il faut que j'ajoute le manufacturer dans le modèle json ou il n'y a que ça à faire ?

**Comment by KiwiHC16** [comment]
Ton PR dans le master. Il faudra tester. 
sera dans la version bêta mardi et en stable mardi dans 8 jours. 

UniqId est unique pour identifier le modèle de façon unique. Pour me simplifier la vie je mets AAAAMMDD_HHMmss depuis quelques mois. De toute façon ce n est pas utilisé par le code.

**Comment by KiwiHC16** [comment]
Oui le nom doit être mis à jour dans le json aussi. Le même nom partout.

**Comment by 8Thomas8** [comment]
@KiwiHC16 J'ai testé en modifiant mes fichiers, mais lors de l'association, ça me remet TS011F. Il doit manquer quelque chose.

Edit: Après reboot de deamon: Nouvel équipement 'TS011F__TZ3000_vzopcetz' inconnu. Utilisation de la config par défaut. [Modelisation]

Edit 2: C'est bon j'ai fait toutes les corrections nécessaires, il reste l'image qui n'est pas au bon format, une fois qu'elle est bonne, je fais mettrais à jour ma PR.

**Comment by 8Thomas8** [comment]
Je suis en train de voir que si tu allumes la multiprise avec le bouton qui est dessus, tu n'as pas l'état qui se met à jour sur Jeedom.

J'ai donc ajouté ça et ça marche très bien, pour la première prise : 
```
        "include11": "BindToZigateEtat",
    	"include12": "setReportEtat"
```

J'ai essayé de faire de la même manière que les autres commandes pour l'appliquer aux 2ème et 3ème prise, mais ça ne fonctionne pas :

```
            "include11": "BindToZigateEtat",
            "include11 2": "BindToZigateEtat1",
            "include11 2 2": "BindToZigateEtat2",
    	    "include12": "setReportEtat",
            "include12 2": "setReportEtat1",
            "include12 2 2": "setReportEtat2"
```

J'ai essayé de dupliquer les templates BindToZigate.json et setReportEtat.json, comme le sont les templates On et Off, mais sans succès.

**Comment by wikijm** [comment]
Bonjour @KiwiHC16

Voici l'image (elle vient de https://zigbeealliance.org/fr/zigbee_products/smart-connect-strip-3/) :
![p1823fr](https://user-images.githubusercontent.com/10724809/110440108-96f66500-80b8-11eb-95cb-da2c6ff294c8.png)

**Comment by sbx59** [comment]
J'ai vu que la multiprise étais inclu dans la version beta. 
Je ne sais pas si la fonction d'allumer une prise au choix fonctionne pour vous ?

**Comment by wikijm** [comment]
Bonjour @sbx59 

Grâce au travail de @KiwiHC16  et @8Thomas8, tu devrais avoir suffisamment de détails dans ce ticket pour l'appliquer dès à présent chez toi.

Si cela fonctionne en l'état, il reste encore du travail à faire avant de déployer une mise à jour (intégration d'images, tests unitaires et d'intégration, etc).

N'hésites pas à tester et revenir ici en nous expliquant à quel endroit tu bloques. Cela aidera sans doute des personnes dans la même situation 😄

**Comment by 8Thomas8** [comment]
C'est ok pour l'inclusion de la multiprise et l'intégration de l'image, mais ce n'est pas encore release.

Si vous voulez le faire manuellement et tester, voir :
- https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TS011F__TZ3000_vzopcetz
- https://github.com/KiwiHC16/Abeille/blob/master/images/node_TS011F__TZ3000_vzopcetz.png

J'ai testé chez moi l'inclusion / image, et c'est ok. Il faut penser à remettre TS011F  dans son état d'origine et créer le device TS011F__TZ3000_vzopcetz comme dans les liens ci-dessus.

Le dernier truc qu'il restera à faire marcher, c'est le report d'info quand tu utilises le bouton de la prise, directement.

**Comment by 8Thomas8** [comment]
> @8Thomas8 regardes le modele Abeille/core/config/devices/TS0121/TS0121.json et essayes de recuperer de ce modele le binEtat et serReportEtat. Ca devrait marché pour la premiere prise au moins.

@KiwiHC16 Oui pour la première prise c'est ok, c'est ce que j'ai fais. C'est pour les autres.

**Comment by 8Thomas8** [comment]
Cool, comme ça on est déjà 2 chez qui l'inclusion et le contrôle marchent :P

**Comment by KiwiHC16** [comment]
> > @8Thomas8 regardes le modele Abeille/core/config/devices/TS0121/TS0121.json et essayes de recuperer de ce modele le binEtat et serReportEtat. Ca devrait marché pour la premiere prise au moins.
> 
> @KiwiHC16 Oui pour la première prise c'est ok, c'est ce que j'ai fais. C'est pour les autres.

Donc tu as le retour d etat qui fonctionne pour le premiere prise ? Si tu la pilote avec une telecommande, elle remonte son etat dans Abeille ?

**Comment by sbx59** [comment]
Juste une remarque ( je ne sais pas si je peux le faire moi meme )

Mettre les On et Off du meme coté :

![image](https://user-images.githubusercontent.com/78600632/110611667-b8765000-818f-11eb-8c16-e758d53dfc02.png)

**Comment by sbx59** [comment]
@8Thomas8 
impeccable merci !

![image](https://user-images.githubusercontent.com/78600632/110624264-3f322980-819e-11eb-821f-d4966250fb6d.png)

**Comment by mickadam29** [comment]
Je connaissais pas la disposition. Merci @8Thomas8

**Comment by sbx59** [comment]
Pour moi la version beta ( ajout de la prise et utilisation ) fonctionne parfaitement !

**Comment by 8Thomas8** [comment]
> Donc tu as le retour d etat qui fonctionne pour le premiere prise ? Si tu la pilote avec une telecommande, elle remonte son etat dans Abeille ?

J'ai l'impression que je ne peux pas la contrôler via une télécommande Abeille.

**Comment by tcharp38** [comment]
Salut @sbx59 @8Thomas8 
Quel est le status de ce modele HG06338 aujourd hui ?
On peut clore le point ?

**Comment by 8Thomas8** [comment]
@tcharp38 Le dernier point abordé n'est pas résolu, mais sinon c'est fonctionnel.

A savoir, la première prise se signale bien comme allumée, si on allume la multiprise depuis le bouton de celle ci, mais je n'ai pas réussi à faire la même chose pour les prises 2 et 3.

**Comment by tcharp38** [comment]
Peux tu reinclure ta prise apres avoir
- ecrasé le fichier JSON avec celui ci
[TS011F__TZ3000_vzopcetz.zip](https://github.com/KiwiHC16/Abeille/files/7037913/TS011F__TZ3000_vzopcetz.zip)
A decompresser dans "core/config/devices/TS011F__TZ3000_vzopcetz/
- redemarré Abeille

**Comment by tcharp38** [comment]
Salut @8Thomas8 
Partant pour bosser un peu sur ce sujet ?

**Comment by tcharp38** [comment]
Sujet remplacé par #2354
