### ISSUE TITLE
Lancement en double de Checksocat.sh

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#1850]
Installé ce jour la version Abeille 2021-03-02 01:00:14 sur jeedom 4.1.20 avec 2  Zigate en wifi 

Et depuis la mise à jour ,  checksocat.sh est lancé de façon récurrente alors que l'installation est bonne et le reste d'abeille fonctionne et dialogue avec les 2 zigates en wifi.

Voir la log AbeiileConfig.log ci-jointe.
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/6069567/AbeilleConfig.log)

**Comment by tcharp38** [comment]
Salut

Ce check est fait automatiquement chaque fois que tu ouvres la page de config et si tu as une zigate wifi.

Quel est le souci ?

**Comment by Krankhore** [comment]
Bonjour,
je ne vais plus aller sur la page de config pendant quelques temps pour voir si ça s'arrête.

J'étais effectivement surpris d'en avoir une série et surtout d'en avoir deux dans la même seconde;. Mais peut être qu'effectivement je suis aller plusieurs fois sur la page de config pour relancé le démon qui s'était arrêté après la mise à jour.
 
Merci du retour

**Comment by Krankhore** [comment]
Après test, c'est bien ça. Se lance uniquement lorsque je vais sur la page de configuration.

Par contre , il y a systématiquement **deux** lancements du check
