### ISSUE TITLE
Liste d'équipements supportés à revoir

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1855]
Cette liste
https://kiwihc16.github.io/AbeilleDoc/listeCompatibilite.html

- n'est pas facilement utilisable. On trouve le modele surtout par reconnaissance de la photo
- manque dans la plupart des cas la ref constructeur (limite la recherche), voir la marque
- n'est pas triable par marque et/ou modele

Bref pour moi a revoir et à normaliser.

**Comment by KiwiHC16** [comment]
Cette liste est auto générée sur la base des modèles. Le script est le meme que 

![Capture d’écran 2021-03-05 à 20 34 03](https://user-images.githubusercontent.com/8549674/110164772-21f20980-7df2-11eb-9720-32e9dea2ad9a.png)

en changent les parametres pour generer le format pour la doc.

Ne doit pas être trop difficile a modifier;

Il faudrait ajouter les chmaps qui vont bien dans les modeles. Il faudrait les documenters pour être sure qu on utilise toujours le meme format.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by tcharp38** [comment]
Premiere update faite.
Manque le tri par fabricant ou modele

**Comment by tcharp38** [comment]
Tri par colonne ajouté dans le master.
8046018f6a1e3c31bd0ea9c06674e20ce5b44605
