### ISSUE TITLE
Bizarrerie Zigbee

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1858]
@KiwiHC16 

Ce matin, j'ai modifié ma Pizigate avec antenne PCB en y ajoutant une antenne. En effet, celle-ci dispose des 2 modes. Il suffit de dessouder le shunt entre la puce zigbee et l'antenne PCB et de le faire entre la puce et le connecteur d'antenne extérieure. La sensibilité en est ainsi augmenté. Mais c'est pas le sujet.

Lors de la remise sous tension de cette solution qui me sert au dev DIY et non à ma prod, cela a provoqué une sortie de réseau des routeurs à proximité. Les plus éloignés n'ont pas été impactés. Et du coup, la sortie également du réseau des end device qui étaient attachés à ces routeurs. Grosse pagaille donc ! Ce qui est étonnant, c'est que le réseau de prod est sur le canal 11 et la pizigate sur le 15. Quand je parle de sortie de réseau, je veux dire qu'il a fallu faire une nouvelle inclusion de tout ce qui était en timeout. Sortie de réseau vers 10h30 ce matin et à 18H aucun n'était parvenu à revenir. Et j'avais entre temps éteint la pizigate pour m'assurer que la puissance du signal (canal 15) ne couvrait pas le réseau de la zigate (canal 11)

As tu déjà rencontré le pb avec tes différentes Zigate, Pizigate, wifigate ? Et si oui, comment m'assurer qu'à la prochaine coupure électrique, la pizigate ne mettra pas le bazar sur le réseau de prod de la zigate ? 

Je vais passer commande de E18 avec ampli pour mon réseau de prod. Je vais me faire des routeur DIY. Ils sont finalement programmables avec le CC DEBUGER et le firmware de ptvo. J'ai eu le temps d'en tester un, hier, les LQI sont très bons. Mais je l'ai détruit par décharge électrostatique au moment de l'éteindre. Je me suis acheté tapis et bracelet antistatique ...

![image](https://user-images.githubusercontent.com/36518012/110215816-1105ce80-7eac-11eb-9c0c-b1add70636fa.png)

**Comment by KiwiHC16** [comment]
Salut,
Oui tu peux déplacer le shunt. La version DIN de la zigate fonctionne comme cela. Mais attention à la problématique d adaptation des antennes etc
As tu déjà entendu parler de link budjet ?
Pour le reste je ne vois pas pourquoi les deux réseaux sur des fréquences différentes aurait des interférences comme tu semble le mentionner. Et même si ils sont sur la même fréquence ils ne doivent pas interagir pour plusieurs raisons.
Par contre que tu sortes la zigate du réseau pour faire tes soudures et autre peut avoir des conséquences car les routeurs ne reçoivent plus de réponse de celle ci et peuvent finir par penser qu ils ont perdu le réseau, faire un leave puis un rejoin alors que la zigate est out et ne pouvoir revenir sur le réseau et la ils sont perdus dans la nature. Il faudrait sniffer pendant que tu soudes pour voir ce qu il se passe.

**Comment by mickadam29** [comment]
> Salut,
> Oui tu peux déplacer le shunt. La version DIN de la zigate fonctionne comme cela. Mais attention à la problématique d adaptation des antennes etc
> As tu déjà entendu parler de link budjet ?
> Pour le reste je ne vois pas pourquoi les deux réseaux sur des fréquences différentes aurait des interférences comme tu semble le mentionner. Et même si ils sont sur la même fréquence ils ne doivent pas interagir pour plusieurs raisons.
> Par contre que tu sortes la zigate du réseau pour faire tes soudures et autre peut avoir des conséquences car les routeurs ne reçoivent plus de réponse de celle ci et peuvent finir par penser qu ils ont perdu le réseau, faire un leave puis un rejoin alors que la zigate est out et ne pouvoir revenir sur le réseau et la ils sont perdus dans la nature. Il faudrait sniffer pendant que tu soudes pour voir ce qu il se passe.

Sauf que les équipements dont je parle sont ceux qui sont connectés à la zigate USB, qui n'a pas été touchée. Ceux qui sont rattachés à la pizigate n'ont pas bronché. Ils ont patienté tranquillement et tout est rentré dans l'ordre pour eux lorsque la pizigate a été de nouveau sous tension. Pour faire court, la pizigate (avec nlle antenne) a mis la grouille dans le réseau de la zigate USB, qui ne demandait rien, et encore moins mes équipements de prod. Pour le shunt de l'antenne, j'ai placé une résistance 0hm (court-circuit). Ta piste des routeurs qui pensent qu'ils ont perdu le réseau est possible, si le signal a "effacé" celui de l'autre zigate, plus éloignée. C'est pour ça que je vais devoir améliorer mon réseau de prod en ajoutant des routeurs plus puissants. Maintenant peut-être que c'est pas la pizigate qui a mis la grouille. C'est peut-être une coïncidence. Mais les 2 évènements ont eu lieu ce matin. 
Je verrai si ca se reproduit. 2H pour tout remettre en ordre, mai rien de perdu. Les équipements réinclus sont mis à jour avec une nlle adresse.
 
Merci à toi

**Comment by KiwiHC16** [comment]
C est une coïncidence. 

Si t’es deux systèmes sont distincts il n y a pas de raison d’avoir ce comportement à ma connaissance.

**Comment by mickadam29** [comment]
Ils sont totalement différents. 1 Pc avec zigate USB canal 11 et un raspberry avec pizigate canal 15
La prod en version Master et la dev en version beta. Je remettrai la prod sur une version stable.
