### ISSUE TITLE
si slider set ref to variable

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#186]
Exemple Ampoule Ikea, setLevel as curser attached to Level to move the slider as per the value.

**Comment by KiwiHC16** [comment]
Le champ "value" de la cmd contient l'Id de la commande de ref. Ca veut dire qu'a la creation il faut recuperer l'id de l'autre cmd... Soit faire un search sur les commandes, ou voir si je fais la creation dans l'ordre et que je fait cureent id-1....

**Comment by KiwiHC16** [comment]
Dans la commande slider, la valeur de reference est l'Id de la commande Info et est dans la variable "value".

**Comment by KiwiHC16** [comment]
Done. Tested on 2 Ikea bulbs.

**Comment by mickadam29** [comment]
Nickel. Reste à faire la même chose avec la température ? Tu as prévu ?

**Comment by KiwiHC16** [comment]
Je vais faire une issue pour la temperature. Ne devrait pas être trop de boulot.
