### ISSUE TITLE
Ajout Inter Legrand à un groupe - non visible dans le tableau

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#1874]
Bonjour

je suis sur la dernière version stable d’Abeille (firmware 3.1d) et la dernière version stable de Jeedom.

Je souhaite faire un groupe d’interrupteur (interrupteur Legrand). Quand je fais la commande getGroup sur mes équipements sélectionnés, il y a qu’un seul interrupteur sur les 3 qui remontent. Tous ont une valeur dans IEEE. Ils fonctionnent très bien par ailleurs. Par contre si je les ajoute à un groupe cela à l'air de fonctionner car une télécommande virtuelle j'arrive à les allumer/éteindre. J'ai remarqué pour les équipements qui n'étaient pas visible quand j'utilise la commande Group de l'équipement cela ne me ramène rien

**Comment by KiwiHC16** [comment]
Peux tu mettre le plugin en mode debug, faire les tests suivants et partager le log Abeille et AbeilleCmd.

- Fais un getGroup sur l inter qui fonctionne
- Fais un getGroup sur l inter qui ne fonctionne pas
-

**Comment by sebfar9172** [comment]
Voici 
celui qui fonctionne Abeille1/BF36 et celui qui ne fonctionne pas Abeille1/5048

[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6108848/AbeilleCmd.log)

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6108853/Abeille.log)

**Comment by KiwiHC16** [comment]
Envoi:

```
Message from queueKeyFormToCmd: CmdAbeille1/Ruche/getGroupMembership -> address=BF36&DestinationEndPoint=01
Message from queueKeyFormToCmd: CmdAbeille1/Ruche/getGroupMembership -> address=5048&DestinationEndPoint=01
```
Idem

```
sendCmdToZigate(Dest=Abeille1, cmd=0062, len=0006, datas=02BF36010100)
sendCmdToZigate(Dest=Abeille1, cmd=0062, len=0006, datas=025048010100)
```
Idem

Reception:
```
[2021-03-09 14:41:04][DEBUG] : message(topic='Abeille1/BF36/Group-Membership', payload='-0002')
pas de reponse pour le second.
```
Le premier a le groupe 0002 est en ligne avec ta comprehension ?

Peux tu refaire exactement la meme manip mais avec la commande setGroup et parage le log AbeilleParser en plus du log Abeille et du log AbeilleCmd.

**Comment by sebfar9172** [comment]
Salut, c'est bien un groupe 0002

Il faut faire set group Remote ou set groupe remote legrand ?

**Comment by KiwiHC16** [comment]
Je retrouve dans mes notes:
Commission group for Legrand Telecommande On/Off still interrupteur Issue #1290

**Comment by sebfar9172** [comment]
Voici
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6115110/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6115111/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6115112/Abeille.log)

**Comment by sebfar9172** [comment]
Sinon je remarque que les groupes fonctionnent même si il y a les soucis décrits plus haut par contre si avec une télécommande virtuelle je met mes interrupteurs à Off, cela fonctionne mais l'état des équipements concernés restent à On (1)

**Comment by tcharp38** [comment]
Salut @sebfar9172 
Tu utilises toujours Abeille ?

**Comment by sebfar9172** [comment]
Hello non je suis passé sur home assistant

**Comment by tcharp38** [comment]
Ok. Je vais fermer ce sujet du coup.
Ca te semble mieux que Jeedom donc ? En quoi ? Tu saurais me donner qq exemples ?

**Comment by sebfar9172** [comment]
J’utilise ZHA le zigbee intégré à home assistant. C’est beaucoup plus stable. Je n’ai rarement des pertes de connexion contrairement à jeedom. Je ne regrette pas d’avoir changé.

**Comment by tcharp38** [comment]
Mais le bridge Zigbee est fait par quelle clef ? Je pense que le maillon essentiel est cette partie.

**Comment by sebfar9172** [comment]
Toujours la même la pop justement j’ai gardé la clef pour comparer

**Comment by tcharp38** [comment]
Ha intéressant. Donc jeedom ou le plug-in pour la pop sont moins aboutis

**Comment by sebfar9172** [comment]
Oui et l’équipe jeedom me disait toujours cela vient de ton matériel et pas de jeedom. Bizarre en changeant jeedom par home assistant sans rien toucher au reste tout fonctionne parfaitement

**Comment by tcharp38** [comment]
Il y a trop de couches qui interviennent. Du coup pas toujours facile de faire la part des choses.
Mais tant mieux si tu as une bonne solution stable.. HA + clef POPP
