### ISSUE TITLE
Partage d'information / Image de nos objets

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1876]
@KiwiHC16 

Je tiens à partage ce site qui est vraiment bien.

https://www.remove.bg/fr

Tu importes les png et il te le transforme instantanément en PNG avec fond transparent.
Je vais te faire un PR pour les images dont j'ai besoin.

![image](https://user-images.githubusercontent.com/36518012/110681189-d668a280-81d9-11eb-8d0f-76e5c7bccdf2.png)

**Comment by mickadam29** [comment]
Et il y a surtout la possibilité de convertir le jpg en png avant d'en faire le fond transparent. Donc une copie écran d'un équipement est rapidement transformé. Il faudra s'assurer de la résolution/taille. Je n'ai pas vérifier ce point car les png étaient déjà à la bonne taille. En principe.

**Comment by KiwiHC16** [comment]
PR:

Changement des images pour correspondre au standard fond transparent et ajout modele Sirene Zigbee #1880

**Comment by KiwiHC16** [comment]
In the master. Closure.
