### ISSUE TITLE
Problème de perte des commandes de la zigate aléatoirement.

### ISSUE THREAD

**Issue by SebRider** [KiwiHC16/Abeille#1879]
Bonjour,

J'ai remarqué que je n'arrive plus à avoir le contrôle de mes équipements de manière aléatoire.
Que ce soit mes prise commandées Xiaomi et Ikea, une ampoule ampoule Ikea ou mes capteurs de présence et de fermeture xiaomi.
Bref je n'ai plus de remontés d'information ni de possibilité d'envoi de commande de TOUT mon monde Zigbee.

Chose étrange, j'arrive encore à mettre la clé zigate en mode inclusion, et à inclure de nouveaux équipements (une nouvelle ampoule Lidl achetée récemment par exemple). Mais pareil, une fois incluse, pas moyen de la contrôler.
Le reste de ma domotique continue à fonctionner normalement.

Suite à cela j'ai relancé le daemon qui est en statu "OK", il repasse en "OK" mais rien de plus ne fonctionne.
Je relance donc les dépendances qui ne résout rien de plus.
Je vérifie bien que mon port USB sélectionné de la Zigate USB soit le bon.
Ultime recours, redémarrer Jeedom au complet et la cela refonctionne pour un temps indéterminé.

Cela fait maintenant deux versions principale d'abeille que j'ai ce problème.
Je ne peut pas dire si c'était déjà le cas avant avec ma configuration puisque j'ai tout refait à neuf après passage du plugin Zigate à Abeille.

Je suis sur un pi4
Version abeille : 2021-03-09 01:00:14
Zigate USB : FW 031D
Jeedom : 4.1.20

Je ne sais pas dans quels logs chercher l'erreur je les mettrais à disposition selon les besoins ca sera certainement plus simple que de tout balancer tel quel.
J'ai passé les logs abeille en mode débug.

**Comment by mickadam29** [comment]
Salut

Je t'invite à lire le #1857  et suivre cet issue
Tu n'es pas seul.

**Comment by SebRider** [comment]
@mickadam29 

Merci j'avais vu l'issue, lors de mon précédent coup d'œil.
J'avais pu lire que ce n'était que certains équipements sur "secteur" qui étaient impactés, moi je suspectais plus la clé ou le pluggin à première vue dans mon cas.

En tout cas je vais suivre cela merci.

**Comment by mickadam29** [comment]
> @mickadam29
> 
> Merci j'avais vu l'issue, lors de mon précédent coup d'œil.
> J'avais pu lire que ce n'était que certains équipements sur "secteur" qui étaient impactés, moi je suspectais plus la clé ou le pluggin à première vue dans mon cas.
> 
> En tout cas je vais suivre cela merci.

Le souci apparaît en effet sur les routeurs. Donc équipements sur secteur. MAIS, comme tes équipements sur pile peuvent transiter par ces routeurs, et ne pas avoir une route directe vers la zigate cela veut dire : Plus de routeur, plus d'équipement. Sauf si cet équipement parvient à trouver un autre routeur ou à joindre en direct la zigate.

**Comment by SebRider** [comment]
OK merci pour les explications ! Je veillerai à regarder si les équipements sur pile très proche de la zigate sont toujours actifs là prochaine fois, il est vrais que ceux les plus loin sont les plus fréquemments utilisés

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
#1857 semble different car dans le cas ici un reboot Jeedom resout le soucis. Dans le cas #1857, si mon hypothese est bonne un reboot jeedom ne doit pas resoudre le soucis.

**Comment by KiwiHC16** [comment]
Si ca se reproduit, peut tu envoyer un on a une ampoule et partager le log AbeilleCmd, AbeilleSerial et AbeilleParser au moment ou tu fais l action.

**Comment by SebRider** [comment]
Bonjour,

A cet heure mon réseau viens de se planter complet je redémarre jeedom pour tester mes dires et c'est peut-être des hasards a chaque fois mis la ca remarche.
Sur ce redémarrage par contre cela mettais du temps à remonter.
Du coup je suis allé vérifier dans la page du plugin abeille si le demon était bien relancé et j'ai remarqué que le port série était positionné sur mon port USB de mon modem de télérelève edf et non plus sur le port USB de la ziagate.
Je l'ai remis manuellement et tout était UP à nouveau.

Voici les fichiers de log :
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6160033/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6160034/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6160035/AbeilleCmd.log)

**Comment by SebRider** [comment]
Cela faisait longtemps mais ce soir tout est dans le Black out sauf les capteurs de mouvements xiaomi à pile. Tout le reste est KO, que ce soit ampoule ikea, lidl, prises connectés ikea et xiaomi, détecteurs de portes...

**Comment by tcharp38** [comment]
Salut
Désole de ne pas avoir réagi avant.
Ou en es tu ?
