### ISSUE TITLE
HEIMAN Smart Siren HS2WD-E 

### ISSUE THREAD

**Issue by Jackbets** [KiwiHC16/Abeille#1882]
Bonjour à tous, 

J'ai intégré la sirène HEIMAN Smart Siren HS2WD-E sans problème dans le plugin abeille.  Les commandes ont bien été crées. 
Cependant, je n'arrive pas à faire "que" flasher la sirène ? 

Je déplacer mon curseur "flash" sur mon dashboard, mais cela fait rien.  Est-ce qu'il y a autre chose à faire ? 

Résultat de la commande nom : WarningDevice-EF-3.0
Résultat de la commande IEEE : addr : 5C0272FFFE92A69C

<img width="278" alt="Capture d’écran 2021-03-14 à 10 21 31" src="https://user-images.githubusercontent.com/79042137/111063498-2469f880-84af-11eb-9b5a-18fb67b43a8c.png">

<img width="1317" alt="Capture d’écran 2021-03-14 à 10 25 12" src="https://user-images.githubusercontent.com/79042137/111063553-96dad880-84af-11eb-8e71-02153b518541.png">

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Peux tu partager le log AbeilleCmd quand tu deplace le curseur Flash ?

**Comment by KorionL** [comment]
Bonjour,

J'ai exactement le même problème. voilà ce que j'ai dans mon log AbeilleCmd:
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8401012/AbeilleCmd.log)
Etant vraiment débutant je ne sais pas trop quoi en tirer...

Merci!

**Comment by tcharp38** [comment]
Salut @KorionL 
Ce sujet est ultra vieux. Je vois qu'il avait été fermé donc il etait supposé resolu mais ca ne semble pas le cas.

Si tu es pret a basculer sur la beta et faire des essais, on peut bosser ensemble sur le sujet.

**Comment by KorionL** [comment]
Bonjour @tcharp38,

Oui effectivement c'est très vieux! Je viens de passer sur la beta. Je te laisse me dire ce qu'il y a à faire à partir de là.

Merci!

**Comment by tcharp38** [comment]
Si je comprends bien les 3 boutons du dashboard l'idée est de pouvoir
- declencher le flash seul
- l'alarme seule
- ou les 2
C'est bien ca ?
Et le souci est que seul le flash fonctionne mais pas l'alarme. Correct ?

D'autre part cet equipement semble etre sur batterie n'est ce pas ? Auquel cas je crois qu'il n'y a pas de reporting de niveau de batterie. Tu confirmes ?

**Comment by KorionL** [comment]
Hello!

Alors il y a bien les 3 options que tu indiques: à chaque fois il y a une tempo qu'on peut mettre et en mettant 0 pour moi ça le fait en continue jusqu'à désactivation. L'équipement est branché sur une prise secteur (donc pas de reporting de batteries). Par contre j'ai le son qui fonctionne bien mais pas le flash (que je le lance en individuel ou avec le son). J'aimerais pouvoir faire fonctionner le flash seul afin d'indiquer à la personne qui rentre dans la pièce et et qui désactive l'alarme que la désactivation a bien été prise en compte.

Merci!

**Comment by tcharp38** [comment]
Donc par ex, l appui sur "Flash" ne fait rien du tout ?

Tu me montres un snapshot de cet equipement sur le dashboard ?

**Comment by KorionL** [comment]
Oui bien sûr ça ressemble à ça:

![temp](https://user-images.githubusercontent.com/81571455/161449214-49dd5b0e-85b7-4456-823b-0b38b5a11168.png)

Ce n'est pas des boutons mais des barres de contrôles: lorsque tu déplaces la barre tu mets en route l'alarme pour une durée réglée par la barre en question (0 étant infini). Quand je déplace les barres Sound ou FlashSound j'ai bien le son mais je n'ai donc jamais le flash (pas de falsh nom plus avec la commande Flash)

Voilà j'espère que c'est clair!

**Comment by tcharp38** [comment]
En supposant que tu es à jour de la derniere beta (qui date d'hier)

Peux tu ecraser ton modele avec celui ci (core/config/devices/WarningDevice-EF-3.0/)
[WarningDevice-EF-3.0.json.zip](https://github.com/KiwiHC16/Abeille/files/8411560/WarningDevice-EF-3.0.json.zip)

puis ecraser (core/class)
[AbeilleCmdProcess.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8411585/AbeilleCmdProcess.class.php.zip)

redemarrer le démon Abeille

cliquer sur ton equipement page avancé et configuration > "RECHARGER"

A partir de la sur le dashboard tu devrais avoir 3 nouvelles commandes "TEST".
Si tu peux les tester les unes apres les autres, noter l'effet, et me filer le package de logs (page support > telecharger tout).

Merci

**Comment by KorionL** [comment]
Hello,

J'ai suivi ce que tu m'avais indiqué. J'ai bien copier les deux fichiers comme tu me l'as indiqué mais:
- Quand je fais recharger il m'indique que le "WarningDevice-EF-3.0" n'est pas un équipement connu que qu'il va utiliser le modèle par défaut (après avoir essayé de charger les commandes à partir du fichier Json
- Je n'ai plus que les commandes par défaut de mon équipement...
Tu sais ce qui se passer?

Merci!

**Comment by tcharp38** [comment]
Salut. A part un bug je ne comprends pas pourquoi il ne reconnaîtrait plus le modèle. C'est ce qui s'est passé et du coup par défaut c'est un modèle simplifié qui est utilisé.
Si tu refais une inclusion c'est toujours un modèle non reconnu ?

**Comment by KorionL** [comment]
Hello,

Bon je m'étais un peu emmêlé les pinceaux: c'est bon j'ai les commandes dont tu parles. Pas possible de tester ce soir sinon je risque de faire trop de bruit :s... Dès que j'ai un moment je fais les tests que tu m'a demandé!

**Comment by tcharp38** [comment]
Salut @KorionL 
Toujours interessé par cet antique sujet ?

**Comment by tcharp38** [comment]
Pas de réponses.
Je clos.
A reouvrir si qqn veut bosser dessus

**Comment by brugur** [comment]
Bonjour @KiwiHC16 ou @tcharp38 
je réouvre ce post car je viens d'acquérir une sirène de ce type et je rencontre quelques problèmes à l'utilisation, similaires à ceux d'autres possesseurs.
La référence de ma sirène est MOLO-HS2WD-TY, je joins une photo ainsi que les logs de l'inclusion et de l'utilisation et le dashboard.

17h30 inclusion de la sirène avec création des commandes
17h33 exécution de la commande 'Test flash' , mais imposssible de l'arrêter (durée 1mn)
17h35 exécution de la commande 'Test sound' , mais imposssible de l'arrêter (durée 1mn)
17h37 exécution de la commande 'Flash' , avec curseur mais imposssible de l'arrêter (durée 1mn) le curseur semble inactif
idem pour 'Sound' avec curseur mais imposssible de l'arrêter (durée 1mn) le curseur semble inactif

Si vous pouvez m'aider à faire en sorte que l'on puisse arrêter la sirène ou le flash et pouvoir régler la puissance, la durée de la sirène et la cadence de clignotement et la puissance du flash, ce serait parfait.

A disposition si besoin d'infos supplémentaires.

Merci.
[AbeilleLogs-230225.tar.gz](https://github.com/KiwiHC16/Abeille/files/10831791/AbeilleLogs-230225.tar.gz)
![node_HS2WD](https://user-images.githubusercontent.com/82367786/221369918-e85d0de0-9eb9-46b8-88c2-61bf34a4d730.png)
![image](https://user-images.githubusercontent.com/82367786/221369667-9c4cfda0-edcd-42ca-8018-9148dd51720c.png)
