### ISSUE TITLE
HEIMAN Smart Siren HS2WD-E  commande flash 

### ISSUE THREAD

**Issue by Jackbets** [KiwiHC16/Abeille#1883]
Bonjour à tous, 

J'ai intégré la sirène HEIMAN Smart Siren HS2WD-E sans problème dans le plugin abeille.  Les commandes ont bien été crées. 
Cependant, je n'arrive pas à faire "que" flasher la sirène ? 

Je déplacer mon curseur "flash" sur mon dashboard, mais cela fait rien.  Est-ce qu'il y a autre chose à faire ? 

Résultat de la commande nom : WarningDevice-EF-3.0
Résultat de la commande IEEE : addr : 5C0272FFFE92A69C

<img width="278" alt="Capture d’écran 2021-03-14 à 10 21 31" src="https://user-images.githubusercontent.com/79042137/111063498-2469f880-84af-11eb-9b5a-18fb67b43a8c.png">

<img width="1317" alt="Capture d’écran 2021-03-14 à 10 25 12" src="https://user-images.githubusercontent.com/79042137/111063553-96dad880-84af-11eb-8e71-02153b518541.png">

**Comment by mickadam29** [comment]
A ma connaissance, ce n'est pas implémenté. Il me semble que quelque soit le code envoyé, il n'y a que la sirène qui fonctionne. A confirmer

**Comment by KiwiHC16** [comment]
Redondant avec #1882.

Si si c est implémenterais, je me souviens avoir fait clignoter la mienne pour ne pas utiliser la sirene la nuit quand je faisais mes tests pour ne pas reveiller tout le monde ...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Je clos et continu dans l autre issue.
