### ISSUE TITLE
See if we can do a bit more with IAS

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1885]
Actuellement dans Abeille on ne fait que recuperer les messages venant des equipement et on met à jour Abeille. Quid de configurer les equipements pour qu'ils fonctionnent sans Abeille.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by sbx59** [comment]
Salut,
Comment voudrais tu les faire fonctionné ?

**Comment by mickadam29** [comment]
Je crois qu'il y a une notion de zone. Donc des équipements seraient en mesure de lui envoyer l'info. J'imagine, qu'un capteur d'ouverture de porte/fenêtre envoie l'info de l'ouverture après que la sirène ait été "Armed"

**Comment by tcharp38** [comment]
Je clos le sujet. Trop "generique" et sans cible précise
Je m'attends à une requete inverse basée d'un manque sur un des équipements.
