### ISSUE TITLE
Page santé: cacher/virer colonne "Repond"

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1888]
![image](https://user-images.githubusercontent.com/35221038/111624823-7632bb80-87ec-11eb-8e84-c53f324c14e2.png)

A cacher aux utilisateurs => mode dev.

D'autre part si cette colonne a vraiment un interet elle doit etre mergé avec "Status" sinon c'est incomprehensible.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Ok pour la cacher tant que pas finie.

Pour l affichage je suis preneur d'idée mais les deux infos sont differentes donc c est bien d avoir les deux accessibles.

**Comment by tcharp38** [comment]
Comment explique tu cette colonne au end user ?
Moi j'ai toujours pas compris mais il faut vraiment que ca soit simple à la fin: status OK ou pas OK. Sinon c est vraiment compliqué.

**Comment by KiwiHC16** [comment]
Ok / Pas Ok : oui mais si as Ok il faut donner des billes pour savoir pourquoi pas Ok.

Time-Out: pas de messages de l equipement recu depuis x minutes.
Repond: Quand j'envoie une commande à l'equipement, je ne recois pas la confirmation de la part de l equipement de la reception. C est un accusé de reception pas reçus.

**Comment by tcharp38** [comment]
Comment est ce possible d'avoir l'info dans un sens et pas dans l'autre ?
Actuellement si status ok donc on a recu qqch de l'equipement.
Donc si repond pas ok, c 'est l'autre sens. Mais ca ca ne peut s'appliquer qu'a un eq sur secteur. Un truc sur batterie ne va pas forcement repondre.

Je me gourre ou ?

**Comment by KiwiHC16** [comment]
Equipement -> Abeille: niveau application -> TimeOut. 
Un equipement envoie par exemple toutes les heures une information. Cela indique que dans la denirere heure Abeille a recu un message de l equipement. Donc on peut supposer que le lien Device->Abeille fonctionne.

Abeille -> Equipement -> Abeille au niveau reseau (routage). Si pas de timeout alors il est fort probable que la parti equipement -> Abeille fonctionne. Mais si Repond en erreur ca veut dire que dans la chaine quelque chose n a pas fonctionné, probablement Abeille -> Equipement.

- TimeOut donne un indication sur Uplink
- Repond si timeout ok, donne une indication sur Downlink

**Comment by tcharp38** [comment]
Ca se tient.
Sauf que comment tu gere le retour Abeille vers EQ pour la plupart des equipements sur batterie donc qui dorment ?

Autre question: si tu ajoutes ca c 'est que tu es tombé sur ce genre de soucis. Tu peux donner ton cas d'exemple qui a merdé (comm unidirectionnelle) pour instruction ?

**Comment by KiwiHC16** [comment]
Pour les equipements sur piles il faut que je regarde plus les details car je ne suis pas sure à 100% du fonctionnement de la stack zigbee.

Je n ai pas d exemple specifique en tête au moment ou j écris...

**Comment by tcharp38** [comment]
En dehors de ce que supporte la stack y a t'il dans la spec zigbee qqch un chapitre qui indique
- si un eq sur batterie doit rester un peu en ecoute qq temps apres l'envoi de son info
- et combien de temps

Si ce comportement n'est pas standard alors je ne vois aucune chance fiable d'avoir un lien descendant vers un EQ sur pile.
D'accord avec ca ?

**Comment by tcharp38** [comment]
@KiwiHC16 
Je considère que si on a un uplink la connexion est faite. Je ne vois pas comment on pourrait avoir l'un et pas l'autre.
Quoi qu'il en soit tester ce chemin de retour apparait comme tres compliqué et ca surcharge le reseau (et Abeille) d'un message supplémentaire chaque fois si je comprends bien.

Bref, je clos ce point pour l'instant histoire d'essayer de réduire la liste mais à réouvrir si vraiment tu considères que ca a un interet.
