### ISSUE TITLE
Ajout ampoule Osram Lightify

### ISSUE THREAD

**Issue by malabke** [KiwiHC16/Abeille#189]
Bonjour,

J'ai tenté l'ajout d'une ampoule Osram lightify, l'objet abeille est bien créé mais en "Abeille-b822", avec toutes les commandes "inconnues".
Aucune commande ne semble fonctionner...

Jeedom 3.1.7, Abeille installée depuis github (via le centre de plugin, pas en ligne de commande).
Zigate firmware en version 3d.

Est-il possible de faire quelque chose ?
Merci

**Comment by KiwiHC16** [comment]
Tu es le premier a proposer ces ampoules donc je n'ai aucune info à leur sujet. Peux tu partager une capture d'écran de l'objet sur le dashboard et une capture d'ecran des commandes de l objet ?

**Comment by malabke** [comment]
Avec plaisir ! Si je peux aider à ajouter un objet d'une quelconque façon (j'ai aussi 2 prises Osram, j'ai vu qu'elles étaient supportées mais je ne les ai pas encore ajoutées, si ça peut aider...)
J'ai juste supprimé dans le nom de chaque commande "Commande non reconnue" (un truc comme ça) car la case étant petite ce n'était pas lisible. Je n'ai pas touché au reste.
![dashboard](https://user-images.githubusercontent.com/37160945/37143375-42c0edf6-22bb-11e8-8c0f-258ad58972ee.png)
![commandes](https://user-images.githubusercontent.com/37160945/37143376-42da28fc-22bb-11e8-8bd7-459946f2e9eb.png)

**Comment by KiwiHC16** [comment]
Je ne possede pas ces equipements alors le temps que je passe dessus n'est pas pour moi. Alors toute aide est la bienvenue. Dans un premier temps je veux bien que tu essayes d'integrer les prises avec la doc: https://github.com/KiwiHC16/Abeille/blob/4f56296fececc8c3cc5e772ee7f7beac2e1c2745/Documentation/050_IntegrationEquipement.asciidoc#osram-prise-smart

Et que tu tires de ton experience une doc (le format que tu veux, on la  mettra en asciidoc pour la publier). L'idée serait d'avoir un fichier 600_Osram.asciidoc dans la page 

https://github.com/KiwiHC16/Abeille/tree/4f56296fececc8c3cc5e772ee7f7beac2e1c2745/Documentation.

**Comment by KiwiHC16** [comment]
Pour les ampoules ce qui est tres bien c'est qu on a un nom qui remonte "Classic A60....".
Peux tu aller dans la commande 0000-0005 et faire tester, pour avoir le nom exact et faire un copy/paste ici pour que je fasse un premier fichier JSON pour cette ampoule ?

**Comment by malabke** [comment]
Ça marche, j'essaye d'intégrer les prises ce soir quand je rentre.
Mais je peux déjà tester la commande à distance, ça donne :
Résultat de la commande : Classic A60 W clear - LIGHTIFY

**Comment by KiwiHC16** [comment]
J ai ajouté un JSON pour cette ampoule dans master. Mets a jour master pour voir ce que cela donne.

**Comment by malabke** [comment]
J'ai mis à jour le plugin, il faut que je fasse quelque chose (genre supprimer l'objet) ?
Si non, je teste d'ici 2h en rentrant si ça marche.

**Comment by KiwiHC16** [comment]
Oui il faut supprimer l objet, se mettre en mode automatique.
Garde dans un coup l’adresse de l ampoule (4 digits)

**Comment by malabke** [comment]
Ça marche juste NICKEL ! :)
J'essaye d'intégrer les prises dans la soirée, mais là c'est tip top pour l'ampoule, bravo !

**Comment by malabke** [comment]
Concernant la prise, elle est bien détectée & ajoutée, mais les commandes ne fonctionnement pas.
Ci dessous les screens, si je peux faire quelque chose n'hésites pas.
![image](https://user-images.githubusercontent.com/37160945/37174767-d6a415dc-2317-11e8-808d-fbb1f9bad6ed.png)
![image](https://user-images.githubusercontent.com/37160945/37174790-e4587d94-2317-11e8-992a-b6a0311967b2.png)
![image](https://user-images.githubusercontent.com/37160945/37174899-2d0e9eba-2318-11e8-8d7e-5d766b4a4390.png)
![image](https://user-images.githubusercontent.com/37160945/37174918-373bbd32-2318-11e8-96ea-586b3ec2da03.png)
![image](https://user-images.githubusercontent.com/37160945/37174930-3ea9cea6-2318-11e8-9df5-8c9514991376.png)

**Comment by malabke** [comment]
Ah correction, le "on" fonctionne, et le "getEtat" aussi.
Du coup le toggle fonctionne quand elle est off (pour la mettre on) mais pas l'inverse (logique puisque le off ne marche pas).

**Comment by KiwiHC16** [comment]
Surprenant car la seule difference normalement est qu'on envoie 0 pour Off, 1 pour On et 2 pour Toggle.
Procédons par étape, ampoule en premier. Est ce que les trois commandes On, Off et Toggle fonctionnent (Est ce que l ampoule fait ce qu'on lui demande ?). 
Attention il n'y a pas de retour d'état verss Jeedom à cette étape. Bien regarder l'ampoule physique.

**Comment by malabke** [comment]
Oui oui, comme confirmé hier (le message a été noyé dans la masse, il est juste avant les screens) pour l'ampoule ça fonctionne au top depuis la mise à jour.
Où est-ce que ce paramètre (0/1) est setté ? je ne le vois pas dans les commandes.

**Comment by KiwiHC16** [comment]
Le code converti "On" que tu vois dans la commande par 01, Off par 00 etc. C'est le meme code pour l ampoule et la prise. C'est pour cela que je suis surpris que l ampoule fonctionne et pas la prise. Surtout que le code a ete fait au depart pour la prise.

**Comment by malabke** [comment]
En effet, c'est bizarre.
Je re teste tout ça ce soir, en repartant de 0 : 
- je supprime prise & ampoule
- j'ajoute la prise, je teste
- j'ajoute l'ampoule, je teste

Ca sera l'inverse de ce que j'ai fais (ajouter l'ampoule PUIS la prise), on verra déjà si ça donne le même résultat ^^
Autre petite demande (oui, détail vraiment !) comment je peux changer l'image qui représente l'objet ? Là c'est la photo de la prise, je mettrai bien la photo de l'ampoule ^^
Merci

**Comment by KiwiHC16** [comment]
Envoie une image et je vais la mettre a jour.

**Comment by malabke** [comment]
C'est ce modèle :
![image](https://user-images.githubusercontent.com/37160945/37201172-35abb57a-2387-11e8-8ca3-1802e88822cf.png)

Merci :)

**Comment by KiwiHC16** [comment]
Je viens d ajouter l icone dans le master (je ne peux pas tester)

**Comment by malabke** [comment]
Nop, malgré la mise à jour :
/plugins/Abeille/docs/images/node_OSRAMClassicA60Wclear-LIGHTIFY.png 404 (Not Found)

**Comment by KiwiHC16** [comment]
Et maintenant ?

**Comment by malabke** [comment]
Oaip, là ça fonctionne ! Merci :)

**Comment by KiwiHC16** [comment]
Et les On / Off ?

**Comment by malabke** [comment]
Je suis encore au bureau, du coup je n'ai que l'accès à distance mais je ne peux pas constater physiquement.
Je regarde dès ce soir !

**Comment by malabke** [comment]
Je confirme, pour l'ampoule tout est nickel.
Par contre la prise toujours que le "On" qui fonctionne.
Je n'ai pas eu le temps de faire les manip pour virer l'ampoule et inclure d'abord la prise, j'essaye durant le weekend mais c'est chargé...

**Comment by malabke** [comment]
Désolé, il m'a fallut un peu de temps le weekend/lundi ont été chargés :)
J'ai donc :
- effectué une mise à jour de Abeille ce matin => toujours le problème
- supprimé la prise & l'ampoule
- ajouté la prise => tout marche
- ajouté l'ampoule => tout marche
- ajouté la 2eme prise => tout marche

Je ne sais pas pourquoi ça ne marchait pas la première fois après avoir ajouté l'ampoule en premier, mais là tout est OK ! :)
Merci beaucoup, et si besoin d'infos / tests n'hésites pas à demander !

Je m'occupe au plus vite du doc de retour d'expérience.

**Comment by KiwiHC16** [comment]
@malabke du nouveau pour la doc ?

**Comment by malabke** [comment]
J'ai essayé de faire sur le modèle déjà présent dans la doc, mais je trouve ça léger car tout est automatique depuis tes modifs.
Ci-joint ce que j'ai fait
[Osram.zip](https://github.com/KiwiHC16/Abeille/files/1833818/Osram.zip)

C'est ma première fois pour ce genre de choses, n'hésites pas si je me suis complètement planté, si je peux ajouter des choses (captures, commandes, etc) ou autre !

**Comment by KiwiHC16** [comment]
Ok pas de soucis, un peu de léger plus un peu de léger… ca fini par faire un truc….
Je vais le mettre dans la doc.

**Comment by NagNag73** [comment]
Bonjour

Est ce qu'il y a une méthode à suivre documentée pour pouvoir ajouter un périphérique inconnu tel que mon osram color sans te demander de le faire à chaque périphérique que tu ne possèdes pas ? (En gros faire du participatif à ABEILLE et non juste "profiteur").
En plus de l'ampoule couleur je dispose des plafonniers  osram (2 sortes).

**Comment by KiwiHC16** [comment]
Biensur, c'est pour cela que tout est en open source et dispo à tous.
Il n'y a pas de formule magique mais regardes dans un premier temps la doc https://github.com/KiwiHC16/Abeille/blob/master/Documentation/060_ConfigurationAvancee.asciidoc au chapitre JSON.

**Comment by KiwiHC16** [comment]
Si tu as un equipement specifique, ouvres une issue dédiée. Partages tu infos, questions,... puis quand tu as qq chose qui fonctionne fait un pull request dans github et je l'inclurai pour tout le monde.

**Comment by malabke** [comment]
Depuis les dernières mises à jour, plus rien ne fonctionne.
Ni les prises, ni la lampe.
J'ai vu un autre topic de ta part sur les commandes on/off/toggle et la zigate, c'est lié ?
Je peux faire quelque chose ?

**Comment by KiwiHC16** [comment]
Bizarre, bizarre. C'est quoi la derniere mise a jour ? le master ou la version sur l market ?
Je n'ai pas en tête de modification sur cette partie !

**Comment by malabke** [comment]
C'est la master Github.
Je tenterai de tout désinstaller et tout reprendre à 0, voire si ça change quelque chose...

**Comment by malabke** [comment]
Je confirme, j'ai tout dégagé (supprimé les abeilles, la ruche, désinstallé le plugin).
J'ai tout réinstallé, les abeilles sont bien créées mais rien ne fonctionne, ni ampoule ni prise.
Je vois d'autres topics sur Osram dans les issues, est-ce que ça hasard tout ne pourrait pas être lié à une action de leur part (j'y connais pas grand chose) du genre mise à jour de firmware automatiquement via le wifi ? (oui oui je dis peut être une énormité, je sais ^^)

**Comment by malabke** [comment]
J'ai aussi tenté via le module du market au lieu de Github.
Ça ne marche pas non plus, mais les abeilles ont une "tête" différente, il y a juste : short adresse, état, on, off, toggle sur le dashboard (mais c'est peut être lié à la version du module ?)

**Comment by NagNag73** [comment]
L api osram a évolué et l'ancienne version a tiré sa révérence au 31 mars.
Peut être que même si ABEILLE et ZIGATE n'utilise pas cette API  les
fonctions des devices ont changé le 1er avril ... ? (Pas un poisson)

**Comment by malabke** [comment]
Ah oui, ça pourrait expliquer bien des choses !
Il y a eu de l'info communiquée là dessus ? Comment l'as-tu su ?

Merci !

**Comment by KiwiHC16** [comment]
Avec la ZiGate et Abeille, les equipements OSRAM ne peuvent pas avoir changé de soft donc d'API. As tu associé les équipements OSRAM à la GW OSRAM ? Sont ils restés toujours avec ZIGate / Abeille ?
Je vais vois si les commandes envoyées à la ZiGate sont toujours correctes et que je n'ai fait une modif qui a tout cassé dans le code...

**Comment by KiwiHC16** [comment]
Je viens de faire un push d'une correction. Peux tu tester ?
(Une erreur de copy/paste dans le code mi mars...)

**Comment by NagNag73** [comment]
En faisant une recherche sur leur documentation API REST mais ce n'est
donné que sur un de leur site ...

Ex: https://groups.google.com/forum/m/#!topic/thehomeremote/eFzBfnsHMBQ

**Comment by KiwiHC16** [comment]
Ok,
pour le setReport, il doit y avoir un probleme plus generique que OSRAM car j ai voulu setReport des ampoules Ikea hier et cela ne fonctionnait pas. Je vais regarder ce point.

**Comment by KiwiHC16** [comment]
Un reset de la ZiGate et tout est fonctionnel de nouveau.

**Comment by malabke** [comment]
De mon côté, c'est "bizarre".
J'ai reset l'ampoule.
J'ai tout désinstallé, redémarré le RPI, réinstallé, etc.
L'abeille a bien été recréée, mais toujours en mode "réduit" (uniquement le nom, status, on/off/toggle).
Off a marché, On a marché. Toggle n'a pas marché. Et puis, plus rien ne marche !
Les prises par contre, nickel.
J'ai reset le network (qui était fraichement installé !) et l'ampoule, à l'allumage suivant, a clignoté (signe qu'elle est prête pour inclusion), a été ajoutée (nouvelle shortaddress alors qu'elle n'avait pas changé jusque là), et hop, tout marche !

Donc au final c'est OK côté dév, mais je commence à me demander si mon ampoule n'a pas un problème...

**Comment by KiwiHC16** [comment]
Dans les parametres du demon, tu as "Affichage mode dévelopeur" qui permet lors de la creation d'un objet d'afficher toutes les commandes de l'objet ou uniquement les commandes "utilisateurs".

Dans toutes les étapes que tu décris il manque le "clean" de la ZiGate. La ZiGate contient les informaitons "réseau" des objets comme par exemple les adresses affectées,... Peut être que le problème était la.

Actuellement, lors de creation des setReport cela fonctionne sur toutes mes ampoules sauf sur deux. Une n'a rien de spéciale et une n'est pas en relation direct (Je pense que le probleme vient de la). Par contre pour la premiere, je ne trouve aucune explication, je vais recompiler la ZiGate avec des traces pour voir ce qu'il se passe... La ZiGate ne peut être exempte de bug, peut être tombons nous dedans de temps en temps.

**Comment by malabke** [comment]
Ok, je vois un peu l'idée. Je ne pensais pas que la Zigate stockait des infos, je la voyais juste comme un "relais" à qui on envoit une info, elle la balance en Zigbee et basta.
Merci pour ces explications :)
Et en effet, elle est assez récente pour ne pas être forcément totalement stable, je pense que ça viendra avec le temps (j'espère !).

**Comment by KiwiHC16** [comment]
Je clos cette issue. Si besoin on rouvrira ou on en ouvrira une nouvelle.
