### ISSUE TITLE
Icône retouchée (sans fond blanc)

### ISSUE THREAD

**Issue by Marc--** [KiwiHC16/Abeille#19]
Ce n'est surement pas ta priorité, mais j'avais 2mn à perdre. Voici l'icône ou j'ai retiré le fond blanc. C'est plus propre je trouve.

![abeille_icon](https://user-images.githubusercontent.com/9568739/35268083-7abca4da-0028-11e8-8b98-8f29ba6cb1c9.png)

**Comment by KiwiHC16** [comment]
Super merci.
Je viens de le mettre sur mon système, sera sur GitHub au prochain push.
Ben
