### ISSUE TITLE
Icone disparu de la liste 

### ISSUE THREAD

**Issue by loustic03** [KiwiHC16/Abeille#1905]
Bonjour KiwiHC16 , 
Je viens de remarquer que l'icon du ZigLight a disparue de la liste des équipement , j'ai regarder dans les images du plugin et il n'y a plus rien .
![image](https://user-images.githubusercontent.com/76919490/113331827-b16ed780-9320-11eb-8015-9cedea0664cd.png)
![image](https://user-images.githubusercontent.com/76919490/113331932-d3685a00-9320-11eb-967e-7f9a7666c045.png)

**Comment by tcharp38** [comment]
@mickadam29 Ca te parle ?

**Comment by mickadam29** [comment]
Salut 
En principe, sur les recommandations de @tcharp38 je ne retire rien. Y compris modèles et icônes. Je vérifie sur mon fork.

**Comment by mickadam29** [comment]
salut @loustic03 

Tu aurais le nom du modèle ? Je vais vérifier si j'ai une trace du png dans mes fichiers. Merci à toi. Il y a qqs semaines j'en ai passé qqs dizaines à la moulinette pour les mettre avec fond transparent. J'ai peut-être égaré un fichier.

**Comment by loustic03** [comment]
salut @mickadam29 
Alors le modèle s'appelle ZigLigth et il a été reconnue avec ce non là , j'ai déjà eu des soucis avec cette équipement et KiwiHC16 est intervenu sur mon jeedom car j'avais bien l'image dans le plugin mais il n'était pas dans la liste .
Sinon en dehors du fait que je n'ai plus l'icone ce boitier fonctionne très .

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Je ne le vois pas dans https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices

**Comment by mickadam29** [comment]
Comme le fait penser @KiwiHC16 , ton modèle n'aurait-il pas disparu avec une mise à jour ? Ca ressemble à un modèle perso non intégré dans les releases (master, beta, ....)

**Comment by loustic03** [comment]
ton modèle aurait-il pas disparu avec une mise à jour?
Oui je pense qu'il a disparu sur une mise à jour , j'avait demandé à @KiwiHC16  s'il pouvait l'intégré il y a déjà quelque mois et il me semble qu'il a en sa possession ce modèle.

**Comment by KiwiHC16** [comment]
Je viens de tester sur mon systeme en master et aucun soucis.
C est ici: https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/WS2812_light_controller
Sera dispo dans le prochaines versions. @loustic03: ne fais rien cela mis en place avec une version à venir.

**Comment by loustic03** [comment]
@KiwiHC16 ok ça marche et merci

**Comment by loustic03** [comment]
Merci @KiwiHC16 c'est revenu aprés la mise à jour.
