### ISSUE TITLE
Limite de capacité de la Zigate. Comment aller au delà?

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#1906]
Bonjour,

il semblerait que j'ai atteint la limite de capacité de ma zigate: 55 abeilles.
J'ai inclus 6 commandes legrand volet roulant hier, la 7ème n'a jamais voulu.
Les logs voient bien passer un annonce device 0040, mais rien d'inclus.

Bref, comment faire?
Le mode RAW est-il en cours de développement? (PDM dans abeille et non dans l'eeprom)
Une seconde Zigate resout-elle le problème? Y aura-t-il alors deux réseaux distincts?

Autre soucis "annexe", j'ai tenté d'exclure quelques module pour faire de la place dans le PDM de la zigate -> Erreur, pas d'IEEE parent. Un refresh LQI n'a rien changé.

Merci de votre aide.

Kaléo.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Salut, 
Regardes les capacités annoncées pour les différentes versions de la la zigate, il y a eu des changements au cours du temps. Je ne me souviens plus des valeurs.
Si tu vois les annonces je pense que l equipement est dans le réseau zigbee donc ton soucis ne doit pas la capacité.
Pourrais tu partager un log annonce que tu vois ?
Dans ce message tu dois trouver l adresse courte. Depuis la ruche, faire un getNmae sur cette adresse et cela devrait fonctionner.
Le mode RAW ne sera pas pris en compte par Abeille. Le mode PDM externe que tu as en tête n'est pas encore implémenté dans Abeille, j'ai commencé mais pas encore dispo.
Deux zigates est une solution et Abeille le prend en compte. Oui deux réseaux zigbee dans ce cas.
Sinon je ne comprends pas ton sujet annexe....

**Comment by kaleofr** [comment]
Bonjour, 
a vrai dire, je n'étais pas loin du maxi (40 routers apparement). 
Je me suis résolu à faire une RAZ PDM pour réintégrer tout le monde proprement et mon problème a disparu.

Le problème secondaire était à propos du bouton "exclure" ajouté par tcharp dans le mode developper. Son but doit être d'exclure un device de la zigate si j'ai bien compris mais cela n'avait pas marché pour moi (message: Erreur, pas d'IEEE parent).

Il serait bien de pouvoir gérer proprement les devices de la zigate indépendement de jeedom/abeille. Une vue synthétique, exclure, etc.

En tous cas, désolé pour le dérangement, le problème est résolu... pour le moment.

Kaléo.

**Comment by tcharp38** [comment]
Salut

Concernant la capacité max et comment detecter qu'on est en saturation.. je n'ai toujours pas de reponse de son concepteur.
Donc on ne sait pas detecter que la zigate est saturée ou pas.

Le bouton exclure est toujours en mode dev car pas vérifié et tu confirmes que ca ne fonctionne pas tout le temps.
Je crois qu'il y a une issue sur ce sujet. Je vais la reouvrir.

Qu'entends tu par "pouvoir gerer proprepement les devices" ? Tu as une idée en tete ? Je suis preneur.
Toute idée qu'on puisse mettre en place pour améliorer le cote intuitif ou logique de l'interface.

**Comment by kaleofr** [comment]
Oui, j'imagine bien une page qui interroge la Zigate et dresse la liste des équipements qu'elle connait.
Sur cette page, en face de chaque module, un bouton "Effacer de la Zigate".
On pourrait aussi avoir trois boutons =>  Effacer de la Zigate / Effacer de Jeedom / Effacer partout
Sur cette meme ligne, on pourrait imaginer d'autres actions -> Réinitialiser le Modèle / Choisir un Modèle Personnel / Un Icon Personnalisé / Etc...
On pourrait aussi avoir d'autres infos: IEEE court, nom jeedom (inconnu si... inconnu de abeille), ext.
Bref, moins d'icons et plus de contrôles.
Ca ressemblerai à la page santé mais plus tourné vers la configuration.

Dans ce que je propose ici, il y aurai sur la meme pages les infos issues de la Zigate et celles d'Abeille. A voir comment bien marquer la différence, ou faire deux pages distinctes.

L'avantage du tableau type "Santé", c'est aussi de pouvoir trier les éléments en fonction de l'intitulé de la colonne.

Kaléo.

**Comment by tcharp38** [comment]
Ok merci pour ce retour.

Ca sous entend que tu ne trouves pas la page de gestion actuelle adaptée.
On a déja plein de trucs sur le feu pour stabiliser encore + ce plugin mais si jamais tu as qq mins pour mettre sur un croquis à la main ton idée, ca permet d'eclaircir et de laisser murir.

Pour info tout n'est pas forcement realisable, à cause du FW actuel ou a cause du standard Zigbee simplement.
Par ex virer un eq du reseau ne se fait pas comme ca, surtout pour un eq sur batterie.

Neanmoins on peut toujours faire evoluer les choses.
Reste à definir vers quoi et dans quel ordre mais de maniere generale vers qqch qui apparaisse + intuitif pour tous.

 A murir.
