### ISSUE TITLE
Network Graph: EQ en dehors de la zone visible

### ISSUE THREAD

**Issue by dams74** [KiwiHC16/Abeille#1910]
Bonjour
Je rencontre une petit soucis avec le network graph
J'ai l'impression que j'ai des éléments en dehors de la zone visible
![image](https://user-images.githubusercontent.com/2788955/113811169-01f49380-976c-11eb-87e2-e2ec8c7143d8.png)
Comment faire pour tout remettre dans un endroit visible?
Je vois sur ce graph des éléments noté pas dans jeedom, que sont ces éléments?
Merci de votre aide
Damien

**Comment by tcharp38** [comment]
Salut Damien
Pour les elements "pas dans Jeedom" il s'agit normalement d'equipements toujours connus du réseau zigbee mais pas connus de Jeedom/Abeille.
Quant a ces liens en dehors de la page ca sens le bug mais peut etre que @KiwiHC16 aura une idée pour recentrer le resultat en attendant un correctif.

**Comment by KiwiHC16** [comment]
Oui c est un (vieux) bug. Pas eu le temps de la regarder.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by dams74** [comment]
Merci à tous les deux pour vos réponses
Par contre je viens de mettre à jour ma clé et je viens d'appairer tout mon matériel avec Jeedom. Je ne comprends pas comment il peut y avoir des choses non connu.
Vous pouvez m'expliquer pour ma culture?
Damien

**Comment by tcharp38** [comment]
Salut
Comment as tu mis à jour ta clef ? Tu n'as peut etre pas fait d'erase PDM.
Pour info, mettre le FW à jour ne veut pas dire forcement reset complet de la zigate. Si la PDM n'est pas effacée elle conserve les infos qu'elle avait precedement.

**Comment by dams74** [comment]
Salut
En effet tu as raison je n'ai pas précisé que j'avais fait un erase PDM

**Comment by tcharp38** [comment]
Dans ce cas je ne pige pas pourquoi tu aurais encore des equipements "inconnus". Tu le vois comment ?
D'ailleurs ton graph est propre maintenant ?

**Comment by dams74** [comment]
Le graphe que j'ai mis plus haut a été fait après la mise à jour et le reset

**Comment by tcharp38** [comment]
Ok donc tu as toujours des EQ inconnus et des EQ en dehors du graph.
Si tu veux attacher ton "AbeilleLQI_MapData1.json" je peux essayer de comprendre ce qui se passe pour un des 2 pbs.
Ce fichier est dans /tmp/jeedom/Abeille.
Je pense que tu devra en faire un .zip pour qu'il soit accepté par GitHub.

**Comment by dams74** [comment]
Merci de ton aide
Je ne trouve pas de dossier tmp
![image](https://user-images.githubusercontent.com/2788955/114295556-4783ca00-9aa6-11eb-9775-395f34472872.png)

**Comment by dams74** [comment]
C'est bon j'avais pas vu la fonction placement auto...
![image](https://user-images.githubusercontent.com/2788955/114296366-53be5600-9aab-11eb-887d-235ac4ec58ed.png)

**Comment by dams74** [comment]
j'ai seulement 3 objets noté pas dans jeedom
![image](https://user-images.githubusercontent.com/2788955/114296456-b7e11a00-9aab-11eb-8f97-4c3f66911953.png)

**Comment by tcharp38** [comment]
Le dossier tmp est /tmp donc pas accessible via Jeexplorer.
Il faut que j'ajoute ca à la page support. Entre temps tu peux utiliser SSH, FTP ou tout autre solution que tu connais.

**Comment by tcharp38** [comment]
Le network graph s'appelle maintenant "placement reseau" et est en cours de refonte totale.
Déja dispo dans la beta du moment.
Je clos ce sujet.
