### ISSUE TITLE
version 2021-04-07 01:00:10 plus de remontés

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#1912]
Bonjour, 
je viens d'installer la dernière version (2021-04-07 01:00:10) aujourd'hui sur mon jeedom de test et il semblerait qu'abeille  ne prenne plus aucun évènement du réseau en compte.
J'ai fait un essai avec une ampoule Philips et une ampoule Ikea
Les commandes sont bien transmises à la zigate , les ampoules s’allument mais l'état ne passe pas ON sous jeedom; idem pour le level.
La remontée des ampoules est bien faite par l'ampoule et la zigate car j'ai une zigate wifi utilisé par 2 instances de jeedom. Et sur mon instance de production qui est en version abeille 2021-03-17 01:00:21, l'état et le level changent bien.
De même j'ai des capteurs aquara qui remontent bien dans mon instance de production mais rien sur l'instance de test.

Alors j'ai voulu voir les logs et j'ai activé le debug :
Et chose encore plus bizarre, si je configure les logs en niveau Debug, le fonctionnement redevient normal !
J'ai fait plusieurs tests de redémarrage du démon en mode Debug , Default, Aucun,Warning, Info et Error.
Les retours d'états fonctionnent en mode Debug, Warning,Info et Error  mais pas en Default et Aucun.

Et dans tous les cas de figure , les commandes sont bien transmises aux équipements (ON/OFF, setlevel , settemperaturelight).

Jeedom en 4.1.22
zigate en 031D

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
As tu essayé un redemarrage des daemons du plugin apres l installation de la mise a jour ? As tu toujours le soucis ?

As tu vu des erreurs dans les logs qui pourrait nous guider vers la source du soucis ?
 
@tcharp38 un soucis dans la gestion des logs ? (Pour l instant pas d autre idée, il faut que je teste)

**Comment by Krankhore** [comment]
Oui , j'ai essayé de démarrer le démon une paire de fois.
Je fonctionne en laissant le log sur info.

Et je viens de tester en repassant le mode à default puis à aucun.
Et cela fonctionne aussi, je n'arrive pas à reproduire le problème aujourd'hui.

Pourtant il n'y a pas eu de redémarrage de jeedom ou d'autres mises à jour depuis hier.

C'est super bizarre. Cet après-midi , je vais essayer la mise à jour sur ma VM de production. Et je verrais bien ce que cela donne.

**Comment by Krankhore** [comment]
Je viens de mettre Abeille à jour sur ma VM de prod . Et tout c'est passé sans problème et tout semble fonctionner.

J'ai également mis ensuite à jour Jeedom en 4.1.22 ( car j'étais en 4.1.20)  au cas où. Tout marche encore nickel.
Donc à priori, il n'y a pas de problème sur cette versiond'abeille. Jene sais pas ce qui c'est passé hier.

Sur ma VM de test, tout semble continuer à marcher mais avec une tout petite différence avec la prod.
Lorsque je modifie le setlevel pour une ampoule Philips hue, white ambiance le level se modifie immédiatement dans le widget mais pas avec la bonne valeur et 1à2 secondes après le level à la bonne valeur. Par exemple :
setlevel 50 level passe à 20 puis 2s après à 50
setlevel 30 level passe à 12 puis 2s après à 30
Alors que sur la VM de prod, après une modif de setlevel , le level ne change qu'au bout de 1à2s pour la bonne valeur.

Pour une ampoule IKEA 1000lm, le comportement ressemble mais avec un level intermediaire different ET EN PLUS pas à chaque fois. De temps , il n'y a pas de position intermédiaire. 

Je suppose que l'issue peut être  close ?

**Comment by Krankhore** [comment]
Il y a tout de même un truc bizarre.
Sur ma production tout à bien fonctionné pendant 2 jours. Hier soir, j'ai redémarré le démon et je n'ai plus eu de retour d'évènements ensuite alors que les commandes étaient bien transmises.
J'ai passé le mode du log en Info au lieu de défaut et donc relancé le démon.

Et là, tout à de nouveau fonctionné. Je ne sais si le problème est lié au mode du log ou bien seulement quelque chose qui se produit aléatoirement au moment de la relance du démon.
En tout cas, tout est encore normal depuis hier soir

**Comment by tcharp38** [comment]
@Krankhore il y a un truc qui me chagrinne c'est ce point

> Les retours d'états fonctionnent en mode Debug, Warning,Info et Error mais pas en Default et Aucun.

Tu le reproduis encore ?
Si oui comment tu verifies que les "retours d'etat fonctionnent" ?

**Comment by Krankhore** [comment]
J'étais resté sans changement (log en INFO) pendant une semaine, et je viens de retester : 
Ou je reproduit le cas

Dans la config, je passe le niveau de log à aucun.et je sauvegarde et je relance le démon.

Là tout marche encore bien. J'attends un peu pour relancer une deuxième fois le démon (pour ne pas qu'il dise moins de 45 secondes) .
Et cette fois, je n'ai plus de retour. A savoir: 
- sur le widget , je mets l'ampoule sur ON ou sur OFF 
- mon ampoule s'allume ou s'éteint bien
- MAIS dans jeedom, l'état de l'ampoule ne change plus

Je remets la config des logs en INFO. Je relance le démon deux fois (j(avais déjà remarqué par le passé qu'en redemarrant le démon après le changement du type de log, je n'étais pas toujours pris en compte)

ET là, tout fonctionne de nouveau normalement
la commande ON allume bien l'ampoule et quelques secondes après l'état passe allumé dans le widget de l'ampoule.
Idem en sens inverse pour le OFF.

**Comment by tcharp38** [comment]
Je n'arrive pas à reproduire ce souci.
Donc quand tu as le log en mode "AUCUN" tu n'as aucun retour d'info. Et j'imagine que les equipements passent en timeout.
Peux tu refaire l'essai et via la page support, surveiller les "queues".
Pour info tu devrais avoir la colonne "messages" à retombe à 0 regulierement.
Si ca n'est pas le cas en mode "ca marche pas", peux tu me faire un snapshot de l'état des queues ?
Merci

**Comment by Krankhore** [comment]
Pour les timeouts, je n'ai jamais attendu assez longtemps.

 je vais faire quelques tests.

**Comment by Krankhore** [comment]
Pour les timeouts, je n'ai jamais attendu assez longtemps.

 je vais faire quelques tests.

**Comment by Krankhore** [comment]
ça y est @tcharp38 , j'ai fait quelques tests sur ma vm jeedom de test.Il y a deux zigates wifi. Mes équipements sont sur la zigate 1.

Effectivement les équipements passent en timeout mais pas la ruche elle même
J'ai également vérifier les queues avec la commande IPCS.
Dans tous les cas de figures ci-dessous, elles étaient vides

Fichier zip avec les logs d'abeille en mode debug
[Ne fonctionne pas.zip](https://github.com/KiwiHC16/Abeille/files/6352735/Ne.fonctionne.pas.zip)
[Fonctionne au 2ieme démarrage.zip](https://github.com/KiwiHC16/Abeille/files/6352736/Fonctionne.au.2ieme.demarrage.zip)



Et au final au cours de mes essais,  le mode du log n'a pas d'importance. C'est suite à une relance du démon que cela marche ou pas.J'ai eu de la chance , j'ai pu produire le cas en debug.
L'équipement qui me sert à tester est une ampoule Phillips  :
Adresse (courte/IEEE) 65E8 / 0017880103853FD1
d logique Abeille1/65E8 
Nom jeedom  Lampe Patrice  id 79

- j'ai démarré avec les logs en debug à 18h30 , et j'ai allumé l'ampoule. Elle s'allume mais pas de changement dans l'état du widget
 c'est le fichier zip : Ne fonctionne pas

- J'ai effacé tous les logs et sans changer quoi que ce soit, j'ai redémarré le démon à 18h36
j'ai testé l'allumage et toujours pas de retour d'état. J'ai redémarré le démon et retesté à 18h37-18h38. Et cette fois c'est bon
Cette séquence c'est le fichier zip : Fonctionne au 2ieme démarrage

Dans chaque fichier zip , j'ai mis toutes les logs abeille qui contenaient quelque chose
Depuis , j'ai passé le log en aucun et redémarré le démon, et tout fonctionne toujours  correctement.

Le phénomène n'est pas bloquant puisque lorsque je suis dans le cas ou cela ne fonctionne pas, il me suffit de relancer le démon 1 ou 2 fois. Mais c'est plus que bizarre.
J'espère que dans les logs il y aura une piste

**Comment by tcharp38** [comment]
Je crois que j'ai enfin une piste mais si je me trompe pas ca n'a rien à voir avec le log.
Pour confirmer mes soupcons peux tu refaire un essai "qui fonctionne pas" en utilisant le fichier attaché ?
A decompresser dans core/class/AbeilleParser.class.php

[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6360611/AbeilleParser.class.php.zip)

Il suffira de regarder le log AbeilleParser.

Dans le cas ou ca ne fonctionne plus je m'attends a trouver des messages du type

> [2021-04-22 20:47:25] Abeille1, AbeilleIEEE_Ok==0 => msg 8010 ignored
> [2021-04-22 20:47:25] Abeille1, AbeilleIEEE_Ok==0 => msg 8002 ignored
> [2021-04-22 20:47:25] Abeille1, AbeilleIEEE_Ok==0 => msg 8102 ignored
>

**Comment by Krankhore** [comment]
je viens de faire les premiers essais, mais petit souci : 
- j'étais dans un cas  ou cela ne fonctionnait pas mais rien dans la log d'abeille parser. Mais c'était en mode log aucun faut il que je soit en debug ?
- je me suis mis en mode debug mais là tout fonctionne pour l'instant malgré plusieurs relances du démon.

Néanmoins même lorsque cela fonctionne , j'ai trouvé ceci dans la log abeille parser (voir fichier joint)
**_[2021-04-23 11:11:02][debug]   Ignored payload=0001040000010102D91302000018990A01FF421F0121A90B0421A8130521110006240200000000642989086521360B0A21E865
[2021-04-23 11:12:07][debug]   Ignored payload=00010400000101027D9A020000185B0A01FF421F0121450B0421A81305211100062402000000006429A2086521EC0B0A210000
[2021-04-23 11:12:14][debug]   Ignored payload=0001040405010102882C02000018450A000021A712_**

Également testé avec un scénario qui demande l'état de 3 ampoules (lampe salon/lampe maguit/lampe patrice) , deux se sont bien mis à jour mais pas lampe maguit ( 11h14  dans la log).
Néanmoins en exécutant le scénario une deuxième fois, l'état de lampe maguit s'est bien mis à jour (c'est une ampoule ikea comme lampe salon)

Je vais poursuivre les test pour me retrouver en mode debug avec une situation ou cela ne fonctionne pas( hier j'ai pu le faire sans problème  mais pour l’instant , je n'y arrive plus).

Petite question additionnelle : pourquoi est il indiquer à chaque redémarrage du démon: 
 **_Le mode de fonctionnement de la zigate a bien été modifié_**

[AbeilleParser-prev.log](https://github.com/KiwiHC16/Abeille/files/6364312/AbeilleParser-prev.log)

**Comment by Krankhore** [comment]
Ca y est , j'ai pu arriver dans le cas ou je suis en debug et ou cela ne fonctionne pas et j'ai effectivement le message que tu indiques
voir log abeille  parser çi-jointe

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6365378/AbeilleParser.log)

J'ai également vu dans la log abeille
**_[2021-04-23 14:42:40][DEBUG] : deamon_start(): ***** set zigate 1 in hybrid mode ********_**

Qu'est ce que cela veut dire mode hybride ?

**Comment by tcharp38** [comment]
Ok donc soupçons confirmés.
Je viens de créer une beta avec un certain nombre de correctifs: 210423-BETA-1
J'ai amélioré cette partie meme si je ne suis pas completement satisfait. 
A toi de me dire si tu tombes encore dans des cas d'erreur.

Le mode "hybride" permet de recuperer des paquets zigbee non supportés par le FW de la zigate.
Du coup Abeille en traite/utilise qq uns. Mais dispo que depuis la 3.1d

**Comment by Krankhore** [comment]
J'ai installé la branche beta depuis github
Mais le comportement est très bizarre , la remontée d'état se faisait de temps en temps comme s'ily avait du retard.
Les commandes ne réagissait pas toujours , ou comme s'il y avait un décalage.
plusieurs fois après redémarrage du démon, sur la commande on , l'ampoule s'allume puis la luminosité baisse et une fraction de seconde plus tard l'ampoule est allumé correctement. 
En tout cas , c'est beaucoup plus instable. Avant, les commandes passaient toujours bien (ce n'est plus le cas avec la beta) et les retour d’état revenaient en redémarrant 1ou 2 fois le démon ( en changeant le mode du log) et c'était de nouveau stable.


J'ai arrêté les test et jai désactivé le plugin en version beta que je faisait fonctionne sur ma VM de test car cela m'a mis le bordel dans ma production.
Je n'avais plus de retour d'état et pourtant sur cet environnement, je n'avais rien installé , pas redémarrer le démon et pourtant ce la a cessé de fonctionné pendant que je faisais les les essais de la beta dans la VM de test.

J'ai eu un peu de mal à récupérer la situation : débranchement et branchement de la zigate , redémarrage de jeedom, redémarrage du démon...
J'ai l'impression que ce qui a rétablit la situation , c'est de resauvegarder dans la config l'adresse de la  zigate 

Pour expliquer mon environnement j'utilise la **même** zigate wifi sur mes deux VM ( prod et test) . Jusqu'à présent je n'avais jamais eu d'impact entre les deux à part de temps en temps des erreurs de CRC car je pense que la zigate est un peu faible et répond mal aux requêtes des 2 environnements

Y a t il une contre-indication à attaquer la même zigate ?
Sinon, il faudra que je m'installe une  ampoule ou un capteur ssur ma 2ième zigate quie n'est vu  que par ma VM de test.

**Comment by tcharp38** [comment]
Depuis github, donc tu as la beta du jour ?

Je ne vois pas de soucis a utiliser une zigate wifi par l'un OU l'autre des systemes.

Je veux bien le package de logs des que ca déconne.

**Comment by Krankhore** [comment]
Je n'utilise pas la zigate wifi par l'un OU l'autre mais **par les 2 en même temps !**

Je vais voir comment refaire un essai sans mettre le bordel sur ma prod pour récolter des logs

Accessoirement sur mon test, j'ai remarqué que l'ampoule phillips avait une 'temperature light' à 3807K qui datait du 7 avril dernier. Cela faisait longtemps qu'elles était à zero. Sur les 2 autres ampoules et sur ces mêmes ampoules en production , c'est à toujours encore à 0.
Donc au cours d'un des innombrables essais , une fois , cet évènement à reussi à remonter.

**Comment by tcharp38** [comment]
Les 2 en meme temps ?!
Alors la je sais pas si elle est capable de gerer 2 connexions simultannées et faire la part des choses quand un msg arrive de chaque cote en meme temps. Faut voir avec son concepteur. Tu avais creusé cette piste ?

Essaie de pas melanger les sujets STP. On va ici se focaliser sur ton pb de remontées en visant un EQ particulier.
Si autre pb, faudra ouvrir (ou reouvrir) un autre sujet specifique. D'ac ?

**Comment by Krankhore** [comment]
OK
Je vais refaire des essais avec la version beta mais un peu plus prudemment .
Dès que j'ai le cas et avec des logs , je  les publient.

Sinon, pour info , une zigate connecté à deux jeedom fonctionne. Je l'ai fait pendant une paire de semaines. Seul impact obervé , de temps en temps une erreur de CRC signalé par abeille. 
Mais pour être sûr pendant les tests, je ne connecterait qu’un jeedom à la zigate

**Comment by tcharp38** [comment]
Ca n'est pas parce que ca "fonctionne" que c'est reellement supporté. Je t'invite à te prendre contact avec zigate pour confirmer que le FW supporte 2 connexions simultanées et gere donc bien les conflits.
Cette piste peut aussi en interesser d'autres si vraiment officielle.

Une erreur CRC dans ton cas peut vouloir dire
- defaut de transmission ou perturbation radio
- ou conflit (2 sources ecrivent/lisent dans la zigate en meme temps)
Dans tous ces cas Abeille ne peut rien faire pour corriger le tir, ni aucun autre plugin d'ailleurs.

**Comment by tcharp38** [comment]
@Krankhore 
Bon j'ai confirmation. Meme si ca peut potentiellement fonctionner ce mode de fonctionnement simultanné N'EST PAS supporté par la zigate. Il n'y a rien qui gére les eventuels conflits quand 2 messages arrivent en meme temps de 2 sources differentes.
Bref une config à oublier.

Voir https://github.com/fairecasoimeme/ZiGate/issues/361#

**Comment by Krankhore** [comment]
Je clos l'issue car vraisemblablement lié à l'utilisation de la même zigate wifi par deux instances de jeedom.

J'avais de refais quelques essais et effectivement , de temps cela fonctionne et puis à d'autres moment un des jeedom ne recupére plus rien voire n'arrive pas à envoyer des commandes.
