### ISSUE TITLE
Prise LIDL

### ISSUE THREAD

**Issue by sbx59** [KiwiHC16/Abeille#1913]
Bonjour,

j'avais laisser plusieurs message pour cette prise, un issue est deja crée mais n'y a aucune réponse ... Pouvez vous l'intégré ?

https://github.com/KiwiHC16/Abeille/issues/1736

bonne journée

**Comment by KiwiHC16** [comment]
Bonjour @sbx59,
Le temps manque... d ou le delai de réponse...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Comme il existe #1736, je clos cette issue.
