### ISSUE TITLE
Problème de remontée du link quality et du time-time avec les produits IKEA au niveau des widgets dans jeedom

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#1917]
Bonjour à tous,

Je ne vois plus le link quality et le time-time au niveau du widget dans jeedom pour la totalité des produits IKEA. Je vois correctement ces paramètres avec les sondes de températures Xiaomi/Aquara.

Lorsque que je vais dans le plugin et que je clique sur "network list", l'information est bien affichée.

Merci d'avance.
Ch

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

———————————————————————

Pensez à partager les informations de base de votre système. Pour cela faites un copier/coller des 3 premiers chapitres de la page support.

———————————————————————

**Comment by KiwiHC16** [comment]
Pour le link quality sur l equipement je ne te recommande pas de l utiliser. Il sera enlevé à plus ou moins long terme. Utilise la table à la place.

Pour le time-time, c est bizarre. Peux tu partager une capture d écran de la page commande de ton equipement ?

**Comment by tcharp38** [comment]
> Pour le link quality sur l equipement je ne te recommande pas de l utiliser. Il sera enlevé à plus ou moins long terme. Utilise la table à la place.

@KiwiHC16 tu peux detailler ca ? On parle du LQI qui arrive aves les 8100/8102 par ex ?

**Comment by ChrisChrisChri** [comment]
Pour finir, j'ai refait une inclusion et le time-time apparaît à nouveau. Par contre, toujours pas le link quality? Je trouvais cela pratique de le voir directement mais si cela disparait je ferai autrement. Par contre, détecteru incendier Heiman me remonte sans arrêt une batterie à 0%. J'ai changé la pile. Toujours à 0%. J'ai refait une inclusion et pas de changement...

**Comment by ChrisChrisChri** [comment]
Salut,
Merci pour ta réponse. C'est cette référence de mémoire SMART SMOKE SENSOR HS1SA. Je crois qu'il n'y en a que un chez Heiman.
Merci

**Comment by tcharp38** [comment]
Ok peux tu ouvrir un sujet different pour "Heiman HS1SA pas d'info batterie" ?
C'est histoire de bien séparer les pbs. Merci

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Que fait on avec ce sujet ? Le LQI manque toujours ? Si oui quel equipement (identifiant Zigbee STP) ?

**Comment by ChrisChrisChri** [comment]
C'est en ordre aussi.
Merci.

**Comment by tcharp38** [comment]
Ok je clos.
