### ISSUE TITLE
Transfert zigate + volet dans jeedom (actuellement dans eedomus)

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#1922]
Bonjour,

J'ai actuellement 16 volets zigbee profalux dans eedomus et je souhaiterais passer chez jeedom. J'ai fait un essaie avec un volet et celui s'inclue dans abeille puis quitte celle ci.
Au moment de l'inclusion j'ai tout met volets qui font un va et vient. Je me dit qu'ils ont bien de le reseau de la zigate mais comment l'intégrer à jeedom ?

Merci de votre aide

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

———————————————————————

Pensez à partager les informations de base de votre système. Pour cela faites un copier/coller des 3 premiers chapitres de la page support.

———————————————————————

**Comment by KiwiHC16** [comment]
Difficile pour moi de t'aider en direct car je n'ai pas ces volets. Mais plusieurs utilisateurs les possèdent et utilisent Abeille. Regardes dans les issues ouvertes mais aussi closes et dans le forum:
https://community.jeedom.com/tag/plugin-abeille

Il y a eu plein de discussions sur le sujet. Reviens vers moi si tu ne trouve vraiment rien. Demandes de l aide aussi sur le forum si pas deja fait.

**Comment by Seby9576** [comment]
J'ai déjà vu pas mal de chose sur le sujet, reste à savoir si je dois tout réinclure ou non. Apparemment je n'ai pas le choix.

Que veux tu dire par erase de l'eprom ? Est il obligé de faire 2 aller retour à la fin de la procédure ? Sur eedomus il n'y avait pas besoin. Merci de votre aide.

Cdt

**Comment by Xav-74** [comment]
Pour moi oui tu vas être obligé de tout réinclure, pas le choix !
Pour l'erase eprom, en gros tu remet ta Zigate à zéro. Il faut utiliser un petit utilitaire fourni sur le site zigate.fr (le même que pour la mise à jour du firmware. Tu repartiras ainsi d'une install propre.
Pour les 2 AR en fin de procédure, je me suis aperçu que ce n'étais pas obligatoire. Mais je te le conseille quand même vivement ! C'est la procédure envoyée par Profalux. C'est à la fin de ces 2 AR que le volets enregistre toutes les infos et quitte le mode inclusion.

Xav

**Comment by tcharp38** [comment]
Question... passer de Eedomus a Jeedom ca veut dire utiliser la meme zigate ?
Si oui je pense que @KiwiHC16 a deja qqch en tete pour "recuperer" tous les eq qui se signalent sur la zigate car toujours dans le meme reseau.

**Comment by Seby9576** [comment]
@tcharp38 
Oui c'est ce que je veux faire mais ca n'a pas l'air d'être possible. Vu la galère que j'ai eu pour inclure les volets j'aimerais ne pas avoir à recommencer.
@KiwiHC16 tu as regardé pour faire ca?

Merci

**Comment by Xav-74** [comment]
@Seby9576
Très honnêtement, et si tu veux éviter les galères plus tard je te conseille vivement de repartir de 0
J'ai du réinclure récemment tous mes BSO suite à une modification du code que j'avais demandé. En suivant scrupuleusement la procédure, j'ai passé 5 min par volets !

**Comment by tcharp38** [comment]
Xav a probablement raison.
Tu peux au moins tenter 1 volet et voir comme ca déroule, en le supprimant de Jeedom avant.

**Comment by Seby9576** [comment]
@Xav-74 a aucun moment tu as perdu la commande du volet ?

**Comment by Xav-74** [comment]
Hello @Seby9576
Pour être franc, j'ai perdu la commande une fois de l'un de mes volets. Lors de la première inclusion de mon premier volet. Est-ce que j'avais fait une mauvaise manip je ne sais pas. Mais depuis j'ai du réinclure au moins 3 fois tous mes volets (11) sans le moindre souci.

**Comment by Seby9576** [comment]
Salut @Xav-74 ,

Merci de ton retour. Est ce que tu peux commander tes volets en pourcentage et avec google home ? As tu des soucis de volet qui se ferme pas ou s'ouvre pas de temps en temps comme je peux avoir moi sur eedomus ? Et dernière question as tu le retour d'état du volet ?
Je dmande ca car je vais basculer ma zigate sur jeedom pendant et mes vacances et j'aimerais bien savoir avant.

Merci

**Comment by Xav-74** [comment]
Hello @Seby9576,

Pour Google Home, je pense que cela fonctionne mais j'utilise exclusivement Siri avec les %. Le principe reste le même.
J'utilise pour cela un plugin `Volet prop` qui permet de calculer précisément le % d'ouverture ou de fermeture en fonction du temps de montée du volet. J'arrive donc à une précision intéressante.
Et je te confirme que l'état du volet (ouvert / fermé) est bien géré sans souci.
Enfin, concernant les mouvements intempestifs, je n'ai jamais eu cela.
Quand tu feras ta migration, n'hésites pas, je t'aiderai. Mon pseudo est le même sur le community Jeedom ;)

Xav

**Comment by Seby9576** [comment]
Merci de ton aide, par contre ce n'est pas des mouvements intempestif mais ils ne bougent pas du tout dans le mode automatique mais en individuel ca fonctionne.

**Comment by Xav-74** [comment]
OK je comprends mieux ! Non rien de semblable de mon côté ;)

**Comment by Seby9576** [comment]
Salut,

Bon j'ai fait 14 volets sur 16. Les deux derniers je n'ai pas réussi mais c'est les deux plus éloignés. Je vais rapprocher la box demain.
Pour le retour d'état si commande avec le télécommande le retour ne fonctionne pas sauf si je fait un get level.
Tu peux me dire si tu utilise un widget plus sympa, genre un volet que l'on monte et on descend ? 
Merci

**Comment by Seby9576** [comment]
Salut, j'ai bine mes 16 volets, par contre le retour de position du volet n'est pas mit à jours automatiquement, avez vous une astuce svp ? Merci

**Comment by tcharp38** [comment]
Salut. 
Si tu fais allusion a un retour automatique quand tu changes la position avec la telecommande par ex, ca ne fonctionne pas ou pas bien. Pas eu le temps de creuser avec mes volets mais j'ai toujours ca en tete.

**Comment by pipiche38** [comment]
@tcharp38 il faut mettre un Configure Reporting sur le cluster 0x0008. Du reste, Profalux indique également qu'il faut piloter les Volets uniquement via ce cluster (et ne pas utiliser le cluster 0x0006 ). Dis moi si tu as besoin des infos du reporting ?

**Comment by tcharp38** [comment]
@pipiche38 
Merci pour l'info. Je me doutais d'un truc comme ca mais pas eu le temps.
Je reviendrai vers toi si je bloque.
Merci

**Comment by Seby9576** [comment]
@tcharp38 Ca ne se met pas toujours à jours non plus avec la commande via jeedom. 
@pipiche38 je ne comprend pas trop de quoi tu parles, tu parles d'une modification dans le plugin et non un paramétrage à faire ?

Merci

**Comment by tcharp38** [comment]
Il manque une partie de configuration à faire lors de l'inclusion. Ca sera une modif du fichier JSON.
Je m'y colle des que j'ai torché le sujet en cours.

**Comment by tcharp38** [comment]
Je clos ce sujet qui n'a plus rien à voir avec le transfert.
Voir https://github.com/KiwiHC16/Abeille/issues/1994
