### ISSUE TITLE
Interrupteur sans fil Zemismart : pb de commande

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1924]
Bonjour,

Je viens d'appairer cet interrupteur Zemismart [https://www.zemismart.com/products/zemismart-zigbee-smart-remote-switch-work-with-tuya-zigbee-hub-zigbee-sticker-switch](url). Abeille le reconnait comme un TS0041 mais je ne suis pas certain que ce soit le bon, en tout cas, le visuel n'est pas ok.
Quand j'ai validé le périphérique dans Jeedom après l'avoir juste changé de parent, j'ai eu un bandeau rouge affiché avec : Le nom de la commande ne peut pas être vide :AbeilleCmd Object ( [id:protected] => [logicalId:protected] => [generic_type:protected] => [eqType:protected] => [name:protected] => [order:protected] => 0 [type:protected] => [subType:protected] => [eqLogic_id:protected] => 1344 [isHistorized:protected] => 0 [unite:protected] => [configuration:protected] => [template:protected] => [display:protected] => [value:protected] => [isVisible:protected] => 1 [alert:protected] => [_collectDate:protected] => [_valueDate:protected] => [_eqLogic:protected] => [_needRefreshWidget:protected] => [_needRefreshAlert:protected] => [_changed:protected] => 1 ) 

Ma version d'Abeille est celle de Github : 210217-MASTER_TCHARP38-1

![image](https://user-images.githubusercontent.com/16527222/114314732-32398a80-9afc-11eb-9456-d4a1d1958441.png)

**Comment by tcharp38** [comment]
Salut
Si tu es sur le master, je pense que je viens de pousser le correctif pour ton pb.

**Comment by JC38** [comment]
Bonjour,
Oui, merci, je peux valider l'objet sans plus avoir le message d'erreur dans un bandeau rouge.
Maintenant, il faut que j'intègre cet inter dans un scénario, a première vue, il n'est pas hyper-réactif.

**Comment by tcharp38** [comment]
Si tu confirmes je te laisse cloturer ce sujet.

**Comment by JC38** [comment]
Je clôture pour le pb du bandeau d'erreur.
Merci @tcharp38
