### ISSUE TITLE
Erreur de pilote sur clézigate 

### ISSUE THREAD

**Issue by loustic03** [KiwiHC16/Abeille#1937]
Bonjour ,
 J'ai un souci sur le plugin j'ai régulièrement ce message 

![image](https://user-images.githubusercontent.com/76919490/114935169-25d66a00-9e3b-11eb-9aa8-4d99b99c1301.png)

![image](https://user-images.githubusercontent.com/76919490/114935478-8796d400-9e3b-11eb-8c61-40b4ce7e842a.png)

et zigate en FW 031D

**Comment by tcharp38** [comment]
Salut
Tu as réellement un souci du coup ?
Si tu as ce genre d'erreur c'est qu'il y a un message d'erreur dans le log du kernel (dmesg) concernant ta zigate USB.
Elle est en timeout ?

**Comment by loustic03** [comment]
Salut @tcharp38 
Non j'ai pas de problème de fonctionnement avec la zigate et elle n'est pas en timeout.
J'ai déjà eu cette erreur il y a quelque mois et cela c'est arrêté , mais c'est revenu depuis la dernière mise a jour que j'ai fais donc je me suis posé la question du pourquoi .
Es ce une faiblesse de la zigate?

**Comment by tcharp38** [comment]
Je crois que le PL2303 est connu pour n'être pas tres stable.
J'ai eu le souci avec ma premiere zigate USB. Il fallait vraiment debrancher la zigate et la rebrancher pour que ca rentre dans l'ordre.
D'ailleurs les dernieres Zigate ca a changé

![image](https://user-images.githubusercontent.com/35221038/115109314-6a662080-9f75-11eb-881c-c0ee4eaca574.png)

Concernant ce message c'est etrange que tu l'aies encore. Ou alors c 'est un vieux souci qui traine dans les logs ?
Je sais pas trop mais peut etre qu'il y a qqch a améliorer la.

**Comment by loustic03** [comment]
Salut , concernant le message d'erreur il a disparu (mystère)
*** Ou alors c 'est un vieux souci qui traine dans les logs?*** J'ai rien dans les logs donc a voir dans le temps .
J'ai le prolific bleu sur ma zigate ça fait 3 ans que je l'ai

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

———————————————————————

Pensez à partager les informations de base de votre système. Pour cela faites un copier/coller des 3 premiers chapitres de la page support.

———————————————————————

**Comment by KiwiHC16** [comment]
Perso je recommande les FTDI. 
SI tout ok dans ce cas ne rien faire mais si present tout le temps et message erreur CRC alors le changer en FTDI.

**Comment by loustic03** [comment]
Ok merci si cela continu je changerai le Prolific par un FDTI.
