### ISSUE TITLE
Inclusion wxkg11lm (bouton Aqara)

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#1942]
Bonjour,
Ce n'est peut-être pas un problème de plugin mais je n'arrive pas à inclure ce bouton Aqara. Je mets la clé en mode appairage, j'appuie plus de 10 secondes sur le petit bouton de l'inter, la led clignote bleue puis s'éteint mais je ne vois rien arriver dans Abeille.
Sur le site d'Abeille, il y a un peu de doc mais pas d'info sur l'appairage. Par contre , les liens qui pourraient aider pour les scenarios sont ko, si Kiwi pouvait les remettre, ce serait sympa.
![image](https://user-images.githubusercontent.com/16527222/115149953-98775d80-a066-11eb-8719-15767fe772d2.png)

Mes infos :
1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

———————————————————————

Pensez à partager les informations de base de votre système. Pour cela faites un copier/coller des 3 premiers chapitres de la page support.

———————————————————————

**Comment by KiwiHC16** [comment]
Pourrais tu mettre le plugin en débug, redémarrer le daemon, vider le log AbeilleParser, supprimer l objet pour cet equipement, faire une inclusion de l equipement, partager le log AbeilleParser.

**Comment by JC38** [comment]
Oups, je n'ai pas vu ta réponse de suite. Comme j'ai aussi le plugin Xiaomi, j'ai essayé l'appairage sur la gateway Xiaomi. ça a fonctionné du 1er coup. Sous ce plugin, le nom est remote.b1acn01
Il m'en reste un second pas encore déballé, je pourrai ré-essayer. Tu confirmes que le remote.b1acn01 est bien pris en charge par la Zigate et le plugin ?

**Comment by tcharp38** [comment]
Salut @JC38 
A priori ce "remote.b1acn01" fait partie des configs supportées par Abeille, meme si il peut rester des soucis.
Donc pour creuser tu peux faire ce que Kiwi suggerait. Le log parser pendant l'inclusion est le point d'entrée.
Pense à "supprimer de Jeedom" ton EQ si deja connu, meme en "defaultUnknown"

**Comment by tcharp38** [comment]
Salut @JC38 
Je suppose que le sujet ne t'interesse plus n'est ce pas ? Il me semblait que tu avais basculé sur une autre solution de dongle.

**Comment by JC38** [comment]
Bonjour. Oui, j'utilise maintenant plusieurs dongles, Zigate et autres.
