### ISSUE TITLE
$eqLogic->getStatus('lastCommunication') vs $cmd/'Time-Time'

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1945]
@KiwiHC16 
Je réalise qu'il y a 2 moyens de connaitre l'heure de derniere remontée d'un EQ.
- Via $eqLogic->getStatus('lastCommunication')
- ou via la commande 'Time-Time' de l'EQ

Pourquoi ca ?
N'y a t'il pas qqch à nettoyer ?
Laquelle privilegier ? Ou faut il garder les 2 ?

Ha et j'ai trouvé aussi pourquoi j 'étais parti sur "Last".
La ruche utilise une autre commande... pas "Time-Time" mais "Last" pour la meme info.

**Comment by mickadam29** [comment]
@tcharp38 

Il me semble que tu as indiqué que le dernier PR devait corriger ça justement. Je ne vois pas de changement sur le master. 
En revanche plus d'erreur dans AbeillePHP.log

![image](https://user-images.githubusercontent.com/36518012/115387217-a8b04980-a1da-11eb-8cde-e15c12726fe4.png)

**Comment by tcharp38** [comment]
Oui mais derniere comm ne peut etre rempli que si il y a un retour de l'EQ.
Ca n'est peut etre pas encore le cas.

**Comment by mickadam29** [comment]
Il m’envoie son état 1 fois / heure

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/115416671-42d2ba80-a1f8-11eb-85f9-42fa96c98485.png)

Et tjs pas d'info dernière comm

![image](https://user-images.githubusercontent.com/36518012/115416759-57af4e00-a1f8-11eb-8416-4b28f130aa00.png)

**Comment by tcharp38** [comment]
Migre moi ca sous un sujet séparé STP, et j'ai besoin de savoir si "Time-time" est une de ses commandes.

**Comment by mickadam29** [comment]
ok

**Comment by tcharp38** [comment]
$eqLogic->getStatus('lastCommunication') est mis à jour automatiquement par Jeedom dans

Fichier cmd.class.php

> public function event
> ...
> 		$this->setCache('collectDate', $this->getCollectDate());
> 		$this->setValueDate(($repeat) ? $this->getValueDate() : $this->getCollectDate());
> 		$eqLogic->setStatus(array('lastCommunication' => $this->getCollectDate(), 'timeout' => 0));
> 		$display_value = $value;
> 

Fichier eqLogic.class.php

> public function checkAndUpdateCmd($_logicalId, $_value, $_updateTime = null) {
> ...
> 		if ($_updateTime !== false) {
> 			$cmd->setCache('collectDate', date('Y-m-d H:i:s'));
> 			$this->setStatus(array('lastCommunication' => date('Y-m-d H:i:s'), 'timeout' => 0));
> 		}

et

> 	public function setIsEnable($_isEnable) {
> 		if ($this->isEnable != $_isEnable) {
> 			$this->_needRefreshWidget = true;
> 			$this->_changed = true;
> 			if ($_isEnable) {
> 				$this->setStatus(array('lastCommunication' => date('Y-m-d H:i:s'), 'timeout' => 0));
>

**Comment by tcharp38** [comment]
Utiliser l'info gérée par Jeedom... 'lastCommunication'

Time-Time & Time-TimeStamp ne sont que des cmdes infos specifiques Abeille.
