### ISSUE TITLE
Erreur Lift & Tilt - BSO Profalux

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#1948]
Hello @KiwiHC16,

Comme vu ensemble et pour mémoire, la dernière master a du cassé un truc sur la partie BSO car le "movelift&tilt" ne fonctionne plus pour mes BSO. Le passage en dernière beta a rétabli le service ;)

Merci d'avance pour ton aide,

Xav

**Comment by tcharp38** [comment]
@Xav-74 Ca veut dire quoi ? Tu as des soucis avec le master mais pas avec la beta d'hier ?

**Comment by Xav-74** [comment]
en fait je tourne en prod sur la master en mode nominal.
Lorsque j'ai fait la mise à jour de cette branche jeudi ou vendredi dernier, les BSO ne fonctionnaient plus (commande movelift&tilt).
Je suis donc revenu à la version beta qui a un train de moins que la master pour voir si cela venait de la master et cela a refonctionné !
Il y a donc du avoir une modif qui perturbe cette fonction.

**Comment by tcharp38** [comment]
Zut si qqch est cassé sur le master car c'est moi qui ai poussé le + de choses ces derniers temps.
Et j'aussi créé une beta hier à partir du master.
Ta version "Abeille" de la beta donne quoi ?

**Comment by Xav-74** [comment]
Version Abeille Beta 2021-04-07 01:00:08
J'ai pas encore passé la nouvelle.

**Comment by tcharp38** [comment]
Ha ok. Sauf si Kiwi a du temps va falloir qu'on creuse ensemble.
Je fais attention dans mes updates mais je ne suis pas à l'abri d'avoir cassé un truc ;(

**Comment by Xav-74** [comment]
pas de souci. Je vais essayer d'upgrader avec la nouvelle beta ce soir pour voir.
Je te tiens au jus

**Comment by Xav-74** [comment]
Hello !
Bon je viens de MAJ la dernière beta (20210418-BETA1) et je te confirme que les BSO ne fonctionnent plus.
Il va donc falloir remonter les différents commits pour essayer de comprendre. je vais jeter un oeil auj. 

Xav

**Comment by tcharp38** [comment]
Salut
Quand tu dis "fonctionnent plus" tu peux etre plus precis ?
C'est suite à une action ? Une remontée d'info ?

**Comment by Xav-74** [comment]
pardon oui, ce sont les nouvelles commandes que l'on venait d'implémenter avec Ben :
 - Commande Set Lift
 - Info Lift
 - Commande Set Tilt
 - Info Tilt

**Comment by Xav-74** [comment]
Ces commandes sont vraiment spécifiques au BSO

**Comment by tcharp38** [comment]
D'accord.
J'imagine que les 2 "set" sont des actions et les 2 autres des infos.
Peux tu en actionner un des set et me filer le package des logs en attendant 2 ou 3 mins au moins ?

**Comment by Xav-74** [comment]
oui c'est ca !
pour les logs, sur ma version actuelle qui fonctionne ?

**Comment by tcharp38** [comment]
Ha bien vu. Ca peut etre utile pour comparer.
La meme commande executée dans les 2 cas (celle qui fonctionne, et le dernier master ou la beta) si tu peux.

**Comment by Xav-74** [comment]
ok je fais ca ce soir ;)

**Comment by Xav-74** [comment]
si cela peut déjà t'aider, voici le logs AbeilleCmd pour une commande Tilt sur un BSO avec la version BETA qui fonctionne : 

```
[2021-04-20 11:48:05][debug] ------ execute(eqName=AB BSO Panoramique name=Set Tilt type=action, options={"slider":"70"})
[2021-04-20 11:48:05][debug] ------ execute(): Msg sent: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/3583\/moveToLiftAndTiltBSO","payload":"EP=01&lift=1&inclinaison=70&duration=10"}}
[2021-04-20 11:48:05][debug] ------ execute(): will process cmdAction with cmd Info Ref if exist: Tilt
[2021-04-20 11:48:05][debug]
[2021-04-20 11:48:05][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/3583/moveToLiftAndTiltBSO -> EP=01&lift=1&inclinaison=70&duration=10
[2021-04-20 11:48:05][debug]   L2 - procmsg({"topic":"CmdAbeille1\/3583\/moveToLiftAndTiltBSO","payload":"EP=01&lift=1&inclinaison=70&duration=10","priority":1,"message":null})
[2021-04-20 11:48:05][debug]     L1 - processCmd({"moveToLiftAndTiltBSO":"1","addressMode":"02","priority":1,"dest":"Abeille1","address":"3583","destinationEndpoint":"01","lift":"1","inclinaison":"70","duration":"10"})
[2021-04-20 11:48:05][debug]       sendCmd("Abeille1", cmd="0530", data="023583010100080104021E0a0510110110030146000a", shortAddr=3583, len="0016", priority=1)
[2021-04-20 11:48:05][debug]           incStatCmd(): {"0024":1,"0016":1,"0009":1,"0002":1,"0041":27,"0100":2139,"0010":161,"0530":8}
[2021-04-20 11:48:05][debug] ------ execute(): cmdAction with cmd Info Ref: Tilt with value slider: 70
[2021-04-20 11:48:05][debug]
[2021-04-20 11:48:05][debug]                      processCmdQueueToZigate(): J'ai 1 commande(s) pour la zigate a envoyer.
[2021-04-20 11:48:05][debug]                      sendCmdToZigate(Dest=Abeille1, cmd=0530, len=0016, datas=023583010100080104021E0a0510110110030146000a)
```

**Comment by tcharp38** [comment]
C est deja un debut pour mon info. Merci
N'hesite pas au lieu de faire un copy/paster de faire plutot drag & drop du fichier log, voir mieux du zip complet. J'aurai toutes les infos en meme temps.

**Comment by Xav-74** [comment]
Pas de souci. Besoin de quel log d'ailleurs ? Cmd ? Parser ? autre ?

**Comment by tcharp38** [comment]
La, d'abord cmd + cmd-prev
Mais si ca t ennuies pas tu fais ca via la page support, telecharger tout. Ca permet d'avoir un instantanné de tous les logs donc toutes les taches

**Comment by Xav-74** [comment]
Hello,

Dsl pour le délai mais j'avais pris qq jours de vacances :)
Voici les 2 fichiers de logs : 
- avec la beta du 07/04/21 -> test OK (voir action AB BSO Panoramique de 17h30
- avec la beta du 23/04/21 -> test KO (voir action AB BSO Panoramique de 17h35

Merci d'avance pour ton aide

[AbeilleLogs-210425_beta_210423_KO.tar.gz](https://github.com/KiwiHC16/Abeille/files/6372318/AbeilleLogs-210425_beta_210423_KO.tar.gz)

[AbeilleLogs-210425_Beta_210407_OK.tar.gz](https://github.com/KiwiHC16/Abeille/files/6372319/AbeilleLogs-210425_Beta_210407_OK.tar.gz)

**Comment by tcharp38** [comment]
ok

> [2021-04-25 17:30:03][debug] ------ execute(eqName=AB BSO Cuisine name=getLevel type=action, options={"background":"0"})
> [2021-04-25 17:30:03][debug] ------ execute(): Msg sent: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/2463\/ReadAttributeRequest","payload":"EP=01&clusterId=0008&attributeId=0000"}}
> [2021-04-25 17:30:03][debug] 
> [2021-04-25 17:30:03][debug] Message from queueKeyAbeilleToCmd: CmdAbeille1/2463/ReadAttributeRequest -> EP=01&clusterId=0008&attributeId=0000
> [2021-04-25 17:30:03][debug]   L2 - procmsg({"topic":"CmdAbeille1\/2463\/ReadAttributeRequest","payload":"EP=01&clusterId=0008&attributeId=0000","priority":1,"message":null})
> [2021-04-25 17:30:03][debug]     L1 - processCmd({"ReadAttributeRequest":"1","priority":1,"dest":"Abeille1","address":"2463","clusterId":"0008","attributeId":"0000","EP":"01","Proprio":"0000"})
> [2021-04-25 17:30:03][debug]       sendCmd("Abeille1", cmd="0100", data="0224630101000800000000010000", shortAddr=2463, len="000e", priority=1)
> [2021-04-25 17:30:03][debug]           incStatCmd(): {"0024":1,"0016":1,"0009":1,"0002":1,"0041":1154,"0100":101664,"0010":7703,"0530":78,"0092":40,"004E":378,"0084":11,"0049":3,"0014":8,"0045":16,"0043":13,"0062":5,"0060":4}
> [2021-04-25 17:30:03][debug]                      
> [2021-04-25 17:30:03][debug]                      processCmdQueueToZigate(): J'ai 1 commande(s) pour la zigate a envoyer.
> [2021-04-25 17:30:03][debug]                      sendCmdToZigate(Dest=Abeille1, cmd=0100, len=000e, datas=0224630101000800000000010000)
> [2021-04-25 17:30:03][debug] Abeille1, Type=8000/Status, Status=00/Success, SQN=92, PacketType=0100
> [2021-04-25 17:30:03][debug] Abeille1, Type=8011/APS data ACK, Status=00, Addr=2463, EP=01, ClustId=0008
> [2021-04-25 17:30:03][debug]   Found: [Cuisine][AB BSO Cuisine] set APS_ACK to 1
> [2021-04-25 17:30:03][debug]   APS_ACK: 1
> 

ko

> [2021-04-25 17:34:03][debug] ------ execute(eqName=AB BSO Cuisine name=getLevel type=action, options={"background":"0"})
> [2021-04-25 17:34:03][debug] ------ execute(): Msg sent: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/2463\/ReadAttributeRequest","payload":"EP=01&clusterId=0008&attributeId=0000"}}
> 
> [2021-04-25 17:34:06] Message from queueKeyAbeilleToCmd: TempoCmdAbeille1/2463/getLevel&time=1619364866 -> EP=01&clusterId=0008&attributeId=0000
> [2021-04-25 17:34:06]   L2 - procmsg({"topic":"TempoCmdAbeille1\/2463\/getLevel&time=1619364866","payload":"EP=01&clusterId=0008&attributeId=0000","priority":4,"message":null})
> 
> [2021-04-25 17:34:27] Message from queueKeyCmdToCmd: CmdAbeille1/2463/getLevel -> EP=01&clusterId=0008&attributeId=0000
> [2021-04-25 17:34:27]   L2 - procmsg({"topic":"CmdAbeille1\/2463\/getLevel","payload":"EP=01&clusterId=0008&attributeId=0000","priority":4,"message":null})
> [2021-04-25 17:34:27]   WARNING: Unknown command ! (topic=CmdAbeille1/2463/getLevel)


Note

> getLevel =  "topic": "ReadAttributeRequest",
>             "request": "EP=#EP#&clusterId=0008&attributeId=0000",
> 

http.error

> [Sun Apr 25 17:34:34.471304 2021] [php7:error] [pid 10675] [client 192.168.0.20:61741] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php:61\nStack trace:\n#0 /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php(132): AbeilleCmd::updateField('Abeille1', Object(AbeilleCmd), 'EP=01&lift=#cmd...', Array)\n#1 /var/www/html/core/class/cmd.class.php(1104): AbeilleCmd->execute(Array)\n#2 /var/www/html/plugins/virtual/core/class/virtual.class.php(335): cmd->execCmd(Array)\n#3 /var/www/html/core/class/cmd.class.php(1104): virtualCmd->execute(Array)\n#4 /var/www/html/core/ajax/cmd.ajax.php(88): cmd->execCmd(Array)\n#5 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php on line 61, referer: http://192.168.0.250/index.php?v=d&p=plan&plan_id=2
> [Sun Apr 25 17:35:12.527415 2021] [php7:error] [pid 10675] [client 192.168.0.20:61751] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php:61\nStack trace:\n#0 /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php(132): AbeilleCmd::updateField('Abeille1', Object(AbeilleCmd), 'EP=01&lift=#cmd...', Array)\n#1 /var/www/html/core/class/cmd.class.php(1104): AbeilleCmd->execute(Array)\n#2 /var/www/html/plugins/virtual/core/class/virtual.class.php(335): cmd->execCmd(Array)\n#3 /var/www/html/core/class/cmd.class.php(1104): virtualCmd->execute(Array)\n#4 /var/www/html/core/ajax/cmd.ajax.php(88): cmd->execCmd(Array)\n#5 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleCmd.class.php on line 61, referer: http://192.168.0.250/index.php?v=d&p=plan&plan_id=2
> 
>

**Comment by tcharp38** [comment]
Si jamais tu peux refaire un essai avec la derniere beta en decompressant le fichier attaché dans core/class/AbeilleCmd.class.php
[AbeilleCmd.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6373290/AbeilleCmd.class.php.zip)

Merci pour les logs comparatifs. Tres utiles.

**Comment by Xav-74** [comment]
Merci pour ta réactivité ! Je teste ca ce soir et je te redis

**Comment by Xav-74** [comment]
Par contre, je regardai les logs que tu as extrait, il concerne la commande `getlevel` de l'équipement `AB BSO Cuisine` et pas la commande `setTilt` de l'équipement `AB BSO Panoramique`
Mais peut-être que la cause du souci est néanmoins la même.

**Comment by tcharp38** [comment]
Il y a au moins un pb commun et je ne sais pas comment le tester moi meme.
Sinon parlant de BSO, le sujet https://github.com/KiwiHC16/Abeille/issues/1851 etait pour toi aussi non ?
SI oui tu me donne ton status ?

**Comment by Xav-74** [comment]
Tu peux clore le sujet [#1851](https://github.com/KiwiHC16/Abeille/issues/1851)
Merci

**Comment by tcharp38** [comment]
Du nouveau ?

**Comment by Xav-74** [comment]
Je te confirme que tout est OK avec la version 210423-BETA1 et le fichier AbeilleCmd.class.php modifié ;)
Merci bcp pour ton aide
Tu peux clore cette issue ;)

**Comment by tcharp38** [comment]
Ok il faut donc que je pousse cette modif et on cloturera qu'une fois que la nouvelle beta est ok pour toi.
Ca le fait ?

**Comment by Xav-74** [comment]
Parfait !
Je peux même repasser en master si tu préfères. C'était mon cas avant la découverte du bug.

**Comment by tcharp38** [comment]
je mets à jour le master la avant tout
