### ISSUE TITLE
Nouvelle ampoule IKEA: TRADFRIbulbE27WSopal980lm

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#195]

**Comment by KiwiHC16** [comment]
Est ce type d ampoule ?

http://www.ikea.com/ie/en/products/lighting/smart-lighting/trådfri-led-bulb-e27-980-lumen-wireless-dimmable-white-spectrum-opal-white-art-10318263/


Fonction: On/Off/Level ?
Autres ?

**Comment by mickadam29** [comment]
Voici ce que j'ai pour le kit
Fonction : On/Off/Level et Spectre de Blanc

[ampoule e27.pdf](https://github.com/KiwiHC16/Abeille/files/1803847/ampoule.e27.pdf)

**Comment by mickadam29** [comment]
Pour le spectre de blanc, en partant du modèle TRADFRIbulbE27CWSopal600lm qui gère la couleur
la gestion du jaune/blanc (températeur de couler) se fait via le titre et le message du bouton couleur
A priori Titre=0000 -> jaune Titre=FFFF -> blanc. Message semble pouvoir rester à 0000.
Ci-joint mon fichier json

[TRADFRIbulbE27WSopal980lm.txt](https://github.com/KiwiHC16/Abeille/files/1803902/TRADFRIbulbE27WSopal980lm.txt)

Idéalement; il faudrait remplacer la gestion de la température par un curseur qui agit sur le X (titre)

**Comment by KiwiHC16** [comment]
Je viens mettre dans le master cette ampoule. Pour l instant que les On/Off et Level.
Pour le Hue, il faut que je regarde car la commande n est pas implémentée. J'avais fait des tests mais pas mis dans le code.

Je regarderai aussi ton test avec la couleur pour comprendre comment ca se passe derriere et pourquoi ca semble marcher.

**Comment by mickadam29** [comment]
Parfait. J'ai supprimé la ruche, désinstallé le plugin
réinstallé depuis github et mes ampoules sont créées automatiquement.

**Comment by KiwiHC16** [comment]
;-)

**Comment by mickadam29** [comment]
As-tu corrigé les quotes dans les commandes bind ?

**Comment by KiwiHC16** [comment]
Le bind fait parti des trucs en cours. C'est quoi la problématique des quotes ?

**Comment by mickadam29** [comment]
lorsque l'on utilise les boutons BindToZigateEtat, la commande envoyée d'après les logs contient les adresse entre quotes
BindtoZigateEtat envoie -> address='000B57fffee7338a'&ClusterId=0006&reportToAddress='00158d0001b6997c'
Et cela ne marche pas
Si tu le fait depuis le bouton de la ruche, avec zone Titre et Message, il n'y pas les quotes ''
-> address=000B57fffee7338a&ClusterId=0006&reportToAddress=00158d0001b6997c
Et là ça fonctionne. L'ampoule renvoie bien son état. Le pb est identique pour Level

Voici les logs dans la version que j'avais hier.


Via le bouton Titre et Message de la ruche : 
[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/bind} => address=000B57fffee7338a&ClusterId=0006&reportToAddress=00158d0001b6997c

Via le bouton de l'objet lampe : 
[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/bind} => address='000B57fffee7338a'&ClusterId=0006&reportToAddress='00158d0001b6997c'

Pour le Report les commandes semblent correctes, il n'a pas les quote
[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/setReport} => address=4aac&ClusterId=0006&AttributeId=0000&AttributeType=10

**Comment by KiwiHC16** [comment]
Ah Ok, je ne savais pas. En fait j'étais tout content de parvenir à récupérer les adresses IEEE pour la commande BindtoZigateEtat et au moment de tester, je me suis rendu compte que je ne parvenais pas a faire un bind si le message est routé alors je suis parti dans des investigations sur le routage ZigBee.

Le probleme que tu partages ne devrais pas etre dure à résoudre des que je reviens sur ce sujet.

**Comment by mickadam29** [comment]
OK. D'ailleurs dans le même ordre d'idée, pendant que tu seras le CMDAbeille, lorsque l'on clique sur Liste des équipements, la commande est bien envoyée et interprétée mais cela ne rafraichit pas la vue (Last et Last Stamps) get network status et/ou inclusion status le fait. Je trouve bien pratique le rafraichissement.
Mais peut-être faut-il ouvrir un autre "issue"

**Comment by KiwiHC16** [comment]
Liste Equipement #199

**Comment by KiwiHC16** [comment]
Je viens de mettre dans Master la correction des problemes de "'" dans les Bind.

**Comment by KiwiHC16** [comment]
"Autre point concernant ces ampoules et la télécommande réelle. Via la télécommande le "level" évolue par pas de 17% (appui bref) sans pour autant être en mesure de l'éteindre alors que la remontée du level indique 0% et le graphe à 0": 

Je viens de regarder et le fonctionnement est "normal". Sur Up, la telecommande envoie un Up 43 (17%) avec On/Off. Donc si l ampoule est Off, elle s'allume. Par contre pour le Down, la commande envoyée est down (sans le on/off) donc l ampoule ne s'éteint pas mais reste au niveau luminosité minimum. C'est codé en dur dans la telecommande Ikea. On ne peut pas changer ce comportement. Apres on peut faire des actions Jeedom. Je prefere resté collé au fonctionnement actuel et apres les utilisateurs peuvent faire des scenarios. Qui peut le plus peux le moins.  Scenario peut etre si level = 0 alors Switch off.

**Comment by KiwiHC16** [comment]
Pour simuler la télécommande, je peux ajouter de Up/Down en plus du slider. Je crée une issue #200

**Comment by KiwiHC16** [comment]
"Et peut-être est-il possible de positionner le curseur de la télécommande réelle, à la même valeur que celui de la lampe ?" 
C'est couvert par l'issue #186 

Mais le scenario suivant ne peut pas etre couvert. Deux groupes d ampoules sont commandés chacun par une télécommande. Une ampoule fait partie des deux groupes. Son niveau sera celui de la derniere commande recue. Le slider de l ampoule peut etre mis a jour mais le slider de la telecommande qui n'a pas fait la derniere demande ne peut ^tre mis a jour car dans son groupe des ampoules ont des level différents. Donc les ampoules auront leur slider au niveau de leur luminosité et les télécommande au niveau de leur derniere demande.

**Comment by mickadam29** [comment]
nickel pour la simple quote du bind. Et je n'avais pas pensé aux groupes et ampoules multiples pour les level différents. C'est finalement logique. C'est le slider sur l'objet télécommande qui induit en erreur puisque finalement cette fonction n'existe par sur la télécommande. Je pense comme tu l'as dit qu'il faudrait un up/down et après à chacun de masquer ou pas le slider.

**Comment by mickadam29** [comment]
Pour revenir sur le sujet du slider et setlevel, n'est-il pas possible qu'ils évoluent ensemble ? Je parle uniquement de l'objet lampe. Slider 100% -> setlevel à droite, Slider à 0% ->setlevel à gauche. Au milieu pour 50%

**Comment by KiwiHC16** [comment]
C'est couvert par l'issue #186

**Comment by mickadam29** [comment]
ok.

**Comment by mickadam29** [comment]
Petite remarque. Pourrais-tu inverser les boutons pour que le up soit à droite et le down à gauche ? Plus logique pour ma part par rapport au slider qui à droite correspond au plus élevé (d'où le up à droite)
Idem pour le on/off -> Off à gauche et On à droite. Sinon, bien cette nlle télécommande. Reste la T°.

**Comment by mickadam29** [comment]
Crois-tu qu'il soit envisageable d'envoyer la valeur pour "level". Par exemple, je souhaite un scénario mode détente (level=17%) et travail (level=100%) ?

**Comment by KiwiHC16** [comment]
"Reste la T°." Tu veux dire le temperature de la lumiere ?

**Comment by KiwiHC16** [comment]
Scenarios tournent chez mois. Tu peux faire un truc comme: 

![capture d ecran 2018-03-15 a 10 17 34](https://user-images.githubusercontent.com/8549674/37454196-318e6c28-283a-11e8-8792-3d18790a3f93.png)

8009 est l adresse de ma telecommande.
Je fais =17/100*255 car le set level est si je me souveins bien entre 0 et 255. Je te laisse vérifier.

**Comment by mickadam29** [comment]
Ok, je vais vérifier ces points. Pour la température, je parle en effet de la lumière. (ton)
Pour voir les changements de la télécommande, je suppose que je la supprime suivi d'un get-name.
Par contre, je ne vois pas de mise à jour disponible sur github. Comment est-ce que je récupère le modèle que tu changé dans ce cas de figure ? Je ne pourrais tester que dans la soirée les boutons. Par contre je teste à distance le scénario. Merci

**Comment by KiwiHC16** [comment]
Ca va être plus long car les boutons "droite/gauche" sur la telecommande ne commande pas le ton mais les scenes. Les scenes ne sont pas encore dans Abeille. Et hier je me suis cassé les dents sur le control du Hue....

**Comment by mickadam29** [comment]
Débutant sur Jeedom, je ne sais pas encore à quoi correspondent les scènes. Je suis surpris de la complexité dont tu parles, c'est toi qui maîtrise, car le fait d'utiliser le bouton "color" avec X=xxxx  et message Y=0000 influe déjà sur la température ces ampoules. Par exemple, 3 boutons qui enverraient par exemple X=0000, X=FFFF et éventuellement X=une valeur quelconque serait un moyen de tester. Pour moi tu as déjà pratiquement le code dans le modèle json.
Je ne suis pas certain des valeurs de X. Mais 0000 et FFFF font passer d'un ton chaud à froid (ou inversement)

**Comment by mickadam29** [comment]
Pour la mise à jour, c'est ok. Ce soir je recrée la télécommande. Merci

**Comment by KiwiHC16** [comment]
Dans la standardisation ZigBee, il y a les groupes que tu connais mais aussi les scenes. L'idée est d'envoyer une seule commande et tous les équipments se mettent en place pour cette scene: exemple: scene 1: lampe 1 rouge 10% et prise 3 On, scene 2: lampe 3 - Off et Volet ouvert...

Toujours dans le standardisation, la lumiere est gérée de plusieures facons:
- level = intensité
- color = la couleur
- Hue = Teinte
- Temperature
- Saturation

Pour l instant il a les deux premiers dans Abeille. 

Si la couleur te permet de faire la temperature que tu veux alors passe par des scenarios.

Pour ce qui est de la couleur avec les X et Y, je ne comprends pas comment cela fonctionne. Visiblement ca suit la standardisation "Commission Internationale de l'Éclairage (CIE)".

Si tu cherches l'espace de couleur sur le net tu trouveras plein d'image comme celle ci : http://quasar.cc.osaka-kyoiku.ac.jp/colorworld2010/space/color3/xyz1.png

Si tu veux regarder et partager ta comprehension.

**Comment by mickadam29** [comment]
La lumière reste très complexe en effet ! Entre la teinte, la température, la saturation !!!

Au fait, la présentation diffère. A gauche la télécommande réelle créée avec l'ancien modèle et droite le nouveau (up à droite) mais surtout l'un au dessus de l'autre. Ca reste du dessin, mais ne peut-on pas fixer la disposition des boutons qq soit la taille (largeur/hauteur) de l'objet ?

Je vais regarder pour ajuster la température par scénario, mais un slider serait un ajout parfait pour les ampoules dont la t° est modifiable.

"Si la couleur te permet de faire la temperature que tu veux alors passe par des scenarios.
Pour ce qui est de la couleur avec les X et Y, je ne comprends pas comment cela fonctionne."
Sans pouvoir t'expliquer,
C'est juste que sur une ampoule qui n'est pas à couleur variable mais à température variable, le fait de pousser la même commande avec X,Y joue sur la couleur pour un modèle et sur la température pour l'autre. 
Pour la couleur tu as codé :
![image](https://user-images.githubusercontent.com/36518012/37461160-c8883e2a-284d-11e8-8081-9ff47bcd56d4.png)

Pour la température (qui d'ailleurs ne doit pas être dans le json, puisque pas gérée par ce modèle  ni la Gu10 que je t'ai fournie)
il me semble qu'il suffit d'ajuster X en laissant Y=0000

Je ne suis pas développeur, mais si tu m'expliques brièvement le cheminement des données et fichiers utilisés je pourrais tenter de coder (commande slider dans l'objet, code php dans CMDAbeille.php en reprenant celui de la couleur mais en le limitant au seul X)

**Comment by KiwiHC16** [comment]
Disposition, je viens refaire un push.

**Comment by KiwiHC16** [comment]
Je pense comprendre la manip que tu fais mais je ne trouve pas les infos dans les ampoules pour que cela fonctionne. Cela ne fonctionne pas avec es ampoules.
Pour ton ampoule qui gere la temperature peux tu me donner son nom ?
Peux tu faire la demande "SimpleDescriptorRequest" dessus ? Et me donner le log Parser associé à la réponse.

![capture d ecran 2018-03-15 a 13 11 00](https://user-images.githubusercontent.com/8549674/37462666-0e46a168-2853-11e8-8cc2-c79b301e8bbd.png)

**Comment by mickadam29** [comment]
Je te fais ça. Etant absent de chez moi je ne pourrais te donner le résultat de la température (froid/chaud)
Voici un exemple avec la plus froide ou la plus chaude. Et on inverse en mettant X=0000 

![image](https://user-images.githubusercontent.com/36518012/37465714-3011f4ba-285c-11e8-9377-52c72500457c.png)

**Comment by mickadam29** [comment]
Pour le nom, il s'agit de l'une ou l'autre de ces ampoules IKEA

![image](https://user-images.githubusercontent.com/36518012/37465845-94a26e14-285c-11e8-9540-2958eebaf1d0.png)

**Comment by mickadam29** [comment]
Il semble qu'il y ai un pb depuis la mise à jour de ce matin

![image](https://user-images.githubusercontent.com/36518012/37466028-0c48bcb6-285d-11e8-84c0-47676798e2e8.png)

**Comment by KiwiHC16** [comment]
Normelement le dernier master ne devrait plus avoir ce probleme

**Comment by mickadam29** [comment]
Résultat de SimpleDescriptorRequest"


AbeilleParser 2018-03-15 14:34:14[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 7c
AbeilleParser 2018-03-15 14:34:14[DEBUG];type: 8043 (Simple Descriptor Response)(Not Processed); SQN : 7c; Status : 00; Short Address : 0Dc8; Length : 22; endpoint : 01; profile : c05e; deviceId : 0220; bitField : 02; InClusterCount : 09
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0008 - General: Level Control
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0300 - Lighting: Color Control
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 0B05 - Misc: Diagnostics
AbeilleParser 2018-03-15 14:34:14[DEBUG]In cluster: 1000 - ZLL: Commissioning
AbeilleParser 2018-03-15 14:34:14[DEBUG]OutClusterCount : 04
AbeilleParser 2018-03-15 14:34:14[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-03-15 14:34:14[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2018-03-15 14:34:14[DEBUG]Out cluster: 0020 - General: Poll Control
AbeilleParser 2018-03-15 14:34:14[DEBUG]Out cluster: 1000 - ZLL: Commissioning

**Comment by mickadam29** [comment]
Dernier master avec relance du daemon et ok pour le log

**Comment by mickadam29** [comment]
Est-ce que je peux te fournir un lien vers un autre github ? (genre smartthings). Si oui je collerai le lien mais tu connais certainement.
Quelques modèles IKEA référencés et il est traité de la température de l'ampoule

**Comment by mickadam29** [comment]
Si ça peut aider. Traite spécifiquement de cette ampoule
Autre lien 

https://github.com/ebaauw/homebridge-hue/wiki/ZigBee-Devices

The light supports ct values from 250 (4000K) to 454 (~2200K). The box seemed to suggest that it only had three colour temperature settings, but that's a limitation of the remote.

En mettant 
X=01C6 et Y=0000 > Lumière Blanc Chaud (2200)
X=00FA et Y=0000 > Lumière Blanc Neutre (4000)
Sur l'objet lampe ça agit correctement. Attention le FFFF ne correspond pas à une de ces 2 valeurs !!

![image](https://user-images.githubusercontent.com/36518012/37493683-0bc0eed2-28a6-11e8-9bb3-cc439f7d2bb4.png)



La séquence envoyée par setcolor semble "surchargée" par Y
En écrivant l'une des 2 valeurs dans le cluster 0300/Endpoint 01 pour IKEA on agit sur la température
Selon la norme, la valeur à écrire pour 2200K = 1000000/**454** (01C6) et 4000K = 1000000/**250** (00FA)

2 boutons pour chacune de ces valeurs est peut-être un bon départ ou une liste déroulante en remplacement du type message

**Comment by KiwiHC16** [comment]
"Est-ce que je peux te fournir un lien vers un autre github ?" Oui bien sure, quel est ce lien ?

**Comment by KiwiHC16** [comment]
Je viens de faire un push avec les modifications pour gérer le spectre de blanc/Temperature.
Mets a jour sur le master et dis moi si ca fonctionne.

**Comment by mickadam29** [comment]
Ca marche nickel. Vérifié également avec la GU10WS. Comme on voit les 8 leds, je te confirme que pour 2200 seules les 4 leds orangées sont allumées, 2700 les 8 sont allumées et 4000 seules les 4 leds blanches sont allumées. Donc valeurs et fonctionnement sont ceux attendus. Il va être facile de créer des ambiances !

**Comment by KiwiHC16** [comment]
Si en plus le hard confirme ce qu'on observe alors c est tip top.
Voila un truc de plus qui fonctionne.

**Comment by KiwiHC16** [comment]
Je clos l issue. On reouvrira si besoin de modifs additionnelles.
