### ISSUE TITLE
Page EQ/Derniere comm non renseigné mais Time-Time OK

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1951]
@tcharp38 

L'information LastCommunication n'est pas disponible dans l'objet
![image](https://user-images.githubusercontent.com/36518012/115422572-53396400-a1fd-11eb-8a49-a76038ff0aa1.png)

Pourtant, il récupère de façon régulière des infos
![image](https://user-images.githubusercontent.com/36518012/115422671-6b10e800-a1fd-11eb-9b9c-4a4889c10e75.png)

Et la commande TIME-TIME créée à partir du json fonctionne
![image](https://user-images.githubusercontent.com/36518012/115422797-8b40a700-a1fd-11eb-890f-d28f8f19fb61.png)

**Comment by tcharp38** [comment]
Tu es sur le master ?

**Comment by mickadam29** [comment]
Oui

**Comment by mickadam29** [comment]
Informations clefs nécessaires au support.

Quand vous ouvrez une "issue" dans GitHub merci de copier/coller les 3 premiers chapitres ci dessous 
Pour l'intégration d'un équipement non encore supporté ajoutez le chapitre 4.

1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l","","**************************************","*           Welcome to Jeedom        *","**************************************","Username : jeedom","Password : Mjeedom96",""]
["Linux jeedom 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

4/ AbeilleParser / Modelisation
===============================
[2021-04-20 17:30:06]   ModelIdentifier='diy-mains-fault', trimmed='diy-mains-fault', [Modelisation]

**Comment by mickadam29** [comment]
Je n'ai pas ce problème sur mon env de prod qui a la stable du market

**Comment by tcharp38** [comment]
Je me posais la meme question mais je ne pense pas.
Ha par contre peut etre que ca ne fonctionne pas si la commande n'est pas "affichée"

**Comment by mickadam29** [comment]
En prod, j'ai vérifié. Ni affiché, ni historisé. Et LastComm est renseigné

**Comment by tcharp38** [comment]
Pour info je crois qu'entre ta "prod"' et le master j'ai changé la donne dans le sens ou le "Derniere comm" est remis à jour en temps reel maintenant. Mais j'ai bien peur que ca depende du fait qu'il soit affiché ou non. Pas encore verifié.

**Comment by tcharp38** [comment]
Tu peux tester sur le dernier master ?

**Comment by mickadam29** [comment]
Je vais recharger. J'installe à l'instant. 14H00
J'ai mélangé les 2 sujets. J'ai mis des infos dans #1952 

Ca marche avec la dernière release.
Tu veux qu'on clôture ce point ?

**Comment by tcharp38** [comment]
Ok on cloture. A reouvrir si besoin
