### ISSUE TITLE
Redémarrage JEEDOM et Timeout

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#1952]
Est-ce normal d'avoir tous les objets en timeout à l'issue d'un redémarrage ?
Probablement lié au #1951

![image](https://user-images.githubusercontent.com/36518012/115508307-73106c80-a27d-11eb-82ee-324dc935205b.png)

Je vais attendre que les équipements se manifestent, mais ça me semble curieux. Je m'attends à ce que le dernier enregistrement, évènement soit inscrit dans la BDD et, qu'à l'issue du reboot, jeedom reprenne cette valeur en référence.

Il s'agit bien d'un reboot qui a pris qqs minutes. Pas d'arrêt et redémarrage de jeedom 5j après.

Les commandes Time-time et TimeStamp ne renvoient rien. Comme si ces valeurs n'étaient pas écrites dans la BDD

![image](https://user-images.githubusercontent.com/36518012/115508933-2711f780-a27e-11eb-9af0-661fabf47879.png)

1/ Version (Abeille.version)
============================
210217-MASTER_TCHARP38-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l","","**************************************","*           Welcome to Jeedom        *","**************************************","Username : jeedom","Password : Mjeedom96",""]
["Linux jeedom 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by tcharp38** [comment]
Sur le master je suppose ? Tu aurais le package des logs ?

**Comment by tcharp38** [comment]
Je viens d'essayer sur ma box de test et je vois pas ce souci. Tu fais redemarrer via Reglages->Systeme->Redemarrer ?

**Comment by mickadam29** [comment]
Oui, sur le master
De quel log as tu besoin ?

**Comment by mickadam29** [comment]
Je te dépose le package de logs

**Comment by mickadam29** [comment]
Comme convenu, les équipements se sont manifestés (l'ampoule n'est pas branchée) 25 et 14

![image](https://user-images.githubusercontent.com/36518012/115549616-23e03100-a2a9-11eb-9a77-ef10d8fbb7f5.png)

[AbeilleLogs-210421.tar.gz](https://github.com/KiwiHC16/Abeille/files/6350562/AbeilleLogs-210421.tar.gz)

**Comment by mickadam29** [comment]
> Je viens d'essayer sur ma box de test et je vois pas ce souci. Tu fais redemarrer via Reglages->Systeme->Redemarrer ?

Oui,

**Comment by mickadam29** [comment]
Après redémarrage, tjs rien dans dernière comm. Mais ça reçoit. 
![image](https://user-images.githubusercontent.com/36518012/115549976-98b36b00-a2a9-11eb-8250-be8c39166dd0.png)
Et time-time aussi à jour
![image](https://user-images.githubusercontent.com/36518012/115550104-bf71a180-a2a9-11eb-9d51-3b6a3dc02185.png)

**Comment by mickadam29** [comment]
Du coup, comme c'est à jour (dernière release du master installée à 14h)  je fais le redémarrage pour voir si j'ai encore timeout ou pas. Content d'avoir un env de DEV

**Comment by mickadam29** [comment]
Tjs le point au redémarrage

![image](https://user-images.githubusercontent.com/36518012/115551077-df559500-a2aa-11eb-8ca3-7222a811d6c5.png)

Mais en même temps, au redémarrage l'info est perdue 
![image](https://user-images.githubusercontent.com/36518012/115551302-2479c700-a2ab-11eb-9031-d262974d41d9.png)

**Comment by tcharp38** [comment]
Inclusion capteur puis reboot box
![image](https://user-images.githubusercontent.com/35221038/115960343-204ee300-a511-11eb-8b71-e486a9290024.png)

Appui sur son bouton => retour d'info
![image](https://user-images.githubusercontent.com/35221038/115960416-9bb09480-a511-11eb-8ede-76829920e0a3.png)

Il y a bien qqch a creuser et améliorer mais je ne crois pas que ce soit bloquant. Je pense aussi que ca doit etre vieux ce souci non ?

**Comment by tcharp38** [comment]
@mickadam29 
Salut. D'apres toi ce pb est toujours d'actualité ?

**Comment by mickadam29** [comment]
Salut. Ce n’est pas bloquant dans la mesure où les équipements finissent par se manifester. Ferme le ticket si tu le souhaites

**Comment by tcharp38** [comment]
Non non je ne ferme que si le pb est résolu. Je dois m'embrouiller les pinceaux si toujours d'actualité.

**Comment by tcharp38** [comment]
@mickadam29
J'ai besoin de ton aide sur ce point. Tu le reproduis toujours ?

**Comment by mickadam29** [comment]
Voici des news
Raspberry - Pizigate 3.1E - JEEDOM 4.1.27
Avec cette config je n'ai plus le problème.
L'heure de dernier contact est parfaitement pris en compte. Reboot vers 19h20
![image](https://user-images.githubusercontent.com/36518012/144758674-80b671d5-2773-43a5-be9f-fd57467b328b.png)

**Comment by mickadam29** [comment]
Problème corrigé
