### ISSUE TITLE
Ajout support ampoule INNR RB285C

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1966]
En lien avec https://community.jeedom.com/t/plugin-abeille-et-ampoule-innr-rb165/55955

@Zaboon26
Modele preliminaire tout simple a essayer. Devrait permettre d'allumer et eteindre.
A décompresser dans core/config/devices/RB285C.
[RB285C.zip](https://github.com/KiwiHC16/Abeille/files/6407659/RB285C.zip)

Reinclure l'equipement apres suppression de Jeedom.

**Comment by tcharp38** [comment]
Jeexplorer pour "uploader" et decompresser le zip au bon endroit
html/plugins/Abeille/core/config/devices

puis RB285C/RB285C.json

**Comment by tcharp38** [comment]
Version corrigée mais toujours limitée On/Off.
Désolé pour le fichier corrompu.

[RB285C.zip](https://github.com/KiwiHC16/Abeille/files/6420537/RB285C.zip)

**Comment by Zaboon26** [comment]
Salut tcharp38 ! Me voici enfin connecté à GitHub :)

Donc tout d'abord un grand merci pour le fichier qui fonctionne, ampoule incluse bien reconnue et commande on off fonctionnelle, objet crée automatiquement. 
Puis-je aider à activer les autres commandes ?

**Comment by tcharp38** [comment]
Ok bonne nouvelle.
A quelle commandes fais tu allusion en priorité ?

**Comment by Zaboon26** [comment]
Je pense en priorité à la variation de la luminosité, vraiment utile suivant les moments de la journée, puis le réglage de la température et enfin le mode couleurs, et l'ampoule sera au top.
Le retour d'état a l'air de fonctionner impeccable déjà ce qui est vraiment super !

**Comment by tcharp38** [comment]
Tiens, essaie cette version.
Il manque vraiment des choses dans Abeille pour simplifier cette procedure mais on y travaille.

[RB285C.zip](https://github.com/KiwiHC16/Abeille/files/6439850/RB285C.zip)

**Comment by Zaboon26** [comment]
Yes je vais essayer ça, pas de soucis c'est un super taf que vous faites sur ce plugin 🙂

**Comment by Zaboon26** [comment]
Ça fonctionne, c'est un peu poussif mais le résultat est là, ne manquent que les sliders pour contrôler la température (chaud vers froid) et la palette de couleurs 💪
J'ignore à quel point ça peut être difficile à paramétrer, en tout cas un grand merci pour la taf effectué 🙏🙂

**Comment by tcharp38** [comment]
Que veux tu dire par "poussif" ?
Voila une update pour la temperature de lumiere.
Si tu as un PNG pour cet equipement je peux l'ajouter aussi.
[RB285C.zip](https://github.com/KiwiHC16/Abeille/files/6446060/RB285C.zip)

**Comment by Zaboon26** [comment]
Nickel ça fonctionne !
Par poussif j’entends le retour d'info qui est un peu déroutant sur le slider des niveau, ça le fait bouger un peu dans tous les sens une fois que je l'ai placé quelquepart pendant quelques secondes, mais au final ça fonctionne bien c'est l'essentiel.
Par contre il manque le mode rgb pour que ce soit complet :)
Cette ampoule est compatible phillips hue donc je pense que les commandes doivent être identiques à une philips hue rgb "classique"

Merci à toi ! :+1: 
![RB285C](https://user-images.githubusercontent.com/83779297/117548587-0bf10700-b036-11eb-86cb-5b40ccaf2ea6.png)

**Comment by tcharp38** [comment]
J'avoue que ne connais pas ces produits. Je n'ai aucune ampoule alors je decouvre les commandes au fur et a mesure.
Je creuse.

D'ailleurs as tu une idée des commandes zigbee correspondantes ? Ou tu n'as regardé ce genre de detail ?
Je dis ca car le cluster color, semble etre un des + complets et donc + compliqué. Trop de possibilites et il faudrait arriver à savoir quelles sont les commandes zigbee les + importantes.

**Comment by Zaboon26** [comment]
Je suis un parfait novice et j'avoue ne pas avoir encore les connaissances pour répondre à ta question, malheureusement.
Ou pourait-je trouver ce genre de commandes ?
 Peut-être que je fais fausse route, mais ne serait-ce pas possible d'extraire les commandes d'une ampoule déjà supportée par le plugin afin de l'appliquer à celle ci ? Après tout elle ne doit pas être si différente d'un device à l'autre.

Bien sur je dit cela afin d'essayer de trouver des pistes mais mes connaissances sont parfaitement ridicules à ce niveau...
Merci pour tout ce que tu fais en tout cas !

**Comment by tcharp38** [comment]
Ben si tu precises un peu ce que tu attends. 'RGB hue" c est trop vague pour moi.
Je ne sais pas si il y a des ampoules completement supportées et si ca correspond. Du coup je me vois pas faire une brute copie sans rien maitriser.

Donc si tu as des exemples de "commandes philips Hue classique" peut etre que je comprendrai mieux ce que je dois chercher

Pour info cote il y a un "cluster" (ensemble de commandes et informations) dédié au controle de couleur (cluster 0300). Tu cherches sur le net "zigbee cluster lib" et tu dois trouver ce dont je parle mais attention c est technique.

**Comment by Zaboon26** [comment]
Bonjour tcharp38, merci pour ton retour,

Ce que j'attends c'est simplement de pouvoir contrôler les couleurs sur l'ampoule. 
Je n'ai aucune idée de comment cela peut s’intégrer malheureusement mes connaissance sont nulles sur le sujet, de plus je ne possède pour le moment aucun équipement de ce type duquel je pourrait extraire les commandes liées au contrôle de la couleur pour te le montrer, par contre j'avais des commandes en ce sens avec le plugin zigate, est-ce que cela peut t'être utile ? Si besoin je peut tout à fait refaire une inclusion via ce plugin et te fournir tout type d'info qui pourrait t'être utile :)
J'ai parcouru le pdf du zigbee cluster lib et j'ai retrouvé la section 0300 qui mentionne tout un tas de commandes dont j'ai souvenir d'en avoir croisé certaines avec le plugin zigate.

Voilà pour moi, bonne journée.

**Comment by tcharp38** [comment]
Salut
Oui peut etre que si tu me montres ce que ca donne avec Zigate et la/les commandes concernées, j'arriverai à piger.

**Comment by tcharp38** [comment]
Salut @Zaboon26 
Je sais que ca date mais es tu toujours interessé par ce sujet ?

**Comment by Zaboon26** [comment]
Bonjour!
 Oui bien sûr ça m'intéresse toujours.
Belle journée

**Comment by tcharp38** [comment]
Salut
Du coup tu peux me résumer la situation du jour avec ton recul ?

**Comment by Zaboon26** [comment]
Alors aujourd'hui je l'utilise toujours en mode test car je n'ai pas encore
déménagé et avec le plugin officiel ZigBee tout fonctionne impeccablement.
Je n'ai pas ressayé le plugin abeille

**Comment by tcharp38** [comment]
Salut @Zaboon26 
Merci pour ton retour. Du coup vu que tu es content du plugin officiel, je considere que ce sujet n'a pas de sens sur Abeille.
Je clos mais à reouvrir si ca interesse qqn d'autre.
