### ISSUE TITLE
SonOff SNZB-02 - pb récup Temp + Hum suite mise à jour pluggin

### ISSUE THREAD

**Issue by JeffB04** [KiwiHC16/Abeille#1967]
Bonjour,

Visiblement suite à une mise à jour du plugin, je ne parviens plus à récupérer les valeurs Temperature et Humidité des capteurs Sonoff SNZB-02.
Le problème apparait lors de l'ajout de nouveau capteur uniquement. Les anciens capteurs déjà présent sur Jeedom et fonctionnels continue à fonctionner correctement sauf si les supprime et réintègre.
La détection se passe bien, mais lors du processus d'ajout, j'ai des erreurs visiblement au niveau du template.
[2021-05-01 11:49:48][DEBUG] : message(topic='Abeille2/3536/0000-01-0010', payload='')
[2021-05-01 11:49:48][DEBUG] :   L'objet 'Abeille2/3536' existe mais pas la cmde '0000-01-0010' => message ignoré
[2021-05-01 11:49:56][DEBUG] : message(topic='Abeille2/3536/SimpleDesc-DeviceDescription', payload='Temperature Sensor')
[2021-05-01 11:49:56][DEBUG] :   L'objet 'Abeille2/3536' existe mais pas la cmde 'SimpleDesc-DeviceDescription' => message ignoré
[2021-05-01 11:49:56][DEBUG] : Update ONLINE Status
[2021-05-01 11:49:56][DEBUG] : message(topic='Abeille2/3536/SimpleDesc-01-DeviceDescription', payload='zigbeeTemperature Sensor')
[2021-05-01 11:49:56][DEBUG] :   L'objet 'Abeille2/3536' existe mais pas la cmde 'SimpleDesc-01-DeviceDescription' => message ignoré

Version Jeedom : 4.1.22
Version du pluggin : 210217-MASTER_TCHARP38-1

L'ajout d'autre équipements Sonoff (comme des relais) fonctionne bien.

Plus d'info dans le fichier de log ci-joint :
[debug-log-SNZB-02.txt](https://github.com/KiwiHC16/Abeille/files/6409360/debug-log-SNZB-02.txt)
 
Merci par avance à la communauté pour son aide !

Cordialement.

**Comment by tcharp38** [comment]
Salut
Tu prends la version stable du market ?

**Comment by JeffB04** [comment]
Sur mon profil jeedom, j'accepte effectivement les pluggins en version Bêta. 
Cependant, le centre de mise à jour m'indique que le core ainsi que les versions sont de type "stable". 

La dernière version du pluggin Abeille date du 7 avril. 
Penses-tu que j'ai récupéré une version beta buguée ?

![image](https://user-images.githubusercontent.com/83496407/116793002-7220db80-aac4-11eb-9f8b-4f6cb8b211ff.png)

Merci de ton aide.

**Comment by tcharp38** [comment]
Non tu es sur la derniere stable c'est clair.
Depuis j'ai fait une beta. Si tu peux la tester ca serait bien. J'ai fait plusieurs corrections qui devrait repondre à ton pb.

**Comment by JeffB04** [comment]
Je te confirme que la version beta a résolu le problème de remontée des valeurs de température et d'humidité.
A présent, les sondes fonctionnent correctement à présent.
J'ai prévu de réaliser l'intégration d'autres matériels zigbee demain. Je te tiendrais au courant si je constate d'autres soucis.
Merci de ta réactivité et de ton efficacité... vraiment !

**Comment by tcharp38** [comment]
Cool.
Il me semblait que c'etait fixé.

Juste pour info, quand tu ouvres un nouveau sujet tu peux avant juste faire une recherche rapide sur ceux déja ouverts.
Il y avait déja celui la: https://github.com/KiwiHC16/Abeille/issues/1911.

Je pense faire un stable des demain.

**Comment by tcharp38** [comment]
Beta 210503-BETA-1

**Comment by tcharp38** [comment]
Salut @JeffB04 
Tu en es ou de ce cote ?
J'ai fait une autre beta hier => 210520-BETA-4
Si tu veux tester, penses à faire un backup avant pour pouvoir revenir à la derniere stable au cas ou.

**Comment by JeffB04** [comment]
Bonjour,

Je viens de mettre à jour le pluging en version 210526-BETA-1
Je n’ai pas constaté d’anomalie pour le moment.
Si tu veux que je teste quelque chose en particulier… je peux.
Cordialement.


De : tcharp38 ***@***.***>
Envoyé : vendredi 21 mai 2021 15:39
À : KiwiHC16/Abeille ***@***.***>
Cc : JeffB04 ***@***.***>; Mention ***@***.***>
Objet : Re: [KiwiHC16/Abeille] SonOff SNZB-02 - pb récup Temp + Hum suite mise à jour pluggin (#1967)


Salut @JeffB04<https://github.com/JeffB04>
Tu en es ou de ce cote ?
J'ai fait une autre beta hier => 210520-BETA-4
Si tu veux tester, penses à faire un backup avant pour pouvoir revenir à la derniere stable au cas ou.

**Comment by tcharp38** [comment]
Salut @JeffB04 
Tu as refait une inclusion du coup ?
Juste pour verifier qu'il n'y a toujours pas de regression par rapport à la stable precedente.

**Comment by JeffB04** [comment]
oui, l'inclusion après la suppression fonctionne correctement. 
Tu peux clôturer le case.
Merci encore pour ton aide.

**Comment by tcharp38** [comment]
Je clos. A reouvrir si toujours des soucis.
