### ISSUE TITLE
Ajout support ampoule INNR RB165

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#1972]
En lien avec https://community.jeedom.com/t/plugin-abeille-et-ampoule-innr-rb165/55955

@NikoScotch
Voila un modele tout simple, juste pour faire du On/off.

[RB165.zip](https://github.com/KiwiHC16/Abeille/files/6420593/RB165.zip)

**Comment by NikoScotch** [comment]
Merci @tcharp38 pour le ZIP.
Voici ce que j'ai testé : 
j'ai inséré le fichier JSON ici : 
`html/plugins/Abeille/core/config/devices/RB165/RB165.json`
Puis j'ai supprimé et réinclus l'ampoule. Mais pas de changement par rapport avant : j'ai bien un équipement qui se crée (`Abeille1-116`), mais il n'a toujours pas de commande ON/OFF.
Peut-être ai-je loupé quelque chose ?
Je joins les LOG abeille pour analyse si besoin (pour info j'ai fait l'inclusion aujourd'hui à 16h49) : [AbeilleLogs-210504.tar.gz](https://github.com/KiwiHC16/Abeille/files/6421994/AbeilleLogs-210504.tar.gz)
Merci à vous !
Cordialement.

**Comment by tcharp38** [comment]
Peut etre que j'ai aussi loupé qqch.
J'allais dire "etrange je ne vois pas le log AbeilleParser dans le package" mais je comprends. Il s'agit d'un bug que j'ai corrigé.

Serais tu partant pour faire l'essai sur la beta ?
Tu fais un backup avant tout histoire de pouvoir revenir en arriere si besoin.

Qq infos pour mémoire

> [2021-05-04 16:49:51][debug] Abeille1, Type=8045/Active endpoints response, SQN=DC, Status=00, ShortAddr=9D92, EndPointCount=02, EndPointList=; 01; 02, [Modelisation]
> [2021-05-04 16:49:51][debug]   ModelIdentifier='RB 165', trimmed='RB165', [Modelisation]

> [2021-05-04 16:49:51][debug]   ManufacturerName='innr', trimmed='innr', {"Abeille1\/9D92":{"time":1620139791,"ManufacturerName":"innr"}}, [Modelisation]
> [2021-05-04 16:49:52][debug] Abeille1, Type=8043/Simple descriptor response, SQN=DE, Status=00, Addr=9D92, Length=16, EP=01, Profile=C05E/Zigbee Link Layer (ZLL), DevId=0100/Dimmable light, BitField=02, [Modelisation]
> [2021-05-04 16:49:52][debug]   [Modelisation] InClusterCount=06
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0000 - General: Basic
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0004 - General: Groups
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0003 - General: Identify
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0006 - General: On/Off
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0008 - General: Level Control
> [2021-05-04 16:49:52][debug]   [Modelisation] InCluster=0005 - General: Scenes
> [2021-05-04 16:49:52][debug]   [Modelisation] OutClusterCount=01
> [2021-05-04 16:49:52][debug]   [Modelisation] OutCluster=0019 - General: OTA
>

**Comment by NikoScotch** [comment]
Hello, oui je peux tester, dis moi juste comment switcher sur la version bêta du plugin ? Merci !

**Comment by tcharp38** [comment]
Tu suis ca et choisi "beta" au lieu de "stable"
https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-standard
 Si qqch n'est pas clair, dis moi que je corrige la doc au passage.

**Comment by tcharp38** [comment]
Je viens de trouver une boulette dans le modele de base.
Donc meme avec la beta il te faut prendre ce fichier.
A decompresser dans "core/config/commands"
[RB165.zip](https://github.com/KiwiHC16/Abeille/files/6436285/RB165.zip)

**Comment by NikoScotch** [comment]
Hello @tcharp38 ,
je n'ai pas de dossier `commands` dans `html/plugins/Abeille/core/config/`
(uniquement un dossier `devices`)
Je dois créer le dossier `commands `du coup ?
Que se passe-t-il si j'installe la beta, ça écrase ma config stable ?
merci !

**Comment by NikoScotch** [comment]
Hello,
alors les news.
Tout d'abord pour rappel les conditions du test :
* je suis toujours en version stable
* j'ai placé le [1er fichier](https://github.com/KiwiHC16/Abeille/files/6420593/RB165.zip) ici : `html/plugins/Abeille/core/config/devices/RB165/RB165.json`
* j'ai placé le [2ème fichier](https://github.com/KiwiHC16/Abeille/files/6436285/RB165.zip) ici : `html/plugins/Abeille/core/config/commands/RB165.json`
* j'ai supprimé puis ré-inclu l'ampoule (aujourd'hui vers 17h03)
* mais toujours pareil : le module est bien créé, mais toujours pas de commande ON/OFF créée

Ci joint les logs : [AbeilleLogs-210510.tar.gz](https://github.com/KiwiHC16/Abeille/files/6453106/AbeilleLogs-210510.tar.gz)
Merci à toi !

**Comment by tcharp38** [comment]
Salut.
Si version stable, on va pas perdre de temps la.
J'ai fait une stable il y a qq heures. Elle devrait apparaitre demain sur le market et tu réappliquera les derniers fichiers par dessus.

**Comment by NikoScotch** [comment]
Hello @tcharp38 
désolé j'ai mis un peu de temps à pouvoir faire le test...
Mais la bonne nouvelle c'est que ça marche !
Je suis donc en Abeille version 2021-05-11, j'ai placé [ce fichier](https://github.com/KiwiHC16/Abeille/files/6436285/RB165.zip) aux 2 endroits suivants (2 fois le même fichier) :
`html/plugins/Abeille/core/config/devices/RB165/RB165.json`
`html/plugins/Abeille/core/config/commands/RB165.json`
Et je re-fais l'inclusion, j'obtiens bien un nouveau module avec les commandes ON, OFF, TOGGLE. et ça fonctionne.
Encore merci !

**Comment by tcharp38** [comment]
Bonne nouvelle.
Mais le fichier ne va que dans "devices". Rien à mettre dans commands.

**Comment by tcharp38** [comment]
@NikoScotch 
J'ai fait une beta hier qui doit inclure tout ca => 210520-BETA-4
Si tu es tenté, tu peux la tester et signaler toute regression.
Penses bien à faire un backup si jamais tu devais revenir vers la stable.

**Comment by tcharp38** [comment]
Pas de news. Je considére le modele suffisament utilisable.
Je clos mais à réouvrir si besoi,.
