### ISSUE TITLE
Install fresh sous docker (privilege)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#1979]
![Capture d’écran 2021-05-07 à 10 10 34](https://user-images.githubusercontent.com/8549674/117419088-7877e300-af1c-11eb-99d6-3781ab5496a2.png)

installer ne fonctionne pas et provoque l erreur

![Capture d’écran 2021-05-07 à 10 10 19](https://user-images.githubusercontent.com/8549674/117419053-6eee7b00-af1c-11eb-828b-a52804b2e816.png)

**Comment by tcharp38** [comment]
Devrait etre fixé

**Comment by KiwiHC16** [comment]
Aussitôt dit aussitôt fait !!!
Merci. 
(Pas testé de mon côté)

**Comment by tcharp38** [comment]
J'ai pu le reproduire.
Boulette sur installSocat aussi.

**Comment by tcharp38** [comment]
Je clos.
C'est normalement résolu dans la 210520-BETA-4
A reouvrir si besoin
