### ISSUE TITLE
Support Tya Smart Wireless Scene Switch, ESW-0ZAA-EU

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#1991]
Bonjour à tous,

J'ai depuis quelques semaines une commande Aqara qui fonctinne très bien avec la zigate et Abeille. J'ai associé un scénario pour le click rapide, double click et click long. Je commande soit du Legrand, soit du IKEA.

J'ai eu l'occasion d'acquérir la télécommande ronde IKEA ainsi que la télécommande de chez Tuya. L'inclusion se déroule correctement par contre lorsque je clique sur les boutons des 2 télécommandes rien ne se passe. On dirait qu'il n'y aucune remontée d'informations. Je ne sais donc pas créer un scénario. 

Je ne pense pas que le problème vienne de la télécommande car lorsque je fais un appairage de la commande IKA avec l'ampoule alors celle-ci est capable de la piloter. MAIS alors l'ampoule sort du réseau géré par la ZIGATe. J'ai vu plusieurs posts sur le sujet mais je me demandais s'il n'était pas possible de faire en sorte que ces télécommandes communiquent de la m^me manière que Aqara ?

Merci d'avance.

![image](https://user-images.githubusercontent.com/82177848/118239175-b84d4600-b499-11eb-8c82-3efc4d630791.png)

![image](https://user-images.githubusercontent.com/82177848/118239275-d7e46e80-b499-11eb-9261-e98a9e87ee82.png)

# @tcharp38 @KiwiHC16

**Comment by tcharp38** [comment]
Le standard zigbee propose des tas de solutions pour couvrir un max de fonctionalités mais du coup il y a aussi des tas de trucs "optionnels". Et quand bien meme chaque constructeur fait un peut son interpretation.

Bref tout ca pour dire que je ne sais pas ce que tu entends par "communiquent de la meme maniere" mais en dehors de supporter l'equipement, Abeille ne peut que suivre ses fonctionalités.

Tu as un exemple concret du souci dont tu parles ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Merci pour le retour.

Cela concerne le retour au niveau de l'état
Ex Aqara  il peut passer de 0 à 1 ou 2. Je peux construire un scénario en fonction de cette valeur.
![image](https://user-images.githubusercontent.com/82177848/118315993-8918f200-b4f6-11eb-9a8d-04686abd1699.png)


Pour IKea, on peut voir des valeurs dans le carré bleu mais lorsque je clique sur les boutons, ces valeurs ne bougent pas.
![image](https://user-images.githubusercontent.com/82177848/118316251-e1e88a80-b4f6-11eb-94bf-e1bc79e68bc6.png)


Pour Tuya, on dirait qu'il n'y pas d'affichage prévu pour l'affichage d'une valeur lorsqu'on clique sur les botuons. 
![image](https://user-images.githubusercontent.com/82177848/118316602-515e7a00-b4f7-11eb-981f-8654eb610aa9.png)

En espérant que cela t'aide...

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
J'ai compris qq trucs en essayant de faire qqch avec les telecommandes profalux.

Du coup qq infos
- Une telecommande n'est pas un equipement a qui tu envoies des ordres (autant envoyer l'ordre directement à l'equipement visé)
- Une telecommande n'est pas censée remonter un status. Si par ex tu veux le status d'un volet, ca n'est surement pas la telecommande qui va te dire "il est ouvert" ou "il est fermé". La encore il faut prendre le status de l'equipement visé pour avoir cette info.
- Enfin meme si elles s'integrent au reseau zigbee, il n'y pas pas toujours des infos utiles a recuperer coté Jeedom. Je prends l'exemple de la profalux. Elle est la dans le reseau mais vu de Jeedom aucun interet. Elle ne retourne meme pas son status de batterie. Bref elle est masquée

Du coup il est clair que faire des scenaris sur la base d'une info venant d'une telecommande ne fait pas de sens.

D'accord avec ca ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,

Je comprends en partie ;-)

-)_Une telecommande n'est pas un équipement a qui tu envoies des ordres (autant envoyer l'ordre directement à l'equipement visé)_   --> Ok mais la télécommande va bien envoyer un ordre quelque part ? Il est ou ce quelque part  alors ?

Comment fais-tu alors pour dire à l'ampoule A de s'allumer avec la télécommande B ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,

Je comprends en partie ;-)

-)_Une telecommande n'est pas un équipement a qui tu envoies des ordres (autant envoyer l'ordre directement à l'equipement visé)_   --> Ok mais la télécommande va bien envoyer un ordre quelque part ? Il est ou ce quelque part  alors ?

Comment fais-tu alors pour dire à l'ampoule A de s'allumer avec la télécommande B ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,

Je comprends en partie ;-)

-)_Une telecommande n'est pas un équipement a qui tu envoies des ordres (autant envoyer l'ordre directement à l'equipement visé)_   --> Ok mais la télécommande va bien envoyer un ordre quelque part ? Il est ou ce quelque part  alors ?

Comment fais-tu alors pour dire à l'ampoule A de s'allumer avec la télécommande B ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,

Je comprends en partie ;-)

-)_Une telecommande n'est pas un équipement a qui tu envoies des ordres (autant envoyer l'ordre directement à l'equipement visé)_   --> Ok mais la télécommande va bien envoyer un ordre quelque part ? Il est ou ce quelque part  alors ?

Comment fais-tu alors pour dire à l'ampoule A de s'allumer avec la télécommande B ?

**Comment by tcharp38** [comment]
La telecommande B controle l'ampoule A sans passer par Jeedom.
Si tu veux controler l'ampoule tu dois le faire sans passer par la telecommande (Jeedom => Ampoule).
Et le status vient de l'ampoule elle meme.

Ca te semble pas logique ?

**Comment by ChrisChrisChri** [comment]
Non ça ne me semble pas logique ;-)

Je pensais que le principe d'une box domotique était de pouvoir créer un scénario en fonction d'un événement. 
Par exemple, si j'appuye sur le bouton 1 de la télécommande, j'allume toutes les lampes. Le bouton 2, je coupe la totalité, etc...
L'autre exemple est: cette même ampoule pourrait s'allumer en cas de fuite d'eau ou autre...

Surtout que lorsque je fais l'appairage de ma télécommande IKEA avec ampoule IKEA alors les 2 équipements sortent du réseau. Du coup, si  je veux par exemple "allumer la lampe" avec un autre événement comme un capteur d'ouverture de porte je n'y arrive plus comme l'équipement n'est plus là...  

Je suis bon uniquement pour acheter du aqara alors comme cela marche avec cette marque.

Tu comprends ce que je veux dire ?

**Comment by tcharp38** [comment]
> Je pensais que le principe d'une box domotique était de pouvoir créer un scénario en fonction d'un événement.
> Par exemple, si j'appuye sur le bouton 1 de la télécommande, j'allume toutes les lampes. Le bouton 2, je coupe la totalité, etc...
> L'autre exemple est: cette même ampoule pourrait s'allumer en cas de fuite d'eau ou autre...

D'accord avec cette idée.

>  Surtout que lorsque je fais l'appairage de ma télécommande IKEA avec ampoule IKEA alors les 2 équipements sortent du réseau. Du coup, si je veux par exemple "allumer la lampe" avec un autre événement comme un capteur d'ouverture de porte je n'y arrive plus comme l'équipement n'est plus là...

Ok la on diverge.
Je n'ai pas joué encore avec telecommande Ikéa & actionneur mais pour moi appairer les 2 ne devrait pas empecher d'avoir AUSSI Jeedom dans le meme reseau. Auquel cas Jeedom pourrait recuperer le status de l'ampoule et aussi lui donne des ordres (comme si c etait une autre telecommande).

Mes volets profalux ont leur telecommande appairée (la remote controle le volet en direct) mais les 2 sont aussi dans le meme reseau que Jeedom donc ce dernier peut aussi commander les volets.

Bref je comprends ton idée mais je reste sur ma position.. on ne commande pas une telecommande pour qu'elle renvoi un ordre,  on envoi l'ordre directement au destinataire (jeedom = telecommande annexe).
Je vais jouer avec ma prise ikea + telecommande et je reviendrai vers toi.

**Comment by ChrisChrisChri** [comment]
Ok merci donc si je suis ton raisonnement. Je serai obligé d'acheter une télécommande de la marque pour l'appairer directement à l'équipement. JEEDOM étant là pour être une "commande supplémentaire automatisée" en fonction d'une horloge et/ou événement particulier.

Pour le moment avec mon aqara, je pilote du legrand et ikea en un seul clic et je trouvais cela très confortable mais étant limité à 3 clic sur cette télécommande, c'est pour cette raison que je voulais tester le TUYA car j'avais 3 clics X 4 boutons sur une seule télécommande. Je pouvais alors piloter plusieurs scenari avec une seule télécommande.

**Comment by ChrisChrisChri** [comment]
Est-ce que je pourrai t'envoyer un mail en MP ?

**Comment by tcharp38** [comment]
Ha je comprends autre chose que je n'avais pas pigé:
- tu utilises une telecommande quelconque
- dont le destinataire est Jeedom
- puis tu controles tes equipements qui peuvent etre d'une autre marque

Ca n'est pas un souci et c est possible... tant que la telecommande elle meme offre assez de "services" pour que Jeedom (Abeille) les recupere et puisse en faire qqch.

**Comment by tcharp38** [comment]
> Est-ce que je pourrai t'envoyer un mail en MP ?

Yeap.
fabrice.charpentier@laposte.net

**Comment by ChrisChrisChri** [comment]
[AbeilleLogs-210521.tar.gz](https://github.com/KiwiHC16/Abeille/files/6524623/AbeilleLogs-210521.tar.gz)
Salut, 
Voici le le fichier ;-)

**Comment by tcharp38** [comment]
@ChrisChrisChri 
Ne melangeons pas les sujets.
Le support de la prise Niko continue la #2003

**Comment by tcharp38** [comment]
@ChrisChrisChri 
On fait quoi de ce sujet ?
Tu as compris que les telecommandes n'offraient pas toutes les memes possibilites et du coup pas moyen de "normaliser" ca.
Certaines meme sont inutilisables de Jeedom car sont liées à l'appareil (ex: telec profalux pas Zoe).

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Oui j'ai bien compris. On peut clôturer alors. J'ai justement reçu hier la double télécommande de chez Aqara et elle permet de faire le job. Ca reste toujours un peu nébuleux pour moi de ne pas comprendre pourquoi ça ne peut pas être la même chose avec les autres télécommandes mais comme j'ai une solution via cette marque, je vais l'utiliser. Voici ce que cela donne au niveau de JEEDOM:

![image](https://user-images.githubusercontent.com/82177848/119955953-dd18e180-bfa0-11eb-96ae-ba7afeb47a4f.png)

Un clic sur le bouton de gauche donne état1 = 1 et un double click sur celui de droite = etat2 = 2.

J'aimais bien le principe de Tuya car c'était 4 boutons donc un peu plus de possibilités mais peut-être que Aqara en sortira un un jour. 

Encore merci pour ta recherche. Un

**Comment by tcharp38** [comment]
Ok cote "normalisation" on peut rien faire.

Mais juste sur le sujet telecommande "Tuya", la j'ai pas d'infos.
Cette telecommande est reconnue avec la bonne icone ?
Quel est la ref du modele ?

**Comment by tcharp38** [comment]
Ok donc l'icone est une abeille avec un point d'interrogation.

J'ai besoin des logs suite à une inclusion.
Tu peux retenter et me deposer le package ici ?
J'en profite pour changer le titre du sujet

**Comment by ChrisChrisChri** [comment]
Voici: Eq= Abeille1-163 tuya
[AbeilleLogs-210528.tar.gz](https://github.com/KiwiHC16/Abeille/files/6560186/AbeilleLogs-210528.tar.gz)

**Comment by tcharp38** [comment]
@ChrisChrisChri 
Quelle est la marque de ta remote ? Elle est vendu sous des tas de modeles on dirait.
D'autre part je te laisse trouver une image PNG de cet equipement.

**Comment by ChrisChrisChri** [comment]
Tuya comme dans le lien.
Voici une photo:
![image](https://user-images.githubusercontent.com/82177848/119973517-dd6ea800-bfb3-11eb-92f9-22c1952d2c41.png)

**Comment by tcharp38** [comment]
Tiens, tres preliminaire. J'avoue que je ne comprends pas comment on differencie les 4 boutons sachant qu'il dit n'avoir qu'un seul "end point".

A decompresser dans "core/config/devices"
[TS004F__TZ3000_xabckq1v.zip](https://github.com/KiwiHC16/Abeille/files/6560427/TS004F__TZ3000_xabckq1v.zip)

Redemarre les demons
Detruit ton EQ
Relance une inclusion

Si jamais ca va jusque la je veux bien le log parser pour voir les actions des boutons donc tu joues avec les boutons et tu me files le log. Merci

**Comment by tcharp38** [comment]
C est un fichier JSON qui est dedans.
Au final tu dois avoir
core/config/devices/TS004F__TZ3000_xabckq1v/TS004F__TZ3000_xabckq1v.json

Tu peux utiliser le plugin JeeXplorer pour ca.

Ha oui il te manque une info, le core du plugin Abeille bien sur.

![image](https://user-images.githubusercontent.com/35221038/119976486-705d1180-bfb7-11eb-8e4e-d989c8b8bd80.png)

**Comment by ChrisChrisChri** [comment]
Salut,
J'ai fait les différentes démarches. 
![image](https://user-images.githubusercontent.com/82177848/120064083-db1b5500-c06a-11eb-9243-d27853dc6a64.png)

[AbeilleLogs-210529.tar.gz](https://github.com/KiwiHC16/Abeille/files/6564325/AbeilleLogs-210529.tar.gz)

Au moment de l'inclusion, j'ai vu qu'il allait chercher le modèle TS0004F par contre ça reste sur l'abeille avec le point d'interrogation. J'ai cliqué sur les différents boutons mais lorsque je regarde le TIME - TIME, il n'y a pas de mise à jour par rapport au dernier clic au niveau dutimer. J'imagine donc que la commande ne remonte rien au niveau de Jeedom ?

**Comment by tcharp38** [comment]
Ok le souci est que tu es toujours sur la stable.
Le modele JSON necesasire est le suivant:

[TS004F.zip](https://github.com/KiwiHC16/Abeille/files/6570313/TS004F.zip)
A decompresser comme "core/config/devices/TS004F/TS004F.json"

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Cela reste sur la petite abeille avec point d'interrogation.
![image](https://user-images.githubusercontent.com/82177848/120892268-bc3e3500-c60d-11eb-9c7e-60ee8a955fb0.png)

J'ai essayé à plusieurs reprises.

**Comment by ChrisChrisChri** [comment]
[AbeilleLogs-210605.tar.gz](https://github.com/KiwiHC16/Abeille/files/6602586/AbeilleLogs-210605.tar.gz)

**Comment by tcharp38** [comment]
Je réalise qu'il a 3 sujets identiques sur TS004F__TZ3000_xabckq1v.
Je clos celui la et on se retrouve sur https://github.com/KiwiHC16/Abeille/issues/2155#
