### ISSUE TITLE
Capteur de porte Xiaomi avec bouton impossible a inclure

### ISSUE THREAD

**Issue by biscwii** [KiwiHC16/Abeille#1992]
Salut ! 
Au moment de ma dernière commande de capteurs de porte Xiaomi, je me suis trompé et ai commandé un nouveau modèle (alors que j'étais très habitué à faire fonctionner dans Abeille un modèle plus ancien). Mais ceux là sont impossible à inclure dans Abeille. Du coup j'ai regardé dans la docs pour voir s'ils sont compatibles et j'ai l'impression qu'ils ne sont pas encore pris en compte.
J'ai tout testé : appui court, appui long... Rien n'y fait. Ou alors avez vous une solution?

![IMG_6738](https://user-images.githubusercontent.com/56394268/118271289-599bc280-b4c1-11eb-8ead-50193284cfe4.png)

Merci !

**Comment by tcharp38** [comment]
Salut
C'est ecrit "Bluetooth"... donc rien à voir avec "Zigbee".
Désolé. Sauf si zigbee est aussi supporté, c'est mort pour Abeille.

**Comment by tcharp38** [comment]
Ca arrive.
Tu dois pouvoir le retourner non ?

**Comment by biscwii** [comment]
Sur Aliexpress j'ai des doutes ^^

**Comment by tcharp38** [comment]
J'espere. Je ne me suis jamais posé la question pourtant je commande souvent sur ce site.
Bonne chance en tout cas.

Je clos le sujet.
