### ISSUE TITLE
Ajout Level Up(On/Off) et Level Down sur telecommande Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#200]
As per discussion https://github.com/KiwiHC16/Abeille/issues/195#issuecomment-372735073

**Comment by mickadam29** [comment]
Effectivement, un up/down pour "level" et à terme pour la température du blanc serait parfait. Cela représente finalement le fonctionnement de la télécommande réelle.

**Comment by KiwiHC16** [comment]
Ajouté au master.
Je clos le sujet.

**Comment by mickadam29** [comment]
Petite remarque. Pourrais-tu inverser les boutons pour que le up soit à droite et le down à gauche ? Plus logique pour ma part par rapport au slider qui à droite correspond au plus élevé (d'où le up à droite)
Idem pour le on/off -> Off à gauche et On à droite.
