### ISSUE TITLE
Support Niko connected socket outlet

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2003]
Support prise Niko

EPList=01/F2
ManufacturerName='NIKO NV', trimmed='NIKONV'
ModelIdentifier='Connected socket outlet', trimmed='Connectedsocketoutlet'

    InClusterCount=09
    InCluster=0000 - General: Basic
    InCluster=0003 - General: Identify
    InCluster=0004 - General: Groups
    InCluster=0005 - General: Scenes
    InCluster=0006 - General: On/Off
    InCluster=0702 - Smart Energy: Metering
    InCluster=0B04 - Legrand private
    InCluster=0B05 - Diagnostics (DIAGNOSTICS_CLUSTER)
    InCluster=FC00 - Cluster FC00 inconnu
    OutClusterCount=01
    OutCluster=0019 - General: OTA

**Comment by ChrisChrisChri** [comment]
Salut,
Oui je veux bien essayer.

**Comment by tcharp38** [comment]
Tu es passé sur la beta ou tu preferes attendre la stable ?

**Comment by ChrisChrisChri** [comment]
Je suis toujours sur la stable pour le moment. Si c'est plus facile pour toi je peux passer sur une autre version. Je n'ai pas encore fait beaucoup de chose donc m^me si je plante ma box, je recommencerai.

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Désolé pour mon silence. J'ai avancé sur pas mal de points dont l'assistant de decouverte Zigbee.
Peux tu
- cliquer sur ton equipement
- page avancé
- assistant EQ
- et faire en sorte de remplir chaque requete (passage au vert du bouton refresh correspondant)

Puis me fournir (drag & drop) le fichier "discovery.json"
Merci

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Pas de soucis. Je suis fort occupé sur d'autres choses aussi. 

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7159318/discovery.zip)
![image](https://user-images.githubusercontent.com/82177848/133206563-b9314f02-348d-4c4e-9095-f5baab285d14.png)
Tout est passé au vert sauf quelques éléments qui restent sur l'orange.

Encore merci.

**Comment by tcharp38** [comment]
Salut
Tu as tenté de reappuyer sur les boutons oranges ? Pour le cluster 0005 c 'est normal il y a un bug mais pour les autres c 'est etrange.

Je vais déja regarder le fichier.
Merci

**Comment by tcharp38** [comment]
[Connectedsocketoutlet_NIKONV.zip](https://github.com/KiwiHC16/Abeille/files/7160507/Connectedsocketoutlet_NIKONV.zip)
A decompresser dans core/config/devices
puis redemarrer Abeille
et refaire une inclusion
fais aussi un drag & drop du package de logs (page support/telecharger tout)

**Comment by ChrisChrisChri** [comment]
Tu es un chef :-)

![image](https://user-images.githubusercontent.com/82177848/133236467-8312602d-7730-49fc-88b4-c3cc07f2fc77.png)
[AbeilleLogs-210914.tar.gz](https://github.com/KiwiHC16/Abeille/files/7160822/AbeilleLogs-210914.tar.gz)

Ca marche. J'ai installé un chargeur de GSM et la consommation s'est directement affichée. La commande ON/OFF marche aussi.

Bravo !!

**Comment by tcharp38** [comment]
Ouah, il y a des soucis d'affichage. Tout ca ne devrait pas l'etre.
De + la conso qui s'affiche ne fait pas de sens non ? Si chargeur, ca doit etre plutot 13.4w et non pas 134W.
Et je ne vois pas de courant.
Cote total power j'ai un doute si c'est vraiment supporté.
Je vais jeter un oeil aux logs

**Comment by ChrisChrisChri** [comment]
C'est vrai que j'y pense maintenant 134 W pour un GSM, ce n'est plus une charge rapide mais une charge à la vitesse de la lumière ;-)

**Comment by tcharp38** [comment]
Bon je viens de faire une nouvelle beta, dispo demain via Jeedom, ou de suite si GitHub.
210914-BETA-1

On va repartir de la.
Donc apres mise à jour je veux bien une nouvelle inclusion, le package de logs et on refait le point.
Merci

**Comment by tcharp38** [comment]
Correction 210914-BETA-2

**Comment by ChrisChrisChri** [comment]
Salut, 
J'ai chargé la nouvelle version Abeille mais cela donne toujours un résultat incorrecte au niveau des valeurs.
Le ON/OFF marche sans problème.
![image](https://user-images.githubusercontent.com/82177848/133998138-fd7bfe3a-e0a9-4098-a89a-be80066bb232.png)

![image](https://user-images.githubusercontent.com/82177848/133998470-4fa4c8d4-bc95-462d-80e8-267d0b9eac11.png)



Première image = aspirateur branché
Deuxième image = prise en OFF

Merci d'avanc
[discovery (2).zip](https://github.com/KiwiHC16/Abeille/files/7195485/discovery.2.zip)
e

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Une question avant tout c'est toi qui a rendu toutes les commandes "visibles" sur le dashboard ou c'est un bug ?

**Comment by tcharp38** [comment]
[Connectedsocketoutlet_NIKONV.zip](https://github.com/KiwiHC16/Abeille/files/7196108/Connectedsocketoutlet_NIKONV.zip)
A tester
- decompresser dans core/config/devices/Connectedsocketoutlet_NIKONV
- redemarrer Abeille
- refaire inclusion

Je m'attends a ce que la tension RMSVoltage soit ok et ActivePower soit != 0.
Tu me dira

**Comment by ChrisChrisChri** [comment]
Salut,

Pour les commandes, c'est bien moi. J'affiche la totalité quand je teste et puis je nettoie par la suite.

Ici, pas de changement. Le ON/OFF marche toujours. Par contre rien du tout en valeur instantanée ou autre.

Voici le fichier.

Encore merci
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7204972/discovery.zip)

**Comment by tcharp38** [comment]
Aucun changement cote RMSVoltage ? Toujours faux ?
Peux tu me filer un package de logs ?

**Comment by ChrisChrisChri** [comment]
Salut,

En appuyant sur REPORTING. J'ai obtenu le résultat du test de hier soir. Les différentes données sont alors apparues. Je vois que le nombre de Kw au total n'est pas bon. Il doit y avoir un problème de virgule. 

Tu veux dire quoi par "package de logs" ?

Merci 

![image](https://user-images.githubusercontent.com/82177848/134396581-0196ae98-90f6-48fa-9d88-6d590eccca9e.png)

**Comment by tcharp38** [comment]
C'est quoi "REPORTING" ? Tu trouves ca ou ?

Quand je parle de package de logs c'est le pacakge que tu peux avoir via la page "support" puis "telecharger tout".

**Comment by ChrisChrisChri** [comment]
Salut, j'ai cliqué sur les boutons présents. Enfin je pense que c'est après cette action que le résultat est remonté. Je n'étais pas devant mon JEEDOM. C'est en revenant quelques heures plus tard que j'ai vu ces données.
![image](https://user-images.githubusercontent.com/82177848/134558578-a5f5e2b8-5825-496e-9488-98ebcac50b48.png)




Merc
[AbeilleLogs-210923.tar.gz](https://github.com/KiwiHC16/Abeille/files/7219805/AbeilleLogs-210923.tar.gz)
i.

**Comment by tcharp38** [comment]
Salut
Les 3 boutons/actions dont tu parles auraient dus etre appelées lors de l'inclusion pour configurer le reporting.

On va proceder par etapes car je me perds.
Le RMS voltage est toujours faux et je ne comprends pas pourquoi.

Peux tu trouver la commande RMSVoltage dans la DB et me copier son contenu ?
https://kiwihc16.github.io/AbeilleDoc/Debug.html#acces-a-la-base-de-donnees-jeedom

**Comment by ChrisChrisChri** [comment]
Salut,

Ca va sous cette forme ?

<html>
<body>


11037 | 184 | Abeille | 0B04-01-0505 | 14 | RMSVoltage | {"visibiltyTemplate":0,"minValue":"","maxValue":""} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | V | {"showStatsOnmobile":0,"showStatsOndashboard":0,"invertBinary":"0"} | 1 | null | [] |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11038 | 184 | Abeille | 0B04-01-0508 | 10 | RMSCurrent | {"visibiltyTemplate":1,"minValue":"","maxValue":""} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | mA | {"showStatsOnmobile":0,"showStatsOndashboard":0,"invertBinary":"0"} | 1 | null | [] |  
11039 | 184 | Abeille | 0B04-01-050B | 11 | ActivePower | {"calculValueOffset":"#value#*1\/10","historizeRound":"0","maxValue":"4000","minValue":"0","visibilityCategory":"All","visibiltyTemplate":1} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | W | {"showStatsOnmobile":0,"showStatsOndashboard":0,"invertBinary":"0"} | 1 | null | [] | POWER
11040 | 184 | Abeille | Set-RMSVoltageReporting | 17 | Set-RMSVoltageReporting | {"topic":"configureReporting","request":"ep=01&clustId=0B04&attrType=21&attrId=0505&minInterval=0000&maxInterval=0000","execAtCreation":"yes","Polling":"","PollingOnCmdChange":"","PollingOnCmdChangeDelay":"","RefreshData":"0"} | {"dashboard":"default","mobile":"default"} | 0 | action | other |   | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 1 | null | [] | null
11041 | 184 | Abeille | Set-RMSCurrentReporting | 20 | Set-RMSCurrentReporting | {"topic":"configureReporting","request":"ep=01&clustId=0B04&attrType=21&attrId=0508&minInterval=0000&maxInterval=0000","execAtCreation":"yes","Polling":"","PollingOnCmdChange":"","PollingOnCmdChangeDelay":"","RefreshData":"0"} | {"dashboard":"default","mobile":"default"} | 0 | action | other |   | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 1 | null | [] | null
11042 | 184 | Abeille | Set-ActivePowerReporting | 21 | Set-ActivePowerReporting | {"topic":"configureReporting","request":"ep=01&clustId=0B04&attrType=29&attrId=050B&minInterval=0000&maxInterval=0000","execAtCreation":"yes","Polling":"","PollingOnCmdChange":"","PollingOnCmdChangeDelay":"","RefreshData":"0"} | {"dashboard":"default","mobile":"default"} | 0 | action | other |   | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 1 | null | [] | null


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by tcharp38** [comment]
Oui  c'est bon.
Mais je note que la config RMS voltage n'est pas bonne. il manque la division par 10.
Tu devrais avoir comme pour Active Power un truc du style "calculValueOffset":"#value#*1/10"

Peux tu via la page EQ/avancé .. faire recharger JSON

puis reverifier la DB pour cette commande ?

**Comment by ChrisChrisChri** [comment]
<html>
<body>


11059 | 184 | Abeille | 0B04-01-0505 | 10 | RMSVoltage | {"calculValueOffset":"#value#*1\/10","visibiltyTemplate":0} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | V | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 0 | null | [] |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11060 | 184 | Abeille | 0B04-01-0508 | 11 | RMSCurrent | {"visibiltyTemplate":1} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | mA | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 1 | null | [] |  
11061 | 184 | Abeille | 0B04-01-050B | 12 | ActivePower | {"calculValueOffset":"#value#*1\/10","historizeRound":"0","maxValue":"4000","minValue":"0","visibilityCategory":"All","visibiltyTemplate":1} | {"dashboard":"core::badge","mobile":"core::badge"} | 0 | info | numeric | W | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 1 | null | [] | POWER
11062 | 184 | Abeille | Set-RMSVoltageReporting | 13 | Set-RMSVoltageReporting | {"topic":"configureReporting","request":"ep=01&clustId=0B04&attrType=21&attrId=0505&minInterval=0000&maxInterval=0000","execAtCreation":"yes"} | {"dashboard":"default","mobile":"default"} | 0 | action | other |   | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 0 | null | [] | null
11063 | 184 | Abeille | Set-RMSCurrentReporting | 14 | Set-RMSCurrentReporting | {"topic":"configureReporting","request":"ep=01&clustId=0B04&attrType=21&attrId=0508&minInterval=0000&maxInterval=0000","execAtCreation":"yes"} | {"dashboard":"default","mobile":"default"} | 0 | action | other |   | {"showStatsOnmobile":0,"showStatsOndashboard":0} | 0 | null | [] | null


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by ChrisChrisChri** [comment]
On voit le /10 maintenant. Je vais rebrancher un appareil à l'instant pour vérifier.

**Comment by tcharp38** [comment]
Ok c est mieux. J'attends ton retour et le status quand la prise est ON

**Comment by ChrisChrisChri** [comment]
J'ai un chargeur GSM branché depuis mon dernier post. Tout est à 0. Quand je laisse ma souris sur les indicateurs, je n'ai rien en date de collecte des infos sur toutes les positions.
![image](https://user-images.githubusercontent.com/82177848/134822647-96eb4550-6d4b-4a80-97f1-636750a69109.png)

**Comment by tcharp38** [comment]
Zut. Meme plus la tension ?!
Je vois que le dernier retour est à 22:01:59
Plus on avance moins il y a d'infos. Qqch m'echappe.

Peux tu activer la surveillance et me filer AbeilleMonitor demain ?

**Comment by ChrisChrisChri** [comment]
Non. 
C'est quoi cette surveillance ?

**Comment by tcharp38** [comment]
https://kiwihc16.github.io/AbeilleDoc/Developpement.html#le-moniteur

La doc n'est pas trop à jour mais en gros tu selectionnes ton equipement et tu cliques sur "surveiller".
Il va enregistrer tout ce qui va vers ou qui vient de cet equipement.

**Comment by ChrisChrisChri** [comment]
Ok. C'est parti. Je te tiens au jus...

**Comment by tcharp38** [comment]
Ok. Je viens de faire une petite update de la doc: c est dans le chapitre "debug" maintenant
https://kiwihc16.github.io/AbeilleDoc/Debug.html#le-moniteur

**Comment by ChrisChrisChri** [comment]
[AbeilleMonitor.log](https://github.com/KiwiHC16/Abeille/files/7235572/AbeilleMonitor.log)

Salut,
Voici la liste des LOG.
J'ai branché  un chargeur de GSM à 2 moments distincts. Vers 23h00 et 12h00. 
Merci.

**Comment by tcharp38** [comment]
Je vois des infos qui remontent tres souvent mais je ne vois pas le detail.
Tu es sur la stable ou la beta ?
File moi un package de logs STP à l occase.

**Comment by ChrisChrisChri** [comment]
La stable.
Voici
[AbeilleLogs-210927.tar.gz](https://github.com/KiwiHC16/Abeille/files/7237443/AbeilleLogs-210927.tar.gz)
Merci.

**Comment by tcharp38** [comment]
J'ai trouvé qqch mais du coup
- soit tu bascules sur la beta pour avoir le dernier code
- soit je te file un fichier à modifier pour tester avant la prochaine stable
Tu preferes quoi ?

**Comment by tcharp38** [comment]
Ok cas ou tu veuilles tester, ce fichier est à mettre dans core/class pour ecraser l'existant (à garder de cote)
puis redemarrer le demon Abeille
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/7238681/AbeilleParser.class.php.zip)

**Comment by ChrisChrisChri** [comment]
Salut,
Voilà c'est fait.
J'ai vu directement le changement.
![image](https://user-images.githubusercontent.com/82177848/135072569-64be8779-1397-4e06-a9bb-1f10108efafd.png)

Il reste le nombre total de kWt total power qui reste étrange mais tu touches au but ;-)

Tu veux que je remette la surveillance et que je poste ce soir ?

Encore merci.

**Comment by ChrisChrisChri** [comment]
Je précise que c'est un chargeur de GSM en charge pour le moment donc les données me semblent cohérentes

**Comment by tcharp38** [comment]
Ok, ca progresse. 
Je jettes un oeil au "total power".

Si je ne me gourre pas, la division n'est pas 10 mais 1000.
A tester
[Connectedsocketoutlet_NIKONV.zip](https://github.com/KiwiHC16/Abeille/files/7244397/Connectedsocketoutlet_NIKONV.zip)

- decompresser
- page EQ/Avancé => recharger JSON

**Comment by ChrisChrisChri** [comment]
Salut,
Voici la bonne image pour la prise connectée. Cela évitera un mécontentement des marques ;-)
![Niko](https://user-images.githubusercontent.com/82177848/135887987-b48da13e-4023-4615-a71a-77c4fb4ab37d.PNG)
A+

**Comment by ChrisChrisChri** [comment]
Je viens de charger ton fichier ZIP mais à première vue aucun changement. La division reste à /10. Autre chose la date de collecte pour le TOTAL POWER reste bloquée au 21/09. Je mets l'équipement sous surveillance et je poste un fichier complet demain ?

**Comment by tcharp38** [comment]
Salut.

- Déja bascule sur la nouvelle stable du jour.
- Ensuite mets ton image dans "images" sous le nom "node_Niko-ConnectedSocketOutlet.png"
- Decompresse le fichier suivant dans "core/config/devices/Connectedsocketoutlet_NIKONV"

[Connectedsocketoutlet_NIKONV.zip](https://github.com/KiwiHC16/Abeille/files/7285065/Connectedsocketoutlet_NIKONV.zip)

- Redemarre le demon
- page EQ/avancé recharger JSON
- tu dois maintenant avoir une nouvelle commande "Get-Total Power". Peux tu la tester et me filer un package de logs ?

Note que ton icone ne sera pas mise à jour automatiquement.

**Comment by ChrisChrisChri** [comment]
Salut,
C'est en ordre pour l'image.
J'ai décompressé et recharger le JSON mais je n'ai pas la focntion GET-TOTAL Power. J'ai également perdu les autres fonctions.

Voici ce que j'ai lorsque j'affiche toutes les commandes.

![image](https://user-images.githubusercontent.com/82177848/136024846-85dd98cc-a63a-4096-88be-626d48256a9d.png)

**Comment by tcharp38** [comment]
Tu me files les logs ?

**Comment by ChrisChrisChri** [comment]
A mon avis, je suis allé trop vite. en vérifiant à l'instant, la nouvelle commande était dispo et elle a corrigé la valeur de 15,9kWh. Je vais brancher un appareil dessus et voir l'évolution.

Il faut combien de temps entre le chargement du nouveau fichier JSON et l'apparition des commandes dans l'objet ? Il me semble avoir attendu 3 ou 4 minutes. 


![image](https://user-images.githubusercontent.com/82177848/136040424-226073eb-0065-4341-8287-6b72e1e831e6.png)

**Comment by tcharp38** [comment]
A vrai dire pas sur que ca se raffraichisse tout seul. Le mieux est F5 ou recharger la page pour etre sur.

**Comment by ChrisChrisChri** [comment]
Voici des logs.
Je viens de charger un GSM ensuite j'ai fait le refresh du Total Power. 0,0587. Il y a donc une différence de 0,0092. Cela me semble correcte si on prend une batterie de GSM qui doit tourner dans les 5000 mAh (Elle était chargée à 1/2). Ca te paraît bon aussi ?
[AbeilleLogs-211005.tar.gz](https://github.com/KiwiHC16/Abeille/files/7287356/AbeilleLogs-211005.tar.gz)

![image](https://user-images.githubusercontent.com/82177848/136059952-b74751ef-0a94-4117-9c19-99af40f7ad55.png)

**Comment by tcharp38** [comment]
Cote total power je suppose que si on considere qu' active power (23W) est ok, c'est coherent avec le temps d'allumage du chargeur ?

Sinon je vois dans le log que le report "RMS Voltage" est fait quasi toutes les 2ndes. Pas bon ca.
La raison est qu'il reporte sur une diff de 1 et comme la tension bouge souvent +- 0.1V le reporting est permanent.
Je vais travailler dessus. Inutile de charger le reseau pour ca.

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
J'ai du boulot pour toi.

Ca pour core/config/devices/Connectedsocketoutlet_NIKONV
[Connectedsocketoutlet_NIKONV.zip](https://github.com/KiwiHC16/Abeille/files/7390122/Connectedsocketoutlet_NIKONV.zip)

et ca pour core/class
[class.zip](https://github.com/KiwiHC16/Abeille/files/7390159/class.zip)

puis
- redemarrer Abeille
- reconfigurer la prise
- et me filer le package de logs au bout de qq mins.
J'espere voir beaucoup moins de reporting RMS voltage.
Merci

**Comment by ChrisChrisChri** [comment]
Salut,
J'ai appuyé sur configuration à 19h15
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7391698/AbeilleParser.zip)
.

**Comment by tcharp38** [comment]
Je vois effectivement la configuration, en partie, mais ca ne change rien. Toujours autant de report.

Faut que je reflechisse à ca et que je trouve un moyen de faire des tests sur un autre periph.

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Toujours utilisateur d'Abeille ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,

Oui oui mais en mode relax. Il y a encore eu quelques fois ou j'ai été obligé d'appairer la totalité des équipements. Les petites sondes et prises ça peut encore aller mais quand tu dois démonter tes interrupteurs pour aller chercher les modules LEGRAND, c'est un peu lourd.

**Comment by tcharp38** [comment]
Salut
J'imagine bien.
Pour moi etre obligé de réappairer est inacceptable. Heureusement sur zigate v1 avec dernier FW (3.23), c'est plutot stable.

Du coup du côté de ce sujet "niko" on fait quoi ?
J peux pas bosser dessus sans ton aide alors ... à toi de dire si tu as des choses à revoir sinon on clos.

**Comment by ChrisChrisChri** [comment]
Pour moi, on était bon sur ce dossier car je sais piloter la prise et mesurer. Encore merci.

**Comment by tcharp38** [comment]
Ok merci.
Je ferme. A réouvrir si soucis sur ce device.
