### ISSUE TITLE
Prise en charge du nouveau firmware:

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2005]
https://zigate.fr/2021/05/07/maj-firmware-zigate-version-3-1e/

**Comment by tcharp38** [comment]
3.1e en test. Pas de soucis jusque la.

**Comment by nlhomme** [comment]
Je l'ai depuis dimanche dernier et rien à signaler également (interrupteurs et lampes Ikea Tradfri, capteurs de température/humidité/pression et interrupteurs sans fil Aquara)

**Comment by tcharp38** [comment]
@nlhomme 
As tu fait des (re)inclusions ?

**Comment by nlhomme** [comment]
Des reinclusion oui, les devices se réannoncent normalement , Abeille se charge du reste, pas de régression constaté.

Des inclusions tout court non j'en ai pas fait

**Comment by tcharp38** [comment]
C est bon signe. Merci pour ce retour.

**Comment by tcharp38** [comment]
Accessible à tous dans la 210708-BETA-1

**Comment by tcharp38** [comment]
FW accessible à tous depuis la 210719-STABLE-1
