### ISSUE TITLE
Xiaomi Magic Cube Controller

### ISSUE THREAD

**Issue by shakalagoons** [KiwiHC16/Abeille#201]
Zigate en mode inclusion, appui long sur le bouton d'association du cube :

> AbeilleParser 2018-03-15 09:52:05[DEBUG];type: 004d (Device announce)(Processed->MQTT); Src Addr : 1bdc; IEEE : 00158d0001100Bac; MAC capa : 80
AbeilleParser 2018-03-15 09:52:05[DEBUG]Je ne demande pas a l equipement d annoncer son nom pour le creer dans Abeille si il n existe pas deja
AbeilleParser 2018-03-15 09:52:05[DEBUG] type: 8701 (Route Discovery Confirm)(Not Processed); Status : 00; Nwk Status : 00
AbeilleParser 2018-03-15 09:52:05[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 00; Src Addr : 1bdc; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0010; Data byte list : 6c756d692e73656e736f725f63756265
AbeilleParser 2018-03-15 09:52:05[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 00; Src Addr : 1bdc; End Point : 01; Cluster ID : 0000; Attr ID : 0001; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 03
AbeilleParser 2018-03-15 09:52:06[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 01; Src Addr : 1bdc; End Point : 01; Cluster ID : 0000; Attr ID : ff01; Attr Status : 00; Attr Data Type : 42; Attr Size : 002a; Data byte list : 0121950B0328130421a80105219700062401000000000A2100009721000098210000992100009a210300

L'objet créé en mode semi-automatique :

![image](https://user-images.githubusercontent.com/36044888/37453519-2ca691c4-2838-11e8-9d6f-e1f894300836.png)

Les commandes :

![image](https://user-images.githubusercontent.com/36044888/37453551-444b3bfe-2838-11e8-8548-330b2d9c05f0.png)

Une photo du cube :

![image](https://user-images.githubusercontent.com/36044888/37453460-02110368-2838-11e8-81eb-40743954cbc4.png)

**Comment by KiwiHC16** [comment]
Ok, je vais faire une premiere version de l objet.
Une fois créé, est que d'autres commandes apparaissent en manipulant le cube ?
Est ce que d'autre log Parser s'affichent ?
Est ce que des valeurs changent ?

**Comment by shakalagoons** [comment]
Salut,

Depuis tout à l'heure, de nouvelles commandes sont apparues :
![image](https://user-images.githubusercontent.com/36044888/37455426-5b28c062-283d-11e8-946e-c17dccc42999.png)
![image](https://user-images.githubusercontent.com/36044888/37455174-c5120764-283c-11e8-8a86-284f779e8996.png)

A priori la commande "0012-0055" change de valeur quand je manipule le cube :
- Elle passe à 0 quand je secoue le cube
- Elle passe à 3 quand je lance le cube en l'air et qu'il retombe
- Elle passe à 512 quand je tapote le cube deux fois sur la table
- Elle passe à 256 quand je fais glisser le cube sur la table

La commande "000c-ff05" change aussi de temps en temps, j'ai l'impression que c'est quand j'applique une rotation au cube à plat sur la table.

**Comment by shakalagoons** [comment]
J'essaye de te faire dans la journée une liste des choses qui apparaissent dans "AbeilleParser" en fonction des mouvements.

**Comment by KiwiHC16** [comment]
https://www.kzenjoy.net/2017/jeedom-et-le-xiaomi-mi-cube/

**Comment by shakalagoons** [comment]
**Secouer le cube (5 essais) :**
AbeilleParser 2018-03-15 14:28:22[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9a; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0000
AbeilleParser 2018-03-15 14:28:24[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9b; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0000
AbeilleParser 2018-03-15 14:28:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9c; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0000
AbeilleParser 2018-03-15 14:28:28[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9d; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0000
AbeilleParser 2018-03-15 14:28:31[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9e; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0000

**Chute libre (5 essais) :**
AbeilleParser 2018-03-15 14:32:00[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: bc; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0003
AbeilleParser 2018-03-15 14:32:04[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: bd; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0003
AbeilleParser 2018-03-15 14:32:06[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: be; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0003
AbeilleParser 2018-03-15 14:32:08[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: bf; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0003
AbeilleParser 2018-03-15 14:32:10[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c0; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0003

**Tapoter le cube sur la table (chaque ligne correspond à un essai) :**
AbeilleParser 2018-03-15 14:33:09[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c1; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0205
AbeilleParser 2018-03-15 14:33:20[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c2; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:33:25[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c3; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:33:34[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c4; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0202
AbeilleParser 2018-03-15 14:33:41[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c5; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0053
AbeilleParser 2018-03-15 14:33:45[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c6; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:33:48[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c7; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:33:53[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c8; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:33:57[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: c9; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 005a
AbeilleParser 2018-03-15 14:33:59[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: ca; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0202
AbeilleParser 2018-03-15 14:34:01[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: cb; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0202
AbeilleParser 2018-03-15 14:34:04[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: cc; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0202
AbeilleParser 2018-03-15 14:34:09[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: cd; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0053
AbeilleParser 2018-03-15 14:34:11[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: ce; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:34:18[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: cf; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0203
AbeilleParser 2018-03-15 14:34:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d0; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0201

**Rotation à droite d'environ 90°, cube à plat (5 essais) :**
AbeilleParser 2018-03-15 14:36:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d1; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:36:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d1; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : 41df47b0
AbeilleParser 2018-03-15 14:36:30[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d2; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:36:30[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d2; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : 42a5e666
AbeilleParser 2018-03-15 14:36:33[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d3; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:36:33[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d3; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : 429aa8f5
AbeilleParser 2018-03-15 14:36:36[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d4; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:36:36[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d4; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : 429e3332
AbeilleParser 2018-03-15 14:36:38[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d5; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:36:38[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d5; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : 423a0A3d

**Rotation à gauche d'environ 90°, cube à plat (5 essais) :**
AbeilleParser 2018-03-15 14:37:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d6; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:37:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d6; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : c275c28e
AbeilleParser 2018-03-15 14:37:29[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d7; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:37:29[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d7; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : c2a64291
AbeilleParser 2018-03-15 14:37:31[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d8; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:37:31[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d8; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : c29cd1eb
AbeilleParser 2018-03-15 14:37:32[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d9; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:37:32[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: d9; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : c2b05c28
AbeilleParser 2018-03-15 14:37:35[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: da; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : ff05; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 01f4
AbeilleParser 2018-03-15 14:37:35[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: da; Src Addr : 1bdc; End Point : 03; Cluster ID : 000C; Attr ID : 0055; Attr Status : 00; Attr Data Type : 39; Attr Size : 0004; Data byte list : c290d1eb


Je continue les essais.

**Comment by shakalagoons** [comment]
**Glissement à plat sur la table, face avec l'inscription "Mi" vers le haut (5 essais) :**
AbeilleParser 2018-03-15 14:27:33[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 95; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0105
AbeilleParser 2018-03-15 14:27:35[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 96; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0105
AbeilleParser 2018-03-15 14:27:36[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 97; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0105
AbeilleParser 2018-03-15 14:27:39[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 98; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0105
AbeilleParser 2018-03-15 14:27:41[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 99; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0105

**Glissement à plat sur la table, face avec l'inscription "Mi" vers le bas (5 essais) :**
AbeilleParser 2018-03-15 15:15:19[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 05; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0102
AbeilleParser 2018-03-15 15:15:21[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 06; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0102
AbeilleParser 2018-03-15 15:15:24[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 07; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0102
AbeilleParser 2018-03-15 15:15:26[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 08; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0102
AbeilleParser 2018-03-15 15:15:28[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 09; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0102

**Comment by shakalagoons** [comment]
**Face avec l'inscription "Mi" vers le haut, basculement à 90° vers la droite, puis retour (2 essais) :**
AbeilleParser 2018-03-15 15:19:40[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 18; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 006c
AbeilleParser 2018-03-15 15:19:43[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 19; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0065
AbeilleParser 2018-03-15 15:19:47[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 1a; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 006c
AbeilleParser 2018-03-15 15:19:50[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 1b; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0065

**Idem, mais vers la gauche :**
AbeilleParser 2018-03-15 15:20:56[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 1f; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0069
AbeilleParser 2018-03-15 15:20:58[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 20; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 004d
AbeilleParser 2018-03-15 15:21:01[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 21; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 0069
AbeilleParser 2018-03-15 15:21:03[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 22; Src Addr : 1bdc; End Point : 02; Cluster ID : 0012; Attr ID : 0055; Attr Status : 00; Attr Data Type : 21; Attr Size : 0002; Data byte list : 004d

**Comment by KiwiHC16** [comment]
J'ai ajouté le Cube Aqara.
Je clos ce sujet.

**Comment by KiwiHC16** [comment]
J ai ajouté une doc.
