### ISSUE TITLE
210520-BETA-4: Probleme de gestion des groupes & regressions

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2011]
A priori la 210520-BETA-4 a cassé des chose cotes gestion des groupes.

**Comment by tcharp38** [comment]
Je change le titre.
J'ai l'impression qu'il y a aussi des soucis avec la telecommande virtuelle.
Qqn confirme ?

**Comment by tcharp38** [comment]
Groups & virtual remote control regression fixes #2012
Corrections dans le master.

**Comment by tcharp38** [comment]
210526-BETA-1 dispo sur Git 
Demain sur le market Jeedom.

**Comment by Xav-74** [comment]
Hello @tcharp38,
Je confirme que tout est OK sur la beta ;).
On  peut clore cette issue.
Merci

**Comment by tcharp38** [comment]
Parfait merci.
