### ISSUE TITLE
Ajout Ampoule E27 Philips Hue LWA004

### ISSUE THREAD

**Issue by heikki27** [KiwiHC16/Abeille#2015]
Comme échangé, serait il possible d'ajouter l'ampoule LWA004?

Elle semble exister en beta mais les commandes ne se créent pas

Par avance merci

**Comment by tcharp38** [comment]
Salut @heikki27 
Assures toi d'etre en mode "debug"
relance une inclusion
et mets le package de logs (via la page support, telecharger tout).

Tu es sur la beta du moment  ou sur la stable ?

Merci

**Comment by heikki27** [comment]
[AbeilleLogs-210602.tar.gz](https://github.com/KiwiHC16/Abeille/files/6586897/AbeilleLogs-210602.tar.gz)

@tcharp38 Je suis sur la dernière version du Master

**Comment by tcharp38** [comment]
@heikki27 
Je ne vois aucune annonce de ton ampoule dans le log.
Tu sais pourquoi ? Tu sais comment forcer l'ampoule à s'annoncer ?

**Comment by heikki27** [comment]
Dans Abeillediscover.log : 

***
*** New equipement discovery
***
Network: Abeille1
IEEE: 0017880106C36CD7
Manufacturer: 'Philips'
ModelId: 'LWA004'
Location: ''
MAC capa: 8E
8043/Simple descriptor response, SQN=52, Status=00, Addr=3961, Length=1A, EP=0B, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0101/Dimmable Light, BitField=01
- InClusterCount=08
- InCluster=0000 - General: Basic
- InCluster=0003 - General: Identify
- InCluster=0004 - General: Groups
- InCluster=0005 - General: Scenes
- InCluster=0006 - General: On/Off
- InCluster=0008 - General: Level Control
- InCluster=1000 - ZLL: Commissioning
- InCluster=FC02 - Cluster FC02 inconnu
- OutClusterCount=01
- OutCluster=0019 - General: OTA
8043/Simple descriptor response, SQN=53, Status=00, Addr=3961, Length=0A, EP=F2, ProfId=A1E0/Profil A1E0 inconnu, DevId=0061/Profil A1E0 inconnu, BitField=00
- InClusterCount=00
- OutClusterCount=01
- OutCluster=0021 - Cluster 0021 inconnu
- Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/0008/0009/000A/000B/4000/FFFD
- Clust 0003: 0000/FFFD
- Clust 1000: FFFD
- Clust 1000: FFFD
- Clust FC02: 
- Clust FC02:

**Comment by heikki27** [comment]
> Tu sais comment forcer l'ampoule à s'annoncer ?

Qu'est ce que tu entends par forcer l'ampoule à s'annoncer?

**Comment by heikki27** [comment]
[AbeilleParser-prev.log](https://github.com/KiwiHC16/Abeille/files/6589240/AbeilleParser-prev.log)

Regardes les logs vers 7h46

**Comment by tcharp38** [comment]
Ok bien vu.
Quelle est la ref fabricant de ce produit ?

**Comment by tcharp38** [comment]
Support dans le master.
Tiens moi au jus.
Tu peux relancer l'inclusion sans supprimer ton equipement par defaut.

Cote ampoule elle doit s'annoncer pour entrer sur le reseau mais je ne connais pas la procedure.
Il ne suffit pas d'appuyer sur "inclusion" dans Jeedom.

**Comment by heikki27** [comment]
Magnifique cela a fonctionné.
Un grand merci

**Comment by tcharp38** [comment]
Tant mieux.
Quelle est la ref Philips de ce produit ? J'imagine que ca n'est pas LWA004 non ?

**Comment by heikki27** [comment]
Philips Hue Ampoule LED Connectée White Filament E27 Forme Standard, Compatible Bluetooth 7 W

Single A60 Filament bulb A60 E27

**Comment by tcharp38** [comment]
L'icone correspond au produit ?
Si non je te laisse me trouver un PNG qui correspond mieux.
Merci

**Comment by heikki27** [comment]
![hue_e27_lw04](https://user-images.githubusercontent.com/83362467/120831947-6495c000-c560-11eb-90a7-ec1e3bf58783.png)

et voilà

**Comment by heikki27** [comment]
@tcharp38 encore merci.
Tu saurais m'aider pour un autre device qui est détecté en inconnu? je suis entrain de chercher si c'est simple à ajouter les commandes
