### ISSUE TITLE
intégration module ORVIBO CM10ZW

### ISSUE THREAD

**Issue by marcolabidouille91** [KiwiHC16/Abeille#2024]
Je souhaiterai intégrer le module relais de chez ORVIBO CM10ZW.
Comment faire?
Merci
Marc

**Comment by tcharp38** [comment]
Salut @marcolabidouille91 
L'integration d'un nouvel equipement est malheusement encore loin d'etre simple aujourd hui.

Mais tu peux
- t assurer que tu es en mode debug
- changer le nombre de lignes de logs à 5000 dans la config Jeedom
- Passer en mode inclusion
- et forcer ton module à entrer dans le reseau
- si il est deja integré en tant que "defaullt" et que tu es sur la stable, pense à le detuire avant
- puis mettre ici le package de logs (page support, telecharger tout).

**Comment by marcolabidouille91** [comment]
Salut tcharp38,
Voici les fichiers logs
J'espère avoir fait la bonne manip.
[AbeilleLogs-210609.tar.gz](https://github.com/KiwiHC16/Abeille/files/6621508/AbeilleLogs-210609.tar.gz)

**Comment by tcharp38** [comment]
Manufacturer: 'ORVIBO'
ModelId: '82c167c95ed746cdbd21d6817f72c593'
Location: ''
MAC capa: 8E
8043/Simple descriptor response, SQN=7B, Status=00, Addr=C43F, Length=12, EP=03, ProfId=0104/ZigBee Home Automation (ZHA), DevId=000B/Door Lock Controller, BitField=00
- InClusterCount=04
- InCluster=0000 - General: Basic
- InCluster=0005 - General: Scenes
- InCluster=0004 - General: Groups
- InCluster=0006 - General: On/Off
- OutClusterCount=01
- OutCluster=0000 - General: Basic
8043/Simple descriptor response, SQN=7C, Status=00, Addr=C43F, Length=12, EP=02, ProfId=0104/ZigBee Home Automation (ZHA), DevId=000B/Door Lock Controller, BitField=00
- InClusterCount=04
- InCluster=0000 - General: Basic
- InCluster=0005 - General: Scenes
- InCluster=0004 - General: Groups
- InCluster=0006 - General: On/Off
- OutClusterCount=01
- OutCluster=0000 - General: Basic
8043/Simple descriptor response, SQN=7D, Status=00, Addr=C43F, Length=12, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=000B/Door Lock Controller, BitField=00
- InClusterCount=04
- InCluster=0000 - General: Basic
- InCluster=0005 - General: Scenes
- InCluster=0004 - General: Groups
- InCluster=0006 - General: On/Off
- OutClusterCount=01
- OutCluster=0000 - General: Basic

**Comment by tcharp38** [comment]
A tester

pour core/config/devices
[82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip](https://github.com/KiwiHC16/Abeille/files/6623142/82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip)

et pour core/config/commands
[commands.zip](https://github.com/KiwiHC16/Abeille/files/6623153/commands.zip)

**Comment by tcharp38** [comment]
Support preliminaire 210612-BETA-1

**Comment by marcolabidouille91** [comment]
Voici l'image du relay, 
Merci ca fonctionne tres bien
![node_Orvibo_CM10ZW](https://user-images.githubusercontent.com/54357495/121857252-b6bfa980-ccf5-11eb-8500-0eef6b46dece.png)

**Comment by tcharp38** [comment]
Salut @marcolabidouille91 
Les 3 sorties fonctionnent ?

**Comment by marcolabidouille91** [comment]
Oui très bien 

Envoyé de mon iPhone

**Comment by tcharp38** [comment]
Parfait. Je viens de mettre à jour l'icone.
Sujet a cloturer quand c'est ok sur la prochaine stable.

**Comment by tcharp38** [comment]
@marcolabidouille91 
On cloture ?

**Comment by marcolabidouille91** [comment]
Je te dis ça dans la journée 

Envoyé de mon iPhone

**Comment by tcharp38** [comment]
@marcolabidouille91 
Alors ?

**Comment by marcolabidouille91** [comment]
Tu peux clore
Désolé je t avais oublié 
Marc

Envoyé de mon iPhone

**Comment by tcharp38** [comment]
Merci

**Comment by pinton40** [comment]
bonsoir,
je viens d'installer ce module les 3 relais fonctionnent correctement par contre il n'y a pas le retour d'état.
Est-il possible de l'avoir?
merci d'avance.

**Comment by tcharp38** [comment]
Ha oui effectivement. Le retour existe mais n'est pas affiché.

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices/82c167c95ed746cdbd21d6817f72c593_ORVIBO

[82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip](https://github.com/KiwiHC16/Abeille/files/9640351/82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip)

puis via la page EQ/avancé .. faire reinitialiser 

Dis moi ce qu'il en resulte.

**Comment by pinton40** [comment]
bonjour

les 3 relais et les 3 retours d'états fonctionnent parfaitement super travail.

**Comment by tcharp38** [comment]
Parfait.
Ca sera dans la prochaine beta.
Je clos.

**Comment by pinton40** [comment]
Bonjour
Depuis mon passage a la version beta  le retour d'etat des 3 contacts  su le module commutateur contact sec Zigbee
ORVIBO CM10ZW ne fonctionne plus.
[discovery-396483ce8b3f4e0d8e9d79079a35a420_ORVIBO.json](https://github.com/KiwiHC16/Abeille/files/13324746/discovery-396483ce8b3f4e0d8e9d79079a35a420_ORVIBO.json)
Merci d'avance

**Comment by tcharp38** [comment]
@pinton40 
Il s'agit toujours du meme module CM10ZW ou tu en as plusieurs ?
En effet je ne comprends pas l'historique de ce sujet qui semblait correspondre à un module avec une signature differente.

**Comment by pinton40** [comment]
Oui c'est toujours le même module et je n'en ai qu'un.

**Comment by tcharp38** [comment]
Ok, je seche vraiment la.
Aucun retour d'état ne fonctionne ?

Tiens, peux tu tenter avec ce modele ?
[82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip](https://github.com/KiwiHC16/Abeille/files/13325154/82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip)

nouvelle inclusion
test On 1 ou Off 1
package de logs

**Comment by pinton40** [comment]
Sur le module qui dispose de 3 relais aucun retour d'état
[AbeilleLogs-231111.tar.gz](https://github.com/KiwiHC16/Abeille/files/13325365/AbeilleLogs-231111.tar.gz)

**Comment by pinton40** [comment]
Je vais essayer de revenir sur la version stable car ça fonctionnait très bien

**Comment by tcharp38** [comment]
Tu as un backup de la stable?

**Comment by pinton40** [comment]
oui

**Comment by tcharp38** [comment]
Peux tu tester ca via la page EQ + avancé
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/50310ee6-677b-4d2d-901c-581ccb7d2acf)

et me filer le package de logs

**Comment by pinton40** [comment]
[AbeilleLogs-231111.tar.gz](https://github.com/KiwiHC16/Abeille/files/13325701/AbeilleLogs-231111.tar.gz)

**Comment by pinton40** [comment]
Je viens de me rendre compte que quand je fais la commande on est qu après je fais la commande Get-Status l'etat se met à jour.

**Comment by tcharp38** [comment]
Tout à fait normal. C'est le reporting automatique qui ne se fait pas

**Comment by pinton40** [comment]
ok, veux tu que je repasse en version stable ou j'attends?

**Comment by tcharp38** [comment]
Donc la reponse à la configuration semble correcte

    [2023-11-11 15:01:24] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=A7B2, DstAddrMode=02, DstAddr=0000
    [2023-11-11 15:01:24]   FCF=18/General/Serv->Cli, SQN=14, cmd=09/Read Reporting Configuration Response
    [2023-11-11 15:01:24]   Status=00/Success, Dir=00, AttrId=0000, AttrType=10, minInterval=0000, maxInterval=0000

Tu peux tenter encore un truc 

toujours via la page EQ/Avancé, l'idée est de supprimer cette config
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/415d1a2c-b53e-47c9-a7af-ff3f5036b478)

- puis tu refais une lecture de la config comme indiqué plus haut (Lecture configuration de reporting)
- tu testes le retour au cas ou
- et tu me files les logs
Merci à toi

**Comment by pinton40** [comment]
[AbeilleLogs-231112.tar.gz](https://github.com/KiwiHC16/Abeille/files/13327668/AbeilleLogs-231112.tar.gz)

**Comment by pinton40** [comment]
[AbeilleLogs-231112.tar.gz](https://github.com/KiwiHC16/Abeille/files/13327679/AbeilleLogs-231112.tar.gz)

**Comment by tcharp38** [comment]
As tu testé le bouton 1 ? je ne vois que le 3 mais celui la n'est pas modifié

**Comment by pinton40** [comment]
Je viens de le tester Et le retour d'etat  fonctionne sur le bouton 1

**Comment by pinton40** [comment]
[AbeilleLogs-231112.tar.gz](https://github.com/KiwiHC16/Abeille/files/13327778/AbeilleLogs-231112.tar.gz)

**Comment by tcharp38** [comment]
ok pigé donc.
Je te refais un modele + tard mais tu peux appliquer la meme chose "Ecriture config report" sur les EP 02 et 03
Et normalement tu devrais avoir les retours partout.

**Comment by pinton40** [comment]
Super je viens de le faire pour les 2 autres et ça fonctionne.

**Comment by tcharp38** [comment]
C'est donc confirmé.
Il faut supprimer le reporting de la configuration initiale.

Peux tu refaire une inclusion avec le modele suivant
[82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip](https://github.com/KiwiHC16/Abeille/files/13328640/82c167c95ed746cdbd21d6817f72c593_ORVIBO.zip)
ca sera dans la prochaine beta

**Comment by pinton40** [comment]
Ok super travail merci. Est ce que je peux appliquer la même méthode sur les ampoules IKEA Ampoule TRADFRI bulb E27 White Spectre opal 1000 lm Car j'ai le même problème.

**Comment by pinton40** [comment]
Je viens de remplacer le fichier et faire une nouvelle inclusion et ça fonctionne parfaitement.
Merci

**Comment by tcharp38** [comment]
Quel est le modele utilisé par ton ampoule ?
Voir page EQ/avancé

**Comment by pinton40** [comment]
TRADFRIbulbE27WW806lm J'ouvre un nouveau sujet?

**Comment by tcharp38** [comment]
Tiens, je te laisse refaire une inclusion avec ce modele et tester
[TRADFRIbulbE27WW806lm.zip](https://github.com/KiwiHC16/Abeille/files/13333205/TRADFRIbulbE27WW806lm.zip)

**Comment by pinton40** [comment]
Ca fonctionne ! Maintenant il me reste plus que le retour d'état de l'ampoule TRADFRIbulbE27WSopal1000lm et tout refonctionnera.

**Comment by tcharp38** [comment]
Je te laisse tester avec ca mais je ne comprends pas. Celui de la derniere beta devait deja etre au point
[TRADFRIbulbE27WSopal1000lm.zip](https://github.com/KiwiHC16/Abeille/files/13340783/TRADFRIbulbE27WSopal1000lm.zip)

**Comment by pinton40** [comment]
Merci ca fonctionne.

**Comment by tcharp38** [comment]
Ok donc on peut clore ce sujet ?

**Comment by pinton40** [comment]
oui on peut clore.
