### ISSUE TITLE
Création télécommandes virtuelles

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2025]
Hello,

Sur la version beta actuelle (210601-BETA-2) , il y a une régression sur les télécommandes virtuelles.
En effet, pas de souci lors de la création de la première télécommande, mais lors des suivantes, elles ne sont pas créées, juste une nouvelle annonce et une MAJ de la première.

Xav

**Comment by tcharp38** [comment]
Salut @Xav-74 
Je prefere finaliser malgre tout cette version en stable et lancer dans la foulée une nouvelle beta corrigée.
Il y a deja beaucoup trop d'evolutions depuis la derniere stable
mais je vois ton souci.
A suivre

**Comment by Xav-74** [comment]
Aucun souci ;)

**Comment by tcharp38** [comment]
Correction dans le master.

**Comment by Xav-74** [comment]
Hello,
A priori il doit rester une petite coquille car le bouton est inopérant !
Et aucune trace dans les logs

Edit : en regardant le code, je viens de voir que le `Virtual remote fix KiwiHC16#2025` n'était pas passé.
Je l'ai mis manuellement et c'est OK !

**Comment by Xav-74** [comment]
J'ai l'impression en effet. Ou alors, le second merge a écrasé le premier.

J'en profite également pour un bug d'affichage avec les tlc : 

![image](https://user-images.githubusercontent.com/56156622/121160445-61dee780-c84c-11eb-83d5-983e8e3618d9.png)

Comme tu peux le voir, en définissant le groupe dans les paramètres avancées des tlc virtuelles, elles apparaissent bien dans le tableau.
Par contre pour ma tlc Ikea (TRADFRI Variateur d'intensité) je dois le faire en renseignant le groupe (ici 0005) puis en cliquant sur le "Set Remote Group" : 

![image](https://user-images.githubusercontent.com/56156622/121160908-ca2dc900-c84c-11eb-8afc-eebc5971e844.png)

L'association se fait bien avec mes 2 prises mais la tlc n'apparait pas dans le tableau. C'est juste de la cosmétique ;)

Merci
Xav

**Comment by tcharp38** [comment]
Ca n'est pas une regression mais  un vieux souci n'est ce pas ?
La telecommande en question c'est celle la ?

>   "TRADFRIremotecontrol": {
>     "nameJeedom": "IKEA TRADFRI Rond 5 Boutons Remote Control",
>

**Comment by Xav-74** [comment]
Hello,

Non il s'agit de : 

> "TRADFRIonoffswitch": {
    "nameJeedom": "TRADFRI Variateur d'intensité",

Pour moi cela fonctionnait avant. En tous les cas, elle apparaissait bien dans le tableau ;)

Xav

**Comment by tcharp38** [comment]
Je vois pas comment c est possible. Son JSON n indique meme pas qu'il s agit d'une telecommande.
Tu n'as pas refait d'inclusion recemment n'est ce pas ?

**Comment by Xav-74** [comment]
on est OK que l'on parle pas de l'onglet paramètres avancés
mais bien du bouton `Set Remote Group` ?

Xav

**Comment by tcharp38** [comment]
Ben si. Tu me dis que ton "set remote group" fonctionne.
Mais dans l'onglet "avancé" elle n'apparait pas n'est ce pas ?

**Comment by Xav-74** [comment]
Pardon, je me suis mal exprimé ! Le `set remote group` fonctionne , c'est juste que la tlc n'apparait pas dans le tableau recap des groupes.
Regarde mon screen plus haut, la Tlc Salon (TRADFRIonoffswitch) avec le numéro de groupe 0005 n’apparaît pas.
Avant elle apparissait bien

**Comment by tcharp38** [comment]
Et cote page "avancé" il y a qqch qui apparait comme "telecommande" ?
En tout cas si tu souviens du "avant" je suis preneur. Je ne comprends pas comment elle pouvait etre affichée et de quand date ce changement.

**Comment by tcharp38** [comment]
https://www.zigbee2mqtt.io/devices/E1743.html

**Comment by tcharp38** [comment]
Bon jouvre un sujet specifique et je vais m'en acheter une. 
Sujet déplacé dans https://github.com/KiwiHC16/Abeille/issues/2029

Ici ca reste telecommande virtuelles.

**Comment by tcharp38** [comment]
@Xav-74 
Si la beta du jour 210609-BETA-1 est ok, on clos.

**Comment by tcharp38** [comment]
210610-STABLE-3
