### ISSUE TITLE
Erreur Installation des dépendances

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2026]
Hello,

Suite à une nouvelle installation propre du plugin (version ), il y a une erreur sur le lancement de l'installation des dépendances : 

```Aucun script ne correspond à votre type de Linux : /var/www/html/plugins/Abeille/core/class/../../resources/install_#stype#.sh /tmp/jeedom/Abeille/dependance avec #stype# : apt```

Matériel : Raspberry Pi4 - Buster 32bits uptodate.

Xav

**Comment by tcharp38** [comment]
Dans le master

**Comment by Xav-74** [comment]
Corrigé avec la master 210607-MASTER_TCHARP38-3 👍
