### ISSUE TITLE
Pb inclusion capteur Xiaomi v1

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2034]
Titre à preciser. Trop vague.
Lié a https://community.jeedom.com/t/soucis-dinclusion-ancien-et-nouveau-equipement-xiaomi/62282

**Comment by sebfar9172** [comment]
Bonjour
Je suis en dernière version stable de jeedom et de Abeille avec une zigate usb (en 031D).
Je galère à l’inclusion d’un thermomètre carré xiaomi existant et à l’ajout d’un nouveau. J’essai de redémarrer le démon et jeedom sans succès.
je suis passé en mode debug dans les logs.
Je met la zigate en mode inclusion, j'appuie que le bouton du thermomètre Xiaomi, je relache et il ne s'inclut jamais dans Abeille.
Je suis dispo pour fournir tous les logs nécessaires

**Comment by tcharp38** [comment]
Ok j'ai aussi ce type de capteur et je ne vois pas de soucis.
Peux tu
- dans le config jeedom etre sur que tu as 5000 lignes de log au lieu de 500
- redemarrer les demons si changement
- passer en mode inclusion
- pression > 10sec sur le bouton du capteur
- puis 1min + tard faire un drag & drop du package de logs ici (page support/ telecharger tout) 
Merci

**Comment by sebfar9172** [comment]
Voici
[AbeilleLogs-210609.tar.gz](https://github.com/KiwiHC16/Abeille/files/6622276/AbeilleLogs-210609.tar.gz)

**Comment by tcharp38** [comment]
Ok il manque du monde.
Le parser ne semble pas tourner. Idem pour SerialRead
Que donne la page santé ?
Tu devrais avoir les démons au vert comme suit
![image](https://user-images.githubusercontent.com/35221038/121321314-476d4280-c90e-11eb-8a5d-d9b19d243a63.png)

**Comment by sebfar9172** [comment]
C'est le cas ....

**Comment by tcharp38** [comment]
Donc je pense que ton mode de log n'est pas en mode 'debug'.
A changer + sauvergarde + redemarrer

**Comment by sebfar9172** [comment]
Oups désolé

voici

[AbeilleLogs-210609 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6622337/AbeilleLogs-210609.1.tar.gz)

**Comment by tcharp38** [comment]
[2021-06-09 10:38:50] Abeille1, Type=004d/Device announce, Addr=FF76, ExtAddr=00158D0006CA25E7, MACCapa=80, Rejoin=00
[2021-06-09 10:38:50]   EQ new to parser
[2021-06-09 10:38:50]   Requesting active end points list
[2021-06-09 10:38:51] Abeille1, Type=8000/Status, Status=00/Success, SQN=4D, PacketType=0045
[2021-06-09 10:38:51] Abeille1, Type=8000/Status, Status=00/Success, SQN=4E, PacketType=0045
[2021-06-09 10:38:57] Abeille1, Type=8011/APS data ACK, Status=A7, Addr=FF76, EP=00, ClustId=0005
[2021-06-09 10:38:57] Abeille1, Type=8011/APS data ACK, Status=A7, Addr=FF76, EP=00, ClustId=0005

mais aucune reponse du device.
Ca pue... 
A ce stade je ne vois pas comment Abeille peut sortir du petrin.

J'imagine que ce souci apparait avec n'importe quel equipement non ?
Si c est bien le cas, un RAZ de la zigate me semble etre la seule solution à tenter.

**Comment by sebfar9172** [comment]
oui j'ai essayé un détecteur de présence Xiaomi ... sinon cela fonctionne c'est juste les inclusions ... De temps en temps j'ai réussi à réinclure des capteurs existants ..

Pour la zigate tu parles d'une eraseprom et tout réinclure ?

**Comment by tcharp38** [comment]
malheureusement oui.
Le capteur que tu viens d'essayer de reinclure est à proximité ? Juste pour eliminer tout souci de transmission

**Comment by sebfar9172** [comment]
Oui je suis dans la même pièce .... Bon merci

**Comment by tcharp38** [comment]
Peut etre que tu peux sauvegarder ta zigate avant de tenter.
Du coup une sauvegarde Zigate + backup te permettrait de revenir en arriere.

On a eu ce type de souci avec Xav pour les volets qui ne voulaient plus se reinclure.
https://github.com/KiwiHC16/Abeille/issues/1994

**Comment by Xav-74** [comment]
Je confirme que c'est bien le même problème que moi. Le réseau fonctionnait bien mais je ne pouvais plus inclure quoi que ce soit. Un RAZ Eeprom de la Zigate (à faire 2 fois de suite) a corrigé le souci.
Après c'est du boulot de tout réinclure :( Heureusement pour moi, j'avais des virtuels pour chaque équipements du coup pas besoin de toucher à mes scénarios, Homebridge, design ou autre...

Petite question d'ailleurs : tu n'as pas remis à 0 ta Zigate depuis qd ? As-tu inclus/réinclus beaucoup de modules ? Tu as un compteur sur le plugin qd tu crées ou recrées les modules (0-xxx). Tu es à combien ?
C'est juste pour comparer avec moi et essayer de comprendre l'origine de ce souci ;) 

Xav

**Comment by sebfar9172** [comment]
Alors je n'ai pas accès à mon jeedom mais cela fait plus d'un an (même 2 ans) que je n'ai pas remis à 0 vu qu'avec les dernières versions firmware on n'était pas obligé de réinitialiser

**Comment by sebfar9172** [comment]
Je me demande si ce n'est pas lié au nombre d'équipements ...

**Comment by tcharp38** [comment]
Tout à fait possible ausssi. Ca fait malheuresement partie des points faibles de la zigate pour lesquels on n'a aucune réponse.
Donc table des eq corrompue ou zigate full.

**Comment by sebfar9172** [comment]
A-t-on moyen de le savoir pour la zigate full car quand je regarde la table des associations, j'ai pas mal d'équipement qui passent par les relais

**Comment by tcharp38** [comment]
Aucun :( J'ai déja posé la question à zigate, ils ne savent pas repondre.
Voir: https://github.com/fairecasoimeme/ZiGate/issues/344

**Comment by tcharp38** [comment]
Si l'un de vous peut fournir le package de logs lors d'une inclusion je regarde.
Mais ces capteurs fonctionnent tres bien chez moi, meme en reinclusion. Je viens de retester.

**Comment by mickadam29** [comment]
Je vais attendre les piles dans ce cas 
Merci

**Comment by sebfar9172** [comment]
Hello
donc j'ai réinitialisé  ma Zigate j'ai recommencé l'inclusion de tous les composants. Je n'arrive pas à intégrer les boutons ronds et les détecteurs de mouvement sans luminosité. J'ai les logs suivants.
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6653664/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6653665/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6653666/AbeilleCmd.log)

**Comment by mickadam29** [comment]
Salut 

Même avec une pile neuve, la com se perd. Je verrai pour déplacer mon capteur Xiaomi
En revanche l’inclusion s’est faite.

**Comment by tcharp38** [comment]
Ha donc le niveau de la pile a changé qqch ?

**Comment by tcharp38** [comment]
Salut @sebfar9172 
Je ne vois aucun souci dans tes logs mais ils sont bien trop courts (Max atteint (290 lignes))

- Mets 5000 lignes dans la config Jeedom
- relance une inclusion d'un de tes capteurs
- et drap & drop le package de la page support (telecharger tout)
Merci

**Comment by sebfar9172** [comment]
voici
[AbeilleLogs-210615.tar.gz](https://github.com/KiwiHC16/Abeille/files/6654648/AbeilleLogs-210615.tar.gz)

Là j'ai essayé d'inclure un capteur de mouvement sans détecteur de luminosité

**Comment by tcharp38** [comment]
Tes logs sont toujours aussi courts

> Max atteint (290 lignes)

Une fois la config modifiée et sauvée il faut redemarrer les démons Abeille pour que ce soit pris en compte.

Ceci etant je vois un device announce de ED3E

> [2021-06-15 11:54:40] Abeille1, Type=004d/Device announce, Addr=ED3E, ExtAddr=00158D000289F64F, MACCapa=80, Rejoin=00

> [2021-06-15 11:54:40] Abeille1, Type=8102/Attribut report, SQN=00, Addr=ED3E, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=0012
> [2021-06-15 11:54:40]   ModelIdentifier='lumi.sensor_motion', trimmed='sensor_motion'
> 

Meme si l'inclusion ne se termine pas ce device remonte des infos

> [2021-06-15 11:54:40] Abeille1, Type=8102/Attribut report, SQN=02, Addr=ED3E, EP=01, ClustId=0000, AttrId=FF02, AttrStatus=00, AttrDataType=42, AttrSize=0013
> [2021-06-15 11:54:40]   Xiaomi proprietary (IR/button/door V1)
> [2021-06-15 11:54:40]   Voltage=3025, Voltage%=67

En résumé pour l'instant je vois que le capteur est interrogé (si on parle bien du meme), mais il ne repond pas (pas de retour liste de end points par ex). Du coup la reinclusion n'est pas complete mais malgre tout il remonte des infos de batterie.

**Comment by sebfar9172** [comment]
J'ai fait une inclusion à 15:54 environ d'un capteur de mouvement (sans  détecteur de luminosité). il ne s'inclus pas. J'ai les logs à 500 après avoir redémarrer le démon.
[AbeilleLogs-210615 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6656135/AbeilleLogs-210615.1.tar.gz)

Je met aussi la page santé d'abeille
<img width="1055" alt="Capture d’écran 2021-06-15 155710" src="https://user-images.githubusercontent.com/52531214/122065633-65491480-cdf2-11eb-8061-09f55b05d70e.png">
<img width="1063" alt="Capture d’écran 2021-06-15 155658" src="https://user-images.githubusercontent.com/52531214/122065638-65e1ab00-cdf2-11eb-8768-28d1b054d248.png">

**Comment by tcharp38** [comment]
Est ce qu'il y a un autre equipement qui lui s inclut ?

D'autre part je note de multiples remontées de puissance de AE02/"Prise PC Bureau", plusieurs fois par seconde. Je me demande si ca ne fout pas la pagaille en saturant le reseau.

**Comment by sebfar9172** [comment]
en fait pour les équipements détecteur de  mouvement (je parle des V1, les V2 pas de soucis), celui qui n'ai pas dans Abeille ne s'inclus pas du tout et l'autre qui est présent il met à jour la date heure de connexion mais rien de plus il n'est pas fonctionnel ...

pour la Prise PC Bureau est-ce que je peux faire quelque chose pour cela ?

**Comment by tcharp38** [comment]
Comportement des Xiaomi v1 confirmé different des v2.
Je viens de creer la beta 210615-BETA-1 qui devrait corriger le tir.

**Comment by sebfar9172** [comment]
Merci pour ta version
Je l'ai installé et tenté l'inclusion mais cela n'apparait toujours pas
[AbeilleLogs-210616.tar.gz](https://github.com/KiwiHC16/Abeille/files/6660751/AbeilleLogs-210616.tar.gz)

**Comment by tcharp38** [comment]
Tu peux faire un nouvel essai avec ce code ?
Pour "core/class".
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6661108/AbeilleParser.class.php.zip)

Bien redemarrer les démons une fois que tu l'as installé.
Merci

**Comment by sebfar9172** [comment]
Pas mieux. J'ai juste mis en inclusion et appuyer 3 secondes... 
[AbeilleLogs-210616 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/6661226/AbeilleLogs-210616.2.tar.gz)

**Comment by tcharp38** [comment]
Bon pour moi l'inclusion est bonne.
Quel equipement déconne ?

**Comment by tcharp38** [comment]
Je vois que l'inclusion du DE60 se passe bien jusqu'au bout
mais le 89A1 ne repond pas
et si il ne repond pas c'est parce qu'il y a embouteillage :(

[2021-06-16 09:51:15] Abeille1, Type=004d/Device announce, Addr=89A1, ExtAddr=00158D000289F562, MACCapa=80, Rejoin=00
[2021-06-16 09:51:15]   EQ new to parser
[2021-06-16 09:51:15]   Xiaomi specific identification.
[2021-06-16 09:51:15]   Requesting modelIdentifier from EP 01

et pas de retour pour cette info.

Une nouvelle version du parser à essayer STP.
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6661852/AbeilleParser.class.php.zip)

**Comment by sebfar9172** [comment]
Même résultat...  La commande etat ne retourne rien
[AbeilleLogs-210616 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/6661872/AbeilleLogs-210616.3.tar.gz)

**Comment by tcharp38** [comment]
Nouveau code. J'ai trouvé un autre bug pour ce cas.
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6663963/AbeilleParser.class.php.zip)

Merci de tes tests que je ne peux pas faire moi meme.

**Comment by sebfar9172** [comment]
Cela fonctionne :) Bravo et merci

**Comment by tcharp38** [comment]
Ouf.
Je vais refaire une beta avec ces dernieres modifs du coup.
Merci d'avoir fait le cobaye.

**Comment by sebfar9172** [comment]
Pas de soucis cela m'arrange aussi

**Comment by tcharp38** [comment]
210616-BETA-1

**Comment by tcharp38** [comment]
@sebfar9172 
On cloture ?

**Comment by sebfar9172** [comment]
Fait merci pour ton aide tout est opérationnel
