### ISSUE TITLE
Défault d'installation des dépendance

### ISSUE THREAD

**Issue by nlhomme** [KiwiHC16/Abeille#2037]
Bonjour,

J'utilise la version 210607-STABLE-1 d'Abeille sur Raspbian Buster:
```
root@raspberrypi:~# cat /etc/debian_version 
10.9

root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
```

Contrairement aux version précédente, il semble que l'installation des dépendances soit impossible:
```
[2021-06-10 10:11:48][ERROR] : Aucun script ne correspond à votre type de Linux : /var/www/jeedom/plugins/Abeille/core/class/../../resources/install_#stype#.sh /tmp/jeedom/Abeille/dependance avec #stype# : apt
```

Ce n'est pas bloquant pour moi car j'ai déjà installé le plugin par le passé, mais j'ai voulu le faire pour être sûr d'être à la pointe.

Est-ce que j'ai raté quelque chose?

**Comment by tcharp38** [comment]
Bonjour

Pb connu et fixé sur la beta dispo des maintenant.
Désolé de cette regression.

Neanmoins Abeille semble pouvoir fonctionner malgre cette erreur.
https://github.com/KiwiHC16/Abeille/issues/2026

**Comment by nlhomme** [comment]
Pas de soucis, merci pour ta réactivité.
Je confirme que cela fonctionne malgré l'erreur.

Bonne journée

Edit: je laisse l'issue ouverte pour éviter l'ouverture d'autres issues identiques (sauf si tu penses que ce n'est pas utile)

**Comment by tcharp38** [comment]
Je viens de faire une nouvelle stable. Devrait etre sur le market demain.
Tu peux clore ce sujet une fois que tu as verifié sur la 210610-STABLE-3

**Comment by nlhomme** [comment]
Problème réglé en 210610-STABLE-3, merci encore pour ta réactivité
