### ISSUE TITLE
Bug PHP suite mise à jour dernière version Stable

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#2038]
Hello,

depuis la dernière mise à jour j'ai l'erreur suivante qui apparaît en boucle dans mes logs, et le démon socat qui est en rouge dans la page santé (mais tout semble fonctionner) :

```
thrown in /var/www/html/plugins/Abeille/core/php/AbeilleSocat.php on line 48
PHP Fatal error:  Uncaught Error: Class 'AbeilleTools' not found in /var/www/html/plugins/Abeille/core/php/AbeilleSocat.php:48
Stack trace:
#0 {main}
```

A dispo pour fournir des logs ou autre

**Comment by tcharp38** [comment]
Salut @graouxx 
Pb connu et corrigé dans la beta du moment.
https://github.com/KiwiHC16/Abeille/issues/2031

**Comment by graouxx** [comment]
Cool, merci @tcharp38, j'ai fait une recherche sur le message d'erreur dans l'historique et je n'ai pas vu qu'il y avait déjà un ticket.
