### ISSUE TITLE
Aqua detection sensor

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#204]
Hello,

   As I didn't find ticket about aqua detection sensor from issues with keywords aqua or inondation, I'm aking here:

    May I help to support aqua detection sensor of xiaomi?

Best regards

**Comment by KiwiHC16** [comment]
#119 & #198 
If you take the master, it should be included and work.
Let me know your experience and then we should be able to close this issue.

**Comment by handfreezer** [comment]
arf, should I have to update only one file, or should I have to remove the plugin from jeedom interface, and reinstall it from command line?

**Comment by KiwiHC16** [comment]
I can't answer specifically your question as I don't know the level of your system and as there are many changes every days, the only generic answer is: delete from plugin menu, then install it with git clone.

**Comment by handfreezer** [comment]
Ok.
Just to know: will i loose my confs and objects and history doing this?

**Comment by KiwiHC16** [comment]
Yes.
If you don't want to loose anything,  you can try git pull as per this page https://github.com/KiwiHC16/Abeille/blob/master/Documentation/020_Installation.asciidoc#depuis-github  

Please keep in mind that this is a beta SW and I don't spend(waste) time to work on update/upgrade procedure. So any sort of "production" is at risk when new SW is pushed.

**Comment by handfreezer** [comment]
OK, I understand that upgrade/updae procedure s not a priority as in development, but I don't understand the meaning of "when no SW is pushed" .

**Comment by KiwiHC16** [comment]
"when no SW is pushed" -> "when new SW is pushed" modified in previous message.

**Comment by KiwiHC16** [comment]
I'm closing the case.
