### ISSUE TITLE
Inclusion dans Zigate mais pas remontée dans Jeedom

### ISSUE THREAD

**Issue by biscwii** [KiwiHC16/Abeille#2041]
Salut,

Suite à une MAJ du Firmware de ma zigate, et une mauvaise manip, j'ai effacer l'EEPROM...
J'ai donc essayé de réinclure un par un tous mes équipements (principalement prises IKEA, et capteurs de porte Xiaomi) : les prise IKEA parviennent à se connecter à la zigate et remontent dans Jeedom (la mise à jour est effectuée toute seule). Par contre, les capteurs Xiaomi ne remontent pas automatiquement dans Jeedom; parfois en faisant un ListeEquipement, certains ont été mis à jour dans Jeedom, mais j'en ai un certain nombre qui n'apparaissent pas. Seule façon de voir que l'inclusion a en partie fonctionné est qu'ils apparaissent dans l'onglet Réseau d'Abeille avec un nom type "Abeille1/FA12" et un Objet "Inconnu".
Est il possible de forcer une synchronisation entre les équipement connus par la Zigate et Jeedom? (Vu que Jeedom connait les adresses IEEE, le lien devrait vite être fait, non?)

Merci d'avance

**Comment by tcharp38** [comment]
Salut
Je ne comprends pas tout mais on va se focaliser sur un capteur Xiaomi porte .
Il est reinclu mais ne remonte pas d'info ? C'est ca ?

**Comment by biscwii** [comment]
Mes explications ne sont effectivement pas très claires.
Au moment de l'inclusion, la led bleue du capteur clignote 3 fois, donc le capteur s'inclue dans la Zigate.
Lorsque je fais un refresh de l'onglet "Réseau", le capteur apparait bien avec pour nom "Abeille1/FA12" et pour objet "Inconnu".
Rien ne se met à jour automatiquement dans Jeedom (d'habitude une notification dis quelquechose comme "Nouvelle adresse pour le capteur "Porte d'entrée", on fait la mise à jour"), ce qui fait le lien entre le capteur inclu dans la Zigate, et l'objet Jeedom. 
Ici, pas de mise à jour de mon équipement Jeedom qui correspond à ce capteur, et je n'ai pas non plus de nouvel équipement créé dans Jeedom au nom AbeilleFA12...

**Comment by tcharp38** [comment]
Ok je suppose que tu es sur la derniere stable.
je vais refaire un test de mon cote.
Mais je veux bien tes logs 1 min apres inclusion (page support, telecharger tout). Assures toi d etre en mode debug et augmente les lignes des logs à 5000 au lieu de 500 (config Jeedom).

**Comment by tcharp38** [comment]
Bon aucun souci pour moi sur la stable 210610-STABLE-3

> L'équipement 'Abeille1-120' s'est réannoncé. Mise-à-jour en cours.

Si tu n'as pas eu le message "Nouvel equipement xxx" ou "xxx s'est réannoncé" alors l'inclusion n'est pas complete.
A voir dans les logs.
Attention, j'ai noté que la led du capteur clignote avant l'inclusion. Il s'agit peut etre du leave. Je crois qu'il est important de maintenir le bouton 10sec et pas moins pour initier une inclusion.

**Comment by biscwii** [comment]
Voici les logs,

Les équipements qui restent inconnus de Jeedom ont les adresses courtes : 
FA12
9005
F185
779C
AC1A
[AbeilleLogs-210612.tar.gz](https://github.com/KiwiHC16/Abeille/files/6642220/AbeilleLogs-210612.tar.gz)

**Comment by tcharp38** [comment]
Je vois 779C qui remonte qqch

> [2021-06-12 14:26:46] Abeille1, Type=8102/Attribut report, SQN=37, Addr=A549, EP=01, ClustId=0006, AttrId=0000, AttrStatus=00, AttrDataType=10, AttrSize=0001
> [2021-06-12 14:26:46]   OnOff=01
> 
> [2021-06-12 14:47:14] Abeille1, Type=8102/Attribut report, SQN=00, Addr=779C, EP=01, ClustId=0006, AttrId=0000, AttrStatus=00, AttrDataType=10, AttrSize=0001
> [2021-06-12 14:47:14]   OnOff=00
> 

Neanmoins je ne vois aucune phase d'inclusion. Ton log est trop court (500lignes)

> [2021-06-12 14:39:53] Max atteint (490 lignes) Log précédent sauvé sous '/tmp/jeedom/Abeille/AbeilleCmd-prev.log'

Tu sembles avoir modifié les options avancées et enlevé le "blocage recuperation equipement".
En ce qui me concerne je n'utilise jamais cette option, pas assez robuste, et generatrice de nombreux messages qui, actuellement peuvent ne pas etre correctement geres.

Bref, toujours en se focalisant sur un seul capteur porte, proche de la zigate:
- log a etendre à 5000
- mode inclusion
- 10sec sur bouton
- et recuperer le package de logs 1 min apres

**Comment by biscwii** [comment]
Salut ! Voici les logs !

Il y a plusieurs messages de ce type "L equipement Abeille1/XXXX n existe pas dans Jeedom, j'essaye d interroger l equipement pour le créer."
Je ne comprends vraiment pas pourquoi un équipement n'est pas créé dans Jeedom si un équipement est détecté par la zigate...

[AbeilleLogs-210615.tar.gz](https://github.com/KiwiHC16/Abeille/files/6656226/AbeilleLogs-210615.tar.gz)

**Comment by tcharp38** [comment]
Tu as surement touché les options avancées alors STP remets les par defaut. Les logs sont pourris par des requetes auxquelles je ne m'attends pas.

Ca devrait etre qqch comme suit
![image](https://user-images.githubusercontent.com/35221038/122069928-d938ec00-cdf5-11eb-8223-94fed42cd70f.png)

D'autre part tes logs sont toujours limités à 500 lignes. Trop court. Je suggere plutot 5000.

**Comment by biscwii** [comment]
Effectivement j'avais réglé 5000 dans le mauvais truc.
Le Blocage récupération équipement était sur Non, je l'ai remis sur Oui.
J'ai resté une inclusion et voici les logs. Après m'être assuré que l'équipement jeedom correspondant au capteur que je manipulais était bien activé, et avoir ensuite tenté l'inclusion, j'ai remarqué que l'équipement avait été désactivé.

[AbeilleLogs-210615.tar-2.gz](https://github.com/KiwiHC16/Abeille/files/6656851/AbeilleLogs-210615.tar-2.gz)

**Comment by tcharp38** [comment]
Question: les capteurs qui deconnent sont des Xiaomi v1 ?

**Comment by biscwii** [comment]
Ce sont ceux là 

![](https://projetsdiy.fr/data/uploads/2017/10/xiaomi-mi-smart-porte-fentre-capteur-intelligent-mijia-maison-bien-avec-1-1.jpg)

**Comment by tcharp38** [comment]
Bon c est peut etre du v1 ca alors la beta que je viens de pousser pourrait resoudre ton pb.
Dispo demain sur le market.

**Comment by tcharp38** [comment]
@biscwii 
As tu testé la derniere stable ?
Ca dit quoi ?

**Comment by biscwii** [comment]
Salut ! Je reviens de vacances ce week-end, je te tiens au courant après avoir testé ;)

**Comment by biscwii** [comment]
@tcharp38 
J'ai testé la dernière version, et c'est nickel, j'ai pu réinclure tous mes capteurs facilement. Ceux ci ont été remonté dans Jeedom automatiquement. Donc un GRAND MERCI à toi !

PS : Lorsque les capteurs se réannoncent (que ce soit les Xiaomi ou des prises et ampoules Ikéa), les commandes associées aux capteurs perdent leur Widget (qui me permettait d'afficher leur état avec une image que j'ai créée). Il m'a fallu les associer à nouveau. Je sais pas si c'est un problème connu...

**Comment by tcharp38** [comment]
Salut @biscwii 
Content de lire qu'il y a des trucs qui avancent.
Peux tu ouvrir un sujet sur ton dernier point et me donner qq exemples via des snapshots histoire que je comprenne ? Merci

Et si tu es d'accord on clot ce point ?

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si besoin
