### ISSUE TITLE
Ajout Aqara Opple 6 touches

### ISSUE THREAD

**Issue by heikki27** [KiwiHC16/Abeille#2048]
Je suis à la recherche des commandes pour un modèle non présent : Aqara Opple 6 touches.

IEEE: 04CF8CDF3C7D57E3
Manufacturer: 'LUMI'
ModelId: 'remote.b686opcn01'

Est ce que quelqu'un pourrait m'aiguiller pour créer les commandes dans le fichier JSON?

**Comment by tcharp38** [comment]
Salut
Tu n'as pas de fichier AbeilleDiscover.log qui a été generé ?

**Comment by heikki27** [comment]
*** New equipement discovery
***
Network: Abeille2
IEEE: 04CF8CDF3C7D57E3
Manufacturer: 'LUMI'
ModelId: 'remote.b686opcn01'
Location: ''
MAC capa: 84
8043/Simple descriptor response, SQN=F7, Status=00, Addr=0461, Length=16, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0105/Color Dimmer Switch, BitField=01
- InClusterCount=03
- InCluster=0000 - General: Basic
- InCluster=0003 - General: Identify
- InCluster=0001 - General: Power Config
- OutClusterCount=04
- OutCluster=0003 - General: Identify
- OutCluster=0006 - General: On/Off
- OutCluster=0008 - General: Level Control
- OutCluster=0300 - Lighting: Color Control
8043/Simple descriptor response, SQN=F8, Status=00, Addr=0461, Length=0E, EP=02, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0103/On/Off Light Switch, BitField=01
- InClusterCount=01
- InCluster=0003 - General: Identify
- OutClusterCount=02
- OutCluster=0006 - General: On/Off
- OutCluster=0003 - General: Identify

EP list = '01/02/03/04/05/06'

**Comment by heikki27** [comment]
De quelle façon arrives tu à déterminer les commandes à créer?

**Comment by tcharp38** [comment]
L'ideal avec une doc constructeur qui décrit ca.
Mais du coup dans la plupart des cas, la liste des EP & clusters supportes est la premiere chose.
Apres, il faut arriver à savoir quels sont les atttributs supportés par cluster.
Bizzarre d'ailleurs que je ne les vois pas dans ton "discover.log". 
Une fois que j'aurai compris de quoi il s'agit, on va extrapoler.

**Comment by tcharp38** [comment]
Peux tu
- me donner le modele (c'est bien WXCJKG13LM ?)
- relancer une inclusion
- drag & drop du package de logs (page support/telecharger tout)
- et trouver une belle image PNG du device
Merci

**Comment by tcharp38** [comment]
Regarde le discover.log
Pour l'ampoule OSRAM tu vois une liste du type

> - Clust 0300: 0000/0001/0002/0003/0004/0007/0008/0010/0011/0012/0013/0015/0016/0017/0019/001A/001B/0020/0021/0022/0024/0025/0026/0028/0029/002A
> - Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/0012/4000
> - Clust 0005: 0000/0001/0002/0003/0004
> - Clust 0300: 0000/0001/0002/0003/0004/0007/0008/0010/0011/0012/0013/0015/0016/0017/0019/001A/001B/0020/0021/0022/0024/0025/0026/0028/0029/002A

C'est la liste des attributs supportés par cluster. Donc les commandes a creer (pas toutes, seulement celles qui font du sens)
Je vois pas cette liste chez toi.

2 choses:
- log... toujours QUE 500 lignes
- et tu as certainement un fichier "remote.b686opcn01.json" incomplet. Du coup il le prend et arrete la decouverte. Ca doit expliquer pourquoi on ne voit pas les commandes. Supprime le pour l'interrogation. Je reconnais que c'est pas l'ideal mais pour l'instant c est comme ca

**Comment by heikki27** [comment]
[AbeilleLogs-210615(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6656663/AbeilleLogs-210615.1.tar.gz)

**Comment by heikki27** [comment]
@tcharp38 est ce que tu as une idée des commandes à créer pour le Opple?

**Comment by tcharp38** [comment]
Salut @heikki27 
Désolé pour mon silence. Trop de sujets en cours.
Mais j'avoue que le support des telecommandes est encore pas tres clair pour moi et je n'arrive pas à avoir des infos.

Note que tes logs sont toujours clampés a 500lignes et non pas 5000.
Tu peux voir ca par ex sur la premiere ligne du parser

> [2021-06-15 17:05:07] Max atteint (490 lignes) Log précédent sauvé sous '/tmp/jeedom/Abeille/AbeilleParser-prev.log'

**Comment by heikki27** [comment]
C'est modifié la taille du log.
Il a été identifié en remote.b686opcn01
Et il semblerait qu'un seul des 6 boutons ne fonctionne.

**Comment by tcharp38** [comment]
Les 6 boutons sont independants ?
Ou si tu appuis sur l'un, l'autre de la colonne se releve ?

**Comment by tcharp38** [comment]
[2048_Aqara-Opple-6buttons.zip](https://github.com/KiwiHC16/Abeille/files/6769712/2048_Aqara-Opple-6buttons.zip)

A tester.
Decompresser dans core/config mais attention
- remote.b686opcn01.json => devices/remote.b686opcn01/
- le reste dans "commands"

Redemarrer les démons
Refaire une inclusion
et drag & drop du package de log.

Je m'attends à ce que les boutons 1 et 2 donnent qqch, en supposant qu'ils sont independants.

**Comment by heikki27** [comment]
t'es un chef, je teste ça dans la soirée.

**Comment by tcharp38** [comment]
Salut @heikki27 
On en est ou la dessus ?

**Comment by heikki27** [comment]
Excuses moi j'étais en congés.
Les deux boutons fonctionnent correctement avec un seul état : 1 appui.
As tu une idée de comment gérer le double appui et l'appui long?

**Comment by tcharp38** [comment]
Salut @heikki27 
Désolé pour mon silence. Comme ce sujet n'est pas si trivial pour moi j essaie d avancer ceux pour lesquels j'ai une idée en premier. 
Bref, appui long/double appui je crois avoir compris qu'il fallait changer la config pas defaut mais je n'ai pas assez d'infos pour ca jusque la.

J'ai mis à jour le JSON pour les boutons suivants:

[commands.zip](https://github.com/KiwiHC16/Abeille/files/6974529/commands.zip)
Les commandes à decompresser dans "core/config/commands"

[remote.b686opcn01.json.zip](https://github.com/KiwiHC16/Abeille/files/6974535/remote.b686opcn01.json.zip)
Le JSON dans "core/config/devices/remote.b686opcn01/"

Puis redemarrer Abeille et refaire une inclusion.

**Comment by tcharp38** [comment]
Salut @heikki27 
Des news ?

**Comment by heikki27** [comment]
hello,
l'appareil s'est correctement ajouté.
par contre je bloque sur la gestion des boutons. seul un fonctionne et il allume ou éteint tout ce qui fonctionne en interrupteur.

**Comment by Sdavid66** [comment]
Hello, je viens d'acheter ce bouton et mis à part le online, rien ne remonte. Je te place les logs mais il n'y a pas grand chose. 

je n'ai pas l'impression que les clicks sur les 6 boutons fasse quelque chose. Je suis en version beta (dernière en date).

**Comment by tcharp38** [comment]
Salut @Sdavid66 
C'est bien qu'il y ai un 2nd testeur.
Tes logs sont vides. Es tu bien mode debug ? De plus assure toi pour la suite d'avoir au moins 5000lignes de log au lieu de 500.

**Comment by Sdavid66** [comment]
> Salut @Sdavid66 
> 
> C'est bien qu'il y ai un 2nd testeur.
> 
> Tes logs sont vides. Es tu bien mode debug ? De plus assure toi pour la suite d'avoir au moins 5000lignes de log au lieu de 500.

Oui bien laisse en debug et 5000. 
Je me suis étonné également du peux de logs. Vais voir ce soir directement sur la Zigate pour voir si des trames passent.

**Comment by Sdavid66** [comment]
Hello, nouveaux fichiers de logs.
Battery ne fonctionne pas.
Les 6 status ne donnent rien. 
A+

[AbeilleLogs-210925.tar.gz](https://github.com/KiwiHC16/Abeille/files/7229425/AbeilleLogs-210925.tar.gz)

**Comment by tcharp38** [comment]
Tu pourrais tenter de me generer un "discovery.json" ?
https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

**Comment by Sdavid66** [comment]
Hello, la recherche ne donne rien. 

Je suis allé du coté du mode "console" de ma Zigate. 

Ce que je vois passer c'est des infos pour la première action lorsque je clique sur le bouton en haut à gauche
et la seconde action qui est sur la même ligne à droite.

Pour reste des lignes (4 boutons), rien ne passe dans la Zigate.

Voilà je pense que c'est mort pour cet objet. 

A toute fin utile, je te place les datas de la Zigate.

Bien à toi
[datas_zigate.txt](https://github.com/KiwiHC16/Abeille/files/7232281/datas_zigate.txt)
.

**Comment by tcharp38** [comment]
C 'est quoi le mode console de ta zigate ? Tu as une version Wifi peut etre ?

Mais pas de panique. Je realise que comme c'est un Xiaomi peut etre que ma decouverte Zigbee ne peut pas fonctionner.

**Comment by tcharp38** [comment]
Je viens de faire une update de l'assistant dans laquelle j'ai ajouté l'interrogation forcée du EP01.

![image](https://user-images.githubusercontent.com/35221038/134881469-c04c8707-a7d5-4c24-a9cc-59505dd7a932.png)

Beta 210927-BETA-1

Tu peux tenter ca ?

**Comment by Sdavid66** [comment]
Hello, je vais tenter de refaire la détection.

Par contre: 

J'ai fait le test depuis une console qui se trouve sur une clef Zigate : Zigbee.

C'est cette passerelle qui fourni à Jeedom en Wifi les informations.

Depuis cette console, je ne vois pas passer les trames pour les autres boutons. C'est pour cela que je pense que c'est mort pour ce périphérique. 

Je te tiens au courant après mise à jour de la bêta. 

A +

**Comment by Sdavid66** [comment]
Voici des snapshots car le bouton "Télécharger" n'a aucun effet sur Chrome apparemment.

Ce n'est pas terrible à mon avis. J'ai tout testé.

A+
<img width="617" alt="Capture d’écran 2021-09-27 à 21 47 16" src="https://user-images.githubusercontent.com/90246385/134975344-c9d86649-90e4-425e-b845-4705f8d76619.png">


<img width="625" alt="Capture d’écran 2021-09-27 à 21 46 57" src="https://user-images.githubusercontent.com/90246385/134975303-9a0f0de4-59eb-401a-b3b4-883d64371299.png">

**Comment by tcharp38** [comment]
Ha mais donc il a repondu.
Et tu n'es pas sur la version beta car je ne vois qu'un seul bouton refresh cote "End Points".

En cliquant sur les boutons oranges rien ne fait ?
N'oublie pas qu'un equipement sur batterie doit etre reveillé chaque fois qu'on lui envoi une requete donc la tu dois cliquer sur un des boutons au fur et à mesure pour avoir tous les retours.

Ceci etant j'ai l'impression qu'il ne reporte que la tension et pas le pourcentage. D ou surement le manque de reporting de battery.

**Comment by tcharp38** [comment]
[remote.b686opcn01.json.zip](https://github.com/KiwiHC16/Abeille/files/7239032/remote.b686opcn01.json.zip)

A tester
decompresser, redemarrer demon, refaire inclusion
Ca devrait donner des infos de batterie

**Comment by Sdavid66** [comment]
> Ha mais donc il a repondu.
> Et tu n'es pas sur la version beta car je ne vois qu'un seul bouton refresh cote "End Points".
> 
> En cliquant sur les boutons oranges rien ne fait ?
> N'oublie pas qu'un equipement sur batterie doit etre reveillé chaque fois qu'on lui envoi une requete donc la tu dois cliquer sur un des boutons au fur et à mesure pour avoir tous les retours.
> 
> Ceci etant j'ai l'impression qu'il ne reporte que la tension et pas le pourcentage. D ou surement le manque de reporting de battery.
------------------------
Hello,

Je suis en beta, dernière mise  à jour faite tout à l'heure.

Je ne vois pas ton deuxième bouton -> la beta est: 210916-STABLE-1

Je vais réessayer et je dézippe ton fichier.

**Comment by tcharp38** [comment]
210916-STABLE-1 ca n'est pas la beta c est sur

**Comment by Sdavid66** [comment]
> 210916-STABLE-1 ca n'est pas la beta c est sur

Erreur de ma part, je suis allé dans le changelog... je suis bien en 210926-BETA-1

**Comment by Sdavid66** [comment]
> [remote.b686opcn01.json.zip](https://github.com/KiwiHC16/Abeille/files/7239032/remote.b686opcn01.json.zip)
> 
> A tester
> decompresser, redemarrer demon, refaire inclusion
> Ca devrait donner des infos de batterie

Il manque le fichier Json: battery-Volt2Percent-3.json'

**Comment by Sdavid66** [comment]
> > Ha mais donc il a repondu.
> > Et tu n'es pas sur la version beta car je ne vois qu'un seul bouton refresh cote "End Points".
> > En cliquant sur les boutons oranges rien ne fait ?
> > N'oublie pas qu'un equipement sur batterie doit etre reveillé chaque fois qu'on lui envoi une requete donc la tu dois cliquer sur un des boutons au fur et à mesure pour avoir tous les retours.
> > Ceci etant j'ai l'impression qu'il ne reporte que la tension et pas le pourcentage. D ou surement le manque de reporting de battery.
> 
> Hello,
> 
> Je suis en beta, dernière mise à jour faite tout à l'heure.
> 
> Je ne vois pas ton deuxième bouton -> la beta est: 210916-STABLE-1
> 
> Je vais réessayer et je dézippe ton fichier.

---- Voilà voilà .... :-)

J'ai beaucoup insisté afin d'avoir les boutons en vert mais sans succès pour certains.


<img width="612" alt="Capture d’écran 2021-09-27 à 22 28 58" src="https://user-images.githubusercontent.com/90246385/134980793-63c05367-c694-4935-91b7-151e4a44611e.png">



<img width="566" alt="Capture d’écran 2021-09-27 à 22 29 08" src="https://user-images.githubusercontent.com/90246385/134980757-8a1ba9ff-9591-40ad-b33b-9f4339e2498a.png">

**Comment by Sdavid66** [comment]
> C 'est quoi le mode console de ta zigate ? Tu as une version Wifi peut etre ?
> 
> Mais pas de panique. Je realise que comme c'est un Xiaomi peut etre que ma decouverte Zigbee ne peut pas fonctionner.

Ca ressemble à ça:

C'est la console des trames qui passent par la clef Zigbee. 

<img width="1146" alt="Capture d’écran 2021-09-27 à 22 34 27" src="https://user-images.githubusercontent.com/90246385/134981119-5ad6338b-2f44-4d3f-bb96-e19167678c32.png">

**Comment by tcharp38** [comment]
Merci pour l'info sur cette console. Comme je n'ai pas de Zigate Wifi je n'ai jamais vu ca mais ca peut etre utile pour le debug.
Il y a une beta 210927-BETA-1 qui devrait etre dispo pour toi aujourd hui.
Tu peux basculer dessus ?

**Comment by Sdavid66** [comment]
> Merci pour l'info sur cette console. Comme je n'ai pas de Zigate Wifi je n'ai jamais vu ca mais ca peut etre utile pour le debug. Il y a une beta 210927-BETA-1 qui devrait etre dispo pour toi aujourd hui. Tu peux basculer dessus ?

Hello, ce sont les mêmes résultats malheureusement. (je vois bien les deux boutons maintenant.). 

Comme je ne vois même pas passer les trames pour les 4 autres boutons dans la console de la Zigbee de Zigate, j'ai des doutes sur la suite.

--> J'ai acheté deux de ces boutons. Je vais tester tout à l'heure avec le deuxième pour voir si le premier a des soucis hardware. A+

**Comment by tcharp38** [comment]
Quand tu cliques tu telecharger (discovery.log), il se passe quoi ? Tu peux ouvrir une console de debug java (F12) et me copier le texte qui s affiche si jamais

**Comment by Sdavid66** [comment]
> Quand tu cliques tu telecharger (discovery.log), il se passe quoi ? Tu peux ouvrir une console de debug java (F12) et me copier le texte qui s affiche si jamais

--
<img width="547" alt="Capture d’écran 2021-09-28 à 15 01 27" src="https://user-images.githubusercontent.com/90246385/135091955-bd09b360-1aa6-4aee-bcc9-3a11a726e1fd.png">
>

**Comment by tcharp38** [comment]
ouah... "not allowed". Un cas de figure qui ne fonctionne pas chez toi.
Ton navigateur est Chrome ?
Je n'arrive pas à reproduire cette erreur :(
mais j'ai trouvé un article sur le sujet. Ca vient d'une mise à jour de securité recente de Chrome

https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome

**Comment by Sdavid66** [comment]
> ouah... "not allowed". Un cas de figure qui ne fonctionne pas chez toi.
> 
> Ton navigateur est Chrome ?
> 
> Je n'arrive pas à reproduire cette erreur :(
> 
> mais j'ai trouvé un article sur le sujet. Ca vient d'une mise à jour de securité recente de Chrome
> 
> 
> 
> https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome
> 
> 

Hello,

Oui Chrome sur MacBook et évidemment tenu à jour ;-). 

Il me semble que ça ne fonctionne pas non plus depuis Safari. Je tenterai à l'occasion.

Bonne fin de journée

**Comment by tcharp38** [comment]
Je résume:
- assistant: telecharger ne fonctionne pas mais comme je ne reproduis pas pour l instant je peux pas bosser dessus
- report de batterie: d apres ton discovery, seul le voltage est reporté donc le dernier JSON devrait remonter qqch
- pourquoi 1 seul end point listé ? A priori il y en a 6 d'apres certains commentaires sur le net

Que souhaites tu faire de cet inter ?
- qu'il renvoi des infos faire jeedom pour que ce dernier controle autre chose ?
- qu'il commande directement un groupe ?
- qu'il commande directement un device ?

**Comment by Sdavid66** [comment]
Hello, 

mes réponses aux différents points:

1. assistant: On attendra les prochains qui auront l'erreur ou mon test depuis Safari.
2. report de batterie: Je vais tester
3. 1 seul end point -> Je n'en sais rien.

Suite:

Qu'il renvoie des valeurs afin que je puisse les utiliser via des scenes dans Jeedom.

A+

**Comment by Sdavid66** [comment]
Ce bouton est en protocole Zigbee 3.0. Il n'est pas supporté par la Zigate + Zigbee ancienne génération. Pour l'instant je propose de mettre ce sujet en attente (en tout cas pour moi).

**Comment by tcharp38** [comment]
P.. je ne comprends pas.
Je viens d'installer la derniere version de Chrome chez moi

> Chrome est à jour
> Version 94.0.4606.61 (Build officiel) (64 bits)
> 

et aucun souci pour telecharger le discovery.json

**Comment by ChrisChrisChri** [comment]
Salut,
Comme discuté dans le sujet #2155, je reviens ici pour ma commande à 6 boutons.

Je commence par mettre le JSON de la commande à 2 boutons qui fonctionne très bien.
![image](https://user-images.githubusercontent.com/82177848/136424779-ab014ff7-a2fb-4f79-b334-055631c67cf2.png)

[discovery (1).zip](https://github.com/KiwiHC16/Abeille/files/7305388/discovery.1.zip)



Voici le JSON pour la commande à 6 boutons.
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7305416/discovery.zip)

Je n'arrive pas à avoir le résultat quand je passe par EQ/End point. J'ai bien cliqué sur la télécommande pour la réveiller mais rien  n'apparaît. Dois-je faire autrement ?

J'ai voulu la réintégrer et j'ai eu ce message de Abeille.
![image](https://user-images.githubusercontent.com/82177848/136426497-9460c6a2-c967-43df-a7bc-e7595b601c71.png)


Merci d'avance.

**Comment by Sdavid66** [comment]
Hello, pour aider les développeurs:

discovery

Même bouton. 
[discovery(aquara).json.zip](https://github.com/KiwiHC16/Abeille/files/7353282/discovery.aquara.json.zip)

@ChrisChrisChri  ton discovery est vide, je me suis permis de placer ici le mien (même bouton que toi)

**Comment by tcharp38** [comment]
Comportement par défaut

![image](https://user-images.githubusercontent.com/35221038/137581192-3a755408-e99c-469a-ad8c-96be98c80f14.png)

https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html

**Comment by tcharp38** [comment]
@Sdavid66 @ChrisChrisChri 
Qui peut me faire
- click haut gauche, notez l heure
- click haut droit, notez l heure
- me filer le log AbeilleParser

Il faudra faire la meme chose pour les autres mais on peut deja commencer par ca.
Merci

**Comment by ChrisChrisChri** [comment]
Salut,
1942 pour click gauche
1943 pour click droit
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7357974/AbeilleParser.zip)

**Comment by tcharp38** [comment]
Bouton 1

> [2021-10-16 19:42:02] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DestEP=01, SrcAddrMode=02, SrcAddr=F010, DestAddrMode=02, DestAddr=0000
> [2021-10-16 19:42:02]   FCF=11/Cluster-specific/Cli->Serv, SQN=FA, cmd=00/Off
> [2021-10-16 19:42:02]   Handled by decode8095
> [2021-10-16 19:42:02] Abeille1, Type=8095/OnOff update, SQN=FA, EP=01, ClustId=0006, AddrMode=02, Addr=F010, Status=00

Donc cmd info '01-0006-cmd00'

Bouton 2

> [2021-10-16 19:43:09] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DestEP=01, SrcAddrMode=02, SrcAddr=F010, DestAddrMode=02, DestAddr=0000
> [2021-10-16 19:43:09]   FCF=11/Cluster-specific/Cli->Serv, SQN=FB, cmd=01/On
> [2021-10-16 19:43:09]   Handled by decode8095
> [2021-10-16 19:43:09] Abeille1, Type=8095/OnOff update, SQN=FB, EP=01, ClustId=0006, AddrMode=02, Addr=F010, Status=01

Donc cmd info '01-0006-cmd01'

**Comment by tcharp38** [comment]
Tu peux faire la meme chose avec les boutons suivants 2 et 3 ?
Puis 4 et 5 ?
Merci

**Comment by ChrisChrisChri** [comment]
2011 pour le 2
2012 pour le 3
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7358015/AbeilleParser.zip)

**Comment by ChrisChrisChri** [comment]
2013 pour le 4
2014 pour le 6
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7358031/AbeilleParser.zip)

**Comment by tcharp38** [comment]
Je ne vois aucune remontée pour les boutons 2 à 6.
Du coup reinclure avec celui la
[remote.b686opcn01.json.zip](https://github.com/KiwiHC16/Abeille/files/7358089/remote.b686opcn01.json.zip)

et refaire 2, a 6 STP

**Comment by Sdavid66** [comment]
Hello,

Je viens de faire le test en version beta également chez moi.

Aucune trace dans les logs des bouton 3 à 6
1 et 2 ok avec une valeur à 1.
[AbeilleLogs-211017 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7360286/AbeilleLogs-211017.1.tar.gz)


Je pense définitivement que ce bouton est de la daubasse :-)

**Comment by tcharp38** [comment]
Je ne sais plus si les dernieres modifs sont dans la beta alors faut tester avec le JSON fourni.
En attendant, @Sdavid66, ton log est ultra court :) je ne vois que le click 1/off puis 2/on. Apres ca s arrete.

**Comment by Sdavid66** [comment]
> Je ne sais plus si les dernieres modifs sont dans la beta alors faut tester avec le JSON fourni.
> 
> En attendant, @Sdavid66, ton log est ultra court :) je ne vois que le click 1/off puis 2/on. Apres ca s arrete.

Oui j'ai utilisé le Json avant de tester.

Je ne vois aucune trace des 4 autres commandes. ... les logs sont vides. (On avait eu le même problème avec mon ancienne version de la Zigate.)

**Comment by ChrisChrisChri** [comment]
Salut,
Je ne sais pas si cela peut aider mais voici mon test.
2020 3
2021 4
2022 5
2023 6
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7367702/AbeilleParser.zip)

**Comment by tcharp38** [comment]
Merci @ChrisChrisChri 
mais nada. Aucun retour de l inter.
Faut que je creuse d'autres pistes.

**Comment by tcharp38** [comment]
Antique sujet sans vie depuis un moment.
Je ferme.
A réouvrir si nouvelle piste et si qqn est pret à faire des tests.
