### ISSUE TITLE
Les logs se génèrent sans tenir compte du paramétrage

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#2051]
BOnjour
Si je met "Aucun" dans le niveau de log d'Abeille, les logs se génèrent quand même...
C'est surtout embêtant pour le log "AbeillePHP.log" qui prend plusieurs Mo même si les erreurs ne viennent pas d'Abeille
[18-Jun-2021 12:03:45 Europe/Brussels] PHP Notice:  Undefined variable: CmdOK in /var/www/html/plugins/wifilightV2/core/class/wifilightV2.class.php on line 1281

**Comment by tcharp38** [comment]
Salut

AbeillePHP n'est généré qu'en mode developpeur, mode dans lequel tu n'es pas censé être.
Désactive le, redemarre les démons et vire ton log. Ca devrait etre bon

**Comment by sebfar9172** [comment]
Je suis sorti  du mode développeur, j'ai redémarré le démon abeille, j'ai supprimé les logs en mettant niveau Aucun  et il y a un log qui reste c'est AbeillePHP

**Comment by tcharp38** [comment]
Etrange.
Mais tu ne l'avais pas avant de jouer avec le mode dev. Donc ca doit fonctionner.
Qqch ne doit pas etre rafraichi.
Si ca te parle tu peux tenter un "sudo systemctl restart cron apache2"
ou redemarrer ta machine.

Ce log est un truc special, pas généré par Abeille ni Jeedom. On demande juste (en mode dev) à PHP de rediriger ses erreurs.

**Comment by sebfar9172** [comment]
C'est bon j'ai redémarré...
Merci j'utilise le mode développeur pour ajouter une commande info dans les équipements

**Comment by tcharp38** [comment]
Quel genre de commande ?

**Comment by sebfar9172** [comment]
Une commande binaire qui est mis à jour par un code php pour indiquer que la batterie est en dessous d'un certain seuil

**Comment by tcharp38** [comment]
Comment tu fais ca ?
Tu as un snapshot ?

**Comment by sebfar9172** [comment]
Tous les matins j'ai un scénario qui m'alerte des soucis de Batterie et qui met à jour l'info que j'ai ajouté dans chaque équipement Abeille et j'ai un composant Alarm qui a comme déclencheur cette commande info pour déclencher une alerte comme quoi je vais avoir un soucis de batterie

//Partie 1
$batterie = "Batterie"; // Nom de la commande à rechercher
//$excludeEq = array("[Domotique][Aspirateur]"); // Liste des équipements à ignorer (qui contiennent la commande "$batterie"), ceci est un exemple de syntaxe
$excludeEq = array("[Bureau][Roborock S5]" => 1,"[Appartement][Alerte Batterie]" => 1,"[Appartement][Alarme Batterie]" => 1, "[Appartement][Anémomètre]" => 1, "[Bibliotheque][Alarme Batterie]" => 1, "[Bureau][Alarme Batterie]" => 1, "[Chambre][Alarme Batterie]" => 1, "[Cuisine][Alarme Batterie]" => 1, "[Entree][Alarme Batterie]" => 1, "[Equipement][Florence]" => 1, "[Equipement][Sébastien]" => 1, "[Salledeau][Alarme Batterie]" => 1, "[Salledebain][Alarme Batterie]" => 1, "[Wc][Alarme Batterie]" => 1, "[Salon][Alarme Batterie]" => 1, "[Bureau][Dashboard Aspirateur]" => 1, "[Appartement][Alerte Réinitialisation alarme]" => 1 );
$msgA = ""; //Message a envoyer sur l'état des batteries en danger
$msgW = ""; //Message a envoyer sur l'état des batteries en warning

$errEqLogics = array();
$etatBatterie = array(); //Tableau d'information sur la batterie consultée
$cpt_ok=0;
$cpt_w=0;
$cpt_a=0;

$eqLogics = eqLogic::all();


foreach($eqLogics as $eqLogic)
{
   if ($excludeEq[$eqLogic->getHumanName()] == 1){
    continue;
  }
  
  try{
    //Partie 2
    if (isset($batterie))
    {
      	// si la commande n'existe pas, une exception est levée
    	$cmd = cmd::byString('#' . $eqLogic->getHumanName() . '['. $batterie .']#');
    }

    $allCmds = $eqLogic->getCmd();
    if (count($allCmds) > 0)
    {
      //Partie 3
      foreach($allCmds as $cmd)
      {  
        if (strpos($cmd->getHumanName(),$batterie) !== false)
        {
          $lenNom = ($lenNom < strlen($eqLogic->getName())) ? strlen($eqLogic->getName())+1 : $lenNom;
        }
      }

      //Partie 4
      foreach($allCmds as $cmd)
      {  
        if (strpos($cmd->getHumanName(),"[".$batterie."]") !== false)
        {
          $scenario->setLog("-- Equipement " . $cmd->getHumanName() . " traité");

          $cmd->execCmd();
          
          $nbspace=str_repeat(' ',($lenNom - strlen($eqLogic->getName())));
          $etatBatterie=$eqLogic->getStatus();
          $nom=$eqLogic->getName();
          
          $equipement="#".str_replace($batterie,"Alerte",$cmd->getHumanName())."#";
          
		  if($etatBatterie['batterydanger']==1)
          {
            $scenario->setLog("batterydanger");
            $msgA .= ":red_circle:".$eqLogic->getName() . $nbspace ."  - ". $etatBatterie['battery']." %\n";
            $cpt_a+=1;
            $cmd::byString($equipement)->event(1);
          	$scenario->setLog($equipement);
          }
          else if($etatBatterie['batterywarning']==1)
          { 
	        $cmd::byString($equipement)->event(0);
            $scenario->setLog("batterywarning");
            $msgW .= ":orange_circle:".$eqLogic->getName(). $nbspace ."  - ".$etatBatterie['battery']." %\n";
            $cpt_w+=1;
          }else
          {
           $cpt_ok+=1; 
           $cmd::byString($equipement)->event(0);
          }
        }
      }
    }
  }catch (Exception $e)
  {
    // pas de commande
  }
  
}

$tags['#messageA#'] = $msgA;
$tags['#messageW#'] = $msgW;
$tags['#cpt_ok#'] = $cpt_ok;
$tags['#cpt_w#'] = $cpt_w;
$tags['#cpt_a#'] = $cpt_a;
$scenario->setTags($tags);`

**Comment by tcharp38** [comment]
Interessant.
Du coup dans la partie Abeille/commandes tu ajoutes la commande "batterie" quand pas dispo ?
Tu as un exemple ou tu as du modifier la commande Abeille ?

**Comment by sebfar9172** [comment]
J'ajoute la commande Alerte (La commande Batterie est de base dans tous les équipements Abeille). 

<img width="1055" alt="Capture d’écran 2021-06-18 131455" src="https://user-images.githubusercontent.com/52531214/122552914-340d5600-d037-11eb-918c-0f02236cfb35.png">

**Comment by tcharp38** [comment]
Ok tu as ajouté "Alerte" mais ca  n'est pas Abeille qui la rempli n'est ce pas ?

**Comment by sebfar9172** [comment]
Non c'est le script que j'ai mis plus haut, il regarde le niveau de batterie de chaque équipement qui a une batterie (je n'ai pas que Abeille), si c'est  inférieure à 20 je met Alerte à 1 dans l'équipement concerné, ce qui va déclenché une alarme

**Comment by tcharp38** [comment]
Je vois.
Tu as utilisé une faille, l'acces au mode dev.

Cette page est la pour faire le lien entre les commande Jeedom et les commandes supportées par Abeille. 
Je crois que la methode "propre" serait d'avoir un virtuel qui prend en entrée ce que tu veux (donc les commandes "batterie" de chaque equipement), et en sorte qqch.

Enfin bon tant que ca fonctionne pour toi c'est bon mais attend toi un jour à ce que cette astuce ne marche plus.
Interessant en tout cas.

**Comment by sebfar9172** [comment]
il me semble que dans des versions précédentes d'Abeille j'avais accès à l'ajout d'une commande Info sans le mode dev ....
Oui mais cela m'évite pas mal de boulot de faire comme cela :)
Sinon je m'adapterai 👍 cela me challenge

**Comment by tcharp38** [comment]
Oui c etait une faille.
Mais tu comprends pourquoi ca n'a pas vraiment sa place ici ?
Ajouter une commande qui n'est pas gérée par Abeille... c'est ouvrir la porte à plein de pbs potentiels.

**Comment by sebfar9172** [comment]
En effet, après moi je m'adapte aux possibilités qu'offre le système. En plus cela n'impacte pas le fonctionnement car de façon générale cela fonctionne bien Abeille que j'utilise depuis des années.
Quand j'aurai un peu de temps je regarderai une solution qui ne touche pas aux objets créés par Abeille
