### ISSUE TITLE
Support Lidl Smart Home: Ampoule HG06106C (id = TS0505A, _TZ3000_dbou1ap4)

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2052]
pour @sebgsx01

**Comment by Kenderv** [comment]
Bonjour,
Lors de leur sortie j'avais acheté ces ampoules LIDL HG06106C et puis je les avais oubliées dans un tiroir. Hier j'ai essayé de les inclure avec Abeille. Elles sont reconnues comme : "Abeille | Nouvel équipement identifié (Silvercrest Ruban a LED). Création en cours. Rafraîchissez votre dashboard dans qq secondes.", mais aucune commande ne fonctionne.
Pouvons nous travailler ensemble sur cette ampoule ? Merci

**Comment by Kenderv** [comment]
Pour info, le discovery
[discovery.json (2).txt](https://github.com/KiwiHC16/Abeille/files/7490160/discovery.json.2.txt)

**Comment by tcharp38** [comment]
[TS0505A__TZ3000_dbou1ap4.zip](https://github.com/KiwiHC16/Abeille/files/7490782/TS0505A__TZ3000_dbou1ap4.zip)

A decompresser dans core/config/devices
Je te laisse tester et me trouver une image PNG sans fond pour cet equipement.

**Comment by Kenderv** [comment]
Cette image te convient-elle ?
![Sans titre-1](https://user-images.githubusercontent.com/52486183/140616711-b8211e25-b19a-40d0-a7d2-f474c3495279.png)

**Comment by Kenderv** [comment]
On avance, les commandes On, Off, Toggle fonctionne bien. Le status s'allume quand la commande on est lancée mais s'éteint quelques secondes après. Le setLevel fonctionne dans le sens o--> 100 mais si on le ramène à 0 le status s'allume puis s'éteint, l'apoule ne s'éteint pas, et le Level passe à zéro puis revient au niveau précédent après quelques secondes.
Il ne se passe rien lorsque je clique sur Blanc, Bleu, Rouge ou Vert.
![Abeille-514](https://user-images.githubusercontent.com/52486183/140617957-421e2157-97ee-4329-865e-fae6fe541a6d.JPG)
Enfin dans la config Abeille elle est toujours considérée comme un ruban Led même après avoir relancé le demon.
![Abeille-514-2](https://user-images.githubusercontent.com/52486183/140618304-5d4649dd-8814-4ee2-851e-be4c258943b6.JPG)
Demain (ou plus tard) sera un jour meilleur.
Bonne soirée à toi.

**Comment by tcharp38** [comment]
Je crois que le ColorMode par defaut (mired) n'est pas en ligne avec ce qu'on cherche à faire.
Il y a beaucoup de taf pour remettre les choses au propre cote couleurs. Faut que je me paie cette ampoule pour faire des essais.

**Comment by Kenderv** [comment]
Si je peux t'aider, n'hésites pas je suis relativement dispo. 
Bonne soirée

**Comment by Kenderv** [comment]
Au fait, la photo de l'ampoule ça te convient ? Je sais, quand il n'y aura plus que ce problème .....

**Comment by Kenderv** [comment]
Bonjour,
As-tu pu regarder un peu notre problème de gestion de couleurs et chaleurs de blanc avec cette ampoule ? Je réitère mon offre d'aide si tu as besoin que je fasse des tests.
Merci et bon week-end

**Comment by Kenderv** [comment]
Bon, désolé mais je pense que je ne pourrai pas t'aider, mon ampoule ne s'allume plus du tout. Soit elle a cramé en mon absence soit il faudrait la réinitialiser mais je ne connais pas la procédure et comme elle ne s'allume plus du tout même après une  exclusion je vois pas comment faire. Dommage.

**Comment by tcharp38** [comment]
Salut
Peut etre pas.
Tu as fait comme suit ? "Did it in the following way: 3 seconds on, 1 second off. And it starts to blink on 3rd ON instead of 4th."
J'ai trouvé ca la https://github.com/Koenkk/zigbee2mqtt/issues/5109

**Comment by Kenderv** [comment]
J'ai essayé comme indiqué mais je n'ai pas la moindre lumière à s'allumer. Je crois vraiment qu'elle est nase.

**Comment by tcharp38** [comment]
Zut. Fragile alors.

**Comment by tcharp38** [comment]
Je clos cet antique sujet.
A reouvrir si besoin
