### ISSUE TITLE
Prise en charge des interrupteurs Aqara H1 (WS-EUK01)

### ISSUE THREAD

**Issue by nlhomme** [KiwiHC16/Abeille#2054]
Bonjour,

J'ai commandé cette semaine des interrupteurs Aqara H1 (WS-EUK01) sans neutre:
https://www.domadoo.fr/fr/peripheriques/5726-xiaomi-aqara-interrupteur-mural-intelligent-h1-zigbee-30-sans-neutre-6970504214774.html

Ils sont (d'après ce que j'ai lu) identiques à leurs homologues chinois (avec l’intérieur carré)
J'ouvre cette issue afin de vous confirmer ou non leur prise en charge en l'état par Abeille, et le cas échéant échanger avec vous afin d'améliorer leur prise en charge.

Bonne journée

Nlhomme

**Comment by tcharp38** [comment]
Salut
La comme ca j'ai l'impression qu'il n'est pas supporté mais une fois recu on pourra vérifier et corriger ca.
Il faudra
- logs sur 5000 lignes, mode debug
- mode inclusion
- déclencher l'inclusion de l'inter (procedure à trouver)
- au bout d 1min env drag & drop du package de logs ici (page support/telecharger tout)

**Comment by nlhomme** [comment]
Pour info je n'ai pas encore reçu les ampoules, le vendeur est en attente de réapprovisionnement

**Comment by tcharp38** [comment]
Salut
Info sur ce modele https://zigbee.blakadder.com/Aqara_WS-EUK01.html
Donc identiant zigbee = "lumi.switch.l1aeu1"

**Comment by nlhomme** [comment]
J'ai reçu les interrupteurs ce matin, je fais un retour avec les logs pendant le week-end

**Comment by tcharp38** [comment]
Ok. Essaie de tenter l'assistant... 
une fois l'integration par defaut faite
- click sur EQquipement
- avancé
- assistant EQ
- et tu lances la recherche (refresh) pour chaque case vide. Attention certaines peuvent le rester

Puis drag & drop du fichier "discovery.json" (a zipper si github n accepte pas)

**Comment by nlhomme** [comment]
Bonjour,

Voici les logs en mode DEBUG sur 10 000 lignes, ainsi que le fichier discovery.json après inclusion et rafraichissement des cases vides dans l'assistant EQ

[AbeilleLogs-210724.tar.gz](https://github.com/KiwiHC16/Abeille/files/6872588/AbeilleLogs-210724.tar.gz)
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/6872591/discovery.json.zip)

**Comment by tcharp38** [comment]
> Manufacturer: 'LUMI'
> ModelId: 'switch.l1aeu1'
> Location: -unsupported-
> MAC capa: 80
> 8043/Simple descriptor response, SQN=0F, Status=00, Addr=A33B, Length=1A, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0100/On/Off Light, BitField=01
> - InClusterCount=7
> - InCluster=0000 => General-Basic
> - InCluster=0002 => General-Temperature Config
> - InCluster=0003 => General-Identify
> - InCluster=0004 => General-Groups
> - InCluster=0005 => General-Scenes
> - InCluster=0006 => General-On/Off
> - InCluster=0009 => General-Alarms
> - OutClusterCount=2
> - OutCluster=000A => General-Time
> - OutCluster=0019 => General-OTA
> 8043/Simple descriptor response, SQN=10, Status=00, Addr=A33B, Length=0A, EP=F2, ProfId=A1E0/Profil A1E0 inconnu, DevId=0061/Profil A1E0 inconnu, BitField=00
> - InClusterCount=0
> - OutClusterCount=1
> - OutCluster=0021 => Unknown 0021 cluster

> - Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/FFFD
> - Clust 0002: 0000/0010/0012/0014/FFFD
> - Clust 0003: 0000/FFFD
> - Clust 0005: 0000/0001/0002/0003/0004/0005/FFFD
> - Clust 0009: 0000/FFFD

**Comment by tcharp38** [comment]
[switch.l1aeu1.zip](https://github.com/KiwiHC16/Abeille/files/6884438/switch.l1aeu1.zip)

@nlhomme 
A essayer
- Décompresser dans Abeille/core/devices
- tu devrais avoir ..device/switch.l1aeu1:switch.l1aeu1.json
- redemarrer Abeille
- relancer inclusion

**Comment by nlhomme** [comment]
Merci beaucoup, je vais tester ça en fin de journée

**Comment by tcharp38** [comment]
Je corrige le chemin
core/config/devices/switch.l1aeu1/switch.l1aeu1.json

**Comment by nlhomme** [comment]
L'interrupteur est bien reconnu, et j'ai bien les commandes On et Off, en dehors de l'icône qui n'est pas la bonne c'est parfait, merci beaucoup!
![Capture d’écran 2021-07-27 à 18 39 43](https://user-images.githubusercontent.com/9362475/127193850-c1065a59-acf6-40cd-aab7-7497a5dea892.png)

**Comment by tcharp38** [comment]
Je te laisse me trouver une icone PNG qui convient mieux, et si à l usage il y a un souci ou pas.

**Comment by nlhomme** [comment]
Pour l'icône, j'ai mis "Xiaomi Wall Switch W Neutral 1", qui correspond à l'appareil concerné par la présente issue.

Je vais ajouter d'autres interrupteurs dans les jours qui vont venir, je te tiendrai au courant des avancées.

Merci encore!

**Comment by nlhomme** [comment]
J'ai l'impression qu'au bout de quelques minutes d'extinction l'interrupteur cesse de répondre à toute commande...

**Comment by nlhomme** [comment]
Ça  n'a plus l'air de la faire pour l'instant, peut-être le temps qu'il se synchronise avec le reste du réseau zigbee...
Je reste vigilant

**Comment by nlhomme** [comment]
Bon, depuis tout marche parfaitement, même après un redémarrage de Jeedom 🙂

**Comment by nlhomme** [comment]
Ah si, je remarque que quand j'actionne physiquement son état n'est pas mis à jour dans Jeedom...

**Comment by tcharp38** [comment]
Tiens, tu peux refaire une inclusion avec ce JSON à decompresser au bon endroit ?

[switch.l1aeu1.json.zip](https://github.com/KiwiHC16/Abeille/files/6951262/switch.l1aeu1.json.zip)

**Comment by nlhomme** [comment]
Entendu, je fais ça en fin de semaine, merci :+1:

**Comment by nlhomme** [comment]
Salut, je n'ai pas encore pu tester le nouveau zip car je manque de temps en ce moment, je ne pourrais pas m'en occuper avant la mi-septembre

**Comment by tcharp38** [comment]
Pas de soucis mais du coup il est dans la derniere stable il me semble.

**Comment by nlhomme** [comment]
non, c'est l'ancien zip qui est dans la nouvelle version stable

**Comment by tcharp38** [comment]
L'ancien ? Quel est le bon pour toi et pourquoi ?
Désolé si je te fais repeter.

**Comment by nlhomme** [comment]
Je pense qu'il y a un malentendu, quand j'ai vu "ajout support préliminaire" dans le changelog de la dernière version stable (avant-hier je crois), j'ai pensé que tu y as inclu ce que j'apelle "l'ancien zip", c'est-à-dire le zip que tu m'as donné dans ton commentaire du 27 juillet.

Je ne sais pas quel est le bon, vu que je n'ai pas encore testé le nouveau zip que tu as mis dans ton commentaire du 19 août

**Comment by tcharp38** [comment]
Ok alors on refait le point quand tu as du temps pour tester avec la derniere stable.

**Comment by nlhomme** [comment]
Salut!

Pardon d'avoir mis autant de temps à revenir vers toi.
Je viens de tester le json que tu as fournis dans ton commentaire du 7 août c'est tout bon, je pense que l'issue peut-être clôturée.

Merci encore pour ton assistance!

Nlhomme
