### ISSUE TITLE
Version 210620-STABLE-1 zigate wifi maj necessite redemarrage

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#2055]
J'ai mis à jour aujourd'hui vers la version 210620-STABLE-1.
Après la mise à jour , les démons sont tous passé au vert. J'ai commandé l'allumage d'une ampoule philips; l'ampoule s'allume mais le statut dans jeedom ne change pas. J'ai essayé le changement de puissance et le changement de couleur , toutes les commandes sont exécutés mais aucune modification sous jeedom.
Un redémarrage des démons ne change rien.

Je désactive puis réactive le plugin, et là, socat ne parvient plus à fonctionner
_2021/06/22 16:34:09 socat[11704] N PTY is /dev/pts/6
2021/06/22 16:34:09 socat[11704] N opening connection to AF=2 192.168.50.27:9999
2021/06/22 16:34:10 socat[11704] N successfully connected from local address AF=2 192.168.0.53:48236
2021/06/22 16:34:10 socat[11704] N starting data transfer loop with FDs [5,5] and [7,7]
2021/06/22 16:34:10 socat[11704] W read(7, 0x55c242281cd0, 8192): Connection reset by peer
2021/06/22 16:34:10 socat[11704] N socket 2 to socket 1 is in error
2021/06/22 16:34:10 socat[11704] N socket 2 (fd 7) is at EOF
2021/06/22 16:34:10 socat[11704] E write(7, 0x55c242281cd0, 10): Broken pipe
2021/06/22 16:34:10 socat[11704] N exit(1)_

**Je redémarre la VM** et là , miracle, tous les démons sont au vert et les statuts se mettent à jour sous jeedom.
Je te joint toutes logs mais je pense que cela ne sera pas utilisable , j'ai encore oublié de passer en debug avant de faire la mise à jour. Vu que j'ai un souci à chaque mise à jour (ou presque ), ça va finir par rentrer dans mon crâne : pense au debug !
[AbeilleLogs-210622.tar.gz](https://github.com/KiwiHC16/Abeille/files/6695375/AbeilleLogs-210622.tar.gz)

Je n'ai donc plus de problème mais j'ai tout de même ouvert l'issue pour que d'autres qui rencontrerait le même problème pensent à redémarrer leur machine.

**Comment by tcharp38** [comment]
Tu fais bien de garder le sujet ouvert mais je ne vois pas le lien avec les dernieres modifs Abeille.
D'ailleurs si tu regardes le log que tu viens de donner

La connexion avec la zigate Wifi est ouverte

> 2021/06/22 16:34:09 socat[11704] N opening connection to AF=2 192.168.50.27:9999
> 2021/06/22 16:34:10 socat[11704] N successfully connected from local address AF=2 192.168.0.53:48236

puis d'un coup elle est fermée par le device distant (donc la zigate wifi)

> 2021/06/22 16:34:10 socat[11704] W read(7, 0x55c242281cd0, 8192): Connection reset by peer
> 2021/06/22 16:34:10 socat[11704] N socket 2 to socket 1 is in error
> 2021/06/22 16:34:10 socat[11704] N socket 2 (fd 7) is at EOF
> 2021/06/22 16:34:10 socat[11704] E write(7, 0x55c242281cd0, 10): Broken pipe

Bref.. le souci est entre socat et la zigate Wifi, mais au travers des ports controlés par ta VM.

N'as tu pas pu d'update kernel ou autre recemment ?
En tout cas ca semble non pas un pb zigate Wifi mais un pb VM.

Autre question: peux tu me dire si ca fonctionne toujours si tu relances les démons ? (donc arret restart socat).

**Comment by Krankhore** [comment]
On est d'accord, ce n'est pas lié à la version puisque je l'avais déjà eu auparavant des symptômes identiques.
Et non, aucune mise à jour de kernel ou autre mise à jour depuis avant l'installation de la version abeille du 11 juin.

En redémarrant le démon, cela continue de fonctionner.
Puis j'ai changé le niveau de log et redémarré le démon et cette fois, le problème est réapparu, arrêt de socat. ( ce n'est vraisemblablement pas lié au changement de niveau de log  mais coïncidence bizarre). Et même après plusieurs changements et redémarrage du démon le problème subsiste.

Un redémarrage de la VM et tout est de nouveau nickel. 

Je referais calmement quelques essais de relance du démon en ne changeant aucun paramètre puis en changeant. Je verrais bien si ce trouve une origine.

**Comment by tcharp38** [comment]
Ok donc le souci est bien autour de l'arret/redemarrage de socat.
Donc cool, tu dois pouvoir me filer un package de logs.

Je me demande si la connexion ne reste pas "pending" avec la zigate wifi. Tu sais utiliser des commandes comme "netstat" ?
Un truc qui montre l etat de la connexion TCPIP.

**Comment by Krankhore** [comment]
Ok je verifierais l'état des connexions. netstat n'est pas installé dans ma VM  mais un "SS -tnp" devrait faire le boulot

D’ailleurs, c'est bizarre, j'ai 2 process socat
_ss -tnp
State      Recv-Q      Send-Q                   Local Address:Port                     Peer Address:Port
**ESTAB      0           0                         192.168.0.53:58876                   192.168.50.27:9999       users:(("socat",pid=3972,fd=7))**
ESTAB      0           0                         192.168.0.53:38746                    192.168.0.28:8086       users:(("telegraf",pid=552,fd=7))
ESTAB      0           0                         192.168.0.53:40234                   192.168.0.125:8009       users:(("python3",pid=1505,fd=17))
ESTAB      0           64                        192.168.0.53:22                       192.168.0.41:56314      users:(("sshd",pid=17709,fd=3),("sshd",pid=17656,fd=3))
ESTAB      0           0                         192.168.0.53:46482                    35.209.28.70:443        users:(("python",pid=1672,fd=8))
**ESTAB      0           0                         192.168.0.53:58700                   192.168.50.27:9999       users:(("socat",pid=1451,fd=7))**
ESTAB      0           0                            127.0.0.1:39268                       127.0.0.1:43749      users:(("python3",pid=1634,fd=9))
ESTAB      0           0                            127.0.0.1:43749                       127.0.0.1:39268      users:(("python3",pid=1634,fd=10))
ESTAB      0           0                         192.168.0.53:34731                    34.253.63.97:2001       users:(("python3",pid=1634,fd=8))
ESTAB      0           0                         192.168.0.53:60342                    192.168.0.76:8009       users:(("python3",pid=1505,fd=18))
ESTAB      0           0                         192.168.0.53:32904                    192.168.0.31:1883       users:(("php",pid=1501,fd=11))
ESTAB      0           0                         192.168.0.53:34888                        10.8.1.1:1883       users:(("php",pid=1479,fd=11))
ESTAB      0           0                [::ffff:192.168.0.53]:80              [::ffff:192.168.0.44]:42738      users:(("apache2",pid=1040,fd=9))
patrice@Jeedom:~$_

**Comment by tcharp38** [comment]
Salut
2 processus Socat mais qu'une seule Zigate ?!
Pas normal du tout.
Tu fais un "pgrep -a php | grep Socat" pour confirmer ca mais peut etre que ta commande 'ss' reporte plutot les connexions et non pas les process. Un de PID ne doit plus exister mais la connexion n'est pas encore fermée.
C'est ce que je soupconne

**Comment by Krankhore** [comment]
Il n'y a qu'un seul process AbeilleSocat.php

_patrice@Jeedom:~$ pgrep -a php | grep Socat
3934 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../php/AbeilleSocat.php /dev/zigate1 info 192.168.50.27:9999_

mais 2 process socat
_patrice@Jeedom:~$ ps -Al | grep socat
4 S     0  1451  1443  0  80   0 -  1727 -      ?        00:00:00 socat
4 S     0  3972  3963  0  80   0 -  1727 -      ?        00:00:02 socat_

si je fais htop avec un filtrage sur socat
![image](https://user-images.githubusercontent.com/56954282/123321109-dabf8e00-d532-11eb-969f-ed4fb15aab80.png)

Je vois bien le process AbeilleSocat.php uinique et 2 process socat ainsi que visiblement les process qui ont lancé socat.
J'ai fait un test de **redémarrer le démon** dans abeille  et je me retrouve avec **trois process socat**

_patrice@Jeedom:~$ ps -Al | grep socat
4 S     0  1451  1443  0  80   0 -  1727 -      ?        00:00:00 socat
4 S     0  3972  3963  0  80   0 -  1727 -      ?        00:00:02 socat
4 S     0 16485 16484  0  80   0 -  1727 -      ?        00:00:00 socat

![image](https://user-images.githubusercontent.com/56954282/123322130-2f173d80-d534-11eb-8af0-e935a5862c37.png)

C'est peut être cette accumulation qui finit par créer un  problème, je n'avais encore jamais fait attention à ce point. Je vais encore faire quelques essais

**Comment by Krankhore** [comment]
Il faut que te teste plus longuement mais 

- si je kill les plus anciennes versions de socat (et je conserve la version la plus récente), le statut reste au vert dans abeille mais plus aucune commande n'est transmise , ni aucun retour d'info
- puis , lorsque je kill la dernière version de socat, AbeilleSocat.php s'arrête et le statut de socat passe au rouge

Une relance du démon et tout repasse au vert et je n'ai donc plus qu'une version de socat en cours d'execution.

Donc , c'est comme si Abeille surveillait la version la plus récente de socat MAIS que la communication passait par la version la plus ancienne démarré. 
Je jouerais encore un peu demain et je te ferais les retours.
Bonne soirée

**Comment by tcharp38** [comment]
Salut. Voila une bonne piste.
plus d'un "socat" n'est pas normal.
Normalement la fermeture d'AbeilleSocat devrait entrainer celle de "socat" mais ca ne semble pas toujours le cas.

Je vais creuser et reviens vers toi pour des essais.
Merci

**Comment by tcharp38** [comment]
C est bien ca.
Un kill d'AbeilleSocat n'implique pas un kill du child "socat"... du coup la connexion reste ouverte.
Je ne sais pas pourquoi ca n'est pas propagé mais il va falloir trouver une astuce.

**Comment by tcharp38** [comment]
@Krankhore 
210625-BETA-1 à tester.

**Comment by Krankhore** [comment]
Bonjour,
j'ai fait l'essai avec la beta, ça ne règle pas le problème de socat.
J'ai plusieurs essai à partir de 11h01
- avec la version standard , rédémarrage du démon pour vérifier que plusieurs process socat sont en cours : et c'est le cas.
- installation de la version beta : le démarrage est bon mais effectivement les différents process socat existent toujours mais l'ensemble marche.
- je relance le démon , et cette fois, socat ne reste pas au vert ( broken pipe)
- je kill tous les process socat et je relance le démon : socat ne reste pas au vert et la log indique connexion reset par perr
- 11h15m03 je débranche et rebranche la zigate. Cette fois socat s'active , tout est au vert Mais pas de retour d'info de la zigate, et elle passe en time-out. Serialread2 s'est aperçu de la perte de socat et attend le retour, mais je pense que lors du retour, **le traitement ne se passe pas bien et il n'y a aucune donnée traitée**.
- je relance le démon , ce qui relance aussi serialread2 , et là c'est bon.
- 11h24m03 redemarrage d'abeille après reboot de la machine 
- 11h28m35 je redemarre le démon , et il y a bien un deuxième process socat.

Je te joins les différents logs ( le boutoin témécharger tout dans l'onglet support ne fonctionnait pas). Ce qui m'a obligé à traiter les différents logs et j'ai vu dans http.error toute une serie de '**_sh: 1: kill: Operation not permitted_**'
Je vais voir si je trouve plus de détails dans les logs système

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6721344/Abeille.log)
[http.error.log](https://github.com/KiwiHC16/Abeille/files/6721345/http.error.log)
[AbeilleSocat2.log](https://github.com/KiwiHC16/Abeille/files/6721346/AbeilleSocat2.log)
[AbeilleSerialRead2.log](https://github.com/KiwiHC16/Abeille/files/6721347/AbeilleSerialRead2.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6721348/AbeilleCmd.log)

**Comment by Krankhore** [comment]
Dans auth.log , je trouve des kill sans pid 

_root@Jeedom-test:/var/log# cat auth.log | grep kill
Jun 27 11:01:06 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:01:09 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:01:18 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:22:45 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www/html/core/ajax ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:22:46 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www/html/core/ajax ; USER=root ; COMMAND=/bin/kill -9 1699
Jun 27 11:22:50 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www/html/core/ajax ; USER=root ; COMMAND=/bin/kill -9 2043
Jun 27 11:24:03 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:24:05 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9
Jun 27 11:24:15 Jeedom-test sudo: www-data : TTY=unknown ; PWD=/var/www ; USER=root ; COMMAND=/bin/kill -9_

**Comment by tcharp38** [comment]
Salut
J'ai trouvé un bug de mon côté pour ce pb de kill. Du coup ca ne devait pas cloturer "socat" comme je m'y attendais.
Si tu sais utiliser le master, tu peux retester.
Sinon tu peux pendre ce fichier à décompresser dans core/class
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/6725659/AbeilleTools.class.php.zip)
Sinon attendre prochaine beta.

**Comment by Krankhore** [comment]
Bonjour,
j'ai utilisé le zip joint et c'est beaucoup mieux.
J'avais deux process socat actif, j'ai remplace AbeilleTolls et redémarrer le démon.
Après ça, je n'ai plus qu'un seul process socat nouveau et les deux anciens ont été arrêtés.
ci-joint l'extrait correspondant de la log socat :

_2021/06/28 15:39:42 socat[1102] N socat_signal(): handling signal 15
2021/06/28 15:39:42 socat[1102] W exiting on signal 15
2021/06/28 15:39:42 socat[1102] N socat_signal(): finishing signal 15
2021/06/28 15:39:42 socat[1102] N exit(143)
2021/06/28 15:39:42 socat[4731] N socat_signal(): handling signal 15
2021/06/28 15:39:42 socat[4731] W exiting on signal 15
2021/06/28 15:39:42 socat[4731] N socat_signal(): finishing signal 15
2021/06/28 15:39:42 socat[4731] N exit(143)
[2021-06-28 15:39:45] >>> Démarrage d'AbeilleSocat
[2021-06-28 15:39:45] Daemons: {"cmd":1,"parser":1,"serialRead2":2,"socat2":1,"expected":4}
[2021-06-28 15:39:45] Attention ! Certain systèmes acceptent soit l'option 'raw' soit 'rawer' pour socat. Modifiez la ligne "$parameter=" du fichier AbeilleSocat.php pour mettre la bonne option.
[2021-06-28 15:39:45] Creating connection from 192.168.1.17:9999 to /dev/zigate2
[2021-06-28 15:39:45] cmd=/usr/bin/sudo socat -d -d pty,raw,echo=0,link=/dev/zigate2 tcp:192.168.1.17:9999
2021/06/28 15:39:45 socat[27720] N PTY is /dev/pts/2
2021/06/28 15:39:45 socat[27720] N opening connection to AF=2 192.168.1.17:9999
2021/06/28 15:39:45 socat[27720] N successfully connected from local address AF=2 192.168.0.32:35978
2021/06/28 15:39:45 socat[27720] N starting data transfer loop with FDs [5,5] and [7,7]_

**Comment by tcharp38** [comment]
Cool.
Tu peux continuer de l'utiliser. Ce code est dans le master et dans la beta dispo demain.

**Comment by Krankhore** [comment]
Installé la version 210704-STABLE-1 dispo ce jour sur jeedom.
Tout s'est bien passé et il n'y a bien seulement un process socat.
