### ISSUE TITLE
Champ adresse group pour telec 2btn IKEA et détecteur IR

### ISSUE THREAD

**Issue by Brugal21** [KiwiHC16/Abeille#2057]
Bonjour,

Suite à mon post sur le forum de jeedom, j'ouvre cet issue.

https://community.jeedom.com/t/adresse-groupe-interrupteur-on-off-et-detecteur-ir-ikea/56790

Le champ adresse dans le menu avancé des télécommandes 2btns et du détecteur IR IKEA n'est pas visible. Du coup le tableau des groupes en dessous des abeilles n'est pas renseigné pour ces télécommandes. Cependant il est tout a fait possible de les intégrer à un groupe et tout fonctionne. Juste un problème d'affichage ?

Merci d'avance et courage pour le boulot sur ce plugin en perpétuel évolution...

**Comment by tcharp38** [comment]
Tu fais allusion a cette telecommande ?
![image](https://user-images.githubusercontent.com/35221038/123314237-a0ea8980-d52a-11eb-90c6-1bae7b699af7.png)

**Comment by Brugal21** [comment]
Oui c'est celle là.

**Comment by tcharp38** [comment]
Moi je vois le champ adresse dans la partie avancée.
![image](https://user-images.githubusercontent.com/35221038/123316416-1b1c0d80-d52d-11eb-9164-d31b8808234c.png)

**Comment by Brugal21** [comment]
De mon coté rien

![image](https://user-images.githubusercontent.com/55110607/123317346-32a7c600-d52e-11eb-9d40-8eac5bb10d1f.png)

Je vais ré-inclure en supprimant l'objet jeedom avant pour tester

**Comment by tcharp38** [comment]
Ok. Inutile de le supprimer maintenant.
Peut etre que j'ai mis à jour le JSON mais je me souviens plus. Trop en tete.

**Comment by Brugal21** [comment]
Ok j'attends un nouveau json et je recréerait l'équipement.

Merci pour le retour. 👌

Tu utilises ces télécommandes aussi ? Moi tous les équipements sur pile ikea, cette télécommande, la 5 btns et le détecteur IR passe systématiquement en timeout au bout d'heure après utilisation. Je rappui dessus ou passe devant le détecteur est le time out disparaît.
Du coup la valeur de la batterie ne se met pas à jour. J'ai créé des scénarios avec comme déclencheur le clickmiddle ou autres et j'exécute tout de suite un getbatterie, bindbatterie et report batterie et je récupère l'info de la batterie.
Je pensais qu'avec un bind et report cela devait faire remonter la batterie automatiquement...

**Comment by tcharp38** [comment]
Attends pas tout à la fois :)
Deja
- soit tu reinclus
- soit tu actives le mode developpeur et tu peux recharger le dernier JSON sans inclusion
J'ai acheté une telecommande comme ca pour le support mais pour l'instant je ne m'en sers pas vraiment.

**Comment by Brugal21** [comment]
Ok merci pour l'info sur le mode développeur ! J'ai déjà essayé de les reinclure plusieurs fois sans succès. Elles fonctionnent toutes avec des groupes sans problème. J'ai vraiment que le timeout...

Je savais que ça allait pas te plaire que je parle d'un autre sujet dans l'issue, mais comme tu étais dispo j'ai tenté ma chance 😃 

![image](https://user-images.githubusercontent.com/55110607/123320334-e3639480-d531-11eb-972c-09d9dfe3a165.png)

![image](https://user-images.githubusercontent.com/55110607/123320345-e9f20c00-d531-11eb-9260-44ea496f174d.png)

**Comment by tcharp38** [comment]
Tu veux dire quoi par "reinclure sans succes" ? Ca c'est pas cool.

**Comment by Brugal21** [comment]
La reinclusion fonctionne bien mais le timeout revient à chaque fois.
J'ai édité mon post d'avant pour te montrer ma page santé. Tu peux voir beaucoup d'abeilles et 3 seulement en timeout : 2 telec 2btns et 1 5btns. j'ai une autre 5btns sur laquelle j'ai appuyé dans la dernière heure comme le détecteur IR ou je suis passé devant. Dans 1 h ils sont en timeout si je les touche pas

**Comment by tcharp38** [comment]
Ok, on se focalise sur la TRAFRIonoffswitch. C est la seule que j'ai.
Sauf erreur le seul report qu'il doit y avoir est le report batterie.
Tu peux me donner ton package de logs ?

**Comment by Brugal21** [comment]
Ok ça marche. C'est bien ça le bindshort et le setreport sont sur la batterie.

Mon package de logs ? je met le demon en debug, 5000 lignes, je laisse tourner quelques temps et je t'envoie tous les logs remplis ?

**Comment by tcharp38** [comment]
Oui c'est ca, si tu n'as pas déja mis 5000.
Si tu peux refaire une inclusion puis me filer le package je verrai si je vois qqch qui s'est mal passé.
1min apres l'inclusion ca suffit

**Comment by Brugal21** [comment]
Ok parfait je te prépare ça.
Merci pour tout !

**Comment by Brugal21** [comment]
En pièces jointes les logs.
J'ai fait l'inclusion vers 21h57:20sec :)
Et j'ai retrouvé le paramétrage de l'adresse du groupe dans le champs avancé de l'équipement :)

A quoi sert le champ durée en seconde juste en dessous ?

On peut déjà clore l'issue dont l'objet principal était l'adresse du groupe...

[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6711852/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6711853/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6711854/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6711855/Abeille.log)

**Comment by Brugal21** [comment]
1h plus tard les 2 telec on/off ne sont pas en timeout, au top 👌 

Je ferai pareil avec mes 2 telec 5btns et mon détecteur IR, une reinclusion.

J'ai regardé la date de création et c'était en mars la dernière fois que j'avais essayé de les reinclure donc basé sur un json de mars.

Je te tiens au courant de la suite.

**Comment by tcharp38** [comment]
Je viens de sortir une beta (210625-BETA-1).
Dispo demain sur le market.
Avec cette version tu dois pouvoir recharger le JSON sans reinclure (page EQ/avancé)

**Comment by Brugal21** [comment]
Salut,

Depuis la reinclusion d'hier soir aucun problème, les switch 2btns ne passent plus en timeout 👍

Merci pour l'info de la beta 😉

**Comment by Brugal21** [comment]
Salut @tcharp38 

du coup, plus aucun soucis avec les switch on/off Ikea depuis leur réinclusion ! Le champ télécommande adresse groupe est bien visible et la gestion des groupes fonctionne, c'est parfait !

**Comment by tcharp38** [comment]
Salut
Il faut séparer les sujets. Equipement different = probleme potentiellement different.
Exmple: je ne sais pas à quel EQ correspondent tes derniers logs. Je vois que l'inclusion se passe mal, car trop de messages envoyés en meme temps. C est un pb Abeille qui traine depuis longtemps.

Bref je te laisse renommner si besoin ou le fermer si ok et creer d'autres points séparés. (champ adresse group different de timeout).
Ca sera + facile de suivre
Merci

**Comment by Brugal21** [comment]
Oui je comprend, je vais faire le tri.
Pour ce sujet avec le problème de champ adresse groupe : 
 - les switch on/off Ikea : avec une inclusion récente fonctionne, le champs est visible
 - le détecteur IR Ikea (E1745) : avec une inclusion récente, le champs n'est pas visible

**Comment by tcharp38** [comment]
Merci.
Tiens, teste avec ce JSON  (a decompresser dans core\config\devices\TRADFRImotionsensor)

Je l'ai aussi passé en categorie "security" au lieu de "light". Ca me semble plus juste pour un  detecteur IR.
[TRADFRImotionsensor.zip](https://github.com/KiwiHC16/Abeille/files/6721239/TRADFRImotionsensor.zip)

**Comment by Brugal21** [comment]
Je viens de tester le json, le champ adresse groupe est visible avec ! C'est parfait.
Je suis d'accord avec toi pour la catégorie securité, je me sers des détecteurs en capteur de présence pour mon alarme quand je suis pas là.
On peut donc clore cet issue. 
Merci beaucoup.

**Comment by ghost** [comment]
Bonjour,

Depuis passage en version stable 2021-07-20 (jeedom 4.1.24) j'ai voulu recharger le fichier JSON de l'interrupteur pour retrouver le champ "Adresse groupe". Pas de problème de ce côté-là mais j'ai du coup perdu des commandes, notamment celle permettant de faire remonter l'appui sur le bouton (Up-down de mémoire). 
Conséquence : commande orpheline dans mes scénarios et plus de déclenchements.

J'ai deux autres boutons identiques qui eux ont eu automatiquement leur fichier JSON mis à jour après s'être réanoncés sur le réseau, et même problématique pour le coup.

**Comment by tcharp38** [comment]
Salut @FQsqQ 
Il y avait effectivement 2 commandes INFO en +: Up-Down & Click-Middle.
J'avoue ne pas comprendre du tout comment elles peuvent bouger.
Up-Down change d"etat ? Sur quel evenement ?

Ci joint le JSON corrigé. Dis moi si ca colle.
[TRADFRIonoffswitch.zip](https://github.com/KiwiHC16/Abeille/files/6974175/TRADFRIonoffswitch.zip)
A décompresser dans core/config/devices/TRADFRIonoffswitch/

**Comment by ghost** [comment]
Salut Tcharp. Désolé pour la réactivité mais je n'avais pas reçu de notif de réponse.

Merci pour le fichier JSON corrigé. J'ai bien retrouvé les 2 commandes et tout refonctionne parfaitement.
Finalement c'est la commande Click-Middle dont j'avais besoin et qui renvoit la valeur déclenchant mon scénario : 0 si appui sur le bouton "O"/bas, 1 si appui sur le bouton "I"/haut. La commande Up-Down semble rester sur la valeur 7 quelque soit l'appui.

Quant à la Zigate, elle ne voit la valeur que parce que je l'ai ajoutée au même groupe que le bouton (et l'ampoule associée). D'ailleurs le plugin ne liste plus les groupes dont fait partie la Zigate. Est-ce que c'est toujours une limite de 5 groupes ?

Par contre j'ai perdu l'icône du bouton avec ce fichier JSON. La propriété était "icon" au lieu de "icone", comme dans le JSON d'autres devices. Je l'ai modifié mais la ligne n'apparaît plus dans la liste déroulante pour le choix de l'icône, bien que le nom soit bon et que le .png correspondant n'ait pas bougé. Mais bon, ça c'est un détail.

Merci pour ton aide !

**Comment by tcharp38** [comment]
salut @FQsqQ 
Pas de soucis. Merci pour tes retours.
Ce sujet etant clos, n'hesite pas à le reouvrir si besoin, si qqch n'est pas reglé ou reapparait. Si sujet different alors en ouvrir un autre.
