### ISSUE TITLE
Ikea Tradfri E14 LED 400 lm (LED1536G5)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#206]
Je viens d'avoir cette ampoule.
![img_5655](https://user-images.githubusercontent.com/8549674/37517736-a5c865c0-2912-11e8-82ac-6ff099273bca.jpg)
![img_5649](https://user-images.githubusercontent.com/8549674/37517742-ace2b824-2912-11e8-9793-b48d0cbf41e0.jpg)
![img_5650](https://user-images.githubusercontent.com/8549674/37517753-b8bece26-2912-11e8-89b9-4b4f1dd17cc0.jpg)
![img_5651](https://user-images.githubusercontent.com/8549674/37517759-c0a82c7c-2912-11e8-990a-14dcec60d655.jpg)
![img_5652](https://user-images.githubusercontent.com/8549674/37517761-c76c0786-2912-11e8-925d-72d4004c6de5.jpg)
![img_5653](https://user-images.githubusercontent.com/8549674/37517772-cd366f3a-2912-11e8-85af-fc9186bd47ee.jpg)

**Comment by KiwiHC16** [comment]
https://www.ikea.com/fr/fr/catalog/products/70318284/
Infos from Ikea Web Site

Général
--
Marque | IKEA
Référence du modèle | LED1536G5
Classe d'efficacité énergétique | A+
Consommation d'énergie pondérée | 5 kWh/1000h
Flux lumineux nominal | 400 lm
Durée de vie nominale | 25000 h
Nombre de cycles de commutation | 25000 cycles
Température de couleur | 2700 Kelvin
Temps de chauffage nécessaire pour atteindre 60 % du flux lumineux total | <1 s
Intensité variable | **Non**
Dimensions de la lampe | 110 x 60 mm
Puissance assignée | 5 watt
Flux lumineux assigné | 400 lm
Durée de vie assignée de la lampe | 25000 h
Facteur de puissance de la lampe | 0.7
Facteur de conservation du flux lumineux à la fin de la durée de vie nominale | 70%
Temps d’allumage | 0.5 secondes
Rendu des couleurs | 80
Instructions pour le nettoyage des débris de lampe en cas de bris accidentel de la lampe | www.ikea.com
Recommandations relatives à l’élimination de la lampe à la fin de son cycle de vie | www.ikea.com

------------------------

La couleur de la lumière varie entre 2 200 kelvins (rougeâtre), 2 700 kelvins (blanc chaud) et 4 000 kelvins (blanc froid).

------------------------

L'ampoule n'est pas compatible avec les variateurs d'intensité.

------------------------

[tradfri-ampoule-a-led-e-lumen__AA-1901467-3_pub.pdf](https://github.com/KiwiHC16/Abeille/files/1818947/tradfri-ampoule-a-led-e-lumen__AA-1901467-3_pub.pdf)

**Comment by KiwiHC16** [comment]
AbeilleParser 2018-03-16 12:20:16[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 03; ....

>>> "545241444652492062756c6220453134205753206f70616c203430306c6d".decode("hex")
'TRADFRI bulb E14 WS opal 400lm'

C'est bien l ampoule qui est deja dans Abeille: TRADFRIbulbE14WSopal400lm

WS = White Spectre

**Comment by KiwiHC16** [comment]
Endpoint Count : 01; Endpoint List :; Endpoint : 01

**Comment by KiwiHC16** [comment]
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0008 - General: Level Control
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0300 - Lighting: Color Control
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 0B05 - Misc: Diagnostics
AbeilleParser 2018-03-16 12:24:03[DEBUG]In cluster: 1000 - ZLL: Commissioning
AbeilleParser 2018-03-16 12:24:03[DEBUG]OutClusterCount : 04
AbeilleParser 2018-03-16 12:24:03[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-03-16 12:24:03[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2018-03-16 12:24:03[DEBUG]Out cluster: 0020 - General: Poll Control
AbeilleParser 2018-03-16 12:24:03[DEBUG]Out cluster: 1000 - ZLL: Commissioning

**Comment by KiwiHC16** [comment]
Temperature Dec - Hex
2200 0x0898
2700 0x0A8C
4000 0x0FA0
Color X-Y: si Y=0 et X une des valeurs en hex, ampoule toujours rougeâtre
Color X-Y: si Y=0 et X une des valeurs en dec, ampoule toujours rougeâtre pour 2xxx et blanche pour 4000.

Y=0 et X varie
0000-3500: Rougeatre
3500-5000: Blanchie
5000-FFFF: Blanche

Mais le Y impacte aussi la couleur ....

**Comment by KiwiHC16** [comment]
Association Telecommande Ronde avec Ampoule, appui sur bouton gauche / droite:

![capture d ecran 2018-03-16 a 13 03 01](https://user-images.githubusercontent.com/8549674/37519721-89bf8ee6-291a-11e8-978e-6b35cc131e92.png)

![capture d ecran 2018-03-16 a 13 03 19](https://user-images.githubusercontent.com/8549674/37519731-90736f96-291a-11e8-805b-8bbde13c2c2a.png)

**Comment by mickadam29** [comment]
Nickel. Comment prévois tu la gestion des Kelvin  (température)  sur ces 3 valeurs ?
Il faudra transposer sur la E27WS980 et GU10WS.
Par contre, il me semblait d'après certaines lectures que le mode de ces ampoules étaient par défaut "ct" pour control temperature et une seule valeur et, accessoirement une gestion "xy"

**Comment by KiwiHC16** [comment]
Push done. Can close now.

**Comment by mickadam29** [comment]
Merci pour ce taf
