### ISSUE TITLE
Inclusion détecteur IR Ikea E1745

### ISSUE THREAD

**Issue by Brugal21** [KiwiHC16/Abeille#2060]
Salut @tcharp38 

Pour le détecteur IR ikea (E1745), j'en ai un. Je l'ai réinclus. L'inclusion se passe mal. Il faut relancer l'inclusion du capteur plusieurs fois pour que abeille le détecte et ensuite une fois l'inclusion réussie, le capteur ne remonte aucune info, en particulier l'info clickmiddle. Au bout d'1h il passe en timeout et ne revient jamais car il ne renvoie aucune détection à Jeedom (normalement visible avec l'info clickmiddle)
Je te joins les logs en debug lors de l'inclusion que j'ai faite, j'ai commencé vers 15h12:30s et au bout de 5 ou 6 essais d'inclusion le capteur s'inclue enfin, vers 15h16. Mais ne remonte donc aucune info par la suite.
De plus le champ télécommande adresse groupe n'est pas visible dans l'objet créé.

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/6720161/Abeille.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/6720162/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6720163/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/6720164/AbeilleCmd.log)

Pour info mon système (RPi3B+ / Zigate USB sur HUB USB alimenté et cordon : 

1/ Version (Abeille.version)
============================
210620-STABLE-1

2/ Linux
========
["Raspbian GNU\/Linux 10 \\n \\l",""]
["Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031D

**Comment by tcharp38** [comment]
Salut.
Je crois qu'il y a 2 points
- Le fait de devoir faire plusieurs inclusions est surement un souci Abeille, trop de messages envoyes en meme temps. Je vais bosser la dessus avec toi si tu veux passer sur la beta.
- Apres une inclusion réussie je n ai pas assez de traces. Tu as mis 5000 lignes pour le log ? Si non a changer.
Il me faudrait le log apres une inclusion réussie suivi de click middle puisque tu me dis que ca ne fonctionne pas.

Dernier point, au lieu de coller chaque log, tu peux mettre le package de la page support/telecharger tout.
Il contient tout et meme les logs "previous".

**Comment by Brugal21** [comment]
Salut,

alors pour tes 2 points :

 - ok pour passer en beta, même si j'ai qu'un seul système à la maison et que si ça plante, madame ne sera pas contente... :)

 - mes logs sont paramétrés à 10000 lignes, c'est juste que j'ai récupéré les logs trop rapidement après l'inclusion réussie.
L'info click-middle correspond à une détection de présence par le capteur. Le fonctionnement avant était que l'info clickmiddle est tout le temps = 42, elle ne repasse jamais par une autre valeur. Du coup, pour savoir quand le détecteur capte quelque chose, il faut paramétrer cette commande info avec la gestion de la répétition des valeurs sur toujours répéter.

![image](https://user-images.githubusercontent.com/55110607/123558685-e5c72800-d797-11eb-8c2a-9f0f1953a431.png)

Et même en faisant ça c'est pas parfait, car de ce que j'avais vu la commande clickmiddle renvoie 42 de façon aléatoire aussi...
Comme mon détecteur est dans un groupe avec 2 ampoules, j'avais créer un scénario pour simuler le fonctionnement du détecteur de présence : 

![image](https://user-images.githubusercontent.com/55110607/123558693-f11a5380-d797-11eb-8ab0-04a55a491693.png)

![image](https://user-images.githubusercontent.com/55110607/123558695-f5df0780-d797-11eb-8867-0744980f232f.png)

Aujourd'hui après une inclusion, l'info clickmiddle reste vide : 

![image](https://user-images.githubusercontent.com/55110607/123558754-3fc7ed80-d798-11eb-86e8-8ec61f7e1e9f.png)

De ce que je comprends, je passe le plugin abeille en beta, je remet le json de l'issue #2057, je fais une inclusion et laisse quelques minutes avant de télécharger les logs. Je prends l'ensemble des logs dans la page support du plugin et te les posts là. C'est bien ça ?

**Comment by tcharp38** [comment]
Salut
En fait j'ai besoin de voir ce qui remonte du device avec le click middle, donc au moins le log parser autour de cette action et Abeille.

Pas besoin pour l instant de passer en beta je pense.

**Comment by Brugal21** [comment]
Salut,

du coup je suis passé sur la beta : 

![image](https://user-images.githubusercontent.com/55110607/123693610-8ed55780-d858-11eb-99a0-f18bbeeb162a.png)

Je refais une inclusion en ayant préalablement supprimé le détecteur d'abeille.
21h36:00 démarrage mode inclusion zigate
21h36:10 première inclusion du device (4 x sur le bouton)
21h37:10 deuxième inclusion du device (4 x sur le bouton)
21h37:31 inclusion réussie

![image](https://user-images.githubusercontent.com/55110607/123694197-4c604a80-d859-11eb-8e5a-b8d4e830a609.png)

Ensuite je ne peux rien faire je suis devant le détecteur qui est censé renvoyer une info clickmiddle = 42 sur détection.
21h41:00 à 21h42:00 je bouge la main devant...
21h44:00 page support -> télécharger tout : 

[AbeilleLogs-210628.tar.gz](https://github.com/KiwiHC16/Abeille/files/6728900/AbeilleLogs-210628.tar.gz)

21h45:00 toujours aucune valeur sur clickmiddle...

Dis moi si tu as ce qu'il te faut?

**Comment by Brugal21** [comment]
Ne soit pas désolé, j'ai pas vérifié le package de log avant de te l'envoyer.

Ouais j'avoue que côté log j'ai pas compris pkoi le parser c'est pas rempli...

Pour le prev, je n'arrive pas à le vider depuis la page support. Et je n'ai pas la main pour le démarrer ou l'arrêter comme les logs de la configuration de abeille : 

![image](https://user-images.githubusercontent.com/55110607/123840239-63ad3f80-d90e-11eb-9d49-879e93620917.jpeg)

On dirait que tous les logs supplémentaires de la page support sont bloqués...

Je refais une inclusion est te renvoi les logs en vérifiant qu'ils se remplissent bien cette fois 😀

Edit : j'ai vu que le détecteur s'est reannoncé dans la nuit vers 1h30 du matin. Rien de particulier ensuite. Bon t'as pas de log donc tu t'en fou 😜

Il ne passe aussi jamais en timeout, il parle donc bien avec la zigate apparemment. Par contre aucune info sur le clickmiddle depuis et pareil sur l'info de l'adresse IEEE : rien ne remonte. Pourtant la page santé me donne bien l'adresse...

![image](https://user-images.githubusercontent.com/55110607/123841373-c226ed80-d90f-11eb-90cc-ee58c934acf9.jpeg)

![image](https://user-images.githubusercontent.com/55110607/123841475-e4207000-d90f-11eb-9caf-3328f46de3a0.jpeg)

**Comment by tcharp38** [comment]
Le log "previous" est automatiquement généré quand le log standard est plein. C'est histoire de garder la trace precedente, ce que n'offre pas Jeedom.

Pourquoi t'attends tu a une remontée sur Addr-IEEE ? Pour moi ca ne doit arriver qu'a l'inclusion ou nouvelle annonce, donc tres rare. Mais ca doit etre rempli. Ca n'est pas le cas ?

Il s'est réannoncé vers 1h30 ? Curieux. Si tu as les logs à l occase je veux bien voir pour etre sur qu'il n'a pas fait de "leave" avant.

**Comment by Brugal21** [comment]
Salut,

merci pour les explication des logs. En fait, je met les logs abeille en debug vraiment quand besoin et ensuite je repasse en défaut. Je me dis que ça prend de la ressource au système de laisser le log en debug, peut-être à tort... ?
Du coup pour le moment je suis en debug depuis hier soir et les logs previous se remplissent bien.

Pour la remontée de l'adresse, je ne savais pas que cela remontait qu'une seule fois, merci pour les pécisions. En tout cas pour le détecteur, le champ est vide. Tu peux voir le résultat de la commande en haut de mon deuxième screen du post précédent.

Oui il s'était ré annoncé vers 1h30 mais les logs étaient en défaut, donc pas de trace...
Je reste maintenant en debug le temps de faire toutes nos investigations...
Je refais une inclusion ce soir, plus ou moins tard..., et te file les logs.

**Comment by tcharp38** [comment]
Cote logs, je ne crois pas que ca ai un gros impact. De toute facon ils sont limites par la taille donnée dans la config.
Si jamais tu vois un impact je suis preneur.

Ok adresse IEEE, en y reflechissant oui il doit y avoir un bug. L'adresse est connue mais la commande pas remise à jour.
Il faut que j'y reflechisse => #2068

**Comment by Brugal21** [comment]
Je ne sais pas te dire si ça a un impact, j'ai franchement l'impression que non... Mais, je me dis que les logs abeille quand ils tournent en debug, ils en ecrivent des lignes... mdr.

Je te laisse réfléchir pour l'adresse ;)

Voila la manip que je viens de faire : 
 - essai de supprimer l'équipement du réseau zigbee à l'aide de la commande remove de la ruche et l'adresse ieee de l'équipement => pas fonctionné
 - suppression de l'équipement jeedom =>ok
 - reinitilisation du module
 - mise en inclusion de la zigate
 - inclusion du module
 - besoin de faire 2 x l'inclusion pour que abeille détecte le module
 - à 21h41:40 : création de l'équipement (adresse courte : 2C6D)

Et le package de logs : 

[AbeilleLogs-210630_2.tar.gz](https://github.com/KiwiHC16/Abeille/files/6743596/AbeilleLogs-210630_2.tar.gz)

**Comment by tcharp38** [comment]
un truc à faire:
- tu affiche le log parser
- et tu declenche le detecteur en passant devant

pour voir si qqch est remonté par défaut.
Tu dois voir une correlation entre une nouvelle trace parser et ton mouvement.
Si rien ne se passe, c 'est qu'il faut faire une config particluiere pour le reporting.

**Comment by tcharp38** [comment]
[TRADFRImotionsensor.zip](https://github.com/KiwiHC16/Abeille/files/6749580/TRADFRImotionsensor.zip)

Un autre JSON à essayer. J'ai ajouté un reporting du cluster 6.
Refaire une inclusion avec celui la.

**Comment by tcharp38** [comment]
@Brugal21 
Des news ?

**Comment by tcharp38** [comment]
@Brugal21 
Salut. Je crois que j'ai besoin de ton aide à propos de cette histoire "click middle".

**Comment by Brugal21** [comment]
Salut @tcharp38 

Désolé mais je ne tourne plus avec le plugin abeille. Je ne peux donc plus t'aider sur ce sujet.

Merci encore pour le temps consacré à résoudre les problèmes !

Bon courage pour la suite.

**Comment by tcharp38** [comment]
OK pas de soucis. Tu as basculé sur quoi ?

**Comment by Brugal21** [comment]
J'ai installé le plugin zigbee officiel. J'ai aussi changé de contrôleur pour un Popp.

**Comment by tcharp38** [comment]
Dac. Si jamais tu as des retours en gros sur ce qui t'a fait basculer et donc ce qui pourrait être amélioré, abeille ou zigate,je suis preneur et je transmettrai. Merci
