### ISSUE TITLE
Cmd Addr-IEEE vide au redemarrage

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2068]
Si l'adresse IEEE d'un equipement est forcement connue depuis son annonce, la commande n'est pas remise à jour au redemarrage.
Il faut copier eqLogic/config/IEEE => cmd Addr-IEEE

**Comment by Brugal21** [comment]
Mdr tu as vite réfléchi ;)

**Comment by tcharp38** [comment]
Ce souci doit etre le meme pour
- addr courte
- last comm

**Comment by tcharp38** [comment]
210719-STABLE-1
Semble ok maintenant mais si le mecanisme de sauvegarde/restauration n'est pas clair. Pas encore de réponse de l'equipe Jeedom.
https://community.jeedom.com/t/restauration-de-la-valeur-des-commandes-infos-au-redemarrage-du-plugin/64103
