### ISSUE TITLE
Pb d’inclusion capteur de température

### ISSUE THREAD

**Issue by Bernichou** [KiwiHC16/Abeille#2069]
Bonjour @tcharp38
[AbeilleLogs-210701.tar.gz](https://github.com/KiwiHC16/Abeille/files/6746534/AbeilleLogs-210701.tar.gz)

Merci pour ton aide.
Avant de te répondre, j’ai fait quelques essais d’inclusion. Les capteurs qui refusaient l’intégration ont été reconnus mais d’autres « inconnus » sont apparus. Aujourd’hui, j’en ai 3 !
J’ai fait tout ce que tu m’a demandé et je te joins le téléchargement.

**Comment by tcharp38** [comment]
Salut
Tu es sur quelle version ?
D'autre part penses à augmenter la taille des logs, 500lignes c 'est trop court. Je suggere 5000.
A faire via la config Jeedom: Reglages/systeme/configuration logs
puis sauver
puis redemarrer Abeille (important !)

**Comment by tcharp38** [comment]
Bon à priori tu es sur la 210620-STABLE-1.
Du coup une fois la taille des logs augmentée, je veux bien un nouveau package apres reinclusion. Merci

**Comment by Bernichou** [comment]
Je suis bien sur la 210620 et j'avais déjà augmenté dès hier la taille des logs comme tu me l'avais suggéré.
Qu'entends-tu par redémarrer Abeille, relancer les dépendances ou bien rafraichir ?

**Comment by Bernichou** [comment]
Je t'envoie un nouveau package après réinclusion.
[AbeilleLogs-210701 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6748213/AbeilleLogs-210701.1.tar.gz)

**Comment by tcharp38** [comment]
> Je suis bien sur la 210620 et j'avais déjà augmenté dès hier la taille des logs comme tu me l'avais suggéré.
> Qu'entends-tu par redémarrer Abeille, relancer les dépendances ou bien rafraichir ?

Redemarrer Abeille via la page de config pour qu'il prenne en compte la nouvelle taille

![image](https://user-images.githubusercontent.com/35221038/124128157-cde3f280-da7c-11eb-9afb-cab4e8b357f3.png)

**Comment by tcharp38** [comment]
Regarde le log Parser par ex
Tu trouves ca au top

> Max atteint (490 lignes)

**Comment by Bernichou** [comment]
J'en apprends un peu plus chaque jour !

C'est fait : redémarrer et nouvelle réinclusion.
[AbeilleLogs-210701 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/6748438/AbeilleLogs-210701.2.tar.gz)

**Comment by tcharp38** [comment]
Désolé :)
Il n'y a toujours que 500 lignes.
Regarde l'entete du log parser par ex

> 2021-07-01 15:16:46] Max atteint (490 lignes)

Passer le nombre de lignes à 5000 par log (500 par défaut, trop court).
Reglages > Systeme > Configuration
puis Logs et Logs
« Nombre de lignes maximum dans un fichier de log » = 5000
Sauvegarder
Relancer Abeille

**Comment by Bernichou** [comment]
Je ne comprends pas. J'ai bien sauvegardé l'onglet logs. J'ai relancé Abeille comme indiqué. L'entête du log parser n'a pas changé !
<img width="785" alt="TailleLogs" src="https://user-images.githubusercontent.com/58849313/124158379-22e23180-da9a-11eb-9758-3ee9fb40215b.png">

**Comment by tcharp38** [comment]
Bizzare.
Tu l'as redemarré à 15:14:22, donc tu avais modifié la taille avant ?

**Comment by Bernichou** [comment]
Non, je l'ai redémarré après 18h.

**Comment by Bernichou** [comment]
Et oui, j'avais modifié la taille avant.

**Comment by Bernichou** [comment]
Bonjour @tcharp38,
[AbeilleLogs-210702.tar.gz](https://github.com/KiwiHC16/Abeille/files/6752337/AbeilleLogs-210702.tar.gz)

Bon, ce matin la limite du log à 5000 lignes est reconnue par Abeille.
J’ai fait une réinclusion et un nouveau téléchargement.

**Comment by tcharp38** [comment]
Ha c est bien mieux.
Ton capteur est un Xiaomi temperature carré ?

Si oui je vois bien son inclusion

[2021-07-02 07:42:02] Abeille1, Type=004d/Device announce, Addr=B034, ExtAddr=00158D000543AEAC, MACCapa=80
[2021-07-02 07:42:02]   Xiaomi specific identification.

[2021-07-02 07:42:02] Abeille1, Type=8102/Attribut report, SQN=00, Addr=B034, EP=01, ClustId=0000, AttrId=0005, AttrStatus=00, AttrDataType=42, AttrSize=000C
[2021-07-02 07:42:02]   ModelIdentifier='lumi.weather', trimmed='weather'
[2021-07-02 07:42:02]   EQ is supported with 'weather' identifier

puis il reporte ses infos de temp, pression...

[2021-07-02 07:42:08] Abeille1, Type=8102/Attribut report, SQN=02, Addr=B034, EP=01, ClustId=0402, AttrId=0000, AttrStatus=00, AttrDataType=29, AttrSize=0002
[2021-07-02 07:42:08]   Temp, MeasuredValue=06ED => 17.73C

[2021-07-02 07:42:08] Abeille1, Type=8102/Attribut report, SQN=03, Addr=B034, EP=01, ClustId=0405, AttrId=0000, AttrStatus=00, AttrDataType=21, AttrSize=0002
[2021-07-02 07:42:08]   Humidity, MeasuredValue=2335 => 90.13%

[2021-07-02 07:42:08] Abeille1, Type=8102/Attribut report, SQN=04, Addr=B034, EP=01, ClustId=0403, AttrId=0000, AttrStatus=00, AttrDataType=29, AttrSize=0002
[2021-07-02 07:42:08]   Pressure, MeasuredValue=03F3 => 101.1kPa

Mais je suis surpris de ces retours pour ce capteur.
Il est recent ? Quelle est sa ref ?
Et du coup qu'est ce qui ne fonctionne pas de ton point de vue ?

**Comment by Bernichou** [comment]
Merci de ton retour
Ce sont bien des capteurs Xiami carrés pour les températures(réf ?), ronds pour la détection d’eau.
Ce qui m’ennuie c’est que certains capteurs, ici « Température SdeBain » se déconnectent très très souvent.
Les « détection d’eau », c’est pratiquement tout le temps et même quand ils sont connectés, ils n’envoient pas systématiquement les infos.
J’ai augmenté le réseau de prises IKEA (de 4 je suis passé à 6) en espérant un meilleur maillage mais le Zigbee crée des liens stupides, allant se lier à une prise éloignée alors qu’il en a une tout près. Mais là je ne t’apprends rien, c’est apparemment le cas pour beaucoup d’utilisateurs. 
En ce moment, je n’ai qu’un « inconnu », hier j’en ai eu jusqu’à 4 !
Je refais une inclusion pour les 2 détection d’eau  et je te l’envoie. (Là, ils sont reconnus)
Mes capteurs datent de quelques mois et achetés sur Aliexpress
<img width="1280" alt="TailleLogs" src="https://user-images.githubusercontent.com/58849313/124249047-c75c8600-db23-11eb-9375-7f1c4b43f81b.png">
![LiensAbeille](https://user-images.githubusercontent.com/58849313/124249055-caf00d00-db23-11eb-8d72-4e1971aa4b80.jpg)
![RéseauAbeille1](https://user-images.githubusercontent.com/58849313/124249059-cb88a380-db23-11eb-8d1e-7767aeb1b588.jpg)
![RéseauAbeille2](https://user-images.githubusercontent.com/58849313/124249068-cdeafd80-db23-11eb-9f8c-5f44e940bf41.jpg)
![SantéAbeille](https://user-images.githubusercontent.com/58849313/124249080-d0e5ee00-db23-11eb-8bdc-205d38d7e019.jpg)
[AbeilleLogs-210702 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6753387/AbeilleLogs-210702.1.tar.gz)

**Comment by tcharp38** [comment]
Pour ne pas tout mélanger on ne se focalise que sur le temp carré.
J'aimerais bien connaitre la ref fabricant marqué derriere. Est ce WSDCGQ11LM ?
Comme je disais je pige pas qu'il remonte autant d'infos.

Coté deconnexion, les capteurs Xiaomi sont connus pour être capricieux. Non seulement ils peuvent decider de quitter le reseau d eux meme quand ils n'ont pas eu de reponse depuis un moment mais leur choix de routage semble difficile.
Dans tous les cas la ca n'est pas un pb d'inclusion.

Confirme moi ma comprehension mais du coup l'inclusion se passe correctement, tu as des remontées, puis à un moment le capteur passe en "inconnu". Correct ?

**Comment by Bernichou** [comment]
C'est bien la référence WSDCGQ11LM .
Exact PARFOIS pour le passage en "inconnu" mais pas systématiquement.
Je m'explique : parfois et même souvent, le capteur passe en "Time-out" mais n'indique pas d'"inconnu" supplémentaire.
Et je dois faire un appui long sur le capteur pour le faire revenir sur le réseau.
J'ai pensé bien faire en ajoutant des prises pour un meilleur maillage. Cela pourrait-il perturber le zigbee qui aurait trop de choix à faire ?

**Comment by tcharp38** [comment]
Le passage en "inconnu", je pense à un bug de ma part.
En gros je pense que le device de temps en temps "quitte" puis "reviens". Tu peux confirmer ca en surveillant des "leave request" dans le parser. Mais du coup je crois que le code actuel a une faiblesse pour ce cas. Je bosse dessus.

Par contre si il n'envoie plus rien, ca ressemble aux pbs que j'ai chez moi avec 3 capteurs de temp carré. Ils s'arretent d'envoyer en quittant le reseau d eux meme, mais personne n'est au courant. Défaut Xiaomi.

Le maillage ne peut qu'améliorer les choses mais encore faut il que les periphs acceptent de passer par ces routeurs. La encore cote Xiaomi c'est assez capricieux. En tout cas Abeille ne peut rien faire de ce côté.

**Comment by tcharp38** [comment]
Tu peux essayer un truc pour voir ce que ca donne.
Il y a une fonctionalité "monitoring" cachée.

- Activer le mode developpeur (page de config, options avancées)
- Redemarrer les démons
- Dans la page de gestion tu dois voir apparaitre le bouton "surveiller". 
- tu selectionnes un capteur et clique sur "surveiller"

A partir de la tous les messages de ce capteur sont surveilles, dans les 2 sens.
Voir AbeilleMonitor.log

**Comment by Bernichou** [comment]
J’ai mis en route la « surveillance » et je regarderai les informations données par son log.
En tous cas, je suis très satisfait de ce plugin. On sent beaucoup de rigueur dans sa conception et un souci constant de le faire évoluer.
 Les outils texte et graphique proposés permettent vraiment de mieux « voir » le réseau Zigbee qui est assez déroutant.

Bravo et chapeau pour les passionnés dont tu fais partie qui nous permettent de faire un peu de domotique avec peu de connaissances dans ce domaine.

**Comment by tcharp38** [comment]
Salut
Pour info, j'ai un capteur Xiaomi temp/humidité/pression carré qui refuse de s'inclure maintenant, sans aucune raison.
Je sniff le reseau et je vois qu'il n'essaie meme pas donc rien à voir avec Abeille.
Peut etre les piles trop limites ? 
Comme quoi...

**Comment by Bernichou** [comment]
Bonjour,
De mon côté, depuis deux jours je n'ai plus aucun "inconnu" sur mon réseau .....mais je ne sais pas pourquoi !

**Comment by tcharp38** [comment]
Salut
Je ne sais que te dire.
j'avais moi meme un capteur qui faisait des siennes (il s'incluait sur une box mais pas sur l'autre) mais ca semble venir des piles. Etrange. En tout cas aucun souci de mon coté sur ce capteur.

**Comment by tcharp38** [comment]
@Bernichou 
Je clos le point mais a reouvrir si besoin.
Derniere stable = 210719-STABLE-1
