### ISSUE TITLE
Perte du réglage de l'affichage d'une commande après réinclusion

### ISSUE THREAD

**Issue by biscwii** [KiwiHC16/Abeille#2075]
Salut ! 

(Comme convenu, j'ouvre un post pour ce soucis)

J'ai plusieurs capteurs Xiaomi de porte, ainsi que des ampoules et prises Ikéa. J'ai associé leur commande état à un widget personnalisé avec des images que j'ai créé moi même, afin d'afficher le tout dans un design personnalisé.
Seulement, lorsque les objets se réannoncent (parfois spontanément, ou si je force leur réinclusion), la commande état à laquelle j'avais associé mon widget personnalisé reprend l'affichage par défaut.
L'affichage de la commande état d'une prise Ikéa:
<img width="571" alt="Capture d’écran 2021-07-08 à 17 45 07" src="https://user-images.githubusercontent.com/56394268/124953359-5d594a80-e015-11eb-9cab-c6e7abf1dca0.png">

Le réglage de l'affichage de la commande état:
<img width="571" alt="Capture d’écran 2021-07-08 à 17 44 33" src="https://user-images.githubusercontent.com/56394268/124953592-95f92400-e015-11eb-8e7a-e77eed9e6e84.png">

Après réinclusion : 
<img width="571" alt="Capture d’écran 2021-07-08 à 17 43 21" src="https://user-images.githubusercontent.com/56394268/124953698-a90bf400-e015-11eb-9f50-883b8f09db2e.png">

<img width="571" alt="Capture d’écran 2021-07-08 à 17 44 19" src="https://user-images.githubusercontent.com/56394268/124953784-b923d380-e015-11eb-916c-a642a857b447.png">

Avant, la configuration était retrouvé automatiquement. 

Merci d'avance !

**Comment by tcharp38** [comment]
j'ai besoin de + d 'infos.
Peux tu 
- Menu reglages/systeme/configuration
- puis _OS/DB
- Administration base de données: ouvrir
- Tu ajoutes "select * from cmd"
![image](https://user-images.githubusercontent.com/35221038/125042061-ba96df80-e099-11eb-9ae4-975c8de1347e.png)
- et tu me copies la ligne correspondant à ta commande

Avec ca j'espere pouvoir piger ou ca cloche.
Merci

**Comment by tcharp38** [comment]
Je crois que j'ai compris.

Tu peux confirmer le souci en modifiant le JSON de la commande "etat" (core/config/commands/etat.json)
- remets ton widget préféré pour la commande
- supprime la ligne "template": "light"
- et recharge le JSON via la page EQ/avancé

Ca ne devrait plus écraser ton choix.

**Comment by tcharp38** [comment]
Bon j'ai un souci pour corriger ca pour l'instant.
Je ne sais pas comment distinguer
- si il faut reprendre completement le fichier de config (reinit a partir du modele fourni)
- ou seulement faire une mise à jour partielle (et quoi)
- ou ne rien faire
A reflechir

**Comment by tcharp38** [comment]
Dans la 210709-BETA-3, j'ai appliqué la solution suivante
- pas de mise à jour du template si la commande n'est pas nouvelle.

**Comment by tcharp38** [comment]
Autre correctifs dans la 210715-BETA-1 (ecrasement icone & categorie)

**Comment by tcharp38** [comment]
210719-STABLE-1
A cloturer si ok

**Comment by tcharp38** [comment]
Ca doit etre ok. Je clos
