### ISSUE TITLE
Controleur bandeau LED TUYA (id TS0503B__TZ3000_i8l0nqdu) non reconnu

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2082]
Salutation !
J'ai commandé un controleur de LED RGB. Il est pas n'existe pas encore sur abeille.
https://fr.aliexpress.com/item/1005002548859056.html?spm=a2g0s.9042311.0.0.1da36c379hTxfI
Version RGB 4 Hole
![H65fc647db66940d68e1a2e3d222ac35cf](https://user-images.githubusercontent.com/49479084/125854854-87962e3c-52d3-47a6-9f2d-8b9af9f973a4.jpg)

Voila la ligne avec son petit nom : 
[2021-07-15 22:34:30] Abeille1, Type=004d/Device announce, Addr=A1C9, ExtAddr=CC86ECFFFE56AEC7, MACCapa=8E, Rejoin=00

Comme lors de mon dernier issue pour créer un nouvel objet, je suis dispo pour t'aider =)

Merci beaucoup =)

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6826119/AbeilleParser.log)

**Comment by Jake309** [comment]
J'ai vue que l'on a déjà : TS0505A de chez tuya
C'est une ampoule RGB+CCT, peut être qu'on peut récupérer une partie.

EDIT, dans ton json, c'est un ruban RGBW, surement encore plus facile. 
A creuser après une bonne nuit de sommeil =)

**Comment by tcharp38** [comment]
Voila de quoi tester

[TS503B__TZ3000_i8l0nqdu.zip](https://github.com/KiwiHC16/Abeille/files/6826349/TS503B__TZ3000_i8l0nqdu.zip)

- A decompresser dans core/config/devices
- redemarrer Abeille
- refaire une inclusion

**Comment by Jake309** [comment]
Salutation !
Merci, malheureusement, ca ne fonctionne pas.
Testé 2 fois, dont une ou j'ai aussi essayer de bidouiller un json en rajoutant manufacturer et model.
Mais non reconnue 

[TS503B__TZ3000_i8l0nqdu - copy.zip](https://github.com/KiwiHC16/Abeille/files/6832803/TS503B__TZ3000_i8l0nqdu.-.copy.zip)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/6832806/AbeilleParser.1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6832807/AbeilleParser.log)

**Comment by tcharp38** [comment]
As tu redemarré Abeille ?
Il devrait le reconnaitre.

Si decompréssé au bon endroit tu devrais avoir

core/config/device/TS0503B__TZ3000_i8l0nqdu/TS0503B__TZ3000_i8l0nqdu.json
Ce fichier n'est pris en compte qu'au demarrage d'Abeille.

Du coup t es sur de ca ?

**Comment by Jake309** [comment]
Oui oui, j'ai relancé le demon, activé désactivé le plugin, redémarré mon jeedom.

Je refais le test en redémarrant jeedom

![Capture](https://user-images.githubusercontent.com/49479084/125999341-92728dec-65c3-4a0d-89eb-7f7594eccfac.PNG)

**Comment by Jake309** [comment]
Je pense avoir trouvé !
Ton fichier s'appelle TS503B__TZ3000_i8l0nqdu idem le jsom et la 1ere ligne
alors que le device s'appelle : TS**0**503B__TZ3000_i8l0nqdu      TS(ZERO)530
Je reteste =)

**Comment by Jake309** [comment]
Alors ca a marché, mais je vois des pb : 
`2021-07-16 21:36:30 | Abeille | Erreur sur Abeille::deamon() : Call to a member function getId() on bool`
Il est tagué en OSRAM, je sais pas si c'est normale

![Capture](https://user-images.githubusercontent.com/49479084/126000903-b814119a-53b0-46fb-a9e1-4114a2dcad98.PNG)

 et je peux faire qu'un ON/OFF.

![Capture1](https://user-images.githubusercontent.com/49479084/126000984-e65af1ce-9b1f-4906-be24-03b18e83b836.PNG)
![Capture2](https://user-images.githubusercontent.com/49479084/126000987-716d8a7d-06af-4576-b8e6-693613d14a4f.PNG)

[AbeilleParser (2).log](https://github.com/KiwiHC16/Abeille/files/6833020/AbeilleParser.2.log)

**Comment by Jake309** [comment]
Dans l'équipement / avancé, quand je fais recharger le json, j'ai de nouveau l'erreur:
```
2021-07-16 21:47:02 | Abeille | Mise-à-jour de 'Abeille1-180' à partir de son fichier JSON
2021-07-16 21:47:02 | Abeille | Erreur sur Abeille::deamon() : Call to a member function getId() on bool
```

**Comment by Jake309** [comment]
J'ai refait une intégration propre, je pense que j'ai trop retiré de chose dans les précédents log.
en voila un propre.
il fini par s'appeler Abeille1-179 à la fin.
Dans le premier log que j'ai mis, ou il n'était pas reconnue, on avait ca :
```
[2021-07-15 22:34:30] Abeille1, Type=8043/Simple descriptor response, SQN=66, Status=00, Addr=A1C9, Length=1C, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0102/Color Dimmable Light, BitField=01
[2021-07-15 22:34:30]   InClusterCount=8
[2021-07-15 22:34:30]   InCluster=0000 => General-Basic
[2021-07-15 22:34:30]   InCluster=0003 => General-Identify
[2021-07-15 22:34:30]   InCluster=0004 => General-Groups
[2021-07-15 22:34:30]   InCluster=0005 => General-Scenes
[2021-07-15 22:34:30]   InCluster=0006 => General-On/Off
[2021-07-15 22:34:30]   InCluster=1000 => ZLL-Commissioning
[2021-07-15 22:34:30]   InCluster=0008 => General-Level Control
[2021-07-15 22:34:30]   InCluster=0300 => Lighting-Color Control
[2021-07-15 22:34:30]   OutClusterCount=00
[2021-07-15 22:34:30]   OutCluster=0019 => General-OTA
[2021-07-15 22:34:30]   OutCluster=000A => General-Time
```
Donc si je comprends bien, il voit au moins Lighting-Color Control, donc on pourrait créer ou il devrait créer la commande non ?!
La ou je ne suis pas assez calé, c'est que dans ton json, je ne vois pas de ligne style include300, est ce que ca pourrait venir de la ?

Merci pour le 1er essai en tout cas =) , n'oublie pas de rajouter le 0 la ou il faut =)

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6833115/AbeilleParser.log)

**Comment by tcharp38** [comment]
Salut @Jake309 
Bien vu pour le nom.
Peux tu maintenant basculer sur la derniere stable. Elle sera dispo demain.

Si pas déja fait passe les log de 500 à 5000 lignes (config Jeedom) PUIS redemarre Abeille.
Refais une inclusion.
Et file le package complet (drag & drop du fichier issu de la page support/telecharger tout).

Je pourrai voir ce qui se passe

Merci.

**Comment by Jake309** [comment]
Salut @tcharp38 
Merci pour le retour.
Voila le fichier.
Le meme message d'erreur et les meme commandes.
Uniquement la possibilité de ON/OFF.

Je jéterai un oeil sur le contenu du package ce soir, pour ma culture, c'est toujours intéressant et ca aide a comprendre, meme si trouver une info dans le parser c'est compliqué, alors la, ca doit etre pire xD

Merci

[AbeilleLogs-210719.tar.gz](https://github.com/KiwiHC16/Abeille/files/6840626/AbeilleLogs-210719.tar.gz)

**Comment by tcharp38** [comment]
Salut
Manque de pot il n'y a pas grand chose d'utilisable dans ce package. Tes logs sont trop courts
Ils sont limités a 500 lignes (config par defaut de Jeedom)

> [2021-07-16 22:09:52] Max atteint (490 lignes) Log précédent sauvé sous '/tmp/jeedom/Abeille/AbeilleParser-prev.log'

Peux tu passer à 5000 lignes, sauver, puis redemarrer Abeille ?
La tu peux retenter une inclusion et me redonner le package.
Merci

**Comment by Jake309** [comment]
Salut, 
Désolé pour ce long temps sans nouvelle...
En effet, j'ai trouvé la ligne à mettre à 5000, je me suis trompé avec celle de la timeline.
Voici les log

[AbeilleLogs-210818.tar.gz](https://github.com/KiwiHC16/Abeille/files/7007076/AbeilleLogs-210818.tar.gz)

**Comment by tcharp38** [comment]
Salut @Jake309 
Bon désolé tes logs ne montrent rien d'interessant. 
Par contre ils sont toujours limités à 500lignes. Peut etre n'as tu pas redemarré Abeille.

> Max atteint (490 lignes)

saurais tu tester une beta ?

**Comment by Jake309** [comment]
J'ai mis à 5000
![image](https://user-images.githubusercontent.com/49479084/130097334-26de9980-8298-4026-a89a-bf85d4d4f584.png)
et j'ai redémarrer jeedom complètement.
Tu penses que ca ne fonctionne pas ? il faudrait redémarrer abeille ? comment ? en désactivant et réactivant le plugin ?

Je peux refaire une manip en redémarrant abeille si tu m'explique comment faire, dans le doute =)

Oui, je peux tester une béta, je sais comment faire =)

**Comment by tcharp38** [comment]
Je ne sais pas pourquoi tes logs sont toujours limites à 500. Tu peux le voir avec un message comme ca au top d'AbeilleParser par ex:

> [2021-07-16 22:09:52] Max atteint (490 lignes) Log précédent sauvé sous '/tmp/jeedom/Abeille/AbeilleParser-prev.log'

Une beta est déja dispo. Si tu sais comment basculer dessus, tu vas ensuite sur l'équipement, page "avancé"
et tu ouvres l'assistant qui a fait qq progres.
puis tu lances une interrogation
![image](https://user-images.githubusercontent.com/35221038/130138854-7ceed6f7-0c14-46ac-ba11-515dbdcdf81a.png)

et me file le "discovery.log" que tu peux "telecharger"

**Comment by Jake309** [comment]
je n'arrive pas a rafraichir les end points, le json reste vide.
Je me demande si mon module est pas défaillant car une fois sur 2 il me fait galérer, soit a s'allumer, soit a se mettre en appairage ou autre :/
en tout cas, quand il est bien luné, l'interrogation ne donne rien :/

**Comment by tcharp38** [comment]
C est possible qu'il soit défaillant mais file moi un package de log juste apres avoir lancé l'interrogation des End Points.
Je vais voir si je trouve qqch

**Comment by Jake309** [comment]
[AbeilleLogs-210820.tar.gz](https://github.com/KiwiHC16/Abeille/files/7021688/AbeilleLogs-210820.tar.gz)

**Comment by Jake309** [comment]
je viens de voir, encore bloqué à 500 lignes ....
le plugin est pas en debug, peut etre pour ca que tu trouves rien j'y pense ....... (je suis con, tu peux le dire)

**Comment by tcharp38** [comment]
J'allais juste dire que je ne vois pas grand chose encore mais je vois quand meme des erreurs qui m'intriguent dans http.error

[Fri Aug 20 15:04:12.799527 2021] [php7:error] [pid 5198] [client 192.168.1.52:55810] PHP Fatal error:  Uncaught Error: Call to a member function running() on bool in /var/www/html/plugins/Abeille/core/class/AbeilleTools.class.php:1115\nStack trace:\n#0 /var/www/html/plugins/Abeille/core/class/Abeille.class.php(805): AbeilleTools::isAbeilleCronRunning()\n#1 /var/www/html/core/class/plugin.class.php(738): Abeille::deamon_info()\n#2 /var/www/html/core/ajax/plugin.ajax.php(98): plugin->deamon_info()\n#3 {main}\n  thrown in /var/www/html/plugins/Abeille/core/class/AbeilleTools.class.php on line 1115, referer: http://192.168.1.5/index.php?v=d&m=Abeille&p=Abeille&id=Abeille

Au final tu as basculé sur la beta ou tu es toujours sur la stable ?

**Comment by Jake309** [comment]
je suis sur la beta ;)

**Comment by tcharp38** [comment]
ok en dehors de ton souci si jamais tu vois des regressions, n hesite pas à creer un sujet associé. Je compte en faire une stable semaine prochaine sinon j'avance pas.

Sinon j'ai bien peur d'etre loin d'une connexion jusqu'a lundi soir et des ce soir alors ne sois pas surpris par le manque de retour.

**Comment by tcharp38** [comment]
Salut @Jake309 
Ou en est on sur ce sujet ? Je suis un peu perdu

**Comment by Jake309** [comment]
Salut @tcharp38 ,
Désolé de l'attente, je sors dune période de gros travaux à la maison. 
Mon module a l'air hs, j'arrive plus à le mettre en inclusion etc. 
Jai du acheter encore un déclasser des chinois...
Je pense pas que je vais en acheter un autre d'ici peu.
Si tu veux clore l'issue tu peux du coup. Comme tu le sens 
Merci ! Je continue à rester en bêta pour tester les versions ;)

**Comment by tcharp38** [comment]
Salut @Jake309 
Si tu as un package de logs montrant l'inclusion, n'hesite pas. Avant de dire qu'il est HS, peut etre qu'il y a un autre souci.

C'est cool que tu sois sur la beta. J'ai besoin de retours sur d'eventuelles regressions alors surtout n'hesite pas à me remonter tout souci.

**Comment by Jake309** [comment]
@tcharp38 Je viens de tenter une inclusion, et la tout fonctionne.
Ca met un peu de joie face au interrupteur qui vont plus ^^

Tu veux les log ou pas du coup ? J'étais pas en debug par contre :/

**Comment by tcharp38** [comment]
Cool mais qu'est ce qu'on cherche du coup si c'est bon ? Je te laisse refaire le point sur ce periph et on verra si la logs sont nécessaires
