### ISSUE TITLE
Ampoule YANDHI (id TS0505B__TZ3000_12sxjap4) non reconnu

### ISSUE THREAD

**Issue by yougospam** [KiwiHC16/Abeille#2087]
Bonjour,

J'ai fait l'acquisition un peu rapide de plusieurs ampoules "Yandhi" qui n'existent pas encore sur abeille 
https://fr.aliexpress.com/item/1005002721566009.html

YANDHI Intelligent E27 LUMIÈRE LED Ampoule Zigbee 3.0 rvb + W + C Dimmable Télécommande Tuya Smart Life Avec Alexa Google Maison Intelligente

![image](https://user-images.githubusercontent.com/70427451/126498800-8dc6053a-905e-4d30-8410-b909d1d2bcde.png)

Voici la log qui remonte lors de l'inclusion :

[2021-07-21 15:37:27] Abeille1, Type=8102/Attribut report, SQN=B0, Addr=5728, EP=01, ClustId=0403, AttrId=0010, AttrStatus=00, AttrDataType=29, AttrSize=0002

=> Est-ce la bonne log à transmettre ?

Est-ce possible d'intégrer ce modèle dans Abeille ?

En espérant que ces informations soient suffisantes, je reste à votre disposition.

Merci,
yougo

**Comment by tcharp38** [comment]
Salut @yougospam 
Il y a un truc experimental dans la derniere version stable.
Ton ampoule a du etre reconnue avec une config par defaut.
- Clique sur l'equipement correspondant
-  page "avancé"
- assistant EQ
- et essaie de faire remplir chacune des cases
- puis telecharger le "discovery.log" que tu posera ici par drag & drop

Merci

**Comment by yougospam** [comment]
Bonjour,

Voici ce que j'ai fait :

![image](https://user-images.githubusercontent.com/70427451/126575351-75bfca56-2572-48d3-bdc2-d7e0fac2bb38.png)

Puis : 

![image](https://user-images.githubusercontent.com/70427451/126575397-bcd24913-c13b-4a2f-aab8-7556aae94fa0.png)

Le fichier "discovery.json" contient la chaine de caractères suivante :

{"zgNb":1,"jId":163,"addr":"96BD","ieee":"60A423FFFE328BD9","epCount":0,"epList":[]}

Cordialement,
yougo

**Comment by tcharp38** [comment]
Il manque des tas d'infos.
Pour chaque champ vide peux tu interroger le reseau via le bouton ?
![image](https://user-images.githubusercontent.com/35221038/126604004-396ddfed-0bb4-4714-8a8a-d04092f260aa.png)

**Comment by yougospam** [comment]
Au temps pour moi, je n'avais pas compris que cela interrogeait l'équipement (et donc qu'il fallait qu'il soit allumé)

![image](https://user-images.githubusercontent.com/70427451/126623962-888c7093-796f-4a19-9a9f-38201dc14efd.png)


Le Json contient :
{"zgNb":1,"jId":162,"addr":"ED40","ieee":"60A423FFFE328D94","epCount":2,"epList":{"01":{"inClusters":{"1000":{"FFFD":1},"0000":{"0000":1,"0001":1,"0002":1,"0003":1,"0004":1,"0005":1,"0006":1,"0007":1,"FFDE":1,"FFFD":1,"FFFE":1,"FFE0":1,"FFE1":1,"FFE2":1,"FFE3":1},"0003":{"0000":1,"FFFD":1},"0004":{},"0005":{"0000":1,"0001":1,"0002":1,"0003":1,"0004":1,"FFFD":1},"0006":{},"0008":{},"0300":{"4001":1,"4010":1,"F000":1,"F003":1,"F004":1,"E000":1,"E100":1,"F102":1,"000F":1,"0000":1,"0001":1,"0003":1,"0004":1,"0007":1,"0008":1,"400A":1,"400B":1,"400C":1,"400D":1,"FFFD":1}},"outClusters":{"0019":{"0000":1,"0001":1,"0006":1,"FFFD":1},"000A":{"FFFD":1}}},"F2":{"inClusters":{"":{}},"outClusters":{"0021":{}}}}}

**Comment by yougospam** [comment]
Hello,

Je parviens à piloter l'ampoule avec les manipulations suivantes :
Création du dossier "TS0505B__TZ3000_12sxjap4"
Création du fichier "TS0505B__TZ3000_12sxjap4.json" dans le dossier créé
Ajout du json suivant dans le fichier :

```
{
  "TS0505B__TZ3000_12sxjap4": {
    "nameJeedom": "Yandhi Bulb",
    "manufacturer": "Tuya",
    "timeout": "60",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "icone": "TRADFRIbulbE27CWSopal600lm",
      "mainEP": "01"
    },
    "Commandes": {
      "include15": "getSWBuild",

      "include16": "Identify",

      "include25": "Group-Membership",

      "include6": "On",
      "include7": "Off",
      "include4": "etatLight",
      "include11": "getEtat",
      "include26": "BindToZigateEtat",
      "include28": "setReportEtat",

      "include11 2": "setLevel",
      "include5": "levelLight",
      "include12": "getLevel",
      "include27": "BindToZigateLevel",
      "include29": "setReportLevel",

      "include6 2": "colorX",
      "include7 2": "colorY",
      "include12 2": "Colour",
      "include13 2": "Blanc",
      "include14 2": "Bleu",
      "include15 2": "Rouge",
      "include16 2": "Vert",
      "include17 2": "getColorX",
      "include18 2": "getColorY",
      "include12 2 2": "ColourRGB",
      "include30": "setColourRGB",
      "include30 2": "setRGB",
      "include31": "colorRouge",
      "include32": "setRouge",
      "include33": "colorVert",
      "include34": "setVert",
      "include35": "colorBleu",
      "include36": "setBleu",
      "include38": "2700K",
      "include39": "5000K",
      "include40": "temperatureLight"
    }
  }
}
```

Le seul défaut trouvé pour l'instant est l'inefficacité du bouton "Blanc" pour remettre l'ampoule en blanc.
Il faut utiliser les boutons "2700K" pour de la lumière chaude et "5000K" pour de la lumière froide.

Ce n'est pas parfait mais cela répond à la majeure partie de mes besoins.

[TS0505B__TZ3000_12sxjap4.zip](https://github.com/KiwiHC16/Abeille/files/6861866/TS0505B__TZ3000_12sxjap4.zip)
yougo

**Comment by tcharp38** [comment]
Salut @yougospam 
Ton lien montre 6500K pour lumiere froide. Tu as essayé ?
![image](https://user-images.githubusercontent.com/35221038/126662715-6a2f52e6-9106-4246-842f-819aaacebb98.png)

Je ne comprends pas pourquoi "blanc" ne donne rien. Il ne declenche aucun changement c'est ca ?

**Comment by yougospam** [comment]
Hello,

Réponse tardive, veuillez m'en excuser.
Après de nouveaux tests, le bouton blanc fonctionne ou du moins il fait quelque chose; mais la lumière est bleutée. et non blanche.
Pour le 6500K, non je n'ai pas essayé, je ne sais pas comment faire :)

Dernier point, le pilotage de l'ampoule via Google SmartHome est assez déroutant, aucune couleur n'est correctement reconnue; mais c'est un autre combat.

Dans l'ensemble, l'ampoule fonctionne avec le fichier de config; mais des améliorations sont sûrement possibles.

yougo

**Comment by tcharp38** [comment]
Salut
Pas de soucis.
- pour le "blanc" qui ne donne pas la bonne couleur, j avoue que ce genre de controle n'est pas encore assez clair pour moi et je n'ai aucune ampoule de ce type pour tester
- pour le 6500, change la ligne "include39": "5000K", en "include39": "6500K", puis "recharger JSON" (page equipement/avancé)
- Enfin pour Google SH oui c 'est une autre histoire mais ne peut fonctionne correctement que si deja cote Abeille c'est carré.

**Comment by tcharp38** [comment]
Salut @yougospam 
Que fait on avec ce sujet ? Toujours interessé ?
On clos ? Besoin de revoir qqch ?
Merci

**Comment by tcharp38** [comment]
Vieux sujet sans vie.
Je le ferme mais a reouvrir si qqn est interessé.
