### ISSUE TITLE
Xiaomi Interrupteur simple - Doublon json au niveau du nom

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2088]
Hello,
J'ai bien reçu mon interrupteur simple et ca fonctionne bien ;)
[Xiaomi switch](https://www.amazon.fr/Xiaomi-Interrupteur-connect%C3%A9-Wireless-Switch/dp/B07X71ZS7J/)

Juste une remarque, il doit y avoir une coquille au niveau des json entre le "3AFE170100510001.json" qui est remonté et le sensor_switch.json" qui devrait être le bon ?? Il ont le même nom Jeedom : 
` "nameJeedom": "Xiaomi Interrupteur simple"`

Je m'explique : l'inclusion s'est bien passé et il m'a detecté le bon matériel "sensor_switch". Je le sais notamment grâce à la commande info "multi" qui est bien présente dans mon équipement. Et de plus plus l'icône affiché au départ est le bon.
Mais lorsque je vais sur l'équipement lui-même pour modifier le nom, il ne propose dans la liste que le "3AFE170100510001" et pas le "sensor_switch" car même nom ;)

A éclaircir ;)

Merci

**Comment by Xav-74** [comment]
A priori le "3AFE170100510001" correspond à "Konke Multi-function Button".
Donc il il y a bien un souci au niveau du nameJeedom pour ce modèle ;)

**Comment by tcharp38** [comment]
On dirait qu'on se trouve dans le cas ou l'identifiant se retrouve dans plusieurs produits

Si ton Xiaomi est identifié avec 3AFE170100510001
alors il y a aussi Konke multifunction key
voir : https://zigbee.blakadder.com/Konke_KPKEY.html

Bref raison de + pour ajouter me fabricant et le modele chaque fois dans le JSON pour savoir d'ou ca sort.

**Comment by tcharp38** [comment]
Ha oui donc tu as raison, le JSON 3AFE170100510001 est surement faux.
Je corrige

**Comment by Xav-74** [comment]
Merci !

**Comment by tcharp38** [comment]
Je te laisse verifier avec la 210722-BETA-1

**Comment by Xav-74** [comment]
Merci ! Je teste ca demain matin et te redis ;)

**Comment by nlhomme** [comment]
Bonjour,

S'agit-il des Aqara H1 (WS-EUK01)?
Parce que si oui j'ai déjà ouvert l'issue https://github.com/KiwiHC16/Abeille/issues/2054 pour discuter de leur prise en charge, et dans ce cas autant fermer le miens pour éviter les doublons

**Comment by tcharp38** [comment]
‌Salut

Non je ne crois pas.
Ton modele semble s'identifier encore differermment

http://zigbee.blakadder.com/Aqara_WS-EUK01.html‌

A+
 




De : "Nicolas Lhomme"
A : "KiwiHC16/Abeille" ,"Tcharp38" ,"Comment"
Envoyé: vendredi 23 Juillet 2021 16:06
Objet : Re: [KiwiHC16/Abeille] Xiaomi Interrupteur simple - Doublon json au niveau du nom (#2088)
 

 

Bonjour,

S'agit-il des Aqara H1 (WS-EUK01)?
Parce que si oui j'ai déjà ouvert l'issue #2054 pour discuter de leur prise en charge, et dans ce cas autant fermer le miens pour éviter les doublons

**Comment by Xav-74** [comment]
Retour à la normal ;) je clos.
Merci
