### ISSUE TITLE
Perte d'équipements suite aux mises à jour

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2090]
Salut @KiwiHC16 @tcharp38 

Je voulais vous joindre sur Slack, mais visiblement j'ai des soucis.
Je pense, sans certitude pour le moment, qu'à chaque mise à jour du master, je perds des équipements.
Cela fait, 2 ou 3 mises à jour successives où à chaque fois, quelques équipements disparaissent.
Je dois les inclure à nouveau.
N'ayant pas les logs, association MAJ = Perte d'équipements, je ne peux être catégorique.
La dernière mise à jour date de jeudi 22 ou vendredi 23 juillet. Je sais que j'ai encore des équipements sur piles à réinclure (perdus lors de la précédente mise à jour) mais je constate avoir perdu 5 autres éléments depuis jeudi. Ca c'est certain car j'ai fait la mise à jour en rentrant d'un déplacement et je suis sûr que je n'avais que 4 éléments injoignables au lieu de 9.
Je vais réinclure tout ce petit monde. Je verrai à la prochaine mise à jour. Je ne pense à un bug Abeille mais plutôt au processus de mise à jour qui impacte Abeille et la BDD. Soyons clair, je ne vois pas de lien entre maj Abeille et Zigate et équipements qui sortent du réseau. Mais bon, le constat est là.

**Comment by mickadam29** [comment]
Finalement, cette fois il a suffit de réveiller les équipements en timeout

**Comment by tcharp38** [comment]
Salut @mickadam29
La question qu'il reste est pourquoi tu as des équipements en timeout. Tu as une piste ? Ou ça ne te surprend pas ?
