### ISSUE TITLE
Support nouvelle generation Profalux: id=MOT-C1Z06C/10C

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2091]
Sujet initial: https://community.jeedom.com/t/appairage-profalux-zigbee/64789

**Comment by tcharp38** [comment]
[MOT-C1Z06C.zip](https://github.com/KiwiHC16/Abeille/files/6884275/MOT-C1Z06C.zip)

A tester.
- decompresser dans "Abeille/core/devices" (on doit avoir ..device/MOT-C1Z06C/MOT-C1Z06C.json)
- redemarrer Abeille
- relancer inclusion

Pour besoins de debug
- log Jeedom à passer de 500 à 5000 lignes
- drag & drop ici du package issu de la page support/telecharger tout

**Comment by TiTiPhoto** [comment]
j'avais quelques minutes mais pour le moment je n'arrive plus a voir de trace de prise en compte en inclusion, et le volet me fait des choses etranges (blocage lors de la manip), je fais des reinit dans la journée et reviens

**Comment by TiTiPhoto** [comment]
[20210727AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/6884627/20210727AbeilleParser.log)

ras j'avais pas vu ton deuxième message, voici au moins les log parser. Je regarde les autres infos pour tests ;)

**Comment by tcharp38** [comment]
Le fichier que je t'ai donné n'est pas pris en compte

**Comment by tcharp38** [comment]
Le fichier que je t'ai donné n'est pas pris en compte

> [2021-07-27 12:06:18]   ModelIdentifier='MOT-C1Z06C', trimmed='MOT-C1Z06C'
> [2021-07-27 12:06:18]   deviceUpdate('modelIdentifier', 'MOT-C1Z06C'), status=identifying
> [2021-07-27 12:06:18]   findJsonConfig(), manuf='Profalux', model='MOT-C1Z06C', loc=''
> [2021-07-27 12:06:18]   EQ is UNsupported. 'defaultUnknown' config will be used

Alors sois il n'est pas au bon endroit soit tu n'as pas redemarré Abeille.
Pour rappel tu dois avoir un fichier JSON la
...plugins/Abeille/core/devices/MOT-C1Z06C/MOT-C1Z06C.json

**Comment by TiTiPhoto** [comment]
C'est bien dans /plugins/Abeille/core/devices ? car je n'ai pas le dossier devices non plus, et si c'est le cas c'est bien avec un s, ou sans comme dans l'exemple ?

**Comment by tcharp38** [comment]
Ha zut, ma faute
core/config/devices...

**Comment by tcharp38** [comment]
Info: D'apres les infos du site Profalux, les nouveaux moteurs datent de **fevrier 2021**.

**Comment by TiTiPhoto** [comment]
[AbeilleLogs-210727.tar.zip](https://github.com/KiwiHC16/Abeille/files/6887172/AbeilleLogs-210727.tar.zip)

voila pour les logs après un ajout qui c'est passé sans que je mette la clé en inclusion, mais peut il restait une trace précédemment.

Les équipements sont bien créé correctement, mais les commandes ne passe pas.

**Comment by tcharp38** [comment]
Que veux tu dire par "les commandes ne passent pas" ?

**Comment by TiTiPhoto** [comment]
Que quand je fait monter ou descendre rien ne se passe

**Comment by tcharp38** [comment]
Ok. Peux tu essayer avec le JSON suivant ?
Tu n'as qu'a faire "recharger JSON" via la page de l'equipement/avancé

[MOT-C1Z06C.zip](https://github.com/KiwiHC16/Abeille/files/6887416/MOT-C1Z06C.zip)

**Comment by tcharp38** [comment]
Note interne: 3 EP dans l'ordre 02/F2 puis 01. Pourquoi ?

**Comment by TiTiPhoto** [comment]
> Ok. Peux tu essayer avec le JSON suivant ?
> Tu n'as qu'a faire "recharger JSON" via la page de l'equipement/avancé
> 
> [MOT-C1Z06C.zip](https://github.com/KiwiHC16/Abeille/files/6887416/MOT-C1Z06C.zip)

Pas mieux

**Comment by tcharp38** [comment]
tu peux me filer les logs ?

**Comment by TiTiPhoto** [comment]
[2AbeilleLogs-210727.tar.zip](https://github.com/KiwiHC16/Abeille/files/6887458/2AbeilleLogs-210727.tar.zip)

**Comment by tcharp38** [comment]
Je vois la meme requete, vers le EP (End Point) 01. Je m'attendais au EP 02.
Tu as bien écrasé le fichier precedent ?

Bon autre tactique, via les commandes de l'equipement.

![image](https://user-images.githubusercontent.com/35221038/127199148-bfa6f4d4-2f6b-4da7-a26e-69caea716504.png)

- Tu changes le EP=01 en EP=02
- puis sauvegarde
- puis tester

Le log AbeilleCmd (ou un extrait) suffira pour voir vers quel EP la commande est envoyée.
Ex:

> [2021-07-27 19:06:54] -- execute(eqName=Abeille1-273 name=Monter type=action, options=null)
> [2021-07-27 19:06:54] -- execute(): Msg sent: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/BD36\/setLevel","payload":"Level=100&duration=0000&EP=01"}}
>

**Comment by TiTiPhoto** [comment]
j'ai pas ton affichage avec les 3 champs de commande

**Comment by tcharp38** [comment]
Ha oui, donc juste en mode developpeur. Zut.
Tu peux l'activer temporairement (page de config, options avancées)

**Comment by TiTiPhoto** [comment]
Bon j'avais en effet du avoir un soucis de droit sur le premier remplacement. J'ai pu écraser de nouveau pour de bon

[2021-07-27 19:44:55] -- execute(eqName=Abeille1-273 name=Monter type=action, options={"utid":"0"})
[2021-07-27 19:44:55] -- execute(): Msg sent: {"topic":null,"payload":null,"priority":null,"message":{"topic":"CmdAbeille1\/BD36\/setLevel","payload":"Level=100&duration=0000&EP=02"}}
[2021-07-27 19:44:55] Message from queueKeyAbeilleToCmd: CmdAbeille1/BD36/setLevel -> Level=100&duration=0000&EP=02
[2021-07-27 19:44:55]   L2 - procmsg({"topic":"CmdAbeille1\/BD36\/setLevel","payload":"Level=100&duration=0000&EP=02","priority":1,"message":null})
[2021-07-27 19:44:55]     L1 - processCmd({"setLevel":"1","addressMode":"02","priority":1,"dest":"Abeille1","address":"BD36","destinationEndpoint":"02","Level":255,"duration":"0000"})
[2021-07-27 19:44:55]     NE n a pas repondu lors de precedente commande alors je mets la priorite au minimum.
[2021-07-27 19:44:55]       addCmdToQueue("Abeille1", cmd="0081", data="02BD36010201ff0000", addr=BD36, priority=5)
[2021-07-27 19:44:55]       incStatCmd(): {"0024":1,"0016":1,"0009":1,"0002":1,"0049":5,"0014":19,"0010":434,"0045":2,"0100":48,"0530":2,"0120":2,"0017":10,"0081":10,"0084":6}
[2021-07-27 19:44:55] Message from queueKeyCmdToCmd: TempoCmdAbeille1/BD36/ReadAttributeRequest&time=1627407897 -> EP=02&clusterId=0006&attributeId=0000
[2021-07-27 19:44:55]   L2 - procmsg({"topic":"TempoCmdAbeille1\/BD36\/ReadAttributeRequest&time=1627407897","payload":"EP=02&clusterId=0006&attributeId=0000","priority":4,"message":null})
[2021-07-27 19:44:55] processCmdQueueToZigate(zigate1)
[2021-07-27 19:44:55]   J'ai 1 commande(s) pour la zigate a envoyer.
[2021-07-27 19:44:55]   sendCmdToZigate(Dest=Abeille1, cmd=0081, len=0009, datas=02BD36010201ff0000)
[2021-07-27 19:44:55] Message from queueKeyCmdToCmd: TempoCmdAbeille1/BD36/ReadAttributeRequest&time=1627407898 -> EP=02&clusterId=0008&attributeId=0000
[2021-07-27 19:44:55]   L2 - procmsg({"topic":"TempoCmdAbeille1\/BD36\/ReadAttributeRequest&time=1627407898","payload":"EP=02&clusterId=0008&attributeId=0000","priority":4,"message":null})
[2021-07-27 19:44:55] Message from queueKeyCmdToCmd: TempoCmdAbeille1/BD36/ReadAttributeRequest&time=1627407897 -> EP=02&clusterId=0006&attributeId=0000
[2021-07-27 19:44:55]   L2 - procmsg({"topic":"TempoCmdAbeille1\/BD36\/ReadAttributeRequest&time=1627407897","payload":"EP=02&clusterId=0006&attributeId=0000","priority":4,"message":null})
[2021-07-27 19:44:55] Message from queueKeyCmdToCmd: TempoCmdAbeille1/BD36/ReadAttributeRequest&time=1627407898 -> EP=02&clusterId=0008&attributeId=0000
[2021-07-27 19:44:55]   L2 - procmsg({"topic":"TempoCmdAbeille1\/BD36\/ReadAttributeRequest&time=1627407898","payload":"EP=02&clusterId=0008&attributeId=0000","priority":4,"message":null})

**Comment by tcharp38** [comment]
Cette fois c'est bien vers le EP 02.
Mais j'imagine qu'il ne se passe toujours rien.
Peux tu me donner le log parser aussi pour voir le retour ?

**Comment by TiTiPhoto** [comment]
Tout a fait toujours rien

[AbeilleParser-3.log](https://github.com/KiwiHC16/Abeille/files/6887683/AbeilleParser-3.log)

**Comment by tcharp38** [comment]
Ca ne va pas etre simple ni immediat cette histoire. Je ne vois effectivement rien revenir du volet.
Sa telecommande fonctionne toujours ?
Quand tu l'actionnes, vois tu une info revenir via le parser.log ?

**Comment by TiTiPhoto** [comment]
Oui sa télécommande fonctionne et non rien dans le log.

Vu qu'il est revenu dans Jeedom de manière inhabituelle, je voulais quand meme le repasser correctement pour voir.

Une démarche particulière pour le sortir proprement, et pas uniquement en supprimant les équipements ?

**Comment by tcharp38** [comment]
pas besoin de le supprimer. Il doit etre reintegré.
Apres reinclusion pense à me coller le package complet ici.
Par contre je te previens que je serai off 1 semaine à partir de demain. Pas de reseau dans mon coin.

**Comment by TiTiPhoto** [comment]
Bon pour le moment pas moyen de réinclure faut que je jongle encore avec les réinit.

Je verrais ca dans la semaine et pas de soucis pour ta non dispo et deja merci beaucoup pour ta prise en compte

**Comment by TiTiPhoto** [comment]
[2200AbeilleLogs-210727.tar.zip](https://github.com/KiwiHC16/Abeille/files/6888432/2200AbeilleLogs-210727.tar.zip)

Et voila le package avec une nouvelle inclusion, qui m'a fait déconnecter la télécommande par contre...

**Comment by tcharp38** [comment]
Tiens une nouvelle mouture à essayer. Tu peux juste "recharger le JSON" puis tester On/off et On2/OFF2.

Penses à passer tes logs à 5000 lignes. Tu es toujours limité à 500. C est trop court.
Assures toi aussi de bien écraser le fichier par le zip ci apres.
Le chemin complet du fichier est: 
core/config/devices/MOT-C1Z06C/MOT-C1Z06C.json

[MOT-C1Z06C.zip](https://github.com/KiwiHC16/Abeille/files/6891451/MOT-C1Z06C.zip)

**Comment by TiTiPhoto** [comment]
Je testerais ce soir, pas chez moi aujourd'hui(mes logs sont bien à 5000)

**Comment by TiTiPhoto** [comment]
ca fonctionne sur monter/descendre et on/off(le 2 ko) mais ca vient c'est cool
Je te met les logs
[AbeilleLogs-210728.tar.zip](https://github.com/KiwiHC16/Abeille/files/6894712/AbeilleLogs-210728.tar.zip)

**Comment by TiTiPhoto** [comment]
Pas eu de soucis pour 3 des volets (tous sauf le volet maitre) en incluant bien les volet dans le reseau du maitre avant de l'ajouter à la zigate. Par contre le soucis est present pour ce dernier, il est bien repéré après réinitialisation complete. Mais sort en inconnu.

Les logs avec ma dernière tentative : 
[AbeilleLogs-210803.tar.zip](https://github.com/KiwiHC16/Abeille/files/6925961/AbeilleLogs-210803.tar.zip)

**Comment by pipiche38** [comment]
Peut-etre ais-je loupé un truc, mais la notion de volet maitre n'existe que si il n'y a pas de controleur ZigBee. Dans le cas présent il y a une ZiGate qui est le controleur Zigbee.

**Comment by TiTiPhoto** [comment]
Oui mais c'est pour expliquer ma démarche...et le fait est que c'est le seul que je ne peux pas encore intégrer

**Comment by tcharp38** [comment]
Incroyable !!
Je vois encore un autre identifiant: 'MOT-C1Z10C' et non plus 'MOT-C1Z06C'.
@TiTiPhoto tes volets sont tous du meme type ?
Est ce que celui à l'adresse Addr=9CF6, ExtAddr=20918A00000F999A, est different des autres ?

**Comment by tcharp38** [comment]
> ca fonctionne sur monter/descendre et on/off(le 2 ko) mais ca vient c'est cool
> Je te met les logs
> [AbeilleLogs-210728.tar.zip](https://github.com/KiwiHC16/Abeille/files/6894712/AbeilleLogs-210728.tar.zip)

Donc "monter/descendre" est ok.
Que donne le "seteLevel" ?
On/off etait juste la pour test.

**Comment by TiTiPhoto** [comment]
oui tout est ok. Le setLevel et getLevel est aussi ok.

**Comment by TiTiPhoto** [comment]
> Est ce que celui à l'adresse Addr=9CF6, ExtAddr=20918A00000F999A, est different des autres ?

Pas que je sache, les 4 étant sorti en meme temps des usines pour KparK. La seule difference est que c'est le plus grand(pour baie vitrée.

**Comment by tcharp38** [comment]
Ok. J'imagine alors qu'il y a un identifiant par puissance de moteur. Par hasard sais tu si c'est un 10NM alors que les autres plus petits sont des 06 NM ?

**Comment by tcharp38** [comment]
A tester pour la baie vitrée.
[MOT-C1Z10C.zip](https://github.com/KiwiHC16/Abeille/files/6946149/MOT-C1Z10C.zip)

A decompresser dans "core/config/devices"
puis redemarrer Abeille
puis refaire inclusion volet baie

**Comment by TiTiPhoto** [comment]
Je galère encore a faire la reinclusion proprement (j'ai le volet soit dans zigate soir la télécommande mais pas les deux)
Mais j'ai pu tester depuis Jeedom et pas de soucis pour les commande meme level

**Comment by tcharp38** [comment]
Je reviens juste de chez le frangin. Il est dans un cas ou l'installateur n'a pas su inclure controler tous les volets. On lui a installé 2 generations differentes, et le support Profalux n'a pas su resoudre le pb. Bref... il se peut qu'on galere un peu avec cette nouvelle generation. A priori la version des telecommandes aussi joue un role.

Dans tous les cas, focalise toi sur 1 volet et essaie de me filer le package de logs.

**Comment by TiTiPhoto** [comment]
Mon problème maintenant est que sur le dernier volet les 3 autres sont parfaitement ok. ET je sais que je peux l'inclure en gardant la télécommande comme c'était le cas avant que tu m'envoye le dernier json donc je désespère pas. Mais la nouvelle generation changeant aussi les méthodes de reset ce n'est pas simple

**Comment by TiTiPhoto** [comment]
La problématique qu'il me reste aujourd'hui est pas software mais bien hardware.

**Comment by tcharp38** [comment]
> Mon problème maintenant est que sur le dernier volet les 3 autres sont parfaitement ok. ET je sais que je peux l'inclure en gardant la télécommande comme c'était le cas avant que tu m'envoye le dernier json donc je désespère pas. Mais la nouvelle generation changeant aussi les méthodes de reset ce n'est pas simple

Tu peux me dire qu'elle est cette nouvelle methode de reset ?
Tu as un pdf ou un lien vers une doc ?

**Comment by TiTiPhoto** [comment]
Non aucun lien, rien de diffuser aujourd'hui par Profalux, mais suite au passage de mon installateur qui a eu le support profa, la ou il fallait laisser 5 sec avec le noir et le marron ensemble il faut laisser prêt d'une minute, le temps d'avoir deux arrêts d'aller retour et débrancher au debut du 3eme

**Comment by tcharp38** [comment]
Je ne comprends pas. Sur les nouveaux volets il y a toujours un noir à relier au marron ou plus du tout ?

**Comment by TiTiPhoto** [comment]
Oui toujours mais les temps ne sont plus les memes.

**Comment by tcharp38** [comment]
Donc donc la seule diff dans la procedure est 1min avec le noir & marron connectés ensemble au lieu de 5sec.
j'oublie qqch ?

Des que tu peux me filer des logs je jettes un oeil pour voir si j'en tire qqch.

**Comment by TiTiPhoto** [comment]
[AbeilleLogs-210808.tar.zip](https://github.com/KiwiHC16/Abeille/files/6951362/AbeilleLogs-210808.tar.zip)

Plus que le temps c'est d'attend la 3eme phase d'aller retour pour débrancher, et je ne sais pas si c'est la seule je ne fais qu'enchainer des choses a l'aveugle.

**Comment by tcharp38** [comment]
Je vois bien l'inclusion de la telecommande et du volet 10C.
Qqch fonctionne ou pas ?
De ce que je vois tu devrais pouvoir le controler mais le retour de niveau ne doit pas fonctionner. Je vois un bug de ce côté.
En ligne avec ca ?

Autre question: tu sais me dire si ce 10C est un moteur 10NM ? J'essaie de faire le lien entre les differebts identifiants.

**Comment by TiTiPhoto** [comment]
Comme je te l'ai dit tout est OK, pour le retour level je le récupère bien.
Le problème vient du fait que pour le moment je n'ai plus de lien avec la télécommande...c'est soit l'un soit l'autre mais j'arriverais a retrouver les deux.

Et non comme je te l'ai deja dit aussi je ne sais rien des puissance moteur.

**Comment by tcharp38** [comment]
Je cloture mais a reouvrir si soucis.
