### ISSUE TITLE
Ajout equipement GLEDOPTO CCT Zigbee Controller (GL-C-006)

### ISSUE THREAD

**Issue by OnyBagder** [KiwiHC16/Abeille#2092]
Bonjour,

Je souhaiterais ajouter un nouvel équipement/modèle.

Il s'agit du contrôleur WW/CW GLEDOPTO ref : GL-C-006 https://www.gledopto.eu/cct-controller-controller-zigbee-compatible
J'ai essayé de copier et modifier des .json d'autre contrôleur de la même marque mais je dois louper un truc...

J'ai utiliser l’assistant EQ mais sans grand succès.
Le résultat de discovery.json :
> {"zgNb":1,"jId":604,"addr":"8C4F","ieee":"00124B001D43CEAD","epCount":2,"epList":{"0B":{"inClusters":{"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"0300":{}},"outClusters":{"":{}}},"0D":{"inClusters":{"1000":{}},"outClusters":{"1000":{}}}}}

Et les erreurs remonter dans jeedom lors des clics pour "rafraichir" les infos :
![image](https://user-images.githubusercontent.com/60711319/127747544-40056821-7a6e-4d6b-b0d4-67af209c3a1a.png)

Si il faut d'autres infos/tests, n'hésitez pas à me demander, je ferais au mieux.

Cordialement

**Comment by tcharp38** [comment]
Salut @OnyBagder 
L'assistant n'en est qu'a ses balbutiements. Oublie le pour l'instant.

Peux tu
- t assurer de passer à 5000 lignes au lieu de 500 par defaut pour les logs
- mode debug
- redemarrer Abeille
- refaire une inclusion
- et faire un drag & drop ici du package issu de la page support/telecharger tout.
Merci

**Comment by tcharp38** [comment]
Une fois que tu as fait les manips ci dessus tu peux essayer le modele suivant:
[GL-C-006.zip](https://github.com/KiwiHC16/Abeille/files/6954856/GL-C-006.zip)

A décompresser dans core/config/devices/
puis redemarrer Abeille
et refaire une inclusion

**Comment by OnyBagder** [comment]
Bonjour,

Veuillez me pardonner de la réponse tardive.
Pour répondre à votre 1er message, je n'ai pas refais d'inclusion car après mettre absenté j'ai redémarré ma box domotique (et donc abeille) ce qui à eu pour effet de faire reconnaitre le GL-C-006.json que j'avais précédemment fais, enfin je pense...
Du coup j'ai un module qui fonctionne correctement sauf l'information de la température de blanc actuelle.
Je vous mets ici le .json que j'utilise actuellement (comparer au votre, j'avais juste retiré toute les lignes mentionnant de la couleur ou autres paramètres RGB).

[GL-C-006.zip](https://github.com/KiwiHC16/Abeille/files/6957052/GL-C-006.zip)

J'ai un deuxième module identique, je teste demain une inclusion avec et je posterai les infos demandé sur le premier poste pour étoffer le sujet.

Quoi qu'il en soit, merci pour vos réponses!

**Comment by OnyBagder** [comment]
Bonjour,

Voici le log du module.

[AbeilleLogs-210811.tar.gz](https://github.com/KiwiHC16/Abeille/files/6969786/AbeilleLogs-210811.tar.gz)

A peine branché déjà reconnue en temps que "GL-C-006 GLEDOPTO CCT Zigbee Controller" parce que déjà appairer lors de mes tests précédents et le .json à du faire son effet.
Dites moi si c'est bon pour vous.

Merci

**Comment by tcharp38** [comment]
Salut
Du coup tu peux 
- confirmer que le JSON que tu utilises est celui que tu m'as envoyé et non pas le mien
- me résumer la situation ? Ce qui fonctionne mais surtout ce qui ne fonctionne pas ou manque ?
Merci
Je ne vois rien de particulier dans les logs. Ca semble se dérouler correctement.

**Comment by OnyBagder** [comment]
Bonjour,

Alors je vous confirme que c'est le .json est celui que je vous ai envoyé.

Le résumé :

Lors de l'inclusion de ce module, Abeille ne le reconnaissais pas. Du coup j'ai regarder les équipements de la même marque qui était connu et compatible.
J'ai adapté un .json (celui du  GLEDOPTO contrôleur RGB) en enlevant tout ce qui me paraissait être dédié au RGB.
Je l'ai mis dans le plugin Abeille au bon endroit mais ça n'a pas marché.
Suite à un redémarrage, mon module à été reconnu directement et à l'air de bien fonctionner.

La seule chose qui ne fonctionne pas c'est l'info de la température de couleur actuel.

Dites moi si vous avez besoin de plus d'informations.

MercI

**Comment by tcharp38** [comment]
Ok donc je conserve ton JSON comme ref.
Peux tu décompresser le fichier suivant dans core/config/commands
[temperatureLight.zip](https://github.com/KiwiHC16/Abeille/files/6974305/temperatureLight.zip)

puis via la page EQ/avancé faire un "recharger JSON"

J'ai besoin au moins du log "Abeille" et tu peux verifier si l'info de couleur

**Comment by OnyBagder** [comment]
Le fichier temperatureLight.json existait déjà dans core/config/commands => je l'ai écraser pour le remplacer par le votre.
Pas de changement sur l'info de température de blanc et les autres commandes fonctionnent nominalement.

Voici le log Abeille après remplacement du fichier :
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/6976667/Abeille.txt)

**Comment by tcharp38** [comment]
Oui parfait l'ecrasement.

La commande "temperatureLight" semble etre corrigée comme il faut.
Il reste que je ne sais pas si elle doit etre remontée automatiquement.
Tu t'attends à quoi ? Une action avec setTemperature et un retour via "temperatureLight" ? C'est bien ca?

En supposant que c'est le cas j'ai ajouté la config du report automatique de la température.
A tester avec ce fichier
[GL-C-006.zip](https://github.com/KiwiHC16/Abeille/files/6977867/GL-C-006.zip)
Doit ecraser l'autre, dans core/config/devices/GL-C-006/

Une fois le fichier écrasé tu peux juste faire "reconfigurer" (page EQ/avancé)

**Comment by OnyBagder** [comment]
Bonjour,

Oui, c'est ça, normalement à chaque changement setTemperature l'info temperatureLight doit se mettre à jour automatiquement.

Je viens de tester avec le fichier envoyé, cela n'as pas changer le comportement.
J'ai écraser le fichier précédent, reconfigurer l'EQT et recharger le .json et redémarrer Abeille => pas de changement sur l'info temperatureLight.

En revanche, dans le log il y a cette ligne qui correspond à mon EQT :
> L'objet 'Abeille1/8C4F' existe mais pas la cmde '0300-0B-0007' => message ignoré [] []

Cela correspondrait-il avec cette ligne du .json du message précédent?
> "include-0300-7": "setReportLightColorSpectre"

**Comment by tcharp38** [comment]
Salut
Oui tu suis parfaitement. Ce sont bien les lignes en question mais on avance. Au moins le reporting est fait (le periph renvoi l'info).
Par contre elle est ignorée et je crois avoir trouvé.
Peux tu ecraser la commande setReportLightColorSpectre.json avec le fichier suivant
[setReportLightColorSpectre.zip](https://github.com/KiwiHC16/Abeille/files/6987666/setReportLightColorSpectre.zip)
puis soit refaire une inclusion soit faire "reconfigurer"

Ca doit faire disparaitre le message "L'objet 'Abeille1/8C4F' existe mais pas la cmde '0300-0B-0007' => message ignoré"

**Comment by OnyBagder** [comment]
Bonjour,

Alors j'ai tester le fichier envoyé et rien ne changeais.
La commande temperatureLight avais pour "Cmde Abeille/logicalId" la valeur "0300-01-0007".
Je l'ai changer en "0300-0B-0007" et cela fonctionne.
Je ne sais pas si la reconfiguration de l'EQT devais le faire en auto...

Quoi qu'il en soit pour le 1er EQT cela fonctionne normalement à présent.
Je vais supprimer le 2ieme module et le ré-inclure pour voir si le problème se reproduit avec un autre EQT.

Merci encore!

**Comment by tcharp38** [comment]
Oui c'est ca. Tu devrais avoir "0300-0B-0007".
La ligne suivante est la pour ca dans "temperatureLight.json".
         "logicalId": "0300-#EP#-0007"
Recharger JSON devrait faire le meme effet qu'une reinclusion pour ce souci.

Es tu pret à tester une beta pour chlore ce sujet ou tu preferes rester sur une stable ?

**Comment by OnyBagder** [comment]
J'ai de quoi sauvegarder ma VM avant de faire quoi que ce soit.
Tester une beta ne me dérange pas, au contraire si cela permet de fermer l'issue de manière positive !

**Comment by tcharp38** [comment]
Cool
La 210817-BETA-1 sera dispo demain sur le market ou de suite en direct sur GitHub.
Tu peux me faire tout retour sur une quelconque regression (donc pas seulement sur ce controlleur) avec des sujets separes STP.

**Comment by tcharp38** [comment]
@OnyBagder 
Il y a une stable dispo depuis. Tu me fais un résumé des soucis restants ?
Merci

**Comment by OnyBagder** [comment]
Yes, je viens d'installer la stable, pour le moment tout fonctionne et je n'ai rien remarqué de bizarre.

**Comment by tcharp38** [comment]
Tres bien mais je te laisse confirmer que tout est ok et on clos ce point.

**Comment by tcharp38** [comment]
@OnyBagder 
On peut cloturer le sujet ?

**Comment by tcharp38** [comment]
Pas de news. Je considere que c est ok. A reouvrir si besoin
