### ISSUE TITLE
Parser: AbeilleIEEE_Ok==0 => msg xxx ignored

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2093]
AbeilleSerial3 ok.

AbeilleParser:
```
[2021-08-02 19:45:24] Abeille1, Type=8010/Version, Appli=0003, SDK=031D
[2021-08-02 19:45:24] Abeille3, AbeilleIEEE_Ok==0 => msg 8010 ignored
[2021-08-02 19:45:24] Abeille5, Type=8010/Version, Appli=0003, SDK=031D
[2021-08-02 19:45:24] Abeille4, Type=8010/Version, Appli=0003, SDK=031D
[2021-08-02 19:45:24] Abeille2, Type=8010/Version, Appli=0003, SDK=031D
```

Je ne sais plus ce que c est que ce truc: AbeilleIEEE_Ok==0 qui fait quelle ne traite pas les infos.

**Comment by KiwiHC16** [comment]
```
Abeille/core/class/Abeille.class.php:        // AbeilleIEEE_Ok = -1 si la Zigate detectée n est pas la bonne
```

```
Abeille/core/class/AbeilleParser.class.php:                    parserLog('debug', $dest.', AbeilleIEEE_Ok==0 => msg '.$type." ignored");

```

**Comment by KiwiHC16** [comment]
/* To be sure there is no port changes, 'AbeilleIEEE_Ok' is set to 0 on daemon start.
               Should be updated by 8009 response */

**Comment by KiwiHC16** [comment]
Restart du daemon et tout est en ordre.

**Comment by tcharp38** [comment]
Ca n'est pas nouveau. C'est un pb que je rencontre de temps en temps et pas encore assez "propre".
Lié à l'ordre de démarrage des démons.

En l'occurence si par malheur "SerialRead" ne tourne pas encore lorsque l'interrogation du status réseau zigate est faite (8009), le parser reste dans un etat "en attente de validation addr IEEE zigate". Dans cet etat tous les messages sont ignorés.

**Comment by tcharp38** [comment]
Toujours à l etat de reflexion quant à trouver la meilleure methode, donc ce pb peut toujours apparaitre.

**Comment by tcharp38** [comment]
Correction dans 210827-BETA-1
L'astuce adoptée est de generer la requete "getNetworkStatus" à partir du parser lui meme et non plus à partir du démon principal.
Du coup il est impossible au parser de louper la reponse 8009.
Mieux. Si le parser devait etre redemarré seul, ce mecanisme fonctionne encore.

**Comment by tcharp38** [comment]
Revu à nouveau dans la 210903-BETA-1.
Je n'étais pas satisfait du résultat. Du coup encore + robuste.

**Comment by tcharp38** [comment]
Je crois que la solution est plutot bonne.
Je clos.
