### ISSUE TITLE
Actions inopérantes avec GL-B-008Z

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#2096]
Bonjour,

J'ai depuis plusieurs mois deux lampes Gledopto GL-B-008Z mais depuis 2-3 semaines, je n'arrive plus à les piloter. Tous les envois de commandes actions affichent un succès mais l'action n'est pas réalisée. Concernant les infos, je ne sais pas si celles qui remontent sont les valeurs à l'instant t ou sont les dernières valeurs connues.
Si je coupe l'alimentation de la lampe (ce que je suis obligé de faire car le on/off est ko), j'ai bien ce message qui s'affiche : [Dressing][Lampe Bulb]' s'est réannoncé. Mise-à-jour en cours. Ce qui me laisse penser que la lampe est toujours bien appairée à mon contrôleur.

Ma version d'Abeille est celle de Github, à jour de ce matin 11h15 environ.
Merci pour votre aide.

1/ Version (Abeille.version)
============================
210722-BETA-1

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031E

**Comment by tcharp38** [comment]
Salut @JC38 
Si jamais tu as une idée de ce qui a été changé depuis que ca ne fonctionne plus, ca pourrait aider.

Sinon je vois qu'il y a une commande ON ou OFF.
Peux tu tenter et me filer les logs ici ? (drag & drop du package page support/telecharger tout).
Merci

**Comment by JC38** [comment]
[AbeilleLogs-210809.tar.gz](https://github.com/KiwiHC16/Abeille/files/6952702/AbeilleLogs-210809.tar.gz)
Bonjour,
Je ne sais pas ce qui a changé, je suis sur le canal Github depuis plusieurs mois déjà, je sais que le problème est apparu en juillet et je crois que c'est la période où les changements ont été apportés aux fichiers json des devices. J'espère que les logs te donneront une piste.

**Comment by tcharp38** [comment]
Salut @JC38 
Comment s'appelle ton périph GL-B-008Z ? Ou quelle est son adresse ?

Penses à passer le nombre de lignes de log à 5000. 500 c'est trop peu.
A faire dans la config Jeedom: https://kiwihc16.github.io/AbeilleDoc/Debug.html?highlight=debug

**Comment by JC38** [comment]
Le nom du périphérique : cherche Lampe Bulb , il y en a 2 qui contiennent cette chaine dans leur nom.
Pour l'adresse, celle que je teste le plus a pour adresse 00124B00210F7F9F / En short  : D4C4
Je t'ai refait un package de logs
[AbeilleLogs-210809 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/6953298/AbeilleLogs-210809.1.tar.gz)

**Comment by tcharp38** [comment]
Ha je crois que j'ai merdé qq part.
Peux tu tester une reinclusion avec le modele attaché ?

[GL-B-008Z.zip](https://github.com/KiwiHC16/Abeille/files/6954785/GL-B-008Z.zip)
A decompresser dans "core/config/devices/GL-B-008Z/"

**Comment by JC38** [comment]
Bon, je n'ai pas réinclus la lampe. J'ai changé le fichier json, redémarré Abeille puis allumer la lampe.
J'ai testé le bouton Off et la lampe s'est éteinte ! J'ai testé les changements de couleurs et cela a fonctionné aussi.
Tu penses que je dois malgré tout refaire une exclusion/inclusion de la lampe ?
Pourrais-tu en quelques mots expliquer l'origine du pb?
Quand je passe dans cet écran, je ne devrais pas avoir des remontées d'infos ?
![image](https://user-images.githubusercontent.com/16527222/128725406-47127761-1db6-4d8a-b9d0-2ec5bccc6fba.png)

**Comment by tcharp38** [comment]
Ha mais tu es sur la branche master on dirait.

Bon ca ne change rien à ton souci. 

Coté explication, j'ai modifié pas mal de JSON mais j'ai du introduire une regression pour certains et ca tapait dans le mauvais "end point" (01 au lieu de 0B).
Tu le vois sur ton écran de l'assistant. 2 endpoints supportés: 0B & 0D mais pas 01.

L'écran de découverte est vraiment en phase de dev donc pas mature.
Dans tous les cas tu peux essayer chaque bouton "refresh" pour voir si d'autres infos remontent. Ceux que j'ai entouré la
![image](https://user-images.githubusercontent.com/35221038/128726497-eff169b0-8c81-4ecf-9beb-7900027207db.png)
Si tu as de nouvelles infos, je veux bien ton "discovery.log".

Enfin, tu n'as pas fait de reinclusion alors je soupconne que qq reports ne fonctionneront pas.
Je te laisse verifier et me dire si tu vois toujours une regression apres reinclusion si besoin.

**Comment by JC38** [comment]
Je l'avais écrit en début du sujet, je suis sur la "version du Github" :-(
Il faudrait peut-être revoir les infos clés car je pense que ça ne vous remonte pas quand on est sur la branche master de Github.
Sinon, les refresh ne donnent rien du tout.
Qu'appelles-tu reports ?
Les boutons reconfigurer ou recharger n'ont pas cet objectif de reproduire l'inclusion ?

**Comment by JC38** [comment]
Oups, ce matin, je n'ai plus rien qui fonctionne. Tout est en timeout ! Effet de bord ?
![image](https://user-images.githubusercontent.com/16527222/128824986-deee50cb-c56f-4e2d-917c-df261eb2a5ab.png)

**Comment by tcharp38** [comment]
Ta zigate (Zigbee Ruche) est en TIMEOUT. C'est la priorité. Ce qui veut dire qu'un (ou +) des démons ne tourne pas.
Regarde le log AbeilleParser, je soupconne qu'il te dit qu'il ignore des messages comme l'exemple ci apres:

> [2021-08-10 10:41:47] Abeille1, AbeilleIEEE_Ok==0 => msg 8002 ignored
> [2021-08-10 10:41:47] Abeille1, AbeilleIEEE_Ok==0 => msg 8102 ignored

Si c'est le cas alors redemarre Abeille. C'est un pb connu depuis un bail et pas trouvé encore la solution "propre".

**Comment by tcharp38** [comment]
> Je l'avais écrit en début du sujet, je suis sur la "version du Github" :-(

Désolé. Mais comme tout vient de Github et qu'il y a plusieurs branches, ca pourrait etre aussi une "beta" que le "master".
Dans tous les cas ca n'est pas prudent de rester sur le master. Cette branche est celle qui bouge le + donc on peut tomber sur un fonctionnement temporairement cassé.
Du coup maintenant que j'y pense l'assistant doit etre un peu en vrac. Je vais tacher de pousser mes dernieres updates et te faire faire des essais si tu veux bien.

> Il faudrait peut-être revoir les infos clés car je pense que ça ne vous remonte pas quand on est sur la branche master de Github.

Non car difficile d'identifier ca.

> Sinon, les refresh ne donnent rien du tout.
> Qu'appelles-tu reports ?

Le périphérique peut renvoyer lui meme des infos vers la zigate/jeedom mais ca se configure lors de l'inclusion.

> Les boutons reconfigurer ou recharger n'ont pas cet objectif de reproduire l'inclusion ?

Recharger permet de mettre à jour les commandes si changement
alors que reconfigurer va par ex configurer le periph pour qu'il reporte les infos voulues si besoin.

**Comment by JC38** [comment]
J'ai galéré pour faire repartir Abeille. J'ai enlevé, remis la clé plusieurs fois, j'ai aussi redémarré le daemon et même le PC.
Finalement, j'ai opté pour une solution + radicale, j'ai forcé la réinstall de la branche master et je suis donc avec le "mauvais" json pour la lampe. Et les commandes de la lampe fonctionne même si le endpoint est 01 dans le json, ça devient compliqué à suivre :-(
    "GL-B-008Z": {
        "timeout": "60",
        "configuration": {
            "mainEP": "01",
            "poll": "1",
            "icon": "GL-B-008Z"
        },

OK pour les essais, même un call et un partage d'écran si tu veux.

**Comment by tcharp38** [comment]
Master mis à jour.
Le dernier JSON y est.
Tu peux faire une mise à jour (d'ailleurs tu procedes comment ?) et refaire une inclusion ?

**Comment by JC38** [comment]
C'est chargé. La lampe fonctionne toujours.
je reviens plus tard pour faire un point.

**Comment by JC38** [comment]
Voici un screenshot de l'assistant découverte, j'ai cliqué sur tous les boutons de rafraichissement ainsi que le relire du fichier json dans la partie droite.
![image](https://user-images.githubusercontent.com/16527222/128869738-c9382162-ee04-4c59-9685-c3f86c422871.png)
Et j'ai fait la même chose avec une prise connectée sélectionnée au hasard
![image](https://user-images.githubusercontent.com/16527222/128870094-44bd48a3-f324-4db8-9906-85294330d7cc.png)

**Comment by tcharp38** [comment]
On dirait que l'interrogation de ton GL-B-008Z ne fonctionne pas. Zut.
Je ne sais pas pourquoi mais on peut proceder autrement.

- tu vires le modeles completement (detruit/enleve le JSON)
- tu redemarres Abeille
- relance une inclusion
- et donne le package de logs.

Merci

**Comment by JC38** [comment]
[AbeilleLogs-210811.tar.gz](https://github.com/KiwiHC16/Abeille/files/6966645/AbeilleLogs-210811.tar.gz)
Salut,
Voici les logs. J'ai fait les actions pour la lampe avec l'adresse 30E3. J'ai remis l'autre en place, c'est plus compliqué de tester du coup.

**Comment by tcharp38** [comment]
Salut
Si tu as refait  une inclusion est ce que cette fois tu es satisfait du controle de la lampe ?

Cote log il y a peu a en tirer. Tu n'est plus en mode "debug". Surement à cause de ta reinstallation qui a du te mettre en mode "defaut".

**Comment by JC38** [comment]
Je t'ai fait une série de captures d'écran pour des périphériques différents, car le pb n'est peut-être pas que sur le GL-B-008Z
![image](https://user-images.githubusercontent.com/16527222/128990714-7771b36d-cf48-44b6-abd3-4e272c991709.png)
![image](https://user-images.githubusercontent.com/16527222/128990763-489ac27d-9795-458f-bead-8bae2d9055ab.png)
![image](https://user-images.githubusercontent.com/16527222/128990797-5213f90f-6217-4aaf-b9ba-6dcf293d70de.png)
![image](https://user-images.githubusercontent.com/16527222/128990893-4609d6f7-ef28-439f-8b88-b4f7374b9738.png)
![image](https://user-images.githubusercontent.com/16527222/128990954-5d2ab7fe-2831-4b44-8a0e-b57cc6c58464.png)

**Comment by JC38** [comment]
Oui, le contrôle de la lampe est ok. Je viens de réactiver le debug au cas où tu veuilles des logs + tard.

**Comment by tcharp38** [comment]
Bon ok. Je te laisse confirmer que tout va bien dans les jours suivants et on peut clore ce sujet.
Ca te va ?

Coté assistant, 2 choses
- les equipements doivent etre reveillés pour etre interrogés. C'est normalement le cas de tout eq sur secteur mais pas sur batterie
- le rafraichissement à l ouverture de la page ne fonctionne pas tout le temps mais tu peux relancer la recherche via le bouton refresh à droite de "End points" (cas de Eclairage Cuisson)

**Comment by JC38** [comment]
Pour les interrogations, j'avais un seul équipement sur pile (un détecteur de fumées), tous les autres étaient sur secteur .
1 répéteur Ikea Tradfri
1 lampe Hue
1 contacteur BasicR3
1 lampe GU10
Et j'avais fait un refresh sur chacun.

Sinon, ok, on attend 1 jour ou 2 et on clôture le sujet spécifique à GL-B-008Z
