### ISSUE TITLE
Volant roulant, nouveau module à inclure.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2102]
Sur la base de:
https://faire-ca-soi-meme.fr/non-classe/2021/08/16/limportance-du-maillage-mesh-en-zigbee/

Inclure le module:
https://fr.aliexpress.com/item/1005002271454360.html?aff_fcid=1d82b17e4c1d4f11b553f0268cf46c9e-1629104372734-07441-_AFEPRS&tt=CPS_NORMAL&aff_fsk=_AFEPRS&aff_platform=shareComponent-detail&sk=_AFEPRS&aff_trace_key=1d82b17e4c1d4f11b553f0268cf46c9e-1629104372734-07441-_AFEPRS&terminal_id=19a2288f22e14039a7b5a47830c1e097

**Comment by tcharp38** [comment]
Il y a un autre sujet sur le support du module QS-Zigbee-C01.
Voir https://github.com/KiwiHC16/Abeille/issues/2169
Je cloture celui la
