### ISSUE TITLE
json GL-S-003Z ne fonctionne plus

### ISSUE THREAD

**Issue by skybone54** [KiwiHC16/Abeille#2104]
Bonjour,

La configuration "mainEP" : "0C"  ne fonctionne pas. "0B" fonctionne.

{
    "GL-S-003Z": {
        "manufacturer": "Gledopto",
        "model": "GL-C-003Z",
        "timeout": "60",
        "Comment": "GLEDOPTO RGBW GU10 5W 300lm",
        "configuration": {
            "mainEP": "0C",     ---> OB
            "poll": "1",
            "icon": "GL-S-003Z"
        },

Abeille 210817-BETA-1
Zigate USB

**Comment by tcharp38** [comment]
Salut @skybone54 
Tu es sur la derniere beta il me semble non ?
Si oui peux tu aller sur la page de l'equipement/avancé puis ouvrir l'assistant.
Essaie de faire remplir toutes les lignes en cliquant sur le bouton refresh correspondant
puis drap & drop discovery.log (telecharger) => a zipper pour ce forum

Merci

**Comment by skybone54** [comment]
Ok je fais ça. 
Par contre je vois GL-S et GL-C dans le json. Normal ?

**Comment by skybone54** [comment]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7037876/discovery.zip)

**Comment by tcharp38** [comment]
[GL-S-003Z.zip](https://github.com/KiwiHC16/Abeille/files/7038017/GL-S-003Z.zip)

Alors effectivement le end point est 0B, et j'ai aussi corrigé le nom du model "S" => "C"
Tu peux ecraser celui ci, redemarrer Abeille, et le reinclure ?

**Comment by tcharp38** [comment]
Par contre je ne m'explique pas pourquoi le "End Point" serait maintenant 0B.
Le fichier date de + de 2ans et depuis il a toujours été 0C alors a verifier mais peut etre qu'une version de FW du produit change ca ??

**Comment by skybone54** [comment]
Ok, je réinclurai les ampoules en rentrant du boulot.
Bizarre effectivement car j'ai les ampoules sur abeille depuis plus de 2 ans. Je vois pas trop comment le FW aurait pu être mis à jour.

**Comment by tcharp38** [comment]
Dans ce cas c etait un bug qui etait masqué jusque la mais qui est ressorti avec mes dernieres modifs.

**Comment by tcharp38** [comment]
@skybone54 
Tu me dis si on peut clore ce point depuis la 210824-STABLE-1 ?

**Comment by skybone54** [comment]
Oui ça a l'air de fonctionner correctement maintenant.
Merci

**Comment by tcharp38** [comment]
Ok je clos. A reouvrir si besoin
