### ISSUE TITLE
Support SPLZB-131

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2109]

**Comment by tcharp38** [comment]
@Chris-lal
J'imagine que tu es au moins sur la derniere stable.
- assure toi de passer les logs à 5000 au lieu de 500 (config Jeedom) + mode debug + redemarrer Abeille
- page equipement, clique sur ton device inconnu, puis avancé
- ouvrir assistant
- et essaie de faire en sorte que toutes les lignes soient remplies via les boutons de refresh associé
- et file moi le discovery.json à telecharger (zip + drap & drop ici)
Merci

**Comment by Chris-lal** [comment]
Hello Tcharp38,

Voila les nouveaux logs avec la limite a 5000 et le discovery.json. Je suis bien sur la dernière stable oui, j'ai d'ailleurs tout réinstallé from scratch il y a quelques semaines.

Merci pour ton temps. 
[AbeilleLogs-210828.tar.gz](https://github.com/KiwiHC16/Abeille/files/7069839/AbeilleLogs-210828.tar.gz)
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7069840/discovery.zip)

**Comment by tcharp38** [comment]
[SPLZB-131.zip](https://github.com/KiwiHC16/Abeille/files/7073258/SPLZB-131.zip)
Un premier jet a tester.
 A decompresser dans core/config/devices/SPLZB-131/
puis redemarrer Abeille
puis refaire une inclusion

**Comment by tcharp38** [comment]
Version prelim dans 210831-BETA-1

**Comment by tcharp38** [comment]
Salut @Chris-lal 
Ou en est on ?

**Comment by Chris-lal** [comment]
Hello tcharp38,

Ton package fonctionne correctement merci, toutes les informations sont remontées, les commandes fonctionnent !
il reste 2 choses en cours :
- la valeur RMSVoltage affiche par ex. 23682 V, donc j'imagine qu'elle devrait être divisée par 100.
- les valeurs RMSVoltage, RMSCurrent et ActivePower on tout l'air d'être pull via un cron à 1 min d'intervalle, est-ce qu'elle peuvent être maj dès leur changement comment la valeur état ?

**Comment by tcharp38** [comment]
[SPLZB-131.zip](https://github.com/KiwiHC16/Abeille/files/7196178/SPLZB-131.zip)

A tester pour verifier
- valeur RMS voltage
- et si on peut demander un reporting automatique (fournir le package de logs pendant inclusion). Appliqué sur "RMS current"

**Comment by tcharp38** [comment]
Salut @Chris-lal 
Des news ?

**Comment by Chris-lal** [comment]
Hello Tcharp38,

J'ai testé la nouvelle version, la division par 100 à fait son boulot et la valeur RMS voltage est OK maintenant :)
par contre pour le reporting, ça ne change pas de d'habitude. (Je précise que j'ai testé avec la dernière stable)

voilà le dernier package de logs :
[AbeilleLogs-211004.tar.gz](https://github.com/KiwiHC16/Abeille/files/7279714/AbeilleLogs-211004.tar.gz)

**Comment by tcharp38** [comment]
Salut.
Je ne vois pas la config du reporting dans ton log comme si le dernier JSON n'etait pas pris en compte

- Qq soit ta version il y a une nouvelle stable et une nouvelle beta alors realigne toi STP
- Redeclenche une inclusion ou "page EQ/avancé" tu fais reconfigurer
- et tu me files un package de logs

**Comment by Chris-lal** [comment]
Hello,

j'ai toujours le même résultat, la valeur continue de se mettre à jour toutes les minute.
j'ai MAJ en 211004-STABLE-1, supprimé proprement la prise, redémarré le service puis lancé une inclusion.j'ai aussi tenté le reconfigurer dans la page avancé. Tout ça plusieurs fois sans succès. 
je me suis assuré qu'il prenait bien la dernière version du JSON que tu m'a donné.

voilà les logs : 
[AbeilleLogs-211008.tar.gz](https://github.com/KiwiHC16/Abeille/files/7314034/AbeilleLogs-211008.tar.gz)

si tu vois autre chose que je peux tester dis-le moi.

**Comment by tcharp38** [comment]
Je vois bien la config de reporting cette fois mais il manque le bind.

[SPLZB-131.zip](https://github.com/KiwiHC16/Abeille/files/7314289/SPLZB-131.zip)
A tester, soit via reconfigurer soit via nouvelle inclusion.

**Comment by Chris-lal** [comment]
Yes ça fonctionne ! 

c'est top, tu pourrais le mettre sur Active power aussi ? Pour RMS Voltage je ne sais pas si c'est utile, peut-être que certaines personnes en on besoin.. ou pas.

**Comment by tcharp38** [comment]
[SPLZB-131.zip](https://github.com/KiwiHC16/Abeille/files/7316124/SPLZB-131.zip)

Voila le reporting activé sur les 3.
Du coup j'ai supprimé le polling.

Tu m'enverra un package de logs suite à ce test ?

**Comment by Chris-lal** [comment]
OK ça fonctionne pour les 3 valeurs :)
voilà le log:  [AbeilleLogs-211014.tar.gz](https://github.com/KiwiHC16/Abeille/files/7348637/AbeilleLogs-211014.tar.gz)
 
merci beaucoup pour le taf !

**Comment by tcharp38** [comment]
Je vois beaucoup trop de reporting donc a retravailler et du coup sujet pas clos.

**Comment by Chris-lal** [comment]
Hello Tcharp38,

est-ce que tu as besoin de quelque chose de mon coté pour ça ?

**Comment by tcharp38** [comment]
Non je crois que c'est à moi d te proposer un truc à tester avant. Je reviens vers toi

**Comment by tcharp38** [comment]
@Chris-lal 
Désolé pour mon silence.
Un autre modele à tester.
Refaire inclusion ou "reconfigurer".
[SPLZB-131.zip](https://github.com/KiwiHC16/Abeille/files/7676137/SPLZB-131.zip)

Et file moi le package de logs. J'espere que le reporting RMSVoltage ne sera pas aussi frequent.
Merci

**Comment by Chris-lal** [comment]
Hello @tcharp38,

pas de soucis, je suis un peu long de mon coté aussi.
Nouveau JSON appliqué sur l'une des deux prises que j'ai: d'après la vue temps réel elle à l'air de moins report qu'avant.
les logs : [AbeilleLogs-220104.tar.gz](https://github.com/KiwiHC16/Abeille/files/7808981/AbeilleLogs-220104.tar.gz)
Dis moi ce que tu en penses.

Et meilleurs voeux pour 2022 ;)

**Comment by tcharp38** [comment]
Salut
Tres bonne année à toi.

Bah non au vu du log on n'a pas progressé. Toujours un report plusieurs fois par sec, surement lié au fait que la tension ne reste pas pile poil 220V.

Peux tu via la page EQ/avancé interroger la config

![image](https://user-images.githubusercontent.com/35221038/148258788-96813366-619d-4d2e-a003-360abebd7ae3.png)

et me filer le log AbeilleParser + AbeilleSerialRead

**Comment by Chris-lal** [comment]
Hello, merci. 

Par aquis de concience j'ai reconfiguré l'autre prise avec le dernier JSON et j'ai vraiment l'impression que ça a réduit, je ne vois une MAJ de la valeur de RMSCurrent toutes les 40-50sec seulement. est-ce que le fait d'avoir fait une prise sur 2 aurait pas faussé les logs ?

Dans tous les cas j'ai aussi interrogé la config comme demandé.

Je te joint le package total de log si tu veux voir ce que ça donne avec les 2 prises up-to-date: 
[AbeilleLogs-220105 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7817982/AbeilleLogs-220105.1.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois pas l'interrogation en question.
En meme temps je vois que tes logs sont surchargés par la decouverte du MCCGQ14LM (sujet 2257).
On clos le 2257 d abord et on revient la dessus.

**Comment by tcharp38** [comment]
Salut @Chris-lal 
On fait quoi avec ce vieux sujet ?
Toujours interessé ?

**Comment by tcharp38** [comment]
Je clos cet antique sujet sans vie.
