### ISSUE TITLE
Problème d'inclusion Ikea Tradfri LED 470lm E14

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2111]
https://community.jeedom.com/t/ampoule-ikea-tradfri-led-470-lm-5-2w-e14-et-zigate/66500

**Comment by tcharp38** [comment]
@boosters
Une fois la mise à jour à d'Abeille faite, peux tu
- augmenter les lignes de log de 500 à 5000 (config jeedom)
- passer en mode debug (page de config Abeille)
- redemarrer Abeille
- refaire une inclusion de ton ampoule
- et faire un drag & drop du fichier issu de la page support/telecharger tout
Merci

**Comment by boxsters1423** [comment]
Salut @tcharp38  je vois ton message que maintenant voici le fichier demandé
[AbeilleLogs-210919.tar.gz](https://github.com/KiwiHC16/Abeille/files/7192178/AbeilleLogs-210919.tar.gz)
Merci à toi si je peux aider.

**Comment by boxsters1423** [comment]
Et j'ai le même problème avec l'ampoule TRADFRI bulb GU10 CWS 345lm en plus de la TRADFRI bulb E14 CWS 470lm précédente.

[AbeilleLogs-210919.tar-2.gz](https://github.com/KiwiHC16/Abeille/files/7192240/AbeilleLogs-210919.tar-2.gz)

Est-ce moi qui fait les choses de manière incorrecte ?

**Comment by boxsters1423** [comment]
Désolé mon pseudo était faux sur le forum de la communauté Jeedom. C'est corrigé maintenant. boxsters sur Jeedom et boxsters1423 ici ;-)

**Comment by tcharp38** [comment]
Salut
Peux via la page EQ/Avancé puis assistant EQ
faire en sorte que chaque ligne ai un retour (le bouton refresh passe au vert quand une reponse est reçue)
et me filer le discovery.log

Merci

**Comment by tcharp38** [comment]
Pour l'autre ampoule, je cree un sujet different.
https://github.com/KiwiHC16/Abeille/issues/2137

**Comment by boxsters1423** [comment]
> Salut
> Peux via la page EQ/Avancé puis assistant EQ
> faire en sorte que chaque ligne ai un retour (le bouton refresh passe au vert quand une reponse est reçue)
> et me filer le discovery.log
> 
> Merci

Salut @tcharp38 
Désolé mais c'est la première fois que je vais dans la partie avancé.
C'est quoi la page EQ/Avancé puis assistant EQ ? 
J'ai cherché sur le net et dans les pages de [documentation](https://kiwihc16.github.io/AbeilleDoc) mais j'ai rien trouvé qui correspond.
Par contre je veux bien apprendre et surtout aider si possible.

Merci pour l'autre sujet
À+

**Comment by tcharp38** [comment]
Salut
Pas de soucis.
C'est cette partie https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

**Comment by boxsters1423** [comment]
Salut @tcharp38 

Voici le discovery.log de la TRADFRIbulbE14CWS470lm trouvé dans l'assistant EQ

[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/7196743/discovery.json.zip)

J'espère que c'est ce dont tu as besoin.

Salutations,
boxsters

**Comment by tcharp38** [comment]
[TRADFRIbulbE14CWS470lm.zip](https://github.com/KiwiHC16/Abeille/files/7304978/TRADFRIbulbE14CWS470lm.zip)

A tester.

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Des news ?

**Comment by boxsters1423** [comment]
Impeccable 👍🏻
Merci 🙏

**Comment by tcharp38** [comment]
Cool.
Je cloture.
