### ISSUE TITLE
Impossible de réinclure les Répétiteurs Ikea

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#2120]
Salut
Je reviens de vacances et tous mes relais Ikea sont en timeout et donc tous les équipements liés. Par contre je n'arrive pas à les réinclure. Je met ma zigate en inclusion (31D) avec la dernière stable de jeedom et la 210824-STABLE-1 d'Abeille. J'appuie pendant 10s et rien ne se passe... Que puis je te donner comme information pour que tu puisses m'aider ?
Cordialement.

**Comment by sebfar9172** [comment]
Je viens de tester le beta du 02/09 mais ce n'est pas mieux

**Comment by sebfar9172** [comment]
J'essai Relais Salon


voici quelques logs
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/7107622/Abeille.txt)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7107613/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7107614/AbeilleCmd.log)

**Comment by sebfar9172** [comment]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/7107619/Abeille.txt)

**Comment by tcharp38** [comment]
Salut @sebfar9172 
S'il s'agit du 00047400007A282D je vois qu'il s'annonce à peu pres toutes les 10 à 11sec

> [2021-09-03 19:28:30] Abeille1, Type=004d/Device announce, Addr=0BF0, ExtAddr=00047400007A282D, MACCapa=8E, Rejoin=00


mais Abeille n'arrive pas à l 'interroger

> [2021-09-03 19:28:30] Abeille1, Type=8000/Status, Status=80/Unknown 80 status, SQN=00, PacketType=0045
> [2021-09-03 19:28:31] Abeille1, Type=8000/Status, Status=80/Unknown 80 status, SQN=00, PacketType=0045
> [2021-09-03 19:28:32] Abeille1, Type=8000/Status, Status=80/Unknown 80 status, SQN=00, PacketType=0045

A ce stade je ne sais que penser.
- un souci de saturation de ta zigate ?
- zigate corrompue ?
- ou un effet de bord avec un vieux pb d'Abeille...trop de messages envoyes en meme temps

Je penche pour la 3ieme option.
Note que tes logs n'ont que 290 lignes c'est beaucoup trop court. A augmenter dans la config Jeedom  à 5000 puis rebooter Abeille.

Autre point pour info il y a une beta du jour (210903-BETA-1) si tu veux basculer sur la "futur" stable mais honnetement je ne vois  pas en quoi elle améliorerait ton souci. Mais qui sait...
Je vais reflechir à cette situation.

**Comment by tcharp38** [comment]
Salut @sebfar9172 
Des news ? Ou en es tu ?

**Comment by sebfar9172** [comment]
Salut

J'ai réglé le soucis merci

**Comment by tcharp38** [comment]
Tu peux m'en dire + ? Comment as tu fait ?

**Comment by ChrisChrisChri** [comment]
Bonjour à tous,
Je me permets de venir sur ce sujet car depuis 1 semaine, je perds la totalité des EQ Ikea (Prise et lampe). Je fais l'inclusion, ca tient quelques heures puis de nouveau perte de la communication. Par ricochet, le maillage devient - bon et je perds alors d'autres équipements.

Sebfar9172, c'était quoi ton problème ?
Merci d'avance

**Comment by tcharp38** [comment]
@ChrisChrisChri 
Tu as des repeteurs Ikea aussi ?

**Comment by ChrisChrisChri** [comment]
Oui j'en ai 2 aussi mais je perds aussi les prises et lampes dont une prise qui se situe à 1 mètre de la Zigate d'où mon raisonnement que c'est le matériel IKEA qui serait devenu sensible à quelque chose.
Mes sondes de t° continuent de fonctionner ainsi que Legrand, Niko

**Comment by tcharp38** [comment]
Je n'ai pas de repeteur et je ne sais pas comment on declenche une inclusion mais si toi tu sais, je veux bien que tu me file un package de logs montrant une inclusion d'un repeteur.

**Comment by ChrisChrisChri** [comment]
Etrange Etrange. Il y avait très longtemps que je n'avais pas fait une inclusion pour des EQ IKEA. Je viens de le faire à l'instant pour le répéteur afin de t'envoyer les infos. Abeille ne le reconnait plus automatiquement. Ce serait peut-être pour cette raison que j'aurai un problème récurrent depuis 1 semaine ou 2 sur la totalité des EQ IKEA ?

[AbeilleLogs-211015.tar.gz](https://github.com/KiwiHC16/Abeille/files/7353248/AbeilleLogs-211015.tar.gz)

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7353258/discovery.zip)

**Comment by tcharp38** [comment]
@ChrisChrisChri 
Merci pour ton retour. Je vois un souci effectivement avec l'identifiant.
Je vais me renseigner pour que ca soit propre et je reviens vite.

**Comment by tcharp38** [comment]
Peux tu tester ca ?
[class.zip](https://github.com/KiwiHC16/Abeille/files/7354401/class.zip)
A decompresser dans core/class d'Abeille. Conserve les anciens fichiers au cas ou.

avec ce fichier
[TRADFRIsignalrepeater.zip](https://github.com/KiwiHC16/Abeille/files/7354416/TRADFRIsignalrepeater.zip)
a decompresser dans core/config/devices/TRADFRIsignalrepeater

puis 
- redemarrer Abeille
- refaire inclusion du repeater
- me filer les logs
Merci

**Comment by ChrisChrisChri** [comment]
Voici. 
Cette fois-ci, l'inclusion a marché.


[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7355108/discovery.zip)

[AbeilleLogs-211015.tar.gz](https://github.com/KiwiHC16/Abeille/files/7355113/AbeilleLogs-211015.tar.gz)

Merci

**Comment by tcharp38** [comment]
Ok le support d'un identifiant alternatif semble fonctionner

> [2021-10-15 19:40:00]   EQ is supported with 'TRADFRISignalRepeater' identifier
> [2021-10-15 19:40:00]   JSON id 'TRADFRIsignalrepeater', location 'Abeille'
> 

Ce periph s'identifie
- parfois en TRADFRISignalRepeater comme la
- ou TRADFRIsignalrepeater

**Comment by tcharp38** [comment]
Stable 211019-STABLE-1

@ChrisChrisChri
Une fois que tu as basculé sur la stable tu me confirmes que c est ok et on cloture ?

**Comment by tcharp38** [comment]
Je considere que c 'est bon mais a reouvrir si ca n'est toujours pas le cas.
