### ISSUE TITLE
Problème inclusion tout equipement, 210907-BETA-2

### ISSUE THREAD

**Issue by dams74** [KiwiHC16/Abeille#2125]
Salut
Un de mes volets avait perdu ses commande, j'ai donc voulu l'inclure de nouveau mais je n'y parviens pas.
Je n'avais pas changé le nom du volet mais j'ai fait quand même le test en resetant avec la télécommande mais rien à faire.
Ci joint mon log
j'ai une version beta à jour
merci
[AbeilleLogs-210908 (1).tar.gz.txt](https://github.com/KiwiHC16/Abeille/files/7130634/AbeilleLogs-210908.1.tar.gz.txt)
[AbeilleLogs-210908.tar.gz.txt](https://github.com/KiwiHC16/Abeille/files/7130652/AbeilleLogs-210908.tar.gz.txt)

**Comment by tcharp38** [comment]
Ok on dirait que j'ai cassé qqch sur la beta.
Je creuse.

Pour info tu n'as pas besoin de changer l'extension du package fourni. Le tar.gz est supporté sur ce forum et un simple drag & drop fonctionne. J'ai choisi cette extension pour ca.

Je check et reviens + tard

**Comment by tcharp38** [comment]
Pb compris: 210908-BETA-1

**Comment by dams74** [comment]
> Pb compris: 210908-BETA-1

OK j'attends la mise à jour et je test :-)

**Comment by tcharp38** [comment]
Note que je m'attends à ce qu'il reste un message d'erreur du style "commande Power-Source introuvable" mais ca ne doit pas etre bloquant.

**Comment by dams74** [comment]
J'ai fais la MAJ ce matin, la télécommande c'est bien inclus dans le réseau mais pas le volet
ci joint les logs
Merci
[AbeilleLogs-210910.tar.gz](https://github.com/KiwiHC16/Abeille/files/7141355/AbeilleLogs-210910.tar.gz)

**Comment by tcharp38** [comment]
Alors la je ne pige pas.
Je vois que le volet s'annonce

> [2021-09-10 06:51:02] Abeille1, Type=004d/Device announce, Addr=33FE, ExtAddr=20918A000000165B, MACCapa=8E
> [2021-09-10 06:51:02]   EQ new to parser
> [2021-09-10 06:51:02]   Requesting active end points list

mais il ne repond pas à la requete.

**Comment by dams74** [comment]
je referai ce soir une batterie de tests avec raz

**Comment by dams74** [comment]
une inclusion sans RAZ, l'inclusion ne fonctionne pas
[AbeilleLogs-210915.tar.gz](https://github.com/KiwiHC16/Abeille/files/7171375/AbeilleLogs-210915.tar.gz)
Avec RAZ l'inclusion fonctionne ! Nice Job
le log au cas ou
[AbeilleLogs-210915 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7171411/AbeilleLogs-210915.1.tar.gz)
Merci pour le travail réalisé :-)

**Comment by tcharp38** [comment]
Qu'entend tu par raz ?

**Comment by dams74** [comment]
La manipulation de remise à zéro de la télécommande par l'appui de 5x sur le bouton arrière R

**Comment by tcharp38** [comment]
OK donc raz volet.
Je vais jeter un œil aux logs au cas où, puis transformer la bêta en stable

**Comment by tcharp38** [comment]
la stable est faite.
On peut clore ce sujet ?

**Comment by dams74** [comment]
oui tout fonctionne parfaitement
