### ISSUE TITLE
ORVIBO CM10ZW multiples messages “s’est réannoncé. Mise à jour en cours”

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2132]
Sujet initial: https://community.jeedom.com/t/orvibo-cm10zw-multiples-messages-sest-reannonce-mise-a-jour-en-cours/67583

**Comment by StephaneG38** [comment]
Bonjour,
Ci-joint le fichier AbeilleParser comme demandé.
Merci pour ton aide !!
Stéphane
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/7182773/AbeilleParser.1.log)

**Comment by tcharp38** [comment]
Salut @StepG38 
Dans ton log je ne vois pas d'annonce d'Orbivo. Par contre j'en vois un paquet d'un capteur Xiaomi (00158D00035C2835).
Ca te parle ?

Pourra tu configurer Jeedom pour 5000 lignes de log au lieu de 500, sauver, redemarrer Abeille.

D'autre part j'ai l'impression que tu n'es pas à jour en terme de version Abeille. Je me trompe ?

**Comment by StephaneG38** [comment]
Salut @tcharp38 
Pour le capteur Xiaomi (00158D00035C2835) c'est en effet un capteur de température avec qui j'ai eu des problèmes car il sortait du réseaux très souvent. j'ai changé la pile et tout est rentré dans l'ordre.
Je viens de passer à 5000 lignes et ci-joint un nouveau fichier :  [AbeilleParser (2).log](https://github.com/KiwiHC16/Abeille/files/7187019/AbeilleParser.2.log)
Effectivement j'étais pas à jour : je viens de passer sur la version 2021-09-17 01:00:14, relancer les dépendances et le démon.
J'ai toujours les messages !!
Sinon le module fonctionne toujours très bien !



Merci par avance pour ton aide !

Stéphane

**Comment by tcharp38** [comment]
Je ne vois qu'une annonce dans ce log donc je ne peux rien en déduire.
Je cherche ce genre de truc

> [2021-09-17 18:17:21] Abeille1, Type=004d/Device announce, Addr=4FD6, ExtAddr=00124B00239EF372, MACCapa=8E

**Comment by StephaneG38** [comment]
Hello,
J'ai eu le même problème avec une télécommande 3 boutons loratap.
J'ai changé la pile et tout est revenu dans l'ordre.
Seulement la pas de pile ☹️ a changer.
Je peux essayer de le supprimer et de l'intégrer de nouveau ?
Stéphane

**Comment by StephaneG38** [comment]
Je t'envoie un nouveau fichié :
[AbeilleParser (3).log](https://github.com/KiwiHC16/Abeille/files/7189333/AbeilleParser.3.log)

**Comment by StephaneG38** [comment]
Question : a quoi sert les 3 switchs à coté du bouton reset ?

**Comment by StephaneG38** [comment]
Je viens de tester de supprimer puis réintégrer et j'ai toujours les messages.
Pour info les 3 swicths sont en bas pour que cela fonctionne

**Comment by tcharp38** [comment]
Pour clarifier la situation, une "annonce" de l'équipement (device announce) peut avoir lieu pour plusieurs raisons
- nouveau dans le reseau
- se reannonce parce qu'a nouveau alimenté et revient dans le reseau
- ou dans certains cas (si j'ai bien compris) de changement de topologie reseau ou d'adresse 

Bref c'est normal qu'il y en ai + ou -.

Maintenant peut etre qu'avec mes derniers changements ces messages ne sont plus masqués. Je vais reflechir à ca et soit reduire ces messages à certains cas, soit les supprimer.

En attendant tu peux "surveiller" l'equipement (page des equipements, selectionner Orvibo puis "surveiller"). Ca va te generer un "AbeilleMonitor.log" que tu me filera apres plusieurs annonces.

**Comment by StephaneG38** [comment]
Hello,
Désolé mais Je ne trouve pas pour surveiller l'équipement.
Quand tu dis page des équipement c'est bien dans le menu "Analyse" de Jeedom ?

**Comment by tcharp38** [comment]
Non, je parle de la page Abeille qui affiche les equipements.
Menu "plugins>Protocole domotique>Abeille"
La tu vas trouver ton eq et le bouton surveiller
![image](https://user-images.githubusercontent.com/35221038/133883848-c1597aa3-60a5-4897-bc25-42c0b05bf930.png)

**Comment by StephaneG38** [comment]
Oups !!
OK fait

**Comment by StephaneG38** [comment]
Ci-joint le fichier
[AbeilleMonitor.log](https://github.com/KiwiHC16/Abeille/files/7189679/AbeilleMonitor.log)

**Comment by tcharp38** [comment]
Tu as eu des annonces pendant ce temps ? J'ai regardé vite fait je ne vois pas de messages 004d

**Comment by StephaneG38** [comment]
Oui j'ai eu des annonces

**Comment by tcharp38** [comment]
Bon laisse tourner. Le log va grossir et d'ici demain tu me le file et tu me dis combien d annonces tu as eu

**Comment by StephaneG38** [comment]
Ok
Merci encore 😁

**Comment by StephaneG38** [comment]
Hello,
Ci-joint le fichier :
[AbeilleMonitor (1).log](https://github.com/KiwiHC16/Abeille/files/7191517/AbeilleMonitor.1.log)

J'ai 700 occurrences ce matin !
Merci pour ton aide
Stéphane

**Comment by tcharp38** [comment]
Ouah, 700 ?!
Il se comporte bizzarrement ce module. Autant d'annonc es n est pas normal.
Donc meme si on limite les annonces affichées, il reste un autre pb independant d'Abeille.

Dans l'immediat je ne vois toujours pas d'annonce dans le monitor. Du coup je soupconne un bug de ce cote.
Ces annonces doivent apparaitre dans le log AbeilleParser

**Comment by tcharp38** [comment]
Ok bug du monitor confirmé. Du coup la liste des 004D ne peut pas apparaitre. Je pousse une beta avec la correction.

**Comment by StephaneG38** [comment]
OK 
Du coup c'est mon module qui a un problème ?
J'ai pas tout suivi !
C'est quoi les 004D ?

**Comment by tcharp38** [comment]
Les messages 004D sont les message "device announce". Ce sont ceux que je cherche à voir, en particulier le champ "rejoin".

Mais dans tous les cas il y a beaucoup trop d'annonces. Comme si le module etait perturbé, perdait le reseau, revenait sans arret.

**Comment by tcharp38** [comment]
210919-BETA-1

**Comment by StephaneG38** [comment]
OK 
Comment faire pour installer ta beta ?

**Comment by tcharp38** [comment]
Elle sera dispo sur le market demain.
https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-standard

Tu dois avoir ce bouton "installer beta"
https://kiwihc16.github.io/AbeilleDoc/_images/InstallationMarket-3.png

**Comment by StephaneG38** [comment]
Ok
Merci beaucoup
Bon dimanche
Stéphane

**Comment by StephaneG38** [comment]
Hello,
Je viens d'installer la version Beta du Market : 2021-09-20 01:00:11 - Version Abeille :210919-BETA-1
Toujours les messages.
Ci-joint le fichier 
[AbeilleParser (4).log](https://github.com/KiwiHC16/Abeille/files/7200572/AbeilleParser.4.log)
Merci !
Stéphane
:

**Comment by StephaneG38** [comment]
Hello,
Je ne sais pas si c'est une coincidence mais ma telec Loratap 3 bouton ne fonctionne plus. Les timeTime se mettent à jour à chaque appui mais pas de changement d'état sur les 3 boutons. J'ai suppimé et recréé mais pareille
Désolé de t'embéter encore !!
Stéphane

**Comment by FabriceC38** [comment]
> Hello,
> Je viens d'installer la version Beta du Market : 2021-09-20 01:00:11 - Version Abeille :210919-BETA-1
> Toujours les messages.
> Ci-joint le fichier
> [AbeilleParser (4).log](https://github.com/KiwiHC16/Abeille/files/7200572/AbeilleParser.4.log)
> Merci !

Merci. Je vois effectivement plusieurs annonces
- [2021-09-21 07:49:27] Abeille1, Type=004d/Device announce, Addr=6AAE, ExtAddr=00124B00239EF372, MACCapa=8E
- [2021-09-21 07:51:48] Abeille1, Type=004d/Device announce, Addr=6AAE, ExtAddr=00124B00239EF372, MACCapa=8E
- [2021-09-21 07:54:16] Abeille1, Type=004d/Device announce, Addr=6AAE, ExtAddr=00124B00239EF372, MACCapa=8E
- [2021-09-21 07:56:18] Abeille1, Type=004d/Device announce, Addr=6AAE, ExtAddr=00124B00239EF372, MACCapa=8E

Je ne sais pas pourquoi il fait ca mais a priori ca n'est pas une annonce particuliere.
Je vais tacher de me renseigner et au pire, essayer de virer le message.

**Comment by FabriceC38** [comment]
> Hello,
> Je ne sais pas si c'est une coincidence mais ma telec Loratap 3 bouton ne fonctionne plus. Les timeTime se mettent à jour à chaque appui mais pas de changement d'état sur les 3 boutons. J'ai suppimé et recréé mais pareille
> Désolé de t'embéter encore !!
> Stéphane

Pas de soucis.
Ouvre un sujet séparé STP et file moi un package de logs en m'indiquant quel bouton tu presses et ce que tu attends. Je vais regarder

**Comment by StephaneG38** [comment]
Salut @FabriceC38 
Merci pour ton aide.
Je vais ouvrir un autre sujet pour la télécommande Loratap

**Comment by StephaneG38** [comment]
Sujet ouvert :
[https://github.com/KiwiHC16/Abeille/issues/2138](url)

**Comment by tcharp38** [comment]
Désolé pour le changement de pseudo. Je jongle entre 2 comptes.
Je vais retravailler les messages d'annonce pour les limiter. Je te tiens au jus

**Comment by StephaneG38** [comment]
Dac
Merci !!

**Comment by tcharp38** [comment]
Beta à tester: 210921-BETA-1
Dispo demain via le market

**Comment by StephaneG38** [comment]
Super merci !!

**Comment by StephaneG38** [comment]
Hello,
Je viens de mettre la 210921-BETA-3 et plus de messages !!!
Le module fonctionne parfaitement.
Grand merci @tcharp38 pour le temps passé et ta patience !
Stéphane

**Comment by tcharp38** [comment]
Ok mais attention... plus de messages ne veut pas dire qu'il ne passe pas son temps a refaire des annonces et ca je ne le comprends pas. A garder en tete si jamais il fait des siennes.

La beta est devenue stable, donc dispo sur le market demain.

Je te laisse clore ce sujet quand tu penses que tout est ok sur ce point.
A+

**Comment by StephaneG38** [comment]
Ok je le laisse tourner un peu pour voir avant de clôturer
Bonne soirée
Stéphane

**Comment by StephaneG38** [comment]
Hello,
Bon tout fonctionne encore et plus de messages !
Grand merci à toi @tcharp38 pour le temps passé et ton aide et surtout ta patience

**Comment by tcharp38** [comment]
Cool.
Je clos. A reouvrir si besoin.

**Comment by StephaneG38** [comment]
Très bien !!
Merci encore !

**Comment by jbromain** [comment]
Bonjour à tous,

Pour info, j'ai également ce module ORVIBO, qui marche très bien aussi, mais se ré-annonce toutes les 10 minutes tout pareil.

(Je n'ai pas encore tenté de mettre à jour le module pour masquer ce comportement)

Ca semble donc être un bug logiciel de l'équipement.

**Comment by tcharp38** [comment]
@StepG38 @jbromain 
Si l'un de vous sait mettre à jour ce module et montre un effet sur les annonces (ou autres), n'hesitez pas à partager l'info.
Merci
