### ISSUE TITLE
Moniteur de qualité d'air Aqara AAQS-S01

### ISSUE THREAD

**Issue by JC38** [KiwiHC16/Abeille#2135]
Bonjour,

Je sais que ce produit n'est pas encore supporté par Abeille mais néanmoins, j'ai profité d'une promo pour l'acheter.
S'il est possible de l'intégrer à Abeille et que vous ayez besoin d'infos depuis ma version de Jeedom, donnez-moi la marche à suivre svp.
Attention, je suis sur le canal Github pour le plugin
1/ Version (Abeille.version)
============================
210917-BETA-2

2/ Linux
========
["Debian GNU\/Linux 10 \\n \\l",""]
["Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU\/Linux"]

3/ Firmware
===========
Zigate 1: 031E

**Comment by JC38** [comment]
J'ai trouvé ceci dans le abeille discovery log :
`*** New equipement discovery
***
Network: Abeille1
IEEE: 54EF441000105E92
EP list: 01
Manufacturer: 'LUMI'
ModelId: 'airmonitor.acn01'
Location: ''
MAC capa: 84
8043/Simple descriptor response, SQN=8B, Status=00, Addr=5059, Length=16, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0302/Temperature Sensor, BitField=01
- InClusterCount=6
- InCluster=0000 => General-Basic
- InCluster=0003 => General-Identify
- InCluster=0402 => Measurement-Temperature
- InCluster=0405 => Measurement-Humidity
- InCluster=000C => General-Analog Input (Basic)
- InCluster=0001 => General-Power Config
- OutClusterCount=1
- OutCluster=0019 => General-OTA
- Clust 0001: 0020/0031/0033/0034/0035/0036/003E/FFFD
8043/Simple descriptor response, SQN=8B, Status=00, Addr=5059, Length=16, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0302/Temperature Sensor, BitField=01
- InClusterCount=6
- InCluster=0000 => General-Basic
- InCluster=0003 => General-Identify
- InCluster=0402 => Measurement-Temperature
- InCluster=0405 => Measurement-Humidity
- InCluster=000C => General-Analog Input (Basic)
- InCluster=0001 => General-Power Config
- OutClusterCount=1
- OutCluster=0019 => General-OTA
- Clust 0405: 0000/0001/0002/FFFD
- Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/0008/0009/000A/000B/4000/FFFD
- Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/0008/0009/000A/000B/4000/FFFD
- Clust 0003: 0000/FFFD`

**Comment by tcharp38** [comment]
Salut @JC38 
Peux tu
- cliquer sur ton equipement
- page avancé
- assistant EQ

et faire en sorte que les lignes soient remplies avant de me filer le discovery.json ?
Merci

**Comment by JC38** [comment]
Bonjour,

Malheureusement, l'assistant reste désespérément muet
![image](https://user-images.githubusercontent.com/16527222/134325857-22106bff-b680-4b51-8312-49fed9237193.png)

Je suis pas suffisamment compétent pour aider plus que ça, néanmoins, j'ai trouvé cette discussion qui peut peut-être aider :
[https://github.com/Koenkk/zigbee2mqtt/issues/6872](url)

**Comment by tcharp38** [comment]
Cote assistant tu as reveille ton capteur ? J'imagine qu'il est sur piles donc il s 'endort par defaut.

Sinon merci pour ton lien. Je vais tacher de faire un truc avec les infos du moment.

**Comment by tcharp38** [comment]
Voila un premier jet.
A decompresser dans "core/config/devices"
[airmonitor.acn01.zip](https://github.com/KiwiHC16/Abeille/files/7211874/airmonitor.acn01.zip)

et les commandes suivantes dans "core/config/commands"
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7211876/commands.zip)

puis
- redemarrer le démon Abeille 
- refaire une inclusion

Je n'ai couvert que le retour de batterie, la temp et l'humidite pour l instant

**Comment by JC38** [comment]
Bonjour,
Merci pour les fichiers. Malheureusement, rien ne remonte, l'appareil a bien été redécouvert.
J'ai trouvé au passage comment réveiller l'appareil, du coup, j'ai pu générer un fichier discovery en pj
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7219030/discovery.json.txt)
![image](https://user-images.githubusercontent.com/16527222/134542364-e3da3ae3-7516-4f3f-a7d3-3ea99665938c.png)

**Comment by tcharp38** [comment]
On va proceder par etapes.
Tu peux deja activer la surveillance en selectionnant ton equipement puis le bouton "surveiller". Tu me filera le log AbeilleMonitor au bout de qq heures pour voir si il y a eu des echanges.

**Comment by JC38** [comment]
Bonsoir,

Voici le log ainsi qu'un nouveau fichier json, j'ai mis à jour Abeille depuis Github avant de le générer, du coup, si des modifs ont été faites sur cet assistant récemment, elles sont prises en compte dans ma version.

[AbeilleMonitor.log](https://github.com/KiwiHC16/Abeille/files/7237940/AbeilleMonitor.log)
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7237941/discovery.json.txt)
 Et je viens de voir que des valeurs étaient remontées
![image](https://user-images.githubusercontent.com/16527222/134949556-6143bc73-f332-4195-a9bb-d2901e252ab6.png)
Elles ne me semblent pas juste, sachant qu'à cet instant (18h37), l'afficheur LCD du monteur donne 26,4°c et 58% d'humidité

**Comment by tcharp38** [comment]
Oui la temp et l'humidite sont clairement fausses.
Donc tu es sur le master de Github si je comprends bien. Donc sur la toute derniere version. Correct ?

Peux tu me filer un package de logs ?

**Comment by JC38** [comment]
Désolé, mais j'avais fait le package mais j'avais oublié de l'envoyer.
[AbeilleLogs-210928.tar.gz](https://github.com/KiwiHC16/Abeille/files/7259823/AbeilleLogs-210928.tar.gz)

**Comment by tcharp38** [comment]
Je ne sais pas retrouver ton periph dans ce package.  Je ne trouve ni l'adresse 22DA ni le nom "Abeille1-1352" :(

On va juste regarder la valeur remontée pour la temp
Peux tu
- cliquer sur "Get-Temperature" et immediatement reveiller ton periph
- et me fournir le package dans la foulée (au moins Abeille + AbeilleCmd.log + AbeilleParser.log)

D'ailleurs es tu sur la derniere beta (210929-BETA-1) ou sur la stable ?

**Comment by JC38** [comment]
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7261077/Abeille.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7261078/AbeilleCmd.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7261079/AbeilleParser.log)
[AbeilleParser-prev.log](https://github.com/KiwiHC16/Abeille/files/7261080/AbeilleParser-prev.log)
Je pense que les données sont remontées vers 18h27

**Comment by tcharp38** [comment]
Je vois que tu as fait un "Get-Humidity" à 18:27:29

> [2021-09-30 18:27:29] -- execute(eqName=Abeille1-1352 name=Get-Humidity type=action, options={"utid":"0"})

Mais absolument aucun retour du capteur. Tu as pensé à le reveiller juste apres la commande ?

 A noter que tes logs ne font que 500 lignes. Penser à mettre 5000 dans la config Jeedom et redemarrer le demon Abeille pour la prise en compte

**Comment by JC38** [comment]
Bonjour,
Désolé pour l'absence de retour récent mais j'ai malheureusement des pbs persos qui affectent mon quotidien, 
Je joins un nouveau discovery qui me semble plus riche que le précédent (dernière version Github)
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7317224/discovery.json.txt)
Et voici des logs avec + de lignes que les précédents
[Logs.zip](https://github.com/KiwiHC16/Abeille/files/7317231/Logs.zip)

.

**Comment by tcharp38** [comment]
Salut @JC38 
Pas de soucis. Si je relance si c'est juste pour essayer de donner une priorité aux soucis en cours.

A l'occasion peux tu
- via la page equipement/avancé
- demander la liste de binding 
![image](https://user-images.githubusercontent.com/35221038/136707165-56f0facc-9001-4583-a694-5cc649ca43c2.png)
- et me filer le log AbeilleParser suite à ca

On reprendra quand tu aura un peu + de temps

**Comment by JC38** [comment]
Bonjour,

Je n'arrive pas à avoir les infos qui remontent. Le capteur est en timeout dans Abeille depuis 1 semaine et pas moyen de le voir réapparaitre. Je le réveille, mais rien ne remonte.
Pour moi, il est bien connecté au réseau si je me fis à la doc Aqara : [https://www.aqara.com/userfiles/fileupload/202107/1417788462604132354.pdf](url)
![image](https://user-images.githubusercontent.com/16527222/137633552-e1dba3c3-841c-4628-b050-a21a0fcac685.png)

**Comment by JC38** [comment]
Bon, je suis arrivé à le récupérer en l'excluant puis en le redécouvrant.
J'ai essayé quelques manip (get temp + get humidity), la temp et l'humidité semblent ok
J'ai aussi interrogé la table de binding et récupéré le log en pj
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/7360240/AbeilleParser.1.log)

**Comment by tcharp38** [comment]
Donc le reporting et l'affichage de temp & humidité semblent ok. Tu confirmes ?
Est ce que le retour de batterie est fonctionnel aussi ?

**Comment by tcharp38** [comment]
Je clos.
Suite dans le #2279
