### ISSUE TITLE
Ajout support TRADFRI bulb GU10 CWS 345lm

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2137]

**Comment by tcharp38** [comment]
Meme requete

Salut
Peux via la page EQ/Avancé puis assistant EQ
faire en sorte que chaque ligne ai un retour (le bouton refresh passe au vert quand une reponse est reçue)
et me filer le discovery.log

Merci

**Comment by boxsters1423** [comment]
Et voici le discovery.json pour la TRADFRIbulbGU10CWS345lm

[discovery.json.TRADFRIbulbGU10CWS345lm.zip](https://github.com/KiwiHC16/Abeille/files/7196801/discovery.json.TRADFRIbulbGU10CWS345lm.zip)

Salutations,
boxsters

**Comment by tcharp38** [comment]
[TRADFRIbulbGU10CWS345lm.zip](https://github.com/KiwiHC16/Abeille/files/7217632/TRADFRIbulbGU10CWS345lm.zip)

On fait un test avec ca ?

A decompresser dans core/config/devices/TRADFRIbulbGU10CWS345lm
puis redemarrer demon
puis refaire inclusion

Je laisse l'autre model de cote pour l'instant

**Comment by boxsters1423** [comment]
C'est parti mon kiki 😁

**Comment by boxsters1423** [comment]
J'ai décompressé dans le répertoire TRADFRIbulbGU10CWS345lm

![TinyTake_23-09-2021-15-26-13](https://user-images.githubusercontent.com/33317024/134515490-0f1874b4-a705-4cfe-9d31-2896bf47d0d7.png)

Mais j'ai ces messages dans le log Jeedom. 

[2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentHue.json' n'existe pas.
[2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentSaturation.json' n'existe pas.
[2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentX.json' n'existe pas.
[2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentY.json' n'existe pas.
[2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-ColorMode.json' n'existe pas.

J'ai l'impression qu'il me manque certains fichiers de base.

L'ampoule apparaît néanmoins dans mon réseau abeille.

**Comment by boxsters1423** [comment]
J'ai bien l'ampoule par contre il n'y a pas de gestion des couleurs c'est normal ?

![TinyTake_23-09-2021-15-32-00](https://user-images.githubusercontent.com/33317024/134516549-6f73ad8b-4081-4be7-b11a-09c461c5d4c6.png)
![TinyTake_23-09-2021-15-33-59](https://user-images.githubusercontent.com/33317024/134516577-9496dc09-46ba-4072-94ce-125af4882979.png)

**Comment by tcharp38** [comment]
> [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentHue.json' n'existe pas.
> [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentSaturation.json' n'existe pas.
> [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentX.json' n'existe pas.
> [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentY.json' n'existe pas.
> [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-ColorMode.json' n'existe pas.

Ooops.
Voila les nouvelles commandes pour "core/config/commands"
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7218073/commands.zip)

**Comment by boxsters1423** [comment]
![image](https://user-images.githubusercontent.com/33317024/134518354-200f0013-5008-4442-8082-9969f2fc9918.jpeg)

**Comment by boxsters1423** [comment]
> > [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentHue.json' n'existe pas.
> > [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentSaturation.json' n'existe pas.
> > [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentX.json' n'existe pas.
> > [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-CurrentY.json' n'existe pas.
> > [2021-09-23 15:18:42][ERROR] : Le fichier de commande 'zb-0300-ColorMode.json' n'existe pas.
> 
> Ooops.
> Voila les nouvelles commandes pour "core/config/commands"
> [commands.zip](https://github.com/KiwiHC16/Abeille/files/7218073/commands.zip)

Parfait les messages du log Jeedom ont disparu.

**Comment by tcharp38** [comment]
Du coup tu as des commandes en + non ?

**Comment by boxsters1423** [comment]
Non rien de plus et ça ne réponds plus. Avant j'avais une réponse pour SWBuild par exemple et la lampe répondait aux commandes. Je ne sais pas quel log pourrait aider.

[AbeilleLogs-210923.tar.gz](https://github.com/KiwiHC16/Abeille/files/7218482/AbeilleLogs-210923.tar.gz)

**Comment by tcharp38** [comment]
As tu redemarrer le demon apres ajout des nouvelles commandes ?

**Comment by boxsters1423** [comment]
Oui j'ai même refait l'inclusion

**Comment by tcharp38** [comment]
Ok trouvé un bug
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/7218750/Abeille.class.php.zip)

A decompresser dans core/class
puis redemarrer Abeille
et refaire inclusion STP.

**Comment by tcharp38** [comment]
Etat actuel dans la 210923-BETA-1

**Comment by boxsters1423** [comment]
Cette fois ça y est ✅

![TinyTake_24-09-2021-13-24-10](https://user-images.githubusercontent.com/33317024/134666754-3489247a-9594-4510-aa35-3f82b0434853.png)

J'ai mis à jour le plugin Abeille et j'ai ces différences.

![TinyTake_24-09-2021-13-25-48](https://user-images.githubusercontent.com/33317024/134666957-2b4c8958-dc1e-4f89-999d-78c39ccadf47.png)

![TinyTake_24-09-2021-13-28-12](https://user-images.githubusercontent.com/33317024/134667228-5937a933-c35c-45b0-87d2-e73b36bc75a9.png)

Alors j'ai édité la classe et j'ai laissé le test :  _if ($cmdPointeur_Value)_ car ça me paraissait plus sûr.
Le test 'none' c'est mieux alors je le garde 😁

Pour moi on peut fusionner la modification dans la branche.

**Comment by boxsters1423** [comment]
En fait le test _if ($cmdPointeur_Value)_ est déjà dans la branche master par contre le _none_ est pas dans la master.

**Comment by tcharp38** [comment]
Tu es directement sur le master ?
Si oui alors rien à modifier n'est ce pas ?
Du coup quel est le status ?

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Des news ?

**Comment by boxsters1423** [comment]
Désolé @tcharp38 pour moi tout semble ok ✅

**Comment by tcharp38** [comment]
Ha ok.
Du coup on peut clore et passer se focaliser sur le modele 470lm ?

**Comment by boxsters1423** [comment]
Oui je crois bien. Au pire je rouvrirai cette issue. Tu as fait le merge ?

**Comment by tcharp38** [comment]
Tout est dans la derniere beta. Je vais la basculer en stable dimanche, donc dispo lundi.
On peut refaire le point apres si tu veux.

**Comment by boxsters1423** [comment]
Oui parfait 👍

**Comment by tcharp38** [comment]
Bon je viens juste de creer une stable donc dispo demain.
Tu bascules dessus et on fait le point ?

**Comment by boxsters1423** [comment]
ça marche j'essaie demain 👍

**Comment by tcharp38** [comment]
@boxsters1423 
Des news ?

**Comment by boxsters1423** [comment]
Elles s'affichent comme TRADFRIbulbE14CWSopal600lm mais ça marche...

![TinyTake_07-10-2021-14-49-19](https://user-images.githubusercontent.com/33317024/136387255-0f2d6f62-e80f-44f0-8fdc-6e909ebf0c39.png)

**Comment by tcharp38** [comment]
L'affichage dont tu parles n'est que l'icone utilisée (et non pas un nom ou type) mais ca ne doit pas etre affiché normalement n'est ce pas ?

Je corrige avec un autre modele GU10 (node_IkeaTradfriBulbGU10W400lm) mais si tu trouves mieux, format PNG, fond transparent je prends.

**Comment by boxsters1423** [comment]
Tu as (toujours) 😉 raison le nom affiché pour le JSON est bien GU10

![image](https://user-images.githubusercontent.com/33317024/136414724-dc388911-d2b9-4f30-9045-262c6101d0d6.jpeg)

**Comment by tcharp38** [comment]
Ouf.. sinon je sechais

**Comment by tcharp38** [comment]
@boxsters1423 
Au final tout est bon ? On peut cloturer ce sujet ?

**Comment by boxsters1423** [comment]
Oui c'est tout bon 👍

**Comment by boxsters1423** [comment]
Merci beaucoup 🙏

**Comment by tcharp38** [comment]
Cool. 1 de moins : )
Je clos
