### ISSUE TITLE
Télécommande LORATAP 3 boutons ne fonctionne plus

### ISSUE THREAD

**Issue by StephaneG38** [KiwiHC16/Abeille#2138]
Bonjour,
Ma télécommande LORATAP 3 bouton ne fonctionne plus.
Quand j'appuie sur les boutons, pas de changement d'état et mes scénarios ne sont plus lancés.
Par contre le Time-Time réagit bien à chaque impulsion sur les 3 boutons.
Ci-joint mes logs Abeille

Merci par avance !
Stéphane
[Log Abeille.zip](https://github.com/KiwiHC16/Abeille/files/7202130/Log.Abeille.zip)

**Comment by tcharp38** [comment]
Quel est l'identifiant zigbee de cette telecommande ? (equipement/avancé/fichier JSON)

**Comment by StephaneG38** [comment]
C'est : TS0043__TZ3000_bi6lpsew

**Comment by tcharp38** [comment]
Ha oui ?!
Je ne me souviens pas avoir touché ce modele mais il est ultra simple.
Peux tu me fournir un discovery.json du coup ? Attention, comme c'est une telecommande, donc sur piles, il te faut la reveiller regulierement jusqu'a avoir toutes les reponses.

**Comment by tcharp38** [comment]
Au fait tes logs sont limites à 500lignes. Passe à 5000 STP et redemarre Abeille.

**Comment by StephaneG38** [comment]
Voici :
[discovery.txt](https://github.com/KiwiHC16/Abeille/files/7202621/discovery.txt)

**Comment by tcharp38** [comment]
Ha, tout n'est probablement pas passé au vert mais ca le fait.
j'ai trouvé ma regression qui t'impacte.

**Comment by tcharp38** [comment]
En passant, y a t'il une reference fabricant ou modele ?

**Comment by StephaneG38** [comment]
![Telec lora doc boite](https://user-images.githubusercontent.com/38179281/134162286-eceee380-dab1-48e1-8bf8-886fe2ebf4c8.jpg)

**Comment by tcharp38** [comment]
Donc SS600ZB.
Merci.
Voila un JSON à tester
[TS0043__TZ3000_bi6lpsew.zip](https://github.com/KiwiHC16/Abeille/files/7202682/TS0043__TZ3000_bi6lpsew.zip)

- Decompresser dans core/config/devices/TS0043__TZ3000_bi6lpsew
- Redemarrer Abeille
- refaire inclusion
- tester

A noter que cette fois tu devrais avoir 3 commands "Click X" au lieu de "Etat X"

**Comment by StephaneG38** [comment]
Quand tu dit redemarrer Abeille c'est le Demon ?

**Comment by tcharp38** [comment]
oui

**Comment by StephaneG38** [comment]
Je trouve pas 
![Capture d’écran 2021-09-21 133606](https://user-images.githubusercontent.com/38179281/134163805-b0348566-a741-436d-807c-90c9456233fc.jpg)

**Comment by tcharp38** [comment]
J'ai donné un chemin à partir de la racine du plugin Abeille
donc tu dois aller d'abord dans plugins/Abeille

**Comment by tcharp38** [comment]
210921-BETA-2

**Comment by StephaneG38** [comment]
Oups

**Comment by StephaneG38** [comment]
Super ca marche !!!
Grand merci à toi !!
Stéphane

**Comment by tcharp38** [comment]
On peut clore ?

**Comment by StephaneG38** [comment]
Yes
Elle fonctionne au top
