### ISSUE TITLE
Ajout bouton 4 Scene Switch Buttons de la marque Moes - Tuya

### ISSUE THREAD

**Issue by Sdavid66** [KiwiHC16/Abeille#2151]
Hello,

Je viens de recevoir un nouveau bouton 4 scene de la marque Moes. 

Celui-ci est exactement le même que le "Tuya 4 buttons Scene Switch" noir dont le fichier Json est le "Scene TS0044__TZ3000_vp6clf9d.json".

Lorsque je l'ajoute, il est reconnu comme un "4 Buttons Scene Switch" (image bouton blanc) et dont le fichier Json est le "TS004F__TZ3000_xabckq1v.json".

Le problème c'est qu'il y a une seule configuration d'état dans cette configuration reconnue: -> On et OFF...

Peux-tu appliquer une correction pour que ce dernier puisse apparaître comme le "Tuya 4 buttons Scene Switch?" Merci.

Fichiers de logs en jointure.

[AbeilleLogs-210928.tar.gz](https://github.com/KiwiHC16/Abeille/files/7243460/AbeilleLogs-210928.tar.gz)

**Comment by tcharp38** [comment]
Tu peux me tenter un discovery ?

Je vois que ce modele est tres simple donc oui, probablement incomplet.

Entre parentheses ca promet. Ce model "ressemble" mais ne fonctionne pas de la meme maniere. Surement pour ca qu'il est vide.
Voir https://community.jeedom.com/t/ajout-switch-tuya-4-boutons-ts004f/59494/34

**Comment by Sdavid66** [comment]
... J'avais écrit que c'était mort mais non en fait, je regarde.

Navré mais je n'arrive toujours pas à te télécharger le fichier via le bouton. Rien ne se passe.

Pour le dernier "orange" je n'ai pas réussi le faire venir "vert".
<img width="675" alt="Capture d’écran 2021-09-28 à 14 55 09" src="https://user-images.githubusercontent.com/90246385/135091294-56a4e990-b73f-4d9d-a088-3e084ca018b7.png">
<img width="634" alt="Capture d’écran 2021-09-28 à 14 55 22" src="https://user-images.githubusercontent.com/90246385/135091340-82b8ab3b-3691-4147-8b6f-d749aa15ceb3.png">

<img width="262" alt="Capture d’écran 2021-09-28 à 14 55 29" src="https://user-images.githubusercontent.com/90246385/135091357-999ca86e-e69c-4810-aeff-1f04a89f6a26.png">

**Comment by Sdavid66** [comment]
Hello,

J'ai une piste pour les problèmes de reconnaissances des boutons...

Les périphériques Tuya de la marque Moes sont passés en version 2 de Zigbee.

J'ai sur mon dongle Zigate, une zigbee 1 (première version).
Une Zigate+ avec sa Zigbee 2 est sortie en début d'année et elle supporte le protocole Zigbee 3.0.

Les derniers boutons achetés sont dans cette version ... ceci explique cela. 

Je vais aller en acquérir un et je reviendrai ici dès réception --> d'ici 1 mois je pense.

https://zigate.fr/documentation/descriptif-de-la-zigate-v2/

Bonne fin de journée.

**Comment by tcharp38** [comment]
Suite a qq recherches
- rien à voir avec model TS0044
- 2 modes de fonctionnement; mode par defaut = dimmer

A voir: https://github.com/Koenkk/zigbee2mqtt/discussions/7158
Résumé:

Enum8 = 0 - Dimmer Mode
Enum8 = 1 - 12 Scene switch mode

> ZigBee Cluster Library Frame, Command: Write Attributes, Seq: 24
>     Frame Control Field: Profile-wide (0x10)
>     Sequence Number: 24
>     Command: Write Attributes (0x02)
>     Attribute Field, Enum8: 1
>         Attribute: Unknown (0x8004)
>         Data Type: 8-Bit Enumeration (0x30)
>         Uint8: 1 (0x01)
> 

> ZigBee Cluster Library Frame, Command: Write Attributes, Seq: 23
>     Frame Control Field: Profile-wide (0x10)
>         .... ..00 = Frame Type: Profile-wide (0x0)
>         .... .0.. = Manufacturer Specific: False
>         .... 0... = Direction: Client to Server
>         ...1 .... = Disable Default Response: True
>     Sequence Number: 23
>     Command: Write Attributes (0x02)
>     Attribute Field, Enum8: 0
>         Attribute: Unknown (0x8004)
>         Data Type: 8-Bit Enumeration (0x30)
>         Uint8: 0 (0x00)

Donc il faut probablement ecrire cet attribut 8004 pour changer le mode de fonctionnement par defaut.
A creuser

**Comment by tcharp38** [comment]
Je réalise qu'il a 3 sujets identiques sur TS004F__TZ3000_xabckq1v.
Je clos celui la et on se retrouve sur #2155
