### ISSUE TITLE
MainEP=0B dans le log abeille et plus moyen de piloter mes périphériques philips hue

### ISSUE THREAD

**Issue by Pierre-Lavoine** [KiwiHC16/Abeille#2159]
Hello,

Jeedom V4.1.26
Abeille V211004-STABLE-1

Depuis ce matin plus moyen de commander mes lampe philips hue et le seul élément du log est l'information suivante : MainEP=0B

Kesako ?

**Comment by tcharp38** [comment]
Salut.
Tu n es probablement pas en mode début.
A changer puis redémarrer démon.

Ensuite fais une action sur ton ampoule et files moi le package de logs (page support télécharger tout).

Ça ne fonctionne plus depuis quel évènement ?

**Comment by tcharp38** [comment]
Ha autre chose peux tu me donner l identifiant zigbee /fichier json correspondant ? (page équipement /avancé)
Merci

**Comment by Pierre-Lavoine** [comment]
J'ai redémarré mon serveur domo, ce qui a réglé le problème

Sinon il n'y avait pas eu de mise à jour particulière ou de modification de mon réseau et de mon admin depuis hier matin.

**Comment by tcharp38** [comment]
Ha donc tout est retombe en ordre et on peut clôturer ce sujet ?

**Comment by Pierre-Lavoine** [comment]
Oui tout est revenu en ordre, toutefois j'aurais aimé savoir de où pouvez venir ce message d'erreur et sa cause pour essayer d'y remédier la prochaine fois :)

**Comment by tcharp38** [comment]
A vrai dire le "MainEP=0B" est juste une info de debug mais si tu n'es pas en mode debug ca n'aurait pas du apparaitre.
Donc pas de message d'erreur evident.

Penser a regarder la page santé du plugin avec dans l'ordre
- que les démons tournent (vert en haut de la page): ex; AbeilleCmd+Parser+Serial
- que la zigate soit aussi active

Si tout ca est bon alors reste les logs.

Mais dans ton cas je ne peux rien dire malheureusement.
