### ISSUE TITLE
Useelink multi prise Jeedom Abeille

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#2160]
Salut Tcharp,
@tcharp38 
Voici un nouveau sujet pour l'EQ Useelink.
https://blog.domadoo.fr/guides/multiprise-connectee-zigbee-jeedom-eedomus/

Il s'agit d'une multi-prises. J'ai fait l'inclusion avec abeille mais je n'obtiens le contrôle ON/OFF que sur une seule prise.

![image](https://user-images.githubusercontent.com/82177848/137007255-65ef22f0-1d72-47a9-a4c1-979183701a22.png)
Alors que d'après les informations reprises pour cette multi-prises, chaque prise ainsi que l'USB est pilotable.

Merci d'avance

**Comment by tcharp38** [comment]
Tu connais la musique. Il faut commencer par récupérer un max d'Infos avec l'assistant. A toi d jouer

**Comment by ChrisChrisChri** [comment]
Salut,
Assistant semble indiquer plusieurs end points sur l'EQ mais cela reste orange à partir du deuxième.

Voici le fichier et la photo de l'EQ
[discovery (1).zip](https://github.com/KiwiHC16/Abeille/files/7339421/discovery.1.zip)


![USSELINK](https://user-images.githubusercontent.com/82177848/137162203-541fd6f9-3117-40df-8ba7-4d41b0134035.PNG)

Merci.

**Comment by tcharp38** [comment]
Quand ca reste orange tu relances en cliquant sur les boutons orange ou pas ?
Ca peut prendre un certain temps à recuperer toutes les infos.

**Comment by ChrisChrisChri** [comment]
Oui. Parfois rien ne se passe. Puis je fais un F5 et là alors j'obtiens autre chose.
Je vais encore essayer.

**Comment by tcharp38** [comment]
Merci
Quel est le modele/ref fabricant ?

**Comment by ChrisChrisChri** [comment]
J'ai régulièrement ce message d'erreur lors de l'interrogation
![image](https://user-images.githubusercontent.com/82177848/137187674-fc00053c-23d4-459d-a8e3-269127d00dd7.png)


Modèle: SM-SO306E

**Comment by ChrisChrisChri** [comment]
[discovery (2).zip](https://github.com/KiwiHC16/Abeille/files/7340405/discovery.2.zip)

Voici après +/- 15 minutes en appuyant sur ce qui est orange. Rien ne change

**Comment by tcharp38** [comment]
[TS011F__TZ3000_o005nuxx.zip](https://github.com/KiwiHC16/Abeille/files/7340476/TS011F__TZ3000_o005nuxx.zip)
A tester
Decompresser
redemarrer le demon Abeille
refaire inclusioin

**Comment by ChrisChrisChri** [comment]
T'es un chef !
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7340658/discovery.zip)

Voici la vue où on peut voir les 5 possibilités ;-)
La fonction toggle a disparu mais c'est pas trop grave pour moi. Par contre, tu crois que c'est possible de mesurer également le courant consommé ? Ce serait la cerise sur le gâteau ;-)

![image](https://user-images.githubusercontent.com/82177848/137196658-d511cf24-8cea-4100-9c43-20188b545117.png)

Déjà un très très grand merci pour toutes interventions

**Comment by tcharp38** [comment]
Est ce que tout fonctionne ? Tu me fais un résumé ?

Sinon pas de mesure de conso supportée par cette prise. Il faut le cluster 0702 ou 0B04.

**Comment by ChrisChrisChri** [comment]
Salut, 
Oui. Je sais contrôler de manière indépendante les 4 prises et l'USB. 
Il n'y a que la fonction TOGGLE qui n'est pas disponible ?

Si je comprends bien ton commentaire sur le cluster 0702 et 0B04, cela veut dire que lorsque j'utilise "assistant découverte" de l'EQ et qu'il reste en orange alors l'EQ ne fait pas remonter l'info ?

Pour ouvrir un fichier JSON, tu utilises notepad ?

Grand merci.

**Comment by tcharp38** [comment]
A tester
[TS011F__TZ3000_o005nuxx.zip](https://github.com/KiwiHC16/Abeille/files/7353598/TS011F__TZ3000_o005nuxx.zip)

Cote 702 & 0B04 l'equipement ne dit pas qu'il supporte ces clusters, et ce sont ceux qui permettent de mesurer la conso.

Pour ouvrir un JSON j utilise notepad++ avec le plugin JSON viewer mais il a plein de solutions je pense.

**Comment by ChrisChrisChri** [comment]
Toggle bien présent ;-) Reste plus que l'image à charger et c'est parfait !
Grand grand merci

**Comment by tcharp38** [comment]
Dans ce que je t'ai donné le JSON pointe vers la bonne image
            "icon": "UseeLink-SM-SO306"

Tu as probablement pas detruit ton equipement du coup il a conservé l icone que tu avais. Non ?

**Comment by ChrisChrisChri** [comment]
Je n'ai rien détruit en effet mais d'habitude je retrouve l'icône dans la liste. Ici, elle n'est pas présente dans la liste.

**Comment by tcharp38** [comment]
Ha mais oui tu as raison. Tu n'as pas l'image.
La voila pour "images" bien sur
![node_UseeLink-SM-SO306](https://user-images.githubusercontent.com/35221038/137533242-0e6c37a2-8589-44eb-9854-fb5e4d903ad8.png)

**Comment by tcharp38** [comment]
Du coup status de cette prise ?

**Comment by ChrisChrisChri** [comment]
Salut,
Pour moi, c'est ok.

Merci beaucoup

**Comment by tcharp38** [comment]
Ok, je clos.
A réouvrir si besoin.
Dispo dans 211015-BETA-1
