### ISSUE TITLE
Ikea shortcut button: 1 click = 2 report => pas compatible toggle

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2162]
Sujet initial: https://community.jeedom.com/t/switch-ikea-toggle-fait-clignoter/68618/12

@dedecontrebasse
Peux tu
- augmenter les lignes de log (5000 au lieu de 500 puis redemarrer demon)
- faire un click sur ta remote
- me filer ici (drag & drop) le package issue de la page support/telecharger tout

Je veux voir ce qui remonte du shortcut button

**Comment by dedecontrebasse** [comment]
Salut, et encore merci. 
Je ne trouve toujours pas la page "support/télécharger tout"...
Voici des logs, dis moi si ça va

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7344584/AbeilleParser.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7344585/Abeille.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7344581/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/7344582/AbeilleConfig.log)
[AbeilleDebug.log](https://github.com/KiwiHC16/Abeille/files/7344583/AbeilleDebug.log)

**Comment by tcharp38** [comment]
Je t'ai suggéré la page support/telecharger tout car ca genere un seul package avec tous les logs y compris ceux cachés.

Ceci dit, tu as fait un click ? Si oui à quelle heure et quelle est l'adresse de ton "shortcut button" ? Je ne vois rien passer dans le log.

**Comment by dedecontrebasse** [comment]
Je comprends mais je ne trouve pas la page support sur jeedom... 
Je pense que le clic est à 10:50:31. L'adresse est C94F / B4E3F9FFFE621E6A

**Comment by dedecontrebasse** [comment]
Là le clic est à 11:24:23
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7344780/Abeille.log)

**Comment by dedecontrebasse** [comment]
J'ai trouvé!
[AbeilleLogs-211014.tar.gz](https://github.com/KiwiHC16/Abeille/files/7344835/AbeilleLogs-211014.tar.gz)

**Comment by tcharp38** [comment]
La page support est une page d'Abeille.
Plugins > protocole domotique > Abeille
Le bouton "support" est en haut à droite il me semble.

Ceci dit je vois l'info qui vient de ton bouton

> [2021-10-14 10:45:50] Abeille1, Type=8095/OnOff update, SQN=4A, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2021-10-14 10:45:50] Abeille1, Type=8095/OnOff update, SQN=4A, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> 

ou encore

> [2021-10-14 10:50:26] Abeille1, Type=8095/OnOff update, SQN=4C, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2021-10-14 10:50:26] Abeille1, Type=8095/OnOff update, SQN=4C, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> 

pas de doutes il envoi 2 fois la meme chose dans la meme seconde.

C'est un comportement recent ?

**Comment by dedecontrebasse** [comment]
C'est la première fois que je l'utilise. j'en ai acheté un deuxième qui a le même comportement

**Comment by tcharp38** [comment]
Ha ok.
Avant de conclure que ce type de device n'est pas compatible avec du "toggle", on peut encore faire qq tests.

Une fois que tu l'as inclus, tu fais qqch avec les groupes ?

**Comment by dedecontrebasse** [comment]
Non, j'ai mis du temps avant de toucher aux groupes. mais après avoir réinitialisé la prise hier le bouton a eu un comportement normal. le soir (après avoir déplacé la prise et le bouton), le toggle ne marchait plus.

**Comment by tcharp38** [comment]
La ils ont un pb similaire ou un click genere cette fois 3 actions: https://community.hubitat.com/t/beta-ikea-tradfri-shortcut-button/67945/22

**Comment by dedecontrebasse** [comment]
Plus rigolo...
Si maintenant je fait un scenario de ce type avec comme déclencheur un middle click : Si prise allumé, eteindre la prise, sinon allume là=> ça provoque le même allumage puis extinction dans la seconde. Mais si je met le scénario en mode synchrone, ça marche correctement
![essai lampe onof](https://user-images.githubusercontent.com/92514264/137295039-2082fb1b-86de-4223-8145-1b85c6f5d5fb.png)

![essai lampe onof (1)](https://user-images.githubusercontent.com/92514264/137295049-c17710b7-5519-43b7-af2f-060c886860b8.png)
!

**Comment by dedecontrebasse** [comment]
11:57:12, mode synchrone décoché, comportement anormal
11:57:50, mode synchrone coché, comportement normal
[AbeilleLogs-211014 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7345036/AbeilleLogs-211014.1.tar.gz)

**Comment by tcharp38** [comment]
> [2021-10-14 11:57:11] Abeille1, Type=8095/OnOff update, SQN=6B, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2021-10-14 11:57:11] Abeille1, Type=8095/OnOff update, SQN=6B, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01

et

> [2021-10-14 11:57:49] Abeille1, Type=8095/OnOff update, SQN=6D, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2021-10-14 11:57:49] Abeille1, Type=8095/OnOff update, SQN=6D, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01

Comme tu peux le voir, dans les 2 cas le bouton renvoi une double info.
Je ne sais pas quelle est la diff sync / async de Jeedom. Si tu as un pointeur vers une doc je suis preneur.

**Comment by dedecontrebasse** [comment]
Moi non plus tu sais je tatonne...."Mode synchrone : Lance le scénario dans le thread courant au lieu d’un thread dédié. Ca permet d’augmenter la vitesse de lancement du scénario mais cela peut rendre le système instable."

**Comment by tcharp38** [comment]
Ok donc en synchrone tu perds rien mais en async tu peux perdre une des infos, d'ou un comportement que tu le souhaites.
Bref, pour moi c est un effet de bord mais pas garanti.

**Comment by dedecontrebasse** [comment]
A savoir que quand j'ai réinitialisé la prise ça a marché correctement un temps

**Comment by tcharp38** [comment]
Etrange. Et tu n'as rien fait apres ?

**Comment by dedecontrebasse** [comment]
non

**Comment by tcharp38** [comment]
Tu dis "reinitialisé la prise" mais pas le bouton. Donc le comportement de ce dernier ne doit pas changer car rien à voir.

**Comment by dedecontrebasse** [comment]
tu as raison, je viens de reproduire ce que j'ai fait hier et pas d'ameliorations, je ne sais pas pourquoi ça a bien marché hier matin....

**Comment by tcharp38** [comment]
Bon pour l'instant je seche mais pas un souci Abeille à priori. Je vois pas comment.
2 pistes
- un firmware du bouton pas à jour ?
- Une mauvaise config ou une config manquante lors de l'inclusion ?

Si jamais je tombe dessus en magasin j'en acheterai un mais jusque la jamais vu.

**Comment by dedecontrebasse** [comment]
Ok merci pour ton aide

**Comment by tcharp38** [comment]
D'ailleurs tu l'as trouvé en magasin toi ? Idem pour le repeteur. Je ne le trouve pas en France.

**Comment by dedecontrebasse** [comment]
oui au ikea de Rennes
si tu regarde les stocks en magasin il y en a partout https://www.ikea.com/fr/fr/p/tradfri-lanceur-de-scenario-connecte-blanc-40356381/

**Comment by tcharp38** [comment]
Et le repeteur ? Tu as ca aussi ?

**Comment by dedecontrebasse** [comment]
Nan ils ont plus l'air de le faire en france, en Belgique https://www.ikea.com/be/fr/p/tradfri-amplificateur-de-signal-10400408/

**Comment by mickadam29** [comment]
Attention, ce bouton est un lanceur de scénario ! J'avais fait le JSON à une époque et le PR. Ce fichier a été intégré. Maintenant il a peut-être été repris par qq1. J'ai eu du mal à comprendre comment il fonctionnait, mais je crois que ses fonctions sont limitées. Il envoie la commande quand tu appuies dessus. Je ne me souviens plus s'il gère le double-click, appui long. Je vais allé voir le JSON. Il a bien été repris par @tcharp38 ou @KiwiHC16  et ne gère qu'une valeur. S'utilise avec un scénario dans Jeedom

![image](https://user-images.githubusercontent.com/36518012/151868246-9ec1e392-6b08-4efa-9ddc-d6c94b97ce9e.png)

**Comment by tcharp38** [comment]
Pour info j'ai une piste pour ce pb.
Je crois que ca ne vient pas du bouton, mais de la stack de la zigate.
Donc il y a qqch de possible à faire.

A suivre...

**Comment by tcharp38** [comment]
@dedecontrebasse 
Toujours interessé par ce sujet ?

**Comment by dedecontrebasse** [comment]
Oui bien sûr, dis moi si je peux aider

**Comment by tcharp38** [comment]
Peux tu basculer sur la beta et refaire un test avec le shortcut button ?
Je crois que j'ai compris le souci.

Tu fais un click et tu me file le log AbeilleParser.log.
Merci

Tu aussi me dire si ca convient pour ton souci de toggle.

**Comment by dedecontrebasse** [comment]
Salut,
je suis en BETA,
le toggle marche, voici le parser, rien ne s'y affiche

**Comment by tcharp38** [comment]
Donc le pb initial de ce sujet a disparu ?
Tu n'as pas attaché quoi que ce soit. Qui plus est si c'est vide, c'est que tu n'es pas en mode debug.

**Comment by dedecontrebasse** [comment]
Voila le log

**Comment by tcharp38** [comment]
Quel log ? :)

**Comment by dedecontrebasse** [comment]
celui là!

**Comment by tcharp38** [comment]
Ben... je dois être aveugle ou rien n'est attaché. Regarde toi meme sur le forum.

**Comment by dedecontrebasse** [comment]
je répondais en mail...
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8162170/AbeilleParser.log)
.

**Comment by tcharp38** [comment]
Ok, donc le truc qui m'interesse c'est ca

> [2022-03-01 12:34:33] Abeille1, Type=8095/OnOff update, SQN=1F, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2022-03-01 12:34:33] Abeille1, Type=8095/OnOff update, SQN=1F, EP=01, ClustId=0006, AddrMode=02, Addr=C94F, Status=01
> [2022-03-01 12:34:33]   Duplicated message for SQN 1F => ignoring

Le 2nd est ignoré donc ton souci de toggle doit etre reglé.
Si tu confirmes, on clos le sujet.

**Comment by dedecontrebasse** [comment]
Bravo, je confirme une utilisation normale. 
merci!

**Comment by tcharp38** [comment]
Cool. Je ferme
