### ISSUE TITLE
Tuya - Smart Door Sensor - model CG205

### ISSUE THREAD

**Issue by Sdavid66** [KiwiHC16/Abeille#2165]
Hello,

1. Ce sensor ON-OFF n'est pas reconnu par la ruche.
2. Lorsque j'essaie de lire les communication pour te faire un discovery, il mentionne que le sensor a quitté le réseau. J'ai réessayé plusieurs fois mais sans succès. Je te place les logs.
3. 
Je suis en Version Beta.
[AbeilleLogs-211017.tar.gz](https://github.com/KiwiHC16/Abeille/files/7360211/AbeilleLogs-211017.tar.gz)

![Tuya_smart_sensor](https://user-images.githubusercontent.com/90246385/137633973-bbd96042-ead0-4f00-8302-90e2d621ecef.png)

**Comment by tcharp38** [comment]
Tu me fais un discovery ?

**Comment by Sdavid66** [comment]
> Tu me fais un discovery ?

Lorsque j'essaie de faire un discovery, le module part de l'abeille.

Du coup, je n'arrive même pas à t'en faire un. Je vais ressayer à nouveau demain en redémarrant la totale.

**Comment by tcharp38** [comment]
Ca veut dire quoi "part de l'abeille" ?

**Comment by Sdavid66** [comment]
Oui... ;-)

Lorsque j'essaie d'interagir avec via le discovery, il me dit que le périphérique s'est déconnecté de la ruche ou un truc du style. Comme si je faisais une exclusion du périphérique.

**Comment by tcharp38** [comment]
Ha ca pue le périph qui plante. Je n'envoi que des commandes standard pour l interroger.
Je vais fouiller les logs pour avancer

**Comment by tcharp38** [comment]
[TS0203__TYZB01_xph99wvr.zip](https://github.com/KiwiHC16/Abeille/files/7363354/TS0203__TYZB01_xph99wvr.zip)

A tester. Premier jet.
Apres inclusion faire des actions ouvrir/fermer et me donner l heure correspondante avec le package de logs.
Ce periph utilise un cluster que je n'ai encore jamais vu (IAS).

**Comment by Sdavid66** [comment]
Hello, je te fais ça. 

Il me refait la meme chose. Inclusion ok et après, il quitte direct le réseau et le bouton est en mode "Désactivé".
10:39
[AbeilleLogs-211019.tar.gz](https://github.com/KiwiHC16/Abeille/files/7371637/AbeilleLogs-211019.tar.gz)

**Comment by tcharp38** [comment]
Alors la je pige pas pourquoi il quitte.

> [2021-10-19 10:39:56] Abeille1, Type=8048/Leave indication, ExtAddr=00124B000292EC1B, RejoinStatus=00

Je vois que tu as un FW v2 donc une clef v2 ?! Quel type de clef ?

> Type=8010/Version, Appli=0005, SDK=0320

Pourrais tu eventuellement tester avec le FW 3.1e ?

**Comment by Sdavid66** [comment]
Hello,

Je suis effectivement avec une clef de dernière génération de chez Zigate. C'est un dongle USB. 

Je vais voir la procédure pour la mise à jour et si ce n'est pas trop chaud, je le fais.

A+

**Comment by tcharp38** [comment]
Je vais me renseigner apres de l'equipe Zigate au cas ou ils auraient deja vu ca.

**Comment by tcharp38** [comment]
On me suggere de voir 2 choses
- est ce qu'il n'y a pas une commande qui fait "planter" le device. Pas simple à voir dans la mesure ou il faudrait sniffer ce qui se passe et rien n'est fait differement des autres equipements. Neanmoins a garder en tete.
- quel est le LQI ? Autrement dit ce sensor est loin de la box pendans les tests ? Si oui a refaire à proximité pour voir si ca change qqch.

**Comment by tcharp38** [comment]
[TS0203__TYZB01_xph99wvr.zip](https://github.com/KiwiHC16/Abeille/files/7411142/TS0203__TYZB01_xph99wvr.zip)

Nouvelle version à essayer.
- decompresser
- redemarrer Abeille
- refaire inclusion

**Comment by Sdavid66** [comment]
> On me suggere de voir 2 choses
> 
> - est ce qu'il n'y a pas une commande qui fait "planter" le device. Pas simple à voir dans la mesure ou il faudrait sniffer ce qui se passe et rien n'est fait differement des autres equipements. Neanmoins a garder en tete.
> 
> - quel est le LQI ? Autrement dit ce sensor est loin de la box pendans les tests ? Si oui a refaire à proximité pour voir si ca change qqch.

Et bien merci pour ces renseignements.

Vais voir cela. La deuxième possibilité est probable, je l'ai fait juste derrière un mur. 

Te redis 👍

**Comment by Sdavid66** [comment]
> > On me suggere de voir 2 choses
> > 
> > * est ce qu'il n'y a pas une commande qui fait "planter" le device. Pas simple à voir dans la mesure ou il faudrait sniffer ce qui se passe et rien n'est fait differement des autres equipements. Neanmoins a garder en tete.
> > * quel est le LQI ? Autrement dit ce sensor est loin de la box pendans les tests ? Si oui a refaire à proximité pour voir si ca change qqch.
> 
> Et bien merci pour ces renseignements.
> 
> Vais voir cela. La deuxième possibilité est probable, je l'ai fait juste derrière un mur.
> 
> Te redis 👍

Hello,

Je viens de refaire plusieurs tests à 14:50.

Même chose, au bout de 10 secondes, le SONOFF quitte le réseau. 

Pas trouvé de moyen de faire mieux.

Je précise que j'étais à 3 centimètres du dongle Zigate v2. 

Pour ma part, je vais laisser de côté car la procédure de mise à jour n'est pas triviale. Je commanderai un autre capteur d'ouverture et de fermeture.

Merci encore
[AbeilleLogs-211027.tar.gz](https://github.com/KiwiHC16/Abeille/files/7426320/AbeilleLogs-211027.tar.gz)

**Comment by tcharp38** [comment]
Qqch chose m'echappe. Tu dis le "SonOff" quitte le reseau. On parlait pas d'un autre équipement de chez Tuya plutot ?

Bon je suppose que tu confonds. Je vois bien l'appairage puis 10sec apres un leave sans explication.
Je laisse le sujet ouvert si qqn d'autre a ce sensor et peut donner d'autres infos.

**Comment by Sdavid66** [comment]
Pardon ce n’est pas le SONOFF (mais bien TUYA). Je me suis trompé lorsque j’ai tapé cette info. Nous sommes bien sur ce problème. En attendant, je ne l’utilise plus. On verra pour la suite. Merci en tout cas.

**Comment by tcharp38** [comment]
Qqn d'autre à cet équipement et a des soucis ?

**Comment by tcharp38** [comment]
Trop vieux sujet sans activite.
Je clos mais à reouvrir si qqn à ce modele et veut bosser dessus.
