### ISSUE TITLE
TUYA QS-Zigbee-C01 volet roulant _TZ3000_vd43bbfq modèle TS130F

### ISSUE THREAD

**Issue by pabordel** [KiwiHC16/Abeille#2169]
Bonjour, 
voici les information pour intégrer ce module
Commande volet roulant avec neutre et entrée interrupteur

[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/7386516/discovery.json.zip)

en plus le json du plugin zigbee correspondant
[plugin zigbee-TS130F.json.zip](https://github.com/KiwiHC16/Abeille/files/7386596/plugin.zigbee-TS130F.json.zip)
.

**Comment by tcharp38** [comment]
A decompresser dans "core/config/commands"
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7387241/commands.zip)

A decompresser dans "core/config/devices"
[TS130F__TZ3000_vd43bbfq.zip](https://github.com/KiwiHC16/Abeille/files/7387246/TS130F__TZ3000_vd43bbfq.zip)

Puis redemarrer Abeille
refaire inclusion
me filer le package de logs (page support/telecharger tout)
et on fait le point.

**Comment by pabordel** [comment]
Bonjour je peux fournir un module pour faire des tests si besoin, je travaille sur Grenoble. 

J'ai trouvé ces infos du coté de zigbee2mqtt, comme c'est avec ça que j'ai réussi à calibrer mes volets elles ne devraient pas être trop mauvaises  :

Cluster | CMD | Attributes | Data Type | Value | Description

(0x0102) | Write Attributes (0x02) | 0xf002 | 8-Bit (0x30) | 1 (0x01) | Motor reversal on
(0x0102) | Write Attributes (0x02) | 0xf002 | 8-Bit (0x30) | 0 (0x00) | Motor reversal off
(0x0102) | Write Attributes (0x02) | 0xf001 | 8-Bit (0x30) | 0 (0x00) | Start Calibration
(0x0102) | Write Attributes (0x02) | 0xf001 | 8-Bit (0x30) | 1 (0x01) | End Calibration
(0x0006) | Write Attributes (0x02) | 0x8001 | 8-Bit (0x30) | 0 (0x00) | Light Mode  1
(0x0006) | Write Attributes (0x02) | 0x8001 | 8-Bit (0x30) | 1 (0x01) | Light Mode  2
(0x0006) | Write Attributes (0x02) | 0x8001 | 8-Bit (0x30) | 2 (0x02) | Light Mode  3

(0x0102) | Command (0x00) |   |   |   | open
(0x0102) | Command (0x01) |   |   |   | close
(0x0102) | Command (0x02) |   |   |   | stopp

(0x0102) | Report Attributes (0x0a) | 0x0008 | 8-Bit (0x20) | 0 (0x00) | Position 0%
(0x0102) | Report Attributes (0x0a) | 0x0008 | 8-Bit (0x20) | 100 (0x64) | Position 100%
(0x0102) | Report Attributes (0x0a) | 0xf000 | 8-Bit (0x30) | 0 (0x00) | Moving up
(0x0102) | Report Attributes (0x0a) | 0xf000 | 8-Bit (0x30) | 1 (0x01) | Stopp
(0x0102) | Report Attributes (0x0a) | 0xf000 | 8-Bit (0x30) | 2 (0x02) | Moving do
![QS-Zigbee-C01](https://user-images.githubusercontent.com/65667078/139540968-31e12604-c576-4ad8-b0e4-7b9b82ef0620.png)
wn

**Comment by tcharp38** [comment]
Je prends l'image.
As tu essayé les fichiers que je t'ai filé ?

**Comment by pabordel** [comment]
oui,  et j'ai renvoyé les logs par mails, je les redépose ici au cas ou. 
[AbeilleLogs-211030.tar.gz](https://github.com/KiwiHC16/Abeille/files/7447217/AbeilleLogs-211030.tar.gz)

mauvaise nouvelle rien ne marche :-(

Pour le moment c'est le plugin zigbee (depuis sa dernière mis à jour)  qui s'en sort le mieux avec ce module (j'ai installé zigate, zigbee et abeille).  Avec Zigate il est utilisable mais on ne peut pas calibrer le volet.

**Comment by tcharp38** [comment]
Effectivement je n'avais rien reçu. C est mieux de passer par la.

Quoi qu'il en soit tes logs me disent que tu as une version Abeille plutot tres vieille n'est ce pas ?
Donc pas à jour. Pourquoi ? Volontaire ? Un oubli ?

**Comment by pabordel** [comment]
Pas vraiment volontaire en fait, tant que je ne peux pas utiliser mes volets roulants avec abeille je reste sur un autre plugin (zigate). mais bizarre la dernière maj d'abeille était du 20/10/2021 10 jours c'est très ancien ?

**Comment by tcharp38** [comment]
Je ne comprends pas du tout alors. 20/10/21 non c'est recent, néanmoins les logs que tu m'as envoyé sont d'un code antique c'est clair.
Et meme pas cohérents.
Regarde les dates du parser: 2021-03-27 22:27:24
Du serial read: 2021-04-02 12:15:05
AbeilleCmd: 2021-04-03 06:51:23

bref mars, avril de cette année.
Je pige pas comment tu fais pour avoir ca

**Comment by pabordel** [comment]
J'ai bloqué les mises à jour de abeille pendant un certain temps, car je ne l'utilisais pas. Ça vient peut être de ça. le log doit remonter sur longtemps aussi à cause de ça et de la très faible activité du plugin : juste des tests de temps en temps.

**Comment by tcharp38** [comment]
Du coup comment tu veux proceder ? Avec ce que je t'ai envoyé tu dois pouvoir monter/descendre et avoir un retour de position. Si ca n'est pas le cas il manque qqch deja la.

**Comment by pabordel** [comment]
Alors il manque encore quelque chose : pas de commutation des relais sur les commandes up et down
et la position ne renvoie pas de valeur. 
Les autres commandes fonctionne normalement. 
un problème lié au cluster 258 ? 
[AbeilleLogs-211107.tar.gz](https://github.com/KiwiHC16/Abeille/files/7491922/AbeilleLogs-211107.tar.gz)

**Comment by tcharp38** [comment]
Rien d'utilisable dans tes logs malheureusement. Je pense que tu n'es plus en mode "debug".
Je vois des actions faites ce matin vers 9h mais le log parser date du 30 oct.

**Comment by pabordel** [comment]
Alors il manque encore quelque chose : pas de commutation des relais sur les commandes up et down
et la position ne renvoie pas de valeur. 
Les autres commandes fonctionne normalement. 
un problème lié au cluster 258 ? 
[AbeilleLogs-211107.tar.gz](https://github.com/KiwiHC16/Abeille/files/7491922/AbeilleLogs-211107.tar.gz)
