### ISSUE TITLE
Bind ne fonctionne pas sur système en production une ampoule sur 4 !

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#217]

**Comment by KiwiHC16** [comment]
Bind: 
Fonctionne pour a0da
```
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/bind} => address=000B57fffe3a563b&ClusterId=0006&reportToAddress=00158d0001b22e24
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]Type: CmdAbeille Address: Ruche avec Action: bind
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]6 arguments command
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]command bind
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]len data: 42
AbeilleMQTTCmd 2018-03-23 23:28:48[DEBUG]checksum computed: 11
```

Fonctionne pour 46d9
```
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/bind} => address=000B57fffe952a69&ClusterId=0006&reportToAddress=00158d0001b22e24
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]Type: CmdAbeille Address: Ruche avec Action: bind
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]6 arguments command
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]command bind
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]len data: 42
AbeilleMQTTCmd 2018-03-23 23:30:10[DEBUG]checksum computed: 138
```

Ne fonctionne pas pour 0Cd5
```
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/bind} => address=000B57fffe364820&ClusterId=0006&reportToAddress=00158d0001b22e24
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]Type: CmdAbeille Address: Ruche avec Action: bind
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]6 arguments command
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]command bind
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]len data: 42
AbeilleMQTTCmd 2018-03-23 23:31:28[DEBUG]checksum computed: 2
```
Pourquoi le C de 0Cd5 est en capitale ?

Liste Equipements donne:
`AbeilleParser 2018-03-23 23:33:45[DEBUG]Abeille i: 11; ID : 34; Short Addr : 0Cd5; IEEE Addr: 000B57fffe364820; Power Source (0:battery - 1:AC): 01; Link Quality: 77`

Est ce checksum qui serait que sur un digit ?

**Comment by KiwiHC16** [comment]
sur a0da
0000000 0201 3010 1002 0b15 1002 1b02 ff57 3afe
0000010 3b56 1102 1002 1602 1302 1002 8d15 1002
0000020 1102 2eb2 0224 0311                    
0000028

Sur aCd5:
0000000 0201 3010 1002 0215 1002 1b02 ff57 36fe
0000010 2048 1102 1002 1602 1302 1002 8d15 1002
0000020 1102 2eb2 0224 0311                    
0000028

Le deux streams sont identiques sauf checksum et IEEE qui semblent Ok donc pas de probleme de ce côté. Reste a sniffer l interface radio pour voir ce qu'il s y passe.

**Comment by KiwiHC16** [comment]
Closed by mistake

**Comment by mickadam29** [comment]
Je confirme qu'une des 2 lampes IKEA remonte avec une majuscule, "0Dc8" chez moi

**Comment by KiwiHC16** [comment]
Côté radio la ZiGate n'envoie rien dans le cas adresse aCd5 pour le Bind Etat alors que le bind level fonctionne. Mais l ampoule est bizarre, elle fait des flash de lumiere de temps en temps. Et il semblerait quelle fasse une avalanche de demande pour une adresse IEEE que je ne connais pas: Network Address Request -> 00:00:0A:0E:EE:0E:01:01 en broadcast
Bug de l ampoule, probleme de parametrage,...
Pour la prod je suis passé sur une autre ampoule qui a fonctionnée du premier coup. J'ai gardée cette ampoule de côté pour investiguer plus tard.

**Comment by KiwiHC16** [comment]
Si l'equipement n'est pas en relation radio direct, les bind request ne sont pas envoyés par la zigate (par contre les setReport qui utilisent la short adresse sont envoyés).

**Comment by KiwiHC16** [comment]
Je clos ce point car le bind automatique est un autre sujet.
