### ISSUE TITLE
Support Xiaomi Aqara QBKG26LM (switch.n3acn3)

### ISSUE THREAD

**Issue by NikoScotch** [KiwiHC16/Abeille#2174]
Interrupteur mural 3 boutons Xiaomi Aqara QBKG26LM, non reconnu par le plugin Abeille (stable).
L'interrupteur comporte 3 boutons poussoirs, et 3 sorties phase (chacune associée à un bouton).
Un 1er appui sur un bouton commute la sortie phase associée sur 230V, et une petite LED en face avant passe au bleu.
Un 2ème appui sur le bouton commute la sortie phase associée sur 0V, et la LED s'éteint.
Ci joint le fichier discovery que j'ai réussi à obtenir via la procédure https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7434181/discovery.zip)

**Comment by tcharp38** [comment]
[switch.n3acn3.zip](https://github.com/KiwiHC16/Abeille/files/7435043/switch.n3acn3.zip)

A tester
- decompresser dans core/config/devices
- redemarre Abeille
- refaire inclusion

C est surment incomplet. J'ai l'impression qu'il faut configurer qqch lors de l'appairage pour le mettre dans un mode autre que celui par defaut.

Je te laisse me trouver une image PNG sans fond pour mettre en icone.

**Comment by NikoScotch** [comment]
Bravo @tcharp38 ça fonctionne du 1er coup 👍 🥇 
![image](https://user-images.githubusercontent.com/77047829/139534181-019944be-cf73-4f35-aaa5-3251730bf04b.png)
Je peux piloter les 3 interrupteurs depuis l'interface jeedom (ce qui allume / éteint les LED correspondantes sur l'appareil) ou depuis l'appareil directement (ce qui met à jour l'ampoule correspondante dans l'interface jeedom).
Pour le PNG sans fond, c'est un peu galère car la plupart des images sont sur fond blanc (donc pour détourer sans rogner dans l'inter c'est galère) mais j'ai réussi à faire ça, dis moi si ça te convient 
![Aqara_QBKG26LM](https://user-images.githubusercontent.com/77047829/139534631-d58bc3de-496c-433e-a825-316fddf53c86.png)
Merci encore 👍 👍 👍

**Comment by NikoScotch** [comment]
PS je n'ai pas noter de problème particulier lié à un "mode par défaut" ou autre, mais je verrai à l'usage, je remonterai les infos si besoin

**Comment by tcharp38** [comment]
Il reste 2 choses: j'ai vu qu'il pouvait remonter Total power et Active power mais pas compris de quoi.
Une idée ?

Tu vois qqch remonter ?
J'ai besoin d'un package de logs pour voir ce qui se passe à l'usage.

**Comment by NikoScotch** [comment]
Alors je pense que c'est la puissance consommée par la charge branché sur l interrupteur (la lumière donc) mais j'ai pas pu tester encore correctement j'ai un souci pour l'installer : il faut un neutre et je dois agrandir le trou dans le mur...

**Comment by tcharp38** [comment]
Fais signe quand tu peux continuer les essais.

**Comment by NikoScotch** [comment]
Bon alors j'ai pu installer l'interrupteur, en usage depuis 1 semaine.
Les touches fonctionnent, parfait, mais je ne vois rien dans Total power et Active power, ils restent constamment à 0, et l'historique reste vide (j'ai bien cocher "historiser" pour ces 2 commandes).
De quel(s) log(s) as-tu besoin exactement @tcharp38  ?
merci à toi

**Comment by tcharp38** [comment]
[switch.n3acn3.json.zip](https://github.com/KiwiHC16/Abeille/files/7703501/switch.n3acn3.json.zip)
A tester.

- Decompresser dans core/config/devices/switch.n3acn3
- redemarrer Abeille
- refaire inclusion
- me fournir le package de logs via la page support/telecharger tout
Merci

**Comment by NikoScotch** [comment]
J'utilise l'interrupteur dans plusieurs scénarios, si je dois le ré-inclure je vais devoir refaire les scénario ou bien ?

**Comment by tcharp38** [comment]
Salut @NikoScotch 
Si je n'ai pas changé le nom des commandes que tu utilises, ca devrait etre transparent en le reincluant.
Tu utilises quoi dans ton scenario ?

**Comment by NikoScotch** [comment]
Hello @tcharp38 ,
Dans mon scénario j'utilise l'état des boutons (ON ou OFF) pour piloter d'autres équipements.
J'ai déroulé la procédure que tu m'a indiqué, mais j'ai un doute sur l'étape "refaire l'inclusion" car je n'ai pas eu de message dans abeille (par contre l'interr a bien clignoté rouge puis bleu lent puis bleu rapide, comme si il s'était ré-inclus).
J'ai refait l'inclusion aujourd'hui vers ~16h55 ~17h.
Ci joint les log, dis-moi si tu vois ce qu'il te faut ou pas : [AbeilleLogs-220112.tar.gz](https://github.com/KiwiHC16/Abeille/files/7856025/AbeilleLogs-220112.tar.gz)
.

**Comment by tcharp38** [comment]
Hello
Jettes un oeil aux logs que tu m'as filé. Inutilisables. Soit vides soit plein de messages de corruption.
Je soupconnes que tu n'es plus en mode "debug", n'est ce pas ?
Bref je ne peux rien en faire

**Comment by NikoScotch** [comment]
OK, sorry !
OK j'ai repassé en les log en debug, et j'ai configuré 5000 lignes dans les settings pourtant il semble encore limité à 500 étrange...
bref regarde voir celui ci : ré-association vers 20h38, ensuite j'ai un peu joué avec les 3 boutons.
[AbeilleLogs-220114.tar.gz](https://github.com/KiwiHC16/Abeille/files/7872813/AbeilleLogs-220114.tar.gz)

**Comment by tcharp38** [comment]
Tu dois avoir "Status 1", "Status 2" et "Status 3" qui bougent.
C est bon ?
Du coup tu peux caller ton scenario dessus

**Comment by NikoScotch** [comment]
Oui ça fonctionne merci c'est bon ! (mais ça fonctionnait déjà avant avec les fichiers que tu m'as donné le 28/10).
Les messages de corruption c'est quoi ? un device qui fonctionne mal ?
thanks

**Comment by tcharp38** [comment]
Les message dont je parle ressemblent à ca

> Abeille1, Message corrompu (taille payload incorrecte, taille=17B, att=15B)

Je ne comprends pas encore comment on arrive à ca mais j'ai déja vu.
En tout cas ca ressemble + a un souci general qu 'un souci d'un device mais tout semble rentré dans l'ordre pour toi.

Je clos le sujet ?

**Comment by NikoScotch** [comment]
OK je me demande si je n'ai pas un souci avec ma zigate peut-être... 
Bref oui tu peux clore !
Merci !

**Comment by tcharp38** [comment]
Je clos. A reouvrir si besoin

**Comment by tcharp38** [comment]
@Sososoja
Vu que c'est un de tes modeles, peux tu me filer une vue du snapshot de cet equipement ?
D'autre part as tu constaté des choses qui ne fonctionnement pas comme le Total power ou active power qui ne bougerait pas ?

**Comment by Sososoja** [comment]
Les commandes on off et les retours d'états fonctionnent nickel, mais les infos total power et active power sont depuis toujours à 0.
Mais je ne les utilises pas.

**Comment by tcharp38** [comment]
C est bien ce qui me semblait que qqch deconnait.
Es tu sur que cet equipement fasse ce type de mesure ?

**Comment by Sososoja** [comment]
https://fr.aliexpress.com/item/4001076513250.html?spm=a2g0o.order_list.order_list_main.281.6e5a5e5bpNepdN&gatewayAdapt=glo2fra
J'ai pas l'impression qu'il fasse ça. Je t'ai mis le lien de l’interrupteur si tu veux lire la description.

**Comment by tcharp38** [comment]
Pour memo: a nettoyer. Il doit y avoir des infos utiles dans les trames privées Xiaomi

> [2023-01-26 15:33:00] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FCC0, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=3002, DstAddrMode=02, DstAddr=0000
> [2023-01-26 15:33:00]   FCF=1C/General/Serv->Cli/ManufCode=115F, SQN=87, cmd=0A/Report attributes
> [2023-01-26 15:33:00]   UNHANDLED FCC0-00F7-41: 03281D0521030008215A01092104060F23000090000C200064100065100066100095396789E83F9639F0660D459739000000009839004CAF3B9A2000
> [2023-01-26 15:33:00]   decodeFF01(03281D0521030008215A01092104060F23000090000C200064100065100066100095396789E83F9639F0660D459739000000009839004CAF3B9A2000)
> [2023-01-26 15:33:00]   Legacy 'Puissance'
>

**Comment by Sososoja** [comment]
Salut tcharp38,
Depuis la dernière maj je crois, j'ai ce module qui me remonte des erreurs "ep vide".
Comme tu avais essayé de trouver les infos de conso c'est surement lié à ça car il y en a vraiment régulièrement. La dernière remonte à 15:46:19 dans les logs ci joint.
[AbeilleLogs-230320.tar.gz](https://github.com/KiwiHC16/Abeille/files/11019527/AbeilleLogs-230320.tar.gz)

**Comment by Sososoja** [comment]
Je crois que c'est réglé, j'avais enlevé les mises à jour beta.

**Comment by tcharp38** [comment]
Ca veut dire quoi ? Tu as rebasculé sur la stable et plus de pbs ?

**Comment by Sososoja** [comment]
non l'inverse, j'étais en beta et suis passé en stable et la j'ai commencé à avoir les messages d'erreurs. Et cet après midi je suis repassé en beta et plus de messages d'erreurs.

**Comment by tcharp38** [comment]
Ha donc tu es en beta.
Parfait je prefere ca.

Mais pour info la seule facon de repasser en stable est de restaurer un backup stable sinon tu ne peux que te cogner des pbs.

Du coup... ce sujet peut etre clos ?

**Comment by Sososoja** [comment]
OK, mais j'ai trop de modifs depuis que je suis passé en beta, donc abeille restera en beta.
Merci pour l'info .
Oui tu peux refermer le sujet.

**Comment by tcharp38** [comment]
Ca n'est pas un souci. La beta est la + avancée.
Mais des que la nouvelle stable est sortie, tu peux switcher dessus si plus besoin de support.
