### ISSUE TITLE
Tete thermostatique TV02 Zigbee (TS0601, _TZE200_hue3yfsn)

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2175]
Bonjour,
je voudrais inclure une tete thermostatique : [https://fr.aliexpress.com/item/1005003171968812.html?spm=a2g0s.9042311.0.0.3fdd6c373NJuUz](url)
voici le fichier demandé (si je ne me suis pas trompé!
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7443912/discovery.zip)
)

**Comment by tcharp38** [comment]
Salut @Proft1972 
Je pige pas. Le discovery associé correspond à eWeLink, ZB-SW01, donc pas le bon modele.
Une idée ?

**Comment by Proft1972** [comment]
Hello, j'ai du prendre un mauvais fichier, dsl
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7448335/discovery.zip)

**Comment by tcharp38** [comment]
J'ai l'impression que ton plugin Abeille est une antiquité.
Peux tu le mettre à jour avant de refaire cette interrogation avec l'assistant ?

**Comment by Proft1972** [comment]
Oups j'avais coché la case "ne pas mettrre à jour" voila c'est resolu maintenant enfin j'espere!

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7448537/discovery.zip)

**Comment by tcharp38** [comment]
C'est beaucoup mieux. Tout etait passé au vert ?
Sinon il faut insister un peu pour avoir toutes les infos.

Ceci dit apres rapide coup d oeil sur ce que tu m'as donné, ca va pas etre simple. Pas de cluster standard pour piloter cet equipement donc va falloir creuser. A priori ca utilise un cluster specifique Tuya EF00.

**Comment by tcharp38** [comment]
https://github.com/zigpy/zha-device-handlers/issues/1027
https://github.com/PeWu/tuya-valve-z2m/blob/main/tuya_radiator_valve.js

**Comment by Proft1972** [comment]
Bonjour,
Il n'y a que EF00 qui est resté en orange:
![tete thermo1](https://user-images.githubusercontent.com/93400394/139673740-b26656c0-3b40-4752-a6d8-00a033c64196.jpg)

Voici le nouveau fichier: 

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7453303/discovery.zip)

J'ai regardé les liens que tu as mis mais je ne sais pas quoi en faire !

**Comment by tcharp38** [comment]
Les liens que j'ai posé sont pour moi. Mémo.
Comme je t'ai dit ca va pas etre trivial d'ajouter ce support. Le cluster EF00 n'est pas standard donc il faut passer du temps à comprendre comment les autres s'en sont sortis.

Je vais tacher de trouver du temps pour creuser et revenir vers toi.

En attendant je te laisse me trouver une image PNG sans fond pour mettre en icone.

Autre chose, tu peux aussi refaire une recherche et quand tu arrives sur ce fameux bouton qui reste orange, tu le cliques à nouveau puis me file le log parser. Je vais tacher de comprendre ce qui se passe pour ce cas. 
Merci

**Comment by Proft1972** [comment]
Bonjour, désolé pour le temps de réponse mais j'ai eu des soucis et je n'ai pu répondre aussitot.
voici le   fichier demandé et la photo de la tete thermostatique. Encore désolé
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/7784270/AbeilleParser.zip)

**Comment by Proft1972** [comment]
cette photo est la derniere version:
![tete thermo2](https://user-images.githubusercontent.com/93400394/147559381-3f641d90-6295-4a14-b4fb-253abdcd9a06.png)

**Comment by tcharp38** [comment]
Salut @Proft1972 
Just back. J'ai pris ton image. Merci.

Peux tu basculer sur la beta  211230-BETA-1, derniere de l'année ?
Il faut que je me replonge dans ce sujet donc on refera des essais d'ici peu sur ce cluster particulier.

**Comment by Proft1972** [comment]
Bjr @tcharp38
je n'ai pas  de mise à jour dispo
![image](https://user-images.githubusercontent.com/93400394/147760257-e51f11c3-c544-4ffb-b3c1-7b5a1e9ae718.png)

Y a t il qqch à faire?

**Comment by tcharp38** [comment]
Si tu es deja sur la beta, tu devrais avoir demain une proposition de mise à jour. Donc patiente...

**Comment by tcharp38** [comment]
@Proft1972 
Maintenant qu'il y a des progres cote support d'un cluster EF00 specifique Tuya, ca va peut etre m aider ici aussi.
Peux tu me filer un package de logs avec l'adresse de ce device, et qq actions dessus ?

**Comment by Proft1972** [comment]
[AbeilleLogs-220317.tar.gz](https://github.com/KiwiHC16/Abeille/files/8288631/AbeilleLogs-220317.tar.gz)
voici le package de log, je ne sais pas , mais j'ai fait plusieurs manip sur la tete: ID 474

**Comment by tcharp38** [comment]
Pour info, j'avoue que je ne sais pas comment proceder pour avancer la dessus.
C'est que du specifique Tuya donc ca ne suit aucun standard.

Tu peux déja, si tu as basculé sur la derniere beta, me remettre un package de logs. Je devrais avoir + de details que la derniere fois.

**Comment by Proft1972** [comment]
[AbeilleLogs-220322.tar.gz](https://github.com/KiwiHC16/Abeille/files/8326214/AbeilleLogs-220322.tar.gz)
voici le le package de log avec la nouvelle beta, si tu n'y arrive pas ce n'est pas grave, c'est déjà bien d'avoir essayé!

**Comment by tcharp38** [comment]
@Proft1972 
Je suppose que tu as déja installé cette tete sur un radiateur n'est ce pas ?

**Comment by Proft1972** [comment]
Hello @tcharp38 
Non pas encore, je l'ai sur mon bureau pour faire les essais

**Comment by tcharp38** [comment]
Ha du coup ca te dis de me l'envoyer que je bosse directement dessus quand je trouve du temps ?

**Comment by Proft1972** [comment]
Pas de soucis mais avant, il faut que je trouve un robinet thermo car quand on met les piles, elle fait un aller retour de calibration et si il n'y a pas de robinet ça plante, jusque là j'ai mamaillé pour que cela fonctionne mais comme je dois en acheter un...

**Comment by Proft1972** [comment]
Hello,, j'ai trouvé un robinet, communique moi ton adresse en MP que je puisse te l'envoyer ainsi que la smart box.

**Comment by tcharp38** [comment]
Pour info, je l'ai bien reçu.
Pour l'instant j'arrive à capturer l'état du "set point" venant du thermostat, et j'arrive à le modifier à distance.

Saurais tu me résumer ce que tu attends comme commandes info & actions ?

**Comment by Proft1972** [comment]
Hello,
je voudrais pouvoir lire la temperature actuelle, programmer une température, changer le mode (eco, vacances et manu je crois) et eventuellement l'état des piles

**Comment by tcharp38** [comment]
Ca progresse
![image](https://user-images.githubusercontent.com/35221038/163572926-3f4d90a8-4df4-4a53-b92e-6968ce9a108e.png)

**Comment by Proft1972** [comment]
Je vois ! impecable!

**Comment by tcharp38** [comment]
Je reviens sur le sujet.
Cette tete supporte des tas de trucs qui font du sens quand elle est autonome, mais plus quand elle est controllée par un systeme domotique. Tout implementer pour ne pas s'en servir prendrait beaucoup de temps pour rien.

Bref... avoir un retour de temp et pouvoir changer la consigne ca fait du sens.
Le mode ? Pourquoi faire ? Quel but sachant qu'un scenario couvre le sujet. Ca m'echappe.
Idem pour la programmation que la tete supporte. Le scenario joue ce role avec Jeedom.
Du coup comment penses tu utiliser le "mode" ?

**Comment by Proft1972** [comment]
C'est parce que le mode etait existant mais il est vrai que l'on peut gerer avec un scenario donc juste la consigne et la temp actuelle doivent suffire!

**Comment by tcharp38** [comment]
J'avoue ne pas savoir ce que font ces "modes". Du coup peut être que plusieurs font du sens d'un point de vue box domotique. Tu peux creuser ?

**Comment by Proft1972** [comment]
Salut @tcharp38 d'apres mes recherches, le mode auto peut être programmé depuis un smartphone d'apres un agenda suivant l'occupation du local, le mode vacances met une temp fixe et dans le mode manuel la tete suit la temp affichée:  dans tous les cas, tout peut être fait depuis jeedom, il faudra juste que tu me dise en quel mode (je pense manu)  je dois me mettre pour programmer depuis jeedom

**Comment by tcharp38** [comment]
Salut @Proft1972 
Désolé pour ce sujet qui a bien trainé.
Je viens de reprendre pour essayer de le cloturer mais il ne reste que qq jours et je coupe jusqu'au 2 janvier.
Tout ça pour dire que la suite ne sera qu'en 2023.

**Comment by tcharp38** [comment]
@Proft1972 
Tu me tiens au jus pour la tete ? Ce qui est ok, ce qui ne l'est pas encore.
Merci

**Comment by Proft1972** [comment]
Salut,
Pour le moment, tout parait OK, la remontée de temp n'est apparemment que toute les 10 min?
Check on ,off, status correspondent à quoi?

**Comment by tcharp38** [comment]
Salut
J'ai vu que la tete ne renvoi des infos que si on fait un "check on".
Mais dans ce cas elle en envoi non stop.
Du coup je fais un "check on" toutes les 10mins et un off tout de suite derriere.

Par contre si tu changes la valeur directement sur la tete, normalement elle est aussitot reportée vers Jeedom

**Comment by tcharp38** [comment]
@Proft1972 
Je peux clore ce sujet ?

**Comment by tcharp38** [comment]
@Proft1972 
Je clos. A réouvrir si le moindre souci sur cette tête.
Merci
