### ISSUE TITLE
[KiwiHC16] Add a Reset button in the parameters of a zigate. Not to go to the command page.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2176]

**Comment by tcharp38** [comment]
Tu parles d'un bouton qui envoie la commande 0011 ?

Tu as une use case que je comprenne comment tu l'utilises ?
Merci

**Comment by KiwiHC16** [comment]
C est la commande reset de la Zigate. Oui la commande 0011. 
Je l utilisé en cas de debug. 
Par exemple j avais une Zigate qui avait un comportement très très bizarre. De temps en temps pas moyen d envoyer un on/off sur des prises alors qu un getEtat fonctionnait. Seule solution, coupure de jus de la Zigate. Le reset soft 0011 ne semble pas fonctionner. 
Donc deux sujets, faire un bouton user friendly au lieu d aller dans les commandes. 
Vérifier que la commande 0011 fonctionne bien. 

Depuis je pense avoir trouvé la source du soucis. Une prise aqara au format asiatique (une de mes toutes premières prises au début du projet). Depuis retrait plus de soucis. Elle doit trigger un bug Zigate car même en changeant le hardware Zigate et mis le dernier software j'avais toujours le soucis.

**Comment by tcharp38** [comment]
Dispo dans le master

![image](https://user-images.githubusercontent.com/35221038/144462997-50acd810-32c8-41c7-b240-af923413d6d0.png)

Je te laisse clore le sujet si ca correspond à la demande.

**Comment by tcharp38** [comment]
Je clos. Ca devrait correspondre à la requete mais a reouvrir si ca n'est pas le cas.
