### ISSUE TITLE
[KiwiHC16] Modals size issue.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2177]
![Capture d’écran 2021-10-30 à 15 09 51](https://user-images.githubusercontent.com/8549674/139535722-021e7150-94be-4c73-946c-9eec2c5ac6e6.png

![Capture d’écran 2021-10-30 à 15 10 05](https://user-images.githubusercontent.com/8549674/139535725-9300c77d-58da-4819-9460-b477a74f1141.png)

Clic roue crantée:

![Capture d’écran 2021-10-30 à 15 10 13](https://user-images.githubusercontent.com/8549674/139535731-84980924-7e73-442f-b8e6-62ad2a8baa4b.png)
)

Mauvaise taille de modal.

Problème uniquement visible sous le plugin Abeille

**Comment by tcharp38** [comment]
J'ai effectivement ca de temps en temps et depuis tres longtemps.
Il doit y avoir un cas de figure mal géré par Abeille mais jamais compris ni vraiment cherché.
Je crois cependant que c'est lié à la précédente modale ouverte.
A creuser

**Comment by Kenderv** [comment]
Bonjour,
J'ai également ce problème assez régulièrement mais je n'avais pas noté que c'était seulement sous le plugin Abeille. Je fais un Ctrl+F5 pour vider le cache et cela revient normalement.....jusqu'à la prochaine fois

**Comment by tcharp38** [comment]
Qqn sait reproduire ca de maniere systematique ?
Pour moi c est la plupart du temps nickel.

**Comment by Kenderv** [comment]
Comme déjà indiqué plus haut, je n'avais pas remarqué que c'était seulement sur des équipements gérés par Abeille. En revanche, ce dont je suis sûr c'est que un Ctrl+F5 rétablit l'affichage correct. Peut-être un début de début de piste ?
Bonne journée

**Comment by tcharp38** [comment]
le ctrl F5 efface le cache et recharge une page toute neuve. Donc on perd toutes les actions intermediaires qui ont pu produire le defaut.

**Comment by KiwiHC16** [comment]
F5 je suppose que vous utilisez Firefox...

Je suis avec Safari sur Mac.

Voici comment je fais sur mon systeme de dev par exemple:

Juste une ruche et une ampoule

![Capture d’écran 2021-12-17 à 11 42 26](https://user-images.githubusercontent.com/8549674/146532428-b8c83b27-4cfc-45aa-be3b-58f20b1866b3.png)

Selectionne l ampoule

![Capture d’écran 2021-12-17 à 11 42 38](https://user-images.githubusercontent.com/8549674/146532463-76360a0c-9e69-454e-bcf1-98c7660df96b.png)

Selectionne parameters

![Capture d’écran 2021-12-17 à 11 42 58](https://user-images.githubusercontent.com/8549674/146532516-3ae48a3e-2486-4827-a3c7-75b1a76cf8d5.png)

Selectionne roue de la premiere commande. 

![Capture d’écran 2021-12-17 à 11 43 19](https://user-images.githubusercontent.com/8549674/146532567-9e11db13-f16e-4695-bcef-34411def3d1e.png)
La taille n'est pas bonne et si vous regardez bien la croix en haut a droite semble en cachée une autre car on voit deux petit point noir juste en dessous.

Si je refresh la page, puis tab parametres, puis roue crantée alors la taille est bonne.

**Comment by Kenderv** [comment]
Bonjour,
Non, je suis sur Chrome. Je fais exactement les mêmes manips, parfois j'ai la fenêtre ouverte correctement, par fois j'ai la fenêtre réduite. Ctrl+F5 ou Actualiser la page restaure la fenêtre correctement. En ce moment je n'ai pas ce problème, jusqu'à quand ?????
Bon week-end

**Comment by tcharp38** [comment]
Je ne reproduis pas non plus sous Edge ou Chrome. Mais je reconnais voir ce souci de temps en temps. Ca va pas etre simple.

**Comment by mickadam29** [comment]
Le problème semble corrigé avec la version 4.2.7 de Jeedom. Depuis la mise à jour je n'ai plus ce phénomène. Sous Chrome @tcharp38 j'avais le même problème que semble-t-il tu ne reproduis pas

**Comment by tcharp38** [comment]
Si je reproduis mais jamais de maniere systematique. C est ca qui complique le debug.
Et toujours d'actualité pour moi je crois en 4.2.7. Mais à confirmer

**Comment by edgd1er** [comment]
Pour reproduire: 
* ctrl + f5 sur la page d'accueil: /index.php?v=d&p=dashboard.
* prendre n'importe quel objet lié a la zigate, aller dans commandes et cliquer sur un engrenage de n'importe quelle commande.
* Voir une modal minuscule.

fermer et rouvir la modal permet d'avoir la bonne taille.
une erreur en console est affichée au chargement de la page de l'objet Abeille: 
`Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16/`
il doit manquer une initialisation de la lib highcharts ou une init est déclenchée sans le vouloir.

piste: 
lors du l'execution de la commande: sur le plugin abeille, la modal est erronée. sur un autre plugin, la modal est correct.
`$('#md_modal').dialog().load('index.php?v=d&modal=cmd.configure&cmd_id=' + $(this).closest('.cmd').attr('data-cmd_id')).dialog('open')`


Firefox 96 / linux / jdm 4.2.7

**Comment by tcharp38** [comment]
Merci @edgd1er 
A priori c est bien reproductible par ta methode. Je creuse.

**Comment by mickadam29** [comment]
La manip de @edgd1er ne produit pas le pb chez moi. Le passage en 4.2.7 a solutionné le pb que je rencontrais fréquemment. Disons que je suis chanceux alors.

Chrome est à jour
Version 97.0.4692.99 (Build officiel) (64 bits)

Etes-vous à jour des modules ?

![image](https://user-images.githubusercontent.com/36518012/152028545-20c084ac-a95b-4448-ae2b-9c7ca7782d3f.png)

**Comment by mickadam29** [comment]
J'aurai dû m'abstenir de tester la manip de @edgd1er  !! Depuis, si Abeille ne pose pas de problème de Modal, ce sont les autres !

Voici un exemple d'un plugin qui n'est plus bon. La mise en page est totalement incohérente 

![image](https://user-images.githubusercontent.com/36518012/152029707-1d353776-773f-4524-bb1a-d53d65d8bd62.png)

**Comment by mickadam29** [comment]
Je vérifierai demain sur un autre poste si j'ai le même affichage défectueux

**Comment by tcharp38** [comment]
Surement des trucs qui trainent dans le cache apres mise à jour.
Le CTRL F5 repart de 0 en effacant le contenu local.

**Comment by edgd1er** [comment]
au rechargement depuis l'accueil, la modal utilise le span id ui-id-5 a chaque fois, quand on reclique sur l engrenage, c'est le span id ui-id_2 qui est utilisé a chaque clic.
la span ui-id-5 a une largeur de 300px.
Il y a tellement de js que c'est difficile de comprendre qui fait quoi.

**Comment by tcharp38** [comment]
Je viens de pousser une modif dans le master.
Grace à la facon de reproduire d'edgd1er, je crois avoir cerné le pb, disparu chez moi du coup mais a voir à la longue.

**Comment by mickadam29** [comment]
Salut

Je testerai ce soir
Mais comme indiqué, en faisant la manip de @edge1er j’ai créer le pb sur le plugin Conso. Donc rien à voir avec Abeille. Le problème est peut être plus global à Jeedom. Car d’ailleurs, en 4.2.7, le problème avait disparu chez moi. Faut dire aussi que je ne faisais de ctrl F5 sous Chrome. Jeedom a déjà poussé la 4.2.8 en beta

**Comment by Kenderv** [comment]
Bonjour, 
Pour moi le problème n'est pas réglé avec la V 4.2.7 de Jeedom. 
![image](https://user-images.githubusercontent.com/52486183/152371844-0fdd48ee-eade-4520-929b-f77c5e73e6ba.png)

**Comment by KiwiHC16** [comment]
Vous êtes trop fort. Je viens de tester et ne parviens pas à retrouver le problème.
Je ne clos pas encore mais ca sent bon.

**Comment by edgd1er** [comment]
En 4.2.8, je n arrive plus a reproduire le pb. Je suis a jour sur le dernier master.

**Comment by tcharp38** [comment]
Je clos le point en estimant que c'est fixé cette fois.
Mais à reouvrir si besoin.
