### ISSUE TITLE
[KiwiHC16] Loose tab alignement

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2178]
We can see 3 tabs
![Capture d’écran 2021-10-30 à 16 01 26](https://user-images.githubusercontent.com/8549674/139536033-e5a1c415-60c8-49dd-af02-3e51f2fe61f4.png)

we can see the tabs anymore if we click on the second or third one:
![Capture d’écran 2021-10-30 à 16 02 28](https://user-images.githubusercontent.com/8549674/139536059-01b354f2-6f0a-4494-ba41-6b17e86c3fbf.png)

**Comment by KiwiHC16** [comment]
Si j enleve la partie script de AbeilleEp.php je n'ai plus le soucis.

**Comment by KiwiHC16** [comment]
function addCmdToTable(_cmd) {

semble être la source du soucis

**Comment by KiwiHC16** [comment]
En fait ca semble lié à la longueur de la page. Si la page est plus courte que la fenêtre du browser pas de soucis, si la page est plus longue alors le browser aligne le haut sur le haut de la sous page et masque les boutons tout en haut...
Je ne sais pas pourquoi ...

**Comment by KiwiHC16** [comment]
Pas se comportement sur le plugin Virtuel

**Comment by KiwiHC16** [comment]
Je n ai pas non plus se comportement sur un autre plugin que j ai fait sur la base du dernier template de plugin.

**Comment by KiwiHC16** [comment]
Comme je ne trouve pas, je pense qu'il faudrait repartir  du template et porter Abeille dedans.
Déplus il faudrait faire le menage dans ces fichiers car ils ont grossi et ca devient super dure à lire.

**Comment by tcharp38** [comment]
Revu. Comportement identique au plugin virtuel.
220518-BETA-1

Je clos. A reouvrir si besoin
