### ISSUE TITLE
Perte de communication Capteur xiaomi 

### ISSUE THREAD

**Issue by marcolabidouille91** [KiwiHC16/Abeille#2181]
Bonjour,
Les températures des pièces de mon domicile sont relevées par des sondes Xiaomi WSDCGQ11LM 
Je les ai bien intégré dans le plugin Abeille, elles fonctionnent pendant un certain temps mais au bout d un certain temps, le plugin Abeille ne récupère plus les infos du capteurs.
Pour que ca remarche, il faut que j exclus la sonde et la réintègre.
Si je me mets en surveillance sur la sonde, je n'ai rien qui remonte de la sonde lorsque je la réveille en appuyant sur le bouton.
[AbeilleLogs-211107.tar.gz](https://github.com/KiwiHC16/Abeille/files/7491980/AbeilleLogs-211107.tar.gz)
Merci

Marc

**Comment by tcharp38** [comment]
Salut @marcolabidouille91 
J'en ai moi aussi plusieurs de ces capteurs qui au premier abord sont tres attractifs (joli design compacte et super abordables).
Mais la realité est que j'en perd sans arret.
A priori ils ont besoin d'un maillage tres serré.

Bref pas surpris du tout par ta remarque. Tu trouvera des tas de "plaintes" de ce type sur le net.
Je ne vois rien de particulier dans tes logs mais qq pistes
- verifier LQI des capteurs que tu perds et ajouter repeteur
- position zigate et ajout antenne si jouable
- pb reseaux ou conflit Wifi ? ce dernier peut parasiter le zigbee. Ca aide pas

**Comment by tcharp38** [comment]
Je ferme le point.
Les Xiaomi sont surement les pires des periphs.
En tout cas rien d'evident pour lequel il y a qqch a faire côte Abeille.
