### ISSUE TITLE
Ajout télécommande profalux sur volet existant

### ISSUE THREAD

**Issue by TheTrueTom** [KiwiHC16/Abeille#2184]
Bonjour,
Merci tout d'abord pour votre travail sur le plugin qui fonctionne super bien.

J'ai un souci lors de l'inclusion d'un volet, celui-ci est bien détecté mais la télécommande d'origine ne fonctionne plus avec le volet.
J'ai voulu suivre la procédure profalux pour ajouter une télécommande supplémentaire à un volet.
Pour cela j'ai fait l'inclusion de la télécommande dans le réseau en suivant la procédure suivante :
- 5R - Réinitialisation de la télécommande
- Abeille en mode inclusion
- R-Haut - Pour que la télécommande rejoigne le réseau
- Sortir abeille du mode inclusion

Cela a bien fonctionné et la télécommande est annoncée dans abeille.

Pour assigner cette télécommande à un équipement je dois maintenant prendre une télécommande existante et appuyer sur haut et bas en même temps puis sur stop puis faire 2F-Haut sur la télécommande à associer. Mon problème et que je n'ai plus de télécommande associée à ce volet, seul Abeille l'est. Est-il possible de mimer les appuis Haut-Bas simultanés puis stop avec Abeille ? Ou existe-t-il une commande qui permet de le reproduire ?

Merci d'avance

Config :
PiziGate
RPi 4
Abeille : 2021-10-31 01:00:16
Firmware : 0105-031F

**Comment by tcharp38** [comment]
Salut @TheTrueTom 
Tu veux dire que tu peux piloter ton volet via Abeille mais plus d'une telecommande ? C'est ca ?

Si c'est le cas je n'ai jamais eu ce cas de figure. J'ai toujours considéré que l'appairage avec sa telecommande etait la priorité.
Donc si la telecommande ne fonctionnait plus il fallait recommencer et du coup via le reset "electrique".

Bref je ne sais pas si il y a une procedure autre qu'electrique pour reappairer la telecommande à son volet mais j'ai bien peur que non.

**Comment by TheTrueTom** [comment]
Salut @tcharp38,
c'est exactement ça, je peux le contrôler avec Abeille mais plus via sa télécommande qui n'est plus appariée depuis qu'inclusion dans Abeille.

Il existe bien une procédure chez Profalux pour rajouter une télécommande supplémentaire à un volet, et j'espérais pour l'utiliser pour ne pas avoir à refaire toute la procédure avec les fils.   [@@(Notice télécommande, voir page 2)](https://www.profalux-pro.com/download/1.%20Notices,%20Plans,%20Technique/1.%20Volets%20roulants/3.%20Moteurs%20Commandes%20et%20Accessoires/1.%20Moteur/Moteur%20Profalux%20Zigbee/Notice%20SAV%20Telecommande%20Zigbee%203.0%20-%20NSAV062.pdf)

Sur la notice jointe page 2, les étapes 1 et 2 se passent très bien mais pour ajouter la télécommande à un équipement il faut cliquer sur les boutons haut et bas en même temps. Cela n'est pas possible avec Abeille mais je me demandais si ça ne correspondait pas à une commande particulière que j'aurais pu utiliser.

Merci de l'aide !

**Comment by tcharp38** [comment]
J'avais déja vu ca dans la notice mais je ne le comprends pas.
Si tu n'as qu'1 volet peut etre que ca le fait mais si tu en as plusieurs, comment arrives tu a préciser le volet que la telecommande supplémentaire devra controler ?

D'ailleurs il y a cet encart
![image](https://user-images.githubusercontent.com/35221038/141973897-f9aa083d-02db-47f7-896d-85c25154a67d.png)

Bref la base de tout controle Profalux est que chaque volet a deja sa telecommande et c'est cette derniere qui permet d'envoyer des ordres ciblés au volet.

Mais la ou tu as raison est que tout ca se fait via Zigbee. Sauf que c'est entierement proprietaire et qu'il faudrait sniffer le reseau et faire du reverse pour comprendre la procedure.
As tu vu que c était possible avec d'autres soft domotique ? Par ex Domoticz ?

**Comment by TheTrueTom** [comment]
Je le comprends comme la possibilité de rajouter une seconde télécommande à un volet existant qui possède déjà une télécommande (seulement Abeille dans mon cas).
Pour préciser le volet qui devra être contrôlé, il faut prendre une télécommande existante du volet et appuyer sur haut et bas en même temps suivi de stop et après prendre la télécommande supplémentaire à ajouter et faire 2F+haut.

Vu qu'Abeille fonctionne pour moi comme une télécommande existante, ça devrait techniquement être possible de rajouter la télécommande si on pouvait envoyer la commande Haut+Bas depuis abeille, le stop existant déjà. Resterait à trouver à quelle commande cela correspond !

Je n'ai malheureusement pas de sniffer, donc pas trop de possibilité d'essayer avec un autre de mes volets.

Je n'ai rien trouvé sur Domoticz ou autre malheureusement.

**Comment by tcharp38** [comment]
La base est le couple volet+SA telecommande sinon aucun moyen d'envoyer un ordre au volet lui meme. Donc cet appairage de base est clef.

Ceci dit meme si theoriquement ca devrait etre possible de remplacer sa telecommande par Abeille, dans la pratique ce cas est assez rare. Je pense que ca ne vaut pas le coup de s'y attarder.

Bref il te faut refaire l'appairage volet <> telecommande et je jamais interrompre cette procedure.

J'ai galéré avec mes volets aussi.

Je clos ce sujet. Pas assez de temps pour creuser et comme je disais, rarement necessaire.
Bonne chance mais n'hesite pas à le reouvrir si tu penses qu'il fait toujours du sens.
