### ISSUE TITLE
Suppression de messages concernant un équipement qui n'existe plus

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2186]
Bonjour,
J'avais mis un équipement en surveillance. Je l'ai supprimé de Jeedom. Je récupère chaque jour un message :
![image](https://user-images.githubusercontent.com/52486183/141676998-8acc5fe7-3516-41e5-8b75-e5c9d88f4966.png)
Comment le supprimer ?
Merci et bon dimanche

**Comment by tcharp38** [comment]
Salut @Kenderv 
Effectivement ca apparait en erreur à chaque redemarrage des démons. Je vais corriger le tir mais la tu ne peux rien faire.

**Comment by Kenderv** [comment]
OK Merci et bonne soirée. Tu fais signe quand c'est OK ?

**Comment by tcharp38** [comment]
Ok sur la beta 211115-BETA-2 mais j'ai besoin de retours avant de la stabiliser

**Comment by Kenderv** [comment]
OK, j'installe la 211115-BETA-2 et je te tiens au courant.
Bonne journée

**Comment by Kenderv** [comment]
Sauf que je sais pas faire. J'ai téléchargé Abeille-211115-BETA-2.tar.gz, je l'ai ouvert et j'ai vu Abeille-211115-BETA-2.tar. Je suppose que c'est la sauvegarde du plugin Abeille qui remplace l'ancien dans html/plugins/Abeille. Y-a-t-il une procédure particulière ou simplement exécuter le tar (après backup du répertoire Abeille bien entendu) et relance du démon ?

**Comment by tcharp38** [comment]
Quand tu installes un plugin tu peux choisir la version "stable" ou la version "beta".
Voir la https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by Kenderv** [comment]
OK, mais si je réinstalle Abeille, je vais être obligé de tout réinclure ?

**Comment by tcharp38** [comment]
Non du tout.
Ce genre d'obligation n'apparait qu'a certains changements de firmware Zigate ou quand la table interne de la zigate devient corrompue.

**Comment by Kenderv** [comment]
Beta appliquée sans problèmes. Ouf ! Redémarrage de Jeedom, relance demons Tout est OK, je n'ai plus le message. Merci à toi et ravi d'avoir pu tester cette modif. Bonne journée

**Comment by Kenderv** [comment]
Dois-je fermer le problème ou bien tu t'en charges ?

**Comment by tcharp38** [comment]
Donc tu es sur la version qui devrait devenir stable.
J'attends lundi pour la transformer mais d'ici la n'hesite pas à me signaler toute regression. 
Si pas de retours d 'ici lundi je la transforme en stable et je continue.

Je cloture ce point.
A+

**Comment by Kenderv** [comment]
OK 
A+
