### ISSUE TITLE
Ajout sonde TS0222 / _TYZB01_kvwjujy9

### ISSUE THREAD

**Issue by orbital06** [KiwiHC16/Abeille#2191]
Bonjour, 

Serait-il possible d'ajouter cette sonde: 
![image](https://user-images.githubusercontent.com/23478355/141965537-32840617-e52a-4bdf-b394-cae204b9fa42.png)

J'ai mis plusieurs fichiers json car difficile de l'avoir au complet en une seul fois.
[json.zip](https://github.com/KiwiHC16/Abeille/files/7545370/json.zip)

Merci.

**Comment by tcharp38** [comment]
Salut @orbital06 
J'ai besoin de
- la marque
- le modele

Je ne comprends pas pourquoi tu as généré plusieurs fichiers. Tu peux demander une reinterrogation pour chaque bouton "orange" mais il faut reveiller l equipement en meme temps.

**Comment by orbital06** [comment]
Salut @tcharp38 , 

Alors j'ai été obligé de faire plusieurs fichiers car je n'avais pas de réaction dans Jeedom lorsque je voulais réinterroger.
J'ai été obligé de réinclure le module a chaque fois !

Pour le modèle et la marque les voici:
Sonde MOES ZigBee-THLe

https://www.domotique-store.fr/domotique/usages/meteo-environnement/sondes-thermometres-pour-stations-meteo-connectees-domotiques/1570-sonde-zigbee-de-temperature-hygrometrie-et-luminosite-compatible-tuya-lidl-eedomus-jeedom-ha-etc.html?search_query=ZIGBEE-THLe&results=78

Cldt.

**Comment by tcharp38** [comment]
[TS0222__TYZB01_kvwjujy9.zip](https://github.com/KiwiHC16/Abeille/files/7546617/TS0222__TYZB01_kvwjujy9.zip)

A tester
Décompresser dans "core/config/devices" du plugin Abeille
redemarrer Abeille
refaire inclusion

Pour l'interrogation vu qu'il est sur batterie tu n'as pas d'autre choix que de trouver comment le reveiller en meme temps.
N'y a t'il pas un bouton qui ferait ca ?

**Comment by orbital06** [comment]
Super merci de ton retour rapide.
Le bouton sur le coté sert a l'inclusion si pressé plus de 5 sec. il n'a pas l'air de réveiller le module par simple appuie.

Pour le test : alors le module est inclus.
![image](https://user-images.githubusercontent.com/23478355/141999378-2882b2da-9679-4d48-a0f5-496bd1f6c0aa.png)

Mais les informations ne remontent pas.
On dirais qu'ils manque la valeur en lux également.
![image](https://user-images.githubusercontent.com/23478355/141999196-9316551c-8be2-4ecd-ad72-0c32cd6f71ed.png)

As-tu besoin d'autre chose ?

**Comment by tcharp38** [comment]
Assures toi d'etre en mode debug, 5000 lignes de log.
Laisses tourner un peu
et file moi un package (page support/telecharger tout).

D'ailleurs tu es sur une stable ou beta ?
Si tu es partant pour tester une beta je suis preneur. Besoin de retours.

**Comment by orbital06** [comment]
Je suis en stable, mais je peux faire des tests si besoin.
[AbeilleLogs-211116.tar.gz](https://github.com/KiwiHC16/Abeille/files/7547320/AbeilleLogs-211116.tar.gz)

**Comment by tcharp38** [comment]
Ok si tu n'as pas refait d'inclusion son adresse est toujours 8804 et je ne vois rien du tout remonter.
C'est bien le cas ?

D'autre part, tu n'as que 500 lignes de log. A corriger: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by orbital06** [comment]
Désole, j'avais refait une inclusion.....adresse en 8827.
Voici les logs :
[AbeilleLogs-211116 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/7547701/AbeilleLogs-211116.2.tar.gz)
n!

**Comment by orbital06** [comment]
Pour info complémentaire, depuis que le module est inclus, j'ai des valeurs 0 sur l'affichage.
Ras sur mes autres modules qui ne sont pas inclus.

**Comment by tcharp38** [comment]
Ok, tu devrais avoir au moins une valeur sur Illuminance.
Je la vois remonter.
Pour la temp et l'humidité il y a un souci, normalement corrigé avec ce fichier

[TS0222__TYZB01_kvwjujy9.zip](https://github.com/KiwiHC16/Abeille/files/7547783/TS0222__TYZB01_kvwjujy9.zip)


Ha je sais pourquoi tu ne vois pas illuminance.
Il te manque ce fichier à decompresser dans core/config/commands
[zb-0400-MeasuredValue.zip](https://github.com/KiwiHC16/Abeille/files/7547919/zb-0400-MeasuredValue.zip)

**Comment by orbital06** [comment]
J'ai mis a jours et ajouter le fichier manquant.
Toutes les valeurs sont maintenant présente sur le Dashboard. 

Mais il y a un mais, elle sont toute a 0. et ceux même sur la sonde physiquement. Pas de pb avec les sondes non incluse.
Et par rapport a la version précédence ou seul les LUX était a 0 ici toute les valeurs le sont.
J'ai même un msg E1 sur la valeur degrés que je switch physiquement sur la sonde de degrés a fahrenheit.

adresse en 7BD8
log :
[AbeilleLogs-211116 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/7548121/AbeilleLogs-211116.3.tar.gz)

**Comment by tcharp38** [comment]
Nous y voila. Je crois que ca se complique.
J'ai commencé à fouiller le net pour cette sonde et j'ai cru voir ce genre de soucis "E1".

C'est le periph lui meme qui renvoi 0.
Ex pour la temp

> [2021-11-16 16:08:13] Abeille1, Type=8102/Attribute report, SQN=02, Addr=8827, EP=02, ClustId=0402, AttrId=0000, AttrStatus=00, AttrDataType=29, AttrSize=0002
> [2021-11-16 16:08:13]   **Temp, MeasuredValue=0000 => 0C**

Il faut creuser maintenant pour comprendre pourquoi il fait ca.
Ca pue... https://github.com/Koenkk/zigbee2mqtt/issues/7535

**Comment by orbital06** [comment]
Effectivement !

**Comment by tcharp38** [comment]
Tiens, a retenter
[TS0222__TYZB01_kvwjujy9.zip](https://github.com/KiwiHC16/Abeille/files/7553308/TS0222__TYZB01_kvwjujy9.zip)

- decompresser
- redemarrer Abeille
- refaire inclusion
- me filer le package de logs (reverifie que tu es bien à 5000 lignes de log) au bout de 2 mins par ex

**Comment by orbital06** [comment]
C'est fait.
Pour le moment je n'ai pas vu de pb sur les valeurs a 0 a voir dans le temps
J'ai quand même E1 un msg E1 sur la valeur degrés que je switch physiquement sur la sonde de degrés a fahrenheit.

Voici les logs id : E561
[AbeilleLogs-211116 (6).tar.gz](https://github.com/KiwiHC16/Abeille/files/7553493/AbeilleLogs-211116.6.tar.gz)

Bon toutes les valeurs sont passées a 0 !
En complément j'ai retirer la pile 2-3 fois pour forcer la maj des valeurs.
J'ai constaté que le message E1 apparait  lorsque le module communique la première fois, mais tout le temps.

De plus la valeur en lux n'est pas bonne alors que dans le log abeilleparser.log oui :
[2021-11-17 14:30:19]   Illuminance, MeasuredValue=4498 => 57.003300221896Lx
[2021-11-17 14:30:19]   MeasuredValue, hexValue=4498 => 17560
La valeur dans Jeedom est 17560 et non 57.003.....

Je te rajouter des logs si cela peux aider.
[AbeilleLogs-211116 (7).tar.gz](https://github.com/KiwiHC16/Abeille/files/7554956/AbeilleLogs-211116.7.tar.gz)

**Comment by tcharp38** [comment]
Ce device semble vraiment etre tres capricieux. Je vois qu'il remonte par moments toutes les infos (temp, humidité, lumiere) et parfois il decide de renvoyer 0.

Cote mauvaise valeur lumiere je crois que je m'y attendais. Faut que je corrige le tir mais sur les autres soucis je sais pas comment avancer.

**Comment by orbital06** [comment]
Super merci pour ton retour !

**Comment by tcharp38** [comment]
Tiens, essaie ca pour la lumiere
[zb-0400-MeasuredValue.zip](https://github.com/KiwiHC16/Abeille/files/7555653/zb-0400-MeasuredValue.zip)

Si tu fais "recharger" dans la page EQ/avancé ca devrait suffire à mettre la commande à jour

**Comment by orbital06** [comment]
Cela fonctionne ! 
Super, merci.

Affaire a suivre pour le reste !

**Comment by tcharp38** [comment]
J'avoue que je seche et comme j'ai pas cet equipement je ne peux pas faire d'autres essais. 
Alors si tu trouves d'autres infos, n'hesite pas à les ajouter ici.

**Comment by orbital06** [comment]
Alors pour chipoter avant d'avancer sur les valeurs a 0.
Si possible de faire les calculs directement par le json.
°C a diviser 100.
% d'humidité a diviser par 100 aussi. 
C'est faisable dans les config Jeedom, mais si ont a rien a faire c'est mieux :-)

Encore Merci.

**Comment by tcharp38** [comment]
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7556566/commands.zip)

corrections
pour core/config/commands
puis "recharger" JSON

**Comment by orbital06** [comment]
C'est changé nickel 👍.
Je fais des tests maintenant et reviens vers toi si je trouve des éléments permettant de corriger ces valeurs a 0 !

Encore Merci.

**Comment by tcharp38** [comment]
On en est ou sur ce sujet ? On peut le fermer ?
Note; la beta est la version la + recente. Elle restera telle quelle cette année et je ne la passe en stable en 2022 pour cause d'absence.

**Comment by orbital06** [comment]
Bonjour,

Oui tu peux clôturer le sujet. Les sondes ont été reprisent par le site.

Merci !
