### ISSUE TITLE
intégration ORVIBO ST30 - Capteur de température et humidité Zigbee

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2193]
Bonjour KiwiHC16,

J'ai tenté d'inclure un module ORVIBO, le ST30. Or celui-ci est vu comme un module non reconnu alors qu'il existe dans la liste des modules compatibles un module très similaire (en tout cas d'aspect) qui est le "Thermomètre Zigbee Ewelink".

Y a t'il un moyen pour faire en sorte que le plugin abeille reconnaisse le module ORVIBO ?

D'avance merci pour les infos que vous pourrez m'apporter.

Cordialement,
Thierry

Version Abeille
2021-10-31 01:00:16 
Pizigate firmware version 0003-031C

**Comment by tcharp38** [comment]
Salut @Thiematz 
Peux tu generer un discovery.json ? https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

Je note que tu as un FW 3.1C. Je te suggere de passer en 3.1D au moins. De nombreuses fonctionalités interne ont besoin de cette version minimale.

**Comment by Thiematz** [comment]
Salut @Tcharp38,

merci d'avoir pris le temps de m'aider.
Tout d'abord j'ai essayé de mettre à jour ma Pizigate, mais je rencontre les erreurs suivantes. Visiblement un problème de droits

```
[2021-11-17 16:42:23] Démarrage de 'checkWiringPi.sh'
[2021-11-17 16:42:23] Vérification de l'installation du package 'WiringPi'
[2021-11-17 16:42:23] = Ok
[2021-11-17 16:50:25] Démarrage de 'checkWiringPi.sh'
[2021-11-17 16:50:25] Vérification de l'installation du package 'WiringPi'
[2021-11-17 16:50:25] = Ok
[2021-11-17 16:50:45] Démarrage de 'checkWiringPi.sh'
[2021-11-17 16:50:45] Vérification de l'installation du package 'WiringPi'
[2021-11-17 16:50:45] = Ok
[2021-11-17 16:50:48] Démarrage de 'checkTTY.sh'
[2021-11-17 16:50:48] Vérifications du port '/dev/ttyAMA0'
[2021-11-17 16:50:48] = Ok, le port semble libre.
[2021-11-17 16:50:56] Démarrage de 'checkTTY.sh'
[2021-11-17 16:50:56] Vérifications du port '/dev/ttyAMA0'
[2021-11-17 16:50:56] = Ok, le port semble libre.
[2021-11-18 12:08:49] Démarrage de 'checkWiringPi.sh'
[2021-11-18 12:08:49] Vérification de l'installation du package 'WiringPi'
[2021-11-18 12:08:49] = Ok
[2021-11-18 12:08:57] Démarrage de 'checkTTY.sh'
[2021-11-18 12:08:57] Vérifications du port '/dev/ttyAMA0'
[2021-11-18 12:08:57] = Ok, le port semble libre.
[2021-11-18 12:08:57] Vérification de l'installation du package 'WiringPi'
= Ok
[2021-11-18 12:08:57] Configuration des GPIOs
[2021-11-18 12:08:57] = Ok
[2021-11-18 12:08:57] Configuration du port série
[2021-11-18 12:08:57] = Ok
Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0
Vérifications préliminaires
Compilation du programmateur
mkdir ../../../tmp/JennicBuildDir/
mkdir: cannot create directory '../../../tmp/JennicBuildDir/': No such file or directory
make: *** [Makefile:68: ../../../tmp/JennicBuildDir/] Error 1
= ERREUR: Compilation ratée !
chmod: cannot access '/var/www/html/plugins/Abeille/core/ajax/../../tmp/JennicModuleProgrammer': No such file or directory
= ERREUR: Le programmateur Jennic n'est pas exécutable !
=         /var/www/html/plugins/Abeille/core/ajax/../../tmp/JennicModuleProgrammer
``
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7563094/discovery.zip)
`
Voici le Discovery.zip, mais pas sur que cela soit bon. Je l'ai généré à distance, sans réveiller l'équipement.
S'il faut, je le refait ce soir ;-)

Bonne aprem

**Comment by tcharp38** [comment]
Tu as mis le doigt sur un bug si le repertoire "tmp" n existe pas.
Du coup utilises le fichier corrigé
[Makefile.zip](https://github.com/KiwiHC16/Abeille/files/7563458/Makefile.zip)
Ce fichier va dans "resources/prog_jennic-0.7/build/"
ou cree un repertoire "tmp" dans le plugin Abeille (core, desktop, resources... etc et tmp)

Ton discovery.zip n'a pas été ajouté

**Comment by Thiematz** [comment]
Génial, merci beaucoup @tcharp38 
= Success
- Ok. Programmation faite
Redémarrage de la PiZiGate
= Tout s'est bien passé. Vous pouvez fermer ce log.

J'ai d'autres version proposées, 
3.1e-OPDM
3.1e-Legacy
3.20-OPDM
3.20-Legacy

Saurais-tu me dire la différence entre OPDM et Legacy

Tant qu'à faire, autant faire les maj, non?



[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7563818/discovery.zip)

**Comment by tcharp38** [comment]
La + recente est la 3.20.

L'equipe Zigate recommande une version OPDM (Optimized) mais cela necessite de refaire un reappairage complet si tu viens d'une version "legacy". Donc si t'es pas tenté par l'experience, tu reste en legacy avec la 3.20-Legacy.
Dans tous les cas il te faut une version >= 3.1d

**Comment by tcharp38** [comment]
[898ca74409a740b28d5841661e72268d.zip](https://github.com/KiwiHC16/Abeille/files/7564377/898ca74409a740b28d5841661e72268d.zip)

A decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion
tester

Je te laisse trouver une image PNG sans fond à mettre en icone.

**Comment by Thiematz** [comment]
Merci, je testerai ce soir ou ce we.

Le nom "898ca74409a740b28d5841661e72268d" est important ou je peux le changer par quelque chose de plus lisible ?

**Comment by tcharp38** [comment]
Très important. C'est son identifiant zigbee alors inchangeable. Autrement dit c'est le nom qu'il donne

**Comment by Thiematz** [comment]
Bonjour @tcharp38,

ok, je comprends l'importance du nom, merci.
Le module est reconnu, mais pas top!
La température est affichée sans virgule, je m'explique. 21.54° s'affiche 2154
L'humidité reste à zéro, aucune réaction.

Te faut-il d'autres infos pour y remédier ?

Merci et bonne fin de dimanche ;-)

**Comment by tcharp38** [comment]
Salut @Thiematz 
Cote temp, je pense que c'est corrigé avec ce fichier à venir dans la prochaine beta.
[zb-0402-MeasuredValue.zip](https://github.com/KiwiHC16/Abeille/files/7581842/zb-0402-MeasuredValue.zip)

A decompresser dans "core/config/commands" puis recharger JSON via page EQ/Avancé

Côte humidité aucune idée.
J'ai besoin d'un package de logs (page support/telecharger tout).

**Comment by tcharp38** [comment]
La 211122-BETA-1 regroupe tout le support du moment pour ce periph

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

J'ai mis en place le fichier, mais c'est pire, j'ai plus aucune info, ni temp, ni humidité. Ces 2 commandes sont également absentes de l'onglet commande.

Voici le package de log
[AbeilleLogs-211123.tar.gz](https://github.com/KiwiHC16/Abeille/files/7588744/AbeilleLogs-211123.tar.gz)

Merci pour ton aide

**Comment by tcharp38** [comment]
Salut
Tes logs sont quasi vides. J'imagine que tu n'es plus en mode debug. Tu peux verifier ?
Tu es sur la 211121-STABLE-1 ?

**Comment by Thiematz** [comment]
Re,
effectivement je n'étais plus en debug. Je viens de le changer. J'imagine qu'il faut attendre un peu?
J'ai rechargé l'EQ depuis l'onglet "avancé" et voici les logs, s'ils sont déjà parlant ?

Je suis bien sur la 211121-STABLE-1
[AbeilleLogs-211123(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7589159/AbeilleLogs-211123.1.tar.gz)

**Comment by tcharp38** [comment]
Bah non. Je pige pas d'ou tu sors ca.
Regarde le log AbeilleParser par ex. Il contient la date du "2021-11-18 19:38:55"

**Comment by Thiematz** [comment]
D'ou je sors quoi ?
Tiens, deux captures d'écran qui en diront peut-être plus
![Config_plugin](https://user-images.githubusercontent.com/94549335/143062316-f5e6f2f4-fd4b-4310-8424-5a446e7f8c4a.JPG)
 
![Config_plugin2](https://user-images.githubusercontent.com/94549335/143062348-e4d36d80-b8e5-4b80-b8e7-e4f1bac16839.JPG)

**Comment by tcharp38** [comment]
Je ne vois pas de souci particulier.
Mais regarde le log du Parser. Il donne la date du 18 nov et rien d'autre. Comme si c etait un vieux log.
Verifie, efface le, et relance le démon STP. Ces logs sont incoherents. Il doit y avoir des evenements du jour.

**Comment by Thiematz** [comment]
ok, effectivement, ca bavarde beaucoup plus.
Question : la maj du plugin d'y a 2j n'aurait-elle pas écrasé le JSON du module que tu m'as envoyé ?
Je demande ça parce que lorsque je veux recharger le module il me dit qu'il est inconnu et qu'il utilise le modèle par defaut (sans les commandes temp et hum du coup
[AbeilleLogs-211123(2).tar.gz](https://github.com/KiwiHC16/Abeille/files/7589754/AbeilleLogs-211123.2.tar.gz)
)

**Comment by tcharp38** [comment]
Ha oui ça doit être le cas. Tout fichier non identifié est normalement nettoye. Donc à remettre. Mais l histoire du log n'a rien à voir

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

Je ne comprends plus rien, le module n'est plus reconnu correctement et aucune commande (Temp et Hum) n'est disponible dans les commandes du modules.
Je joins les logs du support si cela peut te permettre d'y voir plus clair ;-)
[AbeilleLogs-211124.tar.gz](https://github.com/KiwiHC16/Abeille/files/7599005/AbeilleLogs-211124.tar.gz)

Encore merci pour ton aide

**Comment by tcharp38** [comment]
Attention. Ce support n'est que dans la beta 211122-BETA-1
Si tu es passée sur la derniere stable il a du faire le menage des fichiers non officiels et du coup tu dois a nouveau remettre le JSON que je t'ai filé, puis redemarrer Abeille et refaire une inclusion.

Je ne vois pas d'inclusion dans tes logs du coup je ne sais pas ce qui se passe.

Ha .. et tu es toujours a 500lignes de log seulement et non pas 5000. Trop court.

**Comment by Thiematz** [comment]
Oui je suis en version stable
Hier soir avant de faire l'inclusion, j'ai bien remis comme discuté précédemment les deux fichiers que tu m'avais fait, le JSON du module et le fichier dans le dossier commande.
Puis refait une inclusion, mais...
Je refait un test ce soir et je te tiens au courant
Log trop court, ....hum! Dans un fichier en particulier? Car j'ai l'impression que ça papote pas mal

**Comment by tcharp38** [comment]
Log trop court car toujours "limité" à 500lignes. Je recommande 5000 pour le debug: https://kiwihc16.github.io/AbeilleDoc/Debug.html#configuration-jeedom-pour-les-logs

**Comment by Thiematz** [comment]
Salut @tcharp38,

alors j'ai tout repris depuis le début, enfin en ce qui concerne ce module :
- upload fichier json module
- upload fichier command
- redémarrage du demon Abeille
[AbeilleLogs-211202.tar.gz](https://github.com/KiwiHC16/Abeille/files/7642264/AbeilleLogs-211202.tar.gz)
...
Mais le module ne remonte que la température sans la décimale (2154° au lieu de 21.54°)
Je te joins de nouveau les logs

**Comment by tcharp38** [comment]
Quelle est l'adresse de ton périph ?
Je note toujours des logs limités à 500lignes. C est court.
D'autre part, es tu partant pour basculer sur la beta ?

Pour cette histoire de decimale, je pense que tu n'as pas refait d'inclusion ou rechargé le JSON apres tes "upload".
Du coup le dernier fichier de commandes "zb-0402-MeasuredValue" n'est pas pris en compte.

**Comment by Thiematz** [comment]
L'adresse du périphérique

Nom
Sonde SàM
Id Jeedom
243
Dernière comm.
2021-12-02 17:16:07
Nom logique
Abeille1/8531
Adresse (courte/IEEE)
8531 / 00158D000504DD76

Oui, je veux bien participer aux tests sur la beta !

Sauf erreur de ma part, j'ai fais l'inclusion après avoir uploadé les 2 fichiers, json du module et fichier de commande.

**Comment by tcharp38** [comment]
Le pb de décimal est sur "Temperature" n'est ce pas ?
Donc

>             "Temperature": { "use": "zb-0402-MeasuredValue", "params": "ep=01", "isVisible": 1 },


et zb-0402-MeasuredValue fait une division par 100 dans les dernieres beta

>             "calculValueOffset": "#value#\/100",


Donc je pense que ca n'est pas pris en compte.

**Comment by Thiematz** [comment]
Oui, le pb de décimal est sur la température, sur l'humidité il n'y a aucune remontée, du tout.

Tu aurais une idée pour la remontée de l'humidité?

Je ne serai pas dispo ce we, mais si semaine pro vous voulez tester la beta, feu !

**Comment by tcharp38** [comment]
Tu peux basculer sur le beta des maintenant. J'ai besoin de retours pour la stabiliser au plus vite et etre sur que je puisse partir en congés sans bloquer personne.

https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by tcharp38** [comment]
Pour **core/config/devices/898ca74409a740b28d5841661e72268d**

[898ca74409a740b28d5841661e72268d.zip](https://github.com/KiwiHC16/Abeille/files/7650026/898ca74409a740b28d5841661e72268d.zip)

Et l'image associée pour "images" sous le nom **"node_Orvibo-ST30.png"**
![node_Orvibo-ST30](https://user-images.githubusercontent.com/35221038/144612891-18b57e7c-29f9-41bb-97e7-276b1b4b8e59.png)

Puis tu refais une inclusion.
Je m attends à ce que l'info d'humidité remonte

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

j'ai pu intégrer mon module, la température et l'humidité remonte bien.
Sans vouloir être chiant ;-), c'est possible d'afficher la décimale sur l'humidité comme sur l'écran intégré ?

J'ai vu une mise à jour pour le plugin, cela veut dire que la version beta est validée ou est-ce encore un step plus loin?

**Comment by tcharp38** [comment]
Si tu es sur la 211205-STABLE-1, oui j'ai fait d'autres modifs depuis.
Voir la: https://kiwihc16.github.io/AbeilleDoc/Changelog.html

Si t'es partant et tant qu'on bosse ensemble, j'aimerais bien que tu sois sur la beta comme ca j'ai des retours en temps reel des regressions urgentes a fixer en particulier. A toi de voir

Ha et a propos de ton souci de décimal, pour moi c 'est fixé. Voila pourquoi je te propose la beta.

**Comment by Thiematz** [comment]
Je suis passé sur la version Beta. dis moi si tu veux les logs (au passage, comment je change la limite des 500 lignes?)
Pour l'instant pas d'effet de bord (pas assez de recul sans doute)

**Comment by tcharp38** [comment]
As tu refait une inclusion apres la migration ?

Pour les logs voir la: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

j'étais un peu occupé ailleurs ces derniers jours.
Non, je n'ai pas refait d'inclusion. Je le ferai pour voir s'il y a du mieux au niveau décimale.

J'ai cherché à inclure un nouveau module Sivercrest, une "applique murale à LED", il me la reconnait comme un ruban à LED, mais aucune commande ne fonctionne.
Je te joins le fichier discovery si tu veux y jeter un oeil. C'est une applique qui doit fonctionner comme un ruban, 16 Mio de couleurs sélectionnables, blanc chaud à blanc froid.
[discovery(6).zip](https://github.com/KiwiHC16/Abeille/files/7789416/discovery.6.zip)

Bonne soirée ;-)

**Comment by tcharp38** [comment]
Salut @Thiematz 
Pas de soucis. Je reviens juste de congés.
Ouvre (ou réouvre) un nouveau sujet pour ne pas tout mélanger STP avec ton discovery mais aussi le modele/ref constructeur.
Merci

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

pour de potentiel remontée d'info concernant la version Beta, je suppose que je dois ouvrir un nouveau post ? Un nom spécial?

**Comment by tcharp38** [comment]
Salut
Oui, precise la version de la beta et un sujet parlant. On changera si besoin.
Merci

**Comment by tcharp38** [comment]
Salut @Thiematz 
Depuis il y a une autre beta (220121-BETA-2) dispo demain.

Il reste des soucis Orvibo ST30 en attente ?

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

désolé, j'étais en dep les 15 derniers jours et très peu dispo.
Le seul "soucis" que je rencontre encore c'est la décimale pour l'humidité qui ne s'affiche pas.

**Comment by tcharp38** [comment]
Tiens, a decompresser dans core/config/commands
Puis tu fais recharger via la page EQ/avancé de ton ST30
Tiens moi jus
[zb-0405-MeasuredValue.zip](https://github.com/KiwiHC16/Abeille/files/7928634/zb-0405-MeasuredValue.zip)

**Comment by tcharp38** [comment]
Salut @Thiematz 
Un retour ?

**Comment by Thiematz** [comment]
Salut @tcharp38,
désolé pour le délai de réponse, j'étais en congé.
J'ai plusieurs infos pour toi ;-)
Voici ce que je vois dans les logs
4928|[2022-06-22 11:06:33][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/2900/01
4929|[2022-06-22 11:06:33][DEBUG] :   'Temperature' (0402-01-0000) => 2182
4930|[2022-06-22 11:06:34][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/2900/02
4931|[2022-06-22 11:06:34][DEBUG] :   'Humidity' (0405-02-0000) => 5569
Et voici ce que m'affiche jeedom
Temp : 21.8°
Hum : 56%
Je n'ai pas de décimale pour l'humidité.
Bonne journée,

**Comment by tcharp38** [comment]
Une fois sur la beta 220625-BETA-1
reinitialiser la config à partir du modele (page EQ/avancé => Reinitialiser)

**Comment by tcharp38** [comment]
@Thiematz 
Ca devrait etre bon sur la beta.
A confirmer

**Comment by tcharp38** [comment]
@Thiematz 
On fait quoi avec ce sujet ?

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

je n'ai toujours pas la décimale, mais j'ai un autre soucis.
En contrôlant ce matin (je reviens de quelques jours de congés), je m'aperçois que l'humidité n'est plus du tout remontée
Je ne trouve rien dans les log si ce n'est une cde inconnue.

4102|[2022-07-18 10:22:19][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/2900/01
4103|[2022-07-18 10:22:19][DEBUG] :   'Température' (0402-01-0000) => 2295
4104|[2022-07-18 10:22:19][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/2900/02
4105|[2022-07-18 10:22:19][DEBUG] :   Unknown Jeedom command logicId='0405-02-0000'
4106|[2022-07-18 10:22:24][DEBUG] : msgFromParser(): Abeille1, Zigate version 0003-0320

Je viens à l'instant de faire la dernière maj de la beta., je te tiens au jus dans la journée s'il y a du changement/mieux.

**Comment by Thiematz** [comment]
@tcharp38 ,
La température remonte bien, avec décimale, mais rien au niveau humidité.
Je te joins les logs si cela peut t'aider
[AbeilleLogs-220718.tar.gz](https://github.com/KiwiHC16/Abeille/files/9132177/AbeilleLogs-220718.tar.gz)

**Comment by tcharp38** [comment]
Peux tu decompresser ce modele
[898ca74409a740b28d5841661e72268d.zip](https://github.com/KiwiHC16/Abeille/files/9132654/898ca74409a740b28d5841661e72268d.zip)

dans core/config/devices/898ca74409a740b28d5841661e72268d
puis
refaire une inclusion

J'ai trouvé une boulette cote humidité.

**Comment by Thiematz** [comment]
Ok, je fais ça ce soir en rentrant.
Merci

**Comment by Thiematz** [comment]
@tcharp38,

génial, ça marche. J'ai la décimale sur l'humidité!
Merci beaucoup pour ton aide !!
Je clotûre le topic du coup ;-)
Bonne journée
