### ISSUE TITLE
Ajout capteur de mouvement LIDL SilverCrest HG06335

### ISSUE THREAD

**Issue by boxsters1423** [KiwiHC16/Abeille#2195]

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Je te laisse generer un discovery.json pour ce periph.
Merci

**Comment by boxsters1423** [comment]
Salut @tcharp38 
Le fichier JSON est bien vide il me semble.
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/7576114/discovery.json.zip)
Ça veut dire que l'équipement ne respecte pas les normes ?
À+

**Comment by tcharp38** [comment]
Ha non c 'est surement parce qu'il est sur batterie n'est ce pas ?
Si c 'est bien le cas alors comme tous les equipements sur batterie, quasi tous, quand ils dorment ils n ecoutent meme pas le reseau pour economiser. Bref tu dois le reveiller 1 à plusieurs fois (jusqu a avoir tous les boutons au vert) pendant la decouverte.

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Je suppose que tu n'es plus interessé par cet antique sujet ?

**Comment by boxsters1423** [comment]
Salut 👋 il est toujours au fond d'un tiroir mais je suis passé au plugin zigbee trop de soucis avec mes clés
