### ISSUE TITLE
Module interrupteur 1/2/3 voies sans neutre

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2196]
J'ai trouvé cet interrupteur sur ali....Je l'ai installé, très simple, puis inclus dans Abeille, reconnu de suite et fonctionnel on/off sans neutre 10.52€. Je pense qu'il a d'autres possibilités que le on-off, à voir.
Voici le discovery.js
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7574786/discovery.json.txt)
et l'image sans fond
![Micromodule Zigbee On-Off sans neutre](https://user-images.githubusercontent.com/52486183/142732600-25d675ed-5447-420b-baa9-6eb662c34753.png)
Interressant ?
Bon dimanche

**Comment by tcharp38** [comment]
Il est reconnu mais identifié en tant que TS0011, "Yagusmart Tuya ZigBee Smart Switch 1 Bang"
c 'est bien ca ?

**Comment by Kenderv** [comment]
Oui tout à fait mais au vu de ce qui est indiqué sur le site 
https://fr.aliexpress.com/item/1005003026962537.html?spm=a2g0o.productlist.0.0.b9257b427at8ef&algo_pvid=fd4b3ae5-f1d1-4a7b-af8f-4f0e9ab3aea6&algo_exp_id=fd4b3ae5-f1d1-4a7b-af8f-4f0e9ab3aea6-7&pdp_ext_f=%7B%22sku_id%22%3A%2212000023313588085%22%7D 
et au travers de l'application Tuya il peut faire beaucoup de choses. Le tout est de savoir si c'est via le cloud probable, ou si on peut le programmer via des commandes supplémentaires. Il existe sous plusieurs marques sur le même site

**Comment by tcharp38** [comment]
Le voice control par ex n'est pas du role d'Abeille.
A quoi d'autre penses tu comme "manque" ?

**Comment by pixeldesbois** [comment]
Hello,
J'ai acheté les mêmes devices. L'inclusion et le on-off fonctionne très bien. Il manque la possibilité des les inclure dans un groupe.
Je cherche à creer un va et vient avec 2 module 1 voie.
Est-ce possible ?

Merci par avance et bon dimanche !

**Comment by Kenderv** [comment]
@tcharp38
Ben finalement je ne vois pas beaucoup d'autre chose, 
![image](https://user-images.githubusercontent.com/52486183/142770205-6fdca42c-0261-429e-b072-ae2acdf60fa9.png)
![image](https://user-images.githubusercontent.com/52486183/142770220-847d2711-b9e1-4c49-9b10-eca29cdf7507.png)
![image](https://user-images.githubusercontent.com/52486183/142770239-6f4b59c4-5802-4c7a-81ad-ee8615aa90f4.png)
ces trois fonctions pouvant être gérées par un scénario. La puissance et les consos instantanée et cumulée ne semblent pas être inclues dans les fonctions natives ne pourront pas être récupérées et pour le Voice control je suis tout à fait d'accord avec toi. Si tu as la possibilité de mettre la bonne image, c'est bien, mais ça n'a pas grande importance. Le module est un peu épais et sera plus facile à intégrer dans une boite avec chaussette. Voilà, Pour 10€ ça fait le boulot, à voir dans le temps.
Bonne soirée.

**Comment by Kenderv** [comment]
@pixeldesbois 
La documentation ne parle pas de la notion de groupe mais le schéma d'installation semble bien, sauf erreur de ma part, indiquer la possibilité de fonctionner en va-et-vient :
![image](https://user-images.githubusercontent.com/52486183/142770611-0381a1a6-d4f9-4b6b-8cf9-1d8868ed2bab.png)
Au fait, comment traduire "gang" ? Merci
 Bonne soirée

**Comment by pixeldesbois** [comment]
Tu peux traduire comme "groupe". En gros tu peux commander un seul groupe d'ampoule.

Pour mon va et vient, c'est parce que je n'ai pas la possibilité de faire comme sur le schéma. Il faudrait que je retire le cable et là c'est compliqué sans casse du mur...

Donc je suis parti sur ce schéma en utilisant les2 fils navettes déjà en place :
![](https://community.jeedom.com/uploads/default/original/2X/4/49dccd434898b8bcd6827f6b2cd5155a1f4fc908.jpeg)

Je gère le va et vient avec un scenario. En l'état ca fonctionne mais il y a de la latence des fois d'où mon besoin de passer par un groupe.

**Comment by tcharp38** [comment]
Je confirme que ce périph supporte l adressage par groupe d apres le discovery de Kenderv.
Je vais vour proposer une update du JSON.
Mais une nouvelle stable pour demain avant tout.
Back soon

**Comment by pixeldesbois** [comment]
Au top ! Merci !

**Comment by tcharp38** [comment]
@Kenderv 
Ton module est vendu sous la marque Tuya ou Avatto ?
C'est bien cette ref "Z-N-WSM01" ?

**Comment by tcharp38** [comment]
[TS0011__TZ3000_ji4araar.zip](https://github.com/KiwiHC16/Abeille/files/7580324/TS0011__TZ3000_ji4araar.zip)

A decompresser dans "core/config/devices"
puis
redemarrer Abeille
refaire inclusion

Attention: Ce JSON correspond au module de kenderv. Le "TS0011" de base n'est pas touché. Je n'en connais pas son origine.

**Comment by Kenderv** [comment]
Mon modèle est AVATTO N-ZLWSM01

**Comment by tcharp38** [comment]
Ok, donc le JSON fourni est en ligne. A tester via une réinclusion.

**Comment by Kenderv** [comment]
OK, pour moi c'est tout bon après avoir rajouté l'image dans le répertoire image. Je n'utilise pas la notion de groupe donc pas pu tester. 
[node_Tuya-1chanSwitchModule.png.txt](https://github.com/KiwiHC16/Abeille/files/7582069/node_Tuya-1chanSwitchModule.png.txt)
Voici le discovery.json
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7582115/discovery.json.txt)
Merci pour tout

**Comment by tcharp38** [comment]
L'image est deja dans la 211122-BETA-1 pour ceux qui veulent tester la future stable

**Comment by pixeldesbois** [comment]
Chez moi, l'ajout de groupe fonctionne mais je n'arrive pas à faire fonctionner une télécommande associée. 
Je dois mal m'y prendre...

Le module que j'utilise est un GIRIER [https://fr.aliexpress.com/item/1005003438720832.html?spm=a2g0s.9042311.0.0.8a1c6c37bEiHjx](url)
Ca reste du Tuya dedans.

Voici le discovery.json
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7584481/discovery.zip)

Bonne soirée

**Comment by tcharp38** [comment]
@pixeldesbois 
Le sujet me semble maintenant different donc en ouvrir un autre en précisant quelle telecommande et commen tu procedes.
Merci

**Comment by tcharp38** [comment]
@Kenderv On peut clore ce sujet ?

**Comment by Kenderv** [comment]
Salut @tcharp38 , Pour moi tout fonctionne correctement. Un petite latence à l'allumage ~ 1 seconde, mais c'est sans doute lié au  fait que l'allumage est fait pas un scénario. Tu peux clore. Merci encore de ton travail. Bonne journée

**Comment by tcharp38** [comment]
Parfait. Merci
Comme dhab a reouvrir si soucis en lien avec le sujet.
