### ISSUE TITLE
Ajout ampoule LIDL TS0502A, _TZ3000_el5kt5im

### ISSUE THREAD

**Issue by odejerph** [KiwiHC16/Abeille#2198]
Bonjour,
J'ai acheté une ampoule spot led chez Lidl et elle n'est pas reconnue par Abeille.
Je vous joins le discovery.json.
Merci beaucoup pour votre support !

[discovery-2.json.zip](https://github.com/KiwiHC16/Abeille/files/7584324/discovery-2.json.zip)

**Comment by tcharp38** [comment]
Salut
Quel est le modele/la ref vendeur ? HGxxx
C est du LivarnoLux ou Silvercrest ?

**Comment by odejerph** [comment]
Bonjour @tcharp38, il s'agit du modèle HG07878A de LIVARNO HOME.

**Comment by tcharp38** [comment]
A tester
[TS0502A__TZ3000_el5kt5im.zip](https://github.com/KiwiHC16/Abeille/files/7588619/TS0502A__TZ3000_el5kt5im.zip)

Decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion

**Comment by odejerph** [comment]
Merci beaucoup
Je viens de tester : cela fonctionne bien pour les commandes On/Off et 2500/5000K ainsi que les infos Status et temperatureLight. Par contre la couleur et l'intensité lumineuse ne fonctionne pas.

**Comment by tcharp38** [comment]
Je crois que ton ampoule est dans un autre mode (dit "mired") donc pas compatible.
A tester avec ca
[TS0502A__TZ3000_el5kt5im.zip](https://github.com/KiwiHC16/Abeille/files/7594789/TS0502A__TZ3000_el5kt5im.zip)

**Comment by odejerph** [comment]
Merci bcp, effectivement cela ne fonctionne pas mieux.
Est-ce que la compatibilité avec le mode "mired" est quelque chose que vous prévoyez à moyen terme ?
Encore merci pour ton aide !

**Comment by tcharp38** [comment]
Peux tu verifier que le color mode à changé ? 
Tu cliques sur ton equipement
page avancé

![image](https://user-images.githubusercontent.com/35221038/143325754-109ffd31-f01a-462b-9889-4790ac99f11f.png)

puis tu me donnes le fichier AbeilleParser.log. L'info doit y etre

**Comment by odejerph** [comment]
Voici le log, je l'ai purgé avant la manip
[AbeilleParser-2.log](https://github.com/KiwiHC16/Abeille/files/7605030/AbeilleParser-2.log)

**Comment by tcharp38** [comment]
Zut la valeur n'apparait pas donc je ne peux pas confirmer que cette valeur a bien ete modifée.

> [2021-11-25 20:53:47] Abeille1, Type=8100/Read individual attribute response, SQN=89, Addr=B9F5, EP=01, ClustId=0300, AttrId=0008, AttrStatus=00, AttrDataType=30, AttrSize=0001
> [2021-11-25 20:53:47]   msgToClient(): Pending messages in queue => doing nothing
>

**Comment by odejerph** [comment]
Y a t-il une manip à réaliser ?

**Comment by tcharp38** [comment]
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/7605437/AbeilleParser.class.php.zip)
Oui tu peux refaire la manip en utilisant ce fichier AbeilleParser.class.php (pour core/class) et apres avoir redemarré Abeille
On devrait voir la valeur de la data maintenant

**Comment by odejerph** [comment]
Voici les nouveaux logs, j'ai l'impression que la valeur 2 est renvoyée

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7610463/AbeilleParser.log)

**Comment by tcharp38** [comment]
Effectivement

> [2021-11-26 20:33:20] Abeille1, Type=8100/Read individual attribute response, SQN=00, Addr=B9F5, EP=01, ClustId=0300, AttrId=0008, AttrStatus=00, AttrDataType=30, AttrSize=0001
> [2021-11-26 20:33:20]   Unknown-0300-0008, hexValue=02 => 2

Donc mode "mired"

![image](https://user-images.githubusercontent.com/35221038/143655514-75bc3d51-6a88-4dd1-b8af-51c3349134c4.png)

Il faut avoir 1 pour un controle X/Y

Peux tu tenter de modifier cette valeur via la page eq/avancé
![image](https://user-images.githubusercontent.com/35221038/143656569-b3e8f599-9267-440e-aa55-5da95c966a79.png)

puis tu relis pour etre sur de relire 01 et non plus 02.

Si c est bien le cas alors certaines commandes de couleur doivent alors fonctionner.

**Comment by odejerph** [comment]
La valeur reste à 2.
Après difficile de savoir si l'écriture se passe bien : elle ne génère aucun log...

**Comment by tcharp38** [comment]
Peux tu me filer le log AbeilelCmd+Parser suite au write ?

**Comment by odejerph** [comment]
Les voici :
[AbeilleParser-3.log](https://github.com/KiwiHC16/Abeille/files/7612118/AbeilleParser-3.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7612119/AbeilleCmd.log)

**Comment by tcharp38** [comment]
Le write est refusé

> [2021-11-27 18:08:52] Abeille1, Type=8110/Write attribute response, SrcAddr=B9F5, EP=01, ClustID=0300, AttrId=0008, Status=86

Status=86 => unsupported.

Donc il doit y avoir une astuce pour changer le color mode.

Ha, la spec dit "The value of the ColorMode attribute cannot be written directly - it is set upon reception of any command in
section 5.2.2.3 to the appropriate mode for that command.".

**Comment by tcharp38** [comment]
Peux tu cliquer sur "Blanc" puis me filer les 2 logs Cmd & Parser ?

**Comment by odejerph** [comment]
Les voici 
[AbeilleParser-4.log](https://github.com/KiwiHC16/Abeille/files/7613750/AbeilleParser-4.log)
[AbeilleCmd-2.log](https://github.com/KiwiHC16/Abeille/files/7613751/AbeilleCmd-2.log)

je suis un peu largué ! :-)
Pour mon info a quelle spec fais-tu référence ?

**Comment by tcharp38** [comment]
La spec en question est une du standard Zigbee: ZCL, Zigbee Cluster Lib (https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf)

**Comment by tcharp38** [comment]
> [2021-11-28 15:54:00] Message from queueKeyAbeilleToCmd: CmdAbeille1/B9F5/setColour -> EP=01&X=6000&Y=6000
> 
> [2021-11-28 15:54:00] Abeille1, Type=8000/Status, Status=00/Success, SQN=BF, PacketType=00B7
> [2021-11-28 15:54:01] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0300, SrcEP=01, DestEP=01, SrcAddrMode=02, SrcAddr=B9F5, DestAddrMode=02, DestAddr=0000
> [2021-11-28 15:54:01]   FCF=08/General/Serv->Cli, SQN=BF, cmd=0B/Default Response
> [2021-11-28 15:54:01]   Cmd=07, Status=C3 => Unsupported cluster

Etrange, ca semble pas supporté.

Peux tu refaire le meme test avec la commande "Set Temperature" apres avoir fait un "recharger JSON"
[TS0502A__TZ3000_el5kt5im.zip](https://github.com/KiwiHC16/Abeille/files/7619543/TS0502A__TZ3000_el5kt5im.zip)

D'ailleurs si tu veux bien basculer sur la beta tu sera sur la derniere mouture et ton retour me sera precieux.

**Comment by odejerph** [comment]
Je suis passé en version beta (sans recharger JSON), voici les fichiers :

[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7621055/AbeilleCmd.log)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/7621057/AbeilleParser.1.log)

Une fois le JSON rechargé, je n'ai plus de commande Set Temperature
![image](https://user-images.githubusercontent.com/94869808/143941500-c395df8b-8e25-433c-ae33-0cf0cdb356ee.png)

**Comment by tcharp38** [comment]
Peux tu me filer le log Abeille ?

**Comment by odejerph** [comment]
Je viens de voir la fonction "Recharger" JSON dans le plugin. 
Lorsque je l'ai fait, j'ai eu le message d'erreur suivant : "Le fichier de commande 'zbCmd-0300-MoveToColorTemp.json' n'existe pas"

**Comment by odejerph** [comment]
Voici le log 
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7621283/Abeille.log)

**Comment by tcharp38** [comment]
[zbCmd-0300-MoveToColorTemp.zip](https://github.com/KiwiHC16/Abeille/files/7621284/zbCmd-0300-MoveToColorTemp.zip)
Pour core/config/commands

C 'est bizarre pourtant il est bien dans la beta

**Comment by odejerph** [comment]
Effectivement, je ne l'avais pas...
Maintenant en jouant sur les températures j'obtiens quelques couleurs entre blanc et orange foncé

[AbeilleParser (2).log](https://github.com/KiwiHC16/Abeille/files/7621333/AbeilleParser.2.log)


[AbeilleCmd (1).log](https://github.com/KiwiHC16/Abeille/files/7621332/AbeilleCmd.1.log)

**Comment by tcharp38** [comment]
Ha pigé. Si tu es sur la beta via le market ca n'est pas la derniere qui ne tombera que demain.
Voila pourquoi elle manque.

**Comment by odejerph** [comment]
Exact !

**Comment by tcharp38** [comment]
@odejerph 
On en est ou ?

**Comment by odejerph** [comment]
> 

As-tu vu mon message ci-dessus  avec les logs (fin novembre) ?

**Comment by tcharp38** [comment]
Oui mais j essaie de resumer
- on/off +status ok
- setLevel +currentlevel ok
- blanc/bleu/rouge/vert + temperatureLight ok du coup ?

**Comment by odejerph** [comment]
Ok, je regarde ça en fin de semaine... Là pas beaucoup de temps !

**Comment by odejerph** [comment]
Voici le statut :

- On/Off + Statut : OK
- SetLevel + Current Level OK
- Set 2700K + Set5000K OK
- blanc/bleu/rouge/vert KO - il ne se passe rien

![Capture d’écran 2021-12-17 à 21 24 11](https://user-images.githubusercontent.com/94869808/146603839-256bb982-3b1d-434b-a7d4-0ae4efa3868c.png)

**Comment by odejerph** [comment]
Si besoin, je te joins les logs
[AbeilleCmd-3.log](https://github.com/KiwiHC16/Abeille/files/7737591/AbeilleCmd-3.log)
[AbeilleParser-5.log](https://github.com/KiwiHC16/Abeille/files/7737592/AbeilleParser-5.log)

**Comment by tcharp38** [comment]
Peux tu faire un "set white" par ex et me filer les logs Cmd + Parser ?

Correction a faire sur "Set 2700" & 5000. Ca ne devrait pas etre un slider.

**Comment by odejerph** [comment]
Hello @tcharp38, je suis absent quelques jours, je t'enverrai cela ASAP

**Comment by tcharp38** [comment]
Aucun souci. Je serai moi aussi loin de mon PC des demain et pendant 1 semaine. Bonnes fetes

**Comment by odejerph** [comment]
Meilleurs voeux à tous ! 

Voici donc les logs suite à un "set white"

[AbeilleCmd-4.log](https://github.com/KiwiHC16/Abeille/files/7803925/AbeilleCmd-4.log)
[AbeilleParser-6.log](https://github.com/KiwiHC16/Abeille/files/7803927/AbeilleParser-6.log)

**Comment by tcharp38** [comment]
Salut @odejerph 
Tres bonne année.

Dis, une question en passant. Je ne trouve pas d'infos sur cette ampoule. Sur sa boite c est ecrit quoi ? Blanc chaud au blanc froid ? Ou plutot couleur RGB ? Je me demande tout betement si c est une ampoule couleur.

**Comment by odejerph** [comment]
Salut @tcharp38, je crois que ta question donne la réponse au problème.
J'ai en effet retrouvé la boite et il est indiqué "Blanc chaud à blanc froid"

![IMG_2773](https://user-images.githubusercontent.com/94869808/148284745-3b175b74-4115-482e-b5af-67dbe9b7b9a5.jpg)

Pourrais-tu du coup régénérer un JSON qui permette de modifier uniquement la température et l'intensité ?

**Comment by tcharp38** [comment]
Voila:
[TS0502A__TZ3000_el5kt5im.zip](https://github.com/KiwiHC16/Abeille/files/7821465/TS0502A__TZ3000_el5kt5im.zip)

**Comment by odejerph** [comment]
C'est parfait, merci bcp.
Et désolé de t'avoir fait perdre du temps avec une ampoule blanche ! ;-)

**Comment by tcharp38** [comment]
Pas de soucis. C'est la que tu vois que le standard zigbee laisse la porte ouverte à n'importe quel device un peu pourri.
L'ampoule dit qu'elle supporte la couleur donc FW pas en ligne.

J'espere qu'ils feront evoluer ce standard pour le rendre + draconien.

Du coup je clos ?
