### ISSUE TITLE
Ajout controleur led strip Tuya TS0501B, _TZ3210_9q49basr

### ISSUE THREAD

**Issue by BradSena** [KiwiHC16/Abeille#2199]
Bonjour,
Je viens d'inclure ce contrôleur pensant que si les RGB marchent celui-ci aussi devrai fonctionner mais non! Il n'est pas reconnu par abeille.
J'ai lu la doc mais je ne trouve pas le readme avec la procédure pour créer le discovery.json, pouvez-vous m'aider?

**Comment by tcharp38** [comment]
Salut @BradSena 
Regarde ca: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by BradSena** [comment]
En fait je viens de comprendre qu'il suffit de cliquer sur le bouton "télécharger" pour crées automatiquement le fichier json. Ce n'est pas précisé dans la doc et je pensait qu'il fallait faire soi-même le fichier...
Toujours est-il que ce module ne remonte aucune info (voir fichier joint)
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/7590138/discovery.json.zip)

**Comment by tcharp38** [comment]
Bah non il ne "suffit" pas :)
Mais il manque surement des choses dans la doc c'est sur.

Bref au vu de ton fichier tu dois avoir encore des boutons en "orange" ce qui veut dire que l'info n'est pas la.
Il faut tacher d'avoir tout au vert avant de telecharger et fournir le discovery. Sinon il est incomplet.
Tu peux retenter ?

Je viens de refaire une petite passe sur la doc de l'assistant.

**Comment by BradSena** [comment]
Je confirme, tout est orange. Mais j'ai beau cliquer et recliquer ça ne se rempli pas.
![Capture d’écran 2021-11-23 à 21 19 30](https://user-images.githubusercontent.com/93638410/143097791-1af7f841-23a9-4618-97ad-d5c3382ff67f.png)

**Comment by tcharp38** [comment]
Peux tu, quand tu te retrouves dans ce cas, cliquer sur le gauche
![image](https://user-images.githubusercontent.com/35221038/143220497-2a3f63ce-2a28-4637-867b-9904412d20ae.png)
puis le droit
et me filer le package de logs (page support/telecharger tout) ?
Merci

**Comment by BradSena** [comment]
Voilà! Merci de ton aide en tous cas!

[AbeilleLogs-211124.tar.gz](https://github.com/KiwiHC16/Abeille/files/7595231/AbeilleLogs-211124.tar.gz)

**Comment by tcharp38** [comment]
D'apres https://zigbee.blakadder.com/Tuya_TS0501B.html
ce device peut etre identifié sous 3 signatures

- TS0501B__TZ3210_9q49basr
- TS0501B__TZ3210_4whigl8i
- TS0501B__TZ3000_4whigl8i

**Comment by tcharp38** [comment]
> Voilà! Merci de ton aide en tous cas!
> 
> [AbeilleLogs-211124.tar.gz](https://github.com/KiwiHC16/Abeille/files/7595231/AbeilleLogs-211124.tar.gz)

Rien d'interessant la dedans malheureusement donc je ne sais pas ce qui bloque coté assistant.
Tu as peut etre un petit triangle en haut a droit de ton navigateur indiquant une erreur Javacript ?

Quoi qu il en soit à l'aveuglette, voila de quoi tester.
A decompresser dans core/config/devices
puis redemarrer Abeille
refaire inclusion
[TS0501B__TZ3210_9q49basr.zip](https://github.com/KiwiHC16/Abeille/files/7596213/TS0501B__TZ3210_9q49basr.zip)

et l'image pour "images"
[node_Tuya-TS0501B-LedController.zip](https://github.com/KiwiHC16/Abeille/files/7596217/node_Tuya-TS0501B-LedController.zip)

**Comment by BradSena** [comment]
Nickel ça marche!
Il y a toutes les commande pour un ruban RGBW mais une fois supprimé celles superflues, c'est parfait
![Capture d’écran 2021-11-24 à 18 50 40](https://user-images.githubusercontent.com/93638410/143289920-5937a636-165f-4e9e-ab71-b7fa379022b0.png)
!
Par contre on peut régler le niveau mais on a pas de retour d'info précis, juste On/Off.

**Comment by tcharp38** [comment]
Tu veux dire qu'il n'y a besoin que de ca ?
Pas de gestion de couleurs ?

**Comment by BradSena** [comment]
Oui tout à fait! Ce module est fait pour les rubans LED simples, je pensais que tu l'avais vu:
![Capture d’écran 2021-11-25 à 06 53 20](https://user-images.githubusercontent.com/93638410/143387366-192141bc-4751-4942-88b0-79a48b47dd92.png)

**Comment by tcharp38** [comment]
Etrange. Il supporte le cluster 0300 (Color control) d'apres ta page discovery donc je ne pige pas.

**Comment by BradSena** [comment]
Peut être qu'en interne c'est la même électronique que les boitier RGB mais il n'y a qu'une sortie connectée?

**Comment by tcharp38** [comment]
Peut etre oui. 
Donc à noter que les commandes "color" peuvent n'avoir aucun effet meme si le cluster est supposé être supporté.
Je laisse le modele tel quel pour l'instant mais je clos.
Sujet à reouvrir si soucis.
