### ISSUE TITLE
Ajout variateur de lumiere  iolloi, Dimmer-Switch-ZB3.0, HZC

### ISSUE THREAD

**Issue by pinton40** [KiwiHC16/Abeille#2200]
Bonjour, serait il possible de rendre compatible avec abeille ce variateur de lumière. 
Merci d avance
[discovery (8).zip](https://github.com/KiwiHC16/Abeille/files/7597696/discovery.8.zip)
.

**Comment by tcharp38** [comment]
Salut

Quelle est la marque et le modele ?

Version prelim a tester:
[Dimmer-Switch-ZB3.0_HZC.zip](https://github.com/KiwiHC16/Abeille/files/7599148/Dimmer-Switch-ZB3.0_HZC.zip)

Decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion
et faire le point

**Comment by pinton40** [comment]
bonsoir merci pour ta réactivité, tu trouveras dans le lien ci-dessous le modèle de l'appareil :
https://www.iolloi.shop/products/iolloi-zigbee-dimmer-b4l

**Comment by pinton40** [comment]
Merci ça fonctionne parfaitement.
 Bonne soirée

**Comment by tcharp38** [comment]
Super.
Je te laisse me trouver un PNG sans fond pour mettre en icone et on peut clore ce sujet.

**Comment by pinton40** [comment]
![ID-EU20FEB4L-1_1_1024x1024@2x_transparent](https://user-images.githubusercontent.com/63167945/143618508-3fdd7770-ddf4-43fc-ad62-4deb4eb03211.png)

**Comment by pinton40** [comment]
Bonsoir voici le PNG.

**Comment by tcharp38** [comment]
Merci.
C 'est enregistré pour la prochaine stable.
Je clos. 
A reouvrir si le moindre souci.

**Comment by pinton40** [comment]
Bonsoir,  serait il possible d'avoir le retour de l'intensité lumineuse lorsqu'il est piloté par une télécommande ou par le bouton poussoir ? 
Merci d'avance

**Comment by tcharp38** [comment]
Tu veux dire que "CurrentLevel" n'est pas mis à jour quand piloté autrement que par Abeille ?
C'est bien ca ?

**Comment by pinton40** [comment]
bonjour oui exactement , désolé si je me suis mal exprimé.

**Comment by tcharp38** [comment]
[Dimmer-Switch-ZB3.0_HZC.json.zip](https://github.com/KiwiHC16/Abeille/files/7624488/Dimmer-Switch-ZB3.0_HZC.json.zip)
A tester avec ce modele du coup.

**Comment by pinton40** [comment]
bonsoir même problème pas d info numérique "level".

**Comment by tcharp38** [comment]
Que veux tu dire ?
"CurrentLevel" n'est pas visible ou aucune info n est remontée ?

Si 2nd cas, as tu fait une reinclusion ?

**Comment by pinton40** [comment]
L'info binaire on off est remonté ,mais aucune info en analogique. Par contre j'ai un défaut qui s'affiche "Le fichier de commande 'zb-0008-CurrentLevel.json' n'existe pas".

**Comment by tcharp38** [comment]
[zb-0008-CurrentLevel.zip](https://github.com/KiwiHC16/Abeille/files/7653902/zb-0008-CurrentLevel.zip)
Voila le fichier manquant pour core/config/commands
puis refaire inclusion.

Serais tu partant pour basculer sur la beta ? Besoin de retours pour la transformer en stable.

**Comment by pinton40** [comment]
salut l'information "CurrentLevel" fonctionne  mais le curseur "Set-Level" ne se met pas jour . Comment faut  il faire pour basculer sur la version beta.

**Comment by tcharp38** [comment]
Regarde ce chapitre et le suivant: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-stable

**Comment by tcharp38** [comment]
Salut @pinton40 
Tres bonne année.

As tu pu basculer sur la beta ?

**Comment by pinton40** [comment]
salut @tcharp38  je te souhaite aussi une très bonne année .
Non je n'ai pas eu le temps de m'en occuper par contre j'ai un message d'erreur récurrent .
" Le fichier de commande 'battery-Volt2Percent-3.json' n'existe pas "
aurais tu la solution Merci d'avance ?

**Comment by tcharp38** [comment]
Ce pb est résolu depuis mais si tu bascules pas sur la beta, tu peux prendre ce fichier pour "core/config/commands"

[battery-Volt2Percent-3.zip](https://github.com/KiwiHC16/Abeille/files/7801142/battery-Volt2Percent-3.zip)

**Comment by tcharp38** [comment]
@pinton40 
Salut. On en est ou sur ce sujet ?

**Comment by pinton40** [comment]
Salut tu peux clôturer le sujet .

merci

**Comment by tcharp38** [comment]
Super.
Merci
