### ISSUE TITLE
Ajout ampoule LIDL LivarnoHome HG07834C

### ISSUE THREAD

**Issue by nonomega** [KiwiHC16/Abeille#2203]
Bonjour,
J'ai acheté une ampoule led E27 chez Lidl (marque LivarnoHome modèle HG07834C).
Elle n'est pas reconnue par Abeille, j'obtiens "Nouvel équipement détecté mais non supporté." 
Je vous joins le discovery.json
Merci beaucoup pour votre support.
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7613768/discovery.zip)

**Comment by tcharp38** [comment]
Salut.

Pour test:

A decompresser dans core/config/commands
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7614259/commands.zip)

A decompresser dans core/config/devices
[TS0505B__TZ3000_qd7hej8u.zip](https://github.com/KiwiHC16/Abeille/files/7614260/TS0505B__TZ3000_qd7hej8u.zip)

Puis
redemarrer Abeille
refaire inclusion 
tester

**Comment by nonomega** [comment]
Hello
J'ai fait le test : J'ai reinclus l'ampoule et elle est correctement reconnue.
On / Off / Set Level fonctionnent !

Je vois dans le json les commandes "Set Temperature", "Set 2200K", "Set 6500K" néanmoins ces commandes n'apparaissent pas dans l'objet sous Abeille.

Je poursuis mes tests et je vous dirais.

Merci encore.

**Comment by tcharp38** [comment]
Si elles n'apparaissent pas c'est qu'il y a une erreur qq part. As tu bien décompressé commands.zip dans core/config/commands avant l'inclusion ?
Si oui peux tu
- cliquer sur ton equipement
- page avancé
- recharger JSON
- et me filer le log Abeille

**Comment by nonomega** [comment]
Hello,
ça fonctionne : je n'avais pas correctement dézippé les fichiers de commands.zip. Merci
Maintenant ça fonctionne : ON/ OFF / LEVEL/ TEMP.

Par contre, j'aurais dû préciser que cette ampoule est RGBW.
Moyen d'ajouter la gestion des couleurs s'il vous plait ?
Merci par avance

**Comment by tcharp38** [comment]
[TS0505B__TZ3000_qd7hej8u.zip](https://github.com/KiwiHC16/Abeille/files/7621089/TS0505B__TZ3000_qd7hej8u.zip)
Pour core/config/devices/TS0505B__TZ3000_qd7hej8u

[zbCmd-0300-MoveToColor.zip](https://github.com/KiwiHC16/Abeille/files/7621096/zbCmd-0300-MoveToColor.zip)
Pour core/config/commands

Je mets tout ca dans une beta dispo demain.
Si tu peux basculer dessus ca aidera et ton retour permettra d'en faire un stable tres vite.
Merci

**Comment by nonomega** [comment]
Hello,
Merci beaucoup. Je fais le nécessaire pour basculer en beta et je vous tiens au jus.

**Comment by nonomega** [comment]
Salut

Extra : avec vos derniers json, je peux contrôler les couleurs !
Merci beaucoup pour le travail.

Je suis passé en beta.
Je me tiens disponible pour tester.
Merci

**Comment by tcharp38** [comment]
Cool. La derniere beta (celle du jour), ne sera dispo que demain.
Ne pas hesiter à ouvrir un sujet précis pour toute regression.

Sinon sur ce sujet, tout est couvert ? On peut clore ?

**Comment by nonomega** [comment]
Oui tout fonctionne comme souhaité.
Je clos. 
Merci encore pour le temps/ travail.
