### ISSUE TITLE
211121-STABLE-1: Pb Zigate WIFI

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2204]

**Comment by tcharp38** [comment]
@glelan
Assure toi avant tout d'etre en mode debug 5000 lignes: https://tcharp38.github.io/AbeilleDoc/Debug.html#support

Et j'ai besoin d'un package de logs (page support/telecharger tout) autour d'un moment de disfonctionnement.
Merci

**Comment by Krankhore** [comment]
Bonjour, 
j'ai le même problème et j'ai redémarrer une VM de test hier avec une zigate wifi vide . je l'ai laissé tourner et visiblement ce matin vers 6h, ile y a eu un souci et depuis une boucle ( 100% sur un coeur par serialread )
Abeille indique bien la perte de la zigate mais relance à répétition socat.

La zigate à regarder est la 2, la première n'est pas active ( et la vm até monté à partir q'une copie de la production)


Chose bizarre , sur la page santé , la ruche est OK  ( bien que juste avant de prendre la copie d'écran , elle a été en time out)
je te joins toutes les logs et les 2 copies d'écran)


![Abeille santé](https://user-images.githubusercontent.com/56954282/144032886-b5639818-1fe1-4a4f-bc85-170c78c96790.JPG)
![Abeille Cpu](https://user-images.githubusercontent.com/56954282/144032896-9f8edcc6-85c4-4c2c-ac0f-d52e2370f81e.JPG)


[AbeilleLogs-211130.tar.gz](https://github.com/KiwiHC16/Abeille/files/7625061/AbeilleLogs-211130.tar.gz)

J'ai rencontré ce problème 3 ou 4 fois en production depuis début septembre. ( la ruche et tous les équpements passent en time-out et cpu à 100% sur un coeur)
Une relance du démon règle le problème, et c'est à nouveau le cas sur ma VM de test.

Je te joins la log de Abeillesocat2 et Abeillereader2 juste après le redémarrage du démon à 11h35m24s


[AbeilleSocat2.log](https://github.com/KiwiHC16/Abeille/files/7625063/AbeilleSocat2.log)
[AbeilleSerialRead2.log](https://github.com/KiwiHC16/Abeille/files/7625064/AbeilleSerialRead2.log)

**Comment by tcharp38** [comment]
Salut @Krankhore 
Si je prends juste tes 2 derniers logs, ca semble fonctionner pour toi.

Socat etabli la connexion avec la ZigateWifi

> 2021/11/30 11:35:25 socat[432799] N PTY is /dev/pts/2
> 2021/11/30 11:35:25 socat[432799] N opening connection to AF=2 192.168.1.12:9999
> 2021/11/30 11:35:25 socat[432799] N successfully connected from local address AF=2 192.168.0.32:37716
> 2021/11/30 11:35:25 socat[432799] N starting data transfer loop with FDs [5,5] and [7,7]

et serial read continue le chemin vers le parser et recoit bien des infos

> [2021-11-30 11:36:02] /dev/zigate2 port opened
> [2021-11-30 11:36:02] Got "8024000D4104000000158D0000CE20950F00"
> [2021-11-30 11:36:02] Got "80000007A300000024000000"
> [2021-11-30 11:36:02] Got "8024000D4104000000158D0000CE20950F00"
> [2021-11-30 11:36:02] Got "80000007A300000024000000"

Donc en redemarrant ca fonctionne. Ca semble en ligne avec ton observation.
J'imagine alors que ca ne dure qu'un temps. C est bien ca ?

**Comment by tcharp38** [comment]
@Krankhore 
Puisque c 'est une VM de test, peux tu basculer sur la beta ? Ca sera + efficace et tes retours seront precieux pour en faire une stable. Merci

J'ai peut etre une piste.

**Comment by Krankhore** [comment]
Ok, j'installe la version beta sur la Vm de test.

Par contre, je ne sais pas quand le cas se reproduira. Ça arrive après des perturbations du wifi. Abeille relance en boucle mais ça ne fonctionne pas alors que la simple relance du démon suffit à rétablir la situation.

Je n'ai pas encore réussi à déterminer quel genre de cas provoque la boucle . J'ai déjà forcé la reconnexion au wifi , bloquer la communication wifi par iptable puis rétabli. Dans chacun de ces tests, la situation se rétablissait toute seule.


En prod, comme le symptôme est une forte augmentation de la cpu, j'avais essayé de contourner le problème avec un scénario que j’exécute toutes les 15 minutes .
![Scénario](https://user-images.githubusercontent.com/56954282/144050695-6b3c2b00-77e7-45f2-8276-9637e78f4356.JPG)

Le scénario a déclenché une fois la relance mais cela n'avais pas suffit. La cpu avait fortement diminué mais les équipements étaient tout de même en time-out. Une relance du démon par la page de configuration a réglé le cas.
J'avour que je ne vois pas quelle différence il y a entre une relance par la page de configuration et $_plugin->deamon_start(true)

**Comment by tcharp38** [comment]
Une fois que tu es en beta, je te propose de mettre  le fichier suivant dans core/php. J'ai fait qq modifs pour la "reprise" de connexion.

[AbeilleSerialRead.zip](https://github.com/KiwiHC16/Abeille/files/7626037/AbeilleSerialRead.zip)

Le log le + interessant pour ce cas est ceui de AbeilleSocat. On voit chaque démarrage et chaque "coupure" et comme il y a peu d'infos ca donne un bon historique des coupures wifi.

**Comment by Krankhore** [comment]
En fait non, dans Abeillesocat , ce n'est pas représentatif des coupures WIFI. Les arrêts que tu vois sont en fait les relances par abeille. UNe coupure du wifi n'est pas indique dans AbeilleSocat.

J'ai fait un essai de couper l'alimentation de ma zigate wifi. Après quelque instant la ruche passe en time-out et la zigate2 passe en rouge dans la page santé mais rien dans AbeilleSocat.
Dans AbeilleSerialRead aucun nouveau message.

Puis j'ai rebranché la zigate . Et là, rien ne change, aucune reprise des communication , il faut relancer le démon qui relance donc socat . Et la communication reprend.

Et je mets ton code en place.

**Comment by tcharp38** [comment]
Tu veux dire que "socat" reste connecté meme si coupure ? J'imagine alors qu'il a un timeout interne avant de sortir

> 2021/11/28 15:28:02 socat[713] N starting data transfer loop with FDs [5,5] and [7,7]
> 2021/11/28 15:33:03 socat[713] N socket 2 (fd 7) is at EOF
> 2021/11/28 15:33:04 socat[713] N exiting with status 0
>

**Comment by Krankhore** [comment]
Oui, j'ai refait l'essai :
 si je debranche (**17h59**) la zigate le process Abeillesocat.php reste, 
Au bout de 5 minutes dans la page santé, la ruche est en time-out , la zigate passe en rouge MAIS aucune info dans la log AbeilleSocat. 
Dans AbeilleSerialRead, AbeilleParserLog  plus de nouvelle ligne , 
Seul Abeille et AbeilleCmdLog continue à lister des lignes


Au bout de 15minutes  , pas de modification de socat. Je pense que le process ne s'arrêtera jamais, il reste en ecoute d'un flux qui ne viendra plus.

Et si je rebranche la zigate (**18h15**), j'ai de nouvelles ligne dans AbeilleSerialReader2 : 
_[2021-11-30 17:59:23] Got "80100005880003031D00"
[2021-11-30 **18:15:51]** Le port /tmp/zigateWifi2 a disparu !
[2021-11-30 18:16:02] /tmp/zigateWifi2 port is back_

dans AbeilleSocat2
_[2021-11-30 15:03:46] >>> Démarrage d'AbeilleSocat
[2021-11-30 15:03:46] Daemons: {"cmd":1,"parser":1,"serialRead2":2,"socat2":1,"expected":4}
[2021-11-30 15:03:46] Attention ! Certain systèmes acceptent soit l'option 'raw' soit 'rawer' pour socat. Modifiez la ligne "$parameter=" du fichier AbeilleSocat.php pour mettre la bonne option.
[2021-11-30 15:03:46] Creating connection from 192.168.1.12:9999 to /tmp/zigateWifi2
[2021-11-30 15:03:46] cmd=/usr/bin/sudo socat -d -d pty,raw,echo=0,link=/tmp/zigateWifi2 tcp:192.168.1.12:9999
2021/11/30 15:03:46 socat[545162] N PTY is /dev/pts/2
2021/11/30 15:03:46 socat[545162] N opening connection to AF=2 192.168.1.12:9999
2021/11/30 15:03:46 socat[545162] N successfully connected from local address AF=2 192.168.0.32:47316
2021/11/30 15:03:46 socat[545162] N starting data transfer loop with FDs [5,5] and [7,7]
2021/11/30 **18:15:51** socat[545162] E read(7, 0x55c97959bd20, 8192): No route to host
2021/11/30 18:15:51 socat[545162] N exit(1)
[2021-11-30 18:15:51] Socat exited with ERROR 1
[2021-11-30 18:15:51] <<< Arret du démon 'AbeilleSocat'
[2021-11-30 18:16:02] >>> Démarrage d'AbeilleSocat
[2021-11-30 18:16:02] Daemons: {"cmd":1,"parser":1,"serialRead2":1,"socat2":1,"expected":4}
[2021-11-30 18:16:02] Attention ! Certain systèmes acceptent soit l'option 'raw' soit 'rawer' pour socat. Modifiez la ligne "$parameter=" du fichier AbeilleSocat.php pour mettre la bonne option.
[2021-11-30 18:16:02] Creating connection from 192.168.1.12:9999 to /tmp/zigateWifi2
[2021-11-30 18:16:02] cmd=/usr/bin/sudo socat -d -d pty,raw,echo=0,link=/tmp/zigateWifi2 tcp:192.168.1.12:9999
2021/11/30 18:16:02 socat[675906] N PTY is /dev/pts/3
2021/11/30 18:16:02 socat[675906] N opening connection to AF=2 192.168.1.12:9999
2021/11/30 18:16:02 socat[675906] N successfully connected from local address AF=2 192.168.0.32:54728
2021/11/30 18:16:02 socat[675906] N starting data transfer loop with FDs [5,5] and [7,7]_

Donc socat réagit au moment ou la zigate est rebranché mais pour autant les messages n'arrrivent pas. Il faut que la relance de socat soit via redémarrage du démon ( à**18h24**) pour que la conversation reprenne.
Et là, les messages reprennent dans AbeilleSerialRead2 
_[2021-11-30 17:59:23] Got "80100005880003031D00"
[2021-11-30 18:15:51] Le port /tmp/zigateWifi2 a disparu !
[2021-11-30 18:16:02] /tmp/zigateWifi2 port is back
[2021-11-30 18:24:32] >>> Démarrage d'AbeilleSerialRead sur port /tmp/zigateWifi2
[2021-11-30 18:24:32] Daemons={"cmd":1,"parser":1,"serialRead2":1,"socat2":1,"expected":4}
[2021-11-30 18:24:32] /tmp/zigateWifi2 port opened
[2021-11-30 18:24:32] Got "8024000D4104000000158D0000CE20950F00"
[2021-11-30 18:24:32] Got "80000007A300000024000000"
[2021-11-30 18:24:32] Got "800000079100000016000000"
[2021-11-30 18:24:32] Got "800000078E00000009000000"
[2021-11-30 18:24:32] Got "80090016AB000000158D0000CE20956D299FB86486A8483F860F00"
[2021-11-30 18:24:32] Got "800000078500000002000000"_

C'est un peu différent de ce pourquoi l'issue a été ouvert puisque dans le cas d'origine, cela s'accompagne d'un boucle CPU en relançant indéfiniment socat mais peut-être que les 2 sont liés. En tout cas, la coupure par débranchement et rebranchement de la zigate est facilement reproductible.

**Comment by tcharp38** [comment]
Ha m...
Ce que tu es en train de dire c'est que si jamais la connexion Wifi est perturbée ou la zigate Wifi down, il faut absolument redemarrer socat car ce dernier ne sait pas reprendre la main.

En ligne avec ca ?

D'ailleurs ces derniers essais sont avec le code modifié ?

**Comment by Krankhore** [comment]
Oui ce dernier essai était avec la version beta et le code modifié.
Dans la version stable, lors de l'essai du début d'après midi,pour autant que je me souvienne,  socat n'avait pas indiqué d"erreur lors la zigate a été rebranché. Et donc n'a pas été redémarré par abeille. 

Dans le dernier cas que j'ai provoqué avec la coupure de la zigate  , socat s'arrête en erreur au moment de la reprise de la zigate (donc différent par rapport à l'essai avec la version stable ou socat ne s'est pas arrêté mais c'est peut être un hasard). 
Abeille réagit et relance socat. Ce que je ne comprends pas , c'est pourquoi cela ne marche pas. 
Il a fallu que je relance le démon par la page de configuration , cela relance aussi socat. Et là ça marche. Pourtant dans les log de AbeilleSocat il n'y a aucune différence de message entre les 2 relances.

Et dans le cas du dysfonctionnement de cette nuit, abeille faisait bien la relance de socat mais cela bouclait car socat s'arrêtait à chaque fois 
2021/11/30 07:26:03 socat[315912] N socket 2 (fd 7) is at EOF
2021/11/30 07:26:03 socat[315912] N exiting with status 0

Donc ce n'est pas simple de conclure qu'il faut 'juste' relancer socat après une coupure du wifi ou de la zigate.

Que fait de plus la relance du démon par la page de config qui ne serait pas fait lors de du redémarrage d'AbeilleSerialRead et AbeilleSocat ?
Sinon, demain, je ferais plusieurs essai de coupure nette pour verifier que le comportement est à chaque fois le même , et je laisserais également la zigate coupée plus longtemps pour voir si socat finit pare partir en time-out.

**Comment by tcharp38** [comment]
Il faut que je reflechisse à ca à tete reposée mais la je suis un peu trop HS.

Par contre dans tes essais, je crois que tu peux augmenter l aspect verbeux de socat en ajoutant "-d"
La on a normalement deja "-d -d", donc un "-d -d -d" pourrait donner d'autres infos. A voir.

Pour repondre à ta question concernant la relance je ne vois pas la difference si ce n'est que tous les démons sont tués et redemarrés via la page de config. Ce qui me renvoi vers le lien entre socat et serialread.
Haaaaa... une boulette. Je reviens vers toi

**Comment by tcharp38** [comment]
[AbeilleSerialRead.zip](https://github.com/KiwiHC16/Abeille/files/7629234/AbeilleSerialRead.zip)

Utilise celui la. J'avais oublié des choses.
Je refais une beta et je file me pieuter. A+

**Comment by Krankhore** [comment]
Bonsoir @tcharp38 ,
j'ai refait quelques teste avec la version beta d'hier et AbeilleSerialRead d'hier soir.
Contrairement à ce que j'avais dit, socat finit en time-out au bout d'un certain délai. Quand j'ai dit que socat s'est arrête au moment où j'ai rebranché la zigate, c'était une coincidence (justement le time-out de socat)

Pour résumé, les essais sont plutôt bon. Je n'ai eu aucun dysfonctionnement .
**premier test :**
14h10 je débranche la zigate 
 socat continue à essayer d'envoyer 
14h16 ruche passe en time-out et zigate en rouge sur la page santé
14h27 socat s'arrête 
abeille relance socat qui s'arrête immédiatement ( no route to host)
abeille relance toutes les minutes
14h34 je rebranche la zigate
14h35 les échanges de messages reprennent. Tous est à nouveau normal

[AbeilleLogs-211201.tar.gz](https://github.com/KiwiHC16/Abeille/files/7636367/AbeilleLogs-211201.tar.gz)

**deuxième essai**
17h02 debranchement de la zigate et remise au bout de 10 secondes
 plus d'échange de messages, ruche en time-out; zigate en rouge. Socat continue a essayer d'envoyer
17h18m52s socat s'arrête en time-out
abeille relance socat
17h19m23s les echanges reprennent , tout revient à le normale

[AbeilleSerialRead2.log](https://github.com/KiwiHC16/Abeille/files/7636392/AbeilleSerialRead2.log)
[AbeilleSocat2.log](https://github.com/KiwiHC16/Abeille/files/7636393/AbeilleSocat2.log)

**troisième essai**
18h08 je bloque le flux par iptables
18h09 j'annule le blocage
les echanges reprennent , juste un flot de 12 messages alors que normalement c'est 2 messages toutes les minutes

[AbeilleSerialRead2(1).log](https://github.com/KiwiHC16/Abeille/files/7636418/AbeilleSerialRead2.1.log)
[AbeilleSocat2(1).log](https://github.com/KiwiHC16/Abeille/files/7636420/AbeilleSocat2.1.log)

**quatrième essai**
18h12 blocage par iptables
18h29 socat s'arrête en time-out 
abeille relance, cette fois socat met deux minutes pour s'arrêter (contrairement au débranchement ici la route existe mais le flux est bloqué)
abeille relance socat
18h34 j'annule le blocage par iptables
18h34m06s les echanges de messages reprennent

[AbeilleSocat2(2).log](https://github.com/KiwiHC16/Abeille/files/7636458/AbeilleSocat2.2.log)
[AbeilleSerialRead2(2).log](https://github.com/KiwiHC16/Abeille/files/7636459/AbeilleSerialRead2.2.log)

Il y a peut être des cas plus  tordus qui pourraient arriver, mas dans les quatre test, le comportement a été correct .

Dans la beta disponible aujourd’hui , as tu mis AbeilleSerialRead que tu m'as envoyé hier soir ? auquel cas, j'installerais la nouvelle beta pour laisser roule la vm de test quelque temps.

**Comment by tcharp38** [comment]
Salut @Krankhore 
Merci pour ces essais tres précis.

Ca semble se derouler pas trop mal sauf pour le cas 2 ou socat se coupe 10min apres l'arret de la Zigate. Ca c'est pas cool du tout.
Peut etre que 10mins c est le timeout par defaut. Auquel cas il doit y avoir une astuce pour le réduire.

Peut etre ca
![image](https://user-images.githubusercontent.com/35221038/144451772-5ed0e7a0-07f5-41ba-8591-30618a5fc6e5.png)
Si tu veux tester (cas 2) avec "-T 120" pour un timeout de 2min.

Oui cette beta devait inclure mes dernieres améliorations du serialRead

**Comment by Krankhore** [comment]
Ok, j'installe la beta. Un délai 10 minutes , si la situation se rétablit ensuite, je ne trouve pas que ce soit forcément gênant mais je faits essayer avec le paramètre -T120 à socat puisque de toute façon il y a au minimum un échange toute les minutes même lorsqu’il n'y a aucun équipement connecté à la zigate , un time-out de 2 minutes doit être une bonne durée.

Une précision , ce n'est pas seulement le cas 2 ou socat part en time-out . C'est dans le cas 1,2 et 4. Il n'y a que le cas 3 ou la coupure des flux n'a duré qu'une minutes ou soat ne s'est pas arrêté et que la reprise des messages  s'est faite.

De toute façon, dans le cas 1 et 2 ( débranchement de la zigate , ou coupure de son alimentation ), comme la zigate redémarre, il faudra forcement que socat finisse en time-out car la session tcp n'est plus activé coté zigate.

**Comment by tcharp38** [comment]
Oui 10min sans connexion alors que la zigate est revenue 10sec apres, je considere ca pas acceptable.
Ce cas 2 est tres particulier car le + long a revenir à une situation normale.

Du coup j'attends de voir ce que disent tes essais avec timeout.

**Comment by Krankhore** [comment]
J'ai donc installé la dernière beta 
En fait , le time-out est  plus long.
Je viens de faire plusieurs essais malgré -T120 , le time-out est au bout de **17m8s**
Du coup j'ai vérifié les logs d'hier plus précisément et c'était bien 17m et 15s dans le cas 1 et 16m56s dans le cas 2 )
Donc 17 minutes  (ma montre n'affichant pas les secondes l'heure exacte de débranchement  reste approximative à la minute ) 

Donc je te joins les logs : dans mes heures notées ici j'ai pris soin de relevé les secondes 
23h55m17s relance démon avec socat **-T120**
23h56m30s debranche pendant 10s
socat tombe au bout de 17m et 8s 
redémarrage automatique par abeille et reprise messages

0h19m02s nouveau debranchement de 10s (socat est avec **-t120** plutôt que **-T120** , j'avais peu d'espoir mais au cas où)
socat tombe au bout 17m 26s
redémarrage automatique par abeille et reprise des messages

Puis j'ai fait des essais en udp au lieu de tcp, mais visiblement la zigate refuse
Puis j'ai mis  **-T55** et là effectivement socat s'arrête après un premier echange de message en indiquant inactivité pendant 55secondes (donc le paramètre est bien pris en compte)

Dans les faits , le timeout pour inactivité ne peut pas marcher car Abeille envoie un message toutes les minutes à la zigate (je suppose que c'est pour lui demander son statut et vérifier qu'elle répond bien et le cas échéant la psser en rouge)
Dans AbeilleSocat on voit ces messages toutes les minutes jeedom-> zigate et une dexième ligne zigate-> jeedom.
Quand je débranche la liaison est coupée, et en des paquets de 3 messages jeedom-> zigate toutes les minutes danz Abeillesocat. Donc d'un point de vue socat, il n'y pas d'inactivité (et donc , je ne sais pas ce qui permet à socat de s'arrêter au bout de 17 minutes de non réponse).

Tu trouveras tout ces comportements dans la log jointe.

Maintenant , ce type de cas doit rester exceptionnel. Cela correspondrait à une perte d'alimentation de la zigate ( defaut du port usb ou de l'alimentation usb, ) Dans mes tests les cas 3 ou 4 sont plus probables  (redémarrage du routeur wifi, perte de paquets, perturbation momentané du wifi) . Et à priori, cela réagit maintenant bien soit en reprenant immédiatement soit après un time-out de 17 minutes.
Mais en tout cas cela reprend alors que l'incident d'origine était une perte du dialogue et une boucle cpu nécessitant une intervention manuelle pour relancer le démon. 


[AbeilleLogs-211203.tar.gz](https://github.com/KiwiHC16/Abeille/files/7645843/AbeilleLogs-211203.tar.gz)

Une petite interrogation:
en fonctionnement normal abeille envoit 10 octet, la zigate reponde par 41 octets. Quand la liaison est rompu, abeille continue à envoyer 10 octets et au bout d'un moment socat indique quelques messages plus court( mais variables)  puis le les messages de 10 octets reprennent. Je ne vois pas à quoi cela correspond;
ex ;
_2021/12/03 00:31:23 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:31:24 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:31:25 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:32:22 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:32:23 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:32:24 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:33:23 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:33:24 socat[2333871] I transferred 8 bytes from 5 to 7
2021/12/03 00:33:24 socat[2333871] I transferred 2 bytes from 5 to 7
2021/12/03 00:33:25 socat[2333871] I transferred 8 bytes from 5 to 7
2021/12/03 00:33:25 socat[2333871] I transferred 2 bytes from 5 to 7
2021/12/03 00:34:22 socat[2333871] I transferred 8 bytes from 5 to 7
2021/12/03 00:34:22 socat[2333871] I transferred 2 bytes from 5 to 7
2021/12/03 00:34:23 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:34:24 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:35:23 socat[2333871] I transferred 10 bytes from 5 to 7
2021/12/03 00:35:24 socat[2333871] I transferred 10 bytes from 5 to 7_
ou 
_2021/12/02 23:58:24 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/02 23:58:25 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/02 23:59:22 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/02 23:59:23 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/02 23:59:24 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:00:02 socat[2316205] I transferred 16 bytes from 5 to 7
2021/12/03 00:00:03 socat[2316205] I transferred 16 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 1 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 3 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 4 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 1 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 6 bytes from 5 to 7
2021/12/03 00:00:04 socat[2316205] I transferred 1 bytes from 5 to 7
2021/12/03 00:00:24 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:00:25 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:00:26 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:01:22 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:01:23 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:01:24 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:02:22 socat[2316205] I transferred 1 bytes from 5 to 7
2021/12/03 00:02:22 socat[2316205] I transferred 9 bytes from 5 to 7
2021/12/03 00:02:23 socat[2316205] I transferred 10 bytes from 5 to 7
2021/12/03 00:02:24 socat[2316205] I transferred 10 bytes from 5 to 7_

Voilà pour aujourd'hui. Si tu as d'autres idées, je suis prêt à faire d'autres tests.
Bonne nuit.

**Comment by tcharp38** [comment]
Vraiment merci pour tes essais.

Effectivement Abeille interroge la zigate toutes les minutes. De mémoire c'est surtout pour le type WIFI. Pas d'interet pour les autres types. Du coup au lieu de chercher à faire tomber Socat peut etre que je peux revoir la copie cote Abeille pour que lui meme redemarre Socat si pas de news.

Mais quel est ton point de vue ? Tout va bien comme ca ? C 'est assez "safe" ? Ou il faut améliorer qqch ?

**Comment by Krankhore** [comment]
Je dirais que ça va déjà bien comme cela puisque maintenant le redémarrage de socat fonctionne bien.

En tout cas dans les cas de tests, plus de cas ou il faut relancer à la main ni de consommation cpu excessive. Cela restera à confirmer après quelques temps de fonctionnement lorsque cela se dispo en stable ( sur ma prod je n'ait eu que 5 cas de boucles en 3 mois) et  voir si cela règle aussi le problème de @glelan.

Si tu peux redémarrer socat après 2 minutes sans news de la zigate ce sera encore mieux puisque cela évitera les 17 minutes de time-out.Et une relance à cette fréquence n'induire pas de surcharge cpu. Si tu fais cette évolution, il faudra aussi ajouter une notification jeedom lorsqu'il y à redémarrage parce que pas de réponse de la zigate afin que l'utilisateur soit averti  et puisse vérifie ce qui s'est passé.

**Comment by tcharp38** [comment]
Ok, on est en ligne.
J'ai ouvert un sujet dédié pour amélioration.

**Comment by tcharp38** [comment]
@Krankhore 
J'ai besoin de faire une stable. Vois tu des regressions critiques ?
Qu'en penses tu ? Je peux basculer la beta en stable ou tu vois des trucs importants à fixer avant ?

**Comment by Krankhore** [comment]
@tcharp38 
Pour moi c'est bon, tu peux basculer la beta en stable

**Comment by tcharp38** [comment]
C'est chose faite.
Nouvelle stable et nouvelle beta.
On clos ce sujet ?

**Comment by Krankhore** [comment]
Oui, bonne journée
