### ISSUE TITLE
Problème inclusion volets nouvelle génération Profalux Abeille

### ISSUE THREAD

**Issue by fichncheaps** [KiwiHC16/Abeille#2205]
Bonjour,
J'avais des volets profalux avec moteur zigbee première génération qui fonctionnaient parfaitement avec Abeille
J'ai changé 4 de ces volets la semaine dernière et je pense qu'ils sont équipés du moteur nouvelle génération.
Sur ces 4 volets, j'ai pu en inclure 2 sans soucis sur Abeille, pour les 2 autres c'est tout simplement impossible. Ils s'affichent en inconnu et après plus rien. Je dois ensuite tout réinitialisé télécommande et moteur car plus rien ne marche.
Pouvez vous m'apportez un peu d'aide?
J'ai lu pas mal d'autres articles sur le sujet mais je n'ai pas vraiment trouvé de solution
Merci d'avance

**Comment by tcharp38** [comment]
Salut.
Les nouveaux volets ont une autre methode d'identification.
Peux tu passer en mode debug/5000 lignes: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support
retenter une inclusion d'un volet recalcitrant
et me filer le package de logs (page support telecharger tout)

**Comment by fichncheaps** [comment]
Merci pour ton retour hyper rapide :) 
Voici les logs, je viens de faire le test à l'instant

[AbeilleLogs-211129 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7618505/AbeilleLogs-211129.1.tar.gz)

Et si jamais ca peut t'aider voici l'étiquette du moteur
![20211129_144900](https://user-images.githubusercontent.com/95218439/143879784-b1580425-15c7-48ba-8628-2cfae69c6419.jpg)

**Comment by tcharp38** [comment]
Quelle est l'adresse IEEEE du volet ?
Je vois ca : 20918A0000112D8D mais j'ai l'impression qu'il s'agit d'une telecommande (id=MAI-ZTS)

Ha autre chose. Je vois que tu as un firmware 3.1c. Je te suggere de migrer vers qqch de + recent. Au moins 3.1D mais sinon 3.20-legacy. Pas de reappairage à faire du coup tant que tu restes en legacy

**Comment by fichncheaps** [comment]
Comment puis je trouver cette adresse?

**Comment by tcharp38** [comment]
En cliquant sur l'équipement inconnu, page avancée
Tu as l'adresse courte et l'adresse IEEE

Mais maintenant j'en suis sur. La seule annonce que je vois dans tes logs est celle d'une telecommande. Donc  à refaire.

Je n'ai pas ces volets mais je sais que leur procedure d'inclusion est differente (des temps plus longs je crois).
As tu trouvé la bonne procédure ?

**Comment by fichncheaps** [comment]
J'ai 3 équipements inconnus:

   - Abeille1-434 -  4B3C / 20918A0000112D3A
   - Abeille1-435 -  7BE3 / 20918A0000112D8D
   - Abeille1-436 -    9676 / 20918A0000112D8F

Pour les 2 autres (mes 4 volets ont été livrés en même temps) la procédure
était la même que pour les anciens volets et ca a marché du premier coup

**Comment by tcharp38** [comment]
20918A0000112D8D c'est une telecommande nouvelle generation. Pour ca je peux faire en sorte que ca ne soit plus "inconnu".
Les autres.. aucune idée.
Il me faut des logs avec le volet.

**Comment by fichncheaps** [comment]
Et est ce que moi je peux te récupérer ces logs du volet?

**Comment by tcharp38** [comment]
[MAI-ZTS_Profalux.zip](https://github.com/KiwiHC16/Abeille/files/7619078/MAI-ZTS_Profalux.zip)
A decompresser dans core/config/devices
La telecommande sera reconnue et cachée car on ne peut probablement rien faire avec cote Abeille, comme les gen 1.

**Comment by fichncheaps** [comment]
Maintenant j'ai bien les télécommandes,
J'ai refait plusieurs tests mais toujours rien concernant le volet.

Je te rejoins les logs au cas ou

Pour les logs du volet, je peux faire quelque chose?

**Comment by tcharp38** [comment]
Tant que tu ne vois pas une "device announce" d'un volet manquant dans AbeilleParser, la procedure d'inclusion est probablement pas bonne donc faut creuser les docs Profalux. Tu procedes comment  d'ailleurs ?

**Comment by fichncheaps** [comment]
Je suis la même procédure que pour les anciens:

   - Réinitialisation de la télécommande 5x R puis stop
   - Je mets Abeille en mode inclusion
   - J'appuie sur R une fois + flèche du haut - Ca fait bien bouger le
   volet et après bouton stop et là plus rien ne se passe

J'ai essayé de regarder dans la documentation mais pour l'instant rien
trouvé
Je continue à creuser

La procédure a marché pour les 2 autres volets.

**Comment by tcharp38** [comment]
@fichncheaps 
Je vais confirmer ca ce soir en refaisant qq essais mais je pense que tu dois juste
- mettre la zigate en mode inclusion
- 1x R + fleche haut
- laisser faire l inclusion qui doit se terminer par un AR du volet

En d'autres termes, je ne toucherais pas au STOP.

**Comment by tcharp38** [comment]
@fichncheaps 
Bon j'ai fait des essais sur la beta du jour (dispo demain) et je confirme les points suivants en faisant 1xR + 1xHAUT

- Si le volet est deja inclu il sort du reseau. Si jamais la zigate etait en mode inclusion alors en sortant il "ferme" le reseau et la zigate ne clignote plus
- Si il n'est pas dans le reseau, il suffit de mettre la zigate en mode inclusion et de faire 1xR + 1xHAUT. Faut le laisser aller jusqu'au bout (2 AR) et PAS jouer avec le bouton STOP.

Pendant mes essais j'ai trouvé une regression que j'ai introduit recemment donc la beta de demain (211202-BETA-2) contiendra le correctif associé.

**Comment by fichncheaps** [comment]
Salut

Je viens de refaire un test avec seulement 1xR + 1xHaut et je ne vois rien
arriver sur Abeille
Je te mets les logs au cas où
Le volet fait bien quelques va et vient après avoir fait la combinaison
mais rien ne se passe et ensuite la télécommande n'est plus associée au
volet et je suis obligé de tout réinitialiser
Je ferai encore un test semaine prochaine avec mon second volet qui pose
problème et qui est moins accessible pour voir si le comportement est le
même

Merci en tout cas pour ton support

**Comment by tcharp38** [comment]
Etais tu en mode inclusion ?
Tu n'as pas attaché de logs donc je ne peux pas verifier.
Et du coup ca peut peut etre expliquer que la telecommande quitte son volet.

**Comment by fichncheaps** [comment]
Oui J'étais bien mode inclusion
Voici les logs

[AbeilleLogs-211204 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7656458/AbeilleLogs-211204.1.tar.gz)
n

**Comment by tcharp38** [comment]
Effectivement ton volet ne se signale pas du tout contrairement à la telecommande (ieee 20918A0000112D8D) qui elle se signale 3 fois.
Juste avant que tu fasses cette manip, la telecommande pilotait elle encore le volet ?
C'est elle qui envoi l ordre au volet donc le couple volet/telec est tres important. C'est la priorité.

**Comment by fichncheaps** [comment]
Oui la télécommande fonctionne parfaitement avant de faire la manipulation

**Comment by tcharp38** [comment]
Ha zut.
Du coup tu en es ou ?

**Comment by fichncheaps** [comment]
Pour le moment toujours au même stade. Je n'ai pas pu faire de nouvel essai.
Je vais essayer de faire cela début de semaine prochaine.
Est ce que ca pourrait être un problème de porter de la zigate? Sachant que
j'ai le même volet dans la même pièce (à 1m d'écart) qui fonctionne sans
problème.

**Comment by tcharp38** [comment]
Je n'y crois pas une seconde.
D'abord parce que j'ai moi aussi des profalux qui couvrent l'appart et forcement plusieurs tres loin de la zigate
Et parce qu'ils se relaient entre eux donc le plus proche de la zigate va faire le routage au suivant.. etc etc.
Et enfin parce que tu recois la telecommande de la meme piece que le volet.

Ha... du coup ca me fait poser une question. La telecommande doit rester à proximité du volet donc la manip est
- zigate en mode inclusion 
- puis tu vas dans la piece du volet/telecommande et tu fais le 1XR + HAUT de la
C'est bien ca que tu as fait ?
Si non, peux etre que la telecommande etait trop loin de son volet.

**Comment by fichncheaps** [comment]
Oui c'est bien ce que j'ai fait.
La télécommande était toute proche du volet.
Je refais un test et te redis

**Comment by fichncheaps** [comment]
Hello

"Attention: Un vieux FW est détecté pour la zigate 1. Une version >= 3.1D
pourrait être requise pour certains équipements."
Est ce que ca pourrait expliquer mon problème?

**Comment by tcharp38** [comment]
Non je ne pense pas. Je ne vois pas ce qui pourrait masquer le device announce du volet. Mais tu devrais faire la mise à jour vers 3.20

**Comment by fichncheaps** [comment]
Ok je vais faire la mise à jour et je referai les tests

**Comment by Seby9576** [comment]
Salut,

J'ai un REX au sujet des volets profalux. Il ne faut rien faire après r+haut. Il faut attendre le clignotement 2x vert de la télécommande. Mais surtout pas de stop (ne rien toucher ) même si ca clignote rouge et que ca clignote plus pendant quelques secondes ca devrait reclignoter de nouveau après et ca jusqu'à avoir les 2 x vert. Moi inclusion toujours nickel comme ca avec volet et télécommande à chaque fois.

**Comment by tcharp38** [comment]
Tout à fait en ligne avec mes observations.

**Comment by Seby9576** [comment]
Dans la procedure kiwihc16 il fallait faire stop il me semble. D'ailleurs est ce que Kiwi hc16 c'est toi ? 
Je viens de lire plus haut qu'il se posait la question de la distance. J'ai une grand maison et des volets très éloigné mais aucun soucis. Pour l'inclusion ça peut marcher du premier coup mais pas toujours. 
Bref ça va finir par passer si tu respectes la procedure

**Comment by tcharp38** [comment]
Non KiwiHC16 n'est pas moi :)
Oui il a mis ca dans la procédure car extrait de la doc officielle Profalux mais pour moi ce truc n'est pas necessaire pour l'inclusion avec Abeille.
@fichncheaps Tu as pu progresser ?

**Comment by fichncheaps** [comment]
Hello
Non rien de mieux
J'ai mis à jour ma zigate en 3.21 dans le doute
J'ai fait que R + haut mais rien ne se passe de plus

**Comment by tcharp38** [comment]
@fichncheaps 
Donc tu as refait l'appairage avec ton volet et ta telecommande peut controller le volet à nouveau ?

**Comment by fichncheaps** [comment]
Oui c'est ca.
J'ai fait R + haut
La télécommande clignotte et le volet fait un ou 2 va et vient
puis plus rien et la télécommande ne commande plus le volet
Donc je suis obligé de refaire l'association télécommande volet avec une
réinitialisation du volet

**Comment by tcharp38** [comment]
M... désolé pour toi.
Tous tes volets se comportent comme ca ou seulement celui la ?

**Comment by Seby9576** [comment]
C'est bizarre effectivement.

**Comment by fichncheaps** [comment]
Seulement 2 volets sur les 6 que j'ai

**Comment by tcharp38** [comment]
@fichncheaps 
Pour info, tout souci est similaire à d'autres cas sous Domoticz.
On attend un retour de Profalux.

**Comment by fichncheaps** [comment]
Hello

Est ce que vous avez eu un retour de Profalux?
Est ce que je peux faire quelque chose à mon niveau?

Bonne jounrée

**Comment by tcharp38** [comment]
Salut @fichncheaps 
Oui j'ai eu un retour via Pipiche sur Domoticz.
Il faut qu'on mette en place une autre procedure mais je n'ai pas eu le temps de m'y pencher.

**Comment by fichncheaps** [comment]
Pas de soucis il n'y a pas de réelle urgence
Mais c'est cool de savoir que ca avance et qu'il y a potentiellement une
piste!

**Comment by tcharp38** [comment]
Hello
Est ce que qqn pourrait faire des essais si je lui file un code ?

**Comment by fichncheaps** [comment]
Hello

Sans problème de mon côté mais pas avant jeudi ou vendredi

**Comment by tcharp38** [comment]
@fichncheaps 
Cool. Donc
- fais une copie de sauvegarde de core/class/AbeilleParser.class.php
- decompresse le fichier attaché dans core/class
- redemarre les demons Abeille
- rente une inclusion (note l heure)
- et file moi le package de logs STP ainsi que ton résumé de ce que tu observes
Merci

[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8031914/AbeilleParser.class.php.zip)

**Comment by SimonChatillon** [comment]
Bonjour, je me joins au sujet car j'ai également des volets profalux zigbee installés tout récemment, et j'aimerais pouvoir les piloter avec Alexa. Pour l'instant je possède uniquement une passerelle zigbee générique avec l'appli smart life. y a-t-il une chance que l'appairage fonctionne avec cet équipement ? Quelqu'un a-t-il testé ?

**Comment by tcharp38** [comment]
@SimonChatillon 
Le sujet ici concerne le plugin Abeille pour les passerelle "Zigate". Je crois comprendre que ca n'est pas ton cas. Je ne sais pas ce que tu entends par "passerelle generique zigbee".

**Comment by SimonChatillon** [comment]
Désolé si je suis un peu hors-sujet, par passerelle générique j'entend une petite box (hub ou gateway zigbee) type LIDL home qui s'interface avec les applications Tuya/Smart Life (la mienne est précisément la Teekar Zigbee Hub). Dans l'application Smart Life il y a bien l'entrée volet roulant zigbee, je pensais que le protocole zigbee était universel et compatible avec tous types d'appareil mais ça n'est peut être pas si simple (je suis néophyte sur zigbee et les appareils types zigate etc, je commence à me documenter sur le sujet)

**Comment by tcharp38** [comment]
@SimonChatillon 
Manque de pot ca n'est pas si simple. Le standard est une chose mais pas assez rigide donc presque chaque constructeur y ajoute sa touche.
Le plugin (ici Abeille), gere le tout en fonction aussi des particularités de la passerelle.
Enfin je ne crois pas 1sec qu'une passerelle Lidl puisse supporter un volet Profalux. Bonne découverte.

**Comment by fichncheaps** [comment]
[AbeilleLogs-220210.tar.gz](https://github.com/KiwiHC16/Abeille/files/8038946/AbeilleLogs-220210.tar.gz)

@tcharp38 je viens de faire un nouveau test
Le comportement est le même qu'avant.
Je me Abeille en inclusion, puis je faire R + haut sur la télécommande.
La télécommande clignotte 2 fois bleu, s'arrête de clignoter environ 15 - 20 secondes puis se remet à clignoter bleu en continue un moment avant d'arrêter.
Après cela la télécommande n'est plus associée au volet
Je te joins les logs ABeille
A dispo pour refaire des tests si besoin

**Comment by tcharp38** [comment]
@fichncheaps 
Merci. J'ai trouvé un autre bug grace a tes logs.

Du coup meme manip à faire avec le code suivant:
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8039815/AbeilleParser.class.php.zip)

**Comment by fichncheaps** [comment]
@tcharp38 même comportement avec la nouvelle classe
Voici les logs
[AbeilleLogs-220210.tar.gz](https://github.com/KiwiHC16/Abeille/files/8040816/AbeilleLogs-220210.tar.gz)
J'ai fait le test à 13h10

**Comment by tcharp38** [comment]
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8041124/AbeilleParser.class.php.zip)

Meme comportement visible mais ca avance.
Une autre correction donc meme topo.
Désolé pour les essais.
Merci

**Comment by fichncheaps** [comment]
[AbeilleLogs-220210 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8041532/AbeilleLogs-220210.1.tar.gz)

@tcharp38 
Pas mieux et même comportement. Test à 14h58
Pas de soucis pour les tests si ca peut faire avancer :)

**Comment by tcharp38** [comment]
Désolé mais cette fois les logs sont trop courts.
Si le test est à 14h58, le log s'arrete à 14h59, et je ne vois que la telecommande qui s'annonce, pas le volet.
Je fouille quand meme mais je doute pouvoir en tirer qqch.

D'ailleurs j'ai bien l'impression que seule la telecommande s'annonce. Je ne vois jamais le volet.

Si on ne s'en sort pas rapidement, j'irai chez le frangin planter ses volets. Je crois qu'il a recu la nouvelle generation.

**Comment by fichncheaps** [comment]
OK je refais un test en laissant plus longtemps

**Comment by fichncheaps** [comment]
[AbeilleLogs-220210 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8041984/AbeilleLogs-220210.2.tar.gz)

Nouveau test fait à 15h58 @tcharp38

**Comment by tcharp38** [comment]
Idem.
Pas de volet. La telecommande s'annonce au mons 5 fois, comme si elle n'arrivait pas à contacter le volet.
Mais du coup la quel est le status ? Elle controle encore le volet avant et apres le test ?

**Comment by fichncheaps** [comment]
Le statut est le meme
Je fais la procédure d'association avec R + Haut et ensuite je suis obligé
de réinitialiser complètement le volet pour ràassocier la télécommande car
plus rien ne fonctionne

**Comment by fichncheaps** [comment]
On est d'accord que la procédure que je fais pour l'association est
correcte? Il n'y a pas de nouvelle procédure?

**Comment by tcharp38** [comment]
Oui je suis d'accord.
Mais aussi bien jusque la on pensait que c etait Abeille qui foutait la pagaille lors de l'appairage volet<>telecommande, mais la je ne vois pas ce cas car le volet ne se presente meme pas.

Je vais tacher de trouver du temps pour aller faire ca chez le frangin.
Je te tiens au jus.

**Comment by fichncheaps** [comment]
Top merci beaucoup en tout cas

**Comment by tcharp38** [comment]
Ote moi d'un doute.. entre chaque essai tu as été obligé de faire la manip de reset electrique pour que la telecommande controle à nouveau le volet n'est ce pas ?

**Comment by fichncheaps** [comment]
Oui
Reset électrique. Manip avec le fil marron et noir. Nouveau reset et après
reassociation de la télécommande

**Comment by tcharp38** [comment]
Donc je ne vois pas de faille à ca.

**Comment by fichncheaps** [comment]
Hello

J'ai trouvé cet article sur le forum zigate, est ce que tu penses que ca
vaut le coup que je teste?

Procédure de réinitialisation des volets Profalux MOT-C1Z06C

A) Sur la télécommande :

Appuyer 5 fois sur le bouton R à l’arrière, la LED clignote plusieurs fois
pour indiquer la réinitialisation de la télécommande.

B) Sur le Volet :

1. Couper l’alimentation électrique ;

2. Brancher le fil noir avec le marron (le bleu est sur le neutre, le noir
et le marron sont sur la phase).

3. Remettre l’alimentation.

4. Attendre 3 SERIES de va-et-vient du volet (environs 60 secondes).

5. Au début de la 3ème SERIE de va-et-vient, coupez l’alimentation
électrique.

6. Rebrancher le fil noir avec le bleu (le bleu et le noir sont sur le
neutre, le marron est sur la phase).

7. NE PAS remettre l’alimentation électrique.

C) Dans Jeedom (quelques soit le module Zigbee) :

Mettre le démon/réseau Zigbee en mode inclusion.

D )Sur le Volet:

- Remettre l’alimentation électrique.

- Le volet fait un ou plusieurs va-et-vient et entre dans le réseau Zigbee
(s’il n’en trouve pas, il créé son propre réseau et devient le coordinateur
de celui-ci).

- Jeedom indique l’arrivé d’un nouveau périphérique Zigbee avec l’adresse
IEEE du volet.

- Ensuite le volet va faire des va-et-vient sans arrêt indiquant qu’il veut
associer une télécommande.

E) Sur la télécommande

- Appuyez sur Stop.

- La LED va clignoter vert, lorsque l’association avec le volet sera faite,
le volet arrête ses va-et-vient et la LED va arrêter de clignoter.

**Comment by tcharp38** [comment]
Salut.
Ha oui. Une procedure legerement differente mais qui sait, si tu en as le courage.
Par contre je ne la conseillerai jamais. Bien trop compliquée. Donc je compte toujours de mon coté faire des essais et trouver la bonne combinaison.

**Comment by Seby9576** [comment]
Salut,

Pour information pas besoin de couper l'électricité pour le reset, il faut simplement faire toucher les deux fils pendants 5 secondes.

Bon courage

**Comment by fichncheaps** [comment]
Ah oui? Pas de risque que ca abime le volet?

**Comment by Seby9576** [comment]
Non pas du tout j'ai vu le mec de profalux faire ca, du coup j'ai fait ca a chaque fois que j'ai eu besoin de faire un reset. Aucun constructeur ne te demandera de faire une manip sous tension

**Comment by tcharp38** [comment]
Oui donc la tu es sous tension alors fais gaffe. Je fais la même chose mais je laisse pas traîner les doigts 😉

**Comment by fichncheaps** [comment]
### VICTOIRE!!!!!!!!!!!!!!!!!!!!

J'ai enfin pu inclure mes 3 volets récalcitrants!
Je suis à tout hasard retourner sur le site de profalux et il y a une nouvelle documentation avec une nouvelle procédure pour rejoindre le réseau:
- Prendre la télécommande du volet dont le moteur a été changé. Faire 4 appui court sur R , puis 1 appui long de 15 secondes sur R.
- Attendre les mouvements du volet
- Pendant les mouvements du volet, faire un appui sur le bouton Stop.
- Attendre la fin des voyants
Avec cette procédure les 3 volets ont pu être appairé du premier coup

Je joins la doc ici et @tcharp38 je te joins les logs si tu veux encore y jeter un coup d'oeil. Les tests ont été faits entre 9h40 et 10h02

Merci encore pour votre aide!!!
Et j'espère pouvoir en aider certains

[AbeilleLogs-220215.tar.gz](https://github.com/KiwiHC16/Abeille/files/8067478/AbeilleLogs-220215.tar.gz)
[Notice SAV Moteur Zigbee - A partir de septembre 2021 - NSAV061.pdf](https://github.com/KiwiHC16/Abeille/files/8067481/Notice.SAV.Moteur.Zigbee.-.A.partir.de.septembre.2021.-.NSAV061.pdf)

**Comment by Seby9576** [comment]
> Oui donc la tu es sous tension alors fais gaffe. Je fais la même chose mais je laisse pas traîner les doigts 😉

Non aucun risque tant que les doigts reste sur l'isolant

Bravo pour ta persévérance @fichncheaps

**Comment by tcharp38** [comment]
Bien joué @fichncheaps 
Sauf que du coup j'ai un doute. J'ai modifié le code pour ce type de periph et je vois que la modif est active dans tes logs.
Du coup je me demande si c'est grace à la nouvelle procedure, ou une combinaison procedure et code.

Comme je sais que certains volets recents avaient deja pu etre inclus par le passé, j'ai bien peur que Profalux ai sorti plusieurs versions de leur nouveau FW. Reste à trouver ce qui fonctionne dans tous les cas pour clore le sujet.
Mais ca avance.

**Comment by fichncheaps** [comment]
Hello
Je pense que c'est surtout la procédure car un de mes volets j'avais réussi
à l'intégrer dans ABeille avant et après avec tous les tests que j'ai fait
il ne voulait plus. Avec la nouvelle procédure ca a remarché du premier
coup.
Après peut être que ton code a aussi aidé.
Par contre, chose bizarre, avec cette procédure j'ai du rerégler les fins
de courses

**Comment by Seby9576** [comment]
Des lors ou tu reset tu dois refaire les fin de course, c'est pour ça que dans la procédure de base tu dois faire 2 aller retour

**Comment by SimonChatillon** [comment]
Quel enfer cette procédure de reset aux fils, j'ai un des volets qui ne veut plus se reconnecter à sa télécommande... J'ai suivi pourtant la doc reset aux fils puis 5x R sur la commande, puis stop mais pas moyen de la ré-associer au volet 😢

**Comment by Seby9576** [comment]
Pour réaffecter la télécommande ce n'est pas cette procédure

**Comment by tcharp38** [comment]
@SimonChatillon 
De quand datent tes volets ?
Quelle procédure exacte suis tu ?

**Comment by SimonChatillon** [comment]
> Pour réaffecter la télécommande ce n'est pas cette procédure

Ah bon ? Pourtant j'ai fait exactement cette même procédure sur un autre volet qui n'était plus appairé à sa télécommande et ça a marché 🤷‍♂️. J'ai suivi cette aide au dépannage de profalux pro : https://www.profalux-pro.com/notice/mon-volet-ne-fonctionne-plus-avec-sa-telecommade-ndep005-2/?telecommande=4729&groupe=groupe-1
(j'ai la télécommande de gauche, la carré) Si tu connais une autre procédure je suis preneur.



> @SimonChatillon De quand datent tes volets ? Quelle procédure exacte suis tu ?

Ils sont tous récents, on me les a installé il y a 3 semaines. Le bout visible du moteur est vert et non orange comme sur la photo postée plus haut.

**Comment by tcharp38** [comment]
@SimonChatillon 
On est d'accord que le souci actuel n'a rien à voir avec Abeille. Tu as perdu le controle du volet par sa telecommande.
C'est bien ca ?

**Comment by SimonChatillon** [comment]
> 

Oui c'est bien ça, même si à terme j'aimerais bien reprendre votre méthode avec zigate et abeille pour essayer de domotiser mes volets avec Alexa car cela semble être le seul moyen d'y parvenir.

**Comment by SimonChatillon** [comment]
J'ai finalement enfin réussi à le reconnecter avec l'aide du support profalux pro au téléphone. Pour info voilà la procédure très précise à respecter si cela peut aider quelqu'un : 
- Appuyer 5 fois sur R sur la télécommande
- Brancher le fil noir à la phase
- Le volet fait 6 aller retours puis s'arrête
- Après quelques secondes, le volet fait à nouveau 2 ou 3 aller retours puis s'arrête
- Après quelques secondes le volet rebouge à nouveau, débrancher immédiatement le fil noir (apparemment le timing est important pour que cela fonctionne, il faut l'enlever dès que cela rebouge)
- Ensuite le volet va se remettre à faire des allers retours, appuyer sur la touche stop de la télécommande. Celle ci clignote normalement en bleu puis en vert signifiant que le volet est appairé.

**Comment by tcharp38** [comment]
Ok merci pour ce retour qui servira aux nouveaux utilisateurs avec volets > sep 2021.
Je me doutais que qqch était trop rapide, alors ca doit aller dans ce sens.

**Comment by TiTiPhoto** [comment]
Simon c'est la procedure de reinit classique, mais si tu avais ton volet dans le réseau zigate, ca te le sort aussi... Le problème reste chez moi sur un volet recalcitrant ou j'ai au choix le volet intégré ou la télécommande mais pas les deux. et pour ma part j'ai un mix vieille telco et nouveau volet.

**Comment by TiTiPhoto** [comment]
Les deux sont parfaitement reconnu, mais le lien télécommande volet ne se fait pas. Et si je coupe et realimente le volet il bouge en attente de télécommande, stop sur la télécommande, le lien se refait mais les action depuis Jeedom vers le volet ne font plus rien

**Comment by tcharp38** [comment]
@TiTiPhoto 
Tu as des soucis encore ?

**Comment by tcharp38** [comment]
Je ferme cet antique sujet.
A réouvrir si soucis.
