### ISSUE TITLE
211126-BETA-2 : zigatewifi passe en timeout

### ISSUE THREAD

**Issue by jeancheminade** [KiwiHC16/Abeille#2206]
Bonjour,

la version 21126-BETA-2 m'a permis d'activer ma zigatewifi et de joindre tous mes capteurs par contre depuis qu'elle est passée en timeout je n'arrive plus à remonter la zigate dans Jeedom.

La Zigate a été redémarrer et son interface d'admin est joignable.

le redémarrage du demon ne change pas l'état des connexion.

Cordialement,

Jean CHEMINADE

[zigatedatas.txt](https://github.com/KiwiHC16/Abeille/files/7620375/zigatedatas.txt)
[AbeilleSocat1.log](https://github.com/KiwiHC16/Abeille/files/7620376/AbeilleSocat1.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/7620377/AbeilleSerialRead1.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7620378/AbeilleParser.log)
[AbeillePHP.log](https://github.com/KiwiHC16/Abeille/files/7620379/AbeillePHP.log)
[AbeilleMonitor.log](https://github.com/KiwiHC16/Abeille/files/7620380/AbeilleMonitor.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/7620381/AbeilleConfig.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7620382/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7620383/Abeille.log)

**Comment by tcharp38** [comment]
Je ne comprends pas ce qui se passe dans ton cas. Ca doit pas etre general car peu de personnes ont remonté un souci Zigate Wifi.
Et manque de pot je ne peux pas tester. Je n'en ai pas.

Bref, pour info le chemin est zigateWifi > socat > serialRead > parser.
On voir bien que Socat tourne (démarré 13h56)
Serial read est en attente aussi depuis 13h57
mais rien ne passe, comme si rien ne venait de l'adresse 192.168.1.8:9999
C 'est bien l'adresse de ta zigate Wifi ?

Est ce que tu sais ou pourrais confirmer qu elle est bien fonctionnelle ? https://zigate.fr/documentation/tester-le-module-wifi/

**Comment by tcharp38** [comment]
@jeancheminade 
Peux tu essayer avec ce fichier ?
[AbeilleSerialRead.zip](https://github.com/KiwiHC16/Abeille/files/7626148/AbeilleSerialRead.zip)
A decompresser dans core/php puis redemarrer Abeille.

Pour ta gouverne il est inutile d'envoyer tous les logs separement. Tu passes par la page support/telecharger tout, et tu as un package que tu peux glisser directement ici. + simple + complet.

**Comment by jeancheminade** [comment]
Bonjour

J'ai effectué le test de ma zigatewifi avec packetsender et il semble quelle ne soit pas en forme. par moment elle répond correctement à d'autre elle reste en état Connected and idle.

j'ai aussi chargé le fichier AbeilleSerialRead.php qui tu m'as mis à disposition mais cela ne change rien (ce qui ne me surprend pas vu le résultat précédent).

j'ai commandé une zigate-ethernet pour remplacer mon module défaillant. je te tiendrais au courant du résultat avec ce nouveau module.

**Comment by tcharp38** [comment]
Ok. Pour info il y a un autre sujet en cours sur la ZigateWifi mais different du tient.
https://github.com/KiwiHC16/Abeille/issues/2204#

**Comment by Krankhore** [comment]
Bonjour, @jeancheminade 
à quel type de wifi est connecté ta zigate ?

Je m'explique : j'ai deux zigates wifi , la première est connecté à deux routeur asus wifi6 en mesh et fonctionne très bien.
La deuxième avait un comportement aléatoire et son interface était très lente à répondre. Je l'ai connecté au wifi de ma livebox (qui n'est donc pas en mesh, ni wifi6) et depuis plus aucun problème.

Donc à voir si tu peux connecter la tienne à un autre wifi.

**Comment by jeancheminade** [comment]
Ma zigatewifi est connecté en wifi 4 sur le canal 4 à une borne qui fait du wifi 4 et 5.

je viens de faire le test de la basculer sur une autre borne qui ne fait que du wifi 4 via un SSID dédié et j'obtiens le même résultat.

**Comment by Krankhore** [comment]
Dommage, ça valait le coup d'essayer.
J'espère qu'avec ton nouveau module ce sera bon.

**Comment by tcharp38** [comment]
@jeancheminade 
Ce sujet a t'il toujours besoin d'etre ouvert ?

**Comment by jeancheminade** [comment]
Bonsoir,

je tourne maintenant depuis quelque jour sur une zigate ethernet sans aucun souci.

Il semble que mon ancien matériel était bien en cause.

Du coup je clos ce sujet.

Merci pour l'aide.
