### ISSUE TITLE
Zbmini time out

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2210]
Bonjour,

J'ai cette actionneur qui est tombé en time out alors qu'il est câblé! Je pensais que cela arrivait seulement avec les éléments sur pile. Je pense qu'il est un peu trop éloigné de la zigate cependant après son inclusion abeille semblait indiquer une bon signal.

Question est il possible de le réveiller sans refaire une inclusion (pas très accessible) ? Merci

**Comment by tcharp38** [comment]
Si il n'envoie plus rien, soit il est HS soit la connexion est perturbée.
Dans les 2 cas on ne peut pas l'ateindre puisqu'on ne recoit rien. Il est peu probable qu'un seul sens du chemin fonctionne.

Il etait peut etre relayé par un routeur HS ? (ex: prise)

**Comment by Seby9576** [comment]
ok, merci,

Non rien mais je vais mettre une prise entre les deux. Par contre en prise j'ai aqara et sixwgh , est ce problématique que le routeur ne soit pas de la même marque ?

**Comment by tcharp38** [comment]
La problematique n'est pas la marque mais plutot si les equipements "se comprennent". Et ca tu ne le sais pas avant.
L'interoperabilite est une faiblesse Zigbee.
Bref faut essayer

**Comment by Seby9576** [comment]
J'ai fait une nouvelle inclusion avec cette fois une prise aqara entre les deux et malgré ca le module se connecte directement sur la zigate. Peut on faire quelque chose contre ca ?

Le module ZBMINI indique 99 en LQI si je me trompe pas c'est la qualité du reseau. Mais quand je fais on et et off le module réagit très vite par contre le retour d'état est très long. C'est comme ca que je l'ai perdu la dernière fois

**Comment by tcharp38** [comment]
On n'a aucun controle sur le "routage". Le reseau fait son choix tout seul.

Peux tu refaire ton test On et Off, noter l'heure, puis me filer le package de logs.

**Comment by Seby9576** [comment]
Bonjour,

Le problème venait du widget et non de la connexion. J'ai enlevé le widget et laissé normal et ca fonctionne sans problème et dès que je met le widget ca ne fonctionne plus. Je ne comprend pas trop pourquoi d'ailleurs.

**Comment by tcharp38** [comment]
?! Ca n'a rien à voir, sauf si le fameux "timeout" dont tu parles est une info du widget.
Que dit la page santé Abeille pour ce périph ?

**Comment by Seby9576** [comment]
Je sais mais le retour d'information ne fonctionne pas si je met le widget que j'ai fait. si je met rien de spécial j'ai aucun soucis

![image](https://user-images.githubusercontent.com/77990298/144632201-109e32c5-aa9c-4813-a896-add8e3979f90.png)

**Comment by tcharp38** [comment]
Bon j avoue que je ne sais pas trop comment faire sur ce sujet mais a priori il n'est pas specifique Abeille n'est ce pas ?

**Comment by Seby9576** [comment]
J'ai l'impression qu'il ne fonctionne plus de nouveau

**Comment by Seby9576** [comment]
Oui repassé en time out :-(. Meme la reinclusion ne donne rien

**Comment by tcharp38** [comment]
Idealement il faudrait que tu bascules sur la beta. Ca sera + simple.
C est possible ?

**Comment by Seby9576** [comment]
Oui si tu m'expliques comment faire

**Comment by Seby9576** [comment]
Pour contre je suis toujours en time out et impossible de le réactiver. Si je fais une reinclusion mes volets bouges mais pas de message et pour l'exclure rien ne se passe.

**Comment by tcharp38** [comment]
> Oui si tu m'expliques comment faire

Comme la stable, tu as le bouton "installer beta": https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-stable

Une fois que tu es sur la beta
- redemarre Abeille
- refait une inclusion de ton Zbmini
- file moi le package de logs

Attention, si il ne se signale pas du tout (pas de "Device announce" dans le parser), il y a vraiment un souci avec ce periph. Soit HS, soit hors portée, soit perturbé par autre chose comme une borne Wifi.

**Comment by Seby9576** [comment]
![image](https://user-images.githubusercontent.com/77990298/144840906-27562ef5-e0a4-49fb-814f-eb2a7900c846.png)
J'ai pas d'onglet BETA

**Comment by tcharp38** [comment]
Suis la doc STP. J'ai fait un chapitre pour ca

**Comment by Seby9576** [comment]
Je vais refaire une inclusion quand j'aurais 5 minutes car il est de nouveau en time Out

**Comment by Seby9576** [comment]
[AbeilleLogs-211209 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7687151/AbeilleLogs-211209.1.tar.gz)

**Comment by Seby9576** [comment]
Par contre j'ai remarqué que je n'arrivais à le mettre à jours qui si je le supprimais.

**Comment by tcharp38** [comment]
La il semble etre bien inclut.
Pas de souci visible particulier.
Je me montre ?

**Comment by Seby9576** [comment]
Dsl j'ai pas compris le "je me montre ? "

De plus inclus hier et déjà en time Out. Dans le réseau il apparaît bien

**Comment by tcharp38** [comment]
Ouah.. je sais pas pourquoi j'ai écrit ca :) Trop fatigué.

Côté timeout, je vois qu'il n y a rien qui empeche ca dans le modele.
Mais marqué timeout ca veut juste dire qu'on n'a recu aucune info de lui.
Peux tu toujours le contoller via On ou Off ?

**Comment by Seby9576** [comment]
Quand il est en time out impossible par contre il est plus en time out alors que j'ai rien fait à pars la maj

**Comment by Seby9576** [comment]
![image](https://user-images.githubusercontent.com/77990298/145617025-b30c6c78-cd34-418d-867d-f1da8b0c44f6.png)
est ce a cause de ca ? La prise du congélateur est séparé de 5m max

J'ai l'impression que si la zigate le perd il passe en time out et le signal est pas top. Puis être sur que la prise congélateur soit routeur ?

**Comment by tcharp38** [comment]
Ha il se peut que Zmini soit routé par ta prise. Et du coup si cette derniere est HS, tout ce qu'elle "route" l'est aussi.

Quand il est en timeout peux tu quand meme tenter On ou Off
me filer les logs et l'adresse du Zbmini ?

**Comment by Seby9576** [comment]
Salut,

Non comme dit plus haut si il est en time out je ne peux rien faire. J'attend de voir la prochaine fois qu'il en time out pour voir la table des liens.
Je te donnerais l'adresse et les logs quand il y aura de nouveau un problème ou tu souhaites les avoir quand même ?

**Comment by Seby9576** [comment]
Salut,

Pour l'instant toujours pas de time out . Par contre tu sais pourquoi si je met en widget j'ai une erreur de javascript stp ? Merci

**Comment by tcharp38** [comment]
Désolé je vous pas de quoi tu parles. Tu peux détailler ? Avec des snapshots

**Comment by Seby9576** [comment]
Salut,

De nouveau en Time out et commande impossible
![image](https://user-images.githubusercontent.com/77990298/146637810-aee3422c-dd28-4322-82ef-3fbf84bbfa47.png)

**Comment by Seby9576** [comment]
La VMC avait deux liens la ruche avec un LQI de 16 et la prise du congélateur à 54 de LQI
Maintenant ma VMC n'est plus dans le réseau et j'ai que ca en lien reseau
![image](https://user-images.githubusercontent.com/77990298/146637960-55bca603-32c8-400c-9497-7841a5adc32a.png)

**Comment by Seby9576** [comment]
Bon j'ai mit en route ma vmc via le bouton qui est sur le micro module et du coup je suis plus en time out

**Comment by tcharp38** [comment]
Ca c est une bonne piste.
Donc ton Zbminin n etait pas sorti du reseau. Il n'avait juste envoyé aucune info depuis un moment.
je crois qu'il manque qqch dans son modele pour forcer la verif qu'il est "vivant".

**Comment by tcharp38** [comment]
[01MINIZB.zip](https://github.com/KiwiHC16/Abeille/files/7739661/01MINIZB.zip)
A tester avec ce modele (refaire inclusion ou recharger JSON)

Par ailleurs si tu arrives à generer un discovery, je suis preneur.

**Comment by Seby9576** [comment]
Je comprends pour le retour d'info mais pourquoi je ne peux plus le changer d'État via jeedom ?
Je dois mettre le fichier ou stp? 
Et c'est quoi un discovery, je fais comment ? Merci

**Comment by tcharp38** [comment]
Je crois qu'il y a une coquille qq part qui empeche l envoi de la commande si le device est marqué "timeout". Ca doit etre ca qui bloque.

Discovery: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by Seby9576** [comment]
Cette il est encore en time out mais il n'est pas vu dans le réseau. J'ai été l'activer sur place mais toujours en time out.

**Comment by tcharp38** [comment]
Tu es sur la beta finalement ?
Si oui via la page support, infos clefs, donne moi les lignes
Equipements et Commandes

**Comment by Seby9576** [comment]
[AbeilleKeyInfos.log](https://github.com/KiwiHC16/Abeille/files/7742982/AbeilleKeyInfos.log)

**Comment by tcharp38** [comment]
J'ai l'impression que la config n'est pas à jour.
Tu as fait un recharger JSON ou REINITIALISER ?

**Comment by Seby9576** [comment]
Oui jeble suis trompé de répertoire ? J'ai mit comme l'autre

**Comment by tcharp38** [comment]
Je suis bete, la mise à jour semble etre correcte. Il est bien configuré pour etre interrogé toutes les 15mins.
Tu me files un log Abeille avec l'adresse de ton ZMINI ?

**Comment by Seby9576** [comment]
[AbeilleLogs-211220 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7747287/AbeilleLogs-211220.1.tar.gz)
Voici les logs car pour faire bref j'ai mit la zigate en mode inclusion pour réinclure la prise sixwgh et hop le Zbmini est revenu.

Pour info le zbmini était depuis hier clignotant comme si il était en mode inclusion. Du coup en mettant la zigate en inclusion il a du revenir dans le réseau. Pour info il était vers 19h30 .

Bon courage car je ne comprend pas ce qui se passe. Peux tu me dire si la prise congélateur fait bien relai ? Car sans elle la ruche à un signal faible ce qui peut expliquer les sorties de réseau. Merci

**Comment by tcharp38** [comment]
D apres ce que tu decris, oui on dirait que la prise fait relais pour la ZBmini. 

Pour l'histoire de timeout j'ai besoin d'un log Abeille qui couvre 1H par ex, avec l'adresse de ta ZbMini.

**Comment by Seby9576** [comment]
Ok, je fais ça ce soir, par contre depuis la modif le zbmini se Coupe tout seul au bout de 10 min

**Comment by Seby9576** [comment]
9C2B / 00124B0024C2DC8
[AbeilleLogs-211221.tar.gz](https://github.com/KiwiHC16/Abeille/files/7756926/AbeilleLogs-211221.tar.gz)
6

**Comment by Seby9576** [comment]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7756944/discovery.zip)
Le discovery maintenant qu'il est de nouveau dans mon réseau

**Comment by tcharp38** [comment]
Grace à ton log je vois qu'il est interrogé maintenant toutes les 15mins. Donc si il repond il tombe pas en timeout.
Peux tu le mettre en surveillance et me fournir AbeilleMonitor.log si jamais ca change d 'état ?

Merci pour le discovery.

**Comment by Seby9576** [comment]
Que veux tu dire par mettre en surveillance ?

**Comment by tcharp38** [comment]
Regarde le moniteur: https://kiwihc16.github.io/AbeilleDoc/Debug.html#le-moniteur

**Comment by Seby9576** [comment]
Depuis ta modif je n'ai plus de time out. Merci

**Comment by tcharp38** [comment]
Cool. Je clos le sujet du coup. Comme d'hab, à réouvrir si besoin.
