### ISSUE TITLE
[KiwiHC16] Retour etat Legrand 20AX a améliorer 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2213]
Sur changement, retour etat pas immédiat.
Sur historique, si valeur à 0 et pas de changement mais dernière moyenne à 10 alors graphe affiche 10 pendant toute la periode sans changement.

**Comment by Patag** [comment]
Je confirme le retour d'état pas immédiat lorsque commandé par Jeedom. En revanche, immédiat lorsqu'on commande le module manuellement ou par fil HP/HC.

**Comment by tcharp38** [comment]
Salut @Patag 
Tu pourrais me generer un discovery ?
voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

D'autre part peux tu apres avoir declenché ton action de Jeedom et une fois le retour d etat actualisé, me filer le package de logs (mode debug) => page support/telecharger tout + drag & drop ici.
Merci

**Comment by Patag** [comment]
Salut @tcharp38. Désolé pour mon temps de réaction, j'ai peu de temps libre en ce moment. Mais avant tout, merci pour ton implication sur ce projet.
Pour le moment je n'ai que le discovery sous la main. Le voici zippé 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7970830/discovery.zip)
Je reviens dès que j'ai les logs
Merci

**Comment by Patag** [comment]
Re
Passage de auto à on : pas de retour de l'état on mais puissance OK
![image](https://user-images.githubusercontent.com/48475891/151833338-2a574d71-3bfd-4573-9817-51233ad709c5.png)
Retour d'état à la bourre 
![image](https://user-images.githubusercontent.com/48475891/151834197-b683b45c-8947-4ab8-94b7-e4f92275797e.png)
Les logs correspondants
[AbeilleLogs-220131.tar.gz](https://github.com/KiwiHC16/Abeille/files/7972484/AbeilleLogs-220131.tar.gz)
Dis-moi si cela suffit. Ceci dit, pas d'urgence mais pour les tests, saches que j'ai mon chauffe-eau électrique (cumulus) branché sur le machin. Les tests seront donc limités.
Merci encore
A+

**Comment by tcharp38** [comment]
Quelle est son adresse courte ?
On dirait qu'il s'appelle "Chauff-eau" au niveau Jeedom mais je ne le retrouve pas dans la trace.

Merci pour le discovery.

Autre point: tu es sur quelle version du plugin ?

**Comment by Patag** [comment]
Salut
Voici
![Capture d’écran 2022-02-01 190955](https://user-images.githubusercontent.com/48475891/152026077-d9981311-9b0c-4a2f-bfa7-77f87f4ae97d.png)
et
![Capture d’écran 2022-02-01 193119](https://user-images.githubusercontent.com/48475891/152029062-0650964a-895f-4191-8e3e-36a8c77fbb3e.png)
Jeedom V4.1.28 stable
Si je me souviens bien, j'ai du mettre l'équipement en monitoring (AbeilleMonitor.log)
A+

**Comment by tcharp38** [comment]
Salut @Patag 
Toujours sur Abeille ?
Cet antique sujet merite toujours de rester ouvert ?
Merci

**Comment by tcharp38** [comment]
Je clos cet antique sujet.
A réouvrir si qqn est interessé.
