### ISSUE TITLE
Volume de CRC dans log très important

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#222]

**Comment by KiwiHC16** [comment]
Exposé du problème:
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=602100#p602100

**Comment by KiwiHC16** [comment]
@guims78, peux tu faire un stty -a -F /dev/ttyUSB0 pour vérifier la configuration du port. Sur quelle type de machine as tu Jeedom ?

Moi le résultat de la commande est:
```
stty -a -F /dev/ttyUSB0
speed 115200 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

**Comment by edgd1er** [comment]
Bjr @guims78, 
sur la raspbian stretch, mosquitto semble avoir des pb récurrents (ssl et websockets en particulier) . 
https://github.com/eclipse/mosquitto/issues/529. La solution proposée sur un forum est la compilation depuis les sources. As tu eu des problèmes pour l install ?
Le post ci dessous donne des indications avec des maj de mars 2018.
https://xperimentia.com/2015/08/20/installing-mosquitto-mqtt-broker-on-raspberry-pi-with-websockets/

As/peux tu fait/faire un test de mosquitto ? http://www.switchdoc.com/2016/02/tutorial-installing-and-testing-mosquitto-mqtt-on-raspberry-pi/ propose un test en fin d article avec les captures d écran.

**Comment by edgd1er** [comment]
Bish-boqh est un script pojr tester mosquitto: https://github.com/raphaelcohn/bish-bosh/blob/master/README.md

**Comment by KiwiHC16** [comment]
@edgd1er : Pourquoi mentionnes tu des infos sur MQTT alors qu'il me semble que le probleme tourne autour du CRC entre ZiGate->AbeilleSerialRead->AbeilleParser (not happy with CRC).

@guims78: Qu'elle est la situation ? As tu toujours le probleme ou tu as reussi a faire fonctionner le systeme ?

**Comment by edgd1er** [comment]
@KiwiHC16

Je pensais plus a un pb de plate-forme parcequ Abeille commence a etre utiliser par plusieurs personnes et que ce genre de pb serait remonté avant. Mais ce n etait qu une hypothèse. D ailleurs depuis le dernier commentaire ce n est pas mosquitto qui est en cause.

**Comment by KiwiHC16** [comment]
@guims78, sur qu'elle type de machine es tu ? Je vois un raspberry mais 1, 2 ou 3 ?

Ci dessous les differences entre la config de mon port (premiere ligne) et ta config (deuxième) ligne.

![capture d ecran 2018-04-01 a 09 59 36](https://user-images.githubusercontent.com/8549674/38171136-6cd531ac-3593-11e8-971e-432288dfcf4e.png)

Peux tu aligner les config avec la commande stty et voir si cela resoud le problème ?

**Comment by KiwiHC16** [comment]
La meme chose avec:
Ligne 1: Mon systeme de dev VM Debian 9
Ligne 2: ton systeme
Ligne 3: Ma Prod sur RPI3 debian 8

![capture d ecran 2018-04-01 a 10 11 38](https://user-images.githubusercontent.com/8549674/38171215-4cd1092e-3595-11e8-8c03-64cbd92ef9c4.png)

**Comment by guims78** [comment]
hello, mon systeme : raspi3 avec Debian Stretch.
Voici le resultat : 
pi@raspberrypi:~ $ stty
speed 9600 baud; line = 0;
eol = M-^?; eol2 = M-^?;
-brkint ixany iutf8
-echok

**Comment by guims78** [comment]
Est-ce que je dois faire d'autres manipulations ?

**Comment by KiwiHC16** [comment]
Sur quel port est la ZiGate ?
As tu d'autres equipements sur les ports USB du RPi3 ?
Si la ZiGate est sur ttyUSB0, peux tu donner le résultat de `stty -a -F /dev/ttyUSB0` ?

**Comment by guims78** [comment]
La zigate est sur ttyUSB0
Voici le resultat : 
```
pi@raspberrypi:~ $ stty -a -F /dev/ttyUSB0
speed 115200 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 0; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
-echoctl -echoke -flusho -extproc
```

J'ai aussi un Stick ZWAVE

**Comment by KiwiHC16** [comment]
As tu essayé d'aligner les parametres stty sur ta ZiGate ?
Quelle est la situation avec ce problème ?

**Comment by guims78** [comment]
Non, car je ne vois pas de quoi l'on parle.
Pour info, je pense que mes problème venez du fait que j'essayais en parallèle les 2 plugins Abeille et Zigate.
J'ai tout supprimé , vider les caches et réinstallé le plugin Zigate seul; Cela semble fonctionner.
Capteur et interrupteur détectés et fonctionnels.

**Comment by KiwiHC16** [comment]
C'est clair que tu ne peux pas avoir deux plugins sur la même ZiGate en même temps.
Donc le problème est résolu. Je clos le cas.
