### ISSUE TITLE
Gestion Zigate Wifi: relancer socat sans nouvelles de la zigate

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2220]
Voir sujet https://github.com/KiwiHC16/Abeille/issues/2204#

> Si tu peux redémarrer socat après 2 minutes sans news de la zigate ce sera encore mieux puisque cela évitera les 17 minutes de time-out.Et une relance à cette fréquence n'induire pas de surcharge cpu. Si tu fais cette évolution, il faudra aussi ajouter une notification jeedom lorsqu'il y à redémarrage parce que pas de réponse de la zigate afin que l'utilisateur soit averti et puisse vérifie ce qui s'est passé.

**Comment by mickadam29** [comment]
Je ne sais pas si ça a un lien. Ce matin j'ai redémarré le démon, débranché la zigate ethernet wifi (pas tout à fait le même équipement que ce post) et ce soir c'est de nouveau KO. J'avais vu qu'il manquait un démon. La carte Ethernet répond au ping.
Donc soit la Zigate (pizigate sur carte) soit les démons.

![image](https://user-images.githubusercontent.com/36518012/151862002-ead22960-852c-461f-b128-d2d7905597c7.png)

Un redémarrage du démon Abeille, rétablit la connexion. Donc démon seul en cause, et tous cas pas la Zigate Ethernet

![image](https://user-images.githubusercontent.com/36518012/151862842-0957432d-4628-483f-805f-854d58c0d39f.png)

**Comment by mickadam29** [comment]
De nouveau inaccessible après seulement qqs minutes (genre 10 minutes)

![image](https://user-images.githubusercontent.com/36518012/151864869-24b0a179-cecd-4d40-999b-148d7ac252bb.png)

![image](https://user-images.githubusercontent.com/36518012/151864680-bd6c4194-a1fb-463b-9b4d-e9d94daa05d4.png)

![image](https://user-images.githubusercontent.com/36518012/151864798-100ee041-c197-4cdf-90e8-f0e5686b3831.png)

Je ne saurai pas dire depuis quand j'ai ce phénomène. C'est mon environnement de recette. Espérons ne pas rencontrer cela sur la prod. Mais là c'est une Zigate+ USB.

**Comment by tcharp38** [comment]
@mickadam29 
Quand tu fais ce genre de manip, penses à attacher le package de logs. Sinon pas moyen de savoir reellement ou est est Abeille.

**Comment by mickadam29** [comment]
Ok je vais te faire ça

**Comment by tcharp38** [comment]
Dans la beta 230721-BETA-1
