### ISSUE TITLE
Zigate sur un autre port déjà utilisé après coupure secteur

### ISSUE THREAD

**Issue by Bennedheure** [KiwiHC16/Abeille#2222]
[https://community.jeedom.com/t/zigate-sur-un-autre-port-apres-coupure-secteur/22555/2](url)

Suite à un redémarrage de Jeedom ou après une coupure secteur, il arrive que le port de la Zigate mémorisé corresponde à un autre périphérique (ex: RFXcom) .

Le plugin RFXcom utilise ce code pour gérer automatiquement le problème du port USB qui peut changer sur le Raspberry Pi :
`$port = config::byKey('port', 'rfxcom');
if ($port != 'auto') {
	$port = jeedom::getUsbMapping($port);
}`

Sinon un mode automatique qui prendrait le 1er port USB avec un périphérique Zigate serait une solution, je n'ai pas vérifié si un ID est présent en interrogeant la Zigate USB pour rendre sa sélection fiable dans le cas où il y aurait plus d'1 Zigate.

**Comment by tcharp38** [comment]
Salut @Bennedheure 
Effectivement Abeille est sensible au port sur lequel il attend une zigate et du coup ne sais pas gerer les "switchs" de port qu'il peut y avoir au redemarrage. Peut etre un chantier pour + tard mais pas d'actualite pour l instant.

**Comment by JLucB-58** [comment]
Bonjour,
(indulgence, c'est mon 1er post GitHub!)
J'ai eu le même problème en voulant migrer de Zigate V1 vers V2.
Config : RPI 3B+ / Buster / Jeedom 4.1.27 / Abeille / Zigate USB et Zigate+ USB
Les 2 Zigate étaient branchées pour les besoins de la migration ( par Jeedom/Abeille "Migration d'equipement")

 Ma solution: faire un lien symbolique dynamique (ça, c'est pour le reboot) sur le bon device.
 
  cd /etc/udev/rules.d
  éditer ou créer 99-usb-serial.rules 
     y ajouter (dans mon exemple): 
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{product}=="ZiGate", ATTRS{manufacturer}=="Silicon Labs", SYMLINK+="ttyUSBZigateV1"
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{product}=="ZiGate", ATTRS{manufacturer}=="FTDI", SYMLINK+="ttyUSBZigateV2"

  vérifier que c'est bon par :
     sudo udevadm control --reload-rules && sudo udevadm trigger && ls -al /dev/ttyUSBZ*
        qui donne chez moi:
lrwxrwxrwx 1 root root 7 déc.  11 15:56 /dev/ttyUSBZigateV1 -> ttyUSB1
lrwxrwxrwx 1 root root 7 déc.  11 15:56 /dev/ttyUSBZigateV2 -> ttyUSB0
      
   Maintenant, dans la config Abeille, il suffit de choisir pour votre Zigate,  /dev/ttyUSBZigateV1 ou /dev/ttyUSBZigateV2
   
  
![Config2Zigate](https://user-images.githubusercontent.com/95973881/145683417-a03d7b30-765b-4717-8da7-1d1c52ababab.png)
 
Solution à vérifier chez vous!

**Comment by KiwiHC16** [comment]
Solution dans #2286

Ce n est pas un soucis Abeille dans le sens ou c est au niveau du Kernel que cela est géré.

Il n'est pas prévu de faire de modification de la conf du kernel depuis Abeille cela serait trop compliqué. On pourrait faire une doc pour expliquer comment faire mais dans l immédiat voir la solution dans #2286.
