### ISSUE TITLE
211202-BETA-1 équipements fantômes

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#2223]
J'ai lu dans la changelog :
**_Récupération équipements fantomes (toujours sur le réseau mais plus dans Jeedom)… revue en cours._**

Juste après install de cette beta, j'ai bien récupéré un sonoff SNZB-02 qui n'était pas dans la base de jeedom. J'ai attendu jusqu'au lendemain pour récupérer un deuxième équipement du même type mais rien.

J'ai donc fait un essai en supprimant une ampoule IKEA  (qui de toute façon n'avait pas de ficher json associé dans abeille). Je l'ai allumé mais rien ne s'est créé dans jeedom.
J'ai relancé le démon , éteint l'ampoule et là , l'équipement s'est bien créé dans jeedom.

5-6 minutes plus tard , j'ai fait la même manip avec une ampoule Philipps. Là aussi , il m'a fallu relancer le démon.

Donc apparemment, cette fonctionnalité de récupération des équipements fantômes ne fonctionne que quelques minutes après le démarrage des process  un peu comme l'inclusion sur une zigate qui est actif quelques minutes.

C'est bien comme cela que ça fonctionne ?

**Comment by tcharp38** [comment]
Non, cette fonctionalité
- reagit sur tout message recu alors que l'equipement n'est pas connu
- et tente de l'identifer au rythme ou il se reveille

Mais il y a un certain nombre de points que je dois encore revoir
- si tu supprimes un eq de Jeedom, il faut redemarrer pour qu'il soit marqué "inconnu"
- tous les messages reçus ne provoquent pas la recherche, pas encore

Autre point faible mais dependant du periph, il se reveille parfoit tellement peu de temps qu'il est impossible de lui envoyer une requete (equipement sur batterie).

Tu peux choisir un equipement, le supprimer et redemarrer Abeille.
La avec les logs on peut voir ce qui manque. 
Sinon attendre les prochaines evolutions. Ce sujet n'étant pas finalisé.

**Comment by Krankhore** [comment]
Ok, merci pour les infos
Je clos
