### ISSUE TITLE
Support Aqara Smart Wall Switch H1 EU (No Neutral, Double Rocker) (WS-EUK02), switch.l2aeu1

### ISSUE THREAD

**Issue by Snakelori** [KiwiHC16/Abeille#2224]
Bonjour,

J'essaye d'inclure un bouton mural Xiaomi "Aqara Interrupteur Mural Intelligent H1 EU " (avec le module Abeille) mais il me dit qu'il n'est pas reconnu.
Message lors de l'inclusion : "Nouvel équipement détecté mais non supporté. Création en cours avec la config par défaut (defaultUnknown)"

Je suis sous Jeedom version 4.2.5 sur Raspberry PI 4B. Version abeille 2021-11-22 01:00:16
Je joint en pj le fichier discovery.json (pas l'impression qu'il y ait beaucoup d'info)

Y a t-il moyen de l'inclure dans le module abeille pour qu'il soit reconnu ?

Merci pour votre aide :)
Bonne soirée !
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/7654594/discovery.json.txt)

**Comment by tcharp38** [comment]
[switch.l2aeu1.zip](https://github.com/KiwiHC16/Abeille/files/7654703/switch.l2aeu1.zip)

A tester.
Decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion

Il me faut une image PNG sans fond pour mettre en icone.

**Comment by Snakelori** [comment]
Super, ça fonctionne !
Merci beaucoup pour votre retour rapide.
Je joint l'image png sans fond mais la qualité n'est pas top :(

Merci beaucoup �
![xiaomi-aqara-smart-wall-switch-double-h1](https://user-images.githubusercontent.com/63954776/144726617-ad0757ed-070c-48b0-b5e4-65887c0dda3e.png)
�

**Comment by tcharp38** [comment]
Ok je prends. Sera dispo dans la prochaine beta.

Tout fonctionne sans soucis ? On peut clore ?

**Comment by Snakelori** [comment]
Oui c'est bon pas de soucis identifié👍 
Le ticket peut être clos.
Bonne journée !

**Comment by tcharp38** [comment]
Merci
A reouvrir si besoin.
