### ISSUE TITLE
Inclusion XIAOMI AQARA - Micromodule ON/OFF Zigbee 3.0 2500W avec neutre - (SSM-U01)

### ISSUE THREAD

**Issue by tibidi** [KiwiHC16/Abeille#2227]
Je partage ici les travaux que j'ai faits pour inclure ce module que je viens d'acheter. Je n'ai pas réussi à le faire fonctionner avec le plugin officiel zigbee. Voir: https://community.jeedom.com/t/switch-aqara-ssm-u01-cluster-not-found/67658/2

Il s'agit juste d'une copie de la configuration du module sans neutre de la même marque à partir du répertoire `switch.l0agl1` dans `devices_local/switch.n0agl1`. J'ai simplement remplacé les occurrences `l0agl1` par `n0agl1` dans les nouveaux fichiers. Cela me permet d'avoir le fonctionnement minimal à savoir les commandes status/on/off.

Au passage bravo pour ce plugin open source et très extensible.
[switch.n0agl1.zip](https://github.com/KiwiHC16/Abeille/files/7656042/switch.n0agl1.zip)

**Comment by tcharp38** [comment]
@tibidi 
Merci pour ce modele.
Rien à redire. Il semble couvrir ce que sait faire le device.
J'allais utiliser l'icone SSM-U02 mais il y a 1 un plot de +. Donc soit tu trouves un PNG sans fond pour ce modele, soit on met le meme que le U02. La diff est quasi invisible.

Sera dans la prochaine beta.

**Comment by tibidi** [comment]
Pour le PNG peut être le SSM-U02 suffit dans un 1er temps. Je suis nul en recherche/manipulation d'images.

**Comment by tcharp38** [comment]
Ok on fait comme ca.

**Comment by tibidi** [comment]
J'ai fait une image à partir du modèle sans neutre. Cela a le mérite de le différencier du module avec neutre.

![image](https://user-images.githubusercontent.com/27189952/144809614-30999677-8f01-48d9-aa29-39212cbc257b.png)

![node_XiaomiAqara-SSM-U02](https://user-images.githubusercontent.com/27189952/144809365-13b14584-4266-4cae-a4dd-29a7529e8a6e.png)

**Comment by tibidi** [comment]
Petite question au passage. À ton moyen par extension d'ajouter un élément dans cette liste en relation avec le nom que l'on met dans le fichier `switch.n0agl1.json` ?
![image](https://user-images.githubusercontent.com/27189952/144810282-5a2ee12c-6c66-4d90-a5c4-0b0b805b23de.png)

Car si on modifie l'équipement après l'inclusion on perd l'icône mentionnée dans le fichier `switch.n0agl1.json`

**Comment by tcharp38** [comment]
Effectivement si un utilisateur choisi une autre icone, elle est conservée.
Cette liste est mal foutue car le nom qui apparait est celui du modele dans lequel l'icone est utilisée et non pas le nom de l'icone.
Du coup effectivement tu ne vois pas tout.
Je pensais changer ca mais au final les noms qui vont apparaitre seront moins parlants.

**Comment by tibidi** [comment]
Voici ce que j'ai fait pour voir mon icône. Cela n'est pas propre car l'api n'est pas orthogonal et peut générer des effets de bord mais peut donner des pistes d'implémentation. 

- https://github.com/tibidi/Abeille/commit/9b77a1c5051983f24fafcca024cb0f7ee8c04df0

![image](https://user-images.githubusercontent.com/27189952/144838244-c7dcff3c-399c-4962-bb94-dbdd5f303d06.png)

**Comment by tibidi** [comment]
Oops typo: https://github.com/tibidi/Abeille/commit/9c45a12968abdc463e4be2c2ac911b8a3ab7437a

En tout cas je le redis super travail 😄

**Comment by tibidi** [comment]
J'ai regardé de plus près le module avec neutre ce matin avec l'assistant d'autodécouverte. Pour aller au bout afin d'éviter des `undefined types` j'ai modifié un peu le code (sans trop comprendre ce que j'ai fait). Voir https://github.com/tibidi/Abeille/commit/cbae963b67d1b79a59b4861624ba428a61f4e91b.

Voici le discovery.json [discovery.zip](https://github.com/KiwiHC16/Abeille/files/7667861/discovery.zip).

Ce module semble avoir en plus les commandes conso/puissance.

@tcharp38  Question: Quand je vois ceci 
![image](https://user-images.githubusercontent.com/27189952/145020993-8e317f7d-dc2c-47c2-8da8-f473211b39e3.png)
Existe-t-il un lien avec la commande `puissance.json` ou je vois `"logicalId": "000C-02-0055"`?

J'ai ajouté `"include11": "puissance"` dans le json de mon module et la valeur retournée est tjs 0.


Pour info voici la log du mes FIXME:

![image](https://user-images.githubusercontent.com/27189952/145022285-50921be7-0eb6-4fcb-bd26-c919194b3e70.png)

**Comment by tibidi** [comment]
Je pense avoir compris le lien entre les commandes et le JSON du module. Cependant, le module rend toujours 0 pour la puissance. À première vue les infos de consommation/puissance ne sont pas accessibles. Voir aussi: https://www.zigbee2mqtt.io/devices/SSM-U01.html

Conclusion ->  Il faut laisser en l'état (ou juste MAJ le discovery.json du précédent commentaire).

**Comment by tcharp38** [comment]
@tibidi 
J'ai mergé ton update de l'assistant.

Je n'ai pas pris l'autre pour autant car pas sur des effets de bord encore.

Cote cluster 000C c'est nouveau pour moi. C'est le cluster "analog input". Donc pas ca peut etre n'importe quoi.
![image](https://user-images.githubusercontent.com/35221038/145087562-0cdd5e1e-9887-4469-aa8e-41098dbd1cae.png)
Mais pas de detail sur ce cluster dans la spec actuelle. Bref je sais pas quoi en faire.
Il faut comprendre comment le device utilise ce cluster.

Ton discovery est beaucoup plus complet mais je comprends pas pourquoi cette fois il y a 5 "end point" alors qu'il n'y en avait que 2 a ta premiere livraison. Une idée ? C'est comme si ce periph avait un autre firmware.

Bref, tu me resumes ou on en est ? Il manque qqch ou on peut clore le sujet ?
D'ailleurs si tu peux utiliser la beta je suis preneur.

Tu peux me filer un package de logs avec l'adresse de ton périph ? Je veux voir ce 000C qui remonte. Merci

**Comment by tibidi** [comment]
Pour résumer voici l'historique:

1. J'ai d'abord pris la config du module `switch.l0agl1` (sans neutre) que j'ai recopié en `switch.n0agl1` (avec neutre) en changeant juste les noms. D'où mon premier `discovery.json` livré.
2. J'ai pris le temps de lire la documentation de ton plugin et découvert l'assistant. J'ai donc appliqué l'assistant sur le module avec neutre `switch.n0agl1` (sujet de ce thread) pour avoir le vrai `discovery.json` de ce module. J'ai dû faire quelques modifications de code pour avoir un résultat. **Donc le `discovery.json` à mettre dans ta config est le dernier livré avec les 5 "end point".**

Pour fermer le sujet il faudrait juste prendre le dernier `discovery.json`.

Pour la log dis-moi ce que tu veux exactement.

**Comment by tcharp38** [comment]
Ok je comprends mieux. Je n'ai pas fait attention que le premier discovery n'était pas du meme device.

Pour le retour 000C à moins d'avoir une nouvelle piste expliquant pourquoi il ne remonte que 0, je suggere de clore ce sujet jusqu'a nouvelle info. Ca te va ?

**Comment by tibidi** [comment]
Oui cela me va parfaitement. En l'état, cela correspond à mes attentes.

**Comment by tibidi** [comment]
Pour info j'ai installé la béta et refait l'association tout est ok. Merci

**Comment by tcharp38** [comment]
Parfait. Merci.
