### ISSUE TITLE
Mise à jour 3.2 OPDM sans erase PDM

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2228]
Salut

Après une mise à jour d'une Zigate V1 en 3.2 OPDM la PDM n'est pas effacée.
Ni en appliquant un reset PDM dans la config. Tous les devices sont encore là après patch et reset PDM

![image](https://user-images.githubusercontent.com/36518012/144920386-f25f4e24-c9f8-45ea-93b5-dec67a04c662.png)

**Comment by mickadam29** [comment]
![image](https://user-images.githubusercontent.com/36518012/144921516-ef0c308e-6668-4992-b567-901c0b727ac1.png)

**Comment by tcharp38** [comment]
Ha c est donc bien une regression Abeille.
Je viens de voir que ca n'est pas la seule commande qui a disparu suite à un mergé foiré :(

**Comment by ghost** [comment]
Je confirme avoir eu le même "souci". Est-ce que cela veut dire que la mise à jour du firmware n'est pas réellement faite ? Abeille m'indique bien que je suis en 3.20 pourtant. Et tout a continué de fonctionner normalement depuis.

**Comment by tcharp38** [comment]
Le bug en question empeche de faire un erase PDM, chose qu'on doit faire si on bascule d'une "legacy" vers "OPDM".
Si tu restes en legacy ou restes en OPDM, ca doit fonctionner normalement.

Correction normalement dans la 211207-BETA-1
Pas testé par contre.

**Comment by mickadam29** [comment]
**Je testerai avec la beta**. Finalement non, car mais 2 env sont sur la version stable. Merci

**Comment by tcharp38** [comment]
Je confirme la regression fixée sur la beta.

**Comment by tcharp38** [comment]
Je clos le sujet. A reouvrir si besoin
