### ISSUE TITLE
Mesure consommation pour le Micromodule ON/OFF Zigbee 3.0 2500W avec neutre - (SSM-U01)

### ISSUE THREAD

**Issue by tibidi** [KiwiHC16/Abeille#2234]
J'ouvre cette issue juste à titre d'investigation pour l'implémentation de la mesure de consommation instantanée de ce module en complément de l'implémentation de base dans cette issue #2227.

Si j'ajoute cette section dans [switch.n0agl1.json](https://github.com/KiwiHC16/Abeille/blob/master/core/config/devices/switch.n0agl1/switch.n0agl1.json)

```
            "Active-Power": {
                "params": "mult=1&div=10",
                "use": "zb-0B04-ActivePower",
                "isVisible": 1
            }
```

J'obtiens bien une valeur qui est en phase avec la consommation de mon ampoule (~6W).

![image](https://user-images.githubusercontent.com/27189952/145199039-d95dd1d8-1c3e-4dc8-8e02-8c81e3f3ed24.png)

Il reste cependant un problème je dois redémarrer le plugin Abeille pour que cette valeur soit mise à jour "et à première vue que via l'assistant de découverte". Scénario:

1. J'éteins la lampe
2. Je redémarre le plugin 
3. Je fais la découverte
4. j'ai ceci -> 0 W
   ![image](https://user-images.githubusercontent.com/27189952/145199631-b74b7499-e168-406f-9d2e-394a6e5eab20.png)
5. J'allume la lampe je rafraichis les attributs de cette ligne -> KO orange -> tjs 0 W
    ![image](https://user-images.githubusercontent.com/27189952/145200046-626c954b-d956-4816-aa4f-e1b9695ec8c8.png)

Si je refais 2-3 alors les lignes repassent en vert et j'ai bien mes 6 W
  ![image](https://user-images.githubusercontent.com/27189952/145200357-2b86aef1-5c43-4a94-afe7-47acc313f75f.png)

**Comment by tcharp38** [comment]
Effectivement c'est une fonctionalité qui manque.

Essaie avec ce modele
[switch.n0agl1.json.zip](https://github.com/KiwiHC16/Abeille/files/7676178/switch.n0agl1.json.zip)
refaire inclusion

**Comment by tibidi** [comment]
J'étais justement sur cette piste par comparaison au mode on/off. 

C'est parfait avec votre json 😄. La consommation instantanée change dans le Tableau de bord suivant que la lampe est allumée ou pas.

Encore merci. 

PS: 
- Quand j'aurai le temps (c'est ce qui me manque) je vais voir si je peux porter les modules de mes volets vers ce plugin.
  - https://www.se.com/fr/fr/product/S520567W/wiser-odace-interrupteur-voletroulant-4a-zigbee-blanc/

**Comment by tcharp38** [comment]
File moi un package de logs histoire de verifier qu'il n'y a pas trop de reporting STP

Pour l autre equipement, verifie qu'il ny  a pas de sujet deja existant. Mais de tete Legrand c'est merdique si j'ai bien vu sur les forums alors a voir. Pas de temps non plus :) Trop de choses en cours.

Mais tu peux aider en stressant la beta

**Comment by tibidi** [comment]
Voici les fichiers en niveau de log `default`.

[abeille.zip](https://github.com/KiwiHC16/Abeille/files/7676540/abeille.zip)

**Comment by tcharp38** [comment]
La trace est bien trop courte. Je ne vois aucun reporting. Mais du coup ca sous entend qu'il n'y en a pas trop.

A toi de dire si on clos le sujet ou pas encore.

**Comment by tibidi** [comment]
Oui tu peux ajouter ton json et fermer.

**Comment by tcharp38** [comment]
Voir 211208-BETA-2
