### ISSUE TITLE
Commande zbWriteAttribute: compatibilité avec attributs propriétaires

### ISSUE THREAD

**Issue by jbromain** [KiwiHC16/Abeille#2236]
Hello,

La commande générique zbWriteAttribute essaye, lors de son exécution, de reconnaitre le type d'attribut (attrType) en fonction de l'attribut, et ce à partir des spécifications.

C'est pour cette raison qu'il n'est la plupart du temps pas nécessaire de fournir attrType dans les paramètres des commandes Jeedom utilisant zbWriteAttribute.

Or, si l'attribut n'est pas reconnu (attribut propriétaire), le type n'est pas identifié ce qui conduit à l'erreur  suivante dans AbeilleCMD:
`command writeAttribute ERROR: Missing 'attrType'`

Il semble s'agir d'un oubli dans le fichier config/commands/zbWriteAttribute.json
Le fait d'ajouter la partie soulignée ci-dessous règle le problème chez moi (la commande s'exécute sans erreur):
![image](https://user-images.githubusercontent.com/72972682/145261679-ab0e48b1-ca8a-487e-b510-75e6166d2600.png)

Cette correction permet par exemple à cette commande de fonctionner (attribut non standard apparemment, commande issue du fichier json TS004F__TZ3000_xabckq1v):
![image](https://user-images.githubusercontent.com/72972682/145263000-ec00541c-be15-44d5-94fe-7f7c411f1e0e.png)

(Malheureusement ce n'est pas pour autant que j'arrive à faire fonctionner l'équipement, j'ai vu qu'il y a déjà plusieurs Issues à son sujet, je vais peut-être en rouvrir une... #2155)

(Je ferai une PR demain pour cette issue)

**Comment by tcharp38** [comment]
Oui ca n'est pas un oubli mais un manque.
C est dans le pipe mais je dois encore ajouter des choses dans le code pour eviter de rajouter forcement "attrVal" partout.

**Comment by jbromain** [comment]
Bien reçu, je corrige temporairement pour moi et je te laisse faire la solution propre alors :)
Merci

**Comment by tcharp38** [comment]
211210-BETA-1 a tester (dispo le 11/dec sur le market)

**Comment by tcharp38** [comment]
@jbromain 
Tu as testé la beta ?
Pour moi ce sujet clos mais je me trompe peut etre. Dis moi

**Comment by jbromain** [comment]
Salut @tcharp38 ,

Désolé pour ce retour tardif, ma domotique était HS.

J'ai toujours le problème sur les dernières beta.

Je vais essayer de l'expliquer mieux.

J'utilise la commande json zbWriteAttribute dans un fichier json (dans devices_local), avec des paramètres:
![image](https://user-images.githubusercontent.com/72972682/146951949-ec50549d-1a7f-493c-b2fb-b604fdb2ce6e.png)

Je m'attends à ce qu'au chargement de mon fichier JSON, la commande soit créées dans Jeedom avec mes paramètres.
Or, ce n'est pas le cas, le attrType est perdu:
![image](https://user-images.githubusercontent.com/72972682/146952327-18fdfd1c-ceb9-45ee-b3e1-c6f7e30fa5ac.png)

De ce fait, à l'exécution de cette commande (lors de l'inclusion, car c'est une commande nécessaire à la configuration initiale de l'équipement), j'obtiens cette erreur:
![image](https://user-images.githubusercontent.com/72972682/146952543-53f189db-5738-4337-8a6a-9e5d077046a2.png)
C'est parfaitement logique d'avoir cette erreur, car writeAttribute essaye de deviner intelligemment le type d'attribut (lorsqu'il ne le reçoit pas) en fonction des spec de l'attribut. Mais là c'est un attribut propriétaire, donc inconnu, donc ce code ne parvient pas à trouver le type (AbeilleCmdProcess.class):
![image](https://user-images.githubusercontent.com/72972682/146952875-cc28872f-0b87-429d-9d17-42ad9e8ef3f4.png)



Ce que j'ai du mal à comprendre en revanche, c'est qu'en parallèle je suis en train d'ajouter le "manufId" à la commande writeAttribute (actuellement forcé à 0000, je voudrais qu'on puisse lui mettre une valeur), et il est bien transmis (en le mettant dans mon JSON de device, il apparait bien dans les params de la commande jeedom, comme tu peux le voir sur les captures ci-dessus).

J'imagine que ton objectif est d'ajouter de manière automatique tous les paramètres "d'origine" (du json de l'équipement) à la commande réelle (issue du json de la commande); j'ai l'impression que le code fautif est dans AbeilleTools.class, par là:
![image](https://user-images.githubusercontent.com/72972682/146953630-a02ccad7-7c94-4f7c-b73f-b745aa51c9fe.png)

(Je ne comprend pas ce code: $cmd1, $cmd2, $newCmd... pas facile à lire)

La correction proposée dans le premier post (dans zbWriteAttribute.json) fonctionne toujours.

**Comment by tcharp38** [comment]
Ok, effectivement le manufId n'est pas supporté mais ca peut se completer.
Par contre que le type d'attribut disparaisse.. alors la pas bon.

J'ai trouvé une boulette. Un seul des 2 params optionnels (attrType & manufId) etait pris en compte.
Tu peux tester avec cette version. Je ferai une nouvelle beta à mon retour debut jan.
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/7758721/AbeilleTools.class.php.zip)

A noter que je n'ai rien fait pour le support de "manufId". Cette histoire n'est pas claire pour moi.

**Comment by jbromain** [comment]
C'est ok avec ton fichier, merci. 
(Je laisse l'issue ouverte pour l'instant, on fermera quand ce sera dispo en bêta)

(Concernant le manufId, il est forcé à 0000 actuellement dans AbeilleCmdProcess, j'ai fait une modification en local pour mes tests, c'est tout simple, je mettrai en commun quand ce sera ok chez moi ;))

**Comment by tcharp38** [comment]
Salut @jbromain 
Juste de retour de congés.
Peux tu basculer sur la  211230-BETA-1 (dispo demain) et signaler toute regression ?
Ma priorité est de la transformer en stable pour avancer les autres sujets et on reprend apres, le temps que je me remette dans le bain aussi.
Merci à toi

**Comment by jbromain** [comment]
Salut @tcharp38,

Après quelques jours d'utilisation de la dernière beta, je n'ai pas constaté de régression.
(notamment, la gestion des paramètres optionnels - cette issue - est ok à présent)

J'ai juste remarqué que le chemin des fichiers PHP utilisés est affiché à certains endroits, mais je suis en mode développeur, donc c'est sans doute pour ça (c'est très bien!):
![image](https://user-images.githubusercontent.com/72972682/148041759-add64d78-e80b-4cb8-b218-f97c017f5d5d.png)


Pour moi c'est stable.
Merci pour tout !

**Comment by tcharp38** [comment]
Salut @jbromain 
Oui les paths en questions sont visibibles qu'en mode dev. Juste pour info dans l'immediat.
Merci pour tes retours.
