### ISSUE TITLE
Pb abeillenetworkGraph

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2237]
Salut
J'ai l'impression qu'il y a un décalage dans la demande car quand je demande un relation avec un équipement il me montre un autre.

Exemple sur la photo ci dessous, j'ai demandé ma vmc et il me montre un télécommande de volet et en routeur en plus. Merci

![image](https://user-images.githubusercontent.com/77990298/145281438-3175f6bd-a000-46c8-9eab-97c6eadeaeb6.png)

**Comment by tcharp38** [comment]
@Seby9576 
Fermé car tu ne l'as plus ?

**Comment by Seby9576** [comment]
Pas vraiment utile et ca te donneras plus de boulot pour pas grand chose
