### ISSUE TITLE
ERROR: Unexpected command 'getEtat'/'getLevel'

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2239]
Pour mémoire. A comprendre.
Vu dans certains logs dont le sujet https://github.com/KiwiHC16/Abeille/issues/2185#

> [2021-12-09 19:07:22] Message from queueKeyCmdToCmd: CmdAbeille1/5A30/getEtat -> EP=01&clusterId=0006&attributeId=0000
> [2021-12-09 19:07:22]   L2 - procmsg({"topic":"CmdAbeille1\/5A30\/getEtat","payload":"EP=01&clusterId=0006&attributeId=0000","priority":4,"message":null})
> [2021-12-09 19:07:22]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
> [2021-12-09 19:07:22]     L1 - processCmd({"getEtat":"getEtat","name":"getEtat","priority":4,"dest":"Abeille1","EP":"01","clusterId":"0006","attributeId":"0000","addr":"5A30"})
> [2021-12-09 19:07:22]     getEtat cmd
> [2021-12-09 19:07:22]     ERROR: Unexpected command 'getEtat'
> 

ou

> [2021-12-09 19:07:26] Message from queueKeyCmdToCmd: CmdAbeille1/1FEF/getLevel -> EP=01&clusterId=0008&attributeId=0000
> [2021-12-09 19:07:26]   L2 - procmsg({"topic":"CmdAbeille1\/1FEF\/getLevel","payload":"EP=01&clusterId=0008&attributeId=0000","priority":4,"message":null})
> [2021-12-09 19:07:26]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
> [2021-12-09 19:07:26]     L1 - processCmd({"getLevel":"getLevel","name":"getLevel","priority":4,"dest":"Abeille1","EP":"01","clusterId":"0008","attributeId":"0000","addr":"1FEF"})
> [2021-12-09 19:07:26]     getLevel cmd
> [2021-12-09 19:07:26]     ERROR: Unexpected command 'getLevel'
>

5A30: Ikea Control Outlet
1FEF: TRADFRI Bulb E27 WW 806lm

**Comment by tcharp38** [comment]
@mlemarrec
Peux tu recharger le JSON de 5A30 par ex (page equipement/avancé => recharger)
et me filer le log Abeille dans la foulée ?

**Comment by mlemarrec** [comment]
Je viens de recharger la conf 5A30 Ikea Control Outlet.
Voici les logs:
[AbeilleLogs-211210.tar.gz](https://github.com/KiwiHC16/Abeille/files/7693702/AbeilleLogs-211210.tar.gz)

**Comment by tcharp38** [comment]
La commande "getEtat" disparait bien.
Tu saurais me dire de quand date la derniere inclusion de cet equipement ? Je me demande si ca n'est pas une vieille erreur qui traine à cause d'une commande supprimée depuis.

**Comment by mlemarrec** [comment]
Je dirai que ca fait bien 6 mois que je les ai inclus.

**Comment by tcharp38** [comment]
Comme je ne sais pas si cette erreur est recente ou vieille, je garde ce truc ouvert pour l'instant.
Normalement l'erreur ne doit plus apparaitre pour cet equipement que tu as rechargé.

**Comment by mlemarrec** [comment]
J'ai rechargé la conf de l'ensembles des devices :
5A30: Ikea Control Outlet
1FEF: TRADFRI Bulb E27 WW 806lm
1A2F: Ikea Control Outlet
F91D: Aqara H1 Smart Wall Switch

**Comment by tcharp38** [comment]
Je considere que ce souci vient d'une configuration trop vieille d'un équipement. Reinitialiser l'equipement avec son dernier modele JSON doit resoudre le pb.
Je clos mais a reouvrir si besoin.

**Comment by tcharp38** [comment]
Pb toujours d'actualité. Je le vois chez moi.

**Comment by tcharp38** [comment]
Pb normalement fixé dans la 220121-BETA-1
Je clos
