### ISSUE TITLE
Ajout support Module volet Roulant dOOwifi DWF-0205ZB-PN-2 

### ISSUE THREAD

**Issue by Pedrito33** [KiwiHC16/Abeille#2241]
Serait il possible d'intégrer ce module dOOwifi pour volets roulants. 

https://doowifi.fr/fr/zigbee/220-Module-volet-encastrable-DWF-0205ZB-PN-2-3760332970385.html

Je joins le .json

Merci pour votre support
[discovery_DWF-0205ZB-PN-2.json.zip](https://github.com/KiwiHC16/Abeille/files/7694343/discovery_DWF-0205ZB-PN-2.json.zip)
.

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices
[TS130F__TZ3000_xxgrunjb.zip](https://github.com/KiwiHC16/Abeille/files/7703017/TS130F__TZ3000_xxgrunjb.zip)

A decompresser dans core/config/commands
[commands.zip](https://github.com/KiwiHC16/Abeille/files/7703027/commands.zip)

puis redemarre Abeille
et refaire inclusion

J'ai besoin d'une image PNG sans fond pour mettre en icone. A toi la balle.

**Comment by Pedrito33** [comment]
![doowifi](https://user-images.githubusercontent.com/95932284/146005246-4f3944c4-94ac-40ea-a711-c955d29c7636.png)
Merci @tcharp38 pour ce retour.
ça fonctionne impec !

voici le png demandé.

**Comment by tcharp38** [comment]
Merci.
L'icone est mise à jour dans la beta de demain 211214-BETA-2
Si tu veux tester cette version, je suis preneur de tes retours.

**Comment by Pedrito33** [comment]
Merci
je suis pas sûr de savoir faire ça.
En attendant, j'ai un soucis. Je n'ai pas trouvé comment régler le temps de fonctionnement.
J'utilise ce module sur une VMC double vitesse et j'aurais besoin de maintenir la commande (Up ou Down) jusqu'à l'arrêt par la commande Stop. Je sais que c'est un module volet, mais bon! 
Pour l'instant, tout fonctionne, mais la commande n'est maintenue que quelques secondes (10,12 s).

Aurais tu une solution ? 
J'ai trouvé ce lien sur le forum, si ça peut aider : https://community.jeedom.com/t/zigbee-commande-volet-zigbee-dwf-0205zb-pn-non-reconnu/72936

Merci

**Comment by tcharp38** [comment]
Ce module etant dedié "volets", doit avoir un systeme de fin de courses
- soit par un temps apres calibrage si existe
- soit par detection de sur consommation

Peut etre que ta VMC a une sur conso au demarrage et le module interprete ca comme une butée.
Pour moi il n'est pas adapté à ton usage

**Comment by Pedrito33** [comment]
Tu as certainement raison, j'avais omis une ligne dans la doc 

> "_Le temps d'action est réglable de 10 secondes jusqu'à 2 minutes pour les grands volets_."

Donc ça ne répond pas à mon besoin, mais pour le fun, j'aimerais savoir comment faire ce réglage, je n'ai pas trouver dans les commandes comment m'y prendre. A prioiri il existe une notion de calibrage mais je ne sais pas comment l'activer.
Peux tu m'aider sur ce point là ?
Pour la détection de conso, il n'en n'est pas fait mention dans la doc, donc je pense qu'il n'y en a pas.

J'ai un module inter sans Neutre de Doowifi qui devrait convenir ( 1 vitesse VMC).

Merci pour ton aide

**Comment by tcharp38** [comment]
Je n'ai rien vu dans les specs Zigbee qui parle de ca sur le cluster "Window covering". Du coup je pense que ca reste un truc propriétaire malheureusement. Donc aucune idée pour l'instant.

**Comment by tcharp38** [comment]
Salut @Pedrito33 
Tres bonne année à toi.

Que fait on avec ce sujet ?

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si besoin
