### ISSUE TITLE
Support détecteur de fumée - Frient - SMSZB-120 (SMSZB-120, frientAS)

### ISSUE THREAD

**Issue by zoipod** [KiwiHC16/Abeille#2242]
Bonjour, 

Je fais suite à cette demande : https://community.jeedom.com/t/detecteur-de-fumee-frient/72238
Comme je l'ai dit avant, le souci c'est que je n'ai pas le discovery.json car l'équipement n'est pas ajouté dans Abeille.
(la zigate se met pourtant à clignoter rapidement, lorsque je tente l'association)

Je suis en mode debug, et j'ai activé les 5000 lignes de log dans la conf Jeedom.

Je les ai commandé ici : 
https://www.domadoo.fr/fr/peripheriques/5409-frient-detecteur-de-fumee-intelligent-zigbee-30-5713594002330.html

Mes logs abeilles : 
[AbeilleLogs-211210.tar.gz](https://github.com/KiwiHC16/Abeille/files/7695673/AbeilleLogs-211210.tar.gz)
(J'ai retenter une association le 10/12 à 22h52, en connectant l'appareil et en le passant en mode association, puis en passant la zigate en mode inclusion.)

Merci.

**Comment by tcharp38** [comment]
Salut @zoipod 
La bonne nouvelle c'est qu'on voit une annonce du device puis plus rien.

> [2021-12-10 22:52:01] Abeille1, Type=004d/Device announce, Addr=4BB6, ExtAddr=0015BC003100B9C6, MACCapa=00
> [2021-12-10 22:52:02] Abeille1, Type=8045/Active endpoints response, SQN=B7, Status=00, Addr=4BB6, EPCount=03, EPList=01/23/26
> [2021-12-10 22:52:02]   deviceUpdate('epList', '01/23/26'): status=identifying
> [2021-12-10 22:52:02]   Requesting manufacturer from EP 01
> [2021-12-10 22:52:02]   Requesting modelIdentifier from EP 01
> [2021-12-10 22:52:02]   Requesting location from EP 01
> 

Quel est la ref/modele de cet equipement ?
Il faut trouver si il est deja supporté ailleurs. Ca aide.

**Comment by zoipod** [comment]
Hello, 

Voici les information de l'appareil : 
Marque : Frient
Model : SMSZB-120
Code produit : 20209600
Zigbee 3.0 certified

Testé ici : https://www.domo-blog.fr/test-detecteur-fumee-zigbee-frient-domotique-jeedom-ha/
avec le dongle Conbee II et le plugin Deconz

**Comment by tcharp38** [comment]
Grace à la ref, j'ai une piste. C est un cas encore pas supporté par Abeille :(
Pour info/memo: ce device à 3 EP: 01, 23, & 26 mais le EP01 ne semble pas avoir de cluster donc pas de 0000 pour repondre à une requete d'identification.

Je dois modifier le mode d'identification, donc pour une prochaine beta mais peu de chances que ce soit pour cette année.

**Comment by tcharp38** [comment]
Salut @zoipod 
Si toujours interessé peux tu basculer sur la beta,
refaire une inclusion
et me filer le package de logs.

Abeille interroge maintenant tous les EP. Ca doit repondre au besoin de ce device.

**Comment by zoipod** [comment]
Hello @tcharp38 
Très bonne nouvelle !

Je viens de faire le test. Un équipement a été créé. Et deux alertes Jeedom sont apparu.
- ERREUR: Impossible de créer le répertoire 'devices_local/SMSZB-120_frientA/S'
- Nouvel équipement détecté mais non supporté. Création en cours avec la config par défaut (defaultUnknown). Rafraîchissez votre dashboard dans qq secondes.

Voici les logs.
[AbeilleLogs-220314.tar.gz](https://github.com/KiwiHC16/Abeille/files/8244790/AbeilleLogs-220314.tar.gz)
L'inclusion a été faite le 14/03 à 13:20:26

Merci.

**Comment by tcharp38** [comment]
Compris le pb. Je reviens vers toi des que je peux.

Peux tu me generer un discovery en attendant ? voir : https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

**Comment by zoipod** [comment]
Voici le discovery : [discovery.zip](https://github.com/KiwiHC16/Abeille/files/8246813/discovery.zip)

**Comment by tcharp38** [comment]
2 zip pour test

Un correctif du parser. Ecraser core/class/AbeilleParser.class.php
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8252581/AbeilleParser.class.php.zip)

et le nouveau modele pour core/config/devices
[SMSZB-120_frientAS.zip](https://github.com/KiwiHC16/Abeille/files/8252574/SMSZB-120_frientAS.zip)

Puis redemarrer Abeille
Refaire inclusion

Et me donner un status et le package de logs.
merci

**Comment by zoipod** [comment]
Hello @tcharp38 

Je viens de d'écraser le fichier php, et d'ajouter le dossier via le plugin Jeexplorer.
J'ai relancé le demon Abeille et refait une inclusion.

A 1er vu j'ai le même comportement.

Voici les logs. l'inclusion a été lancée à 16:15:41
[AbeilleLogs-220315.tar.gz](https://github.com/KiwiHC16/Abeille/files/8254817/AbeilleLogs-220315.tar.gz)

**Comment by tcharp38** [comment]
Le pb est toujours le meme
[2022-03-15 16:15:41]   ManufacturerName='frient A/S', trimmed='frientA/S'

Le '/' devrait etre filtré mais il ne l'est pas.
T es sur d avoir ecrasé le fichier du parser ?
Tu dois avoir la fonction suivante à la ligne 1151

> function cleanManufId($manufId)

**Comment by zoipod** [comment]
Oups désolé. J'ai du me planter dans la maj du fichier.
Je viens de recommencer, et plus d'erreur !

[AbeilleLogs-220315(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8255112/AbeilleLogs-220315.1.tar.gz)

**Comment by tcharp38** [comment]
Ha oui c est bien mieux. Le modele est reconnu.
La valeur de batterie remonte.

Maintenant il me capturer le status de l'alarme.
As tu moyen de declencher un test (comme si detection de fumée) et me filer le package de log avec l heure

**Comment by tcharp38** [comment]
Refaire test avec ce modele et declencher une alarme.
[SMSZB-120_frientAS.zip](https://github.com/KiwiHC16/Abeille/files/8255383/SMSZB-120_frientAS.zip)

J'ai aussi besoin d'une image PNG sans arriere plan pour mettre en icone.

**Comment by zoipod** [comment]
Je viens de faire trois tests : 
- 17h34 : j'ai appuyé sur le bouton test de l'appareil.
- 17h49 : la détection de fumé s'est déclenchée.
- 18h02 : Même test mais avec le nouveau fichier le nouveau modele que tu viens d'envoyer.

[AbeilleLogs-220315(2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8255604/AbeilleLogs-220315.2.tar.gz)

Pour l'image, celle ci devrait aller :
![frient_AS SMSZB-120](https://user-images.githubusercontent.com/14280231/158432761-7cadec2e-eab7-4757-b55f-0b36c01e8af5.png)

**Comment by tcharp38** [comment]
Le nouveau modele ne semble pas pris en compte.
Nouvelle inclusion necessaire ou faire "recharger" le modele via la page EQ/avancé.
Sur le dasboard tu fois avoir un "Status" qui change en mode test.

**Comment by zoipod** [comment]
En effet, je n'avais pas réinclus. C'est fait. Le statut est bien présent, et a bien changé quand il a sonné.
Voici les logs : [AbeilleLogs-220315(3).tar.gz](https://github.com/KiwiHC16/Abeille/files/8256247/AbeilleLogs-220315.3.tar.gz)
Test fait à 19h37

**Comment by tcharp38** [comment]
Du coup c est bon pour toi ?
Il manque qqch ?

**Comment by zoipod** [comment]
A vrai dire j'aurai souhaité pouvoir activer l'alarme sur demande.
Je sais que c'est possible avec ce modèle. Je l'ai lu ici : https://www.domo-blog.fr/test-detecteur-fumee-zigbee-frient-domotique-jeedom-ha/
Je ne vois pas de commande pour faire cela dans l’équipement qui a été créé sur Abeille.

Est ce que tu penses que ce serai possible de le gérer ?

**Comment by tcharp38** [comment]
Je n'avais pas envisagé cette possibilité mais il faut maintenant trouver comment controler la sirene.

J'ai peut etre une piste mais ca demande du dev. Ce genre de commande n'existe pas encore dans Abeille.
Tu devrai tester bien sur.

**Comment by zoipod** [comment]
Ok pas de souci. Merci en tout cas !

**Comment by tcharp38** [comment]
@zoipod 
Peux tu me donner un snapshot de l' affichage pour cet equipement ?
Pour la sirene, tu souhaites la declencher à distance (temps infini) donc  un bouton "Sirene On" + "Sirene OFF" c'est l'idée ?

Autre point: il y a une nouvelle beta dispo.
Une fois que tu as basculé dessus, refais une inclusion et test les nouveaux boutons.
Merci

**Comment by zoipod** [comment]
@tcharp38 
Hello,
Pour la sirène, mon besoin n'est pas tant de la déclencher à distance, mais plutôt de l'intégrer dans des scénarios.
En effet, je souhaiterai l'inclure dans mon alarme, et profiter de la puissance sonore de la sirène.
(Actuellement je n'ai que la passerelle Xiaomi qui sonne, et c'est un peu juste)
 
Mais ok pour ajouter deux boutons On et Off sur l'équipement. Ça pourrai permettre de tester l'appareil facilement.

Je viens de tester ces nouveaux boutons : 
- Le start semble fonctionner. La sirène s'est déclenchée
- Le stop ne semble pas fonctionner. La sirène ne se coupe pas
- Après avoir coupé la sirène manuellement avec le bouton physique de l'appareil. Elle s'est redéclanchée 2 min après, puis a nouveau 2 min après.. J'ai finalement retiré la pile.

Voici deux captures :
![image](https://user-images.githubusercontent.com/14280231/159242095-71dd7def-26ce-41c8-b2c6-05c7ffb8f1ee.png)
![image](https://user-images.githubusercontent.com/14280231/159242436-078df26a-4ad0-45a2-85df-44b8d6726da3.png)

Et voici les logs au cas ou. J'ai effectué le test des boutons start/stop à 11h34
[AbeilleLogs-220321.tar.gz](https://github.com/KiwiHC16/Abeille/files/8314779/AbeilleLogs-220321.tar.gz)

**Comment by tcharp38** [comment]
Salut. Donc j'ai mal compris ta requete.

Pour declencher qqch à partir de l'alarme tu as ce qu'il faut..: l'info "alarm 1".
Ca ne le fait pas ?

Quant au controle de l'alarm à distance, c est à la fois bien et pas bien.
Bien parce que tu arrives à demarrer l'alarme à distance, mais pas bien car tu dis qu'elle ne s'arrete pas et la je seche. 
J'ai suivi le standard pour mettre en place le code.
Si ca n'est pas ton besoin peut etre que je vais desactiver ca (alarm on & off) jusqu'a ce que le truc soit maitrisé.

**Comment by zoipod** [comment]
"Pour declencher qqch à partir de l'alarme tu as ce qu'il faut..: l'info "alarm 1"
=> Yes ça c'est parfait ! Mais c'est l'inverse que je souhaiterai faire. Déclencher la sirène du détecteur, à partir d'un événement externe.
ex : Déclencher la sirène lorsque ma porte d'entrée s'ouvre, et que l'alarme de mon domicile est activée.
C'est pour cela que j'ai besoin d'activer la sirène manuellement, et aussi de la couper :)

Je viens de tester a nouveau. Impossible d’arrêter la sirène en utilisant le bouton stop.
La seule chose à faire, et de retirer la pile.

**Comment by tcharp38** [comment]
Ok donc tu as bien besoin du "Alarm ON" et "Alarm OFF".

Reste que je ne sais pas pourquoi elle ne s'arrete pas.
Il faut creuser le support fait chez les autres solutions si on trouve le code.

**Comment by tcharp38** [comment]
J'ai trouvé un ptite boulette mais pas sur que ca explique. A voir dans la prochaine beta.
Il faudra recharcher le modele ou refaire une inclusion.

**Comment by zoipod** [comment]
Hello @tcharp38 
Suite mise à jour de la beta de Abeille. Le problème est résolu.
Le bouton stop fonctionne à présent. Même si un peu long a réagir, mais ça c'est pas grave.

Merci beaucoup pour ton aide ;)

**Comment by tcharp38** [comment]
Cool.

Du coup  on peut clore ce sujet ?

**Comment by zoipod** [comment]
Yes, je pense que oui :)

As tu une idée de quand ces évols vont passer sur master ?
(pour que je reswitch sur la version stable de Abeille)

**Comment by tcharp38** [comment]
Ok je clos.
Quant à la prochaine stable j'aimerais bien en faire une rapidement avant de pousser d'autres modifs.
Je peux pas dire pour l instant.
