### ISSUE TITLE
Discordance adresse courte / adresse courte à 0000 en cas de réannonce

### ISSUE THREAD

**Issue by jbromain** [KiwiHC16/Abeille#2243]
Bonjour,

Depuis quelques jours j'ai un module qui ne fonctionne plus correctement, il s'agit du module Orvibo multi fonctionnal relay (https://www.domadoo.fr/fr/peripheriques/5340-orvibo-module-commutateur-contact-sec-zigbee.html).

Il est installé depuis longtemps et je pense que ce problème fait suite aux mises à jour d'Abeille et/ou du firmware zigate (j'ai fait les deux le même jour).

Concrètement, ce module se réannonce sans cesse, et ce depuis toujours (cf issue #2132); ça ne posait pas de problème fonctionnel jusqu'à présent, on voyait simplement dans les logs "...s'est réannoncé, mise à jour en cours" ou quelque chose du genre. Je n'ai pas fait attention si son adresse courte changeait ou pas à chaque fois.

Depuis quelque jours, il fonctionne par intermittence. Je l'ai monitoré dans Abeille et il ressort que lorsqu'il se réannonce il se retrouve régulièrement avec l'adresse courte 0000 ou 0400. On voit cette adresse dans les logs. Mais dans Jeedom, l'adresse courte n'est pas modifiée, elle reste à la dernière valeur "qui semble normale".

Il n'y a que lorsque le module se réannonce et récupère une nouvelle adresse courte "normale" qu'il se remet à fonctionner. Parfois quelques heures, parfois quelques minutes.

Voici deux extraits du log de monitoring:

### Logs quand ça marche
(Malgré l'erreur à la fin, il est fonctionnel après cette série de logs)
`[2021-12-12 09:05:59] <= 004d/Device announce, Addr=22CE, ExtAddr=00124B0022CE363B, MACCapa=04
[2021-12-12 09:05:59] <= New short addr for 00124B0022CE363B: 22CE
[2021-12-12 09:06:00] <= 8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=01, DestEP=01, AddrMode=02, Addr=22CE, SQN=CB
[2021-12-12 09:06:00] <= 8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=01, DestEP=01, AddrMode=02, Addr=22CE, SQN=CD
[2021-12-12 09:06:00] <= 8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=01, DestEP=02, AddrMode=02, Addr=22CE, SQN=CE
[2021-12-12 09:06:00] <= 8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=01, DestEP=03, AddrMode=02, Addr=22CE, SQN=CF
[2021-12-12 09:06:06] <= 8011/APS data ACK, Status=A7, Addr=22CE, EP=01, ClustId=0006
[2021-12-12 09:06:06] <= 8011/APS data ACK, Status=A7, Addr=22CE, EP=01, ClustId=0006
[2021-12-12 09:06:06] <= 8011/APS data ACK, Status=A7, Addr=22CE, EP=01, ClustId=0006
[2021-12-12 09:06:06] <= 8011/APS data ACK, Status=A7, Addr=22CE, EP=01, ClustId=0006
[2021-12-12 09:06:10] <= 8701/Route discovery confirm, MACStatus=00 (ZPS_EVENT_NONE->), NwkStatus=D0 (ZPS_NWK_ENUM_ROUTE_DISCOVERY_FAILED->Attempt at route discovery has failed due to any reason except lack of table space), Addr=22CE`

### Logs quand ça ne marche pas
(Après cette série de logs, l'adresse courte dans Abeille reste à la dernière adresse cohérente, et l'équipement n'est plus joignable)
`[2021-12-12 09:19:17] <= 004d/Device announce, Addr=0000, ExtAddr=00124B0022CE363B, MACCapa=04
[2021-12-12 09:19:17] <= New short addr for 00124B0022CE363B: 0000`

Ces deux extraits se suivent; dans cet exemple l'équipement a fonctionné moins d'un quart d'heure.

Log complet sur quelques heures:
[AbeilleMonitor-ORVIBO Contact sec.log](https://github.com/KiwiHC16/Abeille/files/7698588/AbeilleMonitor-ORVIBO.Contact.sec.log)

Je n'exclus pas que le problème vienne d'une saturation de ma zigate (j'ai environ 40 équipements dessus, avec une version de firmware legacy); mais j'ai de nombreux routeurs donc en théorie ça ne devrait pas être le cas (j'ai lu qu'on pouvait théoriquement aller jusqu'à 60/70).

Une idée ?
Merci :)

**Comment by tcharp38** [comment]
Salut.

Un device announce avec adresse 0000 c'est IMPOSSIBLE. Ca pue cette histoire.
Tu as fais quoi comme upgrade FW ?
Tu etais en quoi et tu as basculé sur quoi ?

**Comment by jbromain** [comment]
Hello,

Je suis passé de 3.1a à 3.1e legacy.
J'ai une pizigate v1. 

Je me suis aperçu il y a quelques minutes que j'ai une erreur bizarre dans les logs. 

`Zigate mode has been properly changed.
[2021-12-12 21:54:40] Abeille1, Type=9999/Extended error, ExtStatus=87`

Ce qui dans la doc Zigate signifie:
0x87 There are no free entries in the extended address table. The extended address table is configured in the config editor.

Ça ne m'aide pas beaucoup mais toi peut-être. Une saturation de quelque chose ?

Après recomptage j'ai moins de 35 équipements. (J'ai sorti le module Orvibo pour l'instant)

Merci en tout cas :)

Peut-être une corruption du firmware de ma Zigate?

**Comment by tcharp38** [comment]
Normalement ca aurait du le faire.
Un des pbs de la zigate c'est que tout equipement qui etait enregistre sur le reseau et n'en sort pas proprement (devient HS, plus de piles...) occupe toujours un slot. Aucune solution pour "effacer" ces equipements morts. Du coup à force de faire des tests on peut se retrouver dans ce cas.

Quoi qu'il en soit, il a l'air de dire qu'une des tables est pleine ou corrompue.
J'ai bien peur que tu sois obligé de refaire un reappairage complet. Dans ce cas 
- efface la PDM via la page Ruche/avancé
- et bascule sur la version OPDM
Désolé pour ce retour navrant.

**Comment by jbromain** [comment]
Salut,

C'est rassurant que ce soit que chez moi ;)
Mais bizarre quand même car je n'ai aucun équipement "supprimé" de mon réseau. Certains ont été ré-inclus plusieurs fois, mais théoriquement sans changer d'IEEE.

Je me doutais un peu que j'allais devoir y passer... j'ai anticipé et commandé hier une Zigate+ USB. Je vais la faire cohabiter avec l'ancienne et migrer petit à petit les équipements sur le nouveau "réseau"...

Merci
