### ISSUE TITLE
Prise Ikea impossible a inclure

### ISSUE THREAD

**Issue by dams74** [KiwiHC16/Abeille#2244]
Salut
Je rencontre un soucis avec une prise Ikea. c'est une prise qui a quitté le réseau pour je en sais quelle raison.
Du coup je l'ai supprimé mais je ne parviens pas à l'inclure de nouveau.
ci joint mon log
merci de ton aide
Damien
Ziagate usb en 3.1D et abeille master
[AbeilleLogs-211213.tar.gz](https://github.com/KiwiHC16/Abeille/files/7701305/AbeilleLogs-211213.tar.gz)

**Comment by tcharp38** [comment]
Salut @dams74 
Je ne vois aucune annonce (004D/Device announce) dans tes logs.
Donc ta prise est trop loin/hors de portée ou elle ne s'est pas mise en mode appairage.

**Comment by jbromain** [comment]
J'ai eu beaucoup de mal à inclure les miennes également, elles doivent être à 20cm de la Zigate, et il faut plusieurs essais.

**Comment by tcharp38** [comment]
@jbromain 
Tente une inclusion et file moi le package de logs STP.

**Comment by jbromain** [comment]
Ma Zigate est en cacahuète, je ne touche plus à rien pour l'instant.

Pour moi il n'y a pas de bug Abeille concernant les prises Ikea, elles sont justes pénibles. Je referai un test dès réception de ma nouvelle Zigate :)

**Comment by tcharp38** [comment]
Ok. Effectivement je n'ai pas de soucis non plus chez moi.

**Comment by dams74** [comment]
> 

ça fait des mois qu'elle est à cette emplacement, il n'y a pas de raison qu'elle soit hors de porté.
Du jour au lendemain elle a arrêté de fonctionné.
Si ça se trouve elle est hs

Edit: effectivement elle est capricieuse... après moultes éssais j'ai pu enfin l'appairer de nouveau
Merci de votre aide

**Comment by tcharp38** [comment]
Salut @dams74 
Tres bonne année à toi.
Des news sur ce sujet ?

**Comment by dams74** [comment]
Salut
Très bonne année à toi aussi. 
Après un certain nombre d'essais, elle est retournée dans le réseau et fonctionne parfaitement. 
Merci

**Comment by tcharp38** [comment]
Super !. Je clos le sujet alors.
Mais à réouvrir si besoin.
