### ISSUE TITLE
Firmware ZiGate. Version 3.1e

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2247]
Salut, 

En faisant la MAJ de la dernière béta, j'ai eu une notif qui me disait d'installer la dernière version du firmware de la zigate.
C'est en cours de teste ou c'est déjà opérationnel ? 
Je préfère attendre d'être sur si jamais ^^

Merci

**Comment by tcharp38** [comment]
Le 3.1e est vieux maintenant mais oui je l'ai fixé comme le minimum pour un fonctionnement optimal d'Abeille.
La derniere version est la 3.21 donc oui tu peux passer en 3.1e legacy sans soucis.

**Comment by Jake309** [comment]
En effet, sur les news, le dernier message était celui la :
[https://community.jeedom.com/t/news-de-la-ruche-par-abeille-plugin-abeille/26524/73?u=jake309](url)
Donc j'ai jamais testé. Après, il se pourrait que ca me règle pas mal de petit bug que j'ai ^^

Je peux installer quelle version du coup ? la 3.21 est déjà prise en charge ?

**Comment by tcharp38** [comment]
Les news ne sont pas du tout à jour vu que je n'ai rien posté dessus.
J'utilise la 3.1e depuis un bail sans soucis et j'ai basculé en 3.20 depuis aussi qq temps. Rien à signaler sur 3 box.
Pas testé la 3.21 encore mais je l'ai mise dans le master.

**Comment by Jake309** [comment]
Ok, je vais tester la 3.21 alors =)
Je ferai ca dimanche fin de journée. 
On se tiendra au courant

**Comment by Seby9576** [comment]
Bonjour, J'ai beau chercher je ne trouve pas de procédure pour le mettre à jours cette zigate. j'avais déjà fait sur eedomus mais je ne trouve pas sur jeedom. Merci de votre aide

**Comment by tcharp38** [comment]
Quel type de Zigate as tu ?

**Comment by Seby9576** [comment]
En USB

**Comment by tcharp38** [comment]
Ok donc si v1 tu dois passer par un soft windows
- demonter la clef pour appuyer sur bouton en meme que tu l inseres
- utiliser le soft pour la programmer

Voir chez Zigate la: https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

**Comment by Jake309** [comment]
si tu as déjà des inclusions, penses à la sauvegarde :
[https://zigate.fr/documentation/sauvegardez-et-restaurez-votre-zigate/](url)

J'attaque la mise à jour !

**Comment by Jake309** [comment]
V3.21
Notification :
`2021-12-19 16:48:42 | Abeille | Mauvais port détecté pour zigate 1. Tous ses messages sont ignorés par mesure de sécurité. Assurez vous que les zigates restent sur le meme port, même après reboot. | Abeille/Demon`

Utilise l'heure de la notif si jamais ca t'intéresse pour les log. J'étais pas en debug, desole .... 
Avant ca, j'avais restauré mon backup, mais ca ne marche pas si c'est pas la meme version de firmware.
[AbeilleLogs-211219.tar.gz](https://github.com/KiwiHC16/Abeille/files/7741098/AbeilleLogs-211219.tar.gz)

**Comment by Jake309** [comment]
L'inclusion ne fonctionne pas.
C'est bien le legacy qu'il faut prendre ?

**Comment by tcharp38** [comment]
@Jake309 
2 choses à ma connaissance peuvent declencher ce message
 - le port de la zigate a changé
 - l'adresse IEEE de la zigate à changé pendant l update FW
 
Quel est ton cas ?

Et pour répondre à ta question, oui legacy si tu ne veux pas refaire tous les appairages.

**Comment by Jake309** [comment]
Je suis d'humeur joueuse, je prends l'OPDM :) c'est intéressant à l'usage.

Ok, bonne question, comment je peux savoir ?
Et comment on peut régler ca ?

**Comment by tcharp38** [comment]
Je soupconne que pour avoir le message "Zigate sur le mauvais port" tu as effacé l'adresse MAC de la zigate;
Ca c'est important: garder "reuse MAC"
![image](https://user-images.githubusercontent.com/35221038/146684352-c0479462-cff1-45ea-b442-1690527724f5.png)

Si tu passes en OPDM, tu dois TOUT effacer comme suit
![image](https://user-images.githubusercontent.com/35221038/146684385-7f0affd8-6152-4224-b79e-bccd58a1935f.png)

puis refaire l'appairage de tous tes equipements, sans les effacer de Jeedom.

**Comment by Jake309** [comment]
Alors, j'ai exactement fait les 2 :/
C'est encore plus étrange.
Comment régler ca alors ?

**Comment by Jake309** [comment]
![image](https://user-images.githubusercontent.com/49479084/146685056-698cf383-bd59-40d5-b312-91fa97c05385.png)

J'ai la même adresse que sur mon backup, donc je ne pense qu'elle ait changé.
Le port, pour moi il a toujours était ttyUSB0

**Comment by tcharp38** [comment]
Les logs que tu as envoyé correspondent sans doute à un cas qui fonctionne.
Ca explique que je n'y trouve aucun pb et du coup aucune piste.
Peut etre que ca vient de la 3.21 avec laquelle je n'ai pas encore joué.
A voir si j'ai le temps avant de partir.

Bon je suis en 3.21 sur ma PiZigate (v1). Pas de soucis jusque la.

**Comment by Jake309** [comment]
J'ai essayé la 3.21 OPDM, la led clignote mais j'arrive pas à inclure, la 3.20 OPDM ca ne clignote pas.
Je teste une 3.20 legacy la
Zigate USB v1

**Comment by Jake309** [comment]
`[2021-12-19 20:53:12] Trame en dehors marqueurs: "0219AD021002100210240210021002100210021003"`
Dans serialread1

J'ai souvent cette erreur, je sais pas ce que signifie la trame en dehors marqueurs

**Comment by Jake309** [comment]
je n'ai plus de PB de port, grace à cce que j'ai vue sur un autre issue [https://github.com/KiwiHC16/Abeille/issues/2222](url)
maintenant c'est vraiment quand je veux entrer en inclusion

**Comment by Jake309** [comment]
20h58, passage des log en mode debug, relance du démon, passage en inclusion (la led clignote) j'essaie d'inclure 2 prises, rien.
En 3.20 legacy

[AbeilleLogs-211219.tar.gz](https://github.com/KiwiHC16/Abeille/files/7741505/AbeilleLogs-211219.tar.gz)

**Comment by Jake309** [comment]
Arret de jeedom, v3.21 OPDM, relance, j'ai ce message:
`Mauvais port détecté pour zigate 1. Tous ses messages sont ignorés par mesure de sécurité. Assurez vous que les zigates restent sur le meme port, même après reboot.`
dans la conf, je teste la zigate et sauvegarde, je relance une inclusion, toujours rien.

[AbeilleLogs-211219.tar.gz](https://github.com/KiwiHC16/Abeille/files/7741517/AbeilleLogs-211219.tar.gz)

**Comment by Jake309** [comment]
Je penses que la MAJ l'a cramé. 
https://github.com/fairecasoimeme/ZiGate/issues/390
Jai ouvert un ticket chez nos collègues ou jai détaillé. Mais à mon avis, jai du faire quelque chose de pas bien. 

Si c'est le cas, madame va pas apprécier les congés de fêtes de fin d'année en attendant une nouvelle zigate. Ca sera une v2 pour la peine.

**Comment by tcharp38** [comment]
Perso je vois pas comment tu peux "cramer" la zigate en faisant une mise à jour. Au pire, elle est corrompue et repartir de ta sauvegarde devrait te remettre dans l etat initial.

**Comment by Jake309** [comment]
Je suis daccord avec toi. Et pourtant, ça ne donne rien. 
Jai même tenté de revenir en 3.1d ou 3.1e :/

**Comment by tcharp38** [comment]
Quand tu dis ca donne rien, tu as un package de logs en version "restaurée" ? Des erreurs Abeille ?

**Comment by Jake309** [comment]
Je t'ai mis des package de logs au plus haut, mais ce n'est pas lié à abeille. Car en utilisant TestGUI sous windows, j'arrive pas à appairer ou faire communiquer mes équipements avec la zigate

**Comment by tcharp38** [comment]
Bon si t es sur qu'Abeille n est pas en cause, je creuse pas + pour l'instant.
Je ne savais pas qu'on pouvait declenché une inclusion avec TestGui. Jamais essayé.

**Comment by Seby9576** [comment]
Salut, ça donne pas envie de mettre à jours vu le nombre d'équipement sur ma zigate. Pas envie de tout recommencer 😣
Est ce Jne erreur de procédure ou normalement après maj on est pas obligé de tout Re inclure ?

**Comment by tcharp38** [comment]
T as pas eu de chance. J'ai une v1 USB et 3x v1 Pi et j'ai fait des tas de mises à jour depuis sans soucis autres que tout reappairer parfois.

**Comment by Seby9576** [comment]
Salut

Je vais me lancer dans la maj. Aucun soucis si je passe en 3.21 ?

Quel fichier je dois mettre sur les trois  pour faire la maj svp ? Merci
![image](https://user-images.githubusercontent.com/77990298/149189902-6716b0af-26a5-4f1e-9745-56ab7f354dc0.png)

**Comment by tcharp38** [comment]
Salut @Seby9576 
Tu es toujours sur ta v1 USB ?

**Comment by Seby9576** [comment]
j'ai fait une seule maj mais directement depuis eedomus de souvenir. Je suis en 3.1D

Mais du coup je veux surtout pas faire de bêtise d'où ma question. Surtout qu'il y a trois fichiers

**Comment by tcharp38** [comment]
Tu es en 3.1d donc version "legacy".
Tu prends le firmware "3.21-legacy" pour continuer sans tout réappairer.

La zigate USB v1 est un peu plus lourde pour la mise à jour. C'est la premiere.
Il faut la debrancher, ouvrir le boitier pour avoir acces au bouton, et la brancher sur un PC en maintenant le bouton enfoncé.
Apres quoi tu la flash avec "NXP JN51xx flash programmer".
Attention: tu ne FAIS PAS l'etape 7 (erase EEPROM).

voir  https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

**Comment by Jake309** [comment]
Pour les rex, ma zigate v2, j'en suis fou.
Ça a changé ma vie.
C'est pratiquement instantané, les lumières s'allument tout en même temps quasiment. 
La différence est vraiment flagrante. 
Je ne regrette plus que ma v1 est lâché.

**Comment by tcharp38** [comment]
@Jake309 
Tu dis qu'une v2 est plus "reactive" ?

**Comment by Jake309** [comment]
Oui, chez moi c'est le cas. Et tu vois bien la différence. Que ce soit via un design, Alexa ou le plus lent a l'époque via un bouton Xiaomi. Les 3 sont aussi rapide pour pas dire "instantané"

**Comment by tcharp38** [comment]
Ha ok. Merci pour cette info.
J'espere que tu n'aura pas de soucis spécifiques v2.

**Comment by tcharp38** [comment]
@Jake309 
J'aimerais comprendre un peu mieux pourquoi tu vois un grand changement de reactivité.
Tu es passé de v1 USB a v2 USB. Correct ?
Sais tu dire combien tu as de routers et end devices ?

**Comment by Seby9576** [comment]
> Ok donc si v1 tu dois passer par un soft windows
> 
> * demonter la clef pour appuyer sur bouton en meme que tu l inseres
> * utiliser le soft pour la programmer
> 
> Voir chez Zigate la: https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

Dans la procedure il ne parle pas de ton bouton. J'ai la rouge et non la bleu donc je dois faire comme tu dis ?
Merci pour l'info de l'étape 7 sinon je l'aurais fait bêtement

**Comment by tcharp38** [comment]
:)
regarde de + pres la doc 
![image](https://user-images.githubusercontent.com/35221038/149621023-fb1c72d7-df1d-4285-a651-748a4531b771.png)

Rouge ou bleu.. ca c'est juste pour l'interface TTL. Ca change pas la procedure

**Comment by Seby9576** [comment]
c'est lequel fichier qu'on doit mettre stp ?

**Comment by tcharp38** [comment]
3.21-legacy
la https://github.com/fairecasoimeme/ZiGate/releases/download/v3.21-legacy/ZiGate_v3.21-legacy.bin

**Comment by Seby9576** [comment]
Salut,

Désolé mais est ce normal ? Du coup il n'est pas indiqué sur un port com et donc je ne peux pas la choisir pour la maj
![image](https://user-images.githubusercontent.com/77990298/149744346-ad3d56ce-78d7-4d92-a3c2-91f27447c113.png)

**Comment by tcharp38** [comment]
Je vois 2 choses possibles
- tu n'as pas maintenu le bouton appuyé pendant que tu inserais la zigate
- ou il te faut un driver correspondant au convertisseur TTL/USB

**Comment by Seby9576** [comment]
Ca doit être les drivers car j'ai maintenue le bouton

**Comment by Seby9576** [comment]
c'était bien les drivers mon windows 10 n'etait pas à jours car je l'ai formaté ce week end

**Comment by Seby9576** [comment]
![image](https://user-images.githubusercontent.com/77990298/149760467-2d9dff9a-93b9-43e2-ac1e-7749d92e8c27.png)
Fait et ca semble avoir réussi merci pour les conseils et j'espère que ca va améliorer certaines choses

**Comment by tcharp38** [comment]
Ok tu as donc basculé sur la toute derniere version du FW.
On peut clore ce sujet du coup ?

**Comment by Seby9576** [comment]
pour moi oui vu que la procédure est bonne et que ca fonctionne bien. Merci

**Comment by Jake309** [comment]
@tcharp38 je préfère réouvrir l'issue que de mettre des infos sur "fairesoitmeme", j'ai un peu une dent contre eux ^^

En la retestant après une nouvelle maj erase etc, le logiciel testGUI ne donne rien quand je mets des équipements en inclusion... donc même pb.
Par contre, j'ai voulu la mettre sur abeille pour tester, et la, pas mal d'erreur qui apparaisse du style : 
2022-02-11 12:06:43 Abeille ERREUR: Abeille1, Message corrompu (taille payload incorrecte, taille=18B, att=9B)
2022-02-11 12:06:41 Abeille ERREUR: Abeille2, Message corrompu (taille payload incorrecte, taille=30B, att=26B)
2022-02-11 12:06:41 Abeille ERREUR: Abeille1, Message corrompu (taille payload incorrecte, taille=12B, att=1B)
2022-02-11 12:06:30 Abeille ERREUR: Abeille2, Message corrompu (taille payload incorrecte, taille=32B, att=22B)
2022-02-11 12:06:26 Abeille ERREUR: Abeille1, Message corrompu (taille payload incorrecte, taille=23B, att=22B)
2022-02-11 12:06:24 Abeille ERREUR: Abeille2, Message corrompu (taille payload incorrecte, taille=17B, att=9B)

Après désactivation de la zigateV1 donc abeille2, plus d'erreur.

Je te mets les log. si vraiment tu veux qu'on creuse, on peut, mais en partant du principe qu'on s'était déjà bien prit la tête la dessus la dernière fois, faut pas non plus y passer trop de temps. Si tu vois rien d'intéressant on s'embète pas.
Pour moi, c'est lié à la zigate et pas à abeille, donc si tu vois rien, je pense pas que ca soit utile.
[AbeilleLogs-220211 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8048124/AbeilleLogs-220211.1.tar.gz)

**Comment by Jake309** [comment]
Ce qui est sur, c'est que ca m'a tout fait planter. plus rien ne répond de ce qui vient d'abeille.
Je restaure la sauvegarde de nuit...
La, je suis bien blasé ^^
