### ISSUE TITLE
Status ONLINE pour les routeurs

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#225]
Pour ONLINE, on peut imaginer faire cela pour les ampoules Ikea/Zigbee pas exemple mais cela signifie faire un ping permanent pour savoir si elle repond. On peut imaginer faire un pool toutes les 5 minutes et ajouter une commande info binaire ONLINE.

Peut être utilisé pour le plugin homebridge.

**Comment by NebzHB** [comment]
j'ai demandé d'ajouter le type générique ONLINE au core, ca sera à venir probablement.

Oui un ping n'est intéressant que sur les périphériques alimentés.

**Comment by KiwiHC16** [comment]
Le ping est en place.
des nouvelles du type ONLINE ?
Que dois je mettre à jour pour qu'homebridge recupere l'info ONLINE ?

**Comment by NebzHB** [comment]
Non pas de nouvelles, mais si tu mets ce type générique là, ca devrait fonctionner en homebridge

**Comment by KiwiHC16** [comment]
Done. 
![capture d ecran 2018-05-22 a 10 48 04](https://user-images.githubusercontent.com/8549674/40351843-a870207c-5dad-11e8-8baa-8a7753d0ca67.png)
It will be in the next push.
