### ISSUE TITLE
Ajout support IKEA TRÅDFRI LED 470 lm 4,7W E14 LED1949C5

### ISSUE THREAD

**Issue by GatRed** [KiwiHC16/Abeille#2250]
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/7741078/discovery.json.zip)
Bonjour,

Merci encore et toujours pour ce plugin.
Il y a une nouvelle ampoule IKEA qui, me semble-t-il n’est pas encore reconnu par Abeille (modèle à ne pas confondre avec le modèle très proche à 5,2W).
Voici le fichier discovery.json que j’ai pu obtenir.
Est-il possible de l’ajouter ?
En vous remerciant par avance,
Cordialement,
GatRed

**Comment by tcharp38** [comment]
[TRADFRIbulbE14WScandleopal470lm.zip](https://github.com/KiwiHC16/Abeille/files/7758590/TRADFRIbulbE14WScandleopal470lm.zip)
Pour test
A decompresser dans core/config/devices
puis redemarrer Abeille
refaire inclusion

En congés 1 semaine. Pour bosser dessus il serait bien que tu bascules sur la beta.

**Comment by GatRed** [comment]
Bonjour,

Désolé pour le temps de réponse et merci beaucoup pour ton retour très rapide.
J’ai pu ajouter l’ampoule.
Par défaut, le seul problème que je vois dans jeedom est le réglage de la température: 
Il y a 2 sliders dont je ne comprends pas bien le comportement, au lieu 1 slider pour gérer la température de l’ampoule.

Merci beaucoup pour tout le travail effectué 
![Capture d’écran 2022-01-02 à 21 52 07](https://user-images.githubusercontent.com/96384567/147889250-ab207d2c-8354-4d69-8e81-72a0c0f6cdbb.png)
!

**Comment by tcharp38** [comment]
Salut @GatRed 
Tres bonne année à toi.
Les 2 sliders dont tu parles sont une erreur. Ca devrait être 2 boutons, ou peut etre un seul slider.
Je vais revoir ma copie. 
Tout le reste fonctionne ?

**Comment by GatRed** [comment]
Bonjour @tcharp38,
Très bonne année à toi aussi  !
Le reste fonctionne, mais j’en ai une utilisation assez simple.
Si jamais voici les améliorations possibles :
- les boutons «Set White» «Set Blue» «Set Red» «Set Green» ne servant pas car l’ampoule ne gère les couleurs
- Il me semble qu’il devrait avoir 3 boutons pour le réglage de la température de la lumière, il manque peut-être le bouton 2200K ? (https://www.ikea.com/fr/fr/p/tradfri-ampoule-a-led-e14-470-lumen-sans-fil-a-variateur-dintensite-spectre-blanc-flamme-opalin-20486784/)
- le look de l’ampoule est un peu différent de celui qui apparait dans jeedom, je te joins une capture d’écran
![Capture d’écran 2022-01-03 à 11 25 21](https://user-images.githubusercontent.com/96384567/147920550-68157f27-9848-43db-9517-936277f6b58b.png)
En tout cas, pour moi, c’est déjà top ! merci beaucoup !

**Comment by tcharp38** [comment]
Nouvelle version pour 'core/config/devices/TRADFRIbulbE14WScandleopal470lm'
[TRADFRIbulbE14WScandleopal470lm.zip](https://github.com/KiwiHC16/Abeille/files/7801611/TRADFRIbulbE14WScandleopal470lm.zip)

Et l'image tu mets la tienne dans 'images' sous le nom '**node_Ikea-BulbE14CandleWhite.png**'

Côté température, Ikea dit que cette ampoule propose 3 "couleurs" differentes. Tu les connais ? Il y a au moins 2700K.
Est ce que le "Set-ColorTemp" fait qqch ?

**Comment by GatRed** [comment]
ok, j’ai testé hier soir.
Pour moi tout est OK !

Le slider Set-ColorTemp fait varier la température de l’ampoule, mais je n’identifie pas clairement la 3è couleur.
Je peux faire un test plus précis ce soir.

**Comment by tcharp38** [comment]
A priori cette ampoule ne supporte que 3 "couleurs" donc si tu en vois 3 ca veut dire que le slider couvre la plage.
Tiens moi au jus.

**Comment by tcharp38** [comment]
@GatRed 
On en est ou ?

**Comment by GatRed** [comment]
Salut @tcharp38 !
j’ai bien vérifié : le slider Set-ColorTemp permet bien de faire varier la température selon les 3 niveaux évoqués par IKEA sur leur page produit.
Pour moi, c’est tout bon !
Merci beaucoup.

**Comment by tcharp38** [comment]
Ok super je clos.
A réouvrir si soucis.
