### ISSUE TITLE
Télécommande sans fil Tuya 4 boutons (TS0044, _TZ3000_b7bxojrg)

### ISSUE THREAD

**Issue by cedricdev** [KiwiHC16/Abeille#2251]
Bonjour,

je viens d’acheter une télécommande sans fil Tuya ZigBee 3.0, 4 boutons :
https://fr.aliexpress.com/item/1005003017843535.html?spm=a2g0s.9042311.0.0.27426c37RBAqK2

Elle est reconnue mais comme un élément basic. pas boutons détectés.
Dans l'onglet 'avancé' de l'équipement j'ai

> Identifiant JSON : defaultUnknown

voici les infos trouvées dans AbeilleDiscover.log

```
Network: Abeille1
IEEE: B4E3F9FFFE35742A
EP list: 01/02/03/04
Manufacturer: '_TZ3000_b7bxojrg'
ModelId: 'TS0044'
Location: ''
MAC capa: 80
8043/Simple descriptor response, SQN=F9, Status=00, Addr=F2CF, Length=12, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0000/On/Off Switch, BitField=01
- InClusterCount=3
- InCluster=0000 => General-Basic
- InCluster=0001 => General-Power Config
- InCluster=0006 => General-On/Off
- OutClusterCount=2
- OutCluster=0019 => General-OTA
- OutCluster=000A => General-Time
8043/Simple descriptor response, SQN=FA, Status=00, Addr=F2CF, Length=0C, EP=02, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0000/On/Off Switch, BitField=01
- InClusterCount=2
- InCluster=0001 => General-Power Config
- InCluster=0006 => General-On/Off
- OutClusterCount=0
8043/Simple descriptor response, SQN=FB, Status=00, Addr=F2CF, Length=0C, EP=03, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0000/On/Off Switch, BitField=01
- InClusterCount=2
- InCluster=0001 => General-Power Config
- InCluster=0006 => General-On/Off
- OutClusterCount=0
8043/Simple descriptor response, SQN=FC, Status=00, Addr=F2CF, Length=0C, EP=04, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0000/On/Off Switch, BitField=01
- InClusterCount=2
- InCluster=0001 => General-Power Config
- InCluster=0006 => General-On/Off
- OutClusterCount=0
- Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/FFDE/FFFD/FFFE/FFE0/FFE1/FFE2/FFE3
- Clust 0001: 0000/0020/0021/FFFD
- Clust 0006: 0000
- Clust 0001: 0000/0020/0021/FFFD
- Clust 0006: 0000
- Clust 0001: 0000/0020/0021/FFFD
- Clust 0006: 0000
- Clust 0001: 0000/0020/0021/FFFD
```

Impossible de récupérer quelque chose avec l'assistant de découverte. J'espère que les infos au dessus feront l'affaire

Je ne sais pas si je m’y prends mal ou si c’est vraiment un type inconnu.
Je suis sur RPI3, zigate USB (1ere gen firmware 0004-0320) & jeedom 3.3.59, abeille version "2021-12-06 01:00:18".

J'ai inclus juste après 2 capteurs de température Aqara sans souci. Je conclus donc que le problème vient du module Tuya.

Je vous remercie d’avance pour votre aide.

Cédric

**Comment by cedricdev** [comment]
en fouillant dans /var/www/html/plugins/Abeille/core/config/devices/TOTO/TOTO.JSON j'ai trouvé un modèle qui s'en approchait.
le "TS0044__TZ3000_vp6clf9d"

merci pour cette doc en passant => https://kiwihc16.github.io/AbeilleDoc/ModeleJson.html

du coup je me suis fait ce json
[TS0044.zip](https://github.com/KiwiHC16/Abeille/files/7770943/TS0044.zip)
ça me va très bien, j'arrive à programmer des scenarios. mon but final est atteint.

par contre 3 remarques/questions : 
- je sais pas si mon nommage est viable pour l'avenir dans le dossier devices car il existe plusieurs version du TS0044 visiblement...
- le json contient des "click X" pour les actions sur les boutons. j'ai l'impression que en 'commands' pour la programmation jeedom ça ouvre un peu plus de possibilités. je n'y connais pas grand chose et je ne comprends pas vraiment la différence.
- le resultat des "clics" sont des chaines => 'single' pour 1 clic & 'double' pour 2 clics. est ce possible d'avoir un retour numerique?

**Comment by cedricdev** [comment]
au passage je n'ai pas réussi à avoir mieux que ce résultat sur mon discovery
![image](https://user-images.githubusercontent.com/17140041/147281444-da641e4c-40fc-4637-95c4-d68cc74c7a59.png)

**Comment by tcharp38** [comment]
Salut @cedricdev 
Juste de retour.
Je regarderai des que j'arrive à recuperer mon retard. Pour l instant priorité à transformer la derniere beta ( 211230-BETA-1) en stable. Si tu peux basculer dessus et signaler toute regression ca aidera. Merci

Ce dossier "TOTO" existe chez toi alors dans "devices" ?

**Comment by cedricdev** [comment]
non le dossier TOTO n'existe pas. c'était pour décrire le chemin que j'ai utilisé.

J'utilise le fichier json que j'ai paramétré depuis 3 semaines sans problème => https://github.com/KiwiHC16/Abeille/issues/2251#issuecomment-1000475612 

ci joint un png correspondant : 

![TS0044](https://user-images.githubusercontent.com/17140041/149347711-e95cd592-32e4-41ba-a156-b9b93d0cae52.png)

**Comment by tcharp38** [comment]
@cedricdev 
Ok, pour "toto" je demandais au cas ou. Il m'arrive de m'en servir et j'avais peur d'avoir poussé une bidouille temporaire :)

J'ai pris ton PNG que j'ai appelé "Tuya-TS0044.png".

J'ai pris ton JSON mais je l'ai renommé. Toutes les series Tuya doivent absoluement etre prefixées par l idenfiant fabricant sinon c'est le clash assuré (tellement de derivés sans les memes fonctions...)
Donc TS0044.json devient TS0044__TZ3000_b7bxojrg.json =>
[TS0044__TZ3000_b7bxojrg.zip](https://github.com/KiwiHC16/Abeille/files/7865331/TS0044__TZ3000_b7bxojrg.zip)

Côte "click", pourquoi une valeur numerique serait plus pratique ?
J'avais du faire un choix et je me disais qu'au moins "single", "double", ou "long" etait clair et sans surprise mais peut etre pas l ideal d apres ta requete.

**Comment by cedricdev** [comment]
tu peux oublier ma question c'est très bien le nommage. j'ai atteint mon objectif. ça m'a perturbé sur le coup, mais comme tu dis le nommage permet de comprendre directement.

- tu as intégré le json dans la prochaine beta?
- pour mon info : Les bidouilles que je fais dans le dossier /device , elles sont ecrasée à l'installation d'une nouvelle version si le nommage des fichiers/répertoires est identique? et si le nommage est different les fichiers restent en place? c'est bien ça?

**Comment by tcharp38** [comment]
Toutes mes modifs sont dans la beta du jour. Je n'ai plus rien en attente.

Le dossier "core/config/devices" doit normalement etre realigné sur ce qu'on pousse. Ca veut dire que tout fichier "inconnu" degage et tout fichier modifié et écrasé par l'original de la release.
Seul "core/config/devices_local" n'est pas touché

**Comment by cedricdev** [comment]
Hello @tcharp38 est ce que ce device est inclus dans la derniere beta? 13012022
je l'ai supprimé et ré inclus. ça a bien détecté et c'est fonctionnel mais il manque l'image. du coup j'ai un doute

**Comment by tcharp38** [comment]
Normalement oui.
Peux tu verifier la page avancé de l'equipement ? la partie identifiant zigbee et json. et me faire un snapshot ?

**Comment by cedricdev** [comment]
![image](https://user-images.githubusercontent.com/17140041/149617834-8d791895-4bd9-4f4e-b0a2-95f5e7fd95e5.png)

**Comment by tcharp38** [comment]
Tu me donnes le fichier "key infos", via la page support ?

**Comment by cedricdev** [comment]
[AbeilleKeyInfos.log](https://github.com/KiwiHC16/Abeille/files/7875044/AbeilleKeyInfos.log)

**Comment by tcharp38** [comment]
L'image est "Tuya4ButtonsSwitch" et non pas celle que j'ai mis dans le modele (Tuya-TS0044).
Tu es sur d'avoir supprimé l'équipement de Jeedom avant d'avoir refait son inclusion ?

**Comment by cedricdev** [comment]
ah oui pardon. j'ai forcé une image comme il n'y en avait pas. mais avant j'avais bien supprimé puis inclus à nouveau le module.
Je peux le refaire.
mais avant tu peux me donner le chemin exact de l'image pour que je verifie si elle est bien présente?

**Comment by tcharp38** [comment]
L'image doit etre "node_Tuya-TS0044.png"

**Comment by cedricdev** [comment]
j'ai redémarré le rpi, supprimé le device, réinclu.
toujours pas d'image dans jeedom pourtant tout semble présent dans les fichiers :
 ci dessous l'image bien présente
![image](https://user-images.githubusercontent.com/17140041/149671371-8d7e149f-9d2a-4d42-9b20-43b8b870afc3.png)
ci dessous la conf json. (c'est bon le nommage de l'icone?)
![image](https://user-images.githubusercontent.com/17140041/149671390-c6a51cef-2d17-4918-bad9-b6695a2738fd.png)
ci dessous une capture de ce que j'ai verifié. j'ai verifié le contenu du **select** pour trouver l'image dans la liste. elle n'y est pas. j'ai l'impression qu'elle devrait etre présente dans cette liste

![image](https://user-images.githubusercontent.com/17140041/149674741-d6341b88-cbe5-40ab-a74d-09798ce84475.png)


A part ce souci d'image tout fonctionne bien donc ça ne me gène pas.
n'hésite pas à me demander d'autres infos si besoin.

**Comment by cedricdev** [comment]
![image](https://user-images.githubusercontent.com/17140041/149674750-df56c72e-b3f5-4367-b7fc-ac7f255140c7.png)

**Comment by cedricdev** [comment]
image introuvable dans le <select>

![image](https://user-images.githubusercontent.com/17140041/149674817-443a6b14-8fe1-493e-a125-1119e3f78a01.png)

**Comment by tcharp38** [comment]
Salut @cedricdev 
Je viens de refaire un essai sur la derniere beta. j'ai modifié un JSON pour utiliser "Tuya-TS0044" comme icone puis reinitialisé via la page EQ/avancé.
L'icone est mise à jour. Donc je pige pas pourquoi ton icone n'est pas mise à jour. J'aurais bien aimé fermer ce sujet.

**Comment by cedricdev** [comment]
Hello @tcharp38 . ça me va bien de fermer le sujet. je referai un ticket si je constate un souci sur une nouvelle inclusion plus tard.
Le reste fonctionne au top c'est l'essentiel. et encore merci pour ton boulot!
