### ISSUE TITLE
Support capteur de mouvement Tuya ZigBee PIR motion sensor (RH3040)

### ISSUE THREAD

**Issue by cedricdev** [KiwiHC16/Abeille#2252]
Bonjour,

je viens d'acheter un capteur de mouvement Tuya ZigBee PIR motion sensor :
https://fr.aliexpress.com/item/1005003152536146.html?spm=a2g0s.9042311.0.0.2af66c37c51bKI

il est reconnu mais comme un élément basic. pas de fonction de capteur de mouvement.
Dans l'onglet 'avancé' de l'équipement j'ai

> Identifiant JSON : defaultUnknown

voici les infos trouvées dans AbeilleDiscover.log

```
Network: Abeille1
IEEE: 847127FFFE29B637
EP list: 01
Manufacturer: 'TUYATEC-zn9wyqtr'
ModelId: 'RH3040'
Location: -unsupported-
MAC capa: 80
8043/Simple descriptor response, SQN=FE, Status=00, Addr=07BE, Length=12, EP=01, ProfId=0104/ZigBee Home Automation (ZHA), DevId=0402/IAS Zone, BitField=01
- InClusterCount=3
- InCluster=0000 => General-Basic
- InCluster=0001 => General-Power Config
- InCluster=0500 => Security & Safety-IAS Zone
- OutClusterCount=2
- OutCluster=0019 => General-OTA
- OutCluster=000A => General-Time
- Clust 0000: 0000/0001/0002/0003/0004/0005/0006/0007/FFDE/FFFD/FFFE/FFE0/FFE1/FFE2/FFE3
- Clust 0001: 0000/0020/0021/FFFD
- Clust 0500: 0000/0001/0002/0010/0011/FFFD
```
Impossible de récupérer quelque chose avec l'assistant de découverte. J'espère que les infos au dessus feront l'affaire

Je ne sais pas si je m’y prends mal ou si c’est vraiment un type inconnu.
Je suis sur RPI3, zigate USB (1ere gen firmware 0004-0320) & jeedom 3.3.59, abeille version 2021-12-06 01:00:18".

J'ai inclus juste après 2 capteurs de température Aqara sans souci. Je conclus donc que le problème vient du module Tuya.

Je vous remercie d’avance pour votre aide.

Cédric

**Comment by tcharp38** [comment]
Salut Cédric.
Peux tu generer un discovery.json ? voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by cedricdev** [comment]
Hello

J'ai bien essayé mais rien n'y fait (ci joint la capture d'écran. je n'arrive pas à faire mieux) j'ai pourtant essayé plusieurs situations on/off, reset, declencher un mouvement, le faire juste après une inclusion, etc... Je suis sec.
![image](https://user-images.githubusercontent.com/17140041/146823972-664f6633-88bd-4a23-bb16-4acdc54ae8e9.png)

pour info je trouve que mon cateur ressemble beaucoup à celui ci : https://zigate.fr/le-materiel-compatible-zigate/compatible/samotechpirsensor/

cdt

**Comment by tcharp38** [comment]
J imagine que c est un equipement sur batterie. Il te faut donc le "reveiller" plusieurs fois pendant l'interrogation.
Je vais tacher de construire qqch avec les infos fournies.

**Comment by tcharp38** [comment]
[RH3040.zip](https://github.com/KiwiHC16/Abeille/files/7748137/RH3040.zip)
A decompresser dans core/config/devices
puis
- redemarrer Abeille
- refaire une inclusion

Je compte sur toi pour trouver une image PNG sans arriere plan pour mettre en icone

**Comment by cedricdev** [comment]
Bonjour tcharp. merci pour ton aide. le module est reconnu maintenant.
cependant la capture de mouvement ne déclenche rien coté jeedom (icone zone-status)

Pour l'assistant de découverte j'ai réussi 2 fois à aller plus loin sans jamais obtenir tout vert. je ne peux pas telecharger le JSON dans ce cas. du coup je ne peux malheureusement que t'envoyer les 2 snaps où j'ai eu quelques infos.

![image](https://user-images.githubusercontent.com/17140041/146941551-e7dddede-5c68-42cf-901a-0a730c4f738e.png)

![image](https://user-images.githubusercontent.com/17140041/146941610-8b5179e8-2163-40d2-a72c-bc6193dde4c5.png)

j'ai réussi à avoir ça en demarrant l'assistant de découverte juste après une inclusion

**Comment by cedricdev** [comment]
petit don à l'instant sur votre cagnotte au passage (https://kiwihc16.github.io/AbeilleDoc/Presentation.html#cagnotte). étant moi même dev je mesure le taff et le temps passé ;)

**Comment by tcharp38** [comment]
Effectivement je n'avais pas configué de chemins de retour pour le cluster 0500.
Donc tester avec cette nouvelle version en refaisant une inclusion
[RH3040.zip](https://github.com/KiwiHC16/Abeille/files/7757481/RH3040.zip)

Merci pour le don.

Je suis surpris que tu ne puisse pas telecharger le JSON meme si pas complet. Certains me le filent vide.
Etrange.

**Comment by cedricdev** [comment]
Bonjour @tcharp38,

j'ai tenté avec le nouveau fichier (copie du json puis carrément redémarré le rpi3 et inclusion). le mouvement ne se déclenche toujours pas.
par contre j'ai réussi à avoir une découverte entièrement verte. je n'arrive toujours pas à télécharger via le bouton. ci joint la capture d'écran de ma console. (3 clics tentés)

![image](https://user-images.githubusercontent.com/17140041/147154681-604164eb-f54c-4125-b3b0-bf87540a63ca.png)

en cliquant sur l'erreur ça m'affiche un nouvel onglet avec cette trame json (j'ai l'impression que c'est le resultat du discovery)=>
`{"epCount":1,"endPoints":{"01":{"servClusters":{"0000":{"attributes":{"0004":{"value":"TUYATEC-zn9wyqtr","dataType":"42","access":"05"},"0000":{"dataType":"20","access":"05","value":3},"0001":{"dataType":"20","access":"05","value":69},"0002":{"dataType":"20","access":"05%2...22},"0011":{"dataType":"20","access":"05","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":"UNSUPPORTED"}},"cliClusters":{"0019":{"attributes":{"0000":{},"0001":{},"0006":{},"FFFD":{}}},"000A":{"attributes":{"FFFD":{}}}}}},"powerSource":"battery"}`

**Comment by cedricdev** [comment]
J'ai profité d'une après midi calme pour faire plein d'essais. j'ai tenté plusieurs paramètres json en m'inspirant de nombreux exemples dans le dossier 'devices'. sans succès. Rien d'urgent de toute façon. J'attends ton retour de congés :D 
A+

**Comment by tcharp38** [comment]
Salut @cedricdev 
I'm just back !
Mais l'urgence pour moi est de transformer la beta  211230-BETA-1 (dispo demain) en premiere stable de l'année. Du coup si tu peux basculer dessus et signaler toute regression ca serait chouette.
Apres je pourrai reprendre le sujet.
Merci

**Comment by cedricdev** [comment]
Salut @tcharp38 ça marche. pas d'urgence pour mes demandes de support.
pour installer la beta j'ai bien trouvé la doc (https://kiwihc16.github.io/AbeilleDoc/Installation.html) mais j'ai un peu peur de perdre mes confs. Le plugin est déjà installé et il ne me propose pas de maj vers beta dans le centre de MAJ jeedom malgré l'activation beta dans le market. par contre en faisant une recherche du plugin j'ai bien le bouton "installer beta". Si je clique dessus ça va écraser ma stable sans perdre mes confs?

**Comment by tcharp38** [comment]
Qu'entends tu par "confs" ?
Tu peux faire une sauvegarde de Jeedom juste avant et restaurer au moindre souci.
Mais dis toi bien que la beta actuelle deviendra une stable cette semaine si je n'ai aucun retour négatif.

**Comment by cedricdev** [comment]
je parlais des inclusions dans Abeille et les devices zigbee utilisés dans les scénarios.
Pour faire simple si je clique sur "installer beta" directement depuis le market est ce que ça aura le meme effet qu'un upgrade depuis le centre de mise à jour dans jeedom. ça sera bien transparent?

**Comment by tcharp38** [comment]
C'est l'idée oui. Mais avec un backup tu risques pas grand chose.

**Comment by cedricdev** [comment]
done. je suis sur la version du 31/12. ça marche impec.
Je suis zen j'ai fait une sauvegarde jeddom et aussi une image de mon ssd :D
Ceinture et bretelle. je te tiens au courant si je constate un problème.

**Comment by tcharp38** [comment]
Super :)

**Comment by cedricdev** [comment]
Hello @tcharp38 Je suis en version du 09.01.2022 pas de régression constatée (je suis passé aussi en version 4.1.28 de jeedom)

J'ai vu dans le changelog le support du RH3040 (suite à la création de ce ticket 2252)
https://kiwihc16.github.io/AbeilleDoc/Changelog.html

Le capteur est bien reconnu mais le "zone-statut" n'est jamais déclenché suite à une detection de mouvement. pendant les congés j'avais fait plein de tests de config json sans succès (https://github.com/KiwiHC16/Abeille/issues/2252#issuecomment-1001211966)

**Comment by tcharp38** [comment]
Salut @cedricdev 
Peux tu le declencher puis me filer le package de logs ?
Et l'heure du declenchement.

**Comment by cedricdev** [comment]
Intéressant. j'apprends des choses avec ton support. je lis qu'un message est ignoré dans les logs (14:41)
[AbeilleLogs-220112.tar.gz](https://github.com/KiwiHC16/Abeille/files/7854954/AbeilleLogs-220112.tar.gz)

**Comment by tcharp38** [comment]
Il y a donc bien l info qui remonte mais est ignorée.

> [2022-01-12 14:41:55][DEBUG] : message(topic='Abeille1/11B9/0500-01-0000', payload='0001')
> [2022-01-12 14:41:55][DEBUG] :   L'objet 'Abeille1/11B9' existe mais pas la cmde '0500-01-0000' => message ignoré
> 

Je regarde ca + tard.

**Comment by tcharp38** [comment]
Je viens de faire une modif pour supporter ce cas. Je te fais signe des qu'elle est sur la beta.
Entre temps je vois qu'il n y a pas d'icone pour ce periph. Y a t il deja une image qui correspond au visuel ? Si oui laquelle ? Sinon je te laisse me trouver un PNG sans fond qui correspond. Merci

**Comment by cedricdev** [comment]
Salut. Merci pour ton support. ci joint une image png sans fond.

![RH3040](https://user-images.githubusercontent.com/17140041/149346995-1fb7b346-8756-44e0-9cda-b65bf8c0b68e.png)

J'en profite pour ajouter l'image dans mon autre ticket aussi (2251)

**Comment by tcharp38** [comment]
Voir 220113-BETA-1
Et refaire inclusion apres.
Tu devrait avoir une "Zone-Status" qui soit mise à jour sur presence

**Comment by cedricdev** [comment]
ok. je fais l'upgrade dès que c'est dispo sur le market. Il n'y a que celle du 11012022 pour le moment

**Comment by tcharp38** [comment]
Oui je viens de la faire donc dispo demain

**Comment by cedricdev** [comment]
Tout est ok pour moi maintenant. le capteur est parfaitement fonctionnel et le png apparaît. Merci.

**Comment by tcharp38** [comment]
On peut clore ce sujet du coup ?

**Comment by cedricdev** [comment]
oui je le ferme
