### ISSUE TITLE
Inclusion impossible avec v2, mais ok en v1

### ISSUE THREAD

**Issue by mohatem** [KiwiHC16/Abeille#2254]
Bonjour, depuis quelque jour j’ai remis mon jeedom a neuf, j’ai un RPI4 avec zigate+, je n’ai pas reussi à reinclure l’interrupteur aqara sans fil carré de la chambre du fiston, j’ai commandé un nouvel interrupteur et pareil impossible de l’inclure, j’ai remis ma zigate+ à zero et reinclu

    9 relay xiaomi
    5 detecteur de mouvements xiaomi
    -10 double inter carre sans fil xiaomi
    6 inter simple carre sans fil xiaomi (dont 1 nouveau qui ne voulait pas s’inclure avant la remise a zero )
    1 detcteur d’inondation xiaomi
    6 capteur de porte xiaomi
    2 detecteur de fumée xiaomi
    6 spot ikea
    rebelotte je n’arrive plus a reintegrer de nouvel appareil xiaomi (j’ai essayé plusieurs equipements differents inter, capteur porte…)
    j’ai pri la zigate+ car elle peut theoriquement prendre en charge jusqu’à 200 equipements, j’ai surement raté quelque chose.
Je vient de rajouter mon ancienne zigate v1 en plus et elle prend bien les equipements qui ne passaient pas sur la v2

merci pour votre retour

**Comment by mickadam29** [comment]
Salut

Il existe des issues sur le site de Zigate. Cela concerne le Zigate+
Abeille n'est pas en cause à mon avis.
J'ai bataillé pour inclure un interrupteur Ikea E1743, tous les autres équipements se sont inclus sans problème, ou presque. Il suffit de patienter un jour ou deux pour que l'interrupteur supprimé puisse à nouveau être inclus. Ayant une pizigate (V1), je te confirme que l'interrupteur s'associe très bien à chaque fois avec la même version d'Abeille. Donc le problème est orienté Zigate+ plus qu'Abeille.
Je t'invite à lire ceci si pas déjà fait
https://github.com/fairecasoimeme/ZiGatev2/issues/24

**Comment by mohatem** [comment]
Merci

**Comment by tcharp38** [comment]
Salut @mohatem @mickadam29 
Tres bonne année à vous.

Pour toute diff v1 vs v2, je vous suggere si pas deja fait de remonter les soucis à Zigate directement.
Sauf erreur Abeille n'est pas en cause alors je ferme le sujet mais n'hesitez pas à reouvrir si des nouvelles infos peuvent aider les autres.

A noter que le titre "Inclusion impossible" est trop generique.
