### ISSUE TITLE
Support applique murale Silvercrest HG06701B (TS0505A, _TZ3000_5bsf8vaj)

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2256]
Bonjour,

Et meilleurs voeux pour 2022 en espérant qu'elle soit pleine de rebondissement à tous les points de vue.

J'ai tenté d'inclure un nouveau périphérique Sivercrest, une applique murale LED. Elle est reconnu comme un bande led de la même marque, et c'est presque pas faux car elle dispose des mêmes fonctions : 16Mio de couleurs, blnc chaud à froid.

Mais après inclusion, aucune commande ne fonctionne.

Je vous joins le discovery pour voir ce qui diffère ?!

D'avance merci pour votre aide,
Bonne journée
[discovery(6).zip](https://github.com/KiwiHC16/Abeille/files/7806901/discovery.6.zip)
,

**Comment by tcharp38** [comment]
Salut @Thiematz 
Tres bonne année.

Quet est le type de cet equipement ? Il s'agit de quoi ?
Quel est le modele/ref fabricant ?
L'icone correspondante existe déja ou tu as un PNG sans fond à me filer ?

**Comment by Thiematz** [comment]
Salut @tcharp38,

il s'agit d'une applique murale LED extérieure/intérieur de Lidl (Sivercrest).
En fait elle se comporte comme un ruban led, avec une nuance de 16Mio de couleur, variateur blanc chaud à blanc froid, 
Je te joins le PNG sans fond
![lidl_applique-murale-led-dexterieur-connectee](https://user-images.githubusercontent.com/94549335/148076039-d4fb1c7a-8278-455e-836d-e347a5d7e90f.png)

Je te joins également un petit test qui à été réalisé sur ce produit.
https://www.maison-et-domotique.com/128027-test-lidl-smart-home-multiprise-applique-exterieure-zigbee/

Est-ce suffisant pour avancer ?

**Comment by tcharp38** [comment]
[TS0505A__TZ3000_5bsf8vaj.zip](https://github.com/KiwiHC16/Abeille/files/7808638/TS0505A__TZ3000_5bsf8vaj.zip)

A tester

Quel est la ref/modele donnée pour ce truc ?

**Comment by Thiematz** [comment]
J'ai trouvé ça : HG06701B

**Comment by Thiematz** [comment]
@tcharp38 ,

Merci, j'ai réussi à l'intégrer. Mais je ne peux que faire les fonctions suivantes :
ON, OFF, TOGGLE, et jouer sur l'intensité (variateur)
Je ne peux pas jouer sur la couleur ni sur le blanc chaud, blanc froid.

**Comment by tcharp38** [comment]
Déja et sauf erreur, elle ne supporte pas la couleur. Donc je vire des fonctions du style "Set White"... etc etc
[TS0505A__TZ3000_5bsf8vaj.zip](https://github.com/KiwiHC16/Abeille/files/7816498/TS0505A__TZ3000_5bsf8vaj.zip)

Mais elle doit supporter (d apres la photo de ta boite) la temperature de couleur. On va tacher de creuser ca
Assure toi d'etre en mode debug pour la suite.
Tu dois avoir un slider "Set ColorTemperature"
fais le bouger une fois puis file moi le package de logs (page support/telecharger tout).

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

je pense que tu fais erreur ;-), regarde la photo de l'emballage ci-jointe, pour moi elle le fait.
![20220106_195839](https://user-images.githubusercontent.com/94549335/148438733-0e91d7b3-42d4-43e6-b016-ad8e27f4079b.png)

Je n'ai donc pas installé le dernier fichier que tu m'as envoyé, et les tests suivants sont donc avec le précédent.
Dis-moi si tu veux tout de même que j'installe le dernier fichier.

Le slider "Set ColorTemperature" est bien présent mais impossible de le bouger

Le module s'appelle Abeille1-248 si cela peut t'aider dans les recherches dans les logs
[AbeilleLogs-220106.tar.gz](https://github.com/KiwiHC16/Abeille/files/7824244/AbeilleLogs-220106.tar.gz)

**Comment by tcharp38** [comment]
Effectivement.
J'ai remis les commandes.
Set ColorTemp à tester

Correctif pour core/config/commands
[zbCmd-0300-MoveToColorTemp.zip](https://github.com/KiwiHC16/Abeille/files/7824979/zbCmd-0300-MoveToColorTemp.zip)

Correctif pour core/config/devices/TS0505A__TZ3000_5bsf8vaj
[TS0505A__TZ3000_5bsf8vaj.zip](https://github.com/KiwiHC16/Abeille/files/7824993/TS0505A__TZ3000_5bsf8vaj.zip)

Tout est dans la 220113-BETA-1

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

J'ai installé la dernière version beta, 220114-BETA-1. Je n'ai donc pas uploader les derniers correctifs qui devraient y être si j'ai bien suivi.
J'ai supprimé l'applique pour refait une inclusion. Mais le résultat est le même, impossible de jouer sur la couleur, le curseur ne bouge pas. De même, je ne peux pas varié le blanc (chaud froid)
Seule la luminosité fonctionne
![Capture](https://user-images.githubusercontent.com/94549335/149789561-59eaece8-8b04-40a6-8a1d-dbdf60822b0a.JPG)
[AbeilleLogs-220117.tar.gz](https://github.com/KiwiHC16/Abeille/files/7882569/AbeilleLogs-220117.tar.gz)

**Comment by tcharp38** [comment]
@Thiematz 
Désolé, Il y avait une boulette de clef dupliqué.

[TS0505A__TZ3000_5bsf8vaj.zip](https://github.com/KiwiHC16/Abeille/files/7925927/TS0505A__TZ3000_5bsf8vaj.zip)
Ecraser l'original et faire "recharger" dans la page EQ/Avancé.

Sera dans la prochaine beta.

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

on s'en approche ;-)

Je peux maintenant jouer sur la température de la lumière blanche, entre 2200 et 6000

Mais je ne peux toujours pas changer la couleur

![Capture](https://user-images.githubusercontent.com/94549335/151059831-b677f7f8-2b27-415c-833e-82cf9919ccd9.JPG)

**Comment by tcharp38** [comment]
Nouvelle tentative
[TS0505A__TZ3000_5bsf8vaj.zip](https://github.com/KiwiHC16/Abeille/files/7943647/TS0505A__TZ3000_5bsf8vaj.zip)
Ecraser l'original et faire "recharger" dans la page EQ/Avancé.

Je suis reparti de ce qui fonctionne avec le modele GL-S-007Z Gledopto.

Si pas déja fait pense à basculer avant sur la beta 220123-BETA-1

**Comment by Thiematz** [comment]
Salut @tcharp38,

cette fois c'est la bonne, toutes les fonctions sont disponibles.

Un grand merci à toi

**Comment by tcharp38** [comment]
Cool.
Tu me fera un retour sur la beta si jamais tu vois un souci ?
