### ISSUE TITLE
Support Capteur d'ouverture Aqara MCCGQ14LM (magnet.acn001)

### ISSUE THREAD

**Issue by Chris-lal** [KiwiHC16/Abeille#2257]
hello @tcharp38,

encore moi pour un nouvel équipement...

un capteur d'ouverture magnétique de la marque Aqara Modèle MCCGQ14LM , il ressemble a s'y méprendre au capteurs Xiamoi Aqara déja supportés, mais il ne sont pas reconnus par Abeille donc je suppose que c'est un nouveau modèle.

pour l'image dans Abeille, je pense que ça peut être la même que les autres (XiaomiPorte)
je met des photos ici pour ceux que ça pourrait aider à identifier:

Merci pour ton aide.

![Inked20220104_174439_LI - Copie](https://user-images.githubusercontent.com/89514100/148098049-e9096b31-9e5d-4b9e-b0be-2320e457fd70.jpg)
![20220104_174408 - Copie](https://user-images.githubusercontent.com/89514100/148098107-43fa5bb8-086c-4716-ac19-400d650a5ade.jpg)
![20220104_174632 - Copie](https://user-images.githubusercontent.com/89514100/148098199-933a01de-7891-40ff-9e72-07926df61b58.jpg)

**Comment by tcharp38** [comment]
Salut @Chris-lal 
Tu connais la musique non ? :)
Essaie de me generer un "discovery.json" avec l'assistant STP.

**Comment by Chris-lal** [comment]
Mais oui... je suis un peu a l'ouest :)
logs : [AbeilleLogs-220105.tar.gz](https://github.com/KiwiHC16/Abeille/files/7817890/AbeilleLogs-220105.tar.gz)
Discovery: [discovery.zip](https://github.com/KiwiHC16/Abeille/files/7817895/discovery.zip)

merci !

**Comment by tcharp38** [comment]
[magnet.acn001.zip](https://github.com/KiwiHC16/Abeille/files/7821390/magnet.acn001.zip)
 A tester

pour core/config/devices

Tout est dans la 220113-BETA-1

**Comment by Chris-lal** [comment]
c'est testé, le capteur est bien reconnu au niveau du nom, de l'image, des commandes...
Par contre je ne vois pas quelle variable représente la détection de proximité et je ne vois rien qui change.
[AbeilleLogs-220115.tar.gz](https://github.com/KiwiHC16/Abeille/files/7875496/AbeilleLogs-220115.tar.gz)

**Comment by tcharp38** [comment]
Comment peux tu dire qu'il est bien reconnu ? Je vois un device announce mais il n'est pas reconnu. Au lieu de "magnet.acn001" il prend "defaultUnknown".
Qu'affiche la page avancé de l'equiepemnt ? (identifiant JSON)

**Comment by Chris-lal** [comment]
Oui à la première réinclusion il est resté en DefaultUnknown, mais j'avais oublié les chown et chmod à la copie du JSON.
La seconde inclusion s'est bien passé:

2022-01-15 18:34:22 | Abeille | Nouvel équipement identifié (Xiaomi Aqara MCCGQ14LM door sensor). Création en cours. Rafraîchissez votre dashboard dans qq secondes.

dans avancé > Identfiant JSON : magnet.acn001

**Comment by tcharp38** [comment]
Ok je vois plusieurs annonces. Pas tres propre tout ça.
En temps normal tu devrais avoir les infos de présence sur "Zone Status".
Un point: je vois qu'un FW zigate contient des correctifs pour ce device donc tu devrais essayer avec la 3.21.

https://github.com/fairecasoimeme/ZiGate/releases/tag/v3.21-legacy

**Comment by Chris-lal** [comment]
Hello,

j'ai MAJ ma Zigate en 3.21, exclu le capteur puis nouvelle inclusion propre.
le résultat est malheureusement le même, pas de changement de la valeur de Zone status quand je joue avec le capteur. J'ai testé avec deux capteurs pour être sur que ce n'est pas le matériel qui fait défaut.
[AbeilleLogs-220117.tar.gz](https://github.com/KiwiHC16/Abeille/files/7884119/AbeilleLogs-220117.tar.gz)

**Comment by tcharp38** [comment]
Je vois des infos remonter, mais pas comme je m'y attendais.

A tester.
[magnet.acn001.json.zip](https://github.com/KiwiHC16/Abeille/files/7888145/magnet.acn001.json.zip)

=> 220121-BETA-1

**Comment by Chris-lal** [comment]
Nouveau JSON testé, la commande info "zone-status" disparait.

après le refesh de config ou une nouvelle inclusion j'ai le message suivant : Le fichier de commande 'zb-0500-ZoneStatus-ChangeNotification.json' n'existe pas.
[AbeilleLogs-220122.tar.gz](https://github.com/KiwiHC16/Abeille/files/7918895/AbeilleLogs-220122.tar.gz)

**Comment by tcharp38** [comment]
Salut @Chris-lal 
Le fichier qui te manque doit etre dans la derniere beta, dispo ce jour.
Tu peux basculer dessus ?

**Comment by Chris-lal** [comment]
Hello @tcharp38, 
c'est testé en Beta et OK :D
ZoneStatus à 100 en fermé et 101 en ouvert !
Est-ce qu'il y a moyen de le passer en binaire ou ça dépend du matériel ?
[AbeilleLogs-220126.tar.gz](https://github.com/KiwiHC16/Abeille/files/7945334/AbeilleLogs-220126.tar.gz)

**Comment by tcharp38** [comment]
Cool.
Le bit 0 est le seul utile dans ce cas. Il s'agit d "alarm1".
Idéalement au lieu de ce retour ca serait mieux d'avoir une info du style "Status": 1=ouvert, 0=fermé.

Je reflechis à ca

**Comment by tcharp38** [comment]
@Chris-lal 
Je reviens la dessus.
Peux tu basculer sur la derniere beta, refaire une inclusion, declencher  une ouverture (noter l heure) et me filer le package de logs avec l'heure.

Tu devrais avoir une commande info de + => "Status", type binaire.

**Comment by tcharp38** [comment]
@Chris-lal 
Depuis plusieurs stables sont tombées.
Je peux clore le sujet ?

**Comment by tcharp38** [comment]
Plus de nouvelles depuis un bail.
Je clos mais si qqn a des soucis.. a reouvrir.
