### ISSUE TITLE
Port serie NOK (déjà utilisé)

### ISSUE THREAD

**Issue by komega13** [KiwiHC16/Abeille#2259]
Bonjour,

Subitement aujourd’hui tout mes devices sont passés en time out. Je check la config de Abeille et je vois que le port serie ttyUSB1 est NOK.

J’ai essayé de débrancher puis rebrancher la zigate dans diffèrent port USB, j’ai redémarré mon RPI3b+ sans succès

Je suis en Jeedom V4.1.28
Plugin abeille mis à jour aujourd’hui sans amélioration (Version du 2021-12-06 01:00:18)

Je n’ai rien branché sur le RPI3b+ depuis . (A savoir que mes clefs zigate, z-wave sont sur un HUB auto-alimenté)

Le log Abeilleconfig.log indique :
`[2022-01-04 20:29:23] Démarrage de 'checkTTY.sh'
[2022-01-04 20:29:23] Vérifications du port '/dev/ttyUSB1'
[2022-01-04 20:29:23] = Ok, le port semble libre.
[2022-01-04 20:30:18] Démarrage de 'checkTTY.sh'
[2022-01-04 20:30:18] Vérifications du port '/dev/ttyUSB1'
[2022-01-04 20:30:18] = ERREUR: Le port est utilisé par le process '1093'.
[2022-01-04 20:30:18] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
[2022-01-04 20:30:18] =         Details du process 1093:
[2022-01-04 20:30:18] =           PPid=671, cmd='/usr/sbin/apache2 -k start'`

Abeillecmd.log :
`(les mêmes messages en boucle)
[2022-01-04 14:02:30]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-01-04 14:02:50]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-01-04 14:02:51]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-01-04 14:02:52]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.`

Abeille :
`[2022-01-04 14:03:10][ERROR] : Port série de la zigate 1 INVALIDE ! Zigate désactivée.`

J'ai posté sur le forum Jeedom [ici](https://community.jeedom.com/t/port-serie-nok-port-deja-utilise/75509/5)

Merci par avance pour votre aide :)

**Comment by tcharp38** [comment]
Salut @komega13 
Je t'invite à basculer sur la 211230-BETA-1 qui devrait devenir la prochaine stable d'ici peu.
Voir: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by komega13** [comment]
Salut @tcharp38 et merci pour ta réponse.
Je viens de passer en 211230-BETA-1 suivant la procédure de ton lien, hélas aucune amélioration la zigate n'est toujours pas détectée. Je ne comprend vraiment pas ce qu'il à pu se passer alors que tout fonctionnait bien.

**Comment by tcharp38** [comment]
Salut.
- Assure toi d etre en mode debug
- redemarre Abeille
- et file moi le package de logs (page support/telecharger tout).
- ha et un snapshot de ta page de config pour la zigate en question

**Comment by komega13** [comment]
Salut
Voici le package après avoir basculé en degub +sauvegarde + relance du deamon : 
[AbeilleLogs-220108.tar.gz](https://github.com/KiwiHC16/Abeille/files/7833734/AbeilleLogs-220108.tar.gz)

Voici le screen de la config zigate : 
![fcc11](https://user-images.githubusercontent.com/7727919/148655085-8bc9decb-5fba-40c3-9da2-decec32ded77.png)

**Comment by tcharp38** [comment]
Je pige pas mais je te propose l'essai suivant
- vire la gestion automatique
 
![image](https://user-images.githubusercontent.com/35221038/148657299-e700d060-f3c5-4a8c-b474-0b4e6f42afcc.png)

- arrete les demons Abeille
- Reactive la zigate 1 qui est désactivée.
- Au bout d1 a 2 mins redemarre Abeille
- puis refile moi les logs au cas ou

**Comment by komega13** [comment]
J'ai viré la gestion auto des démons.
Ensuite je ne sais pas comment je peut stopper les démons ? Si je clique sur "désactiver" dans le cadre "état" je n'ai plus accès à la config zigate pour la réactiver AVANT de redémarrer abeille comme tu me le demandes .

**Comment by tcharp38** [comment]
Une fois la gestion auto desactivée, tu peux tenter de démarrer le demon puis l'arreter. Je crois que le bouton "stop" va reapparaitre.
Il y a clairement un cas tordu qui arrive de temps en temps mais je n'arrive pas à le saisir.

**Comment by komega13** [comment]
J'ai juste le bouton "(Re)démarrer" que j'ai utilisé plusieurs fois avec toujours le même message d'erreur "Aucune zigate active veuillez corriger"

C'est quoi ce "apache2 -k start" qui semble utiliser le port de la Zigate pour Abeille ? Le PID change à chaque fois...

J'ai supprimé Abeille puis re-installer depuis le market en version stable. Après activation lorsque je test le port ttyUSB0 pour la première fois j'ai eu ceci :
![fcc12](https://user-images.githubusercontent.com/7727919/148682647-cf47adff-3c2c-4333-aa28-31e9ce09489b.png)

**Comment by tcharp38** [comment]
Regarde la
![image](https://user-images.githubusercontent.com/35221038/148683570-34168941-83c6-4d2c-bc23-7f405f200027.png)
Aucune zigate n'est active. Ca ne peut pas fonctionner comme ca.
J avoue que je ne comprends pas ce qui se passe

**Comment by komega13** [comment]
Je vais tester avec le plugin Zigate pour voir si la clé est détecté je ne sais plus quoi faire...

EDIT : Aucun soucis avec le plugin Zigate

**Comment by tcharp38** [comment]
Appelle moi et on fait un teamviewer si tu veux. 0663630146

**Comment by tcharp38** [comment]
Salut @komega13 
Ou en es tu ?

**Comment by komega13** [comment]
Salut @tcharp38 je suis passé sur le plugin Zigate et tout s'est remis à fonctionné d'un coup. Ducoup j'ai refais tout mes scenario/virtuel avec les ID de ce plugin je me sens pas le courage et le temps de retenter abeille pour le moment mais merci pour ton support en tout cas si tu as besoin de log ou autre n'hesite pas à me demander

**Comment by tcharp38** [comment]
Ok pas de soucis. 
Si ca correspond à tes besoins tant mieux.
Je ne vais pas te faire perdre du temps si tu ne l utilises plus.
Je clos le sujet. A reouvrir si besoin.

**Comment by FlorianHergo** [comment]
Hello,

je n'avais pas vu ce thread : https://github.com/KiwiHC16/Abeille/issues/2332#issuecomment-1048773158
Exactement le même cas que la personne ci-dessus, et oui ca fonctionne aussi très bien sous Zigate.
Sauf que je peux pas ré-appairé les appareils donc je dois rester sous Abeille et retrouver ma config.

**Comment by tcharp38** [comment]
Salut @FlorianHergo 
Tes logs sont vides. Tu n'es pas en mode "debug". Et pense à changer le nombre de lignes à 5000 au lieu des 500 par defaut.
Voir https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

Sinon, demain il y a la nouvelle stable. Je ne pense pas avoir avancé sur ce sujet qui me chagrinne toujours mais sait on jamais.
Si le pb est toujours la, file moi le package de logs. Merci

**Comment by FlorianHergo** [comment]
Je lis ton lien et je m'en occupe tout de suite

**Comment by tcharp38** [comment]
Je pense à autre chose. On peut se faire une session TeamViewer ce soir pour regarder en direct. Ce pb m'intrigue car pas tout le temps visible. Mais a priori tu es aussi sur Freebox, qui semble une plateforme a provoquer le souci.
Si t es partant pour la session, contacte moi sur "tcharp38@laposte.net"

**Comment by FlorianHergo** [comment]
Je suis partant pour t'aider, j'aime bien ce plugin :) donc ok, mais avant 19h30 please

**Comment by FlorianHergo** [comment]
Mon retour :  

Mode debug : j'y suis bien 
![image](https://user-images.githubusercontent.com/8419725/155358317-e0d52c83-bcb4-4383-9fe3-442fd5c4edd9.png)


5000 : Done
![image](https://user-images.githubusercontent.com/8419725/155358595-cfa2d401-eac3-4e74-a7cc-19f6594972af.png)


redémarrage Abeille : Done.

nouveaux logs :  [AbeilleLogs-220223 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8125887/AbeilleLogs-220223.1.tar.gz)

**Comment by tcharp38** [comment]
Attention !! Timeline n'a rien a voir avec les logs

**Comment by tcharp38** [comment]
Je quitte le taf et rentre. Contacte moi par email et on fait le point d 'ici 30mins

**Comment by FlorianHergo** [comment]
corrigé : 
![image](https://user-images.githubusercontent.com/8419725/155359950-5e7cccc4-89f1-4e81-b261-3835d23edefa.png)

redémarrage Abeille : Done.
je recommence le teste de synchro : 
![image](https://user-images.githubusercontent.com/8419725/155360233-f1b52bfa-49ac-419a-9be4-310ebd4914d3.png)

```
[2022-02-23 17:08:06] Démarrage de 'checkTTY.sh'
[2022-02-23 17:08:06] Vérifications du port '/dev/ttyUSB0'
[2022-02-23 17:08:06] = ERREUR: Le port est utilisé par le process '1008'.
[2022-02-23 17:08:06] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
[2022-02-23 17:08:06] =         Details du process 1008:
[2022-02-23 17:08:06] =           PPid=672, cmd='/usr/sbin/apache2 -k start'
```

**Comment by FlorianHergo** [comment]
[AbeilleLogs-220223 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8126572/AbeilleLogs-220223.2.tar.gz)

**Comment by tcharp38** [comment]
@FlorianHergo 
Bon désolé mais tu n'as pas le choix. Ton FW est bien trop vieux. Comme je le mets dans la doc, la version 3.1E est au minimum requise mais tu devrais passer tout de suite en 3.21-LEGACY (pas OPDM sinon tu perds tous tes equipements).

Les erreurs que je vois dans le log viennent directement de l'age du FW.

Donc 
- sauvegarde ta Zigate
- mise à jour en 3.21-legacy SANS effacer l EEPROM
- et on refait le point.

**Comment by FlorianHergo** [comment]
Vraiment merci pour ce call. 
Pour ce thread, je te propose de le clôturer et de repasser sur l'autre ?

Pour les prochains qui parcourrai ce fil de discussion, mon problème à été corrigé rapidement, je n'avais pas mis "Activé" (cf N°1)  : 

![image](https://user-images.githubusercontent.com/8419725/155382870-b11549fd-fc93-464c-a6a1-20840e377323.png)
  
Suite à une sauvegarde, si on appuie sur "tester" ou "Démarré", cette fois-ci plus d'erreur, et la Zigate est bien trouvé sur le port : TTYusb0

**Comment by tcharp38** [comment]
Tu as sauvegardé la flash et l'EEPROM c 'est ca ?

**Comment by FlorianHergo** [comment]
Non, c'est toi qui l'a fait dès le début de la visio, la clef était bien en 3.1C et j'avais juste oublié de mettre "activé" en bas.
Et donc le soucis de port à été réglé comme cela. Ce qui ne corrige pas le soucis de fond où je dois mettre à jour comme tu me l'a expliqué.

**Comment by tcharp38** [comment]
oui dans ton cas le pb a disparu avec
- Zigate status => activée
- puis bouton sauvegarder

**Comment by tcharp38** [comment]
Je ferme cet antique sujet
A réouvrir si besoin
