### ISSUE TITLE
ZiGate ne transmet pas les demandes On Off Toggle

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#226]
Ampoule Ikea en c551.
Elle était sur une autre adresse hier et même comportement.
On et Off ne sortent pas sur la radio. 
Ampoule en position T2 sur la terrasse en bordure de cellule radio probablement.

```
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]Msg Received: Topic: {CmdAbeille/c551/OnOff} => On
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]Type: CmdAbeille Address: c551 avec Action: OnOff
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]OnOff for: c551 action (0:Off, 1:On, 2:Toggle): 01
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]Dest: /dev/ttyUSB5 cmd: 0092 len: 0006 datas: 02c551010101
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]len data: 12
AbeilleMQTTCmd 2018-04-06 09:09:09[DEBUG]checksum computed: 3
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]Msg Received: Topic: {CmdAbeille/c551/OnOff} => Off
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]Type: CmdAbeille Address: c551 avec Action: OnOff
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]OnOff for: c551 action (0:Off, 1:On, 2:Toggle): 00
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]Dest: /dev/ttyUSB5 cmd: 0092 len: 0006 datas: 02c551010100
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]len data: 12
AbeilleMQTTCmd 2018-04-06 09:09:11[DEBUG]checksum computed: 2

```

Par contre le Toggle sort bien sur la radio:

```
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]Msg Received: Topic: {CmdAbeille/c551/OnOff} => Toggle
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]Type: CmdAbeille Address: c551 avec Action: OnOff
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]OnOff for: c551 action (0:Off, 1:On, 2:Toggle): 02
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]Dest: /dev/ttyUSB5 cmd: 0092 len: 0006 datas: 02c551010102
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]len data: 12
AbeilleMQTTCmd 2018-04-06 09:09:12[DEBUG]checksum computed: 0
```

alors que les commandes envoyées sont similaires.

Dans certain cas quand je demande un On sur Jeedom je trouve un Toggle sur la radio alors que le write USB est 01, soit On.

Pour joindre c551 (T2), ZiGate passe par DC15 (T1): le probleme est visible. Plus tard dans les tests la ZiGate adresse directement le c551 et le probleme est toujours la.

Un reset de la ZiGate depuis ruche ne resoud pas le probleme.

Je n'ai pas le probleme sur l ampoule 7714 (Bonne reception radio/meme pièce).
Je ne retrouve pas le meme probleme sur les autres ampoules. Le message est toujours envoyé sur la radio.

Un reset HW (Debranche/branche) de la ZiGate ne resoud pas le problème.

Un reset complet de de Jeedom ne resoud pas le probleme.

Si je fais un On/Off sur une ampoule 6766 et fait de meme sur c551 alors le message radio est pour 6766 !!!

La ZiGate est visiblement en vrac et je ne sais pas comment reprendre la main.

Je vais voir si je peux recuperer le PDM et le lire.

**Comment by KiwiHC16** [comment]
Je clos ce point qui est probablement très spécifique à cette ampoule. Je vérrai le jour ou je l utilise de nouveau.

**Comment by sagitaz** [comment]
Bonjour,

Problème identique sur une Ikea Color E27.
