### ISSUE TITLE
Est ce compatible ?

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2261]
Bonjour,

Je créé une nouvelle issue pour mettre des liens concernant du matériel avec le protocole zigbee afin de connaitre la compatibilité avec Abeille.

Je commence avec ceci que je n'ai pas vu dans la liste d'équipement compatible et qui m'intéresse. Merci

https://fr.aliexpress.com/item/1005002233911562.html?spm=a2g0o.detail.1000014.20.2be13f8cLmArVQ&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.33416.213724.0&scm_id=1007.33416.213724.0&scm-url=1007.33416.213724.0&pvid=d5c6abff-cfd2-40fd-991d-7bf6f545babf&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.33416.213724.0,pvid:d5c6abff-cfd2-40fd-991d-7bf6f545babf,tpp_buckets:668%232846%238109%231935&pdp_ext_f=%7B%22sceneId%22:%2223416%22,%22sku_id%22:%2212000019451371444%22%7D&compareFields=formatted_price:%E2%82%AC%209,72;itemId:1005002233911562;freight_formatted_price:null;source:recommend-sku-FR;is_freeshipping:null;trade_order:89

**Comment by tcharp38** [comment]
@Seby9576 
Impossible de répondre comme ca. 
Dans le monde du zigbee et surtout parmis les module d 'origine Chinoise, c est tout et n'importe quoi.
Je dirais que ces modules sont supportés mais encore faut il verifier comment ils s'identifient.
Idéalement il faut trouver l'identifiant zigbee correspondant pour savcoir si c est supporté.

**Comment by Seby9576** [comment]
Je vais en acheter un et je verrais bien. Merci

**Comment by tcharp38** [comment]
Ok. Je clos le sujet.
Rien ne t empeche de le reouvrir quand tu as ton equipemeent et changer le titre.
