### ISSUE TITLE
Ajout - Bouton Xiaomi Mural - switch.b1nacn02

### ISSUE THREAD

**Issue by cochise57** [KiwiHC16/Abeille#2262]
Bonjour,
Je souhaiterai savoir si il vous serait possible d'ajouter la référence switch.b1nacn02 (qui est équivalent à switch.l1aeu1).
Je vous joint le discovery généré.

Cordialement,
Anthony BREDA
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7835756/discovery.zip)

**Comment by tcharp38** [comment]
Salut @cochise57 
Quel le modele/ref ?

A tester
[switch.b1nacn02.zip](https://github.com/KiwiHC16/Abeille/files/7836182/switch.b1nacn02.zip)

**Comment by cochise57** [comment]
Salut @tcharp38 
C'est un Xiaomi Aqara Wall switch D1 (CQC17003181848).

Tout est fonctionnel, j'ai également rajouter l'action toogle, présent sûr switch_b2nacn02 (ressemblant fortement)

"Toggle": {
    "use": "zbCmd-0006-Toggle",
    "isVisible": 1
},

Il faudra également changer l'icone :-)

Cordialement,
Anthony

**Comment by tcharp38** [comment]
Concernant l icone y  a t il une image correspondante deja dispo ?
Sinon je te laisse trouver un PNG sans fond.

**Comment by cochise57** [comment]
/plugins/Abeille/images/node_XiaomiButtonSW861.png (Xiaomi Interrupteur Carré Simple)
C'est pas le modèle exact mais je pense que cela peux convenir.

Cordialement,
Anthony

**Comment by tcharp38** [comment]
Ok, tant que l'aspect visuel est correct ca le fait. Je corrige pour la prochaine beta.
Sinon tout est ok ? Y compris le report de batterie ?

**Comment by cochise57** [comment]
Salut @tcharp38,
Désolé de ne pas avoir répondu, j'ai pas eu la notification. Oui tout est OK. L'interrupteur étant relié au réseau électrique, il n'y a pas de  remontée de baterie.
Cordialement,
Anthony

**Comment by tcharp38** [comment]
Ha oui effectivement pas de batterie sur ce device :)
Bon je clos alors.
