### ISSUE TITLE
Mode inclusion impossible -- Jeedom -- Plug Abeille

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#2269]
Bonjour à tous,
@tcharp38 

J'ai fait fait un upgrade du firmware de la ZIGATE vers la dernière version. Comme d'habitude (un peu lourd ;-) ), j'ai été obligé de relancer une inclusion des différents équipements. Cela a été pour une grande partie mais il m'en reste une petite dizaine et là il n'y a plus moyen. 
La zigate clignote normalement lors de la mise en inclusion. Lorsque je mets l'EQ en mode appairage, je vois que la clef réagit mais par contre l'EQ ne confirme pas la liaison. Rien ne se passe non plus au niveau du Jeedom.

Par contre, pour les équipements déjà réintégrés je peux les piloter sans problème. Le problème est lié plusieurs marques et les premières inclusions ont fonctionné correctement également avec plusieurs marques d'EQ.

Est-ce que le problème peut venir de Abeille ou directement de la clef Zigate ?

J'ai testé ceci:
Relancer la box domotique
Couper complètement l'alimentation de la box
Relancer les demon

Merci d'avance.

**Comment by tcharp38** [comment]
Salut

Peux tu me dire dans quelle version (legacy ? OPDM ?) tu etais et vers quoi tu as migré ?
Quelle zigate ? v1 ? v2 ?
Comment as tu procédé pour la mise à jour du FW ?

**Comment by ChrisChrisChri** [comment]
Re,

La version de la clef USB est la version rouge. Version LEGACY 3.21 installée . J'avais la version .d avant le flash via le programme flashprogrammer. 
Procédure suivie: j'ai flashé la clef sans effacer l'EEPROM. J'ai rallumé ensuite la boxe domotique. J'ai commencé mon inclusion avec du IKEA, NIKO, Aqara,...et pas de soucis. 
Hier soir, par contre plus moyen.

Merci.

**Comment by tcharp38** [comment]
Donc clef USB v1: tu es passé de 3.1d a 3.21-legacy sans effacer EEPROM.
Ca semble correct.

Quand tu retentes une inclusion, file le package de logs qu'on y jette un oeil.

**Comment by ChrisChrisChri** [comment]
Je viens de refaire une tentative d'inclusion pour l'EQ 82F. 3 essais.
Voici le fichier
[AbeilleLogs-220119.tar.gz](https://github.com/KiwiHC16/Abeille/files/7898694/AbeilleLogs-220119.tar.gz)
.
Merci.

**Comment by tcharp38** [comment]
Je ne vois aucune "device announce" ni aucun message de "82F". Je suppose que tu faisais allusion a 82FC d'ailleurs (Sonde bureau) mais rien en 82FC non plus.

Tu as un souci avec E943/Gestion pompe qui semble ne plus repondre.

Parmis les equipements qui te manquent, y en a t il qui ne passent pas par un routeur ?

**Comment by ChrisChrisChri** [comment]
Oui ceux qui manquent sont ceux qui n'ont pas encore été réintégrés. En effet, il s'agit bien du 82FC.

J'ai oublié de dire que j'avais fait également le test en déplaçant avec les EQ à côté de ma clef zigate (30 cm) pour éliminer le problème d'un routeur. Cela ne donne rien de plus.

Tu penses que je dois reflasher la clef ?

**Comment by tcharp38** [comment]
Tu as donc du refaire tous les appairages jusque la  n est ce pas ?
Si c'est le cas ca sent pas bon mais pas surprenant quand meme :(

Auquel cas le + propre, reflasher en 3.21-OPDM + erase EEPROM, et tu refais tous les appairages.
Désolé pour cette nouvelle. Je dois m'y coller aussi d'ailleurs.

**Comment by ChrisChrisChri** [comment]
Ok. Il faudra bien...C'est quoi la différence entre la version LEGACY et OPDM ? L'équipe ZIGATE ne pourrait pas penser à un autre moyen, par exemple via Jeedon, pour mettre à jour sans devoir tout débrancher ?
Le plus lourd, c'est quand tu as des modules intégrés style legrand derrière un interrupteur.

**Comment by tcharp38** [comment]
La version "legacy" etait le premier format de table interne qui a subit de nombreuses evolutions.
Avec la version "OPDM" ils ont essayé de rendre les choses + "maitrisées", donc plus robustes (moins de corruptions) et ils ont optimisé cette table permettant + d'équipements.

Je suis bien d'accord avec toi. C'est hyper lourd. Aucun moyen de reconstruire un reseau sans tout recommencer de 0 ou de sauver le reseau pour restauration eventuelle. La stack de base qui est le fond de la zigate est une vraie daube. 
Mais je ne connais pas le status des autres clefs, que j'espere + "serieux".

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Tu en es ou ?

**Comment by ChrisChrisChri** [comment]
Salut,
Comme tu me l'avais dit, j'ai reflashé en OPDM et j'ai réussi à réintégrer la totalité. Il ne me reste que les modules dans les murs et les télécommandes mais je pense que ça devrait aller....
Je peux clôturer le sujet
