### ISSUE TITLE
ORVIBO CM10ZW non reconnu (id = 396483ce8b3f4e0d8e9d79079a35a420, ORVIBO)

### ISSUE THREAD

**Issue by thibault-78** [KiwiHC16/Abeille#2275]
Bonjour,
Je n'arrive pas à appairer correctement mon ORVIBO CM107ZW à jeedom:
-> Le message d'erreur est : Nouvel équipement détecté mais non supporté. Création en cours avec la config par défaut (defaultUnknown). Rafraîchissez votre dashboard dans qq secondes.
Il me semblait pourtant que le travail avait été fait pour le rendre compatible : https://github.com/KiwiHC16/Abeille/issues/2024
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/7918315/discovery.zip)
En PJ le discovery
Est ce que vous pouvez m'aider?
Merci par avance
Thibault

**Comment by tcharp38** [comment]
Salut
Le discovery signale qu'il s'identifie comme un autre module.
Sa ref est bien CM10ZW ? Tu as aussi marqué CM107ZW.

**Comment by thibault-78** [comment]
La ref est bien CM10ZW 
J'ai bidouillé le fichier que tu avais fait dans le https://github.com/KiwiHC16/Abeille/issues/2024 avec la valeur trouvé dans le discovery "396483ce8b3f4e0d8e9d79079a35a420" car pour moi c'est le même modèle
il est tout juste inclus dans jeedom et mes premiers tests semblent fonctionner : je n'utilise que 2 relais

**Comment by tcharp38** [comment]
Ok dans ce cas tu ajoutes juste "alternateIds" comme suit dans le fichier "82c167c95ed746cdbd21d6817f72c593_ORVIBO.json". Ca devrait le faire.

>     "82c167c95ed746cdbd21d6817f72c593_ORVIBO": {
>         "alternateIds": "396483ce8b3f4e0d8e9d79079a35a420_ORVIBO",
>         "manufacturer": "Orvibo",

Je pousse cette modif pour la prochaine beta.

**Comment by thibault-78** [comment]
Merci beaucoup pour le support
J'ai fait ta modif en retirant mon fichier
Il est bien reconnu par le bon JSON :)

**Comment by tcharp38** [comment]
Voir 220123-BETA-1, dispo le 24/1

Je te laisse confirmer que tout est ok sur cette beta. Comme ca on peut clore le sujet.
Merci

**Comment by Jake309** [comment]
Salutation =)

J'ai acheté ce modul ce week end, il vient d'être livré, j'étais tout fou de voir qu'il était déjà dans abeille.
Ca c'est joué à quelque jour ^^
Je vais regarder pour l'installer dans les prochaines semaines, je vous fais un retour s'il y a des bug

Merci @tcharp38 pour le taff et la dispo =), je peux pas en dire autant de moi quand on échange :/

**Comment by tcharp38** [comment]
@thibault-78 
Ca dit quoi ?

**Comment by thibault-78** [comment]
Hello @tcharp38 
Je n'ai pas fait le test :(
Mon Jeedom est en mode stable 
Est ce que tu penses que c'est grave de la mettre dans la prochaine stable sans plus de test?
Sinon je ferai le test le WeekEnd prochain

**Comment by tcharp38** [comment]
Pas d'urgence. Le point reste ouvert.
Les modifs seront dans la future stable de toute façon mais du coup non confirmées.

**Comment by tcharp38** [comment]
Pour info, si zigate v2, le pb est peut etre lié à ce point: https://github.com/KiwiHC16/Abeille/issues/2368#

**Comment by tcharp38** [comment]
@thibault-78 
Je clos le sujet mais à réouvrir si besoin.

Il y a eu la 220406-STABLE-1 depuis et une nouvelle stable devrait tomber d'ici la semaine prochaine.
