### ISSUE TITLE
Scene switch TS004F, _TZ3000_xabckq1v

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2278]
Bonjour,

Je viens de recevoir ce module 4 poussoirs zigbee. Pour l'inclusion j'ai appuyé sur le bouton en bas a gauche et c'est bien inclus dans abeille et semble être déjà connu
![image](https://user-images.githubusercontent.com/77990298/150835246-120c90de-bdca-4b99-9b15-8211a2d941c8.png)

Le soucis c'est que j'ai seulement le click 4 qui se met à jours même si je touche aux autres. Est ce que j'ai mal inclus l'appareil ?

Merci

**Comment by tcharp38** [comment]
Peux tu me filer un package de logs pendant l'inclusion ?
Autre question: quelle est la ref exacte fabricant sur l etiquette ? Je me demande si le sujet n'est pas le meme que #2155

**Comment by Seby9576** [comment]
Salut,
Voici les logs, J'ai du faire ca lundi en fin de journée
Pour le ref c'est la marque MOES et la ref c'est scène switch. Par contre il est exactement comme sur la photo. Merci

[AbeilleLogs-220126.tar.gz](https://github.com/KiwiHC16/Abeille/files/7945207/AbeilleLogs-220126.tar.gz)

**Comment by tcharp38** [comment]
En lien avec #2155 je pense.
Quelle ref sur l etiquette vers la pile ? ESW-OZBA-EU ? ou ESW-OZAA-EU ?

**Comment by Seby9576** [comment]
ESW-OZAA-EU

**Comment by tcharp38** [comment]
[TS004F__TZ3000_xabckq1v.zip](https://github.com/KiwiHC16/Abeille/files/7945484/TS004F__TZ3000_xabckq1v.zip)
Tiens, ecrase le fichier avec celui la
puis page EQ/avancé => reinitialiser
fais un essai avec un autre bouton que click 4
et file moi le package de logs

merci

**Comment by Seby9576** [comment]
24AD / 847127FFFEE7A136
[AbeilleLogs-220126 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/7945616/AbeilleLogs-220126.1.tar.gz)

**Comment by Seby9576** [comment]
Salut,

Pour information avant le changement du fichier pour moi les 4 boutons fonctionnaient mais seul click 4 se mettait à jours mais là il semblerait que seul le touche 1 fonctionne (haut gauche) mais toujours click droit qui se met à jours
Je sais pas si je suis claire.
![image](https://user-images.githubusercontent.com/77990298/151430068-365930ce-4ecb-40e3-994a-28209a2844db.png)

**Comment by Seby9576** [comment]
Je confirme dans le log seul le click 1 remonte des informations
![image](https://user-images.githubusercontent.com/77990298/151661585-eb739a2e-57d4-4b76-8cd4-7de96b67aaf8.png)

**Comment by tcharp38** [comment]
Je vois toujours le click venant du EP 01 donc "Click 4".
Les autres message "Unknown... " dont tu parles sont normaux. Juste d'autres moyens de passer la meme commande.

En regardant le net j'ai l'impression que la disposition est la suivante

1 2
3 4

En ligne avec ca ?

Peux tu faire un click sur chacun et noter l'heure, et me filer le log AbeilleParser dans la foulée ?

Penses à basculer sur la beta du 29/1 donc dispo aujourd hui.

**Comment by Seby9576** [comment]
Salut,

Non j'ai fait un clic et j'ai voulu te donner les retours. 
Je suis en ligne avec l'ordre des boutons

J'ai fait dans l'ordre 1,2,3,4. J'ai vider abeilleparser donc tu devrais avoir que les 4 clics mais de ce que je peux voir seul le clic 1 ressort quelque chose
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7972585/AbeilleParser.log)

**Comment by jbromain** [comment]
> ESW-OZAA-EU

Hello, pour être sûr, tu as bien regardé la ref sur l'étiquette à coté de la pile, et non celle inscrite au dos de l'équipement ? Car sur mon exemplaire, j'ai ESW-OZAA-EU sur le plastique (couvercle de la pile) et ESW-OZBA-EU à l'intérieur (sur la carte électronique).

Comme tes symptômes sont exactement comme moi (#2155), je suis étonné de ne pas avoir la même ref que toi.

**Comment by Seby9576** [comment]
Salut,

Mince tu as raison, sur la carte c'est ESW-OZBA-EU. Désolé

**Comment by jbromain** [comment]
Ok, c'est plutôt rassurant finalement. 
Nos équipements sont donc exactement les mêmes et se comportent pareil. 

@tcharp38, il faut peut-être clôturer une des deux issues ? A ta convenance ;)

Est-ce qu'il est possible que l'équipement envoie des choses à la Zigate et que celle-ci ne les forwarde pas à Abeille ?

**Comment by Seby9576** [comment]
C'est con que je ne sois pas au point sur tous ce qui est plugin, le pauvre @tcharp38  semble bien seul a développer abeille.

**Comment by tcharp38** [comment]
Hello. Désolé pour mon silence.

Pour info je ne suis pas le developpeur d'Abeille. C'est KiwiHC16. Je ne fais que reprendre le support etant utilisateur moi meme, mais dans le but d'en faire de - en -.. bref que ca soit robuste et que les outils pour ajouter des modeles soient la.

J'ai fermé le point #2155 qui parle du meme sujet.

Si j'essaie de résumer (et je compte sur vous pour corriger)
- 2 modeles de scene switch qui s'identifient de la meme maniere ([TS004F, _TZ3000_xabckq1v)
- 2 refs: ESW-OZBA-EU (support NOK) & ESW-OZAA-EU (support ok)
- 1 seul bouton repond sur la ref ESW-OZBA-EU

C'est bien ça ?

**Comment by Seby9576** [comment]
Salut,

Avant ta maj mes 4 boutons répondaient bien mais c'était toujours le 4 qui se mettait à jours. Maintenant effectivement il y a que le 4

**Comment by tcharp38** [comment]
"les 4 boutons repondaient mais toujours le 4 mis à jour".
Je ne pige pas comment tu peux dire ca. Tu peux reformuler ?

Le souci actuel est qu'on ne recoit AUCUNE info pour les autres boutons, en ne regardant que le parser (ce qui arrive du reseau). Tu dis qu'avant on recevait les 4 infos ?

**Comment by Seby9576** [comment]
Au début si j'appuyais sur le bouton 1,2,3 ou 4 dans abeille c'était toujours le click 4 qui affichait ce que j'avais fait (court,double,long)

**Comment by tcharp38** [comment]
Donc les 4 boutons remontaient la meme info, comme si il n'y avait qu'un seul bouton.

Bon j'ai aussi l'impression que cette histoire va durer tellement je patauge à distance.
L'un de vous peut m'envoyer cet equipement si il ne sert pas ? Ca sera j'espere + facile pour trouver la combine.

**Comment by Seby9576** [comment]
Oui ou l'info ne remontait pas au bonne endroit.

**Comment by tcharp38** [comment]
Je ne vois pas comment c'est possible.
Du coup pour moi 
- avant: le switch etait dans un mode ou il repond la meme chose sur tous les boutons
- maintenant: il est dans un mode ou seul le bouton 1 repond

Tu peux refaire un essai en supprimant du JSON la partie suivante qui change le fonctionnement par defaut

            "Change config": {
                "use": "zbWriteAttribute",
                "params": "clustId=0006&attrId=8004&attrType=30&attrVal=01",
                "execAtCreation": "Yes"
            },

**Comment by Seby9576** [comment]
seul le bouton 1 fonctionne et met à jours le click 4

**Comment by tcharp38** [comment]
Bon désolé. J'ai l 'impression qu'on tourne en rond et c'est pas efficace du tout.
Seule solution pour progresser la dessus est que j'ai ce modèle le temps nécessaire.
Ha moins que @jbromain ai d'autres pistes.

**Comment by jbromain** [comment]
De mon côté je suis au bout de mes capacités, mais toi tu y arriveras peut-être avec l'équipement 🤞

Je peux te l'envoyer pour les tests, de toute façon je ne m'en sers pas. Et si tu y arrives je serai curieux de connaître ta démarche de recherche, pour pouvoir y arriver tout seul la prochaine fois 😅

Tu peux m'indiquer ton adresse pour l'envoi stp ?

**Comment by tcharp38** [comment]
Merci @jbromain 
Je vais eviter de laisser toutes mes coordonnées sur le forum alors envoi moi un mot sur 'tcharp38@laposte.net'.

J'essaierai de résumer mon process et mes resultats des que je trouve le temps de m'y coller.

**Comment by tcharp38** [comment]
Memo
- Moes, Wireless Scene Switch 21/41, ESW-OZBA-EU
- Appairage: maintenir bouton 3 (en bas a gauche) jusqu'a ce que les 4 boutons clignotent.
- Bouton 2 + 4 maintenus jusqu'a flash bouton 3 => changement de mode
  Attribut 8004 cluster 0006 change de valeur (0 > 1 > 0...).
- Disposition
  1 2
  3  4

**Comment by tcharp38** [comment]
Juste pour expliquer le process, la il ne s'agit pas de pb "zigbee". Le comportement particulier de beaucoup de device passe par des clusters dit "privés". Autrement dit le fabricant (ici Tuya) fait ce qu'il veut.
La seule solution dans ce cas est du reverse engineering en sniffant ce qui se passe avec une passerelle/appli officielle Tuya.

Bref encore du temps passé et finalement avec la confirmation de Pipiche38 (Domoticz), ce modèle est enfin supporté.
Il faut une sequence d'initialisation assez tordue avant qu'il "tombe en marche".

@Seby9576 
Peux tu confirmer le fonctionnement avec ce modele ci joint ?
[TS004F__TZ3000_xabckq1v.zip](https://github.com/KiwiHC16/Abeille/files/8104674/TS004F__TZ3000_xabckq1v.zip)

- Ecraser le fichier identique (core/config/devices/TS004F__TZ3000_xabckq1v/TS004F__TZ3000_xabckq1v.json)
- Refaire une inclusion
- Et tester
-

**Comment by Seby9576** [comment]
Salut,

Bon ca fonctionne mais pour que ca marche j'ai du supprimer le device car sinon j'ai pas eu de message de maj device et toujours pas fonctionnel
J'ai supprimer et fait l'inclusion (bouton 3 jusqu'à clignotement) mais la toujours rien, ensuite j'ai fait ton 2+4 et la j'ai eu le message et tous les boutons sont ok

Veux tu que je recommence pour voir si c'est la bonne procédure ?

![image](https://user-images.githubusercontent.com/77990298/155007662-7f083178-a68a-4227-a33e-481538a82c2f.png)

**Comment by tcharp38** [comment]
2+4 c est pour changer de mode. On ne doit pas le faire normalement. Le modele s en charge.                                                                                                                                                                                                                                                                                                                                                                                      
Comme pas de logs je vois pas ce qui à merdé avec ton cas.
Tu peux refaire une inclusion, mettre le log de coté, et verifier que tout est ok ?

**Comment by Seby9576** [comment]
OK je fais ça demain

**Comment by Seby9576** [comment]
C'est ouf , j'ai fait l'inclusion et ok pas même si on fait pas le 2+4. Mais par contre ce n'est plus dans l'ordre ce qui n'est pas grave en sois vu qu'on peut remettre dans l'ordre et éditer les nom.
bouton 1 -> click 4
bouton 2 -> click 3
bouton 3 -> click 1
bouton 4 -> click 2

[AbeilleLogs-220222.tar.gz](https://github.com/KiwiHC16/Abeille/files/8115115/AbeilleLogs-220222.tar.gz)
s

**Comment by tcharp38** [comment]
L'ordre est basé sur la disposition suivante, qui semble assez logique par ailleurs.

1 2
3 4

Tu nommes pas les boutons comme ca ?

**Comment by Seby9576** [comment]
Oui moi aussi mais dans cette ordre de bouton sur j'appuyais sur le bouton 1 j'avais le click 4 qui se mettait à jours etc. Ce qui n'était pas le cas lors de la première inclusion. Sinon ca fonctionne très bien en changeant le noms de clicks (retour info dans abeille)

**Comment by tcharp38** [comment]
Hello @Seby9576 @jbromain 
On peut clore ce sujet ou il reste qqch en attente ?

**Comment by jbromain** [comment]
Hello, je n'ai pas eu le temps de mettre à jour pour re-tester, mais je pense que tu peux clore, au pire on rouvrira ;)

Merci

**Comment by Seby9576** [comment]
Salut,

Oui c'est good, par contre l'ordre des touches n'est pas toujours pareil après une inclusion. Il suffit juste de remettre dans l'ordre et de renommer. 
Merci tcharp

**Comment by tcharp38** [comment]
@Seby9576 
L'ordre n'est pas toujours pareil ?! Comment est ce possible ?
C est fixé dans le modèle donc ca ne peut pas changer.

**Comment by Seby9576** [comment]
Non pas toujours dans le même ordre. après te dire comment c'est possible je ne sais pas.

**Comment by tcharp38** [comment]
Est ce possible que le premier ordre etait celui que tu avais bidouillé et le second toujours le meme ?

**Comment by Seby9576** [comment]
j'ai du le faire 3 fois voir 4 et le dernier n'était toujours pas dans le bonne ordre mais comme je t'ai dit ca ce change après donc pas de soucis

**Comment by tcharp38** [comment]
Bon je pige pas mais comme il y a une solution et trop de soucis qui s empilent je clos le sujet.
A reouvrir si reels soucis.
