### ISSUE TITLE
Jeedom 4.2.7: Impossible d'affecter un groupe à une ampoule

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2284]
Version Abeille: 220108-STABLE-1

Kernel: ["Linux JEEDOM-DEBIAN 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU\/Linux"]

Zigate 2: 0005-0321

Depuis la version stable de Jeedom 4.2.7, il n'est plus possible d'ajouter un groupe à une ampoule (par exemple). La sécurité mise en place dans la 4.2.7 empêche l'action

![image](https://user-images.githubusercontent.com/36518012/151860937-dd125a83-abf5-4fee-9ecc-61aac89e51bf.png)
![image](https://user-images.githubusercontent.com/36518012/151860988-a4286a39-8391-4725-a734-3434fd78b93b.png)

**Comment by tcharp38** [comment]
Master a tester pour controle des groupes.
Pas touché les autres points encore mais ca impacte aussi les
- remplace
- rehome
- replacezigate

**Comment by tcharp38** [comment]
@mickadam29 Ca dit quoi maintenant ?

**Comment by pixeldesbois** [comment]
Hello,
Je suis en version stable 2022-01-09 01:00:16 et j'ai le même pb.
Veux-tu que je me mette en beta pour te faire un retour ?

**Comment by mickadam29** [comment]
Chez moi hier c’était ko. Je teste demain

**Comment by tcharp38** [comment]
@mickadam29 
Quand tu dis ko, c'est la meme erreur (forbidden) ou autre chose ?

@pixeldesbois 
J'ai cru comprendre que tu avais deja des soucis alors pour l instant reste sur ta stable.

**Comment by pixeldesbois** [comment]
Ok ca marche. Dis moi si il y a  besoin d'aide, logs etc...

Le 08/02/2022 à 12:58, Tcharp38 a écrit :

**Comment by mickadam29** [comment]
Oui, tjs interdit

**Comment by tcharp38** [comment]
@mickadam29 
Tu devrais avoir ce visuel si sur la bonne version.
![image](https://user-images.githubusercontent.com/35221038/153022879-860d8ba9-924c-45d7-a5a6-236f00841193.png)

Que fais tu pour obtenir ce "forbidden" ?

**Comment by mickadam29** [comment]
Dans ce cas j’ai pas testé sur la bonne machine 😓 le boulet
Je te redis ça demain

**Comment by mickadam29** [comment]
Ça marche sur cette version
Ajout/suppression groupe

**Comment by mickadam29** [comment]
Fonction avec la dernière beta
