### ISSUE TITLE
Affichage des ports en "alias"

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2286]
![Capture d’écran 2022-02-01 à 13 07 43](https://user-images.githubusercontent.com/8549674/151965747-b9a97af2-b8af-4338-a066-500bb4ba3d39.png)

**Comment by KiwiHC16** [comment]
En fait il me desactive les zigates !!!
![Capture d’écran 2022-02-01 à 13 09 04](https://user-images.githubusercontent.com/8549674/151965937-657e8d3e-4e05-47fe-a862-6e85955f0524.png)

**Comment by KiwiHC16** [comment]
```
                    foreach (ls('/dev/', 'tty*') as $value) {
                        echo '<option value="/dev/'.$value.'">'.$value.'</option>';
                    }
```
Mis en commentaire dans le code !!!

**Comment by KiwiHC16** [comment]
Correction faite dans le master.

**Comment by tcharp38** [comment]
@KiwiHC16 
J'avais commenté ca pour eviter de proposer une liste de ports inutiles.
On utilise maintenant le retour de Jeedom, getUsbMapping + true.

J'ai eu du mal à piger le lien avec ton souci mais j entrevois la cause. Je garde ca ouvert pour revue.

Le port USB que tu utilises n'etait pas dans la liste ?

**Comment by KiwiHC16** [comment]
Le problème est que si tu as plusieurs zigates ou équipements usb, tu vas avoir /dev/ttyUSB0, /dev/ttyUSB1, ...2,... 3, ...4,...5 comme moi par exemple, et si tu changes l ordre des devices connectés en USB ce qui était ttyUSB0 peut devenir ttyUSB2, etc
Donc j ai ajouté des règles pour créer des liens qui pointent vers les bons équipements. Par exemple un lien /dev/Zigate1 qui pointera sur le device /dev/ttyUSBx qui va bien.

J utilise le serial number du dongle USB pour créer les liens:
```
# /etc/udev/rules.d/88-usb-serial.rules

# FTDI USB-SERIAL
SUBSYSTEM=="tty", ATTRS{serial}=="A50285BI", SYMLINK+="ttyLinkZigate5", MODE="0777"
SUBSYSTEM=="tty", ATTRS{serial}=="A13XPJV",  SYMLINK+="ttyLinkRFXCom",  MODE="0777"
SUBSYSTEM=="tty", ATTRS{serial}=="AC3ZDO7G", SYMLINK+="ttyLinkSMS",     MODE="0777"
SUBSYSTEM=="tty", ATTRS{serial}=="004EM6LB", SYMLINK+="ttyLinkZigate3", MODE="0777"
SUBSYSTEM=="tty", ATTRS{serial}=="003F8XEN", SYMLINK+="ttyLinkZigate1", MODE="0777"
```

**Comment by tcharp38** [comment]
Ok pigé. 
Du coup je n'affichais plus les ports utilisés en "alias" car inconnus.
Mais ptet qu'il y a moyen de les ajouter aussi.

Du coup il y a des ports qui s'affichent en + chez toi donc, sauf erreur,
- ttyLinkZigate5
- ttyLinkRFXCom
- ttyLinkSMS
- ttyLinkZigate3
- ttyLinkZigate1

Et tu selectionnes l'un d'eux. C'est ca ?

**Comment by KiwiHC16** [comment]
Oui. Je leur donne un nom du style 'ttyLinkXXXXX' 
XXXX etant un texte à choisir en fonction des besoins.

**Comment by edgd1er** [comment]
Pour docker,j'ai une solution mais qui n'a été testée qu'avec une seule zigate.
Context:
parfois ma zigate disparait puis revient avec un autre nom (USB1-> USB2), USB1 étant vérrouillé par le conteneur.

J'ai un script qui scan les dev/ttyUSB pour ce vendorId et si ce n'est pas celui attendu, le conteneur est arreté, j'envoie un reset sur le port usb en erreur et le kernel le réattribue à celui attendu: USB1.

Ce script peut avoir trois inconvénients:
* etre sous docker, besoin de faire un start stop du coneneur
* le script ne peut etre inclus dans Abeille, puisqu'il tourne sur la machine hote.
* le script n'est pas testé avec plusieurs zigates.

**Comment by KiwiHC16** [comment]
Je n ai pas ce soucis de perte en cours de route.
Je crée les liens sur le host et dans Docker au démarrage.
Il faut un script qu on ne peut pas etre dans Abeille serait trop compliqué.
