### ISSUE TITLE
[KiwiHC16] Master du 2/2/2022, prepareCmd() erreur

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2287]
![Capture d’écran 2022-02-01 à 13 18 53](https://user-images.githubusercontent.com/8549674/151967155-0b04a504-228a-43dd-b3b1-95d0e578a979.png)

**Comment by tcharp38** [comment]
Besoin du log AbeilleCmd associé pour voir le coupable :(

**Comment by tcharp38** [comment]
Message d'erreur amélioré et dans le master.
A noter que depuis peu une erreur dans le log AbeilleCmd est reportée en message d'erreur user donc il se peut que ce soit une vieille erreur qui trainait.

**Comment by KiwiHC16** [comment]
Je ne l a vois plus dans le master. Je clos.
