### ISSUE TITLE
Xiaomi aqra double switch : what can I do?

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#229]
to help for integration? I guess there is already a tuto to help, but just where?

![image](https://user-images.githubusercontent.com/2912752/38470539-9c5fbeca-3b64-11e8-8445-7698022d19aa.png)

**Comment by KiwiHC16** [comment]
Have you seen #180 ?
I have one on my desk for test. There are 4 models a least. Do you have the reference ?
Put Abeille in semi-automatic mode, do the inclusion and share the AbeilleParser.
First thing is to get the name of the switch.

**Comment by handfreezer** [comment]
ok, this is the same subject. this issue is a duplicate, so closing.
