### ISSUE TITLE
Inclusion no longer works bee 220108-STABLE-1 zigate v1 0004-0321

### ISSUE THREAD

**Issue by peporl** [KiwiHC16/Abeille#2293]
Hello,

Has anyone encountered this problem.

I updated the bee plugin and the zigate firmware, erase the pdm recreated the hive but no way to make an inclusion. the zigate flashes well but the peripherals are no longer recognized.

Thanks in advance

Joseph

**Comment by tcharp38** [comment]
Hello @peporl 
Which device are you trying to pair ?
Moreover, can you enable "debug" mode, restart daemon, try "pairing" and put here the log package from support page ? (telecharger tout) 

Thanks

**Comment by peporl** [comment]
Hi @tcharp38 ,

Please find the log files

I 'am trying to add sonoff snzb 02

Thanks
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/7988832/AbeilleCmd.log)
[AbeilleConfig2.log](https://github.com/KiwiHC16/Abeille/files/7988836/AbeilleConfig2.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/7988837/Abeille.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/7988838/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/7988839/AbeilleSerialRead1.log)

**Comment by tcharp38** [comment]
Hi @peporl 
The log package can be obtained thru support page, then "telecharger tout" (sorry for lack of translations).
It is easier for you and more complete since have also some other internal logs.
I could not see the pb in your log sub set. I will try tomorrow mt SNZ 02 and come back to you

**Comment by peporl** [comment]
Hi @tcharp38 

I found a solution to my problem this morning. I had to move my USB storage key to a USB 2 port and no longer to USB3.

thank you
