### ISSUE TITLE
Support Lexman (Leroy Merlin) Ampoule RGB : LXEK-1,Adeo

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2295]
Salut

Est-il possible d'inclure ce modèle d'ampoule ? Ampoule Lexman vendue par Leroy Merlin
RGB + Blanc +T°

Je joins le fichier discovery. Pour l'icône une ampoule E27 fera l'affaire. Je joins également
Identifiant Zigbee (modelId, manufId)LXEK-1, Adeo

![LXE1-K](https://user-images.githubusercontent.com/36518012/152227899-3d87d626-af41-4fd9-abb1-d80f693b4ae5.png)
 

Merci 

[discovery.txt](https://github.com/KiwiHC16/Abeille/files/7989594/discovery.txt)

Ayant les notices je peux les scanner pour inclure, réinitialiser et appairer avec la télécommande LEXMAN

**Comment by tcharp38** [comment]
[LXEK-1_Adeo.zip](https://github.com/KiwiHC16/Abeille/files/8024250/LXEK-1_Adeo.zip)

A tester.
Dis moi ce que tu en penses.

**Comment by mickadam29** [comment]
Salut

Ca me semble nickel. J'ai de gros soucis de qualité avec la Zigate WIFI. Je passe mon temps à relancer le démon.
Lorsque les trames passent, pas de soucis les commandes sont OK. Je ferai un autre test en Ethernet pour confirmer ton modèle.

**Comment by tcharp38** [comment]
Pour les soucis Wifi, tu peux ajouter un package de logs sur le sujet #2220 ?

**Comment by mickadam29** [comment]
Je vais essayer d'y penser

**Comment by tcharp38** [comment]
Support preliminaire dans 220211-BETA-1 (dispo le 12/2)

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si qqn a besoin de ce support.
