### ISSUE TITLE
Support LEXMAN Télécommande : LXEK-5, ADEO

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2296]
![LXEK-5](https://user-images.githubusercontent.com/36518012/152230093-902601ef-3400-44dc-b251-b0b16f818c75.png)
Salut

Est-il possible de créer le modèle pour la télécommande LEXMAN ?
Identifiant Zigbee (modelId, manufId)LXEK-5, ADEO
Ayant les notices je peux les scanner pour inclure, réinitialiser et appairer avec une ampoule LEXMAN

Je joins le fichier discovery. Très succint

[discovery.txt](https://github.com/KiwiHC16/Abeille/files/7989730/discovery.txt)

 Et une photo sans fond

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si qqn a besoin de ce support.
