### ISSUE TITLE
Ajout Tradfri TRADFRItransformer10W

### ISSUE THREAD

**Issue by rkhadro** [KiwiHC16/Abeille#230]
Bonjour,

le modèle Tradfri est inconnu, pouvez-vous le rajouter SVP. Merci

Voici le  parser:Simple Descriptor Request sur le endpoint 01

AbeilleParser 2018-04-11 11:53:53[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: f2
AbeilleParser 2018-04-11 11:53:53[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-04-11 11:53:53[DEBUG];type: 8043 (Simple Descriptor Response)(Not Processed); SQN : f2; Status : 00; Short Address : 4384; Length : 20; endpoint : 01; profile : c05e; deviceId : 0100; bitField : 02; InClusterCount : 08
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0008 - General: Level Control
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 0B05 - Misc: Diagnostics
AbeilleParser 2018-04-11 11:53:53[DEBUG]In cluster: 1000 - ZLL: Commissioning
AbeilleParser 2018-04-11 11:53:53[DEBUG]OutClusterCount : 04
AbeilleParser 2018-04-11 11:53:53[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-04-11 11:53:53[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2018-04-11 11:53:53[DEBUG]Out cluster: 0020 - General: Poll Control
AbeilleParser 2018-04-11 11:53:53[DEBUG]Out cluster: 1000 - ZLL: Commissioning

**Comment by KiwiHC16** [comment]
Bonjour rkhadro,
Il me faudrait le nom ZigBee de l'objet: depuis l'objet Ruche faire un "Get Name" sur l'adresse 4384 et capturer le log AbeilleParser.
Un photo de l'objet ?

**Comment by rkhadro** [comment]
Je n'ai pas de nom dans les logs:

AbeilleParser 2018-04-11 17:51:56[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: eb
AbeilleParser 2018-04-11 17:51:56[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-04-11 17:51:56[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: eb; Src Addr : 4384; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0017; Data byte list : 54524144465249207472616e73666f726d65722031305

Quand a la photo:
https://www.ikea.com/fr/fr/images/products/tradfri-driver-pour-commande-sans-fil-gris__0553357_PE659468_S4.JPG

**Comment by rkhadro** [comment]
Mais apparemment Abeille retrouve ce nom dans le message d'erreur lors de la création de l'objet:
getJSonConfigFilebyDevices: file not found devicefilename/usr/share/nginx/www/jeedom/plugins/Abeille/resources/AbeilleDeamon/lib/../../../core/config/devices/TRADFRItransformer10W/TRADFRItransformer10W.json

**Comment by KiwiHC16** [comment]
Si je fais un "54524144465249207472616e73666f726d6572203130".decode('hex’) en python ca me donne: 'TRADFRI transformer 10’ mais il manque un caractère.

**Comment by KiwiHC16** [comment]
Ca doit être un W qui manque.
Je vais faire un fichier JSON dans les jours a venir.

**Comment by rkhadro** [comment]
Ce n'est pas le W pour 10 watts
J'ai les debug lors de l'inclusion de l'objet

**Comment by rkhadro** [comment]
oops, je n'ai pas vu votre nouveau message

**Comment by rkhadro** [comment]
Mauvais copier/coller,Il manquait le caractère 7: Data byte list : 54524144465249207472616e73666f726d657220313057
Merci pour la prise en compte

**Comment by KiwiHC16** [comment]
Je viens de le faire et il est maintenant dans le master. Essayez et dites moi ...

**Comment by rkhadro** [comment]
Merci beaucoup, j'essaie

**Comment by rkhadro** [comment]
Ca fonctionne, l'objet est bien créé.
Je vais tester les fonctions.
Par contre au niveau du nom ce n'est pas une ampoule. c'est un transfo pour commander des ampoules led.

Merci encore

**Comment by rkhadro** [comment]
Tout fonctionne bien on/off, toggle  setlevel et retour état/level en les "bindants" .

Par contre, je n'arrive plus à avoir un retour lorsque je fais liste Equipements pour avoir le Link quality.

Avant:
AbeilleParser 2018-04-11 18:32:49[DEBUG]Nombre d'abeilles: 3
AbeilleParser 2018-04-11 18:32:49[DEBUG]Abeille i: 0; ID : 32; Short Addr : 4384; IEEE Addr: 000B57fffeefaf94; Power Source (0:battery - 1:AC): 01; Link Quality: 140
AbeilleParser 2018-04-11 18:32:49[DEBUG]Abeille i: 1; ID : 33; Short Addr : 4d39; IEEE Addr: 84182600000Cb01b; Power Source (0:battery - 1:AC): 01; Link Quality: 106
AbeilleParser 2018-04-11 18:32:49[DEBUG]Abeille i: 2; ID : 34; Short Addr : f59b; IEEE Addr: 000B57fffef4f374; Power Source (0:battery - 1:AC): 01; Link Quality: 110

Maintenant:

AbeilleParser 2018-04-11 19:21:39[DEBUG]Nombre d'abeilles: 2
AbeilleParser 2018-04-11 19:21:39[DEBUG]Abeille i: 0; ID : 32; Short Addr : f59b; IEEE Addr: 000B57fffef4f374; Power Source (0:battery - 1:AC): 01; Link Quality: 112
AbeilleParser 2018-04-11 19:21:39[DEBUG]Abeille i: 1; ID : 33; Short Addr : 4d39; IEEE Addr: 84182600000Cb01b; Power Source (0:battery - 1:AC): 01; Link Quality: 131

**Comment by rkhadro** [comment]
Bonjour,

Très bien, je comprends mieux car j'ai oublié de préciser: 
3 abeilles listées: les 3 devices était cote à cote sur mon bureau.
2 abeilles: le transfo est à l'étage et 2 devices sur mon bureau dont une ampoule ikea.

Je rapatrierais ce soir le transfo pour valider ce problème de réseau.

Autre sujet sur le plug OSram (problème on/off non transmis), je poste ici ou j'ouvre un autre ticket ?

**Comment by KiwiHC16** [comment]
J ai fait des investigations hier soir et je vais faire un script pour essayer d avoir plus d infos sur la liste des équipements. 

OSRam oui ouvre un autre ticket ça sera plus clair et facile à relire.

**Comment by KiwiHC16** [comment]
Le test de l ampoule éteinte est clair !
Je t envoies demain un script à tester pour voir si on peut avoir l information directement du réseau lui même.

**Comment by KiwiHC16** [comment]
Salut,
Peux tu mettre à jour avec le master et faire la manip décrite : https://github.com/KiwiHC16/Abeille/blob/master/Documentation/068_LQI.adoc
et partager le résultat. On verra si c'est en ligne avec tes tests.

**Comment by rkhadro** [comment]
Très intéressant on pourrait par la suite avoir une représentation graphique des relations.

**Comment by KiwiHC16** [comment]
Super de voir que ca marche aussi chez toi. J'ai aussi un sccript qui fait des graphs a partir des sniffs donc j ai dans l'idee de les mettre ensemble...
Mais il faut aussi comprendre les détails car si b3e4 est Sibling de 0000 alors pourquoi b3e4 dit que 0000 est parent ?

**Comment by KiwiHC16** [comment]
"setreportEtat et setReportLevel" et  Switch Off/On. Je ne sais pas et je suppose que cela depend des équipements. Perso je ne les éteint pas mais j'ai eu des situations ou il m'a fallu refaire le setReport.
Il faudrait que je teste pour confirmer. Une bonne info a investiguer.

**Comment by rkhadro** [comment]
Même à ce niveau de LQI 20-50, les commandes passent sans problèmes, mais pas avec liste équipements. 

Oui, pour les modifs, c'est prévu. pour l'instant je n'ai qu'un module en haut, la zigate en bas.

**Comment by KiwiHC16** [comment]
Il faut les deux liens montant et descendant. Peut être que le liens vers Transfo est assez correct mais quand on lui demande des trucs les messages ne reviennent pas. As tu fait du setReport ? As tu les retour d etat ? (Perso j'ai des soucis avec ces niveaux).

**Comment by rkhadro** [comment]
Aucun souci avec les retour d'état et de niveau.

**Comment by KiwiHC16** [comment]
Si tu fais, sur la ruche, un :
![capture d ecran 2018-04-13 a 22 24 05](https://user-images.githubusercontent.com/8549674/38756330-6cd53564-3f69-11e8-8dfb-14ebac445af1.png)

Vois tu un mesage "Type 804E" dans le log AbeilleParser en retour ?

**Comment by rkhadro** [comment]
Je n'ai pas cela LQI dans la ruche.
Comment faire pour rafraîchir les commandes. 
Recréer l'objet ruche ?

**Comment by KiwiHC16** [comment]
Supprimer l objet ruche et faire un restart du plugin, l objet ruche doit être recréé avec toutes les dernieres modifications.

**Comment by rkhadro** [comment]
Recréation de l'objet. toujours pas de LQI.
Faut-il refaire une download du master ?

**Comment by KiwiHC16** [comment]
Désolé en fait je crois avoir fait la commande à la main. Je la mets de suite dans la ruche JSON.

**Comment by KiwiHC16** [comment]
Je viens de le mettre dans le master.

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-04-14 a 16 49 03](https://user-images.githubusercontent.com/8549674/38769452-c5ec183a-4003-11e8-9c0e-a08921e8787c.png)

Un petit graphe de mon réseau de prod. Ca prend forme...

**Comment by rkhadro** [comment]
OK. Merci

**Comment by rkhadro** [comment]
C'est bon cela me retourne bien.Mais le LQI est 88 et 114 !!!

_AbeilleParser 2018-04-14 18:27:01[DEBUG]Type: 804E: (Management LQI response)(Decoded but Not Processed); SQN: ea; status: 00; Neighbour Table Entries: 03; Neighbour Table List Count: 03; Start Index: 00; NWK Address: 0000; Extended PAN ID: d9ac456853e0ce80; IEEE Address: 00158d0001edf80F; Depth: 0; **Link Quality: 88**; Bit map of attributes: 68

AbeilleParser 2018-04-14 18:32:33[DEBUG]Type: 804E: (Management LQI response)(Decoded but Not Processed); SQN: 00; status: 00; Neighbour Table Entries: 03; Neighbour Table List Count: 03; Start Index: 00; NWK Address: 0000; Extended PAN ID: d9ac456853e0ce80; IEEE Address: 00158d0001edf80F; Depth: 0; **Link Quality: 114;** Bit map of attributes: 68_

**Comment by rkhadro** [comment]
Je ne comprends pas les valeurs ont augmentées par rapport à hier.
Et il existe un lien direct avec la zigate.

NE | NE Name | Voisine | Voisine Name | Voisine IEEE | Relation | Profondeur | LQI
-- | -- | -- | -- | -- | -- | -- | --
0000 | Ruche | b3e4 |   | 84182600000Cb01b | Sibling | 00 | 117
0000 | Ruche | f59b |   | 000B57fffef4f374 | Sibling | 00 | 104
b3e4 |   | 0000 | Ruche | 00158d0001edf80F | Parent | 01 | 90
b3e4 |   | f59b |   | 000B57fffef4f374 | Sibling | 01 | 74
b3e4 |   | 4384 |   | 000B57fffeefaf94 | Sibling | 01 | 28	Tradfri Transformer 10 W
f59b |   | 0000 | Ruche | 00158d0001edf80F | Sibling | 00 | 174
4384 |   | 0000 | Ruche | 00158d0001edf80F | Sibling | 00 | 121	Tradfri Transformer 10 W
4384 |   | b3e4 |   | 84182600000Cb01b | Sibling | 0F | 67	Tradfri Transformer 10 W
4384 |   | f59b |   | 000B57fffef4f374 | Sibling | 0F | 59	Tradfri Transformer 10 W

**Comment by rkhadro** [comment]
Joli réseau tu en as un plus que 3 apparement :)

**Comment by KiwiHC16** [comment]
Les infos ne sont pas statiques mais dependent des conditions radio, du traffic sur le reseau, certaines infos sont perdues si non rafraichies, etc, ...
Changes les valeurs dans NetworkDefinition.php en fonction de ton réseau pour avoir les noms qui vont bien.

Essayes http://(jeedom)/plugins/Abeille/Network/AbeilleLQI_Map.php pour avoir le graph de ton reseau en ayant le dernier master (la collect des infos prend du temps, page blanche avant l'affichage).

**Comment by rkhadro** [comment]
Bonjour,

Voici mon petit réseau.

![screenshot 2018-04-15 12 14 18](https://user-images.githubusercontent.com/38282423/38777341-a3b26ea6-40a6-11e8-9044-b413b876a685.png)

Comment agrandir pour que cela soit plus lisible ?

**Comment by rkhadro** [comment]
Oui, j'ai vu, je suis sous safari aussi.
Merci

**Comment by KiwiHC16** [comment]
Aurais tu de connaissance web svg pour rendre le graph manipulable à la souris par exemple pour positionner les equipements ou on veut, sauvegarder l'info pour ne pas a avoir a éditer le fichier  NetworkDefinition.php manuellement ce qui est pénible ?

**Comment by rkhadro** [comment]
Non désolé. je ne développe pas beaucoup. plutôt dans l'infra réseaux et systèmes.
Mais je peux poser la question à des dev.

**Comment by KiwiHC16** [comment]
Je clos ce issue. Car maintenant le JSON existe. S'il manque des trucs on ferra des issues specifique.
