### ISSUE TITLE
Erreur beta 2022-02-03 01:00:11

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2302]
Salut,
Je viens de passer la beta, et j'ai eu direct: 
`2022-02-03 13:43:02 Abeille ERREUR: prepareCmd(): Mauvais format de message reçu (topic=TempoCmdReadAttributeRequest&time=1643892197).`
`2022-02-03 13:43:02 | Abeille | ERREUR: prepareCmd(): Mauvais format de message reçu (topic=TempoCmdReadAttributeRequest&time=1643892198). `
`2022-02-03 13:43:02 | Abeille | ERREUR: prepareCmd(): Mauvais format de message reçu (topic=TempoCmdReadAttributeRequest&time=1643892199).`
`2022-02-03 13:43:02 | Abeille | ERREUR: prepareCmd(): Mauvais format de message reçu (topic=TempoCmdReadAttributeRequest&time=1643892200).`

Rien depuis.
Je ne sais pas si vous aviez vue ou si ca vous sert.
Bonne aprem

**Comment by tcharp38** [comment]
@Jake309 
Oui pb connu.

Je te laisse tester avec ce fichier, pour decompresser dans core/class
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/7995147/Abeille.class.php.zip)

puis redemarrer Abeille
et pense à effacer les erreurs.

Merci pour ton retour

**Comment by Jake309** [comment]
C'est tout bon ! 
Je cloture alors :)

**Comment by tcharp38** [comment]
Pas encore dans le master  donc je reouvre

**Comment by Jake309** [comment]
Okey, je comprends la méthodologie =)

**Comment by tcharp38** [comment]
@Jake309 
Je te laisse tester la 220204-BETA-1 (dispo 05/02) et clore ce point si ok.

**Comment by Seby9576** [comment]
Salut,

Avec la dernière BETA j'ai ca comme erreurs
![image](https://user-images.githubusercontent.com/77990298/152674035-1dc8a101-991b-4365-bbd2-a10b4320f323.png)
Et aussi le pb de volet comme évoqué dans l'issue 1994

**Comment by tcharp38** [comment]
Ca ne me dit rien. Il faut les logs qui englobent ce pb donc ceux de 9:47 le 6/2
Sinon effacer le message et fournir les logs des qu'il reapparait. Merci

**Comment by Seby9576** [comment]
[AbeilleLogs-220206 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8010346/AbeilleLogs-220206.1.tar.gz)
15h15 et 51s

**Comment by tcharp38** [comment]
Alors ca..
le pb vient de "Tel bureau", a priori une telecommande Profalux.
Mais elle serait identifiée via le modele "ShadeController" que je ne comprends pas et connais pas.
De plus l'info de son main EndPoint est daubée (on y trouve "DeviceDescription" au lieu de "01").
Je te suggere de supprimer cet equipement qui par ailleurs ne sert à rien.
Il devrait etre reinclus à l occase, normalement en tant que "TS".

Pour mem

> [2022-02-06 15:15:51] Msg from 'xToCmd': CmdAbeille1/3437/readAttribute => ep=DeviceDescription&clustId=0000&attrId=0000
> [2022-02-06 15:15:51]   prepareCmd(CmdAbeille1/3437/readAttribute, ep=DeviceDescription&clustId=0000&attrId=0000)
> [2022-02-06 15:15:51]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
> [2022-02-06 15:15:51]     processCmd({"readAttribute":"readAttribute","name":"readAttribute","dest":"Abeille1","ep":"DeviceDescription","clustId":"0000","attrId":"0000","addr":"3437"})
> [2022-02-06 15:15:51]     readAttribute cmd
> [2022-02-06 15:15:51]     addCmdToQueue2(pri=4, net=Abeille1, cmd=0100, payload=02343701DeviceDescription000000000000010000, addr=3437 addrMode=02 AckAPS=1)
> [2022-02-06 15:15:51] ERROR:       ERROR: Invalid payload. Not hexa ! (02343701DeviceDescription000000000000010000)
>

**Comment by Seby9576** [comment]
C'était bien ca, j'ai supprimé la télécommande du bureau et je n'ai plus de message d'erreur. Merci

**Comment by tcharp38** [comment]
La telecommande est revenue ?

**Comment by Seby9576** [comment]
Salut,

Non mais si elle ne sert à rien c'est pas grave

**Comment by tcharp38** [comment]
Ok. Mais elle doit finir par revenir.
Je clos.
