### ISSUE TITLE
[Abeille] HUE Motion Outdoor SML002

### ISSUE THREAD

**Issue by gregof45** [KiwiHC16/Abeille#2309]
Bonjour,

Je rencontre un souci avec un détecteur hue-motion SML002.
Ce dernier remonte bien en temps réel la détection de passage mais rien niveau température et luminosité.
Je suis obligé de "rafraichir" manuellement ces données en utilisant l'Assistant de découverte d'équipement (beta) et de forcer le Endpoint02 et les clusters 400 et 402.
Jeedom version 4.2.8, abeille et zigate V1 avec firmware 321. Le capteur Hue motion est à jour.
Une idée?

**Comment by tcharp38** [comment]
Salut
Que veux tu dire "forcer le EP02" ? Tu fais quoi exactement ?

Peux tu pendant que tu y es fournir le discovery.json puisque tu as joué avec l'assistant ? Merci

**Comment by gregof45** [comment]
Salut et merci d'avoir répondu.
Le EP, c'est, d'après ce que je comprends hein, le end point 2 et ensuite apparaissent les différents server / input clusters.
Pour la luminosité, c'est le 400 et la température le 402. 
C'est l'assistant de découverte qui me permet de rafraichir mon capteur
Voici le lien : /var/www/html/plugins/Abeille/desktop/php/AbeilleEq-Advanced-Interrogations.php 

[discovery.txt](https://github.com/KiwiHC16/Abeille/files/8011342/discovery.txt)

![image](https://user-images.githubusercontent.com/71756269/152704082-a2297e77-2076-4755-9124-d29991583725.png)

**Comment by tcharp38** [comment]
Via la page EQ/avancé peux tu verifier quel reporting est en place pour le 400 par ex ?

![image](https://user-images.githubusercontent.com/35221038/152705746-9f67d329-f05d-4713-a002-9c87100742dc.png)

puis tu attaches le package de logs.
Pour info on doit retrouver une trace "Configure reporting response" dans le log parser.

**Comment by gregof45** [comment]
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8147722/AbeilleParser.log)

**Comment by gregof45** [comment]
1er log avec la manipulation qui permet de rafraichir le Endpoint02 cluster 400 / 402

**Comment by gregof45** [comment]
[AbeilleParser(1).log](https://github.com/KiwiHC16/Abeille/files/8147727/AbeilleParser.1.log)
Et voici le log avec la manipulation que tu m'as demandé de réaliser.
Ca marchait bien avant, toutes les 5 minutes. A présent, faut vraiment que je le force via la commande découverte.
Un grand merci par avance.

**Comment by tcharp38** [comment]
Salut @gregof45 
Le reporting du 400 me semble incorrecte

> [2022-02-27 01:00:52] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0400, SrcEP=02, DstEP=01, SrcAddrMode=02, SrcAddr=1334, DstAddrMode=02, DstAddr=0000
> [2022-02-27 01:00:52]   FCF=18/General/Serv->Cli, SQN=E0, cmd=09/Read Reporting Configuration Response
> [2022-02-27 01:00:52]   Status=00/Success, Dir=00, AttrId=0000, AttrType=21, minInterval=FFFF, maxInterval=FFFF

min & max.. ca tient pas la route.

Peux tu tenter de reconfigurer le reporting via la page EQ
![image](https://user-images.githubusercontent.com/35221038/156884722-5b4c3569-e820-409b-95a1-bfdc460330da.png)

Pense à reveiller ton equipement juste en cliquant "Configurer"
puis refais aussi une lecture de la config reporting apres pour trouver le "Read Reporting Configuration Response" dans le log parser.

**Comment by tcharp38** [comment]
[SML002.zip](https://github.com/KiwiHC16/Abeille/files/8190722/SML002.zip)
Si tu preferes, refais une inclusion avec ce modele.
Et donne moi le package de logs dans la foulée.
Merci

**Comment by dams74** [comment]
Salut
J'ai le même souci que cet issu. Voici mes log après deux inclusions
A ta dispo pour faire des tests ou autre
Merci de ton aide
[AbeilleLogs-220403.tar.gz](https://github.com/KiwiHC16/Abeille/files/8404773/AbeilleLogs-220403.tar.gz)
e

**Comment by tcharp38** [comment]
[SML002.zip](https://github.com/KiwiHC16/Abeille/files/8405289/SML002.zip)

@dams74 
Peux tu refaire un essai avec en ecrasant le modele avec celui attaché ?
- Redemarrer Abeille
- refaire inclusion
- et me filer le package de logs

Merci

**Comment by dams74** [comment]
Merci de ton aide
Voici le log
[AbeilleLogs-220404.tar.gz](https://github.com/KiwiHC16/Abeille/files/8406848/AbeilleLogs-220404.tar.gz)
Toujours pas de température et de luminosité
ça ressemble au soucis que j'avais eu ici https://github.com/KiwiHC16/Abeille/issues/1918

**Comment by tcharp38** [comment]
Oui je pensais au meme souci j'ai donc appliqué la meme solution.
Ca dit quoi ?
Le log est trop court et je ne vois du coup pas comment la config se termine.

Vois tu des retour temp ou humidité ?

**Comment by tcharp38** [comment]
Ha... a priori le dernier modele n est pas pris en compte. Ca donnera donc le meme resultat.
Tu l'as bien mis au bon endroit ? => core/config/devices/SML002/SML002.json

**Comment by dams74** [comment]
oui c'est bien à cette emplacement que je l'ai mis
![image](https://user-images.githubusercontent.com/2788955/161683399-784b7c18-fb42-42e8-9a8c-88da68f4ca8b.png)
Ci joint les log de nouvelles inclusions
[AbeilleLogs-220405.tar.gz](https://github.com/KiwiHC16/Abeille/files/8415056/AbeilleLogs-220405.tar.gz)

**Comment by tcharp38** [comment]
Je confirme. Toujours pas pris en compte.

> [2022-04-05 07:14:28] Msg from 'xToCmd': Pri=4, CmdAbeille1/4A5B/configureReporting => ep=02&clustId=0402&attrType=29&attrId=0000&minInterval=012C&maxInterval=0258&**changeVal=**
> [2022-04-05 07:14:28]   prepareCmd(4, CmdAbeille1/4A5B/configureReporting, ep=02&clustId=0402&attrType=29&attrId=0000&minInterval=012C&maxInterval=0258&**changeVal=**)
> [2022-04-05 07:14:28]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
> [2022-04-05 07:14:28]     processCmd({"configureReporting":"configureReporting","name":"configureReporting","priority":4,"dest":"Abeille1","ep":"02","clustId":"0402","attrType":"29","attrId":"0000","minInterval":"012C","maxInterval":"0258","changeVal":"","addr":"4A5B"})
> [2022-04-05 07:14:28]     configureReporting cmd
> [2022-04-05 07:14:28]     Using attrType='29', min='012C', max='0258', **changeVal=''**
> [2022-04-05 07:14:28]     addCmdToQueue2(Pri=4, Net=Abeille1, Cmd=0530, Payload=024A5B010204020104021E0b100306000000292C015802, Addr=4A5B, AddrMode=02)
> [2022-04-05 07:14:28]       Zg 1 queues: [1]=0, [2]=0, [3]=0, [4]=1, [5]=0
> 

Ce qui entraine l'erreur suivante

> [2022-04-05 07:14:28] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0402, SrcEP=02, DstEP=01, SrcAddrMode=02, SrcAddr=4A5B, DstAddrMode=02, DstAddr=0000
> [2022-04-05 07:14:28]   FCF=18/General/Serv->Cli, SQN=03, cmd=0B/Default Response
> [2022-04-05 07:14:28]   Cmd=06, Status=80 => Malformed command
> 

Le 'changeVal' devrait avoir une valeur '0000' comme indiqué dans mon dernier SML002.json.

>             "SetReporting 0402-0000": {
>                 "use": "zbConfigureReporting",
>                 "params": "clustId=0402&attrType=29&attrId=0000&minInterval=012C&maxInterval=0258&changeVal=0000",
>                 "comment": "Reporting every 5 to 10mins",
>                 "execAtCreation": "Yes",
>                 "execAtCreationDelay": 12
>             },
> 

La comme ca, je seche.
Ta photo etant trop reduite je ne vois pas le chemin complet. Bref... une idée ?

**Comment by dams74** [comment]
voici une photo plus grande
![image](https://user-images.githubusercontent.com/2788955/161716537-4cbeae80-60d7-4961-bbf0-dc984142ea5a.png)

Voici une copie du json

    "SML002": {
        "manufacturer": "Philips",
        "model": "9290019758",
        "timeout": "60",
        "configuration": {
            "mainEP": "02",
            "icon": "SML002",
            "batteryType": "2x AAA"
        },
        "category": {
            "security": "1"
        },
        "type": "Philips Hue motion sensor",
        "commands": {
            "SWBuildID": {
                "use": "zb-0000-SWBuildID"
            },

            "include4 3 2": "Batterie-Hue",
            "Bind-0001-ToZigate": {
                "use": "zbBindToZigate",
                "params": "clustId=0001",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 9
            },
            "SetReporting-0001-0021": {
                "use": "zbConfigureReporting",
                "params": "clustId=0001&attrType=20&attrId=0021&minInterval=0708&maxInterval=0E10&changeVal=",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 7
            },

            "include4": "luminositeHue",
            "Bind-0400-ToZigate": {
                "use": "zbBindToZigate",
                "params": "clustId=0400",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 9
            },
            "SetReporting-0400-0000": {
                "use": "zbConfigureReporting",
                "params": "clustId=0400&attrType=21&attrId=0000&minInterval=012C&maxInterval=0258&changeVal=",
                "comment": "Reporting every 5 to 10mins",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 11
            },

            "Temperature": {
                "use": "zb-0402-MeasuredValue",
                "isVisible": 1,
                "isHistorized": 1
            },
            "Bind-0402-ToZigate": {
                "use": "zbBindToZigate",
                "params": "clustId=0402",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 9
            },
            "SetReporting-0402-0000": {
                "use": "zbConfigureReporting",
                "params": "clustId=0402&attrType=29&attrId=0000&minInterval=012C&maxInterval=0258&changeVal=",
                "comment": "Reporting every 5 to 10mins",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 12
            },

            "include3": "presence",
            "Bind-0406-ToZigate": {
                "use": "zbBindToZigate",
                "params": "clustId=0406",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 9
            },
             "SetReporting-0406-0000": {
                "use": "zbConfigureReporting",
                "params": "clustId=0406&attrType=18&attrId=0000&minInterval=0000&maxInterval=0000&changeVal=",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 11
            }
        }
    }

Merci de ton aide

**Comment by gregof45** [comment]
Pour être honnête avec vous, j'ai décroché. Ca fonctionnait super bien à moment,  et sur une vieille beta d'abeille. Et après plus rien. Et je déprime car j'avais pas mal de scénarios basé sur ces valeurs..
Du coup, de temps à autre, je fais la découverte et ca rafraîchit mes valeurs.

**Comment by dams74** [comment]
> Pour être honnête avec vous, j'ai décroché. Ca fonctionnait super bien à moment, et sur une vieille beta d'abeille. Et après plus rien. Et je déprime car j'avais pas mal de scénarios basé sur ces valeurs..

On va arrivé à résoudre ce soucis
J'avais eu le cas il y a un an et nous avions trouvé. 
Il faut comprendre que le code évolue et qu'il peut y avoir parfois des régressions

**Comment by gregof45** [comment]
Ah mais j'en doute pas que vous allez trouver.
Si je peux me permettre,  j'ai l'impression que les problèmes ont débuté quand il y a eu l'ajout de champs dans les commandes (style les demandes d'interrogations d'un cluster toutes les x minutes, qui ne fonctionnent pas d'ailleurs ).

**Comment by tcharp38** [comment]
@dams74 
C'est bien ca. Tu n'utilises pas le dernier modele que je t'ai filé.

Regarde le changeVal de la commande
        "SetReporting-0402-0000": {
            "use": "zbConfigureReporting",
            "params": "clustId=0402&attrType=29&attrId=0000&minInterval=012C&maxInterval=0258&changeVal=",
            "comment": "Reporting every 5 to 10mins",
            "execAtCreation": "Yes",
            "execAtCreationDelay": 12
        },

ca devrait etre changeVal=0000.
Par ailleurs le nom de la cmde à legerement changé aussi "SetReporting-xx" => "SetReporting xx"

**Comment by dams74** [comment]
En effet j'ai mis le fichier présent dans ton commentaire du 5 mars au lieu de celui du commentaire du 3 avril...
Désolé de cette erreur
Je fais un nouveau test en fin d'après midi et poste un nouveau log

**Comment by dams74** [comment]
c'est bon tout est reparti !
Merci @tcharp38 pour ton temps

**Comment by tcharp38** [comment]
Ca veut dire quoi ?
Tu as une remontée d'info Temp & luminosité automatique ?

**Comment by gregof45** [comment]
Tcharp38, Tu es un dieu. J'aurais ta photo, je t'érigerais une statue.
Tout remonte correctement, je vais pouvoir refaire mes scénarios sans passer par mon pont hue.
Petite question, tu sais ce qui s'est passé?

**Comment by dams74** [comment]
> Ca veut dire quoi ? Tu as une remontée d'info Temp & luminosité automatique ?

Oui toute les info remonte bien Température hygro et luminosité
merci encore

**Comment by tcharp38** [comment]
Coool.

Pour info, le souci etait du à une particularité "Philips" qui exige de preciser une valeur de changement permettant de declencher un reporting.
Pas sur d'etre clair mais en gros au lieu de "changeVal=" (non précisé), on a juste ajouté un "changeVal=0000" et il est content avec ce format et du coup accepte la commande.

Il reste qqch en attente sur ce sujet ou on peut clore ?
Merci pour vos essais.

**Comment by gregof45** [comment]
Oui, tu vas pouvoir clôturer le sujet mais j'ai une dernière question. 
Quand le plugin se met à jour, il remodifie toute sa base de données ? Le Json du sml002, il faudra le réinjecter à chaque fois?
Merci encore pour tes heures de recherche ;-)

**Comment by tcharp38** [comment]
Non toute la DB n'est pas mise à jour aujourd hui, et ce meme si certains modeles ont ete mis à jour.
A terme ca serait bien (mais ne doit rien casser pour l utilisateur) mais ca n'est pas le cas.

Par contre le nouveau modele sera utilisé à chaque inclusion ou nouvelle annonce du device si jamais il le fait.

Bref normalement vous n'avez rien a faire.
Concernant le SML002, le dernier modele sera dans la beta de demain, et donc dans la futur stable.

**Comment by tcharp38** [comment]
Dernier modele SML002 dans 220407-BETA-1

**Comment by gregof45** [comment]
Merci Tcharp38, je suis trop heureux ;-)
A clôturer.
