### ISSUE TITLE
OSRAM Plug On/Off 

### ISSUE THREAD

**Issue by rkhadro** [KiwiHC16/Abeille#231]
J'ai un problème avec ce device.

L'objet est créé correctement, mais les commandes ON/OFF Toggle ne sont pas transmises.

L'etat lui est bien transmis si je l'allume à la main + getEtat
Voici les logs:

AbeilleMQTTCmd 2018-04-12 21:26:29[DEBUG]checksum computed: 95
AbeilleMQTTCmd 2018-04-12 21:26:35[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => On
AbeilleMQTTCmd 2018-04-12 21:26:35[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-12 21:26:35[DEBUG]begin processCmd function

Rien ne passe dans le serial et le parser.

en CLI:
mosquitto_pub -h localhost -t "CmdAbeille/b3e4/OnOffOSRAM" -m "Toggle" -d 
Client mosqpub|21954-Jeedom sending CONNECT
Client mosqpub|21954-Jeedom received CONNACK
Client mosqpub|21954-Jeedom sending PUBLISH (d0, q0, r0, m1, 'CmdAbeille/b3e4/OnOffOSRAM', ... (6 bytes))
Client mosqpub|21954-Jeedom sending DISCONNECT

Rien dans les logs parser et serial

**Comment by KiwiHC16** [comment]
Je pense avoir trouvé le bug que j'ai introduit par erreur mi-mars. Je viens de mettre la correction dans master. Peux tu tester ?

**Comment by rkhadro** [comment]
Bonjour,

Le plug éteint,
Rien ne fonctionne. 
ON: Aucun effet 
OFF: Aucun effet
Toggle: Aucun effet.


Le plug allumé:
ON: éteint le plug
OFF: éteint le Plug.
Toggle: aucun effet 

Les logs ci -dessous:

**## Plug allumé**

**Commande ON**
```
AbeilleMQTTCmd 2018-04-14 11:29:10[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => On
AbeilleMQTTCmd 2018-04-14 11:29:10[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:10[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:10[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): On
AbeilleMQTTCmd 2018-04-14 11:29:11[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103On
AbeilleMQTTCmd 2018-04-14 11:29:11[DEBUG]len data: 12
AbeilleMQTTCmd 2018-04-14 11:29:11[DEBUG]checksum computed: 195

AbeilleParser 2018-04-14 11:29:11[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 63
AbeilleParser 2018-04-14 11:29:11[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 63; EndPoint : 03; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00

AbeilleSerialRead 2018-04-14 11:29:11[DEBUG]2018-04-14 11:29:11 -> 80000005740063009200
AbeilleSerialRead 2018-04-14 11:29:11[DEBUG]2018-04-14 11:29:11 -> 810100079a6303000600007b

```
**Commande OFF**
```
AbeilleMQTTCmd 2018-04-14 11:29:16[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => Off
AbeilleMQTTCmd 2018-04-14 11:29:16[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:16[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:16[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): Off
AbeilleMQTTCmd 2018-04-14 11:29:17[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103Off
AbeilleMQTTCmd 2018-04-14 11:29:17[DEBUG]len data: 13
AbeilleMQTTCmd 2018-04-14 11:29:17[DEBUG]checksum computed: 195

AbeilleParser 2018-04-14 11:29:17[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 64
AbeilleParser 2018-04-14 11:29:17[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 64; EndPoint : 03; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00

AbeilleSerialRead 2018-04-14 11:29:17[DEBUG]2018-04-14 11:29:17 -> 80000005730064009200
AbeilleSerialRead 2018-04-14 11:29:17[DEBUG]2018-04-14 11:29:17 -> 810100079d6403000600007b

```
**Commande Toggle**
```
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => Toggle
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): Toggle
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103Toggle
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]len data: 16
AbeilleMQTTCmd 2018-04-14 11:29:25[DEBUG]checksum computed: 205

```
Pas de parser log, ni de serial
——————————————————————————————————————————————————————————————————————————————————————————
**## Plug Eteint**

**Commande ON**
```
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => On
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): On
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103On
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]len data: 12
AbeilleMQTTCmd 2018-04-14 11:29:38[DEBUG]checksum computed: 195

AbeilleParser 2018-04-14 11:29:39[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 65
AbeilleParser 2018-04-14 11:29:39[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 65; EndPoint : 03; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00

```
```
AbeilleSerialRead 2018-04-14 11:29:39[DEBUG]2018-04-14 11:29:39 -> 80000005720065009200
AbeilleSerialRead 2018-04-14 11:29:39[DEBUG]2018-04-14 11:29:39 -> 810100076365030006000084

```

**Commande OFF**
```
_AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => Off
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): Off
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103Off
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]len data: 13
AbeilleMQTTCmd 2018-04-14 11:29:44[DEBUG]checksum computed: 195

```
```
AbeilleParser 2018-04-14 11:29:44[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 66
AbeilleParser 2018-04-14 11:29:44[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 66; EndPoint : 03; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00

```
```
AbeilleSerialRead 2018-04-14 11:29:44[DEBUG]2018-04-14 11:29:44 -> 80000005710066009200
AbeilleSerialRead 2018-04-14 11:29:44[DEBUG]2018-04-14 11:29:44 -> 810100079f6603000600007b

```
**Commande Toggle**
```
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]Msg Received: Topic: {CmdAbeille/b3e4/OnOffOSRAM} => Toggle
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]Type: CmdAbeille Address: b3e4 avec Action: OnOffOSRAM
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]OnOff for: b3e4 action (0:Off, 1:On, 2:Toggle): Toggle
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]Dest:/dev/ttyUSB0cmd: 0092len: 0006datas:02b3e40103Toggle
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]len data: 16
AbeilleMQTTCmd 2018-04-14 11:29:49[DEBUG]checksum computed: 205

```
Pas de parser log, ni de serial

**Comment by rkhadro** [comment]
Pour avoir les infos SW et société.
Peut-on faire cela dans le json du plug:
récupérer  les infos du json ikea bulb:
getManufacturerName clusterId=0000&attributeId=0004
societe Abeille/@device/0000-0004

Pareil pour le SW
Je me reponds moi-même.

**C'est bon pour la société**
**Idem pour le SW**

**Comment by KiwiHC16** [comment]
Je viens de pousser une correction pour les On/Off/Toggle. J'espère que ca marche.

**Comment by rkhadro** [comment]
C'est bon cela fonctionne.

J'ai modifié le JSON du plug01 pour avoir: SW Société
Je peux l'uploader comment ?

![screenshot 2018-04-14 18 44 09](https://user-images.githubusercontent.com/38282423/38770467-da4e8d20-4013-11e8-923d-26f3e7849be3.png)

**Comment by rkhadro** [comment]
Par contre, j'ai essayé le bindtozigate pour avoir le retour état en auto. setReportEtat 

Cela ne fonctionne pas:

```
mosquitto_pub -h localhost -t "CmdAbeille/Ruche/bind" -m "address=84182600000Cb01b&ClusterId=0006&reportToAddress=00158d0001edf80F" -d 
```

_AbeilleParser
```
 2018-04-14 18:47:09[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 12
AbeilleParser 2018-04-14 18:47:09[DEBUG];type: 8030: (Bind response)(Decoded but Not Processed - Just send time update and status to Network-Bind in Ruche); SQN: 0x12; **Status: 0x00**_
```

```
mosquitto_pub -h localhost -t "CmdAbeille/Ruche/setReport" -m "address=b3e4&ClusterId=0006&AttributeId=0000&AttributeType=10" -d 
```

_### AbeilleParser 
```
2018-04-14 18:53:46[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: c2
AbeilleParser 2018-04-14 18:53:46[DEBUG]SQN: 0 for messages which are not transmitted over the air._
```

**Comment by KiwiHC16** [comment]
bind to zigate pour les OSRAM, n'a jamais ete testé donc il est fort probable que cela ne fonctionne pas.
Il faut que je regardes car il faut certainement ajouter le EndPoint dans les parametres.

**Comment by rkhadro** [comment]
Le Pull est fait.

**Comment by KiwiHC16** [comment]
Super, je viens de le mettre dans master.

**Comment by KiwiHC16** [comment]
Est toujours le cas. J avais introduit un bug qui est maintenant corrigé.

**Comment by rkhadro** [comment]
Non, le retour d'état ne fonctionne toujours pas.

**Comment by KiwiHC16** [comment]
Dans la trace ca semble ok.
Peux tu aller dans les commandes de la ruche et faire un clic sur le bouton tester de plug01:

![capture d ecran 2018-06-09 a 17 01 16](https://user-images.githubusercontent.com/8549674/41192983-dece72e2-6c06-11e8-8e82-a3cbe38ae4ab.png)

Est ce que tu as un objet plug01 qui est créé ?
Qu'elle version de Abeille as tu ?

**Comment by rkhadro** [comment]
Oui, Je l'ai deja essayé, je l'ai affiché plug01 et cliquer cela fonctionne bien.

J'utilise la dernière version du Git aujourd'hui à 10h55

![screenshot 2018-06-09 18 26 04](https://user-images.githubusercontent.com/38282423/41193858-da1bcc02-6c12-11e8-9ec7-c67cd9a7139b.png)

**Comment by rkhadro** [comment]
Bon, j'ai réussi à récupérer l'équipement  en créant un plug01, puis en modifiant la BDD avec la bonne short address.
Je vois que les commandes ont été modifiés car le retour ne tape plus sur les bonnes:  
un -03-  en  mileiu de commande
SW 0000-03-4000
societe 0000-03-0004
nom 0000-03-0005
etat 0006-03-0000

Mais toujours pas de retour d'état en auto avec un bindtozigate + setreportetat
```
[2018-06-09 19:15:12][DEBUG] : Message ->Plug 01<- sur Abeille/3e0C/0000-03-0005
[2018-06-09 19:15:12][DEBUG] : L objet: Abeille/3e0C existe mais pas la commande: 0000-03-0005
[2018-06-09 19:15:12][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/3e0C/Time-TimeStamp', ... (10 bytes))
```

**Comment by KiwiHC16** [comment]
Aie, pourquoi 3 parametres ! Ca ressemble a une modif que j avais faite pour les interrupteur Xiaomi. 
Il faut que je me remette dans ce sujet pour voir pourquoi tu as cette valeur….

**Comment by KiwiHC16** [comment]
Je confirme c est suite a ma modif de code pour les inter xiaomi. Donc comme tu l as fait il faut modifier les commandes. Je fais les modifs.

**Comment by rkhadro** [comment]
OK, merci.
Le problème d'association vient de la aussi tu crois ?
J'essaierai lorsque tu auras fait la modification.

Edit: je teste la MàJ.

**Comment by KiwiHC16** [comment]
Effectivement ca ne fonctionne pas. Il faut que je fasse une modif. Je travaille dessus.

**Comment by KiwiHC16** [comment]
Je viens de pousser. Ca semble fonctionner chez moi en simulant (Je ne peux pas tester en réel).

Non le probleme d'association est un autre sujet.

Est ce que la creation marche de nouveau ?

**Comment by rkhadro** [comment]
J'essaie et reviens .

Edit:

Ca fonctionne l'objet est bien créé.
 les commandes sont revenus en -03-, normal ?

![screenshot 2018-06-10 18 18 31](https://user-images.githubusercontent.com/38282423/41203683-e20d5e1c-6cda-11e8-8ebc-7935e32b75de.png)

**Comment by KiwiHC16** [comment]
Oui c est une evolution pour gérer plus de situation qu'auparavant .

**Comment by KiwiHC16** [comment]
Essayons le bind. 

Peux tu essayer un 
```mosquitto_pub -h localhost -t "CmdAbeille/Ruche/bind" -m "address=84182600000Cb01b&targetEndpoint=03&ClusterId=0006&reportToAddress=00158d0001edf80F"```

En mettant les bonnes adresses. La premiere est l'adresse de l'equipement et la deuxieme l'adresse de la Zigate.

Et partage le resultat dans AbeilleParser.

**Comment by rkhadro** [comment]
Voici:

Ce sont les bonnes @ que tu m'as donné.
```
[2018-06-10 23:35:57][DEBUG] : --- process a new message -----------------------
[2018-06-10 23:35:57][DEBUG] : Message ->address=84182600000Cb01b&targetEndpoint=03&ClusterId=0006&reportToAddress=00158d0001edf80F<- sur CmdAbeille/Ruche/bind
[2018-06-10 23:35:59][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/Ruche/Network-Bind', ... (51 bytes))
[2018-06-10 23:35:59][DEBUG] : --- process a new message -----------------------
[2018-06-10 23:35:59][DEBUG] : Message ->2018-06-10 23:35:59 Status (00: Ok, <>0: Error): 00<- sur Abeille/Ruche/Network-Bind


AbeilleParser 2018-06-10 23:35:58[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 96
AbeilleParser 2018-06-10 23:35:59[DEBUG];type: 8030: (Bind response)(Decoded but Not Processed - Just send time update and status to Network-Bind in Ruche); SQN: 0x96; Status: 0x00
```

**Comment by rkhadro** [comment]
Et le set Report:

````
[2018-06-10 23:42:40][DEBUG] : Envoi du message address=3e0C&ClusterId=0006&AttributeId=0000&AttributeType=10 vers CmdAbeille/Ruche/setReport
[2018-06-10 23:42:40][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/Ruche/setReport', ... (61 bytes))
[2018-06-10 23:42:40][DEBUG] : --- process a new message -----------------------
[2018-06-10 23:42:40][DEBUG] : Message ->address=3e0C&ClusterId=0006&AttributeId=0000&AttributeType=10<- sur CmdAbeille/Ruche/setReport

AbeilleParser 2018-06-10 23:42:43[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 68
```

**Comment by KiwiHC16** [comment]
Je viens de commander une ampoule et une prise, cela simplifira les investigation. Devrait les avoir en fin de semaine.

**Comment by rkhadro** [comment]
Très bien. Merci

**Comment by KiwiHC16** [comment]
Je viens de la recevoir et tout semble ok maintenant. Je clos le point.

**Comment by KiwiHC16** [comment]
J ouvre un autre sujet retour etat #281
