### ISSUE TITLE
[KiwiHC16] (master) ERREUR: readAttribute(): Format attribut (508) incorrect => ignoré.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2310]

**Comment by tcharp38** [comment]
Ça vient de la cmde getPlugAW de tête, qui contenait 508 au lieu de 0508. Faire recharger json devrait fixer le pb

**Comment by KiwiHC16** [comment]
J'ai fait la modif directement dans la base. On verra si cela suffit.
Merci.

**Comment by tcharp38** [comment]
Comment as tu fait la modif ? Ou peut etre juste dans ta base ?
Je m'attends à du code de correction dans "install.php" qui va realigner les bases des users au démarrage en fonction du derniere code Abeille mais rien vu en coup d oeil rapide.
j'ai loupé ?

**Comment by tcharp38** [comment]
Pb pas corrigé chez les users.
Seul le fichier JSON l'est.

**Comment by tcharp38** [comment]
Correction de la DB au demarrage dans la nouvelle beta
Beta 220316-BETA-1 dispo des demain (17/3) sur le market. Contient toutes les modifs jusqu'a cette heure.
