### ISSUE TITLE
Support Heiman Détecteur CO (id = COSensor-EF-3.0, HEIMAN)

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#2312]
Bonjour à tous,
@tcharp38 
Je viens d'essayer d'inclure le détecteur de CO de Heiman dans Jeedom via Abeille mais rien ne remonte.
Si quelqu'un peut m'aider ? Le détecteur incendie est déjà présent dans le système.
Merci d'avance.
95A7 / 5C0272FFFEE9B36B

[AbeilleLogs-220206.tar.gz](https://github.com/KiwiHC16/Abeille/files/8010280/AbeilleLogs-220206.tar.gz)

![image](https://user-images.githubusercontent.com/82177848/152683527-f923365c-e300-4f5f-8cde-369b2a766d6d.png)

**Comment by tcharp38** [comment]
Cette eq n'est pas supporté par Abeille.
Genere & attache le discovery.json STP

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Voici:

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8012846/discovery.zip)

Ca reste en orange malgré le réveil de l'EQ.
Merci.

**Comment by tcharp38** [comment]
Merci mais quasi vide.
Regarde sur la page EQ/avancé.. 
Est ce qu'il te propose pas de telecharger un "discovery" ? Si oui peux tu l'attacher ?

**Comment by ChrisChrisChri** [comment]
Salut,
Désolé j'ai été obligé de lancer quelques fois l'assistant et de réveiller l'EQ à plusieurs reprises avant d'avant un discovery en vert. J'avais pas mal d'erreur de javascript...
Ici, ça me semble mieux pour t'aider.
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8025138/discovery.zip)

Encore merci. 
Mon autre Heiman "incendie" qu'on avait par paramétré il y quelques mois reste lui bloqué sur un état à 20.Je ne sais pas si c'est un bug ou alors si la sonde est déjà encrassée...Est-ce possible ?

![image](https://user-images.githubusercontent.com/82177848/153019228-19a26f18-220a-4177-8bba-3f39de7a058c.png)

**Comment by tcharp38** [comment]
Ha oui bien mieux ce discovery. Je regarde.

Ne mélange pas les sujets STP. Ouvre ou reouvre un autre sujet. Et "autre Heiman" ca me parle pas. J'ai besoin de précisions.

**Comment by tcharp38** [comment]
[COSensor-EF-3.0.zip](https://github.com/KiwiHC16/Abeille/files/8032358/COSensor-EF-3.0.zip)

Pour test:
- decompresser dans core/config/devices
- redemarrer demon Abeille
- refaire inclusion
- et faire le point

Quelle est la ref du modele ? C est le HS1CA ou peut etre EN50291 ?
Quel type de batterie et combien ?

A noter que ce capteur semble (d'apres https://zigbee.blakadder.com/Heiman_HS1CA.html) etre reconnu sous les IDs suivants
- COSensor-EM
- COSensor-N
- CO_V15
- CO_YDLV10
- COSensor-EF-3.0
- CO_V16
- 1ccaa94c49a84abaa9e38687913947ba

**Comment by ChrisChrisChri** [comment]
Je n'arrive plus ouvrir JEEXPLORER. Une erreur systématique ???

![image](https://user-images.githubusercontent.com/82177848/153248021-83e868a3-c107-477b-a996-19dadb4c0183.png)


J'y suis arrivé via l'explorer de la nouvelle version de Jeedom.
EQ = 3F1E

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8034664/discovery.zip)

Nom du modèle= Smart Carbon Monoxide Alarme   
M420-66Ever1.0
Working voltage: DC3V(CR17335/CR123A Lithium Battery)

**Comment by tcharp38** [comment]
Ça n'est pas un pb Abeille mais j'ai la réponse.
Ce plugin ne sert plus à rien car jeedom propose la même chose. Fouille les menus, je ne sais plus lequel mais le même que pour la config jeedom

**Comment by tcharp38** [comment]
Support actuel dans 220211-BETA-1 (dispo le 12/2)

**Comment by tcharp38** [comment]
@ChrisChrisChri 
ou en est on ?

**Comment by ChrisChrisChri** [comment]
Salut Tcharp,
Sorry, je pensais t'avoir répondu. Je viens de relancer les tests à l'instant. 
Depuis la dernière modification, c'est beaucoup mieux. Par contre le status reste sur 20 en permanence et quand je teste le bouton de déclenchement,il passe à 121. Il faut appuyer 2 X sur le bouton test de l'EQ pour qu'il déclenche. 
Pourquoi est-ce qu'il reste à 20 en permanence ?


![image](https://user-images.githubusercontent.com/82177848/158025486-7745c2dd-98df-43c5-93a9-1e34b376e206.png)


![image](https://user-images.githubusercontent.com/82177848/158025671-b1ff201c-759f-4e0a-be2a-42b6b6e1c1eb.png)



[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8237916/discovery.zip)

**Comment by tcharp38** [comment]
le "zone status" est un ensemble de flags dont les principaux sont le bit 0 pour alarm1, et le bit 1 pour alarm2.
Il faut retravailler ca pour ne plus l'afficher.

Peux tu declencher un test, et me filer le package de logs ?
Plus besoin du discovery maintenant.

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Toujours partant pour une autre version du "Zone status"  ?

**Comment by ChrisChrisChri** [comment]
Salut tcharp,
Sorry pour l'absence....
[AbeilleLogs-220429.tar.gz](https://github.com/KiwiHC16/Abeille/files/8592205/AbeilleLogs-220429.tar.gz)

![image](https://user-images.githubusercontent.com/82177848/165982927-fd9661dd-1464-4efe-b9c3-5f17ab60d808.png)


Il reste à 20 et passe à 121 lors du test de sonnerie.

Merci.

**Comment by tcharp38** [comment]
Si ca n'est pas le cas deja, bascule sur la derniere beta

puis ecrase le modele avec celui ci (core/config/devices/COSensor-EF-3.0)
[COSensor-EF-3.0.json.zip](https://github.com/KiwiHC16/Abeille/files/8609495/COSensor-EF-3.0.json.zip)

et via la page EQ/avancé... "Reinitialiser"
Tu devrais avoir un "Door status", bool, mais plus le "Zone status" (masqué)
Je peut changer le modele si tu penses que ca n'est pas adequat.

**Comment by ChrisChrisChri** [comment]
Salut, 
Tu sais juste me rappeler comment passer en BETA ? Je me rappelle être passé un jour dessus mais plus moyen de me souvenir comment....

**Comment by tcharp38** [comment]
Salut. 
J'ai fait un chapitre exprès dans la doc en ligne. Partie installation. Si tu trouves pas je regarderai en rentrant de uk. Je n'ai pas les liens là.

**Comment by ChrisChrisChri** [comment]
Salut, 
Je viens de trouver la doc. Je lis les messages d'alertes de Jeedom. Cela ne risque pas de me poser plus problèmes ? Si c'est pour perdre en stabilité du programme,, je préfère encore attendre que chaque fois recommencer.

**Comment by tcharp38** [comment]
Moi je ne fonctionne qu'en beta.
Au pire tu restore ton dernier backup si jamais tu vois une cata mais j'en doute vu que je demande ca à tous ceux qui demandent un support et qu'aucune regression ne remonte pour l'instant. Par contre c'est le code le + avancé.

**Comment by ChrisChrisChri** [comment]
Ok. je vais y passer et on est bien d'accord que je dois repasser par une réinstallation de Abeille. Je vais perdre la totalité des équipements alors ?

**Comment by ChrisChrisChri** [comment]
Salut, 
Voila je viens de passer en BETA. Pour ceux qui ne savent pas, pas besoin de désinstaller la version existante. Il suffit d'aller dans le market et la version BETA est disponible pour téléchargement.

Je vois bien apparaître le doorstatus maintenant. Merci.

![image](https://user-images.githubusercontent.com/82177848/168476614-c15a4a39-4acf-4727-95d6-c956417204cf.png)

Merci. 
Est-ce que cette adaptation est prévue aussi sur le détecteur de fumée de la m^me marque ?

Encore  merci.

**Comment by tcharp38** [comment]
Salut @ChrisChrisChri 
Du coup concernant ce sujet, reste il qqch en attente on peut on le clore ?

Pour ta derniere question je te laisse voir si un sujet est ouvert sinon en creer un specifique. Désolé, je m'embrouille trop en ce moment.

**Comment by ChrisChrisChri** [comment]
Tu peux clôturer alors pour le détecteur CO et je vais ouvrir un nouveau pour le détecteur de fumée.

Encore merci.
