### ISSUE TITLE
Pb reinitialisation d'état sur certain équipement

### ISSUE THREAD

**Issue by pixeldesbois** [KiwiHC16/Abeille#2315]
Bonjour,
J'avais un soucis de perte d'équipements. Du coup, en mode bourrin j'ai refait toute ma conf "abeille" : 
- Mise à à jour de la zigate avec le dernier firmware et effacement de l'eeprom
- suppression du plugin Abeille et re-installation.
Aucun souci à la re-inclusion des équipements.
Mais sur tous les équipements sans fil de type bouton ou interrupteur, l'etat ne se reinitialise plus dans jeedom. Du coup les scenarii associés ne se joue qu'une fois.
Je n'ai pas trouvé le moyen de forcer l'état.
J'ai ce pb sur : 
- Xiaomi remote.b1acn01. C'est le bouton carré
- Xiaomi sensor_switch. C'est le bouton rond
- Xiaomi remote.b286acn01. C'est l'interrupteur double sans fil
- TS0044__TZ3000_vp6clf9d . C'est un interrupteur 4 boutons/12 scenes

Je suis sous Jeedom 4.2.9. firmware 3.21
Y a t-il quelque chose qui a changé ou ai-je un souci dans ma conf ?
Merci par avance

**Comment by tcharp38** [comment]
Salut @pixeldesbois 
Vu que tu as tout réappairé, j espere que tu es parti du FW "OPDM" et non pas legacy. Correct ?

Si je prends le modele "remote.b1acb01", le retour d'état doit s'appeler "etat". Donc tu dois avoir ca dans ton scenario.
Peux tu
- t assurer d etre en mode debug
- appuyer sur le bouton de ton "remote.b1acb01"
- noter l'heure & l'adresse de ton equipement
- mettre ici le package de logs (page support/telecharger tout)
Merci

**Comment by pixeldesbois** [comment]
Salut @tcharp38 
Oui c'est bien le FW 3.21 OPDM.

Le retour s'appelle bien "etat". En cherchant comment contourner le bug, j'avais ajouté un param dans sa configuration avancée pour essayer de forcer le retour à 0 et cela fonctionne mais 1 minute plus tard... pour mon scenario, je me base sur le changement de timestamp. En résumé, c'est bancal mais ca me depanne pour le bouton carre et rond.
En revanche, je ne peux pas contourner le pb pour les interrupteurs sans fil car il n'y a qu'un seul timestamp pour l'équipement et il en faudrait pour chaque bouton des interrupteurs.

Pour le test avec  le modele "remote.b1acb01"
- Adresse (courte/IEEE) : 89E6 / 00158D0001E79060
- Heure : 14:54
- Logs : [AbeilleLogs-220208.tar.gz](https://github.com/KiwiHC16/Abeille/files/8024345/AbeilleLogs-220208.tar.gz)

Merci

**Comment by tcharp38** [comment]
Ce bouton est une nouveauté ?
Quel est son historique ?
Je vois que "etat1" remonte mais pas "etat". Et je vois pas pourquoi ca serait nouveau. D'ou ma question.

**Comment by pixeldesbois** [comment]
C'est effectivement "etat1" (Numerique), sorry... 
"etat" ("binaire") et multi ne semblent pas remonter de valeur qd je clique sur le bouton. Mais pas sûr, je n'ai pas regardé les logs juste le widget.
Ce bouton n'est pas nouveau, je l'ai depuis pas mal de temps. J'avais du faire une demande d'ajout sur l'ancien forum jeedom

**Comment by tcharp38** [comment]
Ok je préfère. 
Résultat des courses ? Toujours un souci ou pas ? Si oui lequel ?

**Comment by pixeldesbois** [comment]
Oui toujours problématique car état1 ne se reinitialise pas tout seul
Pou retirer tout doute, je viens de le sortir du reseau, supprimer de jeedom.
Je l'ai reinitialisé (appui 10 seconde) puis reinclusion.
J'ai toujours "etat" et "état1" qui se créé avec "etat1" qui garde en mémoire la dernière action (donc pb). J'ai regardé dans l'historique et je ne recois pas de valeur pour "etat"  et "multi".

**Comment by tcharp38** [comment]
Si tu as refait une inclusion tu as peut etre un discovery "local". Voir page EQ/avancé. Il te propose de le "Telecharger".
File le si il existe.

J'avoue que je ne comprends pas pourquoi il n enverrait plus les memes infos qu'avant. Son modele n'a pas changé.
Tu me donnes le package de logs et la derniere adresse du bouton ?
Merci

**Comment by pixeldesbois** [comment]
Arf ! j'avais pas vu ton msg...
`Voir page EQ/avancé`
Je ne vois pas ce que c'est ?

Sinon j'ai fait un truc qui contourne mon problème. Ce n'est pas élégant mais ca marche ...
Dans le scénario gérant les actions du bouton, j'ajoute à la fin du script une zone "code" avec :
`cmd::byString("#[Nom de la commmande etat de l'equipement]#")->event(("0"));`

**Comment by tcharp38** [comment]
Page EQ cest en cliquant sur ton equipement, tu as un onglet "avancé".

**Comment by pixeldesbois** [comment]
OK voici le fichier avec tests du jour : 
[event.txt](https://github.com/KiwiHC16/Abeille/files/8040668/event.txt)

Donc 
TEST1 : 
- heure 12:39:51
- hack du scenario activé
`cmd::byString("#[Zigbee][Bouton.Maelia][etat1]#")->event(("0"));`
- param "valeur retour d'état" fait dans la commande état1
- Résultat OK en 2 secondes (dans le scénario j'ai ajouté une pause d'1 seconde avant d'exécuter le code)

TEST2 :
- heure 12:40:37
- hack du scenario désactivé
- param "valeur retour d'état" fait dans la commande état1
- Résultat OK mais à 12:42:02 - trop long

TEST3 :
- heure 12:42:20
- hack du scenario désactivé
- param "valeur retour d'état" retiré
- Résultat KO - j'ai fait un clic quelques minutes plus tard pour te montrer qu'il ne s'était rien passé

En espérant que cela puisse aider

**Comment by tcharp38** [comment]
@pixeldesbois 
Donne moi vite le package de logs qui va avec STP

**Comment by pixeldesbois** [comment]
[AbeilleLogs-220210.tar.gz](https://github.com/KiwiHC16/Abeille/files/8041171/AbeilleLogs-220210.tar.gz)

**Comment by tcharp38** [comment]
Si on regarde juste les evenements enregistrés par Jeedom (donc qui lui sont transmis)

[2022-02-10 12:27:26][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 0

[2022-02-10 12:39:51][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 1
[2022-02-10 12:39:51][INFO] : Evènement sur la commande [Chambre Maelia][Bouton Maelia][etat] valeur : 1

[2022-02-10 12:39:53][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 0
[2022-02-10 12:39:53][INFO] : Evènement sur la commande [Chambre Maelia][Bouton Maelia][etat] valeur : 0

[2022-02-10 12:40:37][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 1
[2022-02-10 12:40:37][INFO] : Evènement sur la commande [Chambre Maelia][Bouton Maelia][etat] valeur : 1

[2022-02-10 12:42:02][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 0
[2022-02-10 12:42:02][INFO] : Evènement sur la commande [Chambre Maelia][Bouton Maelia][etat] valeur : 0

[2022-02-10 12:42:20][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 1
[2022-02-10 12:42:20][INFO] : Evènement sur la commande [Chambre Maelia][Bouton Maelia][etat] valeur : 1

[2022-02-10 12:46:05][INFO] : Evènement sur la commande [Zigbee][Bouton.Maelia][etat1] valeur : 1

J'en conclus tu as appuyé le bouton
- à 12:39:51, relaché à 12:39:53
- à 12:40:37, relaché à 12:42:02 => ?? relaché si longtemps apres ?
- à 12:42:20, relaché à ??? => Il manque un retour à 0 ici mais je ne vois pas la trace. Ton log parser est trop vieux.

En ligne avec ca ?

Quand tu n'utilises pas ton "hack", tu mets quoi à la place pour declencher le scenario ?

**Comment by pixeldesbois** [comment]
[Zigbee][Bouton.Maelia] correspond à l'équipement physique
[Chambre Maelia][Bouton Maelia][etat] est juste le virtuel correspondant

Je n'ai pas fait d'appui long juste des clics rapides.
Ce que tu appelles "relaché" correspond à
- 12:39: 53 au hack excecuté dans le scenario
- 12:40:02 au retour d'état paramétré dans la commande (conf avancé)

A 12:42, il n'y avait justement aucun contournement de paramétré pour te montrer qu'il a un problème car justement je n'ai pas de "relaché" automatiquement

Je ne mets rien à la place du scenario.

`En ligne avec ca ?`
J'ai pas compris sorry !

**Comment by tcharp38** [comment]
C est moi qui suis désolé. Je ne comprends rien du tout et je vais devoir m'y repencher à tete reposée.
Mais en gros ce que fait Jeedom.. ca me parle pas. J'ai besoin d'isoler le pb au niveau plugin et la je sais pas si il y en a un et lequel.

Le hack et les trucs avancés (typiquement param retour d'etat activé/desactivé??) dont tu parles ... ne me parlent pas. Jeedom n'est pas intuitif et mal documenté.

Bref, quelle est ta vue des choses cote plugin Abeille ?

**Comment by pixeldesbois** [comment]
Pas de souci et puis c'est compliqué quand on ne dialogue pas de vive voix avec le matos sous les yeux (...et l'apéro...).

Si on revient sur le besoin initial, je dirais qu'au niveau du plugin on récupère bien l'état de l'équipement. Suivant l'équipement, cela sera la détection d'un simple clic, double clic, long clic etc... Cet état remonte à Jeedom au moment de l'appui ou de relâchement en fonction de l'équipement.
Au niveau du plugin, cet état ne revient pas à une valeur par défaut et conserve la dernière valeur récupérée.

Prenons un exemple : un bouton qui ne gère qu'un simple clic. Quand je l'appaire son état= 0. Je clique alors état=1 mais ne change plus dans Abeille. Donc au prochain clic, le plugin va remonter à nouveau la valeur 1 et il sera donc impossible de savoir qu'il ya eu un nouveau clic au niveau d'un scénario par exemple qui se déclencherait en fonction du changement d'état.

Au niveau du plugin Abeille, l'idéal serait une option activable par équipement (dans le Json ?) pour remettre un valeur par défaut après 1s.
Cela me pensait qu'à une époque il y avait une fonction "Timer" dans le plugin Abeille qui n'apparrait plus. Un lien avec mon pb ?

**Comment by pixeldesbois** [comment]
Hello,
On pourra dire que c'est mon côté informaticien "KaimePôLesTicketsOuvertsLongtemps" mais je préfère clore à résolu cet issue.
Ca fait une semaine que l'astuce mise dans mes scénarii est en place et cela répond finalement bien au besoin que de remettre l'info de l'état à une valeur donnée.

@tcharp38 Je tenais à dire un grand Merci car c'est dans cet échange que cette idée est sortie.

Finalement au niveau du plugin, je pense qu'il est difficile de "piloter" ces états car le besoin n'est pas dans le plugin en lui même mais au niveau des scénarii (je ne sais pas si je suis clair...)

Pour ceux qui auraient le même besoin que moi, la commande ci-dessous ajoutée à la fin de l'execution du scénario permet de reinitialiser l'état :
`cmd::byString("#[REFERENCE]#")->event("XXXXX");`

[REFERENCE] est à remplacer par la commande info de l'état de l'équipement à réinitialiser
"XXXXX" est  à remplacer par la valeur desirée. exemple "0" ou "" pour vide
