### ISSUE TITLE
Problème après mise à jour zigate USB v1

### ISSUE THREAD

**Issue by baloo53** [KiwiHC16/Abeille#2316]
Bonjour,
Suite à des messages du plugin qui me disait que la zigate que je procède était pas à jour je décide de le faire.
Je passe sur la version : ZiGatev2-320.bin
Tout se passe bien et je relance mon raspi et tout est encore bon.
Néanmoins, pour le plugin abeille je remarque le message:
« Mauvais port détecté pour zigate 1. Tous ses messages sont ignorés par mesure de sécurité. Assurez vous que les zigates restent sur le meme port, même après reboot. »

J’ai relancer le démon, relancé mon raspi mais j’ai toujours ce message avec du coup l’impossibilité d’actionner mes équipement inclus dans abeille.

J’ai lu un sujet ou la personne avait réussi en cliquant sur « ReplaceZigate » mais je tombe sur une page avec écrit " Forbidden You don’t have permission to access this resource."

J'ai essayé le mode inclusion et ma clé se met bien à clignoter.
Je précise que j'ai qu'une seul clé sur un hub
Dans abeille:
`[2022-02-08 10:10:19]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:24]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:29]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:34]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:39]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:44]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:49]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:54]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:10:59]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:11:02]DEBUG : checkAllDaemons() => ok
[2022-02-08 10:11:02]DEBUG : cron1: 4257/SerialRead1, 4259/Parser, 4261/Cmd
[2022-02-08 10:11:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/0000\/getZgVersion&time=1644311482","payload":""}' vers queue 123
[2022-02-08 10:11:02]DEBUG : cron1: GetEtat/GetLevel, addr=229d
[2022-02-08 10:11:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/229d\/readAttribute&time=1644311462","payload":"ep=0B&clustId=0006&attrId=0000"}' vers queue 123
[2022-02-08 10:11:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/229d\/readAttribute&time=1644311462","payload":"ep=0B&clustId=0008&attrId=0000"}' vers queue 123
[2022-02-08 10:11:04]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:11:09]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:11:14]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:11:19]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
[2022-02-08 10:11:25]DEBUG : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}`
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8023135/AbeilleCmd.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8023137/AbeilleSerialRead1.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/8023134/AbeilleConfig.log)
![Sans titre](https://user-images.githubusercontent.com/99254403/152974397-8915a8da-3afa-4651-85b0-7a8baeacf447.png)

Auriez-vous une solution pour moi?
Merci d'avance de votre aide

**Comment by tcharp38** [comment]
Salut @baloo53 
L'affichage de la page de config que tu montres dit "Zigate USB v1" et FW v3.0f (donc legacy).
C etait ton ancienne zigate c est ca ?
Sinon je ne comprends pas pourquoi tu parles de v2.

**Comment by baloo53** [comment]
Non j'ai essayé plusieurs maj sur le site zigate (ancienne et récente) pour voir si sa allait résoudre mon problème et non toujours pareil peut importe la mise à jour le plugin abeille m'indique le même message d'erreur alors que tout semble ok

**Comment by tcharp38** [comment]
Donc tu n'as qu'une zigate et c 'est une zigate USB v1.  C'est ca ?

**Comment by baloo53** [comment]
Oui j'ai qu'une seule clé v1 (la rouge) sur un hub

**Comment by tcharp38** [comment]
Ok donc surtout PAS de FW v2. Je suis d'ailleurs surpris que tu puisses le flasher.

Soit tu prends le 3.21-legacy SANS erase EEPROM et tu n'as normalement pas de reappairage à faire
Soit tu prends le 3.21-OPDM AVEC erase EEPROM (obligatoire), puis réappairage de tous tes equipememts.

D'apres ta page de config tu es toujours dans un vieux FW. Ou alors c 'etait avant ?
![image](https://user-images.githubusercontent.com/35221038/153038291-74a34b74-ddfe-42ae-848a-94c5d51469d2.png)

Comment as tu procédé ?

**Comment by baloo53** [comment]
Et bien j'ai suivi cette procédure:
https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

Je vais essayer ta procédure après le boulot je te tiens au courant.
En revanche je suis obligé de réapparailler tout mes équipements ? C'est à dire démonter tout mes interrupteurs,prises etc pour appuyer sur le trou de reset et refaire une inclusion?

**Comment by baloo53** [comment]
Bon j'ai installé la : ZiGate_v3.21-legacy.bin
Tout semble bon j'ai plus de message d'erreur. 
En revanche impossible à piloter mes équipements j'ai essayé dans réinitialiser 2/3 et sa me les inclus plus :/

**Comment by tcharp38** [comment]
Donc cette fois la page de config t'affiche bien 0003-0321 ?

As tu fait ERASE EEPROM ou pas ?

**Comment by baloo53** [comment]
Oui c'est bien affiché 0003-0321et j'ai pas fais de ERASE EEPROM car j'ai pris la version legacy.
J'aurais du le faire au final?
![Sans titre11](https://user-images.githubusercontent.com/99254403/153184447-d1f887d7-927c-483f-a472-0d8578c80846.png)

**Comment by tcharp38** [comment]
Ok parfait.

L'ideal un jour est de basculer sur  une OPDM mais c est le jour ou tu sera pret à refaire tous les appairages.

Du coup la page santé dit quoi ?
Peux tu me donner un package de logs ?

J'ai une crainte: l'installation de mauvais FW (tu m'as parlé de v2) a peut etre cassé les tables en EEPROM, celles qui memorisent ton reseau. Du coup, a voir mais si aucun equipement ne remonte les infos, tu n'aura peut etre pas le choix de faire un erase PDM et reappairer. Mais a confirmer. je vais voir tes logs deja

**Comment by baloo53** [comment]
Je te donne sa après mon boulot. Mais en effet lors des mes tentatives à mettre à jour la clé j'ai déjà fais un erase. J'ai vraiment suivi toute la procédure du site zigate (lien au dessus)

**Comment by tcharp38** [comment]
Ok donc si tu as fait un erase, la zigate ne connait plus aucun reseau ni equipement. Reappairage necessaire.
Mais dans ce cas je te suggere de basculer tout de suite sur une version OPDM. Donc reflash la + ERASE.

Et reappairage complet :(

Et pour cette info
![image](https://user-images.githubusercontent.com/35221038/153236563-0b6f267a-eee4-4359-b793-b2f226f39edc.png)
elle n'est pas claire.
Si PREMIERE UTILISATION, ou passaage LEGACY vers PDM, ou CORRUPTION PDM

**Comment by baloo53** [comment]
Je vais faire sa oui en revanche avec ma configuration actuelle j'arrive pas non plus à faire une inclusion c'est normal car j'ai essayé justement et rien. :/ 

Oui c'est vrais que ta procédure à toi est plus claire ^^

**Comment by tcharp38** [comment]
Bizarre. Mais vu que l erase eeprom est fait, autant repartir que de bonnes bases. Donc 3.21 opdm + erase eeprom et on refait le point.
La version affichée dans la page de config devra être 0004-0321 du coup.

**Comment by baloo53** [comment]
Oui j'ai bien la version 0004-0321 affichée mais impossible d'inclure mes équipements (testé sur plusieurs)

Voici mes log en mode debug
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/8038948/Abeille.txt)
[AbeilleConfig (2).log](https://github.com/KiwiHC16/Abeille/files/8038949/AbeilleConfig.2.log)
[AbeilleCmd (1).log](https://github.com/KiwiHC16/Abeille/files/8038950/AbeilleCmd.1.log)
[AbeilleSerialRead1 (2).log](https://github.com/KiwiHC16/Abeille/files/8038951/AbeilleSerialRead1.2.log)
![Sans titre7](https://user-images.githubusercontent.com/99254403/153359543-e6da8035-235e-49a1-b998-1bde515f75d3.png)

Vais pas m'en sortir haha 
Merci de ton aide en tout cas

**Comment by tcharp38** [comment]
Mais si tu vas t en sortir.

Tes logs sont tous aussi vieux que l' autre fois. Es tu en mode debug ? J'en doute. Puis redemarrer Abeille.
Et pour le package de logs, tu passes par la page support (Plugins>Protcole domotiqe>Abeille>Support) puis telecharger tout. Le package est complet et c'est + simple pour toi.

**Comment by baloo53** [comment]
Alors je suis passé en mode debug la et j'ai redémarré le demon puis j'ai téléchargé (en effet plus pratique ^^)
[AbeilleLogs-220210 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8039722/AbeilleLogs-220210.1.tar.gz)

**Comment by tcharp38** [comment]
Ok, il te faut relancer l'appairage (inclusion) de chacun de tes modules puisque "erase eeprom" a effacé la mémoire de la zigate.

Donc mode inclusion
puis progressivement forcer le module à se reannoncer.

**Comment by baloo53** [comment]
Et bien c'est se que je fais (enfin je pense) je reset un interrupteur par exemple (Legrand) j'ai bien la led rouge. Puis je clique sur inclusion (ma zigate clignote bleu) mais rien se passe

**Comment by tcharp38** [comment]
Chaque equipement a sa propre procedure d'inclusion.
Tu as des Xiaomi ? C est facile pour ca, en general tu maintiens le bouton 10sec et il doit s'annoncer.
A ne faire que lorsque la zigate est en mode inclusion (clignote)

**Comment by baloo53** [comment]
J'ai un détecteur de mouvement aqara même chose :/ pareil pour une clé USB répéteur et pour mes modules Legrand. :/

**Comment by baloo53** [comment]
J'ai un détecteur de mouvement aqara même chose :/ pareil pour une clé USB répéteur et pour mes modules Legrand. :/

**Comment by tcharp38** [comment]
Tu me redonne un package de logs ?

**Comment by baloo53** [comment]
J'ai refais la manipulation avec deux appareils sans succès.
[AbeilleLogs-220211.tar.gz](https://github.com/KiwiHC16/Abeille/files/8046859/AbeilleLogs-220211.tar.gz)

**Comment by baloo53** [comment]
je dois pas faire un reset sur le plugin ou autre à tout hasard?

**Comment by tcharp38** [comment]
Non je ne vois pas.

Aucun device ne s'annonce.

Ca ressemble à la meme manip d'un autre utilisateur.

Tu peux tenter un dernier truc.
Erase PDM en cliquant sur la ruche, onglet avancé, puis retenter une inclusion.
Tant que tu ne vois pas un "Device announce" dans le log parser c'est qu'un equipement n'arrive à atteindre Abeille.

**Comment by baloo53** [comment]
Non rien du tout :/

**Comment by Jake309** [comment]
#2247 
J'ai remis des news dans mon issue d'origine

**Comment by baloo53** [comment]
Pour moi tout est ok avec la maj, ma clé zigate est bien reconnu et communique bien. Sur le plugin abeille si je la teste sa me dis ok avec la bonne version.
Mais je n'arrive plus à inclure mes équipements

**Comment by Jake309** [comment]
J'ai eu le meme pb que toi @baloo53 . tout allait très bien mais impossible d'inclure. quand j'appuyais sur le bouton inclusion, la led clognotait etc, mais jamais un équipement ne s'ajoutait.
J'ai essayé avec le logiciel testgui, avec la procédure sur le site de zigate, et la je me suis rendu compte que rien ne communiqué, c'est ce qui m'a permis de savoir que c'était ni abeille ni jeedom mais la zigate en elle meme. 
J'ai du en acheter une nouvelle. Depuis plus de pb.
Je n'ai jamais eu de retour depuis le site zigate ou le github fairesoitmeme. C'est dommage. ca demande pourtant à se pencher dessus...
Tout le monde n'est pas aussi énervé que nos dev abeille ^^

**Comment by tcharp38** [comment]
@baloo53 
Tu peux tenter les tests suggerés sur le site ?
https://zigate.fr/documentation/tester-la-zigate-usb/

**Comment by baloo53** [comment]
Je confirme que ma clé fonctionne bien (c'est déjà sa de pris ^^) le problème viens d'ailleur.
![testZ](https://user-images.githubusercontent.com/99254403/153700777-44499f98-1e4a-427c-9d53-34b89cce325d.png)

**Comment by Jake309** [comment]
La champs recieve message a l'ascenseur pas tout en bas, c'est voulu, c'est ton dernier message affiché ? 
Mais si en mettant un équipement en inclusion tu as des lignes qui apparaissent dans raw message c'est gagné :) 
Perso quand je faism permis to join, j'ai un message pas normale a droite et après plus rien dans raw message.

**Comment by baloo53** [comment]
Non moi tout fonctionne très bien :) c'est vraiment pas un problème de clé pour moi

**Comment by Jake309** [comment]
Top, tant mieux, c'est cool. 
Pour le pb de port, j'avais le même,  j'ai modifié un fichier en ssh pour automatiser le port et ne plus avoir le message. J'avais fait la modif pour les 2 version de clé, et quand j'ai eu la v2, ça a marché du feu de dieu aussi 
Des que je suis sur le pc dans la matinée, je te donne ça :)

**Comment by baloo53** [comment]
Et bien pourquoi pas oui merci mais depuis que @tcharp38 ma fait changé la version de ma zigate j'ai plus de message d'erreur de port. Pour résumé tout est au vert , ma clé est ok le plugin m'indique OK mais aucune intégration se fait et j'ai aucun message d'erreur :/

**Comment by Jake309** [comment]
Alors, j'ai vue plus haut, tu ne fais pas l'inclusion dans le bon sens. Tu dois d'abord passer ta zigate en inclusion (via le bouton vert), tu vérifis qu'elle clignote (c'est la ou souvent j'avais le pb) des que tu la vois clignoter, tu mets un équipement en inclusion.
Si tu as des prises, commence par ca, c'est le plus facile. Le detecteur de mouvement par exemple, oublie tant qu'on est pas sur que tout va bien, c'est fastidieux à réintégrer. Si pas de prise, reste sur ton interupteur legrand alors.
Si tu n'as pas de souci, on va pas changer un fichier de configuration pour le plaisir, c'est inutile, ca rajouterai une brique au débugage.

**Comment by Jake309** [comment]
perso je n'ai pas systemétiquement la notif qui dit que mon équipement s'est réannoncer et qu'il se met a jour, je regarde via le bouton santé à coté de config. S'il repasse en OK à l'heure de l'inclusion c'est bon, après, tu peux aussi regardé dans le temps réel en appuyant sur ton interrupteur, tu verras les lignes apparaitre

**Comment by baloo53** [comment]
Toujours rien :p

Mais j'ai sa dans les log 
`[2022-02-12 08:22:25]     Port '/dev/ttyUSB0' non accessible. Commande '0010' non écrite.
[2022-02-12 08:23:03]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:04]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:05]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:06]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:07]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:08]     Port '/dev/ttyUSB0' non accessible. Commande '0100' non écrite.
[2022-02-12 08:23:23]     Port '/dev/ttyUSB0' non accessible. Commande '0010' non écrite.
[2022-02-12 08:23:24]     Port '/dev/ttyUSB0' non accessible. Commande '0010' non écrite.
[2022-02-12 08:23:25]     Port '/dev/ttyUSB0' non accessible. Commande '0010' non écrite.`

**Comment by Jake309** [comment]
Ok, alors je te propose de faire la manip #2222 de JLucB-58, car tu as quand même un pb de port.
Mais j'ai l'impression que ca a changé car j'ai plus tout à fait son screen dans jeedom.
Pour info, mon test me renvoie avec ma v2:
`lrwxrwxrwx 1 root root 7 févr. 11 13:53 /dev/ttyUSBZigateV2 -> ttyUSB0`
et dans jeedom j'ai 
![image](https://user-images.githubusercontent.com/49479084/153702178-3ee0d1cf-97fa-442b-9139-549be59dc4d8.png)

**Comment by Jake309** [comment]
la manip est réversible, car tu vas le créer le fichier, donc facile de le retirer et revenir en arrière.
Perso, quand je modifie ce genre de chose, et que ca touche le matos, je redémarre toujours le serveur pour eviter des bug. essaie sans, et si c'est pas concluant, reboot pour tester.
Comme dirait le vieux jeune, dans le doute, reboot ^^

**Comment by baloo53** [comment]
Ta fais sa via Putty?
Moi j'ai pas de fichier cd /etc/udev/rules.d

**Comment by Jake309** [comment]
oui avec putty.
c'est un répertoire, pas un fichier.
Si tu fais cd /etc [entrée], puis cd /udev [entrée] puis cd /rules.d [entrée] et quand il te dit qu'un de ceux la existe, tu écris cd /etc/.../   jusqu'à avant le message et tu fait double tab pour lister les dossiers qui se trouvent dans ton dossier.
Mais normalement tu devrais l'avoir, je n'avais rien installer de particulier.

Ha si, est ce que tu t'es connecté en root ? c'est surement ca.

**Comment by baloo53** [comment]
Désolé mais j'ai pas tout compris la deuxième partie.
J'écris cd/etc/.../ ??? Je comprends pas la.

**Comment by Jake309** [comment]
Déjà, es tu en Root quand tu tapes les commandes ?
Écrit cd /etc/ [entrée], puis cd /udev/ [entrée] et cd /rules.d/ [entrée]
Sur quel cd ça te mets un message qui te dit qu'il ne trouve pas ?

**Comment by baloo53** [comment]
Oui je suis en mode root c'est bon. puis entrer cd /etc/ mais après pour cd /udev/ sa me dis que sa n'existe pas

**Comment by Patag** [comment]
Salut,
Il y a un problème avec les "/".
Essaye cd /etc/udev/rules.d en respectant les espaces et les /
ou

cd /etc [entrée]
cd udev [entrée] (pas de /)
cd rules.d [entrée] (pas de /)

**Comment by baloo53** [comment]
cd /etc/udev/rules.d à fonctionné sa me met:
pi@raspberrypi:/etc/udev/rules.d $

**Comment by Jake309** [comment]
c'est bon, tu es dans le bon repertoire, autant pour moi, je comprends pas ma synthaxe fonctionne chez moi.
Le pi @ et le $ me font dire que tu n'es pas en root mais en utilisateur pi.
Si tu connais le mot de passe root, il faut t'identifier avec: su - [entrée] et tu devras rentrer le mot de passe, il ne s'affiche pas quand tu le tapes, ne t'inquiètes pas si tu vois rien.

**Comment by baloo53** [comment]
Maintenant j'ai root@raspberrypi: /etc/udev/rules.d#

**Comment by Jake309** [comment]
ok, tu peux fais la suite de la procédure:
nano 99-usb-serial.rules
et copier coller : 
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{product}=="ZiGate", ATTRS{manufacturer}=="Silicon Labs", SYMLINK+="ttyUSBZigateV1"
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", ATTRS{product}=="ZiGate", ATTRS{manufacturer}=="FTDI", SYMLINK+="ttyUSBZigateV2"
et c'est de souvenir ctrl + x pour quitter, il te demander si tu veux sauvegarder, tu as le nom qui s'affiche (nano 99-usb-serial.rules), tu fais entrée

**Comment by baloo53** [comment]
c'est fait. 
Sa à pas résolut mon problème je peux toujours pas inclure d'équipement

**Comment by baloo53** [comment]
j'aurais jamais du faire la maj hahaha bon je vous renvois mes log après un redémarrage demon en mode debug et une tentative d'inclusion.
[AbeilleLogs-220213.tar.gz](https://github.com/KiwiHC16/Abeille/files/8055758/AbeilleLogs-220213.tar.gz)

**Comment by tcharp38** [comment]
Salut.
Je n'ai pas suivi toutes vos manips mais je ne vois aucun "device announce" dans le log parser. Donc aucun equipement qui s'annonce.
En meme temps le log est tres tres court . 2min environ.
Mais la clef semble bien reconnue et repond.

**Comment by baloo53** [comment]
Salut @tcharp38 
Oui je suis perdu et j'ai essayé avec plusieurs équipement legrand, une clé répéteur, un ruban led et une prisse osram. 
[AbeilleLogs-220213.tar.gz](https://github.com/KiwiHC16/Abeille/files/8055807/AbeilleLogs-220213.tar.gz)

**Comment by baloo53** [comment]
Solution trouvé j'ai fais tout les ports de mon hub et sa à fonctionné à force.
Merci à vous pour votre aide

**Comment by tcharp38** [comment]
T'es en train de dire que la conclusion de tout ça est que la zigate etait perturbée (surement electrique) ?!
On sait aujourd hui que sur RPI4 par ex, les SSD pourrissent le fonctionnement de la zigate mais la il y a quoi sur ton hub ? Quel type d'ailleurs ? Auto alimenté ou via le RPI ?

**Comment by baloo53** [comment]
J'ai un hub de 4 port directement alimenté sur mon rpi4 et enfaîte j'ai juste changé de port une première fois puis une deuxième et la troisième c'était bon haha

**Comment by tcharp38** [comment]
Ok. Donc soit la clef etait trop proche de qqch, soit le port à une particularité.
Mais tant mieux.
Mais j'aime pas les "non explications" :) Ca peut toujours revenir.

**Comment by baloo53** [comment]
Oui j'ai refais un test et dès que je change de port sa fonctionne plus.
