### ISSUE TITLE
Support Telecommande 4 Fonction Evology (3450-Geu, CentraLite)

### ISSUE THREAD

**Issue by burzy76** [KiwiHC16/Abeille#2318]
bonjour je souhaite inclure une télécommande 4 fonction de marque Evology avec le protocole Zigbee mais jeedom la reconnait bien mais pas les 4 boutons .
comment peut-on faire pour faire apparaitre ces 4 boutons ?

![Telecommande-portable-connectée-4-fonctions-Evology-Enky](https://user-images.githubusercontent.com/99336018/153205315-1e4edbcb-1024-46a0-a98a-9555afb29472.jpg)
 je vous mets le fichier discovery.json ainsi que la photo de la [télécommande]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8032905/discovery.zip)

merci d'avance de votre aide

**Comment by mickadam29** [comment]
Idem pour moi mais avec ce modèle pour @burzy76 . On verra si le code de la première fonctionne
![image](https://user-images.githubusercontent.com/36518012/153285939-d7d25620-5a94-4769-9e1f-29e7df458839.png)

**Comment by tcharp38** [comment]
Salut @burzy76 

A decompresser dans core/config/devices
Puis redemarrer Abeille
et refaire inclusion

[3450-Geu_CentraLite.zip](https://github.com/KiwiHC16/Abeille/files/8209379/3450-Geu_CentraLite.zip)

Penses à passer en mode debug (sauvegarde + redemarrer)

Une fois l'inclusion faite, peux tu faire une action sur chaque bouton, noter l'heure, et me filer le package de logs (page support/telecharger tout).

Merci

**Comment by tcharp38** [comment]
Memo: https://www.centralite.com/downloads/Datasheet-3Series4ButtonKeyFob_EU.pdf

**Comment by burzy76** [comment]
d'abord merci de travailler sur ce sujet , j'ai décompresser le fichier et supprimer la télécommande puis passer en mode debug j'ai inclus la télécommande et appuyer sur chaque bouton "l'ordre voir la photo " puis télécharger le fichier demandée donc ma télécommande a bien été reconnu mais au niveau des boutons comment cela va être représenter et comment je vais pouvoir les paramétrer car la j'ai rien sur le dashboard 
merci d'avance et en espérant que j'ai bien réussi la procédure   
![image_2022-03-09_104547](https://user-images.githubusercontent.com/99336018/157415881-4e9b51f7-dcee-448c-9278-e978d9610014.png)
[AbeilleLogs-220309.tar.gz](https://github.com/KiwiHC16/Abeille/files/8213519/AbeilleLogs-220309.tar.gz)

**Comment by burzy76** [comment]
mince en relisant mon message j'ai oublier de noter l'heure donc j'ai refait l'appuie sur les boutons l'ordre reste inchangé donc
1 => 11h43
2 => 11h44
3 => 11h45
4 => 11h46 
voila le fichier
[AbeilleLogs-220309 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8213951/AbeilleLogs-220309.1.tar.gz)

**Comment by tcharp38** [comment]
Hello.
Bon je ne vois aucune remontée des boutons.

Mais qq requetes
- passer le log à 5000 lignes. 500 c est trop court: https://kiwihc16.github.io/AbeilleDoc/Debug.html#configuration-jeedom-pour-les-logs
- basculer sur la beta. Comme ca tu sera sur le dernier code: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

Je vais revoir ma copie pour le modele.

**Comment by burzy76** [comment]
donc je pense être en Beta mis en mode debug et mis 5000 lignes pour le log appuis sur les boutons 
1 => 13h24
2 => 13h25
3 => 13h26
4 => 13h27
télécharger le fichier :
[AbeilleLogs-220309 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8214659/AbeilleLogs-220309.2.tar.gz)

**Comment by tcharp38** [comment]
[3450-Geu_CentraLite.zip](https://github.com/KiwiHC16/Abeille/files/8215159/3450-Geu_CentraLite.zip)

Decompresser par dessus l'autre
Refaire inclusion
Refaire manip en notant les heures
Et me filer le package de logs.

Merci

**Comment by burzy76** [comment]
j'ai décompresser le fichier par contre il y a que le fichier central lite .json alors que le 1er fichier avait le fichier central lite et discovery , je l'ai donc remplacer par l'ancien et refait une inclusion et fait un fichier log et en plus je te donne l'image png
![telecommande](https://user-images.githubusercontent.com/99336018/157473301-2fc14e12-1ce7-4994-9670-05c9ecb0f751.png)
le fichier
[AbeilleLogs-220309.tar.gz](https://github.com/KiwiHC16/Abeille/files/8215889/AbeilleLogs-220309.tar.gz)
l'ordre des boutons reste inchangé
1er bouton a 16h15
2eme bouton a 16h16
3eme bouton a 16h17
4emebouton a 16h18
merci d'avance en espérant que je fait bien les manips demandées car c'est la 1er fois que je me lance dans cette aventure

**Comment by tcharp38** [comment]
Le seul fichier utile pour Abeille est '3450-Geu_CentraLite.json'.
Le discovery ne sert qu'au dev pour mettre en place le modele ou pour info.

Tu n'as pas refait l'inclusion avec mon modele. Du coup aucun changement :(

Reprends bien mon dernier zip pour ecraser le precedent,
puis reinclusion
et package
On peut se contenter du bouton 1 pour l'instant

**Comment by burzy76** [comment]
bon j'ai refait les manips => mis le fichier , supprimer la télécommande puis reinit la télécommande et inclure la télécommande a abeille puis a 19h15 appuyer sur le bouton 1 et télécharger les logs 
seule chose que j'ai pas fait redémarrer pluing car je suis pas sure de moi de la manip 
est ce que relancer les dépendances et redémarrer  le démon est la manip ?
[AbeilleLogs-220309 .tar.gz](https://github.com/KiwiHC16/Abeille/files/8217134/AbeilleLogs-220309.tar.gz)

**Comment by burzy76** [comment]
par contre mettre le pluing en beta c'est pareil je suis pas sure d'avoir reussi 
![image_2022-03-09_193026](https://user-images.githubusercontent.com/99336018/157507540-98c84711-067f-4f44-b707-596305e92c0d.png)
est ce bon car la je vérifie tout mais  je suis totalement larguée
merci d'avance

**Comment by tcharp38** [comment]
Ok pas de panique. On va y aller pas à pas.

Pour redemarrer Abeille, ca se fait via la page de config (celle que tu montres)
![image](https://user-images.githubusercontent.com/35221038/157632198-f4571e90-9b8b-4da3-aa48-def9ebac899b.png)

Concernant la beta.. je pense que tu n'y es pas. Tu sembles sur le master mais ca le fait aussi
![image](https://user-images.githubusercontent.com/35221038/157632354-72f1af68-5e0a-422f-991b-af625c0a533c.png)
Pour confirmer fais moi un snapshot de la page "Reglages > Systeme > Centre de mise à jour".

Pour finir, tu n'utilises pas le dernier modele que je t'ai envoyé. Il a du etre ecrasé par le changement de version.

**Comment by burzy76** [comment]
bonjour donc oui je suis en master 
![image_2022-03-10_132248](https://user-images.githubusercontent.com/99336018/157660922-65f0194b-c654-408b-a361-2ea3436c3a5d.png)

**Comment by tcharp38** [comment]
Ok. Ca n'est pas conseillé car c'est la branche qui bouge le + mais pour l'instant ca le fait. Elle est en ligne avec la derniere BETA.

Donc
- remets le DERNIER modele que je t'ai envoyé dans core/config/devices/3450-Geu_CentraLite
- redemarre Abeille (page de config/demon)
- refais une inclusion
- puis clique sur le bouton 1
- et file moi le package de logs
Merci

**Comment by burzy76** [comment]
donc comme j'avais deux fois abeille avec "a "minuscule et "A" majuscule ,j'ai effacer le "a" minuscule 
puis j'ai remis les derniers fichiers dans 3450-Geu_Centralite et redémarrer le pluing 
essaie de faire inclusion sans supprimer l'ancien nok reconnait pas mais j'ai supprimer ancien et refait inclusion ok reconnait la télécommande et appuyer sur le bouton 1 a 14h31 et voici le fichier 
[AbeilleLogs-220310.tar.gz](https://github.com/KiwiHC16/Abeille/files/8223803/AbeilleLogs-220310.tar.gz)

**Comment by tcharp38** [comment]
Yess.. cette fois il y a de la vie.
L equipement etait deja reconnu avant que tu ne le supprimes coté Jeedom.

Bouton1 => EP03

Je reviens vers toi apres reflexion sur la suite des operations.

**Comment by tcharp38** [comment]
220310-BETA-2 a tester demain.
Refaire inclusion
click bouton 1
et package de logs

Tu devrais avoir une commande "Status 1" qui bouge

**Comment by burzy76** [comment]
je me suis aperçu qu'il y avait une mise a jour celle ci installer  attention tjs en master , j'ai refait une inclusion de la télécommande et appuyer a 14h02 sur le bouton 1 et sauvegarder les logs 
[AbeilleLogs-220311.tar.gz](https://github.com/KiwiHC16/Abeille/files/8232064/AbeilleLogs-220311.tar.gz)
![Capture3](https://user-images.githubusercontent.com/99336018/157872492-a8257f83-f0fc-4a62-95f1-139a9215c367.JPG)

**Comment by tcharp38** [comment]
Oui etant sur le master tu risques d'en avoir tous les jours.
Tant qu'on est en mode "support" pour toi c'est pas un souci. Ca te permet juste d etre "a la page". mais apres il faudra que tu bascules sur la beta, voir la stable si tu n'as plus de pbs necessitant du support.

J'ai l'impression qu 'il y a melange. Ce sujet est pour la remote Evology, et non pas pour ZBEK-4_Adeo.
Du coup pas de trace de ton "appui" à 14h02. Tes logs s'arretent @ 13:24:27

**Comment by burzy76** [comment]
j'ai regarder et la des après la mise a jour , j'ai deux pluings abeille qui apparait "a" minuscule et "A" majuscule donc effacer celui du "a" et refait une inclusion de la télécommande et appuyer sur le bouton 1 a 16h34 et télécharger le fichier 
[AbeilleLogs-220311 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8233285/AbeilleLogs-220311.1.tar.gz)
mais oui je compte bien revenir sur du stable après que tout cela soit régler

**Comment by tcharp38** [comment]
Idem... tes logs s'arretent à 2022-03-11 13:24:27
Donc je pige pas du tout mais deja, le fait qu'il y ai 2 plugins... c est pas bon du tout.

Bascule sur la beta en suivant ca: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta
Attention !! Tu dois installer la beta VIA LE MARKET .. et non pas via Github comme tu sembles l'avoir fait.

![image](https://user-images.githubusercontent.com/35221038/157910176-b0de9469-cead-4067-ac11-fe52ee1a5507.png)

**Comment by burzy76** [comment]
bon au faite je ne pouvait pas mettre la version beta car il faut cocher la case autorisation pluing beta dans ton jeedom market "profil" et puis je l'ai installée et refait une inclusion de cette fameuse télécommande et youpi je vois le fameux status 1 que tu me parlait  "icone lumière éteinte" et des que j'ai appuyer sur le bouton 1 a18h24,  l'état de cette lumière a changer "allumée" yes enfin et je te donne le fichier 
[AbeilleLogs-220311 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8234075/AbeilleLogs-220311.2.tar.gz)
en tout cas merci pour tout et de ta patience

**Comment by tcharp38** [comment]
Cool. Ca avance.
Peux tu maintenant presser les autres boutons, noter l heure, et me filer package de logs et l'heure correspondante.

**Comment by burzy76** [comment]
l'ordre des boutons reste inchangé
1er bouton a 11h10
2eme bouton a 11h11
3eme bouton a 11h12
4emebouton a 11h13
et voici le fichier 
[AbeilleLogs-220312.tar.gz](https://github.com/KiwiHC16/Abeille/files/8237429/AbeilleLogs-220312.tar.gz)
![Capture](https://user-images.githubusercontent.com/99336018/158014047-8bd176ed-785a-4e9a-9c1c-3fea4bea23be.JPG)

**Comment by tcharp38** [comment]
[3450-Geu_CentraLite.zip](https://github.com/KiwiHC16/Abeille/files/8237479/3450-Geu_CentraLite.zip)
Refaire inclusion avec ca.

Pour mémoire:
- bouton 1 => EP3
- bouton 2 => EP4
- bouton 3 => EP2
- bouton 4 => EP1

**Comment by burzy76** [comment]
j'ai mis le fichier et refait une inclusion mais pour re-init la télécommande il faut mettre la pile et appuyer sur un bouton donc au début il a du prendre un bouton mais lequel ? j'ai le statuts 2 qui s'est allumée et donc inclusion a 
12h08 statuts 2 allumée
12h09 statuts 4 allumée avec bouton "rond" 
12h10 statuts 3 allumée avec bouton "losange"
12h11 statuts 2 allumée avec bouton "carrée" 
12h12 statuts 1 allumée avec bouton "hexagonale" 
et voici le fichier 
[AbeilleLogs-220312 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8237504/AbeilleLogs-220312.1.tar.gz)

**Comment by tcharp38** [comment]
Sans regarder les logs, ca semble fonctionner comme il faut d'apres ton rapport.

Du coup pour toi tout est bon ou il reste qqch à fixer ?
La remontée de batterie est bien faite ?

**Comment by burzy76** [comment]
oui j'ai bien la remontée de la batterie , j'ai acheter cette télécommande pour activer / de-activer une alarme et pour ouvrir / fermer un portail que me conseille tu pour bien paramétrer les actions car j'ai vu qu'il y avait le statuts que des qu'on appuie il réagie  mais aussi le on1 et off 1 c'est quoi les actions sur les boutons pour activer ceci un appuie active le on1 et si on réappuie c'est off 1 c'est sa  
sinon je ferais des essaies des lundi car la je pars pour deux de travail 
merci pour tout

**Comment by tcharp38** [comment]
Je te suggere d'utiliser uniquement 'Status X' qui passe à 1 ou 0 pour activer/desactiver ton alarme.

Mais en fait, via un scenario tu pourrais aussi utiliser 'On X' & 'Off X' mais ca semble plus compliqué.

Je clos le sujet.
A reouvrir si soucis specifiques Abeille.

**Comment by burzy76** [comment]
ptit retour vite fait programmer lundi ap midi et essai ce mardi matin et impeccable fait le job comme il faut et oui je suis passée par un scenario en relation avec le pluing Alarme de jeedom et en mettant "on X " en condition et impeccable merci a toi ou ton équipe d'avoir pris le tps pour résoudre mon pb
