### ISSUE TITLE
Ajout support ADEO LDSENK09

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#2319]
Demande d'ajout d'équipement. En te remerciant

![image](https://user-images.githubusercontent.com/36518012/153288442-7053b119-9808-4980-a0f4-5fd43571f780.png)

Identifiant Zigbee (modelId, manufId)LDSENK09, ADEO

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8036183/discovery.zip)

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si qqn a besoin de ce support.
