### ISSUE TITLE
Erreur CRC

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2320]
Bonjour,
Je trouve ces messages respectivement dans les logs AbeilleParser.log et AbeilleSerialRead.log 
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8038887/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8038889/AbeilleSerialRead1.log)
Peux-tu, stp, m'indiquer d'où cela proviens et si je peux le corriger ? Merci

**Comment by tcharp38** [comment]
Salut @Kenderv 

Les erreurs CRC apparaissent dans 2 cas
- au demarrage le temps de se synchroniser avec la zigate
- si zigate wifi et perturbation de communication

La tu n'as qu'une erreur donc pas de soucis.
Ce genre d erreur doit etre masqué pour les prochaines releases.

Peux tu basculer sur la 220206-BETA-1 et voir si tu as toujours ca ?

**Comment by tcharp38** [comment]
Je clos car pas vraiment de pb au bout du compte.
A reouvrir si besoin
