### ISSUE TITLE
Menu [Migration d'equipement] => Message Forbidden 

### ISSUE THREAD

**Issue by csercl** [KiwiHC16/Abeille#2322]
Hello
Je suis en Core 4.2.9
et Abeille Beta 2022-02-07 01:00:12

J'avais précédemment utilisé le Pavé Migration d'équipement" pour transférer des équipements d'une ZIgate ver une autre (je n'avais totalement confiance dans le remplacement global de Zigate)
Au final tout avait bien fonctionné à l'époque.
 
Je viens de recevoir une troisième Zigate 
Elle fonctionne correctement et j'ai pu y associer de nouveaux équipements.

J'ai voulu transférer sur cette zigate3 mes équipement actuels mais j'ai le message d'erreur suivant lorsque je clique sur Rehome

<img width="252" alt="Sans titre" src="https://user-images.githubusercontent.com/98477830/153514125-aacac286-da7d-445a-a195-6cf253600864.png">

j'ai les logs en debug mais je ne sais pas ou regarder. Dans le log 'Abeille' je n'ai pas l'impression qu'il y a des info la dessus

J'hésite a utiliser le Remplacement de ZIgate, je voudrais faire un transfert progressif

+
csercl

**Comment by tcharp38** [comment]
Salut @csercl 
Pb connu mais pas eu le temps de m'y coller. C 'est lié au passage en Jeedom 4.2.x.
Je reviens vers toi.

**Comment by tcharp38** [comment]
D'ailleurs tu as trouvé une doc sur cette partie "migration" ?

220211-BETA-1 a tester (dispo le 12/2)

**Comment by csercl** [comment]
Non pas de doc, 
J'avais a l'époque essayé avec 1 equipement.
ca me paraissait logique : choix de l'équipement et de la zigate de destination + 1 bouton avec un nom explicite.. 
j'ai essayé et ca a fait ce à quoi je l'attendais :)

**Comment by tcharp38** [comment]
J ai ajouté des commentaires et revu qq trucs en fonction de ma comprehension.
Tu me dira.

**Comment by csercl** [comment]
Beta installé.
la migration d'équipement à l'air de fonctionner 👍 
essai fait avec un prise ikea controloutlet 
l'équipement est bien transféré vers la zigate destination.

Sur la zigate origine il reste une 'trace' de l'équipement avec un nom auto du genre Abeille2-nnn. 
Cet équipement est désactivé. Je l'ai purement et simplement supprimé.

Sur la zigate destination en revanche l'équipement est présent pour Jeedom mais ne semble pas fonctionnel. il faut réinclure manuellement l'équipement sur cette zigate destination. (je ne me souvenais pas avoir eu a faire ça la fois précédent mais ma mémoire me fait défaut).
Après inclusion, tout va bien.

J'ai 38 équipement a migrer donc ca va être un peu long puisqu'il faut tout réinclure mais c'est déjà super bien que ca soit fait automatiquement coté config jeedom 👍 

Demain vais je tester avec d'autre équipements.

les commentaire et le pavé 'disclaimer' sont bien. 
Il faut peut-être dans le texte prévenir l'utilisateur qu'il doit réinclure l'équipement sur la nouvelle zigate.

J'ai fait un export au cas ou cela vous serve.
[AbeilleLogs-220212.tar.gz](https://github.com/KiwiHC16/Abeille/files/8054440/AbeilleLogs-220212.tar.gz)

**Comment by tcharp38** [comment]
Salut @csercl 
La procedure est la suivante:
- mode inclusion pour la zigate de destination
- demande de quitter le reseau à l equipement et d'en rejoindre un

Donc il doit quitter et se reannoncer mais comme la zigate destination est en inclusion, c'est elle qui doit le recevoir.
Du coup il ne devrait pas etre necessaire de refaire une inclusion apres ca.

Je ne comprends pas ce point "Sur la zigate origine il reste une 'trace' de l'équipement avec un nom auto du genre Abeille2-nnn." Donc j'ai du oublier qqch.

Dans ces logs, tu migrais quoi vers ou ?
Je ne comprends pas le premier "leave". On dirait que tu l'avais déja detruit de Jeedom

[2022-02-12 20:46:19][DEBUG] : msgFromParser(): Leave indication for IEEE 680AE2FFFE82B9BF, rejoin=01
[2022-02-12 20:46:19][DEBUG] : msgFromParser(): WARNING: Device with IEEE 680AE2FFFE82B9BF NOT found in Jeedom

Bref, si tu veux bien, 1 seul à la fois, en notant l'heure et source/dest. Comme ca on peut corriger au fur et à mesure.

**Comment by csercl** [comment]
Pour faire un process propre je suis parti d'un capteur de porte xiaomi NEUF juste déballé qui marche d'habitude nickel avec zigate/abeille.

10:52
- inclusion zigate 2
- création OK Abeille2-580
- adresse courte E938

10:55 essai du capteur => capteur opérationnel


**Bascule Z2 vers Z3**
10:59 : mise en mode inclusion de la zigate 3 (LED clignote)
10:59 :
- demande de migration Abeille2-580  vers zigate 3
- pas trace 'trace' sur la Z2
- dans la liste l'équipement est bien passé sur la Z3

[Edit : si on check le AbeilleParser.log a 11:01-11:02 on voit qu'abeille2 a encore des échanges avec E938]

11:02 essai du capteur : NOK 
11:04 mise en inclusion Z3 + inclusion du capteur 
11:04 Message Abeille	'[Informations][Abeille2-580]' s'est réannoncé. Mise-à-jour en cours.
11:07 essai du capteur : OK


**Bascule Z3 vers Z2**
11:08 mise zigate 2 en inclusion (LED clignote)
11:09 je m'y suis prs trop tot, Message d'Abeille,  j'ai 2 zigate en inclusion.. je force l'arret du mode inclusion sur les 2 Zigate

11:12 mise zigate 2 en inclusion
11:13 
- Demande de migration Abeille2-580 vers Zigate 2
- pas trace 'trace' sur la Z3
- dans la liste l'équipement est bien passé sur la Z2

11:14 
- j'appui un coup bref sur le bp d'inclusion 
- pas de comm avec abeille dans la page santé
- le capteur répond pa un flash unique sur la led donc il pense ne pas être connecté

11:15 je test le capteur avec son aimant = NOK
11:22 toujours rien, je rmet la Z2 en inclusion
11:23 inclusion du capteur OK sur les Leds , MAIS aucun message d'Abeille
[Edit :  dans le log parser on a  "EQ already known: Addr updated from E938 to 6444". il se souvient du E938 qui a pourtant changé lors du passage sur la Z3]

11:24 essai capteur => OK
11:24 extraction du log


[AbeilleLogs-220215.tar.gz](https://github.com/KiwiHC16/Abeille/files/8068224/AbeilleLogs-220215.tar.gz)


**Conclusion/remarques**

1. le transfert coté Jeedom est parfait
2. Il ne reste effectivement aucune trace sur la Zigate source
3. le capteur ne semble pas vraiment inclus dans le réseau de destination et pou rle moment il faut 'finir' en lui dmeandant une inclusion manuelle
4. peut-être adapter le texte du dsclaimer pour demander de mettre la zigate destination en inclusion **à la main** car à la lecture du texte on comprend que cela va se faire tout seul.

**Comment by tcharp38** [comment]
Salut.
Je peux enfin faire ce genre d'essais et ma conclusion est que ca n'est pas aussi simple que je l'esperais.

La raison principale est que mes capteurs Xiaomi ne tentent pas de rejoindre le reseau apres le "leave" malgre la requete.
Je me demande si ca n'est pas encore un truc mal foutu de chez eux.

En testant avec un Osram switch mini je vois qu'il revient sur le meme reseau alors qu'il n'est pas en inclusion.
Bref, la procedure n'est pas bonne.

Par contre la zigate destination se met bien en inclusion toute seule de mon côté.

**Comment by csercl** [comment]
Suite a ton message j'ai refait l'essai avec 2 adaptations dans la procédure :
1) je ne demande pas le mode inclusion sur la zigate destination, je laisse faire abeille
2) **juste après**  le clic sur OK de la migration, au lieu d'attendre, je réveille le capteur plusieurs fois par son bouton .

**Cela a fonctionné** sur le capteur d'ouverture Xiaomi. 
Il est opérationnel sur la zigate destination sans avoir besoin d'inclure.

Le timing semble serré mais jouable. 
Il faut juste être à coté chaque équipement exactement au moment ou tu fait la demande de migration. 
.. et si cela ne fonctionne pas, ce n'est pas grave, il suffit de lancer l'inclusion en manuel.

Au cas ou, j'ai refais un log
a 13:50 on voit le leave suivi du create.

[AbeilleLogs-220215 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8069267/AbeilleLogs-220215.1.tar.gz)

Dans l'aprèm je refais la manip avec un control outlet Ikea pour vois si le comportement est répétitif.

**Comment by tcharp38** [comment]
Etrange. C'est avec celui la que j'ai fait le premier essai et sans succes.

**Comment by csercl** [comment]
Xiaomi = prise de tête :)

**Comment by tcharp38** [comment]
Oui ca c'est sur, mais meme si j'exclus Xiaomi, je ne comprends pas si il y a une solution pour demander à un equipement de quitter le reseau courant et rejoindre celui qui est ouvert (en inclusion).

**Comment by csercl** [comment]
J'ai donc fait plusieurs aller/retour entre zigate 2 et 3 de mon capteur.
le comportement est peu répétitif avec des variations

1. - pas d'inclusion dans le réseau destination comme tu l'avais noté, même en réveillant le capteur
2. - inclusion automatique en 'réveillant' le capteur.. j'ai eu ce cas plusieurs fois
3. - inclusion automatique dans le réseau destination SANS avoir touché le capteur.. c'est le graal mais je ne l'ai eu qu'une seule fois
4. - et, cherry on ze cake, création d'un nouvel équipement dans le réseau destination avec un fantôme de l'équipement sur le réseau source. et cela sans même avoir mis le capteur en inclusion par son bouton

c'est une variante de ce cas 4 que j'ai eu hier ou on se retrouve avec 2 équipements à la fin
 image ci-dessous avec Abeille-580 sur la zigate 2 et abeille-581 sur la zigate 3
evidement 580 est inerte et 581, le nouveau fonctionne

![image](https://user-images.githubusercontent.com/98477830/154071945-36a885be-1fe0-4441-b9b9-3ece70a685fd.png)


petit log 
[AbeilleLogs-220215 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8069500/AbeilleLogs-220215.1.tar.gz)

Courage ! ;)

De mon coté je pense que c'est utilisable tel quel si le cas 4 n'arrive pas trop souvent.
il faut juste que l'utilisateur soit averti

**Comment by tcharp38** [comment]
Autres modifs dans la 220215-BETA-1.
Maintenant tout equipement deja connu de Jeedom peut changer de reseau suite à reinclusion et il ne doit plus y avoir de doublon.

Forcer un equipement à quitter le reseau pour en rejoindre un autre reste un point ouvert.

**Comment by csercl** [comment]
Beta installée

j'ai continué avec le capteur xiaomi pour pouvoir comparer avec les essais passés. 
Le comportement est répétitif

1) je prend la précaution de mettre les 2 zigate HORS inclusion.
2) commande de migration Z2->Z3 ou bien Z3->Z2 + [OK]
3) nota : à ce stade si je ne réveille pas le capteur pas son bouton, il reste fonctionnel sur la Zigate source (détéction de porte ok)
4) **1er appui** su le bp du capteur : il quitte le réseau, désactivé par abeille, disparait du dash
5) nota : là, on peu attendre il ne se passe rien le capteur est out
6) **2eme appui** sur le bp du capteur : il rejoins le réseau destination, visible au Dash et 
7) ca marche !!

C'est cool 👍 
ca marche bien et c'est du systématique (tenté 5-6 fois)
plus jamais eu de création en doublon


Un log entre le début et la fin de manip :

**arret manuel d'inclusion sur les Zigate**
0187|[2022-02-16 10:07:33]DEBUG : msgFromParser(): Abeille2, permit join, status=00
0188|[2022-02-16 10:07:35]DEBUG : msgFromParser(): Abeille3, permit join, status=00

**Début de migration** 
0189|[2022-02-16 10:07:56]DEBUG : msgFromParser(): Abeille3, permit join, status=01
0190|[2022-02-16 10:08:02]DEBUG : checkAllDaemons() => ok
0191|[2022-02-16 10:08:02]DEBUG : cron(): Daemons: 1446/Socat1, 1454/SerialRead1, 1459/SerialRead2, 1467/SerialRead3, 1469/Parser, 1472/Cmd
0192|[2022-02-16 10:08:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/0000\/getZgVersion&time=1645002502","payload":""}' vers queue 1212
0193|[2022-02-16 10:08:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille2\/0000\/getZgVersion&time=1645002502","payload":""}' vers queue 1212
0194|[2022-02-16 10:08:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille3\/0000\/getZgVersion&time=1645002502","payload":""}' vers queue 1212
0195|[2022-02-16 10:08:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"CmdAbeille3\/0000\/permitJoin","payload":"Status"}' vers queue 1212
0196|[2022-02-16 10:08:02]DEBUG : msgFromParser(): Abeille3, permit join, status=01


**1er appui sur BP du capteur**
0197|[2022-02-16 10:08:07]DEBUG : msgFromParser(): Leave indication for Abeille2/00158D0007758A1E, rejoin=01
0198|[2022-02-16 10:08:07]DEBUG : postSave()
0199|[2022-02-16 10:08:23]DEBUG : msgFromParser(): Abeille1, Zigate version 0004-0321
0200|[2022-02-16 10:08:23]DEBUG : msgFromParser(): Abeille2, Zigate version 0004-0321
0201|[2022-02-16 10:08:23]DEBUG : msgFromParser(): Abeille3, Zigate version 0004-0321

**2eme appui sur BP du capteur**
0202|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Device migration from Abeille2/D15F to Abeille3/7DB7
0203|[2022-02-16 10:08:25]DEBUG : postSave()
0204|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Eq announce received for Abeille3/7DB7, jsonId='sensor_magnet.aq2', jsonLoc='Abeille'
0205|[2022-02-16 10:08:25]DEBUG : createDevice(create, dev={"net":"Abeille3","addr":"7DB7","ieee":"00158D0007758A1E","modelId":"sensor_magnet.aq2","manufId":"LUMI","jsonId":"sensor_magnet.aq2","jsonLocation":"Abeille"}
0206|[2022-02-16 10:08:25]DEBUG :   Already existing device Abeille3/7DB7 => [Informations][Abeille3-581]
0207|[2022-02-16 10:08:25]DEBUG :   Device is already enabled. Doing nothing.
0208|[2022-02-16 10:08:25]DEBUG : postSave()
0209|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Eq announce received for Abeille3/7DB7, jsonId='sensor_magnet.aq2', jsonLoc='Abeille'
0210|[2022-02-16 10:08:25]DEBUG : createDevice(create, dev={"net":"Abeille3","addr":"7DB7","ieee":"00158D0007758A1E","modelId":"sensor_magnet.aq2","manufId":"LUMI","jsonId":"sensor_magnet.aq2","jsonLocation":"Abeille"}
0211|[2022-02-16 10:08:25]DEBUG :   Already existing device Abeille3/7DB7 => [Informations][Abeille3-581]
0212|[2022-02-16 10:08:25]DEBUG :   Device is already enabled. Doing nothing.
0213|[2022-02-16 10:08:25]DEBUG : postSave()
0214|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Attribute report from 'Abeille3/7DB7/01': Attr='0000-01-0005', Val='sensor_magnet.aq2'
0215|[2022-02-16 10:08:25]DEBUG :   Unknown Jeedom command '0000-01-0005'
0216|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Attribute report from 'Abeille3/7DB7/01': Attr='0000-01-0001', Val='3'
0217|[2022-02-16 10:08:25]DEBUG :   Unknown Jeedom command '0000-01-0001'
0218|[2022-02-16 10:08:25]DEBUG : msgFromParser(): Attributes report by name from 'Abeille3/7DB7/01
0219|[2022-02-16 10:08:25]DEBUG :   Batterie-Volt => 3005
0220|[2022-02-16 10:08:25]DEBUG :   Batterie-Pourcent => 61
0221|[2022-02-16 10:08:25]DEBUG :   0006-01-0000 => 01

**Essai => il est opérationnel**
0222|[2022-02-16 10:08:43]DEBUG : msgFromParser(): Attribute report from 'Abeille3/7DB7/01': Attr='0006-01-0000', **Val='0'**
0223|[2022-02-16 10:08:43]DEBUG : msgFromParser(): Attribute report from 'Abeille3/7DB7/01': Attr='0000-01-FF01', Val='?'
0224|[2022-02-16 10:08:43]DEBUG :   Unknown Jeedom command '0000-01-FF01'
0225|[2022-02-16 10:08:44]DEBUG : msgFromParser(): Attribute report from 'Abeille3/7DB7/01': Attr='0006-01-0000', **Val='1'**

**Comment by tcharp38** [comment]
Bon d'apres tes retours ca semble un peu mieux.
Du coup que manque t'il pour que ca soit propre et clair pour tout utilisateur ?

**Comment by tcharp38** [comment]
Nouvelle update+ doc dans 220218-BETA-1

**Comment by csercl** [comment]
NIckel 👍 
la doc et bien. beta installée, 
Je continue doucement les transfert avec quelques réinclusions qui restent nécessaire.

merci et bravo pour le job !
Issue a clore il me semble ;)

**Comment by tcharp38** [comment]
Parfait.
Je considere que c'est ok mais a réouvrir si soucis.
