### ISSUE TITLE
Multi-zigates: Abeille sans réaction si une zigate en erreur

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2323]
J'ouvre ce sujet pour indiquer d'apres les observations  qu'Abeille peut etre HS dans le cas suivant
- plusieurs zigates actives
- et l'une d'elles est en erreur (CRC)

**Comment by Jake309** [comment]
Re, oui, en voulant retester la zigatev1, j'ai créé de nouveau problème bien plus impactant ^^
Je t'avouerai qu'après cet épisode, je vais plus tenter d'essayer la zigatev1. 

Je solutione ce pb abeille sur le serveur, et je me dégoterai un autre pc pour faire des test

**Comment by tcharp38** [comment]
Moi je fais des essais sur des OrangePi zero à 10e. J'en ai du coup 4 ou 5 :)

Pour info, la 220211-BETA-1 doit se comporter differement.
Toute erreur CRC n'est plus transmise au parser. Donc seul le chemin SerialRead gere les erreurs (avec Socat si wifi).

A tester

**Comment by Jake309** [comment]
La seule solution que j'ai trouvé dans l'immédiat, c'est de tout réintégrer.
Impossible de faire autrement pour récupérer mes équipements. Même restaurer des sauvegarde ca ne change rien.
cf : #2247

**Comment by tcharp38** [comment]
Tu parles de ton pb USB v1 apres mise à jour n est ce pas ? Rien à voir avec "multi zigate" ou je me trompe ?

**Comment by Jake309** [comment]
J'ai tout mes équipements sur la zigate V2 usb. Ce matin, en branchant ma V1 sur mon jeedom et en l'ajoutant à abeille, j'ai eu tout les message d'erreur que tu as vue tout a l'heure et plus aucun équipement ne fonctionnait.
J'ai retiré la V1 de jeedom, redemarré le serveur, toujours rien n'allait.
J'ai restauré une sauvegarde, toujours aucun équipement présent dans abeille ne fonctionnaient.
La seule solution que j'ai trouvé et que je viens de terminer (2h) c'est de réinclure tout mes équipements zigbee.

Pour ca que je disais être bien blasé et ne plus vouloir tester la V1 sur mon jeedom de la maison ^^

**Comment by tcharp38** [comment]
ok pigé mais du coup pas normal.
Car les equipements sur le reseau v2 restent sur le v2 sauf si entre temps tu as tenté de les inclure dans la v1.

Mais je te comprends. On doit pouvoir se servir de tout ca et pas seulement ne faire que des essais et reappairer. Sinon ca n'est pas serieux.

**Comment by Jake309** [comment]
Non, j'ai rien migré, surtout pas malheureux xD
Ya juste eu un truc bizarre qui pourrais t'intéresser, c'est que 2 prises en attente qui étaient dans ruche (le groupe ou se trouve les zigate) ont était dupliqué sur la zigateV1, donc quand j'allais dans santé, le meme équipement avec la meme adresse apparaissait sur les 2 zigate. Et en bas du tableau, j'avais un message pour me dire que les 2 équiepements avec les mémé adresse étaient sur les 2 zigate et que c'était pas normale.
Mais ca ne me la pas fait avec mon module RGB tuya. encore plus étrange.
J'espère que ca va pas trop te titiller, parce que je vais pas remettre ma zigatev1 ^^

**Comment by Jake309** [comment]
d'ailleurs, si elle t'intéresse pour tester ce bug de mise a jour qui gène plusieurs utilisateur, je peux te l'envoyer ;) 
J'ai regardé, de souvenir j'avais un usb ttl qui devait trainé, mais pas trouvé. 
Tout disparait depuis le déménagement :/

**Comment by tcharp38** [comment]
Ma premiere Zigate est aussi une v1 USB. Toujours pas mise à jour. Faut que je m'y colle mais manque de pot c'est celle que "j 'utilise pour de vrai :)". Elle gere les volets, le chauffage et plein d autres trucs.

Apres si tu es sur de ne plus jamais t en servir, je peux essayer de trouver du temps et la tester au cas ou j'en tire des infos utiles.

**Comment by Jake309** [comment]
Oula ! attention, tu es prévenu malheureux, ca risque de planter ^^

Moi ca m'est égale, c'est pour toi. je pense avoir faire tout ce que je savais faire, misa a jour, testgui, test sur abeille.
Jamais testé de faire une maj avec abeille, je sais pas si on peut le faire en direct ?

C'est toi qui vois :)

**Comment by tcharp38** [comment]
Pas le choix il faudra que je fasse une mise à jour. FW trop vieux.
J'espere trouver du temps pour ca dans la semaine.

Mais revenons en sur le sujet "multi zigates"... qui avait ou a encore des soucis de plantage si une zigate est en erreur ?

**Comment by Jake309** [comment]
j'avais, j'ai tout purgé, maintenant, j'ai qu'une zigate et plus de problème ^^
J'attends d'avoir un pc utilisable pour monter des serveur et faire des tests pour brancher la vieille zigate dessus

**Comment by Jake309** [comment]
On peut clore en attendant, je ne sais pas quand j'aurai un pc, et encore moins quand j'aurai le temps (arrivée imminente à la maison =) )

**Comment by tcharp38** [comment]
@Jake309 
Arrivée d'un(e) ptit nouveau ?! Je comprends bien ? Si oui félicitations. Mais t inquiete les pbs domotiques perdurent alors ils t attendront surement.

**Comment by tcharp38** [comment]
Je clos ce sujet.
A reouvrir si pb multi zigate alors qu'une d'elles est HS
