### ISSUE TITLE
Souci inclusion interrupteur sans fil xiaomi aqara D1 : WXKG03LM

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2325]
J'ai resorti un interrupteur que je n'arrive pas a intégrer depuis un moment.
J'ai réussi qu'une fois, quand je l'ai reçu, depuis sur mon ancienne zigatev1 et la sur la V2, impossible de l'inclure.
C'est un grand aqara carré. simple.
Je l'ai supprimé de jeedom ca na rien changé (j'ai déjà réussi a solutionné ce genre de pb avec d'autre équipement en faisant ca).
Je sèche, et je l'aime bien celui la contrairement au petit ^^
Voici les log en mode débug
[AbeilleLogs-220211.tar.gz](https://github.com/KiwiHC16/Abeille/files/8049557/AbeilleLogs-220211.tar.gz)
.

**Comment by tcharp38** [comment]
FW version Appli=0005, SDK=0321

J'observe une annonce, Abeille demande la liste des EP... et rien. Meme pas d'acquittement du device.

> [2022-02-11 15:57:20] Abeille1, Type=004d/Device announce, Addr=2166, ExtAddr=0400536D04015D6B, MACCapa=B4
> [2022-02-11 15:57:20]   eq={"ieee":"0400536D04015D6B","capa":"","rejoin":"","status":"idle","time":1644591440,"endPoints":null,"mainEp":"","manufId":null,"modelId":null,"location":null,"jsonId":"","jsonLocation":""}
> [2022-02-11 15:57:20]   Requesting active end points list
> [2022-02-11 15:57:20] Abeille1, Type=8000/Status, Status=00/Success, SQN=0C, PacketType=0045, Sent=02, SQNAPS=60, NPDU=02, APDU=01
> [2022-02-11 15:57:20] Abeille1, Type=8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=00, DstEP=00, AddrMode=02, Addr=2166, SQNAPS=60, NPDU=02, APDU=00
> [2022-02-11 15:57:27] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=2166, EP=00, ClustId=0005, SQNAPS=60

Etrange.
Question bete... facile de refaire un essai avec une pile neuve ?
Et tu me redonnes les logs STP

**Comment by Jake309** [comment]
Yes, j'avais déjà testé, j'ai eu le souci avec mes capteur de présence infrarouge ;)
J'ai refais comme ca tu as un point de comparaison. j'ai intégré des sonde de température avant de refaire le test.
Voila les log, 2 ou 3 tentatives
[AbeilleLogs-220211 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8049908/AbeilleLogs-220211.1.tar.gz)
.

**Comment by Jake309** [comment]
S'il répond pas, c'est qu'il est hs je pense. sinon il n'y a pas de raison.
Si abeille attend une info mais n'en a pas. c'est tout vue.

**Comment by tcharp38** [comment]
J'aimerais bien etre aussi sur que toi. J'ai deja vu des trucs bizarres avec les devices mal foutus, comme Xiaomi.
Il se peut qu'il se comporte pas bien vis à vis du standard.

Je peux te faire faire un essai de reinclusion avec un code particulier ?

**Comment by Jake309** [comment]
Oui oui, sans souci ;)

**Comment by tcharp38** [comment]
Le jour ou tu as du temps tu me dira sur quelle version tu es et je ferai une bidouille alignée juste pour ton cas.
A+

**Comment by Jake309** [comment]
Salut :) 
Des que ma nouvelle install fonctionne, on pourra regarder si tu veux .
Merci
a+
