### ISSUE TITLE
Perte de communication de l'ensemble des équipements - ( Type=9999/Extended error, ExtStatus=80)

### ISSUE THREAD

**Issue by Bob2969** [KiwiHC16/Abeille#2327]
Bonjour,

je rencontre un problème depuis plus d'une semaine sur mon réseau. 
Je perds régulièrement l'ensemble de mes équipements.

Mon réseau est constitué de:
- une PiGate en v3-031E
- capteurs Aqara 
- capteurs Sonoff 
- Interrupteur Legrand
- Contacteur Legrand
- 2 Ampoules HUE LW017 (récemment ajoutés avec JSON personalisé)
- 1 Détecteur HUE SML04 (récemment ajoutés avec JSON personalisé)

En mode débug, je finis par avoir cette ligne qui se répète:
_Abeille1, Type=9999/Extended error, ExtStatus=80_
Bizarrement à chaque fois que ça se reproduit le dernier objet à communiquer est 1 des 3 équipements HUE...

Seul un restart du Demon permet de récupérer les communications.
Quel est ce type de message (9999)? 
Voyez-vous d'où ça pourrait venir?

[AbeilleParser-prev.log](https://github.com/KiwiHC16/Abeille/files/8074489/AbeilleParser-prev.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/8074532/Abeille.log)

Merci

**Comment by tcharp38** [comment]
Salut @Bob2969 
Le message 9999 est un message permettant de remonter un code d'erreur precis.
Regarde la si tu veux: https://zigate.fr/documentation/commandes-zigate/
Pour le peu que j'en vois je soupconne un trop grand nombre de requetes en meme temps.
C'est encore un point faible d'Abeille sur lequel nous travaillons.

Tes logs sont incomplets. A l'avenir pense à mettre le package que tu peux avoir via la page support puis "telecharger tout". On pourra voir via AbeilleCmd.log en particulier quels sont les equipements concernés et pourquoi.

**Comment by Bob2969** [comment]
Merci @tcharp38 pour ta réponse.

Je comprends avec la doc que c'est du à un manque de PDU. A priori on peut modifier la limite "_The number of NPDUs is set in the “Number of NPDUs” property of the “PDU Manager” section of the config editor"_
Tu sais comment accéder au Config Editor?

Je joins de nouveaux logs (complet cette fois) je viens d'avoir un plantage à 22h13. Un reset SW permet de relancer les communications. Je vais mettre en place un reset régulièrement pour éviter le crash complet pendant des heures.
[AbeilleLogs-220216.tar.gz](https://github.com/KiwiHC16/Abeille/files/8083780/AbeilleLogs-220216.tar.gz)

**Comment by tcharp38** [comment]
Manque de pot ce PDU n'est pas modifiable. Il est fixé à la création du firmware qui lui meme est limité par la taille de memoire dispo en interne. La v1 a plus de limites que la v2.

Es tu partant pour migrer sur la beta ? C'est celle qui va donner la prochaine stable et il y a un certain nombre de changements dans ce sens.

**Comment by Bob2969** [comment]
Ah oui je veux bien tester la bêta si ça améliore ce côté là. Comment je peux la récupérer ? 
Sinon le reset régulier à l'air d'assurer le service mais ce n'est pas très propre.

**Comment by tcharp38** [comment]
Regarde la pour la beta: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

Le reset regulier nettoie tous les messages en attente donc je comprends que le symptome disparaisse.

**Comment by tcharp38** [comment]
En creusant un peu + tes derniers logs je vois l'origine du pb.

- 22h13: un device s'annonce (manuf='SignifyNetherlandsB.V.', model='SML004')
- la config suit puis plantage complet de la zigate
- il y a aussi des erreurs de reception à ce meme moment
- quand le log se termine la zigate est toujours dans un etat foireux et n'a pas libéré ses ressources internes

Peux tu exclure cet equipement pour confirmer qu'il en est bien la cause ?
A premiere vue, ca n'est pas la piste que j'avais en tete, en tout cas pas completement. Du coup j'ai bien peur que le meilleur remede sera de repartir d'un reseau vierge avec FW 3.21-OPDM => reappairage complet.

Mais bascule deja sur la beta et tiens moi au jus.

**Comment by Bob2969** [comment]
J'avais bien des doutes sur cet équipement (Détecteur de Mvt HUE). 
Pour l'exclusion, comme il est sur pile, y a t'il un moyen direct pour l'exclure autre que par le bouton "Exclure"?

J'ai une Zigate USB V2 qui arrive demain, je vais essayer d'isoler cet équipement dessus voir ce que ça donne.
Avant ça je teste la Bêta et je te tiens au courant.

Merci pour l'aide

**Comment by tcharp38** [comment]
Pour l'exclure proprement, pas le choix => bouton exclure et reveil en meme temps.
Sinon tu pourrais au moins l 'eteindre le temps des essais pour confirmer que tu n'as plus de soucis sans.

**Comment by tcharp38** [comment]
@Bob2969 
Pour ton pb, je me demande si tu ne devrais pas mettre à jour ton FW zigate. 3.1e => 3.21-legacy
Pas de réappairage requis si tu restes en 'legacy'.
Mais les erreurs observées peuvent etre fixées dans le dernier FW.

**Comment by tcharp38** [comment]
Salut @Bob2969 
Des news ?

**Comment by Bob2969** [comment]
Hello @tcharp38,
alors j'ai pris le temps de faire plusieurs tests depuis mon dernier message. 
Après le reset SW et passage en Beta du plugin et les équipements HUE exclue du réseau. Je n'ai eu aucun soucis pendant 3 jours. Ensuite:
- ajout du détecteur de Mvt SML004 ==> aucun soucis pendant 2 jours
- ajout des 2 ampoules LW017 ==> crash du réseau 1 jour après.

Je suis donc quasiment sûr que ce sont ces équipements qui font saturer la PDU. Sais-tu comment est incrémenté ce NPDU? Est-ce qu'un équipement un peu trop bavard sur le réseau peut amener la saturation?

Un reset SW permet toujours de retrouver de la stabilité sur quelques jours. J'ai de nouveau exclu les équipements HUE et pour l'instant aucun soucis depuis 1 semaine.
J'ai depuis reçu une Zigate USB v2 et je vais porter les équipements suspects sur celle-ci d'ici ce weekend.

Je te tiendrais au courant.

**Comment by tcharp38** [comment]
Le 'NPDU' n'est pas configurable. C'est lié à la stack de la zigate. Donc tu aura + de marge avec une v2.

Néanmoins je suis preneur de logs autour du moment ou ca part en live si tu as.

**Comment by tcharp38** [comment]
Salut @Bob2969 
Que fait on avec ce sujet ?
Tu en es ou ?

**Comment by Bob2969** [comment]
> Salut @Bob2969 Que fait on avec ce sujet ? Tu en es ou ?

Hello, aucun crash depuis le passage des équipements suspects sur la v2.
Je n'ai pas trop cherché à faire de test supplémentaire, la stabilité du moment me va bien 😅
Je verrais le comportement en chargeant au fur et à mesure la v2.

**Comment by tcharp38** [comment]
Ok. Je clos le sujet alors mais à réouvrir si ca fait du sens.
