### ISSUE TITLE
Support Ikea TRADFRI LED 806 lm E27 (TRADFRIbulbE27CWS806lm, modele LED1924G9)

### ISSUE THREAD

**Issue by zabouille** [KiwiHC16/Abeille#2328]
Bonjour.
J'ai acheté une ampoule Ikea TRADFRI LED 806 lm E27. Lors de l'inclusion, l'objet se créé mais j'ai un message

2022-02-15 18:18:47 | Abeille | Nouvel équipement détecté mais non supporté. Création en cours avec la config par défaut (defaultUnknown). Rafraîchissez votre dashboard dans qq secondes.

Voici le log correspondant
[AbeilleLogs-220215.tar.gz](https://github.com/KiwiHC16/Abeille/files/8077117/AbeilleLogs-220215.tar.gz)

Est-ce un nouveau type d'ampoule?

Merci d'avance de votre aide.

**Comment by tcharp38** [comment]
Salut @zabouille 
Donc ce modele n'est pas (encore) supporté par Abeille.
Merci de generer un discovery avec l'assistant: voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

**Comment by zabouille** [comment]
Bonjour

Lorsque j'utilise l'assistant sur l'objet, j'ai un message:

http://192.168.1.58/index.php?v=d&m=Abeille&p=AbeilleEqAssist&id=72 | 1634 | Uncaught TypeError: Cannot read properties of undefined (reading '01')

et le rafraichissement sur le End point 01 ne donne rien (j'ai bien veillé à allumer la lampe).

![Ampoule TRADFRI](https://user-images.githubusercontent.com/59845540/154413511-2fc53e37-305f-4040-9a2b-837490fd8a7b.jpg)

Est-ce que j'ai loupé quelque chose à faire :(?

Merci

**Comment by tcharp38** [comment]
T'es tombé sur un bug de l'assistant.

Essaie de voir sur la page equipement/avancé, si il y a  un "discovery local" (auto decouverte), fais telecharger et mets le la.

**Comment by zabouille** [comment]
Bonsoir
Voici ce que j'ai sur la page Avancé
![TRADFRI Avancé](https://user-images.githubusercontent.com/59845540/154536538-15a94a83-b63c-4d96-a42c-1d8da1830028.jpg)

Hier j'ai fait l'assistant de découverte. Je ne vois rien d'autre.

**Comment by tcharp38** [comment]
Bon je ne comprends pas.

Peux tu basculer sur la beta, https://tcharp38.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta
t assurer d etre en mode debug
et refaire une inclusion ?

**Comment by zabouille** [comment]
Bonjour
J'ai installé la béta, et en mode debug réinclus l'objet.
Du coup l'assistant de découverte fonctionnait.
Voici les logs et le json généré par l'assistant et celui du discovery local (je ne savais pas si ça générait la même chose, donc j'ai mis les deux)

Merci

[AbeilleLogs-220218.tar.gz](https://github.com/KiwiHC16/Abeille/files/8094321/AbeilleLogs-220218.tar.gz)
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8094329/discovery.zip)
[discovery local.zip](https://github.com/KiwiHC16/Abeille/files/8094330/discovery.local.zip)

**Comment by tcharp38** [comment]
Ok on va pouvoir faire un modele.
Tu peux m'en dire + ?
- ref Ikea
- Couleur ? Blanc ? Forme d'ampoule
- et il me faut une image PNG sans fond pour mettre en icone si n'existe pas deja dans Abeille

**Comment by tcharp38** [comment]
[TRADFRIbulbE27CWS806lm.zip](https://github.com/KiwiHC16/Abeille/files/8096915/TRADFRIbulbE27CWS806lm.zip)

En attendant voila de quoi tester.
A decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion

**Comment by zabouille** [comment]
La référence Ikea est 704.391.58
Ampoule LED E27 806 lumen variateur d'intensité spectre couleur et blanc / globe opalin
![tradfri-ampoule-led-e27-806-lumen-sans-fil-a-variateur-dintensite-spectre-couleur-et-blanc-globe-opa](https://user-images.githubusercontent.com/59845540/154693883-14a6acc9-1ba8-4130-9874-6b0da1b3145c.png)

Je refais l'inclusion ce soir

**Comment by tcharp38** [comment]
220218-BETA-1

**Comment by zabouille** [comment]
Bonsoir
J'ai inséré le dossier , redémarré et relancé l'inclusion.
J'ai le même message d'erreur (mais le type de lampe est reconnu dans Identifiant Zigbee (modelId, manufId) (voir photo)
![Tradfri bis](https://user-images.githubusercontent.com/59845540/154744341-1855ad8f-24a9-4f72-9a55-af9a8dcff54e.jpg)

Voici les logs.
[AbeilleLogs-220218 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8099620/AbeilleLogs-220218.1.tar.gz)

**Comment by tcharp38** [comment]
Avec l'editeur de fichiers (Reglages>Systeme) verifie que tu as bien
TRADFRIbulbE27CWS806lm
dans core/config/devices
Tu devrais avoir un core/config/devices/TRADFRIbulbE27CWS806lm/TRADFRIbulbE27CWS806lm.json

Si c est le cas peut etre n'as tu pas redémarré Abeille avant reinclusion ?

**Comment by zabouille** [comment]
Oups, j'avais laissé un dossier intermédiaire, désolée.
Là c'est parfait, ça marche.
Merci beaucoup!!! :)

**Comment by tcharp38** [comment]
cool.
Je n'ai pas le temps d'entrer dans le detail, surtout à distance, alors a toi de t assurer que tout est bon et on peut clore ce sujet.

**Comment by zabouille** [comment]
Oui tout est bon :)
Encore merci!!!!
