### ISSUE TITLE
Support Smart Air Box tuya (TS0601, _TZE200_yvx5lh6k)

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2329]
Hello,

avant d'acheter ce détecteur, penses tu qu'il est (ou sera) compatible avec abeille:

https://fr.aliexpress.com/item/1005002650159305.html

Apparemment, il serait compatible avec le plugin zigbee (https://community.jeedom.com/t/demande-integration-smart-air-box-tuya/67907) mais j'aurais aimé qu'il soit compatible avec abeille ;)

**Comment by tcharp38** [comment]
Salut @Proft1972 
Si il l'est pour le plugin Zigbee ca doit etre jouable aussi pour Abeille.
Note qu'il est tout recent et qu'a priori les valeurs remontées (Voc, Co²) semblent "discutables".
Je vois aussi qu'a priori ca n'est que sur du cluster EF00 specifique.

Bref ca doit le faire.

**Comment by Proft1972** [comment]
Ok, je vais donc le commander et je compterai sur toi pour l'inclure dans abeille!

**Comment by Proft1972** [comment]
Bonjour @tcharp38 
J'a ibien recu le capteur smartair box
Voici le fichier Json: 


[discovery (5).zip](https://github.com/KiwiHC16/Abeille/files/8243372/discovery.5.zip)
et le png
![tuya smart](https://user-images.githubusercontent.com/93400394/158133724-0f516fdf-c59a-4409-acf5-83fffcfe1a9d.png)

**Comment by tcharp38** [comment]
Je regarde.
Est ce que c'est vendu sous la marque Tuya, modele RSH-AirBox01 ?
Si non, quelle marque et modele ?

**Comment by Proft1972** [comment]
Voici le lien ou je l'ai acheté:
https://fr.aliexpress.com/item/1005002650159305.html?gatewayAdapt=glo2fra&spm=a2g0o.order_list.0.0.21ef5e5bPaiwaJ

et les photos de la boite, c'est bien "smart air box tuya" mais je ne vois pas la ref :+1: 
![1647250733527](https://user-images.githubusercontent.com/93400394/158148231-43db341b-0e81-47db-82a4-1fbac65c2df3.jpg)
![1647250733532](https://user-images.githubusercontent.com/93400394/158148342-b38aa96e-6c14-4411-acf5-da6a0d111900.jpg)

**Comment by tcharp38** [comment]
Bon je suppose donc un produit generique "Tuya".
Quant au modele,.. je ne vois rien sur tes photos.
Je prends le "RSH-AirBox01" de ce site: https://zigbee.blakadder.com/Tuya_RSH-AirBox01.html

A tester avec ce JSON qui ne fait pas grand chose encore. J'aurai besoin des logs pour voir ce que le device envoie.
[TS0601__TZE200_yvx5lh6k.zip](https://github.com/KiwiHC16/Abeille/files/8243698/TS0601__TZE200_yvx5lh6k.zip)

Donc
- decompresser dans core/config/devices
- redemarrer Abeille
- refaire inclusion
- fournir un package de logs au bout de qq mins

Bien sur, je presuppose que tu es en mode debug, 5000 lignes min, et plutot sur la beta histoire  d etre au gout du jour.

**Comment by Proft1972** [comment]
voici le package de logs. J'ai bien la dernière beta, en mode debug et sur 5000 lignes
[AbeilleLogs-220314 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8243896/AbeilleLogs-220314.1.tar.gz)

**Comment by tcharp38** [comment]
:(

Logs vides. Tu n'es pas en mode debug.
A corriger, puis redemarrer Abeille.

**Comment by Proft1972** [comment]
C'est bizarre, le mode debug saute régulierement! là ca devrait etre bon:
[AbeilleLogs-220314 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8244282/AbeilleLogs-220314.2.tar.gz)

**Comment by tcharp38** [comment]
Oui j'ai noté ca chez certains utilisateurs. Si tu peux me dire suite à quoi il saute, j'aurai peut etre une piste.

Tes logs sont toujours vides :(
Il faut pour changer le mode, toujours sauvegarder puis redemarrer le demon.
Tant que ton log AbeilleParser est vide, inutile de renvoyer un package

**Comment by Proft1972** [comment]
[AbeilleLogs-220314 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/8245569/AbeilleLogs-220314.3.tar.gz)
cette fois ci , il y a qqch dans abeille parser, en revanche, je ne comprends pas pkoi il était vide la derniere fois....

Et peut etre pourras tu me dire pourquoi j'ai ce défaut: ERREUR: readAttribute(): Format attribut (508) incorrect => ignoré.
je l'ai plusieurs centaine de fois par jour!

**Comment by tcharp38** [comment]
Ok je note plusieurs remontées d'info EF00-02

> [2022-03-14 15:15:38] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=EF00, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=8F8C, DstAddrMode=02, DstAddr=0000
> [2022-03-14 15:15:38]   FCF=09/Cluster-specific/Serv->Cli, SQN=73, cmd=02/Unknown-EF00-02
> [2022-03-14 15:15:38]   Ignored cluster specific command EF00-02

Je dois creuser sur le net car c'est pas standard du tout.

Côté erreur "508", c'est vieux ca. Ca vient d'un bug d'une commande que j'ai corrigé depuis.
Si les commandes sont fixées depuis, la DB ne l'est pas. Voir https://github.com/KiwiHC16/Abeille/issues/2310#
Il faudrait que je prenne du temps pour ajouter un code de "correction au demarrage".
En attendant tu peux fixer toi meme le pb en rechargeant les modeles (page EQ/avancé) pour les equipements suivants
- id 426: "prise Lidl 1"
- id 427: "prise Lidl 2"

**Comment by Proft1972** [comment]
Je ne sais pas recharger un modele (j'ai cherché un peu ^partout mais surement pas au bon endroit!)

**Comment by tcharp38** [comment]
Pour le pb 508 je l'ai fixé pour la prochaine beta. Tu pourra alors confirmer que ca resoud le pb.

En attendant peux tu
- copier core/class/AbeilleParser.class.php en .orig ou autre pour en garder une copie
- ecraser avec ce nouveau code
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8246797/AbeilleParser.class.php.zip)
- redemarrer
- et me fournir le log parser qq mins apres

J'ai commencé d'ajouter un truc specific Tuya mais ca va pas etre simple. Le support ne semble pas complet non plus chez d autres solutions domotiques.

**Comment by Proft1972** [comment]
J'ai rechargé les Json, mais j'ai perdu l'état d'une des prise, c'est normal? Je n'ai plus l'info "status"

edit: j'ai rechargé et maintenant j'ai "status"

**Comment by tcharp38** [comment]
Ha oui désolé. La mise à jour utilise le nom du modele. C est aussi a corriger mais pas eu le temps.

**Comment by Proft1972** [comment]
[AbeilleParser (2).zip](https://github.com/KiwiHC16/Abeille/files/8246913/AbeilleParser.2.zip)
voici le fichier abeille parser

**Comment by tcharp38** [comment]
Merci

Nouvel essai avec ca STP
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8247183/AbeilleParser.class.php.zip)

**Comment by Proft1972** [comment]
[AbeilleParser (3).zip](https://github.com/KiwiHC16/Abeille/files/8247258/AbeilleParser.3.zip)

et voilà

**Comment by tcharp38** [comment]
Voila un nouveau modele
[TS0601__TZE200_yvx5lh6k.zip](https://github.com/KiwiHC16/Abeille/files/8251975/TS0601__TZE200_yvx5lh6k.zip)

et un nouveau code
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8251982/AbeilleParser.class.php.zip)

Tu dois redemarrer le demon et refaire une inclusion.

**Comment by Proft1972** [comment]
Hello,

je viens de mettre les 2 fichiers mais j'ai des valeurs bizarres:
![smart co2 1](https://user-images.githubusercontent.com/93400394/158412363-94d46234-1587-4fef-921c-9d1c0f6d3d91.jpg)

**Comment by tcharp38** [comment]
J'ai besoin du package de logs. Pense à le mettre chaque fois.

**Comment by Proft1972** [comment]
[AbeilleLogs-220315.tar.gz](https://github.com/KiwiHC16/Abeille/files/8255164/AbeilleLogs-220315.tar.gz)

Le voici

**Comment by tcharp38** [comment]
J'ai l impression que tu as bien pris le dernier modele mais pas le dernier code du Parser. non ?

**Comment by Proft1972** [comment]
[AbeilleLogs-220315 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8255706/AbeilleLogs-220315.1.tar.gz)

j'ai pourtant mis en place le fichier, j'ai recommencé des fois qui'il ne l'ai pas pris en compte

**Comment by tcharp38** [comment]
J'ai trouvé encore un bug. Désolé. Ma faute.
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8255800/AbeilleParser.class.php.zip)

**Comment by Proft1972** [comment]
[AbeilleLogs-220315 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8256091/AbeilleLogs-220315.2.tar.gz)

**Comment by tcharp38** [comment]
C est mieux non ?
Tu me fais un résumé de ce qui déconne encore ?

J'ai l'impression que tu dois avoir des erreurs de division à l'affichage, au moins sur la temp & humidité.

**Comment by Proft1972** [comment]
![smart co2 2](https://user-images.githubusercontent.com/93400394/158445517-1e3acca4-f439-4011-a8e0-1c6ecf47be54.jpg)
pour le co2, j'ai l'impression que c'est bon, enb revanche pour la temperature et l'humidité, les valeurs sont fausses à moins que ce soit un probleme de virgule? sur un autre détecteur  placé à coté, j'ai 24° et 40% d'humidité(peut être pas trop précis) et VOC, je ne sais pas à quoi ça correspond
edit: En effet c'était #value/ j'ai mis : c'est impec!

**Comment by tcharp38** [comment]
C est ca, un pb de virgule sur la temp & l humidité.

Nouveau code:
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8256201/AbeilleParser.class.php.zip)

Par contre je ne sais pas pourquoi le VOC remonte 0

**Comment by Proft1972** [comment]
avec le nx code, j'ai 0 en temp et en huidité avec % en unité

**Comment by tcharp38** [comment]
Besoin des logs mais tu as modifié le modele non ?
Si tu as changé la division ca peut expliquer.

**Comment by Proft1972** [comment]
[AbeilleParser (4).zip](https://github.com/KiwiHC16/Abeille/files/8256275/AbeilleParser.4.zip)
voici le log .

sinon je n'ai rien changé à part la division
VOC sont les Composés Organique Volatiles, si je mets le detecteur dans un sac en plastique et que je souffle dedans, le CO2 et le VOC augmentent donc je pense que c'est bon

**Comment by tcharp38** [comment]
Allez, encore un correctif.

[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8256833/AbeilleParser.class.php.zip)

Ha, je crois qu'il manque une autre info mais je n'en connais pas la validite. Phormaldeide ca te parle ? Je crois qu'il peut aussi fourninr cette info mais je n'en suis pas sur.

**Comment by Proft1972** [comment]
Tout fonctionne, merci!
D'après le site, le capteur est capable de mesurer la temperature,l'humidité, le CO2, le VOC (COV) et le HCHO (le formaldehyde) qui est un polluant de l'air

**Comment by tcharp38** [comment]
Nouveau modele
[TS0601__TZE200_yvx5lh6k.zip](https://github.com/KiwiHC16/Abeille/files/8260563/TS0601__TZE200_yvx5lh6k.zip)

Nouveau code
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8260574/AbeilleParser.class.php.zip)

Tu devrais avoir CH20 en +

**Comment by Proft1972** [comment]
J'ai tout , y compris CH20! c'est impec!!!!

**Comment by tcharp38** [comment]
Parfait.
Avant de fermer ce sujet je vais te demander de faire un dernier essai sur la beta que je vais pousser.
Comme j'ai du ajouter du code specifique Tuya, j'ai fini par l'isoler pour que ce soit + propre.
Bref la beta aura ce decoupage et c'est juste pour confirmer que je n'ai rien cassé.

Beta 220316-BETA-1 dispo des demain (17/3) sur le market. Contient toutes les modifs jusqu'a cette heure.

**Comment by Proft1972** [comment]
Pas de probleme, je ferai le test demain 
;)

**Comment by Proft1972** [comment]
Hello @tcharp38 
Tout fonctionne normalement avec la Beta: j'ai le png, les 5 mesures paraissent ok!
Merci beaucoup!
question subsidiaire: as tu eu le temps de regarder pour la tete thermo? [https://github.com/KiwiHC16/Abeille/issues/2175]

**Comment by tcharp38** [comment]
Ok.
Je clos ce sujet. A reouvrir si pbs.
Pour le 2175 on s'y retrouve.

**Comment by Proft1972** [comment]
hello @tcharp38 
je ne sais pas si ca à un rapport mais ma cle plante tous le jours depuis mes modifs

**Comment by tcharp38** [comment]
Tu peux donner + de details ? Qu'observes tu ?
Tu peux filer un package quand tu constates que "c'est planté" ?

**Comment by Proft1972** [comment]
Tous mes equipements passent en timeout, je suis obligé de débrancher la clé et de la rebrancher pour que cela refonctionne.
Si j'ai à nouveau le probleme, je t'enverrai le package de log

**Comment by Proft1972** [comment]
[AbeilleLogs-220324.tar.gz](https://github.com/KiwiHC16/Abeille/files/8344507/AbeilleLogs-220324.tar.gz)
hello, ce soir, je n'ai plus eu de reception à partir de 18h35 ( j'etais sur d'avoir mis le CO2 en  historisation sans moyenne mais je l'ai retrouvé en moyenne)

**Comment by tcharp38** [comment]
Pas sur de comprendre le souci.
D'apres les logs il y a une remontée d info CO2 quasi toutes les 5sec. Idem pour les autres mesures.
D'ailleurs je trouve que c'est bien trop frequent ca.

**Comment by Proft1972** [comment]
Oui les infos sont bien remotées ttes les 5 secondes mais à plus précisément 18h37, il nya pls eu de com et tous mes equipements sont passés en timeout.
Est il possible d'augmenter ce temps et le passer à 1min par ex parce que 5 sec c'est vrai que c'est trop fréquent!
voici la courbe co2 jusqu'à je debrache la clé ce matin à 7h30
![co2](https://user-images.githubusercontent.com/93400394/160075860-62a867e3-f4f3-4a3d-92b8-4bab4424d6bd.jpg)
:

**Comment by Proft1972** [comment]
déconnexion à nouveau ce soir à 17h11. Je mets les logs
[AbeilleLogs-220325.tar.gz](https://github.com/KiwiHC16/Abeille/files/8352623/AbeilleLogs-220325.tar.gz)
Pour info, la led bleue de la clé etait éteinte

**Comment by tcharp38** [comment]
Explique moi ce que tu observes.
Je ne vois rien dans les logs qui montrent un souci.

**Comment by Proft1972** [comment]
lorsque j'ai , ce que jappelle "une deconnexion" tous mes equipements sont en timleout et plus aucun equipement ne communique. Pour essayer, j'ai desactivé l'equipement smart box et j'ai quand meme eu la deconnexion et ce matin,n quand j'ai voulu debracher/rebrancher la clé, ca ne fonctionnait pas! Jai testé ma clé et elle etait en NOK. j'ai fait "rafraichir" et le port usb serie a disparu (c'est deja arrivé, je crois). J'ai remis le port usb Zigate, j'ai sauvegardé et depuis ca refonctionne

**Comment by tcharp38** [comment]
Je vois enfin un souci dans tes derniers logs
- dernier message du parser: [2022-03-25 17:11:43] Abeille1, Type=8011/APS data ACK, Status=00/Success, Addr=28BE, EP=01, ClustId=EF00, SQNAPS=E2
- c'est aussi le dernier message du port serie: [2022-03-25 17:11:43] Got "80110008030028BE01EF00E200"

Bref la zigate semble ne plus envoyer quoi que ce soit.
Pour moi ca n'est pas en lien avec la smart air box. D'accord ?
Reste à voir si il est possible de faire un reset de cette zigate sans intervention manuelle.

Tu peux tenter le reset SW si ca recommence ? (page EQ/avancé)
![image](https://user-images.githubusercontent.com/35221038/160241557-b3a0c070-393c-499d-8a65-dcea836aab4c.png)
Et me filer le package de logs dans la foulée. je veux voir si on arrive à la remettre en service

**Comment by Proft1972** [comment]
J'ai été obligé de redémarrer jeedom car j'avais des pb avec BLEA, peut etre que c'est lié
Pour l'instant tout refonctionne

**Comment by tcharp38** [comment]
Ok.
Pense a ouvrir un autre sujet. On est en train de pourrir celui la et je suis quasi sur que ca n'a pas de rapport avec la Air Box.

**Comment by Proft1972** [comment]
Concernant cette smart air box, n'y aurait t-il pas un genre de reset car la led rouge àl'interieur s'allume et apparement ne s'eteint pas, je pense que c'est quand on depasse une des valeurs seuil (qui serait parfait si on pouvait les parametrer). Si je t'envoie la tete thermo je pourrais t'envoyer aussi la smart air box

**Comment by tcharp38** [comment]
Je veux bien essayer de regarder aussi mais j'espere que tu n'es pas pressé.

**Comment by tcharp38** [comment]
Un petit status: le modele Abeille de la Smart Air Box donne ca

![image](https://user-images.githubusercontent.com/35221038/163785108-5a38106a-0529-4d40-a612-e8e006a60df3.png)

- J'ai respiré dans le capteur pour faire monter VOS & CH20. Tout semble réagir. Les valeurs te semblent correctes ?
- Ce device renvoi enormement d'infos, trop regulierement, quasi toutes les 2nde. Pb apparament connu mais aucune solution trouvée pour le réduire: https://github.com/Koenkk/zigbee2mqtt/issues/8966. Cet afflux de messages peut finir par faire planter la zigate et donc le systeme.
- En dehors du moment ou on branche la Smart Air, je ne vois pas de voyant rouge. Comment le declenchais tu ?

**Comment by Proft1972** [comment]
Salut @tcharp38 
les valeurs me paraissent correctes!
Concernat le voyant, il s'allume je ne sais pas quand mais il est impossible de l'éteindre sauf en débranchant la smart box, je pensais qu'il y avait un parametre à modifier...

**Comment by tcharp38** [comment]
Reste à trouver comment le déclencher pour essayer de l'arrêter

**Comment by Proft1972** [comment]
J'ai essayé en mettant la bax dans un sac en plastique pour faire monter le co2 mais je n'ai pas reussi à allumer le voyant....Je pensais que tu verrais qqch

**Comment by tcharp38** [comment]
Un p'tit résumé de la situation:
- Supporté par Abeille MAIS
- ce périph pourri le reseau en envoyant des infos non stop. Comme cluster privé, aucune idée s'il est possible de changer la frequence de reporting. Souci signalé par differents utilisateurs hors Abeille. **Peut aller jusqu'a faire planter la zigate**.
- De mon côte je n'arrive pas (en dehors de la phase d'inclusion apres reset) a allumer les leds et voir ce qui se passe.

Je vais arreter la pour l'instant, en esperant qu'une mise à jour du FW voit le jour.

![image](https://user-images.githubusercontent.com/35221038/165100650-70b069d2-c995-4cf8-b415-c47c87de69b4.png)

**Comment by tcharp38** [comment]
Correction: Pour une raison encore inconnue j'ai pu déclencher l'alarme (les LEDs s'allument). 
Comme suggéré par @Proft1972, mettre dans un sac plastique et respirer dedans. Ca fini par se déclencher mais aucune idée de l'info qui fait "declencher".
Temp montée jusqu a 30deg sans effet, humidité jusqua 98% sans effet.

Y aurait'il une alarme "over limit" ? Si oui comment faire un reset, autre que debrancher/rebrancher ?

**Comment by Proft1972** [comment]
Hello @tcharp38 ,
C 'est deja bien! j'ai lu le sujet qui parle du Fw mais il n'y a pas de grand espoir!
j'ai essayé pour voir, on verra bien!
L'allumage de la led ne correspond à rien de bien clair, à suivre si unn jour il y a un nouveau fw
Merci en tout cas!

**Comment by tcharp38** [comment]
Cet équipement est à priori bien supporté MAIS équipement déconseillé car pourrit le réseau par des messages inutiles et beaucoup trop fréquents.

Je recommande d'eviter ce periph, à moins qu'une mise à jour FW existe un jour.

Je clos.
