### ISSUE TITLE
Gros soucis zigbee et abeille

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2331]
Bonjour,

J'ai perdu tous mes capteurs, est ce a cause de la derniere BETA? 
![image](https://user-images.githubusercontent.com/77990298/154800145-eb0477f8-5db6-4a74-9120-1505ff4a11f6.png)

**Comment by tcharp38** [comment]
Salut @Seby9576 
J'en doute vu que je suis dessus sur plusieurs boxes mais file moi un package de logs que je regarde un peu.

Tu n'as fait qu'une mise à jour en beta et rien d'autre ? Aucun autre evenement ?

**Comment by Seby9576** [comment]
[AbeilleLogs-220220.tar.gz](https://github.com/KiwiHC16/Abeille/files/8104500/AbeilleLogs-220220.tar.gz)

Salut je dirais que c'est arrivé samedi matin, j'ai débranché et rebranché la zigate et scruté le réseau et j'ai pus récupéré mes équipements sauf deux.

**Comment by tcharp38** [comment]
Ha donc c'est le log apres recup.
Manque de pot rien à signaler dans celui la.
Les 2 en question, quels sont ils ? (type) Donc toujours en timeout je suppose ce qui sous entend qu'ils n'ont remonté aucun info depuis.

**Comment by tcharp38** [comment]
@Seby9576 
Tu en es ou la dessus ?

**Comment by Seby9576** [comment]
Salut,

Dsl, ceux qui sont resté en time out sont sur pile ( 3 capteurs température humidité pression aqara) et ils font parties de ceux que je perds de temps en temps mais je ne sais pas pourquoi et c'est souvent en groupe.
Je les ai réinclus car sinon ils ne reviennent pas tout seul.

**Comment by tcharp38** [comment]
Ha ok. J'ai le meme souci comme beaucoup. 
Ces capteurs pourtant si attirants au debut ont un comportement de daube qui fait que j'en veux plus.
Le pb est qu'ils ne reviennent pas seuls sur le reseau si qqch deconne.

Bref à utiliser en champ tres direct, sans obstacles ou murs armés, ou poubelliser.

Je considere ce sujet clos du coup.
Ok ?

**Comment by Seby9576** [comment]
Ok seul soucis c'est qu'on ne sait pas pourquoi ca planté. Oui tu peux clôturer

Pour les capteurs de température et humidité si tu as des conseils ? Il semblerait que Sonoff soit mieux.

Toi tu as quoi ?

**Comment by tcharp38** [comment]
Effectivement on ne sait rien. Si jamais ca se reproduit, pense a mettre le pacakge de logs de cote tout de suite.

J'ai acheté un sonoff et un tuya recemment mais pas encore de retours dessus pour voir s'ils se reconnectent.
Donc trop tot pour des infos utiles mais je garde les Xiaomi pour des liaisons simples et sans routeur.
