### ISSUE TITLE
Récupération des équipements fantomes

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2332]
J'ouvre ce sujet pour discuter/améliorer/corriger la récupération des équipements fantomes.. donc ceux toujours dans le réseau zigbee mais inconnus d'Abeille.

Utile par exemple lorsqu'on restore un vieux backup (donc on ne restore que Jeedom) alors que depuis d'autres équipements ont rejoint le réseau.

Sujet Jeedom: https://community.jeedom.com/t/recuperation-equipements-zigbee-apres-reinstallation-jeedom/72644

**Comment by eoeir** [comment]
Bonjour @tcharp38,

Voici un package de logs générés en mode debug suite à une (nouvelle) réinstallation propre :
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8106844/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/8106848/Abeille.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8106849/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8106850/AbeilleSerialRead1.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/8106851/AbeilleConfig.log)

Actuellement, je n'ai aucun device récupéré et je vois deux devices inconnus dans le réseau (Abeille1/704F et Abeille1/F128).
Je n'ai pas de décompte précis mais mon réseau en comptait une dizaine.

**Comment by eoeir** [comment]
Depuis, j'ai récupéré 8/10 équipements (3 routeurs et 5 points de terminaisons) qui ont été créés sur une période d'environ 48h sans aucune intervention de ma part dans Jeedom.
Il ne me manque plus que 2 capteurs qui ne sont pas réapparus pour l'instant. La récupération semble mieux fonctionner qu'avant.

**Comment by tcharp38** [comment]
Salut @eoeir 
Déja as tu trouvé une doc Abeille sur le sujet ? Je ne sais plus si je l'avais mise à jour mais sinon il faut.

Le principe de la récupération est le suivant:
- un equipement se signale mais n'est pas connu de Jeedom
- en fonction des infos qu'il manque on l'interroge (adr IEEE, model & manuf ID)
- une fois identifié il est créé dans Jeedom

Tu as un exemple de le log parser, a priori d'un capteur de lumiere.

> [2022-02-20 23:43:22] Abeille1, Type=8102/Attribute report, SQN=85, Addr=51EE, EP=01, ClustId=0400, AttrId=0000, AttrStatus=00, AttrDataType=21, AttrSize=0002
> [2022-02-20 23:43:22]   Illuminance, MeasuredValue=0000 => 0.99976976799816Lx
> [2022-02-20 23:43:22]   MeasuredValue, hexValue=0000 => 0
> [2022-02-20 23:43:22]   deviceUpdate('', ''): Unknown device detected
> [2022-02-20 23:43:22]   Requesting IEEE

La ou c'est compliqué c'est pour les End Devices. Ceux pour la plupart sont sur batterie donc ne se reveillent que pour faire qqch d'utile (envoyer un reporting par ex) et se remettent en vieille tout de suite derriere. Il n'ecoutent plus rien.
Bref le temps est tres tres court avant que l'interrogation qu'on lui envoi atteigne sa cible. Abeille a besoin d etre encore optimisé pour le raccourcir.
Dans l'exemple precedent le capteur ne repond pas. La requete est arrivée trop tard.

Dans ce cas, pas trop de choix, soit le reveiller souvent si on sait de quel device il s'agit, soit carrement refaire une inclusion.

Ca fait du sens tout ça ?

Autre point, un package de logs peut etre obtenu directement de la page support/telecharger tout. C'est fait pour ca et c est bien plus complet que ce que tu ne peux voir.

**Comment by tcharp38** [comment]
A propos des 2 fantomes qui restent, tu as une idée de qui ils sont ?
Je vois déja une piste d'amélioration mais pas sur que ca suffise pour aller jusqu'au bout avec ces 2 la.

**Comment by FlorianHergo** [comment]
Bonjour,

Je me rejoins a votre thread. Je suis dans le cas exactement le même que vous. Nouvelle VM suite à crash. Tous les capteurs de Jeedom and co sont tous OK. Sauf Abeille et tous les volets. Je peux me joindre à vous pour tester si je récupère bien tout.
Toute fois, j'ai un autre soucis avant cela.

Sous Abeille, il ne veut pas se connecter au port TTYusb0, pourtant sous l'application Zigate il peut se connecter à la clef.
Bien sur j'ai essayé de replugé la clef plusieurs fois. Et le plugin Zigate est éteint quand j'utilise Abeille.

```
[2022-02-23 14:13:38] Vérifications du port '/dev/ttyUSB0'
[2022-02-23 14:13:38] = ERREUR: Le port est utilisé par le process '1008'.
[2022-02-23 14:13:38] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
[2022-02-23 14:13:38] =         Details du process 1008:
[2022-02-23 14:13:38] =           PPid=672, cmd='/usr/sbin/apache2 -k start'
[2022-02-23 14:13:38] Redémarrage des démons
```

Freebox Delta.

[AbeilleLogs-220223.tar.gz](https://github.com/KiwiHC16/Abeille/files/8124577/AbeilleLogs-220223.tar.gz)


Merci d'avance

**Comment by tcharp38** [comment]
@FlorianHergo 
J'ai réouvert le sujet "Port serie NOK". On s'y retrouve vu que c'est ta priorité, mais pas ici. Merci

**Comment by eoeir** [comment]
> 
Je n'ai pas trouvé de documentation autre que celle là (https://kiwihc16.github.io/AbeilleDoc/Remplacement.html) qui mentionne les équipements fantomes mais juste une ligne sur la récupération.

Ton explication est très claire et effectivement, comme les deux équipements manquants sont des capteurs Aqara sur batterie (le capteur de luminosité et un capteur d'ouverture) je suppose qu'ils restent en ligne que trop peu de temps pour que la requête des infos manquantes n'arrive.

Je ne sais pas si c'est lié mais je constate aussi une certaine instabilité du "réseau" zigbee. Hier matin il a planté et tous les équipements étaient en timeout. Les équipements sont revenus en ligne après un reboot du Raspberry.

Ce soir, je constate à nouveau que presque tous les équipements sont en timeout.

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/8127974/Abeille.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8127977/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/8127978/AbeilleConfig.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8127979/AbeilleParser.log)
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8127981/AbeilleSerialRead1.log)

**Comment by tcharp38** [comment]
Salut
Je vois beaucoup d'activité dans ton réseau, trop.
Une des raisons peut etre le fait que tu aies mis 'non' sur "Blocage récuperation équipement inconnu". C'est le cas ?
Si oui alors lors de l'analyse reseau a minuit, il tente de recuperer tous les eq inconnus et ca genere trop de messages. 
Ca peut etre la raison de l'instabilité dont tu parles.

Autre point, le package de logs est dispo via la page support/telecharger tout. Il est plus complet et c est plus simple pour toi.

**Comment by eoeir** [comment]
Je te confirme que j'avais mis 'non' sur "Blocage récuperation équipement inconnu". Je viens de le changer sur oui.
Est-ce que cela va avoir un impact sur pour les deux capteurs manquants ?

Je ne suis pas convaincu que cela viennent de la tentative de récupération de minuit car j'ai observé les perturbations à des heures assez variées.

Pour le package de log, j'ai essayé d'utilisé la fonction mais sauf si je rate quelque chose je ne télécharge rien.

**Comment by tcharp38** [comment]
Laisse le sur oui, et pense à sauver & redemarrer les demons apres changement.
Pour moi ce truc fout la pagaille.

Concernant tes 2 derniers capteurs, pas sur qu'Abeille y arrive du tout. Si ils sont accessibles, je te suggere de les reinclure tout simplement.

Côte package... je ne sais que dire. Tout le monde s'en sert donc globalement ca fonctionne plutot bien. Tu as du tomber dans un cas particulier que je ne comprends pas pour l' instant.

Tu bascules sur la stable du jour ?

**Comment by eoeir** [comment]
Je suis repassé sur la version stable.
La récupération des logs fonctionne dans cette configuration.

En revanche je suis toujours en vrac sur mes équipements, la plupart restent en timeout malgré un redémarrage.

**Comment by tcharp38** [comment]
Prends l'habitude d attacher un package de logs quand tu as un souci. On peut comprendre ce qui se passe.
La page santé dit quoi ?

**Comment by FlorianHergo** [comment]
Hello @tcharp38,

juste pour etre sur avant de faire l'upgrade vers le 3.21 comme demandé, peux-tu me confirmer que l'information du site est fausse et que malgré le fait que j'ai une V1, je peux bien sur mettre la 3.21 en LEGACY ?

![image](https://user-images.githubusercontent.com/8419725/155701904-d544ac98-b7fb-487b-9f0c-a11c15044d97.png)

**Comment by tcharp38** [comment]
Salut @FlorianHergo 
Ou vois tu une fausse info ?

Dans ton cas et de maniere à ne pas réappairer, tu passes en 3.21-LEGACY.
Mais il est evident que le jour ou tu dois refaire tout l'appairage, alors la il faudra repartir propre, sur la version OPDM (celle qui equipe la v2 d'ailleurs).

Fais la sauvegarde de la zigate (flash ET eeprom).
puis fais la mise a jour en 3.21-LEGACY.
C'est le plus "safe" pour toi qui ne veux pas reappairer aujourd hui.

**Comment by eoeir** [comment]
> Prends l'habitude d attacher un package de logs quand tu as un souci. On peut comprendre ce qui se passe. La page santé dit 
quoi ?

![image](https://user-images.githubusercontent.com/71673288/155805468-ee0b43bd-1b7e-4764-95bf-b14246d793d2.png)

J'ai récupéré une partie des équipements mais pas tous. De plus voici des dysfonctionnements constatés à l'instant : 
- je n'arrive pas à réintégrer le capteur de luminosité qui était fantome (cf. plus haut),
- je n'arrive pas non plus à réinclure le capteur TS0201
- je n'arrive pas à commande l'ampoule Tradfri ou le relay.c2acn01

Je vois pas mal de timeout dans le log AbeilleCmd mais je ne sais pas si c'est lié :
zigateAckCheck(): WARNING: Zigate1 cmd 0100 TIMEOUT (SQNAPS=) => Considering zigate available.

[AbeilleLogs-220225.tar.gz](https://github.com/KiwiHC16/Abeille/files/8144968/AbeilleLogs-220225.tar.gz)

**Comment by eoeir** [comment]
Petit update : mon réseau est de plus en plus en vrac
![image](https://user-images.githubusercontent.com/71673288/156251705-8977ef1f-e989-4827-b140-d9474bd8d853.png)

Une idée pour avancer ?

[AbeilleLogs-220301.tar.gz](https://github.com/KiwiHC16/Abeille/files/8164870/AbeilleLogs-220301.tar.gz)

**Comment by tcharp38** [comment]
@eoeir 
Trop à la fois et pas sur que ca ai un lien encore avec le sujet.

On prend par ex 020F, le relay.c2acn01
Sa derniere remontée d'info est vieille

> [2022-03-01 08:27:34] Abeille1, Type=8102/Attribute report, SQN=CA, Addr=020F, EP=01, ClustId=0000, AttrId=FF01, AttrStatus=00, AttrDataType=42, AttrSize=0044
> [2022-03-01 08:27:34]   Xiaomi proprietary (Double relay)

En fait il est interrogé toutes les 15mins mais ne repond pas tout le temps.
Si la communication avec lui est routée.. le router est HS.
Sinon souci de perturbation elec.
En tout cas pour l'instant je ne vois pas Abeille en cause pour celui la.

Passons au BASICZBR3/31C0
Idem au cas precedent. ll ne repond plus aux interrogations

> [2022-03-01 22:15:55] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=31C0, EP=01, ClustId=0000, SQNAPS=EC

BBB2 & B613 sont des capteurs sur pile donc ils remontent une info quand ils en sentent le besoin.
Du coup cette info semble pas relayée jusqu a la zigate.

Enfin le TS201 est dans le meme cas que les 2 premiers. Il est interrogé toutes les 15mins mais ne repond plus.

Si on regarde ton premier rapport avec la vue réseau, on voit que la TRAFRIBulb semble relayer tous ces equipements en "timeout".
Tu peux confirmer en la laissant allumée 20mins par ex pour voir si ils reviennent "vivants".
Si c'est le cas ton maillage reseau n'est pas bon car dependant de cette ampoule qui, je suppose, est souvent hors tension donc ne joue pas son role de relais.

Dis moi si ca fait du sens ou pas. En tout cas ...ca semble hors sujet "fantome" maintenant.

**Comment by eoeir** [comment]
Pour conclure, j'ai fait quelques tests ce WE. En laissant l'ampoule allumée, pas de changement.
J'ai rallumé mon setup initial (RPi 1B + Pizigate) et j'ai récupéré le réseau et j'ai pu réinclure les équipements manquants.

Pour info, voici comment il est routé : l'ampoule n'est pas sensée relayer de capteurs.
![Abeille](https://user-images.githubusercontent.com/71673288/156981346-72450980-3e7f-45f7-9e92-efb373bdd59c.PNG)

Donc je pense que le soucis vient plutôt de la gateway "en version RPi 4".

Comme on est sortis du sujet initial, je vais explorer cette piste ailleurs ;)

Merci pour ton aide.

**Comment by tcharp38** [comment]
Oui on est hors sujet mais n hesite pas a en creer un particulier si besoin.
Je ne sais pas/plus de quelle gateway tu parles mais j'avais créé ce sujet
https://github.com/KiwiHC16/Abeille/issues/2116
et j'en ai monté un du coup pour test.

**Comment by tcharp38** [comment]
Autre améliorations dans la 220329-BETA-1

**Comment by tcharp38** [comment]
Je clos ce sujet.
Les equipements sont récupérés automatiquement (au moins en partie) si ils donnent signe de vie alors qu'ils sont inconnus de Jeedom.
