### ISSUE TITLE
Equipements Osram Smart+ (Ledvance) non reconnus sur Zigate+ (v2), ok sur Zigate (v1)

### ISSUE THREAD

**Issue by ghost** [KiwiHC16/Abeille#2333]
Bonjour,

Je viens de changer ma Zigate v1 (en format Pizigate) pour une v2. J'ai pu réintégrer tous mes équipements sauf des prises connectées et une ampoule Osram Smart+. Je ne vois pas ce qui bloque. J'ai essayé sur un jeedom tout juste descendu, le problème persiste.

Ci-joint les logs que j'ai pu recueillir (tentative d'inclusion d'une prise vers 20h19). Le bouton "Télécharger tout" n'a pas fonctionné, j'ai inclus tous les fichiers un par un.

Je reste évidemment à disposition pour d'autres tests.

Version Abeille: 220218-BETA-1
Kernel: ["Linux jeedom 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU\/Linux"]
Zigate 1: 0005-0321

**Comment by tcharp38** [comment]
Salut @FQsqQ 
Il n'y a rien d'utile dans ces logs.
A l'heure que tu donnes, aucun equipement ne se signale à Abeille.
Le pb semble donc purement zigate si tu es sur de la procedure de reset.

Tu peux peut etre reconfirmer le fonctionnement en zigate v1. Si ca marche... pas de doutes, la zigate est coupable.

**Comment by ghost** [comment]
Je confirme le fonctionnement sur la v1. Peut-être donc le reset de l'équipement qui ne fonctionne pas.
Je vais également me renseigner sur un possible échange de la zigate.
