### ISSUE TITLE
Mini Smart Socket avec remontée conso et puissance (TS011F, _TZ3000_5f43h46b)

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2334]
Salut @tcharp38 
Je reviens sur ce sujet car ma prise m'ayant lâchée Domotique Store me l'a remplacée gratuitement mais lorsque je la réinclus elle est considérée comme une TS0121 et non comme un TS0121__TZ3000_8nkb7mof et je n'ai à nouveau plus aucune remontée de puissance et de conso. Voici la config :
![image](https://user-images.githubusercontent.com/52486183/154934082-3e2dc0f6-ef10-4a9e-82ec-3d54e7887a9d.png)
Que puis-je faire ? Merci
![image](https://user-images.githubusercontent.com/52486183/154934481-8d1646dc-60ad-4235-8c01-957b6a3ae214.png)

Salut @Kenderv
Alors c'est qu'elle s'identifie comme une autre prise.
Genere moi un discovery et ouvre un autre sujet STP vu que ca n'est pas une "TS0121" (ok), "_TZ3000_8nkb7mof" (PAS ok)

Voilà, Merci
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/8108558/discovery.json.txt)

C'est pourtant, physiquement, la même prise que la précédente, apparemment de type Tuya

**Comment by tcharp38** [comment]
Y a t'il une ref fabricant ?
Une marque meme si "powered by Tuya" ?
Parmis les images dispos, quelle est la plus representative de ce periph ?

**Comment by tcharp38** [comment]
[TS011F__TZ3000_5f43h46b.zip](https://github.com/KiwiHC16/Abeille/files/8109980/TS011F__TZ3000_5f43h46b.zip)
A tester
decompresser dans core/config/devices

**Comment by Kenderv** [comment]
Toujours le même problème, 
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/8110935/discovery.json.txt)
Il s'affiche comme TS0121

**Comment by Kenderv** [comment]
J'ai cru que c'était un problème de droit, le répertoire et les fichiers étaient en 755, je les ai passé en 775 mais c'est toujours pareil. Le proprio et le groupe sont OK en 775 et en www-data

On dirait qu'il ne prend pas le bon json ?? Aurais-je loupé quelque chose quelque part ?

Voilà le message d'inclusion 
2022-02-21 18:29:02 Abeille Nouvel équipement identifié (Yagusmart Tuya ZigBee Smart Switch). Création en cours. Rafraîchissez votre dashboard dans qq secondes.

**Comment by Kenderv** [comment]
L'image la plus ressemblante est celle-ci
![image](https://user-images.githubusercontent.com/52486183/155004561-bb1c2325-c932-48db-960a-adae23b81f1b.png)
https://www.domotique-store.fr/domotique/usages/mesure-de-consommation-energetique-domotique/prises-domotique-mesure-consommation-energie/1474-prise-connectee-zigbee-16a-avec-mesure-de-consommation-compatible-tuya-smart-life-conbee-ii-et-zigate.html?search_query=prise+zigbee&results=127

**Comment by tcharp38** [comment]
Tu me files un package de logs lors de l'inclusion ?
Si tu as decompressé le fichier au bon endroit et redemarré le plugin, je ne vois pas de raison pour qu'il ne soit pas reconnu.

**Comment by Kenderv** [comment]
Bonjour,
Autant pour moi, je n'ai pas pensé à redémarrer le plugin. Je l'ai fait ce matin et l'inclusion s'est bien faite. Sauf erreur de ma part, Total Power = Conso cumulée, RMS Current = Ampérage, Active Power = Conso instantanée. Les 2 derniers restent à zéro lors de l'allumage d'une lampe avec ampoule halogène.  Voici un package de logs et l'adresse de la prise
![image](https://user-images.githubusercontent.com/52486183/155087910-8e8b02c5-1755-4973-afbd-8d3683e6737b.png)
[AbeilleLogs-220222.tar.gz](https://github.com/KiwiHC16/Abeille/files/8114728/AbeilleLogs-220222.tar.gz)
Bonne journée

**Comment by Kenderv** [comment]
Si je lance manuellement les commandes Get Total power et Get Active Power les infos sont bien remontées. Par contre si j'éteins la lampe les valeurs RMS Current et Active Power ne reviennent pas à zéro. Total Power augmente de 1Kwh toutes les 2-3 minutes pour une ampoule de 48W. Merci

**Comment by tcharp38** [comment]
Salut @Kenderv 
Tes logs sont vides. Tu n'es probablement pas en mode debug.

La question est de savoir si ce device remonte des infos de lui meme ou si on est obligé de faire du polling. La je peux pas repondre.
Active le mode debug, allume ta prise, et file moi un package au bout de qq mins pour voir si qqch remonte de lui meme.

Cote total power, je suppose qu'il faut appliquer une division par 1000.

**Comment by Kenderv** [comment]
Ouais, le mode debug n'était pas activé. Je ne pense à rien, ça doit être du à l'âge. J'ai passé le Total Power en /1000 avec 2 décimales. voilà les logs après quelques minutes et quelques allumages
[AbeilleLogs-220222.tar.gz](https://github.com/KiwiHC16/Abeille/files/8115899/AbeilleLogs-220222.tar.gz)


HS Le problème de la caudale rétrécie n'est pas réglé, je viens de l'avoir

**Comment by Kenderv** [comment]
Le RMS Current est exprimé en mA. Je ne suis pas un spécialiste en électricité mais cela ne correspond il pas à la Tension exprimée en V. Connais tu la différence ebtre RMS Current et RMS Voltage ? Merci et mille excuses pour ces questions un peu HS.

**Comment by tcharp38** [comment]
Pas de soucis pour les questions.

RMS current = A ou mA => courant instantané
RMS voltage = V => tension instantanée

Tes logs toujours vides. Je soupconne que tu n'as pas redemarré Abeille apres changement niveau de log.

**Comment by Kenderv** [comment]
Oui, encore une fois je suis désolé d'oublier de relancer Abeille après les modifs apportées à sa configuration. Je viens de le faire et j'au relancé manuellement les Get Total Power, RMS Voltage et RMS Current + plusieurs allumages et extinction de l'ampoule. . J'attends un peu de temps et je t'envoie tout cela. Merci pour tes réponses, mais je suis surpris de voir le RMS Voltage à 218V et le RMS Current à 238V alors que d'autres prises me donnent un tension à 238V? Une expilcation ? Merci de ton aide. Toujours pas de modification des valeurs à l'extinction de la lampe. 
![image](https://user-images.githubusercontent.com/52486183/155275670-bae4abad-962c-4f9b-a65c-189f0019815c.png)
[AbeilleLogs-220223.tar.gz](https://github.com/KiwiHC16/Abeille/files/8122508/AbeilleLogs-220223.tar.gz)
Bonne journée

**Comment by tcharp38** [comment]
238mA pour 49W c'est pas déconnant.

Cote inversion Current<>Voltage, Abeille ne fait pas d'erreur. C'est bien l'info qui est remontée mais c'est effectivement troublant. Si erreur, c'est le firmware du device qui fait une boulette.
A essayer sur une autre charge. 

Cote reporting, le Total power remonte tout seul mais ca semble etre le seul.
Donc il faut mettre en place du polling pour les autres infos.

A tester (ecraser, refaire inclusion ou recharger JSON)
[TS011F__TZ3000_5f43h46b.zip](https://github.com/KiwiHC16/Abeille/files/8139968/TS011F__TZ3000_5f43h46b.zip)

**Comment by Kenderv** [comment]
Je viens de remplacer le fichier json, relancer Abeille, supprimer la prise de Jeedom, ré-inclusion. 
Toujours pareil, pas de remontée de valeurs. J'ai modifié la valeur de Total Power en divisant #value#/1000 arrondi 2, c'est OK, l'Active power reste à 0, le RMS Current est à 238V
![image](https://user-images.githubusercontent.com/52486183/155730298-a0111e7f-2740-440f-86f1-c351a6e2bd07.png)
et les logs après re-inclusion
[AbeilleLogs-220225.tar.gz](https://github.com/KiwiHC16/Abeille/files/8141819/AbeilleLogs-220225.tar.gz)

J'espère ne rien avoir oublié cette fois

**Comment by tcharp38** [comment]
D'apres tes logs tu n'utilises pas mon fichier; pas la bonne icone, et le div 1000 en fait deja partie.

Il suffit de regarde le log Abeille et chercher "createDevice()"...

> [2022-02-25 14:57:44][DEBUG] : msgFromParser(): Eq announce received for Abeille1/F0E9, jsonId='TS011F__TZ3000_5f43h46b', jsonLoc='Abeille'
> [2022-02-25 14:57:44][DEBUG] : createDevice(create, dev={"net":"Abeille1","addr":"F0E9","ieee":"A4C13863DAD8805D","modelId":"TS011F","manufId":"_TZ3000_5f43h46b","jsonId":"TS011F__TZ3000_5f43h46b","jsonLocation":"Abeille"}
> [2022-02-25 14:57:44][DEBUG] :   New device Abeille1/F0E9
> ...
> [2022-02-25 14:57:44][DEBUG] :   config={"icon":"JR-ZPM01","mainEP":"01"}
> ...
> [2022-02-25 14:57:44][DEBUG] :   Adding cmd 'Total power' => '0702-01-0000', ''
> 
>

**Comment by Kenderv** [comment]
Que te dire ? D'abord un grand merci pour ta patience, je ne parle pas de ta compétence, elle n'est plus à prouver. J'espère que tous tes interlocuteurs ne sont pas aussi étourdis (pour ne pas dire pire) que moi. Je suis désolé. On va terminer la semaine sur une bonne nouvelle, tout fonctionne correctement quand on utilise les bons fichiers. Merci encore et bon week-end. Tu peux clore le post, si d'autres problèmes se présentaient je te ferai signe.

**Comment by tcharp38** [comment]
Ha ben ca c'est une bonne nouvelle.
Je clos mais à réouvrir pour tout souci avec ce device.

**Comment by Kenderv** [comment]
Re-bonjour,
Décidément, je crois que je ne vais pas m'en sortir. Je viens de recommander cette même prise mais elle n'est pas reconnue comme les précédentes, pas de puissance, pas de remontée de conso et conso cumulée. Je te joins un discovery.json. Peux-tu, stp, me dire ce que tu en penses ? Merci
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/8326478/discovery.json.txt)
Bonne soirée

**Comment by Kenderv** [comment]
Salut @tcharp38 ,
Bon, en regardant le discovery.json que je t'ai envoyé hier, j'ai remarqué que le champ value du servClusters 0000 attributes 0004 avait une valeur (_TZ3000_typdpbpg) différente de ma prise précédente (_TZ3000_5f43h46b). J'ai repris le répertoire que nous avions créé la dernière fois et remplacé les anciennes valeurs par les nouvelles partout où je les ai trouvées dans les 2 fichiers .json en me disant que comme c'était la même prise j'avais une petite chance que ça fonctionne. J'ai relancé le demon d'Abeille et là Bingo, ça a marché.  La démarche était-elle correcte ?

**Comment by Kenderv** [comment]
Tu peux donc clore à nouveau le post. Merci

**Comment by tcharp38** [comment]
Salut
Ta démarche n'est pas si mal. Cloner le modele quand on considere qu'il est identique mais avec une signature diferente ca le fait.
Tu peux aussi ajouter "alternateIds" dans le modele d origine.

Ca correspond à ca ? https://zigbee.blakadder.com/Tuya_YX-DZ005.html

**Comment by ValFaure** [comment]
Je me permets de m'incruster dans la conversation car grâce à ton modèle j'ai pu faire fonctionner parfaitement une prise similaire qui au départ n'était reconnue par abeille que partiellement (seulement le on/off, pas de remontée de conso).

La mienne est vendue en tant que "Tuya smart plug" et s'annonce avec un manufId "_TZ3000_gjnozsaz" au lieu de "_TZ3000_5f43h46b" et elle ressemble à ça :
![prise](https://user-images.githubusercontent.com/105385971/167923681-d948f38e-023d-4346-abc6-bba4f6934ae4.PNG)

Du coup j'ai cloné le modèle et j'ai juste modifié les occurrences "5f43h46b" par "gjnozsaz".
Est-ce qu'il vaut mieux du coup passer par un paramètre "alternateIds" ? Et dans ce cas où est-ce que tu l'insères exactement ? Dans le premier bloc du .json à la suite de "manucfacturer","model","type", .... ?

En tout cas merci déjà pour le modèle qui m'a permis de très vite avoir une prise fonctionnelle !
