### ISSUE TITLE
Nouvelle install, zigate introuvable

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2336]
Salut !

J'ai trouvé un autre pc, j'ai fait une install complète dessus, débian, jeedom, abeille. en vue de récupérer l'autre pc pour faire des test avec ma zigate V2.
Impossible d'ajouter la zigate, j'ai le mouliné jeedom mais rien ne se fait. j'ai testé 3 fois de tout réinstallé, faire un chmod 777 sur ttyUSB etc, rien n'y fait. que ce soit en stable ou en beta.

Je mets les log, j'espère que ca sera utile :) 
En espérant qu'on trouve. pas possible tout ce qui m'arrive avec les zigates ^^

![image](https://user-images.githubusercontent.com/49479084/155611680-f138c7c3-8a4d-4d7e-aca3-a091f8125093.png)
![image](https://user-images.githubusercontent.com/49479084/155611720-0f543dba-d228-46ca-8899-bf0d3f5c03fb.png)
[AbeilleLogs-220224.tar.gz](https://github.com/KiwiHC16/Abeille/files/8136544/AbeilleLogs-220224.tar.gz)

**Comment by Jake309** [comment]
en faisant usb-devices j'obtiens ca:
T:  Bus=02 Lev=01 Prnt=01 Port=09 Cnt=01 Dev#=  2 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=0403 ProdID=6015 Rev=10.00
S:  Manufacturer=FTDI
S:  Product=ZiGate
S:  SerialNumber=ZIGATE+
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=90mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=ftdi_sio

et un lsusb:
Bus 002 Device 002: ID 0403:6015 Future Technology Devices International, Ltd Bridge(I2C/SPI/UART/FIFO)

**Comment by tcharp38** [comment]
@Jake309 
Tu as progressé ?

**Comment by tcharp38** [comment]
@Jake309 
Que fait on de ce sujet ?

**Comment by tcharp38** [comment]
@Jake309 
Je clos. A réouvrir si tu as matière à faire avancer le sujet.
Le dernier package de logs ne contenait que des logs quais vides, donc surement mode debug pas actif.
