### ISSUE TITLE
Erreur "Forbidden" quand on essaye de remplacer un equipement

### ISSUE THREAD

**Issue by vince122** [KiwiHC16/Abeille#2337]
Bonjour,

J'essaye d'utiliser la fonction (très pratique) de remplacement d'équipement.

J'essaye de remplacer un équipement HS par un équipement neuf, ça me redirige à l'adresse : http://JEEDOM/plugins/Abeille/desktop/php/AbeilleFormAction.php

Mais j'obtiens l'erreur suivante :
(403)
Forbidden
You don't have permission to access this resource.

J'ai essayé de desactiver le fichier .htaccess en le renomant, ça a fonctionné.
Je pense qu'il va falloir que tu rajoutes une regex pour qu'on puisse accéder à ces fichiers.

Je suis en JEEDOM 4.2.13
PHP 7.4.25
Debian 11.2

A+
Vincent.

**Comment by tcharp38** [comment]
Salut @vince122
Parfait. J'attendais un utilisateur pour me pencher sur le souci introduit avec jeedom 4.2.
Sera tu prêt à basculer sur la bêta pour ce sujet ?

**Comment by vince122** [comment]
Par la présente, j'accepte de service de cobaye pour l'avenir du plugin Abeille 

Yes pas de soucis

**Comment by tcharp38** [comment]
Comment utilises tu cette fonctionalité et as tu trouvé une doc ?

**Comment by vince122** [comment]
Si tu parles de la fonctionnalité de remplacement, j'ai trouvé cette doc qui n'est pas à jour : https://kiwihc16.github.io/AbeilleDoc/Remplacement.html

Maintenant c'est assez intuitif, il y a des menus déroulants dans la page principale d'Abeille, donc j'ai sélectionné l'équipement HS dans le menu du haut et sélectionné l'équipement neuf (après l'avoir appairé) dans le menu du bas

Sinon pour passer en Beta, j'ai été dans le Market j'ai sélectionné Abeille puis Installer Beta
Je suis en 220223-BETA-1

**Comment by tcharp38** [comment]
On est d'accord que ca ne fait de sens que pour remplacer un equipement HS par un du MEME modele ?
Ou tu vois un autre interet ?

**Comment by tcharp38** [comment]
220228-BETA-2 a tester (dispo le 1/mars). Je viens de la faire avec d'autres mise à jour. J'ai aussi revu la partie doc.

Pense à faire un backup Jeedom avant test.
Et ne tester qu'un equipement à la fois.
Merci pour tes retours

**Comment by tcharp38** [comment]
Je clos. Je considere le point résolu sur la beta.
A reouvrir si besoin
