### ISSUE TITLE
Support Interrupteur filaire connecté Legrand pour volet roulant (Shutterswitchwithneutral)

### ISSUE THREAD

**Issue by xyko0** [KiwiHC16/Abeille#2340]
Bonjour,

J'aimerais savoir s'il est possible d'intégrer ce genre d'équipement avec Abeille : 
https://www.legrand.fr/pro/catalogue/42798-version-dooxie-with-netatmo/interrupteur-filaire-connecte-pour-volet-roulant-et-store-dooxie-with-netatmo-blanc-sans-plaque
J'ai un peu cherché et n'ai pas trouvé la réponse dans les autres issues, je crois que le sujet n'avait pas été jusqu'au bout.

Sur le site de la Zigate, il est indiqué que l'équipement est compatible : 
https://zigate.fr/produits-legrand-compatibles-zigate/compatible/interrupteurfilaireconnectpourvoletroulant/

Merci beaucoup

**Comment by tcharp38** [comment]
Salut @xyko0 
A priori, si le site Zigate dit que c'est compatible ca doit etre integrable.
Ceci dit, l'idéal serait de savoir si il est supporté sur d'autres boxes domotiques, genre Domoticz ou autre.

**Comment by xyko0** [comment]
Salut @tcharp38 
Dans la liste des éléments compatibles, je vois ça : 
![image](https://user-images.githubusercontent.com/52315700/156141632-74848565-b674-46ff-a924-a6c7674b6966.png)
Est-ce que vous pourriez me confirmer qu'il s'agit du même élément ?

**Comment by tcharp38** [comment]
Je ne peux pas confirmer. Ce modèle date d'une époque ou je ne bossais pas sur Abeille.
Il ne contient ni le fabricant ni la ref du modele
mais à priori ca correspond à ca: https://zigbee.blakadder.com/Legrand_067726.html

**Comment by xyko0** [comment]
Ok c'est une bonne nouvelle pour moi alors :)
C'est la version antérieur de Legrand
Dommage que je ne puisse pas vérifier que ça fonctionne avec les nouvelles versions Dooxie qui semblent très similaires mais si j'ai validation que ça fonctionne sur le matoss que tu m'as indiqué, je vais surement partir là-dessus. 
Merci bcp !

**Comment by xyko0** [comment]
Pour info et ceux qui tomberait sur cette issue, j'ai acheté la version filaire suivante : https://www.legrand.fr/pro/catalogue/42798-version-dooxie-with-netatmo/interrupteur-filaire-connecte-pour-volet-roulant-et-store-dooxie-with-netatmo-blanc-sans-plaque

ça fonctionne nickel en suivant la procédure d'appairage décrite sur le site de la zigate : https://zigate.fr/produits-legrand-compatibles-zigate/compatible/interrupteurfilaireconnectpourvoletroulant/

Je pense que ça doit fonctionner de la même manière que ce soit Céliane ou Dooxie et que ce soit filaire ou sans-fil.

Dans tous les cas, si ça peut vous permettre de mettre la doc (liste des compatibilités) à jour quand vous aurez le temps, je pense que ça renseignerait mieux les gens que "Shutter switch with neutral".

Merci encore pour votre travail ;)

**Comment by tcharp38** [comment]
J'ai mis à jour le modele de l'interrupteur filaire avec
- le nom du fabricant => Legrand
- le modele => 067726 

D'un point de vue Abeille, aucun lien avec "Dooxie".

L'inter fonctionne comme attendu ?

Quel est l'identifiant de modèle JSON donné par la page EQ/avancé ?
![image](https://user-images.githubusercontent.com/35221038/157292558-154e81dc-d848-499f-bb96-a97dce8e270b.png)

**Comment by xyko0** [comment]
Bonjour,

Désolé pour le temps de réponse...
L'identifiant modèle JSON est : Shutterswitchwithneutral
![image](https://user-images.githubusercontent.com/52315700/158346271-1380493c-d857-4f7c-82ce-042936908b4d.png)


L'inter fonctionne comme attendu je confirme 👍  
![image](https://user-images.githubusercontent.com/52315700/158346152-9e23ae70-851b-433b-9378-8a3a49cf33eb.png)

Si je parlais de Dooxie, c'est juste pour la doc afin que d'autres personnes qui seraient dans mon cas ne se posent pas la question. Et donc que Céliane ou Dooxie de chez Legrand, fonctionnent avec Abeille.

**Comment by tcharp38** [comment]
J'ai l 'impression que le terme "Dooxie" correspond juste à la finition.
Du coup je ne sais pas ou placer ce mot mais pas "fabricant" ni modele d'ailleurs.

Je clos.
A reouvrir si besoin.
