### ISSUE TITLE
Ampoule Tradfri GU10 340lm White, LED2005R5 (TRADFRIbulbGU10WS345lm, IKEAofSweden)

### ISSUE THREAD

**Issue by burzy76** [KiwiHC16/Abeille#2344]
Bonjour j’ai pu lire que l’intégration de cette ampoule d’IKEA a déjà été faite sur jeedom  avec le pluing abeille mais à ce jour j’ai  voulu l’intégrer à mon raspberry  pi 3 avec pizigate et pluing abeille mais il me la reconnaît pas et avec aucune commande 
Savez vous si il y a qqch à faire merci d’avance

**Comment by tcharp38** [comment]
Salut @burzy76 
Elle s'identifie probablement d'une autre maniere.
Quelle ampoule ? Quelle ref ? Quelle culot ? Ca manque de details.

En tout cas peux tu generer un discovery ? => https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by burzy76** [comment]
bonsoir oui c'est vrai que j'ai pas donner bcp de détail car je pensait que le sujet avait déjà été traiter il y a quelques mois mais en regardant un peu plus près l'autre ampoule tradfri est légèrement différentes donc voici le fichier en espérant que je l'ai bien réalisée    
![image_2022-03-04_190721](https://user-images.githubusercontent.com/99336018/156818069-fb26ebbf-f8d3-4a16-936d-869da2c28842.png)
puis le fichier discovery
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8187976/discovery.zip)

**Comment by burzy76** [comment]
Je vous donne les photos du packaging 
![image](https://user-images.githubusercontent.com/99336018/156819109-0404caa3-ee4f-4d17-a78e-1fbb97951051.jpg)
![image](https://user-images.githubusercontent.com/99336018/156819166-29b8b10d-8201-42f9-864c-782b0d6a81c5.jpg)
En espérant de vous aider au maximum bonne soirée

**Comment by tcharp38** [comment]
Je ne peux manque de pot rien faire avec ce discovery. Il est vide.
Merci d utiliser l'assistant pour en générer un.

**Comment by burzy76** [comment]
bonsoir, est ce parce que je l'ai mal fait le fichier discovery ? et sinon comment je peux faire pour en générer un car jamais fait cette procédure je suis tout nouveau dans ce domaine .
merci

**Comment by tcharp38** [comment]
J'ai décrit la procédure dans la doc que j'ai indiqué. Il faut avoir tous les boutons au vert.

**Comment by tcharp38** [comment]
@burzy76 
Alors tu t'en sors ? Tu patauges ?

**Comment by burzy76** [comment]
bonjour oui j'ai un peu patauger mais je sais pourquoi , j'ai essayer lumière éteinte et rien se passée, donc voila maintenant je t'envoie le fichier  merci d'avance pour le travail effectuer 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8213777/discovery.zip)

**Comment by tcharp38** [comment]
[TRADFRIbulbGU10WS345lm.zip](https://github.com/KiwiHC16/Abeille/files/8214135/TRADFRIbulbGU10WS345lm.zip)

A tester: decompresser dans core/config/devices

Je te laisse me trouver une image PNG sans arriere plan, pour mettre en icone

**Comment by burzy76** [comment]
aussitôt reçu ,aussitôt essayer et rien n'a changer , logiquement je suis en mode beta , j'ai télécharger le fichier et extrait a l'endroit indiquer puis j'ai exclue et supprimer l'ampoule pour l'inclure a nouveau , le plugin reconnait qqch mais rien comme commande même pas un on/off
je te mets une photo en png dit moi si cela te convient 
![tradfri led](https://user-images.githubusercontent.com/99336018/157435441-ed8a037a-8f1e-4512-a3e6-4f358c1b3c63.png)

**Comment by tcharp38** [comment]
Tu peux refaire une inclusion et me filer le package de logs ?
A l'avenir, pense à le mettre chaque fois histoire d'avoir une trace des evenements au moment opportun.

J'ai pris ton image. Merci

**Comment by burzy76** [comment]
donc je l'ai supprimer et refait une inclusion de l'ampoule et voici le fichier 
[AbeilleLogs-220309 .tar.gz](https://github.com/KiwiHC16/Abeille/files/8215659/AbeilleLogs-220309.tar.gz)

**Comment by tcharp38** [comment]
Inutile de supprimer l'equipement de Jeedom.

Quoi qu'il en soit il ne trouve pas le modele

> [2022-03-09 15:49:23]   EQ is UNsupported. 'defaultUnknown' config will be used

Donc soit il n'est pas dans core/config/devices
soit tu n'as pas redemarré Abeille apres l'avoir ajouté

**Comment by burzy76** [comment]
Ha ok mais justement j,ai chercher comment redémarrer abeille mais où cas ou que je me soit trompé quelle est la procédure pour redémarrer abeille 
Merci

**Comment by tcharp38** [comment]
page de config => demon => redemarrer

![image](https://user-images.githubusercontent.com/35221038/157670284-74ae5f7f-cf87-45d2-b90b-f7ac5d211ed9.png)

**Comment by burzy76** [comment]
impeccable cela fonctionne merci bcp de votre aide

**Comment by tcharp38** [comment]
Du coup on peut clore ce sujet ou il reste qqch en attente ?

**Comment by tcharp38** [comment]
Je clos le sujet en supposant que tout est bon.
Mais à réouvrir si besoin.
