### ISSUE TITLE
Ajout de fonctionnalités

### ISSUE THREAD

**Issue by apages2** [KiwiHC16/Abeille#2347]
Bonjour,

Il serait bien de pouvoir sélectionner le type d’équipement sans pour autant s'appuyer sur le mode auto lié à la ref et le constructeur renvoyer par l’équipement lors de l'inclusion. Par exemple un choix multiple de type select dans le menu avancé. par défaut le select sélectionné et les commandes créées sont ceux de la détection auto et ensuite, si on choisit un autre type d’équipement, on crée en plus les commandes liées a ce type d’équipement et qui n'existe pas dans les commandes du template par défaut. l'idée est de ne pas supprimer celles qui n'existent pas, cette possibilité doit être au choix de l'utilisateur

De même il serait intéressant de pouvoir rajouter manuellement des commandes a un équipement.

Je conçoit que ce point est plutôt lié a des utilisateurs avancés, mais en mode d’intégration de nouveau équipements, c'est plus simple je trouve.

De même, il serait intéressant de rajouter la fonctionnalité qui rend possible la navigation d'un équipement a un autre simplement en cliquant bouton droit sur la flèche de retour lorsqu'on est sur un équipement.

Merci

**Comment by tcharp38** [comment]
Salut @apages2 
Désolé, c'est bien trop vague tout ca.
Je ne comprends déja pas la premiere phrase. "Selectionner le type d'équipement sans pour autant s'appuyer sur le mode auto".
Je ne sais vraiment pas à quoi tu fais allusion.
 
Peux tu donner un exemple avec des snapshots ?
Et on va decouper ce sujet en autant de sujets differents sinon c'est ingérable.

**Comment by apages2** [comment]
Salut

Pour le premier sujet
![2022-03-08 12_24_52-Boxio - Jeedom](https://user-images.githubusercontent.com/12720395/157229273-a4a4574f-9dbb-40b9-b3f4-b2f0cd1158b3.jpg)

Pour l'ajout des commandes 
![2022-03-08 12_26_08-Boîte de réception - aurelien pages@orange com - Outlook](https://user-images.githubusercontent.com/12720395/157229415-938b155d-4986-4086-abab-106a906d7a71.jpg)

pour le dernier sujet :
![image](https://user-images.githubusercontent.com/12720395/157229580-508f26cf-bb4c-411e-94ea-5e7aee14a59d.png)

L'idée etait de lancer le sujet. Je peux regarder plus precisement le point 1 et 2 car j'utilise ce systeme sur mes plugins, donc potentiellement avec un peu de temps, je pourrais proposer un PR.

Pour le 3eme sujet, c'est une fonction native a jeedom (présente depuis la V4 je pense). Là aussi je pourrais regarder pour un PR

Bye

**Comment by apages2** [comment]
re,

laisse tomber le point2, je viens de decouvrir le mode developpeur

**Comment by tcharp38** [comment]
Point 1/
Je ne connais pas ce menu. 
Il n'est donc pas du plugin mais de Jeedom.
Comment tu y arrives par curiosité ?

Point 2/
Je suis personnellement contre ce menu que je n'utilise jamais. C'est une possibilité historique.
- Il est incomplet car ne permet pas de definir tous les parametres d'une commande
- Dangereux
- Le travail demandé pour mettre à jour ce GUI pour un truc dedié qq (2 ou 3) developpeurs ne vaut pas le coup.
Quel commande vois tu manquante pour en avoir besoin ?

Point 3/
Pourquoi pas.

**Comment by tcharp38** [comment]
@apages2 
Je clos ce sujet, pas pour dire non mais pour essayer de faire "du vide".

A recreer si besoin, sujet par sujet, aussi precis que possible.
Merci
