### ISSUE TITLE
Ampoule Lexman Gu10 460lm (ZBEK-4, Adeo)

### ISSUE THREAD

**Issue by burzy76** [KiwiHC16/Abeille#2348]
bonjour peut t'on inclure cet ampoule de Leroy merlin de marque Lexman ou Adeo ZBEK-4 en GU10  svp 
merci d'avance 
![Capture](https://user-images.githubusercontent.com/99336018/157423105-aa1014fd-e699-4a96-a89d-065f22f8d86e.JPG)
et voici le fichier 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8213807/discovery.zip)

**Comment by burzy76** [comment]
Je vous mets la photo
![image](https://user-images.githubusercontent.com/99336018/157423536-8cea28e6-197f-4bc3-a174-cdb3a7da44fd.jpg)

**Comment by tcharp38** [comment]
[ZBEK-4_Adeo.zip](https://github.com/KiwiHC16/Abeille/files/8214296/ZBEK-4_Adeo.zip)

A tester
La encore il me faut une image PNG du GU10, pas la boite, sans arriere plan.

**Comment by burzy76** [comment]
je t'envoie la photo en png
![lexman GU10](https://user-images.githubusercontent.com/99336018/157466804-55389e2d-5242-41f8-9ebd-c55832ea6c69.png)
,pareil que l'ampoule ikea je l'ai supprimer et refait une inclusion et voici le fichier
[AbeilleLogs-220309 .tar.gz](https://github.com/KiwiHC16/Abeille/files/8215699/AbeilleLogs-220309.tar.gz)

**Comment by tcharp38** [comment]
Meme problematique que ton ampoule Ikea.
Le modele que je t'ai donné n'est pas trouvé.

Il doit etre la
core/config/devices/ZBEK-4_Adeo/ZBEK-4_Adeo.json
le tout dans le plugin Abeille

**Comment by burzy76** [comment]
sinon je viens de voir que j'ai deux fois abeille dans réglage / system / éditeurs de fichier est ce normal ? 
c'est bien par ce chemin que tu va pour extraire les fichiers que tu donne .
![image_2022-03-10_135216](https://user-images.githubusercontent.com/99336018/157665588-e78e7567-78b9-4034-bf2b-99aa2c946c79.png)

**Comment by tcharp38** [comment]
Ha non ca n'est pas normal. 
Le "abeille" (a minuscule) n'est pas bon.
A supprimer

donc le chemin pour les devices est
html/plugins/Abeille/core/config/devices

**Comment by burzy76** [comment]
bon ayant eu une petite formation,  j'ai pu refaire ce que tu ma dit et c'est ok ampoule bien reconnu avec les commandes adéquats nikel merci a toi pour le travail fourni sauf en touchant au set level , l'intensité a bien diminuer mais impossible après d'avoir l'intensité maximal de la lampe donc je l'ai de nv inclus au pluing et son intensité est revenu donc pour l'instant je touche que au on/ off et encore merci pour ce que tu fait

**Comment by burzy76** [comment]
donc pareil que pour l'ampoule d'ikea j'ai repris a zéro et refait ce que tu ma dit et c'est ok ampoule reconnu avec les commandes adéquats comme celle d'ikea j'ai pas essayer de baisser l'intensité car eu un souci avec celle d'ikea donc je touche au on / off 
merci a toi et a ton acharnement

**Comment by tcharp38** [comment]
Tu fais un résumé des commandes qui ne fonctionnent pas ?

**Comment by tcharp38** [comment]
Salut @burzy76 
Quel est le status de ce sujet ?

**Comment by burzy76** [comment]
Bonjour concernant ce sujet je pensais te l’avoir dit mais pour mon moi sa fonctionne bien depuis la mise en service et donc comme de faite le sujet peut-être  clos sauf si pour d’autre personne il y a un souci
Merci pour tout

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Tcharp38 ***@***.***>
Envoyé : Wednesday, April 27, 2022 11:39:03 PM
À : KiwiHC16/Abeille ***@***.***>
Cc : burzy76 ***@***.***>; Mention ***@***.***>
Objet : Re: [KiwiHC16/Abeille] Ampoule Lexman Gu10 460lm (ZBEK-4, Adeo) (Issue #2348)


Salut @burzy76<https://github.com/burzy76>
Quel est le status de ce sujet ?

**Comment by tcharp38** [comment]
Ok j'avais mal compris.
Je clos mais a réouvrir si souci avec cet équipement.
