### ISSUE TITLE
Alerte ! Démon arrété ou planté. (Re)démarrage nécessaire.

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2349]
Salut,
Ca fait 2 fois depuis la maj que j'ai ce message.
Beta : 2022-03-08 01:00:13

J'étais pas en log debug, je sais pas s'il serait préférable que je les laisse en débug constament ?

2022-03-09 18:10:0 - Abeille - Alerte ! Démon arrété ou planté. (Re)démarrage nécessaire.
[AbeilleLogs-220309.tar.gz](https://github.com/KiwiHC16/Abeille/files/8216735/AbeilleLogs-220309.tar.gz)
2

**Comment by Jake309** [comment]
Il  vient de nouveau de planter.
J'ai remarqué uen grosse latence entre le moment ou j'actionne un interrupteur, et l'allumage d'une lampe. Ou pareil, quand depuis mon interface web, j'allume une lampe, c'est ultra long. 
Si j'appuye plusieurs fois pour espérer en bon impatient que ca s'allume plus vite, j'ai le plantag
[AbeilleLogs-220309 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8216768/AbeilleLogs-220309.1.tar.gz)
e

**Comment by Jake309** [comment]
Petit feedback. 
Que ce soit, une commande d'interrupteur, un détecteur de mouvement, ou un actionnement via un design, la commande est super longue a passer. Les retour d'état aussi ne sont pas rapide. 
M'a fallu du temps pour comprendre que mon ampoule ZigBee ne s'allumait pas où s'éteignait pas a cause de mon détecteur de mouvement. Je pensais que c'était elle qui merdait

**Comment by tcharp38** [comment]
Salut @Jake309 
Je creuse ca mais je réalise que tu es sur une zigate v2.
Son comportement doit etre different des v1 sur lesquelles je bossse.

**Comment by tcharp38** [comment]
[AbeilleCmdQueue.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8218934/AbeilleCmdQueue.class.php.zip)
Si tu veux tester et me fournir les logs. Je vais tacher d etre reactif sur ce sujet.

**Comment by Jake309** [comment]
Ho punaise, j'ai pas vue ton message. j'ai vue le premier et comme j'ai pas ouvert le mail pour pa oublié, j'ai pas vue le second...
Désolé, le bébé est arrivé à la maison hier, c'est un peu plus compliqué à trouver du temps.
Ce pb m'impacte directement encore plus avec le V.I.P. , surtout pour les lumières de nuit en allumage auto.

**Comment by tcharp38** [comment]
Pas de soucis. A voir comment toi tu as du temps pour me faire des retours.
En attendant j'ai poussé une nouvelle beta (220310-BETA-2) juste à l instant (donc dispo demain) avec qq correctifs mais j'aurais besoin de tes logs pour suivre de + pres.

**Comment by Jake309** [comment]
Voila mes logs. T'inquiéte, on va débuguer ca. enfin, je suis dispo pour tester. 
Si ca peut t'aider. Par trop de nouveau. à certains moment, 1 lampe ou un retour d'état est plus réactif.
[AbeilleLogs-220310.tar.gz](https://github.com/KiwiHC16/Abeille/files/8225415/AbeilleLogs-220310.tar.gz)

**Comment by tcharp38** [comment]
Je te laisse basculer sur la beta demain, et me refaire un point avec le package de logs.

Au passage, je note que l'equipement 7837/Congelateur remonte parfois des infos un peu debiles

- Temp, MeasuredValue=D8F0 => -100C
- Humidity, MeasuredValue=FF9C => 654.36%

C est un capteur Xiaomi carré et je doute qu'il soit concu pour fonctionner à des températures aussi basses mais les valeurs ne riment à rien. Non ?

**Comment by Jake309** [comment]
Ca marche, pas de souci, je te fais ca =)
Oui, ils sont prévue jusque -25, il décroche vers -27 et part à -100. On a remarqué ca, mais globalement ca donner un aperçue.
Après, je t'avouerai que dans les congélo, c'est pas très utile contrairement au frigo.

**Comment by Jake309** [comment]
Salut @tcharp38,
Tes petites corrections ont eu un effet positif. à première vue tout semble etre de nouveau réactif.
J'ai testé à plusieurs reprises, l'allume ampoule et prises par détection de mouvement, les interrupteurs pour allumage de prose, globalement tout depuis mon design. 
Tout correspond à ce que je vivais à l'époque.
Je te mets quand meme mes logs pour que tu puisses voir. heure de la mise à jour : 2022-03-11 06:49:08
[AbeilleLogs-220311.tar.gz](https://github.com/KiwiHC16/Abeille/files/8232152/AbeilleLogs-220311.tar.gz)

**Comment by tcharp38** [comment]
Merci pour les logs. Ca vaut toujours le coup de jeter un oeil.
Ceci dit pour le coup je ne vois rien d'anormal ou qui me pousse vers une amélioration quelconque.

Je te laisse verifier tout ça pendant qq jours et clore le point si ca fonctionne comme tu le souhaites.

**Comment by Jake309** [comment]
Salut. 
Tout semble repartie comme en 40. 
Je clôture. 
Si tu avais identifié des soucis sur le dev, c'est top. Sinon, encore un mystère ^^
J'y ai gagné en temps de réponse par rapport à avant l'ouverture de l'issue, donc pas totalement inutile :)

**Comment by tcharp38** [comment]
Oui j'ai trouvé 1 ou 2 bugs mais surtout un peu d' optimisation pour + d'efficacité.
Ta machine sur laquelle tourne Abeille est tres reactive.

**Comment by Jake309** [comment]
Oui j'ai un i5 8Go juste pour jeedom. Sans swap, c'est top.
En tout cas, j'ai du mieux, les retour des prises tradfri quand on les allume ou les éteint sont bien plus rapide, voir instantané qu'il n'a jamais été :)

**Comment by tcharp38** [comment]
Les optimisations paient.
