### ISSUE TITLE
Page avancé: Absence de modèle JSON

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#2353]
J'ai remarqué, et ce n'est pas récent, que certains équipements n'ont plus l'information du template  qui a servi à les créer.

Ce n'est pas bloquant, tout fonctionne bien mais je m'en suis aperçu il y a quelques mois en faire une reconfiguration d'un équipement (ampoule IKEA laquelle le retour d'informaion sur la température de couleur ne fonctionnait plus  #1063 )

Ce n'est pas le template qui est en cause, puisqu'à l'époque j'avais 2 ampoules IKEA identiques et une des deux avait bien l'information du template et pas l'autre. A l'époque j'ai refait l'inclusion de l'ampoule en galérant un peu.

Aujourd'hui, en faisant un tour sur la page avancé des équipements, je m'aperçois que beaucoup ( mais pas tous) n'ont plus non plus cette information. 
Ci-dessous des exemples d'équipements semblables( 2 Xiaomi rond et 2  Xiaomi carré) dont l'un a perdu l'info et l'autre pas.
![Xiami rond_avec](https://user-images.githubusercontent.com/56954282/157917028-52d9a827-f535-4ca2-bc16-521117db839d.JPG)
![Xaiomirond_sans](https://user-images.githubusercontent.com/56954282/157917033-432d4a75-9877-4b68-8625-39c266914c6b.JPG)

![Xiaomicarre_avec](https://user-images.githubusercontent.com/56954282/157917093-7977033f-f4a0-44db-a792-8f7ebffd0e4d.JPG)
![Xiaomicarre_sans](https://user-images.githubusercontent.com/56954282/157917095-2079fb72-a7c5-44c1-aee5-1c5e16fe6366.JPG)

**Comment by tcharp38** [comment]
Le sujet est à revoir.
L'identifiant zigbee est une info que j'ai ajouté très récemment. Donc seuls les devices inclus depuis ont cette info.

L aspect template est à clarifier. Tu as des exemples avec snapshot ?

**Comment by Krankhore** [comment]
Je me suis mal exprimé, , je parle du modèle json. Sur les copie d'écran, tu peux voir weather et sensor_ht . 
Les deux autres devraient aussi avoir respectivement sensor_ht et weather

**Comment by tcharp38** [comment]
Ha oui, bonne remarque.
Ces 2 la ont ete reinclus recemment ou au contraire sont de vieux equipements ?

Mais effectivement la DB ne contient pas ces infos, ni la signature zigbee, pour ces 2 la.

**Comment by Krankhore** [comment]
Ce sont de vieux équipements , inclus il y a plus de 2ans et en même temps. Les 2 modèles carrés quelques mois plus tard et en même temps aussi.

J'ai eu la même chose sur 2 ampoules IKEA incluses il y longtemps et en même temps. L'une avait perdu le modèle et l'autre pas. J'ai supprimé et réinclus l'ampoule défaillante il y a quelques mois (faire un reset d'une ampoule IKEA c'est casse pied). Depuis son modèle est resté en place.

**Comment by tcharp38** [comment]
Une idée de quand ca s'est produit ? Ou suite à quoi ?
La je n'ai aucune piste. D'autant que tu es le premier à remonter ça.
A noter que meme l'affichage du modele n'est present que depuis qq releases.

**Comment by Krankhore** [comment]
Non, aucune idée de quant cela date. Cela peut être très vieux
Pour l'ampoule , je l'ai remarqué l'automne dernier.
Mais pour les capteurs de température, je viens seulement de le remarqué.

Ceci dit, cela ne gêne aucunement le fonctionnement. Je l'ai juste remarqué lorsque j'ai voulu faire un reconfigurer sur la page avancé de mon ampoule IKEA.

Je comprends bien que sans logs, sans information temporelle , il n'y a peu de chance de trouver une origine.
A voir si tu as aussi certains équipements dans ce cas ou si d'autres en ont et quel pourrait être le moyen de ressaisir cette info.

Mais rien ne presse puisque par ailleurs tout fonctionne de façon nominale.

Je viens de vérifier sur mon environnement de test que je fais tourner de temps en temps (pour tester les nouvelles versions de plugins ou de core de jeedom)  et que j'ai monté depuis une sauvegarde il y a plus d'un an, la situation des équipements est la même.
Cette situation date donc vraisemblablement de plus ans.

Donc si personne ne se manifeste, il faudra conclure qu'un incident s'est produit un jour chez moi et clôturer l'issue.

**Comment by tcharp38** [comment]
Ok donc plutot que "disparu" je soupconne que le modele n'a jamais été enregistré dans la DB. Surement un bug de l'epoque.

Une reinclusion devrait corriger le pb.

**Comment by Krankhore** [comment]
J'en essayé une ré-inclusion d'un capteur.
Abeille voit bien l'annonce (13h59) , l'adresse à changé , l'ancien équipement est mis à jour mais le modèle ne s'enregistre pas.
[AbeilleParser(4).log](https://github.com/KiwiHC16/Abeille/files/8237642/AbeilleParser.4.log)
![Chambre](https://user-images.githubusercontent.com/56954282/158019160-a1f1bacf-1d3e-4c7f-afab-a172b5024f99.JPG)

Je suppose que je pourrais d'abord supprimer de jeedom mais dans ce cas toutes les id de commandes vont changer et il mettra à jour tout ce qui utilise cet équipement.

**Comment by tcharp38** [comment]
Intéressant. Je ragarde ça ce we.

**Comment by tcharp38** [comment]
Je n'ai pas le bon log (Abeille au lieu d'AbeilleParser), mais je soupconne que rien n'est fait car le device est deja connu et actif.
Au lieu de l'effacer tu peux le desactiver et le reinclure pour confirmer cette hypothese.

Mais il faut que je retravaille la dessus.

**Comment by Krankhore** [comment]
Effectivement, ça marche
j'ai désactivé le capteur Xiaomi , mis la zigate en inclusion et resté 7secondes sur le bouton du capteur.
Le capteur s'est ré-annoncé , Abeille a mis à jour.
Le modèle JSON est bien présent cette fois.
[AbeilleLogs-220312.tar.gz](https://github.com/KiwiHC16/Abeille/files/8238574/AbeilleLogs-220312.tar.gz)
![Chambre1](https://user-images.githubusercontent.com/56954282/158037003-be9016b0-0083-421c-80ba-94d4fba9b293.JPG)

il a recrée une des commandes puisque le modèle a du changer ( Humidite est devenu Humidity)

**Comment by tcharp38** [comment]
Beta 220316-BETA-1 dispo des demain (17/3) sur le market. Contient toutes les modifs jusqu'a cette heure.

**Comment by Krankhore** [comment]
J'ai installé la beta.
Je te confirme que maintenant , l'équipement se met à jour lors d'une ré-annonce même s'il est activé. Plus besoin de de le déactivé pour que le modèle JSON soit mis à jour.
J'ai fait l'essai avec un capteur de température, mis la zigate en inclusion et appui 7 secondes sur le bouton pour provoquer une nouvelle annonce.

**Comment by tcharp38** [comment]
Parfait. 
Je clos alors.
Merci pour ton retour.
