### ISSUE TITLE
Multiprise Lidl HG6338-FR 02/2022

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2354]
bonjour, 
il semble y avoir besoin d'une nouvelle intégration pour le modèle  HG6338-FR de lidl de Février 2022, il est reconnu par le plugin comme Silvercrest powerstrip USB SPSZ 3 A1, et l'image est conforme à la multiprise (Identifiant modèle JSONTS011F__TZ3000_vzopcetz Source: Abeille)
mais les endpoint ne sont pas corrects et la multiprise ne répond qu'a un OFF ou On complet sur toutes les commandes: un toggle en fait, même si les 3 endpoint apparaissent.

avez vous une solution? merci.
(pour memoire [LIDL Multiprise USB HG06338-FR · Issue #1848 - GitHub](https://github.com/KiwiHC16/Abeille/issues/1848)

**Comment by k1n0th0r** [comment]
Bonjour a tous 
JE débute, mais si je peux aider ou m'orienter pour mieux vous aider avec plaisir.
Je rencontre le meme comprtement que VVorttexx.
Appareil bien reconnu en HG06338
association effectuée multiprise éteinte avec reset au préalable (info depuis zigbee2mqtt.io/device)
mais L1,L2,L3 s'allument en meme temps si j'appuie sur une commande 

Je vais passer en Beta voir si j'ai du mieux
Je reste a votre ecoute

Merci d'avance

edit:
Apres upgrade de Zigbee2mqtt dev-branch fonctionne parfaitement

**Comment by tcharp38** [comment]
L un de vous 2 peut me faire un discovery ?
Voir la: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee

**Comment by VVorttexx** [comment]
avec plaisir et célérité
[discovery_HG6338-Fr_022022.zip](https://github.com/KiwiHC16/Abeille/files/8242678/discovery_HG6338-Fr_022022.zip)

**Comment by tcharp38** [comment]
ok merci.
Pour clarifier la situation on va se focaliser sur une point particulier; par ex l'appui sur ON allume tout et OFF eteint tout au lieu de la ligne L1 seulement ? C'est bien ca ?

J'ai besoin d'un package de logs suite à cette action, avec l'heure de l action et ladresse du device.
Merci

**Comment by VVorttexx** [comment]
bon alors je tombe de la chaise, mais j'ai une multi qui marche...la seule qui soit branchée depuis le début:
mise a jour OTA automatique? je n'ai rien fait de mon coté.

Adresse (courte/IEEE)7E0D / 0C4314FFFEF63AB5  11h47
celle là coupe et allume chaque prise différentié
par contre l'autre (intégré depuis l'achat, mais éteinte) ne fonctionne pas correctement:
Adresse (courte/IEEE)6251 / 0C4314FFFEF63C6E  11h49
appui  de off1 coupure total
appui de ON2 allumage total
[AbeilleLogs-220314.tar.gz](https://github.com/KiwiHC16/Abeille/files/8244094/AbeilleLogs-220314.tar.gz)

**Comment by tcharp38** [comment]
Tes logs sont inutilisables (vides). Tu n'es pas en mode debug.
Donc a modifier et redemarrer Abeille.
Et manip a refaire.

Maintenant 2 modeles qui se comportent differement, ca sent le FW different ca :(

Es tu sur la beta ? Si non, je te suggere de basculer dessus histoire d etre au gout du jour des dernieres evolutions et corrections.

**Comment by VVorttexx** [comment]
oups :
je suis déjà en bêta, les 2 modèles ne fonctionnaient pas à l'achat  initialement. 
12h21 Adresse (courte/IEEE)6251 / 0C4314FFFEF63C6E 
appui  de off1 coupure total
appui de ON2 allumage total
12h22 Adresse (courte/IEEE)7E0D / 0C4314FFFEF63AB5 
on ok
off1 ok 
[AbeilleLogs-220314 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8244293/AbeilleLogs-220314.1.tar.gz)
j'espère que c'est mieux

**Comment by VVorttexx** [comment]
bon désolé , en faisant 3 ou 4 fois l'assistant découverte de l'équipement, la prise se met a fonctionner totalement..., j'en ai une troisième dans son emballage je vais tester mais il semble bien qu'il faille forcer plusieurs fois la découverte pour que l'équipement réponde correctement. 
merci Tcharp38.
k1n0th0r est ce que cela fonctionne pour toi?

**Comment by tcharp38** [comment]
File moi un package de logs suite à l inclusion que je jette un oeil mais... mode debug avant :)

**Comment by k1n0th0r** [comment]
Hello

Avant maj rien ne fonctionnait normalement.
Exactement comme toi.
Je tourne sous Homeassistant (vm) avec un serveur dédié mqtt sur une autre
machine (pi3)
Et depuis plus de soucis les commandes sont cohérente , mais j'ai effectué
une modif .
Peut-être suffit il d'être patient ?
Et je n'ai pas eu le reflex de prendre la version qui était là lors de
l'anomalie.
😕

**Comment by tcharp38** [comment]
Au final y  a t il encore un pb ?
Je ne vois rien de particulier dans les logs, en dehors d erreur liées a une vieille version.

**Comment by VVorttexx** [comment]
Bonjour désolé du retard de réponse, 
je n'ai plus de problème avec les 2 multi utilisé, (je n'ai pas retrouvé la dernière partie chez quelqu'un qui doit la ramener...un jours ) 
donc non plus de problème cela fonctionne bien, merci encore de ton temps.

**Comment by tcharp38** [comment]
Ok.
J'avoue ne pas savoir si il y a un pb potentiel qq part ou pas mais sans + de details, le clos.
A reouvrir si besoin
