### ISSUE TITLE
Ampoule LivarnoLux (Lidl) led gu10 HG08131A (TS0505B, _TZ3000_quqaeew6)

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2356]
pourriez vous intégrer cette ampoule Lidl ,  elle ressort en:
Identifiant Zigbee (modelId, manufId)TS0505B, _TZ3000_quqaeew6
Identifiant modèle JSONdefaultUnknown Source: Abeille
[discovery_livarno_lux_led_gu10 HG08131A.zip](https://github.com/KiwiHC16/Abeille/files/8309766/discovery_livarno_lux_led_gu10.HG08131A.zip)

merci.
j'ajoute le PNG 
![livarno_lux_led_gu10 HG08131A](https://user-images.githubusercontent.com/47332515/159132466-d2dbab83-9ccb-4477-bb6e-7daeeecf0439.png)

**Comment by tcharp38** [comment]
Salut @VVorttexx

[TS0505B__TZ3000_quqaeew6.zip](https://github.com/KiwiHC16/Abeille/files/8311799/TS0505B__TZ3000_quqaeew6.zip)
A decompresser dans core/config/devices
puis redemarrer Abeille
refaire inclusion 

et faire le point

**Comment by VVorttexx** [comment]
Hello ,
beau boulot, j'ai intégré la config, redémarrage du demon,  supprimé les devises après quelques essais cela a fonctionné,   je n'ai pas essayé toutes les commandes mais principales ON/OFF/BLUE/RED/GREEN/WHITE fonctionnent. 
L'icone apparait comme lexman GUI10 Bulb, mais pas un souci.
Merci Beaucoup Tcharp38.

**Comment by tcharp38** [comment]
Je viens de pousser une beta qui contient toutes les dernieres modifs.
Si tu peux tout tester et confirmer que c est ok, on peut clore ce point.

Pour le nom de l'icone ca n'est pas fiable donc ne pas s y fier. Le titre associé à l icone est tiré du modele qui l utilise.

**Comment by VVorttexx** [comment]
Hello, 
j'ai du revenir sur une stable avant de repasser en beta j'avais perdu la zigate, mais toutes les devices sont revenues en ligne. 
Test Ok pour moi sur toutes les commandes. 
mais il semble manquer une option température:  la led blanche ne s'allume pas, pour le blanc, je passe par la commande white qui fait une couleur blanche avec les leds de couleurs. si tu vois ce que je veux dire.
(détail aussi dans le json : "manufacturer": "LavarnoLux",)
merci

**Comment by tcharp38** [comment]
Salut
Pas de pistes sur ta "perte de zigate" car aucune info.

Tu me donnes un snapshot du dashboard pour cet equipement ?

**Comment by VVorttexx** [comment]
salut, voici
![image](https://user-images.githubusercontent.com/47332515/159555774-122abed7-bf96-49da-8642-9858d556d4e7.png)
j'ai tout coché dans le doute.
je te mets aussi pour comparaison une ampoule à viser de même marque:
![image](https://user-images.githubusercontent.com/47332515/159556384-d93aa80a-5ae0-434d-8906-43f1247efc29.png)
TS0505B__TZ3000_qd7hej8u Source: Abeille
qui a bien le set-température, et passe bien en blanc sur une seul led, avec ce curseur alors quelle passe en blanc "3 couleurs" si je fais un set white.
merci.

**Comment by VVorttexx** [comment]
bonjour, je n'ai pas trouvé le moyen d'allumer la led blanche principale, elle s'allume lors d'une ré initialisation de l'ampoule, mais n'ai plus sollicité ensuite, quelque soit la commande utilisé. 
As tu eu le temps de regarder de ton coté? 
Merci.

**Comment by tcharp38** [comment]
Salut @VVorttexx 

En supposant que tu es toujours sur la beta, et donc sur la derniere du jour, peux tu ecraser le modele par celui ci
[TS0505B__TZ3000_quqaeew6.zip](https://github.com/KiwiHC16/Abeille/files/8381664/TS0505B__TZ3000_quqaeew6.zip)

puis faire un "reinitialiser" via la page EQ/avancé.

Je veux bien un snapshot du dashboard mais n'affiche pas tout. Aucun interet. Je veux juste voir ce qui est rendu visible par defaut à l'utilisateur.
J'ai ajouté 2 boutons "warm" & "white" en supposant que ca a le meme effet que sur mon ampoule.
Merci

**Comment by VVorttexx** [comment]
Salut, 
j'ai donc mise a jour la Beta du 30-03-2022 01:00:15 (tu devrais dormir un peu si c'est toi qui l'a poussée :-) )
et écrasé le json par le nouveau
![image](https://user-images.githubusercontent.com/47332515/160886690-bce741a8-349e-4e4c-8acb-af7381fe2497.png)
A gauche le réinitialisé et a droite pas encore.
le cool/warm white allume bien la led blanche principale, le white fait un mixte des leds de couleurs.
C'est nickel pour moi . 
merci @tcharp38

**Comment by tcharp38** [comment]
Tu vois une diff warm et cold ?
D'ailleurs ton ampoule est bien couleur +warm+cold ou seulement deux des trois ?

**Comment by VVorttexx** [comment]
oui cool est très blanc alors que warm est orangé, il doit y avoir un potentiel entre les 2 genre set-white  possible. 
l'ampoule est bien couleur +warm+cold

![20220330_211517](https://user-images.githubusercontent.com/47332515/160914047-32c8c52a-ebda-488d-bb0c-a832698ae870.jpg)
de gauche à droite white, cool white et warm white
et dans le mêmes sens:
![20220330_211618](https://user-images.githubusercontent.com/47332515/160914388-249fe3ff-cd6f-432f-9b2f-29e62f3fc5fe.jpg)
![20220330_211624](https://user-images.githubusercontent.com/47332515/160914420-6d423bcb-cdb4-4631-819d-f00d2c4854a9.jpg)
![20220330_211630](https://user-images.githubusercontent.com/47332515/160914461-3cef1901-daf2-48d1-8eb6-a97aefa57bc6.jpg)
on voit que white allume les led périphériques alors que cool white allume la led centrale.

**Comment by tcharp38** [comment]
Oui normalement ce sont 3 series de leds differentes
- des leds couleurs
- des leds blanc froid
- des leds blanc chaud

Bref tu as l'air de dire que tout roule et donc qu'on peut clore ce sujet ?

**Comment by VVorttexx** [comment]
Bonjour, 
C'est ok pour moi on peut clore. merci encore.
