### ISSUE TITLE
Prise Ikea non détecté 

### ISSUE THREAD

**Issue by nawak86** [KiwiHC16/Abeille#2358]
Bonsoir,

Je suis sous Abeille + Zigate v2 j’ai tout mes équipements en aqara qui fonctionnent correctement mais impossible de faire détecter une prise ikea.
Je mets bien la zigate en inclusion je reste 10s sur le bouton de la prise avec un trombone j’entends bien le clac de la prise mais rien n’apparait sur Abeille.

Auriez-vous une idée ?

Version Jeedom : 4.2.14
Abeille à jour version stable
Prise ikea : 19972 Type : E1702 Tradfri Control Outlet

![5afad777aae29f290f712fa9313757f32be9f976](https://user-images.githubusercontent.com/5274111/159573432-5c131ab2-2f99-4077-b6f0-0147ebe11516.jpeg)

![fc1eb497f49336debcc48ce647bb48d275444e6b](https://user-images.githubusercontent.com/5274111/159573439-b2dc0f93-ac69-4927-82fd-7d9f1476d9fd.jpeg)

![39778d99a855860b579998edd7964bbca0bca551](https://user-images.githubusercontent.com/5274111/159573449-a62fc360-2e24-407e-b4b2-6138203b9aa9.jpeg)

`Informations clefs nécessaires au support.

Quand vous ouvrez une "issue" dans GitHub merci de copier/coller les 3 premiers chapitres ci dessous 
Pour l'intégration d'un équipement non encore supporté ajoutez le chapitre 4.

Version Abeille: 220223-STABLE-1

Kernel: ["Linux vm-jeedom-prod 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU\/Linux"]

Zigate 1: 0004-0321
Zigate 2: 0005-0321

Table du plugin
===============
{
    "233": {"type":"plugin","name":"Abeille","logicalId":"Abeille","localVersion":"2022-02-24 01:00:17","remoteVersion":"2022-02-24 01:00:17","source":"market","status":"ok","configuration":"{\"version\":\"stable\",\"market\":1,\"third_plugin\":1,\"doNotUpdate\":\"0\"}","updateDate":"2022-02-24 01:39:12"},
}`

`[2022-03-20 16:50:01][DEBUG] : deamon_info(): {« state »:« ok »,« launchable »:« ok »,« launchable_message »:""}
[2022-03-20 16:50:01][DEBUG] : deamon_info(): {« state »:« ok »,« launchable »:« ok »,« launchable_message »:""}
[2022-03-20 16:50:02][DEBUG] : checkAllDaemons() => ok
[2022-03-20 16:50:02][DEBUG] : cron(): Daemons: 32733/SerialRead1, 32740/SerialRead2, 32745/Parser, 32747/Cmd, 32754/Monitor
[2022-03-20 16:50:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille1/0000/getZgVersion&time=1647791422 »,« payload »:""} › vers queue 1212
[2022-03-20 16:50:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille2/0000/getZgVersion&time=1647791422 »,« payload »:""} › vers queue 1212
[2022-03-20 16:50:03][DEBUG] : deamon_info(): {« state »:« ok »,« launchable »:« ok »,« launchable_message »:""}
[2022-03-20 16:50:23][DEBUG] : msgFromParser(): Abeille1, Zigate version 0004-0321
[2022-03-20 16:50:23][DEBUG] : msgFromParser(): Abeille2, Zigate version 0005-0321
[2022-03-20 16:50:33][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/E981/01 ›: Attr=‹ 0400-01-0000 ›, Val=‹ 32 ›
[2022-03-20 16:50:33][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/E981/01 ›: Attr=‹ 0406-01-0000 ›, Val=‹ 01 ›
[2022-03-20 16:50:56][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/FBBA/01 ›: Attr=‹ 0006-01-0000 ›, Val=‹ 1 ›
[2022-03-20 16:51:02][DEBUG] : deamon_info(): {« state »:« ok »,« launchable »:« ok »,« launchable_message »:""}
[2022-03-20 16:51:02][DEBUG] : checkAllDaemons() => ok
[2022-03-20 16:51:02][DEBUG] : cron(): Daemons: 32733/SerialRead1, 32740/SerialRead2, 32745/Parser, 32747/Cmd, 32754/Monitor
[2022-03-20 16:51:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille1/0000/getZgVersion&time=1647791482 »,« payload »:""} › vers queue 1212
[2022-03-20 16:51:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille2/0000/getZgVersion&time=1647791482 »,« payload »:""} › vers queue 1212
[2022-03-20 16:51:05][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/FBBA/01 ›: Attr=‹ 0006-01-0000 ›, Val=‹ 0 ›
[2022-03-20 16:51:23][DEBUG] : msgFromParser(): Abeille1, Zigate version 0004-0321
[2022-03-20 16:51:23][DEBUG] : msgFromParser(): Abeille2, Zigate version 0005-0321
[2022-03-20 16:51:47][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/E981/01 ›: Attr=‹ 0400-01-0000 ›, Val=‹ 31 ›
[2022-03-20 16:51:47][DEBUG] : msgFromParser(): Attribute report from ‹ Abeille2/E981/01 ›: Attr=‹ 0406-01-0000 ›, Val=‹ 01 ›
[2022-03-20 16:52:01][DEBUG] : deamon_info(): {« state »:« ok »,« launchable »:« ok »,« launchable_message »:""}
[2022-03-20 16:52:02][DEBUG] : checkAllDaemons() => ok
[2022-03-20 16:52:02][DEBUG] : cron(): Daemons: 32733/SerialRead1, 32740/SerialRead2, 32745/Parser, 32747/Cmd, 32754/Monitor
[2022-03-20 16:52:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille1/0000/getZgVersion&time=1647791542 »,« payload »:""} › vers queue 1212
[2022-03-20 16:52:02][DEBUG] : publishMosquitto(): Envoyé ‹ {« topic »:« TempoCmdAbeille2/0000/getZgVersion&time=1647791542 »,« payload »:""} › vers queue 1212
[2022-03-20 16:52:15][DEBUG] : msgFromParser(): Abeille2, permit join, status=01
[2022-03-20 16:52:23][DEBUG] : msgFromParser(): Abeille1, Zigate version 0004-0321
[2022-03-20 16:52:23][DEBUG] : msgFromParser(): Abeille2, Zigate version 0005-0321`

merci pour votre aide

j'ai aussi essayé avec ma zigate v1

Bonne soirée

**Comment by tcharp38** [comment]
Salut @nawak86 
2 choses
- Vu que tu as une v1 et une v2, par hasard est ce que l'inclusion avec la v1 fonctionne ?
- Peux tu fournir le package de logs 1 min apres une tentative d'inclusion ? Un drag & drop ici, pas de copy/paste.

**Comment by nawak86** [comment]
Hello,

Non ça ne fonctionne pas j'ai déjà essayé avec les 2

je viens de te faire l'archive de log j'avoue c'est pratique ;)
[AbeilleLogs-220324.tar.gz](https://github.com/KiwiHC16/Abeille/files/8337268/AbeilleLogs-220324.tar.gz)

encore merci pour ta réponse

**Comment by tcharp38** [comment]
Malheureusement je ne vois pas le log AbeilleParser dans le package, et pas de "device announce".
Désolé, il va falloir recommencer.

**Comment by nawak86** [comment]
c'est mieux avec ça : ?
[AbeilleLogs-220325.tar.gz](https://github.com/KiwiHC16/Abeille/files/8346557/AbeilleLogs-220325.tar.gz)

merci :)

**Comment by tcharp38** [comment]
Bah non.. la prise ne s'annonce pas du tout.
Tu devrais trouver un "device announce" dans le log parser (ou parser-prev) et ca n'est pas le cas.

Je crois que qqn d'autre avait remonté ce genre de souci avec ce type de prise. 
similaire https://github.com/KiwiHC16/Abeille/issues/2244

**Comment by nawak86** [comment]
je viens de réessayer plusieurs fois prise collé à la zigate rien ne se passe. j'ai vu le topic que tu viens de me linker mais pour le coup j'ai jamais eu signe de vie de mes prises.

on est d'accord sur la procédure : 

> Mettre la Zigate en mode inclusion (Bouton Inclusion), la Led bleue de la Zigate doit clignoter…
Faire un reset de la prise en insérant un petit trombone dans le trou pres de la led de la prise. Attendre 5s, la prise doit apparaitre dans Jeedom.

peut être aussi un soucis depuis le dernier firmware de la zigate.

**Comment by tcharp38** [comment]
Tu sais quoi ? Je dois reinclure ma prise Ikea que j'ai perdu depuis l'upgrade du FW.
Je vais faire l'essai et on verra.
J'ai un zigate v1 USB.. donc une antiquité. Le tout premier modele en fait. Mais FW OPDM 3.21

**Comment by tcharp38** [comment]
Je confirme que c'est ok sur ma v1 usb 3.21 OPDM.
La prise s'est annoncée et Abeille à fait le reste. Elle est fonctionnelle.

Mode inclusion + reset > 5sec et elle s'est annoncée.

Bref pour moi pas de soucis du plugin. De + si elle n'apparait ni en v1 ni en v2.. alors je doute plutot de la prise que des clefs.

**Comment by nawak86** [comment]
Et bien tu as bien de la chance :D j'ai essayé ma zigate v1 aussi mais rien je viens de tester ma zigate v1 avec le logiciel de test voila ce que ca donne ne permit joint plus reset 5s : 
`Type: 0x8000 (Status)
  Length: 9
  Status: 0x00 (Success)
  SQN: 0xAA
  Message: 
Type: 0x8012 (Unrecognized)
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x8002 (Data Indication)
  Status: 0x00
  Profile ID: 0x0000 (Unknown)
  Cluster ID: 0x0013 (Unknown)
  Source EndPoint: 0x00
  Destination EndPoint: 0x00
  Source Address Mode: 0x02
  Source Address: Not Valid
  Destination Address Mode: 0x02
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x8701 (Route Discovery Confirm)
  SQN: 0x00
  Status: 0x00
  Network Status: 0x44
Type: 0x8012 (Unrecognized)
Type: 0x8011 (Unrecognized)
`
j'ai l'impression que ca communique on est d'accord ?

**Comment by nawak86** [comment]
Désolé c'était pas très lisible

Type: 0x8000 (Status)
  Length: 9
  Status: 0x00 (Success)
  SQN: 0xAA
  Message: 
Type: 0x8012 (Unrecognized)
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x8002 (Data Indication)
  Status: 0x00
  Profile ID: 0x0000 (Unknown)
  Cluster ID: 0x0013 (Unknown)
  Source EndPoint: 0x00
  Destination EndPoint: 0x00
  Source Address Mode: 0x02
  Source Address: Not Valid
  Destination Address Mode: 0x02
Type: 0x004D (End Device Announce)
  Short Address: 0xA1D8
  Extended Address: 0xB4E3F9FFFEFCAE94
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x8701 (Route Discovery Confirm)
  SQN: 0x00
  Status: 0x00
  Network Status: 0x44
Type: 0x8012 (Unrecognized)
Type: 0x8011 (Unrecognized)

**Comment by nawak86** [comment]
![image](https://user-images.githubusercontent.com/5274111/160209922-dd2f7323-741c-45c7-ad9f-871bdbe84add.png)
une fois ajouté avec le logiciel sur le pc je vois l'appareil je pense dans Réseau sur Abeille1 mais je ne sais pas comment le faire ajouter en équipement dans abeille :/

![image](https://user-images.githubusercontent.com/5274111/160210339-694c191f-c15c-48ed-95bb-fa8e0cfc08a1.png)

**Comment by tcharp38** [comment]
Ha elle est donc dans ton réseau mais l'inclusion ne s'est pas faite jusqu'au bout.
Tu as retenté combien de fois ?
La premiere fois j'ai eu ce phenomene.

**Comment by tcharp38** [comment]
@nawak86 
On en reparle quand tu aura basculé sur la 220329-BETA-1
J'ai amélioré le support des équipements fantomes (dans le reseau mais pas dans Jeedom).

**Comment by nawak86** [comment]
hello désolé les enfants sont malade j'ai un peu moins de temps, disons que l'équipement a rejoins ma zigate avec le logiciel de test sous windows pas via abeille/jeedom je vais faire la bascule en installant la beta pour voir et je te fais un retour ;)
merci en tout cas

**Comment by nawak86** [comment]
bon aucune détection avec la maj je suis sous proxmox avec une vm je me demande si je vais pas me faire un jeedom de test sur une machine physique avec la zigate v1

même en mode test avec le pc et la zigate je rajoute la prise et après elle finit par disparaitre quand je repasse sur abeille.

je comprends vraiment pas après c'est peut être une impression mais je trouve mon réseau moins performant depuis que je suis passé a la freebox pop peut être le wifi qui pose soucis. je vais essayé avec le wifi désactivé.

**Comment by tcharp38** [comment]
Tu as mis à jour la bêta ce matin ?
Si oui rafraîchi le réseau et regarde si la prise est dans le réseau.

**Comment by nawak86** [comment]
hello, je suis déjà plus en forme je viens de m'y remettre j'ai enlevé la zigate v1 et j'ai laissé la v2 j'ai tenté une inclusion sans trop y croire et j'ai un équipement inconnu :p 

![image](https://user-images.githubusercontent.com/5274111/161451175-faf4e4e1-dff5-4951-958d-d4c04b928bbe.png)

![image](https://user-images.githubusercontent.com/5274111/161451188-2d18eb6b-258e-48c7-9cc0-9726826a9517.png)

Que dois-je faire ? 

merci

+++

**Comment by nawak86** [comment]
c'était trop beau lol je suis passé en beta2 j'ai enlevé les prises et j'arrive plus a les voir même en unknow :/ ça va me rendre chèvre lol

**Comment by tcharp38** [comment]
Nouvel equipement inconnu avec la v2 ? Ca ressemble à ce sujet: https://github.com/KiwiHC16/Abeille/issues/2368

Peux tu me donner le package de logs si ca n est pas trop tard ?

**Comment by tcharp38** [comment]
Salut @nawak86 
Que fait on avec ce sujet ?

**Comment by nawak86** [comment]
salut désolé très peu de temps en se moment j'ai toujours le problème avec la dernière version d'abeille et j'ai toujours des périphériques inconnus qui se rajoutent tout seul.

tu penses que mon problème viens d'une modifications matériel apportée aux nouvelles prises ?

+++ merci

**Comment by tcharp38** [comment]
Salut

"périphériques inconnus qui se rajoutent tout seul." ca n'est pas le sujet initial mais un bug est confirmé en zigate v2/3.21
voir https://github.com/fairecasoimeme/ZiGatev2#version-322
Nouveau FW pas encore dispo a priori.

Quel est le status "Ikea non detecté" ?

**Comment by nawak86** [comment]
hello, je viens de ressayer les prises elles se sont bien incluse je ne sais pas si tu avais modifié quelque chose ;) mais merci
+++

**Comment by tcharp38** [comment]
Je clos le sujet alors.
Merci
