### ISSUE TITLE
MS01 reconnu comme TH01

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#2359]
Bonjour, 
depuis la dernière mise à jour, hasard ou non, un de mes trois capteurs IR SonOff est reconnu comme TH01 au lieu de MS01.
(je n'ai pas de TH01).

Identifiant Zigbee (modelId, manufId) 66666, eWeLink
Identifiant modèle JSON                      TH01 Source: Abeille

Pour les 2 autres: 
Identifiant Zigbee (modelId, manufId)   (vide)
Identifiant modèle JSON                        MS01 Source: Abeille

Pourquoi ne peut on toujours pas forcer un modèle dans jeedom?
C'est à dire avoir dans "Configuration" : Réinitialiser / Recharger / Reconfigurer / "Reconfiguration Manuelle"
En cliquant sur "Reconfiguration Manuelle" on pourrait choisir un modèle JSON de notre choix.

Pour info:  
- Réinitialiser / Recharger / Reconfigurer ne marche pas -> TH01
- réinclure ne marche pas -> TH01
- supprimer de jeedom et réinclure ne marche pas -> TH01

Solution (temporaire j'espère):
- Suppression des commandes de température et d'humidié.
- Ajout manuelle d'une commande "etat"
- Modification de l'icone (qui était passé au SNZ02 lors des tentatives de reconfguration)
-> Tout semble fonctionnel.

Est-il possible que ce soit un disfonctionnement du capteur? D'une nouvelle procédure d'inclusion?
Dois-je m'attendre a voir mes deux autres capteurs changer de type aussi?

Cordialement,

Kaléo.

**Comment by tcharp38** [comment]
Salut @kaleofr 
Si le device dit qu'il s'appelle "66666" alors il s'identifie comme un Sonoff SNZB-02
voir https://zigbee.blakadder.com/Sonoff_SNZB-02.html
Donc pour moi c'est pas du MS01 mais bel et bien TH01 ou 66666

Les 2 autres qui n'ont pas de signature Zigbee ont surement ete inclus il y a un moment. Je n'avais pas encore mis ce type d'info de coté pour affichage.

Le SNZB-03 quant a lui devrait dire "MS01"
https://zigbee.blakadder.com/Sonoff_SNZB-03.html

Bref.. je ne sais que dire la mais Abeille ne choisit le modele qu'en fonction de l'identification du device.

Donc en résumé... t'es en train de dire que ton SNZB-03 dit qu'il s'appelle "66666".
Si c'est bien cela, je ne comprends absoluement pas comment c 'est possible.

**Comment by kaleofr** [comment]
Bonjour @tcharp38 ,

Loin de moi l'envie de vous embêter pour rien et donc OUI, mon SNZB-03 dit qu'il s'appelle "66666".
Les trois avaient été installé en même temps.
Il me remonte 81% de batterie, et cette nuit il s'est encore réinitialisé en TH01 (Température et Humidité sont réapparus et etat a disparu). C'est problématique que ces changements arrivent tout seuls!

Je viens de le mettre à surveiller.

La valeur de batterie peut elle être érronée?

Kaléo.

**Comment by tcharp38** [comment]
@kaleofr 
Pas de soucis mais... si ton SNZB-03 s identifie comme un SNZB-02 on ne peut rien faire.
J'ai quand meme du mal à croire ça. Ca voudrait dire que le FW embarqué est celui du 02 et non pas 03.

Si il y a eu "reinitialisation", c'est qu'il s'est à nouveau annoncé. En général ca arrive lorsque la communication est perturbée ou mauvaise.

Peux tu
- prendre ton 03
- mode inclusion cote Abeille
- forcer le 03 a se reannoncer (Long press reset button for 5s until the LED indicator flashes three times)
- et 1min apres fournir le package de logs (mode debug bien sur)

**Comment by kaleofr** [comment]
Bonsoir,
nous avons donc fait des tests et comme je le disais, mon MS01 se présente comme un 66666. Mes deux autres MS01 se présentent bien comme des MS01.
-> plutôt incompréhensible.

Après tout, il reste fonctionnel si on rajoute la commande "etat" 0500-01-0000 donc, rien de grave si a l'avenir je ne perds plus la commande info.

Enfin, le TH01 dispose de l'"alternateIds": "66666" Sa dénomination normale étant... TH01.
Se pourrait-il que les TH01 qui se présentent en 66666 soient en fait dans le même cas que mon MS01? En mode perte d'identité :-p
Du coup 66666 ne voudrait pas dire que nous avons à faire à un TH01 mais à un SONOFF qui peut être un TH01 ou un MS01, ou.... autre allez savoir?

Quoi qu'il en soit, je suggère de garder la trace de ce fonctionnement étrange, mais l'issue peut-être close pour moi.

Merci de ton aide @tcharp38,

Kaléo.

**Comment by tcharp38** [comment]
Donc il n'y a rien à faire.

J'imagine qu'il fait partie des tous premiers MS01 mis sur le marché avec un firmware daubé. Les 2 autres doivent etre plus recents.

De meme le 66666 doit etre un identifiant des tous premiers SNSZB02.

Bref, heureusement qu'il s'agit d'équipements peu onéreux.

Je clos le sujet.
