### ISSUE TITLE
Récupérer le groupe utilisé par une télécommande Ikea

### ISSUE THREAD

**Issue by rkhadro** [KiwiHC16/Abeille#236]
Bonjour,

Je n'arrive pas à créer des groupes quelque soit le type d'ampoule gu10/E27
La commande ne passe pas dans le parser.

_### AbeilleMQTTCmd 2018-04-17 19:12:25[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/addGroup} => **address=68cc&DestinatioEndPoint=01&groupAddress=aaaa**
AbeilleMQTTCmd 2018-04-17 19:12:25[DEBUG]Type: CmdAbeille Address: Ruche avec Action: addGroup
AbeilleMQTTCmd 2018-04-17 19:12:25[DEBUG]6 arguments command
AbeilleMQTTCmd 2018-04-17 19:12:25[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-17 19:12:42[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/getGroupMembership} => address=68cc&DestinatioEndPoint=01
AbeilleMQTTCmd 2018-04-17 19:12:42[DEBUG]Type: CmdAbeille Address: Ruche avec Action: getGroupMembership
AbeilleMQTTCmd 2018-04-17 19:12:42[DEBUG]4 arguments command
AbeilleMQTTCmd 2018-04-17 19:12:42[DEBUG]begin processCmd function_

**Comment by rkhadro** [comment]
Bon pour les groupes, c'est bon.
Mais ma télécommande(ikea ronde 5 boutons) ne fonctionne pas.
J'ai suivi le 200_IKEA.asciidoc pour ajouter deux devices au groupe aaaa.
Ensuite dans les commandes de ma télécommande ikea j'ai remplacé addrGroup par mon groupe aaa.

Les commandes sur la fenêtre fonctionnent, mais pas la télécommande.

Faudrait-il associé la télécommande avec chaque device ?

Quand je fais un liste équipement, il est bien la et la fenêtre se rempli avec IEE et short.

![screenshot 2018-04-17 21 32 08](https://user-images.githubusercontent.com/38282423/38892178-ccbe7984-4286-11e8-9a84-821487aaea0b.png)

AbeilleParser 2018-04-17 21:26:20[DEBUG]Abeille i: 0; ID : 00; Short Addr : e8ee; IEEE Addr: 90fd9ffffe055371; Power Source (0:battery - 1:AC): 00; Link Quality: 119

Ah oui, le get battery ne renvoi rien.

AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]Msg Received: Topic: {CmdAbeille/e8ee/ReadAttributeRequest} => clusterId=0001&attributeId=0021
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]Type: CmdAbeille Address: e8ee avec Action: ReadAttributeRequest
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]data: 02e8ee0101000100000000010021
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]len data: 28
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]Dest:/dev/ttyUSB0 cmd:0100 len:000E datas:02e8ee0101000100000000010021
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]len data: 28
AbeilleMQTTCmd 2018-04-17 21:36:47[DEBUG]checksum computed: 42

AbeilleParser 2018-04-17 21:36:47[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 80

**Comment by rkhadro** [comment]
Bien reçu.

Merci pour l'explication. je vais voir comment faire pour utiliser La zigate en sniff.

**Comment by KiwiHC16** [comment]
Je change le titre du fait des derniers échanges

**Comment by rkhadro** [comment]
Bonsoir,

Cela me va comme titre

**Comment by rkhadro** [comment]
Bonsoir,

Comment faire pour la passer en sniffer.
Flasher le firmware sniff sur zigate - OK
Ensuite télécharger ubiqua analyser, mais quelque soit le type device choisi ubiqua n'arrive pas à initialiser le sniffer.

Une piste ?

Il faut 2 usb zigate, une en coordinateur et une en sniff, c'est bien ca ?
J'avais oublié ta butineuse, je regarde.

**Comment by KiwiHC16** [comment]
Oui il fait un coordinateur pour gérer le réseau et un sniffer. 
Ubiqua est la solution la plus facile. As tu une configuration comme celle ci ?
![capture d ecran 2018-04-29 a 10 23 29](https://user-images.githubusercontent.com/8549674/39404654-7ba1acc8-4b97-11e8-9abd-0eb92ac994b9.png)
J'avais galéré car il faut flow control à nono.
Butineuse demande de mettre les mains dans le cambouis, ce n'est pas encore une solution plug and play. La version de Jérôme est peut être plus accessible avec plus de doc. Les deux fonctionnent.

**Comment by KiwiHC16** [comment]
Reponse a cette"issue": https://github.com/KiwiHC16/Abeille/blob/master/Documentation/200_IKEA.asciidoc#telecommnande-ronde-5-boutons

Donc je clos le sujet.
