### ISSUE TITLE
Support LEGRAND double switch sans fil (077724/067774, Doublegangsremoteswitch_Legrand)

### ISSUE THREAD

**Issue by apages2** [KiwiHC16/Abeille#2360]
Bonjour,

Serait-il possible d’intégrer le support de l'inter double sans-fil Legrand by netatmo (ref 067774 ou 077724)

la decouverte ne marche pas sur cette inter. Je pense qu'il y a deux endpoint, puisque deux boutons et les meme cluster client/server que l'inter sans fil 067723 (cf deuxieme issue), mais sans certitude. Je pense que cette inter doit etre vu comme une telecommande

Merci pour la prise en compte
Cordialement

**Comment by tcharp38** [comment]
Dans la page EQ/avancé, n'as tu pas la possibilité de telecharger un discovery local ?

**Comment by apages2** [comment]
Au temps pour moi je connaissait pas je croyais que le local etait le meme que celui généré.

C'est quoi la différence entre les deux ?

Voici le fichier 
[067774 _discovery.zip](https://github.com/KiwiHC16/Abeille/files/8348253/067774._discovery.zip)

**Comment by tcharp38** [comment]
C est assez recent.
Si Abeille ne trouve pas de modele pour l'equipement, il essaie de l'interroger pour avoir un max d'infos et creer le modele.
C'est l'equivalent de l'assistant, pas aussi complet, mais fait automatiquement pendant la phase d'inclusion.

On essaie d'avancer sur le #2361 d'abord ?

**Comment by tcharp38** [comment]
Antique sujet sans vie.
Je ferme mais à réouvrir si besoin.
