### ISSUE TITLE
Support LEGRAND switch sans fil (067723, Remoteswitch_Legrand)

### ISSUE THREAD

**Issue by apages2** [KiwiHC16/Abeille#2361]
Bonjour,

Serait-il possible d’intégrer le support de l'inter sans-fil Legrand by netatmo (ref 067773)

 a priori, le template semble exister, mais il n'a pas l'air opérationnelle. Je pense qu'il faudrait le déclarer  en telecommande pour pouvoir faire un bind avec un autre produit legrand

ci-joint la decouverte
[067723_discovery.zip](https://github.com/KiwiHC16/Abeille/files/8345142/067723_discovery.zip)

Merci pour la prise en compte
Cordialement

**Comment by tcharp38** [comment]
Salut @apages2 
Je vois qu'il y a un modele existant déja.
Ca ressemble à quoi une fois l'inclusion faite ?
Rien ne fonctionne ?

**Comment by apages2** [comment]
salut @tcharp38 

En fait, les commandes classique marche (get-sw, sw, time, ieee, short-addr, link, online)

Mais pour le on/off, comme il faut que je le lie avec un autre module ca ne marche pas. J'ai essayé de faire des bind device ou bind group dans tous les sens, mais ca ne marche pas.

A moins que je m'y prenne mal.

j'ai essayé de bind mon inter sans fil a mon autre module sur le cluster 6, j'ai essayé de binder mon inter avec un group sur le cluster 6, et mis l'inter dans le meme group, mais rien y fait.

d'ailleur a quoi servent les commandes Bind-0001-ToZigate ou Bind-0006-ToZigate et SetReporting-0001-0021 ou SetReporting-0006-0021 sur tous les modules

enfin les commandes de batterie ne marche pas

Cordialement

**Comment by tcharp38** [comment]
Salut

Seules les commandes "visibles" à l'utilisateur m interessent. Ca donne la vision de ce qu'il peut faire avec.
Celles qui ne sont pas affichées sont soit optionnelles, soit utilisées pour configurer l'equipement.

Bind-0001-ToZigate par ex demande au device d'envoyer vers la zigate toute info du cluster 0001 (power).
SetReporting-0001-0021 quant à lui demande au device qu'il renvoi le % battery tous les X sec.
Ces 2 ne sont à utiliser qu'une fois à la config (pendant l inclusion) et ne servent plus apres.

Bref t'as l'air de me dire que ce device ne fonctionne pas du tout.

**Comment by apages2** [comment]
Salut,

**Bref t'as l'air de me dire que ce device ne fonctionne pas du tout.** => Oui

Je vais essayé d'adapter le template TRADFRIonoffswitch pour avoir la config telecommande.

L'inter sans fil est un ZED, je pense qu'il ne peut fonctionner que lorsqu'il est lié a un ZR

**Comment by tcharp38** [comment]
Dans la page EQ/avancé, quels sont les identifiants Zigbee et modele JSON donnés ?

**Comment by apages2** [comment]
L’identifiant zigbee est : Remoteswitch, Legrand
Modèle json : Remoteswitch Source: Officielle

**Comment by tcharp38** [comment]
Ok donc c est bien le bon modele.
Déja la batterie. Ce periph ne remonte pas le % mais seulement la tension.

[Remoteswitch.zip](https://github.com/KiwiHC16/Abeille/files/8353183/Remoteswitch.zip)

Tu peux ecraser le modele et refaire une inclusion avec ce nouveau.
Remontée de batterie toutes les H

Apres l'inclusion, peux tu faire un appui sur le bouton du haut, noter l'heure et me filer le package de logs.
Merci

**Comment by kaleofr** [comment]
Si vous parlez du modele Remoteswitch.json,  il est parfaitement fonctionnel pour moi depuis des mois (années ? ).
Pour la batterie effectivement je ne sais pas, mais pour les bouton ça marche.
Je confirme par contre que ça n'est pas évident,  il me semble qu'il fallait mettre l'interrupteur et la zigate sur un même groupe, ou quelque chose comme ça.

Par contre, par pitié, essayez de ne pas casser le json dans les prochaines maj.

Kaléo.

**Comment by apages2** [comment]
Salut kaleo 

C’est déjà une excellent nouvelle de savoir que quelqu’un utilise ce template ça permettra de pouvoir faire des tests 

Qu’elle commande utilises -tu?

Est-ce que les équipements que tu pilotes sont dans un groupe? Si oui comment as-tu fait pour mettre l’inter depart/arrive dans ce même groupe

Est-il possible de faire un screen shoot des commandes?

Merci

Envoyé de mon iPhone

**Comment by tcharp38** [comment]
Oui bonne nouvelle. Ca veut dire que le seul souci est la remontée du niveau de batterie.
Apres il faut trouver comment l'utiliser.

**Comment by apages2** [comment]
Hello,

Bon j'avance de mon coté

Le nouveau template que t'as envoyé ne remonte toujours pas la partie batterie.

Pour ce qui est du fonctionnement, y a un truc que je dois louper.

Si sur mon ZR, je renseigne un groupe (0001) et que je fait une add group dans la page principal, je vois que ce module a le groupe 0001 d'affecté.

Sur mon ZED, si je clique sur ON qui execute la commande : CmdAbeille/#addrGroup#/OnOffGroup, ca ne marche pas. Par contre, si je remplace la commande par CmdAbeille/0001/OnOffGroup ca marche.

Il y a donc un probleme sur l'affectation du groupe sur mon ZED. J'ai essayé de faire de meme avec le addgroup, set group et set group legrand (d'ailleur je sais pas ce que font ces deux dernières commandes), pas mieux. Comment associer un module ZED a un groupe?

D'ailleur, physiquement quand j'appuie sur mon ZED, il actionne pas le ZR. Il faut donc que j'arrive enregistré mon groupe dans la memoire physique du ZED.

Ensuite, vu que dans la conf par defaut de ce module, il y a enormement de commande, je sais pas si elles sont toutes necessaire, ca serait interressant de voir avec kaleo, les commandes qu'il utilise.

Bye

**Comment by apages2** [comment]
Re,

le probleme vient certainement du fait que l'inter sans fil n'a pas le cluster 0004 :
Input Cluster Count: 6
Cluster 0: Cluster ID: 0x0000 (General: Basic)
Cluster 1: Cluster ID: 0x0001 (General: Power Config)
Cluster 2: Cluster ID: 0x0003 (General: Identify)
Cluster 3: Cluster ID: 0x000F (General: Binary Input Basic)
Cluster 4: Cluster ID: 0x0020 (General: Poll Control)
Cluster 5: Cluster ID: 0xFC01 (Proprietaire)
Output Cluster Count: 6
Cluster 0: Cluster ID: 0x0000 (General: Basic)
Cluster 1: Cluster ID: 0x0003 (General: Identify)
Cluster 2: Cluster ID: 0x0006 (General: On/Off)
Cluster 3: Cluster ID: 0x0008 (General: Level Control)
Cluster 4: Cluster ID: 0x0019 (General: OTA)
Cluster 5: Cluster ID: 0xFC01 (Proprietaire)

**Comment by tcharp38** [comment]
@apages2 
Peux tu me filer un package de logs apres appui sur un des boutons ?

> Apres l'inclusion, peux tu faire un appui sur le bouton du haut, noter l'heure et me filer le package de logs.

**Comment by apages2** [comment]
voici

12h05 et environ 20s
 85B5 / 0004740000C36669 
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8355242/AbeilleCmd.log)
[AbeilleDebug.log](https://github.com/KiwiHC16/Abeille/files/8355243/AbeilleDebug.log)

**Comment by tcharp38** [comment]
Merci mais..
- quand je demande le package de logs c'est celui via la page support/telecharger tout. C'est + simple pour toi et plus complet pour moi. Et en l'occurence le log qui m interesse la (parser) n'est pas dispo.
- je note que tu es sur la stable. Ca t embete de migrer sur la beta ?

**Comment by apages2** [comment]
Pas de soucis pour migrer sur la beta

pour les logs, je prefere t'envoyer les fichiers que t'as besoin pour eviter de transmettre des données sensible accessible a tous (clé API, login/password du market lors de l'upgrade, etc...)

Je t'envoi ca quand c migré

**Comment by tcharp38** [comment]
Je viens de creer le sujet #2364
Tu peux m'aider à clarifier ce que tu vois comme info sensible a ne pas exporter ?

**Comment by apages2** [comment]
c'est transmis dans l'autre issue.

Peux-tu m'eclairer sur le fonctionnement de l'accès aux fonction zigbee depuis la page avancée, typiquement :ZCL: Ecriture attribut

Je doit m'y prendre comme un pied je pense, mais j'essai par exemple d'activer le mode identity sur un module sans fil.

![image](https://user-images.githubusercontent.com/12720395/160241498-90d1fbf1-a8a1-4b4f-9559-df06a5a2751b.png)

mais ca marche pas. D'ailleur j'ai pas compris la direction. Quand tu mets 00 c'est la zigate qui se comporte en client et qui envoi au serveur (module) ou l'inverse.

J'essai de parcourir la doc zigbee https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf qui est enorme mais bien complète pour essayer de comprendre ce que je fait

Aussi pour la partie batterie, ta commande à pour logicalID : 0001-01-0020
est-ce que c'est le plugin qui recupère ce logicalID pour envoyer une requete sur le cluster 1 attribut 0020?

Car si je fait un lecture attribut depuis la page avancé, sur l'EP01, le cluster 01 et l'attribut 20, j'obtient
![image](https://user-images.githubusercontent.com/12720395/160241890-68633cfc-e75a-4369-bf5a-9a263afc1d05.png)

donc l'interrogation en zigbee remonte bien la tension de la batterie

Bye

**Comment by apages2** [comment]
Bon je me repond pour la batterie ;-)

En faite, il faut rajouter une commande Get-batterie avec un topic readattribute (je suppose que le toipc fait appel a une fonction dans abeille ou alors peut importe le topic) et le paramètre ep=01&clustId=0001&attrId=0020, puis ensuite lancer la commande info 0001-01-0020 pour que la valeur s'affiche. Je suppose donc que tu stockes en base la valeur pour le cluster 0001, l'ep 01 et l'attribut 0020 et que la commande info recupère cette donnée en s'appuyant sur le logicalid pour retrouver la valeur.

Le problème doit donc provenir de l'histoire de Bind 0001-ToZigate et de SetReporting 0001-00020 qui paramètre pas la remonté de cette info dans le module lors de l'inclusion.

Bref je verifierais ce sujet quand on aura régler le problème du group car là j'ai des fichiers de template dans tous les sens en officielle, local, etc....

**Comment by apages2** [comment]
Voici les logs après installation de la beta

[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/8355545/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8355547/AbeilleCmd.log)
[AbeilleDebug.log](https://github.com/KiwiHC16/Abeille/files/8355548/AbeilleDebug.log)

Pour info, j'ai créé un autre issue sur un problème que j'avais deja constaté mais qui existe encore avec la beta et que je viens de me rappeler lors de la manip
#2365 

Cordialement

**Comment by kaleofr** [comment]
Bonjour Tout le monde,

> Salut kaleo C’est déjà une excellent nouvelle de savoir que quelqu’un utilise ce template ça permettra de pouvoir faire des tests Qu’elle commande utilises -tu? 
Click_Middle, qui renvoie 1 ou 0.

>Est-ce que les équipements que tu pilotes sont dans un groupe? 
Je ne pilote qu'un interrupteur filaire legrand en direct, il est dans un groupe indépendant de l'inter (avec toutes mes autres lumières)

Si oui comment as-tu fait pour mettre l’inter depart/arrive dans ce même groupe
Franchement je ne sais plus, il me semble d'après les docs qu'il fallait surtout mettre inter et ruche dans le même groupe.

Apparemment je ne reçois pas le niveau de batterie avec le modèle actuel.

Autre point, étant sur piles, il se réannonce souvent à l'utilisation... et je perd le time-out que j'ai configuré à 2 ou 3 jours. 
60 minutes pour un inter que j'utilise une ou deux fois pas jours, parfois 0, ce n'est pas adapté.

Kaléo

**Comment by tcharp38** [comment]
@kaleofr
Le timeout de 60 est calé sur le reporting de batterie qui doit etre "au pire" toutes les H.
Donc c'est la dessus qu'on doit bosser.

Mais je viens de realiser que ce device ne PEUT PAS faire du reporting de batterie. Il renvoi une erreur "NON REPORTABLE".
C'est dingue, car on ne peut pas interroger un equipement sur batterie vu qu'il ne repond que quand il veut.
Bref  pour la batterie il doit y avoir une autre solution ou un truc caché dans le cluster proprietaire Legrand.

Il faudrait savoir si il y a une mise à jour FW.

**Comment by tcharp38** [comment]
Antique sujet sans vie.
Je ferme mais à réouvrir si besoin.
