### ISSUE TITLE
Masquer certaines infos dans le package de logs

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2364]
Pour eviter de transmettre des infos perso.

**Comment by apages2** [comment]
J'ai pas tout analysé, mais par exemple, dans le fichier AbeilleKeyInfos.log, il y a la clé API (qui est crypté, mais qui n'a aucun interet dans le troubleshooting)

le fichier update, transmet aussi l'url qui a servit a faire l'update avec l'hwkey le login et password, la aussi crypté en SHA1, mais bon !!!

Bye

**Comment by tcharp38** [comment]
Dans keyinfos, ou est cette clef ? Je ne l'ai pas dans mes logs.

Ok pour le log "update" lui meme généré par Jeedom, je peux filtrer 'hwkey=', 'password=' avant package.

**Comment by apages2** [comment]
dans la table config, clé api

dans le fichier update, filtre aussi l'username

**Comment by tcharp38** [comment]
Voir 220329-BETA-1

- masquage clef api table config
- masquage URL log update

**Comment by tcharp38** [comment]
Exemple de filtrage sur 'update' => FILTERED à la place de l'url

> [2022-03-30 08:42:54][ALERT] : URL https:// FILTERED
> --2022-03-30 08:42:54--  https:// FILTERED

et sur "key infos"

>     "agressifTraitementAnnonce": {"plugin":"Abeille","value":"4"},
>     "api": FILTERED,
>     "blocageRecuperationEquipement": {"plugin":"Abeille","value":"Oui"},
> 

Je clos.
A reouvrir si besoin de filtrer autre chose.
