### ISSUE TITLE
Equipements selectionnés par erreur après suppression

### ISSUE THREAD

**Issue by apages2** [KiwiHC16/Abeille#2365]
Bonjour,

Je créé cette issue concernant un comportement bizzare que j'ai constaté.

Lorsque je selectionne un equipement et que je le supprime, celui-ci disparait bien, mais lorsque la page se rafrachie, j'ai d'autre modules qui sont selectionné.

Ce qui pose problème si je fait tout de suite une autre operation (group, suppression, etc) car ca s'applique au module coché, mais que je n'avait pas moi meme selectionné

Il est possible de regarder ce point?

Cordialement

**Comment by tcharp38** [comment]
Salut @apages2 
Je viens d 'essayer et je ne reproduis pas ce genre de soucis.
Tu supprimes comment l'equipement ? Via le bouton "supprimer de jeedom" (mon cas de test) ? Ou autrement ?
Ha si tu as des snapshots ca peut aider.

**Comment by tcharp38** [comment]
@apages2 
C 'est un souci que tu as toujours ?
Je ne reproduis pas et personne d'autre ne le remonte mais si c 'est un vrai pb ca bloque la stable.

**Comment by tcharp38** [comment]
Jamais reproduis ni remonté par ailleurs.
Je clos mais à reouvrir si nouvelles données.

**Comment by tcharp38** [comment]
Semble etre un vrai pb mais impossible de reproduire de mon coté.
Si qqn trouve une technique pour reproduire de maniere quasi systematique, je prends.

**Comment by tcharp38** [comment]
@eoeir
Quel est ton navigateur ?

**Comment by eoeir** [comment]
Désolé je n'avais pas vu ce message. C'est Firefox.

Il me semble que maintenant l'ensemble des équipements sont désélectionnés après exclusion, ce qui traite le pb.

**Comment by tcharp38** [comment]
Peut etre que le pb est partie suite à une mise à jour de Firefox.
Ou une mise à jour d'Abeille
mais comme je n'ai jamais pu reproduire.. rien n'est sur.

Je garde le sujet ouvert pour l instant.

**Comment by apages2** [comment]
Bonjour,

 

Je confirme, j’ai le problème

 

Cordialement

 

De : Tcharp38 ***@***.*** 
Envoyé : mercredi 6 avril 2022 15:19
À : KiwiHC16/Abeille ***@***.***>
Cc : apages2 ***@***.***>; Mention ***@***.***>
Objet : Re: [KiwiHC16/Abeille] Probleme sur equipements selectionné après suppression (Issue #2365)

 

@apages2 <https://github.com/apages2> 
C 'est un souci que tu as toujours ?
Je ne reproduis pas et personne d'autre ne le remonte mais si c 'est un vrai pb ca bloque la stable.

**Comment by tcharp38** [comment]
Salut @apages2 
Par hasard aurais tu une  procedure pour reproduire de maniere systematique ?

**Comment by tcharp38** [comment]
Pb jamais reproduit.
Je ferme.
A réouvrir si besoin
