### ISSUE TITLE
Apparition équipements inconnus depuis 220329-BETA-2

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2368]
Salut,

Depuis la dernière beta, j'ai des équipements qui apparaisse tout seul dans ma ruche avec aucune commande.
J'en ai supprimé 10 environs, mais ca revient tout le temps.
![image](https://user-images.githubusercontent.com/49479084/161102465-f1dfa355-5d85-4f88-82c2-1c2d7050bf90.png)
![image](https://user-images.githubusercontent.com/49479084/161102482-5ffbec66-5cfb-4057-a97c-66ff83363167.png)

[AbeilleLogs-220331.tar.gz](https://github.com/KiwiHC16/Abeille/files/8391270/AbeilleLogs-220331.tar.gz)

**Comment by Jake309** [comment]
depuis mon message de nouveaux equipements
[image](https://user-images.githubusercontent.com/49479084/161226415-f119d055-64d6-454d-8faf-5a3924bcb633.png)

**Comment by tcharp38** [comment]
Tu as regardé si c etait coherent avec de vrais equipements ?
Si tu vas sur page avancé de l'un d eux ca donne quelle signature ?

**Comment by Jake309** [comment]
Je sais pas si je regarde au bon endroit.
En adresse, aucun doublon et identifiant zigbee vide
![image](https://user-images.githubusercontent.com/49479084/161257435-ec313e05-c1e7-4781-92e3-1cdf0024c9b8.png)

**Comment by tcharp38** [comment]
Que donnes la page santé ?
Il faut en fait etre sur que l'adresse IEEE (ici 0400536d04015D8B) ne soit pas celle d'un autre equipement.

**Comment by Jake309** [comment]
J'avais compris comme ca, donc dans santé, quand je fais un recherche (ctrl+F), je n'ai que le "fantaome" en adresse IEEE pour chaque
![image](https://user-images.githubusercontent.com/49479084/161281617-3bdcf3f5-d79c-4b0a-9b26-b20c4642a697.png)

**Comment by Jake309** [comment]
Comme disait l'autre, dans le doute reboot.
Je relance jeedom au cas ou. Je donner des news dans quelques heures le temps de voir si de nouveau apparait. Je viens de supprimer une nouvelle fois

**Comment by tcharp38** [comment]
Pense a me filer un package de logs STP.

Mais donc pour toi tu n'as aucun device inconnu ?

**Comment by Jake309** [comment]
Je viens de tout sup pour faire un audit réseau, j'en ai un qui est revenu dans la foulée.
Si ca peut t'aider :
Ruche Abeille1-284 |   | Abeille1 | 1B96 | 0400536D04015D6B | Time-out | 2022-04-03 16:15:22 | 0 | ? | -

![image](https://user-images.githubusercontent.com/49479084/161432436-ae45e22f-e5a7-4dbc-acce-ea4b690b4d8c.png)

[AbeilleLogs-220403.tar.gz](https://github.com/KiwiHC16/Abeille/files/8404701/AbeilleLogs-220403.tar.gz)

**Comment by Jake309** [comment]
J'ai pas eu la notif mais de ton message, vraiment désolé :/

Et pour te répondre, non, aucun device innconnu, ca fait d'ailleur un moment que je n'ai pas fait de réintégration de nouveau

**Comment by tcharp38** [comment]
Concernant l'equipement que tu signales (ieee 0400536D04015D6B), je vois une veritable annonce de celui ci.
Donc il existe bel et bien

[2022-04-03 15:50:45] Abeille1, Type=004d/Device announce, Addr=1D86, ExtAddr=0400536D04015D6B, MACCapa=B4
[2022-04-03 15:52:54] Abeille1, Type=004d/Device announce, Addr=1D0A, ExtAddr=0400536D04015D6B, MACCapa=B4
[2022-04-03 16:15:22] Abeille1, Type=004d/Device announce, Addr=1E7E, ExtAddr=0400536D04015D6B, MACCapa=B4
[2022-04-03 16:17:50] Abeille1, Type=004d/Device announce, Addr=1B96, ExtAddr=0400536D04015D6B, MACCapa=24

Sauf qu'il ne donne aucune autre info.
Aucune idée de quel equipement ca peut etre ?
En tout cas ca fait du sens qu'il soit dans Abeille mais "non visible" pour l'instant car toujours inconnnu.

**Comment by Jake309** [comment]
Alors, qu'il y en ait 1 je veux bien, mais la depuis tout à l'heure, 6 autres sont apparus, ca fait beaucoup.
S'il ne sont pas connu dans abeille, c'est sur que je ne sais pas de ou ca vient. Car tout les modules que j'achète sans être sur qu'ils fonctionnent dans abeille, quand ils sont pas intégré, je fais la démarche pour qu'on le fasse.
Donc très hottemment, je ne vois absolument pas de ou ca peut venir.

D'ailleurs, regarde à quel point c'est étrange, ta 2eme ligne, avec ladresse 1D0A, dans mon screen, elle se retrouve avec un IEEE différent. la 2eme inconnu : 1D0A | 04015E2004015D6B
Je ne sais pas si c'est ilogique ou pas. pour moi, l'une est liée à l'autre et est donc unique

![image](https://user-images.githubusercontent.com/49479084/161438149-00f4650f-44a5-4b89-a030-316c7d22ad63.png)

[AbeilleLogs-220403.tar.gz](https://github.com/KiwiHC16/Abeille/files/8405024/AbeilleLogs-220403.tar.gz)

**Comment by tcharp38** [comment]
Je suis bien d'accord avec toi. Mais pour le coup Abeille n'est pas fautif.
Je trouvais les adresses IEEE etranges, et au final j'en arrive à la conclusion que la la zigate dit n'importe quoi.

Exemples
Un 8002 et le 004D qui suit sont issus du meme message zigbee.
Le 8002 dit que le message vient de 338E (donc "Contact sec") alors que le 004D lui "invente" des adresses.
Manque de pot Abeille utilise le 004D dans ce cas.

[2022-04-03 15:52:54] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:52:54]   Handled by decode004D
[2022-04-03 15:52:54] Abeille1, Type=004d/Device announce, Addr=1D0A, ExtAddr=0400536D04015D6B, MACCapa=B4

[2022-04-03 15:57:27] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:57:27]   Handled by decode004D
[2022-04-03 15:57:27] Abeille1, Type=004d/Device announce, Addr=8D00, ExtAddr=0000001E040048DC, MACCapa=02

[2022-04-03 15:59:28] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:59:28]   Handled by decode004D
[2022-04-03 15:59:28] Abeille1, Type=004d/Device announce, Addr=1C8E, ExtAddr=0400536D04015D6B, MACCapa=B4

En conclusion, soit ta Zigate est corrompue (désolé mais pour moi la v2 est moins mature que la v1),
soit il y a un bug restant.
Je vais creer un sujet chez Zigate mais clairement pas un bug Abeille à ce stade.

**Comment by Jake309** [comment]
Ca roule, je vais la débrancher et le rebrancher pour voir. meme si le reboot de la machine a rien changer l'autre jour.
On se tien au courant.
il m'arrive pas mal de thuile ^^ j'espère être un bon beta testeur :D

**Comment by tcharp38** [comment]
@Jake309 
Quand as tu fait la mise à jour du FW zigate ?
L'equipement qui semble à l 'origine des pbs semble etre Orvibo CM10ZW. Y a t 'il eu un changement pour lui ?
Bref on cherche a comprendre quel evenement a déclenché ce pb si tu vois qqch.

**Comment by Jake309** [comment]
Je l'ai acheté le 19/12, elle était au dernier firmware quand je l'ai recu (0005-0321) donc j'ai pas touché.

Le Orvibo a eu droit à un reboot électrique la semaine derniere car il ne répondait plus.
C'est vrai que ca pourrait correspondre en terme de période entre le reboot elec et l'apparition des device inconnus.

Je vais aller refaire un reboot elec pour voir, si pas de changement, je le remettrai en inclusion pour qu'il se mette à jour au niveau d'abeille. Si toujours rien, je vais tenter une exclusion inclusion.

Je te tien au courant. Je vais faire le reboot elec la dans 5min, et la suite en fonction dans la journée le temps de voir ce que ca donne entre 2

**Comment by tcharp38** [comment]
Ok merci.
Donc si changement, c'est juste au niveau Orvibo qui a subit un reboot.

Tu peux suivre le debat, voir repondre en direct sur le forum Zigate.

**Comment by Jake309** [comment]
Oui sans probleme, je mets les info des 2 cotés ;) 
Merci pour l'aide. 
Je fias les essaie, donne des news et si ca regle le pb je cloture cette issue

**Comment by tcharp38** [comment]
On peut continuer sur le forum Zigate pour l 'instant tant qu'il n'y a pas de conclusion.
On cloturera ce sujet + tard avec une explication et/ou solution.

**Comment by Jake309** [comment]
Alors, j'ai tenté une réinitialisation via le menu avancé de abeille. 
J'ai réinclu le module (j'ai bien eu le message réannoncé -> mise a jour)
Rien, toujours le pb.
Il ne me reste plus que le supprimer de Jeedom et le réintégrer. Mais comme tu dis que ca semble venir de la zigate et que la réinitialisation change rien, j'y crois pas trop

Je viens de voir le pb avec la prise ikea.

**Comment by Jake309** [comment]
est ce que tu veux que j'essaie de charger une ancienne sauvegarde d'avant le début des bug pour totalement dédouaner abeille ?

**Comment by tcharp38** [comment]
Tu peux oui si tu as le temps mais j'ai déja pas de doutes.
Il y a un souci sur le message envoyé par la zigate à Abeille.. déja totalement incoherent pour CET équipement.

**Comment by tcharp38** [comment]
Résumé du point:
- de nombreux équipements inconnus apparaissent 
- il sont issus d'une véritable annonce (message 004D)
- manque de pot l'adresse courte et Ieee sont daubées. Il s'agit à priori  toujours du meme equipement qui s'annonce (donc meme ieee) mais la stack zigate v2 se plante.
- Equipement source = Orvibo CM10ZW

**Comment by tcharp38** [comment]
@Jake309 
A decompresser dans core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8455420/AbeilleParser.class.php.zip)

Et core/php
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/8455423/AbeilleParser.zip)

puis redemarrer Abeille
supprimer tous les equipements 'en tros'
et tester
je veux bien un package de logs

**Comment by Jake309** [comment]
Je vois l'organisation pour envoyer le module si c'est gérable.
En fonction je testerai ta verrue. Mais sur le principe je suis de ton avis, il est préférable de régler le pb a la base et pas modifier en route pour qu'il n'apparaisse pas

**Comment by Jake309** [comment]
Info d'en cours
depuis que j'ai débranché le module pour l'envoyer fairecasoimeme , je n'ai plus de devices fantomes qui se créent.
C'est donc bien lié à ce qui est envoyé ou reçu par le device. on s'en doutait. Mais bon, autant le tracé ca peut toujours servir.

**Comment by tcharp38** [comment]
Pour mémo: bug confirmé dans le firmware zigate.

**Comment by tcharp38** [comment]
@Jake309 
Si tu as reçu ton CM10ZW peux tu me dire si les fantomes se creent toujours malgre la verrue que j'ai poussé ?

**Comment by Jake309** [comment]
Salut !!! 
Non, je n'ai plus de fantôme actuellement.
J'attends la version stable du firmware pour mettre à jour la zigate. 
On regarde pour retirer ta verrue une fois qu'elle sort si tu veux. 
Jessaie de répondre au issue dans la soirée ;)

**Comment by Seby9576** [comment]
Bonjour,

J'ai pas réussi a tous comprendre mais j'ai également deux devices non reconnus et sans commande. J'ai beau supprimer ils reviennent systématiquement. Il y a quelque chose à faire ?

Merci

**Comment by tcharp38** [comment]
Salut @Seby9576 
Si ces devices ont toujours la meme adresse IEEE alors ce sont des vrais periphs qui sont dans ton reseau mais inconnus de Jeedom jusque la.
Ils ne sont surement pas visibles sur le dashboard n est ce pas ?
Tu me files un package de logs ?

**Comment by Seby9576** [comment]
[AbeilleLogs-220515.tar.gz](https://github.com/KiwiHC16/Abeille/files/8694399/AbeilleLogs-220515.tar.gz)
id 275 et 276

**Comment by tcharp38** [comment]
Ces 2 equipements ont ete cree le 2022-05-02 à qq mins d'ecart (18:51:28 & 18:57:50).
Adresse IEEE 20918AFFFF009105 & 847127FF00000001.
Fabricant Profalux & Silicon Laboratories

A part ca rien d'autre dans les logs. 

Je soupconne que pour Profalux il s agit d'une telecommande. L'inclusion n'est pas complete mais de toute façon tu ne peux rien en faire. Une de tes telecommandes est manquante sous Jeedom ?

Pour le periph "Silicon Laboratories", il semble lui aussi un vrai periph qui ne "parle" quasi jamais.

Bref contrairement au sujet initial, ca ne semble pas des periphs "bidons".
Tu peux eventuellement activer la surveillance sur l'un deux pour voir si qqch passe sur plusieurs jours.

**Comment by Jake309** [comment]
Salut, 

J'ai 2 nouveau "fantomes"
Nom Abeille1-387
Id Jeedom 387
Dernière comm.
Nom logique Abeille1/72DF
Adresse (courte/IEEE) 72DF / 00158D0002D7901B

Nom Abeille1-386
Id Jeedom 386
Dernière comm.
Nom logique Abeille1/D411
Adresse (courte/IEEE) D411 / 00158D000365774C

Ya aussi une autre étrangeté, je t'en parle la mais s'il faut on ouvre une issue spécifique.
Hier et aujourd'hui, j'ai réussi à intégrer 2 équipement sans que la zigate soit en inclusion.

Nom Xiaomi temphumiditypressure square sensor
Id Jeedom 384
Dernière comm. 2022-05-28 09:22:21
Nom logique Abeille1/96B6
Adresse (courte/IEEE) 96B6 / 00158D0002D792C4

Nom Xiaomi Vibration
Id Jeedom 385
Dernière comm. 2022-05-28 09:20:53
Nom logique Abeille1/7B15
Adresse (courte/IEEE) 7B15 / 00158D0002AFD7A2

Ca ne pourrait pas être lié à la vérue ou un des dernieres maj beta ?
Pour info, j'ai toujours pas mis à jout la zigate, il est pas en final le firmware :/

**Comment by tcharp38** [comment]
L'inclusion d'un nouvel equipement sans etre en mode inclusion n'est pas possible, donc ils etaient deja dans le réseau.
Tu t'en es apperçu comme ca ou tu as tenté de les inclure toi meme ?

Je pense que progressivement Abeille récupère des infos d'équipements que tu as déja dans ton réseau. Ca correspond aux changements que j'ai apporté recemment.

C'est en ligne avec tes infos ?

**Comment by Jake309** [comment]
Sur le fond je suis d'accord avec toi, le pb c'est que c'est des capteurs que j'ai acheté sur leboncoin.
D'ailleur un detecteur de vibration aqara, j'en avais encore jamais eu, donc on ne peut même pas dire qu'il s'est copié d'un autre ou non.
J'ai essayé une sonde de température aussi, j'ai eu la notif et la création. Je vais essayer avec d'autres aujourd'hui, si ca se reproduit je mettrai les log.

**Comment by Xav-74** [comment]
Hello @tcharp38,

Même symptôme sur mon install depuis 1 mois environ je dirai.
Version Jeedom : 4.2.18 stable
Version Abeille : 220406-STABLE-1
Version Zigate : v1 firmware 0003-031E

Apparition de nouveaux équipements que je ne supprime pas pour le moment pour contrôler les IEEE.
Les IEEE sont souvent très proches de celles de mes 4 prises IKEA (celles-ci sont toujours OK dans Abeille).
Et pour l'une, il a une adresse IEEE quasi idem à celle de ma ruche (à deux ou trois caractères près). Et d'ailleurs il prend l'icone de la ruche ! Mais passe tout de suite en timeout.

J'essaie de te filer un package de logs dès que je peux !

Xav

**Comment by Jake309** [comment]
J'ai le phénomène qui est revenu aussi. 
Je sais pas si tu as viré ta verrue ?

**Comment by Jake309** [comment]
Je réouvre de ce fait tcharp

**Comment by tcharp38** [comment]
@Xav-74 
Il y a eu de nombreuses modifications depuis cette derniere stable que tu utilises.
Du coup pas sur que ton souci ne soit pas déja transformé.

@Jake309 
De tête la verrue dont tu parles est toujours d'actualité je pense.
Je rappelle que ce sujet concerne les zigate v2 et qu'un bug est confirmé et fixé en 3.22 (pas encore sorti).

**Comment by Xav-74** [comment]
Hello @tcharp38 
Merci pour le retour. Je viens de passer en dernière beta ce matin. Je mets sous surveillance et te redis.

**Comment by Jake309** [comment]
J'ai de nouveau pas mal de pollution. Je mets un screen tout a l'heure. Plus en 12h en stable quen 24 en beta. 
J'espère que la mise à jour du firmware sortira vite en stable.
Je vais relancer par la pour avoir des infos

**Comment by tcharp38** [comment]
Pour mémoire, en zigate v2 FW < 3.22, des equipements inconnus (car incorrects) peuvent se signaler.
Il s'agit d'un bug ZIGATE V2 et non pas Abeille, qui devrait etre corrigé en 3.22 (pas encore dispo à ce jour).


Je clos le sujet.
