### ISSUE TITLE
Mise-à-jour PiZigate

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2369]
Pour faire suite a https://github.com/fairecasoimeme/ZiGate/issues/396#

Passer en beta: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by Jerome63000** [comment]
Alors visiblement la mise a jour a réussie a se faire dans Abeille en vidant le cache, version 0004-0321, j'ai rechargé mes périphériques, ils répondent.
Si je tente une mise a jour 3.21OPDM j'ai l'erreur :

http://xxx.xxx.x.xx/core/php/getResource.php?file=core/js/log.class.js&md5=97aae7c356368e6a141e894799c00e88&lang=fr_FR | 246 | Uncaught ReferenceError: $rawLogCheck is not defined 

Peut-être due au fait que j'ai déjà le dernier firmware? Ou bien il faut que je fasse quand même un effaçage EEPROM?

**Comment by tcharp38** [comment]
L'erreur dont tu parles est un bug de la version stable. C'est pourquoi je te suggère de basculer sur la bêta, bien plus avancée

**Comment by Jerome63000** [comment]
Je vais temporiser un peu avant de passer en béta. Mes périphériques fonctionnent, j'ai juste mon plugin Alarme qui ne se déclenche plus, je ne penses pas que ce soit dû à la Pizigate. Je vais d'abord voir si tout est OK côté plugin Alarme

**Comment by tcharp38** [comment]
Ok comme tu veux.
Ce plugin fait quoi ? Il prend des infos venant d'un equipement Abeille ou il controle un equipement Abeille ?

**Comment by Jerome63000** [comment]
Normalement il prend les infos des capteurs.
Si un capteur change d'état, on donne une action a faire. Mes capteurs fonctionnes, mais l'info n'a aucune action dans le plugin. J'ai ouvert un sujet spécifique pour ce problème sur le forum Jeedom

**Comment by tcharp38** [comment]
Donc j'en conclus que ça n'est pas une action vers Abeille.

**Comment by tcharp38** [comment]
Salut @Jerome63000 
Tu en es ou sur ce sujet ?

**Comment by Jerome63000** [comment]
Salut,

Alors a ma pizigate et mon plugin abeille fonctionnent très bien après plusieurs mises à jour, réinstallation et redémarrage.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tcharp38** [comment]
Ha ben voilà une bonne nouvelle.
Je clos le sujet du coup.
Merci
