### ISSUE TITLE
CPU jusqu’à 25% et si répertoire plugin sur répertoire en mémoire cpu à 5% Max

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#237]

**Comment by edgd1er** [comment]
Quel utilitaire as tu pour monter une partition en mémoire ?
j avais essayé pour eviter l ecriture des logs en permanence sur la sd, ramlog sans succès. Ca marche bcp mieux avec log2ram.

Edit: avec qq chose comme ca, sans doute , mount -t tmpfs -o size=512m tmpfs /mnt/ramdisk

Je me demande si lebfait debpasserbpar un fichier pipe ne ralentit pas inutilement le système ?

**Comment by edgd1er** [comment]
A priori selon https://stackoverflow.com/questions/25721631/how-expensive-is-a-named-pipe-fifo, le fifo est tres couteux en perf sur un dd encore pljs sur un sd, il faudrait ke deplacer dans un tempfs. Et c est  que semble indiquer un comm dans le thread Abeille.

**Comment by KiwiHC16** [comment]
Si le pipe est source de ralentissement on peut s en passer. Il est un héritage des premières versions de code. 
Il n a pas d intérêt aujourd’hui sauf j oubli un truc. Êtes vous sur sur l os écrit sur disque pour un pipe ?

**Comment by KiwiHC16** [comment]
Pour moi le pipe reste en mémoire comme le dit une personne dans le lien mentionné plus haut: "A named pipe is just a file system entry for an in-memory buffer", peut être que je me trompe...

**Comment by edgd1er** [comment]
Effectivement selon le man: " When processes are exchanging data via the  FIFO,  the  kernel
       passes  all  data  internally without writing it to the filesystem"

j'ai fait un essai en déplaçant le fifo dans le rep tmp qui est monté en mémoire sur un Rpi.
Pas d'amélioration du démarrage du moins, 1.3 à 2 minutes pour lancer les démons. au lancement d'Abeille mon load cpu monte a 1.82 sur 1 minutes et 2 sur 5 minutes. Le Rpi2 est bien chargé.

Je me demande si ce ne sont pas les mécanismes du fifo qui ralentissent le système. As t on besoin de garder le pipe ? Y a t il des commandes faites de séries de messages ordonnés ? 

Dans le debug, je vois bcp d'appel à deamon_info concurrents. ou alors le deamon_info out n'est pas logué. Ce n'est que de la lecture d'info mais ça peut être gourmand.

Pour info, j'ai juste modifié  $in="/tmp/AbeilleSerialFifo"; dans le /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/config.php 

Si vous faites la modif, constatez vous un différence ?

**Comment by KiwiHC16** [comment]
Je pense qu’on peut virer le pipe car il n’apporte rien d’après mes souvenirs sauf un découplage de la remontée des infos sur le port et le parsing lui même (gestion des blocking). Mais je ne pense pas que le pipe en lui même amène de la charge cpu. Il faut regarder la manière dont les blocking sont gérés. Le parser bouclait sans relâche sur le pipe à une période. On avait mis un test sur chaîne vide pour ne pas avoir trop de log vide mais le process boucle probablement toujours. 

Autre sujet est la boucle de monitoring des démons qui me semble super lente sur mon RPI 3 ( alors sur un 2...), il y a certainement de l optimisation sur ce point. Et ça boucle toutes les 5 ou 15s alors que je pensais que Jeedom lançait la vérification que toutes les 5 mins.

**Comment by KiwiHC16** [comment]
Modification dans le master.
