### ISSUE TITLE
Commande info en doublon sur certains capteurs

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2370]
Salut,

Depuis peu j'ai deux commandes humidités qui apparaissent sur les capteurs température et humidité, c'est le cas sur aqara et sonoff. Par contre sonoff je n'ai pas de valeur sur la deuxièmes. Pour les aqara comment savoir quelle est la bonne vu que ce n'est pas la même valeur.
![image](https://user-images.githubusercontent.com/77990298/161299555-314660e1-c148-4392-8290-1a2c438872bd.png)

Merci de ton aide

**Comment by tcharp38** [comment]
Peux tu me donner un package de logs et L'identifiant du modèle correspondant ?

**Comment by Seby9576** [comment]
![image](https://user-images.githubusercontent.com/77990298/161317111-4a309200-008d-46fd-82c2-5a9b1c0d9d94.png)
![image](https://user-images.githubusercontent.com/77990298/161317296-7a93688c-ce82-427d-9291-20948221b1e5.png)
![image](https://user-images.githubusercontent.com/77990298/161317359-e0152ee5-d398-4111-8a5a-966f50904bf9.png)
![image](https://user-images.githubusercontent.com/77990298/161317448-c9348478-627a-48d8-8a8a-bf6d308198c4.png)

[AbeilleLogs-220401.tar.gz](https://github.com/KiwiHC16/Abeille/files/8399996/AbeilleLogs-220401.tar.gz)

**Comment by Seby9576** [comment]
Voici un ou il y en a pas de doublon. A savoir c'est lors d'une réinclusion que ca se produit. De plus certains donnent maintenant avec un chiffre après la virgule alors qu'avant non.
![image](https://user-images.githubusercontent.com/77990298/161317714-7e955440-3266-4e24-8876-ae3521df1795.png)
Merci

**Comment by tcharp38** [comment]
Je vois 2 questions
- pourquoi la mise à jour du modele est elle declenchée. La pas de traces, le log du parser se rempli trop vite
- pour la mise à jour a conservé 2 "humidité". En fait le bon est "Humidity" (je normalise progressivement un peu tout les noms)

[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8402161/Abeille.class.php.zip)

Peux tu decompresser ce fichier dans Abeille/core/class
puis redemarrer le demon
cliquer sur "capteur de constance", page avancé
faire "recharger" modele
et me filer le package de logs 

Merci

**Comment by Seby9576** [comment]
[AbeilleLogs-220402.tar.gz](https://github.com/KiwiHC16/Abeille/files/8402194/AbeilleLogs-220402.tar.gz)
Je viens de le faire à l'instant

**Comment by Seby9576** [comment]
Humidity est vide
Humidité j'ai une valeur

**Comment by tcharp38** [comment]
Tu as toujours "humidity" ?
Raffraichis ton dashboard. Je ne le vois plus dans les commandes enregistrées

Ha et contrairement à ce que j'ai dit, dans ton cas le bon est bien "Humidite". Le nom n'est pas changé si mise à jour.

**Comment by Seby9576** [comment]
Pourquoi j'ai deux valeurs différentes ?

Tu as toujours "humidity" ? Pour certains oui d'autre non

**Comment by tcharp38** [comment]
Argh.. je vois ce qui se passe. Cas imprévu.

Si jamais tu veux tenter sur un seul capteur le temps que je trouve la solution, tu peux faire un "Reinitialiser". Ca devrait supprimer les doublons.

**Comment by Seby9576** [comment]
Celui de la salle de jeu

Humidity 42.9
humidite 654

**Comment by tcharp38** [comment]
Tu peux arreter la tes essais. J'ai compris.
Il y a des doublons qui ont ete crées suite a un bug mais qui ne sont pas gérés lors de la mise à jour.
Je reviens vers toi.
Entre temps si tu n'as pas de backup recent, fais en un. Je ne veux pas te mettre dans la m.. tu as beaucoup de devices.

**Comment by tcharp38** [comment]
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8402246/Abeille.class.php.zip)

Decompresser
redemarrer
recharger un modele
et verifier dashboard et me donner le package

**Comment by Seby9576** [comment]
T'inquiète pas les back up sont fait chaque nuit automatiquement
![image](https://user-images.githubusercontent.com/77990298/161377718-9f65f0c4-9821-4b4c-a6e2-be339a62361b.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-220402 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/8402278/AbeilleLogs-220402.2.tar.gz)
Idem je viens de le faire mais j'ai regardé et j'ai toujours les deux commandes

**Comment by tcharp38** [comment]
Il faut que je revois ma copie.

**Comment by tcharp38** [comment]
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8402500/Abeille.class.php.zip)
 J'espere que c est bon cette fois.

L'avantage de tout ça est que je pense que ce dernier code est + robuste et couvre d'autres cas pas tres propres. Bref ca devrait avoir du bon sur la qualité d'Abeille en general.

**Comment by tcharp38** [comment]
Pour info j'ai fait une nouvelle beta. Sera dispo demain sur le market.
Je compte un peu sur toi pour savoir si on peut eliminer ce sujet des soucis empechant de faire une version stable. Merci

**Comment by Seby9576** [comment]
Je ferais un test demain en fin de journée. Bon week-end

**Comment by Seby9576** [comment]
Salut, J'ai plus qu'un humidité cette fois, par contre tu as fait en sorte d'avoir toujours un chiffre après la virgule ?

Faut il tous les recharger maintenant ?

Merci

**Comment by tcharp38** [comment]
A priori il n'y avait aucun chiffre apres la virgule avant. Ca fait plus de plus de sens non ?

**Comment by Seby9576** [comment]
Pour moi ça n'a pas vraiment d'importance mais why not.c'était une question comme ca. Mes widgets ne sont plus adapté mais si ça bouge pas  je vais changer. Merci

**Comment by tcharp38** [comment]
Pour moi un pourcentage avec un chiffre apres la virgule n'est pas vraiment utile. Je corrige le modele.

Tu peux decompresser ca dans core/config/commands
[zb-0405-MeasuredValue.zip](https://github.com/KiwiHC16/Abeille/files/8409611/zb-0405-MeasuredValue.zip)

**Comment by Seby9576** [comment]
C'est good pour la virgule, dois recharger chaque capteurs pour la prise en compte du doublon stp ?

**Comment by tcharp38** [comment]
Oui malheureusement.
A terme j'espère arriver à mettre en place une mise à jour automatique si la modèle a évolué, tout en gardant qq customisations de l'utilisateur

**Comment by Seby9576** [comment]
OK pour info il y avait aussi l'info pression qui était en double mais comme je m'en sert pas je n'avais pas vu

**Comment by tcharp38** [comment]
@Seby9576 
Du coup quel est le status de ce sujet ? On peut clore ?

En ligne avec le résumé suivant ?

- Corrigé depuis la  220402-BETA-2
- Si le pb apparait sur un des equipemeent, faire "recharger" modele via la page EQ/avancé

**Comment by Seby9576** [comment]
Oui c'est good sauf aussi le doublon pour la pression. Pour moi ce n'est pas dérangeant mais je préfère remonter l'info
![image](https://user-images.githubusercontent.com/77990298/162054267-5fa7f52d-6bbc-4c84-a548-a39595202e9a.png)

**Comment by tcharp38** [comment]
Ha je suppose qu'il s'agit du modele "weather".
Dans ce cas il ne s'agit pas d'une regression. Je vois que le modele est construit comme ca mais c'est historique.
J'essaie de comprendre.

**Comment by tcharp38** [comment]
Ok.
Il s'agit au final de la meme info mais 2 sources differentes.
D'autre part seule "pression" est visible par défaut, l'autre ("pression1") est masquée.

Pour info, 
- "pression" est tiré de l'attribut 0403-01-0010
- alors "pression1" est tiré de l'attribut 0403-01-0000

Pas vraiment de sens de garder les 2. A nettoyer à l'occase mais n 'est pas une regression. Modele construit comme ca des les débuts d'Abeille.

**Comment by tcharp38** [comment]
Il n'y a plus qu'une "pression" dans le dernier modele du "whether".
Tu peux tester via la page EQ/Avancé => modele, reinitialiser

Je clos le point mais a reouvrir si soucis.
