### ISSUE TITLE
Philips Hue Smart Plug LOM007

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2374]
J'ouvre un issue pour le sujet initié sur le forum Jeedom ici : https://community.jeedom.com/t/philips-hue-smart-plug/82620

Le résumé : 
J'ai acheté une prise zigbee Philips Hue Smart Plug
Elle n'est pas reconnue pas Abeille (defaultUnknown)

J'ai lu ici [https://community.jeedom.com/t/philips-hue-smart-button-jeedom-v3-plugin-abeille/36350](url) et ici [https://community.jeedom.com/t/compatibilite-phillips-hue-smart-plug/55039](url) que l'identification de cette prise varie selon les séries.

La mienne est une LOM007.

J'attache le fichier discovery.
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8499634/discovery.zip)

**Comment by tcharp38** [comment]
Salut

[LOM007.zip](https://github.com/KiwiHC16/Abeille/files/8501369/LOM007.zip)

A decompresser dans core/config/devices
redemarrer Abeille
et refaire inclusion.

Tiens moi au jus

**Comment by eoeir** [comment]
J'ai du m'y reprendre à plusieurs fois mais c'est bon. Inclusion réussie, prise fonctionnelle !

Merci.

**Comment by tcharp38** [comment]
Ok.
Du coup tout est bon ou le sujet doit rester ouvert ?

**Comment by eoeir** [comment]
Pas besoin de le laisser ouvert.
