### ISSUE TITLE
Sonde déportée température (id = THS317-ET ,OWON)

### ISSUE THREAD

**Issue by ChrisChrisChri** [KiwiHC16/Abeille#2379]
Bonjour TCharp38,

Voici une sonde qui permet de mesurer de manière déportée un liquide. Si t'as le temps de jeter de jeter un oeil, Je n'ai pas de retour de température dans Abeille. 

![image](https://user-images.githubusercontent.com/82177848/165993297-7b8c3c43-6825-43b8-92b0-7169075c161c.png)

[discovery (1).zip](https://github.com/KiwiHC16/Abeille/files/8592617/discovery.1.zip)

Merci d'avance.

**Comment by tcharp38** [comment]
Salut
Je viens juste d'ajouter cette sonde (la mienne est la THS317-ET) pour mon usage perso.
Donc elle devrait deja etre dans la derniere beta.
Tu bascules dessus et testes ?

> 220428-BETA-1
> -------------
> 
> - ...
> - Owon multi-sensor THS317-ET: Ajout support.
> - ...
>

**Comment by tcharp38** [comment]
@ChrisChrisChri 
Des news ?

**Comment by ChrisChrisChri** [comment]
Salut,
J'ai bien installé la BETA. La sonde apparaît avec l'option T° affiche un résultat. Peux-tu me dire quel est le taux de rafraichissement ou le temps d'attente entre 2 mesures ?

![image](https://user-images.githubusercontent.com/82177848/168477232-d3064855-8a38-4c93-ace5-618c07987034.png)

**Comment by tcharp38** [comment]
Normalement la température est remontée toutes les 5 à 10mins.
Ca n'est pas ce que tu observes ?

**Comment by ChrisChrisChri** [comment]
Oui. On est dans cette tranche. Tu penses qu'il y a moyen de diminuer le temps d'attente. Je dois mesurer la température entre le départ d'eau froide et d'eau chaude. Le but est de régler le débit rentrant en fonction....En 10 minutes, ça laisse passer trop de temps...

**Comment by tcharp38** [comment]
Tu penses à quoi comme durée ?

Je suis reticent à modifier le modele pour 2 raisons
- le changement de temp n'est en général pas qqch qui a une dynamique rapide
- et plus le periph se reveille souvent pour envoyer l'info plus vite il vide ses batteries

Bref 5 à 10min c est qqch d'habituel.

Mais tu pourrais modifier la durée de ton cote (configureReporting)

**Comment by ChrisChrisChri** [comment]
Salut,
Oui tu as raison. C'était pour me faciliter la vie lors de l'installation et éviter de devoir attendre entre chaque test. Une fois que ce sera en place, le délai est tout à fait raisonnable.
Merci pour le job comme d'hab !!!

**Comment by tcharp38** [comment]
Du coup on clos ce sujet ?

**Comment by tcharp38** [comment]
Je réouvre le sujet suite à https://community.jeedom.com/t/ths317-pas-de-remonte-de-temperature/114300

**Comment by gegedme** [comment]
merci pour ton aide.
Ma zigate est à jour.
j'ai refait l'inclusion plusieurs fois.
la sonde apparait mais jamais de remonté de température puis elle passe en timeout.
ce matin je viens de refaire une inclusion.
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/bf955ec1-9f4b-4b3d-ab01-d4ff85366e8b)
toujours pas de température.
ci-joint tous les log Abeille
merci 
[AbeilleLogs-231108.tar.gz](https://github.com/KiwiHC16/Abeille/files/13293449/AbeilleLogs-231108.tar.gz)

**Comment by gegedme** [comment]
une heure après 
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/a8c40847-0428-48de-9b3d-e74bf11f21bd)

**Comment by tcharp38** [comment]
Je viens de ressortir mon modele du placard.
Je regarde ça

**Comment by tcharp38** [comment]
Bon j'ai bien les remontées de batterie et temperature.
Voila le dernier modele que je vais pousser dans la prochaine beta.
[THS317-ET_OWON.zip](https://github.com/KiwiHC16/Abeille/files/13297350/THS317-ET_OWON.zip)

A decompresser dans core/config/devices/THS317-ET_OWON
puis redemarrer le démon Abeille
et refaire une inclusion.
et me filer le package de logs (page maintenance + telecharger tout) au bout de qq mins

Voila mon log monitor pour info
[AbeilleMonitor (3).log](https://github.com/KiwiHC16/Abeille/files/13297397/AbeilleMonitor.3.log)

**Comment by gegedme** [comment]
j'essaye de suite
merci

**Comment by gegedme** [comment]
j'ai du créer le répertoire devices qui n'existait pas 
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/9e8a7e56-778c-4ff3-b6aa-213af84c07c2)

voilà le package de logs après le redémarrage du démon abeille, l'inclusion et 5 min d'attente.
[Uploading AbeilleLogs-231108.tar.gz…]()

**Comment by gegedme** [comment]
j'ai tout refait en ajoutant un répertoire THS317-ET_OWON dans core/config/devices/ dans lequel j'ai extrait l'archive.
ci-joint les logs après 5min
[AbeilleLogs-231108 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13297708/AbeilleLogs-231108.1.tar.gz)

**Comment by tcharp38** [comment]
Le reporting se fait toutes les 5 à 10mins pour la temp, 30 à 58mins pour la batterie.
Donc à surveiller mais log trop court pour l'instant.

**Comment by ChrisChrisChri** [comment]
Bjr, 
Voila que je me reconnecte. En ce qui me concerne, j'ai un retour d'infos depuis tjrs donc +/- 05/2022. Mon scénario qui me relève la température 1x/jour par mail fonctionne correctement. Si je peux aider.... @tcharp38, la marque NIKO( matériel électrique comme Legrand) a étendu sa gamme dans les interrupteurs. Je n'ai pas encore craqué :-)

**Comment by gegedme** [comment]
24 heures après toujours de remonté de température
[AbeilleLogs-231109.tar.gz](https://github.com/KiwiHC16/Abeille/files/13310365/AbeilleLogs-231109.tar.gz)

**Comment by tcharp38** [comment]
Je soupconne 2 choses
- le FW est different et peut etre pas à jour
- la phase d'inclusion se passe mal

Tu peux recommencer une inclusion et me filer les logs ? Je vais regarder le 2nd point en details.

**Comment by gegedme** [comment]
je fais ça de suite !
merci

**Comment by gegedme** [comment]
[Uploading AbeilleLogs-231109 (1).tar.gz…]()
voilà

**Comment by tcharp38** [comment]
Upload incomplet 😔

**Comment by gegedme** [comment]
j'ai retenté une inclusion après avoir supprimé l'équipement.
puis téléchargé tout les log.
[AbeilleLogs-231110.tar.gz](https://github.com/KiwiHC16/Abeille/files/13316629/AbeilleLogs-231110.tar.gz)

j'espère que j'ai bien tout fait cette fois ci

**Comment by gegedme** [comment]
j'ai utilisé l'assistant de découverte d'équipement
tout est dans le vert
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/5d93627f-f33a-4fb1-a610-7a4ccced0929)
[discovery-THS317-ET_OWON.json](https://github.com/KiwiHC16/Abeille/files/13316739/discovery-THS317-ET_OWON.json)

**Comment by tcharp38** [comment]
Bon ben device un peu + recent que le mien.
A priori 20221019 contre 20121101
Donc visiblement pas le meme FW.

Mais tu n'utilises pas le modèle que je te donné car j'ai pas fait attention.. tu ne l'as pas mis au bon endroit.
Comme c'est un modele existant tu n'as aucun repertoire a creer
Tu dois avoir core/config/devices/THS317-ET_OWON/THS317-ET_OWON.json
C'est celui la qu'il faut ecraser avant de refaire une inclusion.

Accessoirement si tu bascules sur la beta Abeille tu sera au gout du jour de toutes les avancées. Elle est tres mature.

**Comment by gegedme** [comment]
ok. j'ai corrigé 👍 
je suis en béta
j'ai écrasé le fichier Json avec celui que tu m'avais donné dans le bon répertoire.
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/989fd6c4-a162-4d86-9a38-1ef24fbb4f87)
les commandes ont changé et j'ai maintenant la batterie.
[AbeilleLogs-231110 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13319620/AbeilleLogs-231110.1.tar.gz)

**Comment by gegedme** [comment]
[AbeilleMonitor (1).log](https://github.com/KiwiHC16/Abeille/files/13319761/AbeilleMonitor.1.log)
après 5 minutes

**Comment by gegedme** [comment]
j'ai configuré le relevé de température toutes les minutes
voilà le log après 10 minutes
[AbeilleMonitor (2).log](https://github.com/KiwiHC16/Abeille/files/13319849/AbeilleMonitor.2.log)

**Comment by tcharp38** [comment]
Je realise que le modele n'est pas complet. Cet equipement est sur batterie donc tu ne peux PAS l'interroger.
C'est à lui de donner des infos regulierement.
Je creuse

**Comment by tcharp38** [comment]
Ho p... la galere.
Je viens de comprendre

Ton device utilise le "end point" 01 et non pas "03" comme le notre.
Alors ca c'est de l'incompatibilité !!! Travail de cochon.
Ils changent le FW et sa maniere de fonctionner, sans changer l'identifiant du device.

Pour test, ecrase le modele avec celui ci et je vais reflechir à la solution la + simple.
[THS317-ET_OWON.zip](https://github.com/KiwiHC16/Abeille/files/13321002/THS317-ET_OWON.zip)
Donc tu refais une inclusion et tu laisses tourner au moins 10mins avant de verifier

**Comment by gegedme** [comment]
ok. c'est fait.
je faire du Kendo et rentre vers 20h.
je regarderai en rentrant.
merci encore pour ton aide.

**Comment by gegedme** [comment]
je viens de regarder avant de partir !!!
ça fonctionne !!!!
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/64d6fd91-8bc1-435a-9c31-f029dd86974d)
tu es mon sauveur.

**Comment by gegedme** [comment]
pour te faire une donation, je fais comment ?
as-tu un lien ?

**Comment by tcharp38** [comment]
Merci à toi. Ca m'aidera à acheter du matos de test https://paypal.me/Tcharp38
Reste à trouver une solution propre pour supporter ces 2 FW.

En résumé, pour une même signature de device
- ancien devices (dateCode=20121101) => ENDPOINT 3 => Forcer modele **"THS317-ET_OWON-old"**
- nouveau devices (dateCode=20221019) => ENDPOINT 1

A partir de la 1ere beta 2024, il sera possible de forcer un modele "old" pour la 1ere generation de ces équipements.

**Comment by gegedme** [comment]
Je viens de faire un don.
Ne soit pas surpris....
J'ai des gros doigts. En voulant donner 20 euros j'ai mal tapé et j'ai versé 0,20 euros.
La honte 😅
J'ai complété immédiatement 😜

**Comment by tcharp38** [comment]
😂
Merci beaucoup

**Comment by tcharp38** [comment]
Pour mémo, le modele Abeille à partir d'aujourd hui va se baser sur le EP01.
Du coup les anciens devices qui utilisent le EP03 ne fonctionneront plus sans modification apres inclusion.

Pas de solution automatique à l'heure actuelle

**Comment by Kallagan99** [comment]
bonjour à tous !
je me permets de poster un commentaire à ce sujet.
Je viens de recevoir 8 sondes de ce modèle, incluses sous Jeedom avec le plugin Abeille en beta.
RAS pour l'inclusion (instantanée en beta).
Les infos remontent, il faut être un peu patient (ça met jusqu'a 30 min pour les 1eres infos).
Le niveau de batterie aussi sauf que celui ci ne se met plus à jour ensuite. On reste avec la 1ere valeur remontée.
Ca vous fait ça aussi ?

EDIT : Il semble que la période d'update pour la température soit de 54 min... allez comprendre

**Comment by tcharp38** [comment]
Salut @Kallagan99 
Choisi une de tes sondes, et met la en surveillance. Ca va remplir AbeilleMonitor.log qu'on regardera... l'année prochaine.

**Comment by tcharp38** [comment]
@Kallagan99 
Des nouvelles ?
