### ISSUE TITLE
Tuya Smoke Detector (id = TS0601, _TZE200_ntcy3xu1)

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2380]
Hello, I have just acquired Zigbee Smoke Detector (Tuya). I would like to install it in Jeedom (4.2.14) with Abeille, as it is not referenced, I generated an attached "discovery.json" file as indicated in the manual.
Thanks for your help
(sorry I use a translator, I don't speak English)
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8605147/discovery.zip)

**Comment by tcharp38** [comment]
Hello @Jeedom122 
At first could you switch to beta version ?
I prefer to do support on this for 2 reasons; more advanced code and your feedback is key for next level.

Note that this is a Tuya device that uses "non standard" EF00 private cluster. So not straightforward to integrate.

Please ensure to be in "debug" mode, with 5000 lines for logs.

**Comment by Jeedom122** [comment]
Boujour @tcharp38 
J'ai vu que vous avez une adresse laposte.net, est-ce que l'on pourrait communiquer en français ? SVP
Je vais essayer de passer en version beta.
Merci pour votre intérêt à mon problème.

**Comment by Jeedom122** [comment]
Boujour @tcharp38
J'ai vu que vous êtes d'Echirolles, d’où le 38, est-ce que l'on pourrait communiquer en français ? SVP
Je viens de passer Abeille en mode debug.
Par contre pour l'installation de la version beta, est-ce je vais perdre les appareils déjà installés ?
Merci pour votre intérêt à mon problème.

**Comment by Jeedom122** [comment]
Pour info, voici le lien vers le produit [Tuya WiFi Zigbee](https://fr.aliexpress.com/item/1005003984592114.html?spm=a2g0o.order_list.0.0.21ef5e5bxY2Enk&gatewayAdapt=glo2fra)
Merci !

**Comment by tcharp38** [comment]
Pas de soucis pour le Français :) J'ai cru que tu étais anglophone et j'etais surpris d'ailleurs puisqu'Abeille n'est pas vraiment adapté pour ça.

En passant en beta, tu ne perds rien. Tu sera sur la derniere version du code.
Au pire tu as toujours un backup automatique Jeedom qui te permet de revenir en arriere.

Une fois que tu as basculé sur la beta, peux tu faire faire un test (il doit y avoir un bouton pour ca) et me filer le package de logs (page support, telecharger tout).
Merci

**Comment by Jeedom122** [comment]
Merci à toi, je regarde ça ce soir dès que je rentre...

**Comment by Jeedom122** [comment]
Bonjour @tcharp38 ,
Je te joins les logs, ainsi que le discovery.
Par contre j'ai bien passé les logs en 5000 lignes, relancé, désactivé et réactivé Abeille, et même relancer le serveur, rien n'y fait toujours 500 lignes, donc j'ai fait 2 extractions.
Le passage en bêta, pas de souci :)
Bonne journée et merci !

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8618607/discovery.zip)
[log 03-05-22.zip](https://github.com/KiwiHC16/Abeille/files/8618608/log.03-05-22.zip)
[log 04-05-22.zip](https://github.com/KiwiHC16/Abeille/files/8618609/log.04-05-22.zip)

**Comment by tcharp38** [comment]
Salut.
Si les logs sont toujours a 500 lignes c est que tu n'as pas modifié le bon endroit.
Tout le monde se plante t'inquiete.
![image](https://user-images.githubusercontent.com/35221038/166647906-6b80f34b-c171-4a6e-acba-82005046f1cc.png)

Je vais regarder ce que tu as envoyé.

Autre remarque, la page support te permet de generer un package de logs & autres infos utiles, d'un seul coup. 
C'est ce que j'appelle le "package de logs".

L'adresse de ton "smoke detector" est bien BDA6 ?

**Comment by Jeedom122** [comment]
@tcharp38, effectivement il y avait encore un onglet pour modifier la quantité de log ;)
D'ailleurs depuis la modification il n'y a qu'un fichier qui a pris du poids "Abeille" 2479 logs
que je joins, car même en cherchant sur internet je n'ai pas trouvé "package de logs", désolé.
Oui "smoke detector" est bien BDA6.
[Abeille.zip](https://github.com/KiwiHC16/Abeille/files/8619902/Abeille.zip)

**Comment by tcharp38** [comment]
Pour le package de logs:

- Plugins > Protocole domotique > Abeille
- Puis en haut a droit "SUPPORT"
- Et enfin sur la gauche tu as l'ensemble des logs et autres infos utiles et le bouton "Telecharger tout"

Je vais creuser ca mais probablement la semaine prochaine. Je fais un aller-retour en UK, retour dimanche. Donc loin de mon PC de dev.

**Comment by Jeedom122** [comment]
D'accord, dans le plugin Abeille, je cherchais dans jeedom :(
Voilà le fameux
[AbeilleLogs-220504.tar.gz](https://github.com/KiwiHC16/Abeille/files/8621267/AbeilleLogs-220504.tar.gz)
Bon séjour chez les Anglais.
A+

**Comment by tcharp38** [comment]
Salut @Jeedom122 
Si tu as bien basculé sur la derniere beta, peux tu refaire une inclusion de ton equipement ?
Puis me fournir le package de logs.
Merci

**Comment by Jeedom122** [comment]
Bonjour @tcharp38 ,
Oui j'ai fait la MaJ, le détecteur Tuya a bien été reconnu, je te joins des captures d'écrans sur le résultat obtenu.
Ce soir je ferais des tests, et te ferais parvenir le package de logs.
Bonne journé
![2022-05-13_112204](https://user-images.githubusercontent.com/104787819/168256776-d749a180-e704-4878-b12d-3f24ce250bff.jpg)
![2022-05-13_084710](https://user-images.githubusercontent.com/104787819/168256787-287d4dad-aa20-46d7-84bf-2c525a213cf4.jpg)
![2022-05-13_111920](https://user-images.githubusercontent.com/104787819/168256790-c58c062a-281d-4dbe-9a3d-bbd8b4261a49.jpg)
![2022-05-13_095058](https://user-images.githubusercontent.com/104787819/168256793-04da5cdc-914a-4fa3-8d5a-50fcf4b294c1.jpg)
e

**Comment by Jeedom122** [comment]
Et voilà les logs, j'ai activé l'alarme avant peut-être tu auras plus d'infos.
Merci !! 
et bon weekend
[AbeilleLogs-220513.tar.gz](https://github.com/KiwiHC16/Abeille/files/8689666/AbeilleLogs-220513.tar.gz)
.

**Comment by tcharp38** [comment]
Salut
Quand tu dis que tu as activé l'alarme, tu veux dire quoi ? Il y a un bouton de test ? Si oui c'est equivalent à une detection de fumée ?

Je vois dans le log qqch qui remonte à 2022-05-13 19:07:05 avec la valeur 00
puis 2022-05-13 19:07:13 avec la valeur 01
mais je ne sais pas à quoi ca correspond.
Je soupconne qu'il s'agit du status "smoke detection", DP 01.

Du coup quand tu fais une manip, soit précis et donne moi l'heure STP.

Et si tu as une image PNG sans arriere plan à mettre en icone, je suis preneur.

**Comment by tcharp38** [comment]
Tiens.
J'ai fait 2 suppositions: smoke alaram sur DP 01, et battery percent sur DP 0F.

Pour core/config/device/TS0601__TZE200_ntcy3xu1
[TS0601__TZE200_ntcy3xu1.zip](https://github.com/KiwiHC16/Abeille/files/8701405/TS0601__TZE200_ntcy3xu1.zip)

Pour core/config/commands
[attr-Smoke-Alarm.zip](https://github.com/KiwiHC16/Abeille/files/8701440/attr-Smoke-Alarm.zip)

Pour core/php
[AbeilleParser-Tuya.zip](https://github.com/KiwiHC16/Abeille/files/8701417/AbeilleParser-Tuya.zip)

Redemarrer Abeille
Refaire test
Et filer log & heure

**Comment by Jeedom122** [comment]
Bonjour @tcharp38 ,
Je te remercie pour le temps que tu mets à chercher une solution au bon fonctionnement du Tuya smoke.
J'ai remplacé les fichiers joints dans le précédent message, relancé Abeille.
Voici le résultat de toutes les fonctions activées
![2022-05-18_085833](https://user-images.githubusercontent.com/104787819/168979323-73326298-7f17-4f49-a6a1-7f5c84a5ef97.jpg)
Le "online" s'active régulièrement ?
Et "link Quality" la donnée varie, à un moment s'était indiquée "air quality"
Effectivement il y a un bouton test pour l'alarme, par contre est-ce que c'est l’équivalent à une détection de fumée ?
Je refais un test ce soir avec plus de précision.
Je te joins une image png du détecteur
[node_Tuya-smok.zip](https://github.com/KiwiHC16/Abeille/files/8714068/node_Tuya-smok.zip)
Bonne journée !

**Comment by tcharp38** [comment]
Salut
Merci pour le PNG. C'est mergé.
Toutes les infos que tu affiches sont des infos internes, non exposées sur le dashboard.
Mais normal jusque la vu que le modele ne contient encore aucune info.

J'ai besoin des logs pour voir ce qui remonte.

Le "online" donne une idée du status du periph si vivant ou pas
Linkquality = idée de la transmission

Pour le role du bouton "test" je ne peux pas repondre. N'y a t il rien dans la doc ?
Mais je suppose que ca devrait etre l equivalent à une alarme declenchée

**Comment by Jeedom122** [comment]
Hello @tcharp38 ,
Voici les logs après MaJ, déclenchement de l'alarme le 18 à 20h40, pendant 5s avec bouton
et aujourd'hui à 12h10 déclenchement avec de la fumée, comma ça ;)
[AbeilleLogs-220519.tar.gz](https://github.com/KiwiHC16/Abeille/files/8728165/AbeilleLogs-220519.tar.gz)
Et voilou !!
A++

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Voici le retour d'infos sur le fonctionnement depuis la MàJ.
Il y a bien la détection alarme, avec un scénario l'info est bien transmise lors du changement de statut, super !!
Par contre l'info de la batterie ne remonte pas, est-ce que je dois renseigner quelques choses ?
L'essentiel fonctionne, je te remercie encore pour ton aide !

![2022-05-31_102554](https://user-images.githubusercontent.com/104787819/171128648-37113946-1a51-4ede-b678-183263692a0b.jpg)

**Comment by tcharp38** [comment]
Salut @Jeedom122 
Du coup il ne manque que le retour de batterie ?

On dirait que ce device ne sait pas faire de reporting de batterie: https://github.com/Koenkk/zigbee2mqtt/issues/12622

J'ai ajouté le "battery low".

A decompresser dans core/config/commands
[attr-Battery-Low.zip](https://github.com/KiwiHC16/Abeille/files/8809367/attr-Battery-Low.zip)

A decompresser dans core/config/devices/TS0601__TZE200_ntcy3xu1
[TS0601__TZE200_ntcy3xu1.zip](https://github.com/KiwiHC16/Abeille/files/8809378/TS0601__TZE200_ntcy3xu1.zip)

A decompresser dans core/php
[AbeilleParser-Tuya.zip](https://github.com/KiwiHC16/Abeille/files/8809387/AbeilleParser-Tuya.zip)

- puis redemarrer Abeille
- refaire inclusion
- et faire le point


D"autre part, j'ai besoin des infos suivantes pour completer le modele:
- type de batterie
- ref fabricant si existe

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Merci pour les nouveaux fichiers.
Après installation et test, il est bien indiqué lorsque les piles sont faibles et lorsqu'elles sont chargées.
Par contre pas de pourcentage, ça avance bien :)
Ce sont 2 piles LR03 qui alimentent l'appareil.
Merci pour le travail déjà effectué et pour la suite, bonne soirée...

**Comment by tcharp38** [comment]
Hello.
Pour le pourcentage je ne sais pas comment résoudre le pb.
Le device ne semble pas le fournir, ni de maniere automatique ni par lecture.
Idem pour la tension.

Bref sauf si il y a une info cachée dans le cluster EF00, on ne peut pas inventer cette info sur la batterie.

Par contre idéalement il faudrait reporter à Jeedom 100% tout le temps et 0% à reception de "battery low".

**Comment by Jeedom122** [comment]
@tcharp38,
Merci beaucoup pour ton aide, cela semble fonctionner.
J'avais mis une alerte sur la batterie lorsqu'elle est low, ça fonctionne.
Encore merci !!!

**Comment by tcharp38** [comment]
Cool.
On peut clore ce sujet du coup ?

**Comment by Jeedom122** [comment]
Oui, merci !
