### ISSUE TITLE
deamon_start_cleanup: message récurrent "DB config v20201025 < v20201122 => Update required"

### ISSUE THREAD

**Issue by Bch78** [KiwiHC16/Abeille#2381]
A chaque redémarrage de Abeille il y a apparition du message:
[2022-05-03 07:41:36][DEBUG] : deamon_start_cleanup(): **DB config v20201025 < v20201122 => Update required**.

Une analyse du code :
./plugins/Abeille/plugin_info/install.php

montre les lignes suivantes:
208        if (intval($dbVersion) < 20201122) {
 :             :
 :             :
 :             :
**401            //    config::save('DbVersion', '20201122', 'Abeille');**
402        }
403    }

autrement dit:
si on s'aperçoit que la version DB est inférieure à 20201122 alors on exécute des actions de mise à niveau
et à la fin de cette séquence, on ne met pas à jour la valeur de DbVersion (ligne 401:mise à jour est en commentaire)
=> à la prochaine exécution on refera la même chose.

Est-ce le comportement voulu pour une raison quelconque ?
Ou alors est-ce une erreur de laisser la ligne commentée ?

Merci.

===================
Ma config Abeille:
===================

Informations clefs nécessaires au support.

Quand [vous ouvrez une "issue"](https://github.com/KiwiHC16/Abeille/issues/new) dans GitHub merci de copier/coller les 3 premiers chapitres ci dessous 
Pour l'intégration d'un équipement non encore supporté ajoutez le chapitre 4.

Version Abeille: 220406-STABLE-1

Kernel: ["Linux raspberrypi-039 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU\/Linux"]

Zigate 1: 0003-0321

Table 'update'
==============
{
    "12": {"type":"plugin","name":"Abeille","logicalId":"Abeille","localVersion":"2022-04-07 01:00:21","remoteVersion":"2022-04-07 01:00:21","source":"market","status":"ok","configuration":"{\"version\":\"stable\",\"market\":1,\"third_plugin\":1,\"doNotUpdate\":\"0\"}","updateDate":"2022-04-16 17:38:59"},
}

Table 'cron'
============
{
    "120910": {"enable":"1","class":"Abeille","function":"deamon","schedule":"* * * * *","timeout":"1440","deamon":"1","deamonSleepTime":"1","option":null,"once":"0"},
}

Table 'config'
==============
{
    "AbeilleActiver1": {"plugin":"Abeille","value":"Y"},
    "AbeilleActiver10": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver2": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver3": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver4": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver5": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver6": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver7": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver8": {"plugin":"Abeille","value":"N"},
    "AbeilleActiver9": {"plugin":"Abeille","value":"N"},
    "AbeilleIEEE1": {"plugin":"Abeille","value":"00158D00021E113E"},
    "AbeilleIEEE_Ok1": {"plugin":"Abeille","value":"1"},
    "AbeilleIEEE_Ok10": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok2": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok3": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok4": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok5": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok6": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok7": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok8": {"plugin":"Abeille","value":"0"},
    "AbeilleIEEE_Ok9": {"plugin":"Abeille","value":"0"},
    "AbeilleParentId": {"plugin":"Abeille","value":"7"},
    "AbeilleSerialPort1": {"plugin":"Abeille","value":"\/dev\/ttyAMA0"},
    "AbeilleSerialPort10": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort2": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort3": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort4": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort5": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort6": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort7": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort8": {"plugin":"Abeille","value":"none"},
    "AbeilleSerialPort9": {"plugin":"Abeille","value":"none"},
    "AbeilleType1": {"plugin":"Abeille","value":"PI"},
    "AbeilleType10": {"plugin":"Abeille","value":"USB"},
    "AbeilleType2": {"plugin":"Abeille","value":"USB"},
    "AbeilleType3": {"plugin":"Abeille","value":"USB"},
    "AbeilleType4": {"plugin":"Abeille","value":"USB"},
    "AbeilleType5": {"plugin":"Abeille","value":"USB"},
    "AbeilleType6": {"plugin":"Abeille","value":"USB"},
    "AbeilleType7": {"plugin":"Abeille","value":"USB"},
    "AbeilleType8": {"plugin":"Abeille","value":"USB"},
    "AbeilleType9": {"plugin":"Abeille","value":"USB"},
    "active": {"plugin":"Abeille","value":"1"},
    "agressifTraitementAnnonce": {"plugin":"Abeille","value":"4"},
    "api": FILTERED,
    "blocageRecuperationEquipement": {"plugin":"Abeille","value":"Oui"},
    "blocageTraitementAnnonce": {"plugin":"Abeille","value":"Non"},
    "DbVersion": {"plugin":"Abeille","value":"20201025"},
    "deamonAutoMode": {"plugin":"Abeille","value":"1"},
    "deamonRestartNumber": {"plugin":"Abeille","value":"0"},
    "functionality::cron10::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cron15::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cron30::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cron5::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cron::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cronDaily::enable": {"plugin":"Abeille","value":"1"},
    "functionality::cronHourly::enable": {"plugin":"Abeille","value":"1"},
    "IpWifiZigate1": {"plugin":"Abeille","value":""},
    "IpWifiZigate10": {"plugin":"Abeille","value":""},
    "IpWifiZigate2": {"plugin":"Abeille","value":""},
    "IpWifiZigate3": {"plugin":"Abeille","value":""},
    "IpWifiZigate4": {"plugin":"Abeille","value":""},
    "IpWifiZigate5": {"plugin":"Abeille","value":""},
    "IpWifiZigate6": {"plugin":"Abeille","value":""},
    "IpWifiZigate7": {"plugin":"Abeille","value":""},
    "IpWifiZigate8": {"plugin":"Abeille","value":""},
    "IpWifiZigate9": {"plugin":"Abeille","value":""},
    "lastDeamonLaunchTime": {"plugin":"Abeille","value":"2022-05-03 07:41:36"},
    "monitor": {"plugin":"Abeille","value":"119"},
    "preventLQIRequest": {"plugin":"Abeille","value":"no"},
}

**Comment by tcharp38** [comment]
Salut @Bch78 
Ce message n'est qu'un message de debug.
Ca pose un souci ?

Pour info, a chaque demarrage on verifie (et met jour si necessaire) les database MySQL.
Donc c'est voulu.

A noter que j'ai fait evoluer cette partie dans la beta du moment.

Donc il y a un souci ?

**Comment by Bch78** [comment]
Non, à priori pas de souci.

J'étais juste étonné par le fait que l'on faisait systématiquement la tentative de mise à jour sans ensuite monter la DB de niveau car la ligne de mise à jour 
    "config::save('DbVersion', '20201122', 'Abeille');" 
était en commentaire.

Peut être fermé si pas de souci de votre côté.

En tout cas merci pour la réponse et tout le travail réalisé.

**Comment by tcharp38** [comment]
En fait j'essaie de regrouper une certain nombre de mise à jours avant d'incrementer la version.
Du coup le "save" est resté commenté un bout de temps.

Tu peux avoir une idée des modifs depuis la stable la.. https://kiwihc16.github.io/AbeilleDoc/Changelog.html#id1

Je clos.
A bientot
