### ISSUE TITLE
Support Lidl Smart Home: Ampoule LED Dimmable HG07878C

### ISSUE THREAD

**Issue by LoLoXim** [KiwiHC16/Abeille#2383]
Bonjour,
Je viens d'inclure avec Abeille les dernières ampoules LIDL LED Dimmable mais elles sont reconnues comme : "Abeille | Nouvel équipement identifié (Silvercrest Ruban a LED). 
Malgré la déclaration du type de device en "ZigbeeDimmablelight", les commandes ne fonctionnent pas.

Avez-vous besoin d'infos supplémentaires ?
Merci d'avance.
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8671959/discovery.zip)

**Comment by LoLoXim** [comment]
Au cas ou j'ajoute une photo sans fon
![ampoule-lidl](https://user-images.githubusercontent.com/64632719/167907509-c26cac1e-cdc2-4170-9bc5-ee99116fbf6a.png)
d

**Comment by tcharp38** [comment]
Salut @LoLoXim 

Voila un modele à tester.

- decompresser dans core/config/devices
- redemarrer demon Abeille
- refaire inclusion
- tester
- faire un résumé de ce qui est bon/pas bon

[TS0502A__TZ3000_49qchf10.zip](https://github.com/KiwiHC16/Abeille/files/8680077/TS0502A__TZ3000_49qchf10.zip)

**Comment by tcharp38** [comment]
@LoLoXim 
Des news ?

**Comment by LoLoXim** [comment]
Bonjour,

Mes excuses pour le temps passé... Ca fonctionne bien.

Point à revoir 
Bcp trop de commandes remontent dans la liste
l'image n'est pas fonctionnelle
Pas de widget dans le dashboard Jeedom

Je reviendrai vers toi avec ces informations dès que j'aurai le temps de m'y pencher. Merci pour le travail.

**Comment by LoLoXim** [comment]
Merci pour le travail effectué

**Comment by tcharp38** [comment]
Tu sembles dire qu'il y  a des soucis alors je reouvre.
Peux tu basculer sur la beta pour profiter de toutes les dernieres evolutions ?

**Comment by LoLoXim** [comment]
bonjour, comment je bascule sur la beta ?

**Comment by tcharp38** [comment]
Je l'ai pas sous les yeux mais la doc, chapitre installation donne les infos

**Comment by tcharp38** [comment]
https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by LoLoXim** [comment]
Je te joins les infos du manuel
![001](https://user-images.githubusercontent.com/64632719/192136645-34e9aac4-b24b-4df3-a165-8f17bfe46581.jpg)
![002](https://user-images.githubusercontent.com/64632719/192136646-14884422-d883-4667-a967-026608b7e089.jpg)
![003](https://user-images.githubusercontent.com/64632719/192136647-b6be7051-6a14-41f9-9e86-55130f6947c4.jpg)

**Comment by LoLoXim** [comment]
J'ai basculer sur la beta ça fonctionne.
Je vais tester à nouveau ce weekend, couplé au capteur de mouvement et je vous fait un retour. Merci.

**Comment by tcharp38** [comment]
Salut @LoLoXim 
Peut on clore ce sujet ou il reste de points a travailler ?

**Comment by tcharp38** [comment]
Je ferme ce sujet sans vie.
A réouvrir si qqn est interessé.
