### ISSUE TITLE
Support ampoule E27 RGB Eglo/Awox (id = TLSR82xx, AwoX)

### ISSUE THREAD

**Issue by ValFaure** [KiwiHC16/Abeille#2384]
Bonjour,

Serait-il possible d'inclure une ampoule E27 RGB de marque "Eglo" dans Abeille ?

modelId : TLSR82xx
manufId : AwoX

avec le discovery : [discovery.txt](https://github.com/KiwiHC16/Abeille/files/8672551/discovery.txt)
 
Ampoule achetée à Brico Dépot et très similaire aux ampoules Lexman de Leroy Merlin. 
J'ai d'ailleurs réussi à la faire fonctionner plutôt bien en renommant le modèle .json créé pour l'issue #2295 , seulement il n'y a pas de commandes On/Off/Toggle/Etat/Level dans ce modèle, et la commande "White" donne une couleur orange. Tout le reste est nickel.

Merci d'avance sur le temps que vous pourrez y consacrer !

**Comment by tcharp38** [comment]
Salut @ValFaure 
Voila un modele à decompresser dans core/config/devices
puis 
- redemarrer demon Abeille
- refaire inclusion
- tester
- faire un résumé de ce qui est bon/pas bon

Merci
[TLSR82xx_AwoX.zip](https://github.com/KiwiHC16/Abeille/files/8679904/TLSR82xx_AwoX.zip)

**Comment by ValFaure** [comment]
Merci pour ce retour rapide !

Tout est bon dans ce modèle mais il n'y a plus la gestion des couleurs qui fonctionnait lorsque je me basais sur le modèle LXEK-1-Adeo de l'issue #2295

Si tu peux du coup inclure les commandes de couleur dans TLSR82xx_AwoX tout sera nickel.

Edit : je viens de voir que l'image de l'objet n'est plus bonne. Le .json indique "icon": "Generic-E27" qui ne semble pas exister. C'est ok si je choisis "BulbE27" dans la liste déroulante sur la page "Equipement" de l'objet

**Comment by tcharp38** [comment]
Rien sur la couleur car je viens de voir que le discovery pour le cluster "0300" est vide.
Comment l'as tu généré ? Si via l'assistant, tout était au "vert" ?

Pour l'icone, ne t'inquiete pas. J'ai fait qq updates pour normaliser les noms. Ca va venir avec la prochaine beta.

**Comment by ValFaure** [comment]
Oui j'ai fait le discovery via l'assistant. Je viens de retester et en effet cela reste orange pour le cluster "0300". Cela veut dire que l'ampoule n'annonce pas son support pour les commande de la couleur c'est ça ? Est-ce que c'est possible que cela s'annonce sur un autre cluster ?

En tout cas cela fonctionne plutôt bien avec avec la partie des commandes de couleur du modèle LXEK-1_Adeo, donc ça me va.

**Comment by tcharp38** [comment]
Quelle partie as tu ajouté du coup ?
Peux tu me filer ton modèle ?

**Comment by ValFaure** [comment]
J'ai copié les blocs de "Color Mode" jusqu'à la fin au "Bind 0300-ToZigate"
Ca donne ça : [TLSR82xx_AwoX_modif.zip](https://github.com/KiwiHC16/Abeille/files/8694568/TLSR82xx_AwoX_modif.zip)

**Comment by tcharp38** [comment]
Bon je l'ai repris tel quel pour la prochaine beta.
Pas sur que tout soit necessaire mais je te laisse refaire une passe.. ne doivent etre visibles que les boutons ou infos qui font du sens pour ce periph.

**Comment by ValFaure** [comment]
Tel quel tout est parfait. Toutes les commandes fonctionnent et remontent les bonnes infos (même toutes celles liées à la couleur). 

Au niveau de l'affichage sur le Dashboard j'ai laissé par défaut et c'est suffisant. Il y a les actions de base + les 4 boutons pour les modes couleur (White, Red, Green, et Blue).

Reste la commande White qui avec les valeurs X et Y toutes les 2 à 0x6000 donne un orange au lieu d'un blanc. Il faudrait que je teste des paramètres différents dans le .json. 
D'ailleurs est-ce qu'il y a un moyen plus simple d'envoyer des valeurs X et Y à l'ampoule sans modifier le .json ?

En tout cas si c'est bon pour toi on peut clôturer l'issue.

**Comment by tcharp38** [comment]
Si la couleur n'est pas bonne on cloture pas. Je prefere que ce soit propre.
Tu peux ajouter cette commande dans ton JSON et faire des essais. Ca permet de choisir directement la couleur

            "Set RGB": {
                "use": "setRGB",
                "isVisible": 1,
                "nextLine": "after"
            },

Mais sinon ca serait effectivement bien qu'on puisses, via la page EQ/avancé, tester differentes valeurs.
Je vais ajouter ça

**Comment by tcharp38** [comment]
Voila. Ca sera dispo dans la prochaine beta

![image](https://user-images.githubusercontent.com/35221038/168767574-3bdebcf5-c553-4138-8bd8-5aa0aefab972.png)

**Comment by ValFaure** [comment]
Merci pour la commande Set RGB. Du coup j'ai pu trouver les valeurs correctes pour X et Y pour la commande White : 

"White": {
                "use": "zbCmd-0300-MoveToColor",
                "params": "X=4F6E&Y=5391",
                "isVisible": "1"
            },

Maintenant tout est bon ! Merci encore pour ta réactivité !

**Comment by tcharp38** [comment]
Ok merci
Du coup voila le modele officiel qui sera dans la prochaine beta => 220531-BETA-1

[TLSR82xx_AwoX.zip](https://github.com/KiwiHC16/Abeille/files/8714605/TLSR82xx_AwoX.zip)

Je clos.
A réouvrir si soucis.
