### ISSUE TITLE
Contrôleur d'arrosage - WOOX (id = TS0101, _TZ3210_eymunffl)

### ISSUE THREAD

**Issue by Sososoja** [KiwiHC16/Abeille#2385]
Bonjour, 

Avec l'arrivée du printemps j'ai acheté un contrôleur d'arrosage 
"https://www.planete-domotique.com/controleur-d-arrosage-intelligent-on-off-zigbee-3-0-woox.html".
Je le trouve dans la ruche, mais il n'est pas reconnu.
Si quelqu’un peut m'aider, ci joint le fichier discovery

Merci à vous

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8689444/discovery.zip)

**Comment by tcharp38** [comment]
Salut @Sososoja 

[TS0101__TZ3210_eymunffl.zip](https://github.com/KiwiHC16/Abeille/files/8692595/TS0101__TZ3210_eymunffl.zip)

A decompresser dans core/config/devices
puis redemarrer demon Abeille
et refaire inclusion

Il me faudra une image PNG sans arriere plan pour mettre en icone.

**Comment by Sososoja** [comment]
Salut tcharp38,

Voici une image pour l’icône

Merci encore

![TS0101  TZ3210](https://user-images.githubusercontent.com/105510886/168421929-b9acb2a0-1672-4d6d-9e0a-246e3fbd93ed.png)

**Comment by tcharp38** [comment]
Merci pour l'image.
Quel est le status ?

**Comment by Sososoja** [comment]
Ça fonctionne nickel, j'ai bien on et off et le retour d'état

**Comment by tcharp38** [comment]
Super ! Tout est dans la dernière bêta qui sera dispo dans qq heures.

Penses tu qu'il y a une durée limite d'ouverture ? Si la zigate ou la boxe domotique tombent alors que la vanne est ouverte, y a t il une sécurité ?

**Comment by Sososoja** [comment]
OK cool, merci

J'ai justement fais du mortier ce matin, et j'ai branché le jet sur la vanne qui du coup est resté allumé durant 3h.
La je viens de faire un test, j'ai allumé, la vanne et redémarrer jeedom, au redémarrage le retour passe à fermé, alors qu'elle était toujours en service. mais en appuyant sur off elle c'est bien coupé.
J'ai fais un scénario avec une tempo et j'ai toute la domotique sur onduleur, ça devrai pas arriver.

Si tu veux d'autres infos, hésite pas.

**Comment by tcharp38** [comment]
Merci pour ton retour. 
Je pense qu'il manque des sécurités sur ce genre d équipement donc il faut sécuriser la box. 

Du coup on peut clore ce sujet ?

**Comment by Sososoja** [comment]
Oui, il faudra pouvoir mettre une tempo max dans le module.
J'avais un truc un bluetooth, pas très pratique mais au moins la prog était dans le module.
Je vais recevoir des modules genre télérupteur pour  de l'éclairage, je reviendrais surement vers toi.
Oui tu peut clore le sujet, merci encore
