### ISSUE TITLE
Support Saswell Electrovanne SAS980SWT-7-Z01 (id = TS0601, _TZE200_81isopgh)

### ISSUE THREAD

**Issue by MaelFr** [KiwiHC16/Abeille#2388]
Hello,

Je cherche à inclure [ce nouvel équipement](https://www.domadoo.fr/fr/peripheriques/5886-saswell-electrovanne-et-programmateur-d-arrosage-connecte-zigbee-mesure-de-consommation.html).
Apparemment c'est du Tuya, j'ai trouvé quelques infos [ici](https://github.com/zigpy/zha-device-handlers/issues/1556#issuecomment-1122919421) qui semblent intéressantes, mais je n'ai pour le moment pas réussi à assembler tous les morceaux pour que ça fonctionne.

Je joins le discovery et l'image.

![sas_sas980_1_1-removebg-preview](https://user-images.githubusercontent.com/13976666/169653256-40d3f0b2-284c-4f0e-a085-17c888fb1937.png)
[discovery_sas980swt.zip](https://github.com/KiwiHC16/Abeille/files/8747666/discovery_sas980swt.zip)

**Comment by tcharp38** [comment]
Ils font vraiment tout pour nous compliquer l'integration.
Un controle d'electro vanne pourrait se faire facilement via le cluster 0006/Onoff mais la il n'est pas supporté.
Donc il faut décoder/comprendre l'utilisation non standard avec le cluster EF00.

Il y a un bouton qui permet d'activer la vanne manuellement ?

**Comment by MaelFr** [comment]
Oui il y a un bouton qui permet de faire ouvert/fermé et la synchro en restant appuyé 3 sec.

J'ai tenté un 0006/OnOff en tout premier avant de le synchro, sans succès évidemment. J'ai compris pourquoi en regardant le discovery ensuite et en faisant quelques recherches.

**Comment by MaelFr** [comment]
Ci-joint des logs lorsque j'appuie sur le bouton. Le dernier appui ferme la vanne, l'avant dernier l'ouvre.
L'adresse est `74DF`

[AbeilleLogs-220521.tar.gz](https://github.com/KiwiHC16/Abeille/files/8748375/AbeilleLogs-220521.tar.gz)

**Comment by MaelFr** [comment]
J'ai réussi \o/ je commande et j'ai le retour d'état.
Je prépare la PR.

**Comment by MaelFr** [comment]
Il semblerait qu'il y a deux DP (01 et 0C) qui retournent la même info sous deux format différents, c'est possible ?

```
1963|[2022-05-22 10:17:01]   Dp=01, DpType=01, Func=00, DpLen=01: Unrecognized DP (data=01)
1974|[2022-05-22 10:17:01]   Dp=0C, DpType=04, Func=00, DpLen=01 => On/Off=1/ON
```

**Comment by MaelFr** [comment]
Il semblerait que cette vanne existe aussi dans les marques [RTX](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5248) et [Lidl](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4958) avec des noms légèrement différents.

**Comment by tcharp38** [comment]
J'ai mergé ton PR avec qq modifs.
Je cherche à eviter la multiplication des modifs de code. Donc par ex la Parser-Tuya contient des fonctions generiques "rcvValue" & "rcvValueDiv". Tu verra.

Il faut que je trouve le meme type de combine pour Cmd-Tuya, toujours dans l'idée de ne plus toucher le code, juste les modeles.

Du coup que manque t'il pour ce support ?

**Comment by NilkOne** [comment]
Bonjour,
J'ai également acheté une électrovanne Saswell sas980swt-7-z01, pouvez-vous m'aider pour l'intégrer dans Zigbee2MQTT ? (je l'utilise via Home Assistant)

On peut voir sur cette page que c'est [supporté pour un modèle équivalent](https://www.zigbee2mqtt.io/devices/ZVG1.html), par contre la Saswell est affiché Not supported dans Zigbee2MQTT

**Comment by tcharp38** [comment]
Salut @NilkOne 
Désolé, ce git est spécifique plugin "Abeille" (pour Jeedom), et j'avoue que je ne connais rien à Zigbee2MQTT.
La signature de ton modele est differente de l'équivalent, meme si fonctionalités et visuel identiques. Reste à trouver ou ca se cache de ton côté.

**Comment by MaelFr** [comment]
@tcharp38 Tout fonctionne correctement pour moi.
Je viens de recevoir un message du vendeur :
```
Suite à une erreur de production du fabricant, il semblerait que le contrôleur d'arrosage Saswell que vous avez reçu n'ait pas la mesure de consommation.
Si cela est bloquant pour vous, nous pouvons vous proposer une reprise pour échange contre une version avec mesure de consommation.
```
Du coup c'est normal que je n'arrive pas à récupérer la conso. Je fais l'échange et je vois si y'a besoin d'autre chose.

@NilkOne désolé, je ne pourrai pas t'aider non plus

**Comment by tcharp38** [comment]
Ok on attend ton echange et ton status alors.

**Comment by GitMouth** [comment]
Salut, je cherche à faire fonctionner cet appareil sur Home Assistant, via deCONZ, qui fonctionne avec des fichiers de définition DDF, et pour identifier les variables, données etc, il y a des "endpoints" qui intègrent des "clusters" composés d'attributs. souvent tout ça en hexa, vous avez peut-être quelque chose de similaire ici ?

**Comment by tcharp38** [comment]
Salut @GitMouth 
"endpoints", "cluster", "attributes" .. tout ca vient du standard Zigbee donc oui qq part on joue avec.
Mais hors sujet. Qui plus est je n'ai aucun idée des besoins de HA ou deConz. Donc sans question + précise, je ne pourrais meme pas aider. Il doit y avoir un forum dédié qq part.

**Comment by GitMouth** [comment]
> Salut @GitMouth "endpoints", "cluster", "attributes" .. tout ca vient du standard Zigbee donc oui qq part on joue avec. Mais hors sujet. Qui plus est je n'ai aucun idée des besoins de HA ou deConz. Donc sans question + précise, je ne pourrais meme pas aider. Il doit y avoir un forum dédié qq part.

Ok, je suis assez récent sur le sujet, sur l'aspect dev je veux dire.
Ce que je recherche, c'est "l'adressage" (si c'est le bon terme) pour retrouver les valeurs de mesure de consommation, de niveau de batterie, et pour ouvrir / fermer la vanne. Pour l'instant je n'ai que le retour d'état de la vanne. Une fois que j'ai ces infos je configuré un fichier DDF, ça me créée des sensers / entités dans deCONZ/HA.

**Comment by tcharp38** [comment]
Je viens de regarder le modele Abeille actuel. Il se trouve que cet equipement ne suit aucun "standard" Zigbee comme de + en + chez Tuya. Il passe par un cluster "privé" Tuya (EF00, donc ils font ce qu'ils veulent dedans).

Bref c'est toujours galère de trouver comment controler ou recuperer une info dans ce monde.
Un aperçu de doc Tuya : https://developer.tuya.com/en/docs/iot-device-dev/tuya-zigbee-universal-docking-access-standard?id=K9ik6zvofpzql

**Comment by GitMouth** [comment]
> Je viens de regarder le modele Abeille actuel. Il se trouve que cet equipement ne suit aucun "standard" Zigbee comme de + en + chez Tuya. Il passe par un cluster "privé" Tuya (EF00, donc ils font ce qu'ils veulent dedans).
> 
> Bref c'est toujours galère de trouver comment controler ou recuperer une info dans ce monde. Un aperçu de doc Tuya : https://developer.tuya.com/en/docs/iot-device-dev/tuya-zigbee-universal-docking-access-standard?id=K9ik6zvofpzql

Ok merci je vais poursuivre mes recherches, déjà j'ai un cluster. Si quelqu'un d'autre passe par ici par hasard, n'hésitez pas à contribuer merci a tous

**Comment by tcharp38** [comment]
@MaelFr 
Salut.
Des news ?

**Comment by MaelFr** [comment]
Le nouveau m'est expédié aujourd'hui.

**Comment by NilkOne** [comment]
Bonjour @MaelFr , as-tu réussi à intégrer le suivi de consommation de la nouvelle vanne ?

**Comment by MaelFr** [comment]
Oui, la config que j'avais prévue fonctionne.
Il faut juste que je fasse une petite modif, la conso remonte en décilitres et pas en litres.

**Comment by NilkOne** [comment]
@MaelFr, chouette tu sais si c'est basé sur Zigbee2mqtt ?

Tu reçois une valeurs tous les combiens de secondes ? Précis à 0,1 litre près donc ?

**Comment by MaelFr** [comment]
Je ne pense pas pour mqtt.

J'ai l'impression que ç ne remonte que toutes les minutes. Oui, précis à 0,1 litre.

**Comment by tcharp38** [comment]
@MaelFr 
Du coup tu me résumes ce qu'il manque ou a corriger avant cloturer ce sujet ?
Merci

**Comment by MaelFr** [comment]
@tcharp38 
Je pense qu'il faut ajouter ça dans le fichier de conf `TS0601__TZE200_81isopgh.json` à la commande `Measured value` :
```
"calculValueOffset" : "#value#/10",
"historizeRound": 1
```

**Comment by tcharp38** [comment]
Voila le modele corrigé.
Je vous laisse tester (reinitialiser via la page EQ/Avancé)
[TS0601__TZE200_81isopgh.zip](https://github.com/KiwiHC16/Abeille/files/9542166/TS0601__TZE200_81isopgh.zip)

**Comment by tcharp38** [comment]
@MaelFr 
Du nouveau ?
Peut on clore ce sujet ?

**Comment by MaelFr** [comment]
Hello,

J'ai oublié d'envoyer le message, désolé.

Oui c'est tout bon pour moi.

Merci

**Comment by tcharp38** [comment]
Super.

Je clos.
Comme d'hab a reouvrir si pb restant sur ce device.
