### ISSUE TITLE
Support stores occultants IKEA TREDANSEN (id =TREDANSENblock-outcellulblind, IKEAofSweden)

### ISSUE THREAD

**Issue by dsergent** [KiwiHC16/Abeille#2392]
Bonjour,

Serait-il possible d'ajouter le support des stores IKEA TREDANSEN ? J'ai pu les inclure en utilisant la même configuration que les FYRTUR.

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8777535/discovery.zip)
![TREDANSENblock-outcellulblind](https://user-images.githubusercontent.com/32458402/170451405-7b435cf1-fc5f-4335-b3c4-8ddd1b222e26.jpg)

Merci !

**Comment by dsergent** [comment]
Voici la configuration que j'utilise avec une proposition d'image.
[TREDANSENblock-outcellulblind.zip](https://github.com/KiwiHC16/Abeille/files/8777687/TREDANSENblock-outcellulblind.zip)

**Comment by tcharp38** [comment]
Salut @dsergent 
Peux tu me générer un discovery ? https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by tcharp38** [comment]
Salut @dsergent

Voila le modele officiel que je vais pousser pour la prochaine beta.

A decompresser dans core/config/devices,
puis redemarrer Abeille
refaire inclusion

[TREDANSENblock-outcellulblind_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/8799467/TREDANSENblock-outcellulblind_IKEAofSweden.zip)

**Comment by dsergent** [comment]
Hello. 
Merci beaucoup !
Ca fonctionne parfaitement.
Denis

**Comment by tcharp38** [comment]
Ok, tout sera dans la prochaine beta => 220531-BETA-1

Je clos.
A réouvrir si soucis.
