### ISSUE TITLE
Depuis 220515-BETA-1: Conflit de nom si inclusion de 2 équipements du même type

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2393]
Hello,

J'ai vu que suite à une récente version de la beta les périphériques sont créés avec un nom intelligible plutôt qu'un simple "Abeille1-ID", ce qui est plutôt cool.

Par exemple les capteurs de température/humidité Xiaomi ronds sont créés avec le nom : "Xiaomi Temperature Rond". 

Hier j'ai inclu un de ces capteurs et je l'ai immédiatement renommé.
Aujourd'hui, je viens d'essayer d'en inclure deux autres à la suite sans renommer le premier et cela a généré l'erreur suivante à la deuxième inclusion : 

> deamon(): Exception [MySQL] Error code : 23000 (1062). Duplicate entry 'Xiaomi Temperature Rond-1' for key 'unique' : UPDATE `eqLogic` SET `id` = :id, `name` = :name, `logicalId` = :logicalId, `generic_type` = :generic_type, `object_id` = :object_id, `eqType_name` = :eqType_name, `isVisible` = :isVisible, `isEnable` = :isEnable, `configuration` = :configuration, `timeout` = :timeout, `category` = :category, `display` = :display, `order` = :order, `comment` = :comment, `tags` = :tags WHERE id = :id

Je suppose qu'il y a un conflit entre les deux derniers dans la base de données Abeille. 

Voici les logs : 
[AbeilleLogs-220526.tar.gz](https://github.com/KiwiHC16/Abeille/files/8781430/AbeilleLogs-220526.tar.gz)

**Comment by tcharp38** [comment]
Merci pour ce retour. Ça ne me surprend pas en fait. Boulette de ma part à corriger dans la semaine.

**Comment by tcharp38** [comment]
J'ai choisi de remettre l'ID dans le nom.
Du coup ca donnerait "Xiaomi Temperature Rond - 12" si l'ID est 12.

Peux tu tester avec le fichier suivant à decompresser dans core/class ?
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8803490/Abeille.class.php.zip)

**Comment by eoeir** [comment]
J'ai déployé le fichier Abeille.class.php et redémarré Abeille mais j'ai toujours la même erreur à l'inclusion du 2eme équipement.

[AbeilleLogs-220601.tar.gz](https://github.com/KiwiHC16/Abeille/files/8811402/AbeilleLogs-220601.tar.gz)

**Comment by tcharp38** [comment]
Zut. Effectivement je vois encore des erreurs.

Nouveau code:
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8812548/Abeille.class.php.zip)

**Comment by eoeir** [comment]
Testé et validé ;) 

![image](https://user-images.githubusercontent.com/71673288/171479647-85a49d06-7c88-40e1-ae52-9b8f81fd1a6f.png)

**Comment by tcharp38** [comment]
Parfait. 
Donc pour résumer plutot que "Abeille<X>-<ID>", le nommage est maintenant "<type> - <ID>".
Je clos une fois que la nouvelle beta est poussée.
Merci pour ton aide.
