### ISSUE TITLE
Prise commandée Blitzwolf SHP13 (id = TS011F, _TZ3000_amdymr7l)

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2396]
Bonjour,
je souhaiterais inclure une prise commandée Blitzwolf SHP13 mais qui est reconnue en Yagusmart Tuya ZigBee Smart Switch - 611
Normalement, il y a une mesure puissance
Voici le fichier discovery:
[discovery (7).zip](https://github.com/KiwiHC16/Abeille/files/8827625/discovery.7.zip)

Merci

**Comment by tcharp38** [comment]
Salut @Proft1972 

Elle correspond à ca https://zigbee.blakadder.com/BlitzWolf_BW-SHP13.html ?

A tester
[TS011F__TZ3000_amdymr7l.zip](https://github.com/KiwiHC16/Abeille/files/8847850/TS011F__TZ3000_amdymr7l.zip)

**Comment by Proft1972** [comment]
Salut @tcharp38 .
Ca fonctionne mais ce fichier n'était pas dans abeille , il a fallu que je le rajoute, c'est normal?

**Comment by tcharp38** [comment]
Yes.
La signature est differente donc 2 options
- nouveau modele (celui que j'ai ajouté)
- ou ca correspond à un autre modele avec une signature "alternate" => "alternateIds"

**Comment by tcharp38** [comment]
Hello @Proft1972 
Que fait on avec ce sujet ?

**Comment by Proft1972** [comment]
Salut @tcharp38 Maintenant la prise fonctionne depuis que j'ai ajouté ton nouveau fichier cela marchera t il avec une installation neuve?

**Comment by tcharp38** [comment]
Hello.
Oui ca devrait car j'ai poussé dans la beta en meme temps.

**Comment by Proft1972** [comment]
hello @tcharp38 ,
alors on peut cloturer

**Comment by tcharp38** [comment]
Ok, cool.
A reouvrir si besoin.
