### ISSUE TITLE
impossible d'ajouter des prises Tuya TS011F

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2398]
Salut,
Je viens de recevoir 4 prises Tuya (j'en ai déjà 2 sur Jeedom).
Aucune des 4 ne s'intègrent.
J'ai réessayé 2 fois ce matin (la dernière fois à 6h26, 27), j'ai vue passer des message d'erreur dans le Parser

Pour hoter le doute de la zigate, j'ai intégré avec succé de nouveau module Aqara hier soir et sans souci.
C'est vraiment les prise Tuya qui pose PB.

Je mets le package de log. Un jour faudrait prendre le temps de m'expliquer ce qu'il faut chercher/regarder pour aider à faire une première analyse.
[AbeilleLogs-220610.tar.gz](https://github.com/KiwiHC16/Abeille/files/8875784/AbeilleLogs-220610.tar.gz)

**Comment by Jake309** [comment]
Je suis repasser sur la stable. J'ai réussi à en ajouter une. 
Par contre, j'ai le même on avec du aqara. Impossible a ajouter. 
Doit y avoir un souci quelque part

**Comment by Jake309** [comment]
Salut @tcharp38 ,
Je pense qu'il  y a un pb plus conséquent.
Sur mes 10 nouveaus équipements (4 prise tuya et diverse aqara, inter, porte et mouvement) j'ai réussi à en intégré 2, le detecteur ya un moment, mais le prise tuya j'ai réussi en stable après énormément de tentative. 
Tout les autres, pas moyen. 
Par contre, j'ai l'impression que les tentatives d'inclusion se soldent par l'apparition d'équipement fantomes (en lien avec mes dernier commentaire sur l'issue dédié)
Qu'en penses tu ?
![image](https://user-images.githubusercontent.com/49479084/173222018-9df4bf19-ac81-4f13-a41f-cfb96951fd45.png)
[AbeilleLogs-220612.tar.gz](https://github.com/KiwiHC16/Abeille/files/8885380/AbeilleLogs-220612.tar.gz)

**Comment by tcharp38** [comment]
Salut @Jake309 
Sur ton premier log je vois ca

**[2022-06-10 06:31:39] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=1AD0, DstAddrMode=02, DstAddr=0000
[2022-06-10 06:31:39]   Device Announce: SQN=00, Addr=1AD0, IEEE=00124B00251E0E19, Cap=8E
[2022-06-10 06:31:39]   Handled by decode004D
[2022-06-10 06:31:39] Abeille1, Type=004d/Device announce, Addr=20EA, ExtAddr=0400536D04015D6B, MACCapa=B4
[2022-06-10 06:31:39]   WARNING: Corrupted message => ignoring
[2022-06-10 06:31:39] Abeille1, Type=8012/APS data confirm, Status=00, Addr=1AD0, SQNAPS=1C, NPDU=00, APDU=00**

Il s'agit du bug zigate v2, FW 3.21
voir https://github.com/fairecasoimeme/ZiGatev2/issues/36

En gros tu es toujours sur le souci que tu as toi meme entré: https://github.com/KiwiHC16/Abeille/issues/2368#

En ligne avec ca ?

**Comment by Jake309** [comment]
Ce que je trouve ultra bizarre, c'est que j'ai cherché à intégrer pendant 3 jours :
4 prise tuya
3 détecteur de porte aqara
2 sonde de température aqara
2 détecteur de mouvement aqara
1 inter aqara (le petit carré avec bouton rond)
Et que je n'ai réussi qu'à intégrer 1 sonde de température, 1 prise tuya

**Comment by Jake309** [comment]
Fausse manip en écrivant...

C'est quand même étrange de pas réussir à intégrer les tuya qui sont simple et le 2eme température. 
Les porte et mouvement, ok, c'est un peu chiant, encore que mouvement il ne faut pas trop de tentative.
Mais là ça fait beaucoup d'échec

**Comment by tcharp38** [comment]
Le log est explicite pour moi. Bug zigate v2. Je te suggère de tenter le Fw 3.22 rc qui est sur le site zigate. Ça n'est pas la version finale mais ça devrait corriger le souci que tes logs montrent.

Je ne vois rien qui mette en évidence une telle régression du plugin Abeille.

Si tu as toujours une zigate v1, tu peux confirmer ou contredire mon point de vue.

**Comment by Jake309** [comment]
Salut @tcharp38 ,
Je viens de faire la mise à jour en 3.22 rc, et j'ai un souci sur le mode inclusion, la led clignote 7 fois puis s'arrête.
Dans la parser, on voit que le mode inclusion passe inactif de quelques secondes à une minute environ

[AbeilleLogs-220624 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/8973678/AbeilleLogs-220624.1.tar.gz)

**Comment by Jake309** [comment]
Je viens de repasser sur la 3.21 car une latence fole etc
C'est pas abeille, je pense que la 3.22 rc est pas très propre.
actuellement j'ai la led qui clignote 4min et tout réagis très bien.

J'ai une question, avec le bug et les équipements fantomes, est ce que ca pourrait jouer sur le nombre max d'équipement sur la zigate ? 
Je m'explique, comme je n'arrive plus à faire d'inclusion, je me demande si j'ai pas atteint le max de la zigate a cause du bug. il y a un moyen de vérifier le nombre d'équipement connecté à la zigate ?

**Comment by tcharp38** [comment]
Salut @Jake309 
Oui ce que tu dis fais du sens.
La zigate merde dans les adresses internes et du coup si elle considere chaque mauvaise adresse comme un vrai device, la table peut arriver à la fin.

Je vais regarder le log 3.22rc quand meme

**Comment by tcharp38** [comment]
@Jake309 
on fait quoi de ce vieux sujet ? Les choses ont evolué ?

**Comment by Jake309** [comment]
Oula, bien vieux
On peut clore, désolé je l'ai pas vue trainer.
Plus de souci
