### ISSUE TITLE
Disparition des photos SONOFF en stable

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2399]
Pour tester les inclusions qui ne fonctionne pas, je suis repasser en stable le temps d'une soirée et nuit.
J'ai peu remarquer que les icone SONOFF n'apparaissaient plus contrairement à la beta.
J'ai mis qu'une partie de mes équipements, mais c'est vraiment l'intégralité de la marque SONOFF
Je ne sais pas si c'est un bug, ou juste moi. 
Dans le doute, je préfère communiquer pour que tu le sache

![image](https://user-images.githubusercontent.com/49479084/173222226-8473afd7-99c7-490c-bbdf-8c5fcb08b0d1.png)
![image](https://user-images.githubusercontent.com/49479084/173222228-d76894b9-d263-4d48-96b7-2b970dc6a981.png)

**Comment by tcharp38** [comment]
Salut @Jake309 
Sauf erreur tu as fait des essais en beta.
Comment es tu revenu sur la stable ?
En fait pour revenir "en arriere" il faut absolument restaurer un backup et non pas changer juste "beta" en "stable".
Ca doit venir de la.

Je compte faire une nouvelle stable mardi ou mercredi.

**Comment by Jake309** [comment]
Oui en effet. J'ai été sur le market et j'ai installé la stable ^^
Ça explique le souci ^^

**Comment by tcharp38** [comment]
@Jake309 
On peut clore ce sujet ?
Tu as basculé sur la derniere stable ou beta ?

**Comment by Jake309** [comment]
Oui oui, j'avais fait l'erreur de manip que tu as cité.
Ce week end je m'occupe de ma zigate pour les autres sujets ;)
