### ISSUE TITLE
Check that with a fresh install default global parameters are used.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#24]
Lors de la derniere install from fresh, le port com n'etait pas defini.

Le definir dans les paramètres globaux du plugin et sauvegarder.

**Comment by Marc--** [comment]
Je confirme avoir eu le même problème lors d'une update. J'ai du ajouter a la main le "/dev/ttyUSB0" dans la conf du plugin.

**Comment by KiwiHC16** [comment]
Fresh install (Supprime Abeille, installation Abeille) et les parametres ne sont pas dans la base.
Apres sauvegarde, ils sont dans la base.
Le demarrage du demon fait un enregistrement aussi.
Mettre partout dans le code config::key(x,y,"default value pour etre sure de ne pas avoir le probleme");

**Comment by KiwiHC16** [comment]
Je ne vois plus de probleme
