### ISSUE TITLE
Perte aléatoire de communication avec un equipement

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#240]
Problematique différente du cas #210. Ici le capteur n'envoie plus rien. Exemple ouverture de porte et rien sur la radio.

**Comment by KiwiHC16** [comment]
Ce problème semble plus important/fréquent pour les équipements en limite de couverture. 
La ZiGate ne recoit plus d'info d'un équipement "Door Sensor". Si ouverture du capteur, on ne voit rien sur la radio. Un appui court sur le bouton lateral provoque un "network join" et un allumage court de la led bleue. Si le réseau est ouvert, le capteur fait un join et recoit une nouvelle adresse. Et tout repart comme avant.

**Comment by KiwiHC16** [comment]
@handfreezer, peux tu faire: http://[IP]/plugins/Abeille/Network/AbeilleLQI_Map.php 
Est ce que le capteur 'perdu' apparait dans la liste ?
Il faut le master.

Il faut que je fasse la doc...

**Comment by handfreezer** [comment]
Je regarde ce soir ou mercredi soir au pire. Merci de te pencher sur le cas.

**Comment by handfreezer** [comment]
Note: jai le constat avec des equipements qui se trouve en vue direct a 1m50 ( même piece) et un lot de capteur dans une boite a moins de 30 cm.... je ne pense donc pas quil s'agit dun souci de distance.

**Comment by KiwiHC16** [comment]
Quelles sont tes observations ? Des logs ? des sniffs ?
Perts tu un ou tous les équipements en même temps ?

**Comment by handfreezer** [comment]
Résultat de l'URL AbeilleLQI_Map.php:
![image](https://user-images.githubusercontent.com/2912752/39451343-ac0444c4-4cce-11e8-8681-ee643a025012.png)


Cela ne ressemble pas à mes sensors

**Comment by KiwiHC16** [comment]
C'est normal, je vais faire la doc ce soir.

**Comment by handfreezer** [comment]
Alors voici ce que je peux donner comme info/constat:
zone0 : vue directe avec la zigate (entre 30cm et 150cm, pas de mur, pas d'écran: air libre seulement)
zone1 : un mur
zone2 : maximum deux murs, plus éloigné
zone10: 1 à 2 murs, et parfois en transversal
=>uniquement en xiaomi, il y a un mélange de capteur température/humidité, temp/hum/pression, deux radar, détecteur de porte.

Note importante : j'ai plus de périphérique que cette liste, mais mon écran est pas assez grand, il doit y en avoir entre 5 et 10 en plus.

![image](https://user-images.githubusercontent.com/2912752/39451877-7fb85598-4cd0-11e8-8854-fbc77e6c9440.png)

**Comment by handfreezer** [comment]
Le cosntat ou sensation que j'ai , c'est que tout d'un coup, je perds la com entre les capteur et la zigate : j'explique:
- quand un capteur marche, et que j'appuie brièvement sur son bouton, j'ai trois clignotements rapides bleu et une mise à jour dans jeedom
- quand un capteur "disparait", et que j'appuie brièvement sur son bouton , j'ai :
     - soit à la première pression 3 clignotements bleu puis à la seconde pression un seul clignotement long
     - soit un seul clignotement long tout de suite.

A noter qu'une fois en mode "clignotement" long, je ne peux pas "rappuyer" tout de suite sur le bouton pour avoir un nouveau clignotement, il faut que j'attende quelques secondes avant de pouvoir refaire la manip.

Enfin, une fois en mode clignotement long, si j'active le mode inclusion de la zigate, et que j'appuie longtemps sur le bouton du capteur, il s'appaire à nouveau, et c'est reparti mais avec un nouvel ID...

**Comment by handfreezer** [comment]
Pour ce qui logs et sniff, je t'avoue que je n'ai rien fais, car je ne sais pas trop quoi chercher, mais actuellement je suis dans un état où tout à sauté, donc je peux faire autant de test que voulu, et même en refaire la synchro sur certain.

**Comment by handfreezer** [comment]
J'ai ça en liste d'inventaire:
```
AbeilleParser 2018-04-30 23:55:23[DEBUG]Nombre d'abeilles: 17
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 0; ID : 00; Short Addr : a132; IEEE Addr: 00158d0001fd8f72; Power Source (0:battery - 1:AC): 00; Link Quality: 71
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 1; ID : 01; Short Addr : 2e01; IEEE Addr: 00158d0001bc23dd; Power Source (0:battery - 1:AC): 00; Link Quality: 90
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 2; ID : 02; Short Addr : 4d6c; IEEE Addr: 00158d0001c16470; Power Source (0:battery - 1:AC): 00; Link Quality: 201
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 3; ID : 03; Short Addr : bea1; IEEE Addr: 00158d0001fd8d5c; Power Source (0:battery - 1:AC): 00; Link Quality: 179
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 4; ID : 04; Short Addr : b047; IEEE Addr: 00158d0001fd8d74; Power Source (0:battery - 1:AC): 00; Link Quality: 75
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 5; ID : 05; Short Addr : 71c5; IEEE Addr: 00158d0001d6fa76; Power Source (0:battery - 1:AC): 00; Link Quality: 203
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 6; ID : 06; Short Addr : 1c3a; IEEE Addr: 00158d0001e52a65; Power Source (0:battery - 1:AC): 00; Link Quality: 173
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 7; ID : 07; Short Addr : 49b8; IEEE Addr: 00158d00017140e5; Power Source (0:battery - 1:AC): 00; Link Quality: 192
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 8; ID : 08; Short Addr : 4e63; IEEE Addr: 00158d0002276147; Power Source (0:battery - 1:AC): 00; Link Quality: 153
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 9; ID : 09; Short Addr : 3483; IEEE Addr: 00158d0002239f7a; Power Source (0:battery - 1:AC): 00; Link Quality: 201
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 10; ID : 0A; Short Addr : 01df; IEEE Addr: 00158d0001d707b1; Power Source (0:battery - 1:AC): 00; Link Quality: 192
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 11; ID : 0B; Short Addr : 2432; IEEE Addr: 00158d000223a616; Power Source (0:battery - 1:AC): 00; Link Quality: 182
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 12; ID : 0C; Short Addr : 1ad7; IEEE Addr: 00158d000227b700; Power Source (0:battery - 1:AC): 00; Link Quality: 192
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 13; ID : 0D; Short Addr : 716c; IEEE Addr: 00158d0001f26256; Power Source (0:battery - 1:AC): 00; Link Quality: 203
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 14; ID : 0E; Short Addr : d0f2; IEEE Addr: 00158d0001d70822; Power Source (0:battery - 1:AC): 00; Link Quality: 48
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 15; ID : 0F; Short Addr : 4d35; IEEE Addr: 00158d0001d6fb03; Power Source (0:battery - 1:AC): 00; Link Quality: 60
AbeilleParser 2018-04-30 23:55:23[DEBUG]Abeille i: 16; ID : 10; Short Addr : 23b8; IEEE Addr: 00158d0001d6e021; Power Source (0:battery - 1:AC): 00; Link Quality: 191
```

Truc suspect maintenant que je vois ça : ma liste de "santé" à plus de ligne que d'abeille...

**Comment by KiwiHC16** [comment]
Je viens de faire une mise à jour de la doc: https://github.com/KiwiHC16/Abeille/blob/master/Documentation/068_LQI.adoc

**Comment by KiwiHC16** [comment]
D'apres l'horaire d'arrêt des info le 23 à 21h30, j'aurai tendance à penser que tu as le problème #210 qui viendrait d'un soucis dans la lib client MQTT. Avec ce probleme, on ne voit plus de message dans le log Abeille. Un restart du plugin et ca doit re-marcher. As tu essayé un restart du plugin ?

**Comment by KiwiHC16** [comment]
Pour les clignotement des LED ne ne peut commenter. Mais je te confirme qu'un appui long provoque un "Leave" de l'équipement suivi d'un "Join" accepté sur ZiGate en mode inclusion et du coup une nouvelle adresse.

**Comment by KiwiHC16** [comment]
"ma liste de "santé" à plus de ligne que d'abeille...": c'est possible car le plug in crée des objets à chaque nouvelle adresse. Donc un équipement qui se déconnecte, reconnecter (appui long) crée deux objet dans Jeedom. Pour l'instant je ne "delete" rien dans Jeedom. Maintenant que je sais recuperer les adresses IEEE pour quasiement tous les équipements, je vais voir comment identifier le objet dans Jeedom qui n'existent plus dans réseau ZigBee. Mais je veux faire encore des tests avant...

**Comment by KiwiHC16** [comment]
As tu des messages comme ceux ci dans ton log abeille (pas AbeilleParser) avant de faire un restart plugin ?

```
[2018-05-01 00:45:42][DEBUG] : --- process a new message -----------------------
[2018-05-01 00:45:42][DEBUG] : Message ->Toggle<- sur CmdAbeille/db83/OnOff
[2018-05-01 00:45:42][DEBUG] : 16 : Client jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/db83/0006-0000', ... (1 bytes))
[2018-05-01 00:45:42][DEBUG] : --- process a new message -----------------------
[2018-05-01 00:45:42][DEBUG] : Message ->1<- sur Abeille/db83/0006-0000
[2018-05-01 00:45:42][DEBUG] : 16 : Client jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/db83/Time-TimeStamp', ... (10 bytes))
[2018-05-01 00:45:42][DEBUG] : --- process a new message -----------------------
[2018-05-01 00:45:42][DEBUG] : Message ->1525128342<- sur Abeille/db83/Time-TimeStamp
[2018-05-01 00:45:42][DEBUG] : 16 : Client jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/db83/Time-Time', ... (19 bytes))
[2018-05-01 00:45:42][DEBUG] : --- process a new message -----------------------
[2018-05-01 00:45:42][DEBUG] : Message ->2018-05-01 00:45:42<- sur Abeille/db83/Time-Time
```

**Comment by handfreezer** [comment]
un peu pris par le temps, j'apporte juste une précision : il n'y a aucun doublon dans la liste : j'ai bien autant de ligne que de périphériques physiques, (à chaque fois que j'ai réinclu un device, j'ai supprimé l'ancien). La liste retournée par la zigate (je ne connaissais pas la commande) est donc incomplète à priori.

Pour ceux de la liste, effectivement, un reboot semble résoudre le problème.

J'ai malgré tout donc un problème de perte d'équipement dans la liste de la zigate je pense.

Est-ce que l'on peut prévoir une sorte de crontab qui récupère la liste régulièrement sans mettre les logs en debug? à moins que les logs en debug soit raisonnable?

**Comment by KiwiHC16** [comment]
Je ne connais pas encore tous les détails de la ZiGate mais pour l'instant je ne sais pas avoir toute la liste des équipements du réseau. Il est même fort probable que la ZiGate ne les connaissent pas elle même: pas beaucoup de stockage dans la mémoire possible. Cela reste un question ouverte. Une de mes prochaines actions est de récupérer ce qu'elle a en mémoire pour essayer de mieux comprendre ce point.

**Comment by handfreezer** [comment]
Bon, je viens de monter une maquette avec 25 moeuds (cf. liste ci-dessous), et j'ai laissé les logs à debug.

```
AbeilleParser 2018-05-03 01:46:49[DEBUG]Nombre d'abeilles: 25
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 0; ID : 00; Short Addr : 06f6; IEEE Addr: 00158d0001fd8d5c; Power Source (0:battery - 1:AC): 00; Link Quality: 204
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 1; ID : 01; Short Addr : 12c0; IEEE Addr: 00158d0001c16470; Power Source (0:battery - 1:AC): 00; Link Quality: 197
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 2; ID : 02; Short Addr : c900; IEEE Addr: 00158d0002239f7a; Power Source (0:battery - 1:AC): 00; Link Quality: 178
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 3; ID : 03; Short Addr : 68b9; IEEE Addr: 00158d0002276147; Power Source (0:battery - 1:AC): 00; Link Quality: 180
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 4; ID : 04; Short Addr : f74a; IEEE Addr: 00158d000227b700; Power Source (0:battery - 1:AC): 00; Link Quality: 191
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 5; ID : 05; Short Addr : 2d6f; IEEE Addr: 00158d0001f26256; Power Source (0:battery - 1:AC): 00; Link Quality: 180
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 6; ID : 06; Short Addr : 4bdd; IEEE Addr: 00158d0001d707b1; Power Source (0:battery - 1:AC): 00; Link Quality: 195
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 7; ID : 07; Short Addr : 8954; IEEE Addr: 00158d000223a616; Power Source (0:battery - 1:AC): 00; Link Quality: 199
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 8; ID : 08; Short Addr : 3bdc; IEEE Addr: 00158d0001d6fa76; Power Source (0:battery - 1:AC): 00; Link Quality: 200
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 9; ID : 09; Short Addr : 418b; IEEE Addr: 00158d0001d78c5f; Power Source (0:battery - 1:AC): 00; Link Quality: 231
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 10; ID : 0A; Short Addr : d052; IEEE Addr: 00158d0001656e31; Power Source (0:battery - 1:AC): 00; Link Quality: 168
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 11; ID : 0B; Short Addr : d391; IEEE Addr: 00158d00010Fec57; Power Source (0:battery - 1:AC): 00; Link Quality: 237
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 12; ID : 0C; Short Addr : dc6c; IEEE Addr: 00158d00022345fb; Power Source (0:battery - 1:AC): 00; Link Quality: 168
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 13; ID : 0D; Short Addr : 5c64; IEEE Addr: 00158d0001e57366; Power Source (0:battery - 1:AC): 00; Link Quality: 171
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 14; ID : 0E; Short Addr : ac74; IEEE Addr: 00158d00016d6bf0; Power Source (0:battery - 1:AC): 00; Link Quality: 216
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 15; ID : 0F; Short Addr : 58c5; IEEE Addr: 00158d0001d84d75; Power Source (0:battery - 1:AC): 00; Link Quality: 229
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 16; ID : 10; Short Addr : 70d2; IEEE Addr: 00158d0001e48104; Power Source (0:battery - 1:AC): 00; Link Quality: 234
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 17; ID : 11; Short Addr : 74c7; IEEE Addr: 00158d0001e45a2e; Power Source (0:battery - 1:AC): 00; Link Quality: 236
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 18; ID : 12; Short Addr : 8a96; IEEE Addr: 00158d0001b7b649; Power Source (0:battery - 1:AC): 00; Link Quality: 232
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 19; ID : 13; Short Addr : 32c9; IEEE Addr: 00158d0001b7a7be; Power Source (0:battery - 1:AC): 00; Link Quality: 225
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 20; ID : 14; Short Addr : e972; IEEE Addr: 00158d0001de6116; Power Source (0:battery - 1:AC): 00; Link Quality: 230
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 21; ID : 15; Short Addr : 461b; IEEE Addr: 00158d0001b7a86a; Power Source (0:battery - 1:AC): 00; Link Quality: 233
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 22; ID : 16; Short Addr : b7e4; IEEE Addr: 00158d0001b7b471; Power Source (0:battery - 1:AC): 00; Link Quality: 230
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 23; ID : 17; Short Addr : db7f; IEEE Addr: 00158d00020195c7; Power Source (0:battery - 1:AC): 00; Link Quality: 234
AbeilleParser 2018-05-03 01:46:49[DEBUG]Abeille i: 24; ID : 18; Short Addr : ae18; IEEE Addr: 00158d0001d3ada8; Power Source (0:battery - 1:AC): 00; Link Quality: 217
```

**Comment by handfreezer** [comment]
NE | NE Name | Voisine | Voisine Name | Voisine IEEE | Relation | Profondeur | LQI
-- | -- | -- | -- | -- | -- | -- | --
0000 | Ruche | 06f6 |   | 00158d0001fd8d5c | Child | 01 | 204
0000 | Ruche | 12c0 |   | 00158d0001c16470 | Child | 01 | 197
0000 | Ruche | c900 |   | 00158d0002239f7a | Child | 01 | 178
0000 | Ruche | 68b9 |   | 00158d0002276147 | Child | 01 | 180
0000 | Ruche | f74a |   | 00158d000227b700 | Child | 01 | 191
0000 | Ruche | 2d6f |   | 00158d0001f26256 | Child | 01 | 180
0000 | Ruche | 4bdd |   | 00158d0001d707b1 | Child | 01 | 192
0000 | Ruche | 8954 |   | 00158d000223a616 | Child | 01 | 193
0000 | Ruche | 3bdc |   | 00158d0001d6fa76 | Child | 01 | 200
0000 | Ruche | 418b |   | 00158d0001d78c5f | Child | 01 | 231
0000 | Ruche | d052 |   | 00158d0001656e31 | Child | 01 | 193
0000 | Ruche | d391 |   | 00158d00010Fec57 | Child | 01 | 230
0000 | Ruche | dc6c |   | 00158d00022345fb | Child | 01 | 199
0000 | Ruche | ac74 |   | 00158d00016d6bf0 | Child | 01 | 216
0000 | Ruche | 58c5 |   | 00158d0001d84d75 | Child | 01 | 229
0000 | Ruche | 70d2 |   | 00158d0001e48104 | Child | 01 | 234
0000 | Ruche | 74c7 |   | 00158d0001e45a2e | Child | 01 | 236
0000 | Ruche | 8a96 |   | 00158d0001b7b649 | Child | 01 | 232
0000 | Ruche | 32c9 |   | 00158d0001b7a7be | Child | 01 | 225
0000 | Ruche | e972 |   | 00158d0001de6116 | Child | 01 | 230
0000 | Ruche | 461b |   | 00158d0001b7a86a | Child | 01 | 233
0000 | Ruche | b7e4 |   | 00158d0001b7b471 | Child | 01 | 230
0000 | Ruche | db7f |   | 00158d00020195c7 | Child | 01 | 234
0000 | Ruche | ae18 |   | 00158d0001d3ada8 | Child | 01 | 217

**Comment by KiwiHC16** [comment]
J'ai trouvé une bonne raison au comportement. Si les équipements ne sont pas vu par la ZiGate pendant un certain temps, puis ils sont visibles de nouveau alors elle les rejette avec un Leave. Certains se re-connectent, d'autres restent hors du réseau. Visiblement les équipements ne se comportent pas tous de la même façon. La raison est donc la couverture radio et doit donc être revu si on perd un équipement.

Avec les LQI qui sont dans ta liste tu ne devrais pas avoir la perte d'équipement (Je dirai si LQI < 100 alors il y a risque).  

La liste LQI change dans le temps et des équipements peuvent apparaitre, disparaitre sans pour autant entrer dans le cas "perte d'équipement". Je n'ai pas encore compris les evenements qui mettent à jour cette liste. En cours d'investigation.

**Comment by handfreezer** [comment]
OK, c'est cool d'avoir une piste, car pour l'instant, rien n'a disparu, mais en même temps, tous les capteurs sont à 30cm de l'environnement de test.
Je vais les éparpiller et je vous donne des nouvelles dans quelques jours.

**Comment by max5962** [comment]
Hello @KiwiHC16 
Merci pour l'aider apporter sur ce sujet.
je dev sur home-assistant actuellement et je récup des idées un peu partout :)

Peux-tu me dire si le LQI est la même information que le RSSI ( link quality ) ? 
T'a piste est prometteuse, cependant un module qui n'émet pas souvent ( capteur ouverture de fenêtre par exemple ) semble être dans le même cas.
J'ai un module à 1 mètre en direct de la Zigate, qui n'as pas été actionné pendant 1 mois. Résultat, le module a disparu. Il a fallut le l'appareiller à nouveau.

**Comment by KiwiHC16** [comment]
Quel est ce capteur de fenêtre ? Un Xiaomi V1 (pas la version rectangulaire mais disons elliptique)
Ou est ce un autre ?

RSSI et LQI ne sont pas identiques mais donnent une idée de la qualité radio.

**Comment by max5962** [comment]
C'est un capteur d'ouverture pardon :)
J'ai que du V2 ( celui de droite https://community.smartthings.com/t/xiaomi-vs-aqara-door-window-sensors/90738 ) 

Je vais tenter tenter d'implémenter le LQI.
Quel est l'avantage de LQI vs DeviceList (0815 ) ? 
merci

**Comment by KiwiHC16** [comment]
Device List sont les infos retournées par zigate. LQI sont les infos retournées par les routeurs. 

Quelle version de zigate utilises tu ?

**Comment by max5962** [comment]
Merci pour l'information.
La dernière sortie, version "d".

**Comment by KiwiHC16** [comment]
La conclusion sur ce sujet est "Mauvaise couverture radio" = "perte des equipements".
Je clos cette discussion. Si on fait face a de nouveaux scenarios, on ouvrira une au issue.

**Comment by max5962** [comment]
Hello,
ce n'est pas ma conclusion car j'ai un module à moins d'1 mètre de ma zigate et pourtant je le perd régulièrement. 
Je reçoit la semaine prochaine une nouvelle zigate pour valider que la première était défectueuse.
En revanche ton hypothèse sur le leave envoyé me semble plus cohérent.
Il faudrait alors pour les modules xiaomi un comportement différents quitte à s'éloigner du standard zigbee.

**Comment by KiwiHC16** [comment]
On continue sur #251
