### ISSUE TITLE
Ampoule Ledvance E27 tunable white (id = A60STW, LEDVANCE)

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2400]
Bonjour @KiwiHC16 
Je viens de recevoir cette ampoule Ledvance Smart+ en zigbee 800lm 360° 9w E27 (<14€ sur AMZ) dont voici le .png
![LedvanceColor](https://user-images.githubusercontent.com/52486183/173368346-7719ab37-be6c-4c73-a5ff-afe19f0cd383.png)
Elle est bien incluse mais non reconnue. J'ai lancé un découverte et voici le .json
[ledvance.discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/8891607/ledvance.discovery.json.txt)
Est-ce que tu penses qu'elle ressemble à quelque chose de connu. J'ai vu que tu avais déjà intégré une PC Ledvance.
Merci

**Comment by tcharp38** [comment]
Salut @Kenderv 

Quel est le modèle/ref fabricant ?

A décompresser dans core/config/devices
[A60STW_LEDVANCE.zip](https://github.com/KiwiHC16/Abeille/files/8918125/A60STW_LEDVANCE.zip)

puis redemarrer Abeille
refaire inclusion
faire le point

**Comment by Kenderv** [comment]
Salut @tcharp38 
et merci de ta réponse. 

Modèle/Ref fabricant : 
![image](https://user-images.githubusercontent.com/52486183/174079869-90dff50b-2f03-4c76-a83d-a7bf26a2ccd2.png)

J'ai décompressé le fichier à sa place, déposé le fichier .png dans le répertoire images sous le nom node_Ledvance-BulbE27-Color.png, redémarré le démon Abeille et lancé l'inclusion. L'ampoule a bien été incluse 
On : l'ampoule clignote 2 fois puis après ~2 secondes s'allume blanc chaud, je pense 2700. Le phénomène du clignotement ne se produit plus aux allumages suivants.
Off : L'ampoule s'éteint
SetLevel : l'éclairage diminue et remonte en bougeant le curseur et le current level évolue avec une latence de ~2 secondes
white, blue, red, green et le changement de couleur via la commande RGB sans aucun effet sur l'éclairage. 
La commande identify (testée par hasard) provoque le passage en lumière froide et clignotante arrêtée par la cde off. Une nouvelle cde On reproduit le phénomène indiqué plus haut.
Toggle : OK
Color mode après getcolormode = 2
Voilà le résultat de mes tests. Si tu veux que je procède à d'autres n'hésite pas à me le demander.
Bon courage et merci de ton aide.

**Comment by tcharp38** [comment]
Salut @Kenderv 
Merci pour ce status

- On: Le clignotement veut surement dire que l'Ampoule a rejoint un reseau ou qqch comme ca vu que ca n'apparait plus apres. Donc j'imagine que c'est la premiere fois apres qu'elle soit alimentée non ?
- Latence: 2 sec c est beaucoup mais mes essais avec ce genre d'ampoule montrent qu'elles ne sont pas réactives de toute façon
- Identify: Jamais eu le temps de tester ce genre de fonctionalité mais si pb on peut toujours creuser

Tu peux me filer un snapshot du dashboard pour cet equipement ?

**Comment by Kenderv** [comment]
Salut @tcharp38 
Qu'entends tu par "le snapshot du dashboard" ? Les commandes générées ?
Je te confirmes que je n'ai pas réussi à faire varier ni la température des blancs ni les couleurs.
Merci

**Comment by tcharp38** [comment]
Je parle du "visuel" sur le dashboard.

**Comment by Kenderv** [comment]
Le voici 
![image](https://user-images.githubusercontent.com/52486183/176132773-6239ce59-d2de-4215-a9f8-4b7e5a85b5f3.png)

**Comment by tcharp38** [comment]
Peux tu cliquer sur "white" puis me filer le package de logs ?
Attends bien une 10aine de secondes avant d extraire les logs et surtout note l heure de ton action.
Merci

**Comment by Kenderv** [comment]
Voilà le log, j'ai cliqué sur white à 17h50et quelques secondes. Dis moi si cela te convient 
[AbeilleLogs-220701.tar.gz](https://github.com/KiwiHC16/Abeille/files/9030113/AbeilleLogs-220701.tar.gz)

Edit L'adresse de l'équipement est 159E

**Comment by Kenderv** [comment]
Le test précédent a été fait ampoule éteinte, voici les logs lampe allumée. Je ne sais pas si cela change quelque chose mais au ca ou ...
[AbeilleLogs-220701 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9030195/AbeilleLogs-220701.1.tar.gz)
.

**Comment by tcharp38** [comment]
On a au moins une réponse graçe a tes logs:

> [2022-07-01 18:01:59] -- execute(eqName='Ledvance color E27 bulb Bureau' name='White' type=action, options={"user_login":"JDLM","user_id":"2"})
> [2022-07-01 18:01:59] -- execute(): Msg sent: {"topic":"CmdAbeille1\/159E\/setColour","payload":"EP=01&X=6000&Y=6000"}
> [2022-07-01 18:01:59] Msg from 'xToCmd': Pri=4, CmdAbeille1/159E/setColour => EP=01&X=6000&Y=6000
> [2022-07-01 18:01:59]   prepareCmd(4, CmdAbeille1/159E/setColour, EP=01&X=6000&Y=6000)
> [2022-07-01 18:01:59]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
> [2022-07-01 18:01:59]     processCmd({"setColour":"setColour","name":"setColour","priority":4,"dest":"Abeille1","EP":"01","X":"6000","Y":"6000","addr":"159E"})
> 
> [2022-07-01 18:01:59]   sendCmdToZigate(Dest=Abeille1, cmd=00B7, datas=02159E0101600060000001)
> [2022-07-01 18:01:59] processAcks(): msg={"type":"8000","net":"Abeille1","status":"00","sqn":"94","sqnAps":"FB","packetType":"00B7","nPDU":"00","aPDU":"01"}
> 
> [2022-07-01 18:01:59] Abeille1, Type=8000/Status, Status=00/Success, SQN=94, PacketType=00B7, Sent=01, SQNAPS=FB, NPDU=00, APDU=01
> [2022-07-01 18:01:59] Abeille1, Type=8012/APS data confirm, Status=00, Addr=159E, SQNAPS=FB, NPDU=00, APDU=01
> [2022-07-01 18:01:59] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0300, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=159E, DstAddrMode=02, DstAddr=0000
> [2022-07-01 18:01:59]   FCF=08/General/Serv->Cli, SQN=94, cmd=0B/Default Response
> [2022-07-01 18:01:59]   Cmd=07, Status=81 => Unsupported cluster command

Bref la commande "Move to Color" (utilisée par White/Red/Green/Blue) n'est pas supportée.

**Comment by Kenderv** [comment]
Ton message m'a perturbé et j'ai regardé l'emballage de l'ampoule. Et bien je te dois des excuses car en fait c'est une ampoule qui n'est pas couleur mais seulement blanche dimmable et permettant la variation de T° . Ce qui, sans doute, expliqurait ton message précédent. Je suis absent quelques temps et je reprendrai contact à mon retour. Encore mille excuses.
C'est celle-ci qui apparaît bien dans ta liste des équipements supportés :
![image](https://user-images.githubusercontent.com/52486183/177727167-f362c968-dce9-4cc2-ab1d-7bd22dd77b49.png)

**Comment by tcharp38** [comment]
Ha ben je prefere ça.
Au moins c'est en ligne avec les observations.
Donc pas de controle de couleur, juste un controle de température.

Je vais revoir le modele.

**Comment by tcharp38** [comment]
[A60STW_LEDVANCE.zip](https://github.com/KiwiHC16/Abeille/files/9062511/A60STW_LEDVANCE.zip)

Refaire inclusion ou reinitialiser via la page EQ/avancé

**Comment by tcharp38** [comment]
220714-STABLE-1

**Comment by Kenderv** [comment]
Salut @tcharp38 
De retour, voilà ce que j'ai fait : 
Installation de 220714-STABLE-1 (en lieu et place https://github.com/KiwiHC16/Abeille/issues/2400#issuecomment-1177348361)
Exclusion et suppression de l'ampoule dans le plugin Abeille
Ré inclusion de l'ampoule : immédiatement reconnue au premier allumage
Le niveau d'éclairage fonctionne mais pas la variation de température à l'aide du curseur. Ce curseur varie de de 0 à 100. Est -ce en % ou en température Kelvin ? Lorsque je fais un test sur ColorTemperature j'obtiens 370. Si je lance manuellement l'URL de la commande Set Temperature avec une valeur à 4000 la température de la lampe change correctement.
A toi de jouer. Merci et bonne journée

Edit : Je viens de relancer le demon et tout fonctionne. Donc tout est OK. Merci

**Comment by tcharp38** [comment]
Salut @Kenderv 
Un vieux sujet mais je suis perdu.
Au final il y a encore des soucis ou ce sujet peut etre clos ?

**Comment by Kenderv** [comment]
Salut @tcharp38 
Détends-toi et respire, tout va bien, tu peux clore ce sujet comme indiqué dans mon dernier message.
A bientôt sans doute et merci

**Comment by tcharp38** [comment]
:)
Merci
