### ISSUE TITLE
tous en time out apres deplacement du raspberry

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2401]
comme expliquer en remontant mon raspberry dans ma goulotte gtl je n ai plus rien de reconnu par abeille, tous est en time out
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/8898456/AbeilleSerialRead1.log)
[AbeillePHP.log](https://github.com/KiwiHC16/Abeille/files/8898457/AbeillePHP.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/8898458/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/8898459/AbeilleConfig.log)

**Comment by chrisb13790** [comment]
[AbeillePHP(1).log](https://github.com/KiwiHC16/Abeille/files/8899604/AbeillePHP.1.log)
[AbeilleConfig(1).log](https://github.com/KiwiHC16/Abeille/files/8899605/AbeilleConfig.1.log)
[AbeilleSerialRead1(1).log](https://github.com/KiwiHC16/Abeille/files/8899606/AbeilleSerialRead1.1.log)

**Comment by chrisb13790** [comment]
2022-06-14 14:15:02 | Abeille | ERREUR: le pilote pl2303 semble en erreur, impossible de communiquer avec la zigate. | Il faut débrancher/rebrancher la zigate et relancer le démon.

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Peux tu me filer un snapshot de ta page de config ?
Et le package de logs (page support/telecharger tout). Il est bien plus complet que ce que tu donnes.

Merci

De ce premier je conclus que tu as une Zigate USB (v1 ? v2 ?).
Correct ?

**Comment by chrisb13790** [comment]
salut
voici ce que tu me demande
oui zigate 1ere gen v1 adaptateur bleu
![Sans titre 1](https://user-images.githubusercontent.com/91745100/173875360-10aa060f-1813-4317-801c-2db014994c85.jpg)
![Sans titre 2](https://user-images.githubusercontent.com/91745100/173875363-6016f16f-fa75-4dfb-af67-8554e0aeeef8.jpg)
![Sans titre 3](https://user-images.githubusercontent.com/91745100/173875364-bd50104e-289f-4fd8-a5f2-de06498e2011.jpg)
[AbeilleLogs-220615.tar.gz](https://github.com/KiwiHC16/Abeille/files/8911236/AbeilleLogs-220615.tar.gz)

**Comment by tcharp38** [comment]
Ok, cote page de config ca semble bon.

Le FW devra etre mis à jour en 3.21.

Mais tes logs sont vides car tu n'es pas en mode debug :(
Désolé. C'est une base nécessaire pour tout support.
Donc
- passer en mode debug + SAUVEGARDER
- ET redemarrer Abeille (démon)

**Comment by chrisb13790** [comment]
Salut a part repartir de zéro,que puis je faire ?

**Comment by tcharp38** [comment]
Salut

Je ne peux pas te conseille cette solution car je ne pige pas ce qui se passe.

Peux tu
- activer le mode debug + sauvegarde + redemarrer demon
- et me filer le package de logs

**Comment by chrisb13790** [comment]
j ai envoyé une veille sauvegarde,fait les mise a jours ,activé mode debug et relancer le demon
[AbeilleLogs-220617.tar.gz](https://github.com/KiwiHC16/Abeille/files/8926427/AbeilleLogs-220617.tar.gz)

**Comment by chrisb13790** [comment]
bon ca remarche pourquoi je sais pas lol c est la troisieme fois que je fait ca meme chose

**Comment by tcharp38** [comment]
Tant mieux si c est reparti mais incompris = pas bon.. :(
Je jettes un oeil aux logs au cas ou.

Et je ne vois rien sur ce dernier log.
Bref, pas de piste. Pourtant j'ai l'impression que ce cas de figure apparait de temps en temps, rarement mais... présent.

Je te laisse cloturer le souci si il n'apparait plus.

**Comment by chrisb13790** [comment]
Re, j ai de nouveau une erreur pl2303 mais ça fonctionne toujours

**Comment by tcharp38** [comment]
Quel genre ? Tu vois ça comment ?

**Comment by chrisb13790** [comment]
L erreur je la vois dans le centre de message jeedom un petit carré orange
apparaît.ensuite direction l icône santé du plugin.exemple l inter sdb
timeout si je clique dessus il répond quand même jusqu'à que la ruche tombe
en timeout et parfois il répond pas.

**Comment by tcharp38** [comment]
Si ça se reproduit, met moi le package de logs stp

**Comment by chrisb13790** [comment]
J ai tjrs l erreur pl2303 qui revient j ai commander une nv adaptateur USB
ttl

**Comment by tcharp38** [comment]
Pas de logs ?

**Comment by chrisb13790** [comment]
Je t'envoie ça demain

**Comment by chrisb13790** [comment]
salut voici les logs

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 20 juin 2022 à 22:51, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 21 juin 2022 à 16:48, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
re problème de communication réglé la partie usb ne sortait pas assez

Le mar. 21 juin 2022 à 16:49, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
par contre j essaye de connecter un sonoff snzb-02 (capteur temp/humidité)
impossible
je lance l inclusion sa clignote,j appui 5 seconde sur le capteur il
clignote mais dans le plugin rien,pas de message ni de nouvel équipement


Le mar. 21 juin 2022 à 18:46, chris barcelone ***@***.***> a
écrit :

> re problème de communication réglé la partie usb ne sortait pas assez
>
> Le mar. 21 juin 2022 à 16:49, chris barcelone ***@***.***>
> a écrit :
>
>>
>>
>>
>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Garanti
>> sans virus. www.avast.com
>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>> <#m_-579854505075031556_m_4054238038855697148_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>>
>> Le mar. 21 juin 2022 à 16:48, chris barcelone ***@***.***>
>> a écrit :
>>
>>> salut j ai recu l adaptateur mais j ai un souci de com avec la zigate y
>>> a t il une procedure a faire suite au changement de l adaptateur ?
>>>
>>>
>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Garanti
>>> sans virus. www.avast.com
>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>>> <#m_-579854505075031556_m_4054238038855697148_m_4146557075187010306_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>>>
>>> Le mar. 21 juin 2022 à 06:49, chris barcelone ***@***.***>
>>> a écrit :
>>>
>>>> salut voici les logs
>>>>
>>>>
>>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Garanti
>>>> sans virus. www.avast.com
>>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>>>> <#m_-579854505075031556_m_4054238038855697148_m_4146557075187010306_m_5295018712769036927_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>>>>
>>>> Le lun. 20 juin 2022 à 22:51, chris barcelone <

**Comment by tcharp38** [comment]
Il n'y a pas de logs. Tu dois surement faire un reply quelconque autrement que par l'interface web de GitHub.
Bref je ne vois rien.

Je te suggere de basculer sur la beta pour ton test SonOff
et dans tous les cas.. j'ai besoin du package de logs.

**Comment by chrisb13790** [comment]
Ok ça marche la j ai installé la dernière beta , j ai essayé de mettre à
jour la zigate mais plus rien marché du coup retour en 3.1e

**Comment by tcharp38** [comment]
Ouah.
Bon on cumule les pbs.

Resultat ? Tu dis que ca fonctionne maintenant ? Tu as pu inclure ton SonOff ?

**Comment by chrisb13790** [comment]
petit retour
plus rien ne marche.
 retour de jeedom a 1 semaine en arriere , fw zigate retour en 3.1e mais bizarrement plus le même numéro de fw dans abeille.je pense vraiment a changer tous le système de domo
![ancien](https://user-images.githubusercontent.com/91745100/175254466-3fdd3e54-fee0-4f47-a1c1-bb0949524f5f.jpg)
![nouveau](https://user-images.githubusercontent.com/91745100/175254498-c38ad6ef-5ec4-4e70-b0ab-ab7083c94ea1.jpg)
![Sans titre 1](https://user-images.githubusercontent.com/91745100/175256697-1abeb5b0-a2fc-45e1-ba4f-be608485e847.jpg)
![Sans titre 2](https://user-images.githubusercontent.com/91745100/175256711-f84344de-7deb-46d6-905c-da601831e49f.jpg)
![Sans titre 3](https://user-images.githubusercontent.com/91745100/175256743-059316e4-b9d6-41fd-8cfc-4457db4bc368.jpg)

**Comment by chrisb13790** [comment]
[AbeilleLogs-220623.tar.gz](https://github.com/KiwiHC16/Abeille/files/8965595/AbeilleLogs-220623.tar.gz)

**Comment by chrisb13790** [comment]
si tu veux je remets le dernier fw sur la zigate et la derniere beta sur abeille

**Comment by tcharp38** [comment]
Désolé de lire tes déboires meme si je les comprends.

Trop de changements à la fois c'est clair.
Tu as changé le FW, mais j'ai l'impression que tu etais en "legacy" (0003-031E) et que mainteant tu affiches une version "OPDM" (0004-031E).

Peux tu me dire ce que tu as fait exactement cote FW ?

**Comment by chrisb13790** [comment]
l ancien etait le 0004-031e et le nouveau 0003-031e j ai juste reprogrammé sans faire erase eeprom mais j ai essayé le3.20 , 3.21 etc pas de resultat

**Comment by tcharp38** [comment]
Normal alors.
Si tu etait en 0004-xxx (donc OPDM), tu ne reviens pas en arriere et tu gardes une version OPDM (la + recente et + fiable).

Donc passage 0004-031e (version OPDM) => 0003-031e (version LEGACY, vieux format interne) pas bon

Le bon truc: 0004-031e => 0004-0321

Tu suis ?

**Comment by chrisb13790** [comment]
oui
![Sans titre 4](https://user-images.githubusercontent.com/91745100/175302973-a4605e7e-1a6a-4f72-ab47-da1b205c1c3d.jpg)
du coup veux tu que j installe celle la ?
est ce que je fais la mise a jour abeille en derniere version beta ?

**Comment by tcharp38** [comment]
Pour faire retomber les choses en marche (jespere), oui mets la version 3.21 OPDM.

Le passage en beta ne peut rien resoudre à ce stade. C est un pb Zigate.

**Comment by chrisb13790** [comment]
voila maj zigate et abeille beta faite,tous sauf abeille en timesout
![Sans titre 5](https://user-images.githubusercontent.com/91745100/175317898-258fb89e-1b14-4383-8fbb-476940f741aa.jpg)
pas de changement
[AbeilleLogs-220623.tar.gz](https://github.com/KiwiHC16/Abeille/files/8967939/AbeilleLogs-220623.tar.gz)

**Comment by tcharp38** [comment]
Je vois ca :(
Si tu regardes le log parser, c'est lui qui indique tout ce qui remonte des Zigates.. et la apres la config nada.
On voit bien que tu en Appli=0004, SDK=0321, alors qu'au debut de ce sujet tu etais en 0004-031E
![image](https://user-images.githubusercontent.com/35221038/175319803-75f10119-be87-486d-a11b-e247c141a612.png)

J'ai bien peur que le passage via la mauvaise version 0003/Legacy ai cassé la structure interne du FW :(
Auquel cas... si tu n'as pas de backup zigate (pas supporté via Abeille), tu dois faire un "Erase PDM" et tout réappairer.

**Comment by chrisb13790** [comment]
si ce n est que tous reappairer  sans supprimer sur abeille pas bien grave,
du coup je connecte la zigate au programmateur et je fais juste un erase ou je refais la complète ?

**Comment by tcharp38** [comment]
Si tu cliques sur la ruche, onglet "Avancé", tu dois trouver "Erase PDM" non ?
Si oui alors tu le fais, et passe tente une inclusion.

**Comment by chrisb13790** [comment]
erase pdm fait quand je demande l inclusion la zigate ne clignote pas et impossible d appairer mon capteur porte par exemple

**Comment by chrisb13790** [comment]
[AbeilleLogs-220623.tar.gz](https://github.com/KiwiHC16/Abeille/files/8968544/AbeilleLogs-220623.tar.gz)

**Comment by tcharp38** [comment]
Tant que la zigate ne clignote pas inutile d aller + loin.
Peux tu redemarrer Abeille et repasser en mode inclusion ?

**Comment by chrisb13790** [comment]
je redémarre comment ? juste le demon ?

**Comment by tcharp38** [comment]
oui.
Ca a pour effet de faire un reset de la zigate.

**Comment by chrisb13790** [comment]
demon redemarré a clignote pas a l inclusion

**Comment by chrisb13790** [comment]
[AbeilleLogs-220623.tar.gz](https://github.com/KiwiHC16/Abeille/files/8968995/AbeilleLogs-220623.tar.gz)

**Comment by tcharp38** [comment]
Decidement.
Elle ne se comporte pas comme il faut.

J'ai eu ce genre de déboires et j'ai recommencé l'update FW, mais du coup en ajoutant "Erase EEPROM".
La version 3.21-OPDM (0004-0321) est toujours celle qu'il faut cibler. C est la derniere pour Zigate v1.

Au passage, le bouton "TEST" de la page de config donne un resultat ok ?

**Comment by chrisb13790** [comment]
au depart oui effectivement maintenant  sur le test j ai un nok
je reflash la zigate avec un erase ?

**Comment by chrisb13790** [comment]
je fais erase pdm ou complete?

**Comment by tcharp38** [comment]
Tu dois suivre ca
https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

en terminant par ca
7- Cliquez enfin sur “Erase EEPROM” puis “Complete EEPROM” si c’est votre première utilisation de la ZiGate.

mais je pige pas ou est ce "Complete"

**Comment by chrisb13790** [comment]
quand tu clique sur erase eeprom il ouvre une fenetre et demande pdm only ou complete eeprom
![Sans titre 6](https://user-images.githubusercontent.com/91745100/175377436-474e71ad-0c85-4405-92ed-cf263ff1e4bb.jpg)

**Comment by tcharp38** [comment]
Alors Complete EEPROM d'apres le tuto Zigate

**Comment by chrisb13790** [comment]
toujours nok

**Comment by chrisb13790** [comment]
je retente encore une fois

**Comment by tcharp38** [comment]
!? Avec cette procédure le fw devrait être nickel et remis à zéro.
Le pb est ailleurs. Perturbations alim ou port usb ?

**Comment by chrisb13790** [comment]
pourtant entre l ouverture du pb et maintenant rien a changer a part le usb ttl bleu remplacer par le rouge avant la tentative de maj du fw et ca marché c est partie en vrille apres maj fw

**Comment by chrisb13790** [comment]
viens de passer en ok 
![Sans titre 7](https://user-images.githubusercontent.com/91745100/175380868-5673e1c5-36a5-4195-b99e-04b05b8da55b.jpg)

**Comment by tcharp38** [comment]
Miracle ?
Ça clignote en inclusion ?

**Comment by chrisb13790** [comment]
oui ca cligonte lol j essaye d inclure mon capteur de porte rien mon nouveau sonoff capteur temperature rien

**Comment by tcharp38** [comment]
Ok, ça progresse enfin.
Tu es en stable ou bêta ?

**Comment by chrisb13790** [comment]
derniere beta

**Comment by chrisb13790** [comment]
![Sans titre 8](https://user-images.githubusercontent.com/91745100/175382625-c2934ef3-b449-4c88-bc9c-a67745c54a54.jpg)
comment corriger ca ?

**Comment by tcharp38** [comment]
Via le menu jeedom configuration logs et encore logs je crois

**Comment by chrisb13790** [comment]
ca c est fait

**Comment by chrisb13790** [comment]
j arrive pas a remettre la zigate sur canal 26
![Sans titre 9](https://user-images.githubusercontent.com/91745100/175385196-77de3d35-1e69-4d92-a97d-e29a93b3a108.jpg)
![Sans titre 10](https://user-images.githubusercontent.com/91745100/175385215-69727dad-02ca-4826-861e-45b0819a7583.jpg)
quand je fait modifier rien ne se passe

**Comment by tcharp38** [comment]
Ha m.. tu as vraiment besoin de changer le canal ?
J'avoue que n'ai jamais fait cette manip.
File moi les logs quand tu as fait cette manip que je regarde ce qui se passe.

**Comment by chrisb13790** [comment]
pour les livolo pas le choix du canal 26 mais j arrive pas a le changer je vais passer par le programateur comme j avais fais la premiere fois

**Comment by tcharp38** [comment]
Avant ca tu confirmes que tu arrives à inclure qqch ?

**Comment by chrisb13790** [comment]
pour le moment je n arrive pas inclure,pas encore changer de canal
je vais faire un test du module radio en meme temps que je vais changer le canal
[AbeilleLogs-220624.tar.gz](https://github.com/KiwiHC16/Abeille/files/8973381/AbeilleLogs-220624.tar.gz)

**Comment by chrisb13790** [comment]
test et changement canal ok

![Sans titre 12](https://user-images.githubusercontent.com/91745100/175473606-7652a91a-bf5a-46e5-9b4d-a3f208b3662e.jpg)

**Comment by chrisb13790** [comment]
![Sans titre 11](https://user-images.githubusercontent.com/91745100/175476286-eb00a5a2-173b-4718-a491-2bae8a29ee37.jpg)

**Comment by chrisb13790** [comment]
log apres le test et changement de canal
[AbeilleLogs-220624.tar.gz](https://github.com/KiwiHC16/Abeille/files/8973744/AbeilleLogs-220624.tar.gz)

**Comment by chrisb13790** [comment]
toujours pas d inclusion malgré la led qui clignote
[Uploading AbeilleLogs-220624.tar.gz…]()

**Comment by chrisb13790** [comment]
petit retour sur la journée de test
quitte a tous reprendre suppression d abeille et reinstal =pas de changement
installation plugin zigate=pas de changement
remplacement cle usb avec mise en place raspios et d un nouveau jeedom tout neuf =pas de changement et meme pas de detection de la zigate
installation du plugin zigate sur le nv jeedom=détection des inter et capteur porte
retour sur l ancienne clé usb reinstallation derniere stable =detection des inters et capteurs sur certain je n ai pas eu besoin de faire de re-inclusion mais toujours pas avec le snzb-02

**Comment by chrisb13790** [comment]
test avec un nouveau module mhcozy modele zg-005-rf
detecté mais pas reconnu
![Sans titre 13](https://user-images.githubusercontent.com/91745100/175658717-9f38982c-40a8-4ab1-b5f5-d254675fba62.jpg)
![Sans titre 14](https://user-images.githubusercontent.com/91745100/175658737-da81a759-f96d-4618-8dea-dd4ce9f5073f.jpg)

**Comment by tcharp38** [comment]
Beaucoup d 'essais je vois.

Le point suivant 

> retour sur l ancienne clé usb reinstallation derniere stable =detection des inters et capteurs sur certain je n ai pas eu besoin de faire de re-inclusion mais toujours pas avec le snzb-02

veut dire quoi ? Quelle est cette ancienne clef ? Quelle etait la nouvelle ? Désolé. Je suis un peu perdu.
Mais il semble que ca fonctionne en dehors du snzb02 c'est ca ?

Pour ton nouvel equipement, a mettre dans un sujet different specifique et la procedure de la doc: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement
Merci

**Comment by chrisb13790** [comment]
inclusion sonoff snzb-02ok
j ai souvent cette erreur 
![Sans titre 15](https://user-images.githubusercontent.com/91745100/175765297-1f19bce5-44fe-4806-917a-d1b94b26763f.jpg)
j ai réussi a recuperer ceci

**Comment by chrisb13790** [comment]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8984207/discovery.zip)
et creer ceci
![node_MHCOZY-ZG-005-RF](https://user-images.githubusercontent.com/91745100/175765397-ba50079d-90c6-4334-b22b-d1247c3d6bf5.png)

**Comment by chrisb13790** [comment]
sur le raspi os et sur clé usb pas de hdd pas assez de place dans les coffrets elecriques, du coup j avais fait une deuxieme clé usb pour faire des test avec un os et jeedom tous neuf

**Comment by chrisb13790** [comment]
du coup je tourne sur la clé usb de depart
 zigate en 0004-0321
Version Abeille :220619-STABLE-1

**Comment by tcharp38** [comment]
Du coup quel est le status de ce sujet ?
L'err Javascript que tu montres ne me surprends pas. Faudra que je corrige des que je tombe dessus.

**Comment by chrisb13790** [comment]
Je pense qu on peut le fermé a moins que tu veuilles des logs

**Comment by tcharp38** [comment]
Je clos.
A reouvrir si le sujet en a besoin.

**Comment by chrisb13790** [comment]
salut j ai recu l adaptateur mais j ai un souci de com avec la zigate y a t
il une procedure a faire suite au changement de l adaptateur ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 21 juin 2022 à 06:49, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
salut ce matin j ai voulu faire la maj d abeille ; erreur fichier
corrompu[image:
Sans titre 1.jpg]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 21 juin 2022 à 19:08, chris barcelone ***@***.***> a
écrit :

> par contre j essaye de connecter un sonoff snzb-02 (capteur temp/humidité)
> impossible
> je lance l inclusion sa clignote,j appui 5 seconde sur le capteur il
> clignote mais dans le plugin rien,pas de message ni de nouvel équipement
>
>
> Le mar. 21 juin 2022 à 18:46, chris barcelone ***@***.***>
> a écrit :
>
>> re problème de communication réglé la partie usb ne sortait pas assez
>>
>> Le mar. 21 juin 2022 à 16:49, chris barcelone ***@***.***>
>> a écrit :
>>
>>>
>>>
>>>
>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Garanti
>>> sans virus. www.avast.com
>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>>> <#m_8505092866420556208_m_-579854505075031556_m_4054238038855697148_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>>>
>>> Le mar. 21 juin 2022 à 16:48, chris barcelone ***@***.***>
>>> a écrit :
>>>
>>>> salut j ai recu l adaptateur mais j ai un souci de com avec la zigate y
>>>> a t il une procedure a faire suite au changement de l adaptateur ?
>>>>
>>>>
>>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Garanti
>>>> sans virus. www.avast.com
>>>> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>>>> <#m_8505092866420556208_m_-579854505075031556_m_4054238038855697148_m_4146557075187010306_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>>>>
>>>> Le mar. 21 juin 2022 à 06:49, chris barcelone <

**Comment by tcharp38** [comment]
Salut
Tu me files le package de logs STP ?

**Comment by chrisb13790** [comment]
Salut je t envoi ça ce soir mais depuis pas eu de souci j ai remis un
scenar d inclusion toute les 30 min

**Comment by chrisb13790** [comment]
Salut désolé j ai complétement zappé,je dois t envoyé ça sur github ?

Le mar. 11 oct. 2022 à 13:42, chris barcelone ***@***.***> a
écrit :

**Comment by tcharp38** [comment]
Yeap, ici et pas par email. Ca ne fonctionne pas.

**Comment by chrisb13790** [comment]
voici les logs
[AbeilleLogs-221014.tar.gz](https://github.com/KiwiHC16/Abeille/files/9788874/AbeilleLogs-221014.tar.gz)

**Comment by tcharp38** [comment]
Pas de trace d'erreur dans ces logs :(
Je vois que tu es toujours sur la derniere stable. Je pense en faire une nouvelle cette semaine.
Quoi qu'il en soit ouvre un sujet séparé si ce genre de souci revient histoire de pas pourrir ce thread.
Merci

**Comment by chrisb13790** [comment]
Que recherche tu comme erreurs car depuis la dernière fois qui remonte a un
p'tit moment j ai pas eu de souci a part des pertes que j ai résolu en
fessant une inclu toute les 30 min

**Comment by tcharp38** [comment]
Je cherchais l'erreur que tu as mentionné "erreur fichier corrompu".

Pourquoi & comment declenches tu une inclusion toutes les 30mins ?

**Comment by chrisb13790** [comment]
C est vieux ça aussi si tu te rappel j avais eu un souci avec la maj de la
zigate entre la version odm etc .....
Je lance une inclusion toute les 30 min car je me suis aperçu que j avais
des inters livolo qui passé en Time out

**Comment by tcharp38** [comment]
Ha c 'est pour les inter. Ouvre un sujet sur ce cas. C 'est à creuser.

**Comment by chrisb13790** [comment]
salut j ai ouvert un nouveau ticket n°2476 suite a des erreurs ce matin

**Comment by chrisb13790** [comment]
salut aujourd hui tout en time out peut etre depuis plusieurs jours je ne sais pas car des gars essaye de me faire repartir le rflink
[AbeilleLogs-230706.tar.gz](https://github.com/KiwiHC16/Abeille/files/11970850/AbeilleLogs-230706.tar.gz)

**Comment by chrisb13790** [comment]
on a reussi a faire repartir rflink mais j ai l impression qu abeille patoge
[AbeilleLogs-230706(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11971492/AbeilleLogs-230706.1.tar.gz)

**Comment by tcharp38** [comment]
Salut
Ca faisait un moment que tu n'avais pas eu de soucis il me semble :(

Pourquoi dis tu qu'Abeille patauge ?

Je note que tu es sur le canal 26 Zigbee. Ca me semble etrange et surement pas tres compatible avec pas mal de devices.
C'est ton choix ?

**Comment by chrisb13790** [comment]
salut j avais arreté un temps, ca mouline j arrive pas a faire repartir certain device malgres des reinclusion
pour le canal 26 pas le choix pour les livolo

**Comment by tcharp38** [comment]
Quel device en particulier ?

**Comment by chrisb13790** [comment]
![Sans titre](https://github.com/KiwiHC16/Abeille/assets/91745100/54792d62-09e9-4311-b57f-dfa6f8278973)
celui qui te fais envie ;-)

**Comment by tcharp38** [comment]
Ha oui quasi que des livolo en time out ?!

**Comment by tcharp38** [comment]
Apres reflexion.. c est tres etrange.
J'ai l'impression que le "Time-out" n'est pas vrai en fait.

Regarde 28F8 dans ton exemple
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/727928ec-8295-4296-90e9-c124bb336c7a)

Le tableau dit "en timeout depuis 18H" mais le dernier message date de 20:46:13
D'autre part dnas les infos clefs ce device n'est en fait PAS en timeout.
Il ny a que le suivant

>  - Z1: [maison][Sonoff smart switch - 157], id=157: TIMEOUT (2023-07-06 20:46:13)
>        addr=342B, type='Sonoff smart switch', model='01MINIZB'

Ca me perturbe ca.
On dirait qu'il y a une incohérence qq part.

**Comment by tcharp38** [comment]
Je pense que ta page "santé" n'est pas en ligne (pas raffraichie) avec le package de logs que tu as filé.
Le code pour identifier le "timeout" fait la meme chose donc je vois pas d'ou peut venir une telle diff.
Ca fait du sens ?

Du coup quelle est la situation ? Et si tu me refiles le packages de logs fait aussi un snapshot a jour de la page santé STP

**Comment by chrisb13790** [comment]
Ça marche je te ferais ça demain soir ou mercredi

**Comment by chrisb13790** [comment]
Salut
Tout est rentré apparemment dans l' ordre tous les services sont en ok
alors que je n arrivais pas à faire de reinclusions.dis moi si tu veux
quand même les logs ou autre

**Comment by tcharp38** [comment]
Salut
Non si c 'est a nouveau ok pour toi on laisse courrir. Pas sur d'en tirer qqch maintenant.

**Comment by chrisb13790** [comment]
Ok alors on cloture
