### ISSUE TITLE
Ajout GLEDOPTO GL-C-008P Pro RGB RGBW Strip Contrôleur

### ISSUE THREAD

**Issue by nawak86** [KiwiHC16/Abeille#2402]
Hello,

J'aimerais ajouter un modèle json de produit mais je ne sais pas comment on fait j'ai la possibilité de faire un discovery.json c'est ce qu'il faut que je fournisse ? 

Le voici :

`{
    "endPoints": {
        "0B": {
            "status": "00",
            "servClusters": {
                "0000": {
                    "attributes": {
                        "0000": {
                            "dataType": "20",
                            "access": "05",
                            "value": 3
                        },
                        "0001": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0002": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0003": {
                            "dataType": "20",
                            "access": "05",
                            "value": 2
                        },
                        "0004": {
                            "dataType": "42",
                            "access": "05",
                            "value": "GLEDOPTO"
                        },
                        "0005": {
                            "dataType": "42",
                            "access": "05",
                            "value": "GL-C-008P"
                        },
                        "0006": {
                            "dataType": "42",
                            "access": "05",
                            "value": "20211020"
                        },
                        "0007": {
                            "dataType": "30",
                            "access": "05",
                            "value": 0
                        },
                        "0008": {
                            "dataType": "30",
                            "access": "05",
                            "value": 255
                        },
                        "0009": {
                            "dataType": "30",
                            "access": "05",
                            "value": 255
                        },
                        "000A": {
                            "dataType": "41",
                            "access": "05",
                            "value": ""
                        },
                        "000B": {
                            "dataType": "42",
                            "access": "05",
                            "value": ""
                        },
                        "4000": {
                            "dataType": "42",
                            "access": "05",
                            "value": "11076802"
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0003": {
                    "attributes": {
                        "0000": {
                            "dataType": "21",
                            "access": "07",
                            "value": 0
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0004": {
                    "attributes": {
                        "0000": {
                            "dataType": "18",
                            "access": "05",
                            "value": "00"
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0005": {
                    "attributes": {
                        "0000": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0001": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0002": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0003": {
                            "dataType": "10",
                            "access": "05",
                            "value": 0
                        },
                        "0004": {
                            "dataType": "18",
                            "access": "05",
                            "value": 0
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0006": {
                    "attributes": {
                        "0000": {
                            "dataType": "10",
                            "access": "05",
                            "value": 1
                        },
                        "4000": {
                            "dataType": "10",
                            "access": "05",
                            "value": 1
                        },
                        "4001": {
                            "dataType": "21",
                            "access": "07",
                            "value": 0
                        },
                        "4002": {
                            "dataType": "21",
                            "access": "07",
                            "value": 0
                        },
                        "4003": {
                            "dataType": "30",
                            "access": "07",
                            "value": 255
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0008": {
                    "attributes": {
                        "0000": {
                            "dataType": "20",
                            "access": "05",
                            "value": 254
                        },
                        "0001": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "000F": {
                            "dataType": "18",
                            "access": "07",
                            "value": "00"
                        },
                        "4000": {
                            "dataType": "20",
                            "access": "07",
                            "value": 51
                        },
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                },
                "0300": {
                    "attributes": {
                        "0000": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0001": {
                            "dataType": "20",
                            "access": "05",
                            "value": 254
                        },
                        "0002": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0003": {
                            "dataType": "21",
                            "access": "05",
                            "value": 17623
                        },
                        "0004": {
                            "dataType": "21",
                            "access": "05",
                            "value": 43739
                        },
                        "0007": {
                            "dataType": "21",
                            "access": "05",
                            "value": 250
                        },
                        "0008": {
                            "dataType": "30",
                            "access": "05",
                            "value": 1
                        },
                        "000F": {
                            "dataType": "18",
                            "access": "07",
                            "value": "00"
                        },
                        "0010": {
                            "dataType": "20",
                            "access": "05",
                            "value": 5
                        },
                        "0011": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0012": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0013": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0015": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0016": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0017": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0019": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "001A": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "001B": {
                            "dataType": "20",
                            "access": "05",
                            "value": 0
                        },
                        "0020": {
                            "dataType": "21",
                            "access": "05",
                            "value": 0
                        },
                        "0021": {
                            "value": 0
                        },
                        "0022": {
                            "value": 0
                        },
                        "0024": {
                            "value": 0
                        },
                        "0025": {
                            "value": 0
                        },
                        "0026": {
                            "value": 0
                        },
                        "0028": {
                            "value": 0
                        }
                    }
                },
                "1000": {
                    "attributes": {
                        "FFFD": {
                            "dataType": "21",
                            "access": "05",
                            "value": 1
                        }
                    }
                }
            },
            "cliClusters": {
                "0019": {
                    "attributes": {
                        "0000": [],
                        "0001": [],
                        "0002": [],
                        "0006": [],
                        "FFFD": []
                    }
                }
            }
        },
        "F2": {
            "status": "00",
            "cliClusters": {
                "0021": {
                    "attributes": []
                }
            }
        },
        "00": {
            "status": "83",
            "statusMsg": "EP is NOT active"
        }
    }
}`

Voici le produit : https://www.amazon.fr/gp/product/B09872CWZH/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Apparemment déjà ajouté sur le plugin Zigbee de Jeedom : https://community.jeedom.com/t/demande-dajout-gledopto-gl-c-008p/61497

Merci 

Bonne soirée ;)

**Comment by tcharp38** [comment]
Hello

A decompresser dans core/config/devices
puis redemarrer demon
et refaire inclusion

[GL-C-008P_GLEDOPTO.zip](https://github.com/KiwiHC16/Abeille/files/8986345/GL-C-008P_GLEDOPTO.zip)

Je te laisse me trouver une image PNG sans arriere plan

**Comment by nawak86** [comment]
Bonjour, 

merci je vais l'ajoute de suite mais je ne pourrais pas tester avant ce soir.
sinon pour l'image : 
![GL-C-008P](https://user-images.githubusercontent.com/5274111/176687651-60c1efb7-77f3-48a4-8ac5-de61b600cb4c.png)

Bonne journée

**Comment by nawak86** [comment]
[GL-C-008P.zip](https://github.com/KiwiHC16/Abeille/files/9020128/GL-C-008P.zip)
je viens de faire le package avec image a mettre dans devices
j'essaye ce soir.
++

**Comment by nawak86** [comment]
[GL-C-008P.zip](https://github.com/KiwiHC16/Abeille/files/9022987/GL-C-008P.zip)
avec l'image à mettre dans Abeille/Images

J'ai inclus le fichier mais je n'ai pas de commandes j'ai bien redémarrer le démon avant.
![image](https://user-images.githubusercontent.com/5274111/176765166-53052f20-8269-4f52-8cb3-9942498b61a5.png)
![image](https://user-images.githubusercontent.com/5274111/176765179-1542ce08-cedb-49a9-9f80-76901a7bc8df.png)
![image](https://user-images.githubusercontent.com/5274111/176765217-27838324-e13d-4aa6-a040-ea41aab4a63c.png)

merci

Bonne soirée

**Comment by tcharp38** [comment]
Pas de commandes ?!
Peux tu refaire une inclusion ou juste faire "reinitialiser" via la page EQ/avancé
et me filer les logs ?

**Comment by nawak86** [comment]
oui c'est ça que tu voulais :
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/9029615/Abeille.txt)
Je ne sais pas pourquoi l'image n'est pas prise non plus.
merci

**Comment by tcharp38** [comment]
Salut @nawak86 
J'ai besoin des logs donc du package de logs, celui obtenu via la page support/telecharger tout.
Mais du coup tu es obligé de reinitilialiser à nouveau avant de me l'envoyer vu les logs sont tournants.

**Comment by nawak86** [comment]
Hello

ça marche je viens de le faire :
[AbeilleLogs-220705.tar.gz](https://github.com/KiwiHC16/Abeille/files/9048999/AbeilleLogs-220705.tar.gz)

J'espère que ca te suffira :) merci

++

**Comment by tcharp38** [comment]
Ouah ?!
Ce package est tres incomplet

![image](https://user-images.githubusercontent.com/35221038/178102405-676105ac-5aef-44e8-9e4e-70971e9b51b2.png)

Il devrait y avoir au moins 'Abeille' + 'AbeilleParser.log' + 'AbeilleCmd.log'.
T'es bien en mode debug ?

**Comment by nawak86** [comment]
Hello 

Je suis bien en debug j'ai rien d'autre que ça :
[AbeilleLogs-220711.tar.gz](https://github.com/KiwiHC16/Abeille/files/9087783/AbeilleLogs-220711.tar.gz)
![image](https://user-images.githubusercontent.com/5274111/178365363-44768a70-cd51-40c8-8c8f-5680ce328fd2.png)

je comprends pas :/

**Comment by tcharp38** [comment]
?!
Peux tu juste redemarrer le démon Abeille via la page de config, puis me filer le package de logs dans la foulée ?

**Comment by nawak86** [comment]
pas de soucis je viens de redémarrer le démon : 
[AbeilleLogs-220715.tar.gz](https://github.com/KiwiHC16/Abeille/files/9119037/AbeilleLogs-220715.tar.gz)

**Comment by nawak86** [comment]
et j'ai refais inclusion j'ai bien eu le message comme quoi il s'est réannoncé voici le pack de log:
[AbeilleLogs-220715 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9119065/AbeilleLogs-220715.1.tar.gz)

j'ai toujours 0 commandes

merci

**Comment by tcharp38** [comment]
Ca me perturbe.
Les logs parser et cmd par ex sont toujours vides.
Pour moi tu n'es pas en mode debug, ou ca n'est pas sauvegardé ou tu n'as pas redémarré.
Du coup je soupconne le cas "pas sauvegardé" avant de redemarrer.

Je crois qu'il faut j'ajoute une alerte qq part si pas mode "debug".

**Comment by nawak86** [comment]
LOL désolé je sais plus ce que j'ai fais mais si tu peux ajouter une alerte pourquoi pas je fais le teste plus tard quand je serais chez moi

**Comment by nawak86** [comment]
toujours la ?

**Comment by tcharp38** [comment]
Salut
Oui toujours la.

As tu pu basculer sur la derniere beta ?
Et si oui pourrais tu me regenerer un package de logs que je vois ou on en est ?
Merci

**Comment by nawak86** [comment]
désolé j'ai pas vu la notification de ta réponse, je viens de faire une maj : Version Abeille: 220916-STABLE-1

tu veux quoi ? un discovery dans chaque mode du controleur ?

+++

**Comment by tcharp38** [comment]
Deja juste un pacakge de logs en mode debug.
On a vu que qqch clochait dans tes derniers packages. Ils etaient quasi vides.

**Comment by nawak86** [comment]
j'ai fait un reset des log j'ai activé le debug et voila les logs après quelques minutes : 
[AbeilleLogs-220920.tar.gz](https://github.com/KiwiHC16/Abeille/files/9602649/AbeilleLogs-220920.tar.gz)
ps : j'ai pas fais d'inclusion

**Comment by tcharp38** [comment]
Il n'y a aucun log du parser par ex, donc tu n'es toujours pas en mode debug :(
https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by nawak86** [comment]
[AbeilleLogs-220923.tar.gz](https://github.com/KiwiHC16/Abeille/files/9629674/AbeilleLogs-220923.tar.gz)
et la ? j'avais peut être pas relancé abeille.
je suis passé aussi à 5000lignes
++

**Comment by tcharp38** [comment]
Parfait.
Tu as des logs maintenant.

Tu ne voudrais pas basculer sur la beta histoire d etre alignes ?

**Comment by tcharp38** [comment]
Salut @nawak86 
Serais tu par hasard toujours interessé ?
Si non je ferme cet antique sujet.
Merci

**Comment by nawak86** [comment]
Hello tu peux cloturer merci ;)
