### ISSUE TITLE
Inclusion volet profalux zigbee impossible depuis le changement de télécommande

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2404]
Bonjour,

J'ai du faire changer deux télécommandes qui consommaient beaucoup de pile mais pour ca le technicien à du faire un reset du volet et donc sortir le volet du réseau. Depuis je n'arrive plus à les intégrer au réseau que ce soit avec la nouvelle télécommande ou l'ancienne télécommande. j'utilise toujours la même procédure qui fonctionnait très bien jusque là. 
J'ai tout essayé mais rien n'y fait.
Merci pour votre aide.

**Comment by tcharp38** [comment]
Salut @Seby9576
Mode debug et logs... C'est un minimum si tu veux un retour utile.
Retente une inclusion et donne moi les logs que je jette un œil

**Comment by Seby9576** [comment]
Salut,

J'ai fait mais sur celle ci et j'ai vu qu'elle était closed du coup j'ai recréé un post en oubliant de mettre un lien #1994. Désolé

Voici la vu de abeille ou j'ai l'impression que j'ai beaucoup de device non reconnu (surement les télécommandes)
![image](https://user-images.githubusercontent.com/77990298/174674900-ad7879b9-833c-4583-9102-a3d23ce932b1.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-220620.tar.gz](https://github.com/KiwiHC16/Abeille/files/8943540/AbeilleLogs-220620.tar.gz)
Ca c'est les logs tout frais avec R+haut comme je faisait avant et avec mes anciennes télécommandes

Ceux dans l'autre poste c'était avec les nouvelles #1994

Merci

**Comment by tcharp38** [comment]
@Seby9576 
Trop tard pour faire une proposition ce soir, mais je crois avoir une piste, a tester demain. Je te tiens au jus.

**Comment by Seby9576** [comment]
Salut, de toute façon j'étais couché 😅

Je pourrais faire des tests à partir de 18h

**Comment by tcharp38** [comment]
Salut

Pour ecraser celui de core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/8955039/AbeilleParser.class.php.zip)

puis redemarrer
et refaire test d inclusion
et filer les logs

Sinon cette correction sera dans la beta de demain ... 220622-BETA-1

**Comment by Seby9576** [comment]
J'ai écrasé
redémarré les demons
Inclusion et les logs après 30 s

Inclusion faite vers 18h20 et toujours rien
[AbeilleLogs-220622.tar.gz](https://github.com/KiwiHC16/Abeille/files/8959575/AbeilleLogs-220622.tar.gz)

**Comment by tcharp38** [comment]
Voila mon analyse:

Zigate v1: Appli=0003, SDK=0321

- Le volet s'annonce à 18h20 (device announce)
  [2022-06-22 18:20:08] Abeille1, Type=004d/Device announce, Addr=7E20, ExtAddr=20918AFFFF0090F1, MACCapa=8E, Rejoin=00
  [2022-06-22 18:20:08]   EQ already known: Addr updated from 8B38 to 7E20
  [2022-06-22 18:20:08]   eq={"ieee":"20918AFFFF0090F1","capa":"","rxOnWhenIdle":1,"rejoin":"","status":"identifying","time":1655914770,"endPoints":null,"mainEp":"","manufId":null,"modelId":null,"location":null,"jsonId":"","jsonLocation":"","tuyaEF00":null}
  [2022-06-22 18:20:08]   Requesting active end points list

- Abeille l'interroge pour avoir des precisions (quels sont les End Points)
- mais à priori la requete ne part pas
  [2022-06-22 18:20:08] Abeille1, Type=8000/Status, Status=00/Success, SQN=09, PacketType=0045, Sent=02, SQNAPS=EA, NPDU=00, APDU=01
  [2022-06-22 18:20:08] Abeille1, Type=8012/APS data confirm, Status=00, Addr=7E20, SQNAPS=EA, NPDU=00, APDU=01
  [2022-06-22 18:20:09] Abeille1, Type=9999/Extended error, ExtStatus=87

Je ne comprends pas cette erreur 87

> 0x87 There are no free entries in the extended address table. The extended address table is configured in the config editor

je vais tacher d'en savoir + via l'equipe Zigate.

**Comment by Seby9576** [comment]
Salut,

Pour moi c'est la télécommande et elle est bien intégré dans mon réseau mais pas le volet

L'adresse courte est différente car c'est suite à un test ce matin et d'hier soir comme sur les logs mais IEEE est identique

![image](https://user-images.githubusercontent.com/77990298/175294713-8a011619-bfb3-4d61-b806-5f3f4c4aded6.png)

**Comment by Seby9576** [comment]
Dsl mais en regardant de plus prêt lors de l'inclusion ce sont deux devices en plus qui ce sont ajoutés et avec quasiment la même IEEE
![image](https://user-images.githubusercontent.com/77990298/175341937-0258fc9a-c04e-4faf-b14f-25f14a065ec8.png)

Ca serait pas le volet et la télécommande mais le volet ne serait pas reconnu ?

**Comment by tcharp38** [comment]
2 dev avec quasi la meme IEEE ca ressemble au volet + telecommande. D'ailleurs ils s'annoncent en meme temps.
Tu me files ton package de logs que je vois le status ?

**Comment by Seby9576** [comment]
Salut, oui en même temps mais pas d'annonce d'abeille. Je dois rafraîchir pour les voir.
Pour le packtage des logs il faut que je refasse une inclusion ?

**Comment by tcharp38** [comment]
J'avoue que je seche.
Aucune des 2 inclusions ne semble se passer correctement la.
Il n'y a pas d'identifiant du modele à utiliser donc Abeille n'a pas reçu assez d'infos de ces 2 equipements.

Tu as beaucoup d'équipements enregistrés sur cette zigate ?
Tu es capable d'inclure un type different, autre que volet Profalux ?

**Comment by Seby9576** [comment]
Est ce que l'identifiant peut être effacer comme avec la Zoé ? Volet changé en salon par exemple ? 
Oui j'ai pas mal d'équipement sur la zigate

J'ai pas fait de nouvelle inclusion, seulement des capteurs sur pile en out

**Comment by tcharp38** [comment]
Ca n'est pas un souci d'identifiant pour l'instant car ni le volet ni la telecommande ne repondent.
Si la zigate etait saturée ca pourrait surement donner ça, d'ou ma question concernant l'inclusion d'un autre type d'eq, et si possible un qui n'est pas déja entré dans ce reseau.

**Comment by Seby9576** [comment]
Je pense que tu as mis le doigt sur quelques choses car j'ai essayé d'inclure un détecteur de mouvement et c'est pareil
[AbeilleLogs-220627.tar.gz](https://github.com/KiwiHC16/Abeille/files/8994141/AbeilleLogs-220627.tar.gz)
![image](https://user-images.githubusercontent.com/77990298/175994412-ba6f1182-f67d-4aaa-996c-85dc7a90c796.png)

**Comment by Seby9576** [comment]
Après les volets étaient déjà présent avant donc entre deux j'avais rien rajouté

**Comment by Seby9576** [comment]
Question pour faire de la place  comment sortir toutes mes télécommandes de volet de mon réseau ? Elles me sont pas utiles mais quand je fais exclure il se passe rien et si je supprime de jeedom elle finissent par revenir. Commet dois je procéder stp?

**Comment by tcharp38** [comment]
Une info: l'erreur x87 qu'on voit parfois passer veut dire que la zigate est PLEINE.
Ca peut expliquer.

**Comment by Seby9576** [comment]
Sais tu comment enlever les télécommandes ded volets stp? J'ai l'impression que exclure ne fonctionne pas

**Comment by tcharp38** [comment]
Aucune possibilité à partir d'Abeille. Elles ne sont guere standard.
Mais si tu cherches à les enlever pour gagner de la place... pas possible. Le volet et sa telecommande doivent etre dans le meme reseau.

**Comment by Seby9576** [comment]
Je dois faire quoi rajouter une zigate ?

**Comment by tcharp38** [comment]
Je le crains.
Ou ajouter des routeurs. Je crois que la limitation total est differente du nombre de liaisons "directes" (prise en charge par la zigate sans passer par un routeur).

Je pense d'ailleurs que c'est pour ça qu'il avait créé la zigate Wifi.

**Comment by Seby9576** [comment]
D'après zigate le nombre d'équipement maximum serait de 40 en direct et 70 max. Je n'y suis pas non plus. De plus je persiste mais exclure ne fonctionne pas vu que les volets et télécommandes non reconnu reviennent sans cesse
![image](https://user-images.githubusercontent.com/77990298/176190765-35a3393c-77b7-416a-a822-788d6865696f.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-220628.tar.gz](https://github.com/KiwiHC16/Abeille/files/9002218/AbeilleLogs-220628.tar.gz)
J'ai supprimé deux prises zigbee et fais une tentative d'inclusion et c'est toujours pareil. :-(

**Comment by tcharp38** [comment]
Tu les as reellement exclues ?

Je vois 2 annonces dont la premiere qui se termine bien

> [2022-06-28 16:57:43] Abeille1, Type=004d/Device announce, Addr=24F0, ExtAddr=540F57FFFE74B61A, MACCapa=8E, Rejoin=00
> [2022-06-28 16:57:52]   EQ is supported with 'TS011F__TZ3000_cphmq0q7' identifier

Et celle du volet

> [2022-06-28 16:57:55] Abeille1, Type=004d/Device announce, Addr=08F2, ExtAddr=20918AFFFF0090F1, MACCapa=8E, Rejoin=00
> ...
> [2022-06-28 16:58:09] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=08F2, EP=00, ClustId=0005, SQNAPS=E5
> [2022-06-28 16:58:10] Abeille1, Type=9999/Extended error, ExtStatus=87

Bref 2 sorties peut etre mais une entrée avant le volet. Ca reste à la limite.

Peux tu via la page "reseau" forcer l'interrogation du reseau 
puis via la page support, me filer le fichier AbeilleLQI-Abeille1.json
![image](https://user-images.githubusercontent.com/35221038/176384045-21380037-0618-44b1-81af-22ad4d7dd1c1.png)

Il manque un status du nombre d equipements en direct et total

**Comment by Seby9576** [comment]
[AbeilleLQI-Abeille1.json.log](https://github.com/KiwiHC16/Abeille/files/9009807/AbeilleLQI-Abeille1.json.log)
J'ai vidé les logs avant de le faire

Merci

**Comment by Seby9576** [comment]
[AbeilleLogs-220629.tar.gz](https://github.com/KiwiHC16/Abeille/files/9010173/AbeilleLogs-220629.tar.gz)
En enlevant la deuxième prises j'ai bien inclus le volet mais sans le télécommande. Ce qui doit correspondre a ce que tu disais (trop de device), Je pense que je suis toujours trop encombrer pour que la télécommande rentre avec le volet.

Si je prend un deuxième zigate est ce ca sera deux réseaux différent ou seulement une prolongation du premier ?

Dois je prendre la V2 pour être mieux ?

**Comment by tcharp38** [comment]
Oui 2nd zigate = 2nd reseau.
Donc les equipements de l'un ne peuvent causer (via Zigbee) à l'autre.

La zigate v1 n'est plus en vente je crois et n'a plus de mises à jour.
La v2 supporte bien + d'équipements, et a des mises à jour en cours, mais n'est pas encore super mature d'apres les retours.
Autre solution.. une v1 d occase. Il y en a un paquet sur le boncoin.

**Comment by Seby9576** [comment]
Je n'arrive pas en exclure ceux sur piles donc impossible de faire de la place. Donc même si je prend une clé supplémentaire je ne pourrais rien faire.

As tu vu si je dépassais la quantité maximum ? Il y a t il un autre moyen que de faire exclure ?
Pour info mon volet s'inclus seul mais je sais pas si c'est à cause de ca mais le volet répond au commandes abeille mais il fait un simple aller et retour.

**Comment by tcharp38** [comment]
Pour exclure un equipement sur pile tu dois pouvoir le reveiller immediatement apres l'envoi de l'ordre de sortie.
Pas toujours possible.
Au pire il le fait lui meme si tu peux lui forcer un reset.

Les volets qui ne font qu'un AR c est surement à cause du calibrage pas terminé (2 AR complets necessaires apres reset).

**Comment by Seby9576** [comment]
C'est ce que je fais, j'appuie sur le bouton dans la foulée. J'ai essayé un  appui court et aussi un de 3secondes.
C'est pas simple cette histoire. Du coup j'ai combien d'équipement dans la zigate ?

Puis je transférer un équipement d'une zigate à l'autre quand j'aurais les deux ?

**Comment by tcharp38** [comment]
Non pas simple. Le reset de chaque equipement est particulier.

J'avoue que totaliser les equipements est un manque. Je ne sais meme pas trop comment m'y prendre.

Quant à "transferer", tu n'as pas d'autre choix de lui forcer l'exclusion d'un reseau et reintegration dans l'autre, mais si il est toujours connu de Jeedom (pas supprimé), tu gardes son ID/nom et autres modifs que tu peux avoir fait.

**Comment by Seby9576** [comment]
[AbeilleLogs-220629 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9012834/AbeilleLogs-220629.1.tar.gz)
J'ai encore supprimé un équipement sur secteur et c'est toujours pareil lors de l'inclusion du volet, je perd la télécommande et la volet reste bloqué en position avec seulement des va et viens. J'ai vidé les logs avant de faire l'inclusion donc ca sera au début.

Toujours impossible avec ceux sur pile malgré plusieurs tentatives ( une vingtaine avec différentes méthodes )

Merci

**Comment by Seby9576** [comment]
Si je l'inclus avec ma nouvelle clé est ce qu'il va intégrer le nouveau réseau et sortir de l'ancien ? car je n'arrive pas du tout a exclure les éléments sur piles. Ca me fait un peu rager...

**Comment by Seby9576** [comment]
Salut comment on fait pour mettre le port usb quand on a un Hub stp ?

**Comment by Seby9576** [comment]
[AbeilleLogs-220704.tar.gz](https://github.com/KiwiHC16/Abeille/files/9041261/AbeilleLogs-220704.tar.gz)
Salut,

J'ai fait une tentative d'inclusion du volet et j'ai eu le volet et la télécommande mais j'ai quand même perdu la télécommande. La procédure est elle différente avec les nouveaux modèles de télécommande ? C'est la question que je me pose. Je te joins les logs pour voir si tu peux voir quelque chose la dessus.

Le télécommande qui est apparu
![image](https://user-images.githubusercontent.com/77990298/177198385-f3af9f1f-9f32-4917-9af4-3c26140fda2b.png)

Et le volet (même IEEE que plus haut)
![image](https://user-images.githubusercontent.com/77990298/177198489-018de1b6-fe4c-4f39-ade7-d7977e3ff368.png)

**Comment by tcharp38** [comment]
Hello
Désolé pour la latence. 

Je pensais qu'une nouvelle procedure etait necessaire pour les nouveaux volets, mais peut etre que les telecommandes aussi se comportent differement.
Quelle procédure utilises tu exactement ?

D'autre part je vois un equipement qui s'annonce souvent mais ca n'aboutit pas... ieee=94DEB8FFFE47EDC2.
Une idée de quoi il s'agit ?
Ha et ca n'abouti pas à cause de l'err 87 donc zigate full. Tu es dans une situation que je n'ai jamais rencontré.
En meme temps je n'ai pas autant d'equipements que toi.

Pour qu'un sensor sur pile sorte, le mieux est de NE PAS etre en mode inclusion et lui faire un reset.
Il va quitter le reseau et ne devrait pas pouvoir le rejoindre, ou il va rejoindre le reseau ouvert si tu as une autre zigate en mode inclusion.

**Comment by Seby9576** [comment]
Salut,

Procédure r+haut.  Elle réagit différemment au niveau du voyant ça c'est sûr. 

Ça n'aboutit toujours pas avec tout ce qu'il a plus ? J'ai reset 4 équipements sur pile qui sont toujours dans abeille mais qui sont en out
 Pourquoi j'ai bien eu les deux annonces alors ?
Pour les équipements qui s'annoncent je ne peux pas te dire vu qu'ils ne sont pas reconnu. J'en ai 4 comme ça.

**Comment by tcharp38** [comment]
Je ne comprends pas comment réagit la zigate mais tes questions font du sens.

Les annonces montrent que l'equipement tente de rejoindre le reseau mais ca n'est pas pour autant qu'il est "accepté" et pour le coup la zigate ne veut pas.

Quant à la sequence, un truc qui me derange est le "STOP". J'aurais tendance à ne PAS le faire. Je crois que ca rentre en conflit avec le controle coté Jeedom. A tenter à l occase si tu n'en as pas marre.

**Comment by Seby9576** [comment]
Normalement je ne fais pas de stop mais les nouvelles télécommandes ne réagissent pas pareil. Ca clignote bleu et pendant longtemps comme si elle attendait quelque chose. Je vais refaire des tests ce week end car j'ai fait de la place.

**Comment by Seby9576** [comment]
[AbeilleLogs-220709.tar.gz](https://github.com/KiwiHC16/Abeille/files/9077521/AbeilleLogs-220709.tar.gz)
Test inclusion avec novelle telecommande

R+ Haut et j'ai touché, au final j'ai perdu la telecommande et j'ai pas le volet

**Comment by Seby9576** [comment]
[AbeilleLogs-220709 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9077547/AbeilleLogs-220709.1.tar.gz)
la avec l'ancienne et dans les deux cas je n'ai pas fait de stop.

**Comment by Seby9576** [comment]
Et la il y a pratiquement plus que mes volets sur la zigate
![image](https://user-images.githubusercontent.com/77990298/178115343-3caf2cee-4b76-401b-a599-6f148b7b7e21.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-220710.tar.gz](https://github.com/KiwiHC16/Abeille/files/9079432/AbeilleLogs-220710.tar.gz)
La un test avec volet et telecommande que j'avais deja inclus dans le réseaux mais quie maintenant ca ne fonctionne plus. mais cette fois j'ai pas perdu le telecommande

**Comment by Seby9576** [comment]
Bon j'ai pu inclure un volet sur le popp et le plugin zigbee avec l'ancienne telecommande mais toujours impossible sur la zigate

**Comment by Seby9576** [comment]
La sur le deuxième volets j'ai deux device non reconnu et j'ai pas perdu la télécommande
[AbeilleLogs-220713.tar.gz](https://github.com/KiwiHC16/Abeille/files/9104000/AbeilleLogs-220713.tar.gz)
@tcharp38 tu as laché l'affaire ?

**Comment by tcharp38** [comment]
Salut @Seby9576 
Non je n'ai pas laché.

Je vois bien 2 annonces en meme temps de:
20918AFFFF009104
et
20918AFFFF0090FF

Donc j'en conclus qu'il s'agit d'un autre couple volet/telecommande que celui dont a parlé avant puisque IEEE differente.
Ceci etant la encore,
- ils s'annoncent
- Abeille les interrogent pour avoir des infos
- mais aucune reponse

Le pb ne vient pas des volets et bel et bien de l'etat de la zigate.
Je vois trop d erreurs juste avant.
Et comme l erreur qui revient souvent c'est zigate pleine, je crois qu'elle est juste dans un sale etat (corrompue).

Saurais tu me dire depuis que cette zigate existe, quand as tu refait un appairage complet (erase PDM) ?

**Comment by Seby9576** [comment]
Salut,

Que veux tu dire par appairage complet ?

Ça me dit rien ton erase pdm. Ça consiste en quoi ? Quelles sont les risques ? 

Merci

**Comment by tcharp38** [comment]
Appairage complet c'est partir d'une zigate vierge (elle ne connait aucun equipement).

A force de faire des manips et changer de version de FW, il se peut que ses tables internes soient corrompues.
Du coup j'aurais tendance à la remettre à zero (mise à jour en version OPDM 3.21 + erase PDM + reappairage complet).

Le reappairage = reinclusion de tous tes modules donc oui ca peut etre du boulot.

Note que le passage en version ODPM (0004-0321 au lieu de 0003-0321) permettra
- d avoir un truc à jour. Table optimisée + propre (aux dires de l equipe Zigate)
- supporter + d equipements car optimisée

C'est clair ?

**Comment by Seby9576** [comment]
Oui c'est clair,  mais comme tu dis c'est du job. La clé a été mis à jours depuis peu mais je saurais dire quoi.
Bon j'ai pas vraiment le choix mais si c'est pas ça j'aurais plus deux volets hs mais 16. Refaire scénarios, virtuels etc.

**Comment by tcharp38** [comment]
Je comprends ta frustration.
Je suis passé par la.

N avais tu pas une autre + vieille ? Une v1 ?

**Comment by Seby9576** [comment]
Non pas d'autre mais si il faut en acheter une autre why not.

![image](https://user-images.githubusercontent.com/77990298/179253200-ea5df12c-5de3-4fd2-8bce-0aa9a231d4fe.png)

Avec ca on peut pas transférer sans peine ?

**Comment by tcharp38** [comment]
pas sans peine non.
Avec plusieurs zigates (ou autre), il faut ouvrir le futur reseau (mode inclusion) et forcer le periph à quitter le courant.
Il devrait tenter de se rattacher à celui ouvert.

**Comment by Seby9576** [comment]
ok bon je te laisse clôturer le sujet. Car la solution au pb de départ c'est d'inclure les volets avec les anciennes télécommandes puis inclure la nouvelle de le réseau puis ajouter la nouvelle télécommande  (3.0) au volet.
Manip : haut + bas puis stop -> pendant les va et viens (quelques secondes) Fx2  puis haut
la les deux télécommandes sont opérationnelles et on peut enlever les piles de l'ancienne qui était défaillante (conso de piles excessive )

J'ai une nouvelle demande sur #1994 si tu as un peu de temps.

Merci
