### ISSUE TITLE
Inclusion volets gen 1 Profalux

### ISSUE THREAD

**Issue by LowGiiK** [KiwiHC16/Abeille#2405]
> Ce qui marche chez moi:
> 
> ### Étape 1: Remise à zéro de la télécommande et du volet.
> * Tout d'abord monter le **volet au maximum**.
> * Appuyer **5x sur le bouton R**
>   La télécommande va clignoter **vert** puis **rouge 3x**.
>   Le volet va faire un ou deux va et vient.
>   Attendre que la télécommande **ne clignote plus**.
> * Dans la minute qui suit, appuyer sur **STOP** pour confirmer que la télécommande est bien celle du volet en question.
>   Le volet va faire un va et vient puis 2 à la suite quelques secondes plus tard.
> * On test la télécommande en faisant la **flèche du BAS**.
>   (Si jamais les commandes du votre volet sont inversées: appuyer **1x sur F** et confirmer avec **STOP**
>   Le volet va faire un va et vient).
> * Arrêter le **volet à mi-hauteur**.
> 
> ### Étape 2: Inclusion du volet
> * Mettre le plugin Abeille en **mode inclusion**
>   (Appuyer sur le bouton **"+"**  depuis le plugin Abeille -> la clé Zigate doit **clignoter bleue**).
>   (Si d'autres volets sont déjà dans le réseau ils signalent l'ouverture du réseau en faisant un va et vient).
> * Appuyer **1x sur R**.
> * Appuyer ensuite sur la **flèche du HAUT**.
>   Le moteur devrait faire plusieurs va et vient … **ATTENDRE** que la télécommande **NE CLIGNOTTE PLUS DU TOUT** !!
> * Seulement à ce moment, appuyer sur la touche **STOP** de la télécommande.
> * Ouvrir et fermer votre volet complètement **2 fois**.
>   (Dans mon cas avec le volet à mi hauteur je faisait: HAUT, BAS, HAUT, BAS, HAUT)
>   A la fin des 2 cycles, le volet fera un petit va et vient. S'il ne le fait pas, pas de panique. Au pire des cas vous n'aurez
>   associé que la télécommande mais vous n'aurez pas perdu la liaison volet-commande).
> * Rafraichir le dashboard d'Abeille et votre volet devrait apparaitre.

Bonjour à tous

Je suis totalement novice et je souhaiterais relier mes volets Profalux à Jeedom via une Zigate USB 2 et le plugin Abeille.

J'ai réussi à appairer un volet pour faire des tests.
Cependant je n'ai pas les bonne commandes dans l'onglet du même nom sur la page de la télécommande associée (télécommande classique je n'ai pas la Zoé).
Je lis partout sur github qu'il faut passer sur le cluster  8 pour avoir le level control mais je ne sais pas où ça se trouve ni comment faire.

Debian 10.12
Jeedom v4.2.19
Zigate v0005-0321

![image](https://user-images.githubusercontent.com/107943884/174856574-4f5215ca-c54b-4421-8ba2-7e43b210c669.png)

![image](https://user-images.githubusercontent.com/107943884/174856960-94137547-a8ef-4257-828a-be2aac555654.png)

![image](https://user-images.githubusercontent.com/107943884/174856813-9bcea472-1c51-4929-ac5e-d7467c699f60.png)

Merci d'avance pour votre aide

**Comment by tcharp38** [comment]
Salut @LowGiiK 
Tu ne peux rien faire avec la telecommande d'un point de vue Jeedom.

Par contre le volet doit etre lui aussi inclut dans jeedom et la tu peux le controler ou recevoir ses retours (level).

Donc cote Jeedom, oublie la telecommande. Elle est dans le reseau mais c'est tout. Aucun interet ni possibilité.

**Comment by LowGiiK** [comment]
Merci de ta réponse @tcharp38!

Pour ajouter un volet on est bien d'accord qu'il faut prendre la télécommande de ce même volet et appuyer 1xR puis 1x haut et passer en mode inclusion dans Abeille? Parce que de mon côté Abeille ne chope que la télécommande pendant cette manip.

Désolé des questions qui sont banales et qui ont été posées mille fois mais malgré tout ce que je lis sur les points de ce github mes capacités en informatique sont vite atteintes.

**Comment by tcharp38** [comment]
Ca me semble cohérent.
Néanmoins sache que les volets recents peuvent etre recalcitrants. Tout n'est pas clair au vu des deboires des utilisateurs, et ce meme sans Jeedom/Abeille.

Il faudrait que tu
- passes en mode debug
- redemarre Abeille
- refais une inclusion de volet
- et file moi le package de logs de la page support/telecharger tout.

Penses à regarder cette doc: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by LowGiiK** [comment]
Voici les logs :
[AbeilleLogs-220622.tar.gz](https://github.com/KiwiHC16/Abeille/files/8958005/AbeilleLogs-220622.tar.gz)

**Comment by tcharp38** [comment]
Le mode debug n'est pas pris en compte.
Peut etre parce que 'jai oublié de dire "sauvegarder" avant de redemarrer :(

**Comment by LowGiiK** [comment]
En effet je n'ais pas sauvegardé la petite fenêtre...
En mode Debug rien ne s'ajoute à Abeille, ni même la télécommande.
Je ne sais pas si cela se voit dans les logs:

[AbeilleLogs-220622.tar.gz](https://github.com/KiwiHC16/Abeille/files/8959900/AbeilleLogs-220622.tar.gz)

**Comment by LowGiiK** [comment]
_En effet je n'ais pas sauvegardé la petite fenêtre...
En mode Debug rien ne s'ajoute à Abeille, ni même la télécommande.
Je ne sais pas si cela se voit dans les logs:_


Edit,
Ca viens de fonctionner pour le premier volet! 
J'ai fait une fausse manip en voulant réessayer du coup j'ai dû couper électriquement mon volet et Faire les étape D, E, F de la notice puis j'ai suivi la procédure complète de ce lien (pas uniquement 1xR et 1xHaut) : https://kiwihc16.github.io/AbeilleDoc/devices/Profalux.html

La notice: (Même si mes volets ont été installés en avril 2021 je me suis référé à la doc après 09/2021)
[Notice.SAV.Moteur.Zigbee.-.A.partir.de.septembre.2021.-.NSAV061.pdf](https://github.com/KiwiHC16/Abeille/files/8960026/Notice.SAV.Moteur.Zigbee.-.A.partir.de.septembre.2021.-.NSAV061.pdf)

![image](https://user-images.githubusercontent.com/107943884/175099814-83874212-e37d-4141-bd04-731ca73f4c68.png)

Et les logs qui vont avec au cas ou:
[AbeilleLogs-220622.tar.gz](https://github.com/KiwiHC16/Abeille/files/8960056/AbeilleLogs-220622.tar.gz)

Par contre est-ce normal que le premier volet fasse parfois des vas et viens en même temps que l'ajout d'un second?
J'ai tenté d'en ajouter 2 autres mais la manipulation a échouée. Ils sont restés en bas au moment de l'ajout dans Abeille. J'ai du appuyer trop tôt sur STOP, je n'ai pas pu faire les 2 AR.  Ils sont bien reconnu dans Jeedom mais plus par les télécommandes et ils semblent tout deux avoir des courses très très faibles.
Je suis bon pour les remettre à zéro demain.

**Comment by tcharp38** [comment]
Bon sans regarder les logs, ce que tu décris me parle.

- Tous les volets qui sont deja dans le reseau vont signaler par un AR, soit l entree en mode inclusion, soit l'arrivée d'un nouveau periph dans le reseau. Donc AR normal
- Tout volet qui a subit un reset (ex: 5xR), doit etre recalibré. Tu dois lui faire faire 2 AR complets. Il va alors signaler la fin par un AR.

Pour moi tes volets sont de la premiere generation (identification faite via l'attribut "location"="volet" car ne renvoi pas le "modelId").

J'avoue que l'inclusion des Profalux n'a jamais été claire.

**Comment by LowGiiK** [comment]
L'association dans Jeedom s'est bien passée.
Les volets sont bien de la première génération (N° de modèle commençant par C18...). 
Cependant je peux certifier que pour moi la procédure diffère sinon mon volet reste bloqué en bas et se déconnecte de sa télécommande. Seule solution -> Remise à zéro via câblage électrique  du moteur (fil bleu et noir).

Ce qui marche chez moi:

### Étape 1: Remise à zéro de la télécommande et du volet.
- Tout d'abord monter le **volet au maximum**.

- Appuyer **5x sur le bouton R**
           La télécommande va clignoter **vert** puis **rouge 3x**.
           Le volet va faire un ou deux va et vient.
           Attendre que la télécommande **ne clignote plus**.

- Dans la minute qui suit, appuyer sur **STOP** pour confirmer que la télécommande est bien celle du volet en question.
           Le volet va faire un va et vient puis 2 à la suite quelques secondes plus tard.

- On test la télécommande en faisant la **flèche du BAS**.
           (Si jamais les commandes du votre volet sont inversées: appuyer **1x sur F** et confirmer avec **STOP**
            Le volet va faire un va et vient).

- Arrêter le **volet à mi-hauteur**.

### Étape 2: Inclusion du volet

- Mettre le plugin Abeille en **mode inclusion**
           (Appuyer sur le bouton **"+"**  depuis le plugin Abeille -> la clé Zigate doit **clignoter bleue**).
           (Si d'autres volets sont déjà dans le réseau ils signalent l'ouverture du réseau en faisant un va et vient).

- Appuyer **1x sur R**.
- Appuyer ensuite sur la **flèche du HAUT**.
           Le moteur devrait faire plusieurs va et vient … **ATTENDRE** que la télécommande **NE CLIGNOTTE PLUS DU TOUT** !!

- Seulement à ce moment, appuyer sur la touche **STOP** de la télécommande.

- Ouvrir et fermer votre volet complètement **2 fois**.
           (Dans mon cas avec le volet à mi hauteur je faisait: HAUT, BAS, HAUT, BAS, HAUT)
           A la fin des 2 cycles, le volet fera un petit va et vient. S'il ne le fait pas, pas de panique. Au pire des cas vous n'aurez 
           associé que la télécommande mais vous n'aurez pas perdu la liaison volet-commande).

- Rafraichir le dashboard d'Abeille et votre volet devrait apparaitre.

NB: entre chaque ajout de volet de refermait avec le bouton **"-"** le mode inclusion et j'allait vérifier que la Zigate ne clignotait plus.

Je clos le point et j'attache ma réponse en début de sujet.
Merci encore @tcharp38
