### ISSUE TITLE
Support mhcozy ZG-005-RF 4 chan relay (id = TS0004, _TZ3000_excgg5kb)

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2408]
![node_MHCOZY-ZG-005-RF](https://user-images.githubusercontent.com/91745100/175765580-fc3e99cc-2b94-4cea-939f-dc65328ee28e.png)
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/8984219/discovery.zip)

**Comment by chrisb13790** [comment]
Dans la partie commande j ai rien normal?

**Comment by tcharp38** [comment]
Salut
Je creuse.

L image est de tres mauvaise qualité. On ne peut rien lire dessus.
Quel est le modele en question ? Je soupconne que ce n'est pas ZG-0005-RF. Ca commence plutot par TYxxx
Ou alors la photo n'est pas la bonne.

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices
redemarrer demon
refaire inclusion

[TS0004__TZ3000_excgg5kb.zip](https://github.com/KiwiHC16/Abeille/files/8986313/TS0004__TZ3000_excgg5kb.zip)

Je te laisse me trouver une image de meilleure qualité.
Et confirmer que la ref est bien ZG-0005-RF

**Comment by chrisb13790** [comment]
![ZG-005-RF](https://user-images.githubusercontent.com/91745100/175809287-1feb4df8-63b1-4cb5-bb80-0fcdf811d600.jpg)
pour la ref je confirm c est ce qu il y a noté sur le boitier apres tu le retrouve sous d autre marque avec la meme ref

**Comment by chrisb13790** [comment]
instal faite dans commande il manque des commandes
les actions sur les 4 relais 
le mode de foctionnement (3 modes)

**Comment by tcharp38** [comment]
Merci pour l'image. Bien meilleure maintenant.

De quelles actions parles tu ? On X et Off X ca ne suffit pas ?
Quant au mode, aucune idée de quoi tu parles. Si tu as une doc ou un lien ca peut servir.

**Comment by chrisb13790** [comment]
https://www.amazon.fr/dp/B09XGMQ449?ref_=cm_sw_r_ud_dp_MFPVANZK32212KCV8FNX
-Il y a 3 modes differents:
Indépendant momentané 
Indépendant permanent 
Ou bascule quand 1 en on les autres en off
- 4 relais donc il devrait avoir 4 on et 4 off hors j en ai aucun qui apparaît 
![Screenshot_20220626-232940_Samsung Internet](https://user-images.githubusercontent.com/91745100/175834463-be8844c4-e4b9-4817-a466-35980613ec9c.jpg)

**Comment by tcharp38** [comment]
Ha ben clairement ca n'est pas le modele que je t'ai filé qui a servi à l inclusion.

A verifier via l'onglet "avancé" => "Identifiant modele"

**Comment by chrisb13790** [comment]
![Screenshot_20220627-154349](https://user-images.githubusercontent.com/91745100/175956652-22b261c1-91b8-4d4e-a496-dbf0d8b0af22.png)

**Comment by tcharp38** [comment]
Ok tu l'avais mis dans "core/devices" ou "core/devices_local" ?

**Comment by chrisb13790** [comment]
Je l ai mis dans abeille/core/device, mais j' ai regardé il y est aussi dans device local

**Comment by tcharp38** [comment]
La version "device_local" est à virer.
Puis redemarrer Abeille et refaire inclusion.

Par defaut il prend toujours le modele local/custom/user. Donc qu'il est la le modele officiel n est pas utilisé.

Note que ce modele est dispo dans la beta de demain: 220628-BETA-1

**Comment by chrisb13790** [comment]
re 
effacement du modèle local, re-inclusion ok
manque juste le choix du mode de fonctionnement

**Comment by tcharp38** [comment]
Pour ca j'ai besoin de pistes.
Si il y a un bouton pour changer ca, peux tu l'actionner, noter l'heure et me filer le package de logs dans la foulée ?
Je veux essayer de voir comment est géré ce "mode"

**Comment by chrisb13790** [comment]
Ça marche j essayé ça ce soir

**Comment by chrisb13790** [comment]
[AbeilleLogs-220629.tar.gz](https://github.com/KiwiHC16/Abeille/files/9011378/AbeilleLogs-220629.tar.gz)
voici le log 16h17/16h18 changement de mode le dernier selectioné est momentané(off appui sur bouton 0.5s on et retour en off)
ordre des modes momentané/independant/bascule(si r1 on les autres off, demande sur un autre relais celui ci passe en on et les autres en off)

**Comment by tcharp38** [comment]
Bon je ne vois rien passer de particulier concernant le changement de mode.
Faut donc creuser sur le net pour comprendre comment on fait ca.

Mais je vois que ce device fait beaucoup de reporting, quasi toutes les 4sec. Je pige pas pourquoi il est aussi bavard.

**Comment by chrisb13790** [comment]
c est un ptit bavard lol omment puis je t aider ?

**Comment by tcharp38** [comment]
Bavard n'est pas forcement une bonne chose. Ca peut pourrir le reseau avec des infos inutiles.
Malheureusement pas la premiere fois que je vois ca d'un equipement Tuya. C'est crade.

Pour avancer sur le mode il faut trouver par quel biais on fait ca.
C'est du specifique Tuya, rien de standard, alors faut esperer que qqn a deja creusé.
Bref faut scruter le net à la recherche d'une piste

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Tu as plusieurs sujets ouverts mais il faudra qu'on reprenne celui la aussi :)

**Comment by chrisb13790** [comment]
Oui mais celui ci n est pas opérationnel donc pas pressé

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Toujours pas opérationnel ? Meme pour du test ?

**Comment by chrisb13790** [comment]
Non pas en opération mais je peux l allumer pour du test si tu veux , j ai
toujours pas basculer en beta ni suivi si il y avait du timeout

**Comment by tcharp38** [comment]
Tout dépend quel temps tu as, et si tu peux passer en beta.
Mais le jour ou ca arrive alors il faut deja juste pouvoir le brancher pour le piloter en mode test.
Bref... fais signe

**Comment by chrisb13790** [comment]
Ça marche j essaye ça en fin de semaine

**Comment by Jeedom122** [comment]
Bonjour,
Je viens d'installer ZG-003-RF, même chose que le ZG-005-RF, seul l'alim change, modèle 7-32V (ZG-003-RF) et un modèle 85-250V (ZG-005-RF), par contre, les deux réf utilisent aussi une alim 5 v (que j'utilise).
Je pensais que l'inclusion se passerait bien après lecture du post, mais que nenni.
Alors je le relance, voici les infos:
[AbeilleLogs-240106.tar.gz](https://github.com/KiwiHC16/Abeille/files/13850870/AbeilleLogs-240106.tar.gz)
[discovery-TS0004__TZ3000_u3oupgdy.json](https://github.com/KiwiHC16/Abeille/files/13850873/discovery-TS0004__TZ3000_u3oupgdy.json)
et l'image
![node_1-ZigBee-ZG-003-RF](https://github.com/KiwiHC16/Abeille/assets/104787819/ca00a1d1-5a78-42d2-a8be-ced1e63a0b53)
Par contre le changement de mode me semble pas utile une fois sélection sur l'appareil.
Plus d'infos [ICI](https://github.com/zigpy/zha-device-handlers/issues/2538)
Merci @tcharp38 pour ton aide.

**Comment by chrisb13790** [comment]
Salut
Je viens de basculer en beta et rebrancher si besoin


Le dim. 26 nov. 2023, 17:22, chris barcelone ***@***.***> a
écrit :

> Non pas en opération mais je peux l allumer pour du test si tu veux , j ai
> toujours pas basculer en beta ni suivi si il y avait du timeout
>
>

**Comment by tcharp38** [comment]
@Jeedom122 
Le ZG-003-RF a les memes commandes que le 005 ?
Pour l'image je prefere la version "en boitier" vu que c'est ce que tu achetes.
D'autre part ton modèle est vendu sous quelle marque ?

**Comment by Jeedom122** [comment]
@tcharp38 , effectivement ce sont les mêmes appareils, vendu sous la marque [Tuya (sans boitier)](https://www.aliexpress.com/item/1005002519598661.html?spm=a2g0o.order_detail.order_detail_item.3.1372f19cEc65IK) Plus d'info [ICI](https://www.sigalou-domotique.fr/je-teste-le-smart-switch-zg-005-rf) et [ICI](https://www.domotique-store.fr/domotique/usages/controle-acces-domotique-a-distance/actionneurs-pour-portes-de-garages-et-portails/1753-module-actionneur-zigbee-4-sorties-libres-de-potentiel-a-contact-sec-au-format-din.html)

**Comment by tcharp38** [comment]
@Jeedom122 
Voila le modele qui sera dans la prochaine beta
[TS0004__TZ3000_excgg5kb.zip](https://github.com/KiwiHC16/Abeille/files/13853160/TS0004__TZ3000_excgg5kb.zip)

@chrisb13790 
Ton modèle est Mhcosy ZG-005-RF ou Mhcosy TYWD 4ch-RF ?
Je veux changer l'image degueu par la bonne.

**Comment by chrisb13790** [comment]
J ai trouvé ceci ci ça peut aider
https://www.sigalou-domotique.fr/je-teste-le-smart-switch-zg-005-rf

Le dim. 7 janv. 2024 à 14:27, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
Mon modèle est le mhcozy zg-005-rf

Le dim. 7 janv. 2024, 14:37, chris barcelone ***@***.***> a
écrit :

**Comment by Jeedom122** [comment]
Je viens d'installer le fichier "TS0004__TZ3000_excgg5kb.zip" dézippé dans le dossier /core/device, relancé Abeille, voici le résultat après une inclusion ?

![2024-01-07_182201](https://github.com/KiwiHC16/Abeille/assets/104787819/64b47d93-150d-49d1-8ba2-f67c9ab4810c)

Avec ce message
![2024-01-07_182704](https://github.com/KiwiHC16/Abeille/assets/104787819/f2cae55b-353e-42f8-8921-2c12de5c04b0)

**Comment by tcharp38** [comment]
Ha c'est un pb connu et fixé.

A decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13855033/AbeilleParser.class.php.zip)

supprimer equipement
puis redemarrer démon
refaire inclusion

**Comment by Jeedom122** [comment]
Parfait, tout fonctionne, je n'en doutait pas ;)
Merci @tcharp38 pour le temps passé à régler nos problèmes :)
Bonne journée...

**Comment by tcharp38** [comment]
@Jeedom122 
Cool.

@chrisb13790 
T'es en ligne ? On peut fermer le sujet ou il subsiste un souci ?

**Comment by chrisb13790** [comment]
Pour moi pas de souci , la seule fonctionnalité c est rajouté le mode de
fonctionnement, sinon on peux fermer

**Comment by tcharp38** [comment]
Ha oui il te manque le mode, donc non on ne ferme pas tout de suite.

**Comment by tcharp38** [comment]
Salut @chrisb13790 

Pour le controle du mode,  je ne trouve rien sur le net. La plupart des systemes ne semblent pas l'implementer.
Mais on peut faire qq essais si tu es partant ? L'info se cache forcement dans un cluster privé. Ca revient donc a essayer de deviner ou.

Pour memo: piste = cluster E001, attribut D010 (type 30/enum8)

**Comment by chrisb13790** [comment]
Salut,
oui pas de souci
Le module est toujours branché mais inutilisé pour le moment

**Comment by tcharp38** [comment]
Ok peux tu changer le mode et noter l 'heure,
puis me filer le package de logs ?
je voudrais voir si une info remonte et laquelle.

Merci

**Comment by chrisb13790** [comment]
Salut
Fin de semaine je vais avoir un peu de temps pour m occuper de notre topic

**Comment by chrisb13790** [comment]
salut,
desolé pour l absence beaucoup de boulot,
 a partir de de main je vais avoir du temps pour faire des test et autre,
je vais poser une alarme lexman / enki en protocole zigbee si ca t
interesse pour faire des remontées sur jeedom si c est possible et s
occuper de module
4 relais , tiens moi au jus .
cdt

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tcharp38** [comment]
Salut
Pas de soucis. J'atteri à peine donc je n'étais pas dispo depuis qq semaines.
A toi la balle

**Comment by chrisb13790** [comment]
salut
j ai mis a jour le plugin version beta 2024-07-11 01:00:26   et je pense qu
on a du boulot :-)

**Comment by tcharp38** [comment]
Ha m..
Pas bon signe cette phrase :(

**Comment by chrisb13790** [comment]
Ma zigate est en 3.21 je pense que la première chose a faire et upgrade le
firmware mais je me rappel plus si legacy ou opdm

**Comment by tcharp38** [comment]
0004-0321 => OPDM
0003-0321 => Legacy

**Comment by chrisb13790** [comment]
Super merci

**Comment by chrisb13790** [comment]
maj firm[image: image.png]
ware ok, pour tester j ai reconnecté deux capteurs, 1 contact de porte et
une sonde temperature j ai essayé le repeteur suite mais sans succes

Le ven. 2 août 2024 à 12:00, chris barcelone ***@***.***> a
écrit :

> Super merci
>

**Comment by tcharp38** [comment]
Il me faut le package de logs en mode DEBUG pour voir de + pres.

**Comment by chrisb13790** [comment]
pourtant suis bien en debug
[image: image.png]

**Comment by chrisb13790** [comment]
test avec le repeteur bureau
[image: image.png]


Le ven. 2 août 2024 à 15:41, chris barcelone ***@***.***> a
écrit :

> pourtant suis bien en debug
> [image: image.png]
>
>

**Comment by tcharp38** [comment]
J'imagine que tu reponds par email.. les images et autres fichiers attachés ne passent pas.
Donc je ne vois rien.
Quoi qu'il en soit le piege est que lorsque tu passes en mode debug tu dois redemarrer Abeille imperativement. Pas trouvé d autre solution jusque la.

et il me faut toujours le package de logs pour analyser la situation

**Comment by chrisb13790** [comment]
ok je redemarre et je passe par git

**Comment by chrisb13790** [comment]
essai avec répéteur bureau
![image](https://github.com/user-attachments/assets/0c9cdb84-a216-4379-8f7a-12c384e4b454)
[AbeilleLogs-240802.tar.gz](https://github.com/user-attachments/files/16471209/AbeilleLogs-240802.tar.gz)

**Comment by tcharp38** [comment]
Ok donc tu es passé en 0004-0323 (donc OPDM).

C'est le fait d'avoir basculé sur la beta qui entraine tous ces  timeout et NOACK ?
Tout etait clean avant ?

Je me rends compte qu'il y a 3 sujets que tu as ouverts, tous quasi sur la meme problematique... TIMEOUT.

Peut on fermer celui la et rester sur le #2609 qui me semble d'actualite ?

**Comment by chrisb13790** [comment]
non c etait deja en vrac avant de faire la maj d abeille beta
ok on passe sur https://github.com/KiwiHC16/Abeille/issues/2609

**Comment by tcharp38** [comment]
Je ferme celui la.
A reouvrir si soucis specifiques ZG-005-RF
