### ISSUE TITLE
Support volet roulant Profalux d'id MOT-C1Z06F

### ISSUE THREAD

**Issue by mossroy** [KiwiHC16/Abeille#2411]
C'est a priori un modèle très proche du MOT-C1Z06C (cf #2091), mais il n'est pas reconnu automatiquement.

J'ai réussi à l'inclure dans la ruche, et à le faire fonctionner en copiant le fichier plugins/Abeille/core/config/devices/MOT-C1Z06C/MOT-C1Z06C.json dans un nouveau répertoire/fichier plugins/Abeille/core/config/devices_local/MOT-C1Z06F/MOT-C1Z06F.json et en y changeant simplement l'id MOT-C1Z06C par MOT-C1Z06F.

Je n'ai pas testé en détail mais tout m'a l'air de bien marcher: montée, descente, arrêt, affichage du level actuel, setLevel

Peut-être faudrait-il simplement le déclarer en alternateId de MOT-C1Z06C?

**Comment by tcharp38** [comment]
Salut @mossroy 

En supposant que l'identifiant MOT-C1Z06F a le meme comportement que MOT-C1Z06C, tu as bien compris.

Du coup voila le modele à tester.
[MOT-C1Z06C.zip](https://github.com/KiwiHC16/Abeille/files/9076307/MOT-C1Z06C.zip)

Redemarrer Abeille avant de refaire l 'inclusion.

**Comment by tcharp38** [comment]
Tout est dans la 220713-BETA-1

**Comment by tcharp38** [comment]
220714-STABLE-1

**Comment by tcharp38** [comment]
@mossroy 
Ca dit quoi sur la stable ?

**Comment by mossroy** [comment]
Désolé, je n'ai pas eu le temps de refaire l'inclusion de mes volets.
Par contre, j'ai pu upgrader à la version 220714-STABLE-1 d'Abeille, et ai supprimé mon répertoire plugins/Abeille/core/config/devices_local/MOT-C1Z06F: même après redémarrage ça fonctionne toujours bien

**Comment by tcharp38** [comment]
Ok, je clos en considerant que c'est bon mais à reouvrir si toujours des soucis.
