### ISSUE TITLE
Install version "2022-06-20 01:00:21" : erreur md5sum: resources/archives/...: No such file or directory

### ISSUE THREAD

**Issue by Bch78** [KiwiHC16/Abeille#2413]
Bonjour,

Lors de l'installation de la version "2022-06-20 01:00:21" présence de nombreux messages d'erreurs dans le fichier AbeilleConfig.log qui sont tous de la forme:
 - md5sum: **resources/archives**/xxxxxxxxxx: **No such file or directory**
 - **resources/archives**/xxxxxxxxxx: **FAILED open or read**

Après vérification via "Réglages -> Système -> Editeur de fichiers" le répertoire resources ne contient en effet pas de sous-répertoire archives.
Le contenu de resources pour mon installation est le suivant:
-rwxrwxr-x  1 www-data www-data 1395 Jul 10 10:40 ca_dns.crt
-rwxrwxr-x  1 www-data www-data   30 Jul 10 10:40 .htaccess
-rwxrwxr-x  1 www-data www-data 8047 Jul 10 10:40 install_nodejs.sh
-rwxrwxr-x  1 www-data www-data 1951 Jul 10 10:40 root_market.crt

Faut-il considérer celà comme une erreur / bug  ? 
ou alors est-ce mineur et lié aux tests de mise au point de la version "2022-06-20 01:00:21"

A priori l'installation jeedom se comporte bien.

Merci

-----------------
Extrait du fichier AbeilleConfig.log
-----------------
1432|[2022-07-04 07:16:51] Vérifications du port '/dev/ttyAMA0'
1433|[2022-07-04 07:16:51] = Ok, le port semble libre.
1434|[2022-07-04 07:16:51] Vérification de l'installation du package 'WiringPi'
1435|= Ok
1436|[2022-07-04 07:16:51] Configuration des GPIOs
1437|[2022-07-04 07:16:51] = Ok
1438|[2022-07-04 07:16:51] Configuration du port série
1439|[2022-07-04 07:16:51] = Ok
1440|[2022-07-04 07:16:51] zgGetVersion()
1441|[2022-07-04 07:16:51] Interrogation de la Zigate sur port /dev/ttyAMA0
1442|[2022-07-04 07:16:51] zgWrite(0010000010)
1443|[2022-07-04 07:16:51] zgRead()
1444|[2022-07-04 07:16:51]   Read=8000000999000000100000000000
1445|[2022-07-04 07:16:51] zgRead()
1446|[2022-07-04 07:16:51]   Read=80100005B40003032100
1447|[2022-07-04 07:16:51] FW version 0003-0321
1448|[2022-07-04 07:16:51] Redémarrage des démons
1449|[2022-07-10 10:40:28] Test d'intégrité d'Abeille
**1450|[2022-07-10 10:40:28] - md5sum: resources/archives/AbeilleInterrogate.php: No such file or directory
1451|[2022-07-10 10:40:28] - resources/archives/AbeilleInterrogate.php: FAILED open or read
1452|[2022-07-10 10:40:28] - md5sum: resources/archives/AbeilleLQI_List.php: No such file or directory
1453|[2022-07-10 10:40:28] - resources/archives/AbeilleLQI_List.php: FAILED open or read
1454|[2022-07-10 10:40:28] - md5sum: resources/archives/LqiStorage.php: No such file or directory
1455|[2022-07-10 10:40:28] - resources/archives/LqiStorage.php: FAILED open or read
1456|[2022-07-10 10:40:28] - md5sum: resources/archives/NetworkDefinition.php: No such file or directory
1457|[2022-07-10 10:40:28] - resources/archives/NetworkDefinition.php: FAILED open or read
1458|[2022-07-10 10:40:28] - md5sum: resources/archives/RadioTraffic.php: No such file or directory
1459|[2022-07-10 10:40:28] - resources/archives/RadioTraffic.php: FAILED open or read
1460|[2022-07-10 10:40:28] - md5sum: resources/archives/RadioTrafficMap.php: No such file or directory
1461|[2022-07-10 10:40:28] - resources/archives/RadioTrafficMap.php: FAILED open or read
1462|[2022-07-10 10:40:28] - md5sum: resources/archives/RadioVoisines.php: No such file or directory
1463|[2022-07-10 10:40:28] - resources/archives/RadioVoisines.php: FAILED open or read
1464|[2022-07-10 10:40:28] - md5sum: resources/archives/RadioVoisinesMap.php: No such file or directory
1465|[2022-07-10 10:40:28] - resources/archives/RadioVoisinesMap.php: FAILED open or read
1466|[2022-07-10 10:40:28] - md5sum: resources/archives/RouteRecord.json: No such file or directory
1467|[2022-07-10 10:40:28] - resources/archives/RouteRecord.json: FAILED open or read
1468|[2022-07-10 10:40:28] - md5sum: resources/archives/RouteRecord.php: No such file or directory
1469|[2022-07-10 10:40:28] - resources/archives/RouteRecord.php: FAILED open or read
1470|[2022-07-10 10:40:28] - md5sum: resources/archives/essai.json: No such file or directory
1471|[2022-07-10 10:40:28] - resources/archives/essai.json: FAILED open or read
1472|[2022-07-10 10:40:28] - md5sum: resources/archives/prog_jennic/JennicModuleProgrammerRPI3: No such file or directory
1473|[2022-07-10 10:40:28] - resources/archives/prog_jennic/JennicModuleProgrammerRPI3: FAILED open or read
1474|[2022-07-10 10:40:28] - md5sum: resources/archives/xmlhttpConfChange.php: No such file or directory
1475|[2022-07-10 10:40:28] - resources/archives/xmlhttpConfChange.php: FAILED open or read
1476|[2022-07-10 10:40:28] = ERREUR: Les fichiers ci-dessus sont corrompus.
1477|[2022-07-10 10:40:28] = L'installation s'est mal déroulée, peut-être par manque de place**.

**Comment by tcharp38** [comment]
Salut @Bch78 
Ha oui le message n'est pas important mais il souligne quand meme un pb... ce répertoire "ARCHIVE" ne devrait pas être soumis à ce test md5sum.
Je vais corriger.
Merci

**Comment by tcharp38** [comment]
Corrigé dans la 220713-BETA-1

**Comment by tcharp38** [comment]
220714-STABLE-1

**Comment by tcharp38** [comment]
Je clos.
Ca doit etre fixé dans la derniere stable mais à reouvrir si besoin.
