### ISSUE TITLE
Legrand bouton dooxie 600699 (id = Remoteswitch, Legrand)

### ISSUE THREAD

**Issue by jmlm74** [KiwiHC16/Abeille#2417]
Bonjour,

Lors de la reconnaisance du bouton en objet, ce bouton est effectivement reconnu comme "legrand remote switch". 
Par contre il ne me remonte rien lorsque j'appuie sur l'un ou l'autre des boutons.
Je vous joins les logs en mode debug ainsi qu'un discovery.json.

Merci d'avance.
Cordialement

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/9176646/Abeille.log)
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/9176647/discovery.json.txt)
.

**Comment by tcharp38** [comment]
Je pense qu'il y a deja un sujet ouvert sur ce meme device et du coup le modele ne doit pas être complet.
On va pouvoir bosser dessus mais plutot a mon retour mi aout.

**Comment by tcharp38** [comment]
Meme identifiant que modele 067723: https://github.com/KiwiHC16/Abeille/issues/2361

**Comment by tcharp38** [comment]
Je ferme ce sujet. Voir #2361
