### ISSUE TITLE
Zlinky and abeille

### ISSUE THREAD

**Issue by Iwhite67** [KiwiHC16/Abeille#2418]
Bonjour, je vient de mettre en route mon installation Zigbee, j'ai bien le linky avec zlinky mais aucune information sauf le tarif est remonté

Jeedom
Zlinky
Zigate avec abeille

**Comment by tcharp38** [comment]
Salut @Iwhite67 
Je n'ai probablement pas complété le modele jusque la.
quelle info cherches tu en particulier ?

Note que je pars en congés jusqu au 10 aout donc ne t attends pas à une reaction rapide.

**Comment by Iwhite67** [comment]
Hello

voici la liste de ce qui m'interesse
<html>
<body>


Commande TIC | CLUSTER | Attribut | Droit | Comment | data type | size max | unit | designation | valeur par defaut
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BASE | 0x0702 | 0x0000 | RP |   | Uint48 | 9 car | Wh | Index Base | 0
IINST | 0x0B04 | 0x0508 | RP |   | Uint16 | 3 car | A | Courant efficace | 0xFFFF
IMAX | 0x0B04 | 0x050A | RO |   | Uint16 | 3 car | A | Intensité maximale | 0xFFFF


</body>
</html>


HCHC HCHP, pas besoin
si besoin plus tard, ceci ce change ou, dans le coeur du plugin ?


![image](https://user-images.githubusercontent.com/9698964/180978979-b4d7d10a-1362-4172-a343-eec7762c7ae4.png)

**Comment by Iwhite67** [comment]
hum, interessant, j'ai trouver ou c'est configuré et c'est déjà configuré

![image](https://user-images.githubusercontent.com/9698964/180996770-d1248dc1-9b11-4e10-b709-f48ad337a069.png)

**Comment by tcharp38** [comment]
Je ne sais pas trop ce qui est reporté "par défaut". Il y a eu des changements de firmware Zlinky depuis mes premiers essais.
D'ailleurs es tu à jour ?

Tiens, un nouveau modele à essayer.

A decompresser dans core/config/devices/ZLinky_TIC_LiXee
[ZLinky_TIC_LiXee.zip](https://github.com/KiwiHC16/Abeille/files/9196224/ZLinky_TIC_LiXee.zip)

puis refaire inclusion
et me filer le package de logs (via page support/telecharger tout).
Attention à bien etre en mode debug/5000 lignes de log: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by Iwhite67** [comment]
s'il faut refaire l'inclusion, j'essaie ce weekend

**Comment by Iwhite67** [comment]
j'ai déjà fait le changement, effectué un redemarrage de jeedom, voici un premier package

en rentrant ce week end, je fait une inclusion du linky
[AbeilleLogs-220727.tar.gz](https://github.com/KiwiHC16/Abeille/files/9196331/AbeilleLogs-220727.tar.gz)

**Comment by tcharp38** [comment]
Tu n'es pas en mode "debug" vu que les logs sont vides.
A modifier via la page config, puis sauvegarder et redemarrer le démon Abeille (et non pas Jeedom).

Si tu fais tout ça à distance, au lieu de refaire une inclusion tu peux tenter de "reinitialiser" via la page equipement/avancé.

**Comment by Iwhite67** [comment]
J'ai activé le débug, Restart Abeille et reinclusion du linky
[AbeilleLogs-220805.tar.gz](https://github.com/KiwiHC16/Abeille/files/9269840/AbeilleLogs-220805.tar.gz)

C'est good, hormis l'intensité instantané

**Comment by Iwhite67** [comment]
Edit :

j'ai rajouter un Get IINST, c'est good
