### ISSUE TITLE
Automatique Adress Update

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#242]
Bonjour

Le titre est en anglais pour être lisible par un plus grand public : l'idée de ma request est : sur chaque abeille (nœud) avoir dans l'onglet Équipement, sur la même ligne que 'Topic Abeille' un bouton 'Remplacement Abeille' qui aurait un algo comme:

1. Activer le mode "Join" de la ruche
2. Détecter le premier appairage se faisant
3. Si c'est le même type de périphérique changer le "Topic Abeille" sinon avoir le comportement normal (ajout d'une Abeille en mode auto par exemple)
4. Désactiver le mode "Join"
5. Afficher un popup de succès ou d'échec

Évidemment, le besoin premier est lié aux pertes d'appairage des devices, le besoin futur sera en cas de remplacement réel d'un équipement.

Note : j'ai bien vu dans la ruche l'option de remplacement avec l'ancien et nouveau ID court, mais quand il y en a une dizaine à faire, et qu'il faut en plus passer par l'interface plugin Abeille pour enlever les anciens, c'est pas top.

**Comment by KiwiHC16** [comment]
C'est probablement faisable mais ca ne résoud pas au soucis initial: la perte d un équipement.

Il n'est pas une operation normale de faire un remplacement. Cela ne devrait se produire que sur remplacement du hardware. Dans ce cas, on a la solution existante avec les commandes dans la ruche.

Il y a deja beaucoup de commande sur les objets et les utilisateurs ont demandés à garder que le strict nécessaire.

Il y a une autre piste qui est d'utiliser la MAC adresse, qui permettrait de detecter les doublons, deux équipements logiques pour un equipement réel ... on dit celui qu'on veut garder (Historique des datas, scenarios,...).

Il faut probablement réfléchir un peu plus avant de faire un truc.

**Comment by handfreezer** [comment]
Tout à fait d'accord : je n'ai pas autant de recul que toi ni de retour utilisateur, j'ai ouvert le ticket car je pense qu'il y a quelque chose à faire.

Note que j'ai aussi laissé une note côté zigate car je ne sais pas si c'est normal qu'une commande leave soit émise quand cela fait longtemps qu'un équipement n'a pas "pointé".

Le coup de la MAC semble sympa, mais je ne comprends pas le principe du choix de l'historique? Le principe serait d'intégrer une sorte de "patch" logiciel qui gère le changement d'ID court automatiquement?

**Comment by KiwiHC16** [comment]
Historique: Jeedom garde un historique des commandes (valeurs comme temperature par exemple). Si tu effaces un objet, alors automatiquement Jeedom efface l'historique associé.

**Comment by KiwiHC16** [comment]
J'ai ajouté deux tests qui vont générer une alerte si les adresses changent. Cela permettra aux utilisateurs d'être informés. Je vais voir si ces messages arrivent souvent et si on veut faire une mise à jour automatique sur changement ou si nous laissons l utilisateur faire la manip à la main.

**Comment by KiwiHC16** [comment]
Inclus dans le master avec le push de ce jour.
Dans la conf, il y un nouveau mode "Mode de gestion des adresses courtes".
En gros dans le mode automatique, si un équipement change d'adresse courte, celle ci sera changée dans l'objet jeedom.
De ce fait, l'objet Jeedom ne change pas (c est transparent pour l utilisateur, y a des messages pour information qui permettent de suivre les changements ). 

Maintenant il faut tester car j'ai beaucoup touché a la fonction centrale.
Il faut aussi mettre à jour les equipments dans Jeedom:
1) supprimer et recréer manuellement si pas top d'équipement 
2) lancer la requete sql suivante:
....

**Comment by handfreezer** [comment]
Excellent, dès que je rentre chez moi, je me mets à jour et je vous dis dés que j'ai une perte (et j'ai déjà un module de perdu....)

**Comment by handfreezer** [comment]
par contre, il y a ... après "la requete sql suivante"?

**Comment by KiwiHC16** [comment]
Oui je travaille sur la requête elle est  plus compliquée que prévue mais elle se prépare.

**Comment by handfreezer** [comment]
je viens de faire l'update, mais maintenant, je ne peux plus "envoyer de commande" à la zigate, je continue de recevoir les update des capteurs, mais je ne peux pas par exemple demander l'état du mode d'inclusion, ni le déclencher. je précise que je n'ai fait aucun update sql à la main. J'ai relancé les démons.

**Comment by edgd1er** [comment]
bjr,

haha, j'ai mis a jour mon jeedom de prod avec la dernière version du master. Quels sont les impacts possibles ou attendus des derniers commits ?
Ps: j'ai du ré-inclure un contacteur de porte (xiaomi door sensor), la détection et la "récuperation" de l'historique ont été automatique. je n'ai pas du faire de renommage. une super fonctionnalité, sachant les pb de xiaomi a rester reconnu... dans le réseau zigbee.

**Comment by handfreezer** [comment]
Bien sûr en bon débutant, je l'ai fait sur la "prod"... (mais comme c'est pas fiable, je ne dépends pas de la stabilité du système :-) )
Par contre, depuis l'update, j'ai perdu 3 device, alors que je n'en ai pas perdu en 4semaines, une idée?

**Comment by handfreezer** [comment]
bon, épatant (j'avais une sauvegarde tout de même :-) ) alors j'ai tenté le coup de la suppression de la ruche et relance du démon : nickel : reconstruction de la ruche illico, et je peux activer le mode inclusion.
De là, j'ai pu forcer l'update du capteur de température, et synchronisation des adresses courtes automatiques... (un clignotement bleu long puis trois courts sur le capteur)
Ça veut tout de même dire que le capteur à tenter un rejoin et que la zigate l'a accepté mais avait bien viré son adresse courte de sa table?

**Comment by KiwiHC16** [comment]
Le code sur la master contine tles modif pour garder un equipement sur changement d adresse.
Mais pour faire ce code j'ai simplifier les definitions des commandes dans les objets. De ce fait il faut mettre a jour la definition des objets dans la base sql de Jeedom. Je n'ai pas encore fini le script pour faire cela. Soit vous supprimez les objets dans jeedom et vous les recréés (en demandant le nom a l equipement, soit en faisant une nouvelle inclusion).
Le plug in Abeille n'impacte pas la perte des équipements. Perso, je n'en perds pas depuis des semaines... bizarre...
Je bosse sur le script....

**Comment by KiwiHC16** [comment]
Salut handfreezer,
Je viens de mettre le script dans le master. Le script s'execute lors du lancement du plugin. Peux tu faire une mise à jour master, supprimer la ruche et relancer le plugin. Ensuite tester pour voir si tout est Ok. A faire sur un systeme de test si possible en premier. Il est possible de devoir relancer Jeedom car je fais les changement dans la base directement (Ce n'est pas clair ce point la pour moi).
Par la suite si des équipements changent d'adresse tu dois recevoir un message et l objet dans jeedom est mis à jour. Rien à faire pour l utilisateur.
Il faut aussi que les adresses IEEE soient collectées soit par un Liste Equipement (si tous les équipement sont en direct sur la zigate ou par un "recalcul du cache" dans "Network List->Table des noeuds"

**Comment by handfreezer** [comment]
Je vais faire l'update, mais sur le système que j'ai en cours d'usage (la procédure de restauration marche bien, ...)Juste deux questions:

- quelle forme prend le message que l'on doit recevoir? (une popup, un mail à configurer, ...?)

- je ne comprends pas la subtilité de la dernière phrase sur les adresses IEEE: est-ce que le simple enregistrement en noeud dans jeedom ne suffit pas?

Note : je n'ai pas de noeud routeur dans mon installation.

**Comment by handfreezer** [comment]
Pdt l'update j'ai eu deux warnings:

***************Update plugins***************
[2018-08-26 13:52:15][ALERT] : Début de la mise à jour de : Abeille
[2018-08-26 13:52:15][ALERT] : Action de pré-update...
[2018-08-26 13:52:15][ALERT] : OK
[2018-08-26 13:52:15][ALERT] : Téléchargement du plugin...
[2018-08-26 13:52:16][ALERT] : Téléchargement de Abeille...
[2018-08-26 13:52:18][ALERT] : OK
[2018-08-26 13:52:18][ALERT] : Décompression du zip...
[2018-08-26 13:52:19][ALERT] : OK
[2018-08-26 13:52:19][ALERT] : Post-installation de Abeille...
PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/html/core/class/system.class.php on line 128
PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/html/core/class/system.class.php on line 128
[2018-08-26 13:52:22][ALERT] : OK
***************Update plugin successfully***************


Je continue le process

**Comment by handfreezer** [comment]
Le principe marche bien avec popup qui previent du changement d'adresse courte, MAIS j'ai dû passer la passerelle zigate en mode "inclusion".

je continue de surveiller.

**Comment by KiwiHC16** [comment]
Je clos le sujet. Si il y a des soucis on ouvrira des issues spécifiques.
