### ISSUE TITLE
Ajout support Innr RC 250 (id = RC250, innr)

### ISSUE THREAD

**Issue by Alcolo47** [KiwiHC16/Abeille#2420]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/9208923/discovery.zip)

Lien constructeur: https://www.innr.com/fr/produit/remote-control/ 

Lien commerce: https://www.amazon.fr/gp/product/B098B6Y18L/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

Merci.

**Comment by tcharp38** [comment]
Salut @Alcolo47 
Un modele rapide mais incomplet. Il va falloir creuser.

[RC250_innr.zip](https://github.com/KiwiHC16/Abeille/files/9299752/RC250_innr.zip)

- A decompresser dans core/config/devices
- puis redemarrer Abeille
- refaire inclusion

Il me faudra une image PNG sans arriere plan pour mettre en icone.

Ensuite il faudra trouver ce qui est envoyé en pressant chaque bouton et en capturant les logs (mode debug).

**Comment by tcharp38** [comment]
Salut @Alcolo47 
Toujours interessé par ce sujet ?

**Comment by tcharp38** [comment]
Plus de vie.
Je ferme le sujet.
A reouvrir si ca interesse qqn
