### ISSUE TITLE
Philips Hue white 806 model 9290018216 (id = LWA011) 

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2421]
Bonjour,

J'ai une Philips hue white 806 que je n'arrive pas à intégrer dans jeedom avec zigate et abeille.

Voici quelques infos :
![image](https://user-images.githubusercontent.com/26632961/183088086-c9dd5b88-47bf-4b71-8072-e7d5c7858095.png)
Hue white A60 9W 49mA 2700K
Model : 9290018216
Serial : D0CF7A

L'inclusion fonctionne mais aucune commande.

Pouvez-vous m'aider à faire fonctionner cette ampoule ?

Merci par avance.

**Comment by tcharp38** [comment]
Salut @toat
Ce modele ne semble pas connu d'Abeille.
Peux tu generer un discovery via l'assistant et me le filer ici ?
Voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

**Comment by toat** [comment]
salut,

Voici.
[LWA011.txt](https://github.com/KiwiHC16/Abeille/files/9843790/LWA011.txt)

Merci.

**Comment by tcharp38** [comment]
[LWA011.zip](https://github.com/KiwiHC16/Abeille/files/9844824/LWA011.zip)
Manip idem LWU001

**Comment by toat** [comment]
Pour celle-ci ca semble pas bon.

![image](https://user-images.githubusercontent.com/26632961/197379633-6e00c5b3-588b-46fb-b6ce-978a3c16ade8.png)

J'ai fait l'inclusion plusieurs fois.

**Comment by tcharp38** [comment]
J'ai besoin du package de logs apres l inclusion. Sinon je suis aveugle

**Comment by toat** [comment]
Voila 
[AbeilleLogs-221023.tar.gz](https://github.com/KiwiHC16/Abeille/files/9846235/AbeilleLogs-221023.tar.gz)

**Comment by tcharp38** [comment]
Pourrais tu basculer sur la beta ?
Tu ne sembles pas en mode debug et tu aurais du avoir un message te disant ca.
Si tu regardes le log AbeilleParser par ex, tu vois que la trace date de 2021-12-28
Bref inutilisable.

Il faut que je blinde ca pour qu'il soit evident que pour toute demande de support, le mode debug + log 5000 lignes + beta soit un minimum.

**Comment by toat** [comment]
J'ai mis la beta. 

J'ai CMD et PARSER qui ne tournent pas.

==> AbeilleParser.log <==

PHP Parse error:  syntax error, unexpected '}', expecting ')' in /var/www/html/plugins/Abeille/core/php/AbeilleZigbeeConst.php on line 68

==> AbeilleCmd.log <==
[2022-10-23 14:02:02] >>> Démarrage d'AbeilleCmd
PHP Parse error:  syntax error, unexpected '}', expecting ')' in /var/www/html/plugins/Abeille/core/php/AbeilleZigbeeConst.php on line 68

**Comment by toat** [comment]
![image](https://user-images.githubusercontent.com/26632961/197391027-3d820684-98d4-47dc-b56b-5c30ef9c624b.png)

**Comment by tcharp38** [comment]
Ha m.. je l'ai corrigé ca mais à priori ca n'a pas ete pris en compte sur cette beta.
Voila le fichier

[AbeilleZigbeeConst.zip](https://github.com/KiwiHC16/Abeille/files/9846541/AbeilleZigbeeConst.zip)

A decompresser dans core/config/php

Et bien sur redemarrer Abeille

**Comment by tcharp38** [comment]
Et voila une mise à jour du modele. j'y ai trouvé une boulette.
Inclusion à refaire donc
[LWA011.zip](https://github.com/KiwiHC16/Abeille/files/9846578/LWA011.zip)

**Comment by toat** [comment]
Il ne veut plus me télécharger le package de logs dans "Maintenance". J'ai fait un tar à la main.

[AbeilleLogs.tar.gz](https://github.com/KiwiHC16/Abeille/files/9846579/AbeilleLogs.tar.gz)

j'ai refait un inclusion de l'ampoule.

**Comment by toat** [comment]
Ok je vais tester cela.

**Comment by toat** [comment]
Ca fonctionne. Merci beaucoup.
