### ISSUE TITLE
Philips Hue white 407 model : 9290024406 (id = LWU001, SignifyNetherlandsB.V.)

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2422]
Bonjour,

J'ai une philips hue white E14 que je n'arrive pas a intégrer à jeedom.

![image](https://user-images.githubusercontent.com/26632961/183093808-5759a3b0-e9ec-4075-97ba-f385920b5490.png)

Hue white E14 5.7W 34mA 2700K
Model 9290024406 

L'inclusion fonctionne mais aucune commande.

Pouvez-vous m'aider à faire fonctionner cette ampoule ?

Merci par avance.

**Comment by tcharp38** [comment]
Salut @toat 
Ce modele ne semble pas connu d'Abeille.
Peux tu generer un discovery via l'assistant et me le filer ici ?
Voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

**Comment by toat** [comment]
Salut,

Voici
[LWU001.txt](https://github.com/KiwiHC16/Abeille/files/9843791/LWU001.txt)

Merci.

**Comment by tcharp38** [comment]
Pour test:

A decompresser dans core/config/devices
[LWU001.zip](https://github.com/KiwiHC16/Abeille/files/9844814/LWU001.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by toat** [comment]
ca fonctionne merci.
