### ISSUE TITLE
Aubess smoke sensor (id = TS0601, _TZE200_uebojraa)

### ISSUE THREAD

**Issue by trynifred** [KiwiHC16/Abeille#2426]
Bonjour, le détecteur de fumé indiqué ici n'est pas détecté.
https://fr.aliexpress.com/item/1005004416503008.html?spm=a2g0o.order_list.0.0.614b5e5bDXYxYJ&gatewayAdapt=glo2fra
Je' suis en version béta
Merci de votre aide
[discovery (2).zip](https://github.com/KiwiHC16/Abeille/files/9338078/discovery.2.zip)

**Comment by tcharp38** [comment]
Salut @trynifred 

- Quelle est la ref ou modele ?
- Quel est le type de batterie ?
- J'aurai aussi besoin d'une image PNG sans arriere plan à mettre en icone.

Voila déja un premier jet mais a completer.
Comme tous les modeles d'origine Tuya, ca demande de creuser ce qu'il sait faire car rien n'est standard.

A decompresser dans core/config/devices
[TS0601__TZE200_uebojraa.zip](https://github.com/KiwiHC16/Abeille/files/9349588/TS0601__TZE200_uebojraa.zip)

puis s'assurer d etre en mode debug + sauvegarder
redemarrer Abeille
refaire inclusion
et me filer le package de logs (page support/telecharger tout)

**Comment by trynifred** [comment]
Voici l’image



 

Lien vers le modèle : https://fr.aliexpress.com/item/1005004416503008.html?spm=a2g0o.order_list.0.0.22db5e5bOqwtZ5 <https://fr.aliexpress.com/item/1005004416503008.html?spm=a2g0o.order_list.0.0.22db5e5bOqwtZ5&gatewayAdapt=glo2fra> &gatewayAdapt=glo2fra

 

Et les logs en pièce joint.

Merci +++

 

 

De : Tcharp38 ***@***.***> 
Envoyé : mardi 16 août 2022 11:48
À : KiwiHC16/Abeille ***@***.***>
Cc : trynifred ***@***.***>; Mention ***@***.***>
Objet : Re: [KiwiHC16/Abeille] Aubess smoke sensor (id = TS0601, _TZE200_uebojraa) (Issue #2426)

 

Salut @trynifred <https://github.com/trynifred> 

*	Quelle est la ref ou modele ?
*	Quel est le type de batterie ?
*	J'aurai aussi besoin d'une image PNG sans arriere plan à mettre en icone.

Voila déja un premier jet mais a completer.
Comme tous les modeles d'origine Tuya, ca demande de creuser ce qu'il sait faire car rien n'est standard.

A decompresser dans core/config/devices
TS0601__TZE200_uebojraa.zip <https://github.com/KiwiHC16/Abeille/files/9349588/TS0601__TZE200_uebojraa.zip> 

puis s'assurer d etre en mode debug + sauvegarder
redemarrer Abeille
refaire inclusion
et me filer le package de logs (page support/telecharger tout)

**Comment by tcharp38** [comment]
Ni image ni logs attachés :(
Tu n'as probablement pas utilisé l interface WEB de github. J'ai déja vu ce souci.

**Comment by trynifred** [comment]
[AbeilleLogs-220816.tar.gz](https://github.com/KiwiHC16/Abeille/files/9352383/AbeilleLogs-220816.tar.gz)
![image](https://user-images.githubusercontent.com/42860902/184919605-63652077-cd73-4617-a84f-b77ec2412f68.png)

**Comment by tcharp38** [comment]
Ton log est trop court (seulement 500 lignes)

> [2022-08-15 16:52:53] Max reached (490 lignes) Previous log saved as '/tmp/jeedom/Abeille/AbeilleParser-prev.log'

Le modele n'est toujours pas reconnu.
As tu bien redemarré Abeille ?

Merci pour l'image.

**Comment by trynifred** [comment]
oui je l'ai fait avant de le réintégrer
et j'a bien mis 5000 lignes dans les logs, en tout cas je pense

**Comment by trynifred** [comment]
[AbeilleLogs-220817.tar.gz](https://github.com/KiwiHC16/Abeille/files/9357869/AbeilleLogs-220817.tar.gz)
nouvelle tentative

**Comment by trynifred** [comment]
il le reconnait en aubess smoke sensor, c'est bien ce qui est dans le json que tu m'as envoyé

**Comment by tcharp38** [comment]
Donc il y a du mieux.
Mais les logs sont dans un etat que j'ai déja vu mais jamais compris comment on en arrivait la.

Quoi qu'il en soit il doit au moins y avoir un crash chez toi.

Peux tu decompresser ce fichier dans core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/9358634/AbeilleParser.class.php.zip)

et redemarrer Abeille
il sera dans la beta de demain

**Comment by tcharp38** [comment]
Salut @trynifred 
Des news ?

**Comment by tcharp38** [comment]
Plus de news depuis un moment.
Je clos mais à réouvrir si qqn veut bosser dessus.
