### ISSUE TITLE
Micromodule ZigBee pour volet roulant

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2427]
Salut @tcharp38
Il ne me semble pas avoir vu ce micromodule VR dans les équipements compatibles 
https://www.domotique-store.fr/domotique/modules-domotiques/modules-encastrables/micromodules-domotiques-sans-fil-volets-roulants/1470-micromodule-zigbee-pour-volet-roulant-compatible-jeedom-eedomus.html?search_query=micromodule+zigbee+volet+roulant&results=188 
Il est compatible Tuya Smart Life et compatible Jeedom avec un dongle Zigbee. 
Penses-tu pouvoir l'intégrer dans Abeille ?
J'espère que tu as passé de bonnes vacances rt que tu es près à mettre la tête dans le guidon.
Merci de ton aide

**Comment by tcharp38** [comment]
Salut @Kenderv 
Encore un module d origine Tuya.
Comme il y en a eu plusieurs, j 'imagine que c'est jouable pour Abeille.

Les vacances etaient tres bien. J'ai pu deconnecter 10 jours :)

**Comment by Kenderv** [comment]
J'en attends 1, je reprends contact avec toi dès réception.
Merci

**Comment by tcharp38** [comment]
@Kenderv 
On fait quoi de ce sujet ?

**Comment by Kenderv** [comment]
Bonjour @tcharp38 
Tu peux fermer, je n'ai en ce moment pas le temps de m'occuper de cela. Si besoin on le rouvrira plus tard.
Merci et bonne semaine

**Comment by tcharp38** [comment]
Ok.
A réouvrir dès que ca interesse qqn.
Bonne semaine
