### ISSUE TITLE
Philips Hue Smart Plug LOM008

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2431]
Hello,

Après LOM007, voici LOM008...  Encore une nouvelle version de la prise Philips Hue Smart Plug.

Voici le fichier discovery : 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/9435220/discovery.zip)

Tu peux ajouter un modèle pour celle-ci aussi ?

Merci

**Comment by tcharp38** [comment]
Salut @eoeir 

Tiens à tester. 
A decompresser dans core/config/devices puis redemarrer Abeille et refaire inclusion

[LOM008.zip](https://github.com/KiwiHC16/Abeille/files/9443050/LOM008.zip)

Je le pousse dans la beta.

**Comment by eoeir** [comment]
J'ai fait le test.

La prise est bien détectée comme une Philips Hue Smart Plug maintenan mais les commandes ressemblent plus à celle d'une ampoule avec les commandes "Set Level", "Current Level" et "Get Current Level. Voici le widget affiché : 
![image](https://user-images.githubusercontent.com/71673288/187286842-4fa1c026-f697-4ed6-ad94-16a6d1c5997b.png)

Les commandes "On" et "Off" ne fonctionnent pas et le retour d'état non plus quand l'interrupteur sur la prise est utilisé.

Voici le package de logs :
[AbeilleLogs-220829.tar.gz](https://github.com/KiwiHC16/Abeille/files/9447616/AbeilleLogs-220829.tar.gz)

**Comment by tcharp38** [comment]
Je vois bien une annonce du device mais l'inclusion se passe mal donc normal qu'il n'y ai pas de retour. 
Aucune commande n'arrive jusqu'au device.

Un lien avec tes soucis de time out general ?

Concernant les cmds "Level", elles n'ont de sens que si le plug supporte un mode "dimmer". C'est le cas ?

**Comment by eoeir** [comment]
Pour l'instant RAS sur mon soucis précédent de time out général, le réseau semble stable depuis que je suis repassé en USB 2. 
Je suis en train de progressivement réinclure l'ensemble des devices et j'ajoute celui-ci pour aussi mieux mailler mon réseau.

Il s'agit de la version FR (avec fiche de terre mâle) de la Philips Hue Smart Plug (type https://www.lesnumeriques.com/prise-connectee/philips-hue-smart-plug-p53919/test.html). La précédente qui s'identifiait comme LOM007 était la version UE (sans fiche male). Pas de fonction dimmer sur ce device.

Que puis-je faire / tester ?

**Comment by eoeir** [comment]
Aujourd'hui "On", "Off" et le retour d'état fonctionnent.
"Set Level" allume à 1% et 0% éteint. Pas de changement à plus de 1%.

**Comment by tcharp38** [comment]
Le retour d'etat est ok ?
Alors il a du se reannoncer. Etrange mais tant mieux.

Comme je disais, le "set level" fait du sens ou pas ? Cette prise supporte un mode "dimmer" ?
Je ne trouve pas la spec de ce produit.

**Comment by eoeir** [comment]
Je ne trouve rien d'officiel non plus. 

Quelques mentions sur internet que cette prise n'a pas de fonction dimmer (ex : https://www.smarthomepoint.com/philips-hue-smart-plug/#can-you-dim-lights-with-philips-hues-smart-plug)

Aucune info dans la doc fournie avec la prise, pas de mention de dimmer sur l'emballage.

**Comment by tcharp38** [comment]
C'est ce que je soupconne. 
Du coup je suis d'avis de simplement virer cette commande + Current Level.
Qu'en penses tu ?

**Comment by eoeir** [comment]
Je pense aussi que c'est le mieux à faire.

**Comment by tcharp38** [comment]
Voila le modele que je vais pousser
Ecraser l'autre et refaire "reinitialisation" via page EQ/avancé
[LOM008.zip](https://github.com/KiwiHC16/Abeille/files/9482319/LOM008.zip)

Je te laisse clore le sujet quand c'est bon.

**Comment by eoeir** [comment]
C'est bon pour moi.

Merci.
