### ISSUE TITLE
Impossible d'ajouter une 2eme zigate

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2432]
Bonjour,
J'essaie désespérément d'ajouter ma zigate V1 sur jeedom mais pas moyen :/
J'ai ce message : 
`[2022-08-29 08:33:22] ERROR: zgGetVersion(): ERREUR d'accès à la Zigate sur port /dev/ttyUSB1
`
J'ai testé tout les ttyUSB1 et pareil avec mon alias que j'utilise pour ma V2, j'ai toujours ce message.

Pour info:
`root@Jeedom:~# ls -l /dev/ttyUSB*`
`crw-rw-rw- 1 root dialout 188, 0 août  29 08:32 /dev/ttyUSB0`
`crw-rw---- 1 root dialout 188, 1 août  29 08:29 /dev/ttyUSB1`
`lrwxrwxrwx 1 root root         7 août  29 08:29 /dev/ttyUSBZigateV1 -> ttyUSB1`
`lrwxrwxrwx 1 root root         7 août  29 08:29 /dev/ttyUSBZigateV2 -> ttyUSB0`

![image](https://user-images.githubusercontent.com/49479084/187138253-eb4e6bed-0af2-47ec-a2fc-f1abd5798c27.png)

[AbeilleLogs-220828.tar.gz](https://github.com/KiwiHC16/Abeille/files/9442078/AbeilleLogs-220828.tar.gz)

Une idée ?
Merci

**Comment by tcharp38** [comment]
Salut @Jake309 
Comme ca je seche.
Peux tu 
- desactiver la gestion automatique du démon
- arreter Abeille
- et tester le port ttyUSB1 ?

et au moins me filer le log AbeilleConfig.

**Comment by Jake309** [comment]
Salut @tcharp38 

Toujours le même souci.
Je vais commenter le lien symbolique de la V1 pour faire le test, des fois que ce soit ca.

[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/9443535/AbeilleConfig.log)

**Comment by Jake309** [comment]
Salut @tcharp38 

Chose faite, pas de changement.
Je viens de tester en supprimant mon lien symbolique pour la V1. Pas de mieux :/

On dirait un problème de droit, le message est bien parlant, mais je sais pas à quel endroit.

[AbeilleConfig (1).log](https://github.com/KiwiHC16/Abeille/files/9443597/AbeilleConfig.1.log)

**Comment by Jake309** [comment]
Je pense que le PB vient de la zigate, car quand je selectionne la ligne ou il y a que ttyUSB1 sans rien d'autre, ca mouline mais ca ne s'arrête jamais, et quand je fais voir la config, j'ai ca :  

[2022-08-30 11:24:33] Test de communication avec la Zigate; type=USB, port=/dev/ttyUSB0
[2022-08-30 11:24:33] Arret des démons
[2022-08-30 11:24:33] Démarrage de 'checkTTY.sh'
[2022-08-30 11:24:33] Vérifications du port '/dev/ttyUSB0'
[2022-08-30 11:24:33] = Ok, le port semble libre.
[2022-08-30 11:24:33] zgGetVersion()
[2022-08-30 11:24:33] Interrogation de la Zigate sur port /dev/ttyUSB0
[2022-08-30 11:24:33] zgWrite(0010000010)
[2022-08-30 11:24:33] zgRead()

il y a un pb sur le read. C'est la zigate qui doit répondre ?
je t'ai mis le package de log, j'ai pas réglé à 5000 la limite, mais comme il y a rien, je pense que ca va pas poser de souci.

PS: fait pas gaffe au ttyUSB0, j'ai refait une install sur un autre pc pour teste pour dédouaner tout souci de droit, modif ou autre.

[AbeilleLogs-220830.tar.gz](https://github.com/KiwiHC16/Abeille/files/9451650/AbeilleLogs-220830.tar.gz)

**Comment by tcharp38** [comment]
Oui c'est ca.
[2022-08-30 11:24:33] zgWrite(0010000010) => envoie de la cmde "get version"
[2022-08-30 11:24:33] zgRead() => Attente du retour de la zigate

Donc elle ne repond pas du tout.
Tu as des erreurs sur "dmesg" liées à ce port USB ?
Tu peux la tester avec l'outil officiel du site Zigate ?

**Comment by tcharp38** [comment]
Oui c'est ca.
[2022-08-30 11:24:33] zgWrite(0010000010) => envoie de la cmde "get version"
[2022-08-30 11:24:33] zgRead() => Attente du retour de la zigate

**Comment by Jake309** [comment]
Non j'ai rien dans dmesg.
L'outil officiel j'ai jamais réussi à voir les discussions avec les équipements (même quand je l'utilisais sur mon précédent jeedom), mais jusqu'à faire clignoter la led pas de souci, encore maintenant.
j'avais des doutes sur ma clé, donc j'avais demandé qu'il me la teste en envoyant mon orvibo pour debug, il m'a dit qu'elle fonctionnait.
Ce week end j'ai un ami qui vient avec sa zigate V1 pour que je puisse faire les test et voir si c'est le mienne qui merde ou autre chose. on pourra aussi croiser les USB TTL. 

J'aimerai qu'elle fonctionne pour avoir une solution de repli avant de faire un RAZ de ma V2.
J'ai acheté la V2 pour ce probleme, donc j'ai pas trop envie de me retrouver sans rien...

**Comment by tcharp38** [comment]
Je continue de reflechir à ce qui pourrait etre en cause coté Abeille mais en dehors d'un conflit, je ne vois pas.
Tu as bien désactivé la gestion auto du démon avant de faire ton dernier test ?

**Comment by Jake309** [comment]
J'ai la même chose que sur mon jeedom de test quand je choisis un des ports correspondant à la zigate. 
Pour moi le pb vient de la zigate. 
J'attends ce week end den avoir une 2eme pour tester et te faire un retour. 
Sinon oui, la gestion auto du démon est bien désactivé :)

**Comment by tcharp38** [comment]
Ok, j'attends ton retour alors.

**Comment by Jake309** [comment]
Salut @tcharp38 
Alors tout est bon pour moi et mon ancienne zigate (v1) fonctionne actuellement sur mon jeedom de maison. 
Je clos :)
