### ISSUE TITLE
OSRAM Lightify Classic E60 TW E27 (id = ClassicA60TW, OSRAM)

### ISSUE THREAD

**Issue by rsuard** [KiwiHC16/Abeille#2435]
Hello, 

je suis désolé si je relance un sujet déjà évoqué mais je ne trouve pas de solution. J'ai vu dans la doc qu'il pouvait y avoir des problèmes avec ce matériel, y a t'il un moyen de tout de même les faire fonctionner ?

Pour info, je suis sur un jeedom à jour sur PI avec une PiZigate.
J'ai plusieurs Smart plug OSRAM qui marchent sans souci.
J'ai aussi un cube et un detecteur Aqara qui marchent parfaitement aussi (meme pour controler les prises OSRAM)

mon souci est sur les ampoules : 
- la B20 apparait en ClassicB40TW-LIGHTIFY - 26 de type ClassicB40TW-LIGHTIFY mais ne répond pas aux controles dans Jeedom
- les 2 E27 apparaissent en defaultUnknown - 27 et defaultUnknown - 28 avec pourtant en avancé pour les 2 : ClassicA60TW du manufId OSRAM

Est ce possible de les faire fonctionner ? Comment ? 

merci beaucoup pour votre aide.

**Comment by tcharp38** [comment]
Salut @rsuard 
On va séparer les sujets.

Les E27 restent ici mais il me faut le discovery.json (page EQ/assistant): https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

Les B20 ont déja un identifiant commun avec le sujet suivant: https://github.com/KiwiHC16/Abeille/issues/2023#top
On s'y retrouve  mais la aussi j'ai besoin du discovery.

**Comment by rsuard** [comment]
Hello @tcharp38,

voici mes JSON discovery pour les 2 E27
[discovery(1).json.zip](https://github.com/KiwiHC16/Abeille/files/9478949/discovery.1.json.zip)
[discovery(2).json.zip](https://github.com/KiwiHC16/Abeille/files/9478950/discovery.2.json.zip)

Merci beaucoup pour ton aide

**Comment by tcharp38** [comment]
Manque de pot ces discovery sont vides.
Tu dois obtenir tous les boutons au vert.
C etait le cas ?

**Comment by rsuard** [comment]
Merci pour ton retour. Non ils ne sont pas tous verts. J’ai ça pour une des E27 
![FBF769ED-46DF-4337-85B2-A88BC063EED7](https://user-images.githubusercontent.com/32543811/188217354-49917446-a3bd-47ad-8140-8326ec9630e8.jpeg)

**Comment by rsuard** [comment]
@tcharp38 je viens d’ajouter une nouvelle light et j’ai ca (les autres sont toujours vides…)
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/9481955/discovery.json.zip)

Merci à toi

**Comment by rsuard** [comment]
Hello,

alors, j’ai tout recommencé, je les ai exclu et enlevée de jeedom, puis remise (et j’ai ajouté 2 autres ampoules E27 soit 4 au total)

j’obtiens 3 réponses pour les e27, et une qui reste vide, malgré mes tentatives sur le bouton, et la réinitialisation. (Une différence de version et/ou de firmware peut être ?)

voici les 3 JSON reçus :
[E27-3.zip](https://github.com/KiwiHC16/Abeille/files/9482549/E27-3.zip)
[E27-1.zip](https://github.com/KiwiHC16/Abeille/files/9482550/E27-1.zip)
[E27-2.zip](https://github.com/KiwiHC16/Abeille/files/9482551/E27-2.zip)

encore merci pour ton aide !
Je mets le json de la b40 sur l’autre thread.

merci

**Comment by tcharp38** [comment]
Enfin des infos utiles dans ces discovery.
Ce sujet est figé "Classic A60 TW" ce qui semble etre le modele.

A decompresser dans core/config/devices
[ClassicA60TW_OSRAM.zip](https://github.com/KiwiHC16/Abeille/files/9482647/ClassicA60TW_OSRAM.zip)

puis
- redemarrer Abeille
- refaire inclusion
- tester

Je te laisse me trouver une belle image PNG sans arriere plan pour mettre en icone.

**Comment by rsuard** [comment]
Un grand merci @tcharp38, dès que j’allume un ordi je test

**Comment by rsuard** [comment]
@tcharp38 merci pour tout, les lampes fonctionnent parfaitement ! (je me suis log à mon pi, j'en ai profité pour faire la MAJ d'abeille, je pense que tu as du pousser les JSON dedans non ? Car j'ai pas eu besoin de pousser les ZIP dedans)
Question, core/config/devices c'est ou ? Je suis connecté en SSH et en netatalk à mon pi, mais je ne sais pas ou est le dossier de ton plugin Jeedom. Merci encore !
