### ISSUE TITLE
Thermostat Schneider WISER (id = Thermostat, SchneiderElectric)

### ISSUE THREAD

**Issue by heyo069** [KiwiHC16/Abeille#2436]
[Wiser Schneider Thermostat.zip](https://github.com/KiwiHC16/Abeille/files/9478311/Wiser.Schneider.Thermostat.zip)

**Comment by tcharp38** [comment]
Bonjour

Voila un modele preliminaire.
[Thermostat_SchneiderElectric.zip](https://github.com/KiwiHC16/Abeille/files/9478560/Thermostat_SchneiderElectric.zip)

A decompresser dans core/config/devices
puis redemarrer Abeille
et refaire inclusion

De quel model s'agit il ?
J'ai besoin d'une image PNG sans arriere plan a mettre en icone.
Quel type de batterie ?

**Comment by tcharp38** [comment]
Salut @heyo069 
Des news ?

**Comment by tcharp38** [comment]
Je clos ce vieux sujet sans infos.
Il manque toujours l'image correspondante et un status.
