### ISSUE TITLE
TuYa Wall switch module WHD02 / iHSW02 (id = TS0001, _TZ3000_rmjr4ufz)

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2438]
Hello,

Je continue avec mes nouveaux devices.
Je viens d'intégrer un micromodule TuYa On/Off 16A à mettre dans les boites d'encastrement électriques. 
https://fr.aliexpress.com/item/1005003195003664.html

![photo_2022-09-04_10-43-57](https://user-images.githubusercontent.com/71673288/188305696-348b7db8-fbe2-4ef9-ab8a-82ca5906c030.jpg)

Il est identifié comme iHSW02 sur le module et semblerait être aussi connu sous le nom WHD02 :
https://www.zigbee2mqtt.io/devices/WHD02.html
https://z2m.dev/devices/tuya/whd02.html

Il est identifié par Abeille comme un "Zemismart 1 boutons". Je suppose que le module s'identifie de la même manière que cet interrupteur...

Les commandes ON/OFF fonctionnent et le retour d'état aussi (à noter que la commande s'appelle "etat charge 0").
Le module est sensé faire mesure de consommation mais je n'ai rien de ce côté là.

Voici le fichier de discovery : 
[discovery iHSW02.zip](https://github.com/KiwiHC16/Abeille/files/9484331/discovery.iHSW02.zip)

**Comment by tcharp38** [comment]
Je ne vois aucune piste pour le retour de conso.
Le WHD02 semble ne pas le faire non plus.
Tu vois ca ecrit sur son manuel ?

**Comment by eoeir** [comment]
J'ai vérifié, ce n'est qu'un module on/off. Je me suis trompé pour la mesure d'énergie.

Est-ce que l'on peut faire quelque chose pour le fait qu'il soit détecté correctement et pas comme un interrupteur Zemismart ?

**Comment by tcharp38** [comment]
On peut faire un modele dedié qui ne soit rien d'autre qu'une copie du zemismart si meme comportement.

**Comment by tcharp38** [comment]
Essaie avec ce modele
a decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion
[TS0001__TZ3000_rmjr4ufz.zip](https://github.com/KiwiHC16/Abeille/files/9542137/TS0001__TZ3000_rmjr4ufz.zip)

J'ai besoin d'une image PNG sans arriere plan a mettre en icone.

**Comment by eoeir** [comment]
OK pour la réinclusion. Il est bien identifié par Abeille comme "Tuya mini smart switch".

Voici l'image pour l'ajouter au modèle.

![TuYa iHSW02](https://user-images.githubusercontent.com/71673288/189534165-5da18903-f118-43ab-999d-5660e19dbc60.png)

**Comment by tcharp38** [comment]
Heu... j'ai pris cette image mais c'est un modele WIFI ca.
Donc pas la bonne

**Comment by eoeir** [comment]
J'avais pas fait gaffe mais le visuel de la version wifi est utilisé dans les annonces de la version zigbee...

**Comment by tcharp38** [comment]
J'te laisse en trouver un autre alors :)
Il me semblait d'ailleurs que la ref apparaissait sur la verison Zigbee.

**Comment by tcharp38** [comment]
@eoeir 
On en est ou sur ce sujet ?

**Comment by eoeir** [comment]
Voici une nouvelle image du bon modèle :

![ceb74ef6148e313292dca929e47c6b6167838fa6_original](https://user-images.githubusercontent.com/71673288/206924595-ebcc9441-9f6f-4480-ba6c-d1ef88247f71.png)

**Comment by tcharp38** [comment]
Merci. C'est intégré.
Il y a des soucis restants sur ce sujet ?

**Comment by eoeir** [comment]
Non. 
Tout est OK avec celui-là.
