### ISSUE TITLE
Philips Hue Motion Sensor (id = SML003, SignifyNetherlandsB.V.)

### ISSUE THREAD

**Issue by scotchbitman** [KiwiHC16/Abeille#2440]
Bonjour,

Je suis en train d'essayer d'intégrer un détecteur de mouvement Philips Hue (SML003) (https://www.amazon.fr/Philips-D%C3%A9tecteur-Mouvement-Motion-Sensor/dp/B09CV78GV1/ref=sr_1_5?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=J0H8RGO808CD&keywords=d%C3%A9tecteur%2Bde%2Bmouvement%2Bphilips&qid=1662472078&sprefix=d%C3%A9tecteur%2Bde%2Bmouvement%2Bphilips%2Caps%2C88&sr=8-5&th=1) sous Jeedom via le plugin Abeille mais il ne semble pas reconnu. 

Pouvez-vous me fournir un modèle s'il vous plaît ?
Quelle est la marche à suivre pour générer un fichier "discovery" ?

Merci.

**Comment by tcharp38** [comment]
Bonjour

Pour l'ajout de tout nouvel equipement, voir la doc la:
https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

Pour info le SML004 est aussi en cours d'inclusion.

J'aurai aussi besoin d'une belle image PNG sans arriere plan pour mettre en icone
et de connaitre le type de piles.

**Comment by scotchbitman** [comment]
Bonjour,

Merci pour votre réponse. Je viens d'effectuer la procédure d'ajout.
Voici donc le fichier "discovery" qui en ressort:

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/9507046/discovery.zip)

Voici également l'image demandée :

![philips-motion-sensor-sml003](https://user-images.githubusercontent.com/8740095/188904328-ef866402-09bb-40cd-aa61-cb1f72d75125.png)

Le type de piles utilisées dans cet appareil sont des AAA x 2

Merci.

**Comment by tcharp38** [comment]
A tester

A decompresser dans core/config/devices
[SML003.zip](https://github.com/KiwiHC16/Abeille/files/9508781/SML003.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by scotchbitman** [comment]
Bonjour tcharp38,

Merci.
Je viens de tester le fichier que vous m'avez fourni, visiblement l'appareil est à présent reconnu mais dès l'inclusion j'ai ce message qui apparaît :

**Le fichier de commande 'zb-0406-Occupancy.json' n'existe pas.**

Pour info j'obtiens ce nouveau panneau de commande sur le dashboard (voir ci-dessous) mais à mon avis il manque en effet la partie "occupation" ou capteur de mouvement.

![capteur-mvt-pannel](https://user-images.githubusercontent.com/8740095/189142604-03cd0f9b-e217-40c4-8ff1-37c87ad7b123.jpg)

Merci.

PS : Pour le moment il n'y a pas d'icône visible sur le plugin Abeille mais j'imagine qu'elle sera intégrée par la suite ?

**Comment by tcharp38** [comment]
Salut
Effectivement j'ai oublié d'autres fichiers mais je te suggere de basculer sur la beta qui contient toutes les dernieres mises à jour.
Voir la: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by tcharp38** [comment]
Salut @scotchbitman 
On en est ou ?
Comme il y a aussi le SML004 en // peut etre qu'il y a des choses assez communes.

**Comment by scotchbitman** [comment]
Salut @tcharp38 
Pour l'instant je n'ai pas fait la bascule sur la beta, d'après la doc que tu m'as fournie, pour utiliser des plugins en beta il faut aussi passer Jeedom en beta. Du coup j'ai reporté l'opération à plus tard :)

Sinon quand prévoyez-vous de faire passer vos modifs sur la version stable ?

Merci.

**Comment by tcharp38** [comment]
Salut

Non non juste Abeille en beta.

Mais bon si tu ne veux pas basculer, voila le fichier qui semble manquer. 
A decompresser dans core/config/commands
[zb-0406-Occupancy.zip](https://github.com/KiwiHC16/Abeille/files/9632015/zb-0406-Occupancy.zip)

Le passage beta vers stable ne se fera que lorsque plusieurs utilisateurs auront stressé un peu la beta pour etre sur qu'il n y a pas de regression bloquante.

**Comment by scotchbitman** [comment]
Hello tcharp38,

OK c'est noté pour la version beta.
Merci pour le fichier manquant, ça fonctionne parfaitement à présent.

Bonne journée.
