### ISSUE TITLE
Intégration module 

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2441]
Hello @tcharp38 ,

J'ai voulu inclure le module suivant :
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

Mais il n'est pas reconnu correctement par le plugin Abeille. Abeille me le reconnait comme étant : Yagusmart Tuya ZigBee Smart Switch

Est-il possible de modifier/créer son json pour qu'il soit correctement reconnu ?

Je te joins les log d'après inclusion, l'ID du module est le 269

D'avance merci
Tommy

[AbeilleLogs-220907.tar.gz](https://github.com/KiwiHC16/Abeille/files/9526859/AbeilleLogs-220907.tar.gz)

**Comment by tcharp38** [comment]
Salut
Toute demande de nouvel equipement doit au moins venir avec le fichier discovery pour avoir un minimum d infos.
Voir la: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement
Avec ce fichier j'aurai sa signature

**Comment by Thiematz** [comment]
Salut,
ok, je clôture celui-ci et refait un dans la bonne catégorie ;-)

Merci

**Comment by tcharp38** [comment]
Pas obligé de cloturer :) Tu pouvais juste editer le titre et le changer.
