### ISSUE TITLE
Inclusion TuYa smart plug (id= TS011F, _TZ3000_gjnozsaz)

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2443]
Salut,

je viens d'inclure un module "Power Plug NAS-WR01B" qui est en fait un TuYa TS011F_plug_1 dont voici le lien descriptif

https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

Joins également le discorery.json

Merci pour ton aide
Tommy

[discovery(12).zip](https://github.com/KiwiHC16/Abeille/files/9533442/discovery.12.zip)

**Comment by tcharp38** [comment]
Tiens voila un modele preliminaire

a decompresser dans core/config/devices
redemarrer Abeille
et refaire inclusion

[TS011F__TZ3000_gjnozsaz.zip](https://github.com/KiwiHC16/Abeille/files/9533991/TS011F__TZ3000_gjnozsaz.zip)

**Comment by Thiematz** [comment]
Génial, ça marche !

Merci @tcharp38, t'es au top !!

**Comment by tcharp38** [comment]
Tout est bon ?

**Comment by Thiematz** [comment]
Oui c'est tout bon!
