### ISSUE TITLE
LIDL-Livarno HOME ampoule LEd  Blanc-couleur  Ogive (id = TS0505B, _TZ3000_th6zqqy6)

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2448]
Bonjour voici le discovery d'une ampoule Led Lidl monté dans le plugin mais non reconnu.

[discovery_TZ3000_th6zqqy6.zip](https://github.com/KiwiHC16/Abeille/files/9594166/discovery_TZ3000_th6zqqy6.zip)

Pourriez vous en faire l'ajout? merci.

**Comment by tcharp38** [comment]
Salut

A decompresser dans core/config/devices
[TS0505B__TZ3000_th6zqqy6.zip](https://github.com/KiwiHC16/Abeille/files/9594863/TS0505B__TZ3000_th6zqqy6.zip)

puis redemarrer Abeille
et refaire inclusion

j'ai besoin d'une ref/modele
et d'une image PNG sans arriere plan pour mettre en icone
et d'un lien vers la description du produit/doc

**Comment by VVorttexx** [comment]
ok pour l'installation cela fonctionne, color.
il me manque un cool white warm white pour la led Blanche (pour l'instant le white fait un mixte des 3 couleurs)
(même PB que pour Ampoule LivarnoLux (Lidl) led gu10 HG08131A (TS0505B, _TZ3000_quqaeew6) )

ref: HG07834B
![image](https://user-images.githubusercontent.com/47332515/191008568-c75f0dda-a519-4120-a051-0348b2d494bf.png)
Jej n'ai pas de lien Lidl, ou livarno le plus propre est https://www.zigbee2mqtt.io/devices/HG07834B.html

**Comment by VVorttexx** [comment]
![lux2](https://user-images.githubusercontent.com/47332515/191042525-bbcd8c53-50e8-42b2-b918-d1cf232baa17.png)


un fond transparent, plus en cohérence avec les autres icone lidl du plugin

Et j'ai trouvé ça aussi
https://www.lidl.be/p/fr-BE/livarno-home-ampoule-led-smart-home/p100340514

**Comment by VVorttexx** [comment]
Hello, 
c'est faisable du coup?
il manque un cool white warm white pour la led Blanche (pour l'instant le white fait un mixte des 3 couleurs)
(même PB que pour Ampoule LivarnoLux (Lidl) led gu10 HG08131A (TS0505B, _TZ3000_quqaeew6) )

**Comment by tcharp38** [comment]
Peux tu me faire un snapshot du widget créé sur le dashboard
et me dire quels sont les boutons qui sont fonctionnels ou pas, avec leur effet ?
Merci

**Comment by VVorttexx** [comment]
voici
![image](https://user-images.githubusercontent.com/47332515/192156054-e51f8bc7-d700-44a4-bc42-ddeac3484829.png)

tous les boutons fonctionnent suivant leur nom. (mais le white fait du blanc avec la combinaison des 3 leds de couleur.)

pour mémoire, tu avais modifié ma précédente demande comme ça:
![image](https://user-images.githubusercontent.com/47332515/192156191-230694ad-78cf-4c05-a01a-36228220abc0.png)

la le white allume les 3 led pour faire du blanc.
alors que le cool white allume la led blanche seule.
Merci à toi.

**Comment by tcharp38** [comment]
Voila un nouveau modele
[TS0505B__TZ3000_th6zqqy6.zip](https://github.com/KiwiHC16/Abeille/files/9682741/TS0505B__TZ3000_th6zqqy6.zip)

Peux tu, via la page EQ/avancé, faire un "reinitialiser" et verifier le dashboard ?

**Comment by VVorttexx** [comment]
Hello, marche nickel.
MERCI
![image](https://user-images.githubusercontent.com/47332515/193272244-c774fad5-8e74-4e0e-a53e-8d6b82772485.png)
