### ISSUE TITLE
Prise de courant étanche connectée Plexo with Netatmo 16A (id = Connectedoutlet, Legrand)

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2449]
Bonsoir,

J'ai ajouté une prise extérieure Legrand à mon réseau de ce modèle : 
![image](https://user-images.githubusercontent.com/71673288/191100591-becea6b0-cffc-4315-92ce-7a8848d9634b.png)
https://www.legrand.fr/pro/catalogue/43074-version-plexo-with-netatmo/prise-de-courant-etanche-connectee-plexo-with-netatmo-16a-3680w-complet-saillie-2-postes-gris
Ref. Legrand 069796

Elle est détectée comme un "_Legrand Prise Connected Outlet Mural 220V avec Neutre_" donc il faudrait créer un nouveau modèle qui corresponde à cette prise.

Ensuite, j'ai rien ou presque dans l'assistant de découverte : 
![image](https://user-images.githubusercontent.com/71673288/191101219-38b6ad11-5b4d-4024-96c8-88aa6af69bad.png)

[discovery Legrand.zip](https://github.com/KiwiHC16/Abeille/files/9601886/discovery.Legrand.zip)

Et même si le device semble à peu près correctement inclus rien ne fonctionne : 
![image](https://user-images.githubusercontent.com/71673288/191101845-cb460070-41e2-4af4-88bd-1268164982de.png)

Les logs, inclusion à 21:23 :
[AbeilleLogs-220919 Legrand.tar.gz](https://github.com/KiwiHC16/Abeille/files/9601906/AbeilleLogs-220919.Legrand.tar.gz)

**Comment by tcharp38** [comment]
Vu que cette prise s'identifie comme un modele existant, il n'y a rien à faire d'autre que s assurer qu'il soit fonctionnel.

Mais dans ton cas l'inclusion se passe mal.
On dirait qu'il y a un souci de routage avec ta prise

> [2022-09-19 21:23:18] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=96E1, EP=00, ClustId=0021, SQNAPS=70
> [2022-09-19 21:23:20] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=96E1, EP=01, ClustId=0006, SQNAPS=71
> [2022-09-19 21:23:20] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=96E1, EP=01, ClustId=0B04, SQNAPS=72
> [2022-09-19 21:23:23] Abeille1, Type=8701/Route discovery confirm, MACStatus=00/ZPS_EVENT_NONE, NwkStatus=D0/ZPS_NWK_ENUM_ROUTE_DISCOVERY_FAILED, Addr=96E1
>

**Comment by eoeir** [comment]
Je n'ai pas eu le temps de refaire un test d'inclusion ce soir mais j'en ai fait plusieurs avant d'ouvrir cet issue avec le même comportement. Il est probable que les inclusions ratent systématiquement.

Depuis hier soir, aucune communication avec la prise depuis l'inclusion ratée : 
![image](https://user-images.githubusercontent.com/71673288/191362803-255f91c7-a9c0-4068-858f-f459948790cd.png)

**Comment by eoeir** [comment]
Je me suis fais une serie de tests d'inclusion et à force de tentatives, j'ai réussi à faire une inclusion réussie.

Grâce à la solution trouvée ici https://community.jeedom.com/t/prise-legrand-with-netatmo/10246, voici la procédure qui a marché pour moi : 
- exclusion + suppression du module d'Abeille
- appui long (8-10s) sur le bouton reset jusqu'à ce que la LED (en rouge) clignote
- coupure alimentation électrique du module
- mettre la zigate en mode inclusion
- maintenir le bouton reset appuyé et remettre le module sous tension
- garder le bouton reset appuyé jusqu'à ce que la LED (en rouge) clignote
Et là miracle, le module fait son inclusion, la LED passe en vert et le module répond aux commandes. 

Il faudra que je répète l'opération pour être certain que la procédure est reproductible.

Voici le fichier discovery et les logs : 

[discovery Legrand.zip](https://github.com/KiwiHC16/Abeille/files/9628599/discovery.Legrand.zip)
[AbeilleLogs-220922.tar.gz](https://github.com/KiwiHC16/Abeille/files/9628602/AbeilleLogs-220922.tar.gz)

**Comment by pipiche38** [comment]
https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/Corner_Legrand-Netatmo.md#pairing-processAprès il faut aussi que la prise soit mise sous tension après la zigate, ainsi que les autres périphériques Legrand.En effet les prises comptabilisent leurs durées de fonctionnement et si il y a un gros écart l’appairage ne se fait pas.Envoyé de mon iPhoneLe 22 sept. 2022 à 20:48, eoeir ***@***.***> a écrit :﻿
Je me suis fais une serie de tests d'inclusion et à force de tentatives, j'ai réussi à faire une inclusion réussie.
Grâce à la solution trouvée ici https://community.jeedom.com/t/prise-legrand-with-netatmo/10246, voici la procédure qui a marché pour moi :

exclusion + suppression du module d'Abeille
appui long (8-10s) sur le bouton reset jusqu'à ce que la LED (en rouge) clignote
coupure alimentation électrique du module
mettre la zigate en mode inclusion
maintenir le bouton reset appuyé et remettre le module sous tension
garder le bouton reset appuyé jusqu'à ce que la LED (en rouge) clignote
Et là miracle, le module fait son inclusion, la LED passe en vert et le module répond aux commandes.

Il faudra que je répète l'opération pour être certain que la procédure est reproductible.
Voici le fichier discovery et les logs :
discovery Legrand.zip
AbeilleLogs-220922.tar.gz

**Comment by tcharp38** [comment]
@pipiche38 
Merci pour tes infos.

@eoeir 
Je vois que le dernier appairage a réussi.
Je ne sais pas si qqch doit et peut etre amélioré coté Abeille. La je vois pas.
Mais du coup c'est tout bon pour toi ?

J'ai ajouté l'image en tant que "Legrand-Connectedoutlet-2" mais sans modifier le modele vu que la signature reste identique, donc pas possible de mettre la bonne image tout le temps.

**Comment by eoeir** [comment]
Je viens de faire une nouvelle image avec le fond transparent pour remplacer celle avec le fond blanc :

![191100591-becea6b0-cffc-4315-92ce-7a8848d9634b2](https://user-images.githubusercontent.com/71673288/206920434-b1f95be2-8b77-4801-9f35-a44bbc4b5564.png)

Depuis que j'ai réussi l'inclusion, la prise fonctionne mais elle se met en time-out. Quand je passe une commande elle fonctionne.

J'ai l'impression aussi que si je lui associe un capteur, celui-ci passe également en time-out et sort du réseau. Il faudrait que je fasse plus de tests pour confirmer ce point.

**Comment by tcharp38** [comment]
Tente de faire un reinitialiser et dis moi si il revient en timeout apres.
J'ai pris l'image. Merci

**Comment by eoeir** [comment]
Depuis la version précédente d'Abeille (pas celle d'aujourd'hui), il n'est plus en timeout.

Je laisse le sujet ouvert au cas où mais ça semble bon.

**Comment by tcharp38** [comment]
Salut @eoeir 
On peut clore le sujet ?

**Comment by eoeir** [comment]
Oui, je clos.
