### ISSUE TITLE
Motion Xiaomi: Temporisation retour à 0

### ISSUE THREAD

**Issue by alex1313c** [KiwiHC16/Abeille#2450]
Bonjour

Je suis entrain de passer mes capteurs sur le plugins Abeille , jusqu’à présent j’utiliser le plugins zigate

Je remarque que le tempo pour le retour d’état des capteurs motion Xiaomi / Aqara dépasse les 1m30 sur abeille alors que sur le plugin Zigate le retour d’état était de 30 secondes

Avez-vous une solution pour modifier le temps du retour d’état

je vous remercie

**Comment by tcharp38** [comment]
Salut

Via la page EQ/avancé peux tu me confirmer le modele JSON utilisé ?

**Comment by alex1313c** [comment]
Bonjour @tcharp38  

J'ai que 2 capteur de cette marque les modèles sont différents

Si je me trompe pas pour le modèle JSON

le premier sensor_motion.aq2 ( modèle avec le bouton )
le deuxieme sensor_motion  ( modèle sans bouton )

**Comment by tcharp38** [comment]
Je vois les infos "presence" & "luminosité".
Donc quand tu parles de retour d etat tu parlse du temps de reaction de "presence" ?

**Comment by alex1313c** [comment]
Bonsoir

Lorsque un mouvement et détecter, le temps pour que le capteur capteur
retourne à 0. Pour pouvoir détecter un autre mouvement

**Comment by tcharp38** [comment]
Ha ok.

Peux tu 
- basculer sur la beta: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta
- passer en mode debug: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support
- une fois que tu as redemarré tout ca tu declenches une detection  et note l'heure
- et me file le package de logs (page maintenance + telecharger tout)... drag & drop ici

Merci
Je vais voir comment ca se comporte.

**Comment by alex1313c** [comment]
Bonjour @tcharp38 

Voici le fichier de log en debug, j'ai déclencher le  détecteur jusqu’à son retour en état 0, les délais sont aléatoire

20:59:00
21:00:02

21:02:01
21:04:03

[AbeilleLogs-220923.tar.gz](https://github.com/KiwiHC16/Abeille/files/9636547/AbeilleLogs-220923.tar.gz)

**Comment by tcharp38** [comment]
Ok je crois que je comprends.

Ce sensor n'envoie pas 1 puis 0. Il se contente d'envoyer 1 lors de l'evenement.
Le retour à 0 vient donc du côté Jeedom mais comment on fait ca.. bonne question.
Je creuse

**Comment by tcharp38** [comment]
C'est donc fait par Jeedom via la configuration  'returnStateTime' = 1
Manque de pot a priori c'est en minutes donc au min retour à 0 1 minute apres.

Tu peux tenter qqch.
- clic sur ton equipement
- puis configuration avancée en haut à droite
- trouve la commande "etat"
- puis a droite de cette commande il y a une roue crantée
  
![image](https://user-images.githubusercontent.com/35221038/192088948-bae8d3f5-ade9-4ac8-941a-5b296501e93e.png)

- onglet configuration
- et tu dois trouver un truc comme ca

![image](https://user-images.githubusercontent.com/35221038/192088970-d1325ec4-9755-4742-82f5-67342e0243a0.png)

L'idée est de voir si en mettant 0.5 au lieu de 1 dans la "Durée avant retour d'état" ca peut fonctionner.
Donc 0.5 puis sauve puis test

**Comment by alex1313c** [comment]
Sur l'ancien plugins que j’utilisé. le capteur envoyé sont état à 0 a la zigate
Effectivement quand tu repasse devant l’état 1 reste plus longtemps car le capteur doit renvoyé sont état 1 
Les capteurs on une temporisation d’origine de 30 secondes pour passer de 1 a 0,

**Comment by alex1313c** [comment]
Oui je viens de voir dans gestion des valeurs retour a 0 après 1 min

**Comment by tcharp38** [comment]
> Sur l'ancien plugins que j’utilisé. le capteur envoyé sont état à 0 a la zigate Effectivement quand tu repasse devant l’état 1 reste plus longtemps car le capteur doit renvoyé sont état 1 Les capteurs on une temporisation d’origine de 30 secondes pour passer de 1 a 0,

Je ne sais pas comment on fait 30sec.
D 'ou l essai proposé avec 0.5min.

**Comment by alex1313c** [comment]
30 Seconde c'est interne au capteur :)
Il envoyer 1 a la zigate et 30 seconde apres il envoyer 0 

0.5 ne fonctionne pas les capteurs reste  bloqué sur 1

**Comment by tcharp38** [comment]
Non 30sec ca n'est pas interne vu que la il n'envoi jamais le 0 d apres les logs.

Donc je ne vois pas comment la valeur retombe à 0.

**Comment by alex1313c** [comment]
sinon c'est pas bien grave :).  1 min c'est pas la fin du monde non plus :)

**Comment by tcharp38** [comment]
Oui mais j'aimerais bien savoir comment c'est géré avec le plugin Zigate pour obtenir 30sec.
C'est peut etre un truc dans Jeedom que je ne connais pas.

**Comment by alex1313c** [comment]
Si je réinstalle le plugins et j'associe le capteur , Les associations reste pour les autres équipement avec abeille ?

**Comment by tcharp38** [comment]
Les equipements "Abeille" restent oui.
Comme le device est deja sur la zigate tu vas juste le reassocier sur le meme reseau mais cette fois il sera géré par le plugin Zigate.
Ca devrait le faire.

Apres il faudra qu'il soit en mode debug, que tu declenches une detection, attende le retour à 0 avant de filer les logs "zigate".
Et il faudrait aussi regarder la partie "retour d'etat" pour la commande info equivalente

![image](https://user-images.githubusercontent.com/35221038/192136085-41767ea5-21f6-45eb-9826-fe3b638df0a1.png)

**Comment by alex1313c** [comment]
Pour le premier capteur et le deuxieme capteur. maintenant c'est 10 seconde au lieu de 30. 

pas de retour d'etat depuis jeedom, plutot un Set expire timer for 1-1030-0 in 10 depuis zigate

[log.zip](https://github.com/KiwiHC16/Abeille/files/9640988/log.zip)

**Comment by tcharp38** [comment]
C'est quoi ce set expire timer ? Ça se trouve ou ? Tu as un snapshot ?

**Comment by alex1313c** [comment]
log capteur 1
[2022-09-25 16:25:10][DEBUG][zigate](ZiGate-Decode data) : Set expire timer for 1-1030-0 in 10

**Comment by tcharp38** [comment]
Ha donc tu vois ca dans les logs mais tu ne vois pas où ça se configure. C'est bien ça ?

**Comment by alex1313c** [comment]
oui c'est ca.  par contre depuis la mise a jour en OPDM le temps est passer de 30 a 10 seconde je ne sais pas si il y a un lien 
dans le plugins je ne voit pas ou est cette info de 10

**Comment by alex1313c** [comment]
https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html#note-about-occupancy-timeout-option

occupancy_timeout: Time in seconds after which occupancy is cleared after detecting it (default 90 seconds). The value must be a number with a minimum value of 0

**Comment by tcharp38** [comment]
Tu as fait la mise à jour en OPDM ? Via Abeille ? Autrement ?
Donc tu as tout reappairé ?

**Comment by alex1313c** [comment]
J'en ai profiter lors du changement de plugins pour passer de 3.21 legacy a 3.21 ODPM
J'ai fais la mise a jour depuis abeille, et quand j'ai fais les test avec le plugins zigate  le temps de retour pour l'etat 0 est passer de 30 a 10 secondes mais je ne sais pas si ca a un lien

**Comment by tcharp38** [comment]
On trouve ca dans le log "zigate":
[2022-09-25 16:31:06][DEBUG][zigate](ZiGate-Decode data) : Set expire timer for 1-1030-0 in 10

Donc c'est bien le plugin qui semble changer la valeur 10sec apres, et pas Jeedom.
Cette fonctionalité n'existe pas dans Abeille. Dommage que Jeedom ne le gere pas en dessous d'1 min

Je viens d'ouvrir un sujet chez Jeedom la dessus: https://community.jeedom.com/t/cmde-info-retour-detat-inferieur-a-la-minute/91426

**Comment by tcharp38** [comment]
Confirmé: Jeedom ne gere pas ca donc il faut une implementation Abeille pour le faire.
Je vais y reflechir mais pas pour tout de suite je pense.

Donc... pas de retour à 0 inferieur à 1min

**Comment by alex1313c** [comment]
Oui pas de soucis, merci pour ton aide
1 min c'est pas la fin du monde non plus :). si tu as besoin de faire des test, pas de soucis

En tous cas c'est un très bon plugins

**Comment by tcharp38** [comment]
1 min c'est la limitation Jeedom.
J'ai mis dans ma TODO list de quoi trouver une solution pour faire mieux.

Du coup que reste il sur ce sujet ?

**Comment by mickadam29** [comment]
Salut à vous 2. N'utilisant plus Abeille je me permets tout de même une remarque. Dans Abeille, avec Zigate j'avais mis une valeur de retour d'état et une durée. Comme évoqué dans ce post. @alex1313c , lorsque tu dis que l'état du détecteur revient à sont état initial au bout de 30 puis 10 secondes (plugin et jeedom), es-tu certain que le capteur est en mesure de détecter à nouveau une présence à l'issue de ces quelques secondes  ?  De mémoire, sous un délai proche de 2min, aucun mouvement n'est retourné. C'est à dire que ton Xiaomi n'enverra qu'un seul mouvement dans un intervalle de 2 min. Donc la valeur par défaut de 1min convient. En revanche, lui indiquer la valeur retour d'état était indispensable pour moi. Le capteur envoie l'info lorsqu'il détecte une présence mais ne renvoie pas forcément l'info à l'issue de son time out (jeedom, je ne perçois plus de mouvement). Tout cela a peut-être évolué depuis. Je suis passé de Abeille à Z2M il y a qq mois déjà. @tcharp38 toujours dans le dev à ce que je vois. Bon courage à toi et @KiwiHC16

**Comment by alex1313c** [comment]
@mickadam29 , oui sous le plugins zigate j'etait a 30 seconde pour le retour d’état et détection possible dessuite après
je suis passer a abeille et la redetection est variable, je suis repasser pour des test sur zigate et maintenant c'est plus 30 mais 10 seconde et le capteur redetecte dessuite apres ( la seul manip que j'ai fait c'est de passer en version OPDM et ré-associer

Les 2 capteurs que j'ai de cette marque ne sont pas modifier

@tcharp38  Merci, après c'est pas gênant dans mon utilisation pour ces 2 capteurs. la je cherche plutot a eteindre la led de la pizigate.  lors que je le fais elle fini par s'allumer de nouveau

**Comment by tcharp38** [comment]
Hello
Du coup concernant ce sujet reste t'il qqch à voir ?

J'ai bien noté dans ma TODO de trouver une solution pour descendre en dessous de la minute en retour d'etat mais pas dans mes priorites.

**Comment by alex1313c** [comment]
@tcharp38 
salut desole pour le temps de réponse 
non plus rien :)

merci
