### ISSUE TITLE
Ampoule connectée Livarno: TS0502A 

### ISSUE THREAD

**Issue by Kamiz09** [KiwiHC16/Abeille#2456]
Salut,
Voici une nouvelle ampoule de chez Livarno. Référence : HG08130C
Elle apparait sous le nom suivant dans Abeille : TS0502A

Voici les logs lors de l'inclusion : 
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/9639167/AbeilleParser.txt)

Ce n'est pas une ampoule RGB.
Température de couleur min. : 2000K
Température de couleur max. : 6500K

**Comment by tcharp38** [comment]
Salut @Kamiz09 
J'ai besoin du discovery: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by Kamiz09** [comment]
Mince, je n'ai pas l'Assistant de découverte en version 2020-07-16 d'Abeille.
Je n'ai pas le choix de faire la mise à jour du plugin (2022-09-17) ? Pas de problème de compatibilité avec la PiZigate en version 031c ?

**Comment by tcharp38** [comment]
Ouahhhh.
Alors vue la quantité de changements (dont syntaxe de modeles) et corrections ou améliorations.. pas le choix que de te mettre à jour.

Mais tu vas devoir
- mettre le plugin à jour: note qu apres ca je pense que ca ne fonctionnera plus tant que le FW de la zigate n'est pas lui aussi à jour.
- puis dans la foulée passer le FW en version 3.21-LEGACY

En gardant la version "legacy" tu ne devrait pas avoir besoin de faire de reappairages.

**Comment by Kamiz09** [comment]
J'avais prévu de réinstaller complètement mon système de toute manière, histoire d'être à jour.
Je reviens vers toi à ce moment-là du coup 👍

**Comment by tcharp38** [comment]
Salut @Kamiz09 
Des nouvelles ?
Toujours intéressé ?

**Comment by tcharp38** [comment]
Pas de vie.
Je ferme le sujet.
A réouvrir si ca interesse qqn
