### ISSUE TITLE
Post Beta 27/09: plus d'inclusion dans la ruche, mais déplacé dans la conf. du plugin.

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#2462]
Bonjour,

Suite a ce commit https://github.com/KiwiHC16/Abeille/commit/6917e708317cde7c3e2a6fd9b43af233cb43ec32#diff-8342cb63575e46c6b6a06dddfde47ebbe132f5af2c507070fe5a4da5e4057529, le bouton inclusion a disparu de la ruche. 
il semblerait que les deux minuscules boutons + et - de la page de configuration du plugin le remplacent.
Peux tu confirmer ? Dans le code, ces boutons semblent etre présent dans une page (modal) healthshort , je ne les ai pas trouvé.  les boutons inclusion/fin inclusion sont ils présents ailleurs ?

![image](https://user-images.githubusercontent.com/3601462/193480792-8b939e49-6c0c-43dd-81c4-dd1ad2253264.png)

**Comment by tcharp38** [comment]
Salut @edgd1er 
En ce qui me concerne je ne connaissais pas d'autre moyen de passer la zigate en mode inclusion autrement que depuis ce bouton "+"
![image](https://user-images.githubusercontent.com/35221038/194027714-0abb036e-5914-4c8a-ab7e-8546a20dcc20.png)

J'ai toujours utilisé ça.

Mais donc tu tu utilisais une commande via la page "Avancé" de la zigate. C'est bien ça ?

J'ai probablement fait du ménage.

**Comment by edgd1er** [comment]
Salut @tcharp38,

Avant le commit cité, il y avait dans le ruchecommand.json une commande "inclusion" caché par défaut, mais qui activée faisait apparaitre le bouton "inclusion" dans la ruche sur la page principale (index.php...P=dashboard) qq part entre extpan et network status.

Je ne demande pas forcément le retour de la commande, je ne connais pas la raison qui a conduit à la suppression. L'idée était plus de savoir si l'inclusion via le + vert était la (nouvelle pour moi) façon de faire. 

le menage est question ;) core/config/rucheCommand.json
![image](https://user-images.githubusercontent.com/3601462/194108788-ac631055-1d2e-4299-8c5d-5f1010944e70.png)

![image](https://user-images.githubusercontent.com/3601462/194107181-630cffe4-e0f2-4b2e-91af-d172b50418d3.png)

**Comment by tcharp38** [comment]
Ha oui c'est ca.

En fait je considere qu'une cmde Jeedom est necessaire si ca peut rentrer dans le cadre d'un controle via scenario ou autre plugin Jeedom. Ca n'est pas le cas ici. 
Du coup j'ai viré des tas de commandes Zigates difficilement utilisables au profil de la page avancée.
Mais pour l'inclusion je crois qu'il manque un bouton sur la page avancé pour l'ouvrir.

Sinon depuis le debut (ca vient de Kiwi), entrer ou sortir du mode inclusion se fait via le + et - de la page de gestion.

Donc si j'ajoute un bouton sur la page avancée, ca te va ?

**Comment by tcharp38** [comment]
Bon du coup j'ai ajouté 2 boutons dans la partie "Avancé" pour pouvoir controller ca la aussi

![image](https://user-images.githubusercontent.com/35221038/194284683-5bd4fbe4-e5e9-404f-ab3c-20078e0d5ffc.png)

Ca sera dans la prochaine beta.

**Comment by edgd1er** [comment]
oui, l'un (+ et-) ou l'autre (page avancé) conviennent. Je dirais que le reglage dans la page avancée est plus intuitive que les +/-.
Merci pour la modif et les explications.

**Comment by tcharp38** [comment]
Oui d'accord avec toi. Pas intuitif. Sans doc ca ne tombe pas sous le sens.
Peut etre à améliorer un jour.

On peut clore ce sujet ?

**Comment by edgd1er** [comment]
oui. :)
