### ISSUE TITLE
Ajout Support Interrupteur Aqara WallSwitch (id = switch.b1lacn02)

### ISSUE THREAD

**Issue by mistersmile1002** [KiwiHC16/Abeille#2466]
Bonjour. 
Serait-il possible d'inclure cette interrupteur dans la gestion du plugin Abeille.
Merci pour votre dev et toutes les améliorations que vous apportez au quotidien.
[discovery.json.zip](https://github.com/KiwiHC16/Abeille/files/9732911/discovery.json.zip)

**Comment by tcharp38** [comment]
Salut @mistersmile1002 

C'est bien un QBKG21LM ?

Voila un modele. A decompresser dans core/config/devices
[switch.b1lacn02.zip](https://github.com/KiwiHC16/Abeille/files/9734273/switch.b1lacn02.zip)

puis redemarrer Abeille
refaire inclusion
test & résumé

**Comment by Mickael-CloudGirafe** [comment]
Salut @tcharp38 

Merci pour le fichier.
J'ai fait toutes les manipulations et le l'interrupteur s'est bien ajouté mais les commandes ne fonctionnent pas. Il a bien reconnu mon modele et tout semble correct pourtant.
Je n'arrive pas a allumer et éteindre la lumière.

**Comment by tcharp38** [comment]
Passe en mode debug et file moi un package de logs STP: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

**Comment by Mickael-CloudGirafe** [comment]
[AbeilleLogs-221007.tar.gz](https://github.com/KiwiHC16/Abeille/files/9735042/AbeilleLogs-221007.tar.gz)
Voici les logs en mode debug.

**Comment by tcharp38** [comment]
Tu n'es pas en mode debug ou alors tu n'as pas redemarré Abeille apres le changement ou pas sauvegardé avant de redemarrer.
Les logs sont quasi vides.

Autre chose.. peux tu basculer sur la beta ? https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by Mickael-CloudGirafe** [comment]
J'ai bien activé les logs en debug et rédémarré le plugin.
Je viens de passer en beta.
[AbeilleLogs-221010 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/9745112/AbeilleLogs-221010.2.tar.gz)

**Comment by tcharp38** [comment]
Bah non. Logs toujours vides.
Quand tu mets "debug", tu dois "sauvegarder", puis redemarrer démon Abeille pour que ca soit pris en compte :(

**Comment by mistersmile1002** [comment]
j'ai l'mpression que le plugin est bien passé en mode debug.
Dit moi si c'est ok.
[AbeilleLogs-221016.tar.gz](https://github.com/KiwiHC16/Abeille/files/9794671/AbeilleLogs-221016.tar.gz)

**Comment by tcharp38** [comment]
@mistersmile1002 
Ok. Je vois les logs.
Peux tu appuyer sur le switch, noter l heure, et me filer à nouveau le package de logs ?

**Comment by mistersmile1002** [comment]
Bonjour je viens d'appuyer sur le bouton aujourd'hui à 17h20
[AbeilleLogs-221026.tar.gz](https://github.com/KiwiHC16/Abeille/files/9870913/AbeilleLogs-221026.tar.gz)

**Comment by tcharp38** [comment]
Salut.
Sauf erreur la tu as appuyé sur le dashboard.
Je vois que le End point est mauvais (01 au lieu de 02).
Faire, via la page EQ/Avancé => reinitialiser

Puis appuyer sur le switch du dashboard + heure + logs
Puis appuyer sur le switch lui meme + heure + logs

Merci

**Comment by mistersmile1002** [comment]
Bonjour.
Désolé je n'ai pas pu poster avant. 
J'ai fait les mise à jour Abeille et l'interrupteur fonctionne de nouveau.
Merci
