### ISSUE TITLE
dongle invisible depuis maj Abeille Beta

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2471]
Salut a tous,

j'ai procédé à la maj du plugin abeille Beta jeudi dernier, comme à chaque maj en fait !

Suite à cela, un message m'informait qu'il serait bon de faire la maj du module PIZigate. Je m’exécute depuis le plugin Abeille.

Et là, le drame ! la maj qui bloque et plus moyen d'avoir un retour d'état du PiZigate.

Ma question : y a t'il moyen de forcer d'une manière ou d'une autre (via le plugin/Jeedom ou depuis Linux) la maj de la PiZigate histoire de la retrouver dans Abeille ?

D'avance merci pour toute l'aide que vous pourrez m'apporter, je sèche!

PS : j'ai même essayé de restaurer une sauvegarde à la veille de la maj, mais rien n'y fait!
PS2 : je vous mets les logs, si des fois cela peut aider ;-)

[AbeilleLogs-221010.tar.gz](https://github.com/KiwiHC16/Abeille/files/9745873/AbeilleLogs-221010.tar.gz)

**Comment by tcharp38** [comment]
Salut @Thiematz 
Désolé pour toi. On va tacher de comprendre ce qui se passe.

Peux tu me donner un snapshot de ta page de config ? Je ne comprends pas le "dongle invisible"
Vite fait comme ca je vois que le type de la zigate 1 est USB alors que tu as dit que c'était une PI. Ca n'est pas coherent.
D'autre part si USB, Abeille ne peut pas la mettre à jour. C'est bien trop particulier vu qu'il faut la debrancher et demonter.

D'autre part avant de te lancer dans la mise à jour du FW tu etais dans quelle version et tu as migré vers quelle version ?

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

merci pour ton aide !

Ma ruche est sur la PI, mais tu as raison, dans les logs tu as vu USB car j'ai testé les différentes possibilité car j'en étais réduit à "pfff, je sais plus quoi essayer" ;-)

Maintenant c'est de nouveau la conf initiale
![image](https://user-images.githubusercontent.com/94549335/194902614-14647482-f8c7-4233-93da-7e8a527f40df.png)

la PI est (était, en fonction de son état actuelle inconnu) en 3.20 Legacy. Je voulais la passer, comme proposé en 3.21 Legacy.

J'ai, ce matin, avant de partir au taff, branché sur l'USB du raspberry, un dongle Zigate (la rouge) et j'ai réussi, sur la zigate 2 à la voir, ce qui m'a créé une seconde ruche.

**Comment by tcharp38** [comment]
Peux tu desactiver la gestion automatique du demon
puis arreter le demon
tester l'acces au port via le bouton "Tester" de la PI
et voir ce que ca donne ? File moi le log AbeilleConfig STP

**Comment by Thiematz** [comment]
C'est fait! Aucune amélioration!

Voici le log. Si je comprends bien, il y a quelque chose qui monopolise le port en question (j'essai de comprendre en même temps ;-))
[AbeilleConfig.zip](https://github.com/KiwiHC16/Abeille/files/9747930/AbeilleConfig.zip)

**Comment by tcharp38** [comment]
Le check ne fonctionne pas.

> [2022-10-10 19:35:29] Démarrage de 'checkTTY.sh'
> [2022-10-10 19:35:29] Vérifications du port '/dev/ttyAMA0'
> [2022-10-10 19:35:29] = ERREUR: Le port est utilisé par le process '6841'.
> [2022-10-10 19:35:29] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
> [2022-10-10 19:35:29] =         Details du process 6841:
> [2022-10-10 19:35:29] =           PPid=822, cmd='/usr/sbin/apache2 -k start'
> 

Qqch utilise toujours le port.
Peux tu arreter manuellement Abeille apres avoir supprimé la gestion auto surtout sinon Jeedom le relance.
Il y a qqch dans cette partie qui n'est pas propre et pas compris.

**Comment by Thiematz** [comment]
qu'entends tu par "arreter manuellement abeille"?
J'ai l'impression que c'est le check du port qui le relance. Tant que je ne fais pas le check, le daemon reste arrêté.
Dès que je lance le check, il redemarre

**Comment by tcharp38** [comment]
Oui tu as raison. Le check doit le relancer mais au moins au moment du check, si tu l'as arreté manuellement et desactivé la gestion auto, je ne comprends pas quel process pourrait encore utiliser le port.

**Comment by Thiematz** [comment]
Mais le check fonctionne sur la Zigate 2
![image](https://user-images.githubusercontent.com/94549335/194935810-f6e41f47-d979-4750-8c24-194975446170.png)

Mais je ne suis pas d'avoir bien compris "arreter manuellement abeille"
un simple click sur le carré rouge dans la partie daemon ?

**Comment by tcharp38** [comment]
Manuellement c est comme suit
![image](https://user-images.githubusercontent.com/35221038/194937380-e3075005-9e51-4f22-b292-b5e2eef9a914.png)

**Comment by Thiematz** [comment]
ok, donc c'est bien ce que j'ai fait

**Comment by tcharp38** [comment]
Tu as desactivé la gestion auto
arreté le demon
puis testé.. tout de suite ou tu as attendu qq secondes ?

**Comment by Thiematz** [comment]
Les deux, tant que je ne teste pas, le daemon reste arrêté!

**Comment by tcharp38** [comment]
Mais meme apres 10sec arrete, le test dit "toujours occupé" c'est bien ca ?

**Comment by Thiematz** [comment]
Oui, même phénomène après 10sec et après 1min

**Comment by tcharp38** [comment]
Bah zut. Qui occupe ce foutu port du coup si tous les démons Abeille sont arretes ?
Via une console Linux, peux tu verifier qu'aucun process Abeille ne tourne ?

pgrep -a php | grep Abeille

**Comment by Thiematz** [comment]
![image](https://user-images.githubusercontent.com/94549335/194944481-7d276058-a5ae-43ea-aed5-fcf6d96f6751.png)

**Comment by Thiematz** [comment]
Et voici lorsque j'arrête manuellement le daemon

![image](https://user-images.githubusercontent.com/94549335/194944575-24192aa0-dcf3-4846-8a1a-2e3e4d213886.png)

**Comment by tcharp38** [comment]
Donc Abeille est bien arrété. Je pige pas ce qui peut encore occuper le port dans ce cas la.

**Comment by Thiematz** [comment]
Et si le port était effectivement libre mais la PIZigate dans un état "batard" suite à la tentative de maj infructueuse !?

Sais-tu s'il y a moyen de mettre la PiZigate à jour hors Jeedom, via ligne de cde linux ?

**Comment by tcharp38** [comment]
Oui il y a moyen: https://zigate.fr/documentation/parametrer-la-pizigate/?seq_no=2

Mais non le port n'est pas libre. Il est toujours utilisé par apache, comme le dit le message d'err :(

> [2022-10-10 19:35:29] Démarrage de 'checkTTY.sh'
> [2022-10-10 19:35:29] Vérifications du port '/dev/ttyAMA0'
> [2022-10-10 19:35:29] = ERREUR: Le port est utilisé par le process '6841'.
> [2022-10-10 19:35:29] = Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
> [2022-10-10 19:35:29] = Details du process 6841:
> [2022-10-10 19:35:29] = PPid=822, cmd='/usr/sbin/apache2 -k start'

C'est bien ce qui me chagrinne: Quelle est la procedure propre pour que tout soit relaché...

**Comment by tcharp38** [comment]
En discutant avec un collegue, on pense que les choses se deroulent comme suit:
- la demande d'arret d'Abeille doit mal se terminer (le/les process sont tués car pas arretes assez vite)
- apache doit surement gerer les couches basses pour PHP (le langage utilisé par Abeille)
- resultat c 'est apache qui a encore la main sur le port => systemctl stop apache2

Il faut que je bosse l'arret + propre des démons mais tu peux m'aider car je ne reproduis pas le meme souci sur mon OrangePi

**Comment by Thiematz** [comment]
Aucun soucis, je suis dispo pour faire les tests

**Comment by Thiematz** [comment]
Je peux essayer de faire la maj de la PiZigate tout de même ou tu préfères que j'attende ?

**Comment by tcharp38** [comment]
La mise à jour n'a rien à voir avec le souci.
Mais j'arrive à voir des pbs de mon côté. Je vois si je peux améliorer qqch.

Bref tu peux faire la MAJ.
Attention à bien rester en 'legacy', sinon tu devra effacer la PDM et refaire tous les appairages.

**Comment by Thiematz** [comment]
ok, merci!
A ta dispo donc pour les tests

**Comment by tcharp38** [comment]
Pour info dans mes essais je m'appercois que parfois un des demons ne s arrete pas proprement. On doit le tuer.
Ce qui peut expliquer qu'apache (sur lequel repose PHP) continue de squatter le port.
J'essaie de voir comment forcer un arret propre.

**Comment by tcharp38** [comment]
J'ai revu la partie d'arret des démons et je pense avoir amélioré les choses.
Voir la beta 221029-BETA-1 qui sera dispo demain.

**Comment by tcharp38** [comment]
@Thiematz 
Des retours sur ce sujet ?

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

Désolé, j'ai pas pu tester
j'ai pas réussi à reflasher ma PIgate suite au plantage de la maj.
Du coup j'ai commandé une nouvelle clé Zigbee. Dès qu'elle arrive, je testerai.

**Comment by tcharp38** [comment]
Ha oui?
Tu as essayé via Abeille ou via l'outil suggéré par le site Zigate ?

**Comment by Thiematz** [comment]
Abeille ne reconnais plus la PIgate
Je suis en train de monter un autre Raspberry pour essayer de réanimer la carte via l'outil zigate, pas envie de flinguer mon installation ;-).

**Comment by tcharp38** [comment]
Ha donc tu n'arrivais plus à mettre à jour le FW depuis Abeille mais pas forcement depuis l'outil Zigate.
Donc tu devrais pouvoir la reanimer.

**Comment by Thiematz** [comment]
Depuis l'outil Zigate non plus, mais j'ai pas fait 1000 tentatives non plus, trop peur de déstabiliser mon système

**Comment by tcharp38** [comment]
Ha m.. Donc meme avec l' outil zigate. Etrange.

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

J'ai monté mon PiZigate sur un autre PI3.

Je suis toute la procédure, mais quelque chose m'échappe. Lorsque je fait le wget, je récupère un zip vide, alors que via un navigateur, il est consistent.
Du coup la cde unzip plante

J'ai même essayé de créer tous les dossiers/sous dossier un à un, mais lorsque je lance le "make" j'ai une erreur 

Makefile:8: *** séparateur manquant. Arrêt.

J'ai l'impression que la mise en forme du document n'est pas bonne après téléchargement via wget.

sudo apt-get install wget unzip
sudo wget https://github.com/fairecasoimeme/ZiGate/raw/master/Tools/JennicModuleProgrammer_R07.zip
unzip JennicModuleProgrammer_R07.zip
cd JennicModuleProgrammer/
cd Build/
make

Quelqu'un a-t'il déjà rencontré ce genre d'erreur ? Et saurait me dire ce que je fais de faux !

D'avance merci pour vos lumières

**Comment by tcharp38** [comment]
Salut
Si tu as une PiZigate v1, Abeille sait la flasher directement. C'est le seul cas.
Je vais tenter un truc sur ton pacakge

**Comment by tcharp38** [comment]
Bon pas de soucis avec ce package une fois transféré sur mon OrangePi

> root@FelicityDbox: ls
> FlashProgrammerExtension_JN5168.bin  Makefile  version.txt
> root@FelicityDbox: make
> cc  -I. -Wall -O2 -I../Source/ -DDBG_ENABLE -DVERSION="\"56124\"" -c ../Source/uart.c
> cc  -I. -Wall -O2 -I../Source/ -DDBG_ENABLE -DVERSION="\"56124\"" -c ../Source/JN51xx_BootLoader.c
> ../Source/JN51xx_BootLoader.c: In function ‘BL_DownloadExtensionToRamBeforeErase’:
> ../Source/JN51xx_BootLoader.c:1612:98: warning: passing argument 4 of ‘iBL_WriteRAM’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>          if(iBL_WriteRAM(iUartFd,0x04000400 + n, u8ChunkSize, FlashProgrammerExtension_JN5168_bin + n) == -1)
>                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
> ../Source/JN51xx_BootLoader.c:1219:86: note: expected ‘uint8_t *’ {aka ‘unsigned char *’} but argument is of type ‘const unsigned char *’
>  static int iBL_WriteRAM(int iUartFd, uint32_t u32Address, uint8_t u8Length, uint8_t *pu8Buffer)
>                                                                              ~~~~~~~~~^~~~~~~~~
> cc  -I. -Wall -O2 -I../Source/ -DDBG_ENABLE -DVERSION="\"56124\"" -c ../Source/Firmware.c
> cc  -I. -Wall -O2 -I../Source/ -DDBG_ENABLE -DVERSION="\"56124\"" -c ../Source/main.c
> ../Source/main.c: In function ‘main’:
> ../Source/main.c:115:9: warning: variable ‘iVerify’ set but not used [-Wunused-but-set-variable]
>      int iVerify = 0;
>          ^~~~~~~
> cc  uart.o JN51xx_BootLoader.o Firmware.o main.o   -o JennicModuleProgrammer
>

**Comment by Thiematz** [comment]
J'ai bien une V1, mais quelque chose ne veut pas.

18 17:03:15] =           PPid=678, cmd='/usr/sbin/apache2 -k start'
[2022-11-18 17:03:39] Démarrage de 'checkTTY.sh'
[2022-11-18 17:03:39] Vérifications du port '/dev/ttyAMA0'
[2022-11-18 17:03:39] = ERREUR: Le port est utilisé par le process '703'.
[2022-11-18 17:03:39] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
[2022-11-18 17:03:39] =         Details du process 703:
[2022-11-18 17:03:39] =           PPid=678, cmd='/usr/sbin/apache2 -k start'
[2022-11-18 17:03:49] Démarrage de 'checkWiringPi.sh'
[2022-11-18 17:03:49] Vérification de l'installation du package 'WiringPi'
[2022-11-18 17:03:49] = Ok
Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0
Vérifications préliminaires
= Ok
Démarrage de 'updateFirmware.sh' flash /dev/ttyAMA0 ZiGate_v3.21-OPDM.bin
Vérifications préliminaires
= Ok
Lancement de la programmation du firmware
- Port tty: /dev/ttyAMA0
- Firmware: ZiGate_v3.21-OPDM.bin
JennicModuleProgrammer Version: 0.7(r56124)+
**= ERROR: Failed to read chip ID.**
=        Check Zigate GPIO control (flash mode set + reset pulse required) !
= ATTENTION !!!
= Quelque chose s'est mal passé. Veuillez vérifier le log ci-dessus.


vu l'erreur sur le chip ID, j'ai peur que ma PI soit HS. T'en penses quoi ?

**Comment by Thiematz** [comment]
En fait, malgré les cdes suivantes :
$ gpio mode 0 out
$ gpio mode 2 out
$ gpio write 2 1 
$ gpio write 0 0
$ gpio write 0 1

je n'arrive plus à avoir la led bleue qui s'illumine plus fort

**Comment by tcharp38** [comment]
On dirait que qqch d'autre utilise ce port.
Le controle GPIO est inclu dans Abeille pour une PI.

As tu un fichier /boot/config.txt et/ou /boot/cmdline.txt ?
Si oui tu peux zipper et les mettre la ?

**Comment by tcharp38** [comment]
Salut @Thiematz 
Que fait on avec ce sujet ?

**Comment by Thiematz** [comment]
Salut @tcharp38 ,

désolé pour ce long silence, mon travail ne me permet pas toujours d'être actif sur le forum.
J'essaie d'extraire les fichiers demain dans la matinée.

Bonne soirée

**Comment by tcharp38** [comment]
Aucun souci.
Moi j'ai tendance à y passer beaucoup trop de temps.
C'etait juste pour savoir si le sujet devait etre encore ouvert.

**Comment by Thiematz** [comment]
[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/10677443/Downloads.zip)
Salut @tcharp38 ,
J'aimerai bien pouvoir y passer un peu plus de temps ;-) surtout vu la réactivité autour du plugin Abeille, ça fait plaisir.
voici les fichiers demandés
En espérant y voir plus clair
A+

**Comment by tcharp38** [comment]
Désolé mais je vais te demander d'autres infos.
J'ai l'impression que ton port choisi pour la Zigate est en conflit avec une utilisation du kernel.

Via la page de Jeedom .. Reglages/Systeme/configuration
puis _OS/DB
et Administration systeme

peux tu me donner les sorties de
- dmesg
- lsusb
- et eventullement ls -al /dev/ttyUSB*

**Comment by Thiematz** [comment]
Voilà les fichiers de chaque commande
[ls_la _dev_ttyUSB.txt](https://github.com/KiwiHC16/Abeille/files/10696296/ls_la._dev_ttyUSB.txt)
[lsusb.txt](https://github.com/KiwiHC16/Abeille/files/10696298/lsusb.txt)
[dmesg.txt](https://github.com/KiwiHC16/Abeille/files/10696299/dmesg.txt)

**Comment by tcharp38** [comment]
J'essaie de résumer la situation mais corrige moi si je fais erreur

- RPI3
- Zigate type PI => Si RPI3 le port est bien ttyAMA0

Si RPI3, il te faut les lignes suivantes dans **/boot/config.txt** et la premiere semble manquer

> dtoverlay=pi3-disable-bt
>   enable_uart=1

Enfin le site Zigate recommande d 'executer

> $ sudo systemctl disable hciuart
> $ sudo usermod -aG gpio pi
> $ sudo reboot

Voir: 
- https://zigate.fr/documentation/tester-sa-pizigate/?seq_no=2
- Compatibilité RPI3 https://zigate.fr/documentation/compatibilite-raspberry-pi-3-et-zero-w/

**Comment by Thiematz** [comment]
Salut @tcharp38,

super, j'ai réussi à flasher la PI. J'avais déjà suivi cette procédure, mais j'ai dû faire une c**** avec le ficher config.txt car effectivement il manquait la ligne "dtoxxx"
Merci beaucoup pour ton aide ;-)
Je clôture !
