### ISSUE TITLE
Ajout support _ Double wall switch Aqara avec neutre (id = switch.n2aeu1, LUMI)

### ISSUE THREAD

**Issue by koolg63** [KiwiHC16/Abeille#2474]
Bonjour, 

Je n'arrive pas à configurer cet interrupteur. 
Je suis encore nouveau sur jeedom.
Je comprend qu'il manque l'intégration de l'équipement au plugin Abeille.

je joint ici le discovery.
[discovery_n2aeu1.zip](https://github.com/KiwiHC16/Abeille/files/9815465/discovery_n2aeu1.zip)

Si une bonne âme passe par là :)

**Comment by koolg63** [comment]
Avant d'utiliser Abeille j’étais parti sur le plugin Zigate mais l'intégration Profalux est bien meilleur ici.
Je ne sais pas si cela peux aider mais il est peut-être possible de récupérer des informations pour cet interrupteur au niveau du plugin ZiGate car l'intégration de l'intéupteur était de mémoire parfaite sur le plugin ZiGate.

Autre question peut-être bête : Pouvez-vous me confirmer qu'il n'est pas possible d'utiliser 2 plugin différents raccordés tous deux à la zigate ? Dans le cas contraire, une manipulation particulière est à faire afin d'utiliser Zigate et Abeille en même temps ?

**Comment by koolg63** [comment]
Mon interrupteur semble assez proche de celui-ci : https://kiwihc16.github.io/AbeilleDoc//devices/Equipements.html#wall-switch-2

**Comment by tcharp38** [comment]
Salut @koolg63 
Non, 2 plugins ne peuvent pas gerer la meme clef (le meme dongle Zigbee). Donc il faut choisir entre le plugin officiel, le plugin Zigate, et Abeille.

Quand tu as généré ton discovery, tout était passé au vert ?

Autre point: saurais tu résumer tout ce qu'il sait faire ou ce qu'il faut supporter ?

**Comment by tcharp38** [comment]
[switch.n2aeu1_LUMI.zip](https://github.com/KiwiHC16/Abeille/files/9824113/switch.n2aeu1_LUMI.zip)
Pour test

A decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion

**Comment by koolg63** [comment]
> Salut @koolg63 Non, 2 plugins ne peuvent pas gerer la meme clef (le meme dongle Zigbee). Donc il faut choisir entre le plugin officiel, le plugin Zigate, et Abeille.
> 
> Quand tu as généré ton discovery, tout était passé au vert ?
> 
> Autre point: saurais tu résumer tout ce qu'il sait faire ou ce qu'il faut supporter ?

Effectivement, dans mon souvenir (plusieurs mois sont passés), avoir activé Zigate et Abeille en même temps ça avait fait des chocapics.

Aïe, malheureusement, j'ai réussi à avoir une fois la découverte toute verte sapin mais je n'avais pas encore lu la partie de la doc où il est indiqué qu'il faut à ce moment récupérer le fichier discovery.
Celui que j'ai joint est d'une découverte rachitique.

C'est un simple bouton poussoir double avec un témoin lumineux par bouton pour savoir si la lampe éclaire ou non. 
Il n'y a pas d'autres fonctions particulières selon moi.

Il y a marqué sur la boite : "Electricity Consumption Calculation" mais c'est peut-être bien uniquement via la passerelle Aqara Hub.

La fiche produit : https://www.domadoo.fr/fr/peripheriques/5729-aqara-interrupteur-mural-double-intelligent-h1-zigbee-30-avec-neutre-ws-euk04-6970504214804.html

**Comment by koolg63** [comment]
> Aïe, malheureusement, j'ai réussi à avoir une fois la découverte toute verte sapin mais je n'avais pas encore lu la partie de la doc où il est indiqué qu'il faut à ce moment récupérer le fichier discovery. Celui que j'ai joint est d'une découverte rachitique.

Et je n'arrive pas à avoir une bonne découverte de nouveau

**Comment by koolg63** [comment]
> [switch.n2aeu1_LUMI.zip](https://github.com/KiwiHC16/Abeille/files/9824113/switch.n2aeu1_LUMI.zip) Pour test
> 
> A decompresser dans core/config/devices redemarrer Abeille refaire inclusion

Du génie tcharp !!

Ca fonctionne à la perfection 💯 

(J'ai un gros doute sur la valeur de l'encadré "Active Power" mais je vais faire ma mesure pour confirmer ou non la valeur. (une ampoule LED assez classique affichée 94W...)

**Comment by tcharp38** [comment]
Peux tu donner un snapshot de l équipement sur le dashboard ?

Cote assistant, tu me montres aussi ce que ca donne ?

Enfin côte power, c'est bien possible qu'il faille mettre une div par 10 peut etre.

**Comment by koolg63** [comment]
Voici la capture : 
![Screenshot_2022-10-20-10-27-11-135](https://user-images.githubusercontent.com/55705100/197009645-a2313702-74bb-4141-a596-fd121d727622.jpg)

Que veux-tu dire par assistant ?

**Comment by tcharp38** [comment]
Merci pour le snapshot, ca me va.

Tu es d'accord que pour Active Power ca devrait etre divisié par 10 ?

L'assistant de découverte est accessible via la page EQ/avancé: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#assistant-de-decouverte-zigbee
C'est lui qui doit avoir tous les boutons au vert, au moins essayer.

**Comment by koolg63** [comment]
Salut,

Je confirme le facteur de 10 pour la puissance instantanée.

Je n'obtiens rien avec l'assistant de découverte : 
![Screenshot 2022-10-22 at 20-19-31 AbeilleEqAssist - Jeedom Delta](https://user-images.githubusercontent.com/55705100/197356646-2542195f-b0d9-4261-b4af-8373f6ffc470.png)
Même avec les boutons de rafraichissement.

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices/switch.n2aeu1_LUMI
[switch.n2aeu1_LUMI.json.zip](https://github.com/KiwiHC16/Abeille/files/9858979/switch.n2aeu1_LUMI.json.zip)

puis page EQ/avancé => reinitialiser

Le facteur 10 doit etre la.

File moi un package de logs STP au passage

**Comment by koolg63** [comment]
Merci c'est parfait.

Est-ce ce package que tu veux ?

[AbeilleLogs-221104.tar.gz](https://github.com/KiwiHC16/Abeille/files/9941280/AbeilleLogs-221104.tar.gz)

**Comment by tcharp38** [comment]
Oui c'est bien le package.
Par contre je vois des trucs qui me font peur.

Tu as une zigate v2 type USB

Mais avec un FW 0105-031E ??

Ton plugin Abeille semble bien trop vieux.
STP bascule sur la derniere beta.
Assures toi d etre en mode debug pour les logs aussi.

**Comment by koolg63** [comment]
Salut,

Premièrement, la zigate et le jeedom ont été monté il y a de nombreux mois. 

Si je suis bien les dates de releases, alors il n'existait pas d'autres versions quand j'ai reçu puis installé ma zigate : https://github.com/fairecasoimeme/ZiGatev2/releases

Je vais malgré tout lancer son upgrade via cette page : https://zigate.fr/documentation/mise-a-jour-de-la-zigate-2/

Ensuite, sur les maj jeedom et plugin, je les lance de temps en temps quand les notifications m'y invitant apparaissent.
Je ne me précipite pas. Ma dernière version de Abeille étant du 17/09 de cette année, je ne me rend peut-être pas bien compte, mais je ne mesure donc pas l'urgence de la mise à jour :-) .

**Comment by koolg63** [comment]
Resalut,

J'ai pu correctement mettre à jour ma zigate en v3.21.
Merci de ta vigilance.

**Comment by tcharp38** [comment]
Ok du coup on en est ou pour ton sujet initial ?

**Comment by koolg63** [comment]
Comme je disais un peu plus tôt. Tout est nickel pour l'inclusion et l'utilisation de ces interrupteurs.
