### ISSUE TITLE
SOS ma zigate ou abeille ne semble plus fonctionner

### ISSUE THREAD

**Issue by Seby9576** [KiwiHC16/Abeille#2475]
[AbeilleLogs-221019.tar.gz](https://github.com/KiwiHC16/Abeille/files/9823274/AbeilleLogs-221019.tar.gz)
Bonjour,

Gros soucis plus rien semble fonctionner alors que les demons et la zigate sont ok. la plus part de mes equipements sont des volets profalux et un seul fonctionne sur 14.

Quand je fais une inclusion les autres volets font bien un va et vient

![image](https://user-images.githubusercontent.com/77990298/196775826-85d55a4e-0a65-4b4a-b6ad-aee28ae940f6.png)

**Comment by Seby9576** [comment]
Parfois ca fonctionne avec une très grosse latence

**Comment by tcharp38** [comment]
Que s'est il passé avant que tu tombes dans cet etat ?
Tu avais pourtant une config stable non ? Je me trompe ?

En fait il y a tres peu de retours des periphs, surtout 8B6A donc "Volet Salle de jeux 3".
Les autres ne repondent pas. Pas d'acquittement et beaucoup d erreurs remontées par la zigate.
Le log parser etant tres court, je ne vois rien d'autre.

Changement quelconque Wifi ? Autre perturbations ?

**Comment by Seby9576** [comment]
Effectivement rien de spécial,  j'ai installé jeemate c'est tout. 
Quand je collecte le réseau seul le volet 2 cuisine ressort mais quand je fais une inclusion mes volets bougent bien.

**Comment by Seby9576** [comment]
Ça semble refonctionner ce matin, je me connecte quand j'arrive à mon taff pour voir si tout est rentré dans l'ordre

**Comment by Seby9576** [comment]
[AbeilleLogs-221020.tar.gz](https://github.com/KiwiHC16/Abeille/files/9826573/AbeilleLogs-221020.tar.gz)
je confirme c'est revenu, le seul truc que j'ai fait c'est débrancher et rebrancher la zigate ce matin. Est ce qu'elle etait mal mise vu qu'hier j'ai bougé mes branchement dans la baie informatique! Je ne vois que ca mais c'est bizarre

**Comment by tcharp38** [comment]
Tant mieux. Néanmoins il y a un certain nombre d erreurs de la Zigate 

> [2022-10-20 07:15:57] Abeille1, Type=9999/Extended error, ExtStatus=87

Si je comprends bien ca veut dire qu'elle est saturée.
A un moment donné il faudra envisager de
- migrer en version OPDM (3.21-OPDM => 0004-0321)
- effacer la PDM
- et refaire tous les appairages
Je crois qu'elle est dans un état assez instable et sauf erreur, tu ne dois pas pouvoir ajouter quoi que ce soit.

**Comment by Seby9576** [comment]
Oui je peux plus rien faire, c'est prévu mais il me faut du temps pour faire tout ça. L'inclusion ça va encore c'est tout le reste qui prend un temps fou ( virtuel, scenario, résumé, etc)

Il faut que je trouve une procédure pour ne pas faire d'erreur

**Comment by tcharp38** [comment]
On est en ligne alors.
Je ne sais pas ce qu'offrent les autres solutions mais pour moi il n'y a pas photo, c 'est un gros point faible de la zigate.

**Comment by Seby9576** [comment]
Est ce lié à la zigate je ne pense pas. Jeedom devrait garder en mémoire les identifiants et les rétribuer dans des cas comme ca

**Comment by Seby9576** [comment]
Bon ca recommence ce soir alors que pour le coup j'ai rien touché. Comme ce matin je l'ai débranché et rebranché et c'est reparti.

[AbeilleLogs-221020.tar.gz](https://github.com/KiwiHC16/Abeille/files/9833500/AbeilleLogs-221020.tar.gz)

mais cette fois c'est la popp et plugin zigbee qui font pareil . idem debranchement rebranchement en marche de la clé et ca refonctionne. Je pense que du coup le pb est pas lié à la clé

**Comment by tcharp38** [comment]
Ha oui si tu as un merdier sur une autre clef en meme temps, ca sent la perturbation elec ou radiofrequence.

Dans tes logs il semble y avoir + de remontées mais toujours autant d erreurs 87 (There are no free entries in the extended address table). 
Mais je seche.

Quel genre d'info as tu avec le plugin officiel + popp
 ?

**Comment by Minisnaky** [comment]
J'ai aussi les même erreurs sur ma clé Zigate depuis le passage en 3.23 lagacy. Tu es en quel firmware ?

**Comment by Seby9576** [comment]
Je pense que c'est également depuis la maj que j'ai ce pb là mais difficile  d'être certain. Il me semble que c'est cette version également

**Comment by tcharp38** [comment]
Maj de ?

**Comment by Seby9576** [comment]
Du firmware de la zigate

**Comment by tcharp38** [comment]
Les derniers logs que tu m'as donné montrent un FW Appli=0003, SDK=0321 donc 3.21 LEGACY et non pas 3.23.

Et tu disais que ca merdait aussi sur les autres clefs.
Donc j'ai l'impression qu'on melange tout dans ce sujet non ?

**Comment by tcharp38** [comment]
@Seby9576 
On en est ou ?

**Comment by Seby9576** [comment]
Pas trop de soucis a par des volets qui se ferment pas toujours mais je vais refaire un raz et la maj pour repartir sur une base propre.

Ets ce que je peux suivre à la lettre ce tuto : https://zigate.fr/documentation/mise-a-jour-de-la-zigate/

Je dois faire la maj avec le 3.23 OPDM ?

**Comment by tcharp38** [comment]
Ok pour le tuto pour la version USB v1 (celle que tu as n'est ce pas ?).

J'utilise la 3.23-OPDM depuis peu. Rien à dire jusque la mais tu peux tu contenter de la 3.22-OPDM pour l'instant.

Dans tous les cas prends bien une OPDM, donc erase COMPLETE (EEPROM comprise) + reappairage complet.
N efface aucun equipement cote Jeedom. Ca facilite la reconstruction du reseau.

Et on refait le point ensuite.

**Comment by Seby9576** [comment]
Maj faite, je vais commencer les inclusions
![image](https://user-images.githubusercontent.com/77990298/198961417-7c689807-7d27-4d71-b050-be3eb8a33db0.png)

**Comment by Seby9576** [comment]
Première merde, si je lance l'inclusion j'ai le message qui apparait 1 seconde puis la page semble se rafraichir et plus rien. 
[AbeilleLogs-221031.tar.gz](https://github.com/KiwiHC16/Abeille/files/9899353/AbeilleLogs-221031.tar.gz)

L'inclusion semble quand même se faire mais sans message, j'ai fait le test avec mon volet cuisine 1 et il est bien dans le réseau mais j'ai peu de commande. Si je comprends bien le type n'est pas reconnu comme un volet profalux
![image](https://user-images.githubusercontent.com/77990298/198965279-1d7e1052-da1e-42b0-8b3d-2cdbce36cecf.png)

![image](https://user-images.githubusercontent.com/77990298/198964844-df39cccf-a933-4091-b3e4-0040de86a5a4.png)

**Comment by tcharp38** [comment]
Oui il n'a pas été identifié.
Ca se fait normalement avec le nom "volet" dans sa "localisation". C'est tordu mais c'est comme ca pour les premiers volets Profalux.
Ne l'as tu pas modifié avec Zoé par ex ?

Je ne vois pas l'inclusion dans les logs. Pas d'annonce du device.

**Comment by Seby9576** [comment]
Possible à l'époque mais j'ai plus la zoé. Désolé j'ai effacé les logs. Que dois-je faire du coup ?

Merci

**Comment by tcharp38** [comment]
Si tu veux celui la tout de suite, il faut refaire une inclusion et me donner les logs dans la foulée que je vois comment il s'annonce.

Mais peut etre vaut il mieux avancer avec un autre d'abord non ?

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9900187/AbeilleLogs-221031.1.tar.gz)
Je viens de faire celui de mon bureau, évidemment même soucis. Ca me parle ce soucis mais je sais plus ou on a déjà évoqué le sujet

**Comment by Seby9576** [comment]
Retrouvé, il fallait reset le volet à l'époque
![image](https://user-images.githubusercontent.com/77990298/198988832-897a1166-0f10-49f7-98ba-2046f1ee54a7.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/9900369/AbeilleLogs-221031.2.tar.gz)
Reset du volet bureau et reinclusion mais il semble que c'est toujours pareil. Faudrait-il le supprimer de jeedom du coup ?

**Comment by tcharp38** [comment]
Voila c'est bien ca. Tes volets ne s'appellent plus 'volet'.

> [2022-10-31 11:19:09]   LocationDescription='Bureau         ', trimmed='Bureau'

Tu avais du changer ce nom, surement via Zoe.
Abeille aujourd hui, comme d'autres, ne sait pas reconnaitre ces vieux volets (qui ne s'identifient pas suivant le standard Zigbee). Du coup.. il faudrait les renommer.

On peut essayer un truc:
Sur chacun de tes volets, donc non reconnus, via la page EQ/avancé, tu les renommes en "volet"

![image](https://user-images.githubusercontent.com/35221038/198992561-9ead8afe-9056-40ad-ba57-bdc8d47d9ac5.png)

Pour etre sur que c'est bon tu refais une lecture de l'attribut apres coup
![image](https://user-images.githubusercontent.com/35221038/198992871-a3dfbd1d-7d16-4042-966b-df0d77462b93.png)

et tu me files les logs
Si tout se passe bien la nouvelle inclusion devrait etre ok

**Comment by Seby9576** [comment]
Oui c'est bien ca mais le reset aurait du tout effacer. Je mets volet ou dans cette ligne stp
![image](https://user-images.githubusercontent.com/77990298/198995341-f38493e5-6fe9-48a9-8d20-b18580c1cc14.png)

**Comment by tcharp38** [comment]
oui tente ca + relecture.
Ca devrait fonctionner et file moi les logs pour confirmer

**Comment by Seby9576** [comment]
Désolé mais je demandais ou modifier ? dans quelle case stp ? Je ne veux pas faire d'erreur

**Comment by tcharp38** [comment]
Ha pardon.

![image](https://user-images.githubusercontent.com/35221038/199003307-62929ffd-5aa9-431d-be8a-b7b5c7a2339a.png)

Tu dois aussi avoir End Point = 01 et cluster 0000/Basic

**Comment by Seby9576** [comment]
Pour l'instant j'ai ca et j'ai fait ce que tu as dit mais je fais lire il ne se passe rien

![image](https://user-images.githubusercontent.com/77990298/199006360-081f457c-b94c-4e11-b94e-328f935ca355.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/9901116/AbeilleLogs-221031.3.tar.gz)

**Comment by tcharp38** [comment]
Oui je vois une erreur. Il faut ajouter le type de l'attribut: "42"

![image](https://user-images.githubusercontent.com/35221038/199015521-f2b2f6d1-1596-46c3-b395-30e17eaa8ff5.png)

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (4).tar.gz](https://github.com/KiwiHC16/Abeille/files/9901320/AbeilleLogs-221031.4.tar.gz)
J'ai eu un message invalid mais j'ai pas eu le temps de tout noter

Caa ne semble pas avoir focntionné car quand je fais lire il ne ce passe rient

**Comment by tcharp38** [comment]
Je découvre des bugs au fur et à mesure de ces tests... vu que c'est du jamais fait.
"Volet bureau" semble ok.
Tu retentes l'inclusion de celui la ?

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (5).tar.gz](https://github.com/KiwiHC16/Abeille/files/9901455/AbeilleLogs-221031.5.tar.gz)
Je ne vois pas d'amélioration, je viens de faire son inclusion.

Pourquoi le reset moteur n'a rien donné ? C'est parcerque je ne l'ai pas supprimé de jeedom ?

**Comment by Seby9576** [comment]
[AbeilleLogs-221031 (6).tar.gz](https://github.com/KiwiHC16/Abeille/files/9901546/AbeilleLogs-221031.6.tar.gz)
j'ai supprimé le volet de jeedom puis j'ai du faire 2 inclusions et cette fois le volet est nickel

**Comment by tcharp38** [comment]
Cool.
Tu voudrais pas basculer sur la beta, comme ca je te file les dernieres corrections en temps reel ?

**Comment by Seby9576** [comment]
Je viens de lancer la maj de la dernière BETA.
Il faut faire absolument dans cette l'ordre :

-Reset telecommande (5xR). attendre la fin
-Reset moteur perso je fais toucher le fils noir avec la phase 5 secondes
-Appuyer sur stop télécommande pour connecter la télécommande au moteur
- Mode inclusion puis R+haut et normalement le volet se met a jours même si il n'y a pas de message
- 2 va et vient et c'est ok

En faisant comme ça on ne perd pas les viruels, scenario,resumés,widgets etc.

**Comment by Seby9576** [comment]
Par contre j'ai perdu un de mes volets quand j'avais presque terminé mais je sais pas pourquoi. Je du le sortir du réseau et le réinclure.

**Comment by Seby9576** [comment]
[AbeilleLogs-221101.tar.gz](https://github.com/KiwiHC16/Abeille/files/9908654/AbeilleLogs-221101.tar.gz)
Dernier log pour savoir si tout va bien.

**Comment by tcharp38** [comment]
Comme ca je ne vois rien d'anormal.
Tu as des soucis quelconques ? Quel est le status ?

**Comment by Seby9576** [comment]
Je pense qu'on peut clôturer ce sujet. Je trouve que le réseau semble meilleur et plus réactif.

Seul ombre au tableau un volet ne s'est pas ouvert ce matin avec mon scénario. Ca arrivait déja avant mais je ne sais pas pourquoi, mon scenario commande un virtuel avec un groupe de volet et ce matin j'ai commandé ce virtuel et le volet c'est bien ouvert. Bref pb déja connu d'avant.

**Comment by tcharp38** [comment]
Ok je ferme.
Mais pour ton pb de violet c'est marrant j'ai ça de temps en temps. Si jamais tu reproduis et que tu as les logs qui correspondent, ouvre un sujet et met tout dedans. Mais il me faut vraiment les logs autour de l'instant en défaut.

**Comment by Seby9576** [comment]
[AbeilleLogs-221102.tar.gz](https://github.com/KiwiHC16/Abeille/files/9917798/AbeilleLogs-221102.tar.gz)
Salut, 

Désolé mais le pb à recommencé, plus de réseau mais zigate ok.

Redémarrage jeedom -> NOK
Pour que ca refonctionne, changement du port de la clé dans le paramétrage puis j'ai remis le bon port et la ca refonctionne

**Comment by tcharp38** [comment]
Le pb est arrivé à quelle heure ?

**Comment by Seby9576** [comment]
Je sais pas exactement, à 8h43 mes volets sud aurait du s'ouvrir, 1 seul à pu le faire donc je suppose que ca a du déconner à ce moment là.

**Comment by tcharp38** [comment]
Dommage je n'ai pas les traces à cette heure. Tu as du redemarrer ton RPI et du coup ca efface les fichier "-prev" (previous).

J'observe ca
- 08:48:26 => tu as du faire un test de port
- 08:48:33 => Abeille restart ? => la par contre la Zigate est dans un sale etat. Beaucoup d 'erreurs que je ne comprends pas.
- 08:49:58 => Un autre restart
- 08:55:03 => encore un.. je crois que c'est le dernier et la plus d erreurs.

En ligne avec ca ?

**Comment by Seby9576** [comment]
Oui j'ai fait un test de port pour voir si il y avait un soucis mais le test indiquait ok alors que rien ne fonctionnait. J'ai dit 8h43 mais c'est peut être 7h43, j'ai regardé l'heure de mon scenario. Désolé pas facile de savoir

**Comment by tcharp38** [comment]
Pas de traces du cas avant.
Si ca recommence pense à mettre le package de logs de cote tout de suite avant toute manip.

**Comment by Seby9576** [comment]
Ok je ferais ca.

Ce que je remarque pour que ca refonctionne c'est que je dois débrancher et rebrancher la zigate ou changer de port et remettre le bon.
Pour info j'ai un hub alimenté ou j'ai deux clé dessus (zigate et aeotec zwave)

**Comment by tcharp38** [comment]
Je vais forcer un "soft reset" à chaque redemarrage. On verra si ca améliore les choses.

**Comment by Seby9576** [comment]
C'est à dire ?

**Comment by tcharp38** [comment]
J'ajoute une commande dans Abeille au demarrage.
Ca ne peut que rendre les choses + propres.

**Comment by Seby9576** [comment]
[AbeilleLogs-221103.tar.gz](https://github.com/KiwiHC16/Abeille/files/9928019/AbeilleLogs-221103.tar.gz)
J'ai encore perdu mon réseau. Certains volets des chambres sont ouverts mais pas d'autre donc plantage surement vers 11h

**Comment by tcharp38** [comment]
Il y a des erreurs qui apparaissent depuis 10;46 ce matin.
Ca te dit qqch ?

[2022-11-03 10:46:38] Abeille1, Type=9999/Extended error, ExtStatus=80

Du coup peux tu faire un reset SW via la page EQ/avancé de la zigate pour voir ce que ca dit ?

**Comment by Seby9576** [comment]
[AbeilleLogs-221104.tar.gz](https://github.com/KiwiHC16/Abeille/files/9940308/AbeilleLogs-221104.tar.gz)
Désolé j'avais redémarré avant, je le ferais la prochaine fois. J'ai eu encore un soucis aujourd'hui.

Pi j'avais désactivé le redémarrage des démons automatiquement. J'ai relancé les démons et ça semble refonctionner. Bizarre c'est pire qu'avant RAZ et la maj de la zigate.

**Comment by tcharp38** [comment]
Je ne sais pas ou tu en es mais un redemarrage manuel peut changer cet état.
Mais je creuse pour comprendre comment ca a pu se produire.

**Comment by Seby9576** [comment]
Salut,
Pour l'instant pas de plantage depuis. Si ça recommence j'appliquerais le reset sw.
Pi : le redémarrage de jeedom ne sert à rien

**Comment by Seby9576** [comment]
Salut,
De nouveau un plantage (surement vers 17h55 car j'ai un volet qui s'est fermé mais pas le reste) et le reset sw a fonctionné
[AbeilleLogs-221108 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9963600/AbeilleLogs-221108.1.tar.gz)

**Comment by tcharp38** [comment]
Oui je vois ca. On dirait que le reset SW a fait du ménage.
Super piste en tout cas.
Il faudrait que je trouve comment declencher un soft reset automatiquement dans ce genre de cas.

Mais le souci de base est pourquoi on arrive à ca ?
Je vois que ca fait suite à une annonce de "Poussoir 4 bouto" (Tuya 4 buttons scene switch).
Je soupconne que trop de requetes sont envoyées en meme temps.

J'ai 2 points à creuser la.

**Comment by tcharp38** [comment]
En fait j'aimerais bien creuser l'inclusion de ce device qui s'annonce
- à 14:53:53
- à 15:53:41
- à 16:53:30 et c'est celui la qui entraine une multitude d'erreurs

Je sais pas pourquoi il s'annonce aussi souvent. Mauvaise reception ? Il est isolé et pas de repeteur ?
Il se passe qqch à ces heures ?

Bref j'ai besoin d'un package de logs autour de cet evenement. Dans le dernier par ex AbeilleCmd est trop recent et n'englobe aucune de ces annonces.

**Comment by Seby9576** [comment]
Le bouton 4 poussoirs est un lanceur de scénario donc il ne sert pas tout le temps. 
Trop éloigné c'est possible, est ce qu'un volet lui sert de passerelle ? Sinon effectivement il est pas à côté de la zigate.
Aux heures indiqué il n'a sûrement pas servi
Dis moi si j'ai quelque chose à faire pour aider.

Merci

**Comment by tcharp38** [comment]
Pas sur qu'il accepte de se faire relayer par un volet. Ces devices "pas cher" sont mal finis et ne respectent que partiellement le standard.
Quel LQI as tu sur la page santé ?

Si tu peux me chopper un package de logs qui englobe une annonce de ce truc "device announce", y compris AbeilleCmd, je peux reflechir ce qui peut déclencher ca.

**Comment by Seby9576** [comment]
[AbeilleLogs-221109.tar.gz](https://github.com/KiwiHC16/Abeille/files/9973787/AbeilleLogs-221109.tar.gz)
Je viens de faire une multitude de commande avec le 4 poussoirs proche de la zigate

**Comment by Seby9576** [comment]
[AbeilleLogs-221109 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9973795/AbeilleLogs-221109.1.tar.gz)
Même chose mais cette fois très éloigné

**Comment by Seby9576** [comment]
Le reset sw semble avoir fait du bien puisque j'ai eu aucun soucis avec mes volets aujourd'hui

**Comment by tcharp38** [comment]
Je viens d'implementer un reset SW automatique si la zigate se bloque 3mins.
Je teste un peu avant de pousser une beta.

**Comment by tcharp38** [comment]
Une fois à jour sur la beta 221108-BETA-1, tu peux ecraser AbeilleParser.class.php avec le suivant
(core/class)
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/9981241/AbeilleParser.class.php.zip)

**Comment by Seby9576** [comment]
Ok fait, tu me diras ce que ca doit faire et si tu veux des logs

**Comment by tcharp38** [comment]
C'est inclus dans la beta 221110-BETA-1 de demain.
Un reset SW devrait etre déclenché si tu retombes dans ce cas du coup tu ne devrais plus le voir.

**Comment by tcharp38** [comment]
@Seby9576 
On fait quoi de ce sujet ?

**Comment by Seby9576** [comment]
Je n'ai pas vu de bloquage depuis mais avec ton reset sw si il y en a eu un je n'ai pas du le voir. Si tu veux tu peux cloturer.

Merci

**Comment by tcharp38** [comment]
Ok, on clos le sujet.
A reouvrir si jamais ca revient sur le tapis.
