### ISSUE TITLE
Dernière version Abeille et clé Zigate firmware 3.23

### ISSUE THREAD

**Issue by Minisnaky** [KiwiHC16/Abeille#2479]
J'ai procédé à la mise à jour de mon firmware sur clé Zigate en 3.23 hier, tel que suggéré par Abeille. Mise a jour ok et Erase eeprom complet. J'ai réinjecté mon eeprom après upgrade du firmware et impossible d'inclure de nouveau objets.
J'ai donc refait une maj du firmware et supression eeprom. Test de la clés sur Windows ok. Sur jeedom j'ai reinclu quelques objets. Pas de problème avec les ampoules hue, capteurs et boutons xiaomi  et prises Ikea, mais plus de mal avec les Switch on/off Ikea. Bref. Mon plus gros problème c'est que tous les équipements Xiaomi tombent en timeout et ne fonctionnent plus après une paire d'heure... Je ne comprends pas. Je m'arrache les cheveux. Si jamais vous avez une idée ou piste...?

**Comment by tcharp38** [comment]
Salut.
La 3.23 vient de sortir pour une zigate v1 mais je n'ai pas testé.
Pourquoi as tu effacé l eeprom et quelle version as tu pris (legacy ou opdm)?
Et que veux tu dire par réinjecter l eeprom ?

Dans tous les cas il me faut un package de logs pour tenter d'en tirer qq pistes.

**Comment by Minisnaky** [comment]
Merci pour ton retour. Je suis en legacy. Ma Zigate était en 3.1e et après le 1er flash en 3.23,   rien ne fonctionnait correctement. J'ai donc fait un dump de l'eeprom, puis reflashé la Zigate et Erase eeprom avant de réinjecter mon backup eeprom.
Je récupère mes logs demain et je les poserai ici. 
Merci encore.
Bonne soirée

**Comment by tcharp38** [comment]
Quelle 3.23 as tu choisi ?
Et comment fais tu pour ne flasher que l eeprom ?

**Comment by Minisnaky** [comment]
Bonsoir.

Bon alors, tout d'abord, pour flasher seulement l'eeprom (après l'avoir sauvegardé évidemment oO), j'utilise JN51XX Production Flasher et la commande (à adapter au cas par cas évidemment) : 
.\JN51xxProgrammer.exe -s COM4 -P 115200 -e .\Backup_Zigate_EEprom_00-15-8D-00-01-ED-BE-74.bin

Ensuite, concernant mon problème et son avancée. 
J'ai décidé ce matin de reflasher ma zigate en 3.23 Legacy et faire un erase eeprom complete, sans réinjecter mon eeprom précédent
. Ensuite, j' fait un reset de mes équipements zigbee (d'ailleurs au passage pour info, même ceux qui annonçaient leur départ du réseau avant n'étaient plus notifiés par Abeille). Après ça, pour chaque équipement, j'ai ouvert le mode inclusion sur la clé et inclut les équipements un par un.( Ici idem, sur les 30 équipements traités, seul 2 messages d'Abeille m'indiquant que les équipements s'étaient réannoncés (comportement Nouveau? Normal?). 
Ca a tenu au moins une heure... puis de nouveau, timeout de mes équipements Xiaomi....

J'ai tout repris depuis le début (flash, erase, reset des équipements, réinclusion et blablabla...) MAIS, je n'ai pas inclus le repeter TRADFRI. Depuis, tout semble tenir correctement. Même l'ajout du groupe sur mes télécommandes TRADFRI 5 boutons s'est étrangement fait assez rapidement par rapport à d'habitude (pas plus de 5 essais MAX ^^).

Je vous fais un retour demain, mais si est toujours bon, je jette au rebut le repeter TRADFRI.

Voilou.

Bonne soirée ;)

**Comment by tcharp38** [comment]
Salut.
Ok je comprends ton histoire de "reinjection" mais de toute façon en changeant de version ca me semble dangereux.

Quoi qu'il en soit il est tres dommage que tu n'aies pas choisi la version OPDM. C est celle la qui est recommandée alors quitte à repartir de 0.. Je l'avais indiqué dans la release notes.

De mon coté j'ai basculé sur la 3.23 et jusque la .. pas de soucis pour moi.

Bonne soirée

**Comment by tcharp38** [comment]
Je confirme pas de soucis avec la 3.23 des lors que la programmation est correcte.

@Minisnaky 
Tu as encore des soucis ou on peut clore ce sujet ?

**Comment by Minisnaky** [comment]
Alors...
Suite à ton conseil , et parce que je suis un poil perfectionniste..., je suis reparti à zéro ce matin. Flash de la Zigate en 3.23 OPDM, Erase complète eeprom/pdm, et réinclusion de tous mes équipements.
Pour le moment, j'ai encore des comportements vraiment anormaux (timeouts, lanceur de scénario TRADFRI qui sont bien inclus, sans timeout mais dont l'appuie n'est pas reçu par la Zigate et les logs débug qui sont en 9999 exit 80, ou 83, ou 87....).
J'ai testé la maj du firmware d'un des lanceurs directement sur la passerelle Ikea, et après réinclusion dans abeille, il a retrouvé un comportement normal.
Qu'à cela ne tienne, j'ai lancé la MAJ OTA depuis abeille avec des firmware ota.signed. J'ai bien le message indiquant que l'équipement commence sa mise à jour, mais elle n'aboutie jamais et je n'ai pas de message d'erreur 😔. Idem sur un équipement branché, maj OTA se lance, mais n'aboutie jamais.
Depuis ton test en 3.23, as tu testé une MAJ OTA? Le problème est peut être lié à ce récent firmware de la Zigate...
Bref, faut que je continue à fouiller. Je te tiens au courant et si ça persiste, je t'inonde de logs 😁

**Comment by tcharp38** [comment]
Tu as des erreurs 87 depuis que tu as tout reappairé ?

Pas testé OTA depuis un bail.

Entre temps as tu basculé sur la beta ?
SI oui envoie les logs que je jettes deja un oeil à la situation.

**Comment by Seby9576** [comment]
Je suis sur la 3.23 et sur la dernière BETA, si besoin je suis là pour faire des tests.

C'est quoi la maj OTA ?

**Comment by tcharp38** [comment]
OTA = Over The Air
Autrement dit une facon pour mettre a jour le FW des periphs si le periph le supporte et SI tu trouves une mise-à-jour de FW, ce qui est tres rare pour des devices low cost & mal finis

**Comment by Minisnaky** [comment]
Bonsoir.
Bon. Effectivement, encore des erreurs 87 après la réinclusion des les équipements avec le firmware 3.23 OPDM.
Et des comportements très étranges (inclusions ok mais de suite après les équipements qui ne communiquent plus, uniquement sur du Ikea, on/off switch ou lanceur de scenario...)
Dans le doute, j'ai exclus le repeter TRADFRÏ et l'ai supprimé de jeedom. Après un certain temps (nécessaire pour recréer les routes j'imagine) les équipements ont arrêtes de se mettre en timeout. Pour les récalcitrants, je les ai inclus sur la passerelle Ikea, MAJ firmware et retour sur jeedom. Ça a fonctionné.

En revanche je confirme que les MAJ OTA n'aboutissent pas (testé seulement avec des équipements IKEA, mes Xiaomi et hue sont up to date), que ce soit pour les équipements sur batterie ou secteur. J'ai bien les messages "pop-up" abeille qui annoncent le début de la Maj du firmware, et les traces dans les logs, mais après, plus rien.

Voilou.
En l'état pour moi, c'est pas si pire. Je vais devoir reléguer mon repeter Ikea au placard mais je devrais survivre. Maintenant je vais surveiller la consommation des piles parce que durant toutes mes manipulations, j'ai du en remplacer plus d'un dizaine, dont certaines 2 fois. Comme si elles avaient été drainées.
Bref.

P.S.: non j'ai pas basculé sur la BETA. J'aurai dû ?

**Comment by tcharp38** [comment]
Salut.
Les erreurs 87 me chagrinnent. D'apres le site Zigate ca voudrait dire que c'est plein. Incompréhensible si tu viens de faire un erase PDM + reappairage. A moins que tu aies beaucoup de devices.

Si une mise à jour OTA se relance, je veux bien des logs pour voir ce qui se passe.
Mode debug, package de logs via la page maintenance.

Et oui je prefere faire du support sur la beta, car c 'est le dernier code et je peux reagir rapidement en fonction des soucis eventuels. Mais pas une obligation.

**Comment by tcharp38** [comment]
Salut @Minisnaky 
Tu en es ou sur ce sujet ?

**Comment by Minisnaky** [comment]
Salut. Désolé pour ma latence de réponse!
J'ai plein de comportements étranges, mais le plus embêtant c'est la perte aléatoire des boutons Ikea... Pour qu'ils soient de nouveau OK sous Abeille, je suis obligé d'enlever la pile, attendre 1 ou 2mn, et remettre la pile. Et là, ils sont de nouveau fonctionnels... Mais j'ai laissé tombé l'étude des logs. Comme c'est aléatoire c'est trop chronophage.
J'ai définitivement enlevé le routeur tradfri aussi. Quand il est sur le réseau c'est du grand n'importe quoi.
Les MAJ OTA ne se terminent jamais non plus.

**Comment by tcharp38** [comment]
Salut @Minisnaky 
Désolé de tout tes déboires.
Il faut arriver à traiter les soucis un par un mais les isoler n'est pas forcement facile je le reconnais.
Le routeur Trafri.. ben je viens de decouvrir que le mien etait en timeout. Je pige pas pourquoi.
Ca gave ces equipements de pietre qualité.

Bref.. que souhaites tu faire ?
Tu ouvres un sujet precis sur les boutons par ex?

**Comment by Minisnaky** [comment]
Salut. Oui tu peux fermer le sujet. Quand j'aurais le temps de m'y plonger j'ouvrirai un sujet dédié à chaque soucis. Merci pour tout en tout chef 😊
