### ISSUE TITLE
Xiaomi Presence Aqara 2 problème remonté luminosité (sensor_motion.aq2)

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2481]
Bonjour,

J'ai un problème sur les capteurs "Xiaomi Presence Aqara 2", la luminosité reste à 1.

[AbeilleLogs-221101.tar.gz](https://github.com/KiwiHC16/Abeille/files/9911039/AbeilleLogs-221101.tar.gz)

Merci pour l'aide.

**Comment by tcharp38** [comment]
Salut @toat 
Je vois que tu en as plusieurs. C'est le cas pour tous ? Sinon merci de preciser celui qui deconne.

**Comment by toat** [comment]
salut,

Tous remontent mal l'information.

**Comment by tcharp38** [comment]
Ok je crois que j'ai compris.
Encore un truc foireux à la Xiaomi.. fait semblant de respecter les standard mais en fait non.

**Comment by tcharp38** [comment]
Une fois que tu as basculé sur la beta, dispo demain, 
via la page EQ/avancé => reinitialiser
puis redemarrer Abeille
et me filer les logs

Pour etre + precis sur le cas ici
le cluster 0400, attribut 0000 est la luminance
sur laquelle d apres la spec on doit appliquer une formule pour en extraire la luminance en Lux

Sauf que.. dans ce cas Xiaomi renvoi directement une valeur (en Lux ?) et aucune formule de doit etre appliquée.
Bref j'ai ajouté un attribut 'notStandard' sur cette commande dans le modele, auquel cas il ne devrait pas transformer la valeur reçue

**Comment by toat** [comment]
Ca fonctionne merci.

**Comment by tcharp38** [comment]
Super !
