### ISSUE TITLE
Zigate v1: Equipements inconnus réapparaissent => pb mauvais message 804E

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2483]
Salut,

Je pense que c'est depuis le passage en beta, j'ai des équipements qui apparaissent sans que je fasse quoi que ce soit :
![image](https://user-images.githubusercontent.com/26632961/199657894-e4723dc3-907b-4930-9d0d-a4eb72cd72a0.png)

J'ai fait un suppression que l'ensemble de ces équipements mais ils sont revenu cette nuit.

Merci pour l'aide.

[AbeilleLogs-221103.tar.gz](https://github.com/KiwiHC16/Abeille/files/9926008/AbeilleLogs-221103.tar.gz)

**Comment by tcharp38** [comment]
Salut
C 'est tout à fait possible pour ceux qui sont dans ton réseau mais ne sont pas connus de Jeedom.
Ceci ca en fait beaucoup  la ca m'intrigue.

**Comment by tcharp38** [comment]
Je vois rien. Le moment de leur creation n'est plus dans les logs.

Peux n'en supprimer qu'un, 
puis via Reseaux, tu forces la reinterrogation (j'imagine que la il revient)
et tu me files les logs

**Comment by toat** [comment]
J'ai supprimé l'équipement 563.

Quand tu dis réinterrogation c'est bien ca ?
![image](https://user-images.githubusercontent.com/26632961/199802853-99bc941e-0b98-4cfe-8d8b-c1d16a3e4702.png)

Voila les logs.
[AbeilleLogs-221103(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9931994/AbeilleLogs-221103.1.tar.gz)

**Comment by tcharp38** [comment]
Je vais regarder. Un nouvel équipement est revenu ?

**Comment by toat** [comment]
Non il est pas revenu.

**Comment by toat** [comment]
Je viens de refaire la manip, j'ai le Abeille1-581 qui est revenu.
[AbeilleLogs-221104.tar.gz](https://github.com/KiwiHC16/Abeille/files/9935575/AbeilleLogs-221104.tar.gz)

**Comment by tcharp38** [comment]
Je vois effectivement le device avec IEEE 00158D0004001800 qui est connu du réseau.
J'ai d'abord cru qu'il s'agissait d'une adresse bidon mais à mon avis c'est valide.. Un device d'origine Jennic.. donc peut etre du vieux Xiaomi.

En + cet equipement semble etre sur secteur.

Pas d'idée de qui il peut etre ?

Quoi qu'il en soit je réalise qu'il manque qqch pour le découvrir.
Peux tu cliquer dessus, page avancé/assistant et essayer de découvrir toutes les infos ?

**Comment by toat** [comment]
Un xiaomi sur secteur ca me parle pas...

J'ai fait la découverte :
![image](https://user-images.githubusercontent.com/26632961/199936759-d7d1c817-2e88-432b-a493-470e80a11f0f.png)

[discovery.txt](https://github.com/KiwiHC16/Abeille/files/9936760/discovery.txt)

**Comment by tcharp38** [comment]
Bon donc il repond pas. Le discovery n'a aucun interet dans ce cas.

Apres analyse je pense que la zigate dit n'importe quoi lors de l'interrogation. Elle me gave cette stack de m.. qui la compose.
Bref, je vais entrer un bug chez Zigate et implementer autre chose côté Abeille pour mieux gérer les erreurs.

Mais a noter que tu as des tas d'erreurs 'Abeille1, Type=9999/Extended error, ExtStatus=80'
Je sais pas trop comment interpreter ca.
Peux tu confirmer que tu as ces erreurs dans le log parser actuel, puis faire un SW reset (page EQ/avancé zigate), et voir si ca améliore les choses ?

**Comment by toat** [comment]
Je te confirme que j'ai bien les erreurs dans le log parser.

Je ne comprend trop ce que tu me demande de faire :  SW reset (page EQ/avancé zigate)

![image](https://user-images.githubusercontent.com/26632961/199942151-d07ba046-4217-4318-90eb-ce9d5a983e5a.png)

C'est bien ca ?

**Comment by tcharp38** [comment]
oui c est ca.
Juste pour voir si ca un effet sur ces erreurs

**Comment by toat** [comment]
Erreur toujours présente.

[AbeilleLogs-221104.tar.gz](https://github.com/KiwiHC16/Abeille/files/9937058/AbeilleLogs-221104.tar.gz)

**Comment by tcharp38** [comment]
Oui je vois.
C'est peut etre lié à trop de commandes envoyées à la zigate en meme temps.
Je creuserai + tard.

Je viens d'entrer un bug chez Zigate: https://github.com/fairecasoimeme/ZiGate/issues/407
Je dois maintenant modifier Abeille dans ce sens et reviens vers toi.

**Comment by tcharp38** [comment]
Voila j'ai poussé une beta qui sera dispo demain, pour ce cas la.
221104-BETA-1

Une fois que tu aura basculé sur cette version, supprime tes equipements fantomes, et test.
Un raffraichissement reseau est la meilleure solution.
Et surtout met les logs de coté des que tu vois un souci.

**Comment by toat** [comment]
Ca semble bon, j'ai fait le refresh et il ne réapparait pas. Je te confirme cela dans quelques jours.

Merci.

**Comment by toat** [comment]
L'équipement est revenu...

[AbeilleLogs-221109.tar.gz](https://github.com/KiwiHC16/Abeille/files/9971162/AbeilleLogs-221109.tar.gz)

**Comment by tcharp38** [comment]
Tu peux me dire lequel ?

**Comment by toat** [comment]
Abeille1-583

**Comment by tcharp38** [comment]
Il a reapparu à minuit, lors de l'interrogation reseau :( Avec une adresse IEEE débile (0000000000000000).
Sauf que les logs sont trop recents maintenant.

Tu peux provoquer un refresh reseau et me les filer à nouveau ?

**Comment by toat** [comment]
Voila 
[AbeilleLogs-221109(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/9972359/AbeilleLogs-221109.1.tar.gz)

**Comment by tcharp38** [comment]
Quelle galere.
Cette fois le 967F n'est meme plus dans la liste donc si tu l'avais supprimé il ne serait pas revenu.
Bref il ne revient pas tout le temps :(

Désolé mais pour avancer la balle est encore chez toi.
Il faudrait détruire ce device à nouveau.
Puis relancer des refresh reseau jusqu'a ce qu'il reapparaisse et la mettre les logs de côté.

Il y a des cas ou la zigate fait vraiment n'importe quoi :(

**Comment by tcharp38** [comment]
Salut @toat 
Toujours interessé ?
Je me disais que si l'équipement créé a toujours une adresse IEEE à 0, on peut au moins filtrer ca.
Qu'en dis tu ?

**Comment by toat** [comment]
Salut,

Pour l'instant il est pas revenu. Je fais les MAJ en beta dés que c'est disponible.

Merci pour ton aide.

**Comment by tcharp38** [comment]
ok tiens moi au jus.

**Comment by tcharp38** [comment]
Salut @toat 
Des news sur ce sujet ?

**Comment by toat** [comment]
Salut,

L'équipement remonte encore, avec un autre nom :
![image](https://user-images.githubusercontent.com/26632961/226259881-40050566-eef4-43cb-9f63-2442680e6d8f.png)

Je suis plus en beta par contre...

**Comment by tcharp38** [comment]
Dommage que tu aies abandonné la beta. Elle est de tres loin bien + avancée que la derniere stable.

Bref il faut que je fige cette beta au plus vite.
J'attends encore qq retours et je bascule la beta en stable.

**Comment by tcharp38** [comment]
Salut @toat 
La nouvelle stable est sortie.
As tu basculé dessus ?
Des soucis ?

**Comment by toat** [comment]
Salut,

Je suis repassé en beta suite à ton message d'avant.

J'ai fait pas mal de ménage dans mes équipements ce matin, pour avoir une page de santé un peu plus clean.

Un équipement est remonté en inconnue :

![image](https://user-images.githubusercontent.com/26632961/229347273-c3dfa033-30cf-4500-b017-ca43ca1329bb.png)

[AbeilleLogs-230402.tar.gz](https://github.com/KiwiHC16/Abeille/files/11131818/AbeilleLogs-230402.tar.gz)

Merci pour ton aide.

**Comment by tcharp38** [comment]
Salut
Juste un rappel: la beta est la version la + avancée. TOUJOURS + recent qu'une stable. Donc aucun souci pour rester dessus.
Par contre pour revenir a une stable, ne jamais basculer dessus autrement que par une restauration.

Concernant ton equipement inconnu, pour moi cette fois c'est une vraie adresse. Donc un vrai equipement, sur un chip Jennic.
Je soupconne un device Xiaomi, un vieux truc.
Sauf qu'il n'est pas souvent causant. Donc Abeille n'a pas toutes les infos.

Aucune idée de qui il peut etre ? Cherche cote Xiaomi

**Comment by tcharp38** [comment]
Salut @toat 
Quelle est la situation vis à vis de ce sujet ?
Merci

**Comment by tcharp38** [comment]
Hello.
Pas de news depuis un moment.
Je clos. A reouvrir si besoin
