### ISSUE TITLE
MOES - Thermostat BHT-002-GCLZBW Zigbee

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2485]
Bonjour @tcharp38,
Le retour, pour un nouveau challenges ;)
Je viens d'installer un [thermostat MOES BHT-002](https://www.domadoo.fr/fr/thermostats/5781-moes-thermostat-intelligent-zigbee-blanc-pour-chaudiere-eaugaz-3a.html)
Inclusion OK, reconnu comme TUYA TS0601_TZE200_aoclfnxz, comme indiqué sur différent forum.
Voici le résultat ?

![2022-11-04_112107](https://user-images.githubusercontent.com/104787819/199953781-c3310e1d-b937-428d-b41b-b85013609b22.jpg)

Je te joins les logs:
[AbeilleLogs-221104.tar.gz](https://github.com/KiwiHC16/Abeille/files/9937389/AbeilleLogs-221104.tar.gz)

Voici l'image PNG sans arrière plan.
![MOES - Thermostat BHT-002](https://user-images.githubusercontent.com/104787819/199956892-8bd96d5a-2656-47c1-a936-62ed01ffb375.png)

Merci pour ton aide.
Bonne journée
:)

**Comment by tcharp38** [comment]
Salut
J'ai besoin que tu me generes le discovery via l'assistant
https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

Merci

**Comment by Jeedom122** [comment]
Pour info il devrait avoir ceux-ci comme commande:
- Température avec + et -
- Marche/arrêt
- Mode Manuel
- Mode Programme
Il y en a d'autres (mes gadget ;))

Voici le précieux
 [discovery.zip](https://github.com/KiwiHC16/Abeille/files/9939349/discovery.zip)

Merci !

**Comment by tcharp38** [comment]
Encore du Tuya hors standard :(
Ca va pas être du direct.

Mode programme n'a pas d'interet vu que dans ce contexte c'est Jeedom et ses scenaris qui pilote.

**Comment by tcharp38** [comment]
Pour être clair, il faut trouver
- les "DataPoints" Tuya interessants
- et comment les interpreter

**Comment by Jeedom122** [comment]
En fait, je vais utiliser la programmation du thermostat, et lorsque je voudrais intervenir manuellement sur la température, il faut pouvoir le désactiver.
Est-ce que ceux-ci peut intéresser ?
[Moes.Zigbee.Thermostat.txt](https://github.com/KiwiHC16/Abeille/files/9940247/Moes.Zigbee.Thermostat.txt)

**Comment by tcharp38** [comment]
Hello
Désolé pour le silence.
Assure toi d etre sur la derniere BETA.

A decompresser dans core/config/devices
[TS0601__TZE200_aoclfnxz.zip](https://github.com/KiwiHC16/Abeille/files/10093445/TS0601__TZE200_aoclfnxz.zip)

redemarrer Abeille
refaire inclusion
tester
et m'envoyer les logs

C'est incomplet. C'est juste un premier jet

**Comment by Jeedom122** [comment]
Salut @tcharp38 ,
Pas de soucis, j'ai eu un problème avec le thermostat HS, retour fournisseur, rupture de stock, 2 à 3 semaines pour l'échange.
Je te tien au courant.
Merci !
A++

**Comment by tcharp38** [comment]
Salut
Ok j'attends de tes nouvelles alors.

Entre temps n'hesite pas a suivre les dernieres beta pour faire un retour si tu vois une regression.

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
De nouveau opérationnel ;)
Voici le retour des tests.
- J'ai un message d'erreur à chaque inclusion " ERREUR: Abeille1, Message corrompu (taille payload incorrecte, taille=23B, att=512B)" 
- Une capture d'écran des fonctions
![plugin Abeille](https://user-images.githubusercontent.com/104787819/208633620-2f2eef9c-8c8c-4c20-8937-e1aa41d62296.jpg)
Une erreur d'affichage sur la température.
- je te joins les logs
[AbeilleLogs-221220.tar.gz](https://github.com/KiwiHC16/Abeille/files/10267174/AbeilleLogs-221220.tar.gz)
J'ai testé le plugin Zigbee Jeedom,
voici les fonctions
![plugin Zigbee Jeedom](https://user-images.githubusercontent.com/104787819/208634229-a6ef7129-fd94-431f-9cf1-5de570996565.jpg)

En fait il ne reste que la possibilité de régler la consigne, et bloquer/débloquer l'écran (gadget pour moi)

Et d'après MOES il y a une synchro de l'heure avec la passerelle Tuya (peut-être compliqué)

Encore merci pour tout,

Et voilou...
Bonne journée :)

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,

Décidément pas de chance, le nouveau thermostat a aussi un problème, donc retour fournisseur, cette fois pour avoir.

Désolé, pour le temps que tu as passé, j'espère que cela servira à d'autres.

Une info, j'avais tous les jours une création d'un objet Abeille ?
Depuis que j'ai supprimé le thermostat, plus ce problème.


![2022-12-21_115715](https://user-images.githubusercontent.com/104787819/209089693-5421815d-d359-4a53-85a0-80974881d1b8.jpg)

STP, j'ai une question, j'ai une sonde température SONOF dont la valeur n'est pas correct (+ 1,5°) je n'arrive pas à saisir la bonne formule pour le rectifier manuellement.
Merci pour ton aide.

Passe de bonnes fêtes de fin d'année.

**Comment by Jeedom122** [comment]
Salut @tcharp38,
Il y a toujours des créations d'objets intempestifs dans Abeille ?
![2022-12-29_115257](https://user-images.githubusercontent.com/104787819/209941610-b91a81ee-cf7c-46c9-8a9f-922d139f8a0b.jpg)
Et pour la sonde de température SONOFF, les modifications apportées ne change pas la valeur ?
![2022-12-29_115239](https://user-images.githubusercontent.com/104787819/209941730-d9e5c9e0-8f94-49e0-b2ba-f533f01a7a45.jpg)
As-tu une idée, merci !

**Comment by tcharp38** [comment]
Salut @Jeedom122 
J'ai atteri hier alors je reprends doucement.
Tres bonne année à toi.

Pour la creation d'objets, ont ils toujours la meme adresse IEEE ?

Pour la formule, ca me semble correct mais ne mettre aucun espace. Jeedom ne check pas ca je crois malheureusement.

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Bon retour :)
Merci, très bonne année à toi aussi !

Pour les objets je n'ai pas fait attention à l'adresse IEEE avant de les supprimer, je surveille ;)

Pour la formule, je tâtonne, j'essaie sans espace.

A+++

**Comment by tcharp38** [comment]
Pour la formule, file moi un package de logs et l'adresse ou ID de l equipement que je regarde si je vois qqch.

**Comment by Jeedom122** [comment]
Bonjour @tcharp38 ,
Merci pour ta proposition d'aide pour la formule, j'ai trouvé -0.93 pour réduire le relevé de 0.8 ?
Et j'ai constaté que la formule s'est effacée deux fois ?

Par contre pour info, j'ai constaté une erreur Abeille à chaque redémarrage de Jeedom 
![2022-12-30_105341](https://user-images.githubusercontent.com/104787819/211158849-a61db687-e2ec-4907-9b0e-9ec36883f892.jpg)

Ensuite pour répondre à ta question sur la création intempestive d'objet Abeille, effectivement il y a le même IEEE.
![2023-01-06_201141](https://user-images.githubusercontent.com/104787819/211158960-59b73335-96cb-4544-9881-88e96a53745e.jpg)

Bon weekend :)

**Comment by tcharp38** [comment]
Salut @Jeedom122 
Si toujours la meme IEEE ca n'est probablement pas un bug. Tu as bien dans ton reseau un device "inconnu" de Jeedom.
File moi le pacakge de logs que je regarde quelles infos il y a dessus.

Si tu as redémarré Abeille recemment j'en profiterai pour voir si je comprends qqch pour cette erreur "message corrompu".

Ha et bascule bien sur la derniere beta STP.

**Comment by Jeedom122** [comment]
Salut @tcharp38,
Ci-joint le package de logs.
[AbeilleLogs-230110.tar.gz](https://github.com/KiwiHC16/Abeille/files/10382785/AbeilleLogs-230110.tar.gz)
Je suis bien sous la beta, dernière version.
J'ai encore la formule qui s'est effacée pour la sonde température sonoff ?
Merci pour l'écoute et le temps passé à résoudre les petits problèmes des utilisateurs, respect !
Bonne journée...

**Comment by tcharp38** [comment]
Hello.
Ben ton device a disparu. Il n'apparait nul part avec cette adresse IEEE. Je me trompe ?

Pour la formule qui s'efface il faut que je creuse ca. Pas cool

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Je ne t'ai pas répondu tout de suite pour avoir un peu de recul sur les infos.
Effectivement je n'ai plus de création intempestive d'objet Abeille pour l'instant :)
Par contre, toujours la suppression de la formule pour la sonde de température.
Bonne journée

**Comment by tcharp38** [comment]
Pour la formule qui disparait, ca sera pour la prochaine beta.

**Comment by Jeedom122** [comment]
Super !
Merci !
Je clôture le sujet.
A++
Bon Weekend

**Comment by tcharp38** [comment]
Je reouvre jusqu'a ce que tu me confirmes que c'est ok :)
Donc ... demain au mieux.
Merci et bon WE

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Petit retour concernant la sonde température, hier la formule était renseignée, suite à la mise à jour d'aujourd'hui, elle à disparu :(
Voilou... :)
A++

**Comment by tcharp38** [comment]
Salut.

Désolé :( Je pensais l'avoir fixé mais je viens de trouver un autre bug.

Demain seulement, bascule sur la nouvelle beta (230126-BETA-1) puis
- remettre ta formule
- faire une "Mise à jour" via la page avancée de l'equipement
- reverifier la formule
- si toujours ok redemarrer Abeille et reverifier la formule
- et me filer les logs

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,

Voici le retour:
Mise à jour de l'équipement : formule présente
Redémarrer Abeille : formule supprimée

Les logs
[AbeilleLogs-230127.tar.gz](https://github.com/KiwiHC16/Abeille/files/10517872/AbeilleLogs-230127.tar.gz)

Bonne journée et weekend,
A++

**Comment by tcharp38** [comment]
Salut @Jeedom122 
Je suis un peu perdu. Tu cherchais à mettre une formule sur ton Thermostat ?
Je ne le vois plus dans les équipements Abeille donc... tu peux m'eclairer ?

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Non le thermostat j'ai laissé tomber, 2 reçus, 2 en pannes.
La formule ses sur la sonde température sonoff :)

**Comment by tcharp38** [comment]
Ha donc ca devient hors sujet du coup.
Je te laisse clore celui la et ouvrir un sujet dédié si tu veux bien.

Pour les thermostats tu les voyais comment "en panne" ?

**Comment by Jeedom122** [comment]
Le premier l'horloge prenait 5 mn par heure + température 2° de plus.
Le second l’horloge prenait quelques minutes par jour, 1/2 heure au bout d'une semaine.
J'ouvre un autre sujet.
Merci !
