### ISSUE TITLE
Xiaomi temp/humidity/pressure sensor valeur anormal

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2497]
Salut,

Je constate des valeurs erronées au niveau d'un capteur de température Xiaomi :
![image](https://user-images.githubusercontent.com/26632961/201673610-81cec8cf-894c-406f-b194-e68bd93144c1.png)

Est-ce que cela provient d'une défaillance du matériel ?

Merci d'avance.
[AbeilleLogs-221114.tar.gz](https://github.com/KiwiHC16/Abeille/files/10003457/AbeilleLogs-221114.tar.gz)

**Comment by tcharp38** [comment]
Salut
Je vois que tu en as plusieurs. Le defaut est sur tous ?

Et je ne trouve pas ce "Salon thermostat" dans la liste. Une idée ?

**Comment by toat** [comment]
Salut,

J'ai le problème que sur celui-ci.

C'est la capture du thermostat, du plugin. Voici la capture de la sonde :

![image](https://user-images.githubusercontent.com/26632961/202897553-812a5a41-024a-4926-9178-3b8d882e9549.png)

**Comment by tcharp38** [comment]
Si tu n'as le souci que sur 1 capteur et que tu en as d'autre du meme type, je doute du capteur et non pas d'Abeille.
Mais .. j'aimerais bien voir dans les logs un de ces moments.

Par contre tes derniers logs sont bourrés d'erreurs.
Peux tu basculer sur la derniere beta
redemarrer Abeille
et me filer les logs au bout de 10mins par ex ?

**Comment by toat** [comment]
C'est le seul capteur posant problème, je pense qu'en effet il est défectueux.

Merci.

Voici les logs.

[AbeilleLogs-221204.tar.gz](https://github.com/KiwiHC16/Abeille/files/10149226/AbeilleLogs-221204.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois rien concernant ce capteur dans les logs.
Comme le cas est assez rare, peut etre que tu peux le capturer en le mettant en surveillance. Le log sera dans AbeilleMonitor.

**Comment by toat** [comment]
Le niveau de la pile était faible, je l'ai changé pour voir si cela peut venir de la.

J'ai remplacé son nom pour info, c'est maintenant "Chambre amis 1 thermomètre"

**Comment by tcharp38** [comment]
Ok j'attends ton retour alors.
Si ca se reproduit, active la surveillance sur ce device

**Comment by toat** [comment]
Cela fait plus d'un mois sans problème de mauvaise valeur. Probablement à cause des piles.

Je ferme l'issue.
