### ISSUE TITLE
Repeteur Loratap (id = TS0207, _TZ3000_gszjt2xx)

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2498]
Hello,
pourrais tu creer ce routeur 👍 
[discovery (10).zip](https://github.com/KiwiHC16/Abeille/files/10005414/discovery.10.zip)

![Loratap](https://user-images.githubusercontent.com/93400394/201724196-4d0298f7-ca70-4c2d-9775-38713ce9c6f8.png)

Question subsidiaire: depuis hier j'ai de temps en temps :

ERREUR: 'cmd' vide !
Qu'est ce que ca veut dire?
Merci!
Edit 15/11/2022: apparement il fonctionne mais il n'y a pas la bonne image, j'ai celle par défaut, une abeille ;-)

**Comment by tcharp38** [comment]
Hello.
Il a la gueule du repeteur Tuya.

Donc Loratap 
Quelle ref/modele ?

Pour ton erreur "cmd vide" j'ai besoin des logs correspondants.

**Comment by tcharp38** [comment]
Ecraser le modele TS0207__TZ3000_m0vaazab avec celui la
[TS0207__TZ3000_m0vaazab.zip](https://github.com/KiwiHC16/Abeille/files/10023322/TS0207__TZ3000_m0vaazab.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by Proft1972** [comment]
Tout à l'air de fonctionner ! merci!!! 

Quels log il te faut pour le pb de cmd vide? le package?

**Comment by tcharp38** [comment]
Oui, toujours le package car en fonction des soucis je ne sais pas ou chercher par avance. Le package est assez complet meme si il manque encore qq trucs.

**Comment by Proft1972** [comment]
j'ai eu le defaut ce matin mais le mode debug a disparu, je le remets et je t'envoie les logs au prochain défaut!

**Comment by tcharp38** [comment]
Ca c'est un truc que j'ai déja eu aussi mais je n'ai jamais compris à quel moment le mode debug disparaissait.
Si jamais tu as une piste, je prends aussi.

**Comment by Proft1972** [comment]
j'ai remarqué que le mode débug se perd quand on arrete et redemarre abeille, d'ailleurs ca le fait aussi sur d'autres plugin!

**Comment by tcharp38** [comment]
Ca n'est pourtant pas systematique. Arreter/redemarrer.. je le fais des tonnes de fois pour mes tests et pourtant je reste en mode debug.
Je pensais plutot que c'était lié à une mise à jour.

Mais si ca le fait pour d'autres plugins.. c'est un souci coté Jeedom alors.

**Comment by Proft1972** [comment]
J'ai plutot l'impression que ca vient de Jeedom oui .
 Concernant abeille, de temps en temps (rarement quand même) je perds la clé zigate, je crois que c'est suite à un redemarrage mais je ne suis pas sûr. J'ai beau sélectionner la clé et le port usb, il met toujours NOK  quand je fais "tester" .La dernière fois, j'ai résolu le problème en faisant "libérer" mais les fois d'avant je ne sais plus, j'ai fais tellement de choses!

**Comment by tcharp38** [comment]
Le dernier pb dont tu parles, à savoir "tester = NOK" ca je connais.
Un truc bizarre lié à PHP & apache. J'ai amélioré un peu les choses mais pas satisfaisant encore.

**Comment by Proft1972** [comment]
[AbeilleLogs-221118.tar.gz](https://github.com/KiwiHC16/Abeille/files/10039480/AbeilleLogs-221118.tar.gz)
Hello, voici le package de logs, j'ai eu le défaut 2 fois, la 2eme à 7h34:03
Bonne recherche

**Comment by tcharp38** [comment]
Ca doit correspondre à ca

    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][PAC Piscine]', cmdLogicId=''
    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][PAC Piscine]', cmdLogicId=''
    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][PAC Piscine]', cmdLogicId=''
    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][Pompe Piscine]', cmdLogicId='Get RMS Current'
    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][Pompe Piscine]', cmdLogicId='Get Active Power'
    [2022-11-18 07:34:04][DEBUG] : executePollCmds(cron), '[Piscine][Pompe Piscine]', cmdLogicId='Get RMS Voltage'

mais evenement trop vieux par rapport aux logs.

Du coup par déduction ca doit etre les commandes

- Get RMS Voltage
- Get RMS Current
- Get Active Power

de l'equipement 614 (PAC Piscine)

Peux tu juste déclencher un 'Get Active Power' par ex et me filer les logs avec l heure ?

**Comment by Proft1972** [comment]
[AbeilleLogs-221118 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10040520/AbeilleLogs-221118.1.tar.gz)
j'ai déclenché 'get active power à 11h41

**Comment by tcharp38** [comment]
Ben je ne vois pas d'erreur :(
Tu en as vu une passer ?

**Comment by Proft1972** [comment]
ah ben non! je ne pensais pas qu'il fallait attendre un defau
[AbeilleLogs-221118 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/10043957/AbeilleLogs-221118.2.tar.gz)
J'ai  déclenché un 'Get Active Power' à 19h37 et le defaut a eu lieu à 17h24:m03s

**Comment by tcharp38** [comment]
Bon je ne sais pas d'ou sort l'erreur dont tu parles.
Je ne vois rien.

On clos ce sujet "repeteur" et tu ouvres un autre le jour ou tu as les logs correspondants à l erreur ?

**Comment by Proft1972** [comment]
ok on fait comme ca
