### ISSUE TITLE
221019-STABLE-1: Prise Blitzwolf SHP15 (TS011F__TZ3000_u5u4cakc) remonte valeur incohérente pour Total Power (consommation)

### ISSUE THREAD

**Issue by CocoShaker** [KiwiHC16/Abeille#2499]
Bonjour,

Suite à l'échange sur Jeedom Community [(https://community.jeedom.com/t/blitzwolf-bw-shp15/74849/8?u=hermioneg)], j'ouvre cette anomalie.
J'ai déballé une 2nde prise neuve, mis le plugin en mode debug, et fait l'inclusion. Prise reconnue, commandes créées sans problème apparent (1er package log joint). La commande Total Power = 0 KWh. Normal.

J'ai branché un mobile en chargement sur cette prise, et laissé une heure environ. Je rafraichis la commande, et j'obtiens Total Power = 8589934592KWh. C'est bien sûr incohérent avec le résultat attendu. (2eme package log joint)

J'ai le même résultat sur une première prise identique neuve, et une ancienne prise Tuya TS0121__TZ3000_rdtixbnu qui s'est mise à retourner ce genre de résultat vers mi-octobre 2022, alors qu'elle fonctionnait bien avant.
[AbeilleLogs-221116 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10021710/AbeilleLogs-221116.1.tar.gz)
[AbeilleLogs-221116 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/10021712/AbeilleLogs-221116.2.tar.gz)

A dispo si besoin de manipulation/logs.
Merci pour votre aide.

**Comment by tcharp38** [comment]
Salut @CocoShaker 

Je vois 

> [2022-11-16 12:15:02] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C687, DstAddrMode=02, DstAddr=0000
> [2022-11-16 12:15:02]   FCF=18/General/Serv->Cli, SQN=EE, cmd=01/Read Attributes Response
> [2022-11-16 12:15:02]   AttrId=0000/CurrentSummationDelivered, Status=00, AttrType=25, Value=006D00000000 => 468151435264

Et effectivement la valeur est mal interprétée.
Je pense que c'est fixé dans la beta.
Donc 2 choix
- tu bascules sur la derniere beta
- je te file juste le fichier à ecraser 

Autre point.. tu es sur un tres vieux FW (0003-031E).
Il faudra envisager un jour de basculer sur le 3.23-OPDM avec reappairage complet pour repartir de qqch de propre
ou juste sur la 3.23-LEGACY sans réappairage... pour l'instant.

**Comment by CocoShaker** [comment]
Merci pour la réponse rapide.
J'ai installé la beta, et cela a bien corrigé pour les 2 Blitzwolf. J'attends de voir pour l'autre prise Tuya. C'était donc bien la dernière mise à jour qui avait "cassé" ma consommation. J'aurais dû ouvrir un ticket plus tôt, lesson learned !
Pour le FW je sais, mais j'ai déjà tellement eu de mal à passer sur la 31E que j'essayais de gagner du temps avant de mettre à jour à nouveau le FW. Je vais y passer bientôt, promis !

Encore merci pour toute l'aide.

**Comment by tcharp38** [comment]
Le FW n'est evidement pas une obligation, pas pour l'instant. Il reste compatible avec ce que j'ai modifié.
Mais le jour ou tu commences à avoir des comportements bizarres.. alors la faudra pas hesiter et repartir de qqch de propre.. à savoir dernier FW en version **OPDM**.

**Comment by CocoShaker** [comment]
Hello,
Mise à jour du FW en 3.23 Legacy effectuée sans soucis.

**Comment by tcharp38** [comment]
Ouff :)
J'ai toujours peur de ça.
