### ISSUE TITLE
Ajouter le capteur IR/Light Xiaomi (@tfabien )

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#25]
@tfabien dans forum Abeille Jeedom.

Aujourd'hui, réinstallation du firmware zigate 3.0b , et configuration/test sur le pc avec ZWGui, concluants
Branchement au Rpi, mise a jour du plugin depuis la branche stable du github, et cela fonctionne :-)
le détecteur de présence fonctionne, mais uniquement l'ancien modele
Le nouveau modele (avec capteur de luminosité) n'est pas reconnu.

Effectivement, plus de creation d'objets inconnus avec la derneire version master 318e58e 
mais pas de creation du detecteur de presence non plus ;)

La liste des clusters n'est pas publiée sur zigate.fr pour ce capteur, je suppose que c'est pour ca qu'il n'est pas présent dans le plugin
http://zigate.fr/produits-xiaomi-compatibles-zigate/

Capteur de presence/luminosité (nouveau modele Aqara)
https://fr.gearbest.com/alarm-systems/p ... tml?wid=55

Lors du bind:
-------------- 2018-01-24 21:42:00
protocolDatas
message > 12 char
-------------- 2018-01-24 20:42:00
protocolDatas
message > 12 char
Type: 8102
type: 8102
[2018-01-24 20:42:00]
(Attribute Report)(Processed->MQTT)
SQN: 06
Src Addr : 1010
End Point : 18
Cluster ID : 0001
Attr ID : 016f
Attr Status :
Attr Data Type :
Attr Size :
Data byte list :
Type: 8110

Detection presence ON
[2018-01-24 21:39:00][DEBUG] : AbeilleSerial: 2018-01-24 21:39:00 -> 8102000Fe701b3b5
[2018-01-24 21:39:00][DEBUG] : AbeilleParser: -----------------------
[2018-01-24 21:39:00][DEBUG] : AbeilleParser: protocolData
[2018-01-24 21:39:00][DEBUG] : AbeilleParser: type: 8102
[2018-01-24 21:39:00][DEBUG] : AbeilleParser: (Attribut Report)(Processed->MQTT)

-------------- 2018-01-24 21:40:51
protocolDatas
message > 12 char
Type: 8102
type: 8102
[2018-01-24 21:40:51]
(Attribute Report)(Processed->MQTT)
SQN: 16
Src Addr : b3b5
End Point : 00
Cluster ID : 1010
Attr ID : 8011
Attr Status : 04
Attr Data Type : 06
Attr Size : 0010
Data byte list : 00
-------------- 2018-01-24 20:40:51
protocolDatas
message > 12 char
Type: 8102
type: 8102
[2018-01-24 20:40:51]
(Attribute Report)(Processed->MQTT)
SQN: 16
Src Addr : b3b5
End Point : 00
Cluster ID : 1010
Attr ID : 8011
Attr Status : 04
Attr Data Type : 06
Attr Size : 0010
Data byte list : 00

**Comment by lukebr91** [comment]
![image](https://user-images.githubusercontent.com/35848408/35777315-2e7951da-09ac-11e8-8cfc-58f837d206ec.png)
En passant devant : 

> AbeilleParser: 2018-02-04 13:16:28 -------------- 2018-02-04 13:16:28: protocolData
> AbeilleParser: 2018-02-04 13:16:28 message > 12 char
> AbeilleParser: 2018-02-04 13:16:28 Type: 8102 quality: 39
> AbeilleParser: 2018-02-04 13:16:28  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:28 [2018-02-04 13:16:28]
> AbeilleParser: 2018-02-04 13:16:28 SQN: 02
> AbeilleParser: 2018-02-04 13:16:28 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:28 End Point : 01
> AbeilleParser: 2018-02-04 13:16:28 Cluster ID : 0400
> AbeilleParser: 2018-02-04 13:16:28 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:28 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:28 Attr Data Type : 21
> AbeilleParser: 2018-02-04 13:16:28 Attr Size : 0002
> AbeilleParser: 2018-02-04 13:16:28 Data byte list : 01db
> AbeilleParser: 2018-02-04 13:16:28 Data byte: ".$data
> AbeilleParser: 2018-02-04 13:16:28 -------------- 2018-02-04 13:16:28: protocolData
> AbeilleParser: 2018-02-04 13:16:28 message > 12 char
> AbeilleParser: 2018-02-04 13:16:28 Type: 8102 quality: 39
> AbeilleParser: 2018-02-04 13:16:28  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:28 [2018-02-04 13:16:28]
> AbeilleParser: 2018-02-04 13:16:28 SQN: 03
> AbeilleParser: 2018-02-04 13:16:28 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:28 End Point : 01
> AbeilleParser: 2018-02-04 13:16:28 Cluster ID : 0406
> AbeilleParser: 2018-02-04 13:16:28 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:28 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:28 Attr Data Type : 18
> AbeilleParser: 2018-02-04 13:16:28 Attr Size : 0001
> AbeilleParser: 2018-02-04 13:16:28 Data byte list : 01
> AbeilleParser: 2018-02-04 13:16:28 Data byte: ".$data
> AbeilleParser: 2018-02-04 13:16:36 -------------- 2018-02-04 13:16:36: protocolData
> AbeilleParser: 2018-02-04 13:16:36 message > 12 char
> AbeilleParser: 2018-02-04 13:16:36 Type: 8102 quality: 39
> AbeilleParser: 2018-02-04 13:16:36  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:36 [2018-02-04 13:16:36]
> AbeilleParser: 2018-02-04 13:16:36 SQN: 04
> AbeilleParser: 2018-02-04 13:16:36 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:36 End Point : 01
> AbeilleParser: 2018-02-04 13:16:36 Cluster ID : 0400
> AbeilleParser: 2018-02-04 13:16:36 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:36 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:36 Attr Data Type : 21
> AbeilleParser: 2018-02-04 13:16:36 Attr Size : 0002
> AbeilleParser: 2018-02-04 13:16:36 Data byte list : 01a4
> AbeilleParser: 2018-02-04 13:16:36 Data byte: ".$data
> AbeilleParser: 2018-02-04 13:16:36 -------------- 2018-02-04 13:16:36: protocolData
> AbeilleParser: 2018-02-04 13:16:36 message > 12 char
> AbeilleParser: 2018-02-04 13:16:36 Type: 8102 quality: 36
> AbeilleParser: 2018-02-04 13:16:36  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:36 [2018-02-04 13:16:36]
> AbeilleParser: 2018-02-04 13:16:36 SQN: 05
> AbeilleParser: 2018-02-04 13:16:36 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:36 End Point : 01
> AbeilleParser: 2018-02-04 13:16:36 Cluster ID : 0406
> AbeilleParser: 2018-02-04 13:16:36 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:36 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:36 Attr Data Type : 18
> AbeilleParser: 2018-02-04 13:16:36 Attr Size : 0001
> AbeilleParser: 2018-02-04 13:16:36 Data byte list : 01
> AbeilleParser: 2018-02-04 13:16:36 Data byte: ".$data

Quelques seconde plus tard (retour etat 0 ?)

> AbeilleParser: 2018-02-04 13:16:41 -------------- 2018-02-04 13:16:41: protocolData
> AbeilleParser: 2018-02-04 13:16:41 message > 12 char
> AbeilleParser: 2018-02-04 13:16:41 Type: 8102 quality: 5d
> AbeilleParser: 2018-02-04 13:16:41  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:41 [2018-02-04 13:16:41]
> AbeilleParser: 2018-02-04 13:16:41 SQN: 06
> AbeilleParser: 2018-02-04 13:16:41 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:41 End Point : 01
> AbeilleParser: 2018-02-04 13:16:41 Cluster ID : 0400
> AbeilleParser: 2018-02-04 13:16:41 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:41 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:41 Attr Data Type : 21
> AbeilleParser: 2018-02-04 13:16:41 Attr Size : 0002
> AbeilleParser: 2018-02-04 13:16:41 Data byte list : 01ec
> AbeilleParser: 2018-02-04 13:16:41 Data byte: ".$data
> AbeilleParser: 2018-02-04 13:16:41 -------------- 2018-02-04 13:16:41: protocolData
> AbeilleParser: 2018-02-04 13:16:41 message > 12 char
> AbeilleParser: 2018-02-04 13:16:41 Type: 8102 quality: 5d
> AbeilleParser: 2018-02-04 13:16:41  type: 8102 (Attribut Report)(Processed->MQTT)
> AbeilleParser: 2018-02-04 13:16:41 [2018-02-04 13:16:41]
> AbeilleParser: 2018-02-04 13:16:41 SQN: 07
> AbeilleParser: 2018-02-04 13:16:41 Src Addr : 4436
> AbeilleParser: 2018-02-04 13:16:41 End Point : 01
> AbeilleParser: 2018-02-04 13:16:41 Cluster ID : 0406
> AbeilleParser: 2018-02-04 13:16:41 Attr ID : 0000
> AbeilleParser: 2018-02-04 13:16:41 Attr Status : 00
> AbeilleParser: 2018-02-04 13:16:41 Attr Data Type : 18
> AbeilleParser: 2018-02-04 13:16:41 Attr Size : 0001
> AbeilleParser: 2018-02-04 13:16:41 Data byte list : 01
> AbeilleParser: 2018-02-04 13:16:41 Data byte: ".$data

**Comment by lukebr91** [comment]
![image](https://user-images.githubusercontent.com/35848408/35777962-23685286-09b7-11e8-8c5f-4ebe85ea33fd.png)

J'ai ajouté pour le JSON : 
> "lumi.sensor_motion.aq2": {
>     "nameJeedom": "Xiaomi Presence Aqara",
>     "battery_type": "1xCR2032",
>     "Categorie": {
>       "security": "1"
>     },
>     "configuration": {
>       "icone": "XiaomiInfraRouge"
>     },
>     "Commandes": {
>       "IEEE-Addr": {
>         "name": "IEEE-Addr",
>         "order": 8,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": "badge"
>       },
>       "0000-0001": {
>         "name": "SW",
>         "order": 0,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": ""
>       },
>       "0000-0005": {
>         "name": "nom",
>         "order": 1,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": ""
>       },
>       "0406-0000": {
>         "name": "etat",
>         "order": 2,
>         "isHistorized": "1",
>         "Type": "info",
>         "subType": "binary",
>         "invertBinary": "1",
>         "template": "presence",
>         "configuration": {
>           "returnStateValue": "0",
>           "returnStateTime": "1"
>         }
>       },
>       "0400-0000": {
>         "name": "Luminosite",
>         "order": 3,
>         "isHistorized": "1",
>         "Type": "info",
>         "subType": "numeric",
>         "invertBinary": "0",
>         "template": ""
>       },
>       "Time-Time": {
>         "name": "Last",
>         "order": 4,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": ""
>       },
>       "Time-TimeStamp": {
>         "name": "Last Stamp",
>         "order": 5,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "numeric",
>         "invertBinary": "0",
>         "template": "badge"
>       },
>       "Link-Quality": {
>         "name": "Link Quality",
>         "order": 6,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": "badge"
>       },
>       "Power-Source": {
>         "name": "Power Source",
>         "order": 7,
>         "isHistorized": "0",
>         "Type": "info",
>         "subType": "string",
>         "invertBinary": "0",
>         "template": "badge"
>       }
>     }
>   },

👍

**Comment by KiwiHC16** [comment]
Luc, peux tu nous donner une image de ce capteur ?

**Comment by lukebr91** [comment]
![image](https://user-images.githubusercontent.com/35848408/35929316-83e00f80-0c2f-11e8-95dc-b834eacf6910.png)

**Comment by lukebr91** [comment]
Si tu peux corriger l'image du body sensor non aqara ;)  
![image](https://user-images.githubusercontent.com/35848408/35929391-afe9d692-0c2f-11e8-9af7-bc14954e912d.png)

**Comment by KiwiHC16** [comment]
JSON dans master maintenant, et les deux icones aussi. Peux tu tester ?

**Comment by lukebr91** [comment]
Pour moi c'est ok, merci !

**Comment by KiwiHC16** [comment]
Ok alors je clos l issue.
