### ISSUE TITLE
Sonde de température et humidité Moes (id = RH3052, TUYATEC-gqhxixyk)

### ISSUE THREAD

**Issue by brutusangel** [KiwiHC16/Abeille#2500]
Bonjour
j'essaie d'intégrer un sonde de température/humidité Tuya RH3052 , mais je n'y arrive pas.
J'essaie de modifier la configuration du fichier *. json,  sur base de ce que j'ai pu lire sur le forum et ici , mais j'y arrive pas/
Je joint le fichier de débug en annexe.
Mon système tourne sur RPI3 avec Pizigate et jeedom ver4.
Pouvez-vous m'aider?..
Merci 
[AbeilleLogs-221117.tar.gz](https://github.com/KiwiHC16/Abeille/files/10026424/AbeilleLogs-221117.tar.gz)

**Comment by tcharp38** [comment]
Salut @brutusangel 
La premiere chose est d'obtenir un fichier discovery.
Voir la doc: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by tcharp38** [comment]
Est ce que ca correspond à ce modele ? https://zigbee.blakadder.com/Rehent_RH-ZTH1.html
Donc vendeur = Rehent & modele = RH-ZTH1 ?

**Comment by brutusangel** [comment]
Bonjour,
Non cela ne correspond pas au modèle du lien/
Voici un lien https://fr.aliexpress.com/item/1005002591252576.html?spm=a2g0o.order_list.0.0.21ef5e5bBE7obv&gatewayAdapt=glo2fra

je vous joint le discovery demandé suivant votre procédure.
J'y ai aussi ajouté discovery(4) qui est celui qui se trouve dans le répertoire device_local . (il me parait plus complet) 

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10031885/discovery.zip)

[discovery (4).zip](https://github.com/KiwiHC16/Abeille/files/10031880/discovery.4.zip)

Merci

**Comment by tcharp38** [comment]
C'est donc du "Moes" sur une base Tuya
Y a t'il une ref associée ?

Ton "discovery" est completement vide donc inutilisable.
Celu du local contient qq pistes interressantes mais toujours pas l'identifiant. Etrange.

As tu eu tous les voyants au vert ? Il faut reveiller le device en meme temps d'une maniere ou d'une autre et faire des refresh jusqu'a ce que les voyants soient au vert.

**Comment by tcharp38** [comment]
Je me suis basé sur qq infos trouvées dans les logs.

A decompresser dans core/config/devices/TS0201__TZ3000_dowj6gyi
[TS0201__TZ3000_dowj6gyi.zip](https://github.com/KiwiHC16/Abeille/files/10032612/TS0201__TZ3000_dowj6gyi.zip)

redemarrer Abeille
refaire inclusion

**Comment by brutusangel** [comment]
j'ai fait ce que tu as demandé, j'ai relancé et passé les voyants tous  au vert , et télécharger le discovery que voici discovery  
Ca ne fonctionne toujours pas, mais il y a de l'avancement... 
Merci
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10033079/discovery.zip)
Au fait, j'ai oublié de te dire que j'avais aussi ce message qui apparaissait. (déjà avant)

	2022-11-17 16:24:56	Abeille	ERREUR: Abeille1, Message corrompu (taille payload incorrecte, taille=10B, att=0B)

**Comment by tcharp38** [comment]
Tu as essayé mon modele ?
Qu 'est ce que "ne fonctionne toujours pas" ? Trop vague. Et il me faut le package de logs en relation avec l'evenement pour creuser.

**Comment by brutusangel** [comment]
je n'ai toujours pas la température et le taux d'humidité. n'y l'icone ... j'ai toujours l'icone Abeille....
[AbeilleLogs-221117.tar.gz](https://github.com/KiwiHC16/Abeille/files/10033411/AbeilleLogs-221117.tar.gz)
![Capture](https://user-images.githubusercontent.com/92653196/202499853-fab3f35b-5f83-4081-b158-498b7c23ea14.PNG)



Voici ce que tu as demandé... je fais peut-être des erreurs.... 
Oui oui ,j'ai essayé ton modèle

Merci

**Comment by tcharp38** [comment]
As tu fait une nouvelle inclusion apres avoir redemarré Abeille ?
Si non je te laisse le faire
et me filer le package de logs dans la foulée.

**Comment by brutusangel** [comment]
Oui j'avais tout fait comme tu avais demandé.
Voici ce que je viens de faire:
- j'ai désinstallé abeille de jeedom
- j'ai réinstallé abeille
- j'ai  décompressé et copié dans core/config/devices/TS0201__TZ3000_dowj6gyi
- j"ai redémarré abeille et fait une nouvelle inclusion.
- j'ai créé le discovery et log 
- 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10035289/discovery.zip)
[AbeilleLogs-221117.tar.gz](https://github.com/KiwiHC16/Abeille/files/10035291/AbeilleLogs-221117.tar.gz)

j'espère que j'ai bien fait la procédure..
je suis toute ouïe pour toutes manipulations/

**Comment by tcharp38** [comment]
Ha je viens de comprendre.
Tu es sur la stable donc loin derriere les dernieres evolutions et le modele que je t'ai donné ne correspond pas.

Tu ne voudrais pas basculer sur la beta ?

**Comment by brutusangel** [comment]
oui, mais je ne sais pas comment faire...
 je vais dans le centre de mise jour de jeedom et je vois que c'est la version stable de abeille qui est installée, mais si je demande de vérifier la mise à jour, il ne me propose pas le beta , ça reste toujours sur le version stable .
Je ne sais pas comment forcer l'installation de la beta.

**Comment by tcharp38** [comment]
Il faut prendre l'habitude de regarder la doc. J'y ai passé pas mal de temps, donc meme si ca n'est pas le top ou pas clair, il y a des infos.
Voir la: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by brutusangel** [comment]
Merci, je n'avais pas vu et lu..
Voici ce que j'ai fait.
J'ai voulu repartir à 0 et j'ai réinstallé mon raspberry,  Pizigate  et l'installation de jeedom.
j'ai installé la version Beta de  Abeille, suivant t'as procédure.
j'ai Modifier core/config/devices/TS0201__TZ3000_dowj6gyi comme demandé.
 j'ai redémarré Abeille et refait une inclusion/
Et Je suis Heureux de dire que cela fonctionne.  J'ai bien mon appareil intégré à Jeedom.
Merci pour t'as patience et ton professionnalisme.

**Comment by tcharp38** [comment]
Super !
Donc des soucis restants ?

**Comment by brutusangel** [comment]
Je regarde, mais on dirait que j'ai des lignes droites dans l'historique, comme si ce n'est pas rafraichi... j'ai installé un 2em capteur identiques et il apparait bien dans abeilles, mais , j'ai aussi  des lignes droites dans l'historique. (21° et 63%)..
Je vais laisser un peu de temps pour voir s'il y a des variations.

**Comment by tcharp38** [comment]
File un package de logs.
On verra ce qui remonte.

**Comment by brutusangel** [comment]
Voici, 
je n'arrive pas à avoir tout vert à la découverte d'un capteur et les courbes reste droites sur les 2 capteurs.
Et sur l'un des 2 capteurs, je suis passé en time-out.
voici
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10042367/discovery.zip)
[AbeilleLogs-221118.tar.gz](https://github.com/KiwiHC16/Abeille/files/10042376/AbeilleLogs-221118.tar.gz)

**Comment by tcharp38** [comment]
Ok on va pas jouer avec les 2 en meme temps.

Le 9B7A (donc "Cuisine") remonte plein d'infos, de temp et d'humidité.
Si celui la tient, c'est bon.

Oublie le discovery maintenant. Seuls les logs sont utiles pour avancer.

**Comment by brutusangel** [comment]
la température et humidité reste toujours figées  depuis des heures à l'écran et ne varient pas non plus dans l'historique.
J'ai aussi un petit icone de timeout sur le cadre.
![Capture1](https://user-images.githubusercontent.com/92653196/202812864-afbd85a9-b657-48c6-a5b8-54ab68274bda.PNG)
Je te joint le fichier des log, en espérant que tu trouves.
merci
[AbeilleLogs-221118.tar.gz](https://github.com/KiwiHC16/Abeille/files/10045209/AbeilleLogs-221118.tar.gz)

**Comment by tcharp38** [comment]
Normal.
En regardant les logs on voit qu'il a quitté le réseau à 15:42:04

> [2022-11-18 15:42:04] Abeille1, Type=8048/Leave indication, ExtAddr=60A423FFFE39E7C2, RejoinStatus=00

Saurais tu pourquoi ?

Tu as du avoir un message aussi, du style "blabla à quitté le reseau". Verifie les messages Jeedom en haut à droite

![image](https://user-images.githubusercontent.com/35221038/202850245-f16efb2e-cc5d-4dc3-8cf9-25419054cf87.png)

**Comment by brutusangel** [comment]
Bonjour,
En fait, je n'ai pas de message reçu de jeedom qu'il avait quitté le réseau. (il y avait aussi 2 autres capteurs en timeout).
Du fait que je ne savais pas quoi faire, j'ai désinstallé Abeille et je l'ai réinstallé.
J'ai lancé une nouvelle découverte pour le capteur Cuisine , et voici le message que j'ai reçu de jeedom (corruption)
![Capture](https://user-images.githubusercontent.com/92653196/202907369-d4eb7a9b-2041-44ff-a32b-ea6733d2b3ff.PNG)

Depuis l'installation ce matin, je n'ai toujours pas de remise à jour de la température et du taux d'humidité du capteur.
les valeurs sont toujours figées depuis installation.
je te joins les logs ...
[AbeilleLogs-221120.tar.gz](https://github.com/KiwiHC16/Abeille/files/10049903/AbeilleLogs-221120.tar.gz)

**Comment by tcharp38** [comment]
Le capteur qui avait quitté le reseau est à nouveau la.
Donc tu as refait une inclusion.

Ceci étant.. je vois de nombreuses erreurs CRC venant de la Zigate.
Ca n'est pas normal du tout et ca genere le message d'erreur '..message corrompu...".

Es tu sur que personne d'autre n'utilise le port /dev/ttyAMA0 ?

Peux tu me zipper les fichiers
/boot/config.txt
/boot/cmdline.txt

**Comment by brutusangel** [comment]
je n'ai pas d'autre équipement sur mon raspberry.. je ne pense pas que ttyAMAO est utilisé autre part... 
Voici ce que tu m'as demandés comme fichier.. 
 Pas facile tout ça... peut être que c'est hardware...
Voici
[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/10060165/Downloads.zip)

**Comment by tcharp38** [comment]
Je ne vois malheureusement rien dans ces 2 fichiers qui parlent de /dev/ttyAMA0.

Les erreurs CRC peuvent etre produites par des acces concurrents de temps en temps à ce port.
Le log "AbeilleSerial" est le premier à capturer ces erreurs. Tu peux y voir les heures si jamais ca te parle.

**Comment by brutusangel** [comment]
j'essaie d'installer sur RPI 4 pour voir ce qu'il se passe... mais j'ai des soucis d'installation
Je parcours  les procédures d'installation , mais j'ai des soucis... 
je reviens une fois que j'ai pu réussir à installer sur Rpi 4.

**Comment by brutusangel** [comment]
je suis bloqué a l'installation du RPI 4 et je ne sais pas pk... j'ai suivi la procédure, mais voici le message qui me bloque.
![Capture](https://user-images.githubusercontent.com/92653196/203665996-1d979960-eab7-43c9-b7ce-eac2f49874f9.PNG)

**Comment by tcharp38** [comment]
Salut
Désolé. Perso je ne tourne pas sur RPI et donc jamais installé mais on dirait qu'il y a des soucis avec le serveur.
Il y a surement une autre methode pour installer le RPI.
Quoi qu'il en soit c'est hors sujet et hors Abeille à ce stade :(

**Comment by brutusangel** [comment]
Voilà, j'ai installé sur RPI 4.. 
J'ai le même phénomène , la valeur n'est pas rafraichie. Elle se rafraichi par moment quand je parcourue les vue différentes de jeedom, mais , je ne trouve pas à quel moment la valeur est remise à jour. 
Si je constate certaines choses,  je reviendrais mettre un message.

**Comment by tcharp38** [comment]
Tu me files un package de logs entre temps ?

**Comment by brutusangel** [comment]
voici, 
j'ai réinstallé sur un RPI 3B.. et toujours le souci de remise a jour des valeurs.
je te joins un petit log... 
[AbeilleLogs-221212 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10203538/AbeilleLogs-221212.1.tar.gz)

**Comment by tcharp38** [comment]
Je suppose que tu as clos le sujet par erreur. Je reouvre.

**Comment by tcharp38** [comment]
Hello
Ecrase ton modele par celui ci
[TS0201__TZ3000_dowj6gyi.zip](https://github.com/KiwiHC16/Abeille/files/10207824/TS0201__TZ3000_dowj6gyi.zip)

et refait une inclusion

**Comment by brutusangel** [comment]
Super.... ça Fonctionne ...
je n'ai plus de timeout.

Merci pour l'assistance..,

**Comment by tcharp38** [comment]
Que reste il du coup sur ce sujet pour le clore ?

**Comment by brutusangel** [comment]
Tout est en ordre....je clos...
Merci
