### ISSUE TITLE
Ajout GLEDOPTO GL-FL-004P Floodlight RGB+CCT PRO (id = GL-FL-004P, GLEDOPTO)

### ISSUE THREAD

**Issue by CocoShaker** [KiwiHC16/Abeille#2501]
Bonjour,

Cela fait plusieurs mois que j'utilise ces projecteurs avec un modèle local. Est-ce qu'il serait possible de l'inclure dans la configuration du plugin ?
Voici le lien du produit : [https://fr.aliexpress.com/item/1005001849117747.html](url)
Le discovery : `{"epCount":2,"endPoints":{"0B":{"servClusters":{"1000":{"attributes":{"FFFD":{"dataType":"21","access":"05","value":1}},"commandsGenerated":["01","03","11","13","15","40","41","42"],"commandsReceived":["41","42"]},"0000":{"attributes":{"4000":{"dataType":"42","access":"05","value":"V_1_7_A1"},"0004":{"value":"GLEDOPTO","dataType":"42","access":"05"},"0005":{"value":"GL-FL-004P","dataType":"42","access":"05"},"0000":{"dataType":"20","access":"05","value":3},"0001":{"dataType":"20","access":"05","value":0},"0002":{"dataType":"20","access":"05","value":0},"0003":{"dataType":"20","access":"05","value":2},"0006":{"dataType":"42","access":"05","value":"20210421"},"0007":{"dataType":"30","access":"05","value":0},"0008":{"dataType":"30","access":"05","value":255},"0009":{"dataType":"30","access":"05","value":255},"000A":{"dataType":"41","access":"05","value":""},"000B":{"dataType":"42","access":"05","value":""},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":["00"],"commandsGenerated":[]},"0003":{"attributes":{"0000":{"dataType":"21","access":"07","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":["00","01"],"commandsGenerated":["00"]},"0004":{"attributes":{"0000":{"dataType":"18","access":"05","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":["00","01","02","03","04","05"],"commandsGenerated":["00","01","02","03"]},"0005":{"attributes":{"0000":{"dataType":"20","access":"05","value":0},"0001":{"dataType":"20","access":"05","value":0},"0002":{"dataType":"21","access":"05","value":0},"0003":{"dataType":"10","access":"05","value":0},"0004":{"dataType":"18","access":"05","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":["00","01","02","03","04","05","06","40","41","42"],"commandsGenerated":["00","01","02","03","04","06"]},"0006":{"attributes":{"4000":{"dataType":"10","access":"05","value":1},"4001":{"dataType":"21","access":"07","value":0},"4002":{"dataType":"21","access":"07","value":0},"4003":{"dataType":"30","access":"07","value":255},"0000":{"dataType":"10","access":"05","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":["00","01","02","40","41","42"],"commandsGenerated":[]},"0008":{"attributes":{"4000":{"dataType":"20","access":"07","value":51},"0000":{"dataType":"20","access":"05","value":254},"0001":{"dataType":"21","access":"05","value":0},"000F":{"dataType":"18","access":"07","value":0},"FFFD":{"dataType":"21","access":"05","value":1}},"commandsReceived":[],"commandsGenerated":[]},"0300":{"attributes":{"0000":{"dataType":"20","access":"05","value":84},"0001":{"dataType":"20","access":"05","value":254},"0002":{"dataType":"21","access":"05","value":4},"0003":{"dataType":"21","access":"05","value":5762},"0004":{"dataType":"21","access":"05","value":40554},"0007":{"dataType":"21","access":"05","value":158},"0008":{"dataType":"30","access":"05","value":1},"000F":{"dataType":"18","access":"07","value":0},"0010":{"dataType":"20","access":"05","value":5},"0011":{"dataType":"21","access":"05","value":0},"0012":{"dataType":"21","access":"05","value":0},"0013":{"dataType":"20","access":"05","value":0},"0015":{"dataType":"21","access":"05","value":0},"0016":{"dataType":"21","access":"05","value":0},"0017":{"dataType":"20","access":"05","value":0},"0019":{"dataType":"21","access":"05","value":0},"001A":{"dataType":"21","access":"05","value":0},"001B":{"dataType":"20","access":"05","value":0},"0020":{"dataType":"21","access":"05","value":0}},"commandsReceived":[],"commandsGenerated":[]},"0019":{"attributes":{}}},"cliClusters":{"0019":{"attributes":{"0000":{},"0001":{},"0002":{},"0006":{},"FFFD":{}}}}},"F2":{"servClusters":{"":{}},"cliClusters":{"0021":{}}}},"powerSource":"mains"}`

L'image : 
![GLEDOPTO 10W Floodlight RGB+CCT PRO](https://user-images.githubusercontent.com/118360569/202670473-896a6027-4324-4a10-9abb-aa7cf6ede398.png)

Merci !

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices
[GL-FL-004P_GLEDOPTO.zip](https://github.com/KiwiHC16/Abeille/files/10043260/GL-FL-004P_GLEDOPTO.zip)

puis redemarrer Abeille
refaire inclusion
et tester

**Comment by CocoShaker** [comment]
Merci.
Par contre je vais devoir attendre un peu :  pour le réinclure, je dois couper son alimentation, et comme c'est un spot extérieur son alim est dans le pool house. Il pleut ...

**Comment by tcharp38** [comment]
Ha OK. Un réinitialiser via sa page avancé doit aussi le faire

**Comment by CocoShaker** [comment]
Non j'ai essayé, mais ça repart sur le modèle local, tout en précisant qu'il existe un modèle officiel.
![image](https://user-images.githubusercontent.com/118360569/203116275-bf70818a-d087-410d-b3cf-c11ca404470a.png)
![image](https://user-images.githubusercontent.com/118360569/203116419-ffb8529c-8cdd-4161-859d-5c9d08e0fd19.png)

**Comment by tcharp38** [comment]
Ok alors detruit le modele local avant de refaire la meme manip.
Il sort d'ou d'ailleurs ce modele local (devices_local) ?

**Comment by CocoShaker** [comment]
Hello,
Désolée pour le délai, le travail...
Alors le modèle local vient d'une copie d'un autre GL que j'ai adapté quand j'ai eu mes projecteurs. Je l'ai déposé dans device_local et intégré mes projos comme cela. Cela fonctionnait, j'ai eu les commandes que je voulais (on, off..). J'ai demandé à créer un modèle dédié pour que cela serve à tous.
Nouveau test :
J'ai supprimé tous les dossiers GL-FL-004P* qu'ils soient dans device ou device_local. J'ai redémarré le démon, puis fait la mise à jour beta 221122-beta1 qui contient le modèle à tester. J'ai redémarré le démon.
Je fais "réinitialiser", mais il me donne le même message qu'avant : modèle local utilisé alors qu'un modèle officiel existe.
J'ai bien vérifié, je n'ai plus de fichier dans device-local (sauf les readme). J'inclus les logs, au cas où.

Il pleut pratiquement toujours ou il fait noir quand je suis à la maison, pas pratique pour aller réinclure les projecteurs. J'essaierai ce week-end si pas réussi d'ici là. merci !
[AbeilleLogs-221123.tar.gz](https://github.com/KiwiHC16/Abeille/files/10077275/AbeilleLogs-221123.tar.gz)

**Comment by tcharp38** [comment]
Hello.
Pas de soucis. On doit pouvoir reinitialiser l'equipement a distance vu qu'il est sur secteur.
Je reflechis et on teste qqch

**Comment by tcharp38** [comment]
A decompresser dans core/class
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/10091547/Abeille.class.php.zip)

Puis redemarrer Abeille
faire reinitialiser
et me filer les logs

**Comment by CocoShaker** [comment]
Hello,

J'ai réussi à mettre à jour à force de relancer (je n'ai pas installé le package ci-dessus). Et je confirme que les commandes fonctionnent.
Un grand merci !!

**Comment by tcharp38** [comment]
Ok, du coup on peut clore ce sujet ?

**Comment by CocoShaker** [comment]
Tout à fait, je clôture !
