### ISSUE TITLE
Ajout Philips Hue White E27 LWA017

### ISSUE THREAD

**Issue by Krankhore** [KiwiHC16/Abeille#2503]
Bonjour,
est il possible d'ajouter l'ampoule Philips white 1100 lumen
le fichier discovery: 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10056614/discovery.zip)

![Philips Hue White ](https://user-images.githubusercontent.com/56954282/203052838-be18b1b5-ebc5-475c-b533-426587875ac3.jpg)

**Comment by tcharp38** [comment]
A tester
[LWA017_SignifyNetherlandsBV.zip](https://github.com/KiwiHC16/Abeille/files/10066843/LWA017_SignifyNetherlandsBV.zip)

L'image ne devrait avoir aucun arriere plan et seul le format PNG est accepté.
Je te laisse corriger le tir.

**Comment by Krankhore** [comment]
Bonjour, 
il a fallu que j'ajoute des points pour que cela fonctionne :
LWA017_SignifyNetherlands**B.V..zip** au lieu de LWA017_SignifyNetherlandsBV.zip et donc idem pour le nom du fichier json (et le modèle dans le fichier json )

Pour l’icône , j'ai repris celle de la Philips LTA001, c'est la même forme ( d'ailleurs j'avais fait un essai avec le fichier json de la LTA001 et cela marchait très bien)

et merci.

**Comment by tcharp38** [comment]
Ha oui pour les points j'ai fait aussi un correctif dans le code. Désolé.
Pour l'icone c'est aussi fixé dans la prochaine beta.

Je te laisserai tester la prochaine beta avant de clore ce sujet si tout va bien.
Detruire ton eq cote Jeedom et refaire inclusion.

**Comment by Krankhore** [comment]
Bonjour,
j'ai supprimé l’équipement coté jeedom, supprimé le répertoire dans devices_local et installé la dernière  beta.

En rallumant l'ampoule, elle a bien été reconnu par abeille et s'est bien enregistré.
C'est tout bon.

**Comment by tcharp38** [comment]
On peut clore le sujet du coup ?

**Comment by Krankhore** [comment]
je clôture
