### ISSUE TITLE
repeteur ikea passe en time out

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2505]
repeteur ikea qui decroche et passe en time out
[AbeilleLogs-221121(4).tar.gz](https://github.com/KiwiHC16/Abeille/files/10070777/AbeilleLogs-221121.4.tar.gz)

**Comment by chrisb13790** [comment]
[AbeilleLogs-221122.tar.gz](https://github.com/KiwiHC16/Abeille/files/10071352/AbeilleLogs-221122.tar.gz)

**Comment by tcharp38** [comment]
Peux tu faire un reinitialiser de "TRADFRI signal repeater bureau".
L'autre me semble deja correct.

Et me filer les logs

**Comment by chrisb13790** [comment]
[AbeilleLogs-221123.tar.gz](https://github.com/KiwiHC16/Abeille/files/10072874/AbeilleLogs-221123.tar.gz)

**Comment by tcharp38** [comment]
Donc pour moi il ne devrait plus etre en timeout.
Tu confirmes ?

**Comment by chrisb13790** [comment]
pour le moment pas de timeout j ai lancé la maj de la beta , je ferais un point demain matin

**Comment by chrisb13790** [comment]
plus de timeout

**Comment by tcharp38** [comment]
Parfait.
Pour memo, il faut "reinitialiser" l'equipement via la page avancé pour corriger ce souci.

On cloture ?

**Comment by chrisb13790** [comment]
Toujours pas en Time out on peux clôturer 😁

**Comment by chrisb13790** [comment]
ce matin timeout

**Comment by chrisb13790** [comment]
[Uploading AbeilleLogs-221125.tar.gz…]()

**Comment by tcharp38** [comment]
Je ne peux pas recuperer le package.
Tu en fais un autre ?
Quel est le status la ?

**Comment by chrisb13790** [comment]
[AbeilleLogs-221205.tar.gz](https://github.com/KiwiHC16/Abeille/files/10155304/AbeilleLogs-221205.tar.gz)

**Comment by tcharp38** [comment]
Je vois que pour les 2 repeteurs, la valeur "rxOnWhenIdle" n'est pas bonne et vaut 0.
Mais d'ou vient cette valeur à la c... ?

Bascule sur la derniere beta (221204-BETA-1)
refait une interrogation reseau (reseau, 
![image](https://user-images.githubusercontent.com/35221038/205683882-7233640d-887c-4e05-811b-6b4a8d3cd473.png)

puis file moi les logs STP

Merci

**Comment by chrisb13790** [comment]
[AbeilleLogs-221205(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10156369/AbeilleLogs-221205.1.tar.gz)

**Comment by tcharp38** [comment]
Le 0020 (TRADFRI signal repeater suite) doit maintenant etre interrogé regulierement n'est ce pas ?

Par contre aucun signe de "TRADFRI signal repeater bureau". Il ne semble meme pas sur le reseau car l'interrogation ne le montre pas. Je me trompe ?

**Comment by chrisb13790** [comment]
les  2 sont sur le reseau , ils etaient operationnel , quand ils passaient en time out je fessait la commande Get-SWBuildID et ils repassaient en ok la ca ne marche plus

**Comment by tcharp38** [comment]
Celui du bureau ne semble plus dans le reseau. L'interrogation reseau devrait montrer qu'il est la mais ca n'est pas le cas.

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Quel est le status de ce sujet ?

**Comment by chrisb13790** [comment]
En berne
Je n ai pas eu le temps de m en occupé surtout qu un est dans une cloison ,
vu que je n arrive pas le réactiver en fessant la commande get swbuildid
alors qu avant ça marcher je te tiens au jus

**Comment by chrisb13790** [comment]
J ai relancer bureau en reapairant manuellement

Le mar. 13 déc. 2022 à 20:02, chris barcelone ***@***.***> a
écrit :

**Comment by chrisb13790** [comment]
les  2 sont sur le reseau , ils etaient operationnel , quand ils passaient en time out je fessait la commande Get-SWBuildID et ils repassaient en ok la ca ne marche plus
ce matin
[AbeilleLogs-221214.tar.gz](https://github.com/KiwiHC16/Abeille/files/10224704/AbeilleLogs-221214.tar.gz)

**Comment by tcharp38** [comment]
Il y a donc toujours un bug qq part car le repeater "TRADFRI signal repeater bureau" est repassé en rxOnWhenIdle=0.

Donc soit le bug est à l'inclusion soit + tard mais dans tous les cas je n'ai pas de trace la.

Je crois que j'ai un repeater à la maison qu'on vient de me filer. Je vais faire des essais.
Entre temps tu peux faire un refresh reseau et me filer les logs ?
Ca devrait corriger le pb de timeout du bureau.

A noter que je vois plusieurs devices impactés par le meme bug
- Ikea signal repeater
- Sonoff smart switch
- Xiaomi Single Switch Module T1

**Comment by tcharp38** [comment]
Pas de soucis avec mon repeater :(

**Comment by tcharp38** [comment]
@chrisb13790 
J'ai eu des soucis au final. Il est passé en timeout mais je sais pas pourquoi et n'etait plus joignable du tout.
Pourtant il etait toujours sur le reseau mais ne repondait plus.

J'ai fait une mise à jour OTA
http://fw.ota.homesmart.ikea.net/global/GW1.0/01.19.046/bin/10037603-3.1-TRADFRI-signal-repeater-2.3.086.ota.ota.signed
Tu devrais en faire de meme.

**Comment by chrisb13790** [comment]
Ok je m en occuperai dès que possible

**Comment by tcharp38** [comment]
Bon je reviens sur ce point.
Mon repeteur a encore dégagé sans aucune raison vers 23h hier. Pourtant il est regulierement interrogé mais ne repond plus.
Rien à faire distance. Il faut le debrancher et rebrancher pour qu'il soit à nouveau en vie.

Bref ma conclusion... de la merde. Aucune fiabilité.
Je ne vois pas d'autre solution que d'ignorer ce type de produit.

**Comment by tcharp38** [comment]
Je confirme à nouveau. Il est devenu "sans reponse" sans aucune raison apparente. Et pourtant plusieurs devices routés à travers lui, cassant ainsi une partie du reseau.

Cette fois je le vire.
Je clos le sujet. Faut pas perdre de temps sur ce routeur

**Comment by chrisb13790** [comment]
Salut je viens de jeter un oeil tous est encore en Timeout je crois que je
vais tous arrêter et trouver une autre solution plus on avance moins ça
marche

**Comment by tcharp38** [comment]
Tout y compris la zigate ?
Si non, mon repeteur Ikea viré.. mon réseau va mieux.

**Comment by chrisb13790** [comment]
Oui je t ai mis sur le bon topic le log et le dmesg

**Comment by chrisb13790** [comment]
Du coup tu utilise quoi a la place ?


Le jeu. 2 mars 2023 à 20:27, chris barcelone ***@***.***> a
écrit :

> Oui je t ai mis sur le bon topic le log et le dmesg
>
>

**Comment by tcharp38** [comment]
Encore rien à cet endroit mais clairment c'est de la daube. Pas fiable et la rien à faire en ce qui me concerne.
Donc soit des prise qui vont faire relais, soit chose que je n'ai pas encore testé, le repeteur Tuya.
Faut que je retrouve et le mette en service.
