### ISSUE TITLE
Xiaomi carre temp: % batterie

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#2507]
Le commit c392a808f100fcf33f6acf4fa64820310353a4e8 introduit la gestion des champs propriétaires xiaomi est en particulier le champ `0001-01-0021`
Sur les 4 types de devices xiaomi que j'ai,  sensor_86sw1, sensor_motion.aq2, sensor_magnet.aq2, weather, les deux premiers ont un % correct.

la remontée du champ `0001-01-0021` semble buggée sur ces devices. la valeur remontée est 100. Abeille logiquement, affiche ces valeurs.

la valeur recalculée est plus correcte: 
[2022-12-01 10:50:48]   Volt=3015, Volt%=64, Temp=1699, Humidity=5134, Pressure=102330

Je ne sais pas s'il est possible de traiter différement le % de batterie pour ces deux devices ....

```
==> /media/usb1/docker/jeedom/pluglog/AbeilleSerialRead1.log <==
[2022-12-01 10:50:48] Got "81020032A9C2674C010000FF01004200250121C70B0421A81305214C10062400000000006429A30665210E14662BBA8F01000A210000A5"

==> /media/usb1/docker/jeedom/pluglog/AbeilleParser.log <==
[2022-12-01 10:50:48] Abeille1, Type=8102/Attribute report, SQN=C2, Addr=674C, EP=01, ClustId=0000, AttrId=FF01, AttrStatus=00, AttrDataType=42, AttrSize=0025
[2022-12-01 10:50:48]   Xiaomi proprietary (Temp square sensor)
[2022-12-01 10:50:48]   Tag=01, Type=21/uint16, ValueHex=0BC7 => 3015 ==> min=2.85, max=3, 0001-01-0021=100
[2022-12-01 10:50:48]   Tag=04, Type=21/uint16, ValueHex=13A8 => 5032 (ignored)
[2022-12-01 10:50:48]   Tag=05, Type=21/uint16, ValueHex=104C => 4172 (ignored)
[2022-12-01 10:50:48]   Tag=06, Type=24/uint40, ValueHex=0000000000 => 0 (ignored)
[2022-12-01 10:50:48]   Tag=64, Type=29/int16, ValueHex=06A3 => 1699 ==> div=100, 0402-01-0000=16.99
[2022-12-01 10:50:48]   Tag=65, Type=21/uint16, ValueHex=140E => 5134 ==> div=100, 0405-01-0000=51.34
[2022-12-01 10:50:48]   Tag=66, Type=2B/int32, ValueHex=00018FBA => 102330 ==> 0403-01-0000=102330
[2022-12-01 10:50:48]   Tag=0A, Type=21/uint16, ValueHex=0000 => 0 (ignored)
[2022-12-01 10:50:48]   Volt=3015, Volt%=64, Temp=1699, Humidity=5134, Pressure=102330

==> /media/usb1/docker/jeedom/pluglog/Abeille <==
[2022-12-01 10:50:48][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/674C/01
[2022-12-01 10:50:48][DEBUG] :   'Battery-Percent' (0001-01-0021) => 100 %
[2022-12-01 10:50:48][DEBUG] :   Battery % reporting: 0001-01-0021, val=100
```
[AbeilleLogs-221201.tar.gz](https://github.com/KiwiHC16/Abeille/files/10134367/AbeilleLogs-221201.tar.gz)

**Comment by tcharp38** [comment]
Salut @edgd1er 
Oui j'ai introduit un systeme permettant de decrire les periph Xiaomi de maniere generique, sans retoucher le code.
En tout cas c'est l idée à terme.

Pour le pourcentage de batterie j'ai repris ce qui est appliqué chez zigbee-herdsman-converters.git, une des ref de code.
Xiaomi pour la plupart ne renvoi que la tension batterie.

3.015V pour une batterie 3V.. elle est pleine donc 100% ca me choque pas.
Le 64% comme avant ? Alors la oui ca ca me choque.

La formule est la suivante
                    $value2 = ($value2 - $min) / ($max - $min);
                    $value2 *= 100;
avec min=2.85V et max=3V

qu'en penses tu ?

**Comment by tcharp38** [comment]
J'ai trouvé un bug de ce sujet, puisqu'il faut appliquer une div par 1000 avant de convertir en %.
Le master est à jour mais ca ne change pas ce que j'ai ecris au dessus.

221202-BETA-1

Il faut juste faire un "reinitialiser" sur les modeles du type "weather" ou "magnet.aq2".. seuls modeles concernes pour l instant.

**Comment by edgd1er** [comment]
J'ai changé les piles en début d'année et j'aimerais bien qu'elles soient toujours à 100% mais ça ne me parait pas trop réaliste.
le résultat sera faux dans la mesure ou le max n'est pas 3V mais 3.135v.

D'ailleurs dans le code  il y a:
```
    public static function volt2pourcent($voltage) {
        $max = 3.135;
        $min = 2.8;
        if ($voltage / 1000 > $max) {
            log::add('Abeille', 'debug', 'Voltage remonte par le device a plus de '.$max.'V. Je retourne 100%.');
            return 100;
        }
        if ($voltage / 1000 < $min) {
            log::add('Abeille', 'debug', 'Voltage remonte par le device a moins de '.$min.'V. Je retourne 0%.');
            return 0;
        }
        return round(100 - ((($max - ($voltage / 1000)) / ($max - $min)) * 100));
    }
```

**Comment by tcharp38** [comment]
Ce 3.135 n'est absolument pas vrai.
Ca peut certe arriver que la batterie fasse plus que son voltage nominal, mais cette valeur est bidon et certainement pas constante pour toutes les batteries 3V.
Dire que 3.015V = 60% de capacité.. ben non pas d'accord. Avec cette formule et une batterie dont la tension neuve est juste un peu au dessus de 3V, tu n'es deja pas à 100%. Donc pas coherent.

Donc pour moi le plafond haut reste la tension nominale de la batterie, donc 3V dans la plupart des cas.

Pour le 2.8, ok, ca ca vient de l'experience qui semble dire qu'un device Xiaomi est mort si la tension tombe à 2.8.
L'equipe herdsman dit plutot 2.85 mais du coup on est dans la bonne tranche.

Tu me suis ?

**Comment by edgd1er** [comment]
D'après ce que tu dis la tension mesurée en sortie ne varie pas, hors ce n'est pas ce je j'avais retenu de mes cours de physiques.

Exemple sur des batteries:
https://pveducation.com/solar-concepts/battery-state-of-charge-vs-open-circuit-battery-voltage/

Le graph de cet article indique une décroissance de la tension en fonction du temps pour une pile: https://batteryuniversity.com/article/examining-loading-characteristics-on-primary-and-secondary-batteries

Les spécifications d'un pile maxwell 2032 assez commune, indique un voltage nominal a 3v, mais un peu plus a T0 et beaucoup moins après plusieurs heures 1000 heures à 15kOhm.
Une tension entre 3.2 et 2.8 est considérée normale pour le fonctionnement du device. En déça la tension n'est plus suffisante pour un fonctionnement correcte. 
Un calcul en pourcentage entre le 3.2 du début et le 2.8 permet d'estimer l'état de la pile.
Finalement, le pourcentage ne va varier qu'au début puis à la fin de la vie de la pile. mais c'est suffisant pour pouvoir anticiper les remplacements.

La, j'ai l'impression que tu proposes du 0/1. 1=100% jusqu'a arret du device (0%).
Que vois tu comme variation possible de cette valeur ?
SI le device est capable de remonter un pourcentage comment le determine t-il ?

**Comment by tcharp38** [comment]
> D'après ce que tu dis la tension mesurée en sortie ne varie pas, hors ce n'est pas ce je j'avais retenu de mes cours de physiques.

Non ca n'est pas ce que je dis. La tension varie d'un max vers 0, le max etant parfois un peu au dessus du nominal.
Mais ce + n'est notifié nul part. Une pile de 3V est garantie pour donner au moins 3V neuve, certainement pas 3.135 ou autre, sinon ca serait une pile 3.135 et non pas 3V.

Bref la formule ne change que coté max.. je considere qu'au dela du nominal c'est toujours 100%.
La valeur basse elle est critique. 2.8 ou 2.85 et le device est "mort"... donc on on report 0%.

En résumé je considere (et l'equipe hertzman-converter) que la plage est 2.85 (0%) => 3V (100%).
Abeille considerait 2.8 (0%) a 3.135 (100%).
Voila la diff, principalement sur cette valeur au dela du nominal.

**Comment by edgd1er** [comment]
ok, donc exit le datasheet de la pile CR2032, pourquoi pas.
le max devient 3V (100%), min reste passe à 2.85v. Dans les faits, pas sur que cela change grand chose. hormis une impression d'usure plus rapide, puisque la plage 100% sera plus étendue.
La mesure du voltage n'est plus disponible, il ne reste que la valeur recalculée du % ? (j'ai peut etre conservé par erreur des modifs sur mon fork)

**Comment by tcharp38** [comment]
Datasheet ?
Tiens je n'avais pas pensé à regarder.
Mais en voila qq extraits

![image](https://user-images.githubusercontent.com/35221038/206210482-f12e0373-fd58-4f1b-a49b-0c34fcd73602.png)

![image](https://user-images.githubusercontent.com/35221038/206210641-a6bef860-48fe-4d93-918f-0d6d62b37a4d.png)

Il n'est jamais mentionné que ca fait + que sa tension nominale (3V) dans ce cas.

Pour le retour du voltage effectivement je l'ai viré pour la simple raison qu'il y avait toujours un "recalcul" en % derriere.
Mais si tu penses que cette info est utile peut etre que je dois remettre ca, mais cette fois decorélé du %.

**Comment by tcharp38** [comment]
Salut @edgd1er 
On fait quoi avec ce sujet ?

**Comment by edgd1er** [comment]
Salut Tcharp,

J'avais commencé un message mais il s'est perdu, j'ai fait l'experience du peu d'utilité du calcul de pourcentage 3-2.8v, avec le rafraichissement la pile est passée de 100% a device hors réseau car éteint.
Du coup, le % calculé ne me semble pas fiable. Est il possible de remettre parmi les mesures disponibles la tension ?

**Comment by tcharp38** [comment]
Hmm.. pas cool ca mais je n'ai pas baissé le seuil bas. Au contraire il est passé à 2.85 au lieu de 2.8.
Autrement dit il devrait etre donné à 0% plus tot qu'avant.

Je compte bien remettre la tension mais je dois nettoyer du code avant.

**Comment by edgd1er** [comment]
ok, pas d'urgence, tu es demandé sur bien d'autres sujets, bon courage ;)

**Comment by tcharp38** [comment]
Salut @edgd1er 
Tres bonne année à toi.

Je viens de remettre la cmde info 'Battery-Volt' sur le "wether" et "sensor_magnet.aq2"
Voir 230106-BETA-1 dispo demain
Il faudra recharger le modele

**Comment by edgd1er** [comment]
Salut @tcharp38 
Meilleurs voeux aussi.
je regarde ça tt de suite, j'utilise le dépot direct dans le container ;)

**Comment by edgd1er** [comment]
Salut @tcharp38 
Meilleurs voeux aussi.
je regarde ça tt de suite, j'utilise le dépot direct dans le container ;)

**Comment by edgd1er** [comment]
je clos l'issue, tout est ok. merci

![image](https://user-images.githubusercontent.com/3601462/211160294-a08c1759-9e88-489f-a0c9-f48ab6af2999.png)
