### ISSUE TITLE
Perte d'un equipement qui est à 1m (@max5962)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#251]
Hello,ce n'est pas ma conclusion car j'ai un module à moins d'1 mètre de ma zigate et pourtant je le perd régulièrement.Je reçoit la semaine prochaine une nouvelle zigate pour valider que la première était défectueuse.En revanche ton hypothèse sur le leave envoyé me semble plus cohérent.Il faudrait alors pour les modules xiaomi un comportement différents quitte à s'éloigner du standard zigbee.

**Comment by KiwiHC16** [comment]
C'est un capteur d'ouverture 
J'ai que du V2 ( celui de droite https://community.smartthings.com/t/xiaomi-vs-aqara-door-window-sensors/90738 )

**Comment by KiwiHC16** [comment]
@max5962, je crois avoir lu que tu ne fonctionnes pas avec Jeedom mais avec une autre solution: "je dev sur home-assistant".
Peux tu confirmer ?

**Comment by max5962** [comment]
Bonjour.
Oui c'est tout à fait ça. Ça ne semble donc pas lié aux box domotiques.

**Comment by KiwiHC16** [comment]
Non, je ne vois aucune raison dans Abeille pour que cela le soit. Il faudrait soit sniffer soit avoir des log de la box. Je n'ai pas HA donc je ne peux aider.
Je clos donc le sujet. On le rouvrira si tu as des logs que je peux interpreter pour aider: Sniff ou Abeille.
