### ISSUE TITLE
perte device xiaomi aqara

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2511]
capteur de porte et sonde temperature
[AbeilleLogs-221205.tar.gz](https://github.com/KiwiHC16/Abeille/files/10155299/AbeilleLogs-221205.tar.gz)

**Comment by tcharp38** [comment]
Peut etre lie avec tes repeteurs en timeout.

**Comment by tcharp38** [comment]
@chrisb13790 
On fait quoi avec ce sujet ?

**Comment by chrisb13790** [comment]
Pour le moment pas de perte on peux fermer

**Comment by tcharp38** [comment]
A reouvrir si besoin
