### ISSUE TITLE
Aubess interrupteur zigbee 4 points (id = TS0044, _TZ3000_wkai4ga5)

### ISSUE THREAD

**Issue by arnoakavdb** [KiwiHC16/Abeille#2512]
Salut,
je viens d'acquérir deux nouveau interrupteur aubess zigbee reconnu par abeille mais sans aucunes commandes. L'interrupteur possède 4 boutons et chaque bouton possède 3 fonctions(press,long press,2 press)
![Screenshot_20221208-203052~2](https://user-images.githubusercontent.com/38015866/206553088-24f6d697-38a4-4f9d-9c86-6da96cb55723.png)
je vais poster les log de chaque boutons indépendamment car 12 fonctions sur le même log ca va faire beaucoup....
voici celui pour le bouton 1 : 
[AbeilleLogs-221208.tar.gz](https://github.com/KiwiHC16/Abeille/files/10189029/AbeilleLogs-221208.tar.gz)

20h51--|> simple pression bouton 1
20h52--|>double pression bouton 1
20h53--|>longue pression bouton 1

d'avance merci 👍

**Comment by arnoakavdb** [comment]
pour le bouton 2 ;

20h56--|> simple pression bouton 2
20h57--|>double pression bouton 2
20h58--|>longue pression bouton 2
[AbeilleLogs-221208 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10189075/AbeilleLogs-221208.1.tar.gz)

**Comment by arnoakavdb** [comment]
pour le bouton 3 ;

20h59--|> simple pression bouton 3
21h00--|>double pression bouton 3
21h01--|>longue pression bouton 3
[AbeilleLogs-221208 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/10189090/AbeilleLogs-221208.2.tar.gz)

**Comment by arnoakavdb** [comment]
pour le bouton 4 ;

21h02--|> simple pression bouton 4
21h03--|>double pression bouton 4
21h04--|>longue pression bouton 4
[AbeilleLogs-221208 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/10189112/AbeilleLogs-221208.3.tar.gz)

**Comment by arnoakavdb** [comment]
![aubess](https://user-images.githubusercontent.com/38015866/206673297-52abfb6e-506b-4b0c-bfcd-3bbf806a486c.png)
et voici l'image en png

**Comment by tcharp38** [comment]
Salut

Peux tu me generer un discovery via l'assistant ?
Merci

**Comment by arnoakavdb** [comment]
Ok je vais regarde a ça 👍

**Comment by arnoakavdb** [comment]
[discovery (1).zip](https://github.com/KiwiHC16/Abeille/files/10196272/discovery.1.zip)
17h03--|>bouton 1 simple pression
17h04--|>bouton 1 double pression 
17h05--|>appui long

dis moi si ce fichier est correct pour que je puisse faire la même chose pour les 3 autres boutons...
merci

**Comment by arnoakavdb** [comment]
Je ne sais pas si tu as déjà eu l'occasion de regarder au discovery?

**Comment by tcharp38** [comment]
Salut @arnoakavdb 
Je jettes un oeil.
Il y a une reference/modele sur ce produit ?

**Comment by tcharp38** [comment]
Pour test

A decompresser dans core/config/devices
[TS0044__TZ3000_wkai4ga5.zip](https://github.com/KiwiHC16/Abeille/files/10217462/TS0044__TZ3000_wkai4ga5.zip)


puis redemarrer Abeille et refaire inclusion

**Comment by arnoakavdb** [comment]
Je test ça en rentrant et je te tiens au courant.pour les références je vais regarder si je trouve un peu plus sur l'appareil

**Comment by tcharp38** [comment]
Verifie aussi qu'il supporte bien un appui long. Je ne le vois pas passer. On dirait que c'est juste "single" ou "double"

**Comment by arnoakavdb** [comment]
ok je referais un discovery alors pour le long press mais oui il est disponible 
![Screenshot_20221213-125601](https://user-images.githubusercontent.com/38015866/207311774-6fefcebf-f069-4f93-8299-997fa8aa02c3.png)

**Comment by tcharp38** [comment]
Non laisse tomber le discovery il n'apportera rien de + maintenant
Il faut les logs au bon moment avec l' heure precise de l'action

**Comment by arnoakavdb** [comment]
Ok ok je fais ça pour les 3 actions sur les quatres boutons avec l'heure précise

**Comment by tcharp38** [comment]
Surtout le mode "long press", et un seul bouton ca suffira.
Les autres sont identiques sur des EP differents.

Mais teste d'abord. Il se  peut que ca fonctionne deja.. click = single, double ou long

**Comment by arnoakavdb** [comment]
[AbeilleLogs-221213.tar.gz](https://github.com/KiwiHC16/Abeille/files/10221281/AbeilleLogs-221213.tar.gz)
voilq a 20h01 j'ai fait plusieur long press.
Pour les references j'ai ceci : 
ESW-0ZAA-EU & RSH-ZigBee-SC04

encore merci pour tout

**Comment by tcharp38** [comment]
Bon donc à priori le click "long" remonte aussi.
Donc tout est bon ?

**Comment by arnoakavdb** [comment]
oui parfait tout est fonctionnel :-) encore un grqnd merci pour le suivi du plugin

**Comment by tcharp38** [comment]
Ok cool.
Je te laisse clore le sujet quand tu es sur que tout est bon.
Tout sera dans la beta de demain.

**Comment by arnoakavdb** [comment]
je viens de tout mettre en place via scenario, tout est parfait on peut cloturer.Merci
