### ISSUE TITLE
PaulmannLichtGmbH-Dimmablelight 500.44 (id = Dimmablelight, PaulmannLichtGmbH)

### ISSUE THREAD

**Issue by cbenji59** [KiwiHC16/Abeille#2516]
Bonjour,

Serait-il possible d'ajouter ce materiel.
PaulmannLichtGmbH-Dimmablelight 500.44

[PaulmannLichtGmbH-Dimmablelight 500.44.zip](https://github.com/KiwiHC16/Abeille/files/10189187/PaulmannLichtGmbH-Dimmablelight.500.44.zip)

Je n'ai pas été capable d'obtenir plus d'information sur ce module, même en le ré-incluant, rafraichissant plusieurs fois l'information.

S'il n'est pas possible de l'intégrer, ce n'est pas un soucis pour moi. Il ne s'agit que d'un seul équipement donnée par un ami.

Le fichier zip contient le fichier discovery.json, un screenshot du pluggin pour les références et une image pour l'icone.

Merci par avance

**Comment by tcharp38** [comment]
Celui la ca va etre plus compliqué vu que le discovery est vide. Aucune info utile.

Tu peux tenter une nouvelle decouverte avec l'assistant ?
Il se passe quoi ? Tous les voyants sont au vert ou pas ?

**Comment by cbenji59** [comment]
Salut!

J'ai retenté une découverte, et même chose.
Ce-dessous le screenshot de l'assistant - rien ne se passe quand je clique plusieurs fois sur les flèches oranges.
![image](https://user-images.githubusercontent.com/120128547/206842170-cea97f93-bd3f-4a02-954b-a7a0f6a4f6a2.png)

Ci-dessous le nouveau fichier json (qui doit être identique à celui téléchargé initialement)
[discovery (2).zip](https://github.com/KiwiHC16/Abeille/files/10199566/discovery.2.zip)

Pour information:
J'ai pu voir que ce module n'est pas supporté par la Zigate.
Aussi, j'ai utilisé ce module sur Philips Hue.

_Je me répète, mais s'il est impossible de l'intégrer, ce n'est pas un soucis. Il s'agit d'un unique module inutilisé chez moi pour le moment._

Merci beaucoup de ton aide!

**Comment by tcharp38** [comment]
Tiens, un modele "fait main", pour test.

A decompresser dans core/config/devices
[Dimmablelight_PaulmannLichtGmbH.zip](https://github.com/KiwiHC16/Abeille/files/10209134/Dimmablelight_PaulmannLichtGmbH.zip)

puis redemarrer Abeille
refaire inclusion
tester

Il me manquera une image PNG sans arriere plan.

**Comment by cbenji59** [comment]
Salut! Merci de ton aide!
Je regarde cela ce weekend et reviens vers toi!
Merci!

**Comment by tcharp38** [comment]
Salut @cbenji59 
Ce sujet commence à dater.
Toujours interessé ?
Si oui quel est le status ?
Merci

**Comment by tcharp38** [comment]
@cbenji59 
J'imagine que tu as migré sur une autre solution.
Je clos ce sujet mais à réouvrir si ca interesse qqn.

**Comment by cbenji59** [comment]
Hey @tcharp38,

Désolé, je n'ai pas été actif de ce côté là.
Tu peux fermer le sujet sans soucis, le module n'étant pas actuellement
utilisé.
Je reviendrais sur ce thread ultérieurement si jamais j'avais absolument
besoin de celui-ci.

Merci de ton aide!

**Comment by tcharp38** [comment]
Hello
Ok donc toujours utilisateur d'Abeille.
A bientot

**Comment by cbenji59** [comment]
>
> Exact ! Et tout marche nickel !
Merci!
