### ISSUE TITLE
Réseau abeille actualisation

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2518]
Salut,

Suite à un souci de perte de nombreux équipements de mon réseau, j'ai du réintégrer quasiment l'ensemble de mes équipements.

Je cherche toujours à comprendre pourquoi et je me demande si ce n'est pas un problème de porté du signal ou que ma zigate fatigue... J'ai rajouté une prise faisant relais pour renforcer le maillage.

Depuis cet événement, je n'arrive plus à faire l’actualisation du réseau :
![image](https://user-images.githubusercontent.com/26632961/207008957-adc4f679-01dd-40a4-9cf7-dc371bb92b69.png)
En forcent la réinterrogation, cela remonte 2-3 équipement et souvent aucun.

J'ai aussi remarqué une latence assez importante (1 à 2s) lors de l'activation d'un lumière par exemple et surtout que sur l'interface jeedom cela met plus 4-5s à actualiser le status de la lumière. Cette lumière a une vue directe sur l'antenne qui est à 5 mètres environs.

Cette lumière fait partie d'un groupe (virtuel) de lumière, j'ai créé un équipement virtuel qui me permet de piloter les deux ampoules en même temps. lorsque j'allume par le groupe, la lumière 1 s'allume et la seconde met 1 à 2s de plus pour s'allumer. Je n'avais pas ce comportement avant mon problème.

[AbeilleLogs-221212.tar.gz](https://github.com/KiwiHC16/Abeille/files/10206562/AbeilleLogs-221212.tar.gz)

Merci pour ton aide.

**Comment by tcharp38** [comment]
Salut.
La premiere chose à faire est de s'assurer que les "repeteurs" (donc prise/volet roulant ou autre sur secteur) ne sont pas en timeout.

je regarde un peu tes logs

**Comment by toat** [comment]
J'ai fait la dernière maj beta et je constate une net amélioration de la réactivité. Mes deux ampoules s'allument en même temps. J'ai aussi retrouver mes équipements dans la partie réseau abeille.

**Comment by tcharp38** [comment]
J'aime ce genre de commentaires :) sinon c'est desesperant.
La derniere beta de l'année est celle du jour. Je suis hors ligne jusqu'au 2 alors j'espere qu'il n'y aura pas de gros soucis entre temps.

**Comment by tcharp38** [comment]
I'm back !
Tres bonne année.

Tu en es ou sur ce sujet ?

**Comment by toat** [comment]
Bonne année a toi aussi.

C'est très stable en ce moment. Côté réseau, cela remonte bien.

Est-ce que cela peut être liée à la MAJ beta ? Faut-il pas que je repasse en stable si j'ai plus de problème ?

Merci.

**Comment by tcharp38** [comment]
Salut

Concernant ce sujet, les evolutions doivent normalement nettoyer et améliorer les choses donc ca pourrait expliquer, bien qu'il n'y ait pas vraiment de piste la. Bref c'est "tombé en marche"... tant mieux.

Si tu n'as plus de supports en cours, tu peux rester en stable.
Par contre si encore besoin de support, reste en beta. Tes retours me permettront de corrger des choses au passage.
