### ISSUE TITLE
Réinitialisation volets et BSO Profalux

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2519]
Hello @tcharp38 

Comme échangé ensemble, j'ouvre une issue suite à la suppression par erreur d'une commande sur l'un de mes volets. J'ai donc réalisé un "Réinitialiser" dans l'onglet Avancé mais les commandes 'UP" et "Down" ne remontrent pas !
J'ai essayé en supprimant toutes les commandes. Sans succès. 
J'ai également fait la même opération sur d'autres volets et BSO et même souci. Il manque ces commandes et parfois même la commandes "CurrentLevel". 
De ce que je vois, il s'agit surtout des commandes qui ont été renommées entre mon inclusion et les nouveaux modèles (Monter -> Up  Descendre -> down  Level -> CurrentLevel).

Peux tu jeter un oeil ? En PJ le log vider avant la réinitilisation du volet "Salle à manger).
J'aimerais éviter de devoir tout réinclure :)

Merci d'avance

Xav 

[AbeilleLogs-221212.tar.gz](https://github.com/KiwiHC16/Abeille/files/10208277/AbeilleLogs-221212.tar.gz)

**Comment by Xav-74** [comment]
Edit : je viens de refaire des tests ! 
Le problème venait de la personne entre la chaise et le clavier :)
En fait, je faisais un "réinitialiser" qui créait bien les commandes mais je ne quittais pas l'équipement sans le sauver ! Or si je sauvegarde, les commandes up & down n'étaient pas affichées donc supprimer au final !

Désolé du dérangement. Ca pourra au pire servir à certains :)

Xav

**Comment by tcharp38** [comment]
:)
J'aime les pbs qui s'ouvrent et se referment aussitot. Oufff
