### ISSUE TITLE
Calibrage position volet (fille de #114)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#252]
setLevel = 2 * % ouverture + 75

setLevel = a * (% ouverture) + b

avoir a et b modifiable par l utilisateur.

Ou une methode auto de calibrage.

**Comment by KiwiHC16** [comment]
Je viens de mettre le code.
Deux manip a faire:
- mettre a jour avec le master
- modifier l'objet volet
-- soit en le supprimant et le recreant
-- soit en changeant le commande setLevel par setLevelVolet (CmdAbeille/#addr#/setLevelVolet=>CmdAbeille/#addr#/setLevel)

Ensuite tu peux jouer avec la formule dans le fichier AbeilleMQTTCmd.php en ligne 241-264.

**Comment by dams74** [comment]
Parfait!
Du coup tu as mis quoi comme formule et valeur?
Edit: Trouvé!
Attention Pour un set level (level en %)
a = -0.0084
b = 3.04
c = 35
level = level * level * a + level * b + c

Et Pour un get level (level de 0 à 255):
a=0.00081872
b=0.2171167
c=-8.60201639
level = level * level * a + level * b + c

Lorsque tu fait Setlevel on envoie une valeur en % avec le slider?
Donc il faut appliquer la première formule quand on fait un setlevel

**Comment by KiwiHC16** [comment]
la formule en polynôme du second degré avec a, b et c mais je ne peux pas tester alors la probabilité que ca marche du premier coup est faible

**Comment by dams74** [comment]
ok j'essaie ça dans la soirée

**Comment by dams74** [comment]
Avec le volet en position central:
Je fais un get level: valeur remonté= 0
Abeille Parser
```
AbeilleParser 2018-05-24 18:56:57[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0C
AbeilleParser 2018-05-24 18:56:57[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-05-24 18:56:57[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 0C; Src Addr : cc3e; End Point : 01; Cluster ID : 0008; Attr ID : 0000; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 01
```

Abeille MQTTCmd
```
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]Msg Received: Topic: {CmdAbeille/cc3e/ReadAttributeRequest} => clusterId=0008&attributeId=0000
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]Type: CmdAbeille Address: cc3e avec Action: ReadAttributeRequest
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]processCmd call with: ReadAttributeRequest-1-address-cc3e-clusterId-0008-attributeId-0000-
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]data: 02cc3e0101000800000000010000
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]len data: 28
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]Dest:/dev/ttyUSB0 cmd:0100 len:000E datas:02cc3e0101000800000000010000
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]len data: 28
AbeilleMQTTCmd 2018-05-24 18:59:03[DEBUG]checksum computed: 246
```

Tu as besoin d'autre chose en log?

**Comment by KiwiHC16** [comment]
Recuperes le dernier master, je viens de changer un peux la formule. Est ce que le volet bouge ? Est ce qu'il se met à la bonne hauteur ?

**Comment by dams74** [comment]
Ok j'essaie de tester ça demain. Sinon le set level ne fait pas déplacer le volet et le get level ne remonte pas de valeurs.

**Comment by zoozbiro** [comment]
Voici quelques retour : 

version abeille : `0f1740ae7d99b0f311be331e49b281c23c045f03`

position du curseur central, le volet est quasiment fermé

log abeilleParser : 

```
[2018-05-25 13:31:46][DEBUG] : Envoi du message Level=50&duration=01 vers CmdAbeille/a69b/setLevelVolet
[2018-05-25 13:31:46][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/setLevelVolet', ... (20 bytes))
[2018-05-25 13:31:46][DEBUG] : --- process a new message -----------------------
[2018-05-25 13:31:46][DEBUG] : Message ->Level=50&duration=01<- sur CmdAbeille/a69b/setLevelVolet
```

log abeilleMQTTCmd : 

```
[2018-05-25 13:31:46][DEBUG] : Envoi du message Level=50&duration=01 vers CmdAbeille/a69b/setLevelVolet
[2018-05-25 13:31:46][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/setLevelVolet', ... (20 bytes))
[2018-05-25 13:31:46][DEBUG] : --- process a new message -----------------------
[2018-05-25 13:31:46][DEBUG] : Message ->Level=50&duration=01<- sur CmdAbeille/a69b/setLevelVolet
```

**Comment by KiwiHC16** [comment]
dans abeilleMQTTCmd on devrait avoir un log avec "level255:".
As tu supprimé l'objet Volet dans Jeedom et re-créé ? (Premiere solution)
Ou tu va dans les commandes et tu changes setLevel par setLevelVolet (deuxieme solution).

Si tu as "level255:" dans le log c'est que la bonne commande est prise en compte. Ensuite tu peux adapter la formule dans AbeilleMQTTCmd.php en ligne 256 (a, b, c a modifier). Ou carrement mettre une autre formule comme calculé dans #114 .Perso je ne peux pas le faire je n'ai pas de volet Profalux.

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-05-25 a 14 40 37](https://user-images.githubusercontent.com/8549674/40544735-a0a37514-6029-11e8-86b1-aefe1007aee8.png)

**Comment by zoozbiro** [comment]
Oui c'est bon j'ai le level est j'arrive à modifier les valeurs dans le fichier AbeilleMQTTCmd.php. J'essaie de modifier les valeurs de la formule.

**Comment by KiwiHC16** [comment]
La formule que j'avais estimée dans #114 etait Level = 2 * % ouverture + 75
Pour ca il faut a=0, b=2 et c=75, sauf erreur.

**Comment by zoozbiro** [comment]
Bon je sèche un peu... j'ai faits plusieurs tests, la formule en l'état fait bouger le volet mais pas correctement, en gros le volet reste quasiment tout le temps quasiment fermé...(légèrement ajouré) par contre j'ai constaté que le setlevel255 passé directement en paramètre à un résultat par loin de la vérité...
Alors voici les résultats des tests. pour un setlevel à 50% le volet est quasiment fermé légèrement ajouré 
Abeille : 

```
`[2018-05-28 20:46:51][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver sending PINGREQ
[2018-05-28 20:46:51][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PINGRESP
[2018-05-28 20:47:00][DEBUG] : Envoi du message Level=51&duration=01 vers CmdAbeille/a69b/setLevelVolet
[2018-05-28 20:47:00][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/setLevelVolet', ... (20 bytes))
[2018-05-28 20:47:00][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:47:00][DEBUG] : Message ->Level=51&duration=01<- sur CmdAbeille/a69b/setLevelVolet`
```

AbielleMQTTcmd : 

```
`AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]Msg Received: Topic: {CmdAbeille/a69b/setLevelVolet} => Level=51&duration=01
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]Type: CmdAbeille Address: a69b avec Action: setLevelVolet
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]level255: 143
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]level: 22
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]processCmd call with: setLevel-1-addressMode-02-address-a69b-destinationEndpoint-01-Level-22-duration-01-
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]Dest:/dev/ttyUSB0 cmd:0081 len:0009 datas:02a69b010101160001
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]len data: 18
AbeilleMQTTCmd 2018-05-28 20:47:00[DEBUG]checksum computed: 161`
```


GetLevel Abeille : 

```
`[2018-05-28 20:50:57][DEBUG] : Envoi du message clusterId=0008&attributeId=0000 vers CmdAbeille/a69b/ReadAttributeRequest
[2018-05-28 20:50:57][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/ReadAttributeRequest', ... (31 bytes))
[2018-05-28 20:50:57][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:57][DEBUG] : Message ->clusterId=0008&attributeId=0000<- sur CmdAbeille/a69b/ReadAttributeRequest
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/0008-0000', ... (2 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->22<- sur Abeille/a69b/0008-0000
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/Time-TimeStamp', ... (10 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->1527533458<- sur Abeille/a69b/Time-TimeStamp
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/Time-Time', ... (19 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->2018-05-28 20:50:58<- sur Abeille/a69b/Time-Time`
```

getlevel AbeilleMQTTcmd : 

```
`[2018-05-28 20:50:57][DEBUG] : Envoi du message clusterId=0008&attributeId=0000 vers CmdAbeille/a69b/ReadAttributeRequest
[2018-05-28 20:50:57][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/ReadAttributeRequest', ... (31 bytes))
[2018-05-28 20:50:57][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:57][DEBUG] : Message ->clusterId=0008&attributeId=0000<- sur CmdAbeille/a69b/ReadAttributeRequest
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/0008-0000', ... (2 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->22<- sur Abeille/a69b/0008-0000
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/Time-TimeStamp', ... (10 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->1527533458<- sur Abeille/a69b/Time-TimeStamp
[2018-05-28 20:50:58][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'Abeille/a69b/Time-Time', ... (19 bytes))
[2018-05-28 20:50:58][DEBUG] : --- process a new message -----------------------
[2018-05-28 20:50:58][DEBUG] : Message ->2018-05-28 20:50:58<- sur Abeille/a69b/Time-Time`
```

Je continue à creuser... :)

**Comment by KiwiHC16** [comment]
Et si tu mets a=0, b=1 et c=0 ?

**Comment by zoozbiro** [comment]
J'ai donc testé avec ces paramètres, pour un setLevel à 50% le volet est fermé à 1,4m sur un volet de 220 environ.

Voici les logs 

Abeille :
`[2018-05-30 20:17:55][DEBUG] : Envoi du message Level=49&duration=01 vers CmdAbeille/a69b/setLevelVolet
[2018-05-30 20:17:55][DEBUG] : Mosquitto: Log level: 16 Message: Client jeedom_pub_deamon_Loop_ForEver received PUBLISH (d0, q0, r0, m0, 'CmdAbeille/a69b/setLevelVolet', ... (20 bytes))
[2018-05-30 20:17:55][DEBUG] : --- process a new message -----------------------
[2018-05-30 20:17:55][DEBUG] : Message ->Level=49&duration=01<- sur CmdAbeille/a69b/setLevelVolet`

AbielleMQTTcmd :

`AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]Msg Received: Topic: {CmdAbeille/a69b/setLevelVolet} => Level=49&duration=01
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]Type: CmdAbeille Address: a69b avec Action: setLevelVolet
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]level255: 124
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]level: 124
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]processCmd call with: setLevel-1-addressMode-02-address-a69b-destinationEndpoint-01-Level-124-duration-01-
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]Dest:/dev/ttyUSB0 cmd:0081 len:0009 datas:02a69b0101017c0001
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]len data: 18
AbeilleMQTTCmd 2018-05-30 20:17:55[DEBUG]checksum computed: 203`

Je vais essayer de faire varié B pour voir si j'arrive à un résultat correct

**Comment by dams74** [comment]
@zoozbiro  tu as le widget slider value qui te permet d'afficher la valeur sur le slider lorsque tu le déplaces.
de mon côté je vais essayé de faire quelques test vendredi matin.

**Comment by zoozbiro** [comment]
Oui j'utilise SlidVertical pour avoir une valeur précise, mes tests d'hier ne sont pas très concluants. J'ai utilisé la 1.2 pour un set value à 50% c'est ok par contre 80% et 20% ca ne correspond pas vraiment. Je vais essayer un peu ce soir et demain aussi.

**Comment by dams74** [comment]
J'ai un peu de temps ce matin
Alors j'ai mis ça:
a = -0.0084
b = 3.04
c = 35
level = level * level * a + level * b + c
Pour un envoie de commande à 50% le résultat que je calcul est 166

Le log: 
```
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]Msg Received: Topic: {CmdAbeille/9ce1/setLevelVolet} => Level=50&duration=01
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]Type: CmdAbeille Address: 9ce1 avec Action: setLevelVolet
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]level255: 127
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]level: 255
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]processCmd call with: setLevel-1-addressMode-02-address-9ce1-destinationEndpoint-01-Level-255-duration-01-
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]Dest:/dev/ttyUSB0 cmd:0081 len:0009 datas:029ce1010101ff0001
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]len data: 18
AbeilleMQTTCmd 2018-06-01 08:14:02[DEBUG]checksum computed: 8
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]Msg Received: Topic: {CmdAbeille/9ce1/Annonce} => Default
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]Type: CmdAbeille Address: 9ce1 avec Action: Annonce
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]Preparation de la commande annonce pour default
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]processCmd call with: ReadAttributeRequest-1-address-9ce1-clusterId-0000-attributeId-0005-
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]data: 029ce10101000000000000010005
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]len data: 28
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]Dest:/dev/ttyUSB0 cmd:0100 len:000E datas:029ce10101000000000000010005
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]len data: 28
AbeilleMQTTCmd 2018-06-01 08:15:03[DEBUG]checksum computed: 116
```

Le volet s'ouvre en grand.
Faut-il faire une manipulation lorsque l'on modifie AbeilleMQTTCmd.php  pour que ce soit pris en compte?
J'ai modifié les valeur et ça fait le même résultat

Edit:
 je pense qu'il faut rebooté pour que les valeurs soient prise en compte. Je teste de nouveau.
Je ne suis pas sur que le calcule fonctionne
En mettant les même valeurs qu'en début de ce post  le résultat dans le log est toujours 255.
Par contre si je met a=0 et b=0 et c=166 soit le résultat pour un demande à 50%.
Lorsque j'envoie c=166 le volet se met bien au milieu

**Comment by zoozbiro** [comment]
Oui tu dois redémarrer le démon pour que les modifications dans le fichier soit prise en compte, je vais tester les même valeur. Comment fais tu pour obtenir ces valeurs ?

**Comment by dams74** [comment]
C'est le fruit de nombreuses recherche pour faire fonctionner mes volet profalux en zigbee.
Lors de ces recherches je suis tombé sur un article (http://www.domotique-info.fr/2014/09/installation-domotique-pascal-d/) où pascal fait fonctionner ses volets avec une clé télégésys zigbee et un programme en python. La formule est dans son programme python.(https://github.com/dams74/ProfaluxAPI/blob/master/ProfaluxApi.py)
Je me suis dit si ça fonctionne pour lui ça devrai fonctionner pour nous

**Comment by KiwiHC16** [comment]
Oui apres changement des valeurs il faut faire un restart du plugin.

**Comment by KiwiHC16** [comment]
@dams74, es tu toujours avec le même volet ? Peux tu me confirmer que les valeurs suivantes sont valables sur ton volet (C'est tes données dans l issue #114):
Volet à 0% ouvert: 0x01
volet à 10 % ouvert:0x3E
volet à 20% ouvert: 0x5c
volet à 30% ouvert:0x74
volet à 40% ouvert:0x8C
volet à 50% ouvert:0xA2
volet à 60% ouvert:0xB7
volet à 70% ouvert:0xC9
volet à 80% ouvert:0xDB
volet à 90% ouvert:0xEE
volet à 100% ouvert:0xFE

@zoozbiro, peux tu me donner les valeurs pour ton volet ? (Voir issue #114 pour les récupérer).

**Comment by KiwiHC16** [comment]
En ssh sur la machine envoie les commandes suivantes:
mosquitto_pub -h localhost -m "Level=99&duration=01" -t "CmdAbeille/7191/setLevel"

Tu remplaces 99 par un valeur entre 01 et 99.
Tu remplaces  7191 par l'adresse du volet.

 et si le volet bouge tu notes sa hauteur.

**Comment by dams74** [comment]
Oui je suis toujours sur le même volet. J'ai pas revérifier les valeurs mais elles étaient bonnes à l'époque. Je pourrai contrôler à nouveau la semaine prochaine.

**Comment by zoozbiro** [comment]
Alors voici les valeurs, mon volets fais environ 220cm j'ai mis à chaque le log data.... je ne sais pas si tu vas en avoir besoin. Dis moi si je peux faire d'autre test. J'ai un peu de temps encore jusqu'en fin/millieu d'aprem



Volet à 0% fermé:                        datas:02a69b010101000001
volet à 10 % fermé (ajouré)        datas:02a69b010101190001
volet à 20% fermé de 200cm     datas:02a69b010101330001
volet à 30% fermé de 180cm     datas:02a69b0101014c0001
volet à 40% fermé de 160cm     datas:02a69b010101660001
volet à 50% fermé de 140cm     datas:02a69b0101017f0001
volet à 60% fermé de 120cm     datas:02a69b010101990001
volet à 70% fermé de 90cm       datas:02a69b010101b20001
volet à 80% fermé de 60cm       datas:02a69b010101cc0001
volet à 90% fermé de 30cm       datas:02a69b010101e50001
volet à 100% ouvert:                   datas:02a69b010101ff0001

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-06-01 a 14 21 52](https://user-images.githubusercontent.com/8549674/40840592-a3cb2218-65a7-11e8-9e29-27dc391c0b1d.png)

a = 0,714285714
b = 0,285714286
c = 0

En vert la courbe avec le coefficient que j'ai calculés. Reste à mettre dans le code. La tout est en pourcent alors que setLevel dans le code ne l'ai pas. Une petite regle de trois à faire.

**Comment by zoozbiro** [comment]
Cool c'est top! Du coup il ne faut plus utiliser setLevelVolet pour tester ?

**Comment by KiwiHC16** [comment]
setLevel = function( setLevelVolet )

**Comment by KiwiHC16** [comment]
Je viens de pousser une nouvelle version dans le master. Essayez et dites moi.

**Comment by zoozbiro** [comment]
Merci pour le taf Ben,  j'essaie de faire des tests dans la semaine et je te tiens au courant.

**Comment by KiwiHC16** [comment]
Retour d expérience ?

**Comment by dams74** [comment]
Désolé pour le délai des tests.
De mon côté c'est parfait

**Comment by KiwiHC16** [comment]
Ok dans ce cas je clos, et dans les prochains jours je vais regarder le stop et apres le retour d etat.
