### ISSUE TITLE
Sonde température et humidité HT-EF-3.0_HEIMAN intégration

### ISSUE THREAD

**Issue by brutusangel** [KiwiHC16/Abeille#2520]
Bonjour
j'essaie d'intégrer un sonde de température/humidité HT-EF-3.0_HEIMAN , mais je n'y arrive pas.
voici un lien descriptif: https://zigbee.blakadder.com/Heiman_HS1HT.html
Je joint le fichier discovery en annexe.
Mon système tourne sur RPI3 avec Pizigate et jeedom ver4.
Pouvez-vous m'aider?..
Merci
[discovery-HT-EF-3.0_HEIMAN.zip](https://github.com/KiwiHC16/Abeille/files/10210430/discovery-HT-EF-3.0_HEIMAN.zip)

**Comment by tcharp38** [comment]
[HT-EF-3.0_HEIMAN.zip](https://github.com/KiwiHC16/Abeille/files/10211587/HT-EF-3.0_HEIMAN.zip)
A decompresser dans core/config/devices
redemarrer Abeille
refaire inclusion

J'ai besoin aussi d'une image PNG sans arriere plan de bonne qualité

**Comment by brutusangel** [comment]
j'ai intégré, mais pas de changement.
Voici une image du capteur. 

![41RW-6rgYOL](https://user-images.githubusercontent.com/92653196/207180768-457a401a-b354-4efc-a492-ff056d73b590.jpg)

j'ai refais un discovery et je joins un log
[AbeilleLogs-221213.tar.gz](https://github.com/KiwiHC16/Abeille/files/10212866/AbeilleLogs-221213.tar.gz)

[discovery-HT-EF-3.0_HEIMAN.zip](https://github.com/KiwiHC16/Abeille/files/10212839/discovery-HT-EF-3.0_HEIMAN.zip)

**Comment by tcharp38** [comment]
Le modele n'a pas été trouvé lors de l'annonce du device.
Soit tu ne l'as pas mis au bon endroit (core/config/devices)
soit tu n'as pas redemarré Abeille

Mais bascule sur la beta du jour qui le contient et tu peux rententer

**Comment by tcharp38** [comment]
J'ai pris l'image et converti en PNG mais l'arriere plan est a effacer. Je te laisse t'y coller. Merci

**Comment by brutusangel** [comment]
Super , ça fonctionne j'ai la température et l'humidité. 

Pour l'image:
je n'ai pas trouvé l'image que tu me cite,. Je joins une image, j'ai réduis le fond blanc (avec paint), mais je ne sais pas si cela te suffit.  

![HEIMAN](https://user-images.githubusercontent.com/92653196/207450247-ac2c9499-effd-4f22-869e-7a5cc26aafcd.png)

**Comment by tcharp38** [comment]
Je prends l'image merci.
Si tout est ok, je te laisse clore le sujet.

**Comment by brutusangel** [comment]
En fait, je viens de le voir, 
il  n'y a pas l'affichage du % de la batterie dans analyse-équipements et je ne vois rien non plus, dans l'équipement et onglet commandes
[AbeilleLogs-221213 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10222654/AbeilleLogs-221213.1.tar.gz)

**Comment by tcharp38** [comment]
Effectivement. Mauvais endpoint.

Teste avec ce modele
[HT-EF-3.0_HEIMAN.json.zip](https://github.com/KiwiHC16/Abeille/files/10222783/HT-EF-3.0_HEIMAN.json.zip)

Je l'ai poussé dans la beta 221214-BETA-1 mais pas sur que ce soit celle qui est prise en compte pour aujourd hui.

**Comment by brutusangel** [comment]
j'ai placé le fichier décompressé dans le répertoire, core/config/devices  HT-EF-3.0_HEIMAN, 
relancé, abeille, inclusion , mais pas de changement.
j'essayerais avec la beta que tu as poussé cet après midi.
Voici mon dernier log , après avoir intégré le fichier dans le répertoire.
[AbeilleLogs-221214.tar.gz](https://github.com/KiwiHC16/Abeille/files/10222937/AbeilleLogs-221214.tar.gz)

**Comment by brutusangel** [comment]
Bonjour,
Je viens de voir que c'est bon, (j'aurais du attendre ) car c'est bon et sans mettre a jour la beta. 
Merci pour le support
Je clos le sujet.

**Comment by tcharp38** [comment]
Je suis sceptique que tout soit bon cote souci timeout mais ca n'est pas specifique Heiman pour le coup.

**Comment by brutusangel** [comment]
Image sans fond...
![HEIMAN-removebg-preview](https://user-images.githubusercontent.com/92653196/207737348-d1080d05-4f57-4afa-878f-491fc2279c86.png)

**Comment by tcharp38** [comment]
C'est integré. Merci
