### ISSUE TITLE
 capteur HEIMAN HS1MS-EF (id = PIRSensor-EF-3.0, HEIMAN)

### ISSUE THREAD

**Issue by brutusangel** [KiwiHC16/Abeille#2521]
Bonjour
j'essaie d'intégrer un capteur de mouvement HEIMAN , mais je n'y arrive pas.
voici un lien descriptif: https://www.zigbee2mqtt.io/devices/HS1MS-EF.html.
Je joint le fichier discovery en annexe, une image
Mon système tourne sur RPI3 avec Pizigate et jeedom ver4.
Pouvez-vous m'aider?..
Merci
[AbeilleLogs-221214.tar.gz](https://github.com/KiwiHC16/Abeille/files/10227667/AbeilleLogs-221214.tar.gz)
[discovery-PIRSensor-EF-3.0_HEIMAN.zip](https://github.com/KiwiHC16/Abeille/files/10227668/discovery-PIRSensor-EF-3.0_HEIMAN.zip)

![HS1MIS-EF](https://user-images.githubusercontent.com/92653196/207592965-d39e11b8-a809-4715-a94e-8671956022d3.PNG)

**Comment by tcharp38** [comment]
Tester le modele de la beta de demain 221214-BETA-7

**Comment by brutusangel** [comment]
Ok.. j'attends la mise a jour.. 
Cette image te convient mieux?... elle est sans fond...

![HS1MIS-EF-removebg-preview](https://user-images.githubusercontent.com/92653196/207723399-a082ccfe-9eb7-4a31-9b12-cea564430a50.png)

**Comment by tcharp38** [comment]
C'est intégré.
Merci

**Comment by brutusangel** [comment]
J'ai remis à jour avec la beta et presque tout est en ordre.
La seule chose que ne fonctionne pas, c'est l'état.  L'état ne change pas quand il y a un mouvement  (la diode led du capteur fonctionne) .
je te joint le log...
[AbeilleLogs-221215.tar.gz](https://github.com/KiwiHC16/Abeille/files/10236235/AbeilleLogs-221215.tar.gz)

**Comment by tcharp38** [comment]
Salut @brutusangel 
Bonne année !

Peux tu 
- declencher une detection de mouvement
- noter l heure precise
- et me filer les logs ?

**Comment by brutusangel** [comment]
Bonjour, 
Mes meilleurs vœux pour cette nouvelle Année.
je n'ai plus le temps pour le suite, je suis a l'étranger pour un certain temps.
je clôture le sujet, 
merci pour le suivi fait.

**Comment by tcharp38** [comment]
@brutusangel 
Ok bonne mission alors.
Peut etre que ca interessera qqn de reprendre ca.
