### ISSUE TITLE
Volets Profalux non reconnu => defaultUnknown

### ISSUE THREAD

**Issue by BigYo69** [KiwiHC16/Abeille#2523]
Bonjour,

J'utilise le plugin abeille depuis 2 ans avec une clé Zigate pour piloter mes volets roulants via Jeedom. Mais il y a 6 mois, une mise à jour du plugin a causé un dysfonctionnement. J'ai du faire une restauration pour revenir à l'ancienne version (version du 24/02), mais hier j'ai mis à jour le core Jeedom en 4.3.12 (sans toucher au plugin Abeille - j'étais en 4.2.14), et j'ai de nouveau le même problème.

Ce qu'il se passe c'est que dès que j'utilise un volet (soit via une commande Jeedom, soit avec la télécommande), celui-ci est remplacé par un nouvel équipement sans commande et donc inutilisable. Dans le même temps, un équipement télécommande est créé (sans commande lui aussi).

![image](https://user-images.githubusercontent.com/120782194/208238229-ca980fd9-10f4-4932-a8e0-b41bf3f18196.png)

![image](https://user-images.githubusercontent.com/120782194/208238214-cc02cea0-0e4c-405c-8d73-66b9e93bdec0.png)

J'ai essayé de refaire la procédure d'inclusion, mais les équipements ne sont pas reconnus.

Je ne peux donc plus utiliser mes volets avec Jeedom :/ Auriez-vous une solution ?

Merci d'avance

**Comment by Seby9576** [comment]
Bizarre car je n'ai pas ton soucis alors que je suis sur la même config que toi. Question bête mais as tu la zoé ?

**Comment by BigYo69** [comment]
La Zoé c'est la télécommande centralisée ? Si oui, je la possède bien.

J'ai essayé d'inclure d'autres VR, j'en ai qu'un seul qui est reconnu (mais les commandes ne fonctionnent pas, le volet fait juste un va et vient). Pour les autres, je n'ai que la télécommande qui apparaît.

J'utilise ce protocole :https://zigate.fr/documentation/association-des-volets-profalux-a-la-zigate/

**Comment by Seby9576** [comment]
si avec la zoe tu leur a donné un nom c'est mort. abeille ne reconnait plus ton device en tant que volet. Tu n'a pas le choix que de réinitialiser tes volets. La zoé est inutile car même si tu perd le réseau zigate ta zoé est inopérante

**Comment by BigYo69** [comment]
Je leur ai en effet donné un nom. Mais ça avait toujours marché jusqu’à présent. Et avec la télécommande centralisée opérationnelle en parallèle.

**Comment by Seby9576** [comment]
Oui moi aussi mais tant qui tu ne fais rien ça va. Je sais pas combien tu as de volet moi je n'ai 16 et franchement l'inclusion est rapide

**Comment by BigYo69** [comment]
J’en ai 12 de mon côté.
Du coup tu préconises un reset au niveau de la télécommande c’est ça ?

**Comment by tcharp38** [comment]
Salut
Si le volet n'est pas identifié c'est que son nom "volet" a été modifé, surement avec la Zoé.
C'est un défaut de la premiere generation Profalux qui ne suit pas le standard Zigbee.

**Comment by Seby9576** [comment]
Non reset du volet avec les fils. Technique qui n'est pas dans la notice, tu prend le fils noir et tu touche la phase 5 secondes. Puis stop avec la télécommande et après tu dois refaire tout. C'est moche mais tu as pas le choix. Et fais comme moi vend ta Zoé

**Comment by BigYo69** [comment]
Ah punaise je me souviens avoir fait ça au début, c’était pénible !

Pourquoi la vendre ?

**Comment by Seby9576** [comment]
Elle sert à rien quand tu as jeedom. As tu google home ?

**Comment by BigYo69** [comment]
J’ai Alexa 

Toute la maison est en KNX sinon … sauf les volets le menuisier ayant commandé des moteurs sans fil :(

**Comment by BigYo69** [comment]
Je viens de faire la manip pour réinitialiser les volets sur un VR pour tester. Pas mieux, mon volet n'est toujours pas reconnu ...

Refait une seconde fois avec un VR qui était reconnu mais dont les commandes ne fonctionnaient pas (va et vient). Et j'ai toujours le même problème.

La réinitialisation ne résout donc pas le problème.

**Comment by Seby9576** [comment]
Dans type tu as volet ou inconnu ? Avais tu supprimé de jeedom avant ?

**Comment by BigYo69** [comment]
Ceux qui sont reconnus, j'ai "Profalux Shutter".
Les autres n'apparaissent même pas sur Jeedom.

Et ceux qui apparaissent tout seul lorsque j'utilise l'équipement pour la première fois après la MàJ sont "Default unknown".

**Comment by BigYo69** [comment]
Bon j'ai refait la manip d'inclusion que j'ai linkée plus haut en faisant une descente/montée 2 fois à la fin, et ... ça marche !

Par contre, j'ai toujours des VR non reconnus lors de l'inclusion. Est-ce par ce qu'ils sont loin de la box ?

**Comment by Seby9576** [comment]
Non a mon avis tu peux refaire un deuxième reset

**Comment by BigYo69** [comment]
J'ai fait l'inclusion de tous mes volets, seuls 3 ont été reconnus et fonctionnent (ce sont les plus proches de la box).

Un a été reconnu mais n'est pas identifié (tous les champs de l'équipement sont vides). Je l'ai pourtant reset 2 fois.

Les autres ne sont pas reconnus et ne s'affichent pas sur Jeedom.

Demain je tenterai de mettre ma box dans le salon, au plus près des VR pour voir si ça change quelque chose.

**Comment by Seby9576** [comment]
J'ai ma box dans le garage et ça fonctionne.  Est ce qu' ils apparaissent lors de l'inclusion ? Si oui il sont forcément à portées. 
Conseil d'inclusion : R+haut et surtout ne rien toucher jusqu'au deux clignotement vert et le va et viens

**Comment by BigYo69** [comment]
Non justement, ils n'apparaissent pas :/
Merci je teste ça demain.

**Comment by tcharp38** [comment]
Salut @BigYo69 

Comme je l'ai dit, un volet doit avoir sa "localisation" nommée "volet". C'est le cas par defaut. Mais tu as du le modifier pour tes volets. Du coup... Abeille ne les reconnait pas et ils deviennent "defaultUnknown".

Si ta telecommande les reconnais encore assure toi qu'ils soient bien tous nommés "volet" et pas autre chose.

**Comment by BigYo69** [comment]
Je vais essayer, mais aucun volet n’est nommé comme tel dans la télécommande. Pourtant certains sont reconnus.

**Comment by tcharp38** [comment]
Ha. En fait cet identifiant "volet" est mis dans un un champ "localisation" du standard Zigbee. Ca n'a aucun sens mais c'était comme ca sur cette premiere generation.
Du coup je ne sais pas par quel biais c'est modifié avec la Zoé mais ce genre de soucis est bien lié au fait de la posseder ou pas.

**Comment by BigYo69** [comment]
Je viens de faire une cartographie avec la Zoé, il n'y a que 5 volets dessus (sur 12 au total). J'ai fait une réinitialisation de la télécommande et plus aucun volet n'est enregistré dessus.

Je vais retenter une inclusion pour voir.

**Comment by tcharp38** [comment]
Bon courage.
Désolé pour toi c'est galere parfois avec ces volets. J'en ai aussi.

Manque de pot dans qq heures je serai hors connexion jusqu'au 2. Peut etre que le + urgent pour toi est de retrouver le controle de tes volets avec la zoé et que le reste peut attendre mon retour. Il y a surement des améliorations a faire à Abeille pour aider ce genre de situation, mais la.. zero temps.
Bon courage.

**Comment by BigYo69** [comment]
Pas de soucis.

Je viens de faire une nouvelle tentative et j'ai toujours 2 éléments qui apparaissent : la télécommande et un inconnu :/

![image](https://user-images.githubusercontent.com/120782194/208291120-a3ae9c46-bbed-466a-b8ab-96a946ab33b4.png)

J'ai rien de la champs "Type" sur abeille.

**Comment by tcharp38** [comment]
C est un volet qui ne se localise pas "volet".
Attends.. je regarde si on peut le modifier a distance avec Abeille

**Comment by tcharp38** [comment]
Via la page avancé de ton volet inconnu (Abeille1-387),
tente d'ecrire la valeur de l'attribut 0010 comme suit

![image](https://user-images.githubusercontent.com/35221038/208291463-06eca61f-da4e-4402-bd8e-2c65f2d89bd2.png)

Pour confirmer, peux tu refaire une lecture 

![image](https://user-images.githubusercontent.com/35221038/208291499-ceddf492-2c77-4da4-acca-9215465db050.png)

et me filer les le package de logs.
Je suppose que tu es en mode debug bien sur avant tout ca pour les logs sinon il n'y aura rien dedans.

**Comment by BigYo69** [comment]
J'ai écrit 0010 en attribut et fait un Write. Puis un Read sur la ligne au-dessus.

Voici mon log (en DEBUG) : 
```
0000|[2022-12-18 10:48:02]DEBUG : checkAllDaemons2()
0001|[2022-12-18 10:48:02]DEBUG :   expected=["SerialRead1","Parser","Cmd"]
0002|[2022-12-18 10:48:02]DEBUG :   running={"runBits":4194311,"daemons":{"SerialRead1":{"pid":"2164","cmd":" \/usr\/bin\/php \/var\/www\/html\/plugins\/Abeille\/core\/class\/..\/php\/AbeilleSerialRead.php Abeille1 \/dev\/ttyUSB0 info"},"Monitor":{"pid":"2613","cmd":" \/usr\/bin\/php -r require '\/var\/www\/html\/plugins\/Abeille\/core\/class\/..\/php\/AbeilleMonitor.php'; monRun();"},"Parser":{"pid":"2615","cmd":" \/usr\/bin\/php \/var\/www\/html\/plugins\/Abeille\/core\/class\/..\/php\/AbeilleParser.php info"},"Cmd":{"pid":"2617","cmd":" \/usr\/bin\/php \/var\/www\/html\/plugins\/Abeille\/core\/class\/..\/php\/AbeilleCmd.php info"}}}
0003|[2022-12-18 10:48:02]DEBUG : checkAllDaemons2() => ok
0004|[2022-12-18 10:48:02]DEBUG : cron(): Daemons: 2164/SerialRead1, 2613/Monitor, 2615/Parser, 2617/Cmd
0005|[2022-12-18 10:48:02]DEBUG :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/0000\/getZgVersion&time=1671356902","payload":""}' vers queue 1212
```

**Comment by tcharp38** [comment]
Ca n'est pas le bon. Soit tu me files tout le package (page maintenance, telecharger tout), soit au moins AbeilleParser

**Comment by BigYo69** [comment]
Désolé, voilà le package. Mais il n'y a rien dans le parser :/

[AbeilleLogs-221218.tar.gz](https://github.com/KiwiHC16/Abeille/files/10253556/AbeilleLogs-221218.tar.gz)

**Comment by tcharp38** [comment]
Exact. Donc tu n'es pas en mode debug.
Tant pis on va supposer que l'ecriture est bonne.
Si tu refais une inclusion de ce volet et que c'est bien le cas, il devrait cette fois le reconnaitre en tant que "Profalux shutter"

**Comment by Seby9576** [comment]
J'ai déjà eu ton cas de deux éléments dont un non reconnu,  après le r+ haut est ce que tu ne touche à rien ?

**Comment by BigYo69** [comment]
> Exact. Donc tu n'es pas en mode debug. Tant pis on va supposer que l'ecriture est bonne. Si tu refais une inclusion de ce volet et que c'est bien le cas, il devrait cette fois le reconnaitre en tant que "Profalux shutter"

Bizarre pourtant, je suis bien en DEBUG
![image](https://user-images.githubusercontent.com/120782194/208292385-a9a712c3-3965-482d-b3cd-937a535ec9e1.png)

> J'ai déjà eu ton cas de deux éléments dont un non reconnu, après le r+ haut est ce que tu ne touche à rien ?

Non, rien. J'attends bien que la télécommande ne clignote plus et je fais 2 fermeture/ouverture complète.

**Comment by tcharp38** [comment]
Pour le mode debug, il faut non seulement sauvegarder mais redemarrer Abeille pour qu'il le prenne en compte.
Je sais c'est pas tres logique. Encore qqch a améliorer.

**Comment by BigYo69** [comment]
Faut-il que je supprime l'équipement inconnu avant de faire l'inclusion ?

J'ai refait la manip, voici le LOG du parser :
```
[2022-12-18 11:21:02] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0014, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:02] Abeille1, Type=8014/Permit join status response, PermitJoinStatus=01
[2022-12-18 11:21:02]   Zigate1: en mode INCLUSION
[2022-12-18 11:21:23] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0010, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:23] Abeille1, Type=8010/Version, Appli=0003, SDK=0321
[2022-12-18 11:21:29] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0017, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:29] Abeille1, Type=8017/Get time server response, Timestamp=724677688
[2022-12-18 11:21:29] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0014, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:29] Abeille1, Type=8014/Permit join status response, PermitJoinStatus=01
[2022-12-18 11:21:29]   Zigate1: en mode INCLUSION
[2022-12-18 11:21:29] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0010, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:29] Abeille1, Type=8010/Version, Appli=0003, SDK=0321
[2022-12-18 11:21:41] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0017, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:41] Abeille1, Type=8017/Get time server response, Timestamp=724677700
[2022-12-18 11:21:41] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0014, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:41] Abeille1, Type=8014/Permit join status response, PermitJoinStatus=01
[2022-12-18 11:21:41]   Zigate1: en mode INCLUSION
[2022-12-18 11:21:41] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0010, Sent=00, SQNAPS=00, NPDU=00, APDU=00
[2022-12-18 11:21:41] Abeille1, Type=8010/Version, Appli=0003, SDK=0321
```

Pour info, ça me change l'icône automatiquement en ruche.

**Comment by Seby9576** [comment]
> > Exact. Donc tu n'es pas en mode debug. Tant pis on va supposer que l'ecriture est bonne. Si tu refais une inclusion de ce volet et que c'est bien le cas, il devrait cette fois le reconnaitre en tant que "Profalux shutter"
> 
> Bizarre pourtant, je suis bien en DEBUG ![image](https://user-images.githubusercontent.com/120782194/208292385-a9a712c3-3965-482d-b3cd-937a535ec9e1.png)
> 
> > J'ai déjà eu ton cas de deux éléments dont un non reconnu, après le r+ haut est ce que tu ne touche à rien ?
> 
> Non, rien. J'attends bien que la télécommande ne clignote plus et je fais 2 fermeture/ouverture complète.

Attention parfois elle ne clignote plus pendant quelques secondes. Il faut absolument les voyants vert et le va et vient de l'ensemble des volets qui sont deja dans le reseau et la tu peux faire les deux aller et retour

**Comment by BigYo69** [comment]
Tu as la procédure quelque part ? Car celle sur le site de Zigate me paraît incomplète :/
J'ai pas tous les volets apparairés qui bouge en fin de process chez moi.

**Comment by BigYo69** [comment]
Je viens de faire plusieurs tentative en modifiant l'attribut des volets, mais j'ai toujours un volet sans type qui apparaît malheureusement :/

**Comment by Seby9576** [comment]
Non propre expérience car je l'ai fait un paquet de fois (avant j'avais eedomus). récemment j'ai fait la maj de la zigate + erase eeprom et donc j'ai fait cette manip 16 fois sans aucun loupé. Peut être quelques chose d'important mais j'ai commencé par le volet le plus près et je recule au fur et a mesure. J'ai l'impression que comme toi ma zigate est dans le garage par contre j'espère pour toi quelle n'est pas dans une baie informatique.

Moi je reset avec le fil puis je fais stop pour que la telecommande soit appairé une fois que j'ai la validation (va et vient + voyant vert) je lance l'inclusion de la zigate puis je fait R + haut et je ne touche a rien tant que j'ai pas ce que j'ai dit. Ensuite je fais les deux va et viens mais ca c'est plus pour les fdc que pour abeille.

**Comment by BigYo69** [comment]
> par contre j'espère pour toi quelle n'est pas dans une baie informatique.

C'est le cas, mais qu'est-ce que ça change ?

**Comment by BigYo69** [comment]
Le reset du fil, c'est fil noir sur fil marron pendant 5 sec, on coup, puis on remet le fil noir tout seul. C'est ça ? Les volets doivent bouger à ce moment-là ? Quand fais-tu le stop ?

**Comment by Seby9576** [comment]
Oui le reset je fait toucher le fil noir avec le fil marron 5 seconds et quand tu relaches le volet doit faire un va et vient et la tu fais le stop. Après la validation du stop test ton moteur attention le volet peut tourner dans le mauvais sens dans ce cas la je fais F+stop. Et la je commence mon inclusion

**Comment by tcharp38** [comment]
Quand tu files des logs, ne copie jamais le texte. Fais juste un glisser/deposer du package de logs.

Si le volet s'annonce tu dois voir dans le parser un "device announce" passer.
Sinon c'est que la procedure n'est pas bonne.
Mets le package de logs apres ta prochaine inclusion ratée, histoire de verifier tout ça.

**Comment by BigYo69** [comment]
En attendant, j'ai testé avec le plugin Zigate. J'ai exactement le même problème : seuls 3 VR sont reconnus (les mêmes que sur Abeille).

J'ai refait une inclusion (ratée) sur Abeille avec le volet pour lequel j'avais modifié l'attribut. Voici le log complet : 
[AbeilleLogs-221218 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10253649/AbeilleLogs-221218.1.tar.gz)

**Comment by tcharp38** [comment]
Ton log parser est tres court.
Mais on n'y voit que les "device announce".. d'un seul periph 20918AFFFF007E51. Il devrait y en avoir 2 (volet et telecommande).

Neanmoins je note qqch qui ne me plait pas.
[2022-12-18 12:02:46] Abeille1, Type=9999/Extended error, ExtStatus=87

On dirait que ta zigate est dans un sale etat.
Vu que tu n'as que tres peu d'equipements, cette erreur ne fait pas de sens pour moi.
Je suggere du coup
- que tu fasses une update FW vers 3.21-OPDM (au lieu de legacy)
- erase PDM => IMPORTANT !, page avancé => voir image
- et reappairage complet

![image](https://user-images.githubusercontent.com/35221038/208295615-ee188e34-aac4-4aae-990f-d8dc92c431c2.png)

Au moins tu repars tout propre tout de suite avant d'avoir trop d'équipements.

**Comment by BigYo69** [comment]
Oui il n’y a qu’un seul équipement car cette fois la télécommande n’a pas été reconnue (des fois elles le sont, des fois non).

Je vais mettre à jour la Zigate. Le problème peut-il être matériel ? Car tant qu’à faire, autant racheter un clé si besoin avant de tout reconfigurer.

Merci beaucoup pour votre aide à tous les 2.

**Comment by tcharp38** [comment]
Non je pense que ca n'est pas materiel. La zigate corrompue me semble plus en ligne.
De toute façon il est recommandé d abandonner le FW legacy des que possible. Moins fiable que la version OPDM.

**Comment by Seby9576** [comment]
Quand j'avais ton pb c'est que je ne faisait pas bien la manip. Après ca ira peut être mieux après un erase et une maj

@tcharp38 peux tu jeter un œil rapide sur mon post "loupé commande volet car j'ai un soucis avec un volet sur lequel j'ai fait un réinitialiser. As tu changer quelque chose ?

**Comment by BigYo69** [comment]
> Non je pense que ca n'est pas materiel. La zigate corrompue me semble plus en ligne. De toute façon il est recommandé d abandonner le FW legacy des que possible. Moins fiable que la version OPDM.

MàJ faite, j'ai toujours le même message dans le parser : 
[2022-12-18 13:41:16] Abeille1, Type=9999/Extended error, ExtStatus=89

**Comment by tcharp38** [comment]
Ca n'est plus la meme erreur.
Pense à mettre le package de logs.
Donc tu en es ou ? Tu as pu en inclure ? Pas du tout ? Toujours un souci sur le meme volet que tout à l heure ?

**Comment by BigYo69** [comment]
En fait, j'ai regardé l'erreur correspond à l'impossibilité de passer la Zigate en Permit join (en effet, elle ne passe pas en mode inclusion). Il faut que je fasse un Start Network, mais je ne trouve pas la commande ...

**Comment by BigYo69** [comment]
Problème réglé, nouveau test, je n'ai désormais que la télécommande qui est reconnue ...

Je suis en train de devenir dingue !

[AbeilleLogs-221218.tar.gz](https://github.com/KiwiHC16/Abeille/files/10253880/AbeilleLogs-221218.tar.gz)

**Comment by BigYo69** [comment]
Alléluia ! J'ai refait une 2e inclusion après l'inclusion de la télécommande et ça marche !

**Comment by Seby9576** [comment]
explique ? je te conseille d'enlever les piles de zoe

**Comment by BigYo69** [comment]
En fait, j'ai fait une première inclusion où la Zigate ne remontait que la télécommande. J'ai supprimé l'équipement et recommencé, même résultat. J'ai laissé la télécommande et refait une inclusion et là le volet est apparu.

Je viens d'en faire 2 autres (qui ne remontaient pas avant la MàJ de la ZiGate) et ça marche direct pas besoin de faire 2 inclusions.****

**Comment by Seby9576** [comment]
Oui comme dit tcharp parfois c'est un peu capricieux. Si tu suis la manip tu devrais ne pas avoir trop de soucis

**Comment by tcharp38** [comment]
Ouf...

**Comment by BigYo69** [comment]
Je suis en train de continuer mes inclusions. J'ai fait la moitié sans incident pour le moment.

Merci à tous les 2 !
