### ISSUE TITLE
Perte équipements systématique

### ISSUE THREAD

**Issue by arnoakavdb** [KiwiHC16/Abeille#2524]
Bonjour,
tout fonctionnait bien mais depuis 2 jours je perd systématiquement le lien avec mes équipements. Le seul moyen est de redémarrer le démon manuellement  et après deux ou trois manipulation d'équipement cela repart. J'ai tenté de changer le canal et de réintégrer les équipements existant mais la toujours la même chose. Je ne comprend pas trop car je n'ai fait aucun changement entre le moment ou tout allait bien et ou tout a lâche
[AbeilleLogs-221220.tar.gz](https://github.com/KiwiHC16/Abeille/files/10271368/AbeilleLogs-221220.tar.gz)

**Comment by arnoakavdb** [comment]
Pour info je suis sur la dernière beta du 15/12

**Comment by tcharp38** [comment]
Salut.
Je suis loin d'une connexion fiable et juste un tel avec moi donc difficile de faire plus pour l'instant
C'est en changeant de bêta que tu as eu des problèmes ?

**Comment by arnoakavdb** [comment]
Non sur l'avant dernière aussi,donc j'ai fait la dernière en pensant que cela réglerai mon aussi mais il persiste.j'ai tenté un restart de jeedom mais toujours la même chose

**Comment by arnoakavdb** [comment]
Bon alors sorry mais voilà je pense que c'était mon système complet qui était genou à terre,après un reboot complet de mon Synology qui héberge jeedom tout est revenu à la normal.
