### ISSUE TITLE
Module volet roulant LoraTap SC500ZB (id = TS130F, _TZ3000_e3vhyirx)

### ISSUE THREAD

**Issue by Valjion** [KiwiHC16/Abeille#2528]
Bonsoir KiwiHC416
J'ai acheté des modules pour piloter des volets roulants qui ne sont pas reconnus.
Pourrais-tu rajouter cela dans Abeille ?
Ci-joint une photo et le fichier discovery.
Merci d'avance et mes meilleurs vœux .

[discovery.zip](https://github.com/KiwiHC16/Abeille/files/10329396/discovery.zip)
![commande volet roulant LoraTap](https://user-images.githubusercontent.com/121679917/210183527-e7e261c1-507c-4fca-8b92-7863db7b1590.png)

**Comment by thedrgraph** [comment]
@Valjion Hello tu pourrait faire un retour, je vais avoir besoin de me pencher sur les module volet roulant bientôt et j'avais déjà aperçu ce model :) 
J'aimerai notamment savoir si il font routeur pour le zigbee ou juste end device ?

Merci.

**Comment by tcharp38** [comment]
Salut @Valjion 
Bonne année.

Voila un premier modele à decompresser dans core/config/devices.
Sera dans la prochaine beta. Ca serait bien qu'entre temps tu bascules dessus.
[TS130F__TZ3000_e3vhyirx.zip](https://github.com/KiwiHC16/Abeille/files/10336712/TS130F__TZ3000_e3vhyirx.zip)

A noter que Loratap a sorti un modele v2. Il y a peut etre des trucs corrigés ou améliorés donc attention.

**Comment by tcharp38** [comment]
@thedrgraph 
Ce module etant sur secteur, il doit faire repeteur. Quasi aucun doute.

**Comment by thedrgraph** [comment]
J'ai un peu chercher et effectivement il devrais faire répéteur. 
Pour ce qui est des versions j'ai trouvé ceci.

![loratap ver](https://user-images.githubusercontent.com/19219121/210372374-26f6e0f9-33d1-43ba-8948-8128b54d6c08.png)

par contre a part la couleur les inscription sont identiques notamment le model : " C500ZB " donc pas facile mais la difference est grande entre time et %

**Comment by tcharp38** [comment]
Merci pour ces infos.
J'espere que les 2 ne s identifient pas de la meme maniere.

**Comment by thedrgraph** [comment]
Bonne question 
surtout que sur le site officiel il parle de la gen 2 avec les descriptif de la gen 1 :( c'est pas gagné :)

**Comment by Valjion** [comment]
Bonjour a vous ,
Merci pour le retour et le fichier ! 
J'étais en déplacent , je vous fait le retour des que je pourrais ! 
Bon week end !

**Comment by Valjion** [comment]
Alors voila, ça fonctionne, j'ai accès au commande monter, descente, stop, au niveau du volet . Par contre niveau calibration, comprend pas trop comment ca fonctionne, c'est comme si il avait déjà une course pré défini en programme, je commence volet en bas, lorsque il est complétement ouvert ,pour lui il n'est que a 47%.
j'ai essayé reste et remise a zéro , mais j'ai pas l'impression que ca change quelque chose .
Et effectivement il est reconnu comme routeur dans abeille . 
Bon,ne soirée

**Comment by tcharp38** [comment]
Salut @Valjion 
Désolé pour mon silence sur le sujet.

As tu basculé sur la derniere beta ?
Pourrais tu me donner un package de logs (mode debug obligatoire) apres une action descente par ex ?
Le package est dispo via la page maintenance/logs/telecharger tout

**Comment by thedrgraph** [comment]
J'ai enfin put avoir le Temp d'installer un model similaire sur le seul volet roulant que j'ai actuellement :).
mais vu le code ce n'est pas la même génération de là a savoir si c'est 1 ou 2 :)
pourvu que j'ai le temp de faire des test :)

**Comment by tcharp38** [comment]
J'attends des billes de l'un de vous pour voir ce qu'il faut changer/corriger/améliorer

**Comment by Valjion** [comment]
Bonsoir a vous, désolé, je n'avais pas vu dans mes mails votre réponse . Merci encore pour le retour , mais je suis au final passé sur des modules Moes, ou tout est directement pris en compte dans Abeille.  Et qui en terme de quali boite et connectique est bien mieux , et pour le même prix .
Bonne soirée a vous .

**Comment by thedrgraph** [comment]
@Tcharp38 je pense que tu peut faire similaire a l'autre module et cloturé ici :)

**Comment by tcharp38** [comment]
@thedrgraph 
Que veux tu dire ?
Le v1 et le v2 n ont pas les meme fonctionalités d'apres ton tableau comparatif alors les modeles sont forcement differents

**Comment by thedrgraph** [comment]
D’après ce même tableau j'ai une V2 avec donc le % et en fait la gestion via le temps fonctionne très bien il devrait en être de même pour l'autre modèle.

**Comment by tcharp38** [comment]
Je prefere que qqn qui a ce modele confirme ou test plutot que pousser qqch à l aveugle.

Mais du coup je clos le sujet vu que @Valjion a basculé sur d'autres modules.. y a plus personne pour tester.
A reouvrir si besoin.
