### ISSUE TITLE
Ajout Legrand 064888 Micromodule Céliane Netatmo

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2529]
Bonjour !!!

Je viens de me faire  livrer un kit micromodule + 2 inter sans pile sans fil.
Le micromodule est compatible Zigate.
Est ce possible de le créer dans abeille svp ?
(Mon package abeille est fichier joint, ajout vers 17h45/50 environ

Dispo au besoin pour tester
Merci

![image](https://user-images.githubusercontent.com/49479084/211060274-7b1097f7-c07e-4ede-aa63-04905cdd1d77.png)

[https://zigate.fr/produits-legrand-compatibles-zigate/compatible/micromoduleclianenetatmopourclairageconnect300wonoffavecneutre/](url)

[https://zigbee.blakadder.com/Legrand_064888.html](url)

[AbeilleLogs-230106.tar.gz](https://github.com/KiwiHC16/Abeille/files/10361746/AbeilleLogs-230106.tar.gz)

**Comment by Jake309** [comment]
J'ai oublié de spécifier, c'est sur abeille1 (zigate V2), qui est bien sur le canal 11 (déjà modifié pour mes inter volet netatmo)

Je pense que c'est celui ci qui a été créé : 
Nom Abeille1-673
Nom logique Abeille1/A2B6
Adresse (courte/IEEE) A2B6 / 00047400001149A9

`[2023-01-06 17:51:08][DEBUG] : msgFromParser(): New device: Abeille1/A2B6, ieee=00047400001149A9`
`[2023-01-06 17:51:08][DEBUG] :   newJeedomDevice(Abeille1, addr=A2B6)`

**Comment by tcharp38** [comment]
Salut @Jake309 
J'ai besoin du discovery pour tout nouvel equipement: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by Jake309** [comment]
Salut @tcharp38 :)
En fait, je t'embête pour rien, le A2B6 semble être un fantome, car en retournant recupérer le discovery, j'ai trouvé mon micromodule:
![image](https://user-images.githubusercontent.com/49479084/211143395-82a6de57-e4e0-401a-9ba9-9a729234e42f.png)

Je clos le sujet de ce fait.
Mille excuse !

PS: je repasse en beta dimanche si tout va bien à la maison
