### ISSUE TITLE
Ajout commande STOP sur Volet Profalux (Fille de de #114)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#253]

**Comment by KiwiHC16** [comment]
Je n ai pas fait le stop encore.

**Comment by KiwiHC16** [comment]
Just pushed the new command.
Update master.
Restart Abeille.
Noter l'adresse du volet.
Delete L objet Volet.
Faire une getName sur l adresse du volet pour recréer l objet volet
et tester ...

**Comment by zoozbiro** [comment]
Hello, désolé pour la dispo tardive. J'ai testé tout fonctionne correctement. J'ai juste du recréer complètement mes volets avec la manipulation sur la télécommande car le get name n'a pas recréé l'objet  (j'ai rater quelque chose? ) 

idem pour le set level tt est ok!!!

Bravo et encore merci pour le travail

**Comment by KiwiHC16** [comment]
Super, toujours bien de savoir que ca fonctionne chez qq !!!

Plusieures raison pour le getName:
- indiquer le bon end point
- ne pas avoir d objet avec cette adresse dans abeille
- ...
