### ISSUE TITLE
Xiaomi Single Switch Module T1 (With Neutral) timeout

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2532]
bonne année meilleurs vœux 
nouveauté 2023 lol il passe en timeout
mais un timeout fictif car en envoyant une commande il repasse en ok
[AbeilleLogs-230110.tar.gz](https://github.com/KiwiHC16/Abeille/files/10383454/AbeilleLogs-230110.tar.gz)

**Comment by tcharp38** [comment]
Bonne année @chrisb13790 
C'est nouveau ?
Si oui, un changement quelconque qui aurait fait basculer ?

**Comment by chrisb13790** [comment]
[AbeilleLogs-230111.tar.gz](https://github.com/KiwiHC16/Abeille/files/10389975/AbeilleLogs-230111.tar.gz)
salut,si par nouveau tu entends le comportement du timeout fictif oui car le module est installé depuis un moment, le seul changement qui aurait pu jouer c est le repeteur suite  mais celui ci tient bon pour le moment , je te remets un log car il me l a refait depuis hier vais essayer de le suivre aujourd hui mais pas mal de chose a faire

**Comment by chrisb13790** [comment]
[Uploading AbeilleLogs-230111(1).tar.gz…]()

**Comment by tcharp38** [comment]
Ce dernier log est ... pas la.
Tu as du interrompre avant qu'il ne soit sur Github.

Néanmoins via le package precedent je vois ca qui n'est pas bon pour 0E9F

> {\"macCapa\":\"8E\",\"mainsPowered\":1,\"rxOnWhenIdle\":0}

Le rxOnWhenIdle ne devrait pas etre à 0 pour un macCapa 8E.

Je pense qu'il a été modifié lors du refresh reseau qui a lieu toutes les nuits.
Dans ton cas je recois 2 infos contraitres

>     Du 0020: "addr":"0E9F","bitMap":"0225"
>     Du B78D: "addr":"0E9F","bitMap":"0229"
>     Du 342B: "addr":"0E9F","bitMap":"0229"

Ces valeurs de bitmap à 229 sont celles qui me chagrinnent. Ca voudrait dire RXOFF et non pas RXON.
Bref soit j'ai toujours pas compris comment interpreter ce champ 'bitmap' 
soit certains routeurs renvoient ... de la merde.

Dans tous les cas je modifie le code maintenant pour ne plus tenir compte de cette info. Seul le macCapa le sera.

**Comment by chrisb13790** [comment]
[AbeilleLogs-230111(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10393830/AbeilleLogs-230111.1.tar.gz)
je t ai remis le log precedent

**Comment by tcharp38** [comment]
Je pousse une nouvelle beta ce soir pour demain.
Une fois que tu as fait la mise à jour et redemarré
essaie via la page avancé de ton Xiaomi d'interroger le "node descriptor". 
et tu me files les logs

j'espere que ca fixe le pb

**Comment by chrisb13790** [comment]
voici le log apres redémarrage du demon  abeille et intero du descripteur de noeud
[AbeilleLogs-230113.tar.gz](https://github.com/KiwiHC16/Abeille/files/10410107/AbeilleLogs-230113.tar.gz)

**Comment by tcharp38** [comment]
"rxOnWhenIdle\":1
Dis moi si il retombe en timeout.
Pour moi ca devrait etre bon.

**Comment by chrisb13790** [comment]
pas de perte sur la journée,on peux fermer

**Comment by tcharp38** [comment]
A reouvrir si besoin

**Comment by Xav-74** [comment]
Hello @tcharp38

Je me permets de réouvrir le sujet car je rencontre exactement le même souci avec le modèle Xiaomi Single switch suivant :
![image](https://user-images.githubusercontent.com/56156622/231162137-b09340b8-fdda-40f4-a0a1-c1ca7cb29f36.png)

Je pensais au départ que cela venait de ma pile qui était un peu faiblarde mais suite au remplacement même souci. J'ai tenté le bouton réparer mais sans succès également.

J'ai passé le module en surveillance ce matin : voici les logs 
```
0000|[2023-04-11 11:14:07] >>> Démarrage du démon de monitoring
0001|[2023-04-11 11:14:07] Equipement à surveiller: [Garage][AB Interrupteur Garage], C023-00158D0005471E6F
0002|[2023-04-11 11:19:25] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C023, DstAddrMode=02, DstAddr=0000
0003|[2023-04-11 11:19:25] <=   FCF=18/General/Serv->Cli, SQN=09, cmd=0A/Report attributes
0004|[2023-04-11 11:19:25] <=   AttrId=0000/OnOff, AttrType=10, ValueHex=00 => 0
0005|[2023-04-11 11:19:25] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C023, DstAddrMode=02, DstAddr=0000
0006|[2023-04-11 11:19:25] <=   FCF=18/General/Serv->Cli, SQN=0A, cmd=0A/Report attributes
0007|[2023-04-11 11:19:25] <=   AttrId=0000/OnOff, AttrType=10, ValueHex=01 => 1
0008|[2023-04-11 13:12:58] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0000, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C023, DstAddrMode=02, DstAddr=0000
0009|[2023-04-11 13:12:58] <=   FCF=1C/General/Serv->Cli/ManufCode=1234, SQN=0B, cmd=0A/Report attributes
0010|[2023-04-11 13:13:04] <= 8011/APS data ACK, Status=A7/NO_ACK, Addr=C023, EP=01, ClustId=0000, SQNAPS=8D
0011|[2023-04-11 13:13:05] <= 8702/APS data confirm fail, Status=F0/MAC_ENUM_TRANSACTION_EXPIRED, SrcEP=01, DstEP=01, AddrMode=02, Addr=C023, SQNAPS=8D, NPDU=00, APDU=00
0012|[2023-04-11 14:13:10] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0000, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C023, DstAddrMode=02, DstAddr=0000
0013|[2023-04-11 14:13:10] <=   FCF=1C/General/Serv->Cli/ManufCode=1234, SQN=0C, cmd=0A/Report attributes
0014|[2023-04-11 14:13:16] <= 8011/APS data ACK, Status=A7/NO_ACK, Addr=C023, EP=01, ClustId=0000, SQNAPS=AC
0015|[2023-04-11 14:13:17] <= 8702/APS data confirm fail, Status=F0/MAC_ENUM_TRANSACTION_EXPIRED, SrcEP=01, DstEP=01, AddrMode=02, Addr=C023, SQNAPS=AC, NPDU=00, APDU=00
0016|[2023-04-11 14:13:38] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C023, DstAddrMode=02, DstAddr=0000
0017|[2023-04-11 14:13:38] <=   FCF=18/General/Serv->Cli, SQN=0D, cmd=0A/Report attributes
0018|[2023-04-11 14:13:38] <=   AttrId=8000/Unknown-0006-8000, AttrType=20, ValueHex=02 => 2
```
Réinclusion à 11h13 au cas ou 
Surveillance à 11h14
Appui une fois à 11h19
Passage en timeout à 13h13 (timeout de 60min)
Appui double à 14h13

Si tu as besoin d'autres logs, n'hésites pas !
Merci
