### ISSUE TITLE
Mise a jour Firmware via OTA

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2534]
Salut,

Je réfléchissais à mettre à jour mes équipements, je vois que abeille le permet via OTA mais il faut lui fournir les firmware.
Comme je regarde ce qui se fait ailleurs avant de demander, 
Est ce qu'il est possible que dans un temps, on ait une publication de firmware automatique (via maj abeille ?) comme on le voit sur le plugin zigbee ?

De façon à ce que nos équipements puissent se mettre à jour quand ils demandent s'il y en a :) 

Meric !

**Comment by tcharp38** [comment]
Salut
Le plugin Zigbee fait ca ? 
Je vois pas comment c'est possible vu que les FW ne sont pas "publiques" sauf dans certains cas.
Ikea c'est assez ouvert.
Beaucoup d autres sont recupérés que parce que tu as une appli du fabricant et la passerelle qui va bien.

Bref je suis curieux de savoir ce qu'offre le plugin zigbee

**Comment by Jake309** [comment]
J'ai trouvé ça la :
[https://community.jeedom.com/t/questions-sur-le-fonctionnement-ota/59005](https://community.jeedom.com/t/questions-sur-le-fonctionnement-ota/59005) 

Et quelqu'un dit que le plugin puise la :
https://github.com/Koenkk/zigbee-OTA/tree/master/image

Tu sais où je peux récupérer les Ikea ?
La maj des firmware, ça peut surement résoudre certains problèmes sur des équipements, je suis chaud pour tester. 
Je vais télécharger toute la base du lien GitHub et tester ca

**Comment by tcharp38** [comment]
Donc c'est ca. Le plugin permet que le device qui le souhaite fasse une mise à jour SI le FW a été recupéré et installé.
En dehors de Ikea, les autres FW ne sont pas facilement accessibles.

Pour Ikea les FW dispos sous donnés via un fichier XML en ligne il me semble.
Il faut que je remette la main dessus

**Comment by tcharp38** [comment]
@Jake309 
Voila le lien qui permet d etre à jour sur les FW Ikea
http://[fw.ota.homesmart.ikea.net/feed/version_info.json](http://fw.ota.homesmart.ikea.net/feed/version_info.json)

Mais à ma connaissance c'est le seul fabricant qui fait ca et qui rend les FW publiques.
Du coup le plugin ne peut rien faire pour les autres.

En ligne avec ca ?

**Comment by tcharp38** [comment]
@Jake309 
Je viens de mettre à jour pour repeteur IKEA. Ca fonctionne tres bien.

Tu as des soucis de mise a jour ?

**Comment by Jake309** [comment]
Salut @tcharp38 

J'ai essayé avec ton lien, j'ai téléchargé le control outlet, qui correspond au prise.

![image](https://user-images.githubusercontent.com/49479084/214254742-645773f1-a20d-4790-becf-012672fe3248.png)

Je coche et notifie mon équipement, 
`  | 2023-01-24 10:27:36 | Abeille | [Bureau][Bibliothèque]: Mise-à-jour du firmware démarrée `

Après plus rien sauf les occurrences qui croient.
Mon équipement (j'en ai essayé plusieurs) ne change jamais de version de FW quand je fais un `Get-SWBuildID`

Je ne sais pas ce que tu fais toi pour que ca fonctionne, je suis preneur de ta façon de faire si c'est pas la même.
Ou alors j'oublie de faire quelque chose en plus.

Je veux mettre a jour mes équipements car je suis toujours en quete d'un système parfait sans latence, sans bug etc :-)

**Comment by tcharp38** [comment]
Salut
C'est tout à fait ca mais la mise à jour prend plusieurs minutes.
Le devices demande le nouveau FW petits bouts par petits bouts.
Tu me files le package de logs quand c'est comme ca. On peut verifier que ca se déroule comme il faut.

**Comment by Jake309** [comment]
Salut,
Alors, arrivé un moment j'ai une notif disant que l'équipement a annulé le telechargement de la mise à jour.
Je te mets le package de llog. 

J'en ai testé 2 dont : 
`Nom logiqueAbeille1/53ED`
`Adresse (courte/IEEE)53ED / B4E3F9FFFEABFD04`

merci pour ton aide :)

[AbeilleLogs-230124.tar.gz](https://github.com/KiwiHC16/Abeille/files/10503949/AbeilleLogs-230124.tar.gz)

**Comment by Jake309** [comment]
@tcharp38 J'ai reussi à en faire une cette nuit.
Je sais pas si c'est du au fait qu'elle était éteinte et pas sollicitée mais en tout cas plusieurs heure après, j'ai eu la notif MAJ terminé et j'ai le nouveau firmware qui remonte

**Comment by tcharp38** [comment]
Bonne nouvelle. 
Effectivement comme c'est assez long il faut que la connexion soit bonne et peut etre pas perturbée tout le long.
Mais dans tous les cas tant que le FW est dispo le device doit le redemander tous les jours jusqu'a mise à jour ok.

Concernant ton log pour 53ED, on voit bien la demande

> [2023-01-24 18:10:29] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0019, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=53ED, DstAddrMode=02, DstAddr=0000
> [2023-01-24 18:10:29]   FCF=01/Cluster-specific/Cli->Serv, SQN=04, cmd=01/Query Next Image Request
> [2023-01-24 18:10:29]   fieldCtrl=01, manufCode=117C, imgType=1101, fileVers=20024623, hwVers=003C
> [2023-01-24 18:10:29]   FW version 23089631 available. Response handled by Zigate server.
> 

suivi de multiples "block request"

> [2023-01-24 18:10:39] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0019, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=53ED, DstAddrMode=02, DstAddr=0000
> [2023-01-24 18:10:39]   FCF=01/Cluster-specific/Cli->Serv, SQN=13, cmd=03/Image Block Request
> [2023-01-24 18:10:39]   fieldCtrl=00, manufCode=117C, imgType=1101, fileVers=23089631, fileOffset=00000372, maxData=3F

et la fin

> [2023-01-24 18:13:01] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0019, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=53ED, DstAddrMode=02, DstAddr=0000
> [2023-01-24 18:13:01]   FCF=01/Cluster-specific/Cli->Serv, SQN=1F, cmd=06/Upgrade End Request
> [2023-01-24 18:13:01]   Handled by decode8503
> [2023-01-24 18:13:01] Abeille1, Type=8503/OTA upgrade end request, SQN=1F, EP=01, ClustId=0019, AddrMode=02, Addr=53ED, ImgVers=23089631, ImgType=1101, ManuCode=117C, Status=95
> 


Je constate aussi qu'il y avait 2 mise à jour OTA en meme temps.
Une aussi pour F121 ([Salon][Baril]) en meme temps que 53ED ([Bureau][Bibliothèque])

Enfin je vois un crash qui s'est produit au milieu, imposant un redemarrage du démon. Ca n'a pas du aider.
Je vais bosser dessus.
Mais en ce qui me concerne la mise à jour fonctionne.

**Comment by tcharp38** [comment]
@Jake309 
On fait quoi de ce sujet ?

**Comment by Jake309** [comment]
Je pense qu'on peut clôturer.
J'ai réussi mes mise a jour, mais c'est pas évident et le manque de dispo des firmware tempeche de démocratiser la chose :/

**Comment by tcharp38** [comment]
C'est clair.
Les FW ne sont dispos que chez qq fabricants un peu serieux.
Je clos. A reouvrir si besoin
