### ISSUE TITLE
Intégration ZBMINI-L (id = ZBMINI-L, SONOFF)

### ISSUE THREAD

**Issue by Fabtwo38** [KiwiHC16/Abeille#2539]
Bonjour,

J'ai rajoute un nouvel équipement dans Abeille ( Pizigate ) et je n'obtiens pas de commande pour cet équipement.

pourriez vous m'aider ?

Cordialement,
Fabrice
[discovery-ZBMINI-L_SONOFF.json.txt](https://github.com/KiwiHC16/Abeille/files/10438524/discovery-ZBMINI-L_SONOFF.json.txt)

**Comment by tcharp38** [comment]
Salut @Fabtwo38 
A decompresser dans core/config/device
[ZBMINI-L_SONOFF.zip](https://github.com/KiwiHC16/Abeille/files/10439043/ZBMINI-L_SONOFF.zip)

puis redemarrer Abeille
et refaire inclusion

J'ai besoin d'une belle image PNG sans arriere plan pour l'icone

**Comment by Fabtwo38** [comment]
merci beaucoup, voici l'image 
![Capture d'écran_20230117_213525](https://user-images.githubusercontent.com/77851160/213007072-856d13ec-6c98-42d0-9f54-f9420611aad9.png)

**Comment by Fabtwo38** [comment]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/10439352/Abeille.txt)
J'ai dézippé le fichier dans abeille/core/config/device
J'ai redémarré le daemon d'abeille et refait l'inclusion mais je n'ai pas de commande ON/OFF .
Peut etre ai je loupé quelque chose ?
Il cherche des fichiers json qui n'existe pas

**Comment by tcharp38** [comment]
Ha oui. Tu es surement sur une version stable.
Du coup 2 choix
1/ patienter pour une nouvelle stable
2/ basculer sur la beta, reappliquer le modele, et refaire inclusion
voir https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

Je prefere le 2 pour tout support. Ca m'aide pour avancer.
A toi de voir.
j'ai pris l'image. Elle sera dans la prochaine beta.

**Comment by Fabtwo38** [comment]
du coup avec la version beta, les commandes apparaissent .

merci beaucoup pour ton aide .

**Comment by tcharp38** [comment]
Tout est bon ?
Il manque qqch ?

**Comment by Fabtwo38** [comment]
Tout est bon pour cet équipement.
Merci pour le support.

**Comment by tcharp38** [comment]
Super.
je clos alors mais a reouvrir si soucis
