### ISSUE TITLE
Abeille formule sonde température sonoff SNZB 02 supprimée

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2540]
@tcharp38, comme convenu j'ouvre un sujet concernant l'utilisation des formules qui disparaissent dans Abeille ?

![2023-01-30_155057](https://user-images.githubusercontent.com/104787819/215510542-c9d38768-0aff-48b0-a033-fb471073d975.jpg)

Pour rappel:
Mise à jour Abeille : formule supprimée
Mise à jour de l'équipement : formule présente
Redémarrage Abeille : formule supprimée

Voilou...

**Comment by tcharp38** [comment]
Ton dernier status était different:
![image](https://user-images.githubusercontent.com/35221038/215526837-14218fa2-14e1-40c2-a989-72c5a2f88ae3.png)
https://github.com/KiwiHC16/Abeille/files/10517872/AbeilleLogs-230127.tar.gz

Néanmoins je crois que ce status est + juste. En tout cas j'ai trouvé qqch qui peut expliquer la perte au "redemarrage".
A voir dans la prochaine beta dispo demain 230130-BETA-1

**Comment by Jeedom122** [comment]
Salut @tcharp38,
Mise à jour effectuée, la formule toujours présente.
Je patiente quelques jours avant de clôturer le sujet.
Merci !!!!
A++

**Comment by Jeedom122** [comment]
Cela semble bon.
Est-ce que je peux repasser à la version stable d'Abeille ?

**Comment by Jeedom122** [comment]
Pour info, à chaque redémarrage de serveur j'ai ce message
![2023-02-02_163918](https://user-images.githubusercontent.com/104787819/216370282-6ebf940d-67ce-49d6-93a9-5d0a47f26b8d.jpg)

**Comment by tcharp38** [comment]
> Cela semble bon. Est-ce que je peux repasser à la version stable d'Abeille ?

Je n'ai pas sorti de nouvelle stable avec les derniers correctifs... donc à toi de voir.
Mais si tu repasses en stable.. tu dois faire une RESTAURATION et surtout pas installer la stable, plus vieille que la beta du moment.
Je te suggere d'attendre la prochaine stable pour y basculer et y rester si plus besoin de support.

**Comment by tcharp38** [comment]
> Pour info, à chaque redémarrage de serveur j'ai ce message ![2023-02-02_163918](https://user-images.githubusercontent.com/104787819/216370282-6ebf940d-67ce-49d6-93a9-5d0a47f26b8d.jpg)

Files moi un package de logs apres un redemarrage STP

**Comment by Jeedom122** [comment]
Salut @tcharp38,
Voici le package de logs après redémarrage.
[AbeilleLogs-230205.tar.gz](https://github.com/KiwiHC16/Abeille/files/10610778/AbeilleLogs-230205.tar.gz)

Je vais rester sous la bêta pour l'instant, faire une restauration ?  je ne comprend pas  ;)

**Comment by tcharp38** [comment]
Le premier message au démarrage semble parfoit corrompu.
D'ou cette erreur.
J'ai modifié pour filtrer ce genre d'erreur.

Peux tu decompresser ce code dans core/php (en gardant une copie de l original)
[AbeilleSerialRead.zip](https://github.com/KiwiHC16/Abeille/files/10662300/AbeilleSerialRead.zip)

puis tu redemarre Abeille
et me file les logs.
Merci

**Comment by Jeedom122** [comment]
Dans core/php il n'y avait pas de fichier AbeilleSerialRead.php ?
Pour redémarrer Abeille, j'ai relancé le démon ???? Ce n'est pas ça ?
[AbeilleLogs-230206.tar.gz](https://github.com/KiwiHC16/Abeille/files/10663470/AbeilleLogs-230206.tar.gz)

**Comment by tcharp38** [comment]
Tu dois mélanger avec le core/php de jeedom.
Pour Abeille c'est plugins/Abeille/core/php et tu dois trouver AbeilleSerialRead

**Comment by Jeedom122** [comment]
Oui, exacte de me suis trompé de core.
Rectifié, relancé le démon et voici les logs
[AbeilleLogs-230206.tar.gz](https://github.com/KiwiHC16/Abeille/files/10668308/AbeilleLogs-230206.tar.gz)
Bonne soirée

**Comment by tcharp38** [comment]
Tu n'as pas eu d'erreur du coup. Je me trompe ?
Tu peux refaire plusieurs essais pour confirmer et me filer les logs si tu vois toujours une erreur au démarrage.

**Comment by Jeedom122** [comment]
Non et je viens de redémarrer le serveur jeedom, pas d'erreur.
Voici les logs
[AbeilleLogs-230207.tar.gz](https://github.com/KiwiHC16/Abeille/files/10674921/AbeilleLogs-230207.tar.gz)

**Comment by Jeedom122** [comment]
Effectivement il n'y a pas eu d'erreur, et je viens de redémarrer le serveur jeedom, pas d'erreur non plus. :)
Voici les logs
[AbeilleLogs-230207.tar.gz](https://github.com/KiwiHC16/Abeille/files/10674940/AbeilleLogs-230207.tar.gz)

**Comment by tcharp38** [comment]
Je confirme que l'erreur est filtrée.
On peut clore ce sujet du coup ?

**Comment by Jeedom122** [comment]
OK, je clos le sujet.
Merci pour les différentes corrections.
Bonne journée
