### ISSUE TITLE
Ajout NodOn SIN-4-2-20 - Micromodule d'éclairage ZigBee 2 sorties 3A 

### ISSUE THREAD

**Issue by chimini21** [KiwiHC16/Abeille#2541]
Bonjour,
serait-il possible d'ajouter le module ci dessous dans abeilles?
NodOn SIN-4-2-20 - Micromodule d'éclairage ZigBee 2 sorties 3A 

Merci d'avance à toute l'équipe

[discovery-undefined_NodOn (3).zip](https://github.com/KiwiHC16/Abeille/files/10543471/discovery-undefined_NodOn.3.zip)

![nodon 2 relais](https://user-images.githubusercontent.com/124026579/215683957-dedf88ce-1d84-43b4-8a15-61085641c21b.PNG)

**Comment by tcharp38** [comment]
Salut @chimini21 
Peux tu relancer l'assistant de decouverte ? Tu dois avoir tous les boutons au vert ou grisés.

Il me manque surtout le 'modèle' comme dans cet exemple
![image](https://user-images.githubusercontent.com/35221038/215722637-e1b73336-c6df-4081-b6b7-1d28fd357877.png)

Je vais faire un modele mais il sera en ligne avec la derniere beta.
Donc soit tu bascules sur la beta, soit tu devra patienter pour la prochaine release.

**Comment by chimini21** [comment]
L'information ne s'affiche pas.
je vais essayer de le réinclure demain.
Merci pour le retour rapide.

**Comment by tcharp38** [comment]
Peux tu me filer le package de logs (page maintenance/telecharger tout) apres avoir retenté avec l'assistant ?
Attention mode debug obligatoire.

**Comment by chimini21** [comment]
Bonjour,
toujours pas de modèle après re inclusion "fastidieuse".
L'équipement en question à l'ID 230 inclusion vers 20h25.
merci
 
[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/10560910/Downloads.zip)

**Comment by tcharp38** [comment]
Je vois 2 soucis.
1/ tu es sur la stable et non pas la beta donc ca ne risque de pas aboutir. Trop de changements depuis
2/ Je vois un bug lié à la chaine d'identification assez pourrie de ce device. Je dois modifier le code pour nettoyer un peu mieux ces caracteres.
 
![image](https://user-images.githubusercontent.com/35221038/216163154-48431fb5-96d7-4ea1-805a-689e05f5e7e2.png)

Donc prochaine beta.
Pas de date pour la stable pour l'instant.

**Comment by chimini21** [comment]
Bonsoir, voici les nouveaux log suite au passage en BETA et à ta version de ce jour. 
pas sur que cela fonctionne. voir vers 20h57
Merci de ton retour
[Uploading AbeilleLogs-230202 (1).tar.gz…]()

complément
[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/10573025/Downloads.zip)

**Comment by tcharp38** [comment]
Ca n'est pas encore ca.
Je dois revoir le code. Désolé.

> [2023-02-02 21:10:52]   ModelIdentifier='SIN-4-2-20        ÌË  ±    =', cleaned='SIN-4-2-20ÌË±='

A l'avenir ne me file que le package de logs. Il est complet, mais attend bien que l'upload soit terminé.
La j'ai du utiliser ton complément, l'autre n etant pas dispo.

Encore un truc... taille des logs bien trop courte. Tu aurais du avoir un message reclamant au moins 5000 lignes non ?

**Comment by chimini21** [comment]
salut,
ok merci, c'est pas grave, c'est déjà cool de développer aussi rapidement.
Tu le vois comment que l'upload est terminé?
pour les 5000 lignes j'ai bien vu mais je pensais que ca ciblait
suffisamment le module.
Cordialement

**Comment by tcharp38** [comment]
Peux tu decompresser ce code dans core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/10578084/AbeilleParser.class.php.zip)

puis redemarrer Abeille
refaire inclusion
et me filer les logs ?

**Comment by chimini21** [comment]
Inclusion fait vers 13h19
dis moi si tu en as assez

**Comment by tcharp38** [comment]
Dommage... pas de logs :(

**Comment by chimini21** [comment]
dans quel fichier il faut regarder? que je vérifie avant d'envoyer

**Comment by tcharp38** [comment]
J'ai besoin du package, dans lequel je vais regarder AbeilleParser en premier.

**Comment by chimini21** [comment]
[2023-02-03 16:08:15]   ModelIdentifier='SIN-4-2-20       ÌË  ±   =',
cleaned='SIN-4-2-20ÌË± ='
[2023-02-03 16:08:15]   deviceUpdate('modelId', 'SIN-4-2-20ÌË± ='):
Status=discovering

**Comment by tcharp38** [comment]
Sur d'avoir utilisé mon dernier code ?

**Comment by chimini21** [comment]
Oui
Après j'ai laissé l'autre en old dans le dossier.
Problématique ?

**Comment by tcharp38** [comment]
Le .old n'est pas problematique.
Mais je ne comprends pas cette trace si nouveau code.
Il faut que je trouve une solution pour faire des essais de mon cote

**Comment by tcharp38** [comment]
Mon code était daubé.

Nouvel essai avec celui la
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/10580749/AbeilleParser.class.php.zip)

**Comment by chimini21** [comment]
ça ressort mieux le nom.

**Comment by tcharp38** [comment]
Donc tu dois pouvoir me refaire un discovery, complet cette fois avec tous les voyants au vert.
Et file moi le package de logs suite à ca STP

**Comment by chimini21** [comment]
Salut,
désolé du retour tardif, pas eu le temps hier.
Tout ne passe pas au vert, a voir si tu as ce qu'il faut.
merci

[image: image.png]

**Comment by tcharp38** [comment]
Salut
Qu'est ce qui ne passe pas au vert ?
Peux tu me faire un snapshot ? J'ai l'impression que tu as voulu mettre une image mais elle n'est pas dispo.

**Comment by chimini21** [comment]
[image: image.jpg]

**Comment by tcharp38** [comment]
Ne repond que via l'interface WEB de Gihub. Les retours via email ne fonctionnent pas avec les attachements.
du coup ... toujours pas d'image ou autre info dispo.
Tu peux verifier par toi meme via l'onglet "preview" avant d'envoyer le commentaire.

**Comment by chimini21** [comment]
voici les fichiers.

[Uploading Downloads.zip…]()

**Comment by tcharp38** [comment]
Je suis désolé.. encore loupé.
C'est toujours marqué "uploading" donc tu as du etre trop rapide et pas laisser finir.

Pense au "preview" pour t'assurer que ta livraison est correcte.

**Comment by chimini21** [comment]
Salut, 
désolé du retour tardif, mas eu le temps ces derniers jours.


[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/10704509/Downloads.zip)

**Comment by tcharp38** [comment]
Salut 

docs:
https://nodon.fr/wp-content/uploads/2021/04/NodOn_Zigbee_ON-OFF-LightingRelaySwitch_SIN-4-2-20-Datasheet_FR.pdf
https://nodon.fr/download/539/user-guide/23096/p1900-sin-4-2-20_pro-ug-v1_digital.pdf

Modele preliminaire a decompresser dans core/config/devices
[SIN-4-2-20_NodOn.zip](https://github.com/KiwiHC16/Abeille/files/10706601/SIN-4-2-20_NodOn.zip)
puis 
- redemarrer Abeille
- refaire inclusion

Attention!! En ligne avec la derniere beta. Il se peut qu'il manque des commandes si tu restes sur la stable.

**Comment by eoeir** [comment]
J'ai le même module mais je l'avais laissé de côté car j'avais d'autres priorités. Je viens de tester avec la dernière beta : le module est bien reconnu.

![image](https://user-images.githubusercontent.com/71673288/219951371-6465d77c-5da6-4a90-80da-67de8cad2f6e.png)

Les deux commandes ON/OFF fonctionnent bien.

La commande Set Level est inutile, elle allume le 2eme circuit dès qu'elle est mise à 1%, aucune variation au-delà.

Je mets un package de logs si ça peut t'aider à affiner l'analyse.
[AbeilleLogs-230219.tar.gz](https://github.com/KiwiHC16/Abeille/files/10777001/AbeilleLogs-230219.tar.gz)

Et voici une image png avec transparence pour la mise à jour du modèle
![nodon-sin-4-2-20-module-zigbee-on-off](https://user-images.githubusercontent.com/71673288/219952138-40c8f79d-1f1e-4fbf-8fc2-d23f24c89337.png)

**Comment by tcharp38** [comment]
@eoeir 
Ce module est just un switch 2 canaux ou on peut faire varier la luminosité des ampoules connectées.
Que dit la doc ?

Merci pour l'image.

**Comment by eoeir** [comment]
C'est juste un switch 2 canaux, pas de fonction dimming : 
https://www.nodon.fr/nodon/module-eclairage-on-off-zigbee/
https://nodon.fr/wp-content/uploads/2021/04/NodOn_Zigbee_ON-OFF-LightingRelaySwitch_SIN-4-2-20-Datasheet_FR.pdf

**Comment by tcharp38** [comment]
Ok merci. Je corrige le modele pour la prochaine beta.

**Comment by tcharp38** [comment]
@eoeir 
Il y a encore qqch à faire pour ce sujet ?.

**Comment by eoeir** [comment]
Je ne vois pas la nouvelle image du module malgré une réinitialisation. Normal ?

**Comment by tcharp38** [comment]
Tu as fait "mise-à-jour" ou "reinit" ?
La premiere ne change pas les trucs qui peuvent etre customisés par l'utilisateur, dont l'icone.
La 2ieme devrait se realigner sur le modele.

L'image semble etre la bonne sur le master donc dans chaque beta depuis.

**Comment by eoeir** [comment]
J'ai bien fait une réinit.
Je peux tenter une suppression puis réinclusion quand j'ai 5 mins.

**Comment by tcharp38** [comment]
Je pige pas. Le "reinit" aurait du remettre l'icone du modele.
Tu peux verifier que l'image qui est dans ton repo est la bonne ?

**Comment by eoeir** [comment]
Je te confirme que c'est la bonne image qui est dans /var/www/html/plugins/Abeille/images

**Comment by tcharp38** [comment]
Ok donc vu qu'il n'y en a qu'une... c est ton navigateur qui n est pas rafraichi et utilise toujours une vieille surement de son cache.
Ctrl F5 ?

**Comment by eoeir** [comment]
Pas de changement... 

![image](https://user-images.githubusercontent.com/71673288/223564701-a75fe5b0-b3b8-428f-b8f8-3719bbfdf617.png)

Sur l'équipement l'image est cassée et le lien pointe vers plugins/Abeille/images/node_null.png

![image](https://user-images.githubusercontent.com/71673288/223564958-1bf1784c-51e2-4133-a27a-f8c4e3085a8d.png)

Si je sélectionne manuellement l'image du module Nodon, elle s'affiche correctement.

![image](https://user-images.githubusercontent.com/71673288/223565119-d802816c-d73b-4b36-80b6-fd9720f2f03e.png)

**Comment by tcharp38** [comment]
ok, donc il y a un autre bug.

Du coup tout est revenu en ordre ?

**Comment by eoeir** [comment]
Après la sélection manuelle de l'image, oui.

**Comment by tcharp38** [comment]
Pour le pb d'image je le mets dans ma liste. Peut etre une idée pour éviter ca.

Pour ce sujet, on peut le fermer ?

**Comment by eoeir** [comment]
Pour moi oui, mais je ne suis pas l'auteur.

**Comment by tcharp38** [comment]
Je clos.
A réouvrir si soucis ou manques.
