### ISSUE TITLE
LoraTap Zigbee 3 gang remote (id = TS0043, _TZ3000_famkxci2)

### ISSUE THREAD

**Issue by Sososoja** [KiwiHC16/Abeille#2542]
Salut tcharp38,
J'ai voulu ajouter cette télécommande pour lancer des scènes, elle est dans le listing mais n'est pas reconnu.
Ci joint les logs après l’appairage.
Merci 
[AbeilleLogs-230204.tar.gz](https://github.com/KiwiHC16/Abeille/files/10609149/AbeilleLogs-230204.tar.gz)

**Comment by tcharp38** [comment]
Tu peux tenter avec l'assistant ?
Pour faire passer tous les voyants au vert, n'hesite pas a cliquer souvent sur la telec pour qu'elle se reveille et recoive les requetes.

**Comment by tcharp38** [comment]
Et il me faudra 
- une ref/modele
- une image PNG sans arriere plan

**Comment by tcharp38** [comment]
En fait decompresse ce modele dans core/config/devices/TS0043__TZ3000_bi6lpsew
[TS0043__TZ3000_bi6lpsew.zip](https://github.com/KiwiHC16/Abeille/files/10665194/TS0043__TZ3000_bi6lpsew.zip)

redemarre Abeille
et refais une inclusion

**Comment by Sososoja** [comment]
J'ai mis le zip que tu m'as donné et tout fonctionne, chaque boutons permet de faire un ou deux appuis et l'image de la commande remonte également dans abeille.
Plus qu'a créer un virtuel !

**Comment by tcharp38** [comment]
Parfait. 
Sera dans la prochaine beta.

Je clos.
