### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by boxsters1423** [KiwiHC16/Abeille#2543]
J'ai cette erreur dans le log http.error

[Sat Feb 04 18:17:52.408737 2023] [php7:notice] [pid 3304] [client 84.226.201.34:53465] PHP Notice:  Undefined variable: path in /var/www/html/plugins/Abeille/core/ajax/AbeilleFiles.ajax.php on line 301, referer: monprotocole://monadresse:monport/index.php?v=d&m=Abeille&p=AbeilleMaintenance

Kernel: ["Linux jeedom 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU\/Linux"]

Version Abeille: 230102-STABLE-1

Zigate 1
 - FW version: 0003-0321
 - Channel   : 11
 - Type      : WIFI

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Saurais tu me dire quelle action tu as fait pour déclencher cette erreur ?

**Comment by tcharp38** [comment]
Salut @boxsters1423 
Je clos le sujet ne pouvant le reproduire et pas d'autre retour de ce type.
Si jamais ca revient et que tu as + d'infos, je te laisse le reouvrir.
Merci
