### ISSUE TITLE
Support LIVARNO Home LED floor lamp (id =TS0502A, _TZ3000_8uaoilu9)

### ISSUE THREAD

**Issue by sebgeekinside** [KiwiHC16/Abeille#2544]
Lampadaire à LED LIVARNO en vente via LIDL.
Apparait via le plugin Abeille à travers le modèle : TS0502A

Apparait via Zigbee2MQTT à travers le modèle : 14153905L - https://www.zigbee2mqtt.io/devices/14153905L.html

[discovery-TS0502A__TZ3000_8uaoilu9.zip](https://github.com/KiwiHC16/Abeille/files/10609902/discovery-TS0502A__TZ3000_8uaoilu9.zip)

Température de couleur min. : 3 000 K
Température de couleur max. : 6 500 K

**Comment by tcharp38** [comment]
Bonjour

Voila un modele de test mais qui ne sera probablement compatible qu avec la beta du moment ou la prochaine stable.
[TS0502A__TZ3000_8uaoilu9.zip](https://github.com/KiwiHC16/Abeille/files/10664948/TS0502A__TZ3000_8uaoilu9.zip)

A decompresser dans core/config/devices

il me faut aussi une belle image PNG sans arriere plan à mettre en icone.

**Comment by sebgeekinside** [comment]
Effectivement, via la dernière version stable 2023-01-03 01, cette définition de modèle induit des erreurs.
A voire suite à prochaine version stable à venir...

![image](https://user-images.githubusercontent.com/87441712/217080940-be24df42-f418-4edf-a3f6-ce82069e08b4.png)

**Comment by tcharp38** [comment]
Oui je m'y attendais un peu. 
Désolé je peux pas perdre du temps à faire des modeles déja obsoletes et je dois me focaliser sur la prochaine stable.
A suivre...

**Comment by sebgeekinside** [comment]
A travers le version stale 2023-05-29 01:00:31, je constate que ce lampadaire est à présent reconnu en tant que 'Livarno Home LED floor lamp'.
Les commandes actions On 1/Off 1 ainsi que Set Level (intensité lumineuse) sont opérationnelles.

Ce modèle intègre un éclairage lumière blanche dans une gamme de température de 3 000 K à 6 500 K.

En testant différentes commandes actions, je ne vois pas comment modifier la température de lumière blanche.

Est-ce que cette version du plugin intègre cette fonctionnalité de modification de température de lumière blanche ?

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Tu peux me montrer un snapshot de cet equipement sur le dashboard ?

C'est une ampoule couleur + blanc ? Ou juste blanc ?

**Comment by sebgeekinside** [comment]
> Salut @sebgeekinside Tu peux me montrer un snapshot de cet equipement sur le dashboard ?
> 
> C'est une ampoule couleur + blanc ? Ou juste blanc ?

Ci-dessous la capture des commandes infos ou actions affichés par défaut sur le dashboard de l'équipement :
![image](https://github.com/KiwiHC16/Abeille/assets/87441712/da9e9a65-a9a5-4db7-9d93-b8c5c7d66259)
Le bouton 'White' (tout comme les boutons Blue', 'Red' et ' Green') n'entraine aucune modification.
Il existe sur l'équipement d'autres commandes info/action dont une commande info 'ColorTemperature' de valeur '153' et une commande info 'Color Mode' de valeur '2''.
Il n'existe pas de commande action pour modifier la température de couleur ou modification du mode couleur.

Le modèle que je possède est un lampadaire uniquement de lumière blanche.

**Comment by tcharp38** [comment]
Donc c'est bien ca le modele n'est pas à jour.
Je vire tout ce qui est controle de couleur. Ca n'a aucun sens
et j'ajoute le controle de temperature

Tu peux tester avec ce modele ? Une "mise à jour" via la page equipement/avancé devrait suffire
[TS0502A__TZ3000_8uaoilu9.zip](https://github.com/KiwiHC16/Abeille/files/12249972/TS0502A__TZ3000_8uaoilu9.zip)

Tout est dans la beta 230803-BETA-2 qui sera dispo demain le 4/8/23.

**Comment by sebgeekinside** [comment]
Je viens de tester le modèle que tu avais fourni.

Pour que mon équipement soit correctement reconnu, j'ai dû retirer la ligne 10 ("genericType": "Light",).
Avec cette modification et après quelques tests, la modification de température de lumière blanche semble fonctionnelle sur la plage [3 000 K, 6 500 K].
Merci ! :-)

Petite remarque en plus de la ligne 10 à retirer au sein du modèle : il semble que la commande info ColorTemperature ne soit pas mise à jour avec la valeur de la température définie.

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Je ne comprends pas cette histoire de "genericType". C'est une info à garder donc il m'en faut plus.
Qu'est ce que ca engendre ? Le widget sur le dashboard est different ? Comment en est tu arrivé à supprimer cette ligne ?

**Comment by sebgeekinside** [comment]
Hello,

bon... je viens de tester en remettant la ligne "genericType": "Light" dans le fichier TS0502A__TZ3000_8uaoilu9.json.
J'ai supprimer le device, relancé le demon du Plugin puis lancer une nouvelle inclusion qui cette fois-ci a reconnu correctement le modèle du device !
J'ai donc peut-être été vers une mauvaise piste de problème... 

J'ai donc laissé la ligne dans le fichier json.

En revanche, comme indiqué dans mon message précédent, la commande info ColorTemperature n'est pas mise à jour avec la valeur de la température définie.
![image](https://github.com/KiwiHC16/Abeille/assets/87441712/4a51354e-e0cf-49b8-a5bb-6386fb3c12b9)

Te faut-il des log pour investiguer ?

**Comment by tcharp38** [comment]
Je préfère ça.
Du coup le color temp est suppose etre en ligne avec set color temp. Donc peux tu faire un set color temp et me filer les logs qq mins après ?

**Comment by sebgeekinside** [comment]
Voici les log, en ayant déclenché à plusieurs reprises la commande action Set Color Temp (autour de 11:22:46).
[AbeilleLogs-230903.tar.gz](https://github.com/KiwiHC16/Abeille/files/12505627/AbeilleLogs-230903.tar.gz)

Je me rends compte que je n'ai pas été très précis auparavant dans les différentes commandes qui ne semblent pas fonctionner quant à la gestion de la température de la lumière blanche.
Certes, comme déjà indiqué, la commande info ColorTemperature n'est pas mise à jour avec la valeur de la température définie mais ça n'est pas tout.
L'utilisation de la commande action Set Color Temp ne semble pas fonctionner non plus : suite à utilisation de cette commande, il n'y a pas de changement de température de la lumière sur la barre lumineuse.

**Comment by tcharp38** [comment]
Tres etrange.
J'ai déja vu ca mais jamais expliqué.
Ton device (CB20) fait un reporting, par contre des qu'on l'interroge qq secondes plus tard il ne recoit pas l' info.

Du coup tes "Set Color temp" n'arrivent pas au device, raison pour laquelle rien ne se passe.

    [2023-09-03 11:22:05] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=CB20, DstAddrMode=02, DstAddr=0000
    [2023-09-03 11:22:05]   FCF=18/General/Serv->Cli, SQN=38, cmd=0A/Report attributes
    [2023-09-03 11:22:05]   AttrId=0000/OnOff, AttrType=10, ValueHex=01 => 1
    [2023-09-03 11:22:09] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=CB20, EP=01, ClustId=0006, SQNAPS=BF

Vu que tu as 2 reseaux, t es t'il possible de tester ce device sur la Zigate Wifi qui est une v1 (au lieu de la Zigate 1 en v2) ?

**Comment by sebgeekinside** [comment]
J'ai migré le device vers ma seconde Zigate via la fonctionnalité du plugin Abeille.
Voici les log, en ayant déclenché la commande action Set Color Temp (autour de 11:10:52) qui fonctionne.
[AbeilleLogs-230909.tar.gz](https://github.com/KiwiHC16/Abeille/files/12565387/AbeilleLogs-230909.tar.gz)

**Comment by tcharp38** [comment]
Tu dis que ca fonctionne ?
Donc ca confirme ma crainte... le FW de la Zigate v2 est encore en cause.
Si on n'en a pas encore parlé, je te suggere de faire une mise à jour de ce FW. Mais à garder en tete que le dernier, meme si corrige certains points importants, il n'est malheureusement toujours pas au niveau d'une zigate v1 :(

**Comment by sebgeekinside** [comment]
Sur cette seconde Zigate (Zigate Wifi en v1), la commande action Set Color Temp fonctionne.
En revanche, la commande info ColorTemperature n'est toujours pas mise à jour avec la valeur de la température définie.
À l'image de la capture fournie dans mon post [ci-dessus](https://github.com/KiwiHC16/Abeille/issues/2544#issuecomment-1703761973) .

**Comment by tcharp38** [comment]
Ok je vois.
Il y a en fait bel et bien un retour mais la valeur n'est pas bonne du tout.
Je creuse

Memo

    [2023-09-09 11:10:50] -- execute([Salon][La barre lumineuse][Set Color Temp], type=action, options={"slider":"6500","user_login":"admin","user_id":"1"})
    [2023-09-09 11:10:50]   updateField(): Updated 'EP=01&slider=#slider#'
    [2023-09-09 11:10:50]   updateField(): To 'EP=01&slider=6500'
    [2023-09-09 11:10:50] -- execute(): Msg sent: {"topic":"CmdAbeille2\/6B2B\/setTemperature","payload":"EP=01&slider=6500"}
    [2023-09-09 11:10:50] Msg from 'xToCmd': {"topic":"CmdAbeille2\/6B2B\/setTemperature","payload":"EP=01&slider=6500"}
    [2023-09-09 11:10:50]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
    [2023-09-09 11:10:50]     processCmd({"setTemperature":"setTemperature","name":"setTemperature","priority":4,"dest":"Abeille2","EP":"01","slider":"6500","addr":"6B2B"})
    [2023-09-09 11:10:50]     TempK=6500 => Using tempMireds=0099, transition=0001
    [2023-09-09 11:10:50]     addCmdToQueue2(Pri=1, Net=Abeille2, Cmd=00C0, Payload=026B2B010100990001, Addr=6B2B, AddrMode=02)
    
    [2023-09-09 11:10:52] Abeille2, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0300, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=6B2B, DstAddrMode=02, DstAddr=0000
    [2023-09-09 11:10:52]   FCF=18/General/Serv->Cli, SQN=27, cmd=01/Read Attributes Response
    [2023-09-09 11:10:52]   AttrId=0007/ColorTemperatureMireds, Status=00, AttrType=21, ValueHex=0099 => 153
    
    [2023-09-09 11:10:52][DEBUG] : msgFromParser(): Read attributes response by name from 'Abeille2/6B2B/01
    [2023-09-09 11:10:52][DEBUG] :   'ColorTemperature' (0300-01-0007) => 153 K

**Comment by tcharp38** [comment]
Vu que tu n'es pas sur la beta, est ce que tu veux tester ce fichier apres avoir mis l'original de côté ?

A decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/12575933/AbeilleParser.class.php.zip)
puis redemarrer Abeille
tester le 'setTemp'
voir ce que ca donne
et filer le package de logs

Merci

**Comment by sebgeekinside** [comment]
Suite à remplacement par le fichier AbeilleParser.class.php.zip fourni puis modification de la température de la couleur blanche via la commande action Set Color Temp, la commande info ColorTemperature fonctionne :
![image](https://github.com/KiwiHC16/Abeille/assets/87441712/835a9c4c-a852-41b5-bbff-020fc87d1528)

Merci !

**Comment by tcharp38** [comment]
Super !
Je dois encore supprimer la virgule sur ColorTemp dans le modele. Ca n'a aucun interet.

D'autres points sur ce sujet ?

**Comment by tcharp38** [comment]
Si tu refais une inclusion avec ce modele, apres suppression, ou reinit à partir de sa page avancé tu ne devrais plus avoir de nombres apres la virgules.
[TS0502A__TZ3000_8uaoilu9.zip](https://github.com/KiwiHC16/Abeille/files/12579201/TS0502A__TZ3000_8uaoilu9.zip)

**Comment by sebgeekinside** [comment]
> Super ! Je dois encore supprimer la virgule sur ColorTemp dans le modele. Ca n'a aucun interet.
> 
> D'autres points sur ce sujet ?

La modification de la température de couleur blanche ne fonctionne pas à travers l'app Google Home et mon dispositif :
Device via plugin Abeille <-> Plugin Google Smarthome <-> app Google Home.
Ceci, malgré la configuration du type générique à 'Lumière Température Couleur' pour la commande action Set Color Temp.
Mais pas sûr que ça soit en lien avec le plugin Abeille et la configuration pour ce device.
Je n'ai pas d'autres device avec possibilité de faire varier la température de la couleur, je n'ai pas de moyen de comparaison.

Mise à part cela (désolé si ça n'est pas lié au plugin Abeille et la configuration pour ce device, je le mentionne juste au cas où...), je n'ai pas constaté d'autre point à remonter :-).

**Comment by tcharp38** [comment]
Tu peux faire un truc.
Déclencher la modif de couleur via ton app, et me filer l'heure+le package de logs dans la foulée.
Au moins on peut voir ce qui se passe coté Abeille et si il recoit toutes les infos necessaires.

**Comment by tcharp38** [comment]
@sebgeekinside 
Quel est le status de ce sujet ?

**Comment by sebgeekinside** [comment]
Je n'ai pas pu entreprendre de test tel que tu le décrivais le 18/09.
Suite à modification de procédé d'authentification côté Google, vis-à-vis du mode standalone du Plugin Google Smarthome, il ne m'est pour l'instant plus possible d'exécuter des commandes Jeedom via intégration standalone du Plugin Google Smarthome.

**Comment by tcharp38** [comment]
Ok.
Du coup peut on dire qu'a l heure actuelle aucun souci lié à Abeille ?
Si oui je ferme le sujet mais à reouvrir si pb Abeille confirmé.
Ca t'irais ?

**Comment by sebgeekinside** [comment]
Ça me va.

**Comment by tcharp38** [comment]
Ok. Je ferme
A réouvrir si pb Abeille

**Comment by sebgeekinside** [comment]
Je constate que la commande Information Status fournit une valeur correcte uniquement si au préalable j'ai lancer la commande Action Get Status.
Je m'attends à ce que la commande Information Status fournisse la valeur à jour sans avoir au préalable j'ai lancer la commande Action Get Status.

Que faut-il fournir comme log pour l'analyse ?

**Comment by tcharp38** [comment]
Salut @sebgeekinside 

Etrange. Soit il y a un bug qq part, soit ce FW ne supporte pas le reporting qui pourtant est bien demandé dans le modele.

Peux tu via l'onglet "avancé" du device essayer de configurer le reporting manuellement et me filer les logs dans la foulée ?

![image](https://github.com/user-attachments/assets/72887282-7a27-4251-934e-1b567dac1684)

**Comment by sebgeekinside** [comment]
Après avoir lancer Configurer - ZCL ; Configurer le reporting, la commande Info fonctionne à nouveau !
Merci ! :-)

**Comment by tcharp38** [comment]
Ça ne me plaît pas pour autant. Vu que c'est ce que doit faire la modèle peux t'assurer s'être ça fonctionne avec une "MISE À JOUR" ou "REINIT" dans le même onglet ?
