### ISSUE TITLE
Plugin abeille ne trouve pas le module Zigbee sur la jeedom Luna

### ISSUE THREAD

**Issue by Thiematz** [KiwiHC16/Abeille#2545]
Bonsoir,

tout est dit dans le titre, mais j'ai récemment fait l'acquisition de la nouvelle jeedom LUNA et je voulais utiliser le plugin Abeille, mais il m'est impossible d'inclure un équipement car le plugin ne trouve aucun module Zigbee.

Abeille peut-il fonctionner sur la LUNA ?

Je joins les logs si cela peut aider

Merci pour votre aide et bonne soirée
[AbeilleLogs-230206.tar.gz](https://github.com/KiwiHC16/Abeille/files/10669045/AbeilleLogs-230206.tar.gz)

**Comment by tcharp38** [comment]
Salut @Thiematz 
Merci pour les logs mais je crois que tu n'es pas en mode debug donc pas de trace utile.

Il y a qqch d'incoherent surement sur la page de config.
Le port de la zigate 1 n'est pas defini.
Celui de la zigate 2 l'est mais elle.. n'est pas activée.

Mets moi un snapshot de la page de config aussi STP en + des logs en mode debug (sauvegarde + redemarrage Abeille)

**Comment by Thiematz** [comment]
@tcharp38 ,

Je te joins les log, avec en plus deux copies d'écran. L'une de la config Abeille et l'autre celle de Zigbee, peut-être que cela peut te donner des infos.

Alors effectivement, La Zigate 1 et 2 sont mal définies, mais c'est parce que je ne sais pas quel type de module selectionner. J'ai tout essayé et aucune ne match visiblement.

[AbeilleLogs-230207.tar.gz](https://github.com/KiwiHC16/Abeille/files/10678528/AbeilleLogs-230207.tar.gz)
![Zigbee](https://user-images.githubusercontent.com/94549335/217340676-daccaa73-ebac-46a8-a50a-e69f7594ab29.PNG)
![Abeille](https://user-images.githubusercontent.com/94549335/217340705-dad87135-d8e6-40ab-8644-83fa0ec17ac4.PNG)

**Comment by tcharp38** [comment]
Bon j'ai besoin de comprendre du coup.
Tu veux mettre combien de zigates sous Abeille ?
Et quel type ?

L'image du plugin zigbee n'apporte rien vu qu'il ne s'agit pas d'une zigate mais d'un autre controlleur.

Pense a activer le mode debug. Tes logs sont vides.

**Comment by Thiematz** [comment]
En fait, j'ai acheté une LUNA Zigbee, et j'aimerai pouvoir utiliser le plugin Abeille plutot que le Zigbee.
J'ai donc testé les différentes possibilité, sur le plugin zigbee il est fait mention du module "POPP", est-ce un indice pour trouver le bon port à utiliser dans Abeille ?
J'ai activé le mode debug et relancé le demon, sachant très bien que les zigates sont mal configurées. Mais au final e ne souhaite en utiliser qu'une. J'aimerai utiliser le module interne à la box plutôt que de devoir rebrancher un hub usb
[AbeilleLogs-230208.tar.gz](https://github.com/KiwiHC16/Abeille/files/10686933/AbeilleLogs-230208.tar.gz)

**Comment by tcharp38** [comment]
Ha je crois que je commence à piger.
Abeille ne gère QUE les Zigates. Donc tout autre type de clef... pas bon.
POPP est un autre type de clef Zigbee.

Cette box integre donc une clef Zigbee par défaut, autre que Zigate.
Mais tu dois pouvoir aussi ajouter une Zigate je suppose.
De quel type s'agit il ? USB ? PI ? v1 ? v2 ?

**Comment by Thiematz** [comment]
Ah mince, donc c'est mort sans un dongle additionnel ?

**Comment by tcharp38** [comment]
Abeille sans Zigate.. oui ca c'est mort.
Maintenant peut etre que tu peux ajouter une zigate USB sur la Luna mais encore faut il que ca fasse du sens.
Le plugin Zigbee ne te convient pas ?

**Comment by Thiematz** [comment]
Disons que je le trouve moins bien qu'Abeille.
A voir si l'équipe derrière ce plugin est aussi réactive que toi/vous.
J'ai des modules qui ne s'intègrent pas bien alors qu'ils sont super bien gérés par Abeille

**Comment by tcharp38** [comment]
Ca fait plaisir à lire.
Mais bon si tu as une zigate USB tu peux tenter de la mettre sur le port USB de la Luna.

**Comment by Thiematz** [comment]
J'vais pas avoir le choix, même si je voulais éviter ça.
En tout cas merci ;-)
