### ISSUE TITLE
Problème Zigate v2

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2546]
_Pour hsitorique_

Salut,
Il y a des jours, comme celui ci, ou tu te demandes si tu ne devrais pas arrêter la domotique...

J'ai 5 nouveau interrupteur à intégré que je ne parviens pas à intégrer...
J'en ai déjà 4 sur ma zigate et abeille que j'ai intégrer il y a plusieurs moi, pourquoi je n'arrive pas a intégrer ceux la...

Avant que je ne pête un plomb et format ma zigate, ou envoie tout promener et passe chez l'énemie ou je ne sais pas quoi encore.
Est ce que quelqu'un pourrait me dire si quelque chose apparait dans mes log ?

Je suis bien sur le canal 11 (je me suis déjà fait avoir).
J'ai utilisé moult procédures différentes. Dont celle qui marchait pour les 4 premiers.
Je commence a me dire que la zigate me joue encore des siennes...

Merci

[AbeilleLogs-230218.tar.gz](https://github.com/KiwiHC16/Abeille/files/10775169/AbeilleLogs-230218.tar.gz)

**Comment by Jake309** [comment]
Je viens de tester avec une clé zigbee Popp sur le plugin officiel zigbee, est l'intégration est immédiate :( 
Le problème vient donc d'Abeille ou de la zigate, je penche sur la 2ème possibilité, mais a voir

**Comment by Jake309** [comment]
J'ai réinitialisé la zigate, c'est redevenue fonctionnelle.
Toujours canal 11, appuie de 8s, la led rouge clignote on relache, ca passe magenta ou vert direct.

Par contre, j'ai des bug de mode inclusion.
Quand j'appuie sur le +, ma zigate ne réagie pas tout le temps. Je ne sais pas ce qui cause ca :/

PS: Zigate commence a m'irriter

**Comment by Jake309** [comment]
Il y a un problème non négligeable je pense.
J'ai flashé la zigate, en effacant tout. Quand j'ai réinitialisé un volet pour le réintégrer, abeille me notifie qu'il a quitté le réseau, alors que le plugin ne devrait pas le savoir car la zigate est censé être vierge ?

[AbeilleLogs-230219.tar.gz](https://github.com/KiwiHC16/Abeille/files/10776494/AbeilleLogs-230219.tar.gz)

**Comment by Jake309** [comment]
Je viens d'avoir ce message : 
![image](https://user-images.githubusercontent.com/49479084/219950152-bd41c68e-c881-4c5c-9b83-1d69d86396e6.png)

J'ai réussi a intégré 3 volets éxistant et 1 nouveau.
Mais une fois les 4min terminées, plus possible de remettre la zigate en inclusion

[AbeilleLogs-230219 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10776943/AbeilleLogs-230219.1.tar.gz)

**Comment by Jake309** [comment]
Tout mes volets sont intégrés.
J'ai une latence de 2min entre l'ordre et l'action (ouverture ou fermeture)

dernier essai, volet bureau : 14h45:58 remonté a 14h47:58 14h48:00 environ

[AbeilleLogs-230219.tar.gz](https://github.com/KiwiHC16/Abeille/files/10777036/AbeilleLogs-230219.tar.gz)

J'attends avant de tout réintégrer

**Comment by tcharp38** [comment]
Salut @Jake309 
Desolé pour tes déboires.
Je  creuse tes logs mais oui je comprends qu'elle t'irrite. Moi aussi, de + en +.

**Comment by tcharp38** [comment]
> Il y a un problème non négligeable je pense. J'ai flashé la zigate, en effacant tout. Quand j'ai réinitialisé un volet pour le réintégrer, abeille me notifie qu'il a quitté le réseau, alors que le plugin ne devrait pas le savoir car la zigate est censé être vierge ?

Si tu as un message "a quitté le reseau" c'est qu'Abeille a recu un message indiquant que le device venait de quitter le reseau.
Ca arrive la plupart du temps sur un reset du device. Le message vient de la zigate. Abeille n'invente rien.
Du coup comment as tu "éffacé" la zigate ?

**Comment by Jake309** [comment]
> > Il y a un problème non négligeable je pense. J'ai flashé la zigate, en effacant tout. Quand j'ai réinitialisé un volet pour le réintégrer, abeille me notifie qu'il a quitté le réseau, alors que le plugin ne devrait pas le savoir car la zigate est censé être vierge ?
> 
> Si tu as un message "a quitté le reseau" c'est qu'Abeille a recu un message indiquant que le device venait de quitter le reseau. Ca arrive la plupart du temps sur un reset du device. Le message vient de la zigate. Abeille n'invente rien. Du coup comment as tu "éffacé" la zigate ?

J'ai fait une mise a jour du firmware en écrasant tout. L'option de tout supprimer sur le wiki de mise a jour. 
C'est pour ça que ça m'étonne quabeille, car je suis d'accord,ça vien de la zigate. mais elle est censé être vierge comme si je venais de l'acheter.

**Comment by Jake309** [comment]
> Salut @Jake309 Desolé pour tes déboires. Je creuse tes logs mais oui je comprends qu'elle t'irrite. Moi aussi, de + en +.

Salut @tcharp38 
Ce n'est pas de ta faute, n'en soit pas désolé :) 
Jen suis a un point où je ne sais plus quoi faire.
Abeille me satisfait tellement. Le plugin ZigBee officiel est plein d'erreur et de problème, je trouve ça inadmissible pour de l'officiel, je l'ai testé, c'est affreux, jamais je tournerai dessus.
Il reste quoi comme solution si on abandonne tous, acheter des passerelles de chaque marque, et utilisé jeedom comme concentrateur. J'y pense très sérieusement, mais ça va a l'encontre de ma politiques "no cloud"... Mais des fois, pour plus de tranquillité....

**Comment by tcharp38** [comment]
C'est ta zigate v1 ou ta v2 que tu as a reflashé et effacé ?

La solution de marque est surement (j'espere) + stable et robuste mais elle risque aussi de restreindre les devices supportés.
Ceci etant ca peut etre une bonne solution.
Le cloud est toujours requis ?

**Comment by Jake309** [comment]
C'est ma v2. 

En fait quand je dis cloud, c'est que ta passerelle est forcément connecté au serveur de la marques donc ils ont accès à ce qu'ils veulent en fonction des CGU. Après ça reste un billet en fonction des marque que tu as. Et dans mon cas, comme je me suis amusé à tester plein de truc avec le zigzte, il faudra aussi que je réduise le nombre de marque :/  ou pour quelques, je continue à utiliser une clé multimarque. 
Mais encore, j'ai pas envie. Abeille et ta dispo pour le faire évoluer est top

**Comment by tcharp38** [comment]
Ok, pour etre clair, meme si je n'ai pas de v2 (j'ai 5x v1), mon sentiment au vu des differents retours et soucis est que la v2 est bien moins stable que la v1. Cette stack NXP est desastreuse :(

Pour ton souci sur la v2, est ce qu'un reset SW remet les choses en place ?
Quel est le status la ? Toujours aussi pourri ?
En fait idealement j'aurais besoin des logs qui couvrent le moment ou ca fonctionne et le passage en "ca merde".

**Comment by Jake309** [comment]
Je partage ton avis, le V2 est bien en deça de la V1, et même en dev, je me demande si elle est pas à l'abandon, souvient toi de mon module orvibo qui créait des device fantome, donc correctif en pre-release est pire que la stable avec le bug, et sa version avec plein de correctif qui devait sortir le mois suivant n'a jamais vue le jour...

Je pense que je vais repasser sur ma V1 avant de m'enflammer à acheter des passrelles.
Je suis pas trop chez moi cette semaine, donc je pourrais pas te dire tout de suite, mais je demanderai à ma femme. après avoir tout réintégré, j'ai l'impression qu'une magie s'est opéré, j'ai eu du moyeux sur tout ce qui est luminaire etc.
Mais les volets, qui était avant le must face a tout le reste, est bien derrière. 2min de latence, pas de retour d'état en automatique.
Oula, pour trouver des log de l'époque ou ca marché, je vais regarder dans de vieille issue ou j'avais déjà les volets si tu veux.

Mais très franchement, je ne pense pas que ce soit abeille. Déjà à l'époque our tout marchait bien, un jour reaction instantané, le lendemain les lumières s'allumaient les unes à la suites des autres, ou alors latences de plusieurs secondes. 
C'est ce qui est le plus frustrant. Tout roule et sans que tu n'ai rien fait, ca merde. Tu vas te coucher, le lendemain c'est de nouveau au top...
On a pas la main sur la zigate, le problème est la. J'ai voulu apporter mon aide avec le orvibo, mais quand je vois que ca ma couté du temps, un envoie postale etc pour finalement meme pas avoir un correctif viable, ca en dit long sur le sérieux je pense :/

**Comment by tcharp38** [comment]
> Je partage ton avis, le V2 est bien en deça de la V1, et même en dev, je me demande si elle est pas à l'abandon, souvient toi de mon module orvibo qui créait des device fantome, donc correctif en pre-release est pire que la stable avec le bug, et sa version avec plein de correctif qui devait sortir le mois suivant n'a jamais vue le jour...

Je me souviens bien.
Et oui plus beaucoup de réaction et de mises à jour :( C'est pourquoi je conseille de n'investir si besoin que dans une v1, et d'occase. Il y en a des tonnes sur LBC. Et à petit prix.. ca peut la rendre encore un peu interessante mais surement pas neuve.

Pour ton souci, meme si on ne peut pas forcement faire grand chose coté Abeille, comprendre ce qui fout la zigate en vrac est clef.

**Comment by Jake309** [comment]
J'ai cette issue la : https://github.com/KiwiHC16/Abeille/issues/2529
Mais si je n'utilise pas de matos pendant le temps des log, tu ne verras pas grand chose.
Mais c'est ce que j'ai de mieux :/

La V1, tu recommande en OPDM ou Legacy ?

**Comment by tcharp38** [comment]
Le 2529 est clos. Donc tu as toujours des soucis ?

V1 en OPDM dernier FW c'est ce qu'il y a de + propre à ma connaissance côté Zigate.
Mais j'aimerais bien, si je trouvais le temps, me pencher sur le support d'une autre clef.. Sonoff en Zstack. Ca semble etre un FW bien + propre. Mais la ca n'est pas du court terme.

**Comment by Jake309** [comment]
Non, le sujet était pour une intégration, mais le module existait déjà. J'ai un fantome qui est apparue en même temps que le micromodule legrand ^^.
C'est pour que tu puisse récupérer des log pas trop vieux avec mes volets etc, avant de passer à du pourri

Ouep, je te comprends, le temps est devenu tellement rare... C'est un truc de fou. Ou j'en fais trop et métale trop dans différents domaines. La vie de famille ca chamboule bien l'orga aussi :) 
En tout cas, si un jour je peux t'aider dans quoi que ce soit, c'est le sujet pour lequel je peux investir du temps car ca me sert directement.

**Comment by tcharp38** [comment]
Donc ce fantome est toujours la ?
Il revient quand tu le detruits mais revient il toujours avec la meme adresse IEEE ?

**Comment by Jake309** [comment]
Oui, j'ai plus de orvibo, mais j'ai toujours ce fantome, c'est moins impactant maintenant, 2 ou 3 équipements.
La j'en ai un c'est : Adresse (courte/IEEE) : C5CC / FFFFFFFFFFFFFFFF
J'ai déjà eu des cas ou un module qui passez en time out (nécessitait une inclusion) se réintègre mais sous un nouveau IEEE.

**Comment by tcharp38** [comment]
Une adresse comme ca avec que des F c'est du n'importe quoi.
Donc surement le FW de la zigate qui genere cette cochonerie. C'est sur la zigate v2 n'est ce pas ?

**Comment by Jake309** [comment]
Biensur que c'est la V2 :)   Sur le papier elle était bien, je l'ai acheté.
Je vais tout repasser sur la V1 et me débarraser de cette arnaque.
Tu vas bientot la voir sur leboncoin ^^

**Comment by tcharp38** [comment]
La v2 etait prometteuse oui mais dommage que le support soit à l'arret.

**Comment by tcharp38** [comment]
@Jake309 
A ma grande surprise un nouveau FW v2 vient juste de sortir:  https://github.com/fairecasoimeme/ZiGatev2/releases/tag/v3.a0

**Comment by Jake309** [comment]
Salut @tcharp38 
Oula !! Alors que j'avais prévu de basculer sur la V1 ce weekend. 
Je vais la tester avant. 
Vraiment radicale ce nouveau firmware. Je vais regarder sil le wiki en parle pour savoir si je peux le faire sans tout réintégrer. 
Merci d'avoir pensé à moi :)

**Comment by tcharp38** [comment]
J'attends de tes news du coup.

**Comment by Jake309** [comment]
Salut Tcharp,

J'ai fais la mise a jour sans ecraser et tout réintégrer.
J'ai récupéré une belle fluidité. Je laisse encore un peu.

J'ai ce message : 
`Abeille | ERREUR: msgToLQICollector(): Impossible d'envoyer le msg vers AbeilleLQI (err 11)`

Ca te parle ?

[AbeilleLogs-230225.tar.gz](https://github.com/KiwiHC16/Abeille/files/10831775/AbeilleLogs-230225.tar.gz)

**Comment by tcharp38** [comment]
Salut.
On dirait que tu n'es plus en mode debug. Je me trompe ?

Pour les erreurs, du coup je ne vois pas trop ce qui se passe.
Le code 11 semble dire "ressource temporairement indispo" mais.. pas assez d'infos :(

**Comment by Jake309** [comment]
Oui, j'étais en defaut :(
J'ai relancé mon jeedom complet après avoir remis les log en débug. Si j'ai encore le message, je te les redonne :)

**Comment by Jake309** [comment]
Le revoila.
10 occurence, la dernière à 16:53:35 

[AbeilleLogs-230226.tar.gz](https://github.com/KiwiHC16/Abeille/files/10834073/AbeilleLogs-230226.tar.gz)

Autre question, l'état des équipements, c'est eux qui l'envoie ? 
J'ai 2 volet qui ne m'envoient pas leur status, je dois faire un get pour qu'ils se mettents à jour. Volet cuisine par exemple : 2BC4 / 0004740000B9B81D

Merci

**Comment by tcharp38** [comment]
Je seche toujours.
Ces erreurs arrivent seules ou c'est toi qui déclenche un raffraichissement reseau ?

Pour les volets, ce sont eux qui font un "reporting". Ils envoient leur status quand il change.
Ce pb est recent ?

**Comment by Jake309** [comment]
Salut
Désolé, un peu de retard.
J'ai des log, avec pas mal d'occurence.
Je te confirme que ca arrive seul, car j'en ai la nuit ou la journée quand on est pas la.

[AbeilleLogs-230228.tar.gz](https://github.com/KiwiHC16/Abeille/files/10852809/AbeilleLogs-230228.tar.gz)

Tu vas encore orienté ton debug, mais j'ai ca depuis la MAJ de la zigate V2 ^^

**Comment by tcharp38** [comment]
J'observe que le device (est ce vraiment lui ?) renvoi des infos LQI alors qu'on ne lui demande pas.
Il faudrait pouvoir sniffer le reseau pour etre sur que ca vient de lui mais vu que tu as ce pb depuis une mise à jour du FW... il doit y avoir un lien.

En + je vois aussi d'autres infos qui remontent mais sans requete préalable.
Comme une "Routing table response"... tres etrange.

Je vais ouvrir un sujet chez Zigate. La je penche pour un effet de bord du FW 0005-03A0.
Et pour la prochaine beta je masque cette erreur.

Exemple (les message 'Management LQI response' & 'Routing table response' sont inattendus)

    [2023-02-26 16:43:35] Abeille1, Type=8000/Status, Status=00/Success, SQN=11, PacketType=0100, Sent=01, SQNAPS=9F, NPDU=02, APDU=01
    [2023-02-26 16:43:35] Abeille1, Type=8702/APS data confirm fail, Status=D4/ZPS_NWK_ENUM_FRAME_IS_BUFFERED, SrcEP=01, DstEP=01, AddrMode=02, Addr=5C64, SQNAPS=9F, NPDU=02, APDU=00
    [2023-02-26 16:43:38] Abeille1, Type=8012/APS data confirm, Status=00, Addr=16FB, SQNAPS=A0, NPDU=02, APDU=00
    [2023-02-26 16:43:38] Abeille1, Type=8012/APS data confirm, Status=00, Addr=16FB, SQNAPS=A1, NPDU=02, APDU=00
    [2023-02-26 16:43:38] Abeille1, Type=8011/APS data ACK, Status=00/Success, Addr=16FB, EP=00, ClustId=0031, SQNAPS=A0
    [2023-02-26 16:43:38] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=8031, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=16FB, DstAddrMode=02, DstAddr=0000
    [2023-02-26 16:43:38]   Management LQI response, SQN=F7, Status=00, NTableEntries=0F, startIdx=00, nTableListCount=02
    [2023-02-26 16:43:38]   NExtPANId=01FAB4DAC0E09278, NExtAddr=00158D0003A3594D, NAddr=4983, NBitMap=0205 => ?/Parent/RxONWhenIdle/Router, NDepth=01, NLQI=5F
    [2023-02-26 16:43:38]   NExtPANId=01FAB4DAC0E09278, NExtAddr=00158D0001875DC4, NAddr=6A3A, NBitMap=0212 => ?/Child/RxOFFWhenIdle/EndDevice, NDepth=03, NLQI=69
    [2023-02-26 16:43:38] ERROR: msgToLQICollector(): Impossible d'envoyer le msg vers AbeilleLQI (err 11)
    [2023-02-26 16:43:38] Abeille1, Type=804E/Management LQI response (unused).
    [2023-02-26 16:43:38] Abeille1, Type=8011/APS data ACK, Status=00/Success, Addr=16FB, EP=00, ClustId=0032, SQNAPS=A1
    [2023-02-26 16:43:38] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=8032, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=16FB, DstAddrMode=02, DstAddr=0000
    [2023-02-26 16:43:38]   Routing table response, SQN=F8, Status=00, TableEntries=42, StartIdx=0, TableListCount=7
    [2023-02-26 16:43:38]   DestAddr=2EF7, Status=0/Active, NextHop=2EF7
    [2023-02-26 16:43:38]   DestAddr=5C64, Status=1/Discovery_Underway, NextHop=FFFE
    [2023-02-26 16:43:38]   DestAddr=0227, Status=1/Discovery_Underway, NextHop=FFFE
    [2023-02-26 16:43:38]   DestAddr=7375, Status=1/Discovery_Underway, NextHop=FFFE
    [2023-02-26 16:43:38]   DestAddr=0E41, Status=1/Discovery_Underway, NextHop=FFFE
    [2023-02-26 16:43:38]   DestAddr=0000, Status=0/Active + Many To One, NextHop=8120
    [2023-02-26 16:43:38]   DestAddr=28E3, Status=4/Validation_Underway, NextHop=28E3

**Comment by Jake309** [comment]
2023-03-01 09:12:14 | Abeille | ERREUR: msgToRoutingCollector(): Impossible d'envoyer le msg vers AbeilleRoutes (err 11) |  13

[AbeilleLogs-230301.tar.gz](https://github.com/KiwiHC16/Abeille/files/10860884/AbeilleLogs-230301.tar.gz)

J'ai celui la en plus maintenant... sérieux, ca va me rendre fou.

est ce que c'est bien l'équipement avec l'adresse 16FB qui génère ca ?
Si oui, je l'ai identifié, c'est un équipement historique qui ne ma jamais posé de pb, mais je vais tenter une réintégration pour vois.

J'attends de recevoir la gateway Legrand pour basculer dessus tout mon legrand (le prix de la tranquillité $$$)
et je fais un full flash de la v2 et réintègre tout pour tester.

PS: je viens de lire ton issue juste au dessus et tu as l'air de dire que c'est jamais le même, donc bon, je tenterai de le réintégrer, mais on va pas y mettre d'espoir

Ca ne me dérange pas qu'elle soit présente, au moins qu'on puisse identifier l'origine avant.
Parce que bon, masquer c'est bien à l'usage, mais a mon avis, ce genre d'info erroné ca charge le réseau ou la zigate et crée une potentiel latence.

Pour sniffer, faut un truc en particulier ?

**Comment by tcharp38** [comment]
Ok c'est confirmé par Zigate.
C'est une nouveauté de ce FW. Il fait des interrogations de lui meme regulierement mais Abeille ne s'attend pas à recevoir ces messages sans les avoir demandé. 

Du coup j'ai masqué les 2 erreurs qui peuvent donc etre normales.
Nouvelle beta en cours pour demain.

**Comment by tcharp38** [comment]
@Jake309
Ca dit quoi avec les dernieres beta et ce FW ?

**Comment by Jake309** [comment]
Pour le REX.
J'ai retiré mes volets legrands hier en cours de basculement, j'ai récupéré un peu de temps de réponse sur le reste.
Vas savoir pourquoi ...
Sinon, j'ai viré ma zigate V2, je repasse tout sur la v1, j'ouvre une issue pour des pb avec les capteur xiaomi
