### ISSUE TITLE
TRÅDFRI Télécommande 5 boutons - Pourquoi ce comportement sur évènement/info [LeftRight] déclenché par appui bouton direction < ou > ? 

### ISSUE THREAD

**Issue by sebgeekinside** [KiwiHC16/Abeille#2547]
Cela fait plusieurs mises à jour de version STABLE du plugin que je constate un comportement différent d'auparavant lors de l'appui sur le bouton direction < ou > qui correspond à l'évènement/info [LeftRight].

Je crée enfin une issue pour demander si le comportement constaté est correct ou bien s'il y a un dysfonctionnement.

Suite à appui par exemple sur le bouton de direction < i.e. bouton Left pour lequel la commande info [LeftRight] va déclencher la prise de valeur 1, tout nouvel autre appui sur ce même bouton n’enclenche plus aucun évènement. La commande info [LeftRight] ne réagit plus à tout nouvel appui sur ce même bouton.
Pour qu’un nouvel appui sur ce bouton donne lieu à un évènement via la commande info [LeftRight], il faut auparavant appuyer sur le bouton de direction opposé, à savoir ici le bouton de direction > i.e. bouton Right qui va induire un évènement de la commande info [LeftRight] qui va prendre la valeur 0.

C’est comme s’il fallait obligatoirement qu’il y ait appui en alternance entre bouton de direction < et bouton de direction > pour qu’il y ait un évènement de la commande info [LeftRight] i.e. obligation d'alternance de valeur 0 et 1 de cette commande info.

La combine trouvée pourrait être de positionner cette commande info [LeftRight] à "toujours répéter" sur Oui dans sa configuration. Cela permettrait de ne plus avoir une prise en compte seulement s'il y a alternance entre valeur 0 et 1. Cependant, sans comprendre pourquoi, "toujours répéter" repasse automatiquement à Non après je ne sais quel événement.

Les autres boutons n'ont pas ce même comportement.

C'est un comportement que j'ai constaté depuis mise à jour vers la version STABLE du plugin (2022-04-07 01:00:21). Ça date... Avec version STABLE antérieure, je ne constatais pour ce comportement.

A travers log AbeilleParde.log, je constate que tout appui sur un bouton de direction semble correctement réceptionné au niveau de la ZiGate, qu’il y ait eu ou non alternance d’appui entre les 2 boutons de direction.

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Je ne connais pas cette telecommande et il se peut qu'au fil des changements j'ai cassé un truc.

J'ai besoin de ton aide pour creuser ça
- un visu pour voir à quoi elle ressemble
- via sa page, onglet avancé, me dire quel est le modele correspondant

et
- mode debug page config Abeille, 5000 lignes de logs au min
- faire une action sur le bouton choisi, noter lheure
- et me filer le package de logs (page maintenance/telecharger tout)

Merci

**Comment by sebgeekinside** [comment]
Voici : 
- Son visuel : 
![TRÅDFRI Télécommande 5 boutons](https://user-images.githubusercontent.com/87441712/221350949-337f1e1e-48ca-4e69-8fe2-cf5563d362e9.png)
Ce visuel permet de voir que cette télécommande possède : 
    - Un bouton de direction ayant le symbole < (i.e. bouton Left pour lequel la commande info [LeftRight] va déclencher la prise de valeur 1),
    - Un bouton de direction ayant le symbole > (i.e. bouton Right pour lequel la commande info [LeftRight] va déclencher la prise de valeur 0),
- Mon package de logs du plugin Abeille suite au contexte ci-dessous : [AbeilleLogs-230225.tar.gz](https://github.com/KiwiHC16/Abeille/files/10830779/AbeilleLogs-230225.tar.gz)

Contexte :

1. Il y a quelque jours, j'avais à nouveau configuré la commande info [LeftRight] à Oui pour "Répéter les valeurs identiques".
Cette configuration a permis de ne plus avoir une prise en compte seulement s'il y a alternance entre valeur 0 et 1 de cette commande info [LeftRight]. 
Cette configuration est restée ainsi plusieurs jours. 
Les différents appuis successifs réalisés alors sur l'un des boutons de direction aboutissent au bon déclenchement souhaité et défini via un scénario : tout appui successif sur le même bouton de direction déclenche bien le scénario (i.e. la commande info [LeftRight] va bien prendre la même valeur à chacun des appuis successifs sur le même bouton de direction).

2. Mais aujourd'hui, sans cerner de la cause, je constate que le configuration "Répéter les valeurs identiques" est repassée automatiquement à Non après je ne sais quel événement.
Aujourd'hui, avec la commande info [LeftRight] positionnée à Non pour "Répéter les valeurs identiques", j'ai appuyé plusieurs fois sur le bouton de direction ayant le symbole < (i.e. bouton Left pour lequel la commande info [LeftRight] devrait déclencher la prise de valeur 1).
Les différents appuis successifs réalisés sur le bouton de direction n'aboutissent pas au déclenchement souhaité et défini via le scénario.
J'ai réalisé un dernier appui vers [2023-02-25 10:52...].

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Désolé pour la latence. Je voulais pousser une nouvelle beta avant de creuser d'autres soucis.

Donc l'info 'LeftRight' contient soit 1 ou 0 suivant si bouton gauche/droit. C'est ca ?

Ton souci de suppression du "Repeter les valeurs identiques" doit etre fixé dans la beta il me semble.

Ceci dit ca ne fait pas partie du modele non plus donc il semble incomplet.
En outre j'ai l'impression qu'il y a bien + que ce que la telecommande supporte.
Tu peux me faire un snapshot du widget correspondant sur le dashboard ?

**Comment by sebgeekinside** [comment]
> Donc l'info 'LeftRight' contient soit 1 ou 0 suivant si bouton gauche/droit. C'est ca ?

Lors d'un appui sur : 
- Le bouton gauche : la commande info [LeftRight] prend systématiquement la valeur 1,
- Le bouton droit : la commande info [LeftRight] prend systématiquement la valeur 0.

> Tu peux me faire un snapshot du widget correspondant sur le dashboard ?

Voici :
![image](https://user-images.githubusercontent.com/87441712/222533799-f8b4c5ef-375d-488b-b023-3bd178ccbe09.png)

> En outre j'ai l'impression qu'il y a bien + que ce que la télécommande supporte.

De souvenir, suite à mise à jour du plugin vers la version STABLE du 2022-04-07 01:00:21, j'ai dû reprendre des scénarii Jeedom car j'avais alors constaté que des commandes info auparavant utilisées n'étaient plus celles qui retournaient à présent la valeur lors d'appuis sur des boutons de la télécommande.
Auparavant, il me semble que c'était l'une des commandes info [Left-Right-Cmd] ou [Left-Right-Direction] que j'utilisais. 
Suite à ma mise à jour du plugin indiquée ci-dessus, j'ai dû utiliser à la place la commande info [LeftRight].
A présent, je en sais pas à quoi servent les commandes info [Left-Right-Cmd] ou [Left-Right-Direction].

**Comment by tcharp38** [comment]
Si tu utilisais 'Left-Right-Cmd' ou '..Direction' avant je ne comprends pas non plus a quoi servait "LeftRight".

Peux tu presser LEFT, noter l'heure
presser RIGHT noter l heure
Presser UP & noter l'heure
et presser DOWN & noter l'heure ?
Puis me filer le package de logs.

Il y a surement des trucs à remettre au propre la.

D'ailleurs ca ne serait pas mieux d'avoir un truc du style suivant ?
- Left clic
- right clic
- up clic
- down clic

**Comment by sebgeekinside** [comment]
Voici le package de logs qui trace les actions suivantes : 
- A [2023-03-04 12:10:51] : appui sur le bouton Left,
- A [2023-03-04 12:11:28] : appui sur le bouton Right,
- A [2023-03-04 12:11:55] : appui court sur le bouton Up,
- A [2023-03-04 12:12:17] : appui court sur le bouton Down,
- A [2023-03-04 12:12:45] : appui sur le bouton Middle,
- A [2023-03-04 12:39:24] : appui long sur le bouton Up, plus précisément, lors de cette action je constate dans Abeille.log qu'il y a une valeur émise lors de l'appui sur le bouton à [2023-03-04 12:39:24] et une valeur émise lors du replacement du bouton à [2023-03-04 12:39:26], 
- A [2023-03-04 12:40:15] : appui long sur le bouton Down, plus précisément, lors de cette action je constate dans Abeille.log qu'il y a une valeur émise lors de l'appui sur le bouton à [2023-03-04 12:40:15] et une valeur émise lors du replacement du bouton à [2023-03-04 12:40:17].

[AbeilleLogs-230304.tar.gz](https://github.com/KiwiHC16/Abeille/files/10888201/AbeilleLogs-230304.tar.gz)

Personnellement, il m'importe peu que l'information du bouton sur lequel j'ai appuyé (par rapport au couple de boutons opposés Left/Right, Up/Down) soit portée par 1 ou 2 commandes info distinctes. 
Du moment qu'on arrive bien via 1 ou 2 commandes info à faire la distinction du bouton sur lequel on a appuyé...
En ayant la possibilité de distinguer entre appui court ou appui long pour le couple de boutons (Up/Down)(cf. détails ci-dessous).

Dans un usage classic de cette télécommande destiné à la gestion de luminaires, le couple de boutons (Up/Down) correspond respectivement à augmentation de luminosité/diminution de luminosité.
Ce couple de boutons gère ainsi appui court ou appui long (cf. traces logs associées).
Pour les autres boutons de cette télécommande, je n'ai pas constaté de comportement différent en effectuant appui court, appui long.
Je ne constate pas non plus de comportement différents de tous les boutons de cette télécommande quand j'effectue un double appui sur un bouton.

**Comment by tcharp38** [comment]
Salut
Je vois que tu étais sur une stable, donc une antiquité de version par rapport à ce que je viens de pousser.
Plutot que d'analyser de vieux logs, je te laisse faire la mise à jour et un retour.
Merci

**Comment by sebgeekinside** [comment]
Tester le comportement d'une version non stable implique pour moi de mettre en place un environnement Jeedom dédié, ce que je n'ai pas entrepris jusqu'à présent, faute de temps et d'équipements en double.
Je ne suis pas fervent d'installer une version non stable du plugin sur mon environnement actuel et de rebasculer sur version stable via restauration complète d'une sauvegarde Jeedom.
Wait...

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
As tu basculé sur la nouvelle stable ?
Des soucis ?

**Comment by sebgeekinside** [comment]
Je n'ai pas encore basculé sur la version 230326-STABLE-1.

J'ai vu dans le changelog qu'il fallait en terme de prérequis :
- Zigate v2 avec version firmware 3.A0,
- Zigate v1 avec version firmware 3.1e à minima et version 3.23 recommandée.

Sous la page de configuration du plugin Abeille, mes 2 Zigates (1 Zigate v2 + 1 Zigate v1) sont indiquées avec firmware de version 0005-0321. 
J'en déduis que cela correspond à la version 3.21.

Pour bénéficier des évolutions de la version 230326-STABLE-1 du plugin Abeille, je suis donc amené à mettre à jour le firmware de mes 2 Zigates.
C'est toujours une étape qui ne me rassure pas, mes expériences précédentes ayant impliqué du temps pour analyser et comprendre pourquoi tout n'était pas opérationnel après update de version de firmware Zigates combiné à update de version du plugin Abeille.

**Comment by tcharp38** [comment]
Je vois.
Tu peux basculer sur la dernière version d Abeille sans changer les fw de tes zigate.
Je vais revoir mon message.

**Comment by sebgeekinside** [comment]
> Salut @sebgeekinside As tu basculé sur la nouvelle stable ? Des soucis ?

Je viens enfin de basculer sur la version 230326-STABLE-1.
Je ne constate pas d'amélioration, il y a même des régressions :
- L'appui sur le bouton Middle n'est plus opérationnel,
- L'appui court sur le bouton Left n'est plus opérationnel,
- L'appui court sur le bouton Right n'est plus opérationnel.

Il y a toujours les différentes commandes : LeftRight-Cmd, Left-Right-Direction. 
Aucune ne semble changer de valeur lors d'appuis sur bouton Left ou Right.

Voici le package de logs qui trace les actions suivantes :
- A [2023-05-12 14:23:47] : appui sur le bouton Left,
- A [2023-05-12 14:24:35] : appui sur le bouton Right,
- A [2023-05-12 14:25:05] : appui sur le bouton Middle.

[AbeilleLogs-230512.tar.gz](https://github.com/KiwiHC16/Abeille/files/11463870/AbeilleLogs-230512.tar.gz)

Cela semble rejoindre l'issue : https://github.com/KiwiHC16/Abeille/issues/2576#issue-1678636447.

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Beaucoup trop de modifs en cours de mon cote.
J'ai poussé hier une nouvelle stable.
On peut refaire le point à partir de celle la ?

**Comment by sebgeekinside** [comment]
Salut @tcharp38,

voici ce que je constate suite à installation de la version STABLE du 2023-05-29 :

- L'appui sur le bouton Middle est opérationnel,
- L'appui court sur le bouton Left n'est toujours pas opérationnel,
- L'appui court sur le bouton Right n'est toujours pas opérationnel.

Il y a toujours les différentes commandes : LeftRight, LeftRight-Cmd, Left-Right-Direction.
Aucune ne semble changer de valeur lors d'appuis sur bouton Left ou Right.

Voici le package de logs qui trace les actions suivantes :

- A [2023-06-03 10:22:32] : appui sur le bouton Left,
- A [2023-06-03 10:23:49] : appui sur le bouton Right.

[AbeilleLogs-230603.tar.gz](https://github.com/KiwiHC16/Abeille/files/11642112/AbeilleLogs-230603.tar.gz)

**Comment by sebgeekinside** [comment]
Salut @tcharp38, suite à installation de la version STABLE du 2023-05-29, les appuis courts sur chacun des boutons sont opérationnels !

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Ca c'est une bonne nouvelle.
Donc plus aucun souci sur ce modele d'apres toi ?

**Comment by sebgeekinside** [comment]
Je n'ai pas l'opportunité de manipuler les appuis longs de cette télécommande, je ne peux donc pas dire si cette dernière version du modèle du plugin fonctionne pour cela mais pour le reste, à travers mon usage et mes quelques tests des appuis courts sur différents boutons, RAS comme dysfonctionnement ! :-)
