### ISSUE TITLE
Xiaomi Aqara 'weather': une pile survoltée à 30V

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#2548]
Qq chose a du se passer dans une release récente: 30v pour une pile 2032 ça me parait un peu beaucoup ;)

rien de bien urgent cependant.

Xiaomi temp/humidity/pressure sensor: weather.json

![image](https://user-images.githubusercontent.com/3601462/221214873-0522c941-c801-46f7-9da2-c528367e4191.png)
![image](https://user-images.githubusercontent.com/3601462/221215353-5bf5ccbc-264e-4ba3-9d45-36cf9f53c750.png)

**Comment by edgd1er** [comment]
c'est peut etre une surcharge de ma part avec ça:
je voulais retrouver des pressions en mm/hg et pas en hpa.

```
"fromDevice": {
                "0000-FF01": {
                    "01-21": {
                        "func": "numberDiv",
                        "div": 100,
                        "info": "0001-01-0020"
```

**Comment by tcharp38** [comment]
Salut @edgd1er 
L'info 0001-01-0020 est pour la tension batterie.
Sauf erreur, Xiaomi renvoi la tension * 1000, donc il faut un div by 1000 et non pas by 100.
C'est toi qui a modifié ca ? Pour ?
Aucun rapport avec la pression en tout cas

**Comment by edgd1er** [comment]
Salut @tcharp38 
oui, tres certainement, je me suis trompé. je ne maitrise pas les codes zigbee (0001-01-0020), les codes abeilles et autres nécéssités du code ( 0000-FF01, 01-21, 64-29, 66-2B, ...).
le but premier était d'avoir la pression en mbar.
L'issue peut etre fermé, je vais continuer d'experimenter de mon coté.
Désolé pour l'issue non liée au code d'abeille.

**Comment by tcharp38** [comment]
Le sujet n'est pas assez detaillé. Tu fais allusion à quel modele ?

**Comment by edgd1er** [comment]
plugins/Abeille/core/config/devices/weather/weather.json

**Comment by edgd1er** [comment]
Dans les logs, je vois un div 100 au lieu d'un div 1000, je ne vois pas d'ou vient ce chiffre. j'ai vidé le cache jeedom et redémarrer l'apache.
`,"xiaomi":{"fromDevice":{"0000-FF01":{"01-21":{"func":"numberDiv","div":100,`

le modèle indique bien sur le rpi:
```
"xiaomi": {
            "fromDevice": {
                "0000-FF01": {
                    "01-21": {
                        "func": "numberDiv",
                        "div": 1000,
                        "info": "0001-01-0020"
                    },
```

Pourtant le log indique:
`
[2023-02-28 08:13:15]   Updated eq={"ieee":"00158D0002272FED","macCapa":"80","rxOnWhenIdle":0,"manufCode":null,"rejoin":"","status":"idle","time":1677568312,"endPoints":{"01":{"manufId":"LUMI","modelId":"weather","location":""}},"mainEp":"01","manufId":"LUMI","modelId":"weather","location":"","jsonId":"weather","jsonLocation":"Abeille","tuyaEF00":null,"customization":null,"xiaomi":{"fromDevice":{"0000-FF01":{"01-21":{"func":"numberDiv","div":100,"info":"0001-01-0020"},"64-29":{"func":"numberDiv","div":100,"info":"0402-01-0000"},"66-2B":{"func":"number","info":"0403-01-0000"},"65-21":{"func":"numberDiv","div":100,"info":"0405-01-0000"}}}},"sqnList":{"34":1677567109,"35":1677567109,"00":1677568318,"01":1677567109,"02":1677567109,"03":1677567120,"04":1677567120,"05":1677567120,"06":1677568329,"07":1677568329,"08":1677568329,"09":1677568359,"0A":1677568359,"0B":1677568359,"0C":1677568369,"0D":1677568369,"0E":1677568389,"0F":1677568389,"10":1677568389,"11":1677568395,"12":1677568395},"zigbeeId":"weather"}
`

**Comment by tcharp38** [comment]
Le modele est lu
- a l inclusion
- si tu fais "mise à jour" ou "reinitialiser" via la page avancée

Donc tant que tu ne fais pas l'un ou l'autre les anciennes infos perdurent. Ca ne serait pas le souci ?

**Comment by edgd1er** [comment]
Effectivement avec le clic sur `mise a jour`, cela fonctionne (presque, 3/4 devices ok).
Je m'interroge sur le faite que le réglage qui n'est ni dans le modèle, ni dans le bdd, ni dans la cache widget de jeedom.

il y aurait un autre cache qui résiste aux réglages bdd/fichiers et aux restarts ?

je m'attendais a retouver les réglages dans la BDD, ce n'est pas le cas:
`select c.id,c.eqType , c.configuration , c.template,c.* from cmd c where c.eqType='Abeille' and c.logicalId in ('0001-01-0020','0001-01-0021');`

il semblerait qu'a chaque fois le fichier modele json soit lu, a moins que le modèle ne soit stocké dans une variable globale ($GLOBALS['eqList']). Avec un restart du daemon, la variable globale n'est elle pas remise a zéro ?

```
/* Check if device is already known to parser.
        If not, add entry with given net/addr/ieee.
        Returns: device entry by reference */
    function &getDevice($net, $addr, $ieee = null, &$new = false) {
        if (!isset($GLOBALS['eqList'][$net]))
.....
```

**Comment by tcharp38** [comment]
Alors pas sur de tout comprendre mais

- le modele est lu lors de l'inclusion ou mise-à-jour ou reinit
- la BDD eqLogic est mise à jour en fonction du modele
- les démons AbeilleCmd & AbeilelParser relisent la BDD au démarrage ou update du device cote Jeedom. Le stockage est ce fameux "eqList".


Ca aide ?

Au final il y a un pb ?
J'ai cru comprendre que le souci venait d'essais sur le modele. Je me gourre ?

**Comment by edgd1er** [comment]
ça confirme ce que j'ai lu du code pour la logique.

Effectivement, j'avais modifié le modèle puis corrigé sans faire la reinit. Cependant en ayant corrigé la conf des commandes directement dans la bdd, je m'attendais a avoir le voltage correct. il y a peut un cache BDD gérer par PHP qui m'a joué un tour.
J'aurais sans doute du faire un restart du conteneur.

Je ferme l'issue, les valeurs sont correctes et j'ai corrigé les valeurs stockées en bdd. Merci.
