### ISSUE TITLE
Inclusion volet Profalux impossible

### ISSUE THREAD

**Issue by cissemp** [KiwiHC16/Abeille#2549]
Bonjour à tous

J’ai mon jeedom Smart sur lequel j’ai plusieurs volets profalux connectés en zigbee avec le plugin Abeille.
Jusqu’à présent tout fonctionnait bien mais depuis une semaine, j’ai un volet qui s’est déconnecté et n’est plus pilotable depuis Jeedom. J’ai donc décidé de le retirer et de faire à nouveau l’inclusion comme indiqué sur le lien [Profalux — Documentation Abeille 11.02.2021](https://kiwihc16.github.io/AbeilleDoc/devices/Profalux.html).
J’ai toujours procédé ainsi mais cette fois ça ne marche pas malgré plusieurs tentatives. J’ai pensé à un problème de signal radio mais il y a un autre volet qui est juste à côté (5m à peine) j’ai même déplace mon jeedom pour brancher juste à côté du volet mais rien à faire.
Au final j’ai malheureusement bloqué mon volet qui n’est même plus pilotable avec la télécommande mais c’est un autre souci qui n’est pas l’objet du ticket mais je suis preneur aussi d’aide là dessus.
Merci
[AbeilleLogs-230226.tar.gz](https://github.com/KiwiHC16/Abeille/files/10833837/AbeilleLogs-230226.tar.gz)

**Comment by cissemp** [comment]
Merci @KiwiHC16  pour ton aide rapide

**Comment by tcharp38** [comment]
Salut @cissemp 
Je ne vois pas le log AbeilleParser.
D'autre part tu n'es pas en mode debug donc pas de traces utiles.

Si tu n'as plus le controle avec la telecommande, tu dois deja reappairer les 2 via le reset electrique.
Ne te focalise que sur 1 seul volet, le + proche de la zigate.

J'attends de tes news.

**Comment by cissemp** [comment]
Bonjour

Je me suis rendu compte que j'utilisais le plugin en beta, je suis revenu
sur une version stable et ça fonctionne.
L'incident est donc clos
Merci d'avance

**Comment by tcharp38** [comment]
Content pour toi mais pas bon pour moi.
Pas normal.
Je vais faire des essais avec mes volets pour comprendre.

Je clos le sujet. A réouvrir si besoin
