### ISSUE TITLE
Xiaomi: diverses clarifications

### ISSUE THREAD

**Issue by rkhadro** [KiwiHC16/Abeille#255]
Bonjour,

Je viens de recevoir mes xiaomi: switch.aq2,weather, sensor_magnet.aq2

Ils sont correctement reconnu avec quelques problème d'affichage(IEE-Addr n'apparait pas, état d'un switch qui reste bloqué).
Lorsque je fais un ActiveEndpoint ou SimpleDescriptorRequest avec 01 ou getName avec Endpoint 01, je n'obtiens pas de réponse.

![screenshot 2018-05-22 19 33 19](https://user-images.githubusercontent.com/38282423/40379707-25900f60-5df7-11e8-859e-3f8039c1d9ca.png)

![screenshot 2018-05-22 19 33 05](https://user-images.githubusercontent.com/38282423/40379747-4226c97a-5df7-11e8-9f8b-47f86ba7fa91.png)

```
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/ActiveEndPoint} => address=d64a
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]Type: CmdAbeille Address: Ruche avec Action: ActiveEndPoint
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]2 arguments command
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]Dest:/dev/ttyUSB0 cmd:0045 len:0002 datas:d64a
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]len data: 4
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]checksum computed: 219
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]len data: 4
AbeilleMQTTCmd 2018-05-22 19:20:39[DEBUG]checksum computed: 219

AbeilleParser 2018-05-22 19:20:39[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: c6
AbeilleParser 2018-05-22 19:20:39[DEBUG]SQN: 0 for messages which are not transmitted over the air.

----

AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/SimpleDescriptorRequest} => address=d64a&endPoint=01
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]Type: CmdAbeille Address: Ruche avec Action: SimpleDescriptorRequest
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]4 arguments command
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]begin processCmd function
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]Dest:/dev/ttyUSB0 cmd:0043 len:0003 datas:d64a01
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]len data: 6
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]checksum computed: 221
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]len data: 6
AbeilleMQTTCmd 2018-05-22 19:41:29[DEBUG]checksum computed: 221

AbeilleParser 2018-05-22 19:41:30[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: cc
AbeilleParser 2018-05-22 19:41:30[DEBUG]SQN: 0 for messages which are not transmitted over the air.
```

**Comment by rkhadro** [comment]
Quand je fais un liste équipements certains  Xiaomi ne répondent pas 
Ici il manque le switch 65c8 et le weather f252 que je viens d'associer (pas de link Quality, pas de Last Stamp)

![screenshot 2018-05-22 20 00 52](https://user-images.githubusercontent.com/38282423/40381052-027b925c-5dfb-11e8-9694-ca6a93e93ab1.png)


```
AbeilleParser 2018-05-22 19:56:08[DEBUG]Nombre d'abeilles: 11
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 0; ID : 00; Short Addr : d64a; IEEE Addr: 00158d0002135f96; Power Source (0:battery - 1:AC): 00; Link Quality: 153
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 1; ID : 01; Short Addr : d05f; IEEE Addr: 00158d00022c8c62; Power Source (0:battery - 1:AC): 00; Link Quality: 140
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 2; ID : 02; Short Addr : 5d0D; IEEE Addr: 00158d00020489a6; Power Source (0:battery - 1:AC): 00; Link Quality: 153
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 3; ID : 32; Short Addr : f59b; IEEE Addr: 000B57fffef4f374; Power Source (0:battery - 1:AC): 01; Link Quality: 113
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 4; ID : 33; Short Addr : 8d7e; IEEE Addr: 00047400000979d5; Power Source (0:battery - 1:AC): 01; Link Quality: 156
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 5; ID : 34; Short Addr : a627; IEEE Addr: 000B57fffecb69cb; Power Source (0:battery - 1:AC): 01; Link Quality: 137
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 6; ID : 35; Short Addr : b3e4; IEEE Addr: 84182600000Cb01b; Power Source (0:battery - 1:AC): 01; Link Quality: 119
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 7; ID : 36; Short Addr : b1a0; IEEE Addr: 000474000089045a; Power Source (0:battery - 1:AC): 01; Link Quality: 134
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 8; ID : 37; Short Addr : f2d1; IEEE Addr: 000B57fffed4fe5d; Power Source (0:battery - 1:AC): 01; Link Quality: 88
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 9; ID : 38; Short Addr : 68cc; IEEE Addr: 000B57fffed4d560; Power Source (0:battery - 1:AC): 01; Link Quality: 83
AbeilleParser 2018-05-22 19:56:08[DEBUG]Abeille i: 10; ID : 39; Short Addr : 4384; IEEE Addr: 000B57fffeefaf94; Power Source (0:battery - 1:AC): 01; Link Quality: 78

**Comment by KiwiHC16** [comment]
> Lorsque je fais un ActiveEndpoint ou SimpleDescriptorRequest avec 01 ou getName avec Endpoint 01, je n'obtiens pas de réponse.

C'est normal les switch et door sensor dorment par defaut et n'ecoute pas les demandes de la ZiGate. Si tu les reveilles alors peut être vont ils repondre mais je n'ai jamais essayé.

**Comment by KiwiHC16** [comment]
> Ils sont correctement reconnu avec quelques problème d'affichage(IEE-Addr n'apparait pas, état d'un switch qui reste bloqué).

IEEE n'apparait pas. Il faut faire soit un list equipement, mais ce n'est pas garanti, il vaut mieux faire un Network List en mode refresh.

![capture d ecran 2018-05-22 a 23 08 04](https://user-images.githubusercontent.com/8549674/40390300-0d92df64-5e15-11e8-9083-9a166d651775.png)

![capture d ecran 2018-05-22 a 23 08 15](https://user-images.githubusercontent.com/8549674/40390307-120231b2-5e15-11e8-9ba2-82d3b317345a.png)

Pour cela il te faut probablement soit la dernier master ou la version que j'ai mis sur le market il y a un ou deux jours.

**Comment by KiwiHC16** [comment]
> Quand je fais un liste équipements certains Xiaomi ne répondent pas
Ici il manque le switch 65c8 et le weather f252 que je viens d'associer (pas de link Quality, pas de Last Stamp)

Si tu as des routeurs dans ton reseau ZigBee tu n'auras pas toutes les infos en faisant Liste Equipement, il faut faire un Network-List avec un refresh Cache (Voir doc).

Si tu actives (un petit appui court sur le bouton lateral) alors le timestamp doit se mettre a jour.

**Comment by rkhadro** [comment]
Bon, le f252 ne répondait plus, j'ai du le supprimer et le réassocier (224f).

En fait le timestamp apparait, mais de manière fugace lors de l'appui sur le switch.
 
hors connexion avec la ruche,je n'ai aucun xiaomi dans la liste lors du refresh:


NE | NE Name | Voisine | Voisine Name | Voisine IEEE | Relation | Profondeur | LQI
-- | -- | -- | -- | -- | -- | -- | --
0000 | Ruche | d64a | Xiaomi-Inter | 00158d0002135f96 | Child | 01 | 115
0000 | Ruche | d05f | Xiaomi-Temp | 00158d00022c8c62 | Child | 01 | 178
0000 | Ruche | 5d0D | Xiaomi-Porte | 00158d00020489a6 | Child | 01 | 152
0000 | Ruche | 224f | Xiaomi-Inter1 | 00158d000213534a | Child | 01 | 191
0000 | Ruche | a627 | Ikea-Transfo1 | 000B57fffecb69cb | Sibling | 00 | 140
0000 | Ruche | 8d7e | Legrand-Plug | 00047400000979d5 | Sibling | 00 | 161
0000 | Ruche | f59b | Ikea-Amp | 000B57fffef4f374 | Sibling | 00 | 98
0000 | Ruche | b3e4 | Osram-Plug | 84182600000Cb01b | Sibling | 00 | 140
0000 | Ruche | b1a0 | Legrand-Inter | 000474000089045a | Sibling | 00 | 137
a627 | Ikea-Transfo1 | 0000 | Ruche | 00158d0001edf80F | Sibling | 00 | 242
a627 | Ikea-Transfo1 | 8d7e | Legrand-Plug | 00047400000979d5 | Sibling | 0F | 229
a627 | Ikea-Transfo1 | b1a0 | Legrand-Inter | 000474000089045a | Sibling | 0F | 219
a627 | Ikea-Transfo1 | b3e4 | Osram-Plug | 84182600000Cb01b | Sibling | 0F | 196
a627 | Ikea-Transfo1 | f59b | Ikea-Amp | 000B57fffef4f374 | Sibling | 0F | 184
8d7e | Legrand-Plug | 0000 | Ruche | 00158d0001edf80F | Sibling | 00 | 247
8d7e | Legrand-Plug | b1a0 | Legrand-Inter | 000474000089045a | Sibling | 01 | 252
8d7e | Legrand-Plug | f59b | Ikea-Amp | 000B57fffef4f374 | Sibling | 01 | 247
8d7e | Legrand-Plug | b42f | Ikea-Telecom2 | 90fd9ffffe8c6b2f | Child | 03 | 247
8d7e | Legrand-Plug | a627 | Ikea-Transfo1 | 000B57fffecb69cb | Sibling | 01 | 247
8d7e | Legrand-Plug | b3e4 | Osram-Plug | 84182600000Cb01b | Parent | 01 | 247
f59b | Ikea-Amp | 0000 | Ruche | 00158d0001edf80F | Sibling | 00 | 161
f59b | Ikea-Amp | 8d7e | Legrand-Plug | 00047400000979d5 | Sibling | 0F | 192
f59b | Ikea-Amp | a627 | Ikea-Transfo1 | 000B57fffecb69cb | Sibling | 0F | 154
f59b | Ikea-Amp | b1a0 | Legrand-Inter | 000474000089045a | Sibling | 0F | 198
f59b | Ikea-Amp | b3e4 | Osram-Plug | 84182600000Cb01b | Sibling | 0F | 188
b3e4 | Osram-Plug | a627 | Ikea-Transfo1 | 000B57fffecb69cb | Sibling | 01 | 90
b3e4 | Osram-Plug | 27a5 |   | 90fd9ffffe055371 | Parent | 01 | 12
b3e4 | Osram-Plug | 0000 | Ruche | 00158d0001edf80F | Sibling | 01 | 116
b3e4 | Osram-Plug | 8d7e | Legrand-Plug | 00047400000979d5 | Sibling | 01 | 108
b3e4 | Osram-Plug | f59b | Ikea-Amp | 000B57fffef4f374 | Sibling | 01 | 102
b3e4 | Osram-Plug | b1a0 | Legrand-Inter | 000474000089045a | Sibling | 01 | 108
b1a0 | Legrand-Inter | b3e4 | Osram-Plug | 84182600000Cb01b | Sibling | 01 | 247
b1a0 | Legrand-Inter | f59b | Ikea-Amp | 000B57fffef4f374 | Sibling | 01 | 247
b1a0 | Legrand-Inter | 8d7e | Legrand-Plug | 00047400000979d5 | Sibling | 01 | 252
b1a0 | Legrand-Inter | a627 | Ikea-Transfo1 | 000B57fffecb69cb | Sibling | 01 | 247
b1a0 | Legrand-Inter | 32e3 | Ikea-Telecom1 | 90fd9ffffed26f3e | Child | 02 | 247
b1a0 | Legrand-Inter | 27a5 |   | 90fd9ffffe055371 | Child | 02 | 105
b1a0 | Legrand-Inter | 0000 | Ruche | 00158d0001edf80F | Parent | 00 | 252

**Comment by KiwiHC16** [comment]
> "hors connexion avec la ruche, je n'ai aucun xiaomi dans la liste lors du refresh"

Que veux tu dire ? Dans la premiere colonne tu ne trouveras que les routeurs (Ampoule Ikea, Plug,...), dans les equipements xiaomi, il n'y a que la prise xiaomi qui fait routeur et si tu n'en a pas alors il n'y en a pas.

**Comment by KiwiHC16** [comment]
C'est un beau réseau, Ikea, OSRAM, Legrand,...
L'interrupteur Legrand fait routeur, je ne savais pas. C'est interesssant car le bouton mural xiaomi ne le fait pas d'apres ce que je vois.

**Comment by KiwiHC16** [comment]
> "le timestamp apparait, mais de manière fugace lors de l'appui sur le switch"

Peux tu fournir plus de details car je ne comprends pas ton soucis. affichage fugace où ? sur le widget ?

**Comment by rkhadro** [comment]
Idem pour le f252 weather, j'ai du le supprimer et l'associer de nouveau car le last était bloqué sur 20h30 et aucune vie dans le log parser.
Maintenant, j'ai toutes les infos

![screenshot 2018-05-23 00 07 31](https://user-images.githubusercontent.com/38282423/40392835-58008b48-5e1d-11e8-9c80-daec7ba8fb25.png)

**Comment by rkhadro** [comment]
>Que veux tu dire ? Dans la premiere colonne tu ne trouveras que les routeurs (Ampoule Ikea, Plug,...), dans les equipements xiaomi, il n'y a que la prise xiaomi qui fait routeur et si tu n'en a pas alors il n'y en a pas.
Bonjour,

Ok, je n'avais pas compris que seul les routeurs apparaissait

> "Peuxt u fournir plus de details car je ne comprends pas ton soucis. affichage fugace où ? sur le widget ?"



Oui, c'est bien sur le widget. 
Lorsque je clique sur le switch, l'état passe du 'x' au 'coche". 
Pendant ce changement d'état, je vois le timestamp apparaitre et disparaitre rapidement.

J'avais ce comportement aussi sur weather et le sensor_magnet et cela s'est auto résolu au bout d'un moment.

**Comment by KiwiHC16** [comment]
> Pendant ce changement d'état, je vois le timestamp apparaitre et disparaitre rapidement.

Aie. C'est une partie qui est standard à Jeedom. Comme ca je ne sais que dire. Quel browser web utilises tu ? As tu d'autres "commandes" qui font ca ? Est ce que la dalle/le carre de l objet est assez grand ?

Tu as deux fois la même info mais presentée différemment: "Last" et "Last Stamp". As tu le même comportement pour les deux ?

**Comment by rkhadro** [comment]
Oui, J'ai eu ce problème qu'avec les Xiaomi weather et switch.
J'en ai une autre  c'est @ IEE qui ne s'affiche pas.

![screenshot 2018-05-23 19 28 06](https://user-images.githubusercontent.com/38282423/40440895-9473ddda-5ebf-11e8-8428-12337d85a668.png)

Non ce n'est pas la taille du widget 
Le Last est la date sur les weather
Last stamp c'est le timestamp sur les weather.

![screenshot 2018-05-23 19 22 45](https://user-images.githubusercontent.com/38282423/40440642-e8d0a846-5ebe-11e8-93ef-0a5ce0f3610b.png)
 
En gros avec les xiaomi, j'ai du les supprimer plusieurs fois pour que toutes les infos remontent sur le widget.
D'ailleurs, comment faire, sans re associer pour que le device soit créer de nouveau ?
Le getName ne fonctionne pas avec les xiaomi.

**Comment by KiwiHC16** [comment]
Un appui sur le bouton lateral doit les reveiller et ils envoient leur nom, qui provoque la creation de l objet dans Abeille si il n'existe pas ou à été supprimé.

**Comment by KiwiHC16** [comment]
"état d'un switch qui reste bloqué": la V2 des switch n'envoie pas deux messages un sur appui et un sur relache comme le fait la V1, il envoie un seul message avec les deux infos. Donc pour avoir un truc que fonctionne avec le V2, L'etat appuie reste pendant 1s (min) à 2s (max) et reviens à 0 (relâché).

**Comment by KiwiHC16** [comment]
> "En gros avec les xiaomi, j'ai du les supprimer plusieurs fois pour que toutes les infos remontent sur le widget": 

il y a encore un probleme que je n'ai pas réglé qui est que la premiere valeur qui remonte n'est pas visible. Il faut attendre la seconde. C'est dans une des issues. ESsayes plutot de faire remonter les infos (ex. appui bouton lateral, faire changer la temperature, faire LQI refresh, faire Liste Equipement, attendre 50min la remontée automatique d'info).

**Comment by KiwiHC16** [comment]
> J'en ai une autre c'est @ IEE qui ne s'affiche pas

Elle ne remonte pas seul dans la majeur partie des cas. Fait un Liste Equipement ou un refresh cache LQI et tu devrais l avoir. Normalement avec le dernier master le cron15 doit la faire remonter.

**Comment by KiwiHC16** [comment]
Je viens de rendre compte qu'il y a un melange de Last/LastStamp et Time/TimeStamp. Je viens de realigner tous les modeles sur Time/TimeStamp. Il faut le master et sera pris en compte sur la creation de nouveaux equipements. Pas obligatoire.

**Comment by rkhadro** [comment]
> Un appui sur le bouton lateral doit les reveiller et ils envoient leur nom, qui provoque la creation de l objet dans Abeille si il n'existe pas ou à été supprimé.

C'est effectivement le cas, l'objet est bien recréé.
Mais sans les infos SW, IEE, Short et Link Quality.
Un liste équipements me fait bien remonté IEE et Link Quality, mais pas Short Dress
![screenshot 2018-05-24 14 08 37](https://user-images.githubusercontent.com/38282423/40484460-0248448a-5f5c-11e8-9398-919385e34c19.png)
```

AbeilleParser 2018-05-24 14:04:25[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: ef; Src Addr : 5d0D; End Point : 01; Cluster ID : 0000; Attr ID : ff01; Attr Status : 00; Attr Data Type : 42; Attr Size : 001d; Data byte list : 0121170C0328170421a81305213200062407000000000A210000641001
AbeilleParser 2018-05-24 14:04:25[DEBUG]Champ proprietaire Xiaomi, decodons le et envoyons a Abeille les informations (Door Sensor)
AbeilleParser 2018-05-24 14:04:25[DEBUG]Voltage: 3095
AbeilleParser 2018-05-24 14:04:48[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f0; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-05-24 14:04:49[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f1; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01
AbeilleParser 2018-05-24 14:04:49[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f2; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-05-24 14:04:49[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f3; Src Addr : 5d0D; End Point : 01; Cluster ID : 0000; Attr ID : ff01; Attr Status : 00; Attr Data Type : 42; Attr Size : 0009; Data byte list : 0421a8130A21000073
AbeilleParser 2018-05-24 14:04:50[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f4; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01
AbeilleParser 2018-05-24 14:04:51[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f5; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-05-24 14:04:51[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f6; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01
AbeilleParser 2018-05-24 14:04:53[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: f7; Src Addr : 5d0D; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-05-24 14:05:02[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-05-24 14:05:02[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-05-24 14:05:02[DEBUG];type: 8015 (Abeille List)(Processed->MQTT) Payload: 00d64a00158d0002135f96006201d05f00158d00022c8c6200b6025d0D00158d00020489a6008303224f00158d000213534a00b804e2f100158d00022c7138008a05def200158d0002047242009232b1a0000474000089045a018d33f59b000B57fffef4f3740174348d7e00047400000979d501a135b3e484182600000Cb01b016936a627000B57fffecb69cb018f00
```
La deuxième tentative me remonte tout sauf SW.

![screenshot 2018-05-24 14 14 09](https://user-images.githubusercontent.com/38282423/40484832-249d920a-5f5d-11e8-9652-e1460cf9fe59.png)

**Comment by rkhadro** [comment]
> Elle ne remonte pas seul dans la majeur partie des cas. Fait un Liste Equipement ou un refresh cache LQI et tu devrais l avoir. Normalement avec le dernier master le cron15 doit la faire remonter.

Ok, je vais mettre à jour et te tiens au courant.

**Comment by rkhadro** [comment]
> "état d'un switch qui reste bloqué": la V2 des switch n'envoie pas deux messages un sur appui et un sur relache comme le fait la V1, il envoie un seul message avec les deux infos. Donc pour avoir un truc que fonctionne avec le V2, L'etat appuie reste pendant 1s (min) à 2s (max) et reviens à 0 (relâché).

Pour moi le fonctionnement est un appui change l'état, mais il ne revient pas tout de suite à X. faut attendre une durée de l'ordre de la minute (je n'ai pas mesuré).

Tiens la l'etat reste bloqué à UP.
![screenshot 2018-05-24 14 22 31](https://user-images.githubusercontent.com/38282423/40485108-f0b16baa-5f5d-11e8-80bc-57db52679120.png)

Debug lors de l'appui court: 

```


AbeilleParser 2018-05-24 14:23:16[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 37; Src Addr : 224f; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-05-24 14:23:16[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 37; Src Addr : 224f; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01
```

**Comment by KiwiHC16** [comment]
> L'etat appuie reste pendant 1s (min) à 2s (max) et reviens à 0 (relâché)

Pardon il faut lire "L'etat appuie reste pendant _1 min_ (min) à _2 min_ (max) et reviens à 0 (relâché)"

**Comment by rkhadro** [comment]
Je supprime l'objet et le recré. j'ai tout sauf le SW et link quality

J'appuie court:

![screenshot 2018-05-24 14 30 00](https://user-images.githubusercontent.com/38282423/40485682-81cf0e98-5f5f-11e8-92d5-a2eff75a16b2.png)

ca revient à X au bout d'une minute.

**Comment by rkhadro** [comment]
Bon, il faut que j'installe le master et je reviendrais vers toi.

**Comment by KiwiHC16** [comment]
C'est quoi le "X" que tu as en bas du widget ?
Peux tu me faire une capture des commandes pour voir qu'elle est cette commande associée à ce "X" !!!

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-05-24 a 14 38 23](https://user-images.githubusercontent.com/8549674/40485929-23930cb6-5f60-11e8-9cb9-a31905f3da46.png)

Ca devrait être comme ca.

**Comment by KiwiHC16** [comment]
> Il manque des infos.

C'est normal dans la mesure ou pour l'instant je collecte les informations au fils de l'eau. C'est à dire que l'objet est créé mais les champs ne sont pas renseignés car pour 90% d'entre eux ils ne remontent pas.  Puis dans la vie du réseau, les infos remontent et les champs sont renseignés.

Quand j'aurai du temps je regarderai à forcer la mise à jour des infos... actuellement il y a par exemple un cron toutes les 15 minutes qui va chercher des infos.

**Comment by KiwiHC16** [comment]
Pour le PowerSource en gros 'X', regardes https://github.com/KiwiHC16/Abeille/blob/master/Documentation/060_ConfigurationAvancee.asciidoc#power-source

**Comment by rkhadro** [comment]
Pour le Power-Source merci, je l'avais lu cette doc, mais petite memoire.
Félicitation pour tes docs, elles sont de qualité, ainsi que pour ton travail.
 Edit:

Waouh, j'avais pas vu le network mesh dynamique, c'est très bien

![screenshot 2018-05-24 23 33 52](https://user-images.githubusercontent.com/38282423/40514849-fd25cbf4-5faa-11e8-958a-7de9b3b4e710.png)


Merci

**Comment by KiwiHC16** [comment]
Comme cette discussion est tres longue, c'est difficile pour moi de savoir ce qui fonctionne, de ce qui ne fonctionne pas et de trouver les points qui restent ouverts. Je te propose de clore ce sujet et si tu as de questions alors on ouvrira une autre "issue".
