### ISSUE TITLE
Infos de consommation Xiaomi Aqara 2 way control module (id=relay.c2acn01)

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2551]
Maintenant que l'on a à peu près traité le sujet des infos de consommation sur le module Xiaomi en version single way [ici](https://github.com/KiwiHC16/Abeille/issues/2517), j'ouvre une issue pour la version 2 ways.

J'utilise ce module dans une configuration un peu compliquée puisqu'il vient simuler le double interrupteur (bistable) de commandes de ma VMC. 

Pour faire au plus simple: 

- quand le premier module single way allume la VMC, cela injecte du courant en 220v dans le circuit 
- selon les positions (on/off) de chaque canal du deuxième module, cela active/désactive la haute vitesse ou le bypass de la VMC.

Ce montage est OK du point de vue fonctionnel mais je pense que l'intégration du modèle dans Abeille est incomplète pour les infos de consommation.

Les commandes et le widget remontent des infos _Puissante Inst_ et _Conso_
![image](https://user-images.githubusercontent.com/71673288/222984101-5903cb02-5426-4e40-83d8-7a94c84219c1.png)

La valeur de _Puissante Inst_ (en W) ressemble beaucoup à celle de Current (en mA) du module single way.
A la différence de l'autre module, pas d'info de voltage ?
La valeur _Conso_ reste à zéro. Pas d'historique dans Jeedom, pas de remonté dans les logs : 

```
[2023-03-05 20:53:08][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/1180/01
[2023-03-05 20:53:08][DEBUG] :   'Bypass' (0006-01-0000) => 0
[2023-03-05 20:53:08][DEBUG] :   'Vitesse' (0006-02-0000) => 0
[2023-03-05 20:53:08][DEBUG] :   'Puissance Inst' (000C-01-0055) => 0.03394603729248 W
```

**Comment by eoeir** [comment]
J'ajoute un package de logs.
[AbeilleLogs-230305.tar.gz](https://github.com/KiwiHC16/Abeille/files/10892900/AbeilleLogs-230305.tar.gz)

**Comment by tcharp38** [comment]
Effectivement ce truc ne semble pas à jour.

Nouveau modele pour test:
[relay.c2acn01.json.zip](https://github.com/KiwiHC16/Abeille/files/10898502/relay.c2acn01.json.zip)

J'ai ajoute voltage, current + total power

**Comment by eoeir** [comment]
C'est beaucoup mieux : 

![image](https://user-images.githubusercontent.com/71673288/223257683-50c2d17b-57c5-48fb-b17d-e4aead23665b.png)

Je laisse tourner et je regarde si les valeurs sont cohérentes demain.

**Comment by eoeir** [comment]
Statut à ce soir : 

- Current : les valeurs évoluent mais restent très faibles
- Total Power : est bien un cumul de valeurs faibles, semble donc OK
- Active Power : une seule valeur à 1W lors d'un test ce soir (20h15)
- Voltage : OK

Difficile de se prononcer sur _Current_ et _Active Power_ car ça peut être lié à mon montage particulier. Tu vois des choses au niveau des logs ?

[AbeilleLogs-230307.tar.gz](https://github.com/KiwiHC16/Abeille/files/10914263/AbeilleLogs-230307.tar.gz)

**Comment by tcharp38** [comment]
Rien qui cloche dans les logs. Le decodage des valeurs semble bon.

Comment alimentes tu ta VMC ? Bypass & vitesse sont reliés comment ?
J'ai l'impression qu'il n'y a pas de charge derriere, donc normal que le courant ou puissance soit ridicile.

L'idéal serait de mettre une vraie charge connue, ex une ampoule 100w, et la on peut confirmer les mesures.

**Comment by eoeir** [comment]
Ils sont directement reliés à la VMC mais je pense également qu'il n'y a pas de charge sur ces circuits. La vitesse et le bypass s'adaptent simplement en fonction de la présence ou non du 220v sur les circuits.

A l'occasion je pourrai tester avec une ampoule mais ça ne vas pas être tout de suite car c'est pas très accessible dans les combles...

**Comment by tcharp38** [comment]
Ok.
Je modifie juste le modele pour reduire le nombre de chiffres apres la virgule. La c'est crade.

En dehors de ca ca te convient et on peut clore le sujet ?

**Comment by eoeir** [comment]
Oui, on peut fermer.
Je verrai ensuite en fonction du résultat du test de charge.

**Comment by tcharp38** [comment]
Ok.
Ne pas hesiter à réouvrir si besoin.
