### ISSUE TITLE
Module volet roulant LoraTap SC500ZB-v2 (id = TS130F,_TZ3000_femsaaua)

### ISSUE THREAD

**Issue by thedrgraph** [KiwiHC16/Abeille#2552]
Hello,

Très proche en apparence du Module Zigbee volet roulant LoraTap (id = TS130F, _TZ3000_e3vhyirx) #2528
il n'a pas le même code voici le discovery :
[discovery-TS130F,_TZ3000_femsaaua.txt](https://github.com/KiwiHC16/Abeille/files/10949117/discovery-TS130F._TZ3000_femsaaua.txt)

Pour l'image tu peut reprendre la même que le TS130F, _TZ3000_e3vhyirx on doit en avoir un gen 1 et l'autre gen 2 a mon avis
Merci.

**Comment by tcharp38** [comment]
Ok je pars du principe que c'est le meme comportement.

Voila le modele commun a decompresser dans core/config/devices/TS130F__TZ3000_e3vhyirx
[TS130F__TZ3000_e3vhyirx.zip](https://github.com/KiwiHC16/Abeille/files/10961528/TS130F__TZ3000_e3vhyirx.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by thedrgraph** [comment]
Apparemment c'est fonctionnel il faut juste que je confirme les % indiqués.
Je vais tester sur la semaine.

Merci.

**Comment by thedrgraph** [comment]
Hello, 

j'ai fait un test pour voir les % il sont a la ramasse complet.
Si je me met a 0% donc fermer et que j'ouvre si je stop une fois ouvert (quand le volet coupe de lui même) je suis a 48% 
a noté que le volet a ces fin de course de régler donc ce stop de lui même mais il n'y a pas de retour d'info du dit fin de course donc le boîtier lui continue d'envoyer l'info up ou down pendant un certain temp. je voit pas comment le "calibrer" pour lui donner les bonne valeur haute et basse surtout sans avoir de retour d'info des fin de course. 
pour info : volet roulant 4 fils terre/neutre/ rotation up/ rotation down
donc pas de retour d'info possible.

**Comment by tcharp38** [comment]
J'imagine que les fins de course du volet sont mecaniques.
Le module doit detecter une surconso en fin de course et devrait etre capable de faire un retour d'info graçe au calibrage.

Non ?

**Comment by thedrgraph** [comment]
Aucune idée mais j'ai pas l'impression ce volet était présent quand j'ai acheter la maison.
Mais au bruit j'ai l'impression qu'il s'agit de fin de course électromécanique ce qui serait mieux d’ailleurs :)

**Comment by tcharp38** [comment]
Peux tu faire un
- up + noter l heure
- attendre l'ouverture ou arret
- down et noter l heure
- attendre fermeture ou arret
- me filer le package de logs

Merci


D'ailleurs, ce modele à la meme ref que l'autre ? SC500ZB ?

**Comment by thedrgraph** [comment]
Pour le modele la ref est SC500ZB-v2 sur le manuel.
j'ai pas eu le temp de faire les manip pour le moment :(

**Comment by thedrgraph** [comment]
Hello bon j'ai eu le temps de faire des test que voici :
[AbeilleLogs-230423.tar.gz](https://github.com/KiwiHC16/Abeille/files/11303383/AbeilleLogs-230423.tar.gz)

1 fermeture via le bouton mural

11h47 début fermeture
11h47 arrivé en bas
appuie sur stop
11h48 début ouverture
11h48 fin ouverture 
appuie sur stop

2 utilisations des commande jeedoom

11h50 demande descente
11h50 fin fermeture
11h51 auto stop

11h52 ouverture
11h52 ouvert
11h53 auto stop

en gros le volet a besoins de moins de 30 secondes pour être ouvert ou fermer et le plugin considère qu'il faut 1 minutes  

Merci

**Comment by tcharp38** [comment]
Salut.
Un peu perdu dans tous tes essais.
Je ne sais pas ce qui se passe bien de ce qui se passe mal.

Tu peux faire ces manips ?

> Peux tu faire un
> 
> up + noter l heure
> attendre l'ouverture ou arret
> down et noter l heure
> attendre fermeture ou arret
> me filer le package de logs

**Comment by thedrgraph** [comment]
En fait c'est ce que j'ai fait ci dessus 
En premier via la commande physique relier au boitier et en second avec l'interface jeedom
pour les test je part ouvert je descend le volet et fermer en moins de 30s et si je fait un stop je ne suis pas a 100% 
pour le module 100% (ou 0%) c'est après 1min de mouvement dans un sens ou l'autre y a t'il moyen de "calibré" ce pourcentage ou le temps pour atteindre les valeur max et mini ? 
nota sans passé par l'app officiel loratap, bien sur.

**Comment by tcharp38** [comment]
Tiens, voila un nouveau modele avec "Calibration" & "Set calibration" pour test.
Faire une mise à jour via sa page avancé

[TS130F__TZ3000_e3vhyirx.zip](https://github.com/KiwiHC16/Abeille/files/11313255/TS130F__TZ3000_e3vhyirx.zip)

**Comment by thedrgraph** [comment]
Hello 

nickel Merci :)

**Comment by tcharp38** [comment]
Ca veut dire quoi ? Ca repond aux derniers soucis ?

**Comment by thedrgraph** [comment]
la nouvelle version corrige le soucis de timing tu peut validé :)

**Comment by tcharp38** [comment]
Ha cool.
Donc on peut fermer ce sujet ou il reste des choses à voir pour ce device ?

**Comment by thedrgraph** [comment]
on peut clôturé,
Merci
