### ISSUE TITLE
Intégration / Equipement Xiaomi non reconnue

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2553]
Salut
J'ai tout remis à neuf concernant Abeille: Plus de Zigate v2, flash de la v1 en v3.23 OPDM, réinstalation du plugin, ruche etc.
Abeille est en beta 2023-03-12 01:00:18

Mon souci est sur les équipements "end point" de xiaomi, interrupteur, detecteur de mouvement et capteur d'ouverture.
Ils ne sont pas reconnu dans abeille.
Un exemple de chaque :
E915 / 00158D0001875DC4 : capteur d'ouverture
8DA1 / 00158D00079AB434 : interrupteur rond
9ECA / 00158D00044C2111 : detecteur de mouvement

Une piste ?
Pour info, si ca peut t'aider, 00158D0001875DC4 est le derniers équipement que j'ai intégré ce matin

[AbeilleLogs-230312 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/10950490/AbeilleLogs-230312.1.tar.gz)

**Comment by Jake309** [comment]
E915 / 00158D0001875DC4 s'est mise a jour et m'a créé les commandes.
J'ai essayé avec un autre capteur d'ouverte, pareil, vierge, le 2575 / 00158D00019DA8E0
J'ai refait des inclusions avec F412 / 00158D000202DB75 pas de changement

[AbeilleLogs-230312 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/10951352/AbeilleLogs-230312.2.tar.gz)

**Comment by tcharp38** [comment]
Je vois beaucoup d'erreurs du type
"Abeille1, unexpected IEEE => msg 8702 ignored. Port switch ??"

Tu as changé la zigate de port surement dans tes manips non ?

Si oui il y a une partie "changement de zigate" sur la page des equipements.
Tu dois indiquer que la nouvelle zigate doit etre acceptée.

![image](https://user-images.githubusercontent.com/35221038/224820481-62518b58-84f1-4f16-9c40-abacc78f125e.png)

Ha et je ne vois aucun "Device announce".. donc l'equipement ne s'annonce meme pas.

**Comment by Jake309** [comment]
Ha bien vue, j'avais homis ce detail :/
J'ai retenté des inclusions, mais c'est pas ca qui est a l'origine je pense
8DA1 / 00158D00079AB434 : interrupteur rond
9ECA / 00158D00044C2111 : detecteur de mouvement

[AbeilleLogs-230314.tar.gz](https://github.com/KiwiHC16/Abeille/files/10970676/AbeilleLogs-230314.tar.gz)

C'est bizarre que tu me dises qu'ils s'annoncent pas, car ils sont créé en inconnue 
![image](https://user-images.githubusercontent.com/49479084/225058652-5fb9d134-40bf-4503-a6cb-923155ef5c1e.png)
![image](https://user-images.githubusercontent.com/49479084/225058953-b680d774-73b6-4684-a52e-3e1cfd88beac.png)

**Comment by tcharp38** [comment]
On dirait qu'il y a un truc bizarre.
On va se focaliser sur le plus simple pour toi avec lequel faire des essais.

Peux tu confirmer qu'il n'a aucun modele d'équioement identifié ?

Je sens que tu es tombé sur une regression mais la j'ai les yeux qui tombent alors je creuse ça demain.

**Comment by tcharp38** [comment]
Tu peux tester avec ca ?

A decompresser dans core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/10984033/AbeilleParser.class.php.zip)

puis redemarrer Abeille

et retenter l'inclusion

**Comment by Jake309** [comment]
Salut @tcharp38 
Vraiment désolé pour le délais, en ce moment c'est compliqué de trouver du temps.

Alors, j'ai pris un nouveau capteur d'ouverture jamais intégré pour qu'on puisse mieux voir et comprendre.

Sans ton fichier : 
FD2A / 00158D000172075E
Abeilles1-766
Inclusion à 10h47
Même résultat, model non reconnue, aucune commande.

Avec ton fichier et relance des démons:
E1D6 / 00158D0002391EEA
Abeille1-767
inclusion à 10h55
Pas dévolution

J'ai rententé le FD2A / 00158D000172075E, comme je voyais rien, je l'ai sortie quand la zigate n'était pas en inclusion, je l'ai relancé et réessayé d'intégrer, le capteur ne s'est pas réactivé.
J'ai également tenté le bouton rond du 1er poste avec ton fichier, RAS.

[AbeilleLogs-230319.tar.gz](https://github.com/KiwiHC16/Abeille/files/11010639/AbeilleLogs-230319.tar.gz)

**Comment by tcharp38** [comment]
Je n'ai pas l'impression que tu aies utilisé mon code: soit decompréssé au mauvais endroit soit Abeille pas redemarré.
Je refais qq essais et je pousse une nouvelle beta pour demain. Ca sera + simple.

**Comment by Jake309** [comment]
![image](https://user-images.githubusercontent.com/49479084/226205499-53924098-835a-4467-ac08-0bc14a75fe0b.png)

Je l'ai mis la. Pour le redémarrage, on est bien d'accord que les démons suffise ?

![image](https://user-images.githubusercontent.com/49479084/226205535-99dd2152-3391-494c-ac67-787ad18a6491.png)

Je recharge ton fichier, redémarre jeedom complètement et refais un essai

**Comment by Jake309** [comment]
Alors, les 2 sont passés:
FD2A / 00158D000172075E
Abeilles1-766
E1D6 / 00158D0002391EEA
Abeille1-767

J'ai réussi a remettre le poussoir rond et carré : 
E786 / 00158D00027C92A0       C68B / 00158D0002AD8DF1

Par contre, pour avoir la notif et l'apparition, une fois intégré, je dois faire une pression simple du le bouton d'appairage. Avant, une fois l'inclusions lancé et faite ( 3 clignotements) mon équipement était créé.
Peut etre du au fait qu'ils existaient mais en inconnu

[AbeilleLogs-230319.tar.gz](https://github.com/KiwiHC16/Abeille/files/11012171/AbeilleLogs-230319.tar.gz)

**Comment by tcharp38** [comment]
Ha je prefere ca.
Tout est dans la beta dispo ce jour.
Je te laisse refaire des essais apres mise à jour et me dire si on peut clore ce sujet.
Je voudrais faire une stable rapidos et c etait un des points bloquants.

**Comment by Jake309** [comment]
Salut,

J'ai eu la surprise ce matin :
| 2023-03-20 06:58:11 | Abeille | [Salle de bain haut][Mvt SdB Haut]: Nouvel équipement identifié.
J'ai essayé de le réintégrer hier soir il devait être 22h environ, c'était le dernier type d'équipement récalcitrant.

Si ca peut t'aider, je te mets les log j'espère qu'il y aura de l'info vue l'heure.

[AbeilleLogs-230320.tar.gz](https://github.com/KiwiHC16/Abeille/files/11015932/AbeilleLogs-230320.tar.gz)

PS: j'ai oublié d'appuyer sur envoyer ce matin ^^

**Comment by tcharp38** [comment]
Il a été intégré à 6:58. 
Donc pas de logs du Parser.. l'evenement est trop vieux.

Par contre je pense qu'il ne s'est pas réannoncé. Il a juste donné des nouvelles et Abeille a fini par l'identifier.
Le message "nouvel equipement" est donc faux.

Bref.. des soucis avec ce device ?
Pense à basculer sur la derniere beta avec les fixes officiels STP

**Comment by Jake309** [comment]
Je passe la MAJ, mais je ne pourrai pas tester avant demain soir, je prends la route des que je rentre ce soir et rentre en fin de journée demain.
Je te tiens au courant demain soir. J'ai encore des équipements a intégrer et des inconnue à remettre dans le bon chemin ^^

**Comment by tcharp38** [comment]
Pas de soucis.

**Comment by Jake309** [comment]
Salut @tcharp38 
Avec la mise à jour j'ai retrouvé mon comportement d'avant.
Des modules qui vont bien, d'autres qui font n'importe quoi, mais du déjà vue.
C'est les capteurs qui sont pas top. J'attends de récupérer ma gateway xiaomi pour voir s'il n'y a pas de mise à jour dessus.
Mais du coup, pour ma part c'est bon.
On peut clore le sujet si t'as pas d'autre test a faire (je retrouve de la dispo) et si ta stable est prete, on peut y aller :)

**Comment by tcharp38** [comment]
Ok je ferme ce sujet.
J'attends ce WE et je bascule la beta en stable si pas de point bloquant.
