### ISSUE TITLE
Prise encastrée MOES ZK-FR16M-WH (id=TS011F,_TZ3000_ss98ec5d)

### ISSUE THREAD

**Issue by eoeir** [KiwiHC16/Abeille#2554]
Je viens d'intégrer ce module de prise encastrée MOES ZK-FR16M-WH : 

![image](https://user-images.githubusercontent.com/71673288/224578748-3d564d48-c2a9-4eb5-ae68-b0085e26025a.png)

https://www.domotique-store.fr/domotique/usages/mesure-de-consommation-energetique-domotique/prises-domotique-mesure-consommation-energie/1829-prise-encastree-connectee-zigbee-compatible-tuya-smart-life-google-home-et-amazon-alexa.html

Il est détecté par Abeille comme un Sixwgh WH025 plug (TS011F__TZ3000_cphmq0q7) mais semble bien fonctionner : 

![image](https://user-images.githubusercontent.com/71673288/224578731-ff3abaa6-e1fe-4c43-9bce-36446e56cc40.png)

Inclusion à 23:24

[AbeilleLogs-230312.tar.gz](https://github.com/KiwiHC16/Abeille/files/10952306/AbeilleLogs-230312.tar.gz)

Est-ce possible de faire un modèle spécifique ?

**Comment by tcharp38** [comment]
Salut @eoeir 

Je modifie le modele pour ne changer que le nom, modele, et image.

A decompresser dans core/config/devices/TS011F__TZ3000_cphmq0q7
[TS011F__TZ3000_cphmq0q7.zip](https://github.com/KiwiHC16/Abeille/files/10967307/TS011F__TZ3000_cphmq0q7.zip)

A decompresser dans "images"
[node_Tuya-SmartSocket-3.zip](https://github.com/KiwiHC16/Abeille/files/10967310/node_Tuya-SmartSocket-3.zip)

Tu peux tenter un "reinit" via la page avancé

**Comment by eoeir** [comment]
Je n'ai pas eu le temps de m'occuper de ce sujet récemment.

C'est OK pour l'image mais la réinitialisation après la mise à jour du modèle n'a pas eu d'effet sur le device...

J'ai remarqué un autre sujet bien gênant. La prise se coupe toute seule pour une raison que je n'ai pas identifiée à ce stade.
On voit par exemple ici qu'elle s'est arrêtée à 22:49 hier alors que je n'ai pas fait d'action pour la couper :

[2023-04-13 22:49:10][DEBUG] : msgFromParser(): Read attributes response by name from 'Abeille1/3259/01
[2023-04-13 22:49:10][DEBUG] :   'RMS Voltage' (0B04-01-0505) => 232 (calculValueOffset=#value#*1/1)
[2023-04-13 22:49:10][DEBUG] :   'RMS Current' (0B04-01-0508) => 544 mA
[2023-04-13 22:49:10][DEBUG] :   'Active Power' (0B04-01-050B) => 98 (calculValueOffset=#value#*1/1)
**[2023-04-13 22:49:12][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3259/01
[2023-04-13 22:49:12][DEBUG] :   'Status' (0006-01-0000) => 0**
[2023-04-13 22:49:12][DEBUG] :   Triggering 'Poll 0B04' with delay 5
[2023-04-13 22:49:12][DEBUG] :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/3259\/readAttribute&time=1681418957","payload":"ep=01&clustId=0B04&attrId=0505,0508,050B"}' vers queue 1212
[2023-04-13 22:49:12][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3259/01
[2023-04-13 22:49:12][DEBUG] :   'Status' (0006-01-0000) => 0
[2023-04-13 22:49:12][DEBUG] :   Triggering 'Poll 0B04' with delay 5
[2023-04-13 22:49:12][DEBUG] :   publishMosquitto(): Envoyé '{"topic":"TempoCmdAbeille1\/3259\/readAttribute&time=1681418957","payload":"ep=01&clustId=0B04&attrId=0505,0508,050B"}' vers queue 1212
[2023-04-13 22:49:12][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3259/01
[2023-04-13 22:49:12][DEBUG] :   Unknown Jeedom command logicId='E001-01-D001'
[2023-04-13 22:49:18][DEBUG] : msgFromParser(): Read attributes response by name from 'Abeille1/3259/01
[2023-04-13 22:49:18][DEBUG] :   'RMS Voltage' (0B04-01-0505) => 0 (calculValueOffset=#value#*1/1)
[2023-04-13 22:49:18][DEBUG] :   'RMS Current' (0B04-01-0508) => 0 mA
[2023-04-13 22:49:18][DEBUG] :   'Active Power' (0B04-01-050B) => 0 (calculValueOffset=#value#*1/1)
[2023-04-13 22:49:18][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3259/01
[2023-04-13 22:49:18][DEBUG] :   Unknown Jeedom command logicId='E001-01-D001'

Voici le package de logs complet :
[AbeilleLogs-230414.tar.gz](https://github.com/KiwiHC16/Abeille/files/11236671/AbeilleLogs-230414.tar.gz)

**Comment by tcharp38** [comment]
Salut
Je ne vois rien dans tes logs.
A priori la commande d'arret ne vient pas d'Abeille.
Mais en regardant le net je vois qu'elle a une fonction "minuterie".

Ca veut dire qu'il faut creuser pour s'assurer que ce truc est desactivé.
Mais pour ca il faut qu'elle soit supporté ailleurs pour comprendre comment on gere ca.

Peux tu deja me generer un discovery ?

**Comment by eoeir** [comment]
Effectivement je n'avais pas vu toutes ces fonctions : "Fonctions minuterie, programmations hebdomadaires, simulation de présence, etc."

Voici le fichier discovery.

[discovery-TS011F__TZ3000_ss98ec5d.zip](https://github.com/KiwiHC16/Abeille/files/11239449/discovery-TS011F__TZ3000_ss98ec5d.zip)

**Comment by tcharp38** [comment]
Pour toutes ces fonctions il y a des attributs cachés car privés, surement dans les clusters E000 ou E0001.
Mais sans passerelle Tuya et un sniffer pour faire du reverse engineering...
ou qqn d'autre qui a trouvé comment supporter cet equipement.

Tout ca pour dire que la je seche pour trouver ces fonctionalites cachées.

**Comment by eoeir** [comment]
Visiblement c'est un problème connu sur les prises TS011F : 
[https://community.jeedom.com/t/prises-zigbee-qui-passent-en-off-toutes-seul/81067/23](url)
[https://community.home-assistant.io/t/tuya-zigbee-plug-turning-itself-off/396484/55](url)

Et il semblerait que certains arrivent à résoudre le problème avec une mise à jour de firmware : 
[https://community.home-assistant.io/t/zha-ota-firmware-update-upgrade/488960](url)

Est-ce qu'à ton avis je peux faire une maj OTA avec ce fichier ? 
https://images.tuyaeu.com/smart/firmware/upgrade/20220907/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin

**Comment by tcharp38** [comment]
Ha bonnes recherches.
Je découvre un FW Tuya pour la premiere fois.

Il faut que tu tentes via la page OTA.
Tu ajoutes le FW
et notifie ta prise
Si les infos coincident, la maj va démarrer, sinon.. ca n'est pas le bon FW.

File moi le package de logs dans la foulée

**Comment by eoeir** [comment]
Comment l'ajouter ? 
Le format ne semble pas supporté par la page OTA d'Abeille (ne reconnait pas les .bin et ça ne fonctionne pas en le renommant en .ota)

**Comment by tcharp38** [comment]
Si ca fonctionne, je viens de tenter

> [2023-04-16 11:42:17] OTA FW: 1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin
> [2023-04-16 11:42:17]   startIdx=0
> [2023-04-16 11:42:17]   header={"otaUpgradeFileId":"0BEEF11E","otaHeaderVersion":"0100","otaHeaderLength":"0038","otaHeaderFieldControl":"0000","manufCode":"1141","imageType":"D3A3","fileVersion":"000000C0","zigbeeStackVersion":"0002","otaHeaderString":"54656c696e6b204f54412053616d706c65205573616765000000000000000000","totalSize":"0004B1E2"}
> [2023-04-16 11:42:17]   OTA FW for 1141: imgType=D3A3, version=000000C0

Quand tu fais ajouter, selectionne "tous les fichiers"
![image](https://user-images.githubusercontent.com/35221038/232290731-9f0556aa-8dc0-4b61-8454-154f166b863d.png)

**Comment by eoeir** [comment]
Ok pour "tous les fichiers" mais il ne se passe rien chez moi après ouvrir. La fenêtre disparait et c'est tout... Quel est le log qui donne ces traces ?

**Comment by tcharp38** [comment]
AbeilleParser.log

**Comment by eoeir** [comment]
Rien dans AbeilleParser.log

Comme c'est la première fois que je tente une maj OTA, je ne sais pas si je loupe quelque chose ou si il y a un bug.

Il y a une conf à faire quelque part avant ?

**Comment by tcharp38** [comment]
Non aucune conf.
Il faut ajouter le fichier
puis notifier l'equipement qu'un FW est dispo.
J'avais mis une doc en ligne https://kiwihc16.github.io/AbeilleDoc/Utilisation.html#mise-a-jour-over-the-air

Fais ces 2 manips et file moi le package dans la foulée STP

**Comment by eoeir** [comment]
J'ai fait un enregistrement de la manip parce que je ne vois pas apparaître le firmware après l'avoir ajouté. Je l'ai retéléchargé mais ça n'a rien changé. Idem en changeant de navigateur...

[screen-recording.webm](https://user-images.githubusercontent.com/71673288/233770473-9bdb182e-4532-4924-9c4e-2337d3a2041b.webm)

[AbeilleLogs-230422.tar.gz](https://github.com/KiwiHC16/Abeille/files/11300575/AbeilleLogs-230422.tar.gz)

**Comment by tcharp38** [comment]
Decompresse ce fichier dans Abeille/core/php
[AbeilleUpload.zip](https://github.com/KiwiHC16/Abeille/files/11302146/AbeilleUpload.zip)

et retente STP

**Comment by eoeir** [comment]
Pas de changement visible...

Voici les logs : 
[AbeilleLogs-230422(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11302281/AbeilleLogs-230422.1.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois pas mes commentaires dans les logs donc je suppose que ca n'est pas mon dernier code.
Mais peu importe. je te suggere de retenter sur la beta dispo ce jour.

**Comment by eoeir** [comment]
Je suis passé à la version d'aujourd'hui, j'ai retenté l'opération mais toujours rien.

Voici les logs : 
[AbeilleLogs-230502.tar.gz](https://github.com/KiwiHC16/Abeille/files/11377771/AbeilleLogs-230502.tar.gz)

**Comment by tcharp38** [comment]
Je vois une erreur à la création du repertoire contenant les FW

> [2023-05-02 23:08:03] AbeilleUpload: tmpFile=/tmp/phpJ4vl5d
> [2023-05-02 23:08:03] AbeilleUpload: ERROR: Can't create destination dir
> 

Peux tu decompresser ce fichier dans Abeille/core/php
[AbeilleUpload.zip](https://github.com/KiwiHC16/Abeille/files/11380888/AbeilleUpload.zip)

puis juste cliquer sur ajouter FW
et me filer les logs

Tant que le FW n apparait pas dans les FW dispos.. inutile d aller + loin.

**Comment by eoeir** [comment]
Fait, sans résultat apparent.
Je vois la même erreur dans le log AbeilleDebug.

[AbeilleLogs-230503.tar.gz](https://github.com/KiwiHC16/Abeille/files/11391121/AbeilleLogs-230503.tar.gz)

**Comment by tcharp38** [comment]
Tout à fait meme erreur mais normal vu que je n'ai fait qu'ajouter un message de debug

> [2023-05-03 22:47:21] AbeilleUpload: destDir='/var/www/html/plugins/Abeille/core/php/../../tmp/fw_ota'
> [2023-05-03 22:47:21] AbeilleUpload: ERROR: Can't create destination dir

Du coup je sais maintenant qu'il n arrive pas à creer tmp/fw_ota dans le plugin Abeille.
Peux tu me dire si "tmp" existe ? C'est peut etre ça.
Chemin: /var/www/html/plugins/Abeille/tmp

Si il n'existe pas, pour confirmer peux tu le creer puis retenter la manip "ajouter FW"

**Comment by eoeir** [comment]
J'ai créé le répertoire et cela a fonctionné. Cela ne corrige pas le soucis avec la création autonome du répertoire par Abeille.

J'ai lancé la MAJ OTA et cela semble aussi OK car j'ai eu une notification de lancement de la mise à jour et je vois la prise demander les blocs du FW. Je ne sais pas si cela a réussi car je ne sais pas quoi chercher dans les logs pour le confirmer.

[AbeilleLogs-230504.tar.gz](https://github.com/KiwiHC16/Abeille/files/11394232/AbeilleLogs-230504.tar.gz)

**Comment by tcharp38** [comment]
Merci pour tes essais. Je vais corriger ce petit souci de tmp.

La maj démarre bien mais je la vois s'arreter
Dernier transfert:

> [2023-05-04 07:59:07] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0019, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=3259, DstAddrMode=02, DstAddr=0000
> [2023-05-04 07:59:07]   FCF=01/Cluster-specific/Cli->Serv, SQN=DE, cmd=03/Image Block Request
> [2023-05-04 07:59:07]   fieldCtrl=02, manufCode=1141, imgType=D3A3, fileVers=000000C0, fileOffset=00000480, maxData=40
> 

puis ne repond plus

> [2023-05-04 07:59:07] Abeille1, Type=8702/APS data confirm fail, Status=E9/MAC_ENUM_NO_ACK, SrcEP=01, DstEP=01, AddrMode=02, Addr=3259, SQNAPS=8C, NPDU=00, APDU=00

et enfin + tard il reprend du service mais la maj est abandonnée.
Etrange.
En tout cas pas de soucis coté Abeille a priori.
Peut etre va t il retenter une maj + tard

**Comment by tcharp38** [comment]
Salut @eoeir 
On fait quoi avec ce sujet ?

**Comment by eoeir** [comment]
Cette prise ne me satisfait pas. C'est loin d'être gagné d'arriver à gérer la fonction minuterie et je ne vais pas investir dans une passerelle tuya pour essayer de mettre à jour le firmware.
Donc de mon côté, j'abandonne.

**Comment by tcharp38** [comment]
@eoeir 
Ca te dit de m'envoyer cette prise que je regarde de + pres ? Sans promesse par contre.
Si oui envoie moi un email @ tcharp38@laposte.net
