### ISSUE TITLE
ZigBee amplificateur de Signal USB-3 (id = ZB-SW01)

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2555]
Bonjour,
Je viens de faire l'acquisition d'une clé usb pour amplifier/répéter un signal zigbee, non reconnu par Abeille.
Voici la référence, ZigBee – amplificateur de Signal USB 3.0, répéteur de Signal pour Tuya eWeLink et quelques infos.
![ZigBee_3 0_USB_Signal_Amplifier](https://user-images.githubusercontent.com/104787819/225702034-4aa07096-6d3e-48b1-93e4-f032e8e9fc06.png)
[AbeilleLogs-230316.tar.gz](https://github.com/KiwiHC16/Abeille/files/10993847/AbeilleLogs-230316.tar.gz)
![2023-03-16_182959](https://user-images.githubusercontent.com/104787819/225703957-55208a40-3917-421a-89d1-71ff1b72ba01.jpg)
Merci pour votre aide.
Cordialement

**Comment by tcharp38** [comment]
Salut @Jeedom122 
Meme requete habituelle pour un nouvel equipement... generer un discovery via l'assistant.

Ha mais je vois un souci.
Il s'identifie "ZB-SW01"... donc ca n'est pas un nouvel equipement.
Pourquoi dis tu qu'il n'est pas reconnu par Abeille ?

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Effectivement, abeille a installé la clé usb avec le plugin de l'interrupteur eWeLink ZB-SW01, d’où la fonction on/off ?
Alors que c'est simplement un répéteur de Signal pour Zigbee eWeLink, la passerelle avec les autres modules fonctionne.
![2023-03-17_090555](https://user-images.githubusercontent.com/104787819/225847892-b38efd8b-d4a2-4c8c-beed-2e952c02e0a2.jpg)
Peut-être juste modifier le plugin eWeLink ZB-SW01 pour ne garder que l'essentiel et intégrer l'image ?
Bonne journée !

**Comment by tcharp38** [comment]
Salut
Ce device s'identifie comme un autre donc AUCUN moyen de le differencier.
Si je casse le modele pour ton repeteur, alors les autres devices avec la meme signature seront en manque de fonctionalités.

Ex: ce device est probablement celui qui a servi pour le modele: https://zigbee.blakadder.com/eWeLink_ZB-SW01.html
Et voila le tient on dirait: https://zigbee.blakadder.com/easyiot_ZB-Router.html

En gros ton repeteur ne devrait pas s identifier comme ca. Je pige pas pourquoi il livrent des cochonneries pareil.

Bref.. je ne vois pas de solution, ni pour changer l icone, ni le nom. Nada.
Tu vois la problématique ?

**Comment by Jeedom122** [comment]
Oui tout à fait !
S'il fonctionne, je peux juste désactiver les fonctions inutiles et intégrer la bonne image manuellement.
La seule information qui m'intéresse ses ça disponibilité en ligne et la qualité du lien.
Donc je clôture le sujet ?

**Comment by tcharp38** [comment]
Ok on est en ligne.
Je clos. A reouvrir si besoin

**Comment by Jeedom122** [comment]
Merci @tcharp38 pour ton expertise.
Bon weekend...
