### ISSUE TITLE
[KiwiHC16] Suite à re-install PiZigate V1, lib wiringpi pas dispo, migration vers PiGpiod.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2556]
Tracking du cas pour l instant dans gitlab perso jeedom/Abeille#32

**Comment by KiwiHC16** [comment]
I pushed a proposed first implementation in commit [1cf5166](https://github.com/KiwiHC16/Abeille/commit/1cf5166b129f46079143b967170021c65d2da474)

Tested on Dev RPI3.

Implementation of new PiGpio is done in // of legacy WiringPi.

Both should work.

Select the one to be used in the plugin config page.

![Capture d’écran 2023-03-17 à 15 05 24](https://user-images.githubusercontent.com/8549674/225927617-93c1b972-c1b4-49e6-945d-a27aa61be068.png)

J espere ne rien avoir cassé car j ai un peu galéré avec Git...

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-03-17 à 15 06 18](https://user-images.githubusercontent.com/8549674/225927840-518da297-cd77-422d-a77f-397198404e7f.png)

Upgrade to the latest firmware done but during dev so need to check Abeille UI again and again.

**Comment by tcharp38** [comment]
A priori c'est intégré et aucun retour la dessus.
Je clos. A reouvrir si soucis
