### ISSUE TITLE
AUBESS prise avec moniteur de conso (id = TS011F,  _TZ3000_gvn91tmx)

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#2558]
Bonjour j'ai fait l'acquisition de 4 de ces prises, apparaige et détection avec Abeille OK sauf que la consommation et puissance instantanées ne sont pas remontés.

Detecté en tant que "Yagusmart Tuya ZigBee Smart Switch"

[discovery-TS011F__TZ3000_gvn91tmx.json.txt](https://github.com/KiwiHC16/Abeille/files/11011167/discovery-TS011F__TZ3000_gvn91tmx.json.txt)

**Comment by Jorael57** [comment]
Lien vers l'article :  https://fr.aliexpress.com/item/1005005097656228.html

**Comment by Jorael57** [comment]
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/11011217/AbeilleParser.log)

**Comment by tcharp38** [comment]
Salut
Voila un modele preliminaire a decompresser dans core/config/devices
[TS011F__TZ3000_gvn91tmx.zip](https://github.com/KiwiHC16/Abeille/files/11011986/TS011F__TZ3000_gvn91tmx.zip)

puis redemarrer Abeille
refaire inclusion
tester
filer le package de logs et pas de log seul.

**Comment by Jorael57** [comment]
[AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/11023492/AbeilleSerialRead1.log)
[AbeilleParser (1).log](https://github.com/KiwiHC16/Abeille/files/11023493/AbeilleParser.1.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/11023494/AbeilleCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/11023496/Abeille.log)

Tester mais rien de remonte et le on/off ne fonctionne plus avec ce modèle . Par contre la prise a un comportement anormal depuis, à intervalle régulier elle fait un off/on rapide ( chose qu'elle ne faisait pas hier)

**Comment by tcharp38** [comment]
Salut
Je ne peux rien faire avec ca.

Il me faut le package de logs et pas les logs séparés. C'est d'ailleurs bien + simple pour toi.
D'autre part je ne sais pas comment il s'appelle, ou son adresse.

- Bref, peux tu basculer sur la beta du jour,
- faire une "mise à jour" via la page avancé de ton equipement
- faire un ON et OFF et noter l'heure
- et me filer le package de logs

**Comment by Jorael57** [comment]
> Salut Je ne peux rien faire avec ca.
> 
> Il me faut le package de logs et pas les logs séparés. C'est d'ailleurs bien + simple pour toi. D'autre part je ne sais pas comment il s'appelle, ou son adresse.
> 
> * Bref, peux tu basculer sur la beta du jour,
> * faire une "mise à jour" via la page avancé de ton equipement
> * faire un ON et OFF et noter l'heure
> * et me filer le package de logs

C'est quoi ce que tu appelles le package de log ? le télécharger tout dans maintenance de abeille ?

**Comment by tcharp38** [comment]
Oui le package via "telecharger tout" de la page maintenance. 
Tu peux directement faire un drag & drop ici. Il est concu pour ca et est bien + complet que les qq logs visibles via la page de config.

**Comment by Jorael57** [comment]
[AbeilleLogs-230321.tar.gz](https://github.com/KiwiHC16/Abeille/files/11034134/AbeilleLogs-230321.tar.gz)

le on et off sont autour de 22h59

**Comment by tcharp38** [comment]
Alors je ne vois aucun retour d'info du ON ou OFF mais il se met a envoyer des tas de reporting de power à 0.

Est ce que le ON/OFF fonctionnait, avec un retour avec le modele "Yagusmart Tuya ZigBee Smart Switch" ?

**Comment by Jorael57** [comment]
Non le On Off ne fonctionnait pas , par contre  il fait un "auto"  OFF puis ON très rapidement  à intervalle régulier. Je ne sais pas si c'est un problème de la prise ou de abeille, mais ça ne le faisait pas le premier jour. Et la 2 prise le font . Je réessaye ce soir

**Comment by tcharp38** [comment]
Donc meme si pas de retour du status, tu ne peux pas commander ON ou OFF, quel que soit le modele.

**Comment by Jorael57** [comment]
Je n'est pas essayer de nouveau avec Yagusmart Tuya ZigBee Smart Switch

**Comment by tcharp38** [comment]
Non inutile d essayer. Je voulais juste savoir si ca faisait qqch avant.
Tu es sur que cote prise, rien ne change avec On ou Off ? Si tu n'as rien branché dessus il doit au moins y avoir un voyant non ?

**Comment by Jorael57** [comment]
> Je n'est pas essayer de nouveau avec Yagusmart Tuya ZigBee Smart Switch

Ah avec ce modèle le on/off depuis jeedom fonctionnait on s'est mal compris je pense.

**Comment by tcharp38** [comment]
Ha.. c 'est ce que j'essaie de comprendre.
Donc si ca fonctionnait avec le modele initial Yagusmart, voila celui la a retester.

[TS011F__TZ3000_gvn91tmx.zip](https://github.com/KiwiHC16/Abeille/files/11044437/TS011F__TZ3000_gvn91tmx.zip)

Une fois decompressé au bon endroit, refaire une inclusion, tester on/off en notant l heure, et me filer les logs.

**Comment by Jorael57** [comment]
Je ne sais pas si ça peut t'aider : https://community.jeedom.com/t/amelioration-des-fonctions-sur-prise-zigbee-ts011f-manufacturer-tz3000-gvn91tmx/102938

**Comment by Jorael57** [comment]
[AbeilleLogs-230322.tar.gz](https://github.com/KiwiHC16/Abeille/files/11044681/AbeilleLogs-230322.tar.gz)

21h51 pour le clique ON et le clique OFF quelques secondes après
Avec celui la , les actions ON et OFF sont opérationnelles

**Comment by tcharp38** [comment]
Aucune trace apres [2023-03-22 21:44:11] <<< Arret du démon AbeilleParser
Peut etre que le mode debug n'est plus actif.

Quoi qu'il en soit tu dis qu'avec ce dernier modele, On & Off fonctionnent et le retour d'info aussi (mise à jour de Status).
C'est bien ca ? Si oui on avance.

**Comment by Jorael57** [comment]
Le status du on ou du Off oui il fonctionne.
Sinon il y a ça https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html
ça parle du fait que le firmware ne reporte plus automatiquement la conso et qu'il faut faire du "polling" je te laisse lire tu comprendras surement mieux que moi

**Comment by Jorael57** [comment]
Sinon effectivement j'ai l'impression d'avoir un soucis avec les logs il n'y a plus rien d'écrit dedans

**Comment by Jorael57** [comment]
Note le active power semble fonctionnait mais il est très long à ce mettre à jour

**Comment by Jorael57** [comment]
![image](https://user-images.githubusercontent.com/72082610/227047463-9c4191db-a417-4d0b-8b55-73dc58e0c587.png)

Finalement le RMS current a fini par changer aussi après plusieurs minutes avec une charge mais je trouve pas ça cohérent avec la puissance  (la puissance est bonne  vis à vis de ce que j'ai branché dessus)

**Comment by tcharp38** [comment]
Il y a des choses qui remontent automatiquement du coup.
Donc pas besoin de "polling" pour ce device. Des TS011 il y en a a la pelle carrée et pas toujours avec la meme fonctionalite. C'est la merde "Tuya".

Peux tu reactiver les logs, et me filer un package quand la prise est ON ?

**Comment by Jorael57** [comment]
Aurais tu du coup une (ou plusieurs) référence de prise zigbee avec monitoring  que tu recommanderais ?

**Comment by Jorael57** [comment]
Malgré le redémarrage de jeedom, je n'ai plus de log pour abeille :/

**Comment by Jorael57** [comment]
[AbeilleLogs-230322 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11045290/AbeilleLogs-230322.1.tar.gz)

**Comment by tcharp38** [comment]
Hello.
Le mode debug est de retour. Parfait.

Je vois bien le ON envoyé au device
Ce dernier renvoi bien un report.
Donc c'est un progres. La prise est donc commandée maintenant.

Mais j'ai l'impression que Jeedom n'est pas tenu au courant de ce reporting.


En fait je ne comprends pas ce que j 'observe.
Peux tu basculer sur la beta du jour (230322-BETA-3) et refaire la manip ? Avec les logs et l heure STP.
Note qu'apres update, tu n'as pas besoin de redemarrer ta box mais seulement le démon Abeille via sa page de config.

**Comment by Jorael57** [comment]
[AbeilleLogs-230402.tar.gz](https://github.com/KiwiHC16/Abeille/files/11133427/AbeilleLogs-230402.tar.gz)
 23h47 pour l'heure.

Par contre je ne sais pas à quoi c'est du, si c'est cette prise ou la dernière version d'abeille mais j'ai maintenant un décalage de 2 à 5s sur certaines de mes actions (sur d'autres équipements)  Par exemple pour allumer une lumière via un switch sans fil.

**Comment by Jorael57** [comment]
Ah oui autres points l'unité de consomation n'est pas bonne ( il m'indique plus de 500 kwh de conso alors qu'en reel je dois etre à plus de 5

**Comment by tcharp38** [comment]
Voila un modele pour test de l'unité.
Faire une 'mise à jour' via la page avancé
[TS011F__TZ3000_gvn91tmx.zip](https://github.com/KiwiHC16/Abeille/files/11153574/TS011F__TZ3000_gvn91tmx.zip)

**Comment by tcharp38** [comment]
Salut @Jorael57 
On fait quoi avec ce sujet ?

**Comment by tcharp38** [comment]
En l'absence de "testeur" je ferme le sujet.
A réouvrir si qqn a ce device
