### ISSUE TITLE
Mise a jour position volet roulant Legrand Netatmo (id = Shutterswitchwithneutral)

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2559]
Depuis le passage sur ma zigate v1, ma position de volet roulant ne se met plus à jours.

[Bureau][Volet Bureau]
Id Jeedom : 730
 F38F / 0004740000B9B820 

J'ai trouvé ce file ou kiwihc disait : 
> Il faut probablement faire un bind, setReport.
[https://community.jeedom.com/t/interrupteur-volet-roulant-celiane-with-netatmo-etat/51103/11]

J'ai donc fait ca : 
![image](https://user-images.githubusercontent.com/49479084/226372989-1e0df918-d693-4915-8a2e-aacf8dbcee57.png)

Le `Bind 0102-ToZigate` me renvoie une erreur : 
| 2023-03-20 15:31:37 | Abeille | ERREUR:     ERROR: Invalid addr length

Est ce le lien avec la remonté des positions qui ne se fait plus ?

Quand je fais un get position : `getcurrent_position_lift_percentage` , La mise à jour se fait bien.
Je pourrais lancer cette commande après une exécution de up ou down, mais si je le fais en physique sur l'interrupteur, j'aurai pas la mise à jour :/

[AbeilleLogs-230320(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11019379/AbeilleLogs-230320.1.tar.gz)

**Comment by tcharp38** [comment]
Hmm.. j'ai donc cassé un truc.
Je creuse

**Comment by tcharp38** [comment]
Peux tu faire un "mise à jour" via la page avancée.
Puis me filer les logs.

**Comment by tcharp38** [comment]
Bon j'ai compris les erreurs de ton cas de figure... tres rare vu que personne n'utilises les cmdes en "manuel".
Fixé dans la beta dispo demain.

Il te faut tout de meme refaire une mise à jour du modele et tester.

**Comment by Jake309** [comment]
Rah, j'avais pas vue tes 3 messages, juste la notif du premier :( . Excuses moi...

Je comprends pas pourquoi tu dis utiliser les commandes en manuel ? c'est pas ce que je fais si j'ai bien compris.
Du moins, si par manuel tu entends appuyé sur l'action get. 

J'ai fais la mise a jour de tout mes volet via avancé.
Je te mets les log, car la béta n'a pas résolue le pb
si ca peut t'aider à filter : F38F / 0004740000B9B820

[AbeilleLogs-230322.tar.gz](https://github.com/KiwiHC16/Abeille/files/11044584/AbeilleLogs-230322.tar.gz)


Et je te mets de nouveau les log, car j'ai retesté le bind et setreport.
Pas de message d'erreur, mais pas de mise à jour de position, je l'ai eu après en faisant le get position.

[AbeilleLogs-230322 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11044590/AbeilleLogs-230322.1.tar.gz)

**Comment by tcharp38** [comment]
> Je comprends pas pourquoi tu dis utiliser les commandes en manuel ? c'est pas ce que je fais si j'ai bien compris.
> Du moins, si par manuel tu entends appuyé sur l'action get.

Je fais allusion à utiliser la commande via la page "commandes" de l'équipement.
Je ne fais jamais et ne vois pas le besoin de le faire. Donc tu es un rare utilisateur de ce mode et tu es tombé sur une regression :) Merci pour le test.

Grace à tes logs j'ai trouvé une boulette dans le modele.
Essaie avec celui ci.
[Shutterswitchwithneutral.zip](https://github.com/KiwiHC16/Abeille/files/11050470/Shutterswitchwithneutral.zip)

Peux tu aussi tenter de me générer un discovery via l'assistant ?
Merci

**Comment by Jake309** [comment]
Je m'occupe de ca ce soir ;)

En fait, je ne m'en sers jamais de la commande via la page "commandes".
C'était pour t'expliquer le pb, j'ai du mal m'exprimer. Avant, l'état remontait en automatique, mais plus maintenant, par contre quand j'utilise la commande via la page, l'état se met bien a jour.

L'issue est fait pour retrouver la mise à jour automatique de l'état.

Les interrupteurs de volet, plusieurs secondes après un mouvement, tu entends un relais claqué (de mise au repos peut être) et dans le même temps, avant, la position dans jeedom était mise à jour.
Aujourd'hui je n'ai plus cette mise à jours automatique de l'état.

Je sais pas si tu m'as compris ^^

**Comment by tcharp38** [comment]
Bien compris et je crois que c'est en ligne avec le modèle corrigé. Tu me dira

**Comment by Jake309** [comment]
J'ai mis le nouveau json et redemarré jeedom.
Dans l'onglet avancé de chaque interrupteur de volet j'ai fait mise a jour sur la ligne configuration et sauvegardé.

J'ai fais plusieurs ouverture/fermeture, pas de changement à première vue.

J'ai ensuite ouvert l'asistant configuration : 
[discovery-Shutterswitchwithneutral_Legrand.zip](https://github.com/KiwiHC16/Abeille/files/11056372/discovery-Shutterswitchwithneutral_Legrand.zip)


Édit, j'ai tenté une réinitialisation sur un. Pas de mieux

**Comment by tcharp38** [comment]
Merci pour le discovery.
Pour le reste je ne peux rien dire sans logs.

J'ai besoin que tu fasses une "mise à jour" d'un seul volet, puis que tu me file les logs, avec l 'heure et le nom ou adresse du volet.

**Comment by Jake309** [comment]
F38F / 0004740000B9B820
[volet bureau]   id jeedom 730
6h43 mise à jour et 6h44 réinitialisation

[AbeilleLogs-230324.tar.gz](https://github.com/KiwiHC16/Abeille/files/11058789/AbeilleLogs-230324.tar.gz)

**Comment by tcharp38** [comment]
Tres etrange, le configureReporting est toujours en erreur, differente du coup precedent mais toujours la:

> [2023-03-24 06:44:08] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=F38F, DstAddrMode=02, DstAddr=0000
> [2023-03-24 06:44:08]   FCF=18/General/Serv->Cli, SQN=BA, cmd=07/Configure Reporting Response
> [2023-03-24 06:44:08]   Status=85/Invalid field, Attr=0008, Dir=00
>

**Comment by tcharp38** [comment]
Peux tu retenter avec ce modele
[Shutterswitchwithneutral.zip](https://github.com/KiwiHC16/Abeille/files/11060904/Shutterswitchwithneutral.zip)

donc mise à jour
+ noter l 'heure
+ me filer les logs

**Comment by Jake309** [comment]
F38F / 0004740000B9B820
[volet bureau] id jeedom 730
21:00:03 mise à jour

Ya pas mal de  ligne qui resemble au tiennent, mais j'ai trouvé un success
`[2023-03-24 21:00:06]   FCF=18/General/Serv->Cli, SQN=01, cmd=07/Configure Reporting Response`
`[2023-03-24 21:00:06]   Status=00/Success, Attr=0008, Dir=00`

[AbeilleLogs-230324 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11066217/AbeilleLogs-230324.1.tar.gz)

@tcharp38 t'es un bon ! ca fonctionne. Même quand je lance les montée/descente via l'interrupteur en physique.
J'ai aussi la position entrouvert.
C'est même instantané, donc mieux qu'au début (peut être la zigate v1 qui fait ca faut dire ^^)

**Comment by tcharp38** [comment]
Il me semblait que je n'avais pas pu tout cassé donc forcement des trucs pas propres qui trainaient encore.
Tant mieux.
On peut clore le sujet du coup ou il reste encore des points à voir sur ce switch ?

**Comment by Jake309** [comment]
Yep, on peut clore^

J'ai juste une différence, c'est que des que le volet commence a descendre, il s'affiche en fermé direct.
Si je le stop, il s'affiche direct en état intermédiaire. Donc ca me dérange pas
Pareil pour la remonté.

Avant, il me l'affichait qu'une fois les mouvement terminée (et un temps d'attente).
C'est pas choquant en soit, j'ai pas de scénario qui déclenche en fonction de l'état du volet.
Mais ca peut poser problème un jour à d'autre personne.
Je sais pas si ca vaut la peine de passer du temps dessus si ca se règle pas en 3 clics.

Merci en totu cas tcharp

**Comment by tcharp38** [comment]
Ha pas sur qu'Abeille puisse faire quoi que ce soit sur ce cas mais si tu me files les logs pour ce cas, je peux regarder. Je pense que le volet lui meme renvoi 0 puis la position finale. A verifier

**Comment by Jake309** [comment]
6h30 environ, on envoie un ordre à plusieurs volets dont
Volet Cuisine : 763A / 0004740000B9B81D
On ne voit pas le changement 100% > 0 > 50, enfin dans mon historique, je vois que 100 > 50

[AbeilleLogs-230330.tar.gz](https://github.com/KiwiHC16/Abeille/files/11109729/AbeilleLogs-230330.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois qu'un retour 0 & 50% de ce device.
Manque de pot je ne sais pas quel etait l'ordre les logs etant legerement trop recents.

[2023-03-30 06:33:26][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/763A/01
[2023-03-30 06:33:26][DEBUG] :   'current_position_lift_percentage' (0102-01-0008) => 0 %

[2023-03-30 06:33:31][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/763A/01
[2023-03-30 06:33:31][DEBUG] :   'current_position_lift_percentage' (0102-01-0008) => 50 %

Donc pour moi rien d'incoherent la.

Peux tu reefaire juste l'action sur 1 volet et file moi les infos (logs + heure + pb vu) en ligne avec le pb que tu veux montrer ?

**Comment by Jake309** [comment]
Alors, le 100% tu le vois pas car il est à 20h 21h hier.
En gros, 100% volet fermé, 50% entre-ouvert, 0% ouvert.
Donc ce matin, on est parti de fermé et on l'a arrêté, donc il aurait du faire 100% > 50%, mais comme tu le dis, il a envoie 0 le temps du mouvement. 
On a le même effet à l'inverse, il est ouvert =0%, je le ferme et l'arrête en route, il envoie 100% puis 50%

Après, je suis d'accord que ce n'est pas torp impactant. Mais comme je n'avais pas ce mode de fonctionnement auparavant (avec ma zigate v2 et avant la régression), je me suis interpelé

Je te film l'écran de pc et le volet en faisant l'action et te donne les log. Je suis chez moi dans l'aprem, je le ferai.

**Comment by tcharp38** [comment]
Donc reproduis juste 1 cas "qui merde"
et file moi toutes les billes et on avise la suite.

**Comment by Jake309** [comment]
[Volet bureau]   F38F / 0004740000B9B820
j'appuie sur `Down` : passe de `100%` à `0%` en descendant.
je `Stop` la descente passe de `0%` à `50%`
La théorie voudrait qu'il fasse `100%` > `50%`. il n'est jamais fermé, donc il ne devrait pas afficher `0%`

https://user-images.githubusercontent.com/49479084/228870275-4a47b377-d351-4c51-a1ef-178534b0e3ce.mp4
(galère à up un video avec un max à 10mo)

[AbeilleLogs-230330.tar.gz](https://github.com/KiwiHC16/Abeille/files/11112657/AbeilleLogs-230330.tar.gz)

A la fin de fait un up pour le remonter.
ps: oui, j'ai toujours pas fait les finitions du chantier fenetre ^^

**Comment by tcharp38** [comment]
Je vois tous ces evenements.
Le mieux pour les suivre est de regarder le log Jeedom "events"

[2023-03-30 16:22:51][INFO] : Evènement sur la commande [Bureau][Volet Bureau][current_position_lift_percentage] valeur : 100%
[2023-03-30 16:23:00][INFO] : Evènement sur la commande [Bureau][Volet Bureau][current_position_lift_percentage] valeur : 50%
[2023-03-30 16:23:10][INFO] : Evènement sur la commande [Bureau][Volet Bureau][current_position_lift_percentage] valeur : 0%

Malheureusement je ne vois pas en quoi Abeille fait faux. C'est bel et bien le device qui envoie ces infos mais la je suis d'accord avec un arret à 50%.. aucune raison que ca passe à 0 10sec + tard.

On n'a pas regardé la piste du FW. Peut etre y a t il une maj "Shutterswitchwithneutral" ?

**Comment by tcharp38** [comment]
Je pense qu'il y a un pb de FW
Regarde ce sujet: https://github.com/Koenkk/zigbee2mqtt/issues/4819
Ca ressemble bien à ca

**Comment by Jake309** [comment]
Arf ! en effet.
Il est vrai que j'ai connecté les inter à la passerelle legrand.....
Donc j'ai eu des mises à jour de firmware.
Finalement c'était pas l'idéal de tester via la passerelle avant de passer sur le zigate v1.
On va attendre une nouvelle version et on fera la mise à jour :/
Je cloture l'issue de ce fait @tcharp38 , tu as été meilleur que moi pour trouver le pb.
