### ISSUE TITLE
Set Nom des volets Profalux

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#256]
See #114

**Comment by KiwiHC16** [comment]
C'est bon je sais faire. Je viens de la faire sur un interrupteur Xiaomi. Reste à le mettre dans le code.

**Comment by KiwiHC16** [comment]
C'est dans le code.
https://github.com/KiwiHC16/Abeille/blob/master/Documentation/062_Parametres_des_equipements.adoc

**Comment by KiwiHC16** [comment]
Dis moi si cela fonctionne sur tes volets.
Attention: si on change la valeur de ce champ qui est normalement "Volet" alors la creation automatique ne marchera plus. Il faut qu'on regarde une fois que tu confirme que cela fonctionne.
Je regardes aussi ton deuxieme fichier de Sniff.

**Comment by dams74** [comment]
J'essaie de tester ça aussi vite que possible.
Il n'y a pas d'inquiétude à avoir au sujet de la création auto car lors de la manipulation de reset avant l'inclusion ça remet le nom volet.

**Comment by dams74** [comment]
J'ai pas de get location dans ma ruche
J'ai pourtant mis à jour depuis master github
version du plugin `0de6e6931541e504f1faaa7f947b480d0cd61b23`

**Comment by KiwiHC16** [comment]
Supprimes la ruche et redémarre le démon pour recréer la ruche.

**Comment by zoozbiro** [comment]
hello messieurs,

J'ai un peu de temps aujourd'hui je vais essayer de vous aider un peu :) 



alors voici mes logs : 

abeilleParser suite à un getLocation : 

```
AbeilleParser 2018-05-25 08:57:15[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 8a
AbeilleParser 2018-05-25 08:57:15[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 8a; Src Addr : 27be; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0005; Data byte list : ->volet<-
```

abeilleParser suite à un setLocation : 

```
AbeilleParser 2018-05-25 09:01:00[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9b
AbeilleParser 2018-05-25 09:01:00[DEBUG]type: 8701: (APS Data Confirm Fail)(Decoded but Not Processed); Status : d3; Source Endpoint : 01; Destination Endpoint : 01; Destination Mode : 02; Destination Address : f524; SQN: : d0
AbeilleParser 2018-05-25 09:01:00[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9c
AbeilleParser 2018-05-25 09:01:00[DEBUG]type: 8701: (APS Data Confirm Fail)(Decoded but Not Processed); Status : d3; Source Endpoint : 01; Destination Endpoint : 01; Destination Mode : 02; Destination Address : 2006; SQN: : d0
AbeilleParser 2018-05-25 09:01:00[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9d
AbeilleParser 2018-05-25 09:01:00[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 9d; Src Addr : 5edc; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-
```


abeilleParser suite à un getLocation : 
```
AbeilleParser 2018-05-25 09:01:50[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: a0
AbeilleParser 2018-05-25 09:01:50[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-05-25 09:01:50[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: a0; Src Addr : 27be; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 000A; Data byte list : ->PF Cuisine<-
```

Sur mon installation ça semble fonctionner.

**Comment by KiwiHC16** [comment]
Trop fort !

**Comment by KiwiHC16** [comment]
Comme ca fonctionne je clos ce sujet.
@dams74, si tu ne parviens pas a le faire fonctionner ouvre une "issue" spécifique. J'essaye de garder le nombre d'issue a un nombre raisonnable et le plus specifique possible.
