### ISSUE TITLE
Legefirm répéteur de Signal Amplificateur USB (id = TS0207, _TZ3000_nkkl7uzv)

### ISSUE THREAD

**Issue by chrisb13790** [KiwiHC16/Abeille#2560]
![usb repeteur](https://user-images.githubusercontent.com/91745100/227223315-6b55f498-f7fa-4758-8ead-85ec82426403.jpg)
salut besoin d aide pour intergrer
dis moi ce dont tu as besoin

**Comment by tcharp38** [comment]
Salut
Je suppose qu'il n'est pas reconnu alors.
J'ai besoin du discovery

**Comment by chrisb13790** [comment]
comment avoir le discovery  ?

**Comment by tcharp38** [comment]
Ha toi t'as pas jeté un oeil à la doc :)
https://tcharp38.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by chrisb13790** [comment]
non on l vait deja fait pour un mhcozy relais 4c mais je me souvenais pas que sa s appellait discovery
ceci est automatiquement completer ou c est a moi de le remplir 
Identifiant Zigbee (modelId, manufId)

**Comment by chrisb13790** [comment]
[discovery-TS0207__TZ3000_nkkl7uzv.zip](https://github.com/KiwiHC16/Abeille/files/11066079/discovery-TS0207__TZ3000_nkkl7uzv.zip)
j ai trouvé ca 
https://zigbee.blakadder.com/Tuya_TS0207.html

**Comment by tcharp38** [comment]
Tiens, ecrase le modele avec celui ci
core/config/devices/TS0207__TZ3000_m0vaazab
[TS0207__TZ3000_m0vaazab.zip](https://github.com/KiwiHC16/Abeille/files/11069699/TS0207__TZ3000_m0vaazab.zip)

puis redemarrer Abeille
refaire inclusion
La bonne image sera dans la prochaine beta de demain

**Comment by tcharp38** [comment]
Non en fait l'image n'est pas bonne. 
J'ai recadré et converti en PNG mais il faut rendre transparent le fond.
Je te laisse faire.
Voila le PNG
![node_Tuya-Repeater-2](https://user-images.githubusercontent.com/35221038/227734226-9e486a4c-3dae-40da-93e6-8d37acd09715.png)

**Comment by chrisb13790** [comment]
non reconnu , est ce a cause de la fin du nom du fichier ?

**Comment by tcharp38** [comment]
Comment ca ?
Donne moi les logs STP

**Comment by chrisb13790** [comment]
[AbeilleLogs-230325.tar.gz](https://github.com/KiwiHC16/Abeille/files/11069889/AbeilleLogs-230325.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois pas le "device announce" dans les logs.
As tu bien redémarré Abeille ?

**Comment by chrisb13790** [comment]
effectivement je n avais pas redemarré, j ai refait une inclu
![Sans titre 2](https://user-images.githubusercontent.com/91745100/227742743-5d0f3302-0b5a-4585-ada5-19a75abeae95.jpg)
mais la fin du nom n est pas la meme que le json

**Comment by tcharp38** [comment]
Certains modeles supportent plusieurs identifiants. C'est le cas du repeteur.

Donc toujours pas reconnu mais pas de logs ?

**Comment by chrisb13790** [comment]
[AbeilleLogs-230325(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11070296/AbeilleLogs-230325.1.tar.gz)

**Comment by tcharp38** [comment]
Le seul device announce que je vois est celui d'un Livolo.
Je pense que tu dois debrancher le repeteur et le rebrancher pour qu'il s'annonce à nouveau.

**Comment by chrisb13790** [comment]
<html><body>


2023-03-26 11:06:21 | Abeille | Nouvel  équipement détecté mais non supporté. Création en cours avec la config  par défaut (defaultUnknown). Rafraîchissez votre dashboard dans qq  secondes.

[AbeilleLogs-230326.tar.gz](https://github.com/KiwiHC16/Abeille/files/11071145/AbeilleLogs-230326.tar.gz)

**Comment by tcharp38** [comment]
> [2023-03-26 11:00:43]   findModel(), manufId='_TZ3000_nkkl7uzv', modelId='TS0207', loc=''
> [2023-03-26 11:00:43]   EQ is UNsupported. 'defaultUnknown' config will be used

Aucun doute le modele n'est pas à sa place

Je vois un seul identifiant alternatif

> [2023-03-25 19:32:06][DEBUG] : getDevicesList(): Alternate ID 'LTW004' for 'LTW001'
> [2023-03-25 19:32:06][DEBUG] : getDevicesList(): Alternate ID 'TS0207__TZ3000_gszjt2xx' for 'TS0207__TZ3000_m0vaazab'
> [2023-03-25 19:32:06][DEBUG] : getDevicesList(): Alternate ID 'TH-EM_HEIMAN' for 'HT-EF-3.0_HEIMAN'

Alors que si je teste chez moi

> [2023-03-26 12:38:05][DEBUG] : getDevicesList(): Alternate ID 'TS0207__TZ3000_ufttklsz' for 'TS0207__TZ3000_m0vaazab'
> [2023-03-26 12:38:05][DEBUG] : getDevicesList(): Alternate ID 'TS0207__TZ3000_5k5vh43t' for 'TS0207__TZ3000_m0vaazab'
> [2023-03-26 12:38:05][DEBUG] : getDevicesList(): Alternate ID 'TS0207__TZ3000_gszjt2xx' for 'TS0207__TZ3000_m0vaazab'
> [2023-03-26 12:38:05][DEBUG] : getDevicesList(): Alternate ID 'TS0207__TZ3000_nkkl7uzv' for 'TS0207__TZ3000_m0vaazab'

La beta du jour devrait resoudre ça: 230325-BETA-2

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Des news ?

**Comment by chrisb13790** [comment]
Salut il a l air intégré mais j ai quasi plus aucun inter livolo qui fonctionne j ai jeté un oeil y a des commande on off et sans doute autre chose qui on disparu

**Comment by tcharp38** [comment]
Ha zut.
Tu me donnes un package de logs ?

**Comment by chrisb13790** [comment]
[AbeilleLogs-230408.tar.gz](https://github.com/KiwiHC16/Abeille/files/11182916/AbeilleLogs-230408.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois rien qui saute aux yeux.
Il y a eu un ON à 07:54 mais il semble s etre bien passé non ?

[2023-04-08 07:54:56] -- execute([maison][couloir][On 1], type=action, options={"user_login":"admin","user_id":"1"})

Peux tu en choisir un qui ne fonctionne pas, et faire une action dessus, noter l heure et filer les logs ?
Ha en fait tu me dis que certains ont des commandes manquantes ? Lequel ?

**Comment by chrisb13790** [comment]
Ok ça marche je te fais sans quand je peux

**Comment by tcharp38** [comment]
Attends. je viens de trouver un pb qui peut expliquer.

**Comment by tcharp38** [comment]
Un modele corrigé.
[TI0001.zip](https://github.com/KiwiHC16/Abeille/files/11183013/TI0001.zip)

Faire "mise à jour" via la page avancé de l'equipement qui merde.
Désolé j'ai trouvé une faille que je dois arriver à couvrir par + de tests mais tu me confirmera que c'est bien ca.

**Comment by chrisb13790** [comment]
Je balance le modèle corrigé ou j attends ?

**Comment by tcharp38** [comment]
Non tu peux le garder. Il est dans la beta et j'ai rien changé de +.
Par contre j'ai amélioré mes tests dans la foulée.

**Comment by chrisb13790** [comment]
j ai remplacer le TI0001 dans la base de données suivie par la maj de l equipement rien pas de changement , fait un appairage la j ai des commande en plus mais pas off 2 , je teste les commandes on1=off 2,on2=ok, off1=ok

**Comment by tcharp38** [comment]
Bon on est en train de pourrir le mauvais sujet.
Si le repeater est ok.. on clos.

Reouvrir le 2476 et j'ai besoin du package de logs STP.

**Comment by tcharp38** [comment]
@chrisb13790 
Ce repeteur de signal est ok ?

**Comment by chrisb13790** [comment]
Salut je te dirais que ça devrait être bon depuis mon PB de rflink tout est
éteint est ranger dans un placard

**Comment by tcharp38** [comment]
Ha oui tu jettes l'eponge sur cette solution zigbee alors.
Je comprends.
Je ne vais plus t embetter avec mes questions et je vais fermer tes sujets ouverts du coup.
J'espere que tu trouvera qqch de + stable.

**Comment by chrisb13790** [comment]
salut, j ai redemarré le pi4 avec un os tout neuf, , est il possible de recuperer abeille seulement pour le mettre sur un jeedom tout neuf aussi ?

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Ha je soupconne que tu veux recuperer ta base données d'Abeille et pas repartir de 0.
Du coup la seule solution que je vois est de restaurer un backup à version equivalente.
C'est bien ça ?

**Comment by chrisb13790** [comment]
Oui mais si je peux plugin par plugin

**Comment by tcharp38** [comment]
Malheureusement je ne vois pas comment faire.
Dans les DB il y a des tas d'infos dont certaines sont mises par Abeille et d 'autres par Jeedom.
Et tout ça doit être en ligne avec le code correspondant car le format interne peut avoir évolué.

**Comment by chrisb13790** [comment]
Ok
Merci vais balancer la dernière sauvegarde que j avais

**Comment by tcharp38** [comment]
Bonne chance

**Comment by chrisb13790** [comment]
Avant de faire la sauvegarde j avais viré rflink donc j espère que ça va le
faire
🤞
