### ISSUE TITLE
Loratap roller shutter touch switch SC400ZB-EU v2 (id = TS130F,_TZ3000_dbpmpco1)

### ISSUE THREAD

**Issue by alexh-fr** [KiwiHC16/Abeille#2561]
Bonjour,

Pouvez-vous intégrer le module TS130F__TZ3000_dbpmpco1 s'il vous plait
J'ai testé le .zip du #2552 en modifiant les références. 
Le up/stop/down fonctionne parfaitement, mais je n'ai que ces 3 commandes, et aucunes autres infos (à part la base IEEE-Addr, Link quality, ...)

Ci-après, une photo du module, et le discovery.json
![image](https://user-images.githubusercontent.com/78020272/227347903-860bb762-f3ff-4719-935d-7c768da45f78.png)
[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/11055770/discovery.json.txt)

Merci beaucoup pour votre aide.
Je reste à votre disposition.

Bonne journée.

**Comment by tcharp38** [comment]
Bonjour

C'est du Loratap aussi ?
Une ref fabricant ?

**Comment by alexh-fr** [comment]
Bonjour,

Oui Loratap également: "Tuya Smart Life ZigBee 3.0, 2nd generation".
Acheté ici: https://fr.aliexpress.com/item/4001190275372.html
Référence fabricant : SC400ZB-EU

Merci pour votre aide.

**Comment by tcharp38** [comment]
Salut @ChikooDanko 
Je fais une nouvelle stable ce WE normalement. Donc on reprendra ca apres sinon tu es obligé de basculer sur la beta pour faire des tests.
A suivre

**Comment by alexh-fr** [comment]
Merci @tcharp38 pour ton aide.

Est-ce qu'il y a la commande info pour obtenir la position du volet dans la beta ?
En attendant la version stable, comment et/ou où puis-je récupérer juste les infos/fichier pour utiliser correctement ce module Zigbee ?

Bonne journée,

**Comment by tcharp38** [comment]
Hello.
Désolé vraiment pas le temps à faire du support sur une vieille stable.
Néanmoins je viens d'en créer une nouvelle à l 'instant qui sera dispo lundi. Elle est alignée sur la derniere beta.

Donc on repart de la des que tu as basculé dessus.

**Comment by tcharp38** [comment]
Une nouvelle stable est dispo.
Je te laisse basculer dessus et on refait le point.

**Comment by tcharp38** [comment]
Une nouvelle stable est dispo.
Je te laisse basculer dessus et on refait le point.

**Comment by alexh-fr** [comment]
@tcharp38 Merci pour ta réactivité.

Retour sur la MAJ:
- Réinitialisation de l'équipement : OK / R.A.S. 
- Logo en concordance avec l'équipement
- Création commande : OK.
- L'info "Level" se met à jour correctement dès que l'interrupteur passe en position "STOP". Que ce soit fait manuellement physiquement sur le bouton ou via la commande Jeedom mais également lorsque module passe automatiquement en "STOP" lorsqu'il ne détecte plus de mouvement du volet. 
- Par contre, le pourcentage du "Level" est NOK. J'ai fait plusieurs tests à la suite pour te donner un ordre d'idée : 
1. Stade initial, volet fermé : Level à 22%
2. Ouverture complète : 56%
3. Fermeture complète : 20%
4. Réouverture complète : 54%
5. Fermeture complète : 13%
6. Réouverture complète : 45%
7. Fermeture complète : 11%
8. Réouverture complète : 45%
7. Fermeture complète : 11%
8. Réouverture complète : 44%
9. Fermeture complète : 11%
10. Réouverture complète : 44%
11. Fermeture complète : 11%
12. Réouverture complète : 45%
13. Fermeture complète : 12%
14. Ouverture de -+ moitié : 27%
15. Fermeture complète : 0%
16. Ouverture complète : 91%
17. Fermeture complète : 61%
18. Ouverture complète : 96%
19. Fermeture complète : 59%

Je ne sais pas si cela va te servir, mais je t'ai joint le log "Abeille" (j'ai préféré anonymiser les noms provenant de mes autres capteurs Zigbee) avec le timestamp de mes actions.
[log_Test_TS130F__TZ3000_dbpmpco1.txt]https://github.com/KiwiHC16/Abeille/files/11082716/log_Test_TS130F__TZ3000_dbpmpco1.txt)

A dispo au besoin

**Comment by tcharp38** [comment]
Il manque la calibration.
C'est ce qui permet de dire "tout fermé = 0%", "tout ouvert = 100%".
Du coup le level doit etre en ligne avec ca.

Je te laisse essayer avec ce modele. J'ai ajouté la possibilité de configurer le "calibration time".
Tu dois le mettre à la valeur max pour ouvrir/fermer ton volet
[TS130F__TZ3000_dbpmpco1.zip](https://github.com/KiwiHC16/Abeille/files/11087914/TS130F__TZ3000_dbpmpco1.zip)
A decompresser sur l'aure
puis via la page "avance" faire "mise à jour" et tester.

Cote logs on risque de pas aller vite. je ne peux rien faire sans eux. Il me faut le package generé par la page "mainteance"/"telecharger tout".

**Comment by alexh-fr** [comment]
Je te confirme que cela fonctionne parfaitement après avoir réglé le temps d'ouverture/fermeture.
J'ai juste un léger "décalage" car mes volets s'ouvrent + vite qu'ils ne se ferment, mais qui n'est pas liée au plugin/zigbee/module.

As-tu besoin des logs ?

Merci pour ton aide

**Comment by tcharp38** [comment]
Salut
Du coup il reste qqch sur ce sujet ou on peut le fermer ?

**Comment by alexh-fr** [comment]
Salut @tcharp38 

Pour moi, tout est bon, le sujet peut être clos.
Si tu souhaites pour mettre au propre, comme mes autres équipements sur Abeille ont leurs images avec un fond transparent, je t'ai inséré ci-après le capteur avec le même fond.

![227347903-860bb762-f3ff-4719-935d-7c768da45f78](https://user-images.githubusercontent.com/78020272/228525793-a075718c-abfa-40c3-a459-d0ffc867fc09.png)

Merci pour ton aide et ta réactivité !

**Comment by tcharp38** [comment]
J'ai pris ton image pour la prochaine beta.
Merci

je clos le sujet.
A reouvrir si pbs
