### ISSUE TITLE
Support Bouton Moes Tuya IP55 ZN358218 (id = TS004F, _TZ3000_kjfzuycl)

### ISSUE THREAD

**Issue by fab263** [KiwiHC16/Abeille#2562]
Bonjour,
A la recherche d'un bouton Zigbee étanche (IP55) pour l'extérieur (pour un futur bouton de sonnette), à ma connaissance il n'en existe pas aujourd'hui. Serait-il possible de prendre en charge le bouton Tuya ZigBee 3.0 IP55 ZN358218 ?

SKU: ZT-SY-SR

https://fr.aliexpress.com/item/1005004774449897.html?spm=a2g0o.order_list.order_list_main.5.4b045e5bNeZyDI&gatewayAdapt=glo2fra

https://moeshouse.com/products/ip55-waterproof-smart-zigbee-scene-switch-wireless-remote-dimmer?variant=39880100085841

Par avance merci

**Comment by tcharp38** [comment]
Salut
L'as tu déja acheté ?
Si oui tu dois suivre cette procedure: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

Il me faudra aussi
- la ref vendeur si existe
- une image PNG sans arriere plan a mettre en icone

**Comment by fab263** [comment]
Non pas encore commandé. 
Mais j'hésite avec la solution du bouton aqara en appliquant une couche de protection.

https://www.reddit.com/r/Aqara/comments/jky988/flex_seal_sprayed_to_make_a_weatherproof_doorbell/

**Comment by tcharp38** [comment]
Ha ok.
Dans tous les cas on ne peut ajouter le support sans que qqn bosse dessus.
Et je ne peux donner de conseils n'ayant pas ce type d'équipement.

**Comment by fab263** [comment]
Bon je l'ai commandé. Je devrai le recevoir d'ici 10 jours, je te tiens au courant.

**Comment by fab263** [comment]
En attendant voici le png du bouton et sa référence : ZT-SY-SR

![Bouton](https://user-images.githubusercontent.com/46577175/227717126-eb306911-bf2e-4f6f-bb55-bf7cb9f510e8.png)

**Comment by fab263** [comment]
Bonjour, 
Je viens de revoir l'équipement. Voici le fichier zip de découverte. 
A ta dispo si besoin d'autres infos.

[discovery-TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11151109/discovery-TS004F__TZ3000_kjfzuycl.zip)

**Comment by tcharp38** [comment]
Salut

Voila un modele preliminaire pour core/config/devices
[TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11158063/TS004F__TZ3000_kjfzuycl.zip)

puis redemarrer Abeille
refaire inclusion

Penser a activer le mode debug pour les logs.

**Comment by fab263** [comment]
> Salut
> 
> Voila un modele preliminaire pour core/config/devices [TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11158063/TS004F__TZ3000_kjfzuycl.zip)
> 
> puis redemarrer Abeille refaire inclusion
> 
> Pe

Voici les logs suite à la nouvelle inclusion de l'équipement.
[AbeilleLogs.zip](https://github.com/KiwiHC16/Abeille/files/11158255/AbeilleLogs.zip)

**Comment by tcharp38** [comment]
Il semble bien reconnu non ?
Tu as testé ?

**Comment by fab263** [comment]
Oui j'ai des infos remontent bien (voir capture). Mais je ne vois rien concernant le simple ou double click  du bouton par exemple. 

![image](https://user-images.githubusercontent.com/46577175/230285813-65142eaa-8cde-4ff9-9c4c-2ffbd6eca207.png)

**Comment by tcharp38** [comment]
J'ai besoin que tu fasses un clic, note l'heure, et me file le package de logs (page maitenance + telecharger tout).

**Comment by fab263** [comment]
Hello,

Voici les logs demandées 👍 

20:37:10 : appuie long
20:38:00 : 1 appuie court
20:39:00 : 2 appuies court

[AbeilleLogs-230406.tar.gz](https://github.com/KiwiHC16/Abeille/files/11173573/AbeilleLogs-230406.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois que de 2 retours differents.
Voila le nouveau modele.
[TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11174095/TS004F__TZ3000_kjfzuycl.zip)

Et une nouvelle commande
[inf_zbCmdC-0008-Step.zip](https://github.com/KiwiHC16/Abeille/files/11174097/inf_zbCmdC-0008-Step.zip)

**Comment by fab263** [comment]
J'ai fait la mise à jour. Mais l'appuie sur le bouton ne provoque aucun changement. [Step] et [Stop] sont toujours à 1...

![image](https://user-images.githubusercontent.com/46577175/230660455-f7b2c9a6-e975-4b85-8a18-d4eca691d0ce.png)

**Comment by fab263** [comment]
Hello, 
J'ai refait 3 tests de simple clic à 10:16:30s, 10:16:40s, 10:16:50s

Je constate à chaque appuie les memes messages d'erreur dans AbeilleCmd.log  le message "Corresponding cmd not found" et dans Abeille.log "Unknown Jeedom command logicId='01-click'" . Ci joint les logs  :

[AbeilleLogs-230408.tar.gz](https://github.com/KiwiHC16/Abeille/files/11182821/AbeilleLogs-230408.tar.gz)

Dans AbeilleParser j'ai vu des libellés différents en fonction du type de clic long, double ou simple (Click=long, Click=double, Click=single) :

clic long à 10:41:15, double clic à 10:41:31,  simple clic à 10:41:41 

[AbeilleLogs-230408 V2.tar.gz](https://github.com/KiwiHC16/Abeille/files/11182850/AbeilleLogs-230408.V2.tar.gz)

**Comment by tcharp38** [comment]
Bon je ne pige pas pourquoi les retours d infos sont differents cette fois.

Voila le nouveau modele
[TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11182893/TS004F__TZ3000_kjfzuycl.zip)

Et une nouvelle commande pour core/config/commands
[inf_click.zip](https://github.com/KiwiHC16/Abeille/files/11182892/inf_click.zip)

Si tu pouvais basculer sur la beta demain ca serait cool.
Tu aura toutes ces mises à jour et pourra me faire un retour sur une eventuelle regression.

**Comment by fab263** [comment]
Hello, 

Je viens de tester les différents clics du bouton (1 court, 2 courts, long) et les différents états remontent bien. J'ai remarqué une chose :  le simple clic et double clic remontent si on relache le bouton rapidement dans la demi seconde environ. Le clic long remonte si c'est maintenu plus de 3s. Sinon l'état [Click] ne changera pas. Peut être qu'une future mise à jour du firmware du bouton sera faite pour corriger ce petit désagrément pour des clics entre 0.5 et 3s ?

Dernière chose importante : pour que les clic remontent bien, le bouton doit être en mode Remote et non en mode Scene (les 1ere log que je t'avais envoyées devaient être en mode Scene). Comme cela est expliqué dans la documentation pour passer d'un mode à l'autre il faut faire 3 clic courts de suite.

**Comment by tcharp38** [comment]
Jusque la je n'ai pas vu d info differente remonter pour un click "long" donc pas sur qu il soit supporté.
Il faut pour ca surveiller le log parser, et voir si il y a une difference entre le retour d info click simple/double ou long.

Pour le passage en mode "remote".. la il faut trouver comme on le fait basculer. Tuya c'est tout sauf standard donc ca revient à faire du reverse engineering ou fouiller le net pour voir comment les autres se debrouillent avec ca. J'essaierai de voir.

**Comment by fab263** [comment]
Hello, je viens de passer sur la dernière beta. RAS ça semble bien fonctionner.  Les différents click remontent bien y compris pour le type de click long :

![image](https://user-images.githubusercontent.com/46577175/231392784-3af2265a-1117-4860-9e67-6690253fdc4e.png)


Pour le passage en mode remote/Scene en appuyant 3clic court ça a l'air de fonctionner d'après ce que j'ai vu dans la log parser.

**Comment by tcharp38** [comment]
Reste donc à trouver comment "forcer" ce mode 'remote' par defaut.

**Comment by tcharp38** [comment]
Tiens, ecrase le modele avec celui ci
[TS004F__TZ3000_kjfzuycl.zip](https://github.com/KiwiHC16/Abeille/files/11213711/TS004F__TZ3000_kjfzuycl.zip)

et refais une inclusion.


Pour memo:

>         configure: async (device, coordinatorEndpoint, logger) => {
>             const endpoint = device.getEndpoint(1);
>             await endpoint.read('genBasic', [0x0004, 0x000, 0x0001, 0x0005, 0x0007, 0xfffe]);
>             await endpoint.write('genOnOff', {'tuyaOperationMode': 1});
>             await endpoint.read('genOnOff', ['tuyaOperationMode']);
>             try {
>                 await endpoint.read(0xE001, [0xD011]);
>             } catch (err) {/* do nothing */}
>             await endpoint.read('genPowerCfg', ['batteryVoltage', 'batteryPercentageRemaining']);
>             await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
>             await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
>             await reporting.batteryPercentageRemaining(endpoint);
>         },
>

**Comment by fab263** [comment]
Hello, j'ai refait une nouvelle inclusion avec le nouveau modele puis quelques tests. Voici la log.
[AbeilleLogs-230416.tar.gz](https://github.com/KiwiHC16/Abeille/files/11241604/AbeilleLogs-230416.tar.gz)

**Comment by tcharp38** [comment]
Salut
Est ce qu il est toujours necessaire de changer le mode en manuel (3clic court ) ?

**Comment by fab263** [comment]
Après l'inclusion oui sinon les clic ne remontent pas.
Ensuite si jamais je refais 3x je rebascule de nouveau en mode Scene.

**Comment by tcharp38** [comment]
Je vois en fait que l'inclusion s'est mal passée.
Etrange cas.
Peux tu refaire la meme chose avec ce code ?
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11241742/AbeilleParser.class.php.zip)

A decompresser dans Abeille/core/class
puis redemarre Abeille
refaire inclusion
filer les logs

**Comment by fab263** [comment]
[AbeilleLogs-230416 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11241813/AbeilleLogs-230416.1.tar.gz)

J'ai eu un message d'erreur à l'inclusion (ERREUR: Cmd 'writeAttribute': Paramètre 'ep' vide !)

Sinon meme symptome qu'avant (3x clic pour basculer puis c'est OK)

**Comment by tcharp38** [comment]
Etrange que je trouve ces bugs mais bon.. c'est l'interet d'avoir des gens qui bossent sur une beta.
Merci à toi.

A decompresser dans Abeille/core/class
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11241920/AbeilleTools.class.php.zip)

puis redemarrer Abeille
et faire une mise à jour de ton equipement (page avancé)
et me filer les logs

**Comment by tcharp38** [comment]
Pour info j'ai poussé une beta avec tous les correctifs du moment. Elle sera dispo demain.

**Comment by fab263** [comment]
OK. Voici la dernière log suite à la maj AbeilleTools
[AbeilleLogs-230416.tar.gz](https://github.com/KiwiHC16/Abeille/files/11242126/AbeilleLogs-230416.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois plus l'erreur.
Est ce que le bon mode est actif ?

**Comment by tcharp38** [comment]
Salut @fab263 
Toujours interessé par ce sujet ?

**Comment by tcharp38** [comment]
Plus de vie ici.
Je ferme le sujet.
A réouvrir si qqn est interessé pour bosser dessus.
