### ISSUE TITLE
Probleme inclusion ampoule ikea Tradfri 470lm E27 

### ISSUE THREAD

**Issue by mohatem** [KiwiHC16/Abeille#2564]
Bonjour j'ai réussi a inclure l'ampoule mais elle est marquée comme inconnu dans abeille, je n'ai aucune commande, par contre les ampoule tradfri 250lm e27 ca fonctionne nickel 

Merci pour l'aide 

[discovery-TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.json.zip](https://github.com/KiwiHC16/Abeille/files/11072859/discovery-TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.json.zip)

**Comment by tcharp38** [comment]
Salut @mohatem 
Je vais regarder ça mais avant tout peux tu me donner la ref de ce modele ?

Peux tu aussi faire le test suivant sur la 250lm
- setLevel au max
- et me filer les logs (maintenance/telecharger tout)

Attention !! Si pas deja le cas mets toi en mode debug via la page de config + redemarrer Abeille

Merci

**Comment by tcharp38** [comment]
Voila un modele pour test
[TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/11089603/TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.zip)

il faut aussi ajouter cette commande à "core/config/commands"
[act_setLevel-Light.zip](https://github.com/KiwiHC16/Abeille/files/11089624/act_setLevel-Light.zip)

Puis redemarrer Abeille
refaire inclusion
et tester

**Comment by mohatem** [comment]
> Salut @mohatem Je vais regarder ça mais avant tout peux tu me donner la ref de ce modele ?
> 
> Peux tu aussi faire le test suivant sur la 250lm
> 
>     * setLevel au max
> 
>     * et me filer les logs (maintenance/telecharger tout)
> 
> 
> Attention !! Si pas deja le cas mets toi en mode debug via la page de config + redemarrer Abeille
> 
> Merci

**Comment by mohatem** [comment]
Merci pour ton retour 

le modele est le LED2102G3 

Voici le log pour le setLevel au max 
[AbeilleLogs-230328.tar.gz](https://github.com/KiwiHC16/Abeille/files/11091970/AbeilleLogs-230328.tar.gz)

**Comment by tcharp38** [comment]
Du coup l'image correspondante n'est pas bonne.
Il me faudra une image PNG sans arriere plan pour mettre en icone.
Tu as pu tester le modele ?

Ce sujet est fermé par erreur je suppose non ?

**Comment by mohatem** [comment]
les commandes fonctionnes c'est parfait, 
voici l'image en png sans arriere plan , je suis en train de me prendre la tête pour le même problème avec bandes led osram smart+
![tradfri 470 filament](https://user-images.githubusercontent.com/58750727/228322742-b76a4472-4d54-4930-bf13-6a76d7024b8e.png)
