### ISSUE TITLE
Réparation équipement suite perte modèle sur volet/telec Profalux

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2565]
Hello @tcharp38 

J'ai une petite question à te poser.
Pour une raison que j'ignore encore, j'ai l'un de mes volets Profalux et sa tlc qui viennent de passer en type/modèle defaultUnknown.
De ce fait les actions monter / descendre / stop ont disparu ! La tlc continue de piloter le volet par contre.
De plus grâce à l'utilisation des groupes sur Abeille, j'arrive encore à le piloter (uniquement si groupe).

C'est un volet qui n'est accessible que via une échelle 3 pans (vitre fixe) et à chaque fois que je refais la manip de réinclusion, il plante et m'oblige à le resetter via la méthode des câbles élec.

Ma question est donc : peut-on forcer un type/modèle sur un équipement ? SI oui, comment faire ? ;)

Merci d'avance

Xav

**Comment by tcharp38** [comment]
Salut @Xav-74 
Haaaaaaa... j'ai eu ce pb il y a qq jours chez moi. Pas compris du tout ce qui c'était passé.
Du coup ne voulant pas me retaper une inclusion (le volet etant toujorus dans le reseau), j'ai bossé sur qq améliorations pour "réparer" ce genre de cas.

Es tu sur la beta ?

**Comment by Xav-74** [comment]
Hello ! Yes dernière beta de ce matin !

**Comment by tcharp38** [comment]
Parfait. Tu vas pouvoir tester.
Active le mode dev via la page de config/options avancées
Redemarre Abeille
Puis va sur le volet en question, onglet avancé
Tu dois voir un bouton "Reparer".

Appuis dessus jusqu'a ce qu'Abeille te dise ".. mise à jour à partir de .."

Accessoirement file moi les logs que je check comment ca se deroule.
C'est du preliminaire mais ca m'a sorti de ce pb

**Comment by Xav-74** [comment]
Super pour le tips ! Je teste ça demain et je te tiens au jus 😜

**Comment by Xav-74** [comment]
Bon j'ai essayé rapidement avec mon DNS externe mais le clic sur "Réparer" reste inopérant de mon côté !

**Comment by tcharp38** [comment]
Pas si sûr. Donne moi les logs stp

**Comment by Xav-74** [comment]
Je te confirme que tout est OK.
En fait le souci venait de moi :)
Lorsque je cliquais sur Réparer, je ne quittais pas l'équipement mais je faisais un save pour voir si les commandes réapparaissaient.
Or la mise à jour de l'équipement se fait en quittant celui-ci er en revenant dessus. Du coup j'écrasais systématiquement les modifs faites !
C'est tout bon merci !

**Comment by tcharp38** [comment]
Ok super.
J'ai encore un peu amélioré le process hier et j'ai encore du taf dessus avant de le rendre "public" mais ca aide.

A suivre !

**Comment by Xav-74** [comment]
Hello @tcharp38 

Je me permets de réouvrir temporairement ce sujet car ce week-end, j'ai un volet et sa tlc qui sont passé en "defaultUnknown".
En voulant utiliser la méthode réparer, je m'aperçois que le modèle est "rucheCommand" 

![image](https://user-images.githubusercontent.com/56156622/237023612-1e2fbd5a-5d23-4d45-8570-d4b496790769.png)

Et le bouton Réparer semble inopérant. Plusieurs clics à 9h21. Voici les logs.

[AbeilleLogs-230509.tar.gz](https://github.com/KiwiHC16/Abeille/files/11428404/AbeilleLogs-230509.tar.gz)

Merci d'avance

**Comment by tcharp38** [comment]
Salut @Xav-74 
Ha oui un souci que j'ai déja vu passer sur mes volets. Tres rare mais visiblement pas compris.

Ce sont bien des volets "Profalux" ?

Peux tu donner le snapshot complet de la page avancé .. au moins la partie "common" + "device" ? Je ne vois pas le rapport avec 'rucheCommand'

**Comment by Xav-74** [comment]
Je te confirme ! Volet Profalux de 2018
Voici la page complète :

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/7d08d8c7-3725-47fd-9fd1-c36469ca3c15)

Idem, voici celle de la tlc : 

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/9dd4fcf8-5eda-423b-b633-38a043a41ffe)

A noter que sur la page santé ils sont bien en defaultUnknown"

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/fdf282a9-585f-495d-8aee-b7c9831bec95)

Merci
Xav

**Comment by tcharp38** [comment]
Ok, tres etrange.
Cote telecommande on ne peut rien faire mais en meme temps son apparition ou non dans Jeedom n'apporte strictement rien.
Laisse la de cote, cachée.

Cote volet, peux tu faire plusieurs fois "reparer" (je sais c'est ch.. mais pas eu le temps d aller + loin), en laissant 1 à 2sec entre chaque appuis. Ca doit finir par une mise à jour.
File le moi les logs dans la foulée.
Je n'ai vu aucune tentative de reparation sur ce volet.

**Comment by Xav-74** [comment]
On est en phase sur la partie tlc ;)

J'ai essayé de réparer avec une 100aine de clics espacés de 2s. Sans résultat.
D'ailleurs sur la dernière beta, j'ai une erreur si je passe en mode inclusion : 

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/b6065b32-fb8a-4451-a1d5-6c741e688d31)

Un lien ou pas ?

**Comment by tcharp38** [comment]
Les logs STP.
Je vais voir si je reproduis ton erreur.

**Comment by Xav-74** [comment]
[AbeilleLogs-230509.tar.gz](https://github.com/KiwiHC16/Abeille/files/11431323/AbeilleLogs-230509.tar.gz)

**Comment by tcharp38** [comment]
Ha oui je reproduis l' erreur :( 
Pour le "reparer".. je crois qu'il y a aussi une regression depuis les modifs pour le support de la 4.4.
Je regarde ca tout de suite

**Comment by tcharp38** [comment]
Peux tu tester la beta d'hier ?

**Comment by Xav-74** [comment]
Beta installée ;)

C'est OK pour l'inclusion maintenant.
Par contre pas mieux pour le réparer :

[AbeilleLogs-230510.tar.gz](https://github.com/KiwiHC16/Abeille/files/11439853/AbeilleLogs-230510.tar.gz)

**Comment by FabriceC38** [comment]
Ha ben oui il manque des choses dans ce "repair"

Peux tu décompresser ce fichier dans Abeille/core/php
[AbeilleRepair.zip](https://github.com/KiwiHC16/Abeille/files/11442576/AbeilleRepair.zip)

puis faire qq "reparer"
et me filer les logs.
Merci

**Comment by FabriceC38** [comment]
Ha ben oui il manque des choses dans ce "repair"

Peux tu décompresser ce fichier dans Abeille/core/php
[AbeilleRepair.zip](https://github.com/KiwiHC16/Abeille/files/11442950/AbeilleRepair.zip)

et celui la dans Abeille/core/class
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11442956/AbeilleTools.class.php.zip)

puis faire qq "reparer"
et me filer les logs.
Merci

**Comment by tcharp38** [comment]
Ha ben oui il manque des choses dans ce "repair"

Peux tu décompresser ce fichier dans Abeille/core/php
[AbeilleRepair.zip](https://github.com/KiwiHC16/Abeille/files/11442981/AbeilleRepair.zip)


et celui la dans Abeille/core/class
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11442956/AbeilleTools.class.php.zip)

puis faire qq "reparer"
et me filer les logs.
Merci

**Comment by Xav-74** [comment]
[AbeilleLogs-230510.tar.gz](https://github.com/KiwiHC16/Abeille/files/11443225/AbeilleLogs-230510.tar.gz)

Mise à jour des fichiers à 16h47 puis redémarrage du démon.
Plusieurs clics sur réparer puis réinitialiser mais je reste toujours en defaultUnknown

Merci d'avance

**Comment by tcharp38** [comment]
Alors je viens de réaliser un truc... ton volet a une adresse IEEE qui n'est pas celle de Profalux.
Je reve.

20918A000006EB17 ("AB Tlc Volet Salle \u00e0 manger") => Profalux
000D6F0012214D89 ("AB Volet Salle \u00e0 manger") => Ember Corporation

Je pige pas d'ou ca sort alors on va reverifier ca.
Via sa page avancé, fais une requete d'adresse IEEE
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/96267891-fdbf-4342-85a9-20610d44f991)

et file moi au moins le log parser dans la foulée.

**Comment by Xav-74** [comment]
```
2290|[2023-05-10 17:41:04] Abeille1, Type=8000/Status, Status=00/Success, SQN=00, PacketType=0010, Sent=00, SQNAPS=00, NPDU=00, APDU=00
2291|[2023-05-10 17:41:04] Abeille1, Type=8010/Version, Appli=0003, SDK=0323
2292|[2023-05-10 17:41:14] Abeille1, Type=8000/Status, Status=00/Success, SQN=46, PacketType=0041, Sent=02, SQNAPS=5E, NPDU=00, APDU=01
2293|[2023-05-10 17:41:14] Abeille1, Type=8012/APS data confirm, Status=00, Addr=1144, SQNAPS=5E, NPDU=00, APDU=01
2294|[2023-05-10 17:41:14] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=8001, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=1144, DstAddrMode=02, DstAddr=0000
2295|[2023-05-10 17:41:14]   IEEE address response: SQN=46, Status=00, ExtAddr=000D6F0012214D89, Addr=1144
2296|[2023-05-10 17:41:14] Abeille1, Type=8041/IEEE address response (unused).
2297|[2023-05-10 17:41:14] Abeille1, Type=8011/APS data ACK, Status=00/Success, Addr=1144, EP=00, ClustId=0001, SQNAPS=5E
```

**Comment by Xav-74** [comment]
en effet, tous mes matériels Profalux (volets + tlc) commencent par 20918A00000...

Au pire t'embête pas, je refait une inclusion propre. Il a peut-être vrillé :)

**Comment by tcharp38** [comment]
Non fais juste la lecture IEEE qu'on voit

**Comment by tcharp38** [comment]
Il repond bien 000D6F0012214D89.. mais ca n'est pas Netgear contrairement à ce que j'ai dit avant mais "Ember corporation".
?!?
Je vais fouiller le net pour voir si il y a une piste

**Comment by tcharp38** [comment]
Bon aucune piste :(
Du coup mon procédé de recupération spécifique Profalux ne s'applique pas pour toi.
Si ca n'est pas le volet lui meme qui repond cette enormité... d'ou ca vient ?

Tu as un autre volet de la meme generation ?

**Comment by tcharp38** [comment]
Nouveau test avec cette version du coup. J'ignore l adresse IEEE.
[AbeilleRepair.zip](https://github.com/KiwiHC16/Abeille/files/11444463/AbeilleRepair.zip)

**Comment by Xav-74** [comment]
Je te confirme que c'est OK avec cette version 👍 
Mais je ne voudrais pas te faire modifier le code juste pour un volet capricieux. Je vais tenter de le réinitialiser puis le réinclure ce week-end car en effet j'ai 11 volets et BSO + 11 tlc Profalux et toutes les adresses IEEE commencent par 20918A00000... sauf celui-ci.

PS : de mémoire par contre je crois que c'est le seul qui a été changé suite à une panne 1 mois après la livraison de ma maison

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/5928e611-d4c5-443e-85d2-08b384221c52)

**Comment by tcharp38** [comment]
Tu me files les logs ?
Stp ?

**Comment by Xav-74** [comment]
Les voici : 
[AbeilleLogs-230511.tar.gz](https://github.com/KiwiHC16/Abeille/files/11449131/AbeilleLogs-230511.tar.gz)

En espérant que tu ais toutes les infos (réparation vers 22H30 de mémoire)

**Comment by tcharp38** [comment]
Encore une update.
[AbeilleRepair.zip](https://github.com/KiwiHC16/Abeille/files/11449951/AbeilleRepair.zip)

Je garde ces modifs car je veux eviter à tout pris d etre obligé de refaire une inclusion quand on peut "reparer".

**Comment by Xav-74** [comment]
👍 

Test ce matin à 10h05 avec ce nouveau fichier. Voici les logs : 
[AbeilleLogs-230512.tar.gz](https://github.com/KiwiHC16/Abeille/files/11460872/AbeilleLogs-230512.tar.gz)

Juste une dernière chose avant de clore : dans l'onglet équipement, tous les "type" affichent "Zigate" et sur l'onglet "Avancé" le 'Modèle équipement" reste sur "rucheCommand". ET ce pour tous mes équipements ;)

**Comment by tcharp38** [comment]
Ca c'est corrigé normalement dans la beta dispo ce jour.
Je te laisse basculer et confirmer.

**Comment by Xav-74** [comment]
Yes je n'avais pas fait la mise à jour pour tester ton dernier fichier. C'est chose faite.
Je te confirme que c'est OK pour l'onglet avancé, pas pour celui de l'équipement ;)

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/2584ebd0-ef1f-42c5-b361-0f5997281f7d)

Je clos le sujet et merci encore pour ton support !!!

**Comment by tcharp38** [comment]
Merci pour tes essais.
C'est grace à ceux qui utilisent la beta qu'on peut avancer et fiabiliser/améliorer les choses.
