### ISSUE TITLE
Bug d'actions lors d'éxecution

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2566]
Salut !
Ce matin j'ai de nouveau eu un bug assez embétant. que j'ai déjà eu dans le passé.
- Ce matin, je demande à Alexa d'arrêter mon `soufflant (4EF6 / 50325FFFFE5ABF89)`   : Alexa éteint soufflant
Jusque la tout va bien.
Je sors de la salle de bain et le je vois toutes mes lumières de séjour éteintes.

J'avais un peu configurer ma timeline pour voir ca, mais je viens de renforcer l'affichage des remontés quand je vois cette image

![image](https://user-images.githubusercontent.com/49479084/228785896-02e0010e-2dfe-492b-8132-ca6b5e294791.png)

C'est à 6h44 que je coupe le soufflant, et ca a envoyé des commandes à plein de chose.
Sur mon virtuel j'ai plein d'équipement dont par exemple : `Canapé (B44D / 00158D0003A3594D)` qui à reçu un `off`
**Dont mon contact de porte de garage : `Contact sec (CB8D / 00124B00246DFC10)`, et c'est la que ca fait peur, car la denrière fois ca me l'a ouverte.**
_Je pense d'ailleurs que mes `Niches (78FB / 00158D0003543B07)` se sont aussi éteinte alors qu'il y avait du mouvement (allumé quand mouvement, mais je ne sais plus_

Je ne sais pas comment débuguer ou identifier le problème.
Je fais une issue car c'est vraiment pas normal ce phénomène, mais je suis très curieux de savoir comment identifier l'origine.

La première question que j'ai en tête, c'est, est ce qu'un `OFF` à était envoyé à tous les équipements zigbee ?
si ca peut t'aider à savoir si c'est le ca, j'ai à première vue, 15 équipements sur Abeille qui contiennent une action OFF.

[AbeilleLogs-230330.tar.gz](https://github.com/KiwiHC16/Abeille/files/11109864/AbeilleLogs-230330.tar.gz)

**Comment by tcharp38** [comment]
Si tu dis que couper le soufflant est ton point de départ alors je vois ca (AbeilleCmd.log)

[2023-03-30 06:44:30] -- execute([Salle de bain haut][Soufflant][Off], type=action, options=null)

Ca c'est ok mais il y a aussi dans la foulée

[2023-03-30 06:44:30] -- execute([Salon][Liseuse][Off], type=action, options=null)
[2023-03-30 06:44:30] -- execute([Cuisine][Four][Off], type=action, options=null)
[2023-03-30 06:44:30] -- execute([Salon][Baril][Off], type=action, options=null)
[2023-03-30 06:44:30] -- execute([Cuisine][Café][Off], type=action, options=null)
[2023-03-30 06:44:30] -- execute([Garage][Contact sec][Off], type=action, options=null)
[2023-03-30 06:44:30] -- execute([Bureau][Bibliotèque][Off], type=action, options=null)

Autrement dit... il y a  de vraies demandes pour arreter tous ces équipements et elles proviennent toutes de Jeedom.
Abeille ne fait qu'obeir.

Pour confirmer ca tu peux juste, via le dashboard, refaire un [Salle de bain haut][Soufflant][Off] et voir si ca declenche autre chose.

Si j'ai bien compris c'est Alexa qui envoie l'ordre donc tu dois avoir un log de ce plugin non ?
Auquel cas peut etre que tu y trouvera les autres demandes.

**Comment by Jake309** [comment]
D'accord, je vais creuser ca.
Si ce n'est pas abeille, pas de raison que je te dérange.
Ca ne s'est pas reproduit en faisant [Salle de bain haut][Soufflant][Off].
C'est vraiment rarement, alors que le soufflant tourne tout les jours.

Tu as ouvert quel fichier pour voir ces log ?
Qu'est ce qui te permet de savoir que ca provient de jeedom ? le fait que ce soit pazr exemple : execute([Salon][Liseuse][Off], type=action, options=null) ?

Merci

**Comment by tcharp38** [comment]
J'ai regardé dans AbeilleCmd.log
Si l'ordre vient de Jeedom (scenario, ou d'un autre plugin par ex), c'est toujours préfixé par "-- execute()"

**Comment by tcharp38** [comment]
@Jake309 
Tu as trouvé qqch ?

**Comment by Jake309** [comment]
Toujours rien depuis. d'où le délai 
On peut cloturer.
