### ISSUE TITLE
TS0201 NIKJEBDF  (TS0201__TZ3000_ywagc4rj)

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2567]
Bonjour, j'ai des ennuis avec des sondes températures et humidités qui se sont connectés en premiers lieux en TS0201. 
et qui fonctionnaient très bien. Mais depuis le 2023-03-27 01:00:23 le device n'ont plus de commande température et humidité.
la relance de la découverte ne voit plus le device comme un TS0201, j’ai supprimé et refait la connexion de la sonde et elle n’est plus reconnue. defaultUnknown - 599
j’ai relancé les dépendances sans succès.
Version
2023-03-27 01:00:23
il semble aussi que le répertoire /core/config/device/TS0201 ne contienne aucun .json, est ce normal?
je joins le Discovery, mais encore une fois cela a focntionné auparavant. 
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/11139826/discovery.zip)
merci

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Pas surpris qu'il se passe qqch avec ce modele vu que je l'ai renommé mais normalement il devait etre transparent pour toi.
Peux tu me donner un package de logs ? (mode debug, page maintenance/telecharger tout).
Ton discovery est vide, donc pas utile malheureusement.

**Comment by VVorttexx** [comment]
bonjour,

voici

Cdlt.

**Comment by tcharp38** [comment]
Salut

Aucun log attaché.
Ne jamais faire un reply. Ca ne fonctionne pas. Il faut passer par l interface WEB de Github.

**Comment by VVorttexx** [comment]
[AbeilleLogs-230404 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11148324/AbeilleLogs-230404.1.tar.gz)
Devrait être mieux.

**Comment by tcharp38** [comment]
A quoi ressemble ton device TS0201 ?
Quelle marque ? ref ?
J'ai besoin d'une image PNG sans arriere plan si ca ne correspond pas à un truc deja existant ce qui semble etre le cas.
Merci

**Comment by VVorttexx** [comment]
bonjour, 
alors c'est un NIKJEBDF (non c'est pas le chat qui marche sur le clavier)
tu peux avoir toutes les infos là 
https://www.amazon.fr/dp/B0BNLFV5BD?ref=ppx_yo2ov_dt_b_product_details&th=1
mais pour moi c'est la même image que le TS0201

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices/TS0201__TYZB01_hjsgdkfl
[TS0201__TYZB01_hjsgdkfl.zip](https://github.com/KiwiHC16/Abeille/files/11157707/TS0201__TYZB01_hjsgdkfl.zip)

puis redemarrer Abeille
et refaire inclusion

**Comment by VVorttexx** [comment]
Hello, merci cela fonctionne, vais refaire les scenar et les dashboard,
mais les temp. et humidité sont bien là, un truc étrange sur l'écran du
device,  j'ai 44% d'humidité, mais dans Jeedom j'ai 4,4, suit obligé de
passer #value#*10...(mais cela le faisait lors de la première installation,
pas de lien avec le nouveau json.)

merci pour ta rapidité.
Cordialement.

**Comment by tcharp38** [comment]
Ha pas cool cette histoire de %.
peux tu me filer le package de logs que je regarde ?
Ca voudrait dire que meme si meme aspect il ne se comporte pas comme le mien.

**Comment by VVorttexx** [comment]
voici les logs avec les devices ré intégrées
[AbeilleLogs-230407.tar.gz](https://github.com/KiwiHC16/Abeille/files/11176356/AbeilleLogs-230407.tar.gz)

**Comment by tcharp38** [comment]
Manque de pot tes logs sont bien trop courts.
Tu aurais du avoir un message d'aileurs, te disant de passer à 5000 lignes non ?

Du coup je ne vois pas la remontée d'info '%'.

**Comment by VVorttexx** [comment]
hello, j'ai du merdé en fait, voici en mode debbug et 5000 lignes.
[AbeilleLogs-230407 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11180612/AbeilleLogs-230407.1.tar.gz)

**Comment by tcharp38** [comment]
[2023-04-07 20:00:47] Abeille2, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0405, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=27B4, DstAddrMode=02, DstAddr=0000
[2023-04-07 20:00:47]   FCF=08/General/Serv->Cli, SQN=A7, cmd=0A/Report attributes
[2023-04-07 20:00:47]   AttrId=0000/MeasuredValue, AttrType=21, ValueHex=0182 => ZCL corrected value, 3.86

Le device remonte x182, soit 386, qui doit etre divisé par 100 d'apres la spec ZCL, donc 3.86.
Si le 38.6 est la bonne valeur alors ca confirme que ce device ne remonte pas un truc standard.
Il lui faut donc un modele specifique.

Mais il faut que je modifie le code aussi pour pouvoir supporter un cas foireux comme ca.

Peux tu basculer sur la prochaine beta une fois qu'elle est prete ?

**Comment by VVorttexx** [comment]
Hello,
Vu le coté chinois du bazar il y a des chances pour qu'il ne soit pas
standard en effet, ok pour passer en bêta pour test quand tu veux, mais en
même temps, cela ne vaut peut être pas le coup de modifier le code juste
pour ça, comme il suffit de corriger la valeur dans jeedom, pour moi c'est
transparent.
Comme tu veux.
GIL

**Comment by tcharp38** [comment]
Je ne fais pas un code spécifique au device mais qqch de generique, reutilisable.
J'avais deja du le faire pour un autre, mais sur une autre info (temperature). Bref j'ai juste rendu le truc encore + generique.
La beta de demain contiendra ca.

**Comment by VVorttexx** [comment]
ok c'est noté je passerai en Bêta demain et t'informerai.

**Comment by tcharp38** [comment]
Salut @VVorttexx 
On en est ou sur ce sujet ?

**Comment by VVorttexx** [comment]
Salut, je croyais t avoir répondu désolé pas de PB pr moi, je suis resté en beta mais cela fonctionne. Merci.

**Comment by tcharp38** [comment]
Ha cool.
Je clos le sujet alors.
Merci

Pas de soucis pour rester en beta. Tu es du coup toujours en avance sur la stable.
