### ISSUE TITLE
Ajout support SONOFF ZBMINI Extreme - ZBMINIL2

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2569]
Bonjour,
J'ai acheté ces nouveaux modules Sonoff... Est-ce que c'est possible de les intégrer dans Abeille???

![image](https://user-images.githubusercontent.com/68732573/230662401-1822f085-696e-4fd9-88f1-a6ab6254fd7a.png)

Merci d'avance

**Comment by fable73** [comment]
[discovery-ZBMINIL2_SONOFF.zip](https://github.com/KiwiHC16/Abeille/files/11181279/discovery-ZBMINIL2_SONOFF.zip)

**Comment by tcharp38** [comment]
Pour test

A decompresser dans core/config/devices
[ZBMINIL2_SONOFF.zip](https://github.com/KiwiHC16/Abeille/files/11181920/ZBMINIL2_SONOFF.zip)

L'image pour "images"
[node_Sonoff-ZBMiniL2.zip](https://github.com/KiwiHC16/Abeille/files/11181924/node_Sonoff-ZBMiniL2.zip)


redemarrer Abeille
refaire inclusion

Si tu peux, ca serait bien que tu bascules sur la beta. Je demande toujours ca quand je fais du support. 
Ca me permet d'avoir des retours et de travailler sur le dernier code.

**Comment by fable73** [comment]
Merci pour ta réactivité! J'avais essayé de trafiquer le json de la version précédente de ce switch mais ça fonctionnait pas...
le tien marche nickel... J'ai juste changé 

- la "category" pour mettre "ligth" au lieu de "energy"

- le titre de quelques commandes pour virer les "1"... je te remet ici le json modifié...

J'en ai profité aussi pour supprimer le tour blanc de l'image que je t'avais envoyé... plus sympa sur le thème sombre.
[ZBMINIL2_SONOFF_EA.zip](https://github.com/KiwiHC16/Abeille/files/11183123/ZBMINIL2_SONOFF_EA.zip)
![node_Sonoff-ZBMiniL2](https://user-images.githubusercontent.com/68732573/230719099-06758f9b-a266-4680-8227-f39af1e996da.png)

**Comment by fable73** [comment]
[node_Sonoff-ZBMiniL2.zip](https://github.com/KiwiHC16/Abeille/files/11183129/node_Sonoff-ZBMiniL2.zip)

**Comment by tcharp38** [comment]
Ok j'ai pris tes modifs.
Ca sera dans la prochaine beta.
