### ISSUE TITLE
Régression : Capteur Temp et humidité TS0201__TZ2000_a476raq2 modèle disparue 

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#2570]
Depuis une mise à jour d'abeille ou plusieurs je ne sais pas exactement, car je viens juste de le voir, ma zigate ayant complétement plantée, tous mes capteurs de temperature avec ecran lcd rond Tuya sont vide avec un modèle défini à : "defaultUnknow"

![image](https://user-images.githubusercontent.com/72082610/230741827-853f2c6e-3555-4f8f-9a8b-a38ed2798762.png)

Cordialement,

**Comment by Jorael57** [comment]
Mais il y a une chance pour que ce soit depuis la dernier maj seulement.

**Comment by Jorael57** [comment]
[discovery-TS0201__TZ2000_a476raq2.json.txt](https://github.com/KiwiHC16/Abeille/files/11184221/discovery-TS0201__TZ2000_a476raq2.json.txt)
Au cas ou tu en a besoin

**Comment by tcharp38** [comment]
Salut @Jorael57 
Peux tu me dire à quoi il ressemble ce device ? C'est un capteur avec affichage comme suit ?

![image](https://user-images.githubusercontent.com/35221038/230760302-5004162e-9525-4b7f-9fb2-ad8a6ec9faa2.png)

**Comment by Jorael57** [comment]
Oui c'est bien ça.
Tu as tjs besoin du package de logs ?

**Comment by tcharp38** [comment]
Non inutile.

Un modele à ecraser (core/config/devices/TS0201__TYZB01_hjsgdkfl)
[TS0201__TYZB01_hjsgdkfl.zip](https://github.com/KiwiHC16/Abeille/files/11199765/TS0201__TYZB01_hjsgdkfl.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by bidoch78** [comment]
Chez moi le device ressemble à ca.
Si à l'occasion vous pouvez l'ajouter, ca serait cool.

![capteurtemp-ybi](https://user-images.githubusercontent.com/16101584/233857140-4598d45f-6ae1-4b3f-ae2b-a7ad69cbb419.png)

**Comment by tcharp38** [comment]
@bidoch78 
Cet aspect laisse à penser que c'est un modele different qui est manquant ou pas reconnu.
Ouvre un sujet different et suis ca STP: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by tcharp38** [comment]
@Jorael57 
On en est ou ?

Si tu as basculé sur la derniere beta, tu dois pouvoir refaire une inclusion sans soucis. Tu confirmes ?

**Comment by Jorael57** [comment]
Nul part,.. je me bas avec la zigate : 

```
[2023-05-10 00:00:01] Test de communication avec la Zigate; type=USB, port=/dev/ttyUSB10, GpioLib=WiringPi
[2023-05-10 00:00:02] Démarrage de 'checkTTY.sh'
[2023-05-10 00:00:02]  Vérifications du port '/dev/ttyUSB10'
[2023-05-10 00:00:02] = ERREUR: Le port est utilisé par le process '1'.
[2023-05-10 00:00:02] =         Il doit être libéré et n'être utilisé QUE par le plugin Abeille pour permettre le dialogue avec la Zigate.
[2023-05-10 00:00:02] =         Details du process 1:
[2023-05-10 00:00:02] =           PPid=0, cmd='/sbin/init'
```
La zigate ne répond plus à jeedom

**Comment by tcharp38** [comment]
Le port semble utilisé par "init".. comme si ton systeme avait mis une console ou autre dessus.
Je ne suis pas expert Linux mais tu as changé qqch dans ta config ou fait une mise à jour du kernel peut etre ?

**Comment by Jorael57** [comment]
Oui c'est possible qu'il y ait eu une update du kernel, mon jeedom est sur un container linux sous Proxmox.
mais pour débugger ce qui se passe là je ne suis pas expert ... J'ai réussi à reflasher la zigate sans problème donc ça c'est bon.
Je suis repasser sur Abeille Stable pour voir mais pas de changement.
... Je ne sais plus quoi faire, je vais chercher du côté des commandes pour débloqué le port USB.

**Comment by tcharp38** [comment]
peux tu me filer les ficheirs suivants si tu trouves
/boot/config.txt
/boot/cmdline.txt

**Comment by Jorael57** [comment]
Je n'ai aucun de ces fichiers que ce soit sur le host ou sur le container.

**Comment by Jorael57** [comment]
Voici un lsof sur la clé USB :
lsof /dev/ttyUSB10
COMMAND      PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd        1       root    0u   CHR    1,3      0t0    5 /dev/null
systemd        1       root    1u   CHR    1,3      0t0    5 /dev/null
systemd        1       root    2u   CHR    1,3      0t0    5 /dev/null
systemd-j     44       root    0r   CHR    1,3      0t0    5 /dev/null
systemd-j     44       root    1w   CHR    1,3      0t0    5 /dev/null
systemd-j     44       root    2w   CHR    1,3      0t0    5 /dev/null
avahi-dae     94      avahi    0r   CHR    1,3      0t0    5 /dev/null
cron          95       root    0r   CHR    1,3      0t0    5 /dev/null
dbus-daem     96 messagebus    0u   CHR    1,3      0t0    5 /dev/null
polkitd       99       root    0u   CHR    1,3      0t0    5 /dev/null
polkitd       99       root    1u   CHR    1,3      0t0    5 /dev/null
polkitd       99       root    2u   CHR    1,3      0t0    5 /dev/null
rsyslogd     100       root    0r   CHR    1,3      0t0    5 /dev/null
rsyslogd     100       root    1w   CHR    1,3      0t0    5 /dev/null
rsyslogd     100       root    2w   CHR    1,3      0t0    5 /dev/null
rsyslogd     100       root    4r   CHR    1,9      0t0   10 /dev/urandom
systemd-l    101       root    0r   CHR    1,3      0t0    5 /dev/null
wpa_suppl    102       root    0r   CHR    1,3      0t0    5 /dev/null
atd          103     daemon    0u   CHR    1,3      0t0    5 /dev/null
atd          103     daemon    1u   CHR    1,3      0t0    5 /dev/null
atd          103     daemon    2u   CHR    1,3      0t0    5 /dev/null
avahi-dae    106      avahi    0r   CHR    1,3      0t0    5 /dev/null
ModemMana    119       root    0r   CHR    1,3      0t0    5 /dev/null
ModemMana    119       root    2w   CHR    1,3      0t0    5 /dev/null
unattende    301       root    0r   CHR    1,3      0t0    5 /dev/null
fail2ban-    304       root    0r   CHR    1,3      0t0    5 /dev/null
sshd         317       root    0r   CHR    1,3      0t0    5 /dev/null
ntpd         325        ntp    0r   CHR    1,3      0t0    5 /dev/null
ntpd         325        ntp    1r   CHR    1,3      0t0    5 /dev/null
ntpd         325        ntp    2r   CHR    1,3      0t0    5 /dev/null
mosquitto    332  mosquitto    0r   CHR    1,3      0t0    5 /dev/null
apache2      346       root    0r   CHR    1,3      0t0    5 /dev/null
apache2      346       root    1w   CHR    1,3      0t0    5 /dev/null
apache2      402   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2      402   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2      403   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2      403   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2      408   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2      408   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2      410   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2      410   www-data    1w   CHR    1,3      0t0    5 /dev/null
mariadbd     477      mysql    0r   CHR    1,3      0t0    5 /dev/null
master       637       root    0u   CHR    1,3      0t0    5 /dev/null
master       637       root    1u   CHR    1,3      0t0    5 /dev/null
master       637       root    2u   CHR    1,3      0t0    5 /dev/null
master       637       root    4u   CHR    1,3      0t0    5 /dev/null
master       637       root    6u   CHR    1,3      0t0    5 /dev/null
master       637       root    7u   CHR    1,3      0t0    5 /dev/null
master       637       root    8u   CHR    1,3      0t0    5 /dev/null
master       637       root    9u   CHR    1,3      0t0    5 /dev/null
qmgr         639    postfix    0u   CHR    1,3      0t0    5 /dev/null
qmgr         639    postfix    1u   CHR    1,3      0t0    5 /dev/null
qmgr         639    postfix    2u   CHR    1,3      0t0    5 /dev/null
packageki  63945       root    0r   CHR    1,3      0t0    5 /dev/null
apache2   231195   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   231195   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2   231290   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   231290   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2   231291   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   231291   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2   231292   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   231292   www-data    1w   CHR    1,3      0t0    5 /dev/null
pickup    251271    postfix    0u   CHR    1,3      0t0    5 /dev/null
pickup    251271    postfix    1u   CHR    1,3      0t0    5 /dev/null
pickup    251271    postfix    2u   CHR    1,3      0t0    5 /dev/null
apache2   253960   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   253960   www-data    1w   CHR    1,3      0t0    5 /dev/null
apache2   253962   www-data    0r   CHR    1,3      0t0    5 /dev/null
apache2   253962   www-data    1w   CHR    1,3      0t0    5 /dev/null
php       254901   www-data    0r   CHR    1,3      0t0    5 /dev/null
**php       254901   www-data    8r   CHR  188,0      0t0  863 /dev/ttyUSB10**
php       254903   www-data    0r   CHR    1,3      0t0    5 /dev/null
php       254905   www-data    0r   CHR    1,3      0t0    5 /dev/null
php       254919   www-data    0r   CHR    1,3      0t0    5 /dev/null
php       254962   www-data    0r   CHR    1,3      0t0    5 /dev/null

**Comment by Jorael57** [comment]
En fait la Zigate fonctionne toujours tous les nœuds du reseau qui sont tjs dans le réseau fonctionnent par contre impossible de la passer en mode inclusion. 
Est ce que si je passe la zigate sur le plugin zigbee je perds tous le reseau ?  ( C'est pour tester si ça vient du plugin ou de jeedom)

**Comment by tcharp38** [comment]
Ha ben des choses ont changé alors.
Peux tu me filer le package de logs ?

**Comment by Jorael57** [comment]
Bon finalement j'ai avancé , pour cette issue je confirme que c'est de nouveau ok.

Par contre pour la zigate ou jeedom ou le plugin , j'ai actuellement 1min de delai environ entre le moment ou je clique sur le bouton pour passer la zigate en inclusion et le moment ou elle se met à clignoter.

Je ferme cette issue et j'ouvre une autre pour investiguer le problème de lenteur ?

**Comment by tcharp38** [comment]
Oui si ca devient hors sujet... il vaut mieux basculer sur un + approprié.
