### ISSUE TITLE
Plugin introuvable  : AbeilleEq => Incompatibilité Jeedom 4.4

### ISSUE THREAD

**Issue by Snakelori** [KiwiHC16/Abeille#2571]
Bonjour,
J’ai un soucis depuis quelques jours .Quand je veux afficher des informations sur mes équipements dans plugin abeille j’ai plusieurs messages d’erreur surlignés en rouge qui affiche « Plugin Introuvable : AbeilleEQ » et impossible d’aller dans les onglets « Avancé » ou « commande » des mes équipements enregistrés dans le plugin « Abeille ».
Merci pour votre aide

Jeedom : Version 4.4.0
Abeille : Version 2023-03-27 01:00:23
Clé Zigate+ : Version 0005-03A0

![image](https://user-images.githubusercontent.com/63954776/230956121-3b4db4e1-287e-48b9-94b0-29c40be6b0df.png)

**Comment by tcharp38** [comment]
Salut @Snakelori 
Que s'est il passé avant que ca ne bascule sur ce pb ?
Je n'ai jamais vu ce genre d'err et personne d'autre n'a remonté le souci.

Ha par contre je constate que tu es passé en Jeedom 4.4.
Ca c'est du jamais testé. Peut etre y a t'il un lien.

**Comment by Snakelori** [comment]
En fait j'ai fait une MAJ du firmware de ma Zigate mais je me suis aperçu que j'étais déjà en 3.20. Ensuite j'ai voulais éditer un de mes équipements dans abeille et j'ai eu ce message d'erreur. 
Pour info aujourd'hui j'ai fait une MAJ de ma zigate en 0005-03A0 mais cela ne change rien. 
Jje ne sais pas dire si c'est depuis que je suis en jeedom v 4.4 que j'ai le soucis :(

**Comment by tcharp38** [comment]
Comment tu bascules en 4.4 ?
J'ai l'impression qu'elle n'est pas encore en version stable. Je me trompe ?

**Comment by Snakelori** [comment]
Directement à partir de jeedom dans la section MAJ.
Oui effectivement , elle n'est pas en version stable 😔

**Comment by tcharp38** [comment]
J'ai du activer le mode beta pour core.
Mais je suis en 4.4 et je reproduis ton pb... bel et bien lié à la 4.4

Je vais regarder et essayer de comprendre.

**Comment by Snakelori** [comment]
Ah ok, merci 👍

**Comment by tcharp38** [comment]
Par contre à premiere vue ca n'est pas evident donc pas sur de fixer ca rapidos.
Je te suggere de desactiver le mode "beta" pour le core et revenir en 4.3.x qui elle est stable.

**Comment by Snakelori** [comment]
OK . J'vais faire ça . Merci 😉

**Comment by Snakelori** [comment]
J'suis repassé en version 4.3.17 et cela fonctionne de nouveau ;)
Merci tcharp38 et bon courage pour la résolution en 4.4 ;)

**Comment by kaleofr** [comment]
Hello,
du nouveau à propos de ce soucis?
Parce que je viens d'avoir quelques modifs à faire et de me rendre compte de ce problème.
Du coup ma dernière sauvegarde en 4.3 à presque un mois et ca m'ennui de devoir réutiliser un backup aussi ancien.
Enfin... la 4.4... il va bien falloir y passer également :-(

Donc, je ne viens pas ici pour mettre la pression mais plutôt pour savoir si je dois faire un croix sur un mois d'historique et de modifs ou plutôt patienter un peu pour faire mes nouvelles modifs.

Merci.

Kaléo.

**Comment by tcharp38** [comment]
Salut
Non je n'ai pas avancé sur le support de la 4.4 mais elle n'est qu'en stade "alpha".
Pas vue d'annonce du contraire.

Mais je comprends ton dilemne. Je vais voir si je peux trouver une piste rapide.

**Comment by kaleofr** [comment]
Je viens de tenter la déconseillée downgrade de 4.4 à 4.3.17 sans utiliser de backup... ca semble ok.
Donc plus d'urgence pour moi.
Par contre, j'avais configuré les mises à jour du Core sur Beta et non Alpha. La 4.4 semble donc être considérée comme une Beta.
Merci en tous cas.

**Comment by tcharp38** [comment]
230501-BETA-1 a tester.
@kaleofr 
je compte sur toi pour un faire un retour sur les regressions. Jai du changer pas mal de trucs au final

**Comment by tcharp38** [comment]
Je clos le sujet.
Pour moi c'est bon.
A reouvrir si besoin.

**Comment by kaleofr** [comment]
Je viens de repasser en 4.4.0
Les pages avancé et commandes sont de retour.
Par contre, en mode Dev, les boutons "Ajouter une commande info", "Ajouter une commande action" et "Ajouter une commande JSON" ne fonctionnent plus.

--> Alors retour en 4.3.17 et je me rend compte que ces boutons "ajouter" ne fonctionnent plus non plus en stable 
:-(

**Comment by tcharp38** [comment]
Non non attends.
Pourquoi utilises tu cette page.. et surtout ces bouton accessibles en mode dev uniquement.
Ca n'est pas normal.

**Comment by tcharp38** [comment]
Decompresser ce fichier dans Abeille/desktop/php
[Abeille-Js.zip](https://github.com/KiwiHC16/Abeille/files/11411847/Abeille-Js.zip)

ca devrait corriger ton souci meme si, je persiste, ce mode ne doit pas etre utilisé.
Si il manque des commandes c'est dans le modele et certainement pas un truc a faire "en dynamique".

**Comment by kaleofr** [comment]
Hello,
merci pour le fichier, il a résolu le problème.

> Non non attends. Pourquoi utilises tu cette page.. et surtout ces bouton accessibles en mode dev uniquement. Ca n'est pas normal.

Parce qu'il n'est TOUJOURS pas possible de choisir un modèle à appliquer à un device. 
Certe, on ne devrait jamais avoir à faire cela en théorie. Mais la théorie c'est pas la vraie vie.
J'ai des MS01 qui parfois se déclarent en 66666, hors c'est aussi le cas de TH01 chez d'autres. Tu as donc déclaré le 66666 comme alternateIds pour le TH01.
Bilan, mes MS01 capricieux se transforment de temps en temps en TH01... et ne me remontent évidement aucune température.
Il me faut donc supprimer les info Temp et Hydro et remettre une info etat.
Voila pourquoi.

Kaléo.

**Comment by tcharp38** [comment]
Je clos ce sujet d'incompatibilité.
Il devrait etre resolu depuis qq temps mais à réouvrir si ca n'est pas le cas.
