### ISSUE TITLE
ERREUR: Cmd ‹ cmd-0102 ›: Paramètre ‹ cmd › vide !

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2573]
Hello @tcharp38 ,
j'ai posé une question sur le forum jeedom, je pense que tu ne l'as pas vu 👍 
"Bonjour, tous les matins, j’ai le defaut " ERREUR: Cmd ‹ cmd-0102 ›: Paramètre ‹ cmd › vide ! " qui apparait. Quel log serait il interressant de fournir?
Je suis sur u RPI 3B+, v 4.3.17 , hdd Msata."

**Comment by tcharp38** [comment]
Salut @Proft1972 
Non je n'ai pas ce type d'erreur.
J'ai besoin au moins des los Cmd & Cmd-prev en esperant que le pb y soit. Sinon il faut reproduire avant de filer les logs.

**Comment by Proft1972** [comment]
> Salut @Proft1972 Non je n'ai pas ce type d'erreur. J'ai besoin au moins des los Cmd & Cmd-prev en esperant que le pb y soit. Sinon il faut reproduire avant de filer les logs.

Hello @tcharp38 ,

le probleme c'est que je n'ai que quelques minutes de log, quand je verifie, il est trop tard...
Pourtant, je suis à 5000 lignes de log.
Que faudrait il faire?

**Comment by tcharp38** [comment]
Files moi au moins le log "info clefs", via la page maintenance.
Je vais déja voir qui utilise la cmd-0102

**Comment by Proft1972** [comment]
voici le log:

[AbeilleKeyInfos.zip](https://github.com/KiwiHC16/Abeille/files/11214116/AbeilleKeyInfos.zip)

**Comment by Proft1972** [comment]
Je pense que c'est l'equipement 513 c'est un essai de volet, pour le moment il est débranché, c'est peut etre pour ca

**Comment by tcharp38** [comment]
Bien vu c'est lui

>     "142831": {"eqLogic_id":"513","eqType":"Abeille","logicalId":"Up","order":"2","name":"Up","configuration":"{\"topic\":\"cmd-0102\",\"request\":\"ep=01&cmd=\",\"visibiltyTemplate\":\"1\",\"RefreshData\":\"0\"}","template":"{\"dashboard\":\"core::default\",\"mobile\":\"core::default\"}","isHistorized":"0","type":"action","subType":"other","unite":"","display":"{\"invertBinary\":\"0\",\"showStatsOnmobile\":0,\"showStatsOndashboard\":0}","isVisible":"1","value":null,"alert":"[]","generic_type":""},
>     "142832": {"eqLogic_id":"513","eqType":"Abeille","logicalId":"Stop","order":"3","name":"Stop","configuration":"{\"topic\":\"cmd-0102\",\"request\":\"ep=01&cmd=\",\"visibiltyTemplate\":\"1\",\"RefreshData\":\"0\"}","template":"{\"dashboard\":\"core::default\",\"mobile\":\"core::default\"}","isHistorized":"0","type":"action","subType":"other","unite":"","display":"{\"invertBinary\":\"0\",\"showStatsOnmobile\":0,\"showStatsOndashboard\":0}","isVisible":"1","value":null,"alert":"[]","generic_type":""},
>     "142833": {"eqLogic_id":"513","eqType":"Abeille","logicalId":"Down","order":"4","name":"Down","configuration":"{\"topic\":\"cmd-0102\",\"request\":\"ep=01&cmd=\",\"visibiltyTemplate\":\"1\",\"RefreshData\":\"0\"}","template":"{\"dashboard\":\"core::default\",\"mobile\":\"core::default\"}","isHistorized":"0","type":"action","subType":"other","unite":"","display":"{\"invertBinary\":\"0\",\"showStatsOnmobile\":0,\"showStatsOndashboard\":0}","isVisible":"1","value":null,"alert":"[]","generic_type":""},

Je ne sais pas comment tu es arrivé dans cet etat mais si tu refais une "mise à jour" via la page avancé, ca ne resoud pas le souci ?

**Comment by Proft1972** [comment]
Hello @tcharp38 ,
comment fait on pour faiire une mise a jour depuis la page avancée? Depuis la config du plugin? j'ai peur de faire une betise!

**Comment by tcharp38** [comment]
Tu cliques sur ton equipement 513 et tu as un onglet "avancé".

Et enfin, suite au modele, tu as le bouton en question
![image](https://user-images.githubusercontent.com/35221038/231696373-a9a70c1c-05d8-4a2c-9d8d-d470b71f1197.png)

**Comment by Proft1972** [comment]
Je viens de le faire et je l'ai reactivé. quand il ét ait désactivé, je n'ai pas eu de défaut ;-)

**Comment by tcharp38** [comment]
Ok, tiens moi au jus.
Je te laisse fermer le sujet quand tu penses que c'est bon.

**Comment by Proft1972** [comment]
Hello @tcharp38 ,

Apparemment, après mise à jour, je n'ai plus de problèmes 😊😉

Je ferme et  le rouvrirai si besoin, encore merci👍

**Comment by tcharp38** [comment]
Ok. Une nouvelle beta sera dispo demain avec les derniers correctifs.
