### ISSUE TITLE
Message dupliqué 'click-middle'

### ISSUE THREAD

**Issue by Minisnaky** [KiwiHC16/Abeille#2574]
Bonsoir.
J'ai procédé à la dernière MAJ stable du plugin abeille.
Depuis, c'est tout cassé :(
- Sur les boutons "shortcut" IKEA, la commande est envoyée deux fois de suite à une seconde d'intervalle. Du coup, pour tous les scénarios avec un toggle sur une lampe, la lampe s'allume, puis s'éteint 1 secondes après (ou l'inverse).  Mes 10 boutons ont le même comportement depuis la MAJ.
- Sur les boutons IKEA ronds 5 touches, seules l'information UP-Down fonctionne (aucune réaction sur le click-middle ou LeftRight)... 
C'est embatant :/.  Les info existent toujours mais ne semble pas fonctionner, leur valeur ne change jamais.

J'ai tenté l'exclusion et inclusion de ces deux type d'équipements, mais même comportement.

Heeelp grand chef :)

**Comment by tcharp38** [comment]
Salut @Minisnaky 
On va se concentrer sur le shortcut.
Je ne pige pas "la commande est envoyée" deux fois.

Peux tu me filer le package de logs (maintenance/telecharger tout) et me donner l'adresse ou l ID d'un equipement en cause ?

**Comment by Minisnaky** [comment]
Salut @tcharp38 
Je te fais ça en fin d'aprem 😜

**Comment by Minisnaky** [comment]
Salut @tcharp38.
Désolé, je n'ai pas pu m'en occuper avant.
Je te joins les logs demandé.
Pour analyse, tu peux regarder l'equipement suivant 
- id Jeedom 288
- Abeille1/F4DF 
- F4DF / 680AE2FFFEF0A9DA

Au cas où, pour les tradfrii rond 5 boutons, l'équipement Abeille1/4ACE | 4ACE / 000D6FFFFE1D51A6 remonte les erreurs dans les logs sur les commande non bindées.

N'hésites pas si besoin. Merci encore.

[AbeilleLogs-230416.tar.gz](https://github.com/KiwiHC16/Abeille/files/11242890/AbeilleLogs-230416.tar.gz)

**Comment by tcharp38** [comment]
Salut
Je ne vois pas le phenomene.
Si j'ai bien compris, en cliquant sur le bouton tu recois 2 evenements cote Jeedom ?
Peux tu cliquer 1 fois et me filer les logs ?

**Comment by Minisnaky** [comment]
Salut :)
C'est exactement ca.
Je viens de faire la manipulation demandée.
J'ai clear les logs, et appuyé sur un shortcut ikea (Abeille1/5C9E - 5C9E / 84FD27FFFE17D80D). Le phénomène est toujours présent. Jeedom reçoit deux fois l'event click-middle avec une valeur à 1.
Du coup, coté logs du scénario lié j'ai ca : 
------------------------------------
[2023-04-19 15:59:38][SCENARIO] -- Start : Scenario execute automatiquement sur evenement venant de : [LOFT][Interrupteur Lampe Monde des Jeux 2][Click-Middle] (1).
[2023-04-19 15:59:38][SCENARIO] - Exécution du sous-élément de type [action] : action
[2023-04-19 15:59:38][SCENARIO] Exécution de la commande  [GEEKS WORLD][Lampe Monde des Jeux][Toggle]
[2023-04-19 15:59:38][SCENARIO] Fin correcte du scénario
------------------------------------
[2023-04-19 15:59:39][SCENARIO] -- Start : Scenario execute automatiquement sur evenement venant de : [LOFT][Interrupteur Lampe Monde des Jeux 2][Click-Middle] (1).
[2023-04-19 15:59:39][SCENARIO] - Exécution du sous-élément de type [action] : action
[2023-04-19 15:59:39][SCENARIO] Exécution de la commande  [GEEKS WORLD][Lampe Monde des Jeux][Toggle]
[2023-04-19 15:59:39][SCENARIO] Fin correcte du scénario

Je te joins les logs "épurés" après appuie du le shortcut
[AbeilleLogs-230419.tar.gz](https://github.com/KiwiHC16/Abeille/files/11273917/AbeilleLogs-230419.tar.gz)

Côté télécommande ronde ikea, on pourra aussi approfondir?

Merci chef!

**Comment by tcharp38** [comment]
J'ai trouvé un bug qui doit expliquer ton souci.

Decompresse ce code dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11276047/AbeilleParser.class.php.zip)

puis redemarre Abeille
et teste.

**Comment by tcharp38** [comment]
J'ai trouvé un bug qui doit expliquer ton souci.

Decompresse ce code dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11276047/AbeilleParser.class.php.zip)

puis redemarre Abeille
et teste.

**Comment by Minisnaky** [comment]
Salut @tcharp38 !
Manipulation faite. 
=> Ca refonctionne correctement! Tu gères la fougère l'ami :).

Pour les télécommandes rondes, on reste sur ce thread ou j'ouvre une autre issue?

**Comment by tcharp38** [comment]
Parfait.
Ouvre un autre sujet stp.
