### ISSUE TITLE
Volet Profalux plus reconnu du jour au lendemain

### ISSUE THREAD

**Issue by fichncheaps** [KiwiHC16/Abeille#2575]
Bonjour
Hier soir en fermant mes volets, un d'entre eux ne s'est pas fermé.
En regardant l'historique des commandes supprimées, on voit une suppression des commandes montées / descente... mais il reste 4 commandes basiques
J'ai tenté de le supprimer / recréer mais le volet revient dans le même état 
Je joins les 2 captures d'écran et les logs
Si vous avez une idée ou une explication je suis preneur
Merci et bonne journée
[AbeilleLogs-230415.tar.gz](https://github.com/KiwiHC16/Abeille/files/11239376/AbeilleLogs-230415.tar.gz)
![2023-04-15 12_58_03-Résumé - Jeedom](https://user-images.githubusercontent.com/95218439/232222684-bd57f0d3-c1f4-417b-83f2-b4b622bcbf34.png)
![2023-04-15 14_13_33-AbeilleEq - Jeedom](https://user-images.githubusercontent.com/95218439/232222699-dba5c407-cd98-43d7-8796-a72fb28185ef.png)
![2023-04-15 14_13_38-AbeilleEq - Jeedom](https://user-images.githubusercontent.com/95218439/232222702-70b31913-be13-4b4b-9938-b96427bf6ab0.png)

**Comment by Xav-74** [comment]
Hello @fichncheaps 

Ca m'est arrivé une fois également. Le volet a perdu son modèle (type = defaultUnknown).
Peux-tu installer la dernière beta du plugin et activer le mode développeur dans la partie configuration.
Ensuite tu vas sur l'onglet avancé de ton volet et tu devrais voir un bouton réparer.

![image](https://user-images.githubusercontent.com/56156622/232409640-3e02b4d0-6f19-467c-bb7a-aa7b412c36dc.png)

Clique desuus puis à l'issue, tu cliques sur mise à jour. Reviens sur la page Abeille et ton volet devrait avoir repris le bon type et recréé toutes les commandes ;)

Xav

**Comment by tcharp38** [comment]
Merci @Xav-74 
Rien à ajouter d'autre que... j'ai moi aussi eu ce souci. Ca doit etre specifique à "Profalux" mais je n'ai pas encore trouvé la faille, meme si j'ai une piste.

Je suggere d'appuyer sur "Réparer" plusieurs fois, en laissant 1 sec entre, jusqu'a l'annonce.

**Comment by fichncheaps** [comment]
Merci pour votre aide à tous les 2.
Effectivement en passant en mode développeur et en faisant réparer j'ai retrouvé mon volet!!!
