### ISSUE TITLE
Xiaomi bouton WXKG01LM non reconnu

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2577]
Salut,

j'essaie d'intégrer ce bouton qui doit pourtant correspondre à 
![image](https://user-images.githubusercontent.com/68732573/233671802-9c4652e5-7855-4791-a405-8b5300b9ff91.png)

mais rien à faire...
J'ai mis à jour ma pizigate (3.23-OPDM) + abeille beta

le log m'indique :
0064|[2023-04-21 16:40:16]DEBUG : msgFromParser(): Abeille1, permit join, status=01
0065|[2023-04-21 16:40:26]DEBUG : msgFromParser(): Leave indication for Abeille1/00158D0007DCA72A, rejoin=00
0066|[2023-04-21 16:40:26]DEBUG : msgFromParser(): WARNING: Device with IEEE 00158D0007DCA72A NOT found in Jeedom
0067|[2023-04-21 16:40:27]DEBUG : msgFromParser(): New device: Abeille1/0B98, ieee=00158D0007DCA72A
0068|[2023-04-21 16:40:27]DEBUG :   newJeedomDevice(Abeille1, addr=0B98)
0069|[2023-04-21 16:40:27]DEBUG : postSave()
0070|[2023-04-21 16:40:27]DEBUG : postSave()
0071|[2023-04-21 16:40:27]DEBUG : msgFromParser(): Attributes report by name from 'Abeille1/0B98/01
0072|[2023-04-21 16:40:27]DEBUG :   Unknown Jeedom command logicId='0000-01-0005'
0073|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-TimeStamp'
0074|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-Time'
0075|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Link-Quality'
0076|[2023-04-21 16:40:27]DEBUG : msgFromParser(): Attributes report by name from 'Abeille1/0B98/01
0077|[2023-04-21 16:40:27]DEBUG :   Unknown Jeedom command logicId='0000-01-0001'
0078|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-TimeStamp'
0079|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-Time'
0080|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Link-Quality'
0081|[2023-04-21 16:40:27]DEBUG : msgFromParser(): Attributes report by name from 'Abeille1/0B98/01
0082|[2023-04-21 16:40:27]DEBUG :   Unknown Jeedom command logicId='0000-01-FF02'
0083|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-TimeStamp'
0084|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Time-Time'
0085|[2023-04-21 16:40:27]DEBUG :   updateTimestamp(): WARNING: Abeille1/0B98, missing cmd 'Link-Quality'
...

Où pourrais être le problème? Tu as besoin de plus d'info?
Merci d'avance

**Comment by tcharp38** [comment]
Salut @fable73 
Toujours donner le package de logs (page maintenance + telecharger tout) pour voir ce qui se passe
et aussi savoir si tu es sur la stable ou sur la beta.

Le log montre que le device s'annonce bien mais l'inclusion semble s arreter en cours de route.
J'ai besoin de tous les logs juste apres ta tentative d'inclusion.
Inutile de le supprimer de Jeedom.

**Comment by fable73** [comment]
[AbeilleLogs-230421.tar.gz](https://github.com/KiwiHC16/Abeille/files/11297847/AbeilleLogs-230421.tar.gz)

Salut Tcharp38,
j'ai supprimé le device, vidé les log, redémarré Jeedom et re-fait l'inclusion + quelques tentatives de click...
Normalement il devrait pas y avoir des milliers de lignes...

le 38 = Isère? Si c'est le cas, on est physiquement pas loin... J'habite à Montmélian ;)

**Comment by tcharp38** [comment]
Pour mémo, inclusion interrompue suite à erreur interne

> [2023-04-21 19:03:26] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0000, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=EC43, DstAddrMode=02, DstAddr=0000
> [2023-04-21 19:03:26]   FCF=18/General/Serv->Cli, SQN=00, cmd=0A/Report attributes
> [2023-04-21 19:03:26]   AttrId=0005/ModelIdentifier, AttrType=42, ValueHex=6C756D692E73656E736F725F737769746368 => cleaned model, sensor_switch
> [2023-04-21 19:03:26]   decode8002_ReportAttribute() ERROR: Unexpected record size 2

Decompresser ce code dans plugin/Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11299465/AbeilleParser.class.php.zip)

puis redemarrer Abeille
et refaire inclusion.
Si ca ne fonctionne toujours pas, j'ai besoin du package de logs dans la foulée

**Comment by fable73** [comment]
Pas mieux... Voici les logs
[AbeilleLogs-230422.tar.gz](https://github.com/KiwiHC16/Abeille/files/11300976/AbeilleLogs-230422.tar.gz)

**Comment by tcharp38** [comment]
J'avoue que je ne comprends pas. Et j'ai rien pour faire des tests jusqu'au 26.
Je vois pas ce qui se passe pour l'instant.

Il faudrait que je te file un code avec un peu + de messages pour creuser. Je vais y reflechir.

**Comment by tcharp38** [comment]
Apres reflexion j'ai trouvé qq boulettes dans le code qui peuvent expliquer ton cas.
A decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11302089/AbeilleParser.class.php.zip)

puis redemarrer Abeille
refaire inclusion
et logs

**Comment by fable73** [comment]
tu es au top!!
Le bouton est là avec ses commandes.... il me reste plus qu'à tester.
Merci

**Comment by tcharp38** [comment]
Parfait. je pousse une nouvelle beta de suite.

**Comment by Jake309** [comment]
Ha, je vais pouvoir réessayer d'intergrer les miens, ca va peut être solutionner mon problème :)
Edit: a non, les rond sont ok, c'est le carré qui me pose des soucis. a voir

**Comment by tcharp38** [comment]
@fable73 
Tu l'as fermé volontairement donc plus de soucis. C'est bien ca ?

**Comment by fable73** [comment]
Oui j'ai pu faire ce que je voulais avec... notamment pour moi détecter le changement d'état.
Ca remonte bien les informations de batterie...
Donc c'est Ok pour mon utilisation... et je pense pour la majorité des usages...

![image](https://user-images.githubusercontent.com/68732573/235371454-27b160fb-6038-4159-8817-71c6a9147fa1.png)
