### ISSUE TITLE
Ajout IKEA TRÅDFRI LED 470 lm 4,2W E14 LED2101G4

### ISSUE THREAD

**Issue by ntatayet** [KiwiHC16/Abeille#2578]
Bonjour,

Je viens d'acquérir une ampoule IKEA TRADFRI LED 470 lm E14 4,2W ref LED2101G4.
Elle n'est pas reconnue par le plugin malgré la bonne intégration

<img width="860" alt="Capture d’écran 2023-04-21 à 19 06 59" src="https://user-images.githubusercontent.com/131478832/233694959-d49a533c-6ef4-4948-8162-e3877ad0eaa8.png">

J'ai mis les logs ici mais débutant avec le plugin, si il faut autre chose ne pas hésiter à me le dire.

[AbeilleLogs-230421.tar.gz](https://github.com/KiwiHC16/Abeille/files/11297875/AbeilleLogs-230421.tar.gz)

Merci d'avance pour le support et merci bcp pour le travail déjà accompli.
Cordialement,
Ntatayet

**Comment by tcharp38** [comment]
Salut @ntatayet 
Il me faut le discovery...
voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by ntatayet** [comment]
Salut,

Est-ce bien cela ?

[discovery-TRADFRIbulbE14WSglobe470lm_IKEAofSweden (1).json.zip](https://github.com/KiwiHC16/Abeille/files/11300689/discovery-TRADFRIbulbE14WSglobe470lm_IKEAofSweden.1.json.zip)

Merci d'avance,
Ntatayet

**Comment by tcharp38** [comment]
Pour test

A decompresser dans Abeille/core/config/devices
[TRADFRIbulbE14WSglobe470lm.zip](https://github.com/KiwiHC16/Abeille/files/11302098/TRADFRIbulbE14WSglobe470lm.zip)

puis redemarrer Abeille
et refaire inclusion

J'ai besoin 
- d'une ref fabricant
- d'une image PNG sans arriere plan à mettre en icone

**Comment by ntatayet** [comment]
Bonjour,

Merci, l'ampoule est bien reconnue mais seul le on/off fonctionne.

Je n'arrive pas à faire varier l'intensité
La gamme de couleur de cette ampoule est limitée à bleu jaune.
Surement à cause de l'erreur : " Abeille | Le fichier de commande 'act_setLevel-Light.json' n'existe pas."
Où puis-je trouver ce fichier et où dois-je le mettre svp ?

Sur leur site, ca correspond à [](https://www.ikea.com/fr/fr/p/tradfri-ampoule-a-led-e14-470-lumen-connecte-sans-fil-a-variateur-dintensite-spectre-blanc-globe-50486787/)

Il y aura également le visuel (je n'arrive pas à l'extraire en png avec mon ordi, désolée)

La ref fabriquant est la LED2101G4 (qui est absente de leur site internet)

Merci encore,
Ntatayet

**Comment by tcharp38** [comment]
Salut
Voila la commande manquante.

A decompresser dans core/config/commands
[act_setLevel-Light.zip](https://github.com/KiwiHC16/Abeille/files/11304180/act_setLevel-Light.zip)

Refaire une inclusion avant de tester.

Voila l'image dont il faut nettoyer l'arriere plan.
[node_Ikea-BulbE14-Globe.zip](https://github.com/KiwiHC16/Abeille/files/11304189/node_Ikea-BulbE14-Globe.zip)

**Comment by tcharp38** [comment]
Salut @ntatayet 
Toujours interessé par ce sujet ?

**Comment by tcharp38** [comment]
Plus de signe de vie.
Je ferme le sujet pas à réouvrir si il y a toujours des soucis et que ca interesse qqn.
