### ISSUE TITLE
Tuya capteur temp & humidité (id = TS0201, _TZ3000_xr3htd96)

### ISSUE THREAD

**Issue by bidoch78** [KiwiHC16/Abeille#2579]
Est-ce qu'il serait possible d'ajouter dans le fichier TS0201__TYZB01_hjsgdkfl.json l'alternateIds suivant :

"TS0201__TZ3000_xr3htd96": {
              "manufacturer": "Tuya",
              "model": "Display",
              "type": "Tuya temp/humidity display"				
}

J'ai fait la modif chez moi et ça fonctionne nickel.

![capteurtemp-ybi](https://user-images.githubusercontent.com/16101584/233858273-fde2722d-eeae-4406-b81f-74812ff45419.png)

Merci

**Comment by bidoch78** [comment]
Par contre je pense que ces capteurs sont des clones. On trouve différentes marques sur Amazon.
[Lien](https://www.amazon.fr/RANRAO-hygrom%C3%A8tres-temp%C3%A9rature-dhumidit%C3%A9-intelligent/dp/B0BPSVSJ5D/ref=mp_s_a_1_28?crid=1K6EVNUUEZWMA&keywords=capteur+humidit%C3%A9+zigbee&qid=1682281071&sprefix=capteur+humidit%C3%A9+zigbee%2Caps%2C128&sr=8-28)

**Comment by bidoch78** [comment]
[discovery_local.json.txt](https://github.com/KiwiHC16/Abeille/files/11409540/discovery_local.json.txt)

**Comment by tcharp38** [comment]
A tester avec ca
[TS0201__TZ3000_xr3htd96.zip](https://github.com/KiwiHC16/Abeille/files/11409945/TS0201__TZ3000_xr3htd96.zip)

Sera dans la beta de demain

**Comment by bidoch78** [comment]
Ok merci.
Est-ce qu'il y aura également l'image associée ?

**Comment by tcharp38** [comment]
Oui

**Comment by tcharp38** [comment]
Salut @bidoch78 
On peut clore ce sujet ou il reste des points ?

**Comment by bidoch78** [comment]
C'est tout bon tu peux cloturer.
Merci

**Comment by tcharp38** [comment]
Merci
