### ISSUE TITLE
ERREUR: bind0030: Invalid addr length (#IEEE#) après mise à jour plugin Abeille

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2580]
Hello @tcharp38 ,
apress chaque mise à jour du plugin Abeille, j'ai ce message,.
Saurais tu me dire ce qu il se passe avec ces logs ou te faut il  autre chose?
[AbeilleLogs-230424.tar.gz](https://github.com/KiwiHC16/Abeille/files/11307437/AbeilleLogs-230424.tar.gz)

**Comment by tcharp38** [comment]
Salut @Proft1972 
Tres etrange ce cas que je ne vois pas.
Je creuse.

**Comment by tcharp38** [comment]
Ce pb est issue d'une fonctionalité maintenant obsolete.
Peux tu faire une mise à jour de "[Volets][volet 1]" et me dire si le pb persiste ?

**Comment by Proft1972** [comment]
Hello,

J'ai bien fait une mise à jour, y a plus qu'à attendre une mise à jour et je te redirai!
Merci en tout cas!

**Comment by tcharp38** [comment]
Je clos le sujet que je considere ok mais à reouvrir si ca n'est pas le cas.
