### ISSUE TITLE
Ajout support Tuya controleur porte de garage (id = TS0601, _TZE200_nklqjk62)

### ISSUE THREAD

**Issue by thibault-78** [KiwiHC16/Abeille#2581]
Bonjour,
est il possible de prendre en compte ce matériel ?
merci par avance
[discovery-TS0601__TZE200_nklqjk62.zip](https://github.com/KiwiHC16/Abeille/files/11313151/discovery-TS0601__TZE200_nklqjk62.zip)
<img width="153" alt="Tuya Smart Zigequation" src="https://user-images.githubusercontent.com/65721947/234075584-b10d04bc-1854-4534-a192-104e63df6c49.png">

**Comment by tcharp38** [comment]
Salut @thibault-78 
Ce periph fait quoi ?
Il y a une marque ? Une reference de modele ?

**Comment by thibault-78** [comment]
Bonjour,
c'est un contacteur sec avec détecteur d'ouverture intégré pour les portes de Garage
La marque : Dongguan
Référence: PJ-ZGD01

https://fr.aliexpress.com/item/1005005257227550.html?spm=a2g0o.productlist.main.1.11781085u8y0El&algo_pvid=0bbf4197-b486-42bc-8347-eff72f4ba30a&algo_exp_id=0bbf4197-b486-42bc-8347-eff72f4ba30a-0&pdp_npi=3%40dis%21EUR%2144.44%2121.33%21%21%21%21%21%40211bf2da16825053971236178d0742%2112000032606659416%21sea%21FR%212887717497&curPageLogUid=TfsxYPbRBz8N

**Comment by tcharp38** [comment]
Pour test

A decompresser dans Abeille/core/config/devices
[TS0601__TZE200_nklqjk62.zip](https://github.com/KiwiHC16/Abeille/files/11360930/TS0601__TZE200_nklqjk62.zip)

A decompresser dans Abeille/core/config/commands
[inf_generic-Binary.zip](https://github.com/KiwiHC16/Abeille/files/11360943/inf_generic-Binary.zip)



puis redemarrer Abeille
refaire inclusion

Il n'ya  que 2 cmdes info pour l'instant

**Comment by thibault-78** [comment]
Bonjour @tcharp38 
merci pour le fichier
Le device est bien reconnu maintenant
L'info "door contact" semble bien fonctionner => Le statut change bien dès que l'on rapproche / éloigne l'aimant
je ne sais pas ce qu'est l'info Door trigger => Je suppose que ça devrait plutôt être la commande qui permet de faire le "contact sec" ?
Autre piste : le discovery n'est pas tout à fait complet:
je n'arrive pas à passer au vert le end Point F2
![image](https://user-images.githubusercontent.com/65721947/235720566-532e8300-09b8-43fc-ad32-efe442a58ad5.png)
Aurais-tu une idée?
Merci par avance

**Comment by tcharp38** [comment]
Salut
Laisse tomber le EP F2.. ca ne repond pas souvent chez Tuya.

Je ne sais pas ce qu'est "trigger".
A toi de me dire ce qu'il manque comme fonctionalité.

**Comment by thibault-78** [comment]
Hello 
Ok on oublie le EP F2 alors :)
Ce device doit faire 2 chose:
- détecteur d'ouverture de porte (ca c'est OK c'est la commande "Door contact" de type info)
- déclencher le contact sec pour ouvrir la porte de garage (que j'aurai supposé être la commande "Door Trigger")
Dans le json que tu m'as fait le "door trigger" est de type info. Ne devrait il pas être de type action => pour pouvoir piloter l'ouverture de la porte de garage.

**Comment by tcharp38** [comment]
Tiens, decompresse ce modele et fais une mise à jour à partir de la page avancé
[TS0601__TZE200_nklqjk62.zip](https://github.com/KiwiHC16/Abeille/files/11425164/TS0601__TZE200_nklqjk62.zip)

puis test open/close
et file moi les logs

**Comment by thibault-78** [comment]
Bonjour @tcharp38 
Je ne sais pas comment tu trouves les commandes et leurs noms, mais en tout cas c'est fonctionnel :)
-> Je m'attendais à avoir un seul bouton
En tout cas:
Le bouton "open" marche uniquement si "Door contact" indique "Fermé"
Le bouton "close" marche tant que "Door contact" indique "Ouvert"
Les seules modif que j'ai faites sont sur "door trigger":
 - inverser la valeur 
 - affichage widget type door

Est ce que la photo que je t'ai donnée est suffisante pour l'inclure dans la prochaine release? 
As-tu quand meme besoin des logs ? 

Merci beaucoup pour le travail effectué

**Comment by thibault-78** [comment]
dernière info: le "door trigger" change bien d'état quand on déclenche une action mais je ne comprend pas trop l'intéret

**Comment by tcharp38** [comment]
> Je m'attendais à avoir un seul bouton

Un "toggle" alors plutot que "ouvrir" et "fermer" ?

Tu confirmes que 
- "Door contact" c'est la valeur du capteur
- "Door trigger" ca doit etre la valeur du bouton mural

**Comment by thibault-78** [comment]
Oui je pensais qu'il n'y aurait qu'une seule commande type toggle mais les 2 boutons c'est parfait
je confirme Door contact est la valeur du capteur
Pour Door trigger : pour moi c'est l'historique des commandes (open/close) envoyées par le module : il n'y a pas de bouton physique connecté sur le module, le module se cable en // du bouton physique directement sur le moteur de la porte de garage. il n'est donc pas possible de récupérer l'état de ce bouton (hélas)

**Comment by tcharp38** [comment]
Alors le lien que tu as donné n est pas le bon.
On voit clairement un interrupteur mural sur une entrée "signal"
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/59802c98-4271-4b41-9edf-dd3286b2ee54)

Du coup pas d'entrée de ce type ? L'image n'est pas bonne ?

**Comment by tcharp38** [comment]
Donc 
"Door contact" c'est celui la qui donne un etat de la porte du coup les modifs d inversion et widget sont pour celui la et pas "door trigger". Correct ?

**Comment by thibault-78** [comment]
Oui c'est bien ca:
 Door Contact = état du capteur d’ouverture (modif Widget + inversion)

**Comment by tcharp38** [comment]
Je te laisse tester avec ce modele. Il te suffit d'ecraser le tient, et refaire une "mise à jour" via la page avancé.
[TS0601__TZE200_nklqjk62.zip](https://github.com/KiwiHC16/Abeille/files/11548238/TS0601__TZE200_nklqjk62.zip)

Apres quoi.. il reste quoi pour fermer ce sujet ?

**Comment by tcharp38** [comment]
@thibault-78 
Du nouveau ?
On peut clore ce sujet ?

**Comment by thibault-78** [comment]
Hello @Tcharp38
Désolé je suis en plein travaux chez moi et je ne peux pas tester :(
Je devrais pouvoir faire les tests dans un mois
Merci encore pour ton aide

**Comment by tcharp38** [comment]
Ok, pas de soucis. 
On garde le sujet ouvert.
Bons travaux.

**Comment by thibault-78** [comment]
Hello @tcharp38 
Je viens de le tester à l’instant 
Tout est fonctionnel :)

**Comment by tcharp38** [comment]
Hello

Merci. Je clos ce sujet alors.
A reouvrir si soucis.
