### ISSUE TITLE
Ajout Disjoncteur intelligent Tongou TO-Q-SY1-ZT (id = TS011F, _TZ3000_qeuvnohg)

### ISSUE THREAD

**Issue by thedrgraph** [KiwiHC16/Abeille#2583]
Hello,

Disjoncteur intelligent Tuya avec mesure, rail DIN Marque Tongou TO-Q-SY1-JZT
Il est reconnu comme prise commander voici l'image et le discovery 
Il devrait aussi pouvoir mesuré la consomation.
![TS011F_TZ3000_qeuvnohg](https://user-images.githubusercontent.com/19219121/234415497-85e1257a-e41a-422e-b352-75d9fb16b475.jpg)
[discovery-TS011F__TZ3000_qeuvnohg.json.txt](https://github.com/KiwiHC16/Abeille/files/11327190/discovery-TS011F__TZ3000_qeuvnohg.json.txt)

Merci

**Comment by thedrgraph** [comment]
Nota trouvé ici : https://fr.aliexpress.com/item/1005004747066832.html

**Comment by tcharp38** [comment]
Salut @thedrgraph 
Voila un modele preliminaire

A decompresser dans Abeille/core/config/devices
[TS011F__TZ3000_qeuvnohg.zip](https://github.com/KiwiHC16/Abeille/files/11360959/TS011F__TZ3000_qeuvnohg.zip)

Et l'image dans Abeille/images
[node_Tongou-DinCircuitBreaker.zip](https://github.com/KiwiHC16/Abeille/files/11360962/node_Tongou-DinCircuitBreaker.zip)
Je n'ai pas pris la tienne, trop basse qualité (illisible), format JPEG pas accepté. Il faut du PNG SANS arriere plan donc image à nettoyer. A toi la balle.

Redemarrer Abeille
refaire inclusion
tester...

**Comment by thedrgraph** [comment]
désolé j'ai été absent plusieurs jours 
J'ai retravailler l'image pour avoir un fond transparent 
![node_Tongou-DinCircuitBreaker](https://github.com/KiwiHC16/Abeille/assets/19219121/55c51041-abf5-4b34-82ed-f026f7c1295f)

**Comment by tcharp38** [comment]
Salut

Récupéré pour la prochaine beta.
En dehors de l'image... quel est le status ?

**Comment by thedrgraph** [comment]
Sorry pas eu le temp de tester j'espere ce week end pour voir la gestion de la conso

**Comment by thedrgraph** [comment]
Hello tous fonctionne pour ce model.

**Comment by tcharp38** [comment]
Super !
Je clos le sujet. A reouvrir si soucis
