### ISSUE TITLE
Ajout prise Tuya (id = TS011F, _TZ3000_y4ona9me)

### ISSUE THREAD

**Issue by thedrgraph** [KiwiHC16/Abeille#2584]
Bonjour pour ajout.

Fonctionne correctement on/off :)

[discovery-TS011F__TZ3000_y4ona9me.json.txt](https://github.com/KiwiHC16/Abeille/files/11341854/discovery-TS011F__TZ3000_y4ona9me.json.txt)

![prise](https://user-images.githubusercontent.com/19219121/234820123-80b83c58-ce2f-42c1-9a26-a7c3cde656d9.jpg)

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices
[TS011F__TZ3000_y4ona9me.zip](https://github.com/KiwiHC16/Abeille/files/11368329/TS011F__TZ3000_y4ona9me.zip)

puis redemarrer Abeille
refaire inclusion
tester

**Comment by tcharp38** [comment]
Salut @thedrgraph 
Quel est le status de ce sujet ?

**Comment by thedrgraph** [comment]
Désolé pour le délais, pas de soucis.
tous fonctionne parfaitement.

**Comment by tcharp38** [comment]
Ok merci bien.
Je clos mais  à reouvrir si soucis
