### ISSUE TITLE
problème affichage

### ISSUE THREAD

**Issue by toat** [KiwiHC16/Abeille#2587]
Salut,

je ne sais pas depuis combien de temps mais je n'ai plus de bouton sauvegarder/supprimer dans les équipements :
![image](https://user-images.githubusercontent.com/26632961/235990802-3807722a-cec5-4093-8f7f-61ba4f1a0fa8.png)

et au niveau des commandes, j'ai ca : 
![image](https://user-images.githubusercontent.com/26632961/235990920-458c8344-f9bd-4cc1-bdfb-0dbfe6fe1588.png)

J'ai essayé de restart le daemon et reboot le serveur mais ca change rien. J'ai essayé avec Edge, change rien.

Merci pour ton aide.
[AbeilleLogs-230503.tar.gz](https://github.com/KiwiHC16/Abeille/files/11385251/AbeilleLogs-230503.tar.gz)

**Comment by tcharp38** [comment]
Ma faute. Petite regression deja fixée.

Tu peux décompresser ce fichier dans Abeille/desktop/php
[Abeille-Eq.zip](https://github.com/KiwiHC16/Abeille/files/11390137/Abeille-Eq.zip)
et tester

Ca sera fixé dans la beta de demain.

**Comment by tcharp38** [comment]
@toat 
Du nouveau ?

**Comment by toat** [comment]
c'est bon avec la maj d'hier, merci
