### ISSUE TITLE
Telecommande 3 boutons LoraTap (id = TS0043, _TZ3000_yw5tvzsk)

### ISSUE THREAD

**Issue by Sososoja** [KiwiHC16/Abeille#2589]
Bonjour tcharp38,

J'ai un nouveau bouton pour lancer des scénarios, je pensai que ce serai reconnu comme la télécommande à 3 boutons, mais non pas de chance.
Ci joint une image et les logs.

Bon week end

![LoraTap](https://user-images.githubusercontent.com/105510886/236553216-0c78f88c-18f0-423a-912c-19c7667c81e7.png)
[AbeilleLogs-230505.tar.gz](https://github.com/KiwiHC16/Abeille/files/11409562/AbeilleLogs-230505.tar.gz)

**Comment by tcharp38** [comment]
Salut
Il me faut le discovery.
Tu t y colles ?

**Comment by Sososoja** [comment]
C'est vrai que avec le discovery, c'est mieu
Désolé

[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/11410608/discovery.json.txt)

**Comment by tcharp38** [comment]
Ca pourrait.. mais il est completement vide.

Tu dois lancer l assistant sur le device inconnu, et presser les boutons plusieurs fois pour reveiller la telecommande et avoir un max de "bouton verts": https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

**Comment by Sososoja** [comment]
Je viens de m'énerver un bon moment, mais aucuns end point, aucun cluster... Y'a rien qui remonte
C'est vraiment la loos...

**Comment by Sososoja** [comment]
y'a même pas de code fabricant ou de numéro de version, vraiment rien.

**Comment by tcharp38** [comment]
Jettes un œil dans devices_local, peut être qu'il y a un bout de discovery.

Abeille/core/config/devices_local

**Comment by Sososoja** [comment]
Il y a ça, mais y a pas grand chose dedans

[discovery.json.txt](https://github.com/KiwiHC16/Abeille/files/11415770/discovery.json.txt)

**Comment by tcharp38** [comment]
Effectivement, pas grand chose mais on sait maintenant comment il s'identifie: TS0043 + _TZ3000_yw5tvzsk

**Comment by tcharp38** [comment]
Peux tu faire un click sur chaque bouton, noter l'heure et me filer le package de logs ?

**Comment by Sososoja** [comment]
Voilà c'est fait
J'ai appuié sur les boutons à 20h57 espacé de 3 secondes environ

[AbeilleLogs-230509.tar.gz](https://github.com/KiwiHC16/Abeille/files/11435102/AbeilleLogs-230509.tar.gz)

**Comment by tcharp38** [comment]
Decompresse ce fichier par dessus son original (Abeille/core/config/devices/TS0043__TZ3000_bi6lpsew)
[TS0043__TZ3000_bi6lpsew.zip](https://github.com/KiwiHC16/Abeille/files/11439637/TS0043__TZ3000_bi6lpsew.zip)

redemarre Abeile
refais une inclusion

**Comment by Sososoja** [comment]
Voilà c'est fait et ça fonctionne nickel, il reconnais bien les apuis simple, double et long

Merci beaucoup encore une fois

**Comment by tcharp38** [comment]
Parfait.
On peut fermer le sujet du coup ?

**Comment by Sososoja** [comment]
oui, merci encore
