### ISSUE TITLE
Problème lors appui court sur TRÅDFRI Shortcut Button depuis mise à jour 230326-STABLE-1 du plugin

### ISSUE THREAD

**Issue by sebgeekinside** [KiwiHC16/Abeille#2590]
Suite à installation de la version 230326-STABLE-1, je constate une régression dans le comportement du plugin lors d'un appui court sur TRÅDFRI Shortcut Button.
L'appui est bien détecté (commande Click-Middle prend la valeur 1).
Cependant, dans la foulée, la commande Click-Middle est répétée en prenant à nouveau la valeur 1. Peut-être est-ce lié au relâchement du bouton après l'appui ?

Voici le package de logs qui trace un appui court à [2023-05-12 14:43:55].
Dans AbeilleParser.log, on constate des traces à [2023-05-12 14:43:55] (suite à appui court) et dans la foulée, on constate également des traces à [2023-05-12 14:43:56]. Ces secondes traces semblent correspondre à ce qui entraine la répétition de valeur 1 de la commande Click-Middle.

[AbeilleLogs-230512.tar.gz](https://github.com/KiwiHC16/Abeille/files/11464056/AbeilleLogs-230512.tar.gz)

**Comment by tcharp38** [comment]
Salut @sebgeekinside 
Il y a effectivement un bug sur la stable qui semble deja corrigé depuis un moment sur la beta.

Si tu veux tester decompresse ce fichier dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/11559367/AbeilleParser.class.php.zip)

pense à mettre l'original de coté au cas ou.

Puis redemarre Abeille

J'espere pousser une nouvelle stable dans la semaine mais peu d'utilisateurs de la beta pour me faire des retours.

**Comment by sebgeekinside** [comment]
@tcharp38,  suite à installation de la version STABLE du 2023-05-29, je ne constate plus le bug objet de cet issue !
