### ISSUE TITLE
Lenteur Importante entre les actions sur l'interface web et l'execution réelle 

### ISSUE THREAD

**Issue by Jorael57** [KiwiHC16/Abeille#2591]
Pour faire suite à mon problème de lenteur.
Exemple : il faut presque 1minute entre la demande de passer la zigate en mode inclusion et le moment ou elle se met à clignoter .
Pareil pour l'allumage des lumières via des boutons zigbee déportés.

Je ne sais pas si le problème vient de la zigate ou du plugin ou de jeedom ou encore de l'OS.

Info : Containeur Linux Debian pour Jeedom
Host : Proxmox 
USB:  Zigate en "passtrough" vers le container 
Fonctionner sans soucis jusqu'à il y a quelques semaines.

Côté ressource système il ne semble pas y avoir de problème de CPU ou de RAM.

**Comment by tcharp38** [comment]
Salut
Peux tu faire une de ces actions qui prend du temps
et me filer le package de logs qq mins apres ?

**Comment by tcharp38** [comment]
Pour info je soupconne que cette lenteur est due à un de tes equipements qui ne repond pas ou est regulierement difficilement joignable. Ca bloque les autres requetes pendans qq sec

**Comment by tcharp38** [comment]
Salut @Jorael57 
Que fait on avec ce sujet ? Des news ?

**Comment by Jorael57** [comment]
@tcharp38 
Désolé je suis pas mal occupé en ce moment et j'ai laissé ça de côté. j'essaye de faire ça d'ici 15 jours

**Comment by tcharp38** [comment]
Aucune urgence.
je relancerai d'ici la rentrée pour refaire le point.
Bonnes vacances

**Comment by Jake309** [comment]
J'ai déjà eu le pb, c'était un équipement qui était sur la fin.
Peu de temps après qu'on ait identifié le fotif il a péri ^^
Après un reboot, si ya toujours des lenteurs, c'est forcément un équipement qui fou le réseau en caraf

**Comment by tcharp38** [comment]
Oui, une faiblesse d'Abeille que je connais.

Quand un equipement n'est pas joignable, et à cause du fait que la Zigate ne traite qu'un seul message à la fois, cette derniere reste bloqué jusqu'a "timeout".. donc 7sec.
Donc tout equipement en NO ACK peut ralentir profondement les actions.
La page santé affiche maintenant cet état de "NO ACK".

**Comment by tcharp38** [comment]
@Jorael57  @Jake309 
J'avais poussé dans une des dernieres beta qqch qui passe un device en "NO ACK" en basse priorité.
Ca permet de ne plus ralentir les autres en bloquant le reseau. Du coup ca doit améliorer ces soucis.

Je clos le sujet mais à reouvrir si besoin.
