### ISSUE TITLE
Reprise domotique 

### ISSUE THREAD

**Issue by baloo53** [KiwiHC16/Abeille#2596]
Bonjour,

Je viens vers vous pour un peu d’aide pour la reprise de ma domotique. Ca fait quelque mois que j’avais tout laissé de coter suite à une mise a jour qui après l’avoir effectué avait rendu inerte mes équipements.
Donc j’aimerais relancer la machine ^^ Je suis dans la même configuration avec le plugin abeille.

Pour information j’ai jeedom installé sur un raspberry en SSD
J’ai une clé zigate avec le firmware 0004-0321 et quand je test le port via le plugin sa m’indique que c’est OK
J’ai les dernières mises à jours officiel du plugin et de jeedom

Voici les log en mode debug:
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/11646304/AbeilleParser.log)
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/11646305/AbeilleCmd.log)
[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/11646306/AbeilleConfig.log)

Voici le message d’erreur que j’ai lorsque je veux utiliser un de mes équipements:
ERREUR: Cmd ‹ cmd-0102 ›: Paramètre ‹ cmd › vide !
Suite à sa j'ai suivi ce topic qu'on ma recommandé [https://github.com/KiwiHC16/Abeille/issues/2573](url)
Avec cette procédure j'ai plus de message d'erreur mais mes équipements ne fonctionne toujours pas :/ 

Pour information dans la partie "Réseau abeille" du plugin quand je vais un rafraichissement, aucun équipement est remonté 

Merci d'avance pour votre aide

**Comment by baloo53** [comment]
Je sais pas si sa peut aider mais j'ai fais quelques tests.
J'ai essayé de me mettre en mode intégration. J'ai remarqué que les LEDs vertes sur mes équipements Legrand étaient éteinte. J'ai donc essayé d'appuyer un seul fois sur le bouton reset de l'un d'eux. Juste un click. Et la tout mes équipements sont passés en vert.
Je referme l'intégration et teste de nouveau de manipuler un équipement mais rien se passe :/ j'ai essayé de redémarrer jeedom et relancer les demons et toujours rien :/

Voilà petit teste supplémentaire mais toujours bloqué :/

**Comment by tcharp38** [comment]
Salut @baloo53 

Pour tout support j'ai besoin du pacakge de logs généré via la page maintenance/telecharger tout.
Donc mode debug, et 5000 lignes de log au moins. La tu n'as que 500 lignes. Bien trop court.

Ceci etant, le device qui genere cette erreur "ERROR: Cmd 'cmd-0102': Paramètre 'cmd' vide !" est le 9741.
Je te suggere de recharger le modele via sa page "avancé"... comme suit
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/38798d3e-ff79-4467-a5df-d7aa23eae86e)

**Comment by baloo53** [comment]
Je te télécharge les logs ce soir. Tu a besoin d'une manipulation en particulière ?

Oui pour le code erreur j'ai fais les mises à jour. J'ai plus le code d'erreur en revanche sa a pas débloqué la situation :/

**Comment by baloo53** [comment]
j'ai fais sa je sais pas si c'est suffisant 

[AbeilleLogs-230605.tar.gz](https://github.com/KiwiHC16/Abeille/files/11651183/AbeilleLogs-230605.tar.gz)

**Comment by tcharp38** [comment]
C'est mieux mais les logs sont trop courts.
Voir https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

Je vois que tous tes equipements sont en timeout.
Ca a déja fonctionné avant ? Si oui qu'as tu changé ?
Ha je vois que tu dis aussi "pas d'équipement detecté via le refresh reseau"... donc ca vient de ta zigate. Qu'as tu fait dessus ? Une mise à jour FW ? Si oui comment ?

**Comment by baloo53** [comment]
Et bien j'ai rien fais du tout. A l'époque tout fonctionnait très bien et j'ai effectué une mise à jour jeedom et abeilles et plus rien fonctionnait. J'avais déjà rencontré des problèmes à l'époque que j'ai pu résoudre avec de l'aide sur le forum jeedom mais du coup cette fois la j'en avait marre pour être honnête.
Mon système est resté je dirais 6mois éteint. 
Ma zigate fonctionne correctement et je suis sur un firmware 0004-0321

**Comment by baloo53** [comment]
Voici des log plus long, j'ai modifié à 5000 lignes 
[AbeilleLogs-230605 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/11657507/AbeilleLogs-230605.1.tar.gz)

**Comment by tcharp38** [comment]
Ce qui me chagrine c'est qu'aucun equipement ne soit connu de la zigate (refresh reseau vide).
Pour moi cette situation n'est possible que si tu as fait une mise à jour du FW avec effacement de la PDM.
Ca te parle ?

Du coup à ce stade je te suggere
- de basculer en FW 3.23 OPDM.. (donc 0004-0323). C'est le dernier de la v1 et le + avancé
- effacer la PDM via la page avancé de la zigate
- refaire une inclusion de tes devices ou commencer juste par 1 pour voir comment ca se comporte

Qu'en penses tu ?

**Comment by baloo53** [comment]
J'ai déjà fait une mise à jour du firmware à l'époque et tout c'était bien passé. Maintenant que j'y pense une fois sa m'étais arrivé et j'avais juste changé de port usb et c'est reparti (j'ai pas fais le test encore)
Refaire une inclusion sa me chagrine un peut mes équipements sont dans les murs pour certains et c'est vraiment pas pratique :/ surtout que j'ai une vingtaine d'équipements.
Je peux quand même faire la maj sans efface la PDM c'est toujours possible sa

Et à l'époque sa m'arrivait souvent d'avoir la table de réseau vide. Je fesais un redémarrage de jeedom puis pareil sur le demon du plugin abeille et c'est reparti. C'est pour sa que j'ai arrêté un moment car j'en avais marre de relancer mon système comme sa a chaque fois

**Comment by tcharp38** [comment]
Je comprends bien ton agacement au vu de ton historique.

Mais la si la Zigate dit qu'elle ne connait aucun equipement je vois pas comment c'est possible autrement qu'un effacement de la PDM..

Peux tu juste faire un refresh reseau et me filer le package de logs ?

**Comment by baloo53** [comment]
Pour information, j'ai changer de port USB sur mon hub et sa refonctionne. Comme je les évoqué plus haut, sa met déjà arrivé en revanche j'ai aucune explication :/

**Comment by tcharp38** [comment]
Ok alors perturbations electriques.
Il y a de nombreux post sur le sujet autour des RPI4 en particulier et SSD.

Du coup tout est revenu en ordre ?

**Comment by baloo53** [comment]
Oui sa à l'air :) je vais voir maintenant pour mettre ma zigate à jour comme tu ma évoqué qu'elle ne l'était pas.
Et aussi voir pour mettre mes équipements Legrand aussi à jour si je trouve les firmwares pour passer en AOT sinon je le ferais pas.

En tout cas merci de ton aide. :)

**Comment by tcharp38** [comment]
Je te conseille d y aller progressivement histoire de pouvoir identifier les eventuels soucis.
Donc pas tout à la fois.

En gros tu laisses du temps entre tes changements (ex 1 jour) pour t assurer que tout est encore ok.

**Comment by baloo53** [comment]
Oui je vais déjà faire la maj de la clé zigate car mes équipements Legrand sa a l'air extrêmement compliqué de trouver les firmwares ou alors faut passer par la passerelle officielle et donc faire une exclusion :/

**Comment by tcharp38** [comment]
Tu en es ou ?
Pourquoi d'ailleurs veux tu mettre à jour tes equipements Legrand ? Si ca fonctionne comme ca inutile de changer leur FW.

**Comment by baloo53** [comment]
Je met à jour gentiment mes équipements Legrand.
Je le fais car je me dis que sa peut apporter de nouvelles fonctions et de la stabilité ^^
Tout se passe bien pour l'instant.
J'ai pas encore fait la maj de ma clé zigate, il faut que je me trouve une bonne procédure et que je trouve le FW. J'ai pas envie de faire de bêtises ^^

**Comment by tcharp38** [comment]
Salut @baloo53 
Ou en es tu ?

**Comment by tcharp38** [comment]
Salut @baloo53 
Aucune nouvelle depuis qq temps. Je clos le sujet mais à réouvrir si besoin.
