### ISSUE TITLE
Contrôleur d'arrosage - WOOX : pas de remontée des informations de la batterie

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2599]
Bonsoir,
j'ai mis en place cette vanne connectée... je n'ai pas de remontée des informations de batterie (% ou tension)
Si tu peux regarder... dans le json du fichier correspondant "TS0101__TZ3210_eymunffl" il y a bien 

            "Battery-Percent": {
"use": "inf_zbAttr-0001-BatteryPercent"
            },

mais ça remonte rien...

j'ai trouvé aussi ce sujet sur le forum Jeedom... plugin Zigbee, pas le tien... mais incapable d'arriver à en faire quelque chose...
https://community.jeedom.com/t/recuper-donnee-piles-controleur-arrosage-woox-r7060/84232/2

Je suis toujours en version beta....

**Comment by tcharp38** [comment]
Salut

Voila un nouveau modele a essayer

A decompresser dans Abeille/core/config/devices/TS0101__TZ3210_eymunffl
[TS0101__TZ3210_eymunffl.zip](https://github.com/KiwiHC16/Abeille/files/11910651/TS0101__TZ3210_eymunffl.zip)

puis refaire une inclusion et tester.

Si ca ne change rien, merci d activer le mode debug et fournir un package de logs (voir https://kiwihc16.github.io/AbeilleDoc/Debug.html#support)

**Comment by fable73** [comment]
Salut,
Dsl pas eu le temps de tester avant...
Pas mieux 
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/7da82826-ee87-4548-b8fa-54f29153c65d)

[AbeilleLogs-230702.tar.gz](https://github.com/KiwiHC16/Abeille/files/11929680/AbeilleLogs-230702.tar.gz)

Voici le package de logs...

**Comment by tcharp38** [comment]
Nouveau test.

J'ai encore vidé le modele pour suivre ce qui est fait chez "zigbee-herdsman-converters".
[TS0101__TZ3210_eymunffl.zip](https://github.com/KiwiHC16/Abeille/files/11931491/TS0101__TZ3210_eymunffl.zip)

**Comment by fable73** [comment]
[AbeilleLogs-230703.tar.gz](https://github.com/KiwiHC16/Abeille/files/11933291/AbeilleLogs-230703.tar.gz)

Pas mieux... :(

**Comment by tcharp38** [comment]
La je seche mais il doit y avoir un  report via le cluster privé.

Nouvelle tentative.
Tu peux juste faire une "mise à jour" via la page "avancé".
[TS0101__TZ3210_eymunffl.zip](https://github.com/KiwiHC16/Abeille/files/11934588/TS0101__TZ3210_eymunffl.zip)

**Comment by fable73** [comment]
[AbeilleLogs-230703.tar.gz](https://github.com/KiwiHC16/Abeille/files/11939674/AbeilleLogs-230703.tar.gz)

Voici le log... après ce contrôleur d'arrosage est sur batterie... j'ai essayé tout de suite de le faire fonctionner à la main. J'espère que ça le "réveille"...

**Comment by tcharp38** [comment]
Trop court pour voir si ca fait effet.
Tu as vu du nouveau ?
Peut etre peux tu mettre le device en "surveillance" et me filer le log AbeilleMonitor apres qq heures

**Comment by fable73** [comment]
Salut,
Désolé pas eu le temps cette semaine... Je viens de faire un log de quelques heures... 
[AbeilleLogs-230708.tar.gz](https://github.com/KiwiHC16/Abeille/files/11992251/AbeilleLogs-230708.tar.gz)
Qd tu disais "surveillance"... tu pensais à quelque chose de particulier???

a+

**Comment by tcharp38** [comment]
Salut

Sur la page de gestion ou tu vois tous les equipements tu peux selectionner ton controller et cliquer sur "surveiller".
Ca va generer un "AbeilleMonitor.log" avec tous les echanges de/vers ce periph.

Concernant ton log je ne vois toujours pas le retour que j'attends qui permettrait de donner une valeur de batterie :(

**Comment by fable73** [comment]
[AbeilleLogs-230710.tar.gz](https://github.com/KiwiHC16/Abeille/files/12007689/AbeilleLogs-230710.tar.gz)
Voilà j'ai fait ça ce soir.... Normalement l'arrosage a du se mettre en route à 22h00 et s'arrêter à 22h30...
Merci en tout cas pour ton aide au top

**Comment by tcharp38** [comment]
Salut @fable73 
Désolé, je n'avais pas vu ta réponse.
Peux tu mettre à jour ta beta ? Il y a eu plusieurs avancées depuis dont une qui m'interesse pour ce sujet.

Il me faudra le package de logs apres 30 mins au moins

**Comment by fable73** [comment]
Salut,
Pas de soucis... je vais te faire attendre aussi 😉
je te fais ça fin août... je suis en vadrouille...
A+
Eric

**Comment by tcharp38** [comment]
:)
Bonne balade

**Comment by fable73** [comment]
Oups, le retour de vacances a été plus dur que prévu ;-)
J'ai pris le temps cet après-midi de ré-installer ce device (j'ai la dernière beta) et de te faire un long log...
Après si ça donne rien...
[AbeilleLogs-231007.tar.gz](https://github.com/KiwiHC16/Abeille/files/12838922/AbeilleLogs-231007.tar.gz)

**Comment by tcharp38** [comment]
Salut @fable73 
Je pense que le souci vient toujours d'un message specifique Tuya que je ne sais pas encore comment traiter.
Ca doit etre en ligne avec ce sujet https://github.com/KiwiHC16/Abeille/issues/2600

Mais vu que le sujet est assez vieux et que j'ai trop de trucs en tete, tu me confirmes que quand tu manipules ON/OFF tu as bien un retour de status ? Du coup il ne manque que le retour de batterie n'est ce pas ?

**Comment by fable73** [comment]
Salut @tcharp38,
Je te confirme qu'avec le ON et OFF j'ai bien le retour de statut... que je les actionne depuis Jeedom ou directement physiquement depuis le contrôleur... Donc effectivement, il ne manque que le % de batterie...

**Comment by fable73** [comment]
@tcharp38 
Au top 👍 
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/841af08a-b345-4f7e-9e8c-b50cd646a1f2)

Nickel...

Est-ce que je ferme le topic???

**Comment by fable73** [comment]
problème résolu !

**Comment by tcharp38** [comment]
Salut @fable73 
Peux tu placer cet equipement en surveillance et me filer le package de logs apres 1 à 2H par ex ?
Merci

**Comment by fable73** [comment]
[AbeilleLogs-231015.tar.gz](https://github.com/KiwiHC16/Abeille/files/12910568/AbeilleLogs-231015.tar.gz)
@tcharp38 
Voici le package de logs...

**Comment by tcharp38** [comment]
Je regarde. Merci
Tu es sur que le reporting de la batterie est fait regulierement ?

Le log monitor est pour l'instant trop court. Je ne vois pas quand remonte l'info de batterie.

**Comment by fable73** [comment]
[AbeilleLogs-231016.tar.gz](https://github.com/KiwiHC16/Abeille/files/12919256/AbeilleLogs-231016.tar.gz)
Je t'ai mis le log après quasiment une journée...

Pour la fréquence de reporting de la batterie... aucune idée... mais j'ai l'impression que ça rafraichit... rarement...
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/1875848d-d135-4282-8d06-0f7e27638e08)
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/26ac5a33-564b-48f3-9e1c-a29e972d8f51)

A priori dernière com à 16h44... alors qu'il est 18h23... donc normal qu'hier avec en gros une heure de log tu n'es rien vu passer...

**Comment by tcharp38** [comment]
Ok je vois un reporting toutes les 4H mais il y en a bien un.
Apres tout la batterie n'est pas supposée changer en aussi peu de temps donc c'est plutot intelligent.

    [2023-10-16 08:39:30] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=EF00, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=D8ED, DstAddrMode=02, DstAddr=0000
    [2023-10-16 08:39:30] <=   FCF=09/Cluster-specific/Serv->Cli, SQN=58, cmd=06/Unknown-EF00-06
    [2023-10-16 08:39:30] <=   TY_DATA_SEARCH: 049B6502000400000057
    [2023-10-16 08:39:30] <=   Dp=65, Type=02, Len=0004, ValueHex=00000057 => 'rcvValue' => '0001-01-0021'=87
    
    [2023-10-16 12:41:41] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=EF00, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=D8ED, DstAddrMode=02, DstAddr=0000
    [2023-10-16 12:41:41] <=   FCF=09/Cluster-specific/Serv->Cli, SQN=5A, cmd=06/Unknown-EF00-06
    [2023-10-16 12:41:41] <=   TY_DATA_SEARCH: 049C6502000400000057
    [2023-10-16 12:41:41] <=   Dp=65, Type=02, Len=0004, ValueHex=00000057 => 'rcvValue' => '0001-01-0021'=87
    
    [2023-10-16 16:44:05] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=EF00, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=D8ED, DstAddrMode=02, DstAddr=0000
    [2023-10-16 16:44:05] <=   FCF=09/Cluster-specific/Serv->Cli, SQN=5C, cmd=06/Unknown-EF00-06
    [2023-10-16 16:44:05] <=   TY_DATA_SEARCH: 049D6502000400000057
    [2023-10-16 16:44:05] <=   Dp=65, Type=02, Len=0004, ValueHex=00000057 => 'rcvValue' => '0001-01-0021'=87

Du coup on peut fermer ce sujet ?

**Comment by fable73** [comment]
Oui, Je l'avais déjà fermé... 
Mais comme ça, on a une info de plus...
En tout cas, beau boulot! merci !!!
