### ISSUE TITLE
AbeilleMQTTCmd.php semble ne pas processer tous les messages

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#26]
Sur client getEtat Ikea Bulb, AbeilleMQTTCmd.php ne reagit pas à tous les coups alors que je vois les messaages dans mosquitto.

**Comment by KiwiHC16** [comment]
Faire une verification du nombre de process (group de 3 php /dev/ttyUSB0) qui tourne en arrière plan. Si duplication alors problème. Doit arrêter et relancer qu'une instance.

**Comment by edgd1er** [comment]
C fait. daemon_info remonte  nok si pb. Le plugin passe au rouge si pb dans configuration.

**Comment by KiwiHC16** [comment]
Inclus dans les dernières modifications d 'edgd1er.
