### ISSUE TITLE
Impossible d'associer correctement certains devices auparavant sans problème, alors que d'autres identiques sont inclus correctement.

### ISSUE THREAD

**Issue by 8Thomas8** [KiwiHC16/Abeille#2604]
Bonjour.

Il semble impossible depuis quelques temps d'associer les modules Aquara temp/humidity/pressure sensor ([exemple](https://fr.aliexpress.com/item/1005004888285918.html?spm=a2g0o.ppclist.product.4.2fba2f992f995V&pdp_npi=2%40dis%21EUR%2116%2C21%E2%82%AC%2112%2C31%E2%82%AC%21%21%21%21%21%40211b446316895476831586783e6946%2112000032317748297%21btf&_t=pvid%3A21b02530-3e92-468b-bf55-d7b292fb4137&afTraceInfo=1005004888285918__pc__pcBridgePPC__xxxxxx__1689547683&gatewayAdapt=glo2fra)).

J'ai essayé les 2 dernières stables et j'ai l'impression que le problème existait déjà. J'ai également essayé avec 2 modules différents.

Il s'agit de modules qui étaient jusqu'à présent associés. L'un a perdu l'association , et le second, je l'ai supprimé moi même pour tester, car je n'arrivais plus à associer le premier.

**Comment by tcharp38** [comment]
Salut @8Thomas8 
Pour toute demande de support il me faut le package de logs => https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

En l'occurence il me faudrait les logs apres une tentative d'inclusion.

Concernant ce capteur, j'en ai moi meme un paquet et j'ai recemment reinclu la plupart sans soucis.
File moi les logs qu'on regarde ce qui se passe.
Merci

**Comment by 8Thomas8** [comment]
Salut @tcharp38 , désolé j'ai été un peu vite hier soir ...

**Hardware :**
- RPI 4 4Go
- Jeedom 4.3.17

**Gateway :**
- PiZigate
- Firmware 0004-0323

**Logs :**
- [Abeille.log](https://github.com/KiwiHC16/Abeille/files/12074311/Abeille.log)
- [AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/12074306/AbeilleConfig.log)
- [AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/12074307/AbeilleCmd.log)
- [AbeilleSerialRead1.log](https://github.com/KiwiHC16/Abeille/files/12074308/AbeilleSerialRead1.log)
- [AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/12074309/AbeilleParser.log)

N'hésite pas si besoin d'autre chose.

Pour le contexte, je n'ai pas plus d'info que dans le 1er post. Je n'ai rien ajouté, modifier, que ce soit niveau config, hardware, ou environnement / matériel associé.

**Comment by tcharp38** [comment]
Salut

2 choses
- inutiles de t embeter à mettre les logs 1 par 1. Page maintenance + telecharger tout. C'est un package bien + complet et tout fait. Juste un drag & drop ici et ca roule
- tes logs me semblent un peu courts. Je vois une annonce à 2023-07-18 00:53:07 et le log s arrete à 2023-07-18 00:53:37

Quoi qu'il en soit j'ai ce type de device.
Je vais refaire un essai pour voir.

**Comment by 8Thomas8** [comment]
J'ai reset les logs, redémarré Abeille et fait l'association avant de transmettre ces logs.

Je peux refaire une asso ce soir et te donner le fichier complet.

Je n'arrive pas à savoir exactement depuis quand j'ai ce problème. Les sondes qui sont toujours associées fonctionnent sans problème, mais si elles perdent l'association, volontairement ou non, impossible de les ré associer.

**Comment by tcharp38** [comment]
Attention !!
Cette generation de capteurs Xiaomi a de gros defauts. En particulier lorsqu'ils perdent la connexion il quittent le reseau d'eux meme et NE REVIENNENT JAMAIS. Bref si pas de tres bonne couverture c'est de la daube.

Ha mais attends.. ton log montre un truc interessant:

> [2023-07-18 00:53:11] Abeille1, Type=004d/Device announce, Addr=B9CB, ExtAddr=00158D0002B35644, MACCapa=80, Rejoin=00
> [2023-07-18 00:53:11]   eq={"ieee":"00158D0002B35644","macCapa":"80","rxOnWhenIdle":0,"manufCode":null,"rejoin":"00","status":"identifying","time":1689634387,"endPoints":null,"mainEp":"","manufId":null,"modelId":null,"location":null,"jsonId":"","jsonLocation":"","tuyaEF00":null,"customization":null,"xiaomi":null}
> [2023-07-18 00:53:11]   Requesting active end points list
> [2023-07-18 00:53:11]   NXP based device. Requesting modelIdentifier from EP 01
> [2023-07-18 00:53:14] Abeille1, Type=8011/APS data ACK, Status=A7/NO_ACK, Addr=B9CB, EP=00, ClustId=0005, SQNAPS=41

On voit une annonce du device
Abeille l'interroge dans la foulée
mais déja il ne repond plus

Donc pour moi tu as 
- un souci de batterie
- un pb de couverture reseau
- voir un pb de perturbation reseau (d'ailleurs je constate que tu es sur le canal 20 c'est normal ?)

**Comment by 8Thomas8** [comment]
Coté batterie c'est éliminé, j'ai testé avec pile neuve.
Coté couverture, en étant à proximité, pas mieux.

Pour le reste, je n'ai jamais changé de canal depuis 2/3 ans. Et la perturbation réseau à voir, c'est possible, je vais voir comment je peux éliminer / confirmer ça.

J'ai l'impression que parfois, le capteur apparaît dans les périphériques associés, mais sans être définie comme étant tel ou tel périphérique.

**Comment by tcharp38** [comment]
Ok alors voir avec le canal.
Generalement le 11 reste le + standard mais peut etre qu'il y a eu une boulette au fil des versions d'Abeille.

**Comment by 8Thomas8** [comment]
Impossible de changer de canal via l'interface. Il va falloir que je regarde comment faire autrement.

Voici les logs, si besoin :
- [AbeilleLogs-230719.tar.gz](https://github.com/KiwiHC16/Abeille/files/12089615/AbeilleLogs-230719.tar.gz)

**Comment by tcharp38** [comment]
Ha oui je vais améliorer ca.
Tu dois passer par la page de gestion, cliquer sur la zigate, avancé, choix du canal => appliquer

**Comment by tcharp38** [comment]
Je vois dans les logs que c'est toujours le meme comportement.
Le device s'annonce puis cesse de repondre.
Je vais faire des essais en passant sur le canal 20 pour voir si je peux reproduire qqch de similaire mais je ne vois plus que ça.

Ha.. logs trop courts. Merci de passer à 5000 lignes au moins.

**Comment by tcharp38** [comment]
Encore une chose.. tu peux basculer sur la beta. Version + avancée que la derniere stable et qui contient toutes les dernieres evolutions ou correctifs. Important pendant le support car j'ai besoin de retours aussi avant de la convertir en prochaine stable.

**Comment by 8Thomas8** [comment]
> Ha oui je vais améliorer ca. Tu dois passer par la page de gestion, cliquer sur la zigate, avancé, choix du canal => appliquer

Testé hier soir mais ça me retourne une erreur. Je t'en dis plus ce soir.

**Comment by tcharp38** [comment]
Ha, raison de + pour basculer sur la beta alors.
J'ai corrigé des choses dans ce sens

> - Interne: Parser: Améliorations pour reconnaissance fantomes.
> - Page équipement: Corrections d'affichage 'type' & 'icone'.
> - Blitzwolf temp/humidité/display: Correction signature pour 'TS0201__TZ2000_hjsgdkfl'.
> - Volet Profalux: Changement catégorie => 'ouvrant'.
> - Interne: AbeilleTools::getParameters() => getConfig().
> - Zigate USB/+: Cycle power off/on si sans réponse depuis plus de 2mins.
> - Interne: Supression de qq fichiers obsoletes.
> - Page de config: Ajout option avancée pour empecher cycle power OFF/ON sur Zigates USB plantées.
> - Page de config: Qq améliorations de traductions US.
> 
> 230711-BETA-1
> -------------
> 
> - Interne: Parser: Corrections d'identification cas Profalux.
> - Aubess TS044 _TZ3000_wkai4ga5: Mise-à-jour du modèle pour eviter annonces multiples (2594).
> - Controlleur d'arrosage WOX: Mise-à-jour du modèle pour remontée batterie (2599).
> - Page maintenance: Mise-à-jour infos clefs.
> - Interne: Parser: Support prélim. EF00 cmd 06/TY_DATA_SEARCH.
> - Schneider Wiser plug: Support préliminaire (2601).
> 
> 230618-BETA-1
> -------------
> 
> - Modeles équipement: Suppression commande 'Xiaomi-ff01'.
> - **Correction changement de canal Zigate.**
> 
> 230613-BETA-1
> -------------
> 
> - Modèle équipement: 'value' peut etre surchargé.
> - Profalux volet: Valeur par défaut 'Set Level' ajustée sur 'CurrentLevel'.
>

**Comment by tcharp38** [comment]
Bon je confirme.
Pas moyen d'inclure ce capteur sur le canal 20 de mon côté.

Donc je te suggere de basculer sur la beta, et changer le canal vers 11.
Attention, toutes tes devices ne vont peut etre pas suivre. Il faudra au moins les reveiller, voir les reinclure si besoin.

**Comment by 8Thomas8** [comment]
Je suis sur la branche beta, et canal 11. Rien de mieux.

Par contre ce que je vois, c'est que certains périphériques se réassocient avec le même ID et refonctionne, d'autres avec un ID différent, et aucun "type de device" déterminé, et ceux-ci ne fonctionnent donc pas. J'ai certains capteurs d'ouverture Aquara qui fonctionnent, d'autres non. J'ai des prises Lidl qui prennent un nouvel ID aussi, sans être reconnu en tant que multiprise (logo abeille).

Ce n'est pas lié spécifiquement aux modules Aquara.

J'ai tenté un restore d'un backup de décembre, rien de mieux. J'ai juste vu que le canal 20 avait été choisi par le mode auto.

J'édite le nom de l'issue.

[AbeilleLogs-230719.tar.gz](https://github.com/KiwiHC16/Abeille/files/12100260/AbeilleLogs-230719.tar.gz)

**Comment by tcharp38** [comment]
Ha zut.

Bon le changement de canal n'est semble ok cote Zigate mais tous les devices sur pile... eux n'ont pas forcement recu le changement. Pour cause... ils dorment la plupart du temps.
J'ai bien peur que tu doivent les reinclure.

Du coup que souhaites tu faire ? Si tu reviens sur le canal 20 tu devrais retrouver petit à petit le controle des devices qui eux sont restés sur ce canal.
Mais pour moi ca ne fonctionne pas avec ces vieux Xiaomi qui sont plutot canal 11.

**Comment by tcharp38** [comment]
Pour rappelle quant au choix du canal

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/abcd40bc-2ef6-4895-8ab0-24253a6fee82)

**Comment by 8Thomas8** [comment]
Je suis passé sur le canal 11. Dans tous les cas je n'arrive pas à récupérer la totalité de mes devices en repassant sur le 20.

Les devices qui n'ont pas suivi le changement de canal sont impossible à réinclure, et ceux qui ont suivi, si je les supprime, je ne peux pas les réinclure non plus.

Donc ma question maintenant c'est pourquoi je n'arrive plus à inclure aucun device. Pour le moment je ne vois pas.

**Comment by tcharp38** [comment]
Tu n'as rien à supprimer pour réinclure quoi que ce soit. Je le déconseille meme.

On va se focaliser sur les devices sur secteur avant tout. Ce sont les + importants car ils font relais.
Sont ils tous reinclus ?
Si non refais l inclusion de l'un d'eux... et donne moi le package de logs 5 à 10mins apres

**Comment by 8Thomas8** [comment]
Salut.
J'ai pas donné de news, j'étais absent.

Les devices secteurs ne s'inclus plus non plus, qu'ils aient perdu l'association, ou que je les supprime moi même.
Je pourrais réessayer pour te fournir le package log ce soir.

Je me tâte à repartir sur une install propre du Raspberry + Jeedom + plugins. Histoire de voir si ce n'est pas un problème matériel, au cas où.

**Comment by 8Thomas8** [comment]
@tcharp38 Voici les logs 5min après avoir inclus une prise Ikéa qui avait perdu l'association seule.
[AbeilleLogs-230730.tar.gz](https://github.com/KiwiHC16/Abeille/files/12209957/AbeilleLogs-230730.tar.gz)

**Comment by tcharp38** [comment]
Salut @8Thomas8 

J'avoue qu'a la lecture des logs je ne pige pas trop ce qui se passe. Je vois plusieurs "annonces" des devices (donc ils tentent de revenir dans le reseau) mais ca n'aboutit pas. A chaque retour vers le device, l'info n'est pas acquitée.
A ce stade je ne vois pas de pb software.

Du coup aurais tu une idée de quand tout ça a commencé et si par hasard qqch a été changé dans ton environnement ?
Tu as déplace le RPI ? Mis en boitier ? Ou peut etre mis qqch a coté ?
Tout ça t'inspire ?

**Comment by 8Thomas8** [comment]
Je pense que ça a commencé en début d'année. J'ai une prise que je ne pouvais plus associer mais j'avais mis ça sur le compte de la prise.

Concernant les changements que tu évoques j'y ai pensé mais rien de tout ça chez moi. Ça pourrait être dans le voisinage, mais j'ai rien remarqué.

Je vais partir sur un reset total du raspberry et refaire une installation pour voir.

Je te tiendrais au courant du résultat ici.

**Comment by tcharp38** [comment]
Je pense plutot à un souci HW/environnement que logiciel.

Tu peux me décrire ton installation ?

**Comment by 8Thomas8** [comment]
Oh rien de spé, un RPI 4Go et un piZigate v1 sur une SD, dans un boitier ouvert, sur un bureau depuis 3 ans.


J'ai réinstaller le RPI et la piZigate, et le testa zigate n'est pas concluant :

```bash
# sudo ./PiZiGate_test /dev/tty0
RPI Model searching ...
All it's OK
Verifying /boot/cmdline.txt ...
+ /boot/cmdline.txt seems to be OK
Searching /dev/tty0...
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
+ Port : /dev/tty0 is not used
Verif GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Config GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Opening : /dev/tty0 ...
+ /dev/tty0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK
- No packet received - size sent : 11 - error : 11

```
J'ai peur que ce soit là le problème, et un soucis matériel. Je n'ai jamais eu cette erreur avant. Quand je cherche des info sur cette erreur, ça sent pas bon.

**Comment by tcharp38** [comment]
Sur du tty0 ?

Sur mon OrangePi j'utilise un ttyS0.

Oui ca doit etre ttyS0. Ca doit expliquer ton erreur.

**Comment by 8Thomas8** [comment]
Bien vu. J'avais oublié ce détail :D

Il suffit pourtant de bien tout lire ... https://zigate.fr/documentation/compatibilite-raspberry-pi-4-b/

**Comment by 8Thomas8** [comment]
Bon pas mieux sur une install fraiche. Je n'ai que Abeille et j'ai toujours le même soucis.

Je continue de chercher.

**Comment by tcharp38** [comment]
Pense à coller un package de logs au fur et à mesure, des fois que ca m'inspire autre chose.
Mais franchement je doute d'un souci SW. Ca semble plutot materiel ou perturbation elec, alim defectueuse...

**Comment by 8Thomas8** [comment]
Salut @tcharp38 .

J'ai acheté un nouveau module (USB cette fois) pour mon RPI, et l'association des devices fonctionne parfaitement. Il s'agissait donc bien d'un défaut du module piZigate. Apparemment il avait fait son temps (2 ans et quelque).

Merci d'avoir exploré avec moi les différentes pistes possible. On clôture l'issue ?

**Comment by tcharp38** [comment]
Salut @8Thomas8 
Ok, ca semble effectivement confirmer un souci de module.

Je clos le sujet du coup.
Merci
