### ISSUE TITLE
changement de clé

### ISSUE THREAD

**Issue by Proft1972** [KiwiHC16/Abeille#2605]
Hello @tcharp38 ,
est il possible de changer la cle zigate pour une clé avec antenne car je trouve que j'ai des pertes de reception...pourtant j'ai un routeur loratap mais je n'arrive pas à avoir un module....

**Comment by tcharp38** [comment]
Salut
Tu parles de "transferer le reseau vers une autre clef" ?
Je n'ai jamais tenté mais peut etre qu'on peut faire un backup complet de la clef et la restaurer sur la nouvelle.
Coté Abeille, comme la zigate n offre aucun service de ce type, on ne peut pas faire de miracles.
Il faut idealement
- connecter la nouvelle clef EN PLUS de l'ancienne
- la mettre en inclusion
- et declencher une reinclusion de chaque device
- du coup ils vont quitter proprement la 1ere clef pour aller sur la nouvelle

Mais ca  c'est lourd

De mon côté je vais souder un connecteur ou une antenne directement sur ma version USB pour améliorer la couverture.

**Comment by tcharp38** [comment]
Sujet sans vie vieux d1 an.
Je ferme mais à reouvrir si besoin
