### ISSUE TITLE
Inclusion prise Ledvance Smart+ Indoor (id = PlugValue, LEDVANCE)

### ISSUE THREAD

**Issue by jbromain** [KiwiHC16/Abeille#2610]
Hello :)

Je profite des vacances pour me remettre un peu dans la domotique...

J'ai acheté de nouvelles prises Ledvance, celles-ci:
https://www.amazon.fr/dp/B07VCG5G7H

J'en avais déjà, elles fonctionnent bien dans l'ensemble, et se mettent rarement en cacahuète.

Elles ne sont plus correctement identifiées lors de l'inclusion (elles s'ajoutent bien, mais avec les commandes par défaut, alors que tout se passait bien avant).

![image](https://github.com/KiwiHC16/Abeille/assets/72972682/c1f778b5-2e72-422b-90ea-54c96770593b)

Les prises correctement incluses (il y a longtemps) s'affichent avec ces infos:
![image](https://github.com/KiwiHC16/Abeille/assets/72972682/d75ea93e-b17b-4b20-8af6-0ca6d461f053)

(Je n'ai pas essayé de ré-inclure les "anciennes" prises par peur de tout casser, mais j'imagine qu'il y a un changement de firmware... les prises sont exactement les mêmes visuellement, et je les ai achetées sur la même fiche produit Amazon, même code barre).

Je pense qu'il faut "reconnaitre" le nouveau nom de modèle sans pour autant supprimer l'ancien.

Ci-joint export des logs. L'inclusion a démarré à 17:36:09 sur Abeille2. 
Je pense que la partie intéressante est dans AbeilleParser-prev.log.
[AbeilleLogs-230811.tar.gz](https://github.com/KiwiHC16/Abeille/files/12323211/AbeilleLogs-230811.tar.gz)

Remarques/questions:
- J'arrive à piloter les prises en ajoutant manuellement les commandes, telles qu'elles sont configurées sur les anciennes prises (ça semble être du classique On/Off).  **EDIT 18h57**: en fait ce n'est pas une solution, car les commandes ajoutées manuellement sont perdues si je débranche/rebranche la prise (Abeille semble raffraichir les commandes depuis le fichier de configuration par défaut à ce moment-là).
- Je n'arrive pas "forcer" un modèle sur la page de configuration de l'équipement. Ce serait top de pouvoir le faire, pour permettre la gestion des équipements inconnus "standards" (utilisant les clusters de base, comme le cluster On/off). On pourrait imaginer un équipement type "Cluster On/Off", qu'il suffirait d'appliquer sur n'importe quel équipement "non reconnu" pour ajouter automatiquement les commandes de base. Et idem pour chaque "type d'équipement courant". On pourrait même imaginer qu'Abeille nous pose la question, quand un équipement n'est pas précisément connu, de choisir ce que c'est dans une liste (une ampoule, une prise, un thermomètre...)
- Pour aller encore plus loin, on peut même imaginer que ce choix se fasse tout seul: dans les logs d'inclusion, on voit bien qu'Abeille a compris que l'équipement gérait le cluster 6 On/Off: il pourrait ajouter automatiquement les commandes standard de ce cluster, même sans connaître l'équipement.
- Il me semble qu'avant l'interface affichait le nom du fichier JSON utilisé comme configuration, je ne retrouve plus cette info. 
- Ce serait top que les logs "Parser" et "Cmd" soient séparés par Zigate (comme c'est le cas pour SerialRead); je pense que ça simplifierait le débug.

Je suis bien conscient que c'est un travail colossal, il faudrait que je me replonge dans le code car il y a dû beaucoup changer depuis la dernière fois que j'y ai touché... 

Dernière chose: la cagnotte est-elle toujours active ? est-ce que les contributions vont bien à ceux/celui qui bosse le plus sur le projet (tcharp38) ?

Merci !

**Comment by tcharp38** [comment]
Salut @jbromain 

Tu as oublié la procédure. Trop longtemps en vacances :)
J'ai besoin du discovery: https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html#ajout-d-un-nouvel-equipement

Bascules sur la derniere beta aussi.

Ton device est un nouveau donc normal qu'il ne soit pas reconnu.
Reste à savoir si ce modele "PlugValue" est identique au "PlugZ3". Tu as des infos la dessus ?

    Il me semble qu'avant l'interface affichait le nom du fichier JSON utilisé comme configuration, je ne retrouve plus cette info.

Toujours dispo: page EQ/avancé => modèle

    Ce serait top que les logs "Parser" et "Cmd" soient séparés par Zigate (comme c'est le cas pour SerialRead); je pense que ça simplifierait le débug.

C'est une idée mais la ca correspond reellement au démon: 1 démon parser, plusieurs démons serialread.
Et puis il y a deja beaucoup de logs.. j'ai peur d'alourdir.
Mais je garde l'idée en tete.

    Dernière chose: la cagnotte est-elle toujours active ? est-ce que les contributions vont bien à ceux/celui qui bosse le plus sur le projet (tcharp38) ?

Je n'y ai pas accès. C'est KiwiHC16 qui gérait.

**Comment by tcharp38** [comment]
Tiens ecrase le modele PlugZ3 avec celui la.
[PlugZ3.zip](https://github.com/KiwiHC16/Abeille/files/12327173/PlugZ3.zip)

puis tu redemarres Abeille
et tu refais une inclusion

**Comment by jbromain** [comment]
Hello :)

Normalement je suis bien sur la dernière beta.
J'ai mis le nouveau json est c'est ok (même sans réinclure, j'ai juste débranché rebranché).

Merci !

**Comment by tcharp38** [comment]
Debrancher/rebrancher.. il a du se reannoncer mais tu as du redemarrer Abeille au moins j'imagine.

**Comment by jbromain** [comment]
Oui oui bien sûr :)

**Comment by tcharp38** [comment]
Je prefere ça :)

Bon retour à toutes tes suggestions, j'ai pas zappé du tout.
J'ai répondu en partie je crois mais chaque suggestion peut necessiter un paquet de lignes :) Bref... tu peux ouvrir un sujet specifique pour le/les points les importants pour toi et on en discute.. meme si ca fini fermé.

Dans tous les cas je fais evoluer l'archi progressivement.. et la priorité pour moi est la "maturité" du plugin et sa facilité d utilisation "sans besoin de support".
Accessoirement le temps que j'y passe aussi :)

**Comment by jbromain** [comment]
Hello,

Ok, je vais explorer un peu le code dans les prochains jours et ouvrir des tickets pour discuter de certains points (en commençant par ceux que je pense pouvoir traiter moi-même, si on les valide).

Pour l'historique: ci-joint le Discovery de la prise Ledvance Smart+ Indoor 2023 (tout vert, ça confirme la bonne implémentation du protocole, je ne peux que recommander cette prise):
[discovery-PlugValue_LEDVANCE.zip](https://github.com/KiwiHC16/Abeille/files/12329097/discovery-PlugValue_LEDVANCE.zip)

**Comment by tcharp38** [comment]
Ne t'attarde pas trop au code. En constante evolution lente pour faire disparaitre des trucs pas trop propres ou changer progressivement certains points de l'architecture.
Donc plutot focus sur les fonctionalités.

Merci pour le discovery.
A l occase, tu peux faire celui du Z3 ? Ca permettrait de comparer.

**Comment by jbromain** [comment]
Le voici (pas réussi à tout avoir vert, mais pas loin):
![image](https://github.com/KiwiHC16/Abeille/assets/72972682/4c9230eb-1f41-4927-a2ef-05ab4ea6316c)
[discovery-PlugZ3_LEDVANCE.zip](https://github.com/KiwiHC16/Abeille/files/12336156/discovery-PlugZ3_LEDVANCE.zip)

**Comment by tcharp38** [comment]
Merci
