### ISSUE TITLE
Ajout prise LEXMAN Smart Plug 10 A (id = LDSENK01F, ADEO)

### ISSUE THREAD

**Issue by chimini21** [KiwiHC16/Abeille#2613]
Bonjour,
j'ai voulus ajouter des prises Lexman voyant qu'elles étaient déjà prise en compte par Abeille.
Cependant celle que j'ai acheté doivent être plus ancienne car pas le même id LDSENK01F au lieu de LDSENK02F
Ci joint le fichier assistant découvert.
Est-ce que cela suffit?
merci d'avance
Cordialement
[discovery-LDSENK01F_ADEO.zip](https://github.com/KiwiHC16/Abeille/files/12378375/discovery-LDSENK01F_ADEO.zip)

**Comment by tcharp38** [comment]
Salut

Avant de faire un modele, peux tu creuser pour savoir quelle difference il y a avec un LDSENK02F ?

D'autre part il me faudra une image BMP sans arriere plan si le visuel est different.

**Comment by chimini21** [comment]
D'après ce que j'ai pu trouver.
LDSENK02F:
16A avec mesure de consommation

LDSENK01F
10A sans mesure de consommation 

Pour l'image c'est la même

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices

[LDSENK01F_ADEO.zip](https://github.com/KiwiHC16/Abeille/files/12387641/LDSENK01F_ADEO.zip)

puis redemarrer Abeille
refaire inclusion 
tester

Attention.. mode debug si besoin de support.
Voir si le "Set Level" fait un sens. La prise dit qu'elle supporte ca

**Comment by chimini21** [comment]
Bonjour,
le "Set Level" ne sert pas à grand chose vu qu'elle ne fait que le ON/OFF, il faut se mettre à o% ou 100% pour le changement d'état.
du coup, il manque la fonction ON et OFF basic dans les commandes.
Peux-tu les ajouter?
Merci d'avance
cordialement

**Comment by tcharp38** [comment]
Salut
Pas surpris pas ta reponse mais bon au cas ou .. ce device dit qu'il supporte le "set level".
Je le vire du modele.

Le ON/OFF est deja implementé mais comme tu n'es pas sur la beta, il doit te manquer des fichiers.

2 choix donc
- tu bascules dessus et tu es au gout du jour et tu restes la dessus jusqu'a la prochaine stable
- tu restes sur cette vieille stable mais tu dois avoir des erreurs indiquant qu'il manque des fichiers.. il me faut la liste

**Comment by chimini21** [comment]
Bonjour,
Désoler du retour tardif, je suis passé sur la beta.
Tout est OK.
merci

**Comment by tcharp38** [comment]
Merci
Je clos le sujet mais à réouvrir si soucis.
