### ISSUE TITLE
Problèmes sur l'IHM (tri, et selection)

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#2615]
Bonjour,
sur les dernières beta il m'est impossible de trier les lignes de la page Santé Abeille.
Si je mets mon curseur sur une colonne (Status par exemple), l'info bulle affiche bien "Trier par" mais le clic ne fonctonne plus.

Suis-je le seul?

Autre problème, pour connaitre le(s) groupe(s) d'un device, je le selectionne dans ma liste et je clic sur "Get groups".
Réponse de l'interface: "Aucun équipement sélectionné" 
Impossible donc de vérifier ni d'ajouter des groups!

Bizarement, la sélection d'un équipement pour le surveiller fonctionne.

Une idée?
Kaléo.

**Comment by tcharp38** [comment]
Pour la page santé j'ai vu le souci. J'ai cassé ça en ajoutant un raffraichissement de la page santé toutes les 2sec.
Donc a mettre sur ma todo.

Pour le "get groups".. je vais regarder ça.

Pour info, pas mal de changements en cours, en particulier pour autoriser (dans un cas extreme) le choix d'un modele d'equipement.
Il me semble que tu es un des rares à en avoir besoin donc a venir. La prochaine beta ne sera fonctionnelle sur ce plan donc pas de panique.

**Comment by tcharp38** [comment]
Pour le "Get group" je reproduis le pb.
Neanmoins cette fonction doit disparaitre.
Tu devrais avoir un bouton "refresh" à cote de ton equipement qui te permet de faire la meme chose + facilement

Exemple

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/f2d70e6b-fecd-4980-9e33-8113ebefce2b)

**Comment by kaleofr** [comment]
-> "choix d'un modele" oui, merci! J'ai vu les discussions en cours.
-> Get Group, oui c'est plus simple comme tu l'indiques, mais cela ne permet pas de faire les add group, set group remote et legrand. Et comme j'ai tout réinclus de 0, je suis bloqué pour l'instant. Mais bon, je me passerai d'automatismes dans la maison quelques temps. Pas de problèmes.

Merci.

**Comment by tcharp38** [comment]
Je regarde ca tres vite.

**Comment by tcharp38** [comment]
A decompresser dans desktop/js => Abeille/desktop/js/Abeille.js
[Abeille.zip](https://github.com/KiwiHC16/Abeille/files/12409850/Abeille.zip)

Garde la version originale au cas ou mais ca semble corriger ton souci.

Je pousse une beta pour demain.

**Comment by kaleofr** [comment]
Merci pour ce travail.
Ca a provoqué l'erreur suivante, en cas d'appui sur inclusion : ERREUR: Commande inattendue: '{"zgSetPermitMode":"zgSetPermitMode","name":"zgSetPermitMode","priority":4,"dest":"Abeille2","mode":"start","addr":"0000"}'

Du coup je passe par la ruche, pas de soucis, mais a ne pas publier en l'etat. :-(

**Comment by tcharp38** [comment]
Ha zut. Il manque d autres updates donc bascule sur la bêta d hier. Ça devrait résoudre

**Comment by tcharp38** [comment]
Dans la prochaine beta, le tri des colonnes de la page santé est de retour.

=> 230830-BETA-1

@kaleofr 
Je te laisse clore ce sujet des que tu as confirmé que c'est ok pour toi.
