### ISSUE TITLE
Ajout impossible des Sonoff-SNZB-02 / eWeLink TH01

### ISSUE THREAD

**Issue by kaleofr** [KiwiHC16/Abeille#2616]
Un de mes TH01 s'est déconnecté du réseau, peut être les piles.

Depuis, impossible de l'ajouter: pile neuve, nouveau TH01, RAZ de la Zigate, réinclusion de tout mes devices... sauf des TH01.
Aucun ne veux réapparaitre.

Vers 14h47.
[AbeilleLogs-230822.tar.gz](https://github.com/KiwiHC16/Abeille/files/12409065/AbeilleLogs-230822.tar.gz)

C'est moi ou il y a un problème quelque part?

Kaléo

**Comment by tcharp38** [comment]
Est ce que ca correspond aux adresses suivantes ?
- 061B
- 7F34
- AD0A

Ces devices sont en 'NO ACK'
Un phenomene que je vois sur dautres sujets... tous en 3.A0 :(
Voir #2604 ou #2614

**Comment by kaleofr** [comment]
Oui... j'ai bien fait de mettre a jour le firmware alors :-(

**Comment by tcharp38** [comment]
Le pb est qu il corrige quand même des tas de soucis mais en apporte d autres 😕

J'essaie de mon côté de prendre le contrôle sur le fw. Pas assez de réactivité et corrections à mon goût

**Comment by kaleofr** [comment]
Je vois.
D'autant plus problématique que ca ne s'arrète pas la. Je viens de voir que j'ai une ampoule Hue White en Time-out... alors qu'elle répond aux on/off. 
Le retour d'info n'a pas l'air fonctionnel mais l'ordre est exécuté.
NO_ACK et du coup abeille la considère en time-out.

1277|[2023-08-23 10:01:59] Equipement à surveiller: [Bureau][Test Light], 2CFA-0017880100E493A5
1278|[2023-08-23 10:02:31] => 0062-022CFA010B00
1279|[2023-08-23 10:02:31] <= 8012/APS data confirm, Status=00, Addr=2CFA, SQNAPS=98, NPDU=00, APDU=00
1280|[2023-08-23 10:02:38] <= 8011/APS data ACK, Status=A7/NO_ACK, Addr=2CFA, EP=01, ClustId=0004, SQNAPS=98
1281|[2023-08-23 10:03:11] => 0092-022CFA010B02
1282|[2023-08-23 10:03:11] <= 8012/APS data confirm, Status=00, Addr=2CFA, SQNAPS=9A, NPDU=04, APDU=00
1283|[2023-08-23 10:03:17] <= 8011/APS data ACK, Status=A7/NO_ACK, Addr=2CFA, EP=01, ClustId=0006, SQNAPS=9A
1284|[2023-08-23 10:03:24] => 0100-022CFA010B000600000000010000
1285|[2023-08-23 10:03:24] <= 8012/APS data confirm, Status=00, Addr=2CFA, SQNAPS=9C, NPDU=04, APDU=00
1286|[2023-08-23 10:03:30] <= 8011/APS data ACK, Status=A7/NO_ACK, Addr=2CFA, EP=01, ClustId=0006, SQNAPS=9C


... Même chose sur une prise lidl et surement d'autres équipements...

**Comment by kaleofr** [comment]
En attendant des nouvelles rassurantes, je suis rapidement revenu au FW 3.22...

**Comment by tcharp38** [comment]
2 questions...
- peut on résumer le sujet en disant qu'il est specifique Zigate v2/+ ?
- de ton experience, le FW 3.22 est + fiable/utilisable que la version 3.A0 ?

J'essaie de clarifier la situation pour les malheureux proprietaires de Zigate v2

**Comment by kaleofr** [comment]
peut on résumer le sujet en disant qu'il est specifique Zigate v2/+ ?
-> je ne sais pas, pour moi c'était effectivement sur une v2. Si c'est le cas pour tout le monde alors effectivement...

de ton experience, le FW 3.22 est + fiable/utilisable que la version 3.A0 ?
-> de mon expérience, oui, je suis revenu tout de suite en 3.22. Pour mon installation et mes équipements le FW 3.22 ne me pose pas trop de problèmes. Le 3.A0 a tout de suite mis le bazard.

Pas de nouvelles pistes ni de communications avec akila à ce sujet?

**Comment by tcharp38** [comment]
Du coup pour la prochaine stable je vais conseiller la 3.22 et signaler des comportements etranges avec la 3.A0.

Aucune nouvelle d'Akila. Pas tres reactif sur son forum de toute façon :(

**Comment by tcharp38** [comment]
@kaleofr 
Que fait on de ce sujet ?

**Comment by kaleofr** [comment]
Si le problème est effectivement avec le FW 3.A0, autant fermer.
Par contre, ou en est-on de la compatibilité avec ce firmware? Pour ma part je suis toujours en 3.22

**Comment by tcharp38** [comment]
Rien de nouveau chez Zigate donc d'apres tes experiences, la 3.22 reste le meilleur candidat.

**Comment by tcharp38** [comment]
Salut @kaleofr 
Concernant le sujet initial "Ajout impossible des Sonoff-SNZB-02 / eWeLink TH01"... tu as encore des soucis en FW 3.22 ?

**Comment by tcharp38** [comment]
Je ferme cet antique sujet sans vie depuis un moment.
A réouvrir si besoin
