### ISSUE TITLE
Capteur température/humidité Tuya avec afficheur (id = TS0201, _TZ3210_ncw88jfq)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2619]
Bonjour,
J'ai acheté un capteur de température avec afficheur zigbee, et il n'est pas encore répertorié a priori.
Voici donc le template généré avec l'assistant découverte
[discovery-TS0201__TZ3210_ncw88jfq.zip](https://github.com/KiwiHC16/Abeille/files/12542765/discovery-TS0201__TZ3210_ncw88jfq.zip)
![S16e89a90ff8943b3922081ce4d003ec7O](https://github.com/KiwiHC16/Abeille/assets/144285463/3cec3816-f74b-4b25-9c0b-a8130ac7b5bc)

pourriez-vous m'aider à le rendre fonctionnel dans ma ruche ?

**Comment by tcharp38** [comment]
Salut @M4dd4M 
Quel type de batterie et combien ?
D'autre part il me faut l'image au format PNG sans arriere plan. La balle est chez toi.

Voila le modele à decompresser dans core/config/devices
mais je doute que ca fonctionne si tu n'es pas sur la beta.
Tu aura donc le choix entre basculer sur la beta ou attendra la prochaine stable.
[TS0201__TZ3210_ncw88jfq.zip](https://github.com/KiwiHC16/Abeille/files/12553602/TS0201__TZ3210_ncw88jfq.zip)

**Comment by M4dd4M** [comment]
Bonjour @tcharp38 
Merci pour la réponse, oui je veux bien passer en Beta ... mais je ne sais pas trop comment faire, je ne trouve pas comment changer la source depuis Jeedom ...
Pour quand est prévue la prochaine stable ?

Sinon c''est 2 batteries AAA pour l'alim avec un bouton reset/connect au dos.

PS : voici un PNG
![thermo](https://github.com/KiwiHC16/Abeille/assets/144285463/b66560c0-5956-4c63-9633-209ecca8b4ac)

**Comment by tcharp38** [comment]
Pour l'installation de la beta suivre ca https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta
Il s'agit de la beta d'ABEILLE et non pas de Jeedom

J'ai pris l'image. Elle sera dans la beta dispo demain (231009-BETA-1)

**Comment by M4dd4M** [comment]
L'intégration est parfaite, tout est OK avec ce capteur dans la dernière beta, merci !
Du coup, je vais en acheter d'autre, car il est assez pratique.

**Comment by tcharp38** [comment]
Ok super.
Je ferme le sujet du coup. A réouvrir si souci.
