### ISSUE TITLE
Prises OSRAM/Ledvance en time-out

### ISSUE THREAD

**Issue by CocoShaker** [KiwiHC16/Abeille#2620]
Bonjour,
Suite à mon sujet https://community.jeedom.com/t/3-prises-ledvance-osram-smart-ko-en-meme-temps/112040/2?u=hermioneg voici le package de logs.
J'ai vérifié être en debug, redémarré le demon, mis en mode inclusion, puis tenté la réinclusion de [Cuisine][Prise O3 Camera].
Aucun changement dans Jeedom (toujours en time-out), commande non réactive.

Merci pour votre aide.
[AbeilleLogs-230913 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/12597344/AbeilleLogs-230913.1.tar.gz)

**Comment by tcharp38** [comment]
Salut @CocoShaker 
Apres analyse des logs je vois effectivement que la prise s'annonce mais ca ne va pas plus loin.
Elle est tout de suite "injoignable" donc sa configuration ne se termine pas.

En creusant un peu + je vois des erreurs x87 (0x87 There are no free entries in the extended address table.)
Autrement dit la Zigate dit qu'elle est pleine.
Meme si le nombre max admis reste encore un mystere pour moi, je soupconne fortement qu'elle soit corrompue :(

Comme tu es en FW 0003-0323, c'est peut etre l'occasion de faire un clean et partir sur la version OPDM 0004-0323.
Ca veut donc dire.. mettre à jour le FW, effacer tout le réseau, et reinclure tous les equipements.

Désolé pour cette mauvaise nouvelle. A ce stade.. Abeille ne semble pas en cause.
Qu'en penses tu ?

**Comment by CocoShaker** [comment]
Merci pour ton retour.
C'est ce que je craignais, j'ai quand même beaucoup de devices, plus ceux que j'ai supprimés mais qui doivent toujours être dans la clé. Dommage pour moi ceux que je n'arrive plus à inclure sont quand même parmi les plus utiles (détecteurs ouverture). Je n'ai pas vraiment d'autre choix, je vais passer au dernier firmware OPDM. Ca ne me dérange pas de tout réinclure, par contre, je n'ai pas envie de refaire les scenarii, virtuels, design etc... Si je laisse les objets dans Jeedom, il va les "reconnaître" à la nouvelle inclusion ?

**Comment by tcharp38** [comment]
Alors j'allais dire oui mais en reflechissant il y a des soucis potentiels.
Je m'explique.

A chaque nouvelle annonce, c'est le modele courant qui est utilisé. Donc je soupconne que tes devices ont ete inclus il y a longtemps donc avec de vieux modeles et donc avec le nom des commandes de l'époque. Si entre temps j'ai renommé certaines commandes (Ex: 'etat' => 'Status') pour des soucis de normalisation et nettoyage.. il se peut que qu'a la reinclusion il perde la vieille commande au profit de la nouvelle sans pouvoir faire le lien qu'il s'agit de la meme.

Pas sur d'etre clair mais du coup tu peux avoir des commandes orphelines à cause de ca, et donc tes scenarii cassés.

Tu peux avoir le meme phenomene en faisant une "mise à jour" de chacun de tes modeles.
Ca te permet d'y aller pas à pas avant de lancer la réinclusion de tout.

Tu suis ?
T inquiete pas si tu dis non :)

**Comment by CocoShaker** [comment]
Si, j'ai compris, j'ai déjà dû réinclure des équipements qui ont eu des commandes modifiées suite aux changements de modèle. Ca n'est pas très grave, déjà si je ne perds pas l'équipement, je peux toujours retrouver mes commandes orphelines et les remplacer par les nouvelles, ou adapter si changement de type. 
Bon je vais me lancer ce we, quand j'aurai du temps. Dernière question : faut-il exclure les modules qui fonctionnent toujours de la Zigate avant le clean/upgrade, histoire de mettre toutes les chances de mon côté pour le réappairage, ou ce n'est pas la peine ?
merci :)

**Comment by tcharp38** [comment]
Tu gardes tout tes équipements connus de Jeedom.

C'est du côté de la Zigate que le "reset" se fait.
Apres update du FW + erase PDM.. son réseau sera vide, elle ne connaitra plus aucun equipement. Comme si chaque eq avait été exclu. C'est la ou chaque reappairage doit refaire le lien avec l'équipement "Jeedom".
Bref pour repondre à ta question.. pas besoin d'exclure.

Je te suggere de proceder pas à pas.
Tu fais l'update "legacy => opdm" (qui doit enchainer automatiquement un "erase PDM") puis tu ne refais l'inclusion que d'un equipement pour voir comment ca se deroule.
Si tout se passe bien tu peux dérouler et couvrir tes autres periphs.

**Comment by CocoShaker** [comment]
Merci pour tes conseils : firmware mis à jour, erase complete eeprom, puis réappairage des équipements en commençant par les prises/routeurs. 33 équipements à nouveau opérationnels (j'ai eu des difficultés avec les projecteurs de jardin car montés en série, 1 seul voulait s'inclure, mais au final ok).
Encore un grand merci pour tout !

**Comment by tcharp38** [comment]
Tu as donc basculé sur la 3.23 opdm ?

**Comment by CocoShaker** [comment]
Oui j'ai pris la dernière version v3.23 opdm  ( [https://github.com/fairecasoimeme/ZiGate/releases/tag/v3.23-opdm](url)=
![image](https://github.com/KiwiHC16/Abeille/assets/118360569/042c7b66-dc89-4a8b-a13e-7889bc120df3)

**Comment by tcharp38** [comment]
Parfait !
