### ISSUE TITLE
Intégration Smart Switch ZG-005-RF 

### ISSUE THREAD

**Issue by baloo53** [KiwiHC16/Abeille#2621]
Bonjour,

On ma conseillé d'ouvrir une issue ici.
J'aurais voulu savoir si c'est possible d'intégrer cette équipement sur abeille (voir photo)
Le plugin a bien détecté l'objet en revanche il m'indique équipement inconnu.
L'équipement à un mode Switch pour passer de poussoir à contact sec et il a 4 canaux 
Je suis à votre écoute pour toute information que je pourrais fournir

Cordialement

![IMG_20230915_185151](https://github.com/KiwiHC16/Abeille/assets/99254403/ca3d502b-fe62-4ae4-b82f-16175821ea51)

**Comment by tcharp38** [comment]
salut @baloo53 
A priori ce modele est deja supporté depuis la beta 230822-BETA-1 mais elle n'a pas encore été basculée en stable.
C'est ce sujet: (https://github.com/KiwiHC16/Abeille/issues/2608)

Mais pour etre sur qu'il s'agit de la meme signature j'ai besoin du discovery
Voir https://kiwihc16.github.io/AbeilleDoc/AjoutNouvelEquipement.html

**Comment by baloo53** [comment]
Merci bien je te fais sa dans l'aprem.
Ta besoin d'un autre bêta testeur ou tout est fixé pour toi? Car sinon j'attends juste la version stable :)

**Comment by tcharp38** [comment]
Il n'y a jamais assez de beta testeurs :)
Meme si je fais attention à l'impact de mes modifs, il y a toujours un risque d'un truc cassé. D'ou la necessité que certains utilisent la beta et me reportent toute regression des leur decouverte et je la corrige dans la foulée.

**Comment by baloo53** [comment]
D'accord et bien avec plaisir alors. Je vais voir sa demain au calme alors. Car si je vais trop vite je risque de faire des bêtises surtout que j'ai la poisse avec mon jeedom.

Je supprime le composant "inconnu" je passe mon plugin en beta puis en mode debug. Enfin j'inclus de nouveau l'objet qui devrait être connue (version bêta) et j'attends 10min puis je t'envoie les log c'est bien sa?

**Comment by tcharp38** [comment]
C'est ça mais 3 ou 4 min ça suffira.

**Comment by baloo53** [comment]
Bon je suis passé en BETA, j'ai lancé une intégration de ma clé et j'ai un nouvelle équipement qui a été identifié. Je me dis super ^^ malheureusement je sais pas pourquoi sa ma crée un équipement que j'avais déjà.
l'interrupteur connecté Legrand pour le volet de la chambre d'amis, celui qui vient d'être crée fonctionne parfaitement mais plus l'ancien ^^
Mais aucune trace de module relais 4 canaux. Je me demande si j'ai bien effectué un reset de celui-ci. Tu connais la démarche stp? j'ai trouvé de tout sur le net 
[AbeilleLogs-230917.tar.gz](https://github.com/KiwiHC16/Abeille/files/12642175/AbeilleLogs-230917.tar.gz)

**Comment by baloo53** [comment]
Bon j'ai réussi, le module à l'air de très bien fonctionner 
je te partage les log.
[AbeilleLogs-230917 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/12643048/AbeilleLogs-230917.1.tar.gz)

**Comment by tcharp38** [comment]
Parfait.
Du coup c'est ok pour le smart switch mais tu as un souci avec un inter Legrand ?

**Comment by baloo53** [comment]
Oui parfait, j'ai aussi une télécommande qui était fourni avec mais je peux pas tester et te donner les log car les piles sont en cours de livraison hahhaha

Pour Legrand et bien non c'est ok sa ma créé un deuxième objet je sais pas pourquoi mais je vais le remplacer et sa va marcher je pense (j'attendais de repasser en version stable)
Au passage j'en profite en espérant que la discussion ne va pas devenir une usine à gaz ^^
Vu qu'on parle des interrupteurs Legrand celiane, à l'époque j'avais évoqué le problème d'état des volets. Ainsi que l'option inversé qui ne fonctionne pas. J'ai le fameux 0% qui correspond à fermé pour certains de mes volets et d'autres ouvert et du coup pareil pour le 100%. Je sais pas si la problématique avait été éclairci :)

**Comment by tcharp38** [comment]
Pour Legrand, tu reouvres un sujet existant ou le mets a jour, ou tu en crees un nouveau.

Du coup je ferme ce sujet ZG-005-RF.
A reouvrir si soucis.
