### ISSUE TITLE
Ajout Ampoule Philips Hue LTE002 (id = LTE002, Philips)

### ISSUE THREAD

**Issue by Zhitomiri** [KiwiHC16/Abeille#2622]
Bonjour,

J'ai tenté sans succès d'intégrer une ampoule Philips Hue LTE002, non reconnue dans Abeille.

Cette ampoule semble être connue et reconnue sur d'autres plateformes :
https://zigbee.blakadder.com/Philips_LTE002.html

Je vous joins le log de l'assistant de découverte.
[discovery-LTE002_Philips.zip](https://github.com/KiwiHC16/Abeille/files/12647431/discovery-LTE002_Philips.zip)

Serait-il possible de l'ajouter à Abeille ?

En vous remerciant par avance.
Zhitom.

**Comment by tcharp38** [comment]
Salut
Il me faudra une image au format PNG sans arriere plan.

Voila un modele à tester, a decompresser dans Abeille/core/config/devices
mais peut etre te faudra t'il basculer en beta Abeille pour que ce soit fonctionnel.
Sinon il faudra attendre la prochaine stable.

[LTE002_Philips.zip](https://github.com/KiwiHC16/Abeille/files/12647961/LTE002_Philips.zip)

**Comment by Zhitomiri** [comment]
Merci pour ce retour.

Je suis passé en bêta et avec ce fichier, les commandes fonctionnent (on/off, variation de l'intensité, variation de la température du blanc).

Par contre, c'est une ampoule qui ne fait exclusivement que du blanc, de chaud (2200K) à froid (6500K) et des commandes pour d'autres couleurs sont également présentes mais inutiles pour ce modèle.

Je vous joins aussi une photo pour illustrer le modèle dans votre base de données:
![LTE002](https://github.com/KiwiHC16/Abeille/assets/145348076/3bc248d7-7f89-4a5c-8023-adb06c346067)

Encore merci,
Zhitom.

**Comment by tcharp38** [comment]
Voila le nouveau modele.
J'ai viré le controle des couleurs.
[LTE002_Philips.zip](https://github.com/KiwiHC16/Abeille/files/12650196/LTE002_Philips.zip)

Tu peux juste faire "mise à jour" via la page "avancé" de l'équipement.

Tout sera dans la prochaine beta dispo demain le 19

**Comment by tcharp38** [comment]
Salut @Zhitomiri 
Tu as des retours à faire sur ce sujet ? Des soucis ?

**Comment by tcharp38** [comment]
Plus de vie sur ce sujet.
Je ferme mais à réouvrir si qqn est interessé pour bosser sur cette prise.
