### ISSUE TITLE
ERREUR: Unknown device - Beta 2023-09-20 01:00:22

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2623]
Salut !

J'ai des équipements qui ont quitté le réseau.
J'ai voulu les réintégré et j'ai eu ce message d'erreur a chaque fois.
De plus, est ce normale que ca me crée toujours un nouveau devide avec une nouvelle addr ? 
Car le module est le meme et déjà intégré 

Merci :)

> 2023-09-22 18:56:21 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=E25B |   |  
>   | 2023-09-22 18:56:11 | Abeille | [Ruche][Abeille1-852]: Nouvel équipement identifié. |   |  
>   | 2023-09-22 18:56:09 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=F600 |   | 3
>   | 2023-09-22 18:55:37 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=EFDE |   |  
>   | 2023-09-22 18:55:05 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=6B38 |   |  
>   | 2023-09-22 18:54:58 | Abeille | [Ruche][Abeille1-851]: Nouvel équipement identifié. |   |  
>   | 2023-09-22 18:54:52 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=0C4D |   |  
>   | 2023-09-22 18:54:35 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=4082

[AbeilleLogs-230922.tar.gz](https://github.com/KiwiHC16/Abeille/files/12703070/AbeilleLogs-230922.tar.gz)

**Comment by Jake309** [comment]
petit complément, le 851 correspond au 6B38 et le 852 au E25B, respectivement fenetre buanderie et parents
J'ai bien la mise à jour d'état après intégration

**Comment by Jake309** [comment]
Nouvel équipement

> 2023-09-22 19:34:01 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=FFBF |   | 3
>   | 2023-09-22 19:33:41 | Abeille | [Ruche][Abeille1-853]: Nouvel équipement identifié.


[AbeilleLogs-230922 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/12703196/AbeilleLogs-230922.2.tar.gz)

**Comment by Jake309** [comment]
>2023-09-24 13:53:08 | Abeille | ERREUR: Unknown device: Net=Abeille1 Addr=488E |   | 2402
2402 occurence pour un équipement que je ne retrouve pas dans santé :( 

[AbeilleLogs-230924.tar.gz](https://github.com/KiwiHC16/Abeille/files/12708433/AbeilleLogs-230924.tar.gz)

**Comment by tcharp38** [comment]
Salut @Jake309 
Je rentre juste. Je regarde ca demain dans la journée.

**Comment by tcharp38** [comment]
Bon finalement j'ai pas tenu.
Je crois que j'ai compris l'erreur. Ca arrive sur des equipements qui ne sont pas connus de Jeedom.

Bref.. je vais corriger ça mais sauf erreur, ca ne provoque qu'un message. Pas d'autre souci en perspective ?

**Comment by Jake309** [comment]
Salut @tcharp38 

Justement j'allais te dire que rien ne pressait car ça n'avait a première vue pas d'impact 
Serveur non saturé et commandes toujours réactives.
J'ai redémarré le demon après mon post, pour l'instant pas de nouvelles erreur :)

J'espère que le week end a été bon ;)

**Comment by tcharp38** [comment]
Oui, WE plutot pas mal.

Tiens, a decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/KiwiHC16/Abeille/files/12709629/AbeilleParser.class.php.zip)

Si tu supprimes le suivant de Jeedom

     - Z1: [Buanderie][Fenetre buanderie], id=851: ok
           addr=6B38', model='sensor_magnet, type='Xiaomi door sensor'

tu ne devrais plus avoir d'erreur quand il renvoi une info.
Je te laisse verifier que c'est le cas.

**Comment by Jake309** [comment]
Salut !!!
Alors, j'ai remplacé le fichier, mais je ne joue pas trop avec les capteurs de fenetre.
Ce sont des xiaomi, c'est capricieux, c'est la galère à intégrer

Par contre la, je viens de réintégrer un module qui existait déjà, et il me sort le message à chaque action (on ou off)

ERREUR: Unknown device: Net=Abeille1 Addr=8CEB
Il s'appelle barre, plus tot dans la soirée niches old et niche (tu sents les mouvements d'équipement :p)

Sur celui la, on peut jouer sans souci, c'est une prise, c'est facile :D 

J'espère que ca te fait pas trop de boulot a regénérer le fichier :/ 

[AbeilleLogs-230929.tar.gz](https://github.com/KiwiHC16/Abeille/files/12771102/AbeilleLogs-230929.tar.gz)

**Comment by Jake309** [comment]
On continue les problèmes ^^
Chaque nouvelle inclusion j'ai l'erreur.
Mais est ce normal qu'un équipement qui existe déjà, quand je le réintégre, il me le met en nouvelle équipement ?
[Ruche][Abeille1-865]: Nouvel équipement identifié.     adresse : 3AB2
alors que c'est mon: Mvt SdB Haut     adresse : 22B4

Forcément nouvel équipement : ERREUR: Unknown device: Net=Abeille1 Addr=3AB2

Merci Tcharp :) 

[AbeilleLogs-230929 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/12771186/AbeilleLogs-230929.1.tar.gz)

**Comment by tcharp38** [comment]
Salut. Loin de mon ordi mais juste au cas où es tu sur d'avoir écrasé la fichier ? Je n'ai pas refais de bêta depuis il me semble mais pas sur non plus. Je verrai ça lundi

**Comment by Jake309** [comment]
salut, oui, profites du week end, il sert à ca !
Après les intégrations je reboot jeedom et j'ai plus les erreurs.
J'ai renommé l'ancien en .old, collé le tien et redémarré jeedom :)

**Comment by tcharp38** [comment]
Le message "unknown device" n'est pas une erreur affichée n'est ce pas ?
Tu l'as trouvé dans les logs de debug.
Je me trompe ?

**Comment by Jake309** [comment]
C'est affiché dans le centre de messages justement :/ j'ai pas été voir les logs
En gros, auparavant, j'avias le message du style (équipement) s'est réannoncé, mise à jours de la table ou du réseau truc dans le genre.
Maintenant que je réintégre un module qui déconne, j'ai ca à la place
<img width="869" alt="Capture d’écran 2023-10-01 à 22 10 25" src="https://github.com/KiwiHC16/Abeille/assets/49479084/f0957a9c-e494-4fe6-a3fe-6a8358639a00">

au cas ou, ca me coute rien de toujours mettre les log
[AbeilleLogs-231001.tar.gz](https://github.com/KiwiHC16/Abeille/files/12778143/AbeilleLogs-231001.tar.gz)

**Comment by tcharp38** [comment]
J'ai viré le message. A confirmer dans la beta de demain.

**Comment by Jake309** [comment]
J'ai plus le message.
Dans les log abeille et abeilleparser je vois ce genre de messages:
[2023-10-05 22:19:36][DEBUG] :   Unknown Jeedom command logicId='0402-01-0000'
[2023-10-05 22:19:59][DEBUG] :   Unknown Jeedom command logicId='0403-01-0014'
[2023-10-05 22:19:59][DEBUG] :   Unknown Jeedom command logicId='0403-01-0010'

[2023-10-05 22:22:52]   AttrId=F000/Unknown-0102-F000, AttrType=20, ValueHex=64 => 100

Je ne sais pas si ca peut avoir un impact.

En tout cas, je sais pas si une des modif a une incidence, ou juste le temps depuis mon changement de certaines prises, mais j'ai remarqué une meilleure réactivité.

[AbeilleLogs-231005.tar.gz](https://github.com/KiwiHC16/Abeille/files/12823000/AbeilleLogs-231005.tar.gz)

**Comment by tcharp38** [comment]
Ok ca c'est normal.

Quant à la reactivité j'ose croire que les differentes modifs progressives vont dans le bon sens.

Je clos ce sujet mais à reouvrir si besoin.
Merci
