### ISSUE TITLE
Tous en Timeout sauf ruche

### ISSUE THREAD

**Issue by CocoShaker** [KiwiHC16/Abeille#2624]
Bonjour,

Suite de [https://github.com/KiwiHC16/Abeille/issues/2620](url)
Après 7 jours de fonctionnement optimal, tous les équipements sont passés en timeout le 23/09 entre 17h et 18h (mais pas la Zigate).
J'ai tenté redémarrage demon, changement de port USB, reinit du firmware... Les équipements restent injoignables.

Voici le package de logs. Merci pour toute l'aide que tu peux m'apporter encore !
[AbeilleLogs-230924.tar.gz](https://github.com/KiwiHC16/Abeille/files/12708048/AbeilleLogs-230924.tar.gz)

**Comment by tcharp38** [comment]
Salut

Qu'entends par "reinit" du firmware ? Tu as fait un "erase PDM" ?
Via la page "reseau" peux tu demander un raffraichissement et me donner les logs ?
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/dcb45081-16ba-4a98-824c-5cf0ad4cdf01)

On verra si il reste des equipements connus de la zigate deja.

**Comment by CocoShaker** [comment]
Salut

Non, j'ai juste remis à jour le même firmware, mais pas fait Erase PDM.
Lorsque je rafraichis le reseau, ça me dit "erreurcan't write lock file" et "erreur  le fichier Abeille.lqi n'existe pas".
J'ai fait Routes/Tout collecter, puis rafraichi le reseau, plus d'erreur.

Voici le package : 
[AbeilleLogs-230925.tar.gz](https://github.com/KiwiHC16/Abeille/files/12711213/AbeilleLogs-230925.tar.gz)

**Comment by tcharp38** [comment]
Tout ça me laisse perplexe.

En gros
- La Zigate repond puisqu'elle renvoi sa version regulierement donc le port est bon
- Par contre tout interrogation d'un equipement n'abouti pas (NO ACK) comme si il n'y avait aucun equipement sur le reseau. D'ou ma question sur l'effacement PDM.

Ha un truc

    [2023-09-25 06:49:58] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=8031, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=0000, DstAddrMode=02, DstAddr=0000
    [2023-09-25 06:49:58]   Management LQI response: SQN=E5, Status=C1, NTableEntries=, StartIdx=, NTableListCount=
    [2023-09-25 06:49:58]   Status != 00 => Decode canceled

Ce message avec l'err C1 semble dire que ton reseau est vide.

Juste pour confirmer ca, peux tu passer en mode inclusion et reinclure n'importe quel eq, le + facile pour toi.
Puis me filer les logs ?

**Comment by CocoShaker** [comment]
Bonsoir
Désolée de ne pas répondre vite, je rentre du taf...
J'ai mis en inclusion et tenté ma prise Osram.
De ce que j'ai vu dans les logs, elle s'inclut bien. Mais les commandes ne répondent pas et dans Santé elle apparait toujours time-out-noACK. Au fait, je suis passée sur la version beta hier, pour voir si ça changeait quelque chose...
voici le package
[AbeilleLogs-230925 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/12717824/AbeilleLogs-230925.2.tar.gz)

**Comment by CocoShaker** [comment]
Heu en fait les commandes répondent maintenant (mais Santé toujours KO). Je vais essayer de tout réinclure ...

**Comment by tcharp38** [comment]
Le fait d'avoir des tas d'equipements toujours dans Jeedom mais plus dans le reseau peut ralentir les actions pour ceux qui fonctionnent (ici osram).

Bref ca semble dire que la manip de mettre à jour le FW a aussi effacé la PDM.
Mais ca n'explique pas ton probleme d'origine qui devait etre autre.

**Comment by CocoShaker** [comment]
Bonjour,
J'ai intégré le plus de modules possibles hier soir (sauf ceux extérieur) et ce matin ils semblent toujours ok.
Effectivement la mise à jour du FW semble avoir tout effacé., bon à savoir. Mais avant cela, je n'arrivais pas à réinclure un équipement, et ma clé ne répondait pas. Ca m'inquiète de ne pas connaître l'origine du problème, ça pourrait se reproduire...
Si ça te convient, je laisse ouvert l'issue pendant quelques jours, pour voir si je reperds tout à nouveau.
Merci encore pour ton aide !

**Comment by tcharp38** [comment]
Oui pas bon de pas savoir le souci d'origine.
Mais je ne comprends pas non plus comment l'erase PDM a été fait. Normalement il est fait uniquement si tu passes d'une version "legacy" vers "opdm" et plus de "opdm" vers "opdm"...

**Comment by CocoShaker** [comment]
Bonjour,

Comme promis je reviens après quelques jours pour faire un état des lieux.
J'ai réussi à réinclure mes équipements et ils sont stables et fonctionnels. Je ne sais pas ce qui s'est passé, j'espère que ça ne se reproduira pas. Je retiens que la réinstallation du même firmware a effacé tous mes devices... ou alors ils étaient perdus avant mais je ne sais pas comment.
Je ferme le ticket, merci pour ton aide !

**Comment by tcharp38** [comment]
Oui j'avoue que je n'ai pas compris pourquoi ca avait été effacé mais bon.. il subsiste encore qq points a améliorer sans aucun doute une fois qu'ils sont compris.

**Comment by CocoShaker** [comment]
Bonjour tcharp38,

Après 2 mois sans aucun soucis, j'ai eu exactement le même crash hier. Entre 11h et 12h, tous mes equipements sont passés en time-out. Je ne m'en suis rendue compte que le soir car mes lumières ne s'allumaient pas. J'ai tout de suite enregistré le package de logs.
J'ai essayé de réinclure une prise, ça a fonctionné mais elle a lâché avant 30 minutes. 
J'ai un capteur qui s'est réactivé tout seul dans la nuit, tous les autres équipements sont restés time-out. Là j'essaye de faire revenir les prises, mais ça relâche aussitôt. 
Voici le package de logs : 
[AbeilleLogs-231129.tar.gz](https://github.com/KiwiHC16/Abeille/files/13513423/AbeilleLogs-231129.tar.gz)
J'espère que tu pourras voir d'où ça vient.

Merci

**Comment by tcharp38** [comment]
Hello

Ha oui tout est en vrac.
Aucun device ne repond.

Dans les tests precedents tu etais en beta Abeille, la tu es de retour en stable.
Pourquoi et comment as tu procédé ?

**Comment by CocoShaker** [comment]
Non je m'étais remise en stable avant de refaire toutes les inclusions. Je n'ai touché à rien depuis (pas de maj). J'ai juste eu un nouvel équipement (Aqara détecteur mvt), inclus il y a 5-6 jours.

**Comment by CocoShaker** [comment]
Voici le package des logs actuel. Tu verras que j'ai réinclus une prise qui lâche à chaque fois. Seul le PIR
[AbeilleLogs-231130.tar.gz](https://github.com/KiwiHC16/Abeille/files/13514240/AbeilleLogs-231130.tar.gz)
 qui est revenu tout seul reste.

**Comment by tcharp38** [comment]
Est ce que tes soucis ne datent pas de l'inclusion de ce nouveau detecteur ?
D'ailleurs comment s'appelle t'il que j'essaie de le retrouver dans les logs ?

La zigate passe son temps à renvoyer une erreur. Je ne pige pas.
Pourrais tu desactiver tous tes devices sur secteur sauf le plug que tu as reinclus. On va limiter les requetes comme ca et tacher de voir ce qui se passe.

**Comment by CocoShaker** [comment]
Ca a commencé plus de 4 jours après donc ?
C'est "PIR A2 WC" (31A0)

**Comment by tcharp38** [comment]
La zigate passe son temps à renvoyer une erreur. Je ne pige pas.
Pourrais tu desactiver tous tes devices sur secteur sauf le plug que tu as reinclus. On va limiter les requetes comme ca et tacher de voir ce qui se passe.

**Comment by CocoShaker** [comment]
C'est fait. Je te refais un package ?

**Comment by tcharp38** [comment]
oui

redemarre Abeille
et donne moi le package 5mins apres STP

**Comment by CocoShaker** [comment]
J'ai réinclus 2 équipements sur pile pour vérifier, ça a fonctionné. Voici le package.
[AbeilleLogs-231201.tar.gz](https://github.com/KiwiHC16/Abeille/files/13525988/AbeilleLogs-231201.tar.gz)

**Comment by CocoShaker** [comment]
J'en ai 8 qui fonctionnent (les plus proches), je n'ai pas essayé ceux de l'étage. Apparemment ça tient.
J'espère que tu vas me dire qu'il y a une prise qui déconne, et qu'en l'enlevant tout pourra refonctionner ...

**Comment by tcharp38** [comment]
Jusque la je ne vois pas les erreurs du package precedent.
Il y a bien qqch qui fiche la pagaille mais je ne vois encore pas.

Peux tu laisser comme ca, lister les 8 qui sont supposés etre ok, et on regarde si ca tient ?

**Comment by CocoShaker** [comment]
OK, justement il y en a un qui est reparti : capteur ouverture entrée
![image](https://github.com/KiwiHC16/Abeille/assets/118360569/f44dc161-daf1-446c-a90c-f1c74b130e22)
[AbeilleLogs-231201 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13527418/AbeilleLogs-231201.1.tar.gz)

**Comment by CocoShaker** [comment]
Plus que 2 survivants...

**Comment by tcharp38** [comment]
Désactive le 49AD ([Energie][Prise conso Tuya]) il ne repond pas et ralenti tout.

**Comment by CocoShaker** [comment]
Elle a été désactivée avec les autres ce midi. Demon relancé, et j'ai même fait un reboot de jeedom. Mais on voit que la recup de la conso est toujours cron.
Comment puis-je faire pour l'arrêter ? Je vais la débrancher, mais ça ne changera rien.

**Comment by CocoShaker** [comment]
Dans ses commandes je vois ça : 
![image](https://github.com/KiwiHC16/Abeille/assets/118360569/39f84a5b-cbc1-4c65-baae-9f627b20a1e8)
je vais mettre le 1 à 0, mais de toute façon ce n'est pas normal que ça force la commande car car pas cochée et équipement désactivé, non ?

**Comment by CocoShaker** [comment]
C'est ok, la commande n'est plus lancée toutes les minutes.
Je retente les inclusions.

**Comment by tcharp38** [comment]
Ha tu veux dire que si l'equipement est désactivé les commandes qui doivent etre repetées sont quand meme executées ?
Si oui il doit y avoir un bug

**Comment by CocoShaker** [comment]
Oui c'est ce qui s'est passé. Ca aura au moins eu le mérite de trouver un bug ;o)
Bon sinon j'ai réactivé des équipements et ils remontent tout seuls (les prises) ! Je termine de réveiller les capteurs, et je te dis si ça tient.

**Comment by CocoShaker** [comment]
Même des équipements que je n'arrivais plus à inclure depuis la dernière fois (projecteurs LED exterieur) sont remontés tout seuls !! 
Pour le coupable, c'est peut être le modèle qui est à revoir (TS0121__TZ3000_rdtixbnu), ou la prise elle-même. Ou simplement la commande qui tentait de se réactualiser. Si je peux t'aider à trouver... Un dernier package de log pour la route !
[AbeilleLogs-231201 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13529709/AbeilleLogs-231201.2.tar.gz)

**Comment by CocoShaker** [comment]
Hello, en fait hier tout est remonté mais les commandes n'étaient pas opérationnelles. Ce matin tout est en time-out à nouveau.
[AbeilleLogs-231202.tar.gz](https://github.com/KiwiHC16/Abeille/files/13533627/AbeilleLogs-231202.tar.gz)

**Comment by tcharp38** [comment]
Désolé :(
Ca doit etre desesperant.
Je vois que plus aucun device ne repond. Ils sont tous en "NO ACK" et aucun device n envoi d'info non plus.

Comme si la zigate etait perturbée à un moment donné la foutant en vrac.
J'ai du mal à comprendre ce qui a changé pour arriver à cet état, ou comprendre qu'est ce qui se passe entre le moment ou ca fonctionne et celui ci ou personne ne donne signe de vie.

**Comment by tcharp38** [comment]
> Oui c'est ce qui s'est passé. Ca aura au moins eu le mérite de trouver un bug ;o) Bon sinon j'ai réactivé des équipements et ils remontent tout seuls (les prises) ! Je termine de réveiller les capteurs, et je te dis si ça tient.

Je viens de réaliser que j'avais déja corrigé ce pb dans la beta.
La stable que tu utilises commence a etre tres tres vieille et je n'ai pas encore eu l'occasion d'en faire une nouvelle.
Du coup si tu as un backup d'une version que tu consideres ok pour toi, ca te dit de revenir sur la beta ?

Ceci étant la beta ne fera pas de miracles.
Qqch perturbe la zigate la. Par ex un capteur à proximité, si tu le reveil, il devrait envoyer une info à la zigate que tu vois arriver dans le parser (un "report attribute" par ex).
On est donc dans la meme situation que tu avais eu il y a un moment.

Tu me résumes ta configuration HW ? Une zigate USB + RPI + ??  Les SSD ont tendance à perturber le zigbee tout comme une mauvaise alim, ou trop petite par rapport au nombre d'USB.. etc.

**Comment by CocoShaker** [comment]
Salut,
Merci pour ton message, pas dispo ce matin.
Je viens d'installer la beta, au point où j'en suis ça ne fera pas de mal.
Voici ma page santé : 
![image](https://github.com/KiwiHC16/Abeille/assets/118360569/49fdf696-371a-4418-87bc-13ee92f73277)

Je suis sur Jeedup depuis plus de 3 ans, et malgré les critiques moi je ne m'en plains pas. Ma zigate est sur un hub USB alimenté avec un autre dongle Enocean et RFPlayer.
Chez moi j'ai aussi un pont Hue et un bridge Tuya car certains devices étaient incompatibles avec Abeille. Les 3 ponts sont éloignés de 6 à 10m. J'ai aussi un routeur Syno pour le wifi, et 2 autres Mesh syno pour le wifi (étage et extension), dont 1 très proche de la Zigte. Je sais que ça fait beaucoup de perturbations... Mais c'est comme ça depuis le début.
Je me demande si ma Zigate n'arrive pas en bout de course, comment savoir si elle est défectueuse ? L'idéal serait de virer le bridge Tuya déjà, mais mes modules volets ne passent pas sous abeille.
Encore un grand merci pour ta dispo en tout cas !
Je surveille ce qui se passe avec la beta.

**Comment by CocoShaker** [comment]
Pas de grand changement. Les équipements se réveillent si je fais désactiver/activer, mais les commandes ne répondent pas et les capteurs ne renvoient pas leur état.
[AbeilleLogs-231202 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13536424/AbeilleLogs-231202.1.tar.gz)

**Comment by tcharp38** [comment]
Bon je réponds vite et je vais tacher de faire un peu autre chose que de la domotique. J'y passe beaucoup trop de temps ces jours ci :)

Oui ca fait beaucoup de perturbations.
Déja as tu vérifié que le canal zigbee utilisé n'est pas trop encombré ? C'est le 11 ici il me semble, à comparer avec ton occupation spectrale wifi (attention pas la meme numerotation).

Ensuite comme on peut souvent le voir sur le net, la zigate comme d'autres est tres sensible à toute perturbation electrique ou mauvaise alim USB. Le simple fait de changer de port peut changer la donne.
Un SSD perturbe beaucoup aussi. Il y a plein de lectures sur le sujet.
Mettre la zigate au bout d'un petit cable pour l'eloigner de perturbations peut aussi changer.
Bref il faut creuser la je pense.

Je regarderai tes logs + tard.

Quant à tes modules Tuya non reconnus, on peut etre retenter à l occasion. Tu ouvres un sujet spécifique pour l'un d'eux si il n'existe pas déja.

**Comment by tcharp38** [comment]
He.. peux tu juste refaire un "rafraichissement reseau" et me filer les logs ?

**Comment by CocoShaker** [comment]
Refresh reseau, voici les logs. 
[AbeilleLogs-231202 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13536545/AbeilleLogs-231202.2.tar.gz)
Je te dirai quel modèle pour volets, moi aussi, je vais profiter de ce we ... merci !!!!

**Comment by tcharp38** [comment]
Eh bien c'est bien ce que j'avais cru voir .. :(
La zigate ne connait plus que 2 équipements donc pas étonnant que personne ne reponde ou ne donne signe de vie

    [2023-12-02 15:38:16] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=8031, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=0000, DstAddrMode=02, DstAddr=0000
    [2023-12-02 15:38:16]   Management LQI response: SQN=67, Status=00, NTableEntries=02, StartIdx=00, NTableListCount=02
    [2023-12-02 15:38:16]   NExtPANId=1F3F96DAD76DD0CA, NExtAddr=00158D00053E7630, NAddr=0DC3, NBitMap=0212 => ?/Child/RxOFFWhenIdle/EndDevice, NDepth=01, NLQI=FF
    [2023-12-02 15:38:16]   NExtPANId=1F3F96DAD76DD0CA, NExtAddr=00158D0007352F58, NAddr=E25A, NBitMap=0212 => ?/Child/RxOFFWhenIdle/EndDevice, NDepth=01, NLQI=D3

Par contre ces 2 la etant toujours sur le reseau ils devraient donner signe de vie et je vois que c'est bien le cas.
Ces 2 la te parlent ? Tu as fait qqch de particulier ?

Maintenant comment expliquer que tous les autres ont disparu ?
Par curiosité, tu peux tenter de redemarrer Abeille (ca fait un reset de la Zigate dans la foulée), et rafraichissement reseau et voir si parfois tu en vois + ou -. Tu peux pour ça afficher la table des noeuds, au lieu de regarder les logs.

**Comment by CocoShaker** [comment]
Hello, 

Ce sont 2 equipements que j'ai réinclus manuellement. Mais ils lâchent au bout d'une heure ou 2 (des capteurs aqara).
OK pour le redémarrage Abeille, pas encore testé...

**Comment by CocoShaker** [comment]
J'ai désactivé Abeille, puis réactivé et relancé le demon (2 fois car la 1ere pas en debug).
Tous les equipements non désactivés sont UP, mais en fait ils ne répondent pas. Dans quelques heures ils seront time-out.
![image](https://github.com/KiwiHC16/Abeille/assets/118360569/84909101-3f3c-4753-ac70-3706a449f289)

[AbeilleLogs-231203.tar.gz](https://github.com/KiwiHC16/Abeille/files/13540085/AbeilleLogs-231203.tar.gz)

**Comment by tcharp38** [comment]
Le truc c'est que je ne vois toujours que 2 equipements dans ton reseau. Et c'est bien ce qui me chagrinne.
Ca n'est possible que si ils ont tous quitté le réseau (impossible), ou si on a effacé la PDM (mais la pourquoi et comment ?)

Les 2 qui sont actuellement tiennent ? 0DC3 & C714
Si oui peux tu en ajouter un ou 2 de + qui sont proches de la zigate ? ca veut dire reinclusion.

Concernant le status au démarrage je pense qu'il est a revoir.

**Comment by CocoShaker** [comment]
Oui les 2 tiennent, ils sont toujours UP. Il y en a un qui ne renvoie pas son état, mais l'autre c'est ok. Par contre depuis la beta j'ai ce message : `getDeviceModel(): Modèle 'rucheCommand' inconnu.`
J'ai inclus un autre à l'instant (Capteur ouverture entrée F7EC), qui renvoie bien son état. Voici les logs, je regarde si toujours ok dans 2 heures.
[AbeilleLogs-231204.tar.gz](https://github.com/KiwiHC16/Abeille/files/13547604/AbeilleLogs-231204.tar.gz)

**Comment by tcharp38** [comment]
Oui on m'a signalé ce souci d'erreur mais je n'arrive pas à reproduire.
A voir sur la beta de demain. J'étais en train de faire d'importants changements.

Tu peux désactiver AED7, il est NO ACK et ne fait pas partie du reseau actuellement.

Quel est celui qui ne remonte pas son etat ?

**Comment by CocoShaker** [comment]
Je l'ai désactivé (détecteurouverture aqara). Mais de toute façon ils sont tous en time-out. Et en fait aucun ne renvoyait son état au bout de quelques minutes. Je déprime totalement ! Demain je suis en teletravail, je serai plus dispo pour tenter des trucs, si tu as des idées.

**Comment by tcharp38** [comment]
Pas sur que tu aies compris ce que je disais... alors je résume.
Ta Zigate ne connait que 2, ou plutot 3 devices. Tous les autres ne font plus partie du reseau donc ne peuvent ni recevoir d'info ni en envoyer.
Ca c'est la bonne nouvelle car il suffit normalement de les reinclure et ils seront de retour.

La mauvaise nouvelle est que je n'ai pas compris pourquoi tout à disparu du reseau.

Maintenant.. on y va pas à pas pour etre sur que ceux reinclus tiennent et restent.
Autant se focaliser sur les routeurs à proximité de la zigate en premier.

Tu me suis ?

**Comment by CocoShaker** [comment]
Si, si j'ai bien compris. Mais j'ai fait l'exercice plusieurs fois de réinclure des prises ou autres devices. La log me monte inclusion OK, device connu, mais ensuite aucune commande ne fonctionne, et aucun retour d'état. A chaque fois je crois que c'est OK mais passé l'inclusion l'équipement fait le mort. Et au bout de quelques heures, time-out. 
Je pense que c'est ma zigate qui a pété un cable, je ne vois pas pourquoi ça déconne comme ça sans aucun changement dans mon environnement.

**Comment by tcharp38** [comment]
Il peut y avoir plusieurs choses.
Ca n'est pas parce qu'il est dans le reseau qu'il ne peut pas avoir de soucis de config.

Bref..  quels sont ceux que tu as reinclus et quel est leur status ?
Si ils sortent à nouveau du reseau sans raison alors oui peut etre que la Zigate a un souci

**Comment by CocoShaker** [comment]
Salut,

Pour info j'ai abandonné car mes devices que j'arrivais à réinclure ne répondaient qu'au moment de l'inclusion puis plus rien. Que ce soit des capteurs à pile ou des prises. Aucune commande ne passait.
Je ne pense pas que cela vienne du plugin, comme j'avais eu par 2 fois déjà le soucis avant que tout ne refonctionne. Je pense que ma Zigate ne fonctionne plus très bien (4 ans). J'ai donc acheté une Deconz et suis passée sur un autre plugin.

Merci pour toute l'aide que tu m'as apportée. Le plugin Abeille est vraiment top !

**Comment by tcharp38** [comment]
Salut @CocoShaker
Désolé de lire cela mais je comprends tout à fait. J'espère que Deconz t apportera meilleure satisfaction, ainsi que le plug-in associé.
Bonne continuation
