### ISSUE TITLE
1 équipement, nouvelle adresse à chaque "réinclusion"

### ISSUE THREAD

**Issue by Jake309** [KiwiHC16/Abeille#2625]
Salut,

Je tiens un phénomène étrange. Finalement les capteur d'ouverture xiaomi avec la zigate, c'est toujours compliqué.
Mon capteur : Baie vitrée (FB17) était en time out, j'ai voulu le réintégrer en ne le voyant plus changer détat.
je l'ai fais 2 fois, et j'ai eu 2 nouveau équipement pour chaque réintégration: 3AEA et 8BC4.
J'ai eu le pb avec tout mes capteurs d'ouverture, maintenant que je recolle les morceaux des derniers mois (j'ai pas été efficace sur l'installation de ces capteurs), mais ca m'arrivait à chaque fois pratiquement.

J'ai essayé avec un interrupteur, j'ai pas le pb, juste le message de mon autre issue (ERREUR: Unknown device: Net=Abeille1 Addr=90C8).
Tu le verras pas dans les log, j'ai testé en tapant le message :)

Mon capteur est baie vitrée est facile d'accés, on peut jouer avec sans problème pour les besoin du debug.
Cette semaine j'aurai le temps en soirée de pouvoir tester et te répondre Tcharp (et tout les jours jusqu'à la naissance de la 2eme) :)

Pour rappel, Zigate V1 firmware lu par abeille : 0004-0323

[AbeilleLogs-231001.tar.gz](https://github.com/KiwiHC16/Abeille/files/12776570/AbeilleLogs-231001.tar.gz)

**Comment by Jake309** [comment]
Je sais pas si tu le verras dans les log, ca remonte à vendredi, ou peut etre dans ce de l'autre issue.
Le detecteur de présence 3AB2 a été créé suite à réinclusion alors qu'il fait partie de mes plus vieux équipements

**Comment by tcharp38** [comment]
Alors pour ce sujet je pense avoir corrigé qqch qui n'est pas encore dans la beta.

**Comment by Jake309** [comment]
ha c'est cool :)

**Comment by tcharp38** [comment]
Donc a confirmer avec la beta de demain
231002-BETA-1

**Comment by tcharp38** [comment]
@Jake309 
Des que tu as des nouvelles je regarde. Je veux faire une stable et je crois que c'est le dernier point qui me freine un peu

**Comment by Jake309** [comment]
Salut !
Je viens de voir la beta, j'avais pas eu la notif sur jeedom, il se comporte étrangement ces denriers jours.
Je fais des test et te tiens au courant :)

**Comment by Jake309** [comment]
Salut Tcharp !!!
Plus de probleme, j'ai un capteur récalcitrant que je réintegre tout les jours, et je n'ai plus de création de nouvel équipement.
Je clos, tu réouvres si tu veux qu'on fasse des tests :)

**Comment by tcharp38** [comment]
Salut @Jake309 
Cool pour ce sujet.

Concernant ton capteur recalcitrant tu as une piste ? Normalement c'est un souci de couverture reseau, ou perturbation Wifi par ex.
