### ISSUE TITLE
Ikea Tradfri E27 LED2102G3 sans réponse

### ISSUE THREAD

**Issue by rsuard** [KiwiHC16/Abeille#2626]
Hello,

Je crois que ce modèle IKEA que je viens d’acquérir ne répond pas.
Est ce possible de voir si je peux le connecter comme une autre ampoule ikea ?

Merci beaucoup, 
Excellente journée

**Comment by tcharp38** [comment]
Salut @rsuard 
Si il ne s'annonce pas tu ne peux rien faire. C'est la base.

- Passer en mode debug
- mode inclusion
- forcer l'inclusion de ta LED
- et me filer les logs (page maintenance/telecharger tout)

Mais encore une fois tant qu'il n'est pas reconnu au moins comme un equipement inconnu rien n'est possible.
Et verifier que la LED de la Zigate clignote en mode inclusion

**Comment by rsuard** [comment]
Hello,

Merci pour ta réponse,
Je vais tenter, quand tu dis « forcer l’inclusion » il y a un truc particulier ?
D’habitude je clic juste sur l’inclusion je lance la procédure sur le Device (en fonction de son appairage) mais je ne force rien ?

Bien à toi,

**Comment by tcharp38** [comment]
Si la Zigate clignote.. c'est qu'elle a ouvert le reseau et est donc prete à accepter n'importe quel device qui se presente.
Mais si ce dernier ne se presente pas... la elle ne peut rien faire.

On doit voir des "Device announce" dans le log du parser si ce device s'annonce vraiment et la comme tu dis, la procedure depend du device.

Bref tant qu'il n'y a pas de "device announce" (en supposant que la Zigate est bien en attente), le pb est cote device.

Ca aide ?

**Comment by rsuard** [comment]
Hello,

Pas sur de voir grand chose, voici les logs, auraient ils changer le protocole sur ces ampoules ?
https://www.dropbox.com/scl/fi/9ckxtro14zrcjtl4vpk1n/Abeille?rlkey=ezuzgxhqx4z0yovwis5n3v5if&dl=0

Un grand merci

**Comment by tcharp38** [comment]
Pour tout support, pense à copier/coller le package de logs generé via la page "maintenance" + "telecharger tout".
C'est tres complet et tu n'as qu'a faire un drag & drop ici. Pas besoin de passer par dropbox.

Ceci je ne vois rien dans ron log "Abeille". Le + important pour ton cas est "AbeilleParser.log" dans lequel tu dois voir un "device announce" passer.
Le protocole ne peut avoir changé. Si Zigbee... la procedure est toujours la meme.

Par contre la maniere de le mettre en mode inclusion la c'est toujours specique.

Si tu peux
- passer en mode inclusion => la zigate clignote
- brancher ton ampoule (à priori rien à faire pour qu'elle se mette en attente)
- me filer le package de logs au bout de 5min
Je regarderai si qqch me parle

**Comment by rsuard** [comment]
Hello @tcharp38 
merci pour tes retours et désolé pour le temps de réponse.
Voici les logs :
[AbeilleLogs-231018.tar.gz](https://github.com/KiwiHC16/Abeille/files/12994978/AbeilleLogs-231018.tar.gz)
Merci pour tes retours. 
PS : je crois que j'ai un souci, j'ai une ampoule qui arrivent dans ma conf sans savoir quand (hors inclusion) et elle revient meme si je la supprime du réseau. Elle vient se remettre dans l'objet parent toute seule, et je n'arrive pas à savoir ou elle est physiquement, c'est un fantome.

**Comment by tcharp38** [comment]
Salut @rsuard 

Je ne vois aucune annonce d'un device quelconque dans les logs. Donc rien à faire cote Abeille pour l'instant.

Ta Zigate v2 est en v3.20. Si le dernier FW 3.A0 n'est pas forcement recommandé, peut etre devrais tu au moins passer en 3.22.

Concernant ton fantome, est ce toujours la meme adresse IEEE ? Si oui laquelle ?

Accessoirement tu es sur la derniere stable, qui date maintenant. La beta est bien + en avance

**Comment by rsuard** [comment]
Hello, 

Merci pour toutes tes réponses. 

Pour ce qui est de l'ampoule fantome, voici les info : 
![ampoule-fantome](https://github.com/KiwiHC16/Abeille/assets/32543811/477938f0-7669-4085-b3c4-d26f39fb8e61)
![IEEE](https://github.com/KiwiHC16/Abeille/assets/32543811/a6e97f0d-ac19-4843-81db-bef97d9ec25b)
![journal](https://github.com/KiwiHC16/Abeille/assets/32543811/5a5adc84-df96-4355-a798-f52893d386a6)

Pour la lampe ikea, c'est celle ci, étrange qu'elle ne dise rien non ?
https://www.ikea.com/be/fr/p/tradfri-ampoule-led-e27-470-lumen-connecte-sans-fil-a-variateur-dintensite-blanc-chaud-transparent-globe-90539072/

Pour la zigate, c'est en fait une pigate... que je n'arrive pas à flasher, je ne sais pas trop pk, j'ai une erreur de gestion des GPIO je crois. 
voir : 

//

2023-10-19 20:23:05] Log max reached (490 lines). Previous log saved as '/tmp/jeedom/Abeille/AbeilleConfig-prev.log'
[2023-10-19 20:23:07] Démarrage de 'checkTTY.sh'
[2023-10-19 20:23:07]  Vérifications du port '/dev/ttyAMA0'
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
Output information may be incomplete.
[2023-10-19 20:23:07] = Ok, le port semble libre.
[2023-10-19 20:23:07] Configuration des GPIOs
Verification de l installation du package 'pigpio'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Can't connect to pigpio at localhost(8888)
Did you start the pigpio daemon? E.g. sudo pigpiod
Did you specify the correct Pi host/port in the environment
variables PIGPIO_ADDR/PIGPIO_PORT?
E.g. export PIGPIO_ADDR=soft, export PIGPIO_PORT=8888
Did you specify the correct Pi host/port in the
pigpio.pi() function? E.g. pigpio.pi('soft', 8888)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
= ERREUR: Commande 'gpio' manquante ou non executable !
=         Le package WiringPi est probablement mal installe.
[2023-10-19 20:23:07] Configuration du port série
[2023-10-19 20:23:07] = Ok
[2023-10-19 20:23:07] zgGetVersion()
[2023-10-19 20:23:07] Interrogating zigate on port /dev/ttyAMA0
[2023-10-19 20:23:07] zgWrite(0010000010)
[2023-10-19 20:23:07] zgRead()
[2023-10-19 20:23:07]   Read=800000099D000000100000050100
[2023-10-19 20:23:07] zgRead()
[2023-10-19 20:23:07]   Read=80100005B30005032000
[2023-10-19 20:23:07] FW version 0005-0320
[2023-10-19 20:23:20] updateFirmware(PI, ZiGate_v3.21-OPDM.bin, WiringPi, /dev/ttyAMA0)
[2023-10-19 20:23:20] Checking parameters
---------------------------------
Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0 WiringPi
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
---------------------------------
Démarrage de 'updateFirmware.sh' flash /dev/ttyAMA0 WiringPi ZiGate_v3.21-OPDM.bin
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
Lancement de la programmation du firmware
- Port tty: /dev/ttyAMA0
- Firmware: ZiGate_v3.21-OPDM.bin
JennicModuleProgrammer Version: 0.7(r56124)+
= ERROR: Failed to read chip ID.
=        Check Zigate GPIO control (flash mode set + reset pulse required) !
= ATTENTION !!!
= Quelque chose s'est mal passé. Veuillez vérifier le log ci-dessus.
[2023-10-19 20:30:24] Démarrage de 'checkWiringPi.sh'
[2023-10-19 20:30:24] Vérification de l'installation du package 'WiringPi'
[2023-10-19 20:30:24] = Ok
[2023-10-19 20:30:29] updateFirmware(PI, ZiGate_v3.21-OPDM.bin, WiringPi, /dev/ttyAMA0)
[2023-10-19 20:30:29] Checking parameters
---------------------------------
Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0 WiringPi
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
---------------------------------
Démarrage de 'updateFirmware.sh' flash /dev/ttyAMA0 WiringPi ZiGate_v3.21-OPDM.bin
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
Lancement de la programmation du firmware
- Port tty: /dev/ttyAMA0
- Firmware: ZiGate_v3.21-OPDM.bin
JennicModuleProgrammer Version: 0.7(r56124)+
= ERROR: Failed to read chip ID.
=        Check Zigate GPIO control (flash mode set + reset pulse required) !
= ATTENTION !!!
= Quelque chose s'est mal passé. Veuillez vérifier le log ci-dessus.
[2023-10-19 20:31:09] updateFirmware(PI, ZiGate_v3.21-OPDM.bin, WiringPi, /dev/ttyAMA0)
[2023-10-19 20:31:09] Checking parameters
---------------------------------
Démarrage de 'updateFirmware.sh' check /dev/ttyAMA0 WiringPi
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
---------------------------------
Démarrage de 'updateFirmware.sh' flash /dev/ttyAMA0 WiringPi ZiGate_v3.21-OPDM.bin
Vérifications préliminaires
/var/www/html/plugins/Abeille/core/ajax
= Ok
Lancement de la programmation du firmware
- Port tty: /dev/ttyAMA0
- Firmware: ZiGate_v3.21-OPDM.bin
JennicModuleProgrammer Version: 0.7(r56124)+
= ERROR: Failed to read chip ID.
=        Check Zigate GPIO control (flash mode set + reset pulse required) !
= ATTENTION !!!
= Quelque chose s'est mal passé. Veuillez vérifier le log ci-dessus.

//

J'ai deux clé USB mqtt je crois, que j'ai eu avec des ampoules d'occas, est ce mieux que je les utilise ?

Pour ce qui est de la béta, comment je l'active ?

J'ai un gros souci ce soir, plus aucun de mes appareils ne réponds...

Merci encore pour ton aide.

Belle soirée

**Comment by tcharp38** [comment]
Ouah, beaucoup de choses la.

On ne va garder que le sujet "ampoule" ici.
ouvre un autre sujet "Probleme flashage PI Zigate v2" STP.

Donc pour l'ampoule, normalement tu devrais pouvoir la piloter avec une telecommande Ikea sans passer par la Zigate.
En suivant les instructions Ikea ca doit rouler tout seul. Si déja ca n'est pas fonctionnel.. alors ton ampoule est peut etre defectueuse. Raison pour laquelle elle ne s'annonce pas dans le reseau Abeille.
Ca fait du sens ?

Cote beta Abeille.. regarde ca https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

Dernier point: au lieu de copier des parties de log, mets moi le package de logs complet de la page maintenance.
Je n'ai pas assez d'infos ici.

**Comment by rsuard** [comment]
Bonsoir, 

désolé, je vais ouvrir 2 autres tickets. 
Je n'ai pas de télécommande ikea, ni de passerelle ikea d'ailleurs. Je pensais pouvoir l'inclure comme les autres produits ikea. Tant pis, je la mettrai derriere un sonoff mini.

Je vais continuer de fouiller ce point...

Merci encore, je posterai ici si je trouve pour la lampe. 

PS : je suis passer en BETA.

**Comment by tcharp38** [comment]
Salut
Les produits ikea jusque là fonctionnent avec abeille et zigate.
L'idée de la télécommande ikea était juste d essayer d éliminer une piste car jusque la je ne vois rien qui pointe vers la zigate ou même abeille

**Comment by rsuard** [comment]
Hello, 
J'ai acheté un lanceur de scénario ikea, je vais voir si il marche et si je peux le triguer en direct. pas sur qu'il fasse office de télécommande sans plateforme.
J'ai aussi pris des capteurs de présence (je crois que c'est une version pas dans la doc...) qui eux sont peut être appairables en direct sur une ampoule...
J'ai regardé sur la boite pour me rassurer, c'est bien des ampoule zigbee, ça devrait donc poper à un moment non ?
Je regarde dès que je finis mes travaux,
Merci pour tes retours

**Comment by rsuard** [comment]
Hello, 
J'ai fini mes travaux et donc mis ma PiZigate à son emplacement presque définitif et surtout déballé le reste des produits IKEA. 
La deuxieme ampoule est apparue direct !  
Voici les logs, je vais tenter de suivre ton process de découverte des commandes dans ta doc. 
[AbeilleLogs-231127.tar.gz](https://github.com/KiwiHC16/Abeille/files/13480565/AbeilleLogs-231127.tar.gz)
Belle soirée, 
Romain

**Comment by rsuard** [comment]
@tcharp38 et voila ! 
[discovery-TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.json.zip](https://github.com/KiwiHC16/Abeille/files/13480797/discovery-TRADFRIbulbE27WWG95CL470lm_IKEAofSweden.json.zip)
et l'image à associer : 
<img width="894" alt="tradfri-ampoule-led-e27-470-lumen-connecte-sans-fil-a-variateur-dintensite-blanc-chaud-transparent-globe__1143858_pe881648_s5" src="https://github.com/KiwiHC16/Abeille/assets/32543811/d09abbad-72ab-4d6c-9688-61665013f636">
Merci pour ton aide !

**Comment by tcharp38** [comment]
Salut @rsuard 
Donc ca veut dire que ta premiere ampoule est HS. Meme vision ?

En dehors de l'image à corriger, il reste autre chose à voir sur ce sujet ?

**Comment by rsuard** [comment]
hello @tcharp38 
j'ai débranchée la seconde, j'ai retenté l'appairage et elle a pris ! 
Nope, le reste est bon je pense (il reste un endpoint en orange dans ton outil de découverte mais je pense pas que ça pose souci ?)
Merci, je peux clore si tu veux.

**Comment by tcharp38** [comment]
Ok on ferme le sujet du coup. 
Qu'il reste qqch en orange dans l'assistant n'est pas surprenant. Certans devices ne prennent meme pas la peine de repondre "je ne supporte pas cet acces".
