### ISSUE TITLE
Ajout support AEOTEC Range Extender Zi (id = WG001-Z01, AL001)

### ISSUE THREAD

**Issue by baloo53** [KiwiHC16/Abeille#2627]
Bonjour tout le monde ,

Mon réseau zigbee étant pas stable j'ai décidé, à force de lecture sur le net, d'acheter ce répéteur zigbee
[https://www.amazon.fr/AEOTEC-Extension-port%C3%A9e-R%C3%A9p%C3%A9teur-Augmentation/dp/B0B4P3Y7VH/ref=asc_df_B0B4P3Y7VH/?tag=googshopfr-21&linkCode=df0&hvadid=603256915161&hvpos=&hvnetw=g&hvrand=11905438410056064385&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9055639&hvtargid=pla-1722870687255&psc=1](url)

J'ai lancé mon inclusion sur le plugin, il a bien été détecté mais inconnu :/ J'ai donc regardé la page du plugin sur "l'assistant découverte" et je pense avoir fait le job :) 

Je vous communique donc tout les info que j'ai. 

![1](https://github.com/KiwiHC16/Abeille/assets/99254403/46fbcd5e-645d-4a1d-9443-b27cd338330d)
[discovery-WG001-Z01_AL001.zip](https://github.com/KiwiHC16/Abeille/files/12792824/discovery-WG001-Z01_AL001.zip)

**Comment by tcharp38** [comment]
Salut

J'ai besoin
- du type de batterie
- d'une image au format PNG SANS arriere plan

En attendant tu peux tester avec ce modele a decompresser dans Abeille/core/config/devices
[WG001-Z01_AL001.zip](https://github.com/KiwiHC16/Abeille/files/12793551/WG001-Z01_AL001.zip)

**Comment by baloo53** [comment]
D'une image PNG sans arrière plan? excuse moi je comprends pas (néophyte ^^)
Pour la batterie c'est sur secteur enfaite

**Comment by tcharp38** [comment]
J'ai besoin d'une image pour mettre une icone sur ce type d'equipement.
Donc image au format PNG et non pas JPG
et pas de fond blanc mais un fond transparent

**Comment by baloo53** [comment]
En espérant que cela te va car j'ai galéré ^^ 
pour info sur la prise j'ai un numéro de model : ZGA001-C15

![Répétiteur](https://github.com/KiwiHC16/Abeille/assets/99254403/186a607d-e041-49b9-9f66-1fea1b03c94f)

**Comment by tcharp38** [comment]
J'ajoute ca pour la prochaine beta.
merci

As tu testé le modele ?

**Comment by baloo53** [comment]
Non pas encore. J'ai peur de faire des bêtises ^^ 
Je passe en mode beta pour faire sa? Et après je place le zip décompression vers Abeille/core/config/devices ?

Pour info dans la section santé du plugin je suis au vert (statut OK)

**Comment by tcharp38** [comment]
Ha oui c'est vrai que passer en beta d'abord fait du sens.
Il y a trop d evolutions et le modele est aligné sur le dernier code.. donc la beta.

Du coup je fais une nouvelle beta (231004-BETA-1) pour demain avec ce modele et l'image.
Tu pourra basculer dessus directement et on avise.

**Comment by baloo53** [comment]
D'accord alors j'attends demain pour mettre mon plugin en beta alors. 
Tu me diras aussi les tests que tu désires que j'effectue

**Comment by baloo53** [comment]
Je suis passé sur la beta. Tu a besoin que j'effectue quoi comme tests ?

**Comment by tcharp38** [comment]
Salut @baloo53 
Tu peux donc tenter de reinclure ton "extender".
Et me filer le package de logs 5mins apres

**Comment by baloo53** [comment]
Ok voici la manipulation effectué (je préfère détailler)
En version béta:
-Passage en mode débug
-Suppression de l'équipement
-Passage en mode inclusion
-Réinitialisions de l'équipement (une minute après le temps de comprendre qu'il faut rester appuyer sur le bouton 20s)   
-Détection de l'équipement ( Avec la photo que je tes fournie)
-Attente de 5min
-Téléchargement des logs 

Voili voilou :)

[AbeilleLogs-231006.tar.gz](https://github.com/KiwiHC16/Abeille/files/12834600/AbeilleLogs-231006.tar.gz)

**Comment by tcharp38** [comment]
Salut @baloo53 
Je vois le device qui s'annonce bien donc (device => zigate)
Sauf que le retour vers le device semble toujours sans acquittement (NO ACK). Comme si le chemin de retour ne fonctionnait.

Tu serais sur une zigate v2  ca ne me surprendrait pas (Dernier FW pas top) mais la..perturbation wifi ?
Quand tu fais l'inclusion, l extender est loin de la Zigate ? A proximité ?

Je note que tu n'es pas sur le meilleur FW de ta V1. Tu es en 3.21 alors que la 3.23 existe.
Je te suggere aussi de faire cette mise à jour en 3.23 OPDM.

**Comment by baloo53** [comment]
Salut @tcharp38 

Alors pour l'extender, il est à 2m de ma zigate. Je les laissé à côté le temps de nos tests.

Pour mon FW je vais voir en effet pour passer sur le 3.23. Je vais essayer de trouver un protocole ludique pour faire sela car la dernière fois que j'ai fais sa (il y a 2/3ans) j'ai supprimé tout mes équipements hahaha

Tu pense que si je met à jour mon FW tu va y voir plus clair ou tu a besoin d'autres choses ?

**Comment by baloo53** [comment]
Bon et bien je savais bien que j'allais faire une boulette ^^ 

Se que j'ai fais:
J'ai suivi la procédure : [https://zigate.fr/documentation/mise-a-jour-de-la-zigate/](url)
J'ai PAS effectué la ligne 7 (pour pas effacer mes équipement si j'ai bien compris)
j'ai utilisé ce FW : [ZiGate v3.23 (OPDM)](https://github.com/fairecasoimeme/ZiGate/releases/tag/v3.23-opdm)

Lors du flash aucun message d'erreur, je replace ma clé sur mon raspi et redémarre jeedom
Sur le plugin je relance les demon ==> OK 
En revanche maintenant ma clé est plus détecté :/ 
  
[AbeilleLogs-231009.tar.gz](https://github.com/KiwiHC16/Abeille/files/12848746/AbeilleLogs-231009.tar.gz)

![IMG_20231009_193246](https://github.com/KiwiHC16/Abeille/assets/99254403/580dd39c-9810-4609-ba7d-342bc38a5e71)
J'ai vu se test la à effectuer sur le PC et je suis ok aussi

**Comment by tcharp38** [comment]
La procedure que tu as suivi me semble correcte.
Mais tu n'es pas en mode debug alors je n'ai pas de traces

Ha et passe à 5000 lignes de log et non pas 500.
C est trop court 500.

**Comment by baloo53** [comment]
Oui désolé j'avais oublié.

[AbeilleLogs-231009 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/12849537/AbeilleLogs-231009.1.tar.gz)

**Comment by tcharp38** [comment]
Salut
Tu n'as pas sur la derniere beta (231009-BETA-1)

J'imagine que ton systeme est toujours HS aujourd hui ?

**Comment by baloo53** [comment]
Salut, 

Oui en effet toujours HS. :/

**Comment by tcharp38** [comment]
Alors tente un truc
- Sur la  page de config, desactive la gestion automatique du demon
- Arrete Abeille
- Attends qq mins
- Et fait un test du port serie
et file moi les logs STP

**Comment by baloo53** [comment]
J'espère avoir bien fait les choses :)
Bizarrement j'ai l'impression que ma clé est en mode "flash" led rouge avec petite led bleu, pourtant mon flash c'est très bien déroulé

[AbeilleLogs-231010.tar.gz](https://github.com/KiwiHC16/Abeille/files/12858327/AbeilleLogs-231010.tar.gz)
[AbeilleLogs-231010 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/12858447/AbeilleLogs-231010.1.tar.gz)

**Comment by tcharp38** [comment]
Toujours tout HS ?
En fait je vois dans les logs une situation jamais comprise.

As tu supprimé la gestion automatique des démons et arrété les démons ?
Apres quoi le "TESTER" sur le port de la Zigate doit remonter ok.
C'est le cas ?

**Comment by baloo53** [comment]
Normalement j'ai bien fait sa. Et non toujours rien malheureusement :/ 
Voici d'autres log si sa peut t'aiguiller 
[AbeilleLogs-231010.tar.gz](https://github.com/KiwiHC16/Abeille/files/12860310/AbeilleLogs-231010.tar.gz)

**Comment by tcharp38** [comment]
C'est bien de mettre les logs à chaque fois.
Je ne vois aucune zigate active.
Par hasard ne serait elle pas en mode "desactivé" sur la page config ?

**Comment by baloo53** [comment]
Bon, après avoir refait une mise à jour sur la 21 puis de nouveau sur la 23 cela semble fonctionner.
Du coup revenons à nos moutons.
J'ai exclu l'extender de mon jeedom, je suis passer en mode debug, activer le mode intégration, l'extender à été détecté puis j'ai attendu 5min.
Voici les logs
[AbeilleLogs-231010 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/12860757/AbeilleLogs-231010.3.tar.gz)

**Comment by tcharp38** [comment]
Tu vois des soucis ? Il m'a l'air d etre bien intégré la

**Comment by baloo53** [comment]
Pas de problème particulier en vue. C'est sensé améliorer la fiabilité de mon réseau. Un moyen de voir son efficacité via les logs ou bien une manipulation particulière ? Histoire qu'on confirme ensemble

**Comment by tcharp38** [comment]
Alors ca n'améliore que si un device decide de passer par le router au lieu de son ancien chemin.

Manque de pot je ne suis pas encore satisfait de ce que propose Abeille pour voir le "routage".
J'avais commencé de retravailler le "placement reseau" dans lequel
- tu mets le plan de ta maison
- tu places tes equipements
- et tu vois les liaisons et faiblesses, y compris le chemin utilisé
Mais ca n'est pas finalisé.

Ha si tu peux le voir via le reseau, tu verra si un equipement est relié à ton routeur ou pas.

**Comment by baloo53** [comment]
D'accord, merci pour l'information. 
Si je peux aider pour quoique ce soit (partage de log, d'objet, placement réseau) dit le moi en tout cas

**Comment by tcharp38** [comment]
Tu penses du coup que ce sujet peut etre fermé ?

Concernant le placement réseau il y a un sujet ouvert. Tu peux tenter de l'utiliser et me remonter ce qui te bloque.
Pour moi il manque toujours une gestion des differents "niveaux" si tu habites en maison

**Comment by baloo53** [comment]
Le sujet peut être clôturé si tout est bon pour toi.
Je vais voir le topic pour les placement réseau car oui j'ai une maison à deux étages et atelier donc si sa peut aider ^^
