### ISSUE TITLE
Ajout Télécommande infrarouge Zigbee (ID=TS1201__TZ3290)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2628]
Bonjour,

J'ai acheté une télécommande infrarouge Zigbee, dans le but de commander quelques appareils (dont clim) mais elle n'est pas reconnue.

A noter la bête est sensé avoir une fonction pour apprendre des codes infrarouge... je ne vois pas trop comment cela peut fonctionner avec l'interface (?)

Voici la découverte réalisée et un PNG.
(alimentation avec 2xAAA)
![commande-IR](https://github.com/KiwiHC16/Abeille/assets/144285463/cdfc7968-1655-447a-aa2d-fa67684d75d1)
[discovery-TS1201__TZ3290_ot6ewjvmejq5ekhl_infra-rouge.zip](https://github.com/KiwiHC16/Abeille/files/12846781/discovery-TS1201__TZ3290_ot6ewjvmejq5ekhl_infra-rouge.zip)

**Comment by tcharp38** [comment]
Gros sujet deja en cours.
Voir la https://github.com/KiwiHC16/Abeille/issues/2607

Je clos celui ci
