### ISSUE TITLE
Ajout prise alarme / sirène (ID=TS0224, _TZ3000_cipibmnp)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2629]
Bonjour,

J'ai acheté cette prise alarme / sirène dans le but de quelques scénarios, mais elle ne semble pas reconnue dans ma ruche...

Voici la découverte (complète) et un PNG.
![prise-alarme](https://github.com/KiwiHC16/Abeille/assets/144285463/586d2143-6844-4fad-ae56-2e08787eec04)
[discovery-TS0224__TZ3000_cipibmnp_alarme.zip](https://github.com/KiwiHC16/Abeille/files/12846806/discovery-TS0224__TZ3000_cipibmnp_alarme.zip)

**Comment by M4dd4M** [comment]
![prise-alarmev2](https://github.com/KiwiHC16/Abeille/assets/144285463/89a143a0-6531-4dca-bd8c-599a86734b11)

**Comment by tcharp38** [comment]
Salut @M4dd4M 

Qq requetes
- si tu n'es pas sur la beta Abeille il faudrait que tu bascules dessus. Trop de modifs depuis la derniere stable
- quelle est la marque et modele ?
- d'autre part as tu la liste des commandes que tu attends ?

Je pousse une beta (231009-BETA-1) pour demain avec un support preliminaire.

**Comment by M4dd4M** [comment]
Je vais basculer vers la beta dans la semaine.
Je n'ai pas de liste des commandes exactes, mais a priori ça devrait être un truc du genre :
 - on/off de la sirène (avec un niveau de volume ?)
 - Contrôle de la lumière coloris / intensité (et vitesse de flash ?)

**Comment by tcharp38** [comment]
Il y a un modele dans la derniere beta.
Peux tu reinclure ton alarme, et tester ?
Il y a surement des choses en trop, qui ne fonctionnent pas, voir meme qui manquent.

**Comment by M4dd4M** [comment]
Salut,
J'ai réinclus l'alarme , c'est mieux avec l'icone qui va bien :-)
Bon, y'a plein de choses effectivement 👍
 - Les boutons ON et OFF allument et éteignent la lumière.
 - Tous les boutons pour changer les couleurs / température sont sans effets.
 - Il y a un report de statut de l'alarme 
 ... mais rien pour lancer sirène. (j'ai testé tout les actionneur dans la config avancée)

**Comment by tcharp38** [comment]
Sauf erreur ce truc ne sait pas changer la couleur. Je vire donc tout ce qui controle de couleur.
Mais on devrait avoir un controle de volume et un controle de luminosité a priori.

Je revois ma copie.

**Comment by tcharp38** [comment]
Je te laisse ecraser le modele par celui ci
[TS0224__TZ3000_cipibmnp.zip](https://github.com/KiwiHC16/Abeille/files/12922235/TS0224__TZ3000_cipibmnp.zip)

puis refaire une inclusion
et tester

**Comment by M4dd4M** [comment]
@tcharp38 c'est pas mal, on est quasi tout bon avec ça !
La sirène se déclenche et peut être arrêtée, et de façon réactive.
La lumière également.

Après, ce que je remarque :
 - Le niveau choisi pour le réglage du volume de l'alarme n'a pas d'incidence ,cela déclenche avec la même intensité (normalement, cela plusieurs niveau serai possible d'après le descriptif du produit)
 - Il n'y a qu'une couleur pour la led, et sans réglage d'intensité (là aussi, d'après le descriptif, couleur et intensité son variable)
 
Après, si c'est trop compliqué, tu peux laisser comme ça car c'est fonctionnel.

**Comment by tcharp38** [comment]
On peut creuser un peu.
Par rapport à tout ce qui est sur le dashboard tu me resumes les effets de chaque bouton ?

**Comment by M4dd4M** [comment]
alors les effets des boutons :
identify -> je ne sais pas, a priori rien
ON -> allume la lumière
OFF -> éteint la lumière
Siren -> curseur de 0 à 3 -> allume la sirène quand on change la valeur
Flash only -> Ne fait rien
OFF -> éteint la sirène

**Comment by tcharp38** [comment]
Salut @M4dd4M 
Désolé, je vois que j'ai laissé ce sujet de côté.
Que fait on avec ? Qu'est ce qui ne te semble pas propre ou manquant si toujours interessé ?

**Comment by M4dd4M** [comment]
Salut @tcharp38 
Il manque le changement de couleur des leds et le réglage du volume...
... mais  tu peux laisser en l'état, car c'est fonctionnel et stable. Finalement, le volume pour une alarme n'a que peu d'importance, et les leds ne se voient pas beaucoup ^^
C'est bien intégré dans ma maison, en cela permet d'avoir un relai général pour les détecteurs de fumée connectés, impec !
Merci pour le travail tu peux clore ! 👍
