### ISSUE TITLE
Ajout Bouton 3 contact Moes ( ID=TS0043, _TZ3000_gbm10jnj)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2630]
Bonjour,
J'ai acheté ce triple interrupteur de marque Moes qui ne semble pas reconnu d'origine.
C'est étrange car ces petit frères en version 1 inter le sont.
Alimentation avec une pile 2032.

![Bouton3](https://github.com/KiwiHC16/Abeille/assets/144285463/9bf39df4-32b1-4d61-aeb0-dc38a4bad237)
[discovery-TS0043__TZ3000_gbm10jnj_bouton-3btn_moes.zip](https://github.com/KiwiHC16/Abeille/files/12846832/discovery-TS0043__TZ3000_gbm10jnj_bouton-3btn_moes.zip)

**Comment by tcharp38** [comment]
Tiens, ecrase le modele existant par celui ci
et refais une inclusion

[TS0043__TZ3000_bi6lpsew.zip](https://github.com/KiwiHC16/Abeille/files/13068393/TS0043__TZ3000_bi6lpsew.zip)

**Comment by M4dd4M** [comment]
non reconnu ... mais peut-être parceque son nom est le TS0043__TZ3000**__gbm10jnj_** ?

**Comment by tcharp38** [comment]
Besoin des logs. Toujours. Sinon ca n'est qu'a "l'aveugle"

**Comment by M4dd4M** [comment]
Je reviens sur ce sujet : J'ai renommé le package envoyé pour qu'il corresponde avec le nom et ça fonctionne.
Les 3 touches remontent correctement aux différents niveaux (single, double et long).
Donc juste l'image a intégrer (et le nom car c'est le modèle d'un Loratap ) et on est bon, je crois :-)

**Comment by tcharp38** [comment]
Salut @M4dd4M 
Ne fais pas ce genre de chose STP sinon on ne peut pas nettoyer les pbs.
Ca n'est pas normal. 
Le package que je t'ai envoyé contient non seulement la signature TS0043__TZ3000_bi6lpsew mais aussi TS0043__TZ3000_gbm10jnj.
Donc ton device aurait du etre reconnu.

Bref on fait quoi avec ce sujet ?

Au passage, quelle est la ref "MOES" de cet inter ?

**Comment by M4dd4M** [comment]
Salut,
Alors là je t'avoue que je ne comprends pas, non, cela non fonctionnait pas du tout (non reconnu) avec le package que tu m'a envoyé plus haut, alors que ça a marché instantanément après l'ajout du même package renommé... 
Désolé, je ne savait pas que c'était une bêtise, surtout que de mon point de vue ça a fait fonctionné la chose, et que cela fonctionne depuis sans soucis.
Y'a pas de ref MOES précise : C'est écrit "MOES ZigBee Scene Switch"

Donc que faire du sujet, je ne sait pas trop, ça serai pas mal de finaliser pour d'autre utilisateurs potentiels non ?
J'imagine qu'il faut que je supprime ce que j'ai mis et que j'attende un nouveau package ?

**Comment by tcharp38** [comment]
Je corrige. Ca n'est pas une betise :)
Mais comme je ne pige pas pour moi ca n'est pas corrigé. 

- Si tu bascules sur la derniere beta
- supprime ton equipement
- et refais une inclusion qui fonctionne sans aucune modif de fichier... alors la c'est tout bon.

Si ca fonctionne pas, j'ai besoin du package de logs pour corriger le souci que je ne vois pas.

**Comment by M4dd4M** [comment]
Bonjour, Tu peux clore c'est OK
L'icone ne remonte pas automatiquement, mais je peux aller le changer il est bien là.
Tout fonctionne bien.
Merci !
