### ISSUE TITLE
ajout commande 6 boutons Loratap ( ID=TS0046, _TZ3000_iszegwpd)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2631]
Bonjour,

Cet télécommande Lolatap avec 6 boutons et magnétique me semblait tellement pratique ... mais elle n'est pas reconnue dans ma ruche.
(alimenté par une pile 2032)

![Bouton6](https://github.com/KiwiHC16/Abeille/assets/144285463/b8b08ff9-c6fa-428a-af7a-202b17f9b074)
[discovery-TS0046__TZ3000_iszegwpd_6btn_lolatap.zip](https://github.com/KiwiHC16/Abeille/files/12846847/discovery-TS0046__TZ3000_iszegwpd_6btn_lolatap.zip)

**Comment by M4dd4M** [comment]
![Bouton6v2](https://github.com/KiwiHC16/Abeille/assets/144285463/822027b3-1580-48fd-bebc-38d34b4f9596)

**Comment by M4dd4M** [comment]
Salut @tcharp38 dis moi, y'a t-il une difficulté particulière avec ce bouton ? est que le discovery fournis est suffisant ? Puis-je aider ?

**Comment by tcharp38** [comment]
Je n'ai rien attaque ne sachant pas si j'étends un modèle existant ou si j'en crée un nouveau.
Je vais creuser

**Comment by tcharp38** [comment]
Y a t'il un nom de modele ? Une ref ?

**Comment by tcharp38** [comment]
Pour test

A decompresser dans core/config/devices
[TS0046__TZ3000_iszegwpd.zip](https://github.com/KiwiHC16/Abeille/files/13068220/TS0046__TZ3000_iszegwpd.zip)

**Comment by M4dd4M** [comment]
Salut @tcharp38 ,
Chez Loratap, ils font tout un tas de télécommandes avec entre 1 à 6 boutons ( j'ai vu que le modèle 3 boutons avait déjà été ajouté). Là c'est le modèle 6 boutons.

On peut en trouver [ici par exemple](https://fr.aliexpress.com/item/1005004988714663.html?spm=a2g0o.order_list.order_list_main.52.6ac05e5bqLs4mN&gatewayAdapt=glo2fra).

Avec ce qui tu as envoyé, pas grand résultat, cela discute avec le device semble l'actualiser, sans pour autant avoir de bouton.
Peut-être certainement la même base que le [modèle 3 boutons déjà traité](https://github.com/KiwiHC16/Abeille/issues/2589) ?

**Comment by tcharp38** [comment]
Tu as refais une inclusion ?
J'ai besoin des logs apres cette etape et un snapshot du widget. Tu devrais avoir 6 infos.

**Comment by M4dd4M** [comment]
mon jeedom était dans le choux (en même temps pas de reboot depuis 100 jours et plein d'install... :-)

Donc un reboot, des maj, et une inclusion plus tard : c'est bon :
 - Bouton bien reconnu
 - 6 infos présentes qui changent entre : single null / double null / long null

Donc ça ma semble pas mal ça !
( après je ne sais pas si c'est normal qu'il y ai "null" a chaque fois... )

**Comment by tcharp38** [comment]
Alors je pige pas d'ou sort ce "null" mais c'est à creuser.
Fais un click sur un des boutons et files moi les logs dans la foulée STP

**Comment by M4dd4M** [comment]
Je ne sais trop comment faire pour les logs, je relis les docs pour apprendre et t'envois ça

**Comment by tcharp38** [comment]
Ha désolé.
C'est facile.
Page maintenance + telecharger tout et tu fais un drag & drop ici. Rien d'autre à faire

**Comment by M4dd4M** [comment]
Bon et bien, 3 semaine plus tard, le bouton marche super bien, les "null" avaient disparu après une nouvelle association.
mise a part le logo qui ne remonte pas, pour moi c'est validé. Merci @tcharp38 !!

**Comment by tcharp38** [comment]
Pb de logo ?
Es tu aligné sur la derniere beta ?
Il te faudra supprimer l'equipement de Jeedom et refaire une inclusion propre.

**Comment by M4dd4M** [comment]
@tcharp38 je viens de le refaire a partir de 0, le nom est correct, mais le logo est KO.
Oui, je suis sur la dernière Beta : 2023-11-11 01:00:28

**Comment by tcharp38** [comment]
Peux tu me donner un snapshot de ta page EQ/avancé ?
Ex
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/e9c16326-8eaf-4c41-a590-2bb6f3a78b1f)

**Comment by M4dd4M** [comment]
![loratap-6boutons-Capture d’écran 2023-11-15 123117](https://github.com/KiwiHC16/Abeille/assets/144285463/43a0aff7-3a80-4c06-a572-4eb4944f1c46)

**Comment by tcharp38** [comment]
zut.
Peux tu faire un "reinitialiser" et me filer le package de logs ?

**Comment by M4dd4M** [comment]
réinit faite à 13:23
[AbeilleLogs-231115.tar.gz](https://github.com/KiwiHC16/Abeille/files/13364482/AbeilleLogs-231115.tar.gz)

**Comment by M4dd4M** [comment]
Hello, comme pour un autre, le logo ne remonte pas a l'inclusion (mais il est bien disponible dans le stock) donc je le met manuellement.
L'équipement fonctionne bien, on peu clore.
Merci !!

**Comment by tcharp38** [comment]
Je pige pas ce pb de logo.
Je ne reproduis pas mais bon.. on va attendre que qqn relance un sujet specifique si ca se reproduit.
