### ISSUE TITLE
Statut No-ACK dans l'outil SANTE

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2632]
Bonjour,
j'ai un capteur de température Xiaomi qui a un statut No-ACK dans l'outil SANTE... 
j'ai changé les piles, mais j'ai le même statut... 
Je reçois toujours bien les remontées d'info...
J'ai rien trouvé dans la doc au sujet de ce statut...
j'ai trouvé ce post
https://community.jeedom.com/t/sonoff-snzb-02-temperature-humidite-ne-remonte-aucune-info/60622/13
mais pas le "Apply settings to NE" 
Est-ce que ça a été renommé depuis ??
Merci

**Comment by tcharp38** [comment]
Salut @fable73 
Tu me files le package de logs ? (page maintenante + telecharger tout + drag&drop ici).

Si il remonte ses infos ca n'est pas bloquant donc pas d'autres soucis sur ce device n'est ce pas ?

**Comment by tcharp38** [comment]
Merci de basculer sur la derniere beta (postée hier).
Ca doit resoudre ce pb.

**Comment by fable73** [comment]
@tcharp38 

![image](https://github.com/KiwiHC16/Abeille/assets/68732573/42fbecae-9e26-4092-93d8-e6d67e48f946)

Tu es un chef !!!!

**Comment by fable73** [comment]
Mince posté sur le mauvais topic... je remet dans l'autre...

**Comment by fable73** [comment]
Mais la conclusion est la même 🥇 
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/bb61e1e6-40b2-4b78-9ca9-724ffd39cc41)

Impeccable !!!

Je ferme?
