### ISSUE TITLE
Aubess 4 buttons switch TS0044__TZ3000_wkai4ga5

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2633]
Bonjour !

Un petit soucis avec le support de ce bouton... qui est parfaitement pris en charge pour ce qui est de ses 4 boutons !
Sauf peut-être un peu trop de discussion avec ce dernier ? Tellement même que les piles ne durent que 2 semaine (au lieu d'1 an ou 2 ...)

Y'a t-il quelque chose a changer pour limiter cela ?

**Comment by tcharp38** [comment]
Salut @M4dd4M 
A ma connaissance il n'y a pas d'astuce pour réduire le nombre de "reporting" fait par le device.
C'est un truc "Tuya".. donc qui ne respecte pas le standard Zigbee avec un cluster privée "EF00" à la sauce Tuya.

**Comment by tcharp38** [comment]
Je réalise que c'est le meme sujet que le https://github.com/KiwiHC16/Abeille/issues/2594
Je ferme celui ci.
