### ISSUE TITLE
SilverCrest-HG08673-FR  prise connecté (SAPZ 1 A2) (id = TS011F, _TZ3000_ynmowqk2)

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2635]
identique à Silvercrest-HG06337-FR
mais avec  en plus
"compteur énergétique pour contrôler votre consommation"

[discovery-TS011F__TZ3000_ynmowqk2.json](https://github.com/KiwiHC16/Abeille/files/13168691/discovery-TS011F__TZ3000_ynmowqk2.json)
(Je propose la même image avec juste un kWh en plus.)
![priseLidl](https://github.com/KiwiHC16/Abeille/assets/47332515/970d9a27-2a09-4bf7-a3f6-26a46e247129)

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Tiens, a tester.
[TS011F__TZ3000_ynmowqk2.zip](https://github.com/KiwiHC16/Abeille/files/13176284/TS011F__TZ3000_ynmowqk2.zip)

J'espere que ce plug fait du reporting automatique mais on verra dans les logs.


Pour mémo:

    fingerprint: tuya.fingerprint('TS011F', ['_TZ3000_j1v25l17', '_TZ3000_ynmowqk2', '_TZ3000_3uimvkn6']),
    model: 'HG08673',
    vendor: 'Lidl',
    description: 'Silvercrest smart plug with power monitoring (EU, FR)',
    ota: ota.zigbeeOTA,
    extend: tuya.extend.switch({electricalMeasurements: true, powerOutageMemory: true, indicatorMode: true, childLock: true}),
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
        await reporting.rmsVoltage(endpoint, {change: 5});
        await reporting.rmsCurrent(endpoint, {change: 50});
        await reporting.activePower(endpoint, {change: 10});
        // Energy reporting (currentSummDelivered) doesn't work; requires polling: https://github.com/Koenkk/zigbee2mqtt/issues/14356
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
        device.save();
    },
    options: [exposes.options.measurement_poll_interval().withDescription('Only the energy value is polled for this device.')],
    onEvent: (type, data, device, options) => tuya.onEventMeasurementPoll(type, data, device, options, false, true),
    whiteLabel: [
        tuya.whitelabel('Lidl', 'HG08673-BS', 'Silvercrest smart plug with power monitoring (BS)', ['_TZ3000_3uimvkn6']),
    ],

**Comment by VVorttexx** [comment]
Hello Tcharp, merci de ta rapidité habituelle.
bon alors pas de retour de la conso. Je ne me souvenais pas bien de la manip, j' ai  supprimé le plug, mis ne mode debug, re-appareillé le plug...., remis le logs en defaut et télécharger les log. 
[AbeilleLogs-231026.tar.gz](https://github.com/KiwiHC16/Abeille/files/13180229/AbeilleLogs-231026.tar.gz)
j'espère que c'est correct.
merci encore.

**Comment by tcharp38** [comment]
Salut.
Houla.. t'es toujours sur la derniere STABLE.. donc une antiquité.

Soit tu bascules sur la derniere BETA que j'espere transformer en stable a mon retour de mes qq jours off,
soit tu patientes un peu

La plupart de tes logs sont vides car tu n'est pas en mode DEBUG.

Enfin "pas de retour de conso" ca veut dire quoi ?
Tu parles de "Total power" ? Quid des autres infos ?

**Comment by VVorttexx** [comment]
Hello, suis passé en beta, j'ai remis debug et 5000 lignes log.
[AbeilleLogs-231027 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13187947/AbeilleLogs-231027.2.tar.gz)
en fait je n'ai pas d'autre commande que celle là, donc pas de total power.
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/2ca914a7-5e15-4b2c-b086-4f96c4282600)
sinon bonnes vacances :-)

**Comment by tcharp38** [comment]
Ok donc il n'est pas reconnu comme il faut.
Il utilise le modele TS011F (que je devrais virer) plutot que celui que je t'ai filé (TS011F__TZ3000_ynmowqk2)

Ca veut dire que tu n'as pas décompressé le modele au bon endroit (Abeille/core/config/devices)
ou que tu n'as pas redémarré Abeille avant de refaire une inclusion (supprime ton equipement au cas ou).

**Comment by VVorttexx** [comment]
RE, 
lancé dedans
 j'ai ajouter un autre plug  et cette fois il a prix le ynmowqk2:
 
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/6b78ec2d-815f-4111-b453-b5f2f55659ba)

du coup j'ai re tuer l'autre et cela semble fonctionner.
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/1eca6f2f-a1e4-4b76-96e3-242a8f2b415a)

je vais voir si les W sont cohérent...Merci.

**Comment by tcharp38** [comment]
Tu me files les logs ?

**Comment by VVorttexx** [comment]
hello,
je pense que cela fonctionne mtnt, en beta et avec le bon modéle:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/da7a0699-e039-4c47-98d9-8617d45fb133)
(j'ai ajouté l'icone plugins/abeille/images)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/b7b9dac6-034b-402a-9401-5bbde7b557c1)
(faut que je révise ma compréhension des Kwh je trouve que le frigo bouffe bcp :-) )
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/eeb6d870-49f1-47a9-b63e-e72fd145a8f8)

par contre en passant en beta, j'ai ce message sur un on /off /toggle les autres commandes fonctionne (mieux d'ailleurs, les curseur set level vont bien à 0, je crois que cela ne fonctionnais pas avant.) depuis toutes mes remote control .

ERREUR: Commande inattendue: '{"onoff":"1","addressMode":"01","priority":4,"dest":"Abeille2","address":"2000","destinationEndpoint":"01","action":"01"}'

les logs:
[AbeilleLogs-231101.tar.gz](https://github.com/KiwiHC16/Abeille/files/13227609/AbeilleLogs-231101.tar.gz)
Merci.

**Comment by tcharp38** [comment]
Les erreurs dont tu parles sont fixées dans la beta de demain.

Cote KWh.. pas de panique. Je pense qu'il y a des soucis d'unité.
Seul "Total power" te semble faux n est ce pas ?

**Comment by VVorttexx** [comment]
Salut,
donc pour les remote control ça marche.
Pour les KW, en effet c'est le total power, mais
je passe de 259 à 597.5 en 3 jours (j'aimerais des relevés plus court mais cela ne semble pas être possible. )  soit 112 KWh jours ou 4.6 KWh sur 24h 
et de 
597 à 1025, en 4 jours, soit 107 KWh jours (à la louche pour les 2, je ne tombe pas à l'heure exact) ou 4.4 KWh sur 24h
le frige est donnée pour 160 W. soit 3,84 KWh sur 24h
Sauf si je me gourre dans ma compréhension, c'est cohérent. 

C'est l'historisation qui m'embête, j 'aimerais voir la conso au max par heure histoire de voir quand consomme le frigo.
et pourvoir faire un coût par ans pour le replacer dans la facture totale. 
il y a une raison pour laquelle les valeur passe par un calcul du genre:
#value#/1 ou #value#*1/1 ?
(j'ai oublié, la commande ON_all des remotecontrole envois une erreur, <html>

2023-11-05 09:18:28 | Abeille | ERREUR: Commande inattendue: '{"onGroupBroadcast":"onGroupBroadcast","name":"onGroupBroadcast","priority":4,"dest":"Abeille2","On":1,"addr":"2000"}' |   | 4
-- | -- | -- | -- | --
  | 2023-11-05 09:15:47 | Abeille | ERREUR: Commande inattendue:
  
  mais je ne comprend pas comment elle fonctionne, à moins de lui mettre des actions avant/aprés execution ?
  C'est plutôt une toggle qui me manque ici, pour utiliser des boutons sonOFF, mais je contourne en passant par un scénario de toute façon. )

**Comment by tcharp38** [comment]
Salut @VVorttexx 
STP ne mélange pas les sujets. La partie "remote control" est un autre point alors reouvre ou cree le sujet correspondant sinon c'est difficile à suivre et à "nettoyer".
Donc j'ignore tes soucis de remote la

Concernant la prise, si je comprends bien la valeur affichée semble coherente partout.
C'est juste la frequence de raffraichissement de "Total power" qui n'est pas idéale.
le reste est ok.
Correct ?

Peux tu mettre cet equipement en surveillance. J'ai besoin d'AbeilleMonitor apres plusieurs heures pour voir ce qu'il reporte et quand. Merci

**Comment by VVorttexx** [comment]
Hello, oui c'est ça:
semble correct mais le rafraichissement ne se fait pas automatiquement, je viens de faire un get-totalpower pour avoir une 3eme donnée dans le graph.
Je viens de le passer en surveillance je te l'envois ce soir.

**Comment by tcharp38** [comment]
Ha ca aussi je voulais savoir.
Tu ne fais un get que sur "Total power" ? Les autres infos remontent toutes seules ?

Pour info, cote remote je viens de pousser un correctif pour la beta de demain.

**Comment by tcharp38** [comment]
Bon je suppose que tu fais ca que sur "Total power".
Voila un nouveau modele qui va faire un refresh automatiquement toutes les 10mins.
[TS011F__TZ3000_ynmowqk2.zip](https://github.com/KiwiHC16/Abeille/files/13267507/TS011F__TZ3000_ynmowqk2.zip)

Sera dans la beta de demain

**Comment by VVorttexx** [comment]
il n'y a que la conso qui m'intéresse, mais ttes le infos  sont figées et ne se mettent à jours que via un get.
voici le log avec surveillance de la Prise_frigo ID 640
[AbeilleLogs-231106.tar.gz](https://github.com/KiwiHC16/Abeille/files/13268969/AbeilleLogs-231106.tar.gz)

**Comment by tcharp38** [comment]
Que la conso totale et pas instantannée.
Mais je compte sur toi pour regler les autres aussi.

On dirait que tu n'as pas utilisé mon dernier modele. Je ne vois pas la commande de "refresh toutes les 10mins".

**Comment by VVorttexx** [comment]
J'ai mis le dernier modèle après en effet, je n'ai pas vu de différence après 10 mn en faisant un mise à jour du modéle, alors j'ai relancé le daemon. mais tjrs rien et Voltage et current tombe à 0

![image](https://github.com/KiwiHC16/Abeille/assets/47332515/d1d5c7c9-cadf-4982-8c7a-8710ae27da88)
[AbeilleLogs-231106 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13271510/AbeilleLogs-231106.2.tar.gz)
et tjrs un graphiques en retard
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/b827c1de-9b74-43f9-970c-17b8263ebcc3)

**Comment by tcharp38** [comment]
Non tu n'utilises toujours pas le  bon modele car il manque toujours la commande "Refresh Total power".
Ou l'as tu décompressé ?

**Comment by tcharp38** [comment]
Nouveau modele à tester.
Il y avait un conflit entre "Get Total power" et "Refresh total power". Je n'ai gardé que cette derniere

[TS011F__TZ3000_ynmowqk2.zip](https://github.com/KiwiHC16/Abeille/files/13273333/TS011F__TZ3000_ynmowqk2.zip)

**Comment by VVorttexx** [comment]
je les met là:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/1be544e1-e77d-400d-aca3-2b9ea43414ee)
et il a fonctionné j'ai eu une enregistrement toutes les heures. ce qui est acceptable pour un truc qui tourne 24/24
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/abc8dd98-deba-4b2b-b4e0-217abfa32c33)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/bc3aa8db-fb84-4ef4-b4b5-ca7924104d45)
par contre 5,5 KWh en 1 heure...c'est franchement un frigo nucléaire :-) devrait être plus proche de 160w (ça doit être 1,217 KWh et 1,221 KWh, ça donne 99 W ce qui est plus proche de la conso normale de ce frigo la nuit.)
Sinon j'ai mis en place le nouveau modèle et fait une mise à jour:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/fa4cfe67-14ba-47e4-afc1-79a8d0efb485)
juste le monitor:
[AbeilleMonitor.log](https://github.com/KiwiHC16/Abeille/files/13276278/AbeilleMonitor.log)

**Comment by tcharp38** [comment]
Je suis perdu.
Je vois maintenant du reporting automatique pour cet attribut

    [2023-11-07 06:44:36] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:44:36] <=   FCF=08/General/Serv->Cli, SQN=56, cmd=0A/Report attributes
    [2023-11-07 06:44:36] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D6 => 1238
    [2023-11-07 06:46:00] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:46:00] <=   FCF=08/General/Serv->Cli, SQN=5A, cmd=0A/Report attributes
    [2023-11-07 06:46:00] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D7 => 1239
    [2023-11-07 06:48:39] <= 8012/APS data confirm, Status=00, Addr=BB96, SQNAPS=D8, NPDU=00, APDU=02
    [2023-11-07 06:48:40] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:48:40] <=   FCF=08/General/Serv->Cli, SQN=5E, cmd=0A/Report attributes
    [2023-11-07 06:48:40] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D7 => 1239
    [2023-11-07 06:51:24] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:51:24] <=   FCF=08/General/Serv->Cli, SQN=62, cmd=0A/Report attributes
    [2023-11-07 06:51:24] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D7 => 1239
    [2023-11-07 06:53:35] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:53:35] <=   FCF=08/General/Serv->Cli, SQN=65, cmd=0A/Report attributes
    [2023-11-07 06:53:35] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D8 => 1240
    [2023-11-07 06:56:06] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:56:06] <=   FCF=08/General/Serv->Cli, SQN=68, cmd=0A/Report attributes
    [2023-11-07 06:56:06] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D8 => 1240
    [2023-11-07 06:58:57] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 06:58:57] <=   FCF=08/General/Serv->Cli, SQN=6C, cmd=0A/Report attributes
    [2023-11-07 06:58:57] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D8 => 1240
    [2023-11-07 07:01:32] <= 8002/Data indication, Status=00, ProfId=0104, ClustId=0702, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=BB96, DstAddrMode=02, DstAddr=0000
    [2023-11-07 07:01:32] <=   FCF=08/General/Serv->Cli, SQN=6F, cmd=0A/Report attributes
    [2023-11-07 07:01:32] <=   AttrId=0000/CurrentSummationDelivered, AttrType=25, ValueHex=0000000004D9 => 1241

Mais pas le polling que j'ai ajouté.

Tu me redonnes ton package de logs ?

**Comment by VVorttexx** [comment]
Voila.
[AbeilleLogs-231107.tar.gz](https://github.com/KiwiHC16/Abeille/files/13280062/AbeilleLogs-231107.tar.gz)
De mon coté depuis la mise a jour ce matin, je n'ai plus aucunes commande on off, sur aucun device.
generic bulb 14
silvercrest smartplug
silvercrest  HG06337
je viens de rebooter la sigate et le PI. sans succés. Pas d'erreur log et le status est bien a jour, si j'allume un smartplug manuellement il remonte allumé dans la jeedom...suis perdu aussi.

**Comment by tcharp38** [comment]
Heu...
On oublie to plug SilverCrest pour l'instant. Il faut que tu retrouves un etat stable.
Quel device en particulier n'a plus de commande ON/OFF ?

**Comment by VVorttexx** [comment]
les 3 que je t'ai donnée  ne peuvent plus s'allumer.  sauf en manuel
generic bulbGU10 aussi.
je n'en ai pas trouvé qui fonctonne en fait.
pourtant tout et OK
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/ea1bf391-e0b3-4596-8285-cbf9d2211530)

**Comment by tcharp38** [comment]
Je viens de trouver un bug en testant autre chose. Ca peut expliquer.

Decompresse le fichier suivant dans core/class
[AbeilleCmdProcess.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13281658/AbeilleCmdProcess.class.php.zip)

puis redemarre Abeille
et dis moi

**Comment by VVorttexx** [comment]
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/71058afa-204c-4317-a60b-d46d2e5bcafc)
premier tests ça marche!

**Comment by VVorttexx** [comment]
oui ça marche pour tout, (mais j'ai la beta du market, c'est planté pour ceuq qui on t fait la mise à jour non?)

**Comment by tcharp38** [comment]
Ok donc tout est retombé en marche pour toi.
J'ai déja poussé ce correctif pour une beta qui sera dispo demain.

On peut revenir sur le sujet "prise"

**Comment by VVorttexx** [comment]
j'ai retrouvé toutes les infos:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/09bcccba-825f-4267-a05d-4d64230966f2)
mais pas assez de recule pour voir quelle est la période de remonté. 
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/1f3a966f-7b0a-4c64-a27e-44246383faae)
les 4 dernières sont 8,10,12,14h.

**Comment by tcharp38** [comment]
Fait un "reset" du modele en cliquant sur l'equipement puis onglet avancé STP.
La commande "Get total power" ne doit plus exister. Tu dois avoir "Refresh total power" à la place.

Ensuite tu laisses tourner qq heures avant de me filer le log monitor.

**Comment by VVorttexx** [comment]
Hello, c'est fait, 
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/631752eb-c376-4049-8cc4-c5499de04e30)
depuis 9h mais je n'ai que 2 reccords 9h et 11h
[AbeilleLogs-231108.tar.gz](https://github.com/KiwiHC16/Abeille/files/13295486/AbeilleLogs-231108.tar.gz)

**Comment by VVorttexx** [comment]
Hello cette fois cela tourne bien toutes les heures, j'ai un relevé de la conso de la prise de 13h à 19h.
![2023-11-07T17_02_49+01_00](https://github.com/KiwiHC16/Abeille/assets/47332515/a9d44ca7-f63b-4987-94d4-3a55748ef05a)

je sais que tu ne souhaite pas mélanger les sujet, mais bien embêtant quand même, en voulant éteindre une lampe via une remote control, commande OFF all, j'ai coupé toutes les devices d'un coup, lampe, ruban led, prise et notamment le frigo....tu devrais avoir cela dans les logs, d'il y a 15 mn. j'ai mis a jour via le market, mais je n'ai pas retenter l'expérience...ça tue la prise de mon pc aussi .

**Comment by tcharp38** [comment]
J'aime bien ton package de logs :) sauf que moi je n'y connais rien.

Pour revenir sur ton point embettant.. "OFF ALL" ca veut dire eteindre tout le monde. Alors qu'attends tu d'autre comme effet. Elle fait son job.
Mais peut etre voulais tu utiliser "OFF GROUP" ?

**Comment by VVorttexx** [comment]
A flute j'en consomme trop manifestement.
[AbeilleLogs-231109.tar.gz](https://github.com/KiwiHC16/Abeille/files/13311711/AbeilleLogs-231109.tar.gz)
(dommage que tu ne saches pas...je cherche. :-) )

je me doutais un peu quand même pour Off all.... mais j'avais le sentiment confus que cela se limitait aux devices que la remote control avait sous ses ordres, et pas la totalités des devices de la zigate... si ça tombe j'ai coupé tout le quartier....moi cela me parait un peu chaud d'avoir sur chaque remote un blackout total de la maison, et l'intérêt m'échappe un peu. Mais bon mtnt que je le sais.

**Comment by tcharp38** [comment]
Je suis bien d'accord avec toi.
Je n'ai pas concu ce modele mais KiwiHC16.
Et oui le OFF ALL ou ON ALL .. bien trop dangereux. Je vais mettres ces commandes en "ne pas afficher" par défaut.

**Comment by tcharp38** [comment]
Il y a bien une lecture toutes les 10mins
mais ce device fait aussi du reporting tout seul. Etrange.

Du coup on en est ou ?

**Comment by VVorttexx** [comment]
bonjour,
pour moi il afffiche un report toutes les heures, je ne trouve rien toutes les 10 mn ?:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/0423d22e-cb74-4392-9ac0-a970d04977e0)
sauf que cela fait entre 3,5 et 5,5 W (l(unité de mesure est forcément le Wh pas le KWh) par heure, ce qui ne correspond pas à 160 W

je le tourne dans tous les sens est j'ai tjrs un coeff d'environ 40 quelque part.
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/cd78a855-bb21-4602-bf09-322e5c7dd2cd)

**Comment by tcharp38** [comment]
Il y a bien une lecture toutes les 10mins mais l'info ne changeant pas forcement (heureusement pour total power), ca peut donner uen vision toutes les H.

Tiens un nouveau modele. J'ai gardé KWh comme unité mais avec division par 1000.
[TS011F__TZ3000_ynmowqk2.zip](https://github.com/KiwiHC16/Abeille/files/13325231/TS011F__TZ3000_ynmowqk2.zip)

Un ratio 40 ?! La je vois pas d'ou ca peut sortir.
Est ce que la valeur "Active Power" est coherente ?

**Comment by VVorttexx** [comment]
salut, 
je viens de mettre le modèle en place, le KWh est plus cohérent. (j'ai trouvé un article donnait pour une frig de 150 à 200 w un conso annuel de 201 KWh le /1000 trouve ça réponse là)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/67110168-e9bf-4ab3-bf97-9e8bee1ee024)
pour l'active power, la puissance instantanée donc, ça semble conforme
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/dbf409a8-8af6-491e-9153-2557ce6d6cc0)
la puissance nominal est de 160W mais avec les pics de démarrage (jusqu'a x5) cela semble cohérent aussi. toutes les 5 mn d'ailleurs
je ne m'explique pas les retours à 0, il devrait consommer en continue au moins un peu, mais bon pas grave.

Merci.

**Comment by tcharp38** [comment]
Du coup tout est bon.

Je me demande maintenant si je ne supprime pas la lecture toutes les 10mins pour beneficier du reporting.
C'est carrement + propre et efficace.

**Comment by VVorttexx** [comment]
oui tu peux 
et oui pour le report/10.
merci

**Comment by tcharp38** [comment]
Question.. pourquoi demander un report toutes les 10mins ? Le total power change quand il doit changer et c'est la qu'il devrait faire un report. non ?

**Comment by VVorttexx** [comment]
Ben faudrait relire notre conversation, mais moi je n'ai pas besoin d'un enregistrement toutes les 10 mn, ce qui  m'intéresse c'est la conso à l'heure. le frigo à une conso théorique de 160 W en 1 heure. d'après les enregistrements il ferait entre 3 et 10 w en 1 heure. Je m'explique pas le gap mais tant que cela n'explose pas.
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/17b929f1-735c-43f7-89c0-5fabbe9ae2dc)
la il est ts les 5 mn, c'est pas mal de voir les démarrages moteur nette, puis la redescente de puissance.

**Comment by tcharp38** [comment]
Si je supprime la lecture forcée toutes les 10mins on n'aura du coup que le reporting fait du device..le + efficace car c'est quand ca change. Donc si rien de change pendant des heures parce que off.. alors aucune info n'est envoyée.

**Comment by VVorttexx** [comment]
je comprend que le device fait un envoi uniquement si l'active power change, sans période minimum, et que tu as programmé une lecture forcé toutes les 10 mn. permettant un suivi de l'active power. (pourquoi j'ai 5 mn moi? )
Pour la puissance instantanée, c'est pas gênant qu'on ai un envoi que lorsque cela change, pour le frigo cela change souvent. 
pour la puissance cumulée, (je suppose que c'est l'active additionnée en fait) total power, on a de toute façon une heure entre chaque enregistrement. sur la dernière heure j'ai un delta de 9w, comme il est indiqué 160W sur la fiche de l'appareil, ...je n''ai toujours pas compris ce qu'est total power, toutes les heures je devrais avoir dans total power un delta autour de 160W (sans doute plus) mais 9 w?

EN fait je chercher a retomber sur les 160 W de conso par heure, et je n'y arrive pas. 

(et tant que j'y suis il y a une doc des remotecontrol ? )

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Peux tu mettre ton equipement en surveillance dans des heures d'utilisation ?
On va regarder precisement. Je ne comprends pas non plus d'ou sortent ces 5mins mais je soupconne qu'entre la lecture forcée et le reporting automatique.. ca donne à peu pres 5min.
Je ne pige pas non plus le lien entre 9W et 160W..

**Comment by VVorttexx** [comment]
Hello, ok je lance ça, te fait le retour en soirée.

**Comment by VVorttexx** [comment]
enjoy! (debugg et 5000 logs.)
[AbeilleLogs-231126.tar.gz](https://github.com/KiwiHC16/Abeille/files/13467629/AbeilleLogs-231126.tar.gz)

**Comment by tcharp38** [comment]
Bon cette prise n'a clairement pas besoin qu'on l'interroge. Elle envoie bien toutes les infos quand ca qqch change. C'est donc le produit revé. Il ne pollue pas le reseau inutilement et ne parle pas pour rien

On va juste se focaliser sur les valeurs instantannées remontées pour etre sur qu'elles sont bonnes en excluant pour l'instant Total power (CurrentSummationDelivered).
Tu peux voir que le délai n'est pas fixe du tout. Il reporte quand un changement significatif doit l'etre.
Donc puissance du frigo.. environ 75W et 330mA.
Ca me semble cohérent.

    [2023-11-12 10:22:36] <=   FCF=08/General/Serv->Cli, SQN=59, cmd=0A/Report attributes
    [2023-11-12 10:22:36] <=   AttrId=0505/RMS Voltage, AttrType=21, ValueHex=00DE => 222
    [2023-11-12 10:22:36] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=015D => 349
    [2023-11-12 10:22:36] <=   AttrId=050B/Active Power, AttrType=29, ValueHex=004D => 77
    
    [2023-11-12 10:26:32] <=   FCF=08/General/Serv->Cli, SQN=5F, cmd=0A/Report attributes
    [2023-11-12 10:26:32] <=   AttrId=0505/RMS Voltage, AttrType=21, ValueHex=00E1 => 225
    [2023-11-12 10:26:32] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=0150 => 336
    [2023-11-12 10:26:32] <=   AttrId=050B/Active Power, AttrType=29, ValueHex=004B => 75
    
    [2023-11-12 10:27:37] <=   FCF=18/General/Serv->Cli, SQN=61, cmd=0A/Report attributes
    [2023-11-12 10:27:37] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=014E => 334
    
    [2023-11-12 10:29:32] <=   FCF=08/General/Serv->Cli, SQN=63, cmd=0A/Report attributes
    [2023-11-12 10:29:32] <=   AttrId=0505/RMS Voltage, AttrType=21, ValueHex=00E2 => 226
    [2023-11-12 10:29:32] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=014B => 331
    [2023-11-12 10:29:32] <=   AttrId=050B/Active Power, AttrType=29, ValueHex=004A => 74
    
    [2023-11-12 10:30:59] <=   FCF=18/General/Serv->Cli, SQN=65, cmd=0A/Report attributes
    [2023-11-12 10:30:59] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=0146 => 326
    
    [2023-11-12 10:34:30] <=   FCF=08/General/Serv->Cli, SQN=69, cmd=0A/Report attributes
    [2023-11-12 10:34:30] <=   AttrId=0505/RMS Voltage, AttrType=21, ValueHex=00DF => 223
    [2023-11-12 10:34:30] <=   AttrId=0508/RMS Current, AttrType=21, ValueHex=0144 => 324
    [2023-11-12 10:34:30] <=   AttrId=050B/Active Power, AttrType=29, ValueHex=0047 => 71

En ligne avec cette étape ? 
L'affichage et l'historique de ces infos est correct ?

**Comment by VVorttexx** [comment]
hello, 
oui pas de pB, 
le voltage reste stable 220 ~ 
pour active power et le current, j'ai régulièrement 0
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/fec3dab6-934e-40a8-b3d7-ccf13c8522c6)
mais l'historique semble gommer ça:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/f8801c88-37f1-4a65-a71b-5ceed14def6b)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/a261768c-ff76-450d-85c4-1c7af1eff051)

donc jusque là cela se tient.

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Que fait on avec cet antique sujet ?

**Comment by VVorttexx** [comment]
Salut ouhh, en effet perdu de vue, cela tourne bien de mon coté, tu peux fermer pour moi, merci.
