### ISSUE TITLE
Interrupteur mural AQARA OPPLE 4 boutons (id = remote.b486opcn01, LUMI)

### ISSUE THREAD

**Issue by tyler5777** [KiwiHC16/Abeille#2636]
Bonjour,
Interrupteur mural sur batterie Aqara Opple 4 boutons non reconnu dans Abeille (Affiche "defaultUnknown -95" et les commandes générées ne correspondent pas). Il a 4 boutons physique mais chaque bouton peur avoir deux fonctions en faisant un double clique dessus, un appui long sur le bouton (4 secondes) le remet à zéro.
[discovery interrupteur aqara opple 44 boutons.zip](https://github.com/KiwiHC16/Abeille/files/13169459/discovery.interrupteur.aqara.opple.44.boutons.zip)

Merci d'avance :)

**Comment by tyler5777** [comment]
[discovery.zip](https://github.com/KiwiHC16/Abeille/files/13169673/discovery.zip)
 autre fichier discovery qui je crois à l'air un peu plus complet que celui du précédent message

**Comment by tcharp38** [comment]
Salut @tyler5777 
Si ce device est sur piles, alors il faut le reveiller plusieurs fois pendant la decouverte. Tous les boutons doivent etre au vert, en tout cas quasi tous. Ca doit expliquer que le discovery ne soit pas complet.

Quelle ref fabricant ?
J'ai besoin d'une image à mettre en icone, format PNG sans arriere plan.
Sur pile ? Secteur ?

**Comment by tcharp38** [comment]
Ha autre point.
Si pas déja le cas je te suggere de basculer sur la beta Abeille. Il y a beaucoup trop d'avancées depuis la derniere stable.

voir
https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta
https://kiwihc16.github.io/AbeilleDoc/Debug.html#configuration-jeedom-pour-les-logs

**Comment by tyler5777** [comment]
Salut tcharp38.
J'ai installé la version beta et effectivement l'assistant découverte réagis mieux. Ci joint le discovery.zip ; la ref fabriquant au dos de l'interrupteur c'est AQARA OPPLE WXCJKG12LM. Il est alimenté par une pile CR2032.
[discovery-remote.b486opcn01_LUMI.zip](https://github.com/KiwiHC16/Abeille/files/13179894/discovery-remote.b486opcn01_LUMI.zip)

merci à toi
![AQARA_OPPLE_4](https://github.com/KiwiHC16/Abeille/assets/149008301/058ca883-6667-4ae3-8199-6164a6e987a0)

**Comment by tcharp38** [comment]
Pour test

A decompresser dans core/config/devices
[remote.b486opcn01.zip](https://github.com/KiwiHC16/Abeille/files/13186640/remote.b486opcn01.zip)

Mais ca sera dans la beta de demain dans tous les cas.

J'ai besoin que tu 
- refasses une inclusion
- fasse un click
- et me file le package de logs (page maintenance + telecharger tout)

En supposant que tu en en BETA Abeille + debug mode actif 5000 lignes de log

Merci

PS: Je suis off qq jours cette semaine donc ne pas s'attendre a une grosse reaction

**Comment by tyler5777** [comment]
[AbeilleLogs-231027.tar.gz](https://github.com/KiwiHC16/Abeille/files/13189116/AbeilleLogs-231027.tar.gz)

Oui je suis bien en BETA désormais. Mode debug actif avec 5000 lignes. J'ai décompressé le fichier dans le core/config/devices.
Après redémarrage jeedom, le device a été reconnu après inclusion (Xiaomi Aqara Opple 4 boutons). 
J'ai fait un click (fallait appuyer une fois sur l'un des boutons de l'interrupteur c'est bien ça ? :) )
Ci joint le package demandé.

**Comment by tcharp38** [comment]
Mémo pour moi (à creuser)

    [2023-10-27 14:50:50] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FCC0, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=B6ED, DstAddrMode=02, DstAddr=0000
    [2023-10-27 14:50:50]   FCF=1C/General/Serv->Cli/ManufCode=115F, SQN=02, cmd=0A/Report attributes
    [2023-10-27 14:50:50]   UNHANDLED FCC0-00F7-41: 01211D0B0328190421A80105214A0006240100000000082111010A215B7F0C2001641000
    [2023-10-27 14:50:50]     No defined Xiaomi mapping
    [2023-10-27 14:50:50]     Tag=01, Type=21/uint16 => 2845 (ignored)
    [2023-10-27 14:50:50]     Tag=03, Type=28/int8 => 25 (ignored)
    [2023-10-27 14:50:50]     Tag=04, Type=21/uint16 => 424 (ignored)
    [2023-10-27 14:50:50]     Tag=05, Type=21/uint16 => 74 (ignored)
    [2023-10-27 14:50:50]     Tag=06, Type=24/uint40 => 1 (ignored)
    [2023-10-27 14:50:50]     Tag=08, Type=21/uint16 => 273 (ignored)
    [2023-10-27 14:50:50]     Tag=0A, Type=21/uint16 => 32603 (ignored)
    [2023-10-27 14:50:50]     Tag=0C, Type=20/uint8 => 1 (ignored)
    [2023-10-27 14:50:50]     Tag=64, Type=10/bool => 0 (ignored)

et 

    [2023-10-27 14:50:56] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0012, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=B6ED, DstAddrMode=02, DstAddr=0000
    [2023-10-27 14:50:56]   FCF=18/General/Serv->Cli, SQN=03, cmd=0A/Report attributes
    [2023-10-27 14:50:56]   AttrId=0055/Unknown-0012-0055, AttrType=21, ValueHex=0001 => 1

**Comment by tcharp38** [comment]
@tyler5777 
J'aurais besoin que tu refasses un test et que tu notes l'heure exacte quand tu fais ton clic, en testant chaque bouton.
Ca me permet de retrouver l'info dans les logs.

**Comment by tyler5777** [comment]
Salut Tcharp,
Merci pour ton aide. Ci joint le package de logs en fin de message.
Pour info, j'ai refait une inclusion de l'interrupteur à 18H31 qui a été correctement reconnu dans abeille.
Ensuite comme demandé j'ai appuyé 1 fois sur chaque bouton.
18H54 : bouton 1
18H55 : bouton 2
18H56 : bouton 3
18H57 : bouton 4

Puis j'ai fait un appui long de 3-4 secondes sur chaque bouton qui correspond au "release"
19H50 release bouton 1
19H51 release bouton 2
19H52 release bouton 3
19H53 release bouton 4


Pour finir, j'ai double cliqué sur chaque bouton pour la 2nde fonction (5, 6, 7, 8)
19H55 double clique bouton 1
19H56 double clique bouton 2
19H57 double clique bouton 3
19H58 double clique bouton 4

Voilà j'espère que tu verras qq chose dans les logs car chez moi il ne se passe rien.

Merci a+

[AbeilleLogs-231101.tar.gz](https://github.com/KiwiHC16/Abeille/files/13230855/AbeilleLogs-231101.tar.gz)

**Comment by tcharp38** [comment]
Salut

Je suis désolé mais il n'y a aucune trace à l heure donnée. Le log s'arrete le "2023-10-29 08:35:21" et apres plus rien.
Plus en mode debug ?
Ne refais pas tous les tests. on commence par un simple click sur chaque bouton.
Le log clef pour ca est 'AbeilleParser.log'

**Comment by tyler5777** [comment]
Toujours en mode Debug, oui. Il ne se passe plus rien dans le log Parser depuis le 29/10 ... 🤔

**Comment by tyler5777** [comment]
[AbeilleLogs-231104.tar.gz](https://github.com/KiwiHC16/Abeille/files/13256336/AbeilleLogs-231104.tar.gz)

J'ai vidé les Logs et le AbeilleParser réagi à nouveau.

1 clique sur 
Bouton 1 : 11H13
Bouton 2 : 11H14
Bouton 3 : 11H15
Bouton 4 : 11H16

11H17 et 11H18 aucune action de ma part

**Comment by tcharp38** [comment]
Ok je vois.
Donc infos

    0012-01-0055 => value 1
    0012-02-0055 => value 1
    0012-03-0055 => value 1
    0012-04-0055 => value 1

Ce device supporte le double click ou click long ?
Si oui peux tu juste faire la manip sur le premier bouton, avec l'heure ?

**Comment by tyler5777** [comment]
Oui il fait les deux.
[AbeilleLogs-231104(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13256620/AbeilleLogs-231104.1.tar.gz)


13H18 : clique long bouton 1
13H19 : double clique bouton 1

**Comment by tcharp38** [comment]
Donc click long

    [2023-11-04 13:18:03] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0012, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=B5B3, DstAddrMode=02, DstAddr=0000
    [2023-11-04 13:18:03]   FCF=18/General/Serv->Cli, SQN=53, cmd=0A/Report attributes
    [2023-11-04 13:18:03]   AttrId=0055/PresentValue, AttrType=21, ValueHex=0000 => 0

double click

    [2023-11-04 13:18:06] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0012, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=B5B3, DstAddrMode=02, DstAddr=0000
    [2023-11-04 13:18:06]   FCF=18/General/Serv->Cli, SQN=54, cmd=0A/Report attributes
    [2023-11-04 13:18:06]   AttrId=0055/PresentValue, AttrType=21, ValueHex=00FF => 255

**Comment by tcharp38** [comment]
Voila une mise à jour du modele
[remote.b486opcn01.json.zip](https://github.com/KiwiHC16/Abeille/files/13266506/remote.b486opcn01.json.zip)

et une nouvelle commande pour Abeille/core/config/commands
[inf_zbAttr-0012-PresentValue.zip](https://github.com/KiwiHC16/Abeille/files/13266510/inf_zbAttr-0012-PresentValue.zip)

Ca n'est pas idéal mais tu dois avoir 4 "Click X"
et la valeur sera
0 => long
1 => single
255 => double

J'attends ton retour

**Comment by tyler5777** [comment]
Salut Tcharp.
Voici comment ça réagi :
1 pression sur click1 qui passe à l'état 1 ; 2 pressions sur click 2 qui passe à létat 2; long appui sur click3 qui passe à 0 puis à 255 quelques secondes après.

![Capture2](https://github.com/KiwiHC16/Abeille/assets/149008301/c55e9c24-c2dd-41a1-a37d-fbcbba18fca9).

J'ai fait pour chaque bouton le même test à savoir 1 click puis 1 double click et 1 maintien ; tout est Ok ça réagis bien.

Voici l'état au repos après un long appui sur chacun des boutons 
![Capture](https://github.com/KiwiHC16/Abeille/assets/149008301/d5d1b942-f975-4b7c-b9b0-84c9033e84c4)

Les click passent à 0 durant le temps de maintien du bouton (hold) puis à 255 à l'état repos (release).

ça fonctionne désormais j'arrive à lancer mes scénarios et à les arrêter, beau travail :) 
Merci.

**Comment by tcharp38** [comment]
Ha donc mauvaise interprétation.

Donc 
1=single click
2=double click
0=hold, 255=release

Le status de la batterie remonte bien ?

**Comment by tyler5777** [comment]
Oui c'est exactement ça.

La batterie à l'air d'être prise en compte (dernier update hier soir)
![Capturebatt](https://github.com/KiwiHC16/Abeille/assets/149008301/a5438ffb-a9e2-4b5b-b856-449cae4dfa54)

**Comment by tcharp38** [comment]
On peut du coup fermer ce sujet ?

**Comment by tyler5777** [comment]
Oui tout fonctionne bien à présent. Merci beaucoup.
On peut fermer le sujet.
