### ISSUE TITLE
Objets en Timeout

### ISSUE THREAD

**Issue by rsuard** [KiwiHC16/Abeille#2639]
Bonsoir,

Une grande partie de mes objets sont en timeout depusi quelques jours. 
![Capture d’écran 2023-10-24 à 12 04 47](https://github.com/KiwiHC16/Abeille/assets/32543811/a660df63-5df9-4f26-92af-1c221a7b7b4f)

J'ai tenté l'installation d'abeille en béta, le décallage de mon répeteur wifi, rien n'y fait. 

Que puis je faire pour tenter de les faire revenir ?
merci beaucoup,

**Comment by tcharp38** [comment]
Salut @rsuard .
Désolé pour la latence. Je suis encore off qq jours avec peu de connexion reseau.
Tu as toujorus des soucis ?
Dans tous les cas mettre un package de logs avec le sujet histoire d essayer de comprendre et trouver une piste.

**Comment by tcharp38** [comment]
@rsuard 
Des news ?

**Comment by rsuard** [comment]
hello @tcharp38,
Oui et non, j'ai du tout réapairé. Je suis en travaux à la maison donc j'ai pas pu refaire plus de tests car une partie de mes devices sont offline. :-(
J'en ai tout de meme 2-3 censés marcher qui me disent No-ACK.
Je te ferais un feedback en fin de week-end car j'espère avoir fini mes travaux :-)

**Comment by rsuard** [comment]
hello @tcharp38,
les timeouts sont revenus, et toujours plus :-( 
Meme le micro module Sonnoff (lampe flamand) qui n'avait jamais sauté à sauté lui aussi. 
La ça va, il est accessible, mais je suis en train de les mettre petit à petit tous dans mes interupteurs... 
Y a t'il un moyen pour relancer la connexion ? 
(les appareils ont bien de la batterie ou sont sur le 220v)
![Capture d’écran 2024-01-02 à 09 27 08](https://github.com/KiwiHC16/Abeille/assets/32543811/694bc466-18d9-4d1f-9f02-b7023f0ef85f)

**Comment by tcharp38** [comment]
Salut @rsuard 
Je te souhaite une tres belle année, avec j'espere moins de soucis de domotique.

Tous les appareils sur secteur doivent revenir en ligne seuls et rapidement , par ex en faisant un "raffraichissement réseau".
Ceux sur batterie le feront aussi mais au fur et à mesure de leur reveil.

Tu es toujours sur la derniere beta ?
Tu me files un package de logs ?

**Comment by rsuard** [comment]
Hello @tcharp38,
désolé pour mon délai de réponse et mon impolitesse ! Excellente année à toi aussi, avec moins de mes messages pour toi, ahaha ! 
Je reviens sur ce sujet, ça m’inquiète car je suis en train de remplacer tous mes inters et de mettre des micros modules partout, je cherche une solution perenne et stable. 
Donc, j'ai laissé un peu de temps et fait autre chose, aucun des appareils n'est revenu, ni sur batterie, ni sur secteur. 
Un des appareils installés ce week end est déjà en time-out :-(
plusieurs questions pop dans ma tete : 
Dois je changer ma zigate ?  (qui n'est pas à jour, voir l'autre sujet)
Dois je changer de canal pour le zigbee ? elle est à quelques mettre d'un point d'accès wifi.
Dois je mettre des relais zigbee ? Ikea ne vend plus le sien... je ne sais pas trop vers quoi me tourner. 
Merci beaucoup pour toutes tes réponses.  
Très belle semaine à toi !

**Comment by tcharp38** [comment]
Hello

Aucun souci pour le délai.

Donc que des mauvaises nouvelles. Pas cool.
Mais désolé, on va devoir faire une résumé.

Quelle type de zigate, quelle version et tu me files un package de logs ?
Es tu bien aligné sur la derniere beta ?

**Comment by rsuard** [comment]
Hello @tcharp38,

Ouai déso, pas de bonnes news mais plus de temps pour tester et gérer les soucis.
Zigate : c'est la Pi zigate (v2 à priori) que je n'arrive pas à upgrade [voir l'autre thread](https://github.com/KiwiHC16/Abeille/issues/2638), 
Beta : oui, tout MAJ en Beta 
Logs : [AbeilleLogs-240219.tar.gz](https://github.com/KiwiHC16/Abeille/files/14329380/AbeilleLogs-240219.tar.gz)

Je suis à ta dispo,
Très belle journée,

**Comment by tcharp38** [comment]
Je crois que la priorité est de se debarrasser de la 3.20. FW bien trop pourri pour perdre du temps dessus.
Donc priorité sur upgrade FW en 0005-3.22

**Comment by tcharp38** [comment]
Salut @rsuard 
Tu as progressé la dessus ? Abandonné ?

**Comment by Orimanmanman** [comment]
Hello @tcharp38,
J'ai abandonné la zigate oui, désolé mais ça devenait trop chronophage. Je suis passé sur une clé Conbee 2 qui m'avait été envoyée avec des devices d'occas, et pour l'instant tout marche très bien. Cette zigate peu fiable et leur support inexistant ne m'inspirait plus trop confiance. Dommage car ton plugin Abeille était autrement plus fun ! bonne continuation ! PS : si tu veux la pizigate, je peux te l'envoyer par la poste ;-)

**Comment by tcharp38** [comment]
Salut @Orimanmanman 
Pas de soucis. Tu n'es pas le premier à faire cette démarche et ne sera pas le dernier.

Ta PI etant une v2, oui je suis preneur pour essayer de continuer de supporter les malheureux possesseurs d'une v2.

Quant au plugin, vu que tu as fait le saut, si tu as des remarques de trucs utiles vu sur le plugin conbee, je suis aussi curieux.

Merci à toi

**Comment by Orimanmanman** [comment]
@tcharp38 aucun souci, tu peux m'envoyer ton adresse par MP ? 
Pour ce qui est du plugin, j'utilise le plugin officiel Jeedom, JeeZigbee, il est basé sur z2m (Zigbee2MQTT).
Pour l'instant, 
- c'est juste plus fastidieux qu'avec Abeille, il faut renommer correctement chaque device, les attribuer à un objet existant, les rendre visibles, pas mal d'étapes qui pourrait être auto... 
- Par contre, leur map des devices et des qualités de liaisons est pas mal meme si ça devint vite le bordel...
- Les MAJ OTA semblent bien marcher, dommage qu'il n y'ait pas une info sur les devices ou une MAJ est dispo.
- Il y a beaucoup plus de fonction par défaut des devices qui remontent (pas forcement des utiles d'ailleurs)
- la réponse des devices est immédiate et ça change la life VS la zigate, car je pense que ça venait du hardware.
- J'ai toujours le meme souci avec mon ampoule OSRAM qui se rallume seule... c'est un peu Cthulhu 

Bref, du bon et du moins bon, les différences sont pas notables et on est pas trop perdu

**Comment by tcharp38** [comment]
Je ne retrouve pas ton mp du coup peux tu m'envoyer un email à tcharp38@laposte.net ?

Tu peux ausi me montrer le map des devices pour voir a quoi ca ressemble ?
Merci

Je close ce sujet du coup.
