### ISSUE TITLE
Bug télécommandes virtuelles (id=remotecontrol)

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2640]
Hello @tcharp38 

Petit bug sur la dernière beta installée ce matin (231027-BETA2), les télécommandes virtuelles ne fonctionnent plus. J'obtiens le message suivant :
```
ERREUR: Commande inattendue: '{"onoff":"1","addressMode":"01","priority":4,"dest":"Abeille1","address":"0003","destinationEndpoint":"01","action":"01"}'
ERREUR: Commande inattendue: '{"onoff":"1","addressMode":"01","priority":4,"dest":"Abeille1","address":"0003","destinationEndpoint":"01","action":"00"}'
```

Voici les logs complets : 
[AbeilleLogs-231103.tar.gz](https://github.com/KiwiHC16/Abeille/files/13247902/AbeilleLogs-231103.tar.gz)

Pour info, ces tlc me servent à piloter plusieurs volets, pour une gestion par zone.
Merci d'avance

Xav

PS :  j'avais également le souci sur la précédente version 231024-BETA2 mais j'avais du faire un rollback asap car je partais en vacs, donc je n'avais pas de logs à te fournir

**Comment by tcharp38** [comment]
Effectivement.
Regression de ma part.
Désolé. Je m'y colle.

Tu utilises quelles commandes ?
Si commande de groupe, comment tu le précise ?

**Comment by tcharp38** [comment]
Je pousse une nouvelle beta la de suite.. 231103-BETA-1
Donc dispo demain.

**Comment by Xav-74** [comment]
Merci pour ta réactivité !
Mise à jour faite ce matin.

Il y a du mieux mais encore un petit souci pour les commandes on et off
`ERREUR: Cmd 'cmd-0006': Paramètre 'ep' manquant.`

Et les logs complets : 
[AbeilleLogs-231104.tar.gz](https://github.com/KiwiHC16/Abeille/files/13256089/AbeilleLogs-231104.tar.gz)

PS : j'ai régulièrement le message suivant depuis qq temps, tu sais me dire à quoi ca correspond et si c'est normal ? : 
`La Zigate 1 semble plantée mais impossible de lui faire un cycle OFF/ON.`

**Comment by tcharp38** [comment]
Je creuse ca mais c'est curieux. J'avais normalement anticipé ce pb donc qqch n'est pas propre.
Comment as tu défini le groupe à associer ?

**Comment by tcharp38** [comment]
J'ai trouvé. Je n'avais pas les yeux en face des trous.

A decompresser dans Abeille/core/class
[AbeilleCmdProcess.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13256207/AbeilleCmdProcess.class.php.zip)

puis redemarrer le démon Abeille

Ca sera dans la beta de demain

**Comment by Xav-74** [comment]
👍 
Tout est OK pour moi
Merci pour ta réactivité !

**Comment by tcharp38** [comment]
J'aimerais bien que tu me dises comment tu l'utilises.
Il y a plusieurs options sur cette commande virtuelle. Je suppose que tu n'utilises que la commande ON/OFF/TOGGLE groupe ?
Et si oui, tu definies comment le groupe ?

**Comment by Xav-74** [comment]
Yes je te confirme que j'utilise exclusivement les commandes On et Off via un virtuel et scénario (je gère comme cela car j'ai également des positions favorites pour ces groupes de volets)

Côté Abeille, je sélectionne les volets du groupe puis je définis un numéro de groupe et enfin `Add Group` 
Ensuite je sélectionne ma tlc virtuel et je fais un `Set Group Remote` avec le numéro précédent. Au final ca donne ca chez moi (et ca fonctionne au top) : 

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/4e701485-118e-433f-a04a-e24daea60117)

**Comment by tcharp38** [comment]
Ha tu m'en apprends des choses :)
Jamais utilisé cette fonctionalité.
Merci
