### ISSUE TITLE
[KiwiHC16] Refresh network ne semble pas recuperer les infos des routeurs non définis dans Jeedom db.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2642]
Semble remonter la table de zigate mais n interroge pas les routeurs (RIen en zigbee sniff)

![Capture d’écran 2023-11-05 à 15 54 38](https://github.com/KiwiHC16/Abeille/assets/8549674/28b2d642-971e-4e3c-bd80-42d1b2c36e76)

Roue orange

Jeedom 4.3.19 et Zigate V1 Frimware 0004-0323

**Comment by KiwiHC16** [comment]
Ca semble interroger les routeurs s'ils sont connus par Abeille mais pas s'ils ne sont pas connus par Abeille.
Si c est le cas, on a perdu une super fonctionne de decouverte automatique du reseau et la moi qui repart d'une base mariadb vierge, je galère.

La seule facon actuellement est de refaire une inclusion. Pas top.

J ai un equipement dans le grenier tres difficile d acces, galère...

**Comment by tcharp38** [comment]
Le refresh lqi récupère les routeur connus de la zigate puis recursivement ceux connus de chaque routeur. Connus ou pas de jeedom. Donc je ne comprends pas la sujet.
Bref comme avant.
 Tu as un log lqi qui prouve le contraire ?

**Comment by KiwiHC16** [comment]
Le fonctionnement que tu décris est celui attendu mais ne fonctionne pas. Je suis toujours entrain de re-intégrer tous les devices. Des que j aurai du temps je prendrai des traces.

**Comment by tcharp38** [comment]
Ok. Sans trace c'est difficile mais je vais faire des essais demain en surprimant mes routeur de jeedom et en lançant un refresh lqi

**Comment by KiwiHC16** [comment]
Je viens de finir la mise a jour d'Abeille sur une docker jeedom derniere version et pas de soucis particuliers sauf cas ouverts ce jour, pas critiques. Donc Beta ok pour moi.

**Comment by KiwiHC16** [comment]
Test de ce soir:

Deux prises/plug  intégrées (Ruche/Plug1/Plug2):

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/7ca1fa15-4688-42f1-85a3-1af4f2d39870)

Refresh reseau (Ruche/Plug1/Plug2 sont interrogées):

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/ed1066c1-1b76-4ca6-9a5e-51444865209c)

Suppression Plug1 de Jeedom (Supprimer eq, rien en zigbee):

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/7c7ea609-4f67-4280-9ae8-53ef347aef44)

Affichage reseau toujours idem:

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/684dc5fa-040e-43a7-ba23-384468e8501a)

Refresh réseau:

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/128dc104-6958-419a-8368-20e836463082)

Il a bien trouvé un inconnu...
Mais inconnu n est pas interrogé pour être créé dans jeedom:

![image](https://github.com/KiwiHC16/Abeille/assets/8549674/b939dd1f-0725-43ce-a3b6-a4c7238295e1)

Je suis obligé de faire une inclusion manuellement pour retrouver la prise. Sa suppose que je sache qui elle est et ou elle est poure faire la manip. Par le passé, Abeille interrogeait et créait les equipements manquants dans Jeedom mais sur le reseau.

**Comment by tcharp38** [comment]
Si inconnu et routeur.. bien d'accord avec toi. Il manque une découverte automatique.
Le bouton "réparer" est la pour ça mais pour l'instant il n'est pas comme je veux. Il faut le relancer pour qu'il progresse et lui laisser le temps.
Donc toujours dans les trucs à améliorer progressivement

**Comment by KiwiHC16** [comment]
Ou puis je trouver le bouton réparer ?

**Comment by KiwiHC16** [comment]
Ok je vois une part de réponse dans #2643.

**Comment by tcharp38** [comment]
Le refresh network recupere partiellement les routeurs mais j'ai poussé aujourd hui une correction.
Il les interroge si inconnus. Du coup mon test avec 3 prises differentes supprimées de Jeedom permet de les voir reapparaitre en qq sec apres un refresh network.
C'est dans le master.

**Comment by KiwiHC16** [comment]
Tip top, j essaye immédiatement.

**Comment by KiwiHC16** [comment]
Sur le master: Snif ca ne fonctionne pas:

Situation de depart:

![Capture d’écran 2023-11-08 à 16 31 50](https://github.com/KiwiHC16/Abeille/assets/8549674/b2d7be1a-e95f-4049-ad60-c7de4567c816)

La prise est en adresse: 8C0E

Je supprime la prise depuis la page de la prise:
 
![Capture d’écran 2023-11-08 à 16 32 36](https://github.com/KiwiHC16/Abeille/assets/8549674/8926c3dc-5a73-4e11-b60d-59326bdc42fb)

Donc plus dans la liste:

![Capture d’écran 2023-11-08 à 16 33 11](https://github.com/KiwiHC16/Abeille/assets/8549674/7e13f200-1652-4599-800a-b4a7a12aeb80)

Je vais dans réseau:

![Capture d’écran 2023-11-08 à 16 34 02](https://github.com/KiwiHC16/Abeille/assets/8549674/dbca3024-4d09-49d6-9216-ba1ede4b6c6a)

Et je demande un refresh:

![Capture d’écran 2023-11-08 à 16 34 37](https://github.com/KiwiHC16/Abeille/assets/8549674/b0b65467-27d4-48e6-81ed-44dfd801d645)

Ca bosse:

![Capture d’écran 2023-11-08 à 16 35 03](https://github.com/KiwiHC16/Abeille/assets/8549674/16413257-2e73-425d-b6eb-5cb49f1b3962)

Il identifie un inconnu à la bonne adresse.

Par contre l inconnu est devenu Coordinator ! et la prise routeur:

![Capture d’écran 2023-11-08 à 16 36 20](https://github.com/KiwiHC16/Abeille/assets/8549674/9534278a-bf3a-4aea-bf05-51fcc901f3ac)

Aie aie

Puis rien ;-(

![Capture d’écran 2023-11-08 à 16 37 19](https://github.com/KiwiHC16/Abeille/assets/8549674/b5d8ff35-80e6-4c68-ad0c-11b970ceefba)

Je ne touche à rien, je te laisse la main.

**Comment by tcharp38** [comment]
Allez je reteste sur ma branche apres avoir verifié que tous les fichiers etaient en ligne avec le master.

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/e9bb2db9-5c9c-4ebd-bf35-51cf9ca42d1b)

Je supprime les 3 prises

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/91ea1e94-5c1b-45e9-aea9-c5cd32163335)

Pas eu le temps d'ouvrir le reseau et déja une prise est de retour.
Elle a du faire un reporting et Abeille rebondi immediatement la dessus pour faire l'identification.

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/73f368ab-8ace-49ca-ac52-3d7bb28684d0)

Cette fois je lance un refresh du reseau, et les 2 autres reviennent

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/19129d53-53d8-4c34-9890-46c509b12ea9)

Bref tout est ok pour moi.

Peux tu refaire la manip de ton cote et me filer le package de logs ?

Ha et pour le status de la page santé j'ai compris. Il est créé en meme temps qu'Abeille recupere les infos manquantes.
Du coup il est incomplet mais si tu relances un refresh avec des equipements enfin connus, il redevient ok.

**Comment by KiwiHC16** [comment]
`Ha et pour le status de la page santé j'ai compris. Il est créé en meme temps qu'Abeille recupere les infos manquantes.
Du coup il est incomplet mais si tu relances un refresh avec des equipements enfin connus, il redevient ok.`

Je suis en ligne.

**Comment by KiwiHC16** [comment]
Je suis sur le dernier commit: 35b7611020a41482a5183348569abf70380afaf0 du master mais cela ne fonctionne pas.

Je suis en Zigate V2 USB avec les firmware: 0005-03A0

Inclusion d'une prise OSRAM ou d une prise "BlitzWolf smart plug - 16" fonctionne parfaitement.

Apres supression, aucune creation et apres refresh network indique un inconnu:

![Capture d’écran 2023-11-09 à 19 04 40](https://github.com/KiwiHC16/Abeille/assets/8549674/b0acf970-1aad-4162-9bec-2d24d80d4b76)

Si j'appui sur le bouton de la prise, elle fait un report de l etat qui passe dans Parser:

```
[2023-11-09 19:06:09] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=03, DstEP=01, SrcAddrMode=02, SrcAddr=E271, DstAddrMode=02, DstAddr=0000
[2023-11-09 19:06:09]   FCF=18/General/Serv->Cli, SQN=03, cmd=0A/Report attributes
[2023-11-09 19:06:09]   AttrId=0000/OnOff, AttrType=10, ValueHex=00 => 0
[2023-11-09 19:06:09] Abeille1, Type=8102/Attribute report, SQN=03, Addr=E271, EP=03, ClustId=0006, AttrId=0000, AttrStatus=00, AttrDataType=10, AttrSize=0001
[2023-11-09 19:06:09]   0006-0000 => Handled by decode8002
```

et Abeille log dit:
```
[2023-11-09 19:06:28][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/E271/03
[2023-11-09 19:06:28][DEBUG] :   Unknown device 'Abeille1/E271'
```

Mais cela ne provoque pas abeille pour interroger l'équipement.

Est ce qu'il n y aurait pas un flag dans le soft pour auto-creation ? (Je me souviens qu il y avait ce genre de truc).

Je vais entrer dans le soft pour suivre ce qu il se passe et comprendre pourquoi cela ne fonctionne pas....

**Comment by KiwiHC16** [comment]
Je viens de debrancher la prise et la rebranchée ce qui provoque un Annoucement et la prise est crée.

![Capture d’écran 2023-11-09 à 19 13 02](https://github.com/KiwiHC16/Abeille/assets/8549674/0eb7645e-40fb-4e7b-91e9-791de21e6a49)

**Comment by KiwiHC16** [comment]
```
if ($msg['type'] == "eqAnnounce") {
...
Abeille::createDevice("update", $dev);
```

Semble etre l unique trigger pour la creation.

Pas de creation sur report param, c est ce que j observe.

**Comment by KiwiHC16** [comment]
J'ai une bonne piste et j'ai bien peur qu'une partie du soft est à revoir. J'espere avoir tort.
J ai vu que tu avais créé des variables globales (Ce que j'ai essayé d'éviter tout le temps).
J espere que c est une fausse piste.

- Je demarre Abeille avec 2 prises. Je supprime une prise. Je refresh le réseau et rien ne se produit. 
- Je demarre Abeille avec 2 prises. Je supprime une prise. Je refresh le réseau et rien ne se produit. Je redemarre Abeille. Je refresh le réseau et la prise est trouvée et recréée.

```
function deviceUpdates($net, $addr, $ep, $updates = []) {
            parserLog('debug', 'BEN-----------------');
            if (isset($updates['ieee']))
                $ieee = $updates['ieee'];
            else
                $ieee = null;
            $eq = &getDevice($net, $addr, $ieee, $newDev); // By ref
```

getDevice ne se refere pas a la db mais aux variables globales d apres ma comprehension d ou le soucis.

Variable globale pas mise a jour  sur supression d un eq. Mais remise a jour sur restart Abeille.

Tout cela a confirmer bien sur...

Es tu en ligne avec moi ?

**Comment by tcharp38** [comment]
Alors je n'ai pas tout suivi mais je peux donner qq reponses

- l'equipement supprimé de Jeedom doit entrainer la suppression dans la parser (message eqRemoved je crois).
- j'ai supprimé bon nombre d'acces à la DB car ca bouffe du CPU, total inefficace, surtout en PHP le pire cas (interprété pas compilé).
- le createDevice() met à jour l'equipement ou le crée a partir du modele... donc seulement une fois identifié.
Il y a la creation de l'equipement bien avant ça via un autre message
- Au passage oublie le FW 3.A0. Il semble apporter + de soucis que de solutions. 3.22 recommandé. Ya pas mieux en v2 :(
- Tu veux vraiment pas me filer un package de logs qui montre la suppresion d'un EQ suivie d'un refresh ? Je verrai ce qui se passe dans ton cas mais je t'ai montré que ca marchait nickel sur une de mes v1.

**Comment by KiwiHC16** [comment]
Supression de la prise xiaomi adresse: E271
refresh network

[Abeille.tar.zip](https://github.com/KiwiHC16/Abeille/files/13312280/Abeille.tar.zip)

**Comment by KiwiHC16** [comment]
`l'equipement supprimé de Jeedom doit entrainer la suppression dans la parser (message eqRemoved je crois).`

Si cela doit être le cas, cela ne se produit pas dans mon cas.

Si eq supprimé dans db, &getDevice($net, $addr, $ieee, $newDev) retourne toujours l'équipement, d ou le soucis.

**Comment by KiwiHC16** [comment]
$GLOBALS['eqList'] contient toujours les informations de l'eq supprimé. 

Le probleme vient de là. 

`l'equipement supprimé de Jeedom doit entrainer la suppression dans la parser (message eqRemoved je crois).`

Si c est ca la solution, il faut que je trouve pourquoi cela ne fonctionne pas.

**Comment by KiwiHC16** [comment]
```
www-data@jeedomdevhw:~/html/plugins/Abeille$ grep -R "eqRemoved" *
core/php/AbeilleParser.php:                    } else if ($msg['type'] == 'eqRemoved') {
desktop/js/Abeille.js:                            "&msg=type:eqRemoved_net:Abeille" +
resources/archives/desktop/AbeilleEq-Js.php:                            xhr.open("GET", "plugins/Abeille/core/php/AbeilleCliToQueue.php?action=sendMsg&queueId="+js_queueXToParser+"&msg=type:eqRemoved_net:Abeille"+js_zgId+"_eqList:"+js_eqAddr, true);
```

**Comment by KiwiHC16** [comment]
Je n'ai pas de message eqRemoved qui passe dans AbeilleParser ...

**Comment by KiwiHC16** [comment]
Je pense avoir trouvé la différence entre tes tests et les miens.

Tu dois utiliser:
![Capture d’écran 2023-11-09 à 21 37 33](https://github.com/KiwiHC16/Abeille/assets/8549674/6d576811-0122-4d74-896d-cad9b09f98ab)

Supprimer de Jeedom et dans ce cas dans les logs console Safari, j'ai bien:
![Capture d’écran 2023-11-09 à 21 38 19](https://github.com/KiwiHC16/Abeille/assets/8549674/00343842-8878-4d4b-91b2-32bb21b20b7e)

Qui informe AbeilleParser.

Mais dans mon cas j'ouvre l'equipement:

![Capture d’écran 2023-11-09 à 21 39 10](https://github.com/KiwiHC16/Abeille/assets/8549674/060a6e4f-e519-4c69-a2ba-690d7a61defd)

et je fais supprimer, qui ne laisse aucune trace dans le log console Safari, donc AbeilleParser n'est pas mis à jour.

**Comment by tcharp38** [comment]
Ha ouiiiii bonne piste
Je regarde ça demain. Effectivement il doit y avoir un trou dans la raquette

**Comment by KiwiHC16** [comment]
Voir aussi: #2652

**Comment by KiwiHC16** [comment]
Je clos ce cas et ouvre un sujet plus précis.
