### ISSUE TITLE
[KiwiHC16] How to interrogate a device if we have its short address but eq doesn't exist in Abeille

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2643]

**Comment by KiwiHC16** [comment]
Sur l exemple de #2642, j ai un eq inconnu en adresse courte: 404F

![Capture d’écran 2023-11-05 à 23 20 46](https://github.com/KiwiHC16/Abeille/assets/8549674/71afd9c2-6470-443e-9400-c717c56ebd3c)

Comment puis je faire depuis Jeedom sans touché à l'équipement pour l'interroger et le reconstruire dans Jeedom. Dans la passé j'avais une astuce mais maintenant je ne vois pas comment faire.

**Comment by tcharp38** [comment]
Salut
Comme c'est un routeur ca doit etre jouable.
J'avais commencé un "repair" mais pas finalisé.

Ceci etant via la page EQ/Avancé tu peux initier des tas de choses
mais je te suggere de cliquer "reparer" plusieurs fois en laissant un delai de qq sec entre chaque.

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/d1a9c8f7-da8f-424b-8961-ae20da33ea68)

**Comment by KiwiHC16** [comment]
Dans ce cas le bouton n'est pas au bon endroit. Le bouton existe si l'eq existe dans la db jeedom. Dans mon cas l eq n existe pas dans la db jeedom. Je veux pouvoir l'interroger si je ne connais que son adresse courte. Il faudrait peut être un bouton au niveau de l eq zigate avec la saisie de l adresse courte. Ou mieux un bouton qui cheche tout seul tous le eq manquant dans jeedom mais qui sont dans le reseau zigbee.

**Comment by tcharp38** [comment]
Ce "reparer" est dédié à l'équipement, pour completer et/ou corriger ses infos internes.
Par ex on n'a que son adresse IEEE mais on n'a pas la signature Zigbee, ou pas d'infos sur les clusters supportés.

Mais je vois bien le souci dont tu parles.
Ca cogite depuis un moment et normalement, le "refresh LQI" permet de corriger le cas "le device est dans le reseau mais inconnu de Jeedom"

**Comment by tcharp38** [comment]
@KiwiHC16 
Je considere ce sujet à cloturer.
Je m'explique

Les equipements toujours dans le reseau de la Zigate mais inconnus de Jeedom sont créés et interrogés des qu'ils donnent un signe de vie de maniere automatique. Ca permet progressivement de recuperer toutes les infos necessaires et d'identifier le bon modele. Donc oui la ca peut prendre qq heures pour un equipement qui cause peu.

Le refresh reseau (LQI) declenche la meme chose mais la ca sera qq sec pour des equipements sur secteur qui eux repondent vite. Donc refresh automatique toutes les nuits, ou refresh forcé.

Dans quel cas on doit envoyer une info vers qqch d'inconnu ?

**Comment by KiwiHC16** [comment]
Je suis parfaitement en ligne avec toi. Je clos et on traite dans #2642.
