### ISSUE TITLE
[KiwiHC16] Retour auto etat ampoule IKEA TRADFRIbulbE27opal1000lm ne fonctionne pas. Retour level ok.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2644]

**Comment by tcharp38** [comment]
@KiwiHC16 
Bon j'ai regardé le modele et j'ai trouvé une boulette sur le bind.
Modele corrigé et dans le master

je te laisse refaire une mise à jour ou reset via la page EQ/avancé et me faire un retour.

**Comment by KiwiHC16** [comment]
Des que possible, je backup mon systeme et fait le test.

**Comment by KiwiHC16** [comment]
Je n ai pas de TRADFRIbulbE27opal1000lm pour faire les tests.
Je viens de faire test avec TRADFRIbulbE27WWclear250lm et soucis. La commande bind 0006 envoie en fait sur 0008.

Erreur dans le model visiblement.
```
            "Bind-0006-ToZigate": {
                "use": "act_zbBindToZigate",
                "params": "clustId=0008",
                "execAtCreation": "Yes",
                "execAtCreationDelay": 9
            },
```

Et manque Bind sur 0008.

**Comment by KiwiHC16** [comment]
TRADFRIbulbE27WWclear250lm fonctionne maintenant.
Je retrouve les même erreurs dans TRADFRIbulbE27opal1000lm.

**Comment by tcharp38** [comment]
C'est la ou on s'est marché sur les pieds.
J'avais déja corrigé ça

**Comment by KiwiHC16** [comment]
Ok pas de soucis. Je viens de pousser la modif et cela fonctionne. Je clos.
