### ISSUE TITLE
[KiwiHC16] Telecommande IKEA set group Ok, mais dans Abeille ou definir le groupe pour utiliser la tuile comme si c etait la telecommande ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2645]
Feature perdue en cours de route dans l evolution d abeille ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-05 à 17 03 58](https://github.com/KiwiHC16/Abeille/assets/8549674/09d4a1ae-56bc-4362-a77b-a1d94fe42f5c)

**Comment by KiwiHC16** [comment]
Dans une vieille version d Abeille:

![Capture d’écran 2023-11-05 à 17 05 35](https://github.com/KiwiHC16/Abeille/assets/8549674/eb2b157b-2add-49fb-9a96-55078862d3ad)

**Comment by tcharp38** [comment]
Oui j'ai cassé qqch la mais je vois bien.
Je vais creuser

**Comment by KiwiHC16** [comment]
Dans mes souvenirs, il y avait une partie de code "appelable" pour des categories de produit qui demandent des commandes supplémentaires.

**Comment by tcharp38** [comment]
La gestion des telecommandes est la + compliquée et je n'ai toujours pas réussi à résumer tous les cas de figure pour clarifier ça.
D'ou la regression.

**Comment by KiwiHC16** [comment]
Je viens de retomber sur une partie du code: Abeille-Eq-Advanced-Specific.php

Il y a peut être une relation avec #2650.

Si certains parametres sont definis dans la conf de l'eq ca ajoute des parametres à l affichage. Pour essayer de simplifier j avais des catégories d'eq comme des telecommande, telecommande7groups, paramABC.

Telecommande:
- gestion d un groupe
- Durée: temps necessaire par exemple pour le groupe pour passer de 100% allumé à 0%. (Fonction existante dans les ampoules.
 
telecommande7groups:
- Telecommande à 7 boutons pour controller jusqu a 7 groupes différents

paramABC
- possibilité d applique une calibration sur les volets par exemple pour linéariser le fonctionnement. Y aussi des plugin Jeedom pour faire ca. Donc pas sure du besoin dans Abeille.

**Comment by KiwiHC16** [comment]
Example de la conf d une telecommande sur un vieux systeme:

![Capture d’écran 2023-11-08 à 12 32 58](https://github.com/KiwiHC16/Abeille/assets/8549674/a63fe079-1437-46aa-9e3c-164fad44b84f)

et ce parametre n existe pas sur un systeme fraichement installé.

**Comment by KiwiHC16** [comment]
```
desktop/php/Abeille-Eq-Advanced.php:        include 'Abeille-Eq-Advanced-Specific.php';
```

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-08 à 12 44 34](https://github.com/KiwiHC16/Abeille/assets/8549674/1e40f514-0272-45ad-a486-e1d2fb96f062)

Les positions X, Y, Z ont aussi disparu et tu en auras besoins pour
![Capture d’écran 2023-11-08 à 12 45 38](https://github.com/KiwiHC16/Abeille/assets/8549674/97d6d4f8-be5d-4fc0-af3c-24ae8899d48b)

**Comment by KiwiHC16** [comment]
L'info est bien dans le template TRADFRIremotecontrol:

```
 {
    "TRADFRIremotecontrol": {
        "manufacturer": "Ikea",
        "model": "5 buttons remote",
        "type": "IKEA 5 buttons remote control",
        "genericType": "Light",
        "timeout": "60",
        "configuration": {
            "mainEP": "01",
            "paramType": "telecommande",
            "icon": "Ikea-Remote-5buttons",
            "batteryType": "1x3V CR2032"
        },
        "category": {
            "light": "1"
        },
        "commands": {
         bla lba bla
```

**Comment by KiwiHC16** [comment]
Le code semble bien le prendre en compte dans createDevice dans Abeille.class.php:

![Capture d’écran 2023-11-08 à 13 10 51](https://github.com/KiwiHC16/Abeille/assets/8549674/cd7faa71-73fe-4746-b1f1-cb36e5b483df)

**Comment by KiwiHC16** [comment]
Autre test:

Creation d une telecommande virtuelle:

![Capture d’écran 2023-11-08 à 13 18 40](https://github.com/KiwiHC16/Abeille/assets/8549674/6610b9be-a9eb-4c24-9d75-49239c622eb6)

J ai bien le parametre:

![Capture d’écran 2023-11-08 à 13 19 06](https://github.com/KiwiHC16/Abeille/assets/8549674/f82ff016-2d17-48e6-b4d9-9fc21838192d)

Par contre pas d affichage pour visualiser le groupe contrôlé cette telecommande.

**Comment by KiwiHC16** [comment]
Dans Abeille-Eq-Advanced-Specific.php, si je force le test:

```
<?php
    /* If device is a remote control. 'paramType' is defined in device JSON file */
//    if ($eqLogic->getConfiguration('paramType', '') == "telecommande") {
    if (1) {
?>
```

alors j ai bien l affichage.

$eqLogic n est probablement pas défini...

Je confirme. Il faut virer ces tests pour telecommande, telecommande7 et paramABC et mettre du code d affichage dans Abeille.js

js recupere les infos par ajax url: "plugins/Abeille/core/ajax/Abeille.ajax.php",

**Comment by KiwiHC16** [comment]
Je viens de pousser une correction pour avoir le groupe des télécommandes. Ca semble ok mais ca crée une zone noire si rien n est affiché et les calages de texte ne sont pas terribles  dans le cas d une telecommande. Reste a faire de la mise en page.

**Comment by KiwiHC16** [comment]
Reste à tester que la télécommande pilote bien des groupes d ampoules dans la vraie vie.

**Comment by KiwiHC16** [comment]
Fonctionne dans la vrai vie avec une prise dans un groupe. Je clos donc.
