### ISSUE TITLE
[KiwiHC16] Retour etat Gledopto Spectre Blanc & Gledopto RGBW GU10 ne fonctionne pas apres inclusion

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2646]
See also #2644

**Comment by tcharp38** [comment]
Tu ajoutes un package de logs et/ou des details ? 
Pas d'idée de quoi chercher la.

**Comment by tcharp38** [comment]
Bon j'ai regardé le modele et j'ai trouvé une boulette sur le bind.
Modele corrigé et dans le master
je te laisse refaire une mise à jour ou rest via la page EQ/avancé et me faire un retour.

**Comment by tcharp38** [comment]
@KiwiHC16 
Bon au final j'ai trouvé la aussi une boulette de bind, corrigé dans les modeles sous master et dans la beta de demain.

Mais comme je ne sais pas ce qui ne fonctionne pas, je te laisse tester et me donner des details.

**Comment by KiwiHC16** [comment]
Gledopto Spectre Blanc -> Modele: GL-S-004Z

Gledopto RGBW GU10 -> modele: GL-S-003Z

**Comment by tcharp38** [comment]
Ca ne fonctionne toujours pas apres une "mise à jour" ou "reset" du modele ?
La reconfig du device est necessaire

**Comment by KiwiHC16** [comment]
Il faut que je déplace mon sniffer car lors des tests je ne voyais pas les messages, je pense que je suis trop loin des équipements. Tests à venir.

**Comment by KiwiHC16** [comment]
GL-S-004Z 
Pas de réponse au bind envoyé par Zigate

Demande de la table de bind: réponse "pas supporté"

**Comment by tcharp38** [comment]
Je pense que tu n'es pas aligné sur le master

**Comment by KiwiHC16** [comment]
Avec le dernier master:

Ampoule Blanche - GL-S-004Z

Bind Etat et Level ok:

![Capture d’écran 2023-11-13 à 16 31 02](https://github.com/KiwiHC16/Abeille/assets/8549674/4e52c7c5-1a45-461b-b750-27ef0e03bca0)

Puis plusieurs UnBind fini par repondre "No Entry". Tout ok jusque la.

A un Bind Table request, la reponse est "Pas supporté".

Status: 0006-0B-0000, essai de setReport sur 0000.

![Capture d’écran 2023-11-13 à 16 40 05](https://github.com/KiwiHC16/Abeille/assets/8549674/4c6d9ae8-d7ee-4093-8d83-2b7729860145)

Aucune réponse.

**Comment by KiwiHC16** [comment]
Je laisse tombé, le reporting ne fonctionne pas a ce jour avec ces ampoules.
