### ISSUE TITLE
Création de groupe 

### ISSUE THREAD

**Issue by pinton40** [KiwiHC16/Abeille#2648]
Bonjour, je rencontre un problème je ne peux plus créer de groupe d'éclairage chaque fois que je fais une sélection de luminaire et que je veux faire add group ça m'indique aucun équipement sélectionné ,même problème pour set group remonte. Par contre j'ai réussi a créé un groupe en allant directement sur chaque équipement, menu avance ZLC:ADDgroup. comment faire maintenant pour affecter la télécommande Ikea Ronde. Merci d'avance.

**Comment by tcharp38** [comment]
Salut @pinton40 
Je te suggere de basculer sur la beta Abeille. La stable est bien trop vieille maintenant.
Il me semble avoir corrigé ce type de souci.

https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by pinton40** [comment]
Salut,
Je viens de passer en version bêta la commandes add group fonctionne mais tous les équipements avec des commandes on off ne fonctionne plus.  j'ai  procédé à une restauration sur la version stable tout refonctionne sauf ma télécommande Ikea.

**Comment by tcharp38** [comment]
Désolé. Régression déjà corrigée pour la bêta de demain.

**Comment by pinton40** [comment]
Salut,
Merci Pour le correctif. Je suis repassé en bêta et toutes les commandes ON OFF fonctionnent par contre le retour d'état sur les ampoules ikea ne fonctionne plus ainsi que sur le module 3 relais Iolloi .
Merci d'avance de ton retour

**Comment by tcharp38** [comment]
Peux tu du coup faire ON ou OFF sur ton device (noter l'heure)
puis me filer le package de logs qq mins apres ?

Et me dire de quel device il s agit

**Comment by pinton40** [comment]
[AbeilleCmd.log](https://github.com/KiwiHC16/Abeille/files/13311872/AbeilleCmd.log)
voici les trois appareil qui n'ont plus le retour d'état.

**Comment by pinton40** [comment]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/13311944/Abeille.txt)

**Comment by pinton40** [comment]
[Uploading ABEILLE.txt…]()

**Comment by tcharp38** [comment]
J'ai besoin du package de logs... page maintenance + telecharger tout + glisser/deposer ici
Ha et attention mode debug + sauvegarder sur la page config
Et config des logs => 5000lignes

voir https://kiwihc16.github.io/AbeilleDoc/Debug.html

La ta trace est quasi vide

**Comment by pinton40** [comment]
[AbeilleLogs-231109.tar.gz](https://github.com/KiwiHC16/Abeille/files/13312574/AbeilleLogs-231109.tar.gz)
Ok Je suis désolé voici le log

**Comment by tcharp38** [comment]
Quels sont les appareils qui n'ont plus de retour d'etat ?
La beta sur laquelle tu es passée doit avoir corrigé certains de ces pbs.

**Comment by pinton40** [comment]
Oui la bêta a corrigé toutes les commandes on off par contre je n'ai pas le retour d'état sur le trois contacts du module Orvibo multi-functional relay et sur les lampes : lampe salle a manger et lampe salon.

**Comment by tcharp38** [comment]
Pour la lampe... je te laisse tester sur la beta qui sera dispo demain.
Pour Orvibo.. la pour l'instant je pige pas.

**Comment by pinton40** [comment]
Ok Je teste ça demain merci.

**Comment by pinton40** [comment]
Je vais essayer de faire une nouvelle inclusion pour le module Orvibo.

**Comment by tcharp38** [comment]
Oui file moi le package de logs dans la foulée aussi STP.

**Comment by pinton40** [comment]
[AbeilleLogs-231110.tar.gz](https://github.com/KiwiHC16/Abeille/files/13321609/AbeilleLogs-231110.tar.gz)

**Comment by tcharp38** [comment]
La decouverte n'est plus necessaire mais tu peux m'envoyer ton fichier discovery si tous les voyants sont passés au vert.

**Comment by pinton40** [comment]
Comment puis je te récupérer ce fichier discovery?

**Comment by tcharp38** [comment]
Click sur ton EQ + avancé + assistant decouverte
La ca doit se remplir automatiquement mais sinon tu peux relancer chaque etape avec le bouton correspondant.
Tout doit passer au vert.
apres quoi zip et ici

**Comment by pinton40** [comment]
[discovery-396483ce8b3f4e0d8e9d79079a35a420_ORVIBO.json](https://github.com/KiwiHC16/Abeille/files/13321784/discovery-396483ce8b3f4e0d8e9d79079a35a420_ORVIBO.json)

**Comment by tcharp38** [comment]
Bon on est en train de pourrir ce sujet "Creation de groupe".
Sauf si il y a encore un truc à voir de ce cote on peut fermer ?
Je te laisse ouvrir un sujet dédié Orvibo 396483ce8b3f4e0d8e9d79079a35a420 en précisant le modele correspondant STP car je viens de trouver un vieux sujet ou toi meme tu disais tout est ok sur mon "82c167c95ed746cdbd21d6817f72c593" la https://github.com/KiwiHC16/Abeille/issues/2024#top
