### ISSUE TITLE
Prise connectée Tradfri Control Outlet - cmd-0006 - On / Off inopérant

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2649]
Hello @tcharp38 

Sur la dernière beta `2023-11-07 01:00:32`
Pour les prises connectées Tradfri Outlet Control, les actions On / Off / Toggle sont inopérantes. Peut-être souci sur la migration vers cmd-0006 ;)

Logs complets : (tests à 18h34 sur les logs Cmd)
[AbeilleLogs-231107.tar.gz](https://github.com/KiwiHC16/Abeille/files/13284239/AbeilleLogs-231107.tar.gz)

Xav

**Comment by tcharp38** [comment]
Hello.
Oui désolé. Pb déjà corrigé pour la bêta de demain.

**Comment by tcharp38** [comment]
Tu peux tester ça en attendant
https://github.com/KiwiHC16/Abeille/files/13281658/AbeilleCmdProcess.class.php.zip

A décompresser dans core/class d Abeille
Désolé pour la regression

**Comment by Xav-74** [comment]
All is good ! As usual :)
Et pas de souci les beta sont faites pour ca !
