### ISSUE TITLE
[KiwiHC16] Mise a jour par git de la version de mars avec le dernier master: Probleme d affichage.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2650]

**Comment by KiwiHC16** [comment]
Je suis sur la page des Abeilles:

![Capture d’écran 2023-11-08 à 11 40 23](https://github.com/KiwiHC16/Abeille/assets/8549674/e0d02b68-a76c-40ac-ad47-e799653adf6d)

Je clic sur une Abeille, disons Ch Enfant Fenetre, et la ecran noir:

![Capture d’écran 2023-11-08 à 11 41 03](https://github.com/KiwiHC16/Abeille/assets/8549674/75457cb4-4c3c-4f4e-a3f3-a7523d2c178b)

En fait c est pas complètement noir car les infos sont tout en bas de la page donc invisible sur l ecran:

![Capture d’écran 2023-11-08 à 11 41 56](https://github.com/KiwiHC16/Abeille/assets/8549674/51dbf930-00d7-4c1f-8e49-0f4d92d3b1cb)

Je suis en Jeedom 4.1.27.

Je crois avoir eu le même soucis en 4.3.19. Du coup j ai refait une installation depuis zéro et re-intégres mes abeilles sans rencontrer le soucis. Très surprenant.

**Comment by KiwiHC16** [comment]
Sur le systeme qui ne fonctionne pas:

![Capture d’écran 2023-11-08 à 11 48 52](https://github.com/KiwiHC16/Abeille/assets/8549674/22028eb8-6484-4980-820c-3cd19dad6d0d)

Sur le systeme qui fonctionne:

![Capture d’écran 2023-11-08 à 11 49 54](https://github.com/KiwiHC16/Abeille/assets/8549674/bfb21c47-ee18-4d1e-aa9c-ef683f6d0058)

**Comment by KiwiHC16** [comment]
Comprtement identique sur Safari et sur Firefox.

Un grep ne donne rien:
```
~/html$ grep -R 'style="height: 1000px;' *
```

**Comment by KiwiHC16** [comment]
Si je vire le code suivant dans Abeille-Eq.php alors ca fonctionne:

```
<!-- For all modals on 'Abeille' page. -->
<div class="row row-overflow" id="abeilleModal">
</div>
```

Dans quels cas ce code est il necessaire ?

**Comment by tcharp38** [comment]
Comment tu expliques que ca tombe en marche avec le meme code ?

**Comment by KiwiHC16** [comment]
Une reference dans js est:

```
/* Allows to select of cmd Json file & load it as a new command */
```

![Capture d’écran 2023-11-08 à 12 07 47](https://github.com/KiwiHC16/Abeille/assets/8549674/e53080bf-0107-4ea9-96e2-9a920617f313)

et une autre semble être:

```
/* Called when 'setTimeout' button is pressed
   Allows to modify timeout of selected equipements. */
```

**Comment by KiwiHC16** [comment]
> Comment tu expliques que ca tombe en marche avec le meme code ?

Absoluement aucune idée car je ne comprends le role de ce code. Il doit y avoir du js dans l histoire avec un paramètre quelque part qui est different entre une install de zero et une mise a jour git. 

Quelque chose ajout le style dans la ligne et je ne trouve pas ou dans le code.

**Comment by KiwiHC16** [comment]
Si je déplace le code suivant à la fin d Abeille-Eq.php alors le visuel "normal" et je ne perds pas de soft si celui ci est vraiment nécessaire:
```
<!-- For all modals on 'Abeille' page. -->
<div class="row row-overflow" id="abeilleModal">
</div>
```

**Comment by KiwiHC16** [comment]
Cette solution de contournement fonctionne donc je clos.
