### ISSUE TITLE
[KiwiHC16] Clarification de la methode de suppression d un equipment 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2652]

**Comment by KiwiHC16** [comment]
Actuellement dans Abeille nous avons deux facons de supprimer un équipement (eq):
- A/ Par le bouton "Supprimer" d'origine de Jeedom en rouge dans la page de definition standard de l eq.
- B/ Par le bouton "Supprimer de Jeedom"  dans la page de configuration du plugin en Orange.

2 soucis rencontrés:
- A/ n informe pas AbeilleParser et de ce fait un refresh network ne recupere pas les equipements perdus dans Abeille mais toujours sur le réseau.
- B/ ne permet pas d avoir les fonction de Jeedom qui idenfifie les liens avec les scenario, les autres eq qui vont être impactés par la suppression 

Je propose de passer par la fonction de suppression de Jeedom par defaut et d'ajouter les fonction de suppression d'Abeille par dessus pour recuperer toutes les dfocntionnalités et les benefices des deux.

**Comment by KiwiHC16** [comment]
Exemple de A/

![Capture d’écran 2023-11-10 à 11 14 58](https://github.com/KiwiHC16/Abeille/assets/8549674/2c3985b2-54ac-46a6-8c31-b99cb9e8c673)

![Capture d’écran 2023-11-10 à 11 15 07](https://github.com/KiwiHC16/Abeille/assets/8549674/d85ee2ea-bdc1-4a19-af4b-6497007db0f0)

Vue la taille de ma solution Jeedom cette fonctionnalité est critique pour moi.

**Comment by tcharp38** [comment]
Compris.
En cours

**Comment by tcharp38** [comment]
Dans le master.
Si multiple selection alors la fenetre d'interrogation apparaitra pour cheque équipement selectionné.
Et le parser est informé dans la foulée ce qui doit corriger le #2642

**Comment by KiwiHC16** [comment]
Super, je vais tester ca.

**Comment by KiwiHC16** [comment]
D apres mes testes:

A/ Par le bouton "Supprimer" d'origine de Jeedom en rouge dans la page de definition standard de l eq.

=> pas de changement, ne fonctionne pas comme décrit dans https://github.com/KiwiHC16/Abeille/issues/2642

B/ Par le bouton "Supprimer de Jeedom" dans la page de configuration du plugin en Orange.

=> J ai bien la modification qui donne la liste des scenarii et autres impactés par la suppression.

**Comment by tcharp38** [comment]
Ha oui il manque qqch sur le cas A. Suis con.

**Comment by tcharp38** [comment]
Voila cas A traité.
Il faut détourner une action de base de Jeedom pour ça et ca semble rouler.

**Comment by KiwiHC16** [comment]
Super. Je vais tester.

**Comment by KiwiHC16** [comment]
Pas de changement dans le comportement. 

J'ai une Zigate et une prise. J'ouvre la page de la prise et la supprime (Cas A/), je rafraichi le reseau, elle apparait dans les voisines mais Abeille ne recrée pas la prise. Je relance les daemons , relance le refresh du reseau et j ai bien la (re) creation de la prise.

Je suis sur la derniere master
```
commit 2c7f49f1fa3840a4352551c23a5babf2fc79751e (HEAD -> master, origin/master, origin/HEAD)
Author: Tcharp38 <tcharp38@laposte.net>
Date:   Mon Nov 13 15:31:18 2023 +0100

    No-ACK status for always listening devices only
```

**Comment by tcharp38** [comment]
Je reflechis à nouveau à la situation pour voir ce que j'ai zappé.

**Comment by tcharp38** [comment]
Je seche.
Ca fonctionne tres bien pour moi.
Je vois le message suivant dans le parser apres suppression

    1245|[2023-11-14 12:35:37] Some equipments removed from Jeedom
    1246|[2023-11-14 12:35:37]   Device Abeille1/85C7 (ieee=CC86ECFFFEFA8AB0) removed from Jeedom

puis il reapparait progressivement lors du refresh reseau comme tu peux le voir dans ces logs
[Downloads.zip](https://github.com/KiwiHC16/Abeille/files/13348313/Downloads.zip)

Si tu refais la manip et me file ton package de logs peut etre que qqch me sautera aux yeux.

**Comment by KiwiHC16** [comment]
Ok, je dois encore faire une migration et ensuite je pourrai refaire des tests.

**Comment by KiwiHC16** [comment]
Sur la master :
```
commit 98ef62d1664fa5fb7e06d3d21b2f7903736b768e (HEAD -> master, origin/master, origin/HEAD)
Author: Tcharp38 <tcharp38@laposte.net>
Date:   Wed Nov 15 10:41:16 2023 +0100

    TS0205__TZ3210_up3pngle
```

Situation de départ:

![Capture d’écran 2023-11-15 à 14 42 32](https://github.com/KiwiHC16/Abeille/assets/8549674/7cf208f4-cd6f-426c-b9c2-97bec5a18327)

Reseau refresh:
![Capture d’écran 2023-11-15 à 14 43 44](https://github.com/KiwiHC16/Abeille/assets/8549674/a038327d-d95e-4eae-83bf-7e85730fa757)

Message zigbee:
![Capture d’écran 2023-11-15 à 14 45 40](https://github.com/KiwiHC16/Abeille/assets/8549674/fb66e330-6503-4e9d-8b13-6b383af5fb34)


Tout est ok.

Je supprime la prise, bouton rouge en haut a droite:

![Capture d’écran 2023-11-15 à 14 44 28](https://github.com/KiwiHC16/Abeille/assets/8549674/2eed689e-c147-487c-98e2-11ef602932c0)

![Capture d’écran 2023-11-15 à 14 45 05](https://github.com/KiwiHC16/Abeille/assets/8549674/cf9e43c8-6e89-494f-9a30-f74267efa932)

Je n'ai plus que la ruche.

Rien ne se passe.

J'appuie sur bouton physique de la prise, elle fait un report attribute:
![Capture d’écran 2023-11-15 à 14 47 31](https://github.com/KiwiHC16/Abeille/assets/8549674/c321ce7e-b98c-44ed-b74b-98e3eee6e374)

Toujours rien sur Abeille.

Je debranche et rebranche la prise et ca fonctionne alors que le coup d avant ca n avait pas fonctionné !!!

**Comment by KiwiHC16** [comment]
Bon ben je viens de faire la manip 5 fois et ca fonctionne donc je clos le sujet. ;-)
