### ISSUE TITLE
[KiwiHC16] La fonction Leave ne fonctionne pas.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2653]

**Comment by KiwiHC16** [comment]
Si je fais un "Exclure" de l ampoule:
![Capture d’écran 2023-11-10 à 14 16 50](https://github.com/KiwiHC16/Abeille/assets/8549674/1d7a6db3-e52d-403b-b550-98180487b548)

J ai bien un leave sur la radio:

![Capture d’écran 2023-11-10 à 14 18 38](https://github.com/KiwiHC16/Abeille/assets/8549674/31f139f9-b3e5-47e9-851e-be71a0a47381)

Si j ouvre l equipement et fais un "Leave":
![Capture d’écran 2023-11-10 à 14 19 15](https://github.com/KiwiHC16/Abeille/assets/8549674/6bcf944e-d8c8-4f13-8c2e-acf0fd9edd03)

alors rien sur la radio. Ce Leave ne fonctionne pas.

**Comment by KiwiHC16** [comment]
Le "Leave" ne provoque aucune trace dans AbeilleCmd.log.

**Comment by tcharp38** [comment]
Correction dans le master.
Regression sur plusieurs interrogations.

**Comment by KiwiHC16** [comment]
Ok pour moi. Je clos.
