### ISSUE TITLE
[KiwiHC16] No-Ack

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2654]
Sur la version master 971e97073784f9344e8ed8d8c63505dd6c3e0689: 

![Capture d’écran 2023-11-13 à 10 05 18](https://github.com/KiwiHC16/Abeille/assets/8549674/5746b2c1-0f3e-48a9-88f9-d00caad03940)

Les équipements sur batterie sortent en No-Ack en rouge ce qu'il fait penser qu'il y a un soucis alors que si je regarde les timeout tout est ok.

**Comment by tcharp38** [comment]
Yes, pas encore carré de ce côté.
Mais tu viens de redemarrer non ?

De mon coté ca n'est pas le cas. Pas ce souci avec les eq sur batterie

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/fe32d7c9-8b97-4ad9-acc0-7ded83410905)

**Comment by KiwiHC16** [comment]
Ca tourne depuis plusieurs jours et c est le constat ce matin.

**Comment by tcharp38** [comment]
Je vais revoir comment ce status peut apparaitre mais avec les logs le support est toujours + efficace.

**Comment by tcharp38** [comment]
Bon apres reflexion, cette idée est dangereuse.
A la base j enregistrais le TX status lors de l'envoi d'une commande mais si le user demande une lecture quelconque vers un device sur piles.. ce qui ne peut pas marcher sans le reveiller au bon moment, ca ne peut qu'aboutir à ce status.
Je dois revoir ma copie et limiter ce status qu'aux devices "en ecoute permanente". Pour les autres c'est trop dangereux comme tu le montre la

**Comment by KiwiHC16** [comment]
Je suis en ligne avec toi.

**Comment by tcharp38** [comment]
Mise-à-jour dans le master.
Donc "NO-ACK" limité aux devices en ecoute permanente.

**Comment by KiwiHC16** [comment]
Ok, super, je vais essayer de tester.

**Comment by KiwiHC16** [comment]
Pour moi c est Ok, je clos.
