### ISSUE TITLE
[KiwiHC16] Bind, remove bind, bind group, remove bind group ne fonctionnent pas.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2655]
Si appel depuis une commande d un eq alors fonctionne. Mais si appel depuis la page générique ca ne fonctione pas. Rien dans les traces AbeilleCmd.

![Capture d’écran 2023-11-13 à 13 18 51](https://github.com/KiwiHC16/Abeille/assets/8549674/ed286c1e-51a6-4c59-a9c9-af230ba900c2)

**Comment by KiwiHC16** [comment]
Abeille-Eq-Advanced-Interrogations.php

```
addButton("{{Unbind}}", "btn-danger", "unbindToDevice");
```

Abeille.js:
```
topic = "Cmd" + logicalId + "_bind0030";
...
xhttp.open(
        "GET",
        "/plugins/Abeille/core/php/AbeilleCliToQueue.php?action=sendMsg&queueId=" +
```

**Comment by KiwiHC16** [comment]
js ne trouve pas ieee

![Capture d’écran 2023-11-13 à 13 31 54](https://github.com/KiwiHC16/Abeille/assets/8549674/7df4abb6-988f-47aa-849d-505496910ac0)

**Comment by tcharp38** [comment]
Mais... t'es sur d'etre à jour ?
Ca fait partie des corrections deja faites ca et chez moi ca fonctionne.

**Comment by KiwiHC16** [comment]
Ah ok, je pull alors. Merci.

**Comment by KiwiHC16** [comment]
Effectivement c est Ok. Donc je clos. Tu vas plus vite que la lumière !!!
