### ISSUE TITLE
[KiwiHC16] Inclusion detecteur de porte xiaomi ne fonctionne plus. 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2656]
Impossible d inclure mes capteurs de porte xiaomi. Je fini mes inclusions et je prends des log.

**Comment by tcharp38** [comment]
J'ai refais plusieurs essais en supprimant et sans supprimer.. le door sensor est bien reconnu.
Ces essais m'ont neanmoins permis de corriger qq trucs.

**Comment by KiwiHC16** [comment]
J ai fait 80% des inclusions et je dois encore faire des migrations et ensuite je peux faire des tests et prendre des logs.

**Comment by KiwiHC16** [comment]
Bon ben aujourd'hui tout est ok. Va savoir... Je clos.
