### ISSUE TITLE
[KiwiHC16] Perte complete de 3 prises BliTZOIF (Briques)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2660]
Suite à des inclusions multiples, j'ai 3 prises complément "Briques":
- 2 clignotent: le relai interne, claque rapidement toutes les x secondes. HS ?
- 1 ne repond plus aux solicitations sur le bouton physique : on ne peut plus controller le relai, ni faire d inclusion. HS ? 

HS ? Toutes en 2 jours ? Abeille qui envoie une séquence qui les rend HS ?

Pas le début dune piste, investigations à venir.

(J'en ai au moins 4 qui fonctionnent très bien par ailleurs.)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-15 à 15 28 21](https://github.com/KiwiHC16/Abeille/assets/8549674/6e33ac31-7479-44b7-8398-869fb5a07271)

**Comment by KiwiHC16** [comment]
Info sur l une qui fonctionne sur mon réseau:
![Capture d’écran 2023-11-15 à 15 31 09](https://github.com/KiwiHC16/Abeille/assets/8549674/90890fd6-4d37-4920-9327-44c87acc1ce9)

**Comment by KiwiHC16** [comment]
Prise 1:
- Appui sur bouton lateral pour que la led passe en rouge
- Toutes les 16s, elle passe à Off pendant 1/4 de s puis On. Ca donne l impression qu'elle reboot...
- SI appui 7s sur bouton alors que Led Rouge, alors led bleue apprait fixe pendant 1 à 2s (Elle devrait flasher), puis relai claque, Led rouge revient et bleue éteinte 
- Zigate en mode inclusion et jamais aucune trame zigbee venant de la prise
- Si Led rouge éteint alors rien ne se passe. Mais peut etre toutes le 16s ca "reboot" mais comme le relai est off et led off on ne voit rien se passer.

**Comment by KiwiHC16** [comment]
Prise 2:

- Idem Prise 1

**Comment by KiwiHC16** [comment]
Prise 3:

- rien ne bouge.

**Comment by tcharp38** [comment]
Tu as remarqué que tu étais sur le canal 15 d'apres tes logs?
Peut etre une incompatibilité ?

**Comment by KiwiHC16** [comment]
Oui, j ai vu. Mais le comportement des prises qui "reboot" toutes les 16s c est meme avec zigate éteinte.

Je viens d'en ouvrir (détruire) une et le composant radio est ZT2S: https://developer.tuya.com/en/docs/iot/zt2s-module-datasheet?id=Kas9gdtath9p0 et pour flasher le code: https://developer.tuya.com/en/docs/iot/overview-of-download-firmware-and-authorization?id=Ka4zcqfo0eb5u

**Comment by tcharp38** [comment]
Mais tu dis que 3 prises sont HS en meme temps ? C'est statistiquement pas possible ca

**Comment by KiwiHC16** [comment]
Mon idée est que lors de la reconnaissance des prises, Abeille envoie des configurations que les prises n aiment pas, elles mettent ca en PROM et apres c est le bazar. Aucune preuve, aucun log. Juste un feeling par rapport au moement du plantage des prises. ET pourquoi ces trois là et pas les autres que j'ai ?
Le probleme c est que je ne trouve pas comment les "réveiller"...

**Comment by tcharp38** [comment]
Incroyable !
Ca veut dire pas de HW reset sur ces prises ?
Peut etre en les laisser debranchées un moment ?

**Comment by KiwiHC16** [comment]
Rien de visible au niveau hard (Rien n a brulé, ...) Tout semble Ok.

Aucune piste pour l instant.

**Comment by KiwiHC16** [comment]
Je clos car pas de lien direct avec code Abeille et la chance de trouver la raison est quasi nulle. Si je trouve des infos, je partagerai.

**Comment by KiwiHC16** [comment]
Premiere observation à vérifier, dans le modele il semble qu'une valeur manque, est ce que le code Abeille le gere ?

![Capture d’écran 2023-11-27 à 16 03 34](https://github.com/KiwiHC16/Abeille/assets/8549674/1c64c9c2-93c6-4307-981e-0fb0490a9197)

```
changeVal=
```

![Capture d’écran 2023-11-27 à 16 04 28](https://github.com/KiwiHC16/Abeille/assets/8549674/8e6e88a6-aeff-43c1-b181-c2ca8dbfdab3)

![Capture d’écran 2023-11-27 à 16 04 54](https://github.com/KiwiHC16/Abeille/assets/8549674/eb718c69-61f9-4c02-ad41-540a313bd351)

La valeur est visiblement manquante dans le message zigbee.

**Comment by KiwiHC16** [comment]
configureReporting2

**Comment by tcharp38** [comment]
Oui c'est un sujet que je voulais creuser mais avant tout ... la spec se comprend comment ?

Ces paramtres sont optionnels à priori
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/bf7f08a6-9de8-4799-8291-52022f1e5468)

Une idée ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-27 à 16 24 58](https://github.com/KiwiHC16/Abeille/assets/8549674/d6cfcd22-3288-4066-ad5f-e7784a3427e5)

Je viens de la perdre sur cette commande. Je l ai passé de configureReporting à configureReporting2 dans le modele. Sur zigbee, ca par en vrille, la prise fait un volume incroyable de "report", puis rien puis "reset" toutes les 16s sans plus qucun message zigbee.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-27 à 16 28 23](https://github.com/KiwiHC16/Abeille/assets/8549674/b3dea80c-52eb-4546-9dbc-4eb37ddf4dba)

Ca balance des routes requests alors que je n ai que la zigate et la prise sur ce reseau.

Ne reagit plus avec le bouton sur le coté.

Ne repond plus à aucune commande demandée par Abeille. En fait la zigate fait un route request n'a pas de reponse, et donc n envoie pas la commande.

Finalement repond sur le bouton physique mais un appui long provoque led bleu mais pas de clignotement de celle ci et pas de beacon/Leave sur zigbee.

Je debrance et rebranche, elle fait des Route Request et des Link status donc elle est vivante mais ne repond plus à rien.

**Comment by tcharp38** [comment]
Quelle est la signature de cette prise ?

**Comment by KiwiHC16** [comment]
Bon sans acces au FW, c est mort. Je laisse tomber !

**Comment by tcharp38** [comment]
Comment ca .. une autre morte ?

**Comment by KiwiHC16** [comment]
TS011F__TZ3000_amdymr7l

**Comment by tcharp38** [comment]
Tu peux refaire une autre inclusion ou c'est mort ?

**Comment by KiwiHC16** [comment]
Oui une autre. Il faudrait pouvoir faire un reset PROM mais je n ai pas trouvé comment faire.

**Comment by KiwiHC16** [comment]
Est l accumulation de configuration qui prove ce bug ? Je veut dire que ces prises ont toutes fonctionné une premiere fois d'apres ma mémoire. Puis lors d"une inclusion ou configuration comme celle ci, je les perds.

**Comment by tcharp38** [comment]
Merde.
Bon pour info de ce à quoi je pense.

Le "changeVal" est pour moi (d'apres la spec) optionnel. Donc si on donne rien dans le model on transmet rien.
Ce qui fonctionne pour la plupart des cas.
Peut etre que la... tu as besoin d'une valeur. Donc il faut l'ajouter au modele.

Tu as compris quel configureReporting foutait la merde ?
Il y en a 3 dnas le modele actuelle: 0006-0000, 0B04-0508, & 0B04-050B

**Comment by KiwiHC16** [comment]
Je viens de la perdre sur le dernier: 0B04-050B apres avoir fait les deux autres.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-27 à 16 47 50](https://github.com/KiwiHC16/Abeille/assets/8549674/a6023455-85c8-4b17-8ec3-94e3d57f6d9d)

Elle vient de le balancer un volume de report !!!

**Comment by KiwiHC16** [comment]
```
"params": "clustId=0B04&attrType=21&attrId=0508&minInterval=0000&maxInterval=0000&changeVal="
```

Une piste les min et max sont à 0000 !!!!

Elle serait dans une boucle infinie. J essaye de lui balancer un reset Usine.

J a ajouté un autre prise qui prend les messages en routeur mais ne parvient pas à les livrer à la prise en défaut.

**Comment by tcharp38** [comment]
Oui souvent le cas.
Valeur par defaut

Mais effectivement wireshark n aime pas si changeVal ne vaut rien

Donc pour ce cas 0508, soit RMSCurrent, tu peux mettre 5mA => donc changeVal=5

**Comment by KiwiHC16** [comment]
![Capture d’écran 2023-11-27 à 16 54 39](https://github.com/KiwiHC16/Abeille/assets/8549674/5b76daa8-9f86-43f0-a1b5-68be981fb670)

Elle ne repond pas !!!

**Comment by tcharp38** [comment]
Tu as reconfiguré avec un changeVal ?

**Comment by tcharp38** [comment]
Pour info je pousse à l instant une modif pour "configureReporting2"
Par defaut si pas renseigné le changeVal sera mis à 0, suivant le bon format d'attribut.
Wireshark est content en tout cas

**Comment by KiwiHC16** [comment]
La prise ne repond plus à aucune commande pour l instant.

Toutes les 16s au moment ou le relai claque, elle envoie une salve de report.

Pour l instant la piste est min = max = 0 et elle boucle au point de reboot toutes les 16s.

Mon probleme est qu elle ne semble plus pouvoir accepter de commandes zigbee, car sur le sniff elle ne repond jamais.

**Comment by KiwiHC16** [comment]
Il faudrait interdire min = max et forcer un min < max par mesure de securité dans configureReporting2

**Comment by KiwiHC16** [comment]
La zigate et la prise font des routes requets mais aucunes des deux ne repond à l autre .... !!!

**Comment by tcharp38** [comment]
Pas d'accord avec l'idée de mettre une verue dans le code, qui ne suive pas la spec.
A faire par module si besoin mais ca n'a jamais été mis en evidence.

Et tu mettrais quoi ?

**Comment by KiwiHC16** [comment]
> Pas d'accord avec l'idée de mettre une verue

Quelle verue ?

**Comment by tcharp38** [comment]
Haaaaaa

min=0000 max=0000 c'est acceptable des lors que tu as un changeVal
Suis con mais comme ca oui ca fait du sens.
J'imagine que wireshark n aurait rien dit si min ou max etaient non nuls

Donc la derniere correction qui met le changeVal à 0 doit regler ce cas

**Comment by tcharp38** [comment]
> > Pas d'accord avec l'idée de mettre une verue
> 
> Quelle verue ?

Forcer un max > min..
Si dans le code c'est une verrue

**Comment by KiwiHC16** [comment]
En fait il faut avoir un max > 0, c est le plus important, sinon ca veut dire que le FW doit faire un report en premanance, immédiatement, des infos. Et min par definition doit être <= max. Pour moi ce n est pas une verrue c est verification de base, une verification de consistences des informations utilisateur.

min: le FW ne doit pas faire de rapport plus souvent que toutes les min secondes pour ne pas saturer le reseau.
max:  le FW doit faire un rapport ou moins toutes les max secondes pour avoir une information pas trop vieille.

**Comment by KiwiHC16** [comment]
> Donc la derniere correction qui met le changeVal à 0 doit regler ce cas

Ca n a pas de sens. changeVal doit être au minimum de 1. C est le critere pour provoquer la generation d un rapport. Sur un binaire il faut au moins 1 d'écart, mais 1 sur une mesure de puissance qui fluctue tout le temps il var rapporter tout le temps. Donc par exemple uniquement sur 10 W de variation.

**Comment by KiwiHC16** [comment]
Pour wireshark, je confirme qu il ne decode pas le valChange. Je me souviens de cette observation il y a qq années. J ai bien les valeurs dans les raws data de wireshark mais pas dans le décodage.

**Comment by KiwiHC16** [comment]
Test avec prise OSRAM: Min = 10 et Max = 30

Sans rien faire, report toutes les 30s (d apres wireshark 27s.):
![Capture d’écran 2023-11-27 à 17 53 20](https://github.com/KiwiHC16/Abeille/assets/8549674/fdfaeccb-5527-4162-b806-af28cb9b6823)

Et si On/off tout le temps sur le bouton lateral de la prise (bouton physique) toutes les 10s (Wireshark dit 10s):
![Capture d’écran 2023-11-27 à 17 55 39](https://github.com/KiwiHC16/Abeille/assets/8549674/7bfda012-9a52-4eac-91a8-95c7440b56f6)

Ca fonctionne bien comme prévu.

- Donc max à 0 n a pas de sens avec le risque de tomber dans un bug FW de l eq. 
- Min doit être inferieur à max.
- Val doit être != 0.

Pour moi ces verifications doivent être dans le code. ( C est pas de verrue, c est des verifications de bon parametres).

Je pense que si nous ne faisons pas ces tests on prend le risque d envoyer des valeurs illogiques au FW et tomber sur des cas non testés et planter les eq comme mes prises.

A moins qu ils soient indqué que la valeur 0 desactive la fonction report associé à : min, max ou val.

Est-ce que la norme dit quelque chose sur les valeurs acceptables ?

**Comment by KiwiHC16** [comment]
Test avec prise OSRAM: Min = 0 et Max = 0 et val = 1 => rien de remonte si aucune activité. Et remonet sur chaque appuie sur bouton physique .

Ce qui voudrait dire que la valeur 0 desactive la fonction report associé à : min, max

Donc mes plantages de prise sont autre-chose que je ne trouverai jamais donc elle vont finir à la poubelle et il me faut trouver des prises qui fonctionnent correctement ;-(

**Comment by tcharp38** [comment]
Ok je résume ma compréhension du moment et ce qui devrait etre pour un "configureReporting" correct

- min=0000, max=0000 => changeVal obligatoire >= 1. On met 1 par defaut et non pas 0 et erreur si 0 dans ce cas ou voir dernier cas
  note: 0000=no limit
- min=max=0000 fait toujours du sens SI ET SEULEMENT SI changeVal défini donc >= 1
- min=xxxx => retour d'erreur si max < min. changeVal n'est plus obligatoire
- d'apres la spec on peut quand meme faire un configureReport.. sans AUCUN de ces parametres
  donc je propose que si min=max=0000 on ignore ces champs donc aussi changeVal (qui si il est passé doit etre 0 sinon erreur)

Tu serais en ligne avec ca ?

**Comment by KiwiHC16** [comment]
Je vais essayer de trouver les doc zigbee sur le sujet pour etre sure de suivre leur recommandations. Je reviens vers toi quand je trouve quelque chose. Je propose de ne rien changer pour l instant.

Sinon pour mes prises, je vais prendre les bonnes vieilles Xiaomi plug EU qui font le boulot à priori, elles sont en 10A et pas 16A mais c est quffisent dans la grande majorité des cas. Pour Tuya c est poubelle pour moi.

**Comment by KiwiHC16** [comment]
```
2.4.7.1.2   Direction Field
The direction field specifies whether values of the attribute are be reported, or whether reports of the attribute are to be received. 

If this value is set to 0x00, then the attribute data type field, the minimum reporting interval field, the maximum reporting interval field and the reportable change field are included in the payload, and the timeout period field is omitted. 

The record is sent to a cluster server (or client) to configure how it sends reports to a client (or server) of the same cluster.

 If this value is set to 0x01, then the timeout period field is included in the payload, and the attribute data type field, the minimum reporting interval field, the maximum reporting interval field and the reportable change field are omitted. The record is sent to a cluster client (or server) to configure how it should expect reports from a server (or client) of the same cluster. All other values of this field are reserved
```

Dans notre cas: Direction Field = 00, il faut min, max, valchange et pas timeout
Si Direction Field = 01, seulement TimeOut

**Comment by KiwiHC16** [comment]
```
2.4.7.1.5   Minimum Reporting Interval Field
The minimum reporting interval field is 16-bits in length and shall contain the minimum interval, in seconds, between issuing reports of the specified attribute. If this value is set to 0x0000, then there is no minimum limit, unless one is imposed by the specification of the cluster using this reporting mechanism or by the applicable profile.
```

Min: 2 octets , en secondes Si 0000 pas de min.

**Comment by KiwiHC16** [comment]
```
2.4.7.1.6   Maximum Reporting Interval Field The maximum reporting interval field is 16-bits in length and shall contain the maximum interval, in seconds, between issuing reports of the specified attribute. If this value is set to 0xffff, then the device shall not issue reports for the specified attribute, and the configuration information for that attribute need not be maintained. (Note:- in an implementation using dynamic memory allocation, the memory space for that information may then be reclaimed). 
```

= Temps Max entre deux rapports

Max: 2 octets en secondes si 0xFFFF pas de rapport et l'équipement peut oublier la configuration.

**Comment by KiwiHC16** [comment]
```
2.4.7.1.7   Reportable Change Field The reportable change field shall contain the minimum change to the attribute that will result in a report being issued. This field is of variable length. For attributes with 'analog' data type (see Table 2.15) the field has the same data type as the attribute. The sign (if any) of the reportable change field is ignored. For attributes of 'discrete' data type (see Table 2.15) this field is omitted
```

Changement minimum sur la mesure qui provoque un rapport. La taille depend du type de parametre mais pas clair.

**Comment by KiwiHC16** [comment]
Donc pour moi Max ne peut pas être à zéro et j ai des gros doute sur le fait que cela ne soit pas la raison des briques de mes prises.

**Comment by tcharp38** [comment]
Ok bien vu le chapitre "direction".

Mais toujours pas d'accord avec toi sur le fait que "max=0000" n'est pas possible.
La preuve "If this value is set to 0x0000, and the minimum reporting interval field does not equal 0xffff there SHALL
2707 be no periodic reporting, but change based reporting SHALL still be operational."

J'en suis la d'apres tes dernieres pistes:

    Client to server (dir=00)
    - dataType obligatoire
    - min obligatoire (peut etre 0=no limit)
    - max obligatoire (peut etre 0, 0xffff to disable reporting)
    - changeVal obligatoire
    - timeout optionnel
    Server to client (dir=01)
    - timeout obligatoire

**Comment by KiwiHC16** [comment]
a

**Comment by tcharp38** [comment]
Ha no commentaires se sont croisés. 
Donc ma proposition précédente est à ignorer.
Pour moi le résumer qui tient compte de tes pistes est le suivant

    Client to server (dir=00)
    - dataType obligatoire
    - min obligatoire (peut etre 0=no limit)
    - max obligatoire (peut etre 0, 0xffff to disable reporting) => si max < min = erreur
    - changeVal obligatoire
    - timeout optionnel
    Server to client (dir=01)
    - timeout obligatoire

**Comment by KiwiHC16** [comment]
Dans le cas
Client to server (dir=00)
le timeout n'est pas optionnel, il ne doit pas y etre.

```
period field is omitted
```

**Comment by KiwiHC16** [comment]
```
- max obligatoire (peut etre 0, 0xffff to disable reporting)
```

Que veut dire en pratique 0 ? Dans la norme, je ne vois rien qui exclu 0 ou indique d utiliser 0.

Comment le FW de l equipement peut gérer 0 ?

Ca veut dire qu'entre deux rapports il doit s'écouler 0 secondes, en theorie impossible (tous les rapport en meme temps), en pratique ca donne un CPU qui ne fait que des rapports et une radio qui s'atture complètement et l eq qui "brique". Dans mon cas la prise balance des salves de report et reboot. Soit le FW gere cette valeur 0, soit le FW doit être en peine pour gérer la situation. Peut être que je me trompe mais c est ma comprehension.

**Comment by tcharp38** [comment]
Je pense au cas min=0 max=0 parce que la seule chose importante c'est changeVal.

En tout cas c'est bien precisé plusieurs cas précis mais aucun n'enleve cette option

Non ?

**Comment by tcharp38** [comment]
Proposition corrigée

    Client to server (dir=00)
    * dataType obligatoire
    * min obligatoire
      - 0000=no limit
    * max obligatoire
      - Peut etre 0000 (donc min=0000 aussi pour aucune fenetre de temps mais juste changeVal)
      - 0xffff to disable reporting
      - max=0000 & min=xffff => revert to default reporting
      - si max < min => erreur
    * changeVal obligatoire
    Server to client (dir=01)
    * timeout obligatoire

Je ferai des essais demain sur cette base, pour comment reagit Wireshark.

C'est mieux ?

**Comment by KiwiHC16** [comment]
Avant de conclure, je voudrais configurer changeVal, faire des tests mais je ne comprends pas la valeur à envoyer.

En interrrogeant une ampoule Ikea, elle repond:
 
![Capture d’écran 2023-11-27 à 22 27 22](https://github.com/KiwiHC16/Abeille/assets/8549674/ccfe5203-c746-453c-9c0e-e3b01af3af2f)

Y a pas de changeVal. Je ne sais pas si c est normal ou si elle renvoie la conf qu'Abeille lui a donné lors de l inclusion.

**Comment by KiwiHC16** [comment]
> Proposition corrigée
> 
> ```
> Client to server (dir=00)
> * dataType obligatoire
> * min obligatoire
>   - 0000=no limit
> * max obligatoire
>   - Peut etre 0000 (donc min=0000 aussi pour aucune fenetre de temps mais juste changeVal)
>   - 0xffff to disable reporting
>   - max=0000 & min=xffff => revert to default reporting
>   - si max < min => erreur
> * changeVal obligatoire
> Server to client (dir=01)
> * timeout obligatoire
> ```
> 
> Je ferai des essais demain sur cette base, pour comment reagit Wireshark.
> 
> C'est mieux ?

min=xffff n existe pas dans la norme pour set. Pour get, si l equipement repond 0xffff ca veut dire que la valeur n est pas définie.

**Comment by tcharp38** [comment]
La valeur a envoyer depend du type d'attribut visé.
Mais comme toi je ne me souviens pas d'un retour d'un equipement avec le "reportable change".

Pourquoi tu dis que min=xffff est interdit ? Tu vois ca ou ?
En fait.. non il n'est pas interdit.. il y a le cas max=0000 min=FFFFF

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/656d5cee-4a00-43c7-b1a2-5b7b12679c77)

**Comment by KiwiHC16** [comment]
Exemple dans le Chapitre 2.1.2 de la page https://ww1.microchip.com/downloads/en/Appnotes/Atmel-42334-ZigBee-Attribute-Reporting_ApplicationNote_AT08550.pdf

**Comment by KiwiHC16** [comment]
> La valeur a envoyer depend du type d'attribut visé. Mais comme toi je ne me souviens pas d'un retour d'un equipement avec le "reportable change".
> 
> Pourquoi tu dis que min=xffff est interdit ? Tu vois ca ou ? En fait.. non il n'est pas interdit.. il y a le cas max=0000 min=FFFFF
> 
> ![image](https://private-user-images.githubusercontent.com/35221038/286028731-656d5cee-4a00-43c7-b1a2-5b7b12679c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjE1NzAsIm5iZiI6MTcwMTEyMTI3MCwicGF0aCI6Ii8zNTIyMTAzOC8yODYwMjg3MzEtNjU2ZDVjZWUtNGEwMC00M2M3LWIxYTItNWI3YjEyNjc5Yzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDIxNDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMGQ4MTZkNzIyZWQxOTZlZGJjZTRmMzE1YWNhMzY1MWMyY2Q0ODQ2OTcyYThkMzNmOTI2M2Y4MWU4MmFhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUT99mA5XuPmKMtqYutJlQVagm1SlUJvxehCpm-2UtI)

On ne doit pas avoir la meme version de la doc car ma doc ne parle pas de min = 0xFFFF.

D ou nos differences de comprehension.

**Comment by tcharp38** [comment]
[Zigbee_cluster_lib-r08.pdf](https://github.com/KiwiHC16/Abeille/files/13480688/Zigbee_cluster_lib-r08.pdf)
C'est la plus recente que j'ai trouvé

**Comment by KiwiHC16** [comment]
> La valeur a envoyer depend du type d'attribut visé.

Donc si c est un binaire (etat d une ampoule par exemple), on envoie un octet ? Donc forcement 01 ?

DataType Boolean est 0x10 et utilise 1 octet. Donc on doit ajouter à la fin 0x01 pour changeVal (d apres chapitre 2.6.2.2).

Sur un setReport sans le changeVal, wireshark est ok.

Sur un setReport du Level d une ampoule sans changeVal, wireshark n est pas ok.

 
![Capture d’écran 2023-11-27 à 23 29 42](https://github.com/KiwiHC16/Abeille/assets/8549674/97ff3234-bf99-415c-833b-3c0446fcb3c2)

si je mets 05 pour changeVal alors WireShark est ok.

![Capture d’écran 2023-11-27 à 23 43 16](https://github.com/KiwiHC16/Abeille/assets/8549674/b0f2120a-8fa5-4487-ab91-650d7a5860b5)

Il semble que pour le Boolean le changeVal n est pas necessaire pour Wireshark par contre pour un type 0x20 (Unsigned Integer) il faut le chageVal.

**Comment by KiwiHC16** [comment]
| Sujet |Ta Version|Ma version|
|---|---|----|
| Doc| 075123 | 075123 r02Z |
|Date| December 2019 | May 29, 2008 |

Dix ans d écart.

**Comment by tcharp38** [comment]
> > La valeur a envoyer depend du type d'attribut visé.
> 
> Donc si c est un binaire (etat d une ampoule par exemple), on envoie un octet ? Donc forcement 01 ?

Oui
Ca doit faire la taille exacte correspondante au type d'attribut.

**Comment by tcharp38** [comment]
Ta doc est interessante mais certains cas me semblent contradictoires avec la spec officielle Zigbee.
Je vais creuser mais ca ne peut etre la reference.

**Comment by KiwiHC16** [comment]
Avec une ampoule Ikea existante:

![Capture d’écran 2023-11-27 à 23 58 37](https://github.com/KiwiHC16/Abeille/assets/8549674/8d99e8ea-6e48-4d0f-8aa6-0795002b2d6c)

Conf report avec changeVal à 5:

![Capture d’écran 2023-11-27 à 23 59 38](https://github.com/KiwiHC16/Abeille/assets/8549674/16e6ff18-535c-4e3f-853d-364226573318)

Interrogation de nouveau:
![Capture d’écran 2023-11-28 à 00 00 48](https://github.com/KiwiHC16/Abeille/assets/8549674/04071004-58da-4203-9bfc-87e338c9d1bb)

**Comment by KiwiHC16** [comment]
Test avec param sur cette meme ampoule: min=1 max=FFFE val=5

![Capture d’écran 2023-11-28 à 00 03 31](https://github.com/KiwiHC16/Abeille/assets/8549674/a09f8f91-ed39-430c-abbb-5cdbf9daab32)


Lecture conf:
![Capture d’écran 2023-11-28 à 00 07 20](https://github.com/KiwiHC16/Abeille/assets/8549674/0c49f05a-da9a-4e00-860b-420a00fe9fd9)

**Comment by tcharp38** [comment]
Jusque la il y a qqch qui dise le contraire du dernier résumé que j'ai fait ?

**Comment by tcharp38** [comment]
Apres qq essais, j'ai poussé des modifs dans le master en ligne avec le résumé suivant.
Jusque la c'est ok pour moi et Wireshark est content. 
A noter que dans le cas de data types "discrete", le changeVal ne DOIT PAS etre transmis. Du coup c'est normal que ni le configure reporting ni la reponse ne montrent un changeVal pour un boolean (type 10) par ex.

    The receiver reports (dir=00)
    * dataType obligatoire
    * min obligatoire
      - 0000=no min limit
    * max obligatoire
      - max=0xffff => disable reporting
      - max=0000 & min!=FFFF => no periodic reporting but changeVal based only => changeVal > 0
      - max=0000 & min=FFFF => revert to default reporting
      - sinon si max < min => erreur
    * changeVal obligatoire SEULEMENT si attrType n'est pas "discrete"
    
    The sender reports (dir=01)
    * timeout obligatoire

Dans ce cadre, et de maniere a ne pas devoir modifier tous les modeles, le code mets les valeurs par defaut suivantes
- min = 0
- max = 0
- changeVal = 1

**Comment by KiwiHC16** [comment]
Ok super.
Je viens de finaliser la migration de mes zigates et abeille associé. Je vais mettre en prod le dernier master dans ce cas.
Je clos.
