### ISSUE TITLE
Intégration nouveau model vanne Danfoss Ally eTRV0103 (id = eTRV0103, Danfoss)

### ISSUE THREAD

**Issue by jbromain** [KiwiHC16/Abeille#2662]
Bonjour,

j'ai installé une nouvelle vanne thermostatique Danfoss qui s'identifie sous le modèle 'eTRV0103'.
C'est exactement la même que le modèle 'eTRV0100' qui est déjà connu d'Abeille (mêmes références sur la boîte), et elle fonctionne en forçant le modèle sur eTRV0100.

Pour supporter officiellement ce modèle, est-ce qu'on doit obligatoirement duppliquer le fichier json, ou bien est-ce qu'il y a un système d'alias de modèle ?

(Quelle que soit la réponse, je peux m'en chercher et faire une PR, dis-moi juste ;))

**Comment by tcharp38** [comment]
Salut
Non pas besoin de dupliquer un modele quand les fonctionalités sont identiques.
J'avais introduit un champ qui s'appelle "alternateIds".
Tu me files le discovery ?

**Comment by jbromain** [comment]
Et voilà !
[discovery-eTRV0103_Danfoss.json](https://github.com/KiwiHC16/Abeille/files/13441961/discovery-eTRV0103_Danfoss.json)

Miraculeusement ça a presque tout rapatrié alors que c'est un équipement sur piles.

**Comment by tcharp38** [comment]
Presque ?
Pour tout avoir il faut relancer en reveillant la vanne. Ex en changeant la temp
Ceci etant je crois me souvenir que ce type de vanne est toujours en ecoute
du coup quand tu dis presque, que reste t'il qui n'est pas passé au vert ?

**Comment by tcharp38** [comment]
Tiens, ecrase ce modele, redemarre Abeille, et retente une inclusion
[eTRV0100.json](https://github.com/KiwiHC16/Abeille/files/13448378/eTRV0100.json)

Ce modele merite qu'on le revisite.
Tu pourra m'envoyer un snapshot du dashboard ?

**Comment by jbromain** [comment]
Je vais pas pouvoir faire le test tout de suite, la vanne est installée trop loin pour que je puisse faire une inclusion (j'ai pas mal galéré, il faut être à quelques centimètres pour que ça fonctionne, même si après elle a une excellente portée).

J'en reçois une nouvelle normalement d'ici 2 jours, je testerai (en espérant que ce soit aussi une eTRV0103 ce qu'on ne sait pas à l'avance).

(Le "Presque", il manquait une seule petite case, je ne sais plus laquelle, même en insistant ça se remplissait pas; je te referai un discovery avec la nouvelle, avant de l'installer).

**Comment by tcharp38** [comment]
Ok fais signe.
Pour le discovery ca peut arriver que ca reste orange. Certains devices ne prennent meme pas la peine de repondre "je supporte pas ce truc" .. ils ne repondent juste pas.

**Comment by jbromain** [comment]
Hello,

J'ai reçu la nouvelle vanne, et c'est bien une 103. Je te confirme qu'elle s'inclut parfaitement avec le nouveau JSON.

Voici pour info l'affichage avant toute modification:
![image](https://github.com/KiwiHC16/Abeille/assets/72972682/e6fb530c-f11f-45d1-8c47-a1c135bdc8ea)

(Avis personnel: je trouve que le slider de température est inutilisable, on ne peut pas être précis, surtout sur smartphone; si possible, je pense que ce serait mieux d'avoir quelques boutons prédéfinis pour définir la consigne. De mon coté je retire aussi l'affichage du mode / keylock / display mode, et ajouté celui du % d'ouverture qui m'intéresse plus.)

Et voici une capture du discovery:
![image](https://github.com/KiwiHC16/Abeille/assets/72972682/836b62fa-a977-47fd-b96f-f4c392e27539)

Voici le discovery pour info, mais c'est déjà ce truc-là qui restait orange la dernière fois, le fichier est donc sûrement identique:
[discovery-eTRV0103_Danfoss (1).json](https://github.com/KiwiHC16/Abeille/files/13464921/discovery-eTRV0103_Danfoss.1.json)

Donc sujet clos pour l'intégration de ce modèle :)
Merci !

**Comment by tcharp38** [comment]
Si tu veux bien on ne cloture pas tout de suite.
Ce modele est tres vieux et a besoin de menage
et tout à fait d'accord avec toi.. un slider pour la temperature c'est un peu nase donc à creuser.

Ha coté discovery.. le cluster 0204 peut etre qqch a creuser.
Peux tu refaire un discovery et quand tu as un refresh du 0204 tu me files le package de logs.. je veux voir ce qu'il se passe dans ce cas.

Au passage qu'elle est la ref fabricant de ce TRV0103 ?

Bref t'as encore du taf :)

**Comment by tcharp38** [comment]
Peux tu refaire une inclusion avec ce modele ?
J'ai ajouté 2 boutons + et - pour test
et j'ai besoin du package de logs STP
[eTRV0100.zip](https://github.com/KiwiHC16/Abeille/files/13464996/eTRV0100.zip)

Merci

**Comment by jbromain** [comment]
J'ai réinclus avec le nouveau JSON. Les boutons Plus et Minus ont un comportement bizarre: parfois ça ajoute 0.5° à la consigne, parfois 1°, parfois 2°.

Vers 12h11, j'étais à 19. 
Premier clic sur Plus: passé à 19.5
Deuxième clic sur Plus: passé à 21.5
(J'ai à chaque fois attendu que la consigne remonte)

(J'ai eu un comportement similaire avec le bouton Minus mais j'avais oublié de mettre les logs en débug donc j'ai recommencé ensuite)

Discovery lancé à 12h14.
Clic sur Découverte étendue des attributs sur 0204 à 12h15:30'
Clic sur Découverte (normale) des attributs sur 0204 à 12h15:45'

Voici le package de logs:
[AbeilleLogs-231126.tar.gz](https://github.com/KiwiHC16/Abeille/files/13466614/AbeilleLogs-231126.tar.gz)

La tête Danfoss Ally Zigbee est vendue sous au moins deux références: "014g2420" et "014g2460". C'est exactement le même produit, mais le packaging est différent et les accessoires (adaptateurs pour radiateur) ne sont pas les mêmes.

**Comment by tcharp38** [comment]
Alors si tu regarde les evenements je vois bien 2 fois une augmentation de 0.5degres puis encore une qui fait passer à 20.5.

    [2023-11-26 12:10:32][INFO] : Exécution de la commande [Salon][Radiateur salon][Plus] avec les paramètres {"user_login":"admin","user_id":"1"}
    [2023-11-26 12:10:46][INFO] : Evènement sur la commande [Salon][Radiateur salon][Consigne] valeur : 19.5°C
    
    [2023-11-26 12:10:49][INFO] : Exécution de la commande [Salon][Radiateur salon][Plus] avec les paramètres {"user_login":"admin","user_id":"1"}
    [2023-11-26 12:10:54][INFO] : Evènement sur la commande [Salon][Radiateur salon][Consigne] valeur : 20°C
    
    [2023-11-26 12:10:54][INFO] : Evènement sur la commande [Salon][Radiateur salon][Consigne] valeur : 20.5°C
    [2023-11-26 12:10:55][INFO] : Evènement sur la commande [Salon][Radiateur salon][Consigne] valeur : 21°C
    [2023-11-26 12:10:55][INFO] : Evènement sur la commande [Salon][Radiateur salon][Consigne] valeur : 21.5°C

**Comment by jbromain** [comment]
On dirait que la commande a été exécutée plusieurs fois par la vanne alors. On voit bien qu'elle augmente 3 fois de plus de 0.5° en moins de 2 secondes.

**Comment by tcharp38** [comment]
J'étais en train de creuser et je vois bien 3 reports consécutifs... sans aucune intervention d'Abeille

    [2023-11-26 12:10:54] Abeille2, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0201, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=910A, DstAddrMode=02, DstAddr=0000
    [2023-11-26 12:10:54]   FCF=08/General/Serv->Cli, SQN=7F, cmd=0A/Report attributes
    [2023-11-26 12:10:54]   AttrId=0012/OccupiedHeatingSetpoint, AttrType=29, ValueHex=07D0 => 2000
    [2023-11-26 12:10:54]   AttrId=0030/Unknown-0201-0030, AttrType=30, ValueHex=02 => 2
    [2023-11-26 12:10:54] Abeille2, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0201, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=910A, DstAddrMode=02, DstAddr=0000
    [2023-11-26 12:10:54]   FCF=08/General/Serv->Cli, SQN=00, cmd=0A/Report attributes
    [2023-11-26 12:10:54]   AttrId=0012/OccupiedHeatingSetpoint, AttrType=29, ValueHex=0802 => 2050
    [2023-11-26 12:10:54] Abeille2, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0201, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=910A, DstAddrMode=02, DstAddr=0000
    [2023-11-26 12:10:54]   FCF=08/General/Serv->Cli, SQN=01, cmd=0A/Report attributes
    [2023-11-26 12:10:54]   AttrId=0012/OccupiedHeatingSetpoint, AttrType=29, ValueHex=0834 => 2100

J'avoue que je ne comprends pas du tout

**Comment by jbromain** [comment]
Bug de la vanne ou bug Zigate ou "bug du réseau" ?

J'ai plein de routeurs chez moi, est-il possible que plusieurs routeurs aient relayé la commande, et qu'elle se retrouve exécutée plusieurs fois par la vanne ? J'imagine qu'il y a dans la trame zigbee un numéro de séquence qui permet d'éviter ça coté équipement, mais si la vanne est buguée...

**Comment by tcharp38** [comment]
Je soupconne un bug du FW de la vanne.
Donc mauvaise piste pourtant ce cluster est fait pour ça... mais comme d'hab le FW Tuya est souvent d'une qualité de daube.
Il faut que l'enleve ca du modele pour pas pourrir ce qui fonctionne déja.

Et du coup trouver une autre solution qu'un "slider"

**Comment by jbromain** [comment]
Je ne connaissais pas l'existence des commandes Plus/Moins, dans la tête j'imaginais quelques boutons qui fixent des températures courantes (un bouton 18, 19, 20, 21 par exemple). Ca correspondrait à mon usage, mais je ne sais pas si c'est une bonne idée ou pas.

**Comment by tcharp38** [comment]
C'est une idée mais pas satisfaisante pour moi.
Le + simple pour tout le monde face à un thermostat, c'est un +/- et la valeur de la consigne ainsi que la temperature actuelle.

En regardant chez zigbee-herdsman-converters, j'ai l'impression que ca existe mais sur un cluster privé.
Pas surprenant de la part de Tuya... jamais standard

Pour mémo

    danfoss_thermostat_occupied_heating_setpoint: {
        key: ['occupied_heating_setpoint'],
        convertSet: async (entity, key, value, meta) => {
            utils.assertNumber(value, key);
            const payload = {
                // 1: "User Interaction" Changes occupied heating setpoint and triggers an aggressive reaction
                //   of the actuator as soon as control SW runs, to replicate the behavior of turning the dial on the eTRV.
                setpointType: 1,
                setpoint: Number((Math.round(Number((value * 2).toFixed(1))) / 2).toFixed(1)) * 100,
            };
            await entity.command('hvacThermostat', 'danfossSetpointCommand', payload, manufacturerOptions.danfoss);
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('hvacThermostat', ['occupiedHeatingSetpoint']);
        },
    } satisfies Tz.Converter,


    hvacThermostat: {
        ID: 513, => 0x201

            danfossSetpointCommand: {
                ID: 64,
                parameters: [
                    {name: 'setpointType', type: DataType.enum8},
                    {name: 'setpoint', type: DataType.int16},
                ],
            },

**Comment by jbromain** [comment]
Hello,

Dans le bout de code que tu as posté, ce commentaire m'intéresse grandement; si tu arrives à comprendre comment ils ont pu faire ça, ce serait top:
```
 // 1: "User Interaction" Changes occupied heating setpoint and triggers an aggressive reaction
 //   of the actuator as soon as control SW runs, to replicate the behavior of turning the dial on the eTRV.
```

Car j'ai un problème récurrent avec ces vannes, pas systématique mais assez pénible: quand j'envoie une consigne via la domotique, la consigne est prise en compte (l'attribut correspondant à la consigne se met à jour, et l'afficheur de la vanne affiche bien la nouvelle consigne). 

Mais, réellement, la vanne réagit avec un délai parfois très long (une demi-heure ou une heure). Lorsqu'on manipule la vanne physiquement, la réaction est toujours immédiate. A lire le commentaire dans leur code, on dirait qu'ils ont compris et géré ce comportement.

**Comment by tcharp38** [comment]
Jusque la j'ai juste l'mpression qu'il faut écrire via un attribut different que celui du standard zigbee pour le cluster 0201.
Bref Tuya.. comme a son habitude, semble faire encore hors spec.
Je n'ai pas encore compris comment interpreter ces lignes de code mais j'ai des modifs en cours pour faire qqch de similaire pour raise/lower.

**Comment by jbromain** [comment]
Comment tu sais que c'est Tuya au fait ? Sur la boîte Tuya n'est pas mentionné. Juste "Zigbee Certified".

**Comment by tcharp38** [comment]
Tu as tout à fait raison. Je m'embrouille les pinceaux.
Ca n'est pas Tuya mais ca semble particulier à Danfoss quand même avec une commande spéciale.

Dans le cluster 0x0201 il n'y a pas de commande 0x40 (64)

    hvacThermostat: {
        ID: 513, => 0x201
    
            danfossSetpointCommand: {
                ID: 64,
                parameters: [
                    {name: 'setpointType', type: DataType.enum8},
                    {name: 'setpoint', type: DataType.int16},
                ],
            },

**Comment by tcharp38** [comment]
Tiens via la page EQ/avancé.. j'avais ajouté une commande tout à bas

Peux tu tester ça et voir si ca a un effet ?
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/45859ef0-35dc-47a5-8871-1e0ca640c20e)

**Comment by jbromain** [comment]
Si je comprend bien je pourrais éventuellement lancer la commande ici ?
![image](https://github.com/KiwiHC16/Abeille/assets/72972682/8e8fd8e6-45ab-432f-8de4-37c5ec3918e2)

Pour faire des tests avec les valeurs que tu me donnes. C'est plus rapide que faire un json et réinclure, si on tatonne.

**Comment by jbromain** [comment]
Rien de perceptible; C'était censé mettre la consigne à combien ?

```
0030|[2023-11-30 15:03:32] Msg from 'xToCmd': {"topic":"CmdAbeille1\/43D5\/cmd-Generic","payload":"ep=01&clustId=0201&cmd=40&data=0107D0"}
0032|[2023-11-30 15:03:32]   processCmd({"cmd-Generic":"cmd-Generic","name":"cmd-Generic","priority":4,"dest":"Abeille1","ep":"01","clustId":"0201","cmd":"40","data":"0107D0","addr":"43D5"})
0035|[2023-11-30 15:03:32]     addCmdToQueue2(Pri=4, Net=Abeille1, ZgCmd=0530, Payload=0243D5010102010104021E0611EC400107D0, Addr=43D5, AddrMode=02)
0038|[2023-11-30 15:03:32]   cmd={"dest":"Abeille1","addr":"43D5","cmd":"0530","datas":"0243D5010102010104021E0611EC400107D0","zgOnly":false,"status":"","try":4,"sentTime":0,"timeout":8,"sqn":"","sqnAps":"","ackAps":true,"waitFor":"ACK"}
0039|[2023-11-30 15:03:32]   sendCmdToZigate(Dest=Abeille1, addr=43D5, cmd=0530, datas=0243D5010102010104021E0611EC400107D0)
0053|[2023-11-30 15:03:38] processAcks(): msg={"type":"8011","net":"Abeille1","status":"A7","addr":"43D5","sqnAps":"EA"}
0054|[2023-11-30 15:03:38]   cmd={"dest":"Abeille1","addr":"43D5","cmd":"0530","datas":"0243D5010102010104021E0611EC400107D0","zgOnly":false,"status":"SENT","try":3,"sentTime":1701353012,"timeout":8,"sqn":"EA","sqnAps":"EA","ackAps":true,"waitFor":"ACK"}
0057|[2023-11-30 15:03:39] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"EB"}
0059|[2023-11-30 15:03:39] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"EC"}
0061|[2023-11-30 15:03:39] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"ED"}
0063|[2023-11-30 15:03:39] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"EE"}
```

Mes logs sont extrêmement pollués mais la commande est partie. Je peux voir une réponse éventuelle dans les logs ?

**Comment by tcharp38** [comment]
Tu es sur le master ?
Je m'attendais a voir la ligne

    cmdLog('debug', "  genericCmd: ep=${dstEp}, clustId=${clustId}, zclHeader=${zclHeader}, data=${data}");

07D0 = 20deg * 100

**Comment by jbromain** [comment]
Je suis la bêta (peut-être pas la toute dernière mais pas loin).
J'ai changé pour 21 (0834) vu que la consigne était déjà à 20, ça ne fonctionne pas.
Que signifie que '01' du début ?

**Comment by tcharp38** [comment]
Aucune idée pour le 01. J'essaie d'interpreter le code zigbee-herdsman
Mais je pense qu'il manque le manufCode et mon interface ne permet pas.
Je vais corriger ca mais pas sur d'avoir le temps d'ici ce soir

En gros il faudrait ajouter une commande dans ton json du style

            "SetTest": {
                "use": "act_zbCmdC-Generic",
                "params": "ep=01&clustId=0201&cmd=40&manufCode=1246&data=0107D0"
            },

**Comment by tcharp38** [comment]
Correction dans le master

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/7767c8e9-7cca-405a-82da-95278ff152b5)

**Comment by jbromain** [comment]
Je comprend rien, j'ai ajouté la commande SetTest dans le json, redémarré (2 fois) et ré-initialisé la vanne (2 fois), la commande n'apparaît pas dans la liste.

**Comment by jbromain** [comment]
Oublie le message précédent, je modifiais pas le bon fichier. J'ai bien la commande test mais elle est toujours sans effet même avec le manufcode.

**Comment by tcharp38** [comment]
Je réalise que la cmd est no ack... Ton device ne l'a pas reçue donc normal de pas avoir d effet

Status 8011 a7 et non pas 00

**Comment by jbromain** [comment]
J'aimerais bien comprendre tout ça, un jour. D'une manière générale si je vois un processAcks avec un statut autre que 00 c'est non reçu ? Dans ce cas, qui envoie cette information ?

(J'ai des problèmes de routage qui dépassent largement le cas des vannes, je m'arrache les cheveux depuis des semaines)

**Comment by tcharp38** [comment]
Un 8011 est un resultat important, status 00=ok
Mais status A7=no ack.. Donc répond pas

En gros on essaie d'envoyer des commandes en demandant un acquittement du device pour plus de contrôle

**Comment by jbromain** [comment]
J'ai relancé, j'ai bien le status 00, mais pas plus d'effet.
Mais pas sûr que les logs soient cohérents, je ne vois pas le numéro de séquence lors de l'envoi de la commande (uniquement dans l'accusé). Et il y a deux accusés avec des numéro de séquences différents.

```
1125|[2023-11-30 16:30:46] -- execute(): Msg sent: {"topic":"CmdAbeille1\/43D5\/cmd-Generic","payload":"ep=01&clustId=0201&data=0107D0&cmd=40&manufCode=1246"}
1126|[2023-11-30 16:30:46] Msg from 'xToCmd': {"topic":"CmdAbeille1\/43D5\/cmd-Generic","payload":"ep=01&clustId=0201&data=0107D0&cmd=40&manufCode=1246"}
1128|[2023-11-30 16:30:46]   processCmd({"cmd-Generic":"cmd-Generic","name":"cmd-Generic","priority":4,"dest":"Abeille1","ep":"01","clustId":"0201","data":"0107D0","cmd":"40","manufCode":"1246","addr":"43D5"})
1131|[2023-11-30 16:30:46]     addCmdToQueue2(Pri=4, Net=Abeille1, ZgCmd=0530, Payload=0243D5010102010104021E0815461205400107D0, Addr=43D5, AddrMode=02)
1134|[2023-11-30 16:30:46]   cmd={"dest":"Abeille1","addr":"43D5","cmd":"0530","datas":"0243D5010102010104021E0815461205400107D0","zgOnly":false,"status":"","try":4,"sentTime":0,"timeout":8,"sqn":"","sqnAps":"","ackAps":true,"waitFor":"ACK"}
1135|[2023-11-30 16:30:46]   sendCmdToZigate(Dest=Abeille1, addr=43D5, cmd=0530, datas=0243D5010102010104021E0815461205400107D0)
1137|[2023-11-30 16:30:46] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"71"}
1138|[2023-11-30 16:30:46]   cmd={"dest":"Abeille1","addr":"43D5","cmd":"0530","datas":"0243D5010102010104021E0815461205400107D0","zgOnly":false,"status":"SENT","try":3,"sentTime":1701358246,"timeout":8,"sqn":"71","sqnAps":"71","ackAps":true,"waitFor":"ACK"}
1141|[2023-11-30 16:30:47] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"43D5","sqnAps":"72"}

```

Question: j'ai l'impression que les vannes sont interrogées par polling en continu, toutes les minutes; Pourquoi ? puis-je désactiver ça pour éviter de polluer les logs (et le réseau) ?

**Comment by tcharp38** [comment]
Modele revu donc a recharger via la page equipement/avancé.
Et se mettre sur la derniere beta en attendant la prochaine stable.

**Comment by tcharp38** [comment]
Salut @jbromain 
Que fait on avec ce vieux sujet ?

**Comment by jbromain** [comment]
Hello,
On ferme, c'est parfaitement fonctionnel sur les dernières versions.
