### ISSUE TITLE
Intégration du module  double dimmer Tuya (id = TS110F, _TYZB01_v8gtiaed)

### ISSUE THREAD

**Issue by pirramail** [KiwiHC16/Abeille#2664]
Bonjour,
Je possède des modules "2 Gang Zigbee Dimmer"  modèle QS-Zigbee-D02-TRIAC-2C-LN qui ne sont pas reconnus directement à l'intégration, je n'ai pas trouvé facilement de modèles proches dans les config/devices qui fonctionneraient à la place, ni dans les différents groupes de discussion

Je me permets donc de t'envoyer la logs de découverte complete en PJ
En espérant que le module puisse être intégré dans une prochaine release

Merci par avance
[discovery-TS110F__TYZB01_v8gtiaed.json](https://github.com/KiwiHC16/Abeille/files/13466290/discovery-TS110F__TYZB01_v8gtiaed.json)

**Comment by tcharp38** [comment]
Salut @pirramail 
J'ai besoin d'une image au format PNG sans arriere plan à mettre en icone.

Voila un modele preliminaire à decompresser dans core/config/devices
puis redemarrer Abeille
et refaire une inclusion
[TS110F__TYZB01_v8gtiaed.zip](https://github.com/KiwiHC16/Abeille/files/13466402/TS110F__TYZB01_v8gtiaed.zip)

**Comment by pirramail** [comment]
Bonjour,
merci pour ton retour rapide, çà marche très bien.
ci-jointe  l'image png pour l'icone
![node_TS110F__TYZB01_v8gtiaed](https://github.com/KiwiHC16/Abeille/assets/152056860/1fc539e5-76eb-4e92-86c4-1bf4f3909c20)

**Comment by tcharp38** [comment]
Les 2 canaux fonctionnent ?
L'image sera dans la prochaine beta

**Comment by tcharp38** [comment]
Je suppose que les 2 canaux fonctionnent.
Je ferme mais à reouvrir si soucis sur ce device.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
