### ISSUE TITLE
[KiwiHC16] Integration prise Aqara Smart Plug EU : Total Power

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#2666]

**Comment by tcharp38** [comment]
Quelle est la signature de ce plug ?

**Comment by KiwiHC16** [comment]
plug.maeu01

Quand #2665 sera résolu, je regarderai ce cas.

**Comment by tcharp38** [comment]
Si l'info remonte bien du 0702 c'est surement du polling à faire.

**Comment by KiwiHC16** [comment]
Je clos celui ci car traité dans #2670
