### ISSUE TITLE
Erreur "Modèle 'rucheCommand' inconnu" lors de la ré-inclusion d'un module existant

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2668]
Hello,

J'ai certains capteurs Aqara (température et ouverture) un peu récalcitrants qui passe de temps en temps en timeout.
Je les ré-inclus donc régulièrement et depuis quelques temps, j'ai l'erreur suivante : 

`getDeviceModel(): Modèle 'rucheCommand' inconnu.`

A priori le module fonctionne malgré cette erreur.
En PJ les logs. La ré-inclusion a été faite à 15:58:25.

Si ca peut aider ;)

Jeedom : 4.3.20
Abeille : 231202-BETA-3
[AbeilleLogs-231204.tar.gz](https://github.com/KiwiHC16/Abeille/files/13547871/AbeilleLogs-231204.tar.gz)

**Comment by tcharp38** [comment]
Salut @Xav-74 
Pour l'erreur je n'arrive pas à reproduire.
Je viens de pousser une beta pour demain, avec de gros changements. Tu me dirq ce qu'il en et si tu vois des regressions.

**Comment by Xav-74** [comment]
Hello !

Dsl j'étais en déplacement ces 2 jours.
Mise à jour avec la dernière beta ce matin. Puis réinclusion à 8h29 de 2 modules Aqara (un capteur de temp) et un capteur d'ouverture.
Le message apparait encore les 2 fois

A ta dispo
 
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/13596909/Abeille.log)

**Comment by tcharp38** [comment]
Salut

Donc ce message apparait à chaque inclusion et rien à voir avec le module en cours d'inclusion
Je ne comprends pas pourquoi je n'arrive pas à reproduire ce souci mais je vais creuser.

**Comment by Xav-74** [comment]
Oui il  apparait à chaque ré-inclusion.
Après, je ne sais pas si c'est lié au module, qui semble tout de même fonctionnel

**Comment by tcharp38** [comment]
Le message n'a rien à voir avec le module mais pour l'instant je patauge.

**Comment by Xav-74** [comment]
Hello

Installation de la beta de ce matin. Réinclusion d'un module Aqara que j'avais laissé en timeout pour les tests de ce matin.
Plus de message :)

Je vais laissé ouvert qq jours pour surveillance !
Merci encore

**Comment by tcharp38** [comment]
J'aime pas ca.
Un truc non expliqué est pour moi non résolu mais bon.. a suivre.
Merci en tout cas

**Comment by Xav-74** [comment]
Je me demande si c'est pas un souci perso avec ma clé

**Comment by tcharp38** [comment]
Je clos ce sujet.
Remplacé par #2675
