### ISSUE TITLE
Multiprise Lidl HG6338-FR 10/2023 (id = TS011F, _TZ3000_vzopcetz)

### ISSUE THREAD

**Issue by balabap** [KiwiHC16/Abeille#2669]
bonjour,

je rencontre le même problème que sut le post suivant : https://github.com/KiwiHC16/Abeille/issues/2354

l'appui sur n'importe quel bouton on ou off passe l'intégralité des prise à l'état inverse de l'état précédent et ce pour l'intégralité des prises electriques*;

***avez-vous une idée pour correction est-il prevu de mettre à jour le plugin ?

**Comment by tcharp38** [comment]
Salut @balabap 
J'ai besoin de logs montrant le pb.

Voir https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

Donc mode debug + pacakge de logs via page maitenance + telecharger tout

**Comment by balabap** [comment]
Hello,
Voici les logs. A ta dispo si besoin de plus.
Pour info je suis passé en Beta au cas ou, mais le comportement n'a rien changé.
j'ai fait plusieurs inclusions sans succès.
Merci d'avance pour tes retours
[AbeilleLogs-231205.tar.gz](https://github.com/KiwiHC16/Abeille/files/13562769/AbeilleLogs-231205.tar.gz)

**Comment by tcharp38** [comment]
Je suppose qu'il s'agit de [Maison][Silvercrest power strip USB SPSZ 3 A1 - 266]
Donc quand tu fais "On1" ca donne quoi sur la prise ?

Demain tu aura une autre beta.
Pourra tu refaire un On 1 ou off 1, me donner l'heure et le package de logs, et me dire ce que tu observes ?

**Comment by balabap** [comment]
Voici le nom "Silvercrest power strip USB SPSZ 3 A1 - 266"
adresse courte : 79B5

J'ai fait un on 1 et ca a tout éteint. Que j'appuie sur on, on1, on2, off, Off1, off2, ça passe toutes les prises dans l'état inverse. (Si était allumé, quelque soit le bouton on ou off ca eteint toutes les prises. Si je réappuie, ca rallume tout.)

Ok pour la nouvelle Beta, dès que j'ai mis a jour et récupéré les logs je te les envoie.

**Comment by tcharp38** [comment]
Tiens un modele à decompresser à la place de celui que tu as (core/config/devices/TS011F__TZ3000_vzopcet)
[TS011F__TZ3000_vzopcetz.zip](https://github.com/KiwiHC16/Abeille/files/13572979/TS011F__TZ3000_vzopcetz.zip)
pour test

Sera dans la beta de demain

**Comment by balabap** [comment]
Hello, avec les modifications que tu as fait, cela fonctionne nickel.
Merci beaucoup pour les modifications.
AS-tu besoin des logs ou autre pour valider ou c'est bon pour toi ?

**Comment by tcharp38** [comment]
Si tu me dis que tout est ok, je ferme.
A réouvrir si nouveaux soucis.
Merci

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
KiwiHC16 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
