### ISSUE TITLE
Silvercrest Ruban a LED

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2672]
Bonjour j'ai nommé ruban à Led, mais je ne sais pas si le PB vient d'eux.

j'utilise un  sonOFF SNZB-01
et récupére son  état par un scénario pour toggle, différentes lampes:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/b295b750-e36b-44b9-9619-7da3b66bf350)

depuis la dernière mise à jour Version 2023-12-06 01:00:22 
les 4 LEd vaissellier ne s'allument plus tous, au max 2 et pas tjrs les mêmes, parfois 1, 
l'ordre ON ALL passé par une remote virtu passe bien (mais le toggle manque cruellement).

le premier SI du sénario passe parfaitement aussi, mais il n'y a que 2 lampes.
voici le log.
[AbeilleLogs-231208.tar.gz](https://github.com/KiwiHC16/Abeille/files/13618840/AbeilleLogs-231208.tar.gz)

j'ai le même effets sur une série de 3 lampes  sans passer par un bouton ou scénario tjrs sur un toggle:
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/846410fb-d6ea-4a57-bceb-c76b005e993d)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/42ac71eb-261e-4242-aa70-73672c641715)
![image](https://github.com/KiwiHC16/Abeille/assets/47332515/52a69e09-b103-4539-a0b3-00145f406427)

Il semble qu'au dessus de 2 lampes les commandes sont perdues.
(a tout hasard la zigate: ZiGate-WiFi v2.00 with esp-link v3.2.50-gfe4f565-dirty)

Merci.

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Je soupconne que ton souci soit lié à un correctif que j'ai déja poussé. J'avais vu en effet que plusieurs commandes empilées pouvaient disparaitrent.
Passe sur la beta du jour, et meme celle de demain.
Et tiens moi au jus.

Désolé pour cette regression.

**Comment by VVorttexx** [comment]
hello, 
bon ben désolé du laïus alors :-) , 
mais en effet cela refonctionne avec la maj du jour. 
pas de PB.

**Comment by tcharp38** [comment]
Non t inquiete. Je ne m'appercois pas toujours des soucis c'est bien pourquoi les beta testeurs sont tres utiles.
Merci pour ton retour.
Je ferme le sujet du coup.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
KiwiHC16 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
