### ISSUE TITLE
Motion Sensor Lidl (id = TY0202, _TZ1800_fcdjzz3s)

### ISSUE THREAD

**Issue by alex1313c** [KiwiHC16/Abeille#2674]
Bonjour

Je voulais savoir si vous rencontrer le même problème que moi au niveau des détecteurs de mouvements Lidl 

le souci que je rencontre c'est quand 1 détecteur et associé tout son passe bien, lors de l'ajout d'un deuxième détecteur les deux ne fonctionnent plus dans les 30 min ou 1 seul détecteur fonctionne  

merci d’avance

**Comment by tcharp38** [comment]
Salut @alex1313c 
Quelle est la signature du modele utilisé par ces detecteurs ? (page equipement + avancé + modèle d'equipement)

**Comment by alex1313c** [comment]
Bonjour 

Voici le modèle équipement pour le détecteur qui a fonctionner plus d'un ans sans soucis TY0202__TZ1800_fcdjzz3s , 
Ce détecteur passe en timeout malgré tout (Les piles on était remplacer ) , 

j'ai effacer le nouveau détecteur et retirer les piles. et ça ne change rien non plus 

-> Je viens de faire la mise a jour du plugins, le capteur a l'air d’être repartit, je test ce soir le 2eme

**Comment by tcharp38** [comment]
Donc tu as basculé sur la nouvelle stable. C'est bien ça ?
Apres pour tout support il faudra basculer en mode debug pour pouvoir me filer un package de logs
Voir https://kiwihc16.github.io/AbeilleDoc/Debug.html

**Comment by alex1313c** [comment]
je suis en version bêta ( Version 2024-01-01 01:00:24 )
pour l'instant ça a l'air de fonctionner je n'ai plus de perte sur le premier détecteur, il fonctionner plus normalement depuis le 10 décembre 
je test l'ajout du 2eme et je te tiens au courant si le problème réapparait

**Comment by alex1313c** [comment]
Toujours le même soucis mais peut être un peu plus d'information

le détecteur 1 fonctionne, lorsque je rajoute le détecteur 2 . le 2 Fonctionne mais le 1 perd le lien il reste en état ou il était  et peu de temps apres le 2 ne fonctionne plus 

Jusqu’à présent je supprimer a chaque fois le détecteur, la je suis rester appuyer sur le bouton d'association et je le sort du réseau lorsque je repasse devant le détecteur 1 il clignote 3 fois Vert Orange Rouge et il refonctionne

je me suis mis en mode debug, 
[log.txt](https://github.com/KiwiHC16/Abeille/files/13823266/log.txt)

**Comment by tcharp38** [comment]
Ce log me dit rien du tout.
J'ai besoin du package de logs de la page maintenance +telecharger tout.

**Comment by alex1313c** [comment]
Bonsoir :)

Voici le log en mode debug

* Aucun détecteur fonctionne + Timeout 

23h09
Retrait motion chambre
Le motion SDB refonctionne 

23h12
Réactivation du motion chambre

23h12 à 23h15
passage devant les détecteurs 

23h15
Perte des 2 détecteurs

23h17
Sortie du détecteur chambre
Passage devant celui de la SDB ( Clignote Rouge Orange Vert et il refonctionne

Merci d'avance

[AbeilleLogs-240115(2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13943513/AbeilleLogs-240115.2.tar.gz)

**Comment by tcharp38** [comment]
Salut

Au vu des logs je peux completer

> 23h09
> Retrait motion chambre
> Le motion SDB refonctionne

Adr 13D2/SDB s'annonce à nouveau.
Pourquoi ?

> 23h12
> Réactivation du motion chambre

E2FE/Chambre s'annonce et entre dans le reseau

> 23h12 à 23h15
> passage devant les détecteurs

Remontée status des 2 detecteurs

> 23h15
> Perte des 2 détecteurs

Comment tu vois cette "perte" ? Ha peut etre que le status passe en "NO ACK" ?
Cote logs je vois des erreur 0x85 (trop de transmissions à la fois) de la Zigate à 23:13, mais pas de cause Abeille. Ca semble etre juste les devices qui causent beaucoup à ce moment.

> 23h17
> Sortie du détecteur chambre
> Passage devant celui de la SDB ( Clignote Rouge Orange Vert et il refonctionne

Voila un modele un peu modifié a decompresser dans Abeille/core/config/devices/TY0202__TZ1800_fcdjzz3s
[TY0202__TZ1800_fcdjzz3s.zip](https://github.com/KiwiHC16/Abeille/files/13948457/TY0202__TZ1800_fcdjzz3s.zip)

J'aimerais bien comprendre ce que tu entends par "perte"

**Comment by alex1313c** [comment]
Bonjour

    23h09
**Adr 13D2/SDB s'annonce à nouveau. Pourquoi ?**  
Justement quand je fais quitter le réseau du détecteur chambre et que je passe simplement devant le capteur SDB, il clignote Rouge Orange Vert et le détecteur SDB refonctionne

    23h12
    Réactivation du motion chambre

E2FE/Chambre s'annonce et entre dans le reseau

    23h12 à 23h15
    passage devant les détecteurs

Remontée status des 2 detecteurs

    23h15
    Perte des 2 détecteurs

**Comment tu vois cette "perte" ? Ha peut etre que le status passe en "NO ACK" ?**  
Enfaite la led du détecteur capte mon passage mais sur jeedom l'etat ne change plus, ( il peut être 1 ou 0  mais meme en attendant il reste figer, ensuite au bout d'une heure il passe en timeout 

Cote logs je vois des erreur 0x85 (trop de transmissions à la fois) de la Zigate à 23:13, mais pas de cause Abeille. Ca semble etre juste les devices qui causent beaucoup à ce moment.

    23h17
    Sortie du détecteur chambre
    Passage devant celui de la SDB ( Clignote Rouge Orange Vert et il refonctionne

J'aimerais bien comprendre ce que tu entends par "perte", 
Plus de changement d’état sur jeedom et timeout par la suite
Mais ce qui est bizarre il suffit que je fasse quitter 1 des 2 détecteur du réseau et celui qui reste actif dans le plugins refonctionne directement apres un passage devant

**Comment by alex1313c** [comment]
Bonsoir

Le nouveau modèle est-il passer dans la version bêta ? car j'ai fait la mise a jour avant de faire les test et il me semble qu'il était déjà modifier avec la date de la mise a jour 

J'ai quand même mis le nouveau modèle dans le dossier  /Abeille/core/config/devices/TY0202__TZ1800_fcdjzz3s/

Le Motion SDB fonctionne, par contre celui de la chambre plus du tout je l'ai même supprimer complétement et refait une inclusion, aucun changement d’état.  ca ne pourrai pas venir du détecteur ? je me pose la question car je suis le seul a avoir un soucis avec un motion Lidl supplémentaire 

j'ai remis l'ancien json et pareil.  aucune valeur d’état 

Voici les logs : 
[AbeilleLogs-240117 avec new json.tar.gz](https://github.com/KiwiHC16/Abeille/files/13969430/AbeilleLogs-240117.avec.new.json.tar.gz)

**Comment by tcharp38** [comment]
Salut @alex1313c 
A priori pour ton cas tout est dans la beta mais ca veut aussi dire que les derniers changements du modeles n'apportent pas grand chose. Je me suis juste aligné sur ce qui est fait chez "zigbee-herdsman" une ref dans le domaine Zigbee.

Bref je n'ai pas de piste pour l'instant.
Si tu n'interviens pas du tout les 2 sensors finissent sans reaction du tout c'est ca ? Meme au bout d'un moment ?

**Comment by alex1313c** [comment]
Salut @tcharp38 
Avec la nouvelle version de équipements quand je rajoute le deuxième il n'y a plus aucun état 
Quand je laisse 1 détecteur il marche sans soucis et avec les deux au bout d'un certain tout les 2 passe en Timeout

Si tu as des test précis a réaliser, il n'y a pas de soucis

**Comment by tcharp38** [comment]
Salut
Tu as activé la surveillance ? Si oui tu me files au moins AbeilleMonitor.log ?

**Comment by tcharp38** [comment]
@alex1313c 
Des news ?

**Comment by tcharp38** [comment]
Je ferme ce sujet sans vie.
A réouvrir si ca interesse qqn
