### ISSUE TITLE
getDeviceModel(): Modèle 'rucheCommand' inconnu. lors de la réinclusion de modules TRADFRI déjà connu

### ISSUE THREAD

**Issue by kromer29** [KiwiHC16/Abeille#2675]
Bonjour,
J'ai un petit problème lors de la ré inclusion de lampes IKEA modèle 'IKEA Ampoule TRADFRI bulb E27 White Spectre opal 1000 lm' et d'interrupteur 'TRADFRI on/off switch'.
Pour mettre dans le contexte, lors de micro-coupures électrique chez moi, toutes mes lampes (8 en tout) se sont réinitialisées :-(,
quant à l'interrupteur, c'est suite à un changement de pile après un non fonctionnement de celui-ci.

pour 3 de mes lampes et l'interrupteur à chaque tentative de réinclusion, j'ai le message getDeviceModel(): Modèle 'rucheCommand' inconnu. et mes équipements ne sont pas fonctionnels sous jeedom.

Ce problème date depuis le 26/12/23, j'ai donc d'abord eu ce problème avec la BETA précédant la dernière version stable du 31/12/2023.

Vous trouverez ci-joint les différents logs d'abeille en mode DEBUG. La dernière tentative de réinclusion avec le message d'erreur est au 03/01/2024 à 00:22:58.
[abeille-log-030124.tar.gz](https://github.com/KiwiHC16/Abeille/files/13814792/abeille-log-030124.tar.gz)
En espérant que ça puisse aider.

Bonne journée.

PS: J'ai une PiZigate avec un firmware en 3.23 LEGACY

**Comment by tcharp38** [comment]
Salut @kromer29 
Je n'ai jamais pu reproduire ce souci mais on me l'avait déja signalé.

Pour infos: pour les logs j'ai toujours besoin du package généré via la page "maintenance" + "telecharger tout".
Du coup je ne sais pas sur quelle version tu es mais je te suggere de rester en beta pour qu'on puisse avancer sur le sujet.

Je vais me repencher la dessus.
Arrives tu à declencher l'erreur de maniere systematique ?

**Comment by kromer29** [comment]
Bonjour,
Merci pour ta réponse et désolé pour les derniers logs.
Pour l'erreur, c'est systématique. Les 3 lampes et l'interrupteur font remonter cette erreur à chaque fois.
De plus, j'ai racheté des kits TRADFRI cette semaine et impossible de les inclures (même message).
Une lampe LED E27 806Lm modèle IKEA LED2103G5. Inclusion tentée ce jour à 23:09:09 et son interrupteur modèle E2201 dont j'ai retenté l'inclusion à 23:18:00
[AbeilleLogs-240104.tar.gz](https://github.com/KiwiHC16/Abeille/files/13836030/AbeilleLogs-240104.tar.gz)

Je suis bien sur le canal béta ;-)

**Comment by tcharp38** [comment]
Salut
Je pousse une beta pour demain avec un peu + d'infos.
J'espere que ca permettra d'avancer sur ce pb.

**Comment by kromer29** [comment]
Merci ;-)

**Comment by kromer29** [comment]
J'ai réessayer l'inclusion avec ma lampe ce matin après la mise à jour avec la version béta de ce matin à 17:16:02.

Voici les logs de cet essai, en espérant que ça te soit utile ;-)
[AbeilleLogs-240105.tar.gz](https://github.com/KiwiHC16/Abeille/files/13844328/AbeilleLogs-240105.tar.gz)

**Comment by tcharp38** [comment]
@kromer29 
C'est bloquant pour toi ?
J'avoue que je seche toujours. Je ne comprends toujours pas comment ce cas peut arriver ni pourquoi ca n'arrive que pour qq utilisateurs. Moi je n'arrive pas à reproduire le souci.
Tout ça pour dire que je vais continuer à ajouter des traces mais ca ne sera du coup pas immédiat car c'est toi qui va tester.

**Comment by kromer29** [comment]
Oui, c'est bloquant, car les appareils que je tente d'inclure ne sont pas pilotable par jeedom (les anciens déjà inclus et fonctionnels dans le passé mais réinitialisés à cause des coupures de courant ainsi que les nouveaux achetés cette semaine et encore jamais vu par ma zigate).
Après l'inclusion de la lampe par exemple, si j'envoie une commande quelle qu'elle soit ('on', 'off', 'toggle', etc...), j'ai un message qui m'indique que la commande c'est bien exécutée et ceci malgré que sur la lampe en question, il ne se passe strictement rien.
La lampe n'est pas en cause car après l'avoir réinitialisée et ré-appairée à une télécommande vierge, elle répond très bien aux commandes de celle-ci.
Pour vérifier si c'était en lien avec le plugin, je viens d'essayer avec le plugin zigate après avoir désactiver Abeille. Ma lampe ne fonctionne pas plus après une nouvelle inclusion via zigate.

Je commence à me dire qu'il faudrait peut-être que j'efface ma zigate (en profiter pour passer en OPDM 3.23 :-D ) et tout réinclure et peut-être que ce serait bon. Il faut juste que je trouve le temps et le courage de faire tout ça ;-)

En tout cas, je te remercie du temps que tu passes à aider tout ceux qui ont besoin :-)

**Comment by tcharp38** [comment]
ok bloquant donc on va proceder autrement.

Decompresse ca dans Abeille/core/class
[AbeilleTools.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13847395/AbeilleTools.class.php.zip)

puis redemarre Abeille
refais une inclusion qui merdoit
et files moi les logs STP

**Comment by kromer29** [comment]
[AbeilleLogs-240106.tar.gz](https://github.com/KiwiHC16/Abeille/files/13847566/AbeilleLogs-240106.tar.gz)

Voilà,
Ré inclusion tentée vers 00:37:24.
En espérant que ça aide.

**Comment by tcharp38** [comment]
C'est vraiment un effet de bord vicieux mais on va trouver.
Nouvel essai STP

A decompresser dans Abeille/core/php puis meme manip que precedement
[AbeilleCmd.zip](https://github.com/KiwiHC16/Abeille/files/13849628/AbeilleCmd.zip)

**Comment by kromer29** [comment]
Voici les nouveaux logs avec la modif. (Inclusion tentée à 16:13)
;-)
[AbeilleLogs-240106(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13850164/AbeilleLogs-240106.1.tar.gz)

**Comment by tcharp38** [comment]
Je crois que j'ai trouvé.
En tout cas j'ai fixé qq trucs pas propres.

Peux tu decompresser ce fichier dans Abeille/core/class
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13851793/Abeille.class.php.zip)

et redemarrer Abeille +refaire essai & logs

**Comment by kromer29** [comment]
Bonjour,
J'ai refais l'essai avec tes modifs.
En effet, je n'ai plus de message d'erreur. Cependant, ma lampe ne réponds toujours pas aux commandes de Jeedom après la tentative d'inclusion. :-/
(Début d'inclusion à 15:15:46)

[AbeilleLogs-240107.tar.gz](https://github.com/KiwiHC16/Abeille/files/13853811/AbeilleLogs-240107.tar.gz)

**Comment by tcharp38** [comment]
Alors toi tu commences à avoir des erreurs x87 de la Zigate
autrement dit..."pleine"

    [2024-01-07 15:21:17] Abeille1, Type=9999/Extended error, ExtStatus=87, NPDU=00, APDU=02

Mais tu cumules avec un souci que je n'ai pas encore résolu mais qui trainait dans ma tete depuis un moment.
Je vais travailler la dessus.

**Comment by kromer29** [comment]
Pour la zigate pleine, ça ne m'étonne pas trop.
Je suis à 32 périphériques Zigbee actif et 4 désactivé mais en réserve (et donc encore lié à ma zigate) plus certains qui sont peut-être encore dans sa mémoire.
Il me semble qu'avec le firmware legacy on est limité à 40 appareils zigbee ?

Il faudrait vraiment que je prenne le temps d'effacer et de tout recommencer avec le firmware OPDM :-/

**Comment by tcharp38** [comment]
Je suis incapable de te repondre pour cette limite.Jamais compris
Mais la version OPDM fait mieux.
Quoi qu'il en soit je fais une update du code pour un souci que tu remontes

**Comment by tcharp38** [comment]
A decompresser dans Abeille/core/class
[AbeilleCmdQueue.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13853982/AbeilleCmdQueue.class.php.zip)

Et celui la dans Abeille/core/php
[AbeilleParser.zip](https://github.com/KiwiHC16/Abeille/files/13853984/AbeilleParser.zip)

Puis redemarrer
refaire inclusion
filer les logs

**Comment by kromer29** [comment]
[AbeilleLogs-240107(1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13854301/AbeilleLogs-240107.1.tar.gz)
Voilà les logs avec les modules que tu as modifiés.
(inclusion lancée à 18:21:13)

Merci pour tout le boulot que tu effectue ;-)

**Comment by tcharp38** [comment]
Ouah, ca merde.
Voila une update rapide
[AbeilleCmdQueue.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13854361/AbeilleCmdQueue.class.php.zip)

Je vais tacher de faire + de tests de mon cote mais attends toi a avoir d'autres updates

**Comment by kromer29** [comment]
Voici les nouveaux logs
[AbeilleLogs-240107(2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13854619/AbeilleLogs-240107.2.tar.gz)

(inclusion effectuée à 20:03:51)

**Comment by tcharp38** [comment]
Nouveau code pour Abeille/core/class
[AbeilleCmdQueue.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13855027/AbeilleCmdQueue.class.php.zip)

Désolé, je ne peux pas reproduire ton cas. Du coup les essais sont pour toi.

**Comment by kromer29** [comment]
Nouvel essai avec le nouveau code ;-)
[AbeilleLogs-240107(3).tar.gz](https://github.com/KiwiHC16/Abeille/files/13855118/AbeilleLogs-240107.3.tar.gz)

(inclusion effectuée à 23:12:15)

**Comment by tcharp38** [comment]
C 'est mieux mais ca ne resoud pas ton pb final.. l'inclusion de ton nouvel equipement.
Il s'annonce puis ne repond plus.

Je pense que la Zigate ne fait pas le job. Surement du fait qu'elle dit etre saturée.

Pour confirmer ca tu peux essayer de faire quitter le reseau à un des equipements
et inclure celui ci à la place. Juste une idée mais de toute façon tu ne coupes pas à ajouter une nouvelle Zigate (v1 toujours je conseille, d'occase), ou passer en OPDM.

**Comment by kromer29** [comment]
Bonjour,
Juste pour signaler que tout refonctionne bien.
J'ai rincé ma zigate et j'en ai profité pour la passer en V3.23 OPDM.
Pour l'instant, je refais toutes les inclusions au fur et à mesure et jusqu'à maintenant tout se passe bien.
On verra quand j'aurai réinclu mes 36 équipements ;-).

En tout cas merci pour le boulot accompli :-)
Bon week-end :-)

PS: je n'ai pas réussi à flasher ma zigate via le plugin.
J'ai dû télecharger le firmware 'ZiGate_v3.23-OPDM.bin' via le site de zigate.
j'avais réessayé manuellement avec celui que tu as dans 'Abeille/resources/fw_zigate/zigatev1-3.23-opdm.bin'
mais à priori ma Pizigate n'est pas compatible avec ce firmware

**Comment by tcharp38** [comment]
Salut @kromer29 
Cool. Content de ces bonnes nouvelles.

Par contre je ne pige pas le pb de flashage.
Tu as eu des erreurs ? Des infos à me filer ?
Il ny a que la PI v1 qu'on peut flasher directement d'Abeille.

**Comment by kromer29** [comment]
Avec le firmware présent avec le plugin Abeille, ça me dit juste que ma zigate (son hardware) n'est pas pris en charge par le firmware.
Avec celui que j'ai téléchargé via le site de Zigate, le flashage ce passe bien.
Comme je suis passé par la ligne de commande, je n'ai pas de trace de ça. À l'occasion je peux refaire le flashage avec ton firmware et te faire une capture d'écran 😉

**Comment by kromer29** [comment]
Via le plugin, ça ne fonctionnait pas, mais je n'ai pas vraiment fait attention aux messages d'erreur 🙏

**Comment by tcharp38** [comment]
Ok, je retenterai à l occase. Pour moi ca fonctionnait bien, d'ou ma surprise.

On peut fermer ce sujet du coup ?

**Comment by kromer29** [comment]
Pour moi, c'est tout bon.
Le sujet peut-être clos ;-)
