### ISSUE TITLE
Plugin erreur encodage caractères

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2677]
Bonjour @tcharp38 ,

Comme convenu, j'ouvre un nouveau sujet pour le plugin Abeille, concernant un problème de caractère.

J'ai dû réinstaller un device (SNZB-04), et depuis lorsque je saisie un accent, dans l'onglet commandes, Status, Configuration, j'ai programmé une alerte mail et sms au changement de status, exemple
![2024-01-05_144105](https://github.com/KiwiHC16/Abeille/assets/104787819/cbb25dfa-e475-4626-852b-82ef96b659ed)
Si je tape le même texte pour l'e-mail que celui du sms, j'ai une erreur smtp serveur....... ?

Par contre ce n'est pas nouveau, même chose si je donne un titre  "Capteur porte d'entrée" lors de la sauvegarde l'accent disparaît ?
![2024-01-05_150430](https://github.com/KiwiHC16/Abeille/assets/104787819/e51e1fbf-0322-4e6d-a399-b980f9b1f164)

Merci pour ton aide

**Comment by tcharp38** [comment]
Je ne suis pas sur que ton souci soit lié à Abeille.
Il ne fait rien à ce niveau. C'est du pur Jeedom avec ton plugin email.
Ou bien ca fonctionne avec un autre equipement non Abeille ?

Comment je peux reproduire ? Pas sur de bien comprendre non plus.

**Comment by Jeedom122** [comment]
Ça fonctionnait avant de réinstaller le device abeille ?
Effectivement j'ai le même problème avec Jeedouino.
Le code erreur exact : 
![2023-12-25_203410](https://github.com/KiwiHC16/Abeille/assets/104787819/e4ba1742-4204-4984-a040-ede35fefdcaa)
J'ai l'impression qu'il y a un problème de droit ?
Quand je fais des tests dans le plugin e-mail, cela fonctionne ?

**Comment by tcharp38** [comment]
Ha donc si ca merde avec un autre plugin..Abeille n'est pas en cause mais peut etre as tu fait une autre mise à jour en meme temps?

Donc c'est ton plugin mail qui semble pas content. C'est ça ?
D'ailleurs de quel plugin s'agit il? "Email" officiel de Jeedom SAS ?
Jamais utilisé mais quel message tentes tu d'envoyer?

**Comment by Jeedom122** [comment]
Effectivement, c'est le plugin officiel "Email" qui lorsque je le test fonctionne très bien, avec n'importe quel texte. Déjà ce n'est pas le FAI qui bloque, comme j'ai pu lire sur différents forums.
Par contre dans un plugin cela génère un message d'erreur, alors que ça fonctionnait parfaitement jusqu'au 27 décembre, depuis des années ?

**Comment by tcharp38** [comment]
Mais c'est à cause d'un accent dans le titre ? Dans le message ? Ou autre chose ?
Tu as pu identifier le pb exacte ?

**Comment by Jeedom122** [comment]
En fait c'est même pas un problème d'accent, comme je le pensais au début.
Dans Abeille, au départ j'avais ce texte "ATTENTION ouverture porte d'entrée !", j'ai remplacé par "Alerte", là ça fonctionne

![2024-01-09_090030](https://github.com/KiwiHC16/Abeille/assets/104787819/436814e4-358f-471a-a812-56d6ce26fb2d)

Dans un autre plugin, Jeedouino, je peux mettre n'importe quel texte, ça ne fonctionne pas ?

![2024-01-09_085825](https://github.com/KiwiHC16/Abeille/assets/104787819/9668c85c-bca0-439b-8bf3-70dc19e71489)

J'ai réinstallé le plugin Email, sans résultat, d'ailleurs quand je fais un test directement du plugin ça fonctionne très bien, avec n'importe quel texte.

Tu penses que je devrais ouvrir un ticket auprès de Jeedom ? Le plugin fonctionne.

Je pensais faire les mises à jour en ligne de commandes, qu'est ce que tu en penses ?
sudo apt-get update
sudo apt-get upgrade
etc...

**Comment by Jeedom122** [comment]
Encore plus bizarre, j'utilise le plugin Nut pour l'onduleur, pas de soucis, il envoie bien les messages.
Donc la fonction mail fonctionne, sauf sur Jeedouino et Abeille, plugin que travail depuis 15 jours, depuis mon problème ?
Hummmm

**Comment by Jeedom122** [comment]
Je viens de recevoir un message email du détecteur de fumée, Abeille, Zigbee, sans problème ????
Soucis seulement sur certain devices.
Encore plus étrange ?????

**Comment by tcharp38** [comment]
Tu l'as fermé c'est que tu as résolu ton pb ?

**Comment by Jeedom122** [comment]
Salut @tcharp38 , non, je n'ai pas résolu le problème, comme cela ne concernait pas que Abeille.
J'ai un device Abeille et un Jeedouino qui me pose problème. Je pense réinstaller les deux.
Par contre depuis quelques jours, les messages, même sms ne sont pas systématiquement envoyés, sans message d'erreur ?
Peut-être avec la version 4.4, cela va résoudre le bug, on peut rêver :)

**Comment by tcharp38** [comment]
Ok je comprends.
Effectivement, je ne vois pas en quoi Abeille a un quelconque impact sur ce souci.
Alors bon courage.
