### ISSUE TITLE
Ajout Capteur lumière AQARA :  GZCGQ11LM

### ISSUE THREAD

**Issue by Azriels57** [KiwiHC16/Abeille#2679]
Bonjour, 

Capteur de lumière AQARA – capteur de lumière T1, capteur de luminosité Zigbee 2023, détecteur de lumière automatique pour la maison, contrôle par application magnétique

[discovery-sen_ill.agl01_LUMI (1).json](https://github.com/KiwiHC16/Abeille/files/13908039/discovery-sen_ill.agl01_LUMI.1.json)

**Comment by tcharp38** [comment]
Bonjour

a decompresser dans Abeille/core/config/devices/sen_ill.mgl01
[sen_ill.mgl01.json.zip](https://github.com/KiwiHC16/Abeille/files/13908578/sen_ill.mgl01.json.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by tcharp38** [comment]
Salut @Azriels57 
Des nouvelles ?
J'ai poussé une nouvelle beta pour demain avec toutes les corrections et nouveaux modeles du moment.

**Comment by tcharp38** [comment]
@Azriels57 
Salut
Que fait on avec ce sujet ?

**Comment by tcharp38** [comment]
Je ferme ce sujet sans vie.
A réouvrir si qqn à cet equipement et peut faire des tests.
