### ISSUE TITLE
Network Modal, representation graphique sur la base de mon retour d experience

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#268]
C'est vraiment chouette cette représentation. C'est nettement plus joli que mon graphe du début !!!

- recuperation LQI qui ne semble plus marcher: #267

Petites améliorations:
![capture d ecran 2018-05-29 a 09 52 15](https://user-images.githubusercontent.com/8549674/40645215-ff729274-6325-11e8-9a76-8f45ce788d83.png)
Faire un retour à la ligne qu'en la liste est trop longue (ou ne pas la mettre car difficile à lire et redondant avec "Table de routage"

Evolution:
Page graphique du reseau:
- peut on fixer la position des equipements pour avoir une representation sur la base des x, y qu'on defini dans l'objet. (Un bouton pour choisir placement automatique ou position X,Y)
- Peut on definir la longueur des liens en fonction d'un parametre (Valeur LQI, ...) ?
- Peut on changer la couleur du lien en fonction de cette valeur ?
- Peut on avoir un filtre sur les equipements que l on veut ?
- Peut on avoir un filtre sur les liens que l on veut ? (LQI > 100 par exemple)
- Peut on faire apparaitre la valeur du lien ?
- 

Page Table de routage:
- "Table de routage" en fait ce n'est pas une table de routage, il faudrait lui trouver une autre nom: "Table des voisines",...
- Peut on ajouter un lien sur les adresses courtes pour ouvrir l objet directement
- Ajouter une colonne "objet" qui est l objet Jeedom de rattachement, avec un lien pour aller directement à la page contenant l objet
- Jouer avec la couleur LQI (<50 rouge, <150 orange et vert)
- Bouton recalcule du cache, comme cela peut etre tres long plusieurs minutes, il faudrait que le script qui fait le boulot renvoi sa progression et que dans la page on ai un indicateur de progression.
- ...

**Comment by edgd1er** [comment]
Pour la partie graphique, ce que tu proposes est possible sauf pour
* placement des noeuds ( je ne sais pas faire, mais ça doit etre possible.) cf http://www.yasiv.com/ , https://github.com/anvaka/VivaGraphJS/tree/master/demos/tutorial_svg, http://www.yasiv.com/graphs#Bai/dw256A
* Longueur sur LQI: ne crains tu pas d'avoir des petits patés en cas de de mauvaises valeurs, je pensais mettre des couleurs mais ça aussi, j'ai du mal ;)

En accord avec toi pour la page "routage", par contre pour la maj LQI, je ne vois que comment faire avec du bloquant (roue dentée), a voir comment faire une requete ajax avec plusieurs remontées d'infos.
* Que vois tu quand tu dis "Peut on avoir un filtre sur les equipements que l on veut ?", il y a deja deux filtres, sur les from et to des liens zigbee. Que souhaites tu ajouter ?
* on peut mettre des filtres partout et tri croissant decroissant, il doit y a une librairie js pour le faire, je crois que jQuery le fais aussi avec une extension.

**Comment by KiwiHC16** [comment]
Pour la partie graphique, je n'ai pas d'experience donc ca sera difficile d'aider.

Longueur LQI, l'idée est de faire une carte de la qualité radio. On connait les cartes IGN avec les liens qui sont les distances entre les villes, mais j'ai vu des cartes avec les temps de trajet ce qui est tres interessant. L'idée est de faire pareil. C'est peut etre stupide. La logueur du lien serait inversement proportionelle au LQI avec une distance minimum sur le graphe pour que cela soit lisible.

MAJ LQI, sinon mettre un fichier lock quand le script tourne avec une estimation de temps et un pourcentage dans le fichier, a voir... un truc comme l avancement de l installation des dependances...

Les filtres sont dans "Table Routage" mais pas dans le graphique. Peut on les avoir aussi dans le graph ?

**Comment by KiwiHC16** [comment]
Le graphs et table ne sont pas rafraichi sous Safari apres une collecte des LQI. La seule solution trouvée est d'effacer l historique de Safari ce qui n est franchement pas pratique.

Firefoxx ne semble pas avoir ce soucis.

**Comment by KiwiHC16** [comment]
Pendant la collect, le fichier AbeilleLQI_MapData.json.lock    est créé et contient le nombre NE fait sur le nombre de NE a faire.

Exemple: cat AbeilleLQI_MapData.json.lock
`13 of 15`

**Comment by KiwiHC16** [comment]
Sur ma prod qui a beaucoup de NE, la table s affiche parfaitement par contre le graph n'apparait jamais la roue crantée reste à tourner ... (Safari et Firefox)

**Comment by edgd1er** [comment]
As tu une erreur dans la console de dev du navigateur (F12 sous firefox)  ?

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-05-31 a 11 58 41](https://user-images.githubusercontent.com/8549674/40776074-0697a896-64ca-11e8-8926-655602c3ed7e.png)

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-05-31 a 12 01 07](https://user-images.githubusercontent.com/8549674/40776203-5c3c2754-64ca-11e8-8f75-3aa783dcd8da.png)


Le null est aussi dans la liste !!!

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-05-31 a 12 11 15](https://user-images.githubusercontent.com/8549674/40776689-c71e2850-64cb-11e8-9a80-05ccd74eab13.png)

JSON ontient null...

**Comment by KiwiHC16** [comment]
fde8 n'existe pas dans Jeedom. Ceci explique cela. Donc lors de la collection des infos on trouve un nouveau NE. Il faut que graphe soit transparent et ne plante pas si un NE n'existe pas en base.

**Comment by edgd1er** [comment]
@KiwiHC16,  est ce que tu peux m'envoyer ton fichier json pour que je travaille sur le correctif ?

**Comment by KiwiHC16** [comment]
C est la version de mon reseau de prod.
C est dans celui ci qu’il y a un champ: "Voisine_Name": null,

Ben
