### ISSUE TITLE
Ajout lampe IKEA TRADFRI E27 type:E2201 modèle: TRADFRI WW2320 50050 (id = TRADFRIbulbE27WWglobe806lm, IKEAofSweden)

### ISSUE THREAD

**Issue by kromer29** [KiwiHC16/Abeille#2680]
Bonjour, lors de l'inclusion de la lampe donnée dans le titre, le modèle n'est pas reconnu.

Voici le fichier généré par l'assistant de découverte
[discovery-TRADFRIbulbE27WWglobe806lm_IKEAofSweden(1).zip](https://github.com/KiwiHC16/Abeille/files/13928590/discovery-TRADFRIbulbE27WWglobe806lm_IKEAofSweden.1.zip)

Bonne journée :-)

**Comment by tcharp38** [comment]
Salut @kromer29 

Voila une modele preliminaire
[TRADFRIbulbE27WWglobe806lm_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/13940511/TRADFRIbulbE27WWglobe806lm_IKEAofSweden.zip)

J'ai un doute sur le modele.
Quel est celui de l'ampoule ? Pas la telecommande.
La ref du modele devrait etre un truc du style LED2003G10

**Comment by kromer29** [comment]
Salut @tcharp38 
Ton modèle fonctionne très bien.
La référence du modèle est: LED2103G5.

Merci beaucoup pour ton super travail :-).

**Comment by tcharp38** [comment]
Ok modèle corrigé.
Rien à changer ?
Tout est fonctionnel et pas de bouton sans interet ?

**Comment by kromer29** [comment]
Non, tout est là, 'on', 'off', 'toggle' et 'set level' fonctionne bien et les status de la lampe remonte bien aussi.
Aucun bouton en trop non plus ;-).
La liaison de la lampe à mes interrupteurs via la fonction des groupes du plugin Abeille fonctionne très bien aussi.

Rien à redire :-)

**Comment by tcharp38** [comment]
Ok super.
Je ferme le sujet alors.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)

**Comment by tcharp38** [comment]
@kromer29 
Merci pour ta contribution
