### ISSUE TITLE
Support IKEA VINDSTYRKA air quality sensor (id = VINDSTYRKA, IKEAofSweden)

### ISSUE THREAD

**Issue by gegedme** [KiwiHC16/Abeille#2681]
Bonjour,

bonne année à tous.

je viens d'acquérir un module IKEA pour la qualité de l'air.
est-il possible de l'ajouter aux équipements supportés ?

merci pour l'aide apporté

[discovery-VINDSTYRKA_IKEAofSweden.json](https://github.com/KiwiHC16/Abeille/files/13932193/discovery-VINDSTYRKA_IKEAofSweden.json)

**Comment by tcharp38** [comment]
Salut 

Voila un modele preliminaire à décompresser dans Abeille/core/config/devices
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/13940061/VINDSTYRKA_IKEAofSweden.zip)

Redemarrer Abeille
refaire inclusion

Pour tout support il faut etre en mode debug: https://kiwihc16.github.io/AbeilleDoc/Debug.html#support

Il me faudra une belle image format PNG sans arriere plan à mettre en icone

**Comment by gegedme** [comment]
Hello

Je fais ça en rentrant ce soir 
Merci encore pour ton aide

**Comment by gegedme** [comment]
[AbeilleMonitor (4).log](https://github.com/KiwiHC16/Abeille/files/13941242/AbeilleMonitor.4.log)
[discovery-VINDSTYRKA_IK
![VINDSTYRKA](https://github.com/KiwiHC16/Abeille/assets/139325751/2ecb3648-6347-4fc4-b10f-4a10442f9ec3)
EAofSweden (1).json](https://github.com/KiwiHC16/Abeille/files/13941245/discovery-VINDSTYRKA_IKEAofSweden.1.json)

voilà.

pour l'instant, j'ai bien la température et l'humidité.
pas la qualité de l'air

merci

**Comment by tcharp38** [comment]
Image enregistrée.
Mets le en surveillance et il faudra que tu me files le package de logs demain pour voir ce qu'il remonte et quand.

**Comment by gegedme** [comment]
c'est fait.
je te donne ça ce soir.
bonne journée

**Comment by gegedme** [comment]
[AbeilleLogs-240116.tar.gz](https://github.com/KiwiHC16/Abeille/files/13952750/AbeilleLogs-240116.tar.gz)

voilà le package des logs après une dizaine d'heures d'observation.

**Comment by tcharp38** [comment]
Salut

Peux tu basculer sur la derniere beta
et me résumer les infos que tu attends de ce device en précisant celles qui sont déja ok ?

**Comment by tcharp38** [comment]
Tiens, voila un nouveau modele une fois que tu aura basculé sur la derniere beta.
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/13961346/VINDSTYRKA_IKEAofSweden.zip)

J'aurai besoin du package de logs qq mins apres reinclusion

**Comment by gegedme** [comment]
[AbeilleLogs-240117.tar.gz](https://github.com/KiwiHC16/Abeille/files/13961523/AbeilleLogs-240117.tar.gz)
![Capture d'écran 2024-01-17 110228](https://github.com/KiwiHC16/Abeille/assets/139325751/0929a0ce-3391-4eef-9d3b-722f9c124927)
voilà.
je suis sur la dernière beta
j'ai refait l'inclusion et patienté 5 min
j'aimerais avoir l'indice de qualité de l'air. (pm2.5)
je n'ai pas m'impression qu'il soit dans les commandes disponibles.
c'est bon pour la température et l'humidité.

**Comment by gegedme** [comment]
![Capture d'écran 2024-01-17 110822](https://github.com/KiwiHC16/Abeille/assets/139325751/5a030caa-6374-408f-8357-7f56067e704e)
quand je fais l'inclusion, il y a 2 remontées d'erreur dans Jeedom

**Comment by tcharp38** [comment]
A decompresser dans Abeille/core/class
[AbeilleCmdProcess.class.php.zip](https://github.com/KiwiHC16/Abeille/files/13962604/AbeilleCmdProcess.class.php.zip)

puis redemarrer démon Abeille
et meme manip que precedente

**Comment by gegedme** [comment]
[AbeilleLogs-240117 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/13962977/AbeilleLogs-240117.1.tar.gz)
voilà

**Comment by tcharp38** [comment]
On avance

Inclusion a refaire avec ce nouveau modele
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/13963111/VINDSTYRKA_IKEAofSweden.zip)

Il va falloir ensuite regarder le reporting du VOC. Bien trop frequent. Ca pourri le reseau

**Comment by gegedme** [comment]
![Capture d'écran 2024-01-17 133444](https://github.com/KiwiHC16/Abeille/assets/139325751/795855b5-6763-4e1e-b851-b6075503763e)
yeah !!!!!
tout est là.
en revanche je ne comprends pas pourquoi le VOC renvoie 99 ou 100 en valeur.
cette information renvoie sur le module Ikea si c'est stable, en augmentation ou en diminution en affichant une flèche vers le haut, bas ou horizontale

**Comment by gegedme** [comment]
[AbeilleLogs-240117 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/13963404/AbeilleLogs-240117.2.tar.gz)
et voici les logs après 20 min

**Comment by tcharp38** [comment]
A priori l'index remonté est juste utilisé pour montrer une progression (aumgente/diminue/stable) sur le device.
Je ne sais pas trop comment afficher ce genre de truc avec Jeedom.

Le souci qui reste pour moi et le mode "trop bavard" des infos VOC. Pas bon ça

    [2024-01-17 13:52:12][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:12][DEBUG] :   'VOC' (FC7E-01-0000) => 102 
    [2024-01-17 13:52:13][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:13][DEBUG] :   'VOC' (FC7E-01-0000) => 102 
    [2024-01-17 13:52:14][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:14][DEBUG] :   'VOC' (FC7E-01-0000) => 102 
    [2024-01-17 13:52:15][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:15][DEBUG] :   'VOC' (FC7E-01-0000) => 102 
    [2024-01-17 13:52:16][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:16][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:17][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:17][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:18][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:18][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:19][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:19][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:20][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:20][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:21][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:21][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:22][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:22][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:23][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:23][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:24][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:24][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:25][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:25][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:26][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:27][DEBUG] :   'VOC' (FC7E-01-0000) => 103 
    [2024-01-17 13:52:28][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/3928/01
    [2024-01-17 13:52:28][DEBUG] :   'VOC' (FC7E-01-0000) => 103

**Comment by gegedme** [comment]
de toute façon, l'info VOC n'est pas trop utile.
effectivement .... c'est trop souvent

**Comment by tcharp38** [comment]
Peux tu, via la page EQ/avancé, faire "Mise à jour" et me filer le package de logs ?

**Comment by gegedme** [comment]
ok.
mais où puis-je trouver la page EQ/avancé ?

**Comment by tcharp38** [comment]
Tu cliques sur ton equipement puis onglet "avancé"

**Comment by gegedme** [comment]
[AbeilleLogs-240117 (4).tar.gz](https://github.com/KiwiHC16/Abeille/files/13963576/AbeilleLogs-240117.4.tar.gz)

**Comment by gegedme** [comment]
la valeur pm2.5 ne s'est pas mis à jour depuis 13h32.

**Comment by tcharp38** [comment]
Cote voc la config reporting n'est pas bonne

    [2024-01-17 14:01:29] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FC7E, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=3928, DstAddrMode=02, DstAddr=0000
    [2024-01-17 14:01:29]   FCF=08/General/Serv->Cli, SQN=04, cmd=07/Configure Reporting Response
    [2024-01-17 14:01:29]   Status=86/Unsupported attribute, Attr=0000, Dir=00

Retente une mise à jour + logs avec ce modele STP
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/13963740/VINDSTYRKA_IKEAofSweden.zip)

**Comment by gegedme** [comment]
[AbeilleLogs-240117 (5).tar.gz](https://github.com/KiwiHC16/Abeille/files/13964003/AbeilleLogs-240117.5.tar.gz)

**Comment by gegedme** [comment]
finalement les chiffres VOC sont intéressants.
j'ai placé le module dans mon caisson d'impression 3D
c'est bien monté.
inférieur à 250 ça va.
au-dessus il faut aérer.

**Comment by gegedme** [comment]
![Capture d'écran 2024-01-17 153101](https://github.com/KiwiHC16/Abeille/assets/139325751/027b43c3-3028-4a08-af1a-b7cb896682ff)

**Comment by tcharp38** [comment]
Je ne comprends pas pourquoi il refuse la config reporting du VOC.

**Comment by gegedme** [comment]
désolé de t'embêter avec ça.

merci encore pour ton aide

**Comment by tcharp38** [comment]
Mais non. Il va bien falloir trouver. Il est trop bavard et ca peut finir par planter le systeme.

**Comment by tcharp38** [comment]
Hello
Est on d'accord que le seul pb qui reste est que le retour de VOC est trop bavard ? (toutes les secondes)

Penses à le mettre en surveillance aussi pour avoir un log monitor

**Comment by gegedme** [comment]
Bonsoir

Oui c'est ça.

Je fais ça.
Je te donne le log après combien de temps?

**Comment by tcharp38** [comment]
Qq heures de recul c'est déja interessant.

**Comment by gegedme** [comment]
[AbeilleLogs-240122.tar.gz](https://github.com/KiwiHC16/Abeille/files/14014879/AbeilleLogs-240122.tar.gz)

**Comment by gegedme** [comment]
Dis moi si c'est bon

Merci encore

**Comment by tcharp38** [comment]
Alors avec un rapide coup d'oeil, tu peux toi aussi voir via le monitor qu'il n'y a 
- aucun retour du cluster 042A (PM25)
- un retour quasi toutes les secondes du cluster FC7E (VOC)

Il faut chercher des trucs du style

    [2024-01-17 14:45:30] <= Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FC7E, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=3928, DstAddrMode=02, DstAddr=0000
    [2024-01-17 14:45:30] <=   FCF=0C/General/Serv->Cli/ManufCode=117C, SQN=6F, cmd=0A/Report attributes
    [2024-01-17 14:45:30] <=   AttrId=0000/Unknown-FC7E-0000, AttrType=39, ValueHex=42CC0000 => 102

Tu confirmes que PM25 n est jamais mis à jour ?

**Comment by gegedme** [comment]
Oups....
Ma femme l'avait débranché
Désolé.
C'est reparti

**Comment by gegedme** [comment]
surveillance sut toute la journée.
encore désolé....
[AbeilleLogs-240123.tar.gz](https://github.com/KiwiHC16/Abeille/files/14027671/AbeilleLogs-240123.tar.gz)

**Comment by tcharp38** [comment]
Pas de soucis.

Bon je vois le VOC qui remonte toutes les secondes (pas bon)
et le PM25 qui ne remonte pas du tout (pas bon non plus).

Il faut que je pousse la nouvelle beta pour qu'on puisse faire d autres esssais

**Comment by gegedme** [comment]
Merci encore pour ton aide.

**Comment by tcharp38** [comment]
Si tu as basculé sur la derniere beta tu peux faire les essais suivants
en cliquant sur ton equipement + onglet avancé

Chauqe fois note l'heure

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/f8e93580-52f9-442b-9169-564690670568)

Attends 5 mins

puis meme chose avec le code fabricant

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/db0b8fe4-95f7-4996-b935-b9f9f2c95dd2)

attends encore 5 mins et file moi le package de logs STP

**Comment by gegedme** [comment]
je suis passé sous la béta ce matin.
je fais ça de suite

**Comment by gegedme** [comment]
1er fois : 15:14 à 15:19
2eme fois : 15:20 à 15:25
j'espère avoir tout bien fait. (pour la première étape je l'ai refais 2 fois car mauvaise saisie)
ci-joint les logs 
[AbeilleLogs-240126.tar.gz](https://github.com/KiwiHC16/Abeille/files/14065950/AbeilleLogs-240126.tar.gz)

**Comment by tcharp38** [comment]
Bon je ne vois pas tout mais tu dois te rendre compte qu'avec ces manips le PM25 remonte maintenant tout le temps.

Donc refais la meme manip que le dernier essai (celui avec manufCode=1141)
mais à la place 1 et 1 tu mets 1800 et 1800.
Tu devrais avoir un reporting PM25 toutes les 30mins apres ça.
Tu confirmes ?

**Comment by gegedme** [comment]
Sans faute je fais demain.
En déplacement ce weekend.
Merci

**Comment by gegedme** [comment]
malheureusement, ma ZIGATE n'était plus reconnue depuis plusieurs jours à priori
j'ai rechargé une sauvegarde et recommencer les manipulations.
je confirme les remontées toutes les 30 minutes pour la valeur PM2.5
[AbeilleLogs-240129.tar.gz](https://github.com/KiwiHC16/Abeille/files/14084492/AbeilleLogs-240129.tar.gz)

**Comment by tcharp38** [comment]
Hello 
Zigate plus reconnue ?! Pas cool ca. Tu n'as pas gardé de traces je suppose ?

Pour le PM25 c'est une bonne nouvelle. J'ai corrigé le modele dans ce sens.
On peut essayer d'appliquer la meme chose pour le VOC
Tu peux tenter la meme derniere manip en changeant le cluster 042A par FC7E

**Comment by gegedme** [comment]
c'est fait.
je te redis pour le voc.

désolé, je n'ai pas fait de sauvegarde avec de restaurer ma dernière sauvegarde

**Comment by gegedme** [comment]
voici les logs après 24 h
collecte toutes les 5 minutes j'ai l'impression
[Uploading AbeilleLogs-240130.tar.gz…]()

**Comment by tcharp38** [comment]
Upload pas complet donc pas de logs :(

**Comment by gegedme** [comment]
ah ?
voila de nouveau les logs
[AbeilleLogs-240131.tar.gz](https://github.com/KiwiHC16/Abeille/files/14108171/AbeilleLogs-240131.tar.gz)

**Comment by tcharp38** [comment]
Bon le VOC remonte toujours toutes les sec
Mais je realise un truc.. le manufCode semble etre 117C et non pas 1141 donc je pige pas pourquoi ca a fonctionné pour le PM2.5

Je te laisse refaire une inclusion apres avoir mis à jour le modele
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14110141/VINDSTYRKA_IKEAofSweden.zip)

tu me files le package dans la foulée
puis au bout de qq heures STP

**Comment by gegedme** [comment]
voilà.
[AbeilleLogs-240131 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/14110490/AbeilleLogs-240131.2.tar.gz)

**Comment by tcharp38** [comment]
La config du VOC ne passe toujours pas

    [2024-01-31 11:35:14] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FC7E, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=1FD8, DstAddrMode=02, DstAddr=0000
    [2024-01-31 11:35:14]   FCF=0C/General/Serv->Cli/ManufCode=1141, SQN=04, cmd=07/Configure Reporting Response
    [2024-01-31 11:35:14]   Status=86/Unsupported attribute, Attr=0000, Dir=00

mais ca n'est pas avec mon modele. Le manufCode est toujorus 1141 et non pas 117C.
Tu l'as bien décompressé au bon endroit avant de refaire la manip ?

**Comment by gegedme** [comment]
erreur de manipulation.....
le fichier était dans le répertoire d'à côté.
c'est rectifié
[AbeilleLogs-240131 (3).tar.gz](https://github.com/KiwiHC16/Abeille/files/14111941/AbeilleLogs-240131.3.tar.gz)
je suis pas doué.

**Comment by gegedme** [comment]
après quelques minutes, le VOC est toujours à 0

**Comment by tcharp38** [comment]
Yes.. le VOC ne remonte plus toutes les sec. Il est programmé pour toutes les 30mins et la config est acceptée

    [2024-01-31 14:00:17] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=FC7E, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=94BE, DstAddrMode=02, DstAddr=0000
    [2024-01-31 14:00:17]   FCF=0C/General/Serv->Cli/ManufCode=117C, SQN=04, cmd=07/Configure Reporting Response
    [2024-01-31 14:00:17]   Status=00/Success, Attr=, Dir=

Par contre ca a cassé le PM25 qui lui remonte maintenant toutes les sec. Pour cause.. la config cette fois est refusée

    [2024-01-31 14:00:17] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=042A, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=94BE, DstAddrMode=02, DstAddr=0000
    [2024-01-31 14:00:17]   FCF=0C/General/Serv->Cli/ManufCode=117C, SQN=03, cmd=07/Configure Reporting Response
    [2024-01-31 14:00:17]   Status=86/Unsupported attribute, Attr=0000, Dir=00

Voila un nouveau modele. Je ne touche que PM25 et je te laisse verifier le VOC toutes les 30mins

ATTENTION CORRECTION
[VINDSTYRKA_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14112130/VINDSTYRKA_IKEAofSweden.zip)

**Comment by tcharp38** [comment]
Attention j'avais envoyé un mauvais modele. Reprendre le dernier lien

**Comment by gegedme** [comment]
[AbeilleLogs-240131 (4).tar.gz](https://github.com/KiwiHC16/Abeille/files/14112939/AbeilleLogs-240131.4.tar.gz)
derniers logs

**Comment by tcharp38** [comment]
Ca m'a l'air bon.
Tu me dira si les 2 remontent bien toutes les 30mins

**Comment by gegedme** [comment]
ok. je surveille tout ça

**Comment by gegedme** [comment]
yep. c'est bon pour le PM2.5 et le VOC.
relevé toutes les 30 minutes
en revanche, la température n'a pas changé.
toutes les informations sont passées à 30 minutes ?

**Comment by gegedme** [comment]
ah.... si . 
la température vient de changer

**Comment by tcharp38** [comment]
Je crois que la temp c'est max toutes les 10mins.
Ça n'est pas ce que tu observe s ?

**Comment by gegedme** [comment]
Quelque chose comme ça.
Merci .

**Comment by tcharp38** [comment]
Donc sauf si toi tu vois un truc qui manque ou qui reste à corriger, on peut fermer ce sujet et je pousse une beta avec les dernieres modifs.
A toi de me dire

**Comment by gegedme** [comment]
On fait comme ça 
Merci encore pour ton aide

**Comment by gegedme** [comment]
super travail !!!!
merci pour ton aide
