### ISSUE TITLE
Remplacement équipement

### ISSUE THREAD

**Issue by PaTiTan** [KiwiHC16/Abeille#2683]
Bonjour, 

J'ai un aqara door sensor HS (qui fait une longue suite de clignotement) et je souhaiterai le remplacer.

J'ai ajouter un nouvel équipement identique et quand je les sélectionne et clique sur "remplacer", j'ai : Uncaught TypeError: Cannot read properties of undefined (reading 'jsonId')

Rien ne se passe, les 2 équipements sont toujours là.

Ruche zigate en version 0004-0323, 54 capteurs sur 3 zigates. plugin abeille stable en version 2024-01-01 01:00:32
Merciiii

**Comment by tcharp38** [comment]
Salut @PaTiTan 
Désolé pour le temps de réponse.

Je vois que tu fais fasse à un souci javascript.
Je te suggere de basculer sur la beta du moment. Elle est + avancée que la stable et c'est sur celle la que je bosse.

Tu utilises 3 Zigates ?
Ouah. Pas rencontré beaucoup d'utilisateurs de ce mode.

Maintenant côté "remplacement".. garde un truc en tete:
On n'a pas de solution aujourd hui sur Zigate pour virer un equipement du reseau. Il doit sortir de lui meme. Donc si il est HS.. ben il occupe toujours une place dans la memoire Zigate et doit donc apparaitre sur la page réseau.

**Comment by tcharp38** [comment]
Salut @PaTiTan 

La 240124-BETA-1 sera dispo demain si tu veux retester ton cas.
J'ai trouvé qq soucis.

**Comment by PaTiTan** [comment]
Passage en béta, ça fonctionne parfaitement. 
Merci à toi pour ta réactivité !!!

**Comment by tcharp38** [comment]
Parfait !

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
