### ISSUE TITLE
Support interrupteur IKEA (dimmer) RODRET E2201 (id = RODRETDimmer, IKEAofSweden)

### ISSUE THREAD

**Issue by kromer29** [KiwiHC16/Abeille#2684]
Bonjour,
Lors de l'inclusion de l'interrupteur ci-dessus, ce dernier n'est pas connu.

Voici le fichier créer par l'assistant de découverte:
[discovery-RODRETDimmer_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14002115/discovery-RODRETDimmer_IKEAofSweden.zip)

Edit: petite précision, c'est un interrupteur 2 boutons équipé d'une pile LR03 et ils m'ont l'air de remplacer les anciens modèles E1743

Bonne soirée :-)

**Comment by tcharp38** [comment]
Salut @kromer29 
Il me faut une image PNG sans arriere plan pour ce modele STP

**Comment by kromer29** [comment]
OK, je fais ça en rentrant du boulot 👍

**Comment by kromer29** [comment]
![IKEA RODRET E2201](https://github.com/KiwiHC16/Abeille/assets/155495806/dd14ec81-8119-4c1a-9cd3-bc1f524c106b)
Voilà ;-)
[IKEA RODRET E2201.zip](https://github.com/KiwiHC16/Abeille/files/14014848/IKEA.RODRET.E2201.zip)


Bonne soirée.

**Comment by tcharp38** [comment]
Inclut pour la prochaine beta.
Tu as pu tester le modele ?

**Comment by kromer29** [comment]
Je ne crois pas que tu m'en ai poussé un 😅

**Comment by tcharp38** [comment]
ouahhh :)
Je suis fatigué. Je m'enmèle les pinceaux.

A decompresser dans Abeille/core/config/devices
[RODRETDimmer_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14037456/RODRETDimmer_IKEAofSweden.zip)

puis redemarrer demon
refaire inclusion

**Comment by kromer29** [comment]
Bonsoir,
Je viens tout juste de tester ton modèle. Le On/Off fonctionne très bien, par contre je n'ai pas possibilité de dimmer en plus ou en moins mes lampes inclusent dans Abeille contrairement à mes interrupteurs modèle E1743 (sur une réinit avec juste un appairage lampe-interrupteur sans passer par jeedom le dimmage fonctionne bien).
Ceci dit, à mon niveau et pour ce que je veux piloter avec cet interrupteur le On/Off me suffit.
Cependant, si tu veux faire des ajustements sur le modèle, je peux te faire des essais ;-)

**Comment by tcharp38** [comment]
Le On/Off fonctionne en tant que commande de groupe alors c'est ca ?

Je suppose que la diff enter on/off et dimmer c'est le temps d'appui.
Peux tu du coup en notant l'heure
-on
- off
- faire un appui long +
- appui long -

Les commandes du modele actuel n'ont aucun interet

**Comment by kromer29** [comment]
Bonjour,
Oui, j'utilise tout mes interrupteurs en commande de groupe avec mes lampes et prises.
J'ai fait la manip que tu m'a demandé avec l'appui sur 'on' à 21H14 et 30 secondes .
Et en appuyant longuement, il y a des 'Unknown Jeedom command'.

[AbeilleLogs-240126.tar.gz](https://github.com/KiwiHC16/Abeille/files/14069047/AbeilleLogs-240126.tar.gz)

**Comment by tcharp38** [comment]
Salut

Ok je vois des retours

    [2024-01-26 21:14:40][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/1445/01
    [2024-01-26 21:14:40][DEBUG] :   Unknown Jeedom command logicId='Up-Down'
    [2024-01-26 21:14:40][DEBUG] :   Unknown Jeedom command logicId='01-0008-cmd05'
    [2024-01-26 21:14:43][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/1445/01
    [2024-01-26 21:14:43][DEBUG] :   Unknown Jeedom command logicId='Up-Down'
    [2024-01-26 21:14:43][DEBUG] :   Unknown Jeedom command logicId='01-0008-cmd07'
    [2024-01-26 21:14:45][DEBUG] : deamon_info(): {"state":"ok","launchable":"ok","launchable_message":""}
    [2024-01-26 21:14:45][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/1445/01
    [2024-01-26 21:14:45][DEBUG] :   Unknown Jeedom command logicId='Up-Down'
    [2024-01-26 21:14:45][DEBUG] :   Unknown Jeedom command logicId='01-0008-cmd01'
    [2024-01-26 21:14:47][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/1445/01
    [2024-01-26 21:14:47][DEBUG] :   Unknown Jeedom command logicId='Up-Down'
    [2024-01-26 21:14:47][DEBUG] :   Unknown Jeedom command logicId='01-0008-cmd07'

On dirait que
- 01-0008-cmd05 => click HAUT long
- 01-0008-cmd01 => click BAS long

Voila un nouveau modele à tester
[RODRETDimmer_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14073404/RODRETDimmer_IKEAofSweden.zip)

**Comment by kromer29** [comment]
Bonsoir,
Je viens de faire le test avec le nouveau modèle, c'est comme avant on/off ok mais pas de dimmage de la lampe.

j'ai refais le même test que celui que tu m'avais demandé la 1ère fois.
L'appui sur on était à 22:29:00.
là, sur chaque appui long en '+' ou en '-' j'ai le message 'Abeille1, Type=8085/Unknown-8085 (unused).' qui apparait après environ 1 seconde d'appui sur '+' ou '-' et il réapparait après le relâchement de la commande.
[AbeilleLogs-240127.tar.gz](https://github.com/KiwiHC16/Abeille/files/14073888/AbeilleLogs-240127.tar.gz)

**Comment by tcharp38** [comment]
Ok je comprends le souci et je réalise qu'on est dans le monde galère du détournement initial des "remotes".

En gros une telecommande n'est pas concue pour recevoir des ordres mais au contraire les envoyer.
Dans la plupart des cas, elle envoie ses commandes vers un groupe zigbee particulier. Donc meme si Jeedom etait par terre, tant que le reseau Zigbee fonctionne, les commandes passent toujours. Aucun lien avec Abeille en si ce n'est que ce dernier devrait permettre de changer le groupe.

Donc pour un ON ou OFF c'est standard pour tous les devices. Des lors qu'ils sont dans le groupe ils comprennent ce qu'il receoivent directement de la remote.
Pour click long + ou -.. la  ca n'est pas le cas. Ta commande Ikea ne pourrait donc "dimmer" que des devices Ikea concus pour ca.

Tu cherches à dimmer quoi ?

**Comment by kromer29** [comment]
Bonjour,
Ce que je cherche à dimmer, ce sont justement des lampes ikea dont des modèles comme celui que tu as fait l'autre jour (la led2103g5 #2680).
Pour essai, j'ai réinitialiser l'interrupteur dont-il est question dans ce sujet et 1 lampe du même modèle que celui du #2680.
J'ai synchronisé les 2 ensembles, donc en dehors du réseau de la zigate et là, le on/off, dimmage plus et moins fonctionne.
Ensuite, après inclusion dans le réseau de la zigate puis appairage de l'interrupteur et de la lampe, on/off ok mais dimmage via l'interrupteur ko (mais possible via jeedom).
Ensuite, j'ai lié ma lampe à un autre modèle d'interrupteur (genre les télécommande 5 boutons d'ikea, ou les 2 boutons (les E1743)), le on/off et le dimmage via la télécommande fonctionne.

Ça ressemble au même soucis que j'ai avec les télécommande 5 boutons d'ikea. Dès que le couple interrupteur-lampe est inclus dans le réseau de la zigate, je ne peux plus faire varier la température de couleur de mes lampes via les flèches de la télécommande.
Je pense que ça doit être le même genre de problème entre ces 2 modèles. L'inclusion semble leur faire perdre quelques fonctions 🤔

**Comment by tcharp38** [comment]
Salut
Tu peux essayer de supprimer les lignes suivantes du modele et refaire une inclusion

            "Bind 01-0008-ToZigate": {
                "use": "act_zbBindToZigate",
                "params": "ep=01&clustId=0008",
                "execAtCreation": "yes"
            },

Dans ce cas aucune info autre que la batterie ne remonte à Abeille et peut etre que ca va repondre à ton point si et seulement si tes LEDs comprennent ces commandes de dimming. Donc a tester.
Mais ca n'est pas du tout le mode de fonctionnement que je recommande. Ca n'est pas portable à tous les devices.
Les cas d'utilisation des telecommandes sont vraiment trop variés et jusque la Abeille gere ca au cas par cas. Pas propre

**Comment by kromer29** [comment]
Bonsoir,
Je n'ai pas pu tester ta manip avant ce soir, mais maintenant c'est chose faite.
Résultat, en enlevant les lignes indiquées et en refaisant l'inclusion le dimmage des LEDs (ma lampe modèle 'led2103g5') via la télécommande fonctionne et la lampe reste pilotable par jeedom également.
Comme tu l'avais indiqué, les appuis sur la télécommande ne remonte plus dans jeedom ;-)

**Comment by tcharp38** [comment]
Salut

Ca confirme donc mes soupcons.
Je ne sais pas quelle strategie adopter pour les telecommandes

- soit elle est juste dans le reseau et en dehors de la batterie rien ne remonte à Jeedom. Mais du coup aucun scenario n'est utilisable, et ca ne peut fonctionner qu'entre equipements prevus pour ca (donc meme marque)
- soit tout remonte à Jeedom et en fonction de l'info on commande tel ou tel equipement ou groupe. Ici les scenaris sont utilisables, tout comme ca permet de relier n'importe quel equipement à la telecommande

En ecrivant ces lignes je me dis que le + serieux est le cas 2.
T'en penses quoi ?

**Comment by kromer29** [comment]
Je pense comme toi.

Cependant, j'ai juste une télécommande que j'ai besoin de pouvoir utiliser directement pour dimmer. Les 2 autres télécommandes du même modèle, ce n'est pas nécessaire.

Donc, pour le coup, je pensais dupliquer le modèle en le renommant pour le reconnaître facilement, supprimer les lignes que tu m'as indiqué et forcer ce nouveau modèle sur l'interrupteur qui doit garder la possibilité de dimmer.
Pour toi, ça fonctionne comme approche ?

**Comment by tcharp38** [comment]
Alors on peut dire que le modele par defaut est celui qui renvoi tout à Jeedom
Mais je peux pousser un modele supplementaire (methode deja pre testée) que tu choisis via l'onglet 'avancé'.. => forcer un modele

Ca me semble un bon compromis.
Ca t irait ? Et partant pour tester jusqu' au bout ?

**Comment by kromer29** [comment]
Je suis d'accord pour tester. De toute façon, c'est ce que je comptais faire et ce sera beaucoup plus sûr si les modifs viennent de toi 😁😉

**Comment by tcharp38** [comment]
Voila la variante que j'ai ajouté
[RODRETDimmer_IKEAofSweden-direct.zip](https://github.com/KiwiHC16/Abeille/files/14166274/RODRETDimmer_IKEAofSweden-direct.zip)

A mettre avec le modele par defaut
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/878e14a6-4d37-4cea-b207-deb00d520085)

Via l'onglet avancé, tu dois pouvoir "forcer" ce modele avec la variante "direct".
A voir si il ne manque pas des choses dans le process.

Mais deja peut on verifier qu'avec le modele par defaut on a toutes les infos qui remontent à Jeedom ?

**Comment by kromer29** [comment]
Bonjour,
Désolé pour ne pas avoir fait de tests plus tôt, le temps défile trop vite en semaine.
J'ai essayé le modèle par défaut, tout à l'air de bien remonté dans jeedom vu dans les logs, par contre, quand je veux forcer le modèle sur le 'direct', ça n'a pas l'air de vouloir changer de modèle. Tout continu à remonter dans jeedom et abeille continu à me dire que le modèle utilisé est celui par défaut.
[AbeilleLogs-240211.tar.gz](https://github.com/KiwiHC16/Abeille/files/14232659/AbeilleLogs-240211.tar.gz)

**Comment by tcharp38** [comment]
Salut @kromer29 
J'ai poussé de gros changements dans la derniere beta concernant les modeles forcés.
MAIS .. je réalise que pour un équipement sur batterie, une fois forcé, il te faut quand meme provoquer une reinclusion pour qu'il se base sur le modele forcé et non plus sur le modele auto-detecté.

Tu peux basculer sur la beta du jour ?
Forcer le modele direct
refaire une inclusion
et me filer les logs ?

**Comment by kromer29** [comment]
Bonjour @tcharp38,

J'ai tenté la manip que tu m'as indiqué avec la dernière beta (240213-BETA-1).
Cependant, au niveau de jeedom lors de la réinclusion j'ai le message suivant: <html><body>

  | getDeviceModel(): Unexpected alternate sig 'RODRETDimmer_IKEAofSweden-direct'
-- | --



</body>
</html>

De plus, j'ai encore les commandes up-long et down-long qui remonte dans jeedom.

J'ai aussi quelque chose de bizarre dans l'onglet avancé de mon équipement. Sur la ligne Modèle d'équipement, il est indiqué quee j'utilise bien le modèle direct, mais si je vais dans 'forcer modèle' il m'indique que c'est l'autre modèle qui est actuellement utilisé (voir captures d'écrans).
Je te mets ici les logs lors de l'essai effectué à [2024-02-16 21:34:16].
[AbeilleLogs-240216.tar.gz](https://github.com/KiwiHC16/Abeille/files/14315904/AbeilleLogs-240216.tar.gz)
![RODRET](https://github.com/KiwiHC16/Abeille/assets/155495806/8ef3fff7-c915-40a8-9f81-79a6dec45418)
![RODRET forçage modèle](https://github.com/KiwiHC16/Abeille/assets/155495806/5b554900-dafc-44b7-8ecb-1cbf55eb42d5)

**Comment by tcharp38** [comment]
Salut @kromer29 
En meme temps je faisais des essais de mon coté et j'ai trouvé d'autres failles.
Du coup il faut que je pousse une nouvelle beta pour le support de ces "variantes".
C'est chose faite (240216-BETA-1) qui sera dispo demain.

Une fois que tu as basculé dessus je te laisse refaire la manip.

**Comment by kromer29** [comment]
Bonsoir,
J'ai refait la manip après avoir basculé sur la nouvelle beta, cette fois le forçage de modèle est bien pris en compte (mais l'inclusion reste nécessaire pour la prise en compte).
avec le modèle 'direct', je ne vois plus de remontée des infos de l'interrupteur dans jeedom et le dimmage fonctionne bien (via l'interrupteur)
j'ai lancé l'inclusion à [2024-02-17 22:25:34]
[AbeilleLogs-240217.tar.gz](https://github.com/KiwiHC16/Abeille/files/14320263/AbeilleLogs-240217.tar.gz)
PS: j'ai fais les essais en pilotant une lampe avec l'interrupteur, il y a donc toutes les remontées de la lampe dans les logs. J'espère que ça ne va pas rendre les logs trop illisibles :-/

**Comment by tcharp38** [comment]
Salut
Du coup pour toi il reste quoi à compléter ou corriger ?

**Comment by kromer29** [comment]
Bonjour,

Pour moi, ça me semble bon.
Cependant, si réalisable, pour le modèle par défaut, ce serait possible de voir les infos des appuis sur 'on' et 'off' qui remonte sur jeedom dans le même genre que pour le 'up long' et le 'down long'?

Pour mes interrupteurs qui n'ont pas besoin d'être sur le modèle direct, ça pourrait éventuellement me permettre de déclencher au moins 4 scénarios différents selon la façon d'appuyer dessus :-D

Et peut-être voir pour cette erreur:
[2024-02-17 18:47:35] Abeille1, Type=8085/Unknown-8085 (unused)
Elle survient dès le relâchement des boutons de l'interrupteur.

Merci pour ton super boulot en tout cas :-)

**Comment by tcharp38** [comment]
Salut

Ok on va bosser sur le modele par defaut du coup.

> Et peut-être voir pour cette erreur:
> [2024-02-17 18:47:35] Abeille1, Type=8085/Unknown-8085 (unused)

Ca n'est pas une erreur. Ce message est inutilisé.

Tu peux tenter avec ce modele
[RODRETDimmer_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14330431/RODRETDimmer_IKEAofSweden.zip)

sinon peux tu faire ON ou OFF
noter l'heure
et me filer un package de logs ?.

**Comment by kromer29** [comment]
Bonsoir,
Je viens de faire la mise à jour du modèle et de faire un 'on' à 22:11:40 et un 'off' à 22:11:50.
Voici les logs.
[AbeilleLogs-240219.tar.gz](https://github.com/KiwiHC16/Abeille/files/14336934/AbeilleLogs-240219.tar.gz)

**Comment by tcharp38** [comment]
Ok vu

    [2024-02-19 22:11:42] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C6BE, DstAddrMode=02, DstAddr=0000
    [2024-02-19 22:11:42]   FCF=11/Cluster-specific/Cli->Serv, SQN=0A, cmd=01/On
    [2024-02-19 22:11:42] Abeille1, Type=8095/Unknown-8095 (unused).
    [2024-02-19 22:11:52] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0006, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=C6BE, DstAddrMode=02, DstAddr=0000
    [2024-02-19 22:11:52]   FCF=11/Cluster-specific/Cli->Serv, SQN=0B, cmd=00/Off
    [2024-02-19 22:11:52] Abeille1, Type=8095/Unknown-8095 (unused).

Retente avec ce modele

[RODRETDimmer_IKEAofSweden.zip](https://github.com/KiwiHC16/Abeille/files/14350220/RODRETDimmer_IKEAofSweden.zip)

**Comment by kromer29** [comment]
Bonsoir,

Je viens d'essayer ton nouveau modèle, sur le widget les 4 infos se valident bien.
Pour les logs, voici les moments ou j'ai fait les manips ;-)
22:11:59 réinclusion de l'interrupteur
22:15:30 appui sur 'on'
22:15:40 appui sur 'off'
[AbeilleLogs-240220.tar.gz](https://github.com/KiwiHC16/Abeille/files/14351233/AbeilleLogs-240220.tar.gz)

Bonne soirée.

**Comment by tcharp38** [comment]
Donc c est tout bon pour toi ou il reste qqch a creuser ?
Bonne soirée

**Comment by kromer29** [comment]
Pour moi, c'est tout bon. Le modèle direct est impeccable et celui-ci devrait me permettre de servir de déclencheur à plusieurs scénarios 😁.
Tu as encore fait un super boulot 😉.

Bonne soirée.

**Comment by tcharp38** [comment]
Ok super.
Un de moins.
Tout sera dans la prochaine beta.. et donc la prochaine stable que j'espere sortir dans les prochaines semaines.

Je ferme le sujet

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
