### ISSUE TITLE
Problème ré-installation abeille

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2686]
Salut,
J'ai changé de Raspberry suite à un problème matériel... Et je galère avec Abeille : les équipements qui sont tous passés en time out, les points d'accès relais (prises Blitzwolf SHP13) sont passés en NO-ACK... J'en ai supprimé une, impossible de la ré-associer...

![image](https://github.com/KiwiHC16/Abeille/assets/68732573/ef8fede1-b70b-4feb-8b69-e0342f1084b0)

une idée???

Je t'ai mis le log où j'essaie de ré-associé la prise)...

[AbeilleLogs-240205.tar.gz](https://github.com/KiwiHC16/Abeille/files/14169575/AbeilleLogs-240205.tar.gz)

Merci d'avance

**Comment by tcharp38** [comment]
Salut
Je ne vois rien qui me donne de piste la.
Tu as changé quoi par quoi ?
Tu as utilisé les memes ports USB ? Je soupconne un parasitage de la Zigate pour expliquer ce qui me semble inexplicable.
Pb de perturbation electrique ? Magnetique ?

**Comment by fable73** [comment]
J'ai changé le RPI et le SSD. J'avais des soucis pour le redémarrer en cas de coupure de courant.
La Zigate est une Pizigate => branchement sur le GPIO... J'avais commandé une autre Pizigate, mais mauvais FW
Je vais creuser ce week-end calmement... je te tiens au courant

**Comment by tcharp38** [comment]
Le SSD est connu pour etre gros generateur de parasites. J'avais vu beaucoup de sujets sur RPI4 + SSD.

Regarde ce sujet par ex
https://github.com/KiwiHC16/Abeille/issues/1110

ou celui la
https://github.com/KiwiHC16/Abeille/issues/1107

**Comment by fable73** [comment]
Bon je m'en suis sorti... Mais j'ai été obligé de tout supprimer y compris Abeille de tout refaire calmement....
Pour l'histoire : 
Au départ, un RPI qui démarre avec difficulté... en final c'était l'électronique du boitier du SSD mSata qui lanchait...
J'avais une PiZigate V1 avec antenne externe... Passé à une V2 sans antenne mais avec le mauvais FW... => je l'ai flashé au bon...
Avec ça, j'ai re-installé Jeedom de zéro sur une SD, et en récupérant une sauvegarde,  impossible de me connecter à mes prises pourtant à 10cm du RPI... à un moment, je suis repassé sur la pizigate V1 j'ai bougé l'antenne => là tout se reconnecte.... Je descend le bordel à la cave, trop content... et à nouveau les prises en No-Ack... j'ai essayé de re-bouger l'antenne, par moment ça se reconnectait, puis ça repartait direct...
Du coup, j'ai installé un Jeedom vierge et là aucun problème d'association sur ma Pizigate V2 (sans antenne externe)....
Donc il y a un truc qui s'est corrompu qque part, mais j'ai pas mis la main dessus...
Comme j'ai tout supprimé, obligé de tout refaire (design, scénario, etc...)... Par contre tout remarche nickel avec un nouveau boitier SSD mSata.... branché sur USB2... en ayant lu tes sujets... Merci!!

**Comment by fable73** [comment]
Soldé pour moi

**Comment by tcharp38** [comment]
Ok, tout n'est pas compris mais content que tu sois retombé sur tes pattes.
