### ISSUE TITLE
Problème commande SetTilt - BSO Profalux

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2687]
Hello @tcharp38 

Je suis en train de réinitialiser mes volets et BSO en prévision du passage de ma Zigate v1 en optiPDM.
Comme j'ai vu que tu avais modifié les modèles des BSO (suppression des cmd lift et setlift, en doublon avec level et setlevel), j'ai appliqué le nouveau modèle à l'un de mes BSO (Cuisine) et j'ai un souci avec le tilt, ca ne fonctionne plus : 

Tilt non fonctionnel nouveau modèle : 
```
0591|[2024-02-07 14:47:14] -- execute([Cuisine][AB BSO Cuisine][Set Tilt], type=action, options={"slider":"45","user_login":"admin","user_id":"1"})
0592|[2024-02-07 14:47:41] Zg1 status: idle, Pri1=0, Pri2=0, Pri3=0
0593|[2024-02-07 14:47:41] Tempo status: count=0
```

Tilt fonctionnel avec ancien modèle 
```
0606|[2024-02-07 14:48:10] -- execute([Salon][AB BSO Panoramique][Set Tilt], type=action, options={"slider":"46","user_login":"admin","user_id":"1"})
0607|[2024-02-07 14:48:10]   updateField(): Updated 'EP=01&lift=#cmdInfo_Lift_#&inclinaison=#slider#&duration=10'
0608|[2024-02-07 14:48:10]   updateField(): To 'EP=01&lift=1&inclinaison=46&duration=10'
0609|[2024-02-07 14:48:10] -- Msg sent: {"topic":"CmdAbeille1/8AA9/moveToLiftAndTiltBSO","payload":"EP=01&lift=1&inclinaison=46&duration=10"}
0610|[2024-02-07 14:48:10] -- Will process cmdAction with cmd Info Ref if exist: Tilt
0611|[2024-02-07 14:48:10] -- cmdAction with cmd Info Ref: Tilt with value slider: 46
0612|[2024-02-07 14:48:10] Msg from 'xToCmd': {"topic":"CmdAbeille1/8AA9/moveToLiftAndTiltBSO","payload":"EP=01&lift=1&inclinaison=46&duration=10"}
0613|[2024-02-07 14:48:11]   processCmd({"moveToLiftAndTiltBSO":"1","addressMode":"02","priority":2,"dest":"Abeille1","address":"8AA9","destinationEndpoint":"01","lift":"1","inclinaison":"46","duration":"10"})
0614|[2024-02-07 14:48:11]   command moveToLiftAndTiltBSO
```

Les logs complets :
[AbeilleLogs-240207.tar.gz](https://github.com/KiwiHC16/Abeille/files/14194573/AbeilleLogs-240207.tar.gz)

Jeedom : 4.3.22
Abeille : 240201-BETA-1

La fonction Lift devait servir à cela :)
Merci pour ton aide !
Xav

**Comment by tcharp38** [comment]
Salut @Xav-74 
Je vois que cette commande 'Cuisine][AB BSO Cuisine][Set Tilt]' semble juste... disparaitre et n etre meme pas executée.
Je creuse

**Comment by Xav-74** [comment]
Top merci !
Dispo en ce moment donc n'hésites pas ;)
Dès que tout est OK, je bascule en optiPDM enfin (sic!)

**Comment by tcharp38** [comment]
Pas un fix mais juste pour test.
A decompresser dans Abeille/core/class
[AbeilleCmd.class.php.zip](https://github.com/KiwiHC16/Abeille/files/14212210/AbeilleCmd.class.php.zip)

puis redemarrer Abeille
refaire un test tilt qui marche pas
et me filer les logs STP

**Comment by Xav-74** [comment]
Alors bizarre, sur le premier test j'ai eu ca :

```
2221|[2024-02-08 20:21:13] -- execute([Cuisine][AB BSO Cuisine][Set Tilt], type=action, options={"slider":"45","user_login":"admin","user_id":"1"})
2222|[2024-02-08 20:21:20] Msg from 'xToCmd': {"topic":"CmdAbeille1/C3F8/readAttribute","payload":"ep=01&clustId=0008&attrId=0000"}
2223|[2024-02-08 20:21:20]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
2224|[2024-02-08 20:21:20]   processCmd({"readAttribute":"readAttribute","name":"readAttribute","priority":2,"dest":"Abeille1","ep":"01","clustId":"0008","attrId":"0000","addr":"C3F8"})
2225|[2024-02-08 20:21:20]   readAttribute: ClustId=0008, AttrList=0000
2226|[2024-02-08 20:21:20]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0100, Payload=02C3F80101000800000000010000, Addr=C3F8, AddrMode=02)
2227|[2024-02-08 20:21:20]     Zg 1 queues: Pri1=0, Pri2=1, Pri3=0
```
EDIT : en fait non le C3F8, c'est un autre volet

Puis les suivants uniquement ca : 

```
2266|[2024-02-08 20:21:30] -- execute([Cuisine][AB BSO Cuisine][Set Tilt], type=action, options={"slider":"0","user_login":"admin","user_id":"1"})
```

[AbeilleLogs-240208.tar.gz](https://github.com/KiwiHC16/Abeille/files/14213751/AbeilleLogs-240208.tar.gz)

**Comment by tcharp38** [comment]
Je ne vois pas la trace du commentaire que j'ai ajouté mais je comprends la situation.

Avec ce code la tu dois avoir une erreur générée.
Tu peux confirmer ça déja ?

Pour Abeille/core/class
[AbeilleCmd.class.php.zip](https://github.com/KiwiHC16/Abeille/files/14220410/AbeilleCmd.class.php.zip)
+ redemarrer
+ refaire Set Tilt => ERREUR
+ me filer le package de logs

**Comment by Xav-74** [comment]
Cette fois j'ai bien l'erreur : 

```
3096|[2024-02-09 11:25:56] -- execute([Cuisine][AB BSO Cuisine][Set Tilt], type=action, options={"slider":"40","user_login":"admin","user_id":"1"})
3097|[2024-02-09 11:25:56]   updateField(): Updated 'EP=01&lift=#cmdInfo_Lift_#&inclinaison=#slider#&duration=10'
3098|[2024-02-09 11:25:56]   updateField(): To 'EP=01&lift=#cmdInfo_Lift_#&inclinaison=40&duration=10'
3099|[2024-02-09 11:25:56] -- Msg sent: {"topic":"CmdAbeille1/48B6/moveToLiftAndTiltBSO","payload":"EP=01&lift=#cmdInfo_Lift_#&inclinaison=40&duration=10"}
3100|[2024-02-09 11:25:56] Msg from 'xToCmd': {"topic":"CmdAbeille1/48B6/moveToLiftAndTiltBSO","payload":"EP=01&lift=#cmdInfo_Lift_#&inclinaison=40&duration=10"}
3101|[2024-02-09 11:25:56]   processCmd({"moveToLiftAndTiltBSO":"1","addressMode":"02","priority":2,"dest":"Abeille1","address":"48B6","destinationEndpoint":"01","lift":"#cmdInfo_Lift_#","inclinaison":"40","duration":"10"})
3102|[2024-02-09 11:25:56]   command moveToLiftAndTiltBSO
3103|[2024-02-09 11:25:56]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0530, Payload=0248B6010100080104021E0A0510110110030028000a, Addr=48B6, AddrMode=02
```

Et pour info le BSO qui était ouvert s'est fermé :) mais le tilt fonctionne
Il faut réussir à conserver la hauteur du lift.

[AbeilleLogs-240209.tar.gz](https://github.com/KiwiHC16/Abeille/files/14220548/AbeilleLogs-240209.tar.gz)

**Comment by Xav-74** [comment]
A mon avis pour les BSO, tu dois conserver les cmd Lift et Tilt.
Finalement c'est peut-être la partie Level à supprimer non ? A moins que les commandes up et down l'utilise ?
Pour ma part tous mes scénarios se basent sur Lift et Tilt pour gérer mes BSO

**Comment by tcharp38** [comment]
Ok parfait.
Du coup voila le modele BSO modifié
et une commande modifiée

[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14220657/BSO.zip)
[moveToLiftAndTiltBSO_Tilt.zip](https://github.com/KiwiHC16/Abeille/files/14220661/moveToLiftAndTiltBSO_Tilt.zip)

**Comment by tcharp38** [comment]
Ha concernant ton choix de garder lIft & tilt..
si j'ai viré lift c'est que c est redondant avec level sauf que ce dernier est standard Zigbee contrairement à lift qui est un truc proprietaire. Bref l 'idée etait de faire du menage dans les vérues.

**Comment by Xav-74** [comment]
Bien sûr je comprends ! Si ca marche avec Level c'est mieux en effet.
Je viens de mettre à jour les fichiers, réinitialiser mon BSO puis redémarrer du démon (pas nécessaire mais bon)

Le level n'est toujours pas conservé et j'ai l'erreur suivante : 
`Modele invalide. Commande info 'Level' n'existe pas.`

[AbeilleLogs-240209.tar.gz](https://github.com/KiwiHC16/Abeille/files/14220801/AbeilleLogs-240209.tar.gz)

**Comment by tcharp38** [comment]
Pourtant tu l'as bien cette commande "Level" n'est ce pas ?

**Comment by Xav-74** [comment]
Oui

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/a727ff52-52f0-4f87-bddc-1c06db49d378)

Par contre en y regardant de plus près, le lift allait de 1 à 254 et non de 0 à 100%
Cela ne vient pas de là mais ca permettra d'éviter un aller retour :)

**Comment by tcharp38** [comment]
Ok pigé.
Teste avec ca

[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14223403/BSO.zip)

Ok pour lift je m'attendais à un truc comme ca. Par contre je ne sais pas encore comment le traiter.

Tu as un retour du Tilt ?
Tu me donne un screenshot de ton equipement sur le dashboard ?

**Comment by tcharp38** [comment]
Bon en fait je pousse une beta (240209-BETA-1) pour tester demain.
Je veux nettoyer cette vieille partie donc dans le mode tu vas trouver un "Set Tilt 2" qui va remplacer le "Set Tilt" des que tu dis "OK"

**Comment by Xav-74** [comment]
Avec le dernier fichier ca fonctionne bien au detail près du level (0-100 vs 1-254)
J'ai d'abord fais un lift à 26 puis tilt à 46

```
2846|[2024-02-09 17:39:20] -- cmdAction with cmd Info Ref: Level with value slider: 26
2847|[2024-02-09 17:39:20]   processCmd({"name":"cmd-0008","priority":2,"dest":"Abeille1","addr":"48B6","ep":"01","cmd":"04","level":66,"duration":"01"})
2848|[2024-02-09 17:39:20]   cmd-0008: onOff=01, level=42, duration=0001
2849|[2024-02-09 17:39:20]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0081, Payload=0248B6010101420001, Addr=48B6, AddrMode=02)
2850|[2024-02-09 17:39:20]     Zg 1 queues: Pri1=0, Pri2=1, Pri3=0
2851|[2024-02-09 17:39:20] processCmdQueues(): ZgId=1, Pri=2/Idx=0, NPDU=0, APDU=0
2852|[2024-02-09 17:39:20]   sendCmdToZigate(Dest=Abeille1, addr=48B6, cmd=0081, datas=0248B6010101420001)
2853|[2024-02-09 17:39:20] processAcks(): msg={"type":"8000","net":"Abeille1","status":"00","sqn":"B3","sqnAps":"51","packetType":"0081","nPDU":"00","aPDU":"01"}
2854|[2024-02-09 17:39:20] processAcks(): msg={"type":"8012","net":"Abeille1","nPDU":"00","aPDU":"01"}
2855|[2024-02-09 17:39:20] processAcks(): msg={"type":"8011","net":"Abeille1","status":"00","addr":"48B6","sqnAps":"51"}
2856|[2024-02-09 17:39:20]   cmd={"dest":"Abeille1","addr":"48B6","cmd":"0081","datas":"0248B6010101420001","zgOnly":false,"status":"SENT","try":3,"sentTime":1707496760,"timeout":8,"sqn":"B3","sqnAps":"51","ackAps":true,"waitFor":"ACK"}
2857|[2024-02-09 17:39:20]   eq={"ieee":"20918A000006EB25","txStatus":"ok","jsonId":"BSO","jsonLocation":"Abeille","rxOnWhenIdle":false,"mainEp":"01","commands":{"Down":{"type":"action","subType":"other","logicalId":"01-0008-CmdDownClose","template":"","genericType":"FLAP_DOWN","configuration":{"topic":"setLevel","request":"Level=0&duration=0000&EP=01","visibilityCategory":"All"},"isVisible":1},"Up":{"type":"action","subType":"other","logicalId":"01-0008-CmdUpOpen","template":"","genericType":"FLAP_UP","configuration":{"topic":"setLevel","request":"Level=100&duration=0000&EP=01","visibilityCategory":"All"},"isVisible":1},"Stop":{"subType":"other","logicalId":"01-0008-CmdStopWithOnOff","template":"default","configuration":{"topic":"cmd-0008","request":"ep=01&cmd=07","visibilityCategory":"All"},"type":"action","isVisible":1},"Get Status":{"subType":"other","configuration":{"topic":"readAttribute","request":"ep=01&clustId=0006&attrId=0000"},"type":"action","logicalId":"readAttr-01-0006-0000"},"Status":{"type":"info","subType":"binary","template":"light","configuration":{"repeatEventManagement":"never","visibilityCategory":"All"},"logicalId":"0006-01-0000","genericType":"FLAP_STATE","isVisible":1,"nextLine":"after"},"Set Level":{"isVisible":1,"logicalId":"01-SetLevelVolet","subType":"slider","value":"Level","template":"","genericType":"FLAP_SLIDER","configuration":{"topic":"setLevelVolet","request":"Level=#slider#&duration=01","visibilityCategory":"All"},"type":"action"},"Get Level":{"subType":"other","configuration":{"topic":"readAttribute","request":"ep=01&clustId=0008&attrId=0000"},"type":"action","logicalId":"readAttr-01-0008-0000"},"Level":{"subType":"numeric","template":"shutter","configuration":{"minValue":"0","maxValue":"100","historizeRound":"0","calculValueOffset":"#value#/255*100"},"type":"info","logicalId":"0008-01-0000","unit":"%","genericType":"FLAP_STATE","isVisible":1,"nextLine":"after"},"Set Tilt":{"isVisible":1,"logicalId":"01-SetBSOTilt","subType":"slider","value":"Tilt","template":"","configuration":{"minValue":"0","maxValue":"90","topic":"moveToLiftAndTiltBSO","request":"EP=01&inclinaison=#slider#&duration=10&lift=#cmdInfo_0008-01-0000_#","visibilityCategory":"All"},"type":"action"},"Tilt":{"isVisible":1,"name":"Tilt","isHistorized":"1","subType":"numeric","invertBinary":"0","template":"","configuration":{"minValue":"0","maxValue":"90","historizeRound":"0","calculValueOffset":"","visibilityCategory":"All"},"type":"info","logicalId":"Tilt","unit":"deg"},"Identify":{"subType":"other","logicalId":"identify","template":"","configuration":{"topic":"identifySend","request":"EP=01&duration=0010","visibilityCategory":"additionalCommand"},"type":"action"},"Bind-0006-ToZigate":{"name":"Bind device to Zigate","subType":"other","logicalId":"bind-01-0006-ToZigate","template":"","configuration":{"topic":"bind0030","request":"addr=#IEEE#&ep=01&clustId=0006&destAddr=#ZigateIEEE#&destEp=01","execAtCreation":"Yes","execAtCreationDelay":9},"type":"action"},"SetReporting-0006-0000":{"subType":"other","logicalId":"configReport-01-0006-0000","configuration":{"topic":"configureReporting2","request":"ep=01&clustId=0006&attrType=10&attrId=0000","comment":"Full request ex: ep=01&clustId=0006&attrType=10&attrId=0000&minInterval=#MININTERVAL#&maxInterval=#MAXINTERVAL#&changeVal=#CHANGEVAL#","execAtCreation":"Yes","execAtCreationDelay":11},"type":"action"},"SetReporting-0008-0000":{"subType":"other","logicalId":"configReport-01-0008-0000","configuration":{"topic":"configureReporting2","request":"ep=01&clustId=0008&attrType=20&attrId=0000","comment":"Full request ex: ep=01&clustId=0008&attrType=20&attrId=0000&minInterval=#MININTERVAL#&maxInterval=#MAXINTERVAL#&changeVal=#CHANGEVAL#","execAtCreation":"Yes","execAtCreationDelay":11},"type":"action"},"Short-Addr":{"subType":"string","template":"badge","configuration":{"visibilityCategory":"Network"},"type":"info","logicalId":"Short-Addr","genericType":"GENERIC_INFO"},"IEEE-Addr":{"subType":"string","template":"badge","configuration":{"visibilityCategory":"Network"},"type":"info","logicalId":"IEEE-Addr","genericType":"GENERIC_INFO"},"Link Quality":{"subType":"string","template":"badge","configuration":{"visibilityCategory":"Network"},"type":"info","logicalId":"Link-Quality","genericType":"GENERIC_INFO"},"Online":{"subType":"binary","invertBinary":"0","template":"default","configuration":{"returnStateValue":"0","returnStateTime":"60","repeatEventManagement":"always","visibilityCategory":"Network"},"type":"info","logicalId":"online","genericType":"GENERIC_INFO"},"Time-Time":{"subType":"string","template":"","configuration":{"visibilityCategory":"Time"},"type":"info","logicalId":"Time-Time","genericType":"GENERIC_INFO"},"Time-TimeStamp":{"subType":"numeric","template":"badge","configuration":{"visibilityCategory":"Time"},"type":"info","logicalId":"Time-TimeStamp","genericType":"GENERIC_INFO"}}}
2858|[2024-02-09 17:39:20]   Removing cmd from queue (Pri=2/Idx=0/Count=1)
2859|[2024-02-09 17:39:20]   Queue count after=0
2860|[2024-02-09 17:39:45] -- execute([Cuisine][AB BSO Cuisine][Set Tilt], type=action, options={"slider":"46","user_login":"admin","user_id":"1"})
2861|[2024-02-09 17:39:45]   updateField(): Updated 'EP=01&inclinaison=#slider#&duration=10&lift=#cmdInfo_0008-01-0000_#'
2862|[2024-02-09 17:39:45]   updateField(): To 'EP=01&inclinaison=46&duration=10&lift=26'
2863|[2024-02-09 17:39:45] -- Msg sent: {"topic":"CmdAbeille1/48B6/moveToLiftAndTiltBSO","payload":"EP=01&inclinaison=46&duration=10&lift=26"}
2864|[2024-02-09 17:39:45] -- Will process cmdAction with cmd Info Ref if exist: Tilt
2865|[2024-02-09 17:39:45] -- cmdAction with cmd Info Ref: Tilt with value slider: 46
2866|[2024-02-09 17:39:45] Msg from 'xToCmd': {"topic":"CmdAbeille1/48B6/moveToLiftAndTiltBSO","payload":"EP=01&inclinaison=46&duration=10&lift=26"}
2867|[2024-02-09 17:39:45]   processCmd({"moveToLiftAndTiltBSO":"1","addressMode":"02","priority":2,"dest":"Abeille1","address":"48B6","destinationEndpoint":"01","lift":"26","inclinaison":"46","duration":"10"})
2868|[2024-02-09 17:39:45]   command moveToLiftAndTiltBSO
2869|[2024-02-09 17:39:45]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0530, Payload=0248B6010100080104021E0A0510110110031a2e000a, Addr=48B6, AddrMode=02)
2870|[2024-02-09 17:39:45]     Zg 1 queues: Pri1=0, Pri2=1, Pri3=0
```

Le retour de la cmd Tilt est bien OK. Voici le visuel (brut + widget)

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/07a058ed-a6b2-4e18-abbf-53d1bc96ab3b)

Pour la beta, tu la pousse maintenant ? ou demain seulement ?

**Comment by tcharp38** [comment]
Beta deja faite mais ne sera sur le market que demain

**Comment by Xav-74** [comment]
Zut ! Pas moyen de pousser ce soir ? Difficile de tester demain :p

**Comment by tcharp38** [comment]
C est surtout que je serai pas dispo d ici 30min pour du support.
Ca attendra du coup.

Et pour la beta, c'est Jeedom qui prend une version 1 fois par jour autour de minuit il me semble.

**Comment by Xav-74** [comment]
Ca marche pas de souci !
Mais pour info, tu peux forcer la beta via le market ;)

**Comment by tcharp38** [comment]
Oui tu peux la prendre directement par differents moyens mais c'est compliqué pour l'utilisateur final.

**Comment by Xav-74** [comment]
Ah non ! Ce que je voulais dire c'est que si tu cliques sur le bouton `Github beta` ca n'attend pas le passage auto de Jeedom. Ca pousse la version tout de suite et elle est dispo depuis le centre de mise à jour de Jeedom

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/b233d27f-0446-4802-9b25-25cd2bf09690)

**Comment by tcharp38** [comment]
Ha oui possible.
Mais tu dois faire une config speciale dans Jeedom pour acceder a Github.
Pas forcement simple

**Comment by Xav-74** [comment]
Oui juste activer Github dans config

**Comment by Xav-74** [comment]
Hello @tcharp38 

Beta installé ce matin. Mise à jour de mon BSO et test de la cmd Set Tilt 2
J'ai l'erreur suivante : 

```
0755|[2024-02-10 08:49:01] -- execute([Cuisine][AB BSO Cuisine][Set Tilt 2], type=action, options={"slider":"44","user_login":"admin","user_id":"1"})
0756|[2024-02-10 08:49:01]   updateField(): Updated 'ep=01&fct=profaluxSetTiltLift&cmd=00&message=#message#&tilt=#slider#'
0757|[2024-02-10 08:49:01]   updateField(): To 'ep=01&fct=profaluxSetTiltLift&cmd=00&message=#message#&tilt=44'
0758|[2024-02-10 08:49:01] -- Msg sent: {"topic":"CmdAbeille1/48B6/cmd-Private","payload":"ep=01&fct=profaluxSetTiltLift&cmd=00&message=#message#&tilt=44"}
0759|[2024-02-10 08:49:01] Msg from 'xToCmd': {"topic":"CmdAbeille1/48B6/cmd-Private","payload":"ep=01&fct=profaluxSetTiltLift&cmd=00&message=#message#&tilt=44"}
0760|[2024-02-10 08:49:01]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
0761|[2024-02-10 08:49:01]   processCmd({"cmd-Private":"cmd-Private","name":"cmd-Private","priority":2,"dest":"Abeille1","ep":"01","fct":"profaluxSetTiltLift","cmd":"00","message":"#message#","tilt":"44","addr":"48B6"})
0762|[2024-02-10 08:49:01]   profaluxSetTiltLift(net=, addr=48B6, ep=01, cmd=00)
0763|[2024-02-10 08:49:01] ERROR:   Valeur 'tilt' manquante pour profaluxSetTiltLift()
```

Merci pour ton aide

**Comment by tcharp38** [comment]
Pour info tester chez moi a mis à jour qq soucis pas simple a nettoyer.
Je suis dessus et je peux reproduire une partie de ton cas.
A suivre...

**Comment by Xav-74** [comment]
Ca marche merci pour ton aide !
Dispo pour les tests qd tu veux :p

**Comment by Xav-74** [comment]
Hello @tcharp38 

Installation de la dernière beta à l'instant (240213-BETA-1).
La commande Tilt 2 fonctionne de nouveau 👍 👍 
Je laisse ouvert car je vais devoir modifier les scénarios existants donc je vais devoir faire pas mal de nouveaux tests. Dès que tout est OK, je te redis et tu pourras remplacer la cmd `set tilt` par la cmd `set tilt 2`

Merci pour ta réactivité !

PI : j'ai basculé hier ma Ziagte en version OptiPDM 3.23 (0004-0323). Si j'oublie les galères avec Profalux (le plugin n'est pas en cause mais j'ai du procéder à la réinitialisation de 6 volets sur 11 GRRRrrr) tout s'est bien passé. Les premiers retours sont : 
 - meilleur routage : j'ai des modules sur piles qui on enfin basculé vers le routeur le plus proche (je n'y étais jamais parvenu avant)
 - meilleure réactivité des commandes : quasi plus aucune latence là ou parfois, je devais patienter entre 1 et 2s sur certains devices
 - ... à suivre

++

**Comment by Xav-74** [comment]
Suite des tests : 
J'ai remarqué un petit souci : la cmd info `Tilt` n'est pas mise à jour lors de l'utilisation de la cmd `Set Tilt 2`
Ex : mon BSO est à 90°. Je fais un set à 45°. Le tilt reste à 90°
Pourtant dans mon virtuel, les commandes sont bien liées

**Comment by tcharp38** [comment]
Salut
J'ai besoin d'un package de logs dans lequel tu fais ton "set tilt2".

A propos de ce nom d'ailleurs.. attention. Je l'ai appelé "2" pour conserver celui qui fonctionne mais je compte ne garder que le modele "set tilt 2" renommé en "set tilt" des qu'on a validé ça

**Comment by Xav-74** [comment]
> A propos de ce nom d'ailleurs.. attention. Je l'ai appelé "2" pour conserver celui qui fonctionne mais je compte ne garder que le modele "set tilt 2" renommé en "set tilt" des qu'on a validé ça

-> c'est bien comme cela que je l'avais compris ;)

Voici le package de logs : 
[AbeilleLogs-240214.tar.gz](https://github.com/KiwiHC16/Abeille/files/14279871/AbeilleLogs-240214.tar.gz)

**Comment by tcharp38** [comment]
Le retour d'info "Tilt" fonctionnait recemment ?

Tiens, tu peux me faire un discovery pendant que tu y es ?

**Comment by Xav-74** [comment]
Tant que je n'avais pas mis à jour les BSO via leur modèle, oui cela fonctionnait.

Voici le discovery :
[discovery.json](https://github.com/KiwiHC16/Abeille/files/14295141/discovery.json)

**Comment by tcharp38** [comment]
Donc le retour ne fonctionne pas non plus avec la vieille commande "set tilt" c'est ca ?

**Comment by Xav-74** [comment]
Bien vu ! J'aurais pu tester avant de répondre : cela fonctionne toujours avec la fonction Set Tilt
Voici les logs

[AbeilleLogs-240215.tar.gz](https://github.com/KiwiHC16/Abeille/files/14295318/AbeilleLogs-240215.tar.gz)

Edit : d'ailleurs je m'aperçois que cela met également à jour la cmd info Level. Ce qui n'est pas le cas avec la fonction set Tilt 2. Si tu arrives à le refaire également ce serait top

**Comment by tcharp38** [comment]
J'essaie toujours de comprendre comment ca pouvait fonctionner.
Mais si tu changes le tilt avec la telecommande, est ce que tu vois un retour sur Jeedom ?

**Comment by Xav-74** [comment]
Alors non ca ne met pas à jour sur Jeedom avec la tlc. En même temps j'appuie sur le bouton monter ou descendre pour jouer sur le tilt. Le volet fait des pas de 15° environ et- j'arrête à l'orientation voulu avec le stop. Si j'arrive à 90°, le volet monte ensuite. Si j'arrive à 0°, il descend. Je ne sais pas si je suis clair :p 

Pas de cmd type Get Tilt ?

**Comment by tcharp38** [comment]
C'est assez clair.
Donc pas de retour du tilt automatique. Pas surpris.
Mais tu dois avoir le retour du level par contre.

**Comment by tcharp38** [comment]
Je te laisse decompresser ce modele au bon endroit
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14295678/BSO.zip)

puis refaire
- soit une mise à jour via page equipement/avancé
- soit refaire une inclusion

puis un "Set tilt2"
et tu me files les logs 30sec apres

**Comment by Xav-74** [comment]
Nouveau modèle appliqué sur BSO Cuisine
Set Tilt 2 fait ensuite mais toujours pas de mise à jour du tilt

[AbeilleLogs-240215.tar.gz](https://github.com/KiwiHC16/Abeille/files/14295917/AbeilleLogs-240215.tar.gz)

**Comment by tcharp38** [comment]
Je cherche à trouver comment avoir un reporting automatique du "tilt".
Ce qui permettrait, si c 'est possible, d'avoir la vraie valeur du tilt toujours à jour, qu'il soit changé via la remote ou via Jeedom.

Tu peux retenter avec ce modele ?
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14298877/BSO.zip)

**Comment by Xav-74** [comment]
Et voilà les logs : 
 [AbeilleLogs-240215.tar.gz](https://github.com/KiwiHC16/Abeille/files/14298923/AbeilleLogs-240215.tar.gz)

Pas mieux pour le moment

**Comment by tcharp38** [comment]
Ha si il y a du mieux mais un retour qui semble un peu décalé.

Nouveau modele: j'ai ajouté "Tilt 2" qui va avec "Set Tilt 2"
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14299283/BSO.zip)

Le Set Tilt est censé etre entre 0 et 90 à priori d'apres le reverse engineering à droite à gauche
mais peut etre que le retour est 0 100

**Comment by Xav-74** [comment]
En effet, c'est bcp mieux avec le Tilt 2
Par contre, je te confirme l'écart entre le Set Tilt 2 et Tilt 2.
Ce qui est bizarre c'est que pour 90° j'ai bien un retour à 90° et idem pour 0°.
Par contre pour 25° j'ai 21°

[AbeilleLogs-240215.tar.gz](https://github.com/KiwiHC16/Abeille/files/14299474/AbeilleLogs-240215.tar.gz)

**Comment by tcharp38** [comment]
Le retour est celui du volet, sans aucune modif.
Mais du coup le "Tilt 2" se met à jour meme si tu joues avec la remote.

Je ne sais pas trop quoi faire la avec cet ecart

**Comment by Xav-74** [comment]
Je te confirme que j'ai bien le retour du tilt avec la tlc. Je vais creuser sur cet écart pour essayer de comprendre ;)
Je te redis si j'arrive à quelque chose.
En tous les cas, merci pour le boulot

**Comment by Xav-74** [comment]
Je viens de te pousser un mail qui devrait t'aider pour cette partie tilt ;)

**Comment by Xav-74** [comment]
Bon en fait les écarts sont vraiment minimes et à mon avis cela dépend de la précision du moteur !
Voici les tests que j'ai fait avec un pas de 10 : 


Set | Tilt
   0 | 0
 10 | 10
 20 | 21
 30 | 28
 40 | 41
 50 | 50
 60 | 61
 70 | 70
 80 | 81
 90 | 90


Pour confirmer ce que je disais sur la précisions du moteur, plus les mouvements sont grands, plus les écarts le sont aussi. Je n'ai pas toujours le même retour pour une demande de réglage identique !!
Ex : je suis à 90°, je demande 10°, j'obtiens 7°. Alors que dans mon premier test, le passage de 0° à 10° me donnait bien 10°.

Pour moi on peut en rester la ! Sauf si tu vois qqchose de plus dans ce que je t'ai envoyer par mail ;)
Je te laisse juste nettoyer le modèle BSO.json et me le renvoyer pour un dernier test avant bascule en beta ?

Merci pour tout

**Comment by tcharp38** [comment]
Je suis en ligne avec toi.
Donc le tilt remonté sera celui affiché.

Voila le dernier modele du coup.
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14302846/BSO.zip)

**Comment by Xav-74** [comment]
Tout est OK pour moi avec cette dernière version. Je clos le sujet.
Juste un détail sans importance, le min, le max et l'unité n'apparaissent pas pour le tilt avec ce dernier modèle ;)

Merci infiniment pour tout le boulot !

**Comment by tcharp38** [comment]
pas normal pour le min & max
je creuse

Comment as tu procédé pour changer de modele ? Via "mise à jour" de l'onglet avancé ?

**Comment by tcharp38** [comment]
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14309918/BSO.zip)

J'ai ajouté l'unité "deg"
Faire un "reset" et non pas "mise à jour"

Pour le min & max.. je vois pas car ca fonctionne pour moi.

**Comment by Xav-74** [comment]
Je viens de faire le reste. L'unité apparait bien mais pas le min max.
Ca vient peut-être de moi. Pas bien grave de toute façon car le set tilt a bien pris le 0 / 90.
Donc pas obligatoire pour le tilt lui même

**Comment by tcharp38** [comment]
Ha j'avais compris que c etait sur le "set tilt"
Sur le tilt... quel interet ? Ca n'est pas un slider, juste un nombre.

**Comment by Xav-74** [comment]
Oui tu as pas tort :)
Comme il y a les cases min max, j'avais du les remplir initialement et ca revenait à 0 a chaque reset.
Mais aucun intérêt en effet !!

**Comment by tcharp38** [comment]
Tu vois ou ces cases ?
Si c'est pas "slider" ca n'a aucun sens

**Comment by Xav-74** [comment]
Sur les commandes de l'équipement ! D'ailleurs ce devrait en effet être sur le `set tilt` et pas le `tilt` : 

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/a6b29cf3-9711-4fa0-b09f-f93d71fdd39c)

**Comment by tcharp38** [comment]
Bon point.
La il y a bug Abeille.

Le "set tilt" devrait afficher min & max vu que c'est un curseur. Definir sa plage fait du sens.

Par contre pour une commande info numerique.. a priori c'est aussi valide. J'imagine cette fois que c'est juste au cas ou l'affichage se fait sous forme de demi cercle.. pour donner les limites

**Comment by tcharp38** [comment]
A decompresser dans Abeille/desktop/php
[Abeille.zip](https://github.com/KiwiHC16/Abeille/files/14315337/Abeille.zip)

et recharger la page des commandes.
Ca le fait ?
