### ISSUE TITLE
Aucun affichage dans le graphique des liens

### ISSUE THREAD

**Issue by longyearbyen91** [KiwiHC16/Abeille#2688]
Bonjour, j'ai deux installations du plugins dans 2 logements différents (le mien et celui d'un membre de la famille)
L'un avec un NUC et l'autre avec un RPI4, avec la zigate v1 et l'adaptateur USB<->TTL (le vrai, pas la contrefaçon)
Aucun problème d'inclusion de device sur les deux install tout fonctionne.
Je vois bien les objets dans la table des liens.
Par contre dans les 2 install, le graphique des liens reste vide même en forçant interrogation du réseau.
Les 2 firmware sont en 0003-0323
Merci

**Comment by tcharp38** [comment]
Salut @longyearbyen91 
Ce souci est déja fixé dans la beta Abeille courante.
Je te suggere de basculer dessus car pas de visibilité sur la prochaine stable.
Ca te va ?

**Comment by longyearbyen91** [comment]
Hello @tcharp38 , j'ai testé sur un de mes Jeedom, ca marche nickel
Merci !

**Comment by tcharp38** [comment]
Cool.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)

**Comment by longyearbyen91** [comment]
Ma petite contribution envoyée par paypal

**Comment by tcharp38** [comment]
Merci bien.
