### ISSUE TITLE
Cmd "Level" non mise à jour sur BSO Profalux

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2689]
Hello @tcharp38 

Me revoilà avec mes BSO :)
Je viens de m'apercevoir de quelque chose : 
contrairement à mes volets Profalux, la commande info "level" de mes BSO ne se met pas à jour lorsqu'il bouge.
Si je fais une "getLevel" manuellement, cela fonctionne.

Voici les logs avec un test ce matin sur BSO Salon : 
- 9h59 : commande "Down" ->pas de mise à jour
- 10h00 : commande "Up" -> pas de mise à jour
- 10h01 : commande "SetLevel" à 74% -> passage du level à 29% ?? (sur les volets, cela passe souvent temporairement à une valeur aléatoire avant de prendre la bonne valeur une fois le mouvement terminé) mais pas dans le cas du BSO.
Une différence entre les 2 modèles ? 

[AbeilleLogs-240304.tar.gz](https://github.com/KiwiHC16/Abeille/files/14479064/AbeilleLogs-240304.tar.gz)

PS : j'ai mis ce BSO sous surveillance donc tu as le résumé dans le log monitor ;)

**Comment by tcharp38** [comment]
Salut

Fais une mise à jour avec ce modele.
[BSO.zip](https://github.com/KiwiHC16/Abeille/files/14480034/BSO.zip)

**Comment by Xav-74** [comment]
Trop rapide !
Adopté et validé 👍 

Merci
