### ISSUE TITLE
Commutateur intelligent Zigbee 4ch (id = TS0004, _TZ3000_u3oupgdy)

### ISSUE THREAD

**Issue by judeoleborgne** [KiwiHC16/Abeille#2692]
bonjour,
serait il possible d'ajouter le Commutateur WiFi intelligent Zigbee 4ch 8-35V, il n'est pas reconnu par l'abeille.

je joint le json que j'espere avoir reussi a faire ainsi qu'un png du produit.

un grand merci par avance pour votre travail.

<img width="311" alt="png 4 smart switch" src="https://github.com/KiwiHC16/Abeille/assets/40631786/4d8f3cd5-42aa-4060-8a5e-58fb8c28cc37">
[discovery-TS0004__TZ3000_u3oupgdy.zip](https://github.com/KiwiHC16/Abeille/files/14622789/discovery-TS0004__TZ3000_u3oupgdy.zip)

**Comment by tcharp38** [comment]
Salut @judeoleborgne 
Il est Wifi et Zigbee ?
Quoi qu'il en soit ton discovery est mal attaché.
D'autre part y a t'il une marque et un modèle correspondant ?

**Comment by judeoleborgne** [comment]
il est en zigbee, j'ai un installation rpi3 avec zigate et le plugin abeille.

il ressemble fort à ce modèle : [MHCOZY] ZG-0005-RF > Mhcozy 4 chan relay (undefined/undefined.json), qui est disponible dans l'option forcer le modèle, mais quand je souhaite appliquer il ne se passe rien.

l'article est le suivant : [https://fr.aliexpress.com/item/1005005671967332.html?spm=a2g0o.order_list.order_list_main.4.21ef5e5b1n7LJo&gatewayAdapt=glo2fra](url)

[discovery-TS0004__TZ3000_u3oupgdy.json](https://github.com/KiwiHC16/Abeille/files/14623082/discovery-TS0004__TZ3000_u3oupgdy.json)
[discovery-TS0004__TZ3000_u3oupgdy.zip](https://github.com/KiwiHC16/Abeille/files/14623083/discovery-TS0004__TZ3000_u3oupgdy.zip)

[https://github.com/KiwiHC16/Abeille/files/14623082/discovery-TS0004__TZ3000_u3oupgdy.json](url)
[https://github.com/KiwiHC16/Abeille/files/14623083/discovery-TS0004__TZ3000_u3oupgdy.zip](url)

**Comment by tcharp38** [comment]
Ok donc ton lien Aliexpress dit que c'est un ZG-005-RF

Néanmoins avec cette signature j'ai integré un ZG-003-RF déja present dans la beta.
Donc bascule sur la beta et refais une inclusion de ton device et dis moi ce que ca donne.

**Comment by judeoleborgne** [comment]
opération effectuée avec succès.

- activation des accès beta sur le site internet de jeedom dans la section profil
- ensuite sur le market de jeedom via l'instance jeedom on recherche le plugin abeille
- sans désinstaller le plugin on installe la version beta, les équipements inclus ne disparaissent pas.
- suppression du module et réintégration, il est reconnu et opérationnel. 

merci pour ta réactivité.

**Comment by tcharp38** [comment]
Donc tu confirmes que c'est un 003-RF et non pas 005-RF ?

**Comment by judeoleborgne** [comment]
<img width="688" alt="zg005rf" src="https://github.com/KiwiHC16/Abeille/assets/40631786/e8a7d589-0d5c-4f3a-af1e-319012a80d8d">

il est reconnu comme un 005-rf.

si on part du constat, sur le lien aliexpress, le 005-rf est la version 85-230V alors que le 003-rf est la version 7-32v, alors oui j'ai bien la version 003-rf.

**Comment by tcharp38** [comment]
Il aurait du etre reconnu en ZG-003-RF

Peux tu faire un "reinitialiser" via l'onglet avancé en cliquant sur ton equipement,
puis me filer le package de logs ?
