### ISSUE TITLE
Ampoule Philips 9290030514 (id =LWA021, SignifyNetherlandsBV)

### ISSUE THREAD

**Issue by MichelCHAVOT** [KiwiHC16/Abeille#2693]
Bonjour.
Pouvez-vous ajouter l’ampoule philips hue white E27 550, référence philips 9290030514, référence zigbee LWA021.
A l’intégration, aucun paramètre utile n’apparait.
![intégration lwa021](https://github.com/KiwiHC16/Abeille/assets/36966985/f9b2bc4d-63df-452a-8dbf-a9d49437efb9)
![Image2](https://github.com/KiwiHC16/Abeille/assets/36966985/aae3ac54-d38a-4974-b7ec-66227f9c97cc)
En forçant le modèle LWA017, je peux l’utiliser, (On, Off, Set level, Get level, Level), mais je ne sais pas si j’ai tous les paramètres.

Toutefois, impossible d'intégrer une 2ème ampoule identique. En forçant le modèle LWA017, rien ne change.

J'ai tenté de repartir d'une sauvegarde avant intégration de ces lampes, j'ai ensuite intégré en premier la 2ème lampe, et elle a fonctionné. et à l'intégration de celle qui avait fonctionné au premier test, même échec.
j'ai essayé avec une 3ème ampoule, même échec?

Toutes les ampoules ont la même référence Philips et la même date de fabrication.
Merci.

**Comment by tcharp38** [comment]
Peux tu via l onglet avancé générer le discovery? Utiliser assistant de découverte

**Comment by MichelCHAVOT** [comment]
Voilà le fichier.
[discovery-LWA021_SignifyNetherlandsBV.json](https://github.com/KiwiHC16/Abeille/files/14719981/discovery-LWA021_SignifyNetherlandsBV.json)

**Comment by tcharp38** [comment]
Modele preliminaire
[LWA021_SignifyNetherlandsBV.zip](https://github.com/KiwiHC16/Abeille/files/14725575/LWA021_SignifyNetherlandsBV.zip)

A decompresser dans Abeille/core/config/devices
puis redemarrer demon
refaire inclusion

L'aspect visuel ressemble à quoi ? Et quel type culos ?
Tu as un lien du produit vers le site Philips ?

**Comment by MichelCHAVOT** [comment]
Bonsoir. Merci pour la réactivité !
Le plugin fonctionne, j'ai pu installer 3 lampes. L'affichage fonctionne également.
Toutefois, si je modifie un paramètre (le nom du device, ou le nom d'une commande, ou un paramètre d'affichage d'une commande), çà ne marche que pour la première modification. si j'essaie de modifier un autre paramètre, ça refuse la sauvegarde avec le message :
![erreur](https://github.com/KiwiHC16/Abeille/assets/36966985/fa199a51-7f92-4e22-b932-b300ee3895f6)
Il faut que je redémarre le Démon pour faire une 2ème modif.

**Comment by MichelCHAVOT** [comment]
![LWA021](https://github.com/KiwiHC16/Abeille/assets/36966985/49bae397-7799-4c46-9db3-466d56dda0ac)
C'est une douille E27, 580 lumens, 2100K

**Comment by MichelCHAVOT** [comment]
Le lien vers la page Philips :
https://www.zigbee2mqtt.io/devices/9290030514.html

**Comment by tcharp38** [comment]
Pour l'erreur que tu as peux tu decompresser ce fichier dans Abeille/desktop/js
et redemarrer Abeille
[Abeille.zip](https://github.com/KiwiHC16/Abeille/files/14728635/Abeille.zip)

**Comment by MichelCHAVOT** [comment]
Bonjour.
Installé et testé, çà fonctionne nickel.
Vraiment un grand merci pour ton travail.

**Comment by MichelCHAVOT** [comment]
J'ai aussi créé l'icone qui va avec:
![node_LWA021](https://github.com/KiwiHC16/Abeille/assets/36966985/4f2fff06-4b9f-4506-8b2f-6365bb6bf7df)

**Comment by MichelCHAVOT** [comment]
Bon, j'ai parlé un peu vite.
J'ai intégré 2 nouvelles ampoules identiques.
Le fonctionnement et la modification se passent bien.
Par contre, à l'affichage, le status et le level restent sur off et 0% (bien que les commandes fonctionnent)
Sur l'image ci-dessous, la lampe est allumée (contrairement à ce que l'icone indique) et le level est affiché à 0% alors qu'il est à 100%)
![bug](https://github.com/KiwiHC16/Abeille/assets/36966985/75253164-78e8-4a5d-9cc7-e4c47f5b826f)

**Comment by MichelCHAVOT** [comment]
NB:
Dans l'onglet "Avancé", en cliquant sur "Réparer", tout est revenu dans l'ordre.

**Comment by tcharp38** [comment]
Tu n'aurais pas du avoir recours à "Réparer".
Du coup je ne sais pas trop ou on en est.

Peux tu supprimer ton equipement de Jeedom
refaire une inclusion de l'ampoule
tester
et me filer les logs avec les symptomes si il y a ?

**Comment by MichelCHAVOT** [comment]
Bonjour.
Je suis reparti d'une sauvegarde Jeedom que j'avais faite juste avant d'intégrer les 2 dernières ampoules
Dans ce backup, le fichier LWA021_SignifyNetherlandsBV.json est déjà dans le dossier Devices
Dans le dossier Desktop/js je remets le fichier Abeille.js que tu m'as envoyé.
Je redémarre Abeille.
Je réintègre dans Abeille une nouvelle lampe Philips.
Et là, pas de bug. L'intégration se passe bien, et l'affichage dans jeedom est correct ! ? !
Je ne vois pas pourquoi çà a fonctionné cette fois-ci, et pas la dernière fois alors que je suis reparti du même état de Jeedom.
Je te donne quand même les logs :
[AbeilleRoutes-Abeille1.json.log](https://github.com/KiwiHC16/Abeille/files/14736007/AbeilleRoutes-Abeille1.json.log)
[AbeilleLQI-Abeille1.json.log](https://github.com/KiwiHC16/Abeille/files/14736008/AbeilleLQI-Abeille1.json.log)
[AbeilleLogs-240324.tar.gz](https://github.com/KiwiHC16/Abeille/files/14736009/AbeilleLogs-240324.tar.gz)

Il resterai à intégrer dans le fichier LWA021_SignifyNetherlandsBV.json la bonne icone.
![node_LWA021](https://github.com/KiwiHC16/Abeille/assets/36966985/82cf0221-d753-45a6-861f-4ef88794cd61)
Je l'ai déjà fait à mon niveau en la plaçant dans dossier Abeille/Images.

**Comment by tcharp38** [comment]
Bonjour

Il est important de rester sur la derniere beta surtout si je file des "patchs" intermediaires à mettre dessus.
Je ne sais pas ce qui s'est passé non plus mais quoi qu'il en soit je ne vois pas de piste dans la situation actuelle.

Du coup tout est ok pour ce sujet ou il manque qqch ? ou qqch nest pas propre ?

**Comment by MichelCHAVOT** [comment]
Bonjour.
Pour moi tout va bien, tout est OK.
Il pourrait être intéressant lors d'une prochaine Mise à Jour d'y inclure l'icone de la lampe.
Encore merci pour le travail et la réactivité.👍

**Comment by tcharp38** [comment]
L'icone est déja dans le master donc ce sera pour la prochaine beta.
Je fermerai le sujet alors si il n'y a aucun autre souci.

**Comment by tcharp38** [comment]
Salut @MichelCHAVOT 
Que fait on avec ce sujet ?
Il y a encore des points à traiter ?

**Comment by MichelCHAVOT** [comment]
Bonjour.
On peut clore le sujet, pour moi tout est rentré dans l'odre.
Je pense que j'ai du saturé mon disque avec les nombreux historiques que je garde. Mais comme je suis passé de 4GO à 1TO, je n'ai plus trop d'inquiétude.

Encore merci pour ton aide.

**Comment by tcharp38** [comment]
Ca veut aussi dire que qq part il n'ya pas assez de test ou d'info sur ce genre de pb.
Je garde ca en tete au cas ou je peux generer des messages pour l'utilisateur...

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
