### ISSUE TITLE
Support ampoule RGB E27 (id = TS0505B, TZ3210_mja6r5ix)

### ISSUE THREAD

**Issue by judeoleborgne** [KiwiHC16/Abeille#2694]
bonjour.
serait il possible d'ajouter les ampoules rgb de ce fabricant chinois a la liste des compatibilité abeille.
voici le fichier decouverte completé au maximum ainsi que un png.

merci par avance pour votre travail.

**Comment by judeoleborgne** [comment]
[discovery-TS0505B__TZ3210_mja6r5ix.zip](https://github.com/KiwiHC16/Abeille/files/14732914/discovery-TS0505B__TZ3210_mja6r5ix.zip)
[discovery-TS0505B__TZ3210_mja6r5ix.json](https://github.com/KiwiHC16/Abeille/files/14732915/discovery-TS0505B__TZ3210_mja6r5ix.json)

![rgb e27](https://github.com/KiwiHC16/Abeille/assets/40631786/7726680a-d476-403e-9486-d558fb977930)

**Comment by tcharp38** [comment]
Salut

Peux tu ecraser le modele suivant avec ce fichier
core\config\devices\TS0505B__TZ3210_it1u8ahz

[TS0505B__TZ3210_it1u8ahz.zip](https://github.com/KiwiHC16/Abeille/files/14733681/TS0505B__TZ3210_it1u8ahz.zip)

puis redemarrer Abeille
refaire inclusion
tester et me dire ce qui cloche ou manque ?

**Comment by judeoleborgne** [comment]
nickel ca fonctionne, 
- decompression.
- copie du fichier avec winscp dans le dossier /var/www/html/plugins/Abeille/core/config/devices/
- exclusion du périphérique et suppression de jeedom.
- redémarrage de daemon
- inclusion de l'ampoule, elle est reconnue et je sais la piloter.

merci

**Comment by tcharp38** [comment]
Tout est ok pour toi ?
Tu as les fonctionalités attendues ?

**Comment by judeoleborgne** [comment]
je ne suis pas encore très bon avec jeedom mais a première vue je sais choisir la couleur et faire varier l'intensité.
l 'ampoule ne garde pas en mémoire sa dernière couleur si on la colle derrière un interrupteur classique et les couleurs éclairent beaucoup moins fort que le blanc, mais ca c'est lier à la qualité du produit

**Comment by tcharp38** [comment]
Ok donc je considere que le sujet est clos.
Mais tu peux le réouvrir si tu vois un quelconque souci avec ce device.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
