### ISSUE TITLE
Page santé - mode dark

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2696]
Hello,

Plus une demande d'amélioration qu'un bug ;)
mais depuis la dernière version beta (240403-BETA-2), la page santé est devenu difficilement lisible en mode dark (en tout cas pour mes yeux :D). En mode light, ca passe bien !

![image](https://github.com/KiwiHC16/Abeille/assets/56156622/38e9be0b-4d28-497f-956c-18e0bff06a15)

Possible de jouer sur la couleur en fonction du thème ?
Merci

Xav

**Comment by tcharp38** [comment]
Salut
Je vais regarder ca meme si je ne sais pas trop comment proceder pour que ce soit "maitrisé".
A suivre

**Comment by tcharp38** [comment]
A voir dans la beta de demain ... 240409-BETA-1
Pas tout à fait ce que je voulais mais ca doit etre un peu + lisible

**Comment by Xav-74** [comment]
De mon côté c'est tout bon ! Merci
