### ISSUE TITLE
Ajout support module MOES ZM-105-M (id = TS0601, _TZE204_dcnsggvz)

### ISSUE THREAD

**Issue by gegedme** [KiwiHC16/Abeille#2697]
bonjour,

est-il possible d'ajouter ce module ?
c'est un Module LED ZigBee, Interrupteur à Variateur

[discovery-TS0601__TZE204_dcnsggvz.json](https://github.com/KiwiHC16/Abeille/files/14930138/discovery-TS0601__TZE204_dcnsggvz.json)
![zigbee-smart-dimmer-switch-module-timer-diy-breaker-12-gang-883246](https://github.com/KiwiHC16/Abeille/assets/139325751/56ca4b64-2d44-42d4-9b0a-c94edeccec49)

merci à toi

**Comment by tcharp38** [comment]
Salut
Je vois qu'il s'agit d'un tout nouvel equipement mais Tuya, donc tout à découvrir. Va falloir bosser dessus.

Voila deja un modele vide preliminaire,
a decompresser dans core/config/devices
puis redemarrer
refaire inclusion
[TS0601__TZE204_dcnsggvz.zip](https://github.com/KiwiHC16/Abeille/files/14930646/TS0601__TZE204_dcnsggvz.zip)

Mets ce device en surveillance pour voir un peu ce qu'il raconte

Et tu me filera le package de logs par la suite
Merci

**Comment by gegedme** [comment]
c'est fait.
c'est en surveillance
merci à toi !

**Comment by tcharp38** [comment]
Je crois qu'il y a un inter connectable dessus.
Tu peux l'activer, noter l'heure, et me filer les logs ?

**Comment by gegedme** [comment]
j'ai actionné l'inter à 14:23.
[AbeilleLogs-240410.tar.gz](https://github.com/KiwiHC16/Abeille/files/14932074/AbeilleLogs-240410.tar.gz)

**Comment by tcharp38** [comment]
Il est toujours en "defaultUnknown" donc 
- soit tu ne l'as pas reintegré
- soit le modele n'est pas decompressé ou il faut
- soit autre souci

Neanmoins je vois beaucoup de messages
Nouvelle tentative avec ce modele à reinclure ou reinitialiser via pas equi
[TS0601__TZE204_dcnsggvz.zip](https://github.com/KiwiHC16/Abeille/files/14933269/TS0601__TZE204_dcnsggvz.zip)
pement/avancé

**Comment by gegedme** [comment]
il est bien là .
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/48c4f4b5-78a4-46cb-8322-ad9fc5d41306)
je refais une inclusion avec le nouveau modèle

**Comment by tcharp38** [comment]
Non, unknown device donc le modele que je t'ai filé n'a pas été reconnu

**Comment by gegedme** [comment]
pas décompressé au bon endroit..... désolé.
![image](https://github.com/KiwiHC16/Abeille/assets/139325751/426a1597-48dd-42fe-a557-b2d1561f6d6f)
il est là après inclusion.
j'actionne l'interrupteur et récupère les logs.

**Comment by gegedme** [comment]
[AbeilleLogs-240410 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/14933572/AbeilleLogs-240410.1.tar.gz)

**Comment by tcharp38** [comment]
Ouah.. il est ultra bavard.
Je ne vois meme pas la sequence d'init passer.

Il est en cours de portage sur d'autres solutions aussi. Je vais voir ce qu'ils trouvent.

**Comment by gegedme** [comment]
merci à toi

**Comment by gegedme** [comment]
Bon..... J'ai voulu raccorder le module sur un autre interrupteur....
Clac.... Cramé.
Ne cherche pas plus.
Je ne vais pas en racheter un immédiatement.
Désolé.
Merci encore pour ton aide.

**Comment by tcharp38** [comment]
Ha m...
Désolé pour toi :(

Je ferme le sujet. A reouvrir si besoin pour continuer.
