### ISSUE TITLE
Nouvelle équipement XBee

### ISSUE THREAD

**Issue by baloo53** [KiwiHC16/Abeille#2699]
Bonjour,

Via un collègue j'ai beaucoup discuté du réseau zigbee et du coup , de mon utilisation de abeille.
Aillant du mal avec la porté de mon réseau il ma indiqué qu'il avait en sa possession une carte de marque XBee qu'il pouvait paramétrer avec le logiciel XCTU en mode répéteur et que normalement après sa j'aurais pu l'inclure dans mon réseau. 
Echec de l'opération :/ si j'ouvre cette issue c'est pour savoir si il y a un firmware en particulier à utiliser pour pouvoir inclure cette carte configuré en répéteur sur le plugin abeille? ou bien si il y a un problème de compatibilité ou autre? 
Je vous laisse une photo de la configuration que j'ai effectué.

![IMG_20240417_165152](https://github.com/KiwiHC16/Abeille/assets/99254403/d182e069-29ab-4b99-ba5f-9043a105d0ed)
![z](https://github.com/KiwiHC16/Abeille/assets/99254403/39d97554-3b96-4137-a21c-6176bc87ae01)

**Comment by tcharp38** [comment]
Salut
Ton répéteur a du être inclut comme équipement inconnu (defaultUnknown).
Si c'est bien ça génère moi le discovery
Ou au moins donne moi le package de logs que je vois quelle est son identifiant

**Comment by baloo53** [comment]
C'est sa le problème. J'ai essayé de l'inclure sans la paramétrer et rien du tout. J'ai essayé de le paramétrer via le logiciel et rien du tout non plus. 
On se demande si c'est pas un problème de compatibilité avec le firmware (actuellement digimesh)

**Comment by tcharp38** [comment]
Alors je ne connais pas du tout ce Xbee. Si il ne s'inclut pas dans le reseau... rien à faire coté Abeille.
Apres une fois inclut, il ne sera probablement pas reconnu comme il faut mais c'est la ou je peux intervenir.

Donc ton souci est coté Xbee.
Note qu'un repeteur tout simple du type Tuya.. fonctionne tres bien pour une 10aine d'euros et est reconnu par Abeille normalement.

**Comment by baloo53** [comment]
Merci oui j'ai déjà un répéteur de ce type.
Je cherche aussi à comprendre le réseau zigbee via cette manipulation. En théorie je devrais pouvoir inclure dans mon réseau zigbee n'importe quelle équipements si j'ai le chanel et l'id et la c'est pas le cas. De plus quand je place directement ma clé zigate sur mon ordinateur et que je cherche à scanner le réseau via XCTU je ne trouve rien.

**Comment by tcharp38** [comment]
XCTU ca ne peut pas etre compatible Zigate.
C'est dédié Digi XBee donc je ne comprends pas ta manip.

**Comment by baloo53** [comment]
Je comprends pas non plus désolé :/
XCTU est juste un logiciel qui me permet de paramétrer des équipements zigbee je peux les mettre en mode routeur ou non je peux installer n'importe quel firmware via ce logiciel. C'est juste un outil. D'ou ma question, pourquoi ma clé zigate arrive pas à détecter cette fameuse carte? Je dois peut être installé un firmware particulier ? Tout sa est surtout de la curiosité pour avoir une meilleure compréhension du système zigbee/abeille.
Dans abeille, j'ai mon Pan id et mon chanel. Si je paramètres n'importe quelle équipements avec ces deux numéros en théorie je dois pouvoir l'inclure non?

**Comment by tcharp38** [comment]
XCTU est dédié Digi Xbee, et non pas n'importe quel equipement Zigbee.

Quoi qu'il en soit, pour que la Zigate "voit" un nouveau device
- il faut qu'il soit sur le meme canal que la Zigate
- qu'elle soit en mode inclusion (elle clignote)
- et surtout que ce device s'annonce sur le reseau. Sur un equipement du commerce on provoque ca via un reset du device, ou pression longue sur un bouton par ex

Donc pour toi la question est comment met on le Xbee en mode inclusion (appairage) ?

**Comment by baloo53** [comment]
Excuse moi je vais reprendre mes interrogations pour que sa soit plus clair:

1) Un équipement zigbee a t'il besoin d'un firmware particulier pour pouvoir être inclus dans ma zigate et donc abeilles ?

2) Si je paramètres le chanel et id pan d'un équipement zigbee je dois pouvoir l'inclure sans passer par le mode découverte de mon objet ? (J'ai pas de bouton découverte sur ma carte)

Si je demande sa, c'est que imaginons j'invente un capteur avec une fonction particulière en mode zigbee . Comment faire pour l'inclure sur abeilles ? Dans ma tête il fallait uniquement paramétrer le chanel et l'id pan peut importe le firmware dessus

**Comment by tcharp38** [comment]
1/ non. Si il est Zigbee "end device" ou "router".. il doit pouvoir etre inclus dans Abeille.
2/ Tu n'as que le channel à renseigner. Le PAN Id doit lui etre donné quand il integre un reseau (celui d'Abeille). Donc le point reste le meme... comment lui indiquer de faire une recherche de reseau ouvert et de s'y annoncer. La c'est specifique firmware Xbee

Le standard Zigbee decrit des tas de "clusters" (des fonctionalités). Ton device devra correspondre à l'un ou plusieurs d'entre eux.
Regarde ca https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf

**Comment by baloo53** [comment]
Merci pour cette réponse. En effet je dois me pencher sur comment ouvrir le dialogue de cette carte (mode appareillage) 
Pour le reste je vais continuer à me renseigner sur le réseau zigbee. Ton lien est très utile merci.
J'ai vraiment envie structurer mon réseau et voir les points faibles. Le plugin aide déjà beaucoup avec l'option "réseau". Mais j'aimerais aller plus loin. J'ai un doute aussi sur la clé zigate, es la plus performante. Enfin bref, merci encore

**Comment by tcharp38** [comment]
Suivant le nombre d'equipements tu ne peux pas forcement tout couvrir avec une seule clef. 2 reseaux peuvent etre necessaires.
Apres oui.. Zigate v1 ca le fait, les v2.. non je ne recommande pas (pas serieux).
Il y a plusieurs autres solutions de bridge

**Comment by baloo53** [comment]
Ha et bien avant de clôturer ce sujet je veux bien ta recommandation. je cherche quelque chose de qualité cette fois ma clé zigate est bien mais je pense que j'arrive à ces limites haha et puis elle a quand même 7ans de mémoire

**Comment by tcharp38** [comment]
Alors je n'ai pas essayé d'autre clef, cependant j'étais sur le point de démarrer le support d'un autre modele.
Je penchais vers les ZNP (chip TI) qui semblent avoir un FW de qualité
mais la tendance semble etre plutot EZNET (chip EFR32MG21)

Du coup j'envisage de démarrer le support dans Abeille pour ce type de clef/protocole

Voir https://haade.fr/fr/blog/efr32mg21-silabs-compatible-multiprotocole-zigbee-openthread-matter

**Comment by baloo53** [comment]
Cette clé la par exemple ?

Sonoff Zigbee Gateway, ZBDongle-E USB Zigbee 3.0 USB Dongle Plus, EFR32MG21 + CH9102F Zigbee Clé USB Coordinateur pour ZHA in Home Assistant, iobroker
https://amzn.eu/d/bwHWDlu

**Comment by tcharp38** [comment]
Oui.
Le plugin Zigbee officiel doit déja la supporter.

**Comment by baloo53** [comment]
Mais pas abeille encore :/ je vais attendre je pense car si je dois tout réintégrer sur le plugin zigbee je vais pas en finir (beaucoup de choses encastré dans les murs) alors que avec abeille j'ai remarqué une fonction qui permet de migrer ses équipements d'une clé à une autre.

**Comment by tcharp38** [comment]
Concernant la migration.. attention.
Le standard Zigbee dit qu'un device doit quitter proprement le reseau et normalement dans la foulée il se met à la recherche d'un nouveau pour s'y annoncer. Donc si tu ouvres le reseau destination et force le device a quitter... la migration se fait toute seule.

Je veux finaliser une stable avant d'attaquer le support des clefs EFR32MG21

**Comment by baloo53** [comment]
D'accord affaire à suivre alors

**Comment by tcharp38** [comment]
Je viens de me commander celle la
https://fr.aliexpress.com/item/1005006082023012.html?spm=a2g0o.order_list.order_list_main.5.21ef5e5bsPF7dL&gatewayAdapt=glo2fra

Donc a suivre mais dans un nouveau sujet que je vais ouvrir.

**Comment by baloo53** [comment]
C'est dommage on connait pas la porté du réseau proposé pour cette clé. 
On peut avoir une distance de 50m 100m 300m ou même 3km pour des usages industrielle.

Pour l'instant je pense que je vais déjà mettre à jour ma clé v1 moi haha j'en est pas fait depuis longtemps.
Je suis actuellement sur une version 0004-0323

**Comment by tcharp38** [comment]
Ne surtout pas se fier à ce genre d info. La portee dépend de la puissance de la clef mais surtout des murs et autres perturbations.
Et elle est encore meilleure avec une antenne

Pour ta v1, le fw 0004-0323 est le dernier. Rien de mieux.

**Comment by baloo53** [comment]
Oui en effet une antenne peut aider. Quelques points de soudure et sa se fait mais bon pas envie de le faire sur ce coordinateur :p
Je vais attendre un peu je pense et basculer sur la clé que tu viens d'acheter si les résultats sont meilleurs.
C'est toujours agréable d'améliorer et rendre fiables sont réseau.

**Comment by tcharp38** [comment]
Voir #2703 

Concernant XBee, je ne peux pas faire grand chose tant qu'il ne rentre pas sur le reseau Abeille, donc peut on fermer le sujet ?
Que ca ne t'empeche pas d'y ajouter des pistes pour ceux qui voudraient experimenter comme toi.

**Comment by baloo53** [comment]
Oui tu peux merci
