### ISSUE TITLE
La Zigate 1 semble plantée mais impossible de lui faire un cycle OFF/ON.

### ISSUE THREAD

**Issue by balabap** [KiwiHC16/Abeille#2700]
Hello,
suite a la mise a jour de raspbian vers Bullseye, puis mise a jour des plugins dont abeille puis mise a jour de Jeedom en version 4.4.3, j'ai cette erreur sur ma zigate : 
La Zigate 1 semble plantée mais impossible de lui faire un cycle OFF/ON.

dans les logs abeille parser j'ai plein d'erreurs de ce style : 
3302|[2024-04-17 22:03:24]   msg_receive(queueXToParser) ERROR 22
en version beta, j'ai les erreurs suivantes quand je veux tester le port série de la zigate : 
ERREUR 'checkSerialPort' !
Votre installation semble corrompue.

En version stable, je n'ai pas cette erreur, mais ça mouline en continu.

Avez-vous une idée pour résoudre svp ?

**Comment by balabap** [comment]
Petit update, après avoir désactivé le plugin, puis activé le plugin Zigate, puis désactivé Zigate puis reboot, puis activé le plugin abeille, j'ai toujours l'erreur, mais cependant la zigate communique bien avec mes équipements.
Je laisse ouvert au cas ou ce soit un bug du plugin ;-)

**Comment by tcharp38** [comment]
Salut @balabap 
Pour toute demande de support merci de mettre le package de logs (page maintenance + telecharger tout + glisser deposer ici).
Sinon je suis un peu aveugle pour suivre la situation.

Maintenant d'apres ce que tu dis, le plugin Zigate a fait qqch qu'Abeille ne semble pas faire. Mais.. je seche. Trop aveugle.

**Comment by balabap** [comment]
[AbeilleLogs-240418.tar.gz](https://github.com/KiwiHC16/Abeille/files/15022547/AbeilleLogs-240418.tar.gz)

Voici les logs a 11h07/ 11h08 j'ai activé les logs debug, j'ai cliqué sur le bouton tester de zigate 1 et j'ai eu le message d'erreur "ERREUR 'checkSerialPort' !"
Pour les problème d'hier, tu les trouveras à la date d'hier aux alentours de 22h00.
Je reste à ta disposition si nécessaire.
Merci d'avance

**Comment by tcharp38** [comment]
Qqch ne va pas avec ton installation mais je n'arrive pas à ouvrir ton pacakge de logs.

Donne moi un snapshot de ta page de config ainsi qu'un nouveau package de logs si tu arrives à l ouvrir de ton coté.
Le checkSerialPort sous entend que le port n'est pas bon.
Serait il utilisé par autre chose ?
Donne moi le log "AbeilleConfig.log" STP ca doit en parler.

Ha dernier point.. tu es bien sur la beta d'Abeille ? C'est la version la + avancée.

**Comment by balabap** [comment]
J'ai le même problème que toi, je viens de regénérer le package de logs et il ne fait que 20 octets. c'est bizarre.
voila pour la conf du plugin.
![image](https://github.com/KiwiHC16/Abeille/assets/75443435/6062f5e5-9b8e-4478-966f-a2895bca25a1)

[AbeilleConfig.log](https://github.com/KiwiHC16/Abeille/files/15053356/AbeilleConfig.log)
je te joins aussi le log abeille, qui est plus verbeux
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/15053435/Abeille.log)
Merci à toi

**Comment by tcharp38** [comment]
Etrange cette facon d'acceder au port. Je m attends plutot a qqch du style /dev/ttyUSBx

Peux tu ouvrir une console SSH, 
te mettre dans le repertoire Abeille (/var/www/html/plugins/Abeille)

Puis execute ca en mettant le port correct
./resources/scripts/checkZigate.sh /dev/ttyUSBx USB

Si tu as un "permission denied" dis moi et fais un "chmod +x ./resources/scripts/checkZigate.sh"

**Comment by balabap** [comment]
Salut @tcharp38 , pour info, je ne sais pas si ça va résodure mon problème, mais je me suis aperçu que suite a la mise a jour de mon raspbian j'avais perdu les droits dans le fichier sudoers:
www-data ALL=(ALL:ALL) NOPASSWD: ALL

Je viens de les remettre. 
Je vais procéder a une réinstallation des pacakges et tu Abeille sans suppression. J'ai déjà moins d'erreurs au niveau de mes logs.
Je te tiens au courant.

Edit1 : c'est ce qui générait mes problème de génération du zip des logs.
Edit2 : apres installation des dépendances, toujours KO
- après passage en version stable : Test OK
- après nouveau passage en version beta : KO

**Comment by tcharp38** [comment]
Salut

Le test Zigate est KO en beta mais OK en stable ?
Tu me files le package de logs ?

**Comment by tcharp38** [comment]
Je viens de pousser une beta pour demain.
J'ai trouvé un souci qui doit expliquer ton test KO en beta.

**Comment by balabap** [comment]
ah super, bonne nouvelle. tu veux quand meme les logs ?

**Comment by tcharp38** [comment]
Non, on va attendre que tu bascules sur la nouvelle beta et me fasse un retour.

**Comment by balabap** [comment]
C'est pas mieux pour ma part j'ai toujours l'erreur.
Je te joins les logs.
[AbeilleLogs-240424.tar.gz](https://github.com/KiwiHC16/Abeille/files/15090960/AbeilleLogs-240424.tar.gz)

**Comment by tcharp38** [comment]
Je ne suis pas en mesure de faire des tests.
Ca t ennuie de decompresser ca dans Abeille/core/ajax
[Abeille.ajax.php.zip](https://github.com/KiwiHC16/Abeille/files/15098004/Abeille.ajax.php.zip)

retester
et me filer les logs ?

**Comment by balabap** [comment]
C'est fait, mais la génération du zip me retourne cette erreur :
ERREUR interne: Fichier inexistant
Chemin: /tmp/jeedom/Abeille/AbeilleLogs-240424.tar.gz
Je t'ai généré le zip a la main
[AbeilleLogs_240424.zip](https://github.com/KiwiHC16/Abeille/files/15100079/AbeilleLogs_240424.zip)

**Comment by tcharp38** [comment]
On parle bien du test "KO" non ?
Car la je vois que ca fonctionne.

Pour la generation des logs, si ca ne fonctionne pas c'est + compliqué
Il me faut les logs qui se cachent dans /tmp/jeedom/Abeille que tu peux voir via la page maintenance

**Comment by balabap** [comment]
salut, oui en effet le test "KO" que j'avais n'est plus présent.
Je t'ai téléchargé tous les logs un par un qui étaient dans maintenance.
ce matin j'ai testé, après reboot journalier de mon rapsberry, ca ne fonctionnait pas. Après m'etre connecté en ssh dessus, j'ai tenté d'accéder au dossier indiqué, il me dit que je n'ai pas les permissions pour accéder au dossier Abeille.
J'ai tenté pour revoir le chemin, depuis la page maintenance qu'on peut voir quand ça plante, et la le zip s'est bien mais il fait 0 Ko.
Je dois encore avoir des problèmes de droits liés à la montée en version de Buster vers Bullseye.

**Comment by balabap** [comment]
re, autre point, je ne sais pas si c'est volontaire et / ou si tu le vois dans les logs, mais le fait d'appuyer sur le bouton "test" passe le démon en Non OK, puis il repasse OK quelques secondes après.

**Comment by tcharp38** [comment]
Le dernier point que tu mentionnes est deja fixé. Je pousse une beta pour demain, le 26

**Comment by balabap** [comment]
Hello, j'étais concentré ces derniers temps sur un autre sujet Jeedom. Je n'ai plus de souci depuis la dernière maj, sauf tous les matins à 6h58, j'ai cette erreur : "La Zigate 1 semble plantée mais impossible de lui faire un cycle OFF/ON."
Cependant tout au long de la journée, je n'ai aucun souci avec le module.

**Comment by tcharp38** [comment]
Salut.
Qu y a t il a 6h58 régulièrement ?
Tu as un package de logs ?
Je suppose que tu es à jour côté beta.

**Comment by balabap** [comment]
je ne sais pas ce qu'il y a tous les jours a 6h58. Je viens de réactiver les logs debug. je te donne les infos demain.

**Comment by tcharp38** [comment]
6h58 ca veut dire probablement 7H du mat. Si le plantage est toujours à cette heure, il y a un evenement lié à ca.

**Comment by balabap** [comment]
je viens de trouver ce qui provoque cette erreur, c'est la fin de la sauvegarde Jeedom qui provoque cette erreur. cette sauvegarde est programmée a 6h51. as-tu besoin des logs?

**Comment by tcharp38** [comment]
Ha ok.
Oui si jamais tu as des logs demain matin qui couvrent cette periode.. je peux essayer de comprendre le rapport.

**Comment by balabap** [comment]
bonsoir, voici les logs.
[AbeilleLogs-240517.tar.gz](https://github.com/KiwiHC16/Abeille/files/15357760/AbeilleLogs-240517.tar.gz)
Merci a toi.

**Comment by tcharp38** [comment]
Je vois 2 moments de plantage

    [2024-05-17 06:58:04][INFO] : Pas de réponse de la Zigate 1 depuis plus de 2min
    
    [2024-05-17 08:24:03][INFO] : Pas de réponse de la Zigate 1 depuis plus de 2min

Aucune idée de la raison.
Quoi qu'il en soit on se sait toujours pas la redemarrer. Et pas de RESET sur une version USB contrairement à la version Pi mais bon meme pas sur que ce soit assez propre pour repartir du bon pied.

Comment faire un power OFF/ON reste a trouver .. si tant est qu'il y ait une solution.
Mais il faut que je m installe une verison en Bullseye pour avancer c est clair.

**Comment by balabap** [comment]
hello, ok, ça marche. Si tu veux me faire tester des choses, ou autre n'hésites pas. Je reçois les notifs par mail.

**Comment by tcharp38** [comment]
Ca marche.
Du coup c'est "vivable" pour toi ? Tu dois debrancher/rebrancher la zigate souvent non ?

**Comment by balabap** [comment]
oui c'est vivable sans souci. Je n'ai pas du tout besoin de débrancher / rebrancher.

**Comment by tcharp38** [comment]
Alors la je ne pige pas mais bon.. tant que ca fonctionne pour toi c'est parfait.

On laisse le sujet ouvert ?

**Comment by balabap** [comment]
peu importe, si tu penses pouvoir tester rapidement, on peut le laisser ouvert, sinon on ferme et si ca devient trop génant pour moi, je réouvrirai un sujet.

**Comment by balabap** [comment]
hello, j'ai installé la dernière beta, et ce matin je n'ai pas eu l'erreur. tu aurais trouvé quelque chose ?
Je vaus surveiller et attendre demain pour voir si j'ai encore l'erreur. Sinon on pourra cloturer le sujet.

**Comment by tcharp38** [comment]
@balabap 
Il y a eu un changement de mode de fonctionnement de la Zigate. Je n'utilise plus que le mode "raw".
Ca te parle pas forcement mais quoi qu'il en soit peut etre que la Zigate est plus stable comme ca.

Quel est le status depuis ?

**Comment by balabap** [comment]
Salut,
J'ai eu l'erreur hier matin. DEpuis le 29/05, j'ai plusieurs equipements qui se sont mis en timeout. est-ce que c'est lié a ta modification ou pas je ne saurais le dire. 
Je t'avoue que j'ai un peu laissé tomber la surveillance de abeille, pour me concentrer sur le pilotage de ma borne de recharge pour mes VE, en fonction de ce que produisent mes panneaux solaires, et j'ai aussi acheté un "minipc" afin de migrer tout mon Jeedom vers une VM sur ce minipc, car j'ai l'impression qu'au niveau des performances mon PI4 commence a se trainer.

**Comment by tcharp38** [comment]
Salut
Pense à me filer un package de logs histoire que je puisse voir si qqch me saute aux yeux.

**Comment by balabap** [comment]
[AbeilleLogs-240605.tar.gz](https://github.com/user-attachments/files/15595815/AbeilleLogs-240605.tar.gz)
voila le package de logs, mais je sais pas si tu y trouveras quelque chose.

**Comment by tcharp38** [comment]
D'apres tes logs 1 seul en timeout

    - TO : [chambre parents][Temp Parents], Id=195, TIMEOUT (last comm 2024-05-14 14:18:03)
           Addr=F973, Model='weather', Type='Xiaomi temp/humidity/pressure sensor'

et une prise qui ne repond pas (ou pas à ce moment)

    - NA : [Bureau][Prise Bureau], Id=214, NO-ACK
           Addr=DCAD, Model='TS011F__TZ3000_wamqdr3f', Type='Silvercrest connected plug'

C'est anormal ?

**Comment by balabap** [comment]
le perif en timeout n'a plus de pile donc c'est normal, et la prise bureau, ellese déconnecté et je l'ai réintégrée. Dans la page santé j'en avait 4 ou 5 en time out, mais bon pas grave.

Tien au passage changement de sujet, sur ma migration vers VM, que me conseille-tu ?
- migration via jeelink 
- ou installation de tous les plugins installés sur mon pi4, puis restauration de la sauvegarde de mon pi4 ?

**Comment by tcharp38** [comment]
Ok donc tu as eu des timeouts un moment mais tout est revenu dans l ordre.
Peut etre un relais (une prise, une ampoule ?) qui a foiré ou débranché un moment.

L'idée de passer par Jeelink n'est pas bete. Ca te permet d'y aller progressivement, avec du coup 2 jeedoms en //.
Quand un truc est stable sur ta VM tu peux basculer un autre.

**Comment by balabap** [comment]
Hello, je suis passé apr une restauration directement, j'ai pas réussi a comprendre le fonctionnement de Jeelink.

pour le moment je n'ai plus l'erreur.

Autre point, depuis ma restauration et la dernière maj beta, je ne trouves plus les commandes que j'avais (peut-etre créées manuellement) time-timestamp.
Maintenant j'ai des commande time-time. Quel est le besoin de cette nouvelle commande ?
J'avais un scénario qui calculait la dernière communication qui était justement dans time-timestamp, et  qui me remontait une erreur si j'avais un équipement pas connecté depuis plus d'1 jour.
Dans mon cas, je n'arrive plus a faire le calcul de différence entre "time-time" et "maintenant".
As-tu une idée de comment faire ce calcul ?

**Comment by tcharp38** [comment]
Salut @balabap 
Depuis le début on avait time-time & time-timstamp mais 2 commandes pour la meme information. Seul le format change.

Dans la mesure ou la mise à jour de chaque commande a un cout et que je n'ai jamais vu personne avant toi me parler de "timestamp", je l'ai viré (pour virer la redondance) en ne gardant que celle directement lisible.

Le passage de l'un à l'autre est facile en PHP
$time-time = date("Y-m-d H:i:s", $timestamp)
$time-timestamp = strtotime($time-time)

Peut etre qu'au final c'est timestamp que je dois garder car plus utile qu'une date lisible directement

**Comment by balabap** [comment]
pour ma part je faisais ainsi #timestamp#-(#Time-Timstamp#) > 86400
soit plus de 1 jour sans remontée.

Et je n'arrivais pas a le faire.
Grace à toi, je vais pouvoir résoudre mon scénario avec #timstamp# -  strtotime($time-time)
Ne changes rien si je suis le seul a utiliser le time-timestamp

**Comment by tcharp38** [comment]
Je ne sais pas qui l'utilise mais apres reflexion.. j'aurais du garder la version "timestamp" et virer la version "human".
En effet ca me parait bien + utile pour traiter via des scenarios et c'est surtout pour ça.

En ligne avec ca ?
Si t'es partant je reviens en arriere pour la beta de demain et remets "Time-TimeStamp" en virant l'autre

**Comment by tcharp38** [comment]
Je suis en train de réaliser que meme cette info "Time-TimeStamp" est redondante.
Le "lastCommunication" existe dans Jeedom à priori et utilisable dans les scenaris.

voir https://jeedomiser.fr/article/les-scenarios-dans-jeedom/

    lastCommunication(equipment,[format])
    Retourne la date de la dernière communication pour l’équipement donnée en paramètre, le 2ème paramètre optionnel permet de spécifier le format de retour (détails ici). Cependant, -1 = commande introuvable.

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/c6b8b706-a4a7-4e3b-83db-159c0a84268d)

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/862b5cd2-5b42-4ca0-a4e2-098459799f06)

Bon donc lastCommunication est déja au format "string" si besoin.

**Comment by balabap** [comment]
je viens de tester dasn le testeru d'expresison, et j'arrive pas a faire avec lastCommunication :
date_diff(date("Y-m-d H:i:s", #timestamp#), lastcommunication(#[Jardin][Temp Ext]#))

**Comment by tcharp38** [comment]
Je modifie la beta pour demain et remet "Time-TimeStamp" à la place de "Time-Time"

**Comment by balabap** [comment]
Hello, je profites de ce post pour te poser une question, mais n'hésites pas a me dire si il faut que j'ouvre un nouveau post. Sur mon installation j'ai des détecteurs de fumée Xiaomi, et leur comportement est "bizarre" ces derniers temps. Lorsque j'avais le plugin Zigate, j'avais 2 entrées Alarm qui correspondaient a la détection de fumées et a l'appui long pour le test de mémoire. Avec Abeille, il y a une valeur "Etat" qui quand il ne se passe rien renvoie une chaine vide, et en théorie renvoie 1 quand il  y a détection de fumées. Dans mon cas j'ai un scénario basé sur la valeur de "Etat" et qui me préviens d'un potentiel incendie. il y a quelques semaines j'ai eu le déclenchement de mon systeme (Sirene pour nous réveiller et Alexa assez fort pour nous réveiller) à 2h du matin. Sur une installation similaire chez un parent, j'ai eu 2 déclenchements ces 10 derniers jours sur 2 détecteurs de fumées différents. Dans les 2 cas l'état est passé 1, alors qu'en réalité le détecteur déclencheur de l'alerte s'est mis a "biper" pour indiquer que la batterie est faible. Je penses que l'alerte à 2h du mat chez moi estaussi due a un pb de piles. Et en regardant sur les infos récupérées, l'info "Battery-Percent" ne renvoie rien.
Est-ce que tu as le même matériel chez toi pour tester, si oui, as-tu le même souci, as-tu besoin de logs ?
Pour info, je suis en congés à l'étranger, donc pas forcement réactif, mais je m'éfforcerai de te répondre au plus vite.
Merci à toi.

**Comment by tcharp38** [comment]
Salut @balabap 
Ouvre un sujet dédié à ton detecteur STP.
Quel est le modele que je regarde de + pres ?

Et bonnes vacances. Moi je rentre juste.

**Comment by balabap** [comment]
Salut, j'ai ouvert le post :
https://github.com/KiwiHC16/Abeille/issues/2723
Tu trouveras toutes les infos. 
Bonne reprise a toi ;-)

**Comment by tcharp38** [comment]
Hello @balabap 

J'ai bossé sur un firmware de Zigate V1 pour un pb de crash que j'ai eu de mon coté.
Du coup si besoin on peut basculer dessus quand la zigate plante et creuser le sujet si toujours interessé.

Tiens moi jus

**Comment by balabap** [comment]
salut, pour le moment je n'ai plus de souci. Et pour être honnete je suis en train de basculer en double config jedom /Home Assistant et du coup j'ai racheté une autre clé zigbee pour basculer progressivement sur un conteneur zigbee2mqtt qui enverra les infos aux 2 vms Jeedom / HA.
Malgré tout etant donné que je ne migre que mon environnement je ne resterai pas loin des évolutions pour l'environnement de la famille.
Encore une fois tu fais un boulot formidable, et ce n'est pas a cause de Abeille que je tente cette double infra. c'est plus a cause de bugs sur d'autre plugins pour lesquels les devs ne veulent plus vraiment faire d'evolutions

**Comment by tcharp38** [comment]
Hello

Ben pas de soucis je comprends bien.
J'espere que ta nouvelle solution te satisfera encore mieux donc bonne chance.

Je ferme du coup ce sujet si on n'y fait plus rien mais si jamais, n'hesite pas à le réouvrir.
A bientot peut-etre.
