### ISSUE TITLE
Abeille / Zigate+V2 plus aucun device ne répond !

### ISSUE THREAD

**Issue by MichelCHAVOT** [KiwiHC16/Abeille#2701]
Depuis une semaine, je n'ai plus de réseau Zigbee.
Dans le plugin abeille, je vois tous mes appareils zigbee (j'en ai 32).
Quand je vais sur le réseau abeille, et que je force la réinterrogation du réseau, aucun appareil n'est trouvé !
Du coup, impossible de faire fonctionner mes appareils:
Les capteurs de température ne renvoient pas de données, etc

J'ai tout essayé, j'ai réinstallé debian (11.9) sur un disque externe SSD, réinstallé jeedom, recharger la dernière sauvegarde, j'ai même testé une autre zigate (reconfigurée avec la même adresse MAC), mais rien à faire 😢

Please help !

Cordialement.

Michel CHAVOT.
[AbeilleLogs-240420.tar.gz](https://github.com/KiwiHC16/Abeille/files/15048978/AbeilleLogs-240420.tar.gz)

**Comment by tcharp38** [comment]
Salut Michel
Si aucun équipement n'est détecté durant le rafraîchissement réseau ça semble dire qu aucun n'est connu. Vu qu'ils ne peuvent pas avoir tous quitté le réseau j'en conclu que ce foutu firmware de la zigate v2 à fait lui même du ménage.
Trop peu de 4g pour jeter un œil au package mais demain soir ça sera possible.

Pour confirmer cette hypothèse tu peux reinclure un eq proche de la zigate et voir si lui apparaît ou pas

**Comment by MichelCHAVOT** [comment]
Bonsoir.
J'ai déjà tenté cette manip plusieurs fois, avec 2 équipements différents, y compris avec une zigate neuve, mais jamais rien ne remonte. A noter que j'ai cloné la 2ème zigate d'après la première en suivant la procédure zigate (https://zigate.fr/documentation/cloner-la-zigate-pizigate)
Je dispose aussi d'une 3ème zigate neuve et vierge. Je peux peut-être faire un test avec.
Remarques:
-  Quand je mets la zigate en inclusion, le voyant clignote bien.
-  Quand je fait le test sur le port usb, le résultat est négatif, pourtant le demon redémarre bien. Il y a 2 ports qui permettent de faire fonctionner le demon (voit jpg joint)
![Image3](https://github.com/KiwiHC16/Abeille/assets/36966985/1b3bda9f-8dec-42e2-87b5-95f69d90f9fc)

Merci.

**Comment by tcharp38** [comment]
J'ai du mal à suivre avec toutes tes manips et pas les logs correspondants.
Ceci dit je te suggere de migrer le FW en 3.22. Tu es en 3.21. Ca peut fixer des choses.

Ensuite file moi les logs apres une tentative de reinclusion d'un device et dis moi ce qu'il en est.

**Comment by MichelCHAVOT** [comment]
Bonjour.
Une remarque qui a peut-être son importance:
Je pense que mon système s'est planté car la partition /tmp/jeedom était full à 100%. Je suis donc passé de 256MO à 1GO.
Quand je redescend une sauvegarde récente, cette partition redevient full à 100%. Il faut que je désactive abeille, pour que çà revienne à la normale. Puis, quand je réactive le plugin abeille, la partition n'est plus saturée (1%)
Quand je teste le port usb maintenant çà fonctionne:
![TestPortZigate](https://github.com/KiwiHC16/Abeille/assets/36966985/ac543c8f-2a5f-4b51-b1a7-bad08db52378)


Ce que j'ai fait:
 - J'ai purgé tous les logs
 - J'ai arrêté se système
 - j'ai mis à jour ma zigate en 3.22
 - J'ai redémarré le système.
 - j'ai réinterrogé le réseau : aucun objet détecté.
 - J'ai activé le mode inclusion: la zigate clignote.
 - J'ai essayé d'inclure un capteur de température 3 fois de suite.
 - aucun appareil n'est apparu dans le réseau.
 - En téléchargeant les logs, je me suis apperçu que je n'étais pas en mode débug.
 - J'ai activé le mode débug.
 -  j'ai réinterrogé le réseau : aucun objet détecté.
 - J'ai activé le mode inclusion: la zigate clignote.
 - J'ai essayé d'inclure un capteur de température 3 fois de suite.
 - aucun appareil n'est apparu dans le réseau.
 - J'ai téléchargé les logs
 
[AbeilleLogs-240422.tar.gz](https://github.com/KiwiHC16/Abeille/files/15060468/AbeilleLogs-240422.tar.gz)

Merci.

**Comment by tcharp38** [comment]
Bonjour
Oui si le /tmp est plein ca peut empecher de creer le package de logs. Et certains logs y sont stockés.
Il faudra analyser ca pour comprendre ce qui bouffe tout l'espace.
Il faudrait que j'arrive à ajouter une alerte dans ce cas => dans ma TODO

Je note que 
- tu n'es pas en mode debug (pas sauvegardé ou pas redémarré Abeille)
- que tu es sur la STABLE donc bien vieille par rapport à toutes les avancées de la beta

Tu peux corriger, retenter une inclusion, et me filer le package ?

**Comment by MichelCHAVOT** [comment]
Bonsoir.
Zigate en version 3.22
Abeille en version 240319-beta-3
Jeedom redémarré
Tentative d'inclusion (3 fois) échouée.
Toujours pas de réseau Zigbee

NB le test du port usb sort en NOK, pourtant le demon démarre et passe en OK

voici les logs :
[AbeilleLogs-240422 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/15067453/AbeilleLogs-240422.2.tar.gz)

Merci..

**Comment by tcharp38** [comment]
Salut

Pourquoi  240319-beta-3 ? Ca n'est pas la derniere.

Cette Zigate v2 me desespere :(

Vu que ton reseau est "vide" d'apres elle, je te suggere de faire une "erase PDM" via l'onglet avancé de la Ruche.
Puis retenter une inclusion d'un truc à proximité.

J'ai quand meme trouvé un bug qui doit expliquer le status NOK en beta pour le test de port.
Je pousse une nouvelle beta pour demain (240423-BETA-5)

Si tu veux tester avant demain, decompresse ce fichier dans Abeille/core/scripts et retente le test de port
[checkTTY.zip](https://github.com/KiwiHC16/Abeille/files/15075541/checkTTY.zip)

**Comment by MichelCHAVOT** [comment]
Bonsoir.
J'ai travaillé sur un clone (que j'appelle zigate B) de ma zigate problématique (que j'appelle zigate A).
J'ai fait un erase de la clé, et tout va (presque) bien.
J'ai du réintégré mes 32 équipements, (1/2 journée), et maintenant tous fonctionnent.
Je n'ai pas pu effacé les données avec ta commande "erase PDM" car je ne l'ai pas trouvée.
J'ai reflashé la zigate avec la procédure zigate qui permet de la réinitialser : DK6Programmer -s COM3 -P 115200 -e FLASH -Y -p ZiGatev2-322.bin
Concernant le test du port :
Avec la version 240319-BETA-3, le test est NOK.
si j'y ajoute le correctif que tu m'as envoyé (checkTTY.sh) le test est OK
Avec la version 240423-BETA-7, j'ai une erreur :
![240423-BETA-7](https://github.com/KiwiHC16/Abeille/assets/36966985/82861779-3fdb-4629-afd8-f8d574a7cfe1)
Avec cette version, il faut que je désactive puis active le plugin pour pouvoir redémarrer le démon.

A noter :
Lors de la ré-inclusion de mes 32 équipements, il y a eu au 5 ou 6 blocages. Après quelques inclusion, il y a quelque chose qui se bloque, et impossible de faire une inclusion. La zigate refuse de se mettre en inclusion, le voyant ne clignote pas. Il faut désactiver le plugin puis le ré-activer pour reprendre les inclusions.

Pour les logs, j'ai "merdé". je n'étais plus en mode débug. Et quand je veux téléchargé l'ensemble des logs, j'ai l'erreur suivate :
ERREUR interne: Fichier inexistant
Chemin: /tmp/jeedom/Abeille/AbeilleLogs-240424.tar.gz

1h plus tard ...
A titre de vérification, j'ai cloné ma zigate B sur la zigate A.
Conclusion: rien ne marche, ma zigate A est morte.

Bonne soirée.

**Comment by tcharp38** [comment]
L'erreur fichier inexistant m'a déja été signalée.
Je ne suis pas chez moi donc pour l'instant je patauge. Pas moyen de tester.

Le "effacement PDM" est dispo via l'onglet "avancé" en cliquant sur ta ruche.

Dommage pour les logs lors des blocages mais je crois qu'on fait trop de choses à la fois.

Decompresse ce fichier dans Abeille/core/ajax
[Abeille.ajax.php.zip](https://github.com/KiwiHC16/Abeille/files/15101120/Abeille.ajax.php.zip)

et dis moi si ca corrige ou non le message "checkSerialPort"

Merci
et bonne soirée

**Comment by MichelCHAVOT** [comment]
Bonjour.

çà fonctionne, je n'ai plus le message d'erreur (checkSerialPort), et le test passe en OK.
Par contre le démon s'arrète et ne repart pas tout seul. Il faut le relancer manuellement.

**Comment by tcharp38** [comment]
Voila un correctif qui doit expliquer que ca ne reparte pas.
[Abeille.ajax.php.zip](https://github.com/KiwiHC16/Abeille/files/15112884/Abeille.ajax.php.zip)

Toujours pas moyen pour moi de tester.

**Comment by MichelCHAVOT** [comment]
Nickel. le démon redémarre, aussi bien pour le test du port que pour lire la version du firmware.

Merci beaucoup.

**Comment by tcharp38** [comment]
Je pousse le correctif dans la beta de demain.

Quand est il de ton sujet initial ?

**Comment by MichelCHAVOT** [comment]
Bonjour.
j'ai installé la dernière version (240425-BETA-1) et tout va bien (scan du port OK, lecture de la version du firmware OK, redémarrage du démon automatique OK).
Concernant mon problème initial (perte du réseau zigbee), tout est résolu. 
Le scan du réseau fonctionne, tout mes équipements sont bien connectés et fonctionnent, j'en ai rajouté un nouveau.
**En résumé:**
Système (Box domotique Jeedup version Zigbee avec Zigate+V2 (Powered by Jeedom) - Wizelec) acheté en 12/2022
disque flash de 4 GO.
Plantage de la zigate+V2 suite à une saturation du répertoire /tmp/jeedom.
J'ai remplacé la zigate par une nouvelle. (impossible de faire fonctionner ce dongle, même en réinstallant le firmware et en effaçant les données).
j'ai installé le firmware 3.22 sur la zigate+V2 (sur tes conseils, la 3A0 n'étant pas très stable).
J'ai réinstallé debian (V11.9) sur un disque externe SSD 1TO.
J'ai réinstallé Jeedom (V4.3.23). (je ne suis pas satisfait de la V4.4.3 qui déstructure complètement le dashboard)
J'ai redescendu ma dernière sauvegarde de jeedom.
J'ai passé la taille du répertoire /tmp/jeedom de 256 MO à 4 GO.
J'ai refait l'inclusion de tout mes périphériques, vérifié le bon fonctionnement de chacun.

Merci beaucoup pour ton aide.

**Comment by tcharp38** [comment]
Salut Michel

Merci pour résumé.
Je crois que dans ton cas l'effacement complet de la Zigate avec "-e FLASH" a "nettoyé" beaucoup de choses.

J'espere maintenant que cette situation va tenir et rester stable pour toi.
De mon cote j'arrete toute evolution jusqu'a transformer la version actuelle en version "STABLE" donc n'hesite pas à me remonter tout point bloquant ou regression.

Je ferme le sujet mais à réouvrir si besoin.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
