### ISSUE TITLE
Zlinky : aucune remontée

### ISSUE THREAD

**Issue by fable73** [KiwiHC16/Abeille#2704]
Salut,
Je viens de me rendre compte que mon Zlinky ne re-montait aucune donnée... Juste la connexion, l'horodatage... et le type de contrat...

![image](https://github.com/KiwiHC16/Abeille/assets/68732573/ee1d89a2-b775-4c89-82cf-98fd0a332bc6)

J'ai changé de FW pour passer à la dernière version (V13)
J'ai essayé de refaire plusieurs fois l'associations : rien
Je l'ai mis dans HA... là j'ai toutes les datas... donc pas de problème matériel à priori

J'avais modifié le json de base pour mettre à jour régulièrement la puissance apparente (get PAPP)... donc j'ai repris une version plus "officielle" à partir de #2678... toujours rien...
par contre quand je lance un test d'intégrité dans Abeille, j'ai un problème 

[2024-04-27 18:35:02] Test d'intégrité d'Abeille
[2024-04-27 18:35:05] - core/config/devices/ZLinky_TIC_LiXee/ZLinky_TIC_LiXee.json: FAILED
[2024-04-27 18:35:05] = ERREUR: Les fichiers ci-dessus sont corrompus.
[2024-04-27 18:35:05] = L'installation s'est mal déroulée, peut-être par manque de place.

j'ai mis sous surveillance le Zlinky... j'espère que ça suffira pour savoir ce que ce passe...

[AbeilleLogs-240428.tar.gz](https://github.com/KiwiHC16/Abeille/files/15142334/AbeilleLogs-240428.tar.gz)

**Comment by tcharp38** [comment]
Salut @fable73 
Avant tout peux tu basculer sur la beta. Il y a eu beaucoup de changements depuis ta stable et la beta du jour est en passe de devenir la nouvelle stable.

**Comment by fable73** [comment]
Salut tcharp38... 
Comme d'hab hyper reactif !!!
Passage à la beta fait... il y a l'air d'avoir du mieux!!!
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/36bf5b15-47f8-4284-a774-cd8758faa165)

Je laisse passer la nuit... mais demain si tout va bien je ferme le sujet ;)

j'ai vu ton post sur la future prise en charge des clef EFR32MG21 pour les gateways... J'en ai commandé une aussi... Au besoin je pourrais te servir de beta testeurs...

**Comment by tcharp38** [comment]
Hello
As tu refait une inclusion ou "mise à jour" via l'onglet "avancé" ? Le modele de la beta a evolué depuis la stable il me semble.

**Comment by fable73** [comment]
Salut,
J'avais refait une inclusion... mais par contre, j'ai ajouté un "Get-PAPP" au json... car je n'avais pas de mise à jour de la puissance apparente consommée

            "Get-PAPP": {
                "use": "act_zbReadAttribute",
                "params": "clustId=0B04&attrId=050F",
                "execAtCreation": 1
            },

si tu peux éventuellement le mettre de base...

Après une journée, j'ai des trucs un peu bizarre...
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/67b8b0b4-bb81-46c4-8633-22a515a3c489)
tout à l'air Ok jusqu'à 9h... après c'est bizarre jusqu'à19h... Mais comme j'ai des panneaux solaires depuis peu, je me demande si c'est pas eux qui font ce truc étrange...

Je te propose de fermer le cas pour le moment... OK?

**Comment by tcharp38** [comment]
A propos de PAPP, est ce une info "statique" (à lire qu'une fois), ou cette info est supposée changée ?
J'ai configuré un reporting mais est ce que ca fonctionne ?
Ton historique tu l'as créé en cliquant plein de fois sur "get PAPP" ou les remontées sont automatiques ?

**Comment by fable73** [comment]
Salut,
non pour moi c'est pas une info statique, il faut la lire régulièrement... tu vois son évolution dans le temps
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/1395bf08-b093-4d41-bd85-5209c2ade353)
je confirme le truc étrange, c'est lié aux panneaux solaires qui entrent en production, c'est synchro au niveau du temps...
pour moi ton reporting fonctionne pas, j'avais rien qui remontait, du coup j'ai ajouté le "Get-PAPP" et configuré un refresh régulier...
![image](https://github.com/KiwiHC16/Abeille/assets/68732573/8bd76542-60c8-4264-89a3-7728636d610e)

**Comment by tcharp38** [comment]
Ok il faut donc bosser sur le reporting de ce truc pour eviter de faire du polling regulierement.

Il est marqué "reportable"
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/77fc6164-2dd9-447c-9035-5b65b6d46812)

Donc tu es en TRI ?

Peux tu tenter une config du reporting comme suit (via onglet avancé de ton Zlinky)
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/bd7a81e6-a698-40b5-97a6-757b2d14c52b)
et me filer le package de logs ?

**Comment by tcharp38** [comment]
Ok laisse tomber. Je ne vais pas perdre de temps sur le PAPP.
Le FW du Zlinky n'est pas stable.
Il y a de nombreux sujets sur l'absence de remontée depuis la v12

https://github.com/fairecasoimeme/Zlinky_TIC/issues/241
https://github.com/fairecasoimeme/Zlinky_TIC/issues/145

Il faut donc suivre le forum https://github.com/fairecasoimeme/Zlinky_TIC/issues pour voir si qqch bouge et si nouveau FW.

**Comment by fable73** [comment]
Oki, vu... effectivement il y a beaucoup de demandes ouvertes... sans trop de réponses!

En tout cas, pour le moment, je clos ce sujet... merci pour ton coup de main
