### ISSUE TITLE
Intégration sonde température OWON THS-317-ET failed

### ISSUE THREAD

**Issue by MichelCHAVOT** [KiwiHC16/Abeille#2706]
Bonjour.
Je viens d'acuérir une sonde dde température OWON THS-317-ET :
https://www.domadoo.fr/fr/peripheriques/5998-owon-capteur-de-temperature-connecte-exterieur-sur-cable-zigbee.html

Quand j'active le mode inclusion de la zigate (la led clignote) et que j'appuie sur le bouton de la sonde pour l'intégrer au réseau, dans la seconde qui suit, la led de la zigate se fige et sur jeedom, j'ai le message d'erreur suivant :
**https://domotique.chavot.ovh/core/php/getResource.php?file=plugins/Abeille/desktop/js/Abeille.js&md5=81ec287ff648b4212ab89d389e362a0f&lang=fr_FR	
85	Uncaught TypeError: Cannot read properties of undefined (reading 'manuf')**
Une idée pour résoudre le problème ?
Merci et bonne journée.
[AbeilleLQI-Abeille1.json.log](https://github.com/KiwiHC16/Abeille/files/15348663/AbeilleLQI-Abeille1.json.log)
[AbeilleLogs-240517.tar.gz](https://github.com/KiwiHC16/Abeille/files/15348664/AbeilleLogs-240517.tar.gz)

**Comment by MichelCHAVOT** [comment]
[getResource.zip](https://github.com/KiwiHC16/Abeille/files/15348719/getResource.zip)

**Comment by tcharp38** [comment]
Salut @MichelCHAVOT 
Tres etrange je ne vois pas d'annonce de cet equipement dans les logs.

J'ai retenté avec mon modele mais je ne vois pas cette erreur.
Par contre dans tes logs le device n'apparait pas du tout mais peut etre qu'ils ne datent pas du moment ou tu as fait la manip.

Tu as qqch sur ton dashboard ajouté ?

**Comment by MichelCHAVOT** [comment]
J'ai retenté une inclusion. Cette fois, je n'ai pas eu le message d'erreur, (je l'avais eu lors de mes 2 tentatives cet après-midi).
En appuyant sur le bouton d'inclusion du capteur 3 fois à 10s d'intervalle, il a finit par apparaitre dans abeille.
Par contre, les infos ne remontent pas, toutes les variables restant à zéro, en particulier la température et la batterie.
[AbeilleLogs-240517 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/15354409/AbeilleLogs-240517.1.tar.gz)
Le device porte l'adresse 80E3

**Comment by MichelCHAVOT** [comment]
Je viens de supprimer le capteur d'abeille et j'ai retenté une inclusion.
Mêmes constatations: plus d'erreur dans jeedom, il faut appuyer plusieurs fois sur le bouton d'inclusion du capteur. Les infos ne remontent pas. Dans les logs, il a changé d'adresse: 341B.
le timetime affiché dans le dashboard reste à l'heure de l'inclusion.
[AbeilleLogs-240517 (2).tar.gz](https://github.com/KiwiHC16/Abeille/files/15354633/AbeilleLogs-240517.2.tar.gz)
![owon](https://github.com/KiwiHC16/Abeille/assets/36966985/31df29ee-b531-4715-9572-1a095fd5fb0b)

**Comment by tcharp38** [comment]
Ce capteur est assez bizarre. Je bataille toujours à le faire quitter le reseau et le faire revenir, mais rien à voir avec Abeille.
Tu vois sa LED rouge quand il est sorti du reseau, et VERT quand il a enfin rejoint le reseau.

Je vois un bug qui explique le manque de retour d'infos

    [2024-05-17 18:13:54] Msg from 'xToCmd': {"type":"configureDevice","net":"Abeille1","addr":"80E3"}
    [2024-05-17 18:13:54]   configureDevice(Abeille1, 80E3)
    [2024-05-17 18:13:54]   configureDevice() ERROR: Unknown device

Il va falloir que j'y reflechisse. Je ne pige pas pourquoi ca n'est pas le cas quand je fais l'essai de mon côté.

Entre temps tu peux tenter la chose suivante
- onglet avancé de ton capteur, "Mise à jour" du modele
- et tu le reveilles en cliquant plusieurs fois sur le bouton derriere tout en cliquand OK
- j espere que la config va se refaire

Une question au passage, c est marqué "temp piscine".. tu le mets dans l'eau ?
La sonde est etanche ? J'ai le modele mais j'ai pas fait tilt que c'etait le cas

**Comment by tcharp38** [comment]
Tiens finalement en attendant une prochaine beta.

A decompresser dans Abeille/core/class
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/15358474/Abeille.class.php.zip)

puis refaire inclusion 
et me filer les logs

**Comment by MichelCHAVOT** [comment]
[AbeilleLQI-Abeille1.json (1).log](https://github.com/KiwiHC16/Abeille/files/15360476/AbeilleLQI-Abeille1.json.1.log)
[AbeilleLogs-240518.tar.gz](https://github.com/KiwiHC16/Abeille/files/15360477/AbeilleLogs-240518.tar.gz)

Bonjour.
J'ai remplacé le fichier Abeille.class.php.
J'ai redémarré le demon.
J'ai refait l'inclusion du capteur après l'avoir exclus.
Pas de changement, température et batterie toujours à 0, le timetime reste à l'heure de l'inclusion.
Son adresse est 53A3 
Pour info, mon capteur est en V2: pas de voyant rouge, juste un vert qui (si on appuie sur le bouton) clignote rapidement quand il n'est pas inclus, lentement s'il est inclus. la plage de mesure de températures est augmentée.
Et non, je ne le trempe pas dans l'eau. l'étanchéïté n'est pas garantie, et il ne supporte pas les eaux salées. Je le placerai dans un tube étanche si j'arrive à le faire fonctionner.
Merci et bonne journée.

**Comment by tcharp38** [comment]
J'ai trouvé encore une boulette je pense.
Nouvel essai
[Abeille.class.php.zip](https://github.com/KiwiHC16/Abeille/files/15366908/Abeille.class.php.zip)

**Comment by MichelCHAVOT** [comment]
Bonjour.
Nouvel essai effectué: mais toujours le même constat: température et batterie à 0, timetime à l'heure de l'inclusion.
[AbeilleLogs-240519.tar.gz](https://github.com/KiwiHC16/Abeille/files/15368503/AbeilleLogs-240519.tar.gz)

**Comment by MichelCHAVOT** [comment]
Petite remarque concernant l'inclusion.
Je clique sur le le bouton (+) du plugin abeille: la led de la zigate se mets à clignoter.
à T0 J'appuie sur le bouton du capteur: sa led clignote 3 fois rapidement. au bout d'1 ou 2 secondes la led de la zigate se fige.
A T+10s je rappuie sur le btn du capteur. sa led clignote 3 fois rapidement. la led de la zigate est toujours figée.
A T+20s je rappuie sur le btn du capteur. sa led clignote 3 fois rapidement. la led de la zigate est toujours figée.
A T+24s la led du capteur clignote 3 fois lentement. à priori, çà veut dire qu'il est inclus.
A T+30s, la led de la zigate se remet à clignoter.

**Comment by tcharp38** [comment]
Je vais faire une beta car la j'essaie de faire un patch sur la STABLE mais visiblement il manque des choses.
Donc je pousse une beta pour demain. Ca te va ?

**Comment by MichelCHAVOT** [comment]
En fait, çà à l'air de fonctionner: au bout de 10 minutes, j'ai reçu la température. je te renvoie les logs, adresse: 3789
Je vais attendre une heure pour voir si la batterie remonte.
[AbeilleLogs-240519 (1).tar.gz](https://github.com/KiwiHC16/Abeille/files/15368596/AbeilleLogs-240519.1.tar.gz)

**Comment by MichelCHAVOT** [comment]
Ok pour la Beta demain.

**Comment by MichelCHAVOT** [comment]
C'est bon, la batterie est remontée aussi.

**Comment by MichelCHAVOT** [comment]
Pour info, quelques photos du boitier que j'ai fait pour mon capteur:
![20240519_120337](https://github.com/KiwiHC16/Abeille/assets/36966985/472163b1-695d-4672-b8f2-fb6cf719fa24)
![20240519_120444](https://github.com/KiwiHC16/Abeille/assets/36966985/904ea511-ea5a-4c95-b961-ff9318a863e5)
![20240519_120453](https://github.com/KiwiHC16/Abeille/assets/36966985/f30d6c3f-2bae-4625-ada0-9def2cdbcf2b)

**Comment by tcharp38** [comment]
> C'est bon, la batterie est remontée aussi.

Tres bien. Donc les dernieres corrections qui seront dans la beta sont bonnes.

**Comment by tcharp38** [comment]
> Pour info, quelques photos du boitier que j'ai fait pour mon capteur: ![20240519_120337](https://private-user-images.githubusercontent.com/36966985/331868644-472163b1-695d-4672-b8f2-fb6cf719fa24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjcyNjgsIm5iZiI6MTcxNjEyNjk2OCwicGF0aCI6Ii8zNjk2Njk4NS8zMzE4Njg2NDQtNDcyMTYzYjEtNjk1ZC00NjcyLWI4ZjItZmI2Y2Y3MTlmYTI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEzNTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1N2E2OGJiZDBiZTRmMWFlYWQ2MDVjZjc0OWI2ODIwYzdmYjBhYjQ4YTc4ZmU3ZTIzZjIxMGIxOGNlZDgxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkF0L3efCk0q1xnOehSw15pVJ_J-puHualc6lzoZSt4) ![20240519_120444](https://private-user-images.githubusercontent.com/36966985/331868654-904ea511-ea5a-4c95-b961-ff9318a863e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjcyNjgsIm5iZiI6MTcxNjEyNjk2OCwicGF0aCI6Ii8zNjk2Njk4NS8zMzE4Njg2NTQtOTA0ZWE1MTEtZWE1YS00Yzk1LWI5NjEtZmY5MzE4YTg2M2U1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEzNTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOTkzN2MyYjk2MjUwZDNlZjYxY2M4YWNmMTcwOWIwZGY2ZDBlOTVmY2JjNjI4YjI0ZjFhYzEzZTBjOWFiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGE7EmWzP10PiyE-0t-tFLqmFAdYgo1QNePR0LU2eGo) ![20240519_120453](https://private-user-images.githubusercontent.com/36966985/331868668-f30d6c3f-2bae-4625-ada0-9def2cdbcf2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjcyNjgsIm5iZiI6MTcxNjEyNjk2OCwicGF0aCI6Ii8zNjk2Njk4NS8zMzE4Njg2NjgtZjMwZDZjM2YtMmJhZS00NjI1LWFkYTAtOWRlZjJjZGJjZjJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEzNTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNTIzODdlZjY4MzI2MzU4ZTRhNjc4Y2E3ZGNlOGRiZTNhY2Y4YWE2YjM2Zjk2M2Q2MGMwMmZlOWYxZDNhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2p8E_mkwZS5bPlpt3pkTFyz9b1UjN1FS7dU4Vmf22sU)

Joli boitier.
Bravo !
Du coup tu as du raccourcir le cable de la sonde il me semble.
J'espere que la couche de plastique ne va pas trop impacter la mesure de température.

**Comment by tcharp38** [comment]
Salut @MichelCHAVOT 
Il reste qqch à faire sur ce sujet ?

**Comment by MichelCHAVOT** [comment]
Salut @tcharp38 
Non, pour moi tout est OK, mon capteur fonctionne parfaitement. Les données ne sont remises à jour que toutes les 10 minutes, ce qui est largement suffisant pour une température d'eau de piscine. Il faut juste savoir que les premières données ne remontent que 10 minutes après l'inclusion, ce qui peut être déroutant. 
Tu peux clore le sujet.

**Comment by tcharp38** [comment]
Pour la prochaine beta il y aura lecture de la température lors de l inclusion pour ne pas attendre le premier reporting 10min + tard.

Je ferme le sujet

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)

**Comment by MichelCHAVOT** [comment]
Tout va bien, cette sonde fonctionne correctement. Tu peux clore le sujet.
