### ISSUE TITLE
Comment accéder à un groupe (abeille) dans un scénario ?

### ISSUE THREAD

**Issue by MichelCHAVOT** [KiwiHC16/Abeille#2707]
Bonjour.
Je viens de créer quelques groupes dans abeille :
![groupes](https://github.com/KiwiHC16/Abeille/assets/36966985/fe3a69ad-b4b6-4440-9045-6c88988e5985)
Comment peut-on accéder à ces groupes dans un scénario pour piloter les ampoules en simultané ?
Merci de ton aide.

**Comment by tcharp38** [comment]
Salut Michel

Les groupes Zigbee sont conçus pour pour adresser plusieurs devices Zigbee en meme temps avec la meme commande.
Donc l'emetteur de cet ordre doit etre aussi dans le reseau Zigbee.
En general il s'agit d'une telecommande.

Pour ton cas, peut etre peux tu tenter via la telecommande virtuelle ?
![image](https://github.com/KiwiHC16/Abeille/assets/35221038/96a74f70-c778-41ae-ba6f-cb7bedffc262)

Dis moi si tu t'en sors.
Peut etre qu'il manque qqch à Abeille pour ça ou que la telecommande virtuelle a besoin d'améliorations.

**Comment by MichelCHAVOT** [comment]
Merci, çà fonctionne exactement comme je veux avec la télécommande virtuelle.
