### ISSUE TITLE
Ajout support micromodule NODON Volet roulant (id = SIN-4-RS-20, NodOn)

### ISSUE THREAD

**Issue by EricGIRARD35** [KiwiHC16/Abeille#2709]
Bonjour,

Je viens d'acquerir des module NODON 4 RS 20 pour volet roulant, pourriez vous les ajouter?

Merci d'avance

[discovery-SIN-4-RS-20_NodOn.json](https://github.com/KiwiHC16/Abeille/files/15494111/discovery-SIN-4-RS-20_NodOn.json)

**Comment by tcharp38** [comment]
Salut @EricGIRARD35 
Voila un modele preliminaire à tester.

A decompresser dans Abeille/core/config/devices
[SIN-4-RS-20_NodOn.zip](https://github.com/KiwiHC16/Abeille/files/15497217/SIN-4-RS-20_NodOn.zip)

puis redemarrer Abeille
refaire inclusion
tester

Il me faut une image au format PNG sans arriere plan pour mettre en icone. Je te laisse trouver ca
Merci

**Comment by EricGIRARD35** [comment]
Salut  tcharp38 
Merci pour cette réponse rapide
J'ai mis les fichier décompressés ici /var/www/html/plugins/Abeille/core/config/devices/SIN-4-2-20_NodOn
J'ai redémarré Abeille et refais une inclusion.
Je ne vois aucun changement Unknown device et pas de commades.

Je te joins les log et une image
[AbeilleLogs-240530.tar.gz](https://github.com/KiwiHC16/Abeille/files/15500156/AbeilleLogs-240530.tar.gz)
![SIN-4-RS-20](https://github.com/KiwiHC16/Abeille/assets/43894159/de466cc8-afcb-4c4a-915c-346092f89ed7)

**Comment by tcharp38** [comment]
J'ai pris ton image pour la prochaine beta.

Note que tes logs sont trop courts pour du debug: 500 => 5000 lignes 

Le modele n'est pas reconnu donc soit tu ne l'as pas décompressé au bon endroit, soit tu n'as pas redémarré Abeille avant reinclusion mais tu dis l'avoir fait.
Donc.. peut etre as tu créé le repertoire "SIN-4-2-20_NodOn" auquel cas il y a un niveau de trop ?

    [2024-05-30 14:35:36]   findModel(), manufId='NodOn', modelId='SIN-4-RS-20', loc=''
    [2024-05-30 14:35:36]   EQ is UNsupported. 'defaultUnknown' config will be used

**Comment by EricGIRARD35** [comment]
Ok j'ai passé mes log a 5000 lignes

Je crois effectivement que les fichiers ne sont pas au bon endroit pourtant je ne vois pas ou est l'erreur je n'ai que 2 répertoires abeille et l'autre est dans /tmp. Il ne me semble pas être un niveau trop haut.
![Capture d'écran 2024-05-30 174504](https://github.com/KiwiHC16/Abeille/assets/43894159/bd15162b-b0f1-4f41-bb66-9a56a89ef9b4)
J'ai redémarré la box et relancer les dépendances  puis fait une nouvelle inclusion idem

[AbeilleLogs-240530.tar.gz](https://github.com/KiwiHC16/Abeille/files/15502814/AbeilleLogs-240530.tar.gz)

**Comment by EricGIRARD35** [comment]
Le nom du fichier et du répertoire SIN-4-2-20_NodOn alors que mon module est un SIN-4-RS-20 est ce que cela le viendrait pas de la?
![image](https://github.com/KiwiHC16/Abeille/assets/43894159/16f618b3-9684-42d8-8473-eec95060c71f)

**Comment by EricGIRARD35** [comment]
Je suis un boulet c'est pas le bon fichier je recommence

**Comment by EricGIRARD35** [comment]
Super ca fonctionne merci beaucoup.
La montée descente et stop sont opérationnel mais avec 3 secondes de latence je n'ai pas autant de délais sur mes autres équipements est ce normal.
Le level ne fonctionne pas
Est t'il possible d'ajouter un slider pour contrôler la position car l'équipement le permet?

**Comment by tcharp38** [comment]
Voila une mise à jour du modele uniquement
pour /var/www/html/plugins/Abeille/core/config/devices/SIN-4-2-20_NodOn
[SIN-4-RS-20_NodOn.zip](https://github.com/user-attachments/files/15509822/SIN-4-RS-20_NodOn.zip)


Pour la latence je ne sais pas mais il me faudra les logs montrant ton action que je puisse analyser un peu.

**Comment by EricGIRARD35** [comment]
Maintenant j'ai bien le slider mais il ne fonctionne pas et l'info level non plus.
Je crois avoir identifier l'erreur pour la latence 
![image](https://github.com/KiwiHC16/Abeille/assets/43894159/c2986bc2-793b-4b12-af61-65a3ab2ea477)
Lorsque je change ID logic de level avec ca 01-0102-0008 plus de latence.
Ci dessous les logs
[AbeilleLogs-240531.tar.gz](https://github.com/user-attachments/files/15511599/AbeilleLogs-240531.tar.gz)

**Comment by tcharp38** [comment]
On va se focaliser sur le "set level".
Peux tu faire une action et me filer les logs dans la foulée?

D'autre part il serait bon de voir si un firmware +recent n'existe pas pour cet équipement.
Voir la par exemple https://github.com/Koenkk/zigbee-OTA/tree/master/images/NodOn
les fichiers commencant par
128b-0009-xxx

A priori tu as un FW en version 0000020B donc il y a bien plus recent si je ne me trompe pas => v300

    [2024-05-31 06:51:02] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0019, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=4745, DstAddrMode=02, DstAddr=0000
    [2024-05-31 06:51:02]   FCF=01/Cluster-specific/Cli->Serv, SQN=77, cmd=01/Query Next Image Request
    [2024-05-31 06:51:02]   fieldCtrl=01, manufCode=128B, imgType=0009, fileVers=0000020B, hwVers=0000
    [2024-05-31 06:51:02]   NO fw update available for this manufacturer.

**Comment by tcharp38** [comment]
He.. je viens de découvrir ca. Si c'est vrai les modules NoOn Zigbee supportent aussi du bluetooth
https://www.nodon.fr/application-nodon-connect/
Et la mise à jour semble du coup tres simple

**Comment by EricGIRARD35** [comment]
Hello,
Je viens de faire un set Level a 47% ci dessous les logs
[AbeilleLogs-240602.tar.gz](https://github.com/user-attachments/files/15525036/AbeilleLogs-240602.tar.gz)

**Comment by EricGIRARD35** [comment]
Oublie le log que je viens de t'envoyer je t'en envoi un nouveau

**Comment by EricGIRARD35** [comment]
[Uploading AbeilleLogs-240602 (1).tar.gz…]()

**Comment by tcharp38** [comment]
Dernier log pas dispo. L'update n'est pas allée jusqu'au bout

**Comment by EricGIRARD35** [comment]
Dernier log avant mise a jour module ci joint je viens de faire la mise a jour du module puis réincluions. Le module n'est plus reconnu plus de marque ni de model....

[AbeilleLogs-240602 (1).tar.gz](https://github.com/user-attachments/files/15525227/AbeilleLogs-240602.1.tar.gz)

**Comment by tcharp38** [comment]
La mise à jour est allée jusqu au bout ?
Ca peut prendre du temps

La cmd 'GoToLiftPercentage' ne semble pas supportée

    [2024-06-02 13:11:32] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=6401, DstAddrMode=02, DstAddr=0000
    [2024-06-02 13:11:32]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-02 13:11:32]   Default Response: Cmd=05, Status=81/Unsupported cluster command

Du coup j'ai ajouté "Set level tilt" pour test
[SIN-4-FP-21_NodOn.zip](https://github.com/user-attachments/files/15525360/SIN-4-FP-21_NodOn.zip)

et une nouvelle commande à decompresser dans core/config/commands
[act_zbCmdC-0102-GoToTiltPercentage.zip](https://github.com/user-attachments/files/15525362/act_zbCmdC-0102-GoToTiltPercentage.zip)

**Comment by EricGIRARD35** [comment]
Oui j'ai eu la confirmation qu'elle était terminée mais j'ai une erreur d'initialisation lorsque je tente de me connecter au module par l'application. J'ai fait un mail au support de NodOn.
J'ai d'autres module pour faire les test mais je ne vais pas refaire de mise a jour tant que la première n'est pas réglée.

**Comment by EricGIRARD35** [comment]
heu c'est normale que le nom ai changé? je le place dans un nouveau répertoire SIN-4-FP-21_NodOn?

**Comment by tcharp38** [comment]
Ooops, pardon.
C est un autre modele sur lequel je bosse. 
Voila le bon
[SIN-4-RS-20_NodOn.zip](https://github.com/user-attachments/files/15525390/SIN-4-RS-20_NodOn.zip)

**Comment by EricGIRARD35** [comment]
Ok j'ai pu refaire l'inclusion du module mis a jour et d'un second non mis a jour
Toujours pas d'action du slider ci joint les logs

[AbeilleLogs-240602.tar.gz](https://github.com/user-attachments/files/15525437/AbeilleLogs-240602.tar.gz)

**Comment by EricGIRARD35** [comment]
[AbeilleLogs-240602.tar.gz](https://github.com/user-attachments/files/15525836/AbeilleLogs-240602.tar.gz)

**Comment by EricGIRARD35** [comment]
Ci joint nouveau logs je crois que pour les logs précédents je n'ai pas utilisé la bonne commande mais toujours pas de mouvement.
[AbeilleLogs-240602 (1).tar.gz](https://github.com/user-attachments/files/15525984/AbeilleLogs-240602.1.tar.gz)

**Comment by EricGIRARD35** [comment]
La commande set level et set level tilt semble identique

**Comment by tcharp38** [comment]
J'ai trouvé un bug pour la cmd 'tilt'
néanmoins pas sur que ca solutionne. Le device repond toujours "commande non supportée"

    [2024-06-02 18:11:30] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=680B, DstAddrMode=02, DstAddr=0000
    [2024-06-02 18:11:30]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-02 18:11:30]   Default Response: Cmd=08, Status=81/Unsupported cluster command

Pour test, a decompresser dans Abeille/core/class
[AbeilleCmdProcess.class.php.zip](https://github.com/user-attachments/files/15526082/AbeilleCmdProcess.class.php.zip)

et bien redemarrer Abeille avant de refaire l'essai.

**Comment by EricGIRARD35** [comment]
J'ai remplacé  le fichier dans abeille/core/class et redémarré abeille mais ca ne fonctionne toujours pas ci joint le fichier log
[AbeilleLogs-240602 (2).tar.gz](https://github.com/user-attachments/files/15526253/AbeilleLogs-240602.2.tar.gz)

**Comment by tcharp38** [comment]
Les 2 commandes ne semblent pas supportées :(

    [2024-06-02 19:12:34] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=680B, DstAddrMode=02, DstAddr=0000
    [2024-06-02 19:12:34]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-02 19:12:34]   Default Response: Cmd=08, Status=81/Unsupported cluster command

    [2024-06-02 19:12:50] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=680B, DstAddrMode=02, DstAddr=0000
    [2024-06-02 19:12:50]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-02 19:12:50]   Default Response: Cmd=05, Status=81/Unsupported cluster command

Je me demande du coup qu'elle est l'astuce pour donner une position particuliere.

A creuser mais peut etre que la mise à jour FW n'y est pas pour rien. Il faudrait trouver des infos dessus, en particulier pourquoi une mise à jour.

**Comment by EricGIRARD35** [comment]
J'ai trouvé ca https://github.com/Koenkk/zigbee2mqtt/issues/18412
Je vois dans ce post qu'ils utilisent les commandes currentPositionTiltPercentage et currentPositionLiftPercentage
est ce que cela signifie qu'elles sont bien supportées par le module?

**Comment by EricGIRARD35** [comment]
Après quelques recherches les mises a jour du module pourraient concerner la fonction BSO qui posait problème fin 2022 https://community.jeedom.com/t/module-nodon-sin-4-rs-20-et-bso-orientable/89185/8

**Comment by EricGIRARD35** [comment]
Je  peux demander au support NodOn mais je ne sais pas trop quoi leur demander c'est un peu du chinois pour moi...

**Comment by tcharp38** [comment]
> Après quelques recherches les mises a jour du module pourraient concerner la fonction BSO qui posait problème fin 2022 https://community.jeedom.com/t/module-nodon-sin-4-rs-20-et-bso-orientable/89185/8

Oui surtout la suppression de ce soit disant support.
En effet il n'y a qu'une paire pour le moteur alors comment commander monter/descente et orientation avec ca.. pas possible.

**Comment by tcharp38** [comment]
> J'ai trouvé ca [Koenkk/zigbee2mqtt#18412](https://github.com/Koenkk/zigbee2mqtt/issues/18412) Je vois dans ce post qu'ils utilisent les commandes currentPositionTiltPercentage et currentPositionLiftPercentage est ce que cela signifie qu'elles sont bien supportées par le module?

Ca c'est le retour d'info mais la commande elle.. je vais encore creuser cette piste que je regardais deja.

**Comment by tcharp38** [comment]
Nouveau modele pour test.
[SIN-4-RS-20_NodOn.zip](https://github.com/user-attachments/files/15530784/SIN-4-RS-20_NodOn.zip)

Soit refaire inclusion soit "reinit" via l'onglet "avancé" de l'équipement.

**Comment by EricGIRARD35** [comment]
J'ai refais une  inclusion toujours pas d'amélioration
[Uploading AbeilleLogs-240603.tar.gz…]()

**Comment by tcharp38** [comment]
:(
Log incomplet.

Comment se termine la mise à jour du firmware ?
J'ai tenté avec mes modules NodOn fil pilote via Abeille et j'ai l'impression que la fin est assez bizarre aussi.

**Comment by tcharp38** [comment]
J'ai encore parcouru le net sur le sujet.. ce module semble generer beaucoup de questions.
Si tu as en as plusieurs est ce qu'on peut envisager que tu m'en envoie un pour test que je te renvoi apres ?
Si oui => email @ tcharp38@laposte.net

**Comment by EricGIRARD35** [comment]
> :( Log incomplet.
> 
> Comment se termine la mise à jour du firmware ? J'ai tenté avec mes modules NodOn fil pilote via Abeille et j'ai l'impression que la fin est assez bizarre aussi.

Pour le firmware j'ai deux modules a jour. La mise a jour du firmware est  un peu difficile il faut couper le courant sur le module avant de lancer la mise a jour et refaire la procédure a plusieurs reprises. Une fois la mise a jour effectuer il faut appairer le module a l'application une fois la demande de connexion faite sur l'appli il faut appuyer sur le bouton du micromodule pour finaliser.

**Comment by EricGIRARD35** [comment]
[AbeilleLogs-240603.tar.gz](https://github.com/user-attachments/files/15539400/AbeilleLogs-240603.tar.gz)

**Comment by EricGIRARD35** [comment]
Il y a une différence que je n'avais pas remarqué avec le nouveau model, le Set Level et le Set Level Tilt produisent une mise a jour du Level a la même valeur sans faire bouger  le volet.

**Comment by tcharp38** [comment]
Salut
Es tu sur que ce module supporte le "set position" ?
Tu as vu ca qq part qui le confirmait ?

De mon côté je ne vois pas d'erreurs avec un device qui supporte ces commandes Zigbee standards (cluster 0102)

**Comment by EricGIRARD35** [comment]
Salut,
J'ai les mêmes modules depuis plusieurs années en Enocean qui intègrent
cette fonction ok ca ne veut rien dire c'est pas le même protocole.
Le positionnement n'est effectivement pas précisé sur le site officiel mais
il l'est sur certain sites de revendeur.
J'ai trouvé ce test qui indique que la commande de positionnement existe
dans jeedom avec le plugin zigbee
https://haade.fr/fr/blog/test-du-module-zigbee-volet-roulant-nodon-SIN-4-RS-20

**Comment by tcharp38** [comment]
Oui effectivement, certains disent le supporter.

Du coup je me demande si le FW n'est pas cause. Si mise à jour il y a c'est pour corriger qqch.. mais quoi ?
As tu essayé la mise à jour via Abeille ?

Si tu as plusieurs modules et veux m'en envoyer un en // tu peux maintenant. Je ferai des essais en direct.

**Comment by EricGIRARD35** [comment]
Salut,

Non je n'ai pas testé la mise a jour du FW via Abeille mais j'ai
reussi a mettre a jour les modules par l'application NodON donc je n'en
vois pas trop l'utilité.

Ok je t'envoie un module dès que possible.  Je vais faire la mise à
jour avant de te l'envoyer car je ne l'ai pas encore fait sur le module qui
me reste.

**Comment by tcharp38** [comment]
Te casse pas la tete pour la mise à jour.
Je pourrai tester via Abeille en meme temps du coup.

**Comment by EricGIRARD35** [comment]
Trop tard mise a jour faîte colis emballé

**Comment by tcharp38** [comment]
Pas grave.
Donc la mise à jour s'est bien terminée. Je croyais que tu avais des soucis avec l'appli NodOn.

Mais donc ca aussi dire que cette mise à jour ne corrige rien quant à notre pb.

**Comment by tcharp38** [comment]
Je pousse une nouvelle mise à jour BETA pour demain.
Le modele a aussi changé.
Il faudra "reinitialiser" l'équipement via l'onglet avancé.

**Comment by EricGIRARD35** [comment]
Salut, je viens de faire la nouvelle mise a jour en version beta + rénitialisation de mes deux modules dans l'onglet anvancé.
Je n'ai toujours pas de mouvement lorsque je fais un set Level.
J'ai essayé le bouton de calibration qui a été ajouté il fonctionne.

**Comment by EricGIRARD35** [comment]
[AbeilleLogs-240619.tar.gz](https://github.com/user-attachments/files/15895652/AbeilleLogs-240619.tar.gz)

**Comment by tcharp38** [comment]
Incroyable !!
La commande est juste "refusée".
Mais de mon coté avec ton module.. il se passe qqch et pas un refus.

    [2024-06-19 07:00:26] Msg from 'xToCmd': {"topic":"CmdAbeille1/5B5B/cmd-0102","payload":"ep=01&cmd=05&value=57"}
    [2024-06-19 07:00:26]   No prepare function. Forwarding cmd to AbeilleCmdProcess.
    [2024-06-19 07:00:26]   processCmd({"cmd-0102":"cmd-0102","name":"cmd-0102","priority":2,"dest":"Abeille1","ep":"01","cmd":"05","value":"57","addr":"5B5B"})
    [2024-06-19 07:00:26]   cmd-0102: CmdId=05, Extra=39
    
    [2024-06-19 07:00:26] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=5B5B, DstAddrMode=02, DstAddr=0000
    [2024-06-19 07:00:26]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-19 07:00:26]   Default Response: Cmd=05, Status=81/Unsupported cluster command
    
On va proceder autrement.
Teste ca via l'onglet avancé, 

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/668b5cd8-0f0e-4093-b76a-11f517a66df2)

et tu me files les logs.

Pour info de mon coté je n'obtiens pas un refus mais plutot "failed" qui me semble logique vu que je ne peux pas faire de calibrage (pas branché sur un moteur)

    [2024-06-19 10:35:45] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=9792, DstAddrMode=02, DstAddr=0000
    [2024-06-19 10:35:45]   FCF=08/General/Serv->Cli, SQN=04, cmd=0B/Default Response
    [2024-06-19 10:35:45]   Default Response: Cmd=05, Status=01/Operation failed

**Comment by EricGIRARD35** [comment]
Ci dessous les logs après ce test

[AbeilleLogs-240619 (1).tar.gz](https://github.com/user-attachments/files/15899706/AbeilleLogs-240619.1.tar.gz)

**Comment by tcharp38** [comment]
Pas encore regardé tes logs mais je suis rentré chez moi ce midi et j'ai relié ton module à mon ecran electrique Oray.
Résultat... super !!
Une fois le calibrage fait via le bouton Abeille, le set level fait bouger l ecran mais la le niveau obtenu n'est pas celui demandé.
Il y a qqch à creuser ici aussi.
Quoi qu'il en soit, ce module ne me dit pas "cmde non supportée"

A suivre

**Comment by tcharp38** [comment]
Tes logs disent

05/goToLiftPercent => pas supporté

    [2024-06-19 12:56:22] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=5B5B, DstAddrMode=02, DstAddr=0000
    [2024-06-19 12:56:22]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-19 12:56:22]   Default Response: Cmd=05, Status=81/Unsupported cluster command

Peux tu faire la meme manip avec goTo**Tilt**Percent ?

**Comment by EricGIRARD35** [comment]
C'est fait log ci dessous

[Uploading AbeilleLogs-240619 (2).tar.gz…]()

**Comment by tcharp38** [comment]
Bah non, log pas téléchargé. Upload incomplet :(

**Comment by EricGIRARD35** [comment]
Deuxième essai...

[AbeilleLogs-240619 (2).tar.gz](https://github.com/user-attachments/files/15904285/AbeilleLogs-240619.2.tar.gz)

**Comment by tcharp38** [comment]
Et cette commande est toujours interdite

    [2024-06-19 17:19:14] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0102, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=5B5B, DstAddrMode=02, DstAddr=0000
    [2024-06-19 17:19:14]   FCF=00/General/Cli->Serv, SQN=00, cmd=0B/Default Response
    [2024-06-19 17:19:14]   Default Response: Cmd=08, Status=81/Unsupported cluster command

Desesperant.
Il y a clairement une difference de comportement avec le module que j'ai avec lequel en fait le "set level" est fonctionnel.
Pas tres précis mais ca le fait. Le seul souci est quand on inverse la rotation moteur, il faudrait faire un calcul different pour le set level du style "100 - level" au lieu de "level"

Peux tu me regenerer un discovery avec ta derniere version de firmware ?
Désolé que ca patauge comme ça.

**Comment by tcharp38** [comment]
P.... je crois que j'ai une piste.

Ta Zigate a un ancien FW, le 3.21.
Le dernier en date est le 3.23.. et quand tu regardes la release notes tu vois ça

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/f6955d6b-3a5f-4517-b58c-0b32ce7cbbf3)

Donc ... mets à jour ta Zigate STP.
Note que tu es en version "legacy" du FW (0003)
Il est fortement recommandé de passer en version "OPDM" (0004) => 0004-0323
mais pour ca il te faudra effacer l EEPROM et tout réappairer. Ca peut donc attendre

https://github.com/fairecasoimeme/ZiGate/releases

**Comment by EricGIRARD35** [comment]
Salut,

Oui en effet il faut que je mette à jour le FW de ma zigate

.Il me faut retrouver la clé USB-TTL je le fait des que j'ai mis la main
dessus

Merci

**Comment by tcharp38** [comment]
Pourquoi as tu besoin de cette clé USB-TTL ?
Si Zigate USB il te suffit de la brancher sur un PC en maintenant le bouton appuyé puis d'utiliser le soft du site Zigate.

**Comment by EricGIRARD35** [comment]
J'ai eu pas mal de soucis pour faire la mise a jour. Le pilote proposé sur le site de Zigate ne semble pas compatible avec Windows 11. L'installation se passe bien et le port de com est visible dans le gestionnaire de périphérique mais pas reconnu par l'appli pour flasher la clé.
Bref j'ai finalement réussi avec un vieux PC et houra ca fonctionne;) Un grand MERCI a toi.
Il reste juste un petit détail la visualisation  du Level qui est inversé. Je m'explique lorsque le volet est fermé le Level indique 100% et l'icone indique ouvert (icone gris). A l'inverse quand je demande de monté physiquement le volet monte et je vois l'icone du volet qui descend.

**Comment by tcharp38** [comment]
Haaaaaa.. enfin.

Pour le level j'ai noté ça aussi. Je vais revoir le modele.
Je vais aussi virer "Invert" car pas sur que le comportement du level soit le meme dans les 2 cas et il est facile de cabler à l'inverse.

A suivre..

**Comment by tcharp38** [comment]
Je pousse une beta pour demain. Ca semble etre ok de mon coté
Une fois que tu as basculé dessus => EQ/avancé puis reinitialiser.

**Comment by EricGIRARD35** [comment]
Salut,
J'ai installé la Beta et réinitialisé de mon coté toujours pareil ca fonctionne bien mais l'affichage dans le Dashboard est inversé quand le volet s'ouvre il se ferme sur l'affichage du Dashboard.

**Comment by tcharp38** [comment]
Salut
Tu as besoin de faire un "reinitialiser" via l'onglet avancé.
Et penses à me filer le package de logs.

**Comment by EricGIRARD35** [comment]
Salut,

Ci joint les log. J'avais déjà fait un "reinitialiser" via l'onglet avancé et je l'ai refais aujourd'hui.
Maintenant tout fonctionne correctement je ne comprend pas mais c'est OK

[AbeilleLogs-240624 (1).tar.gz](https://github.com/user-attachments/files/15954752/AbeilleLogs-240624.1.tar.gz)

**Comment by tcharp38** [comment]
Haaaaaaaa. Cool
Je peux fermer le sujet du coup ou il manque qqch ?

**Comment by EricGIRARD35** [comment]
Oui c'est bon tu peux fermer le sujet tout fonction correctement

**Comment by tcharp38** [comment]
Parfait. Je ferme

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
