### ISSUE TITLE
Prise routeur TS011F remonte mauvaises infos sur ses enfants en les designant routeurs eux aussi

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#2711]
Suite du #2676

En résumé une prise TS011F/Yagusmart Tuya ZigBee Smart Switch remonte de mauvaises infos LQI en indiquant que ses enfants sont routeurs alors qu'ils sont End Device.

Ca entraine des interrogations regulieres d'Abeille, sans reponse du device car dormant, et donc une latence dans les commandes.

**Comment by tcharp38** [comment]
@MichelCHAVOT 
Je vois 3 prises avec le meme modele TS011F
Sont elle identiques ?
Si oui je m'attends à ce que tous les enfants de chaque prise soient considérés comme "routeurs"

J'imagine que tu es sur la derniere beta, en tout cas sur qqch de + avancé que les derniers logs sur le sujet.
Du coup peux tu me faire un raffraichissement reseau et me filer le package de logs
+ AbeilleLQI-Abeille1.json que tu peux avoir via la page maintenance aussi
Merci

**Comment by MichelCHAVOT** [comment]
Bonjour.

Les 3 prises :
Lampe sud : adresse F125, identifiant zigbee TS011F, modèle d’équipement TS011F
Chauffage cabine 3D : adresse 3C7E, identifiant zigbee TS011F, modèle d’équipement TS011F
Chambre Parents : adresse 7183, identifiant zigbee TS011F, modèle d’équipement TS011F
sont identiques (sans mesure de puissance, courant, tension).

J’ai aussi 3 prises avec mesure de puissance, courant, tension :
Prise Frigo : adresse 07E7, identifiant zigbee TS011F, modèle d’équipement TS011F__TZ3000_gvn91tmx
Prise TV : adresse A0BD, identifiant zigbee TS011F, modèle d’équipement TS011F__TZ3000_cphmq0q7
Pompe Piscine : adresse 25CB, identifiant zigbee TS011F, modèle d’équipement TS011F__TZ3000_cphmq0q7

Je suis en version Beta : 2024-05-20 01:00:22

ci-joint les logs après réinterrogation réseau.
[AbeilleLQI-Abeille1.json.log](https://github.com/user-attachments/files/15751971/AbeilleLQI-Abeille1.json.log)
[AbeilleLogs-240609.tar.gz](https://github.com/user-attachments/files/15751976/AbeilleLogs-240609.tar.gz)

**Comment by tcharp38** [comment]
Salut
Manque de pot je ne vois pas l'information que je cherche dans mes logs actuels.
En gros je cherche à savoir quelle version de FW a chaque prise pour voir si il y a une difference. Le fait qu'elles sont toutes du meme modele ne prouve rien du tout.

Regarde sur l'onglet avancé, tu as 2 infos

![image](https://github.com/KiwiHC16/Abeille/assets/35221038/f3b29b82-20dd-4bc3-8d73-da4f779f3415)

Si l'info n'est pas la, tu peux tenter "réparer".

**Comment by MichelCHAVOT** [comment]
Salut.
Les 2 infos que tu me demandes ne remontent pas, même en tentant "réparer" (plusieurs fois jusqu'à avoir le bouton "fermer")
ci-joint les copies écran de toutes mes prises.
[Prises onglet avancé.pdf](https://github.com/user-attachments/files/15840799/Prises.onglet.avance.pdf)

**Comment by tcharp38** [comment]
Le "manuf code" à 0000 prouve a quel point ce firmware est baclé.
Donc pas surprenant que les autres infos ne remontent meme pas.

Je vais reflechir à une autre alternative pour essayer d'utiliser une info + fiable, mais quel gachi de temps ces produits baclés.
TODO: ignorer "LQI management response" pour type de neighbor.

**Comment by tcharp38** [comment]
Je pousse pour la beta de demain, un changement qui doit aider ce souci.

En gros je ne fais plus confiance à l 'info remontée par les routeurs (en particulier a cause de ces prises mais j'avais vu ca aussi chez Ikea). Je detecte le type de device autrement (en utilisant le node descriptor/logical type).

Bref une fois la mise à jour faite
tu dois faire un repair de tes prises pour etre sur que l info "logical type" est connue (voir onglet avancé)
puis la tu peux faire un refresh network.
Je m'attends a ce que les enfants ne soient plus consideres comme routeurs.

**Comment by MichelCHAVOT** [comment]
Bonjour.
Ok, merci, je teste çà demain. Es-tu intéressé par les logs qui vont en découler ?

**Comment by tcharp38** [comment]
Oui bien sur.
Surtout si ca ne se comporte pas comment j'imagine

**Comment by MichelCHAVOT** [comment]
Bonjour.
Ci-joint les logs après mise à jour en Beta 2024-06-18 01:00:22
J’ai 9 capteurs de température.
Les noms de ces capteurs commencent tous par les 2 caractères T°
Après scan du réseau, je constate :
Les 2 capteurs « T° Extérieur » et « T° Piscine » sont OK (End Device)
Le capteur « T° Cabine 3D » sort en Router
Le capteur « T° Filles » sort soit en router, soit en End Device
Les 5 capteurs « T° AptChambre », « T° AptSejour », « T° Parents », « T° Quentin », « T° Séjour » n’apparaissent plus dans le scan, **alors qu’ils fonctionnent toujours.**
[AbeilleLQI-Abeille1.json.log](https://github.com/user-attachments/files/15886701/AbeilleLQI-Abeille1.json.log)
[AbeilleLogs-240618.tar.gz](https://github.com/user-attachments/files/15886703/AbeilleLogs-240618.tar.gz)

**Comment by tcharp38** [comment]
Plus la peine de m'envoyer AbeilleLQI.json. Il fait maintenant partie du package.

Qq améliorations
A decompresser dans Abeille/core/php
[AbeilleLQI.zip](https://github.com/user-attachments/files/15888477/AbeilleLQI.zip)

Les capteurs de temps ne donnaient pas avant l'info de type logique que j utilise maintenant. Du coup ca n'est pas utilisé pour savoir si ils sont reellement "routeur".
Au moins la ils ne devraient plus etre interrogés comme routeur mais dans l'immédiat le report restera faux..

**Comment by MichelCHAVOT** [comment]
J'ai chargé le fichier dans Abeille/core/php.
J'ai redémarré le démon.
En lançant l'analyse du réseau, j'obtiens le message d'erreur: **ERREUR: Cmd 'getNeightborTable': Paramètre 'addr' vide !**
Ensuite, çà boucle avec à chaque boucle le message: **Analyse du réseau : X/0=> interrogation de 'Inconnu-' ()**
avec X qui commence à 0, augmente de 1 à chaque boucle, la boucle est sans fin.
Obligé de redémarrer le démon pour sortir de la boucle.
Du coup je suis revenu à la version précédente du fichier. A noter, et que j'ai oublié de te dire tout à l'heure, c'est qu'avec la dernière Béta, j'ai perdu la commande timeTime sur tous les devices.
Si je reviens à ma sauvegarde de cette nuit, je retrouve cette commande.

**Comment by tcharp38** [comment]
Question rapide... tu utilises la commande "Time-Time" pour quoi ?
Si il n'y a que "Time-TimeStamp" ca le fait ?

Pense à me filer le package de logs quand c'est comme ca. Ca aide à trouver une piste.
De mon coté ca ne boucle pas, et pas d erreur, d'ou la necessité des logs

**Comment by MichelCHAVOT** [comment]
Bonjour.
Je suis reparti de la dernière version Beta.
J'ai vidé tous les logs.
J'ai copié le fichier AbeilleLQI.php dans Abeille/core/php
J'ai redémarré le démon.
J'ai lancé l'analyse réseau.
Je l'ai laissé faire 45 boucles (j'ai 42 équipements dans mon réseau en comptant les télécommandes virtuelles)
J'ai redémarré le démon pour sortir de la boucle.
Voici les logs :
[AbeilleLogs-240619.tar.gz](https://github.com/user-attachments/files/15896702/AbeilleLogs-240619.tar.gz)

Concernant le timeTime, je l'affiche sur tous mes capteurs de température. Ce modèle à la fâcheuse habitude de se bloquer quand la batterie descend en dessous de 70 à 80%, et le timeTime me permet de voir quand a eu lieu la dernière transmission.
Je le préfère au timeStamp qui prend plus de place à l'affichage.

**Comment by tcharp38** [comment]
Désolé pour les patchs

En voila un autre
[AbeilleLQI.zip](https://github.com/user-attachments/files/15897721/AbeilleLQI.zip)

Concernant Time-Time.. j'ouvre un sujet dédié.

**Comment by tcharp38** [comment]
Quel est le status de ce sujet sur la derniere beta du jour ?

**Comment by MichelCHAVOT** [comment]
Pour moi, c'est OK, tous les routeurs sont en bleu, tous les End Device sont en vert.

**Comment by tcharp38** [comment]
Ok je ferme ce sujet du coup.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
