### ISSUE TITLE
Erreur: Cmd 'getNeighborTable': Paramètre 'addr' vide !

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2713]
Hello,

```
RPi4b Debian 11 uptodate
Jeedom stable 4.4.7
Abeille 240618-BETA-5
```

Depuis la dernière beta, je reçois en permanence le message suivant : 
`Erreur: Cmd 'getNeighborTable': Paramètre 'addr' vide !`
Aucune incidence sur mon installation.

Package de logs : 
[AbeilleLogs-240621.tar.gz](https://github.com/user-attachments/files/15924581/AbeilleLogs-240621.tar.gz)

Merci d'avance,
Xav

**Comment by tcharp38** [comment]
Salut @Xav-74 
Oui désolé.
Ca doit être lié à mes changements dans l'analyse réseau.

Peux tu décompresser ce fichier dans Abeille/core/php ?
[AbeilleLQI.zip](https://github.com/user-attachments/files/15928270/AbeilleLQI.zip)

Je pousse une autre beta au plus vite

**Comment by Xav-74** [comment]
Pas de stress c'est absolument pas bloquant ;)
Je viens de remplacer le fichier et de redémarrer le démon.
Je te tiens au jus si le message réapparait !

A+

**Comment by Xav-74** [comment]
Hello @tcharp38 

Pour info, message de retour ce matin, j'imagine au moment de l'interrogation du LQI ;)
A ta dispo pour tester si besoin,

Xav

**Comment by tcharp38** [comment]
Hello
Zut. Peux tu relancer le rafraichissement reseau et me filer les logs dans la foulée ?
J'ai testé a nouveau de mon cote et aucune erreur.

Je pousse une beta pour demain dans tous les cas.

**Comment by Xav-74** [comment]
Voici les logs : 
[Abeille.zip](https://github.com/user-attachments/files/15937217/Abeille.zip)

Comme dit ici : https://github.com/KiwiHC16/Abeille/issues/2714
Impossible de télécharger tous les logs. Je les ai donc mis à la main. S'il te manque qqchose dis moi

**Comment by tcharp38** [comment]
J'ai un doute sur l'endroit ou tu as décompressé le fichier.
Donc bascule sur la beta de demain, sans ajout manuel.

Quant aux logs non générés... il faut que j'améliore ca car je n'ai aucune visibilité sur le pb que je ne reproduis pas de mon coté.

**Comment by tcharp38** [comment]
Je crois que j'ai pigé le pb de creation de package.
Ca merde si aucun scan reseau n existe.

Correction dans la beta de demain
Sinon voila le fichier à decompresser dans Abeille/core/ajax
[AbeilleFiles.ajax.php.zip](https://github.com/user-attachments/files/15938053/AbeilleFiles.ajax.php.zip)

**Comment by Xav-74** [comment]
Alors dans l'ordre : 
- copie du fichier AbeilleLQI.php (que tu as mis récemment dans l'issue #2714)
- copie du fichier AbeilleFiles.ajax-php
- relance du démon
- scan du réseau
- attente 1min
- collecte des logs complets

[AbeilleLogs-240622.tar.gz](https://github.com/user-attachments/files/15938148/AbeilleLogs-240622.tar.gz)

**Comment by Xav-74** [comment]
Hello !

Bon pas mieux pour moi avec la nouvelle beta.
Voici les logs
 
[AbeilleLogs-240623.tar.gz](https://github.com/user-attachments/files/15945218/AbeilleLogs-240623.tar.gz)

**Comment by tcharp38** [comment]
Le sujet étant commun avec le #2714, je ferme celui ci et on continue la bas.
