### ISSUE TITLE
Problème scan réseau depuis la beta 2024-06-19 01:00:23

### ISSUE THREAD

**Issue by MichelCHAVOT** [KiwiHC16/Abeille#2714]
Bonjour.
Depuis que j'ai installé cette version beta (2024-06-19 01:00:23), le scan réseau ne fonctionne plus.
Une fois que le scan est lancé, il y a environ 6 erreurs par minute (toujours la même).
Le message est le suivant : ERREUR: Cmd 'getNeighborTable': Paramètre 'addr' vide !
Après le redémarrage de jeedom, cette erreur se produit aussi bien quand on lance le scan réseau manuellement, que lors du scan automatique qui démarre journalièrement après minuit.
Quand je lance le scan réseau manuellement, il y a un scan d'équipement toutes les 10s, avec à chaque équipement le même message d'erreur qui s'affiche : Analyse du réseau : X/0 => interrogation de 'Inconnu-' ()
X s'incrémentant de 1 à chaque boucle, et çà boucle non stop. (sauf à relancer le démon)
De plus, quand je lance la commande "télécharger tout" dans les logs, çà ne fonctionne plus. j'ai le message : 
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/1e70893c-386e-489d-bc11-11255fad91cf)
pourtant, il y a bien de la place sur /tmp : 
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/c7c01c18-e887-4afa-87ca-4375a2a59755)
Le téléchargement des fichiers 1 par 1 fonctionne toujours.
Les voici : 
[Abeille.zip](https://github.com/user-attachments/files/15936956/Abeille.zip)

**Comment by tcharp38** [comment]
@MichelCHAVOT 
Le dernier LQI collector qui est dans la beta de demain est celui ci 
[AbeilleLQI.zip](https://github.com/user-attachments/files/15937964/AbeilleLQI.zip)

Vu les erreurs que tu as on n'est pas en ligne.
Si tu veux tester avant la beta de demain.. il est à décompresser dans Abeille/core/php
et refaire un raffraichissement reseau.

**Comment by MichelCHAVOT** [comment]
Bonjour.
J’ai préféré attendre la version beta que je viens de télécharger.
Je suis donc en Beta 2024-06-23 01:00:30.
J’ai lancé le scan du réseau dans la foulée.
Le scan ne boucle plus, et le téléchargement des logs fonctionne.
Mes remarques :
Sur mes 9 capteurs de température (dont les noms commencent tous par les 2 caractères T°), seuls 4 apparaissent dans le scan :
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/689dcb94-7181-4964-b537-16c4ac1f6744)
Sur ces 4, 2 apparaissent en router avec un lqi à 0.
Je remarque aussi que les lqi ne correspondent pas à ceux affichés sur les widgets :
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/d8a531b9-84a1-43f3-abb1-50351e6cb1da)
Voici les logs : (le téléchargement des logs refonctionne)
[AbeilleLogs-240623.tar.gz](https://github.com/user-attachments/files/15943873/AbeilleLogs-240623.tar.gz)
J’attends 1 heure, car normalement tous mes capteurs ont communiqué leur température au moins 1 fois, sinon ils passent en time out.
Je relance le scan après 1h1/4
Une seule boucle dans le scan, et résultat : aucun équipement dans le scan.
Voici les logs :
[AbeilleLogs-240623 (1).tar.gz](https://github.com/user-attachments/files/15943881/AbeilleLogs-240623.1.tar.gz)
Je redémarre le démon.
Je relance le scan réseau.
Même résultat : 1 seule boucle et aucun équipement dans le scan.
Je redémarre jeedom (par la commande système redémarrer)
J’attends quelques minutes et je relance le scan réseau.
Sur mes 9 capteurs de température, seuls 5 apparaissent dans le scan :
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/f600c2ef-2e96-4596-8234-affe045b87d5)
voici les logs : 
[AbeilleLogs-240623 (2).tar.gz](https://github.com/user-attachments/files/15943886/AbeilleLogs-240623.2.tar.gz)
¼ d’heure plus tard, après vérification que toutes mes températures ont été mises à jour au moins une fois, je relance un scan réseau.
Le scan fonctionne, mais je ne retrouve pas tous mes capteurs de température :
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/2e47f986-58e5-4198-98e6-fd7e4820f1bf)
Voici les logs :
[AbeilleLogs-240623 (3).tar.gz](https://github.com/user-attachments/files/15943888/AbeilleLogs-240623.3.tar.gz)
NB : quand le scan fonctionne, il effectue bien 21 boucles (le nombre de mes équipements branchés sur le secteur et donc à priori routeurs).

**Comment by MichelCHAVOT** [comment]
Je modifie mon NB:
La première boucle est notée 1/8
La 2ème boucle est notée 2/21
La 3ème 3/21
...
La dernière 20/21
ensuite message collecte terminée.
çà fait 20 boucles et non pas 21. Pour moi, il devrait y en avoir 21.

**Comment by tcharp38** [comment]
@Xav-74 @MichelCHAVOT 

Le premier qui peut tester ça et me filer ses logs..
A decompresser dans Abeille/core/php
[AbeilleLQI.zip](https://github.com/user-attachments/files/15951305/AbeilleLQI.zip)

**Comment by Xav-74** [comment]
Alors, après mise à jour du fichier et relance du démon, je n'ai plus l'erreur :
ERREUR: Cmd 'getNeighborTable': Paramètre 'addr' vide !
J'ai un message : `init` mais ensuite rien. Pas d'interrogation des devices

Voici les logs
[AbeilleLogs-240624.tar.gz](https://github.com/user-attachments/files/15952649/AbeilleLogs-240624.tar.gz)

**Comment by tcharp38** [comment]
Merci.

Nouvel essai avec ça STP
[AbeilleLQI.zip](https://github.com/user-attachments/files/15953897/AbeilleLQI.zip)

**Comment by Xav-74** [comment]
Merci pour ton aide !
Nouveau test, mais pas de changement à priori

[AbeilleLogs-240624.tar.gz](https://github.com/user-attachments/files/15955386/AbeilleLogs-240624.tar.gz)

**Comment by tcharp38** [comment]
Je ne comprends toujours pas mais je modifie les messages et j'ajoute des controles.
Nouvelle tentative
[AbeilleLQI.zip](https://github.com/user-attachments/files/15955672/AbeilleLQI.zip)

**Comment by Xav-74** [comment]
👍 
Cette fois ci, message collecte terminée mais pas de devices

[AbeilleLogs-240624.tar.gz](https://github.com/user-attachments/files/15955926/AbeilleLogs-240624.tar.gz)

**Comment by tcharp38** [comment]
Ca avance.

A decompresser dans Abeille/core/class
[Abeille.class.php.zip](https://github.com/user-attachments/files/15956129/Abeille.class.php.zip)

puis redemarrer Abeille
et refaire scan reseau

**Comment by Xav-74** [comment]
Beaucoup mieux 👍 
Ca fonctionne bien cette fois-ci. 14 itérations qui correspondent bien à mes 13 modules sur secteurs + la ruche !

[AbeilleLogs-240624.tar.gz](https://github.com/user-attachments/files/15956417/AbeilleLogs-240624.tar.gz)

Thx !

**Comment by tcharp38** [comment]
Oui c'est mieux, mais dans ton cas un router n'a pas répondu.. le D148 (AB Prise Garage)

    [2024-06-24 15:27:24] Interrogating 'AB Prise Garage' (D148)
    [2024-06-24 15:27:24] interrogateEq(Abeille1, D148, 13)
    [2024-06-24 15:27:24]   msgToCmd: {"topic":"CmdAbeille1/D148/getNeighborTable","payload":"startIndex=00"}
    [2024-06-24 15:27:24]   msgFromParser(eqIndex=13)
    [2024-06-24 15:27:34]   Time-out !

Normal ?

**Comment by tcharp38** [comment]
Les derniers correctifs sont dans la beta de demain.

**Comment by Xav-74** [comment]
Ah oui non pas normal.
Enfin...
J'ai eu une grosse coupure d'élec ce week-end, et j'ai 2, prises qui n'ont pas redémarré (elles sont HS et supprimé de Abeille).
Je n'ai pas testé celle du garage. Je te redis qd je rentre ce soir.

**Comment by tcharp38** [comment]
HS ?
La D148 est toujours dans le reseau et effectivement .. je ne sais pas comment la virer quand elle est morte. Normalement un device quitte lui meme le reseau.

**Comment by Xav-74** [comment]
En fait quand je dis HS, elle reste connecté au réseau mais quand la prise est allumée, l'interrupteur bascule en permanence entre on et off :(
Du coup je la déconnecte pour éviter les soucis électriques ! Et celle de mon garage est actuellement éteinte donc je ne sais pas trop son état actuel !

**Comment by MichelCHAVOT** [comment]
Bonjour.
J'ai testé ton dernier fichier (https://github.com/KiwiHC16/Abeille/issues/2714#issuecomment-2186537063).
J'ai redémarré le démon.
J'ai lancé le scan.
Une première boucle avec le scan de la ruche, puis plus rien, message collecte terminée.
Idem après redémarrage de jeedom.
Voici les logs : 
[AbeilleLogs-240624.tar.gz](https://github.com/user-attachments/files/15958799/AbeilleLogs-240624.tar.gz)

**Comment by Xav-74** [comment]
Juste une remarque sur la dernière version que tu m'as envoyé : 

Tous mes devices sour 220v (donc routeur) sont passés en timeout. Mais fonctionne correctement.
Dans les logs, j'ai : 
`updateTimestamp(): WARNING: Abeille1/F5E1, missing cmd 'Time-Time'`
Ca ne dvrait pas être `Time-TimeStamp'` ??

**Comment by tcharp38** [comment]
@Xav-74 
Je pense que c'est normal. Je ne t'ai filé qu'une partie des modifs.. ca doit expliquer.
Le "Time-TimeStamp" je l'ai viré. Voir #2712 

@MichelCHAVOT 
Idem. Je vous laisse basculer sur la beta demain et refaire le point sans modif de fichier.

**Comment by Xav-74** [comment]
Ok ça marche ! 
Par contre besoin de refaire une mise à jour de chaque eqpt ou ce sera automatique pour supprimer la commande time-timestamp et créer la commande Time-Time ?

**Comment by tcharp38** [comment]
Ha non ca sera automatique.

**Comment by Xav-74** [comment]
Tout est OK pou moi ce matin. Collecte réseau OK sur mes 14 devices (prise gararge OK cette fois)
et plus de timeout ;)

Merci pour ton aide

**Comment by tcharp38** [comment]
Cool.
Pour info j'ai du revoir cette partie à cause de devices (prises TS011F) qui renvoient de fausses infos.

@MichelCHAVOT 
Ca dit quoi de ton côté ?

**Comment by MichelCHAVOT** [comment]
Beta du 25/6 installée.
Le scan du réseau tourne et les 21 équipements sont scannés.
Je n'ai contrôlé que mes capteurs de température, et sur les 9, 2 remontent en routeur, 2 en end device avec un lqi qui n'est pas celui affiché sur le dashboard.
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/6b8468f0-54c1-4091-bd87-9ccebda663b4)
Hormis le capteur de la piscine qui ne fait une mise à jour que toutes les 10 minutes, les autres ont pourtant un rafraichissement qui dépasse rarement la minute.
![image](https://github.com/KiwiHC16/Abeille/assets/36966985/3f63476d-86d2-40e6-b220-0c3b2c6f3f24)
voici les logs : 
[AbeilleLogs-240625.tar.gz](https://github.com/user-attachments/files/15966897/AbeilleLogs-240625.tar.gz)

**Comment by tcharp38** [comment]
@MichelCHAVOT 
Voila un nouveau code à tester.
[AbeilleLQI.zip](https://github.com/user-attachments/files/15968013/AbeilleLQI.zip)

**Comment by tcharp38** [comment]
Je pousse une beta pour demain 
avec des améliorations dans le graphique des liens et le routage reseau.

**Comment by tcharp38** [comment]
Avant de fermer ce sujet, je résume
- le pb de base est que parfoit de fauses infos remontent des routeurs faisant croire qu'un enfant est router alors qu'il est "end device"
- ces données sont ignorées
- au lieu de ça les infos remontées par l'enfant lors de son inclusion sont directement prises en compte
- d'autre part si le routeur ne repond pas il y a maintenant 3 tentatives

**Comment by MichelCHAVOT** [comment]
Voici les logs après mise en place de ton dernier fichier AbeilleLQI.php. J'ai fait tourner le scan réseau 2 fois après avoir redémarrer jeedom.
[AbeilleLogs-240704.tar.gz](https://github.com/user-attachments/files/16100755/AbeilleLogs-240704.tar.gz)

**Comment by tcharp38** [comment]
Salut @MichelCHAVOT
Un très grand merci pour ta donation.
