### ISSUE TITLE
Ajout support Sonoff SNZB-01P (id = SNZB-01P, eWeLink)

### ISSUE THREAD

**Issue by VVorttexx** [KiwiHC16/Abeille#2716]
Bonjour, 
pourriez vous ajouter le bouton Sonoff SNZB-01P eWeLink
(dans le genre du SNZB-01, 3 etats : 1 click, 2 click, click long)

[SNZB-01P.zip](https://github.com/user-attachments/files/16120435/SNZB-01P.zip)
(le PNG est dans le zip..

Merci

**Comment by tcharp38** [comment]
Salut @VVorttexx
Pas sur de pouvoir avancer la dessus avant mon retour en août.

Note qu il se pourrait que tu doives basculer sur la dernière bêta Abeille. A toi de voir si tu anticipes ou pas.
A bientôt

**Comment by VVorttexx** [comment]
Hello,  
pas de Pb pour le délai, 
je suis déjà sur la bêta 2024-07-05 01:00:24, il faut anticipé quoi ? :-)

**Comment by tcharp38** [comment]
Tiens, voila un modele preliminaire.
[SNZB-01P_eWeLink.zip](https://github.com/user-attachments/files/16158006/SNZB-01P_eWeLink.zip)

A decompresser dans Abeile/core/config/devices
puis redemarrer Abeille
puis refaire inclusion

Sera dans la beta de demain

**Comment by VVorttexx** [comment]
Hello, merci, je viens de l'installer à distance, je regarderais ce soir en activant le device, pour l'instant pas de nouvelle commande...merci et bonnes vacances.

**Comment by VVorttexx** [comment]
Hello, bon pas de nouvelle commande, il prend bien le modèle cependant. Jje remets le discovery au cas ou, sinon cela attendra. 
merci.
[discovery-SNZB-01P_eWeLink (1).zip](https://github.com/user-attachments/files/16171445/discovery-SNZB-01P_eWeLink.1.zip)

**Comment by tcharp38** [comment]
C'est un bouton donc il doit générer des actions du style click court, double, long

Il faudra faire ces essais en notant l'heure et me filer le package de logs

**Comment by VVorttexx** [comment]
Ok pour tous les type de click
C'est l'id 770 18h47 et 18h49 
[AbeilleLogs-240711 (1).tar.gz](https://github.com/user-attachments/files/16181028/AbeilleLogs-240711.1.tar.gz)
Merci

**Comment by tcharp38** [comment]
Salut @VVorttexx 
Me voila de retour.

J'ai l'impression que tu n'es pas en mode debug.
A corriger via la page de config + sauvegarder + redemarrer démon.

Ensuite peux tu refaire la meme manip ?

**Comment by VVorttexx** [comment]
Hello j'espère que tu as passé de bonnes vacances. 
voici, cette fois en mode debugg, j'ai appuyé plusieurs fois 1 click 2 clic et click long. 
18:49 normalement tjrs id 770
[AbeilleLogs-240730.tar.gz](https://github.com/user-attachments/files/16431151/AbeilleLogs-240730.tar.gz)
Merci

**Comment by tcharp38** [comment]
Memo

    [2024-07-30 18:49:27][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/EA31/01'
    [2024-07-30 18:49:27][DEBUG] :   Unknown Jeedom command logicId='01-0006-cmd02'
    [2024-07-30 18:49:31][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/EA31/01'
    [2024-07-30 18:49:31][DEBUG] :   Unknown Jeedom command logicId='01-0006-cmd00'
    [2024-07-30 18:49:34][DEBUG] : msgFromParser(): Attributes report by name from 'Abeille1/EA31/01'
    [2024-07-30 18:49:34][DEBUG] :   Unknown Jeedom command logicId='01-0006-cmd01'

**Comment by tcharp38** [comment]
A decompresser dans core/config/devices/SNZB-01P_eWeLink
[SNZB-01P_eWeLink.zip](https://github.com/user-attachments/files/16433565/SNZB-01P_eWeLink.zip)

puis via la page de l'equipement + avancé.. faire mise à jour ou reinitialiser

puis tester
Tu dois avoir une commande info "Click" qui prend la valeur "single", "double", ou "long".

**Comment by VVorttexx** [comment]
bonjour, 
alors cela fonctionne, le bouton change bien l'etat click, peut être juste un détail, la valeur apparait avec un 'null' derrière:
![image](https://github.com/user-attachments/assets/1fb4a754-bb74-41bc-888e-129b8368b525)
pour comparaison avec un SNZB-01
![image](https://github.com/user-attachments/assets/f4b2212e-c2b2-417b-9e2f-6fe28924c2f1)
mais peut être est ce du au modèle?

le temps de faire le test avec l'autre bouton, la valeur a cahnger:
![image](https://github.com/user-attachments/assets/ffa5cf45-3d48-40c1-be70-5ad28d1c7f85)
ça passe de single null a single.
merci

**Comment by VVorttexx** [comment]
Bon j'ai quand même fait le scenario dédié et cela fonctionne bien avec #[Cuisine][Sonoff_comptoir][Click]# == 'single'  
il n'y a pas de temps de latence, donc c'est bon pour moi. 
Merci beaucoup Tcharp!

**Comment by tcharp38** [comment]
Salut

Est ce que les 3 clicks sont ok ? (single, double, long)
Peux tu faire un test et me filer le package de logs. Je veux comprendre pourqui il y a ce "null" derriere

**Comment by VVorttexx** [comment]
oui les 3 fonctionnent, voici les logs après plusieurs allés retours sur les 3 types de clicks.  18:18
[AbeilleLogs-240801.tar.gz](https://github.com/user-attachments/files/16459347/AbeilleLogs-240801.tar.gz)

**Comment by tcharp38** [comment]
Bon je ne vois rien coté Abeille concernant l'affichage de ce "null" mais il y a un sujet ouvert chez Jeedom donc probablement un bug Jeedom et non pas Abeille.
Voir https://community.jeedom.com/t/apparait-null-sur-les-commandes-sans-unite/122342

Je ferme le sujet vu que tout semble ok.

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)

**Comment by tcharp38** [comment]
@VVorttexx 
Je crois que c'est à toi que je dois la contribution alors merci bien.
