### ISSUE TITLE
Ajout support Ikea Tretakt - Prise connectée

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2718]
Hello,

Voici les infos de la nouvelle prise connectée Tretakt de Ikea !
Merci d'avance

[discovery-TRETAKTSmartplug_IKEAofSweden.json.zip](https://github.com/user-attachments/files/16156356/discovery-TRETAKTSmartplug_IKEAofSweden.json.zip)

![tretakt-ikea](https://github.com/KiwiHC16/Abeille/assets/56156622/0ac469ff-a1cb-4075-999f-8454db32837b)

Xav

**Comment by tcharp38** [comment]
Salut @Xav-74 
Désolé, impossible d'ouvrir ton zip.

Quoi qu'il en soit je serai hors service jusqu'a debut aout. Il va falloir patienter...

**Comment by Xav-74** [comment]
Hello @tcharp38,

Il suffit juste d'enlever le .zip du nom du fichier ;)
J'aurais du préciser, désolé.

Pas d'urgence, j'ai réussi à la piloter en forçant avec le modèle de la première génération de prise Ikea Tradfri. Je voulais être certain que la nouvelle était pilotable depuis Jeedom et faire qq tests de maillage. Le reste attendra ton retour.

Bonnes vacances 👍

**Comment by tcharp38** [comment]
Alors voila

A decompresser dans Abeille/core/config/devices
[TRETAKTSmartplug_IKEAofSweden.zip](https://github.com/user-attachments/files/16158517/TRETAKTSmartplug_IKEAofSweden.zip)

puis redemarrer
refaire inclusion

Dans la beta de demain

**Comment by Xav-74** [comment]
Tout est OK pour moi excepté l'image que j'ai pourtant mis dans le bon répertoire avec le nom `node_TRETAKTSmartplug_IKEAofSweden.png`. A moins que je me sois trompé ;)
On verra demain avec la beta 👍 

Merci pour ta réactivité !

PS : vu dans le code de la beta pour le nom ;)
