### ISSUE TITLE
LEDVANCE Prise intelligente pour l'extérieur avec technologie ZigBee,

### ISSUE THREAD

**Issue by fab263** [KiwiHC16/Abeille#2720]
Bonjour, 

Cette prise Zigbee de la marque Ledvance est elle prise en charge par Abeille ? 
je suis à la recherche d'une prise zigbee pour l'extérieur et j'ai trouvé ce modèle... Merci

https://www.amazon.fr/gp/product/B0BFK1HPSB/ref=ox_sc_act_title_1?smid=A3CNQCLCFVX8ST&th=1

**Comment by tcharp38** [comment]
Salut
Comme ça ça ne me dit rien mais tu peux voir sur la liste de compatibilité.
Mais on doit pouvoir la supporter.
Attention je vous de nombreux commentaires négatifs sur ton lien, surtout le manque de prise de terre. C'est une sécurité qui fait du sens pour un produit extérieur

**Comment by fab263** [comment]
OK merci je vais voir si jamais il y a une promo. 
j'ai trouvé chez moi une prise Ikéa zigbee qui devrait faire l'affaire en attendant.

**Comment by tcharp38** [comment]
Je ferme le sujet du coup.
A réouvrir si besoin
