### ISSUE TITLE
Virtual remote - Cmd ongroup / offgroup inopérantes - 240819-BETA-1

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2724]
Hello @tcharp38 

Petit souci avec la beta du jour et les tlc virtuelles. Les boutons ongroup et offgroup sont inopérants.
Jeedom v4.4.13 stable
Debian 11 uptodate

```
3479|[2024-08-20 21:33:13] -- execute([Maison][Tlc Espace Nuit][Off group], type=action, options={"background":"0"})
3480|[2024-08-20 21:33:13] -- request: '#addrgroup#' replaced => request='cmd=00&addrMode=01&addrGroup=0003'
3481|[2024-08-20 21:33:13] -- Msg sent: {"topic":"CmdAbeille1/rc02/cmd-0006","payload":"cmd=00&addrMode=01&addrGroup=0003"}
3482|[2024-08-20 21:33:13] Msg from 'xToCmd': {"topic":"CmdAbeille1/rc02/cmd-0006","payload":"cmd=00&addrMode=01&addrGroup=0003"}
3483|[2024-08-20 21:33:13]   processCmd({"name":"cmd-0006","cmdParams":{"cmd":"00","addrMode":"01","addrGroup":"0003","addr":"rc02"},"priority":2,"repeat":0,"dest":"Abeille1"})
3484|[2024-08-20 21:33:13]   cmd-0006: addrMode=01, addr=, cmd=00
3485|[2024-08-20 21:33:13]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0092, Payload=01010100, Addr=, AddrMode=01, Repeat=0)
3486|[2024-08-20 21:33:13]     Zg 1 queues: Pri1=0, Pri2=1, Pri3=0
3487|[2024-08-20 21:33:13] processCmdQueues(): ZgId=1, Pri=2/Idx=0, NPDU=0, APDU=1
3488|[2024-08-20 21:33:13]   sendCmdToZigate(Dest=Abeille1, addr=, cmd=0092, datas=01010100)
3489|[2024-08-20 21:33:13] processAcks(): msg={"type":"8000","net":"Abeille1","status":"06","sqn":"00","sqnAps":"A9","packetType":"0092","nPDU":"00","aPDU":"00"}
3490|[2024-08-20 21:33:13]   WARNING: Zigate cmd failed (err 06)
3491|[2024-08-20 21:33:13]   Removing cmd from queue (Pri=2/Idx=0/Count=1)
3492|[2024-08-20 21:33:13]   Queue count after=0
3493|[2024-08-20 21:33:13] Msg from 'xToCmd': {"priority":1,"topic":"TempoCmdAbeille1/0000/zgSoftReset&delay=20","payload":""}
3494|[2024-08-20 21:33:13] Msg from 'xToCmd': {"topic":"CmdAbeille1/0000/zgSoftReset","payload":""}
3495|[2024-08-20 21:33:13]   processCmd({"name":"zgSoftReset","cmdParams":{"addr":"0000"},"priority":2,"repeat":0,"dest":"Abeille1"})
3496|[2024-08-20 21:33:13]     addCmdToQueue2(Pri=2, Net=Abeille1, ZgCmd=0011, Payload=, Addr=, AddrMode=, Repeat=0)
3497|[2024-08-20 21:33:13]     Zg 1 queues: Pri1=0, Pri2=1, Pri3=0
3498|[2024-08-20 21:33:13] processCmdQueues(): ZgId=1, Pri=2/Idx=0, NPDU=0, APDU=0
3499|[2024-08-20 21:33:13]   sendCmdToZigate(Dest=Abeille1, addr=, cmd=0011, datas=)
3500|[2024-08-20 21:33:13] processAcks(): msg={"type":"8000","net":"Abeille1","status":"00","sqn":"00","sqnAps":"00","packetType":"0011","nPDU":"00","aPDU":"00"}
3501|[2024-08-20 21:33:13]   Removing cmd from queue (Pri=2/Idx=0/Count=1)
3502|[2024-08-20 21:33:13]   Queue count after=0
3503|[2024-08-20 21:33:18] Zg1 status: idle, Pri1=0, Pri2=0, Pri3=0
3504|[2024-08-20 21:33:18] Tempo status: count=6
3505|[2024-08-20 21:33:25] processAcks(): msg={"type":"8012","net":"Abeille1","nPDU":"01","aPDU":"00"}
```

J'ai pas poussé les tests plus loin que cela car pas dispo ce soir et demain. Mais je regarderai plus en détail jeudi.
Les logs si jamais : [AbeilleLogs-240820.tar.gz](https://github.com/user-attachments/files/16681015/AbeilleLogs-240820.tar.gz)

Merci d'avance,

Xav

**Comment by tcharp38** [comment]
Salut Xav
Je crois que j'ai trouvé

Décompresse ca dans Abeille/core/class
[AbeilleCmdProcess.class.php.zip](https://github.com/user-attachments/files/16689618/AbeilleCmdProcess.class.php.zip)

redemarre le démon Abeille
et reteste

**Comment by Xav-74** [comment]
Hello,

Alors ca fonctionne de nouveau pour les remote mais il reste un souci sur les cmd up and down des volets (que j'appelle dans mes remotes).

`ERREUR: Cmd 'setLevel': Paramètre 'level' manquant.`

A priori tu passes par un setlevel maintenant.
Par contre si je passe par la cmd setlevel directement, ca fonctionne ;)

[AbeilleLogs-240821.tar.gz](https://github.com/user-attachments/files/16690216/AbeilleLogs-240821.tar.gz)

Merci d'avance

**Comment by tcharp38** [comment]
Oui ca j'ai corrigé aussi hier.

Décompresse ca dans Abeille/core/class
[class.zip](https://github.com/user-attachments/files/16690313/class.zip)

et ca dans Abeille/plugin_info
[install.zip](https://github.com/user-attachments/files/16690322/install.zip)

redemarre démon Abeille
et retente

**Comment by Xav-74** [comment]
Je n'ai plus le message mais :
- la commande down ferme le volet
- la commande up aussi :)

**Comment by tcharp38** [comment]
Hein ?!
Les 2 cmds donnent le meme resultat ?
Tu me files les logs ?

**Comment by Xav-74** [comment]
Oups désolé !

Test à 15h04, dans l'ordre : 
- Down
- Setlevel 21%
- Up (le volet se ferme)

[AbeilleLogs-240821.tar.gz](https://github.com/user-attachments/files/16691888/AbeilleLogs-240821.tar.gz)

**Comment by tcharp38** [comment]
Nouvelle update pour Abeille/class
[class.zip](https://github.com/user-attachments/files/16694161/class.zip)

puis redemarrer Abeille

**Comment by tcharp38** [comment]
A decompresser dans Abeille/plugin_info
[install.zip](https://github.com/user-attachments/files/16694390/install.zip)

et redemarrer Abeille

**Comment by Xav-74** [comment]
Retour à la normal pour moi aussi ;)
Merci pour ta réactivité. Je clos

Xav
