### ISSUE TITLE
Problème BSO Profalux

### ISSUE THREAD

**Issue by lrigolo** [KiwiHC16/Abeille#2725]
Bonjour, depuis la dernière mise à jour d'hier dans Abeille (jeedom), les commandes du BSO ne fonctionnent plus. Dans le forcage de l'équipement le BSO Profalux n'apparait plus.

J'ai ce message dans Jeedom :<html>

2024-08-21 08:21:26 | Abeille | ERREUR: Cmd 'setLevel': Paramètre 'level' manquant. 

</div><div class="dt-bottom" style="box-sizing: border-box; scrollbar-width: thin; padding: 8px 10px;"><div class="dt-info" style="box-sizing: border-box; scrollbar-width: thin; margin: 7px 0px; float: right;"></div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>
Merci de ton aide
[AbeilleLogs-240821 (1).tar.gz](https://github.com/user-attachments/files/16687060/AbeilleLogs-240821.1.tar.gz)

**Comment by Xav-74** [comment]
Hello Irigolo

Idem pour moi ! Ce sont les commandes up and down qui ne fonctionne plus. Mais si tu passes par un setlevel, ca doit fonctionner non ?

[https://github.com/KiwiHC16/Abeille/issues/2724](https://github.com/KiwiHC16/Abeille/issues/2724)

**Comment by lrigolo** [comment]
J'ai ça dans les commandes:
![image](https://github.com/user-attachments/assets/18469c7e-3ac4-4b0f-b2ee-ef8a9ca6095c)

**Comment by Xav-74** [comment]
Ah oui il manque des commandes !
Quelle version tes BSO ? (onglet équipement, puis type)

Tu peux essayer de faire une mise à jour (onglet avancé)

**Comment by tcharp38** [comment]
Salut @lrigolo 
Ton package de logs n'est pas téléchargé donc pas de piste.

Peux tu déja décompresser ca dans Abeille/core/class
[class.zip](https://github.com/user-attachments/files/16690673/class.zip)

et ça dans Abeille/plugin_info
[install.zip](https://github.com/user-attachments/files/16690665/install.zip)

puis redemarrer le démon Abeille

Apres quoi tu peux refaire un test de la commande BSO en question
et me filer les logs

**Comment by lrigolo** [comment]
Dans mon premier message je t'avais mis les logs
[AbeilleLogs-240821 (1).tar.gz](https://github.com/user-attachments/files/16691491/AbeilleLogs-240821.1.tar.gz)

ok, j'essaye ça, le type c'est Profalux BSO.

**Comment by lrigolo** [comment]
Voila les logs après l'install, visiblement descente down ça marche mais pas la montée ?
[AbeilleLogs-240821 (2).tar.gz](https://github.com/user-attachments/files/16691614/AbeilleLogs-240821.2.tar.gz)

**Comment by tcharp38** [comment]
Nouvelle update pour Abeille/class
[class.zip](https://github.com/user-attachments/files/16694161/class.zip)

puis redemarrer Abeille

**Comment by lrigolo** [comment]
J'ai cette erreur : ERREUR: Cmd 'setLevel': Paramètre 'ep' manquant.
[Uploading AbeilleLogs-240821.tar.gz…]()

**Comment by tcharp38** [comment]
Tes logs ne sont pas telechargés.. tu es allé surement trop vite

**Comment by lrigolo** [comment]
[AbeilleLogs-240821 (1).tar.gz](https://github.com/user-attachments/files/16694305/AbeilleLogs-240821.1.tar.gz)

**Comment by tcharp38** [comment]
A decompresser dans Abeille/plugin_info
[install.zip](https://github.com/user-attachments/files/16694390/install.zip)

et redemarrer Abeille

**Comment by lrigolo** [comment]
ça fonctionne, merci, tu es au top !

**Comment by tcharp38** [comment]
Ok je pousse une nouvelle beta pour demain du coup

**Comment by lrigolo** [comment]
Merci ++

**Comment by lrigolo** [comment]
Une petite question, je suis en firmware 3.22, faut-il mette la dernière version 3.A0 ?

Merci de ton retour

**Comment by lrigolo** [comment]
Mise à jour abeille ok, merci

**Comment by tcharp38** [comment]
La mise à jour corrige tous tes soucis ?

Concernant le 3.22, donc Zigate v2/+.. d'apres les differents retours je deconseille la 3.A0 qui semble apporter +de soucis que de corrections.

**Comment by lrigolo** [comment]
les commandes up & down fonctionnent, j'ai ce message d'erreur ce matin : 
2024-08-23 00:00:58 | Abeille                ERREUR: msgToCmd() ERROR 22 in AbeilleLQI

**Comment by tcharp38** [comment]
Quand tu signales une erreur, peux tu aussi me donner le package de logs ?

**Comment by lrigolo** [comment]
Ok, tu as raison, excuses moi.
[AbeilleLogs-240823.tar.gz](https://github.com/user-attachments/files/16726206/AbeilleLogs-240823.tar.gz)

**Comment by tcharp38** [comment]
Pas de soucis.

Voila le correctif.
A decompresser dans Abeille/core/php

[AbeilleLQI.zip](https://github.com/user-attachments/files/16726530/AbeilleLQI.zip)

**Comment by lrigolo** [comment]
Merci, c'est fait, voilà les logs après installation et relance
[AbeilleLogs-240823 (1).tar.gz](https://github.com/user-attachments/files/16727308/AbeilleLogs-240823.1.tar.gz)

**Comment by tcharp38** [comment]
Tu verra si l'erreur reapparait
- soit à minuit lors du scan reseau automatique
- soit si tu le lances à la main => reseau => bouton forcer reinterrogation

**Comment by lrigolo** [comment]
Je n'ai pas eu d'erreur en relançant le réseau, merci
![image](https://github.com/user-attachments/assets/dd1e60c4-14dc-4bec-8b97-c1590835fcbe)

**Comment by tcharp38** [comment]
Ok du coup on considere le sujet clos ?

**Comment by lrigolo** [comment]
Oui, merci beaucoup, tu intègreras les modifs php dans la prochaine beta ?

**Comment by tcharp38** [comment]
Ca l'est deja dans la beta de samedi.

Je ferme le sujet.
A reouvrir si soucis

**Comment by tcharp38** [comment]
Content du support, du plugin et/ou simplement envie de sponsoriser la solution ?

Tcharp38 [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/Tcharp38)
