### ISSUE TITLE
Ajout support SONOFF SNZB-06P Presence Sensor

### ISSUE THREAD

**Issue by sebgeekinside** [KiwiHC16/Abeille#2726]
Presence Sensor de la marque SONOFF et de modèle SNZB-06P

[discovery-SONOFF_SNZB-06P_Presence_Sensor.tar.gz](https://github.com/user-attachments/files/16736056/discovery-SONOFF_SNZB-06P_Presence_Sensor.tar.gz)

**Comment by tcharp38** [comment]
Salut
Ce tar gz ne semble pas un discovery mais un package de logs.

D'autre part il me faut une image PNG sans arriere plan à mettre en icone

**Comment by sebgeekinside** [comment]
Ça devrait être mieux avec ce fichier : 
[discovery-SONOFF_SNZB-06P_Presence_Sensor.tar.gz](https://github.com/user-attachments/files/16741932/discovery-SONOFF_SNZB-06P_Presence_Sensor.tar.gz)

Et l'image pour la vignette : 
![SONOFF_SNZB-06P_Presence_Sensor](https://github.com/user-attachments/assets/835b5d3b-8a38-471d-8c1c-1b4d4418b4ab)

**Comment by tcharp38** [comment]
Non je ne pige pas ce que c'est.
Tu as tous les voyants au vert ?
Pourquoi ".tar.gz" ? Ca doit etre un fichier json.. donc a zipper je pense

**Comment by sebgeekinside** [comment]
Une erreur d'extension du fichier json (suite à copier/coller)...

Le fichier discovery.json zippé : [discovery-SONOFF_SNZB-06P_Presence_Sensor.zip](https://github.com/user-attachments/files/16742055/discovery-SONOFF_SNZB-06P_Presence_Sensor.zip)

**Comment by tcharp38** [comment]
Le fichier est vide. Aucune info.
Que dit la page de decouverte ? Tous les voyants ne sont du coup pas au vert.
Peux tu me faire un snapshot de cette page ?

**Comment by sebgeekinside** [comment]
Le fichier avec cette fois-ci tous les voyants au vert : 
[discovery-SNZB-06P_SONOFF.zip](https://github.com/user-attachments/files/16752175/discovery-SNZB-06P_SONOFF.zip)

**Comment by tcharp38** [comment]
Oui bien mieux

Voila un modele preliminaire
a decompresser dans Abeille/core/config/devices
[SNZB-06P_SONOFF.zip](https://github.com/user-attachments/files/16753072/SNZB-06P_SONOFF.zip)

puis redemarrer Abeille
refaire inclusion

**Comment by sebgeekinside** [comment]
Après test rapide, la commande info Occupancy semble fonctionner.

**Comment by tcharp38** [comment]
Du coup il manque qqch pour ce device ?

**Comment by sebgeekinside** [comment]
Je ne vois pas de manque.
Je passe à Closed.
Merci pour la réactivité !
