### ISSUE TITLE
Tuya détecteur presence + luminosité (id = TS0601, _TZE200_3towulqd)

### ISSUE THREAD

**Issue by M4dd4M** [KiwiHC16/Abeille#2727]
Bonjour,

J'ai ajouté un détecteur infra rouge qui ne semble pas encore reconnu.
Voici la découverte complète :
[discovery-TS0601__TZE200_3towulqd.json](https://github.com/user-attachments/files/17225692/discovery-TS0601__TZE200_3towulqd.json)
![discovery-TS0601__TZE200_3towulqd](https://github.com/user-attachments/assets/a0523f56-8304-456c-9667-53fe735686ec)

c'est ce truc là : [https://fr.aliexpress.com/item/1005006492967626.html](url)

Est-ce intégrable ?

Merci d'avance 👍

**Comment by tcharp38** [comment]
A decompresser dans plugins/Abeille/core/config/devices
[TS0601__TZE200_3towulqd.zip](https://github.com/user-attachments/files/17245271/TS0601__TZE200_3towulqd.zip)

puis redemarrer Abeille
refaire inclusion
tester

L'image (pas super propre) sera dans la prochaine beta

Dis moi ce que ca donne

**Comment by M4dd4M** [comment]
Super, je test ça demain.
(je te referai l'image c'est vrai qu'elle est dégeu ^^ )

**Comment by M4dd4M** [comment]
Salut @tcharp38,
Bon et bien le modèle proposé fonctionne très bien depuis 5 jours.

Juste peut-être la luminosité en Lux, dont la valeur est assez haute, mais cohérente, à vue de nez je dirai x30 ou x40 par rapport à d'autre détecteur... si jamais y'a un facteur multiplicateur qui traine, autrement pas grave, c'est la variation qui compte.

Voici une image mieux découpée.
![discovery-TS0601__TZE200_3towulqd-333](https://github.com/user-attachments/assets/efacc3d0-aa95-400e-9291-0ec842075448)

**Comment by tcharp38** [comment]
Salut
J'ai mis à jour l'image. Merci

Pour la luminosité j'ai l'impression qu'il est preferable d'utiliser le cluster privé plutot que le standard Zigbee.
Du coup voila une mise à jour du modele

[TS0601__TZE200_3towulqd.zip](https://github.com/user-attachments/files/17305538/TS0601__TZE200_3towulqd.zip)

Par hasard il n'y a pas une reference qq part du style 'ZG-204ZL' ?

PS: Penses à basculer sur la derniere beta avant d ecraser le modele.

**Comment by M4dd4M** [comment]
Non, pas référence du style 'ZG-204ZL' 

Tout à l'air Ok pour moi en tout cas ! 👍
Merci !

**Comment by tcharp38** [comment]
Tu confirmes ?
C'est mieux avec ce modele ?

**Comment by M4dd4M** [comment]
J'aurai voulu dire oui ... mais cet après midi il est resté bloqué plusieurs heures en présence (alors qu'il y avait rien) et hier soir la luminosité est descendu à 0 lux très vite, alors que ce n'était pas complètement noir.
Donc, non, je préférai avant du coup ^^

**Comment by tcharp38** [comment]
Coté presence rien n'a changé.

Tu as plusieurs sujets ouverts alors on se focalise sur lequel ?
Si celui ci, peux tu mettre ce device en surveillance et me filer les logs au bout de qq heures ?

**Comment by M4dd4M** [comment]
Ok, donc ça doit venir de son placement et du lien avec mon réseau (je l'avais déplacé), je viens de le repositionner un peu plus proche, je vais surveiller ça.
Je veux bien que tu regardes plutôt l'autre sujet de détecteur de présence, car j'en ai 2 qu'aimerai bien ajouter à mon installation.

Hors sujet : Je pense que j'arrive au taquet de ce que peut supporter ma Pizigate, (31 abeiilles dans la ruche) y'a t-il un endroit qui détail les solutions pour étendre sa capacité ... je pensai ajouter une autre passerelles zigate en supplément, ou faire un remplacement par une autre Pizigate (version+) ?
Je ne trouve pas trop de détail dans la documentation

**Comment by tcharp38** [comment]
Donne moi le lien du sujet sur lequel on se focalise en premier STP. Je suis un peu perdu.

Concernant l'extension, je déconseille vivement la Zigate +/v2. Trop de mauvais retours des utilisateurs.
Tu pourrais par ex acheter une v1 d occase (et je suggere la PI car facile à mettre à jour si besoin), il y en a plein et te faire 2 reseaux.
Si tu veux que ton autre zigate soit déportée, ca ressemble à la Zigate Wifi (toujours v1 donc d occase).
Il y a aussi une solution ou tu fais toi meme.. une pizigate avec acces remote wifi.

**Comment by M4dd4M** [comment]
Tu peux clore ce sujet me concernant, ce détecteur n'est vraiment pas fiable, je l'ai sorti de ma config.

**Comment by tcharp38** [comment]
C'est possible car beaucoup de cochonneries mal finies dans les produits de base Tuya mais qu'est ce qui te fait arriver à cette conclusion ?

**Comment by M4dd4M** [comment]
La detection de présence qui fonctionne par intermittence, très bien les premiers jours, puis par fois, et de plus en plus, des détections injustifiées, voir des demi journée de détection (fausses) ... bref, j'ai arrêté d'essayer de comprendre.
Oui, surement un truc mal fini ... après parfois, y'a des trucs bien (CF l'autre détecteur en cours de validation dont je suis très content) ... faut tester avant de démultiplier ^^

**Comment by tcharp38** [comment]
Ok je ferme le sujet
Mais à réouvrir si tu veux t y repencher ou qqn d'autre.
