### ISSUE TITLE
Erreur-cron-contient-plus-de-50-messages => TS011F__TZ3000_ksw8qtmt trop bavard

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2729]
Bonjour,
Depuis plusieurs semaines j’ai un message d’erreur récurrent, 20 par jour :

[2024-11-05 13:23:43][ERROR] : cron(): La queue ‹ xToAbeille › (id ab026d) contient plus de 50 messages => redémarrage des démons.

Je suis en bêta, j’ai fait les mises à jour.
Je ne comprends pas ses messages.
Le seul problème que j’ai constaté, c’est la remontée d’informations sur certaines batteries, que je dois encore creuser.
Merci pour vos retours,
[Abeille.txt](https://github.com/user-attachments/files/17645167/Abeille.txt)

**Comment by tcharp38** [comment]
Peux tu t'assurer d etre en mode debug et me filer le package de logs
page maintenance + telecharger tout

**Comment by Jeedom122** [comment]
Je suis passé en mode debug, plus de 5000 logs.
Voici le package de logs
[AbeilleLogs-241106.tar.gz](https://github.com/user-attachments/files/17645687/AbeilleLogs-241106.tar.gz)
Merci et bonne journée

**Comment by tcharp38** [comment]
Tres etrange. Le package est incomplet. Je ne vois pas de AbeilleParser.log

Il manque plein d autres fichiers aussi comme KeyInfos

**Comment by Jeedom122** [comment]
Oui, effectivement cela m'a semblé bizarre pour l'avoir fait 2 fois avec le même résultat.
Je viens de refaire une extraction, qui me semble correcte cette fois-ci, désolé.
[AbeilleLogs-241106.tar.gz](https://github.com/user-attachments/files/17647752/AbeilleLogs-241106.tar.gz)

**Comment by tcharp38** [comment]
Mais la tu n'as plus d'erreurs n est ce pas ?

**Comment by Jeedom122** [comment]
Si toujours, avec le mode debug, abeille est plutôt bavard.

44841|[2024-11-06 14:29:29] ERROR  : cron(): La queue 'xToAbeille' (id ab026d) contient plus de 50 messages => redémarrage des démons.
45962|[2024-11-06 14:37:09] ERROR  : cron(): La queue 'xToAbeille' (id ab026d) contient plus de 50 messages => redémarrage des démons.

**Comment by tcharp38** [comment]
Ha vite.. file moi les logs.
Ca n etait pas dans tes logs precedents et du coup je ne vois pas la transition

Désolé pour ca.
En fait il faut que tu me les files des que ca bascule dans ce mode "d erreurs" sinon je ne vois pas la trace d'avant qui est tres vite ecrasée. Je cherche à comprendre ce qu'il se passe quand ces erreurs commencent.
Du coup peut etre que tu dois redemarrer Abeille, attendre que les erreurs arrivent, et la me faire un package.

**Comment by Jeedom122** [comment]
Et voilou, dans le premier fichier "Abeille" il y a plein d'erreurs
[AbeilleLogs-241106.tar.gz](https://github.com/user-attachments/files/17648145/AbeilleLogs-241106.tar.gz)

**Comment by tcharp38** [comment]
Ok je crois que j'ai une piste... DB22 est extremement bavard.
Du coup il monopolise les acces à la DB Jeedom pour enregistrer les infos.
Tu peux confirmer ça en le debranchant si possible.

Je reflechis à ce qui peut etre fait de mon coté

**Comment by Jeedom122** [comment]
Heu, c'est quoi DB22 ?

**Comment by tcharp38** [comment]
- ok : [Maison][NOUS A1Z Réseau], Id=162
       Addr=DB22, LastLQI=96, Model='TS011F__TZ3000_ksw8qtmt', Type='Nous smart socket'

**Comment by tcharp38** [comment]
Je crois qu'il va falloir qu'on bosse sur son reporting.
Il renvoi une info jusque"a plusieurs fois par seconde. Cest enorme et inutile

**Comment by Jeedom122** [comment]
Comme tu as pu le remarquer, c'est la prise où se trouve le réseau Ethernet.
Ce soir, je la débranche et je te tiens informé du résultat.

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Effectivement, tu as mis le doigt sur le problème, après la désactivation de DB22, plus de message d'erreur.
Voici les nouveaux logs
[AbeilleLogs-241107.tar.gz](https://github.com/user-attachments/files/17661404/AbeilleLogs-241107.tar.gz)
Sûrement une mise à jour à venir ;)
Merci pour ton aide.

**Comment by tcharp38** [comment]
On va bosser sur ce reporting beaucoup trop frequent
et on reste sur DB22 ([Maison][NOUS A1Z Réseau]) donc a rebrancher si pas déja le cas

    [2024-11-06 18:44:56] Abeille1, Type=8002/Data indication, Status=00, ProfId=0104, ClustId=0B04, SrcEP=01, DstEP=01, SrcAddrMode=02, SrcAddr=DB22, DstAddrMode=02, DstAddr=0000
    [2024-11-06 18:44:56]   FCF=18/General/Serv->Cli, SQN=9E, cmd=0A/Report attributes
    [2024-11-06 18:44:56]   AttrId=0508/RMS Current, AttrType=21, ValueHex=0096 => 150

Via l'onglet avancé de ton equipement peux tu interroger la config de reporting

![image](https://github.com/user-attachments/assets/a683020b-52b3-4bfb-b133-13a28efa720a)

et tu me files les logs
Merci

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Désolé pour ma réponse tardive, j'étais absent une semaine.
Voici mon premier retour:
Config
![config](https://github.com/user-attachments/assets/1a6012eb-7b28-4c2d-a9c4-e7ef48e22fa9)
Suite au lancement de l'interrogation, une erreur:
![erreur](https://github.com/user-attachments/assets/25071107-a508-42cc-94f3-fca52c7d3ab6)
Et ci-joint les logs. 
[AbeilleLogs-241119.tar.gz](https://github.com/user-attachments/files/17812099/AbeilleLogs-241119.tar.gz)
Bonne journée

**Comment by Jeedom122** [comment]
A l'instant, je viens d'avoir l'erreur : La queue 'xToAbeille' (id ab026d) contient plus de 50 messages => redémarrage des démons
Voici le log Abeille au moment de l'erreur.
[Abeille.zip](https://github.com/user-attachments/files/17812264/Abeille.zip)
Merci !

**Comment by tcharp38** [comment]
> Bonjour @tcharp38, Désolé pour ma réponse tardive, j'étais absent une semaine. Voici mon premier retour: Config ![config](https://private-user-images.githubusercontent.com/104787819/387564562-1a6012eb-7b28-4c2d-a9c4-e7ef48e22fa9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDg2MzYsIm5iZiI6MTczMjAwODMzNiwicGF0aCI6Ii8xMDQ3ODc4MTkvMzg3NTY0NTYyLTFhNjAxMmViLTdiMjgtNGMyZC1hOWM0LWU3ZWY0OGUyMmZhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwOTI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmQyZDUwMzRmMjJmNzhlYzg1MWNiZTM0MTU3NjcxOWZlOTQ2ZWU5NGI4OTE4MjkzOTBmNzNhN2ZmNmEyODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o4sGummU-NOSJLlCRbwjl-1aoz897Z8LMyMqZ2Tg1O0) Suite au lancement de l'interrogation, une erreur: ![erreur](https://private-user-images.githubusercontent.com/104787819/387564861-25071107-a508-42cc-94f3-fca52c7d3ab6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDg2MzYsIm5iZiI6MTczMjAwODMzNiwicGF0aCI6Ii8xMDQ3ODc4MTkvMzg3NTY0ODYxLTI1MDcxMTA3LWE1MDgtNDJjYy05NGYzLWZjYTUyYzdkM2FiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwOTI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWIwNjNiOWMzNWI3MzEwODY0YTNhMTI2ZGI3MTM1MTYyYzFmYTRjOGViOWM5MzNmOTkwYmMzYmY3Yzc0MGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8hTp04kO-Ue_pE_8gflhujBdCVwUmLKAY1lHtMkEYGk) Et ci-joint les logs. [AbeilleLogs-241119.tar.gz](https://github.com/user-attachments/files/17812099/AbeilleLogs-241119.tar.gz) Bonne journée

Salut

Pas de soucis pour le delai.
Mais manip pas tout à fait correcte.

Le cluster doit etre 0B04 et l'attribut 0508.. comme indiqué sur ma photo.
A priori tu as gardé le cluster 0000/basic par defaut et tu n'as pas mis l'attribut.

**Comment by Jeedom122** [comment]
Pour info, les champs renseignés ne sont pas sauvegardés.
Après saisie et interrogation, voici les logs
[AbeilleLogs-241119.tar.gz](https://github.com/user-attachments/files/17812949/AbeilleLogs-241119.tar.gz)

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Pour info, j'ai ce nouveau message ?

2024-11-19 15:08:01 | core | La  tâche plugin::cron n'arrive pas à finir à cause du plugin : Abeille  nous vous conseillons de désactiver le plugin et de contacter l'auteur

**Comment by tcharp38** [comment]
Salut
Je n'ai pas oublié. Je m'y repenche d ici qq mins.
Je pense que la surabondance de messages venant du device est la cause de ces soucis.

Dans ton cas il faut vraiment arriver à ce qu'il ne parle pas aussi souvent
et ca serait bien que j'arrive à ignorer une partie de ces messages pour ne pas planter le systeme avec une erreur pour l'utilisateur.

Bref 2 choses à faire.

**Comment by Jeedom122** [comment]
Oui, effectivement, le serveur a dû être saturé à un moment.
Quand j'observe le compteur sur la home page, plusieurs infos sont mises à jour simultanément à chaque seconde.
Ce qui est bizarre, la prise est installée depuis octobre 2022, le problème a surgi suite à la mise à jour d'Abeille au printemps 2024, si ça peut t'aider :)

**Comment by tcharp38** [comment]
Peux tu faire les 2 updates suivantes

A decompresser dans Abeille/core/config/devices/TS011F__TZ3000_ksw8qtmt
[TS011F__TZ3000_ksw8qtmt.zip](https://github.com/user-attachments/files/17831547/TS011F__TZ3000_ksw8qtmt.zip)

A decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/user-attachments/files/17831558/AbeilleParser.class.php.zip)

puis
- redemarrer Abeille
- faire une mise à jour de l equipement via l onglet avancé
- refaire une lecture de config reporting "clust 0B04 attr 0508"
- et me filer les logs  STP

**Comment by Jeedom122** [comment]
@tcharp38, pour être sûr, j'ai redémarrer Abeille d'ici.
![2024-11-20_154207](https://github.com/user-attachments/assets/9f4eb3f3-95ab-48e9-86bd-70491d78b2e0)

Voici les logs
[AbeilleLogs-241120.tar.gz](https://github.com/user-attachments/files/17832558/AbeilleLogs-241120.tar.gz)

Bonne lecture :)

**Comment by tcharp38** [comment]
Oui c'est bien ce qu'il fallait faire.
J'aurais dit redemarrer le démon c'était plus clair ?

Je regarde les logs

**Comment by tcharp38** [comment]
Bon ca m'a l'air de s être bien passé.
On le voit tres bavard juste avant la mise à jour et moins apres.

Je te laisse me faire un retour du coup.
Si c'est ok il faudra faire la mise à jour sur l'autre device de meme type.

**Comment by Jeedom122** [comment]
Bravo @tcharp38,
Plus de message d'erreur, de ralentissement.
La mise à jour du serveur se fait au changement de valeur  la sonde, c'est ça ?
Parfait, merci !!!!
Tu veux faire l'autre device, une mise à jour d'Abeille ne réglera pas le problème ?

**Comment by tcharp38** [comment]
> La mise à jour du serveur se fait au changement de valeur la sonde, c'est ça ?

Tu veux dire quoi par la ?

Je pousse une beta pour demain qui contient tout.
La mise à jour des equipement de ce type se fera automatiquement au redemarrage du démon donc oui tu n'es pas obligé de faire l'autre device. Comme ca tu pourra confirmer que ca roule.

**Comment by Jeedom122** [comment]
Ok @tcharp38, on fait comme ça, j’attends la mise à jour de la bêta et te tiens au jus, et te confirme si tout s'est bien passé.
Ah oui, une petite question, j'ai mes 3 sondes températures/humidités sonoff HS en 3 mois, la plus ancienne a peut-être 2 ans et les autres quelques mois. Tu as eu des retours d'utilisateurs ?
Merci encore et bonne soirée.

**Comment by tcharp38** [comment]
Non pas de retours particuliers. J'en ai une toujours en service depuis un moment.
Quand tu dis HS.. elles ne reviennent plus dans le circuit meme avec une pile neuve ? J'ai un doute la. Ca fait beaucoup trop de casse. Si besoin et pour ne pas pourrir ce sujet, ouvre en un dédié.

241120-BETA-1 en cours

**Comment by Jeedom122** [comment]
Effectivement, après changement de pile, elles ne sont plus détectées, une nouvelle inclusion ne fonctionne pas non plus.
OK, je vais ouvrir un nouveau sujet pour les sondes sonoff, effectivement les 3 en peu de temps, bizarre...

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
Mise à jour effectuée hier, vérification à l'instant.
Le deuxième device est bien installé, les logs sont normaux.
Parfait, je te remercie pour ton aide.
Bon weekend :)

**Comment by tcharp38** [comment]
Salut @Jeedom122 
On laisse tourner le WE et tu me dis si on peut fermer le sujet ?

**Comment by Jeedom122** [comment]
Hello @tcharp38,
Mauvaise nouvelle, l'erreur "xToAbeille' (id ab026d) contient plus de 50 " est revenue depuis le 22 nov.
Voici les logs
[AbeilleLogs-241126.tar.gz](https://github.com/user-attachments/files/17915486/AbeilleLogs-241126.tar.gz)
A++

**Comment by tcharp38** [comment]
Zut :(

Tu n'es plus en mode debug en +. Donc logs incomplets :(
Ou alors tu n'as pas redémarré Abeille apres changement.

Mais de ton coté as tu regardé un peu le device ?
Est il toujours aussi bavard ?

Je verifie quand tu me files des logs complets

**Comment by Jeedom122** [comment]
Bonjour @tcharp38,
J'ai pris un peu de temps pour te répondre, pour faire plusieurs tests.
J'ai re-re-relancé Abeille, utilisé la seconde prise connectée, cela semble correct.
Je pense qu'il faut encore attendre avant de clôturer le sujet, l'autre fois aussi c'était bon.
Voici les logs
[AbeilleLogs-241127.tar.gz](https://github.com/user-attachments/files/17945897/AbeilleLogs-241127.tar.gz)

Par contre, et c'est pour cela que j'ai mis du temps à te répondre, depuis la mise à jour d'Abeille, le plugin n'envoie plus d'email, j'ai une erreur SMTP, bien sûr j'ai testé le plugin messagerie, pas de soucis. Avec les autres plugins, comme Jeedouino, il n'y a pas de problèmes.
J'avais déjà constaté qu'avec Abeille on ne pouvait pas utiliser d'accent dans les messages, cela plantait la messagerie, sûrement un problème de code UTF8 ou autres ? Voici l'exemple que j'avais dû réaliser pour que tout fonctionne correctement.

![2024-11-27_090734](https://github.com/user-attachments/assets/b76d5042-f0f3-49a0-9832-057d6ada90bb)

Par contre maintenant je ne sais pas ?
Merci pour ton aide.
Bonne journée.

**Comment by tcharp38** [comment]
Salut

Ok on attend de voir pour le reporting des messages.

Concernant l'envoi SMS .. quel est le rapport avec Abeille ?
Si je suis bien tu utilises une info "Status", a priori booleenne, pour declencher l'envoi d'un mail.
Cette info ne remonte plus ?

**Comment by Jeedom122** [comment]
L'info remonte, déclenche l'envoi de l’e-mail, mais crée une erreur smtp ? Vraiment bizarre
Comme l'exemple (image) dans mon précédent message, cela s'était déjà produit, pour régler le problème, j'avais modifié le texte pour enlever les accents.
Par contre aucun souci avec les SMS.

**Comment by tcharp38** [comment]
Tu dois etre d'accord  avec moi pour dire qu'Abeille ne peut avoir d'influence sur cette partie.

Mais j'ai deja eu le souci et j'en ai juste conclu... surtout pas d'accents.
Apres je crois comprendre que suivant comme tu l'utilises ca fonctionne ou pas. Ce qui me fait dire qu'il ya un souci sur un des chemins vers SMS, soit venant du plugin soit de Jeedom meme.

**Comment by Jeedom122** [comment]
Hier, j'ai réalisé la dernière mise à jour d'Abeille, et relancé le serveur.
Toujours le même problème, on parle bien des e-mails qui crées une erreur au niveau du serveur smtp.
Résumé, le bug est apparu pile poil après la mise à jour du 20/11.
Sur le même principe d'utilisation, les autres plugins envoient bien les e-mails. Conclusion, un problème avec Abeille.
Aujourd’hui 7h42 j'aurais dû avoir un e-mail, j'ai regardé les logs, je n'ai rien vu de particulier, mais je ne suis pas un spécialiste :)
Voici les logs:
[AbeilleLogs-241129.tar.gz](https://github.com/user-attachments/files/17956322/AbeilleLogs-241129.tar.gz)
Merci et bonne journée @tcharp38

**Comment by tcharp38** [comment]
On ne verra rien dans les logs Abeille car aucune info pure Jeedom ou un autre plugin.
Et si l' info que tu utilises remonte.. j vois pas le souci de ce coté.

Du coup il faudra que j'essaie de reproduire ton cas.

Peux tu ouvrir un sujet dédié pour qu'on arrete de pourrir celui ci ?

**Comment by Jeedom122** [comment]
Plus d'erreurs "Erreur-cron-contient-plus-de-50-messages".
Je clôture le sujet.
Merci @tcharp38 pour ton intervention :)
