### ISSUE TITLE
liste à jour de têtes thermostatiques

### ISSUE THREAD

**Issue by Soshapf** [KiwiHC16/Abeille#2730]
Bonjour,
 je cherche à acheter des têtes thermostatiques compatible zigate et abeille. Dans la liste des périphériques, je ne trouve que deux modèles assez anciens que je retrouve plus en vente. J'imagine qu'il y d'autres modèles notamment des sonoff ou moes ou tuya que je pourrais acheter sur aliexpress. Pouvez-vous me donner une liste de modèles compatibles ? 
En vous remerciant. 
Cordialement

**Comment by tcharp38** [comment]
Bonsoir @Soshapf
Il est quasi impossible de lister des équipements pas encore supportés.
Par contre si ils le sont sur une autre solution alors ce support doit pouvoir être ajouté.

Je suggère néanmoins un produit suivi avec des mises à jour si besoin, ce qui n'existe quasiment jamais chez Tuya pour lequel les marques utilisatrices font le stricte minimum et travail bâclé. Donc peut être sonoff. Moes.. ça reste à voir. Quant à Tuya générique.. dernier choix car aucun support et souvent firmware bâclé.

**Comment by Soshapf** [comment]
Bonjour,
Je vous remercie pour la réponse.
Je comprends qu'en dehors des appareils mentionnés dans la liste, il n'y a pas d'autres têtes thermostatiques supportées.
C'est dommage car j'ai vu des tutos d'utilisation de têtes sonoff avec le plugin JeeZigbee et je pensais que vous auriez inclus d'autres modèles également sans forcément mettre à jour la liste comme j'ai pu le constater pour d'autres appareils.
Tant pis.
Cordialement

**Comment by tcharp38** [comment]
Ça ne veut pas dire que ca n'est pas possible. J'ai juste besoin de qqn qui a cet équipement pour bosser avec lui sur l'intégration.

**Comment by tcharp38** [comment]
Je ferme le sujet mais comme je disais si vous avez un equipement non reconnu, on peut bosser desus ensemble pour l'integrer dans Abeille.
Dés lors qu'il l'est dans d'autres solutions (Domoticz, Jeedom autre plugin.. etc) ca doit etre possible.
