### ISSUE TITLE
Erreur cmd group sur telecommande virtuelle (id = remotecontrol)

### ISSUE THREAD

**Issue by Xav-74** [KiwiHC16/Abeille#2732]
Hello @tcharp38 

Suite à la dernière MAJ en beta faites ce soir, mes commandes de groupe (via tlc virutelle) ne fonctionnent plus :

`ERREUR: Invalid payload. Not hexa ! (01#addrGroup#010100)`

Abeille : 241115-BETA-1
Jeedom : 4.4.19 STABLE
Debian 11

Les logs complets 
[AbeilleLogs-241117.tar.gz](https://github.com/user-attachments/files/17792114/AbeilleLogs-241117.tar.gz)

Merci d'avance,

Xav

**Comment by tcharp38** [comment]
Hoo.. j'ai zappé ça.
Désolé. Je m'y colle de suite.

**Comment by tcharp38** [comment]
@Xav-74 
Juste une question .. comment tu choisissais le "groupe" avant cette erreur ?

**Comment by tcharp38** [comment]
Decompresse ce modele dans Abeille/core/config/devices/remotecontrol
[remotecontrol.zip](https://github.com/user-attachments/files/17792209/remotecontrol.zip)

puis via l'onglet avancé de ta remote, fais "mise à jour"

Tu dois voir apparaitre une "variable" dans l'onglet "Equipement".. avec "addrGroup". 
C'est la que tu dois pouvoir changer le groupe si besoin.

J'attends ton retour avant de pousser une beta

**Comment by Xav-74** [comment]
Pas de souci ! C'est le but d'une beta :)

> Juste une question .. comment tu choisissais le "groupe" avant cette erreur ?
Dans l'onglet Avancé, tu un champ adress group ;)

Le fichier json me retoune une erreur
`Le modèle JSON 'remotecontrol' est corrompu.`

Aucun champ après Variables du coup ;)

**Comment by tcharp38** [comment]
Zut.
Mon fichier ne l'est pas.
[remotecontrol.zip](https://github.com/user-attachments/files/17792407/remotecontrol.zip)
Je te le redonnes du coup.

Pour info j'ai ajouté cette section

        "variables": {
            "addrGroup": "1212"
        },

**Comment by Xav-74** [comment]
C'est moi qui suis bete ! Cela arrive tout le temps qd je copie le fichier directement du zip sur mon jeedom. Je dois le décompressé avant :)

C'est tout bon, ca refonctionne ;)

Merci pour ta réactivité !

**Comment by tcharp38** [comment]
Cool.
Je pousse la beta 241117-BETA-1 pour d'autres du coup.
La mise à jour a partir du modele devrait etre automatique.
