### ISSUE TITLE
Ouahh... missing code to handle private cluster

### ISSUE THREAD

**Issue by Kenderv** [KiwiHC16/Abeille#2733]
Bonjour @tcharp38 
Depuis quelques jours j'ai ce message qui apparaît chaque heure dans le log abeilleparserlog
`0000|[2024-11-25 12:44:36] ERROR:   Ouahh... missing code to handle private cluster
0001|[2024-11-25 13:44:40] ERROR:   Ouahh... missing code to handle private cluster
0002|[2024-11-25 14:44:42] ERROR:   Ouahh... missing code to handle private cluster
0003|[2024-11-25 15:44:46] ERROR:   Ouahh... missing code to handle private cluster
0004|[2024-11-25 16:44:46] ERROR:   Ouahh... missing code to handle private cluster
0005|[2024-11-25 17:44:51] ERROR:   Ouahh... missing code to handle private cluster
0006|[2024-11-25 18:44:52] ERROR:   Ouahh... missing code to handle private cluster
0007|[2024-11-25 19:44:56] ERROR:   Ouahh... missing code to handle private cluster
0008|[2024-11-25 20:44:57] ERROR:   Ouahh... missing code to handle private cluster
0009|[2024-11-25 21:45:02] ERROR:   Ouahh... missing code to handle private cluster
0010|[2024-11-25 22:45:02] ERROR:   Ouahh... missing code to handle private cluster
0011|[2024-11-25 23:45:07] ERROR:   Ouahh... missing code to handle private cluster
0012|[2024-11-26 00:45:07] ERROR:   Ouahh... missing code to handle private cluster
0013|[2024-11-26 01:45:12] ERROR:   Ouahh... missing code to handle private cluster
0014|[2024-11-26 02:45:12] ERROR:   Ouahh... missing code to handle private cluster
0015|[2024-11-26 03:45:17] ERROR:   Ouahh... missing code to handle private cluster
0016|[2024-11-26 04:45:17] ERROR:   Ouahh... missing code to handle private cluster
0017|[2024-11-26 05:45:21] ERROR:   Ouahh... missing code to handle private cluster
0018|[2024-11-26 06:45:21] ERROR:   Ouahh... missing code to handle private cluster
0019|[2024-11-26 07:45:26] ERROR:   Ouahh... missing code to handle private cluster
0020|[2024-11-26 08:45:26] ERROR:   Ouahh... missing code to handle private cluster`
Je n'ai pas la moindre idée de ce qu'il faut faire pour corriger. Merci de ton aide

**Comment by tcharp38** [comment]
Hello @Kenderv 
Désolé pour cette regression. On en discutait déja dans le #1243

En dehors du message vois tu des soucis ?

Voila un fichier à decompresser dans Abeille/core/class
[AbeilleParser.class.php.zip](https://github.com/user-attachments/files/17918785/AbeilleParser.class.php.zip)

puis tu redemarres le démon Abeille

**Comment by tcharp38** [comment]
J'ai poussé une beta pour demain avec ce correctif.

**Comment by Kenderv** [comment]
J'ai fait la modif vers 16:30. J'avais des messages toutes les heures à xx:45:xx et à 16:45:xx je n'ai plus eu de messages . Donc ta modif est efficace. Merci.
Tu peux clore le sujet
