### ISSUE TITLE
Abeille bug envoie e-mail

### ISSUE THREAD

**Issue by Jeedom122** [KiwiHC16/Abeille#2734]
Bonjour,
Le changement d'état du plugin Abeille déclenche bien l'envoi de l’e-mail, mais crée une erreur smtp ?
Le bug est apparu pile poil après la mise à jour d'Abeille du 20/11.
Par contre aucun soucis pour les SMS.
Bien sûr j'ai testé le plugin messagerie, pas de soucis.
D'ailleurs avec les autres plugins, comme Jeedouino par exemple, il n'y a pas de problèmes.
J'avais déjà constaté qu'avec Abeille on ne pouvait pas utiliser d'accent dans les messages, cela créé une erreur SMTP, sûrement un problème de codage UTF8 ou autres ? 
Voici l'exemple que j'avais dû réaliser pour que le message fonctionne correctement.

![390724115-b76d5042-f0f3-49a0-9832-057d6ada90bb](https://github.com/user-attachments/assets/5c76a8f1-f43a-415a-be56-5c3878cb336c)

Je viens de reparamétrer la commande, à suivre...
Merci pour vos retours.

**Comment by Jeedom122** [comment]
Bonjour,
Pour compléter mets recherches, j'avais une sauvegarde du 18 nov que j'ai réinstallée, donc avant la mise à jour du 21.
Le problème reste le même.

![18-11](https://github.com/user-attachments/assets/3ec08b40-a2e7-44df-9943-4b7e495ab80e)

J'ai vérifié l'historique des mails, le dernier envoyé date du 25 nov, donc après la mise à jour d'Abeille

![2024-12-03_164647](https://github.com/user-attachments/assets/4454edfc-e039-4d48-a27c-3503b3dba0bc)

Voici le message d'erreur renvoyé lors du lancement de la requête par Abeille

 ![2024-12-03_164500](https://github.com/user-attachments/assets/94ea4c35-aec4-46d3-8b1f-421efe1cc366)

L'erreur concerne tous les objets gérés par Abeille ? J'ai vérifié les dernières mises à jour, à part Abeille, la plus récente date du 5 nov.
Si quelqu’un à une idée ?

**Comment by Jeedom122** [comment]
Problème résolu, enfin, une solution bricolage, il y a bien un bug avec le codage pour les accents et même dans ce nouveau bug, les espaces et les majuscules ? Et un changement de champ ? Vraiment très bizarre.
Ancien texte depuis des mois, il fallait adapter le champ message

![2024-12-05_115006](https://github.com/user-attachments/assets/28442e46-3e16-44ea-b17a-3b0d5da5e093)

Maintenant, c'est le titre, et non plus le message qu'il faut modifier pour ne plus avoir d'erreur SMTP.

![2024-12-05_114929](https://github.com/user-attachments/assets/672ec78b-cc4a-4b77-8b0c-604a06da4f42)

Si cela peut être utile à quelqu'un

**Comment by tcharp38** [comment]
Ha bravo !!
Donc c'est confirmé qu'Abeille n'est pas en cause. Juste une coincidence.
J'avoue que je ne savais pas trop comment avancer.

On peut fermer le sujet du coup ?

**Comment by Jeedom122** [comment]
Si, le problème vient d'Abeille, la programmation des messages se fait dans Abeille. (copie écran)
Pas de problème avec un autre plugin, comme Jeedouino, message avec accents, espaces dans les deux champs (titre et message), pas de soucis.

![2024-12-05_171535](https://github.com/user-attachments/assets/4868aeaa-541c-49a5-84d5-e1596439ad82)

**Comment by tcharp38** [comment]
Non cet ecran n'est en aucun cas celui d'Abeille. C'est une partie de Jeedom que tu retrouves dans n'importe quel plugin.
Donc je ne vois toujours pas comment il peut influencer la maniere d'envoyer des SMS.

Mais bon si les memes messages et titres passent par ailleurs, il doit bien y en avoir une.

Quel est le plugin qu'il faut installer pour reproduire ce souci ?

**Comment by Jeedom122** [comment]
J'utilise le plugin "Mail" du Market (pas de soucis avec les SMS)

![2024-12-06_085615](https://github.com/user-attachments/assets/799b6fa4-0d87-4331-b1fb-74c713359460)

https://doc.jeedom.com/fr_FR/plugins/communication/mail/

**Comment by tcharp38** [comment]
Bon ben moi je ne reproduis aucun de tes soucis.
Le mail fonctionne bien, avec des accents, des minuscules ou majuscules, dans le titre ou le message.
Et dans le meme mode de fonctionnement que toi.

![image](https://github.com/user-attachments/assets/d7168e58-148c-4786-86db-a7dad199435d)

Bref aucune piste pour une quelconque implication d'Abeille jusque la.

**Comment by Jeedom122** [comment]
J'ai réitéré les tests en utilisant un autre navigateur, mais je suis toujours confronté au même problème. :(
Si cela fonctionne en modifiant le texte, c'est un moindre mal.
Merci pour le temps passé. Cela a permis d'éliminer la possibilité d'un bug Abeille.
Je clôture le post.

**Comment by tcharp38** [comment]
Je n'elimine pas completement la faute à Abeille dans la mesure ou ce plugin comme les autres utilise les couches Jeedom mais peut etre que qqchose n'est pas à jour qq part.
Quoi qu'il en soit tant que je ne sais pas reproduire, je suis aveugle.

Comment arrives tu exactement à cette fenetre de configuration commande dans laquelle tu entres les action SMS & email ?

**Comment by Jeedom122** [comment]
Dans Abeille, je sélectionne l'équipement (capteur sonoff), onglet Commandes et ensuite Configuration commande (flèche)

![2024-12-09_161004](https://github.com/user-attachments/assets/89cd8b7f-a120-4b98-9303-4efac6850d1c)

Onglet configuration, exactement comme toi :)

![2024-12-09_161327](https://github.com/user-attachments/assets/e5a597b8-2ca4-4d7b-893e-8d05057fe8b5)

Bien sûr, j'ai créé au préalable dans le plugin "Mail" un groupe de mails, où l'on peut tester son fonctionnement directement.
J'utilise le même groupe pour tous mes plugins. (le groupe comprend plusieurs adresses, Perso et Pro)
