### ISSUE TITLE
ERREUR 'getHealthDatas' si équipement orphelin sans passerelle active

### ISSUE THREAD

**Issue by scrableur** [KiwiHC16/Abeille#2735]
Bonjour,  depuis un certain temps le comportement de mon plugin abeille est très aléatoire (ou je fais qqch de pas bien). La page santé s'afficher vide, dans réseau j'avais la moitié de mes équipements. Depuis hier soir j'obtiens dans la page santé j'obtiens le message d'erreur : **ERREUR 'getHealthDatas'**
![image](https://github.com/user-attachments/assets/c3ab2e8b-a239-4918-b8ab-c80e3d875248)

dans réseau il me trouve deux équipements dont un qui est toujours en timeout avec un message d'erreur "Aucune donnée. Veuillez forcer la réinterrogation du réseau.".

OS (Debian 11), Jeedom et abeille a jour.

Voici les logs
[AbeilleLogs-241203.tar.gz](https://github.com/user-attachments/files/17993195/AbeilleLogs-241203.tar.gz)

avant hier je voyais aussi des modules en "No-ACK", je n'arrive pas a inclure des modules qui ont disparus ...

Si quelqu'un peut m'aider ca serait super sympa.

**Comment by tcharp38** [comment]
Salut @scrableur 
Si tu es sur la stable je te suggere de basculer sur la derniere beta et me faire un retour si tu vois un souci.

Le "getHealthDatas' me semble fixé depuis un moment comme des tas d'autres pbs potentiels

voir: https://kiwihc16.github.io/AbeilleDoc/Installation.html#installation-de-la-version-beta

**Comment by scrableur** [comment]
je viens de faire la mise a jour et relancer les dépendances --> toujours le même comportement :/

j'ai de temps en temps cette erreur 
![image](https://github.com/user-attachments/assets/59f62786-119b-4051-80c2-651f7cf5a2b4)

**Comment by tcharp38** [comment]
Tu me donnes un package de logs stp ?

**Comment by scrableur** [comment]
oui bien sur 
[AbeilleLogs-241204.tar.gz](https://github.com/user-attachments/files/18000610/AbeilleLogs-241204.tar.gz)

si c'est bien ca dont on parle

**Comment by tcharp38** [comment]
Donc tu dis que tu as toujours l'erreur 'getHealthDatas' ?

Comment procedes tu pour l'avoir ?
As tu rechargé la page depuis la mise à jour ?

**Comment by scrableur** [comment]
oui toujours l'erreur même avec un autre navigateur

**Comment by tcharp38** [comment]
Elle apparait quand tu fais quoi ?

**Comment by scrableur** [comment]
quand je clique sur santé

**Comment by tcharp38** [comment]
Etrange car si cette erreur je l'ai eu, je pouvais la reproduire et je l'ai fixé.
Personne ne l'a plus remonté depuis.

Peux tu me filer les fichiers suivants

    core/ajax/Abeille.ajax.php
    desktop/modal/AbeilleHealth.modal.php:

**Comment by tcharp38** [comment]
Laisse tomber. Je crois que j'ai une piste.

Peux tu decompresser ca dans Abeille/core/ajax
[Abeille.ajax.php.zip](https://github.com/user-attachments/files/18006601/Abeille.ajax.php.zip)

Et celui dans dans Abeille/desktop/modal
[AbeilleHealth.modal.php.zip](https://github.com/user-attachments/files/18006624/AbeilleHealth.modal.php.zip)

puis tu recharges ta page et tu testes la page santé.
Ca dit quoi ?

**Comment by scrableur** [comment]
Bonne nouvelle ! j'ai plus l'erreur mais c'est vide 

![image](https://github.com/user-attachments/assets/64d72ee1-6e2c-487f-ace9-5ec195ef6cd2)

**Comment by tcharp38** [comment]
Ha ha.. une façon de se debarrasser du pb :)

Tu me files le package de logs STP ?

**Comment by scrableur** [comment]
[AbeilleLogs-241204.tar.gz](https://github.com/user-attachments/files/18009429/AbeilleLogs-241204.tar.gz)

le voici

**Comment by tcharp38** [comment]
Je vois ca

    [Wed Dec 04 14:31:52.367600 2024] [php7:error] [pid 1805143:tid 1805143] [client 192.168.3.71:62251] script '/var/www/html/plugins/Abeille/core/ajax/Abeille.ajax.php' not found or unable to stat, referer: http://192.168.3.63/index.php?v=d&m=Abeille&p=Abeille


Un souci avec le fichier Abeille.ajax.php
Tu as procedé comment ? Tu as viré l ancien ? Ou juste ecrasé ?

**Comment by scrableur** [comment]
Renommé en .old et mis le nouveau

il date de 14h31 le fichier donc c'etait peut etre pil poil au moment de la copie

**Comment by tcharp38** [comment]
Depuis ca fonctionne du coup ?

**Comment by scrableur** [comment]
Oui je n'ai plus l'erreur mais la page santé est vide

**Comment by tcharp38** [comment]
Tu peux faire deja une chose
F12 => ouverture d'une fenetre de debug javascript
Puis ouvre la page santé
tu dois voir apparaitre sur la droite "refreshHealth()" comme suit

![image](https://github.com/user-attachments/assets/2414d6d9-ab11-4c3f-979c-20887cb35b94)

Tu me fais une copie de cette partie STP ?

**Comment by scrableur** [comment]
![image](https://github.com/user-attachments/assets/1ba8ceb9-322e-42d4-a4c8-8c7f7b534ae7)

**Comment by tcharp38** [comment]
Ha il y a donc qqch qui remonte.
Autre requete du coup.. peux tu déployer 'equipements', puis 'Abeile1' & 'Abeille2'
comme cet exemple

![image](https://github.com/user-attachments/assets/2fe95bfc-cd97-4a56-a62b-510617cdd524)

**Comment by scrableur** [comment]
![image](https://github.com/user-attachments/assets/1d8c798d-e271-4c05-af71-d3304b82a227)

comme ca ?

**Comment by tcharp38** [comment]
Oui merci. Ca me donne une nouvelle piste.
Je vois une autre erreur du coup.. toujours liée à ta situation particuliere.. un reseau "Abeille1" incomplet car aucune Zigate active pour le seul equipement.

Mais ne le supprime pas tout de suite STP.

**Comment by tcharp38** [comment]
A decompresser dans Abeille/desktop/modal
[AbeilleHealth.modal.php.zip](https://github.com/user-attachments/files/18021769/AbeilleHealth.modal.php.zip)

puis tu raffraichies ta page et tu testes

**Comment by scrableur** [comment]
\o/ ca remarche 
![image](https://github.com/user-attachments/assets/3fbe30cb-0f61-429f-a910-2cba25fb280b)

Merci beaucoup et bravo pour ta réactivité !

est ce normal que les objets apparaissent en no-ack ? (j'ouvre un autre ticket ? )

pour ma culture perso il s'est passé quoi ? 
J'avais une zigate V1 je l'ai désactivé après avoir migré mes équipements vers la 2

**Comment by tcharp38** [comment]
Alors concernant ton souci je t'ai dit que tu etais le seul à l'avoir car cas un peu foireux.
Regarde en bas tu as un equipement "Chambre interrupteur" qui est sur le reseau "Abeille1" mais aucune zigate n'est associée à ce reseau. Bref c 'est un equipement orphelin, un cas sur lequel je ne suis jamais tombé.

Pour les NO ACK, laisse un peu de temps avant de refaire le point. Eventuellement ouvre un sujet dedié si ca persiste.

Je vais du coup pousser une nouvelle beta avec ces correctifs.

On peut fermer ce sujet du coup ?

**Comment by scrableur** [comment]
Oui tu peux fermer le sujet
merci encore
