### ISSUE TITLE
[2018-01-26 10:30:32][ERROR] : [MySQL] Error code : 23000 (1062). Duplicate entry 'Ruche-1' for key 'unique'

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#29]
Error message when stating the plugin.
And each time restart daemon.

**Comment by edgd1er** [comment]
j'ai corrigé le pb avec qq remanient dans le commit e635f99e11d6d1ee94cb4c1d7a4f3b52c7032a5d

la version courte: le pb venait de la 
$elogic = self::byLogicalId("Ruche", 'Abeille'); au lieu de $elogic = self::byLogicalId("Abeille/Ruche", 'Abeille');

**Comment by KiwiHC16** [comment]
Super, merci. Je vais regarder demain et faire un commit.

**Comment by edgd1er** [comment]
should be fixed by commit c09da86957da3a0d9a96642cd79080550464376b
To check

**Comment by KiwiHC16** [comment]
Je ne vois plus ce message.
