### ISSUE TITLE
Network Modal, representation graphique: Refresh ne fonctionne pas

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#292]
Le fichier JSON est bien mis à jour mais pas l affichage.
Sous Safari, le refresh ne fonctionne pas même en fermant Safari, il faut faire un clean historique pour avoir le graphe à jour. 
Sous Firefox, c est un peu la même chose.

**Comment by KiwiHC16** [comment]
Salut edgd1er, as tu eu du temps pour regarder ce sujet ?

**Comment by KiwiHC16** [comment]
Sur ma nouvelle version de graph, je n'ai pas ce problème.

Du nouveau de ton côté ?

**Comment by KiwiHC16** [comment]
Mais je rencontre tres probableent un probleme de cache. Dans ton cas, comme dans le mien je vois qu'on utilise du javascript. Le probleme pour proviens probablement de l utilisation d'AJAX en mode get. Je viens de lire que si l on ne veut pas de cache il faut utiliser AJAX en mode post. 
Je vais tester avant de confirmer.

**Comment by KiwiHC16** [comment]
Ok je vais essayer. 
Quand je fait un "Recalcul du cache" dans la page avec la liste, la progression s'affiche bien et le fichier JSON et créé. Par contre quand je passe à la vue Graphique du réseau, alors le graph est l'ancien (comme si le nouveau JSON n'est pas pris en compte).
Comme si le cache du browser web (Safari) affichait les anciennes infos. Il faut que je clean tout l'historique,... de safari pour qu'il affiche le nouveau graph.

**Comment by KiwiHC16** [comment]
Ok j'ai le film capture d'ecran 20Mo. Comment je te le partage ?

Dans le film tu peux voir que le graph à 7 equipments, par contre dans le fichier JSON, il n'y en a que 5.
Comme si ajax utilisait le cache de ce fichier. Pour GET il faut changer l'URL avec un rand un truc comme get http://IP/xxxxxx/getFile?falseParam=rand ou passer par un POST. 

C est comme cela que je résolu mon soucis hier.

**Comment by KiwiHC16** [comment]
Tu le trouveras à https://github.com/KiwiHC16/Abeille/blob/master/Documentation/films/CaptureEdgder1er.mov

On l'effacera après.

**Comment by KiwiHC16** [comment]
Attention dans le fichier lock (pour partager l avancement, a la fin il n'affiche pas que 'done' mais done avec la date par exemple:  "done - Saturday 6th of October 2018 12:00:22 AM"

**Comment by KiwiHC16** [comment]
Test ce matin: 
- delete fichier son
- relance "recalcul du cache"

Ouverture de la avec Safari:
![capture d ecran 2018-10-11 a 10 54 40](https://user-images.githubusercontent.com/8549674/46792617-10e95f00-cd44-11e8-96c6-0fa5bc96e362.png)

Ouverture de la liste avec Firefox:
![capture d ecran 2018-10-11 a 10 55 11](https://user-images.githubusercontent.com/8549674/46792647-22cb0200-cd44-11e8-9dfc-8d003ce94ea7.png)


Safari graph pas mis à jour, firefox (que je n'utilise pas) à jour.

**Comment by KiwiHC16** [comment]
$.getJSON("plugins/Abeille/Network/AbeilleLQI_MapData.json", function (json) {
fait un Get qui est géré par le cache du browser 

pour bypasser le cache il faut changer l url, donc j ajoute la date.
 $.getJSON("plugins/Abeille/Network/AbeilleLQI_MapData.json?"+Date.now()

So we can close

**Comment by edgd1er** [comment]
le pb c'est qu'en de refresh sur la mm journée, le cache va de nouveau t'embeter non ?
je viens de regarder le get peut prendre une option "cache: false", je vais voir si je peux l'integrer demain matin :)

**Comment by KiwiHC16** [comment]
Date.now() Le nombre de millisecondes écoulées depuis le premier janvier 1970 à minuit UTC donc a chaque requete il y a u moins un ms qui a passée donc le cache ne devrait pas être utilisé.

**Comment by edgd1er** [comment]
ok, bon, bon même si ce n'est plus trop utile, j'avais fait le correctif pour faire une requête ajax sans cache, j'ai dupliqué la méthode pour la récup du json.lock
cela evitera le hack du date.now() ;)
