### ISSUE TITLE
Network Modal, representation graphique: Evolutions

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#293]
Evolution:
Page graphique du reseau:

- peut on fixer la position des equipements pour avoir une representation sur la base des x, y qu'on defini dans l'objet. (Un bouton pour choisir placement automatique ou position X,Y)
- Peut on definir la longueur des liens en fonction d'un parametre (Valeur LQI, ...) ?
- Peut on changer la couleur du lien en fonction de cette valeur ?
- Peut on avoir un filtre sur les equipements que l on veut ?
- Peut on avoir un filtre sur les liens que l on veut ? (LQI > 100 par exemple)
- Peut on faire apparaitre la valeur du lien ?

Page Table de routage:
- Peut on ajouter un lien sur les adresses courtes pour ouvrir l objet directement
- Jouer avec la couleur LQI (<50 rouge, <150 orange et vert)

**Comment by KiwiHC16** [comment]
Graph reseau:
Version edgd1er:

- Peut on fixer la position des equipements pour avoir une representation sur la base des x, y qu'on defini dans l'objet. (Un bouton pour choisir placement automatique ou position X,Y)
  -- il est possible de positionner le centre du graph. pas sur pour le reste.
- Peut on definir la longueur des liens en fonction d'un parametre (Valeur LQI, ...) ?
  -- normalement oui, mais je n'ai jamais réussi
- Peut on changer la couleur du lien en fonction de cette valeur ?
  -- normalement oui, mais je n'ai jamais réussi
- Peut on avoir un filtre sur les equipements que l on veut ?
- Peut on avoir un filtre sur les liens que l on veut ? (LQI > 100 par exemple)
- Peut on faire apparaitre la valeur du lien ?
  -- oui, le plugin zwave y arrive, moi pas :(
- Page Table de routage: 
- Peut on ajouter un lien sur les adresses courtes pour ouvrir l objet directement
  -- je pense que oui
- Jouer avec la couleur LQI (<50 rouge, <150 orange et vert)
 -- pareil, j'avais essayé sans succés, mais c'est possible

Version Kiwi:
A Faire:

- Peut on avoir un filtre sur les liens que l on veut ? (LQI > 100 par exemple): Oui

Ne sera pas fait
- Peut on definir la longueur des liens en fonction d'un parametre (Valeur LQI, ...) ?
=> Oui si on a l'algo qui va bien mais je ne suis pas sure de passer du temps sur cette idée.

Fait
- Peut on changer la couleur du lien en fonction de cette valeur ? Oui fait pour LQI.
- Peut on avoir un filtre sur les equipements que l on veut ? Oui Fait.
- Peut on faire apparaitre la valeur du lien ? Oui fait
- Peut on fixer la position des equipements pour avoir une representation sur la base des x, y qu'on defini dans l'objet. => drag and drop dans la version graphique => faire sauvegarde dans l objet => lire les infos de l objet => Oui Fait

**Comment by edgd1er** [comment]
reponse dans le post précédent :)

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Pas trop de temps pour faire de belle chose, focus sur les fonctions de bases.
