### ISSUE TITLE
Quelques Warning

### ISSUE THREAD

**Issue by xionfr40** [KiwiHC16/Abeille#294]
Bonjour,

Quelques Warning PHP dans les logs : (version stable du 18/06)

PHP Notice:  Uninitialized string offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 37
PHP Notice:  Uninitialized string offset: 3 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 37

PHP Notice:  Undefined variable: GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 38

Cdlt,

Nicolas.

**Comment by xionfr40** [comment]
Un p'tit autre lors de la reception d'un message MQTT tiers , dans le log AbeilleMQTTCmdTimer : 

PHP Notice:  Undefined offset: 1 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/function.php on line 15

Exemple de log précedent le warning:
AbeilleMQTTCmdTimer 2018-06-20 15:02:00[DEBUG]Msg Received: Topic: {sonoff1/tele/UPTIME} => {"Time":"2018-06-20T14:02:00","Uptime":"4T15:16:02"}

**Comment by KiwiHC16** [comment]
PHP Notice: Undefined variable: GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 38

Il manquait un 's'.

Corrigé.

**Comment by KiwiHC16** [comment]
"MQTT tiers": même en envoyant le message sonoff1 sur mosquitto, je ne parviens pas à générer le PHP Notice. 
J'ai changé un peux le code du filtre pour etre sure mais normalement je ne process pas ces messages.

**Comment by KiwiHC16** [comment]
"PHP Notice: Uninitialized string offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 37": modification faite.

Si tu mets a jour avec le master, as tu toujours ces messages d'erreur ?

**Comment by xionfr40** [comment]
PHP Notice:  Undefined variable: type in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmdTimer.php on line 151

En fait, t'a pas initialisé le $type ! ;)

     function procmsg($topic, $msg)
    {
        global $dest;
        global $mqtt;
        global $Timers;
        
        // Process only CmdTimer messages.
        if ($type != "CmdTimer") { return ; }

**Comment by KiwiHC16** [comment]
J ai changé l ordre des lignes, c est pour ca. Je viens de pousser la modif dans le master.

**Comment by xionfr40** [comment]
et celui la aussi :+1: 
AbeilleMQTTCmd 2018-06-21 16:09:38[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/getNetworkStatus} => getNetworkStatus
AbeilleMQTTCmd 2018-06-21 16:09:38[DEBUG]Type: CmdAbeille Address: Ruche avec Action: getNetworkStatus
PHP Notice:  Undefined offset: 1 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/function.php on line 15
AbeilleMQTTCmd 2018-06-21 16:09:38[DEBUG]processCmd call with: getNetworkStatus-getNetworkStatus-

**Comment by xionfr40** [comment]
Je t'en mets d'autre en vrac (que je n'avais pas vu) :

AbeilleMQTTCmd 2018-06-21 16:13:15[DEBUG]Processing MQTT message from jeedom:jeedom@127.0.0.1:1883 qos=0 with log level debug
PHP Notice:  Undefined variable: GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmd.php on line 682

----------------
AbeilleMQTTCmd 2018-06-21 16:13:15[DEBUG]Create a MQTT Client
AbeilleMQTTCmd 2018-06-21 16:13:15[DEBUG]try part
AbeilleMQTTCmd 2018-06-21 16:13:15[DEBUG]Subscribed to topic: #
AbeilleMQTTCmd 2018-06-21 16:13:15[DEBUG]Let loop for ever
PHP Notice:  Undefined offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmd.php on line 33
NFO] : Mosquitto: Connexion à Mosquitto avec code 0 Connection Accepted

----------
PHP Notice:  Undefined variable: GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 1765


-------
AbeilleParser 2018-06-21 16:13:15[DEBUG]Create a MQTT Client
AbeilleParser 2018-06-21 16:13:15[DEBUG]try part
PHP Notice:  Undefined variable: parameters_info in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 1818
AbeilleParser 2018-06-21 16:13:15[DEBUG]Subscribed to topic:
[2018-06-21 16:13:15][INFO] : Mosquitto: Connexion à Mosquitto avec code 0 Connection Accepted.


-----------
PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3

**Comment by KiwiHC16** [comment]
Ruche avec Action: getNetworkStatus => done

**Comment by KiwiHC16** [comment]
AbeilleMQTTCmd.php on line 33 => Je ne trouve pas le soucis

**Comment by KiwiHC16** [comment]
/AbeilleParser.php on line 1765 => Done

**Comment by KiwiHC16** [comment]
AbeilleParser.php on line 1818 => done

**Comment by xionfr40** [comment]
pour le AbeilleMQTTCmd.php on line 33, j'attends que t'ai fini les autres, j'update, et je tente de checker avec toi.

**Comment by KiwiHC16** [comment]
PHP Warning: include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning: include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3

Celui ci est vraiment bizarre. Dans quel fichier trouves tu ca ?

**Comment by KiwiHC16** [comment]
Ok tout dois être dans le master maintenant.

**Comment by xionfr40** [comment]
Au demarrage de AbeilleParser

PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
AbeilleParser 2018-06-21 17:08:26[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-06-21 17:08:26[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-06-21 17:08:26[DEBUG]Create a MQTT Client
AbeilleParser 2018-06-21 17:08:26[DEBUG]try part
[2018-06-21 17:08:26][INFO] : Mosquitto: Connexion à Mosquitto avec code 0 Connection Accepted.

Le fichier /lib/Tools.php existe bien et a bien les droits.

Peut etre que le relatif dans un include n'est pas approprié, et qu’il faudrait passer par __DIR__ pour construire un absolu ?

**Comment by xionfr40** [comment]
exemple: include(dirname(__FILE__) . "../lib/Tools.php");  ?

**Comment by xionfr40** [comment]
Quelques warning dans: 

AbeilleMQTTCmdTimer: 
AbeilleMQTTCmdTimer 2018-06-21 17:08:26[DEBUG]Processing MQTT message from jeedom:jeedom@127.0.0.1:1883 qos=0 with log level debug
Processing MQTT message from jeedom:jeedom@127.0.0.1:1883 qos=0 with log level debug
PHP Notice:  Undefined variable: GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmdTimer.php on line 362
AbeilleMQTTCmdTimer 2018-06-21 17:08:26[DEBUG]Create a MQTT Client
AbeilleMQTTCmdTimer 2018-06-21 17:08:26[DEBUG]try part
AbeilleMQTTCmdTimer 2018-06-21 17:08:26[DEBUG]Subscribed to topic: #
PHP Notice:  Undefined offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmdTimer.php on line 151

------------

AbeilleCmdMQTT:

AbeilleMQTTCmd 2018-06-21 17:08:26[DEBUG]Processing MQTT message from jeedom:jeedom@127.0.0.1:1883 qos=0 with log level debug
AbeilleMQTTCmd 2018-06-21 17:08:26[DEBUG]Create a MQTT Client
AbeilleMQTTCmd 2018-06-21 17:08:26[DEBUG]try part
AbeilleMQTTCmd 2018-06-21 17:08:26[DEBUG]Subscribed to topic: #
AbeilleMQTTCmd 2018-06-21 17:08:26[DEBUG]Let loop for ever
PHP Notice:  Undefined offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmd.php on line 33

**Comment by KiwiHC16** [comment]
Sur qu'elle machine es tu ? (Car je n'ai pas le message /Lib/Tools.php dans le log AbeilleParser quand je demarre le plugin).

**Comment by xionfr40** [comment]
sur un Odroid-C2 avec Debian, Jessie

**Comment by KiwiHC16** [comment]
" GLOBAL in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmdTimer.php on line 362" => done

**Comment by xionfr40** [comment]
Pour le line 33, j'ai rajouté quelques log,

Le warning intervient quand le topic MQTT ne contient que 2 niveau (et pas 3)

AbeilleMQTTCmd 2018-06-21 17:17:29[DEBUG]Msg Received: Topic: {jeedom/status} => online
PHP Notice:  Undefined offset: 2 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleMQTTCmd.php on line 33

**Comment by KiwiHC16** [comment]
Que done un php -v ?
(Moi j ai => PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS ))

**Comment by xionfr40** [comment]
PHP 5.6.33-0+deb8u1 (cli) (built: Jan  5 2018 16:50:22)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies


pour le 151, cela semble etre le meme probleme que le 33 (parsing d'un topic à 2 arg et pas à 3)

**Comment by xionfr40** [comment]
dans fifo.php:

require_once(dirname(__FILE__). '/../lib/Tools.php');

=> plus de warning

**Comment by KiwiHC16** [comment]
Ok je le mets

**Comment by KiwiHC16** [comment]
require_once(dirname(FILE). '/../lib/Tools.php');
ou
require_once(dirname(__FILE__). '/../lib/Tools.php');
?

**Comment by KiwiHC16** [comment]
{jeedom/status} => online

Ajouté un test pour ne pas me prendre les messages des voisins.

**Comment by KiwiHC16** [comment]
require_once(dirname(FILE). '/../lib/Tools.php');

Si je fais ca ca ne demarre plus...

**Comment by xionfr40** [comment]
je recheck ce soir et je te dis

**Comment by xionfr40** [comment]
Tous les warning corrigé sauf le suivant qui se prodiut au démarrage des daemons:

PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3

mais ca marche quand meme...

Peut etre un souci avec le double include..
