### ISSUE TITLE
Sauvegarde: le repertoire docs n'est pas inclus

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#295]
Lors d'une restauration à partir d'un backup Jeedom, le repertoire docs du plugin n'est pas inclus dans le backup.

voir comment les docs et images peuvent être inclus dans le backup.

Dans le code du core: backup.php, docs est exclu ;)

	$excludes = array(
		'tmp',
		'log',
		'docs',
		'doc',
		'tests',
		'support',
		'backup',
		'.git',
		'.log',
		'core/config/common.config.php',
		config::byKey('backup::path'),
	);

**Comment by KiwiHC16** [comment]
Ok, ils faut qu on change le nom d'au moins deux repertoires...

**Comment by KiwiHC16** [comment]
Done.

**Comment by edgd1er** [comment]
Merci :)
