### ISSUE TITLE
Prises connectées Osram : compatibilité partielle

### ISSUE THREAD

**Issue by wolfnco** [KiwiHC16/Abeille#305]
Bonjour,

Je constate une compatibilité partielle de mes prises connectées Osram.
Le changement d'état fonctionne bien.
En revanche, je n'ai pas de remonté d'état, et dans la partie config/santé, les prises sont toujours en erreurs car pas de remontée auto.

Dans les commandes de l'objet, quand je clique sur l'info "état", ça me retourne 1 quelque soit l'état de la prise.

Est ce que tu as une de ces prises pour faire des tests ?

Merci

**Comment by KiwiHC16** [comment]
Oui j'ai maintenant une prise OSRAM. Je peux regarder ces aspects.

**Comment by wolfnco** [comment]
Merci Ben :)

**Comment by KiwiHC16** [comment]
Premier test rapide:
- getEtat fonctionne.
- getModelIdentifier: Plug 01
- getManufactuerName: OSRAM
- getSWBuild: V1.04.12

Et je vois dans ma synthese j'avais deja testé les retours et que cela fonctionne. Il faut probablement que j'ajoute comment faire dans la doc.

a suivre donc ...

**Comment by KiwiHC16** [comment]
Mets à jour avec le master et voir la doc: https://github.com/KiwiHC16/Abeille/blob/master/Documentation/600_OSRAM.asciidoc

**Comment by KiwiHC16** [comment]
Fonctionne même avec homebridge.
Ajout des groupes.

Tu me dis si je peux clore le sujet.

**Comment by wolfnco** [comment]
Je teste ce soir et te confirme ça !

**Comment by wolfnco** [comment]
Re
J'ai bien récupéré l'IEEE de la prise, mais je ne trouve pas celui du zigate. Il n'apparaît pas dans un listall.
Peux tu m'aider ?
Merci :)

**Comment by wolfnco** [comment]
en créant la commande, j'ai pu récupérer l'IEEE dans les logs. C'est marrant, je n'ai pas tout ça avec ma ruche !

**Comment by wolfnco** [comment]
Je ne m'en sors pas....
J'ai modifié les valeurs IEEE de la commande suivante avec les mac de la prise et de la zigate : 
![image](https://user-images.githubusercontent.com/36747565/41998117-45d27e0a-7a5a-11e8-8439-55437bcd7088.png)

Et j'ai cliqué sur  "BindShortToZigateEtat" puis "setReportEtat", mais ça ne change rien. Idem après un double toogle : 
![image](https://user-images.githubusercontent.com/36747565/41998228-87ccfc68-7a5a-11e8-8ce2-3af44ca6a030.png)

**Comment by KiwiHC16** [comment]
Le log AbeilleParser ?

**Comment by wolfnco** [comment]
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2142908/AbeilleParser.txt)

voilà. J'ai aperçu des fail dedans

**Comment by KiwiHC16** [comment]
Peux tu e donner le details de tes commandes : address=....

**Comment by KiwiHC16** [comment]
Il y a des "Configure Reporting response" dans le log main pas le Bind. Il faut chercher le Bind en premier.

**Comment by wolfnco** [comment]
short : address=7d89&targetExtendedAddress=7cb03eaa00a74923&targetEndpoint=03&ClusterId=0006&reportToAddress=00158d0002019914

**Comment by KiwiHC16** [comment]
Normalement tu n'avais pas a modifier les commandes si les adresses IEEE de la prise de la ruche sont à jour. Peux tu supprimer la prise ?
Faire un getName sur l'adresse 7d89 avec le end point 03.
Faire un Liste Equipement sur la ruche et un getNetworkStatus.
Puis bindShort et setReport.

**Comment by KiwiHC16** [comment]
Es tu sure de l adresse: 7cb03eaa00a74923
la mienne commence en 8418... 
Elle devrait avoir le meme debut (c est pas obligatoire).

**Comment by wolfnco** [comment]
J'ai recréé l'objet Abeille pour avoir les mêmes commandes (et le nouveau logo ;))
supprimé la prise
fait les getName, ListEquipement, getNetworkStatus.

Adresse de la  zigate : 
AbeilleParser 2018-06-27 23:13:18[DEBUG]ZiGate Short Address: 0000
AbeilleParser 2018-06-27 23:13:18[DEBUG]IEEE Address: 00158d0001b22f25

Adresse de la prise : 
![image](https://user-images.githubusercontent.com/36747565/42000154-1e51b930-7a60-11e8-9904-3ef6348d6879.png)

AbeilleParser 2018-06-27 23:12:52[DEBUG]Abeille i: 12; ID : 32; Short Addr : 7d89; IEEE Addr: 7cb03eaa00a74923; Power Source (0:battery - 1:AC): 01; Link Quality: 114

Donc bien cette adresse.

Puis j'ai cliqué sur les commandes bindshort et setreport sur l'objet osram qui s'est recréé automatiquement.

Et le temps que j'écrive ce message........
![image](https://user-images.githubusercontent.com/36747565/42000278-7d3975e6-7a60-11e8-862b-3e7de6b2e085.png)

**Comment by KiwiHC16** [comment]
Donc ca marche ?

**Comment by wolfnco** [comment]
Oui, merci beaucoup !
J'ai la même manip à faire pour ma deuxième prise. Peux tu me dire à quoi correspond le end point 03 dans la commande getname ?

**Comment by wolfnco** [comment]
Merci Ben pour ton aide.
Il manque une dernière fonctionnalité : un bouton don paypal pour te payer une bière :)

**Comment by KiwiHC16** [comment]
You are welcome.
Ca fait des années que j'utilise les softs des autres alors j'apporte ma participation au monde du SW libre...

**Comment by wolfnco** [comment]
Belle mentalité !
Mais ça me ferait quand même plaisir de te payer une bière ;)
Car tu es toujours très réactif et prêt à aider, et à toute heure ! C'est pas cher payé du coup une bière ;)

**Comment by KiwiHC16** [comment]
Si tu passes en Seine et Marne, avec plaisir...

**Comment by wolfnco** [comment]
Où plus précisément ? Je suis en limite du Val de Marne...

**Comment by KiwiHC16** [comment]
https://www.google.fr/maps/place/77120+Coulommiers/@48.8095777,2.9516943,11z/data=!4m5!3m4!1s0x47e8b0cab161e73f:0xc745547de035ea2c!8m2!3d48.813071!4d3.083497

**Comment by wolfnco** [comment]
Tu connais Interactive Fusion dans ta ville ?
C'est grâce à eux que j'ai eu mon NUC jeedom d'occasion. Ils ont été supers !

Ca fait un peu loin sinon. Si tu as un compte paypal à me donner en privé, je te ferai un petit paiement du prix d'une bière ;) Au pire ça te paiera un capteur Xiaomi ;)

**Comment by KiwiHC16** [comment]
Je ne connais pas Interactive Fusion. Je connais la rue d'apres l'adresse. Je ferai attention la prochaine fois que je passe par la bas.

Merci encore pour ton offre. C'est offer....
