### ISSUE TITLE
xiaomi inter mural double

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#308]
Il y a un endpoint 03 lorsque l'on fait une pression sur les deux boutons en même temps : cela ferait un etat3 . Je n'arrive à ajouter que des action mais pas d'info.

**Comment by KiwiHC16** [comment]
C est un inter avec pile ou sur secteur ?
Info doit etre dans le model JSON. L option creation manuelle n'est pas active.

**Comment by handfreezer** [comment]
pardon pour le délai de réponse : il s'agit du modèle à pile (l'inter fait 5 millimètres d'épaisseur).

Note cosmétique : le visuel ne matche pas

**Comment by KiwiHC16** [comment]
Peux u me confirmer que l on parle du "sensor_86sw2.json" ?

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-09-03 a 15 58 15](https://user-images.githubusercontent.com/8549674/44990719-35f2f100-af92-11e8-84cf-f94fb73c3593.png)
Dans les commandes de l objet, clic sur "Tester" de la commande nom.

Exemple de resultat:
![capture d ecran 2018-09-03 a 15 58 07](https://user-images.githubusercontent.com/8549674/44990749-4f943880-af92-11e8-9b51-061c8b31c489.png)

**Comment by KiwiHC16** [comment]
Effectivement sur le mien j 'ai en end point 3. Modif faite et pushed to master.
