### ISSUE TITLE
update de l'écran santé après remplacement

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#315]
Bonjour,

J'avais perdu la communication avec un module, je l'ai enrôlé de nouveau et fait le remplacement via le panel de la ruche, après cela, la santé marque bien la dernière heure de réception, mais toujours en rouge comme si cela faisait longtemps que l'on avait plus de communication:
![image](https://user-images.githubusercontent.com/2912752/42124879-9228355c-7c6b-11e8-87fa-3725c516aa11.png)

**Comment by KiwiHC16** [comment]
Les infos de cette page sont rafraichies toutes les minutes. Il faudrait que je fasse un refrsh à l ouverture de la page.
Est ce qu'après une minute, l info était à jour ?

**Comment by handfreezer** [comment]
oui (en fait, je ne sais pas si c'est une minute, mais je faisais des "F5" puis j'ouvrais de nouveau la fenêtre, et je n'ai pas fait cela plus d'une minute c'est sûr.)
