### ISSUE TITLE
Feature request / question : suppression de l'ancien noeud en cas de remplacement

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#316]
Bonjour,

   Je voulais savoir s'il y avait une raison particulière à ne pas remplacer intégralement l'ancien noeud en cas d'usage de la commande remplacement?
   Aujourd'hui : le remplacement copie le nouveau noeud avec un nom "système", supprime l'ancien remplacé et laisse l'ancien nouveau.
   Demain : serait-il possible de supprimer l'ancien remplacé, l'ancien nouveau, et de reporter le nom de l'ancien noeud sur le nouveau noeud?

**Comment by KiwiHC16** [comment]
Actuellement si un equipement change de d'adresse, un nouveau est créé. D'où le besoin de la notion de remplacement. L'idée est de faire évoluer le soft de facon à ne pas se retrouver avec un nouvel objet. et doc pas de fonction replacement.

A venir...

**Comment by handfreezer** [comment]
on garde que le ticket #317
