### ISSUE TITLE
feature request : saisie de remplacement dans le noeud cible

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#317]
Bonjour,

   En fait, comme je viens d'avoir plein de nœud à resynchroniser (ok, il y a eu un problème de perte de synchro, et je n'arrive pas à reproduire sur ma maquette, donc je resynchronise tout le monde, car je n'ai rien mis en évidence de probant...) je me demandais si la manière de remplacement d'un nœud pouvait changer d'une manière ou de l'autre:
- solution 1 : avoir dans la page de propriété une liste déroulante des nœuds venant d'être synchroniser ou une box de saisie de l'adresse courte et le bouton "Remplacement nœud"
- solution 2 : quand un nœud se présente avec un MAC identique à un nœud déjà existant, alors faire le remplacement automatiquement.

**Comment by KiwiHC16** [comment]
J'ai en tête l'option 2 avec un bouton On/Off dans la conf du plugin.

**Comment by handfreezer** [comment]
Je t'avoue que je viens de reperdre 5 ou 6 devices et que les remettre serait franchement plus rapide avec la solution 2 (j'active l'inclusion, je fais le tour, et le reste se fait tout seul...) 

Perso, ça m'irait drôlement bien!

Note : cela ne règlera pas mon problème de fond, mais me permettra de survivre plus facilement en attendant d'investiguer.

**Comment by KiwiHC16** [comment]
Ce que je comprends de ton problème de fond est:
- tu as un réseau de test
- tu as un réseau de prod
- tu ne perds pas le équipements sur ton réseau de test
- tu perd des équipements sur ton réseau de prod
- tu n'as pas de routeur dans tes réseaux (autre que la zigate)
As tu essayé d'ajouter des routeurs (plug xiaomi par exemple ?). Car si ton réseau de test est dans une piece, tu n'as pas de probleme de couverture radio (pas de perte) et si ton réseau de prod est dans plusieurs pieces (probleme de couverture) -> perte.
Ici j'ai des ampoules Ikea qui sont à 4 mètres les unes des autres avec des branchages entre elles et ca me pose de vrais problèmes.

**Comment by handfreezer** [comment]
ce que tu décris est correct... mais : lorsque j'ai ré-associer mes périphériques, j'en ai perdu 4 dans la demi-heure presque, dont 2 plus proches que d'autres capteurs (même alignement je précise) que je n'ai pas encore perdu...
Sur le projet github de zigate, j'ai laissé une note explicative dans loosing devices car en fait j'ai eu un comportement suspect dans getdevicelist.

**Comment by KiwiHC16** [comment]
Yep j ai vu ton message. Je pense que cette fonction a ete dev par Akila.
EN esperant qu'il te réponde

**Comment by handfreezer** [comment]
question à côté : akila ?= fairecasoimeme ?

**Comment by KiwiHC16** [comment]
Oui

**Comment by KiwiHC16** [comment]
Inclus dans #242 qe je viens de clore, je clos.
