### ISSUE TITLE
feature request : link quality dans l'écran santé

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#318]
Bonjour,
Est-il possible d'ajouter la valeur du champ LinkQuality dans l'écran santé entre la colonne ID et la colonne Statut ?

**Comment by KiwiHC16** [comment]
Oui mais ...
LQI d'après ma compréhension et mes mesures ne remonte que la qualité des liens entre la zigate et ses voisines. Des qu'il y a un routeur dans le réseau, ces valeurs pour l'utilisateur final ne sont que partiellement pertinentes. Il est bien plus pertinent de regarder les graphes réseaux avec les valeur de LQI. Pour l'instant je ne suis pas pour, dans la mesure ou cela va amener plus de questions que de réponses. Peut être devons nous formuler ce que nous voulons résoudre...

**Comment by handfreezer** [comment]
Bonjour,
ok, je comprends. pour ma part, je ne cherche pas à résoudre une situation particulière, mais cela m'intéresserait dans le cadre de perte régulière de périph xiaomi et à titre d'information.

**Comment by KiwiHC16** [comment]
Actuellement tu dois trouver la valeur dans le champs LQI de l'équipement (Tu peux garder l historique pour faire des courbes,etc...).
Enfin ce champ n'est pas le LQI mais le RSSI si je me souviens bien. Il faudrait que je re regarde le code.

L'autre solution est d'utiliser le menu "network graph":
![capture d ecran 2018-07-08 a 10 34 36](https://user-images.githubusercontent.com/8549674/42418146-aaea8e84-829a-11e8-9aac-8d69fa28cb35.png)
et de choisir le champ "LinkQualityDec" (La c est le vrai LQI).

Il faut juste mettre a jour le fichier "NetworkDefinition.php" avec tes informations.

**Comment by KiwiHC16** [comment]
Ou network list:
![capture d ecran 2018-07-08 a 11 42 12](https://user-images.githubusercontent.com/8549674/42418748-0ed733d2-82a7-11e8-9e68-9201b0a6f5c7.png)

**Comment by handfreezer** [comment]
ok, je vais viser l'historique car je n'ai pas de routeur pour l'instant du coup la valeur doit avoir un sens.

**Comment by KiwiHC16** [comment]
Les infos sont dispos dans differentes pages donc je clos le point.
Si un besoin pas couvert par l existant on ouvrira une qutre issue.
