### ISSUE TITLE
Volet Profalux: bougent mais ne fonctionnent pas.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#324]

**Comment by KiwiHC16** [comment]
Je viens de refaire une instal clean j'ai toujours le même problème avec mes volets profalux
J'ai fais tous les get sur un volet et voila ce que j'obtiens :

```
AbeilleParser 2018-07-08 15:15:05[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=1
AbeilleParser 2018-07-08 15:15:05[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=1
AbeilleParser 2018-07-08 15:15:05[DEBUG]Create a MQTT Client
AbeilleParser 2018-07-08 15:15:05[DEBUG]try part
AbeilleParser 2018-07-08 15:15:05[DEBUG]Subscribed to topic: 
AbeilleParser 2018-07-08 15:17:05[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: a6
AbeilleParser 2018-07-08 15:17:05[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:10[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-07-08 15:17:10[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:11[DEBUG];type: 8014: ( “Permit join” status response)(Processed->MQTT); Permit Join Status: 01
AbeilleParser 2018-07-08 15:17:11[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:13[DEBUG];type: 004d (Device announce)(Processed->MQTT); Src Addr : 3a8f; IEEE : 20918a0000012440; MAC capa : 8e
AbeilleParser 2018-07-08 15:17:13[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:13[DEBUG]Je demande a l equipement d annoncer son nom
AbeilleParser 2018-07-08 15:17:13[DEBUG]Je demande a l equipement de type generique
AbeilleParser 2018-07-08 15:17:15[DEBUG]Je demande a l equipement de type Hue
AbeilleParser 2018-07-08 15:17:17[DEBUG]Je demande a l equipement de type OSRAM
AbeilleParser 2018-07-08 15:17:19[DEBUG]Je demande a l equipement de type ProFalux
AbeilleParser 2018-07-08 15:17:19[DEBUG] type: 8701 (Route Discovery Confirm)(Decoded but Not Processed); Status : 00; Nwk Status : 00
AbeilleParser 2018-07-08 15:17:19[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 09
AbeilleParser 2018-07-08 15:17:19[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:19[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 09; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-
AbeilleParser 2018-07-08 15:17:19[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0A
AbeilleParser 2018-07-08 15:17:19[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:19[DEBUG];type: 004d (Device announce)(Processed->MQTT); Src Addr : 3dfe; IEEE : 20918a0000012441; MAC capa : 80
AbeilleParser 2018-07-08 15:17:19[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:19[DEBUG]Je ne demande pas a l equipement d annoncer son nom car ce n est pas un routeur (il n ecoute peut etre pas).
AbeilleParser 2018-07-08 15:17:19[DEBUG] type: 8701 (Route Discovery Confirm)(Decoded but Not Processed); Status : 00; Nwk Status : 00
AbeilleParser 2018-07-08 15:17:19[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0B
AbeilleParser 2018-07-08 15:17:19[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:19[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0C
AbeilleParser 2018-07-08 15:17:19[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:20[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:20[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 0C; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0005; Data byte list : ->volet<-
AbeilleParser 2018-07-08 15:17:20[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:17:34[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0D
AbeilleParser 2018-07-08 15:17:34[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:35[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 0D; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00
AbeilleParser 2018-07-08 15:17:36[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0E
AbeilleParser 2018-07-08 15:17:36[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:37[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 0E; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 02; Status : 00
AbeilleParser 2018-07-08 15:17:40[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0F
AbeilleParser 2018-07-08 15:17:40[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:17:41[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 0F; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 01; Status : 00
AbeilleParser 2018-07-08 15:17:42[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 10
AbeilleParser 2018-07-08 15:17:43[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 10; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00
AbeilleParser 2018-07-08 15:17:44[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 11
AbeilleParser 2018-07-08 15:17:45[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 11; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 01; Status : 00
AbeilleParser 2018-07-08 15:17:47[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 12
AbeilleParser 2018-07-08 15:17:48[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 12; EndPoint : 01; Cluster ID: 0008-General: Level Control; Command : 04; Status : 00
AbeilleParser 2018-07-08 15:18:03[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-07-08 15:18:03[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:18:04[DEBUG];type: 8014: ( “Permit join” status response)(Processed->MQTT); Permit Join Status: 01
AbeilleParser 2018-07-08 15:18:04[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:04[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-07-08 15:19:04[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-07-08 15:19:04[DEBUG];type: 8014: ( “Permit join” status response)(Processed->MQTT); Permit Join Status: 00
AbeilleParser 2018-07-08 15:19:04[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:32[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 13
AbeilleParser 2018-07-08 15:19:33[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:33[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 13; Src Addr : 3a8f; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01
AbeilleParser 2018-07-08 15:19:33[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:37[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 14
AbeilleParser 2018-07-08 15:19:38[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:38[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 14; Src Addr : 3a8f; End Point : 01; Cluster ID : 0008; Attr ID : 0000; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 00
AbeilleParser 2018-07-08 15:19:38[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:42[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 15
AbeilleParser 2018-07-08 15:19:43[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:43[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 15; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0004; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : 
AbeilleParser 2018-07-08 15:19:45[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 16
AbeilleParser 2018-07-08 15:19:46[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:46[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 16; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-
AbeilleParser 2018-07-08 15:19:47[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 17
AbeilleParser 2018-07-08 15:19:48[DEBUG]mqttPublish with Qos: 1
AbeilleParser 2018-07-08 15:19:48[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 17; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 4000; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : 
```

La je sais plus quoi faire

**Comment by KiwiHC16** [comment]
Apres avoir ouvert a l inclusion, on voit un équipement arriver:

`type: 004d (Device announce)(Processed->MQTT); Src Addr : 3a8f; IEEE : 20918a0000012440; MAC capa : 8e`

Abeille demande à l'équipement de s'identifier. Une route est trouvée pour joindre l'équipement (ce qui voudrait dire qu'il n'y a pas de route directe).

`AbeilleParser 2018-07-08 15:17:19[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 09; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-`

Il remonte un nom vide (C'est normal pour un volet).

Un deuxieme équipement s'annonce: 

`type: 004d (Device announce)(Processed->MQTT); Src Addr : 3dfe; IEEE : 20918a0000012441; MAC capa : 80`

Ce n'est pas le même (peut être la telecommande, Abeille ne l'interroge pas car non routeur).

Puis le volet s'annonce avec le mot clef 'volet' (Adresse: 3a8f).

`Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 0C; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0005; Data byte list : ->volet<-`

Puis toute un série de On/Off/Toogle que le volet (Je suppose que c'est le volet) accepte sans erreur:

```
AbeilleParser 2018-07-08 15:17:35[DEBUG];Type: 8101 (Default Response)(Not Processed); Le probleme c est qu on ne sait pas qui envoie le message, on a pas la source, sinon il faut faire un mapping avec SQN, ce que je ne veux pas faire.; SQN : 0D; EndPoint : 01; Cluster ID: 0006-General: On/Off; Command : 00; Status : 00
AbeilleParser 2018-07-08 15:17:36[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0E
```

Ensuite le volet repond aux questions:
```
AbeilleParser 2018-07-08 15:19:33[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 13; Src Addr : 3a8f; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 01

AbeilleParser 2018-07-08 15:19:38[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 14; Src Addr : 3a8f; End Point : 01; Cluster ID : 0008; Attr ID : 0000; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 00

AbeilleParser 2018-07-08 15:19:43[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 15; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0004; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list :

AbeilleParser 2018-07-08 15:19:46[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 16; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-

AbeilleParser 2018-07-08 15:19:48[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 17; Src Addr : 3a8f; End Point : 01; Cluster ID : 0000; Attr ID : 4000; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list :
```

**Comment by KiwiHC16** [comment]
Peux tu partager une capture de l objet volet ?
Tout semble fonctionner corectement vue d'Abeille.

@zoozbiro, sais tu si il y a des manips particulieres à faire sur la conf du volet ?
(Symptome: le volet bouge sur la reception des commandes mais ne réalise pas la commande).

**Comment by zoozbiro** [comment]
Non pas de manip particulière sur le volet. Par contre j'ai déjà eu un problème similaire mais je n'ai pas su comprendre pourquoi.

quelque question pour comprendre le problème :

Le volet fonctionne t-il correctement avec ça télécommande (monter, descendre, stop)
si j'ai bien compris lorsque la zigate est mise mode inclusion le volet fait un allé retour, correct ?
Aucune fonction abeille du volet ne fonctionne ? (Identify, ou Time-Time)  ?

manipulation a tester : 

mise en inclusion de zigate
télécommande 1 appui sur R puis bouton monté (volet bouge ? test des fonction depuis jeedom ?)
si fonctionne pas supprimer l'objet abeille du volet
redémarrer deamon abeille
objet abeille volet créé ? 
si oui test fonctionnement si non ne fonctionne pas supprimer objet.
refaire télécommande 1 appui sur R puis bouton monté (volet bouge ?)
objet abeille volet créé ?
si oui test fonctionnement si non ne fonctionne pas supprimer objet.
Suivre la doc de Dams 
https://github.com/KiwiHC16/Abeille/blob/master/Documentation/400_Profalux.asciidoc
bien faire une remise à Zéro de le télécommande. (5xR) puis refaire l'inclusion.

**Comment by KiwiHC16** [comment]
Est ce une zigate wifi ou usb ?

**Comment by zoozbiro** [comment]
usb pour moi

**Comment by cyrililo** [comment]
@KiwiHC16 
Merci d'ouvrir cette Issue
J'ai bien une zigate usb aussi :

Voila une capture d'écran de l'objet volet

![capture d ecran 12](https://user-images.githubusercontent.com/5822424/42461480-d8a95d12-83a0-11e8-9164-8b26b9c4abef.png)

![capture d ecran 14](https://user-images.githubusercontent.com/5822424/42461580-1bfc844a-83a1-11e8-9468-7982d67a9b91.png)

@zoozbiro 

Une fois inclus le volet fonctionne bien avec sa télécommande

En fait chaque fonction de abeille monter, descendre, level..... fait faire un léger aller retour au volet comme il le fait en mode inclusion.

Je ne peut fermer, ouvrir et le stoper  le volet comme avec la télécommande depuis abeille.

J'ai tester ce que tu m'a dis mais rien ne le fait fonctionner correctement.

Je connais par cœur la doc de Dams mais rien y fait.

J'ai le dernier firmware 3.0D, je suis sur une clean install de jeedom la dreniere version 3.2.10
Les périphériques xioami que j'ai, fonctionnent correctement avec abeille.

**Comment by KiwiHC16** [comment]
Peux tu ajouter un copie d ecran des commandes de l objet volet ?
Peux tu aussi faire les getXXXX et partager la capture d ecran car dans ton exemple les infos ne sont pas pressentes.

**Comment by cyrililo** [comment]
Voila les captures des commandes

![capture d ecran 15](https://user-images.githubusercontent.com/5822424/42463934-e9fd8da2-83a7-11e8-9948-3d9b24b66493.png)
![capture d ecran 16](https://user-images.githubusercontent.com/5822424/42463940-ec6df48c-83a7-11e8-9ed8-351c0d4c0cbf.png)
![capture d ecran 17](https://user-images.githubusercontent.com/5822424/42463945-ee23a70e-83a7-11e8-8e01-66d8094a86f5.png)

![capture d ecran 18](https://user-images.githubusercontent.com/5822424/42464222-a935324c-83a8-11e8-9f80-041d0de80a7b.png)

![capture d ecran 19](https://user-images.githubusercontent.com/5822424/42464228-ad478efc-83a8-11e8-9756-252ff1b014c8.png)

J’espère que ça ira les logs en captures

**Comment by cyrililo** [comment]
@KiwiHC16
 
Bon ben je pense avoir trouvé la solution.
Désolé de vous avoir fait perdre votre temps car plusieurs d'entre vous, avez bien spécifié de regarder si les volets profalux étaient mis à jour, avec le dernier firmware ha 1.2

Ce qui n'est apparemment pas le cas avec mes volets.
Je pensé que c’était le cas, car c’était moi qui avait envoyer ma télécommande zoe à Akila pour qu'il décode les trames zigbee et rende la zigate compatible avec le volets profalux.

De plus lors de mes premiers tests j'arrivé à commander tous mes volets normalement donc c'est aussi ce qui m'a induits en erreur.

J'ai contacté profalux pour faire une mise à jour de mes volets et reviens vous pour vous dire si cela à réglé le problème.

Merci encore du temps que vous m'avez consacré.

**Comment by KiwiHC16** [comment]
Comment fais tu pour connaitre la version firmware de tes volets ?

**Comment by dams74** [comment]
Je crois qu'il faut donner le numéro de série d'un volet à profalux afin qu'il regarde dans leur base.

**Comment by cyrililo** [comment]
En fait sur chaque volet il y a une étiquette avec un numéro de série, la première lettre commence par un  C puis viens l'année de construction du volet,  pour ma par  le numéro commence par C15 puis une suite de chiffres, 
Ce qui veut dire  que mes volets sont de 2015.

Les volets profalux avec le firmaware 1.2 ou un autre plus récent peut être, sont construit a partir de juillet 2016 c'est aussi ceux la qui peuvent être commander par leurs box domotique propriétaire:  CALYPS’HOME

Ils ont sortie cette box pratiquement en même temps que la zigate :)

[Compatibilite-CalypsHome-220318.pdf](https://github.com/KiwiHC16/Abeille/files/2192229/Compatibilite-CalypsHome-220318.pdf)$

J'ai eu au  aussi un installateur au téléphone ,qui à rajouté des volets dans une des maisons de notre résidence, qui sont exactement les mêmes volets.

Il m'a dit qu'il a du faire une mise à jour du firmware des volets par profalux pour rajouter les nouveaux, autrement  les nouveaux volets ne pouvaient pas fonctionner avec les anciens.

Voila tout !!

**Comment by cyrililo** [comment]
C'est a quoi je pensé,  c'est indiqué dans la doc calypshome par contre j'ai pas trouvé le module

**Comment by dams74** [comment]
Je vous tiens au courant

**Comment by KiwiHC16** [comment]
On va dire que la solution est l upgrade firmware des volets.
Si cela ne repond pas à la problematique on rouvrira une issue.

**Comment by MaxDak** [comment]
Salut, 
confronté au même problème à savoir: va et viens en guise de réponse à toutes les commandes (mes volets profalux sont récents moins d'un mois). 
J'ai enfin réussi à les piloter !
J'ai suivi la procédure classique d'appairage à la seule différence que j'ai fermé totalement le volet avant de commencer la procédure.
Et la miracle toutes les commandes fonctionnent...

**Comment by cyrililo** [comment]
@MaxDak , Merci pour l'info, j'ai pas encore fais la mise a jours, Profalux me demande environ 300 euros pour mes 9 volets, c'est pas donné. Si par hasard quelqu'un saurait comment le faire sois même.... faudrait aussi disposer du firmware.
Pas chez moi en ce moment mais j’essaierai à mon retour.

**Comment by cyrililo** [comment]
J'ai pu re tester l'inclusion des volets aujourd'hui. Cette fois ça a pu fonctionner mais la méthode est assez bizarre, mais fonctionne.
Donc incluion du volet avec la procédure classique mais volet fermé comme le précise MaxDak, puis ensuite ouverture complète du volet  et fermeture complète 2 fois avec la télécommande.
Le volet fais un va et vient.
Et maintenant je peux piloter chaque volet normalement.
Si je ne fais pas ces 2 ouvertures et fermeture complète après l'inclusion cela ne fonctionne pas. 
Par contre le  niveau d'ouverture du volet ne reste pas en mémoire dans jeedom. 
Par exemple si j'ouvre mon volet à 75% que je quitte jeedom et que reviens dessus le volet et indiquer en position fermée. 
Voilà tout, merci @Maxdak pour m'avoir aider à avancer dans l'inclusion. 
Aussi cela nous apprends qu'il est quand même possible de domotiser les volets profalux avec un firmware plus ancien...

**Comment by cyrililo** [comment]
@kiwiHc16 merci encore pour ton travail !

**Comment by Kadmilos** [comment]
Petit up pour ce post qui m'a bien aidé : après avoir passé 3 jours dans le noir le volet bloqué, j'ai enfin pu le faire fonctionner ! Et l'indicateur de position marche nickel. 
Gros merci à @MaxDak et @cyrililo !!
