### ISSUE TITLE
Perte équipement

### ISSUE THREAD

**Issue by gtranche** [KiwiHC16/Abeille#325]
Bonjour,
j'ai un soucis avec un capteur de température Xiaomi (le carré), régulièrement je n'ai plus de remontée d'infos.
Je redémarre le demon et pouf ça refonctionne.
C'est aléatoire, des fois ça va prendre 2j a tomber, des fois 1 semaines, etc. Mais le résultat est le même et le redémarrage règle le soucis à chaque fois.

Je n'ai pour le moment pas d'autre équipement ZiGate pour savoir si  c'est global ou si c'est une perte de connexion.

Merci

**Comment by KiwiHC16** [comment]
Bonjour,
Si tu redemarre le demon, ce n'est pas le capteur.
Peux tu mettre en debug et partager les logs ?
Sur quelle machine es tu ?
Une zigate wifi ou USB ?

**Comment by gtranche** [comment]
Bon ... pour le moment je n'ai rien de plus.
![jeedom abeille](https://user-images.githubusercontent.com/2045296/42994699-13c1b84c-8c0f-11e8-901e-2b8f80d3f712.PNG)
comme tu peux le voir, c'est la première fois que l'équipement tient aussi longtemps ...

**Comment by KiwiHC16** [comment]
Qu'elle version de Abeille utilises tu ? (Stable/Beta ou Master Github,...)

**Comment by KiwiHC16** [comment]
```la Stable, je n'aurais pas ouvert un ticket sur un truc en beta :p```
Si tu regardes bien les commentaires dans le market, tu verras que la stable est une beta.

Je n'ai pas de soucis que tu poses des questions ca me permet d'ameliorer le plugin.

Ok je clos le sujet.
