### ISSUE TITLE
Plantage

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#327]

**Comment by wolfnco** [comment]
Description : après chaque relance le plugin ne fonctionne qu'une heure ou deux avant de ne plus donner les nouvelles données

**Comment by wolfnco** [comment]
[Abeille_1507.txt](https://github.com/KiwiHC16/Abeille/files/2195537/Abeille_1507.txt)
[AbeilleParser_1507.txt](https://github.com/KiwiHC16/Abeille/files/2195538/AbeilleParser_1507.txt)

**Comment by KiwiHC16** [comment]
Rien dans ces logs qui indique la raison du probleme.

On voit que Abeille tourne et indique que la derniere com est à 1h45
[2018-07-15 09:07:02][DEBUG] : Name: Alimentation_Poulailler lastCommunication: 2018-07-15 01:45:29
Et à 1h45:38 soit 9s plus tard le log Parser s'arrête. As tu tronquéé le log ou tu as mis le log complet ?

Peux t partager les autres logs en particulier AbeilleSerialRead.

Autres questions:
- comment sais tu que ca ne fonctionne plus ? Quelle info?
- Si tu fais un getVersion sur la ruche, est ce que Last et Last Stamps se mettent à jour sur la ruche ? (quand c est planté)
- Est ce une zigate TTL ?
- Est ce que le reste de jeedom fonctionne toujours ?
- Est ce que tu peux controller la prise ? 
- Quand c est planté, est ce que tout les indicateurs du demon sont au vert ?

**Comment by KiwiHC16** [comment]
NUC debian 9 i5 8Go de RAM
Pas de conteneurs ni de virtu
Dernière version de jeedom

**Comment by KiwiHC16** [comment]
![image](https://user-images.githubusercontent.com/8549674/42732311-938a28f0-881f-11e8-99b7-1b462b9ad2e6.png)

**Comment by KiwiHC16** [comment]
Si tu me dis comment me connecté, je peux jeter un oeil quand le systeme est HS pour voir ce qu'il se passe.

**Comment by wolfnco** [comment]
Je vais être occupé les prochaines heures, je te réponds dès que possible.
Pas d'accès ssh distant possible, mais je peux te donner l'accès jeedom si tu promets de ne pas faire de bêtises :)

**Comment by KiwiHC16** [comment]
Ok pas de soucis, tiens moi au courant. Je ne ferais que de la consultation. Si besoin de faire des changement je te demanderai de les faire.
Je suis dispo maintenant pendant une heure, après c'est bien moins sure....

**Comment by wolfnco** [comment]
```
root@nuc:/home/matthieu# fuser /dev/ttyUSB0
/dev/ttyUSB0:         1400
```


```
root@nuc:/home/matthieu# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
...
root       445     1  0 Jul14 ?        00:00:01 /usr/sbin/cron -f
mosquit+   472     1  0 Jul14 ?        00:00:43 /usr/sbin/mosquitto -c /etc/mosq
root       532     1  0 Jul14 tty1     00:00:00 /sbin/agetty --noclear tty1 linu
root       547     1  0 Jul14 ?        00:00:00 /usr/sbin/sshd -D
root       549     1  0 Jul14 ?        00:00:04 /usr/sbin/apache2 -k start
root       570     1  0 Jul14 ?        00:01:03 /usr/bin/python3 /usr/bin/fail2b
mysql      689     1  0 Jul14 ?        00:04:42 /usr/sbin/mysqld
Debian-+   995     1  0 Jul14 ?        00:00:00 /usr/sbin/exim4 -bd -q30m
ntp       1002     1  0 Jul14 ?        00:00:06 /usr/sbin/ntpd -p /var/run/ntpd.
www-data  1359     1  0 Jul14 ?        00:00:09 php /var/www/html/core/class/../
www-data  1387   549  0 Jul14 ?        00:00:25 /usr/sbin/apache2 -k start
www-data  1400     1  0 Jul14 ?        00:00:00 /usr/bin/php /var/www/html/plugi
www-data  1402     1  0 Jul14 ?        00:00:18 /usr/bin/php /var/www/html/plugi
www-data  1404     1  0 Jul14 ?        00:00:06 /usr/bin/php /var/www/html/plugi
www-data  1406     1  0 Jul14 ?        00:00:09 /usr/bin/php /var/www/html/plugi
root      1435     1  0 Jul14 ?        00:00:00 sudo /usr/bin/python /var/www/ht
root      1436  1435  3 Jul14 ?        00:41:26 /usr/bin/python /var/www/html/pl
www-data  1479     1  0 Jul14 ?        00:00:24 php /var/www/html/core/class/../
www-data  1518     1  2 Jul14 ?        00:37:34 /usr/bin/python /var/www/html/pl
root      2822     2  0 20:09 ?        00:00:00 [kworker/u8:2]
root      2840     2  0 20:09 ?        00:00:00 [kworker/3:2]
www-data  3495   549  0 14:37 ?        00:00:10 /usr/sbin/apache2 -k start
root      7714     2  0 18:39 ?        00:00:00 [kworker/1:0]
www-data  7864   549  0 11:34 ?        00:00:19 /usr/sbin/apache2 -k start
root     10370     2  0 21:09 ?        00:00:00 [kworker/3:1]
www-data 12421   549  0 20:51 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 12450   549  0 20:51 ?        00:00:00 /usr/sbin/apache2 -k start
root     15247     2  0 19:39 ?        00:00:00 [kworker/0:2]
www-data 15455   549  0 14:43 ?        00:00:08 /usr/sbin/apache2 -k start
root     19050     2  0 14:09 ?        00:00:03 [kworker/2:0]
root     19177     1  0 06:26 ?        00:00:00 /usr/lib/packagekit/packagekitd
root     19182     1  0 06:26 ?        00:00:00 /usr/lib/policykit-1/polkitd --n
root     20137     2  0 18:09 ?        00:00:00 [kworker/0:0]
www-data 22074   549  0 01:31 ?        00:00:21 /usr/sbin/apache2 -k start
www-data 22084   549  0 01:31 ?        00:00:20 /usr/sbin/apache2 -k start
www-data 22212   549  0 01:31 ?        00:00:25 /usr/sbin/apache2 -k start
root     22773     2  0 20:39 ?        00:00:00 [kworker/1:2]
root     25483   547  0 21:36 ?        00:00:00 sshd: matthieu [priv]
root     26062     2  0 01:15 ?        00:00:02 [kworker/u8:0]
matthieu 26070     1  0 21:36 ?        00:00:00 /lib/systemd/systemd --user
matthieu 26071 26070  0 21:36 ?        00:00:00 (sd-pam)
matthieu 26078 25483  0 21:36 ?        00:00:00 sshd: matthieu@pts/0
matthieu 26081 26078  0 21:36 pts/0    00:00:00 -bash
root     26952 26081  0 21:37 pts/0    00:00:00 su
root     27076 26952  0 21:37 pts/0    00:00:00 bash
root     28119  1436  0 21:37 ?        00:00:00 /usr/local/lib/python2.7/dist-pa
root     28131 27076  0 21:37 pts/0    00:00:00 ps -ef
www-data 30218   549  0 12:42 ?        00:00:16 /usr/sbin/apache2 -k start
root     32586     2  0 17:39 ?        00:00:03 [kworker/2:2]
```

Branché en usb : hub USB + port ethernet (car seulement wifi sur le NUC), autre hub USB avec alim externe, avec dongle BT, zigate et rflink (le hub a été ajouté très récemment, mais il y avait déjà le pb avant).

```
root@nuc:/home/matthieu# lsusb
Bus 002 Device 008: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 002 Device 017: ID 2341:0042 Arduino SA Mega 2560 R3 (CDC ACM)
Bus 002 Device 006: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 002 Device 004: ID 2109:2813 VIA Labs, Inc.
Bus 002 Device 005: ID 0bda:8153 Realtek Semiconductor Corp.
Bus 002 Device 003: ID 2109:2813 VIA Labs, Inc.
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
Je ne peux pas débrancher le premier hub car j'utilise l'ethernet dessus, mais je retire tout le reste.

Il reste donc la zigate en direct, et le hub usb/rj45 avec uniquement le cable réseau dessus.

Je ne vois pas si la zigate clignote après la commande, mais rien dans les logs. Faut-il que je la démonte pour voir la led ?

Je vois qu'Abeille semble être reparti tout seul !
Logs Abeille_Parser : 

```
AbeilleParser 2018-07-15 21:45:16[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-07-15 21:45:16[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-07-15 21:45:16[DEBUG]Create a MQTT Client
AbeilleParser 2018-07-15 21:45:16[DEBUG]try part
AbeilleParser 2018-07-15 21:45:16[DEBUG]Subscribed to topic:
AbeilleParser 2018-07-15 21:45:18[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 01
AbeilleParser 2018-07-15 21:45:19[DEBUG]type: 8701: (APS Data Confirm Fail)(Decoded but Not Processed); Status : d3; Source Endpoint : 01; Destination Endpoint : 01; Destination Mode : 02; Destination Address : 5331; SQN: : 01
AbeilleParser 2018-07-15 21:45:23[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 02
AbeilleParser 2018-07-15 21:45:24[DEBUG]type: 8701: (APS Data Confirm Fail)(Decoded but Not Processed); Status : d3; Source Endpoint : 01; Destination Endpoint : 01; Destination Mode : 02; Destination Address : 01da; SQN: : 01
AbeilleParser 2018-07-15 21:45:28[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 03
AbeilleParser 2018-07-15 21:45:29[DEBUG] type: 8701 (Route Discovery Confirm)(Decoded but Not Processed); Status : d0; Nwk Status : 00
AbeilleParser 2018-07-15 21:45:30[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:45:30[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: 03; Src Addr : 72a7; End Point : 03; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0007; Data byte list : ->Plug 01<-
AbeilleParser 2018-07-15 21:45:30[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:45:33[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 04
AbeilleParser 2018-07-15 21:45:34[DEBUG] type: 8701 (Route Discovery Confirm)(Decoded but Not Processed); Status : d0; Nwk Status : 00
AbeilleParser 2018-07-15 21:45:38[DEBUG];type: 8000 (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 05
AbeilleParser 2018-07-15 21:45:39[DEBUG]type: 8701: (APS Data Confirm Fail)(Decoded but Not Processed); Status : d3; Source Endpoint : 01; Destination Endpoint : 03; Destination Mode : 02; Destination Address : 7d89; SQN: : d0
AbeilleParser 2018-07-15 21:45:49[DEBUG] type: 8701 (Route Discovery Confirm)(Decoded but Not Processed); Status : d0; Nwk Status : 00
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:46:17[DEBUG];Type: 8102 (Attribut Report)(Processed->MQTT); SQN: bd; Src Addr : 7fd8; End Point : 01; Cluster ID : 0000; Attr ID : ff01; Attr Status : 00; Attr Data Type : 42; Attr Size : 001f; Data byte list : 0121270B0421a81305210F00062402000000006429c70B6521bd130A210000
AbeilleParser 2018-07-15 21:46:17[DEBUG]Champ proprietaire Xiaomi, decodons le et envoyons a Abeille les informations (Capteur Temperature Rond)
AbeilleParser 2018-07-15 21:46:17[DEBUG]Voltage: 2855
AbeilleParser 2018-07-15 21:46:17[DEBUG]Temperature: 3015
AbeilleParser 2018-07-15 21:46:17[DEBUG]Humidity: 5053
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
AbeilleParser 2018-07-15 21:46:17[DEBUG]mqttPublish with Qos: 0
```

**Comment by KiwiHC16** [comment]
Moi aussi occupé. Pas de soucis. 
Rflink ou autre, Oui c est ce que je me demande.

**Comment by KiwiHC16** [comment]
Je regardes demain tes logs car la je suis sur le mobile alors ce n’est pas top.

**Comment by KiwiHC16** [comment]
Si tu as debranchée la zigate il est fort probable que Abeille se mette en défaut et qu'apres 5 minutes, jeedom redemarre le plugin. Il faudrait que je fasse le teste pour être sure.

Sinon dans ps -ef, on voit le process 1400 appartenant à www-data mais on ne voit pas son nom, la ligne est tronquée mais on peut supposer que c'est abeille car il y a 1400, 1402, 1404 et 1406 à la suite.

Attendons de voir que dans cette config avec juste zigate et usb/eth tout fonctionne.

**Comment by KiwiHC16** [comment]
Oui ca me semble une bonne approche. Fais aussi par étapes, branchement de l'équipement un jour et activation du plugin associé le lendemain par exemple.

**Comment by wolfnco** [comment]
J'ai remis la dernière version github hier, et pas de problème de stabilité depuis.
Désolé donc d'avoir mis en cause la stabilité de tes version "beta" github...

Ce soir je brancherai le hub USB, et demain le rflink.

**Comment by KiwiHC16** [comment]
Pas de soucis.
Visiblement dans ce que j'ai vu, des plugins n'ont pas de definition manuelle du port USB utilisé. Du coup je ne sais pas comment ils choisissent le port et je me demande s'ils ne mettent pas le bazard ...

**Comment by wolfnco** [comment]
Lesquels ?

**Comment by KiwiHC16** [comment]
de memoire Bluetooth et rflink mais il faudrait verifier.

**Comment by wolfnco** [comment]
J'ai branché ce matin le hub USB autoalimenté, sans rien dessus. Et peu de temps après, plus de remontées !
Ton compte est toujours actif si tu veux regarder

**Comment by wolfnco** [comment]
les logs étaient en standard, je viens de les remettre en debug

**Comment by wolfnco** [comment]
lsusb (commande via l'interface web jeedom car pas d'accès distant en ssh) : 

Bus 002 Device 018: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 002 Device 019: ID 2109:2813 VIA Labs, Inc.
Bus 002 Device 005: ID 0bda:8153 Realtek Semiconductor Corp.
Bus 002 Device 003: ID 2109:2813 VIA Labs, Inc.
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by KiwiHC16** [comment]
Ok je regarde.

**Comment by wolfnco** [comment]
J'ai rebooté.... Dsl. Si le pb vient de là, il se reproduira bientôt

**Comment by KiwiHC16** [comment]
Je viens de supprimer la rchue et de redemarrer le plugin Abeille, pour avoir l object ruche a jour et il n'est plus en alarme. Le probleme vient des vieux objets qui ne possedent pas de timeout. Je vais faire une modif issue #328

**Comment by KiwiHC16** [comment]
Tout semble Ok actuellement. 
Je ne peux avoir les infos (dmesg) en passant par le menu roues-configuration-OS/DB-Administration.
Peux tu faire en root/ssh un dmesg et voir si tu trouves des messages d'erreur en relation avec les port USB.

**Comment by wolfnco** [comment]
Oui, mais qu'en rentrant ce soir

**Comment by wolfnco** [comment]
c'est mis à jour, mais ça ne semble pas bon : aucun info de dernière communication dans la page santé alors que les logs AbeilleParser s'incrémentent bien

**Comment by KiwiHC16** [comment]
il faut faire tourner le plugin:cron et le jeedom:cron5 pour rafraichir les infos ou attendre au moins 5 minutes. Puis faire un refresh de la page web.

**Comment by wolfnco** [comment]
tu m'as perdu là !

**Comment by KiwiHC16** [comment]
Ca semble ok mais j ai un effet de bord et la page Santé ne se met pas a jour correctement. Je regarde pourquoi.

**Comment by KiwiHC16** [comment]
Peux tu faire la mise a jour avec le master ?

**Comment by KiwiHC16** [comment]
Pour info j ai fait afficher des dates sur les widgets. Apres les tests il suffira de les enlever.

**Comment by wolfnco** [comment]
mise à jour. On a maintenant la date de dernière communication, mais le retour du "Very Old Last Communication (>7days)"

**Comment by KiwiHC16** [comment]
Je viens de pousser une modif qui semble fonctionner sur me deux systèmes. J espere que c est la bonne. SI tu peux mettre à jour avec master.

**Comment by wolfnco** [comment]
C'est la bonne :)

**Comment by wolfnco** [comment]
Le plugin a l'air d'être stable. Ça ne viendrait finalement pas du hub alimenté.
Demain matin je brancherai le dongle bt

**Comment by KiwiHC16** [comment]
a suivre...

**Comment by wolfnco** [comment]
Pour le temps en heures depuis lequel les équipements n'ont pas communiqués, pourrais tu arrondir à l'inférieur plutôt qu'au plus près ?
Je m'explique : de mémoire les équipements xiaomi remontent toutes les 50 minutes. Donc dès la 31ème minute, il est indiqué "1", et cela peut laisser penser à un problème, alors qu'il n'en est rien.

Ou sinon indiquer le temps en minutes.

Merci :)

**Comment by wolfnco** [comment]
Ce matin, j'ai eu le problème suite au branchement du dongle BT. Mais après un reboot, tout marchait bien. J'avais eu la même chose avec le hub alimenté, comme si l'ajout d'un device USB perturbait la zigate.

**Comment by KiwiHC16** [comment]
Mon experience est que le branchement/debranchement peut générer des perturbations probablement du fait des variations de consommations.

**Comment by KiwiHC16** [comment]
Pour le temps en heures depuis lequel les équipements n'ont pas communiqués, pourrais tu arrondir à l'inférieur plutôt qu'au plus près ? => #329

**Comment by wolfnco** [comment]
J'ai branché le rflink ce matin : pas de problème. J'active maintenant le plugin.

On indique bien le port usb sur rflink :
![image](https://user-images.githubusercontent.com/36747565/42991711-b900a524-8c06-11e8-84e6-2200345e40d4.png)

Idem pour BLEA : 
![image](https://user-images.githubusercontent.com/36747565/42991753-e0717868-8c06-11e8-9a31-6a912f584ce6.png)

**Comment by KiwiHC16** [comment]
Ok,
Je ne comprends pas comment le BLEA fonctionne. Est ce une clef USB connectée ?

**Comment by wolfnco** [comment]
oui une clé usb

https://www.gearbest.com/usb-gadgets/pp_132019.html

**Comment by KiwiHC16** [comment]
It's strange because the ls -l /dev/ttyUSB* ne donne que:
`crwxrwxrwx 1 root dialout 188, 0 Jul 20 11:45 /dev/ttyUSB0`
sur ton systeme. Et un ls -l /dev/ttyA* ne donne que
`crwxrwxrwx 1 root dialout 166, 0 Jul 20 10:20 /dev/ttyACM0`

Donc je ne sais pas comment cette clef est gérée.

**Comment by wolfnco** [comment]
hcitool dev

Devices:
	hci0	00:1A:7D:DA:71:13

**Comment by KiwiHC16** [comment]
Qu'elle est la situation maintenant ?
Toujours des problemes ou je peux clore le sujet ?

**Comment by KiwiHC16** [comment]
Pas de nouvelle depuis 18 jours. Je clos le sujet. On rouvrira si besoin.

**Comment by wolfnco** [comment]
Désolé, j'étais en vacances, puis la reprise a été chargée.
Je regarde ça et te fais un point rapidement.
