### ISSUE TITLE
Bug potentiel Qos=0, conseillé a 1 dans la doc

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#33]
https://github.com/KiwiHC16/Abeille/blob/3bca3d3fdf7b7fe61eb4e27cffcec097e4bd17d9/resources/AbeilleDaemon/AbeilleMQTTCmd.php#L134

Pas sur que ce soit bien critique cependant....

**Comment by KiwiHC16** [comment]
Oui il faut que je regarde, il y a une bonne explication à https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels
Je suis aussi preneur des tes recommandations, ca me fera gagner du temps.
Merci pour ton travail sur les différents autres sujets.

**Comment by edgd1er** [comment]
voila j'ai mis tt paramètres pour la zigate. d'après l'article très intérréssant, le mode 0 est déconseille ( fire and forget ), le mode 1 apporte une sécurité (try & retry avec ack) mais risque de doublon, le mode 2 est bcp plus lourd. A voir si le mode 1 pose des pb pour l'activation de prise. toggle x2 = rien changé :(

A priori, je ne peux pas faire plusieurs pull requests, dans mon repo, j'ai corrigé qq problèmes et faits qq amélioration:
- création de ruche en doublon
- gestion, des états de dépendances ( ds jeedom) et etat du/des daemon(s)
- réamenagement/ajouts/suppression des logs  (error, info, debug)
A un moment, j'ai appliqué un reformatage de code sur le projet, du coup, je dois faire attention a ne pas commité ces modifs, désolé si qq unes passent ....
je pense que tu peux faire du cherry pick sur mon git mais je ne sais pas trop comment cela fonctionne.

ouais bon, je viens de voir que je ne suis pas aller au bout de la modif et que les trois daemons php ne prennent pas les modifs de paramètres....

**Comment by edgd1er** [comment]
j'ai ajouté l'utilisation des paramètres pour les 3 daemons, mais j'ai un pb avec AbeilleMQTTCmd quand le qos est mis a 1 , le client se déconnecte après 10 sec et ne traite plus les messages.

$topics['CmdAbeille/#'] = array("qos" => 0, "function" => "procmsg");

**Comment by KiwiHC16** [comment]
Ok j ai fait un commit de ton pull. Demain ou dans les jours a venir je vais tester.

**Comment by edgd1er** [comment]
Dans le commit que je viens de faire (30/01 1h22), je n'ai pas touché a cette ligne de code. la question reste entière. le Qos est reçue en paramètre par le daemon. Des tests peuvent être fait.

**Comment by KiwiHC16** [comment]
Ou as tu fais le commit ? Je ne le vois pas. Est ce un commit sur ton repository ?

**Comment by edgd1er** [comment]
après avec parametres tous les daemons, fonctions etc avec le qos, j'ai découvert que ça ne fonctionnait pas. Connection time out du client. ( a priori, confirmé par https://github.com/eclipse/mosquitto/issues/7 )
Dans les prochaines versions, il faudra sans doute mettre une note ou verrouiller le Qos a 0. J'ai la mosquitto v1.4.14, si qq'un peux essayer pour confirmer

**Comment by KiwiHC16** [comment]
Je ne sais pas si un jour je regarderai ce sujet car il ne me parait pas super important car avec 0 ca marche tres bien surtout qu'on est sur une machine unique.
Il faut aussi regarder pourquoi dans l histoire du dev on a deux lib mqtt: phpMQTT.php (https://github.com/bluerhinos/phpMQTT) et Mosquitto\Client (https://mosquitto-php.readthedocs.io/en/latest/client.html). Il faudrait probablement tout passer sous  Mosquitto\Client avant d'aller plus loin dans correction de ce sujet.

**Comment by KiwiHC16** [comment]
J'ai tout passé sous  Mosquitto\Client .

**Comment by KiwiHC16** [comment]
Je viens de passer en QoS 1 et tout fonctionne donc je clos le sujet.

**Comment by KiwiHC16** [comment]
En meme temps l info n est pas prise en compte !!! donc le qos utilisé est 0 .
