### ISSUE TITLE
warning in abeilleserialparser

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#334]
Bonjour, 
  je viens de voir dans les logs en debug de abeilleparserserial:

```
> PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
> PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
> AbeilleSerialRead 2018-08-19 14:20:17[DEBUG]Starting reading port /dev/ttyUSB1 and transcoding to /tmp/AbeilleDeamonInput with log level debug
> AbeilleSerialRead 2018-08-19 14:20:17[DEBUG]Starting with pipe file (to send info to AbeilleParser): /tmp/AbeilleDeamonInput
```

**Comment by KiwiHC16** [comment]
Je ne peux pas tester pour l instant car mes deux systemes sont avec les zigates Wifi et je ne vois pas ce soucis dans cette configuration.
As tu toujours ce problème quand tu (re-)démarres le plugin ?

**Comment by KiwiHC16** [comment]
Du nouveau sur ce sujet ?

**Comment by KiwiHC16** [comment]
En lien avec #373 ?

**Comment by handfreezer** [comment]
Je ne sais pas, j'ai toujours ceci, avec la dernière mise à jour (ce jour)

```
PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
AbeilleParser 2018-10-04 22:47:07[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on admin:admin!@127.0.0.1:1883 qos=0
AbeilleParser 2018-10-04 22:47:07[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on admin:admin!@127.0.0.1:1883 qos=0
AbeilleParser 2018-10-04 22:47:08[DEBUG]Create a MQTT Client
AbeilleParser 2018-10-04 22:47:08[DEBUG]try part
```

**Comment by KiwiHC16** [comment]
Je viens de faire un petit changement. Il devait y avoir un include d'include que le php n'aime pas.
C est dans le master.

**Comment by handfreezer** [comment]
Ok je ne pourrais tester que dans 3 jours.
-- 
Envoyé de mon gsm Android 


-------- Courriel d’origine --------
De : Ben <notifications@github.com>
Envoyé : 5 octobre 2018 10:20:11 GMT+02:00
À : KiwiHC16/Abeille <Abeille@noreply.github.com>
Cc : Handfreezer <github@ulukai.net>, Author <author@noreply.github.com>
Objet : Re: [KiwiHC16/Abeille] warning in abeilleserialparser (#334)

Je viens de faire un petit changement. Il devait y avoir un include d'include que le php n'aime pas.
C est dans le master.

**Comment by KiwiHC16** [comment]
Je clos.
