### ISSUE TITLE
Noeud

### ISSUE THREAD

**Issue by jordangidoin** [KiwiHC16/Abeille#335]
Bonsoir,

Déjà félicitation pour le travail ! 
Cela fonctionne plutôt bien !
J'aimerais avoir des infirmations sur le maillage des noeuds.

J'ai mis des ampoules IKEA et Philips et aussi une prise xiaomi afin de faire relais.
Mais j'ai du mal a atteindre des ampoules GU10 de IKEA que j'ai mi au sous-sol.

Comment faire pour que les noeuds communiquent entre eux ? c'est automatique ?

Merci de votre aide

**Comment by KiwiHC16** [comment]
Oui automatique. Il n y a rien a faire et on ne contrôle pas le fonctionnement. 
Pour voir ce qu il se passe aller dans   - protocol communication - abeille - network list ( refresh ) 
Les infos affichées sont les voisins radio, en gros qui voit qui. Au minimum il faut qu un équipement voir les GU10.

**Comment by jordangidoin** [comment]
Merci pour votre réponse !
Ce matin le graphique était à jour, et la quality était meilleure effectivement sur les GU10.
Par contre j'ai quelques pb avec le bind pour l'état et la luminosité, que faut-il faire, les réinitialiser ? cela fonctionne sur 1 mais pas sur la 2éme

**Comment by KiwiHC16** [comment]
Il faut effectivement un peu de temps pour que le réseau se "cale" avec les nouveaux équipements et les conditions radios. Dans certains cas, il ne sent sort pas et il peut être nécessaire de rajouter des routeurs. Les routes utilisées sont parfois très surprenantes.
Le bind est un peu "fragile" et ne fonctionne pas à tous les coups. Le bind peut etre perdu en cas de routage. Le mieux est de faire deux binds d'affilés avec disons 10 secondes entre les deux. Puis de faire le setReport.
