### ISSUE TITLE
Ajout Bouton rond Xiaomi

### ISSUE THREAD

**Issue by lukebr91** [KiwiHC16/Abeille#34]
http://zigate.fr/xiaomi-bouton-switch-cluster/

lumi.sensor_switch
J'ai réussi à l'intégrer en dupliquant "lumi.sensor_switch.aq2" et cela fonctionne..

Nota: Comme indiqué sur le site Zigate, le clic et le relâchement sont bien 2 instructions envoyées l'une après l'autre contrairement au aqara qui envoi les 2 en même temps lorsque l'on relâche.

**Comment by KiwiHC16** [comment]
Peux tu vous partager la configuration que tu as mis en place dans Abeille, as tu dupliqué dans le fichier JSON ?
Peux tu aussi mettre le plugin en mode semi-automatique pour voir toutes les commandes qui passent ? (On pourra comparer avec les info de Akila).

**Comment by lukebr91** [comment]
J'ai dupliqué le bouton aquara dans le JSON en supprimant simplement ".aq2" et le fonctionnement était OK avec pour seule distinction l'envoi d'une commande dès l'appui et une nouvelle au relâchement.

J'avoue ne pas encore tout maîtrisé dans les code mais j'épluche et j'essaie de comprendre ;)

Ensemble des Log ajout mode semi automatique : 
Abeille
> 2018-01-29 19:18:38][DEBUG] : Envoi du message Inclusion vers CmdAbeille/Ruche/SetPermit
> [2018-01-29 19:18:38][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q1, r0, m2, 'CmdAbeille/Ruche/SetPermit', ... (9 bytes))
> [2018-01-29 19:18:38][DEBUG] : 16 : Client Jeedom sending PUBACK (Mid: 2)
> [2018-01-29 19:18:38][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:38][DEBUG] : Message ->Inclusion<- sur CmdAbeille/Ruche/SetPermit
> [2018-01-29 19:18:38][DEBUG] : AbeilleMQTT, Msg Received: Topic: {CmdAbeille/Ruche/SetPermit} =>	Inclusion
> [2018-01-29 19:18:38][DEBUG] : AbeilleSerial: 2018-01-29 19:18:38 -> 80000005c90005004900
> [2018-01-29 19:18:38][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:38][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:38][DEBUG] : AbeilleParser: type: 8000
> [2018-01-29 19:18:38][DEBUG] : AbeilleParser: (Status)(Not Processed)
> [2018-01-29 19:18:45][DEBUG] : AbeilleSerial: 2018-01-29 19:18:45 -> 8048000Aa300158d00012678c50063
> [2018-01-29 19:18:45][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:45][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:45][DEBUG] : AbeilleParser: type: 8048
> [2018-01-29 19:18:45][DEBUG] : AbeilleParser: (Leave Indication)(Not Processed)
> [2018-01-29 19:18:48][DEBUG] : AbeilleSerial: 2018-01-29 19:18:48 -> 004d000Cec4d0100158d00012678c58063
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: type: 004d
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: (Device annouce)(Processed->MQTT)
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/IEEE-Addr', ... (16 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->00158d00012678c5<- sur Abeille/4d01/IEEE-Addr
> [2018-01-29 19:18:48][INFO] : objet: 00158d00012678c5 creation sans model
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-TimeStamp', ... (10 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->1517249928<- sur Abeille/4d01/Time-TimeStamp
> [2018-01-29 19:18:48][DEBUG] : L objet: Abeille/4d01 existe mais pas la commande: Time-TimeStamp
> [2018-01-29 19:18:48][INFO] : Creation par defaut de la commande: Abeille/4d01/Time-TimeStamp
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-Time', ... (19 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->2018-01-29 19:18:48<- sur Abeille/4d01/Time-Time
> [2018-01-29 19:18:48][DEBUG] : L objet: Abeille/4d01 existe mais pas la commande: Time-Time
> [2018-01-29 19:18:48][INFO] : Creation par defaut de la commande: Abeille/4d01/Time-Time
> [2018-01-29 19:18:48][DEBUG] : AbeilleSerial: 2018-01-29 19:18:48 -> 004d000C084d0100158d00012678c58087
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: type: 004d
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: (Device annouce)(Processed->MQTT)
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/IEEE-Addr', ... (16 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->00158d00012678c5<- sur Abeille/4d01/IEEE-Addr
> [2018-01-29 19:18:48][DEBUG] : L objet: Abeille/4d01 existe mais pas la commande: IEEE-Addr
> [2018-01-29 19:18:48][INFO] : Creation par defaut de la commande: Abeille/4d01/IEEE-Addr
> [2018-01-29 19:18:48][DEBUG] : AbeilleSerial: 2018-01-29 19:18:48 -> 8102001f6b004d010100000005004200126c756d692e73656e736f725f73776974636887
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: type: 8102
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: (Attribut Report)(Processed->MQTT)
> [2018-01-29 19:18:48][DEBUG] : AbeilleSerial: 2018-01-29 19:18:48 -> 8102000E6c014d010100000001002000010A87
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: type: 8102
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: (Attribut Report)(Processed->MQTT)
> [2018-01-29 19:18:48][DEBUG] : AbeilleSerial: 2018-01-29 19:18:48 -> 8701000302000087
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: type: 8701
> [2018-01-29 19:18:48][DEBUG] : AbeilleParser: (Route Discovery Confirm)(Not Processed)
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-TimeStamp', ... (10 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->1517249928<- sur Abeille/4d01/Time-TimeStamp
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-Time', ... (19 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->2018-01-29 19:18:48<- sur Abeille/4d01/Time-Time
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/0000-0005', ... (18 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->lumi.sensor_switch<- sur Abeille/4d01/0000-0005
> [2018-01-29 19:18:48][DEBUG] : L objet: Abeille/4d01 existe mais pas la commande: 0000-0005
> [2018-01-29 19:18:48][INFO] : Creation par defaut de la commande: Abeille/4d01/0000-0005
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-TimeStamp', ... (10 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->1517249928<- sur Abeille/4d01/Time-TimeStamp
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-Time', ... (19 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->2018-01-29 19:18:48<- sur Abeille/4d01/Time-Time
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/0000-0001', ... (2 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->10<- sur Abeille/4d01/0000-0001
> [2018-01-29 19:18:48][DEBUG] : L objet: Abeille/4d01 existe mais pas la commande: 0000-0001
> [2018-01-29 19:18:48][INFO] : Creation par defaut de la commande: Abeille/4d01/0000-0001
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-TimeStamp', ... (10 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->1517249928<- sur Abeille/4d01/Time-TimeStamp
> [2018-01-29 19:18:48][DEBUG] : 16 : Client Jeedom received PUBLISH (d0, q0, r0, m0, 'Abeille/4d01/Time-Time', ... (19 bytes))
> [2018-01-29 19:18:48][DEBUG] : --- process a new message -----------------------
> [2018-01-29 19:18:48][DEBUG] : Message ->2018-01-29 19:18:48<- sur Abeille/4d01/Time-Time
> [2018-01-29 19:18:56][DEBUG] : AbeilleSerial: 2018-01-29 19:18:56 -> 8702000E5ff00101024d0101040000a7014e87
> [2018-01-29 19:18:56][DEBUG] : AbeilleParser: -----------------------
> [2018-01-29 19:18:56][DEBUG] : AbeilleParser: protocolData
> [2018-01-29 19:18:56][DEBUG] : AbeilleParser: type: 8701
> [2018-01-29 19:18:56][DEBUG] : AbeilleParser: (APS Data Confirm Fail)(Not Processed)

 AbeilleMQTTCmd.php.log

> Msg Recieved: Mon, 29 Jan 2018 19:18:38 +0100 Topic: CmdAbeille/Ruche/SetPermit =>	Inclusion
> Type: CmdAbeille
> Address: Ruche
> Action: SetPermit
> Aie aie aie je ne commais pas (encore) cette commande
> getChecksum()
> msgtype: 0049
> length: 0004
> datas: FFFCFE00
> len data: 8

Parser

> -------------- 2018-01-29 19:18:38
> protocolDatas
> message > 12 char
> Type: 8000
> type: 8000
> (Status)(Not processed)
> Length: 5
> Status: 00-(Success)
> SQN: 05
> -------------- 2018-01-29 19:18:45
> protocolDatas
> message > 12 char
> Type: 8048
> (Leave Indication)
> extended addr : 00158d00012678c5
> rejoin status : 00
> -------------- 2018-01-29 19:18:48
> protocolDatas
> message > 12 char
> Type: 004d
> type: 004d(Device announce)(Processed->MQTT)
> Src Addr : 4d01
> IEEE : 00158d00012678c5
> MAC capa : 80
> -------------- 2018-01-29 19:18:48
> protocolDatas
> message > 12 char
> Type: 004d
> type: 004d(Device announce)(Processed->MQTT)
> Src Addr : 4d01
> IEEE : 00158d00012678c5
> MAC capa : 80
> -------------- 2018-01-29 19:18:48
> protocolDatas
> message > 12 char
> Type: 8102
> type: 8102
> [2018-01-29 19:18:48]
> (Attribute Report)(Processed->MQTT)
> SQN: 00
> Src Addr : 4d01
> End Point : 01
> Cluster ID : 0000
> Attr ID : 0005
> Attr Status : 00
> Attr Data Type : 42
> Attr Size : 0012
> Data byte list : 6c756d692e73656e736f725f737769746368
> Data byte: lumi.sensor_switch
> -------------- 2018-01-29 19:18:48
> protocolDatas
> message > 12 char
> Type: 8102
> type: 8102
> [2018-01-29 19:18:48]
> (Attribute Report)(Processed->MQTT)
> SQN: 01
> Src Addr : 4d01
> End Point : 01
> Cluster ID : 0000
> Attr ID : 0001
> Attr Status : 00
> Attr Data Type : 20
> Attr Size : 0001
> Data byte list : 0A
> Data byte: 10
> -------------- 2018-01-29 19:18:48
> protocolDatas
> message > 12 char
> Type: 8701
> (Router Discovery Confirm)(Not processed)
> Status : 00
> Nwk Status : 00
> -------------- 2018-01-29 19:18:56
> protocolDatas
> message > 12 char
> Type: 8702
> type: 8702(APS Data Confirm Fail)(Not processed)
> Status : f0
> Source Endpoint : 01
> Destination Endpoint : 01
> Destination Mode : 02
> Destination Address : 4d01
> SQN: : 01

**Comment by KiwiHC16** [comment]
Ok pour JSON.
Apres avoir joué avec la bouton et mis en semi automatique, peux tu nous partager une capture d'ecran du widget pour voir toutes les commandes (cela sera plus facile a lire et complémentaire aux ors)

**Comment by lukebr91** [comment]
![bouton](https://user-images.githubusercontent.com/35848408/35529085-3a6feb14-0530-11e8-9148-b1c07186a286.png)
Et voilà !

**Comment by KiwiHC16** [comment]
Super merci. Dès qu'on a fait la mise à jour d'edger1er j'inclurai les infos. C'est beau quand ca marche.

**Comment by KiwiHC16** [comment]
Je viens de le mettre dans JSON. As tu une image de ce bouton ?
Je vais publier ce soir.

**Comment by lukebr91** [comment]
ok je testerai ça - comme pour le aqara, à voir comment on peux ramener le multi à 0 ?

https://i2.wp.com/zigate.fr/wp-content/uploads/2017/10/xiaomi_switch.jpg

ou

https://www.google.fr/search?tbs=simg:CAES2AEJal_10bvR2t2QazAELEKjU2AQaBggUCAMICgwLELCMpwgaYgpgCAMSKP8FtQHrBZAStAGxAYoS_1QWwAf4FojbxNqM2wDWmNvA1pTbxJ-Y27ycaMPi5WnTI4aLhhiLDdEuCRvh3zGmWc0UiYKodzrPbMYEW0rRIFIP6pFnyS87Ld7rRgSAEDAsQjq7-CBoKCggIARIEpBVvmwwLEJ3twQkaNgoaCgdjZWlsaW5n2qWI9gMLCgkvbS8wM2dmc3AKGAoGY2lyY2xl2qWI9gMKCggvbS8wMXZrbAw&q=xiaomi+mi+smart+home+wireless+switch&tbm=isch&sa=X&ved=0ahUKEwjdoNrdtYXZAhXK1xQKHVS6AFIQsw4IMw&biw=1920&bih=949

**Comment by KiwiHC16** [comment]
Je viens de faire le push sur la branche master.
Je suis preneur des retours d’experiences.

**Comment by lukebr91** [comment]
Suppression, mise à jour & Intégration OK
![image](https://user-images.githubusercontent.com/35848408/35701514-9216f50c-0796-11e8-9c53-8b3187f652f3.png)

Sauf l'icone dans les paramètres mais ok sur la page du plugin
![image](https://user-images.githubusercontent.com/35848408/35701548-acc31c0a-0796-11e8-94ac-a2aa8a36bb72.png)
![image](https://user-images.githubusercontent.com/35848408/35701603-c9a8842c-0796-11e8-9783-aca8904cb074.png)

et donc envoi de etat = 0 lors de l'appui puis etat =1 au relachement
si clic rapide, l'historique n'affiche pas le 0.

Et donc retour à 0 de l'etat au bout de 2 min, c'est ça? est-ce que l'on peux réduire ce délai?

**Comment by KiwiHC16** [comment]
S'il envoi les messages un a un alors il n y a pas lieux d avoir un retour d état. Je vais l'enlever sur état mais le garder sur multi. Le retour état Jeedom est en minute on ne peut pas aller plus bas.

Ne pas oublier que pour les scenarios il y a aussi la gestion des repetitions:


![capture d ecran 2018-02-01 a 21 57 16](https://user-images.githubusercontent.com/8549674/35703017-02f9a608-079b-11e8-863e-d3f6c5bcd6bf.png)

Je viens de corriger l icon et changer le retour d état dans master.

**Comment by KiwiHC16** [comment]
Et celui ci nous pouvons le fermer aussi ? Switch Rond Version 1

**Comment by KiwiHC16** [comment]
Je le ferme on l'ouvrira de nouveau si besoin.
