### ISSUE TITLE
Time Out Last Communication que faire ?

### ISSUE THREAD

**Issue by jordangidoin** [KiwiHC16/Abeille#344]
Bonjour,

Petite question, j'ai un xiaomi interrupteur simple, qui perds sa communication depuis que je l'ai éloigner de mon raspberry. 

Pourtant quand avant de perde la connexion il fonctionne correctement, notamment parce que j'ai des ampoule qui relais le réseau.

Merci de vos conseils

**Comment by KiwiHC16** [comment]
Bonjour,
Il peut y avoir des soucis de perte d'équipement. Perso j'ai résolu le problème en changeant la couverture radio.
Quel est cet interrupteur simple ?
Quel type d'ampoule ? Sont elles branchées en permanence ?
Avez vous fait un refresh du réseau pour voir si l'interrupteur est vu par au moins un équipement du réseau ?

**Comment by jordangidoin** [comment]
Bonsoir,

comment changer la couverture radio ?

l'interrupteur c'est un celui ci : 
![image](https://user-images.githubusercontent.com/5417643/45382681-4564e080-b609-11e8-8595-d3408803e825.png)
Dans la même pièce il y a des GU10 IKEA et une prise xiaomi

Je viens de ré-associer le bouton et faire un test cela fonctionne pour le moment, mais sans doute demain cela ne fonctionnera plus, et le bouton sera en rouge dans le dashboard.

concernant le refresh réseau je vois le bouton mais uniquement relié à la ruche.
Même après un refresh du cache, a voir demain si cela change, j'ai l'impression que c'est assez long à se re-router différemment

**Comment by KiwiHC16** [comment]
Je remets le mien en service pour tester.
D'après mes notes il se reveille toutes les heures pour intéroger le réseau mais je n'ai pas noté s'il envoyait des infos aussi toutes les heures. Comme c'est le V1 du bouton, il est possible qu'il envoie un messsage qui n'est pas transmis pour l'instant par la zigate et de ce fait Abeille le met en défaut.
A suivre...

**Comment by KiwiHC16** [comment]
Ce bouton remonte toutes les 60minutes sont etat dans le champ FF02. De ce fait il ne doit pas y avoir de TimeOut. Mais pour cela il faut le firmware 3.0.E de la zigate au minimum  qui n'est pas encore dispo.

Si tu appuies sur le bouton est ce que l'icone du widget se met à jour dans le Dasboard Jeedom ?
Si tu appuis, l'etat remonte et le TimeOut est remis à zéro.

**Comment by jordangidoin** [comment]
Merci beaucoup d'avoir pris le temps de regarder.
J'ai changé de bouton et depuis 24H cela semble toujours fonctionne.

Par contre le bouton n'est associé qu'a la ruche, et j'ai pourtant bien rafraichie le cache, mais cela n'a pas d'effet j'ai l'impression (le bouton s'appel btn): 

![image](https://user-images.githubusercontent.com/5417643/45445962-077cc080-b6cc-11e8-8ef3-d4a0a2b84eb8.png)

**Comment by jordangidoin** [comment]
aie... ce matin de nouveau en rouge ...
![image](https://user-images.githubusercontent.com/5417643/45467268-0f198500-b71f-11e8-9ace-d2eac3d0671e.png)

Et je n'arrives pas a le refaire fonctionner, il faut que je le réassocie.
Que puis-je tester ? (je suis développeur, j'ai donc quelques connaissance dans le domaine :) ) 

Merci de ton aide

**Comment by KiwiHC16** [comment]
Est ce que si tu appuis sur le bouton, le symbole etat change ?
Peux tu mettre le plugin en mode debug, vider le log AbeilleParser, appuyer sur le bouton et partager ce qui apparait dans AbeilleParser ?

PS: Pour le graphe il y a des problement de refresh dans le browser, sous Safari les données sont à jour mais le graph ne se rafraichi pas. J'utilise FireFox mais je ne suis pas sure a 100% qu'il se rrafraichisse a chaque fois. On a un cas ouvert sur le sujet.

**Comment by KiwiHC16** [comment]
PS: Il faut appui long de plus de 10s pour voir l icone changer d etat.

**Comment by jordangidoin** [comment]
Ha super, j'ai appuyé longtemps cela a fonctionné.
Le btn n'est plus en rouge.
Il faut donc attendre la nouvelle version du FW pour résoudre ce pb de refresh c'est ca ?.

En tt cas merci de ton aide

**Comment by KiwiHC16** [comment]
Oui c est ça.
