### ISSUE TITLE
Config RPI Docker avec retrait d un USB, ne redemarre pas !!!

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#366]

**Comment by edgd1er** [comment]
bjr, 

ce n'est pas un bug, en cas de retrait de l'usb, le device /usb/ttyUSBn n'est plus disponible. et le container ne peut plus démarrer car le mapping sur le device ttyUSB n'est pas fait. Cela arrive aussi quand tu débranche la clé et la rebranche, tty/USB0 étant vu comme utilisé par l'hote, la clé est définie comme ttyUSB1 au lieu de ttyUSB0 et au prochain démarrage du conteneur ça plante. et sans redémarrage, les demons sont connectés à une clé qui n'existe plus....

La procédure si tu veux retirer la clé (check, inclusion, exclusion, ...), il faut arrêter le conteneur, débrancher la clé, puis plus tard la rebrancher et ensuite redémarrer le conteneur, en ayant vérifier que le mapping sur le tty/USB correspondent au bon device. cela est défini lors du docker run, du docker compose. portainer est conteneur pour gérer les conteneurs (ajout/retrait mem, cpu, volume, device, policy ....).

je suis sur gitter.im, une messagerie liée a github, bien pratique, si tu veux plus d'infos.

**Comment by KiwiHC16** [comment]
Je suis en ligne avec ton explication. Je l'ai classé bug mais comme tu dis ce n'est pas un bug. Il faut que je refasse ma conf. Je vais le reclasser en Help. En c'est un probleme tout ce qu'il y a de plus perso...
Mon problème est que j'ai enlever physiquement un USB sans informer Docker et il n'aime pas.
Je ferai la manip un soir ...

**Comment by KiwiHC16** [comment]
Je ne me souviens plus des détails. Je dois avoir fait un truc comme "docker run --name=jeedomabeille --device=/dev/ttyUSB0 ..." avec la liste des devices. Mais comme j'enleve un, je ne sais pas comment reconfigurer.

Je n'ai jamais joué avec docker-compose car cela ne fonctionnait pas sur mon système.

**Comment by edgd1er** [comment]
si c'est sur RPI (2 ou 3), le site docker propose l'install du paquet via un script en dernière version. ( le Rpi est officiellement supporté) 
https://docs.docker.com/install/linux/docker-ce/debian/#os-requirements

le docker-compose est encore plus simple a installer:
sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

Effectivement, si tu n'as pas un rpi, mais un oodroid ou autre machine exotique, il existe peut etre des paquets non officiels.

**Comment by KiwiHC16** [comment]
Configuration changed. Issue solved.
