### ISSUE TITLE
Log de notice

### ISSUE THREAD

**Issue by xionfr40** [KiwiHC16/Abeille#373]
Hello,

Message de log, sur une fresh install Debian 9, derniere version github de Abeille
`PHP Notice:  Only variables should be passed by reference in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 55`

Cdlt,

Nicolas

**Comment by xionfr40** [comment]
Log de démarrage de AbeilleParser 👍 
```
PHP Warning:  include(../lib/Tools.php): failed to open stream: No such file or directory in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
PHP Warning:  include(): Failed opening '../lib/Tools.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 3
AbeilleParser 2018-09-29 20:12:30[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-09-29 20:12:30[DEBUG]Starting parsing from /tmp/AbeilleDeamonInput to mqtt broker with log level debug on jeedom:jeedom@127.0.0.1:1883 qos=0
AbeilleParser 2018-09-29 20:12:30[DEBUG]Create a MQTT Client
AbeilleParser 2018-09-29 20:12:30[DEBUG]try part
PHP Notice:  Only variables should be passed by reference in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/includes/fifo.php on line 55
```

**Comment by KiwiHC16** [comment]
Salut Nicolas,

Premier post:
Je vais avoir besoin de ton aide car je n'ai pas "PHP Notice: Only variables should be passed by reference in " dans mes logs. Dans quel fichier as tu ce message ?

Deuxième post:
Qu'elle version de Abeille as tu installée ? Depuis le market ? Stable ? Beta ? Github ?

As tu bien défini le port USB de la ZiGate ? As tu les droits dessus ?

Je n'ai pas touché cette partie depuis des mois. Bizarre.

**Comment by xionfr40** [comment]
Hello

en fait je pense que le plugin Abeille n'est pas super compatible avec PHP7 (debian 9 Strech)

j'ai aussi des trucs super pas top:


18-09-30 13:35:03 | Abeille | Erreur sur la fonction deamon_start du plugin : Call to undefined function  () |  
-- | -- | -- | --
  | 2018-09-30 13:33:03 | Abeille | Erreur sur la fonction cron du plugin : Call to undefined function  ()

J'attendrais que tu valides le tout sur Jeedom en Debian 9

a°

**Comment by KiwiHC16** [comment]
Salut, 
Ma machine de dev: PHP Version => 7.0.30-0+deb9u1
root@Abeille:~# cat /etc/issue
Debian GNU/Linux 9 \n \l
Donc ce n'est probablement pas ton problème.

**Comment by KiwiHC16** [comment]
@nherreyre, du nouveau de ton côté ?

**Comment by KiwiHC16** [comment]
Pas de retour. Cloture.
