### ISSUE TITLE
Ajout Bouton Exclusion a côté du bouton inclusion

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#378]

**Comment by KiwiHC16** [comment]
Ajout Bouton Done.

Faire fonction d exclusion d un equipment.

**Comment by KiwiHC16** [comment]
Pour exclure un NE, il faut le désigner (short Address/IEEE). Comment faire ca avec juste un bouton ?
Possibilité dans l objet ruche abeille (Mgt Leave/Remove).
Pour les Xiaomi, le bouton physique provoque le lease. Pour les ampoules rien.

**Comment by KiwiHC16** [comment]
Deplacer dans le mode selection. Faire la commande maintenant.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by tcharp38** [comment]
Tu peux me l'assigner.

**Comment by KiwiHC16** [comment]
#1273

**Comment by KiwiHC16** [comment]
I close this one as duplication with #1273
