### ISSUE TITLE
Colonne dernière comm. vide dans le panneau santé

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#379]
Bonjour,
  Je n'ai plus de valeur dans la colonne dernière communication du panneau santé.
  Une idée?

  Remarque: dans le dashboard principale, la valeur Time-Time est bien à jour, et dynamiquement mise à jour si j'appuie sur un bouton d'un capteur de température xiaomi v2 par exemple.

**Comment by KiwiHC16** [comment]
Petite capture d ecran ?

**Comment by handfreezer** [comment]
Et voilà:
![image](https://user-images.githubusercontent.com/2912752/46436990-9e341e80-c75a-11e8-9e15-76553ab2d192.png)

**Comment by handfreezer** [comment]
et c'est comme ça pour tous mes noeuds

**Comment by KiwiHC16** [comment]
Es tu sur le master maintenant ?

**Comment by handfreezer** [comment]
ya une mise a jour qui vient de tomber, je la passe?

**Comment by KiwiHC16** [comment]
Oui comme ca on est aligné. Les dernieres modifs sont pour un autre sujet.

**Comment by handfreezer** [comment]
done:
![image](https://user-images.githubusercontent.com/2912752/46437660-3088f200-c75c-11e8-81da-7c01672a91c2.png)

**Comment by handfreezer** [comment]
ça bouge pas, il faut attendre un peu peut-être?

**Comment by KiwiHC16** [comment]
Peux tu vider le log AbeilleParser et faire un "Liste Equipement" et partager le log.

**Comment by handfreezer** [comment]
oui, je fais

**Comment by handfreezer** [comment]
```
AbeilleParser 2018-10-03 22:55:40[DEBUG];type: 8000: (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-10-03 22:55:40[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-10-03 22:55:41[DEBUG];type: 8015 (Abeille List)(Processed->MQTT) Payload: 004d6c00158d0001d70822004d0180a400158d0001656e310059024d3500158d0001d6fb03003704bbc200158d0001fd8d740049055cbc00158d0001ab71900043061c3a00158d0001e52a65005d0749b800158d00017140e5005008e88800158d0001e0a37a007b09aefd00158d0001d6cf76005f0A0Fa500158d0001ab711d005d0B40b800158d0001ab711e003d0C249800158d0001d6df5d00590Dcfb800158d0001ab7089008c0E3b0200158d0001a2a94a005a0F395b00158d0001ab712800651023b800158d0001d6e02100b311e97400158d000171f19100cc123ba300158d0001fd8faa005c00
AbeilleParser 2018-10-03 22:55:41[DEBUG]Nombre d'abeilles: 18
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 0; ID : 00; Short Addr : 4d6c; IEEE Addr: 00158d0001d70822; Power Source (0:battery - 1:AC): 00; Link Quality: 77
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 1; ID : 01; Short Addr : 80a4; IEEE Addr: 00158d0001656e31; Power Source (0:battery - 1:AC): 00; Link Quality: 89
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 2; ID : 02; Short Addr : 4d35; IEEE Addr: 00158d0001d6fb03; Power Source (0:battery - 1:AC): 00; Link Quality: 55
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 3; ID : 04; Short Addr : bbc2; IEEE Addr: 00158d0001fd8d74; Power Source (0:battery - 1:AC): 00; Link Quality: 73
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 4; ID : 05; Short Addr : 5cbc; IEEE Addr: 00158d0001ab7190; Power Source (0:battery - 1:AC): 00; Link Quality: 67
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 5; ID : 06; Short Addr : 1c3a; IEEE Addr: 00158d0001e52a65; Power Source (0:battery - 1:AC): 00; Link Quality: 93
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 6; ID : 07; Short Addr : 49b8; IEEE Addr: 00158d00017140e5; Power Source (0:battery - 1:AC): 00; Link Quality: 80
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 7; ID : 08; Short Addr : e888; IEEE Addr: 00158d0001e0a37a; Power Source (0:battery - 1:AC): 00; Link Quality: 123
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 8; ID : 09; Short Addr : aefd; IEEE Addr: 00158d0001d6cf76; Power Source (0:battery - 1:AC): 00; Link Quality: 95
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 9; ID : 0A; Short Addr : 0Fa5; IEEE Addr: 00158d0001ab711d; Power Source (0:battery - 1:AC): 00; Link Quality: 93
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 10; ID : 0B; Short Addr : 40b8; IEEE Addr: 00158d0001ab711e; Power Source (0:battery - 1:AC): 00; Link Quality: 61
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 11; ID : 0C; Short Addr : 2498; IEEE Addr: 00158d0001d6df5d; Power Source (0:battery - 1:AC): 00; Link Quality: 89
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 12; ID : 0D; Short Addr : cfb8; IEEE Addr: 00158d0001ab7089; Power Source (0:battery - 1:AC): 00; Link Quality: 140
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 13; ID : 0E; Short Addr : 3b02; IEEE Addr: 00158d0001a2a94a; Power Source (0:battery - 1:AC): 00; Link Quality: 90
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 14; ID : 0F; Short Addr : 395b; IEEE Addr: 00158d0001ab7128; Power Source (0:battery - 1:AC): 00; Link Quality: 101
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 15; ID : 10; Short Addr : 23b8; IEEE Addr: 00158d0001d6e021; Power Source (0:battery - 1:AC): 00; Link Quality: 179
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 16; ID : 11; Short Addr : e974; IEEE Addr: 00158d000171f191; Power Source (0:battery - 1:AC): 00; Link Quality: 204
AbeilleParser 2018-10-03 22:55:41[DEBUG]Abeille i: 17; ID : 12; Short Addr : 3ba3; IEEE Addr: 00158d0001fd8faa; Power Source (0:battery - 1:AC): 00; Link Quality: 92
AbeilleParser 2018-10-03 22:56:02[DEBUG];type: 8000: (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-10-03 22:56:02[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-10-03 22:56:03[DEBUG];type: 8010 (Version)(Processed->MQTT); Application : 1; SDK : 781
AbeilleParser 2018-10-03 22:56:03[DEBUG]Application: 0001 qos:0
AbeilleParser 2018-10-03 22:56:03[DEBUG]SDK: 030D qos:0
AbeilleParser 2018-10-03 22:56:03[DEBUG];type: 8000: (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2018-10-03 22:56:03[DEBUG]SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2018-10-03 22:56:03[DEBUG];type: 8009: (Network State response)(Processed->MQTT)
AbeilleParser 2018-10-03 22:56:03[DEBUG]ZiGate Short Address: 0000
AbeilleParser 2018-10-03 22:56:03[DEBUG]IEEE Address: 00158d0001b6997b
AbeilleParser 2018-10-03 22:56:03[DEBUG]PAN ID: f572
AbeilleParser 2018-10-03 22:56:03[DEBUG]Ext_PAN_ID: c4cecb4fe539c37b
AbeilleParser 2018-10-03 22:56:03[DEBUG]Channel: 15
AbeilleParser 2018-10-03 22:56:03[DEBUG]Level: 0x00
```

**Comment by KiwiHC16** [comment]
Si je prends la 4d35, dans la capture au debut, elle apparait dans le log. C'est un bon début.
Après il faut que je re-regardes comment ca fonctionne en détail, je ne me souviens plus.
Probablement demain...

**Comment by handfreezer** [comment]
ok, pas de souci (note jusqte que dans mon panneau santé, j'ai réduit la capture d'écrann, mais j'ai tout le monde de la liste, et hormis la ruche, toute la colonne est avec un --

**Comment by handfreezer** [comment]
Malheureusement pour moi dernier message:
![image](https://user-images.githubusercontent.com/2912752/46441903-3e447480-c768-11e8-8234-a1786d642a0c.png)

**Comment by KiwiHC16** [comment]
Peux tu faire la manipulation suivante:
1) Vide le log Abeille.
2) Lance le "cron plugin"
Clic sur fleche verte:
![capture d ecran 2018-10-04 a 10 05 30](https://user-images.githubusercontent.com/8549674/46460708-103d4f80-c7bd-11e8-9b7f-9b7a9e2cb528.png)
dans le menu "Moteur de taches".
3) partage le log entre les lignes:
`[2018-10-02 20:21:59][DEBUG] : ----------- Starting cron -----`
`[2018-10-02 20:21:59][DEBUG] : Ending cron --------------`

**Comment by handfreezer** [comment]
Et voilà:

```
[2018-10-04 22:52:07][DEBUG] : ----------- Starting cron ------------------------------------------------------------------------------------------------------------------------
[2018-10-04 22:52:07][DEBUG] : ----------- Ping Zigate to check Online status
[2018-10-04 22:52:07][DEBUG] : Envoi du message Version vers CmdAbeille/Ruche/getVersion
[2018-10-04 22:52:07][DEBUG] : Envoi du message getNetworkStatus vers CmdAbeille/Ruche/getNetworkStatus
[2018-10-04 22:52:07][DEBUG] : ----------- Refresh health information
[2018-10-04 22:52:07][DEBUG] : --
[2018-10-04 22:52:07][DEBUG] : Name: Ruche Last: 1538686323 Timeout: 60s - Last+TimeOut: 1538686383 now: 1538686327 Delta: -56
[2018-10-04 22:52:07][DEBUG] : Name: Ruche lastCommunication: 2018-10-04 22:52:03 timeout value: 60 timeout status: 0 state: ok
[2018-10-04 22:52:07][DEBUG] : Inclusion Status est a 00 donc on ne demande pas de rafraichir l info.
[2018-10-04 22:52:07][DEBUG] : Ending cron ------------------------------------------------------------------------------------------------------------------------
```

**Comment by KiwiHC16** [comment]
Très bizarre, tu n'as que la ruche qui est testée.
Dans le code, je regarde s'il y a une valeur de timeout. Si il y a une valeur je fais les tests sinon je mets state à '-'.

Le timeout est le paramètre "principal" entre configuration et category (voir l image au dessus, au milieu). Ce n'est pas celui qui est dans status (voir l image au dessus, en bas).

Peux tu configurer le time out, Exemple:
![capture d ecran 2018-10-05 a 10 04 13](https://user-images.githubusercontent.com/8549674/46523455-0c293480-c886-11e8-9adf-dde166e818b0.png)

**Comment by handfreezer** [comment]
Dans 3 jours. ...
-- 
Envoyé de mon gsm Android 


-------- Courriel d’origine --------
De : Ben <notifications@github.com>
Envoyé : 5 octobre 2018 10:06:55 GMT+02:00
À : KiwiHC16/Abeille <Abeille@noreply.github.com>
Cc : Handfreezer <github@ulukai.net>, Author <author@noreply.github.com>
Objet : Re: [KiwiHC16/Abeille] Colonne dernière comm. vide dans le panneau santé (#379)

Très bizarre, tu n'as que la ruche qui est testée.
Dans le code, je regarde s'il y a une valeur de timeout. Si il y a une valeur je fais les tests sinon je mets state à '-'.

Le timeout est le paramètre "principal" entre configuration et category (voir l image au dessus, au milieu). Ce n'est pas celui qui est dans status (voir l image au dessus, en bas).

Peux tu configurer le time out, Exemple:
![capture d ecran 2018-10-05 a 10 04 13](https://user-images.githubusercontent.com/8549674/46523455-0c293480-c886-11e8-9adf-dde166e818b0.png)

**Comment by edgd1er** [comment]
bjr, 

je confirme que  j'ai le "problème" aussi avec la version du "jour" (2018.10.06) :)
seuls deux eléments ont une date, la ruche et un interrupteur carré sur pile.

**Comment by KiwiHC16** [comment]
Ceux qui n'ont pas de date, ont ils un TimeOut de défini dans leur configuration ?

**Comment by edgd1er** [comment]
oui, c ça, si aucun timeout n'est défini (null), alors '-' est affiché.
```
if ($eqLogic->getStatus('state') == '-') { $lastComm = '<span class="label label-info" style="font-size : 1em; cursor : default;">-</span>'; }
```
Le correctif ne serait il pas de supprimer les tests d'etat pour l'affichage de lastCom et depuis ? c'est une info valable meme si on n'indique pas de timeout. D'ailleurs 

 Abeille/desktop/modal/health.php => L68, L73 
 
ps: gitter.im est sympa pour échanger en direct :)

getConfiguration("xx") va chercher la valeur de l'attribut "xx" du champ configuration dans la bdd, mais le champs getStatus('lastCommunication') que va t il chercher sachant que tout les champs status ont la valeur "nul" ?

Peux tu me confirmer qu'il existe des attributs volatiles ( ie non sauvegardé en bdd) comme lastCommunication ?

**Comment by edgd1er** [comment]
effectivement dans le cas ou il n'y a pas de valeurs, le code actuel peut constuire un tableau etrange.

J'ai l'impression que le code ci dessous ne fonctionne pas comme attendu
les equipements sans timer ont un état défini normalement mais ce n'est pas le cas.
As tu la meme lecture que moi ?

Abeille.class L2047
```
if ($eqLogic->getConfiguration("lastCommunicationTimeOut")) {
                        $lastCommunicationTimeOut = $eqLogic->getConfiguration("lastCommunicationTimeOut");
                        if ($lastCommunicationTimeOut != -1) {
                            if (strtotime($eqLogic->getStatus('lastCommunication')) + $lastCommunicationTimeOut > time(
                                )) {
                                // Ok
                                $eqLogic->setStatus('state', 'ok');
                            } else {
                                // NOK
                                $eqLogic->setStatus('state', 'Time Out Last Communication');
                            }
                        } else {
                            $eqLogic->setStatus('state', '-');
                        }
                    } // Si pas de Timer specifique, 24h et 7jours comme seuil d'alerte
                    else {
                        $last = strtotime($eqLogic->getStatus('lastCommunication'));
                        if ($last > time() - $lastCommunicationTimeOut) {
                            // Ok
                            $eqLogic->setStatus('state', 'ok');
                        } elseif ($last < time() - $lastCommunicationTimeOut * 7) {
                            // NOK 7d
                            $eqLogic->setStatus('state', 'Very Old Last Communication (>7days)');
                        } else {
                            // NOK 24h
                            $eqLogic->setStatus('state', 'Old Last Communication (>24h)');
                        }
```

**Comment by KiwiHC16** [comment]
Es tu avec le dernier master, car dans les premieres version j'avais fait un truc compliqué avec un timeout de 24h et d'une semaine. 
J'ai enlevé car une vrai prise de tête pour aucun avantage.

La dernière version ne doit prendre que le timeout de l objet (valeur ou null)

**Comment by edgd1er** [comment]
oui, je fait des rebase chaque jour.

**Comment by KiwiHC16** [comment]
Un vieux bout de code qui doit rester alors, je vais regarder pour l'enlever.

**Comment by KiwiHC16** [comment]
Dans Abeille.class.php, à partir de la ligne 1940, c'est des tests pour lancer Abeille.class.php directement en ligne de commande pour faire des tests avant de le mettre dans jeedom. par exemple:
php Abeille.class.php 2
va lancer le test 2.

Ici le test 4, qui correspond aux coms n'est pas à jour. Je l'enlève car cela ne sert plus.

**Comment by edgd1er** [comment]
je n'ai trouvé que le lastCommunicationTimeOut dans un sensor_ht, un timer et deux trucs tradfri et un RWL

Le calcul de l'etat n'intervient que pour ces 5 la, pour tous les autres ce sera '-'
est ce bien cela que tu voulais ? a un moment, j'avais cru comprendre que les devices n'ayant pas communiqué depuis plus d'une heure levaient une alerte, ce n'est plus le cas ?

**Comment by KiwiHC16** [comment]
Le code est dans le cron (toutes les secondes) a partir de la ligne 241.
L'idée est:
- si pas de timeout defini dans l objet alors pas d'alarme et status '-'
- si un timeout on regarde now-lastcom > time alors alarme

**Comment by KiwiHC16** [comment]
@handfreezer , qu'elle la situation pour toi ? As tu toujours le probleme ?

**Comment by KiwiHC16** [comment]
Je clos. Si besoin on ouvrira une autre issue.
