### ISSUE TITLE
update manuel de remplacement de sensor

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#380]
Bonjour,

   J'ai fait manuellement le changement de short address d'un sensor car il n'a pas été vu automatiquement et je ne sais pas pourquoi... mais la suite risque de vous eclaircir: après le changement manuel, l'écran de description du sensor affiche bien Abeille/5cbc qui est la nouvelle adresse courte, mais dans l'onglet commande, le test de la commande short address continue de me donner 1adc et l'IEEE long est 00000000000000...

une idée?

**Comment by KiwiHC16** [comment]
![capture d ecran 2018-10-03 a 22 20 53](https://user-images.githubusercontent.com/8549674/46436993-a0967880-c75a-11e8-9186-e26c2b9ab2f1.png)

Que donne logicalId ?

**Comment by handfreezer** [comment]
j'ai eu une popup, mais en allant dans l'écran de commande du noeud, le test de la short adress donne toujours l'ancienne adresse, et l'IEEE reste avec que des 0s

**Comment by KiwiHC16** [comment]
Lance un recalcul du cache, pour voir (ca peut petre un peu long):
![capture d ecran 2018-10-03 a 22 28 53](https://user-images.githubusercontent.com/8549674/46437490-c7a17a00-c75b-11e8-95ec-d2ee27d82bb9.png)

**Comment by handfreezer** [comment]
quand je l'ai fait, la liste n'a pas bougé alors que j'ai eu le bandeau succès de fin. j'attends la fin de l'upadte, et je le passe

**Comment by handfreezer** [comment]
je viens de le faire, la liste est mise à jour, j'ai eu la popup, mais j'ai toujours le mauvais resultat sur la commande test de short adress

**Comment by KiwiHC16** [comment]
Que donne test sur IEEE ? (Je ne suis pas sure pour Short Address).

**Comment by handfreezer** [comment]
![image](https://user-images.githubusercontent.com/2912752/46439025-bfe3d480-c75f-11e8-91ae-01e2e0c50cfd.png)

**Comment by KiwiHC16** [comment]
Les cas #379 et #380 sont biens sur la même machine ?

**Comment by handfreezer** [comment]
oui, même machine, même instance de jeedom, même clé zigate, même ensemble de capteurs

**Comment by KiwiHC16** [comment]
Et les autres informations (temperature,...) remontent bien ?

**Comment by handfreezer** [comment]
oui (temp, hum, pression et time-time dans le widget du dashboard).
C'est comme si l'ID de distribution des messages est bon, mais la short address n'a pas été mise à jour et donc l'update de l'IEEE marche pas (l'ID jeedom et le champ short adress ne serait pas le même en interne)

**Comment by KiwiHC16** [comment]
la commande short address n'est pas utilisée. Elle est la que pour récupérer la short address qui remonte et à des besoins futures éventuels (que je ne connais pas). Ou pour  l utilisateur pour faire des scenario et tester cette adresse. Mais Abeille ne l'utilise pas pour la gestion interne.

**Comment by handfreezer** [comment]
zut, du coup, cela n'explique pas l'absence d'update de IEEE.

Dernier message pour moi ce soir.

**Comment by KiwiHC16** [comment]
Focalisons nous sur la mise a jour de l'IEEE pour la '5cbc'. Je viens de regarder le code et la commande doit se mettre à jour sur un "Liste Equipements" (A condition que l'info soit dans la zigate).
Pour verifier, vider le log Abeille, faire un 'Liste Equipement' et partager le log.
Il doit y avoir des message comme:
`[2018-10-02 20:11:10][DEBUG] : Topic: ->Abeille/13c0/IEEE-Addr<- Value ->00158d0001b922fd<-
[2018-10-02 20:11:10][DEBUG] : Ok pas de changement de l adresse IEEE`

**Comment by handfreezer** [comment]
Parmis tout le log, je t'envoie ce qui me semble t'intéresser pour pas noyer le sujet, mais je peux tout mettre si besoin:

```
[2018-10-04 22:49:14][DEBUG] : Topic: ->Abeille/5cbc/IEEE-Addr<- Value ->00158d0001ab7190<-
[2018-10-04 22:49:14][DEBUG] : Alerte changement de l adresse IEEE pour un equipement !!! 5cbc: 0000000000000000 => 00158d0001ab7190
[2018-10-04 22:49:14][DEBUG] : IEEE est null, je ne l utilise pas.
```

**Comment by KiwiHC16** [comment]
J'ai du me prendre les pieds dans le tapis avec les if then else.
Je viens de pousser une modification.
Tests et dis moi.

**Comment by handfreezer** [comment]
Dans 3 jours aussi....
-- 
Envoyé de mon gsm Android 


-------- Courriel d’origine --------
De : Ben <notifications@github.com>
Envoyé : 5 octobre 2018 09:56:05 GMT+02:00
À : KiwiHC16/Abeille <Abeille@noreply.github.com>
Cc : Handfreezer <github@ulukai.net>, Author <author@noreply.github.com>
Objet : Re: [KiwiHC16/Abeille] update manuel de remplacement de sensor (#380)

J'ai du me prendre les pieds dans le tapis avec les if then else.
Je viens de pousser une modification.
Tests et dis moi.

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by KiwiHC16** [comment]
So je clos. On r-ouvrira si besoin.
