### ISSUE TITLE
Cron: il manque l'init de la variable

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#394]
https://github.com/KiwiHC16/Abeille/blob/836d9f25870afed49ad055dcefdd4abfd94e127c/core/class/Abeille.class.php#L159

parameters_info n'est pas global, il faut ajouter en L158
```
 $parameters_info = self::getParameters();
```

**Comment by KiwiHC16** [comment]
Est ce que la correction est dans le pull request que tu as fait aujourd'hui ?
Si oui je suppose qu on peut clore cette issue.

**Comment by edgd1er** [comment]
oui, c'est bien cela. l'issue peut etre fermée :)
