### ISSUE TITLE
Network Graph: pb dans la gestion de non disponibilité des fichiers json

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#401]
Lorsque les fichiers AbeilleLQI_MapData.json.lock et AbeilleLQI_MapData.json ne sont pas accessibles (manquants, droits insuffisants, ..) , la gestion d'erreur n'est pas adéquate.
on a le message "action réalisée avec succés, alors que le traitement a échoué.

reproduction:
- dans le rep network, faire un chattr -i AbeilleLQI_MapData.json*
- relancer un recalcul du cache, on a un message d'erreur, non visible et un dernier message "action réalisée avec succès"

**Comment by KiwiHC16** [comment]
I'm closing do to the pull of today

**Comment by KiwiHC16** [comment]
La progression lors de la collect des infos ne s'affiche plus.
Donc je rouvre la cas.

**Comment by KiwiHC16** [comment]
La progression est ok avec la derniere correction.
