### ISSUE TITLE
integrer living-Colors bloom

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#425]
https://www.philips.fr/c-p/7099730PH/livingcolors-lampe-a-poser

**Comment by KiwiHC16** [comment]
Pour commencer il faudrait son nom ZigBee. Peux tu mettre en log le plugin et faire un getName sur l ampoule ? (Mettre le plug in en mode semi automatique). 
Recuperes l adresse courte dans les logs lors de l appairage.
Dans la ruche pour la commande getName mets:
adresse courte
0B

Partages les infos.

**Comment by KiwiHC16** [comment]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=659045&hilit=living+Colors+bloom#p659045

**Comment by KiwiHC16** [comment]
Pas de nouvelle alors je clos.

**Comment by McFlyPartages** [comment]
salut,

Je reviens sur le sujet.
pour faire le get name il faut que je trouve d'abord l'adresse de la telecommande ou lampe ?

Je pense que c'est f050 car dans graph dev f050 = hue et je n'ai pas de hue.

Ais je bien compris.

Par contre quand je fais un f050 puis get Name je n'ai rien dans les logs.

Je suis bien en semi automatique.

Dans quel log je dois voir ca ?

Merci d'avance

**Comment by McFlyPartages** [comment]
Après plusieurs essais il semblerait que la version que j'ai (Référence 7099760PH et non 7299760p) ne soit pas zigbee mais plutôt wifi et peut être réglable via un pont Hue en entrant le numéro de série complet.

Je vais commander un pont hue sur Amazon et voir si cela marche car plusieurs commentaire mentionne que cela marche via le pont HUE.

Je te retiens au courant.

**Comment by McFlyPartages** [comment]
Pour infos et trace

https://github.com/Koenkk/zigbee-shepherd-converters/pull/79
https://github.com/Koenkk/zigbee2mqtt/issues/328

**Comment by McFlyPartages** [comment]
Merci d'avoir réouvert l' issue.

Donc je te confirme que je peux les associer via le pont Phillips hue

**Comment by KiwiHC16** [comment]
Référence 7099760PH
https://www.philips.co.uk/c-p/7299760PH/hue-white-and-color-ambiance-bloom-table-lamp/specifications
ZigBee Light Link = Yes
https://www2.meethue.com/en-us/p/hue-bloom/729976049#specifications
ZigBee Light Link = Yes

Donc si c'est cette référence et qu'elle fonctionne sur le pont Hue alors elle est bien Zigbee et devrait fonctionner avec la Zigate.

**Comment by KiwiHC16** [comment]
Mets le plug in en debug. 

Vide le log AbeilleParser:
![Capture d’écran 2019-06-18 à 09 16 16](https://user-images.githubusercontent.com/8549674/59660814-bbeeca00-91a9-11e9-8fb3-f7d8363fdbd2.png)

Redemarre le demon.

Tu fais l'inclusion pour avoir l ampoule dans le reseau zigbee (si pas deja fait).

Pour faire le "getName", tu rends l objet Ruche visible:
![Capture d’écran 2019-06-18 à 09 09 09](https://user-images.githubusercontent.com/8549674/59660412-bc3a9580-91a8-11e9-9bec-32eae667b903.png)

Ensuite tu fais le "get name" depuis la ruche.


![Capture d’écran 2019-06-18 à 09 14 08](https://user-images.githubusercontent.com/8549674/59660682-76320180-91a9-11e9-8799-52661315a661.png)

Et tu partages le log AbeilleParser

**Comment by McFlyPartages** [comment]
Ok je fais ça se soir en rentrant merci

**Comment by McFlyPartages** [comment]
Alors voici le get Name sur le '06eb'

```
AbeilleParser 2019-06-18 15:35:00[debug]Message pulled from queue : "800000054e00ca010000"

AbeilleParser 2019-06-18 15:35:00[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}
```

**Comment by McFlyPartages** [comment]
et en bidoullant un peu sur la lampe j'ai ca 

```
AbeilleParser 2019-06-18 15:39:42[debug]Message pulled from queue : "800000054f00cb010000"

AbeilleParser 2019-06-18 15:39:42[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}

AbeilleParser 2019-06-18 15:40:25[debug]Message pulled from queue : "80000005950000001000"

AbeilleParser 2019-06-18 15:40:25[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}

AbeilleParser 2019-06-18 15:40:25[debug]Message pulled from queue : "801000059b0002030F00"

AbeilleParser 2019-06-18 15:40:25[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/SW-Application","payload":"0002"}}

AbeilleParser 2019-06-18 15:40:25[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/SW-SDK","payload":"030F"}}

AbeilleParser 2019-06-18 15:40:29[debug]Message pulled from queue : "800000058c0000000900"

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}

AbeilleParser 2019-06-18 15:40:29[debug]Message pulled from queue : "800900160D000000158d0001ecbbd5df04cadf8f755ec2c3e90B00"

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Short-Addr","payload":"0000"}}

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/IEEE-Addr","payload":"00158d0001ecbbd5"}}

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/PAN-ID","payload":"df04"}}

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Ext_PAN-ID","payload":"cadf8f755ec2c3e9"}}

AbeilleParser 2019-06-18 15:40:29[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Network-Channel","payload":11}}

AbeilleParser 2019-06-18 15:41:23[debug]Message pulled from queue : "80000005950000001000"

AbeilleParser 2019-06-18 15:41:23[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}

AbeilleParser 2019-06-18 15:41:23[debug]Message pulled from queue : "801000059b0002030F00"

AbeilleParser 2019-06-18 15:41:23[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/SW-Application","payload":"0002"}}

AbeilleParser 2019-06-18 15:41:23[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/SW-SDK","payload":"030F"}}

AbeilleParser 2019-06-18 15:41:27[debug]Message pulled from queue : "800000058c0000000900
"
AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Zigate-8000","payload":"00-(Success)"}}

AbeilleParser 2019-06-18 15:41:27[debug]Message pulled from queue : "800900160D000000158d0001ecbbd5df04cadf8f755ec2c3e90B00"

AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Short-Addr","payload":"0000"}}

AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/IEEE-Addr","payload":"00158d0001ecbbd5"}}

AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/PAN-ID","payload":"df04"}}

AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Ext_PAN-ID","payload":"cadf8f755ec2c3e9"}}

AbeilleParser 2019-06-18 15:41:27[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/Ruche\/Network-Channel","payload":11}}
```

**Comment by McFlyPartages** [comment]
![image](https://user-images.githubusercontent.com/44530252/59689434-ef4c4b80-91df-11e9-8604-17275781509c.png)

**Comment by KiwiHC16** [comment]
L'info n'est pas dans les traces. Je viens de faire un test sur mon système et en fait suite aux changements récents, le contenu des traces a aussi changé donc on n'a pas l'info. Il faut que je regarde pourquoi et que je change probablement le code.

**Comment by McFlyPartages** [comment]
Ok je ne sais pas si tu as reçu la réponse a cette issu via la réponse par mail.
Je la remets ici j'ai un  petit moi avant de renvoyer le pont Hue donc si tu as besoin de quoique se soit n’hésite pas

**Comment by KiwiHC16** [comment]
J'ai un pont hue mais je n'ai jamais réussi a en sortir quoi que ce soit...

**Comment by KiwiHC16** [comment]
```
[2019-06-17 15:51:36][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 04; Src Addr : dc8d; End Point : 0C; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0009; Data byte list : ->GL-S-003Z<-
```
Je viens de faire un test avec une ampoule GledOpto et j'ai un message comme celui ci dessus. Il faudrait qu'on ai le meme type de message.

Si tu partages ton ecran avec any desk(.com), je pourrai faire le test directement. Il me faudrait jeedom et 2 ssh ouverts quand je me connecte. Si ok pour toi envoies par MP (Forum Jeedom) le code d accès.

**Comment by McFlyPartages** [comment]
Apres recherche pas de moyen de reset la lampe sauf via application Hue.

Est ce que cela vaut le coup que j'investisse dans une telecommande Hue ?

Sinon je pense que c'est un Ziigbee prprietaire qui est geré par le pont Hue mais pas un vrai Zigbee.

Je mets les liens
http://play.with.free.fr/index.php/les-solutions-zigbee-light-link-de-philips-hue-livingwhites-et-livingcolors/#Les_dispositifs_LivingColors

https://www.multiroom.fr/lampes-philips-smartlink-livingcolors-compatible-philips-hue-zigbee-light-link/

**Comment by McFlyPartages** [comment]
Donc pour la faire reconnaître par la zigate depuis le pont Hue.
Il faut associer la lampe au pont Hue via le numéro de séries.
Une fois associée faire la ,mpise a jour si il y a. (moi j'ai eu)
Mettre la Zigate en inclusion.
puis la supprimer du pont hue et après affaiblissement de la lumière elle seras reconnue par la zigate.

Un grand pas deja

**Comment by McFlyPartages** [comment]
Le resultat du parser pour la commande Get Name 0B
`AbeilleParser 2019-06-26 14:35:20[debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 36; Src Addr : e897; End Point : 0B; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0006; Data byte list : ->LLC011<-`

**Comment by KiwiHC16** [comment]
Modele fait sur la base de la Hue Go.

**Comment by KiwiHC16** [comment]
Le modele est dans le master. Peux tu tester ? (Sais tu mettre le master sur ta machine ?)

- master sur la machine
- restart demon
- inclusion de l ampoule
- test de l ampoule qui devrait apparaitre dans Jeedom.

**Comment by McFlyPartages** [comment]
Salut,

Un grand merci pour ça car cela marche toutes les commandes marches, j'ai installe le master via nextdom et nickel.

Un nouveau model supporte maintenant via ton très bon plugins.

Si tu as besoin de bidouiller pour voir d'autres chose n’hésite pas.

Je vais essayer l’intégration via la télécommande Hue et te tiens au courant avant de renvoyer le pont Hue.

Encore merci
