### ISSUE TITLE
Systeme de Guims78: un bouton

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#431]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=660283#p660283

**Comment by KiwiHC16** [comment]
D'abord, résoudre les problèmes de CRC:

AbeilleParser 2018-10-29 05:55:03[DEBUG];CRC is not as expected (26) is 9a 
AbeilleParser 2018-10-29 05:55:24[DEBUG];CRC is not as expected (145) is 10 
AbeilleParser 2018-10-29 05:55:25[DEBUG];CRC is not as expected (227) is 63 

Comment est connectée la zigate au systeme ?

**Comment by KiwiHC16** [comment]
@Guims78 ou en es tu de ce sujet ?

**Comment by guims78** [comment]
J'ai laissé tombé pour l'instant. 
Mes capteur de T° fonctionnent. 
Je dois faire la mise à jour du FW de la zigate + inclusion de tous les capteurs. 
Je referais l'essai de l'inter à cette occasion. 


⁣Envoyé par TypeApp ​

Le 7 déc. 2018 à 16:40, à 16:40, Ben <notifications@github.com> a écrit:
