### ISSUE TITLE
Remontée consommation: Xiaomi Prise

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#433]

**Comment by rvitch** [comment]
Log parser pour de la prise : Abeille/e052
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2545670/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Salut,
Je ne reconnais pas ce log. Sur qu'elle version d'Abeille es tu ? Comment as tu installé Abeille ?

**Comment by rvitch** [comment]
Salut ben,

j'ai installé abeille de la facon la plus simple qu'il soit, via plugin jeedom.
Au début en version stable et depuis 3 jours je suis sur la master via alternativemarket .
Les logs sont en niveau debug et tu m'a demandé le log abeilleparser .

**Comment by KiwiHC16** [comment]
C'est quoi alternativemarket ?

**Comment by rvitch** [comment]
Le plugin du market alternatif de jeedom (nommé aussi nextdom), en bref  pour la branche master de abeille c'est ton github.

**Comment by rvitch** [comment]
version du plugin : d1fae393e582212ab6596c5678a8d8aebeb928c5

**Comment by KiwiHC16** [comment]
nextdom: je ne sais pas ce qu'ils font et comment cela fonctionne.

Je ne comprends pas le contenu du fichier.

Peux tu vérifier que c est bien le contenu du fichier /var/www/html/log/AbeilleParser ?

Le log doit avoir une contenu comme:

> AbeilleParser 2018-11-04 18:46:03[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
> AbeilleParser 2018-11-04 18:46:03[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2018-11-04 18:46:04[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
> AbeilleParser 2018-11-04 18:46:04[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2018-11-04 18:46:05[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 0E
> AbeilleParser 2018-11-04 18:46:05[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.

Alors que dans le tien on voit: 

> 2018-10-31 14:45:16][DEBUG] : Mosquitto: Log level: 16 Message: Client AbeilleParser sending PUBLISH (d0, q0, r0, m2709, 'Abeille/c615/Link-Quality', ... (2 bytes))
> [2018-10-31 14:45:16][DEBUG] : Mosquitto: Log level: 16 Message: Client AbeilleParser sending PUBLISH (d0, q0, r0, m2710, 'Abeille/c615/Time-TimeStamp', ... (10 bytes))
> [2018-10-31 14:45:16][DEBUG] : Mosquitto: Log level: 16 Message: Client AbeilleParser sending PUBLISH (d0, q0, r0, m2711, 'Abeille/c615/Time-Time', ... (19 bytes))

**Comment by KiwiHC16** [comment]
En ssh si tu fais:
cd /var/www/html/plugins/Abeille/
suivi d un 
git show
ca donne quoi ?

**Comment by rvitch** [comment]
Resultat git show
Ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
Mais je suis sur d'etre sur la version que tu as publié y'a 3 ou 4 jours, j'ai eu l'update apres que tu ai envoyé la tienne.

**Comment by rvitch** [comment]
![image](https://user-images.githubusercontent.com/20045551/47968136-c9fe3900-e065-11e8-9790-44e39a7b0758.png)

**Comment by rvitch** [comment]
Alors j'ai peu etre trouvé une coquille, j'avais les sources de mika d'activé aussi.
Je viens de les desactiver et je réinstalle.
Je vois apres.

**Comment by KiwiHC16** [comment]
Il faut qu on résolve ça sinon on ne pourra pas avancer sur ton sujet. Quand je serai devant ma machine je t enverrai des captures d’écran de la conf des logs pour voir si nous sommes bien en ligne sur ce point.

**Comment by rvitch** [comment]
Ok, fais moi signe qu'on essaye de se caler.
Je ferai ce que je peux pour me libérer.

**Comment by KiwiHC16** [comment]
Dans la conf Jeedom log as tu bien:
![capture d ecran 2018-11-04 a 20 46 21](https://user-images.githubusercontent.com/8549674/47969102-f076a100-e072-11e8-9050-6cd592b36a2b.png)
et
![capture d ecran 2018-11-04 a 20 46 28](https://user-images.githubusercontent.com/8549674/47969104-f8cedc00-e072-11e8-9470-450335e4e0dd.png)

Et dans le plugin Abeille:
![capture d ecran 2018-11-04 a 20 46 55](https://user-images.githubusercontent.com/8549674/47969105-01bfad80-e073-11e8-8414-a093ae9ff327.png)

**Comment by rvitch** [comment]
Voici le log 
Adresse de la prise : dc9e

[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2547402/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Qu'est ce que tu as changé pour que le log soit "correct" maintenant ?

Bon il y a une différence, le champ propriétaire qui remonte à une taille de 0x002b alors que chez moi il a une taille 0x0031. Ce qui explique que l'info 'conso' ne remonte pas.

Reste a trouver pourquoi et voir si on peut décoder cette info.

Est ce bien une prise de ce type: https://static-pepper.dealabs.com/threads/thread_full_screen/default/1093266_1.jpg

**Comment by rvitch** [comment]
Salut ben

Je pense que la principale modification c'est le niveau de log global, qui
était en débug chez moi et donc trop bavard..
N'hésite pas si je peux t'aider encore sur ce trouble shoot.

**Comment by KiwiHC16** [comment]
Src Addr : dc9e; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0009; Data byte list : ->lumi.plug<-

**Comment by KiwiHC16** [comment]
Il faut qu'on fasse du reverse engineering. Il faudrait que tu fasses la manipulation suivante:

Tu trouves une charge (un ampoule par example). Tu la branche sur la prise et tu notes sa puissance en W.

Tu vides le log, tu allumes la prise et tu attends 2 heures pour qu'on ai assez de log, tu partages le log et on essayera de trouver l info dans le champ propriétaire.

**Comment by rvitch** [comment]
Le log que je t'ai fait passer et celui de la prise de mon poêle a granulés.
J'en connais les valeurs de consommation instantanée.
Je sais aussi sur quelle plage de cumul on doit etre, y'a 3 jours Xiaomi
Home me donné un cumul de 3990 kW donc on doit être aux alentours de 4000kw
.

**Comment by KiwiHC16** [comment]
Est ce que ton poêle consomme environ 50W ?
0x8fc23c42 -> 47.19 (W?)

**Comment by KiwiHC16** [comment]
La prise me donne 179kWh.
Je viens de pousser une modif dans le master. Install et dis moi.

**Comment by rvitch** [comment]
Mise à jour faite, l'info remonte .
Bon boulot :-)
Je pense que tu peux basculer l'issue en close.

**Comment by KiwiHC16** [comment]
Ok,
Peux tu me donner le numero sur la prise ?
Moi j ai ZNCZ02LM

**Comment by KiwiHC16** [comment]
Oui une reference produit

**Comment by rvitch** [comment]
Salut ben,

Et bien figure toi que c'est bien le même modèle.
ZNCZ02LM

**Comment by KiwiHC16** [comment]
Ce n'est pas une bonne nouvelle. Deux même produit ne se comportent pas de la même façon.
Je clos cette issue et on verra a aller plus loin si le cas se représente. Mais d autres sujets avant dans la liste.
