### ISSUE TITLE
Gestion chaleur OSRAM GU10

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#435]
bernidouille:
Petit Up pour te dire que je viens de dupliquer un Json OSRAM CLA60RGBWOSRAM vers PAR1650TW
 PAR1650TW.json.txt
(14.1 Kio) Téléchargé 2 fois
J'ai remplacé la terminologie et uploadé sur jeedom.
Inclusion réussie pour le GU10.
ON / OFF / TOGGLE le status et le dimmable fonctionne RAS.
les températures de couleur ne sont pas gérées.

**Comment by KiwiHC16** [comment]
#427 & #428

**Comment by KiwiHC16** [comment]
@bernidouille, es tu dispo pour traiter ce point ?

**Comment by Bernidouille** [comment]
Je viens de tester, Tout est parfait.
Attention sur ce modèle, il n'y a pas de gestion de la couleur (Le GU10  PAR1650TW) et juste la température du Blanc.
Je vais me procurer un  "PAR1650TRGBW" qui lui gérera en plus la couleur.
Ça fera un modèle OSRAM en plus.

**Comment by KiwiHC16** [comment]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&hilit=abeille&sid=b1b748187461f2d58b698b150477409f&start=1760

@Bernidouille : Garden Spot : Tout est bon
