### ISSUE TITLE
Prise Ikea test et integration

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#455]

**Comment by shakalagoons** [comment]
Abeille en semi-automatique, mode inclusion, appui avec une pointe pendant environ 5 secondes sur le bouton de la prise.

![image](https://user-images.githubusercontent.com/36044888/49232721-ca83b880-f3f4-11e8-95da-6a74221e8736.png)

> AbeilleParser 2018-11-29 16:33:14[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 5f; Src Addr : 5874; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0016; Data byte list : ->TRADFRI control outlet<-

ActiveEndPoint :
> AbeilleParser 2018-11-29 16:36:59[DEBUG];type; 8045; (Active Endpoints Response); SQN : 46; Status : 00; Short Address : 5874; Endpoint Count : 03; Endpoint List :; 01; 02; f2

SimpleDescriptorRequest (endpoint 01) :
> AbeilleParser 2018-11-29 16:38:42[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 47; Status : 00; Short Address : 5874; Length : 1c; endpoint : 01; profile : 0104; deviceId : 010A; bitField : 00; InClusterCount : 07
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: 0008 - General: Level Control
AbeilleParser 2018-11-29 16:38:42[DEBUG]In cluster: fc7c -
AbeilleParser 2018-11-29 16:38:42[DEBUG]OutClusterCount : 03
AbeilleParser 2018-11-29 16:38:42[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2018-11-29 16:38:42[DEBUG]Out cluster: 0019 - General: OTA
AbeilleParser 2018-11-29 16:38:42[DEBUG]Out cluster: 0020 - General: Poll Control

SimpleDescriptorRequest (endpoint 02) :
> AbeilleParser 2018-11-29 16:39:44[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 48; Status : 00; Short Address : 5874; Length : 0C; endpoint : 02; profile : c05e; deviceId : 0010; bitField : a8; InClusterCount : 01
AbeilleParser 2018-11-29 16:39:44[DEBUG]In cluster: 1000 - ZLL: Commissioning
AbeilleParser 2018-11-29 16:39:44[DEBUG]OutClusterCount : 01
AbeilleParser 2018-11-29 16:39:44[DEBUG]Out cluster: 1000 - ZLL: Commissioning

SimpleDescriptorRequest (endpoint f2) :
> AbeilleParser 2018-11-29 16:40:34[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 49; Status : 00; Short Address : 5874; Length : 0C; endpoint : f2; profile : a1e0; deviceId : 0061; bitField : 00; InClusterCount : 01
AbeilleParser 2018-11-29 16:40:34[DEBUG]In cluster: 0021 -
AbeilleParser 2018-11-29 16:40:34[DEBUG]OutClusterCount : 01
AbeilleParser 2018-11-29 16:40:34[DEBUG]Out cluster: 0021 -

**Comment by KiwiHC16** [comment]
Plein d'infos !
Je viens de recevoir une livraison Ikea, ca doit être la prise. Je regarde demain.

**Comment by KiwiHC16** [comment]
Je viens de l intégrer:
End Point: 01
Basic: Ok
Identify: Ok
Groups: Ok
Scenes: pas implémenter dans Abeille pour l instant. En cours.
On/Off: Ok
Level Control: ?? (Dans la doc ils parlent de variateur d intensité mais on entend un relai claquer et si j envoie des commandes de level rien ne se passe. Dans la doc, ils parlent de 3 types: E1702, E1705 et E1707. j'ai un E1702.
OTA: J ai vu passer des demandes mais Abeille ne gere pas.
Poll Control: ?
EndPoint 02:
ZLL: na
Endpoint f2:
0021: ?
0021: ?

Retour état On/Off ok.

**Comment by shakalagoons** [comment]
Ca a l'air de fonctionner, merci !

Par contre, impossible d'associer de nouveau des prises qui ont déjà été associées puis supprimées de la ruche... Il y a une manipulation particulière à faire sur la prise ?

**Comment by bart11064** [comment]
Ca fonctionne pour moi.
Par contre, l'état ne se met pas à jour tout seul, je suis obligé de lancer la commande getEtat après chaque action pour avoir l'état courant.
On peut automatiser à chaque changement ou pas ?

**Comment by KiwiHC16** [comment]
Oui ca doit etre auto. Probablement un probleme avec les nouveau template. Ok, I put in my list to test.

**Comment by KiwiHC16** [comment]
Probleme resolu et mis sur le master

**Comment by KiwiHC16** [comment]
Fonctionne chez moi.
