### ISSUE TITLE
La vérification du timeout se fait en seconde alors que la valeur est en minutes

### ISSUE THREAD

**Issue by octera** [KiwiHC16/Abeille#459]
Bonjour,
Depuis la version du 17/11 le plugin fait un vérification des timeouts. Il prend la valeur timeout de l'équipement, or la convention jeedom place cette valeur en minutes et le plugins fait la vérification en seconde.
En conséquence, le plugins place les composant en timeout la ou jeedom les considérais en vie.

D'ailleurs, pourquoi le plugins porte cette responsabilité alors que jeedom le fait aussi?

**Comment by KiwiHC16** [comment]
C est corrigé avec le push de ce jour.
