### ISSUE TITLE
Osram Plug OutDoor icone

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#465]
J'ai rajouter dans mon plugin Abeille la photo pour la prise externe OSRAM en bidouillant (upload puis modif en live de la combo du choix d'image). Si tu peux l'intégrer proprement, je te joins l'image là, elle porte le même nom que la prise classique je ne sais pas si tu peux détecter la différence entre les 2 .

**Comment by poolMiniDomo** [comment]
Voilà mon log lors de l'inclusion de la prise extérieur. Merci pour son intégration
[AbeilleParser_inclusion.log](https://github.com/KiwiHC16/Abeille/files/2616426/AbeilleParser_inclusion.log)

**Comment by KiwiHC16** [comment]
Done. Faire l'appairage classique. Une fois l objet créer dans abeille changer l'Icone par la version outdoor.
