### ISSUE TITLE
Telecommande Philips Hue: niveau batterie & TimeOut ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#466]

**Comment by KiwiHC16** [comment]
Cluster 1 Attribut 0021: reponse: unsupported.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware#version-30f
la partie bind

**Comment by tcharp38** [comment]
Plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
