### ISSUE TITLE
Sur master edgd1er du 30/01 commit 4932a06

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#47]
- demarrage sans le plugin activé et clef USB pas connectée.
=> lors de l'activation du plugin, error message: "Le port n'est pas configuré:" et je ne peux pas activer le plugin. Je suis bloqué.

-demarrage sans le plugin activé et clef USB connectée.
=> le plugin demarre mais la zone demon est remplie avec le message en rouge "Le port n'est pas configuré:"

**Comment by edgd1er** [comment]
@KiwiHC16 

Jj'ai utilisé une fonction jeedom qui recherche les periph usb. 
normalement, si la zigate est trouvée tu as une ligne /dev/ttyusb0 (/dev/tyusb0) qui s'ajoute...
temporairement tu peux ajouter la ligne qui n'est pas trouver par la fonction dans configuration.php (L95)
Hier soir, j'ai testé depuis un docker nouvellement crée sans pb.
Pour le moment auto et Aucun ne fonctionnent pas.(auto pas du tout, none partiellement)

MAJ: 13:13 pas de pull possible avec ton repo non plus, j'ai mergé tes modifs dans ma branche, mais , j'ai perdu des fichiers. (au moins les conf json) et peut etre des modifs, je n'ai pas de clé zigate la pour valider le fonctionnement..... je voudrais utiliser la config port serie = none pour des tests sans zigate, pour le moment, çela ne fonctionne pas. les 3 daemons s’arrêtent. ( j'ai des modifs du 28 qui viennent écraser des modifs du 30 après le merge..... la magie du rebase qui foire.)

je crée une branche pour essayer de réécrire l'historique et récupérer qq chose qui fonctionne.... Je pense avoir repris tout tes commits  
Je n'ai pas de zigate en journée pour valider. Si tu peux faire des tests, peut etre peux tu importer ma branche FixDaemonMess et valider le fonctionnement ?
j'ai utilisé du cherry-pick, j'aurais du faire du rebase interactif.... a définir.

**Comment by KiwiHC16** [comment]
C est la premiere fois que je joue autant avec github, alors tout n'est pas simple.
Dis moi quand tu as un truc que l'on peut merger.
En //, je vais tester FixDaemonMess.
=>
On ne peut pas activer le plugin car il dit que le port n est pas configuré. Puis si on active une deuxieme fois en entre dans le plugin.
Si je choisi le port ttyUSB0 dans la liste alors il continue a dire que le port n est pas configuré avec 
![capture d ecran 2018-01-30 a 16 26 53](https://user-images.githubusercontent.com/8549674/35574583-6fd575ee-05da-11e8-8f34-da8c2708c1f6.png)

**Comment by KiwiHC16** [comment]
Comme il y a eu beaucoup de progrès dans cette partie, je clos cette issue. Si il y a des bugs trouvés alors on fera des issues spécifiques.
