### ISSUE TITLE
Mode semi automatique pour créer les commandes en meme temps que les infos sur la base des nouveaux templates.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#477]

**Comment by handfreezer** [comment]
je viens de mettre à jour et mon inter double xiaomi murale ne marche plus pour l'état 1 : le log abeille indique 0006-01-0000 et dans les commande de mon inter j'ai 0006-0000 pour l'état 1.

Est-ce le même sujet?

**Comment by handfreezer** [comment]
![image](https://user-images.githubusercontent.com/2912752/49314485-f5503880-f4ea-11e8-94c3-51f5c25bdd5b.png)

![image](https://user-images.githubusercontent.com/2912752/49314530-0bf68f80-f4eb-11e8-9f94-dc44b654b549.png)

**Comment by handfreezer** [comment]
Même problème avec le capteur de mouvement : l'info etat et luminosité ne matche plus car cela passe de 0400-0000 à 0400-01-0000 et 0406-0000 à 0406-01-0000

**Comment by handfreezer** [comment]
Ha bah je suppose que c'est le #480 du coup

**Comment by KiwiHC16** [comment]
Visiblement tu as mis à jour avec le master et tu as toujours les "anciens" objets dans Jeedom.
Pour l instant si tu mets à jour avec le master, il faut re-créer tous les équipements.
Je suis entrain de faire une fonction pour faire la mise a jour des objets sans avoir a les supprimer et les recréer. Draft est en place. Peut être d'ici demain soir dans le meilleur des cas.

Je ne sais pas si tu suis le blog: "https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=671627#p671627" mais j'essaye d'y mettre des infos sur l avancement et les problèmes.

**Comment by handfreezer** [comment]
Bonsoir : tu as tout juste, je suis la branche master, j'ai donc eu effectivement un décalage entre le plugin et les commandes info, et j'ai fait un retour arrière sur un backup.
Je vais attendre la fin de ton dev sans souci.
Merci pour ton retour.
Note: j'ai noté le thread du forum, mais comme mon suivi est chaotique, et que le thread concerne tes annonces mais aussi des questions, c'est pas simple de suivre tes news. Peut-être que tu pourrait laisser sur le readme du master un point de suivi, ce serait plus simple accéder et lire, non?

**Comment by KiwiHC16** [comment]
Yep, je peux essayer de maintenir le readme du master comme recap et faire un lien dans le forum.

**Comment by KiwiHC16** [comment]
Je vais essayer de maintenit : https://kiwihc16.github.io/Abeille/fr_FR/changelog

**Comment by KiwiHC16** [comment]
La difficulté est de faire un truc qui marche a tous les coups sans se melanger les crayons. Il n'y a pas de clef primaire pour le faire alors galère. C'est pour ca que le bouton dans abeille couvre probablement 90% des cas mais pas tous. Pour les utilisateurs avancés comme toi c'est une solution d'aller dans la base directement. Avec les nouveaux modele il y a une clef primaire donc ppour le future ca devrait etre plus simple. La clef n'est pas encore utilisée dans le code, c 'est un des trucs que je dois faire.

**Comment by handfreezer** [comment]
Effectivement, mais je pensait que dans ta procédure d'update tu pouvais ajouter ces deux updates en cas de bouton double xiaomi.
Question plus globale: est-ce qu'il n'y a pas un pattern d'action du type 0006-0000 qui pourrait servir de repère pour patcher la base uniquement sur les objets de la ruche? (en fait, je ne sais pas comment marche ton update des modèles? tu accèdes à la base, ou tu utilises des api de jeedom?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by handfreezer** [comment]
Hello,

 Au final, je viens de faire un update de mon plugin sur master, et comme je ne voulais pas tout me palucher à la main, j'ai modifié la fonction daemon_start_cleanup avec le bout de code suivant :

                foreach (array ("0006-0000" => "0006-01-0000", #etat"1" de bouton carre et inter double xiaomi a pile
                                "0006-8000" => "0006-01-8000", #bouton carre multi
                                "0000-ff01" => "0000-01-ff01", #bouton carre specific
                                "0400-0000" => "0400-01-0000", #motion sensor luminosite
                                "0406-0000" => "0406-01-0000"  #motion sensor etat
                                ) as $topicSrc => $topicDst) {
                        if (($row['type'] == 'info') && ($rowArray->topic == $topicSrc)) {
                            log::add(
                                    'Abeille',
                                    'debug',
                                    'deamon_start_cleanup : update logicalId/topic for row_id='.$row['id'].' from '.$topicSrc.' to '.$topicDst
                            );
                            $rowArray->topic = $topicDst;
                            $sqlRequest = 1;
                        }
                }

**Comment by KiwiHC16** [comment]
Je pense que je vais virer le mode semi-auto qui n'a plus de sens vu l evolution du plug in.
