### ISSUE TITLE
Le lancement de l installation des dependances ne se fait pas automatiquement 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#48]

**Comment by edgd1er** [comment]
cela devrait le faire ? 
il est possible de l'ajouter dans le deamon_info if nok => lancement de install.sh.
Autre point, l'install de deps est long et il faudrait remonter une info "en cours" ou mettre la roue dentée.

**Comment by KiwiHC16** [comment]
Le résultat de mes investigations c'est tu peux renvoyer 'state' avec pour valeur ok, nok, in_progress.
Si 'in_progress' tu peux ajouter 'progression' en % et une 'duration' en min. Il ya aussi le 'last_launch'
Mais pour faire ces modifs je voudrais integrer tes modifs d'abord.
C'est le script plugin.dependancy.php dans le core jeedom que fait tout cela.

De meme pour l etat du daemon tu as dans plugin.daemon.php du core jeedom les valeurs: 'state' a ok, nok, puis "launchable" ok, nok, puis launchable_message et auto.

**Comment by KiwiHC16** [comment]
En lisant le code car le lancement des demons n'est pas simple alors je vais plus loin dans le soft.

**Comment by edgd1er** [comment]
je suis en train de clarifier le code et de tester une install from scratch avec docker. du coup, ca prend du temps. Je vais faire un commit un peu barbare mais qui normalement devrait permettre un pull request correct avec tt tes dev.....

**Comment by KiwiHC16** [comment]
En fait si ca fonctionne, il faut juste attendre que Jeedom se reveille soit 5 minutes pour qu'il lance l installation des dependances ...
