### ISSUE TITLE
Faire une mise a jour forcé des objets dans jeedom sur la base des nouveaux templates

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#480]
Sans perdre, l historique, les liaisons Jeelink, hombridge,... les conf éventuelles de l utilisateur.

**Comment by handfreezer** [comment]
Bonjour,

   Si tu as un niveau de enhancement, je dirais que celui-ci est important car à la mise à jour, tout ce qui se base sur les infos/cmdes qui ont changé ne marche plus... cf. #477

**Comment by KiwiHC16** [comment]
Oui c est en cours, je bosse dessus, cf autre issue. Avec un peu de chance, sera dispo demain soir dans le meilleur des cas.

**Comment by handfreezer** [comment]
Cool, merci d'avance!

**Comment by KiwiHC16** [comment]
Dans master mais pas testé. Manque la creation des commandes manquantes dans les objets et définies dans les templates. #483

**Comment by KiwiHC16** [comment]
Je clos ce sujet car dans le code maintenant. Ouvrira des issue sur les problèmes rencontrés.
