### ISSUE TITLE
Perte détecteur de mouvement XIAOMI

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#481]
Je pense après lecture que le problème est connu avec l'id #477 

Une mise a rendu inopérant le détecteur de mouvement Xiaomi
Le détecteur remontait correctement les infos dans "Etat de Santé" ou "TimeStamp" 
Seulement dans le widget, Etat et Luminosité n'étaient plus à jour et figés à la date du 28/11

J'ai supprimé l'objet et refait une inclusion pour obtenir un nouvel objet dans la ruche.
Et du coup je constate que les ID des commandes sont incohérents et du coup je n'avais plus l'information Etat ni Luminosité car le widget pointait sur des valeurs absentes.

La mise à jour a sans doute remplacé les ID par des valeurs de topic différentes
Je joins une copie d'écran où l'on voit que les topics Nom, Etat, Luminosité et Specific ne sont probablement pas ceux attendus. Donc la perte d'information.

Et bien évidemment, les scénarios basés sur cet objet ne fonctionnait plus.

Merci de l'aide apportée à la résolution des incidents

Version JEEDOM 3.2.11
Version Abeille 
Objet XIAOMIinfrarouge2

![pb-jeedom-xiaomi](https://user-images.githubusercontent.com/36518012/49343710-c1058500-f66e-11e8-82cc-2c8238b0fe72.jpg)

**Comment by KiwiHC16** [comment]
Tu dois avoir ce problème car tu as mis à jour depuis le master ou que tu as mis a jour les modules.
Je suppose que c'est ce que tu as fait (un des deux). Peux tu confirmer ?
Le problème est que le master est au milieu d'un dev.
3 solutions:
- tu restaures un backup
- tu mets tout en ligne avec le master (mais il te faudra supprimer les équipements et le re-créer)
- tu attends que je finisse le dev (probablement quelques jours).

**Comment by mickadam29** [comment]
Oui j’ai mis à jour depuis le master
Comme depuis un moment d’ailleurs 
Je vais attendre ton dev 
Mon objet est le seul impacté et pas utile
car je le testais avec des scénarios et alarme
Mais faut reconnaître que ça aurait pu être embêtant 
J’en profite pour te demander si il faut passer la zigate en vE. La mienne est en vD et si il faut tout effacer comme pour la migration vers la D

Merci à toi

**Comment by KiwiHC16** [comment]
Les modifications amenés par la 3.0.e sont à :
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware

`Add Private cluster 0xFC01 to manage some Legrand Netatmo stuff`
-> Si tu as des équipements Legrand. Je n'ai pas encore testé les miens donc pas sur que ca fonctionne avec Abeille.

`Add Power configuration Cluster. Used by Ikea . https://github.com/KiwiHC16/Abeille/issues/139`
-> Si tu veux avoir le niveau des batteries des telecommandes Ikea

`Add 0xFF02 Cluster. Used by Xiaomi devices for battery informations.  https://github.com/KiwiHC16/Abeille/issues/141`
-> Si tu as des équipements Xiaomi premiere version


`Add TimeServer functions (Set 0x0016 and Get 0x0017). You can give a datetime to ZiGate. Some device tell ZiGate to get datetime like some Xiaomi devices.`
=> Pas encore mis en place dans abeille

`Fix UART control flow.`
=> Perso je ne pense que cela soit important

`Fix Device announce from some devices. Ex : fix the Legrand Netatmo join sequence.`
=> Si tu as du Legrand que je n ai pas encore testé.

`Update Device Timeout. 256 min to 16384 min. Limit Xiaomi devices lost. Not a fix but should be better. Not really tested in real condition. https://github.com/fairecasoimeme/ZiGate/issues/38`
=> Devrait améliorer la perte des équipements

Voila à toi de voir. Si tu n'as aucun de ces besoins alors reste en 3.0.d et quand j'aurai fini, ca peut être bien de mettre à jour.

**Comment by KiwiHC16** [comment]
J espère avoir un plugin stable d ici la.

**Comment by KiwiHC16** [comment]
J'ai passé mon systeme de "production" avec le master et pas de problème de mon côté.

**Comment by mickadam29** [comment]
Salut

Je viens de mettre à jour avec la version de pro
Ça fonctionne 
Merci beaucoup

**Comment by KiwiHC16** [comment]
Je clos.
