### ISSUE TITLE
TRADFRI bulb E14 WS opal 400lm

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#50]
mettre toutes les infos dispos dans cet issue

**Comment by zoozbiro** [comment]
<img width="1448" alt="capture d ecran 2018-01-31 a 20 22 57" src="https://user-images.githubusercontent.com/4723029/35642866-c752cf8e-06c4-11e8-8e1d-da2fa653f9ec.png">
<img width="1440" alt="capture d ecran 2018-01-31 a 20 23 11" src="https://user-images.githubusercontent.com/4723029/35642867-c76addae-06c4-11e8-9a59-fca4a07d4a9c.png">
<img width="1499" alt="capture d ecran 2018-01-31 a 20 23 23" src="https://user-images.githubusercontent.com/4723029/35642868-c785fe22-06c4-11e8-9bde-2313734f5f09.png">

**Comment by KiwiHC16** [comment]
Inclus dans JSON et envoyé sur master.
Avez vous une image de cette ampoule ?

**Comment by zoozbiro** [comment]
![tradfri-led-bulb-e14-400-lumen-wireless-dimmable-white-spectrum-opal-white__0463168_pe608600_s4](https://user-images.githubusercontent.com/4723029/35723743-b5c529e6-07fb-11e8-8f9b-71b2a2a5d1d3.jpg)

**Comment by KiwiHC16** [comment]
@zoozbiro, c'est un peu court comme description...

**Comment by zoozbiro** [comment]
Désolé mais j'ai du mal comprendre, tu as demandé une image de l'ampoule non ? De quel type d'information à tu besoin ?

**Comment by KiwiHC16** [comment]
Ben oui mais la je ne vois qu'un rectangle gris avec un icone Question Mark en bleu dedans.
Du coup je ne comprends pas.

**Comment by zoozbiro** [comment]
![tradfri-led-bulb-e14-400-lumen-wireless-dimmable-white-spectrum-opal-white__0463168_pe608600_s4](https://user-images.githubusercontent.com/4723029/35735690-eb15d530-0825-11e8-9324-a53be0cda89d.jpg)

C'est mieux ?

**Comment by zoozbiro** [comment]
Oui

**Comment by zoozbiro** [comment]
![tradfri-ampoule-a-led-e-lumen__0463168_pe608600_s4](https://user-images.githubusercontent.com/4723029/35736399-2b48366e-0828-11e8-9198-7d0ff47aef87.JPG)

**Comment by KiwiHC16** [comment]
Super nous avons l'ampoule maintenant. Je vais l'ajouter.

**Comment by zoozbiro** [comment]
Test effectué en mode automatique l'ampoule est reconnue sans problème après détection (allumage et extinction de l'ampoule). les commandes fonctionnent également.

Par contre il y a un comportement qui pourrait être amélioré, quand l'ampoule est détectée pour la première fois, le setlevel est au minimum (il faut peut être le mettre au maximum) car l'ampoule est au maximum à la première détection.

le bouton identify ne provoque aucune action, normal ?

**Comment by zoozbiro** [comment]
par contre l'image ne remonte pas 
<img width="476" alt="capture d ecran 2018-02-07 a 20 48 46" src="https://user-images.githubusercontent.com/4723029/35938130-86020e76-0c48-11e8-8fcd-d04d5c4ee8ee.png">

**Comment by KiwiHC16** [comment]
Je ne crois pas avoir mis l image encore, ceci explique cela.
