### ISSUE TITLE
graouxx: a chaque coupure réseau , je suis obligé de forcer le redémarrage du daemon.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#501]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&start=1280

Bonjour kiwihc16,

cela fait un petit moment que je ne suis pas venu participer a ce fil de discussion.
J'ai découvert un petit problème avec la dernière version du market, je ne sais pas si il a été déjà soulevé ou corrige sur master.
Il ne me semble pas avoir eu ce problème avec la version précédente ? (peut être lié au fwk 3e car j'ai upgradé les 2 en même temps)

Du coup le **problème est qu'a chaque coupure réseau (redémarrage du routeur par exemple) entre jeedom et la zigate (wifi donc), je suis obligé de forcer le redémarrage du daemon.** Bien entendu la zigate a une ipfixe.

Si tu as besoin que je t'envoie des logs ou autre dis moi.

**Comment by KiwiHC16** [comment]
Version HW est imprimée sur le module. Si le SW est 1.3, le HW doit aussi être 1.3 car sinon ca ne tournerai pas je crois.

Dans log Abeille rien de particulier dauf qu'on ne voit d'info remonter du réseau.

"en filaire ma box domotique (mini pc sur CPL)": tu veuw dire que le réseau passe pas une prise de courant en CPL ?

"IP Fixe" fixé dans le mini PC ou fournie par le DHCP ?

Log AbeilleSocat semble ok.

Je comprends que ton réseau est comme ca:

routeur(DHCP) <-> CPL sur 220V <-> MiniPC(Jeedom) 

Ou est ta borne Wifi dans ton reseau ?

**Comment by graouxx** [comment]
"tu veuw dire que le réseau passe pas une prise de courant en CPL ?" Oui, pour quelques équipements (Jeedom, un ampli HC, ma chaudière) je trouve plus performant que rajouter un dongle wifi. J'hésite à brancher mon mini pc au cul de mon routeur, mais du coup je perds la possibilité de brancher ma télé dessus (et donc plus d'écran)

IP fixé par le DHCP (routeur Xiaomi)

routeur(DHCP) <-> CPL sur 220V <-> MiniPC(Jeedom)
C'est exact, la borne wifi c'est le routeur.

En fait dans le détail 
WAN 1 4G (Huawei ) <-->  Routeur Netgear <--> Routeur Wifi DHCP Xiaomi <--> CPL <--> MiniPC
WAN 2 ADSL (freebx) <-->   ----------------------------------------------------- <-(wifi)-> Zigate

Le routeur Netgear permet de loadbalancer les connections internet, ce n'est pas lui qui fait DHCP.

Et je confirme la version HW 1.3 pour le module wifi Zigate.

Je sais plus si je te l'ai dis, mais je n'avais pas ce problème avant mes montées de version. (3e, nouvelle version Abeille dans Jeedom et ancienne ruche)

**Comment by KiwiHC16** [comment]
Si je comprends bien la connection TCP se fait de la facon suivante:
Zigate(Wifi) <-> (wifi) <-> Router Wifi DHCP Xiaomi <--> (CPL) <--> MiniPC
Et c'est quand le routeur tombe que tu dois redemarrer le plugin.
Est ce bien ca ?

**Comment by graouxx** [comment]
C'est exactement ça.
Et c'est effectivement quand le routeur tombe ou dès qu'il y a perte de communication entre le minipc et la zigate :
- redémarrage routeur
- débranchement/rebranchement zigate (ce que j'ai fait ce matin)

**Comment by KiwiHC16** [comment]
Ok maintenant que je comprends le scenario, je vais pouvoir tester et trouver une solution.
Il y a un ping vers la zigate, pour vérifier quelle est présente. Je peux imaginer sur perte de faire un ping IP, et si ok redemarrge du plugin (ou juste la partie connection).
A suivre.

**Comment by graouxx** [comment]
OK, dis moi si tu as besoin que je fasse un truc

**Comment by KiwiHC16** [comment]
Pas trop d'idée pour l instant. Je reviens vers toi quand j'ai débuté les investigations.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Je ne vais rien mettre dans Abeile car je vais trop complexifier et je ne vois pas de config standard qui permette de faire ce facilement sans provoquer d autres problèmes.
Sur une Zigate Wifi, tu peux utiliser un plugin Ping dans jeedom et un scenarion qui fait ce que tu souhaites sur perte de ping et par exemple le reset du plugin and les commandes dans un block code de scenario:

```
Abeille::deamon_stop();
sleep(10);
Abeille::deamon_start(); 
```
