### ISSUE TITLE
Interrupteur Xiaomi double sur pile "lumi.remote.b286acn01" non détecté

### ISSUE THREAD

**Issue by Tulan** [KiwiHC16/Abeille#504]
Bonsoir,
j'ai acheté un interrupteur mural double Xiaomi sur pile, référence **[WXKG02LM](https://www.domadoo.fr/fr/peripheriques/4517-xiaomi-interrupteur-mural-double-sans-fil-zigbee-aqara-6970504210042.html?search_query=aqara&results=10)**.

Celui-ci n'est pas reconnu par le plugin Abeille, et apparaît dans Jeedom sous le nom "Abeille-c60B--Type d objet inconnu (!JSON)" une fois associé et aucune commande n'est détectée. Dans les logs il est détecté comme **lumi.remote.b286acn01**.

Ci-joint l'ensemble des logs en mode debug de l'association et de plusieurs appuis sur les deux boutons (court, long, double appui ...)

N'hésitez pas si vous avez besoin de plus d'informations ou de beta-test ;)

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2660069/Abeille.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2660070/AbeilleMQTTCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2660071/AbeilleParser.txt)
[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/2660072/AbeilleSerialRead.txt)

**Comment by KiwiHC16** [comment]
Oui il a visiblement chnagé de nom alors il a maintenant son petit modele JSOn personnel ...
Je clos le sujet.
