### ISSUE TITLE
TRADFRI bulb E27 CWS opal 600lm

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#51]
mettre toutes les informations sur cette ampoule ici

**Comment by zoozbiro** [comment]
<img width="1471" alt="capture d ecran 2018-01-31 a 20 52 32" src="https://user-images.githubusercontent.com/4723029/35644371-1152013c-06c9-11e8-8565-3f4fe647c599.png">
<img width="445" alt="capture d ecran 2018-01-31 a 20 54 13" src="https://user-images.githubusercontent.com/4723029/35644372-118f6a86-06c9-11e8-8d5a-105b5a8d6cff.png">

**Comment by KiwiHC16** [comment]
@zoozbiro Peu tu tester, cette ampoule est dans JSOn maintenant.

**Comment by zoozbiro** [comment]
Test effectué en mode automatique l'ampoule est reconnue sans problème après détection (allumage et extinction de l'ampoule). les commandes fonctionnent également.

Par contre il y a un comportement qui pourrait être amélioré, quand l'ampoule est détectée pour la première fois, le setlevel est au minimum (il faut peut être le mettre au maximum) car l'ampoule est au maximum à la première détection.

le bouton identify ne provoque aucune action, normal ? 
avec cette ampoule il est possible d'avoir plusieurs couleurs ce n'est pas encore implémentée ou je dois faire une action?  Si ce n'est pas encore implémentée est ce qu'il a des actions que je peux faire pour aider ?

**Comment by KiwiHC16** [comment]
On a un très bon debut avec une ampoule dans Jeedom.

Comportement: setLevel au max, oui c est possible. 

identify: si la lampe est allumée, doit faire varier l intensité.

Couleurs: non pas encore implémentée mais j'ai découvert les commandes aujourd'hui alors je vais regarder.

**Comment by zoozbiro** [comment]
Je confirme identify ne fonctionne pas

**Comment by KiwiHC16** [comment]
Ok

**Comment by zoozbiro** [comment]
j'ai redémarré le demon et maintenant le bouton identify fonctionne...

**Comment by KiwiHC16** [comment]
Super

**Comment by shakalagoons** [comment]
Si ça peut aider, voici les retours d'une commande "ActiveEndPoint" et d'une commande "SimpleDescriptorRequest" :

AbeilleParser: 2018-02-09 10:12:38[DEBUG]-------------- 2018-02-09 10:12:38: protocolData
AbeilleParser: 2018-02-09 10:12:38[DEBUG]message > 12 char
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Type: 8045 quality: 54
AbeilleParser: 2018-02-09 10:12:38[DEBUG]type: 8045 (Active Endpoints Response)(Not Processed)
AbeilleParser: 2018-02-09 10:12:38[DEBUG]SQN : 3b
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Status : 00
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Short Address : 8c48
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Endpoint Count : 01
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Endpoint List :
AbeilleParser: 2018-02-09 10:12:38[DEBUG]Endpoint : 01



AbeilleParser: 2018-02-09 10:15:28[DEBUG]-------------- 2018-02-09 10:15:28: protocolData
AbeilleParser: 2018-02-09 10:15:28[DEBUG]message > 12 char
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Type: 8043 quality: 4b
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Type: 8043 (Simple Descriptor Response)(Not Processed)
AbeilleParser: 2018-02-09 10:15:28[DEBUG]SQN : 3c
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Status : 00
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Short Address : 8c48
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Length : 22
AbeilleParser: 2018-02-09 10:15:28[DEBUG]endpoint : 01
AbeilleParser: 2018-02-09 10:15:28[DEBUG]profile : c05e
AbeilleParser: 2018-02-09 10:15:28[DEBUG]deviceId : 0200
AbeilleParser: 2018-02-09 10:15:28[DEBUG]bitField : 02
AbeilleParser: 2018-02-09 10:15:28[DEBUG]InClusterCount : 09
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0008 - General: Level Control
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0300 - Lighting: Color Control
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 0B05 - Misc: Diagnostics
AbeilleParser: 2018-02-09 10:15:28[DEBUG]In cluster: 1000 - ZLL: Commissioning
AbeilleParser: 2018-02-09 10:15:28[DEBUG]OutClusterCount : 04
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Out cluster: 0000 - General: Basic
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Out cluster: 0004 - General: Groups
AbeilleParser: 2018-02-09 10:15:28[DEBUG]Out cluster: 0005 - General: Scenes

**Comment by KiwiHC16** [comment]
Oui très intéressant car visiblement elle fait du "Lighting: Color Control" ce que je n'ai pas chez moi. Je n'ai pas encore joué avec. 
Peux tu partager une photo de cette ampoule ?
Je viens de regarder sur le site web IKEA pour acheter une ampoule de type et je la trouve pas, ou l as tu acheté ? Est elle sur le site web IKEA ?

**Comment by zoozbiro** [comment]
j'ai eu un peu de mal a la retrouver car en réalité c'est kit l'ampoule n'est pas encore disponible seul.

http://www.ikea.com/fr/fr/catalog/products/70338951/

je regarde comment je peux faire quelques tests pour la couleur, mais je ne comprendre pas encore comment envoyer le message.

**Comment by KiwiHC16** [comment]
Merci pour l info.
Je n'ai pas mis dans le code la fonction color. Il faut coder la fonction, je vais essayer de le faire la semaine prochaine.

**Comment by KiwiHC16** [comment]
Actuellement comment fais tu changer la couleur ? Avec la telecommande 5 boutons ? Avec l apple sur le mobile ?

**Comment by zoozbiro** [comment]
oui avec la telecommande. dans quel fichier je peux trouver les fonctions ? je vais commencer à regarder

**Comment by KiwiHC16** [comment]
Abeille/resources/AbeilleDeamon et fichiers CmdToAbeille.php dans un premier temps.

**Comment by lukebr91** [comment]
J'ai la même ampoule, fonctionnement OK sur on/off/toggle

Mais depuis l'association avec la zigate, j'ai perdu la fonctionnalité du changement de couleur avec la télécommande 5 boutons (associées également sur la zigate puis avec l'ampoule)
Après lecture de : http://faire-ca-soi-meme.fr/zigate/2017/11/27/maitrisez-vos-ampoules-zigbee/

Est-ce que quelqu'un d'autre a le soucis?

La fonction Colour fonctionne en revanche

**Comment by KiwiHC16** [comment]
Salut @lukebr91 , la fonction couleur avec la telecommande Ikea est géré par les scènes. Mais pour avoir les scènes il faut les groupes. Les groupes fonctionnent maintenant, il faut que je fasse une doc et ensuite il faut implementer les scenes et faire la doc. Encore du boulot mais normalement rien d'impossible je dois avoir tout ce qu il faut en stock.

**Comment by lukebr91** [comment]
Ok merci
J'ai effectivement testé les groupes hier, pour info le plug 01 osram
intégré sans soucis dans le groupe, idem prise Xiaomi mais ça tu savais.

**Comment by KiwiHC16** [comment]
Mais c'est toujours mieux en ayant le feedback de ce qui marche aussi.
Peux tu faire une petite doc sur la plug 01 osram sur comment tu as defini le groupe ? (en asciidoc qui est super simple avec quelque captures d'écran , car je ne peux pas le faire dans la mesure ou je n'ai pas cette prise)

**Comment by KiwiHC16** [comment]
JSON en place. Je clos si issue on ouvrira un cas specifique.
