### ISSUE TITLE
Contacteur porte: suite maj github, perte de l'etat ouvert fermé

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#516]
objet: lumi.sensor_magnet.aq2

Suite à la maj de github, l'etat (ouvert/fermé) n'est pas remonté décodé.
Ci dessous les logs: "L objet: Abeille/ab81 existe mais pas la commande: 0006-01-0000"

==> AbeilleSerialRead <==
AbeilleSerialRead 2018-12-11 17:41:50[DEBUG]2018-12-11 17:41:50 -> 8102000Ef004ab810100060000001000010045

==> AbeilleParser <==
AbeilleParser 2018-12-11 17:41:50[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 04; Src Addr : ab81; End Point : 01; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00

==> Abeille <==
[2018-12-11 17:41:50][DEBUG] : Topic: ->Abeille/ab81/Link-Quality<- Value ->69<-
[2018-12-11 17:41:50][DEBUG] : -
[2018-12-11 17:41:50][DEBUG] : -
[2018-12-11 17:41:50][DEBUG] : Topic: ->Abeille/ab81/0006-01-0000<- Value ->0<-
[2018-12-11 17:41:50][DEBUG] : L objet: Abeille/ab81 existe mais pas la commande: 0006-01-0000
[2018-12-11 17:41:50][DEBUG] : -
[2018-12-11 17:41:50][DEBUG] : -

**Comment by KiwiHC16** [comment]
As tu fait les étapes de mise a jour: https://kiwihc16.github.io/Abeille/fr_FR/changelog

**Comment by edgd1er** [comment]
Merci pour le lien, je vais voir ça. J'avais appliqué le nouveau template aux objets. C'est bien passé pour le detecteur lum/mouv et les 3 capteurs hum/temp/pression. Les deux contacts de porte posent problème ( bonne détection du device mais etat non remonté). je suis dans les 10% pour ces deux devices. je vais découvrir comment focntionne le nouveau modele de template.....

PS: bravo pour la doc, peu de plugin peuvent se vanter d'avoir une doc aussi détaillée.

en appliquant le modèle, j'ai trouvé ça: j'avais changé la commande etat en etatDoor

Abeille Id: 92 - Abeille Name: Abeille-e4ef-jardin template: sensor_magnet.aq2
- parameter identical, no change: 			'uniqId'
- parameter identical, no change: 			'icone'
- parameter identical, no change: 			'battery_type'
- parameter identical, no change: 			'mainEP'
- parameter is not in the template, no change : 	'defaultEP'
- parameter identical, no change: 			'timeout'
---
Cmd Name: nom
- parameter is not in the template, no change : 	'generic_type'
- parameter identical, no change: 			'order'
- parameter identical, no change: 			'isHistorized'
- parameter is not in the template, no change : 	'unite'
- parameter is not in the template, no change : 	'topic'
- parameter is not in the template, no change : 	'request'
- parameter is not in the template, no change : 	'AbeilleRejectValue'
- parameter is not in the template, no change : 	'returnStateValue'
- parameter is not in the template, no change : 	'returnStateTime'
- parameter is not in the template, no change : 	'repeatEventManagement'
- parameter identical, no change: 			'visibilityCategory'
- parameter is not in the template, no change : 	'visibiltyTemplate'
- parameter is not in the template, no change : 	'minValue'
- parameter is not in the template, no change : 	'maxValue'
- parameter is not in the template, no change : 	'calculValueOffset'
- parameter identical, no change: 			'isVisible'
---
Cmd Name: etatDoor ===================================> not found in template
---

**Comment by edgd1er** [comment]
si je remet le nom de la commande a etat: j'ai

---
Cmd Name: etat
- parameter identical, no change: 			'generic_type'
---------> parameter different, will be updated 	'order': '1' -> '2'
- parameter identical, no change: 			'isHistorized'
- parameter is not in the template, no change : 	'unite'
- parameter is not in the template, no change : 	'topic'
- parameter is not in the template, no change : 	'request'
- parameter is not in the template, no change : 	'AbeilleRejectValue'
- parameter is not in the template, no change : 	'returnStateValue'
- parameter is not in the template, no change : 	'returnStateTime'
- parameter is not in the template, no change : 	'repeatEventManagement'
- parameter identical, no change: 			'visibilityCategory'
- parameter is not in the template, no change : 	'visibiltyTemplate'
- parameter is not in the template, no change : 	'minValue'
- parameter is not in the template, no change : 	'maxValue'
- parameter is not in the template, no change : 	'calculValueOffset'
- parameter identical, no change: 			'isVisible'
---

**Comment by KiwiHC16** [comment]
Est ce que cela fonctionne maintenant ?
Je suppose que non et si c'est non dans le log ci dessus, ce que je ne comprends pas c'est pourquoi tu as: "parameter is not in the template, no change : 'topic'"

Dans le log juste avant as tu le nom du modele utilisé ?

Peux tu partager une copie des paramètres de la commande état ?

As tu un truc comme:
![capture d ecran 2018-12-11 a 22 49 18](https://user-images.githubusercontent.com/8549674/49832458-0163b200-fd97-11e8-844c-7e013c458bdf.png)

Le plus important à vérifier est le logicalId et le champ configuration.

**Comment by KiwiHC16** [comment]
"sensor_magnet.aq2" pardon c est écrit dans le post d avant.

**Comment by KiwiHC16** [comment]
Je viens de tester sur mon système est c'est bizarre, il faut que je regardes plus dans les details.

**Comment by edgd1er** [comment]
logicalId et configuration sont différents chez moi:
0006-0000 chez moi , 0006-01-0000 chez toi pr logicalId, et cela se retrouve dans la configuration.
La solution est elle de changer ce deux valeurs ? j'avoue ne pas comprendre d'ou cela vient.

![image](https://user-images.githubusercontent.com/3601462/49833420-b9925a00-fd99-11e8-9d62-d5ae46117820.png)

**Comment by KiwiHC16** [comment]
Oui c'est la raison pour laquelle tu n'as pas l info dans jeedom alors quelle remonte. C'est un des changements du fait des nouveaux template. Mais j'ai l impression que pour les commandes info, l'état n'est pas mis a jour (ta situation). Je pense qu'il manque dans le template etatDoor.json la variable topic dans la champ config. Je le mets et fait un push dans master d'ici 10 minutes le temps de changer et tester.

**Comment by edgd1er** [comment]
pr info, je n'ai pas encore fait la maj vers le firmware 3.0e ( je suis toujours en d) est ce que cela a un impact ?
La manière de décoder les infos du port série donnes des résultats différents ?

**Comment by KiwiHC16** [comment]
Je viens de pousser la modification. Essayes.

**Comment by KiwiHC16** [comment]
Pour 3.0.e regardes #481, j ai fait un petit recap.

**Comment by edgd1er** [comment]
ok, j'ai mis a jour les modèles et appliquer les modèles via la conf du plugin.

et j'ai eu ça:
---
Cmd Name: etat
- parameter identical, no change: 			'generic_type'
- parameter identical, no change: 			'order'
- parameter identical, no change: 			'isHistorized'
- parameter is not in the template, no change : 	'unite'
---------> parameter different, will be updated 	'topic': '0006-0000' -> '0006-01-0000'

et ça fonctionne de nouveau, merci.
