### ISSUE TITLE
TRADFRI Remote Ronde 5 boutons

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#52]
mettre toutes les info ici

**Comment by shakalagoons** [comment]
![image](https://user-images.githubusercontent.com/36044888/35687901-3b0423e6-0770-11e8-857c-751321bb2023.png)

De quelles autres informations aurais-tu besoin ?

**Comment by shakalagoons** [comment]
Je possède cette télécommande, tu aurais besoin de quoi comme informations ?

**Comment by KiwiHC16** [comment]
Peux tu mettre toutes les infos que tu possedes dessus ? Par exemple une photo que je pourrais mettre dans le plugin. La capture d'ecran Jeedom dans le dashboard et les ecrans de l objet avec les parametres globaux et les details des commandes. Expliquer comment tu as associé la telecommande...

J'en ai une aussi mais le plus je recois d'info le plus cela sera complet

J ai recu un  mail avec une capture d ecran alors je l ajoute.

![35687901-3b0423e6-0770-11e8-857c-751321bb2023](https://user-images.githubusercontent.com/8549674/35689822-a4c27ff4-0774-11e8-8ab7-9b2c493bcc7e.png)

**Comment by shakalagoons** [comment]
OK ça marche.
Est-ce qu'il faut se mettre en mode "semi-automatique" pour la création des objets ?

**Comment by KiwiHC16** [comment]
Oui. Dans le mode automatique, Abeille ne crée que les objets qu'il connait. En mode semi automatique, il crée les commandes en fonction de ce qu'il recoit et fait au mieux avec. Ca permet d'avoir un début d'infos sur les messages qui arrivent.

**Comment by shakalagoons** [comment]
La capture que tu as reçue par mail vient de moi je crois, et je ne suis pas certain qu'elle concerne la télécommande, vu que j'avais fait plusieurs manipulations en même temps.

Alors :
- Abeille en mode inclusion
- 4 appuis successifs sur le bouton à l'arrière de la télécommande
- La LED à l'avant de la télécommande clignote en rouge pendant quelques secondes
- La LED bleue de la Zigate clignote rapidement pendant quelques secondes

A priori deux objets ont été créés :
![image](https://user-images.githubusercontent.com/36044888/35691250-3ddf6726-0778-11e8-9cf2-4cdb921a9b07.png)
![image](https://user-images.githubusercontent.com/36044888/35691283-54626f8e-0778-11e8-8130-2ce27be8b550.png)
![image](https://user-images.githubusercontent.com/36044888/35691299-62c02f30-0778-11e8-9eb7-1628317766db.png)

**Comment by KiwiHC16** [comment]
Si c'est la meme télécommande, il y deux objets car la télécommande c'est associée deux fois et a eu deux adresses zigbee différentes dans le temps (Une a chaque nouvelle association). De ce fait 2 objets dans jeedom. Le premier ne sert plus a rien et peut être effacé et le deuxième est le bon. Dans la todo list, j ai pour action d'indiquer les objets qui ne sont plus nécessaires.
J'ai une de ces télécommandes, je vais faire des tests dans les jours qui viennent.

**Comment by shakalagoons** [comment]
OK, merci pour l'info.

Voici pour l'image :

![image](https://user-images.githubusercontent.com/36044888/35742054-b2a9e510-0839-11e8-99fd-6ada7536956e.png)

**Comment by KiwiHC16** [comment]
Je ne sais pas encore comment mettre cette télécommande dans Jeedom.
1) Recevoir des infos de la télécommande comme un appui sur un bouton (Je ne sais pas "encore" faire)
2) Créer un objet télécommande qui simule la vrai télécommande ? Avec 5 boutons ?
Si c'est l'idée je pense maintenant avoir tous les ingrédients, il faut que je les implémente. 

Par ailleurs , les nouvelles du jour c'est que j'ai mis dans Jeedom du code qui permet d'avoir la remontée d'info d'une lampe IKEA qui change d'état quand on la commande avec la télécommande. Ce n'est pas simple et il reste beaucoup d'étapes manuelles que je dois simplifier et rendre simple pour tous.

**Comment by KiwiHC16** [comment]
Dernieres évolutions:
https://github.com/KiwiHC16/Abeille/blob/master/Documentation/IKEA.asciidoc#telecommnande-ronde-5-boutons

**Comment by KiwiHC16** [comment]
Appui bouton au dos 4x alors que ZiGate pas en mode inclusion:

AbeilleParser 2018-03-04 18:08:21[DEBUG]-------------- 2018-03-04 18:08:21: protocolData size(30) message > 12 char
AbeilleParser 2018-03-04 18:08:21[DEBUG]Type: 8048 quality: c9
AbeilleParser 2018-03-04 18:08:21[DEBUG] type: 8048 (Leave Indication)(Processed->Draft-MQTT)
AbeilleParser 2018-03-04 18:08:21[DEBUG]extended addr : 90fd9ffffe165c2c
AbeilleParser 2018-03-04 18:08:21[DEBUG]rejoin status : 00
AbeilleParser 2018-03-04 18:08:21[DEBUG]mqttPublish with Qos: 0

En fait je ne suis pas sure car je n arrive pas a le reproduire.

**Comment by lukebr91** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/23

Un peu de lecture sur les remotes IKEA ;)
Remontée des différents bouton, mise à jour firmware etc

**Comment by KiwiHC16** [comment]
JSON en place. Je clos si issue on ouvrira un cas specifique.
