### ISSUE TITLE
Changement de source de mise à jour et bugs

### ISSUE THREAD

**Issue by mickadam29** [KiwiHC16/Abeille#520]
Bonjour

Pourrais-je avoir la procédure pour modifier la source de mise à jour du plugin ?
Actuellement, je suis toujours sur la branche master de GitHub
Je souhaiterais que le mises à jour soient celles du market de jeedom ou la banche stable.
Ces derniers temps les changements sont fréquents et induisent des pertes dans la configuration.
Par exemple, j'ai dû réinscrire une ampoule Ikea et sa télécommande ronde. Je pilote l'ampoule via la télécommande ronde (réelle) et le widget Ampoule. Mais impossible de récupérer le group pour l'inclure dans la télécommande virtuelle.

Merci

**Comment by mickadam29** [comment]
Merci. J'avais oublié la procédure pour le groupe. Je pensais que la télécommande physique affectait un groupe. A priori non, Donc le Group n'existait pas. J'en ai affecté un et associé à la télécommande virtuelle pour les commandes. Ca semble fonctionner. Je te tiens au courant

**Comment by KiwiHC16** [comment]
Je n'ai pas encore trouver le moyen de trouver le group de la telecommande en dialoguant avec la telecommande en direct, c'est pour ca qu'il faut passer par l ampoule.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by mickadam29** [comment]
Bonjour 

L’idée me semble honnête en rapport du travail fourni.
Je vais y réfléchir 
D’autant que je risque d’avoir besoin de ton aide
Ma ZiGate a cramé lors de la mise à jour en 3.0e. Écran bleu Windows pendant le flash !!
J’ai donc commandé une nouvelle et je vais devoir reprendre toute la conf des objets existants 
Merci à toi

**Comment by KiwiHC16** [comment]
> Je n'ai pas encore trouver le moyen de trouver le group de la telecommande en dialoguant avec la telecommande en direct, c'est pour ca qu'il faut passer par l ampoule.

Par contre dans la version master, je sais forcer le groupe utilisé par la vrai télécommande (plus besoin de se prendre la tete avec une ampoule pour trouver le groupe car c'est nous qui le donnons).

**Comment by KiwiHC16** [comment]
Bizarre que la zigate soit HS car ma comprehension est qu'elle contient un bootloader alors meme en cas de crash durant le flash, on doit pouvoir reprendre le flash a zero et ca doit fonctionner.

**Comment by mickadam29** [comment]
Elle reste allumée bleu fixe très faible
Échec de détection dans le programme de flash.
J’en profite pour t’indiquer que mon problème initial avant flash de la ZiGate c’est que l’ampoule IKEA e27 1000lm vendue avec le variateur rond n’est pas reconnue par le plugin.

**Comment by KiwiHC16** [comment]
Pour l ampoule il me faut son nom.
Il faudrait le plug in en mode debug et faire une inclusion et partager AbeilleParser des que tu as une zigate fonctionnelle.

**Comment by mickadam29** [comment]
Je vais regarder les logs. Avant le crash c’était en debug. Mais ça risque d’être « pollué »

**Comment by KiwiHC16** [comment]
Je suppose que le soucis de zigate hs est clos depuis longtemps.

**Comment by mickadam29** [comment]
Bonjour

Et merci pour le suivi
Le souci est réglé par remplacement de ZiGate 

Merci à toi
