### ISSUE TITLE
Xiaomi Magic Cube - Problème de "commande"

### ISSUE THREAD

**Issue by shakalagoons** [KiwiHC16/Abeille#523]
Salut,

L'inclusion du cube se passe bien, par contre les valeurs ne remontent pas.

Dans le log "Abeille", quand je fais un mouvement avec le cube, j'ai le message suivant qui s'affiche :

> [2018-12-16 20:37:24][DEBUG] : Topic: ->Abeille/92c3/0012-02-0055<- Value ->3<-
[2018-12-16 20:37:24][DEBUG] : L objet: Abeille/92c3 existe mais pas la commande: 0012-02-0055

Quand j'effectue une rotation avec le cube :

> [2018-12-16 20:39:35][DEBUG] : Topic: ->Abeille/92c3/000C-03-0055<- Value ->-30.120002746582<-
[2018-12-16 20:39:35][DEBUG] : L objet: Abeille/92c3 existe mais pas la commande: 000C-03-0055

Merci d'avance !

**Comment by KiwiHC16** [comment]
As tu fait -> https://kiwihc16.github.io/Abeille/fr_FR/changelog
Si oui, il faut que je vérifie le modele qui a évolué et qui pose peut être problème.

**Comment by shakalagoons** [comment]
> As tu fait -> https://kiwihc16.github.io/Abeille/fr_FR/changelog
> Si oui, il faut que je vérifie le modele qui a évolué et qui pose peut être problème.

Salut,
J'ai suivi la procédure indiquée (suppression des objets et du plugin, puis réinstallation), et le problème est toujours présent.
J'utilise la branche "Master" du plugin.
Par contre je ne peux pas rouvrir le cas...

**Comment by KiwiHC16** [comment]
Est ce un cube aqara ? 
As tu une reference du cube ? Sos la trappe a cote de la pile ?

**Comment by shakalagoons** [comment]
Aqara je sais pas, j’ai une inscription « Mi » sur l’une des faces.
Les infos sous la trappe :
CMIIT ID : 2016DP0965
MFKZQ01LM

**Comment by KiwiHC16** [comment]
Ok je regarderai en fin de semaine. Désolé, je ne peux pas avant.

**Comment by shakalagoons** [comment]
Aucun problème, merci !

**Comment by KiwiHC16** [comment]
Perso ce n'est pas Mi ma AQARA sur le dessus.
Sous la trappe la ref est MFKZQ01LM
Qui est la même que la tienne.
C'est un bon début.

**Comment by KiwiHC16** [comment]
Je viens de simuler la creation du cube et c'est n importe quoi. Il faut que je regarde pourquoi !!!

**Comment by shakalagoons** [comment]
Salut,
J’ai fait la mise à jour, j’ai supprimé l’objet et je l’ai recréé, et le problème est toujours le même (messages identiques dans le log « Abeille »).

**Comment by KiwiHC16** [comment]
Peux tu me faire une capture d'ecran de la commande 0012-xx-0055.

**Comment by shakalagoons** [comment]
Voilà :

![image](https://user-images.githubusercontent.com/36044888/51024402-c0bfaa00-1589-11e9-8437-e0e901c79c18.png)
![image](https://user-images.githubusercontent.com/36044888/51024420-cfa65c80-1589-11e9-8e7d-955f308f74af.png)

**Comment by KiwiHC16** [comment]
Les deux ne sont pas bon. Ok, je dois regarder le modele.

**Comment by KiwiHC16** [comment]
Ok visiblement le cube Mi (que tu as) est un modele V1 et  le cube Aqara (celui que j'ai) est uN modele V2.
Meme ref mais probalement pas meme soft.
Je viens de mettre a jour le modele V1 dans le master si tu veux essayer.

**Comment by shakalagoons** [comment]
Ça semble OK, j’ai bien les deux valeurs qui remontent maintenant.

Merci !

**Comment by KiwiHC16** [comment]
Super, je clos le sujet.
