### ISSUE TITLE
capteurs de porte aqara ? remontée batterie ?!

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#524]

**Comment by KiwiHC16** [comment]
Je rebondis sur ce sujet concernant la remontée du pourcentage de batterie, j'ai installé ces derniers jours des capteurs de présence Xiaomi V1, mais impossible d'avoir une remontée du pourcentage de batterie restant, par contre le Cube Xiaomi remonte bien l'information

**Comment by graouxx** [comment]
Dis moi si besoin d'infos
