### ISSUE TITLE
Réactivité improve

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#530]
Bonjour,
apres passage à le pre-release 3.0f et ré-inclusion de tous mes modules + interrupteurs => tout fonctionne.
Je constate juste un délai de 1 à 2 secondes pour l'allumage d'un lampe suite à l'appui sur mon inter mural à pile 1 bouton.
Y a-t-il un paramètrage possible ?

**Comment by KiwiHC16** [comment]
Il y a dans la version courante 0.5s entre deux receptions de messages. Qui ne doit pas impacter ce scénario mais je l'enlève car il ne semble pas super nécessaire. Ensuite il y avait des timers qui peuvent impacter un scenario qui eteint plusieurs ampoules les une apres les autres. 2s entre ampoule.Je l'enlève.

Je ne vois pas de "sleep" qui pourait impacter les scenario ci dessus.
Test : interXiaomi->Radio1->zigate(USB)->Abeille->scenario->abeille->Zigate(USB)->radio2->Prise Ikea
En regardant l'interface radio j'ai des temps(Radio2-Radio1) qui varient de 0,2s à 0,9s disons toujours sous la seconde.

Si les temps sont supérieurs, Explications possibles:
- en cas d'ajout d'un equipement il est interrogé et il y a des sleeps. Pendant cette operation ca ralenti les autres.
- charge de la machine jeedom ?
- routage des message dans le zigbee (peut aller jusqu'5s d apres mes observations)
- autre ?

**Comment by KiwiHC16** [comment]
Can't do more I guess.

**Comment by graouxx** [comment]
Je constate également des latences sur les clics de mes boutons Xiaomi. Je pense que cela vient du bouton en lui même qui "attend" le nombre de clics avant de communiquer l'info. J'ai également cette latence en utilisant la passerelle xiaomi.
Par contre pas de latence sur un inter qui ne gère que le simple click. Je ne sais pas si mon commentaire peut aider.

**Comment by KiwiHC16** [comment]
Si plusieurs appuis alors un message envoyé en fin de procedure.
Certains boutons envoient un message sur appui et un message sur relâche
Certains boutons envoient un message unique sur relache.
