### ISSUE TITLE
Retour etat ampoule Hue

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#534]
Re-Salut @doudz,
Je relisant ma réponse je viens peut être de trouver la solution => C05E
CF Telecommande Hue !!!!
J'ouvre une issue.
Investigations à suivre....

**Comment by doudz** [comment]
Je ne suis pas sûr de bien comprendre, la télécommande a un retour d'état de l'ampoule ?

**Comment by doudz** [comment]
Personnellement je pense que je vais traiter le problème de la façon suivante dès l'instant où la commande passe bien on suppose que l'État est bien changé

**Comment by KiwiHC16** [comment]
Non. On peut faire un retour d'etat de la telecommande Hue, et j'ai fourni les details à @Akila qui a fait le modif necessaire dans 3.0.f.
Il est fort probable que l'ampoule puisse être configuré de la même façon pour remontée son état vers la zigate qui transmettra si en 3.0.f.

**Comment by KiwiHC16** [comment]
Simu du retour d'état, c'est ce que je fais pour l'instant mais si on pouvait avoir un vrai retour d'état ca serait top.

**Comment by KiwiHC16** [comment]
Il faut que je teste mais je ne suis pas sur le sujet pour encore plusieurs jours.

**Comment by KiwiHC16** [comment]
je viens peut être de trouver la solution => C05E

Fausse piste. J'ai confondu avec FC00.

C'est mort de mon point de vue sauf nouvelle info.
