### ISSUE TITLE
Probleme inclusion. (IEEE-Addr; =>ffffffffffffffff<=)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#536]

**Comment by KiwiHC16** [comment]
```
[2019-01-06 09:46:04][DEBUG] : Topic: ->Abeille/Ruche/IEEE-Addr<- Value ->00158d0001ee04b7<-
[2019-01-06 09:46:04][DEBUG] : IEEE-Addr; =>ffffffffffffffff<= ; IEEE non valable pour un equipement, valeur rejetée: Ruche:  =>ffffffffffffffff<=
[2019-01-06 09:46:04][DEBUG] : -
[2019-01-06 09:46:04][DEBUG] : -
[2019-01-06 09:46:04][DEBUG] : Topic: ->Abeille/Ruche/PAN-ID<- Value ->f867<-
```

**Comment by KiwiHC16** [comment]
```
[2019-01-05 22:03:04][DEBUG] : Topic: ->Abeille/Ruche/Short-Addr<- Value ->0000<-
[2019-01-05 22:03:04][DEBUG] : -
[2019-01-05 22:03:04][DEBUG] : -
[2019-01-05 22:03:04][DEBUG] : Topic: ->Abeille/Ruche/IEEE-Addr<- Value ->00158d0001ee04b7<-
[2019-01-05 22:03:04][DEBUG] : IEEE-Addr; =>ffffffffffffffff<= ; IEEE non valable pour un equipement, valeur rejetée: Ruche:  =>ffffffffffffffff<=
[2019-01-05 22:03:04][DEBUG] : -
[2019-01-05 22:03:04][DEBUG] : -
[2019-01-05 22:03:04][DEBUG] : Topic: ->Abeille/Ruche/PAN-ID<- Value ->f867<-
```

**Comment by KiwiHC16** [comment]
Note dans le code
ffffffffffffffff remonte avec les mesures LQI si nouveau equipement.

**Comment by KiwiHC16** [comment]
Test en envoyant Abeille/Ruche/IEEE-Addr -> ffffffffffffffff à mosquito

```
[2019-01-09 22:53:13][DEBUG] : Topic: ->Abeille/Ruche/IEEE-Addr<- Value ->ffffffffffffffff<-
[2019-01-09 22:53:13][DEBUG] : IEEE-Addr; =>ffffffffffffffff<= ; IEEE non valable pour un equipement, valeur rejetée: Ruche:  =>ffffffffffffffff<=
```

**Comment by KiwiHC16** [comment]
Quelle version de zigate ?
Wifi ou TTL ?
Quelle version d'Abeille ?
As tu un equipement Xiaomi que tu souhaites associé et qui ne s'associe pas ? (Si tu avais un capteur de porte de forme rectangulaire cela serait top).

**Comment by StephDiplo150** [comment]
Zigate TTL 3.0e
Abeille version du 18/12
Les 2 équipements qui se sont inclus sont les capteurs de d'ouverture de porte (un rond et un carré). Dans les équipements que je n'arrive pas à inclure, j'ai :
Sonde de température
Détecteur de mouvement
Interrupteur sans neutre (1 et 2 boutons)

**Comment by KiwiHC16** [comment]
Est ce que tu as des messages d'erreur CRC dans ton log AbeilleParser ?

**Comment by StephDiplo150** [comment]
Non. Je n'ai que ça

```
AbeilleParser 2019-01-10 18:16:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-01-10 18:16:15[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-01-10 18:16:16[DEBUG];type; 8015; (Abeille List)(Processed->MQTT) Payload: 009f9f00158d0001d3a1180077010F4a00158d0001a1e66a009f00
AbeilleParser 2019-01-10 18:16:16[DEBUG]Nombre d'abeilles: 2
AbeilleParser 2019-01-10 18:16:16[DEBUG]type: 8015 (Abeille List) Abeille i: 0; ID : 00; Short Addr : 9f9f; IEEE Addr: 00158d0001d3a118; Power Source (0:battery - 1:AC): 00; Link Quality: 119
AbeilleParser 2019-01-10 18:16:16[DEBUG]type: 8015 (Abeille List) Abeille i: 1; ID : 01; Short Addr : 0F4a; IEEE Addr: 00158d0001a1e66a; Power Source (0:battery - 1:AC): 00; Link Quality: 159
```

**Comment by KiwiHC16** [comment]
Peux tu regarder si le dernier post dans #533 est la solution a ton probleme. Mettre == au lieu de =.

**Comment by StephDiplo150** [comment]
Effectivement, j'ai =. Pourtant, j'ai la version du 18/12.
J'ai modifié le fichier. Je dois redémarrer le démon ?

**Comment by StephDiplo150** [comment]
Par contre, ça ne résout pas le problème d'inclusion

**Comment by KiwiHC16** [comment]
oui il faut redemarrer le demon.
Non ca doit juste resoudre le proleme des fffffffffff.

**Comment by StephDiplo150** [comment]
Oui les ffff ont disparu. Mais l'inclusion ne fonctionne pas. J'avais espéré que les problèmes soient liés.
Dommage.
Merci pour la correction

**Comment by StephDiplo150** [comment]
C'est tout bon. A force d'investiguer, j'ai fini par comprendre. Ce n'était ni un problème de pluggin, ni de zigate.
Désormais tout est de nouveau opérationnel.
Merci pour ton aide

**Comment by StephDiplo150** [comment]
Oui mais j'ai un peu honte 😁
La semaine dernière, j'ai déplacé un meuble. Apparemment, il empêche la clé de communiquer correctement avec les équipements.
Ce qui est vicieux, c'est que les problèmes de communication n'ont pas été visibles tout de suite, donc je n'avais pas fait le rapprochement.
Le meuble a retrouvé sa place d'origine, et tout est rentré dans l'ordre.
Encore merci et désolé de t'avoir dérangé

**Comment by KiwiHC16** [comment]
Y a pas de honte et ca peu servir a quelqu'un qui se retrouve dans la meme situation.
Merci pour le partage.
