### ISSUE TITLE
@oufman, clef zigate qui ne fonctionne pas.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#538]
Sur Plugin Zigate
Hello, je parle de la clé Zigate qui n'as jamais fonctionné chez moi.

Le fournisseur de la clé dis que ça viens pas de la clé mais du plug-in et ici on me dit que c'est pas le plug-in, mais que la clé n'est pas détectée.

Du coup j'ai mis 60euro à la poubelle.
Bonjour @oufman,
Je fais le dev du plugin Abeille, on peut essayer de résoudre ton problème.
Si tu le souhaites j'ouvre une "issue" dans github et on troubleshoot ensemble.
@KiwiHC16

**Comment by KiwiHC16** [comment]
Bonjour @oufman,
Peux tu me donner les informations de base:
- version HW de ta zigate
- version SW de ta zigate
- Type de module USB

**Comment by oufman** [comment]
Salut,

Alors la version du FW est le 3.0E
Le module : USB vers TTL D-SUN, celui livré avec.
La version HW de la clé je ne vois pas trop où le trouvé. Elle date de juillet.
J'ai un autocollant (pastille verte) collée dessus.

**Comment by KiwiHC16** [comment]
Ok,
Comment as tu fais la programmation du firmware 3.0.E ? Qu'elle procédure ?

**Comment by oufman** [comment]
J'ai suivi cette procédure à la lettre : https://zigate.fr/wiki/mise-a-jour-de-la-zigate/

Et tenté plusieurs fois.

**Comment by KiwiHC16** [comment]
As tu bien fait l'étape 7:
"Cliquez enfin sur « Erase EEPROM » puis « Complete EEPROM » si c’est votre première utilisation de la ZiGate."

**Comment by oufman** [comment]
Oui oui, ;) à la lettre.

J'ai même essayé depuis 2 PC différents, les ports USB différents.

**Comment by fensoft** [comment]
regarde déja si le port apparait sous linux/jeedom avec dmesg. si  je comprend bien, tu le vois sous windows mais pas linux. donc le pb n'est ni la clé ni le plugin mais plutot ton install

**Comment by oufman** [comment]
Elle apparait bien dans la liste des périphériques disponible quand je veux choisir le port.

**Comment by fensoft** [comment]
autant pour moi alors. par contre peut-être que c'est du a un hub usb pas assez alimenté (ou au raspberry lui même pas assez alimenté = led rouge). essaie de brancher en direct et/ou d'y mettre un hub usb alimenté (j'ai eu des problèmes avec ça justement)

**Comment by oufman** [comment]
Merci pour ton aide.
Alors j'utilise un Intel NUC, je suis branché en direct, par contre je te l'accorde j'ai beaucoup d'équipement USB, j'ai le dongle Zwave, Edisio, RFplayer, modem USB, et la Zigate, par contre pour les plus gourmand j'utilise justement un hub USB alimenté.

**Comment by fensoft** [comment]
pas de problèmes avec un NUC, l'alim est sur-dimensionnée là dessus. pas d'autres idées, je laisse @KiwiHC16 regarder avec toi :)

**Comment by oufman** [comment]
Merci quand même pour ton aide.

Moi personnellement je n y comprends plus rien... juste que je suis vraiment pas content de ce produit.

**Comment by KiwiHC16** [comment]
Sur ton NUC tu fonctionnes en Linux ?
que donne un ls -l /dev/ttyUSB*

**Comment by oufman** [comment]
Oui sous Debian :
Voillà le résultat :
crwxrwxrwx 1 root dialout 188, 0 jan 10 15:20 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 jan 10 09:36 /dev/ttyUSB1
crwxrwxrwx 1 root dialout 188, 2 jan 10 15:20 /dev/ttyUSB2
crwxrwxrwx 1 root dialout 188, 4 jan 10 09:36 /dev/ttyUSB4
crw-rw---- 1 root dialout 188, 5 jan 10 15:19 /dev/ttyUSB5

**Comment by oufman** [comment]
Oui oui j'ai prévenu ;) J'ai quasi tout les dongle, mais j'ai essayé sans tout ce monde, j'ai le même problème.
Debian 9, (4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64)
Install direct sans VM.

lsusb :
Bus 003 Device 002: ID 8087:8000 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:07da Intel Corp. 
Bus 001 Device 003: ID 0658:0200 Sigma Designs, Inc. 
Bus 001 Device 017: ID 12d1:1003 Huawei Technologies Co., Ltd. E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem
Bus 001 Device 018: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 016: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 015: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 001 Device 014: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 020: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Il est sur le ttyUSB0 si je me fie à Jeedom.

**Comment by oufman** [comment]
![capture d ecran 2019-01-10 a 15 31 25](https://user-images.githubusercontent.com/46557902/50975034-d6cb5d00-14ec-11e9-9815-5330bca67ae6.png)

**Comment by KiwiHC16** [comment]
Bus 001 Device 015: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 001 Device 020: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

Pourquoi 0, tu as aussi 5 ?

**Comment by oufman** [comment]
Sauf erreur c'est le dongle Edisio en 5

**Comment by KiwiHC16** [comment]
Si tu fais un 

stty -F/dev/ttyUSB0 115200
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyUSB0

Est ce que la zigate se met a clignoter ?

**Comment by oufman** [comment]
Sans la Zigate : 
Bus 003 Device 002: ID 8087:8000 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:07da Intel Corp. 
Bus 001 Device 003: ID 0658:0200 Sigma Designs, Inc. 
Bus 001 Device 017: ID 12d1:1003 Huawei Technologies Co., Ltd. E220 HSDPA Modem / E230/E270/E870 HSDPA/HSUPA Modem
Bus 001 Device 018: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 016: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 015: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 001 Device 014: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Autant pour moi c'était l'inverse, c'était bien le 5 la ZiGate
Le ControllerD et lié à celui de Edisio

**Comment by KiwiHC16** [comment]
Alors que donne un

stty -F/dev/ttyUSB5 115200
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyUSB5

Est ce que la zigate se met a clignoter ?

**Comment by oufman** [comment]
Il est sensé clignoter longtemps ? Je l'ai pas à côté le NUC, il est dans l'armoire de brassage.

Car là j'ai lancé mais rien

**Comment by KiwiHC16** [comment]
Disons 2 minutes, je ne sais plus mais qq chose comme ca.
Sauf que la j'ai un doute car le reseau zigbee n'est pas démarré.

**Comment by KiwiHC16** [comment]
Je suppose que tu as arreté tout process sur ce port.
fuser /dev/ttyUSB0 ne retourne rien.

Alors Ouvre deux terminaux. 
Lancer la commande dans un terminal (Ecoute):

cat /dev/ttyUSB5 | hexdump -vC

Dans un second terminal envoiyez la commande

stty -F/dev/ttyUSB0 115200
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyUSB5

Dans le premier terminal (Ecoute) vous devriez voir passer du traffic comme:

www-data@Abeille:~/html/log$ cat /dev/ttyUSB0 | hexdump -vC
00000000  01 80 02 10 02 10 02 15  77 02 10 bb 02 10 49 02  |........w.....I.|
00000010  10 03 01 80 02 10 02 10  02 15 70 02 10 bc 02 10  |..........p.....|

**Comment by oufman** [comment]
Aucun mouvement sur le terminal écoute

**Comment by KiwiHC16** [comment]
AUrais tu un autre convertisseur TTL-USB en stock ?

**Comment by oufman** [comment]
J'en ai un mais c'est pas le même modèle je vais essayer de faire les branchements de la clé avec des câbles dupont pour reprendre les bonnes valeurs

**Comment by KiwiHC16** [comment]
Quand tu as fais la programation de la zigate:
- tu utilisais ce meme converitsseur ?
- apres programmation, est ce que le soft relis la zigate pour vérifier la bonne programmation ?

Le firmaware que tu a recuperé as t il le bon MD5 ? (Il y a eu plein de probleme de download).

**Comment by KiwiHC16** [comment]
câbles dupont: ok super je n'osais te demandé mais je vois que tu maîtrises.
Moi je suis en FTDI et nickel.

**Comment by oufman** [comment]
Oui j'ai beaucoup de matos à la maison :) je travail avec du Espeasy, my sensor, etc. du coup j'ai pas mal

**Comment by oufman** [comment]
J'ai fait les branchement mais pas mieux

**Comment by oufman** [comment]
![capture d ecran 2019-01-10 a 15 59 00](https://user-images.githubusercontent.com/46557902/50976596-adaccb80-14f0-11e9-8217-ccc8980843b6.png)

**Comment by KiwiHC16** [comment]
my sensor j ai laissé tombé depuis que je suis zigbee/zigate.
Espeasy: https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md#wifi

**Comment by oufman** [comment]
Joli le montage

**Comment by KiwiHC16** [comment]
Bon alors je te propose de repartir de 0 par la programmation de la zigate.
As tu un windows 7 ou 8 dans le coin ?

**Comment by oufman** [comment]
Pas sous la mains malheureusement, ma VM windows 7 est morte, et les autres machines sont sous mac ou win10

**Comment by oufman** [comment]
Je viens de démarrer un vieux portable, c'est bon il est sous win7, du coup tu as une procédure pour flasher ?

**Comment by KiwiHC16** [comment]
Super, j'ai aussi un Win7 ca évitera les problèmes.
Il faut que tu installes l'IDE NXP et probablement le SDK.
Je te retrouve les liens tout de suite.

**Comment by oufman** [comment]
Merci vraiment sympa de m'aider

**Comment by KiwiHC16** [comment]
Il est probable que tu doives ouvrir un compte chez NXP. Ensuite sur la page:https://www.nxp.com/products/wireless/proprietary-ieee-802.15.4-based/zigbee/zigbee-3.0:ZIGBEE-3-0
Recuperes JN-SW-4141 et JN-SW-4170 et fais l'installation.

**Comment by oufman** [comment]
Aie je regarde l'heure et je vois que je dois partir...
Je vais installer NXP, et le SDK, du moins je vais essayer le portable est vraiment vieux :D 

Ensuite que propose tu ? Tu as une procédure ? ou un lien ?

**Comment by KiwiHC16** [comment]
Apres programmation. Il faut que je te trouve une doc. Sinon je te fairais les captures d écrans.
Je falsh souvent pour le devdonc pas un soucis.
A+

**Comment by oufman** [comment]
Merci encore, je veux bien, mais je suis pas très doué en prog. après pour faire des tests et autre je veux bien aider, j'ai beaucoup de matériel, et j'aime faire évoluer mon install, donc si je peux aider, avec plaisir, mais faut effectivement que ça marche chez moi.

Merci encore, je te recontacte dès que c'est tout bon, mais je penses que ça sera demain, je rentre pas avant un bon moment aujourd'hui.

Belle suite de journée et encore merci.

**Comment by KiwiHC16** [comment]
J'ai une doc en stock:
https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md#zigate-backuprestore

Chapitre restore. Dans la capture d'ecran le radio button "Load EEPROM" est choisi. Pour toi, il faut choisir "Erase EEPROM" et bien sure dans file mettre le bon bin.

Ca va programmer puis relire pour verifier que le programation est bone.

Tiens moi au courant.

**Comment by oufman** [comment]
Merci pour la doc, et pour toutes tes informations !!!
Et un grand merci encore ! Car tout fonctionne, enfin !!!!!

Avec ta méthode j'ai reflasher en 3.0d et ça à fonctionné directement.
J'ai pu synchro mon 1er périphérique Zigbee de Xiaomi, directement depuis ma clé Zigate.

Encore un grand merci.
