### ISSUE TITLE
Vérifier remontée batterie Gradateur Ikea.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#545]
https://github.com/Koenkk/zigbee2mqtt/issues/792

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by tcharp38** [comment]
Plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
