### ISSUE TITLE
Demon root

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#55]
ps -ef | grep Abeille et je vois les demons en root du fait du sudo probablement. Pas unr tres bonne idée. Il faudrait qu'ils soient www-data.

**Comment by edgd1er** [comment]
oui, c’était pour éliminer les pbs de droits quand rien ne marchait,  c'est une ligne a changer dans le lancement des ( system::getsudocmd() oiu quelque chose approchant)

**Comment by KiwiHC16** [comment]
Peut être qu'il faudra faire un ajout de www-data dans le group dialout dans l installation des dependances

**Comment by edgd1er** [comment]
A tester, commit d61c4c8

**Comment by KiwiHC16** [comment]
Super avec ma derniere correction sur les tiennes ca semble être ok.
