### ISSUE TITLE
System @soyann qui flash

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#552]
un Jeedom monté sur une VM sur mon Synology (via Virtual Machine Manager)
d'une Zigate USB.
hier ça plantait toutes les 10-15 min
Pas de log

Petite précision: visiblement il faut un reboot physique de la clé pour la faire repartir (le fait de simplement la démonter de la VM ne fait arrêter le stroboscope), de plus, elle est restée toute la nuit connectée en usb mais non montée sur JD, et elle ne s'est emballée, donc pour moi, c'est bien un problème avec ton plugin (ou firmware).

**Comment by KiwiHC16** [comment]
Alors qq questions pour commencer, si tu as:
- Version la ZIGate ?
- version d'Abeille ?
- OS qui fait tourné Jeedom ?

**Comment by KiwiHC16** [comment]
Je viens de finaliser ma machine toute belle toute neuve, juste avec ton plugin dessus, et voilà ce que ça dit quand je lance les dépendances et le démon (oui, j'ai bien renseigné la clé dans Abeille Serial Port et sauvegardé):
```
2019-01-15 09:55:17	Abeille	Erreur sur la fonction deamon_start du plugin : The client is not currently connected.	
2019-01-15 09:55:12	Abeille	The client is not currently connected.	
2019-01-15 09:55:05	Abeille	Erreur sur la fonction cron du plugin : The client is not currently connected.	
2019-01-15 09:52:31	Abeille	L installation des dependances est en cours, n oubliez pas de lire la documentation: https://github.com/KiwiHC16/Abeille/tre ... umentation	
2019-01-15 09:52:31	Abeille	Attention : installation des dépendances lancée	
2019-01-15 09:52:03	Abeille	Erreur sur la fonction cron du plugin : Class 'Mosquitto\Client' not found
```

(le message de 09:52/03 était à l'activation du plugin)

J'ai aussi noté sur ma machine en prod une perte d'accès de 2-3 minutes à chaque fois que je lançais les dépendances de ton bébé (et remarchait après comme par miracle, juste avec un Unknown error en tête de page)

**Comment by KiwiHC16** [comment]
Alors qq questions pour commencer, si tu as:

Version la ZIGate ?
version d'Abeille ?
OS qui fait tourné Jeedom ?
Peux tu me partager une capture d'ecran de l'etat des dependances et du demon d'abeille dans jeedom ?

Il faut qu'on prenne les sujets un par un sinon on ne va pas y arriver. Je te propose, premier sujet faire tourner Abeille.

**Comment by KiwiHC16** [comment]
Version la ZIGate ? 3.0f
version d'Abeille ? 15-01-2019 (sur la nouvelle machine), 18-12-2018 sur l'autre
OS qui fait tourné Jeedom ? Debian-9,6,0 sur la nouvelle, 9,5,0 sur celle en prod

Bon, je viens de voir que finalement, le démon est lancé... et ma clé fait déjà gyrophare :(
Pourtant, on ne peut plus propre et neuf comme installation

**Comment by KiwiHC16** [comment]
Zigate 3.0.f est une pré-release que je n'ai pas moi-même testée. Perso j'ai une pre-pre release.
Si la zigate part en girophare, le probleme est certainement dans le firmware.
Comment as tu flashé la zigate ?

**Comment by Soyann** [comment]
Ca y est, j'ai pu créer mon compte :p
J'ai flashé ma zigate en suivant les conseilles lu sur le forum, via NXP JN51xx Flah Programmer 1.8.9 sur un windows 7 64 bits, et ai utilisé le fichier suivant: https://github.com/fairecasoimeme/ZiGate/blob/v3.0f/Module%20Radio/Firmware/src/ZiGate/Build/bin/ZiGate_3.0f_pre_release.bin

**Comment by KiwiHC16** [comment]
Ok alors tu ne serais pas le premier avec des problemes de flash.

Peux tu regarder la reponse/solution du cas #538 et voir si tu peux faire le flash de la zigate.

**Comment by Soyann** [comment]
Ca y est, clé remise en 3.0e
J'en profite pour désactiver le plugin Abeille pour passer la mise à jour d'hier (même sans la clé mais juste démarré, ma machine en prod ne voulait digérer la mise à jour, malgré un message [END UPDATE SUCCESS] )
Wait and see...

**Comment by Soyann** [comment]
Bon, ça continue (en moins pire): remis en place de la clé sur ma machine de test: instantanément le démon passe en OK. Par contre, mes équipements toujours en "Time Out Last Communication"
Inclusion d'un capteur de température: la procédure se passe comme il faut, mais le capteur toujours en "Time Out Last Communication". Redémarrage des dépendances: toujours ma perte de communication avec Jeedom pendant quelques minutes... 
2019-01-15 11:37:04 | Abeille | Erreur sur la fonction cron du plugin : The client is not currently connected. |  
-- | -- | -- | --
  | 2019-01-15 11:36:25 | Abeille | The connection was lost. |  
  | 2019-01-15 11:36:06 | Abeille | L installation des dependances est en cours, n oubliez pas de lire la documentation: https://github.com/KiwiHC16/Abeille/tree/master/Documentation

Puis redémarrage du démon:

2019-01-15 11:41:02 | Abeille | Erreur sur la fonction deamon_start du plugin : The client is not currently connected. |  
-- | -- | -- | --
  | 2019-01-15 11:40:56 | Abeille | The client is not currently connected.

**Comment by Soyann** [comment]
Si je désactive Abeille et remet Zigate, le plugin me dit que je suis bien en 3.0e (info que je n'ai pas trouvé dans Abeille). Le plugin démarre sans broncher

**Comment by KiwiHC16** [comment]
Pourquoi fais tu l'installation des dépendances ? Il faut le faire une fois seulement à l'installation du plugin. Ensuite il n'y a pas besoin d'y toucher. L'instalaltion des dépendances provoque un redemarrage apache (je sais c est pas top mais je n ai pas mieux pour l instant) et ca peut expliquer ta perte de comme sur l interface graphique.

Par la suite, il faut uniquemnet faire des redémarrages de demon et on ne touche jamais aux dépendances.

Les time out ne disparaitront quapres les premiers echnages avec les équipements, ca peut prendre une heure. Sur temp xiaomi, appui court sur bouton côté et rafraichi la page timeout et ce doit etre ok.

**Comment by KiwiHC16** [comment]
"Si je désactive Abeille et remet Zigate, le plugin me dit que je suis bien en 3.0e (info que je n'ai pas trouvé dans Abeille). Le plugin démarre sans broncher":

=> l'info est sur l objet ruche.

**Comment by KiwiHC16** [comment]
As tu effacé la EEPROM lors du flash ?

**Comment by KiwiHC16** [comment]
Si tu veux ente midi 30 et 1h30 je peux me connecter sur ta machine.

**Comment by Soyann** [comment]
Noté :)
Oui, j'ai bien tout effacé (dans l'ordre: Program, puis Erase EEPROM, puis complete EEPROM). Tu peux te connecter qud tu veux, je bouge pas

**Comment by KiwiHC16** [comment]
Dis moi en MP comment je fais.

**Comment by Soyann** [comment]
suite à nos échanges privés, voici le contenu de AbeilleParser pour l'ajout de la Hue LCT015:



```
AbeilleParser 2019-01-15 14:04:06[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-01-15 14:04:07[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 10
.....
[2019-01-15 14:10:04][DEBUG] : Mosquitto: Log level: 16 Message: Client AbeilleParser sending PINGREQ
[2019-01-15 14:10:04][DEBUG] : Mosquitto: Log level: 16 Message: Client AbeilleParser received PINGRESP
```

**Comment by KiwiHC16** [comment]
;-( 
infos pas dans le log.

**Comment by Soyann** [comment]
Hello,

Nouvelle journée, nouvelle aventure! 
Hier, suite à nos essais, j'ai remis en place les ampoules (donc fait quand même une coupure de courant), et donc m'attendais à devoir refaire une inclusion, mais que nenni: elles sont restées dans le système comme si de rien n'était!
De plus, j'ai été forcé en fin de soirée à faire un reboot sauvage de ma VM qui était devenu instable. (perte complète de Z-Wave, impossible d'éteindre ou redémarrer Jeedom par les menus... Je tiens à préciser que ma machine était vraiment stable et ne rencontrait aucun bug avant le début de semaine) Suite à ça je m'attendais au pire, mais non, tout est reparti comme en 40 (j'ai simplement remarqué que tous mes objets apparaissaient en doublon dans la table des nœuds).

Par contre, je viens de m’apercevoir que tous mes équipements Abeille sont en "Time Out Last Communication" depuis 11h (y compris la ruche), alors que je n'ai absolument pas eu le temps dans la journée de me pencher sur ma domotique. Ce qui est étrange, c'est que les scénarios de mes ampoules fonctionnent toujours... (par contre les modules sur batterie sont effectivement injoignable)

Une idée? (Abeille v01-15)

Au passage: je note que ma VM consomme beaucoup plus de ressources possesseur depuis hier (je dirais qu'on est passé en gros de 7 à 15% dans Virtual Machine Manager; je dis hier, mais je n'avais pas vérifié depuis la réception de la Zigate), penses-tu que cela vient du mode debug activé? de ton plugin? de la clé (ou une incompatibilité entre le module et le Syno)? d'un plantage général en préparation?

En te remerciant d'avance

**Comment by KiwiHC16** [comment]
Salut,
Oui les logs peuvent certainement augmenter la charge CPU.
Si tu es sur la derniere stable d'Abeille, il est possible que la charge ai augmentée car j'ai enlevé des sleep mais sur ma machine je n'ai rien vu de particulier, aucun changement.

Si tu as des reboot et des coupure de jus, tu ne verras pas tout de suite le probleme. Les equipements sur secteur ne sont pas perdu. Le probleme apparait quand un equipement sur batterie Xiaomi se reveille (toutes les heures disons) et qu'il se fait jeter. Alors apres 2h il tombe en timeout.

Je n'ai pas d'experience syno mais la gestion des ports dans les VM n'est pas simple et source a probleme. Comme dans ton cas l'autre jour. Tu peux "réglé" ce soucis en passant la zigate en wifi.

La mienne est sur batterie et wifi et tourne comme une horloge.
https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md#wifi

**Comment by Soyann** [comment]
Yop
Me voilà revenu de mon périple parisien du jour (vive les réunions!)
Merci pour ces infos. Peux-tu me dire comment faire repartir la ruche (qui est en timeout) pour que je puisse inclure de nouveau mes pitis capteurs?
Merci d'avance

**Comment by KiwiHC16** [comment]
As tu essayé de redémarrer le demon ?

**Comment by Soyann** [comment]
Ah ben tout simplement :p C'est parfait (enfin ça sera parfait quand ces problèmes de firmware seront solutionnés, et qu'on pourra tout débrancher et faire des redémarrages sans broncher)
Merci beaucoup :)

**Comment by KiwiHC16** [comment]
Ok, super.
Peut on clore cette issue ?
Si tu as d'autre soucis on la rouvreri ou on en ouvrira une plus spécifique.
Ok pour toi ?
