### ISSUE TITLE
Ajouter les commandes scenes a tous les modeles

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#557]

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Commande Info Template: 
- Group-Membership: contient  -AAAA-BBBB
- Scene-Membership:

**Comment by KiwiHC16** [comment]
[2021-01-29 02:33:19][DEBUG] : message(topic='Abeille1/3EFE/Group-Membership', payload='-AAAA-BBBB')

**Comment by tcharp38** [comment]
Developpement des "scene" arreté coté Abeille. Ne fait pas de sens face aux scenaris Jeedom.
