### ISSUE TITLE
Desactivation du plugin

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#56]
![capture d ecran 2018-01-31 a 10 07 10](https://user-images.githubusercontent.com/8549674/35614261-be182302-066e-11e8-8c60-6a221b957851.png)

**Comment by edgd1er** [comment]
Dans mon dernier commit, j'ai amelioré l'expérience utilisateur ( visu sur le progression de l'installation, popup install et remove plugin, la ruche a son icone correctement mise)
Je n'ai pas fait de pull request car il reste un pb génant. J'ai trop de daemon parser/reader/cmd, du coup, ça ne traite pas bien... mais ça avance.

**Comment by KiwiHC16** [comment]
Super j attends le pull et je vais ajouter des objets dans JSON. Je ne touche pas à la partie Demon.

**Comment by edgd1er** [comment]
A trster, le commit d61c4c8 doit corriger le pb

**Comment by KiwiHC16** [comment]
Maintenant on a meme un petit message pour dire que le plugin est de installé.
Je clos le point.
