### ISSUE TITLE
Problème inclusion / Probleme LED Bleu Off

### ISSUE THREAD

**Issue by pasoad** [KiwiHC16/Abeille#562]
Bonsoir,

J'essaye depuis plusieurs jours d'intégrer une ampoule ikea Tradfri 1000 lumen. (je précise que c'est ma 1ère inclusion)

Quand j'active le mode "Inclusion" le message "Mode inclusion demandé. La zigate doit se mettre à clignoter." apparaît. Mais la lumière de ma Zigate ne clignote pas et je ne vois pas l'ampoule apparaître dans la liste de mes objets...

Quelqu'un a-t-il déjà eu le problème ? Peut-être une piste pour une solution ?

Merci d'avance pour vos réponses :)

**Comment by KiwiHC16** [comment]
Bonjour @pasoad,
Si ta zigate ne clignote pas ce n'est même pas la peine d'aller plus loin.
Pour t'aider il me faut des informations de base.
Peux tu me dire si c'est une zigate USB ou Wifi ?
Quel firmware est sur ta zigate ? (As tu flashé la zigate si oui avec qu'elle méthode et quel binaire)

**Comment by pasoad** [comment]
Merci pour ta réponse @KiwiHC16,

C'est une Zigate USB qui date du projet sur kickstarter (oui, j'ai mis longtemps avant de commencer à l'utiliser ;) )

J'utilise le firmware 3.0e que j'ai flashé à l'aide des instructions trouvées sur [https://zigate.fr/wiki/mise-a-jour-de-la-zigate/](url)

D'abord sur windows (J'ai recommencé la manip une 10ene de fois) en essayant de changer des paramètre comme baisser la vitesse d'écriture et effacer l'EEPROM, puis sur Linux, mais je n'ai pas encore réussi à arriver au bout de la méthode...

**Comment by KiwiHC16** [comment]
Perso je n'ai jamais utilisé cette méthode donc je ne sais pas trop comment elle fonctionne.
J'utilise l'IDE de NXP comme présenté dans cette vidéo:
https://youtu.be/AWJDQpP-AF4

et regardes aussi la fin de la discusison https://github.com/KiwiHC16/Abeille/issues/538

Apres tu devrais avoir la zigate avec une led qui clignote quand tu demandes une inclusion.

**Comment by pasoad** [comment]
J'ai passé la soirée d'hier à installer l'IDE de NXP (avec un peu de mal, mais ça à fini par fonctionner ;) ) en lisant attentivement la discussion #538 et la vidéo que tu m'as indiqué.

Donc, pour résumer, le flashage c'est bien déroulé jusqu'au bout mais aucun changement au niveau de la lumière rouge qui doit clignoter...

Je commence tout doucement à désespérer :(

**Comment by pasoad** [comment]
J'ai bien coché Erase EEPROM.

Chez moi, la lumière à toujours été rouge mais il me semble que effectivement, au fil de mes lectures, j'ai cru voir qu'elle s'allumait en bleu normalement...

Voici une photo de la clé branchée : 
![img_20190120_145237](https://user-images.githubusercontent.com/46829490/51440125-c15feb00-1cc3-11e9-86f7-061197b78a2c.jpg)

Et voici une capture d'écran de la page de config : 
![capture d ecran du 2019-01-20 14-54-50](https://user-images.githubusercontent.com/46829490/51440111-99708780-1cc3-11e9-8ddb-1cac83cb8d54.png)

**Comment by KiwiHC16** [comment]
On ne parle pas de la même led. Ici tu parles de la LED du module TTL qui est rouge. Elle doit/peut clignoter quand il y a un dialogue entre la plugin/jeedon et la zigate.
La led bleue est sur la zigate. Probablement au dos de ta photo car je ne la vois pas sur ta photo.

**Comment by KiwiHC16** [comment]
Regardes la photo sur #563

**Comment by pasoad** [comment]
Alors voici une autre photo : 
![img_20190120_151542](https://user-images.githubusercontent.com/46829490/51440401-ebff7300-1cc6-11e9-9f87-0e6cce2d4e20.jpg)

**Comment by KiwiHC16** [comment]
Si la LED ne s'allume pas en bleu, je ne vois que ces possibilités, soit:
- la zigate est mal connectée
- la zigate est HS
- la programmation ne s'est pas bien faite

**Comment by pasoad** [comment]
J'ai connecté la Zigate en direct et aussi via une rallonge USB sur les 4 ports USB du raspberry donc je ne pense pas que ce soit la connexion qui foire :(

J'ai remarqué que quand je fais un "Refresh" à partir du soft Beyondtudio, la lumière bleu clignote une fraction de seconde puis s’éteint aussitôt. Pareil quand je clique sur "Inclusion" dans le plug-in Jeedom...

Les 2 articles dont tu parles dans la discussion #563 remplacent-ils complètement ma Zigate actuelle ?

Je vais me rapprocher du concepteur pour voir ce qu'il en pense... si elle est HS ou autre.

Encore merci pour tous ces conseils :)

**Comment by pasoad** [comment]
Je viens de m’apercevoir qu'il y à une différence entre ton BeyondStudio et celui que j'ai installé sur mon ordi. Sur ta vidéo, tu cliques sur le menu "Devices" puis sur "Program Device".

Chez moi, ce menu s'appelle "JN51xx" Peut-être ais-je foiré quelque chose lors de l'installation du soft ?

![sans titre](https://user-images.githubusercontent.com/46829490/51502904-961af000-1dd8-11e9-816c-50e712ceb246.png)

**Comment by KiwiHC16** [comment]
Es tu sur un windows 7 ?
Je sais que des personnes ont eu des soucis avec windows10.

Mais visiblement le soft est bien programmé, la verification se passe bien (ta capture d écran).
As tu bien le message d'effacement de l'EEPROM en fin de programmation ?

Je n'ai pas de zigate vierge pour essayer une programmation complete. Peut etre que le led bleu ne s'allume pas si tu n'as pas démarrée le réseau zigbee, juste une idée. As tu démarré le réseau zigbee ?

**Comment by KiwiHC16** [comment]
Quel binaire charges tu ?
Il y a deux familles de JN51xx, il y a les JN517x et le JN516x, nous nous utilisons les JN516x, vérifie que c'est bien ca que tu utilises dans les differentes fenêtres. Le SDK que tu as installé, c'est bien celui pour JN516x ?

**Comment by pasoad** [comment]
Je faisais la manip sur Windows 10 au début. Mais j'ai installé une VM Windows 7 et toujours le même problème... 

Effectivement, je n'ai pas de message à la fin du processus. Une fois le "flashage" finis, la fenêtre se ferme et c'est tout.

Petite précision, pour que cela fonctionne je dois obligatoirement changer le "baud rate" <=115200 sinon j'ai un message d'erreur : 

![virtualbox_win quantum_22_01_2019_22_05_05](https://user-images.githubusercontent.com/46829490/51568543-413fae00-1e9a-11e9-80fd-4966e9d0f0ec.png)

Oui, je clique bien sur démarrer le réseau zigbee.

Le SDK que j'utilise est celui que j'ai trouvé en tapant JN516x dans le moteur de recherche du site nxp.com

Voici ce que j'utilise : 

NXP                JN-SW-4141 BeyondStudio for NXP v1308.exe
SDK                JN-SW-4163 IEEE802.15.4 SDK v1416.exe
FIRMWARE     ZiGate_Coordinator_v3.0e.bin (aussi essayé avec ZiGate_3.0f_pre_release.bin)
DRIVER           PL2303_64bit_Installer.exe

**Comment by KiwiHC16** [comment]
NXP JN-SW-4141 BeyondStudio for NXP v1308.exe => Ok

SDK JN-SW-4163 IEEE802.15.4 SDK v1416.exe => Inconnu, devrait etre 4170 et pas 4163 je pense. En meme temps pour la programmation a partir d un bin ce n'est pas necessaire les SDK donc ne devrait pas être source de soucis.

FIRMWARE ZiGate_Coordinator_v3.0e.bin (aussi essayé avec ZiGate_3.0f_pre_release.bin) => ok

DRIVER PL2303_64bit_Installer.exe => Je ne sais pas j utilise FTDI 232 et pas PL2303 car j utilise un autre chipset.

**Comment by KiwiHC16** [comment]
Pour la programmation perso je suis en 10000000 sans soucis par contre pour l'utilisation il faut 115200.

**Comment by pasoad** [comment]
Du coup, je ne suis pas plus avancé :(

Je vais essayer de voir avec le concepteur de la Zigate et viendrai donner des nouvelles ici par la suite si jamais j'ai du nouveau.

Merci encore pour ton temps et ta patience @KiwiHC16 .

**Comment by KiwiHC16** [comment]
J'ai vu l'issue que tu as faites alors j'ai ajouté un lien.
Dans le pirer des cas, tu peux me l'envoyer, je la teste et te la renvoie fonctionnelle (si j'y parviens) mais je pense qu'Atila dans le pire des cas te proposera la meme chose.

Je clos ici comme on suis dans ZiGate.

**Comment by pasoad** [comment]
Ok, pas de soucis.

On va bien voir ce qui se dit sur l'autre issue.

Mais si je peux te l'envoyer pour que tu regarde toi même, ça me dis bien :)

**Comment by pasoad** [comment]
Bonsoir,

Juste un petit message pour dire que c'était finalement bien la zigate qui était défect.

Après échange, ça a fonctionné du premier coup !

Encore merci pour ton support @KiwiHC16.
