### ISSUE TITLE
Failed (ZigBee event codes): 04 to be decoded.

### ISSUE THREAD

**Issue by Syxxxx** [KiwiHC16/Abeille#564]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2775987/Abeille.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2775988/AbeilleMQTTCmd.txt)
[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/2775989/AbeilleSerialRead.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2775990/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
En regardant rapidement tes logs tout semble ok.

Peux tu me rappeler ton soucis (désolé de te redemander) ?

**Comment by KiwiHC16** [comment]
@Syxxxx, quel est ton soucis ?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
No answer.

**Comment by edgd1er** [comment]
Pour info, j ai eu le meme comportement en flashant le v3.0e. Bien qu aucune erreur n apparaisse, ni au flash, ni au redémarrage du plugin, le reseau ne demarre pas. J ai du reflasher les 2 zigates sur un autre pc (meme firmware flashé).

**Comment by KiwiHC16** [comment]
Abeille Parser: 

`AbeilleParser 2019-01-19 22:21:04[DEBUG]Nombre d'abeilles: 0`

`AbeilleParser 2019-01-19 22:21:19[DEBUG];type; 8024; ( Network joined / formed )(Processed->MQTT); Satus; Failed (ZigBee event codes): 04; short addr : 00; extended address : ;Channel : 0`

`AbeilleParser 2019-01-19 22:21:37[DEBUG];type; 8014; ( ìPermit joinî status response)(Processed->MQTT); Permit Join Status: 01`

Abeille/AbeilleSerial/AbeilleSerialRead logs all right.

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/74

**Comment by KiwiHC16** [comment]
Status:
0 = Joined existing network
1 = Formed new network 
128 – 244 = Failed (ZigBee event codes)

**Comment by KiwiHC16** [comment]
BDB_E_ERROR_NODE_IS_ON_A_NWK si 4 in the enum.

    BDB_E_SUCCESS,
    BDB_E_FAILURE,
    BDB_E_ERROR_INVALID_PARAMETER,
    BDB_E_ERROR_INVALID_DEVICE,
    BDB_E_ERROR_NODE_IS_ON_A_NWK,
    BDB_E_ERROR_IMPROPER_COMMISSIONING_MODE,
    BDB_E_ERROR_COMMISSIONING_IN_PROGRESS,

Looks like it is just saying I'm in a network I'm not going to start and other one. Funny enough it's its own network, so not an issue.
