### ISSUE TITLE
Problème Inclusion Volets Profalux

### ISSUE THREAD

**Issue by gubas** [KiwiHC16/Abeille#565]
Issue créée pour le suivi des problèmes sur l'inclusion des volets profalux.

Merci de donner un maximum d'informations.

@KiwiHC16 quels sont les logs à te fournir lors de l'inclusion ?

**Comment by KiwiHC16** [comment]
Bonjour,
Mettre le plugin en debug, relancer le demon et me partager le log AbeilleParser lors de l inclusion dans un premier temps.
Apres si possible le log AbeilleMQTTCmd et le log Abeille serait un plus.

**Comment by gubas** [comment]
Bonjour,

J'ai enfin pris le temps de retenter une inclusion.

Abeille me créait bien 2 objets Abeille de type inconnu.

Abeille-9eef--Type d objet inconnu (!JSON)

Abeille-db2f--Type d objet inconnu (!JSON)

A la fin de l'inclusion, la télécommande ne peut plus commander le volet que sur 30 cm du volet ?

Je te joins les 3 logs demandés.

Merci pour ton aide.


[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2799068/Abeille.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2799069/AbeilleMQTTCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2799070/AbeilleParser.txt)

@KiwiHC16

**Comment by gubas** [comment]
A noter que je sais bien sûr rétablir correctement la télécommande et l'ouverture complète des volets mais je me suis dis que c'était peut être une info intéressante.

**Comment by KiwiHC16** [comment]
Log Parser. Tout semble bien se passer du côté de l'inclusion entre le volet, la telecommande et la zigate. J'ai bien le volet qui s'annonce et la télécommande (C'est la premiere fois que j'ai ce niveau d'info pour la télécommande).

Par contre l ordre d'arrivée des infos est inversée ce qui provoque le mauvais fonctionnement.

Je ne possede pas moi même ces volets donc je peux rien tester, je les découvre en fonction des logs que vous fournissez.

```
20918a000006b4ba -> 9eef
20918a000006b4bb -> 1220 
20918a000006b4bb -> db2f (nouvelle adresse immédiatement après?!)
```
```
9eef -> "EP":"01"
```

```
9eef  -> Short Address : 9eef; Length : 22; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0200 (Shade); bitField : 00; InClusterCount : 0B OutClusterCount : 00
```
```
9eef; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0005; Data byte list : ->volet<-
```
```
db2f ->"EP":"01"
```
```
db2f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-
```
```
db2f; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0002; Data byte list : ->TS<-
```
```
AbeilleParser 2019-01-26 15:07:50[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 70; Status : 00; Short Address : **db2f**; Length : 1e; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : _0201 (Shade Controller)_; bitField : 00; InClusterCount : 03
AbeilleParser 2019-01-26 15:07:50[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2019-01-26 15:07:50[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2019-01-26 15:07:50[DEBUG]In cluster: 0015 - 
AbeilleParser 2019-01-26 15:07:50[DEBUG]OutClusterCount : 08
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0003 - General: Identify
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0004 - General: Groups
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0005 - General: Scenes
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0006 - General: On/Off
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0008 - General: Level Control
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: 0100 - Closures: Shade Configuration
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: fc20 - 
AbeilleParser 2019-01-26 15:07:50[DEBUG]Out cluster: fc21 -
```

**Comment by KiwiHC16** [comment]
Dans Abeille, je retrouve le même soucis d'ordre d'arrivée des infos. C'est du au changement fait dans le code pour essayer de gérer les équipements inconnus de facon automatique. Mais le volet de son pas encore dans la liste.

```
[2019-01-26 15:07:39][DEBUG] : Topic: ->Abeille/9eef/SimpleDesc-01-DeviceDescription<- Value ->zigbeeShade<-
[2019-01-26 15:07:39][INFO] : Recherche objet: zigbeeShade dans les objets connus
[2019-01-26 15:07:39][DEBUG] : value:zigbeeShade / trimmed value: zigbeeShade
[2019-01-26 15:07:39][DEBUG] : Template : null
[2019-01-26 15:07:39][DEBUG] : EP: 01
[2019-01-26 15:07:39][DEBUG] : Template : null
[2019-01-26 15:07:39][INFO] : objet: zigbeeShade recherché comme zigbeeShade ne peut pas etre cree completement car je ne connais pas ce type d objet.
[2019-01-26 15:07:39][DEBUG] : objet: null
```

```
[2019-01-26 15:07:39][DEBUG] : Topic: ->Abeille/9eef/0000-01-0010<- Value ->volet<-
[2019-01-26 15:07:39][DEBUG] : L objet: Abeille/9eef existe mais pas la commande: 0000-01-0010
```

```
[2019-01-26 15:07:50][DEBUG] : Topic: ->Abeille/db2f/0000-01-0010<- Value ->TS<-
[2019-01-26 15:07:50][INFO] : Recherche objet: TS dans les objets connus
[2019-01-26 15:07:50][DEBUG] : value:TS / trimmed value: TS
[2019-01-26 15:07:50][DEBUG] : Template : null
[2019-01-26 15:07:50][DEBUG] : EP: 01
[2019-01-26 15:07:50][DEBUG] : Template : null
[2019-01-26 15:07:50][INFO] : objet: TS recherché comme TS ne peut pas etre cree completement car je ne connais pas ce type d objet.
[2019-01-26 15:07:50][DEBUG] : objet: null
```

```
[2019-01-26 15:07:50][DEBUG] : Topic: ->Abeille/db2f/SimpleDesc-01-DeviceDescription<- Value ->zigbeeShade Controller<-
[2019-01-26 15:07:50][DEBUG] : L objet: Abeille/db2f existe mais pas la commande: SimpleDesc-01-DeviceDescription
```

**Comment by KiwiHC16** [comment]
J'ai suffisement d'infos pour aller voir ce qu'il se passe dans le code et trouver une solution.
Je vous tiens au courant des que j'ai du nouveau.

Si c'est "urgent" je peux vous proposer une commande pour créer le volet en attendant la correction finale.

**Comment by gubas** [comment]
Personnellement, il n'y a pas vraiment d'urgence.

Mais je veux bien tester ta "commande" pour voir déjà si ça fonctionne et surtout si ça peut t'aider pour faire la correction définitive.

Merci.

**Comment by KiwiHC16** [comment]
Fais une inclusion si pas deja faite du volet.
Supprimes les objets inconnus.
Dans les logs, ou objets inconnus recuperes l adresse courte (4 digit) des equipments.
En ssh utilises la commande:
`mosquitto_pub -t "CmdCreate/aaaa/0000-0010" -m "volet"`
Remplacer aaaa par l adresse courte. Si tu n'as pas refait d inclusion depuis les log ci dessus, l'adresse doit être 9eef.
Ca doit créer un objet Volet et tu dois pouvoir controller ton volet.

**Comment by gubas** [comment]
OK j'essaye cela ce soir.

Par contre, je comprends pas pourquoi il me fait 2 objets distincts ? (Je dirais même sur certains tests d'inclusions, il en fait 3 ?)

**Comment by gubas** [comment]
Salut,

Juste pour te dire que ça a marché nickel !

J'attends la correction avec impatience

**Comment by gubas** [comment]
OK je comprends mieux.
Merci pour infos intéressantes et surtout intelligibles pour un béotien comme moi :)

**Comment by gubas** [comment]
Tu as une idée de quand tu pourras réaliser les corrections?

C'est juste pour savoir si j'attends pour inclure mes 6 autres volets :)

**Comment by KiwiHC16** [comment]
Dans les prochains jours mais quand ? D'ici une semaine peut être.
Tu peux les inclures et si besoin de tests on fera avec un seul volet une re-inclusion qui normalement ne changera rien dans Abeille.
Comme ca tu peux des aujourd'hui les utiliser, il n y a pas de raison de te faire attendre.

**Comment by KiwiHC16** [comment]
Je viens de faire #571 donc je vais pouvoir faire les modifs pour améliorer le comportement.

**Comment by jossalison38** [comment]
bonsoir 
je vien de regarder l'avancement sur le forum de jeedom et a ma grande surprise j'ai vu que vous aviez beaucoup avancé sur le problème profalux , j'ai vu aussi que KiwiHC16 allez prochainement faire une correction sur abeille . a ce sujet pourrez tu nous prévenir quand la modif sera faite ? car j'ai 15 volet profalux a inclure et la méthode que tu a parler me prendrai trop de temp ( madame risque de voir rouge ) lol 
j'aurais deux petit question 
-pour la mise a jour faut il passer par github ou sur le stable jeedom ?
-faut il attendre la mise a jour de la zigate en 3 F ? (ses tu quand elle sortira ?)

j'attend avec impatiente les modifications pour faire des test , et je ne manquerai pas de te dire si ça marche 
un grand merci a toi pour ta réactivité et ton aide 
cordialement 
joss38

**Comment by gubas** [comment]
Bonsoir,
J'ai eu le temps ce week end de faire des tests...

J'ai pu intégrer 3 volets correctement sans trop de difficultés. (Mais tous ne remontent pas leur état et leur position ...)

Il m'en reste encore 4 ... pour ceux la, c'est très étrange ils s'incluent mais je n'arrive pas à les commander : ils font juste un petit mouvement comme lors des inclusions ...

Si vous avez une idée ?

Sinon je ressayerais de les inclure... (Je suppose qu'il faudrait les mêmes logs ?

**Comment by KiwiHC16** [comment]
Suite à #571, je viens de faire des modifs dans Abeille qui devraient faciliter les choses.

**Comment by KiwiHC16** [comment]
@Joss38, les volets Profalux fonctionnent depuis longtemps dans Abeille, mais suite à des modifications j'ai du casser des trucs qui font que cela ne fonctionne plus.
Pour ce qui est de la méthode à suivre ca va aussi dépendre ton expertise informatique. Si tu as de l'experience récupère depuis GitHub le master (regardes la doc), si tu n'as pas cette expertise attends la version stable.
Perso c'est mieux si tu es sur le master car ca me permet de tester le soft et de pas me faire perdre du temps sur des problemes de vieux softs.
Pour l aspect WAF, je n'ai pas le moindre conseil ;-)

**Comment by KiwiHC16** [comment]
@Gubas, si tu peux mettre le master, faire tes inclusions et partager le log AbeilleParser, AbeilleMQTTCmd et Abeille.

**Comment by gubas** [comment]
OK
J'ai oublié le widget des volets se créaient aussi avec un widget "genre" éclairage ... (Enfin en tout cas le logo est une ampoule et pas un volet : il y a bien sur les bouton Monter / Descendre ...)

J'essaye de faire ça un soir de cette semaine.

Pour le coté WAF : elle est assez conciliante pour mes "jouets" donc ça va :)

**Comment by KiwiHC16** [comment]
Il est fort possible que nous ayons a changer les icônes. Je n'ai pas ces volets alors je ne peux pas jouer avec. Je te laisse me guider sur les choses à faire.

**Comment by gubas** [comment]
Je me demandais : c'est mieux de supprimer l'objet dans abeille puis de reinclure ou reinclure par dessus?

**Comment by KiwiHC16** [comment]
C est mieux de supprimer puis reincluere.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

Je ne possede pas ce produit pourle tester alors si la cagnotte le permet j'en acheterai un.

**Comment by dams74** [comment]
j'attends le firm 3.0f et je remet un de mes volets sur abeille pour tests

**Comment by gubas** [comment]
Bon étrangement les volets qui ne marchaient pas (Que je n'avais pas supprimé) se sont mis à fonctionner  "tout seul" 2/3 jrs après leur inclusion.
Sauf que je n'arrivais pas à les descendre ???

Je n'ai pas encore eu le temps de refaire les inclusions ...

J'essaye de le faire ce soir.

**Comment by gubas** [comment]
J'ai ré-inclus un des volets problématiques même symptômes :

 - quand je réinitialise le volet. (Il s'inverse ?) (Je pense que ça n'a rien à voir avec Abeille :))
 - quand je le réinclu dans Abeille, il se créait mais les boutons ne font que un petit mouvement

Et aussi étrange que ça puisse paraître, je pense que dans 2/3 jours, ils vont se mettre à marcher ... (Mais pas la montée ...)

La distance à la Zigate peut avoir un impact ? (Ils sont les plus loin de la zigate)

J'ai pourtant des ampoules Ikea entre la zigate et les volets qui marchent pas.

Space ...

Voila les logs de l'inclusions.
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2842468/AbeilleMQTTCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2842470/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2842471/AbeilleParser.txt)

**Comment by cyrililo** [comment]
@gubas
Voilà exactement ma méthode d'inclusion de mes volets, si ça peut te servir ! 

1: au dos de la télécommande appuyer 5 fois sur R, attendre que le volet fasse un va et vient , dans la minute appuyer sur le bouton stop 

2: normalement tu dois pouvoir commander tes volet normalement .
Si les commandes sont inverser ( bouton monter et descendre ) appuie une fois sur F et une fois sur stop

3: ensuite tu ferme ton volet complètement.

4: depuis le plugin abeille, ruche en mode inclusion, la zigate doit clignoter.

5: appuie une fois sur R au dos de la télécommande une fois sur le bouton monter, ton volet devrait faire plusieurs va et viens pour s'annoncer.

Une fois qu'il est inclus , tu dois ouvrir et fermer ton volet deux fois avec la télécommande , a la fin de cela ton volet devrait faire encore un va et viens et tu devrais pouvoir le commander normalement depuis abeille

**Comment by dams74** [comment]
Quelqu'un a-t- il essayé d'inclure la télécommande générale?

**Comment by gubas** [comment]
@dams74 Non désolé, j'en ai pas.
@cyrililo Merci j'essayerais.
@KiwiHC16 Il y'a bien un truc que je sais faire ce sont des docs, quand j'aurais réussi à inclure tous mes volets : je produirais une documentation détaillée pas à pas sur ces inclusions de volets Profalux.

**Comment by KiwiHC16** [comment]
@gubas, la doc existante est dans le doc:
https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md

avec un chapitre Profalux: 
https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md#profalux

Tu dois pouvoir la modifier soit directement soit en faisant un PR. Elle est au format md qui est format super simple.

Et pour qu'elle s'affiche joliement il fau tla consulter à l 'adresse:
https://kiwihc16.github.io/Abeille/fr_FR/

Je vais regarder tes logs.

**Comment by gubas** [comment]
@KiwiHC16 Je l'a connais bien cette doc pour l'avoir lue et relue :D (Merci d'ailleurs)
Je voulais juste bien détailler toutes les étapes.
J'essaye de faire un PR au plus vite.

**Comment by KiwiHC16** [comment]
Parser
2d7f => "EP":"01","deviceId":"zigbeeShade Controller"
970F => "EP":"01","deviceId":"zigbeeShade"

Cmd 2d7f
{CmdAbeille/Ruche/ActiveEndPoint} => address=2d7f
{CmdAbeille/Ruche/getName} => address=2d7f&destinationEndPoint=01
{CmdAbeille/Ruche/getLocation} => address=2d7f&destinationEndPoint=01
{CmdAbeille/Ruche/SimpleDescriptorRequest} => address=2d7f&endPoint=01

Cmd 970F
On/Off/setLeveleVolet/get 0006 & 0008

Abeille 2d7f
Cmd n'existe pas - normal car pas de modele, cmd: IEEE, Shot Address, Power-Source, Link-Quality, 
Topic: ->Abeille/2d7f/0000-01-0010<- Value ->TS<-
Topic: ->Abeille/2d7f/SimpleDesc-01-DeviceDescription<- Value ->zigbeeShade Controller<-

Abeille 970F
Creation de l objet sur son nom
Puis arrivée de ZIgBee Shade


D'après les log, tout semble Ok. 

Apres la manipulation associée aux logs, qu'est ce qui fonctionne et qu est ce qui ne fonctionne pas ?

As tu fait la manip de @cyrililo (qui doit etre un calibrage je suppose) depuis ?

**Comment by gubas** [comment]
J'en profite pour partager une doc que je n'avais encore jamais trouvée ailleurs dans mes recherches "Google" :)
[Notice Globale Zoe-Zigbee.pdf](https://github.com/KiwiHC16/Abeille/files/2844378/Notice.Globale.Zoe-Zigbee.pdf)

**Comment by gubas** [comment]
@KiwiHC16 J'ai pu tester que un volet avec la manip de @cyrililo et ça fonctionne !
J'essaye de traiter les autres volets ce soir ou ce week end et je mettrais à jour la doc Profalux en PR avec toutes ces infos ...

**Comment by KiwiHC16** [comment]
Tiens moi au courant et après on essayera d'ajouter dans Abeille la télécommande.

**Comment by cyrililo** [comment]
@gubas  Cool !! En même j'ai vraiment galéré pour trouver comment il fallait faire pour que l'inclusion fonctionne correctement.

**Comment by gubas** [comment]
J'ai réussi à en rajouter 2.

1 très facilement et 1 que j'ai du réinitialiser car il voulait vraiment pas ... ?

Enfin il m'en reste plus qu'un mais bébé dort pas loin donc ça sera pour demain :)

**Comment by gubas** [comment]
J'ai réussi à inclure le dernier : RAS.
Pour moi après 2 "urgences" :

- changer les icônes pour plus que ce soit des "bulbes" ampoules.
![bulbe](https://user-images.githubusercontent.com/596670/52518993-ab0ad680-2c54-11e9-89d6-ba8c22d759e5.PNG)

- avoir des "vraies" valeurs quand à la position des volets. (Je n'ai pas compris comment c'était rafraîchit ?) Je dirais que le 100% ouvert ou fermé fonctionne à peu prés mais le reste ?

En tout cas merci à @KiwiHC16 et @cyrililo : mes volets fonctionnent :)

@KiwiHC16 : j'essaye de faire le PR pour la doc dans le week end !

**Comment by gubas** [comment]
@KiwiHC16 le PR est fait

**Comment by jossalison38** [comment]
bonsoir  je reviens vers vous car ce soir j'ai pu inclure mon premier volet maitre (cuisine ) .
j'ai eu quelque déboire mais ça a fonctionné , j'ai toute les fonction qui marche sauf la fonction stop 
j'ai essayé sur mon deuxième volet qui ce situe a proximité en mettant le plugin abeille en inclusion .
mon volet maitre fait un allez retour (mouvement ) . 
puis j'essaye d'inclure le deuxième , appuie sur R et fleche du haut , les voyant de la télécommande clignote vert , les volet font des allez retour ( les 2) mais rien ne se passe dans le plugin , pas de création du volet .
auriez vous une petit idée d'ou cela peu coincé ?
mauvaise manipulation ?
pour info a chaque appuie sur l'icone inclusion les 2 volet font des mouvement 
aussi j'ai fait la mise a jour de la zigate en 3.F final 
je vous joint les fichier abeille et abeille parser 
merci beaucoup 
cordialement 
joss38
![abeille 2eme volet](https://user-images.githubusercontent.com/47280807/52539162-4b5b1b00-2d7b-11e9-9208-5e87f675f8e0.jpg)
[Abeille 2eme volet.txt](https://github.com/KiwiHC16/Abeille/files/2849343/Abeille.2eme.volet.txt)
[AbeilleParser 2eme volet.txt](https://github.com/KiwiHC16/Abeille/files/2849345/AbeilleParser.2eme.volet.txt)

**Comment by gubas** [comment]
Salut,

Pourquoi tu parles de volet "maître"? Selon ma compréhension chaque volet est complètement indépendant.

Moi aussi lorsque j'incluais un volet tous les autres s'annonçaient. (Petit va et viens)

Tu as bien respecté à la lettre la "nouvelle doc"?

**Comment by jossalison38** [comment]
salut dans la doc il est marqué " Il est indispensable d’avoir une télécommande maître qui jouera le rôle d’interface entre le volet et la ZiGate.
et dans les docs que j'ai trouvé, il parle de coordinateur ( étape F)
je joint le fichier 
![img_20190210_0002](https://user-images.githubusercontent.com/47280807/52539762-11d9de00-2d82-11e9-90a3-a7e5e9bc7b4d.jpg)
De ce que je comprend il y a une télécommande maître ( coordinateur ) qui fait le joint entre les autre volet et la zigate , je peut me trompe  je ne suis pas spécialiste 
j'ai aussi une télécommande général zoe que j'aimerai gardé au cas ou il y est un gros  problème sur ma domotique , et que je puisse pallié a cela .
apparemment ça marche sur ce principe 
cordialement

**Comment by gubas** [comment]
Re, je suis loin d'être un spécialiste aussi lol 

Pour moi, il ne peut y avoir qu'un seul coordinateur Zigbee sur le même réseau.

Dans mon installation (Je n'ai pas de Zoé), chaque volet était relié à une telecommande. Ils n'avaient pas de liens entre eux.

Pour inclure mes volets, j'ai "juste" joué la procédure à la lettre pour chacun des volets.

Et maintenant, tous mes volets et mes télécommandes sont sur le même réseau Zigbee et fonctionnent avec Abeille.

**Comment by dams74** [comment]
Y'a-t-il un soucis avec le git?
Je ne trouve plus la doc pour associer les volet profalux à zigate

**Comment by gubas** [comment]
Elle est y est toujours. @KiwiHC16 a accepté mon PR.

https://github.com/KiwiHC16/Abeille/blob/master/docs/fr_FR/index.md

**Comment by KiwiHC16** [comment]
The user version. More pretty:
https://kiwihc16.github.io/Abeille/fr_FR/

Pour info, @gubas, the github is the source and the user version is on github.io (this is the standardisation of the doc used by Jeedom)

**Comment by gubas** [comment]
sorry for the misunderstanding

**Comment by KiwiHC16** [comment]
Je vais créer des issues spécifiques pour chaque sujet car ca devient difficile à suivre:
Télécommande simulée dans Abeille: #589
Icones sur Volet Profalux: #590
Retour volet Profalux: #591

**Comment by KiwiHC16** [comment]
@jossalisson, tu as un volet dans le réseau zigbee à l'adresse 65e5 d'apres tes logs.
As tu un volet créé dans Abeille ? Si tu regardes son "Topic Abeille" dans ses paramètres est ce à "Abeille/65e5" ? (je suppose que c est celui de la cuisine)

Il doit exister car je vois l envoie de commande vers lui comme:
CmdAbeille/65e5/setLevelStop

Je vois dans AbeilleParser un equipement à l'adresse ae93 qui n'a pas été jusqu'au bout de son intégration dans Abeille. En fait surtout je ne vois pas tout car visiblement tu as un Abeille recent qui crache trop de log. Il faut que je fasse une modif pour eviter de cracher le meme log si souvent. #592.
Il faut que je fasse cette modification avant d aller plus loin dans l analyse de log.

D'apres mes souvenirs, j'avais mis en place la commande stop donc elle doit fonctionner. Est ce que les personnes qui ont ces volets on cette commande stop qui fonctionne ?

**Comment by gubas** [comment]
Oui elle fonctionne.

**Comment by KiwiHC16** [comment]
@jossalisson, je viens de faire la modification, il faudrait que tu mettes à jour Abeille avec le master, puis que tu refasses l'inclusion du second volet et que tu partages AbeilleParser.

**Comment by KiwiHC16** [comment]
Sinon petite précision:
- Sur le réseau ZiGate, il y a un coordinateur et un seul qui est la zigate.

**Comment by jossalison38** [comment]
Bonjour je n'ai pas eu le temps hier soir,  j'essaye de le faire au plus top bonne journée

**Comment by jossalison38** [comment]
bonsoir KiwiHC16 je viens de refaire une inclusion 
je te joint le fichier abaille parser comme demandé  et aussi abeille si besoin 
je n'ai pas plus poussé l'inclusion car il est tard et demain boulot 
merci pour ton aide , soigne toi bien .
a bientot 
cordialement

**Comment by jossalison38** [comment]
[abeille 3.txt](https://github.com/KiwiHC16/Abeille/files/2857651/abeille.3.txt)
[abeille parser 3.txt](https://github.com/KiwiHC16/Abeille/files/2857653/abeille.parser.3.txt)
 desolé petit loupé

**Comment by jossalison38** [comment]
j'ai oublie la commande stop de mon premier volet qui a bien voulu ce configuré ne repond toujour pas .
cela peut t'il venir des commande sur la fonction stop il y a le nombre 1 
je joint une capture écran des commande 
![abeille stop](https://user-images.githubusercontent.com/47280807/52669095-901ab980-2f15-11e9-8a66-13cc26661754.png)
bonne soirée ou journée

**Comment by jossalison38** [comment]
bonsoir
 j'ai tenté ce soir de ré inclure le volet de ma cuisine en suppriment l'objet et en le ré incluant , mais cela na pas fonctionné .
pourriez vous me décrire la méthode pour supprimé et ré inclure le volet , car je penses qui y a quelle que chose que je ne doit pas bien faire ?

**Comment by gubas** [comment]
Supprime l'objet Volet Abeille et après suis la documentation Inclusion Profalux à la lettre.

**Comment by jossalison38** [comment]
J'ai fait exactement ça, même l'effacement 5 fois R puis stop avec reinclusion après et rien ne se crée

**Comment by jossalison38** [comment]
Faut-il appuier sur start zigbee  aussi

**Comment by jossalison38** [comment]
bonsoir ses bon j'ai du faire un recalcul du cache pour que abeille prenne en conte que j'avais supprimé le volet , apres j'ai pu re inclure . je ne sait pas pourquoi ?
d'ailleur maintenant j'ai la fonction stop qui fonctionne

**Comment by gubas** [comment]
Tant mieux. Le recalcul du cache, j'ai eu à le faire après un upgrade Abeille.

**Comment by KiwiHC16** [comment]
"Recalcul du cache" est une mauvaise expression, je devrais changer la therminologie pour éviter la confusion. Il n'y a pas de cache dans Abeille. 
"Recalcul du cache" veut uniquement dire qu'Abeille va interroger les équipements pour avoir leur informations pour faire/mettre à jour le graphe.
Normalement cela ne devrait pas avoir le moindre lien avec les inclusions.
Le principal c'est que cela fonctionne...
