### ISSUE TITLE
Ajout Ampoule OSRAM Smart+ Classic E27 Dimmable

### ISSUE THREAD

**Issue by Marc--** [KiwiHC16/Abeille#568]
Salut !

Je viens d'ajouter une ampoule Osram a mon réseau Zigbee. Pas de soucis pour l'inclusion, c'est super rapide et simple.

C'est un modèle "Smart+ Classic E27 Dimmable", et elle est reconnue comme "Classic A60 W clear - LIGHTIFY" de l'issue #189 . Pas de soucis de ce côté, ça semble être les même sauf la couleur du bulbe qui est opaque sur la mienne. 

Les fonctions ON / OFF / Toggle sont OK, mais l'ampoule est dimmable, et pas de commande présente. 

Je suppose que vu qu'elle est reconnue, c'est qu'elle a le meme identifiant que le modèle déjà implémenté. Donc peut être pas possible de les différencier ?

Voila ce que j'ai comme infos : 
![2019-01-25 19_04_38-dashboard - jeedom](https://user-images.githubusercontent.com/9568739/51764023-4e47e180-20d4-11e9-9b20-f28ebe284ee0.png)

![osram smart](https://user-images.githubusercontent.com/9568739/51764027-50aa3b80-20d4-11e9-98f5-f07e7a600302.png)

Je vais prendre un peu de temps ce soir voir si j'arrive a comprendre le JSON pour ajouter les commandes de dim !

**Comment by Marc--** [comment]
Après un petit tour dans le json (super bien conçu ton plugin) j'ai pu ajouter "levelLight" et "setLevel".

Le résultat est validé, l'ampoule est maintenant dimmable depuis Jeedom ! Je pense que c'est pareil pour la A60W 'clear' de @malabke sur l'issue #189 . S'il peut confirmer c'est cool.

> {
  "ClassicA60Wclear-LIGHTIFY": {
    "nameJeedom": "OSRAM Classic A60 W clear - LIGHTIFY",
    "timeout": "60",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c76620623",
      "icone": "OSRAMClassicA60Wclear-LIGHTIFY",
      "mainEP": "#EP#",
      "defaultEP": "03"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etatLight",
      "include5": "levelLight",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include19": "getEtat",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include28": "setReportEtat"
    }
  }
}

**Comment by KiwiHC16** [comment]
Avec les derniers modèles on peut choisir l icone dans la conf.
