### ISSUE TITLE
Cagnotte Utilisation

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#584]
Si la cagnotte prend forme il faudra choisir les produits. Je ne sais pas trop comment définir les besoins. Alors je fais cette issue et on verra en fonction des discussions.

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by gubas** [comment]
Clairement je suis motivé par du debugging sur les volets Profalux :)

**Comment by KiwiHC16** [comment]
Liste:

Paulman:
- Télécommande
https://www.amazon.fr/Paulmann-50067-Accessoires-Éclairage-Plastique/dp/B071WZZ12Y/ref=as_li_ss_tl?ie=UTF8&qid=1548503235&sr=8-33&keywords=paulmann+telecommande&linkCode=sl1&tag=fairecasoimem-21&linkId=88273a9ca683389c2c54452e4aa56375&language=fr_FR

Innr:
- INNR RC110 (https://github.com/fairecasoimeme/ZiGate/issues/160)

Ikea
- store (Acheté et integré)

Profalux
- Volets Profalux (415€)
`https://volets-discount.fr/profalux/1383-moteur-radio-profalux-zigbee-30-nm`
- Module (225€)
http://www.profalux-pieces-detachees.com/home/350-recepteur-radio-profalux-zigbee.html
- Telecommande Noé (236€)
`http://easyvolets.com/commandes-profalux-volets-roulants/522-telecommande-zoe-profalux-volets-roulants.html`

OSRAM
- Osram - flex led rgbw
- Inter Osram (20€)
`https://www.amazon.fr/Osram-Lightify-Interrupteur-Télécommande-Gris/dp/B00YSXBROI/ref=pd_aw_sbs_201_1?_encoding=UTF8&pd_rd_i=B00YSXBROI&pd_rd_r=7e509a97-2af0-11e9-873e-89a095b53bef&pd_rd_w=ErOdc&pd_rd_wg=rgzye&pf_rd_p=aea87543-a5a0-446d-81fd-2ad3adc8f4c7&pf_rd_r=QP5RJD505Q5F1CXFKJZZ&refRID=QP5RJD505Q5F1CXFKJZZ&th=1`
- Detecteur mouvement osram (50€)
`https://www.amazon.fr/Osram-Lightify-Interrupteur-Télécommande-Gris/dp/B01KOA4YE8/ref=pd_aw_sbs_201_1?_encoding=UTF8&pd_rd_i=B00YSXBROI&pd_rd_r=7e509a97-2af0-11e9-873e-89a095b53bef&pd_rd_w=ErOdc&pd_rd_wg=rgzye&pf_rd_p=aea87543-a5a0-446d-81fd-2ad3adc8f4c7&pf_rd_r=QP5RJD505Q5F1CXFKJZZ&refRID=QP5RJD505Q5F1CXFKJZZ&th=1 `
- Telecommande (see issue)

SUNRICHER
- https://www.sunricher.com/zigbee-series.html

LeGrand
- Volet
...

------------------------------------------------------------
Achetés 
- Prise encastrée Aqara Xiaomi
- Ampoule Aqara Xiaomi

------------------------------------------------------------
Achetés et integrés dans Abeille

Philips: Acheté et integré dans Abeille
- Philips Hue Détecteur de mouvement Motion sensor: https://www.amazon.fr/Philips-D%C3%A9tecteur-mouvement-Motion-sensor/dp/B0748NCMNW/ref=sr_1_8?ie=UTF8&qid=1550053008&sr=8-8&keywords=hue

**Comment by etaillandier** [comment]
Salut Ben,
Pour ma pars je suis pour la poursuite de l'intégration Xaomi, si possible une détection plus simple des actions du Cube Aqara...
Mais clairement j'espère que la cagnotte te permettra simplement de poursuivre le projet sur un maximum de systèmes?

**Comment by KiwiHC16** [comment]
Merci pour la cagnotte. J ouvre une issue pour le cube: https://github.com/KiwiHC16/Abeille/issues/587
pour continuer la discussion.

**Comment by KiwiHC16** [comment]
Pour ceux qui ont des volets Profalux, est ca le module ? 
http://www.profalux-pieces-detachees.com/home/350-recepteur-radio-profalux-zigbee.html
225€

Est ce que quelqu'un a cette prise:
http://www.profalux-pieces-detachees.com/accessoires/27-prise-gigogne.html
35€

Est ce la télécommnde que vous utilisez:
http://www.profalux-pieces-detachees.com/telecommandes-portables/32-telecommande-generale-avec-horloge-noe-profalux.html
208€

**Comment by dams74** [comment]
Les volets n'ont pas de boîtier. C'est inclus dans le moteurs.
Par contre j'ai ce boîtier chez moi en ce moment. Il permet de faire pleins de chose mais j'ai pas eu le temps de tester...
Pour la prise je ne connais pas.
Ce n'est pas cela comme télécommande. C'est celle ci 
http://www.profalux.com/wp-content/uploads/2013/09/ZOE_de.jpg

**Comment by KiwiHC16** [comment]
http://easyvolets.com/commandes-profalux-volets-roulants/522-telecommande-zoe-profalux-volets-roulants.html
236€

**Comment by dams74** [comment]
Oui mais je peux aider avec les produits en ma possession si besoin

**Comment by gubas** [comment]
En profalux, j'ai des bien du zigbee intégrés au moteur.

Mais j'ai une télécommande par volet : https://www.laboutiqueduvolet.com/7273-emetteur-profalux-zigbee-portable.html

**Comment by dams74** [comment]
En télécommande nous avons ça sur chaque volet
![image](https://user-images.githubusercontent.com/2788955/52465130-c6ef7900-2b7d-11e9-8aac-5b9fc46938d2.png)


Et une télécommande générale qui permet de faire des groupes et de la programmation horaire
![image](https://user-images.githubusercontent.com/2788955/52465164-e686a180-2b7d-11e9-82fd-849679b15cac.png)


Ces modules 
![image](https://user-images.githubusercontent.com/2788955/52465188-fd2cf880-2b7d-11e9-821b-6ddfd1a574bd.png)

permettent de commander:
- Eclairage
- porte de garage
- Volet non profalux
- Brise soleil
- portail

**Comment by KiwiHC16** [comment]
Auriez vous un lien vers le moteur volet avec la commande zigbee inclus ? Je ne le trouve pas, ceux que je trouve ont une radio à 800MHz alors que notre zigbee est a 2.4GHz.

**Comment by gubas** [comment]
https://volets-discount.fr/profalux/1383-moteur-radio-profalux-zigbee-30-nm

**Comment by Soyann** [comment]
Il serait top que ce sensor figure dans la liste des équipements supportés:
https://www.amazon.fr/Philips-D%C3%A9tecteur-mouvement-Motion-sensor/dp/B0748NCMNW/ref=sr_1_8?ie=UTF8&qid=1550053008&sr=8-8&keywords=hue
Ce dernier est cher (enfin quand même moins que du Z-Wave quand même), mais il n'est pas comparable aux détecteurs de mouvements Xiaomi (sensibilité aux mouvements réglable et fiable, détection de luminosité réactive et pertinente, délais pour repasser à 0 à 15 secondes et non 2 minutes...).
En te remerciant d'avance

**Comment by KiwiHC16** [comment]
Achat d un capteur de motion Hue car discount:

Item | Sku | Qty | Sous-total
-- | -- | -- | --
Philips Hue Détecteur de mouvement | | 1 | 39,95 €
Sous-total | 39,95 €
Traitement et livraison | 6,00 €
Discount (ILOVEHUE) | -11,99 €
Total général | 33,96 €

**Comment by KiwiHC16** [comment]
Pas d echange alors je garde la com sur la doc.
