### ISSUE TITLE
Prise Xiaomi Encastrée

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#585]
@ivan
Bonsoir
J'ai installé une prise xiaomi en version encastré mais elle n'est pas reconnue lors de l'appairage.
Comme ses paramètres sont strictement identiques à la prise xiaomi comment puis je faire pour qu'elle soit reconnue?
Merci d'avance

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=694948#p694948

**Comment by KiwiHC16** [comment]
@Ivan, peux tu mettre le plugin en debug, faire une inclusion et partager le log AbeilleParser.

As tu un lie vers cette prise pour voir ses caratéristique et avoir une image pour le plugin ?

**Comment by ivan9187** [comment]
Bonjour
le lien vers est: https://m.aliexpress.com/item/32853663507.html?trace=wwwdetail2mobilesitedetail&productId=32853663507&productSubject=Xiaomi-Aqara-Smart-Wall-Socket-ZigBee-Wireless-Wall-Outlet-Mijia-Wall-Socket-Switch-Work-For-Xiaomi&spm=a2g0s.9042311.0.0.4bb94c4d06MIgJ
Je vais faire l'inclusion et t'envoyer le log asap.
Encore merci
Ivan

**Comment by ivan9187** [comment]
Je l'utilise comme relais pour augmenter la portée du réseau zigbee...

**Comment by ivan9187** [comment]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2849246/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2849247/AbeilleParser.txt)

Voici les logs...

Merci

**Comment by ivan9187** [comment]
L'objet inconnu créé par Abeille est : Abeille-98e3--Type d objet inconnu (!JSON)

ivan

**Comment by KiwiHC16** [comment]
"EP":"01","modelIdentifier":"lumi.ctrl_86plug.aq1","deviceId":"zigbeeSmart Plug"

**Comment by KiwiHC16** [comment]
Je viens de faire un modele sur la base de la prise.
Je l'ai mis dans le master.
Essayes et tiens moi au courant.

Mets à jour avec le master ou:
![Uploading Capture d’écran 2019-02-11 à 10.51.23.png…]()

**Comment by ivan9187** [comment]
Super cela fonctionne, il manque juste l'icône (photo de la prise).
J'en profite pour un retour d'expérience :
je dois régulièrement (toutes les semaines environ) re appairer mes capteurs de Temp aquara car la connexion semble perdue (plus de mise à jour), puis certains de mes capteurs xiaomi aquara passent inactifs dans jeedom..
Merci

**Comment by KiwiHC16** [comment]
Je viens d'en recevoir une.
Il faut que je trouve un bout de fil pour la brancher.

**Comment by KiwiHC16** [comment]
C est bien la meme "lumi.ctrl_86plug.aq1"

**Comment by KiwiHC16** [comment]
Elle est bien crée et l icone est present.

**Comment by KiwiHC16** [comment]
Puissance est bonne.

Je clos donc le sujet.
