### ISSUE TITLE
une détection plus simple des actions du Cube Aqara...

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#587]

**Comment by KiwiHC16** [comment]
Je suppose que tu connais cette doc:
https://kiwihc16.github.io/Abeille/fr_FR/#tocAnchor-1-30-12

Que souhaiterais tu faires de différent ?

**Comment by etaillandier** [comment]
Heu... Non je ne connaissais pas, je vais me pencher dessus au plus vite :)

**Comment by etaillandier** [comment]
J'ai donc regardé et en effet il pourrait être sympa d'avoir les commandes regroupées du type "secouer", "basculer 90°" "retourner" "lancer"... Mais il est vrai qu'avec la doc il y a possibilité de tout faire en regroupant.

**Comment by KiwiHC16** [comment]
Exact et si moi je groupe dans Abeille alors je limite l'utilisateur c est pour ca que je ne fais rien.

**Comment by KiwiHC16** [comment]
je clos, si besoin tu rouvres.

**Comment by SnokplaTT** [comment]
Bonjour,
J'ai bien pris connaissance de la documentation mais je n'arrive pas a la comprendre. 
Aurez-tu un exemple de scénario intégrant ces différentes variables? 
Le rouge corresponds a rotation? orange a mouvement? En violet Tap = ?
Désolé, j'ai fait de mon mieux pour croiser ce schéma de la doc avec mes logs mais la logique ne me vient pas.
