### ISSUE TITLE
Xiaomi Bouton Carre: retour etat sur multi

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#59]
Sur le champ multi faire un retour d etat a 0 de la meme facon que le champ etat.

**Comment by KiwiHC16** [comment]
Fait et a tester

**Comment by lukebr91** [comment]
Obligé de supprimer & réinclure le bouton mais fonctionnement OK avec retour multi à 0 au bout de 2min, merci !

Mais du coup
![image](https://user-images.githubusercontent.com/35848408/35703004-fda4540a-079a-11e8-8895-68ca2eabb308.png)
Ici Premier double clic à 21:56:52
Nouveau double clic à 21:57:06 
--> la variable multi n'est pas actualisée (alors que Etat oui sur 2 clics proches) - si un scenario est déclenché par multi, ça ne marche pas tant que l'on a pas eu le retour 0 - même avec le changement d'etat (je viens de voir ta réponse sur l'autre issue)

**Comment by KiwiHC16** [comment]
Regardes 
![capture d ecran 2018-02-01 a 21 57 16](https://user-images.githubusercontent.com/8549674/35703634-0bb94d50-079d-11e8-8356-91ea96aea5c7.png)
C'est la solution.

J ai aussi mis du temps a comprendre la solution. 
- retour d état permet d avoir un icône qui reste a la valeur du clic dans l interface web
- la remontée d'info peut être géré par la gestion de repetition et scenario associés. Tu changes automatique sur "Toujours répéter".

**Comment by lukebr91** [comment]
En effet, fonctionnement niquel en mettant "Toujours répéter", je le met donc pour mes 2 boutons. Merci beaucoup !

On doit pouvoir fermer cet issue & l'ajout Push rond 👍

**Comment by KiwiHC16** [comment]
Super. Le boulot porte ses fruits ....
