### ISSUE TITLE
Retour Volets Profalux

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#591]
#565

**Comment by KiwiHC16** [comment]
@gubas, normalement le niveau demandé est calibré pour que le volet se positionne au bon niveau. J'avais passé pas mal de temps le dessus. J'espere que c est toujours bon.

Pour le retour je ne sais plus il faut que je regardes mais je suis quasi sur que si retour il y a du volet alors c est la valeur brute qui est affichée.

Si tu demandes 60% au volet, quelle valeur as tu dans le widget ? Est il bien rafraichi ?

**Comment by gubas** [comment]
Oui avec le slider : le positionnement est plutôt bon. (Honnêtement je n'ai pas fait de tests poussés)

C'est effectivement plutôt sur le retour d'état : en visuel je ne comprends pas quelles valeurs sont récupérées. C'est plutôt n'importe quoi et j'ai l'impression que ce n'est pas ou mal rafraîchi.

Quels tests je peux faire pour t'aider ?

**Comment by KiwiHC16** [comment]
Fais une serie de demandes de positions à 10% puis 90% puis 10% puis 90% (attends 10s entre chaque) et partages les logs Abeille, AbeilleParser, AbeilleMQTT pour voir ce qu'il se dit.

**Comment by gubas** [comment]
OK je te fais ça ce soir.

**Comment by gubas** [comment]
Voici les logs demandés.

Merci !

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2857479/Abeille.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2857480/AbeilleMQTTCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/2857481/AbeilleParser.txt)
[Abeille (1).txt](https://github.com/KiwiHC16/Abeille/files/2857482/Abeille.1.txt)
[AbeilleMQTTCmd (1).txt](https://github.com/KiwiHC16/Abeille/files/2857483/AbeilleMQTTCmd.1.txt)
[AbeilleParser (1).txt](https://github.com/KiwiHC16/Abeille/files/2857484/AbeilleParser.1.txt)

**Comment by dams74** [comment]
@KiwiHC16 on avait validé le fonctionnement de cela.
Pour le retour c'était bon aussi il me semble

**Comment by KiwiHC16** [comment]
@gubas, avant que je regarde les logs, est ce que lorsque tu as fait les tests, le widget se mettait à jour et avec une valeur en relation avec la valeur demandée ?

@dams74, je crois me souvenir que oui, mais on peut encore vérifier et améliorer si besoin.

**Comment by gubas** [comment]
@KiwiHC16 non pas du tout

**Comment by KiwiHC16** [comment]
Premiere série:
```
[2019-02-12 21:11:02][DEBUG] : Envoi du message: Level=10&duration=01 vers CmdAbeille/9eef/setLevelVolet
[2019-02-12 21:11:02][DEBUG] : Envoi du message: EP=01&clusterId=0006&attributeId=0000 vers CmdAbeille/9eef/ReadAttributeRequest
[2019-02-12 21:11:02][DEBUG] : Envoi du message: EP=01&clusterId=0008&attributeId=0000 vers CmdAbeille/9eef/ReadAttributeRequest
[2019-02-12 21:11:03][DEBUG] : Topic: ->Abeille/9eef/0008-01-0000<- Value ->248<-
[2019-02-12 21:11:03][DEBUG] : L objet: Abeille/9eef existe mais pas la commande: 0008-01-0000
...
[2019-02-12 21:11:24][DEBUG] : Envoi du message: Level=88&duration=01 vers CmdAbeille/9eef/setLevelVolet
[2019-02-12 21:11:24][DEBUG] : Envoi du message: EP=01&clusterId=0006&attributeId=0000 vers CmdAbeille/9eef/ReadAttributeRequest
[2019-02-12 21:11:24][DEBUG] : Envoi du message: EP=01&clusterId=0008&attributeId=0000 vers CmdAbeille/9eef/ReadAttributeRequest

[2019-02-12 21:11:25][DEBUG] : Topic: ->Abeille/9eef/0008-01-0000<- Value ->45<-
[2019-02-12 21:11:25][DEBUG] : L objet: Abeille/9eef existe mais pas la commande: 0008-01-0000
```

Deux envois de commande pour un niveau à 10 puis à 248. Puis demande de l etat et du niveau du volet. Pas de réponse pour l'état (il ne retourne probablement pas son état) et ensuite son niveau mais Abeille ne trouve pas la commande dans le  widget. As tu une commande info "level volet" dans le volet dans abeille. Peux tu partager une capture d'ecran de cette commande ?

(idem pour la deuxieme serie de log).

**Comment by gubas** [comment]
J'ai une commande info "Level" tout court
![level](https://user-images.githubusercontent.com/596670/52777557-644a2180-3044-11e9-8b7f-f758cc3ca5eb.PNG)

**Comment by gubas** [comment]
Par contre je suis retourné voir sur le volet sur lequel j'ai fait les logs et j'ai aussi une commande info "Level"
![level_2](https://user-images.githubusercontent.com/596670/52778096-7b3d4380-3045-11e9-837d-54e680627c53.PNG)

Mais pas avec la bonne "commande" : 0008-01-0000 ??

**Comment by KiwiHC16** [comment]
Peux veux dire que tu as deux volets:
un avec 0008-01-0000
et un avec 0008-10-0000
C'est bien ca ?
(10 est une erreur et je ne trouve nul part ou le code pourrait avoir généré ce 10 !? As tu fait des modifs à la main ?)

**Comment by gubas** [comment]
Oui c'est bien ça : c'est bien 2 volets distincts. (Le premier c'est celui de la cuisine et le deuxième c'est celui du salon ou je t'ai généré les logs)

(NB : J'ai 7 volets en tout)

Non je n'ai jamais fait de modifs manuelles.

**Comment by KiwiHC16** [comment]
Je ne comprends pas d ou vient le 10 dans 0008-10-0000
Je vais modifier le modele pour le forcer à la main.

**Comment by gubas** [comment]
J'ai juste besoin de mettre à jour Abeille et ça roulera ou je dois faire autre chose ?

**Comment by KiwiHC16** [comment]
Sois tu te mets à jour abeille avec le master ou tu utilises le bouton mise à jour des modèles dans la page de configuration. Ensuite tu supprimes le volet et le re-inclus.

**Comment by gubas** [comment]
Pour info, j'ai bien mis à jour Abeille par Github :)

Par contre, pour l'instant j'ai pas trop le temps de réinclure mes volets ...

Il y aurait une autre solution pour mettre à jour tout ça ?

**Comment by dams74** [comment]
Au sujet du level, j'ai manger l'autre jour chez un collègue qui à une calyp'home, la box de profalux pour gérer les volets.
Le niveau n'est pas proportionne sur la boxl, c'est à dire qu'a 50% le volet n'est pas à moitié mais plus 3/4 fermé.
Il m'a aussi indiqué qu'il y avait une touche pour mettre les volets en position fermé mais avec les lames des volets qui laissent passé la lumière du jour, comme ceci:

![image](https://user-images.githubusercontent.com/2788955/56683447-db97d380-66cd-11e9-88b2-0fd16485127a.png)

De mémoire cette position correspondait à 86% mais à vérifier.
Je pense que le travail que l'on a fait autour du calibrage va servir à rien car suivant si le volet est une fenêtre ou une porte fenêtre j'ai peur que les valeurs ne soient pas les même.
Je ferai des essais dès que possible pour vérifier cela

**Comment by KiwiHC16** [comment]
C est plus que probable. Maintenant que le code est dans abeille, on peut faire une doc pour expliquer comment calculer les valeurs et rendre les valeurs ajustable dans abeille, comme ca chacun fait son regleagle (car ca depend aussi beaucoup de la perception de la personne et ca je ne sais pas le mesurer...)

**Comment by Seby9576** [comment]
Bonjour,

Est ce que le plugin abeille fonctionnerait sur eedomus svp ? Merci

**Comment by Seby9576** [comment]
Bonjour,

Pouvez vous me dire si sur jeedom le retour de position fonctionne avec les volets profalux svp ? Si oui est ce un vrai retour de position ou un retour estimatif ?
Je vous pose cette question car je suis actuellement sur eedomus mais j'ai pas mal de soucis avec mes volets. Retour de position fictive et j'ai souvent des volets qui ne s'ouvrent ou se ferment pas en mode automatique.
Donc je pense sérieusement a basculer sur jeedom pour ca.

Merci de vos retour

**Comment by dams74** [comment]
Salut
Il y a bien un retour de position. il faut par contre pour cela faire un get level manuellement ou grâce à un scénario pour le mettre à jour. La position n'est pas proportionnel, par ex 50% correspond à 3/4 fermé
De plus sur jeedom, il y a un plugin officiel volet qui permet de faire pas mal de chose et entre autre de faire ouvrir ou fermer les volets en fonction de la position du soleil.
N'hésite pas à poser d'autre question si besoin

**Comment by Seby9576** [comment]
Effectivement ca ma l'air mieux géré que sur eedomus.  Jeedom est il stable sur un PI4 ? 
Sur eedomus je peux quand même les manipuler en pourcentage mais le retour d'information est fictif. Du coup si dans le lot il y en a un qui bouge pas alors il le voit ouvert alors qu'il est toujours fermé. C'est un peu embêtant.
Est ce que certains ont des soucis similaire sur jeedom ? Sachant que j'ai 16 volets et que j'ai dissocié en trois groupes. Nord, sud et chambres.
Merci de vos retours

**Comment by KiwiHC16** [comment]
Jeedom est très stable sur le rpi et sur rpi4. Mais sur rpi4 il faut faire attention a l alimentation et les câblages USB. Ca peut être galère au debut mais une fois résolue alors nickel. Mon système principal toune sur rpi4/jeedom

Merci @dams74 , c est le souvenir que j avais. 
Il faut que je travaille le retour automatique pour ne pas avoir a demander manuellement. Je pense que j'ai tout ce qu'il faut sauf le temps pour l instant....

**Comment by dams74** [comment]
Je suis à ta disposition pour des tests quand tu auras besoin

**Comment by Seby9576** [comment]
Bonjour,

Et vous pouvez également piloter le volet à la voix via home assistant ?
Quand tu dis mon système principal tourne sur jeedom, parce que tu as plusieurs système ?

**Comment by dams74** [comment]
'je ne pilote pas à la voix mais je pense qu'avec les interactions c'est possible

**Comment by Seby9576** [comment]
C'est pratique mais sur eedomus c'est seulement ouvert ou fermé. Dans HA c'est vu comme un interrupteur et non comme un volet.
Si besoin je peux aider également. Mais également participer financièrement

Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)


La discussion doit être en relation directe avec le titre de l’issue.
Ne pas avoir deux ou plus discussions dans une issue. 
Si la discussion change de sujet, fermer l’issue et en ouvrir une autre avec le sujet qui va bien.
Evitez les généralités et soyez le plus précis possible dans les informations partagées.

**Comment by KiwiHC16** [comment]
Je suis perdu cette issue par dans tous les sens. Pour les discussions "génériques" je prefererai que vous utilisié le forum jeedom. Dans github j essaye d avoir une issue par sujet très precis pour savoir ce que je dois faire dans le code.

Le sujet était "Retour Volets Profalux".

De mon souvenir l idée etait d avoir le retour automaitqye du niveau de valet dans jeedom quand on utilise une telecommande par exemple.

@gubas quelle est la situation pour toi ?

**Comment by tcharp38** [comment]
Le titre etant "retour volets" je clos.
Le retour est maintenant fonctionnel sur la 210520-BETA-4.
A reouvrir si besoin
