### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gubas** [KiwiHC16/Abeille#594]
@KiwiHC16, si tu le souhaites je peux aider en reprenant la documentation pour la remettre en forme et la mettre à jour ? (Avec le plus possible de capture d'écran à jour ?)

Toujours bien sur sur le même principe que les modifs que j'ai effectué sur la doc Profalux.

J'ai vu qu'il y avait pas mal de liens "morts" sur la page d’accueil du projet Github, peut être que je pourrais aussi essayer de les corriger ?

C'est une proposition pour aider ce projet. Dis moi si t'es partant ?

**Comment by KiwiHC16** [comment]
Carrement partant, je fais ce projet open source pour que chacun amene son aide...
Vas y a fond et si tu as des questions sur le fonctionnement je suis dispo.

Il faut que je fasse une partie sur la gestion des telecommandes Ikea. Je vais essayer cette apres midi.

**Comment by KiwiHC16** [comment]
On peut aussi faire de session partage d'ecran pour te montrer le fonctionnement pour te faciliter l'écriture.

**Comment by gubas** [comment]
OK cool.

Je vais déjà essayer de m'approprier la doc et la mettre à jour.

Je pense que ça m'aidera déjà à mieux comprendre le fonctionnement.

Et après clairement, ça m’intéresse d'aller plus loin, je note ta proposition sur le partage d'écran. (Surtout que je suis loin de posséder autant de matériel que toi :))

Je n'ai "que" des volets profalux / ampoules "simple" IKEA / télécommande Hue et en commande (de chine ...) quelques "capteurs" Xiaomi.

Je pense aussi prendre quelques interrupteurs Xiaomi mural filaire sans neutre.

**Comment by gubas** [comment]
Salut,

Avancement de la reprise de la doc ... 
https://github.com/gubas/Abeille/blob/patch-2/docs/fr_FR/index.md

**Comment by KiwiHC16** [comment]
Difficile des regarder depuis mon tel. Je vois que ce n est pas sur mon git. Je suppose que c est un fork. Comment fera ton la mise à jour ? Avec un PR ? Si je fais des changements sur le doc les récupères tu dans ta version ? Ne va t on pas se retrouver avec des conflits ? Ne serait il pas plus simple de faire une branche depuis le master de mon repo ? 
Je connais bien git en utilisation mono utilisateur mais je n ai pas l habitude à plusieurs utilisateurs.

**Comment by gubas** [comment]
Salut, si je fais des modifs tu les récuperas pas en auto (tu es le maître) mais lorsque je ferais un PR j'aurais des "conflits" à résoudre. Ça devrait être simple vu que c'est du "texte".

**Comment by dams74** [comment]
Je pense qu'il faut faire des PR régulièrement afin de ne pas avoir trop de conflits

**Comment by gubas** [comment]
Oui c'est ce que j'essayerais de faire...

**Comment by gubas** [comment]
Bien sûr le premier PR sera conséquent.

Surtout que je suis obligé de décaler des "morceaux". Bien sûr je ne perds aucune donnée.

Et au pire je reprendrais tes modifs.

Bien sûr faudrait éviter de ton côté de faire des gosses modifs de structures...

**Comment by KiwiHC16** [comment]
Ok j'ai fait des petits changements au niveau du texte dans certaines lignes et la je viens d ajouter un chapitre.
Pourquoi ne te mets tu pas sur le master et tu commit à chauqe changement pour limiter les conflits ?
Peut être faut il que je te donne des droits, je ne sais pas.
Fais comme tu le sens et on verra si on a des conflits à gérer.

**Comment by gubas** [comment]
Bein effectivement je n'ai pas de droit donc je ne pas directement mettre à jour.

Je suis obligé de PR avec mon fork.

Je viens d'en faire un ... Je te laisse voir ...

**Comment by KiwiHC16** [comment]
Je vais investiguer pour s avoir ce qui est plus facile. Te donner les droits (je ne sais pas comment on fait) ou passer par des PR.

**Comment by gubas** [comment]
Ok tiens moi au jus

**Comment by KiwiHC16** [comment]
Sur la base de ce que l'on peut lire ici:

https://stackoverflow.com/questions/5007738/multiple-users-and-a-single-repository-on-github-or-springloops

Les PR est la bonne méthode, donc il faut que je limite mes changements pour éviter les conflits.

C est aussi comme cela qu'on procédait sur un autre très gros projet donc restons comme ca.

Suite au merge du PR, je ne sais pas trop si ton fork sera mis à jour automatiquement ou si tu dois faire une synchro.

**Comment by gubas** [comment]
Salut, j'ai fait 3 PR différents pour que ce soit plus simple.

Pour l'instant, je ne fais plus de modifs.

Je vais cleaner mon fork.

**Comment by gubas** [comment]
Il faut que je clean mon fork à chaque fois (Enfin c'est plus simple pour suivre surtout :)

**Comment by tcharp38** [comment]
Salut
Je ne sais pas trop sur quelle doc vous bossez mais suite à mon point #619, je suis partant pour bosser sur un chapitre "debug" si il n'existe pas deja.
Il y aura surement de + en + de monde à utiliser Abeille et pour soulager KiwiHC16 un chapitre de "self debug", au moins de premier niveau pourrait etre utile non ?
Dites moi si ca fait du sens. En attendant j'essaie de refaire tomber en marche ma plateforme.

**Comment by tcharp38** [comment]
Désolé. Je suis idiot. Il y a vraiment plein d'infos fournies par Kiwi via le panneau de config du plugin. Je vais tacher de trouver qqch d'utile pour moi et j'aurai peut etre des suggestions. Merci Kiwi pour le boulot jusque la.

**Comment by KiwiHC16** [comment]
https://kiwihc16.github.io/Abeille/fr_FR/
Chapitre 20

Je suis preneur de toutes les aides disponibles.

**Comment by KiwiHC16** [comment]
Je suis sur le point de repasser la doc au format asciidoc car le format md me gav...
Si vous avez des modifs, pouvez vous faire un PR avant que je ne change tout.

**Comment by gubas** [comment]
ah bon dommage : tu vas pas perdre la mise en page "style" Jeedom ?

**Comment by KiwiHC16** [comment]
Je viens de finir la mise au format AsciiDoc. Elle est dans le master.
Effectivement je perds le format Jeedom mais je galèrai trop avec et le doc sera en locale dans le plugin maintenant.
Ca permet d'avoir des petits fichiers, c est mieux pour git.

**Comment by gubas** [comment]
OK : par contre les liens sont morts dans le github et dans le plugin ?

**Comment by KiwiHC16** [comment]
Je ne suis pas s^r de comprendre ton point.
Le fichier doc source est en asciidoc, le fichier doc généré est en html et contient les liens.
Pour générer la doc il faut lancer le fichier genereDoc.sh

**Comment by gubas** [comment]
https://kiwihc16.github.io/Abeille/fr_FR/ : ne fonctionne plus par exemple.

**Comment by KiwiHC16** [comment]
Et zut, il faut que je trouve une solution ...

**Comment by KiwiHC16** [comment]
La doc est de nouveau en ligne.
Je clos cette "issue" et si besoin on en ouvre des plus spécifiques.

**Comment by handfreezer** [comment]
Hello, I failed to read documentation (in jeedom, by clicking the local doc on latest doc).
Did I miss something?
