### ISSUE TITLE
Télécommande OSRAM

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#595]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&start=1920

**Comment by KiwiHC16** [comment]
Commandée.

**Comment by KiwiHC16** [comment]
Reçue

**Comment by KiwiHC16** [comment]
Incluse

**Comment by KiwiHC16** [comment]
Pour l instant les boutons de base sons conf supplementaire car je ne trouve pas de GW Osram.

**Comment by KiwiHC16** [comment]
https://github.com/ebaauw/homebridge-hue/issues/183

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/235

**Comment by tcharp38** [comment]
Antiquité de sujet qui n'a pas bougé depuis un bail.
A reouvrir et preciser si besoins.
