### ISSUE TITLE
Power Source Icon

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#60]
Sur le power source mettre un petit symbole AC ou DC pour que cela soit plus facile a lire en lieux et place de 00 et 01 (voir si autre valeur)

**Comment by edgd1er** [comment]
Salut Ben, je n'ai pas les infos power source  et link dans le capteur temp/pression/hum. Peux tu me dire ou cela se passe dans le code que je regarde ?
J'ai ça comme remontée du parser.
-------------- 2018-02-01 21:41:01
protocolDatas
message > 12 char
Type: 8102

type: 8102
[2018-02-01 21:41:01]
(Attribute Report)(Processed->MQTT)
SQN: 0E
Src Addr : 6432
End Point : 01
Cluster ID : 0000
Attr ID : 0005
Attr Status : 00
Attr Data Type : 42
Attr Size : 000C
Data byte list : 6c756d692e77656174686572
Data byte: lumi.weather

**Comment by KiwiHC16** [comment]
Ce message su parser est le nom de l équipement : lumi.weather (et 6c756d692e77656174686572 est la meme chose en hexa).

Pour avoir power source et link, il faut utiliser le bouton "Listes Equipements" pour que la Zigate envoie les infos qu'elle a en stock.

**Comment by edgd1er** [comment]
Ca fonctionne. Merci

**Comment by KiwiHC16** [comment]
Je viens de trouver une solution pour afficher un symbole pour être plus sympas.
Créer un widget spécifique:
![capture d ecran 2018-02-01 a 22 36 15](https://user-images.githubusercontent.com/8549674/35704732-b83d50aa-07a0-11e8-904e-bce29ded44bd.png)

![capture d ecran 2018-02-01 a 22 41 17](https://user-images.githubusercontent.com/8549674/35704863-1559ab3a-07a1-11e8-9e54-e9dd653119de.png)


![capture d ecran 2018-02-01 a 22 38 03](https://user-images.githubusercontent.com/8549674/35704734-b8708164-07a0-11e8-80eb-88882ee38946.png)
![capture d ecran 2018-02-01 a 22 38 16](https://user-images.githubusercontent.com/8549674/35704735-b889d2c2-07a0-11e8-9cbc-ac4319968b0f.png)
![capture d ecran 2018-02-01 a 22 38 30](https://user-images.githubusercontent.com/8549674/35704736-b8a2591e-07a0-11e8-9551-461def15fcaa.png)
![capture d ecran 2018-02-01 a 22 38 36](https://user-images.githubusercontent.com/8549674/35704737-b8be6ef6-07a0-11e8-94df-a8e0f0249a50.png)

Il faudra changer les objets dans JSON pour avoir power en binaire par défaut et associer le widget a la commande.

Y a tout y a plus qu a mettre dans le code et la doc.

**Comment by KiwiHC16** [comment]
Done for all existing Node.

**Comment by edgd1er** [comment]
Je n ai pas trouvé le widget dans le market, quel terme utilises pour le trouver ?

**Comment by KiwiHC16** [comment]
C'est dans la plugin "widget". Il faut ajouter "Widget". Je fais une doc et je t'envoies le lien.

**Comment by KiwiHC16** [comment]
Tous les details à:

https://github.com/KiwiHC16/Abeille/blob/master/Documentation/ConfigurationAvancee.asciidoc#widget

**Comment by edgd1er** [comment]
Merci pour la doc, c super. Je comprends pourquoi je ne ele trouvais pas. Je pensais que le widget etait sur le market.

**Comment by KiwiHC16** [comment]
J'essaye de faire la doc car cela me permet de me souvenir de comment on fait et je me dis que le jour ou des personnes vont commencer à utiliser le plugin, il sera facile de pointer la doc dans beaucoup de cas et ca facilitera la vie et la maintenance.
N'hesites pas quand tu fais des modifs softs de faire des captures d'écrans et faire un petit paragraphe.
