### ISSUE TITLE
OSRAM SMART+ Outdoor Flex Multicolor

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#609]
https://www.jeedom.com/forum/viewtopic.php?p=700563#p700563

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
![image](https://user-images.githubusercontent.com/8549674/53231319-f24b8b00-3688-11e9-9263-5fb05aa8f758.png)
c'est un ruban de couleur RGBW. Le lien du site constructeur OSRAM et le modèle "Outdoor Flex Multicolor"
https://smartplus.ledvance.com/products/outdoor-lighting/index.jsp
Topic: ->Abeille/c638/0000-03-0005<- Value ->LIGHTIFY Outdoor Flex RGBW<-

**Comment by KiwiHC16** [comment]
Modele dans le master. A tester.

**Comment by KiwiHC16** [comment]
@Asyrah  
Après mise à jour des modèles, le ruban est désormais bien reconnu, merci.
ON, OFF -> OK
Luminosité -> OK
Par contre je n'arrive pas à changer les couleurs...

**Comment by KiwiHC16** [comment]
setVert EP à 01 par défaut, hors ici il faut 03.
Modif à faire.

**Comment by KiwiHC16** [comment]
Pushed in master. To be tested.

**Comment by KiwiHC16** [comment]
Pour l'instant avec le nouveau modèle créé par kiwihc16, il est détecté et intégrable à Jeedom sans soucis. Seul bmol pour l'instant chez moi, c'est le RGB qui déconne. Sinon niveau matos, ça m'a l'air de bonne facture, à voir dans les prochaines semaines.

**Comment by KiwiHC16** [comment]
Comment est connecté le ruban au controller ?

> Il y a une prise d'alimentation, un sorte de petit transfo entre 2 et le ruban. Tout semble soudé les uns au autre.
Je prendrai une photo

**Comment by Asyrah** [comment]
J'ai suivi la procédure "Alternative : Installation du plugin Abeille avec github depuis le market" pour mettre à jour le plugin. Jeedom m'a informé du succès de la MAJ du plugin.

Version Abeille : "d1adbabfa1f72058fae06545656349d45622a666"
Version Jeedom : 3.1.7

Est-ce la bonne version à tester ? :)

**Comment by KiwiHC16** [comment]
Oui c est la bonne version abeille. 

Peux tu supprimer l objet et faire une inclusion pour le créer de nouveau ?

Une fois créé qu est ce qui fonctionne et qu est ce qui ne fonctionne pas ?

**Comment by Asyrah** [comment]
MAJ abeille en version "eb17db9640e22fc5049c0fe04a5ea92bd628a3fd"
Redémarrage du plugin
Suppression de l'objet Ruban
Mise à jour des modèles
Application des modèles

Inclusion du Ruban > Abeille-c638 (j'ai pas l'impression que le numéro change)
```
Etat ON > ok
Etat OFF > ok
Bouton Toggle > ok
setLevel et affichage > ok
```

Bouton blanc, bleu, rouge, vert > nok
setColorRGB 
```
Demande couleur vert >> bleu
Demande couleur rouge >> vert clair
Demande couleur bleu >> bleu
Demande couleur jaune >> bleu ciel
Demande blanc > rien
Demande noir > rien
```

[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/2921947/Abeille.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/2921948/AbeilleMQTTCmd.txt)

**Comment by KiwiHC16** [comment]
Regardons en premier les histoires de couleur.
Les couleurs sont dans espace pas facile a apprehender. On vas essayer de comprendre ce qu'il se passe en envoyant des commandes spécifiques.
On va utiliser la commande (il faut peut être la rendre visible):
![Capture d’écran 2019-03-15 à 10 54 32](https://user-images.githubusercontent.com/8549674/54423335-bac48180-4710-11e9-926f-1cedafc0d564.png)
Le code est RRGGBB
R pour Red/Rouge
G pour Green/Vert
B pour Bleu

Peux tu mettre FF0000 pour avoir le rouge a fond et les autre off
00FF00 pour Green
0000FF pour Bleu

et me dire les couleurs que tu obtiens.

**Comment by Asyrah** [comment]
[Essai_couleurs.zip](https://github.com/KiwiHC16/Abeille/files/2970512/Essai_couleurs.zip)
Récap des résultats : J'obtiens les bonnes couleurs par ce biais

```
Plugin abeille en version 1dab45cced5ee6313453a543c63dd7c39f8aca4d
Affichage RGB (setColourRGB EP=03&color=#title#) -> OK
Allumage ruban via bouton Toggle -> OK
11:15
FF0000 	-> J'obtiens du rouge
00FF00	-> J'obtiens du vert
0000FF	-> J'obtiens du bleu
FFFFFF 	-> J'obtiens du blanc
11:19
```

**Comment by KiwiHC16** [comment]
```FFFFFF 	-> J'obtiens du blanc```
Est ce les led blanches qui s'allument ? et les Led couleurs sont éteintes ?

```FF0000 	-> J'obtiens du rouge```
Les Led Blanches sont éteintes et seul led couleur rouge ?

Quelles types de Led existent sur ce ruban?
Couleur ?
Blanc ?
Blanc Chaud/Marron ?

**Comment by Asyrah** [comment]
Type de ruban : RGBW. Capable de varier la chaleur du blanc (2000…6500 K)
cf [https://www.osram-lamps.com/ecatalog/smart-home/smart-home-products-with-zigbee-technology/smart-home-luminaires/outdoor-luminaires/smart-outdoor-flex-multicolour/index.jsp](url)


Les leds sont toutes regroupées au même endroit et forme un cercle. 
![leds_cercle](https://user-images.githubusercontent.com/48121420/54426658-b43a0800-4718-11e9-9d6a-44a2041a5bc0.png)
Chaque cercle est espacé de 5 cm.
Il y a 3 leds : un led rouge, un led vert et un led bleu

Quand je demande :
Du blanc -> 3 leds allumés
Du rouge -> led rouge à fond et verte un poil (bleu éteint)
Du vert-> led verte à fond et rouge/bleu un poil
Du bleu -> led bleu à fond et verte un poil (rouge éteint)

**Comment by KiwiHC16** [comment]
Du rouge c'est quand tu envoie FF0000 ?
Donc meme si tu envoies FF0000, il y a du vert dedans ?

**Comment by Asyrah** [comment]
> Du rouge c'est quand tu envoie FF0000 ?
> Donc meme si tu envoies FF0000, il y a du vert dedans ?

Oui. Je résume : 
Quand je demande ff0000 (rouge), les leds rouge (fort) et vert (faiblement) sont allumés sur le ruban.
Quand je demande 00ff00 (vert), les leds rouge (faiblement), vert (fort) et bleu (faiblement) sont allumés sur le ruban.
Quand je demande 0000ff (bleu), les leds rouge (faiblement) et bleu (fort) sont allumés sur le ruban.
Quand je demande ffffff (blanc), les leds rouge (fort), vert (fort) et bleu (fort) sont allumés sur le ruban.

Les couleurs sont respectées, j'obtiens bien ce que j'ai demandé.

**Comment by KiwiHC16** [comment]
Pour FF0000, tu devrais avoir uniquement Rouge et le reste éteint, ce qui n'est pas tout à fait ce qu'il se passe. En fait, les ampoules ne prennent pas ses infos alors elles doivent être modifier.
C'est fait dans le code:
https://github.com/KiwiHC16/Abeille/blob/master/resources/AbeilleDeamon/CmdToAbeille.php#L1914

Et de bonnes explications ici: https://en.wikipedia.org/wiki/SRGB

En gros il faudrait trouver la matrice qui va bien pour cet équipement.
Maintenant si tu trouves que la correspondance RRGGBB et l'équipement est bon alors on peut ne pas toucher à la matrice et juste change les commandes: blanc, rouge, vert, bleu qui elles utilisent le mode couleur en X, Y.

Pour ce faire tu mets le plugin en debug, tu choisis une couleur qui correspond au rouge que tu veux par exemple, tu envoies la requetes RGB, et dans le log tu devrais voir passer les infos X, Y envoyés.

Tu fais le test pour les 4 couleurs (R,G,B,W) et on modifie le modele avec ces valeurs.

**Comment by Bernidouille** [comment]
Salut kiwiHc,
Je remarque la même chose au niveau de mes flex led indoor de chez osram.
Ff0000 - rouge fort et vert faible
00ff00 - vert fort / rouge et bleu faible
0000ff - beu fort / vert faible.

Quand j'utilise la commande RGB de type message. -> color= title.
Cela fonctionne.
Par contre le setRgb. De type color. Ne fonctionne pas ( variations exclusive de bleu ou de vert). 

J'ai essayé pas mal de test, et pour l'instant je n'arrive pas a reproduire le rouge pure... Je continue les recherches et je reviens dès que j'ai trouvé.

**Comment by Asyrah** [comment]
Oui je confirme, pareil que Bernidouille.
La commande SetColorRGB de type EP=03&color=#title# fonctionne.
Celle des couleurs "setColour" ne donne rien (blanc/rouge/bleu/vert)

**Mes essais du soir.**
J'obtiens du rouge avec SetColorRGB  -> FF0000

> [2019-03-19 23:00:09][DEBUG] : execute function with options ->{"title":"ff0000","message":"","utid":"1553031717568"}<-
> [2019-03-19 23:00:09][DEBUG] : -
> [2019-03-19 23:00:09][DEBUG] : Envoi du message: EP=03&color=ff0000 vers CmdAbeille/c638/setColourRGB
> [2019-03-19 23:00:09][DEBUG] : -
> [2019-03-19 23:00:09][DEBUG] : Topic: ->Abeille/c638/colorRouge<- Value ->100<-
> [2019-03-19 23:00:09][DEBUG] : Topic: ->Abeille/c638/colorVert<- Value ->0<-
> [2019-03-19 23:00:09][DEBUG] : Topic: ->Abeille/c638/colorBleu<- Value ->0<-
> [2019-03-19 23:00:09][DEBUG] : Topic: ->Abeille/c638/ColourRGB<- Value ->ff0000<-
> 
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]-----
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]Msg Received: Topic: {CmdAbeille/c638/setColourRGB} => EP=03&color=ff0000
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]Type: CmdAbeille Address: c638 avec Action: setColourRGB
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]msg: EP=03&color=ff0000 rouge: 255 vert: 0 bleu: 0
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]processCmd call with Command parameters: setColourRGB-1-address-c638-R-255-G-0-B-0-destinationEndPoint-03-
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]begin processCmd function
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]colourX: a294 colourY: 53d0
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]Dest:/dev/ttyUSB1 cmd:00B7 len:000B datas:02c6380103a29453d00001
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]len data: 22
> AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]checksum computed: 246

J'obtiens du vert avec SetColorRGB  -> 00FF00

> `[2019-03-19 23:02:17][DEBUG] : execute function with options ->{"title":"00ff00","message":"","utid":"1553031717568"}<-
> [2019-03-19 23:02:17][DEBUG] : Envoi du message: EP=03&color=00ff00 vers CmdAbeille/c638/setColourRGB
> [2019-03-19 23:02:18][DEBUG] : Topic: ->Abeille/c638/colorRouge<- Value ->0<-
> [2019-03-19 23:02:18][DEBUG] : Topic: ->Abeille/c638/colorVert<- Value ->100<-
> [2019-03-19 23:02:18][DEBUG] : Topic: ->Abeille/c638/colorBleu<- Value ->0<-
> [2019-03-19 23:02:18][DEBUG] : Topic: ->Abeille/c638/ColourRGB<- Value ->00ff00<-
> 
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]-----
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]Msg Received: Topic: {CmdAbeille/c638/setColourRGB} => EP=03&color=00ff00
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]Type: CmdAbeille Address: c638 avec Action: setColourRGB
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]msg: EP=03&color=00ff00 rouge: 0 vert: 255 bleu: 0
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]processCmd call with Command parameters: setColourRGB-1-address-c638-R-0-G-255-B-0-destinationEndPoint-03-
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]begin processCmd function
> **AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]colourX: 4c33 colourY: 9867**
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]Dest:/dev/ttyUSB1 cmd:00B7 len:000B datas:02c63801034c3398670001
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]len data: 22
> AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]checksum computed: 195`

J'obtiens du bleu avec SetColorRGB  -> 0000FF

> `[2019-03-19 23:04:14][DEBUG] : execute function with options ->{"title":"0000ff","message":"","utid":"1553031717568"}<-
> [2019-03-19 23:04:14][DEBUG] : Envoi du message: EP=03&color=0000ff vers CmdAbeille/c638/setColourRGB
> [2019-03-19 23:04:14][DEBUG] : Topic: ->Abeille/c638/colorRouge<- Value ->0<-
> [2019-03-19 23:04:14][DEBUG] : Topic: ->Abeille/c638/colorVert<- Value ->0<-
> [2019-03-19 23:04:14][DEBUG] : Topic: ->Abeille/c638/colorBleu<- Value ->100<-
> [2019-03-19 23:04:14][DEBUG] : Topic: ->Abeille/c638/ColourRGB<- Value ->0000ff<-
> 
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]-----
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]Msg Received: Topic: {CmdAbeille/c638/setColourRGB} => EP=03&color=0000ff
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]Type: CmdAbeille Address: c638 avec Action: setColourRGB
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]msg: EP=03&color=0000ff rouge: 0 vert: 0 bleu: 255
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]processCmd call with Command parameters: setColourRGB-1-address-c638-R-0-G-0-B-255-destinationEndPoint-03-
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]begin processCmd function
> **AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]colourX: 261a colourY: 0f3d**
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]Dest:/dev/ttyUSB1 cmd:00B7 len:000B datas:02c6380103261a0f3d0001
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]len data: 22
> AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]checksum computed: 77`

J'obtiens du blanc avec SetColorRGB  -> FFFFFF

> `[2019-03-19 22:46:35][DEBUG] : execute function with options ->{"title":"ffffff","message":"","utid":"1553031717568"}<-
> [2019-03-19 22:46:35][DEBUG] : Envoi du message: EP=03&color=ffffff vers CmdAbeille/c638/setColourRGB
> [2019-03-19 22:46:35][DEBUG] : Topic: ->Abeille/c638/colorRouge<- Value ->100<-
> [2019-03-19 22:46:35][DEBUG] : Topic: ->Abeille/c638/colorVert<- Value ->100<-
> [2019-03-19 22:46:35][DEBUG] : Topic: ->Abeille/c638/colorBleu<- Value ->100<-
> [2019-03-19 22:46:35][DEBUG] : Topic: ->Abeille/c638/ColourRGB<- Value ->ffffff<-
> [2019-03-19 22:46:39][DEBUG] : execute function with options ->{"utid":"1553031717568"}<-
> [2019-03-19 22:46:39][DEBUG] : Envoi du message: EP=03&X=a294&Y=53d0 vers CmdAbeille/c638/setColour
> [2019-03-19 22:47:03][DEBUG] : Envoi du message: Version vers TempoCmdAbeille/Ruche/getVersion&time=1553032043
> [2019-03-19 22:47:03][DEBUG] : Envoi du message: getNetworkStatus vers TempoCmdAbeille/Ruche/getNetworkStatus&time=1553032047
> [2019-03-19 22:47:03][DEBUG] : Get etat and Level des ampoules
> [2019-03-19 22:47:03][DEBUG] : GetEtat/GetLevel: c638
> [2019-03-19 22:47:03][DEBUG] : Envoi du message: EP=03&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/c638/ReadAttributeRequest&time=1553032026
> [2019-03-19 22:47:03][DEBUG] : Envoi du message: EP=03&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/c638/ReadAttributeRequest&time=1553032026
> [2019-03-19 22:47:07][DEBUG] : Topic: ->Abeille/c638/Link-Quality<- Value ->48<-
> 
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]-----
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]Msg Received: Topic: {CmdAbeille/c638/setColourRGB} => EP=03&color=ffffff
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]Type: CmdAbeille Address: c638 avec Action: setColourRGB
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]msg: EP=03&color=ffffff rouge: 255 vert: 255 bleu: 255
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]processCmd call with Command parameters: setColourRGB-1-address-c638-R-255-G-255-B-255-destinationEndPoint-03-
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]begin processCmd function
> **AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]colourX: 4f6e colourY: 5391**
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]Dest:/dev/ttyUSB1 cmd:00B7 len:000B datas:02c63801034f6e53910001
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]len data: 22
> AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]checksum computed: 160`

**Comment by Asyrah** [comment]
Blanc ("title":"ffffff")
AbeilleMQTTCmd 2019-03-19 22:46:35[DEBUG]colourX: **4f6e** colourY: **5391**

Rouge ("title":"ff0000")
AbeilleMQTTCmd 2019-03-19 23:00:09[DEBUG]colourX: **a294** colourY: **53d0**

Vert ("title":"00ff00")
AbeilleMQTTCmd 2019-03-19 23:02:18[DEBUG]colourX: **4c33** colourY: **9867**

Bleu ("title":"0000ff")
AbeilleMQTTCmd 2019-03-19 23:04:14[DEBUG]colourX: **261a** colourY: **0f3d**

En faisant quelques tests de comparaison avec les valeurs des formats des codes couleurs (Hexa -> RGB),  la conversion des couleurs désirées semble fonctionnel via la commande SetColorRGB de type EP=03&color=#title#. J'obtiens bien chacune des couleurs demandées

(https://web-color.aliasdmc.fr/couleur-web-white-rgb-hsl-hexa.html?search_text=rgb%28255%2C255%2C255%29#bloc-search-color)

**Comment by Asyrah** [comment]
En faisant quelques tests de comparaison de valeurs des formats des codes couleurs,  j'obtiens les couleurs désirées via la commande SetColorRGB de type EP=03&color=#title#.

(https://web-color.aliasdmc.fr/couleur-web-white-rgb-hsl-hexa.html?search_text=rgb%28255%2C255%2C255%29#bloc-search-color)

**Comment by Asyrah** [comment]
Je viens de refaire des tests ce soir sur le ruban RGB Osram, tout est fonctionnel sur la version abeille "47c75f16ad0241536851baf37bb405a248aa4a6d"

ON/OFF/Toogle ok
Niveau de luminosité ok
Bouton blanc ok
Bouton bleu ok
Bouton rouge ok
Bouton vert ok

**Comment by KiwiHC16** [comment]
Super !!!

Avec ton choix de couleur ou avec les couleurs d'origine d'Abeille ?

**Comment by Asyrah** [comment]
Les 2 sont fonctionnels : les couleurs d'origine Abeille (blanc, rouge, vert, bleu) et mes couleurs personnalisées 👍 

Testé à l'instant avec la dernière version du master ("c3282ed755d88f41d4da4419ee3f1d7c74345f69")

**Comment by KiwiHC16** [comment]
Nickel, je suppose que je peux fermer le cas maintenant.
