### ISSUE TITLE
TRADFRI bulb E27 opal 1000lm: level

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#61]
Mettre sur la command level un min et un max entre 0 et 100% et mettre a echelle la valeur qui est entre 0 et 255.

{"topic":"Abeille\/f1dc\/0008-0000","minValue":"0","maxValue":"100","timeline::enable":"0","calculValueOffset":"#value# \/ 255 * 100",

A mettre dans JSON

**Comment by zoozbiro** [comment]
<img width="1471" alt="capture d ecran 2018-01-31 a 20 52 32" src="https://user-images.githubusercontent.com/4723029/35644299-dc2f7bba-06c8-11e8-8176-4d5e477cae38.png">
<img width="445" alt="capture d ecran 2018-01-31 a 20 54 13" src="https://user-images.githubusercontent.com/4723029/35644321-ef29588a-06c8-11e8-9664-80b898213104.png">

**Comment by KiwiHC16** [comment]
Included.
