### ISSUE TITLE
Eurotronic Spirit 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#610]

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues?utf8=✓&q=eurotronic+

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098

Thermostat Cluster:
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/1003

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Consigne/Temperature set/get ok.
Reporting to setup.
Controle du taux d ouverture en direct sans consigne de température.

**Comment by KiwiHC16** [comment]
https://github.com/Koenkk/zigbee-shepherd-converters/pull/254

**Comment by KiwiHC16** [comment]
If you turn TRV Mode to 01 (Attribut 0x4000) then you can drive the valve with Attribut Set Valve Position (0x4001). Then you can get the valve position with Attribut Pi Heating (0x0008)

**Comment by KiwiHC16** [comment]
Closing this issue as main fonctions look in place. If specific issue then open a new case.

**Comment by Tulan** [comment]
Hi, 
with the end of winter I have created a Jeedom Mode to switch Off thermostats & all Spirit heads.

It seems the "Off" action don't do anything, as I can see Heating still changing during day and night.

Do you have an idea or do you need any log ?
