### ISSUE TITLE
Alexa: Retour Etat et Level objets type ampoule et spot

### ISSUE THREAD

**Issue by Ricardo544** [KiwiHC16/Abeille#613]
Petit soucis avec le retour d'état dans l'appli mobile Jeedom et le plugin Alexa. Il y a dans chaque objet "lumière" (Ex : spot, ampoule, etc....) deux types d'infos "Level" et "état", ce faisant les objets type ampoule, spot sont toujours en état allumés dans ces deux plugins quelque soit l'action effectuée.

Le binaire "état" passe bien de 0 à 1 selon si on éteint la lampe ou on l'allume, en revanche le numérique "level" ne revient pas à 0, ce qui pose problème dans les plugins mobile et Alexa puisque le type générique pour la remontée de l'état est basé sur la commande info "level" dans le plugin abeille.
J'ai tenté de mettre l'info générique "Lumière état" sur la commande binaire "état", cela fonctionne bien les ampoules ou spots sont bien vus comme éteints ou allumés selon l'action effectuées, par contre suite à cette modification il n'est plus possible d'avoir accès à l'objet dans l'application Amazon Alexa sous Android, dés que je remet le retour d'état sur l'objet "level" l'objet est de nouveau accessible dans l'application Amazon Alexa sous Android et les ampoules ou spots sont de nouveau toujours en état allumés puisque le "level" ne revient jamais à 0.

@+

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Salut Ricardo,
Je ne possède pas Alexa et n'ai jamais utilisé le plugin Alexa Jeedom (Je suppose que c'est ca que tu utilises).
Perso j'ai la solution home bridge qui utilise les parametres "Type Générique" comme source.
Mais procédons par étapes. Commencons par le basique
Peux tu prendre une ampoule (me donner son nom) ?
Si tu l'allume depuis Abeille, est ce qu'elle s'allume ? idem si tu éteints ?
Est ce que tu as le retour d'état allumé/éteinte qui fonctionne ?

**Comment by Ricardo544** [comment]
Hello,

Oui pas de soucis tout cela est fonctionnel.
Concernant le plugin Alexa il fonctionne de la même manière que le Plugin Mobile --> tu assignes des génériques aux objets que tu veux voir remonter dans l'appli Mobile Jeedom ou Alexa.

**Comment by Ricardo544** [comment]
Merde j'ai fermé l'issue

**Comment by Ricardo544** [comment]
Le problème est identique quelque soit la marque de l'ampoule ou spot, ampoule Innr ou Ikea et spot Ikea même soucis. Tout est correct sur le DashBoard de Jeedom.
Voici quelques images pour étayer la chose : 
Le DasBoard jeedom ou l'on voit bien l'état et le level :  
![etat-level](https://user-images.githubusercontent.com/48009784/53399084-87ad8e80-39ab-11e9-89e2-e85f51402eac.jpg)
Le paramètre générique pour l'état : 
![generique-pour-etat](https://user-images.githubusercontent.com/48009784/53399169-b3c90f80-39ab-11e9-8aaa-3724cb05933e.jpg)
Le paramètre générique pour le level : 
![generique-pour-level](https://user-images.githubusercontent.com/48009784/53399193-c5121c00-39ab-11e9-9d8a-d95c792fb822.jpg)

C'est la valeur du Level qui est renvoyée à l'appli mobile Jeedom et à l'appli Alexa, donc cette valeur est toujours > 0 sauf si tu joues avec le Slider "SetLevel" qui te permet de faire varier l'intensité de ton ampoule ou spot.

**Comment by Ricardo544** [comment]
Voici des copies d'écran de l'appli mobile Jeedom et l'appli Alexa sur Android : 

Appli mobile jeedom : 
![screenshot_20190226-102114_jeedom](https://user-images.githubusercontent.com/48009784/53401969-2092d880-39b1-11e9-807e-23052f08c29b.png)

Appli Alexa : 
![screenshot_20190226-101931_amazon_alexa](https://user-images.githubusercontent.com/48009784/53402007-32747b80-39b1-11e9-80d0-04b06d8ffdc8.png)

Toutes les ampoules que tu vois "activées" ne sont pas allumées, elles on simplement leurs "Level" > 0 dans Abeille.

Etat de la l'ampoule mentionnée dans le message précédent : 
![screenshot_20190226-102019_amazon_alexa](https://user-images.githubusercontent.com/48009784/53402078-533cd100-39b1-11e9-8a98-e0dcd6342189.png)

Comme tu peux le voir dans le message précédent elle est bien à l'état éteint sur le DashBoard Jeedom mais pas sur l'appli Jeedom et l'appli Alexa, a cause de l'item Level qui ne revient pas à 0 lorsque l'ampoule est éteinte.

**Comment by Ricardo544** [comment]
D'autre copies d'écran du téléphone sur l'appli Alexa suite à modification du générique pour l'item "Etat" en le passant à "Lumière Etat" et en supprimant le générique sur l'item "Level"
On voit que la lampe à bien le statut "Desactivé" (éteint) nous sommes bien en phase avec le DashBoard Jeedom.
![screenshot_20190226-104259_amazon_alexa](https://user-images.githubusercontent.com/48009784/53403630-4b326080-39b4-11e9-9216-7dba7f0a5c93.png)

Mais impossible d'avoir accès au panneau (Voir image 3 du message précédent) pour pouvoir gérer le slider afin de pouvoir faire varier l'intensité de l'ampoule ou du spot, il n'affiche jamais le panneau de gestion.

![screenshot_20190226-104334_amazon_alexa](https://user-images.githubusercontent.com/48009784/53403718-75841e00-39b4-11e9-9835-2a7fe5891494.png)

 Il y a bien un rapport entre Etat et Level qui met le bordel entre les applications

**Comment by Ricardo544** [comment]
A partir du moment ou je repasse l'item "Level" en mode générique "Lumière Etat" l'appli jeedom mobile et l'appli Alexa ne sont plus en phase avec l'état de l'ampoule sur le DashBoard, en revanche suite à cette manipulation le panneau de gestion de l'ampoule, slider, allumer éteindre et de nouveau accessible dans l'appli Amazon Alexa !!
Il faudrait peut-être faire comme sur le protocole Z-Wave ou le statut Etat et Level ne font qu'un : 
Ampoule éteinte l'état passe à 0 -- Ampoule allumée l'état passe à "n" variant de 1 à 99, forcement > 0 donc statut de la lampe "Allumé" sur le DashBoard Jeedom et l'appli mobile Jeedom+appli Amazon Alexa
De plus lorsque tu joues avec le slider sur une ampoule Z-wave la valeur du slider modifie l'état à "n" donc > 0

**Comment by KiwiHC16** [comment]
Pourquoi c'est l'info level qui est envoyée ? Dans les équipements ZigBee, il y a bien deux valeurs distinctes: Etat et Level.

Pourquoi dans le champ Type Générique on a la valeur Generique ? Avec Homebridge il faut une valeur specifique qui depend du type. As tu ouverts la discussion vers le plugin Alexa pour savoir ce dont il a besoin ?

**Comment by KiwiHC16** [comment]
Je n'ai jamais testé le Plugin Mobile avec Abeille.

**Comment by Ricardo544** [comment]
> 
> 
> Pourquoi c'est l'info level qui est envoyée ? Dans les équipements ZigBee, il y a bien deux valeurs distinctes: Etat et Level.
> 
> Pourquoi dans le champ Type Générique on a la valeur Generique ? Avec Homebridge il faut une valeur specifique qui depend du type. As tu ouverts la discussion vers le plugin Alexa pour savoir ce dont il a besoin ?

C'est pareil avec le plugin Alexa, il faut une valeur spécifique de type générique. Ce qui est fait dans mon cas et c'est ce que tu fais pas défaut lorsque tu crées un nouvel équipement dans le plugin et pour cela je te remercies en passant parce que dans les autres plugins de jeedom ces paramètres ne sont jamais renseignés par défaut.

**Comment by Ricardo544** [comment]
il faudrait que tu passes la valeur du Level à 0 lors de l'extinction de l'ampoule ou du spot et cela résoudrait le problème dans les 2 applis mobiles (Jeedom et Alexa), il faut également que tu repasses la valeur du Level avec la valeur du SetLevel lors de l'allumage de l'ampoule ou du spot et normalement le tour est joué.
Certainement plus facile à dire qu'a faire.

**Comment by KiwiHC16** [comment]
```
A partir du moment ou je repasse l'item "Level" en mode générique "Lumière Etat" l'appli jeedom mobile et l'appli Alexa ne sont plus en phase avec l'état de l'ampoule sur le DashBoard, en revanche suite à cette manipulation le panneau de gestion de l'ampoule, slider, allumer éteindre et de nouveau accessible dans l'appli Amazon Alexa !!
Il faudrait peut-être faire comme sur le protocole Z-Wave ou le statut Etat et Level ne font qu'un :
Ampoule éteinte l'état passe à 0 -- Ampoule allumée l'état passe à "n" variant de 1 à 99, forcement > 0 donc statut de la lampe "Allumé" sur le DashBoard Jeedom et l'appli mobile Jeedom+appli Amazon Alexa
De plus lorsque tu joues avec le slider sur une ampoule Z-wave la valeur du slider modifie l'état à "n" donc > 0
```

Tu peux faire cela en passant par des Virtual je suppose.

Peux tu demander à l'auteur du module Alexa ce qu'il attend comme variable pour son plugin. 
Dans le plugin homebridge, il y a cette doc: https://nebzhb.github.io/jeedom_docs/plugins/homebridge/fr_FR/#tocAnchor-1-10

**Comment by Ricardo544** [comment]
Oui j'ai vu la doc de homebridge et dans la partie lumière on voit bien que le slider passe bien l'état de 0 a 100 et ce fonctionnement est parfait, par contre il faut que l'item Etat soit typé numérique et non binaire.
Concernant les virtuels oui je pourrais effectivement passer par ce biais là, mais c'est un peu couillon de vouloir réinventer la roue.

**Comment by KiwiHC16** [comment]
Pour l'instant c'est difficile pour moi d'avancer sur ce sujet sans avoir des spécifications claires.
Il y a qq sujets en attente pour lesquels je sais ce qu'il faut faire. Pour celui ci, il faut soit avoir les spec soit faire du reverse engineering et c est tres consommateur en temps.
Essayes de trouver des specs.

**Comment by Ricardo544** [comment]
T’inquiètes pas, ce n'est pas grave en soit, le problème est identique avec les ampoules Xiaomi (Plugin de Lunarok) tu ne peux pas avoir accès aux slider dans l'appli Amazon Alexa.
On ne va pas user le soleil la dessus.
Toutes les informations sont correctement renseignées au niveau "Génériques" quoi faire de plus ?
A part comme je disais plus haut le fait de mettre à 0 l'item "Level" lors de l'extinction de l'ampoule, je vois pas trop.

**Comment by KiwiHC16** [comment]
Je peux faire des variables dédiées dans les objets abeilles (une sorte de virtuel dans l objet) pour le rendre compatible. 
Je garde la sujet ouvert jusqu'a ce que j'ai un peu de temps.

**Comment by Ricardo544** [comment]
Pas de soucis. Je suis à ta disposition si tu veux des infos complémentaires ou faire des tests.
@+

**Comment by KiwiHC16** [comment]
Ok, mais probablement d'ici qq mois.

**Comment by pilou689** [comment]
Merci @Ricardo544 pour l'astuce de mettre la commande Etat en numérique et de lui mettre une valeur Générique, puis de passer la valeur de Level à "Lumière Etat". C'est tordu mais Alexa ne me dit plus "je ne sais pas d'où vient le problème" après avoir éxécuté avec succés le changement d'intensité lumineuse.
@KiwiHC16 je pense qu'il manque une valeur "Lumière level" pour la défition des valeurs des commmandes pour les lumières, qui viendrait s'ajouter à "Lumière couleur" et "Lumière état".
Pour info je tourne sous Jeedom avec Alexa et une Zigate (3.0.f) pour gérer des ampoules Philips Hue white et une Hue white ambiance.

**Comment by Ricardo544** [comment]
Hello pilou689,

De rien. Bonne journée à toi.

**Comment by KiwiHC16** [comment]
Je dois limiter le scope de mes dev sinon je ne m en sort pas. Je ne vais pas supporter Alexa. Si quelqu'un peut regarder le sujet....
