### ISSUE TITLE
Kemar's System to stabilize after upgrade: OSRAM TimeOut

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#615]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=702308#p702308

**Comment by KiwiHC16** [comment]
> Edit: Exemple d'un comportement chelou. Ce matin, l'ampoule est en timeout. Je lance un "Toggle" depuis le dashboard, et elle s'allume ?!? Puis elle repasse tranquillement en couleur normal, plus de timeout.

Les timeout fonctionnent simplement en observant les messages provenant des équipements. La date du dernier message est conservé dans Abeille et au bout d'une heure, warning orange, au bout de deux heures warning rouge. Donc dans ton cas l'ampoule doit bien etre dans le réseau zigbee mais Abeille n'a pas recu de message de celle ci.

> une ampoule "OSRAMClassicA60Wclear-LIGHTIFY"
On a plusieurs raisons pour recevoir des messages de l ampoule. Soit elles les evoient toute seule, soit toutes les 15 min Abeille fait un "ping" soit toutes les minutes Abeille demande l'état de l ampoule. Visiblement elle ne remonte rien d'elle même. Pourtant on lui a démandé d'après le modèle mais je ne sais pas si cela fonctionne car je n'ai pas cette ampoule pour tester. Il est fort probable que cela ne fonctionne pas. Ensuite si le champ "batterie type" est vide on la ping.
On va commencer pas investiguer pour ca ne fonctionne pas dans ton cas.

![capture d ecran 2019-02-27 a 09 20 22](https://user-images.githubusercontent.com/8549674/53475716-eab52900-3a70-11e9-8598-3172690455ce.png)
Est ce que ce champ est bien vide ? (pas d'espace ou autre caracteres ?)

**Comment by KiwiHC16** [comment]
Peux tu aussi partager le log Abeille ?

**Comment by Marc--** [comment]
Salut, je confirme le champ batteries est bien vide. Voici le log Abeille.
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/2909268/Abeille.log)

**Comment by KiwiHC16** [comment]
Le log ne dure que 5 minutes. Il n'y a pas d'info interessante.
En ssh peux faire un 
`tail -f Abeille | tee AbeilleTimeOutDebug.log`
Laisser tourner 3 heures et me partager le fichier AbeilleTimeOutDebug.log

**Comment by Marc--** [comment]
Ok, voici un log qui tourne depuis 14h. J'ai jetté un oeil, et je vois un "ping" envoyé tous les 15mn aux équipements sur secteur. La différence avec les autres routeurs de mon réseau, c'est que celui ci ne semble pas répondre.

Info qui me semblent utiles , les routeurs sont : 
Abeille/3086 --> Philips HUE Go
Abeille/521a --> prise Ikea
Abeille/5f2c --> l'ampoule qui pose problème

En gros j'ai le ping : 

> [2019-02-27 15:30:02][DEBUG] : Ping NE with 220V to check Online status
[2019-02-27 15:30:02][DEBUG] : Ping: 3086
[2019-02-27 15:30:02][DEBUG] : Envoi du message: Default vers CmdAbeille/3086/Annonce
[2019-02-27 15:30:07][DEBUG] : Ping: 5f2c
[2019-02-27 15:30:07][DEBUG] : Envoi du message: Default vers CmdAbeille/5f2c/Annonce
[2019-02-27 15:30:12][DEBUG] : Ping: 521a
[2019-02-27 15:30:12][DEBUG] : Envoi du message: Default vers CmdAbeille/521a/Annonce
[2019-02-27 15:30:12][DEBUG] : Topic: ->Abeille/521a/Link-Quality<- Value ->78<-

Ici le 521a à envoyé une info de Link quality.

Une minute après j'ai le 3086 qui envoie aussi une info : 
> [2019-02-27 15:31:01][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->135<-


Mais la seule fois ou je revois le 5f2c dans le log, c'est 15mn plus tard : 

> [2019-02-27 15:45:07][DEBUG] : Ping: 5f2c
[2019-02-27 15:45:07][DEBUG] : Envoi du message: Default vers CmdAbeille/5f2c/Annonce


Donc Abeille doit logiquement penser que l'ampoule n'est plus la.

Mon raisonnement est logique ?

[AbeilleTimeOutDebug.log](https://github.com/KiwiHC16/Abeille/files/2911311/AbeilleTimeOutDebug.log)

**Comment by Marc--** [comment]
Et du coup je viens de tester l'envoi de commandes, ça passe sans problème. 

Et du coup l'objet quitte le "time-out" (qui est basé sur l'age d'un topic mqtt ?) jusqu'à ce qu'Abeille trouve qu'elle est resté trop longtemps sans répondre.

> [2019-02-27 17:41:18][DEBUG] : execute function with options ->{"slider":"13","utid":"1551285231288"}<-
[2019-02-27 17:41:18][DEBUG] : Envoi du message: EP=03&Level=13&duration=10 vers CmdAbeille/5f2c/setLevel
[2019-02-27 17:41:18][DEBUG] : Envoi du message: EP=03&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/5f2c/ReadAttributeRequest&time=1551285680
[2019-02-27 17:41:19][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->150<-
[2019-02-27 17:41:19][DEBUG] : Envoi du message: EP=03&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/5f2c/ReadAttributeRequest&time=1551285682
[2019-02-27 17:41:19][DEBUG] : -
[2019-02-27 17:41:19][DEBUG] : -
[2019-02-27 17:41:19][DEBUG] : Topic: ->Abeille/5f2c/0006-03-0000<- Value ->1<-
[2019-02-27 17:41:19][DEBUG] : -
[2019-02-27 17:41:19][DEBUG] : -
[2019-02-27 17:41:21][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->150<-
[2019-02-27 17:41:21][DEBUG] : -
[2019-02-27 17:41:21][DEBUG] : -
[2019-02-27 17:41:21][DEBUG] : Topic: ->Abeille/5f2c/0006-03-0000<- Value ->1<-
[2019-02-27 17:41:21][DEBUG] : -
[2019-02-27 17:41:21][DEBUG] : -
[2019-02-27 17:41:23][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->153<-
[2019-02-27 17:41:23][DEBUG] : -
[2019-02-27 17:41:23][DEBUG] : -
[2019-02-27 17:41:23][DEBUG] : Topic: ->Abeille/5f2c/0008-03-0000<- Value ->33<-
[2019-02-27 17:41:23][DEBUG] : -
[2019-02-27 17:41:23][DEBUG] : -
[2019-02-27 17:41:29][DEBUG] : execute function with options ->{"utid":"1551285231288"}<-
[2019-02-27 17:41:29][DEBUG] : Envoi du message: Action=Off&EP=03 vers CmdAbeille/5f2c/OnOff
[2019-02-27 17:41:29][DEBUG] : Envoi du message: EP=03&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/5f2c/ReadAttributeRequest&time=1551285691
[2019-02-27 17:41:30][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->141<-
[2019-02-27 17:41:30][DEBUG] : Envoi du message: EP=03&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/5f2c/ReadAttributeRequest&time=1551285693
[2019-02-27 17:41:30][DEBUG] : -
[2019-02-27 17:41:30][DEBUG] : -
[2019-02-27 17:41:30][DEBUG] : Topic: ->Abeille/5f2c/0006-03-0000<- Value ->0<-
[2019-02-27 17:41:30][DEBUG] : -
[2019-02-27 17:41:30][DEBUG] : -
[2019-02-27 17:41:32][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->147<-
[2019-02-27 17:41:32][DEBUG] : -
[2019-02-27 17:41:32][DEBUG] : -
[2019-02-27 17:41:32][DEBUG] : Topic: ->Abeille/5f2c/0006-03-0000<- Value ->0<-
[2019-02-27 17:41:32][DEBUG] : -
[2019-02-27 17:41:32][DEBUG] : -
[2019-02-27 17:41:34][DEBUG] : Topic: ->Abeille/5f2c/Link-Quality<- Value ->150<-
[2019-02-27 17:41:34][DEBUG] : -
[2019-02-27 17:41:34][DEBUG] : -
[2019-02-27 17:41:34][DEBUG] : Topic: ->Abeille/5f2c/0008-03-0000<- Value ->33<-

**Comment by KiwiHC16** [comment]
Oui ta comprehension est la bonne.
Il est possible que des messages soient perdus de temps en temps.
Quelle version d'Abeille as tu ?
Deux choses qu'on peut faire:
- Change le tempo de 0,3s à 10s par exemple dans la ligne https://github.com/KiwiHC16/Abeille/blob/master/resources/AbeilleDeamon/CmdToAbeille.php#L503
et regardes de la meme bacon ce qu'il se passe. 
- Recuperes les logs AbeilleMQTT et AbeilleParser, le premier nous donnera les commandes envoyées et le second command la zigate les as traités.

**Comment by Marc--** [comment]
Hummmff désolé, je n'ai pas reçu les notifs, je crois que gmail a classé github dans le spam.

Version Abeille: 2019-02-12 01:02:10

Pour le reste, je viens de lancer tout ça, et je regarde le résultat ce midi.

**Comment by Marc--** [comment]
J'ai donc modifié le "sleep" à 10s ce matin. Je ne vois pas de changement. Et je n'ai pas trop compris ce qu'il modifie.

Concernant les logs, comportement identique.  Abeille indique bien avoir envoyé les pings, AbeilleMQTTCmd confirme avoir envoyé les pings, mais AbeilleParser n'a aucune trace de messages depuis l'ampoule "5f2c".

Donc je sèche. Une ampoule qui fonctionne quand je lui envoie des commandes mais qui ne répond pas au ping ! Je pense que je vais en commander une 2eme pour voir si j'ai un comportement identique. Je commence à me demander si elle n'est pas défectueuse !

Voici un extrait qui m'a amené à ces conclusions.

***** Abeille *****
--> Commandes ordonnées par Abeille. 
11:45:03 Ping: 3086
11:45:08 Ping: 5f2c
11:45:13 Ping: 521a

> [2019-03-07 11:45:02][DEBUG] : Starting cron15 ------------------------------------------------------------------------------------------------------------------------
> [2019-03-07 11:45:02][DEBUG] : Check USB driver potential crash
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/SW-SDK<- Value ->030F<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/Short-Addr<- Value ->0000<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/IEEE-Addr<- Value ->00158d0000c0e00E<-
> [2019-03-07 11:45:02][DEBUG] : IEEE-Addr;00158d0000c0e00E;Ok pas de changement de l adresse IEEE, je ne fais rien.
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/PAN-ID<- Value ->9d4e<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/Ext_PAN-ID<- Value ->a4c60B0F0C34903b<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/Ruche/Network-Channel<- Value ->11<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->84<-
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:02][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : Topic: ->Abeille/3086/0006-0B-0000<- Value ->0<-
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->84<-
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : Topic: ->Abeille/3086/0008-0B-0000<- Value ->51<-
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : -
> [2019-03-07 11:45:03][DEBUG] : Ping NE with 220V to check Online status
> [2019-03-07 11:45:03][DEBUG] : Ping: 3086
> [2019-03-07 11:45:03][DEBUG] : Envoi du message: Default vers CmdAbeille/3086/Annonce
> [2019-03-07 11:45:08][DEBUG] : Ping: 5f2c
> [2019-03-07 11:45:08][DEBUG] : Envoi du message: Default vers CmdAbeille/5f2c/Annonce
> [2019-03-07 11:45:13][DEBUG] : Ping: 521a
> [2019-03-07 11:45:13][DEBUG] : Envoi du message: Default vers CmdAbeille/521a/Annonce
> [2019-03-07 11:45:13][DEBUG] : Topic: ->Abeille/521a/Link-Quality<- Value ->120<-
> [2019-03-07 11:45:13][DEBUG] : -
> [2019-03-07 11:45:13][DEBUG] : -
> [2019-03-07 11:45:13][DEBUG] : Topic: ->Abeille/521a/0000-01-0005<- Value ->TRADFRI control outlet<-
> [2019-03-07 11:45:13][DEBUG] : Update ONLINE Status
> [2019-03-07 11:45:15][DEBUG] : -
> [2019-03-07 11:45:15][DEBUG] : -
> [2019-03-07 11:45:18][DEBUG] : Ending cron15 ------------------------------------------------------------------------------------------------------------------------


***** AbeilleMQTTCmd *****
--> Envoi des annonces aux equipements. Sens Abeille --> Zigate
11:45:03 vers 3086
11:45:08 vers 5f2c
11:45:13 vers 521a

> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]-----
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]Msg Received: Topic: {CmdAbeille/3086/Annonce} => Default
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]Type: CmdAbeille Address: 3086 avec Action: Annonce
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]Preparation de la commande annonce pour default
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]processCmd call with Command parameters: ReadAttributeRequest-1-address-3086-clusterId-0000-attributeId-0005-EP-01-
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]begin processCmd function
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]data: 0230860101000000000000010005 length: 000e
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]Dest:/dev/ttyUSBzigate cmd:0100 len:000e datas:0230860101000000000000010005
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]len data: 28
> AbeilleMQTTCmd 2019-03-07 11:45:03[DEBUG]checksum computed: 191
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]-----
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]Msg Received: Topic: {CmdAbeille/5f2c/Annonce} => Default
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]Type: CmdAbeille Address: 5f2c avec Action: Annonce
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]Preparation de la commande annonce pour default
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]processCmd call with Command parameters: ReadAttributeRequest-1-address-5f2c-clusterId-0000-attributeId-0005-EP-01-
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]begin processCmd function
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]data: 025f2c0101000000000000010005 length: 000e
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]Dest:/dev/ttyUSBzigate cmd:0100 len:000e datas:025f2c0101000000000000010005
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]len data: 28
> AbeilleMQTTCmd 2019-03-07 11:45:08[DEBUG]checksum computed: 122
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]-----
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]Msg Received: Topic: {CmdAbeille/521a/Annonce} => Default
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]Type: CmdAbeille Address: 521a avec Action: Annonce
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]Preparation de la commande annonce pour default
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]processCmd call with Command parameters: ReadAttributeRequest-1-address-521a-clusterId-0000-attributeId-0005-EP-01-
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]begin processCmd function
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]data: 02521a0101000000000000010005 length: 000e
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]Dest:/dev/ttyUSBzigate cmd:0100 len:000e datas:02521a0101000000000000010005
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]len data: 28
> AbeilleMQTTCmd 2019-03-07 11:45:13[DEBUG]checksum computed: 65
> AbeilleMQTTCmd 2019-03-07 11:46:01[DEBUG]-----


***** AbeilleParser *****
--> Traitement par la Zigate. Sens Zigate --> Abeille.
11:45:02 depuis 3086
11:45:13 depuis 521a
Mais rien sur 5f2c !

> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: f8
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:02[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: f8; Src Addr : 3086; End Point : 0B; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: f9
> AbeilleParser 2019-03-07 11:45:02[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:02[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: f9; Src Addr : 3086; End Point : 0B; Cluster ID : 0008; Attr ID : 0000; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : 33
> AbeilleParser 2019-03-07 11:45:03[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: fa
> AbeilleParser 2019-03-07 11:45:03[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:08[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: fb
> AbeilleParser 2019-03-07 11:45:08[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:13[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: fc
> AbeilleParser 2019-03-07 11:45:13[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
> AbeilleParser 2019-03-07 11:45:13[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: fc; Src Addr : 521a; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0016; Data byte list : ->TRADFRI control outlet<-
> AbeilleParser 2019-03-07 11:46:01[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00

**Comment by Marc--** [comment]
Ce soir j'ai testé en laissant l'ampoule allumée pour voir si elle répondait au ping. Rien non plus. Par contre toujours pas de soucis pour envoyer les commandes on / off.

Demain je dois recevoir la nouvelle, je ferai de nouveaux tests.

**Comment by Marc--** [comment]
Ca y est, nouvelle ampoule installée ce soir. Et malheureusement même comportement. Donc ce n'est (probablement) pas mon ampoule en particulier.

As tu une idée de piste ? Je vais poster sur le forum ce soir pour chercher d'autres utilisateurs d'ampoules Osram, voir si je suis seul dans ce cas ?

Autre chose qui m'étonne un peu. En regardant les logs, je vois qu'il est régulièrement lancé un "Get etat and Level des ampoules". Mais chose bizarre, l'ampoule Osram n'est pas interrogée. L'objet 3086 qu'on voit est une Hue GO. 

> [2019-03-08 19:32:01][DEBUG] : Get etat and Level des ampoules
> [2019-03-08 19:32:01][DEBUG] : GetEtat/GetLevel:
> [2019-03-08 19:32:01][DEBUG] : Envoi du message: EP=0B&clusterId=0006&attributeId=0000 vers CmdAbeille/3086/ReadAttributeRequest
> [2019-03-08 19:32:01][DEBUG] : Topic: ->Abeille/Ruche/PAN-ID<- Value ->9d4e<-
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : Topic: ->Abeille/Ruche/Ext_PAN-ID<- Value ->a4c60B0F0C34903b<-
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : Topic: ->Abeille/Ruche/Network-Channel<- Value ->11<-
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:01][DEBUG] : Envoi du message: EP=0B&clusterId=0008&attributeId=0000 vers CmdAbeille/3086/ReadAttributeRequest
> [2019-03-08 19:32:01][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->99<-
> [2019-03-08 19:32:01][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : Topic: ->Abeille/3086/0006-0B-0000<- Value ->1<-
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->102<-
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : Topic: ->Abeille/3086/0008-0B-0000<- Value ->51<-
> [2019-03-08 19:32:02][DEBUG] : -
> [2019-03-08 19:32:02][DEBUG] : -

**Comment by KiwiHC16** [comment]
Salut, je viens de voir que tu as envoyé plein d infos, je vais essayer de regarder demain ou après demain.

**Comment by Marc--** [comment]
Salut,

Merci pour la doc. Par contre je me sens bête, je ne vois pas du tout ou trouver les champs que tu demandes.

Dans la conf de l'ampoule, je n'ai pas de TimeOut dans informations. Ni de configuration avancée. 

Dans le plugin rien non plus. 

Je suis toujours en version "Stable du 11/2/2019". Il faut que je passe une mise a jour git ?

**Comment by KiwiHC16** [comment]
J'essaye de remettre en ligne la doc et je la complete avec les details. Je fais ca au plus vite.

**Comment by KiwiHC16** [comment]
https://kiwihc16.github.io/Abeille/fr_FR/cron.html#Poll1

**Comment by Marc--** [comment]
Impec merci !

Donc timeout à 60, mais aucune info sur le polling dans la ligne de configuration.

![2019-03-15 12_59_57-Abeille - Jeedom](https://user-images.githubusercontent.com/9568739/54430004-7510b480-4722-11e9-9c35-1a1e20239990.png)

**Comment by KiwiHC16** [comment]
Le probleme vient probablement de Default.
L'ampoule est bien la 5f2c ? C'est une OSRAM ?
```
[2019-03-07 11:45:03][DEBUG] : Envoi du message: Default vers CmdAbeille/3086/Annonce
[2019-03-07 11:45:08][DEBUG] : Ping: 5f2c
[2019-03-07 11:45:08][DEBUG] : Envoi du message: Default vers CmdAbeille/5f2c/Annonce
[2019-03-07 11:45:13][DEBUG] : Ping: 521a
[2019-03-07 11:45:13][DEBUG] : Envoi du message: Default vers CmdAbeille/521a/Annonce
```
Dans la config il manque "protocol":"OSRAM". Ce qui est la vieille méthode que je veut virer. Mais je ne suis pas allé au bout de mes modifs alors tu as ce problème.

Il faut que je change un bout de code.

**Comment by Marc--** [comment]
5f2c c'était bien la première ampoule avant que j'en achète une autre pour tester.

Pas d'urgence pour le changement hein, c'est déjà super d'avoir trouvé la cause. Bon courage pour toutes les modifs.

**Comment by KiwiHC16** [comment]
Ok je viens de faire une modif dans le master.
Peux tu tester avec le master ?

**Comment by Marc--** [comment]
Yep, je ne suis pas sur de mes manips la.

J'ai cloné le git Abeille, supprimé le répertoire du plugin (var/www/html/plugins/Abeille), copié le répertoire téléchargé par git puis restart le démon.

Je suis en "Version Abeille : Mid March Release", mais pas de changement dans le champ info.

La manip est-elle bonne ?

**Comment by KiwiHC16** [comment]
Ta manip semble bonne d'apres ta description.
Je viens de mettre 2 prises OSRAM dans mon systeme et je vais tester.
Je vais changer le titre pour etre plus en ligne avec le sujet.

**Comment by KiwiHC16** [comment]
Mes deux prises sont en timeout (elles fonctionnent), j'investigue et te tiens au courant.

**Comment by KiwiHC16** [comment]
Voila la correction est dans le master normalement.
Mais attention le master n'est pas super testé.
Bien faire des backups pour faire restaure en cas de soucis.

**Comment by Marc--** [comment]
Je viens de faire la mise à jour depuis Github, je te tiens au courant dans la journée.

Par contre, c'est normal les 346Mo du plugin ? Ca semble lié à GIT uniquement, je ne pense pas que ca concerne la version du market, mais je pose la question par curiosité : 

> '# ll /var/www/html/plugins/Abeille/.git/objects/pack
> total 311960
> -rwxrwxr-x 1 www-data www-data    348300 mars  19 10:22 pack-e43f8e57fb79d126a2aad6792b47f9e2a7d446b0.idx
> -rwxrwxr-x 1 www-data www-data 319090350 mars  19 10:22 pack-e43f8e57fb79d126a2aad6792b47f9e2a7d446b0.pack

C'est surement lié au fonctionnement de Git, mais comme je connais peu...

**Comment by KiwiHC16** [comment]
Visiblement c est git qui provoque ca.
www-data@Abeille:~/html/plugins/Abeille$ du -sh .git
325M	.git

Je pense que c est du aux videos que j'avais mis dans le plugin, ue j'ai retiré depuis. Je vais regarder si je peux faire du nettoyage. Je ne sais si c'est possible. Je regarde.

**Comment by KiwiHC16** [comment]
`git clone --depth=1 https://github.com/KiwiHC16/Abeille.git`

au lieu d'un 
`git clone https://github.com/KiwiHC16/Abeille.git`

Permet de limiter l espace disque utilisé passant de 325M à 65M.

Si on fait un `rm .git` on peut encore gagner 28M mais on pert git.

**Comment by Marc--** [comment]
Merci pour la commande git. 

Pour moi on peut fermer l'issue, l'ampoule répond bien depuis la dernière version ! Un grand merci à toi.

**Comment by KiwiHC16** [comment]
Ok super.
Alors je ferme.
