### ISSUE TITLE
"Network status failed" & methode de debug

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#619]
Salut
Depuis un redemarrage recent de mon OrangePi je n'ai plus de mise à jour de mes 2 capteurs de temp Xiaomi et j'avoue ne pas savoir par ou commencer pour debugguer.
Dans la config Abeille, le network status de la Zigate est donné "FAILED (zigbee event codes) 04".

Je suis pret à participer à la mise en place d'une methode de "self debug" si ca semble une bonne idée.

Merci pour toute aide.

**Comment by tcharp38** [comment]
Grace à la mine d'infos accessibles directement via la doc de la config plugin (merci kiwi), j'ai pu avancer un peu sans pour autant debloquer la situation.

Le "Network Status | Failed (ZigBee event codes): 04" affiché dans le tableau "Zigate" de la gestion du plugin semble venir de nul part.

Je suis sur
- Jeedom 3.1.7
- Abeille 2019-02-12 01:02:10 (last officelle)
- Zigate 3.0f

Une décomposition des logs donne la sequence suivante mais pas d'erreur visible

[2019-03-06 16:47:03][DEBUG] : Envoi du message: Version vers CmdAbeille/Ruche/getVersion
[2019-03-06 16:47:03][DEBUG] : Topic: ->Abeille/Ruche/SW-Application<- Value ->0003<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Envoi du message: getNetworkStatus vers CmdAbeille/Ruche/getNetworkStatus
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/SW-SDK<- Value ->030F<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Get etat and Level des ampoules
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/Short-Addr<- Value ->0000<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/IEEE-Addr<- Value ->00158d0001edfac2<-
[2019-03-06 16:47:04][DEBUG] : IEEE-Addr;00158d0001edfac2;Ok pas de changement de l adresse IEEE, je ne fais rien.
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/PAN-ID<- Value ->3c94<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/Ext_PAN-ID<- Value ->3284cf75025703e9<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : Topic: ->Abeille/Ruche/Network-Channel<- Value ->11<-
[2019-03-06 16:47:04][DEBUG] : -
[2019-03-06 16:47:04][DEBUG] : -

AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]-----
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/getVersion} => Version
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]Type: CmdAbeille Address: Ruche avec Action: getVersion
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]processCmd call with Command parameters: getVersion-Version-
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]begin processCmd function
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]Get Version
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]Dest:/dev/ttyUSB0 cmd:0010 len:0000 datas:
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]len data: 2
AbeilleMQTTCmd 2019-03-06 16:47:03[DEBUG]checksum computed: 16
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]-----
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]Msg Received: Topic: {CmdAbeille/Ruche/getNetworkStatus} => getNetworkStatus
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]Type: CmdAbeille Address: Ruche avec Action: getNetworkStatus
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]processCmd call with Command parameters: getNetworkStatus-getNetworkStatus-
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]begin processCmd function
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]Dest:/dev/ttyUSB0 cmd:0009 len:0000 datas:
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]len data: 2
AbeilleMQTTCmd 2019-03-06 16:47:04[DEBUG]checksum computed: 9

AbeilleSerialRead 2019-03-06 16:47:03[DEBUG]2019-03-06 16:47:03 -> 80000005950000001000
AbeilleSerialRead 2019-03-06 16:47:03[DEBUG]2019-03-06 16:47:03 -> 801000059a0003030F00
AbeilleSerialRead 2019-03-06 16:47:04[DEBUG]2019-03-06 16:47:04 -> 800000058c0000000900
AbeilleSerialRead 2019-03-06 16:47:04[DEBUG]2019-03-06 16:47:04 -> 80090016c3000000158d0001edfac23c943284cf75025703e90B00
	8009 = Network State response
	0016 = len
	c3 = chksm
	0000 = short addr
	ext addr = 00158d0001edfac2
	pan id = 3c94
	ext pan id = 3284cf75025703e9
	channel = 0B
	00

Est-ce que le "network status" est reellement fiable ?
Si oui, d'ou vient l'info affichée ?

Merci

**Comment by tcharp38** [comment]
J'ai progressé sur la compréhension du systeme et j'ai pu interroger la Zigate et m'apercevoir que sa liste de devices n'était pas en ligne avec celle d'Abeille.

Je ne sais pas ce qui s'est passé pour arriver à ce point, néanmoins apres un reappairage de mes 2 capteurs,  les choses semblent etre redevenues normales mais je constate que les "short addr" ont changé. Qui fait cette affectation ? La Zigate ? Abeille ?

A noter donc que le "Network status" de la page de gestion est à ignorer. L'erreur reportée est toujours la. Probablement un bug de cette version.

**Comment by KiwiHC16** [comment]
Salut @tcharp38,
En fait le message est probablement faux du fait de documentations divergentes. Dans les dernières versions du master, j'ai fait des changements sur la base de ce que j'ai trouvé dans le source de la zigate. En gros ne pas prendre en compte ce message, il apparait si on fait des demandes de démarrage du réseau zigbee alors qu'il est déjà démarré.
Les adresse courtes des objets sont fournies par la zigate et ils y a toute une liste de raison pour les attribuer et les changer. Mais abeille doit gérer le truc et c'est transparent pour l utilisateur.
Oui j'essaye de faire une doc mais il y a eu des changements important et la doc n'a pas forcement suivie.

**Comment by KiwiHC16** [comment]
Si le réseau est resté qq temps HS du fait de l upgrade alors les capteurs se sont peut être exclu du réseau d'eux même (problème des capteurs xiaomi) dans se cas il faut les re-inclure.

**Comment by KiwiHC16** [comment]
@tcharp38 as tu toujours des soucis ou on peut clore cette "issue" ?

**Comment by tcharp38** [comment]
Salut.
Avec mes manips actuelles dans lesquelles je coupe souvent ma box Jeedom, j'ai parfois le souci des capteurs qui n'envoient plus rien (widget rouge) à Jeedom. La Zigate a toujours la bonne liste donc j'en conclus que c'est le pb dont tu as parlé (les capteurs se sont exclus d eux meme).
Aurais tu un thread sur le sujet ? 
Y a t'il qqch a faire pour l'eviter ou remettre en service ? 
Je pense au cas ou la box est dans une maison secondaire qui peut n'avoir aucun courant pendant qq jours.

Mais pour repondre à ta question tu peux clore le sujet. Il n'est plus en ligne avec le pb restant.
Merci

**Comment by KiwiHC16** [comment]
Ok je le clos.
Ouvres une "issue" avec ton sujet précis si tu as besoin.
