### ISSUE TITLE
Comment "actionner" une prise connectée Tradfri ? 

### ISSUE THREAD

**Issue by pasoad** [KiwiHC16/Abeille#620]
Bonsoir,

Après avoir inclus avec succès une ampoule de la gamme tradfri, j'ai voulu connecté aussi un commutateur on/off de la gamme : 
![th](https://user-images.githubusercontent.com/46829490/53912199-b3d6a880-4058-11e9-8903-a451cec5657b.jpg)

Mais je n'arrive pas à comprendre comment l'actionner ? (car je n'ai que des champs "infos" dans les commandes)
![capture d ecran du 2019-03-06 21-44-28](https://user-images.githubusercontent.com/46829490/53912336-0c0daa80-4059-11e9-8f76-43a410f4aa9e.png)

PS: désolé pour mes questions qui sont certainement très bêtes pour vous...

**Comment by Marc--** [comment]
Salut, bizarre moi j'ai des commandes d'action. Tu peux essayer d'en créer une : 
Toggle / OnOff / Action=Toggle&EP=01

Au moins ça te permettra de tester. Après je ne peux pas te dire pourquoi elles n'ont pas été créées. Moi c'était automatique. Très étrange également leur nom sur ta capture : "Cmd de type inconnu" ???

Cf capture : 
![2019-03-06 22_48_53-abeille - jeedom](https://user-images.githubusercontent.com/9568739/53916333-3e6fd580-4062-11e9-96b0-50677e17d8a7.png)

**Comment by pasoad** [comment]
Parfait ! ça fonctionne.

Merci @Marc--

**Comment by pasoad** [comment]
En fait, cela ne résout pas le problème du "Cmd de type inconnu".

Quand je rajoute un autre device (par exemple un dimmer hue), je me retrouve avec le même problème pour l’absence de commandes actions. 

Et celle que tu m'a donné plus haut ne fonctionne pas avec cette télécommande...

**Comment by Marc--** [comment]
Oui, clairement ma manœuvre était juste la pour dépanner. Mais si tu as le soucis avec plusieurs abeilles, c'est qu'il y a un soucis !

Le problème, c'est que je n'ai pas le niveau pour te dépanner bien loin. Ma réflexion irait dans le sens suivant, mais à confirmer par un pro du plugin : 

Lors de l'inclusion, le plugin crée les objets a l'aide de modèles (JSON). Dans ton cas il ne crée pas toutes les commandes, et il affiche un nom "Cmd de type inconnu". Donc visiblement, soit il n'arrive pas à lire les fichiers, soit à écrire la conf ?


- Je commencerai par désinstaller / réinstaller tout le plugin si possible. 
- Puis je passe les logs en debug. 
- Je lance cette commande pour écrire les logs dans un fichier (car sinon on en a pas assez): "tail -f /var/www/html/log/Abeille | tee AbeilleCreationDebug.log"
- Je tente une inclusion.
- Je post le fichier de log créé.


Pense aussi à arrêter le "tail".

**Comment by KiwiHC16** [comment]
@pasoad , tu nous fais des trucs que je n'avais jamais encore vu.
Supprime l objet prise dans abeille, refais une inclusion et partage le log Abeille en étant en debug.
Apres on verra sil il est nécessaire de lancer la total comme proposé par Marc.

**Comment by pasoad** [comment]
Bonsoir,

Merci @Marc--  pour tes conseils. Je viens justement de refaire l'install ce soir parce qu je n'avais pas encore beaucoups d'équipements installés et maintenant c'est bon. Quand j'inclus un nouvel équipemment, je vois les champs "actions".

Je peux quand meme partager le log pour voir si il n'y a pas d'autres soucis...

Oui je sais @KiwiHC16, j'ai la poisse avec le matos électronique, mais je m'obstine ;)

**Comment by KiwiHC16** [comment]
C est bien de s'obstiner, moi ca fait maintenant 14 mois que je le fais et Abeille est le fruit de cette obstination !!!
;-)

**Comment by KiwiHC16** [comment]
Je suppose que c'est résolu. Je clos. Sinon on rouvre.

**Comment by pasoad** [comment]
Ok, je pense que c'est bon....

.....Pour l'instant :)
