### ISSUE TITLE
Plantage Abeille sur upgrade autre plugins

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#621]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=706601#p706601

**Comment by gubas** [comment]
Je confirme ce problème.
Mais en général un redémarrage du daemon et c'est reparti !

**Comment by KiwiHC16** [comment]
Oui j'i vu ca aussi, mais je n'ai pas le début d'une idée du pourquoi...

**Comment by Marc--** [comment]
Ouf je suis pas fou ^^ : #566
Et Zut, car pas de piste et un problème de plus à gérer. Ceci dit je confirme un restart et c'est reparti. Donc pour l'instant juste besoin de le documenter.

**Comment by KiwiHC16** [comment]
Mise a jour de homebridge pour essayer de comprendre le processus de mis a jour des plug in jeedom:

```
[2019-03-29 14:24:04][ALERT] : [START UPDATE]
[2019-03-29 14:24:04][ALERT] : Début de la mise à jour de : homebridge
[2019-03-29 14:24:04][ALERT] : Action de pré-update...
[2019-03-29 14:24:05][ALERT] : OK
[2019-03-29 14:24:05][ALERT] : Téléchargement du plugin...
[2019-03-29 14:24:05][ALERT] : Téléchargement de homebridge...
[2019-03-29 14:24:05][ALERT] : URL https://www.jeedom.com/market/core/php/downloadFile.php?id=2983&version=stable&jeedomversion=3.3.19&hwkey=xxxxxxxxxx&username=xxxxxxx&password=xxxxxxx&password_type=sha1
--2019-03-29 13:24:05--  https://www.jeedom.com/market/core/php/downloadFile.php?id=2983&version=stable&jeedomversion=3.3.19&hwkey=xxxx&username=xxxxx&password=xxxxx&password_type=sha1
Resolving www.jeedom.com (www.jeedom.com)... 193.70.3.228
Connecting to www.jeedom.com (www.jeedom.com)|193.70.3.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/jeedom/market/homebridge.zip'
0K .......... .......... .......... .......... ..........  616K
...
21200K .......... .......... .......... .......... .......... 1.61M
21250K .......... .......... .......                          2.33M=12s
2019-03-29 13:24:17 (1.79 MB/s) - '/tmp/jeedom/market/homebridge.zip' saved [21788497]
[2019-03-29 14:24:17][ALERT] : OK
[2019-03-29 14:24:17][ALERT] : Décompression du zip...
[2019-03-29 14:24:18][ALERT] : OK
[2019-03-29 14:24:18][ALERT] : Post-installation de homebridge...
[2019-03-29 14:24:20][ALERT] : OK
[2019-03-29 14:24:21][ALERT] : Launch cron dependancy plugins
[2019-03-29 14:24:21][ALERT] : [END UPDATE SUCCESS]
```

grep -R "compression du zip" *
```
core/class/update.class.php: log::add('update', 'alert', __('Décompression du zip...', __FILE__));
core/class/market.class.php: log::add('update', 'alert', __('Décompression du zip...', __FILE__));

```

**Comment by KiwiHC16** [comment]
Ca doit être update.class.php

```
$this->preInstallUpdate(); (Create plugins folder, $plugin->callInstallFunction('pre_update');)
log::add('update', 'alert', __('Téléchargement du plugin...', __FILE__));
$info = $class::downloadObject($this);
$tmp = $info['path'];
$zip->extractTo($cibDir . '/')
$zip->close();
unlink($tmp);
shell_exec('sudo rm -rf ' . __DIR__ . '/../../plugins/' . $this->getLogicalId() . '/doc');
shell_exec('sudo rm -rf ' . __DIR__ . '/../../plugins/' . $this->getLogicalId() . '/docs');
$this->postInstallUpdate($info); (=>$plugin->setIsEnable(1);)
```

On gros ca telecharge un zip contenant le plug in, decompress le zip dans le repertoire et active le plugin.

Je ne vois pas en quoi ca peut impacter les autres plugins et en particulier Abeille.

**Comment by KiwiHC16** [comment]
Je viens de faire une mise a jour homebridge et tout est ok coté Abeille.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Ca je n'ai toujours pas le début d'une piste ;-(

**Comment by Marc--** [comment]
Je viens de passer une mise à jour de plusieurs plugins (Téléinfo, Abeille,...) et le service était KO après la mise à jour. J'ai donc restart et c'est reparti. Dans le log, il m'indique que mosquitto n'est pas démarré. Je ne sais pas si c'est un début de piste, mais Abeille fonctionnait très bien avant que je lance les mises à jour depuis Jeedom.

Lancement de l'update :
> [2019-05-15 17:37:06][DEBUG] : Topic: ->Abeille/Ruche/Zigate-8000<- Value ->00-(Success)<-
> [2019-05-15 17:37:06][DEBUG] : L objet: Abeille/Ruche existe mais pas la commande: Zigate-8000
> [2019-05-15 17:37:07][DEBUG] : Topic: ->Abeille/Ruche/Zigate-8000<- Value ->00-(Success)<-
> [2019-05-15 17:37:07][DEBUG] : L objet: Abeille/Ruche existe mais pas la commande: Zigate-8000
> [2019-05-15 17:37:07][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->111<-
> [2019-05-15 17:37:08][DEBUG] : Topic: ->Abeille/3086/0006-0B-0000<- Value ->0<-
> [2019-05-15 17:37:09][DEBUG] : Topic: ->Abeille/3086/Link-Quality<- Value ->111<-
> [2019-05-15 17:37:09][DEBUG] : Topic: ->Abeille/3086/0008-0B-0000<- Value ->33<-
> [2019-05-15 17:37:22][DEBUG] : Topic: ->Abeille/Ruche/Zigate-8000<- Value ->00-(Success)<-
> [2019-05-15 17:37:22][DEBUG] : L objet: Abeille/Ruche existe mais pas la commande: Zigate-8000
> [2019-05-15 17:37:23][DEBUG] : Topic: ->Abeille/Ruche/SW-Application<- Value ->0003<-
> [2019-05-15 17:37:23][DEBUG] : Topic: ->Abeille/Ruche/SW-SDK<- Value ->030F<-
> [2019-05-15 17:37:46][DEBUG] : Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=Abeille function=pre_update callInstallFunction=1
> [2019-05-15 17:37:57][INFO] : Début d'activation du plugin
> [2019-05-15 17:37:58][INFO] : Info sur le démon : Array (     [state] => nok     [launchable] => nok     [launchable_message] => Les crons et démons sont désactivés     [nbProcessExpected] => 5     [nbProcess] => 5     [log] =>      [auto] => 0     [last_launch] => 2019-05-10 08:01:35 )
> [2019-05-15 17:37:58][DEBUG] : Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=Abeille function=update callInstallFunction=1
> [2019-05-15 17:37:58][WARNING] : -------------------------------------> dependancy_info()
> [2019-05-15 17:37:58][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:37:59][DEBUG] : Mosquitto - Status du service mosquitto : ["1"]
> [2019-05-15 17:37:59][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:37:59][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"ok","mosquitto_message":""}
> [2019-05-15 17:37:59][DEBUG] : dependancy_info: {"state":"ok","progress_file":"\/tmp\/jeedom\/Abeille\/dependance"}
> [2019-05-15 17:39:01][DEBUG] : Envoi du message: Version vers TempoCmdAbeille/Ruche/getVersion&time=1557934761
> [2019-05-15 17:39:01][DEBUG] : deamon start: IN -----------Starting --------------------
> [2019-05-15 17:39:01][DEBUG] : deamon stop: IN -------------BEN------------------
> [2019-05-15 17:39:01][DEBUG] : deamon stop: Killing deamons socat:
> [2019-05-15 17:39:01][DEBUG] : Envoi du message: getNetworkStatus vers TempoCmdAbeille/Ruche/getNetworkStatus&time=1557934765
> [2019-05-15 17:39:02][DEBUG] : deamon stop: Killing deamons: 21047 21049 21051 21053
> [2019-05-15 17:39:02][DEBUG] : deamon stop: Stopping cron
> [2019-05-15 17:39:02][DEBUG] : deamon stop: OUT -------------------------------
> [2019-05-15 17:39:02][DEBUG] : Get etat and Level des ampoules
> [2019-05-15 17:39:02][DEBUG] : GetEtat/GetLevel: 3086
> [2019-05-15 17:39:02][DEBUG] : Envoi du message: EP=0B&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934745
> [2019-05-15 17:39:02][DEBUG] : Envoi du message: EP=0B&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934745
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - serviceMosquittoStart begin
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - Le service mosquitto ne semble pas fonctionner, je vais essayer de le démarrer.
> [2019-05-15 17:39:05][DEBUG] : Mosquitto - Start du service mosquitto (with service): /etc/init.d/mosquitto start 2>&1 ; ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:39:09][DEBUG] : Mosquitto - Start du service mosquitto (with service): service mosquitto start 2>&1 ; ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:39:12][DEBUG] : Mosquitto - Start du service mosquitto (with systemctl): systemctl start mosquitto 2>&1 ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - serviceMosquittoStart end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:39:15][WARNING] : -------------------------------------> dependancy_info()
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:39:15][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:39:15][WARNING] : La verification de fonctionnement du service mosquitto renvoie: Service mosquitto pas démarré.
> [2019-05-15 17:39:15][DEBUG] : Tentative de demarrage alors qu il y a un soucis avec les dependances

Démarrage d'Abeille depuis la page des plugins.
> [2019-05-15 17:40:01][DEBUG] : Envoi du message: Version vers TempoCmdAbeille/Ruche/getVersion&time=1557934821
> [2019-05-15 17:40:01][DEBUG] : Envoi du message: getNetworkStatus vers TempoCmdAbeille/Ruche/getNetworkStatus&time=1557934825
> [2019-05-15 17:40:01][DEBUG] : Get etat and Level des ampoules
> [2019-05-15 17:40:01][DEBUG] : GetEtat/GetLevel: 3086
> [2019-05-15 17:40:01][DEBUG] : Envoi du message: EP=0B&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934804
> [2019-05-15 17:40:02][DEBUG] : Envoi du message: EP=0B&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934805
> [2019-05-15 17:40:02][DEBUG] : deamon start: IN -----------Starting --------------------
> [2019-05-15 17:40:02][DEBUG] : deamon stop: IN -------------BEN------------------
> [2019-05-15 17:40:02][DEBUG] : deamon stop: Killing deamons socat:
> [2019-05-15 17:40:02][DEBUG] : deamon stop: Killing deamons:
> [2019-05-15 17:40:02][DEBUG] : deamon stop: Stopping cron
> [2019-05-15 17:40:02][DEBUG] : deamon stop: OUT -------------------------------
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - serviceMosquittoStart begin
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - Le service mosquitto ne semble pas fonctionner, je vais essayer de le démarrer.
> [2019-05-15 17:40:05][DEBUG] : Mosquitto - Start du service mosquitto (with service): /etc/init.d/mosquitto start 2>&1 ; ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:40:08][DEBUG] : Mosquitto - Start du service mosquitto (with service): service mosquitto start 2>&1 ; ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:40:11][DEBUG] : Mosquitto - Start du service mosquitto (with systemctl): systemctl start mosquitto 2>&1 ["Starting mosquitto (via systemctl): mosquitto.service."]
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - serviceMosquittoStart end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:40:14][WARNING] : -------------------------------------> dependancy_info()
> [2019-05-15 17:40:14][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:40:15][DEBUG] : Mosquitto - Status du service mosquitto : ["0"]
> [2019-05-15 17:40:15][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:40:15][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"nok","mosquitto_message":"Service mosquitto pas d\u00e9marr\u00e9."}
> [2019-05-15 17:40:15][WARNING] : La verification de fonctionnement du service mosquitto renvoie: Service mosquitto pas démarré.
> [2019-05-15 17:40:15][DEBUG] : Tentative de demarrage alors qu il y a un soucis avec les dependances
> [2019-05-15 17:40:29][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2019-05-15 17:40:02
> [2019-05-15 17:41:02][DEBUG] : Envoi du message: Version vers TempoCmdAbeille/Ruche/getVersion&time=1557934882
> [2019-05-15 17:41:02][DEBUG] : Envoi du message: getNetworkStatus vers TempoCmdAbeille/Ruche/getNetworkStatus&time=1557934886
> [2019-05-15 17:41:02][DEBUG] : Get etat and Level des ampoules
> [2019-05-15 17:41:02][DEBUG] : GetEtat/GetLevel: 3086
> [2019-05-15 17:41:02][DEBUG] : Envoi du message: EP=0B&clusterId=0006&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934865
> [2019-05-15 17:41:02][DEBUG] : Envoi du message: EP=0B&clusterId=0008&attributeId=0000 vers TempoCmdAbeille/3086/ReadAttributeRequest&time=1557934865
> [2019-05-15 17:41:11][DEBUG] : deamon start: IN -----------Starting --------------------
> [2019-05-15 17:41:11][DEBUG] : deamon stop: IN -------------BEN------------------
> [2019-05-15 17:41:11][DEBUG] : deamon stop: Killing deamons socat:
> [2019-05-15 17:41:11][DEBUG] : deamon stop: Killing deamons:
> [2019-05-15 17:41:11][DEBUG] : deamon stop: Stopping cron
> [2019-05-15 17:41:11][DEBUG] : deamon stop: OUT -------------------------------
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStart begin
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du service mosquitto : ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"ok","mosquitto_message":""}
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du service mosquitto : ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"ok","mosquitto_message":""}
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStart end: {"mosquitto":"ok","mosquitto_message":""}
> [2019-05-15 17:41:14][WARNING] : -------------------------------------> dependancy_info()
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus begin
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du service mosquitto : ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - Status du process mosquitto: ["1"]
> [2019-05-15 17:41:14][DEBUG] : Mosquitto - serviceMosquittoStatus end: {"mosquitto":"ok","mosquitto_message":""}
> [2019-05-15 17:41:14][DEBUG] : dependancy_info: {"state":"ok","progress_file":"\/tmp\/jeedom\/Abeille\/dependance"}
> [2019-05-15 17:41:14][DEBUG] : deamon_start_cleanup: Debut des modifications si nécessaire
> [2019-05-15 17:41:14][DEBUG] : deamon_start: Port serie defini dans la configuration. ->/dev/ttyUSBzigate<-
> [2019-05-15 17:41:14][DEBUG] : Parametres utilises, Host : 127.0.0.1, Port : 1883, AbeilleParentId : 1, AbeilleSerialPort: /dev/ttyUSBzigate, qos: 0, showAllCommands: N, affichageNetwork: Y, affichageTime: Y, affichageCmdAdd: Y, ModeCreation: Automatique, adresseCourteMode: Automatique, onlyTimer: N, IpWifiZigate : 192.168.4.1
> [2019-05-15 17:41:14][DEBUG] : Subscribe to topic #
> [2019-05-15 17:41:14][INFO] : Mosquitto: Connexion à Mosquitto avec code 0 Connection Accepted.
> [2019-05-15 17:41:14][DEBUG] : Mosquitto: Subscribe to topics
> [2019-05-15 17:41:14][DEBUG] : Start deamon SerialRead: /usr/bin/nohup /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php /dev/ttyUSBzigate debug > /var/www/html/core/class/../../log/AbeilleSerialRead
> [2019-05-15 17:41:14][DEBUG] : Start deamon Parser: /usr/bin/nohup /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleParser.php /dev/ttyUSBzigate 127.0.0.1 1883 jeedom jeedom 0 debug > /var/www/html/core/class/../../log/AbeilleParser
> [2019-05-15 17:41:14][DEBUG] : Start deamon MQTT: /usr/bin/nohup /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmd.php /dev/ttyUSBzigate 127.0.0.1 1883 jeedom jeedom 0 debug > /var/www/html/core/class/../../log/AbeilleMQTTCmd
> [2019-05-15 17:41:14][DEBUG] : Start deamon Timer: /usr/bin/nohup /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmdTimer.php /dev/ttyUSBzigate 127.0.0.1 1883 jeedom jeedom 0 debug > /var/www/html/core/class/../../log/AbeilleMQTTCmdTimer
> [2019-05-15 17:41:14][DEBUG] : Entering CmdAffichage with affichageType: affichageNetwork - Visibility: Y
> [2019-05-15 17:41:14][INFO] : Mosquitto: AbeilleParser Connexion à Mosquitto avec code 0 Connection Accepted.
> [2019-05-15 17:41:14][DEBUG] : AbeilleParser - Mosquitto: Déconnexion de Mosquitto avec code 0
> [2019-05-15 17:41:14][DEBUG] : AbeilleParser -  Mosquitto: Subscribe to topics
> [2019-05-15 17:41:15][DEBUG] : Topic: ->Abeille/0E3d/Link-Quality<- Value ->135<-
> [2019-05-15 17:41:16][DEBUG] : Leaving CmdAffichage
> [2019-05-15 17:41:16][DEBUG] : Entering CmdAffichage with affichageType: affichageTime - Visibility: Y
> [2019-05-15 17:41:16][DEBUG] : Leaving CmdAffichage
> [2019-05-15 17:41:16][DEBUG] : Entering CmdAffichage with affichageType: affichageCmdAdd - Visibility: Y
> [2019-05-15 17:41:17][DEBUG] : Topic: ->Abeille/0E3d/0000-ff01<- Value ->$this->decoded as Volt-Temperature-Humidity<-
> [2019-05-15 17:41:17][DEBUG] : L objet: Abeille/0E3d existe mais pas la commande: 0000-ff01
> [2019-05-15 17:41:17][DEBUG] : Topic: ->Abeille/0E3d/Batterie-Volt<- Value ->2915<-
> [2019-05-15 17:41:17][DEBUG] : Topic: ->Abeille/0E3d/Batterie-Pourcent<- Value ->34<-
> [2019-05-15 17:41:17][DEBUG] : Topic: ->Abeille/0E3d/0402-01-0000<- Value ->2105<-
> [2019-05-15 17:41:17][DEBUG] : Leaving CmdAffichage
> [2019-05-15 17:41:18][DEBUG] : Topic: ->Abeille/0E3d/0405-01-0000<- Value ->4484<-
> [2019-05-15 17:41:19][DEBUG] : deamon_start: *****Envoi de la creation de ruche par défaut ********
> [2019-05-15 17:41:19][DEBUG] : Envoi du message:  vers CmdRuche/Ruche/CreateRuche
> [2019-05-15 17:41:19][DEBUG] : Topic: ->CmdRuche/Ruche/CreateRuche<- Value -><-
> [2019-05-15 17:41:19][DEBUG] : message: createRuche: objet: Abeille/Ruche existe deja
> [2019-05-15 17:41:19][DEBUG] : deamon start: OUT --------------- all done ----------------


Je ne sais pas si ça peut t'aider, sinon il faudrait savoir ce que tu veux voir.

**Comment by KiwiHC16** [comment]
J'ai mis en pause ce sujet pour l instant car dans la version a venir, il n'y aura pas mosquito. On verra si le probleme existe toujours.

**Comment by KiwiHC16** [comment]
Maintenant que le master est sans mosquitto on va pouvoir voir si le probleme existe toujours.

**Comment by Marc--** [comment]
SUite à la mise à jour de Calendar il y a peu, je n'ai pas remarqué le problème du plantage Abeille.

Le temps que je me rende sur la page de conf d'Abeille, j'ai bien vu le démon arrêté, mais il a redémarré tout seul. Donc ça me semble réglé. 

Tu peux fermer l'issue, au besoin je commenterai s'il y a changement. Un grand merci à toi !
