### ISSUE TITLE
Pilotage d'une ampoule depuis télécommande Hue incluse dans le réseau. Comment faire ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#628]

**Comment by Soyann** [comment]
Bonjour KiwiHC16
Merci pour l'ouverture de ce ticket.
Je ne comprenais pas pourquoi je n'arrivais pas à piloter une ampoule LTW010 depuis ma télécommande 4 boutons malgré l'appuie plus de 10s sur le bouton ON (alors que j'avais fait cette manipulation sans problème depuis un autre interrupteur pour piloter 3 ampoules Ikea).
J'ai refait la manipulation ce soir, après avoir changé les piles (dans le doute, même si je n'avais pas d'alerte sur la batterie), et au bout du 3ème essai, c'est passé tout seul... (j'ai l'impression que l'ampoule était également capricieuse, j'ai dut la dévisser / revisser de son goulot pour que ça passe.
Maintenant, je peux piloter l'ensemble, aussi bien depuis cette télécommande, que depuis Jeedom, et cette télécommande change l'état d'un virtuel (le groupement de mes ampoules) pour la gestion de certains scénarios :)

Question subsidiaire: après le changement de pile, le télécommande ne marchait plus dans Jeedom, j'ai donc fait une inclusion pour qu'il mette à jour l'abeille, mais en même temps, il m'a créé (sans raison) un timer... Penses-tu que c'était lié au fait que j'appuyais longuement sur les touches On et Off pour qu'elle se déclare (sans faire le 5x setup pour ne pas perdre la commande directe depuis les ampoules)? Penses tu que je peux le supprimer sans perdre une communication (je peux le laisser s'il y a un doute, tout ce que je veux, c'est avant tout que ça marche)? Dès que tu m'auras répondu, tu pourras clore ce ticket

En te remerciant pour tout

Très cordialement

**Comment by KiwiHC16** [comment]
Les timers ne sont pas liés au zigbee ou zigate.
Peux tu partager une capture d'écran de ce que tu appelles Timer pour être sûr qu'on parle de la même chose ?
Peut être as tu fait un clic sur Timer par erreur... Un bug qq part ...

**Comment by Soyann** [comment]
Hello
Voilà:
![image](https://user-images.githubusercontent.com/46709337/54489893-73c1c200-48b1-11e9-9c21-5c4231f8e314.png)
Je pense également à un bug mineur lors de la création, car dans Santé, je n'ai plus de communication avec depuis sa création (vu que non utilisé, alors que j'ai utilisé l'interrupteur hier soir, et que ce dernier a bien communiqué).

Merci une fois de plus

**Comment by KiwiHC16** [comment]
C'est un pur timer qui n a rien a voir avec le zigate/zigbee.
Tu peux l effacer si tu ne l utilises pas.

**Comment by KiwiHC16** [comment]
Ok je pense que je peux clore ce sujet.
