### ISSUE TITLE
socat in install script

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#640]
@Dams, dans le premier log il y a :
socat: not found

socat est le soft qui fait la connection avec le module wifi. Il n'est semble t il pas sur ton systeme.

Et dans ton log d'installation, je ne vois pas son installation. Peux etre un oubli de ma part.

Je vais l'ajouter dans le script d installation.

Pour toi fais en ssh:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install socat

**Comment by KiwiHC16** [comment]
Done in master

**Comment by dams** [comment]
Ravi d'être au courant de tout ça ! Mais il doit y avoir erreur sur la personne :P
