### ISSUE TITLE
Restaurer état des prises ou ampoules après une coupure de courant

### ISSUE THREAD

**Issue by Ricardo544** [KiwiHC16/Abeille#642]
Hello KiwiHC16,

Sais-tu si dans les paramètres des prises ou ampoules Ikea ou autres si il est possible de paramétrer l'état dans lequel se trouve l'appareil avant coupure de courant et de restaurer celui-ci automatiquement lors du retour du courant. Cela existe sur les modules dimmer Fibaro et ampoules Xiaomi Wifi. J’imagine que si cela était possible tu l'aurais déjà implementé !!!
Je te demande cela car cette semaine nous avons eu une coupure Edf et en pleine nuit toutes les lampes se sont allumées lors du retour du courant.... imagine le bond dans le lit à deux heures du matin :O))

Amicalement

**Comment by KiwiHC16** [comment]
Salut Ricardo,

J'ai vu que Hue faisait de la "pub" pour cette fonctionnalité. Donc je suppose que les ampoules Hue avec le dernier soft le supportent. Jamais vu de discussions similaires pour les autres fabricants.

Je mettais dit je vais faire cela depuis Jeedom/Abeille, je détecte une coupure, et quand le jus reviens je repositionne les ampoules dans leur état. 

Mais sans parler du fait que c est pas forcement facile:
- comment je detecte la coupure ?
- comment je detecte que le jus est revenu ?
- quand le jus revient l ampoule fait ce qu'elle veut avant meme que jeedom soit de retour avant d'envoyer des commandes
- ...

Et puis je me suis dit que ce n'était pas une bonne idée. Quand je développe je garde toujours en tête que le systeme peut planter. Et dans ce cas retour aux bonnes vieilles méthodes surtout pour ceux qui ne connaissent pas la domotique. Dans tous les cas, il faut que les ampoules quand on les allume s'allument avec les interrupteurs et s'eteignent quand on les éteint.

Donc je n'ai rein fait.

**Comment by Ricardo544** [comment]
Re,

Détecter une coupure et quand le jus revient je sais faire, tous mes serveurs et mes jeedoms sont ondulés, je reçois un Sms de jeedom lorsque le jus est coupé et lorsqu'il revient. Je comptais faire un scénario au retour du courant pour gérer les lampes mais je ne serai jamais assez rapide avec ce scénario, au pire je pourrai les éteindre au cas par cas après le retour du courant. Mais dans tous les cas on prendra le flash en pleine nuit quand même.
Je te tiendrai au courant "sans jeu de mot" sur la mise en place de mon scénario. Mais c'est pareil toujours le manque de temps pour continuer à peaufiner la domotique de la maison.

Merci en tout cas pour ta réponse.

Je te souhaite un bon week-end sous le soleil.

**Comment by KiwiHC16** [comment]
Merci toi aussi.
