### ISSUE TITLE
Tous mes capteurs aqara de température V2 en "Time Out Last Communication"

### ISSUE THREAD

**Issue by guillaumecosta** [KiwiHC16/Abeille#649]
Bonjour,

Après installation du plugin et inclusion de mes 9 capteurs de température Xiaomi aqara V2, tout a bien fonctionné pendant quelques heures puis ils sont tous passés en "Time Out Last Communication".
Certains capteurs sont assez éloignés, mais quelques uns ne sont pas plus loin que 2 mètres du dongle Zigate.
D'où peut venir le problème ?
Merci beaucoup.
Guillaume

![Capture](https://user-images.githubusercontent.com/48923956/54941124-5bdee380-4f2c-11e9-88cf-bb59a1d8f963.jpg)

**Comment by KiwiHC16** [comment]
Difficile à dire. Peux tu partager le log AbeilleParser ? et la table "Network List"
![Capture d’écran 2019-03-27 à 18 06 04](https://user-images.githubusercontent.com/8549674/55096878-008f2b80-50bb-11e9-930b-d9c922eb2f15.png)

**Comment by guillaumecosta** [comment]
Malheureusement le log est limité à 500 lignes par défaut, donc je n'ai plus ce qui correspond à l'incident.
J'ai été obligé de supprimer tous les capteurs et les inclure à nouveau.
Si le problème se produit à nouveau, je récupérerai le log et la copie d'écran demandée.

**Comment by jaycenet** [comment]
Meme problème j'ai tout perdu

**Comment by KiwiHC16** [comment]
Aucune raison de "supprimer tous les capteurs" !!!
Il faut au maximum les re-inclure.

@jaycenet peux tu partager le meme ecran ?

Avez vous eu des coupure de courant sur la zigate ?
Est ce que la zigate était déconnectée pendant un certain temps ?
Reboot de votre machine ?
Zigate USB ? Wifi ?

**Comment by guillaumecosta** [comment]
Tous mes capteurs apparaissaient en rouge. Avant de les supprimer, j'ai essayé de les "reconnecter". Je n'y suis pas arrivé ou je n'ai pas la bonne méthode. Je n'ai pas essayé de les réinclure sans les supprimer.
C'est une Zigate USB sur un Raspberry Pi 3 b+.
Il n'y a pas eu de coupure ou de reboot.
Je dois éteindre ma box ce week-end. J'espère qu'on peut éteindre sans avoir à tout réinclure :-)
Pour l'instant, tous mes capteurs fonctionnent sans souci, même les plus éloignés.

**Comment by KiwiHC16** [comment]
Il faut comprendre pourquoi cela c'est produit. 
Perso j'ai mon systeme de production qui fonctionne depuis des semaines sans problème ce qui veut dire qu'en bonne situation ca fonctionne.
Il faut décorréler le fonctionnement ZigBee et Abeille.

Abeille/Jeedom est capable de reconnaitre un equipment zigbee qui a disparu à son retour. Ils n'est donc jamais nécessaire de supprimer un equipment dans Abeille dans ce genre de situation. La suppression ne touche pas le réseau Zigbee, ca ne fait qu'enlever les informations dans Abeille.

Premiere chose, c'est de vérifier le bon fonctionnement d'Abeille. 
Si Abeille ne fonctionne pas trouver pourquoi avec les logs (Abeille, AbeilleParser et AbeilleMQTT) et au pire faire un redemarrage du demon.

Si Abeille fonctionne alors il faut regarder coté ZIgBee. Provoquer du traffic depuis l'équipement et au pire le re-inclure.

Pour les utilisateurs avancés il y a la doc:
https://kiwihc16.github.io/Abeille/fr_FR/Debug.html

Sinon me contacter quand ca ne fonctionne pas pour que je regardes.
Je peux me connecter avec un partage d'écran avec le soft AnyDesk et si vous m'envoyez les infos par MP dans le forum Jeedom.

**Comment by guillaumecosta** [comment]
Merci pour toutes ces informations.
Mon système est sous surveillance.
Je ne manquerai pas de vous faire savoir si je rencontre un nouveau problème.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Ok je clos et si tu as du nouveau ti rouvres.

**Comment by guillaumecosta** [comment]
Bonjour,

J'ai un peu plus d'expérience dans l'utilisation du plugin avec mes capteurs de températures et je rencontre toujours quelques problèmes.
Après mon premier problème qui a été l'objet de ce ticket, j'ai réussi à les faire fonctionner à nouveau en supprimant les équipements (capteurs Xiaomi) puis en les incluant à nouveau. De là, tout à fonctionner à merveilles plusieurs jours.
Ensuite, j'ai dû éteindre mon Raspberry pour changer de prise d'alimentation. En rallumant les Raspberry, mes équipements sont tous passés en rouge au bout de quelques minutes. J'ai alors refait une inclusion sans les avoir supprimés, comme conseillé, et tout s'est bien passé.
Quelques jours plus tard, j'ai du redémarrer Jeedom et là, à nouveau, mes équipement Xiaomi sont tous passés en rouge, mais aussi certains sont devenus inactifs (c'est à dire que la case "Activer" n'était plus cochée). J'ai refait l'inclusion de tous les équipements, après avoir réactiver ceux qui étaient désactivés. Malgré cela, au bout de quelques minutes, ils passaient soit en rouge, soit certains se désactivaient. J'ai fait la manip plusieurs fois. J'ai alors dû les supprimer pour les inclure à nouveau pour que cela soit stable et que tout fonctionne bien pour plusieurs jours...
Dimanche dernier, j'ai appliqué une mise à jour sur Jeedom qui m'a provoqué à nouveau le même phénomène. Rouge + certains désactivés. Depuis, j'ai tout essayé : inclusions, suppression+ réinclusion. Ils reviennent inévitablement en rouge ou désactivés.
Je ne sais pas trop quoi regarder dans les log.
Que pourrais-je faire comme manip pour débloquer la situation ?
Merci d'avance pour ton aide...
Guillaume

**Comment by KiwiHC16** [comment]
Bonjour Guillaume,
Je regardes quasi jamais les cas fermés, alors ouvre plutot un cas sinon je risque de ne jamais voir ton commentaire.
Sur installation / mise a jour d un autre plugin ca peut faire planter Abeille, issue ouverte, pas encore trouvé la raison.
Sur coupure de jus, les device peuvent passer en timeout, normalement apres avoir abeille de nouveau fonctionnel, il n'y a rien a faire apres 2 heures tout doit rentrer dans l ordre.
Si les objets passent en inactifs, c est qu'ils ont annoncé au réseau qu'ils quittaient le réseau. C est un probleme connu des capteurs xiaomi. Dans ce cas il faut faire une inclusion uniquement et tout doit rentrer dans l'ordre.
