### ISSUE TITLE
Upload Fond d ecran pour voisines ne semble pas fonctionner

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#655]
Le fichier est bien la avec firefox mais pas dans safari. Probleme de cache probablement.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by dams74** [comment]
Oui j'ai eu aussi le soucis.
Il me semble qu'après un redémarrage de l'installation, il a fini par apparaître

**Comment by KiwiHC16** [comment]
Je pense que c'est un problème de cache du browser. Il faut que j'ajoute une date ou un numero sur le fichier pour que le browser le récupère.

**Comment by KiwiHC16** [comment]
Done today
