### ISSUE TITLE
Erreur demarrage Demon Abeille

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#657]
Bonjour,

Le rencontre un pb de démarrage du demon abeille, tjrs NOK même en relançant..

Le demon est NOK avec en debug Abeille:
Log debug =
 Envoi du message: Version vers TempoCmdAbeille/Ruche/getVersion&time=1554142703
[2019-04-01 20:18:03][ERROR] : Erreur sur la fonction cron du plugin : The client is not currently connected.
[2019-04-01 20:18:03][DEBUG] : Parametres utilises, Host : 127.0.0.1,             Port : 1883,             AbeilleParentId : 21,             AbeilleConId: jeedom,             AbeilleUser: jeedom,             Abeillepass: jeedom,             AbeilleSerialPort: /dev/ttyUSB0,             qos: 0,  

Quand je fais un apt-get update, a la fin j'obtiens:
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://repo.mosquitto.org/de                 bian stretch InRelease' doesn't support architecture 'arm64'

Pour info (sans sans savoir si cela à un lien) j'ai installé le certificat https (certbot) en suivant le tuto "https://www.domo-blog.fr/securiser-jeedom-https-certificat-ssl-dote-nouveau-challenge-http-01/3/". Aurais cassé qq chose lors de cette installation ?

Merci pour ton aide (toute ma gestion thermostat radiateur est non utilisable..heureusement il ne fait pas trop froid en ce moment !)
Ivan

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Si tu veux que je regardes directement sur ton système en partage d'ecran envoies les infos AnyDesk en MP dans le forum Jeedom.

Sur quel type de machine tourne ton jeedom ?
Est ce que mosquitto fonctionne ? 
Je suppose que la zigate est en USB ?
As tu refait une installation des dependances ?

**Comment by KiwiHC16** [comment]
Toujour besoin de support ?

**Comment by ivan9187** [comment]
Bonjour,

Merci pour ta proposition, je pense avoir effacé trop de chose dans un
fichier de config Apache lors de la réinstallation du SSL...
Je suis repartis d'une image de mon système et tout est rentré dans l'ordre
maintenant.
Bon point: tout mes équipements xiaomi sont restés fonctionnels après la
recharge du backup sur le nouveau système..
Je n'ai donc plus besoin de support.

Merci,
Ivan

**Comment by KiwiHC16** [comment]
Ok je clos.
