### ISSUE TITLE
Generer la liste des objets automatiquement en fonction de JSON

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#66]
Dans le fichier plugins/Abeille/desktop/php/Abeille.php

                  <option value="XiaomiBouton">{{Xiaomi Bouton}}</option>
                  <option value="XiaomiBouton1">{{Xiaomi Bouton 1}}</option>
                  
                  <option value="XiaomiPorte">{{Xiaomi Porte}}</option>
                  <option value="XiaomiInfraRouge">{{Xiaomi Infra Rouge}}</option>
                  <option value="XiaomiPrise">{{Xiaomi Prise}}</option>
                  <option value="XiaomiTemperatureCarre">{{Xiaomi Temperature Carré}}</option>
                  <option value="XiaomiTemperatureRond">{{Xiaomi Temperature Rond}}</option>
                  
                  <option value="IkeaTradfriBulbE27Opal1000lm">{{IKEA TRADFRI bulb E27 opal 1000lm}}</option>

Remplacer cette liste par une liste automatique en fonction de JSON sinon a chaque ajout d'équipement il faut aussi mettre a jour cette liste.

**Comment by edgd1er** [comment]
oups, j'ai crée la #110 avant d'avoir retrouvé celle ci
pr faire dbc95a58d177a6de744c8ede29a5ab6b3819c34a

**Comment by KiwiHC16** [comment]
Closed as part of #110
