### ISSUE TITLE
Remise à zéro jeedom

### ISSUE THREAD

**Issue by Ricardo544** [KiwiHC16/Abeille#665]
Hello,

Petit retour, suite à soucis avec la lib Php Mosquitto sur mon système, je suis reparti de zéro, installation de Stretch, suivi d'une réinstallation de Jeedom et d'une restauration et tout fonctionne correctement de mon coté. Perdu aucun devices que ce soit pour de l'Ikea ou du Xiaomi ou de l'Innr.

Voilà c'était juste pour te tenir au courant.

Bonne journée et bon week-end

**Comment by KiwiHC16** [comment]
Super !

Suite aux investigations sur ton systeme, je comprends mieux cette partie.
Du coup j'ai fait des modifications/scripts qui me permet de mieux gérer ces aspects.

Merci pour le retour.

Je clos le sujet.
