### ISSUE TITLE
Niveau de log: debug indiqué comme > error

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#666]
J'ai modifié dans Tools.php la fonction daemongLogFilter pour avoir le niveau de log défini dans le plugin et celui envoyé par la fonction.
ici la fonction demande l'affichage d'un message de debug, le plugin est réglé sur Error.

La fonction getNumberFromLevel donne les valeurs a Error(1) et a Debug (4) and loglevel est fourni correctement (typo et casse)

je vais faire un correctif.

est pour cela que je vois beaucoup de "if ($debug) then", alors que daemonFilter devrait faire ce travail de tri/affichage en fonction du niveau de log demandé ?

l'idée de $this->debug['cli'] est t il d'avoir un reglage plus fin du débug ou de palier au bug actuel du Tools::getNumberLogLevel ?

-------------------------------------------
Autre point peux tu me dire pourquoi AbeilleMQTTCmd dit ne pas devoir traiter une remontée d'un device ? ( j'avoue ne plus trop avoir en tete les perimetres de chaques démons)
AbeilleMQTTCmd 2019-04-06 10:43:47[WARNING/ERROR]procmsg fct - Msg Received: Topic: {Abeille/82e7/0000-01-0005} => lumi.weather mais ce n est pas pour moi, no action.

-------------------------------------------

AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]----------
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]procmsg fct - topic: TempoCmdAbeille/Ruche/getVersion&time=1554539243 len: 1
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]Topic: ->TempoCmdAbeille/Ruche/getVersion&time=1554539243<- Value ->Version<-
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]procmsg fct - topic: Ajoutons le message a queue.
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]addTempoCmdAbeille - mqttMessageQueue: null
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]----------
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]procmsg fct - topic: TempoCmdAbeille/Ruche/getNetworkStatus&time=1554539247 len: 1
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]Topic: ->TempoCmdAbeille/Ruche/getNetworkStatus&time=1554539247<- Value ->getNetworkStatus<-
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]procmsg fct - topic: Ajoutons le message a queue.
AbeilleMQTTCmd 2019-04-06 10:27:03[DEBUG/ERROR]addTempoCmdAbeille - mqttMessageQueue: null

**Comment by KiwiHC16** [comment]
Ne fait rien de ton côté, car je suis entrain de finaliser ces modifications.
Je vais enlever le parametres de appel de demons pour les récupérer directement de la conf Abeille.
En cours, enormement de changement et clarifications. Master pas stable.
Par contre je suis preneur des remontées de problème.
Je te dirais quand le master commence à être stabilisé.
