### ISSUE TITLE
Gestion de démarrage de Mosquito

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#671]

**Comment by edgd1er** [comment]
Quel est le soucis ?

           exec("ps -e -o '%p;%a' --cols=10000 | grep -v awk | awk '/mosquitto /' | cut -d ';'  -f 1 | wc -l", $output2 );
            $nbProcess = $output1[0]+$output2[0];
            
            if ( ($nbProcess != $nbProcessExpected) ) {....

permet de detecter les ano.

install.sh normalement demarrent les services, As tu remarqué des problèmes ? as tu des logs ?

je viens de remarquer que le test 
``if [[ $(grep -c docker /proc/1/cgroup) -gt 0 ]]; then``
peut ne pas marcher car par defaut raspbian ne gere pas les cgroup. As tu remarqué ce problème sur rapsberry ? il est sans doute possible de fiabiliser le démarrage du service mosquitto.
Est ce cela que tu avais en tete ?

**Comment by KiwiHC16** [comment]
En touchant cette partie, je suis tombé sur plein de situation de plantage sans explication aucune pour l utilisateur. Et pour moi j'ai du suivre le code ligne à ligne pour comprendre pourquoi ca ne demarrait pas.

D ou ma tentative d'aller pas à pas dans le code pour identifier le pas qui plante.
Exemple service dit ok mais le process ne tourne pas.

Je n'ai pas touché (sauf erreur) la partie docker.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Encore un soucis aujourd'hui. Je vais alerter l utilisateur mais je retire le demarrage mosquitto  dans le demon abeille, ca ne fonctionne pas.
