### ISSUE TITLE
TRADFRI Remote Ronde 5 boutons - Pas de remontée d'infos des clics

### ISSUE THREAD

**Issue by waazdakka** [KiwiHC16/Abeille#673]
Hello,
Aucun problème pour faire remonter la télécommande dans mon Jeedom, en revanche, aucune commande ne remonte (J'ai fait un scénario pour créer un message à chaque clic, rien ne remonte...)
J'ai loupé quelque chose ?
Merci !

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Il faut configurer les groupes. As tu fait cette étape ?

**Comment by G0li4th** [comment]
Comment configure-t-on des groupes ?

**Comment by KiwiHC16** [comment]
Il faut definir le groupe utilisé par la télécommande (Bouton set groupe remote).
Il faut ajouter la Zigate au groupe de la telecommande.
Doc: https://kiwihc16.github.io/Abeille/fr_FR/Groups.html

**Comment by waazdakka** [comment]
Ah bien la cagnotte @KiwiHC16 :)
Je regarde tout ca ce week-end ! Merci. :)

**Comment by KiwiHC16** [comment]
Pas d info depuis 1 mois. Je clos. Si besoins r-ouvrez.
