### ISSUE TITLE
Module Double Switch Aqara

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#676]
https://fr.aliexpress.com/item/Original-Xiaomi-Mijia-Aqara-Two-way-control-module-Wireless-Relay-Controller-2-channels-Work-For-Mijia/32982164582.html?spm=a2g0w.10010108.1000016.1.38e04960kPSNKV&isOrigTitle=true

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Est ce qu'il inclus une mesure de courant/Puissance ?

**Comment by elydan** [comment]
Salut, 
En as-tu commandé un ? sinon je veux bien le faire et tester, si ça gère le retour de puissance, ça peut me permettre de gérer mes chauffages sans Z-Wave (ce qui coûte un bras ^^)
Bref dis moi

**Comment by KiwiHC16** [comment]
Je viens de le recevoir. Il est sur mon bureau.
Je vais essayer de faire une revue aujourd'hui.

**Comment by KiwiHC16** [comment]
EP: 01, 02
lumi.relay.c2acn01
Location answer ""
![Capture d’écran 2019-04-25 à 10 45 05](https://user-images.githubusercontent.com/8549674/56722349-328dbf00-6747-11e9-8b60-73c904002dc2.png)
Je ne sais pas pourquoi Abeille ne parse pas correctement la réponse. Wireshark est ok.

![Capture d’écran 2019-04-25 à 10 45 31](https://user-images.githubusercontent.com/8549674/56722378-420d0800-6747-11e9-9d56-e0513e42af39.png)

```
AbeilleParser 2019-04-25 10:45:20[debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 24; Status : 00; Short Address : b468; Length : 10; endpoint : 02; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0101 (Dimmable Light); bitField : 02; InClusterCount : 04
AbeilleParser 2019-04-25 10:45:20[debug]In cluster: 0006 - General: On/Off
AbeilleParser 2019-04-25 10:45:20[debug]In cluster: 0010 - 
AbeilleParser 2019-04-25 10:45:20[debug]In cluster: 0004 - General: Groups
AbeilleParser 2019-04-25 10:45:20[debug]In cluster: 0005 - General: Scenes
AbeilleParser 2019-04-25 10:45:20[debug]OutClusterCount : 00
```

**Comment by KiwiHC16** [comment]
Premiere version dans le master.
Ca remonte bien la puissance et la conso mais pour le module complet, pas par switch.

**Comment by KiwiHC16** [comment]
Fonctionne nickel pour moi.
