### ISSUE TITLE
Perte de mes capteurs aqara de température V2

### ISSUE THREAD

**Issue by guillaumecosta** [KiwiHC16/Abeille#684]
Bonjour,

Mon précédent post (#649) étant fermé, j'en ouvre un nouveau concernant mes nouveaux problèmes.

J'ai maintenant un peu plus d'expérience dans l'utilisation du plugin avec mes capteurs de températures Xiaomi aqara V2 et je rencontre toujours quelques problèmes.
Après mon premier problème qui a été l'objet de ce ticket, j'ai réussi à les faire fonctionner à nouveau en supprimant les équipements (capteurs Xiaomi) puis en les incluant à nouveau. De là, tout à fonctionner à merveilles plusieurs jours.
Ensuite, j'ai dû éteindre mon Raspberry pour changer de prise d'alimentation. En rallumant les Raspberry, mes équipements sont tous passés en rouge au bout de quelques minutes. J'ai alors refait une inclusion sans les avoir supprimés, comme conseillé, et tout s'est bien passé.
Quelques jours plus tard, j'ai du redémarrer Jeedom et là, à nouveau, mes équipement Xiaomi sont tous passés en rouge, mais aussi certains sont devenus inactifs (c'est à dire que la case "Activer" n'était plus cochée). J'ai refait l'inclusion de tous les équipements, après avoir réactiver ceux qui étaient désactivés. Malgré cela, au bout de quelques minutes, ils passaient soit en rouge, soit certains se désactivaient. J'ai fait la manip plusieurs fois. J'ai alors dû les supprimer pour les inclure à nouveau pour que cela soit stable et que tout fonctionne bien pour plusieurs jours...
Dimanche dernier, j'ai appliqué une mise à jour sur Jeedom qui m'a provoqué à nouveau le même phénomène. Rouge + certains désactivés. Depuis, j'ai tout essayé : inclusions, suppression+ réinclusion. Ils reviennent inévitablement en rouge ou désactivés.
Je ne sais pas trop quoi regarder dans les log.
Que pourrais-je faire comme manip pour débloquer la situation ?
Merci d'avance pour ton aide...
Guillaume

**Comment by KiwiHC16** [comment]
Salut Guillaume,
Si tu installes AnyDesk sur un PC et me fourni le code d'acces on peut regarder ensemble en partageant ton écran.
Sinon quelques commentaires:
- il n'est jamais nécessaire de supprimer des équipements dans Abeille (sauf tres rares exceptions).
- un équipement tqui devient désactivé est du au fait que l'équipement à envoyé une deconnection à la zigate et n'est normalement plus dans le réseau. S'il parvient a revenir Abeille doit être mis à jour. Attention ca suppose qu'abeille est en ligne quand cela se passe, sinon des synchro entre le reseau et abeille. Un equipement désactivé egale le reinclure.
- sur redemarrage de jeedom ou d'abeille les equipements peuvent etre en timeout car l historique peut avoir été perturbé, il faut attendre une heure pour avoir le "vrai" status.

Désolé pour cette réponse si tardive.

Dans quel état est ton systeme maintenant ?

**Comment by guillaumecosta** [comment]
Bonjour,
Je pense avoir cerné d'où venait mon problème.
A priori, cela est dû à un problème radio.
J'ai éloigné le contrôleur Zigate d'un bon mètre et cela semble résoudre le problème.
Mon système est stable depuis 2 jours.
Dans quelques jours, je vais refaire le test d'un redémarrage de Jeedom pour voir quel est le comportement des modules.
Merci pour ton aide.
Guillaume

**Comment by guillaumecosta** [comment]
Salut,
Je confirme la stabilité après avoir éloigné mon contrôleur Zigate.
En revanche, aujourd'hui, j'ai effectué une mise à jour du core Jeedom et comme précédemment tous mes capteurs sont passés en "timeout" et sont devenus tout rouge sur le dashboard. C'est le même comportement que lors d'un redémarrage de Jeedom.
J'en suis à plusieurs heures d'attente sans changement.
J'ai essayé un appui court ou long sur les capteurs, sans résultat.
Sais-tu quelle est la marche à suivre pour récupérer mes capteurs ?
Je peux installer AnyDesk si cela peut aider...
Merci

**Comment by KiwiHC16** [comment]
Désolé pour mon retour tardif...

As tu toujours besoin d'aide ?

**Comment by guillaumecosta** [comment]
Oui et non...
Je pensais mon système stable, mais ce n'est toujours pas le cas et je ne comprends pas vraiment pourquoi.
Après une semaine de stabilité, je fais un redémarrage de Jeedom et tous mes capteurs passent en timeout.
De là, impossible de les récupérer : je les inclus à nouveau mais ils repassent en timeout.
J'ai refait l'opération plusieurs fois sur différents capteurs. Parfois un capteur "tenait" 2 ou 3h et puis repassait en timeout.
J'ai testé avec un capteur à 30 cm du dongle Zigate : idem.
Je ne comprends pas pourquoi cela a été stable pendant une semaine, puis plus rien !
Il me reste 2 tests à faire : 
- changer l'environnement du dongle dès fois que quelque chose provoque un problème radio.
- brancher le dongle sur un hub USB alimenté : en effet, je me demande s'il a assez de jus actuellement. J'ai un Raspberry Pi 3 B+ qui tourne sur un SSD alimenté par le Raspberry + un dongle Z-Wave + un dongle Zigate -> ça fait peut-être beaucoup...

Trois questions : 
- As-tu une autre idée d'où peut venir le problème ?
- Est-ce normal d'avoir les capteurs en timeout après un redémarrage Jeedom ?
- Quelle est la procédure pour tous les récupérer sans avoir à tous les réinclure ?

Merci
Guillaume

**Comment by KiwiHC16** [comment]
> Est-ce normal d'avoir les capteurs en timeout après un redémarrage Jeedom ?

Oui et non. Le timeout est juste une indication du fait que des messages remontent des équipements. Lors de la reception d'un message, abeille recupere l heure T0 pour cet equipement. Si apres T0+TimeOut on a tojours recu de messages alors timeout. Si un message arrive pendant que Jeedom et donc abeille est HS alors on manque des messages et les heure T0 ne sont pas mises a jour. Un fois tout revenu les messages remontent, les T0 sont mis a l'heure, donc apres 2x TimeOut tout doit etre en ordre. Si TimeOut 1h, au bout de 2h tout doit etre ok.

> As-tu une autre idée d'où peut venir le problème ?

Il faudrait que tu mettes les logs a 5000 lignes et apres plusieures heures que tu partages AbeilleParser que je vois ce qui remonte.

> Quelle est la procédure pour tous les récupérer sans avoir à tous les réinclure

Normalement tu n'as rien a faire dans Abeille, les info sont gardées. Donc meme si tu refais une inclusion zigate, tu ne dois rien n'avaoir a faire.

Si tu veux je peux jeter un oeil sur ton système si tu partages ton ecran avec l appli AnyDesk (any desk.com).  Il faut juste que tu me fournisse le code d acces par MP dans le forum jeedom par exemple.

**Comment by guillaumecosta** [comment]
Bon, j'ai branché mon dongle Zigate sur un hub USB alimenté et cela ne change rien.
Quand je réinclus mes capteurs, ils repassent tous en timeout au bout d'un certain temps.
J'ai fait un nouveau test : j'ai supprimé un capteur de Jeedom et je l'ai inclus à nouveau. Et là, il fonctionne parfaitement.
Je ne comprends pas...
Je te joins les log Abeille et AbeilleParser (pour info la dernière récinclusion qui laisse le capteur en timeout est datée du 14/05 à 23h et la suppression et inclusion du capteur qui fonctionne correctement est datée du 15/05 à 6h53)
Je te contacte également pour AnyDesk en MP sur le forum Jeedom
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3181917/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3181919/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
D apres le log Abeille, la nuit dernière aucune info n'est remontée...
Et AbeilleParser est un desastre. J avais jamais vu a ce point !!! Ceci explique pourquoi Abeille ne voit rien.
Sur quelle version es tu ?

**Comment by guillaumecosta** [comment]
Pas rassurant ce que tu dis :-(
Version Jeedom : 3.3.24
Version Zigate : 3.0f
Version Abeille : 2019-03-16 01:01:09

**Comment by KiwiHC16** [comment]
Investigatio hier:
beaucoup de warning php avec des probleme d index qui n'existet pas dans AbeilleParser.
Systeme avec que des capteur temp V2 xiaomi.
Redemarrage des demons, tout est ok. Un appui ou inclusion des capteurs et tout revient. Tout repasse au vert.

**Comment by KiwiHC16** [comment]
Ce matin re-down:
Analyse de AbeilleParser:
Pendant la phase de remise en route des capteurs:
```
AbeilleParser 2019-05-15 21:39:59[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 00; Src Addr : 3e77; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 000C; Data byte list : ->lumi.weather<-
PHP Notice:  Undefined index: action in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2211
PHP Notice:  Undefined index: action in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2217
```

```
PHP Notice:  Undefined index: 5f01 in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 1041
```

idem pour 1051, 1055 et ca dure jusqu'à a 22h.

```
AbeilleParser 2019-05-15 22:01:09[DEBUG];type; 8045; (Active Endpoints Response); SQN : b7; Status : 00; Short Address : cdc4; Endpoint Count : 01; Endpoint List :; 01
PHP Notice:  Undefined index: action in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2463
PHP Notice:  Undefined index: timeAnnonceReceived in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2540
PHP Notice:  Undefined index: IEEE in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2542
PHP Notice:  Undefined index: capa in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2544
```

et a la fin du log 
```
AbeilleParser 2019-05-15 23:00:51[DEBUG];Type; 8048; (Leave Indication)(Processed->Draft-MQTT); extended addr : 00158d0002c9cda9; rejoin status : 01
AbeilleParser 2019-05-15 23:01:23[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:01:23[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:01:28[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:01:28[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:01:51[DEBUG];Type; 8048; (Leave Indication)(Processed->Draft-MQTT); extended addr : 00158d0002b5c5e6; rejoin status : 01
AbeilleParser 2019-05-15 23:02:23[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:02:23[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:02:27[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:02:27[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:03:23[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:03:23[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:03:27[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-15 23:03:27[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-15 23:04:03[DEBUG];Type; 8048; (Leave Indication)(Processed->Draft-MQTT); extended addr : 00158d0003464775; rejoin status : 01
```

**Comment by KiwiHC16** [comment]
J'ai le sentiment qu'il y a des problemes au moins sur ton systeme:
- bug abeille qui provoque les erreur "undefine index"
- probleme de courverture radio car les euipements font des leave.

Pour le premier je vais regarder le code pour voir si je trouve des choses. Mais le code a beaucoup changé alors pas facile.

Pour le deuxième, pourrais tu detacher les capterus de leur emplacement et les mettre disont à un metre de la zigate en vue directe, redemarrer les demons, les re-inclure comme hier pour voir ce qu'il se passe ?

**Comment by guillaumecosta** [comment]
Test effectué avec un capteur en vue directe à 1 mètre.
Passe en timeout rapidement.
ci-joint log AbeilleParser.
Et si mon dongle Zigate était en panne ?
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3188935/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Ou en es tu de ton soucis ?

**Comment by guillaumecosta** [comment]
Je comptais attendre encore quelques jours avant de te donner le résultat, mais je crois que tout est bon maintenant.
Ma clé Zigate était bien en panne. Avec la nouvelle clé, tout a l'air très stable.
Qu'y a-t'il de pire qu'une panne pas franche...
Merci pour le temps que tu as passé sur mon problème.

**Comment by KiwiHC16** [comment]
Tu es le bienvenu.
Je clos le point si tu as de nouveaux sujets, ouvre une issue.
