### ISSUE TITLE
Potentielle correction du fichier setVert.json

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#685]
Bonjour,

Tout d'abord, merci beaucoup pour ce travail titanesque ! tout ce qui a été fait ici est vraiment énorme !
Je suis sur Jeedom depuis quelques semaines, j'achète petit à petit tous les composant dont j'ai besoin et du coup je privilégie le zigbee, et étant SysAdmin dans la vraie vie, j'ai tendance à chercher à comprendre et essayer de faire par moi-même donc si je peux ajouter quelques petites pierres à l'édifice ce sera avec plaisir :)
Après étude du fonctionnement des templates (je suis en train d'essayer d'en créer un pour une ampoule GLEDOPTO GL-B-008Z, je le partagerais quand j'aurais terminé) je pense avoir trouvé une coquille, donc dans le doute je le met ici.
fichier : 
/var/www/html/plugins/Abeille/core/config/devices/Template/setVert.json

Version GIT : 
`
{
  "setVert": {
    "isVisible": 0,
    "name": "setVert",
    "order": 43,
    "isHistorized": "0",
    "Type": "action",
    "subType": "slider",
    "generic_type": "DONT",
    "value": "colorVert",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07c766251f1",
      "topic": "additionalCommand",
      "request": "EP=#EP#&color=#slider#",
      "visibilityCategory": "All"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}
`

version corrigée (?) : 
`{
  "setVert": {
    "isVisible": 0,
    "name": "setVert",
    "order": 43,
    "isHistorized": "0",
    "Type": "action",
    "subType": "slider",
    "generic_type": "DONT",
    "value": "colorVert",
    "invertBinary": "0",
    "template": "",
    "configuration": {
      "uniqId": "5c07c766251f1",
      "topic": "setVert",
      "request": "EP=#EP#&color=#slider#",
      "visibilityCategory": "additionalCommand"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}`

Je reste dispo au besoin
bonne soirée !

**Comment by KiwiHC16** [comment]
Salut,
Désolé pour cette réponse tardive.

Je suis preneur pour toute aide. Si tu souhaites de l aide pour rentrer dans le code je peux aider aussi.

Effectivement deux coquilles dans un meme fichier !!!!

Je viens de faire la correction et de la mettre dans le master.

Merci.

**Comment by elydan** [comment]
Salut,
Pas de soucis, je suis déjà content de contribuer ;)
Pour les autres trucs que je verrai je t'ouvrirai d'autres issues (il faut faire propre ^^)
merci pour la correction !
