### ISSUE TITLE
Commande setColourRGB deffectueuse

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#688]
Salut,

pour info lorsqu'on utilise les commandes setColourRGB (voir image) il y a une incompréhension du plugin pour la seconde option.
![image](https://user-images.githubusercontent.com/49734864/56603905-07995300-6601-11e9-8b4a-08a4a739d789.png)
Je m'explique : la première ligne permet à l'utilisateur d'entrer un code Hexa sans le "#", tandis que la seconde utilise la fonction de couleur de Jeedom. seulement Jeedom transmet avec un "#" ce qui créé deux type de retour différents pour la même valeur.

J'ai corrigé en remplaçant ceci : 
master/core/class/AbeilleMQTTCmd.php:2776
		if (count($fields) > 1) {
			$parameters = proper_parse_str( $msg );
		}

par : 
		if (count($fields) > 1) {
			$parameters = proper_parse_str( $msg );
			if (strlen($parameters['color']) == 7) {
				$parameters['color'] = substr($parameters['color'], 1);
			}
		}

Bonne soirée !

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Super. Merci. Je le mets dans le master.

**Comment by KiwiHC16** [comment]
Dans le master.
