### ISSUE TITLE
Intégration TRADFRI Repeater

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#689]
Salut,

Je viens d'acheter un repeater TRADFRI (https://www.ikea.com/fr/fr/catalog/products/10400408/)
Il n'est pas reconnu (même pas son type) du coup je l'ai intégré en mode semi-automatique pour ne pas qu'il le jette.
0000-01-0005 : TRADFRI signal repeater
SimpleDesc-01-DeviceDescription : zigbeeRange Extender

Descriptor :
AbeilleParser 2019-04-23 20:12:45[debug];type; 8045; (Active Endpoints Response); SQN : 17; Status : 00; Short Address : 0Db3; Endpoint Count : 02; Endpoint List :; 01; f2
AbeilleParser 2019-04-23 20:12:58[debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 18; Status : 00; Short Address : 0Db3; Length : 1a; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0008 (Range Extender); bitField : 00; InClusterCount : 06
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: 0000 - General: Basic
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: 0003 - General: Identify
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: 0009 - General: Alarms
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: 0B05 - Misc: Diagnostics
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: 1000 - ZLL: Commissioning
AbeilleParser 2019-04-23 20:12:58[debug]In cluster: fc7c -
AbeilleParser 2019-04-23 20:12:58[debug]OutClusterCount : 03
AbeilleParser 2019-04-23 20:12:58[debug]Out cluster: 0019 - General: OTA
AbeilleParser 2019-04-23 20:12:58[debug]Out cluster: 0020 - General: Poll Control
AbeilleParser 2019-04-23 20:12:58[debug]Out cluster: 1000 - ZLL: Commissioning
AbeilleParser 2019-04-23 20:12:58[debug];Type; fct; processAnnonce, Switch default: WARNING should not exist for ->0Db3<- with state -><-
AbeilleParser 2019-04-23 20:13:03[debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 19; Status : 00; Short Address : 0Db3; Length : 0C; endpoint : f2; profile : a1e0 (); deviceId : 0061 (); bitField : 00; InClusterCount : 01
AbeilleParser 2019-04-23 20:13:03[debug]In cluster: 0021 -
AbeilleParser 2019-04-23 20:13:03[debug]OutClusterCount : 01
AbeilleParser 2019-04-23 20:13:03[debug]Out cluster: 0021 -
AbeilleParser 2019-04-23 20:13:03[debug];Type; fct; processAnnonce, Switch default: WARNING should not exist for ->0Db3<- with state -><-

Merci

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Je viens de mettre un modele dans le master.
Peux tu tester ? La creation de l equipement dans Jeedom et si il apparait dans les graphs Network.

**Comment by elydan** [comment]
Je teste ça ce soir

**Comment by elydan** [comment]
testé, ça fonctionne bien, pas de soucis, juste une remarque, la catégorie "Lumière" est coché nativement, ce qui je pense n'est pas cohérent.
Pour tout le reste nickel

**Comment by KiwiHC16** [comment]
Super !
Dans qu'elle catégorie le vois tu ?

**Comment by elydan** [comment]
pour le coup je le verrai plus dans automatisme, voir dans autre, puisqu'il n'a pas d'usage domotique spécifique.

**Comment by KiwiHC16** [comment]
Fonctionne nickel.
Modele changé pour etre en automatisme.
Dans master.

**Comment by tcharp38** [comment]
Réouvert suite souci https://community.jeedom.com/t/inclusion-tradfi-signal-repeter/68393

**Comment by chrisb13790** [comment]
ci joint les log
[AbeilleLogs-211001.tar.gz](https://github.com/KiwiHC16/Abeille/files/7268161/AbeilleLogs-211001.tar.gz)
s

**Comment by tcharp38** [comment]
@chrisb13790 
Je vois déja que ton FW est vieux. Tu es toujours en 3.1c. La 3.1d est requise au minimum maintenant. 
Tu as qqch contre migrer vers une version + recente ?

**Comment by chrisb13790** [comment]
non juste manque de temps pour suivre lol

**Comment by chrisb13790** [comment]
la 3.1e n est pas encore op je crois

**Comment by tcharp38** [comment]
Au moins la 3.1d.
La 3.1e est deja officielle tout comme la 3.20.
Moi je test en 3.1d ou 3.1e

**Comment by chrisb13790** [comment]
Tu me conseille laquelle ?

**Comment by tcharp38** [comment]
3.1e je ne vois pas de soucis depuis qu'elle existe

**Comment by chrisb13790** [comment]
Ok je ferai ça demain
Merci

**Comment by tcharp38** [comment]
Salut @chrisb13790 
Tu veux toujours travailler la dessus ?

**Comment by chrisb13790** [comment]
Que veux tu dire par travailler dessus ?
La j ai mon mini pc qui a crasher il démarre plus du coup suis repassé sur
un pi 4 bcp de souci sur tous les plugins que je règle au fur et à mesure j
ai plein de perif en inconnu ou pas dans l audit réseau

**Comment by tcharp38** [comment]
Ha donc ca n'est pas le moment. Je te laisse regler tes soucis hors abeille.
Bon courage

**Comment by chrisb13790** [comment]
Hors abeille j ai que airzone mais là je crois que je vais devoir voir avec
eux
Dis moi de quoi tu as besoin des screens ,des logs, etc.....

**Comment by tcharp38** [comment]
Le sujet etait "pb d'inclusion du signal repeater Ikea".

Si tu as un FW >= 3.1d et que tu aligné sur la derniere stable ou beta ou peut a nouveau creuser ca si tu le souhaites.
Il me faut un package de logs qui suit une tentative d'inclusion du repeater et dis moi si tu es sur la stable ou la beta.

**Comment by tcharp38** [comment]
@chrisb13790 
As tu encore des soucis d'inclusion du repeater Ikea ?
Si oui peux tu tester la beta 211015-BETA-1 ? J'ai corrigé une regression de ce coté.
Elle devrait basculer en stable dans la semaine.

**Comment by tcharp38** [comment]
Je considere le pb résolu. Je clos
A reouvrir si besoin

**Comment by chrisb13790** [comment]
Oui j ai pas eu de souci pour le moment
