### ISSUE TITLE
intégration GLEDOPTO bulbs

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#690]
Salut,

J'ai intégré deux bulbs, le GL-B-001Z et le GL-B-008Z, voici un zip qui contient tout (sauf erreur de ma part).

Par contre petite prévention sur ces produits, ils ne semblent pas gérer correctement le mesh routing ...

Bonne soirée,
[GLEDOPTO.zip](https://github.com/KiwiHC16/Abeille/files/3109069/GLEDOPTO.zip)

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
En regardant rapidement cela semble correcte.
Je ne peux tester car je ne possede pas ces ampoules mais je te fais confiance pour les avoir testées.
J'ai juste changé les Id pour etre sure qu'ils sont uniques dans le master.
Je ne parviens pas a ouvrir l'image node_GL-B-008Z.png. Le fichier semble corrompu, peux tu me le renvoyer ?

Qu est ce qui te fait dire qu'elles ne "route" pas ?

**Comment by elydan** [comment]
Ok pour les ID, je me doutais que tu devrais les changer ^^
Concernant l'image, en effet il y avait un problème, la voici refaite.
![node_GL-B-008Z](https://user-images.githubusercontent.com/49734864/56720573-6cf55d00-6743-11e9-9961-c7eed2825fd9.png)
Concernant le rooting, en fait dans la partie Network list, seuls mes équipements Ikea (j'ai du Ikea, du GLEDOPTO et du Xiaomi, uniquement en end device) apparaissent dans la liste côté gauche (Name) les Bulbs sont voisins de tout, donc sont bien pris en compte en receiver, mais pas en sender, ce qui se confirme sur le plan.
![image](https://user-images.githubusercontent.com/49734864/56720809-e8570e80-6743-11e9-8e9a-434a8d2a3016.png)

Sur l'image ci-dessus, on constate (même si c'est un peu fouillis) que les ampoules sont bien considérées comme des routeurs, mais ne semble pas communiquer entre elles, alors que les autres routeurs forment un maillage cohérent.
En faisant des recherches je suis tombé sur d'autres sujet similaires, dont celui-ci : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1374

Si tu as une idée, je prend ;)

**Comment by KiwiHC16** [comment]
Image dans master.

Pour être précis ce graphe ne donne pas le routage. Ce graphe donne les mesures de qualité radio entre équipement si jamais ils decidaient de communiquer entre eux.

Je crois me souvenir d'un soucis avec le GLEDOPTO qui est qu'il ne remonte pas ces mesures. Peux tu me faire une capture de la table (pas du graph) avec toutes les information et me donner le nom d'une des ampoules GLEDOPTO ?

**Comment by KiwiHC16** [comment]
Je viens de regarder et je te confirme que les infos qui remontent des GledOpto sont "pourries".
Mais les autres équipements indiquent que les GledOpto sont des routeurs.
Apres il faudrait que je sniff le traffic pour vérifier mais la je n'ai pas trop le temps.
Pour moi ca route mais les infos radio sont crap.

**Comment by elydan** [comment]
tiens, je t'ai fais un graph plus simple :
![image](https://user-images.githubusercontent.com/49734864/56763067-b2e10e00-67a1-11e9-85e2-0e30ea673548.png)
si ça peut aider, hésite pas à m'expliquer comment sniffer, on gagnera tous les deux du temps, tu auras pas à le faire et je mettrai pas 8 ans à chercher ^^

**Comment by elydan** [comment]
Après un événement (dont je ne me rappelle plus, parce que je me bat avec depuis des heures, peut-être un redémarrage) certains "end device" n'avaient plus d'adresse IEEE dans la fenêtre "santé" j'ai donc cherché à les récupérer et je pense avoir compris le problème des GLEDOPTO. à mon avis les capteurs concernés par cette perte devaient passer par elles et j'ai pu constater qu'ils continuaient à envoyer leurs infos (température / porte ouverte ou fermée) MAIS pas moyen qu'ils répondent à mes requêtes alors que j'arrive très bien à interroger d'autres devices du même type !
Du coup j'en déduis que les GLEDOPTO arrivent à emmètre vers la ZiGate mais que ce n'est pas réciproque, elles semblent ne pas comprendre ce que la ZiGate leur demande !

on a donc la situation suivante :
- les capteurs envoient leurs infos, et c'est bien récupéré par la ZiGate
- les autres routeurs arrivent à communiquer avec les GLEDOPTO et envoient donc les infos correspondantes à la ZiGate
- dès que l'info doit partir de la ZiGate et arriver aux GLEDOPTO, ça foire
            - demande ZiGate => GLEDOPTO "indique moi les infos network"
            - demande ZiGate => Capteur (qui passe par GLEDOPTO) "indique moi ton IEEE"

Je précise également que ce ne sont bien sûr que les tâche de routing qui ont ce problème, car les fonctions de end device (allumer la lumière, remonter l'état, bref l'usage courant) fonctionnent très bien.

Dis moi si le raisonnement te semble correct, auquel cas, je doute que tu puisses régler le problème, il faudra surement voir ça avec faireçasoimeme......

**Comment by KiwiHC16** [comment]
Les "end devices" dans le vocable Zigbee sont sur batteries. Cela veut dire qu'ils dorment 99%, ils ne peuvent donc pas répondre aux requêtes. Si tu veux qu'ils répondent il faut que tu les reveilles avec un appui sur le bouton par exemple mais la fenêtre de tir est de qq secondes.

De plus je ne comprends pas pourquoi les "end device" ont perdu le IEEE car Abeille n'a aucune raison de les enlever.

La seule raison que je vois est que tu fasses un "Recalcul du cache" et comme le GledOpto envoient n'importent quoi (comme indiqué plus haut), ca met la pagaille. Si c'est le problème, la zigate n'y peut rien (donc Akila ni peut rien) et il faut demander à GledOpto un correctif, et la!! bonne chance!! La solution serait qu'au niveau d'abeille je filtre "mieux" les valeurs "pourries".

Peux tu faire une capture d'écran santé, puis "Recalcul du cache", puis capture santé, et partager le Log AbeilleParser pendant le "Recalcul du cache" ? 

Je ne suis pas sure de tout comprendre de ta situation...

**Comment by KiwiHC16** [comment]
Pas de news depuis 2 semaines. Je clos. Rouvres si tu as besoin.
