### ISSUE TITLE
Correction templates getColorX et getColorY

### ISSUE THREAD

**Issue by elydan** [KiwiHC16/Abeille#691]
Salut,

Dans ces deux templates, la requette est celle-ci :
"request": "clusterId=0300&attributeId=0004"

Pour moi du coup ça ne fonctionne pas et j'ai dû repasser sur mes ampoules à la main, du coup je propose de remplacer cette ligne par : 
"request": "clusterId=0300&attributeId=0004&EP=#EP#"
à la condition qu'il n'y ai pas d'effet de bord dont je n'aurai pas conscience bien sûr.

Bonne soirée

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Exact. Un oubli quand j'ai fait la mise a jour des EP.
Nickel. 
Je le mets dans le master.
