### ISSUE TITLE
Exterieur Xiaomi Temperature Sensor Batterie drop and loose messages

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#695]
Find a battery which accept cold environment.

**Comment by smulle48** [comment]
I use these in the danish climate in my Xiaomi button (as doorbell) still running the same battery for two years without problem

http://data.energizer.com/pdfs/cr2032.pdf

**Comment by KiwiHC16** [comment]
Interesting. Thanks.
