### ISSUE TITLE
Problème timeout

### ISSUE THREAD

**Issue by firerdinger** [KiwiHC16/Abeille#696]
Bonjour à tous.
Je pense que le problème a déja été soulevé, mais je me lance quand même.
J'ai une clé zigate achetée et recue debut de semaine, sur laquelle, sur un RP 3 B+ j'ai connecté pour le moment 6 sensors d'ouverture aqara, et 2 hygro xiaomi aqara.
Tout fonctionne a merveille durant 20/24h, et ensuite, hop, timeout... qui ne peut être corrigé qu'en desactivant le plugin puis le reactivant, et relance du deamon...

Ai-je un souci, ou est-ce un problème connu et dans ce cas, quelle est la solution ? Par avance, merci.

**Comment by KiwiHC16** [comment]
Salut,
Quel type de zigate est ce ? USB ?
Peux tu mettre le plugin en debug et partager Abeille et AbeilleParser quand ça plante ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KiwiHC16** [comment]
@firerdinger , des infos ?

**Comment by firerdinger** [comment]
Salut et désolé du temps mis pour répondre mais je faisais des tests !
Donc après déplacement du rp plus de soucis.
Il’semblerait Que tout ne captait pas tout le temps... d’où la détection puis timeout au bout de x heures.

**Comment by KiwiHC16** [comment]
Super. Ajoutes de routeurs pour avoir une meilleure couverture radio.
Je clos le sujet.
