### ISSUE TITLE
Intégration Zigbee OnOff Controller

### ISSUE THREAD

**Issue by dokime7** [KiwiHC16/Abeille#697]
Serait-il possible d'ajouter la prise en charge de ce module switch ON/OFF ?
Il est semble-t-il déjà compatible zigate :
https://zigate.fr/le-materiel-compatible-zigate/compatible/transformateursimple/
(ça n'est pas un transformateur mais un relais switch on/off)

Dispo ici : https://www.amazon.fr/gp/product/B07PDH45DC

J'ai pu l'ajouter en mode semi-automatique mais il y a uniquement des commande infos et pas d'action pour faire ON et OFF.

```
[2019-05-08 21:47:18][INFO] : Recherche objet: zigbeeOn/Off Light dans les objets connus
[2019-05-08 21:47:18][INFO] : objet: zigbeeOn/Off Light recherché comme zigbeeOnOffLight ne peut pas etre creer car je ne connais pas ce type d objet.
```

```
[2019-05-08 21:49:30][INFO] : objet: 01124b001bae7df3 creation sans model
[2019-05-08 21:49:30][INFO] : Creation par defaut de la commande: Abeille/9ce1/Time-TimeStamp
[2019-05-08 21:49:30][INFO] : Creation par defaut de la commande: Abeille/9ce1/Time-Time
[2019-05-08 21:49:32][INFO] : Creation par defaut de la commande: Abeille/9ce1/Link-Quality
[2019-05-08 21:49:32][INFO] : Creation par defaut de la commande: Abeille/9ce1/0000-0B-0005
[2019-05-08 21:49:32][INFO] : Creation par defaut de la commande: Abeille/9ce1/Short-Addr
[2019-05-08 21:49:37][INFO] : Creation par defaut de la commande: Abeille/9ce1/0000-0B-0010
[2019-05-08 21:49:37][INFO] : Creation par defaut de la commande: Abeille/9ce1/Power-Source
[2019-05-08 21:49:38][INFO] : Creation par defaut de la commande: Abeille/9ce1/SimpleDesc-0B-DeviceDescription
```

```
AbeilleMQTTCmd 2019-05-08 21:49:32[INFO]Msg Received: Topic: {CmdAbeille/Ruche/ActiveEndPoint} => address=9ce1
AbeilleMQTTCmd 2019-05-08 21:49:32[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:32[INFO]Msg Received: Topic: {CmdAbeille/Ruche/getName} => address=9ce1&destinationEndPoint=0B
PHP Warning:  Missing argument 6 for getParam(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 2002 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 344
PHP Notice:  Undefined variable: Proprio in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 406
AbeilleMQTTCmd 2019-05-08 21:49:32[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:32[INFO]Msg Received: Topic: {CmdAbeille/Ruche/getLocation} => address=9ce1&destinationEndPoint=0B
PHP Warning:  Missing argument 6 for getParam(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 2011 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 344
PHP Notice:  Undefined variable: Proprio in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 406
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]Msg Received: Topic: {CmdAbeille/Ruche/ActiveEndPoint} => address=9ce1
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]Msg Received: Topic: {CmdAbeille/Ruche/getName} => address=9ce1&destinationEndPoint=0B
PHP Warning:  Missing argument 6 for getParam(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 2002 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 344
PHP Notice:  Undefined variable: Proprio in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 406
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:35[INFO]Msg Received: Topic: {CmdAbeille/Ruche/getLocation} => address=9ce1&destinationEndPoint=0B
PHP Warning:  Missing argument 6 for getParam(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 2011 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 344
PHP Notice:  Undefined variable: Proprio in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 406
AbeilleMQTTCmd 2019-05-08 21:49:37[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:37[INFO]Msg Received: Topic: {CmdAbeille/Ruche/ActiveEndPoint} => address=9ce1
AbeilleMQTTCmd 2019-05-08 21:49:37[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:37[INFO]Msg Received: Topic: {CmdAbeille/Ruche/SimpleDescriptorRequest} => address=9ce1&endPoint=0B
AbeilleMQTTCmd 2019-05-08 21:49:39[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:39[INFO]Msg Received: Topic: {CmdAbeille/Ruche/ActiveEndPoint} => address=9ce1
AbeilleMQTTCmd 2019-05-08 21:49:39[INFO]-----
AbeilleMQTTCmd 2019-05-08 21:49:39[INFO]Msg Received: Topic: {CmdAbeille/Ruche/SimpleDescriptorRequest} => address=9ce1&endPoint=0B
```

**Comment by KiwiHC16** [comment]
Salut
Je viens d en commander un mais ça va prendre du temps. 
Je peux essayer de faire un modèle pour l intégrer. 
Il faudrait le log abeilleparser quand tu fais les inclusions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dokime7** [comment]
Hello,
Il n'y a rien de plus que quelques erreurs dans abeilleparser lors de l'inclusion : 

```
PHP Notice:  Undefined variable: name in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 1134
PHP Notice:  Undefined index: action in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2463
PHP Notice:  Undefined index: timeAnnonceReceived in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2540
PHP Notice:  Undefined index: IEEE in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2542
PHP Notice:  Undefined index: capa in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2544
PHP Notice:  Undefined index: action in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2463
PHP Notice:  Undefined index: timeAnnonceReceived in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2540
PHP Notice:  Undefined index: IEEE in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2542
PHP Notice:  Undefined index: capa in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2544
PHP Notice:  Undefined index: state in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2446
PHP Notice:  Undefined index: state in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/AbeilleParser.php on line 2529
```

**Comment by KiwiHC16** [comment]
Salut,
Bon je suis un peu sous l'eau en ce moment.
Je ferai l integration des que je recois le module cela sera plus simple et rapide.
Probablement en fin de mois.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by dokime7** [comment]
Ça marche merci :)

**Comment by Hydci** [comment]
Bonjour, j'ai le même objet et au moment de l’inclusion voici ce que j'ai dans  log abeilleparser

AbeilleParser 2019-05-18 08:54:03[DEBUG];type; 8014; ( “Permit join” status response)(Processed->MQTT); Permit Join Status: 01
AbeilleParser 2019-05-18 08:54:08[DEBUG];Type; 004d; (Device announce)(Processed->MQTT); Src Addr : b96d; IEEE : 01124b001c2e5435; MAC capa : 8e
AbeilleParser 2019-05-18 08:54:08[DEBUG];Type; 004d; (Device announce)(Processed->MQTT); Src Addr : b96d; IEEE : 01124b001c2e5435; MAC capa : 8e
AbeilleParser 2019-05-18 08:54:08[DEBUG];type; 8701; (Route Discovery Confirm)(Decoded but Not Processed); Status : 00; Nwk Status : 00
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg, NE: {"b96d":{"IEEE":"01124b001c2e5435","capa":"8e","timeAnnonceReceived":1558162448,"state":"annonceReceived"}}
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg ; ===> Demande le EP de l equipement
AbeilleParser 2019-05-18 08:54:10[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9a
AbeilleParser 2019-05-18 08:54:10[DEBUG];type; 8045; (Active Endpoints Response); SQN : 9a; Status : 00; Short Address : b96d; Endpoint Count : 01; Endpoint List :; 0B
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg, NE: {"b96d":{"IEEE":"01124b001c2e5435","capa":"8e","timeAnnonceReceived":1558162448,"state":"EndPoint","action":"annonceReceived->ActiveEndPoint","EP":"0B"}}
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg ; ===> Demande le nom de l equipement
AbeilleParser 2019-05-18 08:54:10[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 04
AbeilleParser 2019-05-18 08:54:10[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 05
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 04; Src Addr : b96d; End Point : 0B; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0007; Data byte list : ->Lamp_01<-
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg, NE: {"b96d":{"IEEE":"01124b001c2e5435","capa":"8e","timeAnnonceReceived":1558162448,"state":"modelIdentifier","action":"ActiveEndPointReceived->modelIdentifier","EP":"0B","modelIdentifier":"Lamp_01"}}
AbeilleParser 2019-05-18 08:54:10[DEBUG];Type; fct; processAnnonceStageChg ; ===> Configure NE
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; ===> Configure NE Start
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; ===> Configure NE End
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 05; Src Addr : b96d; End Point : 0B; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0010; Data byte list : ->                <-
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; processAnnonceStageChg, NE: {"b96d":{"IEEE":"01124b001c2e5435","capa":"8e","timeAnnonceReceived":1558162448,"state":"configuration","action":"modelIdentifierReceived->configuration","EP":"0B","modelIdentifier":"Lamp_01"}}
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; processAnnonceStageChg ; ===> Demande Current State Equipement
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9b
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; processAnnonceStageChg, NE: {"b96d":{"IEEE":"01124b001c2e5435","capa":"8e","timeAnnonceReceived":1558162448,"state":"currentState","action":"configuration->currentState","EP":"0B","modelIdentifier":"Lamp_01"}}
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 06
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 07
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8045; (Active Endpoints Response); SQN : 9b; Status : 00; Short Address : b96d; Endpoint Count : 01; Endpoint List :; 0B
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 06; Src Addr : b96d; End Point : 0B; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0007; Data byte list : ->Lamp_01<-
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 07; Src Addr : b96d; End Point : 0B; Cluster ID : 0000; Attr ID : 0010; Attr Status : 00; Attr Data Type : 42; Attr Size : 0010; Data byte list : ->                <-
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 73; Src Addr : b6d7; End Point : 0B; Cluster ID : 0006; Attr ID : 0000; Attr Status : 00; Attr Data Type : 10; Attr Size : 0001; Data byte list : 00
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9c
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9d
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8045; (Active Endpoints Response); SQN : 9c; Status : 00; Short Address : b96d; Endpoint Count : 01; Endpoint List :; 0B
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 9d; Status : 00; Short Address : b96d; Length : 14; endpoint : 0B; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 05
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2019-05-18 08:54:15[DEBUG]OutClusterCount : 01
AbeilleParser 2019-05-18 08:54:15[DEBUG]Out cluster: 0000 - General: Basic
AbeilleParser 2019-05-18 08:54:15[DEBUG];Type; fct; processAnnonce, Switch default: WARNING should not exist
AbeilleParser 2019-05-18 08:54:17[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9e
AbeilleParser 2019-05-18 08:54:17[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 9f
AbeilleParser 2019-05-18 08:54:17[DEBUG];type; 8045; (Active Endpoints Response); SQN : 9e; Status : 00; Short Address : b96d; Endpoint Count : 01; Endpoint List :; 0B
AbeilleParser 2019-05-18 08:54:17[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 9f; Status : 00; Short Address : b96d; Length : 14; endpoint : 0B; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 05
AbeilleParser 2019-05-18 08:54:17[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2019-05-18 08:54:17[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2019-05-18 08:54:17[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2019-05-18 08:54:17[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2019-05-18 08:54:17[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2019-05-18 08:54:17[DEBUG]OutClusterCount : 01
AbeilleParser 2019-05-18 08:54:17[DEBUG]Out cluster: 0000 - General: Basic
AbeilleParser 2019-05-18 08:54:17[DEBUG];Type; fct; processAnnonce, Switch default: WARNING should not exist
AbeilleParser 2019-05-18 08:54:24[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-18 08:54:24[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.
AbeilleParser 2019-05-18 08:54:28[DEBUG];type; 8000; (Status)(Not Processed); Length: 5; Status: 00-(Success); SQN: 00
AbeilleParser 2019-05-18 08:54:28[DEBUG];type; 8000; SQN: 0 for messages which are not transmitted over the air.

**Comment by KiwiHC16** [comment]
->Lamp_01<-
```
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8045; (Active Endpoints Response); SQN : 9c; Status : 00; Short Address : b96d; Endpoint Count : 01; Endpoint List :; 0B
AbeilleParser 2019-05-18 08:54:15[DEBUG];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 9d; Status : 00; Short Address : b96d; Length : 14; endpoint : 0B; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 05
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0000 - General: Basic
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0003 - General: Identify
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0004 - General: Groups
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0005 - General: Scenes
AbeilleParser 2019-05-18 08:54:15[DEBUG]In cluster: 0006 - General: On/Off
AbeilleParser 2019-05-18 08:54:15[DEBUG]OutClusterCount : 01
AbeilleParser 2019-05-18 08:54:15[DEBUG]Out cluster: 0000 - General: Basic
```

On doit pouvoir faire un modele avec ces infos...

**Comment by Hydci** [comment]
Bonne nouvelle tout ça a toi de jouer du coup

**Comment by KiwiHC16** [comment]
Livraison prévue pour le 7 juin.

**Comment by KiwiHC16** [comment]
Je viens de mettre le modele dans le master, mais je ne peux pas le tester encore.

**Comment by KiwiHC16** [comment]
Je viens d'en recevoir un, de le brancher et il fonctionne.

**Comment by dokime7** [comment]
Testé aussi, ça marche.
Un grand merci à toi :)
