### ISSUE TITLE
Gledopto strip led

### ISSUE THREAD

**Issue by bananavdk** [KiwiHC16/Abeille#698]
bonjour, j'ai un petit soucis quand a la gestion des couleurs.
j'ai l'impression que dans le code il y a un loupé sur la traduction de la couleur pour l'envoyé a l'équippement le stripled est soit bleu quand je demandedu bleu soit vert quand je demande du rouge et bleu faible quand je demande du vert.(j'ai testé avec le plugin ZIGATE et sa fonctionne comme il faut donc ce n'est pas un souci de cablage).
pour le reste RAS la luminosité fonctionne très bien l'allumage et l'extinction aussi.
jedom V3.3.24
ZIGATE wifi V30f
module GLEDOPTO RGB+CCT.
commande utiliser pour le changement de couleur : setRGB playload: EP=0B&color=#color#
s'il y a besoin de plus d'info je reste a dispo.
d'avance merci.

**Comment by KiwiHC16** [comment]
Sur qu'elle version de Abeille es tu ?

**Comment by bananavdk** [comment]
Sur le plugin la version est noté 2019-03-16 01:01:09

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by bananavdk** [comment]
J’allais te demander où sa en était si tu avais trouvé le problème ?

Sa sera réglé dans la prochaine MAJ ?

**Comment by KiwiHC16** [comment]
Je viens de tester avec mon Gleopte Wireless RGB+CCT Led Controller et tout est ok.
Mais la couleur des fils du ruban n'est pas bonne. Ils ne sont pas connecter aux bonnes Led.
Donc le fil Blanc est sur le blan controller (c est ce qu on souhaite)
Le noir est sur le V+
Le bleu est sur le B (C est ce qu on souhaite)
mais
le rouge est sur G 
et le vert est sur R
En gros rouge et vert sont inversés.

**Comment by bananavdk** [comment]
Non les couleurs ne sont pas inversées chez moi, mais attention il y a des bandeaux à anodes communes et d'autres à cathode commune ton problème viens peut être de la !

**Comment by KiwiHC16** [comment]
J'en ai 3 en stock alors je vais essayer avec les trois.
Sur l un deux on peut voir le cablage et j'ai 
Noir sur +12V
Fil Bleu sur G du bandeau
Fil Vert sur R du bandeau
Fil Rouge sur B du bandeau
Fil Blanc sur W du bandeau

Autant dire que les couleurs de fils ne veulent rien dire.

Pour le troisieme il faut que je coupe la prise et connecte directement 

Peux tu verifier le cablege sur le tiens ? Peux tu partager une photo ?

**Comment by bananavdk** [comment]
[image1.jpeg]
[image2.jpeg]
Comme tu peut le voir, je suis bien en +commun ma bande de led est faite comme sa, regarde sur al tienne les infos au niveau des points de coupe, c’est écrit quoi ? Tu as une photo ?

**Comment by KiwiHC16** [comment]
Peux tu ajouter les photos, elles ne sont pas visibles.

**Comment by KiwiHC16** [comment]
Je viens de brancher le deuxieme ruban et tout fonctionne nickel.
![IMG_0098](https://user-images.githubusercontent.com/8549674/58746227-1f63c280-845c-11e9-92cc-6fe69ad811fb.jpeg)
![IMG_0099](https://user-images.githubusercontent.com/8549674/58746235-43bf9f00-845c-11e9-86dc-b73b3e9b21d8.jpeg)

**Comment by bananavdk** [comment]
Sur la photo de ta bande led les fils des couleurs sont inversées (défaut à la fabrication) , donc avec le boîtier tu doit mettre pour ce bandeau le noir sur +12 le bleu sur le G le vert sur le R et le rouge sur le B.

**Comment by KiwiHC16** [comment]
C est bien ce que j'ai fait et tout fonctionne.
Maintenant quid de ton systeme ?

**Comment by bananavdk** [comment]
J’ai pas tout compris de ton mail qu’est-ce que tu veux dire de quid ?

**Comment by KiwiHC16** [comment]
Est ce que ton systeme fonctionne ?
Si non, envoies moi les photos.

**Comment by bananavdk** [comment]
Bien sûr que sa fonctionne 🤪 et même avec Alexa tu veut des photos de quoi ?

**Comment by KiwiHC16** [comment]
Ben si tu ouvres une 'issue' c'est que tu as besoin d'aide: " j'ai un petit soucis quand a la gestion des couleurs."

Ca fonctionne ou ne fonctionne pas ?
As tu résolu ton soucis ?

**Comment by bananavdk** [comment]
Ha oui pardon, depuis la MAJ il y a quelques jours tout fonctionne nickel il faut que je passe le problème en résolut

**Comment by KiwiHC16** [comment]
Ok Super merci.
Ben oui pensez à moi sinon je perds mon temps, c'est frustrant.

**Comment by bananavdk** [comment]
Excuse-moi j’ai vais pas compris que Ben c’était toi...
oui je suis un boulet.

**Comment by KiwiHC16** [comment]
Pas de soucis.
Le principal c est que ca fonctionne.

**Comment by bananavdk** [comment]
Oui et sa fait avancer ton plugin dans le bon sens ;)

Envoyé de mon iPhone

Le 2 juin 2019 à 14:14, Ben <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pas de soucis.
Le principal c est que ca fonctionne.
