### ISSUE TITLE
Redemarrage demon NOK après avoir débanché la zigate

### ISSUE THREAD

**Issue by ivan9187** [KiwiHC16/Abeille#699]
Bonjour,

Le demmon ne redémarra pas même après reset à froid de jeedom.
Clé zigate reconnue sur le port USB 0
Log debug:
[2019-05-11 18:13:45][DEBUG] : Parametres utilises, Host : 127.0.0.1,             Port : 1883,             AbeilleParentId : 1,             AbeilleConId: jeedom,             AbeilleUser: jeedom,             Abeillepass: jeedom,             AbeilleSerialPort: /dev/ttyUSB0,             qos: 0,             showAllCommands: N,             affichageNetwork: N,             affichageTime: N,             affichageCmdAdd: N,             ModeCreation: Automatique,             adresseCourteMode: Automatique,             onlyTimer: N,             IpWifiZigate : 192.168.4.1
[2019-05-11 18:13:45][ERROR] : The client is not currently connected.

Dans le log jeedom:

  | 2019-05-11 18:27:41 | Abeille | Erreur sur la fonction deamon_start du plugin : The client is not currently connected. |  
-- | -- | -- | -- | --
  | 2019-05-11 18:27:30 | Abeille | Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement

Merci,
Ivan

**Comment by KiwiHC16** [comment]
Bonjour Ivan,
Est ce que c est un problème suite à une fresh installation (le plugin ne jamais fonctionné) ou tout fonctionnait, la zigate a été arrachée et cela ne fonctionne plus ?
As tu d autres équipements sur port USB ?
Que donne la commande, en ssh:
ls -l /dev/tty*
Est ce que mosquito fonctionne ?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ivan9187** [comment]
Sans avoir vérifier juste avant de débrancher/rebrancher la zigate il me semblais que le demon fonctionnait juste avant. Sur les autres port j'ai un rfplayer et une clé huawei 3372. j'ai essayer de change le port de la clé zigate sans succès. 
Mosquito samble ok :
root@odroidc2_Black:~# systemctl status mosquitto
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (exited) since Sat 2019-05-11 22:29:07 CEST; 16h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 28113 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 28119 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/mosquitto.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.




root@odroidc2_Black:~# ls -l /dev/tty*
crw-rw-rw- 1 root tty       5,  0 mai   11 18:03 /dev/tty
crw--w---- 1 root tty       4,  0 mai   11 18:03 /dev/tty0
crw--w---- 1 root tty       4,  1 mai   11 20:12 /dev/tty1
crw--w---- 1 root tty       4, 10 mai   11 18:03 /dev/tty10
crw--w---- 1 root tty       4, 11 mai   11 18:03 /dev/tty11
crw--w---- 1 root tty       4, 12 mai   11 18:03 /dev/tty12
crw--w---- 1 root tty       4, 13 mai   11 18:03 /dev/tty13
crw--w---- 1 root tty       4, 14 mai   11 18:03 /dev/tty14
crw--w---- 1 root tty       4, 15 mai   11 18:03 /dev/tty15
crw--w---- 1 root tty       4, 16 mai   11 18:03 /dev/tty16
crw--w---- 1 root tty       4, 17 mai   11 18:03 /dev/tty17
crw--w---- 1 root tty       4, 18 mai   11 18:03 /dev/tty18
crw--w---- 1 root tty       4, 19 mai   11 18:03 /dev/tty19
crw--w---- 1 root tty       4,  2 mai   11 18:03 /dev/tty2
crw--w---- 1 root tty       4, 20 mai   11 18:03 /dev/tty20
crw--w---- 1 root tty       4, 21 mai   11 18:03 /dev/tty21
crw--w---- 1 root tty       4, 22 mai   11 18:03 /dev/tty22
crw--w---- 1 root tty       4, 23 mai   11 18:03 /dev/tty23
crw--w---- 1 root tty       4, 24 mai   11 18:03 /dev/tty24
crw--w---- 1 root tty       4, 25 mai   11 18:03 /dev/tty25
crw--w---- 1 root tty       4, 26 mai   11 18:03 /dev/tty26
crw--w---- 1 root tty       4, 27 mai   11 18:03 /dev/tty27
crw--w---- 1 root tty       4, 28 mai   11 18:03 /dev/tty28
crw--w---- 1 root tty       4, 29 mai   11 18:03 /dev/tty29
crw--w---- 1 root tty       4,  3 mai   11 18:03 /dev/tty3
crw--w---- 1 root tty       4, 30 mai   11 18:03 /dev/tty30
crw--w---- 1 root tty       4, 31 mai   11 18:03 /dev/tty31
crw--w---- 1 root tty       4, 32 mai   11 18:03 /dev/tty32
crw--w---- 1 root tty       4, 33 mai   11 18:03 /dev/tty33
crw--w---- 1 root tty       4, 34 mai   11 18:03 /dev/tty34
crw--w---- 1 root tty       4, 35 mai   11 18:03 /dev/tty35
crw--w---- 1 root tty       4, 36 mai   11 18:03 /dev/tty36
crw--w---- 1 root tty       4, 37 mai   11 18:03 /dev/tty37
crw--w---- 1 root tty       4, 38 mai   11 18:03 /dev/tty38
crw--w---- 1 root tty       4, 39 mai   11 18:03 /dev/tty39
crw--w---- 1 root tty       4,  4 mai   11 18:03 /dev/tty4
crw--w---- 1 root tty       4, 40 mai   11 18:03 /dev/tty40
crw--w---- 1 root tty       4, 41 mai   11 18:03 /dev/tty41
crw--w---- 1 root tty       4, 42 mai   11 18:03 /dev/tty42
crw--w---- 1 root tty       4, 43 mai   11 18:03 /dev/tty43
crw--w---- 1 root tty       4, 44 mai   11 18:03 /dev/tty44
crw--w---- 1 root tty       4, 45 mai   11 18:03 /dev/tty45
crw--w---- 1 root tty       4, 46 mai   11 18:03 /dev/tty46
crw--w---- 1 root tty       4, 47 mai   11 18:03 /dev/tty47
crw--w---- 1 root tty       4, 48 mai   11 18:03 /dev/tty48
crw--w---- 1 root tty       4, 49 mai   11 18:03 /dev/tty49
crw--w---- 1 root tty       4,  5 mai   11 18:03 /dev/tty5
crw--w---- 1 root tty       4, 50 mai   11 18:03 /dev/tty50
crw--w---- 1 root tty       4, 51 mai   11 18:03 /dev/tty51
crw--w---- 1 root tty       4, 52 mai   11 18:03 /dev/tty52
crw--w---- 1 root tty       4, 53 mai   11 18:03 /dev/tty53
crw--w---- 1 root tty       4, 54 mai   11 18:03 /dev/tty54
crw--w---- 1 root tty       4, 55 mai   11 18:03 /dev/tty55
crw--w---- 1 root tty       4, 56 mai   11 18:03 /dev/tty56
crw--w---- 1 root tty       4, 57 mai   11 18:03 /dev/tty57
crw--w---- 1 root tty       4, 58 mai   11 18:03 /dev/tty58
crw--w---- 1 root tty       4, 59 mai   11 18:03 /dev/tty59
crw--w---- 1 root tty       4,  6 mai   11 18:03 /dev/tty6
crw--w---- 1 root tty       4, 60 mai   11 18:03 /dev/tty60
crw--w---- 1 root tty       4, 61 mai   11 18:03 /dev/tty61
crw--w---- 1 root tty       4, 62 mai   11 18:03 /dev/tty62
crw--w---- 1 root tty       4, 63 mai   11 18:03 /dev/tty63
crw--w---- 1 root tty       4,  7 mai   11 18:03 /dev/tty7
crw--w---- 1 root tty       4,  8 mai   11 18:03 /dev/tty8
crw--w---- 1 root tty       4,  9 mai   11 18:03 /dev/tty9
crw--w---- 1 root tty     245,  0 mai   11 20:12 /dev/ttyAML0
crw------- 1 root root      3,  0 mai   11 18:03 /dev/ttyp0
crw------- 1 root root      3,  1 mai   11 18:03 /dev/ttyp1
crw------- 1 root root      3,  2 mai   11 18:03 /dev/ttyp2
crw------- 1 root root      3,  3 mai   11 18:03 /dev/ttyp3
crw------- 1 root root      3,  4 mai   11 18:03 /dev/ttyp4
crw------- 1 root root      3,  5 mai   11 18:03 /dev/ttyp5
crw------- 1 root root      3,  6 mai   11 18:03 /dev/ttyp6
crw------- 1 root root      3,  7 mai   11 18:03 /dev/ttyp7
crw------- 1 root root      3,  8 mai   11 18:03 /dev/ttyp8
crw------- 1 root root      3,  9 mai   11 18:03 /dev/ttyp9
crw------- 1 root root      3, 10 mai   11 18:03 /dev/ttypa
crw------- 1 root root      3, 11 mai   11 18:03 /dev/ttypb
crw------- 1 root root      3, 12 mai   11 18:03 /dev/ttypc
crw------- 1 root root      3, 13 mai   11 18:03 /dev/ttypd
crw------- 1 root root      3, 14 mai   11 18:03 /dev/ttype
crw------- 1 root root      3, 15 mai   11 18:03 /dev/ttypf
crw-rw---- 1 root dialout   4, 64 mai   11 18:03 /dev/ttyS0
crw-rw---- 1 root dialout   4, 65 mai   11 18:03 /dev/ttyS1
crw-rw---- 1 root dialout   4, 66 mai   11 18:03 /dev/ttyS2
crw-rw---- 1 root dialout   4, 67 mai   11 18:03 /dev/ttyS3
crwxrwxrwx 1 root dialout 188,  0 mai   12 14:50 /dev/ttyUSB0
crwxrwxrwx 1 root dialout 188,  1 mai   11 23:59 /dev/ttyUSB1
crwxrwxrwx 1 root dialout 188,  2 mai   12 14:53 /dev/ttyUSB2

**Comment by ivan9187** [comment]
Ma config: 
- Odroïd C2 debian 9.9
- jeedom à jour 
- zigate en 3.0f
- clé Huawei 3372 pour envoyer des SMS (free 2€)

Des actionneurs radiateurs et portails en 433MHz + des capteurs de températures & vibration xiaomi.
j'ai dèjà eu ce même problème de demon abeille que je n'ai pas résolu (hormis en restaurant une image du système debian + jeedom).
A oui j'ai aussi fait récemment une mise à jour debian (apt get upgrade)

Merci pour ton aide.

**Comment by ivan9187** [comment]
Dans santé jeedom j'ai:
Statut démon | NOK |  
Mosquitto | NOK | 

Alors qu'en ssh:
/etc/init.d/mosquitto start 
répond:
[ ok ] Starting mosquitto (via systemctl): mosquitto.service.

Le problème viendrait-il néanmoins de mosquitto ?

Merci pour ton aide.

**Comment by KiwiHC16** [comment]
Si tu fais un 
mosquitto_sub -t "#" -v
est ce que tu vois des messages passer ?

Peux tu partager les logs: Abeille, AbeilleParser et AbeilleCmdMQTT ?

**Comment by ivan9187** [comment]
Bonjour,
Voici le log (AbeilleParser et AbeilleCmdMQTT  sont vides) , je pourrais exécuter la cmde ssh que ce soir..
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/3171758/Abeille.log)

**Comment by ivan9187** [comment]
Finalement j'ai pu exécuter la cmde et il n'y a aucun message qui circule...

**Comment by KiwiHC16** [comment]
Que donne la commande:
`ps -ef | grep mosquitto`

et la commande 
`ps -ef | grep beille
`

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by ivan9187** [comment]
root     26142 25938  0 21:25 pts/0    00:00:00 grep mosquitto
root     26210 25938  0 21:25 pts/0    00:00:00 grep beille

**Comment by ivan9187** [comment]
Si le time est à zéro cela signifie que les taches ne tournent pas ?

**Comment by ivan9187** [comment]
Lors de la mise à jour de la zigate en 3.0f, je ne sais plus si j'ai bien effacé l'EEPROM.
Or suite à la mise à jour mes objects xiaomi ont bien été effacés et j'ai dû les ré-appairer puis le système avec abeille a bien fonctionné...
Si je n'avais pas effacé l'EEPROM est ce que cela aurait quand même fonctionné comme cela a été le cas ?
Le problème que je rencontre peut-il provenir de la clé Zigate ?
Merci,
Ivan

**Comment by KiwiHC16** [comment]
visiblement grep mosquitto ne retourne rien donc rien ne peut fonctionner.
Pour faire vite, je peux me connecter sur ton systeme si tu partages l ecran avec any desk (any desk.com). Il faut juste que tu me fournisse le code d acces par MP dans le forum jeedom par exemple.

**Comment by ivan9187** [comment]
Ok, je peux le faire à partir de 20h30 en semaine ou samedi à 9h ou après 17h...
Quelles sont tes dispo ?
Je te donnerais le code d'accès par MP forum jeedom...

**Comment by ivan9187** [comment]
Une piste intéressante:
En lançant la tache mosquitto en ssh : mosquitto
Le demon abeille démarre correctement (et si j'arrête la tache le demon est nok)
Normalement comment est lancé cette tache ? Quelle manip peut l'avoir stoppée (après un reboot elle n'est pas lancée) ?

# mosquitto
1557854500: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1557854500: Using default config.
1557854500: Opening ipv4 listen socket on port 1883.
1557854500: Opening ipv6 listen socket on port 1883.
1557854500: New connection from 127.0.0.1 on port 1883.
1557854500: New client connected from 127.0.0.1 as jeedom_pub_deamon_Loop_ForEver (c1, k60, u'jeedom').

**Comment by KiwiHC16** [comment]
mosquitto doit demarrer avec ton systeme.
Ensuite jeedom demarre et abeille est lancé. Abeille se connecte a mosquitto.
Je n'ai plus d'odroid en fonctionnement donc je peux regarder commen tle lancement est fait.
Regardes du côté de /etc/init.d ou service.

**Comment by ivan9187** [comment]
le service est lancé au démarrage 
pas de log mosquitto.log
et il faut que je lance mosquitto à la main à chaque reboot..
Je ne sais pas quoi faire malgré des histoires similaires sur les forums...

**Comment by KiwiHC16** [comment]
Si tu me donnes la main sur ta machine, je peux jeter un oeil rapide pour voir si qq chose me saute au yeux.

**Comment by ivan9187** [comment]
Ok, je suis chez moi ce soir à partir de 18h30, j'installerais any desk ...
Merci

**Comment by ivan9187** [comment]
est ce que je pourrais essayer qq chose comme ça ? (faut-il changer  User=mosquitto ?)

sudo update-rc.d mosquitto remove

sudo nano /etc/systemd/system/mosquitto.service

Paste and save this script

[Unit]
Description=Mosquitto MQTT Broker
Documentation=man:mosquitto(8)
Documentation=man:mosquitto.conf(5)
ConditionPathExists=/etc/mosquitto/mosquitto.conf
After=xdk-daemon.service

[Service]
ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
ExecReload=/bin/kill -HUP $MAINPID
User=mosquitto
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
sudo systemctl enable mosquitto.service
sudo reboot

check if mosquitto is running

sudo mosquitto -v

**Comment by KiwiHC16** [comment]
Impossible de te dire. Donnes moi accès qu'on regarde. Je suis sur un nouvelle version qui commence a fonctionner qui n'utilise pas mosquitto. Je vais essayer d avancer vite sur ce sujet et j espere que ca resoudra tous ces soucis relatifs a mosquitto.

**Comment by KiwiHC16** [comment]
Apres clarification, investigation c'est mosquitto qui ne demarre pas au boot, car il ne demarre pas a un /etc/init.d/mosquitto start
Il n'y a pas de log dans /var/log/mosquitto
Le fichier de conf est bon (idem au mien).

On reste sur le demarrage à la main dans la mesure ou la prochaine version d'abeille n utilisera plus mosquitto.

Je clos le cas.
