### ISSUE TITLE
MessageQueue: 2 process php a 90%

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#703]
Tout d'abord, bravo pour la restructuration d'une brique majeure de ton plugin. c'est courageux.

Suite a la mise a jour (mosquitto -> messageQueue 30/05/2019), j'ai deux process php a 90%
La température du mon RPI est passé de 60 a 83 degrés

Constates tu la même chose chez toi ? j'ai redémarré le conteneur pour m'assurer que ce n'etait pas un process zombie. Rien dans les logs en debug n'indiquent de problème. toutes les fonctions semblent correctes, les infos sont remontées dans jeedom ( ouverture porte, temperature, luminosité, présence, interrupteur ).

UID        PID  PPID  C STIME TTY      STAT   TIME CMD
www-data 17890  2883 97 07:34 ?        R     53:57 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmd.php /dev/ttyUSB0 127.0.0.1 1883 jeedom
www-data 17873  2883 96 07:34 ?        R     53:21 php /var/www/html/core/class/../php/jeeCron.php cron_id=15009 SUPERVISOR_GROUP_NAME=apache2 HOSTNAME=156ea548edfb SHLVL=2 AP

Montée en temperature
![image](https://user-images.githubusercontent.com/3601462/58613212-5b105800-82b5-11e9-881e-7b43e6521e43.png)

utilisation temps processeur
![image](https://user-images.githubusercontent.com/3601462/58613323-b2aec380-82b5-11e9-8cf9-80d0ab6b148f.png)

**Comment by KiwiHC16** [comment]
Oui c'est un gros boulot avec plein de risque de problème mais sur le long terme on n aura plus la gestion de la brique mosquitto qui est si difficile a gerer en fonction des confs des utilisateurs.
Mon premier retour d experience c est que c est nettement plus reactif aussi.
Je n'ai pas regarder les aspects cpu car je suis sur des VM.
Il est for possible que les loop non blocantes sur les queues IPC provoque une charge CPU.

**Comment by KiwiHC16** [comment]
C est vraiment cool que tu testes le truc car il y a tellememnt de changements ....

**Comment by KiwiHC16** [comment]
J'ai deux cpu a donf (100%) un avec le demon Abeille et un avec AbeilleMQTTCmd.
A suivre.

**Comment by KiwiHC16** [comment]
Je viens de donner un peu d air pour les deux dans le master.
Mais je ne peux tester encore car la correction issue #705 n'est pas finie.

**Comment by KiwiHC16** [comment]
Les deux cpus sont à 1% maintenant.
