### ISSUE TITLE
MessageQueue: Could not send Msg  payload: {Version,getNetworkStatus, ..] vers 123

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#704]
[2019-05-30 10:58:03][DEBUG] : Envoi du message topic: TempoCmdAbeille/Ruche/getVersion&time=1559206703 payload: Version vers 123
[2019-05-30 10:58:03][DEBUG] : Could not send Msg: {"message":{"topic":"TempoCmdAbeille\/Ruche\/getVersion&time=1559206703","payload":"Version"}} on queue: 123
[2019-05-30 10:58:03][DEBUG] : Envoi du message topic: TempoCmdAbeille/Ruche/getNetworkStatus&time=1559206707 payload: getNetworkStatus vers 123
[2019-05-30 10:58:03][DEBUG] : Could not send Msg: {"message":{"topic":"TempoCmdAbeille\/Ruche\/getNetworkStatus&time=1559206707","payload":"getNetworkStatus"}} on queue: 123

**Comment by KiwiHC16** [comment]
Quand tu as ca, peux tu me donner le resultat de la commande:
ipcs

**Comment by KiwiHC16** [comment]
Est ce que tu as toujours ce souci apres les deux corrections poussées sur le master ?

**Comment by edgd1er** [comment]
je pense que le plugin via la class Abeille interroge la Ruche alors que les demons ne sont pas lancés.
comment reproduire:
Ajoute ce code dans dependancy_info, et les demons ne vont pas se lancer. qq temps apres, tu auras l'erreur:
```
 $cmd = "dpkg -l socat2";
            exec($cmd, $output_dpkg, $return_var);
            if ($output_dpkg[0] == "") {
                log::add( 'Abeille', 'warning', 'Le package socat est nécéssaire pour l\'utilisation de la zigate Wifi.' );
                $return['state'] = 'nok'; //Il manque Socat, relancer l\'installation';
                $return['launchable'] = 'nok';
                $return['launchable_message'] = __('Veuillez (ré-)installer les dépendances', __FILE__);
            }
```

Voici le resultat de la commande.

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages    
0x0000007b 0          www-data   666        16352        112         
0x00000079 32769      www-data   666        0            0           
0x000000dd 65538      www-data   666        0            0           
0x000001a5 98307      www-data   666        0            0           
0x0000026d 131076     www-data   666        0            0           
0x00000336 163845     www-data   666        0            0           
0x000000df 196614     www-data   666        0            0           
0x000000e1 229383     www-data   666        0            0           
0x00000143 262152     www-data   666        0            0           
0x00000141 294921     www-data   666        0            0           
0x0000020b 327690     www-data   666        0            0           
0x0000026f 360459     www-data   666        0            0           
0x000002d3 393228     www-data   666        0            0           
0x0000007c 425997     www-data   666        0            0           

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status      

------ Semaphore Arrays --------
key        semid      owner      perms      nsems

**Comment by KiwiHC16** [comment]
112 messages dans la queue 123 (0x7b) veut dire que les messages venant de Abeille Demon envoyés à AbeilleMQTTCmd ne sont pas traités. Probablement le proces AbeilleMQTTCmd ne fonctionne pas correctement.

**Comment by edgd1er** [comment]
oui, c’était bien le cas puisque les demons étaient arrêtés. La classes Abeille empile les messages meme si rien n'est la pour dépiler ? C'est a dire que les queues de traitement sont crées dans les démons. pas de démons, pas de queue, pas de message envoyés.
Soit la classe Abeille vérifie l'existence des queues avant d"envoyer, soit elle crée elle meme les queues.

D'ailleurs sais tu quelle portée ont ces queues de messages, application (Abeille), site web ( jeedom), serveur (apache) ? C'est a dire, est ce que d'autres application pourraient utilise ces infos ? Est ce un modele producteur-consommateur ?

Je demande parce qu'a un moment j'ai envisagé de récupérer les messages mosquitto pour les coller dans un ELK pour avoir des graphiques plus paramétrables et plus sympa. c'etait faisable sans modifier ton code, puisqu'il suffisait de s'abonner au flux Abeille. Si les messages sont consommés, ce n'est plus possibles sauf a mettre des bouts en plus dans ton code.

**Comment by KiwiHC16** [comment]
Je ne connais pas ELK.
Les queues sont des bons vieux message passing d'unix (avec une surcouche pour php). 
Un émetteur , un consommateur (FIFO).
J'ai gardé le format des message MQTT pour ne pas tout refaire.
Mais si un client vient lire les messages, il les consomme.
Dans ton cas il faut que tu ajoutes des queues dédiées avec le code associé.
Le process ouvre la queue et lit si quelque chose de present
Le process ouvre la queue et push un message
Il n'y a pas de synchro entre message
Si personne ne vient lire la queue elle se remplie
Lecture ou ecriture ne sont pas bloquants.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Est ce toujours un soucis ou peut on clore ce sujet ?

**Comment by KiwiHC16** [comment]
Pas de retour, je clos.
