### ISSUE TITLE
Lancement dépendance semble ko [specific Docker]

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#706]
D'apres ce que j'ai pu voir, maintenant les dependances sont lancés en retour de fonction.

Par exemple dans zwave on a:
```
   /**
     * Install dependancies.
     *
     * @return array Shell script command return.
     */
    public static function dependancy_install()
    {
        log::remove(__CLASS__ . '_update');
        return [
            'script' => dirname(__FILE__) . '/../../resources/install_#stype#.sh ' . jeedom::getTmpFolder('zigate') . '/dependance',
            'log' => log::getPathToLog(__CLASS__ . '_update')
        ];
    }
```

dans Abeille, on a qq chose de similaire:
```
 $result = array( 'script' => dirname(__FILE__).'/../../resources/install.sh '.jeedom::getTmpFolder( 'Abeille' ).'/dependance', 'log' => log::getPathToLog(__CLASS__.'_update'));
...
return $result;
```
cependant, je ne vois pas l'install.sh être lancé. il prend facilement 1 minutes sur RPI et un ps -ef | grep install.sh devrait me permettre de le voir.

Que constates tu ?

**Comment by edgd1er** [comment]
la fonction generique d'install du plgin teste la presence de la commande AT et l'utilise.
le problème vient du fait que lors de la mise en conteneur, les demons systemes sont executes via le supervisor. le demon at ne l'était pas. Jeedom soumet l'execution du script au démon qui ne tourne pas. Rien ne se passe et aucun message d'erreur n'apparait.....

Solution:  en desinstallant ( apt remove at), la fonction générique fait autrement et l'installation est lancée.

Je met l'info, comme tu aides beaucoup sur le forum, cela te donneras une piste en cas de non installation de dépendances.... ;)

**Comment by KiwiHC16** [comment]
Je ne comprends pas tout mais il est tard ...

**Comment by edgd1er** [comment]
la version courte, c'est du au fonctionnement docker, le démon atd ne s’exécutait pas et donc ne traitait pas les jobs soumis via la commande "at". ( si jeedom trouve la commande at, il execute les bash via cette commande.

le conteneur que j'utilise démarre les démons (apache, cron ) via un superviseur ( supervisor ). atd n'est pas géré par supervisor.....

**Comment by KiwiHC16** [comment]
Ok clair.
Interessant car mes dockers sur RPI ne démarrent pas atd.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev
