### ISSUE TITLE
CPU 100% apres Network graph refresh cache

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#708]
Apres avoir cliqué sur le lien refresh cache, l'appel a la fonction updateZigBeeJsonCache() a lancé l'analyse du réseau, j'ai du cliqué plusieurs fois dessus pour avoir un résultat.

Il a du rester qq chose en mémoire car le process php AbeilleMQTTCmd est monté a 100%, 1 heure après, voyant que ça ne redescendait pas, j'ai redémarré les demons. la température redescend doucement. Pratique le RPI pour voir rapidement quand un process s'accapare le cpu. :)

www-data  1718    10 98 17:50 ?        R    138:22  \_ /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmd.php /dev/ttyUSB0 127.0.0.1 1883 jeedom jeedom 0 debug

![image](https://user-images.githubusercontent.com/3601462/58654538-6ba5ea00-8318-11e9-9699-b4249a801615.png)

**Comment by KiwiHC16** [comment]
As tu fais ca avant ou apres les dernières modifications du master car je viens de le faire plusieurs fois et aucun soucis.

**Comment by edgd1er** [comment]
C'était apres les dernieres modifications du master. pas de pont pour moi aujourd'hui, je vais voir pour tester ce soir ou demain :) Peut etre un pb lié à docker comme avec AT

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Peux tu reproduire ce probleme pour comprendre le soucis ou on clos le cas ?
