### ISSUE TITLE
Problème avec les interrupteurs/prises netatmo legrand

### ISSUE THREAD

**Issue by ghost** [KiwiHC16/Abeille#709]
Bonjour
J'ai plusieurs soucis. J'intègre mes prises et interrupteurs Legrand. Le réseau se constitue bien et d'un seul coup ils disparaissent du réseau alors qu'ils sont toujours présents dans le plugin et dans la partie Santé (et elle est bonne)

**Comment by KiwiHC16** [comment]
Les équipements LeGrand n'ont pas fait parti des integrations jusqu'a ce jour. Des tentatives sans aller jusqu'au bout donc je ne peux pas trop t'aider pour l'instant. Il faudrait que je reprenne le sujet.
Peux tu me donner les references des equipements Legrand que tu utilises?

**Comment by ghost** [comment]
Ce sont les interrupteurs et prises dooxie legrand by netatmo

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Les interrupteurs sont ils sur le 220V ou sur piles ?

**Comment by ghost** [comment]
Ce sont des interrupteurs filaires.

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Je n'ai pas l'interrupteur.
Peux tu me donner un lien pour en commander un et j('utiliserai la cagnotte.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by ghost** [comment]
https://www.google.com/shopping/product/10587166404442331951?q=legrand+dooxie+netatmo&safe=active&sa=X&biw=393&bih=768&tbs=vw:l,ss:44&prmd=sinv&prds=epd:10628193916821540017,paur:ClkAsKraX6p_bZwWTYRGCl8w72EKfvlDQMdvKVHiqrFL4HActukBmbIyGqVT5wloWlQ2xSwgczAbH7lis_9UqLzKdztaYrRtcU_4a7faTRlF4vCOqkswPjWIkhIZAFPVH71Bwblx8Kk-8Az0d8jMz9SwDlPN9w,cdl:1,prmr:1,cs:1&ved=0ahUKEwjpvaL7-sXiAhWK_qQKHRnzBXoQgTYI6gY

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Est ce ce pack que tu as ?
Je demande car la prise est dans le meme moitié (plastique) que la GW Legrand.

**Comment by ghost** [comment]
J'avais initialement ce pack mais je n'utilise pas la gateway car avec la
zigate il n'y en a pas besoin. J'utilise ce type de prise :

https://www.mon-habitat-electrique.fr/p/2315-prise-de-courant-connectee-16a-dooxie-with-netatmo-blanc-600391-legrand-3414971044104.html?gclid=Cj0KCQjwocPnBRDFARIsAJJcf95JsixkDrDVebTn11yhChF7fTsu1X2Rb_HpYm71rtrOVppLWxadSMgaAtipEALw_wcB

Cordialement.

**Comment by KiwiHC16** [comment]
Je viens d'en dommander une avec la cagnotte. A suivre.

**Comment by KiwiHC16** [comment]
Prise Murale 220V Dooxie Netatmo avec Neutre fonctionne maintenaant avec la remontée de puissance (Dans master).
Je passe au module encastrable.

**Comment by KiwiHC16** [comment]
Je clos ce sujet et je vais faire une issue par produit Legrand.
