### ISSUE TITLE
Erreur sur le fichier level.json

### ISSUE THREAD

**Issue by ghost** [KiwiHC16/Abeille#710]
Bonjour
Il existe un fichier Level.json mais le plugin cherche un fichier level.json (avec un l minuscule)

**Comment by KiwiHC16** [comment]
Je ne trouve aucune reference a level.son avec l minuscule. Ou as tu vu cette info ?

**Comment by ghost** [comment]
Désolé c’est level.json

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Erreur de frappe de mon cote, c est bien level.json 
Je ne trouve aucune reference dans le code.
Ou as tu cette info ?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Sans info de ta part, je ne peux avancer sur le sujet.

**Comment by ghost** [comment]
Je sais mais j'ai désinstallé le plugin donc je ne peux pas reproduire

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Ok alors je clos le sujet.
