### ISSUE TITLE
Nom du bouton Xiaomi Aqara Wireless Switch

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#711]
Résumé: Le Xiaomi Aqara Wireless Switch n'est pas reconnu par Abeille pour un défaut de nom.
Page 131 et 132 du forum Jeedom

Le bouton s'annonce : ->lumi.sensor_switch.aq3<-[/code]
Sa réponse quand on lui demande son nom : ->lumi.sensor_swit<-
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3240892/AbeilleParser.txt)

Tu avais émis l'idée de faire un verrue dans Abeille et l'intégrer dans le master.

**Comment by KiwiHC16** [comment]
Ok ca me revient.

**Comment by KiwiHC16** [comment]
Fait dans le master
https://github.com/KiwiHC16/Abeille/blob/master/core/class/Abeille.class.php#L1206
