### ISSUE TITLE
Application des modèles

### ISSUE THREAD

**Issue by Asyrah** [KiwiHC16/Abeille#713]
L'application des nouveaux modèles du master entraine des modifications sur les équipements Xiaomi Door Sensor Aqara 2 qui les rendent inutilisable.

> 
[2019-06-02 19:17:35][DEBUG] : L objet: Abeille/5d30 existe mais pas la commande: 0006-01-0000

**Comment by Asyrah** [comment]
Commandes OK (sans application des nouveaux modèles)
![Commandes_ok](https://user-images.githubusercontent.com/48121420/58765820-2e8b6300-8577-11e9-8128-e448ac0aaa94.PNG)

Commande NOK (après application des nouveaux modèles)
![bug_xiaomi](https://user-images.githubusercontent.com/48121420/58765831-44008d00-8577-11e9-88ec-d73fb1789fac.PNG)

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille#cagnotte-pour-acheter-des-équipments-pour-supporter-le-dev

**Comment by KiwiHC16** [comment]
Es tu avec le code master ?

**Comment by Asyrah** [comment]
Oui, je suis en master depuis plusieurs mois désormais pour t'aider dans tes tests d'intégration :)

Problème identifié sur 2 versions différentes:
- Celle sans Mosquitto (master 8225f41d9cd4645e8a8a76deaeff88f237a3ba9c )
- Celle avec Mosquitto (master d70b6d7259787063a1d56f1585073f973d79b173)

Je ne pense pas que le problème soit lié avec la version master mais plus par un copié-coller ou une mauvaise merge des fichiers dans les fichiers modèles.

**Comment by Asyrah** [comment]
J'ai refais le test sur le dernier master c46eff757021099173b2872f5b7f0188a11f36f0. Ma plateforme est de nouveau en vrac (module xiaomi). Voici mes résultats:
[maj_modele.zip](https://github.com/KiwiHC16/Abeille/files/3265216/maj_modele.zip)

Modules impactés par la mise à jour des modèles sur ma plateforme : Xiaomi aqara door sensor 2, Xiaomi aqara Presence 2, Xiaomi interrupteur mural double.

Exemples de commandes qui s'envoi en l'air une fois la mise à jour appliquée:
- (4880) 0000-01-0005 => 0000-#EP#-0005
- (4881) 0006-01-0000 => 0006-#EP#-0000

J'ai trouvé 5 occurances de #EP# dans le fichier Abeille_updateConfig.txt, est-ce normal de les avoir ?

> Cmd Name: nom
> ---------> parameter different, will be updated 	'topic': '0000-01-0005' -> '0000-#EP#-0005'

> Cmd Name: etat
> ---------> parameter different, will be updated 	'topic': '0006-01-0000' -> '0006-#EP#-0000'

> Cmd Name: online
>  ---------> parameter different, will be updated 	'mainEP': '01' -> '#EP#'

**Comment by KiwiHC16** [comment]
Comme dit dans le forum je vais enlever ces boutons car ils risquent de poser plus de soucis qu'autre chose. Je préfère fournir modele et code en meme temps dans des versions stables. Le plugin ne devrait pas avoir d'évolution critique comme ca pu etre le cas au debut donc ce besoin disparait.

**Comment by KiwiHC16** [comment]
Je clos ce point car j'ai enlevé ces boutons d'application de template.
