### ISSUE TITLE
System skybone54 pb dependance (Jeedom smart)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#715]

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille/wiki

**Comment by KiwiHC16** [comment]
Que donne la commande suivante en ssh : 
```
dpkg -l socat
```

**Comment by skybone54** [comment]
dpkg-query: no packages found matching socat

**Comment by skybone54** [comment]
sudo apt-get install socat

Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 vim : Depends: vim-common (= 2:7.4.488-7+deb8u3) but 2:7.4.488-7+deb8u2 is to be installed
 vim-tiny : Depends: vim-common (= 2:7.4.488-7+deb8u3) but 2:7.4.488-7+deb8u2 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by KiwiHC16** [comment]
Visiblement tu as un probleme d installation de package. 
As tu essayé la proposition sur le forum ?
Sinon essayes la commande 
apt-get -f install socat 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skybone54** [comment]
Rien ne fonctionne. Les dépôts jessie n'étant plus dispo.
Apparemment il faudrait que je fasse la migration de ma jeedom smart en stretch

https://www.jeedom.com/forum/viewtopic.php?f=57&t=44870&hilit=depot+jessie

Je tente ça dès que possible

**Comment by skybone54** [comment]
C'est tout bon, ça fonctionne après recovery + restauration backup
https://jeedom.github.io/documentation/howto/fr_FR/recovery_mode_jeedom_smart

**Comment by KiwiHC16** [comment]
Super, alors je clos le sujet.
