### ISSUE TITLE
Erreur installation: apt update index failed

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#716]
https://github.com/KiwiHC16/Abeille/blob/e6f6060ae86dda94ddf3a88517b791904368aa1a/resources/install_apt.sh#L71

Lors du update certains depots pour jessie du moins donnent l'erreur, du coup l 'install de socat ne se fait pas et le plugin reste en défaut, alors que l'install est possible.

Il est possible de ne plus tester l'absence d'erreur de l'apt update et de voir par la suite si le paquet socat s'installe tout de même...

Je me demande si les problèmes récents de dépendances ne viennent pas de la, avec des version veillissantes de debian. (debian-jessie)

```
  W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find
 expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

  E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by KiwiHC16** [comment]
Install socat je propose de l enlever du script d install car ce n est que pour la version wifi. Et mettre un bouton d install spécifique comme pour la pizigate. 
Je ferai ça dans les jours à venir.

**Comment by KiwiHC16** [comment]
Je propose aussi de ne pas faire de apt-update et apt-get upgrade car le moins le plug in touche au system le mien c est. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
