### ISSUE TITLE
Move socat install from dépendance and put it manual.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#718]

**Comment by edgd1er** [comment]
fait dans la PR #717 . je pense qu'il y a un pb dans la PR, ne l'intègre pas tout de suite :(

Edit: en fait ce sont des problèmes avec le fichiers de docs. Aurait tu des CR/LF qui trainent dans le coin ? a chaque pull, ces fichiers sont modifiés automatiquement et je me retrouve bloqué.

error: Your local changes to the following files would be overwritten by merge:
	docSphinx/build/doctrees/Changelog.doctree
	docSphinx/build/html/changelog.html
	docSphinx/build/html/help.html
Please commit your changes or stash them before you merge.
Aborting

La solution pour m'en sortir est un reset HARD depuis ton dépot, mais ce n'est pas terrible comme solution.

**Comment by KiwiHC16** [comment]
J'ai viré la doc de ce repo, c est dans un repo specifique maintenant. Tu ne devrais plus avoir ce soucis j'espère.
J'ai rebase ta proposition de PR sans l avoir testée. 

Tiens moi au courant si il y a un soucis.

Je la testerai des que je trouve 5 minutes.

**Comment by KiwiHC16** [comment]
Le bouton "Cache" de la categorie ZiGate Wifi cache aussi la Categorie PiZiGate.

Il doit y avoir un probleme de positionnement des div ou des noms associés à la zone.

**Comment by edgd1er** [comment]
Ok, je regarderais, peut etre pas tt de suite, j ai un pb  d ecran avec mon pc. :( peut etre une correction en ligne depuis le boulot...

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://github.com/KiwiHC16/Abeille/wiki

**Comment by KiwiHC16** [comment]
Tout semble ok maintenant. Je clos. Merci...
