### ISSUE TITLE
Systeme  romainv 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#727]
je me demande si c'est pas la box qui chauffe
je vais la déplacer.
j'ai pas eut le temps d'analyser les logs.
mais la ruche a planté 2 fois le soir ce weekend.

en jeedom 3.3.26
et 
Linux jeedom 3.14.79-94 #1 SMP PREEMPT Mon Nov 21 17:13:27 BRST 2016 aarch64 GNU/Linux [9.4]

**Comment by romainv62** [comment]
pour complèter les infos.

j'ai la ruche passe en timeout .
sur une box jeedom smart.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/index.html#cagnotte

**Comment by KiwiHC16** [comment]
Est ce une ZiGate USB ?
Est elle connectée directement sur le port USB de la smart ? 
sur un Hub USB Externe ? 
Est ce le module TTL-USB d'origine ?

**Comment by romainv62** [comment]
ZiGate USB-TTL commandé sur zigate.fr
connecté directement sur un des ports USB de la box jeedom smart.

**Comment by KiwiHC16** [comment]
Ne serais tu pas dans ce cas:
```
Bonjour,

Il y a quelques temps, je rencontrais des soucis de timeout sur l'ensemble de mes équipements de façon aléatoire (1x par jour des fois moins, des fois plus).
Depuis 1 semaine (chaleur?), le systeme ne tenait pas plus d'2h avant de se mettre en timeout.
J'ai donc changé le convertisseur usb-ttl de la zigate (j'avais la première version de la zigate, module bleu à l'intérieur) par ce modèle :
https://www.amazon.fr/gp/product/B00LOD ... UTF8&psc=1
Il est pin to pin donc rien à souder ni cable à rajouter.

Depuis plus de problème.
Voilà, si ça peut aider...
```

cf forum https://www.jeedom.com/forum/viewtopic.php?p=743606&sid=b73757efe5ce0b633055d10f9e8286dd#p743606

**Comment by KiwiHC16** [comment]
Du nouveau de ton côté ?

**Comment by romainv62** [comment]
pas de plantage depuis 1 semaine...
il y a 3j je l'ai déplacé pour être moins en contact avec ma box internet.

la box est dans mon cellier, pas de différence de température reelement, temperature monte maxi a 21°/22°, et limite il fait plus chaud maintenant qu'il y a 8j.

**Comment by KiwiHC16** [comment]
Je te propose de clore le sujet, si ca revient on rouvre le sujet.
