### ISSUE TITLE
No more doc?

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#729]
Hello,

  I failed to get acces to local doc on my jeedom nor on the internet  by following buttons in the configuration panel of the plugin.

Did I missed something?

Best regards.

**Comment by smulle48** [comment]
Same here. All docs are gone

**Comment by KiwiHC16** [comment]
Oui c est normal.
La doc est maintenant a l adresse: https://abeilledocsphinx.readthedocs.io/fr/latest/
Je vais changer les infos dans le plugin.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by handfreezer** [comment]
OK, merci.

**Comment by handfreezer** [comment]
désolé, en fait, je te laisse fermer le ticket quand tu veux, mais pour moi c'est bon.

**Comment by KiwiHC16** [comment]
Ok je ferme alors. Pas de soucis pour moi si tu fermes.
