### ISSUE TITLE
Dashboard corrupted

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#730]
Hello,

    My dahsboard seems corrupted by the Abeille plugin, I got this error:
"200 : SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

    If I unactivate the plugin, the message disappear.

Any idea?

Best regards.

**Comment by KiwiHC16** [comment]
You probably have a device template which is corrupted.
They all are in folder plugin/Abeille/core/config/devices
The question is which one is causing this issue.
Any specific action you did before having this behavior ?

**Comment by handfreezer** [comment]
I re-synced few xiaomi devices lost.

**Comment by KiwiHC16** [comment]
How do you re-sync ? what process do you follow ?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by KiwiHC16** [comment]
I which log do you have this message ?

**Comment by handfreezer** [comment]
About resync : what I call a resync is : when a xiaomi sensor do not send data during 1 or 2 days, I activate inclusion mode of the zigate and I do a long press on the "lost" sensor.

**Comment by handfreezer** [comment]
About the message, it is not in a log, but on the main screen:

**Comment by KiwiHC16** [comment]
Ok i will do the same action to see if I can get the same error message.

**Comment by KiwiHC16** [comment]
I just include a door sensor V1 from Xiaomi without any issue.
Do you still have this issue ?

**Comment by handfreezer** [comment]
I have motion sensors, button and dorr detector that corrupt dashboard, but few others of same type don't...

**Comment by handfreezer** [comment]
also, I noticed that from dashboard was corrupted by few devices, all devices lost the configuration of which field to display or not.

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by KiwiHC16** [comment]
Je pense que je viens de tomber sur un probleme similaire. C'est quand j'affiche la commande SW d'un équipement.

![Capture d’écran 2019-07-06 à 09 32 29](https://user-images.githubusercontent.com/8549674/60753353-2341b200-9fd1-11e9-88a4-d09fcd0a2d0c.png)

Si je ne l affiche pas alors pas de soucis.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-07-06 à 09 38 09](https://user-images.githubusercontent.com/8549674/60753394-ceeb0200-9fd1-11e9-9174-8388aee94417.png)

**Comment by KiwiHC16** [comment]
Visiblement la valeur de la commande est pas terrible, il faudrait que j'ajoute un filtrage des valeur qui remontent. Ici c 'est pour la prise Legrnad 220V avec Neutre.

**Comment by handfreezer** [comment]
alors c'est une bonne piste, car effectivement, pour une raison un peu inconnue, tout mes équipement "Abeille" ont vu leur conf "Afficher" de Commande & Info" remis à zero avec tout actif pour tous les périphériques...je fais un essai.

**Comment by handfreezer** [comment]
note que j'ai ajouté il y a pas longtemps une prise IKEA, mais ce n'est pas arrivé pile poil au même moment...

**Comment by handfreezer** [comment]
Et juste pour savoir, où as-tu cette écran : valeur/date de collecte?

**Comment by handfreezer** [comment]
J'avais un bouton lumi.sensor_switch.aq2 , il a fallu que je désactive l'affichage de la commande Specific 0000-01-ff01 pour que cela rentre dans l'ordre, j'essaierais les autres plus tard.

**Comment by KiwiHC16** [comment]
La commande "0000-01-ff01" est source d'ennuies. Je l'avais mise pour voir les infos mais Jeedom n'aime pas le binaire qu'elle remonte. Normalement avec le dernier soft cette info ne remonte plus pour ne pas provoquer ces soucis.

**Comment by handfreezer** [comment]
est-ce que cela veut dire que je dois supprimer la commande partout, ou bien parles-tu du dernier update du plugin Abeille sur master?

**Comment by KiwiHC16** [comment]
Le master n'envoie plus les valeurs pour ne pas créer des problemes d'affichage, et avec home bridge.
Le mieux est de les supprimer dans tes équipements si tu as des soucis.

**Comment by handfreezer** [comment]
OK, je vais faire ça, mais pas tout de suite. je te tiens au courant.
Merci pour ton retour.
