### ISSUE TITLE
pl2303 failed

### ISSUE THREAD

**Issue by handfreezer** [KiwiHC16/Abeille#731]
Bonjour,

    J'ai un message de plantage du driver pl2303 depuis 2 semaines, et cela fais plus d'un an que fonctionne mon dongle.  
   Du coup, comment puis je diagnostiquer si c'est un bug du plugin ou un pbm driver/hardware?

Cordialement,

**Comment by KiwiHC16** [comment]
Je ne peux pas trop t'aider la dessus mais as tu vu le dernier message sur le forum, car le probleme vient soit du Hardware soit du driver, mais pas du plugin.

```
Bonjour,

Il y a quelques temps, je rencontrais des soucis de timeout sur l'ensemble de mes équipements de façon aléatoire (1x par jour des fois moins, des fois plus).
Depuis 1 semaine (chaleur?), le systeme ne tenait pas plus d'2h avant de se mettre en timeout.
J'ai donc changé le convertisseur usb-ttl de la zigate (j'avais la première version de la zigate, module bleu à l'intérieur) par ce modèle :
https://www.amazon.fr/gp/product/B00LOD ... UTF8&psc=1
Il est pin to pin donc rien à souder ni cable à rajouter.

Depuis plus de problème.
Voilà, si ça peut aider...
```

https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&hilit=abeille&start=3120

Perso je ne recommande pas le pl2303 mais plutot le FTDI...

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by handfreezer** [comment]
ok, merci pour l'info, je vais donner une chance à cette solution.

**Comment by handfreezer** [comment]
Pour info, j'ai rebrancher le même zigate mais en direct sur la carte mère plustot que de passer par un hub usb 3 (qui était présent pendant plus d'un an...) et depuis c'est nickel.
