### ISSUE TITLE
Systeme Mikado

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#734]

**Comment by KiwiHC16** [comment]
Je continue de rager sur la portée du Zibee par rapport au Zwave.
Le module Abeille me dit un LQI de 9 alors que je suis à 3 mètres de mon ampoules, sans mur ni micro onde. Le seul truc, c'est le rezo Hue via le pont qui est effectivement sur le même canal. D'ailleurs (voir post précédent), je les vois dans le rezo sans avoir pour autant les objets pilotables (ampoules, capteurs...) puisque sur le pont Hue. J'ai aussi du wifi 2,4. Tout cela peut mettre du bordel sur la qualité ?
J'ai vu aussi que certains change le USB TTL de la zigate. Je n'ai pas tout compris. ils livrent des trucs de mauvaises qualités ? la mienne a deux mois et j'avais direct le firmware 3.0F. Enfin y'a t'il moyen de mettre une antenne ?
Je comptais me servir des ampoules comme relais, et j'ai des prises OSRAM en cours d'acheminement pour améliorer le maillage. Mais si à 3 mètres j'ai 9 de LQI, c'est à la source qu'il y'a un problème. Bon il y a un abajour mais quand même
Merci de vos éclairages, je débute en Zigbee.

**Comment by KiwiHC16** [comment]
Sur quel canal est ta ZiGate ?
Ampoule - ZiGate = 3M => Quelle type d'ampoule ? OSRAM ?
Peux tu partager une capture d'écran du reseau avec le valeur LQI ?

**Comment by mikado933** [comment]
Hello Kiwi,
Tout d'abord un grand merci pour ta dispo et ta démarche.
Je reviens un peu sur le zwave et mon background. Le rezo Zwave est vraiment super stable, et j'ai un bon maillage avec une 20taine de modules. C'est vrai que ce n'est pas open, mais même si je suis informaticien mais pas system, je n'y connais rien en elec et pas le temps de m'y mettre :) . Mon Hue est lui aussi super stable. Le tout dans une VM sur mon Syno vitaminé en mémoire :)
Suis venu au zigbee par curiosité, et puis il y a des modules moins cher et complémentaire au Zwave. 
Bon, après avoir divergé, revenons à mon soucis, et encore un grand merci.

La Zigate est sur le canal 11, mais voici un peu plus d'infos :
Last	2019-07-03 15:01:27 
Last Stamps	1562158887 
SW	0003
SDK	030F
Network Status	Network already formed, not starting it again.
Short address	0000
PAN Id	82b7
Extended PAN Id	bb86cdd0d13551c8
IEEE address	00158d0001ed4702
Network Channel	11

Je n'avais pas fait attention, mais j'ai aussi dans les params sur le wifi : 192.168.4.1:9999
Alors que je n'ai pas l'extension wifi, et que le masque sous rezo ne correspond à rien. Je ne sais pas si cela gêne.
Suis sur mon tel donc la je en peux pas faire de sceens. Néanmoins voici des infos.
Mon ampoule est une OSRAMClassicA60Wclear-LIGHTIFY. J'affiche sur le Dashboard avec le widget les infos dont le LQI. il change tout le temps. Pour l'ampoule, il est passé à 3. Je suis en direct au pire à 4 mètres. J'ai un capteur Xiaomi à 1.5 mètre sans rien d'autres autour, son LQI est de 12 mais je l'ai déjà vu à 40 qqchose. Un autre capteur Xiaomi un peu plus loin que l'ampoule, et son LQI est de 6. Si tu veux le screen, dis moi. Si j'ai oublié un truc, n'hésites pas. Et encore encore Merci de ton aide.

**Comment by mikado933** [comment]
ah oui en complément, je vois que tu as 70 modules. comme je suis newbie mais curieux de mettre pleins de choses, qu'as tu donc comme type de module ? cela pourrait m'apporter des idées :)
Merci à toi :)

**Comment by KiwiHC16** [comment]
Mon ampoule OSRAM me donne des LQI autour d'elle au environ de 80 pour les équipements dans la même pièce. C'est une CLA60RGBWOSRAM.
Si tu as choisi ttyUSB alors les info Wifi ne sont pas utilisés. Donc pas de soucis.

Partages des captures d'ecrans pour etre sure que l on parle de la meme chose...

**Comment by mikado933** [comment]
Hello,

Voici la capture d'écran. L'ampoule c'est l'adresse 13bc. Les deux autres sont des capteurs Xiaomi température/humidité.
Merci

![Capture d’écran 2019-07-03 à 21 54 45](https://user-images.githubusercontent.com/26626110/60621227-6804f780-9ddd-11e9-8fbc-ad289de42e26.png)

**Comment by KiwiHC16** [comment]
Salut, 
Je dirai que tu as un probleme de reception car les valeurs remontées par la ZiGate sont toutes très très basses alors que les valeurs données par l ampoule sont bonnes. 
Si elle est neuve, demande à Akila ce qu'il peut faire pour toi.

**Comment by mikado933** [comment]
Salut,
Merci pour ton retour. Akila, c'est le contact chez Zigate ?

**Comment by KiwiHC16** [comment]
Oui Akila est la personne qui fait la zigate (zigate.fr).

**Comment by KiwiHC16** [comment]
Je clos, rouvres si tu as besoin.
