### ISSUE TITLE
Add command 0x0111 (Heiman Smoke Sensor ?)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#736]
Add cmd 0x0111 E_SL_MSG_WRITE_ATTRIBUTE_REQUEST_IAS_WD to send command to IAS_WD device 

https://zigate.fr/documentation/commandes-zigate/

It's needed for IAS Siren, but what about IAS WD like Heiman smoke sensor ?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by tcharp38** [comment]
Pourquoi un write attribute specific ? Le standard n'en a qu'un.
Reste peut etre juste à rendre "writeAttribute()" ou "writeAttribute0530()" encore + generique.

**Comment by tcharp38** [comment]
Plutot qu'ajouter le support de certains messages, il vaut mieux que ca vienne d'un réel besoin pour un équipement particulier.
Comme ca on a un vrai cas d étude.

Du coup je clos ce sujet.
