### ISSUE TITLE
Pas de remontée puissance & consommation Wall plug

### ISSUE THREAD

**Issue by lukebr91** [KiwiHC16/Abeille#74]
Résolu en passant en commentaire cette ligne : 
https://github.com/KiwiHC16/Abeille/blob/c6f0e5f76cb0d3fa4ba1da174e13ffe1e0ec92d9/resources/AbeilleDeamon/AbeilleParser.php#L488

même condition que la ligne 493

**Comment by KiwiHC16** [comment]
Ok je vais regarder.
Par contre je ne comprend pas le titre de l issue car dans le code il y a le commentaire "// Xiaomi Door Sensor".

Est ce que le sujet et la remontée des paramètres propriétaires Xiaomi dans le cas du door sensor ?

**Comment by lukebr91** [comment]
À cause du Elseif de la ligne que j'ai mentionné, le décryptage de la conso
sur le wall plug ne se fait pas car c'est au Elseif suivant (L493) avec les
mêmes conditions !? (Qui sont correctes)

**Comment by KiwiHC16** [comment]
Qu'elle version de firmware zigate utilises tu car j ai vu qu'@Akila a sortie une version 3.0c avec le commentaire suivant:
"Fix Get Xiaomi private data from cluster 0x0000 attributes 0xFF01 with specific manufacturer 0x115F"

Je suppose que c'est une correction que je lui avais proposé car des messages proprétaires Xiaomi ne passaient pas au travers de la GW qui les rejetait. Je vais passer en V3.0c et voir si ces paramètres remontent bien et si Abeille les gère. Je ne me souviens plus ou j'en était sur ce sujet.

**Comment by KiwiHC16** [comment]
Ok je comprends. 2 sujets différents. Je vais donc ouvrir un autre issue.

**Comment by lukebr91** [comment]
3.0c mais en 3.0b je n'avais pas non plus l'info qui remontait, je me suis
juste penché sur les log pour voir d'où ça pouvait venir.

"Le door sensor envoie un paquet proprietaire 0x115F qu il va fallair
traiter, ne suis pa sure de la longueur car je ne peux pas tester...."
Pour des requêtes venant du wall plug

Le 4 févr. 2018 4:25 PM, "Ben" <notifications@github.com> a écrit :

Ok je comprends. 2 sujets différents. Je vais donc ouvrir un autre issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KiwiHC16/Abeille/issues/74#issuecomment-362914604>, or mute
the thread

**Comment by KiwiHC16** [comment]
J'avais du faire un copy paste en attente de la modification zigate et du coup ton problème.

**Comment by KiwiHC16** [comment]
Ok, J'ai mis une dimension bidon en attendant d avoir la bonne. Quand je ferai le prochain push tu devrais avoir la modif et donc plus le probleme.

**Comment by KiwiHC16** [comment]
I pushed a correction so I close the topic

**Comment by lukebr91** [comment]
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/CmdToAbeille.php on line 247

Il manque quelques commentaires, le daemon ne se lance plus suite à la mise à jour.

**Comment by KiwiHC16** [comment]
Oui je viens de pousser des betises car j utilise un disk nfs depuis 2 machines et j ai eu des problemes de  conflit github.
Ca doit être bon maintenant. Je viens de faire un push.
