### ISSUE TITLE
J'installe une nouvelle Jeedom smart. Quand j'installe Abeille, la ruche ne se créé pas :

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#741]
[MySQL] Error code : 23000 (1452). Cannot add or update a child row: a foreign key constraint fails (`jeedom`.`eqLogic`, CONSTRAINT `fk_eqLogic_object1` FOREIGN KEY (`object_id`) REFERENCES `object` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) : INSERT INTO `eqLogic` SET `id` = :id, `name` = :name, `logicalId` = :logicalId, `generic_type` = :generic_type, `object_id` = :object_id, `eqType_name` = :eqType_name, `eqReal_id` = :eqReal_id, `isVisible` = :isVisible, `isEnable` = :isEnable, `configuration` = :configuration, `timeout` = :timeout, `category` = :category, `display` = :display, `order` = :order, `comment` = :comment, `tags` = :tags

**Comment by KiwiHC16** [comment]
Quelles sont les étapes suivies ?
Smart vierge, installation d'Abeille depuis le market, activation, demarrage du demon et tu as ce message ?

**Comment by sebfar9172** [comment]
Exactement ce que tu as décrit. Abeille est le seul plug-in que j'ai installé.

**Comment by KiwiHC16** [comment]
Ca c est pas cool. 
Si tu redémarres le démon est ce que tu as toujours ce problème ? Est ce que la ruche se crée ?

**Comment by sebfar9172** [comment]
Toujours et pas de ruche.

Cordialement.

Sébastien Faroux

**Comment by sebfar9172** [comment]
J’ai trouvé, il fallait que je créé un Objet pour que la ruche puisse se créer …

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Super
