### ISSUE TITLE
Refresh du status des equipements au redemarrage d'Abeille ?

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#742]
Bonjour
Est il possible qu'Abeille force un refresh du status des equipements connus à son redemarrage ?
Est ce techniquement possible d'ailleurs ?
Ca permettrait par ex d'avoir un etat rapide de la situation et eviter d'attendre un moment (j'ai noté que les capteurs Xiaomi prennent un bout de temps avant de reintegrer le reseau suite à coupure de courant).
Merci

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by KiwiHC16** [comment]
On peut forcer un refresh pour les équipements qui ne dorment pas (Ampoules,...), par contre pour ceux qui dorment c'est beaucoup plus compliqué (Sensor sur batterie).
Pour ceux qui ne dorment pas il y a dans Abeille plusieurs cron pour mettre à jour et  une partie des réponses est dans https://abeilledocsphinx.readthedocs.io/fr/latest/Cron.html mais il faudrait que je mette à jour.
On peu imaginer de ne pas attendre le prochain cron au demarrage et de lancer une collecte au démarrage du demon.
Pour ceux qui dorment il faut attendre qu'ils envoient leur infos. Xiaomi sensor les envoient toutes les heures. Et on ne peux pas facilement les forcer à aller plus vite. Dans tous les cas il faut attendre qu'ils se réveillent.
Un cas / besoin particulier ?

**Comment by tcharp38** [comment]
J'ai cru comprendre qu'au niveau ZigBee
- soit le device donne ses infos de maniere via au "report attribute" (config actuelle)
- soit il y avait aussi un cmde de "request" attribute.
Je n'ai pas encore testé mais cela ne forcerait il pas le sensor à reagir ? En me lisant je me dis que la reponse est dans la question si effectivement le device "dort" il doit rien n'ecouter.

Quant à mon cas, je cherche à comprendre les pbs de robustesse Xiaomi/Zigate sans obligation de "refaire une inclusion". Du coup le fait que le status valide soit parfois tres long à obtenir apres une coupure de courant n'aide pas.

Et merci pour cette reponse rapide

**Comment by KiwiHC16** [comment]
Effectivement tu as les deux: soit report, soit interrogation (s'il est éveillé).

Faire une inclusion est pour donner une adresse et la clef de cryptage à l'équipement. Donc pas besoin de faire un re-inclusion. S'il dort il faut le réveiller. Par exemple pour le sensor door xiaomi, un clic cours sur le coté le reveille et il remonte des infos. 

Mais si la coupure de courant est trop longue, le sensor se reveille et cherche à plusieurs reprises le reseau qui ne repond pas car routeur HS sans courant. A ce moment la plusieurs comportement suivants les fabriquant, par exemple mon observation est que les Xiaomi quittent le réseau. Dans cce cas apres remise du courant il faut faire une inclusion.

Il faut attendre au moins une heure apres la coupure (sans rien touché) pour avoir une idée de la situation.

**Comment by tcharp38** [comment]
Ok, C'est bien le cas "coupure trop longue" qui me chagrinne. Sur une installation avec beaucoup de capteurs, je me vois mal refaire le tour pour refaire une inclusion. Ca rend la solution Xiaomi pas viable pour une maison de campagne avec un reseau electrique moins fiable qu'en ville.

Ceci etant saurais tu me dire si il y a un lien avec le point "pending" cote Zigate et Xiaomi ?
On trouve ca sur son site dans la note du FW 3.0f

> La prochaine mission très importante pour moi va être de contourner le problème des objets Xiaomi sur pile. En effet, le fonctionnement de ces appareils ne gèrent pas correctement le « rejoin ». Sans rentrer trop dans les détails, quand on demande à l’objet de sortir du réseau et de re rentrer (ça fait partie de la norme), l’appareil Xiaomi sort mais ne veut pas revenir. Ce phénomène ne se produit pas juste après un appairage (quand il est bien réveillé) mais lorsqu’il vit depuis un moment. Il est donc difficile de contourner le problème sans avoir accès au code de l’objet.

**Comment by KiwiHC16** [comment]
C est le soucis.
La solution que j'ai, est de mettre la ZiGate sur batterie car c'est la liaison radio xiaomi - zigate qui est important. 
Deux solutions au moins:
- https://abeilledocsphinx.readthedocs.io/fr/latest/Wifi.html (C'est ce que j'utilise)
- ou tu mets une ZiGate Wifi sur une batterie de téléphone sur le port USB et la batterie sur le secteur. Ca fait un APS qui fait que la ZiGate est toujours on. Moi j'en est une sur une batterie: https://duckduckgo.com/?q=jockery&t=osx&iax=images&ia=images

**Comment by KiwiHC16** [comment]
Et si besoin absolue de routeyrs alors tu peux mettre un routeur Ikea sur une batterie jockery comme ca le reseau est plus dur aux pertes de courant.

**Comment by tcharp38** [comment]
D'accord. Merci beaucoup pour ces infos.
Une derniere question (j'espere). Qqn a t'il fait le test avec la passerelle officielle Xiaomi et est il necessaire aussi avec celle la de refaire une inclusion si elle venait à etre OFF plusieurs heures (jours ?) ?

**Comment by ffp17** [comment]
Bonjour,
Intéressant comme test, je vais le faire et je fais un retour ici.

**Comment by ffp17** [comment]
J'ai débranché la gateway Xiaomi pendant 2 heures.
Juste après être rebranchée, la gateway transmet les infos des détecteurs.
Par exemple, le bouton rond est actif 10 s après le retour de la gateway, même chose pour les détecteurs d'ouverture et de mouvement.

**Comment by KiwiHC16** [comment]
Pour moi d'apres mes souvenirs, 2 heures ne sont pas suffisant car l'équipement fait au moins 3 tentatives avant de quitter le réseau. Peux tu faire un test pendant 12 heures ?

Si ca fonctionne alors Xiaomi fait un truc particulier. Ou alors ils ont fait un correctif que tu auras sur ton équipement.

Si ca fonctionne, je brancherai mais GW et ferai un snif des échanges...

**Comment by ffp17** [comment]
Ok j'essaie de faire le test weekend.

**Comment by ffp17** [comment]
Voici le résultat du test :
- hub Xiaomi débranché pendant environ 13 heures
- Rebranché et attente 10 ou 15 secondes pour la connexion wifi
- détecteurs d'ouverture de porte opérationnels immédiatement (je n'ai que les anciens qui sont arrondis)
- boutons rond ok
- détecteurs de mouvement ok mais ils ont mis plus de temps à remonter (les 2 types, ancien et nouveau avec luminosité)

Le hub Xioami est connecté à Jeedom via le plugin Xiaomi Home.
Tout refonctionne parfaitement. Il doit y avoir un truc qui fait que la connexion est gardée.

**Comment by KiwiHC16** [comment]
Ok, je vais essayer de refaire les tests et sniffer. Peut être que cette fois je trouverai le trick. Il faut que je parvienne a avoir un reseau de test sans polution d'autre réseau...

**Comment by KiwiHC16** [comment]
Il y a deux sujets dans une issue:
- refresh at startup: je ne vais pas le faire.
- deconnection xiaomi, pour moi c est un bug xiaomi et je ne peux acceder au code, donc je ne peux rien faire.

Je clos pour essayer de me concentrer sur le sujet les plus "importants".
