### ISSUE TITLE
Stabilité du systeme sebfar

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#744]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=745502#p745502

**Comment by KiwiHC16** [comment]
J'ai une jeedom smart avec une clé zigate.
La ruche est tombé 2 fois hier.
Mais le plus souvent ce sont les mêmes équipements Xiaomi.
Ce matin j'avais aussi des équipements Legrand de tomber j'ai redémarré la box et j'ai redémarré le démon abeille et ils ont été retrouvés

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by sebfar9172** [comment]
voici des logs
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3364856/Abeille.txt)

**Comment by KiwiHC16** [comment]
"[2019-07-06 18:13:13][DEBUG] : (AbeilleLQI - mqqtPublishLQI) Msg sent: false"

Avec ce genre de message, rien ne peut fonctionner pour Abeille. En gros ca veut dire que les messages échangés entre les modules logiciels ne fonctionnent pas.

Il est possble de devoir faire un reboot pour corriger ce point.

Mais ca ne semble touché que la recuperation de info LQI donc le reste devrait fonctionner.

La queue impactée est "queueKeyLQIToCmd": c'est les messages envoyés pour interroger le réseau.
Ce qui est surprenant c'est que la queue "queueKeyAbeilleToCmd" fonctionne. Donc ce n'est pas un blocage de l'envoi des commandes vers la ZiGate.

**Comment by KiwiHC16** [comment]
Du nouveau ? Je clos ?

**Comment by sebfar9172** [comment]
Salut

Oui. Cela stabilise doucement.

Cordialement.

Sébastien Faroux

**Comment by KiwiHC16** [comment]
Ok alors je clos. Si besoin tiens moi au courant.
