### ISSUE TITLE
LeGrand Telecommande Depart Arrivée sur pile

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#749]
https://www.youtube.com/watch?v=est11G4mtk0

Proche Coordinator (1:05)
Deux boutons Appuis, Led Verte Telecmd, Led S'eteint, Led GW S'allume => Reseau ouvert (?)
Tous les routeurs passent en vert (1:27)

Prendre Télécommande et mettre la pile (1:31)
Appui Bouton Bas Telecommande, flash Led 6x, s'éteint 

Appui long sur bouton bas de la telecommande tout en tap tap micro module
Telecommande et Micro module clignotent en bleu (1:59) puis bleu fixe.
Micro module vert, Telecommande off => Association reussie

Fin des operation: Appui une fois centre telecommande Depart Arrivée (2:28), 3 flash verts et s'eteint. Les led vertes des routeurs s'éteingnent.

Telecommande Bouton Bas (coté led) allume les routeurs.
Telecommande Bouton Haut (coté opposé led) éteint les routeurs.

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by tuxtof** [comment]
bonjour @KiwiHC16 , est ce que ce module est censez fonctionner, car je vois des choses a son propos dans le code "core/config/devices/Remoteswitch/Remoteswitch.json"

merci d'avance

**Comment by KiwiHC16** [comment]
Non pas pour l'instant.
Investigations sur son fonctionnement.
Je crois qu'il n'est pas dans la liste zigate.fr

**Comment by KiwiHC16** [comment]
#243 des infos sur l inclusion.

**Comment by KiwiHC16** [comment]
Idem to #797.
