### ISSUE TITLE
Version 3.0c de la zigate

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#75]
Qu'elle version de firmware zigate utilises tu car j ai vu qu'@akila a sortie une version 3.0c avec le commentaire suivant:
"Fix Get Xiaomi private data from cluster 0x0000 attributes 0xFF01 with specific manufacturer 0x115F"

Je suppose que c'est une correction que je lui avais proposé car des messages proprétaires Xiaomi ne passaient pas au travers de la GW qui les rejetait. Je vais passer en V3.0c et voir si ces paramètres remontent bien et si Abeille les gère. Je ne me souviens plus ou j'en était sur ce sujet.

**Comment by edgd1er** [comment]
si la question est pr moi, 3.0b, mais je vais flasher en 3.0c ce soir ou demain.

**Comment by Marc--** [comment]
Je viens de tester en Zigate 3.0c, plugin Abeille mis à jour depuis le market (2018-01-26 09:30:15).

Pas de problème à signaler, mais je n'ai que des capteurs temp carré sous la main. Un test en particulier à faire ?

**Comment by KiwiHC16** [comment]
Je suis passé en 30D et aucun soucis. Il fuat que je vérifie les modifications apportées.

**Comment by KiwiHC16** [comment]
D'apres ce que je vois les groups mambership remontent les bonnes infos maintenant et le champ proprietaires xiaomi sont biens transmis par la zigate donc je clos ce sujet.
