### ISSUE TITLE
[Zigate USB-TTL] Pas reconnu par Nas Syno DS418Play ni sur Jeedom.

### ISSUE THREAD

**Issue by Balrogard** [KiwiHC16/Abeille#750]
Bonjour KiwiHC16,

Je te sollicite car je n'arrive pas à faire reconnaître ma Zigate USB-ttl quand je la branche sur Nas Synology DS418Play.
J'ai les LEDs rouge et bleu qui sont continuellement allumés lorsque je la branche à mon NAS ou sur mon PC. Je ne comprends pas.
Ci-dessous la Zigate, je ne pense pas l'avoir mal connectée.

![66284699_462308321213321_859474611501268992_n](https://user-images.githubusercontent.com/29062324/60987225-7903ba80-a341-11e9-94b6-7056775e08e8.jpg)

J'ai effectué la mise à jour de ma zigate depuis mon PC en suivant l'étape sur ce lien : https://zigate.fr/wiki/mise-a-jour-de-la-zigate/?fbclid=IwAR0OO5SzecA3VZZ0TEXjd4UcHU5XSc1gFbmYNOe2xGlXslcJ6k5y-39tZfs

Après rebranchement de ma zigate sur mon NAS j'ai effectué la commande "dmesg | tail" en ssh sur mon NAS.

```
[63071.848097] Got empty serial number. Generate serial number from product.
[63738.046788] usb 1-3: USB disconnect, device number 5
[64032.082167] usb 1-3: new full-speed USB device number 6 using xhci_hcd
[64032.224660] Got empty serial number. Generate serial number from product.
[64542.313268] init: nmbd main process (2891) killed by TERM signal
[64544.196922] NET: Unregistered protocol family 15
[64545.748320] NET: Registered protocol family 15
[65612.430863] usb 1-3: USB disconnect, device number 6
[66296.756287] usb 1-3: new full-speed USB device number 7 using xhci_hcd
[66296.902756] Got empty serial number. Generate serial number from product.
```

Je ne comprends pas ou est le problème.

**Comment by Balrogard** [comment]
J'ai un peu avancé sur mon problème.
Le NAS reconnait le device USB.

![Capture](https://user-images.githubusercontent.com/29062324/61004805-1cb39180-a367-11e9-8513-db25ebec6f3f.JPG)

Quand je fais un lsusb j'obtiens cela.

![Capture2](https://user-images.githubusercontent.com/29062324/61004813-20471880-a367-11e9-982f-d13c40f39349.JPG)

Par contre je ne retrouve pas de trace de prolific dans le dmesg. Rien qui pourrait me déterminer le numéro ttyUSBXX...

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by KiwiHC16** [comment]
Difficile pour moi de t'aider. Je ne connais Syno. De plus j'ai cru comprendre que des installations tournent avec docker.
Quel est l'OS du Syno ?
Est ce que les logs que tu partages ci dessus sont des logs du Syno (je veux dire pas une VM, ni docker) ?

**Comment by Balrogard** [comment]
Hello KiwiHC16.

La clé est bien reconnu sur un autre NAS (HP) Linux. Sur le Syno j'ai un  "[155641.534379] Got empty serial number. Generate serial number from product." lorsque je branche la zigate. Il faut que je réussise à attribuer un numéro de série à la Zigate. Il faut que je cherche comment le faire. 

Oui Jeedom est sur un docker. Les logs que je partagent proviennent des logs du Syno et non pas de VM ou Docker.

OS Syno : DSM 6.2.2-24922 Update 2 : Kernel Linux 4.4.59+

Si on en crois cette documentation, le DSM Synology embarque moins de kernel que les version Ubuntu/Debian etc...
https://hallard.me/how-to-install-kernel-modules-on-synology-ds1010/
Il faut limite recompiler ton propre kernel ...

**Comment by Balrogard** [comment]
Effectivement le serial Number est bizarre quand tu fait un usb-devices : 

```
T:  Bus=01 Lev=01 Prnt=01 Port=02 Cnt=01 Dev#=  5 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=067b ProdID=2303 Rev=03.00
S:  Manufacturer=Prolific Technology Inc.
S:  Product=USB-Serial Controller
S:  SerialNumber=ffffffc6ffffffa3ffffffcfffffffa3
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=ff(vend.) Sub=00 Prot=00 Driver=pl2303
```

Edit : J'ai trouvé la solution ! il manque les drivers usb pour PL2303 sur les Nas Synology. Il faut utiliser le .spk se trouvant sur ce site : http://www.jadahl.com/drivers_6.2/?arch=apollolake
Rebooter son NAS, replugger la zigate et vous devriez avoir ceci en tapant "dmesg"

```
[ 1210.511819] usb 1-1: new full-speed USB device number 7 using xhci_hcd
[ 1210.653392] Got empty serial number. Generate serial number from product.
[ 1210.661574] pl2303 1-1:1.0: pl2303 converter detected
[ 1210.668038] usb 1-1: pl2303 converter now attached to ttyUSB0
```

En espérant que ça aidera d'autres personnes.

**Comment by KiwiHC16** [comment]
Super nouvelle.
