### ISSUE TITLE
Telecommande INNR

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#753]
Some info in https://github.com/fairecasoimeme/ZiGate/issues/160

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by KiwiHC16** [comment]
Appairage Ok.

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware#version-31a

**Comment by KiwiHC16** [comment]
- Reste la partie monitoring batterie
- La partie Groupe Global si pas configure
- La partie Scene qui envoie un niveau au groupe global

**Comment by tcharp38** [comment]
Plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
