### ISSUE TITLE
Problème d’affichage

### ISSUE THREAD

**Issue by bananavdk** [KiwiHC16/Abeille#754]
Depuis le milieu de semaine dernière des qu’il y a une mise à jour(je sais pas si c’est Du plugin ou du corps) et après chaque redémarrage toutes les sondes capteurs ect se retrouvent avec la plus part des infos et commandes visible dans le Dashboard par exemple ideee , je décoche les case et sa revient à la normal.
Est ce que ce n’est que moi ?
Si ce n’est que moi y a t’il une solution ?

D’avance merci.

**Comment by KiwiHC16** [comment]
As tu bien positionné les menus ?

![Capture d’écran 2019-07-28 à 13 06 04](https://user-images.githubusercontent.com/8549674/62005772-76bea000-b138-11e9-9aa8-a79ad734fb4d.png)

**Comment by bananavdk** [comment]
Merci de ta réponse aussi rapide encore un foi.
Effectivement tout était à oui, je fait des tests et je reviens vers vous après.

Envoyé de mon iPhone

Le 28 juil. 2019 à 13:06, Ben <notifications@github.com<mailto:notifications@github.com>> a écrit :


As tu bien positionné les menus ?

[Capture d’écran 2019-07-28 à 13 06 04]<https://user-images.githubusercontent.com/8549674/62005772-76bea000-b138-11e9-9aa8-a79ad734fb4d.png>

**Comment by bananavdk** [comment]
merci tout a l'aire de fontionné, je ne comprend pas comment sa se fait que l'ensemble de ces cases ai changé du jour au lendemain...
bef, sa fonctionne c'est l'essentiel.
merci encore.
