### ISSUE TITLE
Interrupteur sans fil simple bouton

### ISSUE THREAD

**Issue by Hydci** [KiwiHC16/Abeille#757]
Bonjour,

J'ai acheter des interrupteurs muraux sans fil xiaomi aqara (voir lien plus bas) il et bien reconnu j'ai bien le click sur état 1 mais le double click ou long click ne marche pas voir les logs

Lien de l'interrupteur https://fr.aliexpress.com/item/32905672358.html?spm=a2g0s.9042311.0.0.27426c37OENNtV
[1 clickfonctionne.txt](https://github.com/KiwiHC16/Abeille/files/3457414/1.clickfonctionne.txt)
[inter 2 click fonctionne pas.txt](https://github.com/KiwiHC16/Abeille/files/3457415/inter.2.click.fonctionne.pas.txt)
[log integration.txt](https://github.com/KiwiHC16/Abeille/files/3457416/log.integration.txt)
[long click fonctionne pas.txt](https://github.com/KiwiHC16/Abeille/files/3457417/long.click.fonctionne.pas.txt)

**Comment by KiwiHC16** [comment]
Lequel est ce ?
WXKG03LM (un bouton) 
ou
WXKG02LM (deux boutons)

**Comment by Hydci** [comment]
Celui là c'est l'interrupteur sans fil Xiaomi version 1 Key c'est pas le petit bouton l'autre ticket

**Comment by KiwiHC16** [comment]
C est cette référence : WXKG03LM ?

**Comment by KiwiHC16** [comment]
1 clic:
topic":"Abeille\/5158\/0012-01-0055","payload":1

2 clic:
{"topic":"Abeille\/5158\/0012-01-0055","payload":2}

Long clic:
{"topic":"Abeille\/5158\/0012-01-0055","payload":0}


Peux tu me faire une capture d ecran de la commande 0012-01-0055 ?

**Comment by KiwiHC16** [comment]
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
https://abeilledocsphinx.readthedocs.io/fr/latest/#cagnotte

**Comment by KiwiHC16** [comment]
Integration:
```
AbeilleParser 2019-08-01 17:09:16[debug](fct mqqtPublish) added to queue (queueKeyParserToAbeille): {"message":{"topic":"Abeille\/5158\/0000-01-0005","payload":"lumi.remote.b186acn01"}}
```

```
AbeilleParser 2019-08-01 17:09:40[debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : dd; Status : 00; Short Address : 5158; Length : 20; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 5f01 (); bitField : 01; InClusterCount : 05
AbeilleParser 2019-08-01 17:09:40[debug]In cluster: 0000 - General: Basic
AbeilleParser 2019-08-01 17:09:40[debug]In cluster: 0003 - General: Identify
AbeilleParser 2019-08-01 17:09:40[debug]In cluster: 0019 - General: OTA
AbeilleParser 2019-08-01 17:09:40[debug]In cluster: ffff -
AbeilleParser 2019-08-01 17:09:40[debug]In cluster: 0012 -
AbeilleParser 2019-08-01 17:09:40[debug]OutClusterCount : 07
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0000 - General: Basic
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0004 - General: Groups
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0003 - General: Identify
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0005 - General: Scenes
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0019 - General: OTA
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: ffff -
AbeilleParser 2019-08-01 17:09:40[debug]Out cluster: 0012 -
```

**Comment by KiwiHC16** [comment]
Est ce que tu as ca ?

![Capture d’écran 2019-08-02 à 15 23 48](https://user-images.githubusercontent.com/8549674/62373184-89bae100-b539-11e9-9f0a-f068eb77a05e.png)

**Comment by KiwiHC16** [comment]
Peux tu passer de binaire à numeric ?

Je ne retrouve pas mon 1 bouton, donc je teste avec mon deux boutons mais un clic envoie 1 suivi de 0 immediatement donc tu ne verras rien dans le dashboard par contre tu dois le voir dans le log. Il faut que je retrouve mon un bouton, pour tester.

**Comment by KiwiHC16** [comment]
As tu regardé https://abeilledocsphinx.readthedocs.io/fr/latest/Xiaomi.html#retour-d-experience-sur-l-utilisation-des-wall-switch-xiaomi en particulier sur la gestion des valeurs.

**Comment by Hydci** [comment]
Effectivement passé l'état 1 a numérique a la place de binaire etat 1 affiche bien le bon nombre de click quand je repasse en binaire le double click ne fonctionne plus j'ai donc compris comment cela marcher je penser qu'au double click l'état 2 passé a 1

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je clos.
