### ISSUE TITLE
Delete device doc

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#758]

**Comment by KiwiHC16** [comment]
Faire une doc pour expliquer comment retirer un équipement du réseau.

**Comment by KiwiHC16** [comment]
Comment retirer un device qui est dans le graph LQI mais qu on ne trouve pas en vrai.

**Comment by ffp17** [comment]
> Comment retirer un device qui est dans le graph LQI mais qu on ne trouve pas en vrai.

Tu m'avais donné quelques infos à ce sujet. Avec l'adresse courte on peut récupérer l'adresse IEEE et ensuite la supprimer. Mais je n'ai pas tester car j'avais fait un reset du réseau avant.
J'ai maintenant une zigate de test, donc si besoin je peux faire des tests.

**Comment by KiwiHC16** [comment]
Je ferai les tests en sniffant pour être sure du comportement. J'ai des notes quelque part car j'ai deja fait les tests, il faut juste un peu de temps et que je retrouve mes notes pour faire la doc.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
En fait la doc est deja faite !
http://kiwihc16.free.fr/Suppression.html
Je clos.
