### ISSUE TITLE
Systeme sebfar et Legrand

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#759]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=755961#p755961

**Comment by KiwiHC16** [comment]
Peux tu partager les details techniques de l'interrupteur ? une photo ?
Version du firmware sur ta zigate ?
Version d'Abeille ?

**Comment by sebfar9172** [comment]
On a déjà échangé ensemble sur ce sujet. Tu as acheté les interrupteurs et prises après échange ensemble. Ce sont les dooxie legrand netatmo
j'avais mis la 31a mais je suis repassé en 30f mais avant que je passe en 31a tout fonctionnait bien (j'ai bien fait un erase eprom)
je suis avec la version du market d'Abeille

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ou en est t on sur ce sujet ?

**Comment by sebfar9172** [comment]
Cela s'est réglé
