### ISSUE TITLE
FLOAT Time out et batterie

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#761]
quote=ffp17 post_id=756142 time=1566030998 user_id=6152]
Bonjour,
J'ai des problèmes de noeuds qui passent en time out.
Savez-vous s'il y a un moyen pour surveiller les noeuds du réseau Zigbee ?
Par exemple un genre de ping régulier pour remonter ceux qui ne répondent pas.
Je teste les alertes intégrées à Jeedom mais j'ai peur d'avoir un message à chaque test du même équipement. Sinon il faut aller voir dans la page santé de Abeille.
@KiwiHC, je viens  de me rendre compte que les lampes IKEA FLOALT 60*60 sont déclarées comme des éléments sur pile. J'ai une alerte sur 1 lampe en time out et il faut que je change la pile mais je ne sais pas où ce trouve la pile :) 
Merci et bonne journée,

Edit : je confirme avec les alertes intégrées à Jeedom je suis spammé :(
[/quote]

Salut ffp17,
Il faut certainement qu'on regarde le modele pour le polling pour que les FLOAT ne soient pas en timeout. (Et quon eneleve les infos de piles si elles existent dans le modele. Je fais une issue pour que je regardes ce point quand j aurai un peu de temps.

**Comment by ffp17** [comment]
A ta dispo pour les tests si besoin.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Réponses:
http://kiwihc16.free.fr/Health.html
http://kiwihc16.free.fr/Polling.html

**Comment by KiwiHC16** [comment]
```
 je viens de me rendre compte que les lampes IKEA FLOALT 60*60 sont déclarées comme des éléments sur pile. J'ai une alerte sur 1 lampe en time out et il faut que je change la pile mais je ne sais pas où ce trouve la pile :)
```
Je ne comprends ce point car dans le modele FLOAT on a bien un timeout de 60 minutes et pas de piles déclaré. Ou alors le modele a ete mis a jour depuis la publication de cette issue.

**Comment by KiwiHC16** [comment]
Tout semble ok.

**Comment by ffp17** [comment]
C'est beaucoup plus clair avec la mise à jour de la doc. Merci. Je pense qu'on peut clore le ticket car je ne rencontre plus de problème particulier lié à Abeille. Le seul soucis qu'il me reste concerne un plantage de certains panneaux lumineux de temps en temps (un reset électrique résout le pb) mais cela n'a rien à voir.

**Comment by KiwiHC16** [comment]
Ok je clos. On ouvrira un autre ticket si besoin.
