### ISSUE TITLE
IKEA TRADFRI bulb E14 Color White Spectre Opal 600lm modèle

### ISSUE THREAD

**Issue by zoozbiro** [KiwiHC16/Abeille#765]
Salut Kiwi,

j'ai sans le vouloir acheté une nouvelle ampoule Ikea en titre son nom et si dessous le lien.

https://www.ikea.com/fr/fr/p/tradfri-ampoule-a-led-e14-600-lumen-sans-fil-a-variateur-dintensite-spectre-blanc-colore-opalin-50411565/

J'ai réalisé et testé le modèle sur mon environnement. Si tu veux vérifier et intégrer pour les futurs utilisateurs de celle-ci.

Bonne journée

`{
  "TRADFRIbulbE14CWSopal600lm": {
    "nameJeedom": "IKEA Ampoule TRADFRI bulb E14 Color White Spectre Opal 600lm",
    "timeout": "60",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "uniqId": "5c07c76620ce7",
      "icone": "TRADFRIbulbE14CWSopal600lm",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etatLight",
      "include5": "levelLight",
      "include6": "colorX",
      "include7": "colorY",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include12": "Colour",
      "include13": "Blanc",
      "include14": "Bleu",
      "include15": "Rouge",
      "include16": "Vert",
      "include17": "getColorX",
      "include18": "getColorY",
      "include19": "getEtat",
      "include20": "getLevel",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel",
      "include12 2": "ColourRGB",
      "include30": "setColourRGB",
      "include30 2": "setRGB",
      "include31": "colorRouge",
      "include32": "setRouge",
      "include33": "colorVert",
      "include34": "setVert",
      "include35": "colorBleu",
      "include36": "setBleu"
    }
  }
}`

**Comment by KiwiHC16** [comment]
Super, je viens de l ajouter dans le master. Le modele semble Ok. Je ne l'ai pas tester car je n'ai pas cette ampoule.

Aurais tu une image de cette ampoule ?

**Comment by zoozbiro** [comment]
Oui, j'ai pris sur le site voici
<img width="454" alt="TRADFRIBulbE27CWSOpal600lm" src="https://user-images.githubusercontent.com/4723029/63859437-a535d200-c9a7-11e9-8b92-8ac0bc85962c.PNG">

**Comment by KiwiHC16** [comment]
Ajouté dans le master.

**Comment by slowmotion85** [comment]
Bonjour Kiwi,
Merci beaucoup pour ton travail sur ce plugin.
J'ai la version white sans couleurs de cette ampoule et il m'est impossible de l'intégrer dans Jeedom. L'inclusion ne se fait pas pourtant quand je reset l'ampoule elle clignote bien et se stabilise.
Est-ce que la version sans couleur de celle-ci est prise en compte par Abeille? sinon, est-ce qu'il y a moyen de l'inclure stp?
Merci.

**Comment by slowmotion85** [comment]
Re bonjour :)
J'ai réussi à inclure ce modèle en essayant différents template (sur d'autres ampoules IKEA) et voici celui qui fonctionne bien:
`{
  "TRADFRIbulbE14WSopal600lm": {
    "nameJeedom": "TRADFRI bulb E14 White Spectre opal 600lm",
    "timeout": "60",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "uniqId": "5c07c7662f4f0",
      "icone": "TRADFRIbulbE14CWSopal600lm",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etatLight",
      "include5": "levelLight",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include12": "2200K",
      "include13": "2700K",
      "include14": "4000K",
      "include15": "temperatureLight",
      "include19": "getEtat",
      "include20": "getLevel",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel"
    }
  }
}`
