### ISSUE TITLE
Volet Profalux Calibrage

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#766]
1/ Calibrage: un calibrage Abeille vers Volet est fait dans Abeille (Sur la base de test d'un utilisateur). Si tu demandes 20% depuis Abeille le volet doit se deplacer à 20 %.
Mais le calibrage inverse Volet -> Abeille n'est pas fait. 
Donc si tu demandes 20%, Abeille envoit 30% (calibration), le volet se met à 30% et renvoie 30% d'ou ton souci probablement.
Une solution est d'enlever la calibration à l'envoie
Une autre solution est de calibrer aussi au retour (risque de ne pas etre simple du fait du calibrage non linéaire).

https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=759093#p759093

**Comment by Tof32** [comment]
Salut Kiwi
Suis prêt à tester sans calibration et te faire un retour. Si pas trop compliqué dis moi ou ça se trouve dans le code et je fait la modif sur ma conf

Merci

**Comment by KiwiHC16** [comment]
Si tu vas dans le repertoire:
/var/www/html/plugins/Abeille/core/class

tu trouveras le fichier:
AbeilleMQTTCmd.php

en ligne 2659:
```
$a = -0.8571429;
$b = 1.8571429;
$c = 0;
```

et en ligne 2674:
```
$levelPourcent = $a*$levelSliderPourcent*$levelSliderPourcent+$b*$levelSliderPourcent+c;
```

A toi de jouer....

**Comment by Tof32** [comment]
Ok je refarde ca ce week-end !
Merci ;)

**Comment by Tof32** [comment]
Hello, 
J'ai fait un test avec 
`$levelPourcent = $levelSliderPourcent;`
tout simplement et cela correspond à ce que je cherchais. Il faut juste intégrer que 50% fait plus que la moitié dans la mesure ou le volet a plus de longueur que la fenêtre puisqu'il se compacte en fin de course (aérations entre les lames). 
En convertissant juste le pourcentage en valeur de 0 à 255 on a l'avantage d'avoir un retour d'état correspondant au pourcentage demandé.

**Comment by KiwiHC16** [comment]
Oui tu vas enlever le calibrage donc plus de soucis.
Il faudrait que les paramètres de calibrage soient accessible à l utilisateur. 
Et il faudrait calibrer le retour d'état.
Dans les trucs à faire.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Fait.
