### ISSUE TITLE
Volet Profalux: Retour état sur télécommande: Il faudrait demander au volet de faire un retour d'état mais je ne sais pas si le volet le supporte. A tester.

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#767]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=759093#p759093

**Comment by Tof32** [comment]
Pour cette modif je pense que c’est faisable. J’ai cru comprendre que côté Domoticz ils l’ont intégré. J’ai la box calyps’home de Profalux qui remontait bien cet état après l’utilisation d’une télécommande. Le problème est que depuis l’inclusion des Volets avec là zigate, pas moyen d’intégrer la box dans le réseau de la zigate. 
Si il y a moyen de voir ce qui se passe sur le réseau ZigBee quand on utilise les commandes, à dispo pour faire des tests.

**Comment by KiwiHC16** [comment]
Je vais voir avec fairecasoitmeme si il peut me faire des tests.

**Comment by pipiche38** [comment]
https://github.com/KiwiHC16/Abeille/issues/767#issuecomment-526937116

Il faut faire un configure reporting sur les clusters 0x0006 et 0x0008 après avoir fait un bind

**Comment by KiwiHC16** [comment]
Merci Pipiche, c'est ce que le plugin fait normalement c'est pour cela que je suis perdu. Mais comme je n'ai pas le matos pour tester je me demande si ca fonctionne sur les volets profalux ...

**Comment by pipiche38** [comment]
J’en ai 7 à la maison et ça fonctionne très bien. Par contre il faut bien bind + configure reporting.

Des que je peu je te passe les infos que j’utilise pour les config reporting

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Voici les paramètres que j'utilise pour les volets profalux.
Sur le plugin Domoticz, on refait les bind/configure Reporting régulièrement:
- a chaque changement de Network Adresse (mais je n'ai pas vu les volets en changer)
- Toutes les 24 ou 36 heures

En gros le configure reporting est effectué sur l'attribut 0x0000 des clusters 0x0006 et 0x0008
Les paramètres sont:
Min interval à 0x0001
Max Interval à 0x012C
TimeOut à 0x0FFF
Change: à 0x01 pour cluster 0x0006 et 0x05 pour cluster 0x0008

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by pipiche38** [comment]
Pour information:
https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Profalux-corner.md

**Comment by tcharp38** [comment]
Voir 210520-BETA-4
C'est fonctionnel pour moi.
Je clos. A reouvrir si besoin
