### ISSUE TITLE
@pixeldesbois, systeme

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#770]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=759780#p759780

**Comment by pixeldesbois** [comment]
Salut,
Comme convenu je te poste la capture.
Pour obtenir cette dernière, j'ai
- désactiver le plugin "zigate"
- installer la version stable d'abeille depuis le market
[Capture](https://i.ibb.co/dKVQCs0/abeille.png)

**Comment by KiwiHC16** [comment]
Il faut activer le plugin sinon il n'est pas pris en compte.
La je le vois désactivé...

**Comment by pixeldesbois** [comment]
Oui je sais, quand je l'active puis install des dependances j'ai ça 
[Capture](https://i.ibb.co/z7dhgJd/abeille2.png)
Les logs de
`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Tools::deamonlogFilter(), 1 passed in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 174 and at least 2 expected in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php:64
Stack trace:
#0 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php(174): Tools::deamonlogFilter('Tools: nb line ...')
#1 /var/www/html/plugins/Abeille/core/class/AbeilleParser.php(2737): Tools::getJSonConfigFiles('zigateClusters....')
#2 {main}
thrown in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 64`

**Comment by Brugal21** [comment]
Bonsoir Kiwi,

D'abord un grand merci pour le développement de ce plugin. Je rencontre exactement le même problème sur mon installation, un RPI 3B+ avec RASPBIAN BUSTER dessus. J'ai essayé beaucoup de chose sans succès. Réinstallation complète du RPI avec Jeedom en V.3.3.0, en V4.0, clé Zigate en firmware 3.1a, v3.0f avec reset de l'EEPROM.
J'ai aussi essayé le plugin zi..te qui lui fonctionne normalement. Pour les logs, ils sont exactement les mêmes que pixeldesbois.
Y a t il une solution actuellement, si non je suis disponible pour faire des essais.

Merci d'avance et bonne soirée.

**Comment by KiwiHC16** [comment]
@pixeldesbois sur quel version Jeedom ?

**Comment by jewaz** [comment]
Perso: jeedom, version stable 3.3.31
et j'ai une pizigate etpib3+

**Comment by jewaz** [comment]
![image](https://user-images.githubusercontent.com/55154233/64634888-936c1a00-d3fe-11e9-9da7-cf7acbecf22b.png)

**Comment by Brugal21** [comment]
J’ai exactement le même problème sur jeedom v3.3.30 et sur v4.0.9. Je suis sur RPI3B+ avec un debian buster. Quand j’active le plugin, j’ai les dépendances : ok, la configuration du démon : ok mais le statut du démon est nok. Pour moi, sur la page de configuration du plugin j’ai le même écran que @pixeldesbois et les mêmes logs.

**Comment by jewaz** [comment]
et j'ai ca ds les logs : 

  | 2019-09-10 20:00:02 | Abeille | Erreur sur la fonction cronHourly du plugin : Call to a member function getId() on bool |  
-- | -- | -- | -- | --
  | 2019-09-10 19:15:38 | Abeille | L installation des dependances est en cours

**Comment by jewaz** [comment]
apres je m'apercois que je suis sous jeedom 3.3.31,mais ds la gestion du plugin, ca me met vesion jeedom 3.1.7....

**Comment by KiwiHC16** [comment]
@pixeldesbois, je pense avoir trouvé le problème indiqué dans tes logs:
```
PHP Fatal error: Uncaught ArgumentCountError:...
```
Soit tu recuperes le master, soit dans le fichier :
/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php

tu remplaces la ligne 174: 
```
self::deamonlogFilter( "AbeilleTools: nb line " . strlen($content) );
```

par
```
self::deamonlogFilter( "DEBUG", 'Abeille', 'Tools', "AbeilleTools: nb line " . strlen($content) );
```

**Comment by KiwiHC16** [comment]
@Brugal21 peux tu verifier ce qu'il se passe pour toi avec ce correctif ?

**Comment by pixeldesbois** [comment]
Bonjour tout le monde,
De mon côté je suis en version 3.3.30. Je pense avoir trouvé pour mon cas l'origine du problème.
L'installation est faite sur un Pi2 sur lequel était connecté une carte d'alimentation (elle permet d'allumer et eteindre proprement). Je me suis rendu compte que cette carte sous-alimentait très légèrement le Pi. Du coup, j'ai fait un essai avec une autre SD et sans la carte d'alimentation... et tout fonctionne nickel.

J'ai tenté les 2 hypothèses suivantes mais sans succès :
- Garder cette dernière install et restaurer le dernier backup : pleins de plugins ne fonctionnaient plus...
- Remettre la SD d'origine (sans la fameuse carte d'alim) et tenter l'install d'Abeille : KO.

Du coup, j'ai 2 possibilités de corrections :
- le correctif de Kiwi : rapide à tester (ce soir...). Avantage : je garde mon installation
Inconvénient : il se peut qu'il y ait eu d'autres effets de bord ailleurs dans jeedom et donc de futurs bugs incompréhensibles.
- Refaire une fresh installation. Avantage : je suis sûr que le systeme est clean.
Inconvénient :me retaper toutes les install de plugin, scenario et autres ... Les larmes me viennent car je sais que c'est la solution la plus sûr...

Pour ceux qui ont rencontrés ce problème, etiez-vous dans le même cas que moi ? En gros, un composant susceptible de sous-alimenter le Pi (ca peut-être l'alimentation elle-même)

**Comment by Brugal21** [comment]
Bonjour,
je préviens, je suis novice en RPI, linux et Jeedom (mais pas complétement nb en info :) )
J'ai acheté tout mon matériel il y a 1 mois. J'ai commencé avec le plugin zigate et un jeedom en v3.3.??, je n'ai pas rencontré de problème particulier pour la mise en place de ma domotique (inclusion de mes périphériques xiaomi et ikea). J'ai voulu ensuite testé l'abeille. Je suis donc reparti d'un système vierge avec une ré-install de RASPBIAN BUSTER avec desktop et MAJ en fin d'installation, une clé zigate re-flashé avec le firmware 3.1a, un reset de l'EEPROM, un jeedom en v3.3.30 master. Jeedom fraichement installé, je lance l'installation du plugin abeille et j'obtiens le problème énoncé ici...

D'un point de vue matériel, j'ai de mon coté un RPI 3B+ avec une alimentation de 3A. J'ai de branché sur les ports USB un dongle pour un mini-clavier et la clé zigate. Je ne pense pas être dans le même cas que toi @pixeldesbois ?

@KiwiHC16 je n'ai pas pu tester le correctif proposé hier, je tente de le faire ce soir et reviens vers toi rapidement. En tout cas merci pour ta réactivité !

Bonne journée à tous !

**Comment by pixeldesbois** [comment]
Bonsoir,
J'ai fait le test. Je n'ai plus l'erreur dans les logs mais toujours impossible d'avoir la zone de configuration de la clef zigate.
@Brugal21 : Je ne suis pas expert non plus ! D'ailleurs je me suis rendu compte que mon hypothèse était peut-être fausse car j'ai effectué le test avec une autre carte SD. Donc cela peut aussi venir de là....

Bon bah si je veux Abeille, il faut que je réinstalle tout ... quand on aime on ne compte pas ! 
Merci en tous les cas !

**Comment by Brugal21** [comment]
Bonsoir,

je viens de faire l'essai de modifier la ligne 174 du fichier Tools.php + redémarrage du RPI.
J'active le plugin, la statut du démon reste sur nok, je le redémarre et là il passe au vert !!! Aucun réglage complémentaire n'est apparu dans la gestion du plugin : 

![image](https://user-images.githubusercontent.com/55110607/64730806-2cbf2d00-d4e0-11e9-8bfe-dcda467b38a3.png)

Je vais donc sur la page du plugin et là, écran noir : 

![image](https://user-images.githubusercontent.com/55110607/64731124-d8687d00-d4e0-11e9-9f06-5752aca96dc9.png)

Avec un rafraichissement de la page(F5), j'obtiens l'écran suivant sans aucune action possible sur la page : 

![image](https://user-images.githubusercontent.com/55110607/64731173-f0d89780-d4e0-11e9-9789-bbc0ef084220.png)

Le fichier log Abeille me donne l'info suivante : 22:00:02][ERROR] : Erreur sur la fonction cronHourly du plugin : Call to a member function execCmd() on bool

@KiwiHC16 redis moi si tu as besoin de quelque chose de plus, logs, capture d'écran, essais... Aussi, pourrais tu m'indiquer sous quelle version de Raspbian et Jeedom le plugin est complétement opérationnel ? 

@pixeldesbois je voulais juste prévenir de mon niveau dans le domaine, pour te dire j'ai bien galéré 1h juste pour modifier le fichier Tools... courage pour la réinstallation ;) Je pense que le plugin Abeille vaut le coup d'être testé.

Encore merci @KiwiHC16 pour le temps passer !

Bonne soirée

**Comment by KiwiHC16** [comment]
Tous mes tests sont fait en Jeedom 3.3.x, je n'ai jamais testé Jeedom V4.x.y donc vous rencontrez probablement des soucis du fait de l evolution jeedom.

Je lis aussi que certains sont sur le nouveau debian Duster (ou un truc dans le genre) ais je suis toujours en Debian 9.

Des que j aurai le temps je testerai les nouvelles versions mais il y a tellement a faire ...

**Comment by Brugal21** [comment]
Salut,

Du coup, je suis repassé sur debian 9 et jeedom v3.3.31 et le plugin fonctionne maintenant  correctement. Je migrerai vers debian 10 et jeedom v4 quand tout sera prêt.

Bon courage pour tout le travail qu'il te reste...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
