### ISSUE TITLE
La génération du cache ne se finit pas

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#773]
Je suis en v4. Quand je lance la génération du cache cela ne se finit pas. Mais les équipements sont fonctionnels.

Pour information j'ai un message m'indiquant (je ne sais pas s'il peut y avoir un lien) :
[2019-09-10 11:24:49][AbeilleParser][error]Voltage a plus de 3.135V. Je retourne 100% mais il y a qq chose qui cloche.

**Comment by KiwiHC16** [comment]
Intéressant 
Je n ai pas encore testé la V4.

**Comment by sebfar9172** [comment]
Je ne pense pas que cela soit lié forcément à la v4

**Comment by KiwiHC16** [comment]
[2019-09-10 11:24:49][AbeilleParser][error]Voltage a plus de 3.135V. Je retourne 100% mais il y a qq chose qui cloche.

Ce message doit provenir d'un equipement qui remonte un voltage trop haut. Dans le log peux tu recuperer l adresse de l equipement et identifier l'equipement et me partager l info.

Pour le cache as tu une fichier : AbeilleLQI_MapData.json.lock
dans le repertoire: /var/www/html/plugins/Abeille/Network
Si oui que contient il ?

**Comment by sebfar9172** [comment]
C'est un détecteur d'ouverture xiaomi j'en ai 2 ou 3 avec un voltage supérieur à 3,125

Dans le fichier lock, j'ai seulement : 6 of 11 (Cafetière - 6d63 - 0)

**Comment by sebfar9172** [comment]
il faut que je décolle de la fenêtre et je regarde comment enlever la pile.

Pour le fichier lock je connais l'astuce mais cela se bloque tout le temps, j'ai même redémarrer le démon. Mais rien n'y fait.

**Comment by KiwiHC16** [comment]
Ok peux tu effacer le fichier lock.

En ssh, faire un:
```
php /var/www/html/plugins/Abeille/Network/AbeilleLQI.php 
```

et partager le résultat ?

**Comment by sebfar9172** [comment]
Voici.

Cela a bien généré le cache )
[log.txt](https://github.com/KiwiHC16/Abeille/files/3598977/log.txt)

**Comment by KiwiHC16** [comment]
Donc tu as le graph a jour maintenat ?

**Comment by sebfar9172** [comment]
Oui parfait tout fonctionne j'ai gardé la commande que tu m'as donné au cas où

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ok je viens de mettre à jour le master pour avoir le truc qui fonctionne.
Dispo dans le master.

**Comment by KiwiHC16** [comment]
Analyse du réseau: graphique incohérent
#824
