### ISSUE TITLE
Plugin sous Jeedom V4.0.9 et debian 10 Buster et RPI3 et Zigate USB

### ISSUE THREAD

**Issue by Philou-domo** [KiwiHC16/Abeille#774]
Suite à de nombreuses installations la configuration du plugin ne s'affiche pas malgré la création d'un objet Abeille et la non utilisation du plugin off zigate.
Quelqu'un pourrait il donner la marche à suivre pour bien effacer l'installation du plugin.

Log Abeille:
[2019-09-10 15:09:57][INFO] : Début d'activation du plugin
[2019-09-10 15:09:58][INFO] : Info sur le démon : {"launchable_message":"","launchable":"nok","state":"nok","log":"nok","auto":0}
[2019-09-10 15:09:59][DEBUG] : Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=Abeille function=install callInstallFunction=1
[2019-09-10 15:10:19][ERROR] : Erreur sur Abeille::deamon() : Too few arguments to function Tools::deamonlogFilter(), 1 passed in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 174 and at least 2 expected

Log AbeilleParser:
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Tools::deamonlogFilter(), 1 passed in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 174 and at least 2 expected in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php:64
Stack trace:
#0 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php(174): Tools::deamonlogFilter('Tools: nb line ...')
#1 /var/www/html/plugins/Abeille/core/class/AbeilleParser.php(2737): Tools::getJSonConfigFiles('zigateClusters....')
#2 {main}
thrown in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 64

**Comment by KiwiHC16** [comment]
Salut 
Je n ai pas encore testé sous la V4. 
Je vais ajouter dans la liste des trucs à faire.

**Comment by Xav-74** [comment]
Je profite de ce threat pour avoir une confirmation :
ma mini+ est en train de me lâcher et je viens de commander un Raspberry Pi 4. Le plug in Abeille fonctionne déjà sous Buster ? Si non, une date approximative ? Ca va devenir urgent pour moi :p 
Merci d'avance
Xavier

**Comment by KiwiHC16** [comment]
Je n'ai pas testé sous Buster. Quand ? je ne sais pas encore.

**Comment by Xav-74** [comment]
Je reçois mon PI 4 auj. Je teste donc dans la foulée. A priori la seule chose à adapter est la partie PHP 7.3 et la classe object -> jeeObject. Je te fais un retour suite à l'installation.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Xav-74** [comment]
Petit retour comme promis ce soir :
Raspberry Pi 4 recu, installation de Raspbian Buster Lite 10 puis Jeedom v4
Aucun souci à constater
Je recharge ma conf. Le plugin Abeille se charge bien et est accessible via le menu configuration.
Dépendances OK et démon lancé.
Par contre la page de mes différents équipements reste définitivement vide.
Je décide alors de modifier à la main les 3 fichiers (cf code object-> jeeobject) puis redémarrage du démon
Et là tout est OK :)
Affichage de mes volets et capteurs de T° et les commandes de mes objets virtuels fonctionnent :)
C top !
Je continue mes tests et vous tiens au courant !

**Comment by Xav-74** [comment]
Je viens de remarquer une chose : je n'ai plus la possibilité de configurer la partie concernant la clé Zigbee (cf. issue #770 )
Mais tout est fonctionnel !
A suivre

**Comment by KiwiHC16** [comment]
Salut, Le master doit être ok pour Debian 10, Jeedom V4. Il fonctionne en test sur ma VM.

**Comment by KiwiHC16** [comment]
Je clos l issue. Si toujours des soucis faire une autre issue specifique.
