### ISSUE TITLE
Xiaomi temperature carré - rafraichissement température

### ISSUE THREAD

**Issue by Franckybel** [KiwiHC16/Abeille#776]
J' ai 4 sondes bien intégrées dans Abeille.
Je me rends compte que le rafraîchissement des informations ne se fait pas de façon régulière, quelques minutes pour l'un, plusieurs heures pour un autre ... et cela sans aucune régularité
Si j'appuie sur le bouton, il y a bien une remonté d'info.
Comment "forcer" un rafraîchissement par exemple toutes les heures ?
J'avais testé également dans Domoticz, le rafraîchissement s'effectuait toutes les 5 minutes sans qu'il soit nécessaire de paramétrer quelque chose.

**Comment by KiwiHC16** [comment]
Salut,
Les sondes Xiaomi remontent la temperature toutes les heures au minimum et quand la variation est considée par la capteur suffisement suffisante pour remonter l'info.

Voir: http://kiwihc16.free.fr/Xiaomi.html#temperature-v1

Il n'y a pas de facon a ma connaissance pour modifier ce comportement.

**Comment by Franckybel** [comment]
Super les explications, je n'avais pas lu cette partie.
Suite à la lecture de tous les élèments on comprend le comportement de chaque composant, documentation très complète
Merci à toi
