### ISSUE TITLE
Problème Perte Ampoule Xiaomi apres un mois

### ISSUE THREAD

**Issue by Bernardo59** [KiwiHC16/Abeille#777]
Bonjour,
Tout d'abord, je tenais à te féliciter pour ton plug-in, car je le trouve bien programmé. Je t'ai d'ailleurs encouragé via Paypal.

Néanmoins, je me permets de vous contacter, car je rencontre des difficultés sur Jeedom, et notamment quelques bugs.

Je suis sous une VMware sous EsXi (Debian 9.9 et Jeedom à jour) avec le dongle Zigate (sans wifi). L'ensemble fonctionne correctement, car j'ai l'ensemble des remontées des capteurs de température, d'ouverture de porte, des détecteurs, etc... Sauf, que je rencontre des soucis avec les lampes XIAOMI LED Bulb.

En effet, une fois incluse, j'arrive correctement à les piloter. Puis 1 mois après et sans raison apparente, je retrouve l'ensemble des lampes en OFFLINE et impossible de les supprimer du réseau (via remove) et impossible de les réinclure une nouvelle fois.

La première fois que ça me l'avait fait, j'avais flashé le dongle Zigate et tout était reparti mais j'ai du réinclure l'ensemble des mes capteurs ce qui m'avait pris un week-end complet.
La j'ai plus de 25 capteurs et je me vois mal refaire l'ensemble des inclusions... :/
Je  te sollicite pour ça et aussi pour remonter des bugs, car quand je vais sur Jeedom et sur l'onglet Abeille PARSER, j'obtiens le message suivant:
PHP Warning:  Missing argument 2 for Tools::deamonlogFilter(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 174 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 64
Idem pour AbeilleSerialRead, j'ai le même message...
J'ai regardé un peu sur GitHub ou ça pouvait venir, mais je t'avouerai que je sèche.

Si tu as des suggestions, je suis preneur.

Te remerciant par avance,

Benoit

**Comment by KiwiHC16** [comment]
Deux sujets:
1/ lampes XIAOMI LED Bulb: perso j'en ai une qui fonctionne sans soucis depuis des semaines. Est ce que tu perds toutes tes lampes en meme temps ? Peux tu toujours les piloter ? Comment sais tu qu'elles sont OFFLINE. Qu'elle info utilises tu pour avoir cet état ? Peux tu partager le graph du réseau avec les valeurs LQI ?

2/ "Missing argument 2 for Tools" C'est un bug. J'ai proposé une correction dans https://github.com/KiwiHC16/Abeille/issues/774 #774

**Comment by Bernardo59** [comment]
Salut,

Tout d'abord, merci pour ton retour ! :) 

Non, j'ai perdu uniquement les ampoules se trouvant dans l'escalier et dans le couloir. Celle qui pilote l'allumage des toilettes est restée fonctionnelle dans un premier temps puis, même problème que les autres, impossible de les piloter. 
A l'heure d'aujourd'hui je les ai supprimées du réseau ZigBee malgré que le plugin me disait "Unknown device" et également du plug-in. 
Tu trouveras ci-dessous une capture de mes LQI:
![LQI ZIGBEE](https://user-images.githubusercontent.com/55277966/64909860-6fb41700-d711-11e9-8e2e-40f84ef0266b.PNG)

J'ai essayé de ré-inclure un nouveau capteur aujourd'hui mais j'ai le message "La Zigate semble ne pas pouvoir traiter toutes les demandes." quand je lance l'inclusion... De plus, l'inclusion a l'air de fonctionner car j'ai la zigate qui clignote pour dire qu'il a trouvé un nouvel element ZigBee. Après coup, j'ai le message suivant qui apparait dans AbeillePARSER:
PHP Notice:  Undefined property: AbeilleParser::$debig in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 2629

J'ai essayé de faire un backup sur un ancien snapshot qui était fonctionnel à l'époque mais j'ai toujours le même résultat. 
J'ai essayé avec une nouvelle installation sous Debian 9.9 en x86 mais j'ai également le même symptôme.

Si je désinstalle le plugin abeille et que je le réinstalle une nouvelle fois, dois-je tout ré-inclure ou juste sortir du sommeil l'ensemble des capteurs ? J'hésite également à formater la clé Zigate et réinstaller le firmware.
Merci de ton aide !

**Comment by Bernardo59** [comment]
En utilisant le logiciel de test de la zigate (https://zigate.fr/documentation/tester-la-zigate-usb-v1-1/) j'ai pu voir la liste de mes équipements:

Type: 0x8000 (Status)
  Length: 5
  Status: 0x00 (Success)
  SQN: 0x00
  Message: 
Type: 0x8015 (Get Devices List)
  Length: 9
  ID: 0
  Short Address: 0x9013
  IEEE Address: 0x158D00033E02B4 => OK, Chambre Parentale - Temperature
  Power Source: 0
  Link Quality: 117
  ID: 1
  Short Address: 0xC56C
  IEEE Address: 0x158D0003EEF9B4 => OK, Toilettes - Detecteur Ouverture
  Power Source: 0
  Link Quality: 180
  ID: 2
  Short Address: 0x25F6
  IEEE Address: 0x158D00033A4794 => OK, Toilettes - Detecteur Présence
  Power Source: 0
  Link Quality: 149
  ID: 3
  Short Address: 0xE070
  IEEE Address: 0x158D00036D38BC => OK, Chambre Emma - Température
  Power Source: 0
  Link Quality: 85
  ID: 4
  Short Address: 0x4BB1
  IEEE Address: 0x158D000283E8EF ==> Inconnu
  Power Source: 0
  Link Quality: 242
  ID: 5
  Short Address: 0x69D5
  IEEE Address: 0x158D0003EEF152 => OK, Salon - Detecteur Ouverture - 1
  Power Source: 0
  Link Quality: 158
  ID: 6
  Short Address: 0x7F0A
  IEEE Address: 0x158D0003EF1B18 => OK, Salon - Detecteur Ouverture - 2
  Power Source: 0
  Link Quality: 144
  ID: 7
  Short Address: 0xAAEF
  IEEE Address: 0x158D0003EEFCEE => OK, Couloir Entrée - Detecteur Ouverture
  Power Source: 0
  Link Quality: 100
  ID: 8
  Short Address: 0x8E66
  IEEE Address: 0x158D00036B2CE8 => Inconnu
  Power Source: 0
  Link Quality: 191

J'ai des équipements dont je ne connais pas mais je pense que ça doit être les ampoules puisque je ne vois que ça... :/ 
Du coup, je les ai supprimés par l'intermediaire du logiciel via la fonction "Leave". 
J'ai supprimé les équipements de la clé Zigate et j'ai pu inclure un nouvel équipement et ré-inclure mes ampoules !!! 
![ReinclusionAmpoule](https://user-images.githubusercontent.com/55277966/64910723-f40a9800-d719-11e9-8e06-5fcf5e495388.PNG)

Je t'avouerai que je n'y comprend absolument rien... :/
On dirait vraiment que la clé était comme bloquée 

Par contre, j'ai toujours des soucis niveau ABEILLEPARSER:
[AbeillePARSERLog.txt](https://github.com/KiwiHC16/Abeille/files/3612906/AbeillePARSERLog.txt)

**Comment by KiwiHC16** [comment]
Je vais regarder tout cela dès que j'ai 5 minutes.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je vais avoir un peut plus de temps maintenant.
Je viens de parcourir tous tes informations mais je sèche sur les sujets qui restent bloquants.
Quelle est ta situation ? Que souhaites tu que l on regardes ?

**Comment by KiwiHC16** [comment]
Tourjours besoin d'aide ?

**Comment by KiwiHC16** [comment]
Pas de retour ...
