### ISSUE TITLE
Problème pour inclure des Ampoules IKEA

### ISSUE THREAD

**Issue by mikatoomik** [KiwiHC16/Abeille#778]
Bonjour,
J'ai quelque fois ce message d'erreur
IEEE-Addr; adresse IEEE pour 08e7 qui remonte est deja dans l objet ef17 - Ampoule1, on fait la mise a jour automatique
et la première ampoule n'est plus dans le réseau, et a apparemment été remplacée par la seconde ampoule

je suppose que c'est un truc au niveau de cette fameuse adresse IEEE
mais je n'ai pas très bien compris où on la trouve et comment on la modifie, si deux ampoules on la même

**Comment by KiwiHC16** [comment]
Salut l'IEEE est unique pour chque produit. Il n'y en a pas deux identiques au monde.
C'est l'adresse courte qui peut changer. 
Visiblement tu as deux objets dans Abeille pour un même device physique.
Ca peut arriver dans des cas très spécifiques.
Soit l objet 08e7 est le bon soit l objet ef17. Reperes le bon et efface l autre.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je clos.
