### ISSUE TITLE
Retain flag

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#78]
Sur un objet deja existant, ajout d une commande et par défaut le flag retain is set, should not !!!

**Comment by edgd1er** [comment]
As tu essayé du qos = 1?

**Comment by KiwiHC16** [comment]
Non pas encore. Je viens d'ajout Identify et je cherche a récupérer les groupes des ampoules IKEA. J'avoue que comme cela fonctionne actuellement ce n'est pas dans mes priorités...

**Comment by edgd1er** [comment]
Ct pr savoir si en testant qos=1 ca avait déclenché le retain flag. Pas de lien a priori, mais j ai touché au client mosquitto, donc a étudier....

**Comment by KiwiHC16** [comment]
Non non c est dans un object, tu peux demander la creation d une commande et par défaut il met le flag.
![capture d ecran 2018-02-04 a 19 41 04](https://user-images.githubusercontent.com/8549674/35780945-6a546faa-09e3-11e8-9a1b-9b9e2df66de8.png)
Commande créée avec le flag.
![capture d ecran 2018-02-04 a 19 41 12](https://user-images.githubusercontent.com/8549674/35780946-6f28a78a-09e3-11e8-8da4-ff1ba270933d.png)

**Comment by KiwiHC16** [comment]
Modification faite, sera dans le prochain push.
