### ISSUE TITLE
Configuration plugin Abeille impossible !

### ISSUE THREAD

**Issue by didius62** [KiwiHC16/Abeille#780]
Bonjour

Je souhaite tester le plugin Abeille mais la partie configuration du plugin n'apparait pas !
le log du plugin donne toujours la meme erreur 👍 
[2019-09-20 15:26:27][ERROR] : [MySQL] Error code : 23000 (1452). Cannot add or update a child row: a foreign key constraint fails (`jeedom`.`eqLogic`, CONSTRAINT `fk_eqLogic_object1` FOREIGN KEY (`object_id`) REFERENCES `object` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)  : INSERT INTO `eqLogic` SET `id` = :id, `name` = :name, `logicalId` = :logicalId, `generic_type` = :generic_type, `object_id` = :object_id, `eqType_name` = :eqType_name, `eqReal_id` = :eqReal_id, `isVisible` = :isVisible, `isEnable` = :isEnable, `configuration` = :configuration, `timeout` = :timeout, `category` = :category, `display` = :display, `order` = :order, `comment` = :comment, `tags` = :tags

l'installation Jeedom est toute fraiche derniere version , la zigate est connectée en USB et fonctionne si je teste avec le plugin zigate .

j'ai tenté de desinstaller et reinstaller , toujours la meme erreur.

que puis je faire ?

Merci

**Comment by didius62** [comment]
Bonjour 
N'ayant pas de reponse je quitte les tests sur pc , pour revenir a un raspberry.
l'installation du plugin Abeille se presente mieux , la configuration est bien disponible.
Malheureusement le mode inclusion ne fonctionne pas : 
erreur 
  [MySQL] Error code : 23000 (1452). Cannot add or update a child row: a foreign key constraint fails (`jeedom`.`eqLogic`, CONSTRAINT `fk_eqLogic_object1` FOREIGN KEY (`object_id`) REFERENCES `object` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) : INSERT INTO `eqLogic` SET `id` = :id, `name` = :name, `logicalId` = :logicalId, `generic_type` = :generic_type, `object_id` = :object_id, `eqType_name` = :eqType_name, `eqReal_id` = :eqReal_id, `isVisible` = :isVisible, `isEnable` = :isEnable, `configuration` = :configuration, `timeout` = :timeout, `category` = :category, `display` = :display, `order` = :order, `comment` = :comment, `tags` = :tags

De plus la zigate ne quitte jamais le mode inclusion! 

Je suis dans l'incapacité de tester ce plugin , dommage je voulais le comparer au plugin zigate !

Bonne journée

**Comment by didius62** [comment]
Bonjour 
Je suis surpris de ne pas avoir de reponse du developpeur du plugin !

Cdt

**Comment by KiwiHC16** [comment]
Salut didius62,

Voici dans quel situation je développe ce plugin ...
https://www.jeedom.com/forum/viewtopic.php?f=59&t=33573&p=575280&hilit=abeille#p575280

Et ces derniers temps comme indiqué dans le forum, je n'ai pas vraiment de temps...

**Comment by KiwiHC16** [comment]
Sur quelle version de Jeedom es tu ? Si c'est la V4, d'autres ont remonté ce type de problème mais je n'ai pas testé sur jeedom V4...

**Comment by didius62** [comment]
Bonjour 
La version de jeedom est 3.3.32.

Didier

**Comment by KiwiHC16** [comment]
Peux tu partager une capture d'ecran de la page configuration ?
Peux tu partager le log Abeille ?
Sur qu'elle machine RPI ? VM ?
Quelle version d'OS ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ou en es tu sur ce sujet ?

**Comment by Cyril25000** [comment]
Bonjour, 
j'ai le même soucis de la page blanche dans la page de configuration.
Par contre si je rafraîchi la page, alors tous les textes apparaissent avec les symboles {{text}}. Même les textes du menu Jeedom tel que Accueil, Analyse....

[log abeille 20190130.docx](https://github.com/KiwiHC16/Abeille/files/3791269/log.abeille.20190130.docx)

version Jeedom : 3.3.29
RPI : 3b+ Linux raspberrypi 4.19.66-v7+ #1253

En espérant que ca aide à debugger.

Cyril

**Comment by didius62** [comment]
Merci mais je suis retourné sur le plugin zigate.

**Comment by KiwiHC16** [comment]
@Cyril25000 , peux tu me dire quelle version d'Abeille tu as ?
Est ce la derniere en stable du market ?

Ce genre de probleme est typique d'une erreur de typo. Normalement ce n'est pas grand chose a corriger. Reste à la trouver.

**Comment by KiwiHC16** [comment]
Je viens de mettre la version stable de Abeille sur mon systeme en Jeedom 3.3.35 et je ne rencontre pas le soucis.
Quel browser utilises tu ?

**Comment by KiwiHC16** [comment]
Pas de nouvelle, je clos. Rouvrir si besoin.
