### ISSUE TITLE
Integration Ampoule IKEA plante le démon

### ISSUE THREAD

**Issue by stepkinn** [KiwiHC16/Abeille#781]
Bonjour,
je tente d'inclure une ampoule IKEA comme suit :
- je place ma ZiGate collée à l'ampoule
- Abeille en mode inclusion
- Reset de l'ampoule (6 fois ON OFF depuis l'état allumé. L'ampoule s'éteint et se rallume une fois).
- Patiente 30s, rien dans Jeedom
- J'éteins l'ampoule 15s puis la rallume
- Le démon ABEILLE s'est arrêté et ne redémarre pas.
- Je reboot mon Jeedom pour retrouver le démon en fonctionnement.

Ci-joints mes logs en mode DEBUG de toute la procédure ci-dessus.
Ne sachant pas lesquels envoyer je les joints tous :)

[AbeilleMQTTCmd.log](https://github.com/KiwiHC16/Abeille/files/3639679/AbeilleMQTTCmd.log)
[Abeille.log](https://github.com/KiwiHC16/Abeille/files/3639680/Abeille.log)
[AbeilleSerialRead.log](https://github.com/KiwiHC16/Abeille/files/3639681/AbeilleSerialRead.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/3639682/AbeilleParser.log)

**Comment by stepkinn** [comment]
Je viens de refaire un essai d'intégration et cette fois le démon à planté lors de l'inclusion.
J'ai trouvé cette ligne dans le log Abeille : 
[2019-09-22 13:56:20][INFO] : objet: TRADFRI bulb E14 CWS opal 600lm recherché comme TRADFRIbulbE14CWSopal600lm ne peut pas etre creer car je ne connais pas ce type d objet.
[Abeille_2.log](https://github.com/KiwiHC16/Abeille/files/3639691/Abeille_2.log)

**Comment by KiwiHC16** [comment]
Cette ampoule: TRADFRIbulbE14CWSopal600lm est bien dans le master. Peut être n'est elle pas sur la version Abeille de ton système. Mais cela ne devrait pas planter le demon. Et je ne vois pas de trace de plantage dans les logs.
Peux tu mettre le master sur ton système?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Des nouvelles ?

**Comment by stepkinn** [comment]
Salut Kiwi,
j'ai essayé plusieurs fois et toujours rien. J'ai tenté depuis la dernière mise à jour et pas mieux.
Mettre le master ? Tu veux dire mettre à jour direct depuis le GIT ?

**Comment by stepkinn** [comment]
Salut Kiwi,

j'ai réussi à inclure l'ampoule !
Mode opératoire : Mod inclusion de la zigate / Reset de l'ampoule avec 6 extinction/allumages consécutifs en partant de l'état allumé et elle est remontée direct (j'ai même l'impression que le message de remontée d'un nouveau module est apparu avant la fin du reset).

J'utilise Abeille dans mon installation domotique quotidienne donc merci pour ton travail et pour le suivi de cette demande !
