### ISSUE TITLE
Ajout ampoules INNR RF263 et RF265

### ISSUE THREAD

**Issue by ccrepin** [KiwiHC16/Abeille#782]
Bonjour,
Je souhaite équiper mon installation de ces 2 modèles d'ampoules.
Ok avec le plugin ZIGATE Mais KO sur Abeille.

J'ai extrait les logs parser. Pouvez vous voir si c'est ajoutable sur abeille ?

[INRR_RF263_AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/3639803/INRR_RF263_AbeilleParser.log)
[INRR_RF265_AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/3646864/INRR_RF265_AbeilleParser.log)

Si besoin, je peux faire livrer ces modèles chez vous ? Ou cagnotte. Dites moi...

Merci

**Comment by ccrepin** [comment]
Finalement, je me suis tombé sur la doc d'inclusion, c'est très clair.

J'ai généré les 2 json+ajout dans le git.
Je ne peux pas uploader les images, elles sont ici si vous souhaitez les ajouter
http://dl.free.fr/sUbuSti5u
http://dl.free.fr/fGGbiCcqm

**Comment by KiwiHC16** [comment]
Je viens de rajouter les icones dans le master.
