### ISSUE TITLE
Humein - 3 Détecteurs incendie non reconnus

### ISSUE THREAD

**Issue by Franckybel** [KiwiHC16/Abeille#783]
Bonjour,

J'avais ouvert un autre poste, mais je n'ai pas eu de retour afin de corriger le problème.
J'ai 3 détecteurs incendie Heiman qui ne s'enregistrent pas dans Abeille.
Un collègue a réussi à les intégrer dans son environnement Domoticz et sa Zigate.

Voici les LOGS en mode debug durant l'essai d'intégration.
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3641361/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3641362/AbeilleParser.txt)

Dès que j'aurai la solution, je vais pouvoir lancer mes scénarios avec alarme et information mail/SMS sur ce type d'alerte en récupérant également la température des pièces concernées.

Merci d'avance pour le support

**Comment by Franckybel** [comment]
Voici encore plus de détails pour effectuer une analyse et pouvoir donner une solution
Lors de l'inclusion, Abeille n'ajoute pas le device mais le device est bien enregistré sur le réseau Zigate.
Lorsque l'on demane à Abeille d'effectuer la carte du réseau on peut constater que le device est bien sur le réseau mais attaché à aucun device dans Abeille.

Liste des Devices
![image](https://user-images.githubusercontent.com/53462598/66103880-4cb1b000-e5b7-11e9-8652-995e79ce8f78.png)

Carte du réseau Zigbee généré par Abeille via 'Network List'
Le device 00158d000275a1c8 n'est pas dans Abeille mais bien visible sur la cartographie du réseau Zigbee de la Zigate
Même problème une fois encore sur les 3 détecteurs
![image](https://user-images.githubusercontent.com/53462598/66104092-d6617d80-e5b7-11e9-9bde-ebadbb80961a.png)

**Comment by Franckybel** [comment]
Merci d'avance pour le support sur ce sujet, il est étrange que la Zigate intègre bien le device et que le plugin Abeille ne e prenne pas en compte

**Comment by KiwiHC16** [comment]
Bonjour,
Je ne connais pas ce modele et donc il n'est pas dans Abeille.
Peux tu partager toutes les informations sur ce produit ?
Photos ? Specifications ? Liens d'achat ?....
Dans le log je trouve des informations très interessantes qui montre que le détecteur est bien dans le réseau et qu'on doit pouvoir le gérer:
```
[AbeilleParser][debug];Type; fct; processAnnonceStageChg, NE: {"3797":{"IEEE":"00158d0001ff5bcb","capa":"80","timeAnnonceReceived":1568478518,"state":"configuration","action":"modelIdentifierReceived->configuration","EP":"01","modelIdentifier":"SmokeSensor-N-3.0"}}
```

**Comment by KiwiHC16** [comment]
```
[AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : 24; Status : 00; Short Address : 3797; Length : 16; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0402 (IAS Zone); bitField : 01; InClusterCount : 06
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0003 - General: Identify
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0001 - General: Power Config
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0500 - Security & Safety: IAS Zone
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0502 - Security & Safety: IAS WD
[2019-09-14 18:28:46][AbeilleParser][debug]In cluster: 0B05 - Misc: Diagnostics
[2019-09-14 18:28:46][AbeilleParser][debug]OutClusterCount : 01
[2019-09-14 18:28:46][AbeilleParser][debug]Out cluster: 0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
#775 
Ici on parle d un capteur: Humein alors que dans l autre on parle de Heiman, est ce les mêmes ?

J'ai inclus un Heiman que j'ai en stock mais je ne connais pas Humein.

**Comment by Franckybel** [comment]
Salut,

Super bonne nouvelle, en fait ces appareils ressemblent très fortement aux Humein et dans Domoticz ils sont intégrés comme des Humein.
Si ce n'est pas déjà fait, je vais cloturer l'autre sujet car en fait cela est le même avec les mêmes capteurs
Si je ne me trompe pas on peut aussi demander aux capteurs de sonner.
Voici les informations demandées
Sur le site Aliexpress : https://fr.aliexpress.com/item/32842412335.html?spm=a2g0s.9042311.0.0.76676c37nunhU8
Les photos de l'appareil et de la documentation
![20191004_191935](https://user-images.githubusercontent.com/53462598/66227700-fab77a00-e6dd-11e9-8b8f-1f5e9eb390d3.jpg)
![20191004_191940](https://user-images.githubusercontent.com/53462598/66227702-fab77a00-e6dd-11e9-845c-9cc024bc1a20.jpg)
![20191004_191948](https://user-images.githubusercontent.com/53462598/66227703-fb501080-e6dd-11e9-88a7-1eed70d31531.jpg)
![20191004_191930](https://user-images.githubusercontent.com/53462598/66227704-fbe8a700-e6dd-11e9-927c-fa788841df9e.jpg)
![20191004_192018](https://user-images.githubusercontent.com/53462598/66227776-2cc8dc00-e6de-11e9-8d8e-51ee55bbd8bb.jpg)
![20191004_192032](https://user-images.githubusercontent.com/53462598/66227777-2cc8dc00-e6de-11e9-93b1-1d9799b504b3.jpg)
![20191004_192043](https://user-images.githubusercontent.com/53462598/66227778-2cc8dc00-e6de-11e9-8529-09e8a9cbef79.jpg)
![20191004_192050](https://user-images.githubusercontent.com/53462598/66227780-2cc8dc00-e6de-11e9-998c-740602339927.jpg)

**Comment by KiwiHC16** [comment]
Visiblement ils osnt vendus sous plusieurs nom...
Je duplique le modele...

**Comment by KiwiHC16** [comment]
Je viens de mettre le modele dans le master. Peux tu tester ?

**Comment by Franckybel** [comment]
Tu as raison et cela est trompeur car on pense acheter du Humein mais c'est une autre marque même si même appareil.
Quand tu parles master, tu veux dire mise à jour à partir de github en suivant
Alternative : Installation du plugin Abeille avec github depuis le market
Si c'est le cas, Après mise à jour, mode inclusion et aucun changement, l'appareil est bien sur le réseau zigbee mais pas présent dans Abeille.
J'ai redémarré Jeedom après mise à jour au cas où, idem.
Dis moi si je dois te fournir plus d'élèments, merci encore pour ton support

**Comment by KiwiHC16** [comment]
Oui faire une mise a jour depuis github mais que si tu maitrises Github.

Peux tu me confirmer que tu as bien les fichiers dans 
![Capture d’écran 2019-10-11 à 12 36 23](https://user-images.githubusercontent.com/8549674/66645451-c08d3180-ec23-11e9-8f8a-3934afbf4c4e.png)

**Comment by Franckybel** [comment]
Salut
Visiblement le répertoire n'existe pas
![image](https://user-images.githubusercontent.com/53462598/66649546-bfadcd00-ec2e-11e9-98ec-6c66aec0b500.png)

Voici ce que j'ai pour la version Abeille avec github depuis le market lors de ma mise à jour il y a 3 jours, je n'avais eu aucun message d'erreur lors de l'installation manuelle
![image](https://user-images.githubusercontent.com/53462598/66648794-bf143700-ec2c-11e9-8521-dc8433ffea4b.png)

**Comment by KiwiHC16** [comment]
Ca ne semble pas être la derniere version car la derniere version à pour référence: 7925649390736c811f2cae4c47866ebcd2a9d31a

Récupères le répertoire et le fichier ici: https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices et mets les sur ton systeme.

**Comment by Franckybel** [comment]
Dans le lien que tu as fourni des devices, il n'y a pas le répertoire "SmokeSensor-N-3.0" que tu as mentionné précédemment. 
Est-ce une erreur de ma part ?

**Comment by KiwiHC16** [comment]
Peux tu mettre la dernier version stable et vérifier que tu as bien les fichiers.
Si oui faire l inclusion...

**Comment by Franckybel** [comment]
J'ai installé la version stable
Le répertoire "SmokeSensor-N-3.0" dans Devices n'existe pas après l'installation de la version stable
J'ai quand même testé l'inclusion et le résultat est le même, visible sur le réseau Zigbee (00158d...) et absent d'Abeille
Voici les captures d'écran
![image](https://user-images.githubusercontent.com/53462598/66826427-b3868000-ef4c-11e9-8112-4b6608d6e6d5.png)
![image](https://user-images.githubusercontent.com/53462598/66826479-d31da880-ef4c-11e9-8bcc-78d82b52d753.png)

**Comment by KiwiHC16** [comment]
Y a un truc bizarre. Mes systemes de devaient pas etre a jour. Je pousse une nouvelle stable pour etre dispo demain matin.

**Comment by Franckybel** [comment]
J'ai installé la version stable
Les appareils remontent bien dans Abeille, il y a juste un 'Mais', lorsqu'il y a détection incendie sur le capteur, Abeille ne met pas l'état à 1 du capteur alors que dans les LOG je constate bien une communication.
Pour 'aider à voir potentiellement le problème, j'ai mis les logs en mode debug et voici les fichiers exportés après déclenchement de l'alarme sur le capteur.
Dits moi si tu as tout ce qu'il te faut ... pas simple visiblement à vouloir intégrer un Sensor qui n'est pas connu.
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/3736559/AbeilleMQTTCmd.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3736560/AbeilleParser.txt)
[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/3736561/AbeilleSerialRead.txt)
[event.txt](https://github.com/KiwiHC16/Abeille/files/3736562/event.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3736563/Abeille.txt)

**Comment by KiwiHC16** [comment]
Salut, Je ne me souvient plus exactement du fonctionnement mais je vois ce message:
```
[2019-10-16 22:33:21][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 06; Src Addr : 2521; End Point : 01; Cluster ID : 0001; Attr ID : 0021; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : ->92<-
```
et ce message:
```
[2019-10-16 22:33:18][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 00; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0021; extended status: 00; zone id: 01; delay: 0000
```
et si tu regardes dans la doc que j ai fait: http://kiwihc16.free.fr/Heiman.html
je parle bien de 0021.
Il faut que je regarde plus en détail quand j'aurai le capteur dans les mains pour faire un test.

**Comment by KiwiHC16** [comment]
```
[2019-10-16 22:33:18][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 00; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0021; extended status: 00; zone id: 01; delay: 0000
[2019-10-16 22:33:18][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 03; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0020; extended status: 00; zone id: 01; delay: 0000
[2019-10-16 22:33:20][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 05; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0021; extended status: 00; zone id: 01; delay: 0000
[2019-10-16 22:33:22][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 07; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0020; extended status: 00; zone id: 01; delay: 0000
[2019-10-16 22:33:28][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 09; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0021; extended status: 00; zone id: 01; delay: 0000
[2019-10-16 22:33:28][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 0B; endpoint: 01; cluster id: 0500; src address mode: 02; src address: 2521; zone status: 0020; extended status: 00; zone id: 01; delay: 0000
```
En filtrant on voit bien les valeurs 20 et 21 dans zone status comme dans la doc.

Abeille ne converti pas la valeur en 1 (Alarme) et 0 (Pas alarme) pour laisser toute flexibilité à l'utilisateur. Il faut dans ton scénario mettre detection sur nouvelle valeur et test si 20 ou 21...

**Comment by KiwiHC16** [comment]
Pour moi tout semble ok et il fonctionne comme l'Heiman.

**Comment by Franckybel** [comment]
Parfait, j'ai juste une dernière question les valeurs 0020 et 0021 sont dans "Zone Status" comme tu l'as indiqué et comme indiqué dans la documentation, mais ce champ n'existe pas dans l'objet. 
Comment l'extraire ? je n'ai pas trouvé sur le web.

**Comment by KiwiHC16** [comment]
Aie. Il faut que je regardes.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-10-21 à 13 21 42](https://user-images.githubusercontent.com/8549674/67201069-bc23fe00-f405-11e9-8356-eb466b76d683.png)

**Comment by KiwiHC16** [comment]
As tu la commande ?
![Capture d’écran 2019-10-21 à 13 22 25](https://user-images.githubusercontent.com/8549674/67201115-d4941880-f405-11e9-9b4a-5211bc2125f1.png)

La valeur 20 et 21 doit remonter dedans.

**Comment by Franckybel** [comment]
Je viens d'effectuer de nouveau les tests.
Il y a bien une remontée d'information mais le champs Etat ne se met pas à jour et reste à 0.
Que ça soit sur le widget ou dans l'historique, cela est vrai pour les 3 détecteurs.
Juste une petite capture d'écran sur les logs temps réel.
Décidément pas de chance avec ce modèle de détecteur, y a t il un problème dans le modèle ?
![image](https://user-images.githubusercontent.com/53462598/67230264-4471c580-f43d-11e9-971c-018b287cca53.png)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-10-22 à 14 21 08](https://user-images.githubusercontent.com/8549674/67285085-32dcfc00-f4d7-11e9-84bc-d9f2acc33eaa.png)
Peux tu me confirmer que tu as bien cela pour la commande ?

Pour déclancher il faut une fumée. Je ne sais pas le déclencher sans fumée. Peux tu envoyer de la fumée et partager le log AbeilleParser ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Franckybel** [comment]
Pas de soucis pour la cagnotte car tu vas me faire gagner l'achat de capteurs :)
Ok,  durant le test j'ai fait déclencher l'alarme en appuyant sur le bouton puis avec une allumette.
Je ne suis pas expert voici ce que je remarque
- Les valeurs remontées semblent identiques avec alarme par Bouton ou réelle avec allumette
- il semble que le "SQN" s'incrémente bien et la remontée "Attr ID : 0021" (Si c'est ça le champs de remontée de l'alarme)
- A l'arrêt de la sonnerie il ne semble pas que la valeur "Attr ID" revienne à 0020 (comme indiqué dans la doc).
- Sur le widget la valeur Etat reste à 0 sur tout le test..

Voici le Log Parser
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3758310/AbeilleParser.txt)

Capture d'écran de la commande, cela semble identique à toi
![image](https://user-images.githubusercontent.com/53462598/67328814-4eb5c180-f51a-11e9-913f-bf150f72e131.png)

**Comment by KiwiHC16** [comment]
Comment fais tu l'alarme par bouton ? (perso ce ne semble pas fonctionner, peut être que le soft est different entre ton module et le mien).

**Comment by KiwiHC16** [comment]
Si tu fais un 
```
grep -R "fac6" AbeilleParser.txt | grep "Attr ID : 002"
```

On n'a que des Cluster 01 qui indique le niveau batterie:
```
AbeilleParser.txt:[2019-10-22 22:05:41][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 96; Src Addr : fac6; End Point : 01; Cluster ID : 0001; Attr ID : 0021; Attr Status : 00; Attr Data Type : 20; Attr Size : 0001; Data byte list : ->c8<-
```

Il n'y a rien pour le cluster 0500 donc normal que le widget ne change pas.
Je me demande si la config du device doit etre faite (je ne me souviens plus) et si elle est faite dans ton cas.

![Capture d’écran 2019-10-25 à 10 19 14](https://user-images.githubusercontent.com/8549674/67555061-e846c400-f710-11e9-883d-7f1c25365774.png)

Tu vas trouver dans les commandes :
- BindShortToSmokeHeiman
- setReportSmokeHeiman

Peux tu reveiller le device et lui envoyer ces commandes avec le bouton "tester" de celle ci et me partager le log AbeilleParser.

**Comment by Franckybel** [comment]
Pour déclencher l'alarme en fait il suffit d'appuyer sur le bouton clignotant rouge, attention aux oreilles.
Visiblement pas aussi simple que cela pour intégrer ces détecteurs incendie qui ressemble à l'origine aux Heiman mais qui n'en sont pas.
Je ne sais pas comment cela fonctionne avec Domoticz, mon collègue m'a emprunté un détecteur et visiblement il a été vu comme un Heiman.
Si tu vois que c'est trop compliqué, n'hésite pas à me le dire, je les revendrai et j'achèterai du Xiaomi.

Voici le fichier AbeilleParser en ayant exécuté les 2 commandes et également appuyé sur l'alarme.
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3773432/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Je ne vois rien dans ton log par rapport à l'alarme.
As tu fait:
- BindShortToSmokeHeiman
- setReportSmokeHeiman

**Comment by Franckybel** [comment]
J'avais bien cliqué sur tester sur chaque commande après avoir mis les logs en mode Debug.
J'ai reproduit la séquence
- Log mode debug
- En réveillant le capteur par une alarme en appuyant sur le bouton
- Cliqué sur les 2 commandes
- Déclenchant l'alarme en appuyant sur le bouton
Voici le nouveau Log
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3785964/AbeilleParser.txt)

**Comment by KiwiHC16** [comment]
Je ne comprends pas, je ne vois des manips que tu dis faire dans le log.

Je ne vois qu'une solution pour avancer maintenant c'est qu'on fasse un partage d'écran pendant que tu fais les manips.

Si tu es ok, il faudrait que tu installes anydesk.com sur ta machine que tu utiilises pour le browse et que tu me donnes le code d'accès. il me faudrait aussi deux ssh ouvert sur jeedom.

Tiens moi au courant.

**Comment by Franckybel** [comment]
Salut,

Pas de soucis pour avancer comme tu l'indiques, j'ai installé anydesk sur mon PC, 
SSH est déjà mis en place il faut juste créer les 2 users
Comment veux tu planifier cela ?
Peut-on échangé en privé pour que je t’indique ce que tu as besoin ?

**Comment by KiwiHC16** [comment]
Toujours preneur pour investiguer ? Si Ok, il faudra que tu m'envoies la clef AnyDesk pour que je me connectes. Tiens moi au courant.

**Comment by Franckybel** [comment]
Salut
J'ai revendu les détecteurs et je vais acheter des xiaomi il y aura moins de problèmes
Je vais te déposer un don car tu as passé du temps sur ça.

A+

**Comment by Franckybel** [comment]
Merci encore
