### ISSUE TITLE
Systeme @ymer66

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#789]
De: ymer66
Bonsoir kiwi
Depuis 2 semaine environ, ai tous mes modules à piles qui passent au rouge.
Parfois,je suis obligé de les réveiller manuellement ou d'attendre le lendemain.
Hier j'ai changé toutes mes piles.
Mais rien à faire. Ça vient de me le faire.
Aurais-tu une idée ?
Cordialement.

**Comment by KiwiHC16** [comment]
De: ymer66
Oui ,j'ai 4 prises Xiaomi et plusieurs Switch Xiaomi (version sans fire Line) disposés dans la maison pour faire relais.
J'ai aussi deux ampoules Ikea. Une dans mon salon et une partie nuit.
Non, mes modules sur secteur restent opérationnels (Vert). Et la ruche ne tombe pas !
Une idée ?

**Comment by KiwiHC16** [comment]
Peux tu partager une capture de la page santé ?
Une capture de la page Network Graph ?
Log Abeille et log AbeilleParser

**Comment by galise2play** [comment]
Avec plaisir. (ps pour le moment ça n'a pas clashé)
Les deux lumieres ikéa (je ne les utilise plus)
le switch, je ne l'ai pas réveillé.
![Capture du 2019-10-08 18-38-25](https://user-images.githubusercontent.com/43139505/66415620-4fb80080-e9fc-11e9-81f6-55c3416e86d4.png)
![Capture du 2019-10-08 18-38-39](https://user-images.githubusercontent.com/43139505/66415626-5181c400-e9fc-11e9-9959-81be8e68f206.png)
![Capture du 2019-10-08 18-38-49](https://user-images.githubusercontent.com/43139505/66415632-547cb480-e9fc-11e9-9940-c4a39be87871.png)
![Capture du 2019-10-08 18-39-51](https://user-images.githubusercontent.com/43139505/66415636-56467800-e9fc-11e9-8699-27077a287291.png)

**Comment by galise2play** [comment]
[abeille.txt](https://github.com/KiwiHC16/Abeille/files/3703614/abeille.txt)

**Comment by galise2play** [comment]
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3703617/AbeilleParser.txt)

**Comment by galise2play** [comment]
Bonsoir Kiwi, comme tous les soir mon zigbee tombe....
En image :
![Capture du 2019-10-08 22-47-35](https://user-images.githubusercontent.com/43139505/66432146-b0a40080-ea1d-11e9-8bfa-564ab32c5c35.png)
![Capture du 2019-10-08 22-47-53](https://user-images.githubusercontent.com/43139505/66432158-b4d01e00-ea1d-11e9-9a6b-5c0e5d965c5f.png)

**Comment by galise2play** [comment]
[abeilleparser.txt](https://github.com/KiwiHC16/Abeille/files/3704464/abeilleparser.txt)
[abeille.txt](https://github.com/KiwiHC16/Abeille/files/3704465/abeille.txt)

**Comment by galise2play** [comment]
Salut KiwiHc16,
Ce matin, à mon réveil tout était dans le rouge (modules sur pile)
Au vu du grand nombre de modules sur pile, j'ai donc décidé d'optimiser le déploiement des routeurs dans ma maison.
J'ai commencé par supprimer mes ampoules ikéas qui ne me servaient plus.
J'ai déployé mes prises et j'ai souhaité faire un "GetLQI" pour mettre à jour le graphique du réseau.
Le problème c'est qu'il m'est impossible d'exécuter "GetLQI". Il affiche un message d'erreur en rouge qui disparait aussitot "oups.... debug, file d'attente.." bref je n'ai pas le temps de le lire.
J'ai aussi des modules sur piles xiaomi avec des voltages à plus de 3.135 v. (log Abeilleparser)
Que puis-je faire pour remettre un peu d'ordre dans tous ça ?
L'idée de répartir mes routeur est selon toi bien tenté ?
Cordialement.

**Comment by JC38** [comment]
@remidetoulon .
Essaye de réinstaller le plugin sur lui-même. On est déjà 2 à avoir eu ce pb de GetLQI ko et la réinstall par dessus a fait le job. Centre de mise à jour et réinstaller sur la ligne du plugin.

**Comment by galise2play** [comment]
Ça fonctionne. Merci
Et depuis hier soir. Rien n'est tombé pour le moment.
Il a fallu revoir la disposition de mes routeurs.
Encore merci

**Comment by KiwiHC16** [comment]
Ok super. Je clos le sujet alors.

**Comment by galise2play** [comment]
Bonjour Kiwihc16. Ce matin je me lève et tous les capteurs de portes Xiaomi
ainsi que mes capteurs de température Xiaomi sont au 3/4 dans le rouge.
Même des capteurs qui sont à 4m de la zigate (sans aucun obstacle).
Je ne comprends pas.
Aurais tu une idée ?

**Comment by JC38** [comment]
Quelles sont les valeurs des LQI quand ça fonctionne ? Tout tombe, tu as rien d'autres que du Xiaomi qui resterait up ?

**Comment by galise2play** [comment]
Salut kiwiHC
Je crois avoir trouvé l'erreur.
J'ai deux gateway Xiaomi dans les chambres de mes enfants. Et après
réflexion, je me suis dit que ça pouvait être un élément perturbateur. Je
les ai débranchés, tout est revenu. Il faut voir sur plusieurs jours.

**Comment by galise2play** [comment]
Salut kiwiHC
A nouveau, hier soir tout est tombé !! A mon réveil ce matin quelques
modules de sont réveillés (capteurs d'ouverture) en ouvrant et fermant la
porte. D'autres comme les boutons aqara doivent impérativement être
réveillés en appuyant sur le Petit bouton.
Je crois que pour élucider mon problème je vais tout reinclure à commencer
par les routeurs dans le bon ordre.
Tu as un ligne bien particulière à me conseiller ?
Pour le moment je clique sur "inclusion" puis sur le bouton du module à
appairer. La zigate clignote plus vite sans laisser de message particulier.
Est ce la bonne procédures ?

**Comment by galise2play** [comment]
Salut Kiwihc16,
Dis moi, c'est toi qui est du côté de Perpignan ?
