### ISSUE TITLE
Problème de "remplacement" de devices Osram

### ISSUE THREAD

**Issue by waazdakka** [KiwiHC16/Abeille#792]
J’ai tenté plusieurs fois d’appairer un capteur de mouvement Osram via la Zigate. Systématiquement, celui-ci prend la place d’une prise connectée Osram, avec le laconique message “IEEE-Addr; adresse IEEE pour 953c (ou autre) qui remonte est deja dans l objet e102 - Osram… on fait la mise à jour automatique”.

Résutat : le device remplacé (une prise Osram, à chaque fois j'ai l'impression) semble changer d'adresse IEEE pour une nouvelle adresse, et le capteur de mouvement prend l'adresse de la prise mais est encore considérée comme une prise Osram (donc capteur inutilisable).

Une idée ? Merci !!

**Comment by KiwiHC16** [comment]
Salut,
Super surprenant.
Comment fais tu l'appairage ? Pour le capteur mouvement ? Pour Prise ?

Peux tu faire un appairage prise et partager le log AbeilleParser ?
Peux tu faire un appairage capteur mouvement et partager le log AbeilleParser ?

**Comment by waazdakka** [comment]
Bin je fais l'appairage de manière plutôt classique, je lance la découverte depuis Abeille, je mets la pile du capteur en gardant le bouton appuyé, et Abeille m'affiche son message de mise à jour de l'adresse à ce moment.
Je fais un AbeilleParser demain soir pour te remonter les logs. Merci :)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Pas de nouvelle je clos. Rouvres si besoin.
