### ISSUE TITLE
Plugin jeedom abeille - inclusion - Pizigate ne clignote pas

### ISSUE THREAD

**Issue by antarmc** [KiwiHC16/Abeille#793]
Salut,

Voici ma problématique : Pizigate ne clignote pas lors du lancement de l'inclusion.

Ma conf : 
Rpi3 Raspbian stretch sur MicroSD
Pizigate (firmware ?) + abeille (Version 2019-08-17 01:01:06 version jeedom 3.1.7) port Cubiboard (/dev/ttyS0)
Jeedom 3.3.33

Mes tests de debug : 
1)ruche visible : clic bouton version : aucune réaction
2)un seul plugin utilisant ce port tty0
3) test de mise en inclusion en ligne de commande ssh, resultat : 
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyUSB0
4) je vois bien passer du traffic en écoute : 1 ligne en exemple : 
000002a0  7e 80 98 66 66 1e 66 98  1e 86 98 7e e6 80 98 80  |~..ff.f....~....|
5) equipements zigbee : désolé je n'ai pas compris ce qu'il fallait faire

Log inquietant :

[logs.zip](https://github.com/KiwiHC16/Abeille/files/3722164/logs.zip)

Abeille parser : 
PHP Warning:  Missing argument 2 for Tools::deamonlogFilter(), called in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 174 and defined in /var/www/html/plugins/Abeille/resources/AbeilleDeamon/lib/Tools.php on line 64

merci de votre aide
gg guys

**Comment by KiwiHC16** [comment]
1) Log PHP Warning, je vais publier une nouvelle version Abeille qui corrige ce point.
2) Est ce qu'après cette commande
```
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyUSB0
```
la zigate clignote ?

Peux tu faire un ls -l /dev/ttySO en ssh ?

**Comment by antarmc** [comment]
Après la commande echo : pas de clignotement (ni juste après l'envoi de la commande,ni en inclusion)

Seconde commande : ls: cannot access '/dev/ttySO': No such file or directory

Antar

**Comment by antarmc** [comment]
En relisant ce que j'écris je me rends compte de l'erreur dans la commande il y a O à la place du 0
Voici le résultat avec la bonne commande : crwxrwxrwx 1 root dialout 4, 64 Oct 13 17:41 /dev/ttyS0
Mais toujours pas de clignotement.

**Comment by KiwiHC16** [comment]
Tu fais bien un 

```
echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyS0
```

ttyS0 et pas ttyUSB0 

Est ce que ca clignote maintenant ?

**Comment by antarmc** [comment]
Oui c est ce que j ai fait (copier coller)

Pas de clignotement...

Antar

Message envoyé depuis un mobile.

________________________________

**Comment by antarmc** [comment]
Ah j ai sans doute fait l erreur sans relire le ttys0

Je teste tout à l heure merci

Message envoyé depuis un mobile.

________________________________

**Comment by antarmc** [comment]
Voici le message retourné par le PI à echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyS0

-bash: echo: write error: Input/output error

**Comment by KiwiHC16** [comment]
Es tu root quand tu fais le test ?

**Comment by antarmc** [comment]
j'avais essayé avec sudo devant la commande : sudo echo -ne '\x01\x02\x10\x49\x02\x10\x02\x14\xb0\xff\xfc\xfe\x02\x10\x03' > /dev/ttyS0
echo: write error: Input/output error
désolé je n'y connais rien en commandes linux donc c'est du chinois pour moi tout ca, j'aimerais bcp aider mais je ne sais pas faire...

**Comment by KiwiHC16** [comment]
write error: Input/output error
Cela veut dire que Linux ne peut pas ecrire sur le port. Il ne peut pas parler à la zigate.
Donc il faut absoluement résoudre ca en premier.
As tu suivi ces explications:: https://jeedomiser.fr/article/pilotez-vos-appareils-zigbee-avec-la-pizigate/

**Comment by antarmc** [comment]
yes c'est que j'ai fait, je viens de tout reprendre et tout est ok.
et viens de me rendre compte que j'ai fais le boulet de compétition : le port utilisé est ttyAMA0 et ce n'est pas celui que j'utilise dans tous mes tests...
forcément avec le bon port tout fonctionne nettement mieux. désolé du temps que je t'ai fait perdre.
j'ai néanmoins une chose anormale c'est le temps de reboot de mon jeedom depuis l'install du pizigate : 11 minutes montre en main... Une idée ?
Merci encore

**Comment by KiwiHC16** [comment]
Perso, la presence de la PiZigate ne change absoluement rien au temps de boot sur mes systemes

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Suite sur #809.
Je clos celui ci.
