### ISSUE TITLE
Systeme Biscwii

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#796]
https://community.jeedom.com/t/probleme-inclusion-xiaomi-abeille-pizigate-perte-connexion/3162/3

**Comment by KiwiHC16** [comment]
```
J’utilise depuis quelques semaines des détecteurs d’ouverture Xiaomi/Mijia, un capteur de fumée Xiaomi/Honeywell, une Pizigate installée sur un Raspberry PI 3B+, ainsi que le plugin abeille.

Tout fonctionnait parfaitement pendant quelques jours/semaines, jusqu’au jour ou je me suis rendu compte que le détecteur de fumée ainsi que 2 détecteurs d’ouverture avaient perdu la connexion avec jeedom. C’était peu étonnant, ces 3 appareils étaient situés plutot loin de la Pizigate, et je n’ai encore aucun appareil actif qui pourrait améliorer le maillage.
```

Peux tu partager une capture d'ecran de la Santé et NetworkList/Table des Noeuds pour voir l'ensemble de ton réseau ?

**Comment by biscwii** [comment]
Salut KiwiHC16,
Depuis mon message, j'ai de plus en plus mis en doute le fonctionnement de la PiZigate. Pour une raison que j'ignore, celle ci refusait d'inclure de nouveaux capteurs (le problème était le même avec Abeille, et le plugin Zigate). Pour vérifier ma théorie, j'ai commandé une Zigate USB, et là, comme par magie, j'ai pu réinclure sans aucun problème tous mes détecteurs. Il ne s'agit donc pas d'un problème du plugin Abeille. Je vais continuer d'investiguer dans un topic relatif à PiZigate maintenant.

Merci beaucoup

**Comment by KiwiHC16** [comment]
Ok je clos le sujet alors.
