### ISSUE TITLE
Legrand Interrupteur Départ/Arrivée Entrée/Sortie Sur Pile (ZLE21 / 18W16)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#797]
https://community.jeedom.com/t/plugin-abeille-pour-la-zigate-zigbee/2774/28

**Comment by KiwiHC16** [comment]
Peux tu partager toutes les informations que tu as sur le sujet ?
Comment as tu fait l'inclusion ?
Comment apparait il dans Abeille ? (capture ecran)
Logs ?

**Comment by mulbuck** [comment]
j'ai appuyé longtemps sur le bouton reset (à côté de la led), jusqu'à ce que la LED passe en rouge permanent. 
Inclusion dans abeille
encore bouton reset, jusqu'à ce qu'il passe en vert en vert quand abeille l'a vu.
Le problème c'est qu'il est vu comme une télécommande départ arrivée.
Les 2 boutons sont vu comme on/off, mais pas de retour de polling me semble-t-il.
En tout cas, le fonctionnement n'est pas le même que sans fil.
Je te joins la vue dashboard, et les toutes les commandes
Pas de log pour le moment, il faut que je le sorte et reintègre.

![Legrand dashboard](https://user-images.githubusercontent.com/56731443/67105135-7a5a4400-f1c8-11e9-82d5-1be80d3aab9e.png)
![Legrand commandes 1](https://user-images.githubusercontent.com/56731443/67105140-7e866180-f1c8-11e9-9ec5-fccc860237ce.png)

![Legrand commandes 2](https://user-images.githubusercontent.com/56731443/67105145-834b1580-f1c8-11e9-8782-2e3dfae7988d.png)
![Legrand commandes 3](https://user-images.githubusercontent.com/56731443/67105154-880fc980-f1c8-11e9-85a2-403a55b370ef.png)
![Legrand commandes 4](https://user-images.githubusercontent.com/56731443/67105158-8b0aba00-f1c8-11e9-8e02-bcd316170ed3.png)
![Legrand commandes 5](https://user-images.githubusercontent.com/56731443/67105160-8e05aa80-f1c8-11e9-83d4-6196af1ac923.png)

**Comment by pipiche38** [comment]
L'inter sans fil Simple ou Double Gang se comporte de 2 façons
- par defaut l'etat de l'inter est communiqué via le cluster 0x000f sur l'attribut Present Value
- La partie Long press et release via le message 0x8085

- Si on bind les clusters de l'inter avec la Zigate alors il y a également retour via le 0x8095

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Merci Pipiche pour les infos. Je regarderai des que je peux.

**Comment by mulbuck** [comment]
Hello, 

voici le log en debug du parser quand j'ajouter l'interrupteur sans fil Legrand.
Veux-tu un autre fichier de log?
Mulb
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3775062/AbeilleParser.txt)

**Comment by pipiche38** [comment]
> Merci Pipiche pour les infos. Je regarderai des que je peux.

@KiwiHC16 ci-après les définitions (Nom de modèle et liste des clusters) que j'ai pour les 3 sans fils :

L'entrée c'est le nom de modèle 0x0000/0x0005

`    "Remote switch":{"Ep":{  "01":{"0000":"","0003":"","000f":"","0020":"","0001":"","fc01":"","0003":"","0006":"","0008":"","0000":"","0019":""}}},`
```
    "Double gangs remote switch":{"Ep":{
"01":{"0000":"","0003":"","000f":"","0020":"","0001":"","fc01":"","0003":"","0006":"","0008":"","0000":"","0019":""},
"02":{"0003":"","000f":"","0006":"","0008":""}}},
```
```
    "Shutters central remote switch":{"Ep":{
"01":{"0000":"","0001":"","0003":"","0102":"","000f":"","fc01":"","0019":"","0020":""}}},
```

**Comment by KiwiHC16** [comment]
Dans Abeille Paerser si dessus:
```
NE: {"eb2c":{"IEEE":"0004740000ab2d39","capa":"80","timeAnnonceReceived":1572105470,"state":"configuration","action":"modelIdentifierReceived->configuration","EP":"01","modelIdentifier":" Remote switch\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}}
```

```
[2019-10-26 17:57:57][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 3b; Src Addr : eb2c; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 001f; Data byte list : -> Remote switch<-

[2019-10-26 17:57:57][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); SQN: 3c; Src Addr : eb2c; End Point : 01; Cluster ID : 0000; Attr ID : 0010; Attr Status : 86; Attr Data Type : ff; Attr Size : 0000; Data byte list : -><-
```

**Comment by KiwiHC16** [comment]
J'ai un modele pour RemoteSwitch avec comme commentaire: "Legrand Télécommande Depart Arrivée"

**Comment by KiwiHC16** [comment]
Comme elle sert a activer l inclusion de la GW Legrand je ne pas passer plus de temps dessus au risque de perdre la GW.
Sinon elle commande des scenes (voir les notes).

**Comment by KiwiHC16** [comment]
.

**Comment by KiwiHC16** [comment]
.
