### ISSUE TITLE
Erreur "Class 'object' not found" lors de l'accès au plugin

### ISSUE THREAD

**Issue by arnaud-coral** [KiwiHC16/Abeille#798]
Bonjour,

Suite à l'installation d'Abeille, j'obtiens une erreur "Class 'object' not found" lorsque je tente d'accéder au plugin.

![image](https://user-images.githubusercontent.com/38693862/66940837-eeb8aa00-f045-11e9-816a-ca4606e59ba5.png)

Je n'ai pas observé d'erreur pendant l'installation du plugin, ni des dépendances, tout semble au vert.

![image](https://user-images.githubusercontent.com/38693862/66940887-0ee86900-f046-11e9-9133-b276ae5c2b90.png)

J'ai eu un message comme quoi la ruche allait être créée : 

![image](https://user-images.githubusercontent.com/38693862/66940927-27588380-f046-11e9-9183-498f5675bafb.png)

Du côté des logs : 

Installation des dépendances : 
```
+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependancy_abeille_in_progress
+ echo 'Début d'\''installation des dépendances'
Début d'installation des dépendances
+ '[' '!' -z /tmp/jeedom/Abeille/dependance ']'
+ PROGRESS_FILE=/tmp/jeedom/Abeille/dependance
+ touch /tmp/jeedom/Abeille/dependance
+ echo 0
+ echo
+ echo 'Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement '
Avancement: 0% ---------------------------------------------------------------------------------------------------> Environnement
+ echo
+ echo 50
+ echo
+ echo 'Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.'
Avancement: 50% ---------------------------------------------------------------------------------------------------> Ajout au groupe dialout.
+ echo
+ echo '**Ajout du user www-data dans le groupe dialout (accès à la zigate)**'
**Ajout du user www-data dans le groupe dialout (accès à la zigate)**
++ groups www-data
++ grep -c dialout
+ [[ 1 -ne 1 ]]
+ echo 'OK, utilisateur www-data est déja dans le group dialout'
OK, utilisateur www-data est déja dans le group dialout
+ echo 100
+ echo
+ echo 'Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN'
Avancement: 100% ---------------------------------------------------------------------------------------------------> FIN
+ echo
+ rm /tmp/jeedom/Abeille/dependance
```

Suite à réinstallation du plugin : 
```
[2019-10-16 18:46:35][INFO] : Début d'activation du plugin
[2019-10-16 18:46:36][INFO] : Info sur le démon : {"launchable_message":"","launchable":"nok","state":"nok","log":"nok","auto":0}
[2019-10-16 18:46:36][DEBUG] : Lancement de : /var/www/html/core/class/../../core/php/jeePlugin.php  plugin_id=Abeille function=install callInstallFunction=1
```

Côté système : 
- Raspberry Pi 3B
- Raspbian 9.11 fresh install
- Jeedom 4.0.23 fresh install
- Abeille version latest

Est-ce que quelqu'un aurait déjà reproduit ce problème, et aurait éventuellement une solution ou une piste ?

Merci !!

**Comment by arnaud-coral** [comment]
J'ajoute ce que je viens de trouver dans le log http.error : 

```[16-Oct-2019 18:59:21 Europe/Brussels] PHP Fatal error:  Uncaught Error: Class 'object' not found in /var/www/html/plugins/Abeille/plugin_info/configuration.php:90
Stack trace:
#0 /var/www/html/core/php/utils.inc.php(67): require_once()
#1 /var/www/html/index.php(65): include_file('plugins/Abeille...', 'configuration.p...', 'configuration', 'Abeille')
#2 {main}
thrown in /var/www/html/plugins/Abeille/plugin_info/configuration.php on line 90
tail: cannot open '/var/www/html/core/class/../../log/starting' for reading: No such file or directory```

**Comment by KiwiHC16** [comment]
Salut,
Ok interessant le log, je vais pourvoir regarder dans le code.
Pour info je n'ai pas encore testé la V4 Jeedom avec Abeille.
Debian 10 (buster) — current stable release
Debian 9 (stretch) — oldstable release
Donc tu es sur la derniere mise a jour de Debian 9. Il faut que je regarde sur mes systemes quelle version est utilisée.

Pourrais tu mettre en commentaire les lignes 90, 91 et 92:
```
  foreach (object::all() as $object) {
                                    echo '<option value="' . $object->getId() . '">' . $object->getName() . '</option>';
                              }
```

dans le fichier /var/www/html/plugins/Abeille/plugin_info/configuration.php

et me dire si la page s'ouvre ?

**Comment by arnaud-coral** [comment]
Hello,

Pour info, j'avais testé un upgrade de Stretch vers Buster, mais le résultat a été catastrophique.
J'ai été un peu trop optimiste car la doc Jeedom mentionne bien que la version supportée est bien la 9 et pas encore la 10, le core ne semble pas stable sous Buster (dépendances non satisfaites). 

D'où l'installation toute neuve et le passage de Jeedom 3 vers 4 ;-)

Je viens de tester en commentant le code mentionné, mais le problème persiste hélas.

![image](https://user-images.githubusercontent.com/38693862/66988388-ba370380-f0c2-11e9-8ef1-94a202ee45c7.png)

Quelque chose à regarder ce ce côté là peut-être ?

```
tail: cannot open '/var/www/html/core/class/../../log/starting' for reading: No such file or directory
```

**Comment by arnaud-coral** [comment]
Correction confirmée en appliquant le fix [#799](https://github.com/KiwiHC16/Abeille/pull/799)
