### ISSUE TITLE
ZiGate ne transmet pas les groupes correctement 

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#80]
Après avoir ajouté 2 ou 3 groupes dans une ampoule IKEA, si je demande la liste , je reçois une liste mais seul le premier terme est valide.

![capture d ecran 2018-02-04 a 21 51 24](https://user-images.githubusercontent.com/8549674/35782385-8398ebf8-09f7-11e8-92ba-0b433db05b8b.png)
![capture d ecran 2018-02-04 a 21 51 35](https://user-images.githubusercontent.com/8549674/35782386-83b2e56c-09f7-11e8-9b91-dee23dfba25a.png)
![capture d ecran 2018-02-04 a 21 51 43](https://user-images.githubusercontent.com/8549674/35782387-83cbca78-09f7-11e8-9682-c1420da8b629.png)
![capture d ecran 2018-02-04 a 21 51 56](https://user-images.githubusercontent.com/8549674/35782388-83e39162-09f7-11e8-91ef-b7d1789b774e.png)
![capture d ecran 2018-02-04 a 21 54 03](https://user-images.githubusercontent.com/8549674/35782389-83fbd57e-09f7-11e8-9e45-4c6d3cd42d57.png)
![capture d ecran 2018-02-04 a 21 54 10](https://user-images.githubusercontent.com/8549674/35782390-84143038-09f7-11e8-8a77-88cc6b89f928.png)
![capture d ecran 2018-02-04 a 21 54 17](https://user-images.githubusercontent.com/8549674/35782391-842f1d3a-09f7-11e8-837b-dcd5ffa14a3b.png)
![capture d ecran 2018-02-04 a 21 54 23](https://user-images.githubusercontent.com/8549674/35782392-8447d87a-09f7-11e8-8735-d6d93bfea7fc.png)

**Comment by fairecasoimeme** [comment]
Fix in next version 3.0d

**Comment by KiwiHC16** [comment]
Les groupes remontent correctement maintenant. Le parser decodage doit etre revu.
Exemple ampoule IKEAalors qu'il n'y a que le groupe "5fbd":

AbeilleParser 2018-02-22 13:36:13[DEBUG]-------------- 2018-02-22 13:36:13: protocolData size(32) message > 12 char
AbeilleParser 2018-02-22 13:36:13[DEBUG]Type: 8062 quality: b7
AbeilleParser 2018-02-22 13:36:13[DEBUG]Type: 8062: (Group Memebership)(Decoded but Not Processed)
AbeilleParser 2018-02-22 13:36:13[DEBUG]payload length: 22
AbeilleParser 2018-02-22 13:36:13[DEBUG]group part of the payload length: 8
AbeilleParser 2018-02-22 13:36:13[DEBUG]SQN: 60
AbeilleParser 2018-02-22 13:36:13[DEBUG]endPoint: 01
AbeilleParser 2018-02-22 13:36:13[DEBUG]clusterId: 0004
AbeilleParser 2018-02-22 13:36:13[DEBUG]capacity: 0C
AbeilleParser 2018-02-22 13:36:13[DEBUG]group count: 16
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 0(addr:12): ff01
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 1(addr:16): 5fbd
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 2(addr:20): b7
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 3(addr:24): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 4(addr:28): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 5(addr:32): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 6(addr:36): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 7(addr:40): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 8(addr:44): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 9(addr:48): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 10(addr:52): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 11(addr:56): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 12(addr:60): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 13(addr:64): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 14(addr:68): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 15(addr:72): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 16(addr:76): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 17(addr:80): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 18(addr:84): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 19(addr:88): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 20(addr:92): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]group 21(addr:96): 
AbeilleParser 2018-02-22 13:36:13[DEBUG]Level: 0xb7

**Comment by KiwiHC16** [comment]
Je clos car sera couvert dans le cas #72
