### ISSUE TITLE
Comprendre timeout, petite question (pas un bug)

### ISSUE THREAD

**Issue by Dites33** [KiwiHC16/Abeille#803]
1 / Dans ma maison, grace à toi ;) j'ai maintenant 14 ampoules E14, E27 IKEA, 2 ampoules AQARA Xiaomi et 4 spots GU10 Ikea

Une grande partie de ces ampoules se trouvent sur des plafonniers ou des lampes ayant déjà un interrupteur physique.

Je remarque que si j'éteint physiquement une lampe, l'état dans Abeille reste inchangé. Cela m'embete un peu car j'aimerai qu'Abeille,sur ces équipements là, essayent de les contacter et si ils ne répondent pas, passent en OFF ou en ON si au contraire ils sont allumés :)

Est ce possible ?

2 / Mes capteurs de températures sont des Aqara. Ils ne remontent une info que si la température varie. Si elles ne varient pas pendant plus d'une heure (ca arrive), le capteur passe en rouge dans Jeedom (au niveau de l'affichage), comment puis je dire à Abeille de ne passer en rouge que si le timeout est supérieur à 24h par exemple ? Je change la zone timeout dans chaque équipement ? Ca suffit ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut,
1/ "si j'éteint physiquement une lampe": Dans ce cas la lampe n'a plus d'electricité et donc n'envoit pas d'information à Jeedom. Actuellement elles sont interegées toutes les 15 minutes et si elles ne repondent pas alors elles passent en timeout (En rouge). Je ne peux pas trop faire plus car si elle ne repond peut avoir plusieurs raisons autre que "éteint physiquement". Donc je ne supporte pas trop ton approche. Le principe est que les ampoulent sont aussi des routeurs donc les éteindre n'est pas une bonne idée. Le mieux serait d'enlever les interrupteur physique et mettre des télécommandes.

2/ Oui normalement tu changes le TimeOut. Mais je dois dire ne pas l'avoir trop testé. Essayes et tiens moi au courant. Normalement il y a un message toutes les heures donc si ca passe en rouge cela veut dire que le capteur n'arrive pas a parler a la zigate, tu as un probleme radio (peut etre as tu eteins une ampoule et elle ne route plus et le capteur n est plus dans le reseau).

**Comment by Dites33** [comment]
MErci @KiwiHC16  pour tes réponses. 

Quand tu passes une ampoule en timeout, pourrais tu à minima passer l'état à ETEINTE ? Vu que tu n'arrives pas à contacter l'ampoule pour connaitre son état, l'a laisser sur ALLUMEE ce n'est pas très pertinent non plus vu que dans beaucoup de cas, si tu as un timeout c'est que l'ampoule n'est pas dans le réseau donc que tu ne peux pas savoir l'état.Il me semble que toutes les infos devraient repasser à null ou 0 comme c'est le cas sur le plugin Zigate.

 Je n’enlève pas les interrupteurs physique car si mon serveur jeedom tombe (ca arrive), mes enfants ne pourraient plus allumer ou éteindre les lumières :(

**Comment by KiwiHC16** [comment]
Moi les interrupteurs sont cachés pour ne pas être utilisé sauf soucis.
La base d'Abeille est de refleter les infos reçues. Je ne fais pas d'interpretation pour coller au plus pret du systeme et ainsi laisser l'utilisateur procéder comme il veut.
TimeOut ne veut pas dire éteinte... Si je ne connais pas l'état pourquoi mettre éteinte alors qu'elle est peut être allumé et vice versa...
Typiquement j'ai une ampoule en limite de couverture qui ne recoit pas tous les messages et donc tombe en time out, je ne vois pas pourquoi je changerai l'état...
Si tu souhaites ce mode de fonctionnement utilises les scenarii.

**Comment by Dites33** [comment]
Je comprends parfaitement @KiwiHC16. Si tu ne sais pas si elle est eteinte ou allumée tu restes dans l'état précedent. Je suis d'accord. J'essaye juste de voir comment je peux me débrouiller ;)

Tu me parles de scenarii, as tu un petit exemple 

Mon souhait c'est que si une ampoule ne réponds pas pendant x minutes alors je la passe etat OFF.

**Comment by KiwiHC16** [comment]
Tu peux faire un scenario declenché sur la commande Online de l'ampoule.
Regardes #788

**Comment by KiwiHC16** [comment]
Je clos. Rouvres si besoin.
