### ISSUE TITLE
RPi boot tres lent

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#809]
J’enchaine sur une autre question : depuis l’install de abeille et de pizigate mon jeedom est tres lent a booter : 12 minutes !

Si je désactive le plugin c’est pareil et si je retire physiquement le pizigate aussi.

Une piste d’analyse du phénomène svp ?

**Comment by KiwiHC16** [comment]
Peux tu partager le resultat des commandes (en ssh):
```
sudo cat /var/log/syslog
```
et
```
sudo dmesg
```

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by antarmc** [comment]
Voici les logs demandés. Merci pour ton suivi.

[dmesg.txt](https://github.com/KiwiHC16/Abeille/files/3775966/dmesg.txt)
[syslog.txt](https://github.com/KiwiHC16/Abeille/files/3775967/syslog.txt)

Je viens de constater que mon pb de lenteur au boot ne se produit qu'au second reboot.
Le premier a duré une bonne minute pas plus.

Je rajoute donc les logs juste après ce second reboot très lent :

[dmesg2.txt](https://github.com/KiwiHC16/Abeille/files/3776001/dmesg2.txt)
[syslog2.txt](https://github.com/KiwiHC16/Abeille/files/3776002/syslog2.txt)

Je vois que le syslog est tellement long qu'il a été tronqué au début dans le SHH de putty à l'écran.

**Comment by KiwiHC16** [comment]
Désolé, je ne vois pas.
Les deux dmesg donne un lancement du core en 7s et a 665 lancement du Bluetooth;
Pour la PiZigate on pique le port serie du bluetooth donc soit il faut desactiver le bluetooth ou le reconfigurer. C est dans la doc. Mais dans les deux semblent se comporter de la même façon.

Il faudrait que tu partages les heures de reboot et comme le reboot a ete effectué.
Dans le premier syslog pas de reboot mais de plaintes: "ramlog: Previous shutdown/restart was unclean, "
Pour le second ,reboot a 14:42:24:
```
Oct 27 14:43:58 raspberrypi wifi-country[326]: Could not determine WiFi iomem address
Oct 27 14:43:58 raspberrypi systemd[1]: wifi-country.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 14:43:58 raspberrypi systemd[1]: Failed to start Disable WiFi if country not set.
```
et semble reboot encore à  14:43:58 sans prévenir.

Puis
```
Oct 27 14:44:10 raspberrypi ntpd[593]: Soliciting pool server 95.81.173.74
```
et pas de reponse pendant 10 minutes
```
Oct 27 14:53:22 raspberrypi ntpd[593]: 95.81.173.8 local addr 192.168.0.252 -> <null>
``` 

Est ce que le RPI est en Wifi sur le reseau ? 
Est ce que l'alimentation est suffisante (reboot spontané).

**Comment by antarmc** [comment]
Il n'y a pas eu de reboot spontané, ce que tu lis donc dans les logs me surprend beaucoup...
Je vais renouveler les reboots et te spécifier les heures précises de déclenchement et te filer les logs demandés.
L'alim est suffisante, 3A de mémoire, j'ai suivi les précos.
Le rpi n'est pas en wifi mais en filaire.

**Comment by KiwiHC16** [comment]
Salut Antarmc,
Je ne peux pas trop supporter tous les cas lorsqu'ils sont en dehors du plugin lui meme. 
Je n'ai pas assez de temps pour tout.
J'essaye de me focaliser sur Abeille.
Je clos le sujet.
Si tu as du nouveau rouvre le.
