### ISSUE TITLE
Erreur d'index non défini dans les logs

### ISSUE THREAD

**Issue by Dites33** [KiwiHC16/Abeille#812]
J'ai cette ligne dans le log qui revient tout le temps, pas grave mais à corriger sur la prochaine release peut être ;) 

PHP Notice:  Undefined index: d4 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 2559

**Comment by Dites33** [comment]
Je rajoute : 

PHP Notice:  Undefined index: Proprio in /var/www/html/plugins/Abeille/core/class/AbeilleMQTTCmd.php on line 2579
PHP Notice:  Undefined index: Proprio in /var/www/html/plugins/Abeille/core/class/AbeilleMQTTCmd.php on line 1648

**Comment by KiwiHC16** [comment]
Ok pour "PHP Notice: Undefined index: d4" je viens d'ajouter un commentaire dans le code mais faudrait investiguer plus.

Modifié le code pour 2579 et 1648.

Je ne clos pas car il faut encore tester.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/207

**Comment by KiwiHC16** [comment]
Semble Ok Je clos.
