### ISSUE TITLE
Modules IKEA, scenario avec de multiples modules

### ISSUE THREAD

**Issue by bouboun59** [KiwiHC16/Abeille#813]
Bonjour,

j'ai remarqué un souci avec abeille et les modules ikea.
En effet j'ai un scénario qui allume/éteint des lumières : scénario ambiance, avec 4 modules Ikea différents.
2 transfos lampe led (tradfi)
2 prise ikea

Et au final seul 3 vont s'allumer, j'ai donc du découper mes scénarios avec 1 minute de latence.
Les scénarios s'active à 19h00 et 19h01 (allumage),  et 23h00 / 23h01 (extension lumière).

cela résout mon problème par rapport aux heures.

Cependant quand j'utilise Alexa, en disant allume la lumière d'ambiance, j'ai toujours un des modules qui reste éteint donc je dois demander l'action plusieurs fois à l'Alexa....

tout cela n'est pas pratique, j'aimerais donc savoir pourquoi on ne peut pas envoyer plus de 3 ordres au final en même temps ?

merci

JEEDom 4.0.25
Version Abeille : Stable 15/10/2019
Module ZIGATE GPIO RASPBERRY 3 B

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Jeedom en V4 .... y en a qui aime le risque mais ca montre aussi que ca fonctionne (pas encore eu le temps de tester).

Interessant de voir qu'Abeille fonctionne avec Alexa ;-)
Je ne le savais pas.

Ton problème provient d'un nombre trop élévé de demandes que le réseau ne peut gérer. Une demande Alexa, 4 messages vers le reseau. Cela provient du fait qu'Abeille ne fait pas de gestion de flux. Il faudra probablement que le le fasse un jour.

Une solution est de n'envoyer qu'un message Zigbee. Pour ce faire créer (ou utiliser une telecommande) avec toutes les ampoules dans ce groupe. Et piloter la telecommande depuis Alexa.

http://kiwihc16.free.fr/Groups.html

**Comment by KiwiHC16** [comment]
Le probleme des trop grand nombre de messages doit etre géré maintenant dans la version master. Mais comme il y beaucoup de changement il va falloir pas mal de tests pour confirmer que tout va bien.

**Comment by bouboun59** [comment]
J'ai fait un bouton en attendant, cependant parfois le problème se produit, une des lampes ne s éteint pas, mais c'est moins fréquent.

Pour Jeedom V4 stable, pour le moment cela fonctionne bien à part quelques bugs d'affichage

**Comment by KiwiHC16** [comment]
Je viens de faire des modifications sur la gestion d envoie des commandes à la zigate pour améliorer cet aspect.  C est en cours et sera dans la prochaine stable. Mais c est touchy donc il faut que je teste le plus possible avant De donner ça à tout le monde et de tout planter.

**Comment by KiwiHC16** [comment]
La Zigate a une limite quand on a un burst de commandes qui arrive. J'ai fait évolué le plugin pour gérer cette situation. Cela n'assure pas la simultanéité des actions car par des recherches de route peuvent avoir lieu et introduire un delai de quelques secondes. Mais tout doit s'allumer. Pour la simultaniité il faut passer par les groupes.

**Comment by KiwiHC16** [comment]
Je clos le sujet car dans master. Mais si le probleme reste on rouvrira un cas.
