### ISSUE TITLE
homebridge setlevel du transfo 30W d'IKEA

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#814]
Autre petit truc, ton plugin fonctionne correctement avec homebridge (mieux que le ... en tout cas), mais avec quelques soucis quand même :

- le setlevel du transfo 30W d'IKEA ne se met pas à jour instantanément, il faut attendre au moins 10sec pour qu'il s'actualise. Je remarque ce problème quand j'utilise la télécommande 5 boutons IKEA qui pilote ce transfo et 2 autres ampoules IKEA GU10. Si par exemple, je diminue la puissance avec la télécommande, la lumière diminue, les valeurs sont actualisées tout de suite dans jeedom pour les 2 ampoules, mais pas le transfo, et dans l'app Maison. Avant d'avoir Jeedom, j'utilisais la passerelle IKEA, tout fonctionnait normalement avec, le retour d'état dans l'app Maison était instantané pour les 3 équipements.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Très vieux sujet et plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
