### ISSUE TITLE
Homebridge sonde temperature

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#815]
- j'ai des sondes t°/HR/Pression AQARA carré, je demande à remonter une seule des 2 pressions disponible avec le capteur. Dans l'appli EVE, j'ai systématiquement les 2 valeurs de pression de la sonde qui remontent.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-10-29 à 21 21 57](https://user-images.githubusercontent.com/8549674/67805890-26860f80-fa92-11e9-992e-ac54d9e1d855.png)

As tu une des commande pression sur la bonne valeur et l'autre sur aucun ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-10-29 à 21 23 15](https://user-images.githubusercontent.com/8549674/67805980-53d2bd80-fa92-11e9-943b-8b866ac9f033.png)

Comme ici le dernier est sur aucun. La sonde remonte deux fois la meme info... Tu choisis celle que tu veux.

**Comment by Brugal21** [comment]
Voila la config d'une sonde carré AQARA.

Les commandes de l'équipement, avec les 2 valeurs de pression : 

![image](https://user-images.githubusercontent.com/55110607/67897465-b7c2b800-fb5e-11e9-8b73-7d0b5f2ad6a6.png)

Le détail de la commande pression : 

![image](https://user-images.githubusercontent.com/55110607/67897582-fe181700-fb5e-11e9-8191-634232e2baee.png)

Le détail de la commande pression 1 : 

![image](https://user-images.githubusercontent.com/55110607/67897658-2b64c500-fb5f-11e9-9b13-acff5247bdf7.png)

Et le paramétrage de l'équipement dans homebridge : 

![image](https://user-images.githubusercontent.com/55110607/67897795-67982580-fb5f-11e9-90e6-a082d6f0e12b.png)

Et ce que j'obtiens dans EVE ;

![image](https://user-images.githubusercontent.com/55110607/67898316-674c5a00-fb60-11e9-8533-fe08062772c2.png)

**Comment by KiwiHC16** [comment]
La je pense que c'est un bug homebridge car ce n'est pas la premiere fois que voit un non alignement entre les valeurs dans le device et la valeur dans le recap homebridge.
Je vais demander de l'aide au dev de homebride

**Comment by KiwiHC16** [comment]
https://community.jeedom.com/t/type-generique-dans-commande-different-du-type-generique-dans-hombridge/6033

**Comment by KiwiHC16** [comment]
@Brugal21, peux tu faire la manipulation proposé par nebz dans le forum jeedom ?

**Comment by Brugal21** [comment]
Salut,

j'ai pas tout compris à ce que disais nebz... mais j'ai cru comprendre que le type générique inscrit pour la commande pression 1 (Météo Pression) n'était pas adapté.
Du coup j'ai modifié le type générique de la commande pression 1 de toutes mes sondes AQARA par "aucun". J'ai redémarré le démon homebridge et c'est tout bon dans EVE ! J'ai maintenant bien qu'une  seule valeur de pression qui remonte :)

Bon, y a toujours pas les graphes...

Pour info, je pense que ce type générique vient avec la création automatique de l'équipement par l'abeille... donc voir dans le plugin pour ne pas mettre de type générique sur cette valeur ?

Merci kiwi, tu peux clore l'issue.

![Capture d%u2019écran%A0  2019-10-31 à 18 31 16](https://user-images.githubusercontent.com/55110607/67971305-d8e1e200-fc0c-11e9-946d-28c3361ed09b.png)

**Comment by KiwiHC16** [comment]
Ok super.

Vue Commande:
![Capture d’écran 2019-10-31 à 18 52 17](https://user-images.githubusercontent.com/8549674/67972745-9241b700-fc0f-11e9-94b6-aecb85d67050.png)

Vue Homebridge:
![Capture d’écran 2019-10-31 à 18 51 04](https://user-images.githubusercontent.com/8549674/67972692-79d19c80-fc0f-11e9-9cc3-57ac9c6a0911.png)

Info dans Jeedom:
![Capture d’écran 2019-10-31 à 18 53 04](https://user-images.githubusercontent.com/8549674/67972818-aeddef00-fc0f-11e9-8f19-b8991fffc6d7.png)

Et ce n'est pas celui de la station météo.

Modele changé.

**Comment by KiwiHC16** [comment]
Je clos.
