### ISSUE TITLE
avec les ampoules aqara que je n’arrive pas à mettre à 6500K

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#817]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Très vieux sujet et plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
