### ISSUE TITLE
Impossible d'ajouter des abeilles sur VM Freebox Delta 

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#819]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3793901/Abeille.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3793902/AbeilleParser.txt)

Bonjour,
Je viens de me prendre une seconde Zigate pour un second Jeedom sur une VM Freebox Delta (v4.0.25)
J'ai installé la version Master d'Abeille, démarré le réseau ZigBee, et fait une tentative d'inclusion. La clé clignote correctement, mais quand je fais un appairage sur mon capteur de température Xiaomi (qui est à 2 mètres de ma box), ce dernier ne se met pas à clignoter rapidement comme d'habitude en fin d'appairage, et l'objet n'apparait pas dans le plugin. 
Une idée?
Merci d'avance

**Comment by Soyann** [comment]
Ils sont au début du message :p

**Comment by Soyann** [comment]
Je viens de les réinitialiser, et je n'ai plus AbeilleParser, ni AbeilleMQTT. Quand je regarde Abeille, c'est pas très verbeu:
[2019-10-31 17:49:02][DEBUG] : Envoi du message topic: TempoCmdAbeille/Ruche/getVersion&time=1572540562 payload: Version vers 123
[2019-10-31 17:49:02][DEBUG] : Msg sent: {"message":{"topic":"TempoCmdAbeille\/Ruche\/getVersion&time=1572540562","payload":"Version"}} on queue: 123
[2019-10-31 17:49:02][DEBUG] : Envoi du message topic: TempoCmdAbeille/Ruche/getNetworkStatus&time=1572540566 payload: getNetworkStatus vers 123
[2019-10-31 17:49:02][DEBUG] : Msg sent: {"message":{"topic":"TempoCmdAbeille\/Ruche\/getNetworkStatus&time=1572540566","payload":"getNetworkStatus"}} on queue: 123
[2019-10-31 17:49:02][DEBUG] : Get etat and Level des ampoules
[2019-10-31 17:49:02][DEBUG] : Envoi du message topic: CmdAbeille/Ruche/permitJoin payload: Status vers 123
[2019-10-31 17:49:02][DEBUG] : Msg sent: {"message":{"topic":"CmdAbeille\/Ruche\/permitJoin","payload":"Status"}} on queue: 123

Pourtant, je suis bien en mode Debug...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Pardon, je n'avais pas vu les fichiers. Je regardes.

**Comment by KiwiHC16** [comment]
Dans abeille on voit que jeedom discute bien avec la zigate. Version soft 30F par exemple.
Mode inclusion en cours: ->Abeille/Ruche/permitJoin-Status<- Value ->01<-

Mais on ne voit pas de device qui s'annonce.

As tu demarré le réseau zigbee ?
Si tu n'as pas de device sur cette zigate essayes de faire un reset (bouton sur la ruche).
Si pas suffisent, fais un erase PDM (bouton sur la ruche), demarre le reseau, et fais l inclusion.

Tiens moi au courant.

**Comment by Soyann** [comment]
Merci
Le réseau ZigBee était bien démarré
Reset -> idem
Erase Persistent Data , Start ZigBee, inclusion -> idem :(

**Comment by Soyann** [comment]
J'ai testé la capteur sur mon ancienne gateway (histoire d'être certain que ce ne soit pas lui le fautif), il s'est enregistré comme un grand. J'ai également repassé le firmware 3.0f, histoire de, (j'ai bien redémarré le réseau après), mais pas plus concluant. snif

**Comment by KiwiHC16** [comment]
Tu dis avoir mis le master. Peux tu essayer avec la derniere version stable ?

**Comment by Soyann** [comment]
J'ai de gros problèmes avec la dernière version stable: comme dit ici https://github.com/KiwiHC16/Abeille/issues/787, je n'arrive à rien.
Par contre, je viens de faire un autre teste: j'ai désinstallé Abeille, mis l'autre plugin, fait une inclusion: ça marche.
J'ai désinstallé pour remettre abeille (toujours en master pour avoir les menus), et l'inclusion a marché!!!
Par contre (après une pause de 10 min), j'ai voulu remettre un autre capteur: le voyant ne clignote plus sur la zigate grrrrrrrrrrrr

**Comment by KiwiHC16** [comment]
Comme indiqué je n'ai pas encore travaillé sur la V4.

**Comment by Soyann** [comment]
Arf, les VM Delta ne sont qu'en v4, et j'avoue avoir hâte de migrer ma machine en prod, car c'est une belle évolution. Donc si tu cherches un cobaye, ce sera avec plaisir.

**Comment by KiwiHC16** [comment]
Quel est l OS sur les VM Delta ?

**Comment by Soyann** [comment]
Linux Jeedom-Delta 4.19.0-6-arm64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) aarch64

Si tu veux un accès https + ssh à une VM rien que pour toi, je peux t'envoyer ça par mail ;)

Merci beaucoup

**Comment by KiwiHC16** [comment]
Bien venu pour tester. Je fais tourner une VM Debian 10 avec Jeedom V4 maintenant, j'ai corrigé 3 bugs. J'en cherche d 'autres.

**Comment by KiwiHC16** [comment]
Super, des que je recois to mail je regardes.

**Comment by Soyann** [comment]
hello, eh tu n'as pas reçu mon mail nocturne avec des identifiants?

**Comment by Soyann** [comment]
je viens de voir que je ne l'ai pas envoyé de la bonne boite, mais tu as normalement reçu un truc vers 2h18

**Comment by Soyann** [comment]
j'ai appliqué l'update du master, refait un essai à 12h12 -> idem: le capteur n'est pas détecté

**Comment by KiwiHC16** [comment]
Oui mail bien recu mais perdu dans la masse. Je viens de te repondre.

**Comment by Soyann** [comment]
Dispo si besoin d'appuyer sur les boutons d'appairage :p

**Comment by KiwiHC16** [comment]
Peux tu mettre la derniere master et me dire quand ok pour que je me connecte.

**Comment by Soyann** [comment]
En cours

**Comment by Soyann** [comment]
Je viens de faire un essai: pas mieux :(

**Comment by Soyann** [comment]
Et même moins bien: Attention [Test][Ruche] n'a pas envoyé de message depuis plus de 15 min (vérifiez les piles)

**Comment by Soyann** [comment]
Hello, je viens de finir de mettre en place un système d'échange (que je pense pratique et interactif) directement depuis ma VM. N'hésite pas à t'en servir. En te remerciant de nouveau et en espérant que tout rentrera rapidement dans l'ordre. Bon courage ++

**Comment by KiwiHC16** [comment]
Je suis encore sur un soucis de traitements des messages en interne au plugin. Je crois que c est le dernier probleme vraiment bloquant. Je travaille dessus apres on pourra certainement faire des tests.

**Comment by Soyann** [comment]
N'hésites surtout pas à faire signe (via ma VM) quand tu es opé, je suis comme un gamin qui attend de croiser le père noël!

**Comment by KiwiHC16** [comment]
Salut, je suis encore tombé (dans la cheminée) sur un cas, je viens de pousser la modif. On ne doit pas être loin d'un truc fonctionnel .

**Comment by Soyann** [comment]
Hello, Ayant coupé ma nuit en 2, j'ai fais un essai à 4h du mat avec (du coup) l'avant dernière version du Master, et j'ai réussi à inclure le capteur de température!!! par contre, mon capteur de mouvements et deux capteurs d'ouverture font toujours la sourde oreille (grrrr), de plus j'avais toujours les messages de timeout sur la ruche (mais les valeurs de températures se mettaient bien à jour). Je viens d'appliquer l'update, et c'est pas mieux :( (aussi bien pour l'inclusion que pour les messages me demandant de vérifier les piles de la ruche... je veux bien, mais il faut m'expliquer où elles sont :p ). Courage, tu progresses, et suis certains que d'ici peu, tu réussiras à dompter cette bête sauvage!

**Comment by KiwiHC16** [comment]
Ok je vais essayer pour voir sur mon systeme. J'espere cet apres midi.

**Comment by KiwiHC16** [comment]
Salut Soyann,
Je viens de tester avec V4 VM  avec le master et je viens d'inclure Xiaomi vibration, temperature V1 & V2, Inondation, Door, IR V1,... sans soucis.
Je crois que c'est une version qui va pouvoir avoir droit au market en stable dans quelque temps.
Je laisse tourner encore mes deux systemes quelques jours.
En début de seamine je pourrais peut être me connecter sur ton systeme. Peux tu mettre la derniere master si pas deja fait ?

**Comment by KiwiHC16** [comment]
Il faut peut être que je fasse les test avec le firmaware stable zigate avant toute chose...

**Comment by Soyann** [comment]
Peux-tu te connecter chez moi et regarder? (je ne vois pas de maj du master)

**Comment by Soyann** [comment]
Tu peux te connecter quand tu veux: tant que ça ne marche pas au poil, c'est open bar pour toi dessus; de toute façon, une fois que ce sera nickel, j'en créerai une autre 'propre' pour mettre en prod dans mon écosystème

**Comment by Soyann** [comment]
Comme indiqué sur le forum, je vais pour le moment laissé ma clé en V30F, le temps que tu finisses tes éventuels réglages (ma machine t'attend!), mais pour la suite, préconises-tu de passer en V31a? A-t-elle de réels avantages par rapport à la V30f (le changelog n'est pas très parlant pour moi)? Le fait de faire cette mise à jour implique-t-il un raz de la clé et donc un nouvel appairage des abeilles? Merci une fois de plus

**Comment by Soyann** [comment]
Bonsoir,
Excellente nouvelle, avec l'update du master du jour, j'ai réussi à inclure mes abeilles de test!!! Par contre, il a fallu que je m'y reprenne à plusieurs fois pour que certaines acceptent l'appairage (sur un capteur de porte, après une 10ene d'essais, j'ai retiré-remis les piles, puis ça a été enfin digéré). Donc pour moi, c'est tout bon (enfin je garde également plusieurs jours en attente de la version stable avant de migrer sur de la prod; si tu veux te connecter pour analyser les logs, c'est toujours possible ;) )

**Comment by Soyann** [comment]
Par contre: 
![image](https://user-images.githubusercontent.com/46709337/69570774-d5016f80-0fc0-11ea-9d9e-7d7469551760.png)

**Comment by Soyann** [comment]
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3888354/Abeille.txt)

**Comment by Soyann** [comment]
PS: si tu clôtures, tu pourras avant répondre à ma question d'hier soir sur les versions de firmware?

**Comment by KiwiHC16** [comment]
Je n'ai vu sur ta configuration que du xiaomi dans ce cas la 3.0F est très bien. C'est celle que j'ai encore sur ma prod.

**Comment by KiwiHC16** [comment]
Pour l'inclusion il peut être nécessaire d'être patient entre chaque manip car Abeille est probablement trop demandeur en volume de message vers l'équipement. J'ai peut être forcé la dose. Je wis probablement réduire.

**Comment by KiwiHC16** [comment]
Tiens moi au courant dans le jours a venir. On clôturera quand tout est ok après plusieurs jours.

**Comment by Soyann** [comment]
Hello, voici le seul message nocturne: 2019-11-26 00:35:03 Attention [Bureau][Fenêtre (bas)] n'a pas envoyé de message depuis plus de 60 min (vérifiez les piles). Sinon, tout roule :)

**Comment by Soyann** [comment]
Grosse latence sur l'exécution du (seul et unique) scénario à 08:07:05: bien 2-3 secondes avant que la lumière ne change d'état; je pense que cela vient pus du capteur que de l'ampoule.

**Comment by Soyann** [comment]
Pour le volume de messages à l'inclusion, peut-être devrais-tu modifier les retours au niveau du centre de messages, pour que ça fasse un truc du genre: "Création de l'abeille xxx (comme à l'heure actuelle, mais complété par: ) Merci de patienter pendant l'initiation des commandes", puis un second message effaçant le premier et disant "Création de l'abeille xxx terminée, appuyez sur F5 (blablabla)". C'est peut-être plus simple que de revoir le vocabulaire de la ruche ;)

**Comment by Soyann** [comment]
Salut, gros problème ce soir: en rentrant, j'ai redémarré ma box pour faire une mise à jour de cette dernière. Au préalable, j'ai arrêté proprement ma VM (en ai profité pour ajouter un hub sur le port USB), redémarré ma box, et redémarré ma VM. Depuis, seuls mes équipements sur batterie remontent leur état, mais je n'ai plus moyen allumer aussi bien la prise que la lampe... Je viens de rebooter l'ampoule: idem, elle reste allumée et pas moyen de l'éteindre. Pourtant dans Santé, ça a l'air de communiquer... Je laisse tel quel pour le moment, pour si tu peux venir faire un tour.

**Comment by Soyann** [comment]
Je viens de voir qu'il y a un update du master, j'attends un peu avant de l'appliquer, de peur que ça fausse ton analyse (si tu passes sur ma machine, tu pourras le faire si tu veux)

**Comment by Soyann** [comment]
Bon, j'ai voulu mettre à jour Jeedom, avait bien coché 'Ne pas mettre à jour' pour Abeille, mais il a quand même appliqué sur ton plugin. Ce n'est pas pour autant que ça marche mieux...

**Comment by Soyann** [comment]
Je vois ça dans les logs Abeille:
fct message Topic: ->Abeille/Ruche/Zigate-8000<- Value ->(ZigBee Error Code unknown): 15<-

Redémarrage vers 18h10

**Comment by Soyann** [comment]
Bon, je viens de trouver: c'est le hub usb qui met le bazar ...

**Comment by Soyann** [comment]
Du coup, tu veux faire des essais avec ce hub, ou je peux le retourner directement? (ce qui me dépasse, c'est qu'il marche, que la clé est reconnue, et que mes Xiaomi remontent bien, seul les routeurs posent problème). https://www.amazon.fr/gp/product/B00QWZAI8Q/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by Soyann** [comment]
Hello, petit retour d'expérience: tout marche bien chez moi (hormis la mésaventure hubiène). J'ai de temps à autre de petits timeout sur les équipements que je n'explique pas (pas plus que sur mon autre zigate en prod, car je pense que la couverture de ma maison est quand même assez bonne avec la quantité de routeurs que j'ai, et qui sont positionnés de manière à assurer la meilleur couverture possible...).
Donc même si là, il n'y a pas d'excuse vu que tout est dans la même pièce, je suis certain qu'un réglage de timeout à 122 min comme sur l'autre rendra (chez moi) tout ça transparent, et donc je mets un pouce en l'air pour passer la Master en stable (enfin pour la VM Delta)
Merci encore pour tout, je reste à ta dispo si tu as besoin (ma VM test est encore en ligne et le restera encore quelques jours, donc n'hésites pas si tu veux y faire un tour), et si tu as du temps ou de la curiosité pour ces histoires de timeout ou de hub (que je retournerai en début de semaine prochaine sans nouvelles de ta part), ce sera avec plaisir que je t'apporterai mon amble aide ;)
Merci merci merci merci merci merci
PS: dispo demain aprem, et ce weekend sauf samedi soir (enfin si ma femme ne tique pas trop sur le temps passé derrière l'ordi :p )
++

**Comment by KiwiHC16** [comment]
Ok super. Bizarre l histoire du Hub. Je te propose de close cette issue et d'en ouvrir d'autres si besoin.
