### ISSUE TITLE
bug de remonté des statuts des équipements

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#822]
Sur branch master

Quand je clic dans “santé”, tout est “Time out last communication” (ou presque)

Par contre tout fonctionne très bien (les commandes)
J’ai des équipements livolo et des routeurs.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut,
As tu des captures d'ecran a partager ?
Quelle version Jeedom ?
Quelle Version Abeille ?
Peux tu partager le log AbeilleParser ?

**Comment by graouxx** [comment]
Hello,
Jeedom 3.3.36
Abeille master

A priori tout est rentré dans l'ordre, ça fonctionne à nouveau après avoir lancer plusieurs "get LQI". Et je pense que le soucis vient plutôt de la. Régulièrement le tableau est incomplet dans Network List et quand je lance un get LQI ça s'arrête rapidement ou au bout de quelques secondes. Je suis obligé de relancer plusieurs fois.

**Comment by KiwiHC16** [comment]
Je pense que cela devrait être meilleur avec la version a venir.
Aurais tu le moyen de tester avec la version Master ?

**Comment by KiwiHC16** [comment]
Je propose de clore. On rouvrira si besoin.
