### ISSUE TITLE
Systeme @salchr

### ISSUE THREAD

**Issue by salchr** [KiwiHC16/Abeille#823]
Bonsoir,
Déjà merci pour le développement effectué qui m'a permis d'automatiquer une bonne partie de ma maison.
Je rencontre néanmoins qq soucis (rapsberry 3+, zigate usb) je perds régulièrement mes périphériques, obligé de les ré inclure. Perte en time out communication. En checkant mes link quality je suis en moyenne au dessus de 100. 
J'ai 36 nœuds et 4 démons de lancés (peut être est trop juste mais je ne trouve pas où changer le nombre de démons).
Je perds en moyenne entre 4 et 5 periph par semaine
Comment faire pour éviter cela ? et que puis-je apporter comme infos pour aiguiller la résolution de ces soucis ?
Bonne soirée

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut,
Peux tu donner la liste des equipements que tu perds (Adresse courte) ?
Partager une capture d'écran de la table santé et de la table des noeuds ?

**Comment by salchr** [comment]
Bonjour,
Merci pour ta réponse.
Tu trouveras ci dessous les éléments demandés. J'espère que ce sont ceux que tu demandais.
Bonne journée.

![sante](https://user-images.githubusercontent.com/53155542/68475009-3c7c9880-0227-11ea-91c7-1fbfa2fff8d4.jpg)
![noeud](https://user-images.githubusercontent.com/53155542/68475016-3edef280-0227-11ea-958b-a88b607a1e54.jpg)

**Comment by salchr** [comment]
Bonjour,
Juste concernant mes avancées sur le problème, j'ai changé de serveur jeedom. Je suis passé d'un raspberry pi3 + à, un vrai PC  en core I5. J'ai peu tout restaurer, mon système a été stable pdt 2 jours puis rebelotte.
Sur ma 36 équipements j'en ai perdu 20 au bout du 4eme jour l'ancé.
J'ai un reboot du serveur dans la nuit automatique.
Je ne sais où chercher ou comment procéder pour en trouver les raisons.
Merci d'avance et bonne journée.

**Comment by KiwiHC16** [comment]
Merci pour première capture. 
Peux tu partager la table des LQI ?
(Une zigate débranchée, arrêtée peut provoquer la perte d équipement. Elle doit être en fonctionnement tout le temps).

**Comment by salchr** [comment]
Bonjour tu trouveras ci dessus les LQI. La zigate est effectivement branchée tout le temps. Par contre je pense que je fais repenser mon maillage de la maison et mettre bcp plus de prise connectée et alimentée. Voire rajouter un autre router en jeelink avec un autre zigate et tout resyncrho. J'en suis aujourd'hui à 24 perif déconnecté... Les périfs en dessous de 100 en LQI je sais que c'est plus que border du coup je ne m'en soucie pas.
![image](https://user-images.githubusercontent.com/53155542/68943039-5e879500-07aa-11ea-823d-25030a9cdf13.png)

**Comment by KiwiHC16** [comment]
Salut,
Pourquoi as tu "J'ai un reboot du serveur dans la nuit automatique" ? Dans le passé des utilisateurs m'avaient indiqué des pertes d'équipement sur reboot de la machine...

Sinon, dans tes infos je vois:
```
afdb - 136 (Child Zigate)
b260 - inconnu
2740 - 228 (Child Zigate)
75d2 - inconnu
Not same time

23 visibles de la zigate: bien dans la limite de capa.
```

Les LQI sont haut donc on ne devrait pas avoir de soucis. ( >50 ca doit fonctionner).

Sur quel canal est la zigate ?
As tu du Wifi autour ? Sur quel canal ?

**Comment by salchr** [comment]
Bonjour,
Merci pour ton temps et ton retour (je n'oublierai pas la cagnotte ;)). Ok pour le reboot, je supprime la tâche. 
J'avais qq doutes sur mon rapsberry sur ma première install, je suis passé sur un vrai poste informatique du coup c'est plus stable donc je stop cet cron.
Question con : quelle est la limite de préiphérique d'un zigate ?

Pour le canal je suis en 11. Le wifi le plus proche est en 6.  pas d'interférence au scanner wifi.

Pour suivi j'ai augmenté le nombre de prise connecté pour avoir un maillage + important ce week-end. Pas mal de périph sont revenus d'eux même.
J'ai aussi  augmenté le temps des times out pour les  Détecteurs de Mvt et de porte, ainsi que les capteur de température.
A suivre si çà suit son cour ou pas.

**Comment by KiwiHC16** [comment]
```
quelle est la limite de préiphérique d'un zigate ?
```
Je ne me souviens plus du chiffre exacte mais je crois que c est 70. Avec un contrainte, 40 max en direct sur la zigate. Les autres étant sur des routeurs.

**Comment by KiwiHC16** [comment]
```
pas d'interférence au scanner wifi
```
Comment scan tu le wifi ?

**Comment by KiwiHC16** [comment]
Ok tiens moi au courant avec les routeurs additionnels.

**Comment by salchr** [comment]
> ```
> quelle est la limite de préiphérique d'un zigate ?
> ```
> 
> Je ne me souviens plus du chiffre exacte mais je crois que c est 70. Avec un contrainte, 40 max en direct sur la zigate. Les autres étant sur des routeurs.

Ok merci pour cette information

**Comment by salchr** [comment]
> ```
> pas d'interférence au scanner wifi
> ```
> 
> Comment scan tu le wifi ?

Avec un outils sur PC que j'utilise dans mon métier (je suis dans l'informatique) qui me permet  de traquer les bornes signaux en fonction de mes déplacement. Sinon j'ai le wifi scanner sur mon téléphone portable (android) qui marche pas mal...

**Comment by KiwiHC16** [comment]
Peux tu être plus précis ? Nom des softs et HW utilisés ?
Si tu utilises les softs classiques sur PC qui remontent les infos wifi tu ne verras rien sur le zigbee, d'où mes questions...

**Comment by salchr** [comment]
> Peux tu être plus précis ? Nom des softs et HW utilisés ?
> Si tu utilises les softs classiques sur PC qui remontent les infos wifi tu ne verras rien sur le zigbee, d'où mes questions...

Hello,
Oui pardon j'ai procédé par élimination en fait. Je ne vois effectivement pas le réseau Zigbee mais que mes wifi.
Je suis dans une maison individuelle, j'ai scanné mon propre wifi "informatique" et je l'ai éloigné le plus possible de mon zigbee.
Mon zigbee est en 11.  
Mon wifi est en 3 et 5 (routeur et PA), donc je déborde un peu sur le 6.

**Comment by KiwiHC16** [comment]
Tu peux visualiser les bandes dans les premiers graphes http://kiwihc16.free.fr/Radio.html
Il pourrait être interessant de pousser vers le haut le Wifi ou le ZigBee. par exemple ZigBee en 26.
Il faut l'éloigner de la zigate mais aussi des équipements. Par exemple j'avais un camera wifi à 20 cm d'une prise zigbee et je perdais tout le temps la prise. 
Attention certain mode Wifi ont des largeur de bandes tres large 40MHz au lieu de 20MHz).

**Comment by salchr** [comment]
> Tu peux visualiser les bandes dans les premiers graphes http://kiwihc16.free.fr/Radio.html
> Il pourrait être interessant de pousser vers le haut le Wifi ou le ZigBee. par exemple ZigBee en 26.
> Il faut l'éloigner de la zigate mais aussi des équipements. Par exemple j'avais un camera wifi à 20 cm d'une prise zigbee et je perdais tout le temps la prise.
> Attention certain mode Wifi ont des largeur de bandes tres large 40MHz au lieu de 20MHz).

Bonjour,
Ok j'avais mal compris les graphs. Je pousse la zigate en 26 du coup.  Mon zigate est à 5m de ma box, et mon premier periph zigbee dans le même genre. J'ai un autre Point d'accès dans un local extérieur, le perif zigbee le + proche est à une 10ene de mètre. Tu sais tout :)

**Comment by salchr** [comment]
Bonjour,
Je profite de cette chaine qui ressemble de plus en plus à "un bon usage du zigbee"... 
2 questions: 
J'ai activé dans la page de conf l'affichage des infos réseau et autre time. Je les ai bien retrouvé sur mon dashboard, mais impossible de revenir en arrière. En les décochant ça reste toujours affiché. Y a  moyen d'automatiser sans repasser sur chaque équipement.
Et y a t il moyen de forcer l'audit réseau, j'ai mes prises alimentées posées samedi qui ne sont pas encore prise en compte dans l'audit.
Merci à toi (je viens de cagnoter)

**Comment by KiwiHC16** [comment]
Effectivement alors je renomme l'issue.

**Comment by KiwiHC16** [comment]
```
J'ai activé dans la page de conf l'affichage des infos réseau et autre time. Je les ai bien retrouvé sur mon dashboard, mais impossible de revenir en arrière. En les décochant ça reste toujours affiché. Y a moyen d'automatiser sans repasser sur chaque équipement.
```

Dans la conf 
![Capture d’écran 2019-11-19 à 17 04 47](https://user-images.githubusercontent.com/8549674/69163539-b3027b80-0aee-11ea-9035-c3ac232a2b97.png)

Passes les affichage a non et sauvegarde.

**Comment by KiwiHC16** [comment]
```
Et y a t il moyen de forcer l'audit réseau, j'ai mes prises alimentées posées samedi qui ne sont pas encore prise en compte dans l'audit.
```
Normalement ca doit se faire une fois par nuit (mais j ai un doute que cela fonctionne, je vais créer un cas). Sinon fait le bouton "Get LQI" pour forcer le refresh des informations.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2019-11-19 à 17 06 46](https://user-images.githubusercontent.com/8549674/69163710-fb219e00-0aee-11ea-84f1-06dc9309e6c3.png)

**Comment by salchr** [comment]
> Normalement ca doit se faire une fois par nuit (mais j ai un doute que cela fonctionne, je vais créer un cas). Sinon fait le bouton "Get LQI" pour forcer le refresh des informations.

Hello, à priori il ne se fait pas. j'ai une lampe que j'ai supprimées qui sont toujours présente dans le réseau. qd je force le lqi il me dit opération de collecte toujours en cours.

![image](https://user-images.githubusercontent.com/53155542/69163959-679c9d00-0aef-11ea-88a5-73f84f3ddabb.png)

**Comment by salchr** [comment]
> Passes les affichage a non et sauvegarde.

pour les affichage même en passant à non ca n'a pas fonctionné. J'ai modifié à la main. ++

**Comment by KiwiHC16** [comment]
Je viens de faire des modifications sur ce sujet dans le master.

**Comment by KiwiHC16** [comment]
#773

**Comment by KiwiHC16** [comment]
php /var/www/html/plugins/Abeille/Network/AbeilleLQI.php

**Comment by salchr** [comment]
au top!!!
merci je vais appliquer cela.

**Comment by salchr** [comment]
Après effacement du fichier json.lock + exécution de la commande, le graphique est ok.

**Comment by KiwiHC16** [comment]
On clos cette issue ?

**Comment by salchr** [comment]
Oui on peut. Je pense. Donc à retenir :
- faire un bon mesh permanent en routeur
- vérifier les superpositions fréquence wifi  /Zigbee
- j'ai augmenté mon délais de time-out
- refaire le refresh réseau.

Et au final c'est stable :)
Merci pour tout.

**Comment by KiwiHC16** [comment]
Oui tout ces points sont importants.
