### ISSUE TITLE
Analyse du réseau: graphique incohérent

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#824]
Bonjour.
J'essaie d'utiliser le "Network list" pour comprendre mes problèmes de perte de capteur.
Si la partie "Résumé" tient la route et liste mes péripheriques (Voisins :Zigate, Temp C1, Volet C1, Temp C2, Volet C2, Temp C3, Volet C3, Volet CU, Temp SM, Volet SM, Temp ST), la partie "Graphique" ne me parle pas du tout et la table des noeuds encore moins.

Version Abeille: 2019-10-16 01:01:06
Version Zigate: SDK | 031a
Version Jeedom: 3.3.37

J'ai du louper qqch. Comment l'utiliser ?
Merci

<img width="833" alt="Table des noeuds" src="https://user-images.githubusercontent.com/35221038/68800687-dcd52180-065a-11ea-83c7-b5596fdaa1b5.png">
<img width="580" alt="Resume" src="https://user-images.githubusercontent.com/35221038/68800689-dd6db800-065a-11ea-8b0c-cd8799c37dbf.png">
<img width="591" alt="Graphique" src="https://user-images.githubusercontent.com/35221038/68800692-de064e80-065a-11ea-97e7-ed9c819506fc.png">

**Comment by KiwiHC16** [comment]
Regardes:

https://abeilledocsphinx.readthedocs.io/fr/latest/Radio.html

**Comment by tcharp38** [comment]
Salut Kiwi.
J'avais déja parcouru ce chapitre mais malheureusement sans arriver à afficher mon réseau.

- La page "Résumé" est ok.
- La page "Graphique du réseau" ne l'est déja plus. Ca n'est pas mon réseau et aucune explication ou bouton pour le mettre à jour.
- Idem pour la "Table des noeuds". Ca ne correspond à rien de mon réseau et la, juste un bouton "Get LQI" qui ne semble pas rafraichir le reseau non plus.

J'ai lu que ces tables étaient reactualisées toutes les 24H ou qu'on pouvait forcer la mise à jour via "Network List->Table des noeuds->Recalcul du cache", hors je n'ai pas ce genre de bouton.
Du coup je me demande ce que j'ai loupé.

**Comment by KiwiHC16** [comment]
Dans la doc "Network List->Table des noeuds->Recalcul du cache" mais il doit s'appeler "Get LQI" maintenant.

Je viens de regarder plus en détails ton cas et effectivement il y a un soucis.

Peux tu me faire une capture d'ecran de la page des Abeille ?

Cette page:
![Capture d’écran 2019-11-18 à 11 02 27](https://user-images.githubusercontent.com/8549674/69043215-e9f36700-09f2-11ea-87a5-a71d6290c0cc.png)

Peux tu partager le fichier "AbeilleLQI_MapData.json" qui est dans le repertoire /var/www/html/plugins/Abeille/Network/  ?
Et le fichier "AbeilleLQI_MapData.json.lock" dans le meme repertoire.

**Comment by KiwiHC16** [comment]
Je viens d installer une Jeedom V4 sur Debian 10 et j'ai des soucis. Il faut que je comprenne ce qu'il se passe.

**Comment by KiwiHC16** [comment]
Voilà ca semble bien mieux apres mes changements. Tout semble fonctionner sur ma V4 Debian 10.
Peux tu tester avec le master ?

**Comment by tcharp38** [comment]
Salut Kiwi.
Désolé pour mon silence. Pas eu le temps de faire les essais.
Néanmoins, je suis toujours en v3 et non pas v4.
Je peux tenter ta branche de dev quand meme ?
Si oui, j'ai vu une solution pour la recuperer via Git, mais comment puis je copier les equipements déja connus (et historiques) pour ne pas repartir de 0 ?
Merci

**Comment by KiwiHC16** [comment]
Ok dans ce cas. Je continu les tests en V4 et je regarderai V3 et te tiens au courant. Je viens de tomber sur un soucis.

**Comment by KiwiHC16** [comment]
Maintenant ca devrait être bon en V4, les dernieres modifications sont dans le master.

**Comment by KiwiHC16** [comment]
La génération du cache ne se finit pas #773
Il y a une commande a lancer à la main ca peut aider.

**Comment by tcharp38** [comment]
Question bete: Le master est encore compatible v3 ?
Jusque la j'evite de passer en v4 pour ne pas cumuler les soucis.

**Comment by KiwiHC16** [comment]
Si tu mettrises Git tu peux mettre le master et rollback si soucis. Sinon c'est plus compliqué. 
Pas sure que le master soit toujours ok V3. Je dirais oui mais pas testé.

**Comment by KiwiHC16** [comment]
Oui le master est ok avec la V3. Mon systeme principal fonctionne comme ca. Prend le version beta du Market.

**Comment by tcharp38** [comment]
Salut Kiwi.
J'avais trouvé du temps pour passer sur le git au lieu du market mais j'étais sur la branche master.

D'ailleurs en passant, quelle est la procedure propre pour passer du market à GIT ?
J'ai supposé les etapes suivantes
- systemctl stop cron => n'arrete pas cron
- systemctl stop apache2
- cd /var/www/html/plugins
- mv Abeille Abeille.market
- git clone https://github.com/KiwiHC16/Abeille.git
- cd Abeille
- git checkout beta
- puis un sudo reboot
Ca fait du sens ? Des suggestions ?

Quoi qu'il en soit il y a de nets progres.
- La page "résumé" me liste bien mes equipements comme avant (Zigate + capteurs Xiaomi temp + volets profalux):
Zigate, Temp C1, Volet C1, Temp C2, Volet C2, Temp C3, Volet C3, Volet CU, Temp SM, Volet SM, Temp ST
- le Graphique reseau, une fois passé par le "Get LQI" de la "Table des noeuds", donne enfin qqch qui ressemble à mon réseau
![image](https://user-images.githubusercontent.com/35221038/70084739-2d62ed80-160f-11ea-9e03-5a39b666fa29.png)
Je ne sais pas encore l'interpreter mais ca fait du sens.
- Enfin la table des noeuds:
![image](https://user-images.githubusercontent.com/35221038/70085199-1244ad80-1610-11ea-8669-1bb3adbf4791.png)
![image](https://user-images.githubusercontent.com/35221038/70085266-2b4d5e80-1610-11ea-924e-2c125330b6c8.png)

Mes capteurs de température les plus eloignés (Temp C1, C2 & C3) semblent sans vie. Je vais tacher de faire le lien avec ces infos.

A suivre
Merci pour tout ce travail

**Comment by KiwiHC16** [comment]
Ta procedure de market / git me semble bonne perso je suis beaucoup plus brutal mais je "sais" ce que je fais, et si ca plante je parviens à redemarrer.

La seule modif que je te proposerai est de changer
mv Abeille Abeille.market
par
tar cvf Abeille.tar Abeille
ou mv Abeille en dehors du repertoire des plugin, dans un /home/perso par exemple.

**Comment by tcharp38** [comment]
Ok merci.
2 petits bugs a signaler dans la table des noeuds:
- Le mot "Ruche" apparait en lieu et place du nom "Zigate" que j'ai donné à cet equipement.
- Certains voisins ne sont pas identifiés alors qu'ils sont connus. Par exemple celui ci
![image](https://user-images.githubusercontent.com/35221038/70140064-30ec8800-1694-11ea-8b77-bade9ec9c90c.png)
00158d0001edfac2 n'est autre que "Ruche" (ou plutot "Zigate" normalement)
Du coup ca semble impacter le "graphique reseau".

Pour les autres non nommés je suppose qu'il s'agit de mes capteurs de temp mais je ne comprends pas pourquoi la correlation adresse IEEE <> nom n'est pas dispo. Meme si en time out pour la raison que je cherche toujours, ils sont connus d'Abeille.

**Comment by tcharp38** [comment]
Salut Kiwi.
J'ai rebasculé sur la derniere version officielle market "2019-12-11 01:01:06".
Pas de changement par rapport à la beta. Le bug le plus embettant est certainement celui des voisins non identifiés mais connus.
![image](https://user-images.githubusercontent.com/35221038/70861464-aecf4f80-1f2e-11ea-8ca3-de6ac3218397.png)

Veux tu que je l'entre comme un bug independant ?
Veux tu que je fasse qqch ? Quand tu marques "help wanted" c'est dans quel but ?
J'imagine que tu n'as pas un temps infini à consacrer à tout ça alors si je peux faire qqch, dis moi.
Merci

**Comment by KiwiHC16** [comment]
J'essayes d'avoir des "issues" les plus précises possibles pour être le plus efficace.
Je prefererai qu on ferme cette issue et que tu en ouvres une sur le sujet spécifique.
Peux tu ouvrir une autre issue et y mettre deux tables. La page santé et la page "Table des noeuds" .

**Comment by tcharp38** [comment]
Ca marche pour moi. Je m'y colle aujourd hui des que j'ai qq minutes.

**Comment by tcharp38** [comment]
Je clos ce pb.
Des améliorations depuis la version market "2019-12-11 01:01:06".
2 bugs séparés #889 & #890
