### ISSUE TITLE
System @Pixou

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#825]
https://www.jeedom.com/forum/viewtopic.php?f=184&t=33573&p=777815#p777815

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Pas d info.

**Comment by pixou80** [comment]
désolé plus moyen de retrouver mes identifiants
(et j'ai reçu mes capteurs de porte entre temps ^^)

le problème est toujours le même avec rien à l'affichage et pleins de {{{ après F5
