### ISSUE TITLE
TRADFRI bulb GU10 W 400lm

### ISSUE THREAD

**Issue by zoozbiro** [KiwiHC16/Abeille#83]
Hello, j'ai testé une nouvelle lampe Ikea. J'ai modifié le fichier JSON en local et cela fonctionne parfaitement. 

un peu peur de faire une bêtise en publiant mon fichier je ne suis pas super à l'aise avec github, du coup voici mes infos. 

`"TRADFRI bulb GU10 W 400lm": {
    "nameJeedom": "TRADFRI bulb GU10 W 400lm",
    "Categorie": {
      "light": "1"
    },
    "configuration": {
      "icone": "IkeaTradfriBulbGU10W400lm"
    },
    "Commandes": {
      "0000-0005": {
        "name": "nom",
        "order": 0,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": ""
      },
      "0000-0004": {
        "name": "societe",
        "order": 1,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": ""
      },
      "0000-4000": {
        "name": "SW",
        "order": 2,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": ""
      },
      "0006-0000": {
        "name": "etat",
        "order": 3,
        "isHistorized": "1",
        "Type": "info",
        "subType": "binary",
        "invertBinary": "0",
        "template": "light"
      },
      "0008-0000": {
        "name": "Level",
        "order": 4,
        "isHistorized": "1",
        "Type": "info",
        "subType": "numeric",
        "invertBinary": "0",
        "template": "",
        "units": "%",
        "configuration": {
          "minValue": "0",
          "maxValue": "100",
          "historizeRound": "0",
          "calculValueOffset": "#value#/255*100"
        }
      },
      "Time-Time": {
        "name": "Time-Time",
        "order": 5,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": ""
      },
      "Time-TimeStamp": {
        "name": "Time-TimeStamp",
        "order": 6,
        "isHistorized": "0",
        "Type": "info",
        "subType": "numeric",
        "invertBinary": "0",
        "template": "badge"
      },
      "On": {
        "name": "On",
        "order": 7,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/OnOff",
          "request": "On"
        }
      },
      "Off": {
        "name": "Off",
        "order": 8,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/OnOff",
          "request": "Off"
        }
      },
      "Toggle": {
        "name": "Toggle",
        "order": 9,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/OnOff",
          "request": "Toggle"
        },
        "display": {
          "forceReturnLineAfter": "1"
        }
      },
      "Level": {
        "name": "setLevel",
        "order": 10,
        "isHistorized": "0",
        "Type": "action",
        "subType": "slider",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/setLevel",
          "request": "Level=#slider#&duration=01"
        }
      },
      "getEtat": {
        "name": "getEtat",
        "order": 11,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/ReadAttributeRequest",
          "request": "clusterId=0006&attributeId=0000"
        }
      },
      "getLevel": {
        "name": "getLevel",
        "order": 12,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/ReadAttributeRequest",
          "request": "clusterId=0008&attributeId=0000"
        }
      },
      "getManufacturerName": {
        "name": "getManufacturerName",
        "order": 13,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/ReadAttributeRequest",
          "request": "clusterId=0000&attributeId=0004"
        }
      },
      "getModelIdentifier": {
        "name": "getModelIdentifier",
        "order": 14,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/ReadAttributeRequest",
          "request": "clusterId=0000&attributeId=0005"
        }
      },
      "getSWBuild": {
        "name": "getSWBuild",
        "order": 15,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/ReadAttributeRequest",
          "request": "clusterId=0000&attributeId=4000"
        }
      },
      "IEEE-Addr": {
        "name": "IEEE-Addr",
        "order": 16,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": "badge"
      },
      "Link-Quality": {
        "name": "Link Quality",
        "order": 17,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": "badge"
      },
      "Power-Source": {
        "name": "Power Source",
        "order": 18,
        "isHistorized": "0",
        "Type": "info",
        "subType": "string",
        "invertBinary": "0",
        "template": "badge"
      },
      "Identify": {
        "name": "Identify",
        "order": 19,
        "isHistorized": "0",
        "Type": "action",
        "subType": "other",
        "invertBinary": "0",
        "template": "",
        "configuration": {
          "topic": "CmdAbeille/#addr#/identifySend",
          "request": "duration=0010"
        }
      }
    }
  }`

voici l'image : 

![tradfri-led-bulb-gu-lumen__0463170_pe608601_s4](https://user-images.githubusercontent.com/4723029/35826321-b4340c86-0ab8-11e8-9b58-6570089c41c0.JPG)

**Comment by KiwiHC16** [comment]
Super. Merci. Je viens de la mettre dans ma version. Sera dans le prochain push. Je garde le "issue" ouvert en attendant ton retour des que tu pourras tester. Moi je ne peux pas tester, je n'ai pas cette ampoule.

**Comment by KiwiHC16** [comment]
@zoozbiro peux tu tester ?

**Comment by zoozbiro** [comment]
Test effectué en mode automatique l'ampoule est reconnue sans problème après détection (allumage et extinction de l'ampoule). les commandes fonctionnent également.

Par contre il y a un comportement qui pourrait être amélioré, quand l'ampoule est détectée pour la première fois, le setlevel est au minimum (il faut peut être le mettre au maximum) car l'ampoule est au maximum à la première détection.

le bouton identify ne provoque aucune action, normal ?

**Comment by KiwiHC16** [comment]
Oui on peut pour mettre en place setLevel.
identify: mon ampoule fait varier l intensité.

**Comment by KiwiHC16** [comment]
JSON en place. Je clos si issue on ouvrira un cas specifique.
