### ISSUE TITLE
Redémarrage démon nécessaire régulièrement

### ISSUE THREAD

**Issue by Mavericklolo** [KiwiHC16/Abeille#832]
Bonjour KiwiHC16,

Comme échangé sur le forum Jeedom, je rencontre des instabilités depuis quelques semaines avec le plugin Abeille.

Mes objets passent en hors connexion et je ne peux plus les commander.

Un redémarrage du service solutionne le soucis. Le redémarrage peut être nécessaire au bout de quelques minutes, voire moins si des actions sont demandées (inclusion, ...). Peut être une saturation au niveau de la zigate???

J'étais en version Master sur une Jeedom V3/Debian9 avec un RPI3 et une Wifi Zigate.

Suite à un crash de ma carte SD, j'ai décidé de remonter un nouveau Jeedom basé sur une V4 et Debian 10 en alternative à une remontée de ma sauvegarde.

J'ai rencontré quelques soucis avec la version stable puis le master mais c'est stabilisé maintenant (la partie de ta doc sur Effacer mes bidouilles et remettre les droits semblent avoir aider) et je reviens à un comportement similaire à celui que j'avais.

J'ai pu rajouter une grande partie de mes lampes mais je devais relancer le démon toutes les 1 ou 2 lampes.

Je me demande s'il ne s'agit pas de saturation du plugin ou de la zigate car je viens de tester l'allumage d'un lampe sans problème depuis ma dernière relance du démon de cette nuit. Je redémarre les logs (je les avais remis par défaut) et ma lampe ne répondait plus mais elle s'est allumé 40 secondes plus tard. Dans les logs MQTTCmd, elle avait 180 commandes à envoyer quand j'ai regardé. Elle est maintenant à 1 et la lampe fonctionne normalement. Je suis désolé j'ai collecté les logs quelques minutes après et cela avait écrasé les précédents. Je te collecte les logs si cela se reproduit.

Je te mets les logs du parser, du MQTTCmd et de Abeille.

Dis moi si tu veux que je reproduise quelque chose pour donner de la clarté aux logs.

Pour info, j'ai à peu près 25 lampes Ikea dont 4 sont allumées en permanence (bypass interrupteur). J'ai inclus pour l'instant une quinzaine de lampes dont 2 permanentes. Je n'ai aucun scénario de recréer pour la gestion des lumières actuellement. Normalement, j'en ai 5 (les 4 permanentes et une 5ème sur interrupteur) avec des détecteurs présence Zwave.

Merci pour ton aide.

Cordialement,

Laurent

[20191120 - 1220 - Logs-Abeille-Mavericklolo.zip](https://github.com/KiwiHC16/Abeille/files/3868910/20191120.-.1220.-.Logs-Abeille-Mavericklolo.zip)

**Comment by KiwiHC16** [comment]
Salut Laurent,

Plusieurs commentaires à la lecture des infos si dessus.
```J'étais en version Master sur une Jeedom V3/Debian9 avec un RPI3 et une Wifi Zigate.```
La version Master n'est pas du tout stable en ce moment alors a utliser qu'avec parcimonie ... Il est peu probable que cela fonctionne correctement.

```Jeedom basé sur une V4 et Debian 10 en alternative à une remontée de ma sauvegarde.```
Je suis entrain de tester les modifications nécessaires pour que cela fonctionne. Donc pour l instant cette conf ne doit pas fonctionner correctement.

```Je me demande s'il ne s'agit pas de saturation du plugin ou de la zigate ```
C est simplement que le soft n'est pas stabilisé. Peux être qu'avec la V4, Debian 10 et Master d'aujourd'hui 13h cela peut fonctionné. Mon système a 6 ampoules et semble fonctionné. 

```Pour info, j'ai à peu près 25 lampes Ikea dont 4 sont allumées en permanence (bypass interrupteur). ```
Ce n'est pas une bonne idée d'éteindre des équipements électriquement car ca perturbe le réseau zigbee et le routage mesh pert tout son sense. Toutes les ampoules doivent être allumées éléectriquement même si éteinte.

**Comment by Mavericklolo** [comment]
Je te partage les logs  lors d'une latence importante.

[20191120 - 1512 - Logs Abeille Mavericklolo.zip](https://github.com/KiwiHC16/Abeille/files/3869711/20191120.-.1512.-.Logs.Abeille.Mavericklolo.zip)

Je te remercie pour tes retours.

J'ai installé cette nouvelle version en connaissance de cause donc pas de soucis et je rencontre globalement un comportement similaire au master sur V3 et Debian 9.

Je voulais repasser sur la stable avec la V3 pour assurer car je suis souvent en déplacement. Comme je suis à la maison actuellement. C'était préférable de migrer ce qui pouvait l'être actuellement même si la V10 n'est pas encore stable. Et je suis plus disponible pour béta tester.

En ce qui concerne l'alimentation permanente des ampoules, la target est de le systématiser mais j'avais été un peu refroidit par la stabilité de la gateway IKEA au début et le coût des détecteurs et/ou interrupteurs nécessaires. Par contre, un certain nombre d'ampoules sont remontées que pour le monitoring mais pas géré par Abeille et peuvent sans problème être désincluses.

En feedback complémentaire, je crois qu'il y a un petit bug d'affichage des devices (les noms n'apparaissent pas (voir image jointe).

![2019-11-20_15-39-16 - Abeille - Mavericklolo](https://user-images.githubusercontent.com/27410124/69251073-1b199600-0bb1-11ea-8945-6f88059b66dc.png)

En V4, l'utilisation des thèmes alternatif peut rendre illisible les informations (lettres noires sur fond noire) sur certains devices. Ce n'est pas prioritaire car on peut permuter facilement de vue mais s'il y a un template fourni par la Team Jeedom, à voir dans le futur.

En tous les cas, bravo pour ton travail sur le plugin et le support que tu apportes aux utilisateurs.

**Comment by KiwiHC16** [comment]
"je crois qu'il y a un petit bug d'affichage des devices" corrigé ce matin dans le master.

**Comment by KiwiHC16** [comment]
Essayes avec le master il doit ête ok maintenant. Il tourne sur deux machines ici depuis 12h.

**Comment by Mavericklolo** [comment]
Je suis en déplacement aujourd’hui mais je regarde cela ce soir. Merci

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mavericklolo** [comment]
J'ai mis à jour. Je te tiens au courant.

Les noms apparaissent bien mais ils apparaissent à côté de l'objet chez moi.

![2019-11-21_22-42-34 - Abeille - Mavericklolo](https://user-images.githubusercontent.com/27410124/69379328-8dbd6b00-0cb0-11ea-8d8d-12fc4601e1a6.png)

Pas de soucis si c'est voulu mais c'est plus régulièrement en dessous.

Cdlt,

**Comment by KiwiHC16** [comment]
C'est "voulu" afin de mettre la case de selection avec chaque equipement. Les case de base dans jeedom sont pas assez haute alors j'ai trouvé cette astuce de les élargir. Il faudrait changer le coeur de jeedom...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peut on fermer cette issue ou y a t il d autres questions ?

**Comment by KiwiHC16** [comment]
Je propose de clore. Rouvrir si besoin.
