### ISSUE TITLE
set group remote sur gradateur Ikea: fonctionne t il ?

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#842]
Suite de #368

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Antique sujet sans infos.
Je clos mais a reouvrir si ca parle à qqn.
