### ISSUE TITLE
Legrand Interrupteur Dimmer Encastrable Sur Secteur (ZLE18 / 18W37)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#848]
5W to 60W Led or 10 lamps Maxi
7W to 300W Bulb

3 connecteurs: L , wave, wave

Qu est ce qu il fait ce truc ? Variatuer sans neutre ?

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Legrand.html#interrupteur-sans-neutre

**Comment by pipiche38** [comment]
Pour ton info https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Legrand-corner.md

**Comment by KiwiHC16** [comment]
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware#version-30e
Premier topic.

**Comment by KiwiHC16** [comment]
Dimmer On 0101 fonctionne pour activer le dimmer.
Par contre Dimmer Off avec 0000 ne semble pas fonctionner. On verra peut êrte un jour mais l important c est d'avoir le dimmer.
