### ISSUE TITLE
Timer (un événement déclencheur)

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#851]
Bonsoir, KiwiHC16

Merci pour tout ce que tu fait.

Est t'il possible de modifier
Dans commande / état / configuration 
Gestion des valeurs
Valeurs interdites (séparées par ";")
Valeur retour d'état
0
**Durée avant retour d'état (min)**
1

l’unité de mesure est en minute 
donc le mini c'est une minute ce qui est très long ....
ne peut t'on pas avoir une expression en secondes ?

(mes capteur étant modifier leur retombée est < a 10s)

**Comment by KiwiHC16** [comment]
Non car c est le core de Jeedom.
Mais ce que tu peux faire c'est d'enlever cette valeur et utiliser les timer dans Abeille: http://kiwihc16.free.fr/Timer.html
Dans ce cas tu seras à la seconde.

**Comment by djsyl** [comment]
Ok je vais regarder un peut la doc car j'ai pas explorer le timer 
merci je repasse ici que ce soit ok ou pas

**Comment by djsyl** [comment]
Super taff sur TIMER , ca le fait :) 
ça vaut vraiment le coup de s'attarder dessus.

Si je devait faire une critique constructive 
tu devrait ajouter dans l'onglet param de TIMER
pour Start Stop et Cancel 
un événement déclencheur

Ce qui éviterai de repasser par la case scénario pour des cas simple.

Voila bon courage et encore bravo pour ce que tu fait.

Bonne journée

**Comment by KiwiHC16** [comment]
Oui c'est un sujet que j'avais en tête mais jamais fait. J'avais fait un truc similaire dans un plugin different. Il faudrait que je me replonge dans le sujet.
Je garde le point en changeant le titre de l issue.

**Comment by djsyl** [comment]
Parfait

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Will be followed in Timer part: https://github.com/KiwiHC16/Timer/issues/3
Closed here
