### ISSUE TITLE
Plugin Configuration panel not visible

### ISSUE THREAD

**Issue by genestep** [KiwiHC16/Abeille#852]
I installed the plugin on my new raspberry 3 (installed previously on a raspberry zero). 
I can't see configuration screen (to setup the pizigate port) in any case I tried and daemon is always NOK with configuration NOK
I don't have much information in the logs  (except that port is wrong)

Bug or a wrong configuration on my side ?
Thanks for the feedback

![Capture](https://user-images.githubusercontent.com/33360064/69453894-3200e980-0d65-11ea-9a37-f4d76298e7f3.JPG)

**Comment by djsyl** [comment]
Si c'est une V4 il faut prendre la Beta du plugin

![abeille](https://user-images.githubusercontent.com/19546412/69460998-c2dfc100-0d75-11ea-97ab-e4529c2165e0.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)
