### ISSUE TITLE
Legrand Inter Sur Pile fait un rejoin avant d'envoyer la commande mais ca provoque un process annonce...

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#853]

**Comment by Smanar** [comment]
Oui, exact, m'en suis rendu compte il y a 4/5 jours aussi.
Ca arrive aussi a pipiche, donc c'est surement le fonctionnement normal.
Vraiment chiant.

**Comment by pipiche38** [comment]
C'est le process normal de mon point de venu, car notamment le Flag Rejoin est positionné.
Donc comportement normal de la part d'un device remote, qui a pour habitude d'etre endormi.

@KiwiHC16 , c'est pour ça que le firmware 3.1b donnera également l'information de Rejoin

**Comment by Smanar** [comment]
D'ailleurs question con, tu as fais des bind dessus @pipiche38 mais as tu aussi mit des reports attributes ?
Combien de temps cet appareil peut rester endormis sans faire la moindre requete ? Si c'est illimité, je peux comprendre le device annonce, mais sinon je vois pas l'utilité.

**Comment by pipiche38** [comment]
Pas de Report Attribute, dans la mesure où le Hub legrand n'en fait pas.
Juste les binds.

Possible que en cas de diminution (sous un seuil de la batterie) il se reveil pour envoyer une alerte (enfin j'aurai fait ça), sinon aucune raison qu'il se réveille ...

**Comment by pipiche38** [comment]
Du reste, si tu prends n'importe quel Legrand, après une coupure de courant, il fait un REJOIN de la même façon avec le flag à 0x02

**Comment by Smanar** [comment]
Ok, donc fonctionnement completement different que les ikea ou aquara.
Ca explique pourquoi mon read attribute ne marche pas. Et je trouve ca pas con comme fonctionnement.
Si j'ai bien compris, il peut rester 5 jours sans aucunes requetes, mais sans jamais quitter le reseau, et puis lors d 'un appuis il previent qu'il se reveille qu'on puisse le bombarder de question, et se rendort.

Par contre ca va poser probleme pour la detection des devices deconnectés, si il peut rester plusieurs jours sans donner signes de vie.

**Comment by pipiche38** [comment]
Normal ou pas, je ne sais pas quoi répondre. Faudrait voir la norme. Par contre cela me semble pas déconnant. Pourquoi un Objet Connecté aurait à parler sur un réseau si il n'a rien à dire. 
Donc cela me semble assez élégant.

Maintenant que ça pause des problèmes de logiques en fonction des différents comportements , je suis d'accord.

**Comment by KiwiHC16** [comment]
Les deux comportements pour moi sont ok avec la norme. 
C'est une questions de choix.

Soit j'utilise le flag de Rejoin comme tu proposes, sois je ne génère le Join que durant la periode ou la ZiGate est en mode inclusion. Ou les deux, à voir... (C'est bien d'avoir le choix).

**Comment by KiwiHC16** [comment]
Implementé dans le master.
