### ISSUE TITLE
Timer-Param-Action commandes Alexa ou G-home champs message volume absent

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#854]
Bonjour,

Bon tout est pratiquement dans le titre 

lorsque l'on veut faire un message vocal sur les commandes 
Action avant après ...

il n'y a pas de champs pour renseigner le message et son volume a lire.

Si il y a une astuce ou une correction je suis preneur.

j'ai bien pensé lancer un scénario qui ferait la même chose mais je ne sais comment activer un scénario la ou on me demande une commande ...

Bonne soirée

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je dois dire que je ne comrend pas ! (Désolé).
Qu'est ce que c'est G-Home ?
Alexa, je ne joue pas avec (j utilise homebridge).

Peux tu essayer de décrire ce que tu souhaites faire ? (Désolé)

**Comment by djsyl** [comment]
Bonsoir,
Ce sont respectivement les 2 galets assistants google-home-mini et Echo-dot (alexa)
voici comment on les fait parler dans un senario Jeedom par exemple

![img](https://user-images.githubusercontent.com/19546412/69906710-e8994580-13c7-11ea-8ade-a79f922d786c.jpg)


il y a donc un champ de commande plus un champ message et un champ titre ou volume dans le quel on passe les paramètres de volume.

**Comment by KiwiHC16** [comment]
En gros ta question est comment je mets des paramètres a une commande de start/stop d'un timer ?
Est ce bien cela ?

**Comment by djsyl** [comment]
yes docteur

**Comment by KiwiHC16** [comment]
Je ne me souviens pas avoir mis en place cette possibilité.
Tu peux probablement passer par un scenario.
http://kiwihc16.free.fr/Timer.html#commande-ou-scenario
Il faudrait vérifier que cela fonctionne car je n'utilise pas/plus cette possibilité dans mon réseau.

**Comment by djsyl** [comment]
Bonjour, Désolé
Cela semblait être la bonne idée 
j'ai reproduit ce qui est dans ta doc a l'identique a l'exception du N° ID du scénario mais çà ne fonctionne pas.

**Comment by KiwiHC16** [comment]
Ok il faut que je regarde le code.

**Comment by KiwiHC16** [comment]
Will be followed in Timer part: https://github.com/KiwiHC16/Timer/issues/2
Closed here.
