### ISSUE TITLE
Abeille sur buster 

### ISSUE THREAD

**Issue by rvitch** [KiwiHC16/Abeille#869]
Hardware Pi4 sous buster.
J'ai basculé sur la bêta et le plugin semble fonctionner, la ruche en.tout cas, car pour le reste, aucun des devices ne semble communiquer.
Sur les devices que je n'ai pas touché du tout, quand je les réveillent ils signale bien communiquer avec le contrôleur (3 flashs) mais aucune valeur ne se mets à jour.
Et si je tente une re-inclusion, il ne se passe rien avec abeille mais je perd carrément la com contrôleur (un seul flash sur reveil).
Voici le logs aux alentour d'une inclusion qui fini tel que décrit plus haut.
[abeille.txt](https://github.com/KiwiHC16/Abeille/files/3950688/abeille.txt)
[abeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/3950689/abeilleMQTTCmd.txt)
[abeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3950690/abeilleParser.txt)
[abeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/3950691/abeilleSerialRead.txt)

**Comment by rvitch** [comment]
Les capteurs d'ouvertures associés avant la bascule de version et qui communiquent directement avec la zigate fonctionnent.
Aucun des capteurs de température xiaomi associés avant la bascule ne communiquent .
Aucun des modules sur secteur ne communique ni ne s'associe.
Aucun des capteurs sur pile ne s'associes.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```APS Data Confirm Fail```
Tu as beaucoup de ces messages qui indiquent que la zigate ne peut joindre l'équipement.

**Comment by KiwiHC16** [comment]
#872 a investiguer.

**Comment by KiwiHC16** [comment]
```
APS Data Confirm Fail
```
Tu as plein de ces messages qui veulent dire que la zigate ne parvient a dialoguer avec l équipement.

**Comment by KiwiHC16** [comment]
En terme de communication entre la zigate et abeille ca semble bon.
Premiere étape, remettre en ordre les routeurs du réseau zigbee et ensuite les device sur piles.
Peux tu :
- vider les logs Abeille et AbeilleParser
- prendre la premiere prise xiaomi
- l inclure
- et partager Abeille et AbeilleParser.

**Comment by rvitch** [comment]
Salut,
L'inclusion de la prise xiaomi n'arrive pas à se faire..
Voici abeille :
[abeille.txt](https://github.com/KiwiHC16/Abeille/files/3955728/abeille.txt)
Par contre pour l'instant parcer reste vide malgres ma config à 5000 lignes en debug.

**Comment by KiwiHC16** [comment]
Pas grand chose d'utilise dans log Abeille.
As tu du traffic dans AbeilleSerial ?

**Comment by rvitch** [comment]
Je ferme l'issue, désolé de t'avoir fait passé du temps la dessus, mon controleur usb TTL avait pris un coup...ca marche apres swap de ce dernier.
Version abeille stable sous buster = fonctionnelle

**Comment by KiwiHC16** [comment]
Super nouvelle.
