### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by flemzord** [KiwiHC16/Abeille#870]
Bonjour, 

Je viens d'avoir une update d'abeille sur mon Jeedom. 
Mais je trouve pas de Changelog, et les versions Github ne corresponde pas avec les versions Jeedom ? 

Cordialement,
Maxence

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Changelog.html

mais pas forcement à jour.

Sinon regarder: https://github.com/KiwiHC16/Abeille/commits/master

**Comment by KiwiHC16** [comment]
Besoin d'infos sur un sujet particulier ?

**Comment by KiwiHC16** [comment]
http://kiwihc16.free.fr/Changelog.html#id7

**Comment by KiwiHC16** [comment]
Je clos car toutes les infos disponiblement sont accessible maintenant.
