### ISSUE TITLE
Zigate - Xiaomi flood captor in time-out after inclusion

### ISSUE THREAD

**Issue by dragonslore** [KiwiHC16/Abeille#873]
Hello,

I have the last version of Jeedom and Abeille plugin hosted on a docker container based on my Synology NAS.

Everything works fine for my Zigbee network except one Xiaomi aqara flood captor which turns in timeout few hours after its inclusion.

As you can see on the graph, the captor is not linked to the "ruche".

![abeille_capteur innondation](https://user-images.githubusercontent.com/18243286/70660214-f40b2d00-1c61-11ea-99fe-714647ee8748.jpg)

When I delete it and include it again, it remains connected and in sync few hours with a latency of 216. Battery is ok at 76%.
I put this captor at 1meter from the Zigate key and same thing is happening.

Do you have any idea what happens and how to solve this ?

Thanks a lot
Manu

**Comment by KiwiHC16** [comment]
Peux tu partager une photo de la zigate et du capteur ? (si je comprends ils sont l'un au dessus de l autre).

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by dragonslore** [comment]
Oui voici la photo
![20191212_082156](https://user-images.githubusercontent.com/18243286/70691232-dcab5e80-1cb8-11ea-9dba-9dadc40c9976.jpg)

**Comment by KiwiHC16** [comment]
Effectivement ce n'est pas un probleme de distance.
As tu une borne wifi ? tes voisins ? sur quelle frequence/canal ?

**Comment by dragonslore** [comment]
J'ai une borne wifi qui emet en 2,4ghz et en 5ghz dans l'appartement (livebox), ce n'est que ce capteur d'innondation qui est capricieux.

**Comment by KiwiHC16** [comment]
Sur le 2.4ghz, sur quel canal ?
Ou est cette livebox par rapport à la zigate et la capteur ?

**Comment by dragonslore** [comment]
Canal radio 1
La livebox est dans l'entrée à genre 5 mètres.

**Comment by KiwiHC16** [comment]
Ok et la zigate est sur quel canal ?
As tu du traffic permanent Wifi comme par exemple Camera Wifi, streaming par  le wifi ?
Sais tu si les voisins ont du wifi et sur quel canal ?

**Comment by dragonslore** [comment]
C'est une zigate usb, comment je peux connaitre le canal ? Je n'ai pas de traffic permanent en wifi sauf sur mon mobile. Pour les voisins c'est sur qu'il y a du wifi mais je ne connais pas leur config.

**Comment by KiwiHC16** [comment]
Pour le canal zigbee soit tu regardes dans la ruche en la rendant visiblen, soit dans la page des Abeille tu as un truc du genre:

![Capture d’écran 2019-12-14 à 17 42 34](https://user-images.githubusercontent.com/8549674/70851723-1dfa6480-1e99-11ea-8c6b-0f4bca35910b.png)

(Ici c est une version de dev donc la deuxieme colonne n'est pas renseignée mais toi tu dois avoir des valeurs.)

**Comment by dragonslore** [comment]
<img width="313" alt="2019-12-14_19h10_02" src="https://user-images.githubusercontent.com/18243286/70852740-5869fe80-1ea5-11ea-9a68-b6f7e0ae0819.png">

**Comment by KiwiHC16** [comment]
Comme tu peux le voir ici: http://kiwihc16.free.fr/Radio.html
Les deux bandes se chevauche, ce n'est pas idéal.
Peux tu changer le canal de la livebox ?

**Comment by dragonslore** [comment]
J'ai configuré sur 13 le canal de la livebox.

**Comment by KiwiHC16** [comment]
Des améliorations ?

**Comment by dragonslore** [comment]
Je te dis ça ce soir...

**Comment by dragonslore** [comment]
Merci pour ton aide ça semble mieux communiquer maintenant. A suivre...
