### ISSUE TITLE
Ajout modèle Tradfri à filament LED1842G3

### ISSUE THREAD

**Issue by Titom59** [KiwiHC16/Abeille#875]
Salut @kiwihc16 comme convenu je créer une issue, qu'as tu besoin pour la création du modèle?

**Comment by KiwiHC16** [comment]
Peux tu g’faire l inclusion de l ampoule avec le plugin en debug et partager le log Abeille et le log AbeilleParser ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Titom59** [comment]
Étant déjà inclu dans la zigate je suis obligé de la supprimé ou pas. Ou juste réinitialisé l'ampoule sans supprimer l'objet dans jeedom?

**Comment by KiwiHC16** [comment]
Eteints electriquement l'ampoule, attends 10s et allumes la de nouveau.
Puis partage le log Abeille et AbeilleParser. Ca devrait être ok avec une ampoule Ikea.

**Comment by Titom59** [comment]
voici les log
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3961684/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3961685/Abeille.txt)

**Comment by KiwiHC16** [comment]
```
[2019-12-13 17:16:14][AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); SQN : b5; Status : 00; Short Address : 9b3b; Length : 1e; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0101 (Dimmable Light); bitField : 01; InClusterCount : 07
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0003 - General: Identify
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0004 - General: Groups
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0005 - General: Scenes
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0006 - General: On/Off
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 0008 - General: Level Control
[2019-12-13 17:16:14][AbeilleParser][debug]In cluster: 1000 - ZLL: Commissioning
[2019-12-13 17:16:14][AbeilleParser][debug]OutClusterCount : 04
[2019-12-13 17:16:14][AbeilleParser][debug]Out cluster: 0005 - General: Scenes
[2019-12-13 17:16:14][AbeilleParser][debug]Out cluster: 0019 - General: OTA
[2019-12-13 17:16:14][AbeilleParser][debug]Out cluster: 0020 - General: Poll Control
[2019-12-13 17:16:14][AbeilleParser][debug]Out cluster: 1000 - ZLL: Commissioning
```

**Comment by KiwiHC16** [comment]
Un bon début.
Etape suivante, peux tu afficher la Ruche.
Dans la ruche il y a une commande getName, tu mets l'adresse: 9b3b
et tu lances la commande.
Puis tu partages Abeille et AbeilleParser.

**Comment by Titom59** [comment]
Voila pour toi 
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/3963857/AbeilleParser.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/3963858/Abeille.txt)

**Comment by Titom59** [comment]
par contre j'ai pas mal de "ZigBee Error Code unknown" dans abeille c'est normal?

**Comment by KiwiHC16** [comment]
```
TRADFRI bulb E27 WW clear 250lm
```

Y a plus qu'a faire un modèle dans les jours à venir.

Pour les erreurs on pourra regarder plus tard mais en regle general c'est signe de mauvais réseau zigbee.

**Comment by Titom59** [comment]
OK impeccable pour le modèle.

Niveau erreur je viens de rejeter un œil et en fait ça va j'en ai pas tant, c'était surtout parce que pour te sortir les logs j'ai coupé la plupart des équipement électriquement pour être sur de ne pas pourrir les logs et que tu n'ai pas à chercher dans je ne sais combien de lignes, du coup au moment de réalimenter tous ça j'avais pas mal de zigbee error.
 Est-ce que le peu de ces messages peuvent venir du fait que j'ai pas mal d'équipements de marque différente (ikea, hue, xiaomi etc...)? 

Par contre j'ai des erreur " php notice undefined index "assez régulièrement. Pareil pas de" Objet existe mais pas la commande je passe"

**Comment by KiwiHC16** [comment]
Pour les messages d'erreur il y a plein de raisons possibles. Difficile de te répondre.
Php index: je crois avoir fait une correction dans le master (pas encore utilisable).
" Objet existe mais pas la commande je passe": Pour les messages FF01 c'est normal, par contre pour d'autres commandes il faut regarder si des commandes ne seraient pas manquantes dans les modeles.

**Comment by KiwiHC16** [comment]
Je viens de faire un modele qui est dans le master.
Peux tu partager une image de l ampoule pour l'ajouter ?

**Comment by Titom59** [comment]
Un grand merci @KiwiHC16 pour, une fois de plus ta réactivité.
Voici l'image 
![tradfri-led-bulb-e27-250-lumen__0722195_PE733517_S5](https://user-images.githubusercontent.com/37124709/71165419-1946ff00-2251-11ea-9ebe-0c7251d929e8.jpeg)

**Comment by KiwiHC16** [comment]
Si tu veux essayé, récupères le fichier peso:
https://github.com/KiwiHC16/Abeille/tree/master/core/config/devices/TRADFRIbulbE27WWclear250lm
que tu mets dans /var/www/plugins/Abeille/core/config/devices avec son répertoire.
et le fichier image:
https://github.com/KiwiHC16/Abeille/tree/master/images
node_TRADFRIbulbE27WWclear250lm.png
dans /var/www/plugins/Abeille/images

**Comment by Titom59** [comment]
Au top c'est fait néanmoins faut-il reinclure pour mettre à jour ?

**Comment by KiwiHC16** [comment]
Oui (et effaces l ancienne Abeille si tu en avais une) ou fais un getNmae sur l adresse courte.
