### ISSUE TITLE
Prises legrand netatmo pas de refresh si pas d'action (routage problématique)

### ISSUE THREAD

**Issue by rvitch** [KiwiHC16/Abeille#877]
Bonjour Kiwi,

Je suis toujours sur mon soucis de prises legrand et leurs problemes de routage.
Je viens de m'apercevoir que ces prises ne rafraichissent pas leur statut si pas d'action dessus.
Le soucis engendré c'est que les end devices qui sont routés par ces prises ne communiques plus non plus si pas d'action.
Du coup, comme apres trois messages sautés, pertes des end devices.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
L'état de la prise et le routage ne sont pas liés normalement.
Quelle est ta configuration pour voir si je peux en mettre une en place et regarder ce qu'il se passe.
Jeedom <-> Abeille <-> USB/Wifi/Zigate ? <-> Prise Legrand <-> Capteur ?

Peux tu me rappeler quel est le capteur ?
Peux tu me partager une capture d'ecran de "Network Graph" et de "Table des noeuds".
M'indiquer qui est qui en fonction des adresses et qui pose quel probleme.

**Comment by Smanar** [comment]
Ça m’intéresse aussi.
J'en connait chez qui ça marche sans probleme (après je connais pas leur maillage), mais j'ai de gros problemes avec un inter sans neutre legrand et une sonde xiaomi, routage impossible.
Je me suis deja posé des questions sur le routage Legrand <> Xiaomi

**Comment by KiwiHC16** [comment]
Il faut que je vérifie mais un inter sans neutre n'est probablement pas un routeur mais un end device. Donc ca doit expliquer ton soucis.

**Comment by Smanar** [comment]
Si, si c'est un routeur, je peux le garantir, au départ on voit bien le maillage aussi, avec la sonde qui passe par lui, mais ça part en live des les premières heures.
J'ai essayé plusieurs reglages, avec attribute reporting, avec pooling, tjour pareil. Mais j'ai jamais vu quelqu'un d'autre se plaindre de ca a part moi, donc je pensais que ca venait de moi (et comme c'est un appareil sans neutre, j'ai pensé comme toi que ca pouvait l'expliquer, mais la pour le coup c'est bien une prise qu'il a)

**Comment by pipiche38** [comment]
Maillage Legrand
25 devices Legrand ( Inter W/o Neutre, Inter Volet, Micro Module, Prises) ainsi qu'une dizaine de remote Simple,Double

<img width="545" alt="Screenshot 2019-12-14 at 15 10 06" src="https://user-images.githubusercontent.com/8291674/70849822-de754d80-1e83-11ea-87e3-e6521b39c079.png">

PS/ Ce qui est certain, c'est que chacun de ces equipements a été connecté au Hub pour un upgrade firmware

**Comment by KiwiHC16** [comment]
Dans mes notes, je trouve:
Inter 220V sans neutre Dimmer Legrand

Capability Information: 0x8e
Coordinator: no
Full Function: Yes
AC Power: Yes
Rx On Idle: Yes
...

Donc Full Function devrait dire routeur. Mais je voudrais vérifier. Je vais en brancher un dans les jours à venir pour voir.

Donc deux tests à faire:
- verifier que le dimmer sans neutre est un routeur
- mettre un sensor xiaomi en routage prise Legrand.

C'est quoi ton End Device ?

**Comment by pipiche38** [comment]
Je te confirme que les Inter w/o neutre routent parfaitement. Contrairement aux Livolo, Tuya et autres inter w/o neutre
Maintenant comme je le précisais il est possible que ce soit un problème de firmware.

**Comment by rvitch** [comment]
PIPIche38
Le soucis traite de routage inter marques.
Tu nous montres que le routage de device legrand vers legrand, c'est super , d'une autre coté il y aurait vraiment un pb si les legrand ne routaient pas les legrand..
L'histoire de la mise à jour du firmware est intéressante mais le seul vrai test que tu pourrait faire pour amener de l'info pertinente  serait d'associer un end device xiaomi sur pile dans ton réseau pour voir comment il se comporte sur tes routeurs.

**Comment by rvitch** [comment]
Kiwi, 
Que ce soit moi ou smanar, il s'agit de capteur sur piles Xiaomi.

**Comment by pipiche38** [comment]
Il y a aucune raison que ça ne route pas. Il n’y a pas de notions de marque à ce niveau !
Le seul élément que je vois possible c’est un firmware bug, ce qui me semble possible pour un switch sans neutre 

Envoyé de mon iPhone

**Comment by Smanar** [comment]
Ok, alors @pipiche38 vient de me faire remarquer la version du firmware de mon inter dimmer, il a plus d'un an et n'a pas été mit a jour depuis qu'il a quité la centrale legrand, et j'ai loupé beaucoup de MAJ.

Ca peut expliquer pourquoi moi j'avais des problemes et pas lui.

Tu as la centrale Legrand @rvitch ?

**Comment by rvitch** [comment]
non pas de centrale Legrand ..

**Comment by tcharp38** [comment]
Tres vieux sujet sans activité depuis un moment.
Je clos mais à réouvrir si ca interesse qqn.
