### ISSUE TITLE
Interrupteurs Tuya/Zemismart

### ISSUE THREAD

**Issue by Evililim** [KiwiHC16/Abeille#883]
Bonjour,

Ma question : Est-ce que les nouveaux interrupteurs Tuya Zigbee fonctionnent avec la Zigate et Abeille ?

Je viens de découvrir de nouveaux interrupteurs Zigbee de Tuya ou Zemismart.
Le gros avantage, c'est qu'ils sont filaire, et peuvent remplacer les interrupteurs standards.
Ils sont au format européen, peuvent être installé dans une boite encastrable ronde, et surtout CE.
Liens AliExpress : [Interrupteur Zemismart](https://fr.aliexpress.com/item/4000087402218.html) - [Interrupteur Tuya (Choisir EU)](https://fr.aliexpress.com/item/4000411386577.html)

J'ai cherché des infos sur le forum Jeedom :
- [Un utilisateur dont l'interrupteur est bien associé, l'état remonte, mais pas d'action ON/Off possible](https://www.jeedom.com/forum/viewtopic.php?f=184&t=46826)
- [Un autre qui dit la même chose](https://www.jeedom.com/forum/viewtopic.php?f=148&t=46790&p=753161)

Les 2 post datent d'août.

Je voudrais savoir si ces interrupteurs fonctionnent aujourd'hui.

Merci,

Evi

![ezgif-2-a648d145286c](https://user-images.githubusercontent.com/12346464/70857893-52047280-1ef7-11ea-8eae-d8e2f6ee1967.jpg)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Bonjour Evi,
Je n'ai pas d'information sur ces produits.
Par défaut ils ne fonctionnent pas dans Abeille car il faut un modèle qui n'existe as aujourd'hui.
Si il fonctionne avec Zigate, alors depuis Abeille on peut l'interroger et voir ce qu'il nous raconte pour faire un modèle.
Est ce que quelqu'un en a un pour faire les tests ?
(Peux être peux tu contacter les personnes qui ont mis des messages pour qu'ils utilisent leur inter pour nous aider).

**Comment by Evililim** [comment]
J'ai trouvé ça sur le forum de la Zigate : [zemismart interrupteur mural 2 bouton](https://zigate.fr/forum/topic/zemismart-interrupteur-mural-2-bouton/)
Le probleme remonté est le même que sur le forum Jeedom, seul l'état remonte, pas les boutons d'action ON OFF.

J'en ai commandé qui arriveront vers le 10 janvier. Je pourrais faire des tests.
J'ai aussi fait une donation à la cagnotte, si tu veux en acheter un ;)

**Comment by deennoo** [comment]
J'en ai 10 de ce modeles : 

Simple double triple bouton, avec neutre et sans neutre.

Ils fonctionnent tous tres bien avec la zigate et le plugin Domoticz

**Comment by KiwiHC16** [comment]
Je viens de commander une version 3 boutons.
A suivre...

**Comment by Evililim** [comment]
J'ai reçu les interrupteurs 1 et 2 boutons. Le modèle 1 bouton fonctionne parfaitement !! Mais pas le 2 boutons.

Le 1 bouton :
- 🔵 L'état remonte bien
- 🔵 On/Off/Toggle fonctionne bien
- 🔵 Le widget est propre (logo ampoule pour état et 3 boutons action ON/Off/Toggle)
- 🔴 Pas d'image

Le 2 boutons : 
- 🔵 j'ai réussi à l’inclure dans abeille
- 🔴 1 seul  bouton apparaît dans les commandes

**Comment by KiwiHC16** [comment]
J'ai reçu un colis, je pense que le 3 boutons est dedans. Je devrais pouvoir tester prochainement...

**Comment by KiwiHC16** [comment]
Ok je viens de le brancher. Il est en trois boutons.
```
TS0003
```

```
[2020-02-26 11:35:56][AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); dest: Abeille1; SQN : 81; Status : 00; Short Address : b40F; Length : 14; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0100 (On/Off Light); bitField : 00; InClusterCount : 05
[2020-02-26 11:35:56][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2020-02-26 11:35:56][AbeilleParser][debug]In cluster: 0003 - General: Identify
[2020-02-26 11:35:56][AbeilleParser][debug]In cluster: 0004 - General: Groups
[2020-02-26 11:35:56][AbeilleParser][debug]In cluster: 0005 - General: Scenes
[2020-02-26 11:35:56][AbeilleParser][debug]In cluster: 0006 - General: On/Off
[2020-02-26 11:35:56][AbeilleParser][debug]OutClusterCount : 01
[2020-02-26 11:35:56][AbeilleParser][debug]Out cluster: 0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
Dixit Pipiche: Pour les switchs rien de particulier. Il s'appaire de façon standard avec le plugin Zigate de Domoticz

Il y a un attribut 0xffe2  sur le cluster 0x0000 (propriétaire) qui communique des infos. Pour l'instant pas décodé

**Comment by KiwiHC16** [comment]
Je viens de mettre le modele dans le master pour le 3 boutons.

**Comment by KiwiHC16** [comment]
L etat remonte que l'inter soit commandé depuis Abeille ou part un appui physique sur l inter.

**Comment by KiwiHC16** [comment]
@Evililim, peux tu me donner le nom de ton inter que tu trouveras dans la commande nom dans abeille.

**Comment by Evililim** [comment]
Désolé pour le retard :)
Le nom de l'inter 2 boutons : TS0002
Le nom de l'inter 1 boutons : TS0001

**Comment by KiwiHC16** [comment]
Ok je viens de faire les deux modeles. Je clos. On ouvrira une issue specifique si probleme. Sera dans la prochaine version.
