### ISSUE TITLE
Volets profalux et xiaomi ... routage possible ?

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#884]
Bonjour.
Juste une question d'ordre générale.
Qqn a t'il une expérience à propos du routage via des volets profalux ?
Mon appart est maillé par 5 volets profalux qui font office de routeur mais mes capteurs de température Xiaomi ne semblent pas utiliser cette possibilité.
Une idée ? Des suggestions ?
Merci

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je n'ai pas d'info la dessus. As tu moyen de sniffer les messages ZigBee ?

**Comment by tcharp38** [comment]
Je pensais passer par cette étape si aucun retour. Je reviens vers toi quand j'ai des nouvelles.

**Comment by KiwiHC16** [comment]
Je clos le sujet. Si besoin r-ouvre le.
