### ISSUE TITLE
Ruche en timeout depuis maj 11/12/19

### ISSUE THREAD

**Issue by Dreaky255** [KiwiHC16/Abeille#885]
Depuis la mise à jour du 11 décembre dernier, l'objet "Ruche" se met en timeout régulièrement (en moyenne toutes les 20 à 40min). Avant la maj le timeout était réglé sur 15min, je l'ai augmenté à 30min mais je continue de recevoir ces warnings.
Bien que la ruche soit en timeout, le plugin continue de recevoir les messages des autres "abeilles" sans soucis. Donc le plugin fonctionne correctement hormis ce timeout, mais ces notifications/warning sont très ennuyantes.

Ce qui a été fait :
- Redémarrage du système jeedom
- Extinction et rallumage du raspberry
- Unplug et re-plug de la zigate
- Arrêt et redémarrage du daemon
- Lancement des dépendances.
=> Sans succès.

Rien de particulier à signaler dans les logs.

On peut voir sur le screenshot que les heures de réceptions de certaines abeilles sont postérieures au dernier ping de la ruche (exemples entourés en rouge), preuve que ce timeout ne perturbe pas la réception des autres abeilles :
<a href="https://ibb.co/CKwX834"><img src="https://i.ibb.co/s9gDRdc/Capture.png" alt="Capture" border="0"></a>

Une piste pour régler le soucis ? Ou un c'est un bug ?

**Comment by rvitch** [comment]
Supprime la ruche et relance ton demon

**Comment by Dreaky255** [comment]
Je viens de faire la manip : suppression ruche et redémarrage du demon, pas d'amélioration. La ruche retombe en timeout alors que les autres abeilles continuent de recevoir des infos.

Au passage, le redémarrage du démon suite à la suppression de la ruche a généré une erreur SQL (clé duplicate sur une insertion, j'ai oublié de récupéré l'erreur, mais pas lié à mon prob à mon avis).

On peut voir sur le screen que la ruche n'a plus rien renvoyé dès 11min après sa création.

<a href="https://ibb.co/0YM4rTv"><img src="https://i.ibb.co/5s8pLmw/Capture.png" alt="Capture" border="0"></a>

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut, j'ai passé le polling de la ruche à une heure. Donc il faut changer le TimeOut à un peut plus d'une heure.
Mais ....
Pour ceux qui ont une ZiGate Wifi ca pause un soucis que je viens de trouver ce week end. Le lien tombe au bout de 5 minutes si les équipements n'envoient pas de message. Alors dans le master je suis revenu au polling toutes les minutes.

**Comment by Dreaky255** [comment]
Super merci. En attendant la montée de version, je passe le timeout à 1h+. Merci pour la correction et encore merci pour ton travail pour la communauté.

**Comment by KiwiHC16** [comment]
De rien. Bonne utilisation.
