### ISSUE TITLE
Abeille / Buster

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#888]
Bonjour Mister Kiwi

Alors voilà j'était sous stretch 
j'ai fait une sauvegarde  de mon jeedom
puis une installation de buster sur une carte neuve
nouvelle install jeedom puis restauration de la sauvegarde
depuis j'ais régulièrement des messages et un mauvais fonctionnement de Abeille ...

merci de ton aide

[Abeille.log](https://github.com/KiwiHC16/Abeille/files/3968407/Abeille.log)
[AbeilleMQTTCmd.log](https://github.com/KiwiHC16/Abeille/files/3968408/AbeilleMQTTCmd.log)
[AbeilleMQTTCmdTimer.log](https://github.com/KiwiHC16/Abeille/files/3968409/AbeilleMQTTCmdTimer.log)
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/3968410/AbeilleParser.log)
[AbeilleSerialRead.log](https://github.com/KiwiHC16/Abeille/files/3968411/AbeilleSerialRead.log)
[AbeilleSocat.log](https://github.com/KiwiHC16/Abeille/files/3968412/AbeilleSocat.log)
[Abeille_installSocat.log](https://github.com/KiwiHC16/Abeille/files/3968413/Abeille_installSocat.log)
[Abeille_update.log](https://github.com/KiwiHC16/Abeille/files/3968414/Abeille_update.log)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
[2019-12-16 15:05:19][DEBUG] : **deamon info: OUT**  deamon deamon_info: {"state":"ok","launchable":"ok","launchable_message":"","nbProcessExpected":5,"nbProcess":"5"}
[2019-12-16 15:05:25][DEBUG] : **deamon info: IN**
[2019-12-16 15:05:25][DEBUG] : deamon_info, nombre de demons: 4
[2019-12-16 15:05:25][INFO] : deamon_info: found 4/5 running.
[2019-12-16 15:05:25][DEBUG] : **deamon info: OUT**  deamon deamon_info: {"state":"nok","launchable":"ok","launchable_message":"","nbProcessExpected":5,"nbProcess":"4"}
```

Visiblement tu as un process qui crash. Lequel ?
Peux tu faire en ssh:
```
ps -ef | grep Abeille
```
quand tu as des soucis ?

**Comment by KiwiHC16** [comment]
On dirait que c'est AbeilleSerial qui tombe:
```
[2019-12-16 15:05:22][AbeilleSerialRead][error]CRITICAL Fichier /tmp/zigate n existe pas
```

Est ce un zigate WiFi ?

**Comment by KiwiHC16** [comment]
```[2019-12-16 15:05:22][AbeilleSocat][Info]Arret de Socat on relance dans 1 minute.
Arret de Socat on relance dans 1 minute.
[2019-12-16 15:06:22][AbeilleSocat][Info]Creation de la connection wifi.
Creation de la connection wifi.
[2019-12-16 15:06:22][AbeilleSocat][Info]Command: /usr/bin/socat pty,rawer,echo=0,link=/tmp/zigate tcp:192.168.0.252:9999
Command: /usr/bin/socat pty,rawer,echo=0,link=/tmp/zigate tcp:192.168.0.252:9999
```

Ca semble être la connection wifi qui tombe.

C'est probablement le probleme du timeout module wifi.

**Comment by KiwiHC16** [comment]
Peux tu faire un scenario qui fait un getVersion sur la ruche toutes les minutes et me dire si ca résout le probleme ?

**Comment by djsyl** [comment]
Oui c'est une Zigate WiFi

 ps -ef | grep Abeille
www-data 12637     1  0 11:05 ?        00:00:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSocat.php /tmp/zigate debug 192.168.0.252:9999
www-data 12698     1  0 11:05 ?        00:00:00 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleSerialRead.php /tmp/zigate debug
www-data 12700     1  0 11:05 ?        00:00:03 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleParser.php /tmp/zigate 127.0.0.1 1883 jeedom jeedom 0 debug
www-data 12702     1  1 11:05 ?        00:00:06 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmd.php /tmp/zigate 127.0.0.1 1883 jeedom jeedom 0 debug
www-data 12704     1  0 11:05 ?        00:00:03 /usr/bin/php /var/www/html/plugins/Abeille/core/class/../../core/class/AbeilleMQTTCmdTimer.php /tmp/zigate 127.0.0.1 1883 jeedom jeedom 0 debug
pi       19424 19285  0 11:14 pts/1    00:00:00 grep --color=auto Abeille

**Comment by KiwiHC16** [comment]
Je crois que c est la correction que j ai faite il y a deux jours dans le master:
https://github.com/KiwiHC16/Abeille/commit/c52b66065a5210fe577599ec852ee607680e6962

Mets en place le scenario.

**Comment by djsyl** [comment]
Pour le senario si j'ai bien compris :
programmé : */5 * * * *
puis une action: qui appel la version :
#[DETECTEURS][Ruche][Version]#

**Comment by KiwiHC16** [comment]
Yep, ca doit le faire.

**Comment by djsyl** [comment]
beaucoup plus calme au niveaux des messages je suis repasser de 5 a 1 minute
ca a l'air de tenir

**Comment by KiwiHC16** [comment]
5 est limite car le timeout est de 5 minutes.

**Comment by KiwiHC16** [comment]
Je clos. Ouvres une autre issue si soucis.
