### ISSUE TITLE
Network list / Table des noeuds: Voisine_name, IEEE au lieu du nom connu de la ruche

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#889]
J'ouvre ici un bug identifié dans l'issue #824.

Abeille: version Market "2019-12-11 01:01:06"
Zigate: FW 3.1a

Dans la table des noeuds, le voisin "ruche" n'est pas nommé. On trouve l'adresse IEEE au lieu du nom connu.

Exemple dans mon cas:
![image](https://user-images.githubusercontent.com/35221038/70931366-9139dd00-2037-11ea-98c6-44eee61b4a4a.png)

Et la table "Santé Abeille"

![image](https://user-images.githubusercontent.com/35221038/70931412-af074200-2037-11ea-8c1e-8cf49deacba2.png)

00158d0001edfac2 devrait être "Zigate"

A noter un point ouvert pour plus tard. Qq adresses inconnues comme "20918a0000048345" , "20918a0000048343" et "20918a000004833d". Ca ressemble à mes volets profalux sans etre les miens. Des volets du voisinage ? (je suis en appart). Mais alors pourquoi serait il dans mon réseau ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
#892

**Comment by KiwiHC16** [comment]
Je pense que j'ai corrigé ce problème dans le master:
https://github.com/KiwiHC16/Abeille/commit/40870dfb7b802fcd7a77f82320a69ce2fa3a2c47

**Comment by tcharp38** [comment]
Il y a une diff avec la version master du 23/jan/20 mais ca n'est pas encore ca :)
On trouve 0000 au lieu du nom de la ruche.

![image](https://user-images.githubusercontent.com/35221038/73119519-4dee5a80-3f63-11ea-8020-28b8ab92593f.png)

**Comment by KiwiHC16** [comment]
je n'ai rien changé dans le master sur ce sujet. Par contre il y a un probleme supplementaire que est le melange des ruches dans cette partie du plugin. Je dois travailler dessus.

**Comment by tcharp38** [comment]
Alors on s'est mal compris.
Tu as ecrit toi même juste avant "Je pense que j'ai corrigé ce problème dans le master: 40870df".
Quoi qu'il en soit je note une difference, on avait l'adresse IEEE complete. On a l'adresse courte maintenant. Mais dans tous les cas ca n'est toujours pas le nom de la ruche.

Le seul truc genant dans l'histoire est le resultat graphique plus compliqué car il considere 0000 et Ruche comme 2 periphs differents.

**Comment by KiwiHC16** [comment]
J'ai fumé la moquette. Il faut que je reprenne le sujet à 0 car je ne l'ai pas adapté pour Multi Zigate

**Comment by KiwiHC16** [comment]
Apres toutes les dernieres mise a jour dans la master le sujet doit etre couvert. Je clos.
