### ISSUE TITLE
Network list / Table des noeuds: Nom "Ruche" au lieu du nom connu

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#890]
Un autre bug dérivé du #824 

Bug mineur.
Le mot "Ruche" apparait en lieu et place du nom "Zigate" que j'ai donné à cet equipement.
Les autres équipements sont bien nommés.

Abeille: version Market "2019-12-11 01:01:06"
Zigate: FW 3.1a

![image](https://user-images.githubusercontent.com/35221038/70932464-1b834080-203a-11ea-9cc5-1b2307885fa3.png)

Le tableau "Santé Abeille"

![image](https://user-images.githubusercontent.com/35221038/70932543-4372a400-203a-11ea-86bb-a772a7941e76.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Effectivement, il faut que je corrige.

**Comment by KiwiHC16** [comment]
Push today in master

**Comment by KiwiHC16** [comment]
Should be in master with all latest modifications.
