### ISSUE TITLE
Address IEEE inconnues

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#892]
A noter un point ouvert pour plus tard. Qq adresses inconnues comme "20918a0000048345" , "20918a0000048343" et "20918a000004833d". Ca ressemble à mes volets profalux sans etre les miens. Des volets du voisinage ? (je suis en appart). Mais alors pourquoi serait il dans mon réseau ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Depuis la ruche: peux tu faire un getName sur l'adresse 7d7d:

![](https://user-images.githubusercontent.com/35221038/70931366-9139dd00-2037-11ea-98c6-44eee61b4a4a.png)

Et partager le log AbeilleParser ?

**Comment by tcharp38** [comment]
Désolé. Je suis incapable de faire cette manip.
J'ai bien trouvé "getName" dans les commandes de ma ruche mais et j'ai supposé qu'il fallait remplacer "address=#title#" par "address=0x7d7d" puis le bouton "test" mais ca ne menne nul part. Quant au résultat, j'imagine qu'il faut fouiller les logs mais la, rien ne bouge dans "AbeilleParser.log". Je ne vois que des messages de test dans "Abeille.log"

**Comment by KiwiHC16** [comment]
Mets juste:
7d7d
dans le champ.

**Comment by tcharp38** [comment]
Une fois la ruche "visible", et qq pistes via les forums, j'ai enfin qqch

![image](https://user-images.githubusercontent.com/35221038/71214328-5513b000-22b5-11ea-892e-edd2e4484db1.png)

**Comment by tcharp38** [comment]
Sans le "0x" ca donne + d'infos on dirait

![image](https://user-images.githubusercontent.com/35221038/71214427-91471080-22b5-11ea-9e9a-e1db08868179.png)

**Comment by tcharp38** [comment]
[AbeilleParser.log](https://github.com/KiwiHC16/Abeille/files/3985858/AbeilleParser.log)

**Comment by KiwiHC16** [comment]
Peux tu le refaire car la premiere fois il ne dit pas le trouver puis ensuite dit avoir trouvé la route.

**Comment by tcharp38** [comment]
Voila.
Ca t'inspire ?
[AbeilleParser-20dec19.log](https://github.com/KiwiHC16/Abeille/files/3989639/AbeilleParser-20dec19.log)

**Comment by KiwiHC16** [comment]
Il ne trouve pas 7d7d
Mais pourquoi 7d7d je ne trouve pas dans la table du debut.
Je vois 7d5d
Ceci expliquerait cela...

Peux tu essayer avec 7d5d ?

**Comment by KiwiHC16** [comment]
Du nouveau ?

**Comment by KiwiHC16** [comment]
Pas de nouveau. Je clos. A rouvrir si du nouveau.

**Comment by tcharp38** [comment]
Salut
Désolé pour mon silence.
Depuis que je suis passé sur la version Abeille de decembre, j'ai perdu tous mes capteurs et mon orangepi a planté plusieurs fois. Peut etre aucun lien mais a premiere vue trop de logs, plus de place dans /var/log.. plus de reponses de Jeedom.

Sauf si tu me dis que vas pousser une version officielle d'ici peu, je bascule sur le master et je reouvre les points si necessaire. Merci
