### ISSUE TITLE
Créer des télécommandes de scene et pas uniquement de groupe

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#896]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Support des "scenes" Zigbee via Abeille arreté. Ne fait pas de sens face aux scenaris Jeedom + flexibles.
