### ISSUE TITLE
Installation dépendances impossible sur RPI3 suite à évolution du install.sh

### ISSUE THREAD

**Issue by lukebr91** [KiwiHC16/Abeille#90]
https://github.com/KiwiHC16/Abeille/blob/9d8d38dd23d2fffe9c1ecadb4c67d7cc9ef4803e/resources/install.sh#L73

Plus possible de lancer l'install : 
> Erreur critique: les versions connues sont jessie et stretch.ici, on a stretch Erreur critique: les versions connues sont jessie et stretch.ici, on a stretch

**Comment by KiwiHC16** [comment]
@edgd1er peux tu regarder ca, ca doit être lié aux dernières modifications que tu as proposé et que j'ai poussé.

**Comment by edgd1er** [comment]
Oui, désolé, ce serait fait ce soir. Je me suis fait avoir par le case sensitive :( ou pas, sretch n'est un version ;)
