### ISSUE TITLE
HUE telecommande dimmer switch (@fred60fr)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#93]
@Fred60fr, je fais une issue spécifique pour la telecommande.
As tu une photo et des infos technique sur cette telecommande ?

**Comment by fred60fr** [comment]
c'est une hue dimmer switch que j'ai eu avec l'ampoule.
mais je me pose la question suivante : est ce utile de chercher a l'integrer car le but du jeu  n'est pas que jeedom remplace la telecommande  ? 
![img-0017](https://user-images.githubusercontent.com/36207614/36040138-ed673c30-0dc4-11e8-8210-09a2b4427fae.JPG)
![img-0016](https://user-images.githubusercontent.com/36207614/36040139-ee07f76a-0dc4-11e8-949e-5842fd709472.JPG)

**Comment by KiwiHC16** [comment]
J'ai la même alors je peux investiguer.
Je me pose la même question cf #52 
Ce que je sais sur elle c'est qu'elle est super pratique pour faire un reset d'ampoule IKEA.

**Comment by Marc--** [comment]
Je confirme avoir lu un peu partout que la télécommande permet un reset des ampoules, pas que Ikea, ça semble commun au ZLL.

Et rien n’empêche de l'utiliser comme télécommande Zigbee avec Jeedom. Je veux dire, si on peux recevoir ses boutons, ça fait une remote pour actionner différentes choses, pas forcément les ampoules non ?

D'ailleurs lors de mes recherches il y a quelques temps, j'ai pu découvrir que la télécommande de la Freebox révolution utilise du Zigbee. Personnellement je n'en ai plus, mais si certains se sentent chauds de la sniffer...

**Comment by lukebr91** [comment]
Dispo si besoin pour la télécommande, j'ai tenté une inclusion avec Appui AV+Free ais ne fonctionne pas (on peux rêver 😄)

Par contre il faut changer le firmware c'est ça?

**Comment by KiwiHC16** [comment]
@lukebr91  je crée une issue avec la télécommande Free. Essayons de garder ce fil pour la télécommande Hue.

**Comment by KiwiHC16** [comment]
Oui c est un reset ZLL.
J'ai des télécommandes DIO et Jeedom reçoit les infos sur appuis des boutons. Ensuite en fait ce que l'on veut avec les scénarios Jeedom. A voir si nous pouvons faire la même chose.

**Comment by KiwiHC16** [comment]
Dans les traces faites hier, je vois que cette telecommande fait comme les télécommandes Ikea, c'est a dire qu'elle defini un group puis une scène pour contrôler ses ampoules. Elle n'envoie donc rien vers le contrôleur lors d'appui sur ses touches. Lors d'une commande group, tous les routeurs repetent le message mais le zigate ne transmet pas l'info vers jeedom.

**Comment by KiwiHC16** [comment]
Inclus dans master ce soir.
