### ISSUE TITLE
Perte totale du réseau, plus de commandes et de remontées d’états 

### ISSUE THREAD

**Issue by Titom59** [KiwiHC16/Abeille#937]
Salut @KiwiHC16, cela fait 3/4 jours que je galère avec ma zigate une fois par 24h environ je perd tous le réseau, plus de commande prise en compte et plus aucune remonté d’état.
J'ai des log charger d'erreur, on en avait déjà parler dans l'issue #875.
Tous redémarre si je reboot jeedom.
je remarque aussi que le log AbeilleMQTTCmd fait presque 50Mo

[AbeilleParser (2).txt](https://github.com/KiwiHC16/Abeille/files/4005371/AbeilleParser.2.txt)
[Abeille (2).txt](https://github.com/KiwiHC16/Abeille/files/4005372/Abeille.2.txt)

**Comment by KiwiHC16** [comment]
Je regarde des mon retour. Semaine prochaine...

**Comment by KiwiHC16** [comment]
D'apres le log toutes les commandes envoyées à la zigate sont rejetées par la zigate.
Quand ca se produit pourrais tu partager le log AbeilleParser et le log AbeilleMQTTCmd ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peux tu me rappeler la version d'Abeille et de Zigate que tu utilises ?

**Comment by Titom59** [comment]
Pour le coup je suis tranquille avec ça depuis que j'ai reflasher la zigate avec la dernière version en date + un complète eeprom puis reinclusion.
Sinon je suis sur la dernière bêta d'abeille étant sur jeedom v4
Quoiqu'il en soit si ça se reproduit je t'envoie les les logs.

**Comment by KiwiHC16** [comment]
Ok alors je clos. Tu ouvriras une nouvelle issue.
