### ISSUE TITLE
Heiman HS1SA-N non reconnu

### ISSUE THREAD

**Issue by Bou-fon** [KiwiHC16/Abeille#938]
Hello Kiwi

j essaie d inclure ces detecteurs de fumées, sans succes malheureusement
ci dessous le parser de l inclusion
peux tu aider, SVP

merci et bonnes fetes
Phil

[AbeilleParser inclusion heiman HS1A-N.txt](https://github.com/KiwiHC16/Abeille/files/4009336/AbeilleParser.inclusion.heiman.HS1A-N.txt)

**Comment by KiwiHC16** [comment]
Il donne son nom
```
SmokeSensor-N-3.0
```

A mon retour on peut regarder dans les details.
Semaine prochaine.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
```
/var/www/html/plugins/Abeille/core/config/devices/SmokeSensor-N-3.0/SmokeSensor-N-3.0.json
```

Le modele est deja dans Abeille.

Peux tu vérifier que tu as le fichier ci dessus dans ton système ?

**Comment by Bou-fon** [comment]
Hello Kiwi

 

Desolé du retard, j etais absent

 

Tout d abord, meilleurs vœux pour cette nouvelle année et longue vie au plugin abeille 

 

Je viens de verifier et efectivement le fichier est bien present dans le repertoire 

Juste pour info je suis très limité sous linux, donc si tu as besoin de verifier des trucs compliqués, essaie de bien expliquer, SVP

 

Phil

**Comment by Bou-fon** [comment]
Hello Ben

as tu eu un moment pour traiter le soucis de ce capteur?
Merci de ton aide
Phil

**Comment by Bou-fon** [comment]
il me semble que j ai le meme pb que olivr2s sur le HS1SA-E
quand j execute les commandes que tu lui as demandé, j ai le time-time qui se met à jour sur la tuile du capteur sur jeedom
sinon j etais en time out

**Comment by Bou-fon** [comment]
hello
pas de news?
toujours pas d alarme lors d un test de fumée avec declenchemenbt du capteur. rien n est reporté dans Jeedom.

**Comment by KiwiHC16** [comment]
Ok je vais essayer d'en mettre un sur mon systeme pour tester.

Peux tu faire une commande Bind sur le capteur et partager le log AbeilleMQTTCmd et AbeilleParser ?

**Comment by KiwiHC16** [comment]
Peux tu vérifier que tu as un valeur dans la commande IEEE du capteur ?

**Comment by KiwiHC16** [comment]
Voir mes derniers commentaires dans #947

**Comment by Bou-fon** [comment]
Ok je vais essayer d'en mettre un sur mon systeme pour tester.

Peux tu faire une commande Bind sur le capteur et partager le log AbeilleMQTTCmd et AbeilleParser ?

Hello Ben

Donc dans le parser tu as ça
Quant à l autre rien, il reste vide
Tu  partles bien de la commande bindshort to smoke ?

phil

**Comment by Bou-fon** [comment]
Peux tu vérifier que tu as un valeur dans la commande IEEE du capteur ?

Résultat de la commande : 00158d000275865d

**Comment by Bou-fon** [comment]
La version de la zigate c est le SDK ?

SDK
031a

Si c est ça, il me faut upgrader

XD

**Comment by KiwiHC16** [comment]
D apres https://zigate.fr/2019/07/12/maj-firmware-zigate-version-3-1a/
3.1a doit être la version minimum:
```
Add support of cluster IAS_WD (0x0502). To manage alarm siren
```

Si tu es en 3.1a soit doit être Ok.

**Comment by Bou-fon** [comment]
Hello 

 

Dans ton message à propos de l issue olivr, tu dis :

« Je viens de mettre a jour ma zigate en 3.1b et cela fonctionne.

Mettez votre zigate au dernier firmware si ce n'est pas le cas.

Et là tu me dis que la 3.1A est bonne

J y suis en 3.1A et cela n fonctionne pas, je n ai aucune reception d alarme

Ce qui est quand meme la fonction principale d un detecteur de fumée :)

 

As-tu besoin d autres logs pour avancer?

**Comment by KiwiHC16** [comment]
3.1A était la dernière dispo jusqu’à ce matin.
La 3.1A est suffisante. 

Peux tu faire:
- vider le log AbeilleParser 
- vider le log AbeilleMQTTcmd
- faire les commandes bind 
- faire les commandes setReport
(Le capteur doit être réveillé lors de l exécution de ces commandes en appuyant de temps à autre sur le bouton en façade)
- puis appui bouton façade
Et partager AbeilleParser et AbeilleMQTTCmd.

**Comment by Bou-fon** [comment]
Hello hello

Ci-joint le parser des commandes demandées

L autre est vide

Cdlt

Phil

**Comment by KiwiHC16** [comment]
Peux tu regarder directement à l adresse:
https://github.com/KiwiHC16/Abeille/issues/938

Il n y a pas de fichier.

**Comment by Bou-fon** [comment]
oups! desolé
[AbeilleParser (2).txt](https://github.com/KiwiHC16/Abeille/files/4089824/AbeilleParser.2.txt)

le fichier parser
comme je te disais, dans l autre (abeillemqttcmd) il n y a rien

Phil

**Comment by Bou-fon** [comment]
d ailleurs, si ça t interesse, j avais capturé le parser lors de l inclusion d 1 detecteur, 
[AbeilleParser inclusion heiman HS1A-N.txt](https://github.com/KiwiHC16/Abeille/files/4089836/AbeilleParser.inclusion.heiman.HS1A-N.txt)

**Comment by KiwiHC16** [comment]
Le detecteur eeb5  detecte et remonte l info:
```
[2020-01-20 17:42:31][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 92; endpoint: 01; cluster id: 0500; src address mode: 02; src address: eeb5; zone status: 0021; extended status: 00; zone id: 01; delay: 0000
...
[2020-01-20 17:42:33][AbeilleParser][debug];Type; 8401; (IAS Zone status change notification )(Processed); SQN: 94; endpoint: 01; cluster id: 0500; src address mode: 02; src address: eeb5; zone status: 0020; extended status: 00; zone id: 01; delay: 0000
```

Zone status 20 puis 21 comme je l indique dans la doc: http://kiwihc16.free.fr/Heiman.html

Peux tu faire une capture d'ecran de la commande Etat:
![Capture d’écran 2020-01-21 à 11 21 03](https://user-images.githubusercontent.com/8549674/72796724-1e2c1380-3c40-11ea-9d0f-12cd0d4c4b4c.png)
 et la partager ?

**Comment by KiwiHC16** [comment]
Attention: l'appuie sur le bouton de facade déclenche l envoie de l alarme mais celle ci ne dure que quelques milliseconde (max 1 seconde) et de ce fait le widget n'a pas le temps de se rafraichir, donc on ne le voit pas à tous les coup sur le dashboard. Mais si tu fais un scenario avec le trigger detection de fumée alors le scenario sera déclenche. Tu peux aussi mettre un retour d'etat pour cette commande pour que l alarme reste au moins une minute.

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-01-21 à 11 28 40](https://user-images.githubusercontent.com/8549674/72797317-2df82780-3c41-11ea-95d1-20deed787670.png)

**Comment by Bou-fon** [comment]
j ai fait un scenario avec comme declencheur "etat" du detecteur. en prallele j utilise le plugin "alarme"
j ai beau m archarner sur le bouteur test du detecteur => aucun declenchement, les logs du scenario restent vides
ce qui me gene c est que dans le parametrage de l equipement, si tu testes la commande "etat", cela reste vide (ni 0, ni 1) voir image dessous. ce qui me fait dire que la commande arrive comme tu la vois dans les logs mais elle ne semble pas etre positionnée dans le flag "etat" de l equipement

![image](https://user-images.githubusercontent.com/59358434/72804742-6acc1a80-3c51-11ea-96cd-5012c4e2649b.png)
[Nouveau Microsoft Word Document.docx](https://github.com/KiwiHC16/Abeille/files/4091025/Nouveau.Microsoft.Word.Document.docx)

**Comment by KiwiHC16** [comment]
Tu es sur un vieux bug. Si tu regardes la commande elle est en mode binaire alors que la valeur qui remonte est 20 ou 21. Passe la commande état de binaire à numeric et ca devrait fonctionner.

**Comment by Bou-fon** [comment]
hello Ben

efectivement j etais sur binaire, mais le fait de mettre sur Numerique n a rien changé donc
j ai exclu un detecteur et reinclus pour repartir à 0 
refait les manip bind et setreport en actionnant le bouton et le flag "etat "n est toujours pas initialisé, rien. j ai historisé le flag de façon à voir si un changement furtif s operait => rien
d ailleurs cela se verifie dans les scenarios car la variable "etat" est à ""

pas top, désolé

**Comment by KiwiHC16** [comment]
Ok, le plus simple serai qu on fasse une session d'investigation en partageant les écrans.
Si tu es ok, tu installes sur une machine anydesk.com.
Tu me fournis le code d'access (par mail a kiwihc16 à free.fr) et on troubleshoot online.
Il faudrait que tu es préparé, un browser web avec jeedom d'affiché et deux ssh sur le jeedom.
Dis moi si ca t'intéresse.

**Comment by Bou-fon** [comment]
J utilise teamviewer pour le pc

Pratique et simple et surtout portable

Si tu veux on fait une session je prepare le browser et 2 SSH

**Comment by KiwiHC16** [comment]
Je te propose anydesk car je ne peux plus utiliser TeamViewer...

**Comment by Bou-fon** [comment]
Ok dès que tu es prêt , tu me di

**Comment by KiwiHC16** [comment]
Je suis dispo presque toute la journée.
Envois mail avec code et je me connecte.

**Comment by Bou-fon** [comment]
done

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-01-22 à 15 56 13](https://user-images.githubusercontent.com/8549674/72904775-b8b75000-3d2f-11ea-84a7-7c9cb49ccea7.png)

Dans le capteur SmokeSensor-N-3.0. la valeur de l attribut est 0000 et pas 0002.

Modele specifique fait dans les modeles.

**Comment by KiwiHC16** [comment]
Faire dans le master le nouveau modele comme fait sur ma machine en prod.
Et trouver pourquoi le premier modele tester refuse de remonter son alarme alors qu il le faisait au debut. Comment faire une reset de la bete ?

**Comment by KiwiHC16** [comment]
Modele fait et mis dans le master.

**Comment by KiwiHC16** [comment]
[030813172350.pdf](https://github.com/KiwiHC16/Abeille/files/4097968/030813172350.pdf)

Doc trouvée sur le net.
Pas d info sur reset du device.

**Comment by Bou-fon** [comment]
apres avoir enlevé la pile et remis
le detecteur en defaut retourne bien l alarme
Merci Kiwi :-)

**Comment by KiwiHC16** [comment]
Super !!!
Niclek !!!!

Je viens de publier aussi une modif dans le master ce qui fait que les futures inclusions devraient être plus simple.

**Comment by KiwiHC16** [comment]
Je clos alors.
Si autre soucis, ouvres une autre issue.

**Comment by Bou-fon** [comment]
Pas de soucis

 

Encore merci pour ta disponibilite
