### ISSUE TITLE
IR Ikea

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#942]
https://community.jeedom.com/t/abeille-detecteur-ikea/5690/5

**Comment by KiwiHC16** [comment]
- mettre la sensibilité lumineuse sur Soleil pour qu'il vous detecte même avec de la lumière.
- Faire une inclusion (zigate en mode inclusion et clignote) du detecteur IR Ikea en faisant 4x OO sur le bouton au dos du capteur. Il a fallu que je le fasse mainte fois avant que celui ci s'appaire au réseau.
- Le device doit apparaitre dans le dashboard (rafraichir)
- ![Capture d’écran 2020-01-18 à 02 30 31](https://user-images.githubusercontent.com/8549674/72656287-81951780-399a-11ea-9d90-3d39330dfe1d.png)
- Dans la page de configuration, selectionner le capteur IR, positionner le groupe (exemple: AAAA) et faire set Group Remote (Il faut reveiller le capteur pour qu'il accepte la demande, faites le bouger devant vous pour qu il vous detecte et se reveille).
- ![Capture d’écran 2020-01-18 à 02 32 19](https://user-images.githubusercontent.com/8549674/72656315-c28d2c00-399a-11ea-95ad-734309fd9c21.png)
- Selectionner une Ampoule Ikea, definissez le groupe (le meme) et faite un set Group.
- Ca devrait fonctionner. En bougeant le detecteur vers vous, l ampoule doit s'allumer le temps du timer puis s'éteindre.

**Comment by dams74** [comment]
Merci @KiwiHC16  mais comment faire pour déclencher un scénario?

**Comment by battousai90** [comment]
Hello @KiwiHC16 

J'ai le nouveau détecteur ikea e1745.
L'inclusion fonctionne, il apparaît bien dans le dashboard.
Par contre impossible d'ajouter un groupe.
ce nouveau capteur n'a plus de potentiomètre pour pour mettre sur soleil et régler le timer, mais  2 boutons, 1 pour nuit ou jour comme sur l'ancien, et un pour la luminosité, le réglage du timer a disparu, apparemment il sera par défaut sur 3 minutes.
As-tu réussi a paramétrer ce nouveau capteur ?
Merci d'avance pour ta réponse.

**Comment by KiwiHC16** [comment]
@dams74, tu declares le groupe dans la zigate aussi. Alors Abeille reçoit le messages sur l'objet IR Ikea si je me souviens bien.

**Comment by KiwiHC16** [comment]
@battousai90, je ne possède pas ce capteur alors difficile de te répondre. Je mets le lien vers la cagnotte si tu veux mettre qq € pour que je le teste. Si j'en avais un je pourrai sniffer les messages pour voir si il fonctionne de la meme manière que celui deja intégré.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
apres avoir mis la zigate dans le groupe:
```
[2020-01-22 16:53:04][AbeilleParser][debug];Type; 8095; (Remote button pressed (ONOFF_UPDATE) a group response)(decoded but Not Processed); dest: Abeille; SQN: 00; endPoint: 01; clusterId: 0006; statusId: 02; sourceAddr: b7cd; cmd: 42
```

```
[2020-01-22 16:54:58][DEBUG] : fct message Topic: ->b7cd/Click-Middle<- Value ->42<-
```

**Comment by KiwiHC16** [comment]
Je viens d ajouter la commande dans l objet IR pour avoir l info qui remonte. 
C'est ok maintenant.

**Comment by KiwiHC16** [comment]
Donc apres avoir defini le groupe dans la zigate, le message vont remonté dans l objet IR dans la commande click middle.

![Capture d’écran 2020-01-23 à 00 51 10](https://user-images.githubusercontent.com/8549674/72944843-75360380-3d7a-11ea-9f42-0675bcce6670.png)

(il faut le master d aujourd'hui)

**Comment by KiwiHC16** [comment]
@battousai90, on va continuer avec une issue specifique sinon on melange les sujets et c est difficile a suivre. : #957

**Comment by KiwiHC16** [comment]
@dams74, peux tu tester ?

**Comment by dams74** [comment]
J'essaie dans la semaine, merci @KiwiHC16

**Comment by KiwiHC16** [comment]
Je clos. Ouvrir un autre issue si besoin.
