### ISSUE TITLE
Multizigate: Présentation / Affichage dans panneau de configuration

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#943]
Bonjour,
Pour le projet mutizigate, voici les améliorations visuelles qui seraient à intégrer:
-Sur la page de configuration, dans la section Paramètre, il faudrait un champ par Zigate permettant de les nommer, afin de pouvoir les identifier sur la page de gestion autrement que par Zigate 1, 2, 3, 4 ou 5. (donnant par exemple Sécurité pour la Zigate1, Automatismes pour la Zigate2, Osram pour la Zigate 3...)
![image](https://user-images.githubusercontent.com/46709337/72203424-d6e99a00-346b-11ea-8fbc-0e73924a8a7e.png)

-Sur la page de gestion du plugin, on retrouverait une ligne par Zigate (avec le nom personnalisé sur la page de configuration), avec en première tuile, le bouton d'inclusion, en second la ruche (nommée: Ruche + nom de la Zigate, dans l'exemple "Ruche Sécurité", "Ruche Automatisme", "Ruche Osram", "Ruche Zigate 4", et ce, afin qu'il n'y ait pas de conflit si plusieurs ruches sont dans le même objet), puis les abeilles appairées à la passerelle en question.
![image](https://user-images.githubusercontent.com/46709337/72203721-88d69580-346f-11ea-9e0f-3210945d9f48.png)

En espérant que tu trouveras pertinent ces demandes (faites avec un montage moins à l'arrache que par mail :p )

Bon courage et merci :)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
#866

**Comment by KiwiHC16** [comment]
> Sur la page de gestion du plugin, on retrouverait une ligne par Zigate (avec le nom personnalisé sur la page de configuration), avec en première tuile, le bouton d'inclusion, en second la ruche (nommée: Ruche + nom de la Zigate, dans l'exemple "Ruche Sécurité", "Ruche Automatisme", "Ruche Osram", "Ruche Zigate 4", et ce, afin qu'il n'y ait pas de conflit si plusieurs ruches sont dans le même objet), puis les abeilles appairées à la passerelle en question.

Fait dans le master.

**Comment by KiwiHC16** [comment]
> -Sur la page de configuration, dans la section Paramètre, il faudrait un champ par Zigate permettant de les nommer, afin de pouvoir les identifier sur la page de gestion autrement que par Zigate 1, 2, 3, 4 ou 5. (donnant par exemple Sécurité pour la Zigate1, Automatismes pour la Zigate2, Osram pour la Zigate 3...)

J utilise le nom donné à la ruche.

**Comment by Soyann** [comment]
Yesss, ça va être beaucoup plus simple comme ça :)
Après, pour être perfectionniste, peux-tu mettre ton icône sur fond transparent plutôt que blanc, et la mettre en taille plus petite (la page est déjà suffisamment longue comme ça :p )?
![image](https://user-images.githubusercontent.com/46709337/73200454-17693900-4137-11ea-8d77-53fdd08ec58e.png)
Merci beaucoup :)

**Comment by Soyann** [comment]
Autre piste: mettre le logo d'inclusion en tout petit à la suite du nom (voilà ce qui se fait à la concurrence :p avec la passerelle que j'aimerais bien voir disparaitre avec le multizigate)
![image](https://user-images.githubusercontent.com/46709337/73201540-821b7400-4139-11ea-97b5-98112ad0df2a.png)
(avec le popup quand on passe la souris sur ce petit + )

**Comment by KiwiHC16** [comment]
Pour les icones transparent, je ne sais pas faire. Sais tu faire ?

**Comment by KiwiHC16** [comment]
Je viens d ajouter la possibilité d'activer ou desactiver une zigate.
Il va falloir faire des tests car c est brute de fonderie.
Manque t il un truc de ta liste ?

**Comment by KiwiHC16** [comment]
Le petit plus serait faisable. Je vais regarder.

**Comment by KiwiHC16** [comment]
Petit plus remplace le gros icône.

**Comment by KiwiHC16** [comment]
https://www.dropizi.fr/blog/enlever-fond-image-transparent

**Comment by Soyann** [comment]
-Nickel pour le activer/désactiver (juste faire que par défaut si non précisé avant, le port de la zigate 1 est activé et les autres désactivés, sinon, tu vas au devant de râleries), mais faire en sorte que si ce paramètre a été modifié par le user, il soit mémorisé pour les mises à jours suivantes
-Pour le + de l'inclusion, mets le après le nom de la zigate et non avant, et mets le de couleur (sinon, les gens ne le verront pas), de plus la petite bulle quand on passe dessus avec la souris pour expliquer que c'est le bouton d'inclusion serait un plus non négligeable

**Comment by Soyann** [comment]
Tu assures sur le dernier update sur le visuel! Le + coloré après le texte, la bulle, c'est nickel :)
Bon, par contre, il reperd le port de connexion à la mise à jour :(

**Comment by Soyann** [comment]
Je dirais même plus: finalement, c'est la cata: il m'a perdu toutes mes abeilles de "Réseau Abeille", et ma ruche est en Time Out :'(

**Comment by Soyann** [comment]
Nouvel update: Le port est resté, mes équipements réseaux sont de nouveau là, mais toujours une ruche en Time Out et plus de communication avec les Abeilles

**Comment by Soyann** [comment]
Je vois

**Comment by Soyann** [comment]
Mais suis confiant pour la suite

**Comment by Soyann** [comment]
Préviens moi quand tu auras fixé tout ça (je me suis remis sur le canal stable en attendant)

**Comment by Soyann** [comment]
Hello, peux-tu faire un point sur la stabilité du Master actuel? (si tu attends des retours, on va pas avancer vu que je suis repassé en stable :p )
++

**Comment by KiwiHC16** [comment]
Elle est vraiment bien. Je tourne avec depuis plusieurs jours.
Bon la il faut que je repare une zigate qui a ete emportée par la tempête ...

**Comment by Soyann** [comment]
Hello, 
Bon, je viens de repasser ma machine secondaire en master et:
-maj ok, le port était bien configuré, mais le démon ne s'est pas lancé automatiquement -> ok après redémarrage du démon.
-Dans Network Graph, mes abeilles restent en gris (routeurs et End Devices), le bouton 'Refresh Network Information' ne marche pas.
-Dans Network List, Table des noeuds, mes abeilles ont disparue après un Get LQI Z1, et maintenant, j'ai un message: 'Fichier vide, rien à traiter'
-Malgré ça, j'ai l'impression que la communication marche toujours (maj des températures et état des capteurs de porte ok, valeurs dans Santé, dernière communication > à la maj)...

**Comment by KiwiHC16** [comment]
-maj ok, le port était bien configuré, mais le démon ne s'est pas lancé automatiquement -> ok après redémarrage du démon.
=> mis dans master

-Dans Network Graph, mes abeilles restent en gris (routeurs et End Devices), le bouton 'Refresh Network Information' ne marche pas.
=> ca devrait fonctionner maintenant

-Dans Network List, Table des noeuds, mes abeilles ont disparue après un Get LQI Z1, et maintenant, j'ai un message: 'Fichier vide, rien à traiter'
=> ca devrait fonctionner maintenant

Ok je clos ce sujet. Je vais publier une beta. Si tu peux tester la beta a partir de demain et ouvrir des issues cela permettra d'avoir une stable d ici la fin du mois.
