### ISSUE TITLE
Multizigate: automatismes d'inclusion (protection/exclusion/auto)

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#944]
Alors, lorsqu'on demande une inclusion sur une zigate, il faudrait:
-Vérifier qu'aucune autre Zigate est dans cet état, sinon, faire un stop inclusion sur les autres avant de lancer l'inclusion.
-Si l'IEEE est déjà renseigné sur une autre zigate, pour la mise à jour:
   +Faire un Remove IEEE sur l'ancienne zigate
   +Déplacer l'objet associé sur la bonne zigate

Cela évitera bien des bugs utilisateurs, et permettra de déplacer facilement les objets d'une zigate à une autre

Merci et bon courage

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Soyann** [comment]
Autres actions (de confort) à prévoir:
-Si une ZiGate est en inclusion, il faudrait qu'un second appuie sur le '+' ou sur la commande associée stop cet état 
-Modifier le message d'inclusion: 'Mode inclusion demandé pendant deux minutes sur ZiGate x qui doit se mettre à clignoter. Recliquez sur le bouton d'inclusion pour quitter ce mode'
-En fin d'inclusion, il faudrait lancer automatiquement un 'GetLQI Zx' afin de mettre à jour la Table des nœuds avec les périphériques fraichement ajoutés / mis à jour
Merci encore

**Comment by KiwiHC16** [comment]
-En fin d'inclusion, il faudrait lancer automatiquement un 'GetLQI Zx' afin de mettre à jour la Table des nœuds avec les périphériques fraichement ajoutés / mis à jour

=> Je ne vais pas le faire pour au moins deux raisons. 
--> Lors de l inclusion d'un modele il y a beaucoup de message et je ne veux pas surchager en plus. Je veux maximiser la chance d inclusion.
--> Les infos LQI sont mesurées par les équipements quand il y a des communications et ce n'est pas immédiat. Donc si on fait un refresh il est quasi sure qu on aura rien d interessant.

**Comment by KiwiHC16** [comment]
-Si une ZiGate est en inclusion, il faudrait qu'un second appuie sur le '+' ou sur la commande associée stop cet état
=> je ne vais pas faire cela car tu peux etre dans une situation ou tu veux avoir deux zigates en inclusion et que l'equipement a inclure decide du reseau qu'il prefere. 
=> Par contre je vais ajouter un message si deux Zigate en inclusion pour alerter l utilisateur

**Comment by KiwiHC16** [comment]
-Modifier le message d'inclusion: 'Mode inclusion demandé pendant deux minutes sur ZiGate x qui doit se mettre à clignoter. Recliquez sur le bouton d'inclusion pour quitter ce mode'

=> bouton specifique fait.

**Comment by KiwiHC16** [comment]
-Si l'IEEE est déjà renseigné sur une autre zigate, pour la mise à jour:
+Faire un Remove IEEE sur l'ancienne zigate
+Déplacer l'objet associé sur la bonne zigate

=> Cela n'est pas possible car certains équipements ne transmettent pas l adresse IEEE lors de l'inclusion. Abeille fait un polling apres pour essayer de le recuperer, ca peut mettre une heure pour le recuperer voir plus. Donc on peut se retrouver avec deux equipements dans Abeille pour le meme équipement physique. Si duplication alors cela sera visible dans la page santé du fait du double IEEE.

**Comment by KiwiHC16** [comment]
Clos.
