### ISSUE TITLE
Oups une collecte est déjà en cours

### ISSUE THREAD

**Issue by graouxx** [KiwiHC16/Abeille#945]
Bonjour,

Je pense qu'une collecte (GetLQI) a planté et du coup impossible d'en relancer une nouvelle, j'ai le message suivant à chaque fois que je relance.
Sans doute un lock quelque part.
![erreur zigate 2](https://user-images.githubusercontent.com/36622777/72221893-1644e300-355f-11ea-8b31-634cc4adb58b.png)

**Comment by Soyann** [comment]
Hello,
J'ai déjà rencontré ce souci: essayes d'effacer le fichier AbeilleLQI_MapData.json.lock en ssh et de relancer le refresh cache. Ça devrait débloquer.

**Comment by KiwiHC16** [comment]
Ou sur dernière version d'abeille, un redémarrage demon fiat le boulot (je ne me souviens pas si je l'ai fait avant ou après le version mi-decembre).

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
clos.
