### ISSUE TITLE
Abeille ne passe plus en mode inclusion

### ISSUE THREAD

**Issue by sebfar9172** [KiwiHC16/Abeille#946]
Bonjour

Voici les logs pour mon problème d'instabilité d'Abeille qui ne passe plus en mode inclusion (v4 3.1a). Le réseau ne semble plus fonctionner.
Je redémarre Jeedom et cela refonctionne. Le redémarrage d'Abeille ne suffit pas.

[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4051415/AbeilleParser.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/4051416/AbeilleMQTTCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4051417/Abeille.txt)

**Comment by KiwiHC16** [comment]
A premiere vue, tu as un volume de 
```
[2020-01-12 21:59:56][DEBUG] : fct message Topic: ->Abeille/Ruche/Zigate-8000<- Value ->(ZigBee Error Code unknown): 15<-
```
impressionant.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Et la queue des mesasges est longue tout le temps:
```
Je mets la commande dans la queue (Nb Cmd:24):
```

**Comment by KiwiHC16** [comment]
Peux tu partager une capture d ecran de la page santé ?

**Comment by sebfar9172** [comment]
ok dès que l'accès externe jeedom fonctionne :)

**Comment by sebfar9172** [comment]
voici
![Capture d’écran 2020-01-13 à 11 43 52](https://user-images.githubusercontent.com/52531214/72249617-029a8a80-35fa-11ea-9a49-8d518f7c99c5.png)
![Capture d’écran 2020-01-13 à 11 43 46](https://user-images.githubusercontent.com/52531214/72249618-03332100-35fa-11ea-9b86-59b0240bc164.png)

**Comment by KiwiHC16** [comment]
Tout semble ok de ce coté.
As tu essayé de faire une demande d inclusion depuis le bouton sur l objet ruche ? Est ce qu'elle clignote ?

**Comment by sebfar9172** [comment]
Pour l'instant tout est stable. Je remarque que dans le graphe certains composants sont gris même s'ils fonctionnent parfaitement et remontent les informations. Je préfère toucher à rien :) 
J'attendrais la nouvelle version.

**Comment by KiwiHC16** [comment]
On clos ce cas et on reprendra sur la nouvelle version ?
