### ISSUE TITLE
Perte des répéteurs Ikea

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#953]
Bonjour,
Ma seconde Zigate (future Sécurité) marchait jusqu'à peu sans problèmes, mais depuis que j'ai ajouté un troisième répéteur, et bien je les perds tous (les abeilles reliées directement au coordinateur restent par contre bien sur le réseau). 
Depuis, même si je n'en inclue (difficilement) qu'un dans Abeille, il perd au bout de quelques heures la connexion.
Je note dans AbeilleMQTTCmd le message suivant:
```
[2020-01-18 12:46:23][AbeilleMQTTCmd][debug]*************
[2020-01-18 12:46:23][AbeilleMQTTCmd][debug]Message 8000 status recu: ZPS_EVENT_ERROR Indicates that an error has occurred on the local node. The nature of the error is reported through the structure ZPS_tsAfErrorEvent - see Section 7.2.2.17. JN-UG-3113 v1.5 -> En gros pas de place pour traiter le message cmdAck: {"type":"8000","status":"15","SQN":"00","PacketType":"0100"} alors que j ai 1 message(s) en attente: [{"time":1579347983,"retry":3,"dest":"\/dev\/ttyUSB0","cmd":"0100","len":"000e","datas":"02d7940101000000000000010005"}]
[2020-01-18 12:46:23][AbeilleMQTTCmd][debug]J'ai 1 commande(s) pour la zigate apres reception de ce Ack: [{"time":1579347983,"retry":3,"dest":"\/dev\/ttyUSB0","cmd":"0100","len":"000e","datas":"02d7940101000000000000010005"}]
```
et dans AbeilleParser ça:
```
[2020-01-18 12:46:29][AbeilleParser][debug];type; 8000; (Status)(Not Processed); Length: 5; Status: (ZigBee Error Code unknown): 15; SQN: 03; PacketType: 0100
```
Une idée?

**Comment by KiwiHC16** [comment]
Pas d'idée comme çà. C'est très bizarre;
Es tu sur la version master d'Abeille ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by Soyann** [comment]
nop, je suis sur la stable depuis un second Jeedom relié à ma prod via Jeedom link... Si tu veux prendre la main pour jeter un œil, ce sera avec plaisir ;)

**Comment by KiwiHC16** [comment]
je me focalise sur la multi zigate. Quand ssera fait j'aurai un peu plus de temps. Désolé pour l instant.

**Comment by Soyann** [comment]
no problemo (tant que le multi zigate n'est pas prêt, ils sont de toute façon superficiels) ;)

**Comment by Soyann** [comment]
Salut,
Vu que tes travaux avancent à grand pas, je me suis décidé ce soir à tester sur cette seconde machine la version Master (ne pouvant ajouter de version beta, mon Jeedom étant en stable).
Premières constatations: 
-Après l'installation, il perd le port de la Zigate 1
-Dans Santé & Network Graph, plein d'Abeilles qui ne viennent pas de chez moi (vu les noms)
![image](https://user-images.githubusercontent.com/46709337/72962415-90256980-3db4-11ea-94c4-9491ba42d40f.png)
-Mes abeilles remontent bien, mais dans Santé, pas de IEEE (j'ai voulu re-synchoniser un premier répéteur, il m'a fait un nouvel objet)
-Dans Network Graph, tous les objets 'Pas dans Jeedom', et le texte de progression en 'Workping', impossible de refresh ou reload, malgré redémarrage du démon ou ré-installation des dépendances.
![image](https://user-images.githubusercontent.com/46709337/72962370-7126d780-3db4-11ea-957f-deefabf8731b.png)


Tout fut réparé en faisant un Get LQI Z1. Donc rien de grave, mais déstabilisant pour une mise à jour ;) Il ne reste que mon concentrateur marqué 'Pas dans Jeedom', et ma Ruche Abeille en gris. 

De plus, si je supprime ma ruche et relance le démon, elle renait bien de ces cendres, mais impossible de faire de Refresh Network Information, car j'ai de nouveau un Workping (obligé de passer par Network List pour relancer le scan)

Je vais inclure au fur et à mesure les répéteurs pour voir si ils tiennent maintenant, et te ferai un retour.

**Comment by Soyann** [comment]
Hello,
Le système à tourné toute la journée sans soucis avec 2 répéteurs, je viens à l'instant l'inclure le 3eme

**Comment by Soyann** [comment]
Bon, et bien ce coup-ci, on dirait que tout tient, et que le problème a disparu, tout aussi bizarre que le problème en lui même, on va croiser les doigts pour que ça ne se reproduise pas. En l'état, je clôture, et relancerai si ça revient ;)
