### ISSUE TITLE
nouveau détecteur IR ikea e1745 (suite: de IR Ikea #942)

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#957]

**Comment by KiwiHC16** [comment]
https://www.zigbee2mqtt.io/devices/E1525_E1745.html

**Comment by KiwiHC16** [comment]
The new model E1745 (2019, IP44)

**Comment by KiwiHC16** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1676

**Comment by KiwiHC16** [comment]
https://github.com/ioBroker/ioBroker.zigbee/issues/335

**Comment by KiwiHC16** [comment]
Commandé. Attente livraison pour l inclure...

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Il est dans déjà dans Abeille. En fait il se comporte comme le E1525 (avec de subtilités).
Il faut voir qu'une fois qu'il a envoyé une demande d'allumage il ne renverra pas de nouvelle demande avant 95s. C'est important pour la suite. Par defaut il utilise le groupe 0000.
Pour définir le groupe avec lequel il va discuté, il faut faire un set Group Remote avec le bon timing.
Pas évident car aucune indication n'est visible (Perso je peux le voir avec le sniffer). La manip a faire est la suivante.
- mettre le detecteur en mode jour et nuit
- Cacher le detecteur pendant au moins 95s
- selectionner le detecteur dans la conf abeille
- saisir le groupe, par exemple AAAA
- faire Set Group Remote
- et immediatement de-caché le capteur pour qu il vous detecte et se reveille pour envoyer sa commande
Voila le capteur doit etre programmé, sinon refaire la manip.
- Ajouter le groupe a une ampoule ici AAAA
- attendre 95s
- declencher le capteur en bougeant devant lui et l ampoule doit s allumer.

**Comment by gcourtot** [comment]
Hello KiwiHC16,

Tout d'abord merci beaucoup pour ton travail.
Cette histoire de 95 seconde ca aide pas :(
Je vais essayer ca, même si je sais que ca va marcher.
Du coup le timer est réglable pour l'extinction ? Et les 95 secondes ?

**Comment by dams74** [comment]
En fait c'est celui ci que j'ai ...

**Comment by KiwiHC16** [comment]
Pour l instant je ne connais pas de moyen de changer ces valeurs.

**Comment by battousai90** [comment]
> Hello KiwiHC16,
> 
> Tout d'abord merci beaucoup pour ton travail.
> Cette histoire de 95 seconde ca aide pas :(
> Je vais essayer ca, même si je sais que ca va marcher.
> Du coup le timer est réglable pour l'extinction ? Et les 95 secondes ?

C'était moi, j'i pas vu que j'était sur le compte du boulot.
J'ai réussi après 2 heures de cache cache avec le détecteur, il est très capricieux. Déjà que le set group remote est pénible avec les télécommandes et interrupteurs, mais alors la.
Enfin ça marche merci beaucoup Ben pour l'astuce des 95 secondes.
Après la lumière s’éteint au bout de 3 minutes; dommage que l'on puisse pas régler cette valeur, apparemment c'est figé, on va jouer avec des scénarios.

**Comment by dams74** [comment]
> > Hello KiwiHC16,
> > Tout d'abord merci beaucoup pour ton travail.
> > Cette histoire de 95 seconde ca aide pas :(
> > Je vais essayer ca, même si je sais que ca va marcher.
> > Du coup le timer est réglable pour l'extinction ? Et les 95 secondes ?
> 
> C'était moi, j'i pas vu que j'était sur le compte du boulot.
> J'ai réussi après 2 heures de cache cache avec le détecteur, il est très capricieux. Déjà que le set group remote est pénible avec les télécommandes et interrupteurs, mais alors la.
> Enfin ça marche merci beaucoup Ben pour l'astuce des 95 secondes.
> Après la lumière s’éteint au bout de 3 minutes; dommage que l'on puisse pas régler cette valeur, apparemment c'est figé, on va jouer avec des scénarios.

Tu le fait avec des ampoules ikea ou ampoule zigbee?
J'arrive pas à récupérer l'état de détection du capteur pour lancer un scénario

**Comment by battousai90** [comment]
Salut Dams,

De mon coté que des ampoules Ikea. Pour le scénario je ne vais pas utiliser le capteur comme déclencheur, mais plutôt le status de l'ampoule, après c'est une ampoule qui va s'allumer que par le capteur donc ca m'aide.
Après on peut contourner en :
- Créer un objet virtuel Déclencheur
- Créer une commande Etat en Binaire sur cet objet.
- Affecter un groupe a cet objet
- Affecter le détecteur au même groupe
Quand le détecteur détecte il envoi au virtuel et du coup tu récupère le statut du virtuel pour déclencher tes scénario, voilà l'idée générale a peaufiner.

**Comment by KiwiHC16** [comment]
Il faut ajouter le groupe utilisé par le detecteur et l'affecter à la zigate.

**Comment by KiwiHC16** [comment]
Je clos.
