### ISSUE TITLE
Mise à jour plugin et image dans Network Graph

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#958]
Hello,
Peux tu faire en sorte que l'image de fond dans Network Graph ne soit pas réinitialisée à chaque mise à jour?
En te remerciant d'avance

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Tu veux dire le nid d'abeille par defaut ?

**Comment by Soyann** [comment]
Yep, à chaque mise à jour du plugin, je dois rechercher mon jpg (ma carto d'aspirateur :p). Après, ce n'est pas ce qu'il y a de plus urgent, mais c'est enquiquinant de le faire (surtout en Master avec ses mises à jours très régulières) ;)

**Comment by Soyann** [comment]
Hello
Installation toujours fonctionnelle ici avec le dernier Master, par contre, toujours rien pour Network List / Graph ("Fichier vide, rien à traiter")
Lorsque Network Graph sera de nouveau opérationnel, pourras tu ajouter un menu déroulant permettant d'afficher sur la carte: toutes les zigate / Uniquement zigate X , pour que cela reste lisible (+ éventuellement le n° de zigate sur les points de concentrateurs / Routeurs / End devices)

En te remerciant

**Comment by KiwiHC16** [comment]
Mis dans le master ce jour. Sera dans la prochaine version.
