### ISSUE TITLE
Master 23/jan/20: Reprendre config mono zigate pour zigate1

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#960]
Le passage sur la version master suivante (passage market dec19 => master 23jan20)
commit 66628c2d17bcd279a54b5602af487674e0d953d1
Author: KiwiHC16 <moulinb@free.fr>
Date:   Thu Jan 23 01:10:25 2020 +0100

Il serait bon que la config zigate soit preservée: config mono zigate copié dans zigate1
C'est typiquement le cas pour le port "Abeille serial port".
D'autre part il semble necessaire de mettre les autres serial port sur "Aucun" par defaut.

Ca fait du sens ?

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Le "Aucun" par defaut, est un sujet connu . Je pensais l avoir corrigé... A re-travailler.
Pour le reste, je ne sais pas ce qui ne fonctionne pas car pour moi il ne faut rien toucher et cela fonctionne.
Peux tu être plus précis ? Capture d'écran ?

**Comment by KiwiHC16** [comment]
Ok dans le push.
