### ISSUE TITLE
Network list: changer l'ordre des tab

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#961]
J'avais déja fait la suggestion mais n'hesite pas à me dire si je "pinaille". C'est juste dans l'idée de rendre les choses + claires pour l'utilisateur et surtout limiter les questions et support.
Pour ma part je passe souvent et d'abord par la table des noeuds car c'est ici que je peux faire un "refresh" de l'image réseau.

Je suggère de changer l'ordre
 - Resumé, Graphique, Table des noeuds
par
- Résumé, Table des noeuds, Graphique

D'autre part, renommer
- Get LQI Zx
en 
- Refresh Zx

C'est basse priorité bien entendu.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Pinailles, pas de soucis.
Je fais le truc open source pour avoir le retour d experience et adapter pour avoir le meilleur truc possible.
Si je ne peux pas, ou vois les choses autrement on discute pour trouver le mieux pour tous.
Ok je regarderai. Perso je suis ok.

**Comment by KiwiHC16** [comment]
Get -> Refresh et aussi passé de 5 à 10 zigates possibles.

**Comment by KiwiHC16** [comment]
Fait. Il reste du boulot pour mettre en place le multi zigate. Je trouve dessus.
