### ISSUE TITLE
New Device : HEIMAN smart remote controller: HS1RC-E

### ISSUE THREAD

**Issue by Daradaal** [KiwiHC16/Abeille#962]
Bonjour,

J'ai commandé ce produit HEIMAN smart remote controller: HS1RC-E
https://fr.aliexpress.com/item/32975159931.html

Est-il compatible Abeille ? Je n'arrive pas à l'inclure

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Equipement inconnu pour moi et donc pour Abeille.
Avec la cagnotte je pourrai m'en procuré un pour investiguer. Mais pas tout de suite car j'ai d'autres equiopments qui attendent pour l instant.
As tu des informations techniques dessus ?

**Comment by KiwiHC16** [comment]
Pas d info, je clos.
