### ISSUE TITLE
Master 23/jan/20: Report "santé" incoherent, "Network list" semble ok

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#963]
Je suis passé de la version market dec19 à la master 23jan20.
commit 66628c2d17bcd279a54b5602af487674e0d953d1

La fenetre santé ne voit que ma zigate vivante.

![image](https://user-images.githubusercontent.com/35221038/73119710-25b42b00-3f66-11ea-9604-49993bf7ebc9.png)

Par contre côté "Network list/table des noeuds", apres refresh, Abeille semble recuperer les infos de mes volets donc ils sont en vie non ? D'autre part, malgre le status de santé NOK, mon scenario à bien ouvert mes volets comme prévu ce matin.

![image](https://user-images.githubusercontent.com/35221038/73119738-ab37db00-3f66-11ea-80bb-cfd79380598c.png)

Bon je voulais retenter une re-inclusion d'un de mes capteurs de temp mais je ne trouve plus le bouton "inclusion". Je log un autre pb.

**Comment by tcharp38** [comment]
Autre info:
- Tous les equipements sont rouges dans mon dashboard.
- Neanmoins, comme le fais le scenario, on controle bien les volets
- Apres un commande manuelle des volets par ex, le tableau "santé" dit enfin que le volet est OK

![image](https://user-images.githubusercontent.com/35221038/73119936-b68c0600-3f68-11ea-8c86-8d487e48ea03.png)

**Comment by Soyann** [comment]
Il faut que tu fasses un 'Network List' -> 'Table des noeuds' -> 'Get LQI Z1' pour qu'il scanne tout ton réseau, et qu'il rafraichisse l'état. Sinon, chez moi, tout est repassé en statut OK au fur et à mesure des remontées d'infos (l'info NOK dans santé n'est pour le moment pas pertinente juste après la mise à jour, car les abeilles continuent tout de même de communiquer)

**Comment by tcharp38** [comment]
Déja fait. C'est à partir de la que j'ai posé ce bug.
A l'heure actuelle mon paneau santé est toujours tout en rouge, excepté la zigate. Meme mon volet qui etait ce matin en vert est passé à nouveau en rouge.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je dois dire qu'avec la version multi-ligate, je n'ai pas trop testé/vérifié ces aspects.
Il faut que je regarde les details.

**Comment by KiwiHC16** [comment]
Bon je voulais retenter une re-inclusion d'un de mes capteurs de temp mais je ne trouve plus le bouton "inclusion" -> corrigé depuis.


Peux tu mettre a jour avec le master.
Redemarrer le demon.
Et voir ce qu'il se passe. Premiere observation tous les Abeille/xxxx doivent passer en Abeille1/xxxx et le reste doit mieux fonctionner.

**Comment by KiwiHC16** [comment]
Je clos le sujet car le mieux est de tester avec le master du jour.
Quasi impossible de reprendre une vieille version du master pour testé.
Pour moi je n'ai pas ce soucis sur le dernier master.
