### ISSUE TITLE
Master 23/jan/20: Ou se cache le bouton "inclusion" ?

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#964]
Jeedom v3
Abeille version master, commit 66628c2d17bcd279a54b5602af487674e0d953d1

Pb apparu suite passage "market dec19" => "master 23/jan/20"

Plus de bouton" inclusion" ?

![image](https://user-images.githubusercontent.com/35221038/73119842-da9b1780-3f67-11ea-936c-b78c28e4e80f.png)

**Comment by Soyann** [comment]
Salut,
Il faut afficher la ruche sur le dashboard pour faire l'inclusion depuis cette dernière (ou tester la commande de l'objet ruche). Cela vient du fait qu'il y a un potentiel de 5 inclusions différentes. 
D'où le #943

**Comment by tcharp38** [comment]
Ha ok. En mode  bidouille c'est acceptable mais pour un utilisateur final, pour qui dans la plupart des cas il n'y aura qu'une seule Zigate, c'est lourd.
Ne peut pas pas remettre de 1 à 5 boutons "inclusion ZigateX" qui s'affichent en fonction par ex de leur existence (config ok ou non) ?
Au pire, dans un premier temps juste remettre 5 boutons "Inclusion ZigateX".

Non ?

**Comment by tcharp38** [comment]
D'ailleurs je realise que je ne comprends pas le but du "multi-zigate".
- Si c'est pour permettre de depasser les limites d'une zigate, alors ca justifie plusieurs zigate sur la meme machine. Dans ce cas un seul bouton inclusion suffit. Il mettrait toutes les zigate en mode inclusion et celle qui peut prendre le periph, le prendra et signalera.
- Si c'est pour repartir les zigate sur differentes machines Jeedom (1 maitre, 1 à plusieurs esclaves), pour par exemple avoir une meilleure couverture reseau, alors 1 seule zigate par Jeedom sinon premier cas.

Je dis des conneries ?

**Comment by Soyann** [comment]
Je me cite (le but est de n'avoir qu'un jeedom pour toute la maison):
Les raisons peuvent être multiples: deux zones à couvrir sans routeurs entre les deux (via des zigate wifi), trop d’équipements pour une seule passerelle, différents équipements qui dialoguent mal ensemble (ex: prises Osram avec capteurs Xiaomi)… ou alors (comme dans mon cas), faire de la sécurité: j’ai chez moi une deuxième Zigate à l’opposé de la maison pour que mes capteurs de portes se connectent directement dessus: si je passe par des routeurs et qu’un ‘visiteur’ coupe le jus de la maison, autant ma box et mon Jeedom sont sur du courant ondulé, autant mes ampoules sont directement sur du 220V, donc mes abeilles se connectant dessus ne peuvent plus remonter d’informations)…

Il est donc important de savoir sur quelle zigate tu fais ton inclusion (et visualiser rapidement avec quelle zigate dialogue chaque Abeille)

PS: pour moi, quand tu te lances dans Jeedom, tu es forcement en mode "bidouille", d'autant plus quand tu choisis d'installer un plugin en mode Master plutôt qu'en branche stable ;) Cependant, je te rejoints sur le fait qu'à terme, ce bouton devra tout de même revenir quelque part sur la page de gestion du plugin, d'où la proposition #943

**Comment by tcharp38** [comment]
Ok pigé pour le multi zigate.
Et je vois qu'on est aussi en ligne concernant le bouton inclusion "ce bouton devra tout de même revenir quelque part sur la page de gestion".

Tous mes commentaires ne visent qu'a rendre le triplet Jeedom/Abeille/Zigate comme solution robuste et simple pour tout utilisateur, et donc limiter les questions/support. Donc la "bidouille" ne me semble acceptable qu'en master. Tant que ca va dans ce sens, je resterai impliqué pour faire avancer le schmilblick :) En tout cas merci à tous les participants pour le boulot effectué jusque la.

Le pb du/des futur bouton inclusion n'etant pas résolu, je garde ce point ouvert.

**Comment by KiwiHC16** [comment]
Salut,
Super d'avoir vos retour car ma vue dev est forcement impacté par mes besoins et les contraintes de dev.
Je vais aller dans le direction de  #943

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
C est couvert par les dernières modifications dans le master. Je clos le point.
