### ISSUE TITLE
Regrouper les "info group" par Zigate dans la page de configuration

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#967]

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Ajouter le tri à:
- page santé
- table groupe
- table scene

Prendre exemple sur table des noeuds.

**Comment by tcharp38** [comment]
Salut
Tu parles de la page config mais je ne comprends pas le sujet ni le lien avec le tri dont tu parles apres.
Tu peux detailler ?
Merci

**Comment by KiwiHC16** [comment]
C est un peu un sujet générique d'essayer de mieux présenter les informations.

Par exemple dans la table santé, si tu clic sur une tete de colonne alors la table est ordonnée suivant cette colonne. Cela permet de regrouper les sujets. Par exemple si je clic sur la colonner Ruche, tous les equipements de la ruche 1 sont en premiers, puis equipement ruche 2,... Si je clic sur Name alors tous les equipements de meme type son regroupés. Cela permet comparer les informations.

Cela est fait avec une fonction javascript que je n'arrive pas a faire fonctionner sur toutes les tables. L'idée c est de le mettre en place sur toutes les tables. (Depuis table des noeuds fonctionne aussi).

Dans la table group, table scene il faudra certainement ajouter une colonne Ruche (page config)

**Comment by tcharp38** [comment]
Comme je pas mal repris la page config, je ne me focalise que sur sa finalisation pour l'instant. Si tu as un croquis (photo, scan) de ton idée concernant ta colonne "Ruche" dont tu parles, je suis preneur.
Sinon on verra + tard.
Mais je comprends le sujet generique. Je suis en ligne avec toi. D'ou d'ailleurs le travail en cours sur config.

**Comment by tcharp38** [comment]
@KiwiHC16 Quel est le status de cette requete vis à vis de ce qu'est Abeille aujourd hui ?

**Comment by KiwiHC16** [comment]
![Capture d’écran 2021-01-21 à 14 05 18](https://user-images.githubusercontent.com/8549674/105355006-b3fed380-5bf1-11eb-9821-9f25922024b5.png)

Toujours valide. Ici ma prod avec les 4 réseaux (4 zigates) et tout est mélangé. 

Par exemple Terrasse et Salon ne sont pas sur le meme reseau. Et donc je peux avoir deux fois le meme groupe 0000 mais l un est pour le salon et l autre pour la terrasse. 

Une solution est peut être d ajouter une colonne 1 avec le reseau (Par ex: zigate1, zigate2,... ou par ex: Abeille1, Abeille2,... ou par ex: le logicalId de l equipement (Abeille1/XXXX)) et de pouvoir trier sur la base des titre de colonnes (Comme la table santé).

J'aime bien cette possibilité de trier pour faire des regroupements rapides et comparer.

**Comment by tcharp38** [comment]
Ok mais ca n'est pas la page de config.
Je l'appelle page de gestion (des abeilles) mais peut etre faut il trouver un meilleur nom.
Mais grace à ton exemple concret ca m'eclairci.

**Comment by tcharp38** [comment]
![image](https://user-images.githubusercontent.com/35221038/217294640-5faff233-ce78-415e-ab1d-6e69925b5af6.png)

Dans la beta du jour
230207-BETA-3
