### ISSUE TITLE
Master 28/01/2020 - Configuration - Liste des ports

### ISSUE THREAD

**Issue by olivr2s** [KiwiHC16/Abeille#976]
Bonjour Kiwihc16,

juste pour t’informer que suite à la mise à jour du master du 28/01/20 et les suivantes, je n’ai plus le port dans la liste pour ma Pizigate qui est sur le port GPIO (port ttyS3). J'ai uniquement le port moniteur, Wifi et les USB dans la liste.
Avant le liste des ports était très longue, mais il était présent dans la liste.
Juste pour préciser que je suis sur un Orange pi PC+ et que ma Pizigate est reconnue sur le port ttyS3.
Donc pour le moment je ne fait plus les mises à jour du master pour garder la liaison avec ma Pizigate.

![image](https://user-images.githubusercontent.com/59806634/73518869-c17ae680-43ff-11ea-890f-704cd001e71c.png)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
De nouveau dans le master.
