### ISSUE TITLE
Pizigate, activation forte de la lumière bleue

### ISSUE THREAD

**Issue by zabouille** [KiwiHC16/Abeille#977]
Bonjour
Je possède une Jeedom mini+ depuis plusieurs années en zwave.
J'ai décidé de monter une nouvelle jeedom pour utiliser du zigbee.
mais j'ai un problème d'activation forte de la lumière bleue de ma pizigate.

J’ai donc un raspberry P3B+
Installation de strech lite sur disque dds
Installation de jeedom V4 stable (installé automatiquement par le lien de la documentation jeedom)
J’utilise une Pizigate
J’ai installé le plugin abeille que j’ai activé. J'ai décidé d'utiliser les boutons mis à disposition:
Installation de Wiring Pi
Activation ttyS0
Reboot du pi
Sélection du port Cubiboard ((/dev/ttyS0) et sauvegarde
Les dépendances sont ok
Le démon est ok
Le voyant est bleu pale
La ruche se créée mais le voyant ne se met pas bleu lumière forte.
Je tente de programmer la pizigate avec le bouton mais cela donne une erreur (voir les logs)

Ma première question, à quel moment la led doit devenir bleu fort en suivant cette procédure ?
Comment résoudre le problème d’erreur de programmation ?

(pour info, j'ai effectué plusieurs autres installations avant :
Essayé la procédure en désactivant le bluetooth et en paramétrant les gpio manuellement et la lumière devient bien bleue forte.
Je sélectionne dans ce cas le port /dev/ttyAMA0, tout semble ok, la led se met bien à clignoter lors de l’inclusion mais rien ne s’inclus.
J’ai essayé ma pizigate sur un autre raspberry (modèle avant le 3 ) qu’on m’a prêté et là, j’arrive bien à inclure un équipement, la pizigate est hors de cause)

Merci de votre aide

[Abeille_installGPIO.txt](https://github.com/KiwiHC16/Abeille/files/4144174/Abeille_installGPIO.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4144175/Abeille.txt)
[Abeille_updateFirmwarePiZiGate.txt](https://github.com/KiwiHC16/Abeille/files/4144176/Abeille_updateFirmwarePiZiGate.txt)
[Abeille_installS0.txt](https://github.com/KiwiHC16/Abeille/files/4144177/Abeille_installS0.txt)

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Le log Abeille n'est pas beau.
GPIO semble ok.
L'upgrade firmware n a pas pu etre fait. Manque le soft.
InstallS0 log n est pas beau.
(Je ne me souviens pas du comportement de la led, surtout que je n'en ai pas sur mes montages).

**Comment by KiwiHC16** [comment]
Premiere chose à faire régler le ttyS0. Je pense que ton premier soucis est la. Surtout si tu as un ttyAMA0 qui fonctionne dans tes tests.

Connais tu:
- http://kiwihc16.free.fr/InstallationPiZiGate.html
- https://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3-4/

**Comment by KiwiHC16** [comment]
Voir aussi:
- https://zigate.fr/documentation/compatibilite-raspberry-pi-3-et-zero-w/

**Comment by KiwiHC16** [comment]
https://jeedomiser.fr/article/pilotez-vos-appareils-zigbee-avec-la-pizigate/

**Comment by KiwiHC16** [comment]
Pour ce faire, exécutez les commandes suivantes successivement. Vérifiez alors la différence de luminosité pour la Led bleu qui doit éclairer davantage après les avoir exécuter.

gpio mode 0 out
gpio mode 2 out
gpio write 2 1 
gpio write 0 0
gpio write 0 1

Le bouton Reset HW fait cette action et la ZiGate passe en led forte.

**Comment by zabouille** [comment]
Bonsoir et merci beaucoup pour les indications.

Dans le config.txt 
enable_uart=1 est bien présent
 
J’ai exécuté :
sudo systemctl stop serial-getty@ttyS0.service
sudo systemctl disable serial-getty@ttyS0.service
Dans le cmdline , console=serial0,115200 est bien enlevé

J’ai rebooté

J'ai mis à jour les GPIO
gpio mode 0 out
gpio mode 2 out
gpio write 2 1
gpio write 0 0
gpio write 0 1

La lumière est ok bleu forte 
Je passe en mode inclusion, elle clignote bien
J'appuie sur mon XIAOMI AQARA - CAPTEUR DE TEMPÉRATURE ET D'HUMIDITÉ ZIGBEE ( testé avec succès sur un autre raspberry).
Mais l’inclusion ne se fait pas (l'équipement n’apparaît pas).

(c'est ce à quoi j'étais arrivé également sur une précédente installation avec le bluetooth déactivé et l'utilisation du ttyAMA0)

Je permets de te remettre les logs récupérés après la tentative d'inclusion.

Merci beaucoup
Isabelle

[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/4149460/AbeilleSerialRead.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4149461/AbeilleParser.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/4149462/AbeilleMQTTCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4149463/Abeille.txt)



 )

**Comment by KiwiHC16** [comment]
Salut,
Les logs sont bien mieux maintenant. La Zigate discute avec Abeille et indique bien qu'elle est en mode inclusion.
Par contre je ne vois pas message venir du capteur.

Comment fais tu "J'appuie " ?

**Comment by zabouille** [comment]
Bonjour
Sur le capteur, il y a un petit bouton J'appuie dessus jusqu'à ce que la lumière du capteur se met à clignoter (elle clignote 3 fois) puis je lâche (quand je lâche, il y a un nouveau clignotement et quelques seconde après encore un).
J'avais testé ce même capteur quand j'ai testé ma pizigate sur un autre raspberry et il s'intégrait bien.
Je viens de tester également avec un autre aquara détecteur de mouvement et il ne s'intègre pas non plus. (j'ai remis les logs).

[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/4153248/AbeilleSerialRead.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4153249/AbeilleParser.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/4153250/AbeilleMQTTCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4153251/Abeille.txt)

**Comment by KiwiHC16** [comment]
```
petit bouton J'appuie dessus jusqu'à ce que la lumière du capteur se met à clignoter (elle clignote 3 fois) puis je lâche (quand je lâche, il y a un nouveau clignotement et quelques seconde après encore un).
```

=> et quelques seconde après encore un).
=> veut dire que l equipement n a pas rejoint le reseau zigbee.

Il faut 3 flash à la fin pour confirmer l appairage au réseau.

Dans les commandes de la ruche, il y a un bouton Erase PDM (ou qq chose comme ca). Fais tester sur cette commande, puis le bouton demarre Network, puis redemarres le demon Abeille, puis re-inclusion, ca devrait fonctionner.

**Comment by zabouille** [comment]
J'ai fait tester sur ErasePersistentData (c'est la seule commande que j'ai trouvé avec erase et j'ai lu dans un autre post que ce devait être ça)
Puis tester sur startNetwork
J'ai redémarré le demon et retenté l'inclusion avec mes 2 équipements mais rien n'y fait.
Je suis désolée de t’embêter...

Le fait que j'ai effectué l'installation sur un disque SSD au lieu d'une carte SD ne peut pas influer?

[AbeilleSerialRead.txt](https://github.com/KiwiHC16/Abeille/files/4155033/AbeilleSerialRead.txt)
[AbeilleParser.txt](https://github.com/KiwiHC16/Abeille/files/4155034/AbeilleParser.txt)
[AbeilleMQTTCmd.txt](https://github.com/KiwiHC16/Abeille/files/4155035/AbeilleMQTTCmd.txt)
[Abeille.txt](https://github.com/KiwiHC16/Abeille/files/4155036/Abeille.txt)

**Comment by zabouille** [comment]
Bon, je n'y comprend plus rien.
J'ai refait une installation complète sur sur carte SD en déactivant le bluetooth, ça fonctionne.
Du coup, je viens de refaire également complètement l'installation sur mon SSD à l'identique mais cela ne fonctionne par contre toujours pas, pas d'inclusion... c'est incompréhensible.
Demain, je vais récupérer un autre SSD et recommencer dessus.
A suivre...

**Comment by KiwiHC16** [comment]
Comment as tu installé le boot sur ton SSD ?
As ma connaissance le RPI ne peut pas booter sur le SSD et donc on boot sur le SD et on monte le SSD.
Ceci peut expliquer ton soucis car des modifs sont faites au niveau du kernel au moment du boot.

**Comment by zabouille** [comment]
Non non, pour le RPI B3+, pas de soucis, il démarrage bien tout seul sur le ssd.
J'ai récupéré un autre cable pour relier mon SSD au RPI, et bien maintenant ça fonctionne, bref, c'est le câble... Pourtant neuf...
Désolé de t'avoir embêté...
Et merci pour l’info sur les flash (Il faut 3 flash à la fin pour confirmer l appairage au réseau.)
Je vois tout de suite que ça marche
ET voilà, mes 3 détecteurs aqara sont inclus :)
Merci !!!

Je m'attaque prochainement à mes interrupteurs filaires de volets roulants (legrand with netatmo) mais pas de raison que j'ai des problèmes ;)
