### ISSUE TITLE
PiZigate: Revoir bouton "Progammer"

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#980]
Salut Kiwi.

"Programmer" sous entend que la PiZigate ne l'est pas.
D'autre part il n'y a aucune info concernant la version actuelle et la mise à jour potentielle.
La il faut que je trouve dans les logs des infos car en dehors de la fenetre suivante je ne sais pas ce qui s'est passé ou pas. La fenetre devient vide.
![image](https://user-images.githubusercontent.com/35221038/74030010-4476e080-49ae-11ea-956c-0c1f0b447f95.png)

Je suggère du coup
- De déplacer le bouton pour mettre "Firmware" à la place
- D'ajouter la version actuelle du FW "Actuel: XX"
- D'ajouter la version disponible "Mise-à-jour: YY"
- Et enfin le bouton "Programmer" devient "Mettre à jour"

En gros un affichage du style
Firmware  Actuel: XX  Mise-à-jour: YY  <Bouton "Mettre à jour">

Tu en penses quoi ?

Version Jeedom: 3.3.39
Version Abeille: market stable, 2019-12-11 01:01:06

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Je clos.
Tout est dans le master.
