### ISSUE TITLE
PiZigate: Mauvais port pour activation & programmation

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#981]
Sur la version Abeille market "2019-12-11 01:01:06", je note un souci dans la section PiZigate:

![image](https://user-images.githubusercontent.com/35221038/74036656-f7e6d180-49bc-11ea-9a51-096138be58ee.png)

"Activation ttyS0" n'est pas en ligne avec le port choisi, sauvegardé, et fonctionnel puisque j'ai pu appairer mon capteur de temp Xiaomi

![image](https://user-images.githubusercontent.com/35221038/74036711-10ef8280-49bd-11ea-8006-76e40ad4b045.png)

Du coup ca doit expliquer aussi pourquoi la "programmation" ne donne rien car ma PiZigate est en **ttyS1** et non pas ttyS0 (j'utilise des OrangePi Zero).

**Comment by olivr2s** [comment]
Même problème pour moi car ma PiZigate est sur le port ttyS3 sur mon orange pi pc+.

**Comment by KiwiHC16** [comment]
Dans la version master je donne accès à tous les port dispo sur le système.
Malheureusement le master n'est pas encore finalisé pour passer en stable.

**Comment by KiwiHC16** [comment]
Vous pouvez ajouter les trois lignes suivantes 89, 90, 91 dans votre système:
https://github.com/KiwiHC16/Abeille/blob/master/plugin_info/configuration.php#L89

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Avez vous testé ?

**Comment by olivr2s** [comment]
Quand j'ai voulu changer les lignes 89, 90 et 91 dans le fichier configuration.php, les lignes de codes étaient identiques à celles proposées.
J'ai fait la mise à jour, et il cherche toujours à faire la mise à jour du firmware sur le port ttyS0 au lieu du ttyS3 de ma Pizigate

**Comment by KiwiHC16** [comment]
Pardon je n'avais pa bien compris ton soucis. En fait c'est la programmation qui pose soucis. Dans ce cas il faut que tu mettes le bon port dans la ligne https://github.com/KiwiHC16/Abeille/blob/master/resources/updateFrimware.sh#L20

**Comment by tcharp38** [comment]
Kiwi.
J'ai une update à te proposer pour cette partie.
Comment je procede ?

1. je pousse ma branche "master" vers ton repo ?
2. ou je peux creer une branche "master_tcharp38" que je pousse vers ton repo ?
3. ou je suis obligé de creer un fork sous Github à partir duquel je pousse ?

Dis moi quelle procedure suivre.
Merci

**Comment by KiwiHC16** [comment]
Je ne suis pas un pro de ce sujet.
Jusqu'a ce jour des PR (Pull Requests) ont été proposé et je les accepte et ils sont integrés automatiquement.
Je ne sais pas ce qui est plus facile. 
Si tu as un fork aligné sur mon master alors peut etre un Pull Request depuis ton github serait le plus simple.

**Comment by edgd1er** [comment]
Bonjour @tcharp38, @KiwiHC16 
Le plus simple pour tout le monde sans polluer le repot de qq'un d'autre est de "forker" le depot et de proposer des pr sur la master ( dans ce cas), ou tout autre branche que Kiwi proposerait. Cela permet a toi de continuer a travailler, prendre les maj de kiwi et de proposer ton travail une fois qu'il est prêt.

**Comment by tcharp38** [comment]
Bien reçu. Je vais suivre cette piste.
Merci

**Comment by tcharp38** [comment]
Je viens de pousser une "pull request" avec une propale permettant de selectionner le port avant programmation + qq améliorations du script "updateFirmware.sh". L'interface donne ca

Ca n'est pas forcement l'idéal mais c'est une solution
![image](https://user-images.githubusercontent.com/35221038/75989465-9c443100-5ef3-11ea-888b-fa6eae50d69b.png)

A noter que j'ai limité les modifs et n'ai rien touché pour "activation ttyS0" et le "reset HW'. 
D'ailleurs dans quel cas on a besoin du reset PiZigate ?

**Comment by KiwiHC16** [comment]
Super je regarderai tard ce soir.

**Comment by tcharp38** [comment]
Solution intégrée dans le master. Devrait etre dispo dans la prochaine "stable".
