### ISSUE TITLE
Ajout de commande action pour le bouton Legrand by Netatmo avec option variateur

### ISSUE THREAD

**Issue by apages2** [KiwiHC16/Abeille#983]
Il existe deux fonctions disponible sur l'inter connecté de Legrand by Netatmo (067721/067771 et 064891)

La première permet d'activer ou de deactiver la fonction variateur, la seconde permet d'activer la led bleu du bouton soit a l'allumage, soit pour trouver l'interrupteur dans la nuit.

C'est fonction sont activable via les commandes :

Data 0101 > Enable dimmer
Data 0100 > Disable dimmer

endpoint: 1
cluster: 0xfc01
attribute_id: 0x0000
attribute_type: 0x09
value: '0101'

Pour la led c'est l'attribute 0x0001
Data 0x01 > enable led in dark
Data 0x00 > disable led in dark

endpoint: 1
cluster: 0xfc01
attribute_id: 0x0001
attribute_type: 0x10
value: 0x01

Est-il possible de rajouter ces commandes dans le template Legrand Dimmer Switch W/o Neutral ?

Pour plus d'info, j'ai trouvé les infos aux travers des sources suivantes :

https://github.com/doudz/homeassistant-zigate/issues/82
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883
https://github.com/maximushugus/Zigate-Legrand-with-Netatmo-HA

Merci

**Comment by apages2** [comment]
Pour info, j'ai reussi a modifier les paramètres de l'interrupteur grace a l'outil ZGWUI.

le type 10 pour l'attribut 0000 semble implementé, il est donc possible de le modifier directement

![2020-02-10 22_56_51-ZigBee Gateway User Interface](https://user-images.githubusercontent.com/12720395/74194098-e02b7980-4c58-11ea-85af-a726c0faaac7.png)
![2020-02-10 22_57_05-ZigBee Gateway User Interface](https://user-images.githubusercontent.com/12720395/74194100-e1f53d00-4c58-11ea-8f36-dab547f1e080.png)

le type 09 pour l'attribut 0001 ne semble pas fonctionner (pourtant je suis en 3.1c). j'ai donc executé une cmd de type raw

![2020-02-10 22_57_24-ZigBee Gateway User Interface](https://user-images.githubusercontent.com/12720395/74194106-e6b9f100-4c58-11ea-8873-23c06177a20d.png)
![2020-02-10 22_57_37-ZigBee Gateway User Interface](https://user-images.githubusercontent.com/12720395/74194110-e91c4b00-4c58-11ea-9206-e0ab55de3c3d.png)


Il n'y a plus d'urgence mais ca serait bien de l'implementer dans le plugin pour les prochains

Cordialement

**Comment by KiwiHC16** [comment]
Tres interessant !!!
Actuellement pas trop le temps de regarder ce sujet mais je le garde au chaud. Probablement pas avant 2 ou 3 mois...

**Comment by Guinnex** [comment]
Bonjour à tous,
il y a t'il des nouvelles sur l'intégration de l'option variateur avec l'interrupteur/variateur Legrand ?
Pour le moment mon interrupteur est bien présent mais aucune interaction avec celui-ci donc ce n'est pas la priorité mais si une solution existe pour la variation, je suis preneur. Encore merci pour votre travail.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Je vais essayer dans la semaine mais je ne promets rien...

**Comment by KiwiHC16** [comment]
Dimmerswitchwoneutral

**Comment by KiwiHC16** [comment]
Je viens de regarder le modele et les commandes setLegrandDimmerOn et off sont dedans.
Je ne vois pas la partie led.

Peux tu me faire une capture d'écran des commandes du dimmer ?

**Comment by Guinnex** [comment]
Bonsoir, je ne sais pas si ta demande me concerne ou si c'est pour apages2 mais je te fournis mes captures si cela peut t'aider. Pour le moment je rencontre un autre problème car les commandes sous Jeedom ne fonctionnent pas...
bonne soirée et merci
![Dimmer Legrand 01](https://user-images.githubusercontent.com/65119894/84069977-af234180-a9cb-11ea-9cf9-4601dbacff80.jpg)
![Dimmer Legrand 02](https://user-images.githubusercontent.com/65119894/84069986-b2b6c880-a9cb-11ea-9982-3d4ad3f5213b.jpg)
![Dimmer Legrand 03](https://user-images.githubusercontent.com/65119894/84069993-b5192280-a9cb-11ea-8244-08fb88179c62.jpg)
![Dimmer Legrand 04](https://user-images.githubusercontent.com/65119894/84070000-b77b7c80-a9cb-11ea-8d63-f08028672d78.jpg)

**Comment by apages2** [comment]
Bonjour,

il ne s'agit pas de la dispo des commandes, car effectivement le dimmeron/off est present, mais il s'agit de 2 commandes permettant d'activer ou pas le dimmer, d'activer ou pas l'alumage de la led bleu lorsque la lumiere de la piece est eteinte, voir activer ou pas la led bleu quand la lumiere est allumé.

en fait, ce sont les trois options disponible sur l'application home + control

**Comment by kaleofr** [comment]
Bonjour à tous,

en plus de ces 2 commandes, une fois le variateur activé, on peut récupérer le niveau d'allumage (Onlevel, 0008-01-0011), c'est à dire le niveau d'allumage que donnera le dimmer si la lumière est étiente et que l'on envoie juste une commande "On".

Je ne maitrise pas tout (notement les uniqId... j'ai juste changé quelques chiffres au hazard, les numéros des "includes"), peut-être pouvait-on également faire plus générique, mais si ca peux aider, voici mes fichiers:

Dimmerswitchwoneutral.json:
{
  "Dimmerswitchwoneutral": {
    "nameJeedom": "Legrand Dimmer Switch w/o neutral",
    "timeout": "60",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c7662071f",
      "icone": "Dimmerswitchwoneutral",
      "mainEP": "#EP#"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etat",
      "include5": "Level",
      "include6": "Onlevel",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include19": "getEtat",
      "include20": "getLevel",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel",
      "include29 2": "setLegrandDimmerOn",
      "include29 2 2": "setLegrandDimmerOff",
	  "include30": "setLegrandLEDOn",
      "include31": "setLegrandLEDOff"
    }
  }
}

Template/Onlevel.json:
{
  "0008-#EP#-0011": {
    "isVisible": 1,
    "name": "Onlevel",
    "order": 5,
    "isHistorized": "1",
    "Type": "info",
    "subType": "numeric",
    "invertBinary": "0",
    "template": "",
    "unite": "%",
    "configuration": {
	"uniqId": "5c07c76621e12",
      "minValue": "0",
      "maxValue": "100",
      "historizeRound": "0",
      "calculValueOffset": "#value#/255*100",
      "visibilityCategory": "All"
    }
  }
}

Template/setLegrandDimmerOn.json
{
  "DimmerOn": {
    "isVisible": 0,
    "name": "DimmerOn",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c07c7662525sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0000&attributeType=09&value=0101",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Template/setLegrandDimmerOff.json
{
  "DimmerOff": {
    "isVisible": 0,
    "name": "DimmerOff",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c07c766dsd2525sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0000&attributeType=09&value=0000",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Template/setLegrandLEDOn.json
{
  "LedOn": {
    "isVisible": 0,
    "name": "LedOn",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c07c76625222sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0001&attributeType=10&value=01",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Template/setLegrandLEDOff.json
{
  "LedOff": {
    "isVisible": 0,
    "name": "LedOff",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c00c76625222sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0001&attributeType=10&value=00",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Par contre, je ne connais pas la commande pour allumer la led bleu tout le temps (ici c'est uniquement lorsque de la lumière est éteinte).

Kaléo

**Comment by kaleofr** [comment]
Update!
grace au travail regroupé ici: https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Legrand-Netatmo-corner.md

J'ai pu ajouter l'allumage de la diode bleue lorsque la lumière est allumée:
WriteAttributeRequestActivateDimmer -> clusterId=fc01&attributeId=0002&attributeType=10&value=01   (value 01/00 pour on/off)
J'ai donc ajouté à la fin du fichier Dimmerswitchwoneutral.json les lignes suivantes:
  "include32": "setLegrandLEDOn_if_on",
  "include33": "setLegrandLEDOff_if_on"

et les templates qui vons avec:

setLegrandLEDOn_if_on.json
{
  "LedOn_if_on": {
    "isVisible": 0,
    "name": "LedOn_if_on",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c07c76625223sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0002&attributeType=10&value=01",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

setLegrandLEDOff_if_on.json :
{
  "LedOff_if_on": {
    "isVisible": 0,
    "name": "LedOff_if_on",
    "order": 6,
    "isHistorized": "0",
    "Type": "action",
    "subType": "other",
    "configuration": {
      "uniqId": "5c00c76625223sdsdff",
      "topic": "WriteAttributeRequestActivateDimmer",
      "request": "clusterId=fc01&attributeId=0002&attributeType=10&value=00",
      "repeatEventManagement": "always",
      "visibilityCategory": "Network"
    },
    "display": {
      "forceReturnLineAfter": "1"
    }
  }
}

Avec ca on peut donc allumer la led bleue, soit lorsque la lumière est éteinte, soit lorsqu'elle est allumée, soit tous les 2!

Kaléo.

**Comment by tcharp38** [comment]
Salut @apages2 @kaleofr 
C'est un vieux sujet. Ou en est on la dessus ? Toujours interessés ?
Merci

**Comment by kaleofr** [comment]
Comme tout fonctionne parfaitement chez avec ce que j'ai posté ici, je serais surtout intéressé par ne pas avoir à remettre mes fichiers à chaque mise à jour oui.

Le mécanisme des dossiers config/devices/ et devices_local fonctionne à l'envers à mon gout. Abeille devrait d'abord regarder en local puis en global. Ainsi, lorsque que le device est correctement implémenté le développeur peut le supprimer de son local.
De même une copie local permet de personnaliser un icone par exemple. Après  une mises à jours, un device qui se réanonce retrouve la config par défaut et l'icone par défaut même si on l'avait changé... a moins qu'une mise à jour est modifié cela.
Pour éviter ces problèmes, je n'ai pas fait les dernières mises à jours.
Autre soucis, les commandes locales n'existent pas, un device_local qui a besoin de commandes est également impacté par les mises à jours.

Désolé si ceci est un peu hors sujet mais c'est très impactant lorsqu'on a des devices pas encores supportés ou améliorés/personnalisés dans devices_local.

Kaléo.

**Comment by kaleofr** [comment]
petite précision, dans mes fichiers il faut modifier "Type" en "type". La majuscule pose problème.

**Comment by tcharp38** [comment]
Salut @kaleofr 

> je serais surtout intéressé par ne pas avoir à remettre mes fichiers à chaque mise à jour oui.

Tu fais allusion à quel fichier ?

> Abeille devrait d'abord regarder en local puis en global.

Je suis en ligne avec toi et c'est ce que j'ai modifié dans les dernieres versions. Local PUIS global.
Si tu vois un comportement different c'est qu'il y a un bug malgre mes tests.

> Après une mises à jours, un device qui se réanonce retrouve la config par défaut et l'icone par défaut même si on l'avait changé... a moins qu'une mise à jour est modifié cela.

La aussi j'ai fait en sorte que si l'équipement existe deja ce genre de parametre n'est pas retouché si il se reannonce. En gros toutes les infos d'affichage de l'équipement. Il y avait eu plusieurs retours la dessus.

> Autre soucis, les commandes locales n'existent pas, un device_local qui a besoin de commandes est également impacté par les mises à jours.

Un exemple ?

> Désolé si ceci est un peu hors sujet mais c'est très impactant lorsqu'on a des devices pas encores supportés ou améliorés/personnalisés dans devices_local.

Pas de soucis. On est en ligne.

**Comment by kaleofr** [comment]
Re:
> Tu fais allusion à quel fichier ?

Aux json qui sont publiés ci-dessus et qui contiennent les fonctions pour allumer/éteindre la diode bleu du bouton legrand quand la lumière est allumée et/ou quand la lumière est éteinte

> Je suis en ligne avec toi et c'est ce que j'ai modifié dans les dernieres versions. Local PUIS global.
> La aussi j'ai fait en sorte que si l'équipement existe deja ce genre de parametre n'est pas retouché si il se reannonce. En gros toutes les infos d'affichage de l'équipement. Il y avait eu plusieurs retours la dessus.

Exellente nouvelle, je vais faire la mise à jour et regarder

> > Autre soucis, les commandes locales n'existent pas, un device_local qui a besoin de commandes est également impacté par les mises à jours.
> Un exemple ?

Le fichier ci-dessus par exemple "setLegrandLEDOff_if_on.json" est une commande de "Dimmerswitchwoneutral.json"

Je m'appercois d'ailleurs que je n'est pas publiée le dernier Dimmerswitchwoneutral.json complet:

Dimmerswitchwoneutral.json :
{
  "Dimmerswitchwoneutral": {
    "nameJeedom": "Legrand Dimmer Switch w/o neutral",
    "timeout": "60",
    "Categorie": {
      "automatism": "1"
    },
    "configuration": {
      "uniqId": "5c07c7662071f",
      "icone": "Dimmerswitchwoneutral",
      "mainEP": "01"
    },
    "Commandes": {
      "include1": "nom",
      "include2": "societe",
      "include3": "SW",
      "include4": "etat",
      "include5": "Level",
      "include6": "Onlevel",
      "include8": "On",
      "include9": "Off",
      "include10": "Toggle",
      "include11": "setLevel",
      "include19": "getEtat",
      "include20": "getLevel",
      "include21": "getManufacturerName",
      "include22": "getModelIdentifier",
      "include23": "getSWBuild",
      "include24": "Identify",
      "include25": "Group-Membership",
      "include26": "BindToZigateEtat",
      "include27": "BindToZigateLevel",
      "include28": "setReportEtat",
      "include29": "setReportLevel",
      "include29 2": "setLegrandDimmerOn",
      "include29 2 2": "setLegrandDimmerOff",
	  "include30": "setLegrandLEDOn",
      "include31": "setLegrandLEDOff",
 	  "include32": "setLegrandLEDOn_if_on",
      "include33": "setLegrandLEDOff_if_on"
    }
  }
}

Dans tous les cas, merci pour le travail accompli, il est vrai que j'avais moins de temps pour jeedom dernièrement.

**Comment by tcharp38** [comment]
Voila la mise à jour que je vais pousser sur le GIT, avec tes commandes.
En ligne avec ca ?
[core.zip](https://github.com/KiwiHC16/Abeille/files/7188594/core.zip)

**Comment by tcharp38** [comment]
Pour info, la beta 210919-BETA-1 contient les modifs que j'ai poussé.

**Comment by kaleofr** [comment]
Tout semble OK!
J'ai par contre quelques améliorations a proposer pour https://github.com/KiwiHC16/Abeille/issues/1737
-> Le contrôle du blanc le plus chaud (ca va jusqu'à 1700k chez moi) un bouton et un slider (2 commandes).
Je détail ca dans l'issue https://github.com/KiwiHC16/Abeille/issues/1737
-> Le Toggle (pourquoi la commande est-elle en obsolète maintenant?)

Merci,
Kaléo.

**Comment by tcharp38** [comment]
Donc pour toi ce sujet est clos ou pas encore ?

**Comment by kaleofr** [comment]
Celui-ci est clos pour moi oui. Merci encore.

**Comment by tcharp38** [comment]
Ok je clos. A réouvrir si besoin.
