### ISSUE TITLE
LQI: mono -> multiZigate , no information gathered

### ISSUE THREAD

**Issue by edgd1er** [KiwiHC16/Abeille#987]
https://github.com/KiwiHC16/Abeille/blob/3b18ef9b98e4c4f09c062af683e3b53dc70b36f9/Network/AbeilleLQI.php#L281

I think LQI was the first element you converted to multi zigate, before serialPort were indexed.
Abeille Config saving rename the field key name. 

'Abeille', 'AbeilleSerialPort1', '/dev/ttyUSB0'

Therefore, after saving, the line 281 set the bad value and LQI requests return nothing.

I guess there is something to do, while restarting the daemon, a warning to send, requesting for a plugin settings saving if an "AbeilleSerialPort" is found....

No sure though, How would you like to manage the change.

**Comment by KiwiHC16** [comment]
Semble ok avec le dernier push to master.
