### ISSUE TITLE
Impossible d'inclure Aqara 2

### ISSUE THREAD

**Issue by StephaneBro** [KiwiHC16/Abeille#988]
Bonjour,

Je suis un "ancien" utilisateur du pluging Zigate qui ne me permettait pas toutes les commande sur mes objets, je suis venu sur Abeille.
Je suis sous Jeedom V4.0.40 avec une clé Zigate en firmware 3.1a.
J'ai réussis à inclure des capteurs "xiaomi température rond" et "interrupteur simple". Ils fonctionnent parfaitement. Mais avec mes "présence aqara 2", impossible de les inclure.
Un amis m'a conseillé de passer sur la version abeille Master, aprés avoir essayé la version stable et la version beta mais rien ne change, impossible à inclure mes capteurs de mouvement et de luminosité.

Je suis passé en mode debug pour les logs (sur les conseils de mon ami).

J'ai testé en faisant la maj du firmware en 3.1c de ma clé, c'est pire, rien ne s'inclus... je suis revenu en 3.1a.

Comment puis-je faire pour que cela refonctionne?
Merci par avance de votre aide,

Stephane.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Salut,
Etapes a suivre:
- mettre le plugin en debug
- mettre la zigate en inclusion
- faire une inclusion
- partager le log AbeilleParser

**Comment by KiwiHC16** [comment]
Pouraais tu essayer avec la version du 18 mars 2020 car il y a des corrections sur ce sujet.

**Comment by StephaneBro** [comment]
Bonjour,

Désolé du temps de réponse mais oui, c'est parfait maintenant. merci de ton suivie et de ton aide.

Bon Confinabeille :)
