### ISSUE TITLE
Xiaomi Detecteur de Mouvement Etat pas à 1 lors d'un mouvement mais retour Luminosité

### ISSUE THREAD

**Issue by Franckybel** [KiwiHC16/Abeille#989]
Bonjour,

J'ai remarqué sur les détecteurs Xioami que le retour de présence n'était pas systématique (l'état ne passe pas à 1) malgré la présence dans la pièce alors que l'info de la luminosité est bien présent.
Voici le graph pris rapidement aujourd'hui, il y a une seule détection de mouvement remontée dans Abeille mais plusieurs de la luminosité, retour Luminosité correspondant bien à une présence.
Présence : 12:20
Luminosité 12:25, 13:20,13:45
Est-ce un disfonctionnement ?ou faut-il modifier des paramètre sur les commandes ?

![image](https://user-images.githubusercontent.com/53462598/74935084-eb646f00-53e7-11ea-974a-b02c2dd2fc83.png)

Merci pour le support

**Comment by KiwiHC16** [comment]
As tu la courbe pour l'état ?

**Comment by Franckybel** [comment]
En fait, tu l'as c'est la barre à 12:20 et pas d'autres points alors que la luminosité est bien affichée sur d'autres horaires

**Comment by Franckybel** [comment]
Bonjour,
Je ferme ce Topic, le problème est identifié et venait du RaspBerry.
La carte microSD a eu des erreurs L/E, après changement de la carte / Restore, tout est revenu stable.
Merci encore
