### ISSUE TITLE
pipe acces rigth are wrong

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#99]
rm /var/www/html/plugins/Abeille/resources/AbeilleDeamon/input
restart plugin
ls -l /var/www/html/plugins/Abeille/resources/AbeilleDeamon/input

pr----x--t 1 www-data www-data 0 févr. 12 11:42 /var/www/html/plugins/Abeille/resources/AbeilleDeamon/input

Bizarre ces droits !

Je suis sur VM debian 9

Est ce que la ligne 19 du fichier fifo.php "if( !posix_mkfifo( $file, $mode ) )" fonctionne corectement ?

**Comment by KiwiHC16** [comment]
Si j'ajoute un chmod, même résultat.

		if( !file_exists( $file ) ) 
		{
			//print "creating pipe on fs\n";
			if( !posix_mkfifo( $file, $mode ) )
			{
				die( "could not create named pipe $file\n" );
			}
			chown($file, "www-data");
            chmod($file, $mode );
		}

**Comment by KiwiHC16** [comment]
posix_mkfifo( $file, 0777 ) ok
posix_mkfifo( $file, '0777' ) NOK

bool posix_mkfifo ( string $pathname , int $mode )
mode should be an int

**Comment by KiwiHC16** [comment]
si je change l appel de 
$fifoIN = new fifo($in, '0777'); 
a
$fifoIN = new fifo($in, 0777);
les acces rigth du fichier sont bons mais le pipe est toujours cassé.

**Comment by edgd1er** [comment]
Ok, a priori tu as trouvé le correctif :)
avec ça, ça devrait corriger le pb. http://php.net/manual/fr/function.intval.php
if( !posix_mkfifo( $file, intval($mode) ) )

je regarde pour le pipe cassé

**Comment by KiwiHC16** [comment]
La solution semble etre 

<?php
    
    ob_implicit_flush();
    
    class fifo {
        var $fp;
        var $to;
        
        /**
         * Create a first In first Out file according to given parameters
         * fifo constructor.
         * @param $file
         * @param $mode /!\ the permissions of the created file are (mode & ~umask).
         */
        function fifo( $file, $mode, $readWrite )
        {
            if( !file_exists( $file ) )
            {
                print "creating fifo $file for $mode\n";
                if( !posix_mkfifo( $file, $mode ) )
                {
                    die( "could not create named pipe $file\n" );
                }
                chown($file, "www-data");
            }
            print "opening fifo $file for $readWrite\n";
            $this->fp = fopen( $file, $readWrite );
        }
        
        function read() {
            // reads a line from a fifo file
            $line = '';
            do
            {
                $c = fgetc( $this->fp );
                if( ($c != '') and ($c != "\n") and !feof( $this->fp ) ) $line .= $c;
            } while( ($c != '') and ($c != "\n") and !feof( $this->fp ) );
            return $line;
        }
        
        function write( $data ) {
            fputs( $this->fp, $data );
            fflush( $this->fp );
        }
        
        function close()
        {
            fclose($this->fp);
        }
        
    }
   
    
    
$file="tata";
// Le 0777 doit être écrit exactement comme cela, il faut le Zero et ce n'est pas une chaine de caractère.
    $pipe = new fifo( "tata", 0777, "w" );
    $pipe->write("coucou");

?>

**Comment by edgd1er** [comment]
/!\  par erreur, j'ai fait un force commit sur ton repo. ne fait pas de pull.
Pour ton prochain push n'hésites pas à forcer....

**Comment by KiwiHC16** [comment]
C'est pour ca que je ne comprenait rien des changements car ils apparaissent sous mon nom. Je viens de corriger de je fais un push su master.

**Comment by KiwiHC16** [comment]
Il y avait une confusion entre le mode 777 et les acces rigth (r / w)
De plus le comportement de mk_fifo est vraiment bizarre. Un 0777 n'est pas la meme chose qu un  777 !!!
Un autre truc que j ai vu c est que le write est bloquant, je ne pense pas que cela soit une bonne idée.(Je fais un issue sur ce point)
Je clos le sujet mais je te laisse voir si mes modifs sont justes. Recupere le master pour avoir mes modifs..
