### ISSUE TITLE
Weima (Wima) Cylinder Door

### ISSUE THREAD

**Issue by KiwiHC16** [KiwiHC16/Abeille#990]

**Comment by KiwiHC16** [comment]
"modelId": "TY0A01"

https://zigbee2mqtt.discourse.group/t/support-new-pine-world-lock/188

(See my notes)

**Comment by KiwiHC16** [comment]
https://community.smartthings.com/t/wima-vima-xiaomi-cylinder-lock-zigbee/131970

**Comment by KiwiHC16** [comment]
https://community.smartthings.com/t/new-xiaomi-anti-theft-door-lock/138200

**Comment by KiwiHC16** [comment]
https://easydomoticz.com/forum/viewtopic.php?t=7446

**Comment by KiwiHC16** [comment]
Zigbee ID: "lumi.lock.v1"

https://zigbee.blakadder.com/Xiaomi_Vima_A6121.html

**Comment by KiwiHC16** [comment]
https://www.youtube.com/watch?v=4ONGgSzKvO0

**Comment by KiwiHC16** [comment]
https://community.home-assistant.io/t/xiaomi-vima-smart-lock-support/61494

```
I have fully tested this cylinder and this is my considerations:

Its a great and really cheap security system: The first line of security is premature detection, and here, the lock produces an alarm if something is inserted (even a picklock) for more than 3 secs that is not an authorized key. Its really cheap because it has similar cost as similar “not smart” lock+5 keys.
The keys seems to have some NFC mechanism
Battery after 3 months (low use) down 3%, so I suppose it can reach more than 2 years (in my case)
If battery is down, the lock works as any not-smart lock: authorized and not-authorized keys can open. and no alarm, manage, etc. is possible.
If gateway is down (i.e. shutdown all electricty due to an atack), smartlock has all the configuration and a timer inside, so authorized and and even temporary authorized keys can open, not-authorized cannot, indepedent of gateway state. Alarms are sended but nobody can receive them. For this reason is so important to has a UPS or battery system to the gateway…
6.The hardware security is like other cylinder. and a tipical force attack can destroy it (as the most robust cylinder) so you need a god external shield to become really secure. See this brute atack here https://www.youtube.com/watch?v=wqfEd-WGL10 135
In general, the system seem with enough quality, and the keys are really robust (at least until now).
```

```
Few days ago I installed zigbb2mqtt with the project to replace the Xaomi Gateway that cause me many connection alerts.

I discovered that zigbee2mqtt support VIMA smart cylinder and now it is supported by Home Assistant as a sensor.
Now in HA it show the number ok key used to open the door… 01, 02, 03… etc.

But after it show the number of key it retain persistent.
I wish to reset its state… to null.
How can I do it?
```

**Comment by KiwiHC16** [comment]
https://www.zigbee2mqtt.io/devices/A6121.html

Ici xiaomi:
https://github.com/aesedepece/zigbee-shepherd-converters/blob/d6b87435dd82750b5f0f2d4cb27677dcb74bd728/converters/fromZigbee.js
```
    xiaomi_lock_report: {
        cid: 'genBasic',
        type: 'attReport',
        convert: (model, msg, publish, options) => {
            if (msg.data.data['65328']) {
                const data = msg.data.data['65328'];
                const state = data.substr(2, 2);
                const action = data.substr(4, 2);
                const keynum = data.substr(6, 2);
                if (state == 11 && action == 7) {
                    // wrong key or not success inserted
                    return {keyerror: true};
                }
                if (state == 12) {
                    if (action == 1) {
                        // successful unlock, sets everything to neutral state
                        return {inserted: keynum, keyerror: false, forgotten: false};
                    }
                    if (action == 11) {
                        // forgot the key in the lock
                        return {forgotten: keynum, keyerror: false};
                    }
                }
            }
        },
    },
```

Avec la version Tuya un read attribut sur FF30
(clusterId=0000&attributId=FF30&Proprio=0000&EP=01)
Repond Attribut Unknown.

**Comment by KiwiHC16** [comment]
```
[2020-02-25 22:27:47][AbeilleParser][debug];type; 8043; (Simple Descriptor Response)(Not Processed); dest: Abeille1; SQN : 46; Status : 00; Short Address : 7b9f; Length : 14; endpoint : 01; profile : 0104 (ZigBee Home Automation (ZHA)); deviceId : 0051 (Smart Plug); bitField : 00; InClusterCount : 05
[2020-02-25 22:27:47][AbeilleParser][debug]In cluster: 0000 - General: Basic
[2020-02-25 22:27:47][AbeilleParser][debug]In cluster: 000A - General: Time
[2020-02-25 22:27:47][AbeilleParser][debug]In cluster: 0004 - General: Groups
[2020-02-25 22:27:47][AbeilleParser][debug]In cluster: 0005 - General: Scenes
PHP Notice:  Undefined index: 0xef00 in /var/www/html/plugins/Abeille/core/class/AbeilleParser.php on line 1368
[2020-02-25 22:27:47][AbeilleParser][debug]In cluster: ef00 - 
[2020-02-25 22:27:47][AbeilleParser][debug]OutClusterCount : 01
[2020-02-25 22:27:47][AbeilleParser][debug]Out cluster: 0019 - General: OTA
```

**Comment by KiwiHC16** [comment]
Version Tuya: TY0A01

```
[2020-02-25 22:27:44][AbeilleParser][debug];Type; 8102; (Attribut Report)(Processed->MQTT); dest: Abeille1; SQN: 55; Src Addr : 7b9f; End Point : 01; Cluster ID : 0000; Attr ID : 0005; Attr Status : 00; Attr Data Type : 42; Attr Size : 0006; Data byte list : ->TY0A01<-
```

**Comment by KiwiHC16** [comment]
https://www.domotique-info.fr/2019/05/tuya-smart-votre-maison-connectee-sans-box-domotique/

Crap pour le zigbee il faut un GW comme "Smart Gateway" TYGWZW-01
Avec ca le lock s'appaire et on le recuperer dans l appli Tuya sur tel.

**Comment by KiwiHC16** [comment]
https://m.alibaba.com/product/60794327104/Mijia-Weima-Smart-home-door-lock.html

**Comment by KiwiHC16** [comment]
WEIMA electro-mechanical cylinder has joined the App of MI, a supplier of smart home system.By operating the cylinder,you can set different scenes.For example,lamps will be turned on and curtain will be shut when the cylinder is unlocked at night.


http://www.r-weima.com/en/About.asp

**Comment by KiwiHC16** [comment]
https://m.youtube.com/watch?v=jqVThVfnkfw

**Comment by KiwiHC16** [comment]
http://www.r-weima.com/en/ShowVideo2.asp

**Comment by KiwiHC16** [comment]
Gateway: https://www.lesalexiens.fr/labo-test-alexa/test-pont-et-ampoule-zigbee-par-zemismart-simple-rapide-et-peu-gourmand/

**Comment by rvitch** [comment]
Bonjour kiwiHC16 
Un article en parle ici : 
https://www.dealabs.com/bons-plans/verrou-de-porte-de-securite-connecte-xiaomi-vima-smart-lock-cylindre-de-securite-intelligent-1808195

Dans les commentaires , un certain ZINZIN059 parle de la maniere dont il à intégré la serrure sur jeedom (via les couleurs de la GW) :

"Pour l'intégrer à jeedom, j'utilise un code couleur du Gateway xiaomi.
Par exemple, lorsque l'alarme est active sur jeedom (plugin alarme), la couleur du Gateway est d'une couleur définie.
Lorsque j'insère une clé, la couleur change et désactive l'alarme immédiatement (et la couleur s'éteint dans le scénario).
Si l'alarme est désactivée, aucune couleur ne s'allume.
Mais le mode alarme du Gateway peut être géré directement avec la serrure."

IL semble donc déja que la GW xiaomi intégre bien cette notion de clef .


Reponse de Kiwi:
- Oui si tu as une Lock Xiaomi alors elle est dans Mi Home (App Xiaomi). Pour la version Tuya (que j'ai) il faut une GW SmartLife et l'App Tuya.
- Je l'ai bien dans le reseua zigbee mais apres je ne perviens pas encore decoder les messages echangés entre l'App et la serrure. Et je ne peux pas faire juste un 'rejeu' car les mesages changent à chaque essai ;-(

**Comment by rvitch** [comment]
Je veux dire que la serrure semble bien liée à la GW xiaomi est gerer les clefs sous mihome..

**Comment by KiwiHC16** [comment]
Oui il semble que la serrure est prise en compte par l appli  Mi Home.
Dans les menus je la trouve mais l integration ne fonctionne pas.
L appli Mi Home ne le trouve pas alors que je vois que la GW la integrée au réseau ZigBee.
Je bloque sur ce point ;-(

Je confirme, il y a deux modeles au moins, un xiaomi et un tuya. Xiomi avec MiHome et Tuya avec App Tuya.

**Comment by olivr2s** [comment]
Bonjour KiwiHC16,
je possède cette serrure et je l'ai ajouté à ma gateway xiaomi et dans l'appli mi home.
Quand tu cherches à l'ajouter dans mi home, tu passes par où, car pour cette serrure, c'est un peu différent que pour les autres capteurs...
D'ailleurs on peut pas la trouver dans la liste du menu principal de mi home, il faut aller sur la gateway qui est dans mi home, puis faire ajouter un capteur pour l'avoir dans la liste.
Si je me rappel, lors de l'intégration sur la gateway, il faut appuyer sur le bouton beige pendant quelques secondes pour que la gateway fasse l'inclusion...

Reponse Kiwi:
Oui c'est ce que j'ai fait mais j'ai une Tuya pas compatible avec MiHome d apres mes tests.

**Comment by KiwiHC16** [comment]
Voici la méthode que j utilise:
![IMG_1115](https://user-images.githubusercontent.com/8549674/75489110-ee47fc80-59b1-11ea-9594-a49a80637ebe.PNG)
Je choisi la GW
![IMG_1116](https://user-images.githubusercontent.com/8549674/75489128-f56f0a80-59b1-11ea-9215-bff9cffbb46c.PNG)
Je vais dans la page appareil
![IMG_1117](https://user-images.githubusercontent.com/8549674/75489131-f738ce00-59b1-11ea-9f1a-f9d25832dbd1.PNG)
Je fais le plus en bas de page
Je choisi la Door Lock
![IMG_1118](https://user-images.githubusercontent.com/8549674/75489134-f9029180-59b1-11ea-85c0-f07a72b93a98.PNG)
Je choisi la Door Lock
![IMG_1119](https://user-images.githubusercontent.com/8549674/75489139-fbfd8200-59b1-11ea-9c1f-768c223c9f99.PNG)
Appuis 5s
Et la rien... (mais je vois en suiffant que l appairage zigbee se fait)

**Comment by KiwiHC16** [comment]
une idée ?

**Comment by olivr2s** [comment]
Pourtant tu fais tout comme prévu...
Moi j'ai bien réussi à l'inclure...
Bizarre...
![Screenshot_2020-02-27-22-54-03-728_com xiaomi smarthome](https://user-images.githubusercontent.com/59806634/75490304-39630f00-59b4-11ea-949e-899f6de6738f.jpg)

**Comment by KiwiHC16** [comment]
Que peux tu faire depuis l app ?
- autorisation utilisation d une clef ?
- sur une plage horaire ?
- alarme ?
- autre ?

**Comment by olivr2s** [comment]
Voici ce que propose l'application...
- Gestion des clés (Noms, activation ou désactivation de la clé)
- Activation ou désactivation des actions locales (autorisation du bouton interne bleu pour gestion sans l'application)
- Activation ou Désactivation de bip de validation de la clé lors de l'insertion (textes en chinois sur l'appli)
Sinon, l'application de la serrure n'est pas capable de savoir dans quel sen on tourne la clé, juste on sait si la clé à été insérée. Si la clé est active on peut la tournée. Si la clé n'est pas active, on peut pas tourner et la serrure bip.
Lorsque l'on tourne la poignée interne pour agir manuellement sur la serrure, ça ne se voit pas sur l'application.
Au final cette serrure est assez basique, elle permet juste de savoir quelle clé et à quelle heure elle est insérée (uniquement) et d'autoriser ou pas la clé à tourner la serrure.
Le gros défaut est de ne pas savoir il on a ouvert ou fermé la serrure.
Après via l'appli, on peut créer des automatisme à partir de certaines actions de la clé pour agir sur la gateway ou autre...

![Screenshot_2020-02-28-07-43-15-576_com xiaomi smarthome 1](https://user-images.githubusercontent.com/59806634/75517827-e9aa3500-59ff-11ea-913f-0f537e0a48af.jpg)
![Screenshot_2020-02-28-07-43-53-044_com xiaomi smarthome 1](https://user-images.githubusercontent.com/59806634/75517846-f595f700-59ff-11ea-89ad-c18b29fcd8a0.jpg)
![Screenshot_2020-02-28-07-44-46-999_com xiaomi smarthome 1](https://user-images.githubusercontent.com/59806634/75517869-00508c00-5a00-11ea-9f79-da3b56d3231b.jpg)

**Comment by olivr2s** [comment]
La capture d'écran de la page des automatisme de l'application mi home ne marche pas, mais dans les déclencheurs en SI, il y a:
- Unlocked legally
- Non-registered key inserted
- Abnormal operation
- Illegal temporary key insered
- Forget to remove key
- Lost key inserted

**Comment by olivr2s** [comment]
Il y a aussi la serrure qui sonne si on laisse une clé trop longtemps dedans

**Comment by frederic34** [comment]
il y a deux modèles, mija ou tuya, lequel testez vous?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1977

https://fcc.report/FCC-ID/2AP8E-A6121

**Comment by KiwiHC16** [comment]
Interessant. Celui que j'ai s'annonce sous le nom "TY0A01" et il est livré avec une notice qui fait reference à l'application Tuya. "TY" du nom, pourrait faire reference à "TuYa". Juste une supposition. Ce qui expliquera que l'appli Xiaomi ne le reconnaisse pas.

Dans le premier lien, l equipement a pour nom: "lumi.lock.v1" ce qui est typique des noms Xiaomi: "lumi.xxx"

J'ai l'impression que c est la meme hard mais le soft est legerement different. Sur le site de Weima on peut voir qu ils ont des partenariats alors ils ont peut être des soft adaptés pour chaque.

**Comment by frederic34** [comment]
J'ai aussi le TY0A01 version tuya

**Comment by KiwiHC16** [comment]
Sur la boite il est indiqué Model: A6121. Ce qui correspond a la certification FCC. Ce qui semble confirmer que c'est le même hard. Et comme il s'associe à la Zigate (probablement) la meme stack zigbee.

**Comment by KiwiHC16** [comment]
Dans la certif FCC c'est une doc xiaomi (et pas Tuya):
[4033606.pdf](https://github.com/KiwiHC16/Abeille/files/4316863/4033606.pdf)

**Comment by KiwiHC16** [comment]
J'ai commandé avec la cagnotte une GW Tuya pour pouvoir sniffer les messages...
A suivre dans quelques semaines...

**Comment by frederic34** [comment]
![image](https://user-images.githubusercontent.com/3624836/76406382-ea40b500-6389-11ea-8c35-7750017f1260.png)

**Comment by KiwiHC16** [comment]
Interessant mais j'ai ces infos. Ce qu'il me manque c'est le dialogue entre la clef et l appli quand par exemple il y a une alarme clef,...

**Comment by frederic34** [comment]
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/127

Kiwi: Pour moi c'est pour la version Xiaomi d'apres le code que j'ai vu dans zigbee2mqtt. Si je fais la meme chose sur la Tuya, elle m'envoie balader.

**Comment by frederic34** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L1353-L1386

Kiwi: xiaomi_lock_report, Tuya ne repond pas a ces demandes.

**Comment by KiwiHC16** [comment]
J'ai recu la GW Tuya, associé la serrure, installé l'App et sniffer les messages.
Probleme, je ne les decode pas encore. J'espère qu'ils ne sont pas cryptés car ils changent à chaques tests.

**Comment by KiwiHC16** [comment]
frederic34, d'où vient la capture d ecran (fond noir) que tu as partagé ?

**Comment by KiwiHC16** [comment]
Par exemple a chaque insertion d'une clef non ajouté j'ai un message de 16 bytes. Comment je decode ?

![Capture d’écran 2020-03-20 à 13 13 59](https://user-images.githubusercontent.com/8549674/77162622-abf37600-6aac-11ea-8257-0cd04de9b0b3.png)

**Comment by KiwiHC16** [comment]
Zoom sur le 16 bytes:
![Capture d’écran 2020-03-20 à 13 15 10](https://user-images.githubusercontent.com/8549674/77162706-d80ef700-6aac-11ea-9fa0-7d95210a594f.png)

**Comment by rvitch** [comment]
salut ben,

Question bête, qu'en ai t'il quand tu ajoutes un nouvelle clef a l'application ?
je vois 2 façons de fonctionnement :
J'imagine  que la clef renvoie un message d'identification et que ce string est consigné quelque part pour être comparé sur les opérations d'insertion/d'ouverture..
Reste à voir quand l'identification de la clef est encodée.
c'est pour ça que je vois 2 modes de fonctionnement possibles:
l'identification de la clef peut être encodé directement et le système ne communiquer qu'avec le message encodé ou bien communiquer avec une identification non encodé et encoder seulement pour consigner l'identification ..
je pense qu'il faut comparer 3 types de messages qu'une clef peut renvoyer :
clef non associé inséree
association de clef 
clef associée insérée
J'ai déjà bossé sur de l'encodage binaire et Hexa dans le passé et je veux bien aider pour
 cette serrure.

**Comment by KiwiHC16** [comment]
Demande d'ajout de clef.
- GW envoie une commande 0x02 à la serrure avec 16 bytes
- la serrure repond avec la commande 0x02 et 16 bytes
- la GW acquitte la reponse
- bit de la serrure pour demander l insertion de la clef.
- Je n'insere pas la clef
- puis apres quelques secondes, un autre echange pour arreter la transaction

![Capture d’écran 2020-03-20 à 14 14 31](https://user-images.githubusercontent.com/8549674/77166775-20321780-6ab5-11ea-8d9d-0880ce95337b.png)

Essai 1:
GW->Ser : 28:f7:ed:b9:e0:ad:62:61:81:3a:ec:c8:ff:b8:cc:0e
Ser->GW: ed:0c:a4:cf:96:e5:9d:c4:fe:fa:4e:17:90:7b:74:1d

Essai2:
GW->Ser: 40:6c:e4:af:6e:29:09:80:fc:d1:f5:75:37:74:17:df
Ser->GW: 63:3b:76:dc:18:17:19:17:64:d9:81:1a:76:f2:ea:85

**Comment by KiwiHC16** [comment]
Lors de l inclusion:
![Capture d’écran 2020-03-20 à 14 43 38](https://user-images.githubusercontent.com/8549674/77169082-32ae5000-6ab9-11ea-9350-b36867327880.png)

_TYST12_C5IaBuQl

**Comment by frederic34** [comment]
> 
> 
> frederic34, d'où vient la capture d ecran (fond noir) que tu as partagé ?

de mon raspberry, un module que j'essayes de mettre aupoint

**Comment by frederic34** [comment]
![Sélection_073](https://user-images.githubusercontent.com/3624836/77174334-2ded9a00-6ac1-11ea-95f5-b34d3ab9af00.png)

sur 0x0007 c'est date heure après 1 er janv 2000
![Sélection_074](https://user-images.githubusercontent.com/3624836/77174348-32b24e00-6ac1-11ea-9e70-ec58bbcfbdf3.png)

**Comment by KiwiHC16** [comment]
Oui c est bien le meme...

**Comment by KiwiHC16** [comment]
Avec un autre analyseur de protocole. Pas plus d'infos.

![Capture d’écran 2020-03-20 à 15 58 07](https://user-images.githubusercontent.com/8549674/77176019-c38a2900-6ac3-11ea-84e8-4f1eb0efcd82.png)

**Comment by rvitch** [comment]
> Demande d'ajout de clef.
> 
> * GW envoie une commande 0x02 à la serrure avec 16 bytes
> * la serrure repond avec la commande 0x02 et 16 bytes
> * la GW acquitte la reponse
> * bit de la serrure pour demander l insertion de la clef.
> * Je n'insere pas la clef
> * puis apres quelques secondes, un autre echange pour arreter la transaction
> 
> ![Capture d’écran 2020-03-20 à 14 14 31](https://user-images.githubusercontent.com/8549674/77166775-20321780-6ab5-11ea-8d9d-0880ce95337b.png)
> 
> Essai 1:
> GW->Ser : 28:f7:ed:b9:e0:ad:62:61:81:3a:ec:c8:ff:b8:cc:0e
> Ser->GW: ed:0c:a4:cf:96:e5:9d:c4:fe:fa:4e:17:90:7b:74:1d
> 
> Essai2:
> GW->Ser: 40:6c:e4:af:6e:29:09:80:fc:d1:f5:75:37:74:17:df
> Ser->GW: 63:3b:76:dc:18:17:19:17:64:d9:81:1a:76:f2:ea:85

Ce que j'imagine avec les infos que nous avons :
La serrure sécurise les transactions avec une clefs de Cryptage de 128 bits (soucis on ne sais pas sous quelle logique).
Avec ce que tu constate : 
GW->ser : La GW envoie la clef de cryptage en 128 bits
Ser->GW reponse avec id serrure crypté
Pour le vérifier, il faudait que cet id crypté ressorte lors des transactions après inclusion.

1 er truc rapide :
Les deux messages que nous avons sont sur 16 mots hexa et après conversion binaires nous donnes un mots de 128bits..donc toutes les transactions sont bien en 128bits.
Reste à trouver sous quelle type de clefs.

**Comment by KiwiHC16** [comment]
[Inclusion.zip](https://github.com/KiwiHC16/Abeille/files/4360414/Inclusion.zip)

A dezip, puis ouvrir dans wireshark.

Si tu trouves des trucs...

**Comment by rvitch** [comment]
Peux tu faire pareil en fonctionnement après inclusion?

**Comment by rvitch** [comment]
J'ai trouvé du contenu sur lequel s'appuyer :
-http://www.r-wima.com/en/OEM.asp#
A priori la clef est directement encodée en 128 bits et communique sous: UART, I2C interface

**Comment by KiwiHC16** [comment]
Je pense que c'est le bus entre le chip sur la clef et le chip dans la serrure.

**Comment by KiwiHC16** [comment]
Delete Key 1 from the App:

[deleteKey1.zip](https://github.com/KiwiHC16/Abeille/files/4360853/deleteKey1.zip)

**Comment by KiwiHC16** [comment]
Demande de Sync depuis l'App:

[synchro.zip](https://github.com/KiwiHC16/Abeille/files/4360860/synchro.zip)

La c est interessant on voit 16 demandes (16 clefs ?) et des chaines de bytes identiques.

**Comment by KiwiHC16** [comment]
Mes notes et analyses :

[Weima Message Key Clef Door Lock.pdf](https://github.com/KiwiHC16/Abeille/files/4360874/Weima.Message.Key.Clef.Door.Lock.pdf)

**Comment by KiwiHC16** [comment]
Apres je peux faire d autres tests en fonction des besoins.
J'ai dans l'idée de faire de rejeu pour voir ce qu'il se passe. Mais il va falloir faire un peu de code alors pas tout de suite.

**Comment by angeck** [comment]
Je suis très intéressé aussi, j'essaye de l'intégrer dans Zigbee2mqtt, je suis avec attention...

**Comment by 667bdrm** [comment]
Did some research of [Weima cylinder electrical part](https://gitlab.com/667bdrm/weima-lock-research/-/blob/master/README.md). Could be useful for someone who want to integrate cylinder with custom mcu

**Comment by 667bdrm** [comment]
> J'ai trouvé du contenu sur lequel s'appuyer :
> -http://www.r-wima.com/en/OEM.asp#
> A priori la clef est directement encodée en 128 bits et communique sous: UART, I2C interface

Looks like it's a Nationz Z8IDA ISO/IEC 7816 capable TPM chip. 
[Datasheet](https://github.com/KiwiHC16/Abeille/files/5250274/1-1P32H23I3.pdf)

Found some ISO 7816 related projects:
https://www.sodnpoo.com/posts.xml/reading_emv(chip_and_pin)_cards_with_an_arduino.xml
https://www.makomk.com/2010/02/04/arduino-based-funcard-programmer/
https://sourceforge.net/p/arduinosclib/wiki/Home/
http://www.smartcardsupply.com/Content/Cards/7816standard.htm

**Comment by rvitch** [comment]
Salut, 
J'ai trouvé un peu d'info dans le code de mqtt2zigbee :

` xiaomi_lock_report: {
        cluster: 'genBasic',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data['65328']) {
                const data = msg.data['65328'];
                const state = data.substr(2, 2);
                const action = data.substr(4, 2);
                const keynum = data.substr(6, 2);
                if (state == 11) {
                    if (action == 1) {
                        // unknown key
                        return {keyerror: true, inserted: 'unknown'};
                    }
                    if (action == 3) {
                        // explicitly disabled key (i.e. reported lost)
                        return {keyerror: true, inserted: keynum};
                    }
                    if (action == 7) {
                        // strange object introduced into the cylinder (e.g. a lock pick)
                        return {keyerror: true, inserted: 'strange'};
                    }
                }
                if (state == 12) {
                    if (action == 1) {
                        return {inserted: keynum};
                    }
                    if (action == 11) {
                        return {forgotten: keynum};

`

**Comment by andrewostroumov** [comment]
Hey guys, is somebody still interesting this topic? I have WEIMA lock A6121 and trying to integrate to z2m with no luck

**Comment by tcharp38** [comment]
Hello. It's a very old story.
I don't have such device myself but if you it, maybe we can try together.
First step is to do to "advanced page" of device to open zigbee assistant.
Sorry, probably no clean translation :(

**Comment by tcharp38** [comment]
Très vieux sujet et plus d'activite depuis un bail.
Je clos mais à reouvrir si ca interesse qqn.
