### ISSUE TITLE
Network Graph: Abeilles pas dans Jeedom

### ISSUE THREAD

**Issue by Soyann** [KiwiHC16/Abeille#991]
Hello

Suite à ta clôture de l'issue #943 , je viens de mettre à jour Abeille via le Master (Vu que mon Jeedom est en stable, je ne peux installer de version beta), et en effet, les erreurs mentionnées ne sont plus d'actualité. Par contre, dans, Network Graph, mes Abeilles enregistrées sont en gris (pas dans l'audit réseau), et elles apparaissent (le nombre est bon) en 'Pas dans Jeedom'. Je viens d'essayer de redémarrer mon système, refaire un Get LQIZ1, rien n'y fait. Une idée pour corriger ce bug?

Merci :)
++

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by KiwiHC16** [comment]
Peux tu partager des captures d'ecran pour m'aider à comprendre ?

**Comment by Soyann** [comment]
Hello,

Voilà:
![image](https://user-images.githubusercontent.com/46709337/75371158-8bc60200-58c6-11ea-8462-f4be96c5c977.png)
![image](https://user-images.githubusercontent.com/46709337/75371200-9d0f0e80-58c6-11ea-9077-beb876cf186e.png)

En te remerciant

**Comment by KiwiHC16** [comment]
Ok je vais regarder.

**Comment by Soyann** [comment]
Hello

Suite à ton message de ce matin, j'ai effectué la mise à jour du Master, et voici mes constatation:
-Dans Network List, ce n'est pas mes abeilles dans le tableau avant de faire une Get LQI Z1:
![image](https://user-images.githubusercontent.com/46709337/75662308-27f95b80-5c6f-11ea-9599-e3c887136d35.png)
-Tant que je n'ai pas fait ce Get LQI Z1, dans Network Graph, j'ai un Workping, et ne peut faire un Refresh Network Information (donc un Get LQI depuis cette page)
-Le problème ci-dessus (Objets en gris, et abeilles remontent 'Pas dans Jeedom') est toujours présent :(

En te remerciant

**Comment by Soyann** [comment]
Bonjour,
Je viens de faire un essai sur ma machine en prod de la dernière version (06/03/20), et j'ai le même résultat..
![image](https://user-images.githubusercontent.com/46709337/76100412-e6e5ac00-5fcc-11ea-9059-9d8cb91c13da.png)

En te remerciant pour tes investigations ;)

**Comment by KiwiHC16** [comment]
J'ai commencé a revoir cette partie pour le multi zigate, mais c est du boulot. A suivre...

**Comment by tcharp38** [comment]
Kiwi.
De mon coté j'avais commencé de revoir la partie "network list".
Tu penses gerer comment le multi-zigate ? Tout afficher me semble une usine à gaz qui sera tres vite illisible. Je pensais n'afficher que la zigate selectionnée, meme si le fichier JSON de stockage pourrait contenir la totale.
Des idées ?

**Comment by KiwiHC16** [comment]
Première étape faire un fichier json par zigate pour passer de l une à l autre sans avoir à attendre la récupération de toutes les infos réseau. Après je ne sais pas encore.

**Comment by Soyann** [comment]
Pour que ce soit lisible, il faudrait un menu déroulant nommé 'Sélection du réseau à afficher:' (entre les boutons 'Get LQI' et 'Source' par exemple) pour: soit n'afficher qu'une Zigate spécifique, soit l'ensemble du réseau (idem sur le Network Graph)

**Comment by tcharp38** [comment]
Ca se tient mais plutot dans l'ordre: selection de la zigate, puis bouton "Get LQI".
D'ailleurs pour ce bouton j'avais déja remonté ce point: "refresh" me semble plus approprié mais quelles sont les recommendations de l"equipe Jeedom ? Parfois en Francais, parfois en Anglais. On peut peut etre progressivement rendre les choses + coherentes ? Tout en Anglais ou tout en Francais ? Kiwi tu en penses quoi ?

**Comment by Soyann** [comment]
+1 pour l'ordre (en effet, plus logique)
A ce compte là, ne laisser qu'un bouton 'Get LQI' à droite du menu déroulant, et il se fera que sur le réseau sélectionné (ou sur l'ensemble des Zigates si on fait un affichage de toutes les Zigates).
Pour le terme 'Get LQI', cela ne me choque pas vu qu'il y a juste à coté la petite phrase explicative (qui serait à modifier en: "Get LQI permet de lancer l interrogation des équipements _sur la zigate sélectionnée_ pour avoir les information Link Quality Indicator (LQI)"; au passage, merci Kiwi pour ces petits indices que tu laisses un peu partout, qui aident grandement à prise en main de ton outil, sans avoir à fouiller dans la doc) ;)

**Comment by tcharp38** [comment]
Oui 1 bouton selection et 1 bouton de refresh.
Quant au "franglais", c'est ton plugin donc ton choix :) Peut etre que tu te limites au Francais. Il me semble que Jeedom depasse les frontieres. Je ne sais pas du coup quelle vision ils recuperent.

Pour changer de sujet et toujours le "network list", pourquoi renommer les adresses courtes 0000 en "ruche" ? En terme de nommage je suis un peu perdu; On voit du "zigate X", "Ruche", et le nom utilisateur de la zigate. Pour moi c'est ce dernier qui devrait sortir en priorité. J'avais creusé le souci de "Ruche affiché à la place du nom" (#890 et #889 d'ailleurs) et cette conversion me semblait en partie coupable. Est-ce que l'adresse 0000 peut etre autre chose que la zigate ?

**Comment by Soyann** [comment]
Hello
Je viens d'installer la dernière version du Master, et je vois que ça a bougé: je n'ai plus mes objets 'Pas dans Jeedom' et retrouve bien toutes mes abeilles :)
Par contre (sinon ça serait pas drôle), trois observations:
-Je note les boutons Zigate 1, Zigate 2... jusqu'à 10. Il me semblait que le multizigate était limité à 5...
-Si on sélectionne une Zigate non configurée, on arrive sur une fenêtre vierge: il serait bien d'arriver à la place sur une page disant que la zigate n'est pas disponible, et avoir la possibilité de sélectionner une autre (ou encore mieux, que les boutons ne soient pas sélectionnable s'il n'y a pas de configuration)
-Avoir une page de visualisation de l'ensemble des Zigates

Merci une fois de plus pour tout ce taf :) Je pense qu'à la prochaine stable, je vais enfin passer le pas sur ma machine principale (en prod), et profiter enfin du MuliZigate (avec en gros soulagement l'extinction de ma box secondaire)

Bien amicalement

++

**Comment by KiwiHC16** [comment]
Tous les sujets doivent etre dans le master. Je clos et on crera des issues spécifiques.
