### ISSUE TITLE
Stable 02/03/2020: Tout reinclure et multi-zigate ?

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#995]
Salut
Je viens de faire l'update officielle Abeille à l'instant.
Sur ma carte de test je n'ai qu'un PiZigate et un capteur temp Xiaomi.
Aucun des deux n'est reconnu. A la place j'ai eu une nouvelle ruche et un autre capteur.
Si je ne me trompe pas la migration n'est pas transparente du tout.

D'autre part cette version est supposée être "multi-zigate" mais je ne vois rien de "multi".
![image](https://user-images.githubusercontent.com/35221038/75774516-729ed480-5d50-11ea-8e97-097927b27b96.png)

Une idée ?

**Comment by KiwiHC16** [comment]
Tu devrais avoir quelque chose comme:

![Capture d’écran 2020-03-03 à 17 31 00](https://user-images.githubusercontent.com/8549674/75797003-c28f9280-5d74-11ea-9504-7bfff5ce5b0a.png)

**Comment by KiwiHC16** [comment]
Je viens d'installer depuis le market et meme soucis que toi !
Tres tres bizarre.
Je regarde.

![Capture d’écran 2020-03-03 à 17 34 41](https://user-images.githubusercontent.com/8549674/75797315-477aac00-5d75-11ea-955d-551e98da8f9c.png)

**Comment by tcharp38** [comment]
Ouf...
Quoi qu'il en soit mon inquietude est surtout vis à vis de la non transparence. Tu risques d'avoir beaucoup de support à faire pour ceux qui migrent.

**Comment by KiwiHC16** [comment]
Je ne comprends pas ce qu'il s'est passé. C'est je ne sais quelle version qui est en stable !!!
Je refais la manip pour la bonne version soit dispo demain.

**Comment by tcharp38** [comment]
Une suggestion: tu restaures/pointe au plus vite sur la derniere version stable avant d'avoir trop de retours "panique". Ca laissera du temps pour refaire une passe non ?

**Comment by KiwiHC16** [comment]
Je ne peux rien faire.
Je mets à dispo une version, le market Jeedom vient la chercher la nuit suivante et elle est dispo le lendemain.

**Comment by tcharp38** [comment]
Ok. Merci pour l'info. Reste à croiser les doigts alors. 
Pour ma part je suis resté volontairement dans une config tres limitée mais je n'imagine pas être obligé de reinclure tous les equipements dans une utilisation plus costaud.

**Comment by KiwiHC16** [comment]
Ca n'impacte pas l'inclusion donc pas de soucis de ce coté là.

**Comment by tcharp38** [comment]
Donc j'ai fait une mauvaise manip aussi de mon côté. La zigate à été reconnu comme une autre "Ruche". Je reverrai ca sur la suite.

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
Je clos. J'ai basculé sur la "Stable 04/03/2020 (Multi Zigate)"
