### ISSUE TITLE
Maj Du 4 Mars 2020 BUG

### ISSUE THREAD

**Issue by djsyl** [KiwiHC16/Abeille#997]
Salut Kiwi c'est la 2 ième fois que suite a mise a jour on se retrouve avec des plantages

C'ette fois ci même l'ip du zigate a été perdu et même en remettant la bonne rien ne fonctionne.

je suis repartit avec une sauvegarde ...

je trouve cela trés désagréable.pour une version stable.

**Comment by KiwiHC16** [comment]
https://forum.jeedom.com/viewtopic.php?f=184&t=33573&sid=5473063691cf238154329eca3b1fc8db

**Comment by djsyl** [comment]
Tu appel ca une issue un renvoi vers l'ancien forum

c'est lamentable une mise a jour et plus rien ne fonctionne ...

perte des paramètres.

obligé de venir ici voir le pourquoi du comment d'un truc qui ne devrait pas arriver sur une version stable ...
il y a des beta pour faire des essais ...
