### ISSUE TITLE
Stable 04/03/2020: port série pas conservé lors de la migration

### ISSUE THREAD

**Issue by tcharp38** [KiwiHC16/Abeille#998]
Je viens de faire migrer sur la version "Stable 04/03/2020 (Multi Zigate)" depuis la stable precedente.
le port serie n'est pas conservé.
![image](https://user-images.githubusercontent.com/35221038/75866531-750f3600-5e05-11ea-848f-e4458fad62bc.png)

**Comment by tcharp38** [comment]
Info complementaire:

Bon en fait je suis perdu. J'ai essayé de reproduire en passant de
 - la "stable 02/03/2020"
 - à la "stable 04/03/2020"
mais cette fois le port est conservé.

Peut etre est ce la passage de la stable dec 2019 vers la 02/03 ou 04/03 qui merde mais la migration n'est pas forcement transparente vu le post #997

**Comment by KiwiHC16** [comment]
Pensez à la cagnotte:
http://kiwihc16.free.fr/index.html#cagnotte
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/KiwiHC16)

**Comment by tcharp38** [comment]
En ce qui me concerne je n'arrive pas à reproduire.
Je clos donc ce point. Qqn ouvrira qqch de similaire si besoin.
